MATE Desktop Environment: active-sensor-libnotify.c File Reference
active-sensor-libnotify.c File Reference
#include "active-sensor-libnotify.h"
Functions
void active_sensor_libnotify_notify_end (ActiveSensor *active_sensor, NotifType notif_type)
void active_sensor_libnotify_notify (ActiveSensor *active_sensor, NotifType notif_type, const gchar *summary, const gchar *message, const gchar *icon_filename, gint timeout_msecs)
Function Documentation
active_sensor_libnotify_notify()
void active_sensor_libnotify_notify (ActiveSensor * active_sensor, NotifType notif_type, const gchar * summary, const gchar * message, const gchar * icon_filename, gint timeout_msecs)
Definition at line 63 of file active-sensor-libnotify.c.
References error, message(), NULL, PACKAGE, and SENSOR_INTERFACE_ERROR.
Referenced by sensors_applet_notify_active_sensor().
active_sensor_libnotify_notify_end()
void active_sensor_libnotify_notify_end (ActiveSensor * active_sensor, NotifType notif_type)
Definition at line 48 of file active-sensor-libnotify.c.
References error, and NULL.
Referenced by sensors_applet_notify_end().