MATE Desktop Environment: active-sensor.c File Reference
active-sensor.c File Reference
#include <glib.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include "active-sensor.h"
#include "sensors-applet-plugins.h"
#include "sensors-applet-settings.h"
Macros
#define SENSOR_VALUE_RANGE(x) ((SensorValueRange)(CLAMP(x, VERY_LOW_SENSOR_VALUE, VERY_HIGH_SENSOR_VALUE)))
#define CAIRO_GRAPH_COLOR_GRADIENT 0.4
Enumerations
enum SensorValueRange {
VERY_LOW_SENSOR_VALUE = 0 , LOW_SENSOR_VALUE , NORMAL_SENSOR_VALUE , HIGH_SENSOR_VALUE ,
VERY_HIGH_SENSOR_VALUE
}
Functions
void active_sensor_alarm_off (ActiveSensor *active_sensor, NotifType notif_type)
gint active_sensor_compare (ActiveSensor *a, ActiveSensor *b)
void active_sensor_destroy (ActiveSensor *active_sensor)
void active_sensor_update_graph_dimensions (ActiveSensor *as, gint sizes[2])
ActiveSensor * active_sensor_new (SensorsApplet *sensors_applet, GtkTreeRowReference *sensor_row)
void active_sensor_update (ActiveSensor *active_sensor, SensorsApplet *sensors_applet)
void active_sensor_icon_changed (ActiveSensor *active_sensor, SensorsApplet *sensors_applet)
Macro Definition Documentation
CAIRO_GRAPH_COLOR_GRADIENT
#define CAIRO_GRAPH_COLOR_GRADIENT 0.4
Definition at line 48 of file active-sensor.c.
SENSOR_VALUE_RANGE
#define SENSOR_VALUE_RANGE (x) ((SensorValueRange)(CLAMP(x, VERY_LOW_SENSOR_VALUE, VERY_HIGH_SENSOR_VALUE)))
Definition at line 46 of file active-sensor.c.
Enumeration Type Documentation
SensorValueRange
enum SensorValueRange
Enumerator
VERY_LOW_SENSOR_VALUE
LOW_SENSOR_VALUE
NORMAL_SENSOR_VALUE
HIGH_SENSOR_VALUE
VERY_HIGH_SENSOR_VALUE
Definition at line 37 of file active-sensor.c.
Function Documentation
active_sensor_alarm_off()
void active_sensor_alarm_off (ActiveSensor * active_sensor, NotifType notif_type)
Definition at line 107 of file active-sensor.c.
References _ActiveSensor::alarm_command, _ActiveSensor::alarm_timeout_id, LOW_ALARM, and sensors_applet_notify_end().
Referenced by sensors_applet_alarm_off().
active_sensor_compare()
gint active_sensor_compare (ActiveSensor * a, ActiveSensor * b)
Compares two ActiveSensors and returns -1 if a comes before b in the tree, 0 if refer to same row, 1 if b comes before a
Definition at line 192 of file active-sensor.c.
References b, and _ActiveSensor::sensor_row.
Referenced by sensors_applet_reorder_sensors(), and sensors_applet_sensor_enabled().
active_sensor_destroy()
void active_sensor_destroy (ActiveSensor * active_sensor)
Definition at line 325 of file active-sensor.c.
References _ActiveSensor::graph, _ActiveSensor::graph_frame, _ActiveSensor::icon, _ActiveSensor::label, _ActiveSensor::sensor_values, and _ActiveSensor::value.
Referenced by sensors_applet_sensor_disabled().
active_sensor_icon_changed()
void active_sensor_icon_changed (ActiveSensor * active_sensor, SensorsApplet * sensors_applet)
Definition at line 776 of file active-sensor.c.
References ICON_PIXBUF_COLUMN, _ActiveSensor::sensor_row, SENSOR_TYPE_COLUMN, and _SensorsApplet::sensors.
Referenced by sensors_applet_icon_changed().
active_sensor_new()
ActiveSensor * active_sensor_new (SensorsApplet * sensors_applet, GtkTreeRowReference * sensor_row)
Definition at line 409 of file active-sensor.c.
References _ActiveSensor::alarm_timeout_id, _SensorsApplet::applet, FALSE, _ActiveSensor::graph, _ActiveSensor::graph_frame, GRAPH_SIZE, _ActiveSensor::icon, _ActiveSensor::label, mate_panel_applet_get_orient(), MatePanelAppletOrient, NULL, NUM_ALARMS, _ActiveSensor::sensor_row, _ActiveSensor::sensors_applet, _SensorsApplet::settings, _SensorsApplet::size, _ActiveSensor::updated, and _ActiveSensor::value.
Referenced by sensors_applet_sensor_enabled().
active_sensor_update()
void active_sensor_update (ActiveSensor * active_sensor, SensorsApplet * sensors_applet)
Definition at line 483 of file active-sensor.c.
References _, ALARM_ENABLE_COLUMN, CELSIUS, CURRENT_SENSOR, DISPLAY_GRAPH, DISPLAY_ICON, DISPLAY_ICON_WITH_VALUE, DISPLAY_LABEL_WITH_VALUE, DISPLAY_MODE, DISPLAY_VALUE, ENABLE_COLUMN, error, FAHRENHEIT, FALSE, FAN_SENSOR, FONT_SIZE, _ActiveSensor::graph, _ActiveSensor::graph_color, GRAPH_COLOR_COLUMN, HIDE_UNITS, HIGH_ALARM, HIGH_VALUE_COLUMN, _ActiveSensor::icon, ICON_PIXBUF_COLUMN, ID_COLUMN, INTERFACE_COLUMN, KELVIN, _ActiveSensor::label, LABEL_COLUMN, LOW_ALARM, LOW_VALUE_COLUMN, MULTIPLIER_COLUMN, NULL, OFFSET_COLUMN, PATH_COLUMN, _ActiveSensor::sensor_high_value, SENSOR_INTERFACE_ERROR, _ActiveSensor::sensor_low_value, _ActiveSensor::sensor_row, SENSOR_TYPE_COLUMN, _ActiveSensor::sensor_values, _SensorsApplet::sensors, sensors_applet_convert_temperature(), sensors_applet_notify_active_sensor(), sensors_applet_plugins_get_sensor_value_func(), _SensorsApplet::settings, _SensorsApplet::show_tooltip, TEMP_SENSOR, TEMPERATURE_SCALE, TRUE, UNITS_CELSIUS, UNITS_CURRENT, UNITS_FAHRENHEIT, UNITS_RPM, UNITS_VOLTAGE, _ActiveSensor::updated, _ActiveSensor::value, and VOLTAGE_SENSOR.
Referenced by sensors_applet_sensor_enabled(), sensors_applet_update_active_sensors(), and sensors_applet_update_sensor().
active_sensor_update_graph_dimensions()
void active_sensor_update_graph_dimensions (ActiveSensor * as, gint sizes[2])
Definition at line 402 of file active-sensor.c.
References _ActiveSensor::graph.
Referenced by sensors_applet_graph_size_changed().