MATE Desktop Environment: alsa-element.h File Reference
alsa-element.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <alsa/asoundlib.h>
#include "alsa-types.h"
Classes
struct _AlsaElementInterface
Macros
#define ALSA_TYPE_ELEMENT (alsa_element_get_type ())
#define ALSA_ELEMENT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ALSA_TYPE_ELEMENT, AlsaElement))
#define ALSA_IS_ELEMENT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ALSA_TYPE_ELEMENT))
#define ALSA_ELEMENT_GET_INTERFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), ALSA_TYPE_ELEMENT, AlsaElementInterface))
Typedefs
typedef struct _AlsaElementInterface AlsaElementInterface
Functions
GType alsa_element_get_type (void)
snd_mixer_elem_t * alsa_element_get_snd_element (AlsaElement *element)
void alsa_element_set_snd_element (AlsaElement *element, snd_mixer_elem_t *el)
gboolean alsa_element_load (AlsaElement *element)
void alsa_element_close (AlsaElement *element)
Macro Definition Documentation
ALSA_ELEMENT
#define ALSA_ELEMENT (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ALSA_TYPE_ELEMENT, AlsaElement))
Definition at line 31 of file alsa-element.h.
ALSA_ELEMENT_GET_INTERFACE
#define ALSA_ELEMENT_GET_INTERFACE (o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), ALSA_TYPE_ELEMENT, AlsaElementInterface))
Definition at line 35 of file alsa-element.h.
ALSA_IS_ELEMENT
#define ALSA_IS_ELEMENT (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ALSA_TYPE_ELEMENT))
Definition at line 33 of file alsa-element.h.
ALSA_TYPE_ELEMENT
#define ALSA_TYPE_ELEMENT (alsa_element_get_type ())
Definition at line 29 of file alsa-element.h.
Typedef Documentation
AlsaElementInterface
typedef struct _AlsaElementInterface AlsaElementInterface
Definition at line 38 of file alsa-element.h.
Function Documentation
alsa_element_close()
void alsa_element_close (AlsaElement * element)
Definition at line 56 of file alsa-element.c.
References ALSA_ELEMENT_GET_INTERFACE, alsa_element_set_snd_element(), ALSA_IS_ELEMENT, _AlsaElementInterface::close, and NULL.
Referenced by alsa_stream_remove_all(), and alsa_stream_remove_elements().
alsa_element_get_snd_element()
snd_mixer_elem_t * alsa_element_get_snd_element (AlsaElement * element)
Definition at line 32 of file alsa-element.c.
References ALSA_ELEMENT_GET_INTERFACE, ALSA_IS_ELEMENT, and NULL.
alsa_element_get_type()
GType alsa_element_get_type (void)
alsa_element_load()
gboolean alsa_element_load (AlsaElement * element)
Definition at line 48 of file alsa-element.c.
References ALSA_ELEMENT_GET_INTERFACE, ALSA_IS_ELEMENT, and FALSE.
Referenced by alsa_stream_load_elements().
alsa_element_set_snd_element()
void alsa_element_set_snd_element (AlsaElement * element, snd_mixer_elem_t * el)
Definition at line 40 of file alsa-element.c.
References ALSA_ELEMENT_GET_INTERFACE, and ALSA_IS_ELEMENT.
Referenced by alsa_element_close().