MATE Desktop Environment: alsa-device.c File Reference
alsa-device.c File Reference
#include <string.h>
#include <libintl.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <glib-object.h>
#include <alsa/asoundlib.h>
#include <libmatemixer/matemixer.h>
#include "alsa-compat.h"
#include "alsa-constants.h"
#include "alsa-device.h"
#include "alsa-element.h"
#include "alsa-stream.h"
#include "alsa-stream-control.h"
#include "alsa-stream-input-control.h"
#include "alsa-stream-output-control.h"
#include "alsa-switch.h"
#include "alsa-switch-option.h"
#include "alsa-toggle.h"
Macros
#define ALSA_DEVICE_ICON "audio-card"
#define ALSA_STREAM_CONTROL_GET_SCORE(c)
#define ALSA_STREAM_CONTROL_SET_SCORE(c, score)
#define ALSA_STREAM_DEFAULT_CONTROL_GET_SCORE(s) (ALSA_STREAM_CONTROL_GET_SCORE (alsa_stream_get_default_control (ALSA_STREAM (s))))
Enumerations
enum { CLOSED , N_SIGNALS }
Functions
AlsaDevice * alsa_device_new (const gchar *name, const gchar *label)
gboolean alsa_device_open (AlsaDevice *device)
gboolean alsa_device_is_open (AlsaDevice *device)
void alsa_device_close (AlsaDevice *device)
void alsa_device_load (AlsaDevice *device)
AlsaStream * alsa_device_get_input_stream (AlsaDevice *device)
AlsaStream * alsa_device_get_output_stream (AlsaDevice *device)
Macro Definition Documentation
ALSA_DEVICE_ICON
#define ALSA_DEVICE_ICON "audio-card"
Definition at line 39 of file alsa-device.c.
ALSA_STREAM_CONTROL_GET_SCORE
#define ALSA_STREAM_CONTROL_GET_SCORE (c)
Value:
        (GPOINTER_TO_INT (g_object_get_data (G_OBJECT (c),      \
                                             "__matemixer_alsa_control_score")))
Definition at line 41 of file alsa-device.c.
ALSA_STREAM_CONTROL_SET_SCORE
#define ALSA_STREAM_CONTROL_SET_SCORE (c, score)
Value:
        (g_object_set_data (G_OBJECT (c),                       \
                            "__matemixer_alsa_control_score",   \
                            GINT_TO_POINTER (score)))
Definition at line 45 of file alsa-device.c.
ALSA_STREAM_DEFAULT_CONTROL_GET_SCORE
#define ALSA_STREAM_DEFAULT_CONTROL_GET_SCORE (s) (ALSA_STREAM_CONTROL_GET_SCORE (alsa_stream_get_default_control (ALSA_STREAM (s))))
Definition at line 50 of file alsa-device.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CLOSED
N_SIGNALS
Definition at line 65 of file alsa-device.c.
Function Documentation
alsa_device_close()
void alsa_device_close (AlsaDevice * device)
Definition at line 326 of file alsa-device.c.
References ALSA_IS_DEVICE, alsa_stream_has_controls_or_switches(), alsa_stream_remove_all(), CLOSED, MATE_MIXER_STREAM, mate_mixer_stream_get_name(), name, NULL, _AlsaDevice::priv, and TRUE.
alsa_device_get_input_stream()
AlsaStream * alsa_device_get_input_stream (AlsaDevice * device)
Definition at line 403 of file alsa-device.c.
References ALSA_IS_DEVICE, alsa_stream_has_controls_or_switches(), NULL, _AlsaDevice::priv, and TRUE.
alsa_device_get_output_stream()
AlsaStream * alsa_device_get_output_stream (AlsaDevice * device)
Definition at line 416 of file alsa-device.c.
References ALSA_IS_DEVICE, alsa_stream_has_controls_or_switches(), NULL, _AlsaDevice::priv, and TRUE.
alsa_device_is_open()
gboolean alsa_device_is_open (AlsaDevice * device)
Definition at line 315 of file alsa-device.c.
References ALSA_IS_DEVICE, FALSE, NULL, _AlsaDevice::priv, and TRUE.
alsa_device_load()
void alsa_device_load (AlsaDevice * device)
Definition at line 364 of file alsa-device.c.
References ALSA_IS_DEVICE, error, NULL, and _AlsaDevice::priv.
alsa_device_new()
AlsaDevice * alsa_device_new (const gchar * name, const gchar * label)
Definition at line 228 of file alsa-device.c.
References ALSA_DEVICE_ICON, alsa_stream_new(), ALSA_TYPE_DEVICE, label, MATE_MIXER_DEVICE, MATE_MIXER_DIRECTION_INPUT, MATE_MIXER_DIRECTION_OUTPUT, name, NULL, and _AlsaDevice::priv.
alsa_device_open()
gboolean alsa_device_open (AlsaDevice * device)
Definition at line 261 of file alsa-device.c.
References ALSA_IS_DEVICE, FALSE, MATE_MIXER_DEVICE, mate_mixer_device_get_label(), mate_mixer_device_get_name(), name, NULL, _AlsaDevice::priv, and TRUE.