MATE Desktop Environment: alsa-stream-control.h File Reference
alsa-stream-control.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <alsa/asoundlib.h>
#include <libmatemixer/matemixer.h>
#include "alsa-types.h"
Classes
struct AlsaControlData
struct _AlsaStreamControl
struct _AlsaStreamControlClass
Macros
#define ALSA_TYPE_STREAM_CONTROL (alsa_stream_control_get_type ())
#define ALSA_STREAM_CONTROL(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ALSA_TYPE_STREAM_CONTROL, AlsaStreamControl))
#define ALSA_IS_STREAM_CONTROL(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ALSA_TYPE_STREAM_CONTROL))
#define ALSA_STREAM_CONTROL_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ALSA_TYPE_STREAM_CONTROL, AlsaStreamControlClass))
#define ALSA_IS_STREAM_CONTROL_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ALSA_TYPE_STREAM_CONTROL))
#define ALSA_STREAM_CONTROL_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ALSA_TYPE_STREAM_CONTROL, AlsaStreamControlClass))
Typedefs
typedef struct _AlsaStreamControlClass AlsaStreamControlClass
typedef struct _AlsaStreamControlPrivate AlsaStreamControlPrivate
Functions
GType alsa_stream_control_get_type (void)
AlsaControlData * alsa_stream_control_get_data (AlsaStreamControl *control)
void alsa_stream_control_set_data (AlsaStreamControl *control, AlsaControlData *data)
Macro Definition Documentation
ALSA_IS_STREAM_CONTROL
#define ALSA_IS_STREAM_CONTROL (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ALSA_TYPE_STREAM_CONTROL))
Definition at line 50 of file alsa-stream-control.h.
ALSA_IS_STREAM_CONTROL_CLASS
#define ALSA_IS_STREAM_CONTROL_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), ALSA_TYPE_STREAM_CONTROL))
Definition at line 54 of file alsa-stream-control.h.
ALSA_STREAM_CONTROL
#define ALSA_STREAM_CONTROL (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ALSA_TYPE_STREAM_CONTROL, AlsaStreamControl))
Definition at line 48 of file alsa-stream-control.h.
ALSA_STREAM_CONTROL_CLASS
#define ALSA_STREAM_CONTROL_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), ALSA_TYPE_STREAM_CONTROL, AlsaStreamControlClass))
Definition at line 52 of file alsa-stream-control.h.
ALSA_STREAM_CONTROL_GET_CLASS
#define ALSA_STREAM_CONTROL_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), ALSA_TYPE_STREAM_CONTROL, AlsaStreamControlClass))
Definition at line 56 of file alsa-stream-control.h.
ALSA_TYPE_STREAM_CONTROL
#define ALSA_TYPE_STREAM_CONTROL (alsa_stream_control_get_type ())
Definition at line 46 of file alsa-stream-control.h.
Typedef Documentation
AlsaStreamControlClass
typedef struct _AlsaStreamControlClass AlsaStreamControlClass
Definition at line 59 of file alsa-stream-control.h.
AlsaStreamControlPrivate
typedef struct _AlsaStreamControlPrivate AlsaStreamControlPrivate
Definition at line 60 of file alsa-stream-control.h.
Function Documentation
alsa_stream_control_get_data()
AlsaControlData * alsa_stream_control_get_data (AlsaStreamControl * control)
Definition at line 145 of file alsa-stream-control.c.
References ALSA_IS_STREAM_CONTROL, NULL, and _AlsaStreamControl::priv.
alsa_stream_control_get_type()
GType alsa_stream_control_get_type (void)
alsa_stream_control_set_data()
void alsa_stream_control_set_data (AlsaStreamControl * control, AlsaControlData * data)
Definition at line 153 of file alsa-stream-control.c.
References _mate_mixer_create_channel_mask(), _mate_mixer_stream_control_set_balance(), _mate_mixer_stream_control_set_fade(), _mate_mixer_stream_control_set_flags(), _mate_mixer_stream_control_set_mute(), ALSA_IS_STREAM_CONTROL, data, FALSE, MATE_MIXER_CHANNEL_MASK_HAS_BACK, MATE_MIXER_CHANNEL_MASK_HAS_FRONT, MATE_MIXER_CHANNEL_MASK_HAS_LEFT, MATE_MIXER_CHANNEL_MASK_HAS_RIGHT, MATE_MIXER_INFINITY, MATE_MIXER_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_CAN_BALANCE, MATE_MIXER_STREAM_CONTROL_CAN_FADE, MATE_MIXER_STREAM_CONTROL_HAS_DECIBEL, MATE_MIXER_STREAM_CONTROL_MUTE_READABLE, MATE_MIXER_STREAM_CONTROL_MUTE_WRITABLE, MATE_MIXER_STREAM_CONTROL_NO_FLAGS, MATE_MIXER_STREAM_CONTROL_VOLUME_READABLE, MATE_MIXER_STREAM_CONTROL_VOLUME_WRITABLE, NULL, _AlsaStreamControl::priv, and TRUE.