MATE Desktop Environment: app-shell.c File Reference
app-shell.c File Reference
#include <libmate-desktop/mate-desktop-item.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <string.h>
#include <stdlib.h>
#include <glib/gi18n-lib.h>
#include "app-shell.h"
#include "shell-window.h"
#include "app-resizer.h"
#include "slab-section.h"
#include "slab-mate-util.h"
#include "search-bar.h"
#include "application-tile.h"
#include "themed-icon.h"
Macros
#define TILE_EXEC_NAME "Tile_desktop_exec_name"
#define CC_SCHEMA "org.mate.control-center"
#define EXIT_SHELL_ON_ACTION_START "cc-exit-shell-on-action-start"
#define EXIT_SHELL_ON_ACTION_HELP "cc-exit-shell-on-action-help"
#define EXIT_SHELL_ON_ACTION_ADD_REMOVE "cc-exit-shell-on-action-add-remove"
#define EXIT_SHELL_ON_ACTION_UPGRADE_UNINSTALL "cc-exit-shell-on-action-upgrade-uninstall"
Functions
gboolean regenerate_categories (AppShellData *app_data)
void hide_shell (AppShellData *app_data)
void show_shell (AppShellData *app_data)
gboolean create_main_window (AppShellData *app_data, const gchar *app_name, const gchar *title, const gchar *window_icon, gint width, gint height, gboolean hidden)
void layout_shell (AppShellData *app_data, const gchar *filter_title, const gchar *groups_title, const gchar *actions_title, GSList *actions, void(*actions_handler)(Tile *, TileEvent *, gpointer))
AppShellData * appshelldata_new (const gchar *menu_name, GtkIconSize icon_size, gboolean show_tile_generic_name, gboolean exit_on_close, gint new_apps_max_items)
void generate_categories (AppShellData *app_data)
Macro Definition Documentation
CC_SCHEMA
#define CC_SCHEMA "org.mate.control-center"
Definition at line 47 of file app-shell.c.
EXIT_SHELL_ON_ACTION_ADD_REMOVE
#define EXIT_SHELL_ON_ACTION_ADD_REMOVE "cc-exit-shell-on-action-add-remove"
Definition at line 50 of file app-shell.c.
EXIT_SHELL_ON_ACTION_HELP
#define EXIT_SHELL_ON_ACTION_HELP "cc-exit-shell-on-action-help"
Definition at line 49 of file app-shell.c.
EXIT_SHELL_ON_ACTION_START
#define EXIT_SHELL_ON_ACTION_START "cc-exit-shell-on-action-start"
Definition at line 48 of file app-shell.c.
EXIT_SHELL_ON_ACTION_UPGRADE_UNINSTALL
#define EXIT_SHELL_ON_ACTION_UPGRADE_UNINSTALL "cc-exit-shell-on-action-upgrade-uninstall"
Definition at line 51 of file app-shell.c.
TILE_EXEC_NAME
#define TILE_EXEC_NAME "Tile_desktop_exec_name"
Definition at line 46 of file app-shell.c.
Function Documentation
appshelldata_new()
AppShellData * appshelldata_new (const gchar * menu_name, GtkIconSize icon_size, gboolean show_tile_generic_name, gboolean exit_on_close, gint new_apps_max_items)
Definition at line 871 of file app-shell.c.
References _, CC_SCHEMA, _AppShellData::exit_on_close, _AppShellData::icon_size, NewAppConfig::max_items, _AppShellData::menu_name, NewAppConfig::name, _AppShellData::new_apps, _AppShellData::settings, _AppShellData::show_tile_generic_name, _AppShellData::stop_incremental_relayout, and TRUE.
create_main_window()
gboolean create_main_window (AppShellData * app_data, const gchar * app_name, const gchar * title, const gchar * window_icon, gint width, gint height, gboolean hidden)
Definition at line 122 of file app-shell.c.
References _AppShellData::main_app, _AppShellData::shell, show_shell(), and TRUE.
Referenced by ProcmanApp::on_startup().
generate_categories()
void generate_categories (AppShellData * app_data)
Definition at line 889 of file app-shell.c.
References _, category, error, FALSE, _AppShellData::hash, item, matemenu_tree_directory_get_name(), matemenu_tree_directory_iter(), MATEMENU_TREE_FLAGS_NONE, matemenu_tree_get_root_directory(), MATEMENU_TREE_ITEM_DIRECTORY, MATEMENU_TREE_ITEM_ENTRY, MATEMENU_TREE_ITEM_INVALID, matemenu_tree_item_unref(), matemenu_tree_iter_get_directory(), matemenu_tree_iter_next(), matemenu_tree_iter_unref(), matemenu_tree_load_sync(), matemenu_tree_new(), NewAppConfig::max_items, _AppShellData::menu_name, _AppShellData::new_apps, NULL, _AppShellData::tree, TRUE, and type.
Referenced by regenerate_categories().
hide_shell()
void hide_shell (AppShellData * app_data)
Definition at line 95 of file app-shell.c.
References _AppShellData::main_app, _AppShellData::main_app_window_x, and _AppShellData::main_app_window_y.
Referenced by handle_static_action_clicked().
layout_shell()
void layout_shell (AppShellData * app_data, const gchar * filter_title, const gchar * groups_title, const gchar * actions_title, GSList * actions, void(*)(Tile *, TileEvent *, gpointer) actions_handler)
Definition at line 246 of file app-shell.c.
References _AppShellData::actions_section, APP_RESIZER, app_resizer_new(), app_resizer_set_table_cache(), _AppShellData::cached_tables_list, _AppShellData::category_layout, FALSE, _AppShellData::filter_section, _AppShellData::groups_section, NULL, num_cols, _AppShellData::shell, SHELL_WINDOW, shell_window_new(), shell_window_set_contents(), SIZING_SCREEN_WIDTH_LARGE, SIZING_SCREEN_WIDTH_LARGE_NUMCOLS, SIZING_SCREEN_WIDTH_MEDIUM, SIZING_SCREEN_WIDTH_MEDIUM_NUMCOLS, SIZING_SCREEN_WIDTH_SMALL_NUMCOLS, _AppShellData::static_actions, and TRUE.
regenerate_categories()
gboolean regenerate_categories (AppShellData * app_data)
Definition at line 837 of file app-shell.c.
References FALSE, and generate_categories().
show_shell()
void show_shell (AppShellData * app_data)
Definition at line 105 of file app-shell.c.
References _AppShellData::actions_section, _AppShellData::main_app, _AppShellData::main_app_window_shown_once, _AppShellData::main_app_window_x, _AppShellData::main_app_window_y, _AppShellData::shell, SHELL_WINDOW, shell_window_clear_resize_handler(), _AppShellData::static_actions, and TRUE.
Referenced by create_main_window().