MATE Desktop Environment: appearance-themes.h File Reference
appearance-themes.h File Reference
Functions
void themes_init (AppearanceData *data)
void themes_shutdown (AppearanceData *data)
Function Documentation
themes_init()
void themes_init (AppearanceData * data)
Definition at line 976 of file appearance-themes.c.
References _, appearance_capplet_get_widget, COL_LABEL, COL_NAME, COL_THUMBNAIL, CURSOR_SIZE_KEY, CURSOR_THEME_KEY, CUSTOM_THEME_NAME, data, DESKTOP_FONT_KEY, DOCUMENT_FONT_KEY, FALSE, GTK_FONT_KEY, MARCO_THEME_KEY, mate_theme_info_register_theme_change(), mate_theme_init(), mate_theme_meta_info_find_all(), MONOSPACE_FONT_KEY, MORE_THEMES_URL_KEY, _MateThemeMetaInfo::name, NULL, NUM_COLS, _MateThemeMetaInfo::readable_name, WINDOW_TITLE_FONT_KEY, and WP_FILE_KEY.
Referenced by main().
themes_shutdown()
void themes_shutdown (AppearanceData * data)
Definition at line 1135 of file appearance-themes.c.
References data, and mate_theme_meta_info_free().