MATE Desktop Environment: application-tile.c File Reference
application-tile.c File Reference
#include "application-tile.h"
#include "config.h"
#include <string.h>
#include <glib.h>
#include <glib/gi18n-lib.h>
#include <glib/gstdio.h>
#include <unistd.h>
#include "slab-mate-util.h"
#include "libslab-utils.h"
#include "bookmark-agent.h"
#include "themed-icon.h"
Enumerations
enum StartupStatus { APP_IN_USER_STARTUP_DIR , APP_NOT_IN_STARTUP_DIR , APP_NOT_ELIGIBLE }
enum { PROP_0 , PROP_APPLICATION_NAME , PROP_APPLICATION_DESCRIPTION }
Functions
GtkWidget * application_tile_new (const gchar *desktop_item_id)
GtkWidget * application_tile_new_full (const gchar *desktop_item_id, GtkIconSize image_size, gboolean show_generic_name)
MateDesktopItem * application_tile_get_desktop_item (ApplicationTile *tile)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_APPLICATION_NAME
PROP_APPLICATION_DESCRIPTION
Definition at line 84 of file application-tile.c.
StartupStatus
enum StartupStatus
Enumerator
APP_IN_USER_STARTUP_DIR
APP_NOT_IN_STARTUP_DIR
APP_NOT_ELIGIBLE
Definition at line 35 of file application-tile.c.
Function Documentation
application_tile_get_desktop_item()
MateDesktopItem * application_tile_get_desktop_item (ApplicationTile * tile)
Definition at line 615 of file application-tile.c.
application_tile_new()
GtkWidget * application_tile_new (const gchar * desktop_item_id)
Definition at line 117 of file application-tile.c.
References application_tile_new_full(), and TRUE.
application_tile_new_full()
GtkWidget * application_tile_new_full (const gchar * desktop_item_id, GtkIconSize image_size, gboolean show_generic_name)
Definition at line 123 of file application-tile.c.
References APPLICATION_TILE_TYPE, load_desktop_item_from_unknown(), mate_desktop_item_get_entry_type(), mate_desktop_item_get_location(), MATE_DESKTOP_ITEM_TYPE_APPLICATION, mate_desktop_item_unref(), and NULL.
Referenced by application_tile_new().