MATE Desktop Environment: application-tile.h File Reference
application-tile.h File Reference
#include "nameplate-tile.h"
#include <glib.h>
#include <libmate-desktop/mate-desktop-item.h>
Classes
struct ApplicationTile
struct ApplicationTileClass
Macros
#define APPLICATION_TILE_TYPE (application_tile_get_type ())
#define APPLICATION_TILE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), APPLICATION_TILE_TYPE, ApplicationTile))
#define APPLICATION_TILE_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), APPLICATION_TILE_TYPE, ApplicationTileClass))
#define IS_APPLICATION_TILE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), APPLICATION_TILE_TYPE))
#define IS_APPLICATION_TILE_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), APPLICATION_TILE_TYPE))
#define APPLICATION_TILE_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), APPLICATION_TILE_TYPE, ApplicationTileClass))
#define APPLICATION_TILE_ACTION_START 0
#define APPLICATION_TILE_ACTION_HELP 1
#define APPLICATION_TILE_ACTION_UPDATE_MAIN_MENU 2
#define APPLICATION_TILE_ACTION_UPDATE_STARTUP 3
#define APPLICATION_TILE_ACTION_UPGRADE_PACKAGE 4
#define APPLICATION_TILE_ACTION_UNINSTALL_PACKAGE 5
Functions
GType application_tile_get_type (void)
GtkWidget * application_tile_new (const gchar *desktop_item_id)
GtkWidget * application_tile_new_full (const gchar *desktop_item_id, GtkIconSize icon_size, gboolean show_generic_name)
MateDesktopItem * application_tile_get_desktop_item (ApplicationTile *tile)
Macro Definition Documentation
APPLICATION_TILE
#define APPLICATION_TILE (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), APPLICATION_TILE_TYPE, ApplicationTile))
Definition at line 32 of file application-tile.h.
APPLICATION_TILE_ACTION_HELP
#define APPLICATION_TILE_ACTION_HELP 1
Definition at line 38 of file application-tile.h.
APPLICATION_TILE_ACTION_START
#define APPLICATION_TILE_ACTION_START 0
Definition at line 37 of file application-tile.h.
APPLICATION_TILE_ACTION_UNINSTALL_PACKAGE
#define APPLICATION_TILE_ACTION_UNINSTALL_PACKAGE 5
Definition at line 42 of file application-tile.h.
APPLICATION_TILE_ACTION_UPDATE_MAIN_MENU
#define APPLICATION_TILE_ACTION_UPDATE_MAIN_MENU 2
Definition at line 39 of file application-tile.h.
APPLICATION_TILE_ACTION_UPDATE_STARTUP
#define APPLICATION_TILE_ACTION_UPDATE_STARTUP 3
Definition at line 40 of file application-tile.h.
APPLICATION_TILE_ACTION_UPGRADE_PACKAGE
#define APPLICATION_TILE_ACTION_UPGRADE_PACKAGE 4
Definition at line 41 of file application-tile.h.
APPLICATION_TILE_CLASS
#define APPLICATION_TILE_CLASS (c) (G_TYPE_CHECK_CLASS_CAST ((c), APPLICATION_TILE_TYPE, ApplicationTileClass))
Definition at line 33 of file application-tile.h.
APPLICATION_TILE_GET_CLASS
#define APPLICATION_TILE_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), APPLICATION_TILE_TYPE, ApplicationTileClass))
Definition at line 36 of file application-tile.h.
APPLICATION_TILE_TYPE
#define APPLICATION_TILE_TYPE (application_tile_get_type ())
Definition at line 31 of file application-tile.h.
IS_APPLICATION_TILE
#define IS_APPLICATION_TILE (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), APPLICATION_TILE_TYPE))
Definition at line 34 of file application-tile.h.
IS_APPLICATION_TILE_CLASS
#define IS_APPLICATION_TILE_CLASS (c) (G_TYPE_CHECK_CLASS_TYPE ((c), APPLICATION_TILE_TYPE))
Definition at line 35 of file application-tile.h.
Function Documentation
application_tile_get_desktop_item()
MateDesktopItem * application_tile_get_desktop_item (ApplicationTile * tile)
Definition at line 615 of file application-tile.c.
application_tile_get_type()
GType application_tile_get_type (void)
application_tile_new()
GtkWidget * application_tile_new (const gchar * desktop_item_id)
Definition at line 117 of file application-tile.c.
References application_tile_new_full(), and TRUE.
application_tile_new_full()
GtkWidget * application_tile_new_full (const gchar * desktop_item_id, GtkIconSize icon_size, gboolean show_generic_name)
Definition at line 123 of file application-tile.c.
References APPLICATION_TILE_TYPE, load_desktop_item_from_unknown(), mate_desktop_item_get_entry_type(), mate_desktop_item_get_location(), MATE_DESKTOP_ITEM_TYPE_APPLICATION, mate_desktop_item_unref(), and NULL.
Referenced by application_tile_new().