MATE Desktop Environment: async-getprop.c File Reference
async-getprop.c File Reference
#include <assert.h>
#include "async-getprop.h"
#include <X11/Xlibint.h>
Macros
#define NEED_REPLIES
#define NULL ((void*)0)
#define ALIGN_VALUE(this, boundary) ((((unsigned long)(this)) + (((unsigned long)(boundary)) -1)) & (~(((unsigned long)(boundary))-1)))
Typedefs
typedef struct _ListNode ListNode
typedef struct _AgPerDisplayData AgPerDisplayData
Functions
AgGetPropertyTask * ag_task_create (Display *dpy, Window window, Atom property, long offset, long length, Bool delete, Atom req_type)
Status ag_task_get_reply_and_free (AgGetPropertyTask *task, Atom *actual_type, int *actual_format, unsigned long *nitems, unsigned long *bytesafter, unsigned char **prop)
Bool ag_task_have_reply (AgGetPropertyTask *task)
Atom ag_task_get_property (AgGetPropertyTask *task)
Window ag_task_get_window (AgGetPropertyTask *task)
Display * ag_task_get_display (AgGetPropertyTask *task)
AgGetPropertyTask * ag_get_next_completed_task (Display *display)
void * ag_Xmalloc (unsigned long bytes)
void * ag_Xmalloc0 (unsigned long bytes)
Macro Definition Documentation
ALIGN_VALUE
#define ALIGN_VALUE (this, boundary) ((((unsigned long)(this)) + (((unsigned long)(boundary)) -1)) & (~(((unsigned long)(boundary))-1)))
NEED_REPLIES
#define NEED_REPLIES
Definition at line 40 of file async-getprop.c.
NULL
#define NULL ((void*)0)
Definition at line 44 of file async-getprop.c.
Typedef Documentation
AgPerDisplayData
typedef struct _AgPerDisplayData AgPerDisplayData
Definition at line 48 of file async-getprop.c.
ListNode
typedef struct _ListNode ListNode
Definition at line 47 of file async-getprop.c.
Function Documentation
ag_get_next_completed_task()
AgGetPropertyTask * ag_get_next_completed_task (Display * display)
Definition at line 652 of file async-getprop.c.
References NULL.
Referenced by main(), and meta_prop_get_values().
ag_task_create()
AgGetPropertyTask * ag_task_create (Display * dpy, Window window, Atom property, long offset, long length, Bool delete, Atom req_type)
Definition at line 517 of file async-getprop.c.
References NULL.
Referenced by main().
ag_task_get_display()
Display * ag_task_get_display (AgGetPropertyTask * task)
Definition at line 646 of file async-getprop.c.
ag_task_get_property()
Atom ag_task_get_property (AgGetPropertyTask * task)
Definition at line 634 of file async-getprop.c.
ag_task_get_reply_and_free()
Status ag_task_get_reply_and_free (AgGetPropertyTask * task, Atom * actual_type, int * actual_format, unsigned long * nitems, unsigned long * bytesafter, unsigned char ** prop)
Definition at line 584 of file async-getprop.c.
References NULL.
Referenced by meta_prop_get_values().
ag_task_get_window()
Window ag_task_get_window (AgGetPropertyTask * task)
Definition at line 640 of file async-getprop.c.
ag_task_have_reply()
Bool ag_task_have_reply (AgGetPropertyTask * task)
Definition at line 628 of file async-getprop.c.
Referenced by meta_prop_get_values().
ag_Xmalloc()
void * ag_Xmalloc (unsigned long bytes)
Definition at line 671 of file async-getprop.c.
Referenced by meta_prop_get_values().
ag_Xmalloc0()
void * ag_Xmalloc0 (unsigned long bytes)
Definition at line 677 of file async-getprop.c.