MATE Desktop Environment: backend.h File Reference
backend.h File Reference
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <ctype.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <glib.h>
#include <glibtop/netload.h>
Classes
struct DevInfo
Macros
#define SIOCGIWNAME 0x8B01 /* get name == wireless protocol */
#define SIOCGIWENCODE 0x8B2B /* get encoding token & mode */
#define ETH_ALEN 6
#define ETH_LEN 20
#define MAX_FORMAT_SIZE 15
Enumerations
enum DevType {
DEV_LO , DEV_ETHERNET , DEV_WIRELESS , DEV_PPP ,
DEV_PLIP , DEV_SLIP , DEV_UNKNOWN
}
Functions
GList * get_available_devices (void)
const gchar * get_default_route (void)
gboolean is_dummy_device (const char *device)
void free_device_info (DevInfo *devinfo)
void get_device_info (const char *device, DevInfo **info)
gboolean compare_device_info (const DevInfo *a, const DevInfo *b)
void get_wireless_info (DevInfo *devinfo)
GSList * get_ip_address_list (const char *ifa_name, gboolean ipv4)
GSList * get_ip6_address_list (const char *ifa_name)
Macro Definition Documentation
ETH_ALEN
#define ETH_ALEN 6
Definition at line 40 of file backend.h.
ETH_LEN
#define ETH_LEN 20
Definition at line 41 of file backend.h.
MAX_FORMAT_SIZE
#define MAX_FORMAT_SIZE 15
Definition at line 42 of file backend.h.
SIOCGIWENCODE
#define SIOCGIWENCODE 0x8B2B /* get encoding token & mode */
Definition at line 38 of file backend.h.
SIOCGIWNAME
#define SIOCGIWNAME 0x8B01 /* get name == wireless protocol */
Definition at line 37 of file backend.h.
Enumeration Type Documentation
DevType
enum DevType
Enumerator
DEV_LO
DEV_ETHERNET
DEV_WIRELESS
DEV_PPP
DEV_PLIP
DEV_SLIP
DEV_UNKNOWN
Definition at line 45 of file backend.h.
Function Documentation
compare_device_info()
gboolean compare_device_info (const DevInfo * a, const DevInfo * b)
Definition at line 399 of file backend.c.
References b, FALSE, DevInfo::ip, DevInfo::name, DevInfo::running, TRUE, and DevInfo::up.
free_device_info()
void free_device_info (DevInfo * devinfo)
Definition at line 284 of file backend.c.
References DevInfo::essid, and DevInfo::name.
get_available_devices()
GList * get_available_devices (void)
Definition at line 96 of file backend.c.
References devices, and NULL.
get_default_route()
const gchar * get_default_route (void)
Definition at line 246 of file backend.c.
References is_dummy_device(), mask, and NULL.
get_device_info()
void get_device_info (const char * device, DevInfo ** info)
Definition at line 320 of file backend.c.
References DEV_ETHERNET, DEV_LO, DEV_PLIP, DEV_PPP, DEV_SLIP, DEV_UNKNOWN, DEV_WIRELESS, FALSE, get_wireless_info(), DevInfo::hwaddr, DevInfo::ip, memcpy, DevInfo::name, DevInfo::netmask, DevInfo::running, DevInfo::rx, TRUE, DevInfo::tx, DevInfo::type, and DevInfo::up.
get_ip6_address_list()
GSList * get_ip6_address_list (const char * ifa_name)
Definition at line 211 of file backend.c.
References memcpy, and NULL.
get_ip_address_list()
GSList * get_ip_address_list (const char * ifa_name, gboolean ipv4)
Definition at line 115 of file backend.c.
References _, memcpy, and NULL.
get_wireless_info()
void get_wireless_info (DevInfo * devinfo)
Referenced by get_device_info().
is_dummy_device()
gboolean is_dummy_device (const char * device)
Definition at line 68 of file backend.c.
References FALSE, and TRUE.
Referenced by get_default_route().