MATE Desktop Environment: bacon-video-widget-properties.c File Reference
bacon-video-widget-properties.c File Reference
#include "config.h"
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <string.h>
#include <math.h>
#include "bacon-video-widget-properties.h"
Functions
void bacon_video_widget_properties_set_label (BaconVideoWidgetProperties *props, const char *name, const char *text)
void bacon_video_widget_properties_reset (BaconVideoWidgetProperties *props)
void bacon_video_widget_properties_set_duration (BaconVideoWidgetProperties *props, int _time)
void bacon_video_widget_properties_set_has_type (BaconVideoWidgetProperties *props, gboolean has_video, gboolean has_audio)
void bacon_video_widget_properties_set_framerate (BaconVideoWidgetProperties *props, float framerate)
GtkWidget * bacon_video_widget_properties_new (void)
Function Documentation
bacon_video_widget_properties_new()
GtkWidget * bacon_video_widget_properties_new (void)
Definition at line 242 of file bacon-video-widget-properties.c.
References BACON_TYPE_VIDEO_WIDGET_PROPERTIES, BACON_VIDEO_WIDGET_PROPERTIES, bacon_video_widget_properties_reset(), FALSE, NULL, and BaconVideoWidgetProperties::priv.
bacon_video_widget_properties_reset()
void bacon_video_widget_properties_reset (BaconVideoWidgetProperties * props)
Definition at line 89 of file bacon-video-widget-properties.c.
References _, BACON_IS_VIDEO_WIDGET_PROPERTIES, bacon_video_widget_properties_set_duration(), bacon_video_widget_properties_set_label(), C_, FALSE, item, NULL, and BaconVideoWidgetProperties::priv.
Referenced by bacon_video_widget_properties_new().
bacon_video_widget_properties_set_duration()
void bacon_video_widget_properties_set_duration (BaconVideoWidgetProperties * props, int _time)
Definition at line 184 of file bacon-video-widget-properties.c.
References BACON_IS_VIDEO_WIDGET_PROPERTIES, bacon_video_widget_properties_set_label(), NULL, and BaconVideoWidgetProperties::priv.
Referenced by bacon_video_widget_properties_reset().
bacon_video_widget_properties_set_framerate()
void bacon_video_widget_properties_set_framerate (BaconVideoWidgetProperties * props, float framerate)
Definition at line 224 of file bacon-video-widget-properties.c.
References BACON_IS_VIDEO_WIDGET_PROPERTIES, bacon_video_widget_properties_set_label(), C_, and NULL.
bacon_video_widget_properties_set_has_type()
void bacon_video_widget_properties_set_has_type (BaconVideoWidgetProperties * props, gboolean has_video, gboolean has_audio)
Definition at line 203 of file bacon-video-widget-properties.c.
References BACON_IS_VIDEO_WIDGET_PROPERTIES, item, NULL, and BaconVideoWidgetProperties::priv.
bacon_video_widget_properties_set_label()
void bacon_video_widget_properties_set_label (BaconVideoWidgetProperties * props, const char * name, const char * text)
Definition at line 73 of file bacon-video-widget-properties.c.
References BACON_IS_VIDEO_WIDGET_PROPERTIES, item, name, NULL, and BaconVideoWidgetProperties::priv.
Referenced by bacon_video_widget_properties_reset(), bacon_video_widget_properties_set_duration(), and bacon_video_widget_properties_set_framerate().