MATE Desktop Environment: baobab.h File Reference
baobab.h File Reference
#include <time.h>
#include <sys/types.h>
#include <glib.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
Classes
struct _BaobabChartMenu
struct _BaobabFS
struct _BaobabApplication
struct chan_data
Macros
#define BAOBAB_UI_SETTINGS_SCHEMA "org.mate.disk-usage-analyzer.ui"
#define BAOBAB_PREFS_SETTINGS_SCHEMA "org.mate.disk-usage-analyzer.preferences"
#define BAOBAB_SETTINGS_TOOLBAR_VISIBLE "toolbar-visible"
#define BAOBAB_SETTINGS_STATUSBAR_VISIBLE "statusbar-visible"
#define BAOBAB_SETTINGS_SUBFLSTIPS_VISIBLE "subfoldertips-visible"
#define BAOBAB_SETTINGS_ACTIVE_CHART "active-chart"
#define BAOBAB_SETTINGS_MONITOR_HOME "monitor-home"
#define BAOBAB_SETTINGS_EXCLUDED_URIS "excluded-uris"
Typedefs
typedef struct _BaobabChartMenu BaobabChartMenu
typedef struct _BaobabFS BaobabFS
typedef struct _BaobabApplication BaobabApplication
Functions
void baobab_set_busy (gboolean busy)
void baobab_update_filesystem (void)
void baobab_scan_location (GFile *)
void baobab_scan_home (void)
void baobab_scan_root (void)
void baobab_rescan_current_dir (void)
void baobab_stop_scan (void)
void baobab_fill_model (struct chan_data *)
gboolean baobab_is_excluded_location (GFile *)
void baobab_set_toolbar_visible (gboolean visible)
void baobab_set_statusbar_visible (gboolean visible)
void baobab_set_statusbar (const gchar *)
void baobab_quit (void)
Variables
BaobabApplication baobab
Macro Definition Documentation
BAOBAB_PREFS_SETTINGS_SCHEMA
#define BAOBAB_PREFS_SETTINGS_SCHEMA "org.mate.disk-usage-analyzer.preferences"
Definition at line 33 of file baobab.h.
BAOBAB_SETTINGS_ACTIVE_CHART
#define BAOBAB_SETTINGS_ACTIVE_CHART "active-chart"
Definition at line 37 of file baobab.h.
BAOBAB_SETTINGS_EXCLUDED_URIS
#define BAOBAB_SETTINGS_EXCLUDED_URIS "excluded-uris"
Definition at line 39 of file baobab.h.
BAOBAB_SETTINGS_MONITOR_HOME
#define BAOBAB_SETTINGS_MONITOR_HOME "monitor-home"
Definition at line 38 of file baobab.h.
BAOBAB_SETTINGS_STATUSBAR_VISIBLE
#define BAOBAB_SETTINGS_STATUSBAR_VISIBLE "statusbar-visible"
Definition at line 35 of file baobab.h.
BAOBAB_SETTINGS_SUBFLSTIPS_VISIBLE
#define BAOBAB_SETTINGS_SUBFLSTIPS_VISIBLE "subfoldertips-visible"
Definition at line 36 of file baobab.h.
BAOBAB_SETTINGS_TOOLBAR_VISIBLE
#define BAOBAB_SETTINGS_TOOLBAR_VISIBLE "toolbar-visible"
Definition at line 34 of file baobab.h.
BAOBAB_UI_SETTINGS_SCHEMA
#define BAOBAB_UI_SETTINGS_SCHEMA "org.mate.disk-usage-analyzer.ui"
Definition at line 32 of file baobab.h.
Typedef Documentation
BaobabApplication
typedef struct _BaobabApplication BaobabApplication
Definition at line 61 of file baobab.h.
BaobabChartMenu
typedef struct _BaobabChartMenu BaobabChartMenu
Definition at line 41 of file baobab.h.
BaobabFS
typedef struct _BaobabFS BaobabFS
Definition at line 53 of file baobab.h.
Function Documentation
baobab_fill_model()
void baobab_fill_model (struct chan_data * data)
Definition at line 436 of file baobab.c.
References _, baobab, COL_DIR_NAME, COL_DIR_SIZE, COL_ELEMENTS, COL_H_ALLOCSIZE, COL_H_ELEMENTS, COL_H_HARDLINK, COL_H_PARSENAME, COL_H_PERC, COL_H_SIZE, COL_HARDLINK, data, _BaobabApplication::model, name, _BaobabApplication::show_allocated, and TRUE.
baobab_is_excluded_location()
gboolean baobab_is_excluded_location (GFile * file)
Definition at line 522 of file baobab.c.
References baobab, _BaobabApplication::excluded_locations, FALSE, NULL, and TRUE.
Referenced by baobab_check_dir(), and baobab_get_filesystem().
baobab_quit()
void baobab_quit (void)
Definition at line 1196 of file baobab.c.
References baobab_stop_scan().
Referenced by on_delete_activate(), and on_quit_activate().
baobab_rescan_current_dir()
void baobab_rescan_current_dir (void)
Definition at line 286 of file baobab.c.
References baobab, baobab_scan_location(), baobab_update_filesystem(), _BaobabApplication::current_location, and NULL.
Referenced by on_menu_rescan_activate(), and on_tbrescan_clicked().
baobab_scan_home()
void baobab_scan_home (void)
Definition at line 266 of file baobab.c.
References baobab_scan_location().
Referenced by on_menuscanhome_activate(), and on_tbscanhome_clicked().
baobab_scan_location()
void baobab_scan_location (GFile * file)
Definition at line 208 of file baobab.c.
References _, baobab, baobab_chart_set_max_depth(), baobab_check_dir(), baobab_scan_execute(), baobab_set_busy(), baobab_set_statusbar(), _BaobabApplication::CONTENTS_CHANGED_DELAYED, _BaobabApplication::current_location, FALSE, GET_TOGGLE_ACTION, _BaobabApplication::is_local, _BaobabApplication::model, _BaobabApplication::model_max_depth, NULL, _BaobabApplication::rings_chart, _BaobabApplication::show_allocated, show_bars(), _BaobabApplication::STOP_SCANNING, _BaobabApplication::tree_view, _BaobabApplication::treemap_chart, and TRUE.
Referenced by baobab_rescan_current_dir(), baobab_scan_home(), baobab_scan_root(), and scan_folder_cb().
baobab_scan_root()
void baobab_scan_root (void)
Definition at line 276 of file baobab.c.
References baobab_scan_location().
Referenced by on_menuallfs_activate(), and on_tbscanall_clicked().
baobab_set_busy()
void baobab_set_busy (gboolean busy)
Definition at line 80 of file baobab.c.
References baobab, baobab_chart_freeze_updates(), baobab_chart_thaw_updates(), _BaobabApplication::chart_type_combo, FALSE, NULL, _BaobabApplication::rings_chart, _BaobabApplication::spinner, _BaobabApplication::treemap_chart, TRUE, and _BaobabApplication::window.
Referenced by baobab_scan_location(), and on_ck_allocated_activate().
baobab_set_statusbar()
void baobab_set_statusbar (const gchar * text)
Definition at line 616 of file baobab.c.
References baobab, and _BaobabApplication::statusbar.
Referenced by baobab_scan_location(), baobab_stop_scan(), main(), and on_ck_allocated_activate().
baobab_set_statusbar_visible()
void baobab_set_statusbar_visible (gboolean visible)
baobab_set_toolbar_visible()
void baobab_set_toolbar_visible (gboolean visible)
baobab_stop_scan()
void baobab_stop_scan (void)
Definition at line 298 of file baobab.c.
References _, baobab, baobab_set_statusbar(), _BaobabApplication::model, NULL, show_bars(), _BaobabApplication::STOP_SCANNING, _BaobabApplication::tree_view, and TRUE.
Referenced by baobab_quit(), on_menu_stop_activate(), and on_tbstop_clicked().
baobab_update_filesystem()
void baobab_update_filesystem (void)
Definition at line 201 of file baobab.c.
References baobab, baobab_get_filesystem(), and _BaobabApplication::fs.
Referenced by baobab_rescan_current_dir().
Variable Documentation
baobab
BaobabApplication baobab extern
Definition at line 49 of file baobab.c.
Referenced by baobab_check_dir(), baobab_fill_model(), baobab_is_excluded_location(), baobab_prefs_dialog(), baobab_rescan_current_dir(), baobab_scan_execute(), baobab_scan_location(), baobab_set_busy(), baobab_set_statusbar(), baobab_stop_scan(), baobab_treeview_show_allocated_size(), baobab_update_filesystem(), create_directory_treeview(), main(), on_about_activate(), on_chart_snapshot_cb(), on_ck_allocated_activate(), on_helpcontents_activate(), on_menu_collapse_activate(), on_menu_expand_activate(), on_menuscandir_activate(), on_move_upwards_cb(), on_tb_scan_remote_clicked(), on_tbscandir_clicked(), on_tv_selection_changed(), on_zoom_in_cb(), on_zoom_out_cb(), open_file_cb(), open_file_with_application(), popupmenu_list(), scan_folder_cb(), show_bars(), trash_dir_cb(), and trash_file().