MATE Desktop Environment: baobab.c File Reference
baobab.c File Reference
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <glibtop.h>
#include <libmate-desktop/mate-image-menu-item.h>
#include "baobab.h"
#include "baobab-scan.h"
#include "baobab-treeview.h"
#include "baobab-utils.h"
#include "callbacks.h"
#include "baobab-prefs.h"
#include "baobab-treemap.h"
#include "baobab-ringschart.h"
Macros
#define BAOBAB_UI_RESOURCE "/org/mate/disk-usage-analyzer/baobab-main-window.ui"
#define GET_WIDGET(x) (GTK_WIDGET (gtk_builder_get_object (baobab.main_ui, (x))))
#define GET_ACTION(x) (GTK_ACTION (gtk_builder_get_object (baobab.main_ui, (x))))
#define GET_TOGGLE_ACTION(x) (GTK_TOGGLE_ACTION (gtk_builder_get_object (baobab.main_ui, (x))))
Enumerations
enum { DND_TARGET_URI_LIST }
Functions
void baobab_set_busy (gboolean busy)
void baobab_update_filesystem (void)
void baobab_scan_location (GFile *file)
void baobab_scan_home (void)
void baobab_scan_root (void)
void baobab_rescan_current_dir (void)
void baobab_stop_scan (void)
void baobab_fill_model (struct chan_data *data)
gboolean baobab_is_excluded_location (GFile *file)
void baobab_set_statusbar (const gchar *text)
void baobab_quit ()
int main (int argc, char *argv[])
Variables
BaobabApplication baobab
Macro Definition Documentation
BAOBAB_UI_RESOURCE
#define BAOBAB_UI_RESOURCE "/org/mate/disk-usage-analyzer/baobab-main-window.ui"
Definition at line 41 of file baobab.c.
GET_ACTION
#define GET_ACTION (x) (GTK_ACTION (gtk_builder_get_object (baobab.main_ui, (x))))
Definition at line 43 of file baobab.c.
GET_TOGGLE_ACTION
#define GET_TOGGLE_ACTION (x) (GTK_TOGGLE_ACTION (gtk_builder_get_object (baobab.main_ui, (x))))
Definition at line 44 of file baobab.c.
GET_WIDGET
#define GET_WIDGET (x) (GTK_WIDGET (gtk_builder_get_object (baobab.main_ui, (x))))
Definition at line 42 of file baobab.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DND_TARGET_URI_LIST
Definition at line 56 of file baobab.c.
Function Documentation
baobab_fill_model()
void baobab_fill_model (struct chan_data * data)
Definition at line 436 of file baobab.c.
References _, baobab, COL_DIR_NAME, COL_DIR_SIZE, COL_ELEMENTS, COL_H_ALLOCSIZE, COL_H_ELEMENTS, COL_H_HARDLINK, COL_H_PARSENAME, COL_H_PERC, COL_H_SIZE, COL_HARDLINK, data, _BaobabApplication::model, name, _BaobabApplication::show_allocated, and TRUE.
baobab_is_excluded_location()
gboolean baobab_is_excluded_location (GFile * file)
Definition at line 522 of file baobab.c.
References baobab, _BaobabApplication::excluded_locations, FALSE, NULL, and TRUE.
Referenced by baobab_check_dir(), and baobab_get_filesystem().
baobab_quit()
void baobab_quit (void)
Definition at line 1196 of file baobab.c.
References baobab_stop_scan().
Referenced by on_delete_activate(), and on_quit_activate().
baobab_rescan_current_dir()
void baobab_rescan_current_dir (void)
Definition at line 286 of file baobab.c.
References baobab, baobab_scan_location(), baobab_update_filesystem(), _BaobabApplication::current_location, and NULL.
Referenced by on_menu_rescan_activate(), and on_tbrescan_clicked().
baobab_scan_home()
void baobab_scan_home (void)
Definition at line 266 of file baobab.c.
References baobab_scan_location().
Referenced by on_menuscanhome_activate(), and on_tbscanhome_clicked().
baobab_scan_location()
void baobab_scan_location (GFile * file)
Definition at line 208 of file baobab.c.
References _, baobab, baobab_chart_set_max_depth(), baobab_check_dir(), baobab_scan_execute(), baobab_set_busy(), baobab_set_statusbar(), _BaobabApplication::CONTENTS_CHANGED_DELAYED, _BaobabApplication::current_location, FALSE, GET_TOGGLE_ACTION, _BaobabApplication::is_local, _BaobabApplication::model, _BaobabApplication::model_max_depth, NULL, _BaobabApplication::rings_chart, _BaobabApplication::show_allocated, show_bars(), _BaobabApplication::STOP_SCANNING, _BaobabApplication::tree_view, _BaobabApplication::treemap_chart, and TRUE.
Referenced by baobab_rescan_current_dir(), baobab_scan_home(), baobab_scan_root(), and scan_folder_cb().
baobab_scan_root()
void baobab_scan_root (void)
Definition at line 276 of file baobab.c.
References baobab_scan_location().
Referenced by on_menuallfs_activate(), and on_tbscanall_clicked().
baobab_set_busy()
void baobab_set_busy (gboolean busy)
Definition at line 80 of file baobab.c.
References baobab, baobab_chart_freeze_updates(), baobab_chart_thaw_updates(), _BaobabApplication::chart_type_combo, FALSE, NULL, _BaobabApplication::rings_chart, _BaobabApplication::spinner, _BaobabApplication::treemap_chart, TRUE, and _BaobabApplication::window.
Referenced by baobab_scan_location(), and on_ck_allocated_activate().
baobab_set_statusbar()
void baobab_set_statusbar (const gchar * text)
Definition at line 616 of file baobab.c.
References baobab, and _BaobabApplication::statusbar.
Referenced by baobab_scan_location(), baobab_stop_scan(), main(), and on_ck_allocated_activate().
baobab_stop_scan()
void baobab_stop_scan (void)
Definition at line 298 of file baobab.c.
References _, baobab, baobab_set_statusbar(), _BaobabApplication::model, NULL, show_bars(), _BaobabApplication::STOP_SCANNING, _BaobabApplication::tree_view, and TRUE.
Referenced by baobab_quit(), on_menu_stop_activate(), and on_tbstop_clicked().
baobab_update_filesystem()
void baobab_update_filesystem (void)
Definition at line 201 of file baobab.c.
References baobab, baobab_get_filesystem(), and _BaobabApplication::fs.
Referenced by baobab_rescan_current_dir().
main()
int main (int argc, char * argv[])
Definition at line 1222 of file baobab.c.
References _, baobab, baobab_set_statusbar(), create_directory_treeview(), error, FALSE, _BaobabApplication::fs, GET_ACTION, GET_TOGGLE_ACTION, GET_WIDGET, N_, NULL, _BaobabApplication::show_allocated, _BaobabFS::total, _BaobabApplication::tree_view, TRUE, and _BaobabApplication::window.
Variable Documentation
baobab
BaobabApplication baobab
Definition at line 49 of file baobab.c.
Referenced by baobab_check_dir(), baobab_fill_model(), baobab_is_excluded_location(), baobab_prefs_dialog(), baobab_rescan_current_dir(), baobab_scan_execute(), baobab_scan_location(), baobab_set_busy(), baobab_set_statusbar(), baobab_stop_scan(), baobab_treeview_show_allocated_size(), baobab_update_filesystem(), create_directory_treeview(), main(), on_about_activate(), on_chart_snapshot_cb(), on_ck_allocated_activate(), on_helpcontents_activate(), on_menu_collapse_activate(), on_menu_expand_activate(), on_menuscandir_activate(), on_move_upwards_cb(), on_tb_scan_remote_clicked(), on_tbscandir_clicked(), on_tv_selection_changed(), on_zoom_in_cb(), on_zoom_out_cb(), open_file_cb(), open_file_with_application(), popupmenu_list(), scan_folder_cb(), show_bars(), trash_dir_cb(), and trash_file().