MATE Desktop Environment: baobab-treeview.h File Reference
baobab-treeview.h File Reference
#include <gtk/gtk.h>
Enumerations
enum {
COL_DIR_NAME , COL_H_PARSENAME , COL_H_PERC , COL_DIR_SIZE ,
COL_H_SIZE , COL_H_ALLOCSIZE , COL_ELEMENTS , COL_H_ELEMENTS ,
COL_HARDLINK , COL_H_HARDLINK , NUM_TREE_COLUMNS
}
Functions
GtkWidget * create_directory_treeview (void)
void baobab_treeview_show_allocated_size (GtkWidget *tv, gboolean show_allocated)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COL_DIR_NAME
COL_H_PARSENAME
COL_H_PERC
COL_DIR_SIZE
COL_H_SIZE
COL_H_ALLOCSIZE
COL_ELEMENTS
COL_H_ELEMENTS
COL_HARDLINK
COL_H_HARDLINK
NUM_TREE_COLUMNS
Definition at line 26 of file baobab-treeview.h.
Function Documentation
baobab_treeview_show_allocated_size()
void baobab_treeview_show_allocated_size (GtkWidget * tv, gboolean show_allocated)
Definition at line 311 of file baobab-treeview.c.
References baobab, COL_H_ALLOCSIZE, COL_H_SIZE, and _BaobabApplication::model.
Referenced by on_ck_allocated_activate().
create_directory_treeview()
GtkWidget * create_directory_treeview (void)
Definition at line 199 of file baobab-treeview.c.
References _, baobab, baobab_cell_renderer_progress_new(), COL_DIR_NAME, COL_DIR_SIZE, COL_ELEMENTS, COL_H_ALLOCSIZE, COL_H_ELEMENTS, COL_H_PERC, COL_H_SIZE, COL_HARDLINK, FALSE, GET_WIDGET, _BaobabApplication::model, NULL, on_tv_selection_changed(), _BaobabApplication::show_allocated, and TRUE.
Referenced by main().