MATE Desktop Environment: baobab-treeview.c File Reference
baobab-treeview.c File Reference
#include <gtk/gtk.h>
#include <glib.h>
#include <glib/gprintf.h>
#include <glib/gi18n.h>
#include <string.h>
#include "baobab.h"
#include "baobab-treeview.h"
#include "baobab-cell-renderer-progress.h"
#include "baobab-utils.h"
#include "callbacks.h"
Macros
#define GET_WIDGET(x) (GTK_WIDGET (gtk_builder_get_object (baobab.main_ui, (x))))
Functions
GtkWidget * create_directory_treeview (void)
void baobab_treeview_show_allocated_size (GtkWidget *tv, gboolean show_allocated)
Macro Definition Documentation
GET_WIDGET
#define GET_WIDGET (x) (GTK_WIDGET (gtk_builder_get_object (baobab.main_ui, (x))))
Definition at line 36 of file baobab-treeview.c.
Function Documentation
baobab_treeview_show_allocated_size()
void baobab_treeview_show_allocated_size (GtkWidget * tv, gboolean show_allocated)
Definition at line 311 of file baobab-treeview.c.
References baobab, COL_H_ALLOCSIZE, COL_H_SIZE, and _BaobabApplication::model.
Referenced by on_ck_allocated_activate().
create_directory_treeview()
GtkWidget * create_directory_treeview (void)
Definition at line 199 of file baobab-treeview.c.
References _, baobab, baobab_cell_renderer_progress_new(), COL_DIR_NAME, COL_DIR_SIZE, COL_ELEMENTS, COL_H_ALLOCSIZE, COL_H_ELEMENTS, COL_H_PERC, COL_H_SIZE, COL_HARDLINK, FALSE, GET_WIDGET, _BaobabApplication::model, NULL, on_tv_selection_changed(), _BaobabApplication::show_allocated, and TRUE.
Referenced by main().