MATE Desktop Environment: baobab-utils.c File Reference
baobab-utils.c File Reference
#include <glib.h>
#include <glib/gstdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <string.h>
#include <glib/gi18n.h>
#include <glib/gprintf.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <glibtop/mountlist.h>
#include <glibtop/fsusage.h>
#include <libmate-desktop/mate-image-menu-item.h>
#include "baobab.h"
#include "baobab-treeview.h"
#include "baobab-utils.h"
#include "callbacks.h"
Functions
void baobab_get_filesystem (BaobabFS *fs)
gchar * dir_select (gboolean SEARCH, GtkWidget *parent)
void on_toggled (GtkToggleButton *togglebutton, gpointer dialog)
gboolean show_bars (GtkTreeModel *mdl, GtkTreePath *path, GtkTreeIter *iter, gpointer data)
void message (const gchar *primary_msg, const gchar *secondary_msg, GtkMessageType type, GtkWidget *parent)
gint messageyesno (const gchar *primary_msg, const gchar *secondary_msg, GtkMessageType type, gchar *ok_button, GtkWidget *parent)
gboolean baobab_check_dir (GFile *file)
void popupmenu_list (GtkTreePath *path, GdkEventButton *event, gboolean can_trash)
void open_file_with_application (GFile *file)
gboolean can_trash_file (GFile *file)
gboolean trash_file (GFile *file)
gboolean baobab_help_display (GtkWindow *parent, const gchar *file_name, const gchar *link_id)
gboolean is_virtual_filesystem (GFile *file)
Function Documentation
baobab_check_dir()
gboolean baobab_check_dir (GFile * file)
Definition at line 275 of file baobab-utils.c.
References _, baobab, baobab_is_excluded_location(), error, FALSE, is_virtual_filesystem(), message(), name, NULL, TRUE, and _BaobabApplication::window.
Referenced by baobab_scan_location().
baobab_get_filesystem()
void baobab_get_filesystem (BaobabFS * fs)
Definition at line 44 of file baobab-utils.c.
References _BaobabFS::avail, baobab_is_excluded_location(), FALSE, _BaobabFS::total, and _BaobabFS::used.
Referenced by baobab_update_filesystem().
baobab_help_display()
gboolean baobab_help_display (GtkWindow * parent, const gchar * file_name, const gchar * link_id)
Definition at line 473 of file baobab-utils.c.
References _, error, and NULL.
Referenced by on_helpcontents_activate().
can_trash_file()
gboolean can_trash_file (GFile * file)
Definition at line 408 of file baobab-utils.c.
References FALSE, and NULL.
dir_select()
gchar * dir_select (gboolean SEARCH, GtkWidget * parent)
Definition at line 101 of file baobab-utils.c.
References _, FALSE, NULL, on_toggled(), and TRUE.
Referenced by on_menuscandir_activate(), and on_tbscandir_clicked().
is_virtual_filesystem()
gboolean is_virtual_filesystem (GFile * file)
Definition at line 516 of file baobab-utils.c.
References FALSE, NULL, and TRUE.
Referenced by baobab_check_dir().
message()
void message (const gchar * primary_msg, const gchar * secondary_msg, GtkMessageType type, GtkWidget * parent)
Definition at line 227 of file baobab-utils.c.
References type.
Referenced by _gtk_error_dialog_run(), _gtk_message_dialog_new(), _gtk_request_dialog_run(), active_sensor_libnotify_notify(), bacon_message_connection_send(), baobab_check_dir(), battstat_show_help(), caja_application_notify_unmount_show(), caja_inhibit_power_manager(), caja_launch_desktop_file(), caja_restore_files_from_trash(), caja_x_content_bar_set_x_content_type(), cpufreq_utils_display_error(), ev_job_failed(), ev_loading_message_new(), fm_report_error_loading_directory(), fm_report_error_renaming_file(), fm_report_error_setting_group(), fm_report_error_setting_owner(), fm_report_error_setting_permissions(), fr_window_archive_save_as(), gdict_show_error_dialog(), gdict_show_gerror_dialog(), gs_lock_plug_enable_prompt(), gs_lock_plug_show_message(), gsm_consolekit_get_current_session_type(), gsm_consolekit_set_session_idle(), gsm_manager_initialization_error(), gsm_systemd_set_session_idle(), mate_app_message(), mate_app_ok_cancel(), mate_app_ok_cancel_modal(), mate_message_box_construct(), mate_message_box_new(), mate_message_box_newv(), mate_ok_cancel_dialog(), mate_ok_cancel_dialog_modal(), mate_ok_cancel_dialog_modal_parented(), mate_ok_cancel_dialog_parented(), mate_ok_dialog(), mate_ok_dialog_parented(), mate_password_dialog_new(), matekbd_indicator_load_images(), mdm_log_default_handler(), meta_show_dialog(), meta_show_entry_dialog(), move_to_trash_cb(), na_core_utils_dir_list_perms(), na_core_utils_file_list_perms(), open_file_cb(), open_file_with_application(), pluma_file_browser_utils_confirmation_dialog(), pluma_message_bus_connect(), pluma_message_bus_send(), pluma_message_bus_send_message(), pluma_message_bus_send_message_sync(), pluma_message_bus_send_sync(), pluma_message_get(), pluma_message_get_key_type(), pluma_message_get_method(), pluma_message_get_object_path(), pluma_message_get_valist(), pluma_message_get_value(), pluma_message_has_key(), pluma_message_set(), pluma_message_set_valist(), pluma_message_set_value(), pluma_message_set_valuesv(), pluma_message_type_instantiate(), pluma_message_type_instantiate_valist(), pluma_message_validate(), polkit_mate_authenticator_new(), scan_folder_cb(), screenshot_show_error_dialog(), screenshot_show_gerror_dialog(), sensors_applet_notify_active_sensor(), shares_supports_guest_ok(), terminal_util_show_error_dialog(), and trash_file().
messageyesno()
gint messageyesno (const gchar * primary_msg, const gchar * secondary_msg, GtkMessageType type, gchar * ok_button, GtkWidget * parent)
Definition at line 244 of file baobab-utils.c.
References TRUE, and type.
on_toggled()
void on_toggled (GtkToggleButton * togglebutton, gpointer dialog)
Definition at line 142 of file baobab-utils.c.
Referenced by dir_select().
open_file_with_application()
void open_file_with_application (GFile * file)
Definition at line 362 of file baobab-utils.c.
References _, baobab, message(), NULL, TRUE, and _BaobabApplication::window.
Referenced by open_file_cb(), open_file_cb(), and open_folder_cb().
popupmenu_list()
void popupmenu_list (GtkTreePath * path, GdkEventButton * event, gboolean can_trash)
Definition at line 338 of file baobab-utils.c.
References _, baobab, _BaobabApplication::is_local, open_file_cb(), and trash_dir_cb().
show_bars()
gboolean show_bars (GtkTreeModel * mdl, GtkTreePath * path, GtkTreeIter * iter, gpointer data)
Definition at line 150 of file baobab-utils.c.
References baobab, COL_DIR_SIZE, COL_ELEMENTS, COL_H_ALLOCSIZE, COL_H_ELEMENTS, COL_H_PERC, COL_H_SIZE, FALSE, NULL, and _BaobabApplication::show_allocated.
Referenced by baobab_scan_location(), baobab_stop_scan(), and on_ck_allocated_activate().
trash_file()
gboolean trash_file (GFile * file)
Definition at line 432 of file baobab-utils.c.
References _, baobab, error, FALSE, message(), NULL, TRUE, and _BaobabApplication::window.
Referenced by trash_dir_cb().