MATE Desktop Environment: base-window.c File Reference
base-window.c File Reference
#include <glib/gi18n.h>
#include <stdlib.h>
#include <string.h>
#include <core/na-gtk-utils.h>
#include "base-application.h"
#include "base-builder.h"
#include "base-window.h"
#include "base-gtk-utils.h"
#include "base-marshal.h"
Macros
#define BASE_PROP_GTK_DATA "base-prop-window-gtk-data"
Enumerations
enum {
BASE_PROP_0 , BASE_PROP_PARENT_ID , BASE_PROP_APPLICATION_ID , BASE_PROP_XMLUI_FILENAME_ID ,
BASE_PROP_HAS_OWN_BUILDER_ID , BASE_PROP_TOPLEVEL_NAME_ID , BASE_PROP_WSP_NAME_ID , BASE_PROP_DESTROY_ON_DISPOSE_ID ,
BASE_PROP_N_PROPERTIES
}
enum { INITIALIZE_GTK , INITIALIZE_BASE , SHOW_WIDGETS , LAST_SIGNAL }
Functions
GType base_window_get_type (void)
gboolean base_window_init (BaseWindow *window)
int base_window_run (BaseWindow *window)
BaseApplication * base_window_get_application (const BaseWindow *window)
BaseWindow * base_window_get_parent (const BaseWindow *window)
GtkWindow * base_window_get_gtk_toplevel (const BaseWindow *window)
: the name of the searched child.
base_window_get_widget: @window: this BaseWindow instance.
Returns a pointer to the named widget which is a child of the toplevel #GtkWindow associated with @window.
Returns: a pointer to the searched widget, or NULL. This pointer is owned by GtkBuilder instance, and must not be g_free() nor g_object_unref() by the caller.
GtkWidget * base_window_get_widget (const BaseWindow *window, const gchar *name)
void base_window_display_error_dlg (const BaseWindow *parent, const gchar *primary, const gchar *secondary)
gboolean base_window_display_yesno_dlg (const BaseWindow *parent, const gchar *primary, const gchar *secondary)
void base_window_display_message_dlg (const BaseWindow *parent, GSList *msg)
gulong base_window_signal_connect (BaseWindow *window, GObject *instance, const gchar *signal, GCallback fn)
gulong base_window_signal_connect_after (BaseWindow *window, GObject *instance, const gchar *signal, GCallback fn)
gulong base_window_signal_connect_by_name (BaseWindow *window, const gchar *name, const gchar *signal, GCallback fn)
gulong base_window_signal_connect_with_data (BaseWindow *window, GObject *instance, const gchar *signal, GCallback fn, void *user_data)
void base_window_signal_disconnect (BaseWindow *window, gulong handler_id)
: the name of the searched GtkWindow.
base_window_get_gtk_toplevel_by_name: @window: this BaseWindow instance.
Returns: the named top-level GtkWindow.
The function searches for the toplevel first in the private builder, and then in the class common builder (if not found and is not the same).
This is just a convenience function to be able to open quickly a window (e.g. Legend dialog).
The caller may close the window by g_object_unref()-ing the returned #GtkWindow.
GtkWindow * base_window_get_gtk_toplevel_by_name (const BaseWindow *window, const gchar *name)
Macro Definition Documentation
BASE_PROP_GTK_DATA
#define BASE_PROP_GTK_DATA "base-prop-window-gtk-data"
Definition at line 98 of file base-window.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BASE_PROP_0
BASE_PROP_PARENT_ID
BASE_PROP_APPLICATION_ID
BASE_PROP_XMLUI_FILENAME_ID
BASE_PROP_HAS_OWN_BUILDER_ID
BASE_PROP_TOPLEVEL_NAME_ID
BASE_PROP_WSP_NAME_ID
BASE_PROP_DESTROY_ON_DISPOSE_ID
BASE_PROP_N_PROPERTIES
Definition at line 77 of file base-window.c.
anonymous enum
anonymous enum
Enumerator
INITIALIZE_GTK
INITIALIZE_BASE
SHOW_WIDGETS
LAST_SIGNAL
Definition at line 102 of file base-window.c.
Function Documentation
base_window_display_error_dlg()
void base_window_display_error_dlg (const BaseWindow * parent, const gchar * primary, const gchar * secondary)
base_window_display_error_dlg: @parent: the BaseWindow parent, may be NULL. @primary: the primary message. @secondary: the secondary message.
Display an error dialog box, with a 'OK' button only.
if @secondary is not null, then @primary is displayed as a bold title.
Definition at line 1124 of file base-window.c.
Referenced by base_iunique_init_with_name(), cact_menubar_edit_on_cut(), cact_menubar_edit_on_delete(), and cact_menubar_file_save_items().
base_window_display_message_dlg()
void base_window_display_message_dlg (const BaseWindow * parent, GSList * msg)
base_window_display_message_dlg: @parent: the BaseWindow parent, may be NULL. @message: the message to be displayed.
Displays an information dialog with only an OK button.
Definition at line 1159 of file base-window.c.
References NULL, and TRUE.
base_window_display_yesno_dlg()
gboolean base_window_display_yesno_dlg (const BaseWindow * parent, const gchar * primary, const gchar * secondary)
base_window_display_yesno_dlg: @parent: the BaseWindow parent, may be NULL. @primary: the primary message. @secondary: the secondary message.
Display a warning dialog box, with a 'OK' button only.
if @secondary is not null, then @primary is displayed as a bold title.
Returns: TRUE if the user has clicked 'Yes', FALSE else.
Definition at line 1142 of file base-window.c.
base_window_get_application()
BaseApplication * base_window_get_application (const BaseWindow * window)
base_window_get_application: @window: this BaseWindow object.
Returns: a pointer on the BaseApplication object.
The returned pointer is owned by the primary allocator of the application ; it should not be g_free() nor g_object_unref() by the caller.
Definition at line 986 of file base-window.c.
References BASE_IS_WINDOW, NULL, and BaseWindow::private.
Referenced by cact_menubar_file_on_new_action(), cact_menubar_file_on_new_menu(), cact_menubar_maintainer_on_test_function(), cact_providers_list_init_view(), cact_schemes_list_init_view(), cact_sort_buttons_new(), and cact_tree_ieditable_initialize().
base_window_get_gtk_toplevel()
GtkWindow * base_window_get_gtk_toplevel (const BaseWindow * window)
base_window_get_gtk_toplevel: @window: this BaseWindow instance..
Returns the top-level GtkWindow attached to this BaseWindow object.
The caller may close the window by g_object_unref()-ing the returned #GtkWindow.
Definition at line 1033 of file base-window.c.
References BASE_IS_WINDOW, NULL, and BaseWindow::private.
Referenced by base_gtk_utils_restore_window_position(), base_gtk_utils_save_window_position(), base_gtk_utils_select_dir(), base_gtk_utils_select_file_with_preview(), and cact_menubar_help_on_about().
base_window_get_gtk_toplevel_by_name()
GtkWindow * base_window_get_gtk_toplevel_by_name (const BaseWindow * window, const gchar * name)
Definition at line 1065 of file base-window.c.
References base_builder_get_toplevel_by_name(), BASE_IS_WINDOW, BASE_WINDOW_GET_CLASS, name, NULL, and BaseWindow::private.
base_window_get_parent()
BaseWindow * base_window_get_parent (const BaseWindow * window)
base_window_get_parent: @window: this BaseWindow instance..
Returns the BaseWindow parent of @window.
The returned object is owned by @window, and should not be freed.
Definition at line 1009 of file base-window.c.
References BASE_IS_WINDOW, NULL, and BaseWindow::private.
base_window_get_type()
GType base_window_get_type (void)
Definition at line 148 of file base-window.c.
base_window_get_widget()
GtkWidget * base_window_get_widget (const BaseWindow * window, const gchar * name)
Definition at line 1099 of file base-window.c.
References BASE_IS_WINDOW, na_gtk_utils_find_widget_by_name(), name, NULL, and BaseWindow::private.
Referenced by base_gtk_utils_toggle_set_initial_state(), base_window_signal_connect_by_name(), cact_iaction_tab_has_label(), cact_main_statusbar_initialize_gtk_toplevel(), cact_main_statusbar_set_locked(), cact_main_tab_enable_page(), cact_main_tab_is_page_enabled(), cact_main_toolbar_activate(), cact_menubar_view_on_tabs_pos_changed(), and cact_preferences_editor_run().
base_window_init()
gboolean base_window_init (BaseWindow * window)
base_window_init: @window: this BaseWindow object.
Initialize the Gtk toplevel if needed, initialize the window at runtime, and show it.
Returns: TRUE if the window has been successfully loaded and initialized and all widgets showed, FALSE else.
Definition at line 661 of file base-window.c.
References base_builder_new(), BASE_IS_BUILDER, BASE_IS_WINDOW, BASE_SIGNAL_INITIALIZE_WINDOW, BASE_SIGNAL_SHOW_WIDGETS, BASE_WINDOW_GET_CLASS, FALSE, BaseWindow::private, and TRUE.
Referenced by base_window_run(), and cact_main_window_new().
base_window_run()
int base_window_run (BaseWindow * window)
base_window_run: @window: this BaseWindow object.
Runs the window.
This function calls the run() virtual method, and does nothing else. If the derived class does not rely on the main loop, it really should implement the run() virtual method.
Returns: the exit code as set by the derived class, or:
BASE_EXIT_CODE_PROGRAM if the window has already been disposed,
BASE_EXIT_CODE_INIT_WINDOW if the window was not and cannot be loaded and initialized.
Definition at line 928 of file base-window.c.
References BASE_EXIT_CODE_INIT_WINDOW, BASE_EXIT_CODE_OK, BASE_EXIT_CODE_PROGRAM, BASE_IS_WINDOW, BASE_WINDOW_GET_CLASS, base_window_init(), and BaseWindow::private.
Referenced by cact_add_capability_dialog_run(), cact_add_scheme_dialog_run(), cact_assistant_export_run(), cact_assistant_import_run(), cact_confirm_logout_run(), cact_export_ask_user(), cact_icon_chooser_choose_icon(), and cact_preferences_editor_run().
base_window_signal_connect()
gulong base_window_signal_connect (BaseWindow * window, GObject * instance, const gchar * signal, GCallback fn)
Records a connected signal, to be disconnected at CactWindow dispose.
Definition at line 1207 of file base-window.c.
References BASE_IS_WINDOW, and BaseWindow::private.
Referenced by base_gtk_utils_toggle_set_initial_state(), base_window_signal_connect_by_name(), cact_iaction_tab_init(), cact_ibasenames_tab_init(), cact_icapabilities_tab_init(), cact_icommand_tab_init(), cact_ienvironment_tab_init(), cact_iexecution_tab_init(), cact_ifolders_tab_init(), cact_imimetypes_tab_init(), cact_iproperties_tab_init(), cact_ischemes_tab_init(), cact_menubar_new(), cact_sort_buttons_new(), and cact_tree_ieditable_initialize().
base_window_signal_connect_after()
gulong base_window_signal_connect_after (BaseWindow * window, GObject * instance, const gchar * signal, GCallback fn)
Definition at line 1223 of file base-window.c.
References BASE_IS_WINDOW, and BaseWindow::private.
base_window_signal_connect_by_name()
gulong base_window_signal_connect_by_name (BaseWindow * window, const gchar * name, const gchar * signal, GCallback fn)
Definition at line 1239 of file base-window.c.
References BASE_IS_WINDOW, base_window_get_widget(), base_window_signal_connect(), name, and BaseWindow::private.
base_window_signal_connect_with_data()
gulong base_window_signal_connect_with_data (BaseWindow * window, GObject * instance, const gchar * signal, GCallback fn, void * user_data)
Definition at line 1258 of file base-window.c.
References BASE_IS_WINDOW, BaseWindow::private, and user_data.
Referenced by cact_main_tab_init().
base_window_signal_disconnect()
void base_window_signal_disconnect (BaseWindow * window, gulong handler_id)
Definition at line 1289 of file base-window.c.
References BASE_IS_WINDOW, and BaseWindow::private.
Referenced by cact_tree_ieditable_terminate().