MATE Desktop Environment: base-window.h File Reference
base-window.h File Reference
#include <gtk/gtk.h>
#include "base-application.h"
Classes
struct BaseWindow
struct BaseWindowClass
Macros
#define BASE_TYPE_WINDOW (base_window_get_type())
#define BASE_WINDOW(object) (G_TYPE_CHECK_INSTANCE_CAST(object, BASE_TYPE_WINDOW, BaseWindow))
#define BASE_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, BASE_TYPE_WINDOW, BaseWindowClass))
#define BASE_IS_WINDOW(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, BASE_TYPE_WINDOW))
#define BASE_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), BASE_TYPE_WINDOW))
#define BASE_WINDOW_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), BASE_TYPE_WINDOW, BaseWindowClass))
#define BASE_PROP_PARENT "base-prop-window-parent"
#define BASE_PROP_APPLICATION "base-prop-window-application"
#define BASE_PROP_XMLUI_FILENAME "base-prop-window-xmlui-filename"
#define BASE_PROP_HAS_OWN_BUILDER "base-prop-window-has-own-builder"
#define BASE_PROP_TOPLEVEL_NAME "base-prop-window-toplevel-name"
#define BASE_PROP_WSP_NAME "base-prop-window-wsp-name"
#define BASE_PROP_DESTROY_ON_DISPOSE "base-prop-window-destroy-on-dispose"
#define BASE_SIGNAL_INITIALIZE_GTK "base-signal-window-initialize-gtk"
#define BASE_SIGNAL_INITIALIZE_WINDOW "base-signal-window-initialize-window"
#define BASE_SIGNAL_SHOW_WIDGETS "base-signal-window-show-widgets"
Typedefs
typedef struct _BaseWindowPrivate BaseWindowPrivate
typedef struct _BaseWindowClassPrivate BaseWindowClassPrivate
Functions
GType base_window_get_type (void)
gboolean base_window_init (BaseWindow *window)
int base_window_run (BaseWindow *window)
BaseApplication * base_window_get_application (const BaseWindow *window)
BaseWindow * base_window_get_parent (const BaseWindow *window)
GtkWindow * base_window_get_gtk_toplevel (const BaseWindow *window)
GtkWindow * base_window_get_gtk_toplevel_by_name (const BaseWindow *window, const gchar *name)
GtkWidget * base_window_get_widget (const BaseWindow *window, const gchar *name)
void base_window_display_error_dlg (const BaseWindow *parent, const gchar *primary, const gchar *secondary)
gboolean base_window_display_yesno_dlg (const BaseWindow *parent, const gchar *primary, const gchar *secondary)
void base_window_display_message_dlg (const BaseWindow *parent, GSList *message)
gulong base_window_signal_connect (BaseWindow *window, GObject *instance, const gchar *signal, GCallback fn)
gulong base_window_signal_connect_after (BaseWindow *window, GObject *instance, const gchar *signal, GCallback fn)
gulong base_window_signal_connect_by_name (BaseWindow *window, const gchar *name, const gchar *signal, GCallback fn)
gulong base_window_signal_connect_with_data (BaseWindow *window, GObject *instance, const gchar *signal, GCallback fn, void *user_data)
void base_window_signal_disconnect (BaseWindow *window, gulong handler_id)
Macro Definition Documentation
BASE_IS_WINDOW
#define BASE_IS_WINDOW (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, BASE_TYPE_WINDOW))
Definition at line 68 of file base-window.h.
BASE_IS_WINDOW_CLASS
#define BASE_IS_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), BASE_TYPE_WINDOW))
Definition at line 69 of file base-window.h.
BASE_PROP_APPLICATION
#define BASE_PROP_APPLICATION "base-prop-window-application"
Definition at line 186 of file base-window.h.
BASE_PROP_DESTROY_ON_DISPOSE
#define BASE_PROP_DESTROY_ON_DISPOSE "base-prop-window-destroy-on-dispose"
Definition at line 191 of file base-window.h.
BASE_PROP_HAS_OWN_BUILDER
#define BASE_PROP_HAS_OWN_BUILDER "base-prop-window-has-own-builder"
Definition at line 188 of file base-window.h.
BASE_PROP_PARENT
#define BASE_PROP_PARENT "base-prop-window-parent"
Properties defined by the BaseWindow class. They should be provided at object instanciation time.
Instanciation time requires:
either PARENT or APPLICATION
XMLUI_FILENAME
TOPLEVEL_NAME
HAS_OWN_BUILDER
Definition at line 185 of file base-window.h.
BASE_PROP_TOPLEVEL_NAME
#define BASE_PROP_TOPLEVEL_NAME "base-prop-window-toplevel-name"
Definition at line 189 of file base-window.h.
BASE_PROP_WSP_NAME
#define BASE_PROP_WSP_NAME "base-prop-window-wsp-name"
Definition at line 190 of file base-window.h.
BASE_PROP_XMLUI_FILENAME
#define BASE_PROP_XMLUI_FILENAME "base-prop-window-xmlui-filename"
Definition at line 187 of file base-window.h.
BASE_SIGNAL_INITIALIZE_GTK
#define BASE_SIGNAL_INITIALIZE_GTK "base-signal-window-initialize-gtk"
Signals defined by the BaseWindow class.
All signals of this class share the same behavior:
the message is sent to all derived classes, which are free to connect to the signal in order to implement their own code;
finally, the default class handler invokes the corresponding virtual method of the derived class. The derived class should call the parent class method at the end of its implementation.
This way, each class is free to choose to implement the action, either as a signal handler or as a virtual method if it is a class derived from BaseWindow.
See each signal description for detailed information on exactly when the signal is emitted.
Definition at line 212 of file base-window.h.
BASE_SIGNAL_INITIALIZE_WINDOW
#define BASE_SIGNAL_INITIALIZE_WINDOW "base-signal-window-initialize-window"
Definition at line 213 of file base-window.h.
BASE_SIGNAL_SHOW_WIDGETS
#define BASE_SIGNAL_SHOW_WIDGETS "base-signal-window-show-widgets"
Definition at line 214 of file base-window.h.
BASE_TYPE_WINDOW
#define BASE_TYPE_WINDOW (base_window_get_type())
SECTION: base-window @title: BaseWindow @short_description: the BaseWindow base window class definition base-window.h
This is a base class which manages a Gtk+ toplevel.
One global UI manager is allocated at BaseWindow class level. Each window may have its own, provided that it is willing to reinstanciate a new builder each time the window is opened.
Cf. http://bugzilla.gnome.org/show_bug.cgi?id=589746 against Gtk+ 2.16 : a GtkFileChooserWidget embedded in a GtkAssistant is not displayed when run more than once. As a work-around, reload the XML ui in a new builder each time we run an assistant !
Note that having its own builder implies loading in it the required XML file which holds the needed UI definition, and so even if this same XML file has already been load in the common builder.
The common BaseBuilder is never g_object_unref(), so the embedded Gtk toplevels are only destroyed when quitting the program.
Definition at line 65 of file base-window.h.
BASE_WINDOW
#define BASE_WINDOW (object) (G_TYPE_CHECK_INSTANCE_CAST(object, BASE_TYPE_WINDOW, BaseWindow))
Definition at line 66 of file base-window.h.
BASE_WINDOW_CLASS
#define BASE_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, BASE_TYPE_WINDOW, BaseWindowClass))
Definition at line 67 of file base-window.h.
BASE_WINDOW_GET_CLASS
#define BASE_WINDOW_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), BASE_TYPE_WINDOW, BaseWindowClass))
Definition at line 70 of file base-window.h.
Typedef Documentation
BaseWindowClassPrivate
typedef struct _BaseWindowClassPrivate BaseWindowClassPrivate
Definition at line 81 of file base-window.h.
BaseWindowPrivate
typedef struct _BaseWindowPrivate BaseWindowPrivate
Definition at line 72 of file base-window.h.
Function Documentation
base_window_display_error_dlg()
void base_window_display_error_dlg (const BaseWindow * parent, const gchar * primary, const gchar * secondary)
base_window_display_error_dlg: @parent: the BaseWindow parent, may be NULL. @primary: the primary message. @secondary: the secondary message.
Display an error dialog box, with a 'OK' button only.
if @secondary is not null, then @primary is displayed as a bold title.
Definition at line 1124 of file base-window.c.
Referenced by base_iunique_init_with_name(), cact_menubar_edit_on_cut(), cact_menubar_edit_on_delete(), and cact_menubar_file_save_items().
base_window_display_message_dlg()
void base_window_display_message_dlg (const BaseWindow * parent, GSList * msg)
base_window_display_message_dlg: @parent: the BaseWindow parent, may be NULL. @message: the message to be displayed.
Displays an information dialog with only an OK button.
Definition at line 1159 of file base-window.c.
References NULL, and TRUE.
base_window_display_yesno_dlg()
gboolean base_window_display_yesno_dlg (const BaseWindow * parent, const gchar * primary, const gchar * secondary)
base_window_display_yesno_dlg: @parent: the BaseWindow parent, may be NULL. @primary: the primary message. @secondary: the secondary message.
Display a warning dialog box, with a 'OK' button only.
if @secondary is not null, then @primary is displayed as a bold title.
Returns: TRUE if the user has clicked 'Yes', FALSE else.
Definition at line 1142 of file base-window.c.
base_window_get_application()
BaseApplication * base_window_get_application (const BaseWindow * window)
base_window_get_application: @window: this BaseWindow object.
Returns: a pointer on the BaseApplication object.
The returned pointer is owned by the primary allocator of the application ; it should not be g_free() nor g_object_unref() by the caller.
Definition at line 986 of file base-window.c.
References BASE_IS_WINDOW, NULL, and BaseWindow::private.
Referenced by cact_menubar_file_on_new_action(), cact_menubar_file_on_new_menu(), cact_menubar_maintainer_on_test_function(), cact_providers_list_init_view(), cact_schemes_list_init_view(), cact_sort_buttons_new(), and cact_tree_ieditable_initialize().
base_window_get_gtk_toplevel()
GtkWindow * base_window_get_gtk_toplevel (const BaseWindow * window)
base_window_get_gtk_toplevel: @window: this BaseWindow instance..
Returns the top-level GtkWindow attached to this BaseWindow object.
The caller may close the window by g_object_unref()-ing the returned #GtkWindow.
Definition at line 1033 of file base-window.c.
References BASE_IS_WINDOW, NULL, and BaseWindow::private.
Referenced by base_gtk_utils_restore_window_position(), base_gtk_utils_save_window_position(), base_gtk_utils_select_dir(), base_gtk_utils_select_file_with_preview(), and cact_menubar_help_on_about().
base_window_get_gtk_toplevel_by_name()
GtkWindow * base_window_get_gtk_toplevel_by_name (const BaseWindow * window, const gchar * name)
Definition at line 1065 of file base-window.c.
References base_builder_get_toplevel_by_name(), BASE_IS_WINDOW, BASE_WINDOW_GET_CLASS, name, NULL, and BaseWindow::private.
base_window_get_parent()
BaseWindow * base_window_get_parent (const BaseWindow * window)
base_window_get_parent: @window: this BaseWindow instance..
Returns the BaseWindow parent of @window.
The returned object is owned by @window, and should not be freed.
Definition at line 1009 of file base-window.c.
References BASE_IS_WINDOW, NULL, and BaseWindow::private.
base_window_get_type()
GType base_window_get_type (void)
Definition at line 148 of file base-window.c.
base_window_get_widget()
GtkWidget * base_window_get_widget (const BaseWindow * window, const gchar * name)
Definition at line 1099 of file base-window.c.
References BASE_IS_WINDOW, na_gtk_utils_find_widget_by_name(), name, NULL, and BaseWindow::private.
Referenced by base_gtk_utils_toggle_set_initial_state(), base_window_signal_connect_by_name(), cact_iaction_tab_has_label(), cact_main_statusbar_initialize_gtk_toplevel(), cact_main_statusbar_set_locked(), cact_main_tab_enable_page(), cact_main_tab_is_page_enabled(), cact_main_toolbar_activate(), cact_menubar_view_on_tabs_pos_changed(), and cact_preferences_editor_run().
base_window_init()
gboolean base_window_init (BaseWindow * window)
base_window_init: @window: this BaseWindow object.
Initialize the Gtk toplevel if needed, initialize the window at runtime, and show it.
Returns: TRUE if the window has been successfully loaded and initialized and all widgets showed, FALSE else.
Definition at line 661 of file base-window.c.
References base_builder_new(), BASE_IS_BUILDER, BASE_IS_WINDOW, BASE_SIGNAL_INITIALIZE_WINDOW, BASE_SIGNAL_SHOW_WIDGETS, BASE_WINDOW_GET_CLASS, FALSE, BaseWindow::private, and TRUE.
Referenced by base_window_run(), and cact_main_window_new().
base_window_run()
int base_window_run (BaseWindow * window)
base_window_run: @window: this BaseWindow object.
Runs the window.
This function calls the run() virtual method, and does nothing else. If the derived class does not rely on the main loop, it really should implement the run() virtual method.
Returns: the exit code as set by the derived class, or:
BASE_EXIT_CODE_PROGRAM if the window has already been disposed,
BASE_EXIT_CODE_INIT_WINDOW if the window was not and cannot be loaded and initialized.
Definition at line 928 of file base-window.c.
References BASE_EXIT_CODE_INIT_WINDOW, BASE_EXIT_CODE_OK, BASE_EXIT_CODE_PROGRAM, BASE_IS_WINDOW, BASE_WINDOW_GET_CLASS, base_window_init(), and BaseWindow::private.
Referenced by cact_add_capability_dialog_run(), cact_add_scheme_dialog_run(), cact_assistant_export_run(), cact_assistant_import_run(), cact_confirm_logout_run(), cact_export_ask_user(), cact_icon_chooser_choose_icon(), and cact_preferences_editor_run().
base_window_signal_connect()
gulong base_window_signal_connect (BaseWindow * window, GObject * instance, const gchar * signal, GCallback fn)
Records a connected signal, to be disconnected at CactWindow dispose.
Definition at line 1207 of file base-window.c.
References BASE_IS_WINDOW, and BaseWindow::private.
Referenced by base_gtk_utils_toggle_set_initial_state(), base_window_signal_connect_by_name(), cact_iaction_tab_init(), cact_ibasenames_tab_init(), cact_icapabilities_tab_init(), cact_icommand_tab_init(), cact_ienvironment_tab_init(), cact_iexecution_tab_init(), cact_ifolders_tab_init(), cact_imimetypes_tab_init(), cact_iproperties_tab_init(), cact_ischemes_tab_init(), cact_menubar_new(), cact_sort_buttons_new(), and cact_tree_ieditable_initialize().
base_window_signal_connect_after()
gulong base_window_signal_connect_after (BaseWindow * window, GObject * instance, const gchar * signal, GCallback fn)
Definition at line 1223 of file base-window.c.
References BASE_IS_WINDOW, and BaseWindow::private.
base_window_signal_connect_by_name()
gulong base_window_signal_connect_by_name (BaseWindow * window, const gchar * name, const gchar * signal, GCallback fn)
Definition at line 1239 of file base-window.c.
References BASE_IS_WINDOW, base_window_get_widget(), base_window_signal_connect(), name, and BaseWindow::private.
base_window_signal_connect_with_data()
gulong base_window_signal_connect_with_data (BaseWindow * window, GObject * instance, const gchar * signal, GCallback fn, void * user_data)
Definition at line 1258 of file base-window.c.
References BASE_IS_WINDOW, BaseWindow::private, and user_data.
Referenced by cact_main_tab_init().
base_window_signal_disconnect()
void base_window_signal_disconnect (BaseWindow * window, gulong handler_id)
Definition at line 1289 of file base-window.c.
References BASE_IS_WINDOW, and BaseWindow::private.
Referenced by cact_tree_ieditable_terminate().