MATE Desktop Environment: base-application.c File Reference
base-application.c File Reference
#include <glib/gi18n.h>
#include <string.h>
#include "base-application.h"
#include "base-isession.h"
#include "base-iunique.h"
Enumerations
enum {
BASE_PROP_0 , BASE_PROP_ARGC_ID , BASE_PROP_ARGV_ID , BASE_PROP_OPTIONS_ID ,
BASE_PROP_APPLICATION_NAME_ID , BASE_PROP_DESCRIPTION_ID , BASE_PROP_ICON_NAME_ID , BASE_PROP_UNIQUE_NAME_ID ,
BASE_PROP_CODE_ID , BASE_PROP_N_PROPERTIES
}
Functions
GType base_application_get_type (void)
int base_application_run_with_args (BaseApplication *application, int argc, GStrv argv)
gchar * base_application_get_application_name (const BaseApplication *application)
gboolean base_application_is_willing_to_quit (const BaseApplication *application)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BASE_PROP_0
BASE_PROP_ARGC_ID
BASE_PROP_ARGV_ID
BASE_PROP_OPTIONS_ID
BASE_PROP_APPLICATION_NAME_ID
BASE_PROP_DESCRIPTION_ID
BASE_PROP_ICON_NAME_ID
BASE_PROP_UNIQUE_NAME_ID
BASE_PROP_CODE_ID
BASE_PROP_N_PROPERTIES
Definition at line 66 of file base-application.c.
Function Documentation
base_application_get_application_name()
gchar * base_application_get_application_name (const BaseApplication * application)
base_application_get_application_name: @application: this BaseApplication instance.
Returns: the application name as a newly allocated string which should be be g_free() by the caller.
Definition at line 733 of file base-application.c.
References BASE_IS_APPLICATION, name, NULL, and BaseApplication::private.
base_application_get_type()
GType base_application_get_type (void)
Definition at line 111 of file base-application.c.
base_application_is_willing_to_quit()
gboolean base_application_is_willing_to_quit (const BaseApplication * application)
base_application_is_willing_to_quit: @application: this BaseApplication instance.
Returns: TRUE if the application is willing to quit, FALSE else.
This function is typically called from the derived application, when the user has required the termination, in order to let it handle unsaved modifications.
Definition at line 758 of file base-application.c.
References BASE_IS_APPLICATION, BASE_IS_ISESSION, BASE_ISESSION, base_isession_is_willing_to_quit(), and TRUE.
Referenced by cact_menubar_maintainer_on_test_function().
base_application_run_with_args()
int base_application_run_with_args (BaseApplication * application, int argc, GStrv argv)
base_application_run_with_args: @application: this BaseApplication -derived instance.
Starts and runs the application. Takes care of creating, initializing, and running the main window.
All steps are implemented as virtual functions which provide some suitable defaults, and may be overridden by a derived class.
Returns: an int code suitable as an exit code for the program.
Though it is defined as a virtual function itself, it should be very seldomly needed to override this in a derived class.
Definition at line 466 of file base-application.c.
References BASE_EXIT_CODE_OK, BASE_EXIT_CODE_PROGRAM, BASE_IS_APPLICATION, and BaseApplication::private.
Referenced by main().