MATE Desktop Environment: bookmark-agent.h File Reference
bookmark-agent.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <time.h>
Classes
struct BookmarkItem
struct BookmarkAgent
struct BookmarkAgentClass
Macros
#define BOOKMARK_AGENT_TYPE (bookmark_agent_get_type ())
#define BOOKMARK_AGENT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), BOOKMARK_AGENT_TYPE, BookmarkAgent))
#define BOOKMARK_AGENT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), BOOKMARK_AGENT_TYPE, BookmarkAgentClass))
#define IS_BOOKMARK_AGENT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), BOOKMARK_AGENT_TYPE))
#define IS_BOOKMARK_AGENT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), BOOKMARK_AGENT_TYPE))
#define BOOKMARK_AGENT_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), BOOKMARK_AGENT_TYPE, BookmarkAgentClass))
#define BOOKMARK_AGENT_STORE_STATUS_PROP "store-status"
#define BOOKMARK_AGENT_ITEMS_PROP "items"
Enumerations
enum BookmarkStoreStatus { BOOKMARK_STORE_DEFAULT_ONLY , BOOKMARK_STORE_DEFAULT , BOOKMARK_STORE_USER , BOOKMARK_STORE_ABSENT }
enum BookmarkStoreType {
BOOKMARK_STORE_USER_APPS = 0 , BOOKMARK_STORE_USER_DOCS = 1 , BOOKMARK_STORE_USER_DIRS = 2 , BOOKMARK_STORE_RECENT_APPS = 3 ,
BOOKMARK_STORE_RECENT_DOCS = 4 , BOOKMARK_STORE_SYSTEM = 5 , BOOKMARK_STORE_N_TYPES = 6
}
Functions
GType bookmark_agent_get_type (void)
BookmarkAgent * bookmark_agent_get_instance (BookmarkStoreType type)
gboolean bookmark_agent_has_item (BookmarkAgent *this, const gchar *uri)
void bookmark_agent_add_item (BookmarkAgent *this, const BookmarkItem *item)
void bookmark_agent_move_item (BookmarkAgent *this, const gchar *uri, const gchar *uri_new)
void bookmark_agent_remove_item (BookmarkAgent *this, const gchar *uri)
void bookmark_agent_reorder_items (BookmarkAgent *this, const gchar **uris)
void bookmark_agent_update_from_bookmark_file (BookmarkAgent *this, GBookmarkFile *store)
void bookmark_agent_purge_items (BookmarkAgent *this)
void bookmark_item_free (BookmarkItem *item)
Macro Definition Documentation
BOOKMARK_AGENT
#define BOOKMARK_AGENT (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), BOOKMARK_AGENT_TYPE, BookmarkAgent))
Definition at line 34 of file bookmark-agent.h.
BOOKMARK_AGENT_CLASS
#define BOOKMARK_AGENT_CLASS (c) (G_TYPE_CHECK_CLASS_CAST ((c), BOOKMARK_AGENT_TYPE, BookmarkAgentClass))
Definition at line 35 of file bookmark-agent.h.
BOOKMARK_AGENT_GET_CLASS
#define BOOKMARK_AGENT_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), BOOKMARK_AGENT_TYPE, BookmarkAgentClass))
Definition at line 38 of file bookmark-agent.h.
BOOKMARK_AGENT_ITEMS_PROP
#define BOOKMARK_AGENT_ITEMS_PROP "items"
Definition at line 41 of file bookmark-agent.h.
BOOKMARK_AGENT_STORE_STATUS_PROP
#define BOOKMARK_AGENT_STORE_STATUS_PROP "store-status"
Definition at line 40 of file bookmark-agent.h.
BOOKMARK_AGENT_TYPE
#define BOOKMARK_AGENT_TYPE (bookmark_agent_get_type ())
Definition at line 33 of file bookmark-agent.h.
IS_BOOKMARK_AGENT
#define IS_BOOKMARK_AGENT (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), BOOKMARK_AGENT_TYPE))
Definition at line 36 of file bookmark-agent.h.
IS_BOOKMARK_AGENT_CLASS
#define IS_BOOKMARK_AGENT_CLASS (c) (G_TYPE_CHECK_CLASS_TYPE ((c), BOOKMARK_AGENT_TYPE))
Definition at line 37 of file bookmark-agent.h.
Enumeration Type Documentation
BookmarkStoreStatus
enum BookmarkStoreStatus
Enumerator
BOOKMARK_STORE_DEFAULT_ONLY
BOOKMARK_STORE_DEFAULT
BOOKMARK_STORE_USER
BOOKMARK_STORE_ABSENT
Definition at line 57 of file bookmark-agent.h.
BookmarkStoreType
enum BookmarkStoreType
Enumerator
BOOKMARK_STORE_USER_APPS
BOOKMARK_STORE_USER_DOCS
BOOKMARK_STORE_USER_DIRS
BOOKMARK_STORE_RECENT_APPS
BOOKMARK_STORE_RECENT_DOCS
BOOKMARK_STORE_SYSTEM
BOOKMARK_STORE_N_TYPES
Definition at line 64 of file bookmark-agent.h.
Function Documentation
bookmark_agent_add_item()
void bookmark_agent_add_item (BookmarkAgent * this, const BookmarkItem * item)
Definition at line 157 of file bookmark-agent.c.
References item.
bookmark_agent_get_instance()
BookmarkAgent * bookmark_agent_get_instance (BookmarkStoreType type)
Definition at line 569 of file bookmark-agent.c.
References BOOKMARK_STORE_N_TYPES, NULL, and type.
bookmark_agent_get_type()
GType bookmark_agent_get_type (void)
Definition at line 125 of file bookmark-agent.c.
References NULL.
bookmark_agent_has_item()
gboolean bookmark_agent_has_item (BookmarkAgent * this, const gchar * uri)
Definition at line 150 of file bookmark-agent.c.
Referenced by bookmark_agent_remove_item().
bookmark_agent_move_item()
void bookmark_agent_move_item (BookmarkAgent * this, const gchar * uri, const gchar * uri_new)
Definition at line 188 of file bookmark-agent.c.
References error, NULL, and TYPE_IS_RECENT.
bookmark_agent_purge_items()
void bookmark_agent_purge_items (BookmarkAgent * this)
Definition at line 206 of file bookmark-agent.c.
References error, NULL, and TYPE_IS_RECENT.
bookmark_agent_remove_item()
void bookmark_agent_remove_item (BookmarkAgent * this, const gchar * uri)
Definition at line 237 of file bookmark-agent.c.
References bookmark_agent_has_item(), error, NULL, and TYPE_IS_RECENT.
bookmark_agent_reorder_items()
void bookmark_agent_reorder_items (BookmarkAgent * this, const gchar ** uris)
Definition at line 283 of file bookmark-agent.c.
bookmark_agent_update_from_bookmark_file()
void bookmark_agent_update_from_bookmark_file (BookmarkAgent * this, GBookmarkFile * store)
Definition at line 355 of file bookmark-agent.c.
References bookmark_item_free(), IS_BOOKMARK_AGENT, and item.
bookmark_item_free()
void bookmark_item_free (BookmarkItem * item)
Definition at line 391 of file bookmark-agent.c.
References item.
Referenced by bookmark_agent_update_from_bookmark_file().