MATE Desktop Environment: button-widget.c File Reference
button-widget.c File Reference
#include <config.h>
#include <string.h>
#include <glib/gi18n.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <gdk/gdkx.h>
#include "button-widget.h"
#include "panel-widget.h"
#include "panel-types.h"
#include "panel-util.h"
#include "panel-config-global.h"
#include "panel-marshal.h"
#include "panel-typebuiltins.h"
#include "panel-globals.h"
#include "panel-enums.h"
#include "panel-enums-gsettings.h"
Macros
#define BUTTON_WIDGET_DISPLACEMENT 2
Enumerations
enum {
PROP_0 , PROP_ACTIVATABLE , PROP_IGNORE_LEAVE , PROP_HAS_ARROW ,
PROP_DND_HIGHLIGHT , PROP_ORIENTATION , PROP_ICON_NAME
}
Functions
GtkWidget * button_widget_new (const char *filename, gboolean arrow, PanelOrientation orientation)
void button_widget_set_activatable (ButtonWidget *button, gboolean activatable)
gboolean button_widget_get_activatable (ButtonWidget *button)
void button_widget_set_icon_name (ButtonWidget *button, const char *icon_name)
const char * button_widget_get_icon_name (ButtonWidget *button)
void button_widget_set_orientation (ButtonWidget *button, PanelOrientation orientation)
PanelOrientation button_widget_get_orientation (ButtonWidget *button)
void button_widget_set_has_arrow (ButtonWidget *button, gboolean has_arrow)
gboolean button_widget_get_has_arrow (ButtonWidget *button)
void button_widget_set_dnd_highlight (ButtonWidget *button, gboolean dnd_highlight)
gboolean button_widget_get_dnd_highlight (ButtonWidget *button)
void button_widget_set_ignore_leave (ButtonWidget *button, gboolean ignore_leave)
gboolean button_widget_get_ignore_leave (ButtonWidget *button)
GtkIconTheme * button_widget_get_icon_theme (ButtonWidget *button)
cairo_surface_t * button_widget_get_surface (ButtonWidget *button)
Macro Definition Documentation
BUTTON_WIDGET_DISPLACEMENT
#define BUTTON_WIDGET_DISPLACEMENT 2
Definition at line 55 of file button-widget.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_ACTIVATABLE
PROP_IGNORE_LEAVE
PROP_HAS_ARROW
PROP_DND_HIGHLIGHT
PROP_ORIENTATION
PROP_ICON_NAME
Definition at line 45 of file button-widget.c.
Function Documentation
button_widget_get_activatable()
gboolean button_widget_get_activatable (ButtonWidget * button)
Definition at line 805 of file button-widget.c.
References BUTTON_IS_WIDGET, FALSE, and _ButtonWidget::priv.
button_widget_get_dnd_highlight()
gboolean button_widget_get_dnd_highlight (ButtonWidget * button)
Definition at line 912 of file button-widget.c.
References BUTTON_IS_WIDGET, FALSE, and _ButtonWidget::priv.
button_widget_get_has_arrow()
gboolean button_widget_get_has_arrow (ButtonWidget * button)
Definition at line 886 of file button-widget.c.
References BUTTON_IS_WIDGET, FALSE, and _ButtonWidget::priv.
button_widget_get_icon_name()
const char * button_widget_get_icon_name (ButtonWidget * button)
Definition at line 833 of file button-widget.c.
References BUTTON_IS_WIDGET, NULL, and _ButtonWidget::priv.
Referenced by panel_drawer_set_dnd_enabled().
button_widget_get_icon_theme()
GtkIconTheme * button_widget_get_icon_theme (ButtonWidget * button)
Definition at line 946 of file button-widget.c.
References BUTTON_IS_WIDGET, NULL, and _ButtonWidget::priv.
button_widget_get_ignore_leave()
gboolean button_widget_get_ignore_leave (ButtonWidget * button)
Definition at line 938 of file button-widget.c.
References BUTTON_IS_WIDGET, FALSE, and _ButtonWidget::priv.
button_widget_get_orientation()
PanelOrientation button_widget_get_orientation (ButtonWidget * button)
Definition at line 860 of file button-widget.c.
References BUTTON_IS_WIDGET, and _ButtonWidget::priv.
button_widget_get_surface()
cairo_surface_t * button_widget_get_surface (ButtonWidget * button)
Definition at line 954 of file button-widget.c.
References BUTTON_IS_WIDGET, NULL, and _ButtonWidget::priv.
Referenced by panel_launcher_set_dnd_enabled().
button_widget_new()
GtkWidget * button_widget_new (const char * filename, gboolean arrow, PanelOrientation orientation)
Definition at line 771 of file button-widget.c.
References BUTTON_TYPE_WIDGET, and NULL.
button_widget_set_activatable()
void button_widget_set_activatable (ButtonWidget * button, gboolean activatable)
Definition at line 787 of file button-widget.c.
References BUTTON_IS_WIDGET, FALSE, and _ButtonWidget::priv.
button_widget_set_dnd_highlight()
void button_widget_set_dnd_highlight (ButtonWidget * button, gboolean dnd_highlight)
Definition at line 894 of file button-widget.c.
References BUTTON_IS_WIDGET, FALSE, and _ButtonWidget::priv.
button_widget_set_has_arrow()
void button_widget_set_has_arrow (ButtonWidget * button, gboolean has_arrow)
Definition at line 868 of file button-widget.c.
References BUTTON_IS_WIDGET, FALSE, and _ButtonWidget::priv.
Referenced by panel_menu_button_set_has_arrow().
button_widget_set_icon_name()
void button_widget_set_icon_name (ButtonWidget * button, const char * icon_name)
Definition at line 813 of file button-widget.c.
References BUTTON_IS_WIDGET, and _ButtonWidget::priv.
Referenced by panel_action_button_set_type().
button_widget_set_ignore_leave()
void button_widget_set_ignore_leave (ButtonWidget * button, gboolean ignore_leave)
Definition at line 920 of file button-widget.c.
References BUTTON_IS_WIDGET, FALSE, and _ButtonWidget::priv.
Referenced by panel_menu_button_popup_menu().
button_widget_set_orientation()
void button_widget_set_orientation (ButtonWidget * button, PanelOrientation orientation)
Definition at line 841 of file button-widget.c.
References BUTTON_IS_WIDGET, and _ButtonWidget::priv.
Referenced by orientation_change().