MATE Desktop Environment: cact-main-window.c File Reference
cact-main-window.c File Reference
#include <glib/gi18n.h>
#include <stdlib.h>
#include <api/na-object-api.h>
#include <api/na-timeout.h>
#include <core/na-iprefs.h>
#include <core/na-pivot.h>
#include "base-isession.h"
#include "cact-iaction-tab.h"
#include "cact-icommand-tab.h"
#include "cact-ibasenames-tab.h"
#include "cact-imimetypes-tab.h"
#include "cact-ifolders-tab.h"
#include "cact-ischemes-tab.h"
#include "cact-icapabilities-tab.h"
#include "cact-ienvironment-tab.h"
#include "cact-iexecution-tab.h"
#include "cact-iproperties-tab.h"
#include "cact-main-tab.h"
#include "cact-main-statusbar.h"
#include "cact-main-window.h"
#include "cact-marshal.h"
#include "cact-menubar.h"
#include "cact-tree-view.h"
#include "cact-confirm-logout.h"
#include "cact-sort-buttons.h"
Enumerations
enum {
MAIN_PROP_0 = 0 , MAIN_PROP_ITEM_ID , MAIN_PROP_PROFILE_ID , MAIN_PROP_CONTEXT_ID ,
MAIN_PROP_EDITABLE_ID , MAIN_PROP_REASON_ID , MAIN_PROP_N_PROPERTIES
}
enum {
MAIN_ITEM_UPDATED , TAB_ITEM_UPDATED , SELECTION_CHANGED , CONTEXT_MENU ,
LAST_SIGNAL
}
Functions
GType cact_main_window_get_type (void)
CactMainWindow * cact_main_window_new (const CactApplication *application)
CactClipboard * cact_main_window_get_clipboard (const CactMainWindow *window)
CactTreeView * cact_main_window_get_items_view (const CactMainWindow *window)
void cact_main_window_reload (CactMainWindow *window)
void cact_main_window_block_reload (CactMainWindow *window)
gboolean cact_main_window_quit (CactMainWindow *window)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MAIN_PROP_0
MAIN_PROP_ITEM_ID
MAIN_PROP_PROFILE_ID
MAIN_PROP_CONTEXT_ID
MAIN_PROP_EDITABLE_ID
MAIN_PROP_REASON_ID
MAIN_PROP_N_PROPERTIES
Definition at line 133 of file cact-main-window.c.
anonymous enum
anonymous enum
Enumerator
MAIN_ITEM_UPDATED
TAB_ITEM_UPDATED
SELECTION_CHANGED
CONTEXT_MENU
LAST_SIGNAL
Definition at line 147 of file cact-main-window.c.
Function Documentation
cact_main_window_block_reload()
void cact_main_window_block_reload (CactMainWindow * window)
cact_main_window_block_reload: @window: this CactMainWindow instance.
Temporarily blocks the handling of pivot-items-changed signal.
Definition at line 1036 of file cact-main-window.c.
References CACT_IS_MAIN_WINDOW, na_timeout_event(), PIVOT_SIGNAL_ITEMS_CHANGED, and CactMainWindow::private.
Referenced by cact_menubar_file_save_items().
cact_main_window_get_clipboard()
CactClipboard * cact_main_window_get_clipboard (const CactMainWindow * window)
cact_main_window_get_clipboard: @window: this CactMainWindow instance.
Returns: the CactClipboard convenience object.
Definition at line 965 of file cact-main-window.c.
References CACT_IS_MAIN_WINDOW, NULL, and CactMainWindow::private.
Referenced by cact_menubar_edit_on_copy(), cact_menubar_edit_on_cut(), and cact_menubar_maintainer_on_dump_clipboard().
cact_main_window_get_items_view()
CactTreeView * cact_main_window_get_items_view (const CactMainWindow * window)
cact_main_window_get_items_view: @window: this CactMainWindow instance.
Returns: The CactTreeView convenience object.
Definition at line 988 of file cact-main-window.c.
References CACT_IS_MAIN_WINDOW, NULL, and CactMainWindow::private.
Referenced by cact_menubar_edit_on_cut(), cact_menubar_edit_on_delete(), cact_menubar_edit_on_duplicate(), cact_menubar_edit_on_paste(), cact_menubar_edit_on_paste_into(), cact_menubar_file_on_new_action(), cact_menubar_file_on_new_menu(), cact_menubar_file_on_new_profile(), cact_menubar_file_save_items(), cact_menubar_maintainer_on_brief_tree_store_dump(), cact_menubar_maintainer_on_list_modified_items(), cact_menubar_view_on_collapse_all(), and cact_menubar_view_on_expand_all().
cact_main_window_get_type()
GType cact_main_window_get_type (void)
Definition at line 208 of file cact-main-window.c.
cact_main_window_new()
CactMainWindow * cact_main_window_new (const CactApplication * application)
Returns a newly allocated CactMainWindow object.
Definition at line 815 of file cact-main-window.c.
References BASE_PROP_APPLICATION, BASE_PROP_DESTROY_ON_DISPOSE, BASE_PROP_TOPLEVEL_NAME, BASE_PROP_WSP_NAME, BASE_PROP_XMLUI_FILENAME, BASE_WINDOW, base_window_init(), CACT_IS_APPLICATION, CACT_TYPE_MAIN_WINDOW, NULL, and TRUE.
cact_main_window_quit()
gboolean cact_main_window_quit (CactMainWindow * window)
cact_main_window_quit: @window: the CactMainWindow main window.
Quit the window, thus terminating the application.
Returns: TRUE if the application will terminate, and the @window object is no more valid; FALSE if the application will continue to run.
Definition at line 1343 of file cact-main-window.c.
References CACT_IS_MAIN_WINDOW, FALSE, CactMainWindow::private, and TRUE.
Referenced by cact_menubar_file_on_quit().
cact_main_window_reload()
void cact_main_window_reload (CactMainWindow * window)
cact_main_window_reload: @window: this CactMainWindow instance.
Refresh the list of items. If there is some non-yet saved modifications, a confirmation is required before giving up with them.
Definition at line 1013 of file cact-main-window.c.
References CACT_IS_MAIN_WINDOW, and CactMainWindow::private.
Referenced by cact_menubar_edit_on_reload().