MATE Desktop Environment: cact-sort-buttons.h File Reference
cact-sort-buttons.h File Reference
#include "base-window.h"
Classes
struct CactSortButtons
struct CactSortButtonsClass
Macros
#define CACT_TYPE_SORT_BUTTONS (cact_sort_buttons_get_type())
#define CACT_SORT_BUTTONS(object) (G_TYPE_CHECK_INSTANCE_CAST(object, CACT_TYPE_SORT_BUTTONS, CactSortButtons))
#define CACT_SORT_BUTTONS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, CACT_TYPE_SORT_BUTTONS, CactSortButtonsClass))
#define CACT_IS_SORT_BUTTONS(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, CACT_TYPE_SORT_BUTTONS))
#define CACT_IS_SORT_BUTTONS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), CACT_TYPE_SORT_BUTTONS))
#define CACT_SORT_BUTTONS_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), CACT_TYPE_SORT_BUTTONS, CactSortButtonsClass))
Typedefs
typedef struct _CactSortButtonsPrivate CactSortButtonsPrivate
typedef struct _CactSortButtonsClassPrivate CactSortButtonsClassPrivate
Functions
GType cact_sort_buttons_get_type (void)
CactSortButtons * cact_sort_buttons_new (BaseWindow *window)
Macro Definition Documentation
CACT_IS_SORT_BUTTONS
#define CACT_IS_SORT_BUTTONS (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, CACT_TYPE_SORT_BUTTONS))
Definition at line 58 of file cact-sort-buttons.h.
CACT_IS_SORT_BUTTONS_CLASS
#define CACT_IS_SORT_BUTTONS_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), CACT_TYPE_SORT_BUTTONS))
Definition at line 59 of file cact-sort-buttons.h.
CACT_SORT_BUTTONS
#define CACT_SORT_BUTTONS (object) (G_TYPE_CHECK_INSTANCE_CAST(object, CACT_TYPE_SORT_BUTTONS, CactSortButtons))
Definition at line 56 of file cact-sort-buttons.h.
CACT_SORT_BUTTONS_CLASS
#define CACT_SORT_BUTTONS_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, CACT_TYPE_SORT_BUTTONS, CactSortButtonsClass))
Definition at line 57 of file cact-sort-buttons.h.
CACT_SORT_BUTTONS_GET_CLASS
#define CACT_SORT_BUTTONS_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), CACT_TYPE_SORT_BUTTONS, CactSortButtonsClass))
Definition at line 60 of file cact-sort-buttons.h.
CACT_TYPE_SORT_BUTTONS
#define CACT_TYPE_SORT_BUTTONS (cact_sort_buttons_get_type())
SECTION: cact-sort-buttons @title: CactSortButtons @short_description: The Sort Buttons class definition cact-sort-buttons.h
A convenience class to manager sort buttons in the user interface.
The sort order mode is monitored, so that buttons automatically display the right order mode if it is modified by another way (e.g. from Preferences editor).
Modifying the sort order mode requires that:
level zero is writable (see NAUpdater)
preferences are not locked (see NAUpdater)
sort order mode is not a mandatory preference.
Definition at line 55 of file cact-sort-buttons.h.
Typedef Documentation
CactSortButtonsClassPrivate
typedef struct _CactSortButtonsClassPrivate CactSortButtonsClassPrivate
Definition at line 71 of file cact-sort-buttons.h.
CactSortButtonsPrivate
typedef struct _CactSortButtonsPrivate CactSortButtonsPrivate
Definition at line 62 of file cact-sort-buttons.h.
Function Documentation
cact_sort_buttons_get_type()
GType cact_sort_buttons_get_type (void)
Definition at line 90 of file cact-sort-buttons.c.
References type.
cact_sort_buttons_new()
CactSortButtons * cact_sort_buttons_new (BaseWindow * window)
cact_sort_buttons_new: @window: the main window.
Returns: a new CactSortButtons object.
Definition at line 213 of file cact-sort-buttons.c.
References BASE_IS_WINDOW, BASE_SIGNAL_INITIALIZE_WINDOW, base_window_get_application(), base_window_signal_connect(), CACT_APPLICATION, cact_application_get_updater(), CACT_TYPE_SORT_BUTTONS, NULL, CactSortButtons::private, and WINDOW_DATA_SORT_BUTTONS.
Referenced by cact_menubar_new().