MATE Desktop Environment: cact-iaction-tab.h File Reference
cact-iaction-tab.h File Reference
#include <glib-object.h>
Classes
struct CactIActionTabInterface
Macros
#define CACT_TYPE_IACTION_TAB (cact_iaction_tab_get_type())
#define CACT_IACTION_TAB(instance) (G_TYPE_CHECK_INSTANCE_CAST(instance, CACT_TYPE_IACTION_TAB, CactIActionTab))
#define CACT_IS_IACTION_TAB(instance) (G_TYPE_CHECK_INSTANCE_TYPE(instance, CACT_TYPE_IACTION_TAB))
#define CACT_IACTION_TAB_GET_INTERFACE(instance) (G_TYPE_INSTANCE_GET_INTERFACE((instance), CACT_TYPE_IACTION_TAB, CactIActionTabInterface))
Typedefs
typedef struct _CactIActionTab CactIActionTab
typedef struct _CactIActionTabInterfacePrivate CactIActionTabInterfacePrivate
Functions
GType cact_iaction_tab_get_type (void)
void cact_iaction_tab_init (CactIActionTab *instance)
gboolean cact_iaction_tab_has_label (CactIActionTab *instance)
Macro Definition Documentation
CACT_IACTION_TAB
#define CACT_IACTION_TAB (instance) (G_TYPE_CHECK_INSTANCE_CAST(instance, CACT_TYPE_IACTION_TAB, CactIActionTab))
Definition at line 50 of file cact-iaction-tab.h.
CACT_IACTION_TAB_GET_INTERFACE
#define CACT_IACTION_TAB_GET_INTERFACE (instance) (G_TYPE_INSTANCE_GET_INTERFACE((instance), CACT_TYPE_IACTION_TAB, CactIActionTabInterface))
Definition at line 52 of file cact-iaction-tab.h.
CACT_IS_IACTION_TAB
#define CACT_IS_IACTION_TAB (instance) (G_TYPE_CHECK_INSTANCE_TYPE(instance, CACT_TYPE_IACTION_TAB))
Definition at line 51 of file cact-iaction-tab.h.
CACT_TYPE_IACTION_TAB
#define CACT_TYPE_IACTION_TAB (cact_iaction_tab_get_type())
SECTION: cact_iaction_tab @short_description: CactIActionTab interface definition. cact/cact-iaction-tab.h
This interface implements the "Caja Menu Item" tab of the notebook.
Entry fields are enabled, as soon as an edited item has been set as a property of the main window, Fields are those of NAObjectItem (i.e. not NAObjectProfile, not NAIContext, but may be NAObjectAction specific).
Definition at line 49 of file cact-iaction-tab.h.
Typedef Documentation
CactIActionTab
typedef struct _CactIActionTab CactIActionTab
Definition at line 54 of file cact-iaction-tab.h.
CactIActionTabInterfacePrivate
typedef struct _CactIActionTabInterfacePrivate CactIActionTabInterfacePrivate
Definition at line 55 of file cact-iaction-tab.h.
Function Documentation
cact_iaction_tab_get_type()
GType cact_iaction_tab_get_type (void)
Definition at line 100 of file cact-iaction-tab.c.
cact_iaction_tab_has_label()
gboolean cact_iaction_tab_has_label (CactIActionTab * instance)
cact_iaction_tab_has_label: @window: this CactIActionTab instance.
An action or a menu can only be written if it has at least a label.
Returns TRUE if the label of the action or of the menu is not empty.
Definition at line 352 of file cact-iaction-tab.c.
References BASE_WINDOW, base_window_get_widget(), CACT_IS_IACTION_TAB, FALSE, and label.
cact_iaction_tab_init()
void cact_iaction_tab_init (CactIActionTab * instance)
cact_iaction_tab_init: @instance: this CactIActionTab instance.
Initialize the interface Connect to BaseWindow signals
Definition at line 176 of file cact-iaction-tab.c.
References BASE_SIGNAL_INITIALIZE_GTK, BASE_SIGNAL_INITIALIZE_WINDOW, BASE_WINDOW, base_window_signal_connect(), CACT_IS_IACTION_TAB, cact_main_tab_init(), CACT_MAIN_WINDOW, data, FALSE, NULL, and TAB_ACTION.