MATE Desktop Environment: cact-application.c File Reference
cact-application.c File Reference
#include <glib.h>
#include <glib/gi18n.h>
#include <api/na-core-utils.h>
#include "cact-application.h"
#include "cact-main-window.h"
Functions
GType cact_application_get_type (void)
CactApplication * cact_application_new (void)
NAUpdater * cact_application_get_updater (const CactApplication *application)
Function Documentation
cact_application_get_type()
GType cact_application_get_type (void)
Definition at line 83 of file cact-application.c.
cact_application_get_updater()
NAUpdater * cact_application_get_updater (const CactApplication * application)
cact_application_get_updater: @application: this CactApplication object.
Returns a pointer on the NAUpdater object.
The returned pointer is owned by the CactApplication object. It should not be g_free() not g_object_unref() by the caller.
Definition at line 339 of file cact-application.c.
References CACT_IS_APPLICATION, NULL, and CactApplication::private.
Referenced by cact_menubar_file_on_new_action(), cact_menubar_file_on_new_menu(), cact_providers_list_init_view(), cact_schemes_list_init_view(), cact_sort_buttons_new(), and cact_tree_ieditable_initialize().
cact_application_new()
CactApplication * cact_application_new (void)
cact_application_new:
Returns: a newly allocated CactApplication object.
Definition at line 213 of file cact-application.c.
References BASE_PROP_APPLICATION_NAME, BASE_PROP_DESCRIPTION, BASE_PROP_ICON_NAME, BASE_PROP_OPTIONS, BASE_PROP_UNIQUE_NAME, CACT_TYPE_APPLICATION, NULL, and PACKAGE.
Referenced by main().