MATE Desktop Environment: cact-menubar.c File Reference
cact-menubar.c File Reference
#include <glib/gi18n.h>
#include <core/na-io-provider.h>
#include <core/na-iprefs.h>
#include "cact-application.h"
#include "cact-main-statusbar.h"
#include "cact-main-toolbar.h"
#include "cact-main-tab.h"
#include "cact-menubar-priv.h"
#include "cact-sort-buttons.h"
#include "cact-tree-view.h"
Macros
#define MENUBAR_PROP_STATUS_CONTEXT "menubar-status-context"
#define MENUBAR_PROP_MAIN_STATUS_CONTEXT "menubar-main-status-context"
Enumerations
enum { UPDATE_SENSITIVITIES , LAST_SIGNAL }
Functions
GType cact_menubar_get_type (void)
CactMenubar * cact_menubar_new (BaseWindow *window)
: the name of the item in a menu.
cact_menubar_enable_item: @bar: this CactMenubar instance.
@enabled: whether this item should be enabled or not.
Enable/disable an item in an menu.
void cact_menubar_enable_item (const CactMenubar *bar, const gchar *name, gboolean enabled)
void cact_menubar_save_items (BaseWindow *window)
Macro Definition Documentation
MENUBAR_PROP_MAIN_STATUS_CONTEXT
#define MENUBAR_PROP_MAIN_STATUS_CONTEXT "menubar-main-status-context"
Definition at line 209 of file cact-menubar.c.
MENUBAR_PROP_STATUS_CONTEXT
#define MENUBAR_PROP_STATUS_CONTEXT "menubar-status-context"
Definition at line 208 of file cact-menubar.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
UPDATE_SENSITIVITIES
LAST_SIGNAL
Definition at line 213 of file cact-menubar.c.
Function Documentation
cact_menubar_enable_item()
void cact_menubar_enable_item (const CactMenubar * bar, const gchar * name, gboolean enabled)
Definition at line 923 of file cact-menubar.c.
References action, _CactMenubarPrivate::action_group, _CactMenubarPrivate::dispose_has_run, name, and CactMenubar::private.
Referenced by cact_menubar_edit_on_update_sensitivities(), cact_menubar_file_on_update_sensitivities(), cact_menubar_help_on_update_sensitivities(), cact_menubar_tools_on_update_sensitivities(), and cact_menubar_view_on_update_sensitivities().
cact_menubar_get_type()
GType cact_menubar_get_type (void)
Definition at line 246 of file cact-menubar.c.
References type.
cact_menubar_new()
CactMenubar * cact_menubar_new (BaseWindow * window)
cact_menubar_new: @window: the window which embeds the menubar, usually the CactMainWindow.
The created menubar attachs itself to the @window; it also connect a weak reference to this same @window, thus automatically g_object_unref() -ing itself at @window finalization time.
The menubar also takes advantage of BaseWindow messages to initialize its Gtk widgets.
Returns: a new CactMenubar object.
Definition at line 411 of file cact-menubar.c.
References BASE_IS_WINDOW, BASE_SIGNAL_INITIALIZE_WINDOW, base_window_signal_connect(), cact_sort_buttons_new(), CACT_TYPE_MENUBAR, NULL, CactMenubar::private, _CactMenubarPrivate::sort_buttons, _CactMenubarPrivate::window, and WINDOW_DATA_MENUBAR.
cact_menubar_save_items()
void cact_menubar_save_items (BaseWindow * window)
cact_menubar_save_items: @window: the BaseWindow
Definition at line 939 of file cact-menubar.c.
References cact_menubar_file_save_items().