MATE Desktop Environment: cact-assistant-export.h File Reference
cact-assistant-export.h File Reference
#include "base-assistant.h"
Classes
struct CactAssistantExport
struct CactAssistantExportClass
Macros
#define CACT_TYPE_ASSISTANT_EXPORT (cact_assistant_export_get_type())
#define CACT_ASSISTANT_EXPORT(object) (G_TYPE_CHECK_INSTANCE_CAST(object, CACT_TYPE_ASSISTANT_EXPORT, CactAssistantExport))
#define CACT_ASSISTANT_EXPORT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, CACT_TYPE_ASSISTANT_EXPORT, CactAssistantExportClass))
#define CACT_IS_ASSISTANT_EXPORT(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, CACT_TYPE_ASSISTANT_EXPORT))
#define CACT_IS_ASSISTANT_EXPORT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), CACT_TYPE_ASSISTANT_EXPORT))
#define CACT_ASSISTANT_EXPORT_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), CACT_TYPE_ASSISTANT_EXPORT, CactAssistantExportClass))
Typedefs
typedef struct _CactAssistantExportPrivate CactAssistantExportPrivate
typedef struct _CactAssistantExportClassPrivate CactAssistantExportClassPrivate
Functions
GType cact_assistant_export_get_type (void)
void cact_assistant_export_run (BaseWindow *parent)
Macro Definition Documentation
CACT_ASSISTANT_EXPORT
#define CACT_ASSISTANT_EXPORT (object) (G_TYPE_CHECK_INSTANCE_CAST(object, CACT_TYPE_ASSISTANT_EXPORT, CactAssistantExport))
Definition at line 69 of file cact-assistant-export.h.
CACT_ASSISTANT_EXPORT_CLASS
#define CACT_ASSISTANT_EXPORT_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, CACT_TYPE_ASSISTANT_EXPORT, CactAssistantExportClass))
Definition at line 70 of file cact-assistant-export.h.
CACT_ASSISTANT_EXPORT_GET_CLASS
#define CACT_ASSISTANT_EXPORT_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), CACT_TYPE_ASSISTANT_EXPORT, CactAssistantExportClass))
Definition at line 73 of file cact-assistant-export.h.
CACT_IS_ASSISTANT_EXPORT
#define CACT_IS_ASSISTANT_EXPORT (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, CACT_TYPE_ASSISTANT_EXPORT))
Definition at line 71 of file cact-assistant-export.h.
CACT_IS_ASSISTANT_EXPORT_CLASS
#define CACT_IS_ASSISTANT_EXPORT_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), CACT_TYPE_ASSISTANT_EXPORT))
Definition at line 72 of file cact-assistant-export.h.
CACT_TYPE_ASSISTANT_EXPORT
#define CACT_TYPE_ASSISTANT_EXPORT (cact_assistant_export_get_type())
SECTION: cact_assistant_export @short_description: CactAssistantExport class definition. cact/cact-assistant-export.h
Rationale:
Up to v 1.10.x, actions are exported as config_uuid.schemas. These are actually full MateConf schema exports of the form : <schemalist> <schema> <key>/schemas/apps/caja-actions/..../uuid/label</key> <applyto>/apps/..../label</applyto>
I don't know why Frederic had chosen to export as schema. But this implies that :
if all actions are imported via mateconftool-2 –install-schema-file, then the schema will be repeated once for each imported action (as schema is attached here to the uuid), which is obviously a waste of resources
it seems that MateConfClient refuses to delete only the 'applyto' key when there is a corresponding schema key ..? (to be confirmed)
Considering exporting schemas, we have two goals with this :
make the files lighter
keep the compatibility with previous mode
which means exporting the minimal schema file which can be imported with v1.10 and previous series., and via mateconftool-2 –install-schema-file.
Definition at line 68 of file cact-assistant-export.h.
Typedef Documentation
CactAssistantExportClassPrivate
typedef struct _CactAssistantExportClassPrivate CactAssistantExportClassPrivate
Definition at line 84 of file cact-assistant-export.h.
CactAssistantExportPrivate
typedef struct _CactAssistantExportPrivate CactAssistantExportPrivate
Definition at line 75 of file cact-assistant-export.h.
Function Documentation
cact_assistant_export_get_type()
GType cact_assistant_export_get_type (void)
Definition at line 128 of file cact-assistant-export.c.
cact_assistant_export_run()
void cact_assistant_export_run (BaseWindow * main_window)
Run the assistant.
@main: the main window of the application.
Definition at line 360 of file cact-assistant-export.c.
References BASE_PROP_HAS_OWN_BUILDER, BASE_PROP_PARENT, BASE_PROP_QUIT_ON_ESCAPE, BASE_PROP_TOPLEVEL_NAME, BASE_PROP_WARN_ON_ESCAPE, BASE_PROP_WSP_NAME, BASE_PROP_XMLUI_FILENAME, BASE_WINDOW, base_window_run(), CACT_IS_MAIN_WINDOW, CACT_TYPE_ASSISTANT_EXPORT, NA_IPREFS_ASSISTANT_ESC_CONFIRM, NA_IPREFS_ASSISTANT_ESC_QUIT, na_settings_get_boolean(), NULL, and TRUE.
Referenced by cact_menubar_tools_on_export().