MATE Desktop Environment: cact-assistant-import.h File Reference
cact-assistant-import.h File Reference
#include "base-assistant.h"
Classes
struct CactAssistantImport
struct CactAssistantImportClass
Macros
#define CACT_TYPE_ASSISTANT_IMPORT (cact_assistant_import_get_type())
#define CACT_ASSISTANT_IMPORT(object) (G_TYPE_CHECK_INSTANCE_CAST(object, CACT_TYPE_ASSISTANT_IMPORT, CactAssistantImport))
#define CACT_ASSISTANT_IMPORT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, CACT_TYPE_ASSISTANT_IMPORT, CactAssistantImportClass))
#define CACT_IS_ASSISTANT_IMPORT(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, CACT_TYPE_ASSISTANT_IMPORT))
#define CACT_IS_ASSISTANT_IMPORT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), CACT_TYPE_ASSISTANT_IMPORT))
#define CACT_ASSISTANT_IMPORT_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), CACT_TYPE_ASSISTANT_IMPORT, CactAssistantImportClass))
Typedefs
typedef struct _CactAssistantImportPrivate CactAssistantImportPrivate
typedef struct _CactAssistantImportClassPrivate CactAssistantImportClassPrivate
Functions
GType cact_assistant_import_get_type (void)
void cact_assistant_import_run (BaseWindow *main)
Macro Definition Documentation
CACT_ASSISTANT_IMPORT
#define CACT_ASSISTANT_IMPORT (object) (G_TYPE_CHECK_INSTANCE_CAST(object, CACT_TYPE_ASSISTANT_IMPORT, CactAssistantImport))
Definition at line 44 of file cact-assistant-import.h.
CACT_ASSISTANT_IMPORT_CLASS
#define CACT_ASSISTANT_IMPORT_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, CACT_TYPE_ASSISTANT_IMPORT, CactAssistantImportClass))
Definition at line 45 of file cact-assistant-import.h.
CACT_ASSISTANT_IMPORT_GET_CLASS
#define CACT_ASSISTANT_IMPORT_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), CACT_TYPE_ASSISTANT_IMPORT, CactAssistantImportClass))
Definition at line 48 of file cact-assistant-import.h.
CACT_IS_ASSISTANT_IMPORT
#define CACT_IS_ASSISTANT_IMPORT (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, CACT_TYPE_ASSISTANT_IMPORT))
Definition at line 46 of file cact-assistant-import.h.
CACT_IS_ASSISTANT_IMPORT_CLASS
#define CACT_IS_ASSISTANT_IMPORT_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), CACT_TYPE_ASSISTANT_IMPORT))
Definition at line 47 of file cact-assistant-import.h.
CACT_TYPE_ASSISTANT_IMPORT
#define CACT_TYPE_ASSISTANT_IMPORT (cact_assistant_import_get_type())
SECTION: cact_assistant_import @short_description: CactAssistantImport class definition. cact/cact-assistant-import.h
Definition at line 43 of file cact-assistant-import.h.
Typedef Documentation
CactAssistantImportClassPrivate
typedef struct _CactAssistantImportClassPrivate CactAssistantImportClassPrivate
Definition at line 59 of file cact-assistant-import.h.
CactAssistantImportPrivate
typedef struct _CactAssistantImportPrivate CactAssistantImportPrivate
Definition at line 50 of file cact-assistant-import.h.
Function Documentation
cact_assistant_import_get_type()
GType cact_assistant_import_get_type (void)
Definition at line 135 of file cact-assistant-import.c.
cact_assistant_import_run()
void cact_assistant_import_run (BaseWindow * main_window)
cact_assistant_import_run: @main: the CactMainWindow parent window of this assistant.
Run the assistant.
Definition at line 320 of file cact-assistant-import.c.
References BASE_PROP_HAS_OWN_BUILDER, BASE_PROP_PARENT, BASE_PROP_QUIT_ON_ESCAPE, BASE_PROP_TOPLEVEL_NAME, BASE_PROP_WARN_ON_ESCAPE, BASE_PROP_WSP_NAME, BASE_PROP_XMLUI_FILENAME, BASE_WINDOW, base_window_run(), CACT_IS_MAIN_WINDOW, CACT_TYPE_ASSISTANT_IMPORT, NA_IPREFS_ASSISTANT_ESC_CONFIRM, NA_IPREFS_ASSISTANT_ESC_QUIT, na_settings_get_boolean(), NULL, and TRUE.
Referenced by cact_menubar_tools_on_import().