MATE Desktop Environment: cact-tree-ieditable.h File Reference
cact-tree-ieditable.h File Reference
#include <api/na-object.h>
#include "base-window.h"
Classes
struct CactTreeIEditableInterface
Macros
#define CACT_TREE_IEDITABLE_TYPE (cact_tree_ieditable_get_type())
#define CACT_TREE_IEDITABLE(object) (G_TYPE_CHECK_INSTANCE_CAST(object, CACT_TREE_IEDITABLE_TYPE, CactTreeIEditable))
#define CACT_IS_TREE_IEDITABLE(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, CACT_TREE_IEDITABLE_TYPE))
#define CACT_TREE_IEDITABLE_GET_INTERFACE(instance) (G_TYPE_INSTANCE_GET_INTERFACE((instance), CACT_TREE_IEDITABLE_TYPE, CactTreeIEditableInterface))
Typedefs
typedef struct _CactTreeIEditable CactTreeIEditable
typedef struct _CactTreeIEditableInterfacePrivate CactTreeIEditableInterfacePrivate
Enumerations
enum TreeIEditableDeleteOpe { TREE_OPE_DELETE = 0 , TREE_OPE_MOVE }
Functions
GType cact_tree_ieditable_get_type (void)
void cact_tree_ieditable_initialize (CactTreeIEditable *instance, GtkTreeView *treeview, BaseWindow *window)
void cact_tree_ieditable_terminate (CactTreeIEditable *instance)
void cact_tree_ieditable_delete (CactTreeIEditable *instance, GList *items, TreeIEditableDeleteOpe ope)
gboolean cact_tree_ieditable_remove_deleted (CactTreeIEditable *instance, GSList **messages)
GList * cact_tree_ieditable_get_deleted (CactTreeIEditable *instance)
void cact_tree_ieditable_insert_items (CactTreeIEditable *instance, GList *items, NAObject *sibling)
void cact_tree_ieditable_insert_at_path (CactTreeIEditable *instance, GList *items, GtkTreePath *path)
void cact_tree_ieditable_insert_into (CactTreeIEditable *instance, GList *items)
void cact_tree_ieditable_set_items (CactTreeIEditable *instance, GList *items)
void cact_tree_ieditable_dump_modified (const CactTreeIEditable *instance)
gboolean cact_tree_ieditable_is_level_zero_modified (const CactTreeIEditable *instance)
Macro Definition Documentation
CACT_IS_TREE_IEDITABLE
#define CACT_IS_TREE_IEDITABLE (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, CACT_TREE_IEDITABLE_TYPE))
Definition at line 57 of file cact-tree-ieditable.h.
CACT_TREE_IEDITABLE
#define CACT_TREE_IEDITABLE (object) (G_TYPE_CHECK_INSTANCE_CAST(object, CACT_TREE_IEDITABLE_TYPE, CactTreeIEditable))
Definition at line 56 of file cact-tree-ieditable.h.
CACT_TREE_IEDITABLE_GET_INTERFACE
#define CACT_TREE_IEDITABLE_GET_INTERFACE (instance) (G_TYPE_INSTANCE_GET_INTERFACE((instance), CACT_TREE_IEDITABLE_TYPE, CactTreeIEditableInterface))
Definition at line 58 of file cact-tree-ieditable.h.
CACT_TREE_IEDITABLE_TYPE
#define CACT_TREE_IEDITABLE_TYPE (cact_tree_ieditable_get_type())
SECTION: cact-tree_ieditable @title: CactTreeIEditable @short_description: The CactTreeIEditable interface definition cact-tree_ieditable.h
This interface is to be implemented by a CactTreeView which would want get edition features, such as inline edition, insert, delete, and so on.
CactTreeIEditable maintains the count of modified items. Starting with zero when the tree view is filled up, it is incremented each time an item is modified, inserted or deleted. The modified count is fully recomputed after a save.
Definition at line 55 of file cact-tree-ieditable.h.
Typedef Documentation
CactTreeIEditable
typedef struct _CactTreeIEditable CactTreeIEditable
Definition at line 60 of file cact-tree-ieditable.h.
CactTreeIEditableInterfacePrivate
typedef struct _CactTreeIEditableInterfacePrivate CactTreeIEditableInterfacePrivate
Definition at line 61 of file cact-tree-ieditable.h.
Enumeration Type Documentation
TreeIEditableDeleteOpe
enum TreeIEditableDeleteOpe
Delete operations
Enumerator
TREE_OPE_DELETE
TREE_OPE_MOVE
Definition at line 73 of file cact-tree-ieditable.h.
Function Documentation
cact_tree_ieditable_delete()
void cact_tree_ieditable_delete (CactTreeIEditable * instance, GList * items, TreeIEditableDeleteOpe ope)
cact_tree_ieditable_delete: @instance: this CactTreeIEditable instance. @list: list of NAObject to be deleted. @ope: whether the objects are actually to be deleted, or just moved to another path of the tree.
Deletes the specified list from the underlying tree store.
If the items are to be actually deleted, then this function takes care of repositionning a new selection if possible, and refilter the display model. Deleted NAObjectItems are added to the 'deleted' list attached to the view, so that they will be actually deleted from the storage subsystem on save. Deleted NAObjectProfiles are not added to the list, because the deletion will be recorded when saving the action.
If the items are to be actually moved to another path of the tree, then neither the 'deleted' list nor the 'count_modified' counter are modified.
Definition at line 451 of file cact-tree-ieditable.c.
References CACT_IS_TREE_IEDITABLE, cact_tree_model_delete(), CACT_TREE_VIEW, cact_tree_view_select_row_at_path(), cact_tree_view_set_notify_allowed(), FALSE, NA_OBJECT, na_object_check_status, na_object_get_parent, NULL, TREE_OPE_DELETE, TREE_SIGNAL_MODIFIED_STATUS_CHANGED, and TRUE.
Referenced by cact_menubar_edit_on_cut(), and cact_menubar_edit_on_delete().
cact_tree_ieditable_dump_modified()
void cact_tree_ieditable_dump_modified (const CactTreeIEditable * instance)
cact_tree_ieditable_dump_modified: @instance: this CactTreeIEditable *instance.
Dump information about modified items.
Definition at line 1021 of file cact-tree-ieditable.c.
References CACT_IS_TREE_IEDITABLE.
Referenced by cact_menubar_maintainer_on_list_modified_items().
cact_tree_ieditable_get_deleted()
GList * cact_tree_ieditable_get_deleted (CactTreeIEditable * instance)
cact_tree_ieditable_get_deleted: @instance: this CactTreeIEditable *instance.
Returns: a copy of the 'deleted' list, which should be na_object_free_items() by the caller.
Definition at line 640 of file cact-tree-ieditable.c.
References CACT_IS_TREE_IEDITABLE, na_object_copyref_items, and NULL.
Referenced by cact_tree_view_get_items_ex().
cact_tree_ieditable_get_type()
GType cact_tree_ieditable_get_type (void)
Definition at line 97 of file cact-tree-ieditable.c.
cact_tree_ieditable_initialize()
void cact_tree_ieditable_initialize (CactTreeIEditable * instance, GtkTreeView * treeview, BaseWindow * window)
cact_tree_ieditable_initialize: @instance: the CactTreeView which implements this interface. @treeview: the embedded #GtkTreeView tree view. @window: the BaseWindow which embeds the @instance.
Initialize the interface, mainly connecting to signals of interest.
Definition at line 174 of file cact-tree-ieditable.c.
References base_window_get_application(), base_window_signal_connect(), CACT_APPLICATION, cact_application_get_updater(), CACT_IS_TREE_IEDITABLE, CACT_TREE_MODEL, IDUPLICABLE_SIGNAL_MODIFIED_CHANGED, IDUPLICABLE_SIGNAL_VALID_CHANGED, MAIN_SIGNAL_SELECTION_CHANGED, na_iduplicable_register_consumer(), TREE_COLUMN_LABEL, TREE_SIGNAL_LEVEL_ZERO_CHANGED, and TREE_SIGNAL_MODIFIED_STATUS_CHANGED.
cact_tree_ieditable_insert_at_path()
void cact_tree_ieditable_insert_at_path (CactTreeIEditable * instance, GList * items, GtkTreePath * insert_path)
cact_tree_ieditable_insert_at_path: @instance: this CactTreeIEditable instance. @items: a list of items to be inserted (e.g. from a paste). @path: insertion path.
Inserts the provided @items list in the treeview.
This function takes care of repositionning a new selection if possible, and refilter the display model.
Definition at line 734 of file cact-tree-ieditable.c.
References CACT_IS_TREE_IEDITABLE, CACT_TREE_VIEW, cact_tree_view_select_row_at_path(), cact_tree_view_set_notify_allowed(), FALSE, na_object_check_status, na_object_get_parent, TREE_SIGNAL_LEVEL_ZERO_CHANGED, TREE_SIGNAL_MODIFIED_STATUS_CHANGED, and TRUE.
Referenced by cact_tree_ieditable_insert_items().
cact_tree_ieditable_insert_into()
void cact_tree_ieditable_insert_into (CactTreeIEditable * instance, GList * items)
cact_tree_ieditable_insert_into: @instance: this CactTreeIEditable instance. @items: a list of items to be inserted (e.g. from a paste).
Inserts the provided @items list as first children of the current item.
The provided @items list is supposed to be homogeneous, i.e. referes to only profiles, or only actions or menus.
If the @items list contains only profiles, they can only be inserted into an action, and the profiles will eventually be renumbered.
If new item is a NAObjectMenu or a NAObjectAction, it will be inserted as first children of the current menu.
This function takes care of repositionning a new selection as the last inserted item, and refilter the display model.
Definition at line 798 of file cact-tree-ieditable.c.
References CACT_IS_TREE_IEDITABLE, CACT_TREE_VIEW, cact_tree_view_select_row_at_path(), na_object_check_status, and na_object_get_parent.
Referenced by cact_menubar_edit_on_paste_into(), and cact_tree_ieditable_insert_items().
cact_tree_ieditable_insert_items()
void cact_tree_ieditable_insert_items (CactTreeIEditable * instance, GList * items, NAObject * sibling)
cact_tree_ieditable_insert_items: @instance: this CactTreeIEditable instance. @items: a list of items to be inserted (e.g. from a paste). @sibling: the NAObject besides which the insertion should occurs; this is mainly used for inserting duplicated items besides each of original ones; may be NULL.
Inserts the provided @items list just before the @sibling object, or at the current position in the treeview if @sibling is NULL.
The provided @items list is supposed to be homogeneous, i.e. referes to only profiles, or only actions or menus.
If the @items list contains profiles, they can only be inserted into an action, or before another profile.
If new item is a NAObjectMenu or a NAObjectAction, it will be inserted before the current action or menu.
This function takes care of repositionning a new selection (if possible) on the lastly inserted item, and to refresh the display.
Definition at line 677 of file cact-tree-ieditable.c.
References CACT_IS_TREE_IEDITABLE, cact_tree_ieditable_insert_at_path(), cact_tree_ieditable_insert_into(), cact_tree_model_object_at_path(), cact_tree_model_object_to_path(), NA_IS_OBJECT_ACTION, NA_IS_OBJECT_ITEM, NA_IS_OBJECT_PROFILE, na_object_get_parent, and NULL.
Referenced by cact_menubar_edit_on_duplicate(), cact_menubar_edit_on_paste(), cact_menubar_file_on_new_action(), cact_menubar_file_on_new_menu(), cact_menubar_file_on_new_profile(), and cact_tree_ieditable_remove_deleted().
cact_tree_ieditable_is_level_zero_modified()
gboolean cact_tree_ieditable_is_level_zero_modified (const CactTreeIEditable * instance)
cact_tree_ieditable_is_level_zero_modified: @instance: this CactTreeIEditable *instance.
Returns: TRUE if the level zero must be saved, FALSE else.
Definition at line 1042 of file cact-tree-ieditable.c.
References CACT_IS_TREE_IEDITABLE, and FALSE.
Referenced by cact_menubar_file_save_items().
cact_tree_ieditable_remove_deleted()
gboolean cact_tree_ieditable_remove_deleted (CactTreeIEditable * instance, GSList ** messages)
cact_tree_ieditable_remove_deleted: @instance: this CactTreeIEditable *instance. @messages: a pointer to a #GSList of error messages.
Actually removes the deleted items from the underlying I/O storage subsystem.
@messages #GSList is only filled up in case of an error has occured. If there is no error (cact_tree_ieditable_remove_deleted() returns TRUE), then the caller may safely assume that @messages is returned in the same state that it has been provided.
Returns: TRUE if all candidate items have been successfully deleted, FALSE else.
Definition at line 592 of file cact-tree-ieditable.c.
References CACT_IS_TREE_IEDITABLE, cact_tree_ieditable_insert_items(), FALSE, item, NA_IIO_PROVIDER_CODE_OK, na_object_dump_norec, na_object_free_items, NA_OBJECT_ITEM, na_object_ref, na_updater_delete_item(), NULL, and TRUE.
Referenced by cact_menubar_file_save_items().
cact_tree_ieditable_set_items()
void cact_tree_ieditable_set_items (CactTreeIEditable * instance, GList * items)
Definition at line 956 of file cact-tree-ieditable.c.
References CACT_IS_TREE_IEDITABLE, cact_tree_model_delete(), cact_tree_model_insert_before(), CACT_TREE_VIEW, cact_tree_view_get_item_by_id(), id, na_factory_object_copy(), NA_IFACTORY_OBJECT, NA_IS_OBJECT_ACTION, NA_IS_OBJECT_MENU, NA_OBJECT, na_object_get_id, and NA_OBJECT_ITEM.
cact_tree_ieditable_terminate()
void cact_tree_ieditable_terminate (CactTreeIEditable * instance)
cact_tree_ieditable_terminate: @instance: the CactTreeView which implements this interface.
Free the data when application quits.
Definition at line 255 of file cact-tree-ieditable.c.
References base_window_signal_disconnect(), CACT_IS_TREE_IEDITABLE, na_object_free_items, NULL, and VIEW_DATA_IEDITABLE.