MATE Desktop Environment: cact-menubar.h File Reference
cact-menubar.h File Reference
#include "base-window.h"
Classes
struct CactMenubar
struct CactMenubarClass
Macros
#define CACT_TYPE_MENUBAR (cact_menubar_get_type())
#define CACT_MENUBAR(object) (G_TYPE_CHECK_INSTANCE_CAST(object, CACT_TYPE_MENUBAR, CactMenubar))
#define CACT_MENUBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, CACT_TYPE_MENUBAR, CactMenubarClass))
#define CACT_IS_MENUBAR(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, CACT_TYPE_MENUBAR))
#define CACT_IS_MENUBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), CACT_TYPE_MENUBAR))
#define CACT_MENUBAR_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), CACT_TYPE_MENUBAR, CactMenubarClass))
Typedefs
typedef struct _CactMenubarPrivate CactMenubarPrivate
typedef struct _CactMenubarClassPrivate CactMenubarClassPrivate
Functions
GType cact_menubar_get_type (void)
CactMenubar * cact_menubar_new (BaseWindow *window)
void cact_menubar_save_items (BaseWindow *window)
Macro Definition Documentation
CACT_IS_MENUBAR
#define CACT_IS_MENUBAR (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, CACT_TYPE_MENUBAR))
Definition at line 68 of file cact-menubar.h.
CACT_IS_MENUBAR_CLASS
#define CACT_IS_MENUBAR_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), CACT_TYPE_MENUBAR))
Definition at line 69 of file cact-menubar.h.
CACT_MENUBAR
#define CACT_MENUBAR (object) (G_TYPE_CHECK_INSTANCE_CAST(object, CACT_TYPE_MENUBAR, CactMenubar))
Definition at line 66 of file cact-menubar.h.
CACT_MENUBAR_CLASS
#define CACT_MENUBAR_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, CACT_TYPE_MENUBAR, CactMenubarClass))
Definition at line 67 of file cact-menubar.h.
CACT_MENUBAR_GET_CLASS
#define CACT_MENUBAR_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), CACT_TYPE_MENUBAR, CactMenubarClass))
Definition at line 70 of file cact-menubar.h.
CACT_TYPE_MENUBAR
#define CACT_TYPE_MENUBAR (cact_menubar_get_type())
Definition at line 65 of file cact-menubar.h.
Typedef Documentation
CactMenubarClassPrivate
typedef struct _CactMenubarClassPrivate CactMenubarClassPrivate
Definition at line 81 of file cact-menubar.h.
CactMenubarPrivate
typedef struct _CactMenubarPrivate CactMenubarPrivate
Definition at line 72 of file cact-menubar.h.
Function Documentation
cact_menubar_get_type()
GType cact_menubar_get_type (void)
Definition at line 246 of file cact-menubar.c.
References type.
cact_menubar_new()
CactMenubar * cact_menubar_new (BaseWindow * window)
cact_menubar_new: @window: the window which embeds the menubar, usually the CactMainWindow.
The created menubar attachs itself to the @window; it also connect a weak reference to this same @window, thus automatically g_object_unref() -ing itself at @window finalization time.
The menubar also takes advantage of BaseWindow messages to initialize its Gtk widgets.
Returns: a new CactMenubar object.
Definition at line 411 of file cact-menubar.c.
References BASE_IS_WINDOW, BASE_SIGNAL_INITIALIZE_WINDOW, base_window_signal_connect(), cact_sort_buttons_new(), CACT_TYPE_MENUBAR, NULL, CactMenubar::private, _CactMenubarPrivate::sort_buttons, _CactMenubarPrivate::window, and WINDOW_DATA_MENUBAR.
cact_menubar_save_items()
void cact_menubar_save_items (BaseWindow * window)
cact_menubar_save_items: @window: the BaseWindow
Definition at line 939 of file cact-menubar.c.
References cact_menubar_file_save_items().