MATE Desktop Environment: cact-menubar-tools.c File Reference
cact-menubar-tools.c File Reference
#include "cact-assistant-export.h"
#include "cact-assistant-import.h"
#include "cact-menubar-priv.h"
Functions
void cact_menubar_tools_on_update_sensitivities (const CactMenubar *bar)
void cact_menubar_tools_on_import (GtkAction *action, BaseWindow *window)
void cact_menubar_tools_on_export (GtkAction *action, BaseWindow *window)
Function Documentation
cact_menubar_tools_on_export()
void cact_menubar_tools_on_export (GtkAction * action, BaseWindow * window)
cact_menubar_tools_on_export: @action: the #GtkAction of the item. @window: the BaseWindow main application window.
Triggers the "Tools/Export assistant" item.
Definition at line 75 of file cact-menubar-tools.c.
References BASE_WINDOW, and cact_assistant_export_run().
cact_menubar_tools_on_import()
void cact_menubar_tools_on_import (GtkAction * action, BaseWindow * window)
cact_menubar_tools_on_import: @action: the #GtkAction of the item. @window: the BaseWindow main application window.
Triggers the "Tools/Import assitant" item.
Definition at line 62 of file cact-menubar-tools.c.
References BASE_WINDOW, and cact_assistant_import_run().
cact_menubar_tools_on_update_sensitivities()
void cact_menubar_tools_on_update_sensitivities (const CactMenubar * bar)
cact_menubar_tools_on_update_sensitivities: @bar: this CactMenubar object.
Update sensitivities on the Tools menu.
Definition at line 45 of file cact-menubar-tools.c.
References cact_menubar_enable_item(), _CactMenubarPrivate::has_writable_providers, _CactMenubarPrivate::have_exportables, and CactMenubar::private.