MATE Desktop Environment: cact-menubar-file.c File Reference
cact-menubar-file.c File Reference
#include <glib.h>
#include <glib/gi18n.h>
#include <api/na-core-utils.h>
#include <api/na-timeout.h>
#include <core/na-io-provider.h>
#include <core/na-iprefs.h>
#include "cact-application.h"
#include "cact-main-statusbar.h"
#include "cact-main-tab.h"
#include "cact-menubar-priv.h"
#include "cact-tree-ieditable.h"
Functions
void cact_menubar_file_initialize (CactMenubar *bar)
void cact_menubar_file_on_update_sensitivities (const CactMenubar *bar)
void cact_menubar_file_on_new_menu (GtkAction *gtk_action, BaseWindow *window)
void cact_menubar_file_on_new_action (GtkAction *gtk_action, BaseWindow *window)
void cact_menubar_file_on_new_profile (GtkAction *gtk_action, BaseWindow *window)
void cact_menubar_file_on_save (GtkAction *gtk_action, BaseWindow *window)
void cact_menubar_file_save_items (BaseWindow *window)
void cact_menubar_file_on_quit (GtkAction *gtk_action, BaseWindow *window)
Function Documentation
cact_menubar_file_initialize()
void cact_menubar_file_initialize (CactMenubar * bar)
Definition at line 69 of file cact-menubar-file.c.
cact_menubar_file_on_new_action()
void cact_menubar_file_on_new_action (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_file_on_new_action: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers File / New action item.
Definition at line 153 of file cact-menubar-file.c.
References action, base_window_get_application(), CACT_APPLICATION, cact_application_get_updater(), CACT_IS_MAIN_WINDOW, CACT_MAIN_WINDOW, cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_insert_items(), na_object_action_new_with_defaults(), na_object_check_status, na_object_free_items, NA_OBJECT_ITEM, na_updater_check_item_writability_status(), and NULL.
cact_menubar_file_on_new_menu()
void cact_menubar_file_on_new_menu (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_file_on_new_menu: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers File / New menu item.
Definition at line 123 of file cact-menubar-file.c.
References base_window_get_application(), CACT_APPLICATION, cact_application_get_updater(), CACT_IS_MAIN_WINDOW, CACT_MAIN_WINDOW, cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_insert_items(), na_object_check_status, na_object_free_items, NA_OBJECT_ITEM, na_object_menu_new_with_defaults(), na_updater_check_item_writability_status(), and NULL.
cact_menubar_file_on_new_profile()
void cact_menubar_file_on_new_profile (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_file_on_new_profile: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers File / New profile item.
Definition at line 183 of file cact-menubar-file.c.
References _, action, CACT_IS_MAIN_WINDOW, CACT_MAIN_WINDOW, cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_insert_items(), MAIN_PROP_ITEM, na_object_attach_profile, na_object_check_status, na_object_free_items, na_object_profile_new_with_defaults(), na_object_set_label, na_object_set_new_id, and NULL.
cact_menubar_file_on_quit()
void cact_menubar_file_on_quit (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_file_on_quit: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers the File / Quit item.
Definition at line 419 of file cact-menubar-file.c.
References CACT_MAIN_WINDOW, cact_main_window_quit(), and NULL.
cact_menubar_file_on_save()
void cact_menubar_file_on_save (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_file_on_save: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers File /Save item.
Saving is not only saving modified items, but also saving hierarchy (and order if alpha order is not set).
This is the same function that cact_menubar_file_save_items(), just with different arguments.
Definition at line 226 of file cact-menubar-file.c.
References CACT_IS_MAIN_WINDOW, and cact_menubar_file_save_items().
cact_menubar_file_on_update_sensitivities()
void cact_menubar_file_on_update_sensitivities (const CactMenubar * bar)
cact_menubar_file_on_update_sensitivities: @bar: this CactMenubar object.
Update sensitivity of items of the File menu.
Definition at line 81 of file cact-menubar-file.c.
References cact_menubar_enable_item(), _CactMenubarPrivate::enable_new_profile, _CactMenubarPrivate::has_writable_providers, _CactMenubarPrivate::is_action_writable, _CactMenubarPrivate::is_parent_writable, _CactMenubarPrivate::is_tree_modified, and CactMenubar::private.
cact_menubar_file_save_items()
void cact_menubar_file_save_items (BaseWindow * window)
cact_menubar_file_save_items: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Save items. This is the same function that cact_menubar_file_on_save(), just with different arguments.
Synopsis:
rewrite the level-zero items list
delete the items which are marked to be deleted
rewrite (i.e. delete/write) updated items
The difficulty here is that some sort of pseudo-transactionnal process must be setup:
if the level-zero items list cannot be updated, then an error message is displayed, and we abort the whole processus
if some items cannot be actually deleted, then an error message is displayed, and the whole processus is aborted; plus: a/ items which have not been deleted must be restored (maybe marked as deleted ?) -> so these items are modified b/ the level-zero list must be updated with these restored items and reset modified
idem if some items cannot be actually rewritten...
Definition at line 268 of file cact-menubar-file.c.
References BAR_WINDOW_VOID, base_window_display_error_dlg(), CACT_MAIN_WINDOW, cact_main_window_block_reload(), cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_is_level_zero_modified(), cact_tree_ieditable_remove_deleted(), cact_tree_view_get_items(), DUPLICATE_REC, FALSE, na_core_utils_slist_free(), na_core_utils_slist_join_at_end(), na_iprefs_write_level_zero(), na_object_check_status, na_object_dump_tree, na_object_duplicate, na_object_free_items, NA_OBJECT_ITEM, na_object_reset_origin, NA_PIVOT, na_pivot_set_new_items(), NULL, BaseWindow::private, TREE_SIGNAL_LEVEL_ZERO_CHANGED, and TREE_SIGNAL_MODIFIED_STATUS_CHANGED.
Referenced by cact_menubar_file_on_save(), and cact_menubar_save_items().