MATE Desktop Environment: cact-preferences-editor.c File Reference
cact-preferences-editor.c File Reference
#include <glib.h>
#include <glib/gi18n.h>
#include <api/na-iimporter.h>
#include <core/na-desktop-environment.h>
#include <core/na-exporter.h>
#include <core/na-export-format.h>
#include <core/na-gtk-utils.h>
#include <core/na-import-mode.h>
#include <core/na-importer.h>
#include <core/na-ioptions-list.h>
#include <core/na-iprefs.h>
#include <core/na-tokens.h>
#include "cact-application.h"
#include "base-gtk-utils.h"
#include "cact-schemes-list.h"
#include "cact-providers-list.h"
#include "cact-preferences-editor.h"
Enumerations
enum { DESKTOP_ID_COLUMN = 0 , DESKTOP_LABEL_COLUMN = 0 , DESKTOP_N_COLUMN }
Functions
GType cact_preferences_editor_get_type (void)
void cact_preferences_editor_run (BaseWindow *parent)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DESKTOP_ID_COLUMN
DESKTOP_LABEL_COLUMN
DESKTOP_N_COLUMN
Definition at line 110 of file cact-preferences-editor.c.
Function Documentation
cact_preferences_editor_get_type()
GType cact_preferences_editor_get_type (void)
Definition at line 174 of file cact-preferences-editor.c.
cact_preferences_editor_run()
void cact_preferences_editor_run (BaseWindow * parent)
cact_preferences_editor_run: @parent: the BaseWindow parent of this dialog (usually the CactMainWindow).
Initializes and runs the dialog.
Definition at line 440 of file cact-preferences-editor.c.
References BASE_IS_WINDOW, BASE_PROP_PARENT, BASE_PROP_TOPLEVEL_NAME, BASE_PROP_WSP_NAME, BASE_PROP_XMLUI_FILENAME, BASE_WINDOW, base_window_get_widget(), base_window_run(), CACT_TYPE_PREFERENCES_EDITOR, NA_IPREFS_ADMIN_PREFERENCES_LOCKED, na_settings_get_boolean(), NULL, and CactPreferencesEditor::private.
Referenced by cact_menubar_edit_on_prefererences().