MATE Desktop Environment: cact-application.h File Reference
cact-application.h File Reference
#include <core/na-updater.h>
#include "base-application.h"
Classes
struct CactApplication
struct CactApplicationClass
Macros
#define CACT_TYPE_APPLICATION (cact_application_get_type())
#define CACT_APPLICATION(object) (G_TYPE_CHECK_INSTANCE_CAST(object, CACT_TYPE_APPLICATION, CactApplication))
#define CACT_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, CACT_TYPE_APPLICATION, CactApplicationClass))
#define CACT_IS_APPLICATION(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, CACT_TYPE_APPLICATION))
#define CACT_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), CACT_TYPE_APPLICATION))
#define CACT_APPLICATION_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), CACT_TYPE_APPLICATION, CactApplicationClass))
Typedefs
typedef struct _CactApplicationPrivate CactApplicationPrivate
typedef struct _CactApplicationClassPrivate CactApplicationClassPrivate
Functions
GType cact_application_get_type (void)
CactApplication * cact_application_new (void)
NAUpdater * cact_application_get_updater (const CactApplication *application)
Macro Definition Documentation
CACT_APPLICATION
#define CACT_APPLICATION (object) (G_TYPE_CHECK_INSTANCE_CAST(object, CACT_TYPE_APPLICATION, CactApplication))
Definition at line 56 of file cact-application.h.
CACT_APPLICATION_CLASS
#define CACT_APPLICATION_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, CACT_TYPE_APPLICATION, CactApplicationClass))
Definition at line 57 of file cact-application.h.
CACT_APPLICATION_GET_CLASS
#define CACT_APPLICATION_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), CACT_TYPE_APPLICATION, CactApplicationClass))
Definition at line 60 of file cact-application.h.
CACT_IS_APPLICATION
#define CACT_IS_APPLICATION (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, CACT_TYPE_APPLICATION))
Definition at line 58 of file cact-application.h.
CACT_IS_APPLICATION_CLASS
#define CACT_IS_APPLICATION_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), CACT_TYPE_APPLICATION))
Definition at line 59 of file cact-application.h.
CACT_TYPE_APPLICATION
#define CACT_TYPE_APPLICATION (cact_application_get_type())
SECTION: cact_application @short_description: CactApplication class definition. cact/cact-application.h
This is the main class for caja-actions-config-tool program.
The CactApplication object is instanciated in main() function.
Properties are explicitely set in cact_application_new() before calling base_application_run().
The CactApplication object is later g_object_unref() in main() after base_application_run() has returned.
Definition at line 55 of file cact-application.h.
Typedef Documentation
CactApplicationClassPrivate
typedef struct _CactApplicationClassPrivate CactApplicationClassPrivate
Definition at line 71 of file cact-application.h.
CactApplicationPrivate
typedef struct _CactApplicationPrivate CactApplicationPrivate
Definition at line 62 of file cact-application.h.
Function Documentation
cact_application_get_type()
GType cact_application_get_type (void)
Definition at line 83 of file cact-application.c.
cact_application_get_updater()
NAUpdater * cact_application_get_updater (const CactApplication * application)
cact_application_get_updater: @application: this CactApplication object.
Returns a pointer on the NAUpdater object.
The returned pointer is owned by the CactApplication object. It should not be g_free() not g_object_unref() by the caller.
Definition at line 339 of file cact-application.c.
References CACT_IS_APPLICATION, NULL, and CactApplication::private.
Referenced by cact_menubar_file_on_new_action(), cact_menubar_file_on_new_menu(), cact_providers_list_init_view(), cact_schemes_list_init_view(), cact_sort_buttons_new(), and cact_tree_ieditable_initialize().
cact_application_new()
CactApplication * cact_application_new (void)
cact_application_new:
Returns: a newly allocated CactApplication object.
Definition at line 213 of file cact-application.c.
References BASE_PROP_APPLICATION_NAME, BASE_PROP_DESCRIPTION, BASE_PROP_ICON_NAME, BASE_PROP_OPTIONS, BASE_PROP_UNIQUE_NAME, CACT_TYPE_APPLICATION, NULL, and PACKAGE.
Referenced by main().