MATE Desktop Environment: cact-tree-view.c File Reference
cact-tree-view.c File Reference
#include <glib/gi18n.h>
#include <api/na-object-api.h>
#include <core/na-gtk-utils.h>
#include "base-keysyms.h"
#include "cact-application.h"
#include "cact-main-window.h"
#include "cact-marshal.h"
#include "cact-tree-view.h"
#include "cact-tree-model.h"
#include "cact-tree-ieditable.h"
Typedefs
typedef gboolean(* FnIterOnSelection) (CactTreeView *, GtkTreeModel *, GtkTreeIter *, NAObject *, gpointer)
Enumerations
enum {
TREE_PROP_0 , TREE_PROP_WINDOW_ID , TREE_PROP_PARENT_ID , TREE_PROP_WIDGET_NAME_ID ,
TREE_PROP_MODE_ID , TREE_PROP_NOTIFY_ALLOWED_ID , TREE_PROP_N_PROPERTIES
}
enum {
COUNT_CHANGED , FOCUS_IN , FOCUS_OUT , LEVEL_ZERO_CHANGED ,
MODIFIED_STATUS , SELECTION_CHANGED , LAST_SIGNAL
}
enum { TOGGLE_UNDEFINED , TOGGLE_COLLAPSE , TOGGLE_EXPAND }
Functions
GType cact_tree_view_get_type (void)
CactTreeView * cact_tree_view_new (BaseWindow *window, GtkContainer *parent, const gchar *treeview_name, CactTreeMode mode)
void cact_tree_view_fill (CactTreeView *view, GList *items)
gboolean cact_tree_view_are_notify_allowed (const CactTreeView *view)
void cact_tree_view_set_notify_allowed (CactTreeView *view, gboolean allow)
void cact_tree_view_collapse_all (const CactTreeView *view)
void cact_tree_view_expand_all (const CactTreeView *view)
NAObjectItem * cact_tree_view_get_item_by_id (const CactTreeView *view, const gchar *id)
GList * cact_tree_view_get_items (const CactTreeView *view)
GList * cact_tree_view_get_items_ex (const CactTreeView *view, guint mode)
void cact_tree_view_select_row_at_path (CactTreeView *view, GtkTreePath *path)
Typedef Documentation
FnIterOnSelection
typedef gboolean(* FnIterOnSelection) (CactTreeView *, GtkTreeModel *, GtkTreeIter *, NAObject *, gpointer)
Definition at line 111 of file cact-tree-view.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TREE_PROP_0
TREE_PROP_WINDOW_ID
TREE_PROP_PARENT_ID
TREE_PROP_WIDGET_NAME_ID
TREE_PROP_MODE_ID
TREE_PROP_NOTIFY_ALLOWED_ID
TREE_PROP_N_PROPERTIES
Definition at line 74 of file cact-tree-view.c.
anonymous enum
anonymous enum
Enumerator
COUNT_CHANGED
FOCUS_IN
FOCUS_OUT
LEVEL_ZERO_CHANGED
MODIFIED_STATUS
SELECTION_CHANGED
LAST_SIGNAL
Definition at line 88 of file cact-tree-view.c.
anonymous enum
anonymous enum
Enumerator
TOGGLE_UNDEFINED
TOGGLE_COLLAPSE
TOGGLE_EXPAND
Definition at line 103 of file cact-tree-view.c.
Function Documentation
cact_tree_view_are_notify_allowed()
gboolean cact_tree_view_are_notify_allowed (const CactTreeView * view)
cact_tree_view_are_notify_allowed: @view: this CactTreeView instance.
Returns: TRUE if notifications are allowed, FALSE else.
Definition at line 925 of file cact-tree-view.c.
References CACT_IS_TREE_VIEW, FALSE, and CactTreeView::private.
cact_tree_view_collapse_all()
void cact_tree_view_collapse_all (const CactTreeView * view)
cact_tree_view_collapse_all: @view: this CactTreeView instance.
Collapse all the tree hierarchy.
Definition at line 964 of file cact-tree-view.c.
References CACT_IS_TREE_VIEW, and CactTreeView::private.
Referenced by cact_menubar_view_on_collapse_all().
cact_tree_view_expand_all()
void cact_tree_view_expand_all (const CactTreeView * view)
cact_tree_view_expand_all: @view: this CactTreeView instance.
Collapse all the tree hierarchy.
Definition at line 981 of file cact-tree-view.c.
References CACT_IS_TREE_VIEW, and CactTreeView::private.
Referenced by cact_menubar_view_on_expand_all().
cact_tree_view_fill()
void cact_tree_view_fill (CactTreeView * view, GList * items)
cact_tree_view_fill: @view: this CactTreeView instance.
Fill the tree view with the provided list of items.
Notification of selection changes is temporary suspended during the fillup of the list, so that client is not cluttered with tons of selection-changed messages.
Definition at line 891 of file cact-tree-view.c.
References CACT_IS_TREE_VIEW, CACT_TREE_MODEL, cact_tree_model_fill(), FALSE, na_object_count_items, CactTreeView::private, TREE_SIGNAL_COUNT_CHANGED, TREE_SIGNAL_MODIFIED_STATUS_CHANGED, and TRUE.
cact_tree_view_get_item_by_id()
NAObjectItem * cact_tree_view_get_item_by_id (const CactTreeView * view, const gchar * id)
cact_tree_view_get_item_by_id: @view: this CactTreeView instance. @id: the searched NAObjectItem.
Returns: a pointer on the searched NAObjectItem if it exists, or NULL.
The returned pointer is owned by the underlying tree store, and should not be released by the caller.
Definition at line 1002 of file cact-tree-view.c.
References CACT_IS_TREE_VIEW, CACT_TREE_MODEL, cact_tree_model_get_item_by_id(), item, NULL, and CactTreeView::private.
Referenced by cact_tree_ieditable_set_items().
cact_tree_view_get_items()
GList * cact_tree_view_get_items (const CactTreeView * view)
cact_tree_view_get_items: @view: this CactTreeView instance.
Returns: the content of the current tree as a newly allocated list which should be na_object_free_items() by the caller.
Definition at line 1028 of file cact-tree-view.c.
References cact_tree_view_get_items_ex(), and TREE_LIST_ALL.
Referenced by cact_menubar_file_save_items(), and cact_menubar_maintainer_on_brief_tree_store_dump().
cact_tree_view_get_items_ex()
GList * cact_tree_view_get_items_ex (const CactTreeView * view, guint mode)
cact_tree_view_get_items_ex: @view: this CactTreeView instance. @mode: the list content
Returns: the content of the current tree as a newly allocated list which should be na_object_free_items() by the caller.
Definition at line 1042 of file cact-tree-view.c.
References CACT_IS_TREE_VIEW, CACT_TREE_IEDITABLE, cact_tree_ieditable_get_deleted(), CACT_TREE_MODEL, cact_tree_model_get_items(), NULL, CactTreeView::private, TREE_LIST_DELETED, and TREE_MODE_EDITION.
Referenced by cact_tree_view_get_items().
cact_tree_view_get_type()
GType cact_tree_view_get_type (void)
Definition at line 151 of file cact-tree-view.c.
References CACT_TREE_IEDITABLE_TYPE, NULL, and type.
cact_tree_view_new()
CactTreeView * cact_tree_view_new (BaseWindow * window, GtkContainer * parent, const gchar * treeview_name, CactTreeMode mode)
cact_tree_view_new: @window: the BaseWindow which embeds the tree view. @parent: the GtkContainer parent of the tree view. @treeview_name: the GtkTreeView widget name. @mode: management mode.
Returns: a newly allocated CactTreeView object, which will be owned by the caller. It is useless to unref it as it will automatically auto-destroys itself at @window finalization.
This function is called from CactMainWindow::on_base_initialize_gtk() signal handler, thus only once during the application life.
Definition at line 603 of file cact-tree-view.c.
References CACT_TYPE_TREE_VIEW, NULL, TREE_PROP_MODE, TREE_PROP_PARENT, TREE_PROP_WIDGET_NAME, and TREE_PROP_WINDOW.
cact_tree_view_select_row_at_path()
void cact_tree_view_select_row_at_path (CactTreeView * view, GtkTreePath * path)
cact_tree_view_select_row_at_path: @view: this CactTreeView object. @path: the #GtkTreePath to be selected.
Select the row at the required path, or the immediate previous, or the next following, or eventually the immediate parent.
If nothing can be selected (and notify is allowed), at least send a message with an empty selection.
Definition at line 1083 of file cact-tree-view.c.
References CACT_IS_TREE_VIEW, FALSE, MAIN_SIGNAL_SELECTION_CHANGED, NULL, CactTreeView::private, and TRUE.
Referenced by cact_tree_ieditable_delete(), cact_tree_ieditable_insert_at_path(), and cact_tree_ieditable_insert_into().
cact_tree_view_set_notify_allowed()
void cact_tree_view_set_notify_allowed (CactTreeView * view, gboolean allow)
cact_tree_view_set_notify_allowed: @view: this CactTreeView instance. @allow: whether the notifications are to be allowed.
Definition at line 947 of file cact-tree-view.c.
References CACT_IS_TREE_VIEW, and CactTreeView::private.
Referenced by cact_tree_ieditable_delete(), and cact_tree_ieditable_insert_at_path().