MATE Desktop Environment: cadp-writer.h File Reference
cadp-writer.h File Reference
#include <api/na-iio-provider.h>
#include <api/na-iexporter.h>
#include <api/na-ifactory-provider.h>
Functions
gboolean cadp_iio_provider_is_willing_to_write (const NAIIOProvider *provider)
gboolean cadp_iio_provider_is_able_to_write (const NAIIOProvider *provider)
guint cadp_iio_provider_write_item (const NAIIOProvider *provider, const NAObjectItem *item, GSList **messages)
guint cadp_iio_provider_delete_item (const NAIIOProvider *provider, const NAObjectItem *item, GSList **messages)
guint cadp_iio_provider_duplicate_data (const NAIIOProvider *provider, NAObjectItem *dest, const NAObjectItem *source, GSList **messages)
guint cadp_writer_iexporter_export_to_buffer (const NAIExporter *instance, NAIExporterBufferParmsv2 *parms)
guint cadp_writer_iexporter_export_to_file (const NAIExporter *instance, NAIExporterFileParmsv2 *parms)
guint cadp_writer_ifactory_provider_write_start (const NAIFactoryProvider *provider, void *writer_data, const NAIFactoryObject *object, GSList **messages)
guint cadp_writer_ifactory_provider_write_data (const NAIFactoryProvider *provider, void *writer_data, const NAIFactoryObject *object, const NADataBoxed *boxed, GSList **messages)
guint cadp_writer_ifactory_provider_write_done (const NAIFactoryProvider *provider, void *writer_data, const NAIFactoryObject *object, GSList **messages)
Function Documentation
cadp_iio_provider_delete_item()
guint cadp_iio_provider_delete_item (const NAIIOProvider * provider, const NAObjectItem * item, GSList ** messages)
Definition at line 250 of file cadp-writer.c.
References cadp_desktop_file_get_key_file_uri(), CADP_DESKTOP_PROVIDER, CADP_IS_DESKTOP_FILE, CADP_IS_DESKTOP_PROVIDER, cadp_utils_uri_delete(), _CappDesktopProviderPrivate::dispose_has_run, item, NA_IIO_PROVIDER_CODE_NOT_WILLING_TO_RUN, NA_IIO_PROVIDER_CODE_OK, NA_IIO_PROVIDER_CODE_PROGRAM_ERROR, NA_IS_IIO_PROVIDER, NA_IS_OBJECT_ITEM, na_object_get_provider_data, and CappDesktopProvider::private.
cadp_iio_provider_duplicate_data()
guint cadp_iio_provider_duplicate_data (const NAIIOProvider * provider, NAObjectItem * dest, const NAObjectItem * source, GSList ** messages)
Definition at line 312 of file cadp-writer.c.
References CADP_DESKTOP_PROVIDER, CADP_IS_DESKTOP_FILE, CADP_IS_DESKTOP_PROVIDER, dest, _CappDesktopProviderPrivate::dispose_has_run, NA_IIO_PROVIDER_CODE_NOT_WILLING_TO_RUN, NA_IIO_PROVIDER_CODE_OK, NA_IIO_PROVIDER_CODE_PROGRAM_ERROR, NA_IS_IIO_PROVIDER, NA_IS_OBJECT_ITEM, na_object_get_provider_data, na_object_set_provider_data, and CappDesktopProvider::private.
cadp_iio_provider_is_able_to_write()
gboolean cadp_iio_provider_is_able_to_write (const NAIIOProvider * provider)
Definition at line 95 of file cadp-writer.c.
References CADP_IS_DESKTOP_PROVIDER, cadp_xdg_dirs_get_user_data_dir(), FALSE, na_core_utils_dir_is_writable_path(), and na_core_utils_dir_list_perms().
cadp_iio_provider_is_willing_to_write()
gboolean cadp_iio_provider_is_willing_to_write (const NAIIOProvider * provider)
Definition at line 83 of file cadp-writer.c.
References TRUE.
cadp_iio_provider_write_item()
guint cadp_iio_provider_write_item (const NAIIOProvider * provider, const NAObjectItem * item, GSList ** messages)
Definition at line 127 of file cadp-writer.c.
References cadp_desktop_file_new_for_write(), CADP_DESKTOP_FILE_SUFFIX, CADP_DESKTOP_PROVIDER_SUBDIRS, CADP_IS_DESKTOP_FILE, CADP_IS_DESKTOP_PROVIDER, cadp_xdg_dirs_get_user_data_dir(), FALSE, id, item, na_core_utils_dir_list_perms(), na_core_utils_slist_free(), na_core_utils_slist_from_split(), NA_IIO_PROVIDER_CODE_PROGRAM_ERROR, NA_IS_OBJECT_ITEM, na_object_get_id, na_object_get_provider_data, na_object_is_readonly, na_object_set_provider_data, NULL, and TRUE.
cadp_writer_iexporter_export_to_buffer()
guint cadp_writer_iexporter_export_to_buffer (const NAIExporter * instance, NAIExporterBufferParmsv2 * parms)
cadp_writer_iexporter_export_to_buffer: @instance: this NAIExporter instance. @parms: a NAIExporterBufferParmsv2 structure.
Export the specified 'item' to a newly allocated buffer.
Definition at line 355 of file cadp-writer.c.
References NAIExporterBufferParmsv2::buffer, cadp_desktop_file_get_key_file(), cadp_desktop_file_new(), NAIExporterBufferParmsv2::exported, NAIExporterBufferParmsv2::format, NAIExporterBufferParmsv2::messages, NA_IEXPORTER_CODE_ERROR, NA_IEXPORTER_CODE_INVALID_FORMAT, NA_IEXPORTER_CODE_INVALID_ITEM, NA_IEXPORTER_CODE_OK, NA_IFACTORY_OBJECT, NA_IFACTORY_PROVIDER, na_ifactory_provider_write_item(), NA_IIO_PROVIDER_CODE_OK, NA_IS_OBJECT_ITEM, NULL, and NAIExporterBufferParmsv2::version.
cadp_writer_iexporter_export_to_file()
guint cadp_writer_iexporter_export_to_file (const NAIExporter * instance, NAIExporterFileParmsv2 * parms)
cadp_writer_iexporter_export_to_file: @instance: this NAIExporter instance. @parms: a NAIExporterFileParmsv2 structure.
Export the specified 'item' to a newly created file.
Definition at line 415 of file cadp-writer.c.
References NAIExporterFileParmsv2::basename, cadp_desktop_file_new_for_write(), CADP_DESKTOP_FILE_SUFFIX, cadp_desktop_file_write(), NAIExporterFileParmsv2::exported, NAIExporterFileParmsv2::folder, NAIExporterFileParmsv2::format, id, NAIExporterFileParmsv2::messages, NA_IEXPORTER_CODE_ERROR, NA_IEXPORTER_CODE_INVALID_FORMAT, NA_IEXPORTER_CODE_INVALID_ITEM, NA_IEXPORTER_CODE_OK, NA_IEXPORTER_CODE_UNABLE_TO_WRITE, NA_IFACTORY_OBJECT, NA_IFACTORY_PROVIDER, na_ifactory_provider_write_item(), NA_IIO_PROVIDER_CODE_OK, NA_IS_OBJECT_ITEM, na_object_get_id, NULL, and NAIExporterFileParmsv2::version.
cadp_writer_ifactory_provider_write_data()
guint cadp_writer_ifactory_provider_write_data (const NAIFactoryProvider * provider, void * writer_data, const NAIFactoryObject * object, const NADataBoxed * boxed, GSList ** messages)
Definition at line 501 of file cadp-writer.c.
References CADP_DESKTOP_FILE, cadp_desktop_file_remove_key(), cadp_desktop_file_set_boolean(), cadp_desktop_file_set_locale_string(), cadp_desktop_file_set_string(), cadp_desktop_file_set_string_list(), cadp_desktop_file_set_uint(), CADP_GROUP_DESKTOP, CADP_GROUP_PROFILE, CADP_IS_DESKTOP_FILE, NADataDef::desktop_entry, NA_BOXED, na_boxed_get_as_void(), na_boxed_get_string(), na_core_utils_slist_free(), na_data_boxed_get_data_def(), na_data_boxed_is_default(), NA_DATA_TYPE_BOOLEAN, NA_DATA_TYPE_LOCALE_STRING, NA_DATA_TYPE_STRING, NA_DATA_TYPE_STRING_LIST, NA_DATA_TYPE_UINT, NA_IIO_PROVIDER_CODE_OK, NA_IIO_PROVIDER_CODE_PROGRAM_ERROR, NA_IS_OBJECT_PROFILE, na_object_get_id, na_object_get_parameters, NAFO_DATA_PATH, NADataDef::name, NADataDef::type, and NADataDef::write_if_default.
cadp_writer_ifactory_provider_write_done()
guint cadp_writer_ifactory_provider_write_done (const NAIFactoryProvider * provider, void * writer_data, const NAIFactoryObject * object, GSList ** messages)
Definition at line 592 of file cadp-writer.c.
References CADP_DESKTOP_FILE, NA_IIO_PROVIDER_CODE_OK, NA_IS_OBJECT_ITEM, and NA_OBJECT_ITEM.
cadp_writer_ifactory_provider_write_start()
guint cadp_writer_ifactory_provider_write_start (const NAIFactoryProvider * provider, void * writer_data, const NAIFactoryObject * object, GSList ** messages)
Definition at line 476 of file cadp-writer.c.
References CADP_DESKTOP_FILE, NA_IIO_PROVIDER_CODE_OK, NA_IS_OBJECT_ITEM, and NA_OBJECT_ITEM.