MATE Desktop Environment: cadp-desktop-file.c File Reference
cadp-desktop-file.c File Reference
#include <string.h>
#include <gio/gio.h>
#include <api/na-core-utils.h>
#include "cadp-desktop-file.h"
#include "cadp-keys.h"
Functions
GType cadp_desktop_file_get_type (void)
CappDesktopFile * cadp_desktop_file_new (void)
CappDesktopFile * cadp_desktop_file_new_from_path (const gchar *path)
CappDesktopFile * cadp_desktop_file_new_from_uri (const gchar *uri)
CappDesktopFile * cadp_desktop_file_new_for_write (const gchar *path)
GKeyFile * cadp_desktop_file_get_key_file (const CappDesktopFile *ndf)
gchar * cadp_desktop_file_get_key_file_uri (const CappDesktopFile *ndf)
gchar * cadp_desktop_file_get_file_type (const CappDesktopFile *ndf)
gchar * cadp_desktop_file_get_id (const CappDesktopFile *ndf)
GSList * cadp_desktop_file_get_profiles (const CappDesktopFile *ndf)
gboolean cadp_desktop_file_has_profile (const CappDesktopFile *ndf, const gchar *profile_id)
void cadp_desktop_file_remove_key (const CappDesktopFile *ndf, const gchar *group, const gchar *key)
void cadp_desktop_file_remove_profile (const CappDesktopFile *ndf, const gchar *profile_id)
gboolean cadp_desktop_file_get_boolean (const CappDesktopFile *ndf, const gchar *group, const gchar *entry, gboolean *key_found, gboolean default_value)
gchar * cadp_desktop_file_get_locale_string (const CappDesktopFile *ndf, const gchar *group, const gchar *entry, gboolean *key_found, const gchar *default_value)
gchar * cadp_desktop_file_get_string (const CappDesktopFile *ndf, const gchar *group, const gchar *entry, gboolean *key_found, const gchar *default_value)
GSList * cadp_desktop_file_get_string_list (const CappDesktopFile *ndf, const gchar *group, const gchar *entry, gboolean *key_found, const gchar *default_value)
guint cadp_desktop_file_get_uint (const CappDesktopFile *ndf, const gchar *group, const gchar *entry, gboolean *key_found, guint default_value)
void cadp_desktop_file_set_boolean (const CappDesktopFile *ndf, const gchar *group, const gchar *key, gboolean value)
void cadp_desktop_file_set_locale_string (const CappDesktopFile *ndf, const gchar *group, const gchar *key, const gchar *value)
void cadp_desktop_file_set_string (const CappDesktopFile *ndf, const gchar *group, const gchar *key, const gchar *value)
void cadp_desktop_file_set_string_list (const CappDesktopFile *ndf, const gchar *group, const gchar *key, GSList *value)
void cadp_desktop_file_set_uint (const CappDesktopFile *ndf, const gchar *group, const gchar *key, guint value)
gboolean cadp_desktop_file_write (CappDesktopFile *ndf)
Function Documentation
cadp_desktop_file_get_boolean()
gboolean cadp_desktop_file_get_boolean (const CappDesktopFile * ndf, const gchar * group, const gchar * entry, gboolean * key_found, gboolean default_value)
cadp_desktop_file_get_boolean: @ndf: this CappDesktopFile instance. @group: the searched group. @entry: the searched entry. @key_found: set to TRUE if the key has been found, to FALSE else. @default_value: value to be set if key has not been found.
Returns: the read value, or the default value if the entry has not been found in the given group.
Definition at line 729 of file cadp-desktop-file.c.
References CADP_IS_DESKTOP_FILE, error, FALSE, NULL, CappDesktopFile::private, and TRUE.
Referenced by cadp_reader_ifactory_provider_read_data().
cadp_desktop_file_get_file_type()
gchar * cadp_desktop_file_get_file_type (const CappDesktopFile * ndf)
cadp_desktop_file_get_type: @ndf: the CappDesktopFile instance.
Returns: the value for the Type entry as a newly allocated string which should be g_free() by the caller.
Definition at line 536 of file cadp-desktop-file.c.
References CADP_IS_DESKTOP_FILE, NULL, CappDesktopFile::private, and type.
cadp_desktop_file_get_id()
gchar * cadp_desktop_file_get_id (const CappDesktopFile * ndf)
cadp_desktop_file_get_id: @ndf: the CappDesktopFile instance.
Returns: a newly allocated string which holds the id of the Desktop File.
Definition at line 560 of file cadp-desktop-file.c.
References CADP_IS_DESKTOP_FILE, NULL, and CappDesktopFile::private.
cadp_desktop_file_get_key_file()
GKeyFile * cadp_desktop_file_get_key_file (const CappDesktopFile * ndf)
cadp_desktop_file_get_key_file: @ndf: the CappDesktopFile instance.
Returns: a pointer to the internal #GKeyFile.
Definition at line 359 of file cadp-desktop-file.c.
References CADP_IS_DESKTOP_FILE, NULL, and CappDesktopFile::private.
Referenced by cadp_writer_iexporter_export_to_buffer().
cadp_desktop_file_get_key_file_uri()
gchar * cadp_desktop_file_get_key_file_uri (const CappDesktopFile * ndf)
cadp_desktop_file_get_key_file_uri: @ndf: the CappDesktopFile instance.
Returns: the URI of the key file, as a newly allocated string which should be g_free() by the caller.
Definition at line 383 of file cadp-desktop-file.c.
References CADP_IS_DESKTOP_FILE, NULL, and CappDesktopFile::private.
Referenced by cadp_iio_provider_delete_item().
cadp_desktop_file_get_locale_string()
gchar * cadp_desktop_file_get_locale_string (const CappDesktopFile * ndf, const gchar * group, const gchar * entry, gboolean * key_found, const gchar * default_value)
cadp_desktop_file_get_locale_string: @ndf: this CappDesktopFile instance. @group: the searched group. @entry: the searched entry. @key_found: set to TRUE if the key has been found, to FALSE else. @default_value: value to be set if key has not been found.
Returns: the read value, or the default value if the entry has not been found in the given group.
Definition at line 778 of file cadp-desktop-file.c.
References CADP_IS_DESKTOP_FILE, error, FALSE, NULL, CappDesktopFile::private, and TRUE.
Referenced by cadp_reader_ifactory_provider_read_data().
cadp_desktop_file_get_profiles()
GSList * cadp_desktop_file_get_profiles (const CappDesktopFile * ndf)
cadp_desktop_file_get_profiles: @ndf: the CappDesktopFile instance.
Returns: the list of profiles in the file, as a newly allocated GSList which must be na_core_utils_slist_free() by the caller.
Silently ignore unknown groups.
Definition at line 586 of file cadp-desktop-file.c.
References CADP_GROUP_PROFILE, CADP_IS_DESKTOP_FILE, NULL, and CappDesktopFile::private.
cadp_desktop_file_get_string()
gchar * cadp_desktop_file_get_string (const CappDesktopFile * ndf, const gchar * group, const gchar * entry, gboolean * key_found, const gchar * default_value)
cadp_desktop_file_get_string: @ndf: this CappDesktopFile instance. @group: the searched group. @entry: the searched entry. @key_found: set to TRUE if the key has been found, to FALSE else. @default_value: value to be set if key has not been found.
Returns: the read value, or the default value if the entry has not been found in the given group.
Definition at line 824 of file cadp-desktop-file.c.
References CADP_IS_DESKTOP_FILE, error, FALSE, NULL, CappDesktopFile::private, and TRUE.
Referenced by cadp_reader_ifactory_provider_read_data().
cadp_desktop_file_get_string_list()
GSList * cadp_desktop_file_get_string_list (const CappDesktopFile * ndf, const gchar * group, const gchar * entry, gboolean * key_found, const gchar * default_value)
cadp_desktop_file_get_string_list: @ndf: this CappDesktopFile instance. @group: the searched group. @entry: the searched entry. @key_found: set to TRUE if the key has been found, to FALSE else. @default_value: value to be set if key has not been found.
Returns: the read value, or the default value if the entry has not been found in the given group.
Definition at line 875 of file cadp-desktop-file.c.
References CADP_IS_DESKTOP_FILE, error, FALSE, na_core_utils_slist_free(), na_core_utils_slist_from_array(), NULL, CappDesktopFile::private, and TRUE.
Referenced by cadp_reader_ifactory_provider_read_data().
cadp_desktop_file_get_type()
GType cadp_desktop_file_get_type (void)
Definition at line 74 of file cadp-desktop-file.c.
cadp_desktop_file_get_uint()
guint cadp_desktop_file_get_uint (const CappDesktopFile * ndf, const gchar * group, const gchar * entry, gboolean * key_found, guint default_value)
cadp_desktop_file_get_uint: @ndf: this CappDesktopFile instance. @group: the searched group. @entry: the searched entry. @key_found: set to TRUE if the key has been found, to FALSE else. @default_value: value to be set if key has not been found.
Returns: the read value, or the default value if the entry has not been found in the given group.
Definition at line 927 of file cadp-desktop-file.c.
References CADP_IS_DESKTOP_FILE, error, FALSE, NULL, CappDesktopFile::private, and TRUE.
Referenced by cadp_reader_ifactory_provider_read_data().
cadp_desktop_file_has_profile()
gboolean cadp_desktop_file_has_profile (const CappDesktopFile * ndf, const gchar * profile_id)
cadp_desktop_file_has_profile: @ndf: the CappDesktopFile instance. @profile_id: the identifier of the profile.
Returns: TRUE if a group can be found in the .desktop file for this profile, FALSE else.
Since: 3.1
Definition at line 634 of file cadp-desktop-file.c.
References CADP_GROUP_PROFILE, CADP_IS_DESKTOP_FILE, FALSE, and CappDesktopFile::private.
cadp_desktop_file_new()
CappDesktopFile * cadp_desktop_file_new (void)
cadp_desktop_file_new:
Retuns: a newly allocated CappDesktopFile object.
Definition at line 201 of file cadp-desktop-file.c.
References CADP_TYPE_DESKTOP_FILE, and NULL.
Referenced by cadp_writer_iexporter_export_to_buffer().
cadp_desktop_file_new_for_write()
CappDesktopFile * cadp_desktop_file_new_for_write (const gchar * path)
cadp_desktop_file_new_for_write: @path: the full pathname of a .desktop file.
Retuns: a newly allocated CappDesktopFile object.
Definition at line 325 of file cadp-desktop-file.c.
References error, and NULL.
Referenced by cadp_iio_provider_write_item(), and cadp_writer_iexporter_export_to_file().
cadp_desktop_file_new_from_path()
CappDesktopFile * cadp_desktop_file_new_from_path (const gchar * path)
cadp_desktop_file_new_from_path: @path: the full pathname of a .desktop file.
Retuns: a newly allocated CappDesktopFile object.
Key file has been loaded, and first validity checks made.
Definition at line 219 of file cadp-desktop-file.c.
References error, NULL, and CappDesktopFile::private.
cadp_desktop_file_new_from_uri()
CappDesktopFile * cadp_desktop_file_new_from_uri (const gchar * uri)
cadp_desktop_file_new_from_uri: @uri: the URI the desktop file should be loaded from.
Retuns: a newly allocated CappDesktopFile object, or NULL.
Key file has been loaded, and first validity checks made.
Note: This function is in particular used when importing a file. So it is rather common that the file not be a .desktop one. Do not warns when file is malformed.
Definition at line 272 of file cadp-desktop-file.c.
References data, error, na_core_utils_file_load_from_uri(), NULL, and CappDesktopFile::private.
Referenced by cadp_reader_iimporter_import_from_uri().
cadp_desktop_file_remove_key()
void cadp_desktop_file_remove_key (const CappDesktopFile * ndf, const gchar * group, const gchar * key)
cadp_desktop_file_remove_key: @ndf: this CappDesktopFile instance. @group: the group. @key: the key.
Removes the specified key.
Note that this doesn't work very well for localized keys, as we only remove a key which has the exact same label that the provided one. So we'd have to remove:
key
key[en_US.UTF-8]
key[en_US]
key[en]
Definition at line 671 of file cadp-desktop-file.c.
References CADP_IS_DESKTOP_FILE, key, NULL, and CappDesktopFile::private.
Referenced by cadp_writer_ifactory_provider_write_data().
cadp_desktop_file_remove_profile()
void cadp_desktop_file_remove_profile (const CappDesktopFile * ndf, const gchar * profile_id)
cadp_desktop_file_remove_profile: @ndf: this CappDesktopFile instance. @profile_id: the id of the profile.
Removes the group which describes the specified profile.
Definition at line 703 of file cadp-desktop-file.c.
References CADP_GROUP_PROFILE, CADP_IS_DESKTOP_FILE, NULL, and CappDesktopFile::private.
cadp_desktop_file_set_boolean()
void cadp_desktop_file_set_boolean (const CappDesktopFile * ndf, const gchar * group, const gchar * key, gboolean value)
cadp_desktop_file_set_boolean: @ndf: this CappDesktopFile object. @group: the name of the group. @key: the name of the key. @value: the value to be written.
Write the given boolean value.
Definition at line 972 of file cadp-desktop-file.c.
References CADP_IS_DESKTOP_FILE, key, and CappDesktopFile::private.
Referenced by cadp_writer_ifactory_provider_write_data().
cadp_desktop_file_set_locale_string()
void cadp_desktop_file_set_locale_string (const CappDesktopFile * ndf, const gchar * group, const gchar * key, const gchar * value)
cadp_desktop_file_set_locale_string: @ndf: this CappDesktopFile object. @group: the name of the group. @key: the name of the key. @value: the value to be written.
Write the given string value.
Until v 3.0.4, locale strings used to be written for all available locales e.g. 'en_US.UTF-8', 'en_US', 'en.UTF-8', 'en', 'C'.
Starting with v 3.0.4, encoding part of the locale is no more written.
The better solution would be to include in the UI a listbox with all available locales, letting the user choose himself which locale he wish modify.
A first fallback would be to set some sort of user preferences: whether to write all available locales, whether to write all but C locales, ...
As of v 3.0.4, we choose:
always write the first locale, which should obviously be the user locale;
also write all locales derived from the first (e.g. en_US, en_GB, en);
when the prefix of the locale changes, stop to write other locales unless the first prefix was 'en', as we suppose that the C locale will always be in english.
The locale prefix is identified by '_' or '@' character.
Definition at line 1013 of file cadp-desktop-file.c.
References CADP_IS_DESKTOP_FILE, FALSE, key, prefix, CappDesktopFile::private, and TRUE.
Referenced by cadp_writer_ifactory_provider_write_data().
cadp_desktop_file_set_string()
void cadp_desktop_file_set_string (const CappDesktopFile * ndf, const gchar * group, const gchar * key, const gchar * value)
cadp_desktop_file_set_string: @ndf: this CappDesktopFile object. @group: the name of the group. @key: the name of the key. @value: the value to be written.
Write the given string value.
Definition at line 1086 of file cadp-desktop-file.c.
References CADP_IS_DESKTOP_FILE, key, and CappDesktopFile::private.
Referenced by cadp_writer_ifactory_provider_write_data().
cadp_desktop_file_set_string_list()
void cadp_desktop_file_set_string_list (const CappDesktopFile * ndf, const gchar * group, const gchar * key, GSList * value)
cadp_desktop_file_set_string_list: @ndf: this CappDesktopFile object. @group: the name of the group. @key: the name of the key. @value: the value to be written.
Write the given list value.
Definition at line 1106 of file cadp-desktop-file.c.
References CADP_IS_DESKTOP_FILE, key, na_core_utils_slist_to_array(), and CappDesktopFile::private.
Referenced by cadp_writer_ifactory_provider_write_data().
cadp_desktop_file_set_uint()
void cadp_desktop_file_set_uint (const CappDesktopFile * ndf, const gchar * group, const gchar * key, guint value)
cadp_desktop_file_set_uint: @ndf: this CappDesktopFile object. @group: the name of the group. @key: the name of the key. @value: the value to be written.
Write the given uint value.
Definition at line 1130 of file cadp-desktop-file.c.
References CADP_IS_DESKTOP_FILE, key, and CappDesktopFile::private.
Referenced by cadp_writer_ifactory_provider_write_data().
cadp_desktop_file_write()
gboolean cadp_desktop_file_write (CappDesktopFile * ndf)
cadp_desktop_file_write: @ndf: the CappDesktopFile instance.
Writes the key file to the disk.
Returns: TRUE if write is ok, FALSE else.
Starting with v 3.0.4, locale strings whose identifier include an encoding part are removed from the desktop file when rewriting it (these were wrongly written between v 2.99 and 3.0.3).
Definition at line 1153 of file cadp-desktop-file.c.
References CADP_IS_DESKTOP_FILE, data, error, FALSE, NULL, CappDesktopFile::private, and TRUE.
Referenced by cadp_writer_iexporter_export_to_file().