MATE Desktop Environment: caja-sidebar.h File Reference
caja-sidebar.h File Reference
#include <glib-object.h>
#include <gtk/gtk.h>
Classes
struct _CajaSidebarIface
Macros
#define CAJA_TYPE_SIDEBAR (caja_sidebar_get_type ())
#define CAJA_SIDEBAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_SIDEBAR, CajaSidebar))
#define CAJA_IS_SIDEBAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_SIDEBAR))
#define CAJA_SIDEBAR_GET_IFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), CAJA_TYPE_SIDEBAR, CajaSidebarIface))
Typedefs
typedef struct _CajaSidebar CajaSidebar
typedef struct _CajaSidebarIface CajaSidebarIface
Functions
GType caja_sidebar_get_type (void)
const char * caja_sidebar_get_sidebar_id (CajaSidebar *sidebar)
char * caja_sidebar_get_tab_label (CajaSidebar *sidebar)
char * caja_sidebar_get_tab_tooltip (CajaSidebar *sidebar)
GdkPixbuf * caja_sidebar_get_tab_icon (CajaSidebar *sidebar)
void caja_sidebar_is_visible_changed (CajaSidebar *sidebar, gboolean is_visible)
Macro Definition Documentation
CAJA_IS_SIDEBAR
#define CAJA_IS_SIDEBAR (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_SIDEBAR))
Definition at line 37 of file caja-sidebar.h.
CAJA_SIDEBAR
#define CAJA_SIDEBAR (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_SIDEBAR, CajaSidebar))
Definition at line 36 of file caja-sidebar.h.
CAJA_SIDEBAR_GET_IFACE
#define CAJA_SIDEBAR_GET_IFACE (obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), CAJA_TYPE_SIDEBAR, CajaSidebarIface))
Definition at line 38 of file caja-sidebar.h.
CAJA_TYPE_SIDEBAR
#define CAJA_TYPE_SIDEBAR (caja_sidebar_get_type ())
Definition at line 35 of file caja-sidebar.h.
Typedef Documentation
CajaSidebar
typedef struct _CajaSidebar CajaSidebar
Definition at line 40 of file caja-sidebar.h.
CajaSidebarIface
typedef struct _CajaSidebarIface CajaSidebarIface
Definition at line 41 of file caja-sidebar.h.
Function Documentation
caja_sidebar_get_sidebar_id()
const char * caja_sidebar_get_sidebar_id (CajaSidebar * sidebar)
Definition at line 89 of file caja-sidebar.c.
References CAJA_IS_SIDEBAR, CAJA_SIDEBAR_GET_IFACE, and NULL.
Referenced by caja_navigation_window_add_sidebar_panel().
caja_sidebar_get_tab_icon()
GdkPixbuf * caja_sidebar_get_tab_icon (CajaSidebar * sidebar)
Definition at line 113 of file caja-sidebar.c.
References CAJA_IS_SIDEBAR, CAJA_SIDEBAR_GET_IFACE, and NULL.
Referenced by caja_navigation_window_add_sidebar_panel().
caja_sidebar_get_tab_label()
char * caja_sidebar_get_tab_label (CajaSidebar * sidebar)
Definition at line 97 of file caja-sidebar.c.
References CAJA_IS_SIDEBAR, CAJA_SIDEBAR_GET_IFACE, and NULL.
Referenced by caja_navigation_window_add_sidebar_panel().
caja_sidebar_get_tab_tooltip()
char * caja_sidebar_get_tab_tooltip (CajaSidebar * sidebar)
Definition at line 105 of file caja-sidebar.c.
References CAJA_IS_SIDEBAR, CAJA_SIDEBAR_GET_IFACE, and NULL.
Referenced by caja_navigation_window_add_sidebar_panel().
caja_sidebar_get_type()
GType caja_sidebar_get_type (void)
Definition at line 59 of file caja-sidebar.c.
References NULL, and type.
caja_sidebar_is_visible_changed()
void caja_sidebar_is_visible_changed (CajaSidebar * sidebar, gboolean is_visible)
Definition at line 121 of file caja-sidebar.c.
References CAJA_IS_SIDEBAR, and CAJA_SIDEBAR_GET_IFACE.