MATE Desktop Environment: caja-file-management-properties-main.c File Reference
caja-file-management-properties-main.c File Reference
#include <config.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <libcaja-private/caja-global-preferences.h>
#include <libcaja-private/caja-module.h>
#include "caja-file-management-properties.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 46 of file caja-file-management-properties-main.c.
References caja_file_management_properties_dialog_show(), caja_global_preferences_init(), caja_module_setup(), and NULL.