MATE Desktop Environment: caja-clipboard-monitor.c File Reference
caja-clipboard-monitor.c File Reference
#include <config.h>
#include <gtk/gtk.h>
#include <eel/eel-debug.h>
#include <eel/eel-gtk-macros.h>
#include <eel/eel-glib-extensions.h>
#include "caja-clipboard-monitor.h"
#include "caja-file.h"
Enumerations
enum { CLIPBOARD_CHANGED , CLIPBOARD_INFO , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (CajaClipboardMonitor, caja_clipboard_monitor, G_TYPE_OBJECT)
CajaClipboardMonitor * caja_clipboard_monitor_get (void)
void caja_clipboard_monitor_emit_changed (void)
void caja_clipboard_monitor_set_clipboard_info (CajaClipboardMonitor *monitor, CajaClipboardInfo *info)
CajaClipboardInfo * caja_clipboard_monitor_get_clipboard_info (CajaClipboardMonitor *monitor)
void caja_clear_clipboard_callback (GtkClipboard *clipboard, gpointer user_data)
void caja_get_clipboard_callback (GtkClipboard *clipboard, GtkSelectionData *selection_data, guint info, gpointer user_data)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CLIPBOARD_CHANGED
CLIPBOARD_INFO
LAST_SIGNAL
Definition at line 50 of file caja-clipboard-monitor.c.
Function Documentation
caja_clear_clipboard_callback()
void caja_clear_clipboard_callback (GtkClipboard * clipboard, gpointer user_data)
Definition at line 217 of file caja-clipboard-monitor.c.
References caja_clipboard_monitor_get(), caja_clipboard_monitor_set_clipboard_info(), and NULL.
caja_clipboard_monitor_emit_changed()
void caja_clipboard_monitor_emit_changed (void)
Definition at line 96 of file caja-clipboard-monitor.c.
References caja_clipboard_monitor_get(), and CLIPBOARD_CHANGED.
Referenced by caja_clipboard_monitor_get(), and caja_clipboard_monitor_set_clipboard_info().
caja_clipboard_monitor_get()
CajaClipboardMonitor * caja_clipboard_monitor_get (void)
Definition at line 79 of file caja-clipboard-monitor.c.
References CAJA_CLIPBOARD_MONITOR, caja_clipboard_monitor_emit_changed(), CAJA_TYPE_CLIPBOARD_MONITOR, eel_debug_call_at_shutdown(), and NULL.
Referenced by caja_clear_clipboard_callback(), caja_clipboard_monitor_emit_changed(), and caja_get_clipboard_callback().
caja_clipboard_monitor_get_clipboard_info()
CajaClipboardInfo * caja_clipboard_monitor_get_clipboard_info (CajaClipboardMonitor * monitor)
Definition at line 211 of file caja-clipboard-monitor.c.
References CajaClipboardMonitor::details.
Referenced by caja_get_clipboard_callback().
caja_clipboard_monitor_set_clipboard_info()
void caja_clipboard_monitor_set_clipboard_info (CajaClipboardMonitor * monitor, CajaClipboardInfo * info)
Definition at line 194 of file caja-clipboard-monitor.c.
References caja_clipboard_monitor_emit_changed(), CLIPBOARD_INFO, CajaClipboardMonitor::details, and NULL.
Referenced by caja_clear_clipboard_callback().
caja_get_clipboard_callback()
void caja_get_clipboard_callback (GtkClipboard * clipboard, GtkSelectionData * selection_data, guint info, gpointer user_data)
Definition at line 286 of file caja-clipboard-monitor.c.
References caja_clipboard_monitor_get(), caja_clipboard_monitor_get_clipboard_info(), caja_file_get_uri(), FALSE, CajaClipboardInfo::files, NULL, and TRUE.
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (CajaClipboardMonitor , caja_clipboard_monitor , G_TYPE_OBJECT)