MATE Desktop Environment: caja-window.h File Reference
caja-window.h File Reference
#include <gtk/gtk.h>
#include <eel/eel-glib-extensions.h>
#include <libcaja-private/caja-bookmark.h>
#include <libcaja-private/caja-entry.h>
#include <libcaja-private/caja-window-info.h>
#include <libcaja-private/caja-search-directory.h>
#include "caja-application.h"
#include "caja-information-panel.h"
#include "caja-side-pane.h"
Classes
struct CajaWindowClass
struct CajaWindow
Macros
#define CAJA_TYPE_WINDOW caja_window_get_type()
#define CAJA_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_WINDOW, CajaWindow))
#define CAJA_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_WINDOW, CajaWindowClass))
#define CAJA_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_WINDOW))
#define CAJA_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_WINDOW))
#define CAJA_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_WINDOW, CajaWindowClass))
#define CAJA_WINDOW_SLOT_DEFINED
Typedefs
typedef struct CajaWindowSlot CajaWindowSlot
typedef struct _CajaWindowPane CajaWindowPane
typedef struct CajaWindowSlotClass CajaWindowSlotClass
typedef enum CajaWindowOpenSlotFlags CajaWindowOpenSlotFlags
typedef struct _CajaWindowPrivate CajaWindowPrivate
Enumerations
enum CajaWindowShowState { CAJA_WINDOW_NOT_SHOWN , CAJA_WINDOW_POSITION_SET , CAJA_WINDOW_SHOULD_SHOW }
enum CajaWindowOpenSlotFlags { CAJA_WINDOW_OPEN_SLOT_NONE = 0 , CAJA_WINDOW_OPEN_SLOT_APPEND = 1 }
Functions
GType caja_window_get_type (void)
void caja_window_show_window (CajaWindow *window)
void caja_window_close (CajaWindow *window)
void caja_window_connect_content_view (CajaWindow *window, CajaView *view)
void caja_window_disconnect_content_view (CajaWindow *window, CajaView *view)
void caja_window_go_to (CajaWindow *window, GFile *location)
void caja_window_go_to_tab (CajaWindow *window, GFile *location)
void caja_window_go_to_full (CajaWindow *window, GFile *location, CajaWindowGoToCallback callback, gpointer user_data)
void caja_window_go_to_with_selection (CajaWindow *window, GFile *location, GList *new_selection)
void caja_window_go_home (CajaWindow *window)
void caja_window_new_tab (CajaWindow *window)
void caja_window_new_window (CajaWindow *window)
void caja_window_go_up (CajaWindow *window, gboolean close_behind, gboolean new_tab)
void caja_window_prompt_for_location (CajaWindow *window, const char *initial)
void caja_window_display_error (CajaWindow *window, const char *error_msg)
void caja_window_reload (CajaWindow *window, gboolean new_tab)
void caja_window_allow_reload (CajaWindow *window, gboolean allow)
void caja_window_allow_up (CajaWindow *window, gboolean allow)
void caja_window_allow_stop (CajaWindow *window, gboolean allow)
GtkUIManager * caja_window_get_ui_manager (CajaWindow *window)
Macro Definition Documentation
CAJA_IS_WINDOW
#define CAJA_IS_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_WINDOW))
Definition at line 48 of file caja-window.h.
CAJA_IS_WINDOW_CLASS
#define CAJA_IS_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_WINDOW))
Definition at line 50 of file caja-window.h.
CAJA_TYPE_WINDOW
#define CAJA_TYPE_WINDOW caja_window_get_type()
Definition at line 43 of file caja-window.h.
CAJA_WINDOW
#define CAJA_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_WINDOW, CajaWindow))
Definition at line 44 of file caja-window.h.
CAJA_WINDOW_CLASS
#define CAJA_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_WINDOW, CajaWindowClass))
Definition at line 46 of file caja-window.h.
CAJA_WINDOW_GET_CLASS
#define CAJA_WINDOW_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_WINDOW, CajaWindowClass))
Definition at line 52 of file caja-window.h.
CAJA_WINDOW_SLOT_DEFINED
#define CAJA_WINDOW_SLOT_DEFINED
Definition at line 61 of file caja-window.h.
Typedef Documentation
CajaWindowOpenSlotFlags
typedef enum CajaWindowOpenSlotFlags CajaWindowOpenSlotFlags
Definition at line 68 of file caja-window.h.
CajaWindowPane
typedef struct _CajaWindowPane CajaWindowPane
Definition at line 65 of file caja-window.h.
CajaWindowPrivate
typedef struct _CajaWindowPrivate CajaWindowPrivate
Definition at line 83 of file caja-window.h.
CajaWindowSlot
typedef struct CajaWindowSlot CajaWindowSlot
Definition at line 62 of file caja-window.h.
CajaWindowSlotClass
typedef struct CajaWindowSlotClass CajaWindowSlotClass
Definition at line 67 of file caja-window.h.
Enumeration Type Documentation
CajaWindowOpenSlotFlags
enum CajaWindowOpenSlotFlags
Enumerator
CAJA_WINDOW_OPEN_SLOT_NONE
CAJA_WINDOW_OPEN_SLOT_APPEND
Definition at line 77 of file caja-window.h.
CajaWindowShowState
enum CajaWindowShowState
Enumerator
CAJA_WINDOW_NOT_SHOWN
CAJA_WINDOW_POSITION_SET
CAJA_WINDOW_SHOULD_SHOW
Definition at line 70 of file caja-window.h.
Function Documentation
caja_window_allow_reload()
void caja_window_allow_reload (CajaWindow * window, gboolean allow)
Definition at line 508 of file caja-window.c.
References action, CAJA_ACTION_RELOAD, CAJA_IS_WINDOW, CajaWindow::details, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, and _CajaWindowPrivate::main_action_group.
caja_window_allow_stop()
void caja_window_allow_stop (CajaWindow * window, gboolean allow)
caja_window_allow_up()
void caja_window_allow_up (CajaWindow * window, gboolean allow)
Definition at line 419 of file caja-window.c.
References CAJA_IS_WINDOW, CAJA_WINDOW_CLASS, and EEL_CALL_METHOD.
Referenced by caja_window_update_up_button().
caja_window_close()
void caja_window_close (CajaWindow * window)
Definition at line 837 of file caja-window.c.
References CAJA_IS_WINDOW, CAJA_WINDOW_CLASS, and EEL_CALL_METHOD.
Referenced by caja_application_close_all_navigation_windows(), caja_application_close_all_spatial_windows(), caja_application_close_parent_windows(), caja_window_pane_slot_close(), and caja_window_slot_open_location_full().
caja_window_connect_content_view()
void caja_window_connect_content_view (CajaWindow * window, CajaView * view)
Definition at line 1606 of file caja-window.c.
References CAJA_IS_VIEW, CAJA_IS_WINDOW, caja_view_grab_focus(), caja_window_get_active_slot(), caja_window_get_slot_for_view(), caja_window_load_view_as_menus(), NULL, and CajaWindowSlot::pending_location.
Referenced by caja_window_slot_connect_content_view().
caja_window_disconnect_content_view()
void caja_window_disconnect_content_view (CajaWindow * window, CajaView * view)
Definition at line 1635 of file caja-window.c.
References CAJA_IS_VIEW, CAJA_IS_WINDOW, caja_window_get_active_slot(), and caja_window_get_slot_for_view().
Referenced by caja_window_slot_disconnect_content_view().
caja_window_display_error()
void caja_window_display_error (CajaWindow * window, const char * error_msg)
Definition at line 1495 of file caja-window.c.
References CAJA_IS_WINDOW, and NULL.
caja_window_get_type()
GType caja_window_get_type (void)
caja_window_get_ui_manager()
GtkUIManager * caja_window_get_ui_manager (CajaWindow * window)
Definition at line 1669 of file caja-window.c.
References CAJA_IS_WINDOW, CajaWindow::details, NULL, and _CajaWindowPrivate::ui_manager.
Referenced by caja_location_bar_new(), caja_navigation_window_initialize_actions(), caja_navigation_window_initialize_menus(), caja_navigation_window_load_extension_toolbar_items(), caja_navigation_window_remove_go_menu_items(), and caja_search_bar_new().
caja_window_go_home()
void caja_window_go_home (CajaWindow * window)
Definition at line 522 of file caja-window.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CAJA_IS_WINDOW, caja_window_slot_go_home(), CajaWindow::details, and FALSE.
caja_window_go_to()
void caja_window_go_to (CajaWindow * window, GFile * location)
Definition at line 234 of file caja-window.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CAJA_IS_WINDOW, caja_window_slot_go_to, CajaWindow::details, and FALSE.
Referenced by caja_desktop_window_update_directory().
caja_window_go_to_full()
void caja_window_go_to_full (CajaWindow * window, GFile * location, CajaWindowGoToCallback callback, gpointer user_data)
Definition at line 250 of file caja-window.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CAJA_IS_WINDOW, caja_window_slot_go_to_full, CajaWindow::details, FALSE, and user_data.
Referenced by caja_connect_server_dialog_display_location_async().
caja_window_go_to_tab()
void caja_window_go_to_tab (CajaWindow * window, GFile * location)
Definition at line 242 of file caja-window.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CAJA_IS_WINDOW, caja_window_slot_go_to, CajaWindow::details, and TRUE.
caja_window_go_to_with_selection()
void caja_window_go_to_with_selection (CajaWindow * window, GFile * location, GList * new_selection)
Definition at line 261 of file caja-window.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CAJA_IS_WINDOW, caja_window_slot_go_to_with_selection, and CajaWindow::details.
caja_window_go_up()
void caja_window_go_up (CajaWindow * window, gboolean close_behind, gboolean new_tab)
Definition at line 354 of file caja-window.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CAJA_IS_WINDOW, CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, CAJA_WINDOW_OPEN_FLAG_CLOSE_BEHIND, CAJA_WINDOW_OPEN_FLAG_NEW_TAB, caja_window_slot_open_location_full(), CajaWindow::details, CajaWindowSlot::location, and NULL.
caja_window_new_tab()
void caja_window_new_tab (CajaWindow * window)
Definition at line 282 of file caja-window.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CAJA_NEW_TAB_POSITION_END, caja_preferences, CAJA_PREFERENCES_NEW_TAB_POSITION, caja_window_open_slot(), CAJA_WINDOW_OPEN_SLOT_APPEND, caja_window_set_active_slot(), caja_window_slot_get_location(), caja_window_slot_go_to, CajaWindow::details, FALSE, NULL, and CajaWindowSlot::pane.
caja_window_new_window()
void caja_window_new_window (CajaWindow * window)
Definition at line 319 of file caja-window.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CajaWindow::application, caja_application_create_navigation_window(), CAJA_IS_WINDOW, CAJA_IS_WINDOW_SLOT, CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, caja_window_slot_get_location(), caja_window_slot_open_location_full(), CajaWindow::details, FALSE, and NULL.
caja_window_prompt_for_location()
void caja_window_prompt_for_location (CajaWindow * window, const char * initial)
Definition at line 530 of file caja-window.c.
References CAJA_IS_WINDOW, CAJA_WINDOW_CLASS, and EEL_CALL_METHOD.
caja_window_reload()
void caja_window_reload (CajaWindow * window, gboolean new_tab)
Definition at line 486 of file caja-window.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CAJA_IS_WINDOW, CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, CAJA_WINDOW_OPEN_FLAG_NEW_TAB, caja_window_slot_open_location_full(), caja_window_slot_reload(), CajaWindow::details, CajaWindowSlot::location, and NULL.
caja_window_show_window()
void caja_window_show_window (CajaWindow * window)
Definition at line 745 of file caja-window.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, caja_file_set_has_open_window(), CAJA_IS_SPATIAL_WINDOW, caja_window_slot_update_icon(), caja_window_slot_update_title(), CajaWindow::details, NULL, _CajaWindowPrivate::panes, _CajaWindowPane::slots, TRUE, and CajaWindowSlot::viewed_file.