MATE Desktop Environment: caja-sidebar-title.c File Reference
caja-sidebar-title.c File Reference
#include <config.h>
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include <gtk/gtk.h>
#include <pango/pango.h>
#include <glib/gi18n.h>
#include <eel/eel-background.h>
#include <eel/eel-gdk-extensions.h>
#include <eel/eel-gdk-pixbuf-extensions.h>
#include <eel/eel-glib-extensions.h>
#include <eel/eel-gtk-extensions.h>
#include <libcaja-private/caja-file-attributes.h>
#include <libcaja-private/caja-global-preferences.h>
#include <libcaja-private/caja-metadata.h>
#include <libcaja-private/caja-sidebar.h>
#include "caja-sidebar-title.h"
#include "caja-window.h"
Macros
#define MAX_TITLE_SIZE 256
#define MINIMUM_INFO_WIDTH 32
#define SIDEBAR_INFO_MARGIN 4
#define MIN_TITLE_FONT_SIZE 12
#define TITLE_PADDING 4
#define DEFAULT_LIGHT_INFO_COLOR "#FFFFFF"
#define DEFAULT_DARK_INFO_COLOR "#2A2A2A"
Enumerations
enum {
LABEL_COLOR , LABEL_COLOR_HIGHLIGHT , LABEL_COLOR_ACTIVE , LABEL_COLOR_PRELIGHT ,
LABEL_INFO_COLOR , LABEL_INFO_COLOR_HIGHLIGHT , LABEL_INFO_COLOR_ACTIVE , LAST_LABEL_COLOR
}
Functions
GtkWidget * caja_sidebar_title_new (void)
void caja_sidebar_title_select_text_color (CajaSidebarTitle *sidebar_title, EelBackground *background)
char * caja_sidebar_title_get_text (CajaSidebarTitle *sidebar_title)
void caja_sidebar_title_set_text (CajaSidebarTitle *sidebar_title, const char *new_text)
void caja_sidebar_title_set_file (CajaSidebarTitle *sidebar_title, CajaFile *file, const char *initial_text)
gboolean caja_sidebar_title_hit_test_icon (CajaSidebarTitle *sidebar_title, int x, int y)
Macro Definition Documentation
DEFAULT_DARK_INFO_COLOR
#define DEFAULT_DARK_INFO_COLOR "#2A2A2A"
Definition at line 59 of file caja-sidebar-title.c.
DEFAULT_LIGHT_INFO_COLOR
#define DEFAULT_LIGHT_INFO_COLOR "#FFFFFF"
Definition at line 58 of file caja-sidebar-title.c.
MAX_TITLE_SIZE
#define MAX_TITLE_SIZE 256
Definition at line 51 of file caja-sidebar-title.c.
MIN_TITLE_FONT_SIZE
#define MIN_TITLE_FONT_SIZE 12
Definition at line 55 of file caja-sidebar-title.c.
MINIMUM_INFO_WIDTH
#define MINIMUM_INFO_WIDTH 32
Definition at line 52 of file caja-sidebar-title.c.
SIDEBAR_INFO_MARGIN
#define SIDEBAR_INFO_MARGIN 4
Definition at line 53 of file caja-sidebar-title.c.
TITLE_PADDING
#define TITLE_PADDING 4
Definition at line 56 of file caja-sidebar-title.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
LABEL_COLOR
LABEL_COLOR_HIGHLIGHT
LABEL_COLOR_ACTIVE
LABEL_COLOR_PRELIGHT
LABEL_INFO_COLOR
LABEL_INFO_COLOR_HIGHLIGHT
LABEL_INFO_COLOR_ACTIVE
LAST_LABEL_COLOR
Definition at line 72 of file caja-sidebar-title.c.
Function Documentation
caja_sidebar_title_get_text()
char * caja_sidebar_title_get_text (CajaSidebarTitle * sidebar_title)
Definition at line 673 of file caja-sidebar-title.c.
References CajaSidebarTitle::details.
caja_sidebar_title_hit_test_icon()
gboolean caja_sidebar_title_hit_test_icon (CajaSidebarTitle * sidebar_title, int x, int y)
Definition at line 815 of file caja-sidebar-title.c.
References CAJA_IS_SIDEBAR_TITLE, CajaSidebarTitle::details, FALSE, and NULL.
caja_sidebar_title_new()
GtkWidget * caja_sidebar_title_new (void)
Definition at line 226 of file caja-sidebar-title.c.
References caja_sidebar_title_get_type(), and NULL.
caja_sidebar_title_select_text_color()
void caja_sidebar_title_select_text_color (CajaSidebarTitle * sidebar_title, EelBackground * background)
Definition at line 238 of file caja-sidebar-title.c.
References CAJA_IS_SIDEBAR_TITLE, DEFAULT_DARK_INFO_COLOR, DEFAULT_LIGHT_INFO_COLOR, eel_background_is_dark(), eel_background_is_set(), eel_gdk_rgba_is_dark(), LABEL_COLOR, LABEL_COLOR_ACTIVE, LABEL_COLOR_HIGHLIGHT, LABEL_COLOR_PRELIGHT, LABEL_INFO_COLOR, LABEL_INFO_COLOR_ACTIVE, LABEL_INFO_COLOR_HIGHLIGHT, and NULL.
caja_sidebar_title_set_file()
void caja_sidebar_title_set_file (CajaSidebarTitle * sidebar_title, CajaFile * file, const char * initial_text)
Definition at line 751 of file caja-sidebar-title.c.
References caja_file_ref(), CajaSidebarTitle::details, FALSE, and NULL.
caja_sidebar_title_set_text()
void caja_sidebar_title_set_text (CajaSidebarTitle * sidebar_title, const char * new_text)
Definition at line 680 of file caja-sidebar-title.c.
References CajaSidebarTitle::details, and MAX_TITLE_SIZE.