MATE Desktop Environment: caja-location-bar.h File Reference
caja-location-bar.h File Reference
#include <gtk/gtk.h>
#include <libcaja-private/caja-entry.h>
#include "caja-navigation-window.h"
#include "caja-navigation-window-pane.h"
Classes
struct CajaLocationBar
struct CajaLocationBarClass
Macros
#define CAJA_TYPE_LOCATION_BAR caja_location_bar_get_type()
#define CAJA_LOCATION_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_LOCATION_BAR, CajaLocationBar))
#define CAJA_LOCATION_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_LOCATION_BAR, CajaLocationBarClass))
#define CAJA_IS_LOCATION_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_LOCATION_BAR))
#define CAJA_IS_LOCATION_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_LOCATION_BAR))
#define CAJA_LOCATION_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_LOCATION_BAR, CajaLocationBarClass))
Typedefs
typedef struct _CajaLocationBarPrivate CajaLocationBarPrivate
typedef struct CajaLocationBar CajaLocationBar
Functions
GType caja_location_bar_get_type (void)
GtkWidget * caja_location_bar_new (CajaNavigationWindowPane *pane)
void caja_location_bar_set_active (CajaLocationBar *location_bar, gboolean is_active)
CajaEntry * caja_location_bar_get_entry (CajaLocationBar *location_bar)
void caja_location_bar_activate (CajaLocationBar *bar)
void caja_location_bar_set_location (CajaLocationBar *bar, const char *location)
Macro Definition Documentation
CAJA_IS_LOCATION_BAR
#define CAJA_IS_LOCATION_BAR (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_LOCATION_BAR))
Definition at line 45 of file caja-location-bar.h.
CAJA_IS_LOCATION_BAR_CLASS
#define CAJA_IS_LOCATION_BAR_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_LOCATION_BAR))
Definition at line 47 of file caja-location-bar.h.
CAJA_LOCATION_BAR
#define CAJA_LOCATION_BAR (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_LOCATION_BAR, CajaLocationBar))
Definition at line 41 of file caja-location-bar.h.
CAJA_LOCATION_BAR_CLASS
#define CAJA_LOCATION_BAR_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_LOCATION_BAR, CajaLocationBarClass))
Definition at line 43 of file caja-location-bar.h.
CAJA_LOCATION_BAR_GET_CLASS
#define CAJA_LOCATION_BAR_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_LOCATION_BAR, CajaLocationBarClass))
Definition at line 49 of file caja-location-bar.h.
CAJA_TYPE_LOCATION_BAR
#define CAJA_TYPE_LOCATION_BAR caja_location_bar_get_type()
Definition at line 40 of file caja-location-bar.h.
Typedef Documentation
CajaLocationBar
typedef struct CajaLocationBar CajaLocationBar
CajaLocationBarPrivate
typedef struct _CajaLocationBarPrivate CajaLocationBarPrivate
Definition at line 52 of file caja-location-bar.h.
Function Documentation
caja_location_bar_activate()
void caja_location_bar_activate (CajaLocationBar * bar)
Definition at line 406 of file caja-location-bar.c.
References caja_entry_select_all(), and CajaLocationBar::details.
Referenced by caja_navigation_window_pane_show_navigation_bar_temporarily().
caja_location_bar_get_entry()
CajaEntry * caja_location_bar_get_entry (CajaLocationBar * location_bar)
Definition at line 657 of file caja-location-bar.c.
References CajaLocationBar::details.
Referenced by caja_navigation_window_pane_setup().
caja_location_bar_get_type()
GType caja_location_bar_get_type (void)
caja_location_bar_new()
GtkWidget * caja_location_bar_new (CajaNavigationWindowPane * pane)
Definition at line 541 of file caja-location-bar.c.
References caja_clipboard_set_up_editable(), CAJA_LOCATION_BAR, CAJA_TYPE_LOCATION_BAR, CAJA_WINDOW, caja_window_get_ui_manager(), CAJA_WINDOW_PANE, CajaLocationBar::details, NULL, and TRUE.
Referenced by caja_navigation_window_pane_setup().
caja_location_bar_set_active()
void caja_location_bar_set_active (CajaLocationBar * location_bar, gboolean is_active)
Definition at line 618 of file caja-location-bar.c.
References CajaLocationBar::details, and NULL.
Referenced by G_DEFINE_TYPE().
caja_location_bar_set_location()
void caja_location_bar_set_location (CajaLocationBar * bar, const char * location)
Definition at line 559 of file caja-location-bar.c.
References CAJA_LOCATION_ENTRY, caja_location_entry_set_special_text(), caja_location_entry_update_current_location(), CajaLocationBar::details, eel_uri_is_search(), and NULL.