MATE Desktop Environment: caja-navigation-window-menus.c File Reference
caja-navigation-window-menus.c File Reference
#include <config.h>
#include <locale.h>
#include <libxml/parser.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <eel/eel-glib-extensions.h>
#include <eel/eel-mate-extensions.h>
#include <eel/eel-stock-dialogs.h>
#include <eel/eel-string.h>
#include <libcaja-private/caja-file-utilities.h>
#include <libcaja-private/caja-global-preferences.h>
#include <libcaja-private/caja-ui-utilities.h>
#include <libcaja-private/caja-search-engine.h>
#include <libcaja-private/caja-signaller.h>
#include "caja-actions.h"
#include "caja-notebook.h"
#include "caja-navigation-action.h"
#include "caja-zoom-action.h"
#include "caja-view-as-action.h"
#include "caja-application.h"
#include "caja-bookmark-list.h"
#include "caja-bookmarks-window.h"
#include "caja-file-management-properties.h"
#include "caja-property-browser.h"
#include "caja-window-manage-views.h"
#include "caja-window-private.h"
#include "caja-window-bookmarks.h"
#include "caja-navigation-window-pane.h"
Macros
#define MENU_PATH_HISTORY_PLACEHOLDER "/MenuBar/Other Menus/Go/History Placeholder"
#define RESPONSE_FORGET 1000
#define MENU_ITEM_MAX_WIDTH_CHARS 32
Functions
void caja_navigation_window_update_show_hide_menu_items (CajaNavigationWindow *window)
void caja_navigation_window_update_spatial_menu_item (CajaNavigationWindow *window)
void caja_navigation_window_remove_go_menu_callback (CajaNavigationWindow *window)
void caja_navigation_window_remove_go_menu_items (CajaNavigationWindow *window)
void caja_navigation_window_update_split_view_actions_sensitivity (CajaNavigationWindow *window)
void caja_navigation_window_initialize_actions (CajaNavigationWindow *window)
void caja_navigation_window_initialize_menus (CajaNavigationWindow *window)
Macro Definition Documentation
MENU_ITEM_MAX_WIDTH_CHARS
#define MENU_ITEM_MAX_WIDTH_CHARS 32
Definition at line 64 of file caja-navigation-window-menus.c.
MENU_PATH_HISTORY_PLACEHOLDER
#define MENU_PATH_HISTORY_PLACEHOLDER "/MenuBar/Other Menus/Go/History Placeholder"
Definition at line 61 of file caja-navigation-window-menus.c.
RESPONSE_FORGET
#define RESPONSE_FORGET 1000
Definition at line 63 of file caja-navigation-window-menus.c.
Function Documentation
caja_navigation_window_initialize_actions()
void caja_navigation_window_initialize_actions (CajaNavigationWindow * window)
Definition at line 942 of file caja-navigation-window-menus.c.
References _, action, CAJA_ACTION_SEARCH, CAJA_NAVIGATION_DIRECTION_BACK, CAJA_NAVIGATION_DIRECTION_FORWARD, caja_navigation_window_update_split_view_actions_sensitivity(), CAJA_TYPE_NAVIGATION_ACTION, CAJA_TYPE_VIEW_AS_ACTION, CAJA_TYPE_ZOOM_ACTION, CAJA_WINDOW, caja_window_get_ui_manager(), _CajaNavigationWindow::details, FALSE, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, _CajaNavigationWindowPrivate::navigation_action_group, NULL, and TRUE.
caja_navigation_window_initialize_menus()
void caja_navigation_window_initialize_menus (CajaNavigationWindow * window)
caja_window_initialize_menus
Create and install the set of menus for this window. @window: A recently-created CajaWindow.
Definition at line 1071 of file caja-navigation-window-menus.c.
References caja_navigation_window_update_show_hide_menu_items(), caja_navigation_window_update_spatial_menu_item(), caja_ui_string_get(), CAJA_WINDOW, caja_window_get_ui_manager(), and NULL.
caja_navigation_window_remove_go_menu_callback()
void caja_navigation_window_remove_go_menu_callback (CajaNavigationWindow * window)
Definition at line 381 of file caja-navigation-window-menus.c.
References _CajaNavigationWindow::details, and _CajaNavigationWindowPrivate::refresh_go_menu_idle_id.
caja_navigation_window_remove_go_menu_items()
void caja_navigation_window_remove_go_menu_items (CajaNavigationWindow * window)
Definition at line 391 of file caja-navigation-window-menus.c.
References CAJA_WINDOW, caja_window_get_ui_manager(), _CajaNavigationWindow::details, _CajaNavigationWindowPrivate::go_menu_action_group, _CajaNavigationWindowPrivate::go_menu_merge_id, and NULL.
caja_navigation_window_update_show_hide_menu_items()
void caja_navigation_window_update_show_hide_menu_items (CajaNavigationWindow * window)
Definition at line 317 of file caja-navigation-window-menus.c.
References action, CAJA_ACTION_SHOW_HIDE_EXTRA_PANE, CAJA_ACTION_SHOW_HIDE_LOCATION_BAR, CAJA_ACTION_SHOW_HIDE_SIDEBAR, CAJA_ACTION_SHOW_HIDE_STATUSBAR, CAJA_ACTION_SHOW_HIDE_TOOLBAR, CAJA_IS_NAVIGATION_WINDOW, CAJA_NAVIGATION_WINDOW_PANE, caja_navigation_window_pane_location_bar_showing(), caja_navigation_window_sidebar_showing(), caja_navigation_window_split_view_showing(), caja_navigation_window_status_bar_showing(), caja_navigation_window_toolbar_showing(), CAJA_WINDOW, _CajaNavigationWindow::details, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, and _CajaNavigationWindowPrivate::navigation_action_group.
Referenced by caja_navigation_window_hide_sidebar(), caja_navigation_window_hide_status_bar(), caja_navigation_window_hide_toolbar(), caja_navigation_window_initialize_menus(), caja_navigation_window_pane_hide_location_bar(), caja_navigation_window_pane_show_location_bar(), caja_navigation_window_show_sidebar(), caja_navigation_window_show_status_bar(), caja_navigation_window_show_toolbar(), caja_navigation_window_split_view_off(), and caja_window_pane_slot_close().
caja_navigation_window_update_spatial_menu_item()
void caja_navigation_window_update_spatial_menu_item (CajaNavigationWindow * window)
Definition at line 352 of file caja-navigation-window-menus.c.
References action, CAJA_ACTION_FOLDER_WINDOW, CAJA_IS_NAVIGATION_WINDOW, caja_preferences, CAJA_PREFERENCES_ALWAYS_USE_BROWSER, _CajaNavigationWindow::details, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, and _CajaNavigationWindowPrivate::navigation_action_group.
Referenced by caja_navigation_window_initialize_menus().
caja_navigation_window_update_split_view_actions_sensitivity()
void caja_navigation_window_update_split_view_actions_sensitivity (CajaNavigationWindow * window)
Definition at line 542 of file caja-navigation-window-menus.c.
References action, _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CAJA_IS_NAVIGATION_WINDOW, CAJA_WINDOW, caja_window_get_next_pane(), caja_window_slot_get_location(), _CajaNavigationWindow::details, CajaWindow::details, FALSE, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, _CajaNavigationWindowPrivate::navigation_action_group, NULL, and _CajaWindowPrivate::panes.
Referenced by caja_navigation_window_initialize_actions(), and caja_navigation_window_split_view_off().