MATE Desktop Environment: caja-thumbnails.c File Reference
caja-thumbnails.c File Reference
#include <config.h>
#include <math.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <signal.h>
#include <gtk/gtk.h>
#include <sys/wait.h>
#include <libmate-desktop/mate-desktop-thumbnail.h>
#include <eel/eel-gdk-pixbuf-extensions.h>
#include <eel/eel-graphic-effects.h>
#include <eel/eel-string.h>
#include <eel/eel-debug.h>
#include <eel/eel-vfs-extensions.h>
#include "caja-thumbnails.h"
#include "caja-directory-notify.h"
#include "caja-global-preferences.h"
#include "caja-file-utilities.h"
#include "caja-file-private.h"
Macros
#define MATE_DESKTOP_USE_UNSTABLE_API
#define INVALID_MTIME 0
#define THUMBNAIL_CREATION_DELAY_SECS 3
Functions
void caja_thumbnail_remove_from_queue (const char *file_uri)
void caja_thumbnail_prioritize (const char *file_uri)
gboolean caja_can_thumbnail_internally (CajaFile *file)
gboolean caja_thumbnail_is_mimetype_limited_by_size (const char *mime_type)
gboolean caja_can_thumbnail (CajaFile *file)
void caja_create_thumbnail (CajaFile *file)
Macro Definition Documentation
INVALID_MTIME
#define INVALID_MTIME 0
Definition at line 58 of file caja-thumbnails.c.
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 37 of file caja-thumbnails.c.
THUMBNAIL_CREATION_DELAY_SECS
#define THUMBNAIL_CREATION_DELAY_SECS 3
Definition at line 61 of file caja-thumbnails.c.
Function Documentation
caja_can_thumbnail()
gboolean caja_can_thumbnail (CajaFile * file)
Definition at line 360 of file caja-thumbnails.c.
References caja_file_get_mime_type(), caja_file_get_mtime(), caja_file_get_uri(), mate_desktop_thumbnail_factory_can_thumbnail(), and mime_type.
Referenced by caja_file_get_icon().
caja_can_thumbnail_internally()
gboolean caja_can_thumbnail_internally (CajaFile * file)
Definition at line 342 of file caja-thumbnails.c.
References caja_file_get_mime_type(), and mime_type.
Referenced by caja_file_get_icon().
caja_create_thumbnail()
void caja_create_thumbnail (CajaFile * file)
Definition at line 384 of file caja-thumbnails.c.
References caja_file_get_mime_type(), caja_file_get_uri(), caja_file_set_is_thumbnailing(), CajaFile::details, FALSE, _CajaFilePrivate::file_info_is_up_to_date, _CajaFilePrivate::got_file_info, _CajaFilePrivate::mtime, NULL, and TRUE.
Referenced by caja_file_get_icon().
caja_thumbnail_is_mimetype_limited_by_size()
gboolean caja_thumbnail_is_mimetype_limited_by_size (const char * mime_type)
Definition at line 354 of file caja-thumbnails.c.
References mime_type.
Referenced by caja_file_should_show_thumbnail().
caja_thumbnail_prioritize()
void caja_thumbnail_prioritize (const char * file_uri)
Definition at line 226 of file caja-thumbnails.c.
caja_thumbnail_remove_from_queue()
void caja_thumbnail_remove_from_queue (const char * file_uri)
Definition at line 190 of file caja-thumbnails.c.