MATE Desktop Environment: caja-location-entry.h File Reference
caja-location-entry.h File Reference
#include <libcaja-private/caja-entry.h>
Classes
struct CajaLocationEntry
struct CajaLocationEntryClass
Macros
#define CAJA_TYPE_LOCATION_ENTRY caja_location_entry_get_type()
#define CAJA_LOCATION_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_LOCATION_ENTRY, CajaLocationEntry))
#define CAJA_LOCATION_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_LOCATION_ENTRY, CajaLocationEntryClass))
#define CAJA_IS_LOCATION_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_LOCATION_ENTRY))
#define CAJA_IS_LOCATION_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_LOCATION_ENTRY))
#define CAJA_LOCATION_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_LOCATION_ENTRY, CajaLocationEntryClass))
Typedefs
typedef struct CajaLocationEntryDetails CajaLocationEntryDetails
typedef struct CajaLocationEntry CajaLocationEntry
Enumerations
enum CajaLocationEntryAction { CAJA_LOCATION_ENTRY_ACTION_GOTO , CAJA_LOCATION_ENTRY_ACTION_CLEAR }
Functions
GType caja_location_entry_get_type (void)
GtkWidget * caja_location_entry_new (void)
void caja_location_entry_set_special_text (CajaLocationEntry *entry, const char *special_text)
void caja_location_entry_set_secondary_action (CajaLocationEntry *entry, CajaLocationEntryAction secondary_action)
void caja_location_entry_update_current_location (CajaLocationEntry *entry, const char *path)
Macro Definition Documentation
CAJA_IS_LOCATION_ENTRY
#define CAJA_IS_LOCATION_ENTRY (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_LOCATION_ENTRY))
Definition at line 37 of file caja-location-entry.h.
CAJA_IS_LOCATION_ENTRY_CLASS
#define CAJA_IS_LOCATION_ENTRY_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_LOCATION_ENTRY))
Definition at line 39 of file caja-location-entry.h.
CAJA_LOCATION_ENTRY
#define CAJA_LOCATION_ENTRY (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_LOCATION_ENTRY, CajaLocationEntry))
Definition at line 33 of file caja-location-entry.h.
CAJA_LOCATION_ENTRY_CLASS
#define CAJA_LOCATION_ENTRY_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_LOCATION_ENTRY, CajaLocationEntryClass))
Definition at line 35 of file caja-location-entry.h.
CAJA_LOCATION_ENTRY_GET_CLASS
#define CAJA_LOCATION_ENTRY_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_LOCATION_ENTRY, CajaLocationEntryClass))
Definition at line 41 of file caja-location-entry.h.
CAJA_TYPE_LOCATION_ENTRY
#define CAJA_TYPE_LOCATION_ENTRY caja_location_entry_get_type()
Definition at line 32 of file caja-location-entry.h.
Typedef Documentation
CajaLocationEntry
typedef struct CajaLocationEntry CajaLocationEntry
CajaLocationEntryDetails
typedef struct CajaLocationEntryDetails CajaLocationEntryDetails
Definition at line 44 of file caja-location-entry.h.
Enumeration Type Documentation
CajaLocationEntryAction
enum CajaLocationEntryAction
Enumerator
CAJA_LOCATION_ENTRY_ACTION_GOTO
CAJA_LOCATION_ENTRY_ACTION_CLEAR
Definition at line 57 of file caja-location-entry.h.
Function Documentation
caja_location_entry_get_type()
GType caja_location_entry_get_type (void)
caja_location_entry_new()
GtkWidget * caja_location_entry_new (void)
Definition at line 470 of file caja-location-entry.c.
References CAJA_TYPE_LOCATION_ENTRY, and NULL.
caja_location_entry_set_secondary_action()
void caja_location_entry_set_secondary_action (CajaLocationEntry * entry, CajaLocationEntryAction secondary_action)
Definition at line 413 of file caja-location-entry.c.
References CAJA_LOCATION_ENTRY_ACTION_CLEAR, CAJA_LOCATION_ENTRY_ACTION_GOTO, and CajaLocationEntry::details.
caja_location_entry_set_special_text()
void caja_location_entry_set_special_text (CajaLocationEntry * entry, const char * special_text)
Definition at line 480 of file caja-location-entry.c.
References CajaLocationEntry::details, FALSE, and TRUE.
Referenced by caja_location_bar_set_location().
caja_location_entry_update_current_location()
void caja_location_entry_update_current_location (CajaLocationEntry * entry, const char * path)
Definition at line 402 of file caja-location-entry.c.
References CAJA_ENTRY, caja_entry_set_text(), and CajaLocationEntry::details.
Referenced by caja_location_bar_set_location(), caja_location_dialog_new(), and caja_location_dialog_set_location().