MATE Desktop Environment: caja-emblem-utils.c File Reference
caja-emblem-utils.c File Reference
#include <config.h>
#include <sys/types.h>
#include <utime.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <sys/stat.h>
#include <glib.h>
#include <glib/gstdio.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <eel/eel-gdk-pixbuf-extensions.h>
#include <eel/eel-stock-dialogs.h>
#include "caja-file.h"
#include "caja-emblem-utils.h"
Macros
#define EMBLEM_NAME_TRASH "emblem-trash"
#define EMBLEM_NAME_SYMLINK "emblem-symbolic-link"
#define EMBLEM_NAME_NOREAD "emblem-noread"
#define EMBLEM_NAME_NOWRITE "emblem-nowrite"
#define EMBLEM_NAME_NOTE "emblem-note"
#define EMBLEM_NAME_SHARED "emblem-shared"
Functions
GList * caja_emblem_list_available (void)
void caja_emblem_refresh_list (void)
char * caja_emblem_get_icon_name_from_keyword (const char *keyword)
gboolean caja_emblem_should_show_in_list (const char *emblem)
char * caja_emblem_get_keyword_from_icon_name (const char *emblem)
GdkPixbuf * caja_emblem_load_pixbuf_for_emblem (GFile *emblem)
gboolean caja_emblem_verify_keyword (GtkWindow *parent_window, const char *keyword, const char *display_name)
void caja_emblem_install_custom_emblem (GdkPixbuf *pixbuf, const char *keyword, const char *display_name, GtkWindow *parent_window)
gboolean caja_emblem_can_remove_emblem (const char *keyword)
gboolean caja_emblem_can_rename_emblem (const char *keyword)
gboolean caja_emblem_remove_emblem (const char *keyword)
gboolean caja_emblem_rename_emblem (const char *keyword, const char *name)
char * caja_emblem_create_unique_keyword (const char *base)
Macro Definition Documentation
EMBLEM_NAME_NOREAD
#define EMBLEM_NAME_NOREAD "emblem-noread"
Definition at line 48 of file caja-emblem-utils.c.
EMBLEM_NAME_NOTE
#define EMBLEM_NAME_NOTE "emblem-note"
Definition at line 50 of file caja-emblem-utils.c.
EMBLEM_NAME_NOWRITE
#define EMBLEM_NAME_NOWRITE "emblem-nowrite"
Definition at line 49 of file caja-emblem-utils.c.
EMBLEM_NAME_SHARED
#define EMBLEM_NAME_SHARED "emblem-shared"
Definition at line 51 of file caja-emblem-utils.c.
EMBLEM_NAME_SYMLINK
#define EMBLEM_NAME_SYMLINK "emblem-symbolic-link"
Definition at line 47 of file caja-emblem-utils.c.
EMBLEM_NAME_TRASH
#define EMBLEM_NAME_TRASH "emblem-trash"
Definition at line 46 of file caja-emblem-utils.c.
Function Documentation
caja_emblem_can_remove_emblem()
gboolean caja_emblem_can_remove_emblem (const char * keyword)
Definition at line 350 of file caja-emblem-utils.c.
References FALSE, and TRUE.
caja_emblem_can_rename_emblem()
gboolean caja_emblem_can_rename_emblem (const char * keyword)
Definition at line 369 of file caja-emblem-utils.c.
References FALSE, and TRUE.
caja_emblem_create_unique_keyword()
char * caja_emblem_create_unique_keyword (const char * base)
Definition at line 491 of file caja-emblem-utils.c.
References NULL.
caja_emblem_get_icon_name_from_keyword()
char * caja_emblem_get_icon_name_from_keyword (const char * keyword)
Definition at line 74 of file caja-emblem-utils.c.
References NULL.
Referenced by caja_emblem_rename_emblem().
caja_emblem_get_keyword_from_icon_name()
char * caja_emblem_get_keyword_from_icon_name (const char * emblem)
Definition at line 158 of file caja-emblem-utils.c.
References NULL.
caja_emblem_install_custom_emblem()
void caja_emblem_install_custom_emblem (GdkPixbuf * pixbuf, const char * keyword, const char * display_name, GtkWindow * parent_window)
Definition at line 257 of file caja-emblem-utils.c.
References _, caja_emblem_verify_keyword(), eel_gdk_pixbuf_save_to_file(), eel_show_error_dialog(), NULL, and TRUE.
caja_emblem_list_available()
GList * caja_emblem_list_available (void)
Definition at line 54 of file caja-emblem-utils.c.
caja_emblem_load_pixbuf_for_emblem()
GdkPixbuf * caja_emblem_load_pixbuf_for_emblem (GFile * emblem)
Definition at line 173 of file caja-emblem-utils.c.
References CAJA_ICON_SIZE_STANDARD, eel_gdk_pixbuf_load_from_stream(), eel_gdk_pixbuf_scale_down_to_fit(), and NULL.
caja_emblem_refresh_list()
void caja_emblem_refresh_list (void)
Definition at line 65 of file caja-emblem-utils.c.
caja_emblem_remove_emblem()
gboolean caja_emblem_remove_emblem (const char * keyword)
Definition at line 389 of file caja-emblem-utils.c.
References FALSE, NULL, and TRUE.
caja_emblem_rename_emblem()
gboolean caja_emblem_rename_emblem (const char * keyword, const char * name)
Definition at line 442 of file caja-emblem-utils.c.
References caja_emblem_get_icon_name_from_keyword(), caja_icon_info_clear_caches(), FALSE, name, NULL, and TRUE.
caja_emblem_should_show_in_list()
gboolean caja_emblem_should_show_in_list (const char * emblem)
Definition at line 127 of file caja-emblem-utils.c.
References EMBLEM_NAME_NOREAD, EMBLEM_NAME_NOTE, EMBLEM_NAME_NOWRITE, EMBLEM_NAME_SHARED, EMBLEM_NAME_SYMLINK, EMBLEM_NAME_TRASH, FALSE, and TRUE.
caja_emblem_verify_keyword()
gboolean caja_emblem_verify_keyword (GtkWindow * parent_window, const char * keyword, const char * display_name)
Definition at line 220 of file caja-emblem-utils.c.
References _, eel_show_error_dialog(), FALSE, NULL, and TRUE.
Referenced by caja_emblem_install_custom_emblem().