MATE Desktop Environment: caja-file-info.c File Reference
caja-file-info.c File Reference
#include <config.h>
#include "caja-file-info.h"
#include "caja-extension-private.h"
Functions
GList * caja_file_info_list_copy (GList *files)
void caja_file_info_list_free (GList *files)
GType caja_file_info_get_type (void)
gboolean caja_file_info_is_gone (CajaFileInfo *file)
GFileType caja_file_info_get_file_type (CajaFileInfo *file)
char * caja_file_info_get_name (CajaFileInfo *file)
GFile * caja_file_info_get_location (CajaFileInfo *file)
char * caja_file_info_get_uri (CajaFileInfo *file)
char * caja_file_info_get_activation_uri (CajaFileInfo *file)
GFile * caja_file_info_get_parent_location (CajaFileInfo *file)
char * caja_file_info_get_parent_uri (CajaFileInfo *file)
CajaFileInfo * caja_file_info_get_parent_info (CajaFileInfo *file)
GMount * caja_file_info_get_mount (CajaFileInfo *file)
char * caja_file_info_get_uri_scheme (CajaFileInfo *file)
char * caja_file_info_get_mime_type (CajaFileInfo *file)
gboolean caja_file_info_is_mime_type (CajaFileInfo *file, const char *mime_type)
gboolean caja_file_info_is_directory (CajaFileInfo *file)
gboolean caja_file_info_can_write (CajaFileInfo *file)
void caja_file_info_add_emblem (CajaFileInfo *file, const char *emblem_name)
char * caja_file_info_get_string_attribute (CajaFileInfo *file, const char *attribute_name)
void caja_file_info_add_string_attribute (CajaFileInfo *file, const char *attribute_name, const char *value)
void caja_file_info_invalidate_extension_info (CajaFileInfo *file)
CajaFileInfo * caja_file_info_lookup (GFile *location)
CajaFileInfo * caja_file_info_create (GFile *location)
CajaFileInfo * caja_file_info_lookup_for_uri (const char *uri)
CajaFileInfo * caja_file_info_create_for_uri (const char *uri)
Variables
CajaFileInfo *(* caja_file_info_getter)(GFile *location, gboolean create)
Detailed Description
or NULL if
Definition in file caja-file-info.c.
Function Documentation
caja_file_info_add_emblem()
void caja_file_info_add_emblem (CajaFileInfo * file, const char * emblem_name)
Definition at line 278 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, and NULL.
Referenced by caja_dropbox_finish_file_info_command().
caja_file_info_add_string_attribute()
void caja_file_info_add_string_attribute (CajaFileInfo * file, const char * attribute_name, const char * value)
Definition at line 300 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, and NULL.
caja_file_info_can_write()
gboolean caja_file_info_can_write (CajaFileInfo * file)
Definition at line 269 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, FALSE, and NULL.
caja_file_info_create()
CajaFileInfo * caja_file_info_create (GFile * location)
caja_file_info_create: @location: the location to create the file info for
Returns: (transfer full): a CajaFileInfo
Definition at line 341 of file caja-file-info.c.
References caja_file_info_getter, and TRUE.
Referenced by caja_file_info_create_for_uri().
caja_file_info_create_for_uri()
CajaFileInfo * caja_file_info_create_for_uri (const char * uri)
caja_file_info_create_for_uri: @uri: the URI to lookup the file info for
Returns: (transfer full): a CajaFileInfo
Definition at line 372 of file caja-file-info.c.
References caja_file_info_create().
caja_file_info_get_activation_uri()
char * caja_file_info_get_activation_uri (CajaFileInfo * file)
Definition at line 164 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, and NULL.
caja_file_info_get_file_type()
GFileType caja_file_info_get_file_type (CajaFileInfo * file)
Definition at line 122 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, and NULL.
caja_file_info_get_location()
GFile * caja_file_info_get_location (CajaFileInfo * file)
Definition at line 146 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, and NULL.
caja_file_info_get_mime_type()
char * caja_file_info_get_mime_type (CajaFileInfo * file)
Definition at line 239 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, and NULL.
caja_file_info_get_mount()
GMount * caja_file_info_get_mount (CajaFileInfo * file)
Definition at line 221 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, and NULL.
caja_file_info_get_name()
char * caja_file_info_get_name (CajaFileInfo * file)
Definition at line 131 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, and NULL.
caja_file_info_get_parent_info()
CajaFileInfo * caja_file_info_get_parent_info (CajaFileInfo * file)
Definition at line 205 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, and NULL.
caja_file_info_get_parent_location()
GFile * caja_file_info_get_parent_location (CajaFileInfo * file)
Definition at line 180 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, and NULL.
caja_file_info_get_parent_uri()
char * caja_file_info_get_parent_uri (CajaFileInfo * file)
Definition at line 189 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, and NULL.
caja_file_info_get_string_attribute()
char * caja_file_info_get_string_attribute (CajaFileInfo * file, const char * attribute_name)
Definition at line 288 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, and NULL.
caja_file_info_get_type()
GType caja_file_info_get_type (void)
Definition at line 85 of file caja-file-info.c.
References NULL, and type.
caja_file_info_get_uri()
char * caja_file_info_get_uri (CajaFileInfo * file)
Definition at line 155 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, and NULL.
Referenced by fm_ditem_page_make_box().
caja_file_info_get_uri_scheme()
char * caja_file_info_get_uri_scheme (CajaFileInfo * file)
Definition at line 230 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, and NULL.
caja_file_info_invalidate_extension_info()
void caja_file_info_invalidate_extension_info (CajaFileInfo * file)
Definition at line 314 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, and NULL.
caja_file_info_is_directory()
gboolean caja_file_info_is_directory (CajaFileInfo * file)
Definition at line 260 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, FALSE, and NULL.
Referenced by caja_dropbox_finish_file_info_command().
caja_file_info_is_gone()
gboolean caja_file_info_is_gone (CajaFileInfo * file)
Definition at line 113 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, FALSE, and NULL.
caja_file_info_is_mime_type()
gboolean caja_file_info_is_mime_type (CajaFileInfo * file, const char * mime_type)
Definition at line 248 of file caja-file-info.c.
References CAJA_FILE_INFO_GET_IFACE, CAJA_IS_FILE_INFO, FALSE, is_mime_type(), mime_type, and NULL.
Referenced by fm_ditem_page_should_show().
caja_file_info_list_copy()
GList * caja_file_info_list_copy (GList * files)
SECTION:caja-file-info @title: CajaFileInfo @short_description: File interface for caja extensions libcaja-extension/caja-file-info.h
CajaFileInfo provides methods to get and modify information about file objects in the file manager. caja_file_info_list_copy: @files: (element-type CajaFileInfo): the files to copy
Returns: (element-type CajaFileInfo) (transfer full): a copy of @files. Use caja_file_info_list_free to free the list and unref its contents.
Definition at line 46 of file caja-file-info.c.
References NULL.
Referenced by caja_image_converter_get_file_items().
caja_file_info_list_free()
void caja_file_info_list_free (GList * files)
caja_file_info_list_free: @files: (element-type CajaFileInfo): a list created with caja_file_info_list_copy
Definition at line 67 of file caja-file-info.c.
References NULL.
caja_file_info_lookup()
CajaFileInfo * caja_file_info_lookup (GFile * location)
caja_file_info_lookup: @location: the location to lookup the file info for
Returns: (transfer full): a CajaFileInfo
Definition at line 329 of file caja-file-info.c.
References caja_file_info_getter, and FALSE.
Referenced by caja_file_info_lookup_for_uri().
caja_file_info_lookup_for_uri()
CajaFileInfo * caja_file_info_lookup_for_uri (const char * uri)
caja_file_info_lookup_for_uri: @uri: the URI to lookup the file info for
Returns: (transfer full): a CajaFileInfo
Definition at line 353 of file caja-file-info.c.
References caja_file_info_lookup().
Variable Documentation
caja_file_info_getter
CajaFileInfo *(* caja_file_info_getter) (GFile *location, gboolean create) (GFile * location, gboolean create)
Definition at line 26 of file caja-file-info.c.
Referenced by caja_file_info_create(), and caja_file_info_lookup().