MATE Desktop Environment: caja-icon-private.h File Reference
caja-icon-private.h File Reference
#include <eel/eel-glib-extensions.h>
#include "caja-icon-canvas-item.h"
#include "caja-icon-container.h"
#include "caja-icon-dnd.h"
Classes
struct CajaIcon
struct CajaIconRubberbandInfo
struct StretchState
struct CajaIconContainerDetails
Enumerations
enum DragState { DRAG_STATE_INITIAL , DRAG_STATE_MOVE_OR_COPY , DRAG_STATE_STRETCH }
enum Axis { AXIS_NONE , AXIS_HORIZONTAL , AXIS_VERTICAL }
enum {
LABEL_COLOR , LABEL_COLOR_HIGHLIGHT , LABEL_COLOR_ACTIVE , LABEL_COLOR_PRELIGHT ,
LABEL_INFO_COLOR , LABEL_INFO_COLOR_HIGHLIGHT , LABEL_INFO_COLOR_ACTIVE , LAST_LABEL_COLOR
}
Functions
CajaIcon * caja_icon_container_get_icon_by_uri (CajaIconContainer *container, const char *uri)
void caja_icon_container_move_icon (CajaIconContainer *container, CajaIcon *icon, int x, int y, double scale, gboolean raise, gboolean snap, gboolean update_position)
void caja_icon_container_select_list_unselect_others (CajaIconContainer *container, GList *icons)
char * caja_icon_container_get_icon_uri (CajaIconContainer *container, CajaIcon *icon)
char * caja_icon_container_get_icon_drop_target_uri (CajaIconContainer *container, CajaIcon *icon)
void caja_icon_container_update_icon (CajaIconContainer *container, CajaIcon *icon)
gboolean caja_icon_container_has_stored_icon_positions (CajaIconContainer *container)
gboolean caja_icon_container_emit_preview_signal (CajaIconContainer *view, CajaIcon *icon, gboolean start_flag)
gboolean caja_icon_container_scroll (CajaIconContainer *container, int delta_x, int delta_y)
void caja_icon_container_update_scroll_region (CajaIconContainer *container)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
LABEL_COLOR
LABEL_COLOR_HIGHLIGHT
LABEL_COLOR_ACTIVE
LABEL_COLOR_PRELIGHT
LABEL_INFO_COLOR
LABEL_INFO_COLOR_HIGHLIGHT
LABEL_INFO_COLOR_ACTIVE
LAST_LABEL_COLOR
Definition at line 115 of file caja-icon-private.h.
Axis
enum Axis
Enumerator
AXIS_NONE
AXIS_HORIZONTAL
AXIS_VERTICAL
Definition at line 108 of file caja-icon-private.h.
DragState
enum DragState
Enumerator
DRAG_STATE_INITIAL
DRAG_STATE_MOVE_OR_COPY
DRAG_STATE_STRETCH
Definition at line 91 of file caja-icon-private.h.
Function Documentation
caja_icon_container_emit_preview_signal()
gboolean caja_icon_container_emit_preview_signal (CajaIconContainer * view, CajaIcon * icon, gboolean start_flag)
Definition at line 9207 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIcon::data, FALSE, NULL, PREVIEW, and TRUE.
caja_icon_container_get_icon_by_uri()
CajaIcon * caja_icon_container_get_icon_by_uri (CajaIconContainer * container, const char * uri)
caja_icon_container_get_icon_by_uri: @container: An icon container widget. @uri: The uri of an icon to find.
Locate an icon, given the URI. The URI must match exactly. Later we may have to have some way of figuring out if the URI specifies the same object that does not require an exact match.
Definition at line 8369 of file caja-icon-container.c.
References caja_icon_container_get_icon_uri(), CajaIcon::data, CajaIconContainer::details, CajaIconContainerDetails::icons, and NULL.
caja_icon_container_get_icon_drop_target_uri()
char * caja_icon_container_get_icon_drop_target_uri (CajaIconContainer * container, CajaIcon * icon)
Definition at line 8635 of file caja-icon-container.c.
References CajaIcon::data, GET_ICON_DROP_TARGET_URI, and NULL.
caja_icon_container_get_icon_uri()
char * caja_icon_container_get_icon_uri (CajaIconContainer * container, CajaIcon * icon)
Definition at line 8621 of file caja-icon-container.c.
References CajaIcon::data, GET_ICON_URI, and NULL.
Referenced by caja_icon_container_get_icon_by_uri().
caja_icon_container_has_stored_icon_positions()
gboolean caja_icon_container_has_stored_icon_positions (CajaIconContainer * container)
Definition at line 9228 of file caja-icon-container.c.
References CajaIcon::data, CajaIconContainer::details, FALSE, GET_STORED_ICON_POSITION, CajaIconContainerDetails::icons, NULL, and TRUE.
caja_icon_container_move_icon()
void caja_icon_container_move_icon (CajaIconContainer * container, CajaIcon * icon, int x, int y, double scale, gboolean raise, gboolean snap, gboolean update_position)
Definition at line 2617 of file caja-icon-container.c.
References CajaIconContainerDetails::auto_layout, caja_icon_container_is_layout_rtl(), caja_icon_container_update_icon(), CajaIcon::data, CajaIconContainer::details, FALSE, ICON_POSITION_CHANGED, CajaIconContainerDetails::keep_aligned, CajaIconContainerDetails::lock_icons_position, CajaIcon::saved_ltr_x, CajaIconPosition::scale, CajaIcon::scale, TRUE, CajaIconPosition::x, CajaIcon::x, CajaIconPosition::y, and CajaIcon::y.
Referenced by caja_icon_container_unstretch().
caja_icon_container_scroll()
gboolean caja_icon_container_scroll (CajaIconContainer * container, int delta_x, int delta_y)
Definition at line 603 of file caja-icon-container.c.
caja_icon_container_select_list_unselect_others()
void caja_icon_container_select_list_unselect_others (CajaIconContainer * container, GList * selection)
caja_icon_container_select_list_unselect_others. @container: An icon container widget. @selection: A list of CajaIcon *.
Set the selection to exactly the icons in @selection.
Definition at line 8309 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIcon::data, CajaIconContainer::details, FALSE, hash, CajaIconContainerDetails::icons, NULL, and SELECTION_CHANGED.
caja_icon_container_update_icon()
void caja_icon_container_update_icon (CajaIconContainer * container, CajaIcon * icon)
Definition at line 7589 of file caja-icon-container.c.
References caja_icon_canvas_item_get_editable_text(), caja_icon_canvas_item_set_attach_points(), caja_icon_canvas_item_set_embedded_text(), caja_icon_canvas_item_set_embedded_text_rect(), caja_icon_canvas_item_set_emblems(), caja_icon_canvas_item_set_image(), caja_icon_info_get_attach_points(), caja_icon_info_get_embedded_rect(), caja_icon_info_get_pixbuf(), caja_icon_info_get_pixbuf_at_size(), CAJA_ICON_MAXIMUM_SIZE, CajaIcon::data, CajaIconContainer::details, CajaIconContainerDetails::drop_target, EEL_CANVAS, EEL_CANVAS_ITEM, eel_canvas_item_set(), FALSE, CajaIconContainerDetails::forced_icon_size, ICON_SIZE_FOR_LARGE_EMBEDDED_TEXT, CajaIcon::is_monitored, CajaIcon::item, MAX, MAXIMUM_IMAGE_SIZE, MIN, MINIMUM_IMAGE_SIZE, NULL, and TRUE.
Referenced by caja_icon_container_move_icon(), caja_icon_container_request_update(), caja_icon_container_request_update_all(), and caja_icon_container_start_renaming_selected_item().
caja_icon_container_update_scroll_region()
void caja_icon_container_update_scroll_region (CajaIconContainer * container)
Definition at line 1100 of file caja-icon-container.c.
References CajaIconContainerDetails::bottom_margin, BOUNDS_USAGE_FOR_ENTIRE_ITEM, caja_get_icon_size_for_zoom_level(), caja_icon_container_get_is_fixed_size(), caja_icon_container_is_auto_layout(), caja_icon_container_is_empty(), caja_icon_container_is_layout_rtl(), caja_icon_container_is_layout_vertical(), CONTAINER_PAD_BOTTOM, CONTAINER_PAD_LEFT, CONTAINER_PAD_RIGHT, CONTAINER_PAD_TOP, CajaIconContainer::details, EEL_CANVAS, eel_canvas_set_scroll_region(), FALSE, ICON_PAD_BOTTOM, ICON_PAD_LEFT, ICON_PAD_RIGHT, ICON_PAD_TOP, CajaIconContainerDetails::left_margin, MAX, MIN, CajaIconContainerDetails::reset_scroll_region_trigger, CajaIconContainerDetails::right_margin, CajaIconContainerDetails::top_margin, and CajaIconContainerDetails::zoom_level.
Referenced by caja_icon_container_clear().