MATE Desktop Environment: caja-link.c File Reference
caja-link.c File Reference
#include <config.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <eel/eel-vfs-extensions.h>
#include "caja-link.h"
#include "caja-directory-notify.h"
#include "caja-directory.h"
#include "caja-file-utilities.h"
#include "caja-file.h"
#include "caja-program-choosing.h"
#include "caja-icon-names.h"
Macros
#define MAIN_GROUP "Desktop Entry"
#define CAJA_LINK_GENERIC_TAG "Link"
#define CAJA_LINK_TRASH_TAG "X-caja-trash"
#define CAJA_LINK_MOUNT_TAG "FSDevice"
#define CAJA_LINK_HOME_TAG "X-caja-home"
Functions
gboolean caja_link_local_create (const char *directory_uri, const char *base_name, const char *display_name, const char *image, const char *target_uri, const GdkPoint *point, int screen, gboolean unique_filename, GError **error)
gboolean caja_link_local_set_text (const char *uri, const char *text)
gboolean caja_link_local_set_icon (const char *uri, const char *icon)
char * caja_link_local_get_text (const char *path)
char * caja_link_local_get_additional_text (const char *path)
char * caja_link_local_get_link_uri (const char *uri)
void caja_link_get_link_info_given_file_contents (const char *file_contents, int link_file_size, const char *file_uri, char **uri, char **name, char **icon, gboolean *is_launcher, gboolean *is_foreign)
Macro Definition Documentation
CAJA_LINK_GENERIC_TAG
#define CAJA_LINK_GENERIC_TAG "Link"
Definition at line 45 of file caja-link.c.
CAJA_LINK_HOME_TAG
#define CAJA_LINK_HOME_TAG "X-caja-home"
Definition at line 48 of file caja-link.c.
CAJA_LINK_MOUNT_TAG
#define CAJA_LINK_MOUNT_TAG "FSDevice"
Definition at line 47 of file caja-link.c.
CAJA_LINK_TRASH_TAG
#define CAJA_LINK_TRASH_TAG "X-caja-trash"
Definition at line 46 of file caja-link.c.
MAIN_GROUP
#define MAIN_GROUP "Desktop Entry"
Definition at line 43 of file caja-link.c.
Function Documentation
caja_link_get_link_info_given_file_contents()
void caja_link_get_link_info_given_file_contents (const char * file_contents, int link_file_size, const char * file_uri, char ** uri, char ** name, char ** icon, gboolean * is_launcher, gboolean * is_foreign)
Definition at line 587 of file caja-link.c.
References FALSE, MAIN_GROUP, name, NULL, TRUE, and type.
caja_link_local_create()
gboolean caja_link_local_create (const char * directory_uri, const char * base_name, const char * display_name, const char * image, const char * target_uri, const GdkPoint * point, int screen, gboolean unique_filename, GError ** error)
Definition at line 191 of file caja-link.c.
References caja_directory_notify_files_added(), caja_directory_schedule_position_set(), caja_ensure_unique_file_name(), caja_get_desktop_directory_uri(), eel_uri_is_desktop(), eel_uri_is_search(), eel_uri_is_trash(), error, FALSE, item, NULL, and TRUE.
Referenced by fm_directory_view_handle_netscape_url_drop().
caja_link_local_get_additional_text()
char * caja_link_local_get_additional_text (const char * path)
Definition at line 382 of file caja-link.c.
References FALSE, NULL, TRUE, and type.
caja_link_local_get_link_uri()
char * caja_link_local_get_link_uri (const char * uri)
Definition at line 546 of file caja-link.c.
References NULL.
Referenced by caja_file_get_drop_target_uri().
caja_link_local_get_text()
char * caja_link_local_get_text (const char * path)
Definition at line 376 of file caja-link.c.
References TRUE.
Referenced by caja_file_rename().
caja_link_local_set_icon()
gboolean caja_link_local_set_icon (const char * uri, const char * icon)
Definition at line 369 of file caja-link.c.
References FALSE.
caja_link_local_set_text()
gboolean caja_link_local_set_text (const char * uri, const char * text)
Definition at line 362 of file caja-link.c.
References TRUE.
Referenced by caja_file_rename().