MATE Desktop Environment: caja-window-slot.c File Reference
caja-window-slot.c File Reference
#include <eel/eel-gtk-macros.h>
#include <eel/eel-string.h>
#include <libcaja-private/caja-file.h>
#include <libcaja-private/caja-file-utilities.h>
#include <libcaja-private/caja-window-slot-info.h>
#include "caja-window-slot.h"
#include "caja-navigation-window-slot.h"
#include "caja-desktop-window.h"
#include "caja-window-private.h"
#include "caja-window-manage-views.h"
Macros
#define parent_class caja_window_slot_parent_class
Functions
G_DEFINE_TYPE_WITH_CODE (CajaWindowSlot, caja_window_slot, G_TYPE_OBJECT, G_IMPLEMENT_INTERFACE(CAJA_TYPE_WINDOW_SLOT_INFO, caja_window_slot_info_iface_init))
GFile * caja_window_slot_get_location (CajaWindowSlot *slot)
char * caja_window_slot_get_location_uri (CajaWindowSlotInfo *slot)
char * caja_window_slot_get_title (CajaWindowSlot *slot)
void caja_window_slot_update_title (CajaWindowSlot *slot)
void caja_window_slot_update_icon (CajaWindowSlot *slot)
void caja_window_slot_is_in_active_pane (CajaWindowSlot *slot, gboolean is_active)
void caja_window_slot_connect_content_view (CajaWindowSlot *slot, CajaView *view)
void caja_window_slot_disconnect_content_view (CajaWindowSlot *slot, CajaView *view)
void caja_window_slot_set_content_view_widget (CajaWindowSlot *slot, CajaView *new_view)
void caja_window_slot_set_allow_stop (CajaWindowSlot *slot, gboolean allow)
void caja_window_slot_set_status (CajaWindowSlot *slot, const char *status)
void caja_window_slot_update_query_editor (CajaWindowSlot *slot)
void caja_window_slot_remove_extra_location_widgets (CajaWindowSlot *slot)
void caja_window_slot_add_extra_location_widget (CajaWindowSlot *slot, GtkWidget *widget)
void caja_window_slot_add_current_location_to_history_list (CajaWindowSlot *slot)
Macro Definition Documentation
parent_class
#define parent_class caja_window_slot_parent_class
Function Documentation
caja_window_slot_add_current_location_to_history_list()
void caja_window_slot_add_current_location_to_history_list (CajaWindowSlot * slot)
Definition at line 591 of file caja-window-slot.c.
References caja_add_bookmark_to_history_list(), CAJA_IS_DESKTOP_WINDOW, caja_send_history_list_changed(), CajaWindowSlot::current_location_bookmark, NULL, CajaWindowSlot::pane, and _CajaWindowPane::window.
Referenced by caja_forget_history().
caja_window_slot_add_extra_location_widget()
void caja_window_slot_add_extra_location_widget (CajaWindowSlot * slot, GtkWidget * widget)
Definition at line 582 of file caja-window-slot.c.
References CajaWindowSlot::extra_location_frame, CajaWindowSlot::extra_location_widgets, and TRUE.
caja_window_slot_connect_content_view()
void caja_window_slot_connect_content_view (CajaWindowSlot * slot, CajaView * view)
Definition at line 446 of file caja-window-slot.c.
References caja_window_connect_content_view(), caja_window_get_active_slot(), NULL, CajaWindowSlot::pane, and _CajaWindowPane::window.
Referenced by caja_window_set_active_slot(), and caja_window_slot_set_content_view_widget().
caja_window_slot_disconnect_content_view()
void caja_window_slot_disconnect_content_view (CajaWindowSlot * slot, CajaView * view)
Definition at line 459 of file caja-window-slot.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, caja_window_disconnect_content_view(), CajaWindow::details, NULL, CajaWindowSlot::pane, and _CajaWindowPane::window.
Referenced by caja_window_manage_views_close_slot(), caja_window_report_view_failed(), caja_window_set_active_slot(), and caja_window_slot_set_content_view_widget().
caja_window_slot_get_location()
GFile * caja_window_slot_get_location (CajaWindowSlot * slot)
Definition at line 234 of file caja-window-slot.c.
References CAJA_IS_WINDOW, CajaWindowSlot::location, NULL, CajaWindowSlot::pane, and _CajaWindowPane::window.
Referenced by caja_navigation_window_back_or_forward(), caja_navigation_window_split_view_on(), caja_navigation_window_update_split_view_actions_sensitivity(), caja_window_new_tab(), caja_window_new_window(), and caja_window_slot_open_location_full().
caja_window_slot_get_location_uri()
char * caja_window_slot_get_location_uri (CajaWindowSlotInfo * slot)
Definition at line 247 of file caja-window-slot.c.
References CAJA_IS_WINDOW_SLOT, CajaWindowSlot::location, and NULL.
Referenced by caja_window_slot_open_location_full(), and caja_window_slot_set_content_view().
caja_window_slot_get_title()
char * caja_window_slot_get_title (CajaWindowSlot * slot)
Definition at line 268 of file caja-window-slot.c.
References caja_compute_title_for_location(), CAJA_IS_WINDOW_SLOT, caja_view_get_title(), CajaWindowSlot::content_view, CajaWindowSlot::location, CajaWindowSlot::new_content_view, and NULL.
Referenced by caja_window_slot_update_title().
caja_window_slot_is_in_active_pane()
void caja_window_slot_is_in_active_pane (CajaWindowSlot * slot, gboolean is_active)
Definition at line 424 of file caja-window-slot.c.
References caja_view_set_is_active(), CajaWindowSlot::content_view, CajaWindowSlot::new_content_view, and NULL.
Referenced by caja_window_pane_set_active().
caja_window_slot_remove_extra_location_widgets()
void caja_window_slot_remove_extra_location_widgets (CajaWindowSlot * slot)
Definition at line 573 of file caja-window-slot.c.
References CajaWindowSlot::extra_location_frame, and CajaWindowSlot::extra_location_widgets.
caja_window_slot_set_allow_stop()
void caja_window_slot_set_allow_stop (CajaWindowSlot * slot, gboolean allow)
Definition at line 509 of file caja-window-slot.c.
References CajaWindowSlot::allow_stop, CAJA_IS_WINDOW_SLOT, CAJA_WINDOW, caja_window_sync_allow_stop(), CajaWindowSlot::pane, and _CajaWindowPane::window.
Referenced by caja_window_report_load_underway(), and caja_window_slot_set_content_view().
caja_window_slot_set_content_view_widget()
void caja_window_slot_set_content_view_widget (CajaWindowSlot * slot, CajaView * new_view)
Definition at line 472 of file caja-window-slot.c.
References CAJA_IS_WINDOW, caja_view_get_widget(), caja_window_slot_connect_content_view(), caja_window_slot_disconnect_content_view(), CajaWindowSlot::content_view, NULL, CajaWindowSlot::pane, TRUE, CajaWindowSlot::view_box, and _CajaWindowPane::window.
Referenced by caja_window_report_view_failed().
caja_window_slot_set_status()
void caja_window_slot_set_status (CajaWindowSlot * slot, const char * status)
Definition at line 523 of file caja-window-slot.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CAJA_IS_WINDOW_SLOT, CAJA_WINDOW, caja_window_sync_status(), CajaWindow::details, CajaWindowSlot::pane, CajaWindowSlot::status_text, and _CajaWindowPane::window.
caja_window_slot_update_icon()
void caja_window_slot_update_icon (CajaWindowSlot * slot)
Definition at line 366 of file caja-window-slot.c.
References _CajaWindowPane::active_slot, caja_icon_info_get_pixbuf_nodefault(), caja_icon_info_get_used_name(), CAJA_IS_WINDOW, CAJA_WINDOW_CLASS, EEL_CALL_METHOD_WITH_RETURN_VALUE, NULL, CajaWindowSlot::pane, and _CajaWindowPane::window.
Referenced by caja_window_show_window().
caja_window_slot_update_query_editor()
void caja_window_slot_update_query_editor (CajaWindowSlot * slot)
Definition at line 548 of file caja-window-slot.c.
References CAJA_WINDOW_SLOT_CLASS, eel_add_weak_pointer(), EEL_CALL_METHOD, NULL, and CajaWindowSlot::query_editor.
caja_window_slot_update_title()
void caja_window_slot_update_title (CajaWindowSlot * slot)
Definition at line 350 of file caja-window-slot.c.
References caja_window_slot_get_title().
Referenced by caja_window_show_window().
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (CajaWindowSlot , caja_window_slot , G_TYPE_OBJECT , G_IMPLEMENT_INTERFACE(CAJA_TYPE_WINDOW_SLOT_INFO, caja_window_slot_info_iface_init))
Definition at line 42 of file caja-window-slot.c.
References caja_directory_get_for_file(), caja_directory_unref(), CAJA_IS_SEARCH_DIRECTORY, CAJA_SEARCH_DIRECTORY, caja_search_directory_set_query(), caja_window_slot_reload(), and CajaWindowSlot::viewed_file.