MATE Desktop Environment: caja-query-editor.c File Reference
caja-query-editor.c File Reference
#include <config.h>
#include <string.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <eel/eel-gtk-macros.h>
#include <eel/eel-glib-extensions.h>
#include <eel/eel-stock-dialogs.h>
#include <libcaja-private/caja-global-preferences.h>
#include "caja-query-editor.h"
#include "caja-src-marshal.h"
#include "caja-window-slot.h"
Macros
#define TYPING_TIMEOUT 750
#define MAX_TAGS_ENTRY_LEN 4096
Enumerations
enum {
DURATION_INVALID , DURATION_ONE_HOUR , DURATION_ONE_DAY , DURATION_ONE_WEEK ,
DURATION_ONE_MONTH , DURATION_SIX_MONTHS , DURATION_ONE_YEAR
}
enum CajaQueryEditorRowType {
CAJA_QUERY_EDITOR_ROW_LOCATION , CAJA_QUERY_EDITOR_ROW_TYPE , CAJA_QUERY_EDITOR_ROW_TAGS , CAJA_QUERY_EDITOR_ROW_TIME_MODIFIED ,
CAJA_QUERY_EDITOR_ROW_SIZE , CAJA_QUERY_EDITOR_ROW_CONTAINED_TEXT , CAJA_QUERY_EDITOR_ROW_LAST
}
enum { CHANGED , CANCEL , LAST_SIGNAL }
Functions
EEL_CLASS_BOILERPLATE (CajaQueryEditor, caja_query_editor, GTK_TYPE_BOX)
void caja_query_editor_set_default_query (CajaQueryEditor *editor)
void caja_query_editor_set_visible (CajaQueryEditor *editor, gboolean visible)
void caja_query_editor_grab_focus (CajaQueryEditor *editor)
CajaQuery * caja_query_editor_get_query (CajaQueryEditor *editor)
void caja_query_editor_clear_query (CajaQueryEditor *editor)
GtkWidget * caja_query_editor_new (gboolean start_hidden, gboolean is_indexed)
GtkWidget * caja_query_editor_new_with_bar (gboolean start_hidden, gboolean is_indexed, gboolean start_attached, CajaSearchBar *bar, CajaWindowSlot *slot)
void caja_query_editor_set_query (CajaQueryEditor *editor, CajaQuery *query)
Variables
struct {
char * name
char * mimetypes [20]
} mime_type_groups []
Macro Definition Documentation
MAX_TAGS_ENTRY_LEN
#define MAX_TAGS_ENTRY_LEN 4096
Definition at line 439 of file caja-query-editor.c.
TYPING_TIMEOUT
#define TYPING_TIMEOUT 750
Definition at line 316 of file caja-query-editor.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DURATION_INVALID
DURATION_ONE_HOUR
DURATION_ONE_DAY
DURATION_ONE_WEEK
DURATION_ONE_MONTH
DURATION_SIX_MONTHS
DURATION_ONE_YEAR
Definition at line 42 of file caja-query-editor.c.
anonymous enum
anonymous enum
Enumerator
CHANGED
CANCEL
LAST_SIGNAL
Definition at line 105 of file caja-query-editor.c.
CajaQueryEditorRowType
enum CajaQueryEditorRowType
Enumerator
CAJA_QUERY_EDITOR_ROW_LOCATION
CAJA_QUERY_EDITOR_ROW_TYPE
CAJA_QUERY_EDITOR_ROW_TAGS
CAJA_QUERY_EDITOR_ROW_TIME_MODIFIED
CAJA_QUERY_EDITOR_ROW_SIZE
CAJA_QUERY_EDITOR_ROW_CONTAINED_TEXT
CAJA_QUERY_EDITOR_ROW_LAST
Definition at line 53 of file caja-query-editor.c.
Function Documentation
caja_query_editor_clear_query()
void caja_query_editor_clear_query (CajaQueryEditor * editor)
Definition at line 1763 of file caja-query-editor.c.
References CajaQueryEditor::details, FALSE, and TRUE.
Referenced by caja_query_editor_set_query().
caja_query_editor_get_query()
CajaQuery * caja_query_editor_get_query (CajaQueryEditor * editor)
Definition at line 1729 of file caja-query-editor.c.
References caja_query_new(), caja_query_set_text(), CajaQueryEditor::details, and NULL.
caja_query_editor_grab_focus()
void caja_query_editor_grab_focus (CajaQueryEditor * editor)
Definition at line 1720 of file caja-query-editor.c.
References CajaQueryEditor::details.
caja_query_editor_new()
GtkWidget * caja_query_editor_new (gboolean start_hidden, gboolean is_indexed)
Definition at line 1775 of file caja-query-editor.c.
References CAJA_QUERY_EDITOR, caja_query_editor_set_visible(), CAJA_TYPE_QUERY_EDITOR, and NULL.
caja_query_editor_new_with_bar()
GtkWidget * caja_query_editor_new_with_bar (gboolean start_hidden, gboolean is_indexed, gboolean start_attached, CajaSearchBar * bar, CajaWindowSlot * slot)
Definition at line 1828 of file caja-query-editor.c.
References CAJA_QUERY_EDITOR, caja_query_editor_set_visible(), caja_search_bar_borrow_entry(), CAJA_TYPE_QUERY_EDITOR, CajaQueryEditor::details, eel_add_weak_pointer(), and NULL.
caja_query_editor_set_default_query()
void caja_query_editor_set_default_query (CajaQueryEditor * editor)
Definition at line 1560 of file caja-query-editor.c.
References CAJA_QUERY_EDITOR_ROW_LOCATION, and CajaQueryEditor::details.
caja_query_editor_set_query()
void caja_query_editor_set_query (CajaQueryEditor * editor, CajaQuery * query)
Definition at line 1865 of file caja-query-editor.c.
References caja_query_editor_clear_query(), CAJA_QUERY_EDITOR_ROW_LAST, caja_query_get_text(), CajaQueryEditor::details, FALSE, TRUE, and type.
caja_query_editor_set_visible()
void caja_query_editor_set_visible (CajaQueryEditor * editor, gboolean visible)
Definition at line 1668 of file caja-query-editor.c.
References CajaQueryEditor::details.
Referenced by caja_query_editor_new(), and caja_query_editor_new_with_bar().
EEL_CLASS_BOILERPLATE()
EEL_CLASS_BOILERPLATE (CajaQueryEditor , caja_query_editor , GTK_TYPE_BOX)
Definition at line 213 of file caja-query-editor.c.
References CAJA_QUERY_EDITOR, CajaQueryEditor::details, EEL_CALL_PARENT, and G_OBJECT_CLASS().
Variable Documentation
[struct]
struct { ... } mime_type_groups[]
mimetypes
char* mimetypes[20]
Definition at line 549 of file caja-query-editor.c.
Referenced by na_icontext_check_mimetypes().
name
char* name
Definition at line 548 of file caja-query-editor.c.