MATE Desktop Environment: caja-search-directory-file.h File Reference
caja-search-directory-file.h File Reference
#include "caja-file.h"
Classes
struct CajaSearchDirectoryFile
struct CajaSearchDirectoryFileClass
Macros
#define CAJA_TYPE_SEARCH_DIRECTORY_FILE caja_search_directory_file_get_type()
#define CAJA_SEARCH_DIRECTORY_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_SEARCH_DIRECTORY_FILE, CajaSearchDirectoryFile))
#define CAJA_SEARCH_DIRECTORY_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_SEARCH_DIRECTORY_FILE, CajaSearchDirectoryFileClass))
#define CAJA_IS_SEARCH_DIRECTORY_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_SEARCH_DIRECTORY_FILE))
#define CAJA_IS_SEARCH_DIRECTORY_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_SEARCH_DIRECTORY_FILE))
#define CAJA_SEARCH_DIRECTORY_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_SEARCH_DIRECTORY_FILE, CajaSearchDirectoryFileClass))
Functions
GType caja_search_directory_file_get_type (void)
void caja_search_directory_file_update_display_name (CajaSearchDirectoryFile *search_file)
Macro Definition Documentation
CAJA_IS_SEARCH_DIRECTORY_FILE
#define CAJA_IS_SEARCH_DIRECTORY_FILE (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_SEARCH_DIRECTORY_FILE))
Definition at line 36 of file caja-search-directory-file.h.
CAJA_IS_SEARCH_DIRECTORY_FILE_CLASS
#define CAJA_IS_SEARCH_DIRECTORY_FILE_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_SEARCH_DIRECTORY_FILE))
Definition at line 38 of file caja-search-directory-file.h.
CAJA_SEARCH_DIRECTORY_FILE
#define CAJA_SEARCH_DIRECTORY_FILE (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_SEARCH_DIRECTORY_FILE, CajaSearchDirectoryFile))
Definition at line 32 of file caja-search-directory-file.h.
CAJA_SEARCH_DIRECTORY_FILE_CLASS
#define CAJA_SEARCH_DIRECTORY_FILE_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_SEARCH_DIRECTORY_FILE, CajaSearchDirectoryFileClass))
Definition at line 34 of file caja-search-directory-file.h.
CAJA_SEARCH_DIRECTORY_FILE_GET_CLASS
#define CAJA_SEARCH_DIRECTORY_FILE_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_SEARCH_DIRECTORY_FILE, CajaSearchDirectoryFileClass))
Definition at line 40 of file caja-search-directory-file.h.
CAJA_TYPE_SEARCH_DIRECTORY_FILE
#define CAJA_TYPE_SEARCH_DIRECTORY_FILE caja_search_directory_file_get_type()
Definition at line 31 of file caja-search-directory-file.h.
Function Documentation
caja_search_directory_file_get_type()
GType caja_search_directory_file_get_type (void)
caja_search_directory_file_update_display_name()
void caja_search_directory_file_update_display_name (CajaSearchDirectoryFile * search_file)
Definition at line 176 of file caja-search-directory-file.c.
References _, CAJA_FILE, caja_file_emit_changed(), caja_file_set_display_name(), caja_query_to_readable_string(), CAJA_SEARCH_DIRECTORY, caja_search_directory_get_query(), CajaFile::details, _CajaFilePrivate::directory, NULL, and TRUE.
Referenced by caja_search_directory_set_query().