MATE Desktop Environment: caja-window-toolbars.c File Reference
caja-window-toolbars.c File Reference
#include <config.h>
#include <unistd.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <glib/gi18n.h>
#include <eel/eel-mate-extensions.h>
#include <eel/eel-gtk-extensions.h>
#include <eel/eel-string.h>
#include <libcaja-extension/caja-menu-provider.h>
#include <libcaja-private/caja-bookmark.h>
#include <libcaja-private/caja-extensions.h>
#include <libcaja-private/caja-file-utilities.h>
#include <libcaja-private/caja-ui-utilities.h>
#include <libcaja-private/caja-global-preferences.h>
#include <libcaja-private/caja-module.h>
#include "caja-application.h"
#include "caja-window-manage-views.h"
#include "caja-window-private.h"
#include "caja-window.h"
#include "caja-desktop-window.h"
Macros
#define TOOLBAR_PATH_EXTENSION_ACTIONS "/Toolbar/Extra Buttons Placeholder/Extension Actions"
Functions
void caja_navigation_window_set_spinner_active (CajaNavigationWindow *window, gboolean allow)
void caja_navigation_window_activate_spinner (CajaNavigationWindow *window)
void caja_navigation_window_initialize_toolbars (CajaNavigationWindow *window)
void caja_navigation_window_load_extension_toolbar_items (CajaNavigationWindow *window)
Macro Definition Documentation
TOOLBAR_PATH_EXTENSION_ACTIONS
#define TOOLBAR_PATH_EXTENSION_ACTIONS "/Toolbar/Extra Buttons Placeholder/Extension Actions"
Definition at line 59 of file caja-window-toolbars.c.
Function Documentation
caja_navigation_window_activate_spinner()
void caja_navigation_window_activate_spinner (CajaNavigationWindow * window)
Definition at line 80 of file caja-window-toolbars.c.
References _CajaNavigationWindow::details, item, NULL, _CajaNavigationWindowPrivate::spinner, _CajaNavigationWindowPrivate::toolbar, and TRUE.
Referenced by caja_navigation_window_initialize_toolbars().
caja_navigation_window_initialize_toolbars()
void caja_navigation_window_initialize_toolbars (CajaNavigationWindow * window)
Definition at line 110 of file caja-window-toolbars.c.
References caja_navigation_window_activate_spinner().
caja_navigation_window_load_extension_toolbar_items()
void caja_navigation_window_load_extension_toolbar_items (CajaNavigationWindow * window)
Definition at line 147 of file caja-window-toolbars.c.
References action, CAJA_MENU_ITEM, caja_toolbar_action_from_menu_item(), CAJA_WINDOW, caja_window_get_ui_manager(), _CajaNavigationWindow::details, _CajaNavigationWindowPrivate::extensions_toolbar_action_group, _CajaNavigationWindowPrivate::extensions_toolbar_merge_id, FALSE, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, item, NULL, and TOOLBAR_PATH_EXTENSION_ACTIONS.
caja_navigation_window_set_spinner_active()
void caja_navigation_window_set_spinner_active (CajaNavigationWindow * window, gboolean allow)
Definition at line 62 of file caja-window-toolbars.c.
References _CajaNavigationWindow::details, _CajaNavigationWindowPrivate::spinner, and _CajaNavigationWindowPrivate::spinner_active.