MATE Desktop Environment: caja-clipboard.h File Reference
caja-clipboard.h File Reference
#include <gtk/gtk.h>
Functions
void caja_clipboard_set_up_editable (GtkEditable *target, GtkUIManager *ui_manager, gboolean shares_selection_changes)
void caja_clipboard_set_up_text_view (GtkTextView *target, GtkUIManager *ui_manager)
void caja_clipboard_clear_if_colliding_uris (GtkWidget *widget, const GList *item_uris, GdkAtom copied_files_atom)
GtkClipboard * caja_clipboard_get (GtkWidget *widget)
GList * caja_clipboard_get_uri_list_from_selection_data (GtkSelectionData *selection_data, gboolean *cut, GdkAtom copied_files_atom)
Function Documentation
caja_clipboard_clear_if_colliding_uris()
void caja_clipboard_clear_if_colliding_uris (GtkWidget * widget, const GList * item_uris, GdkAtom copied_files_atom)
Definition at line 662 of file caja-clipboard.c.
References caja_clipboard_get(), caja_clipboard_get_uri_list_from_selection_data(), data, FALSE, NULL, and TRUE.
caja_clipboard_get()
GtkClipboard * caja_clipboard_get (GtkWidget * widget)
Definition at line 655 of file caja-clipboard.c.
Referenced by caja_clipboard_clear_if_colliding_uris().
caja_clipboard_get_uri_list_from_selection_data()
GList * caja_clipboard_get_uri_list_from_selection_data (GtkSelectionData * selection_data, gboolean * cut, GdkAtom copied_files_atom)
Definition at line 624 of file caja-clipboard.c.
References data, and NULL.
Referenced by caja_clipboard_clear_if_colliding_uris().
caja_clipboard_set_up_editable()
void caja_clipboard_set_up_editable (GtkEditable * target, GtkUIManager * ui_manager, gboolean shares_selection_changes)
Definition at line 560 of file caja-clipboard.c.
Referenced by caja_location_bar_new(), and caja_search_bar_new().
caja_clipboard_set_up_text_view()
void caja_clipboard_set_up_text_view (GtkTextView * target, GtkUIManager * ui_manager)
Definition at line 575 of file caja-clipboard.c.
References TRUE.