MATE Desktop Environment: caja-sidebar.c File Reference
caja-sidebar.c File Reference
#include <config.h>
#include "caja-sidebar.h"
Enumerations
enum { TAB_ICON_CHANGED , ZOOM_PARAMETERS_CHANGED , ZOOM_LEVEL_CHANGED , LAST_SIGNAL }
Functions
GType caja_sidebar_get_type (void)
const char * caja_sidebar_get_sidebar_id (CajaSidebar *sidebar)
char * caja_sidebar_get_tab_label (CajaSidebar *sidebar)
char * caja_sidebar_get_tab_tooltip (CajaSidebar *sidebar)
GdkPixbuf * caja_sidebar_get_tab_icon (CajaSidebar *sidebar)
void caja_sidebar_is_visible_changed (CajaSidebar *sidebar, gboolean is_visible)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TAB_ICON_CHANGED
ZOOM_PARAMETERS_CHANGED
ZOOM_LEVEL_CHANGED
LAST_SIGNAL
Definition at line 28 of file caja-sidebar.c.
Function Documentation
caja_sidebar_get_sidebar_id()
const char * caja_sidebar_get_sidebar_id (CajaSidebar * sidebar)
Definition at line 89 of file caja-sidebar.c.
References CAJA_IS_SIDEBAR, CAJA_SIDEBAR_GET_IFACE, and NULL.
Referenced by caja_navigation_window_add_sidebar_panel().
caja_sidebar_get_tab_icon()
GdkPixbuf * caja_sidebar_get_tab_icon (CajaSidebar * sidebar)
Definition at line 113 of file caja-sidebar.c.
References CAJA_IS_SIDEBAR, CAJA_SIDEBAR_GET_IFACE, and NULL.
Referenced by caja_navigation_window_add_sidebar_panel().
caja_sidebar_get_tab_label()
char * caja_sidebar_get_tab_label (CajaSidebar * sidebar)
Definition at line 97 of file caja-sidebar.c.
References CAJA_IS_SIDEBAR, CAJA_SIDEBAR_GET_IFACE, and NULL.
Referenced by caja_navigation_window_add_sidebar_panel().
caja_sidebar_get_tab_tooltip()
char * caja_sidebar_get_tab_tooltip (CajaSidebar * sidebar)
Definition at line 105 of file caja-sidebar.c.
References CAJA_IS_SIDEBAR, CAJA_SIDEBAR_GET_IFACE, and NULL.
Referenced by caja_navigation_window_add_sidebar_panel().
caja_sidebar_get_type()
GType caja_sidebar_get_type (void)
Definition at line 59 of file caja-sidebar.c.
References NULL, and type.
caja_sidebar_is_visible_changed()
void caja_sidebar_is_visible_changed (CajaSidebar * sidebar, gboolean is_visible)
Definition at line 121 of file caja-sidebar.c.
References CAJA_IS_SIDEBAR, and CAJA_SIDEBAR_GET_IFACE.