MATE Desktop Environment: caja-desktop-icon-file.h File Reference
caja-desktop-icon-file.h File Reference
#include "caja-file.h"
#include "caja-desktop-link.h"
Classes
struct CajaDesktopIconFile
struct CajaDesktopIconFileClass
Macros
#define CAJA_TYPE_DESKTOP_ICON_FILE caja_desktop_icon_file_get_type()
#define CAJA_DESKTOP_ICON_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_DESKTOP_ICON_FILE, CajaDesktopIconFile))
#define CAJA_DESKTOP_ICON_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_DESKTOP_ICON_FILE, CajaDesktopIconFileClass))
#define CAJA_IS_DESKTOP_ICON_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_DESKTOP_ICON_FILE))
#define CAJA_IS_DESKTOP_ICON_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_DESKTOP_ICON_FILE))
#define CAJA_DESKTOP_ICON_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_DESKTOP_ICON_FILE, CajaDesktopIconFileClass))
Typedefs
typedef struct _CajaDesktopIconFilePrivate CajaDesktopIconFilePrivate
Functions
GType caja_desktop_icon_file_get_type (void)
CajaDesktopIconFile * caja_desktop_icon_file_new (CajaDesktopLink *link)
void caja_desktop_icon_file_update (CajaDesktopIconFile *icon_file)
void caja_desktop_icon_file_remove (CajaDesktopIconFile *icon_file)
CajaDesktopLink * caja_desktop_icon_file_get_link (CajaDesktopIconFile *icon_file)
Macro Definition Documentation
CAJA_DESKTOP_ICON_FILE
#define CAJA_DESKTOP_ICON_FILE (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_DESKTOP_ICON_FILE, CajaDesktopIconFile))
Definition at line 33 of file caja-desktop-icon-file.h.
CAJA_DESKTOP_ICON_FILE_CLASS
#define CAJA_DESKTOP_ICON_FILE_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_DESKTOP_ICON_FILE, CajaDesktopIconFileClass))
Definition at line 35 of file caja-desktop-icon-file.h.
CAJA_DESKTOP_ICON_FILE_GET_CLASS
#define CAJA_DESKTOP_ICON_FILE_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_DESKTOP_ICON_FILE, CajaDesktopIconFileClass))
Definition at line 41 of file caja-desktop-icon-file.h.
CAJA_IS_DESKTOP_ICON_FILE
#define CAJA_IS_DESKTOP_ICON_FILE (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_DESKTOP_ICON_FILE))
Definition at line 37 of file caja-desktop-icon-file.h.
CAJA_IS_DESKTOP_ICON_FILE_CLASS
#define CAJA_IS_DESKTOP_ICON_FILE_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_DESKTOP_ICON_FILE))
Definition at line 39 of file caja-desktop-icon-file.h.
CAJA_TYPE_DESKTOP_ICON_FILE
#define CAJA_TYPE_DESKTOP_ICON_FILE caja_desktop_icon_file_get_type()
Definition at line 32 of file caja-desktop-icon-file.h.
Typedef Documentation
CajaDesktopIconFilePrivate
typedef struct _CajaDesktopIconFilePrivate CajaDesktopIconFilePrivate
Definition at line 44 of file caja-desktop-icon-file.h.
Function Documentation
caja_desktop_icon_file_get_link()
CajaDesktopLink * caja_desktop_icon_file_get_link (CajaDesktopIconFile * icon_file)
Definition at line 315 of file caja-desktop-icon-file.c.
References CajaDesktopIconFile::details, and NULL.
Referenced by caja_file_can_rename(), caja_file_get_drop_target_uri(), and caja_file_rename().
caja_desktop_icon_file_get_type()
GType caja_desktop_icon_file_get_type (void)
caja_desktop_icon_file_new()
CajaDesktopIconFile * caja_desktop_icon_file_new (CajaDesktopLink * link)
Definition at line 273 of file caja-desktop-icon-file.c.
References CAJA_DESKTOP_ICON_FILE, caja_desktop_link_get_file_name(), caja_desktop_update_metadata_from_keyfile(), caja_directory_add_file(), caja_directory_emit_files_added(), caja_directory_get_by_uri(), CAJA_FILE, CAJA_TYPE_DESKTOP_ICON_FILE, CajaDesktopIconFile::details, CajaFile::details, _CajaFilePrivate::directory, EEL_DESKTOP_URI, name, _CajaFilePrivate::name, and NULL.
caja_desktop_icon_file_remove()
void caja_desktop_icon_file_remove (CajaDesktopIconFile * icon_file)
Definition at line 245 of file caja-desktop-icon-file.c.
References caja_directory_emit_change_signals(), caja_directory_remove_file(), CAJA_FILE, caja_file_ref(), caja_file_unref(), CajaDesktopIconFile::details, CajaFile::details, _CajaFilePrivate::directory, _CajaFilePrivate::is_gone, NULL, and TRUE.
caja_desktop_icon_file_update()
void caja_desktop_icon_file_update (CajaDesktopIconFile * icon_file)
Definition at line 235 of file caja-desktop-icon-file.c.
References CAJA_FILE, and caja_file_changed().