MATE Desktop Environment: caja-navigation-window-slot.h File Reference
caja-navigation-window-slot.h File Reference
#include "caja-window-slot.h"
Classes
struct CajaNavigationWindowSlot
struct CajaNavigationWindowSlotClass
Macros
#define CAJA_TYPE_NAVIGATION_WINDOW_SLOT (caja_navigation_window_slot_get_type())
#define CAJA_NAVIGATION_WINDOW_SLOT_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), CAJA_NAVIGATION_WINDOW_SLOT_CLASS, CajaNavigationWindowSlotClass))
#define CAJA_NAVIGATION_WINDOW_SLOT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_NAVIGATION_WINDOW_SLOT, CajaNavigationWindowSlot))
#define CAJA_IS_NAVIGATION_WINDOW_SLOT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_NAVIGATION_WINDOW_SLOT))
#define CAJA_IS_NAVIGATION_WINDOW_SLOT_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), CAJA_TYPE_NAVIGATION_WINDOW_SLOT))
#define CAJA_NAVIGATION_WINDOW_SLOT_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), CAJA_TYPE_NAVIGATION_WINDOW_SLOT, CajaNavigationWindowSlotClass))
Typedefs
typedef struct CajaNavigationWindowSlot CajaNavigationWindowSlot
typedef struct CajaNavigationWindowSlotClass CajaNavigationWindowSlotClass
Enumerations
enum CajaBarMode { CAJA_BAR_PATH , CAJA_BAR_NAVIGATION , CAJA_BAR_SEARCH }
Functions
GType caja_navigation_window_slot_get_type (void)
gboolean caja_navigation_window_slot_should_close_with_mount (CajaNavigationWindowSlot *slot, GMount *mount)
void caja_navigation_window_slot_clear_forward_list (CajaNavigationWindowSlot *slot)
void caja_navigation_window_slot_clear_back_list (CajaNavigationWindowSlot *slot)
Macro Definition Documentation
CAJA_IS_NAVIGATION_WINDOW_SLOT
#define CAJA_IS_NAVIGATION_WINDOW_SLOT (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_NAVIGATION_WINDOW_SLOT))
Definition at line 36 of file caja-navigation-window-slot.h.
CAJA_IS_NAVIGATION_WINDOW_SLOT_CLASS
#define CAJA_IS_NAVIGATION_WINDOW_SLOT_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), CAJA_TYPE_NAVIGATION_WINDOW_SLOT))
Definition at line 37 of file caja-navigation-window-slot.h.
CAJA_NAVIGATION_WINDOW_SLOT
#define CAJA_NAVIGATION_WINDOW_SLOT (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_NAVIGATION_WINDOW_SLOT, CajaNavigationWindowSlot))
Definition at line 35 of file caja-navigation-window-slot.h.
CAJA_NAVIGATION_WINDOW_SLOT_CLASS
#define CAJA_NAVIGATION_WINDOW_SLOT_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), CAJA_NAVIGATION_WINDOW_SLOT_CLASS, CajaNavigationWindowSlotClass))
Definition at line 34 of file caja-navigation-window-slot.h.
CAJA_NAVIGATION_WINDOW_SLOT_GET_CLASS
#define CAJA_NAVIGATION_WINDOW_SLOT_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), CAJA_TYPE_NAVIGATION_WINDOW_SLOT, CajaNavigationWindowSlotClass))
Definition at line 38 of file caja-navigation-window-slot.h.
CAJA_TYPE_NAVIGATION_WINDOW_SLOT
#define CAJA_TYPE_NAVIGATION_WINDOW_SLOT (caja_navigation_window_slot_get_type())
Definition at line 33 of file caja-navigation-window-slot.h.
Typedef Documentation
CajaNavigationWindowSlot
typedef struct CajaNavigationWindowSlot CajaNavigationWindowSlot
Definition at line 30 of file caja-navigation-window-slot.h.
CajaNavigationWindowSlotClass
typedef struct CajaNavigationWindowSlotClass CajaNavigationWindowSlotClass
Definition at line 31 of file caja-navigation-window-slot.h.
Enumeration Type Documentation
CajaBarMode
enum CajaBarMode
Enumerator
CAJA_BAR_PATH
CAJA_BAR_NAVIGATION
CAJA_BAR_SEARCH
Definition at line 40 of file caja-navigation-window-slot.h.
Function Documentation
caja_navigation_window_slot_clear_back_list()
void caja_navigation_window_slot_clear_back_list (CajaNavigationWindowSlot * slot)
Definition at line 96 of file caja-navigation-window-slot.c.
References CajaNavigationWindowSlot::back_list, CAJA_IS_NAVIGATION_WINDOW_SLOT, and NULL.
Referenced by caja_forget_history().
caja_navigation_window_slot_clear_forward_list()
void caja_navigation_window_slot_clear_forward_list (CajaNavigationWindowSlot * slot)
Definition at line 87 of file caja-navigation-window-slot.c.
References CAJA_IS_NAVIGATION_WINDOW_SLOT, CajaNavigationWindowSlot::forward_list, and NULL.
Referenced by caja_forget_history().
caja_navigation_window_slot_get_type()
GType caja_navigation_window_slot_get_type (void)
caja_navigation_window_slot_should_close_with_mount()
gboolean caja_navigation_window_slot_should_close_with_mount (CajaNavigationWindowSlot * slot, GMount * mount)
Definition at line 41 of file caja-navigation-window-slot.c.
References CajaNavigationWindowSlot::back_list, CAJA_BOOKMARK, caja_bookmark_get_location(), CAJA_WINDOW_SLOT, CajaWindow::details, FALSE, _CajaWindowPrivate::initiated_unmount, NULL, CajaWindowSlot::pane, CajaNavigationWindowSlot::parent, TRUE, and _CajaWindowPane::window.