MATE Desktop Environment: caja-navigation-window.h File Reference
caja-navigation-window.h File Reference
#include <gtk/gtk.h>
#include <eel/eel-glib-extensions.h>
#include <libcaja-private/caja-bookmark.h>
#include <libcaja-private/caja-sidebar.h>
#include "caja-application.h"
#include "caja-information-panel.h"
#include "caja-side-pane.h"
#include "caja-window.h"
Classes
struct _CajaNavigationWindow
struct _CajaNavigationWindowClass
Macros
#define CAJA_TYPE_NAVIGATION_WINDOW caja_navigation_window_get_type()
#define CAJA_NAVIGATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_NAVIGATION_WINDOW, CajaNavigationWindow))
#define CAJA_NAVIGATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_NAVIGATION_WINDOW, CajaNavigationWindowClass))
#define CAJA_IS_NAVIGATION_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_NAVIGATION_WINDOW))
#define CAJA_IS_NAVIGATION_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_NAVIGATION_WINDOW))
#define CAJA_NAVIGATION_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_NAVIGATION_WINDOW, CajaNavigationWindowClass))
Typedefs
typedef struct _CajaNavigationWindow CajaNavigationWindow
typedef struct _CajaNavigationWindowClass CajaNavigationWindowClass
typedef struct _CajaNavigationWindowPrivate CajaNavigationWindowPrivate
Functions
GType caja_navigation_window_get_type (void)
void caja_navigation_window_allow_back (CajaNavigationWindow *window, gboolean allow)
void caja_navigation_window_allow_forward (CajaNavigationWindow *window, gboolean allow)
void caja_navigation_window_clear_back_list (CajaNavigationWindow *window)
void caja_navigation_window_clear_forward_list (CajaNavigationWindow *window)
void caja_forget_history (void)
gint caja_navigation_window_get_base_page_index (CajaNavigationWindow *window)
void caja_navigation_window_hide_toolbar (CajaNavigationWindow *window)
void caja_navigation_window_show_toolbar (CajaNavigationWindow *window)
gboolean caja_navigation_window_toolbar_showing (CajaNavigationWindow *window)
void caja_navigation_window_hide_sidebar (CajaNavigationWindow *window)
void caja_navigation_window_show_sidebar (CajaNavigationWindow *window)
gboolean caja_navigation_window_sidebar_showing (CajaNavigationWindow *window)
void caja_navigation_window_add_sidebar_panel (CajaNavigationWindow *window, CajaSidebar *sidebar_panel)
void caja_navigation_window_remove_sidebar_panel (CajaNavigationWindow *window, CajaSidebar *sidebar_panel)
void caja_navigation_window_hide_status_bar (CajaNavigationWindow *window)
void caja_navigation_window_show_status_bar (CajaNavigationWindow *window)
gboolean caja_navigation_window_status_bar_showing (CajaNavigationWindow *window)
void caja_navigation_window_back_or_forward (CajaNavigationWindow *window, gboolean back, guint distance, gboolean new_tab)
void caja_navigation_window_show_search (CajaNavigationWindow *window)
void caja_navigation_window_unset_focus_widget (CajaNavigationWindow *window)
void caja_navigation_window_hide_search (CajaNavigationWindow *window)
void caja_navigation_window_set_search_button (CajaNavigationWindow *window, gboolean state)
void caja_navigation_window_restore_focus_widget (CajaNavigationWindow *window)
void caja_navigation_window_split_view_on (CajaNavigationWindow *window)
void caja_navigation_window_split_view_off (CajaNavigationWindow *window)
gboolean caja_navigation_window_split_view_showing (CajaNavigationWindow *window)
gboolean caja_navigation_window_is_in_temporary_navigation_bar (GtkWidget *widget, CajaNavigationWindow *window)
gboolean caja_navigation_window_is_in_temporary_search_bar (GtkWidget *widget, CajaNavigationWindow *window)
Macro Definition Documentation
CAJA_IS_NAVIGATION_WINDOW
#define CAJA_IS_NAVIGATION_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_NAVIGATION_WINDOW))
Definition at line 50 of file caja-navigation-window.h.
CAJA_IS_NAVIGATION_WINDOW_CLASS
#define CAJA_IS_NAVIGATION_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_NAVIGATION_WINDOW))
Definition at line 52 of file caja-navigation-window.h.
CAJA_NAVIGATION_WINDOW
#define CAJA_NAVIGATION_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_NAVIGATION_WINDOW, CajaNavigationWindow))
Definition at line 46 of file caja-navigation-window.h.
CAJA_NAVIGATION_WINDOW_CLASS
#define CAJA_NAVIGATION_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_NAVIGATION_WINDOW, CajaNavigationWindowClass))
Definition at line 48 of file caja-navigation-window.h.
CAJA_NAVIGATION_WINDOW_GET_CLASS
#define CAJA_NAVIGATION_WINDOW_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_NAVIGATION_WINDOW, CajaNavigationWindowClass))
Definition at line 54 of file caja-navigation-window.h.
CAJA_TYPE_NAVIGATION_WINDOW
#define CAJA_TYPE_NAVIGATION_WINDOW caja_navigation_window_get_type()
Definition at line 45 of file caja-navigation-window.h.
Typedef Documentation
CajaNavigationWindow
typedef struct _CajaNavigationWindow CajaNavigationWindow
Definition at line 57 of file caja-navigation-window.h.
CajaNavigationWindowClass
typedef struct _CajaNavigationWindowClass CajaNavigationWindowClass
Definition at line 58 of file caja-navigation-window.h.
CajaNavigationWindowPrivate
typedef struct _CajaNavigationWindowPrivate CajaNavigationWindowPrivate
Definition at line 59 of file caja-navigation-window.h.
Function Documentation
caja_forget_history()
void caja_forget_history (void)
Definition at line 1885 of file caja-window.c.
References CAJA_APPLICATION, CAJA_IS_NAVIGATION_WINDOW, CAJA_NAVIGATION_WINDOW, caja_navigation_window_allow_back(), caja_navigation_window_allow_forward(), caja_navigation_window_slot_clear_back_list(), caja_navigation_window_slot_clear_forward_list(), CAJA_WINDOW, CAJA_WINDOW_SLOT, caja_window_slot_add_current_location_to_history_list(), CajaWindowSlot::current_location_bookmark, CajaWindow::details, FALSE, NULL, _CajaWindowPrivate::panes, and _CajaWindowPane::slots.
caja_navigation_window_add_sidebar_panel()
void caja_navigation_window_add_sidebar_panel (CajaNavigationWindow * window, CajaSidebar * sidebar_panel)
Definition at line 677 of file caja-navigation-window.c.
References CAJA_IS_NAVIGATION_WINDOW, CAJA_IS_SIDE_PANE, CAJA_IS_SIDEBAR, CAJA_NAVIGATION_WINDOW, caja_side_pane_add_panel(), caja_side_pane_set_panel_image(), caja_side_pane_show_panel(), caja_sidebar_get_sidebar_id(), caja_sidebar_get_tab_icon(), caja_sidebar_get_tab_label(), caja_sidebar_get_tab_tooltip(), caja_window_state, CAJA_WINDOW_STATE_SIDE_PANE_VIEW, label, NULL, _CajaNavigationWindow::sidebar, and _CajaNavigationWindow::sidebar_panels.
caja_navigation_window_allow_back()
void caja_navigation_window_allow_back (CajaNavigationWindow * window, gboolean allow)
Definition at line 759 of file caja-navigation-window.c.
References action, CAJA_ACTION_BACK, _CajaNavigationWindow::details, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, and _CajaNavigationWindowPrivate::navigation_action_group.
Referenced by caja_forget_history().
caja_navigation_window_allow_forward()
void caja_navigation_window_allow_forward (CajaNavigationWindow * window, gboolean allow)
Definition at line 772 of file caja-navigation-window.c.
References action, CAJA_ACTION_FORWARD, _CajaNavigationWindow::details, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, and _CajaNavigationWindowPrivate::navigation_action_group.
Referenced by caja_forget_history().
caja_navigation_window_back_or_forward()
void caja_navigation_window_back_or_forward (CajaNavigationWindow * window, gboolean back, guint distance, gboolean new_tab)
Definition at line 2314 of file caja-window-manage-views.c.
References CajaNavigationWindowSlot::back_list, caja_bookmark_get_location(), caja_bookmark_get_scroll_pos(), CAJA_LOCATION_CHANGE_BACK, CAJA_LOCATION_CHANGE_FORWARD, CAJA_WINDOW, CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, CAJA_WINDOW_OPEN_FLAG_NEW_TAB, caja_window_slot_get_location(), caja_window_slot_open_location_full(), CajaNavigationWindowSlot::forward_list, and NULL.
Referenced by caja_navigation_window_go_back(), and caja_navigation_window_go_forward().
caja_navigation_window_clear_back_list()
void caja_navigation_window_clear_back_list (CajaNavigationWindow * window)
caja_navigation_window_clear_forward_list()
void caja_navigation_window_clear_forward_list (CajaNavigationWindow * window)
caja_navigation_window_get_base_page_index()
gint caja_navigation_window_get_base_page_index (CajaNavigationWindow * window)
caja_navigation_window_get_base_page_index: @window: Window to get index from
Returns the index of the base page in the history list. Base page is not the currently displayed page, but the page that acts as the base from which the back and forward commands navigate from.
Definition at line 1087 of file caja-navigation-window.c.
References CAJA_NAVIGATION_WINDOW_SLOT, CAJA_WINDOW, and CajaNavigationWindowSlot::forward_list.
caja_navigation_window_get_type()
GType caja_navigation_window_get_type (void)
caja_navigation_window_hide_search()
void caja_navigation_window_hide_search (CajaNavigationWindow * window)
Definition at line 886 of file caja-navigation-window.c.
References CAJA_NAVIGATION_WINDOW_PANE, caja_navigation_window_pane_hide_temporary_bars(), caja_navigation_window_pane_search_bar_showing(), caja_navigation_window_restore_focus_widget(), and CAJA_WINDOW.
caja_navigation_window_hide_sidebar()
void caja_navigation_window_hide_sidebar (CajaNavigationWindow * window)
Definition at line 1042 of file caja-navigation-window.c.
References caja_navigation_window_update_show_hide_menu_items(), caja_window_state, CAJA_WINDOW_STATE_START_WITH_SIDEBAR, FALSE, NULL, and _CajaNavigationWindow::sidebar.
caja_navigation_window_hide_status_bar()
void caja_navigation_window_hide_status_bar (CajaNavigationWindow * window)
Definition at line 995 of file caja-navigation-window.c.
References caja_navigation_window_update_show_hide_menu_items(), CAJA_WINDOW, caja_window_state, CAJA_WINDOW_STATE_START_WITH_STATUS_BAR, and FALSE.
caja_navigation_window_hide_toolbar()
void caja_navigation_window_hide_toolbar (CajaNavigationWindow * window)
Definition at line 1026 of file caja-navigation-window.c.
References caja_navigation_window_update_show_hide_menu_items(), caja_window_state, CAJA_WINDOW_STATE_START_WITH_TOOLBAR, _CajaNavigationWindow::details, FALSE, and _CajaNavigationWindowPrivate::toolbar.
caja_navigation_window_is_in_temporary_navigation_bar()
gboolean caja_navigation_window_is_in_temporary_navigation_bar (GtkWidget * widget, CajaNavigationWindow * window)
Definition at line 279 of file caja-navigation-window.c.
References CAJA_TYPE_LOCATION_BAR, CAJA_WINDOW, FALSE, NULL, _CajaNavigationWindowPane::temporary_navigation_bar, and TRUE.
Referenced by caja_navigation_window_pane_set_bar_mode().
caja_navigation_window_is_in_temporary_search_bar()
gboolean caja_navigation_window_is_in_temporary_search_bar (GtkWidget * widget, CajaNavigationWindow * window)
Definition at line 296 of file caja-navigation-window.c.
References CAJA_TYPE_SEARCH_BAR, CAJA_WINDOW, FALSE, NULL, _CajaNavigationWindowPane::temporary_search_bar, and TRUE.
Referenced by caja_navigation_window_pane_set_bar_mode().
caja_navigation_window_remove_sidebar_panel()
void caja_navigation_window_remove_sidebar_panel (CajaNavigationWindow * window, CajaSidebar * sidebar_panel)
Definition at line 727 of file caja-navigation-window.c.
References CAJA_IS_NAVIGATION_WINDOW, CAJA_IS_SIDEBAR, caja_side_pane_remove_panel(), NULL, _CajaNavigationWindow::sidebar, and _CajaNavigationWindow::sidebar_panels.
caja_navigation_window_restore_focus_widget()
void caja_navigation_window_restore_focus_widget (CajaNavigationWindow * window)
Definition at line 334 of file caja-navigation-window.c.
References CAJA_IS_VIEW, caja_navigation_window_unset_focus_widget(), CAJA_VIEW, caja_view_grab_focus(), _CajaNavigationWindow::details, _CajaNavigationWindowPrivate::last_focus_widget, and NULL.
Referenced by caja_navigation_window_hide_search().
caja_navigation_window_set_search_button()
void caja_navigation_window_set_search_button (CajaNavigationWindow * window, gboolean state)
Definition at line 901 of file caja-navigation-window.c.
References action, _CajaNavigationWindow::details, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, _CajaNavigationWindowPrivate::navigation_action_group, and NULL.
Referenced by caja_navigation_window_pane_hide_temporary_bars(), and caja_navigation_window_pane_set_bar_mode().
caja_navigation_window_show_search()
void caja_navigation_window_show_search (CajaNavigationWindow * window)
Definition at line 867 of file caja-navigation-window.c.
References CAJA_BAR_SEARCH, CAJA_NAVIGATION_WINDOW_PANE, caja_navigation_window_pane_search_bar_showing(), caja_navigation_window_pane_set_bar_mode(), caja_navigation_window_pane_show_location_bar_temporarily(), CAJA_SEARCH_BAR, caja_search_bar_clear(), caja_search_bar_grab_focus(), CAJA_WINDOW, _CajaNavigationWindowPane::search_bar, _CajaNavigationWindowPane::temporary_search_bar, and TRUE.
caja_navigation_window_show_sidebar()
void caja_navigation_window_show_sidebar (CajaNavigationWindow * window)
Definition at line 1056 of file caja-navigation-window.c.
References caja_navigation_window_update_show_hide_menu_items(), caja_window_state, CAJA_WINDOW_STATE_START_WITH_SIDEBAR, NULL, _CajaNavigationWindow::sidebar, and TRUE.
caja_navigation_window_show_status_bar()
void caja_navigation_window_show_status_bar (CajaNavigationWindow * window)
Definition at line 1005 of file caja-navigation-window.c.
References caja_navigation_window_update_show_hide_menu_items(), CAJA_WINDOW, caja_window_state, CAJA_WINDOW_STATE_START_WITH_STATUS_BAR, and TRUE.
caja_navigation_window_show_toolbar()
void caja_navigation_window_show_toolbar (CajaNavigationWindow * window)
Definition at line 1034 of file caja-navigation-window.c.
References caja_navigation_window_update_show_hide_menu_items(), caja_window_state, CAJA_WINDOW_STATE_START_WITH_TOOLBAR, _CajaNavigationWindow::details, _CajaNavigationWindowPrivate::toolbar, and TRUE.
caja_navigation_window_sidebar_showing()
gboolean caja_navigation_window_sidebar_showing (CajaNavigationWindow * window)
Definition at line 1069 of file caja-navigation-window.c.
References CAJA_IS_NAVIGATION_WINDOW, _CajaNavigationWindowPrivate::content_paned, _CajaNavigationWindow::details, FALSE, NULL, and _CajaNavigationWindow::sidebar.
Referenced by caja_navigation_window_update_show_hide_menu_items().
caja_navigation_window_split_view_off()
void caja_navigation_window_split_view_off (CajaNavigationWindow * window)
Definition at line 1408 of file caja-navigation-window.c.
References _CajaWindowPrivate::active_pane, caja_navigation_window_update_show_hide_menu_items(), caja_navigation_window_update_split_view_actions_sensitivity(), CAJA_WINDOW, caja_window_close_pane(), CajaWindow::details, NULL, and _CajaWindowPrivate::panes.
caja_navigation_window_split_view_on()
void caja_navigation_window_split_view_on (CajaNavigationWindow * window)
Definition at line 1358 of file caja-navigation-window.c.
References action, CAJA_ACTION_SHOW_HIDE_LOCATION_BAR, CAJA_NAVIGATION_WINDOW, CAJA_NAVIGATION_WINDOW_PANE, caja_navigation_window_pane_hide_location_bar(), caja_navigation_window_pane_show_location_bar(), CAJA_WINDOW, caja_window_get_active_slot(), CAJA_WINDOW_PANE, caja_window_slot_get_location(), caja_window_slot_go_to, FALSE, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, NULL, CajaWindowSlot::pane, and TRUE.
caja_navigation_window_split_view_showing()
gboolean caja_navigation_window_split_view_showing (CajaNavigationWindow * window)
Definition at line 1437 of file caja-navigation-window.c.
References CAJA_WINDOW.
Referenced by caja_navigation_window_update_show_hide_menu_items().
caja_navigation_window_status_bar_showing()
gboolean caja_navigation_window_status_bar_showing (CajaNavigationWindow * window)
Definition at line 1015 of file caja-navigation-window.c.
References CAJA_WINDOW, NULL, and TRUE.
Referenced by caja_navigation_window_update_show_hide_menu_items().
caja_navigation_window_toolbar_showing()
gboolean caja_navigation_window_toolbar_showing (CajaNavigationWindow * window)
Definition at line 984 of file caja-navigation-window.c.
References _CajaNavigationWindow::details, NULL, _CajaNavigationWindowPrivate::toolbar, and TRUE.
Referenced by caja_navigation_window_update_show_hide_menu_items().
caja_navigation_window_unset_focus_widget()
void caja_navigation_window_unset_focus_widget (CajaNavigationWindow * window)
Definition at line 268 of file caja-navigation-window.c.
References _CajaNavigationWindow::details, _CajaNavigationWindowPrivate::last_focus_widget, and NULL.
Referenced by caja_navigation_window_restore_focus_widget().