MATE Desktop Environment: caja-query-editor.h File Reference
caja-query-editor.h File Reference
#include <gtk/gtk.h>
#include <libcaja-private/caja-query.h>
#include <libcaja-private/caja-window-info.h>
#include "caja-search-bar.h"
Classes
struct CajaQueryEditor
struct CajaQueryEditorClass
Macros
#define CAJA_TYPE_QUERY_EDITOR caja_query_editor_get_type()
#define CAJA_QUERY_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_QUERY_EDITOR, CajaQueryEditor))
#define CAJA_QUERY_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_QUERY_EDITOR, CajaQueryEditorClass))
#define CAJA_IS_QUERY_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_QUERY_EDITOR))
#define CAJA_IS_QUERY_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_QUERY_EDITOR))
#define CAJA_QUERY_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_QUERY_EDITOR, CajaQueryEditorClass))
Typedefs
typedef struct CajaQueryEditorDetails CajaQueryEditorDetails
typedef struct CajaQueryEditor CajaQueryEditor
Functions
GType caja_query_editor_get_type (void)
GtkWidget * caja_query_editor_new (gboolean start_hidden, gboolean is_indexed)
GtkWidget * caja_query_editor_new_with_bar (gboolean start_hidden, gboolean is_indexed, gboolean start_attached, CajaSearchBar *bar, CajaWindowSlot *slot)
void caja_query_editor_set_default_query (CajaQueryEditor *editor)
void caja_query_editor_grab_focus (CajaQueryEditor *editor)
void caja_query_editor_clear_query (CajaQueryEditor *editor)
CajaQuery * caja_query_editor_get_query (CajaQueryEditor *editor)
void caja_query_editor_set_query (CajaQueryEditor *editor, CajaQuery *query)
void caja_query_editor_set_visible (CajaQueryEditor *editor, gboolean visible)
Macro Definition Documentation
CAJA_IS_QUERY_EDITOR
#define CAJA_IS_QUERY_EDITOR (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_QUERY_EDITOR))
Definition at line 39 of file caja-query-editor.h.
CAJA_IS_QUERY_EDITOR_CLASS
#define CAJA_IS_QUERY_EDITOR_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_QUERY_EDITOR))
Definition at line 41 of file caja-query-editor.h.
CAJA_QUERY_EDITOR
#define CAJA_QUERY_EDITOR (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_QUERY_EDITOR, CajaQueryEditor))
Definition at line 35 of file caja-query-editor.h.
CAJA_QUERY_EDITOR_CLASS
#define CAJA_QUERY_EDITOR_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_QUERY_EDITOR, CajaQueryEditorClass))
Definition at line 37 of file caja-query-editor.h.
CAJA_QUERY_EDITOR_GET_CLASS
#define CAJA_QUERY_EDITOR_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_QUERY_EDITOR, CajaQueryEditorClass))
Definition at line 43 of file caja-query-editor.h.
CAJA_TYPE_QUERY_EDITOR
#define CAJA_TYPE_QUERY_EDITOR caja_query_editor_get_type()
Definition at line 34 of file caja-query-editor.h.
Typedef Documentation
CajaQueryEditor
typedef struct CajaQueryEditor CajaQueryEditor
CajaQueryEditorDetails
typedef struct CajaQueryEditorDetails CajaQueryEditorDetails
Definition at line 46 of file caja-query-editor.h.
Function Documentation
caja_query_editor_clear_query()
void caja_query_editor_clear_query (CajaQueryEditor * editor)
Definition at line 1763 of file caja-query-editor.c.
References CajaQueryEditor::details, FALSE, and TRUE.
Referenced by caja_query_editor_set_query().
caja_query_editor_get_query()
CajaQuery * caja_query_editor_get_query (CajaQueryEditor * editor)
Definition at line 1729 of file caja-query-editor.c.
References caja_query_new(), caja_query_set_text(), CajaQueryEditor::details, and NULL.
caja_query_editor_get_type()
GType caja_query_editor_get_type (void)
caja_query_editor_grab_focus()
void caja_query_editor_grab_focus (CajaQueryEditor * editor)
Definition at line 1720 of file caja-query-editor.c.
References CajaQueryEditor::details.
caja_query_editor_new()
GtkWidget * caja_query_editor_new (gboolean start_hidden, gboolean is_indexed)
Definition at line 1775 of file caja-query-editor.c.
References CAJA_QUERY_EDITOR, caja_query_editor_set_visible(), CAJA_TYPE_QUERY_EDITOR, and NULL.
caja_query_editor_new_with_bar()
GtkWidget * caja_query_editor_new_with_bar (gboolean start_hidden, gboolean is_indexed, gboolean start_attached, CajaSearchBar * bar, CajaWindowSlot * slot)
Definition at line 1828 of file caja-query-editor.c.
References CAJA_QUERY_EDITOR, caja_query_editor_set_visible(), caja_search_bar_borrow_entry(), CAJA_TYPE_QUERY_EDITOR, CajaQueryEditor::details, eel_add_weak_pointer(), and NULL.
caja_query_editor_set_default_query()
void caja_query_editor_set_default_query (CajaQueryEditor * editor)
Definition at line 1560 of file caja-query-editor.c.
References CAJA_QUERY_EDITOR_ROW_LOCATION, and CajaQueryEditor::details.
caja_query_editor_set_query()
void caja_query_editor_set_query (CajaQueryEditor * editor, CajaQuery * query)
Definition at line 1865 of file caja-query-editor.c.
References caja_query_editor_clear_query(), CAJA_QUERY_EDITOR_ROW_LAST, caja_query_get_text(), CajaQueryEditor::details, FALSE, TRUE, and type.
caja_query_editor_set_visible()
void caja_query_editor_set_visible (CajaQueryEditor * editor, gboolean visible)
Definition at line 1668 of file caja-query-editor.c.
References CajaQueryEditor::details.
Referenced by caja_query_editor_new(), and caja_query_editor_new_with_bar().