MATE Desktop Environment: caja-bookmark-list.c File Reference
caja-bookmark-list.c File Reference
#include <config.h>
#include <string.h>
#include <gio/gio.h>
#include <libcaja-private/caja-file-utilities.h>
#include <libcaja-private/caja-file.h>
#include <libcaja-private/caja-icon-names.h>
#include "caja-bookmark-list.h"
Macros
#define LOAD_JOB 1
#define SAVE_JOB 2
Enumerations
enum { CONTENTS_CHANGED , LAST_SIGNAL }
Functions
void caja_bookmark_list_append (CajaBookmarkList *bookmarks, CajaBookmark *bookmark)
gboolean caja_bookmark_list_contains (CajaBookmarkList *bookmarks, CajaBookmark *bookmark)
void caja_bookmark_list_delete_item_at (CajaBookmarkList *bookmarks, guint index)
void caja_bookmark_list_move_item (CajaBookmarkList *bookmarks, guint index, guint destination)
void caja_bookmark_list_delete_items_with_uri (CajaBookmarkList *bookmarks, const char *uri)
const char * caja_bookmark_list_get_window_geometry (CajaBookmarkList *bookmarks)
void caja_bookmark_list_insert_item (CajaBookmarkList *bookmarks, CajaBookmark *new_bookmark, guint index)
CajaBookmark * caja_bookmark_list_item_at (CajaBookmarkList *bookmarks, guint index)
guint caja_bookmark_list_length (CajaBookmarkList *bookmarks)
CajaBookmarkList * caja_bookmark_list_new (void)
void caja_bookmark_list_set_window_geometry (CajaBookmarkList *bookmarks, const char *geometry)
Macro Definition Documentation
LOAD_JOB
#define LOAD_JOB 1
Definition at line 39 of file caja-bookmark-list.c.
SAVE_JOB
#define SAVE_JOB 2
Definition at line 40 of file caja-bookmark-list.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CONTENTS_CHANGED
LAST_SIGNAL
Definition at line 42 of file caja-bookmark-list.c.
Function Documentation
caja_bookmark_list_append()
void caja_bookmark_list_append (CajaBookmarkList * bookmarks, CajaBookmark * bookmark)
caja_bookmark_list_append:
Append a bookmark to a bookmark list. @bookmarks: CajaBookmarkList to append to. @bookmark: Bookmark to append a copy of.
Definition at line 302 of file caja-bookmark-list.c.
References caja_bookmark_copy(), CAJA_IS_BOOKMARK, and CAJA_IS_BOOKMARK_LIST.
Referenced by caja_window_add_bookmark_for_current_location().
caja_bookmark_list_contains()
gboolean caja_bookmark_list_contains (CajaBookmarkList * bookmarks, CajaBookmark * bookmark)
caja_bookmark_list_contains:
Check whether a bookmark with matching name and url is already in the list. @bookmarks: CajaBookmarkList to check contents of. @bookmark: CajaBookmark to match against.
Return value: TRUE if matching bookmark is in list, FALSE otherwise
Definition at line 325 of file caja-bookmark-list.c.
References caja_bookmark_compare_with(), CAJA_IS_BOOKMARK, CAJA_IS_BOOKMARK_LIST, FALSE, CajaBookmarkList::list, and NULL.
Referenced by caja_window_add_bookmark_for_current_location().
caja_bookmark_list_delete_item_at()
void caja_bookmark_list_delete_item_at (CajaBookmarkList * bookmarks, guint index)
caja_bookmark_list_delete_item_at:
Delete the bookmark at the specified position. @bookmarks: the list of bookmarks. @index: index, must be less than length of list.
Definition at line 345 of file caja-bookmark-list.c.
References CAJA_BOOKMARK, CAJA_IS_BOOKMARK, CAJA_IS_BOOKMARK_LIST, CajaBookmarkList::list, and NULL.
caja_bookmark_list_delete_items_with_uri()
void caja_bookmark_list_delete_items_with_uri (CajaBookmarkList * bookmarks, const char * uri)
caja_bookmark_list_delete_items_with_uri:
Delete all bookmarks with the given uri. @bookmarks: the list of bookmarks. @uri: The uri to match.
Definition at line 416 of file caja-bookmark-list.c.
References CAJA_BOOKMARK, caja_bookmark_get_uri(), CAJA_IS_BOOKMARK_LIST, FALSE, CajaBookmarkList::list, NULL, and TRUE.
caja_bookmark_list_get_window_geometry()
const char * caja_bookmark_list_get_window_geometry (CajaBookmarkList * bookmarks)
caja_bookmark_list_get_window_geometry:
Get a string representing the bookmark_list's window's geometry. This is the value set earlier by caja_bookmark_list_set_window_geometry. @bookmarks: the list of bookmarks associated with the window. Return value: string representation of window's geometry, suitable for passing to mate_parse_geometry(), or NULL if no window geometry has yet been saved for this bookmark list.
Definition at line 461 of file caja-bookmark-list.c.
caja_bookmark_list_insert_item()
void caja_bookmark_list_insert_item (CajaBookmarkList * bookmarks, CajaBookmark * new_bookmark, guint index)
caja_bookmark_list_insert_item:
Insert a bookmark at a specified position. @bookmarks: the list of bookmarks. @index: the position to insert the bookmark at. @new_bookmark: the bookmark to insert a copy of.
Definition at line 475 of file caja-bookmark-list.c.
References caja_bookmark_copy(), CAJA_IS_BOOKMARK_LIST, and CajaBookmarkList::list.
caja_bookmark_list_item_at()
CajaBookmark * caja_bookmark_list_item_at (CajaBookmarkList * bookmarks, guint index)
caja_bookmark_list_item_at:
Get the bookmark at the specified position. @bookmarks: the list of bookmarks. @index: index, must be less than length of list.
Return value: the bookmark at position @index in @bookmarks.
Definition at line 499 of file caja-bookmark-list.c.
References CAJA_BOOKMARK, CAJA_IS_BOOKMARK_LIST, CajaBookmarkList::list, and NULL.
caja_bookmark_list_length()
guint caja_bookmark_list_length (CajaBookmarkList * bookmarks)
caja_bookmark_list_length:
Get the number of bookmarks in the list. @bookmarks: the list of bookmarks.
Return value: the length of the bookmark list.
Definition at line 516 of file caja-bookmark-list.c.
References CAJA_IS_BOOKMARK_LIST, and CajaBookmarkList::list.
caja_bookmark_list_move_item()
void caja_bookmark_list_move_item (CajaBookmarkList * bookmarks, guint index, guint destination)
caja_bookmark_list_move_item:
Move the item from the given position to the destination. @index: the index of the first bookmark. @destination: the index of the second bookmark.
Definition at line 375 of file caja-bookmark-list.c.
References CajaBookmarkList::list, and NULL.
caja_bookmark_list_new()
CajaBookmarkList * caja_bookmark_list_new (void)
caja_bookmark_list_new:
Create a new bookmark_list, with contents read from disk.
Return value: A pointer to the new widget.
Definition at line 780 of file caja-bookmark-list.c.
References CAJA_BOOKMARK_LIST, CAJA_TYPE_BOOKMARK_LIST, and NULL.
caja_bookmark_list_set_window_geometry()
void caja_bookmark_list_set_window_geometry (CajaBookmarkList * bookmarks, const char * geometry)
caja_bookmark_list_set_window_geometry:
Set a bookmarks window's geometry (position & size), in string form. This is stored to disk by this class, and can be retrieved later in the same session or in a future session. @bookmarks: the list of bookmarks associated with the window. @geometry: the new window geometry string.
Definition at line 799 of file caja-bookmark-list.c.
References CAJA_IS_BOOKMARK_LIST, and NULL.
Referenced by caja_bookmarks_window_save_geometry().