MATE Desktop Environment: caja-signaller.c File Reference
caja-signaller.c File Reference
#include <config.h>
#include <eel/eel-debug.h>
#include "caja-signaller.h"
Typedefs
typedef GObject CajaSignaller
typedef GObjectClass CajaSignallerClass
Enumerations
enum {
HISTORY_LIST_CHANGED , EMBLEMS_CHANGED , POPUP_MENU_CHANGED , USER_DIRS_CHANGED ,
MIME_DATA_CHANGED , LAST_SIGNAL
}
Functions
G_DEFINE_TYPE (CajaSignaller, caja_signaller, G_TYPE_OBJECT)
GObject * caja_signaller_get_current (void)
Typedef Documentation
CajaSignaller
typedef GObject CajaSignaller
Definition at line 35 of file caja-signaller.c.
CajaSignallerClass
typedef GObjectClass CajaSignallerClass
Definition at line 36 of file caja-signaller.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HISTORY_LIST_CHANGED
EMBLEMS_CHANGED
POPUP_MENU_CHANGED
USER_DIRS_CHANGED
MIME_DATA_CHANGED
LAST_SIGNAL
Definition at line 38 of file caja-signaller.c.
Function Documentation
caja_signaller_get_current()
GObject * caja_signaller_get_current (void)
Definition at line 55 of file caja-signaller.c.
References eel_debug_call_at_shutdown_with_data(), and NULL.
Referenced by caja_directory_monitor_add_internal(), and caja_send_history_list_changed().
G_DEFINE_TYPE()
G_DEFINE_TYPE (CajaSignaller , caja_signaller , G_TYPE_OBJECT)