MATE Desktop Environment: caja-application.h File Reference
caja-application.h File Reference
#include <config.h>
#include <gdk/gdk.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <libegg/eggsmclient.h>
Classes
struct CajaApplication
struct CajaApplicationClass
Macros
#define CAJA_DESKTOP_ICON_VIEW_IID "OAFIID:Caja_File_Manager_Desktop_Icon_View"
#define CAJA_TYPE_APPLICATION caja_application_get_type()
#define CAJA_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), CAJA_TYPE_APPLICATION, CajaApplication))
#define CAJA_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), CAJA_TYPE_APPLICATION, CajaApplicationClass))
#define CAJA_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), CAJA_TYPE_APPLICATION))
#define CAJA_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), CAJA_TYPE_APPLICATION))
#define CAJA_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), CAJA_TYPE_APPLICATION, CajaApplicationClass))
#define CAJA_WINDOW_DEFINED
#define CAJA_SPATIAL_WINDOW_DEFINED
Typedefs
typedef struct CajaWindow CajaWindow
typedef struct _CajaSpatialWindow CajaSpatialWindow
typedef struct _CajaApplicationPrivate CajaApplicationPrivate
Functions
GType caja_application_get_type (void)
CajaApplication * caja_application_new (void)
CajaWindow * caja_application_get_spatial_window (CajaApplication *application, CajaWindow *requesting_window, const char *startup_id, GFile *location, GdkScreen *screen, gboolean *existing)
CajaWindow * caja_application_create_navigation_window (CajaApplication *application, GdkScreen *screen)
void caja_application_close_all_navigation_windows (CajaApplication *self)
void caja_application_close_parent_windows (CajaSpatialWindow *window)
void caja_application_close_all_spatial_windows (void)
void caja_application_open_location (CajaApplication *application, GFile *location, GFile *selection, const char *startup_id, const gboolean open_in_tabs)
Macro Definition Documentation
CAJA_APPLICATION
#define CAJA_APPLICATION (obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), CAJA_TYPE_APPLICATION, CajaApplication))
Definition at line 41 of file caja-application.h.
CAJA_APPLICATION_CLASS
#define CAJA_APPLICATION_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), CAJA_TYPE_APPLICATION, CajaApplicationClass))
Definition at line 43 of file caja-application.h.
CAJA_APPLICATION_GET_CLASS
#define CAJA_APPLICATION_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS((obj), CAJA_TYPE_APPLICATION, CajaApplicationClass))
Definition at line 49 of file caja-application.h.
CAJA_DESKTOP_ICON_VIEW_IID
#define CAJA_DESKTOP_ICON_VIEW_IID "OAFIID:Caja_File_Manager_Desktop_Icon_View"
Definition at line 37 of file caja-application.h.
CAJA_IS_APPLICATION
#define CAJA_IS_APPLICATION (obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), CAJA_TYPE_APPLICATION))
Definition at line 45 of file caja-application.h.
CAJA_IS_APPLICATION_CLASS
#define CAJA_IS_APPLICATION_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), CAJA_TYPE_APPLICATION))
Definition at line 47 of file caja-application.h.
CAJA_SPATIAL_WINDOW_DEFINED
#define CAJA_SPATIAL_WINDOW_DEFINED
Definition at line 58 of file caja-application.h.
CAJA_TYPE_APPLICATION
#define CAJA_TYPE_APPLICATION caja_application_get_type()
Definition at line 39 of file caja-application.h.
CAJA_WINDOW_DEFINED
#define CAJA_WINDOW_DEFINED
Definition at line 53 of file caja-application.h.
Typedef Documentation
CajaApplicationPrivate
typedef struct _CajaApplicationPrivate CajaApplicationPrivate
Definition at line 62 of file caja-application.h.
CajaSpatialWindow
typedef struct _CajaSpatialWindow CajaSpatialWindow
Definition at line 59 of file caja-application.h.
CajaWindow
typedef struct CajaWindow CajaWindow
Definition at line 54 of file caja-application.h.
Function Documentation
caja_application_close_all_navigation_windows()
void caja_application_close_all_navigation_windows (CajaApplication * self)
Definition at line 759 of file caja-application.c.
References CAJA_IS_NAVIGATION_WINDOW, CAJA_WINDOW, caja_window_close(), list_copy(), _List::next, and NULL.
caja_application_close_all_spatial_windows()
void caja_application_close_all_spatial_windows (void)
Definition at line 892 of file caja-application.c.
References CAJA_IS_SPATIAL_WINDOW, CAJA_WINDOW, caja_window_close(), list_copy(), _List::next, and NULL.
caja_application_close_parent_windows()
void caja_application_close_parent_windows (CajaSpatialWindow * window)
Definition at line 873 of file caja-application.c.
References CAJA_IS_SPATIAL_WINDOW, CAJA_WINDOW, and caja_window_close().
caja_application_create_navigation_window()
CajaWindow * caja_application_create_navigation_window (CajaApplication * application, GdkScreen * screen)
Definition at line 1040 of file caja-application.c.
References caja_debug_log(), CAJA_DEBUG_LOG_DOMAIN_USER, CAJA_IS_APPLICATION, CAJA_NAVIGATION_WINDOW_MIN_HEIGHT, CAJA_NAVIGATION_WINDOW_MIN_WIDTH, CAJA_TYPE_NAVIGATION_WINDOW, caja_window_state, CAJA_WINDOW_STATE_GEOMETRY, CAJA_WINDOW_STATE_MAXIMIZED, eel_gtk_window_set_initial_geometry_from_string(), FALSE, NULL, and TRUE.
Referenced by caja_application_open_location(), caja_connect_server_dialog_display_location_async(), caja_window_new_window(), and caja_window_slot_open_location_full().
caja_application_get_spatial_window()
CajaWindow * caja_application_get_spatial_window (CajaApplication * application, CajaWindow * requesting_window, const char * startup_id, GFile * location, GdkScreen * screen, gboolean * existing)
Definition at line 974 of file caja-application.c.
References caja_debug_log(), CAJA_DEBUG_LOG_DOMAIN_USER, CAJA_IS_APPLICATION, CAJA_TYPE_SPATIAL_WINDOW, CAJA_WINDOW, FALSE, NULL, and TRUE.
Referenced by caja_connect_server_dialog_display_location_async(), and caja_window_slot_open_location_full().
caja_application_get_type()
GType caja_application_get_type (void)
caja_application_new()
CajaApplication * caja_application_new (void)
Definition at line 2380 of file caja-application.c.
References CAJA_TYPE_APPLICATION, NULL, and TRUE.
Referenced by main().
caja_application_open_location()
void caja_application_open_location (CajaApplication * application, GFile * location, GFile * selection, const char * startup_id, const gboolean open_in_tabs)
Definition at line 407 of file caja-application.c.
References caja_application_create_navigation_window(), caja_file_list_free(), caja_window_get_active_slot(), CAJA_WINDOW_OPEN_FLAG_NEW_WINDOW, caja_window_slot_open_location_full(), and NULL.