MATE Desktop Environment: caja-spatial-window.h File Reference
caja-spatial-window.h File Reference
#include "caja-window.h"
#include "caja-window-private.h"
Classes
struct _CajaSpatialWindow
struct _CajaSpatialWindowClass
Macros
#define CAJA_TYPE_SPATIAL_WINDOW caja_spatial_window_get_type()
#define CAJA_SPATIAL_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_SPATIAL_WINDOW, CajaSpatialWindow))
#define CAJA_SPATIAL_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_SPATIAL_WINDOW, CajaSpatialWindowClass))
#define CAJA_IS_SPATIAL_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_SPATIAL_WINDOW))
#define CAJA_IS_SPATIAL_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_SPATIAL_WINDOW))
#define CAJA_SPATIAL_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_SPATIAL_WINDOW, CajaSpatialWindowClass))
Typedefs
typedef struct _CajaSpatialWindowClass CajaSpatialWindowClass
typedef struct _CajaSpatialWindowPrivate CajaSpatialWindowPrivate
Functions
GType caja_spatial_window_get_type (void)
void caja_spatial_window_set_location_button (CajaSpatialWindow *window, GFile *location)
Macro Definition Documentation
CAJA_IS_SPATIAL_WINDOW
#define CAJA_IS_SPATIAL_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_SPATIAL_WINDOW))
Definition at line 38 of file caja-spatial-window.h.
CAJA_IS_SPATIAL_WINDOW_CLASS
#define CAJA_IS_SPATIAL_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_SPATIAL_WINDOW))
Definition at line 40 of file caja-spatial-window.h.
CAJA_SPATIAL_WINDOW
#define CAJA_SPATIAL_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_SPATIAL_WINDOW, CajaSpatialWindow))
Definition at line 34 of file caja-spatial-window.h.
CAJA_SPATIAL_WINDOW_CLASS
#define CAJA_SPATIAL_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_SPATIAL_WINDOW, CajaSpatialWindowClass))
Definition at line 36 of file caja-spatial-window.h.
CAJA_SPATIAL_WINDOW_GET_CLASS
#define CAJA_SPATIAL_WINDOW_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_SPATIAL_WINDOW, CajaSpatialWindowClass))
Definition at line 42 of file caja-spatial-window.h.
CAJA_TYPE_SPATIAL_WINDOW
#define CAJA_TYPE_SPATIAL_WINDOW caja_spatial_window_get_type()
Definition at line 33 of file caja-spatial-window.h.
Typedef Documentation
CajaSpatialWindowClass
typedef struct _CajaSpatialWindowClass CajaSpatialWindowClass
Definition at line 49 of file caja-spatial-window.h.
CajaSpatialWindowPrivate
typedef struct _CajaSpatialWindowPrivate CajaSpatialWindowPrivate
Definition at line 50 of file caja-spatial-window.h.
Function Documentation
caja_spatial_window_get_type()
GType caja_spatial_window_get_type (void)
caja_spatial_window_set_location_button()
void caja_spatial_window_set_location_button (CajaSpatialWindow * window, GFile * location)
Definition at line 833 of file caja-spatial-window.c.
References caja_file_get(), caja_file_get_display_name(), caja_file_get_file_info_error(), caja_file_get_icon_surface(), CAJA_FILE_ICON_FLAGS_IGNORE_VISITING, caja_get_icon_size_for_stock_size(), _CajaSpatialWindow::details, error, FALSE, name, NULL, and TRUE.