MATE Desktop Environment: caja-desktop-window.h File Reference
caja-desktop-window.h File Reference
#include "caja-window.h"
#include "caja-application.h"
#include "caja-spatial-window.h"
#include <gtk/gtk-a11y.h>
Classes
struct CajaDesktopWindow
struct CajaDesktopWindowClass
struct CajaDesktopWindowAccessible
struct CajaDesktopWindowAccessibleClass
Macros
#define CAJA_TYPE_DESKTOP_WINDOW caja_desktop_window_get_type()
#define CAJA_DESKTOP_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_DESKTOP_WINDOW, CajaDesktopWindow))
#define CAJA_DESKTOP_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_DESKTOP_WINDOW, CajaDesktopWindowClass))
#define CAJA_IS_DESKTOP_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_DESKTOP_WINDOW))
#define CAJA_IS_DESKTOP_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_DESKTOP_WINDOW))
#define CAJA_DESKTOP_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_DESKTOP_WINDOW, CajaDesktopWindowClass))
#define CAJA_TYPE_DESKTOP_WINDOW_ACCESSIBLE caja_desktop_window_accessible_get_type()
Typedefs
typedef struct _CajaDesktopWindowPrivate CajaDesktopWindowPrivate
Functions
GType caja_desktop_window_get_type (void)
CajaDesktopWindow * caja_desktop_window_new (CajaApplication *application, GdkScreen *screen)
void caja_desktop_window_update_directory (CajaDesktopWindow *window)
gboolean caja_desktop_window_loaded (CajaDesktopWindow *window)
Macro Definition Documentation
CAJA_DESKTOP_WINDOW
#define CAJA_DESKTOP_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_DESKTOP_WINDOW, CajaDesktopWindow))
Definition at line 38 of file caja-desktop-window.h.
CAJA_DESKTOP_WINDOW_CLASS
#define CAJA_DESKTOP_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_DESKTOP_WINDOW, CajaDesktopWindowClass))
Definition at line 40 of file caja-desktop-window.h.
CAJA_DESKTOP_WINDOW_GET_CLASS
#define CAJA_DESKTOP_WINDOW_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_DESKTOP_WINDOW, CajaDesktopWindowClass))
Definition at line 46 of file caja-desktop-window.h.
CAJA_IS_DESKTOP_WINDOW
#define CAJA_IS_DESKTOP_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_DESKTOP_WINDOW))
Definition at line 42 of file caja-desktop-window.h.
CAJA_IS_DESKTOP_WINDOW_CLASS
#define CAJA_IS_DESKTOP_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_DESKTOP_WINDOW))
Definition at line 44 of file caja-desktop-window.h.
CAJA_TYPE_DESKTOP_WINDOW
#define CAJA_TYPE_DESKTOP_WINDOW caja_desktop_window_get_type()
Definition at line 37 of file caja-desktop-window.h.
CAJA_TYPE_DESKTOP_WINDOW_ACCESSIBLE
#define CAJA_TYPE_DESKTOP_WINDOW_ACCESSIBLE caja_desktop_window_accessible_get_type()
Definition at line 69 of file caja-desktop-window.h.
Typedef Documentation
CajaDesktopWindowPrivate
typedef struct _CajaDesktopWindowPrivate CajaDesktopWindowPrivate
Definition at line 49 of file caja-desktop-window.h.
Function Documentation
caja_desktop_window_get_type()
GType caja_desktop_window_get_type (void)
Referenced by caja_desktop_window_new().
caja_desktop_window_loaded()
gboolean caja_desktop_window_loaded (CajaDesktopWindow * window)
Definition at line 434 of file caja-desktop-window.c.
References CajaDesktopWindow::details.
Referenced by caja_window_slot_open_location_full().
caja_desktop_window_new()
CajaDesktopWindow * caja_desktop_window_new (CajaApplication * application, GdkScreen * screen)
Definition at line 187 of file caja-desktop-window.c.
References _, CAJA_DESKTOP_WINDOW, caja_desktop_window_get_type(), caja_desktop_window_update_directory(), FALSE, GDK_IS_X11_DISPLAY, NULL, and TRUE.
caja_desktop_window_update_directory()
void caja_desktop_window_update_directory (CajaDesktopWindow * window)
Definition at line 143 of file caja-desktop-window.c.
References CAJA_IS_DESKTOP_WINDOW, CAJA_WINDOW, caja_window_go_to(), CajaDesktopWindow::details, EEL_DESKTOP_URI, and TRUE.
Referenced by caja_desktop_window_new().