MATE Desktop Environment: caja-search-engine.h File Reference
caja-search-engine.h File Reference
#include <glib-object.h>
#include "caja-query.h"
Classes
struct CajaSearchEngine
struct CajaSearchEngineClass
Macros
#define CAJA_TYPE_SEARCH_ENGINE (caja_search_engine_get_type ())
#define CAJA_SEARCH_ENGINE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_SEARCH_ENGINE, CajaSearchEngine))
#define CAJA_SEARCH_ENGINE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_SEARCH_ENGINE, CajaSearchEngineClass))
#define CAJA_IS_SEARCH_ENGINE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_SEARCH_ENGINE))
#define CAJA_IS_SEARCH_ENGINE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_SEARCH_ENGINE))
#define CAJA_SEARCH_ENGINE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_SEARCH_ENGINE, CajaSearchEngineClass))
Typedefs
typedef struct CajaSearchEngine CajaSearchEngine
Functions
GType caja_search_engine_get_type (void)
gboolean caja_search_engine_enabled (void)
CajaSearchEngine * caja_search_engine_new (void)
void caja_search_engine_set_query (CajaSearchEngine *engine, CajaQuery *query)
void caja_search_engine_set_show_hidden_files (CajaSearchEngine *engine, gboolean show_hidden_files)
void caja_search_engine_start (CajaSearchEngine *engine)
void caja_search_engine_stop (CajaSearchEngine *engine)
gboolean caja_search_engine_is_indexed (CajaSearchEngine *engine)
void caja_search_engine_hits_added (CajaSearchEngine *engine, GList *hits)
void caja_search_engine_hits_subtracted (CajaSearchEngine *engine, GList *hits)
void caja_search_engine_finished (CajaSearchEngine *engine)
void caja_search_engine_error (CajaSearchEngine *engine, const char *error_message)
Macro Definition Documentation
CAJA_IS_SEARCH_ENGINE
#define CAJA_IS_SEARCH_ENGINE (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_SEARCH_ENGINE))
Definition at line 34 of file caja-search-engine.h.
CAJA_IS_SEARCH_ENGINE_CLASS
#define CAJA_IS_SEARCH_ENGINE_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_SEARCH_ENGINE))
Definition at line 35 of file caja-search-engine.h.
CAJA_SEARCH_ENGINE
#define CAJA_SEARCH_ENGINE (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_SEARCH_ENGINE, CajaSearchEngine))
Definition at line 32 of file caja-search-engine.h.
CAJA_SEARCH_ENGINE_CLASS
#define CAJA_SEARCH_ENGINE_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_SEARCH_ENGINE, CajaSearchEngineClass))
Definition at line 33 of file caja-search-engine.h.
CAJA_SEARCH_ENGINE_GET_CLASS
#define CAJA_SEARCH_ENGINE_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_SEARCH_ENGINE, CajaSearchEngineClass))
Definition at line 36 of file caja-search-engine.h.
CAJA_TYPE_SEARCH_ENGINE
#define CAJA_TYPE_SEARCH_ENGINE (caja_search_engine_get_type ())
Definition at line 31 of file caja-search-engine.h.
Typedef Documentation
CajaSearchEngine
typedef struct CajaSearchEngine CajaSearchEngine
Function Documentation
caja_search_engine_enabled()
gboolean caja_search_engine_enabled (void)
caja_search_engine_error()
void caja_search_engine_error (CajaSearchEngine * engine, const char * error_message)
Definition at line 189 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, engine, and ERROR.
caja_search_engine_finished()
void caja_search_engine_finished (CajaSearchEngine * engine)
Definition at line 181 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, engine, and FINISHED.
caja_search_engine_get_type()
GType caja_search_engine_get_type (void)
caja_search_engine_hits_added()
void caja_search_engine_hits_added (CajaSearchEngine * engine, GList * hits)
Definition at line 165 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, engine, and HITS_ADDED.
caja_search_engine_hits_subtracted()
void caja_search_engine_hits_subtracted (CajaSearchEngine * engine, GList * hits)
Definition at line 173 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, engine, and HITS_SUBTRACTED.
caja_search_engine_is_indexed()
gboolean caja_search_engine_is_indexed (CajaSearchEngine * engine)
Definition at line 156 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, CAJA_SEARCH_ENGINE_GET_CLASS, engine, FALSE, and NULL.
Referenced by caja_search_directory_is_indexed().
caja_search_engine_new()
CajaSearchEngine * caja_search_engine_new (void)
Definition at line 98 of file caja-search-engine.c.
References caja_search_engine_beagle_new(), caja_search_engine_simple_new(), caja_search_engine_tracker_new(), and engine.
Referenced by main().
caja_search_engine_set_query()
void caja_search_engine_set_query (CajaSearchEngine * engine, CajaQuery * query)
Definition at line 119 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, CAJA_SEARCH_ENGINE_GET_CLASS, engine, and NULL.
Referenced by main().
caja_search_engine_set_show_hidden_files()
void caja_search_engine_set_show_hidden_files (CajaSearchEngine * engine, gboolean show_hidden_files)
Definition at line 128 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, CAJA_SEARCH_ENGINE_GET_CLASS, engine, and NULL.
caja_search_engine_start()
void caja_search_engine_start (CajaSearchEngine * engine)
Definition at line 138 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, CAJA_SEARCH_ENGINE_GET_CLASS, engine, and NULL.
Referenced by main().
caja_search_engine_stop()
void caja_search_engine_stop (CajaSearchEngine * engine)
Definition at line 147 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, CAJA_SEARCH_ENGINE_GET_CLASS, engine, and NULL.