MATE Desktop Environment: caja-clipboard-monitor.h File Reference
caja-clipboard-monitor.h File Reference
#include <gtk/gtk.h>
Classes
struct CajaClipboardMonitor
struct CajaClipboardMonitorClass
struct CajaClipboardInfo
Macros
#define CAJA_TYPE_CLIPBOARD_MONITOR caja_clipboard_monitor_get_type()
#define CAJA_CLIPBOARD_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_CLIPBOARD_MONITOR, CajaClipboardMonitor))
#define CAJA_CLIPBOARD_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_CLIPBOARD_MONITOR, CajaClipboardMonitorClass))
#define CAJA_IS_CLIPBOARD_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_CLIPBOARD_MONITOR))
#define CAJA_IS_CLIPBOARD_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_CLIPBOARD_MONITOR))
#define CAJA_CLIPBOARD_MONITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_CLIPBOARD_MONITOR, CajaClipboardMonitorClass))
Typedefs
typedef struct _CajaClipboardMonitorPrivate CajaClipboardMonitorPrivate
typedef struct CajaClipboardInfo CajaClipboardInfo
Functions
GType caja_clipboard_monitor_get_type (void)
CajaClipboardMonitor * caja_clipboard_monitor_get (void)
void caja_clipboard_monitor_set_clipboard_info (CajaClipboardMonitor *monitor, CajaClipboardInfo *info)
CajaClipboardInfo * caja_clipboard_monitor_get_clipboard_info (CajaClipboardMonitor *monitor)
void caja_clipboard_monitor_emit_changed (void)
void caja_clear_clipboard_callback (GtkClipboard *clipboard, gpointer user_data)
void caja_get_clipboard_callback (GtkClipboard *clipboard, GtkSelectionData *selection_data, guint info, gpointer user_data)
Macro Definition Documentation
CAJA_CLIPBOARD_MONITOR
#define CAJA_CLIPBOARD_MONITOR (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_CLIPBOARD_MONITOR, CajaClipboardMonitor))
Definition at line 31 of file caja-clipboard-monitor.h.
CAJA_CLIPBOARD_MONITOR_CLASS
#define CAJA_CLIPBOARD_MONITOR_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_CLIPBOARD_MONITOR, CajaClipboardMonitorClass))
Definition at line 33 of file caja-clipboard-monitor.h.
CAJA_CLIPBOARD_MONITOR_GET_CLASS
#define CAJA_CLIPBOARD_MONITOR_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_CLIPBOARD_MONITOR, CajaClipboardMonitorClass))
Definition at line 39 of file caja-clipboard-monitor.h.
CAJA_IS_CLIPBOARD_MONITOR
#define CAJA_IS_CLIPBOARD_MONITOR (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_CLIPBOARD_MONITOR))
Definition at line 35 of file caja-clipboard-monitor.h.
CAJA_IS_CLIPBOARD_MONITOR_CLASS
#define CAJA_IS_CLIPBOARD_MONITOR_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_CLIPBOARD_MONITOR))
Definition at line 37 of file caja-clipboard-monitor.h.
CAJA_TYPE_CLIPBOARD_MONITOR
#define CAJA_TYPE_CLIPBOARD_MONITOR caja_clipboard_monitor_get_type()
Definition at line 30 of file caja-clipboard-monitor.h.
Typedef Documentation
CajaClipboardInfo
typedef struct CajaClipboardInfo CajaClipboardInfo
Definition at line 43 of file caja-clipboard-monitor.h.
CajaClipboardMonitorPrivate
typedef struct _CajaClipboardMonitorPrivate CajaClipboardMonitorPrivate
Definition at line 42 of file caja-clipboard-monitor.h.
Function Documentation
caja_clear_clipboard_callback()
void caja_clear_clipboard_callback (GtkClipboard * clipboard, gpointer user_data)
Definition at line 217 of file caja-clipboard-monitor.c.
References caja_clipboard_monitor_get(), caja_clipboard_monitor_set_clipboard_info(), and NULL.
caja_clipboard_monitor_emit_changed()
void caja_clipboard_monitor_emit_changed (void)
Definition at line 96 of file caja-clipboard-monitor.c.
References caja_clipboard_monitor_get(), and CLIPBOARD_CHANGED.
Referenced by caja_clipboard_monitor_get(), and caja_clipboard_monitor_set_clipboard_info().
caja_clipboard_monitor_get()
CajaClipboardMonitor * caja_clipboard_monitor_get (void)
Definition at line 79 of file caja-clipboard-monitor.c.
References CAJA_CLIPBOARD_MONITOR, caja_clipboard_monitor_emit_changed(), CAJA_TYPE_CLIPBOARD_MONITOR, eel_debug_call_at_shutdown(), and NULL.
Referenced by caja_clear_clipboard_callback(), caja_clipboard_monitor_emit_changed(), and caja_get_clipboard_callback().
caja_clipboard_monitor_get_clipboard_info()
CajaClipboardInfo * caja_clipboard_monitor_get_clipboard_info (CajaClipboardMonitor * monitor)
Definition at line 211 of file caja-clipboard-monitor.c.
References CajaClipboardMonitor::details.
Referenced by caja_get_clipboard_callback().
caja_clipboard_monitor_get_type()
GType caja_clipboard_monitor_get_type (void)
caja_clipboard_monitor_set_clipboard_info()
void caja_clipboard_monitor_set_clipboard_info (CajaClipboardMonitor * monitor, CajaClipboardInfo * info)
Definition at line 194 of file caja-clipboard-monitor.c.
References caja_clipboard_monitor_emit_changed(), CLIPBOARD_INFO, CajaClipboardMonitor::details, and NULL.
Referenced by caja_clear_clipboard_callback().
caja_get_clipboard_callback()
void caja_get_clipboard_callback (GtkClipboard * clipboard, GtkSelectionData * selection_data, guint info, gpointer user_data)
Definition at line 286 of file caja-clipboard-monitor.c.
References caja_clipboard_monitor_get(), caja_clipboard_monitor_get_clipboard_info(), caja_file_get_uri(), FALSE, CajaClipboardInfo::files, NULL, and TRUE.