MATE Desktop Environment: caja-module.c File Reference
caja-module.c File Reference
#include <config.h>
#include <gmodule.h>
#include <eel/eel-gtk-macros.h>
#include <eel/eel-debug.h>
#include "caja-module.h"
#include "caja-extensions.h"
Macros
#define CAJA_TYPE_MODULE (caja_module_get_type ())
#define CAJA_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_MODULE, CajaModule))
#define parent_class caja_module_parent_class
Typedefs
typedef struct _CajaModule CajaModule
typedef struct _CajaModuleClass CajaModuleClass
Functions
G_DEFINE_TYPE (CajaModule, caja_module, G_TYPE_TYPE_MODULE)
void caja_module_setup (void)
GList * caja_module_get_extensions_for_type (GType type)
void caja_module_extension_list_free (GList *extensions)
GObject * caja_module_add_type (GType type)
Macro Definition Documentation
CAJA_MODULE
#define CAJA_MODULE (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_MODULE, CajaModule))
Definition at line 34 of file caja/libcaja-private/caja-module.c.
CAJA_TYPE_MODULE
#define CAJA_TYPE_MODULE (caja_module_get_type ())
Definition at line 33 of file caja/libcaja-private/caja-module.c.
parent_class
#define parent_class caja_module_parent_class
Definition at line 66 of file caja/libcaja-private/caja-module.c.
Typedef Documentation
CajaModule
typedef struct _CajaModule CajaModule
Definition at line 36 of file caja/libcaja-private/caja-module.c.
CajaModuleClass
typedef struct _CajaModuleClass CajaModuleClass
Definition at line 37 of file caja/libcaja-private/caja-module.c.
Function Documentation
caja_module_add_type()
GObject * caja_module_add_type (GType type)
Definition at line 317 of file caja/libcaja-private/caja-module.c.
References NULL, and type.
Referenced by caja_bookmarks_sidebar_register(), caja_emblem_sidebar_register(), caja_history_sidebar_register(), caja_image_properties_page_register(), caja_information_panel_register(), caja_notes_viewer_register(), caja_places_sidebar_register(), and fm_tree_view_register().
caja_module_extension_list_free()
void caja_module_extension_list_free (GList * extensions)
Definition at line 304 of file caja/libcaja-private/caja-module.c.
References NULL.
caja_module_get_extensions_for_type()
GList * caja_module_get_extensions_for_type (GType type)
Definition at line 285 of file caja/libcaja-private/caja-module.c.
References NULL, and type.
caja_module_setup()
void caja_module_setup (void)
Definition at line 258 of file caja/libcaja-private/caja-module.c.
References eel_debug_call_at_shutdown(), FALSE, NULL, and TRUE.
Referenced by main().
G_DEFINE_TYPE()
G_DEFINE_TYPE (CajaModule , caja_module , G_TYPE_TYPE_MODULE)