MATE Desktop Environment: caja-trash-monitor.h File Reference
caja-trash-monitor.h File Reference
#include <gtk/gtk.h>
#include <gio/gio.h>
Classes
struct CajaTrashMonitor
struct CajaTrashMonitorClass
Macros
#define CAJA_TYPE_TRASH_MONITOR caja_trash_monitor_get_type()
#define CAJA_TRASH_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_TRASH_MONITOR, CajaTrashMonitor))
#define CAJA_TRASH_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_TRASH_MONITOR, CajaTrashMonitorClass))
#define CAJA_IS_TRASH_MONITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_TRASH_MONITOR))
#define CAJA_IS_TRASH_MONITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_TRASH_MONITOR))
#define CAJA_TRASH_MONITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_TRASH_MONITOR, CajaTrashMonitorClass))
Typedefs
typedef struct CajaTrashMonitor CajaTrashMonitor
typedef struct CajaTrashMonitorClass CajaTrashMonitorClass
typedef struct _CajaTrashMonitorPrivate CajaTrashMonitorPrivate
Functions
GType caja_trash_monitor_get_type (void)
CajaTrashMonitor * caja_trash_monitor_get (void)
gboolean caja_trash_monitor_is_empty (void)
GIcon * caja_trash_monitor_get_icon (void)
Macro Definition Documentation
CAJA_IS_TRASH_MONITOR
#define CAJA_IS_TRASH_MONITOR (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_TRASH_MONITOR))
Definition at line 41 of file caja-trash-monitor.h.
CAJA_IS_TRASH_MONITOR_CLASS
#define CAJA_IS_TRASH_MONITOR_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_TRASH_MONITOR))
Definition at line 43 of file caja-trash-monitor.h.
CAJA_TRASH_MONITOR
#define CAJA_TRASH_MONITOR (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_TRASH_MONITOR, CajaTrashMonitor))
Definition at line 37 of file caja-trash-monitor.h.
CAJA_TRASH_MONITOR_CLASS
#define CAJA_TRASH_MONITOR_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_TRASH_MONITOR, CajaTrashMonitorClass))
Definition at line 39 of file caja-trash-monitor.h.
CAJA_TRASH_MONITOR_GET_CLASS
#define CAJA_TRASH_MONITOR_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_TRASH_MONITOR, CajaTrashMonitorClass))
Definition at line 45 of file caja-trash-monitor.h.
CAJA_TYPE_TRASH_MONITOR
#define CAJA_TYPE_TRASH_MONITOR caja_trash_monitor_get_type()
Definition at line 36 of file caja-trash-monitor.h.
Typedef Documentation
CajaTrashMonitor
typedef struct CajaTrashMonitor CajaTrashMonitor
Definition at line 32 of file caja-trash-monitor.h.
CajaTrashMonitorClass
typedef struct CajaTrashMonitorClass CajaTrashMonitorClass
Definition at line 33 of file caja-trash-monitor.h.
CajaTrashMonitorPrivate
typedef struct _CajaTrashMonitorPrivate CajaTrashMonitorPrivate
Definition at line 34 of file caja-trash-monitor.h.
Function Documentation
caja_trash_monitor_get()
CajaTrashMonitor * caja_trash_monitor_get (void)
Definition at line 210 of file caja-trash-monitor.c.
References CAJA_TRASH_MONITOR, CAJA_TYPE_TRASH_MONITOR, eel_debug_call_at_shutdown(), and NULL.
Referenced by caja_desktop_link_new(), caja_trash_monitor_get_icon(), caja_trash_monitor_is_empty(), and caja_window_finalize_menus().
caja_trash_monitor_get_icon()
GIcon * caja_trash_monitor_get_icon (void)
Definition at line 234 of file caja-trash-monitor.c.
References caja_trash_monitor_get(), CajaTrashMonitor::details, and NULL.
Referenced by caja_desktop_link_new().
caja_trash_monitor_get_type()
GType caja_trash_monitor_get_type (void)
caja_trash_monitor_is_empty()
gboolean caja_trash_monitor_is_empty (void)
Definition at line 225 of file caja-trash-monitor.c.
References caja_trash_monitor_get(), and CajaTrashMonitor::details.