MATE Desktop Environment: caja-undostack-manager.c File Reference
caja-undostack-manager.c File Reference
#include "caja-undostack-manager.h"
#include "caja-file-operations.h"
#include "caja-file.h"
#include <gio/gio.h>
#include <glib/gprintf.h>
#include <glib-object.h>
#include <glib/gi18n.h>
#include <locale.h>
#include <gdk/gdk.h>
Enumerations
enum { PROP_UNDOSTACK_MANAGER_0 , PROP_UNDO_LEVELS }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (CajaUndoStackManager, caja_undostack_manager, G_TYPE_OBJECT)
CajaUndoStackManager * caja_undostack_manager_instance (void)
gboolean caja_undostack_manager_is_undo_redo (CajaUndoStackManager *manager)
void caja_undostack_manager_request_menu_update (CajaUndoStackManager *manager)
void caja_undostack_manager_redo (CajaUndoStackManager *manager, GtkWidget *parent_view, CajaUndostackFinishCallback cb)
void caja_undostack_manager_undo (CajaUndoStackManager *manager, GtkWidget *parent_view, CajaUndostackFinishCallback cb)
void caja_undostack_manager_add_action (CajaUndoStackManager *manager, CajaUndoStackActionData *action)
void caja_undostack_manager_trash_has_emptied (CajaUndoStackManager *manager)
guint64 caja_undostack_manager_get_file_modification_time (GFile *file)
CajaUndoStackActionData * caja_undostack_manager_data_new (CajaUndoStackActionType type, gint items_count)
void caja_undostack_manager_data_set_src_dir (CajaUndoStackActionData *data, GFile *src)
void caja_undostack_manager_data_set_dest_dir (CajaUndoStackActionData *data, GFile *dest)
void caja_undostack_manager_data_add_origin_target_pair (CajaUndoStackActionData *data, GFile *origin, GFile *target)
void caja_undostack_manager_data_add_trashed_file (CajaUndoStackActionData *data, GFile *file, guint64 mtime)
void caja_undostack_manager_data_add_file_permissions (CajaUndoStackActionData *data, GFile *file, guint32 permission)
void caja_undostack_manager_data_set_file_permissions (CajaUndoStackActionData *data, char *uri, guint32 current_permissions, guint32 new_permissions)
void caja_undostack_manager_data_set_owner_change_information (CajaUndoStackActionData *data, char *uri, const char *current_user, const char *new_user)
void caja_undostack_manager_data_set_group_change_information (CajaUndoStackActionData *data, char *uri, const char *current_group, const char *new_group)
void caja_undostack_manager_data_set_recursive_permissions (CajaUndoStackActionData *data, guint32 file_permissions, guint32 file_mask, guint32 dir_permissions, guint32 dir_mask)
void caja_undostack_manager_data_take_create_data (CajaUndoStackActionData *data, char *target_uri, char *template)
void caja_undostack_manager_data_set_rename_information (CajaUndoStackActionData *data, GFile *old_file, GFile *new_file)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_UNDOSTACK_MANAGER_0
PROP_UNDO_LEVELS
Definition at line 111 of file caja-undostack-manager.c.
Function Documentation
caja_undostack_manager_add_action()
void caja_undostack_manager_add_action (CajaUndoStackManager * manager, CajaUndoStackActionData * action)
Adds an operation to the stack
Definition at line 738 of file caja-undostack-manager.c.
References action, NULL, and _CajaUndoStackManager::priv.
Referenced by caja_file_operation_free(), caja_file_set_group(), caja_file_set_owner(), and caja_file_set_permissions().
caja_undostack_manager_data_add_file_permissions()
void caja_undostack_manager_data_add_file_permissions (CajaUndoStackActionData * data, GFile * file, guint32 permission)
Pushes a recursive permission change data in an existing undo data container
Definition at line 957 of file caja-undostack-manager.c.
References data, and TRUE.
caja_undostack_manager_data_add_origin_target_pair()
void caja_undostack_manager_data_add_origin_target_pair (CajaUndoStackActionData * data, GFile * origin, GFile * target)
Pushes an origin, target pair in an existing undo data container
Definition at line 917 of file caja-undostack-manager.c.
References data, and TRUE.
caja_undostack_manager_data_add_trashed_file()
void caja_undostack_manager_data_add_trashed_file (CajaUndoStackActionData * data, GFile * file, guint64 mtime)
Pushes an trashed file with modification time in an existing undo data container
Definition at line 936 of file caja-undostack-manager.c.
References data, and TRUE.
caja_undostack_manager_data_new()
CajaUndoStackActionData * caja_undostack_manager_data_new (CajaUndoStackActionType type, gint items_count)
Returns a new undo data container
Definition at line 869 of file caja-undostack-manager.c.
References CAJA_UNDOSTACK_MOVETOTRASH, CAJA_UNDOSTACK_RECURSIVESETPERMISSIONS, data, and type.
Referenced by caja_file_operations_copy(), caja_file_operations_duplicate(), caja_file_operations_link(), caja_file_operations_move(), caja_file_operations_new_file(), caja_file_operations_new_file_from_template(), caja_file_operations_new_folder(), caja_file_rename(), caja_file_set_group(), caja_file_set_owner(), caja_file_set_permissions(), and caja_file_set_permissions_recursive().
caja_undostack_manager_data_set_dest_dir()
void caja_undostack_manager_data_set_dest_dir (CajaUndoStackActionData * data, GFile * dest)
Sets the destination directory
Definition at line 905 of file caja-undostack-manager.c.
References data, and dest.
Referenced by caja_file_operations_copy(), caja_file_operations_duplicate(), caja_file_operations_link(), caja_file_operations_move(), and caja_file_set_permissions_recursive().
caja_undostack_manager_data_set_file_permissions()
void caja_undostack_manager_data_set_file_permissions (CajaUndoStackActionData * data, char * uri, guint32 current_permissions, guint32 new_permissions)
Sets the original file permission in an existing undo data container
Definition at line 979 of file caja-undostack-manager.c.
References data, and TRUE.
Referenced by caja_file_set_permissions().
caja_undostack_manager_data_set_group_change_information()
void caja_undostack_manager_data_set_group_change_information (CajaUndoStackActionData * data, char * uri, const char * current_group, const char * new_group)
Sets the change group information in an existing undo data container
Definition at line 1017 of file caja-undostack-manager.c.
References data, and TRUE.
Referenced by caja_file_set_group().
caja_undostack_manager_data_set_owner_change_information()
void caja_undostack_manager_data_set_owner_change_information (CajaUndoStackActionData * data, char * uri, const char * current_user, const char * new_user)
Sets the change owner information in an existing undo data container
Definition at line 998 of file caja-undostack-manager.c.
References data, and TRUE.
Referenced by caja_file_set_owner().
caja_undostack_manager_data_set_recursive_permissions()
void caja_undostack_manager_data_set_recursive_permissions (CajaUndoStackActionData * data, guint32 file_permissions, guint32 file_mask, guint32 dir_permissions, guint32 dir_mask)
Sets the permission change mask
Definition at line 1036 of file caja-undostack-manager.c.
References data, and TRUE.
Referenced by caja_file_set_permissions_recursive().
caja_undostack_manager_data_set_rename_information()
void caja_undostack_manager_data_set_rename_information (CajaUndoStackActionData * data, GFile * old_file, GFile * new_file)
Sets rename information
Definition at line 1074 of file caja-undostack-manager.c.
References data, and TRUE.
caja_undostack_manager_data_set_src_dir()
void caja_undostack_manager_data_set_src_dir (CajaUndoStackActionData * data, GFile * src)
Sets the source directory
Definition at line 892 of file caja-undostack-manager.c.
References data.
Referenced by caja_file_operations_copy(), caja_file_operations_duplicate(), caja_file_operations_link(), and caja_file_operations_move().
caja_undostack_manager_data_take_create_data()
void caja_undostack_manager_data_take_create_data (CajaUndoStackActionData * data, char * target_uri, char * template)
Takes create file information Note: The caller must not free target_uri and template after calling this function.
Definition at line 1058 of file caja-undostack-manager.c.
References data, and TRUE.
caja_undostack_manager_get_file_modification_time()
guint64 caja_undostack_manager_get_file_modification_time (GFile * file)
Returns the modification time for the given file (used for undo trash)
Definition at line 846 of file caja-undostack-manager.c.
References FALSE, and NULL.
caja_undostack_manager_instance()
CajaUndoStackManager * caja_undostack_manager_instance (void)
Returns the undo stack manager instance (singleton pattern)
Definition at line 348 of file caja-undostack-manager.c.
References NULL, and TYPE_CAJA_UNDOSTACK_MANAGER.
Referenced by caja_file_operation_free(), caja_file_operations_copy(), caja_file_operations_duplicate(), caja_file_operations_link(), caja_file_operations_move(), caja_file_operations_new_file(), caja_file_operations_new_file_from_template(), caja_file_operations_new_folder(), caja_file_rename(), caja_file_set_group(), caja_file_set_owner(), caja_file_set_permissions(), and caja_file_set_permissions_recursive().
caja_undostack_manager_is_undo_redo()
gboolean caja_undostack_manager_is_undo_redo (CajaUndoStackManager * manager)
True if undoing / redoing
Definition at line 364 of file caja-undostack-manager.c.
References FALSE, _CajaUndoStackManager::priv, and TRUE.
Referenced by caja_file_operations_copy(), caja_file_operations_duplicate(), caja_file_operations_link(), caja_file_operations_move(), caja_file_operations_new_file(), caja_file_operations_new_file_from_template(), caja_file_operations_new_folder(), caja_file_rename(), caja_file_set_group(), caja_file_set_owner(), caja_file_set_permissions(), and caja_file_set_permissions_recursive().
caja_undostack_manager_redo()
void caja_undostack_manager_redo (CajaUndoStackManager * manager, GtkWidget * parent_view, CajaUndostackFinishCallback cb)
Redoes the last file operation
Definition at line 385 of file caja-undostack-manager.c.
References action, caja_file_get_by_uri(), caja_file_operations_copy(), caja_file_operations_duplicate(), caja_file_operations_link(), caja_file_operations_move(), caja_file_operations_new_file(), caja_file_operations_new_file_from_template(), caja_file_operations_new_folder(), caja_file_operations_trash_or_delete(), caja_file_rename(), caja_file_set_group(), caja_file_set_owner(), caja_file_set_permissions(), caja_file_set_permissions_recursive(), CAJA_UNDOSTACK_CHANGEGROUP, CAJA_UNDOSTACK_CHANGEOWNER, CAJA_UNDOSTACK_COPY, CAJA_UNDOSTACK_CREATEEMPTYFILE, CAJA_UNDOSTACK_CREATEFILEFROMTEMPLATE, CAJA_UNDOSTACK_CREATEFOLDER, CAJA_UNDOSTACK_CREATELINK, CAJA_UNDOSTACK_DELETE, CAJA_UNDOSTACK_DUPLICATE, CAJA_UNDOSTACK_MOVE, CAJA_UNDOSTACK_MOVETOTRASH, CAJA_UNDOSTACK_RECURSIVESETPERMISSIONS, CAJA_UNDOSTACK_RENAME, CAJA_UNDOSTACK_RESTOREFROMTRASH, CAJA_UNDOSTACK_SETPERMISSIONS, FALSE, NULL, _CajaUndoStackManager::priv, and TRUE.
caja_undostack_manager_request_menu_update()
void caja_undostack_manager_request_menu_update (CajaUndoStackManager * manager)
Definition at line 375 of file caja-undostack-manager.c.
caja_undostack_manager_trash_has_emptied()
void caja_undostack_manager_trash_has_emptied (CajaUndoStackManager * manager)
Callback after emptying the trash
Definition at line 805 of file caja-undostack-manager.c.
References action, CAJA_UNDOSTACK_MOVETOTRASH, NULL, and _CajaUndoStackManager::priv.
caja_undostack_manager_undo()
void caja_undostack_manager_undo (CajaUndoStackManager * manager, GtkWidget * parent_view, CajaUndostackFinishCallback cb)
Undoes the last file operation
Definition at line 573 of file caja-undostack-manager.c.
References action, caja_file_get_by_uri(), caja_file_operations_delete(), caja_file_operations_move(), caja_file_operations_trash_or_delete(), caja_file_rename(), caja_file_set_group(), caja_file_set_owner(), caja_file_set_permissions(), CAJA_UNDOSTACK_CHANGEGROUP, CAJA_UNDOSTACK_CHANGEOWNER, CAJA_UNDOSTACK_COPY, CAJA_UNDOSTACK_CREATEEMPTYFILE, CAJA_UNDOSTACK_CREATEFILEFROMTEMPLATE, CAJA_UNDOSTACK_CREATEFOLDER, CAJA_UNDOSTACK_CREATELINK, CAJA_UNDOSTACK_DELETE, CAJA_UNDOSTACK_DUPLICATE, CAJA_UNDOSTACK_MOVE, CAJA_UNDOSTACK_MOVETOTRASH, CAJA_UNDOSTACK_RECURSIVESETPERMISSIONS, CAJA_UNDOSTACK_RENAME, CAJA_UNDOSTACK_RESTOREFROMTRASH, CAJA_UNDOSTACK_SETPERMISSIONS, dest, FALSE, item, NULL, _CajaUndoStackManager::priv, and TRUE.
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (CajaUndoStackManager , caja_undostack_manager , G_TYPE_OBJECT)