MATE Desktop Environment: caja-bookmarks-window.h File Reference
caja-bookmarks-window.h File Reference
#include <gtk/gtk.h>
#include "caja-bookmark-list.h"
#include "caja-window.h"
Functions
GtkWindow * create_bookmarks_window (CajaBookmarkList *bookmarks, CajaWindow *window_source)
void caja_bookmarks_window_save_geometry (GtkWindow *window)
void edit_bookmarks_dialog_set_signals (CajaWindow *window)
Function Documentation
caja_bookmarks_window_save_geometry()
void caja_bookmarks_window_save_geometry (GtkWindow * window)
caja_bookmarks_window_save_geometry:
Save window size & position to disk. @window: The bookmarks window whose geometry should be saved.
Definition at line 509 of file caja-bookmarks-window.c.
References caja_bookmark_list_set_window_geometry(), CAJA_IS_BOOKMARK_LIST, and eel_gtk_window_get_geometry_string().
Referenced by caja_bookmarks_exiting().
create_bookmarks_window()
GtkWindow * create_bookmarks_window (CajaBookmarkList * list, CajaWindow * window_source)
create_bookmarks_window:
Create a new bookmark-editing window. @list: The CajaBookmarkList that this window will edit.
Return value: A pointer to the new window.
Definition at line 258 of file caja-bookmarks-window.c.
References CajaWindow::application, BOOKMARK_LIST_COLUMN_ICON, BOOKMARK_LIST_COLUMN_NAME, BOOKMARK_LIST_COLUMN_STYLE, caja_entry_new(), CAJA_ICON_SIZE_SMALLER, CAJA_IS_NAVIGATION_WINDOW, FALSE, NULL, and TRUE.
edit_bookmarks_dialog_set_signals()
void edit_bookmarks_dialog_set_signals (CajaWindow * window)
Definition at line 413 of file caja-bookmarks-window.c.