MATE Desktop Environment: caja-window-private.h File Reference
caja-window-private.h File Reference
#include <libcaja-private/caja-directory.h>
#include "caja-window.h"
#include "caja-window-slot.h"
#include "caja-window-pane.h"
#include "caja-spatial-window.h"
#include "caja-navigation-window.h"
#include "caja-bookmark-list.h"
Classes
struct _CajaWindowPrivate
struct _CajaNavigationWindowPrivate
Macros
#define CAJA_MENU_PATH_BACK_ITEM "/menu/Go/Back"
#define CAJA_MENU_PATH_FORWARD_ITEM "/menu/Go/Forward"
#define CAJA_MENU_PATH_UP_ITEM "/menu/Go/Up"
#define CAJA_MENU_PATH_RELOAD_ITEM "/menu/View/Reload"
#define CAJA_MENU_PATH_ZOOM_IN_ITEM "/menu/View/Zoom Items Placeholder/Zoom In"
#define CAJA_MENU_PATH_ZOOM_OUT_ITEM "/menu/View/Zoom Items Placeholder/Zoom Out"
#define CAJA_MENU_PATH_ZOOM_NORMAL_ITEM "/menu/View/Zoom Items Placeholder/Zoom Normal"
#define CAJA_COMMAND_BACK "/commands/Back"
#define CAJA_COMMAND_FORWARD "/commands/Forward"
#define CAJA_COMMAND_UP "/commands/Up"
#define CAJA_COMMAND_RELOAD "/commands/Reload"
#define CAJA_COMMAND_BURN_CD "/commands/Burn CD"
#define CAJA_COMMAND_STOP "/commands/Stop"
#define CAJA_COMMAND_ZOOM_IN "/commands/Zoom In"
#define CAJA_COMMAND_ZOOM_OUT "/commands/Zoom Out"
#define CAJA_COMMAND_ZOOM_NORMAL "/commands/Zoom Normal"
#define CAJA_SPATIAL_WINDOW_MIN_WIDTH 100
#define CAJA_SPATIAL_WINDOW_MIN_HEIGHT 100
#define CAJA_SPATIAL_WINDOW_DEFAULT_WIDTH 500
#define CAJA_SPATIAL_WINDOW_DEFAULT_HEIGHT 300
#define CAJA_NAVIGATION_WINDOW_MIN_WIDTH 200
#define CAJA_NAVIGATION_WINDOW_MIN_HEIGHT 200
#define CAJA_NAVIGATION_WINDOW_DEFAULT_WIDTH 800
#define CAJA_NAVIGATION_WINDOW_DEFAULT_HEIGHT 550
Typedefs
typedef void(* CajaBookmarkFailedCallback) (CajaWindow *window, CajaBookmark *bookmark)
Functions
void caja_window_set_status (CajaWindow *window, CajaWindowSlot *slot, const char *status)
void caja_window_load_view_as_menus (CajaWindow *window)
void caja_window_load_extension_menus (CajaWindow *window)
void caja_window_initialize_menus (CajaWindow *window)
void caja_window_finalize_menus (CajaWindow *window)
CajaWindowPane * caja_window_get_next_pane (CajaWindow *window)
void caja_menus_append_bookmark_to_menu (CajaWindow *window, CajaBookmark *bookmark, const char *parent_path, const char *parent_id, guint index_in_parent, GtkActionGroup *action_group, guint merge_id, GCallback refresh_callback, CajaBookmarkFailedCallback failed_callback)
void caja_window_update_find_menu_item (CajaWindow *window)
void caja_window_zoom_in (CajaWindow *window)
void caja_window_zoom_out (CajaWindow *window)
void caja_window_zoom_to_level (CajaWindow *window, CajaZoomLevel level)
void caja_window_zoom_to_default (CajaWindow *window)
CajaWindowSlot * caja_window_open_slot (CajaWindowPane *pane, CajaWindowOpenSlotFlags flags)
void caja_window_close_slot (CajaWindowSlot *slot)
CajaWindowSlot * caja_window_get_slot_for_view (CajaWindow *window, CajaView *view)
GList * caja_window_get_slots (CajaWindow *window)
CajaWindowSlot * caja_window_get_active_slot (CajaWindow *window)
CajaWindowSlot * caja_window_get_extra_slot (CajaWindow *window)
void caja_window_set_active_slot (CajaWindow *window, CajaWindowSlot *slot)
void caja_window_set_active_pane (CajaWindow *window, CajaWindowPane *new_pane)
CajaWindowPane * caja_window_get_active_pane (CajaWindow *window)
void caja_send_history_list_changed (void)
void caja_remove_from_history_list_no_notify (GFile *location)
gboolean caja_add_bookmark_to_history_list (CajaBookmark *bookmark)
gboolean caja_add_to_history_list_no_notify (GFile *location, const char *name, gboolean has_custom_name, GIcon *icon)
GList * caja_get_history_list (void)
void caja_window_bookmarks_preference_changed_callback (gpointer user_data)
void caja_window_sync_status (CajaWindow *window)
void caja_window_sync_allow_stop (CajaWindow *window, CajaWindowSlot *slot)
void caja_window_sync_title (CajaWindow *window, CajaWindowSlot *slot)
void caja_window_sync_zoom_widgets (CajaWindow *window)
void caja_navigation_window_initialize_actions (CajaNavigationWindow *window)
void caja_navigation_window_initialize_menus (CajaNavigationWindow *window)
void caja_navigation_window_remove_bookmarks_menu_callback (CajaNavigationWindow *window)
void caja_navigation_window_remove_bookmarks_menu_items (CajaNavigationWindow *window)
void caja_navigation_window_update_show_hide_menu_items (CajaNavigationWindow *window)
void caja_navigation_window_update_spatial_menu_item (CajaNavigationWindow *window)
void caja_navigation_window_remove_go_menu_callback (CajaNavigationWindow *window)
void caja_navigation_window_remove_go_menu_items (CajaNavigationWindow *window)
void caja_navigation_window_activate_spinner (CajaNavigationWindow *window)
void caja_navigation_window_initialize_toolbars (CajaNavigationWindow *window)
void caja_navigation_window_load_extension_toolbar_items (CajaNavigationWindow *window)
void caja_navigation_window_set_spinner_active (CajaNavigationWindow *window, gboolean active)
void caja_navigation_window_go_back (CajaNavigationWindow *window)
void caja_navigation_window_go_forward (CajaNavigationWindow *window)
void caja_window_close_pane (CajaWindowPane *pane)
void caja_navigation_window_update_split_view_actions_sensitivity (CajaNavigationWindow *window)
Macro Definition Documentation
CAJA_COMMAND_BACK
#define CAJA_COMMAND_BACK "/commands/Back"
Definition at line 137 of file caja-window-private.h.
CAJA_COMMAND_BURN_CD
#define CAJA_COMMAND_BURN_CD "/commands/Burn CD"
Definition at line 142 of file caja-window-private.h.
CAJA_COMMAND_FORWARD
#define CAJA_COMMAND_FORWARD "/commands/Forward"
Definition at line 138 of file caja-window-private.h.
CAJA_COMMAND_RELOAD
#define CAJA_COMMAND_RELOAD "/commands/Reload"
Definition at line 141 of file caja-window-private.h.
CAJA_COMMAND_STOP
#define CAJA_COMMAND_STOP "/commands/Stop"
Definition at line 143 of file caja-window-private.h.
CAJA_COMMAND_UP
#define CAJA_COMMAND_UP "/commands/Up"
Definition at line 139 of file caja-window-private.h.
CAJA_COMMAND_ZOOM_IN
#define CAJA_COMMAND_ZOOM_IN "/commands/Zoom In"
Definition at line 144 of file caja-window-private.h.
CAJA_COMMAND_ZOOM_NORMAL
#define CAJA_COMMAND_ZOOM_NORMAL "/commands/Zoom Normal"
Definition at line 146 of file caja-window-private.h.
CAJA_COMMAND_ZOOM_OUT
#define CAJA_COMMAND_ZOOM_OUT "/commands/Zoom Out"
Definition at line 145 of file caja-window-private.h.
CAJA_MENU_PATH_BACK_ITEM
#define CAJA_MENU_PATH_BACK_ITEM "/menu/Go/Back"
Definition at line 128 of file caja-window-private.h.
CAJA_MENU_PATH_FORWARD_ITEM
#define CAJA_MENU_PATH_FORWARD_ITEM "/menu/Go/Forward"
Definition at line 129 of file caja-window-private.h.
CAJA_MENU_PATH_RELOAD_ITEM
#define CAJA_MENU_PATH_RELOAD_ITEM "/menu/View/Reload"
Definition at line 132 of file caja-window-private.h.
CAJA_MENU_PATH_UP_ITEM
#define CAJA_MENU_PATH_UP_ITEM "/menu/Go/Up"
Definition at line 130 of file caja-window-private.h.
CAJA_MENU_PATH_ZOOM_IN_ITEM
#define CAJA_MENU_PATH_ZOOM_IN_ITEM "/menu/View/Zoom Items Placeholder/Zoom In"
Definition at line 133 of file caja-window-private.h.
CAJA_MENU_PATH_ZOOM_NORMAL_ITEM
#define CAJA_MENU_PATH_ZOOM_NORMAL_ITEM "/menu/View/Zoom Items Placeholder/Zoom Normal"
Definition at line 135 of file caja-window-private.h.
CAJA_MENU_PATH_ZOOM_OUT_ITEM
#define CAJA_MENU_PATH_ZOOM_OUT_ITEM "/menu/View/Zoom Items Placeholder/Zoom Out"
Definition at line 134 of file caja-window-private.h.
CAJA_NAVIGATION_WINDOW_DEFAULT_HEIGHT
#define CAJA_NAVIGATION_WINDOW_DEFAULT_HEIGHT 550
Definition at line 162 of file caja-window-private.h.
CAJA_NAVIGATION_WINDOW_DEFAULT_WIDTH
#define CAJA_NAVIGATION_WINDOW_DEFAULT_WIDTH 800
Definition at line 161 of file caja-window-private.h.
CAJA_NAVIGATION_WINDOW_MIN_HEIGHT
#define CAJA_NAVIGATION_WINDOW_MIN_HEIGHT 200
Definition at line 160 of file caja-window-private.h.
CAJA_NAVIGATION_WINDOW_MIN_WIDTH
#define CAJA_NAVIGATION_WINDOW_MIN_WIDTH 200
Definition at line 159 of file caja-window-private.h.
CAJA_SPATIAL_WINDOW_DEFAULT_HEIGHT
#define CAJA_SPATIAL_WINDOW_DEFAULT_HEIGHT 300
Definition at line 157 of file caja-window-private.h.
CAJA_SPATIAL_WINDOW_DEFAULT_WIDTH
#define CAJA_SPATIAL_WINDOW_DEFAULT_WIDTH 500
Definition at line 156 of file caja-window-private.h.
CAJA_SPATIAL_WINDOW_MIN_HEIGHT
#define CAJA_SPATIAL_WINDOW_MIN_HEIGHT 100
Definition at line 155 of file caja-window-private.h.
CAJA_SPATIAL_WINDOW_MIN_WIDTH
#define CAJA_SPATIAL_WINDOW_MIN_WIDTH 100
Definition at line 154 of file caja-window-private.h.
Typedef Documentation
CajaBookmarkFailedCallback
typedef void(* CajaBookmarkFailedCallback) (CajaWindow *window, CajaBookmark *bookmark)
Definition at line 164 of file caja-window-private.h.
Function Documentation
caja_add_bookmark_to_history_list()
gboolean caja_add_bookmark_to_history_list (CajaBookmark * bookmark)
Definition at line 1786 of file caja-window.c.
References caja_bookmark_compare_uris(), CAJA_IS_BOOKMARK, eel_debug_call_at_shutdown(), FALSE, MAX_HISTORY_ITEMS, and TRUE.
Referenced by caja_add_to_history_list_no_notify(), and caja_window_slot_add_current_location_to_history_list().
caja_add_to_history_list_no_notify()
gboolean caja_add_to_history_list_no_notify (GFile * location, const char * name, gboolean has_custom_name, GIcon * icon)
Definition at line 1844 of file caja-window.c.
References caja_add_bookmark_to_history_list(), caja_bookmark_new(), and name.
caja_get_history_list()
GList * caja_get_history_list (void)
Definition at line 1962 of file caja-window.c.
caja_menus_append_bookmark_to_menu()
void caja_menus_append_bookmark_to_menu (CajaWindow * window, CajaBookmark * bookmark, const char * parent_path, const char * parent_id, guint index_in_parent, GtkActionGroup * action_group, guint merge_id, GCallback refresh_callback, CajaBookmarkFailedCallback failed_callback)
Definition at line 167 of file caja-window-menus.c.
References _, action, caja_bookmark_get_name(), caja_bookmark_get_surface(), CAJA_IS_BOOKMARK, CAJA_IS_WINDOW, CajaWindow::details, FALSE, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, name, NULL, TRUE, and _CajaWindowPrivate::ui_manager.
caja_navigation_window_activate_spinner()
void caja_navigation_window_activate_spinner (CajaNavigationWindow * window)
Definition at line 80 of file caja-window-toolbars.c.
References _CajaNavigationWindow::details, item, NULL, _CajaNavigationWindowPrivate::spinner, _CajaNavigationWindowPrivate::toolbar, and TRUE.
Referenced by caja_navigation_window_initialize_toolbars().
caja_navigation_window_go_back()
void caja_navigation_window_go_back (CajaNavigationWindow * window)
Definition at line 742 of file caja-navigation-window.c.
References caja_navigation_window_back_or_forward(), FALSE, and TRUE.
caja_navigation_window_go_forward()
void caja_navigation_window_go_forward (CajaNavigationWindow * window)
Definition at line 748 of file caja-navigation-window.c.
References caja_navigation_window_back_or_forward(), and FALSE.
caja_navigation_window_initialize_actions()
void caja_navigation_window_initialize_actions (CajaNavigationWindow * window)
Definition at line 942 of file caja-navigation-window-menus.c.
References _, action, CAJA_ACTION_SEARCH, CAJA_NAVIGATION_DIRECTION_BACK, CAJA_NAVIGATION_DIRECTION_FORWARD, caja_navigation_window_update_split_view_actions_sensitivity(), CAJA_TYPE_NAVIGATION_ACTION, CAJA_TYPE_VIEW_AS_ACTION, CAJA_TYPE_ZOOM_ACTION, CAJA_WINDOW, caja_window_get_ui_manager(), _CajaNavigationWindow::details, FALSE, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, _CajaNavigationWindowPrivate::navigation_action_group, NULL, and TRUE.
caja_navigation_window_initialize_menus()
void caja_navigation_window_initialize_menus (CajaNavigationWindow * window)
caja_window_initialize_menus
Create and install the set of menus for this window. @window: A recently-created CajaWindow.
Definition at line 1071 of file caja-navigation-window-menus.c.
References caja_navigation_window_update_show_hide_menu_items(), caja_navigation_window_update_spatial_menu_item(), caja_ui_string_get(), CAJA_WINDOW, caja_window_get_ui_manager(), and NULL.
caja_navigation_window_initialize_toolbars()
void caja_navigation_window_initialize_toolbars (CajaNavigationWindow * window)
Definition at line 110 of file caja-window-toolbars.c.
References caja_navigation_window_activate_spinner().
caja_navigation_window_load_extension_toolbar_items()
void caja_navigation_window_load_extension_toolbar_items (CajaNavigationWindow * window)
Definition at line 147 of file caja-window-toolbars.c.
References action, CAJA_MENU_ITEM, caja_toolbar_action_from_menu_item(), CAJA_WINDOW, caja_window_get_ui_manager(), _CajaNavigationWindow::details, _CajaNavigationWindowPrivate::extensions_toolbar_action_group, _CajaNavigationWindowPrivate::extensions_toolbar_merge_id, FALSE, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, item, NULL, and TOOLBAR_PATH_EXTENSION_ACTIONS.
caja_navigation_window_remove_bookmarks_menu_callback()
void caja_navigation_window_remove_bookmarks_menu_callback (CajaNavigationWindow * window)
caja_navigation_window_remove_bookmarks_menu_items()
void caja_navigation_window_remove_bookmarks_menu_items (CajaNavigationWindow * window)
caja_navigation_window_remove_go_menu_callback()
void caja_navigation_window_remove_go_menu_callback (CajaNavigationWindow * window)
Definition at line 381 of file caja-navigation-window-menus.c.
References _CajaNavigationWindow::details, and _CajaNavigationWindowPrivate::refresh_go_menu_idle_id.
caja_navigation_window_remove_go_menu_items()
void caja_navigation_window_remove_go_menu_items (CajaNavigationWindow * window)
Definition at line 391 of file caja-navigation-window-menus.c.
References CAJA_WINDOW, caja_window_get_ui_manager(), _CajaNavigationWindow::details, _CajaNavigationWindowPrivate::go_menu_action_group, _CajaNavigationWindowPrivate::go_menu_merge_id, and NULL.
caja_navigation_window_set_spinner_active()
void caja_navigation_window_set_spinner_active (CajaNavigationWindow * window, gboolean active)
Definition at line 62 of file caja-window-toolbars.c.
References _CajaNavigationWindow::details, _CajaNavigationWindowPrivate::spinner, and _CajaNavigationWindowPrivate::spinner_active.
caja_navigation_window_update_show_hide_menu_items()
void caja_navigation_window_update_show_hide_menu_items (CajaNavigationWindow * window)
Definition at line 317 of file caja-navigation-window-menus.c.
References action, CAJA_ACTION_SHOW_HIDE_EXTRA_PANE, CAJA_ACTION_SHOW_HIDE_LOCATION_BAR, CAJA_ACTION_SHOW_HIDE_SIDEBAR, CAJA_ACTION_SHOW_HIDE_STATUSBAR, CAJA_ACTION_SHOW_HIDE_TOOLBAR, CAJA_IS_NAVIGATION_WINDOW, CAJA_NAVIGATION_WINDOW_PANE, caja_navigation_window_pane_location_bar_showing(), caja_navigation_window_sidebar_showing(), caja_navigation_window_split_view_showing(), caja_navigation_window_status_bar_showing(), caja_navigation_window_toolbar_showing(), CAJA_WINDOW, _CajaNavigationWindow::details, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, and _CajaNavigationWindowPrivate::navigation_action_group.
Referenced by caja_navigation_window_hide_sidebar(), caja_navigation_window_hide_status_bar(), caja_navigation_window_hide_toolbar(), caja_navigation_window_initialize_menus(), caja_navigation_window_pane_hide_location_bar(), caja_navigation_window_pane_show_location_bar(), caja_navigation_window_show_sidebar(), caja_navigation_window_show_status_bar(), caja_navigation_window_show_toolbar(), caja_navigation_window_split_view_off(), and caja_window_pane_slot_close().
caja_navigation_window_update_spatial_menu_item()
void caja_navigation_window_update_spatial_menu_item (CajaNavigationWindow * window)
Definition at line 352 of file caja-navigation-window-menus.c.
References action, CAJA_ACTION_FOLDER_WINDOW, CAJA_IS_NAVIGATION_WINDOW, caja_preferences, CAJA_PREFERENCES_ALWAYS_USE_BROWSER, _CajaNavigationWindow::details, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, and _CajaNavigationWindowPrivate::navigation_action_group.
Referenced by caja_navigation_window_initialize_menus().
caja_navigation_window_update_split_view_actions_sensitivity()
void caja_navigation_window_update_split_view_actions_sensitivity (CajaNavigationWindow * window)
Definition at line 542 of file caja-navigation-window-menus.c.
References action, _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CAJA_IS_NAVIGATION_WINDOW, CAJA_WINDOW, caja_window_get_next_pane(), caja_window_slot_get_location(), _CajaNavigationWindow::details, CajaWindow::details, FALSE, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, _CajaNavigationWindowPrivate::navigation_action_group, NULL, and _CajaWindowPrivate::panes.
Referenced by caja_navigation_window_initialize_actions(), and caja_navigation_window_split_view_off().
caja_remove_from_history_list_no_notify()
void caja_remove_from_history_list_no_notify (GFile * location)
Definition at line 1834 of file caja-window.c.
References caja_bookmark_new(), FALSE, and NULL.
caja_send_history_list_changed()
void caja_send_history_list_changed (void)
Definition at line 1746 of file caja-window.c.
References caja_signaller_get_current().
Referenced by caja_window_slot_add_current_location_to_history_list().
caja_window_bookmarks_preference_changed_callback()
void caja_window_bookmarks_preference_changed_callback (gpointer user_data)
caja_window_close_pane()
void caja_window_close_pane (CajaWindowPane * pane)
Definition at line 868 of file caja-window.c.
References _CajaWindowPrivate::active_pane, CAJA_IS_WINDOW, CAJA_IS_WINDOW_PANE, caja_window_close_slot(), CajaWindow::details, NULL, _CajaWindowPrivate::panes, _CajaWindowPane::slots, and _CajaWindowPane::window.
Referenced by caja_navigation_window_split_view_off(), and caja_window_pane_slot_close().
caja_window_close_slot()
void caja_window_close_slot (CajaWindowSlot * slot)
Definition at line 907 of file caja-window.c.
References _CajaWindowPane::active_slots, CAJA_IS_WINDOW_PANE, CAJA_IS_WINDOW_SLOT, CAJA_WINDOW_CLASS, EEL_CALL_METHOD, NULL, CajaWindowSlot::pane, _CajaWindowPane::slots, and _CajaWindowPane::window.
Referenced by caja_window_close_pane(), and caja_window_pane_slot_close().
caja_window_finalize_menus()
void caja_window_finalize_menus (CajaWindow * window)
Definition at line 1053 of file caja-window-menus.c.
References caja_preferences, and caja_trash_monitor_get().
caja_window_get_active_pane()
CajaWindowPane * caja_window_get_active_pane (CajaWindow * window)
Definition at line 930 of file caja-window.c.
References _CajaWindowPrivate::active_pane, CAJA_IS_WINDOW, and CajaWindow::details.
caja_window_get_active_slot()
CajaWindowSlot * caja_window_get_active_slot (CajaWindow * window)
Definition at line 2078 of file caja-window.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CAJA_IS_WINDOW, and CajaWindow::details.
Referenced by caja_application_open_location(), caja_navigation_window_split_view_on(), caja_window_connect_content_view(), caja_window_disconnect_content_view(), and caja_window_slot_connect_content_view().
caja_window_get_extra_slot()
CajaWindowSlot * caja_window_get_extra_slot (CajaWindow * window)
Definition at line 2086 of file caja-window.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CAJA_IS_WINDOW, CajaWindow::details, FALSE, NULL, and _CajaWindowPrivate::panes.
caja_window_get_next_pane()
CajaWindowPane * caja_window_get_next_pane (CajaWindow * window)
Definition at line 1677 of file caja-window.c.
References _CajaWindowPrivate::active_pane, CajaWindow::details, NULL, and _CajaWindowPrivate::panes.
Referenced by caja_navigation_window_update_split_view_actions_sensitivity(), and caja_window_pane_slot_close().
caja_window_get_slot_for_view()
CajaWindowSlot * caja_window_get_slot_for_view (CajaWindow * window, CajaView * view)
Definition at line 1860 of file caja-window.c.
References CajaWindowSlot::content_view, CajaWindow::details, CajaWindowSlot::new_content_view, NULL, _CajaWindowPrivate::panes, and _CajaWindowPane::slots.
Referenced by caja_window_connect_content_view(), caja_window_disconnect_content_view(), caja_window_report_load_complete(), caja_window_report_load_underway(), and caja_window_report_view_failed().
caja_window_get_slots()
GList * caja_window_get_slots (CajaWindow * window)
Definition at line 2118 of file caja-window.c.
References CAJA_IS_WINDOW, CajaWindow::details, NULL, _CajaWindowPrivate::panes, and _CajaWindowPane::slots.
caja_window_initialize_menus()
void caja_window_initialize_menus (CajaWindow * window)
caja_window_initialize_menus
Create and install the set of menus for this window. @window: A recently-created CajaWindow.
Definition at line 987 of file caja-window-menus.c.
References _, action, CAJA_ACTION_HOME, CAJA_ACTION_SHOW_BACKUP_FILES, CAJA_ACTION_SHOW_HIDDEN_FILES, CAJA_ACTION_UP, caja_preferences, CAJA_PREFERENCES_SHOW_BACKUP_FILES, CAJA_PREFERENCES_SHOW_HIDDEN_FILES, caja_ui_string_get(), CajaWindow::details, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, _CajaWindowPrivate::main_action_group, NULL, and _CajaWindowPrivate::ui_manager.
caja_window_load_extension_menus()
void caja_window_load_extension_menus (CajaWindow * window)
Definition at line 1173 of file caja-window-menus.c.
References CajaWindow::details, _CajaWindowPrivate::extensions_menu_action_group, _CajaWindowPrivate::extensions_menu_merge_id, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, NULL, and _CajaWindowPrivate::ui_manager.
caja_window_load_view_as_menus()
void caja_window_load_view_as_menus (CajaWindow * window)
Definition at line 1476 of file caja-window.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, caja_file_call_when_ready(), CAJA_IS_WINDOW, caja_mime_actions_get_required_file_attributes(), CajaWindow::details, and CajaWindowSlot::viewed_file.
Referenced by caja_window_connect_content_view().
caja_window_open_slot()
CajaWindowSlot * caja_window_open_slot (CajaWindowPane * pane, CajaWindowOpenSlotFlags flags)
Definition at line 848 of file caja-window.c.
References CAJA_IS_WINDOW, CAJA_IS_WINDOW_PANE, CAJA_IS_WINDOW_SLOT, CAJA_WINDOW_CLASS, EEL_CALL_METHOD_WITH_RETURN_VALUE, CajaWindowSlot::pane, _CajaWindowPane::slots, and _CajaWindowPane::window.
Referenced by caja_window_new_tab(), and caja_window_slot_open_location_full().
caja_window_set_active_pane()
void caja_window_set_active_pane (CajaWindow * window, CajaWindowPane * new_pane)
Definition at line 955 of file caja-window.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CAJA_IS_WINDOW_PANE, caja_window_set_active_slot(), and CajaWindow::details.
Referenced by caja_window_pane_zoom_in(), caja_window_pane_zoom_out(), caja_window_pane_zoom_to_default(), and caja_window_pane_zoom_to_level().
caja_window_set_active_slot()
void caja_window_set_active_slot (CajaWindow * window, CajaWindowSlot * slot)
Definition at line 973 of file caja-window.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, _CajaWindowPane::active_slots, CAJA_IS_WINDOW, CAJA_IS_WINDOW_PANE, CAJA_IS_WINDOW_SLOT, caja_window_report_location_change(), caja_window_slot_connect_content_view(), caja_window_slot_disconnect_content_view(), CajaWindowSlot::content_view, CajaWindow::details, NULL, CajaWindowSlot::pane, _CajaWindowPane::slots, and _CajaWindowPane::window.
Referenced by caja_window_new_tab(), caja_window_pane_slot_close(), and caja_window_set_active_pane().
caja_window_set_status()
void caja_window_set_status (CajaWindow * window, CajaWindowSlot * slot, const char * status)
caja_window_sync_allow_stop()
void caja_window_sync_allow_stop (CajaWindow * window, CajaWindowSlot * slot)
Definition at line 451 of file caja-window.c.
References action, _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CajaWindowSlot::allow_stop, CAJA_ACTION_STOP, CAJA_IS_WINDOW, CAJA_WINDOW_CLASS, CajaWindow::details, EEL_CALL_METHOD, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, and _CajaWindowPrivate::main_action_group.
Referenced by caja_window_slot_set_allow_stop().
caja_window_sync_status()
void caja_window_sync_status (CajaWindow * window)
Definition at line 225 of file caja-window.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CajaWindow::details, and CajaWindowSlot::status_text.
Referenced by caja_window_slot_set_status().
caja_window_sync_title()
void caja_window_sync_title (CajaWindow * window, CajaWindowSlot * slot)
Definition at line 1526 of file caja-window.c.
References CAJA_WINDOW_CLASS, and EEL_CALL_METHOD.
caja_window_sync_zoom_widgets()
void caja_window_sync_zoom_widgets (CajaWindow * window)
Definition at line 1534 of file caja-window.c.
References action, _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CAJA_ACTION_ZOOM_IN, CAJA_ACTION_ZOOM_NORMAL, CAJA_ACTION_ZOOM_OUT, caja_view_can_zoom_in(), caja_view_can_zoom_out(), caja_view_get_zoom_level(), caja_view_supports_zooming(), CAJA_ZOOM_LEVEL_LARGEST, CAJA_ZOOM_LEVEL_SMALLEST, CAJA_ZOOM_LEVEL_STANDARD, CajaWindowSlot::content_view, CajaWindow::details, FALSE, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, _CajaWindowPrivate::main_action_group, NULL, and ZOOM_CHANGED.
caja_window_update_find_menu_item()
void caja_window_update_find_menu_item (CajaWindow * window)
caja_window_zoom_in()
void caja_window_zoom_in (CajaWindow * window)
Definition at line 556 of file caja-window.c.
References _CajaWindowPrivate::active_pane, caja_window_pane_zoom_in(), CajaWindow::details, and NULL.
caja_window_zoom_out()
void caja_window_zoom_out (CajaWindow * window)
Definition at line 573 of file caja-window.c.
References _CajaWindowPrivate::active_pane, caja_window_pane_zoom_out(), CajaWindow::details, and NULL.
caja_window_zoom_to_default()
void caja_window_zoom_to_default (CajaWindow * window)
Definition at line 581 of file caja-window.c.
References _CajaWindowPrivate::active_pane, caja_window_pane_zoom_to_default(), CajaWindow::details, and NULL.
caja_window_zoom_to_level()
void caja_window_zoom_to_level (CajaWindow * window, CajaZoomLevel level)
Definition at line 564 of file caja-window.c.
References _CajaWindowPrivate::active_pane, caja_window_pane_zoom_to_level(), CajaWindow::details, level, and NULL.