MATE Desktop Environment: caja-module.h File Reference
caja-module.h File Reference
#include <glib-object.h>
Functions
void caja_module_setup (void)
GList * caja_module_get_extensions_for_type (GType type)
void caja_module_extension_list_free (GList *list)
GObject * caja_module_add_type (GType type)
Function Documentation
caja_module_add_type()
GObject * caja_module_add_type (GType type)
Definition at line 317 of file caja/libcaja-private/caja-module.c.
References NULL, and type.
Referenced by caja_bookmarks_sidebar_register(), caja_emblem_sidebar_register(), caja_history_sidebar_register(), caja_image_properties_page_register(), caja_information_panel_register(), caja_notes_viewer_register(), caja_places_sidebar_register(), and fm_tree_view_register().
caja_module_extension_list_free()
void caja_module_extension_list_free (GList * list)
Definition at line 304 of file caja/libcaja-private/caja-module.c.
References NULL.
caja_module_get_extensions_for_type()
GList * caja_module_get_extensions_for_type (GType type)
Definition at line 285 of file caja/libcaja-private/caja-module.c.
References NULL, and type.
caja_module_setup()
void caja_module_setup (void)
Definition at line 258 of file caja/libcaja-private/caja-module.c.
References eel_debug_call_at_shutdown(), FALSE, NULL, and TRUE.
Referenced by main().