MATE Desktop Environment: caja-sidebar-title.h File Reference
caja-sidebar-title.h File Reference
#include <gtk/gtk.h>
#include <eel/eel-background.h>
#include <libcaja-private/caja-file.h>
Classes
struct CajaSidebarTitle
struct CajaSidebarTitleClass
Macros
#define CAJA_TYPE_SIDEBAR_TITLE caja_sidebar_title_get_type()
#define CAJA_SIDEBAR_TITLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_SIDEBAR_TITLE, CajaSidebarTitle))
#define CAJA_SIDEBAR_TITLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_SIDEBAR_TITLE, CajaSidebarTitleClass))
#define CAJA_IS_SIDEBAR_TITLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_SIDEBAR_TITLE))
#define CAJA_IS_SIDEBAR_TITLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_SIDEBAR_TITLE))
#define CAJA_SIDEBAR_TITLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_SIDEBAR_TITLE, CajaSidebarTitleClass))
Typedefs
typedef struct _CajaSidebarTitlePrivate CajaSidebarTitlePrivate
Functions
GType caja_sidebar_title_get_type (void)
GtkWidget * caja_sidebar_title_new (void)
void caja_sidebar_title_set_file (CajaSidebarTitle *sidebar_title, CajaFile *file, const char *initial_text)
void caja_sidebar_title_set_text (CajaSidebarTitle *sidebar_title, const char *new_title)
char * caja_sidebar_title_get_text (CajaSidebarTitle *sidebar_title)
gboolean caja_sidebar_title_hit_test_icon (CajaSidebarTitle *sidebar_title, int x, int y)
void caja_sidebar_title_select_text_color (CajaSidebarTitle *sidebar_title, EelBackground *background)
Macro Definition Documentation
CAJA_IS_SIDEBAR_TITLE
#define CAJA_IS_SIDEBAR_TITLE (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_SIDEBAR_TITLE))
Definition at line 43 of file caja-sidebar-title.h.
CAJA_IS_SIDEBAR_TITLE_CLASS
#define CAJA_IS_SIDEBAR_TITLE_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_SIDEBAR_TITLE))
Definition at line 45 of file caja-sidebar-title.h.
CAJA_SIDEBAR_TITLE
#define CAJA_SIDEBAR_TITLE (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_SIDEBAR_TITLE, CajaSidebarTitle))
Definition at line 39 of file caja-sidebar-title.h.
CAJA_SIDEBAR_TITLE_CLASS
#define CAJA_SIDEBAR_TITLE_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_SIDEBAR_TITLE, CajaSidebarTitleClass))
Definition at line 41 of file caja-sidebar-title.h.
CAJA_SIDEBAR_TITLE_GET_CLASS
#define CAJA_SIDEBAR_TITLE_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_SIDEBAR_TITLE, CajaSidebarTitleClass))
Definition at line 47 of file caja-sidebar-title.h.
CAJA_TYPE_SIDEBAR_TITLE
#define CAJA_TYPE_SIDEBAR_TITLE caja_sidebar_title_get_type()
Definition at line 38 of file caja-sidebar-title.h.
Typedef Documentation
CajaSidebarTitlePrivate
typedef struct _CajaSidebarTitlePrivate CajaSidebarTitlePrivate
Definition at line 50 of file caja-sidebar-title.h.
Function Documentation
caja_sidebar_title_get_text()
char * caja_sidebar_title_get_text (CajaSidebarTitle * sidebar_title)
Definition at line 673 of file caja-sidebar-title.c.
References CajaSidebarTitle::details.
caja_sidebar_title_get_type()
GType caja_sidebar_title_get_type (void)
Referenced by caja_sidebar_title_new().
caja_sidebar_title_hit_test_icon()
gboolean caja_sidebar_title_hit_test_icon (CajaSidebarTitle * sidebar_title, int x, int y)
Definition at line 815 of file caja-sidebar-title.c.
References CAJA_IS_SIDEBAR_TITLE, CajaSidebarTitle::details, FALSE, and NULL.
caja_sidebar_title_new()
GtkWidget * caja_sidebar_title_new (void)
Definition at line 226 of file caja-sidebar-title.c.
References caja_sidebar_title_get_type(), and NULL.
caja_sidebar_title_select_text_color()
void caja_sidebar_title_select_text_color (CajaSidebarTitle * sidebar_title, EelBackground * background)
Definition at line 238 of file caja-sidebar-title.c.
References CAJA_IS_SIDEBAR_TITLE, DEFAULT_DARK_INFO_COLOR, DEFAULT_LIGHT_INFO_COLOR, eel_background_is_dark(), eel_background_is_set(), eel_gdk_rgba_is_dark(), LABEL_COLOR, LABEL_COLOR_ACTIVE, LABEL_COLOR_HIGHLIGHT, LABEL_COLOR_PRELIGHT, LABEL_INFO_COLOR, LABEL_INFO_COLOR_ACTIVE, LABEL_INFO_COLOR_HIGHLIGHT, and NULL.
caja_sidebar_title_set_file()
void caja_sidebar_title_set_file (CajaSidebarTitle * sidebar_title, CajaFile * file, const char * initial_text)
Definition at line 751 of file caja-sidebar-title.c.
References caja_file_ref(), CajaSidebarTitle::details, FALSE, and NULL.
caja_sidebar_title_set_text()
void caja_sidebar_title_set_text (CajaSidebarTitle * sidebar_title, const char * new_title)
Definition at line 680 of file caja-sidebar-title.c.
References CajaSidebarTitle::details, and MAX_TITLE_SIZE.