MATE Desktop Environment: caja-search-bar.h File Reference
caja-search-bar.h File Reference
#include <gtk/gtk.h>
#include <libcaja-private/caja-query.h>
#include "caja-window.h"
Classes
struct CajaSearchBar
struct CajaSearchBarClass
Macros
#define CAJA_TYPE_SEARCH_BAR caja_search_bar_get_type()
#define CAJA_SEARCH_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_SEARCH_BAR, CajaSearchBar))
#define CAJA_SEARCH_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_SEARCH_BAR, CajaSearchBarClass))
#define CAJA_IS_SEARCH_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_SEARCH_BAR))
#define CAJA_IS_SEARCH_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_SEARCH_BAR))
#define CAJA_SEARCH_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_SEARCH_BAR, CajaSearchBarClass))
Typedefs
typedef struct CajaSearchBarDetails CajaSearchBarDetails
typedef struct CajaSearchBar CajaSearchBar
Functions
GType caja_search_bar_get_type (void)
GtkWidget * caja_search_bar_new (CajaWindow *window)
GtkWidget * caja_search_bar_borrow_entry (CajaSearchBar *bar)
void caja_search_bar_return_entry (CajaSearchBar *bar)
void caja_search_bar_grab_focus (CajaSearchBar *bar)
CajaQuery * caja_search_bar_get_query (CajaSearchBar *bar)
void caja_search_bar_clear (CajaSearchBar *bar)
Macro Definition Documentation
CAJA_IS_SEARCH_BAR
#define CAJA_IS_SEARCH_BAR (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_SEARCH_BAR))
Definition at line 38 of file caja-search-bar.h.
CAJA_IS_SEARCH_BAR_CLASS
#define CAJA_IS_SEARCH_BAR_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_SEARCH_BAR))
Definition at line 40 of file caja-search-bar.h.
CAJA_SEARCH_BAR
#define CAJA_SEARCH_BAR (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_SEARCH_BAR, CajaSearchBar))
Definition at line 34 of file caja-search-bar.h.
CAJA_SEARCH_BAR_CLASS
#define CAJA_SEARCH_BAR_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_SEARCH_BAR, CajaSearchBarClass))
Definition at line 36 of file caja-search-bar.h.
CAJA_SEARCH_BAR_GET_CLASS
#define CAJA_SEARCH_BAR_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_SEARCH_BAR, CajaSearchBarClass))
Definition at line 42 of file caja-search-bar.h.
CAJA_TYPE_SEARCH_BAR
#define CAJA_TYPE_SEARCH_BAR caja_search_bar_get_type()
Definition at line 33 of file caja-search-bar.h.
Typedef Documentation
CajaSearchBar
typedef struct CajaSearchBar CajaSearchBar
CajaSearchBarDetails
typedef struct CajaSearchBarDetails CajaSearchBarDetails
Definition at line 45 of file caja-search-bar.h.
Function Documentation
caja_search_bar_borrow_entry()
GtkWidget * caja_search_bar_borrow_entry (CajaSearchBar * bar)
Definition at line 195 of file caja-search-bar.c.
References CajaSearchBar::details, and TRUE.
Referenced by caja_query_editor_new_with_bar().
caja_search_bar_clear()
void caja_search_bar_clear (CajaSearchBar * bar)
Definition at line 262 of file caja-search-bar.c.
References CajaSearchBar::details.
Referenced by caja_navigation_window_show_search().
caja_search_bar_get_query()
CajaQuery * caja_search_bar_get_query (CajaSearchBar * bar)
Definition at line 236 of file caja-search-bar.c.
References caja_query_new(), caja_query_set_text(), CajaSearchBar::details, and NULL.
caja_search_bar_get_type()
GType caja_search_bar_get_type (void)
caja_search_bar_grab_focus()
void caja_search_bar_grab_focus (CajaSearchBar * bar)
Definition at line 256 of file caja-search-bar.c.
References CajaSearchBar::details.
Referenced by caja_navigation_window_show_search().
caja_search_bar_new()
GtkWidget * caja_search_bar_new (CajaWindow * window)
Definition at line 218 of file caja-search-bar.c.
References caja_clipboard_set_up_editable(), CAJA_SEARCH_BAR, CAJA_TYPE_SEARCH_BAR, caja_window_get_ui_manager(), CajaSearchBar::details, FALSE, and NULL.
Referenced by caja_navigation_window_pane_setup().
caja_search_bar_return_entry()
void caja_search_bar_return_entry (CajaSearchBar * bar)
Definition at line 207 of file caja-search-bar.c.
References CajaSearchBar::details, and FALSE.