MATE Desktop Environment: caja-recent.c File Reference
caja-recent.c File Reference
#include <eel/eel-vfs-extensions.h>
#include "caja-recent.h"
Macros
#define DEFAULT_APP_EXEC "gio open %u"
Functions
void caja_recent_add_file (CajaFile *file, GAppInfo *application)
Macro Definition Documentation
DEFAULT_APP_EXEC
#define DEFAULT_APP_EXEC "gio open %u"
Definition at line 25 of file caja-recent.c.
Function Documentation
caja_recent_add_file()
void caja_recent_add_file (CajaFile * file, GAppInfo * application)
Definition at line 41 of file caja-recent.c.
References caja_file_get_mime_type(), caja_file_get_uri(), DEFAULT_APP_EXEC, eel_uri_is_desktop(), eel_uri_is_search(), eel_uri_is_trash(), FALSE, and NULL.
Referenced by caja_launch_application_by_uri().