MATE Desktop Environment: caja-window-manage-views.h File Reference
caja-window-manage-views.h File Reference
#include "caja-window.h"
#include "caja-window-pane.h"
#include "caja-navigation-window.h"
Functions
void caja_window_manage_views_close_slot (CajaWindowPane *pane, CajaWindowSlot *slot)
void caja_window_report_load_underway (CajaWindow *window, CajaView *view)
void caja_window_report_selection_changed (CajaWindowInfo *window)
void caja_window_report_view_failed (CajaWindow *window, CajaView *view)
void caja_window_report_load_complete (CajaWindow *window, CajaView *view)
void caja_window_report_location_change (CajaWindow *window)
void caja_window_update_up_button (CajaWindow *window)
Function Documentation
caja_window_manage_views_close_slot()
void caja_window_manage_views_close_slot (CajaWindowPane * pane, CajaWindowSlot * slot)
Definition at line 2301 of file caja-window-manage-views.c.
References caja_window_slot_disconnect_content_view(), CajaWindowSlot::content_view, and NULL.
caja_window_report_load_complete()
void caja_window_report_load_complete (CajaWindow * window, CajaView * view)
Definition at line 1930 of file caja-window-manage-views.c.
References CAJA_IS_WINDOW, caja_view_scroll_to_file(), caja_window_get_slot_for_view(), CajaWindowSlot::content_view, CajaWindow::details, NULL, CajaWindowSlot::pending_scroll_to, and _CajaWindowPrivate::temporarily_ignore_view_signals.
caja_window_report_load_underway()
void caja_window_report_load_underway (CajaWindow * window, CajaView * view)
Definition at line 1551 of file caja-window-manage-views.c.
References CAJA_IS_WINDOW, caja_window_get_slot_for_view(), caja_window_slot_set_allow_stop(), CajaWindow::details, CajaWindowSlot::new_content_view, NULL, _CajaWindowPrivate::temporarily_ignore_view_signals, and TRUE.
caja_window_report_location_change()
void caja_window_report_location_change (CajaWindow * window)
Definition at line 1592 of file caja-window-manage-views.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, CAJA_IS_WINDOW, CAJA_IS_WINDOW_SLOT, CajaWindow::details, CajaWindowSlot::location, NULL, and CajaWindowSlot::pending_location.
Referenced by caja_window_set_active_slot().
caja_window_report_selection_changed()
void caja_window_report_selection_changed (CajaWindowInfo * window)
Definition at line 117 of file caja-window-manage-views.c.
References CajaWindow::details, and _CajaWindowPrivate::temporarily_ignore_view_signals.
caja_window_report_view_failed()
void caja_window_report_view_failed (CajaWindow * window, CajaView * view)
Definition at line 2059 of file caja-window-manage-views.c.
References CAJA_LOCATION_CHANGE_FALLBACK, caja_window_get_slot_for_view(), caja_window_slot_disconnect_content_view(), caja_window_slot_set_content_view_widget(), CajaWindowSlot::content_view, CajaWindow::details, FALSE, CajaWindowSlot::location_change_type, NULL, CajaWindowSlot::pending_location, _CajaWindowPrivate::temporarily_ignore_view_signals, and TRUE.
caja_window_update_up_button()
void caja_window_update_up_button (CajaWindow * window)
Definition at line 313 of file caja-window-manage-views.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, caja_window_allow_up(), CajaWindow::details, FALSE, CajaWindowSlot::location, and NULL.