MATE Desktop Environment: caja-window-menus.c File Reference
caja-window-menus.c File Reference
#include <config.h>
#include <locale.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <glib/gi18n.h>
#include <eel/eel-gtk-extensions.h>
#include <libcaja-extension/caja-menu-provider.h>
#include <libcaja-private/caja-extensions.h>
#include <libcaja-private/caja-file-utilities.h>
#include <libcaja-private/caja-global-preferences.h>
#include <libcaja-private/caja-icon-names.h>
#include <libcaja-private/caja-ui-utilities.h>
#include <libcaja-private/caja-module.h>
#include <libcaja-private/caja-search-directory.h>
#include <libcaja-private/caja-search-engine.h>
#include <libcaja-private/caja-signaller.h>
#include <libcaja-private/caja-trash-monitor.h>
#include "caja-actions.h"
#include "caja-application.h"
#include "caja-connect-server-dialog.h"
#include "caja-file-management-properties.h"
#include "caja-property-browser.h"
#include "caja-window-manage-views.h"
#include "caja-window-bookmarks.h"
#include "caja-window-private.h"
#include "caja-desktop-window.h"
#include "caja-search-bar.h"
Macros
#define MENU_PATH_EXTENSION_ACTIONS "/MenuBar/File/Extension Actions"
#define POPUP_PATH_EXTENSION_ACTIONS "/background/Before Zoom Items/Extension Actions"
#define NETWORK_URI "network:"
#define COMPUTER_URI "computer:"
#define ABOUT_GROUP "About"
#define EMAILIFY(string) (g_strdelimit ((string), "%", '@'))
Functions
void caja_menus_append_bookmark_to_menu (CajaWindow *window, CajaBookmark *bookmark, const char *parent_path, const char *parent_id, guint index_in_parent, GtkActionGroup *action_group, guint merge_id, GCallback refresh_callback, CajaBookmarkFailedCallback failed_callback)
void caja_window_initialize_menus (CajaWindow *window)
void caja_window_finalize_menus (CajaWindow *window)
void caja_window_load_extension_menus (CajaWindow *window)
Macro Definition Documentation
ABOUT_GROUP
#define ABOUT_GROUP "About"
Definition at line 526 of file caja-window-menus.c.
COMPUTER_URI
#define COMPUTER_URI "computer:"
Definition at line 65 of file caja-window-menus.c.
EMAILIFY
#define EMAILIFY (string) (g_strdelimit ((string), "%", '@'))
Definition at line 527 of file caja-window-menus.c.
MENU_PATH_EXTENSION_ACTIONS
#define MENU_PATH_EXTENSION_ACTIONS "/MenuBar/File/Extension Actions"
Definition at line 61 of file caja-window-menus.c.
NETWORK_URI
#define NETWORK_URI "network:"
Definition at line 64 of file caja-window-menus.c.
POPUP_PATH_EXTENSION_ACTIONS
#define POPUP_PATH_EXTENSION_ACTIONS "/background/Before Zoom Items/Extension Actions"
Definition at line 62 of file caja-window-menus.c.
Function Documentation
caja_menus_append_bookmark_to_menu()
void caja_menus_append_bookmark_to_menu (CajaWindow * window, CajaBookmark * bookmark, const char * parent_path, const char * parent_id, guint index_in_parent, GtkActionGroup * action_group, guint merge_id, GCallback refresh_callback, CajaBookmarkFailedCallback failed_callback)
Definition at line 167 of file caja-window-menus.c.
References _, action, caja_bookmark_get_name(), caja_bookmark_get_surface(), CAJA_IS_BOOKMARK, CAJA_IS_WINDOW, CajaWindow::details, FALSE, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, name, NULL, TRUE, and _CajaWindowPrivate::ui_manager.
caja_window_finalize_menus()
void caja_window_finalize_menus (CajaWindow * window)
Definition at line 1053 of file caja-window-menus.c.
References caja_preferences, and caja_trash_monitor_get().
caja_window_initialize_menus()
void caja_window_initialize_menus (CajaWindow * window)
caja_window_initialize_menus
Create and install the set of menus for this window. @window: A recently-created CajaWindow.
Definition at line 987 of file caja-window-menus.c.
References _, action, CAJA_ACTION_HOME, CAJA_ACTION_SHOW_BACKUP_FILES, CAJA_ACTION_SHOW_HIDDEN_FILES, CAJA_ACTION_UP, caja_preferences, CAJA_PREFERENCES_SHOW_BACKUP_FILES, CAJA_PREFERENCES_SHOW_HIDDEN_FILES, caja_ui_string_get(), CajaWindow::details, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, _CajaWindowPrivate::main_action_group, NULL, and _CajaWindowPrivate::ui_manager.
caja_window_load_extension_menus()
void caja_window_load_extension_menus (CajaWindow * window)
Definition at line 1177 of file caja-window-menus.c.
References CajaWindow::details, _CajaWindowPrivate::extensions_menu_action_group, _CajaWindowPrivate::extensions_menu_merge_id, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, NULL, and _CajaWindowPrivate::ui_manager.