MATE Desktop Environment: caja-search-directory-file.c File Reference
caja-search-directory-file.c File Reference
#include <config.h>
#include <string.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <eel/eel-glib-extensions.h>
#include "caja-search-directory-file.h"
#include "caja-directory-notify.h"
#include "caja-directory-private.h"
#include "caja-file-attributes.h"
#include "caja-file-private.h"
#include "caja-file-utilities.h"
#include "caja-search-directory.h"
Functions
G_DEFINE_TYPE (CajaSearchDirectoryFile, caja_search_directory_file, CAJA_TYPE_FILE)
void caja_search_directory_file_update_display_name (CajaSearchDirectoryFile *search_file)
Function Documentation
caja_search_directory_file_update_display_name()
void caja_search_directory_file_update_display_name (CajaSearchDirectoryFile * search_file)
Definition at line 176 of file caja-search-directory-file.c.
References _, CAJA_FILE, caja_file_emit_changed(), caja_file_set_display_name(), caja_query_to_readable_string(), CAJA_SEARCH_DIRECTORY, caja_search_directory_get_query(), CajaFile::details, _CajaFilePrivate::directory, NULL, and TRUE.
Referenced by caja_search_directory_set_query().
G_DEFINE_TYPE()
G_DEFINE_TYPE (CajaSearchDirectoryFile , caja_search_directory_file , CAJA_TYPE_FILE)