MATE Desktop Environment: caja-desktop-link.h File Reference
caja-desktop-link.h File Reference
#include <gio/gio.h>
#include "caja-file.h"
Classes
struct CajaDesktopLink
struct CajaDesktopLinkClass
Macros
#define CAJA_TYPE_DESKTOP_LINK caja_desktop_link_get_type()
#define CAJA_DESKTOP_LINK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_DESKTOP_LINK, CajaDesktopLink))
#define CAJA_DESKTOP_LINK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_DESKTOP_LINK, CajaDesktopLinkClass))
#define CAJA_IS_DESKTOP_LINK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_DESKTOP_LINK))
#define CAJA_IS_DESKTOP_LINK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_DESKTOP_LINK))
#define CAJA_DESKTOP_LINK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_DESKTOP_LINK, CajaDesktopLinkClass))
Typedefs
typedef struct _CajaDesktopLinkPrivate CajaDesktopLinkPrivate
Enumerations
enum CajaDesktopLinkType {
CAJA_DESKTOP_LINK_HOME , CAJA_DESKTOP_LINK_COMPUTER , CAJA_DESKTOP_LINK_TRASH , CAJA_DESKTOP_LINK_MOUNT ,
CAJA_DESKTOP_LINK_NETWORK
}
Functions
GType caja_desktop_link_get_type (void)
CajaDesktopLink * caja_desktop_link_new (CajaDesktopLinkType type)
CajaDesktopLink * caja_desktop_link_new_from_mount (GMount *mount)
CajaDesktopLinkType caja_desktop_link_get_link_type (CajaDesktopLink *link)
char * caja_desktop_link_get_file_name (CajaDesktopLink *link)
char * caja_desktop_link_get_display_name (CajaDesktopLink *link)
GIcon * caja_desktop_link_get_icon (CajaDesktopLink *link)
GFile * caja_desktop_link_get_activation_location (CajaDesktopLink *link)
char * caja_desktop_link_get_activation_uri (CajaDesktopLink *link)
gboolean caja_desktop_link_get_date (CajaDesktopLink *link, CajaDateType date_type, time_t *date)
GMount * caja_desktop_link_get_mount (CajaDesktopLink *link)
gboolean caja_desktop_link_can_rename (CajaDesktopLink *link)
gboolean caja_desktop_link_rename (CajaDesktopLink *link, const char *name)
Macro Definition Documentation
CAJA_DESKTOP_LINK
#define CAJA_DESKTOP_LINK (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_DESKTOP_LINK, CajaDesktopLink))
Definition at line 33 of file caja-desktop-link.h.
CAJA_DESKTOP_LINK_CLASS
#define CAJA_DESKTOP_LINK_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_DESKTOP_LINK, CajaDesktopLinkClass))
Definition at line 35 of file caja-desktop-link.h.
CAJA_DESKTOP_LINK_GET_CLASS
#define CAJA_DESKTOP_LINK_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_DESKTOP_LINK, CajaDesktopLinkClass))
Definition at line 41 of file caja-desktop-link.h.
CAJA_IS_DESKTOP_LINK
#define CAJA_IS_DESKTOP_LINK (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_DESKTOP_LINK))
Definition at line 37 of file caja-desktop-link.h.
CAJA_IS_DESKTOP_LINK_CLASS
#define CAJA_IS_DESKTOP_LINK_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_DESKTOP_LINK))
Definition at line 39 of file caja-desktop-link.h.
CAJA_TYPE_DESKTOP_LINK
#define CAJA_TYPE_DESKTOP_LINK caja_desktop_link_get_type()
Definition at line 32 of file caja-desktop-link.h.
Typedef Documentation
CajaDesktopLinkPrivate
typedef struct _CajaDesktopLinkPrivate CajaDesktopLinkPrivate
Definition at line 44 of file caja-desktop-link.h.
Enumeration Type Documentation
CajaDesktopLinkType
enum CajaDesktopLinkType
Enumerator
CAJA_DESKTOP_LINK_HOME
CAJA_DESKTOP_LINK_COMPUTER
CAJA_DESKTOP_LINK_TRASH
CAJA_DESKTOP_LINK_MOUNT
CAJA_DESKTOP_LINK_NETWORK
Definition at line 57 of file caja-desktop-link.h.
Function Documentation
caja_desktop_link_can_rename()
gboolean caja_desktop_link_can_rename (CajaDesktopLink * link)
Definition at line 402 of file caja-desktop-link.c.
References CAJA_DESKTOP_LINK_COMPUTER, CAJA_DESKTOP_LINK_HOME, CAJA_DESKTOP_LINK_NETWORK, CAJA_DESKTOP_LINK_TRASH, and CajaDesktopLink::details.
Referenced by caja_file_can_rename().
caja_desktop_link_get_activation_location()
GFile * caja_desktop_link_get_activation_location (CajaDesktopLink * link)
Definition at line 374 of file caja-desktop-link.c.
References CajaDesktopLink::details, and NULL.
Referenced by caja_file_get_drop_target_uri().
caja_desktop_link_get_activation_uri()
char * caja_desktop_link_get_activation_uri (CajaDesktopLink * link)
Definition at line 384 of file caja-desktop-link.c.
References CajaDesktopLink::details, and NULL.
caja_desktop_link_get_date()
gboolean caja_desktop_link_get_date (CajaDesktopLink * link, CajaDateType date_type, time_t * date)
Definition at line 394 of file caja-desktop-link.c.
References FALSE.
caja_desktop_link_get_display_name()
char * caja_desktop_link_get_display_name (CajaDesktopLink * link)
Definition at line 358 of file caja-desktop-link.c.
References CajaDesktopLink::details.
caja_desktop_link_get_file_name()
char * caja_desktop_link_get_file_name (CajaDesktopLink * link)
Definition at line 352 of file caja-desktop-link.c.
References CajaDesktopLink::details.
Referenced by caja_desktop_icon_file_new().
caja_desktop_link_get_icon()
GIcon * caja_desktop_link_get_icon (CajaDesktopLink * link)
Definition at line 364 of file caja-desktop-link.c.
References CajaDesktopLink::details, and NULL.
caja_desktop_link_get_link_type()
CajaDesktopLinkType caja_desktop_link_get_link_type (CajaDesktopLink * link)
Definition at line 346 of file caja-desktop-link.c.
References CajaDesktopLink::details.
caja_desktop_link_get_mount()
GMount * caja_desktop_link_get_mount (CajaDesktopLink * link)
Definition at line 336 of file caja-desktop-link.c.
References CajaDesktopLink::details, and NULL.
caja_desktop_link_get_type()
GType caja_desktop_link_get_type (void)
caja_desktop_link_new()
CajaDesktopLink * caja_desktop_link_new (CajaDesktopLinkType type)
Definition at line 211 of file caja-desktop-link.c.
References CAJA_DESKTOP_LINK, CAJA_DESKTOP_LINK_COMPUTER, CAJA_DESKTOP_LINK_HOME, CAJA_DESKTOP_LINK_MOUNT, CAJA_DESKTOP_LINK_NETWORK, CAJA_DESKTOP_LINK_TRASH, caja_desktop_preferences, CAJA_ICON_COMPUTER, CAJA_ICON_HOME, CAJA_ICON_NETWORK, CAJA_PREFERENCES_DESKTOP_COMPUTER_NAME, CAJA_PREFERENCES_DESKTOP_HOME_NAME, CAJA_PREFERENCES_DESKTOP_NETWORK_NAME, CAJA_PREFERENCES_DESKTOP_TRASH_NAME, caja_trash_monitor_get(), caja_trash_monitor_get_icon(), CAJA_TYPE_DESKTOP_LINK, CajaDesktopLink::details, EEL_TRASH_URI, NULL, and type.
caja_desktop_link_new_from_mount()
CajaDesktopLink * caja_desktop_link_new_from_mount (GMount * mount)
Definition at line 287 of file caja-desktop-link.c.
References CAJA_DESKTOP_LINK, caja_desktop_link_monitor_get(), caja_desktop_link_monitor_make_filename_unique(), CAJA_DESKTOP_LINK_MOUNT, CAJA_TYPE_DESKTOP_LINK, CajaDesktopLink::details, name, and NULL.
caja_desktop_link_rename()
gboolean caja_desktop_link_rename (CajaDesktopLink * link, const char * name)
Definition at line 411 of file caja-desktop-link.c.
References CAJA_DESKTOP_LINK_COMPUTER, CAJA_DESKTOP_LINK_HOME, CAJA_DESKTOP_LINK_NETWORK, CAJA_DESKTOP_LINK_TRASH, caja_desktop_preferences, CAJA_PREFERENCES_DESKTOP_COMPUTER_NAME, CAJA_PREFERENCES_DESKTOP_HOME_NAME, CAJA_PREFERENCES_DESKTOP_NETWORK_NAME, CAJA_PREFERENCES_DESKTOP_TRASH_NAME, CajaDesktopLink::details, name, and TRUE.
Referenced by caja_file_rename().