MATE Desktop Environment: caja-window-info.c File Reference
caja-window-info.c File Reference
#include <config.h>
#include "caja-window-info.h"
Enumerations
enum {
LOADING_URI , SELECTION_CHANGED , TITLE_CHANGED , HIDDEN_FILES_MODE_CHANGED ,
BACKUP_FILES_MODE_CHANGED , LAST_SIGNAL
}
Functions
GType caja_window_info_get_type (void)
void caja_window_info_report_load_underway (CajaWindowInfo *window, CajaView *view)
void caja_window_info_report_load_complete (CajaWindowInfo *window, CajaView *view)
void caja_window_info_report_view_failed (CajaWindowInfo *window, CajaView *view)
void caja_window_info_report_selection_changed (CajaWindowInfo *window)
void caja_window_info_view_visible (CajaWindowInfo *window, CajaView *view)
void caja_window_info_close (CajaWindowInfo *window)
void caja_window_info_push_status (CajaWindowInfo *window, const char *status)
CajaWindowType caja_window_info_get_window_type (CajaWindowInfo *window)
char * caja_window_info_get_title (CajaWindowInfo *window)
GList * caja_window_info_get_history (CajaWindowInfo *window)
char * caja_window_info_get_current_location (CajaWindowInfo *window)
int caja_window_info_get_selection_count (CajaWindowInfo *window)
GList * caja_window_info_get_selection (CajaWindowInfo *window)
CajaWindowShowHiddenFilesMode caja_window_info_get_hidden_files_mode (CajaWindowInfo *window)
void caja_window_info_set_hidden_files_mode (CajaWindowInfo *window, CajaWindowShowHiddenFilesMode mode)
CajaWindowShowBackupFilesMode caja_window_info_get_backup_files_mode (CajaWindowInfo *window)
void caja_window_info_set_backup_files_mode (CajaWindowInfo *window, CajaWindowShowBackupFilesMode mode)
GtkUIManager * caja_window_info_get_ui_manager (CajaWindowInfo *window)
CajaWindowSlotInfo * caja_window_info_get_active_slot (CajaWindowInfo *window)
CajaWindowSlotInfo * caja_window_info_get_extra_slot (CajaWindowInfo *window)
gboolean caja_window_info_get_initiated_unmount (CajaWindowInfo *window)
void caja_window_info_set_initiated_unmount (CajaWindowInfo *window, gboolean initiated_unmount)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
LOADING_URI
SELECTION_CHANGED
TITLE_CHANGED
HIDDEN_FILES_MODE_CHANGED
BACKUP_FILES_MODE_CHANGED
LAST_SIGNAL
Definition at line 28 of file caja-window-info.c.
Function Documentation
caja_window_info_close()
void caja_window_info_close (CajaWindowInfo * window)
Definition at line 179 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, and CAJA_WINDOW_INFO_GET_IFACE.
caja_window_info_get_active_slot()
CajaWindowSlotInfo * caja_window_info_get_active_slot (CajaWindowInfo * window)
Definition at line 289 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, CAJA_WINDOW_INFO_GET_IFACE, and NULL.
caja_window_info_get_backup_files_mode()
CajaWindowShowBackupFilesMode caja_window_info_get_backup_files_mode (CajaWindowInfo * window)
Definition at line 263 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, CAJA_WINDOW_INFO_GET_IFACE, and CAJA_WINDOW_SHOW_BACKUP_FILES_DEFAULT.
caja_window_info_get_current_location()
char * caja_window_info_get_current_location (CajaWindowInfo * window)
Definition at line 221 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, CAJA_WINDOW_INFO_GET_IFACE, and NULL.
caja_window_info_get_extra_slot()
CajaWindowSlotInfo * caja_window_info_get_extra_slot (CajaWindowInfo * window)
Definition at line 297 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, CAJA_WINDOW_INFO_GET_IFACE, and NULL.
caja_window_info_get_hidden_files_mode()
CajaWindowShowHiddenFilesMode caja_window_info_get_hidden_files_mode (CajaWindowInfo * window)
Definition at line 245 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, CAJA_WINDOW_INFO_GET_IFACE, and CAJA_WINDOW_SHOW_HIDDEN_FILES_DEFAULT.
Referenced by fm_directory_view_reset_to_defaults().
caja_window_info_get_history()
GList * caja_window_info_get_history (CajaWindowInfo * window)
Definition at line 213 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, CAJA_WINDOW_INFO_GET_IFACE, and NULL.
caja_window_info_get_initiated_unmount()
gboolean caja_window_info_get_initiated_unmount (CajaWindowInfo * window)
Definition at line 305 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, CAJA_WINDOW_INFO_GET_IFACE, and FALSE.
caja_window_info_get_selection()
GList * caja_window_info_get_selection (CajaWindowInfo * window)
Definition at line 237 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, CAJA_WINDOW_INFO_GET_IFACE, and NULL.
caja_window_info_get_selection_count()
int caja_window_info_get_selection_count (CajaWindowInfo * window)
Definition at line 229 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, and CAJA_WINDOW_INFO_GET_IFACE.
caja_window_info_get_title()
char * caja_window_info_get_title (CajaWindowInfo * window)
Definition at line 205 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, CAJA_WINDOW_INFO_GET_IFACE, and NULL.
caja_window_info_get_type()
GType caja_window_info_get_type (void)
Definition at line 99 of file caja-window-info.c.
References NULL, and type.
caja_window_info_get_ui_manager()
GtkUIManager * caja_window_info_get_ui_manager (CajaWindowInfo * window)
Definition at line 281 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, CAJA_WINDOW_INFO_GET_IFACE, and NULL.
Referenced by fm_directory_view_get_ui_manager().
caja_window_info_get_window_type()
CajaWindowType caja_window_info_get_window_type (CajaWindowInfo * window)
Definition at line 197 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, CAJA_WINDOW_INFO_GET_IFACE, and CAJA_WINDOW_SPATIAL.
caja_window_info_push_status()
void caja_window_info_push_status (CajaWindowInfo * window, const char * status)
Definition at line 187 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, and CAJA_WINDOW_INFO_GET_IFACE.
caja_window_info_report_load_complete()
void caja_window_info_report_load_complete (CajaWindowInfo * window, CajaView * view)
Definition at line 140 of file caja-window-info.c.
References CAJA_IS_VIEW, CAJA_IS_WINDOW_INFO, and CAJA_WINDOW_INFO_GET_IFACE.
caja_window_info_report_load_underway()
void caja_window_info_report_load_underway (CajaWindowInfo * window, CajaView * view)
Definition at line 129 of file caja-window-info.c.
References CAJA_IS_VIEW, CAJA_IS_WINDOW_INFO, and CAJA_WINDOW_INFO_GET_IFACE.
caja_window_info_report_selection_changed()
void caja_window_info_report_selection_changed (CajaWindowInfo * window)
Definition at line 162 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, and CAJA_WINDOW_INFO_GET_IFACE.
Referenced by fm_directory_view_send_selection_change().
caja_window_info_report_view_failed()
void caja_window_info_report_view_failed (CajaWindowInfo * window, CajaView * view)
Definition at line 151 of file caja-window-info.c.
References CAJA_IS_VIEW, CAJA_IS_WINDOW_INFO, and CAJA_WINDOW_INFO_GET_IFACE.
caja_window_info_set_backup_files_mode()
void caja_window_info_set_backup_files_mode (CajaWindowInfo * window, CajaWindowShowBackupFilesMode mode)
Definition at line 271 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, and CAJA_WINDOW_INFO_GET_IFACE.
caja_window_info_set_hidden_files_mode()
void caja_window_info_set_hidden_files_mode (CajaWindowInfo * window, CajaWindowShowHiddenFilesMode mode)
Definition at line 253 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, and CAJA_WINDOW_INFO_GET_IFACE.
Referenced by fm_directory_view_reset_to_defaults().
caja_window_info_set_initiated_unmount()
void caja_window_info_set_initiated_unmount (CajaWindowInfo * window, gboolean initiated_unmount)
Definition at line 313 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, and CAJA_WINDOW_INFO_GET_IFACE.
Referenced by fm_directory_view_set_initiated_unmount().
caja_window_info_view_visible()
void caja_window_info_view_visible (CajaWindowInfo * window, CajaView * view)
Definition at line 170 of file caja-window-info.c.
References CAJA_IS_WINDOW_INFO, and CAJA_WINDOW_INFO_GET_IFACE.