MATE Desktop Environment: callbacks.cpp File Reference
callbacks.cpp File Reference
#include <config.h>
#include <giomm.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <signal.h>
#include "callbacks.h"
#include "interface.h"
#include "proctable.h"
#include "util.h"
#include "procactions.h"
#include "procman.h"
#include "procdialogs.h"
#include "memmaps.h"
#include "openfiles.h"
#include "procproperties.h"
#include "load-graph.h"
#include "disks.h"
#include "lsof.h"
#include "sysinfo.h"
Functions
void cb_kill_sigstop (GtkAction *action, gpointer data)
void cb_kill_sigcont (GtkAction *action, gpointer data)
void cb_edit_preferences (GtkAction *action, gpointer data)
void cb_renice (GtkAction *action, GtkRadioAction *current, gpointer data)
void cb_end_process (GtkAction *action, gpointer data)
void cb_kill_process (GtkAction *action, gpointer data)
void cb_show_memory_maps (GtkAction *action, gpointer data)
void cb_show_open_files (GtkAction *action, gpointer data)
void cb_show_process_properties (GtkAction *action, gpointer data)
void cb_show_lsof (GtkAction *action, gpointer data)
void cb_about (GtkAction *action, gpointer data)
void cb_help_contents (GtkAction *action, gpointer data)
void cb_app_exit (GtkAction *action, gpointer data)
gboolean cb_app_delete (GtkWidget *window, GdkEventAny *event, gpointer data)
void cb_end_process_button_pressed (GtkButton *button, gpointer data)
void cb_cpu_color_changed (GSMColorButton *cp, gpointer data)
void cb_mem_color_changed (GSMColorButton *cp, gpointer data)
void cb_swap_color_changed (GSMColorButton *cp, gpointer data)
void cb_net_in_color_changed (GSMColorButton *cp, gpointer data)
void cb_net_out_color_changed (GSMColorButton *cp, gpointer data)
void cb_row_selected (GtkTreeSelection *selection, gpointer data)
gboolean cb_tree_button_pressed (GtkWidget *widget, GdkEventButton *event, gpointer data)
gboolean cb_tree_popup_menu (GtkWidget *widget, gpointer data)
void cb_switch_page (GtkNotebook *nb, GtkWidget *page, gint num, gpointer data)
void cb_change_current_page (GtkNotebook *nb, gint num, gpointer data)
gint cb_user_refresh (GtkAction *, gpointer data)
gint cb_timeout (gpointer data)
void cb_radio_processes (GtkAction *action, GtkRadioAction *current, gpointer data)
Function Documentation
cb_about()
void cb_about (GtkAction * action, gpointer data)
Definition at line 157 of file callbacks.cpp.
References _, ProcData::app, data, N_, NULL, and TRUE.
cb_app_delete()
gboolean cb_app_delete (GtkWidget * window, GdkEventAny * event, gpointer data)
Definition at line 273 of file callbacks.cpp.
References data, ProcData::disk_timeout, FALSE, procman_save_config(), ProcData::terminating, ProcData::timeout, and TRUE.
Referenced by cb_app_exit(), and create_main_window().
cb_app_exit()
void cb_app_exit (GtkAction * action, gpointer data)
Definition at line 263 of file callbacks.cpp.
References ProcData::app, cb_app_delete(), data, and NULL.
cb_change_current_page()
void cb_change_current_page (GtkNotebook * nb, gint num, gpointer data)
Definition at line 422 of file callbacks.cpp.
References cb_timeout(), cb_update_disks(), ProcData::config, ProcData::cpu_graph, ProcConfig::current_tab, data, ProcData::disk_timeout, ProcConfig::disks_update_interval, load_graph_start(), load_graph_stop(), ProcData::mem_graph, ProcData::net_graph, PROCMAN_TAB_DISKS, PROCMAN_TAB_PROCESSES, PROCMAN_TAB_RESOURCES, PROCMAN_TAB_SYSINFO, ProcData::timeout, ProcConfig::update_interval, and update_sensitivity().
Referenced by cb_switch_page(), and create_main_window().
cb_cpu_color_changed()
void cb_cpu_color_changed (GSMColorButton * cp, gpointer data)
Definition at line 311 of file callbacks.cpp.
References data, GSM_GSETTINGS_SCHEMA, and key.
cb_edit_preferences()
void cb_edit_preferences (GtkAction * action, gpointer data)
Definition at line 79 of file callbacks.cpp.
References data, and procdialog_create_preferences_dialog().
cb_end_process()
void cb_end_process (GtkAction * action, gpointer data)
Definition at line 112 of file callbacks.cpp.
References data.
cb_end_process_button_pressed()
void cb_end_process_button_pressed (GtkButton * button, gpointer data)
Definition at line 291 of file callbacks.cpp.
References data.
cb_help_contents()
void cb_help_contents (GtkAction * action, gpointer data)
Definition at line 252 of file callbacks.cpp.
References error, and NULL.
cb_kill_process()
void cb_kill_process (GtkAction * action, gpointer data)
Definition at line 119 of file callbacks.cpp.
References data.
cb_kill_sigcont()
void cb_kill_sigcont (GtkAction * action, gpointer data)
Definition at line 57 of file callbacks.cpp.
References data, and kill_process().
cb_kill_sigstop()
void cb_kill_sigstop (GtkAction * action, gpointer data)
Definition at line 45 of file callbacks.cpp.
References data, and kill_process().
cb_mem_color_changed()
void cb_mem_color_changed (GSMColorButton * cp, gpointer data)
Definition at line 323 of file callbacks.cpp.
References data, and ProcData::settings.
cb_net_in_color_changed()
void cb_net_in_color_changed (GSMColorButton * cp, gpointer data)
Definition at line 338 of file callbacks.cpp.
References data, and ProcData::settings.
cb_net_out_color_changed()
void cb_net_out_color_changed (GSMColorButton * cp, gpointer data)
Definition at line 345 of file callbacks.cpp.
References data, and ProcData::settings.
cb_radio_processes()
void cb_radio_processes (GtkAction * action, GtkRadioAction * current, gpointer data)
Definition at line 518 of file callbacks.cpp.
References ProcData::config, data, ProcData::settings, and ProcConfig::whose_process.
Referenced by create_main_window().
cb_renice()
void cb_renice (GtkAction * action, GtkRadioAction * current, gpointer data)
Definition at line 88 of file callbacks.cpp.
References CUSTOM_PRIORITY, data, HIGH_PRIORITY, LOW_PRIORITY, NORMAL_PRIORITY, procdialog_create_renice_dialog(), renice(), VERY_HIGH_PRIORITY, and VERY_LOW_PRIORITY.
Referenced by block_priority_changed_handlers(), and create_main_window().
cb_row_selected()
void cb_row_selected (GtkTreeSelection * selection, gpointer data)
Definition at line 352 of file callbacks.cpp.
References ProcData::action_group, block_priority_changed_handlers(), data, FALSE, get_last_selected(), HIGH_PRIORITY, LOW_PRIORITY, MutableProcInfo::nice, NORMAL_PRIORITY, NULL, ProcData::selected_process, ProcData::selection, TRUE, update_sensitivity(), VERY_HIGH_PRIORITY, and VERY_LOW_PRIORITY.
Referenced by proctable_new().
cb_show_lsof()
void cb_show_lsof (GtkAction * action, gpointer data)
Definition at line 149 of file callbacks.cpp.
References data, and procman_lsof().
cb_show_memory_maps()
void cb_show_memory_maps (GtkAction * action, gpointer data)
Definition at line 126 of file callbacks.cpp.
References create_memmaps_dialog(), and data.
cb_show_open_files()
void cb_show_open_files (GtkAction * action, gpointer data)
Definition at line 134 of file callbacks.cpp.
References create_openfiles_dialog(), and data.
cb_show_process_properties()
void cb_show_process_properties (GtkAction * action, gpointer data)
Definition at line 142 of file callbacks.cpp.
References create_procproperties_dialog(), and data.
cb_swap_color_changed()
void cb_swap_color_changed (GSMColorButton * cp, gpointer data)
Definition at line 331 of file callbacks.cpp.
References data, and ProcData::settings.
cb_switch_page()
void cb_switch_page (GtkNotebook * nb, GtkWidget * page, gint num, gpointer data)
Definition at line 415 of file callbacks.cpp.
References cb_change_current_page(), and data.
Referenced by create_main_window().
cb_timeout()
gint cb_timeout (gpointer data)
Definition at line 497 of file callbacks.cpp.
References cb_timeout(), data, FALSE, SmoothRefresh::get(), proctable_update(), ProcData::smooth_refresh, ProcData::terminating, ProcData::timeout, and TRUE.
Referenced by cb_change_current_page(), cb_timeout(), kill_process(), and renice().
cb_tree_button_pressed()
gboolean cb_tree_button_pressed (GtkWidget * widget, GdkEventButton * event, gpointer data)
Definition at line 390 of file callbacks.cpp.
References data, do_popup_menu(), and FALSE.
Referenced by proctable_new().
cb_tree_popup_menu()
gboolean cb_tree_popup_menu (GtkWidget * widget, gpointer data)
Definition at line 404 of file callbacks.cpp.
References data, do_popup_menu(), NULL, and TRUE.
Referenced by proctable_new().
cb_user_refresh()
gint cb_user_refresh (GtkAction * action, gpointer data)
Definition at line 488 of file callbacks.cpp.
References data, FALSE, and proctable_update().