MATE Desktop Environment: callbacks.c File Reference
callbacks.c File Reference
#include <string.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include "baobab.h"
#include "baobab-treeview.h"
#include "baobab-utils.h"
#include "callbacks.h"
#include "baobab-prefs.h"
#include "baobab-remote-connect-dialog.h"
#include "baobab-chart.h"
Functions
void on_quit_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_menuscanhome_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_menuallfs_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_menuscandir_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_about_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_menu_expand_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_menu_collapse_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_menu_stop_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_menu_rescan_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_tbscandir_clicked (GtkToolButton *toolbutton, gpointer user_data)
void on_tbscanhome_clicked (GtkToolButton *toolbutton, gpointer user_data)
void on_tbscanall_clicked (GtkToolButton *toolbutton, gpointer user_data)
void on_tb_scan_remote_clicked (GtkToolButton *toolbutton, gpointer user_data)
void on_menu_scan_rem_activate (GtkMenuItem *menuitem, gpointer user_data)
void on_tbstop_clicked (GtkToolButton *toolbutton, gpointer user_data)
void on_tbrescan_clicked (GtkToolButton *toolbutton, gpointer user_data)
gboolean on_delete_activate (GtkWidget *widget, GdkEvent *event, gpointer user_data)
void open_file_cb (GtkMenuItem *pmenu, gpointer dummy)
void trash_dir_cb (GtkMenuItem *pmenu, gpointer dummy)
void on_pref_menu (GtkAction *a, gpointer user_data)
void on_ck_allocated_activate (GtkToggleAction *action, gpointer user_data)
void on_helpcontents_activate (GtkAction *a, gpointer user_data)
void scan_folder_cb (GtkMenuItem *pmenu, gpointer dummy)
void on_tv_selection_changed (GtkTreeSelection *selection, gpointer user_data)
void on_move_upwards_cb (GtkCheckMenuItem *checkmenuitem, gpointer user_data)
void on_zoom_in_cb (GtkCheckMenuItem *checkmenuitem, gpointer user_data)
void on_zoom_out_cb (GtkCheckMenuItem *checkmenuitem, gpointer user_data)
void on_chart_snapshot_cb (GtkCheckMenuItem *checkmenuitem, gpointer user_data)
Function Documentation
on_about_activate()
void on_about_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 62 of file callbacks.c.
References _, baobab, N_, NULL, TRUE, and _BaobabApplication::window.
on_chart_snapshot_cb()
void on_chart_snapshot_cb (GtkCheckMenuItem * checkmenuitem, gpointer user_data)
Definition at line 334 of file callbacks.c.
References baobab, baobab_chart_save_snapshot(), and _BaobabApplication::current_chart.
on_ck_allocated_activate()
void on_ck_allocated_activate (GtkToggleAction * action, gpointer user_data)
Definition at line 255 of file callbacks.c.
References _, action, baobab, baobab_set_busy(), baobab_set_statusbar(), baobab_treeview_show_allocated_size(), FALSE, _BaobabApplication::is_local, _BaobabApplication::model, NULL, _BaobabApplication::show_allocated, show_bars(), _BaobabApplication::tree_view, and TRUE.
on_delete_activate()
gboolean on_delete_activate (GtkWidget * widget, GdkEvent * event, gpointer user_data)
Definition at line 192 of file callbacks.c.
References baobab_quit(), and TRUE.
on_helpcontents_activate()
void on_helpcontents_activate (GtkAction * a, gpointer user_data)
Definition at line 275 of file callbacks.c.
References baobab, baobab_help_display(), NULL, and _BaobabApplication::window.
on_menu_collapse_activate()
void on_menu_collapse_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 126 of file callbacks.c.
References baobab, and _BaobabApplication::tree_view.
on_menu_expand_activate()
void on_menu_expand_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 120 of file callbacks.c.
References baobab, and _BaobabApplication::tree_view.
on_menu_rescan_activate()
void on_menu_rescan_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 138 of file callbacks.c.
References baobab_rescan_current_dir().
on_menu_scan_rem_activate()
void on_menu_scan_rem_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 174 of file callbacks.c.
References NULL, and on_tb_scan_remote_clicked().
on_menu_stop_activate()
void on_menu_stop_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 132 of file callbacks.c.
References baobab_stop_scan().
on_menuallfs_activate()
void on_menuallfs_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 50 of file callbacks.c.
References baobab_scan_root().
on_menuscandir_activate()
void on_menuscandir_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 56 of file callbacks.c.
References baobab, dir_select(), FALSE, and _BaobabApplication::window.
on_menuscanhome_activate()
void on_menuscanhome_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 44 of file callbacks.c.
References baobab_scan_home().
on_move_upwards_cb()
void on_move_upwards_cb (GtkCheckMenuItem * checkmenuitem, gpointer user_data)
Definition at line 316 of file callbacks.c.
References baobab, baobab_chart_move_up_root(), and _BaobabApplication::current_chart.
on_pref_menu()
void on_pref_menu (GtkAction * a, gpointer user_data)
Definition at line 249 of file callbacks.c.
References baobab_prefs_dialog().
on_quit_activate()
void on_quit_activate (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 38 of file callbacks.c.
References baobab_quit().
on_tb_scan_remote_clicked()
void on_tb_scan_remote_clicked (GtkToolButton * toolbutton, gpointer user_data)
Definition at line 162 of file callbacks.c.
References baobab, baobab_remote_connect_dialog_new(), NULL, and _BaobabApplication::window.
Referenced by on_menu_scan_rem_activate().
on_tbrescan_clicked()
void on_tbrescan_clicked (GtkToolButton * toolbutton, gpointer user_data)
Definition at line 186 of file callbacks.c.
References baobab_rescan_current_dir().
on_tbscanall_clicked()
void on_tbscanall_clicked (GtkToolButton * toolbutton, gpointer user_data)
Definition at line 156 of file callbacks.c.
References baobab_scan_root().
on_tbscandir_clicked()
void on_tbscandir_clicked (GtkToolButton * toolbutton, gpointer user_data)
Definition at line 144 of file callbacks.c.
References baobab, dir_select(), FALSE, and _BaobabApplication::window.
on_tbscanhome_clicked()
void on_tbscanhome_clicked (GtkToolButton * toolbutton, gpointer user_data)
Definition at line 150 of file callbacks.c.
References baobab_scan_home().
on_tbstop_clicked()
void on_tbstop_clicked (GtkToolButton * toolbutton, gpointer user_data)
Definition at line 180 of file callbacks.c.
References baobab_stop_scan().
on_tv_selection_changed()
void on_tv_selection_changed (GtkTreeSelection * selection, gpointer user_data)
Definition at line 299 of file callbacks.c.
References baobab, baobab_chart_set_root(), _BaobabApplication::model, NULL, _BaobabApplication::rings_chart, and _BaobabApplication::treemap_chart.
Referenced by create_directory_treeview().
on_zoom_in_cb()
void on_zoom_in_cb (GtkCheckMenuItem * checkmenuitem, gpointer user_data)
Definition at line 322 of file callbacks.c.
References baobab, baobab_chart_zoom_in(), and _BaobabApplication::current_chart.
on_zoom_out_cb()
void on_zoom_out_cb (GtkCheckMenuItem * checkmenuitem, gpointer user_data)
Definition at line 328 of file callbacks.c.
References baobab, baobab_chart_zoom_out(), and _BaobabApplication::current_chart.
open_file_cb()
void open_file_cb (GtkMenuItem * pmenu, gpointer dummy)
Definition at line 200 of file callbacks.c.
References _, baobab, message(), NULL, open_file_with_application(), _BaobabApplication::selected_path, and _BaobabApplication::window.
Referenced by popupmenu_list().
scan_folder_cb()
void scan_folder_cb (GtkMenuItem * pmenu, gpointer dummy)
Definition at line 281 of file callbacks.c.
References _, baobab, baobab_scan_location(), message(), NULL, _BaobabApplication::selected_path, and _BaobabApplication::window.
trash_dir_cb()
void trash_dir_cb (GtkMenuItem * pmenu, gpointer dummy)
Definition at line 221 of file callbacks.c.
References baobab, _BaobabApplication::model, NULL, _BaobabApplication::selected_path, and trash_file().
Referenced by popupmenu_list().