MATE Desktop Environment: ProcmanApp Class Reference
ProcmanApp Class Reference
#include <procman-app.h>
Static Public Member Functions
static Glib::RefPtr< ProcmanApp > create ()
Protected Member Functions
ProcmanApp ()
virtual void on_activate ()
virtual int on_command_line (const Glib::RefPtr< Gio::ApplicationCommandLine > &command_line)
virtual void on_startup ()
virtual void on_shutdown ()
Detailed Description
Definition at line 9 of file procman-app.h.
Constructor & Destructor Documentation
ProcmanApp()
ProcmanApp::ProcmanApp () protected
Definition at line 348 of file procman-app.cpp.
References _.
Referenced by create().
Member Function Documentation
create()
Glib::RefPtr< ProcmanApp > ProcmanApp::create () static
Definition at line 353 of file procman-app.cpp.
References ProcmanApp().
Referenced by main().
on_activate()
void ProcmanApp::on_activate () protected virtual
Definition at line 358 of file procman-app.cpp.
References ProcData::app.
Referenced by on_command_line().
on_command_line()
int ProcmanApp::on_command_line (const Glib::RefPtr< Gio::ApplicationCommandLine > & command_line) protected virtual
Definition at line 370 of file procman-app.cpp.
References _, ProcData::notebook, on_activate(), procman_debug, PROCMAN_TAB_DISKS, PROCMAN_TAB_PROCESSES, PROCMAN_TAB_RESOURCES, PROCMAN_TAB_SYSINFO, procman::OptionGroup::show_file_systems_tab, procman::OptionGroup::show_processes_tab, procman::OptionGroup::show_resources_tab, and procman::OptionGroup::show_system_tab.
on_shutdown()
void ProcmanApp::on_shutdown () protected virtual
Definition at line 431 of file procman-app.cpp.
on_startup()
void ProcmanApp::on_startup () protected virtual
Definition at line 406 of file procman-app.cpp.
References ProcData::app, create_main_window(), GSM_GSETTINGS_SCHEMA, and ProcData::settings.
The documentation for this class was generated from the following files:
procman-app.h
procman-app.cpp