MATE Desktop Environment: clock-location-tile.h File Reference
clock-location-tile.h File Reference
#include <gtk/gtk.h>
#include "clock.h"
#include "clock-face.h"
#include "clock-location.h"
#include "clock-utils.h"
Classes
struct ClockLocationTile
struct ClockLocationTileClass
Macros
#define CLOCK_LOCATION_TILE_TYPE (clock_location_tile_get_type ())
#define CLOCK_LOCATION_TILE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), CLOCK_LOCATION_TILE_TYPE, ClockLocationTile))
#define CLOCK_LOCATION_TILE_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), CLOCK_LOCATION_TILE_TYPE, ClockLocationTileClass))
#define IS_CLOCK_LOCATION_TILE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), CLOCK_LOCATION_TILE_TYPE))
#define IS_CLOCK_LOCATION_TILE_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), CLOCK_LOCATION_TILE_TYPE))
#define CLOCK_LOCATION_TILE_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), CLOCK_LOCATION_TILE_TYPE, ClockLocationTileClass))
Functions
GType clock_location_tile_get_type (void)
ClockLocationTile * clock_location_tile_new (ClockLocation *loc, ClockFaceSize size)
ClockLocation * clock_location_tile_get_location (ClockLocationTile *this)
void weather_info_setup_tooltip (WeatherInfo *info, ClockLocation *location, GtkTooltip *tip, ClockFormat clock_format)
void clock_location_tile_refresh (ClockLocationTile *this, gboolean force_refresh)
Macro Definition Documentation
CLOCK_LOCATION_TILE
#define CLOCK_LOCATION_TILE (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), CLOCK_LOCATION_TILE_TYPE, ClockLocationTile))
Definition at line 16 of file clock-location-tile.h.
CLOCK_LOCATION_TILE_CLASS
#define CLOCK_LOCATION_TILE_CLASS (c) (G_TYPE_CHECK_CLASS_CAST ((c), CLOCK_LOCATION_TILE_TYPE, ClockLocationTileClass))
Definition at line 17 of file clock-location-tile.h.
CLOCK_LOCATION_TILE_GET_CLASS
#define CLOCK_LOCATION_TILE_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), CLOCK_LOCATION_TILE_TYPE, ClockLocationTileClass))
Definition at line 20 of file clock-location-tile.h.
CLOCK_LOCATION_TILE_TYPE
#define CLOCK_LOCATION_TILE_TYPE (clock_location_tile_get_type ())
Definition at line 15 of file clock-location-tile.h.
IS_CLOCK_LOCATION_TILE
#define IS_CLOCK_LOCATION_TILE (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), CLOCK_LOCATION_TILE_TYPE))
Definition at line 18 of file clock-location-tile.h.
IS_CLOCK_LOCATION_TILE_CLASS
#define IS_CLOCK_LOCATION_TILE_CLASS (c) (G_TYPE_CHECK_CLASS_TYPE ((c), CLOCK_LOCATION_TILE_TYPE))
Definition at line 19 of file clock-location-tile.h.
Function Documentation
clock_location_tile_get_location()
ClockLocation * clock_location_tile_get_location (ClockLocationTile * this)
Definition at line 710 of file clock-location-tile.c.
References IS_CLOCK_LOCATION_TILE, and NULL.
clock_location_tile_get_type()
GType clock_location_tile_get_type (void)
clock_location_tile_new()
ClockLocationTile * clock_location_tile_new (ClockLocation * loc, ClockFaceSize size)
Definition at line 65 of file clock-location-tile.c.
References clock_location_get_weather_info(), CLOCK_LOCATION_TILE_TYPE, NULL, and TRUE.
clock_location_tile_refresh()
void clock_location_tile_refresh (ClockLocationTile * this, gboolean force_refresh)
Definition at line 517 of file clock-location-tile.c.
References CLOCK_FACE, clock_face_refresh(), clock_location_get_display_name(), clock_location_get_offset(), clock_location_get_tzname(), clock_location_is_current(), clock_location_localtime(), IS_CLOCK_LOCATION_TILE, and NEED_CLOCK_FORMAT.
weather_info_setup_tooltip()
void weather_info_setup_tooltip (WeatherInfo * info, ClockLocation * location, GtkTooltip * tip, ClockFormat clock_format)
Definition at line 571 of file clock-location-tile.c.
References _, clock_location_get_timezone(), NULL, weather_info_get_apparent(), weather_info_get_conditions(), weather_info_get_icon_name(), weather_info_get_sky(), weather_info_get_temp(), weather_info_get_value_sunrise(), weather_info_get_value_sunset(), and weather_info_get_wind().