MATE Desktop Environment: core.h File Reference
core.h File Reference
#include <gdk/gdkx.h>
#include "common.h"
Enumerations
enum MetaCoreGetType {
META_CORE_GET_END = 0 , META_CORE_WINDOW_HAS_FRAME , META_CORE_GET_CLIENT_WIDTH , META_CORE_GET_CLIENT_HEIGHT ,
META_CORE_IS_TITLEBAR_ONSCREEN , META_CORE_GET_CLIENT_XWINDOW , META_CORE_GET_FRAME_FLAGS , META_CORE_GET_FRAME_TYPE ,
META_CORE_GET_MINI_ICON , META_CORE_GET_ICON , META_CORE_GET_X , META_CORE_GET_Y ,
META_CORE_GET_FRAME_WORKSPACE , META_CORE_GET_FRAME_X , META_CORE_GET_FRAME_Y , META_CORE_GET_FRAME_WIDTH ,
META_CORE_GET_FRAME_HEIGHT , META_CORE_GET_THEME_VARIANT , META_CORE_GET_SCREEN_WIDTH , META_CORE_GET_SCREEN_HEIGHT
}
Functions
void meta_core_get (Display *xdisplay, Window window,...)
void meta_core_queue_frame_resize (Display *xdisplay, Window frame_xwindow)
void meta_core_user_move (Display *xdisplay, Window frame_xwindow, int x, int y)
void meta_core_user_resize (Display *xdisplay, Window frame_xwindow, int gravity, int width, int height)
void meta_core_user_raise (Display *xdisplay, Window frame_xwindow)
void meta_core_user_lower_and_unfocus (Display *xdisplay, Window frame_xwindow, guint32 timestamp)
void meta_core_user_focus (Display *xdisplay, Window frame_xwindow, guint32 timestamp)
void meta_core_lower_beneath_focus_window (Display *xdisplay, Window xwindow, guint32 timestamp)
void meta_core_minimize (Display *xdisplay, Window frame_xwindow)
void meta_core_toggle_maximize (Display *xdisplay, Window frame_xwindow)
void meta_core_toggle_maximize_horizontally (Display *xdisplay, Window frame_xwindow)
void meta_core_toggle_maximize_vertically (Display *xdisplay, Window frame_xwindow)
void meta_core_unmaximize (Display *xdisplay, Window frame_xwindow)
void meta_core_maximize (Display *xdisplay, Window frame_xwindow)
void meta_core_delete (Display *xdisplay, Window frame_xwindow, guint32 timestamp)
void meta_core_unshade (Display *xdisplay, Window frame_xwindow, guint32 timestamp)
void meta_core_shade (Display *xdisplay, Window frame_xwindow, guint32 timestamp)
void meta_core_unstick (Display *xdisplay, Window frame_xwindow)
void meta_core_stick (Display *xdisplay, Window frame_xwindow)
void meta_core_unmake_above (Display *xdisplay, Window frame_xwindow)
void meta_core_make_above (Display *xdisplay, Window frame_xwindow)
void meta_core_change_workspace (Display *xdisplay, Window frame_xwindow, int new_workspace)
int meta_core_get_num_workspaces (Screen *xscreen)
int meta_core_get_active_workspace (Screen *xscreen)
int meta_core_get_frame_workspace (Display *xdisplay, Window frame_xwindow)
const char * meta_core_get_workspace_name_with_index (Display *xdisplay, Window xroot, int index)
void meta_core_show_window_menu (Display *xdisplay, Window frame_xwindow, int root_x, int root_y, int button, guint32 timestamp)
void meta_core_get_menu_accelerator (MetaMenuOp menu_op, int workspace, unsigned int *keysym, MetaVirtualModifier *modifiers)
gboolean meta_core_begin_grab_op (Display *xdisplay, Window frame_xwindow, MetaGrabOp op, gboolean pointer_already_grabbed, gboolean frame_action, int button, gulong modmask, guint32 timestamp, int root_x, int root_y)
void meta_core_end_grab_op (Display *xdisplay, guint32 timestamp)
MetaGrabOp meta_core_get_grab_op (Display *xdisplay)
Window meta_core_get_grab_frame (Display *xdisplay)
int meta_core_get_grab_button (Display *xdisplay)
void meta_core_grab_buttons (Display *xdisplay, Window frame_xwindow)
void meta_core_set_screen_cursor (Display *xdisplay, Window frame_on_screen, MetaCursor cursor)
void meta_core_increment_event_serial (Display *display)
void meta_invalidate_default_icons (void)
void meta_invalidate_all_icons (void)
Enumeration Type Documentation
MetaCoreGetType
enum MetaCoreGetType
Enumerator
META_CORE_GET_END
META_CORE_WINDOW_HAS_FRAME
META_CORE_GET_CLIENT_WIDTH
META_CORE_GET_CLIENT_HEIGHT
META_CORE_IS_TITLEBAR_ONSCREEN
META_CORE_GET_CLIENT_XWINDOW
META_CORE_GET_FRAME_FLAGS
META_CORE_GET_FRAME_TYPE
META_CORE_GET_MINI_ICON
META_CORE_GET_ICON
META_CORE_GET_X
META_CORE_GET_Y
META_CORE_GET_FRAME_WORKSPACE
META_CORE_GET_FRAME_X
META_CORE_GET_FRAME_Y
META_CORE_GET_FRAME_WIDTH
META_CORE_GET_FRAME_HEIGHT
META_CORE_GET_THEME_VARIANT
META_CORE_GET_SCREEN_WIDTH
META_CORE_GET_SCREEN_HEIGHT
Definition at line 32 of file core.h.
Function Documentation
meta_core_begin_grab_op()
gboolean meta_core_begin_grab_op (Display * xdisplay, Window frame_xwindow, MetaGrabOp op, gboolean pointer_already_grabbed, gboolean frame_action, int button, gulong modmask, guint32 timestamp, int root_x, int root_y)
Definition at line 680 of file core.c.
References meta_display_begin_grab_op(), meta_display_for_x_display(), meta_display_screen_for_xwindow(), NULL, and op.
meta_core_change_workspace()
void meta_core_change_workspace (Display * xdisplay, Window frame_xwindow, int new_workspace)
Definition at line 501 of file core.c.
References meta_screen_get_workspace_by_index(), meta_window_change_workspace(), and _MetaWindow::screen.
meta_core_delete()
void meta_core_delete (Display * xdisplay, Window frame_xwindow, guint32 timestamp)
Definition at line 435 of file core.c.
References meta_window_delete().
meta_core_end_grab_op()
void meta_core_end_grab_op (Display * xdisplay, guint32 timestamp)
Definition at line 708 of file core.c.
References meta_display_end_grab_op(), and meta_display_for_x_display().
Referenced by meta_frames_notify_menu_hide().
meta_core_get()
void meta_core_get (Display * xdisplay, Window window, ...)
Definition at line 66 of file core.c.
References _, _MetaWindow::border_only, _MetaWindow::frame, _MetaWindow::gtk_theme_variant, _MetaRectangle::height, _MetaWindow::icon, meta_bug(), META_CORE_GET_CLIENT_HEIGHT, META_CORE_GET_CLIENT_WIDTH, META_CORE_GET_CLIENT_XWINDOW, META_CORE_GET_END, META_CORE_GET_FRAME_FLAGS, META_CORE_GET_FRAME_HEIGHT, META_CORE_GET_FRAME_TYPE, META_CORE_GET_FRAME_WIDTH, META_CORE_GET_FRAME_WORKSPACE, META_CORE_GET_FRAME_X, META_CORE_GET_FRAME_Y, META_CORE_GET_ICON, META_CORE_GET_MINI_ICON, META_CORE_GET_SCREEN_HEIGHT, META_CORE_GET_SCREEN_WIDTH, META_CORE_GET_THEME_VARIANT, META_CORE_GET_X, META_CORE_GET_Y, META_CORE_IS_TITLEBAR_ONSCREEN, META_CORE_WINDOW_HAS_FRAME, meta_display_for_x_display(), meta_display_lookup_x_window(), meta_frame_get_flags(), META_FRAME_TYPE_ATTACHED, META_FRAME_TYPE_BORDER, META_FRAME_TYPE_DIALOG, META_FRAME_TYPE_LAST, META_FRAME_TYPE_MENU, META_FRAME_TYPE_MODAL_DIALOG, META_FRAME_TYPE_NORMAL, META_FRAME_TYPE_UTILITY, meta_prefs_get_attach_modal_dialogs(), meta_warning(), META_WINDOW_DESKTOP, META_WINDOW_DIALOG, META_WINDOW_DOCK, meta_window_get_net_wm_desktop(), meta_window_get_position(), meta_window_get_transient_for(), META_WINDOW_MENU, META_WINDOW_MODAL_DIALOG, META_WINDOW_NORMAL, META_WINDOW_SPLASHSCREEN, meta_window_titlebar_is_onscreen(), META_WINDOW_TOOLBAR, META_WINDOW_UTILITY, _MetaWindow::mini_icon, NULL, _MetaFrame::rect, _MetaScreen::rect, _MetaWindow::rect, _MetaWindow::screen, _MetaWindow::type, _MetaRectangle::width, _MetaRectangle::x, _MetaWindow::xwindow, and _MetaRectangle::y.
Referenced by meta_frames_apply_shapes().
meta_core_get_active_workspace()
int meta_core_get_active_workspace (Screen * xscreen)
Definition at line 523 of file core.c.
References _MetaScreen::active_workspace, meta_screen_for_x_screen(), and meta_workspace_index().
meta_core_get_frame_workspace()
int meta_core_get_frame_workspace (Display * xdisplay, Window frame_xwindow)
meta_core_get_grab_button()
int meta_core_get_grab_button (Display * xdisplay)
Definition at line 750 of file core.c.
References _MetaDisplay::grab_button, _MetaDisplay::grab_op, meta_display_for_x_display(), and META_GRAB_OP_NONE.
meta_core_get_grab_frame()
Window meta_core_get_grab_frame (Display * xdisplay)
Definition at line 729 of file core.c.
References _MetaScreen::display, _MetaWindow::frame, _MetaDisplay::grab_op, _MetaDisplay::grab_screen, _MetaDisplay::grab_window, meta_display_for_x_display(), META_GRAB_OP_NONE, NULL, _MetaDisplay::xdisplay, and _MetaFrame::xwindow.
Referenced by meta_frames_notify_menu_hide().
meta_core_get_grab_op()
MetaGrabOp meta_core_get_grab_op (Display * xdisplay)
Definition at line 719 of file core.c.
References _MetaDisplay::grab_op, and meta_display_for_x_display().
Referenced by meta_frames_notify_menu_hide().
meta_core_get_menu_accelerator()
void meta_core_get_menu_accelerator (MetaMenuOp menu_op, int workspace, unsigned int * keysym, MetaVirtualModifier * modifiers)
Definition at line 550 of file core.c.
References META_MENU_OP_ABOVE, META_MENU_OP_DELETE, META_MENU_OP_MAXIMIZE, META_MENU_OP_MINIMIZE, META_MENU_OP_MOVE, META_MENU_OP_MOVE_DOWN, META_MENU_OP_MOVE_LEFT, META_MENU_OP_MOVE_RIGHT, META_MENU_OP_MOVE_UP, META_MENU_OP_NONE, META_MENU_OP_RECOVER, META_MENU_OP_RESIZE, META_MENU_OP_SHADE, META_MENU_OP_STICK, META_MENU_OP_UNABOVE, META_MENU_OP_UNMAXIMIZE, META_MENU_OP_UNSHADE, META_MENU_OP_UNSTICK, META_MENU_OP_WORKSPACES, meta_prefs_get_window_binding(), name, and NULL.
Referenced by meta_window_menu_new().
meta_core_get_num_workspaces()
int meta_core_get_num_workspaces (Screen * xscreen)
Definition at line 513 of file core.c.
References meta_screen_for_x_screen(), and meta_screen_get_n_workspaces().
meta_core_get_workspace_name_with_index()
const char * meta_core_get_workspace_name_with_index (Display * xdisplay, Window xroot, int index)
Definition at line 664 of file core.c.
References meta_display_for_x_display(), meta_display_screen_for_root(), meta_screen_get_workspace_by_index(), meta_workspace_get_name(), and NULL.
meta_core_grab_buttons()
void meta_core_grab_buttons (Display * xdisplay, Window frame_xwindow)
Definition at line 763 of file core.c.
References meta_display_for_x_display(), and meta_display_grab_window_buttons().
Referenced by meta_frames_manage_window().
meta_core_increment_event_serial()
void meta_core_increment_event_serial (Display * display)
Definition at line 785 of file core.c.
References meta_display_for_x_display(), and meta_display_increment_event_serial().
Referenced by meta_ui_tab_popup_set_showing().
meta_core_lower_beneath_focus_window()
void meta_core_lower_beneath_focus_window (Display * xdisplay, Window xwindow, guint32 timestamp)
Definition at line 310 of file core.c.
References FALSE, _MetaWindow::frame, meta_display_for_x_display(), meta_display_screen_for_xwindow(), meta_error_trap_pop(), meta_error_trap_push(), meta_stack_get_top(), NULL, _MetaScreen::stack, _MetaFrame::xwindow, and _MetaWindow::xwindow.
Referenced by meta_tile_preview_show().
meta_core_make_above()
void meta_core_make_above (Display * xdisplay, Window frame_xwindow)
Definition at line 474 of file core.c.
References meta_window_make_above().
meta_core_maximize()
void meta_core_maximize (Display * xdisplay, Window frame_xwindow)
Definition at line 358 of file core.c.
References META_MAXIMIZE_HORIZONTAL, META_MAXIMIZE_VERTICAL, meta_prefs_get_raise_on_click(), meta_window_maximize(), and meta_window_raise().
meta_core_minimize()
void meta_core_minimize (Display * xdisplay, Window frame_xwindow)
Definition at line 349 of file core.c.
References meta_window_minimize().
meta_core_queue_frame_resize()
void meta_core_queue_frame_resize (Display * xdisplay, Window frame_xwindow)
Definition at line 227 of file core.c.
References META_QUEUE_MOVE_RESIZE, and meta_window_queue().
meta_core_set_screen_cursor()
void meta_core_set_screen_cursor (Display * xdisplay, Window frame_on_screen, MetaCursor cursor)
Definition at line 775 of file core.c.
References _MetaWindow::frame, and meta_frame_set_screen_cursor().
Referenced by meta_frames_unmanage_window().
meta_core_shade()
void meta_core_shade (Display * xdisplay, Window frame_xwindow, guint32 timestamp)
Definition at line 455 of file core.c.
References meta_window_shade().
meta_core_show_window_menu()
void meta_core_show_window_menu (Display * xdisplay, Window frame_xwindow, int root_x, int root_y, int button, guint32 timestamp)
Definition at line 533 of file core.c.
References meta_prefs_get_raise_on_click(), meta_window_focus(), meta_window_raise(), and meta_window_show_menu().
meta_core_stick()
void meta_core_stick (Display * xdisplay, Window frame_xwindow)
Definition at line 492 of file core.c.
References meta_window_stick().
meta_core_toggle_maximize()
void meta_core_toggle_maximize (Display * xdisplay, Window frame_xwindow)
Definition at line 405 of file core.c.
References META_MAXIMIZE_HORIZONTAL, META_MAXIMIZE_VERTICAL, meta_prefs_get_raise_on_click(), meta_window_maximize(), META_WINDOW_MAXIMIZED, meta_window_raise(), and meta_window_unmaximize().
meta_core_toggle_maximize_horizontally()
void meta_core_toggle_maximize_horizontally (Display * xdisplay, Window frame_xwindow)
Definition at line 388 of file core.c.
References META_MAXIMIZE_HORIZONTAL, meta_prefs_get_raise_on_click(), meta_window_maximize(), META_WINDOW_MAXIMIZED_HORIZONTALLY, meta_window_raise(), and meta_window_unmaximize().
meta_core_toggle_maximize_vertically()
void meta_core_toggle_maximize_vertically (Display * xdisplay, Window frame_xwindow)
Definition at line 371 of file core.c.
References META_MAXIMIZE_VERTICAL, meta_prefs_get_raise_on_click(), meta_window_maximize(), META_WINDOW_MAXIMIZED_VERTICALLY, meta_window_raise(), and meta_window_unmaximize().
meta_core_unmake_above()
void meta_core_unmake_above (Display * xdisplay, Window frame_xwindow)
Definition at line 483 of file core.c.
References meta_window_unmake_above().
meta_core_unmaximize()
void meta_core_unmaximize (Display * xdisplay, Window frame_xwindow)
Definition at line 422 of file core.c.
References META_MAXIMIZE_HORIZONTAL, META_MAXIMIZE_VERTICAL, meta_prefs_get_raise_on_click(), meta_window_raise(), and meta_window_unmaximize().
meta_core_unshade()
void meta_core_unshade (Display * xdisplay, Window frame_xwindow, guint32 timestamp)
Definition at line 445 of file core.c.
References meta_window_unshade().
meta_core_unstick()
void meta_core_unstick (Display * xdisplay, Window frame_xwindow)
Definition at line 465 of file core.c.
References meta_window_unstick().
meta_core_user_focus()
void meta_core_user_focus (Display * xdisplay, Window frame_xwindow, guint32 timestamp)
Definition at line 339 of file core.c.
References meta_window_focus().
meta_core_user_lower_and_unfocus()
void meta_core_user_lower_and_unfocus (Display * xdisplay, Window frame_xwindow, guint32 timestamp)
Definition at line 268 of file core.c.
References _MetaScreen::active_workspace, _MetaWindow::has_focus, meta_prefs_get_raise_on_click(), meta_window_located_on_workspace(), meta_window_lower(), meta_workspace_focus_default_window(), _MetaWorkspace::mru_list, NULL, and _MetaWindow::screen.
meta_core_user_move()
void meta_core_user_move (Display * xdisplay, Window frame_xwindow, int x, int y)
Definition at line 236 of file core.c.
References meta_window_move(), and TRUE.
meta_core_user_raise()
void meta_core_user_raise (Display * xdisplay, Window frame_xwindow)
Definition at line 259 of file core.c.
References meta_window_raise().
meta_core_user_resize()
void meta_core_user_resize (Display * xdisplay, Window frame_xwindow, int gravity, int width, int height)
Definition at line 247 of file core.c.
References meta_window_resize_with_gravity(), and TRUE.
meta_invalidate_all_icons()
void meta_invalidate_all_icons (void)
Definition at line 820 of file core.c.
References _MetaWindow::icon_cache, meta_display_list_windows(), meta_get_display(), meta_icon_cache_invalidate(), meta_window_update_icon_now(), and NULL.
meta_invalidate_default_icons()
void meta_invalidate_default_icons (void)
Definition at line 795 of file core.c.
References _MetaWindow::icon_cache, meta_display_list_windows(), meta_get_display(), meta_icon_cache_free(), meta_window_update_icon_now(), NULL, _MetaIconCache::origin, and USING_FALLBACK_ICON.
Referenced by meta_ui_set_current_theme().