MATE Desktop Environment: cpufreq-selector-service.h File Reference
cpufreq-selector-service.h File Reference
#include <glib-object.h>
#include <dbus/dbus-glib.h>
Macros
#define CPUFREQ_TYPE_SELECTOR_SERVICE (cpufreq_selector_service_get_type ())
#define CPUFREQ_SELECTOR_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CPUFREQ_TYPE_SELECTOR_SERVICE, CPUFreqSelectorService))
#define CPUFREQ_SELECTOR_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), CPUFREQ_TYPE_SELECTOR_SERVICE, CPUFreqSelectorServiceClass))
#define CPUFREQ_IS_SELECTOR_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CPUFREQ_TYPE_SELECTOR_SERVICE))
#define CPUFREQ_IS_SELECTOR_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CPUFREQ_TYPE_SELECTOR_SERVICE))
#define CPUFREQ_SELECTOR_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CPUFREQ_TYPE_SELECTOR_SERVICE, CPUFreqSelectorServiceClass))
#define SELECTOR_SERVICE (cpufreq_selector_service_get_instance ())
#define CPUFREQ_SELECTOR_SERVICE_ERROR (cpufreq_selector_service_error_quark ())
#define CPUFREQ_TYPE_SELECTOR_SERVICE_ERROR (cpufreq_selector_service_error_get_type ())
Typedefs
typedef struct _CPUFreqSelectorService CPUFreqSelectorService
typedef struct _CPUFreqSelectorServiceClass CPUFreqSelectorServiceClass
Enumerations
enum { SERVICE_ERROR_GENERAL , SERVICE_ERROR_DBUS , SERVICE_ERROR_ALREADY_REGISTERED , SERVICE_ERROR_NOT_AUTHORIZED }
Functions
GType cpufreq_selector_service_get_type (void)
GType cpufreq_selector_service_error_get_type (void)
GQuark cpufreq_selector_service_error_quark (void)
CPUFreqSelectorService * cpufreq_selector_service_get_instance (void)
gboolean cpufreq_selector_service_register (CPUFreqSelectorService *service, GError **error)
gboolean cpufreq_selector_service_set_frequency (CPUFreqSelectorService *service, guint cpu, guint frequency, DBusGMethodInvocation *context)
gboolean cpufreq_selector_service_set_governor (CPUFreqSelectorService *service, guint cpu, const gchar *governor, DBusGMethodInvocation *context)
gboolean cpufreq_selector_service_can_set (CPUFreqSelectorService *service, DBusGMethodInvocation *context)
Macro Definition Documentation
CPUFREQ_IS_SELECTOR_SERVICE
#define CPUFREQ_IS_SELECTOR_SERVICE (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CPUFREQ_TYPE_SELECTOR_SERVICE))
Definition at line 31 of file cpufreq-selector-service.h.
CPUFREQ_IS_SELECTOR_SERVICE_CLASS
#define CPUFREQ_IS_SELECTOR_SERVICE_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CPUFREQ_TYPE_SELECTOR_SERVICE))
Definition at line 32 of file cpufreq-selector-service.h.
CPUFREQ_SELECTOR_SERVICE
#define CPUFREQ_SELECTOR_SERVICE (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CPUFREQ_TYPE_SELECTOR_SERVICE, CPUFreqSelectorService))
Definition at line 29 of file cpufreq-selector-service.h.
CPUFREQ_SELECTOR_SERVICE_CLASS
#define CPUFREQ_SELECTOR_SERVICE_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), CPUFREQ_TYPE_SELECTOR_SERVICE, CPUFreqSelectorServiceClass))
Definition at line 30 of file cpufreq-selector-service.h.
CPUFREQ_SELECTOR_SERVICE_ERROR
#define CPUFREQ_SELECTOR_SERVICE_ERROR (cpufreq_selector_service_error_quark ())
Definition at line 37 of file cpufreq-selector-service.h.
CPUFREQ_SELECTOR_SERVICE_GET_CLASS
#define CPUFREQ_SELECTOR_SERVICE_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CPUFREQ_TYPE_SELECTOR_SERVICE, CPUFreqSelectorServiceClass))
Definition at line 33 of file cpufreq-selector-service.h.
CPUFREQ_TYPE_SELECTOR_SERVICE
#define CPUFREQ_TYPE_SELECTOR_SERVICE (cpufreq_selector_service_get_type ())
Definition at line 28 of file cpufreq-selector-service.h.
CPUFREQ_TYPE_SELECTOR_SERVICE_ERROR
#define CPUFREQ_TYPE_SELECTOR_SERVICE_ERROR (cpufreq_selector_service_error_get_type ())
Definition at line 38 of file cpufreq-selector-service.h.
SELECTOR_SERVICE
#define SELECTOR_SERVICE (cpufreq_selector_service_get_instance ())
Definition at line 35 of file cpufreq-selector-service.h.
Typedef Documentation
CPUFreqSelectorService
typedef struct _CPUFreqSelectorService CPUFreqSelectorService
Definition at line 47 of file cpufreq-selector-service.h.
CPUFreqSelectorServiceClass
typedef struct _CPUFreqSelectorServiceClass CPUFreqSelectorServiceClass
Definition at line 48 of file cpufreq-selector-service.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SERVICE_ERROR_GENERAL
SERVICE_ERROR_DBUS
SERVICE_ERROR_ALREADY_REGISTERED
SERVICE_ERROR_NOT_AUTHORIZED
Definition at line 40 of file cpufreq-selector-service.h.
Function Documentation
cpufreq_selector_service_can_set()
gboolean cpufreq_selector_service_can_set (CPUFreqSelectorService * service, DBusGMethodInvocation * context)
Definition at line 442 of file cpufreq-selector-service.c.
References error, FALSE, NULL, and TRUE.
cpufreq_selector_service_error_get_type()
GType cpufreq_selector_service_error_get_type (void)
Definition at line 52 of file cpufreq-selector-service.c.
References NULL, SERVICE_ERROR_ALREADY_REGISTERED, SERVICE_ERROR_DBUS, SERVICE_ERROR_GENERAL, and SERVICE_ERROR_NOT_AUTHORIZED.
cpufreq_selector_service_error_quark()
GQuark cpufreq_selector_service_error_quark (void)
Definition at line 72 of file cpufreq-selector-service.c.
cpufreq_selector_service_get_instance()
CPUFreqSelectorService * cpufreq_selector_service_get_instance (void)
Definition at line 125 of file cpufreq-selector-service.c.
References CPUFREQ_SELECTOR_SERVICE, CPUFREQ_TYPE_SELECTOR_SERVICE, and NULL.
cpufreq_selector_service_get_type()
GType cpufreq_selector_service_get_type (void)
cpufreq_selector_service_register()
gboolean cpufreq_selector_service_register (CPUFreqSelectorService * service, GError ** error)
Definition at line 157 of file cpufreq-selector-service.c.
References BUS_NAME, connection, CPUFREQ_SELECTOR_SERVICE_ERROR, CPUFREQ_TYPE_SELECTOR_SERVICE, CPUFREQ_TYPE_SELECTOR_SERVICE_ERROR, error, FALSE, NULL, SERVICE_ERROR_ALREADY_REGISTERED, SERVICE_ERROR_DBUS, and TRUE.
Referenced by main().
cpufreq_selector_service_set_frequency()
gboolean cpufreq_selector_service_set_frequency (CPUFreqSelectorService * service, guint cpu, guint frequency, DBusGMethodInvocation * context)
Definition at line 312 of file cpufreq-selector-service.c.
References CPUFREQ_SELECTOR_SERVICE_ERROR, cpufreq_selector_set_frequency(), error, FALSE, MAX_CPUS, NULL, SERVICE_ERROR_DBUS, and TRUE.
cpufreq_selector_service_set_governor()
gboolean cpufreq_selector_service_set_governor (CPUFreqSelectorService * service, guint cpu, const gchar * governor, DBusGMethodInvocation * context)
Definition at line 377 of file cpufreq-selector-service.c.
References CPUFREQ_SELECTOR_SERVICE_ERROR, cpufreq_selector_set_governor(), error, FALSE, MAX_CPUS, NULL, SERVICE_ERROR_DBUS, and TRUE.