MATE Desktop Environment: cpufreq-selector-service.c File Reference
cpufreq-selector-service.c File Reference
#include <polkit/polkit.h>
#include <dbus/dbus-glib-lowlevel.h>
#include "cpufreq-selector.h"
#include "cpufreq-selector-factory.h"
#include "cpufreq-selector-service.h"
#include "cpufreq-selector-service-glue.h"
Macros
#define MAX_CPUS 255
#define BUS_NAME "org.mate.CPUFreqSelector"
Functions
GType cpufreq_selector_service_error_get_type (void)
GQuark cpufreq_selector_service_error_quark (void)
CPUFreqSelectorService * cpufreq_selector_service_get_instance (void)
gboolean cpufreq_selector_service_register (CPUFreqSelectorService *service, GError **error)
gboolean cpufreq_selector_service_set_frequency (CPUFreqSelectorService *service, guint cpu, guint frequency, DBusGMethodInvocation *context)
gboolean cpufreq_selector_service_set_governor (CPUFreqSelectorService *service, guint cpu, const gchar *governor, DBusGMethodInvocation *context)
gboolean cpufreq_selector_service_can_set (CPUFreqSelectorService *service, DBusGMethodInvocation *context)
Macro Definition Documentation
BUS_NAME
#define BUS_NAME "org.mate.CPUFreqSelector"
Definition at line 49 of file cpufreq-selector-service.c.
MAX_CPUS
#define MAX_CPUS 255
Definition at line 29 of file cpufreq-selector-service.c.
Function Documentation
cpufreq_selector_service_can_set()
gboolean cpufreq_selector_service_can_set (CPUFreqSelectorService * service, DBusGMethodInvocation * context)
Definition at line 442 of file cpufreq-selector-service.c.
References error, FALSE, NULL, and TRUE.
cpufreq_selector_service_error_get_type()
GType cpufreq_selector_service_error_get_type (void)
Definition at line 52 of file cpufreq-selector-service.c.
References NULL, SERVICE_ERROR_ALREADY_REGISTERED, SERVICE_ERROR_DBUS, SERVICE_ERROR_GENERAL, and SERVICE_ERROR_NOT_AUTHORIZED.
cpufreq_selector_service_error_quark()
GQuark cpufreq_selector_service_error_quark (void)
Definition at line 72 of file cpufreq-selector-service.c.
cpufreq_selector_service_get_instance()
CPUFreqSelectorService * cpufreq_selector_service_get_instance (void)
Definition at line 125 of file cpufreq-selector-service.c.
References CPUFREQ_SELECTOR_SERVICE, CPUFREQ_TYPE_SELECTOR_SERVICE, and NULL.
cpufreq_selector_service_register()
gboolean cpufreq_selector_service_register (CPUFreqSelectorService * service, GError ** error)
Definition at line 157 of file cpufreq-selector-service.c.
References BUS_NAME, connection, CPUFREQ_SELECTOR_SERVICE_ERROR, CPUFREQ_TYPE_SELECTOR_SERVICE, CPUFREQ_TYPE_SELECTOR_SERVICE_ERROR, error, FALSE, NULL, SERVICE_ERROR_ALREADY_REGISTERED, SERVICE_ERROR_DBUS, and TRUE.
Referenced by main().
cpufreq_selector_service_set_frequency()
gboolean cpufreq_selector_service_set_frequency (CPUFreqSelectorService * service, guint cpu, guint frequency, DBusGMethodInvocation * context)
Definition at line 312 of file cpufreq-selector-service.c.
References CPUFREQ_SELECTOR_SERVICE_ERROR, cpufreq_selector_set_frequency(), error, FALSE, MAX_CPUS, NULL, SERVICE_ERROR_DBUS, and TRUE.
cpufreq_selector_service_set_governor()
gboolean cpufreq_selector_service_set_governor (CPUFreqSelectorService * service, guint cpu, const gchar * governor, DBusGMethodInvocation * context)
Definition at line 377 of file cpufreq-selector-service.c.
References CPUFREQ_SELECTOR_SERVICE_ERROR, cpufreq_selector_set_governor(), error, FALSE, MAX_CPUS, NULL, SERVICE_ERROR_DBUS, and TRUE.