MATE Desktop Environment: currency-manager.c File Reference
currency-manager.c File Reference
#include <time.h>
#include <glib.h>
#include <glib/gstdio.h>
#include <gio/gio.h>
#include <libxml/tree.h>
#include <libxml/parser.h>
#include <libxml/xpath.h>
#include <libxml/xpathInternals.h>
#include <glib/gi18n.h>
#include "currency-manager.h"
#include "mp.h"
Enumerations
enum { UPDATED , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (CurrencyManager, currency_manager, G_TYPE_OBJECT)
CurrencyManager * currency_manager_get_default (void)
GList * currency_manager_get_currencies (CurrencyManager *manager)
Currency * currency_manager_get_currency (CurrencyManager *manager, const gchar *name)
const MPNumber * currency_manager_get_value (CurrencyManager *manager, const gchar *currency)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
UPDATED
LAST_SIGNAL
Definition at line 105 of file currency-manager.c.
Function Documentation
currency_manager_get_currencies()
GList * currency_manager_get_currencies (CurrencyManager * manager)
Definition at line 134 of file currency-manager.c.
References NULL, and CurrencyManager::priv.
Referenced by unit_manager_get_default().
currency_manager_get_currency()
Currency * currency_manager_get_currency (CurrencyManager * manager, const gchar * name)
Definition at line 141 of file currency-manager.c.
References currency_get_name(), currency_get_value(), mp_is_negative(), mp_is_zero(), name, NULL, and CurrencyManager::priv.
Referenced by currency_manager_get_value().
currency_manager_get_default()
CurrencyManager * currency_manager_get_default (void)
Definition at line 114 of file currency-manager.c.
References _, currency_manager_get_type(), currency_new(), NULL, and CurrencyManager::priv.
Referenced by unit_convert_from(), unit_convert_to(), and unit_manager_get_default().
currency_manager_get_value()
const MPNumber * currency_manager_get_value (CurrencyManager * manager, const gchar * currency)
Definition at line 564 of file currency-manager.c.
References currency_get_value(), currency_manager_get_currency(), NULL, and TRUE.
Referenced by unit_convert_from(), and unit_convert_to().
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (CurrencyManager , currency_manager , G_TYPE_OBJECT)