MATE Desktop Environment: currency.h File Reference
currency.h File Reference
#include <glib-object.h>
#include "mp.h"
Classes
struct Currency
struct CurrencyClass
Macros
#define CURRENCY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), currency_get_type(), Currency))
Typedefs
typedef struct CurrencyPrivate CurrencyPrivate
Functions
GType currency_get_type (void)
Currency * currency_new (const gchar *name, const gchar *display_name, const gchar *symbol)
const gchar * currency_get_name (Currency *currency)
const gchar * currency_get_short_display_name (Currency *currency)
const gchar * currency_get_display_name (Currency *currency)
const gchar * currency_get_symbol (Currency *currency)
void currency_set_value (Currency *currency, MPNumber *value)
const MPNumber * currency_get_value (Currency *currency)
Macro Definition Documentation
CURRENCY
#define CURRENCY (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), currency_get_type(), Currency))
Definition at line 19 of file currency.h.
Typedef Documentation
CurrencyPrivate
typedef struct CurrencyPrivate CurrencyPrivate
Definition at line 21 of file currency.h.
Function Documentation
currency_get_display_name()
const gchar * currency_get_display_name (Currency * currency)
Definition at line 51 of file currency.c.
References NULL, and Currency::priv.
Referenced by unit_manager_get_default().
currency_get_name()
const gchar * currency_get_name (Currency * currency)
Definition at line 44 of file currency.c.
References NULL, and Currency::priv.
Referenced by currency_manager_get_currency(), and unit_manager_get_default().
currency_get_short_display_name()
const gchar * currency_get_short_display_name (Currency * currency)
currency_get_symbol()
const gchar * currency_get_symbol (Currency * currency)
Definition at line 58 of file currency.c.
References NULL, and Currency::priv.
Referenced by unit_manager_get_default().
currency_get_type()
GType currency_get_type (void)
Referenced by currency_new().
currency_get_value()
const MPNumber * currency_get_value (Currency * currency)
Definition at line 73 of file currency.c.
References NULL, and Currency::priv.
Referenced by currency_manager_get_currency(), and currency_manager_get_value().
currency_new()
Currency * currency_new (const gchar * name, const gchar * display_name, const gchar * symbol)
Definition at line 29 of file currency.c.
References currency_get_type(), mp_new(), name, NULL, and Currency::priv.
Referenced by currency_manager_get_default().
currency_set_value()
void currency_set_value (Currency * currency, MPNumber * value)
Definition at line 65 of file currency.c.
References mp_set_from_mp(), NULL, and Currency::priv.