MATE Desktop Environment: delete.c File Reference
delete.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include "util.h"
#include "window-private.h"
#include "errors.h"
#include "workspace.h"
#include <sys/types.h>
#include <sys/wait.h>
#include <signal.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>
Macros
#define _GNU_SOURCE
#define _XOPEN_SOURCE /* for gethostname() and kill() */
Functions
void meta_window_delete (MetaWindow *window, guint32 timestamp)
void meta_window_kill (MetaWindow *window)
void meta_window_free_delete_dialog (MetaWindow *window)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 25 of file delete.c.
_XOPEN_SOURCE
#define _XOPEN_SOURCE /* for gethostname() and kill() */
Definition at line 26 of file delete.c.
Function Documentation
meta_window_delete()
void meta_window_delete (MetaWindow * window, guint32 timestamp)
Definition at line 123 of file delete.c.
References _MetaWindow::delete_window, _MetaWindow::desc, _MetaWindow::display, FALSE, META_DEBUG_WINDOW_OPS, meta_display_ping_window(), meta_error_trap_pop(), meta_error_trap_push(), meta_window_send_icccm_message(), _MetaDisplay::xdisplay, and _MetaWindow::xwindow.
Referenced by meta_core_delete(), and meta_window_client_message().
meta_window_free_delete_dialog()
void meta_window_free_delete_dialog (MetaWindow * window)
Definition at line 195 of file delete.c.
References _MetaWindow::dialog_pid.
Referenced by meta_window_free().
meta_window_kill()
void meta_window_kill (MetaWindow * window)
Definition at line 154 of file delete.c.
References _, _MetaWindow::desc, _MetaWindow::display, FALSE, META_DEBUG_WINDOW_OPS, meta_error_trap_pop(), meta_error_trap_push(), meta_warning(), _MetaWindow::net_wm_pid, NULL, _MetaWindow::wm_client_machine, _MetaDisplay::xdisplay, and _MetaWindow::xwindow.