MATE Desktop Environment: disks.cpp File Reference
disks.cpp File Reference
#include <config.h>
#include <giomm.h>
#include <giomm/themedicon.h>
#include <gtk/gtk.h>
#include <glibtop/mountlist.h>
#include <glibtop/fsusage.h>
#include <glib/gi18n.h>
#include "procman.h"
#include "disks.h"
#include "util.h"
#include "interface.h"
#include "iconthemewrapper.h"
Enumerations
enum DiskColumns {
DISK_DEVICE , DISK_DIR , DISK_TYPE , DISK_SUBVOLUME ,
DISK_TOTAL , DISK_FREE , DISK_AVAIL , DISK_USED ,
DISK_ICON , DISK_USED_PERCENTAGE , DISK_N_COLUMNS
}
Functions
int cb_update_disks (gpointer data)
void create_disk_view (ProcData *procdata, GtkBuilder *builder)
Enumeration Type Documentation
DiskColumns
enum DiskColumns
Enumerator
DISK_DEVICE
DISK_DIR
DISK_TYPE
DISK_SUBVOLUME
DISK_TOTAL
DISK_FREE
DISK_AVAIL
DISK_USED
DISK_ICON
DISK_USED_PERCENTAGE
DISK_N_COLUMNS
Definition at line 25 of file disks.cpp.
Function Documentation
cb_update_disks()
int cb_update_disks (gpointer data)
Definition at line 286 of file disks.cpp.
References ProcData::config, data, ProcData::disk_list, entries, ProcConfig::show_all_fs, and TRUE.
Referenced by cb_change_current_page().
create_disk_view()
void create_disk_view (ProcData * procdata, GtkBuilder * builder)
Definition at line 394 of file disks.cpp.
References _, DISK_AVAIL, DISK_DEVICE, DISK_DIR, DISK_FREE, DISK_ICON, ProcData::disk_list, DISK_N_COLUMNS, DISK_TOTAL, DISK_USED, DISK_USED_PERCENTAGE, FALSE, N_, NULL, procman_get_tree_state(), ProcData::settings, procman::storage_size_cell_data_func(), and TRUE.
Referenced by create_main_window().