MATE Desktop Environment: disks.h File Reference
disks.h File Reference
#include "procman.h"
Functions
void create_disk_view (ProcData *procdata, GtkBuilder *builder)
int cb_update_disks (gpointer procdata)
Function Documentation
cb_update_disks()
int cb_update_disks (gpointer procdata)
Definition at line 286 of file disks.cpp.
create_disk_view()
void create_disk_view (ProcData * procdata, GtkBuilder * builder)
Definition at line 394 of file disks.cpp.
References _, DISK_AVAIL, DISK_DEVICE, DISK_DIR, DISK_FREE, DISK_ICON, ProcData::disk_list, DISK_N_COLUMNS, DISK_TOTAL, DISK_USED, DISK_USED_PERCENTAGE, FALSE, N_, NULL, procman_get_tree_state(), ProcData::settings, procman::storage_size_cell_data_func(), and TRUE.
Referenced by create_main_window().