MATE Desktop Environment: display.c File Reference
display.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include "display-private.h"
#include "util.h"
#include "main.h"
#include "screen-private.h"
#include "window-private.h"
#include "window-props.h"
#include "group-props.h"
#include "frame-private.h"
#include "errors.h"
#include "keybindings.h"
#include "prefs.h"
#include "resizepopup.h"
#include "xprops.h"
#include "workspace.h"
#include "bell.h"
#include "effects.h"
#include "compositor.h"
#include <X11/Xatom.h>
#include <X11/cursorfont.h>
#include <X11/extensions/XRes.h>
#include <gdk/gdkx.h>
#include <string.h>
#include "atomnames.h"
Macros
#define GRAB_OP_IS_WINDOW_SWITCH(g)
#define item(x) #x,
#define item(x) the_display->atom_##x = atoms[idx++];
#define GRAB_MASK
#define MAX_FOCUS_BUTTON 4
#define PING_TIMEOUT_DELAY 5000
#define IN_TAB_CHAIN(w, t)
#define N_TARGETS 4
Functions
MetaGroup * get_focussed_group (MetaDisplay *display)
gboolean meta_display_open (void)
GSList * meta_display_list_windows (MetaDisplay *display)
void meta_display_close (MetaDisplay *display, guint32 timestamp)
MetaScreen * meta_display_screen_for_root (MetaDisplay *display, Window xroot)
MetaScreen * meta_display_screen_for_xwindow (MetaDisplay *display, Window xwindow)
MetaScreen * meta_display_screen_for_x_screen (MetaDisplay *display, Screen *xscreen)
void meta_display_grab (MetaDisplay *display)
void meta_display_ungrab (MetaDisplay *display)
MetaDisplay * meta_display_for_x_display (Display *xdisplay)
MetaDisplay * meta_get_display (void)
gboolean meta_grab_op_is_resizing (MetaGrabOp op)
gboolean meta_grab_op_is_moving (MetaGrabOp op)
guint32 meta_display_get_current_time (MetaDisplay *display)
guint32 meta_display_get_current_time_roundtrip (MetaDisplay *display)
void meta_display_queue_autoraise_callback (MetaDisplay *display, MetaWindow *window)
MetaWindow * meta_display_lookup_x_window (MetaDisplay *display, Window xwindow)
void meta_display_register_x_window (MetaDisplay *display, Window *xwindowp, MetaWindow *window)
void meta_display_unregister_x_window (MetaDisplay *display, Window xwindow)
gboolean meta_display_xwindow_is_a_no_focus_window (MetaDisplay *display, Window xwindow)
Cursor meta_display_create_x_cursor (MetaDisplay *display, MetaCursor cursor)
void meta_display_set_grab_op_cursor (MetaDisplay *display, MetaScreen *screen, MetaGrabOp op, gboolean change_pointer, Window grab_xwindow, guint32 timestamp)
gboolean meta_display_begin_grab_op (MetaDisplay *display, MetaScreen *screen, MetaWindow *window, MetaGrabOp op, gboolean pointer_already_grabbed, gboolean frame_action, int button, gulong modmask, guint32 timestamp, int root_x, int root_y)
void meta_display_end_grab_op (MetaDisplay *display, guint32 timestamp)
void meta_display_check_threshold_reached (MetaDisplay *display, int x, int y)
void meta_display_grab_window_buttons (MetaDisplay *display, Window xwindow)
void meta_display_ungrab_window_buttons (MetaDisplay *display, Window xwindow)
void meta_display_grab_focus_window_button (MetaDisplay *display, MetaWindow *window)
void meta_display_ungrab_focus_window_button (MetaDisplay *display, MetaWindow *window)
void meta_display_increment_event_serial (MetaDisplay *display)
void meta_display_update_active_window_hint (MetaDisplay *display)
void meta_display_queue_retheme_all_windows (MetaDisplay *display)
void meta_display_retheme_all (void)
void meta_display_set_cursor_theme (const char *theme, int size)
gboolean meta_is_syncing (void)
void meta_set_syncing (gboolean setting)
void meta_display_ping_window (MetaDisplay *display, MetaWindow *window, guint32 timestamp, MetaWindowPingFunc ping_reply_func, MetaWindowPingFunc ping_timeout_func, gpointer user_data)
gboolean meta_display_window_has_pending_pings (MetaDisplay *display, MetaWindow *window)
GList * meta_display_get_tab_list (MetaDisplay *display, MetaTabList type, MetaScreen *screen, MetaWorkspace *active_workspace)
MetaWindow * meta_display_get_tab_next (MetaDisplay *display, MetaTabList type, MetaScreen *screen, MetaWorkspace *workspace, MetaWindow *window, gboolean backward)
MetaWindow * meta_display_get_tab_current (MetaDisplay *display, MetaTabList type, MetaScreen *screen, MetaWorkspace *workspace)
int meta_resize_gravity_from_grab_op (MetaGrabOp op)
void meta_display_unmanage_screen (MetaDisplay *display, MetaScreen *screen, guint32 timestamp)
void meta_display_unmanage_windows_for_screen (MetaDisplay *display, MetaScreen *screen, guint32 timestamp)
int meta_display_stack_cmp (const void *a, const void *b)
void meta_display_devirtualize_modifiers (MetaDisplay *display, MetaVirtualModifier modifiers, unsigned int *mask)
void meta_display_increment_focus_sentinel (MetaDisplay *display)
void meta_display_decrement_focus_sentinel (MetaDisplay *display)
gboolean meta_display_focus_sentinel_clear (MetaDisplay *display)
void meta_display_set_input_focus_window (MetaDisplay *display, MetaWindow *window, gboolean focus_frame, guint32 timestamp)
void meta_display_focus_the_no_focus_window (MetaDisplay *display, MetaScreen *screen, guint32 timestamp)
void meta_display_remove_autoraise_callback (MetaDisplay *display)
Display * meta_display_get_xdisplay (MetaDisplay *display)
MetaCompositor * meta_display_get_compositor (MetaDisplay *display)
GSList * meta_display_get_screens (MetaDisplay *display)
gboolean meta_display_has_shape (MetaDisplay *display)
MetaWindow * meta_display_get_focus_window (MetaDisplay *display)
Detailed Description
Handles operations on an X display.
The display is represented as a MetaDisplay struct.
Definition in file display.c.
Macro Definition Documentation
GRAB_MASK
#define GRAB_MASK
Value:
                   (PointerMotionMask |                          \
                   ButtonPressMask | ButtonReleaseMask |        \
           EnterWindowMask | LeaveWindowMask)
GRAB_OP_IS_WINDOW_SWITCH
#define GRAB_OP_IS_WINDOW_SWITCH (g)
Value:
        (g == META_GRAB_OP_KEYBOARD_TABBING_NORMAL  ||  \
         g == META_GRAB_OP_KEYBOARD_TABBING_DOCK    ||  \
         g == META_GRAB_OP_KEYBOARD_TABBING_GROUP   ||  \
         g == META_GRAB_OP_KEYBOARD_TABBING_NORMAL_ALL_WORKSPACES ||  \
         g == META_GRAB_OP_KEYBOARD_ESCAPING_NORMAL ||  \
         g == META_GRAB_OP_KEYBOARD_ESCAPING_NORMAL_ALL_WORKSPACES ||  \
         g == META_GRAB_OP_KEYBOARD_ESCAPING_DOCK   ||  \
         g == META_GRAB_OP_KEYBOARD_ESCAPING_GROUP)
Definition at line 94 of file display.c.
IN_TAB_CHAIN
#define IN_TAB_CHAIN (w, t)
Value:
  (((t) == META_TAB_LIST_NORMAL && META_WINDOW_IN_NORMAL_TAB_CHAIN (w)) \
    || ((t) == META_TAB_LIST_NORMAL_ALL_WORKSPACES && META_WINDOW_IN_NORMAL_TAB_CHAIN (w)) \
    || ((t) == META_TAB_LIST_DOCKS && META_WINDOW_IN_DOCK_TAB_CHAIN (w)) \
    || ((t) == META_TAB_LIST_GROUP && META_WINDOW_IN_GROUP_TAB_CHAIN (w, get_focussed_group(w->display))))
Definition at line 4619 of file display.c.
item [1/2]
#define item (x) #x,
item [2/2]
#define item (x) the_display->atom_##x = atoms[idx++];
MAX_FOCUS_BUTTON
#define MAX_FOCUS_BUTTON 4
Definition at line 4141 of file display.c.
N_TARGETS
#define N_TARGETS 4
PING_TIMEOUT_DELAY
#define PING_TIMEOUT_DELAY 5000
How long, in milliseconds, we should wait after pinging a window before deciding it's not going to get back to us.
Definition at line 4351 of file display.c.
Function Documentation
get_focussed_group()
MetaGroup * get_focussed_group (MetaDisplay * display)
Definition at line 4611 of file display.c.
References _MetaDisplay::focus_window, _MetaWindow::group, and NULL.
meta_display_begin_grab_op()
gboolean meta_display_begin_grab_op (MetaDisplay * display, MetaScreen * screen, MetaWindow * window, MetaGrabOp op, gboolean pointer_already_grabbed, gboolean frame_action, int button, gulong modmask, guint32 timestamp, int root_x, int root_y)
Definition at line 3554 of file display.c.
References _MetaDisplay::compositor, _MetaWindow::desc, FALSE, _MetaWindow::frame, _MetaDisplay::grab_anchor_root_x, _MetaDisplay::grab_anchor_root_y, _MetaDisplay::grab_anchor_window_pos, _MetaDisplay::grab_button, _MetaDisplay::grab_frame_action, _MetaDisplay::grab_have_keyboard, _MetaDisplay::grab_have_pointer, _MetaDisplay::grab_initial_window_pos, _MetaDisplay::grab_initial_x, _MetaDisplay::grab_initial_y, _MetaDisplay::grab_last_moveresize_time, _MetaDisplay::grab_last_user_action_was_snap, _MetaDisplay::grab_latest_motion_x, _MetaDisplay::grab_latest_motion_y, _MetaDisplay::grab_mask, _MetaDisplay::grab_motion_notify_time, _MetaDisplay::grab_old_window_stacking, _MetaDisplay::grab_op, GRAB_OP_IS_WINDOW_SWITCH, _MetaDisplay::grab_resize_timeout_id, _MetaDisplay::grab_screen, _MetaDisplay::grab_threshold_movement_reached, _MetaDisplay::grab_tile_mode, _MetaDisplay::grab_tile_monitor_number, _MetaDisplay::grab_was_cancelled, _MetaDisplay::grab_window, _MetaDisplay::grab_wireframe_active, _MetaDisplay::grab_xwindow, meta_compositor_begin_move(), META_DEBUG_RESIZING, META_DEBUG_WINDOW_OPS, meta_display_set_grab_op_cursor(), meta_error_trap_pop_with_return(), meta_error_trap_push(), meta_grab_op_is_moving(), meta_grab_op_is_resizing(), META_GRAB_OP_KEYBOARD_ESCAPING_DOCK, META_GRAB_OP_KEYBOARD_ESCAPING_GROUP, META_GRAB_OP_KEYBOARD_ESCAPING_NORMAL, META_GRAB_OP_KEYBOARD_ESCAPING_NORMAL_ALL_WORKSPACES, META_GRAB_OP_KEYBOARD_TABBING_DOCK, META_GRAB_OP_KEYBOARD_TABBING_GROUP, META_GRAB_OP_KEYBOARD_TABBING_NORMAL, META_GRAB_OP_KEYBOARD_TABBING_NORMAL_ALL_WORKSPACES, META_GRAB_OP_KEYBOARD_WORKSPACE_MOVING, META_GRAB_OP_KEYBOARD_WORKSPACE_SWITCHING, META_GRAB_OP_NONE, meta_prefs_get_mate_accessibility(), meta_prefs_get_raise_on_click(), meta_prefs_get_reduced_resources(), meta_screen_ensure_tab_popup(), meta_screen_ensure_workspace_popup(), meta_screen_grab_all_keys(), meta_stack_get_positions(), META_TAB_LIST_DOCKS, META_TAB_LIST_GROUP, META_TAB_LIST_NORMAL, META_TAB_LIST_NORMAL_ALL_WORKSPACES, META_TAB_SHOW_ICON, META_TAB_SHOW_INSTANTLY, META_TILE_NONE, meta_warning(), meta_window_begin_wireframe(), meta_window_calc_showing(), meta_window_get_client_root_coords(), meta_window_grab_all_keys(), meta_window_raise(), meta_window_refresh_resize_popup(), NULL, op, _MetaWindow::rect, _MetaScreen::stack, _MetaDisplay::tab_popup_mouse_pressed, _MetaWindow::tile_mode, _MetaWindow::tile_monitor_number, TRUE, _MetaDisplay::xdisplay, _MetaScreen::xroot, _MetaFrame::xwindow, and _MetaWindow::xwindow.
Referenced by meta_core_begin_grab_op(), meta_window_begin_grab_op(), and meta_window_client_message().
meta_display_check_threshold_reached()
void meta_display_check_threshold_reached (MetaDisplay * display, int x, int y)
Definition at line 3986 of file display.c.
References FALSE, _MetaDisplay::grab_initial_x, _MetaDisplay::grab_initial_y, _MetaDisplay::grab_threshold_movement_reached, meta_prefs_get_raise_on_click(), and TRUE.
Referenced by meta_window_handle_mouse_grab_op_event().
meta_display_close()
void meta_display_close (MetaDisplay * display, guint32 timestamp)
Definition at line 885 of file display.c.
References _MetaDisplay::closing, _MetaDisplay::compositor, _MetaDisplay::error_traps, _MetaDisplay::grab_old_window_stacking, _MetaDisplay::leader_window, meta_bug(), meta_compositor_destroy(), meta_display_free_group_prop_hooks(), meta_display_free_window_prop_hooks(), meta_display_remove_autoraise_callback(), meta_display_shutdown_keys(), META_EXIT_SUCCESS, meta_prefs_remove_listener(), meta_quit(), meta_screen_free(), meta_ui_remove_event_func(), _MetaDisplay::name, NULL, _MetaDisplay::screens, _MetaDisplay::window_ids, and _MetaDisplay::xdisplay.
Referenced by meta_display_open(), and meta_display_unmanage_screen().
meta_display_create_x_cursor()
Cursor meta_display_create_x_cursor (MetaDisplay * display, MetaCursor cursor)
Definition at line 3376 of file display.c.
References META_CURSOR_BUSY, META_CURSOR_DEFAULT, META_CURSOR_EAST_RESIZE, META_CURSOR_MOVE_OR_RESIZE_WINDOW, META_CURSOR_NE_RESIZE, META_CURSOR_NORTH_RESIZE, META_CURSOR_NW_RESIZE, META_CURSOR_SE_RESIZE, META_CURSOR_SOUTH_RESIZE, META_CURSOR_SW_RESIZE, META_CURSOR_WEST_RESIZE, and _MetaDisplay::xdisplay.
Referenced by meta_frame_set_screen_cursor(), meta_screen_set_cursor(), and meta_screen_update_cursor().
meta_display_decrement_focus_sentinel()
void meta_display_decrement_focus_sentinel (MetaDisplay * display)
Definition at line 5359 of file display.c.
References _MetaDisplay::sentinel_counter.
meta_display_devirtualize_modifiers()
void meta_display_devirtualize_modifiers (MetaDisplay * display, MetaVirtualModifier modifiers, unsigned int * mask)
Definition at line 5211 of file display.c.
References _MetaDisplay::hyper_mask, mask, _MetaDisplay::meta_mask, META_VIRTUAL_ALT_MASK, META_VIRTUAL_CONTROL_MASK, META_VIRTUAL_HYPER_MASK, META_VIRTUAL_META_MASK, META_VIRTUAL_MOD2_MASK, META_VIRTUAL_MOD3_MASK, META_VIRTUAL_MOD4_MASK, META_VIRTUAL_MOD5_MASK, META_VIRTUAL_SHIFT_MASK, META_VIRTUAL_SUPER_MASK, and _MetaDisplay::super_mask.
meta_display_end_grab_op()
void meta_display_end_grab_op (MetaDisplay * display, guint32 timestamp)
Definition at line 3840 of file display.c.
References _MetaDisplay::compositor, FALSE, _MetaDisplay::grab_have_keyboard, _MetaDisplay::grab_have_pointer, _MetaDisplay::grab_old_window_stacking, _MetaDisplay::grab_op, GRAB_OP_IS_WINDOW_SWITCH, _MetaDisplay::grab_resize_popup, _MetaDisplay::grab_resize_timeout_id, _MetaDisplay::grab_screen, _MetaDisplay::grab_threshold_movement_reached, _MetaDisplay::grab_tile_mode, _MetaDisplay::grab_tile_monitor_number, _MetaDisplay::grab_was_cancelled, _MetaDisplay::grab_window, _MetaDisplay::grab_wireframe_active, _MetaDisplay::grab_wireframe_rect, _MetaDisplay::grab_xwindow, _MetaRectangle::height, meta_compositor_end_move(), META_DEBUG_WINDOW_OPS, meta_display_cleanup_edges(), meta_grab_op_is_moving(), meta_grab_op_is_resizing(), META_GRAB_OP_KEYBOARD_WORKSPACE_MOVING, META_GRAB_OP_KEYBOARD_WORKSPACE_SWITCHING, META_GRAB_OP_NONE, meta_prefs_get_raise_on_click(), meta_resize_gravity_from_grab_op(), meta_screen_ungrab_all_keys(), META_TILE_NONE, meta_tile_preview_hide(), meta_ui_resize_popup_free(), meta_ui_tab_popup_free(), meta_window_calc_showing(), meta_window_end_wireframe(), meta_window_move(), meta_window_raise(), meta_window_resize_with_gravity(), meta_window_ungrab_all_keys(), NULL, _MetaWindow::shaken_loose, _MetaScreen::tab_popup, _MetaDisplay::tab_popup_mouse_pressed, _MetaScreen::tile_preview, TRUE, _MetaDisplay::ungrab_should_not_cause_focus_window, _MetaRectangle::width, _MetaRectangle::x, _MetaDisplay::xdisplay, and _MetaRectangle::y.
Referenced by meta_core_end_grab_op(), meta_display_process_key_event(), meta_window_client_message(), meta_window_free(), and meta_window_handle_mouse_grab_op_event().
meta_display_focus_sentinel_clear()
gboolean meta_display_focus_sentinel_clear (MetaDisplay * display)
Definition at line 5368 of file display.c.
References _MetaDisplay::sentinel_counter.
meta_display_focus_the_no_focus_window()
void meta_display_focus_the_no_focus_window (MetaDisplay * display, MetaScreen * screen, guint32 timestamp)
Definition at line 5496 of file display.c.
References _MetaDisplay::active_screen, _MetaDisplay::expected_focus_window, _MetaDisplay::last_focus_time, meta_display_remove_autoraise_callback(), _MetaScreen::no_focus_window, NULL, and _MetaDisplay::xdisplay.
Referenced by meta_display_open(), and meta_workspace_focus_default_window().
meta_display_for_x_display()
MetaDisplay * meta_display_for_x_display (Display * xdisplay)
Returns the singleton MetaDisplay if "xdisplay" matches the X display it's managing; otherwise gives a warning and returns NULL. When we were claiming to be able to manage multiple displays, this was supposed to find the display out of the list which matched that display. Now it's merely an extra sanity check.
Parameters
xdisplay An X display
Returns
The singleton X display, or NULL if "xdisplay" isn't the one we're managing.
Definition at line 1068 of file display.c.
References meta_warning(), NULL, and _MetaDisplay::xdisplay.
Referenced by meta_core_begin_grab_op(), meta_core_end_grab_op(), meta_core_get(), meta_core_get_grab_button(), meta_core_get_grab_frame(), meta_core_get_grab_op(), meta_core_get_workspace_name_with_index(), meta_core_grab_buttons(), meta_core_increment_event_serial(), meta_core_lower_beneath_focus_window(), and meta_screen_for_x_screen().
meta_display_get_compositor()
MetaCompositor * meta_display_get_compositor (MetaDisplay * display)
Definition at line 5532 of file display.c.
References _MetaDisplay::compositor.
Referenced by meta_frames_apply_shapes().
meta_display_get_current_time()
guint32 meta_display_get_current_time (MetaDisplay * display)
Definition at line 1224 of file display.c.
References _MetaDisplay::current_time.
Referenced by meta_display_get_current_time_roundtrip(), meta_display_increment_focus_sentinel(), and meta_window_client_message().
meta_display_get_current_time_roundtrip()
guint32 meta_display_get_current_time_roundtrip (MetaDisplay * display)
Definition at line 1231 of file display.c.
References meta_display_get_current_time(), NULL, _MetaDisplay::timestamp_pinging_window, and _MetaDisplay::xdisplay.
Referenced by meta_window_client_message(), meta_window_make_fullscreen_internal(), meta_window_maximize(), and meta_window_new_with_attrs().
meta_display_get_focus_window()
MetaWindow * meta_display_get_focus_window (MetaDisplay * display)
Definition at line 5550 of file display.c.
References _MetaDisplay::focus_window.
meta_display_get_screens()
GSList * meta_display_get_screens (MetaDisplay * display)
Definition at line 5538 of file display.c.
References _MetaDisplay::screens.
meta_display_get_tab_current()
MetaWindow * meta_display_get_tab_current (MetaDisplay * display, MetaTabList type, MetaScreen * screen, MetaWorkspace * workspace)
Definition at line 4868 of file display.c.
References _MetaDisplay::focus_window, IN_TAB_CHAIN, meta_window_located_on_workspace(), NULL, _MetaWindow::screen, and type.
meta_display_get_tab_list()
GList * meta_display_get_tab_list (MetaDisplay * display, MetaTabList type, MetaScreen * screen, MetaWorkspace * active_workspace)
Definition at line 4726 of file display.c.
References IN_TAB_CHAIN, meta_display_list_windows(), META_TAB_LIST_NORMAL, META_TAB_LIST_NORMAL_ALL_WORKSPACES, _MetaWindow::minimized, _MetaWorkspace::mru_list, NULL, _MetaWindow::screen, type, _MetaWindow::wm_state_demands_attention, and _MetaWindow::workspace.
Referenced by meta_display_get_tab_next(), and meta_screen_ensure_tab_popup().
meta_display_get_tab_next()
MetaWindow * meta_display_get_tab_next (MetaDisplay * display, MetaTabList type, MetaScreen * screen, MetaWorkspace * workspace, MetaWindow * window, gboolean backward)
Definition at line 4818 of file display.c.
References _MetaWindow::display, _MetaDisplay::focus_window, meta_display_get_tab_list(), NULL, TRUE, and type.
meta_display_get_xdisplay()
Display * meta_display_get_xdisplay (MetaDisplay * display)
Definition at line 5526 of file display.c.
References _MetaDisplay::xdisplay.
Referenced by meta_error_trap_pop(), meta_error_trap_pop_with_return(), and meta_error_trap_push().
meta_display_grab()
void meta_display_grab (MetaDisplay * display)
Definition at line 1025 of file display.c.
References _MetaDisplay::server_grab_count, and _MetaDisplay::xdisplay.
Referenced by meta_display_open(), meta_effects_begin_wireframe(), meta_screen_free(), meta_screen_manage_all_windows(), meta_window_ensure_frame(), meta_window_new(), and meta_window_new_with_attrs().
meta_display_grab_focus_window_button()
void meta_display_grab_focus_window_button (MetaDisplay * display, MetaWindow * window)
Definition at line 4143 of file display.c.
References _MetaWindow::desc, _MetaWindow::have_focus_click_grab, MAX_FOCUS_BUTTON, META_FOCUS_MODE_CLICK, meta_prefs_get_focus_mode(), TRUE, and _MetaWindow::xwindow.
Referenced by meta_window_new_with_attrs(), and meta_window_notify_focus().
meta_display_grab_window_buttons()
void meta_display_grab_window_buttons (MetaDisplay * display, Window xwindow)
Definition at line 4065 of file display.c.
References debug, FALSE, NULL, TRUE, and _MetaDisplay::window_grab_modifiers.
Referenced by meta_core_grab_buttons(), and meta_window_new_with_attrs().
meta_display_has_shape()
gboolean meta_display_has_shape (MetaDisplay * display)
Definition at line 5544 of file display.c.
References META_DISPLAY_HAS_SHAPE.
meta_display_increment_event_serial()
void meta_display_increment_event_serial (MetaDisplay * display)
Definition at line 4215 of file display.c.
References _MetaDisplay::leader_window, and _MetaDisplay::xdisplay.
Referenced by meta_core_increment_event_serial().
meta_display_increment_focus_sentinel()
void meta_display_increment_focus_sentinel (MetaDisplay * display)
Definition at line 5343 of file display.c.
References data, meta_display_get_current_time(), _MetaDisplay::screens, _MetaDisplay::sentinel_counter, and _MetaDisplay::xdisplay.
meta_display_list_windows()
GSList * meta_display_list_windows (MetaDisplay * display)
Definition at line 834 of file display.c.
References NULL, and _MetaDisplay::window_ids.
Referenced by meta_display_get_tab_list(), meta_display_queue_retheme_all_windows(), meta_display_unmanage_windows_for_screen(), meta_invalidate_all_icons(), meta_invalidate_default_icons(), meta_window_foreach_transient(), meta_window_place(), and meta_workspace_list_windows().
meta_display_lookup_x_window()
MetaWindow * meta_display_lookup_x_window (MetaDisplay * display, Window xwindow)
Definition at line 3329 of file display.c.
References _MetaDisplay::window_ids.
Referenced by meta_core_get(), meta_display_open(), meta_display_process_key_event(), meta_screen_composite_all_windows(), meta_window_foreach_ancestor(), meta_window_get_transient_for(), meta_window_new_with_attrs(), and meta_window_place().
meta_display_open()
gboolean meta_display_open (void)
Opens a new display, sets it up, initialises all the X extensions we will need, and adds it to the list of displays.
Returns
True if the display was opened successfully, and False otherwise– that is, if the display doesn't exist or it already has a window manager.
Definition at line 328 of file display.c.
References _, _MetaDisplay::active_screen, _MetaDisplay::allow_terminal_deactivation, _MetaDisplay::autoraise_timeout_id, _MetaDisplay::autoraise_window, _MetaDisplay::closing, _MetaDisplay::compositor, _MetaDisplay::current_time, data, _MetaDisplay::display_opening, _MetaDisplay::error_trap_handler, _MetaDisplay::error_trap_synced_at_last_pop, _MetaDisplay::error_traps, _MetaDisplay::events, _MetaDisplay::expected_focus_window, FALSE, _MetaDisplay::focus_window, _MetaDisplay::grab_edge_resistance_data, _MetaDisplay::grab_have_keyboard, _MetaDisplay::grab_old_window_stacking, _MetaDisplay::grab_op, _MetaDisplay::grab_resize_popup, _MetaDisplay::grab_resize_timeout_id, _MetaDisplay::grab_screen, _MetaDisplay::grab_tile_mode, _MetaDisplay::grab_tile_monitor_number, _MetaDisplay::grab_window, _MetaDisplay::grab_wireframe_active, _MetaDisplay::group_prop_hooks, _MetaDisplay::groups_by_leader, _MetaDisplay::have_xres, idx, _MetaDisplay::ignored_serials, _MetaDisplay::last_focus_time, _MetaDisplay::last_user_time, _MetaDisplay::leader_window, meta_bell_init(), meta_create_offscreen_window(), meta_display_close(), meta_display_focus_the_no_focus_window(), meta_display_grab(), meta_display_init_group_prop_hooks(), meta_display_init_keys(), meta_display_init_window_prop_hooks(), meta_display_lookup_x_window(), meta_display_set_input_focus_window(), meta_display_ungrab(), meta_error_trap_pop(), meta_error_trap_push(), META_GRAB_OP_NONE, meta_is_syncing(), meta_prefs_add_listener(), meta_prefs_get_compositing_manager(), meta_prefs_get_cursor_size(), meta_prefs_get_cursor_theme(), meta_prop_set_utf8_string_hint(), meta_screen_manage_all_windows(), meta_screen_new(), META_TILE_NONE, meta_ui_add_event_func(), meta_ui_get_display(), meta_unsigned_long_equal(), meta_unsigned_long_hash(), meta_warning(), _MetaDisplay::mouse_mode, N_IGNORED_SERIALS, _MetaDisplay::name, NULL, _MetaDisplay::pending_pings, _MetaDisplay::prop_hooks, _MetaDisplay::screens, _MetaDisplay::sentinel_counter, _MetaDisplay::server_grab_count, _MetaDisplay::static_gravity_works, _MetaDisplay::tab_popup_mouse_pressed, _MetaDisplay::timestamp_pinging_window, TRUE, _MetaDisplay::ungrab_should_not_cause_focus_window, _MetaDisplay::window_ids, _MetaDisplay::window_menu, _MetaDisplay::window_with_menu, _MetaDisplay::xdisplay, and _MetaDisplay::xinerama_cache_invalidated.
Referenced by main().
meta_display_queue_autoraise_callback()
void meta_display_queue_autoraise_callback (MetaDisplay * display, MetaWindow * window)
Definition at line 1365 of file display.c.
References _MetaDisplay::autoraise_timeout_id, _MetaDisplay::autoraise_window, _MetaWindow::desc, _MetaWindow::display, META_DEBUG_FOCUS, meta_prefs_get_auto_raise_delay(), and _MetaWindow::xwindow.
Referenced by meta_workspace_focus_default_window().
meta_display_queue_retheme_all_windows()
void meta_display_queue_retheme_all_windows (MetaDisplay * display)
Definition at line 4252 of file display.c.
References _MetaWindow::frame, meta_display_list_windows(), meta_frame_queue_draw(), META_QUEUE_MOVE_RESIZE, meta_window_queue(), _MetaFrame::need_reapply_frame_shape, NULL, and TRUE.
Referenced by meta_display_retheme_all().
meta_display_register_x_window()
void meta_display_register_x_window (MetaDisplay * display, Window * xwindowp, MetaWindow * window)
Definition at line 3336 of file display.c.
References NULL, and _MetaDisplay::window_ids.
Referenced by meta_window_ensure_frame(), and meta_window_new_with_attrs().
meta_display_remove_autoraise_callback()
void meta_display_remove_autoraise_callback (MetaDisplay * display)
Definition at line 5515 of file display.c.
References _MetaDisplay::autoraise_timeout_id, _MetaDisplay::autoraise_window, and NULL.
Referenced by meta_display_close(), meta_display_focus_the_no_focus_window(), and meta_display_set_input_focus_window().
meta_display_retheme_all()
void meta_display_retheme_all (void)
Definition at line 4278 of file display.c.
References meta_display_queue_retheme_all_windows(), and meta_get_display().
meta_display_screen_for_root()
MetaScreen * meta_display_screen_for_root (MetaDisplay * display, Window xroot)
Definition at line 962 of file display.c.
References NULL, _MetaDisplay::screens, and _MetaScreen::xroot.
Referenced by meta_core_get_workspace_name_with_index(), and meta_display_process_key_event().
meta_display_screen_for_x_screen()
MetaScreen * meta_display_screen_for_x_screen (MetaDisplay * display, Screen * xscreen)
Definition at line 1004 of file display.c.
References NULL, _MetaDisplay::screens, and _MetaScreen::xscreen.
Referenced by meta_display_screen_for_xwindow(), and meta_screen_for_x_screen().
meta_display_screen_for_xwindow()
MetaScreen * meta_display_screen_for_xwindow (MetaDisplay * display, Window xwindow)
Definition at line 982 of file display.c.
References meta_display_screen_for_x_screen(), meta_error_trap_pop(), meta_error_trap_push(), NULL, TRUE, and _MetaDisplay::xdisplay.
Referenced by meta_core_begin_grab_op(), meta_core_lower_beneath_focus_window(), and meta_display_process_key_event().
meta_display_set_cursor_theme()
void meta_display_set_cursor_theme (const char * theme, int size)
Definition at line 4284 of file display.c.
References meta_get_display(), meta_screen_update_cursor(), NULL, _MetaDisplay::screens, and _MetaDisplay::xdisplay.
meta_display_set_grab_op_cursor()
void meta_display_set_grab_op_cursor (MetaDisplay * display, MetaScreen * screen, MetaGrabOp op, gboolean change_pointer, Window grab_xwindow, guint32 timestamp)
Definition at line 3485 of file display.c.
References FALSE, _MetaDisplay::grab_have_pointer, GRAB_MASK, META_DEBUG_WINDOW_OPS, meta_error_trap_pop(), meta_error_trap_pop_with_return(), meta_error_trap_push(), NULL, op, TRUE, _MetaDisplay::xdisplay, and _MetaScreen::xroot.
Referenced by meta_display_begin_grab_op(), and meta_window_update_keyboard_resize().
meta_display_set_input_focus_window()
void meta_display_set_input_focus_window (MetaDisplay * display, MetaWindow * window, gboolean focus_frame, guint32 timestamp)
Definition at line 5472 of file display.c.
References _MetaDisplay::active_screen, _MetaDisplay::autoraise_window, _MetaWindow::display, _MetaDisplay::expected_focus_window, FALSE, _MetaWindow::frame, _MetaDisplay::last_focus_time, meta_display_remove_autoraise_callback(), meta_error_trap_pop(), meta_error_trap_push(), _MetaWindow::screen, _MetaDisplay::xdisplay, _MetaFrame::xwindow, and _MetaWindow::xwindow.
Referenced by meta_display_open(), and meta_window_focus().
meta_display_stack_cmp()
int meta_display_stack_cmp (const void * a, const void * b)
Definition at line 5193 of file display.c.
References b, meta_stack_windows_cmp(), _MetaScreen::number, _MetaWindow::screen, and _MetaScreen::stack.
Referenced by meta_display_unmanage_windows_for_screen().
meta_display_ungrab()
void meta_display_ungrab (MetaDisplay * display)
Definition at line 1037 of file display.c.
References meta_bug(), _MetaDisplay::server_grab_count, and _MetaDisplay::xdisplay.
Referenced by meta_display_open(), meta_effects_end_wireframe(), meta_screen_free(), meta_screen_manage_all_windows(), meta_window_ensure_frame(), meta_window_new(), and meta_window_new_with_attrs().
meta_display_ungrab_focus_window_button()
void meta_display_ungrab_focus_window_button (MetaDisplay * display, MetaWindow * window)
Definition at line 4192 of file display.c.
References _MetaWindow::desc, FALSE, _MetaWindow::have_focus_click_grab, MAX_FOCUS_BUTTON, and _MetaWindow::xwindow.
Referenced by meta_window_free(), and meta_window_notify_focus().
meta_display_ungrab_window_buttons()
void meta_display_ungrab_window_buttons (MetaDisplay * display, Window xwindow)
Definition at line 4115 of file display.c.
References debug, FALSE, NULL, and _MetaDisplay::window_grab_modifiers.
Referenced by meta_window_free().
meta_display_unmanage_screen()
void meta_display_unmanage_screen (MetaDisplay * display, MetaScreen * screen, guint32 timestamp)
Definition at line 5153 of file display.c.
References meta_display_close(), meta_screen_free(), _MetaDisplay::name, NULL, _MetaScreen::number, and _MetaDisplay::screens.
meta_display_unmanage_windows_for_screen()
void meta_display_unmanage_windows_for_screen (MetaDisplay * display, MetaScreen * screen, guint32 timestamp)
Definition at line 5171 of file display.c.
References meta_display_list_windows(), meta_display_stack_cmp(), meta_window_free(), and NULL.
Referenced by meta_screen_free().
meta_display_unregister_x_window()
void meta_display_unregister_x_window (MetaDisplay * display, Window xwindow)
Definition at line 3346 of file display.c.
References NULL, and _MetaDisplay::window_ids.
Referenced by meta_window_destroy_frame(), and meta_window_free().
meta_display_update_active_window_hint()
void meta_display_update_active_window_hint (MetaDisplay * display)
Definition at line 4223 of file display.c.
References data, FALSE, _MetaDisplay::focus_window, meta_error_trap_pop(), meta_error_trap_push(), NULL, _MetaDisplay::screens, _MetaDisplay::xdisplay, _MetaScreen::xroot, and _MetaWindow::xwindow.
Referenced by meta_window_notify_focus().
meta_display_xwindow_is_a_no_focus_window()
gboolean meta_display_xwindow_is_a_no_focus_window (MetaDisplay * display, Window xwindow)
Definition at line 3358 of file display.c.
References FALSE, _MetaScreen::no_focus_window, NULL, _MetaDisplay::screens, and TRUE.
Referenced by meta_window_new_with_attrs().
meta_get_display()
MetaDisplay * meta_get_display (void)
Accessor for the singleton MetaDisplay.
Returns
The only MetaDisplay there is. This can be NULL, but only during startup.
Definition at line 1086 of file display.c.
Referenced by meta_display_retheme_all(), meta_display_set_cursor_theme(), meta_invalidate_all_icons(), meta_invalidate_default_icons(), and meta_set_syncing().
meta_grab_op_is_moving()
gboolean meta_grab_op_is_moving (MetaGrabOp op)
Definition at line 1209 of file display.c.
References FALSE, META_GRAB_OP_KEYBOARD_MOVING, META_GRAB_OP_MOVING, op, and TRUE.
Referenced by meta_display_begin_grab_op(), meta_display_end_grab_op(), meta_window_handle_mouse_grab_op_event(), and meta_window_unmaximize().
meta_grab_op_is_resizing()
gboolean meta_grab_op_is_resizing (MetaGrabOp op)
Definition at line 1180 of file display.c.
References FALSE, META_GRAB_OP_KEYBOARD_RESIZING_E, META_GRAB_OP_KEYBOARD_RESIZING_N, META_GRAB_OP_KEYBOARD_RESIZING_NE, META_GRAB_OP_KEYBOARD_RESIZING_NW, META_GRAB_OP_KEYBOARD_RESIZING_S, META_GRAB_OP_KEYBOARD_RESIZING_SE, META_GRAB_OP_KEYBOARD_RESIZING_SW, META_GRAB_OP_KEYBOARD_RESIZING_UNKNOWN, META_GRAB_OP_KEYBOARD_RESIZING_W, META_GRAB_OP_RESIZING_E, META_GRAB_OP_RESIZING_N, META_GRAB_OP_RESIZING_NE, META_GRAB_OP_RESIZING_NW, META_GRAB_OP_RESIZING_S, META_GRAB_OP_RESIZING_SE, META_GRAB_OP_RESIZING_SW, META_GRAB_OP_RESIZING_W, op, and TRUE.
Referenced by meta_display_begin_grab_op(), meta_display_end_grab_op(), and meta_window_handle_mouse_grab_op_event().
meta_is_syncing()
gboolean meta_is_syncing (void)
Returns whether X synchronisation is currently enabled.
Returns
true if we must wait for events whenever we send X requests; false otherwise.
Definition at line 4325 of file display.c.
Referenced by meta_display_open().
meta_resize_gravity_from_grab_op()
int meta_resize_gravity_from_grab_op (MetaGrabOp op)
Definition at line 4888 of file display.c.
References META_GRAB_OP_KEYBOARD_RESIZING_E, META_GRAB_OP_KEYBOARD_RESIZING_N, META_GRAB_OP_KEYBOARD_RESIZING_NE, META_GRAB_OP_KEYBOARD_RESIZING_NW, META_GRAB_OP_KEYBOARD_RESIZING_S, META_GRAB_OP_KEYBOARD_RESIZING_SE, META_GRAB_OP_KEYBOARD_RESIZING_SW, META_GRAB_OP_KEYBOARD_RESIZING_UNKNOWN, META_GRAB_OP_KEYBOARD_RESIZING_W, META_GRAB_OP_RESIZING_E, META_GRAB_OP_RESIZING_N, META_GRAB_OP_RESIZING_NE, META_GRAB_OP_RESIZING_NW, META_GRAB_OP_RESIZING_S, META_GRAB_OP_RESIZING_SE, META_GRAB_OP_RESIZING_SW, META_GRAB_OP_RESIZING_W, and op.
Referenced by meta_display_end_grab_op().
meta_set_syncing()
void meta_set_syncing (gboolean setting)
A handy way to turn on synchronisation on or off for every display.
Definition at line 4337 of file display.c.
References meta_get_display().
Referenced by main().