MATE Desktop Environment: djvu-links.c File Reference
djvu-links.c File Reference
#include <config.h>
#include <string.h>
#include <glib.h>
#include <libdjvu/miniexp.h>
#include "djvu-document.h"
#include "djvu-links.h"
#include "djvu-document-private.h"
#include "ev-document-links.h"
#include "ev-mapping-list.h"
Functions
gboolean djvu_links_has_document_links (EvDocumentLinks *document_links)
EvMappingList * djvu_links_get_links (EvDocumentLinks *document_links, gint page, double scale_factor)
EvLinkDest * djvu_links_find_link_dest (EvDocumentLinks *document_links, const gchar *link_name)
gint djvu_links_find_link_page (EvDocumentLinks *document_links, const gchar *link_name)
GtkTreeModel * djvu_links_get_links_model (EvDocumentLinks *document_links)
Function Documentation
djvu_links_find_link_dest()
EvLinkDest * djvu_links_find_link_dest (EvDocumentLinks * document_links, const gchar * link_name)
Definition at line 401 of file djvu-links.c.
References DJVU_DOCUMENT, and NULL.
djvu_links_find_link_page()
gint djvu_links_find_link_page (EvDocumentLinks * document_links, const gchar * link_name)
Definition at line 417 of file djvu-links.c.
References DJVU_DOCUMENT.
djvu_links_get_links()
EvMappingList * djvu_links_get_links (EvDocumentLinks * document_links, gint page, double scale_factor)
Definition at line 362 of file djvu-links.c.
References _EvMapping::area, _DjvuDocument::d_document, DJVU_DOCUMENT, djvu_handle_events(), ev_mapping_list_new(), NULL, TRUE, _EvRectangle::x1, _EvRectangle::x2, _EvRectangle::y1, and _EvRectangle::y2.
djvu_links_get_links_model()
GtkTreeModel * djvu_links_get_links_model (EvDocumentLinks * document_links)
Definition at line 433 of file djvu-links.c.
References _DjvuDocument::d_document, DJVU_DOCUMENT, djvu_handle_events(), EV_DOCUMENT_LINKS_COLUMN_NUM_COLUMNS, NULL, and TRUE.
djvu_links_has_document_links()
gboolean djvu_links_has_document_links (EvDocumentLinks * document_links)
Definition at line 345 of file djvu-links.c.
References _DjvuDocument::d_document, DJVU_DOCUMENT, djvu_handle_events(), FALSE, NULL, and TRUE.