MATE Desktop Environment: dlg-package-installer.h File Reference
dlg-package-installer.h File Reference
#include "fr-window.h"
Functions
void dlg_package_installer (FrWindow *window, FrArchive *archive, FrAction action)
Function Documentation
dlg_package_installer()
void dlg_package_installer (FrWindow * window, FrArchive * archive, FrAction action)
Definition at line 265 of file dlg-package-installer.c.
References _, _gtk_message_dialog_new(), action, command, FR_COMMAND_CAN_READ, FR_COMMAND_CAN_READ_WRITE, fr_command_get_packages(), FR_PROC_ERROR_GENERIC, get_preferred_command_for_mime_type(), and NULL.