MATE Desktop Environment: dlg-prop.h File Reference
dlg-prop.h File Reference
#include "fr-window.h"
Functions
void dlg_prop (FrWindow *window)
Function Documentation
dlg_prop()
void dlg_prop (FrWindow * window)
Definition at line 56 of file dlg-prop.c.
References _, _FrWindow::archive, _FrArchive::command, data, _FrCommand::files, fr_window_archive_is_present(), fr_window_get_archive_uri(), g_uri_display_basename(), get_file_mtime(), get_file_size(), GET_LABEL, GET_WIDGET, _FrCommand::mime_type, _FrCommand::n_regular_files, NULL, remove_level_from_path(), FileData::size, and TRUE.
Referenced by activate_action_properties().