MATE Desktop Environment: dlg-new.h File Reference
dlg-new.h File Reference
#include <gtk/gtk.h>
#include "eggfileformatchooser.h"
#include "fr-window.h"
Classes
struct DlgNewData
Functions
DlgNewData * dlg_new (FrWindow *window)
DlgNewData * dlg_save_as (FrWindow *window, const char *default_name)
const char * dlg_new_data_get_password (DlgNewData *data)
gboolean dlg_new_data_get_encrypt_header (DlgNewData *data)
int dlg_new_data_get_volume_size (DlgNewData *data)
Function Documentation
dlg_new()
DlgNewData * dlg_new (FrWindow * window)
Definition at line 377 of file dlg-new.c.
References C_, create_type, data, and NULL.
Referenced by show_new_archive_dialog().
dlg_new_data_get_encrypt_header()
gboolean dlg_new_data_get_encrypt_header (DlgNewData * data)
Definition at line 416 of file dlg-new.c.
References capabilities, data, FALSE, FR_COMMAND_CAN_ENCRYPT, FR_COMMAND_CAN_ENCRYPT_HEADER, idx, mime_type_desc, and NULL.
dlg_new_data_get_password()
const char * dlg_new_data_get_password (DlgNewData * data)
Definition at line 400 of file dlg-new.c.
References capabilities, data, FR_COMMAND_CAN_ENCRYPT, idx, mime_type_desc, and NULL.
dlg_new_data_get_volume_size()
int dlg_new_data_get_volume_size (DlgNewData * data)
Definition at line 439 of file dlg-new.c.
References capabilities, data, FR_COMMAND_CAN_CREATE_VOLUMES, idx, MEGABYTE, and mime_type_desc.
dlg_save_as()
DlgNewData * dlg_save_as (FrWindow * window, const char * default_name)
Definition at line 388 of file dlg-new.c.
References C_, data, and save_type.
Referenced by activate_action_save_as(), and show_new_archive_dialog().