MATE Desktop Environment: dlg-extract.c File Reference
dlg-extract.c File Reference
#include <config.h>
#include <string.h>
#include <unistd.h>
#include <gtk/gtk.h>
#include "file-utils.h"
#include "fr-init.h"
#include "gtk-utils.h"
#include "fr-window.h"
#include "typedefs.h"
#include "dlg-extract.h"
Macros
#define GET_WIDGET(x) (GTK_WIDGET (gtk_builder_get_object (data->builder, (x))))
Functions
void dlg_extract (GtkWidget *widget, gpointer callback_data)
void dlg_extract_folder_from_sidebar (GtkWidget *widget, gpointer callback_data)
Macro Definition Documentation
GET_WIDGET
#define GET_WIDGET (x) (GTK_WIDGET (gtk_builder_get_object (data->builder, (x))))
Definition at line 34 of file dlg-extract.c.
Function Documentation
dlg_extract()
void dlg_extract (GtkWidget * widget, gpointer callback_data)
Definition at line 375 of file dlg-extract.c.
References FALSE, and fr_window_get_selection().
Referenced by activate_action_extract(), and activate_popup_extract().
dlg_extract_folder_from_sidebar()
void dlg_extract_folder_from_sidebar (GtkWidget * widget, gpointer callback_data)
Definition at line 387 of file dlg-extract.c.
References fr_window_get_selection(), and TRUE.
Referenced by activate_popup_extract_folder_from_sidebar().