MATE Desktop Environment: dlg-batch-add.h File Reference
dlg-batch-add.h File Reference
#include "fr-window.h"
Functions
void dlg_batch_add_files (FrWindow *window, GList *file_list)
Function Documentation
dlg_batch_add_files()
void dlg_batch_add_files (FrWindow * window, GList * file_list)
Definition at line 463 of file dlg-batch-add.c.
References _gtk_entry_set_filename_text(), check_permissions(), data, FrMimeTypeDescription::default_ext, ENGRAMPA_SCHEMA_BATCH_ADD, ENGRAMPA_SCHEMA_GENERAL, FALSE, file_list, file_name_from_path(), GET_ENTRY, GET_FILE_CHOOSER, get_home_uri(), GET_TOGGLE_BUTTON, GET_WIDGET, GET_WINDOW, MEGABYTE, mime_type_desc, NULL, PREF_BATCH_ADD_DEFAULT_EXTENSION, PREF_BATCH_ADD_VOLUME_SIZE, PREF_GENERAL_ENCRYPT_HEADER, remove_level_from_path(), save_type, single_file_save_type, sort_mime_types_by_extension(), TRUE, and uri_is_file().