MATE Desktop Environment: drawer.h File Reference
drawer.h File Reference
#include "panel.h"
Classes
struct Drawer
Functions
void panel_drawer_create (PanelToplevel *toplevel, int position, GIcon *custom_icon, gboolean use_custom_icon, const char *tooltip)
char * panel_drawer_create_with_id (const char *toplevel_id, int position, GIcon *custom_icon, gboolean use_custom_icon, const char *tooltip)
void drawer_load_from_gsettings (PanelWidget *panel_widget, gboolean locked, gint position, const char *id)
void panel_drawer_set_dnd_enabled (Drawer *drawer, gboolean dnd_enabled)
void drawer_query_deletion (Drawer *drawer)
Function Documentation
drawer_load_from_gsettings()
void drawer_load_from_gsettings (PanelWidget * panel_widget, gboolean locked, gint position, const char * id)
Definition at line 656 of file drawer.c.
References NULL, PANEL_OBJECT_ATTACHED_TOPLEVEL_ID_KEY, PANEL_OBJECT_CUSTOM_ICON_KEY, PANEL_OBJECT_PATH, PANEL_OBJECT_SCHEMA, PANEL_OBJECT_TOOLTIP_KEY, PANEL_OBJECT_USE_CUSTOM_ICON_KEY, panel_profile_load_toplevel(), _PanelWidget::toplevel, and TRUE.
drawer_query_deletion()
void drawer_query_deletion (Drawer * drawer)
Definition at line 724 of file drawer.c.
References _PanelWidget::applet_list, Drawer::info, panel_deletion_dialog(), panel_global_config_get_confirm_panel_remove(), panel_profile_delete_object(), panel_toplevel_get_panel_widget(), and Drawer::toplevel.
panel_drawer_create()
void panel_drawer_create (PanelToplevel * toplevel, int position, GIcon * custom_icon, gboolean use_custom_icon, const char * tooltip)
Definition at line 617 of file drawer.c.
References FALSE, id, NULL, PANEL_GSETTINGS_OBJECTS, PANEL_OBJECT_DRAWER, panel_profile_add_to_list(), and panel_profile_prepare_object().
panel_drawer_create_with_id()
char * panel_drawer_create_with_id (const char * toplevel_id, int position, GIcon * custom_icon, gboolean use_custom_icon, const char * tooltip)
Definition at line 635 of file drawer.c.
References FALSE, id, NULL, PANEL_GSETTINGS_OBJECTS, PANEL_OBJECT_DRAWER, panel_profile_add_to_list(), and panel_profile_prepare_object_with_id().
panel_drawer_set_dnd_enabled()
void panel_drawer_set_dnd_enabled (Drawer * drawer, gboolean dnd_enabled)
Definition at line 701 of file drawer.c.
References Drawer::button, BUTTON_WIDGET, button_widget_get_icon_name(), FALSE, and TRUE.