MATE Desktop Environment: drive-list.h File Reference
drive-list.h File Reference
#include <gtk/gtk.h>
Classes
struct _DriveList
struct _DriveListClass
Macros
#define DRIVE_TYPE_LIST (drive_list_get_type ())
#define DRIVE_LIST(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), DRIVE_TYPE_LIST, DriveList))
#define DRIVE_LIST_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), DRIVE_TYPE_LIST, DriveListClass))
#define DRIVE_IS_LIST(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), DRIVE_TYPE_LIST))
#define DRIVE_IS_LIST_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), DRIVE_TYPE_LIST))
#define DRIVE_LIST_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), DRIVE_TYPE_LIST, DriveListClass))
Typedefs
typedef struct _DriveList DriveList
typedef struct _DriveListClass DriveListClass
Functions
GType drive_list_get_type (void)
GtkWidget * drive_list_new (void)
void drive_list_set_orientation (DriveList *list, GtkOrientation orientation)
void drive_list_set_panel_size (DriveList *list, int panel_size)
void drive_list_set_transparent (DriveList *self, gboolean transparent)
void drive_list_redraw (DriveList *self)
void settings_color_changed (GSettings *settings, gchar *key, DriveList *drive_list)
Macro Definition Documentation
DRIVE_IS_LIST
#define DRIVE_IS_LIST (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), DRIVE_TYPE_LIST))
Definition at line 33 of file drive-list.h.
DRIVE_IS_LIST_CLASS
#define DRIVE_IS_LIST_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), DRIVE_TYPE_LIST))
Definition at line 34 of file drive-list.h.
DRIVE_LIST
#define DRIVE_LIST (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), DRIVE_TYPE_LIST, DriveList))
Definition at line 31 of file drive-list.h.
DRIVE_LIST_CLASS
#define DRIVE_LIST_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), DRIVE_TYPE_LIST, DriveListClass))
Definition at line 32 of file drive-list.h.
DRIVE_LIST_GET_CLASS
#define DRIVE_LIST_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), DRIVE_TYPE_LIST, DriveListClass))
Definition at line 35 of file drive-list.h.
DRIVE_TYPE_LIST
#define DRIVE_TYPE_LIST (drive_list_get_type ())
Definition at line 30 of file drive-list.h.
Typedef Documentation
DriveList
typedef struct _DriveList DriveList
Definition at line 37 of file drive-list.h.
DriveListClass
typedef struct _DriveListClass DriveListClass
Definition at line 38 of file drive-list.h.
Function Documentation
drive_list_get_type()
GType drive_list_get_type (void)
drive_list_new()
GtkWidget * drive_list_new (void)
Definition at line 131 of file drive-list.c.
References DRIVE_TYPE_LIST, and NULL.
drive_list_redraw()
void drive_list_redraw (DriveList * self)
Definition at line 481 of file drive-list.c.
References drive_button_redraw(), _DriveList::mounts, and _DriveList::volumes.
Referenced by settings_color_changed().
drive_list_set_orientation()
void drive_list_set_orientation (DriveList * list, GtkOrientation orientation)
Definition at line 445 of file drive-list.c.
References DRIVE_IS_LIST, and _DriveList::orientation.
drive_list_set_panel_size()
void drive_list_set_panel_size (DriveList * list, int panel_size)
Definition at line 468 of file drive-list.c.
References DRIVE_IS_LIST, _DriveList::icon_size, _DriveList::mounts, and _DriveList::volumes.
drive_list_set_transparent()
void drive_list_set_transparent (DriveList * self, gboolean transparent)
Definition at line 508 of file drive-list.c.
References _DriveList::mounts, _DriveList::relief, and _DriveList::volumes.
settings_color_changed()
void settings_color_changed (GSettings * settings, gchar * key, DriveList * drive_list)
Definition at line 488 of file drive-list.c.
References DRIVE_IS_LIST, and drive_list_redraw().