MATE Desktop Environment: drive-button.h File Reference
drive-button.h File Reference
#include <gtk/gtk.h>
Classes
struct _DriveButton
struct _DriveButtonClass
Macros
#define DRIVE_TYPE_BUTTON (drive_button_get_type ())
#define DRIVE_BUTTON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), DRIVE_TYPE_BUTTON, DriveButton))
#define DRIVE_BUTTON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), DRIVE_TYPE_BUTTON, DriveButtonClass))
#define DRIVE_IS_BUTTON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), DRIVE_TYPE_BUTTON))
#define DRIVE_IS_BUTTON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), DRIVE_TYPE_BUTTON))
#define DRIVE_BUTTON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), DRIVE_TYPE_BUTTON, DriveButtonClass))
Typedefs
typedef struct _DriveButton DriveButton
typedef struct _DriveButtonClass DriveButtonClass
Functions
GType drive_button_get_type (void)
GtkWidget * drive_button_new (GVolume *volume)
GtkWidget * drive_button_new_from_mount (GMount *mount)
void drive_button_queue_update (DriveButton *button)
void drive_button_set_size (DriveButton *button, int icon_size)
int drive_button_compare (DriveButton *button, DriveButton *other_button)
void drive_button_redraw (gpointer key, gpointer value, gpointer user_data)
Macro Definition Documentation
DRIVE_BUTTON
#define DRIVE_BUTTON (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), DRIVE_TYPE_BUTTON, DriveButton))
Definition at line 31 of file drive-button.h.
DRIVE_BUTTON_CLASS
#define DRIVE_BUTTON_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), DRIVE_TYPE_BUTTON, DriveButtonClass))
Definition at line 32 of file drive-button.h.
DRIVE_BUTTON_GET_CLASS
#define DRIVE_BUTTON_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), DRIVE_TYPE_BUTTON, DriveButtonClass))
Definition at line 35 of file drive-button.h.
DRIVE_IS_BUTTON
#define DRIVE_IS_BUTTON (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), DRIVE_TYPE_BUTTON))
Definition at line 33 of file drive-button.h.
DRIVE_IS_BUTTON_CLASS
#define DRIVE_IS_BUTTON_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), DRIVE_TYPE_BUTTON))
Definition at line 34 of file drive-button.h.
DRIVE_TYPE_BUTTON
#define DRIVE_TYPE_BUTTON (drive_button_get_type ())
Definition at line 30 of file drive-button.h.
Typedef Documentation
DriveButton
typedef struct _DriveButton DriveButton
Definition at line 37 of file drive-button.h.
DriveButtonClass
typedef struct _DriveButtonClass DriveButtonClass
Definition at line 38 of file drive-button.h.
Function Documentation
drive_button_compare()
int drive_button_compare (DriveButton * button, DriveButton * other_button)
Definition at line 452 of file drive-button.c.
References _DriveButton::mount, and _DriveButton::volume.
drive_button_get_type()
GType drive_button_get_type (void)
drive_button_new()
GtkWidget * drive_button_new (GVolume * volume)
Definition at line 111 of file drive-button.c.
References DRIVE_TYPE_BUTTON, and NULL.
drive_button_new_from_mount()
GtkWidget * drive_button_new_from_mount (GMount * mount)
Definition at line 128 of file drive-button.c.
References DRIVE_TYPE_BUTTON, and NULL.
drive_button_queue_update()
void drive_button_queue_update (DriveButton * button)
Definition at line 423 of file drive-button.c.
References _DriveButton::update_tag.
Referenced by drive_button_redraw(), and drive_button_set_size().
drive_button_redraw()
void drive_button_redraw (gpointer key, gpointer value, gpointer user_data)
Definition at line 443 of file drive-button.c.
References drive_button_queue_update().
Referenced by drive_list_redraw().
drive_button_set_size()
void drive_button_set_size (DriveButton * button, int icon_size)
Definition at line 431 of file drive-button.c.
References drive_button_queue_update(), DRIVE_IS_BUTTON, and _DriveButton::icon_size.