MATE Desktop Environment: dropbox-command-client.c File Reference
dropbox-command-client.c File Reference
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <errno.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdarg.h>
#include <string.h>
#include <glib.h>
#include "g-util.h"
#include "dropbox-client-util.h"
#include "dropbox-command-client.h"
#include "caja-dropbox.h"
#include "caja-dropbox-hooks.h"
Macros
#define WRITE_OR_DIE_SANI(s, l)
#define WRITE_OR_DIE(s, l)
#define SET_CONNECTED_STATE(s)
Functions
gboolean caja_dropbox_finish_file_info_command (DropboxFileInfoCommandResponse *)
gboolean dropbox_command_client_is_connected (DropboxCommandClient *dcc)
void dropbox_command_client_force_reconnect (DropboxCommandClient *dcc)
void dropbox_command_client_request (DropboxCommandClient *dcc, DropboxCommand *dc)
void dropbox_command_client_setup (DropboxCommandClient *dcc)
void dropbox_command_client_add_on_disconnect_hook (DropboxCommandClient *dcc, DropboxCommandClientConnectHook dhcch, gpointer ud)
void dropbox_command_client_add_on_connect_hook (DropboxCommandClient *dcc, DropboxCommandClientConnectHook dhcch, gpointer ud)
void dropbox_command_client_add_connection_attempt_hook (DropboxCommandClient *dcc, DropboxCommandClientConnectionAttemptHook dhcch, gpointer ud)
void dropbox_command_client_start (DropboxCommandClient *dcc)
void dropbox_command_client_send_simple_command (DropboxCommandClient *dcc, const char *command)
void dropbox_command_client_send_command (DropboxCommandClient *dcc, CajaDropboxCommandResponseHandler h, gpointer ud, const char *command,...)
Macro Definition Documentation
SET_CONNECTED_STATE
#define SET_CONNECTED_STATE (s)
Value:
      {         \
      g_mutex_lock(&(dcc->command_connected_mutex));    \
      dcc->command_connected = s;           \
      g_mutex_unlock(&(dcc->command_connected_mutex));  \
    }
WRITE_OR_DIE
#define WRITE_OR_DIE (s, l)
Value:
    {                       \
    iostat = g_io_channel_write_chars(chan, s,l, &bytes_trans,      \
                      &tmp_error);          \
    if (iostat == G_IO_STATUS_ERROR ||                  \
    iostat == G_IO_STATUS_AGAIN) {                  \
      if (tmp_error != NULL) {                      \
    g_propagate_error(err, tmp_error);              \
      }                                 \
      return NULL;                          \
    }                                   \
  }
WRITE_OR_DIE_SANI
#define WRITE_OR_DIE_SANI (s, l)
Value:
    {                   \
    gchar *sani_s;                          \
    sani_s = dropbox_client_util_sanitize(s);               \
    iostat = g_io_channel_write_chars(chan, sani_s,l, &bytes_trans, \
                      &tmp_error);          \
    g_free(sani_s);                         \
    if (iostat == G_IO_STATUS_ERROR ||                  \
    iostat == G_IO_STATUS_AGAIN) {                  \
      if (tmp_error != NULL) {                      \
    g_propagate_error(err, tmp_error);              \
      }                                 \
      return NULL;                          \
    }                                   \
  }
Function Documentation
caja_dropbox_finish_file_info_command()
gboolean caja_dropbox_finish_file_info_command (DropboxFileInfoCommandResponse * dficr)
Definition at line 333 of file caja-dropbox.c.
References caja_file_info_add_emblem(), caja_file_info_is_directory(), caja_info_provider_update_complete_invoke(), CAJA_OPERATION_COMPLETE, CAJA_OPERATION_FAILED, DropboxFileInfoCommand::cancelled, DropboxFileInfoCommandResponse::dfic, dropbox_use_operation_in_progress_workaround, DropboxFileInfoCommandResponse::emblems_response, FALSE, DropboxFileInfoCommand::file, DropboxFileInfoCommandResponse::file_status_response, DropboxFileInfoCommandResponse::folder_tag_response, NULL, DropboxFileInfoCommand::provider, TRUE, and DropboxFileInfoCommand::update_complete.
dropbox_command_client_add_connection_attempt_hook()
void dropbox_command_client_add_connection_attempt_hook (DropboxCommandClient * dcc, DropboxCommandClientConnectionAttemptHook dhcch, gpointer ud)
Definition at line 795 of file dropbox-command-client.c.
References DropboxCommandClient::ca_hooklist, and debug.
Referenced by dropbox_client_add_connection_attempt_hook().
dropbox_command_client_add_on_connect_hook()
void dropbox_command_client_add_on_connect_hook (DropboxCommandClient * dcc, DropboxCommandClientConnectHook dhcch, gpointer ud)
Definition at line 782 of file dropbox-command-client.c.
References DropboxCommandClient::onconnect_hooklist.
Referenced by dropbox_client_setup().
dropbox_command_client_add_on_disconnect_hook()
void dropbox_command_client_add_on_disconnect_hook (DropboxCommandClient * dcc, DropboxCommandClientConnectHook dhcch, gpointer ud)
Definition at line 769 of file dropbox-command-client.c.
References DropboxCommandClient::ondisconnect_hooklist.
Referenced by dropbox_client_setup().
dropbox_command_client_force_reconnect()
void dropbox_command_client_force_reconnect (DropboxCommandClient * dcc)
Definition at line 743 of file dropbox-command-client.c.
References debug, dropbox_command_client_is_connected(), dropbox_command_client_request(), and TRUE.
Referenced by dropbox_client_force_reconnect().
dropbox_command_client_is_connected()
gboolean dropbox_command_client_is_connected (DropboxCommandClient * dcc)
Definition at line 732 of file dropbox-command-client.c.
References DropboxCommandClient::command_connected, and DropboxCommandClient::command_connected_mutex.
Referenced by dropbox_client_is_connected(), and dropbox_command_client_force_reconnect().
dropbox_command_client_request()
void dropbox_command_client_request (DropboxCommandClient * dcc, DropboxCommand * dc)
Definition at line 752 of file dropbox-command-client.c.
References DropboxCommandClient::command_queue.
Referenced by dropbox_command_client_force_reconnect(), dropbox_command_client_send_command(), and dropbox_command_client_send_simple_command().
dropbox_command_client_send_command()
void dropbox_command_client_send_command (DropboxCommandClient * dcc, CajaDropboxCommandResponseHandler h, gpointer ud, const char * command, ...)
Definition at line 836 of file dropbox-command-client.c.
References command, DropboxGeneralCommand::command_args, DropboxGeneralCommand::command_name, DropboxGeneralCommand::dc, dropbox_command_client_request(), GENERAL_COMMAND, DropboxGeneralCommand::handler, DropboxGeneralCommand::handler_ud, NULL, and DropboxCommand::request_type.
dropbox_command_client_send_simple_command()
void dropbox_command_client_send_simple_command (DropboxCommandClient * dcc, const char * command)
Definition at line 818 of file dropbox-command-client.c.
References command, DropboxGeneralCommand::command_args, DropboxGeneralCommand::command_name, DropboxGeneralCommand::dc, dropbox_command_client_request(), GENERAL_COMMAND, DropboxGeneralCommand::handler, DropboxGeneralCommand::handler_ud, NULL, and DropboxCommand::request_type.
dropbox_command_client_setup()
void dropbox_command_client_setup (DropboxCommandClient * dcc)
Definition at line 758 of file dropbox-command-client.c.
References DropboxCommandClient::ca_hooklist, DropboxCommandClient::command_connected, DropboxCommandClient::command_connected_mutex, DropboxCommandClient::command_queue, FALSE, NULL, DropboxCommandClient::onconnect_hooklist, and DropboxCommandClient::ondisconnect_hooklist.
Referenced by dropbox_client_setup().
dropbox_command_client_start()
void dropbox_command_client_start (DropboxCommandClient * dcc)
Definition at line 811 of file dropbox-command-client.c.
References debug, and NULL.
Referenced by dropbox_client_start().