MATE Desktop Environment: dropbox-command-client.h File Reference
dropbox-command-client.h File Reference
#include <libcaja-extension/caja-info-provider.h>
#include <libcaja-extension/caja-file-info.h>
Classes
struct DropboxCommand
struct DropboxFileInfoCommand
struct DropboxFileInfoCommandResponse
struct DropboxGeneralCommand
struct DropboxCommandClient
Typedefs
typedef void(* CajaDropboxCommandResponseHandler) (GHashTable *, gpointer)
typedef void(* DropboxCommandClientConnectionAttemptHook) (guint, gpointer)
typedef GHookFunc DropboxCommandClientConnectHook
Enumerations
enum CajaDropboxRequestType { GET_FILE_INFO , GENERAL_COMMAND }
Functions
gboolean dropbox_command_client_is_connected (DropboxCommandClient *dcc)
void dropbox_command_client_force_reconnect (DropboxCommandClient *dcc)
void dropbox_command_client_request (DropboxCommandClient *dcc, DropboxCommand *dc)
void dropbox_command_client_setup (DropboxCommandClient *dcc)
void dropbox_command_client_start (DropboxCommandClient *dcc)
void dropbox_command_client_send_simple_command (DropboxCommandClient *dcc, const char *command)
void dropbox_command_client_send_command (DropboxCommandClient *dcc, CajaDropboxCommandResponseHandler h, gpointer ud, const char *command,...)
void dropbox_command_client_add_on_connect_hook (DropboxCommandClient *dcc, DropboxCommandClientConnectHook dhcch, gpointer ud)
void dropbox_command_client_add_on_disconnect_hook (DropboxCommandClient *dcc, DropboxCommandClientConnectHook dhcch, gpointer ud)
void dropbox_command_client_add_connection_attempt_hook (DropboxCommandClient *dcc, DropboxCommandClientConnectionAttemptHook dhcch, gpointer ud)
Typedef Documentation
CajaDropboxCommandResponseHandler
typedef void(* CajaDropboxCommandResponseHandler) (GHashTable *, gpointer)
Definition at line 54 of file dropbox-command-client.h.
DropboxCommandClientConnectHook
typedef GHookFunc DropboxCommandClientConnectHook
Definition at line 65 of file dropbox-command-client.h.
DropboxCommandClientConnectionAttemptHook
typedef void(* DropboxCommandClientConnectionAttemptHook) (guint, gpointer)
Definition at line 64 of file dropbox-command-client.h.
Enumeration Type Documentation
CajaDropboxRequestType
enum CajaDropboxRequestType
Enumerator
GET_FILE_INFO
GENERAL_COMMAND
Definition at line 33 of file dropbox-command-client.h.
Function Documentation
dropbox_command_client_add_connection_attempt_hook()
void dropbox_command_client_add_connection_attempt_hook (DropboxCommandClient * dcc, DropboxCommandClientConnectionAttemptHook dhcch, gpointer ud)
Definition at line 795 of file dropbox-command-client.c.
References DropboxCommandClient::ca_hooklist, and debug.
Referenced by dropbox_client_add_connection_attempt_hook().
dropbox_command_client_add_on_connect_hook()
void dropbox_command_client_add_on_connect_hook (DropboxCommandClient * dcc, DropboxCommandClientConnectHook dhcch, gpointer ud)
Definition at line 782 of file dropbox-command-client.c.
References DropboxCommandClient::onconnect_hooklist.
Referenced by dropbox_client_setup().
dropbox_command_client_add_on_disconnect_hook()
void dropbox_command_client_add_on_disconnect_hook (DropboxCommandClient * dcc, DropboxCommandClientConnectHook dhcch, gpointer ud)
Definition at line 769 of file dropbox-command-client.c.
References DropboxCommandClient::ondisconnect_hooklist.
Referenced by dropbox_client_setup().
dropbox_command_client_force_reconnect()
void dropbox_command_client_force_reconnect (DropboxCommandClient * dcc)
Definition at line 743 of file dropbox-command-client.c.
References debug, dropbox_command_client_is_connected(), dropbox_command_client_request(), and TRUE.
Referenced by dropbox_client_force_reconnect().
dropbox_command_client_is_connected()
gboolean dropbox_command_client_is_connected (DropboxCommandClient * dcc)
Definition at line 732 of file dropbox-command-client.c.
References DropboxCommandClient::command_connected, and DropboxCommandClient::command_connected_mutex.
Referenced by dropbox_client_is_connected(), and dropbox_command_client_force_reconnect().
dropbox_command_client_request()
void dropbox_command_client_request (DropboxCommandClient * dcc, DropboxCommand * dc)
Definition at line 752 of file dropbox-command-client.c.
References DropboxCommandClient::command_queue.
Referenced by dropbox_command_client_force_reconnect(), dropbox_command_client_send_command(), and dropbox_command_client_send_simple_command().
dropbox_command_client_send_command()
void dropbox_command_client_send_command (DropboxCommandClient * dcc, CajaDropboxCommandResponseHandler h, gpointer ud, const char * command, ...)
Definition at line 836 of file dropbox-command-client.c.
References command, DropboxGeneralCommand::command_args, DropboxGeneralCommand::command_name, DropboxGeneralCommand::dc, dropbox_command_client_request(), GENERAL_COMMAND, DropboxGeneralCommand::handler, DropboxGeneralCommand::handler_ud, NULL, and DropboxCommand::request_type.
dropbox_command_client_send_simple_command()
void dropbox_command_client_send_simple_command (DropboxCommandClient * dcc, const char * command)
Definition at line 818 of file dropbox-command-client.c.
References command, DropboxGeneralCommand::command_args, DropboxGeneralCommand::command_name, DropboxGeneralCommand::dc, dropbox_command_client_request(), GENERAL_COMMAND, DropboxGeneralCommand::handler, DropboxGeneralCommand::handler_ud, NULL, and DropboxCommand::request_type.
dropbox_command_client_setup()
void dropbox_command_client_setup (DropboxCommandClient * dcc)
Definition at line 758 of file dropbox-command-client.c.
References DropboxCommandClient::ca_hooklist, DropboxCommandClient::command_connected, DropboxCommandClient::command_connected_mutex, DropboxCommandClient::command_queue, FALSE, NULL, DropboxCommandClient::onconnect_hooklist, and DropboxCommandClient::ondisconnect_hooklist.
Referenced by dropbox_client_setup().
dropbox_command_client_start()
void dropbox_command_client_start (DropboxCommandClient * dcc)
Definition at line 811 of file dropbox-command-client.c.
References debug, and NULL.
Referenced by dropbox_client_start().