MATE Desktop Environment: drwright.c File Reference
drwright.c File Reference
#include <config.h>
#include <string.h>
#include <math.h>
#include <glib/gi18n.h>
#include <gdk/gdk.h>
#include <gdk/gdkx.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <libayatana-appindicator/app-indicator.h>
#include <libmate-desktop/mate-desktop-utils.h>
#include "drwright.h"
#include "drw-break-window.h"
#include "drw-monitor.h"
#include "drw-utils.h"
#include "drw-timer.h"
Macros
#define MATE_DESKTOP_USE_UNSTABLE_API
#define TYPING_MONITOR_ACTIVE_ICON "bar-green"
#define TYPING_MONITOR_ATTENTION_ICON "bar-red"
Enumerations
enum DrwState {
STATE_START , STATE_RUNNING , STATE_WARN , STATE_BREAK_SETUP ,
STATE_BREAK , STATE_BREAK_DONE_SETUP , STATE_BREAK_DONE
}
Functions
DrWright * drwright_new (void)
Variables
gboolean debug
Macro Definition Documentation
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 39 of file drwright.c.
TYPING_MONITOR_ACTIVE_ICON
#define TYPING_MONITOR_ACTIVE_ICON "bar-green"
Definition at line 58 of file drwright.c.
TYPING_MONITOR_ATTENTION_ICON
#define TYPING_MONITOR_ATTENTION_ICON "bar-red"
Definition at line 59 of file drwright.c.
Enumeration Type Documentation
DrwState
enum DrwState
Enumerator
STATE_START
STATE_RUNNING
STATE_WARN
STATE_BREAK_SETUP
STATE_BREAK
STATE_BREAK_DONE_SETUP
STATE_BREAK_DONE
Definition at line 48 of file drwright.c.
Function Documentation
drwright_new()
DrWright * drwright_new (void)
Definition at line 564 of file drwright.c.
References debug, drw_monitor_new(), drw_timer_new(), MIN, NULL, STATE_START, and TYPING_BREAK_SCHEMA.
Referenced by main().
Variable Documentation
debug
gboolean debug extern
Definition at line 37 of file mate-control-center/typing-break/main.c.
Referenced by drwright_new(), and main().