MATE Desktop Environment: edge-resistance.c File Reference
edge-resistance.c File Reference
#include <config.h>
#include "edge-resistance.h"
#include "boxes.h"
#include "display-private.h"
#include "workspace.h"
Macros
#define WINDOW_EDGES_RELEVANT(window, display)
Typedefs
typedef struct ResistanceDataForAnEdge ResistanceDataForAnEdge
Functions
void meta_display_cleanup_edges (MetaDisplay *display)
void meta_window_edge_resistance_for_move (MetaWindow *window, int old_x, int old_y, int *new_x, int *new_y, GSourceFunc timeout_func, gboolean snap, gboolean is_keyboard_op)
void meta_window_edge_resistance_for_resize (MetaWindow *window, int old_width, int old_height, int *new_width, int *new_height, int gravity, GSourceFunc timeout_func, gboolean snap, gboolean is_keyboard_op)
Macro Definition Documentation
WINDOW_EDGES_RELEVANT
#define WINDOW_EDGES_RELEVANT (window, display)
Value:
  meta_window_should_be_showing (window) &&    \
  window->screen == display->grab_screen &&    \
  window         != display->grab_window &&    \
  window->type   != META_WINDOW_DESKTOP &&     \
  window->type   != META_WINDOW_MENU    &&     \
  window->type   != META_WINDOW_SPLASHSCREEN
Definition at line 33 of file edge-resistance.c.
Typedef Documentation
ResistanceDataForAnEdge
typedef struct ResistanceDataForAnEdge ResistanceDataForAnEdge
Definition at line 51 of file edge-resistance.c.
Function Documentation
meta_display_cleanup_edges()
void meta_display_cleanup_edges (MetaDisplay * display)
Definition at line 672 of file edge-resistance.c.
References _MetaEdge::edge_type, _MetaDisplay::grab_edge_resistance_data, META_EDGE_WINDOW, META_SIDE_BOTTOM, META_SIDE_LEFT, META_SIDE_RIGHT, META_SIDE_TOP, NULL, _MetaEdge::side_type, and TRUE.
Referenced by meta_display_end_grab_op(), meta_workspace_activate_with_focus(), and meta_workspace_invalidate_work_area().
meta_window_edge_resistance_for_move()
void meta_window_edge_resistance_for_move (MetaWindow * window, int old_x, int old_y, int * new_x, int * new_y, GSourceFunc timeout_func, gboolean snap, gboolean is_keyboard_op)
Definition at line 1136 of file edge-resistance.c.
References BOX_BOTTOM, BOX_LEFT, BOX_RIGHT, BOX_TOP, _MetaWindow::display, FALSE, _MetaDisplay::grab_last_user_action_was_snap, _MetaDisplay::grab_window, _MetaDisplay::grab_wireframe_active, _MetaDisplay::grab_wireframe_rect, META_DEBUG_EDGE_RESISTANCE, meta_window_get_outer_rect(), meta_window_get_xor_rect(), _MetaRectangle::x, and _MetaRectangle::y.
meta_window_edge_resistance_for_resize()
void meta_window_edge_resistance_for_resize (MetaWindow * window, int old_width, int old_height, int * new_width, int * new_height, int gravity, GSourceFunc timeout_func, gboolean snap, gboolean is_keyboard_op)
Definition at line 1229 of file edge-resistance.c.
References _MetaWindow::display, FALSE, _MetaDisplay::grab_last_user_action_was_snap, _MetaDisplay::grab_window, _MetaDisplay::grab_wireframe_active, _MetaDisplay::grab_wireframe_rect, _MetaRectangle::height, META_DEBUG_EDGE_RESISTANCE, meta_rectangle_resize_with_gravity(), meta_window_get_outer_rect(), meta_window_get_xor_rect(), TRUE, and _MetaRectangle::width.