MATE Desktop Environment: eel-accessibility.c File Reference
eel-accessibility.c File Reference
#include <config.h>
#include <gtk/gtk.h>
#include <atk/atkrelationset.h>
#include "eel-accessibility.h"
Functions
void eel_accessibility_set_up_label_widget_relation (GtkWidget *label, GtkWidget *widget)
AtkObject * eel_accessibility_for_object (gpointer object)
gpointer eel_accessibility_get_gobject (AtkObject *object)
char * eel_accessibility_text_get_text (AtkText *text, gint start_pos, gint end_pos)
gunichar eel_accessibility_text_get_character_at_offset (AtkText *text, gint offset)
char * eel_accessibility_text_get_text_before_offset (AtkText *text, gint offset, AtkTextBoundary boundary_type, gint *start_offset, gint *end_offset)
char * eel_accessibility_text_get_text_at_offset (AtkText *text, gint offset, AtkTextBoundary boundary_type, gint *start_offset, gint *end_offset)
gchar * eel_accessibility_text_get_text_after_offset (AtkText *text, gint offset, AtkTextBoundary boundary_type, gint *start_offset, gint *end_offset)
gint eel_accessibility_text_get_character_count (AtkText *text)
GType eel_accessible_text_get_type (void)
void eel_accessibility_set_name (gpointer object, const char *name)
void eel_accessibility_set_description (gpointer object, const char *description)
Function Documentation
eel_accessibility_for_object()
AtkObject * eel_accessibility_for_object (gpointer object)
eel_accessibilty_for_object: @object: a GObject of some sort
gets an AtkObject associated with a GObject and if it doesn't exist creates a suitable accessible object.
Return value: an associated accessible.
Definition at line 70 of file eel-accessibility.c.
Referenced by eel_accessibility_set_description(), and eel_accessibility_set_name().
eel_accessibility_get_gobject()
gpointer eel_accessibility_get_gobject (AtkObject * object)
eel_accessibility_get_gobject: @object: an AtkObject
gets the GObject associated with the AtkObject, for which @object provides accessibility support.
Return value: the accessible's associated GObject
Definition at line 88 of file eel-accessibility.c.
eel_accessibility_set_description()
void eel_accessibility_set_description (gpointer object, const char * description)
Definition at line 253 of file eel-accessibility.c.
References eel_accessibility_for_object().
eel_accessibility_set_name()
void eel_accessibility_set_name (gpointer object, const char * name)
Definition at line 241 of file eel-accessibility.c.
References eel_accessibility_for_object(), and name.
eel_accessibility_set_up_label_widget_relation()
void eel_accessibility_set_up_label_widget_relation (GtkWidget * label, GtkWidget * widget)
Definition at line 32 of file eel-accessibility.c.
References label.
eel_accessibility_text_get_character_at_offset()
gunichar eel_accessibility_text_get_character_at_offset (AtkText * text, gint offset)
Definition at line 140 of file eel-accessibility.c.
References NULL.
eel_accessibility_text_get_character_count()
gint eel_accessibility_text_get_character_count (AtkText * text)
Definition at line 204 of file eel-accessibility.c.
References NULL.
eel_accessibility_text_get_text()
char * eel_accessibility_text_get_text (AtkText * text, gint start_pos, gint end_pos)
Definition at line 129 of file eel-accessibility.c.
References NULL.
eel_accessibility_text_get_text_after_offset()
gchar * eel_accessibility_text_get_text_after_offset (AtkText * text, gint offset, AtkTextBoundary boundary_type, gint * start_offset, gint * end_offset)
Definition at line 189 of file eel-accessibility.c.
References NULL.
eel_accessibility_text_get_text_at_offset()
char * eel_accessibility_text_get_text_at_offset (AtkText * text, gint offset, AtkTextBoundary boundary_type, gint * start_offset, gint * end_offset)
Definition at line 174 of file eel-accessibility.c.
References NULL.
eel_accessibility_text_get_text_before_offset()
char * eel_accessibility_text_get_text_before_offset (AtkText * text, gint offset, AtkTextBoundary boundary_type, gint * start_offset, gint * end_offset)
Definition at line 159 of file eel-accessibility.c.
References NULL.
eel_accessible_text_get_type()
GType eel_accessible_text_get_type (void)
Definition at line 213 of file eel-accessibility.c.
References NULL, and type.