MATE Desktop Environment: eel-image-table.h File Reference
eel-image-table.h File Reference
#include "eel-wrap-table.h"
Classes
struct EelImageTableEvent
struct EelImageTable
struct EelImageTableClass
Macros
#define EEL_TYPE_IMAGE_TABLE eel_image_table_get_type()
#define EEL_IMAGE_TABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EEL_TYPE_IMAGE_TABLE, EelImageTable))
#define EEL_IMAGE_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EEL_TYPE_IMAGE_TABLE, EelImageTableClass))
#define EEL_IS_IMAGE_TABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EEL_TYPE_IMAGE_TABLE))
#define EEL_IS_IMAGE_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EEL_TYPE_IMAGE_TABLE))
#define EEL_IMAGE_TABLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EEL_TYPE_IMAGE_TABLE, EelImageTableClass))
Typedefs
typedef struct EelImageTable EelImageTable
typedef struct EelImageTableClass EelImageTableClass
typedef struct EelImageTablePrivate EelImageTablePrivate
Functions
GType eel_image_table_get_type (void)
GtkWidget * eel_image_table_new (gboolean homogeneous)
GtkWidget * eel_image_table_add_empty_image (EelImageTable *image_table)
Macro Definition Documentation
EEL_IMAGE_TABLE
#define EEL_IMAGE_TABLE (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EEL_TYPE_IMAGE_TABLE, EelImageTable))
Definition at line 35 of file eel-image-table.h.
EEL_IMAGE_TABLE_CLASS
#define EEL_IMAGE_TABLE_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EEL_TYPE_IMAGE_TABLE, EelImageTableClass))
Definition at line 37 of file eel-image-table.h.
EEL_IMAGE_TABLE_GET_CLASS
#define EEL_IMAGE_TABLE_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EEL_TYPE_IMAGE_TABLE, EelImageTableClass))
Definition at line 43 of file eel-image-table.h.
EEL_IS_IMAGE_TABLE
#define EEL_IS_IMAGE_TABLE (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EEL_TYPE_IMAGE_TABLE))
Definition at line 39 of file eel-image-table.h.
EEL_IS_IMAGE_TABLE_CLASS
#define EEL_IS_IMAGE_TABLE_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EEL_TYPE_IMAGE_TABLE))
Definition at line 41 of file eel-image-table.h.
EEL_TYPE_IMAGE_TABLE
#define EEL_TYPE_IMAGE_TABLE eel_image_table_get_type()
Definition at line 34 of file eel-image-table.h.
Typedef Documentation
EelImageTable
typedef struct EelImageTable EelImageTable
Definition at line 46 of file eel-image-table.h.
EelImageTableClass
typedef struct EelImageTableClass EelImageTableClass
Definition at line 47 of file eel-image-table.h.
EelImageTablePrivate
typedef struct EelImageTablePrivate EelImageTablePrivate
Definition at line 48 of file eel-image-table.h.
Function Documentation
eel_image_table_add_empty_image()
GtkWidget * eel_image_table_add_empty_image (EelImageTable * image_table)
eel_image_table_add_empty_child: @image_table: A EelImageTable.
Add a "empty" child to the table. Useful when you want to have empty space between 2 children.
Returns: The empty child - A EelLabeledImage widget with no label or pixbuf.
Definition at line 646 of file eel-image-table.c.
References EEL_IS_IMAGE_TABLE, eel_labeled_image_new(), FALSE, and NULL.
eel_image_table_get_type()
GType eel_image_table_get_type (void)
Referenced by eel_image_table_new().
eel_image_table_new()
GtkWidget * eel_image_table_new (gboolean homogeneous)
eel_image_table_new:
Definition at line 624 of file eel-image-table.c.
References EEL_IMAGE_TABLE, eel_image_table_get_type(), EEL_WRAP_TABLE, eel_wrap_table_set_homogeneous(), and NULL.