MATE Desktop Environment: eel-art-gtk-extensions.h File Reference
eel-art-gtk-extensions.h File Reference
#include "eel-gtk-extensions.h"
#include "eel-art-extensions.h"
Functions
EelIRect eel_gtk_widget_get_bounds (GtkWidget *widget)
EelDimensions eel_gtk_widget_get_dimensions (GtkWidget *widget)
Function Documentation
eel_gtk_widget_get_bounds()
EelIRect eel_gtk_widget_get_bounds (GtkWidget * gtk_widget)
eel_gtk_widget_get_bounds: @gtk_widget: The source GtkWidget.
Return value: An EelIRect representation of the given GtkWidget's geometry relative to its parent. In the Gtk universe this is known as "allocation."
Definition at line 38 of file eel-art-gtk-extensions.c.
References eel_irect_assign(), and eel_irect_empty.
Referenced by eel_wrap_table_find_child_at_event_point().
eel_gtk_widget_get_dimensions()
EelDimensions eel_gtk_widget_get_dimensions (GtkWidget * gtk_widget)
eel_gtk_widget_get_dimensions: @gtk_widget: The source GtkWidget.
Return value: The widget's dimensions. The returned dimensions are only valid after the widget's geometry has been "allocated" by its container.
Definition at line 58 of file eel-art-gtk-extensions.c.
References eel_dimensions_empty, EelDimensions::height, int(), and EelDimensions::width.