MATE Desktop Environment: eel-canvas-rect-ellipse.h File Reference
eel-canvas-rect-ellipse.h File Reference
#include "eel-canvas.h"
Classes
struct _EelCanvasRE
struct _EelCanvasREClass
struct _EelCanvasRect
struct _EelCanvasRectClass
Macros
#define EEL_TYPE_CANVAS_RE (eel_canvas_re_get_type ())
#define EEL_CANVAS_RE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EEL_TYPE_CANVAS_RE, EelCanvasRE))
#define EEL_CANVAS_RE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EEL_TYPE_CANVAS_RE, EelCanvasREClass))
#define EEL_IS_CANVAS_RE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EEL_TYPE_CANVAS_RE))
#define EEL_IS_CANVAS_RE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EEL_TYPE_CANVAS_RE))
#define EEL_CANVAS_RE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EEL_TYPE_CANVAS_RE, EelCanvasREClass))
#define EEL_TYPE_CANVAS_RECT (eel_canvas_rect_get_type ())
#define EEL_CANVAS_RECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EEL_TYPE_CANVAS_RECT, EelCanvasRect))
#define EEL_CANVAS_RECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EEL_TYPE_CANVAS_RECT, EelCanvasRectClass))
#define EEL_IS_CANVAS_RECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EEL_TYPE_CANVAS_RECT))
#define EEL_IS_CANVAS_RECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EEL_TYPE_CANVAS_RECT))
#define EEL_CANVAS_RECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EEL_TYPE_CANVAS_RECT, EelCanvasRectClass))
Typedefs
typedef struct _EelCanvasRE EelCanvasRE
typedef struct _EelCanvasREClass EelCanvasREClass
typedef struct _EelCanvasRect EelCanvasRect
typedef struct _EelCanvasRectPrivate EelCanvasRectPrivate
typedef struct _EelCanvasRectClass EelCanvasRectClass
Functions
GType eel_canvas_re_get_type (void)
GType eel_canvas_rect_get_type (void)
Macro Definition Documentation
EEL_CANVAS_RE
#define EEL_CANVAS_RE (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EEL_TYPE_CANVAS_RE, EelCanvasRE))
Definition at line 67 of file eel-canvas-rect-ellipse.h.
EEL_CANVAS_RE_CLASS
#define EEL_CANVAS_RE_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EEL_TYPE_CANVAS_RE, EelCanvasREClass))
Definition at line 68 of file eel-canvas-rect-ellipse.h.
EEL_CANVAS_RE_GET_CLASS
#define EEL_CANVAS_RE_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EEL_TYPE_CANVAS_RE, EelCanvasREClass))
Definition at line 71 of file eel-canvas-rect-ellipse.h.
EEL_CANVAS_RECT
#define EEL_CANVAS_RECT (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EEL_TYPE_CANVAS_RECT, EelCanvasRect))
Definition at line 108 of file eel-canvas-rect-ellipse.h.
EEL_CANVAS_RECT_CLASS
#define EEL_CANVAS_RECT_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EEL_TYPE_CANVAS_RECT, EelCanvasRectClass))
Definition at line 109 of file eel-canvas-rect-ellipse.h.
EEL_CANVAS_RECT_GET_CLASS
#define EEL_CANVAS_RECT_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EEL_TYPE_CANVAS_RECT, EelCanvasRectClass))
Definition at line 112 of file eel-canvas-rect-ellipse.h.
EEL_IS_CANVAS_RE
#define EEL_IS_CANVAS_RE (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EEL_TYPE_CANVAS_RE))
Definition at line 69 of file eel-canvas-rect-ellipse.h.
EEL_IS_CANVAS_RE_CLASS
#define EEL_IS_CANVAS_RE_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EEL_TYPE_CANVAS_RE))
Definition at line 70 of file eel-canvas-rect-ellipse.h.
EEL_IS_CANVAS_RECT
#define EEL_IS_CANVAS_RECT (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EEL_TYPE_CANVAS_RECT))
Definition at line 110 of file eel-canvas-rect-ellipse.h.
EEL_IS_CANVAS_RECT_CLASS
#define EEL_IS_CANVAS_RECT_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EEL_TYPE_CANVAS_RECT))
Definition at line 111 of file eel-canvas-rect-ellipse.h.
EEL_TYPE_CANVAS_RE
#define EEL_TYPE_CANVAS_RE (eel_canvas_re_get_type ())
Definition at line 66 of file eel-canvas-rect-ellipse.h.
EEL_TYPE_CANVAS_RECT
#define EEL_TYPE_CANVAS_RECT (eel_canvas_rect_get_type ())
Definition at line 107 of file eel-canvas-rect-ellipse.h.
Typedef Documentation
EelCanvasRE
typedef struct _EelCanvasRE EelCanvasRE
Definition at line 73 of file eel-canvas-rect-ellipse.h.
EelCanvasREClass
typedef struct _EelCanvasREClass EelCanvasREClass
Definition at line 74 of file eel-canvas-rect-ellipse.h.
EelCanvasRect
typedef struct _EelCanvasRect EelCanvasRect
Definition at line 114 of file eel-canvas-rect-ellipse.h.
EelCanvasRectClass
typedef struct _EelCanvasRectClass EelCanvasRectClass
Definition at line 116 of file eel-canvas-rect-ellipse.h.
EelCanvasRectPrivate
typedef struct _EelCanvasRectPrivate EelCanvasRectPrivate
Definition at line 115 of file eel-canvas-rect-ellipse.h.
Function Documentation
eel_canvas_re_get_type()
GType eel_canvas_re_get_type (void)
Definition at line 88 of file eel-canvas-rect-ellipse.c.
References eel_canvas_item_get_type(), and NULL.
Referenced by eel_canvas_rect_get_type().
eel_canvas_rect_get_type()
GType eel_canvas_rect_get_type (void)
Definition at line 453 of file eel-canvas-rect-ellipse.c.
References eel_canvas_re_get_type(), and NULL.