MATE Desktop Environment: eel-debug.h File Reference
eel-debug.h File Reference
#include <glib.h>
Typedefs
typedef void(* EelFunction) (void)
Functions
void eel_stop_in_debugger (void)
void eel_make_warnings_and_criticals_stop_in_debugger (void)
void eel_debug_shut_down (void)
void eel_debug_call_at_shutdown (EelFunction function)
void eel_debug_call_at_shutdown_with_data (GFreeFunc function, gpointer data)
Typedef Documentation
EelFunction
typedef void(* EelFunction) (void)
Definition at line 34 of file eel-debug.h.
Function Documentation
eel_debug_call_at_shutdown()
void eel_debug_call_at_shutdown (EelFunction function)
Definition at line 93 of file eel-debug.c.
References eel_debug_call_at_shutdown_with_data(), and NULL.
Referenced by caja_add_bookmark_to_history_list(), caja_clipboard_monitor_get(), caja_desktop_link_monitor_get(), caja_module_setup(), caja_trash_monitor_get(), and eel_g_hash_table_new_free_at_exit().
eel_debug_call_at_shutdown_with_data()
void eel_debug_call_at_shutdown_with_data (GFreeFunc function, gpointer data)
Definition at line 99 of file eel-debug.c.
References data.
Referenced by caja_signaller_get_current(), caja_ui_string_get(), and eel_debug_call_at_shutdown().
eel_debug_shut_down()
void eel_debug_shut_down (void)
Definition at line 78 of file eel-debug.c.
References NULL.
Referenced by main().
eel_make_warnings_and_criticals_stop_in_debugger()
void eel_make_warnings_and_criticals_stop_in_debugger (void)
Definition at line 72 of file eel-debug.c.
References NULL.
Referenced by main(), and test_init().
eel_stop_in_debugger()
void eel_stop_in_debugger (void)
Definition at line 45 of file eel-debug.c.
References int().