MATE Desktop Environment: eel-gtk-container.c File Reference
eel-gtk-container.c File Reference
#include <config.h>
#include "eel-gtk-container.h"
#include "eel-art-extensions.h"
Functions
void eel_gtk_container_child_expose_event (GtkContainer *container, GtkWidget *child, cairo_t *cr)
void eel_gtk_container_child_map (GtkContainer *container, GtkWidget *child)
void eel_gtk_container_child_unmap (GtkContainer *container, GtkWidget *child)
void eel_gtk_container_child_add (GtkContainer *container, GtkWidget *child)
void eel_gtk_container_child_remove (GtkContainer *container, GtkWidget *child)
void eel_gtk_container_child_size_allocate (GtkContainer *container, GtkWidget *child, EelIRect child_geometry)
Function Documentation
eel_gtk_container_child_add()
void eel_gtk_container_child_add (GtkContainer * container, GtkWidget * child)
eel_gtk_container_child_add:
@container: A GtkContainer widget. @child: A non NULL unparented child.
Add a @child to a @container. The @child is realized, mapped and resized if needed. This is usually called from the "GtkContainer::add" method of the @container. The @child cannot be NULL.
Definition at line 127 of file eel-gtk-container.c.
eel_gtk_container_child_expose_event()
void eel_gtk_container_child_expose_event (GtkContainer * container, GtkWidget * child, cairo_t * cr)
eel_gtk_container_child_expose_event:
@container: A GtkContainer widget. @child: A child of @container or NULL; @event: The expose event.
Forward an expose event to a child if needed. It is valid to give a NULL @child. In that case this function is a noop. Proper clipping is done to ensure that the @child does indeed need to be forwarded the exposure event. Finally, the forwarding only occurs if the child is a NO_WINDOW widget. Of course, it is valid to feed non NO_WINDOW widgets to this function, in which case this function is a noop.
Definition at line 44 of file eel-gtk-container.c.
References NULL.
eel_gtk_container_child_map()
void eel_gtk_container_child_map (GtkContainer * container, GtkWidget * child)
eel_gtk_container_child_map:
@container: A GtkContainer widget. @child: A child of @container or NULL;
Map a child if needed. This is usually called from the "GtkWidget::map" method of the @container widget. If @child is NULL, then this function is a noop.
Definition at line 70 of file eel-gtk-container.c.
References NULL.
eel_gtk_container_child_remove()
void eel_gtk_container_child_remove (GtkContainer * container, GtkWidget * child)
eel_gtk_container_child_remove:
@container: A GtkContainer widget. @child: A non NULL child of @container.
Remove @child from @container. The @container is resized if needed. This is usually called from the "GtkContainer::remove" method of the @container. The child cannot be NULL.
Definition at line 167 of file eel-gtk-container.c.
eel_gtk_container_child_size_allocate()
void eel_gtk_container_child_size_allocate (GtkContainer * container, GtkWidget * child, EelIRect child_geometry)
eel_gtk_container_child_size_allocate:
@container: A GtkContainer widget. @child: A child of @container or NULL;
Invoke the "GtkWidget::size_allocate" method of @child. This function is usually called from the "GtkWidget::size_allocate" method of @container. The child can be NULL, in which case this function is a noop.
Definition at line 198 of file eel-gtk-container.c.
References eel_irect_get_height(), eel_irect_get_width(), eel_irect_is_empty(), NULL, EelIRect::x0, and EelIRect::y0.
eel_gtk_container_child_unmap()
void eel_gtk_container_child_unmap (GtkContainer * container, GtkWidget * child)
eel_gtk_container_child_unmap:
@container: A GtkContainer widget. @child: A child of @container or NULL;
Unmap a child if needed. This is usually called from the "GtkWidget::unmap" method of the @container widget. If @child is NULL, then this function is a noop.
Definition at line 98 of file eel-gtk-container.c.
References NULL.