MATE Desktop Environment: eel-mate-extensions.h File Reference
eel-mate-extensions.h File Reference
#include <gtk/gtk.h>
Functions
char * eel_mate_make_terminal_command (const char *command)
void eel_mate_open_terminal_on_screen (const char *command, GdkScreen *screen)
Function Documentation
eel_mate_make_terminal_command()
char * eel_mate_make_terminal_command (const char * command)
Definition at line 166 of file eel-mate-extensions.c.
References command, FALSE, NULL, prefix, and TRUE.
Referenced by eel_mate_open_terminal_on_screen().
eel_mate_open_terminal_on_screen()
void eel_mate_open_terminal_on_screen (const char * command, GdkScreen * screen)
Definition at line 183 of file eel-mate-extensions.c.
References command, eel_mate_make_terminal_command(), mate_gdk_spawn_command_line_on_screen(), and NULL.
Referenced by caja_launch_application_from_command(), and caja_launch_application_from_command_array().