MATE Desktop Environment: eel-gtk-extensions.c File Reference
eel-gtk-extensions.c File Reference
#include <config.h>
#include "eel-gtk-extensions.h"
#include "eel-gdk-pixbuf-extensions.h"
#include "eel-glib-extensions.h"
#include "eel-mate-extensions.h"
#include "eel-marshal.h"
#include "eel-string.h"
#include <X11/Xlib.h>
#include <X11/Xatom.h>
#include <gdk/gdk.h>
#include <gdk/gdkprivate.h>
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <math.h>
Macros
#define MINIMUM_ON_SCREEN_WIDTH 100
#define MINIMUM_ON_SCREEN_HEIGHT 100
Functions
char * eel_gtk_window_get_geometry_string (GtkWindow *window)
void eel_gtk_window_set_initial_geometry (GtkWindow *window, EelGdkGeometryFlags geometry_flags, int left, int top, guint width, guint height)
void eel_gtk_window_set_initial_geometry_from_string (GtkWindow *window, const char *geometry_string, guint minimum_width, guint minimum_height, gboolean ignore_position)
void eel_pop_up_context_menu (GtkMenu *menu, GdkEventButton *event)
GtkMenuItem * eel_gtk_menu_append_separator (GtkMenu *menu)
GtkMenuItem * eel_gtk_menu_insert_separator (GtkMenu *menu, int index)
GtkWidget * eel_gtk_menu_tool_button_get_button (GtkMenuToolButton *tool_button)
void eel_gtk_label_make_bold (GtkLabel *label)
void eel_gtk_tree_view_set_activate_on_single_click (GtkTreeView *tree_view, gboolean should_activate)
void eel_gtk_message_dialog_set_details_label (GtkMessageDialog *dialog, const gchar *details_text)
GtkWidget * eel_image_menu_item_new_from_icon (const gchar *icon_name, const gchar *label_name)
GtkWidget * eel_image_menu_item_new_from_surface (cairo_surface_t *icon_surface, const gchar *label_name)
gboolean eel_notebook_scroll_event_cb (GtkWidget *widget, GdkEventScroll *event)
Macro Definition Documentation
MINIMUM_ON_SCREEN_HEIGHT
#define MINIMUM_ON_SCREEN_HEIGHT 100
Definition at line 51 of file eel-gtk-extensions.c.
MINIMUM_ON_SCREEN_WIDTH
#define MINIMUM_ON_SCREEN_WIDTH 100
Definition at line 50 of file eel-gtk-extensions.c.
Function Documentation
eel_gtk_label_make_bold()
static void eel_gtk_label_make_bold (GtkLabel * label)
eel_gtk_label_make_bold.
Switches the font of label to a bold equivalent. @label: The label.
Definition at line 337 of file eel-gtk-extensions.c.
References label.
eel_gtk_menu_append_separator()
GtkMenuItem * eel_gtk_menu_append_separator (GtkMenu * menu)
Definition at line 293 of file eel-gtk-extensions.c.
References eel_gtk_menu_insert_separator().
Referenced by caja_drag_drop_action_ask(), and caja_drag_drop_background_ask().
eel_gtk_menu_insert_separator()
GtkMenuItem * eel_gtk_menu_insert_separator (GtkMenu * menu, int index)
Definition at line 299 of file eel-gtk-extensions.c.
Referenced by eel_gtk_menu_append_separator().
eel_gtk_menu_tool_button_get_button()
GtkWidget * eel_gtk_menu_tool_button_get_button (GtkMenuToolButton * tool_button)
Definition at line 311 of file eel-gtk-extensions.c.
References NULL.
eel_gtk_message_dialog_set_details_label()
void eel_gtk_message_dialog_set_details_label (GtkMessageDialog * dialog, const gchar * details_text)
Definition at line 417 of file eel-gtk-extensions.c.
References _, FALSE, label, and TRUE.
eel_gtk_tree_view_set_activate_on_single_click()
void eel_gtk_tree_view_set_activate_on_single_click (GtkTreeView * tree_view, gboolean should_activate)
Definition at line 387 of file eel-gtk-extensions.c.
References NULL.
eel_gtk_window_get_geometry_string()
char * eel_gtk_window_get_geometry_string (GtkWindow * window)
eel_gtk_window_get_geometry_string: @window: a #GtkWindow
Obtains the geometry string for this window, suitable for set_geometry_string(); assumes the window has NorthWest gravity
Return value: geometry string, must be freed
Definition at line 63 of file eel-gtk-extensions.c.
References NULL.
Referenced by caja_bookmarks_window_save_geometry().
eel_gtk_window_set_initial_geometry()
void eel_gtk_window_set_initial_geometry (GtkWindow * window, EelGdkGeometryFlags geometry_flags, int left, int top, guint width, guint height)
eel_gtk_window_set_initial_geometry:
Sets the position and size of a GtkWindow before the GtkWindow is shown. It is an error to call this on a window that is already on-screen. Takes into account screen size, and does some sanity-checking on the passed-in values.
@window: A non-visible GtkWindow @geometry_flags: A EelGdkGeometryFlags value defining which of the following parameters have defined values @left: pixel coordinate for left of window @top: pixel coordinate for top of window @width: width of window in pixels @height: height of window in pixels
Definition at line 151 of file eel-gtk-extensions.c.
References EEL_GDK_HEIGHT_VALUE, EEL_GDK_WIDTH_VALUE, EEL_GDK_X_NEGATIVE, EEL_GDK_X_VALUE, EEL_GDK_Y_NEGATIVE, and EEL_GDK_Y_VALUE.
Referenced by eel_gtk_window_set_initial_geometry_from_string().
eel_gtk_window_set_initial_geometry_from_string()
void eel_gtk_window_set_initial_geometry_from_string (GtkWindow * window, const char * geometry_string, guint minimum_width, guint minimum_height, gboolean ignore_position)
eel_gtk_window_set_initial_geometry_from_string:
Sets the position and size of a GtkWindow before the GtkWindow is shown. The geometry is passed in as a string. It is an error to call this on a window that is already on-screen. Takes into account screen size, and does some sanity-checking on the passed-in values.
@window: A non-visible GtkWindow @geometry_string: A string suitable for use with eel_gdk_parse_geometry @minimum_width: If the width from the string is smaller than this, use this for the width. @minimum_height: If the height from the string is smaller than this, use this for the height. @ignore_position: If true position data from string will be ignored.
Definition at line 223 of file eel-gtk-extensions.c.
References EEL_GDK_HEIGHT_VALUE, eel_gdk_parse_geometry(), EEL_GDK_WIDTH_VALUE, EEL_GDK_X_VALUE, EEL_GDK_Y_VALUE, eel_gtk_window_set_initial_geometry(), MAX, and NULL.
Referenced by caja_application_create_navigation_window().
eel_image_menu_item_new_from_icon()
GtkWidget * eel_image_menu_item_new_from_icon (const gchar * icon_name, const gchar * label_name)
Definition at line 439 of file eel-gtk-extensions.c.
References NULL.
Referenced by caja_side_pane_add_panel().
eel_image_menu_item_new_from_surface()
GtkWidget * eel_image_menu_item_new_from_surface (cairo_surface_t * icon_surface, const gchar * label_name)
Definition at line 473 of file eel-gtk-extensions.c.
References NULL.
eel_notebook_scroll_event_cb()
gboolean eel_notebook_scroll_event_cb (GtkWidget * widget, GdkEventScroll * event)
Definition at line 501 of file eel-gtk-extensions.c.
References FALSE, NULL, and TRUE.
eel_pop_up_context_menu()
void eel_pop_up_context_menu (GtkMenu * menu, GdkEventButton * event)
eel_pop_up_context_menu:
Pop up a context menu under the mouse. The menu is sunk after use, so it will be destroyed unless the caller first ref'ed it.
This function is more of a helper function than a gtk extension, so perhaps it belongs in a different file.
@menu: The menu to pop up under the mouse. @offset_x: Number of pixels to displace the popup menu vertically @offset_y: Number of pixels to displace the popup menu horizontally @event: The event that invoked this popup menu.
Definition at line 281 of file eel-gtk-extensions.c.
Referenced by fm_directory_view_pop_up_background_context_menu(), and fm_directory_view_pop_up_selection_context_menu().