MATE Desktop Environment: egg-sm-client.h File Reference
egg-sm-client.h File Reference
#include <glib-object.h>
Classes
struct _EggSMClient
struct _EggSMClientClass
Macros
#define EGG_TYPE_SM_CLIENT (egg_sm_client_get_type ())
#define EGG_SM_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EGG_TYPE_SM_CLIENT, EggSMClient))
#define EGG_SM_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EGG_TYPE_SM_CLIENT, EggSMClientClass))
#define EGG_IS_SM_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EGG_TYPE_SM_CLIENT))
#define EGG_IS_SM_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EGG_TYPE_SM_CLIENT))
#define EGG_SM_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EGG_TYPE_SM_CLIENT, EggSMClientClass))
Typedefs
typedef struct _EggSMClient EggSMClient
typedef struct _EggSMClientClass EggSMClientClass
typedef struct _EggSMClientPrivate EggSMClientPrivate
Enumerations
enum EggSMClientEndStyle { EGG_SM_CLIENT_END_SESSION_DEFAULT , EGG_SM_CLIENT_LOGOUT , EGG_SM_CLIENT_REBOOT , EGG_SM_CLIENT_SHUTDOWN }
enum EggSMClientMode { EGG_SM_CLIENT_MODE_DISABLED , EGG_SM_CLIENT_MODE_NO_RESTART , EGG_SM_CLIENT_MODE_NORMAL }
Functions
GType egg_sm_client_get_type (void)
GOptionGroup * egg_sm_client_get_option_group (void)
void egg_sm_client_set_mode (EggSMClientMode mode)
EggSMClientMode egg_sm_client_get_mode (void)
EggSMClient * egg_sm_client_get (void)
void egg_sm_client_startup (void)
gboolean egg_sm_client_is_resumed (EggSMClient *client)
GKeyFile * egg_sm_client_get_state_file (EggSMClient *client)
void egg_sm_client_set_restart_command (EggSMClient *client, int argc, const char **argv)
void egg_sm_client_will_quit (EggSMClient *client, gboolean will_quit)
gboolean egg_sm_client_end_session (EggSMClientEndStyle style, gboolean request_confirmation)
Macro Definition Documentation
EGG_IS_SM_CLIENT
#define EGG_IS_SM_CLIENT (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EGG_TYPE_SM_CLIENT))
Definition at line 30 of file egg-sm-client.h.
EGG_IS_SM_CLIENT_CLASS
#define EGG_IS_SM_CLIENT_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EGG_TYPE_SM_CLIENT))
Definition at line 31 of file egg-sm-client.h.
EGG_SM_CLIENT
#define EGG_SM_CLIENT (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EGG_TYPE_SM_CLIENT, EggSMClient))
Definition at line 28 of file egg-sm-client.h.
EGG_SM_CLIENT_CLASS
#define EGG_SM_CLIENT_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EGG_TYPE_SM_CLIENT, EggSMClientClass))
Definition at line 29 of file egg-sm-client.h.
EGG_SM_CLIENT_GET_CLASS
#define EGG_SM_CLIENT_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EGG_TYPE_SM_CLIENT, EggSMClientClass))
Definition at line 32 of file egg-sm-client.h.
EGG_TYPE_SM_CLIENT
#define EGG_TYPE_SM_CLIENT (egg_sm_client_get_type ())
Definition at line 27 of file egg-sm-client.h.
Typedef Documentation
EggSMClient
typedef struct _EggSMClient EggSMClient
Definition at line 34 of file egg-sm-client.h.
EggSMClientClass
typedef struct _EggSMClientClass EggSMClientClass
Definition at line 35 of file egg-sm-client.h.
EggSMClientPrivate
typedef struct _EggSMClientPrivate EggSMClientPrivate
Definition at line 36 of file egg-sm-client.h.
Enumeration Type Documentation
EggSMClientEndStyle
enum EggSMClientEndStyle
Enumerator
EGG_SM_CLIENT_END_SESSION_DEFAULT
EGG_SM_CLIENT_LOGOUT
EGG_SM_CLIENT_REBOOT
EGG_SM_CLIENT_SHUTDOWN
Definition at line 38 of file egg-sm-client.h.
EggSMClientMode
enum EggSMClientMode
Enumerator
EGG_SM_CLIENT_MODE_DISABLED
EGG_SM_CLIENT_MODE_NO_RESTART
EGG_SM_CLIENT_MODE_NORMAL
Definition at line 45 of file egg-sm-client.h.
Function Documentation
egg_sm_client_end_session()
gboolean egg_sm_client_end_session (EggSMClientEndStyle style, gboolean request_confirmation)
egg_sm_client_end_session: @style: a hint at how to end the session @request_confirmation: whether or not the user should get a chance to confirm the action
Requests that the session manager end the current session. @style indicates how the session should be ended, and @request_confirmation indicates whether or not the user should be given a chance to confirm the logout/reboot/shutdown. Both of these flags are merely hints though; the session manager may choose to ignore them.
Return value: TRUE if the request was sent; FALSE if it could not be (eg, because it could not connect to the session manager).
Definition at line 508 of file egg-sm-client.c.
References EGG_IS_SM_CLIENT, egg_sm_client_get(), EGG_SM_CLIENT_GET_CLASS, and FALSE.
egg_sm_client_get()
EggSMClient * egg_sm_client_get (void)
egg_sm_client_get:
Returns the master EggSMClient for the application.
On platforms that support saved sessions (ie, POSIX/X11), the application will only request to be restarted by the session manager if you call egg_set_desktop_file() to set an application desktop file. In particular, if the desktop file contains the key "X
Return value: the master EggSMClient.
Definition at line 327 of file egg-sm-client.c.
References EGG_SM_CLIENT_MODE_DISABLED, egg_sm_client_xsmp_new(), EGG_TYPE_SM_CLIENT, and NULL.
Referenced by base_isession_init(), egg_sm_client_end_session(), egg_sm_client_startup(), main(), main(), panel_session_init(), pluma_session_init(), and terminal_app_handle_options().
egg_sm_client_get_mode()
EggSMClientMode egg_sm_client_get_mode (void)
egg_sm_client_get_mode:
Gets the global EggSMClientMode. See egg_sm_client_set_mode() for details.
Return value: the global EggSMClientMode
Definition at line 308 of file egg-sm-client.c.
Referenced by panel_session_do_not_restart().
egg_sm_client_get_option_group()
GOptionGroup * egg_sm_client_get_option_group (void)
egg_sm_client_get_option_group:
Creates a GOptionGroup containing the session-management-related options. You should add this group to the application's GOptionContext if you want to use EggSMClient.
Return value: the GOptionGroup
Definition at line 230 of file egg-sm-client.c.
References _, entries, N_, and NULL.
Referenced by main(), and main().
egg_sm_client_get_state_file()
GKeyFile * egg_sm_client_get_state_file (EggSMClient * client)
egg_sm_client_get_state_file: @client: the client
If the application was resumed by the session manager, this will return the #GKeyFile containing its state from the previous session.
Note that other libraries and EggSMClient itself may also store state in the key file, so if you call egg_sm_client_get_groups(), on it, the return value will likely include groups that you did not put there yourself. (It is also not guaranteed that the first group created by the application will still be the "start group" when it is resumed.)
Return value: the #GKeyFile containing the application's earlier state, or NULL on error. You should not free this key file; it is owned by @client.
Definition at line 405 of file egg-sm-client.c.
References NULL.
Referenced by ev_application_load_session(), pluma_session_load(), and terminal_app_handle_options().
egg_sm_client_get_type()
GType egg_sm_client_get_type (void)
egg_sm_client_is_resumed()
gboolean egg_sm_client_is_resumed (EggSMClient * client)
egg_sm_client_is_resumed: @client: the client
Checks whether or not the current session has been resumed from a previous saved session. If so, the application should call egg_sm_client_get_state_file() and restore its state from the returned #GKeyFile.
Return value: TRUE if the session has been resumed
Definition at line 378 of file egg-sm-client.c.
References FALSE, and NULL.
Referenced by ev_application_load_session(), pluma_session_is_restored(), and terminal_app_handle_options().
egg_sm_client_set_mode()
void egg_sm_client_set_mode (EggSMClientMode mode)
egg_sm_client_set_mode: @mode: an EggSMClient mode
Sets the "mode" of EggSMClient as follows:
EGG_SM_CLIENT_MODE_DISABLED: Session management is completely disabled. The application will not even connect to the session manager. (egg_sm_client_get() will still return an EggSMClient, but it will just be a dummy object.)
EGG_SM_CLIENT_MODE_NO_RESTART: The application will connect to the session manager (and thus will receive notification when the user is logging out, etc), but will request to not be automatically restarted with saved state in future sessions.
EGG_SM_CLIENT_MODE_NORMAL: The default. #EggSMCLient will function normally.
This must be called before the application's main loop begins.
Definition at line 294 of file egg-sm-client.c.
Referenced by base_isession_init(), main(), panel_session_do_not_restart(), and panel_session_init().
egg_sm_client_set_restart_command()
void egg_sm_client_set_restart_command (EggSMClient * client, int argc, const char ** argv)
egg_sm_client_set_restart_command: @client: the client @argc: the length of @argv @argv: argument vector
Sets the command used to restart @client if it does not have a .desktop file that can be used to find its restart command.
This can also be used when handling the save_state signal, to save the current state via an updated command line. (Eg, providing a list of filenames to open when the application is resumed.)
Definition at line 451 of file egg-sm-client.c.
References EGG_IS_SM_CLIENT, and EGG_SM_CLIENT_GET_CLASS.
Referenced by save_session_cb().
egg_sm_client_startup()
void egg_sm_client_startup (void)
Definition at line 193 of file egg-sm-client.c.
References egg_sm_client_get(), EGG_SM_CLIENT_GET_CLASS, NULL, and TRUE.
Referenced by base_isession_init().
egg_sm_client_will_quit()
void egg_sm_client_will_quit (EggSMClient * client, gboolean will_quit)
egg_sm_client_will_quit: @client: the client @will_quit: whether or not the application is willing to quit
This MUST be called in response to the ::quit_requested signal, to indicate whether or not the application is willing to quit. The application may call it either directly from the signal handler, or at some later point (eg, after asynchronously interacting with the user).
If the application does not connect to ::quit_requested, EggSMClient will call this method on its behalf (passing TRUE for @will_quit).
After calling this method, the application should wait to receive either ::quit_cancelled or quit.
Definition at line 480 of file egg-sm-client.c.
References EGG_IS_SM_CLIENT, and EGG_SM_CLIENT_GET_CLASS.
Referenced by egg_sm_client_quit_requested().