MATE Desktop Environment: egg-idletime.h File Reference
egg-idletime.h File Reference
#include <glib-object.h>
Classes
struct EggIdletime
struct EggIdletimeClass
Macros
#define EGG_IDLETIME_TYPE (egg_idletime_get_type ())
#define EGG_IDLETIME(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), EGG_IDLETIME_TYPE, EggIdletime))
#define EGG_IDLETIME_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), EGG_IDLETIME_TYPE, EggIdletimeClass))
#define EGG_IS_IDLETIME(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), EGG_IDLETIME_TYPE))
#define EGG_IS_IDLETIME_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), EGG_IDLETIME_TYPE))
#define EGG_IDLETIME_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), EGG_IDLETIME_TYPE, EggIdletimeClass))
Typedefs
typedef struct EggIdletimePrivate EggIdletimePrivate
Functions
GType egg_idletime_get_type (void)
EggIdletime * egg_idletime_new (void)
void egg_idletime_alarm_reset_all (EggIdletime *idletime)
gboolean egg_idletime_alarm_set (EggIdletime *idletime, guint alarm_id, guint timeout)
gboolean egg_idletime_alarm_remove (EggIdletime *idletime, guint alarm_id)
gint64 egg_idletime_get_time (EggIdletime *idletime)
Macro Definition Documentation
EGG_IDLETIME
#define EGG_IDLETIME (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), EGG_IDLETIME_TYPE, EggIdletime))
Definition at line 31 of file egg-idletime.h.
EGG_IDLETIME_CLASS
#define EGG_IDLETIME_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), EGG_IDLETIME_TYPE, EggIdletimeClass))
Definition at line 32 of file egg-idletime.h.
EGG_IDLETIME_GET_CLASS
#define EGG_IDLETIME_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), EGG_IDLETIME_TYPE, EggIdletimeClass))
Definition at line 35 of file egg-idletime.h.
EGG_IDLETIME_TYPE
#define EGG_IDLETIME_TYPE (egg_idletime_get_type ())
Definition at line 30 of file egg-idletime.h.
EGG_IS_IDLETIME
#define EGG_IS_IDLETIME (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), EGG_IDLETIME_TYPE))
Definition at line 33 of file egg-idletime.h.
EGG_IS_IDLETIME_CLASS
#define EGG_IS_IDLETIME_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), EGG_IDLETIME_TYPE))
Definition at line 34 of file egg-idletime.h.
Typedef Documentation
EggIdletimePrivate
typedef struct EggIdletimePrivate EggIdletimePrivate
Definition at line 37 of file egg-idletime.h.
Function Documentation
egg_idletime_alarm_remove()
gboolean egg_idletime_alarm_remove (EggIdletime * idletime, guint id)
egg_idletime_alarm_free:
Definition at line 343 of file egg-idletime.c.
References EGG_IS_IDLETIME, FALSE, NULL, and TRUE.
Referenced by gpm_idle_set_timeout_dim().
egg_idletime_alarm_reset_all()
void egg_idletime_alarm_reset_all (EggIdletime * idletime)
egg_idletime_alarm_reset_all:
Definition at line 141 of file egg-idletime.c.
References EGG_IDLETIME_ALARM_TYPE_DISABLED, EGG_IDLETIME_ALARM_TYPE_POSITIVE, EGG_IS_IDLETIME, FALSE, EggIdletime::priv, and SIGNAL_RESET.
egg_idletime_alarm_set()
gboolean egg_idletime_alarm_set (EggIdletime * idletime, guint id, guint timeout)
egg_idletime_alarm_set:
Definition at line 296 of file egg-idletime.c.
References EGG_IDLETIME_ALARM_TYPE_POSITIVE, EGG_IS_IDLETIME, FALSE, NULL, EggIdletime::priv, and TRUE.
Referenced by gpm_idle_set_timeout_dim().
egg_idletime_get_time()
gint64 egg_idletime_get_time (EggIdletime * idletime)
egg_idletime_get_time:
Definition at line 88 of file egg-idletime.c.
References EggIdletime::priv.
Referenced by gpm_idle_set_timeout_dim().
egg_idletime_get_type()
GType egg_idletime_get_type (void)
egg_idletime_new()
EggIdletime * egg_idletime_new (void)
egg_idletime_new:
Definition at line 460 of file egg-idletime.c.
References EGG_IDLETIME, EGG_IDLETIME_TYPE, and NULL.