MATE Desktop Environment: eom-uri-converter.h File Reference
eom-uri-converter.h File Reference
#include <glib-object.h>
#include <glib/gi18n.h>
#include "eom-image.h"
Classes
struct EomUCInfo
struct _EomURIConverter
struct _EomURIConverterClass
Macros
#define EOM_TYPE_URI_CONVERTER (eom_uri_converter_get_type ())
#define EOM_URI_CONVERTER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), EOM_TYPE_URI_CONVERTER, EomURIConverter))
#define EOM_URI_CONVERTER_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), EOM_TYPE_URI_CONVERTER, EomURIConverterClass))
#define EOM_IS_URI_CONVERTER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), EOM_TYPE_URI_CONVERTER))
#define EOM_IS_URI_CONVERTER_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), EOM_TYPE_URI_CONVERTER))
#define EOM_URI_CONVERTER_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), EOM_TYPE_URI_CONVERTER, EomURIConverterClass))
#define EOM_UC_ERROR eom_uc_error_quark ()
Typedefs
typedef struct _EomURIConverterClass EomURIConverterClass
typedef struct _EomURIConverterPrivate EomURIConverterPrivate
Enumerations
enum EomUCType {
EOM_UC_STRING , EOM_UC_FILENAME , EOM_UC_COUNTER , EOM_UC_COMMENT ,
EOM_UC_DATE , EOM_UC_TIME , EOM_UC_DAY , EOM_UC_MONTH ,
EOM_UC_YEAR , EOM_UC_HOUR , EOM_UC_MINUTE , EOM_UC_SECOND ,
EOM_UC_END
}
enum EomUCError { EOM_UC_ERROR_INVALID_UNICODE , EOM_UC_ERROR_INVALID_CHARACTER , EOM_UC_ERROR_EQUAL_FILENAMES , EOM_UC_ERROR_UNKNOWN }
Functions
G_GNUC_INTERNAL GType eom_uri_converter_get_type (void)
G_GNUC_INTERNAL GQuark eom_uc_error_quark (void)
G_GNUC_INTERNAL EomURIConverter * eom_uri_converter_new (GFile *base_file, GdkPixbufFormat *img_format, const char *format_string)
G_GNUC_INTERNAL gboolean eom_uri_converter_check (EomURIConverter *converter, GList *img_list, GError **error)
G_GNUC_INTERNAL gboolean eom_uri_converter_requires_exif (EomURIConverter *converter)
G_GNUC_INTERNAL gboolean eom_uri_converter_do (EomURIConverter *converter, EomImage *image, GFile **file, GdkPixbufFormat **format, GError **error)
G_GNUC_INTERNAL char * eom_uri_converter_preview (const char *format_str, EomImage *img, GdkPixbufFormat *format, gulong counter, guint n_images, gboolean convert_spaces, gunichar space_char)
G_GNUC_INTERNAL void eom_uri_converter_print_list (EomURIConverter *conv)
Macro Definition Documentation
EOM_IS_URI_CONVERTER
#define EOM_IS_URI_CONVERTER (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), EOM_TYPE_URI_CONVERTER))
Definition at line 13 of file eom-uri-converter.h.
EOM_IS_URI_CONVERTER_CLASS
#define EOM_IS_URI_CONVERTER_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), EOM_TYPE_URI_CONVERTER))
Definition at line 14 of file eom-uri-converter.h.
EOM_TYPE_URI_CONVERTER
#define EOM_TYPE_URI_CONVERTER (eom_uri_converter_get_type ())
Definition at line 10 of file eom-uri-converter.h.
EOM_UC_ERROR
#define EOM_UC_ERROR eom_uc_error_quark ()
Definition at line 53 of file eom-uri-converter.h.
EOM_URI_CONVERTER
#define EOM_URI_CONVERTER (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), EOM_TYPE_URI_CONVERTER, EomURIConverter))
Definition at line 11 of file eom-uri-converter.h.
EOM_URI_CONVERTER_CLASS
#define EOM_URI_CONVERTER_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), EOM_TYPE_URI_CONVERTER, EomURIConverterClass))
Definition at line 12 of file eom-uri-converter.h.
EOM_URI_CONVERTER_GET_CLASS
#define EOM_URI_CONVERTER_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), EOM_TYPE_URI_CONVERTER, EomURIConverterClass))
Definition at line 15 of file eom-uri-converter.h.
Typedef Documentation
EomURIConverterClass
typedef struct _EomURIConverterClass EomURIConverterClass
Definition at line 21 of file eom-uri-converter.h.
EomURIConverterPrivate
typedef struct _EomURIConverterPrivate EomURIConverterPrivate
Definition at line 22 of file eom-uri-converter.h.
Enumeration Type Documentation
EomUCError
enum EomUCError
Enumerator
EOM_UC_ERROR_INVALID_UNICODE
EOM_UC_ERROR_INVALID_CHARACTER
EOM_UC_ERROR_EQUAL_FILENAMES
EOM_UC_ERROR_UNKNOWN
Definition at line 46 of file eom-uri-converter.h.
EomUCType
enum EomUCType
Enumerator
EOM_UC_STRING
EOM_UC_FILENAME
EOM_UC_COUNTER
EOM_UC_COMMENT
EOM_UC_DATE
EOM_UC_TIME
EOM_UC_DAY
EOM_UC_MONTH
EOM_UC_YEAR
EOM_UC_HOUR
EOM_UC_MINUTE
EOM_UC_SECOND
EOM_UC_END
Definition at line 24 of file eom-uri-converter.h.
Function Documentation
eom_uc_error_quark()
G_GNUC_INTERNAL GQuark eom_uc_error_quark (void)
Definition at line 160 of file eom-uri-converter.c.
eom_uri_converter_check()
G_GNUC_INTERNAL gboolean eom_uri_converter_check (EomURIConverter * converter, GList * img_list, GError ** error)
eom_uri_converter_check: @converter: a EomURIConverter @img_list: (element-type GFile): a #Gfile list @error: a #GError location to store the error occurring, or NULL to ignore
Definition at line 937 of file eom-uri-converter.c.
References _, EOM_IMAGE, EOM_IS_URI_CONVERTER, EOM_UC_ERROR, EOM_UC_ERROR_EQUAL_FILENAMES, eom_uri_converter_do(), error, FALSE, file_list, NULL, and TRUE.
eom_uri_converter_do()
G_GNUC_INTERNAL gboolean eom_uri_converter_do (EomURIConverter * converter, EomImage * image, GFile ** file, GdkPixbufFormat ** format, GError ** error)
Definition at line 713 of file eom-uri-converter.c.
References EOM_IS_URI_CONVERTER, EOM_UC_COMMENT, EOM_UC_COUNTER, EOM_UC_DATE, EOM_UC_DAY, EOM_UC_FILENAME, EOM_UC_HOUR, EOM_UC_MINUTE, EOM_UC_MONTH, EOM_UC_SECOND, EOM_UC_STRING, EOM_UC_TIME, EOM_UC_YEAR, FALSE, NULL, _EomURIConverter::priv, and TRUE.
Referenced by eom_uri_converter_check().
eom_uri_converter_get_type()
G_GNUC_INTERNAL GType eom_uri_converter_get_type (void)
eom_uri_converter_new()
G_GNUC_INTERNAL EomURIConverter * eom_uri_converter_new (GFile * base_file, GdkPixbufFormat * img_format, const char * format_string)
Definition at line 499 of file eom-uri-converter.c.
References EOM_TYPE_URI_CONVERTER, NULL, and _EomURIConverter::priv.
Referenced by eom_save_as_dialog_get_converter().
eom_uri_converter_preview()
G_GNUC_INTERNAL char * eom_uri_converter_preview (const char * format_str, EomImage * img, GdkPixbufFormat * format, gulong counter, guint n_images, gboolean convert_spaces, gunichar space_char)
Definition at line 800 of file eom-uri-converter.c.
References eom_image_get_file(), EOM_IS_IMAGE, eom_pixbuf_get_common_suffix(), EOM_UC_COMMENT, EOM_UC_DATE, EOM_UC_DAY, EOM_UC_HOUR, EOM_UC_MINUTE, EOM_UC_MONTH, EOM_UC_SECOND, EOM_UC_TIME, EOM_UC_YEAR, FALSE, MAX, MIN, name, NULL, TRUE, and type.
eom_uri_converter_print_list()
G_GNUC_INTERNAL void eom_uri_converter_print_list (EomURIConverter * conv)
Definition at line 433 of file eom-uri-converter.c.
References EOM_UC_COMMENT, EOM_UC_COUNTER, EOM_UC_DATE, EOM_UC_DAY, EOM_UC_FILENAME, EOM_UC_HOUR, EOM_UC_MINUTE, EOM_UC_MONTH, EOM_UC_SECOND, EOM_UC_STRING, EOM_UC_TIME, EOM_UC_YEAR, EOM_URI_CONVERTER, NULL, and _EomURIConverter::priv.
eom_uri_converter_requires_exif()
G_GNUC_INTERNAL gboolean eom_uri_converter_requires_exif (EomURIConverter * converter)
Definition at line 922 of file eom-uri-converter.c.
References EOM_IS_URI_CONVERTER, FALSE, and _EomURIConverter::priv.