MATE Desktop Environment: eom-debug.h File Reference
eom-debug.h File Reference
#include <glib.h>
Macros
#define DEBUG_WINDOW EOM_DEBUG_WINDOW, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_VIEW EOM_DEBUG_VIEW, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_JOBS EOM_DEBUG_JOBS, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_THUMBNAIL EOM_DEBUG_THUMBNAIL, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_IMAGE_DATA EOM_DEBUG_IMAGE_DATA, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_IMAGE_LOAD EOM_DEBUG_IMAGE_LOAD, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_IMAGE_SAVE EOM_DEBUG_IMAGE_SAVE, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_LIST_STORE EOM_DEBUG_LIST_STORE, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_PREFERENCES EOM_DEBUG_PREFERENCES, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_PRINTING EOM_DEBUG_PRINTING, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_LCMS EOM_DEBUG_LCMS, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_PLUGINS EOM_DEBUG_PLUGINS, __FILE__, __LINE__, G_STRFUNC
Enumerations
enum EomDebug {
EOM_DEBUG_NO_DEBUG = 0 , EOM_DEBUG_WINDOW = 1 << 0 , EOM_DEBUG_VIEW = 1 << 1 , EOM_DEBUG_JOBS = 1 << 2 ,
EOM_DEBUG_THUMBNAIL = 1 << 3 , EOM_DEBUG_IMAGE_DATA = 1 << 4 , EOM_DEBUG_IMAGE_LOAD = 1 << 5 , EOM_DEBUG_IMAGE_SAVE = 1 << 6 ,
EOM_DEBUG_LIST_STORE = 1 << 7 , EOM_DEBUG_PREFERENCES = 1 << 8 , EOM_DEBUG_PRINTING = 1 << 9 , EOM_DEBUG_LCMS = 1 << 10 ,
EOM_DEBUG_PLUGINS = 1 << 11
}
Functions
void eom_debug_init (void)
void eom_debug (EomDebug section, const gchar *file, gint line, const gchar *function)
void eom_debug_message (EomDebug section, const gchar *file, gint line, const gchar *function, const gchar *format,...)
Macro Definition Documentation
DEBUG_IMAGE_DATA
#define DEBUG_IMAGE_DATA EOM_DEBUG_IMAGE_DATA, __FILE__, __LINE__, G_STRFUNC
Definition at line 53 of file eom-debug.h.
DEBUG_IMAGE_LOAD
#define DEBUG_IMAGE_LOAD EOM_DEBUG_IMAGE_LOAD, __FILE__, __LINE__, G_STRFUNC
Definition at line 54 of file eom-debug.h.
DEBUG_IMAGE_SAVE
#define DEBUG_IMAGE_SAVE EOM_DEBUG_IMAGE_SAVE, __FILE__, __LINE__, G_STRFUNC
Definition at line 55 of file eom-debug.h.
DEBUG_JOBS
#define DEBUG_JOBS EOM_DEBUG_JOBS, __FILE__, __LINE__, G_STRFUNC
Definition at line 51 of file eom-debug.h.
DEBUG_LCMS
#define DEBUG_LCMS EOM_DEBUG_LCMS, __FILE__, __LINE__, G_STRFUNC
Definition at line 59 of file eom-debug.h.
DEBUG_LIST_STORE
#define DEBUG_LIST_STORE EOM_DEBUG_LIST_STORE, __FILE__, __LINE__, G_STRFUNC
Definition at line 56 of file eom-debug.h.
DEBUG_PLUGINS
#define DEBUG_PLUGINS EOM_DEBUG_PLUGINS, __FILE__, __LINE__, G_STRFUNC
Definition at line 60 of file eom-debug.h.
DEBUG_PREFERENCES
#define DEBUG_PREFERENCES EOM_DEBUG_PREFERENCES, __FILE__, __LINE__, G_STRFUNC
Definition at line 57 of file eom-debug.h.
DEBUG_PRINTING
#define DEBUG_PRINTING EOM_DEBUG_PRINTING, __FILE__, __LINE__, G_STRFUNC
Definition at line 58 of file eom-debug.h.
DEBUG_THUMBNAIL
#define DEBUG_THUMBNAIL EOM_DEBUG_THUMBNAIL, __FILE__, __LINE__, G_STRFUNC
Definition at line 52 of file eom-debug.h.
DEBUG_VIEW
#define DEBUG_VIEW EOM_DEBUG_VIEW, __FILE__, __LINE__, G_STRFUNC
Definition at line 50 of file eom-debug.h.
DEBUG_WINDOW
#define DEBUG_WINDOW EOM_DEBUG_WINDOW, __FILE__, __LINE__, G_STRFUNC
Definition at line 49 of file eom-debug.h.
Enumeration Type Documentation
EomDebug
enum EomDebug
Enumerator
EOM_DEBUG_NO_DEBUG
EOM_DEBUG_WINDOW
EOM_DEBUG_VIEW
EOM_DEBUG_JOBS
EOM_DEBUG_THUMBNAIL
EOM_DEBUG_IMAGE_DATA
EOM_DEBUG_IMAGE_LOAD
EOM_DEBUG_IMAGE_SAVE
EOM_DEBUG_LIST_STORE
EOM_DEBUG_PREFERENCES
EOM_DEBUG_PRINTING
EOM_DEBUG_LCMS
EOM_DEBUG_PLUGINS
Definition at line 33 of file eom-debug.h.
Function Documentation
eom_debug()
void eom_debug (EomDebug section, const gchar * file, gint line, const gchar * function)
Definition at line 138 of file eom-debug.c.
References debug, and NULL.
Referenced by eom_image_load(), eom_print_operation_new(), eom_window_is_empty(), eom_window_new(), and eom_window_open_file_list().
eom_debug_init()
void eom_debug_init (void)
Definition at line 46 of file eom-debug.c.
References debug, EOM_DEBUG_IMAGE_DATA, EOM_DEBUG_IMAGE_LOAD, EOM_DEBUG_IMAGE_SAVE, EOM_DEBUG_JOBS, EOM_DEBUG_LCMS, EOM_DEBUG_LIST_STORE, EOM_DEBUG_NO_DEBUG, EOM_DEBUG_PLUGINS, EOM_DEBUG_PREFERENCES, EOM_DEBUG_PRINTING, EOM_DEBUG_THUMBNAIL, EOM_DEBUG_VIEW, EOM_DEBUG_WINDOW, and NULL.
Referenced by main().
eom_debug_message()
void eom_debug_message (EomDebug section, const gchar * file, gint line, const gchar * function, const gchar * format, ...)
Definition at line 101 of file eom-debug.c.
References debug, and NULL.
Referenced by eom_thumbnail_load().