MATE Desktop Environment: eom-print-image-setup.h File Reference
eom-print-image-setup.h File Reference
#include "eom-image.h"
Classes
struct _EomPrintImageSetup
struct _EomPrintImageSetupClass
Macros
#define EOM_TYPE_PRINT_IMAGE_SETUP (eom_print_image_setup_get_type ())
#define EOM_PRINT_IMAGE_SETUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EOM_TYPE_PRINT_IMAGE_SETUP, EomPrintImageSetup))
#define EOM_PRINT_IMAGE_SETUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EOM_TYPE_PRINT_IMAGE_SETUP, EomPrintImageSetupClass))
#define EOM_IS_PRINT_IMAGE_SETUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EOM_TYPE_PRINT_IMAGE_SETUP))
#define EOM_IS_PRINT_IMAGE_SETUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EOM_TYPE_PRINT_IMAGE_SETUP))
#define EOM_PRINT_IMAGE_SETUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EOM_TYPE_PRINT_IMAGE_SETUP, EomPrintImageSetupClass))
Typedefs
typedef struct _EomPrintImageSetup EomPrintImageSetup
typedef struct _EomPrintImageSetupClass EomPrintImageSetupClass
typedef struct _EomPrintImageSetupPrivate EomPrintImageSetupPrivate
Functions
G_GNUC_INTERNAL GType eom_print_image_setup_get_type (void)
G_GNUC_INTERNAL GtkWidget * eom_print_image_setup_new (EomImage *image, GtkPageSetup *page_setup)
G_GNUC_INTERNAL void eom_print_image_setup_get_options (EomPrintImageSetup *setup, gdouble *left, gdouble *top, gdouble *scale, GtkUnit *unit)
void eom_print_image_setup_update (GtkPrintOperation *operation, GtkWidget *custom_widget, GtkPageSetup *page_setup, GtkPrintSettings *print_settings, gpointer user_data)
Macro Definition Documentation
EOM_IS_PRINT_IMAGE_SETUP
#define EOM_IS_PRINT_IMAGE_SETUP (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EOM_TYPE_PRINT_IMAGE_SETUP))
Definition at line 36 of file eom-print-image-setup.h.
EOM_IS_PRINT_IMAGE_SETUP_CLASS
#define EOM_IS_PRINT_IMAGE_SETUP_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EOM_TYPE_PRINT_IMAGE_SETUP))
Definition at line 37 of file eom-print-image-setup.h.
EOM_PRINT_IMAGE_SETUP
#define EOM_PRINT_IMAGE_SETUP (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EOM_TYPE_PRINT_IMAGE_SETUP, EomPrintImageSetup))
Definition at line 34 of file eom-print-image-setup.h.
EOM_PRINT_IMAGE_SETUP_CLASS
#define EOM_PRINT_IMAGE_SETUP_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EOM_TYPE_PRINT_IMAGE_SETUP, EomPrintImageSetupClass))
Definition at line 35 of file eom-print-image-setup.h.
EOM_PRINT_IMAGE_SETUP_GET_CLASS
#define EOM_PRINT_IMAGE_SETUP_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EOM_TYPE_PRINT_IMAGE_SETUP, EomPrintImageSetupClass))
Definition at line 38 of file eom-print-image-setup.h.
EOM_TYPE_PRINT_IMAGE_SETUP
#define EOM_TYPE_PRINT_IMAGE_SETUP (eom_print_image_setup_get_type ())
Definition at line 33 of file eom-print-image-setup.h.
Typedef Documentation
EomPrintImageSetup
typedef struct _EomPrintImageSetup EomPrintImageSetup
Definition at line 29 of file eom-print-image-setup.h.
EomPrintImageSetupClass
typedef struct _EomPrintImageSetupClass EomPrintImageSetupClass
Definition at line 30 of file eom-print-image-setup.h.
EomPrintImageSetupPrivate
typedef struct _EomPrintImageSetupPrivate EomPrintImageSetupPrivate
Definition at line 31 of file eom-print-image-setup.h.
Function Documentation
eom_print_image_setup_get_options()
G_GNUC_INTERNAL void eom_print_image_setup_get_options (EomPrintImageSetup * setup, gdouble * left, gdouble * top, gdouble * scale, GtkUnit * unit)
eom_print_image_setup_get_options: @setup: a EomPrintImageSetup @left: a pointer where to store the image's left position @top: a pointer where to store the image's top position @scale: a pointer where to store the image's scale @unit: a pointer where to store the #GtkUnit used by the @left and @top values.
Gets the options set by the EomPrintImageSetup.
Definition at line 1024 of file eom-print-image-setup.c.
References EOM_IS_PRINT_IMAGE_SETUP, and _EomPrintImageSetup::priv.
eom_print_image_setup_get_type()
G_GNUC_INTERNAL GType eom_print_image_setup_get_type (void)
eom_print_image_setup_new()
G_GNUC_INTERNAL GtkWidget * eom_print_image_setup_new (EomImage * image, GtkPageSetup * page_setup)
eom_print_image_setup_new: the EomImage to print @page_setup: a #GtkPageSetup specifying the page where the image will be print
Creates a new EomPrintImageSetup widget, to be used as a custom widget in a #GtkPrintUnixDialog. This widgets allows to set the image position and scale in a page.
Returns: a new EomPrintImageSetup
Definition at line 988 of file eom-print-image-setup.c.
References EOM_PRINT_IMAGE_SETUP, EOM_PRINT_PREVIEW, eom_print_preview_set_from_page_setup(), EOM_TYPE_PRINT_IMAGE_SETUP, and NULL.
eom_print_image_setup_update()
void eom_print_image_setup_update (GtkPrintOperation * operation, GtkWidget * custom_widget, GtkPageSetup * page_setup, GtkPrintSettings * print_settings, gpointer user_data)
Definition at line 1043 of file eom-print-image-setup.c.
References EOM_PRINT_IMAGE_SETUP, EOM_PRINT_PREVIEW, eom_print_preview_set_from_page_setup(), eom_print_preview_set_image_position(), FACTOR_MM_TO_INCH, and _EomPrintImageSetup::priv.
Referenced by eom_print_operation_new().