MATE Desktop Environment: eom-image-save-info.h File Reference
eom-image-save-info.h File Reference
#include <glib-object.h>
#include <gio/gio.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
Classes
struct _EomImageSaveInfo
struct _EomImageSaveInfoClass
Macros
#define __EOM_IMAGE_DECLR__
#define EOM_TYPE_IMAGE_SAVE_INFO (eom_image_save_info_get_type ())
#define EOM_IMAGE_SAVE_INFO(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), EOM_TYPE_IMAGE_SAVE_INFO, EomImageSaveInfo))
#define EOM_IMAGE_SAVE_INFO_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), EOM_TYPE_IMAGE_SAVE_INFO, EomImageSaveInfoClass))
#define EOM_IS_IMAGE_SAVE_INFO(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), EOM_TYPE_IMAGE_SAVE_INFO))
#define EOM_IS_IMAGE_SAVE_INFO_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), EOM_TYPE_IMAGE_SAVE_INFO))
#define EOM_IMAGE_SAVE_INFO_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), EOM_TYPE_IMAGE_SAVE_INFO, EomImageSaveInfoClass))
#define EOM_FILE_FORMAT_JPEG "jpeg"
Typedefs
typedef struct _EomImage EomImage
typedef struct _EomImageSaveInfo EomImageSaveInfo
typedef struct _EomImageSaveInfoClass EomImageSaveInfoClass
Functions
GType eom_image_save_info_get_type (void)
EomImageSaveInfo * eom_image_save_info_new_from_image (EomImage *image)
EomImageSaveInfo * eom_image_save_info_new_from_uri (const char *uri, GdkPixbufFormat *format)
EomImageSaveInfo * eom_image_save_info_new_from_file (GFile *file, GdkPixbufFormat *format)
Macro Definition Documentation
__EOM_IMAGE_DECLR__
#define __EOM_IMAGE_DECLR__
Definition at line 11 of file eom-image-save-info.h.
EOM_FILE_FORMAT_JPEG
#define EOM_FILE_FORMAT_JPEG "jpeg"
Definition at line 43 of file eom-image-save-info.h.
EOM_IMAGE_SAVE_INFO
#define EOM_IMAGE_SAVE_INFO (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), EOM_TYPE_IMAGE_SAVE_INFO, EomImageSaveInfo))
Definition at line 16 of file eom-image-save-info.h.
EOM_IMAGE_SAVE_INFO_CLASS
#define EOM_IMAGE_SAVE_INFO_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), EOM_TYPE_IMAGE_SAVE_INFO, EomImageSaveInfoClass))
Definition at line 17 of file eom-image-save-info.h.
EOM_IMAGE_SAVE_INFO_GET_CLASS
#define EOM_IMAGE_SAVE_INFO_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), EOM_TYPE_IMAGE_SAVE_INFO, EomImageSaveInfoClass))
Definition at line 20 of file eom-image-save-info.h.
EOM_IS_IMAGE_SAVE_INFO
#define EOM_IS_IMAGE_SAVE_INFO (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), EOM_TYPE_IMAGE_SAVE_INFO))
Definition at line 18 of file eom-image-save-info.h.
EOM_IS_IMAGE_SAVE_INFO_CLASS
#define EOM_IS_IMAGE_SAVE_INFO_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), EOM_TYPE_IMAGE_SAVE_INFO))
Definition at line 19 of file eom-image-save-info.h.
EOM_TYPE_IMAGE_SAVE_INFO
#define EOM_TYPE_IMAGE_SAVE_INFO (eom_image_save_info_get_type ())
Definition at line 15 of file eom-image-save-info.h.
Typedef Documentation
EomImage
typedef struct _EomImage EomImage
Definition at line 12 of file eom-image-save-info.h.
EomImageSaveInfo
typedef struct _EomImageSaveInfo EomImageSaveInfo
Definition at line 22 of file eom-image-save-info.h.
EomImageSaveInfoClass
typedef struct _EomImageSaveInfoClass EomImageSaveInfoClass
Definition at line 23 of file eom-image-save-info.h.
Function Documentation
eom_image_save_info_get_type()
GType eom_image_save_info_get_type (void)
eom_image_save_info_new_from_file()
EomImageSaveInfo * eom_image_save_info_new_from_file (GFile * file, GdkPixbufFormat * format)
Definition at line 121 of file eom-image-save-info.c.
References EOM_TYPE_IMAGE_SAVE_INFO, _EomImageSaveInfo::exists, FALSE, _EomImageSaveInfo::file, _EomImageSaveInfo::format, _EomImageSaveInfo::has_metadata, _EomImageSaveInfo::jpeg_quality, _EomImageSaveInfo::local, _EomImageSaveInfo::modified, NULL, and _EomImageSaveInfo::overwrite.
Referenced by eom_image_save_info_new_from_uri().
eom_image_save_info_new_from_image()
EomImageSaveInfo * eom_image_save_info_new_from_image (EomImage * image)
Definition at line 82 of file eom-image-save-info.c.
References EOM_IMAGE_DATA_EXIF, eom_image_get_file(), eom_image_has_data(), eom_image_is_modified(), EOM_IS_IMAGE, EOM_TYPE_IMAGE_SAVE_INFO, _EomImageSaveInfo::exists, FALSE, _EomImageSaveInfo::file, _EomImagePrivate::file_type, _EomImageSaveInfo::format, _EomImageSaveInfo::has_metadata, _EomImageSaveInfo::jpeg_quality, _EomImageSaveInfo::local, _EomImageSaveInfo::modified, NULL, _EomImageSaveInfo::overwrite, and _EomImage::priv.
eom_image_save_info_new_from_uri()
EomImageSaveInfo * eom_image_save_info_new_from_uri (const char * uri, GdkPixbufFormat * format)
Definition at line 104 of file eom-image-save-info.c.
References eom_image_save_info_new_from_file(), and NULL.