MATE Desktop Environment: eom-application.c File Reference
eom-application.c File Reference
#include "eom-image.h"
#include "eom-session.h"
#include "eom-window.h"
#include "eom-application.h"
#include "eom-application-activatable.h"
#include "eom-application-internal.h"
#include "eom-util.h"
#include <string.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
Macros
#define APPLICATION_SERVICE_NAME "org.mate.eom.ApplicationService"
Functions
G_DEFINE_TYPE_WITH_PRIVATE (EomApplication, eom_application, GTK_TYPE_APPLICATION)
EomApplication * eom_application_get_instance (void)
gboolean eom_application_open_window (EomApplication *application, guint32 timestamp, EomStartupFlags flags, GError **error)
gboolean eom_application_open_file_list (EomApplication *application, GSList *file_list, guint timestamp, EomStartupFlags flags, GError **error)
gboolean eom_application_open_uri_list (EomApplication *application, GSList *uri_list, guint timestamp, EomStartupFlags flags, GError **error)
gboolean eom_application_open_uris (EomApplication *application, gchar **uris, guint timestamp, EomStartupFlags flags, GError **error)
EggToolbarsModel * eom_application_get_toolbars_model (EomApplication *application)
void eom_application_save_toolbars_model (EomApplication *application)
void eom_application_reset_toolbars_model (EomApplication *app)
Macro Definition Documentation
APPLICATION_SERVICE_NAME
#define APPLICATION_SERVICE_NAME "org.mate.eom.ApplicationService"
Definition at line 44 of file eom-application.c.
Function Documentation
eom_application_get_instance()
EomApplication * eom_application_get_instance (void)
eom_application_get_instance:
Returns a singleton instance of EomApplication currently running. If not running yet, it will create one.
Returns: (transfer none): a running EomApplication.
Definition at line 225 of file eom-application.c.
References APPLICATION_SERVICE_NAME, EOM_APPLICATION, EOM_TYPE_APPLICATION, and NULL.
eom_application_get_toolbars_model()
EggToolbarsModel * eom_application_get_toolbars_model (EomApplication * application)
eom_application_get_toolbars_model: @application: An EomApplication.
Retrieves the EggToolbarsModel for the toolbar in EomApplication.
Returns: (transfer none): An EggToolbarsModel.
Definition at line 464 of file eom-application.c.
References EOM_IS_APPLICATION, NULL, _EomApplication::priv, and _EomApplicationPrivate::toolbars_model.
eom_application_open_file_list()
gboolean eom_application_open_file_list (EomApplication * application, GSList * file_list, guint timestamp, EomStartupFlags flags, GError ** error)
eom_application_open_file_list: @application: An EomApplication. @file_list: (element-type GFile): A list of #GFiles @timestamp: The timestamp of the user interaction which triggered this call (see gtk_window_present_with_time()). @flags: A set of EomStartupFlags influencing a new windows' state. @error: Return location for a #GError, or NULL to ignore errors.
Opens a list of files in a EomWindow. If an EomWindow displaying the first image in the list is already open, this will be used. Otherwise, an empty EomWindow is used, either already existing or newly created.
Returns: Currently always TRUE.
Definition at line 358 of file eom-application.c.
References EOM_WINDOW, eom_window_new(), eom_window_open_file_list(), file_list, NULL, and TRUE.
Referenced by eom_application_open_uri_list(), and eom_application_open_uris().
eom_application_open_uri_list()
gboolean eom_application_open_uri_list (EomApplication * application, GSList * uri_list, guint timestamp, EomStartupFlags flags, GError ** error)
eom_application_open_uri_list: @application: An EomApplication. @uri_list: (element-type utf8): A list of URIs. @timestamp: The timestamp of the user interaction which triggered this call (see gtk_window_present_with_time()). @flags: A set of EomStartupFlags influencing a new windows' state. @error: Return location for a #GError, or NULL to ignore errors.
Opens a list of images, from a list of URIs. See eom_application_open_file_list() for details.
Returns: Currently always TRUE.
Definition at line 407 of file eom-application.c.
References eom_application_open_file_list(), EOM_IS_APPLICATION, eom_util_string_list_to_file_list(), error, FALSE, file_list, and NULL.
eom_application_open_uris()
gboolean eom_application_open_uris (EomApplication * application, gchar ** uris, guint timestamp, EomStartupFlags flags, GError ** error)
eom_application_open_uris: @application: an EomApplication @uris: A #GList of URI strings. @timestamp: The timestamp of the user interaction which triggered this call (see gtk_window_present_with_time()). @flags: A set of EomStartupFlags influencing a new windows' state. @error: Return location for a #GError, or NULL to ignore errors.
Opens a list of images, from a list of URI strings. See eom_application_open_file_list() for details.
Returns: Currently always TRUE.
Definition at line 441 of file eom-application.c.
References eom_application_open_file_list(), eom_util_strings_to_file_list(), error, file_list, and NULL.
eom_application_open_window()
gboolean eom_application_open_window (EomApplication * application, guint32 timestamp, EomStartupFlags flags, GError ** error)
eom_application_open_window: @application: An EomApplication. @timestamp: The timestamp of the user interaction which triggered this call (see gtk_window_present_with_time()). @flags: A set of EomStartupFlags influencing a new windows' state. @error: Return location for a #GError, or NULL to ignore errors.
Opens and presents an empty EomWindow to the user. If there is an empty window already open, this will be used. Otherwise, a new one will be instantiated.
Returns: FALSE if @application is invalid, TRUE otherwise
Definition at line 277 of file eom-application.c.
References EOM_IS_APPLICATION, eom_window_new(), FALSE, NULL, and TRUE.
eom_application_reset_toolbars_model()
void eom_application_reset_toolbars_model (EomApplication * app)
eom_application_reset_toolbars_model: @app: an EomApplication
Restores the toolbars model to the defaults.
Definition at line 493 of file eom-application.c.
References EGG_TB_MODEL_NOT_REMOVABLE, egg_toolbars_model_load_names(), egg_toolbars_model_load_toolbars(), egg_toolbars_model_new(), egg_toolbars_model_set_flags(), EOM_IS_APPLICATION, _EomApplication::priv, and _EomApplicationPrivate::toolbars_model.
eom_application_save_toolbars_model()
void eom_application_save_toolbars_model (EomApplication * application)
eom_application_save_toolbars_model: @application: An EomApplication.
Causes the saving of the model of the toolbar in EomApplication to a file.
Definition at line 478 of file eom-application.c.
References egg_toolbars_model_save_toolbars(), NULL, _EomApplication::priv, _EomApplicationPrivate::toolbars_file, and _EomApplicationPrivate::toolbars_model.
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (EomApplication , eom_application , GTK_TYPE_APPLICATION)