MATE Desktop Environment: eom-thumb-view.h File Reference
eom-thumb-view.h File Reference
#include "eom-image.h"
#include "eom-list-store.h"
Classes
struct _EomThumbView
struct _EomThumbViewClass
Macros
#define EOM_TYPE_THUMB_VIEW (eom_thumb_view_get_type ())
#define EOM_THUMB_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EOM_TYPE_THUMB_VIEW, EomThumbView))
#define EOM_THUMB_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EOM_TYPE_THUMB_VIEW, EomThumbViewClass))
#define EOM_IS_THUMB_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EOM_TYPE_THUMB_VIEW))
#define EOM_IS_THUMB_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EOM_TYPE_THUMB_VIEW))
#define EOM_THUMB_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EOM_TYPE_THUMB_VIEW, EomThumbViewClass))
Typedefs
typedef struct _EomThumbView EomThumbView
typedef struct _EomThumbViewClass EomThumbViewClass
typedef struct _EomThumbViewPrivate EomThumbViewPrivate
Enumerations
enum EomThumbViewSelectionChange {
EOM_THUMB_VIEW_SELECT_CURRENT = 0 , EOM_THUMB_VIEW_SELECT_LEFT , EOM_THUMB_VIEW_SELECT_RIGHT , EOM_THUMB_VIEW_SELECT_FIRST ,
EOM_THUMB_VIEW_SELECT_LAST , EOM_THUMB_VIEW_SELECT_RANDOM
}
Functions
GType eom_thumb_view_get_type (void)
GtkWidget * eom_thumb_view_new (void)
void eom_thumb_view_set_model (EomThumbView *thumbview, EomListStore *store)
void eom_thumb_view_set_item_height (EomThumbView *thumbview, gint height)
guint eom_thumb_view_get_n_selected (EomThumbView *thumbview)
EomImage * eom_thumb_view_get_first_selected_image (EomThumbView *thumbview)
GList * eom_thumb_view_get_selected_images (EomThumbView *thumbview)
void eom_thumb_view_select_single (EomThumbView *thumbview, EomThumbViewSelectionChange change)
void eom_thumb_view_set_current_image (EomThumbView *thumbview, EomImage *image, gboolean deselect_other)
void eom_thumb_view_set_thumbnail_popup (EomThumbView *thumbview, GtkMenu *menu)
Macro Definition Documentation
EOM_IS_THUMB_VIEW
#define EOM_IS_THUMB_VIEW (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EOM_TYPE_THUMB_VIEW))
Definition at line 33 of file eom-thumb-view.h.
EOM_IS_THUMB_VIEW_CLASS
#define EOM_IS_THUMB_VIEW_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EOM_TYPE_THUMB_VIEW))
Definition at line 34 of file eom-thumb-view.h.
EOM_THUMB_VIEW
#define EOM_THUMB_VIEW (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EOM_TYPE_THUMB_VIEW, EomThumbView))
Definition at line 31 of file eom-thumb-view.h.
EOM_THUMB_VIEW_CLASS
#define EOM_THUMB_VIEW_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EOM_TYPE_THUMB_VIEW, EomThumbViewClass))
Definition at line 32 of file eom-thumb-view.h.
EOM_THUMB_VIEW_GET_CLASS
#define EOM_THUMB_VIEW_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EOM_TYPE_THUMB_VIEW, EomThumbViewClass))
Definition at line 35 of file eom-thumb-view.h.
EOM_TYPE_THUMB_VIEW
#define EOM_TYPE_THUMB_VIEW (eom_thumb_view_get_type ())
Definition at line 30 of file eom-thumb-view.h.
Typedef Documentation
EomThumbView
typedef struct _EomThumbView EomThumbView
Definition at line 37 of file eom-thumb-view.h.
EomThumbViewClass
typedef struct _EomThumbViewClass EomThumbViewClass
Definition at line 38 of file eom-thumb-view.h.
EomThumbViewPrivate
typedef struct _EomThumbViewPrivate EomThumbViewPrivate
Definition at line 39 of file eom-thumb-view.h.
Enumeration Type Documentation
EomThumbViewSelectionChange
enum EomThumbViewSelectionChange
Enumerator
EOM_THUMB_VIEW_SELECT_CURRENT
EOM_THUMB_VIEW_SELECT_LEFT
EOM_THUMB_VIEW_SELECT_RIGHT
EOM_THUMB_VIEW_SELECT_FIRST
EOM_THUMB_VIEW_SELECT_LAST
EOM_THUMB_VIEW_SELECT_RANDOM
Definition at line 41 of file eom-thumb-view.h.
Function Documentation
eom_thumb_view_get_first_selected_image()
EomImage * eom_thumb_view_get_first_selected_image (EomThumbView * thumbview)
eom_thumb_view_get_first_selected_image: @thumbview: A EomThumbView.
Returns the first selected image. Note that the returned EomImage is not ensured to be really the first selected image in @thumbview, but generally, it will be.
Returns: (transfer full): A EomImage.
Definition at line 851 of file eom-thumb-view.c.
References NULL.
eom_thumb_view_get_n_selected()
guint eom_thumb_view_get_n_selected (EomThumbView * thumbview)
eom_thumb_view_get_n_selected: @thumbview: An EomThumbView.
Gets the number of images that are currently selected in @thumbview.
Returns: the number of selected images in @thumbview.
Definition at line 804 of file eom-thumb-view.c.
Referenced by eom_thumb_view_select_single().
eom_thumb_view_get_selected_images()
GList * eom_thumb_view_get_selected_images (EomThumbView * thumbview)
eom_thumb_view_get_selected_images: @thumbview: A EomThumbView.
Gets a list with the currently selected images. Note that a new reference is hold for each image and the list must be freed with g_list_free().
Returns: (element-type EomImage) (transfer full): A newly allocated list of EomImage's.
Definition at line 883 of file eom-thumb-view.c.
References item, and NULL.
eom_thumb_view_get_type()
GType eom_thumb_view_get_type (void)
eom_thumb_view_new()
GtkWidget * eom_thumb_view_new (void)
eom_thumb_view_new:
Creates a new EomThumbView object.
Returns: a newly created EomThumbView.
Definition at line 662 of file eom-thumb-view.c.
References EOM_TYPE_THUMB_VIEW, and NULL.
eom_thumb_view_select_single()
void eom_thumb_view_select_single (EomThumbView * thumbview, EomThumbViewSelectionChange change)
eom_thumb_view_select_single: @thumbview: A EomThumbView. @change: A EomThumbViewSelectionChange, describing the desired selection change.
Changes the current selection according to a single movement described by EomThumbViewSelectionChange. If there are no thumbnails currently selected, one is selected according to the natural selection according to the EomThumbViewSelectionChange used, p.g., when EOM_THUMB_VIEW_SELECT_RIGHT is the selected change, the first thumbnail will be selected.
Definition at line 957 of file eom-thumb-view.c.
References EOM_IS_THUMB_VIEW, EOM_LIST_STORE, eom_list_store_length(), eom_thumb_view_get_n_selected(), EOM_THUMB_VIEW_SELECT_CURRENT, EOM_THUMB_VIEW_SELECT_FIRST, EOM_THUMB_VIEW_SELECT_LAST, EOM_THUMB_VIEW_SELECT_LEFT, EOM_THUMB_VIEW_SELECT_RANDOM, EOM_THUMB_VIEW_SELECT_RIGHT, FALSE, and NULL.
Referenced by eom_window_reload_image().
eom_thumb_view_set_current_image()
void eom_thumb_view_set_current_image (EomThumbView * thumbview, EomImage * image, gboolean deselect_other)
eom_thumb_view_set_current_image: @thumbview: A EomThumbView. The image to be selected. @deselect_other: Whether to deselect currently selected images.
Changes the status of a image, marking it as currently selected. If @deselect_other is TRUE, all other selected images will be deselected.
Definition at line 916 of file eom-thumb-view.c.
References EOM_LIST_STORE, eom_list_store_get_pos_by_image(), FALSE, and NULL.
eom_thumb_view_set_item_height()
void eom_thumb_view_set_item_height (EomThumbView * thumbview, gint height)
eom_thumb_view_set_item_height: @thumbview: A EomThumbView. @height: The desired height.
Sets the height of each thumbnail in @thumbview.
Definition at line 777 of file eom-thumb-view.c.
References EOM_IS_THUMB_VIEW, NULL, and _EomThumbView::priv.
Referenced by eom_thumb_nav_set_mode().
eom_thumb_view_set_model()
void eom_thumb_view_set_model (EomThumbView * thumbview, EomListStore * store)
eom_thumb_view_set_model: @thumbview: A EomThumbView. @store: A EomListStore.
Sets the EomListStore to be used with @thumbview. If an initial image was set during @store creation, its thumbnail will be selected and visible.
Definition at line 718 of file eom-thumb-view.c.
References EOM_IS_LIST_STORE, EOM_IS_THUMB_VIEW, eom_list_store_get_initial_pos(), eom_list_store_length(), FALSE, NULL, and _EomThumbView::priv.
eom_thumb_view_set_thumbnail_popup()
void eom_thumb_view_set_thumbnail_popup (EomThumbView * thumbview, GtkMenu * menu)
eom_thumb_view_set_thumbnail_popup: @thumbview: An EomThumbView. @menu: A #GtkMenu.
Set the contextual menu to be used with the thumbnails in the widget. This can be done only once.
Definition at line 1046 of file eom-thumb-view.c.
References EOM_IS_THUMB_VIEW, NULL, and _EomThumbView::priv.