MATE Desktop Environment: eom-thumbnail.c File Reference
eom-thumbnail.c File Reference
#include <libmate-desktop/mate-desktop-thumbnail.h>
#include "eom-thumbnail.h"
#include "eom-list-store.h"
#include "eom-debug.h"
#include "eom-util.h"
Macros
#define MATE_DESKTOP_USE_UNSTABLE_API
#define EOM_THUMB_ERROR eom_thumb_error_quark ()
Enumerations
enum EomThumbError { EOM_THUMB_ERROR_VFS , EOM_THUMB_ERROR_GENERIC , EOM_THUMB_ERROR_UNKNOWN }
Functions
GdkPixbuf * eom_thumbnail_add_frame (GdkPixbuf *thumbnail)
GdkPixbuf * eom_thumbnail_fit_to_size (GdkPixbuf *thumbnail, gint dimension)
GdkPixbuf * eom_thumbnail_load (EomImage *image, GError **error)
void eom_thumbnail_init (void)
Macro Definition Documentation
EOM_THUMB_ERROR
#define EOM_THUMB_ERROR eom_thumb_error_quark ()
Definition at line 41 of file eom-thumbnail.c.
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 32 of file eom-thumbnail.c.
Enumeration Type Documentation
EomThumbError
enum EomThumbError
Enumerator
EOM_THUMB_ERROR_VFS
EOM_THUMB_ERROR_GENERIC
EOM_THUMB_ERROR_UNKNOWN
Definition at line 46 of file eom-thumbnail.c.
Function Documentation
eom_thumbnail_add_frame()
GdkPixbuf * eom_thumbnail_add_frame (GdkPixbuf * thumbnail)
eom_thumbnail_add_frame: @thumbnail: a #GdkPixbuf
Adds a frame to @thumbnail
Returns: (transfer full): a new #GdkPixbuf, storing @thumbnail nicely framed.
Definition at line 392 of file eom-thumbnail.c.
References FALSE.
eom_thumbnail_fit_to_size()
GdkPixbuf * eom_thumbnail_fit_to_size (GdkPixbuf * thumbnail, gint dimension)
eom_thumbnail_fit_to_size: @thumbnail: a #GdkPixbuf @dimension: the maximum width or height desired
Ensures a pixbuf fits a given @dimension
Returns: (transfer full): a new #GdkPixbuf
Definition at line 430 of file eom-thumbnail.c.
References MAX.
eom_thumbnail_init()
void eom_thumbnail_init (void)
Definition at line 533 of file eom-thumbnail.c.
References mate_desktop_thumbnail_factory_new(), MATE_DESKTOP_THUMBNAIL_SIZE_NORMAL, and NULL.
Referenced by main().
eom_thumbnail_load()
GdkPixbuf * eom_thumbnail_load (EomImage * image, GError ** error)
eom_thumbnail_load: a EomImage @error: location to store the error ocurring or NULL to ignore
Loads the thumbnail forIn case of error, NULL is returned and @error is set.
Returns: (transfer full): a new #GdkPixbuf with the thumbnail for NULL in case of error.
Definition at line 469 of file eom-thumbnail.c.
References data, DEBUG_THUMBNAIL, eom_debug_message(), eom_image_get_file(), eom_image_get_pixbuf(), eom_image_is_file_changed(), EOM_THUMB_ERROR_GENERIC, error, mate_desktop_thumbnail_factory_can_thumbnail(), mate_desktop_thumbnail_factory_create_failed_thumbnail(), mate_desktop_thumbnail_factory_generate_thumbnail(), mate_desktop_thumbnail_factory_has_valid_failed_thumbnail(), mate_desktop_thumbnail_factory_save_thumbnail(), and NULL.