MATE Desktop Environment: eom-exif-util.c File Reference
eom-exif-util.c File Reference
#include <time.h>
#include "eom-exif-util.h"
#include "eom-util.h"
#include <string.h>
#include <glib/gi18n.h>
Macros
#define DATE_BUF_SIZE 200
#define GBOOLEAN_TO_POINTER(i) (GINT_TO_POINTER ((i) ? 2 : 1))
#define GPOINTER_TO_BOOLEAN(i) ((gboolean) ((GPOINTER_TO_INT (i) == 2) ? TRUE : FALSE))
Typedefs
typedef ExifData EomExifData
Functions
gchar * eom_exif_util_format_date (const gchar *date)
void eom_exif_util_set_label_text (GtkLabel *label, EomExifData *exif_data, gint tag_id)
void eom_exif_util_format_datetime_label (GtkLabel *label, EomExifData *exif_data, gint tag_id, const gchar *format)
void eom_exif_util_set_focal_length_label_text (GtkLabel *label, EomExifData *exif_data)
const gchar * eom_exif_data_get_value (EomExifData *exif_data, gint tag_id, gchar *buffer, guint buf_size)
EomExifData * eom_exif_data_copy (EomExifData *data)
void eom_exif_data_free (EomExifData *data)
Macro Definition Documentation
DATE_BUF_SIZE
#define DATE_BUF_SIZE 200
Definition at line 43 of file eom-exif-util.c.
GBOOLEAN_TO_POINTER
#define GBOOLEAN_TO_POINTER (i) (GINT_TO_POINTER ((i) ? 2 : 1))
Definition at line 47 of file eom-exif-util.c.
GPOINTER_TO_BOOLEAN
#define GPOINTER_TO_BOOLEAN (i) ((gboolean) ((GPOINTER_TO_INT (i) == 2) ? TRUE : FALSE))
Definition at line 50 of file eom-exif-util.c.
Typedef Documentation
EomExifData
typedef ExifData EomExifData
Definition at line 53 of file eom-exif-util.c.
Function Documentation
eom_exif_data_copy()
EomExifData * eom_exif_data_copy (EomExifData * data)
Definition at line 345 of file eom-exif-util.c.
References data.
eom_exif_data_free()
void eom_exif_data_free (EomExifData * data)
Definition at line 353 of file eom-exif-util.c.
References data.
eom_exif_data_get_value()
const gchar * eom_exif_data_get_value (EomExifData * exif_data, gint tag_id, gchar * buffer, guint buf_size)
eom_exif_data_get_value: @exif_data: pointer to an <structname>ExifData</structname> struct @tag_id: the requested tag's id. See <filename>exif-tag.h</filename> from the libexif package for possible values (e.g. EXIF_TAG_EXPOSURE_MODE). @buffer: a pre-allocated output buffer @buf_size: size of @buffer
Convenience function to extract a string representation of an Exif tag directly from an <structname>ExifData</structname> struct. The string is written into @buffer as far as @buf_size permits.
Returns: a pointer to @buffer.
Definition at line 330 of file eom-exif-util.c.
Referenced by eom_exif_util_format_datetime_label(), and eom_exif_util_set_label_text().
eom_exif_util_format_date()
gchar * eom_exif_util_format_date (const gchar * date)
eom_exif_util_format_date:
Date
: a date string following Exif specifications
Takes a date string formatted after Exif specifications and generates a more readable, possibly localized, string out of it.
Returns: a newly allocated date string formatted according to the current locale.
Definition at line 186 of file eom-exif-util.c.
References _.
Referenced by eom_exif_util_set_label_text().
eom_exif_util_format_datetime_label()
void eom_exif_util_format_datetime_label (GtkLabel * label, EomExifData * exif_data, gint tag_id, const gchar * format)
Definition at line 224 of file eom-exif-util.c.
References eom_exif_data_get_value(), label, and NULL.
eom_exif_util_set_focal_length_label_text()
void eom_exif_util_set_focal_length_label_text (GtkLabel * label, EomExifData * exif_data)
Definition at line 251 of file eom-exif-util.c.
References _, label, and NULL.
eom_exif_util_set_label_text()
void eom_exif_util_set_label_text (GtkLabel * label, EomExifData * exif_data, gint tag_id)
Definition at line 199 of file eom-exif-util.c.
References eom_exif_data_get_value(), eom_exif_util_format_date(), eom_util_make_valid_utf8(), label, and NULL.