MATE Desktop Environment: eom-image-save-info.c File Reference
eom-image-save-info.c File Reference
#include <string.h>
#include "eom-image-save-info.h"
#include "eom-image-private.h"
#include "eom-pixbuf-util.h"
#include "eom-image.h"
Functions
EomImageSaveInfo * eom_image_save_info_new_from_image (EomImage *image)
EomImageSaveInfo * eom_image_save_info_new_from_uri (const char *txt_uri, GdkPixbufFormat *format)
EomImageSaveInfo * eom_image_save_info_new_from_file (GFile *file, GdkPixbufFormat *format)
Function Documentation
eom_image_save_info_new_from_file()
EomImageSaveInfo * eom_image_save_info_new_from_file (GFile * file, GdkPixbufFormat * format)
Definition at line 121 of file eom-image-save-info.c.
References EOM_TYPE_IMAGE_SAVE_INFO, _EomImageSaveInfo::exists, FALSE, _EomImageSaveInfo::file, _EomImageSaveInfo::format, _EomImageSaveInfo::has_metadata, _EomImageSaveInfo::jpeg_quality, _EomImageSaveInfo::local, _EomImageSaveInfo::modified, NULL, and _EomImageSaveInfo::overwrite.
Referenced by eom_image_save_info_new_from_uri().
eom_image_save_info_new_from_image()
EomImageSaveInfo * eom_image_save_info_new_from_image (EomImage * image)
Definition at line 82 of file eom-image-save-info.c.
References EOM_IMAGE_DATA_EXIF, eom_image_get_file(), eom_image_has_data(), eom_image_is_modified(), EOM_IS_IMAGE, EOM_TYPE_IMAGE_SAVE_INFO, _EomImageSaveInfo::exists, FALSE, _EomImageSaveInfo::file, _EomImagePrivate::file_type, _EomImageSaveInfo::format, _EomImageSaveInfo::has_metadata, _EomImageSaveInfo::jpeg_quality, _EomImageSaveInfo::local, _EomImageSaveInfo::modified, NULL, _EomImageSaveInfo::overwrite, and _EomImage::priv.
eom_image_save_info_new_from_uri()
EomImageSaveInfo * eom_image_save_info_new_from_uri (const char * txt_uri, GdkPixbufFormat * format)
Definition at line 104 of file eom-image-save-info.c.
References eom_image_save_info_new_from_file(), and NULL.