MATE Desktop Environment: eom-print.h File Reference
eom-print.h File Reference
#include "eom-image.h"
#include <gtk/gtk.h>
Functions
G_GNUC_INTERNAL GtkPrintOperation * eom_print_operation_new (EomImage *image, GtkPrintSettings *print_settings, GtkPageSetup *page_setup)
G_GNUC_INTERNAL GtkPageSetup * eom_print_get_page_setup (void)
G_GNUC_INTERNAL void eom_print_set_page_setup (GtkPageSetup *page_setup)
G_GNUC_INTERNAL GtkPrintSettings * eom_print_get_print_settings (void)
G_GNUC_INTERNAL void eom_print_set_print_settings (GtkPrintSettings *print_settings)
Function Documentation
eom_print_get_page_setup()
G_GNUC_INTERNAL GtkPageSetup * eom_print_get_page_setup (void)
Definition at line 411 of file eom-print.c.
References EOM_PAGE_SETUP_GROUP, error, and NULL.
eom_print_get_print_settings()
G_GNUC_INTERNAL GtkPrintSettings * eom_print_get_print_settings (void)
Definition at line 479 of file eom-print.c.
References EOM_PRINT_SETTINGS_GROUP, error, and NULL.
eom_print_operation_new()
G_GNUC_INTERNAL GtkPrintOperation * eom_print_operation_new (EomImage * image, GtkPrintSettings * print_settings, GtkPageSetup * page_setup)
Definition at line 314 of file eom-print.c.
References _, data, DEBUG_PRINTING, eom_debug(), eom_image_get_caption(), eom_image_get_size(), eom_print_image_setup_update(), NULL, and TRUE.
eom_print_set_page_setup()
G_GNUC_INTERNAL void eom_print_set_page_setup (GtkPageSetup * page_setup)
Definition at line 462 of file eom-print.c.
References EOM_PAGE_SETUP_GROUP, and NULL.
eom_print_set_print_settings()
G_GNUC_INTERNAL void eom_print_set_print_settings (GtkPrintSettings * print_settings)
Definition at line 507 of file eom-print.c.
References EOM_PRINT_SETTINGS_GROUP, and NULL.