MATE Desktop Environment: eom-application-internal.h File Reference
eom-application-internal.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libpeas/peas-extension-set.h>
#include "eom-application.h"
#include "eom-plugin-engine.h"
#include "egg-toolbars-model.h"
#include "eom-window.h"
Classes
struct _EomApplicationPrivate
Functions
EggToolbarsModel * eom_application_get_toolbars_model (EomApplication *application)
void eom_application_save_toolbars_model (EomApplication *application)
void eom_application_reset_toolbars_model (EomApplication *app)
Function Documentation
eom_application_get_toolbars_model()
EggToolbarsModel * eom_application_get_toolbars_model (EomApplication * application)
eom_application_get_toolbars_model: @application: An EomApplication.
Retrieves the EggToolbarsModel for the toolbar in EomApplication.
Returns: (transfer none): An EggToolbarsModel.
Definition at line 464 of file eom-application.c.
References EOM_IS_APPLICATION, NULL, _EomApplication::priv, and _EomApplicationPrivate::toolbars_model.
eom_application_reset_toolbars_model()
void eom_application_reset_toolbars_model (EomApplication * app)
eom_application_reset_toolbars_model: @app: an EomApplication
Restores the toolbars model to the defaults.
Definition at line 493 of file eom-application.c.
References EGG_TB_MODEL_NOT_REMOVABLE, egg_toolbars_model_load_names(), egg_toolbars_model_load_toolbars(), egg_toolbars_model_new(), egg_toolbars_model_set_flags(), EOM_IS_APPLICATION, _EomApplication::priv, and _EomApplicationPrivate::toolbars_model.
eom_application_save_toolbars_model()
void eom_application_save_toolbars_model (EomApplication * application)
eom_application_save_toolbars_model: @application: An EomApplication.
Causes the saving of the model of the toolbar in EomApplication to a file.
Definition at line 478 of file eom-application.c.
References egg_toolbars_model_save_toolbars(), NULL, _EomApplication::priv, _EomApplicationPrivate::toolbars_file, and _EomApplicationPrivate::toolbars_model.