MATE Desktop Environment: ephy-zoom-action.h File Reference
ephy-zoom-action.h File Reference
#include <gtk/gtk.h>
Classes
struct _EphyZoomAction
struct _EphyZoomActionClass
Macros
#define EPHY_TYPE_ZOOM_ACTION (ephy_zoom_action_get_type ())
#define EPHY_ZOOM_ACTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPHY_TYPE_ZOOM_ACTION, EphyZoomAction))
#define EPHY_ZOOM_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPHY_TYPE_ZOOM_ACTION, EphyZoomActionClass))
#define EPHY_IS_ZOOM_ACTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPHY_TYPE_ZOOM_ACTION))
#define EPHY_IS_ZOOM_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((obj), EPHY_TYPE_ZOOM_ACTION))
#define EPHY_ZOOM_ACTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), EPHY_TYPE_ZOOM_ACTION, EphyZoomActionClass))
Typedefs
typedef struct _EphyZoomAction EphyZoomAction
typedef struct _EphyZoomActionClass EphyZoomActionClass
typedef struct _EphyZoomActionPrivate EphyZoomActionPrivate
Functions
GType ephy_zoom_action_get_type (void)
void ephy_zoom_action_set_zoom_level (EphyZoomAction *action, float zoom)
float ephy_zoom_action_get_zoom_level (EphyZoomAction *action)
void ephy_zoom_action_set_min_zoom_level (EphyZoomAction *action, float zoom)
void ephy_zoom_action_set_max_zoom_level (EphyZoomAction *action, float zoom)
Macro Definition Documentation
EPHY_IS_ZOOM_ACTION
#define EPHY_IS_ZOOM_ACTION (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EPHY_TYPE_ZOOM_ACTION))
Definition at line 32 of file ephy-zoom-action.h.
EPHY_IS_ZOOM_ACTION_CLASS
#define EPHY_IS_ZOOM_ACTION_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((obj), EPHY_TYPE_ZOOM_ACTION))
Definition at line 33 of file ephy-zoom-action.h.
EPHY_TYPE_ZOOM_ACTION
#define EPHY_TYPE_ZOOM_ACTION (ephy_zoom_action_get_type ())
Definition at line 29 of file ephy-zoom-action.h.
EPHY_ZOOM_ACTION
#define EPHY_ZOOM_ACTION (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EPHY_TYPE_ZOOM_ACTION, EphyZoomAction))
Definition at line 30 of file ephy-zoom-action.h.
EPHY_ZOOM_ACTION_CLASS
#define EPHY_ZOOM_ACTION_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EPHY_TYPE_ZOOM_ACTION, EphyZoomActionClass))
Definition at line 31 of file ephy-zoom-action.h.
EPHY_ZOOM_ACTION_GET_CLASS
#define EPHY_ZOOM_ACTION_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS((obj), EPHY_TYPE_ZOOM_ACTION, EphyZoomActionClass))
Definition at line 34 of file ephy-zoom-action.h.
Typedef Documentation
EphyZoomAction
typedef struct _EphyZoomAction EphyZoomAction
Definition at line 36 of file ephy-zoom-action.h.
EphyZoomActionClass
typedef struct _EphyZoomActionClass EphyZoomActionClass
Definition at line 37 of file ephy-zoom-action.h.
EphyZoomActionPrivate
typedef struct _EphyZoomActionPrivate EphyZoomActionPrivate
Definition at line 38 of file ephy-zoom-action.h.
Function Documentation
ephy_zoom_action_get_type()
GType ephy_zoom_action_get_type (void)
ephy_zoom_action_get_zoom_level()
float ephy_zoom_action_get_zoom_level (EphyZoomAction * action)
Definition at line 300 of file ephy-zoom-action.c.
References action, and EPHY_IS_ZOOM_ACTION.
ephy_zoom_action_set_max_zoom_level()
void ephy_zoom_action_set_max_zoom_level (EphyZoomAction * action, float zoom)
Definition at line 323 of file ephy-zoom-action.c.
References action, EPHY_IS_ZOOM_ACTION, ephy_zoom_action_set_zoom_level(), and ZOOM_MAXIMAL.
ephy_zoom_action_set_min_zoom_level()
void ephy_zoom_action_set_min_zoom_level (EphyZoomAction * action, float zoom)
Definition at line 308 of file ephy-zoom-action.c.
References action, EPHY_IS_ZOOM_ACTION, ephy_zoom_action_set_zoom_level(), and ZOOM_MAXIMAL.
ephy_zoom_action_set_zoom_level()
void ephy_zoom_action_set_zoom_level (EphyZoomAction * action, float zoom)
Definition at line 289 of file ephy-zoom-action.c.
References action, EPHY_IS_ZOOM_ACTION, and ZOOM_MAXIMAL.
Referenced by ephy_zoom_action_set_max_zoom_level(), and ephy_zoom_action_set_min_zoom_level().