MATE Desktop Environment: errors.c File Reference
errors.c File Reference
#include <config.h>
#include "errors.h"
#include "display-private.h"
#include <errno.h>
#include <stdlib.h>
#include <gdk/gdk.h>
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
Functions
void meta_error_trap_push (MetaDisplay *display)
void meta_error_trap_pop (MetaDisplay *display, gboolean last_request_was_roundtrip)
int meta_error_trap_pop_with_return (MetaDisplay *display, gboolean last_request_was_roundtrip)
Function Documentation
meta_error_trap_pop()
void meta_error_trap_pop (MetaDisplay * display, gboolean last_request_was_roundtrip)
Definition at line 41 of file errors.c.
References meta_display_get_xdisplay().
Referenced by meta_core_lower_beneath_focus_window(), meta_display_open(), meta_display_screen_for_xwindow(), meta_display_set_grab_op_cursor(), meta_display_set_input_focus_window(), meta_display_update_active_window_hint(), meta_prop_set_utf8_string_hint(), meta_screen_get_mouse_window(), meta_screen_update_showing_desktop_hint(), meta_window_client_message(), meta_window_delete(), meta_window_destroy_frame(), meta_window_ensure_frame(), meta_window_free(), meta_window_kill(), meta_window_new(), meta_window_new_with_attrs(), meta_window_notify_focus(), meta_window_send_icccm_message(), meta_window_set_current_workspace_hint(), meta_window_set_gravity(), and meta_window_update_net_wm_type().
meta_error_trap_pop_with_return()
int meta_error_trap_pop_with_return (MetaDisplay * display, gboolean last_request_was_roundtrip)
Definition at line 48 of file errors.c.
References meta_display_get_xdisplay().
Referenced by meta_display_begin_grab_op(), meta_display_set_grab_op_cursor(), meta_screen_free(), meta_screen_new(), meta_window_client_message(), meta_window_new(), and meta_window_new_with_attrs().
meta_error_trap_push()
void meta_error_trap_push (MetaDisplay * display)
Definition at line 35 of file errors.c.
References meta_display_get_xdisplay().
Referenced by meta_core_lower_beneath_focus_window(), meta_display_begin_grab_op(), meta_display_open(), meta_display_screen_for_xwindow(), meta_display_set_grab_op_cursor(), meta_display_set_input_focus_window(), meta_display_update_active_window_hint(), meta_prop_set_utf8_string_hint(), meta_screen_free(), meta_screen_get_mouse_window(), meta_screen_new(), meta_screen_update_showing_desktop_hint(), meta_window_client_message(), meta_window_delete(), meta_window_destroy_frame(), meta_window_ensure_frame(), meta_window_free(), meta_window_kill(), meta_window_new(), meta_window_new_with_attrs(), meta_window_notify_focus(), meta_window_send_icccm_message(), meta_window_set_current_workspace_hint(), meta_window_set_gravity(), and meta_window_update_net_wm_type().