MATE Desktop Environment: ev-archive.h File Reference
ev-archive.h File Reference
#include <glib-object.h>
Macros
#define EV_TYPE_ARCHIVE ev_archive_get_type ()
Functions
G_DECLARE_FINAL_TYPE (...) typedef enum
EvArchive * ev_archive_new (void)
gboolean ev_archive_set_archive_type (EvArchive *archive, EvArchiveType archive_type)
EvArchiveType ev_archive_get_archive_type (EvArchive *archive)
gboolean ev_archive_open_filename (EvArchive *archive, const char *path, GError **error)
gboolean ev_archive_read_next_header (EvArchive *archive, GError **error)
gboolean ev_archive_at_entry (EvArchive *archive)
const char * ev_archive_get_entry_pathname (EvArchive *archive)
gint64 ev_archive_get_entry_size (EvArchive *archive)
gboolean ev_archive_get_entry_is_encrypted (EvArchive *archive)
gssize ev_archive_read_data (EvArchive *archive, void *buf, gsize count, GError **error)
void ev_archive_reset (EvArchive *archive)
Variables
EvArchiveType
Macro Definition Documentation
EV_TYPE_ARCHIVE
#define EV_TYPE_ARCHIVE ev_archive_get_type ()
Definition at line 26 of file ev-archive.h.
Function Documentation
ev_archive_at_entry()
gboolean ev_archive_at_entry (EvArchive * archive)
Definition at line 202 of file ev-archive.c.
References FALSE, and NULL.
ev_archive_get_archive_type()
EvArchiveType ev_archive_get_archive_type (EvArchive * archive)
Definition at line 94 of file ev-archive.c.
ev_archive_get_entry_is_encrypted()
gboolean ev_archive_get_entry_is_encrypted (EvArchive * archive)
Definition at line 251 of file ev-archive.c.
References FALSE, and NULL.
Referenced by main().
ev_archive_get_entry_pathname()
const char * ev_archive_get_entry_pathname (EvArchive * archive)
Definition at line 211 of file ev-archive.c.
References NULL.
Referenced by main().
ev_archive_get_entry_size()
gint64 ev_archive_get_entry_size (EvArchive * archive)
Definition at line 231 of file ev-archive.c.
References NULL.
Referenced by main().
ev_archive_new()
EvArchive * ev_archive_new (void)
Definition at line 68 of file ev-archive.c.
References EV_TYPE_ARCHIVE, and NULL.
Referenced by main().
ev_archive_open_filename()
gboolean ev_archive_open_filename (EvArchive * archive, const char * path, GError ** error)
Definition at line 123 of file ev-archive.c.
References BUFFER_SIZE, error, FALSE, NULL, and TRUE.
Referenced by main().
ev_archive_read_data()
gssize ev_archive_read_data (EvArchive * archive, void * buf, gsize count, GError ** error)
Definition at line 271 of file ev-archive.c.
References error, and NULL.
ev_archive_read_next_header()
gboolean ev_archive_read_next_header (EvArchive * archive, GError ** error)
Definition at line 182 of file ev-archive.c.
References error, and FALSE.
Referenced by main().
ev_archive_reset()
void ev_archive_reset (EvArchive * archive)
Definition at line 301 of file ev-archive.c.
References NULL.
Referenced by main().
ev_archive_set_archive_type()
gboolean ev_archive_set_archive_type (EvArchive * archive, EvArchiveType archive_type)
Definition at line 102 of file ev-archive.c.
References FALSE, and TRUE.
Referenced by main().
G_DECLARE_FINAL_TYPE()
G_DECLARE_FINAL_TYPE (...)
mate_calc_application_new:
Creates a new MateCalcApplication instance.
Returns: (transfer full): A new MateCalcApplication
Definition at line 27 of file ev-archive.h.
Variable Documentation
EvArchiveType
EvArchiveType
Definition at line 35 of file ev-archive.h.
Referenced by main().