MATE Desktop Environment: ev-attachment.h File Reference
ev-attachment.h File Reference
#include <glib-object.h>
#include <gio/gio.h>
Classes
struct _EvAttachment
struct _EvAttachmentClass
Macros
#define EV_TYPE_ATTACHMENT (ev_attachment_get_type())
#define EV_ATTACHMENT(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_ATTACHMENT, EvAttachment))
#define EV_ATTACHMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_ATTACHMENT, EvAttachmentClass))
#define EV_IS_ATTACHMENT(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_ATTACHMENT))
#define EV_IS_ATTACHMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_ATTACHMENT))
#define EV_ATTACHMENT_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_ATTACHMENT, EvAttachmentClass))
#define EV_ATTACHMENT_ERROR (ev_attachment_error_quark ())
Typedefs
typedef struct _EvAttachment EvAttachment
typedef struct _EvAttachmentClass EvAttachmentClass
typedef struct _EvAttachmentPrivate EvAttachmentPrivate
Functions
GType ev_attachment_get_type (void)
GQuark ev_attachment_error_quark (void)
EvAttachment * ev_attachment_new (const gchar *name, const gchar *description, gint64 mtime, gint64 ctime, gsize size, gpointer data)
const gchar * ev_attachment_get_name (EvAttachment *attachment)
const gchar * ev_attachment_get_description (EvAttachment *attachment)
gint64 ev_attachment_get_modification_date (EvAttachment *attachment)
gint64 ev_attachment_get_creation_date (EvAttachment *attachment)
const gchar * ev_attachment_get_mime_type (EvAttachment *attachment)
gboolean ev_attachment_save (EvAttachment *attachment, GFile *file, GError **error)
gboolean ev_attachment_open (EvAttachment *attachment, GdkScreen *screen, guint32 timestamp, GError **error)
Macro Definition Documentation
EV_ATTACHMENT
#define EV_ATTACHMENT (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_ATTACHMENT, EvAttachment))
Definition at line 37 of file ev-attachment.h.
EV_ATTACHMENT_CLASS
#define EV_ATTACHMENT_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_ATTACHMENT, EvAttachmentClass))
Definition at line 38 of file ev-attachment.h.
EV_ATTACHMENT_ERROR
#define EV_ATTACHMENT_ERROR (ev_attachment_error_quark ())
Definition at line 43 of file ev-attachment.h.
EV_ATTACHMENT_GET_CLASS
#define EV_ATTACHMENT_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_ATTACHMENT, EvAttachmentClass))
Definition at line 41 of file ev-attachment.h.
EV_IS_ATTACHMENT
#define EV_IS_ATTACHMENT (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_ATTACHMENT))
Definition at line 39 of file ev-attachment.h.
EV_IS_ATTACHMENT_CLASS
#define EV_IS_ATTACHMENT_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_ATTACHMENT))
Definition at line 40 of file ev-attachment.h.
EV_TYPE_ATTACHMENT
#define EV_TYPE_ATTACHMENT (ev_attachment_get_type())
Definition at line 36 of file ev-attachment.h.
Typedef Documentation
EvAttachment
typedef struct _EvAttachment EvAttachment
Definition at line 32 of file ev-attachment.h.
EvAttachmentClass
typedef struct _EvAttachmentClass EvAttachmentClass
Definition at line 33 of file ev-attachment.h.
EvAttachmentPrivate
typedef struct _EvAttachmentPrivate EvAttachmentPrivate
Definition at line 34 of file ev-attachment.h.
Function Documentation
ev_attachment_error_quark()
GQuark ev_attachment_error_quark (void)
Definition at line 54 of file ev-attachment.c.
ev_attachment_get_creation_date()
gint64 ev_attachment_get_creation_date (EvAttachment * attachment)
Definition at line 264 of file ev-attachment.c.
References EV_IS_ATTACHMENT, and _EvAttachment::priv.
ev_attachment_get_description()
const gchar * ev_attachment_get_description (EvAttachment * attachment)
Definition at line 248 of file ev-attachment.c.
References EV_IS_ATTACHMENT, NULL, and _EvAttachment::priv.
ev_attachment_get_mime_type()
const gchar * ev_attachment_get_mime_type (EvAttachment * attachment)
Definition at line 272 of file ev-attachment.c.
References EV_IS_ATTACHMENT, NULL, and _EvAttachment::priv.
ev_attachment_get_modification_date()
gint64 ev_attachment_get_modification_date (EvAttachment * attachment)
Definition at line 256 of file ev-attachment.c.
References EV_IS_ATTACHMENT, and _EvAttachment::priv.
ev_attachment_get_name()
const gchar * ev_attachment_get_name (EvAttachment * attachment)
Definition at line 240 of file ev-attachment.c.
References EV_IS_ATTACHMENT, NULL, and _EvAttachment::priv.
Referenced by ev_attachment_open().
ev_attachment_get_type()
GType ev_attachment_get_type (void)
ev_attachment_new()
EvAttachment * ev_attachment_new (const gchar * name, const gchar * description, gint64 mtime, gint64 ctime, gsize size, gpointer data)
Definition at line 218 of file ev-attachment.c.
References data, EV_TYPE_ATTACHMENT, name, and NULL.
ev_attachment_open()
gboolean ev_attachment_open (EvAttachment * attachment, GdkScreen * screen, guint32 timestamp, GError ** error)
Definition at line 384 of file ev-attachment.c.
References _, error, EV_ATTACHMENT_ERROR, ev_attachment_get_name(), ev_attachment_save(), EV_IS_ATTACHMENT, ev_mkstemp_file(), FALSE, NULL, and _EvAttachment::priv.
ev_attachment_save()
gboolean ev_attachment_save (EvAttachment * attachment, GFile * file, GError ** error)
Definition at line 280 of file ev-attachment.c.
References _, error, EV_ATTACHMENT_ERROR, EV_IS_ATTACHMENT, FALSE, NULL, _EvAttachment::priv, and TRUE.
Referenced by ev_attachment_open().