MATE Desktop Environment: ev-annotation.h File Reference
ev-annotation.h File Reference
#include <glib-object.h>
#include <gdk/gdk.h>
#include "ev-document.h"
#include "ev-attachment.h"
#include "ev-macros.h"
Macros
#define EV_TYPE_ANNOTATION (ev_annotation_get_type())
#define EV_ANNOTATION(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_ANNOTATION, EvAnnotation))
#define EV_ANNOTATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_ANNOTATION, EvAnnotationClass))
#define EV_IS_ANNOTATION(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_ANNOTATION))
#define EV_IS_ANNOTATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_ANNOTATION))
#define EV_ANNOTATION_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_ANNOTATION, EvAnnotationClass))
#define EV_TYPE_ANNOTATION_MARKUP (ev_annotation_markup_get_type ())
#define EV_ANNOTATION_MARKUP(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), EV_TYPE_ANNOTATION_MARKUP, EvAnnotationMarkup))
#define EV_ANNOTATION_MARKUP_IFACE(k) (G_TYPE_CHECK_CLASS_CAST((k), EV_TYPE_ANNOTATION_MARKUP, EvAnnotationMarkupInterface))
#define EV_IS_ANNOTATION_MARKUP(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), EV_TYPE_ANNOTATION_MARKUP))
#define EV_IS_ANNOTATION_MARKUP_IFACE(k) (G_TYPE_CHECK_CLASS_TYPE ((k), EV_TYPE_ANNOTATION_MARKUP))
#define EV_ANNOTATION_MARKUP_GET_IFACE(inst) (G_TYPE_INSTANCE_GET_INTERFACE ((inst), EV_TYPE_ANNOTATION_MARKUP, EvAnnotationMarkupInterface))
#define EV_TYPE_ANNOTATION_TEXT (ev_annotation_text_get_type())
#define EV_ANNOTATION_TEXT(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_ANNOTATION_TEXT, EvAnnotationText))
#define EV_ANNOTATION_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_ANNOTATION_TEXT, EvAnnotationTextClass))
#define EV_IS_ANNOTATION_TEXT(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_ANNOTATION_TEXT))
#define EV_IS_ANNOTATION_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_ANNOTATION_TEXT))
#define EV_ANNOTATION_TEXT_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_ANNOTATION_TEXT, EvAnnotationTextClass))
#define EV_TYPE_ANNOTATION_ATTACHMENT (ev_annotation_attachment_get_type())
#define EV_ANNOTATION_ATTACHMENT(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_ANNOTATION_ATTACHMENT, EvAnnotationAttachment))
#define EV_ANNOTATION_ATTACHMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_ANNOTATION_ATTACHMENT, EvAnnotationAttachmentClass))
#define EV_IS_ANNOTATION_ATTACHMENT(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_ANNOTATION_ATTACHMENT))
#define EV_IS_ANNOTATION_ATTACHMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_ANNOTATION_ATTACHMENT))
#define EV_ANNOTATION_ATTACHMENT_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_ANNOTATION_ATTACHMENT, EvAnnotationAttachmentClass))
Typedefs
typedef struct _EvAnnotation EvAnnotation
typedef struct _EvAnnotationClass EvAnnotationClass
typedef struct _EvAnnotationMarkup EvAnnotationMarkup
typedef struct _EvAnnotationMarkupInterface EvAnnotationMarkupInterface
typedef struct _EvAnnotationText EvAnnotationText
typedef struct _EvAnnotationTextClass EvAnnotationTextClass
typedef struct _EvAnnotationAttachment EvAnnotationAttachment
typedef struct _EvAnnotationAttachmentClass EvAnnotationAttachmentClass
Enumerations
enum EvAnnotationType { EV_ANNOTATION_TYPE_UNKNOWN , EV_ANNOTATION_TYPE_TEXT , EV_ANNOTATION_TYPE_ATTACHMENT }
enum EvAnnotationTextIcon {
EV_ANNOTATION_TEXT_ICON_NOTE , EV_ANNOTATION_TEXT_ICON_COMMENT , EV_ANNOTATION_TEXT_ICON_KEY , EV_ANNOTATION_TEXT_ICON_HELP ,
EV_ANNOTATION_TEXT_ICON_NEW_PARAGRAPH , EV_ANNOTATION_TEXT_ICON_PARAGRAPH , EV_ANNOTATION_TEXT_ICON_INSERT , EV_ANNOTATION_TEXT_ICON_CROSS ,
EV_ANNOTATION_TEXT_ICON_CIRCLE , EV_ANNOTATION_TEXT_ICON_UNKNOWN
}
Functions
GType ev_annotation_get_type (void)
EvAnnotationType ev_annotation_get_annotation_type (EvAnnotation *annot)
EvPage * ev_annotation_get_page (EvAnnotation *annot)
guint ev_annotation_get_page_index (EvAnnotation *annot)
gboolean ev_annotation_equal (EvAnnotation *annot, EvAnnotation *other)
const gchar * ev_annotation_get_contents (EvAnnotation *annot)
gboolean ev_annotation_set_contents (EvAnnotation *annot, const gchar *contents)
const gchar * ev_annotation_get_name (EvAnnotation *annot)
gboolean ev_annotation_set_name (EvAnnotation *annot, const gchar *name)
const gchar * ev_annotation_get_modified (EvAnnotation *annot)
gboolean ev_annotation_set_modified (EvAnnotation *annot, const gchar *modified)
gboolean ev_annotation_set_modified_from_time (EvAnnotation *annot, gint64 utime)
void ev_annotation_get_color (EvAnnotation *annot, GdkColor *color)
gboolean ev_annotation_set_color (EvAnnotation *annot, const GdkColor *color)
void ev_annotation_get_rgba (EvAnnotation *annot, GdkRGBA *rgba)
gboolean ev_annotation_set_rgba (EvAnnotation *annot, const GdkRGBA *rgba)
GType ev_annotation_markup_get_type (void)
const gchar * ev_annotation_markup_get_label (EvAnnotationMarkup *markup)
gboolean ev_annotation_markup_set_label (EvAnnotationMarkup *markup, const gchar *label)
gdouble ev_annotation_markup_get_opacity (EvAnnotationMarkup *markup)
gboolean ev_annotation_markup_set_opacity (EvAnnotationMarkup *markup, gdouble opacity)
gboolean ev_annotation_markup_has_popup (EvAnnotationMarkup *markup)
gboolean ev_annotation_markup_set_has_popup (EvAnnotationMarkup *markup, gboolean has_popup)
void ev_annotation_markup_get_rectangle (EvAnnotationMarkup *markup, EvRectangle *ev_rect)
gboolean ev_annotation_markup_set_rectangle (EvAnnotationMarkup *markup, const EvRectangle *ev_rect)
gboolean ev_annotation_markup_get_popup_is_open (EvAnnotationMarkup *markup)
gboolean ev_annotation_markup_set_popup_is_open (EvAnnotationMarkup *markup, gboolean is_open)
GType ev_annotation_text_get_type (void)
EvAnnotation * ev_annotation_text_new (EvPage *page)
EvAnnotationTextIcon ev_annotation_text_get_icon (EvAnnotationText *text)
gboolean ev_annotation_text_set_icon (EvAnnotationText *text, EvAnnotationTextIcon icon)
gboolean ev_annotation_text_get_is_open (EvAnnotationText *text)
gboolean ev_annotation_text_set_is_open (EvAnnotationText *text, gboolean is_open)
GType ev_annotation_attachment_get_type (void)
EvAnnotation * ev_annotation_attachment_new (EvPage *page, EvAttachment *attachment)
EvAttachment * ev_annotation_attachment_get_attachment (EvAnnotationAttachment *annot)
gboolean ev_annotation_attachment_set_attachment (EvAnnotationAttachment *annot, EvAttachment *attachment)
Macro Definition Documentation
EV_ANNOTATION
#define EV_ANNOTATION (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_ANNOTATION, EvAnnotation))
Definition at line 40 of file ev-annotation.h.
EV_ANNOTATION_ATTACHMENT
#define EV_ANNOTATION_ATTACHMENT (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_ANNOTATION_ATTACHMENT, EvAnnotationAttachment))
Definition at line 64 of file ev-annotation.h.
EV_ANNOTATION_ATTACHMENT_CLASS
#define EV_ANNOTATION_ATTACHMENT_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_ANNOTATION_ATTACHMENT, EvAnnotationAttachmentClass))
Definition at line 65 of file ev-annotation.h.
EV_ANNOTATION_ATTACHMENT_GET_CLASS
#define EV_ANNOTATION_ATTACHMENT_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_ANNOTATION_ATTACHMENT, EvAnnotationAttachmentClass))
Definition at line 68 of file ev-annotation.h.
EV_ANNOTATION_CLASS
#define EV_ANNOTATION_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_ANNOTATION, EvAnnotationClass))
Definition at line 41 of file ev-annotation.h.
EV_ANNOTATION_GET_CLASS
#define EV_ANNOTATION_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_ANNOTATION, EvAnnotationClass))
Definition at line 44 of file ev-annotation.h.
EV_ANNOTATION_MARKUP
#define EV_ANNOTATION_MARKUP (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), EV_TYPE_ANNOTATION_MARKUP, EvAnnotationMarkup))
Definition at line 48 of file ev-annotation.h.
EV_ANNOTATION_MARKUP_GET_IFACE
#define EV_ANNOTATION_MARKUP_GET_IFACE (inst) (G_TYPE_INSTANCE_GET_INTERFACE ((inst), EV_TYPE_ANNOTATION_MARKUP, EvAnnotationMarkupInterface))
Definition at line 52 of file ev-annotation.h.
EV_ANNOTATION_MARKUP_IFACE
#define EV_ANNOTATION_MARKUP_IFACE (k) (G_TYPE_CHECK_CLASS_CAST((k), EV_TYPE_ANNOTATION_MARKUP, EvAnnotationMarkupInterface))
Definition at line 49 of file ev-annotation.h.
EV_ANNOTATION_TEXT
#define EV_ANNOTATION_TEXT (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_ANNOTATION_TEXT, EvAnnotationText))
Definition at line 56 of file ev-annotation.h.
EV_ANNOTATION_TEXT_CLASS
#define EV_ANNOTATION_TEXT_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_ANNOTATION_TEXT, EvAnnotationTextClass))
Definition at line 57 of file ev-annotation.h.
EV_ANNOTATION_TEXT_GET_CLASS
#define EV_ANNOTATION_TEXT_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_ANNOTATION_TEXT, EvAnnotationTextClass))
Definition at line 60 of file ev-annotation.h.
EV_IS_ANNOTATION
#define EV_IS_ANNOTATION (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_ANNOTATION))
Definition at line 42 of file ev-annotation.h.
EV_IS_ANNOTATION_ATTACHMENT
#define EV_IS_ANNOTATION_ATTACHMENT (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_ANNOTATION_ATTACHMENT))
Definition at line 66 of file ev-annotation.h.
EV_IS_ANNOTATION_ATTACHMENT_CLASS
#define EV_IS_ANNOTATION_ATTACHMENT_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_ANNOTATION_ATTACHMENT))
Definition at line 67 of file ev-annotation.h.
EV_IS_ANNOTATION_CLASS
#define EV_IS_ANNOTATION_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_ANNOTATION))
Definition at line 43 of file ev-annotation.h.
EV_IS_ANNOTATION_MARKUP
#define EV_IS_ANNOTATION_MARKUP (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), EV_TYPE_ANNOTATION_MARKUP))
Definition at line 50 of file ev-annotation.h.
EV_IS_ANNOTATION_MARKUP_IFACE
#define EV_IS_ANNOTATION_MARKUP_IFACE (k) (G_TYPE_CHECK_CLASS_TYPE ((k), EV_TYPE_ANNOTATION_MARKUP))
Definition at line 51 of file ev-annotation.h.
EV_IS_ANNOTATION_TEXT
#define EV_IS_ANNOTATION_TEXT (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_ANNOTATION_TEXT))
Definition at line 58 of file ev-annotation.h.
EV_IS_ANNOTATION_TEXT_CLASS
#define EV_IS_ANNOTATION_TEXT_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_ANNOTATION_TEXT))
Definition at line 59 of file ev-annotation.h.
EV_TYPE_ANNOTATION
#define EV_TYPE_ANNOTATION (ev_annotation_get_type())
Definition at line 39 of file ev-annotation.h.
EV_TYPE_ANNOTATION_ATTACHMENT
#define EV_TYPE_ANNOTATION_ATTACHMENT (ev_annotation_attachment_get_type())
Definition at line 63 of file ev-annotation.h.
EV_TYPE_ANNOTATION_MARKUP
#define EV_TYPE_ANNOTATION_MARKUP (ev_annotation_markup_get_type ())
Definition at line 47 of file ev-annotation.h.
EV_TYPE_ANNOTATION_TEXT
#define EV_TYPE_ANNOTATION_TEXT (ev_annotation_text_get_type())
Definition at line 55 of file ev-annotation.h.
Typedef Documentation
EvAnnotation
typedef struct _EvAnnotation EvAnnotation
Definition at line 70 of file ev-annotation.h.
EvAnnotationAttachment
typedef struct _EvAnnotationAttachment EvAnnotationAttachment
Definition at line 79 of file ev-annotation.h.
EvAnnotationAttachmentClass
typedef struct _EvAnnotationAttachmentClass EvAnnotationAttachmentClass
Definition at line 80 of file ev-annotation.h.
EvAnnotationClass
typedef struct _EvAnnotationClass EvAnnotationClass
Definition at line 71 of file ev-annotation.h.
EvAnnotationMarkup
typedef struct _EvAnnotationMarkup EvAnnotationMarkup
Definition at line 73 of file ev-annotation.h.
EvAnnotationMarkupInterface
typedef struct _EvAnnotationMarkupInterface EvAnnotationMarkupInterface
Definition at line 74 of file ev-annotation.h.
EvAnnotationText
typedef struct _EvAnnotationText EvAnnotationText
Definition at line 76 of file ev-annotation.h.
EvAnnotationTextClass
typedef struct _EvAnnotationTextClass EvAnnotationTextClass
Definition at line 77 of file ev-annotation.h.
Enumeration Type Documentation
EvAnnotationTextIcon
enum EvAnnotationTextIcon
Enumerator
EV_ANNOTATION_TEXT_ICON_NOTE
EV_ANNOTATION_TEXT_ICON_COMMENT
EV_ANNOTATION_TEXT_ICON_KEY
EV_ANNOTATION_TEXT_ICON_HELP
EV_ANNOTATION_TEXT_ICON_NEW_PARAGRAPH
EV_ANNOTATION_TEXT_ICON_PARAGRAPH
EV_ANNOTATION_TEXT_ICON_INSERT
EV_ANNOTATION_TEXT_ICON_CROSS
EV_ANNOTATION_TEXT_ICON_CIRCLE
EV_ANNOTATION_TEXT_ICON_UNKNOWN
Definition at line 88 of file ev-annotation.h.
EvAnnotationType
enum EvAnnotationType
Enumerator
EV_ANNOTATION_TYPE_UNKNOWN
EV_ANNOTATION_TYPE_TEXT
EV_ANNOTATION_TYPE_ATTACHMENT
Definition at line 82 of file ev-annotation.h.
Function Documentation
ev_annotation_attachment_get_attachment()
EvAttachment * ev_annotation_attachment_get_attachment (EvAnnotationAttachment * annot)
ev_annotation_attachment_get_attachment: @annot: an EvAnnotationAttachment
Returns: (transfer none): an EvAttachment
Definition at line 1197 of file ev-annotation.c.
References EV_IS_ANNOTATION_ATTACHMENT, and NULL.
ev_annotation_attachment_get_type()
GType ev_annotation_attachment_get_type (void)
ev_annotation_attachment_new()
EvAnnotation * ev_annotation_attachment_new (EvPage * page, EvAttachment * attachment)
Definition at line 1179 of file ev-annotation.c.
References EV_ANNOTATION, EV_IS_ATTACHMENT, EV_TYPE_ANNOTATION_ATTACHMENT, and NULL.
ev_annotation_attachment_set_attachment()
gboolean ev_annotation_attachment_set_attachment (EvAnnotationAttachment * annot, EvAttachment * attachment)
Definition at line 1205 of file ev-annotation.c.
References EV_IS_ANNOTATION_ATTACHMENT, FALSE, NULL, and TRUE.
ev_annotation_equal()
gboolean ev_annotation_equal (EvAnnotation * annot, EvAnnotation * other)
ev_annotation_equal: @annot: an EvAnnotation @other: another EvAnnotation
Compare @annot and @other.
Returns: TRUE if @annot is equal to @other, FALSE otherwise
Definition at line 333 of file ev-annotation.c.
References EV_IS_ANNOTATION, and FALSE.
ev_annotation_get_annotation_type()
EvAnnotationType ev_annotation_get_annotation_type (EvAnnotation * annot)
Definition at line 283 of file ev-annotation.c.
References EV_IS_ANNOTATION.
Referenced by ev_annotation_properties_dialog_new_with_annotation().
ev_annotation_get_color()
void ev_annotation_get_color (EvAnnotation * annot, GdkColor * color)
ev_annotation_get_color: @annot: an EvAnnotation @color: (out): a #GdkColor to be filled with the Annotation color.
Get the color of @annot.
Deprecated: 1.2.1: Use ev_annotation_get_rgba() instead.
Definition at line 528 of file ev-annotation.c.
References ev_annotation_get_rgba(), EV_IS_ANNOTATION, and NULL.
Referenced by ev_annotation_set_color().
ev_annotation_get_contents()
const gchar * ev_annotation_get_contents (EvAnnotation * annot)
ev_annotation_get_contents: @annot: an EvAnnotation
Get the contents of @annot. The contents of @annot is the text that is displayed in the annotation, or an alternate description of the annotation's content for non-text annotations
Returns: a string with the contents of the annotation or NULL if @annot has no contents.
Definition at line 354 of file ev-annotation.c.
References EV_IS_ANNOTATION, and NULL.
ev_annotation_get_modified()
const gchar * ev_annotation_get_modified (EvAnnotation * annot)
ev_annotation_get_modified: @annot: an EvAnnotation
Get the last modification date of @annot.
Returns: A string containing the last modification date.
Definition at line 444 of file ev-annotation.c.
References EV_IS_ANNOTATION, and NULL.
ev_annotation_get_name()
const gchar * ev_annotation_get_name (EvAnnotation * annot)
ev_annotation_get_name: @annot: an EvAnnotation
Get the name of @annot. The name of the annotation is a string that uniquely indenftifies @annot amongs all the annotations in the same page.
Returns: the string with the annotation's name.
Definition at line 400 of file ev-annotation.c.
References EV_IS_ANNOTATION, and NULL.
ev_annotation_get_page()
EvPage * ev_annotation_get_page (EvAnnotation * annot)
ev_annotation_get_page: @annot: an EvAnnotation
Get the page where @annot appears.
Returns: (transfer none): the EvPage where @annot appears
Definition at line 299 of file ev-annotation.c.
References EV_IS_ANNOTATION, and NULL.
ev_annotation_get_page_index()
guint ev_annotation_get_page_index (EvAnnotation * annot)
ev_annotation_get_page_index: @annot: an EvAnnotation
Get the index of the page where @annot appears. Note that the index is 0 based.
Returns: the page index.
Definition at line 316 of file ev-annotation.c.
References EV_IS_ANNOTATION.
Referenced by ev_view_focus_annotation(), and ev_view_remove_annotation().
ev_annotation_get_rgba()
void ev_annotation_get_rgba (EvAnnotation * annot, GdkRGBA * rgba)
ev_annotation_get_rgba: @annot: an EvAnnotation @rgba: (out): a #GdkRGBA to be filled with the annotation color
Gets the color of @annot.
Since: 1.2.1
Definition at line 593 of file ev-annotation.c.
References EV_IS_ANNOTATION, and NULL.
Referenced by ev_annotation_get_color(), and ev_annotation_properties_dialog_new_with_annotation().
ev_annotation_get_type()
GType ev_annotation_get_type (void)
ev_annotation_markup_get_label()
const gchar * ev_annotation_markup_get_label (EvAnnotationMarkup * markup)
Definition at line 785 of file ev-annotation.c.
References EV_IS_ANNOTATION_MARKUP, and NULL.
Referenced by ev_annotation_properties_dialog_new_with_annotation().
ev_annotation_markup_get_opacity()
gdouble ev_annotation_markup_get_opacity (EvAnnotationMarkup * markup)
Definition at line 818 of file ev-annotation.c.
References EV_IS_ANNOTATION_MARKUP.
Referenced by ev_annotation_properties_dialog_new_with_annotation().
ev_annotation_markup_get_popup_is_open()
gboolean ev_annotation_markup_get_popup_is_open (EvAnnotationMarkup * markup)
Definition at line 914 of file ev-annotation.c.
References EV_IS_ANNOTATION_MARKUP, and FALSE.
Referenced by ev_annotation_properties_dialog_new_with_annotation().
ev_annotation_markup_get_rectangle()
void ev_annotation_markup_get_rectangle (EvAnnotationMarkup * markup, EvRectangle * ev_rect)
Definition at line 878 of file ev-annotation.c.
References EV_IS_ANNOTATION_MARKUP, and NULL.
ev_annotation_markup_get_type()
GType ev_annotation_markup_get_type (void)
ev_annotation_markup_has_popup()
gboolean ev_annotation_markup_has_popup (EvAnnotationMarkup * markup)
Definition at line 848 of file ev-annotation.c.
References EV_IS_ANNOTATION_MARKUP, and FALSE.
ev_annotation_markup_set_has_popup()
gboolean ev_annotation_markup_set_has_popup (EvAnnotationMarkup * markup, gboolean has_popup)
Definition at line 859 of file ev-annotation.c.
References EV_IS_ANNOTATION_MARKUP, FALSE, and TRUE.
ev_annotation_markup_set_label()
gboolean ev_annotation_markup_set_label (EvAnnotationMarkup * markup, const gchar * label)
Definition at line 796 of file ev-annotation.c.
References EV_IS_ANNOTATION_MARKUP, FALSE, label, NULL, and TRUE.
ev_annotation_markup_set_opacity()
gboolean ev_annotation_markup_set_opacity (EvAnnotationMarkup * markup, gdouble opacity)
Definition at line 829 of file ev-annotation.c.
References EV_IS_ANNOTATION_MARKUP, FALSE, and TRUE.
ev_annotation_markup_set_popup_is_open()
gboolean ev_annotation_markup_set_popup_is_open (EvAnnotationMarkup * markup, gboolean is_open)
Definition at line 925 of file ev-annotation.c.
References EV_IS_ANNOTATION_MARKUP, FALSE, and TRUE.
ev_annotation_markup_set_rectangle()
gboolean ev_annotation_markup_set_rectangle (EvAnnotationMarkup * markup, const EvRectangle * ev_rect)
Definition at line 891 of file ev-annotation.c.
References EV_IS_ANNOTATION_MARKUP, FALSE, NULL, TRUE, _EvRectangle::x1, _EvRectangle::x2, _EvRectangle::y1, and _EvRectangle::y2.
ev_annotation_set_color()
gboolean ev_annotation_set_color (EvAnnotation * annot, const GdkColor * color)
ev_annotation_set_color: @annot: an #Evannotation @color: a #GdkColor
Set the color of the annotation to @color. You can monitor changes to the annotation's color by connecting to notify::color signal on @annot.
Returns: TRUE when the color has been changed, FALSE otherwise.
Deprecated: 1.2.1: Use ev_annotation_set_rgba() instead.
Definition at line 558 of file ev-annotation.c.
References ev_annotation_get_color(), ev_annotation_set_rgba(), EV_IS_ANNOTATION, FALSE, NULL, and TRUE.
ev_annotation_set_contents()
gboolean ev_annotation_set_contents (EvAnnotation * annot, const gchar * contents)
ev_annotation_set_contents: @annot: an EvAnnotation
Set the contents of @annot. You can monitor changes in the annotation's contents by connecting to notify::contents signal of @annot.
Returns: TRUE if the contents have been changed, FALSE otherwise.
Definition at line 372 of file ev-annotation.c.
References EV_IS_ANNOTATION, FALSE, NULL, and TRUE.
ev_annotation_set_modified()
gboolean ev_annotation_set_modified (EvAnnotation * annot, const gchar * modified)
ev_annotation_set_modified: @annot: an EvAnnotation @modified: string with the last modification date.
Set the last modification date of @annot to @modified. To set the last modification date using a #gint64, use ev_annotation_set_modified_from_time() instead. You can monitor changes to the last modification date by connecting to the notify::modified signal on @annot.
Returns: TRUE if the last modification date has been updated, FALSE otherwise.
Definition at line 465 of file ev-annotation.c.
References EV_IS_ANNOTATION, FALSE, NULL, and TRUE.
ev_annotation_set_modified_from_time()
gboolean ev_annotation_set_modified_from_time (EvAnnotation * annot, gint64 utime)
ev_annotation_set_modified_from_time: @annot: an EvAnnotation @utime: a #gint64
Set the last modification date of @annot to @utime. You can monitor changes to the last modification date by connectin to the notify::modified sinal on @annot. For the time-format used, see ev_document_misc_format_date().
Returns: TRUE if the last modified date has been updated, FALSE otherwise.
Definition at line 495 of file ev-annotation.c.
References ev_document_misc_format_date(), EV_IS_ANNOTATION, FALSE, and TRUE.
ev_annotation_set_name()
gboolean ev_annotation_set_name (EvAnnotation * annot, const gchar * name)
ev_annotation_set_name: @annot: an EvAnnotation
Set the name of @annot. You can monitor changes of the annotation name by connecting to the notify::name signal on @annot.
Returns: TRUE when the name has been changed, FALSE otherwise.
Definition at line 418 of file ev-annotation.c.
References EV_IS_ANNOTATION, FALSE, name, NULL, and TRUE.
ev_annotation_set_rgba()
gboolean ev_annotation_set_rgba (EvAnnotation * annot, const GdkRGBA * rgba)
ev_annotation_set_rgba: @annot: an #Evannotation @rgba: a #GdkRGBA
Set the color of the annotation to @rgba.
Returns: TRUE if the color has been changed, FALSE otherwise
Since: 1.2.1
Definition at line 614 of file ev-annotation.c.
References EV_IS_ANNOTATION, FALSE, NULL, and TRUE.
Referenced by ev_annotation_set_color().
ev_annotation_text_get_icon()
EvAnnotationTextIcon ev_annotation_text_get_icon (EvAnnotationText * text)
Definition at line 1041 of file ev-annotation.c.
References EV_IS_ANNOTATION_TEXT.
Referenced by ev_annotation_properties_dialog_new_with_annotation().
ev_annotation_text_get_is_open()
gboolean ev_annotation_text_get_is_open (EvAnnotationText * text)
Definition at line 1065 of file ev-annotation.c.
References EV_IS_ANNOTATION_TEXT, and FALSE.
ev_annotation_text_get_type()
GType ev_annotation_text_get_type (void)
ev_annotation_text_new()
EvAnnotation * ev_annotation_text_new (EvPage * page)
Definition at line 1033 of file ev-annotation.c.
References EV_ANNOTATION, EV_TYPE_ANNOTATION_TEXT, and NULL.
ev_annotation_text_set_icon()
gboolean ev_annotation_text_set_icon (EvAnnotationText * text, EvAnnotationTextIcon icon)
Definition at line 1049 of file ev-annotation.c.
References EV_IS_ANNOTATION_TEXT, FALSE, and TRUE.
ev_annotation_text_set_is_open()
gboolean ev_annotation_text_set_is_open (EvAnnotationText * text, gboolean is_open)
Definition at line 1073 of file ev-annotation.c.
References EV_IS_ANNOTATION_TEXT, FALSE, and TRUE.