MATE Desktop Environment: ev-document-misc.h File Reference
ev-document-misc.h File Reference
#include <cairo.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gtk/gtk.h>
#include "ev-macros.h"
Functions
GdkPixbuf * ev_document_misc_get_thumbnail_frame (int width, int height, GdkPixbuf *source_pixbuf)
GdkPixbuf * ev_document_misc_get_loading_thumbnail (int width, int height, gboolean inverted_colors)
EV_DEPRECATED void ev_document_misc_get_page_border_size (gint page_width, gint page_height, GtkBorder *border)
EV_DEPRECATED void ev_document_misc_paint_one_page (cairo_t *cr, GtkWidget *widget, GdkRectangle *area, GtkBorder *border, gboolean highlight, gboolean inverted_colors)
cairo_surface_t * ev_document_misc_surface_from_pixbuf (GdkPixbuf *pixbuf)
GdkPixbuf * ev_document_misc_pixbuf_from_surface (cairo_surface_t *surface)
cairo_surface_t * ev_document_misc_surface_rotate_and_scale (cairo_surface_t *surface, gint dest_width, gint dest_height, gint dest_rotation)
void ev_document_misc_invert_surface (cairo_surface_t *surface)
void ev_document_misc_invert_pixbuf (GdkPixbuf *pixbuf)
gdouble ev_document_misc_get_monitor_dpi (GdkMonitor *monitor)
gchar * ev_document_misc_format_date (gint64 utime)
void ev_document_misc_get_pointer_position (GtkWidget *widget, gint *x, gint *y)
Function Documentation
ev_document_misc_format_date()
gchar * ev_document_misc_format_date (gint64 utime)
Definition at line 362 of file ev-document-misc.c.
References NULL.
Referenced by ev_annotation_set_modified_from_time(), and ev_properties_view_set_info().
ev_document_misc_get_loading_thumbnail()
GdkPixbuf * ev_document_misc_get_loading_thumbnail (int width, int height, gboolean inverted_colors)
ev_document_misc_get_loading_thumbnail: @width: the desired width @height: the desired height @inverted_colors: whether to invert colors
Returns: (transfer full): a #GdkPixbuf
Definition at line 124 of file ev-document-misc.c.
References NULL.
ev_document_misc_get_monitor_dpi()
gdouble ev_document_misc_get_monitor_dpi (GdkMonitor * monitor)
Definition at line 342 of file ev-document-misc.c.
ev_document_misc_get_page_border_size()
EV_DEPRECATED void ev_document_misc_get_page_border_size (gint page_width, gint page_height, GtkBorder * border)
Definition at line 132 of file ev-document-misc.c.
ev_document_misc_get_pointer_position()
void ev_document_misc_get_pointer_position (GtkWidget * widget, gint * x, gint * y)
Definition at line 376 of file ev-document-misc.c.
References NULL.
Referenced by ev_view_autoscroll_start(), ev_view_autoscroll_stop(), and ev_view_cancel_add_annotation().
ev_document_misc_get_thumbnail_frame()
GdkPixbuf * ev_document_misc_get_thumbnail_frame (int width, int height, GdkPixbuf * source_pixbuf)
ev_document_misc_get_thumbnail_frame: @width: the desired width @height: the desired height @source_pixbuf: a #GdkPixbuf
Returns: (transfer full): a #GdkPixbuf
Definition at line 108 of file ev-document-misc.c.
References TRUE.
ev_document_misc_invert_pixbuf()
void ev_document_misc_invert_pixbuf (GdkPixbuf * pixbuf)
Definition at line 312 of file ev-document-misc.c.
References data.
ev_document_misc_invert_surface()
void ev_document_misc_invert_surface (cairo_surface_t * surface)
Definition at line 299 of file ev-document-misc.c.
Referenced by ev_pixbuf_cache_set_inverted_colors().
ev_document_misc_paint_one_page()
EV_DEPRECATED void ev_document_misc_paint_one_page (cairo_t * cr, GtkWidget * widget, GdkRectangle * area, GtkBorder * border, gboolean highlight, gboolean inverted_colors)
Definition at line 153 of file ev-document-misc.c.
ev_document_misc_pixbuf_from_surface()
GdkPixbuf * ev_document_misc_pixbuf_from_surface (cairo_surface_t * surface)
ev_document_misc_pixbuf_from_surface: @surface: a #cairo_surface_t
Returns: (transfer full): a #GdkPixbuf
Definition at line 228 of file ev-document-misc.c.
References NULL.
ev_document_misc_surface_from_pixbuf()
cairo_surface_t * ev_document_misc_surface_from_pixbuf (GdkPixbuf * pixbuf)
Definition at line 202 of file ev-document-misc.c.
References NULL.
ev_document_misc_surface_rotate_and_scale()
cairo_surface_t * ev_document_misc_surface_rotate_and_scale (cairo_surface_t * surface, gint dest_width, gint dest_height, gint dest_rotation)
Definition at line 239 of file ev-document-misc.c.