MATE Desktop Environment: ev-document-layers.h File Reference
ev-document-layers.h File Reference
#include <glib-object.h>
#include <glib.h>
#include <gtk/gtk.h>
#include "ev-layer.h"
Classes
struct _EvDocumentLayersInterface
Macros
#define EV_TYPE_DOCUMENT_LAYERS (ev_document_layers_get_type ())
#define EV_DOCUMENT_LAYERS(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), EV_TYPE_DOCUMENT_LAYERS, EvDocumentLayers))
#define EV_DOCUMENT_LAYERS_IFACE(k) (G_TYPE_CHECK_CLASS_CAST((k), EV_TYPE_DOCUMENT_LAYERS, EvDocumentLayersInterface))
#define EV_IS_DOCUMENT_LAYERS(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), EV_TYPE_DOCUMENT_LAYERS))
#define EV_IS_DOCUMENT_LAYERS_IFACE(k) (G_TYPE_CHECK_CLASS_TYPE ((k), EV_TYPE_DOCUMENT_LAYERS))
#define EV_DOCUMENT_LAYERS_GET_IFACE(inst) (G_TYPE_INSTANCE_GET_INTERFACE ((inst), EV_TYPE_DOCUMENT_LAYERS, EvDocumentLayersInterface))
Typedefs
typedef struct _EvDocumentLayers EvDocumentLayers
typedef struct _EvDocumentLayersInterface EvDocumentLayersInterface
Enumerations
enum {
EV_DOCUMENT_LAYERS_COLUMN_TITLE , EV_DOCUMENT_LAYERS_COLUMN_LAYER , EV_DOCUMENT_LAYERS_COLUMN_VISIBLE , EV_DOCUMENT_LAYERS_COLUMN_ENABLED ,
EV_DOCUMENT_LAYERS_COLUMN_SHOWTOGGLE , EV_DOCUMENT_LAYERS_COLUMN_RBGROUP , EV_DOCUMENT_LAYERS_N_COLUMNS
}
Functions
GType ev_document_layers_get_type (void)
gboolean ev_document_layers_has_layers (EvDocumentLayers *document_layers)
GtkTreeModel * ev_document_layers_get_layers (EvDocumentLayers *document_layers)
void ev_document_layers_show_layer (EvDocumentLayers *document_layers, EvLayer *layer)
void ev_document_layers_hide_layer (EvDocumentLayers *document_layers, EvLayer *layer)
gboolean ev_document_layers_layer_is_visible (EvDocumentLayers *document_layers, EvLayer *layer)
Macro Definition Documentation
EV_DOCUMENT_LAYERS
#define EV_DOCUMENT_LAYERS (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), EV_TYPE_DOCUMENT_LAYERS, EvDocumentLayers))
Definition at line 37 of file ev-document-layers.h.
EV_DOCUMENT_LAYERS_GET_IFACE
#define EV_DOCUMENT_LAYERS_GET_IFACE (inst) (G_TYPE_INSTANCE_GET_INTERFACE ((inst), EV_TYPE_DOCUMENT_LAYERS, EvDocumentLayersInterface))
Definition at line 41 of file ev-document-layers.h.
EV_DOCUMENT_LAYERS_IFACE
#define EV_DOCUMENT_LAYERS_IFACE (k) (G_TYPE_CHECK_CLASS_CAST((k), EV_TYPE_DOCUMENT_LAYERS, EvDocumentLayersInterface))
Definition at line 38 of file ev-document-layers.h.
EV_IS_DOCUMENT_LAYERS
#define EV_IS_DOCUMENT_LAYERS (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), EV_TYPE_DOCUMENT_LAYERS))
Definition at line 39 of file ev-document-layers.h.
EV_IS_DOCUMENT_LAYERS_IFACE
#define EV_IS_DOCUMENT_LAYERS_IFACE (k) (G_TYPE_CHECK_CLASS_TYPE ((k), EV_TYPE_DOCUMENT_LAYERS))
Definition at line 40 of file ev-document-layers.h.
EV_TYPE_DOCUMENT_LAYERS
#define EV_TYPE_DOCUMENT_LAYERS (ev_document_layers_get_type ())
Definition at line 36 of file ev-document-layers.h.
Typedef Documentation
EvDocumentLayers
typedef struct _EvDocumentLayers EvDocumentLayers
Definition at line 43 of file ev-document-layers.h.
EvDocumentLayersInterface
typedef struct _EvDocumentLayersInterface EvDocumentLayersInterface
Definition at line 44 of file ev-document-layers.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EV_DOCUMENT_LAYERS_COLUMN_TITLE
EV_DOCUMENT_LAYERS_COLUMN_LAYER
EV_DOCUMENT_LAYERS_COLUMN_VISIBLE
EV_DOCUMENT_LAYERS_COLUMN_ENABLED
EV_DOCUMENT_LAYERS_COLUMN_SHOWTOGGLE
EV_DOCUMENT_LAYERS_COLUMN_RBGROUP
EV_DOCUMENT_LAYERS_N_COLUMNS
Definition at line 46 of file ev-document-layers.h.
Function Documentation
ev_document_layers_get_layers()
GtkTreeModel * ev_document_layers_get_layers (EvDocumentLayers * document_layers)
ev_document_layers_get_layers: @document_layers: an EvDocumentLayers
Returns: (transfer full): a #GtkTreeModel
Definition at line 48 of file ev-document-layers.c.
References EV_DOCUMENT_LAYERS_GET_IFACE, and _EvDocumentLayersInterface::get_layers.
ev_document_layers_get_type()
GType ev_document_layers_get_type (void)
ev_document_layers_has_layers()
gboolean ev_document_layers_has_layers (EvDocumentLayers * document_layers)
Definition at line 34 of file ev-document-layers.c.
References EV_DOCUMENT_LAYERS_GET_IFACE, and _EvDocumentLayersInterface::has_layers.
ev_document_layers_hide_layer()
void ev_document_layers_hide_layer (EvDocumentLayers * document_layers, EvLayer * layer)
Definition at line 65 of file ev-document-layers.c.
References EV_DOCUMENT_LAYERS_GET_IFACE, and _EvDocumentLayersInterface::hide_layer.
Referenced by ev_view_handle_link().
ev_document_layers_layer_is_visible()
gboolean ev_document_layers_layer_is_visible (EvDocumentLayers * document_layers, EvLayer * layer)
Definition at line 74 of file ev-document-layers.c.
References EV_DOCUMENT_LAYERS_GET_IFACE, and _EvDocumentLayersInterface::layer_is_visible.
Referenced by ev_view_handle_link().
ev_document_layers_show_layer()
void ev_document_layers_show_layer (EvDocumentLayers * document_layers, EvLayer * layer)
Definition at line 56 of file ev-document-layers.c.
References EV_DOCUMENT_LAYERS_GET_IFACE, and _EvDocumentLayersInterface::show_layer.
Referenced by ev_view_handle_link().