MATE Desktop Environment: ev-file-helpers.c File Reference
ev-file-helpers.c File Reference
#include <config.h>
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <glib.h>
#include <glib/gstdio.h>
#include <glib/gi18n-lib.h>
#include "ev-file-helpers.h"
Macros
#define N_ARGS 4
#define BUFFER_SIZE 1024
Functions
void _ev_file_helpers_init (void)
void _ev_file_helpers_shutdown (void)
int ev_mkstemp (const char *template, char **file_name, GError **error)
GFile * ev_mkstemp_file (const char *template, GError **error)
gchar * ev_mkdtemp (const char *template, GError **error)
void ev_tmp_filename_unlink (const gchar *filename)
void ev_tmp_file_unlink (GFile *file)
void ev_tmp_uri_unlink (const gchar *uri)
gboolean ev_file_is_temp (GFile *file)
gboolean ev_xfer_uri_simple (const char *from, const char *to, GError **error)
gchar * ev_file_get_mime_type (const gchar *uri, gboolean fast, GError **error)
gchar * ev_file_uncompress (const gchar *uri, EvCompressionType type, GError **error)
gchar * ev_file_compress (const gchar *uri, EvCompressionType type, GError **error)
Macro Definition Documentation
BUFFER_SIZE
#define BUFFER_SIZE 1024
Definition at line 445 of file ev-file-helpers.c.
N_ARGS
#define N_ARGS 4
Definition at line 444 of file ev-file-helpers.c.
Function Documentation
_ev_file_helpers_init()
void _ev_file_helpers_init (void)
Definition at line 103 of file ev-file-helpers.c.
Referenced by ev_init().
_ev_file_helpers_shutdown()
void _ev_file_helpers_shutdown (void)
Definition at line 108 of file ev-file-helpers.c.
References NULL.
Referenced by ev_shutdown().
ev_file_compress()
gchar * ev_file_compress (const gchar * uri, EvCompressionType type, GError ** error)
ev_file_compress: @uri: a file URI @type: the compression type @error: a #GError location to store an error, or NULL
Compresses the file at @uri.
If @type is EV_COMPRESSION_NONE, it does nothing and returns NULL.
Otherwise, it returns the filename of a temporary file containing the compressed data from the file at @uri.
On error it returns NULL and fills in @error.
It is the caller's responsibility to unlink the temp file after use.
Returns: a newly allocated string URI, or NULL on error
Definition at line 590 of file ev-file-helpers.c.
References error, NULL, TRUE, and type.
ev_file_get_mime_type()
gchar * ev_file_get_mime_type (const gchar * uri, gboolean fast, GError ** error)
ev_file_get_mime_type: @uri: the URI @fast: whether to use fast MIME type detection @error: a #GError location to store an error, or NULL
Note: on unknown MIME types, this may return NULL without @error being filled in.
Returns: a newly allocated string with the MIME type of the file at @uri, or NULL on error or if the MIME type could not be determined
Definition at line 428 of file ev-file-helpers.c.
References error.
Referenced by ev_document_load().
ev_file_is_temp()
gboolean ev_file_is_temp (GFile * file)
Definition at line 289 of file ev-file-helpers.c.
References FALSE.
Referenced by ev_metadata_new().
ev_file_uncompress()
gchar * ev_file_uncompress (const gchar * uri, EvCompressionType type, GError ** error)
ev_file_uncompress: @uri: a file URI @type: the compression type @error: a #GError location to store an error, or NULL
Uncompresses the file at @uri.
If @type is EV_COMPRESSION_NONE, it does nothing and returns NULL.
Otherwise, it returns the filename of a temporary file containing the decompressed data from the file at @uri. On error it returns NULL and fills in @error.
It is the caller's responsibility to unlink the temp file after use.
Returns: a newly allocated string URI, or NULL on error
Definition at line 561 of file ev-file-helpers.c.
References error, FALSE, NULL, and type.
Referenced by ev_document_factory_get_document().
ev_mkdtemp()
gchar * ev_mkdtemp (const char * template, GError ** error)
ev_mkdtemp: @template: a template string; must end in 'XXXXXX' @error: a location to store a #GError
Creates a temp directory in the atril temp directory.
Returns: a newly allocated string with the temp directory name, or NULL on error with @error filled in
Definition at line 210 of file ev-file-helpers.c.
References _, error, name, and NULL.
ev_mkstemp()
int ev_mkstemp (const char * template, char ** file_name, GError ** error)
ev_mkstemp: @template: a template string; must contain 'XXXXXX', but not necessarily as a suffix @file_name: a location to store the filename of the temp file @error: a location to store a #GError
Creates a temp file in the atril temp directory.
Returns: a file descriptor to the newly created temp file name, or %-1 on error with @error filled in
Definition at line 129 of file ev-file-helpers.c.
References _, error, name, and NULL.
Referenced by ev_image_save_tmp(), and ev_mkstemp_file().
ev_mkstemp_file()
GFile * ev_mkstemp_file (const char * template, GError ** error)
ev_mkstemp_file: @template: a template string; must contain 'XXXXXX', but not necessarily as a suffix @error: a location to store a #GError
Creates a temp #GFile in the atril temp directory. See ev_mkstemp() for more information.
Returns: a newly allocated #GFile for the newly created temp file name, or NULL on error with @error filled in
Definition at line 179 of file ev-file-helpers.c.
References error, ev_mkstemp(), and NULL.
Referenced by ev_attachment_open().
ev_tmp_file_unlink()
void ev_tmp_file_unlink (GFile * file)
Definition at line 250 of file ev-file-helpers.c.
References error, and NULL.
Referenced by ev_tmp_uri_unlink().
ev_tmp_filename_unlink()
void ev_tmp_filename_unlink (const gchar * filename)
Definition at line 236 of file ev-file-helpers.c.
ev_tmp_uri_unlink()
void ev_tmp_uri_unlink (const gchar * uri)
Definition at line 270 of file ev-file-helpers.c.
References ev_tmp_file_unlink().
ev_xfer_uri_simple()
gboolean ev_xfer_uri_simple (const char * from, const char * to, GError ** error)
ev_xfer_uri_simple: @from: the source URI @to: the target URI @error: a #GError location to store an error, or NULL
Performs a g_file_copy() from @from to @to.
Returns: TRUE on success, or FALSE on error with @error filled in
Definition at line 318 of file ev-file-helpers.c.
References error, NULL, source_file, target_file, and TRUE.