MATE Desktop Environment: ev-jobs.c File Reference
ev-jobs.c File Reference
#include <config.h>
#include "ev-jobs.h"
#include "ev-document-thumbnails.h"
#include "ev-document-links.h"
#include "ev-document-images.h"
#include "ev-job-scheduler.h"
#include "ev-document-forms.h"
#include "ev-file-exporter.h"
#include "ev-document-factory.h"
#include "ev-document-misc.h"
#include "ev-file-helpers.h"
#include "ev-document-fonts.h"
#include "ev-document-security.h"
#include "ev-document-find.h"
#include "ev-document-layers.h"
#include "ev-document-print.h"
#include "ev-document-annotations.h"
#include "ev-document-attachments.h"
#include "ev-document-text.h"
#include "ev-debug.h"
#include <gtk/gtk.h>
#include <errno.h>
#include <glib/gstdio.h>
#include <glib/gi18n-lib.h>
#include <unistd.h>
Enumerations
enum { CANCELLED , FINISHED , LAST_SIGNAL }
enum { FONTS_UPDATED , FONTS_LAST_SIGNAL }
enum { FIND_UPDATED , FIND_LAST_SIGNAL }
Functions
gboolean ev_job_run (EvJob *job)
void ev_job_cancel (EvJob *job)
void ev_job_failed (EvJob *job, GQuark domain, gint code, const gchar *format,...)
void ev_job_failed_from_error (EvJob *job, GError *error)
void ev_job_succeeded (EvJob *job)
gboolean ev_job_is_finished (EvJob *job)
gboolean ev_job_is_failed (EvJob *job)
EvJobRunMode ev_job_get_run_mode (EvJob *job)
void ev_job_set_run_mode (EvJob *job, EvJobRunMode run_mode)
EvJob * ev_job_links_new (EvDocument *document)
EvJob * ev_job_attachments_new (EvDocument *document)
EvJob * ev_job_annots_new (EvDocument *document)
EvJob * ev_job_render_new (EvDocument *document, gint page, gint rotation, gdouble scale, gint width, gint height)
void ev_job_render_set_selection_info (EvJobRender *job, EvRectangle *selection_points, EvSelectionStyle selection_style, GdkColor *text, GdkColor *base)
EvJob * ev_job_page_data_new (EvDocument *document, gint page, EvJobPageDataFlags flags)
EvJob * ev_job_thumbnail_new (EvDocument *document, gint page, gint rotation, gdouble scale)
EvJob * ev_job_fonts_new (EvDocument *document)
EvJob * ev_job_load_new (const gchar *uri)
void ev_job_load_set_uri (EvJobLoad *job, const gchar *uri)
void ev_job_load_set_password (EvJobLoad *job, const gchar *password)
EvJob * ev_job_save_new (EvDocument *document, const gchar *uri, const gchar *document_uri)
EvJob * ev_job_find_new (EvDocument *document, gint start_page, gint n_pages, const gchar *text, gboolean case_sensitive)
gint ev_job_find_get_n_results (EvJobFind *job, gint page)
gdouble ev_job_find_get_progress (EvJobFind *job)
gboolean ev_job_find_has_results (EvJobFind *job)
GList ** ev_job_find_get_results (EvJobFind *job)
EvJob * ev_job_layers_new (EvDocument *document)
EvJob * ev_job_export_new (EvDocument *document)
void ev_job_export_set_page (EvJobExport *job, gint page)
EvJob * ev_job_print_new (EvDocument *document)
void ev_job_print_set_page (EvJobPrint *job, gint page)
void ev_job_print_set_cairo (EvJobPrint *job, cairo_t *cr)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CANCELLED
FINISHED
LAST_SIGNAL
Definition at line 49 of file ev-jobs.c.
anonymous enum
anonymous enum
Enumerator
FONTS_UPDATED
FONTS_LAST_SIGNAL
Definition at line 55 of file ev-jobs.c.
anonymous enum
anonymous enum
Enumerator
FIND_UPDATED
FIND_LAST_SIGNAL
Definition at line 60 of file ev-jobs.c.
Function Documentation
ev_job_annots_new()
EvJob * ev_job_annots_new (EvDocument * document)
Definition at line 528 of file ev-jobs.c.
References DEBUG_JOBS, _EvJob::document, EV_TYPE_JOB_ANNOTS, and NULL.
ev_job_attachments_new()
EvJob * ev_job_attachments_new (EvDocument * document)
Definition at line 449 of file ev-jobs.c.
References DEBUG_JOBS, _EvJob::document, EV_TYPE_JOB_ATTACHMENTS, and NULL.
ev_job_cancel()
void ev_job_cancel (EvJob * job)
Definition at line 193 of file ev-jobs.c.
References _EvJob::cancellable, CANCELLED, _EvJob::cancelled, DEBUG_JOBS, EV_GET_TYPE_NAME, _EvJob::finished, _EvJob::idle_finished_id, and TRUE.
Referenced by G_DEFINE_TYPE_EXTENDED().
ev_job_export_new()
EvJob * ev_job_export_new (EvDocument * document)
Definition at line 1549 of file ev-jobs.c.
References DEBUG_JOBS, _EvJob::document, EV_TYPE_JOB_EXPORT, and NULL.
ev_job_export_set_page()
void ev_job_export_set_page (EvJobExport * job, gint page)
Definition at line 1562 of file ev-jobs.c.
References _EvJobExport::page.
ev_job_failed()
void ev_job_failed (EvJob * job, GQuark domain, gint code, const gchar * format, ...)
Definition at line 212 of file ev-jobs.c.
References DEBUG_JOBS, _EvJob::error, EV_GET_TYPE_NAME, _EvJob::failed, _EvJob::finished, message(), and TRUE.
ev_job_failed_from_error()
void ev_job_failed_from_error (EvJob * job, GError * error)
ev_job_failed_from_error: @job: an EvJob @error: a #GError
Rename to: ev_job_failed
Definition at line 246 of file ev-jobs.c.
References DEBUG_JOBS, _EvJob::error, error, EV_GET_TYPE_NAME, _EvJob::failed, _EvJob::finished, and TRUE.
ev_job_find_get_n_results()
gint ev_job_find_get_n_results (EvJobFind * job, gint page)
Definition at line 1367 of file ev-jobs.c.
References EV_JOB, _EvJobFind::pages, and _EvJobFind::results.
ev_job_find_get_progress()
gdouble ev_job_find_get_progress (EvJobFind * job)
Definition at line 1379 of file ev-jobs.c.
References _EvJobFind::current_page, EV_JOB, ev_job_is_finished(), _EvJobFind::n_pages, and _EvJobFind::start_page.
ev_job_find_get_results()
GList ** ev_job_find_get_results (EvJobFind * job)
ev_job_find_get_results: (skip) @job: an EvJobFind
Returns: a #GList of #GLists containing #EvRectangles
Definition at line 1410 of file ev-jobs.c.
References _EvJobFind::pages.
ev_job_find_has_results()
gboolean ev_job_find_has_results (EvJobFind * job)
Definition at line 1398 of file ev-jobs.c.
References _EvJobFind::has_results.
ev_job_find_new()
EvJob * ev_job_find_new (EvDocument * document, gint start_page, gint n_pages, const gchar * text, gboolean case_sensitive)
Definition at line 1336 of file ev-jobs.c.
References _EvJobFind::case_sensitive, _EvJobFind::current_page, DEBUG_JOBS, EV_JOB, EV_TYPE_JOB_FIND, FALSE, _EvJobFind::has_results, _EvDocument::iswebdocument, _EvJobFind::n_pages, NULL, _EvJobFind::pages, _EvJobFind::results, _EvJobFind::start_page, and _EvJobFind::text.
ev_job_fonts_new()
EvJob * ev_job_fonts_new (EvDocument * document)
Definition at line 942 of file ev-jobs.c.
References DEBUG_JOBS, EV_JOB, EV_TYPE_JOB_FONTS, and NULL.
Referenced by ev_properties_fonts_set_document().
ev_job_get_run_mode()
EvJobRunMode ev_job_get_run_mode (EvJob * job)
Definition at line 285 of file ev-jobs.c.
References _EvJob::run_mode.
Referenced by ev_job_scheduler_push_job(), and ev_job_scheduler_update_job().
ev_job_is_failed()
gboolean ev_job_is_failed (EvJob * job)
Definition at line 279 of file ev-jobs.c.
References _EvJob::failed.
ev_job_is_finished()
gboolean ev_job_is_finished (EvJob * job)
Definition at line 273 of file ev-jobs.c.
References _EvJob::finished.
Referenced by ev_job_find_get_progress().
ev_job_layers_new()
EvJob * ev_job_layers_new (EvDocument * document)
Definition at line 1467 of file ev-jobs.c.
References DEBUG_JOBS, _EvJob::document, EV_TYPE_JOB_LAYERS, and NULL.
ev_job_links_new()
EvJob * ev_job_links_new (EvDocument * document)
Definition at line 383 of file ev-jobs.c.
References DEBUG_JOBS, _EvJob::document, EV_TYPE_JOB_LINKS, and NULL.
ev_job_load_new()
EvJob * ev_job_load_new (const gchar * uri)
Definition at line 1041 of file ev-jobs.c.
References DEBUG_JOBS, EV_JOB, EV_TYPE_JOB_LOAD, NULL, and _EvJobLoad::uri.
Referenced by ev_window_open_uri().
ev_job_load_set_password()
void ev_job_load_set_password (EvJobLoad * job, const gchar * password)
Definition at line 1064 of file ev-jobs.c.
References DEBUG_JOBS, NULL, and _EvJobLoad::password.
ev_job_load_set_uri()
void ev_job_load_set_uri (EvJobLoad * job, const gchar * uri)
Definition at line 1054 of file ev-jobs.c.
References DEBUG_JOBS, and _EvJobLoad::uri.
ev_job_page_data_new()
EvJob * ev_job_page_data_new (EvDocument * document, gint page, EvJobPageDataFlags flags)
Definition at line 782 of file ev-jobs.c.
References DEBUG_JOBS, EV_JOB, EV_TYPE_JOB_PAGE_DATA, _EvJobPageData::flags, NULL, and _EvJobPageData::page.
ev_job_print_new()
EvJob * ev_job_print_new (EvDocument * document)
Definition at line 1648 of file ev-jobs.c.
References DEBUG_JOBS, _EvJob::document, EV_TYPE_JOB_PRINT, and NULL.
ev_job_print_set_cairo()
void ev_job_print_set_cairo (EvJobPrint * job, cairo_t * cr)
Definition at line 1668 of file ev-jobs.c.
References _EvJobPrint::cr, and NULL.
ev_job_print_set_page()
void ev_job_print_set_page (EvJobPrint * job, gint page)
Definition at line 1661 of file ev-jobs.c.
References _EvJobPrint::page.
ev_job_render_new()
EvJob * ev_job_render_new (EvDocument * document, gint page, gint rotation, gdouble scale, gint width, gint height)
Definition at line 671 of file ev-jobs.c.
References DEBUG_JOBS, EV_JOB, EV_TYPE_JOB_RENDER, NULL, _EvJobRender::page, _EvJobRender::rotation, _EvJobRender::scale, _EvJobRender::target_height, and _EvJobRender::target_width.
ev_job_render_set_selection_info()
void ev_job_render_set_selection_info (EvJobRender * job, EvRectangle * selection_points, EvSelectionStyle selection_style, GdkColor * text, GdkColor * base)
Definition at line 695 of file ev-jobs.c.
References _EvJobRender::base, _EvJobRender::include_selection, _EvJobRender::selection_points, _EvJobRender::selection_style, _EvJobRender::text, and TRUE.
ev_job_run()
gboolean ev_job_run (EvJob * job)
Definition at line 185 of file ev-jobs.c.
ev_job_save_new()
EvJob * ev_job_save_new (EvDocument * document, const gchar * uri, const gchar * document_uri)
Definition at line 1204 of file ev-jobs.c.
References DEBUG_JOBS, _EvJobSave::document_uri, EV_JOB, EV_TYPE_JOB_SAVE, NULL, and _EvJobSave::uri.
ev_job_set_run_mode()
void ev_job_set_run_mode (EvJob * job, EvJobRunMode run_mode)
Definition at line 291 of file ev-jobs.c.
References _EvJob::run_mode.
ev_job_succeeded()
void ev_job_succeeded (EvJob * job)
Definition at line 261 of file ev-jobs.c.
References DEBUG_JOBS, EV_GET_TYPE_NAME, _EvJob::failed, FALSE, and _EvJob::finished.
ev_job_thumbnail_new()
EvJob * ev_job_thumbnail_new (EvDocument * document, gint page, gint rotation, gdouble scale)
Definition at line 861 of file ev-jobs.c.
References DEBUG_JOBS, EV_JOB, EV_TYPE_JOB_THUMBNAIL, NULL, _EvJobThumbnail::page, _EvJobThumbnail::rotation, and _EvJobThumbnail::scale.