MATE Desktop Environment: ev-jobs.h File Reference
ev-jobs.h File Reference
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <cairo.h>
#include <atril-document.h>
Classes
struct _EvJob
struct _EvJobClass
struct _EvJobLinks
struct _EvJobLinksClass
struct _EvJobAttachments
struct _EvJobAttachmentsClass
struct _EvJobAnnots
struct _EvJobAnnotsClass
struct _EvJobRender
struct _EvJobRenderClass
struct _EvJobPageData
struct _EvJobPageDataClass
struct _EvJobThumbnail
struct _EvJobThumbnailClass
struct _EvJobFonts
struct _EvJobFontsClass
struct _EvJobLoad
struct _EvJobLoadClass
struct _EvJobSave
struct _EvJobSaveClass
struct _EvJobFind
struct _EvJobFindClass
struct _EvJobLayers
struct _EvJobLayersClass
struct _EvJobExport
struct _EvJobExportClass
struct _EvJobPrint
struct _EvJobPrintClass
Macros
#define EV_TYPE_JOB (ev_job_get_type())
#define EV_JOB(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB, EvJob))
#define EV_JOB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB, EvJobClass))
#define EV_IS_JOB(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB))
#define EV_JOB_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_JOB, EvJobClass))
#define EV_TYPE_JOB_LINKS (ev_job_links_get_type())
#define EV_JOB_LINKS(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_LINKS, EvJobLinks))
#define EV_JOB_LINKS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_LINKS, EvJobLinksClass))
#define EV_IS_JOB_LINKS(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_LINKS))
#define EV_TYPE_JOB_ATTACHMENTS (ev_job_attachments_get_type())
#define EV_JOB_ATTACHMENTS(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_ATTACHMENTS, EvJobAttachments))
#define EV_JOB_ATTACHMENTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_ATTACHMENTS, EvJobAttachmentsClass))
#define EV_IS_JOB_ATTACHMENTS(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_ATTACHMENTS))
#define EV_TYPE_JOB_ANNOTS (ev_job_annots_get_type())
#define EV_JOB_ANNOTS(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_ANNOTS, EvJobAnnots))
#define EV_JOB_ANNOTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_ANNOTS, EvJobAnnotsClass))
#define EV_IS_JOB_ANNOTS(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_ANNOTS))
#define EV_TYPE_JOB_RENDER (ev_job_render_get_type())
#define EV_JOB_RENDER(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_RENDER, EvJobRender))
#define EV_JOB_RENDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_RENDER, EvJobRenderClass))
#define EV_IS_JOB_RENDER(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_RENDER))
#define EV_TYPE_JOB_PAGE_DATA (ev_job_page_data_get_type())
#define EV_JOB_PAGE_DATA(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_PAGE_DATA, EvJobPageData))
#define EV_JOB_PAGE_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_PAGE_DATA, EvJobPageDataClass))
#define EV_IS_JOB_PAGE_DATA(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_PAGE_DATA))
#define EV_TYPE_JOB_THUMBNAIL (ev_job_thumbnail_get_type())
#define EV_JOB_THUMBNAIL(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_THUMBNAIL, EvJobThumbnail))
#define EV_JOB_THUMBNAIL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_THUMBNAIL, EvJobThumbnailClass))
#define EV_IS_JOB_THUMBNAIL(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_THUMBNAIL))
#define EV_TYPE_JOB_WEB_THUMBNAIL (ev_job_web_thumbnail_get_type())
#define EV_JOB_WEB_THUMBNAIL(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_WEB_THUMBNAIL, EvJobWebThumbnail))
#define EV_JOB_WEB_THUMBNAIL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_WEB_THUMBNAIL, EvJobWebThumbnailClass))
#define EV_IS_JOB_WEB_THUMBNAIL(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_WEB_THUMBNAIL))
#define EV_TYPE_JOB_FONTS (ev_job_fonts_get_type())
#define EV_JOB_FONTS(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_FONTS, EvJobFonts))
#define EV_JOB_FONTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_FONTS, EvJobFontsClass))
#define EV_IS_JOB_FONTS(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_FONTS))
#define EV_TYPE_JOB_LOAD (ev_job_load_get_type())
#define EV_JOB_LOAD(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_LOAD, EvJobLoad))
#define EV_JOB_LOAD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_LOAD, EvJobLoadClass))
#define EV_IS_JOB_LOAD(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_LOAD))
#define EV_TYPE_JOB_SAVE (ev_job_save_get_type())
#define EV_JOB_SAVE(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_SAVE, EvJobSave))
#define EV_JOB_SAVE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_SAVE, EvJobSaveClass))
#define EV_IS_JOB_SAVE(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_SAVE))
#define EV_TYPE_JOB_FIND (ev_job_find_get_type())
#define EV_JOB_FIND(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_FIND, EvJobFind))
#define EV_JOB_FIND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_FIND, EvJobFindClass))
#define EV_IS_JOB_FIND(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_FIND))
#define EV_TYPE_JOB_LAYERS (ev_job_layers_get_type())
#define EV_JOB_LAYERS(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_LAYERS, EvJobLayers))
#define EV_JOB_LAYERS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_LAYERS, EvJobLayersClass))
#define EV_IS_JOB_LAYERS(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_LAYERS))
#define EV_TYPE_JOB_EXPORT (ev_job_export_get_type())
#define EV_JOB_EXPORT(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_EXPORT, EvJobExport))
#define EV_JOB_EXPORT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_EXPORT, EvJobExportClass))
#define EV_IS_JOB_EXPORT(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_EXPORT))
#define EV_TYPE_JOB_PRINT (ev_job_print_get_type())
#define EV_JOB_PRINT(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_PRINT, EvJobPrint))
#define EV_JOB_PRINT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_PRINT, EvJobPrintClass))
#define EV_IS_JOB_PRINT(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_PRINT))
Typedefs
typedef struct _EvJob EvJob
typedef struct _EvJobClass EvJobClass
typedef struct _EvJobRender EvJobRender
typedef struct _EvJobRenderClass EvJobRenderClass
typedef struct _EvJobPageData EvJobPageData
typedef struct _EvJobPageDataClass EvJobPageDataClass
typedef struct _EvJobThumbnail EvJobThumbnail
typedef struct _EvJobThumbnailClass EvJobThumbnailClass
typedef struct _EvJobWebThumbnail EvJobWebThumbnail
typedef struct _EvJobWebThumbnailClass EvJobWebThumbnailClass
typedef struct _EvJobLinks EvJobLinks
typedef struct _EvJobLinksClass EvJobLinksClass
typedef struct _EvJobAttachments EvJobAttachments
typedef struct _EvJobAttachmentsClass EvJobAttachmentsClass
typedef struct _EvJobAnnots EvJobAnnots
typedef struct _EvJobAnnotsClass EvJobAnnotsClass
typedef struct _EvJobFonts EvJobFonts
typedef struct _EvJobFontsClass EvJobFontsClass
typedef struct _EvJobLoad EvJobLoad
typedef struct _EvJobLoadClass EvJobLoadClass
typedef struct _EvJobSave EvJobSave
typedef struct _EvJobSaveClass EvJobSaveClass
typedef struct _EvJobFind EvJobFind
typedef struct _EvJobFindClass EvJobFindClass
typedef struct _EvJobLayers EvJobLayers
typedef struct _EvJobLayersClass EvJobLayersClass
typedef struct _EvJobExport EvJobExport
typedef struct _EvJobExportClass EvJobExportClass
typedef struct _EvJobPrint EvJobPrint
typedef struct _EvJobPrintClass EvJobPrintClass
Enumerations
enum EvJobRunMode { EV_JOB_RUN_THREAD , EV_JOB_RUN_MAIN_LOOP }
enum EvJobPageDataFlags {
EV_PAGE_DATA_INCLUDE_NONE = 0 , EV_PAGE_DATA_INCLUDE_LINKS = 1 << 0 , EV_PAGE_DATA_INCLUDE_TEXT = 1 << 1 , EV_PAGE_DATA_INCLUDE_TEXT_MAPPING = 1 << 2 ,
EV_PAGE_DATA_INCLUDE_TEXT_LAYOUT = 1 << 3 , EV_PAGE_DATA_INCLUDE_TEXT_ATTRS = 1 << 4 , EV_PAGE_DATA_INCLUDE_TEXT_LOG_ATTRS = 1 << 5 , EV_PAGE_DATA_INCLUDE_IMAGES = 1 << 6 ,
EV_PAGE_DATA_INCLUDE_FORMS = 1 << 7 , EV_PAGE_DATA_INCLUDE_ANNOTS = 1 << 8 , EV_PAGE_DATA_INCLUDE_ALL = (1 << 9) - 1
}
Functions
GType ev_job_get_type (void)
gboolean ev_job_run (EvJob *job)
void ev_job_cancel (EvJob *job)
void ev_job_failed (EvJob *job, GQuark domain, gint code, const gchar *format,...)
void ev_job_failed_from_error (EvJob *job, GError *error)
void ev_job_succeeded (EvJob *job)
gboolean ev_job_is_finished (EvJob *job)
gboolean ev_job_is_failed (EvJob *job)
EvJobRunMode ev_job_get_run_mode (EvJob *job)
void ev_job_set_run_mode (EvJob *job, EvJobRunMode run_mode)
GType ev_job_links_get_type (void)
EvJob * ev_job_links_new (EvDocument *document)
GType ev_job_attachments_get_type (void)
EvJob * ev_job_attachments_new (EvDocument *document)
GType ev_job_annots_get_type (void)
EvJob * ev_job_annots_new (EvDocument *document)
GType ev_job_render_get_type (void)
EvJob * ev_job_render_new (EvDocument *document, gint page, gint rotation, gdouble scale, gint width, gint height)
void ev_job_render_set_selection_info (EvJobRender *job, EvRectangle *selection_points, EvSelectionStyle selection_style, GdkColor *text, GdkColor *base)
GType ev_job_page_data_get_type (void)
EvJob * ev_job_page_data_new (EvDocument *document, gint page, EvJobPageDataFlags flags)
GType ev_job_thumbnail_get_type (void)
EvJob * ev_job_thumbnail_new (EvDocument *document, gint page, gint rotation, gdouble scale)
GType ev_job_fonts_get_type (void)
EvJob * ev_job_fonts_new (EvDocument *document)
GType ev_job_load_get_type (void)
EvJob * ev_job_load_new (const gchar *uri)
void ev_job_load_set_uri (EvJobLoad *load, const gchar *uri)
void ev_job_load_set_password (EvJobLoad *job, const gchar *password)
GType ev_job_save_get_type (void)
EvJob * ev_job_save_new (EvDocument *document, const gchar *uri, const gchar *document_uri)
GType ev_job_find_get_type (void)
EvJob * ev_job_find_new (EvDocument *document, gint start_page, gint n_pages, const gchar *text, gboolean case_sensitive)
gint ev_job_find_get_n_results (EvJobFind *job, gint pages)
gdouble ev_job_find_get_progress (EvJobFind *job)
gboolean ev_job_find_has_results (EvJobFind *job)
GList ** ev_job_find_get_results (EvJobFind *job)
GType ev_job_layers_get_type (void)
EvJob * ev_job_layers_new (EvDocument *document)
GType ev_job_export_get_type (void)
EvJob * ev_job_export_new (EvDocument *document)
void ev_job_export_set_page (EvJobExport *job, gint page)
GType ev_job_print_get_type (void)
EvJob * ev_job_print_new (EvDocument *document)
void ev_job_print_set_page (EvJobPrint *job, gint page)
void ev_job_print_set_cairo (EvJobPrint *job, cairo_t *cr)
Macro Definition Documentation
EV_IS_JOB
#define EV_IS_JOB (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB))
Definition at line 84 of file ev-jobs.h.
EV_IS_JOB_ANNOTS
#define EV_IS_JOB_ANNOTS (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_ANNOTS))
Definition at line 100 of file ev-jobs.h.
EV_IS_JOB_ATTACHMENTS
#define EV_IS_JOB_ATTACHMENTS (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_ATTACHMENTS))
Definition at line 95 of file ev-jobs.h.
EV_IS_JOB_EXPORT
#define EV_IS_JOB_EXPORT (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_EXPORT))
Definition at line 150 of file ev-jobs.h.
EV_IS_JOB_FIND
#define EV_IS_JOB_FIND (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_FIND))
Definition at line 140 of file ev-jobs.h.
EV_IS_JOB_FONTS
#define EV_IS_JOB_FONTS (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_FONTS))
Definition at line 125 of file ev-jobs.h.
EV_IS_JOB_LAYERS
#define EV_IS_JOB_LAYERS (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_LAYERS))
Definition at line 145 of file ev-jobs.h.
EV_IS_JOB_LINKS
#define EV_IS_JOB_LINKS (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_LINKS))
Definition at line 90 of file ev-jobs.h.
EV_IS_JOB_LOAD
#define EV_IS_JOB_LOAD (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_LOAD))
Definition at line 130 of file ev-jobs.h.
EV_IS_JOB_PAGE_DATA
#define EV_IS_JOB_PAGE_DATA (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_PAGE_DATA))
Definition at line 110 of file ev-jobs.h.
EV_IS_JOB_PRINT
#define EV_IS_JOB_PRINT (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_PRINT))
Definition at line 155 of file ev-jobs.h.
EV_IS_JOB_RENDER
#define EV_IS_JOB_RENDER (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_RENDER))
Definition at line 105 of file ev-jobs.h.
EV_IS_JOB_SAVE
#define EV_IS_JOB_SAVE (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_SAVE))
Definition at line 135 of file ev-jobs.h.
EV_IS_JOB_THUMBNAIL
#define EV_IS_JOB_THUMBNAIL (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_THUMBNAIL))
Definition at line 115 of file ev-jobs.h.
EV_IS_JOB_WEB_THUMBNAIL
#define EV_IS_JOB_WEB_THUMBNAIL (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_JOB_WEB_THUMBNAIL))
Definition at line 120 of file ev-jobs.h.
EV_JOB
#define EV_JOB (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB, EvJob))
Definition at line 82 of file ev-jobs.h.
EV_JOB_ANNOTS
#define EV_JOB_ANNOTS (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_ANNOTS, EvJobAnnots))
Definition at line 98 of file ev-jobs.h.
EV_JOB_ANNOTS_CLASS
#define EV_JOB_ANNOTS_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_ANNOTS, EvJobAnnotsClass))
Definition at line 99 of file ev-jobs.h.
EV_JOB_ATTACHMENTS
#define EV_JOB_ATTACHMENTS (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_ATTACHMENTS, EvJobAttachments))
Definition at line 93 of file ev-jobs.h.
EV_JOB_ATTACHMENTS_CLASS
#define EV_JOB_ATTACHMENTS_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_ATTACHMENTS, EvJobAttachmentsClass))
Definition at line 94 of file ev-jobs.h.
EV_JOB_CLASS
#define EV_JOB_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB, EvJobClass))
Definition at line 83 of file ev-jobs.h.
EV_JOB_EXPORT
#define EV_JOB_EXPORT (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_EXPORT, EvJobExport))
Definition at line 148 of file ev-jobs.h.
EV_JOB_EXPORT_CLASS
#define EV_JOB_EXPORT_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_EXPORT, EvJobExportClass))
Definition at line 149 of file ev-jobs.h.
EV_JOB_FIND
#define EV_JOB_FIND (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_FIND, EvJobFind))
Definition at line 138 of file ev-jobs.h.
EV_JOB_FIND_CLASS
#define EV_JOB_FIND_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_FIND, EvJobFindClass))
Definition at line 139 of file ev-jobs.h.
EV_JOB_FONTS
#define EV_JOB_FONTS (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_FONTS, EvJobFonts))
Definition at line 123 of file ev-jobs.h.
EV_JOB_FONTS_CLASS
#define EV_JOB_FONTS_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_FONTS, EvJobFontsClass))
Definition at line 124 of file ev-jobs.h.
EV_JOB_GET_CLASS
#define EV_JOB_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_JOB, EvJobClass))
Definition at line 85 of file ev-jobs.h.
EV_JOB_LAYERS
#define EV_JOB_LAYERS (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_LAYERS, EvJobLayers))
Definition at line 143 of file ev-jobs.h.
EV_JOB_LAYERS_CLASS
#define EV_JOB_LAYERS_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_LAYERS, EvJobLayersClass))
Definition at line 144 of file ev-jobs.h.
EV_JOB_LINKS
#define EV_JOB_LINKS (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_LINKS, EvJobLinks))
Definition at line 88 of file ev-jobs.h.
EV_JOB_LINKS_CLASS
#define EV_JOB_LINKS_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_LINKS, EvJobLinksClass))
Definition at line 89 of file ev-jobs.h.
EV_JOB_LOAD
#define EV_JOB_LOAD (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_LOAD, EvJobLoad))
Definition at line 128 of file ev-jobs.h.
EV_JOB_LOAD_CLASS
#define EV_JOB_LOAD_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_LOAD, EvJobLoadClass))
Definition at line 129 of file ev-jobs.h.
EV_JOB_PAGE_DATA
#define EV_JOB_PAGE_DATA (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_PAGE_DATA, EvJobPageData))
Definition at line 108 of file ev-jobs.h.
EV_JOB_PAGE_DATA_CLASS
#define EV_JOB_PAGE_DATA_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_PAGE_DATA, EvJobPageDataClass))
Definition at line 109 of file ev-jobs.h.
EV_JOB_PRINT
#define EV_JOB_PRINT (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_PRINT, EvJobPrint))
Definition at line 153 of file ev-jobs.h.
EV_JOB_PRINT_CLASS
#define EV_JOB_PRINT_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_PRINT, EvJobPrintClass))
Definition at line 154 of file ev-jobs.h.
EV_JOB_RENDER
#define EV_JOB_RENDER (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_RENDER, EvJobRender))
Definition at line 103 of file ev-jobs.h.
EV_JOB_RENDER_CLASS
#define EV_JOB_RENDER_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_RENDER, EvJobRenderClass))
Definition at line 104 of file ev-jobs.h.
EV_JOB_SAVE
#define EV_JOB_SAVE (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_SAVE, EvJobSave))
Definition at line 133 of file ev-jobs.h.
EV_JOB_SAVE_CLASS
#define EV_JOB_SAVE_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_SAVE, EvJobSaveClass))
Definition at line 134 of file ev-jobs.h.
EV_JOB_THUMBNAIL
#define EV_JOB_THUMBNAIL (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_THUMBNAIL, EvJobThumbnail))
Definition at line 113 of file ev-jobs.h.
EV_JOB_THUMBNAIL_CLASS
#define EV_JOB_THUMBNAIL_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_THUMBNAIL, EvJobThumbnailClass))
Definition at line 114 of file ev-jobs.h.
EV_JOB_WEB_THUMBNAIL
#define EV_JOB_WEB_THUMBNAIL (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_JOB_WEB_THUMBNAIL, EvJobWebThumbnail))
Definition at line 118 of file ev-jobs.h.
EV_JOB_WEB_THUMBNAIL_CLASS
#define EV_JOB_WEB_THUMBNAIL_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_JOB_WEB_THUMBNAIL, EvJobWebThumbnailClass))
Definition at line 119 of file ev-jobs.h.
EV_TYPE_JOB
#define EV_TYPE_JOB (ev_job_get_type())
Definition at line 81 of file ev-jobs.h.
EV_TYPE_JOB_ANNOTS
#define EV_TYPE_JOB_ANNOTS (ev_job_annots_get_type())
Definition at line 97 of file ev-jobs.h.
EV_TYPE_JOB_ATTACHMENTS
#define EV_TYPE_JOB_ATTACHMENTS (ev_job_attachments_get_type())
Definition at line 92 of file ev-jobs.h.
EV_TYPE_JOB_EXPORT
#define EV_TYPE_JOB_EXPORT (ev_job_export_get_type())
Definition at line 147 of file ev-jobs.h.
EV_TYPE_JOB_FIND
#define EV_TYPE_JOB_FIND (ev_job_find_get_type())
Definition at line 137 of file ev-jobs.h.
EV_TYPE_JOB_FONTS
#define EV_TYPE_JOB_FONTS (ev_job_fonts_get_type())
Definition at line 122 of file ev-jobs.h.
EV_TYPE_JOB_LAYERS
#define EV_TYPE_JOB_LAYERS (ev_job_layers_get_type())
Definition at line 142 of file ev-jobs.h.
EV_TYPE_JOB_LINKS
#define EV_TYPE_JOB_LINKS (ev_job_links_get_type())
Definition at line 87 of file ev-jobs.h.
EV_TYPE_JOB_LOAD
#define EV_TYPE_JOB_LOAD (ev_job_load_get_type())
Definition at line 127 of file ev-jobs.h.
EV_TYPE_JOB_PAGE_DATA
#define EV_TYPE_JOB_PAGE_DATA (ev_job_page_data_get_type())
Definition at line 107 of file ev-jobs.h.
EV_TYPE_JOB_PRINT
#define EV_TYPE_JOB_PRINT (ev_job_print_get_type())
Definition at line 152 of file ev-jobs.h.
EV_TYPE_JOB_RENDER
#define EV_TYPE_JOB_RENDER (ev_job_render_get_type())
Definition at line 102 of file ev-jobs.h.
EV_TYPE_JOB_SAVE
#define EV_TYPE_JOB_SAVE (ev_job_save_get_type())
Definition at line 132 of file ev-jobs.h.
EV_TYPE_JOB_THUMBNAIL
#define EV_TYPE_JOB_THUMBNAIL (ev_job_thumbnail_get_type())
Definition at line 112 of file ev-jobs.h.
EV_TYPE_JOB_WEB_THUMBNAIL
#define EV_TYPE_JOB_WEB_THUMBNAIL (ev_job_web_thumbnail_get_type())
Definition at line 117 of file ev-jobs.h.
Typedef Documentation
EvJob
typedef struct _EvJob EvJob
Definition at line 36 of file ev-jobs.h.
EvJobAnnots
typedef struct _EvJobAnnots EvJobAnnots
Definition at line 57 of file ev-jobs.h.
EvJobAnnotsClass
typedef struct _EvJobAnnotsClass EvJobAnnotsClass
Definition at line 58 of file ev-jobs.h.
EvJobAttachments
typedef struct _EvJobAttachments EvJobAttachments
Definition at line 54 of file ev-jobs.h.
EvJobAttachmentsClass
typedef struct _EvJobAttachmentsClass EvJobAttachmentsClass
Definition at line 55 of file ev-jobs.h.
EvJobClass
typedef struct _EvJobClass EvJobClass
Definition at line 37 of file ev-jobs.h.
EvJobExport
typedef struct _EvJobExport EvJobExport
Definition at line 75 of file ev-jobs.h.
EvJobExportClass
typedef struct _EvJobExportClass EvJobExportClass
Definition at line 76 of file ev-jobs.h.
EvJobFind
typedef struct _EvJobFind EvJobFind
Definition at line 69 of file ev-jobs.h.
EvJobFindClass
typedef struct _EvJobFindClass EvJobFindClass
Definition at line 70 of file ev-jobs.h.
EvJobFonts
typedef struct _EvJobFonts EvJobFonts
Definition at line 60 of file ev-jobs.h.
EvJobFontsClass
typedef struct _EvJobFontsClass EvJobFontsClass
Definition at line 61 of file ev-jobs.h.
EvJobLayers
typedef struct _EvJobLayers EvJobLayers
Definition at line 72 of file ev-jobs.h.
EvJobLayersClass
typedef struct _EvJobLayersClass EvJobLayersClass
Definition at line 73 of file ev-jobs.h.
EvJobLinks
typedef struct _EvJobLinks EvJobLinks
Definition at line 51 of file ev-jobs.h.
EvJobLinksClass
typedef struct _EvJobLinksClass EvJobLinksClass
Definition at line 52 of file ev-jobs.h.
EvJobLoad
typedef struct _EvJobLoad EvJobLoad
Definition at line 63 of file ev-jobs.h.
EvJobLoadClass
typedef struct _EvJobLoadClass EvJobLoadClass
Definition at line 64 of file ev-jobs.h.
EvJobPageData
typedef struct _EvJobPageData EvJobPageData
Definition at line 42 of file ev-jobs.h.
EvJobPageDataClass
typedef struct _EvJobPageDataClass EvJobPageDataClass
Definition at line 43 of file ev-jobs.h.
EvJobPrint
typedef struct _EvJobPrint EvJobPrint
Definition at line 78 of file ev-jobs.h.
EvJobPrintClass
typedef struct _EvJobPrintClass EvJobPrintClass
Definition at line 79 of file ev-jobs.h.
EvJobRender
typedef struct _EvJobRender EvJobRender
Definition at line 39 of file ev-jobs.h.
EvJobRenderClass
typedef struct _EvJobRenderClass EvJobRenderClass
Definition at line 40 of file ev-jobs.h.
EvJobSave
typedef struct _EvJobSave EvJobSave
Definition at line 66 of file ev-jobs.h.
EvJobSaveClass
typedef struct _EvJobSaveClass EvJobSaveClass
Definition at line 67 of file ev-jobs.h.
EvJobThumbnail
typedef struct _EvJobThumbnail EvJobThumbnail
Definition at line 45 of file ev-jobs.h.
EvJobThumbnailClass
typedef struct _EvJobThumbnailClass EvJobThumbnailClass
Definition at line 46 of file ev-jobs.h.
EvJobWebThumbnail
typedef struct _EvJobWebThumbnail EvJobWebThumbnail
Definition at line 48 of file ev-jobs.h.
EvJobWebThumbnailClass
typedef struct _EvJobWebThumbnailClass EvJobWebThumbnailClass
Definition at line 49 of file ev-jobs.h.
Enumeration Type Documentation
EvJobPageDataFlags
enum EvJobPageDataFlags
Enumerator
EV_PAGE_DATA_INCLUDE_NONE
EV_PAGE_DATA_INCLUDE_LINKS
EV_PAGE_DATA_INCLUDE_TEXT
EV_PAGE_DATA_INCLUDE_TEXT_MAPPING
EV_PAGE_DATA_INCLUDE_TEXT_LAYOUT
EV_PAGE_DATA_INCLUDE_TEXT_ATTRS
EV_PAGE_DATA_INCLUDE_TEXT_LOG_ATTRS
EV_PAGE_DATA_INCLUDE_IMAGES
EV_PAGE_DATA_INCLUDE_FORMS
EV_PAGE_DATA_INCLUDE_ANNOTS
EV_PAGE_DATA_INCLUDE_ALL
Definition at line 255 of file ev-jobs.h.
EvJobRunMode
enum EvJobRunMode
Enumerator
EV_JOB_RUN_THREAD
EV_JOB_RUN_MAIN_LOOP
Definition at line 157 of file ev-jobs.h.
Function Documentation
ev_job_annots_get_type()
GType ev_job_annots_get_type (void)
ev_job_annots_new()
EvJob * ev_job_annots_new (EvDocument * document)
Definition at line 528 of file ev-jobs.c.
References DEBUG_JOBS, _EvJob::document, EV_TYPE_JOB_ANNOTS, and NULL.
ev_job_attachments_get_type()
GType ev_job_attachments_get_type (void)
ev_job_attachments_new()
EvJob * ev_job_attachments_new (EvDocument * document)
Definition at line 449 of file ev-jobs.c.
References DEBUG_JOBS, _EvJob::document, EV_TYPE_JOB_ATTACHMENTS, and NULL.
ev_job_cancel()
void ev_job_cancel (EvJob * job)
Definition at line 193 of file ev-jobs.c.
References _EvJob::cancellable, CANCELLED, _EvJob::cancelled, DEBUG_JOBS, EV_GET_TYPE_NAME, _EvJob::finished, _EvJob::idle_finished_id, and TRUE.
Referenced by G_DEFINE_TYPE_EXTENDED().
ev_job_export_get_type()
GType ev_job_export_get_type (void)
ev_job_export_new()
EvJob * ev_job_export_new (EvDocument * document)
Definition at line 1549 of file ev-jobs.c.
References DEBUG_JOBS, _EvJob::document, EV_TYPE_JOB_EXPORT, and NULL.
ev_job_export_set_page()
void ev_job_export_set_page (EvJobExport * job, gint page)
Definition at line 1562 of file ev-jobs.c.
References _EvJobExport::page.
ev_job_failed()
void ev_job_failed (EvJob * job, GQuark domain, gint code, const gchar * format, ...)
Definition at line 212 of file ev-jobs.c.
References DEBUG_JOBS, _EvJob::error, EV_GET_TYPE_NAME, _EvJob::failed, _EvJob::finished, message(), and TRUE.
ev_job_failed_from_error()
void ev_job_failed_from_error (EvJob * job, GError * error)
ev_job_failed_from_error: @job: an EvJob @error: a #GError
Rename to: ev_job_failed
Definition at line 246 of file ev-jobs.c.
References DEBUG_JOBS, _EvJob::error, error, EV_GET_TYPE_NAME, _EvJob::failed, _EvJob::finished, and TRUE.
ev_job_find_get_n_results()
gint ev_job_find_get_n_results (EvJobFind * job, gint pages)
Definition at line 1367 of file ev-jobs.c.
References EV_JOB, _EvJobFind::pages, and _EvJobFind::results.
ev_job_find_get_progress()
gdouble ev_job_find_get_progress (EvJobFind * job)
Definition at line 1379 of file ev-jobs.c.
References _EvJobFind::current_page, EV_JOB, ev_job_is_finished(), _EvJobFind::n_pages, and _EvJobFind::start_page.
ev_job_find_get_results()
GList ** ev_job_find_get_results (EvJobFind * job)
ev_job_find_get_results: (skip) @job: an EvJobFind
Returns: a #GList of #GLists containing #EvRectangles
Definition at line 1410 of file ev-jobs.c.
References _EvJobFind::pages.
ev_job_find_get_type()
GType ev_job_find_get_type (void)
ev_job_find_has_results()
gboolean ev_job_find_has_results (EvJobFind * job)
Definition at line 1398 of file ev-jobs.c.
References _EvJobFind::has_results.
ev_job_find_new()
EvJob * ev_job_find_new (EvDocument * document, gint start_page, gint n_pages, const gchar * text, gboolean case_sensitive)
Definition at line 1336 of file ev-jobs.c.
References _EvJobFind::case_sensitive, _EvJobFind::current_page, DEBUG_JOBS, EV_JOB, EV_TYPE_JOB_FIND, FALSE, _EvJobFind::has_results, _EvDocument::iswebdocument, _EvJobFind::n_pages, NULL, _EvJobFind::pages, _EvJobFind::results, _EvJobFind::start_page, and _EvJobFind::text.
ev_job_fonts_get_type()
GType ev_job_fonts_get_type (void)
ev_job_fonts_new()
EvJob * ev_job_fonts_new (EvDocument * document)
Definition at line 942 of file ev-jobs.c.
References DEBUG_JOBS, EV_JOB, EV_TYPE_JOB_FONTS, and NULL.
Referenced by ev_properties_fonts_set_document().
ev_job_get_run_mode()
EvJobRunMode ev_job_get_run_mode (EvJob * job)
Definition at line 285 of file ev-jobs.c.
References _EvJob::run_mode.
Referenced by ev_job_scheduler_push_job(), and ev_job_scheduler_update_job().
ev_job_get_type()
GType ev_job_get_type (void)
ev_job_is_failed()
gboolean ev_job_is_failed (EvJob * job)
Definition at line 279 of file ev-jobs.c.
References _EvJob::failed.
ev_job_is_finished()
gboolean ev_job_is_finished (EvJob * job)
Definition at line 273 of file ev-jobs.c.
References _EvJob::finished.
Referenced by ev_job_find_get_progress().
ev_job_layers_get_type()
GType ev_job_layers_get_type (void)
ev_job_layers_new()
EvJob * ev_job_layers_new (EvDocument * document)
Definition at line 1467 of file ev-jobs.c.
References DEBUG_JOBS, _EvJob::document, EV_TYPE_JOB_LAYERS, and NULL.
ev_job_links_get_type()
GType ev_job_links_get_type (void)
ev_job_links_new()
EvJob * ev_job_links_new (EvDocument * document)
Definition at line 383 of file ev-jobs.c.
References DEBUG_JOBS, _EvJob::document, EV_TYPE_JOB_LINKS, and NULL.
ev_job_load_get_type()
GType ev_job_load_get_type (void)
ev_job_load_new()
EvJob * ev_job_load_new (const gchar * uri)
Definition at line 1041 of file ev-jobs.c.
References DEBUG_JOBS, EV_JOB, EV_TYPE_JOB_LOAD, NULL, and _EvJobLoad::uri.
Referenced by ev_window_open_uri().
ev_job_load_set_password()
void ev_job_load_set_password (EvJobLoad * job, const gchar * password)
Definition at line 1064 of file ev-jobs.c.
References DEBUG_JOBS, NULL, and _EvJobLoad::password.
ev_job_load_set_uri()
void ev_job_load_set_uri (EvJobLoad * load, const gchar * uri)
Definition at line 1054 of file ev-jobs.c.
References DEBUG_JOBS, and _EvJobLoad::uri.
ev_job_page_data_get_type()
GType ev_job_page_data_get_type (void)
ev_job_page_data_new()
EvJob * ev_job_page_data_new (EvDocument * document, gint page, EvJobPageDataFlags flags)
Definition at line 782 of file ev-jobs.c.
References DEBUG_JOBS, EV_JOB, EV_TYPE_JOB_PAGE_DATA, _EvJobPageData::flags, NULL, and _EvJobPageData::page.
ev_job_print_get_type()
GType ev_job_print_get_type (void)
ev_job_print_new()
EvJob * ev_job_print_new (EvDocument * document)
Definition at line 1648 of file ev-jobs.c.
References DEBUG_JOBS, _EvJob::document, EV_TYPE_JOB_PRINT, and NULL.
ev_job_print_set_cairo()
void ev_job_print_set_cairo (EvJobPrint * job, cairo_t * cr)
Definition at line 1668 of file ev-jobs.c.
References _EvJobPrint::cr, and NULL.
ev_job_print_set_page()
void ev_job_print_set_page (EvJobPrint * job, gint page)
Definition at line 1661 of file ev-jobs.c.
References _EvJobPrint::page.
ev_job_render_get_type()
GType ev_job_render_get_type (void)
ev_job_render_new()
EvJob * ev_job_render_new (EvDocument * document, gint page, gint rotation, gdouble scale, gint width, gint height)
Definition at line 671 of file ev-jobs.c.
References DEBUG_JOBS, EV_JOB, EV_TYPE_JOB_RENDER, NULL, _EvJobRender::page, _EvJobRender::rotation, _EvJobRender::scale, _EvJobRender::target_height, and _EvJobRender::target_width.
ev_job_render_set_selection_info()
void ev_job_render_set_selection_info (EvJobRender * job, EvRectangle * selection_points, EvSelectionStyle selection_style, GdkColor * text, GdkColor * base)
Definition at line 695 of file ev-jobs.c.
References _EvJobRender::base, _EvJobRender::include_selection, _EvJobRender::selection_points, _EvJobRender::selection_style, _EvJobRender::text, and TRUE.
ev_job_run()
gboolean ev_job_run (EvJob * job)
Definition at line 185 of file ev-jobs.c.
ev_job_save_get_type()
GType ev_job_save_get_type (void)
ev_job_save_new()
EvJob * ev_job_save_new (EvDocument * document, const gchar * uri, const gchar * document_uri)
Definition at line 1204 of file ev-jobs.c.
References DEBUG_JOBS, _EvJobSave::document_uri, EV_JOB, EV_TYPE_JOB_SAVE, NULL, and _EvJobSave::uri.
ev_job_set_run_mode()
void ev_job_set_run_mode (EvJob * job, EvJobRunMode run_mode)
Definition at line 291 of file ev-jobs.c.
References _EvJob::run_mode.
ev_job_succeeded()
void ev_job_succeeded (EvJob * job)
Definition at line 261 of file ev-jobs.c.
References DEBUG_JOBS, EV_GET_TYPE_NAME, _EvJob::failed, FALSE, and _EvJob::finished.
ev_job_thumbnail_get_type()
GType ev_job_thumbnail_get_type (void)
ev_job_thumbnail_new()
EvJob * ev_job_thumbnail_new (EvDocument * document, gint page, gint rotation, gdouble scale)
Definition at line 861 of file ev-jobs.c.
References DEBUG_JOBS, EV_JOB, EV_TYPE_JOB_THUMBNAIL, NULL, _EvJobThumbnail::page, _EvJobThumbnail::rotation, and _EvJobThumbnail::scale.