MATE Desktop Environment: ev-link-dest.h File Reference
ev-link-dest.h File Reference
#include <glib-object.h>
Macros
#define EV_TYPE_LINK_DEST (ev_link_dest_get_type())
#define EV_LINK_DEST(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_LINK_DEST, EvLinkDest))
#define EV_LINK_DEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_LINK_DEST, EvLinkDestClass))
#define EV_IS_LINK_DEST(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_LINK_DEST))
#define EV_IS_LINK_DEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_LINK_DEST))
#define EV_LINK_DEST_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_LINK_DEST, EvLinkDestClass))
Typedefs
typedef struct _EvLinkDest EvLinkDest
typedef struct _EvLinkDestClass EvLinkDestClass
typedef struct _EvLinkDestPrivate EvLinkDestPrivate
Enumerations
enum EvLinkDestType {
EV_LINK_DEST_TYPE_PAGE , EV_LINK_DEST_TYPE_XYZ , EV_LINK_DEST_TYPE_FIT , EV_LINK_DEST_TYPE_FITH ,
EV_LINK_DEST_TYPE_FITV , EV_LINK_DEST_TYPE_FITR , EV_LINK_DEST_TYPE_NAMED , EV_LINK_DEST_TYPE_PAGE_LABEL ,
EV_LINK_DEST_TYPE_HLINK , EV_LINK_DEST_TYPE_UNKNOWN
}
Functions
GType ev_link_dest_get_type (void)
EvLinkDestType ev_link_dest_get_dest_type (EvLinkDest *self)
gint ev_link_dest_get_page (EvLinkDest *self)
gdouble ev_link_dest_get_top (EvLinkDest *self, gboolean *change_top)
gdouble ev_link_dest_get_left (EvLinkDest *self, gboolean *change_left)
gdouble ev_link_dest_get_bottom (EvLinkDest *self)
gdouble ev_link_dest_get_right (EvLinkDest *self)
gdouble ev_link_dest_get_zoom (EvLinkDest *self, gboolean *change_zoom)
const gchar * ev_link_dest_get_named_dest (EvLinkDest *self)
const gchar * ev_link_dest_get_page_label (EvLinkDest *self)
EvLinkDest * ev_link_dest_new_page (gint page)
EvLinkDest * ev_link_dest_new_xyz (gint page, gdouble left, gdouble top, gdouble zoom, gboolean change_left, gboolean change_top, gboolean change_zoom)
EvLinkDest * ev_link_dest_new_fit (gint page)
EvLinkDest * ev_link_dest_new_fith (gint page, gdouble top, gboolean change_top)
EvLinkDest * ev_link_dest_new_fitv (gint page, gdouble left, gboolean change_left)
EvLinkDest * ev_link_dest_new_fitr (gint page, gdouble left, gdouble bottom, gdouble right, gdouble top)
EvLinkDest * ev_link_dest_new_named (const gchar *named_dest)
EvLinkDest * ev_link_dest_new_page_label (const gchar *page_label)
EvLinkDest * ev_link_dest_new_hlink (const gchar *hlink, gint page)
Macro Definition Documentation
EV_IS_LINK_DEST
#define EV_IS_LINK_DEST (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_LINK_DEST))
Definition at line 39 of file ev-link-dest.h.
EV_IS_LINK_DEST_CLASS
#define EV_IS_LINK_DEST_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_LINK_DEST))
Definition at line 40 of file ev-link-dest.h.
EV_LINK_DEST
#define EV_LINK_DEST (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_LINK_DEST, EvLinkDest))
Definition at line 37 of file ev-link-dest.h.
EV_LINK_DEST_CLASS
#define EV_LINK_DEST_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_LINK_DEST, EvLinkDestClass))
Definition at line 38 of file ev-link-dest.h.
EV_LINK_DEST_GET_CLASS
#define EV_LINK_DEST_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_LINK_DEST, EvLinkDestClass))
Definition at line 41 of file ev-link-dest.h.
EV_TYPE_LINK_DEST
#define EV_TYPE_LINK_DEST (ev_link_dest_get_type())
Definition at line 36 of file ev-link-dest.h.
Typedef Documentation
EvLinkDest
typedef struct _EvLinkDest EvLinkDest
Definition at line 32 of file ev-link-dest.h.
EvLinkDestClass
typedef struct _EvLinkDestClass EvLinkDestClass
Definition at line 33 of file ev-link-dest.h.
EvLinkDestPrivate
typedef struct _EvLinkDestPrivate EvLinkDestPrivate
Definition at line 34 of file ev-link-dest.h.
Enumeration Type Documentation
EvLinkDestType
enum EvLinkDestType
Enumerator
EV_LINK_DEST_TYPE_PAGE
EV_LINK_DEST_TYPE_XYZ
EV_LINK_DEST_TYPE_FIT
EV_LINK_DEST_TYPE_FITH
EV_LINK_DEST_TYPE_FITV
EV_LINK_DEST_TYPE_FITR
EV_LINK_DEST_TYPE_NAMED
EV_LINK_DEST_TYPE_PAGE_LABEL
EV_LINK_DEST_TYPE_HLINK
EV_LINK_DEST_TYPE_UNKNOWN
Definition at line 43 of file ev-link-dest.h.
Function Documentation
ev_link_dest_get_bottom()
gdouble ev_link_dest_get_bottom (EvLinkDest * self)
Definition at line 112 of file ev-link-dest.c.
References EV_IS_LINK_DEST.
ev_link_dest_get_dest_type()
EvLinkDestType ev_link_dest_get_dest_type (EvLinkDest * self)
Definition at line 72 of file ev-link-dest.c.
References EV_IS_LINK_DEST.
Referenced by ev_document_links_get_dest_page(), and ev_document_links_get_dest_page_label().
ev_link_dest_get_left()
gdouble ev_link_dest_get_left (EvLinkDest * self, gboolean * change_left)
Definition at line 100 of file ev-link-dest.c.
References EV_DEST_CHANGE_LEFT, and EV_IS_LINK_DEST.
ev_link_dest_get_named_dest()
const gchar * ev_link_dest_get_named_dest (EvLinkDest * self)
Definition at line 140 of file ev-link-dest.c.
References EV_IS_LINK_DEST, and NULL.
Referenced by ev_document_links_get_dest_page().
ev_link_dest_get_page()
gint ev_link_dest_get_page (EvLinkDest * self)
Definition at line 80 of file ev-link-dest.c.
References EV_IS_LINK_DEST.
Referenced by ev_document_links_get_dest_page().
ev_link_dest_get_page_label()
const gchar * ev_link_dest_get_page_label (EvLinkDest * self)
Definition at line 148 of file ev-link-dest.c.
References EV_IS_LINK_DEST, and NULL.
Referenced by ev_document_links_get_dest_page(), and ev_document_links_get_dest_page_label().
ev_link_dest_get_right()
gdouble ev_link_dest_get_right (EvLinkDest * self)
Definition at line 120 of file ev-link-dest.c.
References EV_IS_LINK_DEST.
ev_link_dest_get_top()
gdouble ev_link_dest_get_top (EvLinkDest * self, gboolean * change_top)
Definition at line 88 of file ev-link-dest.c.
References EV_DEST_CHANGE_TOP, and EV_IS_LINK_DEST.
ev_link_dest_get_type()
GType ev_link_dest_get_type (void)
ev_link_dest_get_zoom()
gdouble ev_link_dest_get_zoom (EvLinkDest * self, gboolean * change_zoom)
Definition at line 128 of file ev-link-dest.c.
References EV_DEST_CHANGE_ZOOM, and EV_IS_LINK_DEST.
ev_link_dest_new_fit()
EvLinkDest * ev_link_dest_new_fit (gint page)
Definition at line 426 of file ev-link-dest.c.
References EV_LINK_DEST, EV_LINK_DEST_TYPE_FIT, EV_TYPE_LINK_DEST, and NULL.
ev_link_dest_new_fith()
EvLinkDest * ev_link_dest_new_fith (gint page, gdouble top, gboolean change_top)
Definition at line 435 of file ev-link-dest.c.
References EV_DEST_CHANGE_TOP, EV_LINK_DEST, EV_LINK_DEST_TYPE_FITH, EV_TYPE_LINK_DEST, and NULL.
ev_link_dest_new_fitr()
EvLinkDest * ev_link_dest_new_fitr (gint page, gdouble left, gdouble bottom, gdouble right, gdouble top)
Definition at line 471 of file ev-link-dest.c.
References EV_DEST_CHANGE_LEFT, EV_DEST_CHANGE_TOP, EV_LINK_DEST, EV_LINK_DEST_TYPE_FITR, EV_TYPE_LINK_DEST, and NULL.
ev_link_dest_new_fitv()
EvLinkDest * ev_link_dest_new_fitv (gint page, gdouble left, gboolean change_left)
Definition at line 453 of file ev-link-dest.c.
References EV_DEST_CHANGE_LEFT, EV_LINK_DEST, EV_LINK_DEST_TYPE_FITV, EV_TYPE_LINK_DEST, and NULL.
ev_link_dest_new_hlink()
EvLinkDest * ev_link_dest_new_hlink (const gchar * hlink, gint page)
Definition at line 509 of file ev-link-dest.c.
References EV_LINK_DEST, EV_LINK_DEST_TYPE_HLINK, EV_TYPE_LINK_DEST, and NULL.
ev_link_dest_new_named()
EvLinkDest * ev_link_dest_new_named (const gchar * named_dest)
Definition at line 491 of file ev-link-dest.c.
References EV_LINK_DEST, EV_LINK_DEST_TYPE_NAMED, EV_TYPE_LINK_DEST, and NULL.
ev_link_dest_new_page()
EvLinkDest * ev_link_dest_new_page (gint page)
Definition at line 389 of file ev-link-dest.c.
References EV_LINK_DEST, EV_LINK_DEST_TYPE_PAGE, EV_TYPE_LINK_DEST, and NULL.
ev_link_dest_new_page_label()
EvLinkDest * ev_link_dest_new_page_label (const gchar * page_label)
Definition at line 500 of file ev-link-dest.c.
References EV_LINK_DEST, EV_LINK_DEST_TYPE_PAGE_LABEL, EV_TYPE_LINK_DEST, and NULL.
ev_link_dest_new_xyz()
EvLinkDest * ev_link_dest_new_xyz (gint page, gdouble left, gdouble top, gdouble zoom, gboolean change_left, gboolean change_top, gboolean change_zoom)
Definition at line 398 of file ev-link-dest.c.
References EV_DEST_CHANGE_LEFT, EV_DEST_CHANGE_TOP, EV_DEST_CHANGE_ZOOM, EV_LINK_DEST, EV_LINK_DEST_TYPE_XYZ, EV_TYPE_LINK_DEST, and NULL.