MATE Desktop Environment: ev-module.c File Reference
ev-module.c File Reference
#include "config.h"
#include "ev-module.h"
#include <gmodule.h>
Typedefs
typedef struct _EvModuleClass EvModuleClass
typedef GType(* EvModuleRegisterFunc) (GTypeModule *)
Functions
const gchar * ev_module_get_path (EvModule *module)
GObject * ev_module_new_object (EvModule *module)
GType ev_module_get_object_type (EvModule *module)
EvModule * ev_module_new (const gchar *path, gboolean resident)
Typedef Documentation
EvModuleClass
typedef struct _EvModuleClass EvModuleClass
Definition at line 47 of file ev-module.c.
EvModuleRegisterFunc
typedef GType(* EvModuleRegisterFunc) (GTypeModule *)
Definition at line 63 of file ev-module.c.
Function Documentation
ev_module_get_object_type()
GType ev_module_get_object_type (EvModule * module)
Definition at line 144 of file ev-module.c.
References EV_IS_MODULE.
ev_module_get_path()
const gchar * ev_module_get_path (EvModule * module)
Definition at line 125 of file ev-module.c.
References EV_IS_MODULE, and NULL.
Referenced by ev_backends_manager_get_document().
ev_module_new()
EvModule * ev_module_new (const gchar * path, gboolean resident)
Definition at line 179 of file ev-module.c.
References EV_TYPE_MODULE, and NULL.
Referenced by ev_backends_manager_get_document().
ev_module_new_object()
GObject * ev_module_new_object (EvModule * module)
Definition at line 133 of file ev-module.c.
References EV_IS_MODULE, and NULL.
Referenced by ev_backends_manager_get_document().