MATE Desktop Environment: ev-module.h File Reference
ev-module.h File Reference
#include <glib-object.h>
Macros
#define EV_TYPE_MODULE (ev_module_get_type ())
#define EV_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EV_TYPE_MODULE, EvModule))
#define EV_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EV_TYPE_MODULE, EvModuleClass))
#define EV_IS_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EV_TYPE_MODULE))
#define EV_IS_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((obj), EV_TYPE_MODULE))
#define EV_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), EV_TYPE_MODULE, EvModuleClass))
Typedefs
typedef struct _EvModule EvModule
Functions
GType ev_module_get_type (void)
EvModule * ev_module_new (const gchar *path, gboolean resident)
const gchar * ev_module_get_path (EvModule *module)
GObject * ev_module_new_object (EvModule *module)
GType ev_module_get_object_type (EvModule *module)
Macro Definition Documentation
EV_IS_MODULE
#define EV_IS_MODULE (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EV_TYPE_MODULE))
Definition at line 55 of file ev-module.h.
EV_IS_MODULE_CLASS
#define EV_IS_MODULE_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((obj), EV_TYPE_MODULE))
Definition at line 56 of file ev-module.h.
EV_MODULE
#define EV_MODULE (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EV_TYPE_MODULE, EvModule))
Definition at line 53 of file ev-module.h.
EV_MODULE_CLASS
#define EV_MODULE_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EV_TYPE_MODULE, EvModuleClass))
Definition at line 54 of file ev-module.h.
EV_MODULE_GET_CLASS
#define EV_MODULE_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS((obj), EV_TYPE_MODULE, EvModuleClass))
Definition at line 57 of file ev-module.h.
EV_TYPE_MODULE
#define EV_TYPE_MODULE (ev_module_get_type ())
Definition at line 52 of file ev-module.h.
Typedef Documentation
EvModule
typedef struct _EvModule EvModule
Definition at line 59 of file ev-module.h.
Function Documentation
ev_module_get_object_type()
GType ev_module_get_object_type (EvModule * module)
Definition at line 144 of file ev-module.c.
References EV_IS_MODULE.
ev_module_get_path()
const gchar * ev_module_get_path (EvModule * module)
Definition at line 125 of file ev-module.c.
References EV_IS_MODULE, and NULL.
Referenced by ev_backends_manager_get_document().
ev_module_get_type()
GType ev_module_get_type (void)
ev_module_new()
EvModule * ev_module_new (const gchar * path, gboolean resident)
Definition at line 179 of file ev-module.c.
References EV_TYPE_MODULE, and NULL.
Referenced by ev_backends_manager_get_document().
ev_module_new_object()
GObject * ev_module_new_object (EvModule * module)
Definition at line 133 of file ev-module.c.
References EV_IS_MODULE, and NULL.
Referenced by ev_backends_manager_get_document().