MATE Desktop Environment: ev-metadata.c File Reference
ev-metadata.c File Reference
#include <gio/gio.h>
#include <string.h>
#include "ev-metadata.h"
#include "ev-file-helpers.h"
Macros
#define EV_METADATA_NAMESPACE "metadata::atril"
Functions
EvMetadata * ev_metadata_new (GFile *file)
gboolean ev_metadata_is_empty (EvMetadata *metadata)
gboolean ev_metadata_get_string (EvMetadata *metadata, const gchar *key, gchar **value)
gboolean ev_metadata_set_string (EvMetadata *metadata, const gchar *key, const gchar *value)
gboolean ev_metadata_get_int (EvMetadata *metadata, const gchar *key, gint *value)
gboolean ev_metadata_set_int (EvMetadata *metadata, const gchar *key, gint value)
gboolean ev_metadata_get_double (EvMetadata *metadata, const gchar *key, gdouble *value)
gboolean ev_metadata_set_double (EvMetadata *metadata, const gchar *key, gdouble value)
gboolean ev_metadata_get_boolean (EvMetadata *metadata, const gchar *key, gboolean *value)
gboolean ev_metadata_set_boolean (EvMetadata *metadata, const gchar *key, gboolean value)
gboolean ev_metadata_has_key (EvMetadata *metadata, const gchar *key)
gboolean ev_is_metadata_supported_for_file (GFile *file)
Macro Definition Documentation
EV_METADATA_NAMESPACE
#define EV_METADATA_NAMESPACE "metadata::atril"
Definition at line 40 of file ev-metadata.c.
Function Documentation
ev_is_metadata_supported_for_file()
gboolean ev_is_metadata_supported_for_file (GFile * file)
Definition at line 305 of file ev-metadata.c.
References FALSE, NULL, and TRUE.
Referenced by ev_window_open_uri().
ev_metadata_get_boolean()
gboolean ev_metadata_get_boolean (EvMetadata * metadata, const gchar * key, gboolean * value)
Definition at line 276 of file ev-metadata.c.
References ev_metadata_get_int(), FALSE, key, and TRUE.
ev_metadata_get_double()
gboolean ev_metadata_get_double (EvMetadata * metadata, const gchar * key, gdouble * value)
Definition at line 244 of file ev-metadata.c.
References ev_metadata_get_string(), FALSE, key, and TRUE.
ev_metadata_get_int()
gboolean ev_metadata_get_int (EvMetadata * metadata, const gchar * key, gint * value)
Definition at line 212 of file ev-metadata.c.
References ev_metadata_get_string(), FALSE, key, and TRUE.
Referenced by ev_metadata_get_boolean().
ev_metadata_get_string()
gboolean ev_metadata_get_string (EvMetadata * metadata, const gchar * key, gchar ** value)
Definition at line 148 of file ev-metadata.c.
References FALSE, key, and TRUE.
Referenced by ev_metadata_get_double(), and ev_metadata_get_int().
ev_metadata_has_key()
gboolean ev_metadata_has_key (EvMetadata * metadata, const gchar * key)
Definition at line 298 of file ev-metadata.c.
References key, and NULL.
ev_metadata_is_empty()
gboolean ev_metadata_is_empty (EvMetadata * metadata)
Definition at line 142 of file ev-metadata.c.
ev_metadata_new()
EvMetadata * ev_metadata_new (GFile * file)
Definition at line 126 of file ev-metadata.c.
References ev_file_is_temp(), EV_METADATA, EV_TYPE_METADATA, and NULL.
Referenced by ev_window_open_uri().
ev_metadata_set_boolean()
gboolean ev_metadata_set_boolean (EvMetadata * metadata, const gchar * key, gboolean value)
Definition at line 290 of file ev-metadata.c.
References ev_metadata_set_string(), and key.
ev_metadata_set_double()
gboolean ev_metadata_set_double (EvMetadata * metadata, const gchar * key, gdouble value)
Definition at line 264 of file ev-metadata.c.
References ev_metadata_set_string(), and key.
ev_metadata_set_int()
gboolean ev_metadata_set_int (EvMetadata * metadata, const gchar * key, gint value)
Definition at line 232 of file ev-metadata.c.
References ev_metadata_set_string(), and key.
ev_metadata_set_string()
gboolean ev_metadata_set_string (EvMetadata * metadata, const gchar * key, const gchar * value)
Definition at line 176 of file ev-metadata.c.
References EV_METADATA_NAMESPACE, key, NULL, and TRUE.
Referenced by ev_metadata_set_boolean(), ev_metadata_set_double(), and ev_metadata_set_int().