MATE Desktop Environment: ev-message-area.h File Reference
ev-message-area.h File Reference
#include <gtk/gtk.h>
Classes
struct _EvMessageArea
struct _EvMessageAreaClass
Macros
#define EV_TYPE_MESSAGE_AREA (ev_message_area_get_type ())
#define EV_MESSAGE_AREA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EV_TYPE_MESSAGE_AREA, EvMessageArea))
#define EV_MESSAGE_AREA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EV_TYPE_MESSAGE_AREA, EvMessageAreaClass))
#define EV_IS_MESSAGE_AREA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EV_TYPE_MESSAGE_AREA))
#define EV_IS_MESSAGE_AREA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EV_TYPE_MESSAGE_AREA))
#define EV_MESSAGE_AREA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EV_TYPE_MESSAGE_AREA, EvMessageAreaClass))
Typedefs
typedef struct _EvMessageArea EvMessageArea
typedef struct _EvMessageAreaClass EvMessageAreaClass
typedef struct _EvMessageAreaPrivate EvMessageAreaPrivate
Functions
GType ev_message_area_get_type (void)
GtkWidget * ev_message_area_new (GtkMessageType type, const gchar *text, const gchar *first_button_text,...)
void ev_message_area_set_image (EvMessageArea *area, GtkWidget *image)
void ev_message_area_set_image_from_stock (EvMessageArea *area, const gchar *stock_id)
void ev_message_area_set_text (EvMessageArea *area, const gchar *str)
void ev_message_area_set_secondary_text (EvMessageArea *area, const gchar *str)
void _ev_message_area_add_buttons_valist (EvMessageArea *area, const gchar *first_button_text, va_list args)
GtkWidget * _ev_message_area_get_main_box (EvMessageArea *area)
Macro Definition Documentation
EV_IS_MESSAGE_AREA
#define EV_IS_MESSAGE_AREA (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EV_TYPE_MESSAGE_AREA))
Definition at line 34 of file ev-message-area.h.
EV_IS_MESSAGE_AREA_CLASS
#define EV_IS_MESSAGE_AREA_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EV_TYPE_MESSAGE_AREA))
Definition at line 35 of file ev-message-area.h.
EV_MESSAGE_AREA
#define EV_MESSAGE_AREA (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EV_TYPE_MESSAGE_AREA, EvMessageArea))
Definition at line 32 of file ev-message-area.h.
EV_MESSAGE_AREA_CLASS
#define EV_MESSAGE_AREA_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EV_TYPE_MESSAGE_AREA, EvMessageAreaClass))
Definition at line 33 of file ev-message-area.h.
EV_MESSAGE_AREA_GET_CLASS
#define EV_MESSAGE_AREA_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EV_TYPE_MESSAGE_AREA, EvMessageAreaClass))
Definition at line 36 of file ev-message-area.h.
EV_TYPE_MESSAGE_AREA
#define EV_TYPE_MESSAGE_AREA (ev_message_area_get_type ())
Definition at line 31 of file ev-message-area.h.
Typedef Documentation
EvMessageArea
typedef struct _EvMessageArea EvMessageArea
Definition at line 38 of file ev-message-area.h.
EvMessageAreaClass
typedef struct _EvMessageAreaClass EvMessageAreaClass
Definition at line 39 of file ev-message-area.h.
EvMessageAreaPrivate
typedef struct _EvMessageAreaPrivate EvMessageAreaPrivate
Definition at line 40 of file ev-message-area.h.
Function Documentation
_ev_message_area_add_buttons_valist()
void _ev_message_area_add_buttons_valist (EvMessageArea * area, const gchar * first_button_text, va_list args)
Definition at line 222 of file ev-message-area.c.
References NULL.
Referenced by ev_message_area_new(), and ev_progress_message_area_new().
_ev_message_area_get_main_box()
GtkWidget * _ev_message_area_get_main_box (EvMessageArea * area)
Definition at line 247 of file ev-message-area.c.
References _EvMessageArea::priv.
ev_message_area_get_type()
GType ev_message_area_get_type (void)
ev_message_area_new()
GtkWidget * ev_message_area_new (GtkMessageType type, const gchar * text, const gchar * first_button_text, ...)
Definition at line 253 of file ev-message-area.c.
References _ev_message_area_add_buttons_valist(), EV_MESSAGE_AREA, EV_TYPE_MESSAGE_AREA, NULL, and type.
ev_message_area_set_image()
void ev_message_area_set_image (EvMessageArea * area, GtkWidget * image)
Definition at line 278 of file ev-message-area.c.
References EV_IS_MESSAGE_AREA, and _EvMessageArea::priv.
ev_message_area_set_image_from_stock()
void ev_message_area_set_image_from_stock (EvMessageArea * area, const gchar * stock_id)
Definition at line 298 of file ev-message-area.c.
References EV_IS_MESSAGE_AREA, NULL, and _EvMessageArea::priv.
Referenced by ev_progress_message_area_new().
ev_message_area_set_secondary_text()
void ev_message_area_set_secondary_text (EvMessageArea * area, const gchar * str)
Definition at line 329 of file ev-message-area.c.
References EV_IS_MESSAGE_AREA, NULL, and _EvMessageArea::priv.
ev_message_area_set_text()
void ev_message_area_set_text (EvMessageArea * area, const gchar * str)
Definition at line 310 of file ev-message-area.c.
References EV_IS_MESSAGE_AREA, NULL, and _EvMessageArea::priv.