MATE Desktop Environment: ev-message-area.c File Reference
ev-message-area.c File Reference
#include <config.h>
#include "ev-message-area.h"
Enumerations
enum { PROP_0 , PROP_TEXT , PROP_SECONDARY_TEXT , PROP_IMAGE }
Functions
void _ev_message_area_add_buttons_valist (EvMessageArea *area, const gchar *first_button_text, va_list args)
GtkWidget * _ev_message_area_get_main_box (EvMessageArea *area)
GtkWidget * ev_message_area_new (GtkMessageType type, const gchar *text, const gchar *first_button_text,...)
void ev_message_area_set_image (EvMessageArea *area, GtkWidget *image)
void ev_message_area_set_image_from_stock (EvMessageArea *area, const gchar *icon_name)
void ev_message_area_set_text (EvMessageArea *area, const gchar *str)
void ev_message_area_set_secondary_text (EvMessageArea *area, const gchar *str)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_TEXT
PROP_SECONDARY_TEXT
PROP_IMAGE
Definition at line 37 of file ev-message-area.c.
Function Documentation
_ev_message_area_add_buttons_valist()
void _ev_message_area_add_buttons_valist (EvMessageArea * area, const gchar * first_button_text, va_list args)
Definition at line 222 of file ev-message-area.c.
References NULL.
Referenced by ev_message_area_new(), and ev_progress_message_area_new().
_ev_message_area_get_main_box()
GtkWidget * _ev_message_area_get_main_box (EvMessageArea * area)
Definition at line 247 of file ev-message-area.c.
References _EvMessageArea::priv.
ev_message_area_new()
GtkWidget * ev_message_area_new (GtkMessageType type, const gchar * text, const gchar * first_button_text, ...)
Definition at line 253 of file ev-message-area.c.
References _ev_message_area_add_buttons_valist(), EV_MESSAGE_AREA, EV_TYPE_MESSAGE_AREA, NULL, and type.
ev_message_area_set_image()
void ev_message_area_set_image (EvMessageArea * area, GtkWidget * image)
Definition at line 278 of file ev-message-area.c.
References EV_IS_MESSAGE_AREA, and _EvMessageArea::priv.
ev_message_area_set_image_from_stock()
void ev_message_area_set_image_from_stock (EvMessageArea * area, const gchar * icon_name)
Definition at line 298 of file ev-message-area.c.
References EV_IS_MESSAGE_AREA, NULL, and _EvMessageArea::priv.
Referenced by ev_progress_message_area_new().
ev_message_area_set_secondary_text()
void ev_message_area_set_secondary_text (EvMessageArea * area, const gchar * str)
Definition at line 329 of file ev-message-area.c.
References EV_IS_MESSAGE_AREA, NULL, and _EvMessageArea::priv.
ev_message_area_set_text()
void ev_message_area_set_text (EvMessageArea * area, const gchar * str)
Definition at line 310 of file ev-message-area.c.
References EV_IS_MESSAGE_AREA, NULL, and _EvMessageArea::priv.