MATE Desktop Environment: ev-metadata.h File Reference
ev-metadata.h File Reference
#include <glib-object.h>
#include <gio/gio.h>
Macros
#define EV_TYPE_METADATA (ev_metadata_get_type())
#define EV_METADATA(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_METADATA, EvMetadata))
#define EV_METADATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_METADATA, EvMetadataClass))
#define EV_IS_METADATA(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_METADATA))
Typedefs
typedef struct _EvMetadata EvMetadata
typedef struct _EvMetadataClass EvMetadataClass
Functions
GType ev_metadata_get_type (void)
EvMetadata * ev_metadata_new (GFile *file)
gboolean ev_metadata_is_empty (EvMetadata *metadata)
gboolean ev_metadata_get_string (EvMetadata *metadata, const gchar *key, gchar **value)
gboolean ev_metadata_set_string (EvMetadata *metadata, const gchar *key, const gchar *value)
gboolean ev_metadata_get_int (EvMetadata *metadata, const gchar *key, gint *value)
gboolean ev_metadata_set_int (EvMetadata *metadata, const gchar *key, gint value)
gboolean ev_metadata_get_double (EvMetadata *metadata, const gchar *key, gdouble *value)
gboolean ev_metadata_set_double (EvMetadata *metadata, const gchar *key, gdouble value)
gboolean ev_metadata_get_boolean (EvMetadata *metadata, const gchar *key, gboolean *value)
gboolean ev_metadata_set_boolean (EvMetadata *metadata, const gchar *key, gboolean value)
gboolean ev_metadata_has_key (EvMetadata *metadata, const gchar *key)
gboolean ev_is_metadata_supported_for_file (GFile *file)
Macro Definition Documentation
EV_IS_METADATA
#define EV_IS_METADATA (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_METADATA))
Definition at line 32 of file ev-metadata.h.
EV_METADATA
#define EV_METADATA (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_METADATA, EvMetadata))
Definition at line 30 of file ev-metadata.h.
EV_METADATA_CLASS
#define EV_METADATA_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_METADATA, EvMetadataClass))
Definition at line 31 of file ev-metadata.h.
EV_TYPE_METADATA
#define EV_TYPE_METADATA (ev_metadata_get_type())
Definition at line 29 of file ev-metadata.h.
Typedef Documentation
EvMetadata
typedef struct _EvMetadata EvMetadata
Definition at line 34 of file ev-metadata.h.
EvMetadataClass
typedef struct _EvMetadataClass EvMetadataClass
Definition at line 35 of file ev-metadata.h.
Function Documentation
ev_is_metadata_supported_for_file()
gboolean ev_is_metadata_supported_for_file (GFile * file)
Definition at line 305 of file ev-metadata.c.
References FALSE, NULL, and TRUE.
Referenced by ev_window_open_uri().
ev_metadata_get_boolean()
gboolean ev_metadata_get_boolean (EvMetadata * metadata, const gchar * key, gboolean * value)
Definition at line 276 of file ev-metadata.c.
References ev_metadata_get_int(), FALSE, key, and TRUE.
ev_metadata_get_double()
gboolean ev_metadata_get_double (EvMetadata * metadata, const gchar * key, gdouble * value)
Definition at line 244 of file ev-metadata.c.
References ev_metadata_get_string(), FALSE, key, and TRUE.
ev_metadata_get_int()
gboolean ev_metadata_get_int (EvMetadata * metadata, const gchar * key, gint * value)
Definition at line 212 of file ev-metadata.c.
References ev_metadata_get_string(), FALSE, key, and TRUE.
Referenced by ev_metadata_get_boolean().
ev_metadata_get_string()
gboolean ev_metadata_get_string (EvMetadata * metadata, const gchar * key, gchar ** value)
Definition at line 148 of file ev-metadata.c.
References FALSE, key, and TRUE.
Referenced by ev_metadata_get_double(), and ev_metadata_get_int().
ev_metadata_get_type()
GType ev_metadata_get_type (void)
ev_metadata_has_key()
gboolean ev_metadata_has_key (EvMetadata * metadata, const gchar * key)
Definition at line 298 of file ev-metadata.c.
References key, and NULL.
ev_metadata_is_empty()
gboolean ev_metadata_is_empty (EvMetadata * metadata)
Definition at line 142 of file ev-metadata.c.
ev_metadata_new()
EvMetadata * ev_metadata_new (GFile * file)
Definition at line 126 of file ev-metadata.c.
References ev_file_is_temp(), EV_METADATA, EV_TYPE_METADATA, and NULL.
Referenced by ev_window_open_uri().
ev_metadata_set_boolean()
gboolean ev_metadata_set_boolean (EvMetadata * metadata, const gchar * key, gboolean value)
Definition at line 290 of file ev-metadata.c.
References ev_metadata_set_string(), and key.
ev_metadata_set_double()
gboolean ev_metadata_set_double (EvMetadata * metadata, const gchar * key, gdouble value)
Definition at line 264 of file ev-metadata.c.
References ev_metadata_set_string(), and key.
ev_metadata_set_int()
gboolean ev_metadata_set_int (EvMetadata * metadata, const gchar * key, gint value)
Definition at line 232 of file ev-metadata.c.
References ev_metadata_set_string(), and key.
ev_metadata_set_string()
gboolean ev_metadata_set_string (EvMetadata * metadata, const gchar * key, const gchar * value)
Definition at line 176 of file ev-metadata.c.
References EV_METADATA_NAMESPACE, key, NULL, and TRUE.
Referenced by ev_metadata_set_boolean(), ev_metadata_set_double(), and ev_metadata_set_int().