MATE Desktop Environment: ev-pixbuf-cache.c File Reference
ev-pixbuf-cache.c File Reference
#include <config.h>
#include "ev-pixbuf-cache.h"
#include "ev-job-scheduler.h"
#include "ev-view-private.h"
Macros
#define FIRST_VISIBLE_PREV(pixbuf_cache) (MAX (0, pixbuf_cache->preload_cache_size - pixbuf_cache->start_page))
#define VISIBLE_NEXT_LEN(pixbuf_cache) (MIN(pixbuf_cache->preload_cache_size, ev_document_get_n_pages (pixbuf_cache->document) - (1 + pixbuf_cache->end_page)))
#define PAGE_CACHE_LEN(pixbuf_cache) (pixbuf_cache->start_page>=0?((pixbuf_cache->end_page - pixbuf_cache->start_page) + 1):0)
#define MAX_PRELOADED_PAGES 3
Typedefs
typedef struct _CacheJobInfo CacheJobInfo
Enumerations
enum ScrollDirection { SCROLL_DIRECTION_DOWN , SCROLL_DIRECTION_UP }
enum { JOB_FINISHED , N_SIGNALS }
Functions
EvPixbufCache * ev_pixbuf_cache_new (GtkWidget *view, EvDocumentModel *model, gsize max_size)
void ev_pixbuf_cache_set_max_size (EvPixbufCache *pixbuf_cache, gsize max_size)
void ev_pixbuf_cache_set_page_range (EvPixbufCache *pixbuf_cache, gint start_page, gint end_page, GList *selection_list)
void ev_pixbuf_cache_set_inverted_colors (EvPixbufCache *pixbuf_cache, gboolean inverted_colors)
cairo_surface_t * ev_pixbuf_cache_get_surface (EvPixbufCache *pixbuf_cache, gint page)
void ev_pixbuf_cache_clear (EvPixbufCache *pixbuf_cache)
void ev_pixbuf_cache_style_changed (EvPixbufCache *pixbuf_cache)
cairo_surface_t * ev_pixbuf_cache_get_selection_surface (EvPixbufCache *pixbuf_cache, gint page, gfloat scale)
cairo_region_t * ev_pixbuf_cache_get_selection_region (EvPixbufCache *pixbuf_cache, gint page, gfloat scale)
void ev_pixbuf_cache_set_selection_list (EvPixbufCache *pixbuf_cache, GList *selection_list)
GList * ev_pixbuf_cache_get_selection_list (EvPixbufCache *pixbuf_cache)
void ev_pixbuf_cache_reload_page (EvPixbufCache *pixbuf_cache, cairo_region_t *region, gint page, gint rotation, gdouble scale)
Macro Definition Documentation
FIRST_VISIBLE_PREV
#define FIRST_VISIBLE_PREV (pixbuf_cache) (MAX (0, pixbuf_cache->preload_cache_size - pixbuf_cache->start_page))
Definition at line 95 of file ev-pixbuf-cache.c.
MAX_PRELOADED_PAGES
#define MAX_PRELOADED_PAGES 3
Definition at line 102 of file ev-pixbuf-cache.c.
PAGE_CACHE_LEN
#define PAGE_CACHE_LEN (pixbuf_cache) (pixbuf_cache->start_page>=0?((pixbuf_cache->end_page - pixbuf_cache->start_page) + 1):0)
Definition at line 99 of file ev-pixbuf-cache.c.
VISIBLE_NEXT_LEN
#define VISIBLE_NEXT_LEN (pixbuf_cache) (MIN(pixbuf_cache->preload_cache_size, ev_document_get_n_pages (pixbuf_cache->document) - (1 + pixbuf_cache->end_page)))
Definition at line 97 of file ev-pixbuf-cache.c.
Typedef Documentation
CacheJobInfo
typedef struct _CacheJobInfo CacheJobInfo
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
JOB_FINISHED
N_SIGNALS
Definition at line 75 of file ev-pixbuf-cache.c.
ScrollDirection
enum ScrollDirection
Enumerator
SCROLL_DIRECTION_DOWN
SCROLL_DIRECTION_UP
Definition at line 6 of file ev-pixbuf-cache.c.
Function Documentation
ev_pixbuf_cache_clear()
void ev_pixbuf_cache_clear (EvPixbufCache * pixbuf_cache)
Definition at line 968 of file ev-pixbuf-cache.c.
References PAGE_CACHE_LEN.
Referenced by ev_pixbuf_cache_set_max_size(), and ev_view_reload().
ev_pixbuf_cache_get_selection_list()
GList * ev_pixbuf_cache_get_selection_list (EvPixbufCache * pixbuf_cache)
Definition at line 1267 of file ev-pixbuf-cache.c.
References EvViewSelection::covered_region, ev_document_get_n_pages(), EV_IS_PIXBUF_CACHE, NULL, EvViewSelection::page, PAGE_CACHE_LEN, and EvViewSelection::rect.
ev_pixbuf_cache_get_selection_region()
cairo_region_t * ev_pixbuf_cache_get_selection_region (EvPixbufCache * pixbuf_cache, gint page, gfloat scale)
Definition at line 1095 of file ev-pixbuf-cache.c.
References ev_document_doc_mutex_lock(), ev_document_doc_mutex_unlock(), ev_document_get_page(), EV_IS_SELECTION, EV_JOB_RENDER, ev_rect_cmp(), ev_render_context_new(), EV_SELECTION, ev_selection_get_selection_region(), and NULL.
ev_pixbuf_cache_get_selection_surface()
cairo_surface_t * ev_pixbuf_cache_get_selection_surface (EvPixbufCache * pixbuf_cache, gint page, gfloat scale)
Definition at line 1025 of file ev-pixbuf-cache.c.
References ev_document_doc_mutex_lock(), ev_document_doc_mutex_unlock(), ev_document_get_page(), EV_IS_SELECTION, EV_JOB_RENDER, ev_rect_cmp(), ev_render_context_new(), EV_SELECTION, ev_selection_render_selection(), EV_VIEW, and NULL.
ev_pixbuf_cache_get_surface()
cairo_surface_t * ev_pixbuf_cache_get_surface (EvPixbufCache * pixbuf_cache, gint page)
Definition at line 893 of file ev-pixbuf-cache.c.
References EV_JOB_RENDER, JOB_FINISHED, and NULL.
ev_pixbuf_cache_new()
EvPixbufCache * ev_pixbuf_cache_new (GtkWidget * view, EvDocumentModel * model, gsize max_size)
Definition at line 225 of file ev-pixbuf-cache.c.
References ev_document_model_get_document(), EV_TYPE_PIXBUF_CACHE, and NULL.
ev_pixbuf_cache_reload_page()
void ev_pixbuf_cache_reload_page (EvPixbufCache * pixbuf_cache, cairo_region_t * region, gint page, gint rotation, gdouble scale)
Definition at line 1333 of file ev-pixbuf-cache.c.
References _get_page_size_for_scale_and_rotation(), EV_JOB_PRIORITY_URGENT, and NULL.
ev_pixbuf_cache_set_inverted_colors()
void ev_pixbuf_cache_set_inverted_colors (EvPixbufCache * pixbuf_cache, gboolean inverted_colors)
Definition at line 861 of file ev-pixbuf-cache.c.
References ev_document_misc_invert_surface(), and PAGE_CACHE_LEN.
ev_pixbuf_cache_set_max_size()
void ev_pixbuf_cache_set_max_size (EvPixbufCache * pixbuf_cache, gsize max_size)
Definition at line 242 of file ev-pixbuf-cache.c.
References ev_pixbuf_cache_clear().
Referenced by ev_view_set_page_cache_size().
ev_pixbuf_cache_set_page_range()
void ev_pixbuf_cache_set_page_range (EvPixbufCache * pixbuf_cache, gint start_page, gint end_page, GList * selection_list)
Definition at line 828 of file ev-pixbuf-cache.c.
References ev_document_get_n_pages(), ev_document_model_get_rotation(), ev_document_model_get_scale(), EV_IS_PIXBUF_CACHE, and ev_pixbuf_cache_set_selection_list().
ev_pixbuf_cache_set_selection_list()
void ev_pixbuf_cache_set_selection_list (EvPixbufCache * pixbuf_cache, GList * selection_list)
Definition at line 1182 of file ev-pixbuf-cache.c.
References ev_document_get_n_pages(), EV_IS_PIXBUF_CACHE, EV_IS_SELECTION, NULL, and PAGE_CACHE_LEN.
Referenced by ev_pixbuf_cache_set_page_range().
ev_pixbuf_cache_style_changed()
void ev_pixbuf_cache_style_changed (EvPixbufCache * pixbuf_cache)
Definition at line 986 of file ev-pixbuf-cache.c.
References NULL, and PAGE_CACHE_LEN.