MATE Desktop Environment: ev-print-operation.c File Reference
ev-print-operation.c File Reference
#include <config.h>
#include "ev-print-operation.h"
#include <glib/gi18n.h>
#include <glib/gstdio.h>
#include <unistd.h>
#include "ev-jobs.h"
#include "ev-job-scheduler.h"
Macros
#define EV_TYPE_PRINT_OPERATION_PRINT (ev_print_operation_print_get_type())
#define EV_PRINT_OPERATION_PRINT(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_PRINT_OPERATION_PRINT, EvPrintOperationPrint))
#define EV_PRINT_SETTING_PAGE_SCALE "atril-print-setting-page-scale"
#define EV_PRINT_SETTING_AUTOROTATE "atril-print-setting-page-autorotate"
#define EV_PRINT_SETTING_PAGE_SIZE "atril-print-setting-page-size"
Typedefs
typedef struct _EvPrintOperationPrint EvPrintOperationPrint
typedef struct _EvPrintOperationPrintClass EvPrintOperationPrintClass
Enumerations
enum { PROP_0 , PROP_DOCUMENT }
enum { DONE , BEGIN_PRINT , STATUS_CHANGED , LAST_SIGNAL }
enum EvPrintScale { EV_SCALE_NONE , EV_SCALE_SHRINK_TO_PRINTABLE_AREA , EV_SCALE_FIT_TO_PRINTABLE_AREA }
Functions
void ev_print_operation_set_current_page (EvPrintOperation *op, gint current_page)
void ev_print_operation_set_print_settings (EvPrintOperation *op, GtkPrintSettings *print_settings)
GtkPrintSettings * ev_print_operation_get_print_settings (EvPrintOperation *op)
void ev_print_operation_set_default_page_setup (EvPrintOperation *op, GtkPageSetup *page_setup)
GtkPageSetup * ev_print_operation_get_default_page_setup (EvPrintOperation *op)
void ev_print_operation_set_job_name (EvPrintOperation *op, const gchar *job_name)
const gchar * ev_print_operation_get_job_name (EvPrintOperation *op)
void ev_print_operation_run (EvPrintOperation *op, GtkWindow *parent)
void ev_print_operation_cancel (EvPrintOperation *op)
void ev_print_operation_get_error (EvPrintOperation *op, GError **error)
void ev_print_operation_set_embed_page_setup (EvPrintOperation *op, gboolean embed)
gboolean ev_print_operation_get_embed_page_setup (EvPrintOperation *op)
const gchar * ev_print_operation_get_status (EvPrintOperation *op)
gdouble ev_print_operation_get_progress (EvPrintOperation *op)
gboolean ev_print_operation_exists_for_document (EvDocument *document)
EvPrintOperation * ev_print_operation_new (EvDocument *document)
Macro Definition Documentation
EV_PRINT_OPERATION_PRINT
#define EV_PRINT_OPERATION_PRINT (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_PRINT_OPERATION_PRINT, EvPrintOperationPrint))
Definition at line 1508 of file ev-print-operation.c.
EV_PRINT_SETTING_AUTOROTATE
#define EV_PRINT_SETTING_AUTOROTATE "atril-print-setting-page-autorotate"
Definition at line 1522 of file ev-print-operation.c.
EV_PRINT_SETTING_PAGE_SCALE
#define EV_PRINT_SETTING_PAGE_SCALE "atril-print-setting-page-scale"
Definition at line 1521 of file ev-print-operation.c.
EV_PRINT_SETTING_PAGE_SIZE
#define EV_PRINT_SETTING_PAGE_SIZE "atril-print-setting-page-size"
Definition at line 1523 of file ev-print-operation.c.
EV_TYPE_PRINT_OPERATION_PRINT
#define EV_TYPE_PRINT_OPERATION_PRINT (ev_print_operation_print_get_type())
Definition at line 1507 of file ev-print-operation.c.
Typedef Documentation
EvPrintOperationPrint
typedef struct _EvPrintOperationPrint EvPrintOperationPrint
Definition at line 1510 of file ev-print-operation.c.
EvPrintOperationPrintClass
typedef struct _EvPrintOperationPrintClass EvPrintOperationPrintClass
Definition at line 1511 of file ev-print-operation.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_DOCUMENT
Definition at line 34 of file ev-print-operation.c.
anonymous enum
anonymous enum
Enumerator
DONE
BEGIN_PRINT
STATUS_CHANGED
LAST_SIGNAL
Definition at line 39 of file ev-print-operation.c.
EvPrintScale
enum EvPrintScale
Enumerator
EV_SCALE_NONE
EV_SCALE_SHRINK_TO_PRINTABLE_AREA
EV_SCALE_FIT_TO_PRINTABLE_AREA
Definition at line 1515 of file ev-print-operation.c.
Function Documentation
ev_print_operation_cancel()
void ev_print_operation_cancel (EvPrintOperation * op)
Definition at line 276 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, and op.
ev_print_operation_exists_for_document()
gboolean ev_print_operation_exists_for_document (EvDocument * document)
Definition at line 2037 of file ev-print-operation.c.
References EV_IS_DOCUMENT_PRINT, and EV_IS_FILE_EXPORTER.
Referenced by ev_print_operation_new().
ev_print_operation_get_default_page_setup()
GtkPageSetup * ev_print_operation_get_default_page_setup (EvPrintOperation * op)
ev_print_operation_get_default_page_setup: @op: an EvPrintOperation
Returns: (transfer none): a #GtkPageSetup
Definition at line 233 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, NULL, and op.
ev_print_operation_get_embed_page_setup()
gboolean ev_print_operation_get_embed_page_setup (EvPrintOperation * op)
Definition at line 308 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, FALSE, and op.
ev_print_operation_get_error()
void ev_print_operation_get_error (EvPrintOperation * op, GError ** error)
Definition at line 286 of file ev-print-operation.c.
References error, EV_IS_PRINT_OPERATION, and op.
ev_print_operation_get_job_name()
const gchar * ev_print_operation_get_job_name (EvPrintOperation * op)
Definition at line 255 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, NULL, and op.
ev_print_operation_get_print_settings()
GtkPrintSettings * ev_print_operation_get_print_settings (EvPrintOperation * op)
ev_print_operation_get_print_settings: @op: an EvPrintOperation
Returns: (transfer none): a #GtkPrintSettings
Definition at line 205 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, NULL, and op.
ev_print_operation_get_progress()
gdouble ev_print_operation_get_progress (EvPrintOperation * op)
Definition at line 326 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, and op.
ev_print_operation_get_status()
const gchar * ev_print_operation_get_status (EvPrintOperation * op)
Definition at line 318 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, NULL, and op.
ev_print_operation_new()
EvPrintOperation * ev_print_operation_new (EvDocument * document)
Definition at line 2048 of file ev-print-operation.c.
References EV_IS_DOCUMENT_PRINT, EV_PRINT_OPERATION, ev_print_operation_exists_for_document(), EV_TYPE_PRINT_OPERATION_PRINT, NULL, and op.
Referenced by ev_window_print_range().
ev_print_operation_run()
void ev_print_operation_run (EvPrintOperation * op, GtkWindow * parent)
Definition at line 265 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, and op.
Referenced by ev_window_print_range().
ev_print_operation_set_current_page()
void ev_print_operation_set_current_page (EvPrintOperation * op, gint current_page)
Definition at line 175 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, and op.
Referenced by ev_window_print_range().
ev_print_operation_set_default_page_setup()
void ev_print_operation_set_default_page_setup (EvPrintOperation * op, GtkPageSetup * page_setup)
Definition at line 215 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, and op.
Referenced by ev_window_print_range().
ev_print_operation_set_embed_page_setup()
void ev_print_operation_set_embed_page_setup (EvPrintOperation * op, gboolean embed)
Definition at line 297 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, and op.
Referenced by ev_window_print_range().
ev_print_operation_set_job_name()
void ev_print_operation_set_job_name (EvPrintOperation * op, const gchar * job_name)
Definition at line 243 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, NULL, and op.
Referenced by ev_window_print_range().
ev_print_operation_set_print_settings()
void ev_print_operation_set_print_settings (EvPrintOperation * op, GtkPrintSettings * print_settings)
Definition at line 187 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, and op.
Referenced by ev_window_print_range().