MATE Desktop Environment: ev-properties-dialog.h File Reference
ev-properties-dialog.h File Reference
#include "ev-document.h"
Macros
#define EV_TYPE_PROPERTIES_DIALOG (ev_properties_dialog_get_type())
#define EV_PROPERTIES_DIALOG(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_PROPERTIES_DIALOG, EvPropertiesDialog))
#define EV_PROPERTIES_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_PROPERTIES_DIALOG, EvPropertiesDialogClass))
#define EV_IS_PROPERTIES_DIALOG(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_PROPERTIES_DIALOG))
#define EV_IS_PROPERTIES_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_PROPERTIES_DIALOG))
#define EV_PROPERTIES_DIALOG_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_PROPERTIES_DIALOG, EvPropertiesDialogClass))
Typedefs
typedef struct _EvPropertiesDialog EvPropertiesDialog
typedef struct _EvPropertiesDialogClass EvPropertiesDialogClass
typedef struct _EvPropertiesDialogPrivate EvPropertiesDialogPrivate
Functions
GType ev_properties_dialog_get_type (void)
GtkWidget * ev_properties_dialog_new (void)
void ev_properties_dialog_set_document (EvPropertiesDialog *properties, const gchar *uri, EvDocument *document)
Macro Definition Documentation
EV_IS_PROPERTIES_DIALOG
#define EV_IS_PROPERTIES_DIALOG (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_PROPERTIES_DIALOG))
Definition at line 35 of file ev-properties-dialog.h.
EV_IS_PROPERTIES_DIALOG_CLASS
#define EV_IS_PROPERTIES_DIALOG_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_PROPERTIES_DIALOG))
Definition at line 36 of file ev-properties-dialog.h.
EV_PROPERTIES_DIALOG
#define EV_PROPERTIES_DIALOG (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_PROPERTIES_DIALOG, EvPropertiesDialog))
Definition at line 33 of file ev-properties-dialog.h.
EV_PROPERTIES_DIALOG_CLASS
#define EV_PROPERTIES_DIALOG_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_PROPERTIES_DIALOG, EvPropertiesDialogClass))
Definition at line 34 of file ev-properties-dialog.h.
EV_PROPERTIES_DIALOG_GET_CLASS
#define EV_PROPERTIES_DIALOG_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_PROPERTIES_DIALOG, EvPropertiesDialogClass))
Definition at line 37 of file ev-properties-dialog.h.
EV_TYPE_PROPERTIES_DIALOG
#define EV_TYPE_PROPERTIES_DIALOG (ev_properties_dialog_get_type())
Definition at line 32 of file ev-properties-dialog.h.
Typedef Documentation
EvPropertiesDialog
typedef struct _EvPropertiesDialog EvPropertiesDialog
Definition at line 28 of file ev-properties-dialog.h.
EvPropertiesDialogClass
typedef struct _EvPropertiesDialogClass EvPropertiesDialogClass
Definition at line 29 of file ev-properties-dialog.h.
EvPropertiesDialogPrivate
typedef struct _EvPropertiesDialogPrivate EvPropertiesDialogPrivate
Definition at line 30 of file ev-properties-dialog.h.
Function Documentation
ev_properties_dialog_get_type()
GType ev_properties_dialog_get_type (void)
ev_properties_dialog_new()
GtkWidget * ev_properties_dialog_new (void)
Definition at line 194 of file ev-properties-dialog.c.
References EV_TYPE_PROPERTIES_DIALOG, and NULL.
ev_properties_dialog_set_document()
void ev_properties_dialog_set_document (EvPropertiesDialog * properties, const gchar * uri, EvDocument * document)
Definition at line 146 of file ev-properties-dialog.c.
References _, ev_document_get_info(), EV_DOCUMENT_INFO_LICENSE, EV_IS_DOCUMENT_FONTS, EV_PROPERTIES_FONTS, ev_properties_fonts_new(), ev_properties_fonts_set_document(), EV_PROPERTIES_LICENSE, ev_properties_license_new(), ev_properties_license_set_license(), EV_PROPERTIES_VIEW, ev_properties_view_new(), ev_properties_view_set_info(), _EvDocumentInfo::fields_mask, label, _EvDocumentInfo::license, and NULL.