MATE Desktop Environment: ev-previewer-window.h File Reference
ev-previewer-window.h File Reference
#include <gtk/gtk.h>
#include <atril-document.h>
#include <atril-view.h>
Macros
#define EV_TYPE_PREVIEWER_WINDOW (ev_previewer_window_get_type())
#define EV_PREVIEWER_WINDOW(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_PREVIEWER_WINDOW, EvPreviewerWindow))
#define EV_PREVIEWER_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_PREVIEWER_WINDOW, EvPreviewerWindowClass))
#define EV_IS_PREVIEWER_WINDOW(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_PREVIEWER_WINDOW))
#define EV_IS_PREVIEWER_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_PREVIEWER_WINDOW))
#define EV_PREVIEWER_WINDOW_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_PREVIEWER_WINDOW, EvPreviewerWindowClass))
Typedefs
typedef struct _EvPreviewerWindow EvPreviewerWindow
typedef struct _EvPreviewerWindowClass EvPreviewerWindowClass
Functions
GType ev_previewer_window_get_type (void)
GtkWidget * ev_previewer_window_new (EvDocumentModel *model)
void ev_previewer_window_set_print_settings (EvPreviewerWindow *window, const gchar *print_settings)
void ev_previewer_window_set_source_file (EvPreviewerWindow *window, const gchar *source_file)
Macro Definition Documentation
EV_IS_PREVIEWER_WINDOW
#define EV_IS_PREVIEWER_WINDOW (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_PREVIEWER_WINDOW))
Definition at line 34 of file ev-previewer-window.h.
EV_IS_PREVIEWER_WINDOW_CLASS
#define EV_IS_PREVIEWER_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_PREVIEWER_WINDOW))
Definition at line 35 of file ev-previewer-window.h.
EV_PREVIEWER_WINDOW
#define EV_PREVIEWER_WINDOW (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_PREVIEWER_WINDOW, EvPreviewerWindow))
Definition at line 32 of file ev-previewer-window.h.
EV_PREVIEWER_WINDOW_CLASS
#define EV_PREVIEWER_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_PREVIEWER_WINDOW, EvPreviewerWindowClass))
Definition at line 33 of file ev-previewer-window.h.
EV_PREVIEWER_WINDOW_GET_CLASS
#define EV_PREVIEWER_WINDOW_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_PREVIEWER_WINDOW, EvPreviewerWindowClass))
Definition at line 36 of file ev-previewer-window.h.
EV_TYPE_PREVIEWER_WINDOW
#define EV_TYPE_PREVIEWER_WINDOW (ev_previewer_window_get_type())
Definition at line 31 of file ev-previewer-window.h.
Typedef Documentation
EvPreviewerWindow
typedef struct _EvPreviewerWindow EvPreviewerWindow
Definition at line 38 of file ev-previewer-window.h.
EvPreviewerWindowClass
typedef struct _EvPreviewerWindowClass EvPreviewerWindowClass
Definition at line 39 of file ev-previewer-window.h.
Function Documentation
ev_previewer_window_get_type()
GType ev_previewer_window_get_type (void)
ev_previewer_window_new()
GtkWidget * ev_previewer_window_new (EvDocumentModel * model)
Definition at line 645 of file ev-previewer-window.c.
References EV_TYPE_PREVIEWER_WINDOW, and NULL.
Referenced by main().
ev_previewer_window_set_print_settings()
void ev_previewer_window_set_print_settings (EvPreviewerWindow * window, const gchar * print_settings)
Definition at line 651 of file ev-previewer-window.c.
References error, and NULL.
Referenced by main().
ev_previewer_window_set_source_file()
void ev_previewer_window_set_source_file (EvPreviewerWindow * window, const gchar * source_file)
Definition at line 707 of file ev-previewer-window.c.
References source_file.
Referenced by main().