MATE Desktop Environment: ev-properties-fonts.h File Reference
ev-properties-fonts.h File Reference
#include "ev-document.h"
#include <gtk/gtk.h>
Macros
#define EV_TYPE_PROPERTIES_FONTS (ev_properties_fonts_get_type())
#define EV_PROPERTIES_FONTS(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_PROPERTIES_FONTS, EvPropertiesFonts))
#define EV_PROPERTIES_FONTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_PROPERTIES_FONTS, EvPropertiesFontsClass))
#define EV_IS_PROPERTIES(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_PROPERTIES_FONTS))
#define EV_IS_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_PROPERTIES_FONTS))
#define EV_PROPERTIES_FONTS_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_PROPERTIES_FONTS, EvPropertiesFontsClass))
Typedefs
typedef struct _EvPropertiesFonts EvPropertiesFonts
typedef struct _EvPropertiesFontsClass EvPropertiesFontsClass
typedef struct _EvPropertiesFontsPrivate EvPropertiesFontsPrivate
Functions
GType ev_properties_fonts_get_type (void)
GtkWidget * ev_properties_fonts_new (void)
void ev_properties_fonts_set_document (EvPropertiesFonts *properties, EvDocument *document)
Macro Definition Documentation
EV_IS_PROPERTIES
#define EV_IS_PROPERTIES (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_PROPERTIES_FONTS))
Definition at line 37 of file ev-properties-fonts.h.
EV_IS_PROPERTIES_CLASS
#define EV_IS_PROPERTIES_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_PROPERTIES_FONTS))
Definition at line 38 of file ev-properties-fonts.h.
EV_PROPERTIES_FONTS
#define EV_PROPERTIES_FONTS (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_PROPERTIES_FONTS, EvPropertiesFonts))
Definition at line 35 of file ev-properties-fonts.h.
EV_PROPERTIES_FONTS_CLASS
#define EV_PROPERTIES_FONTS_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_PROPERTIES_FONTS, EvPropertiesFontsClass))
Definition at line 36 of file ev-properties-fonts.h.
EV_PROPERTIES_FONTS_GET_CLASS
#define EV_PROPERTIES_FONTS_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_PROPERTIES_FONTS, EvPropertiesFontsClass))
Definition at line 39 of file ev-properties-fonts.h.
EV_TYPE_PROPERTIES_FONTS
#define EV_TYPE_PROPERTIES_FONTS (ev_properties_fonts_get_type())
Definition at line 34 of file ev-properties-fonts.h.
Typedef Documentation
EvPropertiesFonts
typedef struct _EvPropertiesFonts EvPropertiesFonts
Definition at line 30 of file ev-properties-fonts.h.
EvPropertiesFontsClass
typedef struct _EvPropertiesFontsClass EvPropertiesFontsClass
Definition at line 31 of file ev-properties-fonts.h.
EvPropertiesFontsPrivate
typedef struct _EvPropertiesFontsPrivate EvPropertiesFontsPrivate
Definition at line 32 of file ev-properties-fonts.h.
Function Documentation
ev_properties_fonts_get_type()
GType ev_properties_fonts_get_type (void)
ev_properties_fonts_new()
GtkWidget * ev_properties_fonts_new (void)
Definition at line 218 of file ev-properties-fonts.c.
References EV_TYPE_PROPERTIES_FONTS, and NULL.
Referenced by ev_properties_dialog_set_document().
ev_properties_fonts_set_document()
void ev_properties_fonts_set_document (EvPropertiesFonts * properties, EvDocument * document)
Definition at line 195 of file ev-properties-fonts.c.
References EV_DOCUMENT_FONTS_COLUMN_NUM_COLUMNS, ev_job_fonts_new(), EV_JOB_PRIORITY_NONE, and ev_job_scheduler_push_job().
Referenced by ev_properties_dialog_set_document().