MATE Desktop Environment: ev-properties-view.c File Reference
ev-properties-view.c File Reference
#include "config.h"
#include <string.h>
#include <sys/time.h>
#include <time.h>
#include <glib/gi18n-lib.h>
#include <gtk/gtk.h>
#include "ev-properties-view.h"
Enumerations
enum Property {
TITLE_PROPERTY , URI_PROPERTY , SUBJECT_PROPERTY , AUTHOR_PROPERTY ,
KEYWORDS_PROPERTY , PRODUCER_PROPERTY , CREATOR_PROPERTY , CREATION_DATE_PROPERTY ,
MOD_DATE_PROPERTY , N_PAGES_PROPERTY , LINEARIZED_PROPERTY , FORMAT_PROPERTY ,
SECURITY_PROPERTY , PAPER_SIZE_PROPERTY , N_PROPERTIES
}
Functions
void ev_properties_view_set_info (EvPropertiesView *properties, const EvDocumentInfo *info)
void ev_properties_view_register_type (GTypeModule *module)
GtkWidget * ev_properties_view_new (const gchar *uri)
Enumeration Type Documentation
Property
enum Property
Enumerator
TITLE_PROPERTY
URI_PROPERTY
SUBJECT_PROPERTY
AUTHOR_PROPERTY
KEYWORDS_PROPERTY
PRODUCER_PROPERTY
CREATOR_PROPERTY
CREATION_DATE_PROPERTY
MOD_DATE_PROPERTY
N_PAGES_PROPERTY
LINEARIZED_PROPERTY
FORMAT_PROPERTY
SECURITY_PROPERTY
PAPER_SIZE_PROPERTY
N_PROPERTIES
Definition at line 36 of file ev-properties-view.c.
Function Documentation
ev_properties_view_new()
GtkWidget * ev_properties_view_new (const gchar * uri)
Definition at line 395 of file ev-properties-view.c.
References EV_TYPE_PROPERTIES, and NULL.
Referenced by ev_properties_dialog_set_document().
ev_properties_view_register_type()
void ev_properties_view_register_type (GTypeModule * module)
Definition at line 389 of file ev-properties-view.c.
References ev_properties_view_get_type().
Referenced by caja_module_initialize().
ev_properties_view_set_info()
void ev_properties_view_set_info (EvPropertiesView * properties, const EvDocumentInfo * info)
Definition at line 318 of file ev-properties-view.c.
References _EvDocumentInfo::author, AUTHOR_PROPERTY, _EvDocumentInfo::creation_date, CREATION_DATE_PROPERTY, _EvDocumentInfo::creator, CREATOR_PROPERTY, EV_DOCUMENT_INFO_AUTHOR, EV_DOCUMENT_INFO_CREATION_DATE, EV_DOCUMENT_INFO_CREATOR, EV_DOCUMENT_INFO_FORMAT, EV_DOCUMENT_INFO_KEYWORDS, EV_DOCUMENT_INFO_LINEARIZED, EV_DOCUMENT_INFO_MOD_DATE, EV_DOCUMENT_INFO_N_PAGES, EV_DOCUMENT_INFO_PAPER_SIZE, EV_DOCUMENT_INFO_PRODUCER, EV_DOCUMENT_INFO_SECURITY, EV_DOCUMENT_INFO_SUBJECT, EV_DOCUMENT_INFO_TITLE, ev_document_misc_format_date(), _EvDocumentInfo::fields_mask, _EvDocumentInfo::format, FORMAT_PROPERTY, _EvDocumentInfo::keywords, KEYWORDS_PROPERTY, _EvDocumentInfo::linearized, LINEARIZED_PROPERTY, MOD_DATE_PROPERTY, _EvDocumentInfo::modified_date, _EvDocumentInfo::n_pages, N_PAGES_PROPERTY, PAPER_SIZE_PROPERTY, _EvDocumentInfo::producer, PRODUCER_PROPERTY, _EvDocumentInfo::security, SECURITY_PROPERTY, _EvDocumentInfo::subject, SUBJECT_PROPERTY, _EvDocumentInfo::title, TITLE_PROPERTY, and URI_PROPERTY.
Referenced by ev_properties_dialog_set_document().