MATE Desktop Environment: ev-properties-license.c File Reference
ev-properties-license.c File Reference
#include "config.h"
#include <string.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include "ev-properties-license.h"
Functions
void ev_properties_license_set_license (EvPropertiesLicense *properties, EvDocumentLicense *license)
GtkWidget * ev_properties_license_new (void)
Function Documentation
ev_properties_license_new()
GtkWidget * ev_properties_license_new (void)
Definition at line 160 of file ev-properties-license.c.
References EV_TYPE_PROPERTIES_LICENSE, and NULL.
Referenced by ev_properties_dialog_set_document().
ev_properties_license_set_license()
void ev_properties_license_set_license (EvPropertiesLicense * properties, EvDocumentLicense * license)
Definition at line 125 of file ev-properties-license.c.
References _, ev_document_license_get_text(), ev_document_license_get_uri(), and ev_document_license_get_web_statement().
Referenced by ev_properties_dialog_set_document().