MATE Desktop Environment: ev-properties-license.h File Reference
ev-properties-license.h File Reference
#include <gtk/gtk.h>
#include <atril-document.h>
Macros
#define EV_TYPE_PROPERTIES_LICENSE (ev_properties_license_get_type())
#define EV_PROPERTIES_LICENSE(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_PROPERTIES_LICENSE, EvPropertiesLicense))
#define EV_PROPERTIES_LICENSE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_PROPERTIES_LICENSE, EvPropertiesLicenseClass))
#define EV_IS_PROPERTIES_LICENSE(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_PROPERTIES_LICENSE))
#define EV_IS_PROPERTIES_LICENSE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_PROPERTIES_LICENSE))
#define EV_PROPERTIES_LICENSE_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_PROPERTIES_LICENSE, EvPropertiesLicenseClass))
Typedefs
typedef struct _EvPropertiesLicense EvPropertiesLicense
typedef struct _EvPropertiesLicenseClass EvPropertiesLicenseClass
typedef struct _EvPropertiesLicensePrivate EvPropertiesLicensePrivate
Functions
GType ev_properties_license_get_type (void)
GtkWidget * ev_properties_license_new (void)
void ev_properties_license_set_license (EvPropertiesLicense *properties_license, EvDocumentLicense *license)
Macro Definition Documentation
EV_IS_PROPERTIES_LICENSE
#define EV_IS_PROPERTIES_LICENSE (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_PROPERTIES_LICENSE))
Definition at line 38 of file ev-properties-license.h.
EV_IS_PROPERTIES_LICENSE_CLASS
#define EV_IS_PROPERTIES_LICENSE_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_PROPERTIES_LICENSE))
Definition at line 39 of file ev-properties-license.h.
EV_PROPERTIES_LICENSE
#define EV_PROPERTIES_LICENSE (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_PROPERTIES_LICENSE, EvPropertiesLicense))
Definition at line 36 of file ev-properties-license.h.
EV_PROPERTIES_LICENSE_CLASS
#define EV_PROPERTIES_LICENSE_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_PROPERTIES_LICENSE, EvPropertiesLicenseClass))
Definition at line 37 of file ev-properties-license.h.
EV_PROPERTIES_LICENSE_GET_CLASS
#define EV_PROPERTIES_LICENSE_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_PROPERTIES_LICENSE, EvPropertiesLicenseClass))
Definition at line 40 of file ev-properties-license.h.
EV_TYPE_PROPERTIES_LICENSE
#define EV_TYPE_PROPERTIES_LICENSE (ev_properties_license_get_type())
Definition at line 35 of file ev-properties-license.h.
Typedef Documentation
EvPropertiesLicense
typedef struct _EvPropertiesLicense EvPropertiesLicense
Definition at line 31 of file ev-properties-license.h.
EvPropertiesLicenseClass
typedef struct _EvPropertiesLicenseClass EvPropertiesLicenseClass
Definition at line 32 of file ev-properties-license.h.
EvPropertiesLicensePrivate
typedef struct _EvPropertiesLicensePrivate EvPropertiesLicensePrivate
Definition at line 33 of file ev-properties-license.h.
Function Documentation
ev_properties_license_get_type()
GType ev_properties_license_get_type (void)
ev_properties_license_new()
GtkWidget * ev_properties_license_new (void)
Definition at line 160 of file ev-properties-license.c.
References EV_TYPE_PROPERTIES_LICENSE, and NULL.
Referenced by ev_properties_dialog_set_document().
ev_properties_license_set_license()
void ev_properties_license_set_license (EvPropertiesLicense * properties_license, EvDocumentLicense * license)
Definition at line 125 of file ev-properties-license.c.
References _, ev_document_license_get_text(), ev_document_license_get_uri(), and ev_document_license_get_web_statement().
Referenced by ev_properties_dialog_set_document().