MATE Desktop Environment: ev-render-context.h File Reference
ev-render-context.h File Reference
#include <glib-object.h>
#include "ev-page.h"
Classes
struct _EvRenderContextClass
struct _EvRenderContext
Macros
#define EV_TYPE_RENDER_CONTEXT (ev_render_context_get_type())
#define EV_RENDER_CONTEXT(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_RENDER_CONTEXT, EvRenderContext))
#define EV_RENDER_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_RENDER_CONTEXT, EvRenderContextClass))
#define EV_IS_RENDER_CONTEXT(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_RENDER_CONTEXT))
Typedefs
typedef struct _EvRenderContext EvRenderContext
typedef struct _EvRenderContextClass EvRenderContextClass
Functions
GType ev_render_context_get_type (void)
EvRenderContext * ev_render_context_new (EvPage *page, gint rotation, gdouble scale)
void ev_render_context_set_page (EvRenderContext *rc, EvPage *page)
void ev_render_context_set_rotation (EvRenderContext *rc, gint rotation)
void ev_render_context_set_scale (EvRenderContext *rc, gdouble scale)
Macro Definition Documentation
EV_IS_RENDER_CONTEXT
#define EV_IS_RENDER_CONTEXT (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_RENDER_CONTEXT))
Definition at line 39 of file ev-render-context.h.
EV_RENDER_CONTEXT
#define EV_RENDER_CONTEXT (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_RENDER_CONTEXT, EvRenderContext))
Definition at line 37 of file ev-render-context.h.
EV_RENDER_CONTEXT_CLASS
#define EV_RENDER_CONTEXT_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_RENDER_CONTEXT, EvRenderContextClass))
Definition at line 38 of file ev-render-context.h.
EV_TYPE_RENDER_CONTEXT
#define EV_TYPE_RENDER_CONTEXT (ev_render_context_get_type())
Definition at line 36 of file ev-render-context.h.
Typedef Documentation
EvRenderContext
typedef struct _EvRenderContext EvRenderContext
Definition at line 33 of file ev-render-context.h.
EvRenderContextClass
typedef struct _EvRenderContextClass EvRenderContextClass
Definition at line 34 of file ev-render-context.h.
Function Documentation
ev_render_context_get_type()
GType ev_render_context_get_type (void)
ev_render_context_new()
EvRenderContext * ev_render_context_new (EvPage * page, gint rotation, gdouble scale)
Definition at line 53 of file ev-render-context.c.
References EV_TYPE_RENDER_CONTEXT, NULL, _EvRenderContext::page, _EvRenderContext::rotation, and _EvRenderContext::scale.
Referenced by ev_pixbuf_cache_get_selection_region(), ev_pixbuf_cache_get_selection_surface(), and G_DEFINE_TYPE_EXTENDED().
ev_render_context_set_page()
void ev_render_context_set_page (EvRenderContext * rc, EvPage * page)
Definition at line 69 of file ev-render-context.c.
References EV_IS_PAGE, NULL, and _EvRenderContext::page.
Referenced by G_DEFINE_TYPE_EXTENDED().
ev_render_context_set_rotation()
void ev_render_context_set_rotation (EvRenderContext * rc, gint rotation)
ev_render_context_set_scale()
void ev_render_context_set_scale (EvRenderContext * rc, gdouble scale)
Definition at line 90 of file ev-render-context.c.
References NULL, and _EvRenderContext::scale.
Referenced by G_DEFINE_TYPE_EXTENDED().