MATE Desktop Environment: ev-sidebar.h File Reference
ev-sidebar.h File Reference
#include <gtk/gtk.h>
#include "ev-document-model.h"
Classes
struct _EvSidebar
struct _EvSidebarClass
Macros
#define EV_TYPE_SIDEBAR (ev_sidebar_get_type())
#define EV_SIDEBAR(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_SIDEBAR, EvSidebar))
#define EV_SIDEBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_SIDEBAR, EvSidebarClass))
#define EV_IS_SIDEBAR(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_SIDEBAR))
#define EV_IS_SIDEBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_SIDEBAR))
#define EV_SIDEBAR_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_SIDEBAR, EvSidebarClass))
Typedefs
typedef struct _EvSidebar EvSidebar
typedef struct _EvSidebarClass EvSidebarClass
typedef struct _EvSidebarPrivate EvSidebarPrivate
Functions
GType ev_sidebar_get_type (void)
GtkWidget * ev_sidebar_new (void)
void ev_sidebar_add_page (EvSidebar *ev_sidebar, GtkWidget *main_widget)
void ev_sidebar_set_page (EvSidebar *ev_sidebar, GtkWidget *main_widget)
void ev_sidebar_set_model (EvSidebar *sidebar, EvDocumentModel *model)
Macro Definition Documentation
EV_IS_SIDEBAR
#define EV_IS_SIDEBAR (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_SIDEBAR))
Definition at line 40 of file ev-sidebar.h.
EV_IS_SIDEBAR_CLASS
#define EV_IS_SIDEBAR_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_SIDEBAR))
Definition at line 41 of file ev-sidebar.h.
EV_SIDEBAR
#define EV_SIDEBAR (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_SIDEBAR, EvSidebar))
Definition at line 38 of file ev-sidebar.h.
EV_SIDEBAR_CLASS
#define EV_SIDEBAR_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_SIDEBAR, EvSidebarClass))
Definition at line 39 of file ev-sidebar.h.
EV_SIDEBAR_GET_CLASS
#define EV_SIDEBAR_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_SIDEBAR, EvSidebarClass))
Definition at line 42 of file ev-sidebar.h.
EV_TYPE_SIDEBAR
#define EV_TYPE_SIDEBAR (ev_sidebar_get_type())
Definition at line 37 of file ev-sidebar.h.
Typedef Documentation
EvSidebar
typedef struct _EvSidebar EvSidebar
Definition at line 33 of file ev-sidebar.h.
EvSidebarClass
typedef struct _EvSidebarClass EvSidebarClass
Definition at line 34 of file ev-sidebar.h.
EvSidebarPrivate
typedef struct _EvSidebarPrivate EvSidebarPrivate
Definition at line 35 of file ev-sidebar.h.
Function Documentation
ev_sidebar_add_page()
void ev_sidebar_add_page (EvSidebar * ev_sidebar, GtkWidget * main_widget)
Definition at line 412 of file ev-sidebar.c.
References EV_IS_SIDEBAR, EV_IS_SIDEBAR_PAGE, EV_SIDEBAR_PAGE, ev_sidebar_page_get_label(), ev_sidebar_page_set_model(), mate_image_menu_item_new_with_label(), NULL, PAGE_COLUMN_MAIN_WIDGET, PAGE_COLUMN_MENU_ITEM, PAGE_COLUMN_NOTEBOOK_INDEX, PAGE_COLUMN_TITLE, and _EvSidebar::priv.
ev_sidebar_get_type()
GType ev_sidebar_get_type (void)
ev_sidebar_new()
GtkWidget * ev_sidebar_new (void)
Definition at line 402 of file ev-sidebar.c.
References EV_TYPE_SIDEBAR, and NULL.
ev_sidebar_set_model()
void ev_sidebar_set_model (EvSidebar * sidebar, EvDocumentModel * model)
Definition at line 506 of file ev-sidebar.c.
References EV_IS_DOCUMENT_MODEL, EV_IS_SIDEBAR, and _EvSidebar::priv.
ev_sidebar_set_page()
void ev_sidebar_set_page (EvSidebar * ev_sidebar, GtkWidget * main_widget)
Definition at line 103 of file ev-sidebar.c.
References FALSE, PAGE_COLUMN_MAIN_WIDGET, and _EvSidebar::priv.