MATE Desktop Environment: ev-stock-icons.c File Reference
ev-stock-icons.c File Reference
#include <config.h>
#include <gtk/gtk.h>
#include "ev-stock-icons.h"
Macros
#define EV_ICONS_PATH ATRILDATADIR "/icons"
Functions
void ev_stock_icons_init (void)
void ev_stock_icons_set_screen (GdkScreen *screen)
Macro Definition Documentation
EV_ICONS_PATH
#define EV_ICONS_PATH ATRILDATADIR "/icons"
Definition at line 54 of file ev-stock-icons.c.
Function Documentation
ev_stock_icons_init()
void ev_stock_icons_init (void)
ev_stock_icons_init:
Creates a new icon factory, adding the base stock icons to it.
Definition at line 90 of file ev-stock-icons.c.
References set.
Referenced by main(), and main().
ev_stock_icons_set_screen()
void ev_stock_icons_set_screen (GdkScreen * screen)
Definition at line 121 of file ev-stock-icons.c.
Referenced by ev_application_open_window().