MATE Desktop Environment: ev-timeline.h File Reference
ev-timeline.h File Reference
#include <glib-object.h>
Classes
struct EvTimeline
struct EvTimelineClass
Macros
#define EV_TYPE_TIMELINE (ev_timeline_get_type ())
#define EV_TIMELINE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EV_TYPE_TIMELINE, EvTimeline))
#define EV_TIMELINE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EV_TYPE_TIMELINE, EvTimelineClass))
#define EV_IS_TIMELINE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EV_TYPE_TIMELINE))
#define EV_IS_TIMELINE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EV_TYPE_TIMELINE))
#define EV_TIMELINE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EV_TYPE_TIMELINE, EvTimelineClass))
Typedefs
typedef struct EvTimeline EvTimeline
typedef struct EvTimelineClass EvTimelineClass
Functions
GType ev_timeline_get_type (void)
EvTimeline * ev_timeline_new (guint duration)
void ev_timeline_start (EvTimeline *timeline)
void ev_timeline_pause (EvTimeline *timeline)
void ev_timeline_rewind (EvTimeline *timeline)
gboolean ev_timeline_is_running (EvTimeline *timeline)
guint ev_timeline_get_fps (EvTimeline *timeline)
void ev_timeline_set_fps (EvTimeline *timeline, guint fps)
gboolean ev_timeline_get_loop (EvTimeline *timeline)
void ev_timeline_set_loop (EvTimeline *timeline, gboolean loop)
guint ev_timeline_get_duration (EvTimeline *timeline)
void ev_timeline_set_duration (EvTimeline *timeline, guint duration)
gdouble ev_timeline_get_progress (EvTimeline *timeline)
Macro Definition Documentation
EV_IS_TIMELINE
#define EV_IS_TIMELINE (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EV_TYPE_TIMELINE))
Definition at line 36 of file ev-timeline.h.
EV_IS_TIMELINE_CLASS
#define EV_IS_TIMELINE_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EV_TYPE_TIMELINE))
Definition at line 37 of file ev-timeline.h.
EV_TIMELINE
#define EV_TIMELINE (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EV_TYPE_TIMELINE, EvTimeline))
Definition at line 34 of file ev-timeline.h.
EV_TIMELINE_CLASS
#define EV_TIMELINE_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EV_TYPE_TIMELINE, EvTimelineClass))
Definition at line 35 of file ev-timeline.h.
EV_TIMELINE_GET_CLASS
#define EV_TIMELINE_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EV_TYPE_TIMELINE, EvTimelineClass))
Definition at line 38 of file ev-timeline.h.
EV_TYPE_TIMELINE
#define EV_TYPE_TIMELINE (ev_timeline_get_type ())
Definition at line 33 of file ev-timeline.h.
Typedef Documentation
EvTimeline
typedef struct EvTimeline EvTimeline
Definition at line 40 of file ev-timeline.h.
EvTimelineClass
typedef struct EvTimelineClass EvTimelineClass
Definition at line 41 of file ev-timeline.h.
Function Documentation
ev_timeline_get_duration()
guint ev_timeline_get_duration (EvTimeline * timeline)
Definition at line 411 of file ev-timeline.c.
References EV_IS_TIMELINE.
ev_timeline_get_fps()
guint ev_timeline_get_fps (EvTimeline * timeline)
Definition at line 338 of file ev-timeline.c.
References EV_IS_TIMELINE.
ev_timeline_get_loop()
gboolean ev_timeline_get_loop (EvTimeline * timeline)
Definition at line 371 of file ev-timeline.c.
References EV_IS_TIMELINE, and FALSE.
ev_timeline_get_progress()
gdouble ev_timeline_get_progress (EvTimeline * timeline)
Definition at line 423 of file ev-timeline.c.
References EV_IS_TIMELINE, and NULL.
Referenced by ev_transition_animation_paint().
ev_timeline_get_type()
GType ev_timeline_get_type (void)
ev_timeline_is_running()
gboolean ev_timeline_is_running (EvTimeline * timeline)
Definition at line 326 of file ev-timeline.c.
References EV_IS_TIMELINE, and FALSE.
Referenced by ev_timeline_rewind(), and ev_timeline_set_fps().
ev_timeline_new()
EvTimeline * ev_timeline_new (guint duration)
Definition at line 273 of file ev-timeline.c.
References EV_TYPE_TIMELINE, and NULL.
ev_timeline_pause()
void ev_timeline_pause (EvTimeline * timeline)
Definition at line 289 of file ev-timeline.c.
References EV_IS_TIMELINE, and PAUSED.
ev_timeline_rewind()
void ev_timeline_rewind (EvTimeline * timeline)
Definition at line 306 of file ev-timeline.c.
References EV_IS_TIMELINE, ev_timeline_is_running(), and NULL.
ev_timeline_set_duration()
void ev_timeline_set_duration (EvTimeline * timeline, guint duration)
Definition at line 396 of file ev-timeline.c.
References EV_IS_TIMELINE.
ev_timeline_set_fps()
void ev_timeline_set_fps (EvTimeline * timeline, guint fps)
Definition at line 349 of file ev-timeline.c.
References EV_IS_TIMELINE, ev_timeline_is_running(), and FRAME_INTERVAL.
ev_timeline_set_loop()
void ev_timeline_set_loop (EvTimeline * timeline, gboolean loop)
Definition at line 382 of file ev-timeline.c.
References EV_IS_TIMELINE, FALSE, and loop.
ev_timeline_start()
void ev_timeline_start (EvTimeline * timeline)
Definition at line 281 of file ev-timeline.c.
References EV_IS_TIMELINE, and EV_TIMELINE_GET_CLASS.
Referenced by ev_transition_animation_set_dest_surface(), and ev_transition_animation_set_origin_surface().