MATE Desktop Environment: ev-transition-animation.h File Reference
ev-transition-animation.h File Reference
#include <atril-document.h>
#include "ev-timeline.h"
#include "ev-transition-effect.h"
Classes
struct EvTransitionAnimation
struct EvTransitionAnimationClass
Macros
#define EV_TYPE_TRANSITION_ANIMATION (ev_transition_animation_get_type ())
#define EV_TRANSITION_ANIMATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EV_TYPE_TRANSITION_ANIMATION, EvTransitionAnimation))
#define EV_TRANSITION_ANIMATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EV_TYPE_TRANSITION_ANIMATION, EvTransitionAnimationClass))
#define EV_IS_TRANSITION_ANIMATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EV_TYPE_TRANSITION_ANIMATION))
#define EV_IS_TRANSITION_ANIMATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EV_TYPE_TRANSITION_ANIMATION))
#define EV_TRANSITION_ANIMATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EV_TYPE_TRANSITION_ANIMATION, EvTransitionAnimationClass))
Typedefs
typedef struct EvTransitionAnimation EvTransitionAnimation
typedef struct EvTransitionAnimationClass EvTransitionAnimationClass
Functions
GType ev_transition_animation_get_type (void)
EvTransitionAnimation * ev_transition_animation_new (EvTransitionEffect *effect)
void ev_transition_animation_set_origin_surface (EvTransitionAnimation *animation, cairo_surface_t *origin_surface)
void ev_transition_animation_set_dest_surface (EvTransitionAnimation *animation, cairo_surface_t *origin_surface)
gint ev_transition_animation_get_page_from (EvTransitionAnimation *animation)
gint ev_transition_animation_get_page_to (EvTransitionAnimation *animation)
void ev_transition_animation_paint (EvTransitionAnimation *animation, cairo_t *cr, GdkRectangle page_area)
gboolean ev_transition_animation_ready (EvTransitionAnimation *animation)
Macro Definition Documentation
EV_IS_TRANSITION_ANIMATION
#define EV_IS_TRANSITION_ANIMATION (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EV_TYPE_TRANSITION_ANIMATION))
Definition at line 38 of file ev-transition-animation.h.
EV_IS_TRANSITION_ANIMATION_CLASS
#define EV_IS_TRANSITION_ANIMATION_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EV_TYPE_TRANSITION_ANIMATION))
Definition at line 39 of file ev-transition-animation.h.
EV_TRANSITION_ANIMATION
#define EV_TRANSITION_ANIMATION (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EV_TYPE_TRANSITION_ANIMATION, EvTransitionAnimation))
Definition at line 36 of file ev-transition-animation.h.
EV_TRANSITION_ANIMATION_CLASS
#define EV_TRANSITION_ANIMATION_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EV_TYPE_TRANSITION_ANIMATION, EvTransitionAnimationClass))
Definition at line 37 of file ev-transition-animation.h.
EV_TRANSITION_ANIMATION_GET_CLASS
#define EV_TRANSITION_ANIMATION_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EV_TYPE_TRANSITION_ANIMATION, EvTransitionAnimationClass))
Definition at line 40 of file ev-transition-animation.h.
EV_TYPE_TRANSITION_ANIMATION
#define EV_TYPE_TRANSITION_ANIMATION (ev_transition_animation_get_type ())
Definition at line 35 of file ev-transition-animation.h.
Typedef Documentation
EvTransitionAnimation
typedef struct EvTransitionAnimation EvTransitionAnimation
Definition at line 42 of file ev-transition-animation.h.
EvTransitionAnimationClass
typedef struct EvTransitionAnimationClass EvTransitionAnimationClass
Definition at line 43 of file ev-transition-animation.h.
Function Documentation
ev_transition_animation_get_page_from()
gint ev_transition_animation_get_page_from (EvTransitionAnimation * animation)
ev_transition_animation_get_page_to()
gint ev_transition_animation_get_page_to (EvTransitionAnimation * animation)
ev_transition_animation_get_type()
GType ev_transition_animation_get_type (void)
ev_transition_animation_new()
EvTransitionAnimation * ev_transition_animation_new (EvTransitionEffect * effect)
Definition at line 600 of file ev-transition-animation.c.
References EV_IS_TRANSITION_EFFECT, EV_TYPE_TRANSITION_ANIMATION, and NULL.
ev_transition_animation_paint()
void ev_transition_animation_paint (EvTransitionAnimation * animation, cairo_t * cr, GdkRectangle page_area)
Definition at line 530 of file ev-transition-animation.c.
References EV_IS_TRANSITION_ANIMATION, EV_TIMELINE, ev_timeline_get_progress(), EV_TRANSITION_EFFECT_BLINDS, EV_TRANSITION_EFFECT_BOX, EV_TRANSITION_EFFECT_COVER, EV_TRANSITION_EFFECT_DISSOLVE, EV_TRANSITION_EFFECT_FADE, EV_TRANSITION_EFFECT_PUSH, EV_TRANSITION_EFFECT_REPLACE, EV_TRANSITION_EFFECT_SPLIT, EV_TRANSITION_EFFECT_UNCOVER, EV_TRANSITION_EFFECT_WIPE, NULL, and type.
ev_transition_animation_ready()
gboolean ev_transition_animation_ready (EvTransitionAnimation * animation)
Definition at line 662 of file ev-transition-animation.c.
References EV_IS_TRANSITION_ANIMATION, FALSE, and NULL.
ev_transition_animation_set_dest_surface()
void ev_transition_animation_set_dest_surface (EvTransitionAnimation * animation, cairo_surface_t * origin_surface)
Definition at line 636 of file ev-transition-animation.c.
References EV_IS_TRANSITION_ANIMATION, EV_TIMELINE, and ev_timeline_start().
ev_transition_animation_set_origin_surface()
void ev_transition_animation_set_origin_surface (EvTransitionAnimation * animation, cairo_surface_t * origin_surface)
Definition at line 610 of file ev-transition-animation.c.
References EV_IS_TRANSITION_ANIMATION, EV_TIMELINE, and ev_timeline_start().