MATE Desktop Environment: ev-view.c File Reference
ev-view.c File Reference
#include "config.h"
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
#include <gdk/gdkkeysyms.h>
#include "ev-mapping-list.h"
#include "ev-document-forms.h"
#include "ev-document-images.h"
#include "ev-document-links.h"
#include "ev-document-layers.h"
#include "ev-document-misc.h"
#include "ev-document-text.h"
#include "ev-pixbuf-cache.h"
#include "ev-page-cache.h"
#include "ev-view-marshal.h"
#include "ev-document-annotations.h"
#include "ev-annotation-window.h"
#include "ev-view.h"
#include "ev-view-accessible.h"
#include "ev-view-private.h"
#include "ev-view-type-builtins.h"
Macros
#define ZOOM_IN_FACTOR 1.2
#define ZOOM_OUT_FACTOR (1.0/ZOOM_IN_FACTOR)
#define SCROLL_TIME 150
#define EV_STYLE_CLASS_DOCUMENT_PAGE "document-page"
#define EV_STYLE_CLASS_INVERTED "inverted"
#define EV_HEIGHT_TO_PAGE_CACHE_KEY "ev-height-to-page-cache"
#define MARGIN 5
#define CURSOR_ON_MULTIPLIER 2
#define CURSOR_OFF_MULTIPLIER 1
#define CURSOR_PEND_MULTIPLIER 3
#define CURSOR_DIVIDER 3
#define PAN_ACTION_DISTANCE 200
#define EPSILON 0.0000001
Enumerations
enum {
SIGNAL_SCROLL , SIGNAL_HANDLE_LINK , SIGNAL_EXTERNAL_LINK , SIGNAL_POPUP_MENU ,
SIGNAL_SELECTION_CHANGED , SIGNAL_SYNC_SOURCE , SIGNAL_ANNOT_ADDED , SIGNAL_ANNOT_REMOVED ,
SIGNAL_LAYERS_CHANGED , SIGNAL_MOVE_CURSOR , SIGNAL_CURSOR_MOVED , N_SIGNALS
}
enum { TARGET_DND_URI , TARGET_DND_TEXT , TARGET_DND_IMAGE }
enum {
PROP_0 , PROP_IS_LOADING , PROP_HADJUSTMENT , PROP_VADJUSTMENT ,
PROP_HSCROLL_POLICY , PROP_VSCROLL_POLICY , PROP_CAN_ZOOM_IN , PROP_CAN_ZOOM_OUT
}
enum EvViewFindDirection { EV_VIEW_FIND_NEXT , EV_VIEW_FIND_PREV }
Functions
G_DEFINE_TYPE_WITH_CODE (EvView, ev_view, GTK_TYPE_CONTAINER, G_IMPLEMENT_INTERFACE(GTK_TYPE_SCROLLABLE, NULL))
void ev_view_scroll (EvView *view, GtkScrollType scroll, gboolean horizontal)
void _get_page_size_for_scale_and_rotation (EvDocument *document, gint page, gdouble scale, gint rotation, gint *page_width, gint *page_height)
gboolean ev_view_get_page_extents (EvView *view, gint page, GdkRectangle *page_area, GtkBorder *border)
void _ev_view_transform_view_point_to_doc_point (EvView *view, GdkPoint *view_point, GdkRectangle *page_area, double *doc_point_x, double *doc_point_y)
void _ev_view_transform_view_rect_to_doc_rect (EvView *view, GdkRectangle *view_rect, GdkRectangle *page_area, EvRectangle *doc_rect)
void _ev_view_transform_doc_point_to_view_point (EvView *view, int page, EvPoint *doc_point, GdkPoint *view_point)
void _ev_view_transform_doc_rect_to_view_rect (EvView *view, int page, EvRectangle *doc_rect, GdkRectangle *view_rect)
void ev_view_handle_link (EvView *view, EvLink *link)
void _ev_view_set_focused_element (EvView *view, EvMapping *element_mapping, gint page)
void _ev_view_focus_form_field (EvView *view, EvFormField *field)
void ev_view_focus_annotation (EvView *view, EvMapping *annot_mapping)
void ev_view_begin_add_annotation (EvView *view, EvAnnotationType annot_type)
void ev_view_cancel_add_annotation (EvView *view)
void ev_view_remove_annotation (EvView *view, EvAnnotation *annot)
gboolean ev_view_supports_caret_navigation (EvView *view)
void ev_view_set_caret_navigation_enabled (EvView *view, gboolean enabled)
gboolean ev_view_is_caret_navigation_enabled (EvView *view)
void ev_view_set_caret_cursor_position (EvView *view, guint page, guint offset)
gint _ev_view_get_caret_cursor_offset_at_doc_point (EvView *view, gint page, gdouble doc_x, gdouble doc_y)
void _ev_view_get_selection_colors (EvView *view, GdkRGBA *bg_color, GdkRGBA *fg_color)
GtkWidget * ev_view_new (void)
void ev_view_set_page_cache_size (EvView *view, gsize cache_size)
void ev_view_set_loading (EvView *view, gboolean loading)
gboolean ev_view_is_loading (EvView *view)
void ev_view_autoscroll_start (EvView *view)
void ev_view_autoscroll_stop (EvView *view)
void ev_view_set_model (EvView *view, EvDocumentModel *model)
void ev_view_reload (EvView *view)
gboolean ev_view_can_zoom_in (EvView *view)
gboolean ev_view_can_zoom_out (EvView *view)
void ev_view_zoom (EvView *view, gdouble factor)
void ev_view_zoom_in (EvView *view)
void ev_view_zoom_out (EvView *view)
void ev_view_zoom_reset (EvView *view)
void ev_view_find_changed (EvView *view, GList **results, gint page)
void ev_view_find_next (EvView *view)
void ev_view_find_previous (EvView *view)
void ev_view_find_set_result (EvView *view, gint page, gint result)
void ev_view_find_search_changed (EvView *view)
void ev_view_find_set_highlight_search (EvView *view, gboolean value)
void ev_view_find_cancel (EvView *view)
void ev_view_select_all (EvView *view)
gboolean ev_view_get_has_selection (EvView *view)
void _ev_view_clear_selection (EvView *view)
void _ev_view_set_selection (EvView *view, GdkPoint *start_point, GdkPoint *end_point)
void ev_view_copy (EvView *ev_view)
void ev_view_copy_link_address (EvView *view, EvLinkAction *action)
void ev_view_hide_cursor (EvView *view)
void ev_view_show_cursor (EvView *view)
gboolean ev_view_next_page (EvView *view)
gboolean ev_view_previous_page (EvView *view)
void ev_view_disconnect_handlers (EvView *view)
Macro Definition Documentation
CURSOR_DIVIDER
#define CURSOR_DIVIDER 3
Definition at line 3247 of file ev-view.c.
CURSOR_OFF_MULTIPLIER
#define CURSOR_OFF_MULTIPLIER 1
Definition at line 3245 of file ev-view.c.
CURSOR_ON_MULTIPLIER
#define CURSOR_ON_MULTIPLIER 2
Definition at line 3244 of file ev-view.c.
CURSOR_PEND_MULTIPLIER
#define CURSOR_PEND_MULTIPLIER 3
Definition at line 3246 of file ev-view.c.
EPSILON
#define EPSILON 0.0000001
Definition at line 6940 of file ev-view.c.
EV_HEIGHT_TO_PAGE_CACHE_KEY
#define EV_HEIGHT_TO_PAGE_CACHE_KEY "ev-height-to-page-cache"
EV_STYLE_CLASS_DOCUMENT_PAGE
#define EV_STYLE_CLASS_DOCUMENT_PAGE "document-page"
Definition at line 105 of file ev-view.c.
EV_STYLE_CLASS_INVERTED
#define EV_STYLE_CLASS_INVERTED "inverted"
Definition at line 106 of file ev-view.c.
MARGIN
#define MARGIN 5
Definition at line 1044 of file ev-view.c.
PAN_ACTION_DISTANCE
#define PAN_ACTION_DISTANCE 200
SCROLL_TIME
#define SCROLL_TIME 150
Definition at line 103 of file ev-view.c.
ZOOM_IN_FACTOR
#define ZOOM_IN_FACTOR 1.2
Definition at line 100 of file ev-view.c.
ZOOM_OUT_FACTOR
#define ZOOM_OUT_FACTOR (1.0/ZOOM_IN_FACTOR)
Definition at line 101 of file ev-view.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SIGNAL_SCROLL
SIGNAL_HANDLE_LINK
SIGNAL_EXTERNAL_LINK
SIGNAL_POPUP_MENU
SIGNAL_SELECTION_CHANGED
SIGNAL_SYNC_SOURCE
SIGNAL_ANNOT_ADDED
SIGNAL_ANNOT_REMOVED
SIGNAL_LAYERS_CHANGED
SIGNAL_MOVE_CURSOR
SIGNAL_CURSOR_MOVED
N_SIGNALS
Definition at line 49 of file ev-view.c.
anonymous enum
anonymous enum
Enumerator
TARGET_DND_URI
TARGET_DND_TEXT
TARGET_DND_IMAGE
Definition at line 64 of file ev-view.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_IS_LOADING
PROP_HADJUSTMENT
PROP_VADJUSTMENT
PROP_HSCROLL_POLICY
PROP_VSCROLL_POLICY
PROP_CAN_ZOOM_IN
PROP_CAN_ZOOM_OUT
Definition at line 70 of file ev-view.c.
EvViewFindDirection
enum EvViewFindDirection
Enumerator
EV_VIEW_FIND_NEXT
EV_VIEW_FIND_PREV
Definition at line 83 of file ev-view.c.
Function Documentation
_ev_view_clear_selection()
void _ev_view_clear_selection (EvView * view)
Definition at line 7996 of file ev-view.c.
_ev_view_focus_form_field()
void _ev_view_focus_form_field (EvView * view, EvFormField * field)
Definition at line 2592 of file ev-view.c.
References _ev_view_set_focused_element(), _EvMapping::area, EV_IS_FORM_FIELD_BUTTON, EV_IS_FORM_FIELD_CHOICE, EV_IS_FORM_FIELD_SIGNATURE, EV_IS_FORM_FIELD_TEXT, ev_mapping_list_find(), ev_page_cache_get_form_field_mapping(), _EvPage::index, _EvFormField::is_read_only, NULL, _EvFormField::page, and _EvView::page_cache.
_ev_view_get_caret_cursor_offset_at_doc_point()
gint _ev_view_get_caret_cursor_offset_at_doc_point (EvView * view, gint page, gdouble doc_x, gdouble doc_y)
Definition at line 4284 of file ev-view.c.
References ev_page_cache_get_text_layout(), NULL, _EvView::page_cache, _EvRectangle::x1, _EvRectangle::x2, and _EvRectangle::y1.
_ev_view_get_selection_colors()
void _ev_view_get_selection_colors (EvView * view, GdkRGBA * bg_color, GdkRGBA * fg_color)
Definition at line 5746 of file ev-view.c.
_ev_view_set_focused_element()
void _ev_view_set_focused_element (EvView * view, EvMapping * element_mapping, gint page)
Definition at line 2079 of file ev-view.c.
References ev_document_model_set_page(), _EvView::focused_element, _EvView::focused_element_page, _EvView::model, NULL, _EvView::scroll_x, _EvView::scroll_y, and TRUE.
Referenced by _ev_view_focus_form_field(), ev_view_focus_annotation(), and ev_view_remove_annotation().
_ev_view_set_selection()
void _ev_view_set_selection (EvView * view, GdkPoint * start_point, GdkPoint * end_point)
Definition at line 8002 of file ev-view.c.
References EV_SELECTION_STYLE_GLYPH.
_ev_view_transform_doc_point_to_view_point()
void _ev_view_transform_doc_point_to_view_point (EvView * view, int page, EvPoint * doc_point, GdkPoint * view_point)
Definition at line 1318 of file ev-view.c.
References ev_view_get_page_extents(), _EvView::rotation, _EvView::scale, EvPoint::x, and EvPoint::y.
_ev_view_transform_doc_rect_to_view_rect()
void _ev_view_transform_doc_rect_to_view_rect (EvView * view, int page, EvRectangle * doc_rect, GdkRectangle * view_rect)
Definition at line 1355 of file ev-view.c.
References ev_view_get_page_extents(), _EvView::rotation, _EvView::scale, _EvRectangle::x1, _EvRectangle::x2, _EvRectangle::y1, and _EvRectangle::y2.
Referenced by _transform_doc_rect_to_atk_rect(), and ev_view_accessible_is_doc_rect_showing().
_ev_view_transform_view_point_to_doc_point()
void _ev_view_transform_view_point_to_doc_point (EvView * view, GdkPoint * view_point, GdkRectangle * page_area, double * doc_point_x, double * doc_point_y)
Definition at line 1295 of file ev-view.c.
References _EvView::scale.
_ev_view_transform_view_rect_to_doc_rect()
void _ev_view_transform_view_rect_to_doc_rect (EvView * view, GdkRectangle * view_rect, GdkRectangle * page_area, EvRectangle * doc_rect)
Definition at line 1306 of file ev-view.c.
References _EvView::scale, _EvRectangle::x1, _EvRectangle::x2, _EvRectangle::y1, and _EvRectangle::y2.
_get_page_size_for_scale_and_rotation()
void _get_page_size_for_scale_and_rotation (EvDocument * document, gint page, gdouble scale, gint rotation, gint * page_width, gint * page_height)
Definition at line 1100 of file ev-view.c.
References ev_document_get_page_size().
Referenced by ev_pixbuf_cache_reload_page().
ev_view_autoscroll_start()
void ev_view_autoscroll_start (EvView * view)
Definition at line 6773 of file ev-view.c.
References AutoScrollInfo::autoscrolling, ev_document_misc_get_pointer_position(), EV_IS_VIEW, _EvView::scroll_info, AutoScrollInfo::timeout_id, and TRUE.
ev_view_autoscroll_stop()
void ev_view_autoscroll_stop (EvView * view)
Definition at line 6792 of file ev-view.c.
References AutoScrollInfo::autoscrolling, ev_document_misc_get_pointer_position(), EV_IS_VIEW, FALSE, _EvView::scroll_info, and AutoScrollInfo::timeout_id.
ev_view_begin_add_annotation()
void ev_view_begin_add_annotation (EvView * view, EvAnnotationType annot_type)
Definition at line 3149 of file ev-view.c.
References _EvView::adding_annot, _EvView::adding_annot_type, EV_ANNOTATION_TYPE_UNKNOWN, EV_VIEW_CURSOR_ADD, and TRUE.
ev_view_can_zoom_in()
gboolean ev_view_can_zoom_in (EvView * view)
Definition at line 7116 of file ev-view.c.
References _EvView::can_zoom_in.
ev_view_can_zoom_out()
gboolean ev_view_can_zoom_out (EvView * view)
Definition at line 7122 of file ev-view.c.
References _EvView::can_zoom_out.
ev_view_cancel_add_annotation()
void ev_view_cancel_add_annotation (EvView * view)
Definition at line 3164 of file ev-view.c.
References _EvView::adding_annot, ev_document_misc_get_pointer_position(), and FALSE.
ev_view_copy()
void ev_view_copy (EvView * ev_view)
Definition at line 8053 of file ev-view.c.
References _EvView::document, and EV_IS_SELECTION.
ev_view_copy_link_address()
void ev_view_copy_link_address (EvView * view, EvLinkAction * action)
Definition at line 8141 of file ev-view.c.
References action, ev_link_action_get_uri(), and _EvView::link_selected.
ev_view_disconnect_handlers()
void ev_view_disconnect_handlers (EvView * view)
ev_view_disconnect_handlers @view: EvView instance
Disconnect all signal handlers from the model, to ensure error free operation of the webview, we have an equivalent function for the webview.
Definition at line 8229 of file ev-view.c.
References _EvView::model.
ev_view_find_cancel()
void ev_view_find_cancel (EvView * view)
Definition at line 7621 of file ev-view.c.
References _EvView::find_pages, and NULL.
ev_view_find_changed()
void ev_view_find_changed (EvView * view, GList ** results, gint page)
Definition at line 7550 of file ev-view.c.
References _EvView::current_page, EV_VIEW_FIND_NEXT, _EvView::find_pages, _EvView::jump_to_find_result, and TRUE.
ev_view_find_next()
void ev_view_find_next (EvView * view)
Definition at line 7565 of file ev-view.c.
References _EvView::current_page, EV_VIEW_FIND_NEXT, and _EvView::find_result.
ev_view_find_previous()
void ev_view_find_previous (EvView * view)
Definition at line 7583 of file ev-view.c.
References _EvView::current_page, EV_VIEW_FIND_PREV, _EvView::find_result, and MAX.
ev_view_find_search_changed()
void ev_view_find_search_changed (EvView * view)
Definition at line 7606 of file ev-view.c.
References _EvView::find_pages, _EvView::jump_to_find_result, NULL, and TRUE.
ev_view_find_set_highlight_search()
void ev_view_find_set_highlight_search (EvView * view, gboolean value)
Definition at line 7614 of file ev-view.c.
References _EvView::highlight_find_results.
ev_view_find_set_result()
void ev_view_find_set_result (EvView * view, gint page, gint result)
Definition at line 7598 of file ev-view.c.
References ev_document_model_set_page(), _EvView::find_result, and _EvView::model.
ev_view_focus_annotation()
void ev_view_focus_annotation (EvView * view, EvMapping * annot_mapping)
Definition at line 3137 of file ev-view.c.
References _ev_view_set_focused_element(), _EvMapping::data, _EvView::document, EV_ANNOTATION, ev_annotation_get_page_index(), and EV_IS_DOCUMENT_ANNOTATIONS.
ev_view_get_has_selection()
gboolean ev_view_get_has_selection (EvView * view)
Definition at line 7990 of file ev-view.c.
References NULL, _EvView::selection_info, and SelectionInfo::selections.
ev_view_get_page_extents()
gboolean ev_view_get_page_extents (EvView * view, gint page, GdkRectangle * page_area, GtkBorder * border)
Definition at line 1179 of file ev-view.c.
References _EvView::continuous, _EvView::document, ev_document_get_n_pages(), MAX, NULL, _EvView::spacing, and TRUE.
Referenced by _ev_view_transform_doc_point_to_view_point(), and _ev_view_transform_doc_rect_to_view_rect().
ev_view_handle_link()
void ev_view_handle_link (EvView * view, EvLink * link)
Definition at line 1837 of file ev-view.c.
References action, _EvView::current_page, dest, _EvView::document, EV_DOCUMENT_LAYERS, ev_document_layers_hide_layer(), ev_document_layers_layer_is_visible(), ev_document_layers_show_layer(), EV_LAYER, ev_link_action_get_action_type(), ev_link_action_get_dest(), ev_link_action_get_hide_list(), ev_link_action_get_show_list(), ev_link_action_get_toggle_list(), EV_LINK_ACTION_TYPE_EXTERNAL_URI, EV_LINK_ACTION_TYPE_GOTO_DEST, EV_LINK_ACTION_TYPE_GOTO_REMOTE, EV_LINK_ACTION_TYPE_LAUNCH, EV_LINK_ACTION_TYPE_LAYERS_STATE, EV_LINK_ACTION_TYPE_NAMED, ev_link_get_action(), NULL, SIGNAL_EXTERNAL_LINK, SIGNAL_HANDLE_LINK, SIGNAL_LAYERS_CHANGED, and type.
Referenced by ev_window_open_document().
ev_view_hide_cursor()
void ev_view_hide_cursor (EvView * view)
Definition at line 8178 of file ev-view.c.
References EV_VIEW_CURSOR_HIDDEN.
ev_view_is_caret_navigation_enabled()
gboolean ev_view_is_caret_navigation_enabled (EvView * view)
Definition at line 3494 of file ev-view.c.
References _EvView::caret_enabled, EV_IS_VIEW, and FALSE.
Referenced by G_DEFINE_TYPE_WITH_CODE().
ev_view_is_loading()
gboolean ev_view_is_loading (EvView * view)
Definition at line 6735 of file ev-view.c.
References _EvView::loading.
ev_view_new()
GtkWidget * ev_view_new (void)
Definition at line 6654 of file ev-view.c.
References EV_TYPE_VIEW, and NULL.
ev_view_next_page()
gboolean ev_view_next_page (EvView * view)
Definition at line 8190 of file ev-view.c.
References _EvView::current_page, ev_document_model_set_page(), EV_IS_VIEW, FALSE, _EvView::model, and TRUE.
Referenced by ev_view_scroll().
ev_view_previous_page()
gboolean ev_view_previous_page (EvView * view)
Definition at line 8206 of file ev-view.c.
References _EvView::current_page, ev_document_model_set_page(), EV_IS_VIEW, FALSE, _EvView::model, and TRUE.
Referenced by ev_view_scroll().
ev_view_reload()
void ev_view_reload (EvView * view)
Definition at line 7094 of file ev-view.c.
References ev_pixbuf_cache_clear(), and _EvView::pixbuf_cache.
ev_view_remove_annotation()
void ev_view_remove_annotation (EvView * view, EvAnnotation * annot)
Definition at line 3177 of file ev-view.c.
References _ev_view_set_focused_element(), _EvView::document, ev_annotation_get_page_index(), EV_DOCUMENT_ANNOTATIONS, ev_document_annotations_remove_annotation(), ev_document_doc_mutex_lock(), ev_document_doc_mutex_unlock(), EV_IS_ANNOTATION, EV_IS_ANNOTATION_MARKUP, EV_IS_VIEW, ev_page_cache_mark_dirty(), EV_PAGE_DATA_INCLUDE_ANNOTS, NULL, _EvView::page_cache, SIGNAL_ANNOT_REMOVED, EvViewWindowChild::window, and _EvView::window_children.
ev_view_scroll()
void ev_view_scroll (EvView * view, GtkScrollType scroll, gboolean horizontal)
Definition at line 938 of file ev-view.c.
References _EvView::current_page, _EvView::document, ev_document_get_n_pages(), ev_view_next_page(), ev_view_previous_page(), FALSE, _EvView::hadjustment, _EvView::jump_to_find_result, _EvView::key_binding_handled, MAX, MIN, TRUE, and _EvView::vadjustment.
ev_view_select_all()
void ev_view_select_all (EvView * view)
Definition at line 7960 of file ev-view.c.
References _EvView::document, ev_document_get_n_pages(), EV_SELECTION_STYLE_GLYPH, NULL, EvViewSelection::page, EvViewSelection::rect, _EvView::rotation, EvViewSelection::style, _EvRectangle::x1, _EvRectangle::x2, _EvRectangle::y1, and _EvRectangle::y2.
ev_view_set_caret_cursor_position()
void ev_view_set_caret_cursor_position (EvView * view, guint page, guint offset)
Definition at line 3502 of file ev-view.c.
References _EvView::caret_enabled, _EvView::cursor_offset, _EvView::cursor_page, _EvView::document, ev_document_get_n_pages(), EV_IS_DOCUMENT, EV_IS_VIEW, and SIGNAL_CURSOR_MOVED.
ev_view_set_caret_navigation_enabled()
void ev_view_set_caret_navigation_enabled (EvView * view, gboolean enabled)
Definition at line 3479 of file ev-view.c.
References _EvView::caret_enabled, and EV_IS_VIEW.
ev_view_set_loading()
void ev_view_set_loading (EvView * view, gboolean loading)
Definition at line 6724 of file ev-view.c.
References _EvView::loading.
ev_view_set_model()
void ev_view_set_model (EvView * view, EvDocumentModel * model)
Definition at line 7010 of file ev-view.c.
References _EvView::accessible, _EvView::continuous, ev_document_model_get_continuous(), ev_document_model_get_fullscreen(), ev_document_model_get_page_layout(), ev_document_model_get_rotation(), ev_document_model_get_scale(), ev_document_model_get_sizing_mode(), EV_IS_DOCUMENT_MODEL, EV_IS_VIEW, EV_VIEW_ACCESSIBLE, ev_view_accessible_set_model(), _EvView::fullscreen, _EvView::model, NULL, _EvView::page_layout, _EvView::rotation, _EvView::scale, and _EvView::sizing_mode.
ev_view_set_page_cache_size()
void ev_view_set_page_cache_size (EvView * view, gsize cache_size)
ev_view_set_page_cache_size: @view: @cache_size:
Sets the maximum size in bytes that will be used to cache rendered pages. Use 0 to disable caching rendered pages.
Note that this limit doesn't affect the current visible page range, which will always be rendered. In order to limit the total memory used you have to use ev_document_model_set_max_scale() too.
Definition at line 6712 of file ev-view.c.
References ev_pixbuf_cache_set_max_size(), _EvView::pixbuf_cache, and _EvView::pixbuf_cache_size.
ev_view_show_cursor()
void ev_view_show_cursor (EvView * view)
Definition at line 8184 of file ev-view.c.
References EV_VIEW_CURSOR_NORMAL.
ev_view_supports_caret_navigation()
gboolean ev_view_supports_caret_navigation (EvView * view)
Definition at line 3464 of file ev-view.c.
References _EvView::document, EV_DOCUMENT_TEXT_GET_IFACE, EV_IS_DOCUMENT_TEXT, FALSE, _EvDocumentTextInterface::get_text, _EvDocumentTextInterface::get_text_layout, and TRUE.
ev_view_zoom()
void ev_view_zoom (EvView * view, gdouble factor)
Definition at line 7128 of file ev-view.c.
References ev_document_model_get_scale(), ev_document_model_set_scale(), EV_SIZING_FREE, _EvView::model, _EvView::pending_scroll, SCROLL_TO_CENTER, and _EvView::sizing_mode.
Referenced by ev_view_zoom_in(), and ev_view_zoom_out().
ev_view_zoom_in()
void ev_view_zoom_in (EvView * view)
Definition at line 7140 of file ev-view.c.
References ev_view_zoom(), and ZOOM_IN_FACTOR.
ev_view_zoom_out()
void ev_view_zoom_out (EvView * view)
Definition at line 7146 of file ev-view.c.
References ev_view_zoom(), and ZOOM_OUT_FACTOR.
ev_view_zoom_reset()
void ev_view_zoom_reset (EvView * view)
Definition at line 7152 of file ev-view.c.
References ev_document_model_set_scale(), EV_SIZING_FREE, _EvView::model, and _EvView::sizing_mode.
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (EvView , ev_view , GTK_TYPE_CONTAINER , G_IMPLEMENT_INTERFACE(GTK_TYPE_SCROLLABLE, NULL))
Definition at line 291 of file ev-view.c.
References _EvView::document, _EvHeightToPageCache::dual_even_left, _EvView::dual_even_left, _EvHeightToPageCache::dual_height_to_page, ev_document_get_n_pages(), ev_document_get_page_size(), ev_document_is_page_size_uniform(), _EvHeightToPageCache::height_to_page, MAX, _EvHeightToPageCache::rotation, and _EvView::rotation.