MATE Desktop Environment: ev-window.h File Reference
ev-window.h File Reference
#include <glib.h>
#include <gtk/gtk.h>
#include "ev-link.h"
Classes
struct EvPrintRange
struct _EvWindow
struct _EvWindowClass
Macros
#define EV_TYPE_WINDOW (ev_window_get_type())
#define EV_WINDOW(object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_WINDOW, EvWindow))
#define EV_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_WINDOW, EvWindowClass))
#define EV_IS_WINDOW(object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_WINDOW))
#define EV_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_WINDOW))
#define EV_WINDOW_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_WINDOW, EvWindowClass))
Typedefs
typedef struct _EvWindow EvWindow
typedef struct _EvWindowClass EvWindowClass
typedef struct _EvWindowPrivate EvWindowPrivate
Enumerations
enum EvWindowRunMode { EV_WINDOW_MODE_NORMAL , EV_WINDOW_MODE_FULLSCREEN , EV_WINDOW_MODE_PRESENTATION }
enum EvPrintPageSet { EV_PRINT_PAGE_SET_ALL , EV_PRINT_PAGE_SET_EVEN , EV_PRINT_PAGE_SET_ODD }
Functions
GType ev_window_get_type (void)
GtkWidget * ev_window_new (void)
const char * ev_window_get_uri (EvWindow *ev_window)
void ev_window_open_uri (EvWindow *ev_window, const char *uri, EvLinkDest *dest, EvWindowRunMode mode, const gchar *search_string)
void ev_window_open_document (EvWindow *ev_window, EvDocument *document, EvLinkDest *dest, EvWindowRunMode mode, const gchar *search_string)
gboolean ev_window_is_empty (const EvWindow *ev_window)
void ev_window_print_range (EvWindow *ev_window, int first_page, int last_page)
const gchar * ev_window_get_dbus_object_path (EvWindow *ev_window)
Macro Definition Documentation
EV_IS_WINDOW
#define EV_IS_WINDOW (object) (G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_WINDOW))
Definition at line 57 of file ev-window.h.
EV_IS_WINDOW_CLASS
#define EV_IS_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_WINDOW))
Definition at line 58 of file ev-window.h.
EV_TYPE_WINDOW
#define EV_TYPE_WINDOW (ev_window_get_type())
Definition at line 54 of file ev-window.h.
EV_WINDOW
#define EV_WINDOW (object) (G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_WINDOW, EvWindow))
Definition at line 55 of file ev-window.h.
EV_WINDOW_CLASS
#define EV_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_WINDOW, EvWindowClass))
Definition at line 56 of file ev-window.h.
EV_WINDOW_GET_CLASS
#define EV_WINDOW_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_WINDOW, EvWindowClass))
Definition at line 59 of file ev-window.h.
Typedef Documentation
EvWindow
typedef struct _EvWindow EvWindow
Definition at line 50 of file ev-window.h.
EvWindowClass
typedef struct _EvWindowClass EvWindowClass
Definition at line 51 of file ev-window.h.
EvWindowPrivate
typedef struct _EvWindowPrivate EvWindowPrivate
Definition at line 52 of file ev-window.h.
Enumeration Type Documentation
EvPrintPageSet
enum EvPrintPageSet
Enumerator
EV_PRINT_PAGE_SET_ALL
EV_PRINT_PAGE_SET_EVEN
EV_PRINT_PAGE_SET_ODD
Definition at line 44 of file ev-window.h.
EvWindowRunMode
enum EvWindowRunMode
Enumerator
EV_WINDOW_MODE_NORMAL
EV_WINDOW_MODE_FULLSCREEN
EV_WINDOW_MODE_PRESENTATION
Definition at line 33 of file ev-window.h.
Function Documentation
ev_window_get_dbus_object_path()
const gchar * ev_window_get_dbus_object_path (EvWindow * ev_window)
Definition at line 8426 of file ev-window.c.
References NULL, and _EvWindow::priv.
ev_window_get_type()
GType ev_window_get_type (void)
ev_window_get_uri()
const char * ev_window_get_uri (EvWindow * ev_window)
ev_window_get_uri: @ev_window: The instance of the EvWindow.
It returns the uri of the document showed in the EvWindow.
Returns: the uri of the document showed in the EvWindow.
Definition at line 2075 of file ev-window.c.
References _EvWindow::priv.
ev_window_is_empty()
gboolean ev_window_is_empty (const EvWindow * ev_window)
ev_window_is_empty: @ev_window: The instance of the EvWindow.
It does look if there is any document loaded or if there is any job to load a document.
Returns: TRUE if there isn't any document loaded or any any documente to be loaded, FALSE in other case.
Definition at line 789 of file ev-window.c.
References EV_IS_WINDOW, FALSE, NULL, and _EvWindow::priv.
ev_window_new()
GtkWidget * ev_window_new (void)
ev_window_new:
Creates a #GtkWidget that represents the window.
Returns: the #GtkWidget that represents the window.
Definition at line 8413 of file ev-window.c.
References EV_TYPE_WINDOW, and NULL.
Referenced by ev_application_open_window().
ev_window_open_document()
void ev_window_open_document (EvWindow * ev_window, EvDocument * document, EvLinkDest * dest, EvWindowRunMode mode, const gchar * search_string)
Definition at line 2461 of file ev-window.c.
References dest, EGG_FIND_BAR, egg_find_bar_set_search_string(), ev_document_get_uri(), ev_document_model_set_document(), ev_file_monitor_new(), EV_IS_DOCUMENT_FIND, ev_link_action_new_dest(), ev_link_new(), EV_VIEW, ev_view_handle_link(), EV_WINDOW_MODE_FULLSCREEN, EV_WINDOW_MODE_PRESENTATION, FALSE, _EvDocument::iswebdocument, NULL, and _EvWindow::priv.
ev_window_open_uri()
void ev_window_open_uri (EvWindow * ev_window, const char * uri, EvLinkDest * dest, EvWindowRunMode mode, const gchar * search_string)
Definition at line 2377 of file ev-window.c.
References dest, ev_bookmarks_new(), ev_is_metadata_supported_for_file(), ev_job_load_new(), EV_JOB_PRIORITY_NONE, ev_job_scheduler_push_job(), ev_metadata_new(), EV_SIDEBAR_BOOKMARKS, ev_sidebar_bookmarks_set_bookmarks(), FALSE, NULL, _EvWindow::priv, and source_file.
ev_window_print_range()
void ev_window_print_range (EvWindow * ev_window, int first_page, int last_page)