MATE Desktop Environment: file-utils.c File Reference
file-utils.c File Reference
#include <config.h>
#include <pwd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <ctype.h>
#include <time.h>
#include <unistd.h>
#include <sys/param.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/types.h>
#include <dirent.h>
#include <glib.h>
#include <gio/gio.h>
#include "file-utils.h"
#include "glib-utils.h"
#include "fr-init.h"
Macros
#define _XOPEN_SOURCE 700
#define SPECIAL_DIR(x) ((strcmp ((x), "..") == 0) || (strcmp ((x), ".") == 0))
Functions
gboolean uri_exists (const char *uri)
gboolean uri_is_file (const char *uri)
gboolean uri_is_dir (const char *uri)
gboolean path_is_dir (const char *path)
gboolean uri_is_local (const char *uri)
char * get_dir_content_if_unique (const char *uri)
gboolean path_in_path (const char *dirname, const char *filename)
goffset get_file_size (const char *uri)
goffset get_file_size_for_path (const char *path)
time_t get_file_mtime (const char *uri)
time_t get_file_mtime_for_path (const char *path)
const gchar * file_name_from_path (const gchar *file_name)
char * dir_name_from_path (const gchar *path)
gchar * remove_level_from_path (const gchar *path)
char * remove_ending_separator (const char *path)
char * build_uri (const char *base,...)
gchar * remove_extension_from_path (const gchar *path)
gboolean make_directory_tree (GFile *dir, mode_t mode, GError **error)
gboolean ensure_dir_exists (const char *uri, mode_t mode, GError **error)
gboolean make_directory_tree_from_path (const char *path, mode_t mode, GError **error)
const char * get_file_extension (const char *filename)
gboolean file_extension_is (const char *filename, const char *ext)
gboolean is_mime_type (const char *mime_type, const char *pattern)
const char * get_file_mime_type (const char *uri, gboolean fast_file_type)
const char * get_file_mime_type_for_path (const char *filename, gboolean fast_file_type)
void path_list_free (GList *path_list)
GList * path_list_dup (GList *path_list)
guint64 get_dest_free_space (const char *path)
gboolean remove_directory (const char *uri)
gboolean remove_local_directory (const char *path)
char * get_temp_work_dir (const char *parent_folder)
gboolean is_temp_work_dir (const char *dir)
gboolean is_temp_dir (const char *dir)
gboolean file_list__match_pattern (const char *line, const char *pattern)
int file_list__get_index_from_pattern (const char *line, const char *pattern)
char * file_list__get_prev_field (const char *line, int start_from, int field_n)
gboolean check_permissions (const char *uri, int mode)
gboolean check_file_permissions (GFile *file, int mode)
gboolean is_program_in_path (const char *filename)
gboolean is_program_available (const char *filename, gboolean check)
const char * get_home_uri (void)
GFile * get_user_config_subdirectory (const char *child_name, gboolean create_child)
int uricmp (const char *uri1, const char *uri2)
char * get_alternative_uri (const char *folder_uri, const char *escaped_name)
char * get_alternative_uri_for_uri (const char *uri)
GList * gio_file_list_dup (GList *l)
void gio_file_list_free (GList *l)
void g_key_file_save (GKeyFile *key_file, GFile *file)
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Definition at line 23 of file file-utils.c.
SPECIAL_DIR
#define SPECIAL_DIR (x) ((strcmp ((x), "..") == 0) || (strcmp ((x), ".") == 0))
Definition at line 47 of file file-utils.c.
Function Documentation
build_uri()
char * build_uri (const char * base, ...)
Definition at line 398 of file file-utils.c.
References FALSE, and NULL.
Referenced by fr_window_paste_selection(), and get_dir_content_if_unique().
check_file_permissions()
gboolean check_file_permissions (GFile * file, int mode)
Definition at line 935 of file file-utils.c.
References FALSE, NULL, and TRUE.
Referenced by check_permissions().
check_permissions()
gboolean check_permissions (const char * uri, int mode)
Definition at line 920 of file file-utils.c.
References check_file_permissions().
Referenced by dlg_batch_add_files(), and fr_window_file_list_drag_data_get().
dir_name_from_path()
char * dir_name_from_path (const gchar * path)
Definition at line 337 of file file-utils.c.
References NULL.
ensure_dir_exists()
gboolean ensure_dir_exists (const char * uri, mode_t mode, GError ** error)
Definition at line 469 of file file-utils.c.
References error, FALSE, make_directory_tree(), NULL, and TRUE.
Referenced by eom_util_dot_dir(), fr_window_archive_extract(), gsm_util_get_empty_tmp_session_dir(), gsm_util_get_saved_session_dir(), and make_directory_tree_from_path().
file_extension_is()
gboolean file_extension_is (const char * filename, const char * ext)
Definition at line 546 of file file-utils.c.
References FALSE.
file_list__get_index_from_pattern()
int file_list__get_index_from_pattern (const char * line, const char * pattern)
Definition at line 873 of file file-utils.c.
References file_list__match_pattern().
file_list__get_prev_field()
char * file_list__get_prev_field (const char * line, int start_from, int field_n)
Definition at line 893 of file file-utils.c.
file_list__match_pattern()
gboolean file_list__match_pattern (const char * line, const char * pattern)
Definition at line 840 of file file-utils.c.
References FALSE.
Referenced by file_list__get_index_from_pattern().
file_name_from_path()
const gchar * file_name_from_path (const gchar * file_name)
Definition at line 313 of file file-utils.c.
References NULL.
Referenced by dlg_batch_add_files(), fr_archive_add(), fr_archive_extract_to_local(), fr_archive_remove(), fr_window_rename_selection(), get_alternative_uri_for_uri(), and rar_check_multi_volume().
g_key_file_save()
void g_key_file_save (GKeyFile * key_file, GFile * file)
Definition at line 1107 of file file-utils.c.
References error, FALSE, and NULL.
get_alternative_uri()
char * get_alternative_uri (const char * folder_uri, const char * escaped_name)
get_alternative_uri: @folder_uri: The URI of the containing folder @escaped_name: The URI-escaped name of the member to find a name for
Tries to find an unused name for @escaped_name in @folder_uri.
Returns: The full URI for the free slot (including directory)
Definition at line 1057 of file file-utils.c.
References NULL, and uri_exists().
Referenced by get_alternative_uri_for_uri().
get_alternative_uri_for_uri()
char * get_alternative_uri_for_uri (const char * uri)
Definition at line 1076 of file file-utils.c.
References file_name_from_path(), get_alternative_uri(), and remove_level_from_path().
get_dest_free_space()
guint64 get_dest_free_space (const char * path)
Definition at line 630 of file file-utils.c.
References NULL.
Referenced by get_temp_work_dir().
get_dir_content_if_unique()
char * get_dir_content_if_unique (const char * uri)
Definition at line 128 of file file-utils.c.
References build_uri(), name, NULL, and TRUE.
get_file_extension()
const char * get_file_extension (const char * filename)
Definition at line 509 of file file-utils.c.
References NULL, and test.
Referenced by get_archive_filename_extension().
get_file_mime_type()
const char * get_file_mime_type (const char * uri, gboolean fast_file_type)
Definition at line 567 of file file-utils.c.
References get_static_string(), and NULL.
Referenced by get_file_mime_type_for_path().
get_file_mime_type_for_path()
const char * get_file_mime_type_for_path (const char * filename, gboolean fast_file_type)
Definition at line 596 of file file-utils.c.
References get_file_mime_type(), mime_type, and NULL.
get_file_mtime()
time_t get_file_mtime (const char * uri)
Definition at line 293 of file file-utils.c.
Referenced by dlg_prop(), get_file_mtime_for_path(), and open_file_new().
get_file_mtime_for_path()
time_t get_file_mtime_for_path (const char * path)
Definition at line 299 of file file-utils.c.
References get_file_mtime(), and NULL.
Referenced by fr_archive_extract_to_local().
get_file_size()
goffset get_file_size (const char * uri)
Definition at line 224 of file file-utils.c.
References NULL.
Referenced by dlg_prop(), and get_file_size_for_path().
get_file_size_for_path()
goffset get_file_size_for_path (const char * path)
Definition at line 251 of file file-utils.c.
References get_file_size(), and NULL.
get_home_uri()
const char * get_home_uri (void)
Definition at line 1010 of file file-utils.c.
References NULL.
Referenced by dlg_batch_add_files(), fr_window_get_add_default_dir(), fr_window_get_extract_default_dir(), and fr_window_get_open_default_dir().
get_temp_work_dir()
char * get_temp_work_dir (const char * parent_folder)
Definition at line 755 of file file-utils.c.
References get_dest_free_space(), and NULL.
Referenced by fr_archive_add(), fr_archive_extract(), fr_archive_extract_to_local(), fr_archive_remove(), and fr_window_archive_save_as().
get_user_config_subdirectory()
GFile * get_user_config_subdirectory (const char * child_name, gboolean create_child)
Definition at line 1019 of file file-utils.c.
References error, make_directory_tree(), and NULL.
gio_file_list_dup()
GList * gio_file_list_dup (GList * l)
Definition at line 1089 of file file-utils.c.
References NULL.
gio_file_list_free()
void gio_file_list_free (GList * l)
Definition at line 1098 of file file-utils.c.
is_mime_type()
gboolean is_mime_type (const char * mime_type, const char * pattern)
Definition at line 560 of file file-utils.c.
References mime_type.
Referenced by caja_file_info_is_mime_type(), and get_mime_type_index().
is_program_available()
gboolean is_program_available (const char * filename, gboolean check)
Definition at line 1003 of file file-utils.c.
References is_program_in_path().
is_program_in_path()
gboolean is_program_in_path (const char * filename)
Definition at line 977 of file file-utils.c.
References FALSE, NULL, ProgramsCache, and TRUE.
Referenced by is_program_available().
is_temp_dir()
gboolean is_temp_dir (const char * dir)
Definition at line 825 of file file-utils.c.
References is_temp_work_dir(), path_in_path(), and TRUE.
is_temp_work_dir()
gboolean is_temp_work_dir (const char * dir)
Definition at line 801 of file file-utils.c.
References FALSE, NULL, and TRUE.
Referenced by is_temp_dir().
make_directory_tree()
gboolean make_directory_tree (GFile * dir, mode_t mode, GError ** error)
Definition at line 433 of file file-utils.c.
References error, FALSE, make_directory_tree(), NULL, and TRUE.
Referenced by ensure_dir_exists(), get_user_config_subdirectory(), and make_directory_tree().
make_directory_tree_from_path()
gboolean make_directory_tree_from_path (const char * path, mode_t mode, GError ** error)
Definition at line 494 of file file-utils.c.
References ensure_dir_exists(), error, and NULL.
path_in_path()
gboolean path_in_path (const char * dirname, const char * filename)
Definition at line 194 of file file-utils.c.
References FALSE, and NULL.
Referenced by is_temp_dir().
path_is_dir()
gboolean path_is_dir (const char * path)
Definition at line 109 of file file-utils.c.
References NULL, and uri_is_dir().
path_list_dup()
GList * path_list_dup (GList * path_list)
Definition at line 618 of file file-utils.c.
References NULL.
Referenced by fr_archive_add().
path_list_free()
void path_list_free (GList * path_list)
Definition at line 610 of file file-utils.c.
References NULL.
Referenced by activate_popup_open(), fr_archive_add(), fr_archive_extract_to_local(), fr_window_archive_add_files(), fr_window_file_list_drag_data_get(), fr_window_get_folder_tree_selection(), fr_window_open_files_with_application(), and open_with_cb().
remove_directory()
gboolean remove_directory (const char * uri)
Definition at line 703 of file file-utils.c.
References error, and NULL.
Referenced by remove_local_directory().
remove_ending_separator()
char * remove_ending_separator (const char * path)
Definition at line 383 of file file-utils.c.
References NULL.
Referenced by fr_window_rename_selection().
remove_extension_from_path()
gchar * remove_extension_from_path (const gchar * path)
Definition at line 418 of file file-utils.c.
References get_archive_filename_extension(), and NULL.
remove_level_from_path()
gchar * remove_level_from_path (const gchar * path)
Definition at line 360 of file file-utils.c.
References NULL.
Referenced by dlg_batch_add_files(), dlg_prop(), fr_window_file_list_drag_data_get(), fr_window_get_selection(), fr_window_rename_selection(), and get_alternative_uri_for_uri().
remove_local_directory()
gboolean remove_local_directory (const char * path)
Definition at line 721 of file file-utils.c.
References NULL, remove_directory(), and TRUE.
Referenced by fr_archive_add().
uri_exists()
gboolean uri_exists (const char * uri)
Definition at line 50 of file file-utils.c.
References FALSE, and NULL.
Referenced by get_alternative_uri(), and open_file_new().
uri_is_dir()
gboolean uri_is_dir (const char * uri)
Definition at line 103 of file file-utils.c.
Referenced by fr_window_archive_extract(), g_list_items_async(), and path_is_dir().
uri_is_file()
gboolean uri_is_file (const char * uri)
Definition at line 97 of file file-utils.c.
Referenced by dlg_batch_add_files(), and fr_window_set_batch__add().
uri_is_local()
gboolean uri_is_local (const char * uri)
Definition at line 122 of file file-utils.c.
Referenced by fr_archive_add_files(), and fr_archive_extract().
uricmp()
int uricmp (const char * uri1, const char * uri2)
Definition at line 1041 of file file-utils.c.
Referenced by dlg_update_add_file(), and fr_archive_add_dropped_items().