MATE Desktop Environment: file-utils.h File Reference
file-utils.h File Reference
#include <sys/types.h>
#include <time.h>
#include <unistd.h>
#include <gio/gio.h>
Macros
#define MIME_TYPE_DIRECTORY "folder"
#define MIME_TYPE_ARCHIVE "application/x-archive"
#define get_home_relative_path(x)
Functions
gboolean uri_exists (const char *uri)
gboolean uri_is_file (const char *uri)
gboolean uri_is_dir (const char *uri)
gboolean path_is_dir (const char *path)
gboolean uri_is_local (const char *uri)
char * get_dir_content_if_unique (const char *uri)
gboolean path_in_path (const char *path_src, const char *path_dest)
goffset get_file_size (const char *uri)
goffset get_file_size_for_path (const char *path)
time_t get_file_mtime (const char *uri)
time_t get_file_mtime_for_path (const char *path)
gboolean make_directory_tree (GFile *dir, mode_t mode, GError **error)
gboolean ensure_dir_exists (const char *uri, mode_t mode, GError **error)
gboolean make_directory_tree_from_path (const char *path, mode_t mode, GError **error)
const char * file_name_from_path (const char *path)
char * dir_name_from_path (const char *path)
char * remove_level_from_path (const char *path)
char * remove_ending_separator (const char *path)
char * build_uri (const char *base,...)
char * remove_extension_from_path (const char *path)
const char * get_file_extension (const char *filename)
gboolean file_extension_is (const char *filename, const char *ext)
gboolean is_mime_type (const char *type, const char *pattern)
const char * get_file_mime_type (const char *uri, gboolean fast_file_type)
const char * get_file_mime_type_for_path (const char *filename, gboolean fast_file_type)
guint64 get_dest_free_space (const char *path)
gboolean remove_directory (const char *uri)
gboolean remove_local_directory (const char *directory)
char * get_temp_work_dir (const char *parent_folder)
gboolean is_temp_work_dir (const char *dir)
gboolean is_temp_dir (const char *dir)
gboolean file_list__match_pattern (const char *line, const char *pattern)
int file_list__get_index_from_pattern (const char *line, const char *pattern)
char * file_list__get_prev_field (const char *line, int start_from, int field_n)
gboolean check_permissions (const char *path, int mode)
gboolean check_file_permissions (GFile *file, int mode)
gboolean is_program_in_path (const char *filename)
gboolean is_program_available (const char *filename, gboolean check)
const char * get_home_uri (void)
GFile * get_user_config_subdirectory (const char *child_name, gboolean create_)
int uricmp (const char *uri1, const char *uri2)
char * get_alternative_uri (const char *folder, const char *name)
char * get_alternative_uri_for_uri (const char *uri)
void path_list_free (GList *path_list)
GList * path_list_dup (GList *path_list)
GList * gio_file_list_dup (GList *l)
void gio_file_list_free (GList *l)
void g_key_file_save (GKeyFile *key_file, GFile *file)
Macro Definition Documentation
get_home_relative_path
#define get_home_relative_path (x)
Value:
    g_strconcat (g_get_home_dir (), \
             "/",               \
             (x),               \
             NULL)
Definition at line 34 of file file-utils.h.
MIME_TYPE_ARCHIVE
#define MIME_TYPE_ARCHIVE "application/x-archive"
Definition at line 32 of file file-utils.h.
MIME_TYPE_DIRECTORY
#define MIME_TYPE_DIRECTORY "folder"
Definition at line 31 of file file-utils.h.
Function Documentation
build_uri()
char * build_uri (const char * base, ...)
Definition at line 397 of file file-utils.c.
References FALSE, and NULL.
Referenced by fr_window_paste_selection(), and get_dir_content_if_unique().
check_file_permissions()
gboolean check_file_permissions (GFile * file, int mode)
Definition at line 932 of file file-utils.c.
References FALSE, NULL, and TRUE.
Referenced by check_permissions().
check_permissions()
gboolean check_permissions (const char * path, int mode)
Definition at line 917 of file file-utils.c.
References check_file_permissions().
Referenced by dlg_batch_add_files(), and fr_window_file_list_drag_data_get().
dir_name_from_path()
char * dir_name_from_path (const char * path)
ensure_dir_exists()
gboolean ensure_dir_exists (const char * uri, mode_t mode, GError ** error)
Definition at line 468 of file file-utils.c.
References error, FALSE, make_directory_tree(), NULL, and TRUE.
Referenced by eom_util_dot_dir(), fr_window_archive_extract(), gsm_util_get_empty_tmp_session_dir(), gsm_util_get_saved_session_dir(), and make_directory_tree_from_path().
file_extension_is()
gboolean file_extension_is (const char * filename, const char * ext)
Definition at line 545 of file file-utils.c.
References FALSE.
file_list__get_index_from_pattern()
int file_list__get_index_from_pattern (const char * line, const char * pattern)
Definition at line 870 of file file-utils.c.
References file_list__match_pattern().
file_list__get_prev_field()
char * file_list__get_prev_field (const char * line, int start_from, int field_n)
Definition at line 890 of file file-utils.c.
file_list__match_pattern()
gboolean file_list__match_pattern (const char * line, const char * pattern)
Definition at line 837 of file file-utils.c.
References FALSE.
Referenced by file_list__get_index_from_pattern().
file_name_from_path()
const char * file_name_from_path (const char * path)
g_key_file_save()
void g_key_file_save (GKeyFile * key_file, GFile * file)
Definition at line 1104 of file file-utils.c.
References error, FALSE, and NULL.
get_alternative_uri()
char * get_alternative_uri (const char * folder_uri, const char * escaped_name)
get_alternative_uri: @folder_uri: The URI of the containing folder @escaped_name: The URI-escaped name of the member to find a name for
Tries to find an unused name for @escaped_name in @folder_uri.
Returns: The full URI for the free slot (including directory)
Definition at line 1054 of file file-utils.c.
References NULL, and uri_exists().
Referenced by get_alternative_uri_for_uri().
get_alternative_uri_for_uri()
char * get_alternative_uri_for_uri (const char * uri)
Definition at line 1073 of file file-utils.c.
References file_name_from_path(), get_alternative_uri(), and remove_level_from_path().
get_dest_free_space()
guint64 get_dest_free_space (const char * path)
Definition at line 629 of file file-utils.c.
References NULL.
Referenced by get_temp_work_dir().
get_dir_content_if_unique()
char * get_dir_content_if_unique (const char * uri)
Definition at line 128 of file file-utils.c.
References build_uri(), name, NULL, and TRUE.
get_file_extension()
const char * get_file_extension (const char * filename)
Definition at line 508 of file file-utils.c.
References NULL, and test.
Referenced by get_archive_filename_extension().
get_file_mime_type()
const char * get_file_mime_type (const char * uri, gboolean fast_file_type)
Definition at line 566 of file file-utils.c.
References get_static_string(), and NULL.
Referenced by get_file_mime_type_for_path().
get_file_mime_type_for_path()
const char * get_file_mime_type_for_path (const char * filename, gboolean fast_file_type)
Definition at line 595 of file file-utils.c.
References get_file_mime_type(), mime_type, and NULL.
get_file_mtime()
time_t get_file_mtime (const char * uri)
Definition at line 292 of file file-utils.c.
Referenced by dlg_prop(), get_file_mtime_for_path(), and open_file_new().
get_file_mtime_for_path()
time_t get_file_mtime_for_path (const char * path)
Definition at line 298 of file file-utils.c.
References get_file_mtime(), and NULL.
Referenced by fr_archive_extract_to_local().
get_file_size()
goffset get_file_size (const char * uri)
Definition at line 223 of file file-utils.c.
References NULL.
Referenced by dlg_prop(), and get_file_size_for_path().
get_file_size_for_path()
goffset get_file_size_for_path (const char * path)
Definition at line 250 of file file-utils.c.
References get_file_size(), and NULL.
get_home_uri()
const char * get_home_uri (void)
Definition at line 1007 of file file-utils.c.
References NULL.
Referenced by dlg_batch_add_files(), fr_window_get_add_default_dir(), fr_window_get_extract_default_dir(), and fr_window_get_open_default_dir().
get_temp_work_dir()
char * get_temp_work_dir (const char * parent_folder)
Definition at line 754 of file file-utils.c.
References get_dest_free_space(), and NULL.
Referenced by fr_archive_add(), fr_archive_extract(), fr_archive_extract_to_local(), fr_archive_remove(), and fr_window_archive_save_as().
get_user_config_subdirectory()
GFile * get_user_config_subdirectory (const char * child_name, gboolean create_)
Definition at line 1016 of file file-utils.c.
References error, make_directory_tree(), and NULL.
gio_file_list_dup()
GList * gio_file_list_dup (GList * l)
Definition at line 1086 of file file-utils.c.
References NULL.
gio_file_list_free()
void gio_file_list_free (GList * l)
Definition at line 1095 of file file-utils.c.
is_mime_type()
gboolean is_mime_type (const char * type, const char * pattern)
Definition at line 559 of file file-utils.c.
References mime_type.
Referenced by caja_file_info_is_mime_type(), and get_mime_type_index().
is_program_available()
gboolean is_program_available (const char * filename, gboolean check)
Definition at line 1000 of file file-utils.c.
References is_program_in_path().
is_program_in_path()
gboolean is_program_in_path (const char * filename)
Definition at line 974 of file file-utils.c.
References FALSE, NULL, ProgramsCache, and TRUE.
Referenced by is_program_available().
is_temp_dir()
gboolean is_temp_dir (const char * dir)
Definition at line 822 of file file-utils.c.
References is_temp_work_dir(), path_in_path(), and TRUE.
is_temp_work_dir()
gboolean is_temp_work_dir (const char * dir)
Definition at line 798 of file file-utils.c.
References FALSE, NULL, and TRUE.
Referenced by is_temp_dir().
make_directory_tree()
gboolean make_directory_tree (GFile * dir, mode_t mode, GError ** error)
Definition at line 432 of file file-utils.c.
References error, FALSE, make_directory_tree(), NULL, and TRUE.
Referenced by ensure_dir_exists(), get_user_config_subdirectory(), and make_directory_tree().
make_directory_tree_from_path()
gboolean make_directory_tree_from_path (const char * path, mode_t mode, GError ** error)
Definition at line 493 of file file-utils.c.
References ensure_dir_exists(), error, and NULL.
path_in_path()
gboolean path_in_path (const char * path_src, const char * path_dest)
Definition at line 193 of file file-utils.c.
References FALSE, and NULL.
Referenced by is_temp_dir().
path_is_dir()
gboolean path_is_dir (const char * path)
Definition at line 109 of file file-utils.c.
References NULL, and uri_is_dir().
path_list_dup()
GList * path_list_dup (GList * path_list)
Definition at line 617 of file file-utils.c.
References NULL.
Referenced by fr_archive_add().
path_list_free()
void path_list_free (GList * path_list)
Definition at line 609 of file file-utils.c.
References NULL.
Referenced by activate_popup_open(), fr_archive_add(), fr_archive_extract_to_local(), fr_window_archive_add_files(), fr_window_file_list_drag_data_get(), fr_window_get_folder_tree_selection(), fr_window_open_files_with_application(), and open_with_cb().
remove_directory()
gboolean remove_directory (const char * uri)
Definition at line 702 of file file-utils.c.
References error, and NULL.
Referenced by remove_local_directory().
remove_ending_separator()
char * remove_ending_separator (const char * path)
Definition at line 382 of file file-utils.c.
References NULL.
Referenced by fr_window_rename_selection().
remove_extension_from_path()
char * remove_extension_from_path (const char * path)
remove_level_from_path()
char * remove_level_from_path (const char * path)
remove_local_directory()
gboolean remove_local_directory (const char * directory)
Definition at line 720 of file file-utils.c.
References NULL, remove_directory(), and TRUE.
Referenced by fr_archive_add().
uri_exists()
gboolean uri_exists (const char * uri)
Definition at line 50 of file file-utils.c.
References FALSE, and NULL.
Referenced by get_alternative_uri(), and open_file_new().
uri_is_dir()
gboolean uri_is_dir (const char * uri)
Definition at line 103 of file file-utils.c.
Referenced by fr_window_archive_extract(), g_list_items_async(), and path_is_dir().
uri_is_file()
gboolean uri_is_file (const char * uri)
Definition at line 97 of file file-utils.c.
Referenced by dlg_batch_add_files(), and fr_window_set_batch__add().
uri_is_local()
gboolean uri_is_local (const char * uri)
Definition at line 122 of file file-utils.c.
Referenced by fr_archive_add_files(), and fr_archive_extract().
uricmp()
int uricmp (const char * uri1, const char * uri2)
Definition at line 1038 of file file-utils.c.
Referenced by dlg_update_add_file(), and fr_archive_add_dropped_items().