MATE Desktop Environment: financial.c File Reference
financial.c File Reference
#include <glib/gi18n.h>
#include "financial.h"
#include "mp.h"
Functions
void do_finc_expression (MathEquation *equation, int function, MPNumber *arg1, MPNumber *arg2, MPNumber *arg3, MPNumber *arg4)
Function Documentation
do_finc_expression()
void do_finc_expression (MathEquation * equation, int function, MPNumber * arg1, MPNumber * arg2, MPNumber * arg3, MPNumber * arg4)
Definition at line 306 of file financial.c.
References FINC_CTRM_DIALOG, FINC_DDB_DIALOG, FINC_FV_DIALOG, FINC_GPM_DIALOG, FINC_PMT_DIALOG, FINC_PV_DIALOG, FINC_RATE_DIALOG, FINC_SLN_DIALOG, FINC_SYD_DIALOG, FINC_TERM_DIALOG, math_equation_set_number(), mp_clear(), and mp_new().
Referenced by finc_response_cb().