MATE Desktop Environment: fm-ditem-page.c File Reference
fm-ditem-page.c File Reference
#include <config.h>
#include <string.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <eel/eel-glib-extensions.h>
#include <libcaja-extension/caja-extension-types.h>
#include <libcaja-extension/caja-file-info.h>
#include <libcaja-private/caja-file.h>
#include <libcaja-private/caja-file-attributes.h>
#include "fm-ditem-page.h"
Macros
#define MAIN_GROUP "Desktop Entry"
Typedefs
typedef struct ItemEntry ItemEntry
Enumerations
enum { TARGET_URI_LIST }
Functions
GtkWidget * fm_ditem_page_make_box (GtkSizeGroup *label_size_group, GList *files)
gboolean fm_ditem_page_should_show (GList *files)
Macro Definition Documentation
MAIN_GROUP
#define MAIN_GROUP "Desktop Entry"
Definition at line 39 of file fm-ditem-page.c.
Typedef Documentation
ItemEntry
typedef struct ItemEntry ItemEntry
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TARGET_URI_LIST
Definition at line 50 of file fm-ditem-page.c.
Function Documentation
fm_ditem_page_make_box()
GtkWidget * fm_ditem_page_make_box (GtkSizeGroup * label_size_group, GList * files)
Definition at line 522 of file fm-ditem-page.c.
References CAJA_FILE_INFO, caja_file_info_get_uri(), and fm_ditem_page_should_show().
fm_ditem_page_should_show()
gboolean fm_ditem_page_should_show (GList * files)
Definition at line 545 of file fm-ditem-page.c.
References CAJA_FILE_INFO, caja_file_info_is_mime_type(), FALSE, and TRUE.
Referenced by fm_ditem_page_make_box().