MATE Desktop Environment: fm-icon-view.h File Reference
fm-icon-view.h File Reference
#include "fm-directory-view.h"
Classes
struct FMIconView
struct FMIconViewClass
Macros
#define FM_TYPE_ICON_VIEW fm_icon_view_get_type()
#define FM_ICON_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FM_TYPE_ICON_VIEW, FMIconView))
#define FM_ICON_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FM_TYPE_ICON_VIEW, FMIconViewClass))
#define FM_IS_ICON_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FM_TYPE_ICON_VIEW))
#define FM_IS_ICON_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FM_TYPE_ICON_VIEW))
#define FM_ICON_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FM_TYPE_ICON_VIEW, FMIconViewClass))
#define FM_ICON_VIEW_ID "OAFIID:Caja_File_Manager_Icon_View"
#define FM_COMPACT_VIEW_ID "OAFIID:Caja_File_Manager_Compact_View"
Typedefs
typedef struct FMIconView FMIconView
typedef struct FMIconViewClass FMIconViewClass
typedef struct FMIconViewDetails FMIconViewDetails
Functions
GType fm_icon_view_get_type (void)
int fm_icon_view_compare_files (FMIconView *icon_view, CajaFile *a, CajaFile *b)
void fm_icon_view_filter_by_screen (FMIconView *icon_view, gboolean filter)
gboolean fm_icon_view_is_compact (FMIconView *icon_view)
void fm_icon_view_register (void)
void fm_compact_view_register (void)
Macro Definition Documentation
FM_COMPACT_VIEW_ID
#define FM_COMPACT_VIEW_ID "OAFIID:Caja_File_Manager_Compact_View"
Definition at line 46 of file fm-icon-view.h.
FM_ICON_VIEW
#define FM_ICON_VIEW (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FM_TYPE_ICON_VIEW, FMIconView))
Definition at line 34 of file fm-icon-view.h.
FM_ICON_VIEW_CLASS
#define FM_ICON_VIEW_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FM_TYPE_ICON_VIEW, FMIconViewClass))
Definition at line 36 of file fm-icon-view.h.
FM_ICON_VIEW_GET_CLASS
#define FM_ICON_VIEW_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FM_TYPE_ICON_VIEW, FMIconViewClass))
Definition at line 42 of file fm-icon-view.h.
FM_ICON_VIEW_ID
#define FM_ICON_VIEW_ID "OAFIID:Caja_File_Manager_Icon_View"
Definition at line 45 of file fm-icon-view.h.
FM_IS_ICON_VIEW
#define FM_IS_ICON_VIEW (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FM_TYPE_ICON_VIEW))
Definition at line 38 of file fm-icon-view.h.
FM_IS_ICON_VIEW_CLASS
#define FM_IS_ICON_VIEW_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FM_TYPE_ICON_VIEW))
Definition at line 40 of file fm-icon-view.h.
FM_TYPE_ICON_VIEW
#define FM_TYPE_ICON_VIEW fm_icon_view_get_type()
Definition at line 33 of file fm-icon-view.h.
Typedef Documentation
FMIconView
typedef struct FMIconView FMIconView
Definition at line 30 of file fm-icon-view.h.
FMIconViewClass
typedef struct FMIconViewClass FMIconViewClass
Definition at line 31 of file fm-icon-view.h.
FMIconViewDetails
typedef struct FMIconViewDetails FMIconViewDetails
Definition at line 48 of file fm-icon-view.h.
Function Documentation
fm_compact_view_register()
void fm_compact_view_register (void)
Definition at line 3646 of file fm-icon-view.c.
References caja_view_factory_register(), and TRANSLATE_VIEW_INFO.
fm_icon_view_compare_files()
int fm_icon_view_compare_files (FMIconView * icon_view, CajaFile * a, CajaFile * b)
Definition at line 2556 of file fm-icon-view.c.
References b, caja_file_compare_for_sort(), FMIconView::details, and fm_directory_view_should_sort_directories_first().
fm_icon_view_filter_by_screen()
void fm_icon_view_filter_by_screen (FMIconView * icon_view, gboolean filter)
Definition at line 2576 of file fm-icon-view.c.
References FMIconView::details.
fm_icon_view_get_type()
GType fm_icon_view_get_type (void)
fm_icon_view_is_compact()
gboolean fm_icon_view_is_compact (FMIconView * icon_view)
Definition at line 3633 of file fm-icon-view.c.
References FMIconView::details.
fm_icon_view_register()
void fm_icon_view_register (void)
Definition at line 3639 of file fm-icon-view.c.
References caja_view_factory_register(), and TRANSLATE_VIEW_INFO.