MATE Desktop Environment: fm-list-model.h File Reference
fm-list-model.h File Reference
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <libcaja-private/caja-file.h>
#include <libcaja-private/caja-directory.h>
#include <libcaja-extension/caja-column.h>
Classes
struct FMListModel
struct FMListModelClass
Macros
#define FM_TYPE_LIST_MODEL fm_list_model_get_type()
#define FM_LIST_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FM_TYPE_LIST_MODEL, FMListModel))
#define FM_LIST_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FM_TYPE_LIST_MODEL, FMListModelClass))
#define FM_IS_LIST_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FM_TYPE_LIST_MODEL))
#define FM_IS_LIST_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FM_TYPE_LIST_MODEL))
#define FM_LIST_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FM_TYPE_LIST_MODEL, FMListModelClass))
Typedefs
typedef struct FMListModelDetails FMListModelDetails
typedef struct FMListModel FMListModel
Enumerations
enum {
FM_LIST_MODEL_FILE_COLUMN , FM_LIST_MODEL_SUBDIRECTORY_COLUMN , FM_LIST_MODEL_SMALLEST_ICON_COLUMN , FM_LIST_MODEL_SMALLER_ICON_COLUMN ,
FM_LIST_MODEL_SMALL_ICON_COLUMN , FM_LIST_MODEL_STANDARD_ICON_COLUMN , FM_LIST_MODEL_LARGE_ICON_COLUMN , FM_LIST_MODEL_LARGER_ICON_COLUMN ,
FM_LIST_MODEL_LARGEST_ICON_COLUMN , FM_LIST_MODEL_FILE_NAME_IS_EDITABLE_COLUMN , FM_LIST_MODEL_NUM_COLUMNS
}
Functions
GType fm_list_model_get_type (void)
gboolean fm_list_model_add_file (FMListModel *model, CajaFile *file, CajaDirectory *directory)
void fm_list_model_file_changed (FMListModel *model, CajaFile *file, CajaDirectory *directory)
gboolean fm_list_model_is_empty (FMListModel *model)
guint fm_list_model_get_length (FMListModel *model)
void fm_list_model_remove_file (FMListModel *model, CajaFile *file, CajaDirectory *directory)
void fm_list_model_clear (FMListModel *model)
gboolean fm_list_model_get_tree_iter_from_file (FMListModel *model, CajaFile *file, CajaDirectory *directory, GtkTreeIter *iter)
GList * fm_list_model_get_all_iters_for_file (FMListModel *model, CajaFile *file)
gboolean fm_list_model_get_first_iter_for_file (FMListModel *model, CajaFile *file, GtkTreeIter *iter)
void fm_list_model_set_should_sort_directories_first (FMListModel *model, gboolean sort_directories_first)
int fm_list_model_get_sort_column_id_from_attribute (FMListModel *model, GQuark attribute)
GQuark fm_list_model_get_attribute_from_sort_column_id (FMListModel *model, int sort_column_id)
void fm_list_model_sort_files (FMListModel *model, GList **files)
CajaZoomLevel fm_list_model_get_zoom_level_from_column_id (int column)
int fm_list_model_get_column_id_from_zoom_level (CajaZoomLevel zoom_level)
CajaFile * fm_list_model_file_for_path (FMListModel *model, GtkTreePath *path)
gboolean fm_list_model_load_subdirectory (FMListModel *model, GtkTreePath *path, CajaDirectory **directory)
void fm_list_model_unload_subdirectory (FMListModel *model, GtkTreeIter *iter)
void fm_list_model_set_drag_view (FMListModel *model, GtkTreeView *view, int begin_x, int begin_y)
GtkTargetList * fm_list_model_get_drag_target_list (void)
int fm_list_model_compare_func (FMListModel *model, CajaFile *file1, CajaFile *file2)
int fm_list_model_add_column (FMListModel *model, CajaColumn *column)
void fm_list_model_subdirectory_done_loading (FMListModel *model, CajaDirectory *directory)
void fm_list_model_set_highlight_for_files (FMListModel *model, GList *files)
Macro Definition Documentation
FM_IS_LIST_MODEL
#define FM_IS_LIST_MODEL (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FM_TYPE_LIST_MODEL))
Definition at line 41 of file fm-list-model.h.
FM_IS_LIST_MODEL_CLASS
#define FM_IS_LIST_MODEL_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FM_TYPE_LIST_MODEL))
Definition at line 43 of file fm-list-model.h.
FM_LIST_MODEL
#define FM_LIST_MODEL (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FM_TYPE_LIST_MODEL, FMListModel))
Definition at line 37 of file fm-list-model.h.
FM_LIST_MODEL_CLASS
#define FM_LIST_MODEL_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FM_TYPE_LIST_MODEL, FMListModelClass))
Definition at line 39 of file fm-list-model.h.
FM_LIST_MODEL_GET_CLASS
#define FM_LIST_MODEL_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FM_TYPE_LIST_MODEL, FMListModelClass))
Definition at line 45 of file fm-list-model.h.
FM_TYPE_LIST_MODEL
#define FM_TYPE_LIST_MODEL fm_list_model_get_type()
Definition at line 36 of file fm-list-model.h.
Typedef Documentation
FMListModel
typedef struct FMListModel FMListModel
FMListModelDetails
typedef struct FMListModelDetails FMListModelDetails
Definition at line 63 of file fm-list-model.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FM_LIST_MODEL_FILE_COLUMN
FM_LIST_MODEL_SUBDIRECTORY_COLUMN
FM_LIST_MODEL_SMALLEST_ICON_COLUMN
FM_LIST_MODEL_SMALLER_ICON_COLUMN
FM_LIST_MODEL_SMALL_ICON_COLUMN
FM_LIST_MODEL_STANDARD_ICON_COLUMN
FM_LIST_MODEL_LARGE_ICON_COLUMN
FM_LIST_MODEL_LARGER_ICON_COLUMN
FM_LIST_MODEL_LARGEST_ICON_COLUMN
FM_LIST_MODEL_FILE_NAME_IS_EDITABLE_COLUMN
FM_LIST_MODEL_NUM_COLUMNS
Definition at line 48 of file fm-list-model.h.
Function Documentation
fm_list_model_add_column()
int fm_list_model_add_column (FMListModel * model, CajaColumn * column)
Definition at line 1638 of file fm-list-model.c.
References FMListModel::details, and FM_LIST_MODEL_NUM_COLUMNS.
fm_list_model_add_file()
gboolean fm_list_model_add_file (FMListModel * model, CajaFile * file, CajaDirectory * directory)
Definition at line 1055 of file fm-list-model.c.
References caja_file_is_directory(), caja_file_ref(), FMListModel::details, FALSE, NULL, and TRUE.
fm_list_model_clear()
void fm_list_model_clear (FMListModel * model)
Definition at line 1372 of file fm-list-model.c.
References FMListModel::details, and NULL.
fm_list_model_compare_func()
int fm_list_model_compare_func (FMListModel * model, CajaFile * file1, CajaFile * file2)
Definition at line 788 of file fm-list-model.c.
References caja_file_compare_for_sort_by_attribute_q(), and FMListModel::details.
fm_list_model_file_changed()
void fm_list_model_file_changed (FMListModel * model, CajaFile * file, CajaDirectory * directory)
Definition at line 1154 of file fm-list-model.c.
References FMListModel::details, FALSE, NULL, and TRUE.
fm_list_model_file_for_path()
CajaFile * fm_list_model_file_for_path (FMListModel * model, GtkTreePath * path)
Definition at line 1380 of file fm-list-model.c.
References FM_LIST_MODEL_FILE_COLUMN, and NULL.
fm_list_model_get_all_iters_for_file()
GList * fm_list_model_get_all_iters_for_file (FMListModel * model, CajaFile * file)
Definition at line 699 of file fm-list-model.c.
References data, FMListModel::details, and NULL.
Referenced by fm_list_model_get_first_iter_for_file().
fm_list_model_get_attribute_from_sort_column_id()
GQuark fm_list_model_get_attribute_from_sort_column_id (FMListModel * model, int sort_column_id)
Definition at line 1542 of file fm-list-model.c.
References CAJA_COLUMN, FMListModel::details, FM_LIST_MODEL_NUM_COLUMNS, and NULL.
fm_list_model_get_column_id_from_zoom_level()
int fm_list_model_get_column_id_from_zoom_level (CajaZoomLevel zoom_level)
Definition at line 1588 of file fm-list-model.c.
References CAJA_ZOOM_LEVEL_LARGE, CAJA_ZOOM_LEVEL_LARGER, CAJA_ZOOM_LEVEL_LARGEST, CAJA_ZOOM_LEVEL_SMALL, CAJA_ZOOM_LEVEL_SMALLER, CAJA_ZOOM_LEVEL_SMALLEST, CAJA_ZOOM_LEVEL_STANDARD, FM_LIST_MODEL_LARGE_ICON_COLUMN, FM_LIST_MODEL_LARGER_ICON_COLUMN, FM_LIST_MODEL_LARGEST_ICON_COLUMN, FM_LIST_MODEL_SMALL_ICON_COLUMN, FM_LIST_MODEL_SMALLER_ICON_COLUMN, FM_LIST_MODEL_SMALLEST_ICON_COLUMN, and FM_LIST_MODEL_STANDARD_ICON_COLUMN.
fm_list_model_get_drag_target_list()
GtkTargetList * fm_list_model_get_drag_target_list (void)
Definition at line 1627 of file fm-list-model.c.
References CAJA_ICON_DND_TEXT.
fm_list_model_get_first_iter_for_file()
gboolean fm_list_model_get_first_iter_for_file (FMListModel * model, CajaFile * file, GtkTreeIter * iter)
Definition at line 715 of file fm-list-model.c.
References FALSE, fm_list_model_get_all_iters_for_file(), NULL, and TRUE.
fm_list_model_get_length()
guint fm_list_model_get_length (FMListModel * model)
Definition at line 1238 of file fm-list-model.c.
References FMListModel::details.
fm_list_model_get_sort_column_id_from_attribute()
int fm_list_model_get_sort_column_id_from_attribute (FMListModel * model, GQuark attribute)
Definition at line 1504 of file fm-list-model.c.
References CAJA_COLUMN, FMListModel::details, FM_LIST_MODEL_NUM_COLUMNS, and NULL.
fm_list_model_get_tree_iter_from_file()
gboolean fm_list_model_get_tree_iter_from_file (FMListModel * model, CajaFile * file, CajaDirectory * directory, GtkTreeIter * iter)
Definition at line 736 of file fm-list-model.c.
References FALSE, and TRUE.
Referenced by fm_list_model_remove_file().
fm_list_model_get_type()
GType fm_list_model_get_type (void)
fm_list_model_get_zoom_level_from_column_id()
CajaZoomLevel fm_list_model_get_zoom_level_from_column_id (int column)
Definition at line 1564 of file fm-list-model.c.
References CAJA_ZOOM_LEVEL_LARGE, CAJA_ZOOM_LEVEL_LARGER, CAJA_ZOOM_LEVEL_LARGEST, CAJA_ZOOM_LEVEL_SMALL, CAJA_ZOOM_LEVEL_SMALLER, CAJA_ZOOM_LEVEL_SMALLEST, CAJA_ZOOM_LEVEL_STANDARD, FM_LIST_MODEL_LARGE_ICON_COLUMN, FM_LIST_MODEL_LARGER_ICON_COLUMN, FM_LIST_MODEL_LARGEST_ICON_COLUMN, FM_LIST_MODEL_SMALL_ICON_COLUMN, FM_LIST_MODEL_SMALLER_ICON_COLUMN, FM_LIST_MODEL_SMALLEST_ICON_COLUMN, and FM_LIST_MODEL_STANDARD_ICON_COLUMN.
fm_list_model_is_empty()
gboolean fm_list_model_is_empty (FMListModel * model)
Definition at line 1232 of file fm-list-model.c.
References FMListModel::details.
fm_list_model_load_subdirectory()
gboolean fm_list_model_load_subdirectory (FMListModel * model, GtkTreePath * path, CajaDirectory ** directory)
Definition at line 1398 of file fm-list-model.c.
References caja_directory_get_for_file(), caja_directory_ref(), caja_directory_unref(), FMListModel::details, FALSE, NULL, and TRUE.
fm_list_model_remove_file()
void fm_list_model_remove_file (FMListModel * model, CajaFile * file, CajaDirectory * directory)
Definition at line 1338 of file fm-list-model.c.
References fm_list_model_get_tree_iter_from_file().
fm_list_model_set_drag_view()
void fm_list_model_set_drag_view (FMListModel * model, GtkTreeView * view, int begin_x, int begin_y)
Definition at line 1612 of file fm-list-model.c.
References FMListModel::details, FM_IS_LIST_MODEL, and NULL.
fm_list_model_set_highlight_for_files()
void fm_list_model_set_highlight_for_files (FMListModel * model, GList * files)
Definition at line 1855 of file fm-list-model.c.
References caja_file_list_copy(), caja_file_list_free(), FMListModel::details, and NULL.
fm_list_model_set_should_sort_directories_first()
void fm_list_model_set_should_sort_directories_first (FMListModel * model, gboolean sort_directories_first)
Definition at line 1492 of file fm-list-model.c.
References FMListModel::details.
fm_list_model_sort_files()
void fm_list_model_sort_files (FMListModel * model, GList ** files)
fm_list_model_subdirectory_done_loading()
void fm_list_model_subdirectory_done_loading (FMListModel * model, CajaDirectory * directory)
Definition at line 1782 of file fm-list-model.c.
References caja_directory_is_not_empty(), FMListModel::details, and NULL.
fm_list_model_unload_subdirectory()
void fm_list_model_unload_subdirectory (FMListModel * model, GtkTreeIter * iter)
Definition at line 1440 of file fm-list-model.c.
References caja_directory_unref(), FMListModel::details, NULL, and SUBDIRECTORY_UNLOADED.