MATE Desktop Environment: fm-tree-model.h File Reference
fm-tree-model.h File Reference
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <libcaja-private/caja-file.h>
Classes
struct FMTreeModel
struct FMTreeModelClass
Macros
#define FM_TYPE_TREE_MODEL fm_tree_model_get_type()
#define FM_TREE_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FM_TYPE_TREE_MODEL, FMTreeModel))
#define FM_TREE_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FM_TYPE_TREE_MODEL, FMTreeModelClass))
#define FM_IS_TREE_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FM_TYPE_TREE_MODEL))
#define FM_IS_TREE_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FM_TYPE_TREE_MODEL))
#define FM_TREE_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FM_TYPE_TREE_MODEL, FMTreeModelClass))
Typedefs
typedef struct FMTreeModelDetails FMTreeModelDetails
Enumerations
enum {
FM_TREE_MODEL_DISPLAY_NAME_COLUMN , FM_TREE_MODEL_CLOSED_SURFACE_COLUMN , FM_TREE_MODEL_OPEN_SURFACE_COLUMN , FM_TREE_MODEL_FONT_STYLE_COLUMN ,
FM_TREE_MODEL_NUM_COLUMNS
}
Functions
GType fm_tree_model_get_type (void)
FMTreeModel * fm_tree_model_new (void)
void fm_tree_model_set_show_hidden_files (FMTreeModel *model, gboolean show_hidden_files)
void fm_tree_model_set_show_only_directories (FMTreeModel *model, gboolean show_only_directories)
CajaFile * fm_tree_model_iter_get_file (FMTreeModel *model, GtkTreeIter *iter)
void fm_tree_model_add_root_uri (FMTreeModel *model, const char *root_uri, const char *display_name, GIcon *icon, GMount *mount)
void fm_tree_model_remove_root_uri (FMTreeModel *model, const char *root_uri)
gboolean fm_tree_model_iter_is_root (FMTreeModel *model, GtkTreeIter *iter)
int fm_tree_model_iter_compare_roots (FMTreeModel *model, GtkTreeIter *iter_a, GtkTreeIter *iter_b)
gboolean fm_tree_model_file_get_iter (FMTreeModel *model, GtkTreeIter *iter, CajaFile *file, GtkTreeIter *currentIter)
GMount * fm_tree_model_get_mount_for_root_node_file (FMTreeModel *model, CajaFile *file)
void fm_tree_model_set_highlight_for_files (FMTreeModel *model, GList *files)
Macro Definition Documentation
FM_IS_TREE_MODEL
#define FM_IS_TREE_MODEL (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FM_TYPE_TREE_MODEL))
Definition at line 42 of file fm-tree-model.h.
FM_IS_TREE_MODEL_CLASS
#define FM_IS_TREE_MODEL_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FM_TYPE_TREE_MODEL))
Definition at line 44 of file fm-tree-model.h.
FM_TREE_MODEL
#define FM_TREE_MODEL (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FM_TYPE_TREE_MODEL, FMTreeModel))
Definition at line 38 of file fm-tree-model.h.
FM_TREE_MODEL_CLASS
#define FM_TREE_MODEL_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FM_TYPE_TREE_MODEL, FMTreeModelClass))
Definition at line 40 of file fm-tree-model.h.
FM_TREE_MODEL_GET_CLASS
#define FM_TREE_MODEL_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FM_TYPE_TREE_MODEL, FMTreeModelClass))
Definition at line 46 of file fm-tree-model.h.
FM_TYPE_TREE_MODEL
#define FM_TYPE_TREE_MODEL fm_tree_model_get_type()
Definition at line 37 of file fm-tree-model.h.
Typedef Documentation
FMTreeModelDetails
typedef struct FMTreeModelDetails FMTreeModelDetails
Definition at line 58 of file fm-tree-model.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FM_TREE_MODEL_DISPLAY_NAME_COLUMN
FM_TREE_MODEL_CLOSED_SURFACE_COLUMN
FM_TREE_MODEL_OPEN_SURFACE_COLUMN
FM_TREE_MODEL_FONT_STYLE_COLUMN
FM_TREE_MODEL_NUM_COLUMNS
Definition at line 49 of file fm-tree-model.h.
Function Documentation
fm_tree_model_add_root_uri()
void fm_tree_model_add_root_uri (FMTreeModel * model, const char * root_uri, const char * display_name, GIcon * icon, GMount * mount)
Definition at line 1716 of file fm-tree-model.c.
References caja_file_get_by_uri(), caja_file_unref(), FMTreeModel::details, and NULL.
fm_tree_model_file_get_iter()
gboolean fm_tree_model_file_get_iter (FMTreeModel * model, GtkTreeIter * iter, CajaFile * file, GtkTreeIter * currentIter)
Definition at line 1957 of file fm-tree-model.c.
References FMTreeModel::details, FALSE, and NULL.
fm_tree_model_get_mount_for_root_node_file()
GMount * fm_tree_model_get_mount_for_root_node_file (FMTreeModel * model, CajaFile * file)
Definition at line 1753 of file fm-tree-model.c.
References FMTreeModel::details, and NULL.
fm_tree_model_get_type()
GType fm_tree_model_get_type (void)
fm_tree_model_iter_compare_roots()
int fm_tree_model_iter_compare_roots (FMTreeModel * model, GtkTreeIter * iter_a, GtkTreeIter * iter_b)
Definition at line 1903 of file fm-tree-model.c.
References b, FMTreeModel::details, FM_IS_TREE_MODEL, and NULL.
fm_tree_model_iter_get_file()
CajaFile * fm_tree_model_iter_get_file (FMTreeModel * model, GtkTreeIter * iter)
Definition at line 1889 of file fm-tree-model.c.
References caja_file_ref(), FM_IS_TREE_MODEL, FM_TREE_MODEL, and NULL.
fm_tree_model_iter_is_root()
gboolean fm_tree_model_iter_is_root (FMTreeModel * model, GtkTreeIter * iter)
Definition at line 1939 of file fm-tree-model.c.
References FALSE, FM_IS_TREE_MODEL, and NULL.
fm_tree_model_new()
FMTreeModel * fm_tree_model_new (void)
Definition at line 1831 of file fm-tree-model.c.
References FM_TYPE_TREE_MODEL, and NULL.
fm_tree_model_remove_root_uri()
void fm_tree_model_remove_root_uri (FMTreeModel * model, const char * root_uri)
Definition at line 1774 of file fm-tree-model.c.
References caja_file_get_by_uri(), caja_file_monitor_remove(), caja_file_unref(), FMTreeModel::details, and NULL.
fm_tree_model_set_highlight_for_files()
void fm_tree_model_set_highlight_for_files (FMTreeModel * model, GList * files)
Definition at line 2006 of file fm-tree-model.c.
References caja_file_list_copy(), caja_file_list_free(), FMTreeModel::details, and NULL.
fm_tree_model_set_show_hidden_files()
void fm_tree_model_set_show_hidden_files (FMTreeModel * model, gboolean show_hidden_files)
Definition at line 1841 of file fm-tree-model.c.
References caja_file_is_hidden_file(), FMTreeModel::details, FALSE, FM_IS_TREE_MODEL, and TRUE.
fm_tree_model_set_show_only_directories()
void fm_tree_model_set_show_only_directories (FMTreeModel * model, gboolean show_only_directories)
Definition at line 1868 of file fm-tree-model.c.
References FMTreeModel::details, FALSE, FM_IS_TREE_MODEL, and TRUE.