MATE Desktop Environment: fm-tree-model.c File Reference
fm-tree-model.c File Reference
#include <config.h>
#include <string.h>
#include <cairo-gobject.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <eel/eel-graphic-effects.h>
#include <libcaja-private/caja-directory.h>
#include <libcaja-private/caja-file-attributes.h>
#include <libcaja-private/caja-file.h>
#include "fm-tree-model.h"
Typedefs
typedef gboolean(* FilePredicate) (CajaFile *)
typedef struct TreeNode TreeNode
typedef struct FMTreeModelRoot FMTreeModelRoot
Enumerations
enum { ROW_LOADED , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_CODE (FMTreeModel, fm_tree_model, G_TYPE_OBJECT, G_IMPLEMENT_INTERFACE(GTK_TYPE_TREE_MODEL, fm_tree_model_tree_model_init))
void fm_tree_model_add_root_uri (FMTreeModel *model, const char *root_uri, const char *display_name, GIcon *icon, GMount *mount)
GMount * fm_tree_model_get_mount_for_root_node_file (FMTreeModel *model, CajaFile *file)
void fm_tree_model_remove_root_uri (FMTreeModel *model, const char *uri)
FMTreeModel * fm_tree_model_new (void)
void fm_tree_model_set_show_hidden_files (FMTreeModel *model, gboolean show_hidden_files)
void fm_tree_model_set_show_only_directories (FMTreeModel *model, gboolean show_only_directories)
CajaFile * fm_tree_model_iter_get_file (FMTreeModel *model, GtkTreeIter *iter)
int fm_tree_model_iter_compare_roots (FMTreeModel *model, GtkTreeIter *iter_a, GtkTreeIter *iter_b)
gboolean fm_tree_model_iter_is_root (FMTreeModel *model, GtkTreeIter *iter)
gboolean fm_tree_model_file_get_iter (FMTreeModel *model, GtkTreeIter *iter, CajaFile *file, GtkTreeIter *current_iter)
void fm_tree_model_set_highlight_for_files (FMTreeModel *model, GList *files)
Typedef Documentation
FilePredicate
typedef gboolean(* FilePredicate) (CajaFile *)
Definition at line 52 of file fm-tree-model.c.
FMTreeModelRoot
typedef struct FMTreeModelRoot FMTreeModelRoot
Definition at line 60 of file fm-tree-model.c.
TreeNode
typedef struct TreeNode TreeNode
Definition at line 59 of file fm-tree-model.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ROW_LOADED
LAST_SIGNAL
Definition at line 44 of file fm-tree-model.c.
Function Documentation
fm_tree_model_add_root_uri()
void fm_tree_model_add_root_uri (FMTreeModel * model, const char * root_uri, const char * display_name, GIcon * icon, GMount * mount)
Definition at line 1716 of file fm-tree-model.c.
References caja_file_get_by_uri(), caja_file_unref(), FMTreeModel::details, and NULL.
fm_tree_model_file_get_iter()
gboolean fm_tree_model_file_get_iter (FMTreeModel * model, GtkTreeIter * iter, CajaFile * file, GtkTreeIter * current_iter)
Definition at line 1957 of file fm-tree-model.c.
References FMTreeModel::details, FALSE, and NULL.
fm_tree_model_get_mount_for_root_node_file()
GMount * fm_tree_model_get_mount_for_root_node_file (FMTreeModel * model, CajaFile * file)
Definition at line 1753 of file fm-tree-model.c.
References FMTreeModel::details, and NULL.
fm_tree_model_iter_compare_roots()
int fm_tree_model_iter_compare_roots (FMTreeModel * model, GtkTreeIter * iter_a, GtkTreeIter * iter_b)
Definition at line 1903 of file fm-tree-model.c.
References b, FMTreeModel::details, FM_IS_TREE_MODEL, and NULL.
fm_tree_model_iter_get_file()
CajaFile * fm_tree_model_iter_get_file (FMTreeModel * model, GtkTreeIter * iter)
Definition at line 1889 of file fm-tree-model.c.
References caja_file_ref(), FM_IS_TREE_MODEL, FM_TREE_MODEL, and NULL.
fm_tree_model_iter_is_root()
gboolean fm_tree_model_iter_is_root (FMTreeModel * model, GtkTreeIter * iter)
Definition at line 1939 of file fm-tree-model.c.
References FALSE, FM_IS_TREE_MODEL, and NULL.
fm_tree_model_new()
FMTreeModel * fm_tree_model_new (void)
Definition at line 1831 of file fm-tree-model.c.
References FM_TYPE_TREE_MODEL, and NULL.
fm_tree_model_remove_root_uri()
void fm_tree_model_remove_root_uri (FMTreeModel * model, const char * uri)
Definition at line 1774 of file fm-tree-model.c.
References caja_file_get_by_uri(), caja_file_monitor_remove(), caja_file_unref(), FMTreeModel::details, and NULL.
fm_tree_model_set_highlight_for_files()
void fm_tree_model_set_highlight_for_files (FMTreeModel * model, GList * files)
Definition at line 2006 of file fm-tree-model.c.
References caja_file_list_copy(), caja_file_list_free(), FMTreeModel::details, and NULL.
fm_tree_model_set_show_hidden_files()
void fm_tree_model_set_show_hidden_files (FMTreeModel * model, gboolean show_hidden_files)
Definition at line 1841 of file fm-tree-model.c.
References caja_file_is_hidden_file(), FMTreeModel::details, FALSE, FM_IS_TREE_MODEL, and TRUE.
fm_tree_model_set_show_only_directories()
void fm_tree_model_set_show_only_directories (FMTreeModel * model, gboolean show_only_directories)
Definition at line 1868 of file fm-tree-model.c.
References FMTreeModel::details, FALSE, FM_IS_TREE_MODEL, and TRUE.
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (FMTreeModel , fm_tree_model , G_TYPE_OBJECT , G_IMPLEMENT_INTERFACE(GTK_TYPE_TREE_MODEL, fm_tree_model_tree_model_init))