MATE Desktop Environment: fontmap.c File Reference
fontmap.c File Reference
#include <config.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <sys/stat.h>
#include "mdvi.h"
#include "private.h"
#include <kpathsea/expand.h>
#include <kpathsea/pathsearch.h>
Macros
#define MAP_HASH_SIZE 57
#define ENC_HASH_SIZE 31
#define PSMAP_HASH_SIZE 57
#define ENCNAME_HASH_SIZE 131 /* most TeX fonts have 128 glyphs */
#define DROUND(x) ((x) >= 0 ? floor((x) + 0.5) : ceil((x) - 0.5))
#define TRANSFORM(x, y) DROUND(efactor * (x) + sfactor * (y))
Typedefs
typedef struct _DviFontMap DviFontMap
typedef struct _PSFontMap PSFontMap
Functions
DviEncoding * mdvi_request_encoding (const char *name)
void mdvi_release_encoding (DviEncoding *enc, int should_free)
int mdvi_encode_glyph (DviEncoding *enc, const char *name)
DviFontMapEnt * mdvi_load_fontmap (const char *file)
void mdvi_install_fontmap (DviFontMapEnt *head)
int mdvi_query_fontmap (DviFontMapInfo *info, const char *fontname)
int mdvi_add_fontmap_file (const char *name, const char *fullpath)
void mdvi_flush_encodings (void)
void mdvi_flush_fontmaps (void)
void ps_init_default_paths (void)
int mdvi_ps_read_fontmap (const char *name)
void mdvi_ps_flush_fonts (void)
char * mdvi_ps_find_font (const char *psname)
TFMInfo * mdvi_ps_get_metrics (const char *fontname)
Macro Definition Documentation
DROUND
#define DROUND (x) ((x) >= 0 ? floor((x) + 0.5) : ceil((x) - 0.5))
ENC_HASH_SIZE
#define ENC_HASH_SIZE 31
Definition at line 61 of file fontmap.c.
ENCNAME_HASH_SIZE
#define ENCNAME_HASH_SIZE 131 /* most TeX fonts have 128 glyphs */
Definition at line 66 of file fontmap.c.
MAP_HASH_SIZE
#define MAP_HASH_SIZE 57
Definition at line 60 of file fontmap.c.
PSMAP_HASH_SIZE
#define PSMAP_HASH_SIZE 57
Definition at line 62 of file fontmap.c.
TRANSFORM
#define TRANSFORM (x, y) DROUND(efactor * (x) + sfactor * (y))
Typedef Documentation
DviFontMap
typedef struct _DviFontMap DviFontMap
Definition at line 33 of file fontmap.c.
PSFontMap
typedef struct _PSFontMap PSFontMap
Function Documentation
mdvi_add_fontmap_file()
int mdvi_add_fontmap_file (const char * name, const char * fullpath)
Definition at line 822 of file fontmap.c.
References _DviFontMapEnt::fullfile, mdvi_free(), mdvi_hash_lookup(), MDVI_KEY, mdvi_strdup(), name, and NULL.
mdvi_encode_glyph()
int mdvi_encode_glyph (DviEncoding * enc, const char * name)
Definition at line 404 of file fontmap.c.
References data, mdvi_hash_lookup(), MDVI_KEY, name, _DviEncoding::nametab, NULL, and Ptr2Int.
mdvi_flush_encodings()
void mdvi_flush_encodings (void)
Definition at line 837 of file fontmap.c.
References _, _DviHashTable::buckets, ListHead::count, DBG_FMAP, DEBUG, ListHead::head, _DviEncoding::links, LIST, mdvi_hash_reset(), mdvi_warning(), _DviEncoding::name, _DviEncoding::nametab, _DviHashTable::nbucks, and _DviEncoding::next.
mdvi_flush_fontmaps()
void mdvi_flush_fontmaps (void)
Definition at line 861 of file fontmap.c.
References ListHead::count, DBG_FMAP, DEBUG, ListHead::head, LIST, mdvi_hash_reset(), and _DviFontMapEnt::next.
mdvi_install_fontmap()
void mdvi_install_fontmap (DviFontMapEnt * head)
Definition at line 625 of file fontmap.c.
References DBG_FMAP, DEBUG, _DviFontMapEnt::fontname, LIST, listh_append(), listh_remove(), mdvi_hash_add(), mdvi_hash_remove(), MDVI_HASH_UNCHECKED, MDVI_KEY, _DviFontMapEnt::next, and NULL.
mdvi_load_fontmap()
DviFontMapEnt * mdvi_load_fontmap (const char * file)
Definition at line 464 of file fontmap.c.
References _, dgets(), dstring_init(), dstring_reset(), _DviFontMapEnt::encfile, _DviFontMapEnt::encoding, _DviFontMapEnt::extend, file_extension(), _DviFontMapEnt::fontfile, _DviFontMapEnt::fontname, _DviFontMapEnt::fullfile, getstring(), getword(), ListHead::head, LIST, listh_append(), listh_init(), mdvi_free(), mdvi_strdup(), mdvi_warning(), _DviEncoding::name, NULL, _DviFontMapEnt::psname, SKIPSP, _DviFontMapEnt::slant, STRCEQ, STREQ, and xalloc.
mdvi_ps_find_font()
char * mdvi_ps_find_font (const char * psname)
Definition at line 1021 of file fontmap.c.
References DBG_FMAP, DEBUG, file_exists(), mdvi_hash_lookup(), MDVI_KEY, mdvi_strdup(), and NULL.
Referenced by mdvi_ps_get_metrics().
mdvi_ps_flush_fonts()
void mdvi_ps_flush_fonts (void)
Definition at line 992 of file fontmap.c.
References ListHead::count, DBG_FMAP, DEBUG, ListHead::head, LIST, listh_init(), mdvi_free(), mdvi_hash_reset(), and NULL.
mdvi_ps_get_metrics()
TFMInfo * mdvi_ps_get_metrics (const char * fontname)
Definition at line 1081 of file fontmap.c.
References _TFMChar::advance, _TFMInfo::chars, DBG_FMAP, DEBUG, _TFMChar::depth, DviFontAFM, DviFontAny, DviFontMapInfo::extend, get_font_metrics(), _TFMChar::height, _TFMInfo::hic, _TFMChar::left, _TFMInfo::loc, mdvi_free(), mdvi_malloc(), mdvi_ps_find_font(), mdvi_query_fontmap(), NULL, _TFMChar::present, DviFontMapInfo::psname, _TFMChar::right, DviFontMapInfo::slant, strrchr, and TRANSFORM.
mdvi_ps_read_fontmap()
int mdvi_ps_read_fontmap (const char * name)
Definition at line 899 of file fontmap.c.
References DBG_FMAP, DEBUG, dgets(), dstring_init(), dstring_reset(), file_extension(), getword(), LIST, listh_append(), mdvi_free(), mdvi_hash_add(), mdvi_hash_lookup(), MDVI_HASH_UNCHECKED, MDVI_KEY, mdvi_strdup(), name, NULL, ps_init_default_paths(), SKIPSP, STREQ, and xalloc.
mdvi_query_fontmap()
int mdvi_query_fontmap (DviFontMapInfo * info, const char * fontname)
Definition at line 802 of file fontmap.c.
References DviFontMapInfo::encoding, _DviFontMapEnt::encoding, DviFontMapInfo::extend, _DviFontMapEnt::extend, DviFontMapInfo::fontfile, _DviFontMapEnt::fontfile, DviFontMapInfo::fullfile, _DviFontMapEnt::fullfile, mdvi_hash_lookup(), MDVI_KEY, NULL, DviFontMapInfo::psname, _DviFontMapEnt::psname, DviFontMapInfo::slant, and _DviFontMapEnt::slant.
Referenced by mdvi_ps_get_metrics().
mdvi_release_encoding()
void mdvi_release_encoding (DviEncoding * enc, int should_free)
Definition at line 393 of file fontmap.c.
References DBG_FMAP, DEBUG, _DviEncoding::links, mdvi_hash_reset(), _DviEncoding::name, and _DviEncoding::nametab.
mdvi_request_encoding()
DviEncoding * mdvi_request_encoding (const char * name)
Definition at line 360 of file fontmap.c.
References DBG_FMAP, DEBUG, Int2Ptr, _DviEncoding::links, mdvi_hash_add(), MDVI_HASH_REPLACE, MDVI_KEY, _DviEncoding::name, name, _DviEncoding::nametab, _DviHashTable::nkeys, NULL, _DviEncoding::private, and _DviEncoding::vector.
ps_init_default_paths()
void ps_init_default_paths (void)
Definition at line 879 of file fontmap.c.
References ASSERT, listh_init(), mdvi_hash_create(), NULL, and PSMAP_HASH_SIZE.
Referenced by mdvi_ps_read_fontmap().