MATE Desktop Environment: fr-process.c File Reference
fr-process.c File Reference
#include <config.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <signal.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#include <glib.h>
#include "fr-proc-error.h"
#include "fr-process.h"
#include "fr-marshal.h"
#include "glib-utils.h"
Macros
#define REFRESH_RATE 20
#define BUFFER_SIZE 16384
Enumerations
enum { START , DONE , STICKY_ONLY , LAST_SIGNAL }
Functions
GType fr_process_get_type (void)
FrProcess * fr_process_new (void)
void fr_process_begin_command (FrProcess *process, const char *arg)
void fr_process_begin_command_at (FrProcess *process, const char *arg, int index)
void fr_process_set_working_dir (FrProcess *process, const char *dir)
void fr_process_set_sticky (FrProcess *process, gboolean sticky)
void fr_process_set_ignore_error (FrProcess *process, gboolean ignore_error)
void fr_process_add_arg (FrProcess *process, const char *arg)
void fr_process_add_arg_concat (FrProcess *process, const char *arg1,...)
void fr_process_add_arg_printf (FrProcess *fr_proc, const char *format,...)
void fr_process_set_arg_at (FrProcess *process, int n_comm, int n_arg, const char *arg_value)
void fr_process_set_begin_func (FrProcess *process, ProcFunc func, gpointer func_data)
void fr_process_set_end_func (FrProcess *process, ProcFunc func, gpointer func_data)
void fr_process_set_continue_func (FrProcess *process, ContinueFunc func, gpointer func_data)
void fr_process_end_command (FrProcess *process)
void fr_process_clear (FrProcess *process)
void fr_process_set_out_line_func (FrProcess *process, LineFunc func, gpointer data)
void fr_process_set_err_line_func (FrProcess *process, LineFunc func, gpointer data)
void fr_process_use_standard_locale (FrProcess *process, gboolean use_stand_locale)
void fr_process_start (FrProcess *process)
void fr_process_stop (FrProcess *process)
int start_switch_state (FrProcess *process)
void start_close_suspend_process (FrProcess *process)
Variables
const char * try_charsets [] = { "UTF-8", "ISO-8859-1", "WINDOW-1252" }
int n_charsets = G_N_ELEMENTS (try_charsets)
Macro Definition Documentation
BUFFER_SIZE
#define BUFFER_SIZE 16384
Definition at line 40 of file fr-process.c.
REFRESH_RATE
#define REFRESH_RATE 20
Definition at line 39 of file fr-process.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
START
DONE
STICKY_ONLY
LAST_SIGNAL
Definition at line 42 of file fr-process.c.
Function Documentation
fr_process_add_arg()
void fr_process_add_arg (FrProcess * process, const char * arg)
Definition at line 424 of file fr-process.c.
References NULL, and _FrProcess::priv.
Referenced by fr_archive_add(), fr_archive_extract_to_local(), fr_archive_remove(), fr_process_add_arg_concat(), and fr_process_add_arg_printf().
fr_process_add_arg_concat()
void fr_process_add_arg_concat (FrProcess * process, const char * arg1, ...)
Definition at line 437 of file fr-process.c.
References fr_process_add_arg(), NULL, and TRUE.
fr_process_add_arg_printf()
void fr_process_add_arg_printf (FrProcess * fr_proc, const char * format, ...)
Definition at line 457 of file fr-process.c.
References fr_process_add_arg().
fr_process_begin_command()
void fr_process_begin_command (FrProcess * process, const char * arg)
Definition at line 345 of file fr-process.c.
References NULL, and _FrProcess::priv.
Referenced by fr_archive_add(), fr_archive_extract_to_local(), and fr_archive_remove().
fr_process_begin_command_at()
void fr_process_begin_command_at (FrProcess * process, const char * arg, int index)
Definition at line 362 of file fr-process.c.
References NULL, and _FrProcess::priv.
fr_process_clear()
void fr_process_clear (FrProcess * process)
Definition at line 549 of file fr-process.c.
References NULL, and _FrProcess::priv.
Referenced by fr_archive_test(), fr_window_archive_extract_here(), fr_window_archive_remove(), fr_window_archive_save_as(), fr_window_open_files(), and fr_window_update_files().
fr_process_end_command()
void fr_process_end_command (FrProcess * process)
Definition at line 538 of file fr-process.c.
References NULL, and _FrProcess::priv.
Referenced by fr_archive_add(), fr_archive_extract_to_local(), and fr_archive_remove().
fr_process_get_type()
GType fr_process_get_type (void)
Definition at line 213 of file fr-process.c.
References NULL, and type.
fr_process_new()
FrProcess * fr_process_new (void)
Definition at line 308 of file fr-process.c.
References FR_PROCESS, FR_TYPE_PROCESS, and NULL.
fr_process_set_arg_at()
void fr_process_set_arg_at (FrProcess * process, int n_comm, int n_arg, const char * arg_value)
Definition at line 474 of file fr-process.c.
References NULL, and _FrProcess::priv.
fr_process_set_begin_func()
void fr_process_set_begin_func (FrProcess * process, ProcFunc func, gpointer func_data)
Definition at line 493 of file fr-process.c.
References NULL, and _FrProcess::priv.
fr_process_set_continue_func()
void fr_process_set_continue_func (FrProcess * process, ContinueFunc func, gpointer func_data)
Definition at line 521 of file fr-process.c.
References NULL, and _FrProcess::priv.
fr_process_set_end_func()
void fr_process_set_end_func (FrProcess * process, ProcFunc func, gpointer func_data)
Definition at line 507 of file fr-process.c.
References NULL, and _FrProcess::priv.
fr_process_set_err_line_func()
void fr_process_set_err_line_func (FrProcess * process, LineFunc func, gpointer data)
Definition at line 574 of file fr-process.c.
References data, _FrProcess::err, FrChannelData::line_data, FrChannelData::line_func, and NULL.
Referenced by fr_command_add(), fr_command_delete(), fr_command_extract(), fr_command_list(), and fr_command_test().
fr_process_set_ignore_error()
void fr_process_set_ignore_error (FrProcess * process, gboolean ignore_error)
Definition at line 411 of file fr-process.c.
References FALSE, NULL, and _FrProcess::priv.
Referenced by fr_archive_add().
fr_process_set_out_line_func()
void fr_process_set_out_line_func (FrProcess * process, LineFunc func, gpointer data)
Definition at line 563 of file fr-process.c.
References data, FrChannelData::line_data, FrChannelData::line_func, NULL, and _FrProcess::out.
Referenced by fr_command_add(), fr_command_delete(), fr_command_extract(), fr_command_list(), and fr_command_test().
fr_process_set_sticky()
void fr_process_set_sticky (FrProcess * process, gboolean sticky)
Definition at line 398 of file fr-process.c.
References FALSE, NULL, and _FrProcess::priv.
Referenced by fr_archive_add(), and fr_archive_remove().
fr_process_set_working_dir()
void fr_process_set_working_dir (FrProcess * process, const char * dir)
Definition at line 383 of file fr-process.c.
References NULL, and _FrProcess::priv.
Referenced by fr_archive_add(), and fr_archive_remove().
fr_process_start()
void fr_process_start (FrProcess * process)
Definition at line 961 of file fr-process.c.
References DONE, _FrProcess::err, _FrProcess::error, FALSE, FR_PROC_ERROR_NONE, NULL, _FrProcess::out, _FrProcess::priv, _FrProcess::restart, START, and TRUE.
Referenced by fr_archive_test(), fr_window_archive_extract_here(), fr_window_archive_remove(), fr_window_archive_save_as(), fr_window_open_files(), and fr_window_update_files().
fr_process_stop()
void fr_process_stop (FrProcess * process)
Definition at line 1084 of file fr-process.c.
References TRUE.
Referenced by fr_archive_stop().
fr_process_use_standard_locale()
void fr_process_use_standard_locale (FrProcess * process, gboolean use_stand_locale)
Definition at line 953 of file fr-process.c.
References NULL, and _FrProcess::priv.
Referenced by fr_command_list().
start_close_suspend_process()
void start_close_suspend_process (FrProcess * process)
Definition at line 1092 of file fr-process.c.
start_switch_state()
int start_switch_state (FrProcess * process)
Definition at line 1088 of file fr-process.c.
Variable Documentation
n_charsets
int n_charsets = G_N_ELEMENTS (try_charsets)
Definition at line 188 of file fr-process.c.
try_charsets
const char* try_charsets[] = { "UTF-8", "ISO-8859-1", "WINDOW-1252" }
Definition at line 187 of file fr-process.c.