MATE Desktop Environment: fr-process.h File Reference
fr-process.h File Reference
#include <glib.h>
#include <gtk/gtk.h>
#include <sys/types.h>
#include "typedefs.h"
Classes
struct FrChannelData
struct _FrProcess
struct _FrProcessClass
Macros
#define FR_TYPE_PROCESS (fr_process_get_type ())
#define FR_PROCESS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FR_TYPE_PROCESS, FrProcess))
#define FR_PROCESS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FR_TYPE_PROCESS, FrProcessClass))
#define FR_IS_PROCESS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FR_TYPE_PROCESS))
#define FR_IS_PROCESS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FR_TYPE_PROCESS))
#define FR_PROCESS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), FR_TYPE_PROCESS, FrProcessClass))
Typedefs
typedef struct _FrProcess FrProcess
typedef struct _FrProcessClass FrProcessClass
typedef struct _FrProcessPrivate FrProcessPrivate
typedef void(* ProcFunc) (gpointer data)
typedef gboolean(* ContinueFunc) (gpointer data)
typedef void(* LineFunc) (char *line, gpointer data)
Functions
GType fr_process_get_type (void)
FrProcess * fr_process_new (void)
void fr_process_clear (FrProcess *fr_proc)
void fr_process_begin_command (FrProcess *fr_proc, const char *arg)
void fr_process_begin_command_at (FrProcess *fr_proc, const char *arg, int index)
void fr_process_add_arg (FrProcess *fr_proc, const char *arg)
void fr_process_add_arg_concat (FrProcess *fr_proc, const char *arg,...)
void fr_process_add_arg_printf (FrProcess *fr_proc, const char *format,...)
void fr_process_set_arg_at (FrProcess *fr_proc, int n_comm, int n_arg, const char *arg)
void fr_process_set_begin_func (FrProcess *fr_proc, ProcFunc func, gpointer func_data)
void fr_process_set_end_func (FrProcess *fr_proc, ProcFunc func, gpointer func_data)
void fr_process_set_continue_func (FrProcess *fr_proc, ContinueFunc func, gpointer func_data)
void fr_process_end_command (FrProcess *fr_proc)
void fr_process_set_working_dir (FrProcess *fr_proc, const char *arg)
void fr_process_set_sticky (FrProcess *fr_proc, gboolean sticky)
void fr_process_set_ignore_error (FrProcess *fr_proc, gboolean ignore_error)
void fr_process_use_standard_locale (FrProcess *fr_proc, gboolean use_stand_locale)
void fr_process_set_out_line_func (FrProcess *fr_proc, LineFunc func, gpointer func_data)
void fr_process_set_err_line_func (FrProcess *fr_proc, LineFunc func, gpointer func_data)
void fr_process_start (FrProcess *fr_proc)
void fr_process_stop (FrProcess *fr_proc)
int start_switch_state (FrProcess *fr_proc)
void start_close_suspend_process (FrProcess *fr_proc)
Macro Definition Documentation
FR_IS_PROCESS
#define FR_IS_PROCESS (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FR_TYPE_PROCESS))
Definition at line 34 of file fr-process.h.
FR_IS_PROCESS_CLASS
#define FR_IS_PROCESS_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FR_TYPE_PROCESS))
Definition at line 35 of file fr-process.h.
FR_PROCESS
#define FR_PROCESS (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FR_TYPE_PROCESS, FrProcess))
Definition at line 32 of file fr-process.h.
FR_PROCESS_CLASS
#define FR_PROCESS_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FR_TYPE_PROCESS, FrProcessClass))
Definition at line 33 of file fr-process.h.
FR_PROCESS_GET_CLASS
#define FR_PROCESS_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS((obj), FR_TYPE_PROCESS, FrProcessClass))
Definition at line 36 of file fr-process.h.
FR_TYPE_PROCESS
#define FR_TYPE_PROCESS (fr_process_get_type ())
Definition at line 31 of file fr-process.h.
Typedef Documentation
ContinueFunc
typedef gboolean(* ContinueFunc) (gpointer data)
Definition at line 43 of file fr-process.h.
FrProcess
typedef struct _FrProcess FrProcess
Definition at line 38 of file fr-process.h.
FrProcessClass
typedef struct _FrProcessClass FrProcessClass
Definition at line 39 of file fr-process.h.
FrProcessPrivate
typedef struct _FrProcessPrivate FrProcessPrivate
Definition at line 40 of file fr-process.h.
LineFunc
typedef void(* LineFunc) (char *line, gpointer data)
Definition at line 44 of file fr-process.h.
ProcFunc
typedef void(* ProcFunc) (gpointer data)
Definition at line 42 of file fr-process.h.
Function Documentation
fr_process_add_arg()
void fr_process_add_arg (FrProcess * fr_proc, const char * arg)
Definition at line 424 of file fr-process.c.
References NULL, and _FrProcess::priv.
Referenced by fr_archive_add(), fr_archive_extract_to_local(), fr_archive_remove(), fr_process_add_arg_concat(), and fr_process_add_arg_printf().
fr_process_add_arg_concat()
void fr_process_add_arg_concat (FrProcess * fr_proc, const char * arg, ...)
Definition at line 437 of file fr-process.c.
References fr_process_add_arg(), NULL, and TRUE.
fr_process_add_arg_printf()
void fr_process_add_arg_printf (FrProcess * fr_proc, const char * format, ...)
Definition at line 457 of file fr-process.c.
References fr_process_add_arg().
fr_process_begin_command()
void fr_process_begin_command (FrProcess * fr_proc, const char * arg)
Definition at line 345 of file fr-process.c.
References NULL, and _FrProcess::priv.
Referenced by fr_archive_add(), fr_archive_extract_to_local(), and fr_archive_remove().
fr_process_begin_command_at()
void fr_process_begin_command_at (FrProcess * fr_proc, const char * arg, int index)
Definition at line 362 of file fr-process.c.
References NULL, and _FrProcess::priv.
fr_process_clear()
void fr_process_clear (FrProcess * fr_proc)
Definition at line 549 of file fr-process.c.
References NULL, and _FrProcess::priv.
Referenced by fr_archive_test(), fr_window_archive_extract_here(), fr_window_archive_remove(), fr_window_archive_save_as(), fr_window_open_files(), and fr_window_update_files().
fr_process_end_command()
void fr_process_end_command (FrProcess * fr_proc)
Definition at line 538 of file fr-process.c.
References NULL, and _FrProcess::priv.
Referenced by fr_archive_add(), fr_archive_extract_to_local(), and fr_archive_remove().
fr_process_get_type()
GType fr_process_get_type (void)
Definition at line 213 of file fr-process.c.
References NULL, and type.
fr_process_new()
FrProcess * fr_process_new (void)
Definition at line 308 of file fr-process.c.
References FR_PROCESS, FR_TYPE_PROCESS, and NULL.
fr_process_set_arg_at()
void fr_process_set_arg_at (FrProcess * fr_proc, int n_comm, int n_arg, const char * arg)
Definition at line 474 of file fr-process.c.
References NULL, and _FrProcess::priv.
fr_process_set_begin_func()
void fr_process_set_begin_func (FrProcess * fr_proc, ProcFunc func, gpointer func_data)
Definition at line 493 of file fr-process.c.
References NULL, and _FrProcess::priv.
fr_process_set_continue_func()
void fr_process_set_continue_func (FrProcess * fr_proc, ContinueFunc func, gpointer func_data)
Definition at line 521 of file fr-process.c.
References NULL, and _FrProcess::priv.
fr_process_set_end_func()
void fr_process_set_end_func (FrProcess * fr_proc, ProcFunc func, gpointer func_data)
Definition at line 507 of file fr-process.c.
References NULL, and _FrProcess::priv.
fr_process_set_err_line_func()
void fr_process_set_err_line_func (FrProcess * fr_proc, LineFunc func, gpointer func_data)
Definition at line 574 of file fr-process.c.
References data, _FrProcess::err, FrChannelData::line_data, FrChannelData::line_func, and NULL.
Referenced by fr_command_add(), fr_command_delete(), fr_command_extract(), fr_command_list(), and fr_command_test().
fr_process_set_ignore_error()
void fr_process_set_ignore_error (FrProcess * fr_proc, gboolean ignore_error)
Definition at line 411 of file fr-process.c.
References FALSE, NULL, and _FrProcess::priv.
Referenced by fr_archive_add().
fr_process_set_out_line_func()
void fr_process_set_out_line_func (FrProcess * fr_proc, LineFunc func, gpointer func_data)
Definition at line 563 of file fr-process.c.
References data, FrChannelData::line_data, FrChannelData::line_func, NULL, and _FrProcess::out.
Referenced by fr_command_add(), fr_command_delete(), fr_command_extract(), fr_command_list(), and fr_command_test().
fr_process_set_sticky()
void fr_process_set_sticky (FrProcess * fr_proc, gboolean sticky)
Definition at line 398 of file fr-process.c.
References FALSE, NULL, and _FrProcess::priv.
Referenced by fr_archive_add(), and fr_archive_remove().
fr_process_set_working_dir()
void fr_process_set_working_dir (FrProcess * fr_proc, const char * arg)
Definition at line 383 of file fr-process.c.
References NULL, and _FrProcess::priv.
Referenced by fr_archive_add(), and fr_archive_remove().
fr_process_start()
void fr_process_start (FrProcess * fr_proc)
Definition at line 961 of file fr-process.c.
References DONE, _FrProcess::err, _FrProcess::error, FALSE, FR_PROC_ERROR_NONE, NULL, _FrProcess::out, _FrProcess::priv, _FrProcess::restart, START, and TRUE.
Referenced by fr_archive_test(), fr_window_archive_extract_here(), fr_window_archive_remove(), fr_window_archive_save_as(), fr_window_open_files(), and fr_window_update_files().
fr_process_stop()
void fr_process_stop (FrProcess * fr_proc)
Definition at line 1084 of file fr-process.c.
References TRUE.
Referenced by fr_archive_stop().
fr_process_use_standard_locale()
void fr_process_use_standard_locale (FrProcess * fr_proc, gboolean use_stand_locale)
Definition at line 953 of file fr-process.c.
References NULL, and _FrProcess::priv.
Referenced by fr_command_list().
start_close_suspend_process()
void start_close_suspend_process (FrProcess * fr_proc)
Definition at line 1092 of file fr-process.c.
start_switch_state()
int start_switch_state (FrProcess * fr_proc)
Definition at line 1088 of file fr-process.c.