MATE Desktop Environment: frame.h File Reference
frame.h File Reference
#include <X11/Xlib.h>
#include "common.h"
#include "types.h"
Functions
Window meta_frame_get_xwindow (MetaFrame *frame)
void meta_frame_calc_borders (MetaFrame *frame, MetaFrameBorders *borders)
void meta_frame_clear_cached_borders (MetaFrame *frame)
Function Documentation
meta_frame_calc_borders()
void meta_frame_calc_borders (MetaFrame * frame, MetaFrameBorders * borders)
Definition at line 326 of file frame.c.
References _MetaFrame::borders_cached, _MetaFrame::cached_borders, meta_frame_borders_clear(), meta_ui_get_frame_borders(), NULL, _MetaWindow::screen, TRUE, _MetaScreen::ui, _MetaFrame::window, and _MetaFrame::xwindow.
Referenced by meta_window_can_tile(), meta_window_destroy_frame(), and meta_window_get_outer_rect().
meta_frame_clear_cached_borders()
void meta_frame_clear_cached_borders (MetaFrame * frame)
Definition at line 348 of file frame.c.
References _MetaFrame::borders_cached, and FALSE.
Referenced by meta_window_frame_size_changed().
meta_frame_get_xwindow()
Window meta_frame_get_xwindow (MetaFrame * frame)
Definition at line 477 of file frame.c.
References _MetaFrame::xwindow.