MATE Desktop Environment: frame-private.h File Reference
frame-private.h File Reference
#include "frame.h"
#include "window-private.h"
Classes
struct _MetaFrame
Functions
void meta_window_ensure_frame (MetaWindow *window)
void meta_window_destroy_frame (MetaWindow *window)
void meta_frame_queue_draw (MetaFrame *frame)
MetaFrameFlags meta_frame_get_flags (MetaFrame *frame)
void meta_frame_get_corner_radiuses (MetaFrame *frame, float *top_left, float *top_right, float *bottom_left, float *bottom_right)
gboolean meta_frame_sync_to_window (MetaFrame *frame, int gravity, gboolean need_move, gboolean need_resize)
cairo_region_t * meta_frame_get_frame_bounds (MetaFrame *frame)
void meta_frame_set_screen_cursor (MetaFrame *frame, MetaCursor cursor)
Function Documentation
meta_frame_get_corner_radiuses()
void meta_frame_get_corner_radiuses (MetaFrame * frame, float * top_left, float * top_right, float * bottom_left, float * bottom_right)
Definition at line 372 of file frame.c.
References meta_ui_get_corner_radiuses(), _MetaWindow::screen, _MetaScreen::ui, _MetaFrame::window, and _MetaFrame::xwindow.
meta_frame_get_flags()
MetaFrameFlags meta_frame_get_flags (MetaFrame * frame)
Definition at line 235 of file frame.c.
References _MetaWindow::border_only, _MetaWindow::fullscreen, _MetaWindow::has_close_func, _MetaWindow::has_maximize_func, _MetaWindow::has_minimize_func, _MetaWindow::has_shade_func, _MetaFrame::is_flashing, META_FRAME_ABOVE, META_FRAME_ALLOWS_DELETE, META_FRAME_ALLOWS_HORIZONTAL_RESIZE, META_FRAME_ALLOWS_MAXIMIZE, META_FRAME_ALLOWS_MENU, META_FRAME_ALLOWS_MINIMIZE, META_FRAME_ALLOWS_MOVE, META_FRAME_ALLOWS_SHADE, META_FRAME_ALLOWS_VERTICAL_RESIZE, META_FRAME_FULLSCREEN, META_FRAME_HAS_FOCUS, META_FRAME_IS_FLASHING, META_FRAME_MAXIMIZED, META_FRAME_SHADED, META_FRAME_STUCK, META_FRAME_TILED_LEFT, META_FRAME_TILED_RIGHT, META_WINDOW_ALLOWS_HORIZONTAL_RESIZE, META_WINDOW_ALLOWS_MOVE, META_WINDOW_ALLOWS_VERTICAL_RESIZE, meta_window_appears_focused(), META_WINDOW_MAXIMIZED, META_WINDOW_TILED_LEFT, META_WINDOW_TILED_RIGHT, _MetaWindow::on_all_workspaces, _MetaWindow::shaded, _MetaFrame::window, and _MetaWindow::wm_state_above.
Referenced by meta_core_get().
meta_frame_get_frame_bounds()
cairo_region_t * meta_frame_get_frame_bounds (MetaFrame * frame)
Definition at line 438 of file frame.c.
References _MetaRectangle::height, meta_ui_get_frame_bounds(), NULL, _MetaFrame::rect, _MetaWindow::screen, _MetaScreen::ui, _MetaRectangle::width, _MetaFrame::window, and _MetaFrame::xwindow.
Referenced by meta_window_get_frame_bounds().
meta_frame_queue_draw()
void meta_frame_queue_draw (MetaFrame * frame)
Definition at line 451 of file frame.c.
References meta_ui_queue_frame_draw(), _MetaWindow::screen, _MetaScreen::ui, _MetaFrame::window, and _MetaFrame::xwindow.
Referenced by meta_display_queue_retheme_all_windows().
meta_frame_set_screen_cursor()
void meta_frame_set_screen_cursor (MetaFrame * frame, MetaCursor cursor)
Definition at line 458 of file frame.c.
References _MetaFrame::current_cursor, _MetaWindow::display, META_CURSOR_DEFAULT, meta_display_create_x_cursor(), _MetaFrame::window, _MetaDisplay::xdisplay, and _MetaFrame::xwindow.
Referenced by meta_core_set_screen_cursor().
meta_frame_sync_to_window()
gboolean meta_frame_sync_to_window (MetaFrame * frame, int gravity, gboolean need_move, gboolean need_resize)
Definition at line 385 of file frame.c.
References _MetaWindow::display, _MetaDisplay::grab_window, _MetaRectangle::height, META_DEBUG_GEOMETRY, meta_ui_move_resize_frame(), meta_ui_repaint_frame(), _MetaFrame::need_reapply_frame_shape, _MetaFrame::rect, _MetaWindow::screen, TRUE, _MetaScreen::ui, _MetaRectangle::width, _MetaFrame::window, _MetaRectangle::x, _MetaFrame::xwindow, and _MetaRectangle::y.
meta_window_destroy_frame()
void meta_window_destroy_frame (MetaWindow * window)
Definition at line 169 of file frame.c.
References _MetaWindow::desc, _MetaWindow::display, FALSE, _MetaWindow::frame, _MetaWindow::frame_bounds, _MetaFrameBorders::invisible, _MetaWindow::mapped, meta_bell_notify_frame_destroy(), META_DEBUG_WINDOW_STATE, meta_display_unregister_x_window(), meta_error_trap_pop(), meta_error_trap_push(), meta_frame_calc_borders(), meta_prefs_remove_listener(), META_QUEUE_CALC_SHOWING, META_QUEUE_MOVE_RESIZE, meta_ui_destroy_frame_window(), meta_window_grab_keys(), meta_window_queue(), NULL, _MetaFrame::rect, _MetaWindow::screen, _MetaScreen::ui, _MetaWindow::unmaps_pending, _MetaRectangle::x, _MetaDisplay::xdisplay, _MetaScreen::xroot, _MetaFrame::xwindow, _MetaWindow::xwindow, and _MetaRectangle::y.
Referenced by meta_window_free().
meta_window_ensure_frame()
void meta_window_ensure_frame (MetaWindow * window)
Definition at line 62 of file frame.c.
References _MetaFrame::borders_cached, _MetaFrame::bottom_height, _MetaFrame::child_x, _MetaFrame::child_y, _MetaFrame::current_cursor, _MetaWindow::desc, _MetaWindow::display, EVENT_MASK, FALSE, _MetaWindow::frame, _MetaWindow::has_shape, _MetaRectangle::height, _MetaFrame::is_flashing, _MetaFrame::mapped, _MetaWindow::mapped, META_DEBUG_WINDOW_STATE, meta_display_grab(), meta_display_register_x_window(), meta_display_ungrab(), meta_error_trap_pop(), meta_error_trap_push(), meta_prefs_add_listener(), meta_ui_apply_frame_shape(), meta_ui_create_frame_window(), meta_ui_set_frame_title(), meta_ui_update_frame_style(), meta_window_grab_keys(), _MetaFrame::need_reapply_frame_shape, _MetaFrame::rect, _MetaWindow::rect, _MetaFrame::right_width, _MetaWindow::screen, _MetaWindow::title, TRUE, _MetaScreen::ui, _MetaWindow::unmaps_pending, _MetaRectangle::width, _MetaFrame::window, _MetaRectangle::x, _MetaDisplay::xdisplay, _MetaWindow::xvisual, _MetaFrame::xwindow, _MetaWindow::xwindow, and _MetaRectangle::y.
Referenced by meta_window_new_with_attrs().