MATE Desktop Environment: frames.h File Reference
frames.h File Reference
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
#include "common.h"
#include "theme.h"
#include "types.h"
Classes
struct _MetaUIFrame
struct _MetaFrames
struct _MetaFramesClass
Macros
#define META_TYPE_FRAMES (meta_frames_get_type ())
#define META_FRAMES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), META_TYPE_FRAMES, MetaFrames))
#define META_FRAMES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), META_TYPE_FRAMES, MetaFramesClass))
#define META_IS_FRAMES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), META_TYPE_FRAMES))
#define META_IS_FRAMES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), META_TYPE_FRAMES))
#define META_FRAMES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), META_TYPE_FRAMES, MetaFramesClass))
Typedefs
typedef struct _MetaFrames MetaFrames
typedef struct _MetaFramesClass MetaFramesClass
typedef struct _MetaUIFrame MetaUIFrame
Enumerations
enum MetaFrameControl {
META_FRAME_CONTROL_NONE , META_FRAME_CONTROL_TITLE , META_FRAME_CONTROL_DELETE , META_FRAME_CONTROL_MENU ,
META_FRAME_CONTROL_APPMENU , META_FRAME_CONTROL_MINIMIZE , META_FRAME_CONTROL_MAXIMIZE , META_FRAME_CONTROL_UNMAXIMIZE ,
META_FRAME_CONTROL_SHADE , META_FRAME_CONTROL_UNSHADE , META_FRAME_CONTROL_ABOVE , META_FRAME_CONTROL_UNABOVE ,
META_FRAME_CONTROL_STICK , META_FRAME_CONTROL_UNSTICK , META_FRAME_CONTROL_RESIZE_SE , META_FRAME_CONTROL_RESIZE_S ,
META_FRAME_CONTROL_RESIZE_SW , META_FRAME_CONTROL_RESIZE_N , META_FRAME_CONTROL_RESIZE_NE , META_FRAME_CONTROL_RESIZE_NW ,
META_FRAME_CONTROL_RESIZE_W , META_FRAME_CONTROL_RESIZE_E , META_FRAME_CONTROL_CLIENT_AREA
}
Functions
GType meta_frames_get_type (void)
MetaFrames * meta_frames_new (void)
void meta_frames_manage_window (MetaFrames *frames, Window xwindow, GdkWindow *window)
void meta_frames_unmanage_window (MetaFrames *frames, Window xwindow)
void meta_frames_set_title (MetaFrames *frames, Window xwindow, const char *title)
void meta_frames_update_frame_style (MetaFrames *frames, Window xwindow)
void meta_frames_repaint_frame (MetaFrames *frames, Window xwindow)
void meta_frames_get_borders (MetaFrames *frames, Window xwindow, MetaFrameBorders *borders)
void meta_frames_apply_shapes (MetaFrames *frames, MetaDisplay *meta_display, Window xwindow, int new_window_width, int new_window_height, gboolean window_has_shape)
cairo_region_t * meta_frames_get_frame_bounds (MetaFrames *frames, Window xwindow, int window_width, int window_height)
void meta_frames_get_corner_radiuses (MetaFrames *frames, Window xwindow, float *top_left, float *top_right, float *bottom_left, float *bottom_right)
void meta_frames_move_resize_frame (MetaFrames *frames, Window xwindow, int x, int y, int width, int height)
void meta_frames_queue_draw (MetaFrames *frames, Window xwindow)
void meta_frames_notify_menu_hide (MetaFrames *frames)
Window meta_frames_get_moving_frame (MetaFrames *frames)
void meta_frames_push_delay_exposes (MetaFrames *frames)
void meta_frames_pop_delay_exposes (MetaFrames *frames)
Macro Definition Documentation
META_FRAMES
#define META_FRAMES (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), META_TYPE_FRAMES, MetaFrames))
Definition at line 65 of file frames.h.
META_FRAMES_CLASS
#define META_FRAMES_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), META_TYPE_FRAMES, MetaFramesClass))
Definition at line 66 of file frames.h.
META_FRAMES_GET_CLASS
#define META_FRAMES_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), META_TYPE_FRAMES, MetaFramesClass))
Definition at line 69 of file frames.h.
META_IS_FRAMES
#define META_IS_FRAMES (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), META_TYPE_FRAMES))
Definition at line 67 of file frames.h.
META_IS_FRAMES_CLASS
#define META_IS_FRAMES_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), META_TYPE_FRAMES))
Definition at line 68 of file frames.h.
META_TYPE_FRAMES
#define META_TYPE_FRAMES (meta_frames_get_type ())
Definition at line 64 of file frames.h.
Typedef Documentation
MetaFrames
typedef struct _MetaFrames MetaFrames
Definition at line 71 of file frames.h.
MetaFramesClass
typedef struct _MetaFramesClass MetaFramesClass
Definition at line 72 of file frames.h.
MetaUIFrame
typedef struct _MetaUIFrame MetaUIFrame
Definition at line 74 of file frames.h.
Enumeration Type Documentation
MetaFrameControl
enum MetaFrameControl
Enumerator
META_FRAME_CONTROL_NONE
META_FRAME_CONTROL_TITLE
META_FRAME_CONTROL_DELETE
META_FRAME_CONTROL_MENU
META_FRAME_CONTROL_APPMENU
META_FRAME_CONTROL_MINIMIZE
META_FRAME_CONTROL_MAXIMIZE
META_FRAME_CONTROL_UNMAXIMIZE
META_FRAME_CONTROL_SHADE
META_FRAME_CONTROL_UNSHADE
META_FRAME_CONTROL_ABOVE
META_FRAME_CONTROL_UNABOVE
META_FRAME_CONTROL_STICK
META_FRAME_CONTROL_UNSTICK
META_FRAME_CONTROL_RESIZE_SE
META_FRAME_CONTROL_RESIZE_S
META_FRAME_CONTROL_RESIZE_SW
META_FRAME_CONTROL_RESIZE_N
META_FRAME_CONTROL_RESIZE_NE
META_FRAME_CONTROL_RESIZE_NW
META_FRAME_CONTROL_RESIZE_W
META_FRAME_CONTROL_RESIZE_E
META_FRAME_CONTROL_CLIENT_AREA
Definition at line 33 of file frames.h.
Function Documentation
meta_frames_apply_shapes()
void meta_frames_apply_shapes (MetaFrames * frames, MetaDisplay * meta_display, Window xwindow, int new_window_width, int new_window_height, gboolean window_has_shape)
Definition at line 1067 of file frames.c.
References _MetaFrameGeometry::borders, FALSE, meta_core_get(), META_CORE_GET_CLIENT_XWINDOW, META_CORE_GET_END, META_DEBUG_SHAPES, meta_display_get_compositor(), meta_prefs_get_compositing_manager(), NULL, _MetaUIFrame::shape_applied, _MetaFrameBorders::total, TRUE, and _MetaUIFrame::xwindow.
Referenced by meta_ui_apply_frame_shape().
meta_frames_get_borders()
void meta_frames_get_borders (MetaFrames * frames, Window xwindow, MetaFrameBorders * borders)
Definition at line 808 of file frames.c.
References NULL.
Referenced by meta_ui_get_frame_borders().
meta_frames_get_corner_radiuses()
void meta_frames_get_corner_radiuses (MetaFrames * frames, Window xwindow, float * top_left, float * top_right, float * bottom_left, float * bottom_right)
Definition at line 854 of file frames.c.
Referenced by meta_ui_get_corner_radiuses().
meta_frames_get_frame_bounds()
cairo_region_t * meta_frames_get_frame_bounds (MetaFrames * frames, Window xwindow, int window_width, int window_height)
Definition at line 1213 of file frames.c.
References NULL.
Referenced by meta_ui_get_frame_bounds().
meta_frames_get_moving_frame()
Window meta_frames_get_moving_frame (MetaFrames * frames)
meta_frames_get_type()
GType meta_frames_get_type (void)
meta_frames_manage_window()
void meta_frames_manage_window (MetaFrames * frames, Window xwindow, GdkWindow * window)
Definition at line 671 of file frames.c.
References _MetaUIFrame::cache_style, _MetaUIFrame::expose_delayed, FALSE, _MetaFrames::frames, meta_core_grab_buttons(), META_FRAME_CONTROL_NONE, NULL, _MetaUIFrame::prelit_control, _MetaUIFrame::shape_applied, _MetaUIFrame::style, _MetaUIFrame::text_height, _MetaUIFrame::text_layout, _MetaUIFrame::title, _MetaUIFrame::window, and _MetaUIFrame::xwindow.
Referenced by meta_ui_create_frame_window().
meta_frames_move_resize_frame()
void meta_frames_move_resize_frame (MetaFrames * frames, Window xwindow, int x, int y, int width, int height)
Definition at line 1234 of file frames.c.
References _MetaUIFrame::window.
Referenced by meta_ui_move_resize_frame().
meta_frames_new()
MetaFrames * meta_frames_new (void)
Definition at line 618 of file frames.c.
References META_TYPE_FRAMES, and NULL.
Referenced by meta_ui_new().
meta_frames_notify_menu_hide()
void meta_frames_notify_menu_hide (MetaFrames * frames)
Definition at line 1954 of file frames.c.
References meta_core_end_grab_op(), meta_core_get_grab_frame(), meta_core_get_grab_op(), META_FRAME_CONTROL_MENU, and META_GRAB_OP_CLICKING_MENU.
meta_frames_pop_delay_exposes()
void meta_frames_pop_delay_exposes (MetaFrames * frames)
Definition at line 3091 of file frames.c.
References _MetaFrames::expose_delay_count, and _MetaFrames::frames.
Referenced by meta_ui_pop_delay_exposes().
meta_frames_push_delay_exposes()
void meta_frames_push_delay_exposes (MetaFrames * frames)
Definition at line 3063 of file frames.c.
References _MetaFrames::expose_delay_count.
Referenced by meta_ui_push_delay_exposes().
meta_frames_queue_draw()
void meta_frames_queue_draw (MetaFrames * frames, Window xwindow)
Definition at line 1257 of file frames.c.
Referenced by meta_ui_queue_frame_draw().
meta_frames_repaint_frame()
void meta_frames_repaint_frame (MetaFrames * frames, Window xwindow)
Definition at line 1301 of file frames.c.
Referenced by meta_ui_repaint_frame().
meta_frames_set_title()
void meta_frames_set_title (MetaFrames * frames, Window xwindow, const char * title)
Definition at line 1268 of file frames.c.
References _MetaUIFrame::text_layout, and _MetaUIFrame::title.
Referenced by meta_ui_set_frame_title().
meta_frames_unmanage_window()
void meta_frames_unmanage_window (MetaFrames * frames, Window xwindow)
Definition at line 704 of file frames.c.
References _MetaFrames::frames, _MetaFrames::last_motion_frame, meta_core_set_screen_cursor(), META_CURSOR_DEFAULT, meta_warning(), NULL, _MetaUIFrame::style, _MetaUIFrame::text_layout, _MetaUIFrame::title, _MetaUIFrame::window, and _MetaUIFrame::xwindow.
Referenced by meta_ui_destroy_frame_window().
meta_frames_update_frame_style()
void meta_frames_update_frame_style (MetaFrames * frames, Window xwindow)
Definition at line 1287 of file frames.c.
Referenced by meta_ui_update_frame_style().