MATE Desktop Environment: frames.c File Reference
frames.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include <math.h>
#include <string.h>
#include "boxes.h"
#include "frames.h"
#include "util.h"
#include "core.h"
#include "menu.h"
#include "fixedtip.h"
#include "theme.h"
#include "prefs.h"
#include "ui.h"
#include "display.h"
#include <cairo-xlib.h>
Macros
#define DEFAULT_INNER_BUTTON_BORDER 3
#define TIP_DELAY 450
#define DECORATING_BORDER 100
#define RESIZE_EXTENDS 15
#define TOP_RESIZE_HEIGHT 4
Functions
G_DEFINE_TYPE (MetaFrames, meta_frames, GTK_TYPE_WINDOW)
MetaFrames * meta_frames_new (void)
void meta_frames_manage_window (MetaFrames *frames, Window xwindow, GdkWindow *window)
void meta_frames_unmanage_window (MetaFrames *frames, Window xwindow)
void meta_frames_get_borders (MetaFrames *frames, Window xwindow, MetaFrameBorders *borders)
void meta_frames_get_corner_radiuses (MetaFrames *frames, Window xwindow, float *top_left, float *top_right, float *bottom_left, float *bottom_right)
void meta_frames_apply_shapes (MetaFrames *frames, MetaDisplay *meta_display, Window xwindow, int new_window_width, int new_window_height, gboolean window_has_shape)
cairo_region_t * meta_frames_get_frame_bounds (MetaFrames *frames, Window xwindow, int window_width, int window_height)
void meta_frames_move_resize_frame (MetaFrames *frames, Window xwindow, int x, int y, int width, int height)
void meta_frames_queue_draw (MetaFrames *frames, Window xwindow)
void meta_frames_set_title (MetaFrames *frames, Window xwindow, const char *title)
void meta_frames_update_frame_style (MetaFrames *frames, Window xwindow)
void meta_frames_repaint_frame (MetaFrames *frames, Window xwindow)
void meta_frames_notify_menu_hide (MetaFrames *frames)
void meta_frames_push_delay_exposes (MetaFrames *frames)
void meta_frames_pop_delay_exposes (MetaFrames *frames)
Macro Definition Documentation
DECORATING_BORDER
#define DECORATING_BORDER 100
Definition at line 2656 of file frames.c.
DEFAULT_INNER_BUTTON_BORDER
#define DEFAULT_INNER_BUTTON_BORDER 3
Definition at line 50 of file frames.c.
RESIZE_EXTENDS
#define RESIZE_EXTENDS 15
Definition at line 2903 of file frames.c.
TIP_DELAY
#define TIP_DELAY 450
Definition at line 1441 of file frames.c.
TOP_RESIZE_HEIGHT
#define TOP_RESIZE_HEIGHT 4
Definition at line 2904 of file frames.c.
Function Documentation
G_DEFINE_TYPE()
G_DEFINE_TYPE (MetaFrames , meta_frames , GTK_TYPE_WINDOW)
meta_frames_apply_shapes()
void meta_frames_apply_shapes (MetaFrames * frames, MetaDisplay * meta_display, Window xwindow, int new_window_width, int new_window_height, gboolean window_has_shape)
Definition at line 1067 of file frames.c.
References _MetaFrameGeometry::borders, FALSE, meta_core_get(), META_CORE_GET_CLIENT_XWINDOW, META_CORE_GET_END, META_DEBUG_SHAPES, meta_display_get_compositor(), meta_prefs_get_compositing_manager(), NULL, _MetaUIFrame::shape_applied, _MetaFrameBorders::total, TRUE, and _MetaUIFrame::xwindow.
Referenced by meta_ui_apply_frame_shape().
meta_frames_get_borders()
void meta_frames_get_borders (MetaFrames * frames, Window xwindow, MetaFrameBorders * borders)
Definition at line 808 of file frames.c.
References NULL.
Referenced by meta_ui_get_frame_borders().
meta_frames_get_corner_radiuses()
void meta_frames_get_corner_radiuses (MetaFrames * frames, Window xwindow, float * top_left, float * top_right, float * bottom_left, float * bottom_right)
Definition at line 854 of file frames.c.
Referenced by meta_ui_get_corner_radiuses().
meta_frames_get_frame_bounds()
cairo_region_t * meta_frames_get_frame_bounds (MetaFrames * frames, Window xwindow, int window_width, int window_height)
Definition at line 1213 of file frames.c.
References NULL.
Referenced by meta_ui_get_frame_bounds().
meta_frames_manage_window()
void meta_frames_manage_window (MetaFrames * frames, Window xwindow, GdkWindow * window)
Definition at line 671 of file frames.c.
References _MetaUIFrame::cache_style, _MetaUIFrame::expose_delayed, FALSE, _MetaFrames::frames, meta_core_grab_buttons(), META_FRAME_CONTROL_NONE, NULL, _MetaUIFrame::prelit_control, _MetaUIFrame::shape_applied, _MetaUIFrame::style, _MetaUIFrame::text_height, _MetaUIFrame::text_layout, _MetaUIFrame::title, _MetaUIFrame::window, and _MetaUIFrame::xwindow.
Referenced by meta_ui_create_frame_window().
meta_frames_move_resize_frame()
void meta_frames_move_resize_frame (MetaFrames * frames, Window xwindow, int x, int y, int width, int height)
Definition at line 1234 of file frames.c.
References _MetaUIFrame::window.
Referenced by meta_ui_move_resize_frame().
meta_frames_new()
MetaFrames * meta_frames_new (void)
Definition at line 618 of file frames.c.
References META_TYPE_FRAMES, and NULL.
Referenced by meta_ui_new().
meta_frames_notify_menu_hide()
void meta_frames_notify_menu_hide (MetaFrames * frames)
Definition at line 1954 of file frames.c.
References meta_core_end_grab_op(), meta_core_get_grab_frame(), meta_core_get_grab_op(), META_FRAME_CONTROL_MENU, and META_GRAB_OP_CLICKING_MENU.
meta_frames_pop_delay_exposes()
void meta_frames_pop_delay_exposes (MetaFrames * frames)
Definition at line 3091 of file frames.c.
References _MetaFrames::expose_delay_count, and _MetaFrames::frames.
Referenced by meta_ui_pop_delay_exposes().
meta_frames_push_delay_exposes()
void meta_frames_push_delay_exposes (MetaFrames * frames)
Definition at line 3063 of file frames.c.
References _MetaFrames::expose_delay_count.
Referenced by meta_ui_push_delay_exposes().
meta_frames_queue_draw()
void meta_frames_queue_draw (MetaFrames * frames, Window xwindow)
Definition at line 1257 of file frames.c.
Referenced by meta_ui_queue_frame_draw().
meta_frames_repaint_frame()
void meta_frames_repaint_frame (MetaFrames * frames, Window xwindow)
Definition at line 1301 of file frames.c.
Referenced by meta_ui_repaint_frame().
meta_frames_set_title()
void meta_frames_set_title (MetaFrames * frames, Window xwindow, const char * title)
Definition at line 1268 of file frames.c.
References _MetaUIFrame::text_layout, and _MetaUIFrame::title.
Referenced by meta_ui_set_frame_title().
meta_frames_unmanage_window()
void meta_frames_unmanage_window (MetaFrames * frames, Window xwindow)
Definition at line 704 of file frames.c.
References _MetaFrames::frames, _MetaFrames::last_motion_frame, meta_core_set_screen_cursor(), META_CURSOR_DEFAULT, meta_warning(), NULL, _MetaUIFrame::style, _MetaUIFrame::text_layout, _MetaUIFrame::title, _MetaUIFrame::window, and _MetaUIFrame::xwindow.
Referenced by meta_ui_destroy_frame_window().
meta_frames_update_frame_style()
void meta_frames_update_frame_style (MetaFrames * frames, Window xwindow)
Definition at line 1287 of file frames.c.
Referenced by meta_ui_update_frame_style().