MATE Desktop Environment: gdict-app.c File Reference
gdict-app.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <sys/stat.h>
#include <gtk/gtk.h>
#include <glib.h>
#include <glib/gi18n.h>
#include "gdict-common.h"
#include "gdict-pref-dialog.h"
#include "gdict-app.h"
Functions
G_DEFINE_TYPE (GdictApp, gdict_app, G_TYPE_OBJECT)
void gdict_init (int *argc, char ***argv)
void gdict_main (void)
void gdict_cleanup (void)
Function Documentation
G_DEFINE_TYPE()
G_DEFINE_TYPE (GdictApp , gdict_app , G_TYPE_OBJECT)
gdict_cleanup()
void gdict_cleanup (void)
Definition at line 426 of file gdict-app.c.
Referenced by gdict_init(), and main().
gdict_init()
void gdict_init (int * argc, char *** argv)
Definition at line 305 of file gdict-app.c.
References _, _GdictApp::database, FALSE, GDICT_APP, gdict_cleanup(), gdict_create_data_dir(), gdict_get_data_dir(), gdict_get_option_group(), GDICT_IS_APP, gdict_source_loader_add_search_path(), gdict_source_loader_new(), GDICT_TYPE_APP, _GdictApp::loader, _GdictApp::lookup_words, _GdictApp::match_words, N_, _GdictApp::no_window, NULL, _GdictApp::settings, _GdictApp::source_name, and TRUE.
Referenced by main().
gdict_main()
void gdict_main (void)
Definition at line 409 of file gdict-app.c.
References _GdictApp::no_window.
Referenced by main().