MATE Desktop Environment: gdict-defbox.h File Reference
gdict-defbox.h File Reference
#include <gtk/gtk.h>
#include "gdict-context.h"
Classes
struct _GdictDefbox
struct _GdictDefboxClass
Macros
#define GDICT_TYPE_DEFBOX (gdict_defbox_get_type ())
#define GDICT_DEFBOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GDICT_TYPE_DEFBOX, GdictDefbox))
#define GDICT_IS_DEFBOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GDICT_TYPE_DEFBOX))
#define GDICT_DEFBOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GDICT_TYPE_DEFBOX, GdictDefboxClass))
#define GDICT_IS_DEFBOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GDICT_TYPE_DEFBOX))
#define GDICT_DEFBOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GDICT_TYPE_DEFBOX, GdictDefboxClass))
Typedefs
typedef struct _GdictDefbox GdictDefbox
typedef struct _GdictDefboxClass GdictDefboxClass
typedef struct _GdictDefboxPrivate GdictDefboxPrivate
Functions
GType gdict_defbox_get_type (void)
GtkWidget * gdict_defbox_new (void)
GtkWidget * gdict_defbox_new_with_context (GdictContext *context)
void gdict_defbox_set_context (GdictDefbox *defbox, GdictContext *context)
GdictContext * gdict_defbox_get_context (GdictDefbox *defbox)
void gdict_defbox_set_database (GdictDefbox *defbox, const gchar *database)
const gchar * gdict_defbox_get_database (GdictDefbox *defbox)
const gchar * gdict_defbox_get_word (GdictDefbox *defbox)
gchar * gdict_defbox_get_text (GdictDefbox *defbox, gsize *length) G_GNUC_MALLOC
void gdict_defbox_select_all (GdictDefbox *defbox)
void gdict_defbox_copy_to_clipboard (GdictDefbox *defbox, GtkClipboard *clipboard)
void gdict_defbox_clear (GdictDefbox *defbox)
void gdict_defbox_lookup (GdictDefbox *defbox, const gchar *word)
gint gdict_defbox_count_definitions (GdictDefbox *defbox)
void gdict_defbox_jump_to_definition (GdictDefbox *defbox, gint number)
void gdict_defbox_set_show_find (GdictDefbox *defbox, gboolean show_find)
gboolean gdict_defbox_get_show_find (GdictDefbox *defbox)
void gdict_defbox_find_next (GdictDefbox *defbox)
void gdict_defbox_find_previous (GdictDefbox *defbox)
void gdict_defbox_set_font_name (GdictDefbox *defbox, const gchar *font_name)
const gchar * gdict_defbox_get_font_name (GdictDefbox *defbox)
gchar * gdict_defbox_get_selected_word (GdictDefbox *defbox) G_GNUC_MALLOC
Macro Definition Documentation
GDICT_DEFBOX
#define GDICT_DEFBOX (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GDICT_TYPE_DEFBOX, GdictDefbox))
Definition at line 29 of file gdict-defbox.h.
GDICT_DEFBOX_CLASS
#define GDICT_DEFBOX_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GDICT_TYPE_DEFBOX, GdictDefboxClass))
Definition at line 31 of file gdict-defbox.h.
GDICT_DEFBOX_GET_CLASS
#define GDICT_DEFBOX_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GDICT_TYPE_DEFBOX, GdictDefboxClass))
Definition at line 33 of file gdict-defbox.h.
GDICT_IS_DEFBOX
#define GDICT_IS_DEFBOX (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GDICT_TYPE_DEFBOX))
Definition at line 30 of file gdict-defbox.h.
GDICT_IS_DEFBOX_CLASS
#define GDICT_IS_DEFBOX_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GDICT_TYPE_DEFBOX))
Definition at line 32 of file gdict-defbox.h.
GDICT_TYPE_DEFBOX
#define GDICT_TYPE_DEFBOX (gdict_defbox_get_type ())
Definition at line 28 of file gdict-defbox.h.
Typedef Documentation
GdictDefbox
typedef struct _GdictDefbox GdictDefbox
Definition at line 35 of file gdict-defbox.h.
GdictDefboxClass
typedef struct _GdictDefboxClass GdictDefboxClass
Definition at line 36 of file gdict-defbox.h.
GdictDefboxPrivate
typedef struct _GdictDefboxPrivate GdictDefboxPrivate
Definition at line 37 of file gdict-defbox.h.
Function Documentation
gdict_defbox_clear()
void gdict_defbox_clear (GdictDefbox * defbox)
gdict_defbox_clear: @defbox: a @GdictDefbox
Clears the buffer of @defbox
Since: 0.1
Definition at line 2584 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
Referenced by gdict_defbox_lookup(), and gdict_window_new().
gdict_defbox_copy_to_clipboard()
void gdict_defbox_copy_to_clipboard (GdictDefbox * defbox, GtkClipboard * clipboard)
gdict_defbox_copy_to_clipboard: @defbox: a GdictDefbox @clipboard: a #GtkClipboard
Copies the selected text inside @defbox into @clipboard.
Since: 0.1
Definition at line 2670 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, and _GdictDefbox::priv.
gdict_defbox_count_definitions()
gint gdict_defbox_count_definitions (GdictDefbox * defbox)
gdict_defbox_count_definitions: @defbox: a GdictDefbox
Gets the number of definitions displayed by @defbox
Return value: the number of definitions.
Since: 0.1
Definition at line 2696 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, and _GdictDefbox::priv.
Referenced by gdict_defbox_jump_to_definition().
gdict_defbox_find_next()
void gdict_defbox_find_next (GdictDefbox * defbox)
gdict_defbox_find_next: @defbox: a GdictDefbox
Emits the "find-next" signal.
Since: 0.1
Definition at line 2613 of file gdict-defbox.c.
References FIND_NEXT, and GDICT_IS_DEFBOX.
gdict_defbox_find_previous()
void gdict_defbox_find_previous (GdictDefbox * defbox)
gdict_defbox_find_previous: @defbox: a GdictDefbox
Emits the "find-previous" signal.
Since: 0.1
Definition at line 2629 of file gdict-defbox.c.
References FIND_PREVIOUS, and GDICT_IS_DEFBOX.
gdict_defbox_get_context()
GdictContext * gdict_defbox_get_context (GdictDefbox * defbox)
gdict_defbox_get_context: @defbox: a GdictDefbox
Gets the GdictContext used by @defbox.
Return value: a GdictContext.
Since: 0.1
Definition at line 1969 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
gdict_defbox_get_database()
const gchar * gdict_defbox_get_database (GdictDefbox * defbox)
gdict_defbox_get_database: @defbox: a GdictDefbox
Gets the database used by @defbox. See gdict_defbox_set_database().
Return value: the name of a database. The return string is owned by the GdictDefbox widget and should not be modified or freed.
Since: 0.1
Definition at line 2014 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
gdict_defbox_get_font_name()
const gchar * gdict_defbox_get_font_name (GdictDefbox * defbox)
gdict_defbox_get_font_name: @defbox: a GdictDefbox
Retrieves the font currently used by @defbox.
Return value: a font name. The returned string is owned by @defbox and should not be modified or freed.
Since: 0.3
Definition at line 2840 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
gdict_defbox_get_selected_word()
gchar * gdict_defbox_get_selected_word (GdictDefbox * defbox)
gdict_defbox_get_selected_word: @defbox: a GdictDefbox
Retrieves the selected word from the defbox widget
Return value: a newly allocated string containing the selected word. Use g_free() when done using it.
Since: 0.12
Definition at line 2859 of file gdict-defbox.c.
References FALSE, GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
gdict_defbox_get_show_find()
gboolean gdict_defbox_get_show_find (GdictDefbox * defbox)
gdict_defbox_get_show_find: @defbox: a GdictDefbox
Gets whether the find pane should be visible or not.
Return value: TRUE if the find pane is visible.
Since: 0.1
Definition at line 2095 of file gdict-defbox.c.
References FALSE, GDICT_IS_DEFBOX, _GdictDefbox::priv, and TRUE.
gdict_defbox_get_text()
gchar * gdict_defbox_get_text (GdictDefbox * defbox, gsize * length)
gdict_defbox_get_text: @defbox: a GdictDefbox @length: return location for the text length or NULL
Gets the full contents of @defbox.
Return value: a newly allocated string containing the text displayed by @defbox.
Since: 0.1
Definition at line 2765 of file gdict-defbox.c.
References FALSE, GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
gdict_defbox_get_type()
GType gdict_defbox_get_type (void)
gdict_defbox_get_word()
const gchar * gdict_defbox_get_word (GdictDefbox * defbox)
gdict_defbox_get_word: @defbox: a GdictDefbox
Retrieves the word being looked up.
Return value: the word looked up, or NULL. The returned string is owned by the GdictDefbox widget and should never be modified or freed.
Since: 0.12
Definition at line 2034 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
gdict_defbox_jump_to_definition()
void gdict_defbox_jump_to_definition (GdictDefbox * defbox, gint number)
gdict_defbox_jump_to_definition: @defbox: a GdictDefbox @number: the definition to jump to
Scrolls to the definition identified by @number. If @number is -1, jumps to the last definition.
Since: 0.1
Definition at line 2720 of file gdict-defbox.c.
References gdict_defbox_count_definitions(), GDICT_IS_DEFBOX, _GdictDefbox::priv, and TRUE.
gdict_defbox_lookup()
void gdict_defbox_lookup (GdictDefbox * defbox, const gchar * word)
gdict_defbox_lookup: @defbox: a GdictDefbox @word: the word to look up
Searches @word inside the dictionary sources using the GdictContext provided when creating @defbox or set using gdict_defbox_set_context().
Since: 0.1
Definition at line 2505 of file gdict-defbox.c.
References _, _gdict_show_error_dialog(), gdict_context_define_word(), gdict_defbox_clear(), GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
gdict_defbox_new()
GtkWidget * gdict_defbox_new (void)
gdict_defbox_new:
Creates a new GdictDefbox widget. Use this widget to search for a word using a GdictContext, and to show the resulting definition(s). You must set a GdictContext for this widget using gdict_defbox_set_context().
Return value: a new GdictDefbox widget.
Since: 0.1
Definition at line 1914 of file gdict-defbox.c.
References GDICT_TYPE_DEFBOX, and NULL.
gdict_defbox_new_with_context()
GtkWidget * gdict_defbox_new_with_context (GdictContext * context)
gdict_defbox_new_with_context: @context: a GdictContext
Creates a new GdictDefbox widget. Use this widget to search for a word using @context, and to show the resulting definition.
Return value: a new GdictDefbox widget.
Since: 0.1
Definition at line 1931 of file gdict-defbox.c.
References GDICT_IS_CONTEXT, GDICT_TYPE_DEFBOX, and NULL.
gdict_defbox_select_all()
void gdict_defbox_select_all (GdictDefbox * defbox)
gdict_defbox_select_all: @defbox: a GdictDefbox
Selects all the text displayed by @defbox
Since: 0.1
Definition at line 2645 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, and _GdictDefbox::priv.
gdict_defbox_set_context()
void gdict_defbox_set_context (GdictDefbox * defbox, GdictContext * context)
gdict_defbox_set_context: @defbox: a GdictDefbox @context: a GdictContext
Sets @context as the GdictContext to be used by @defbox in order to retrieve the definitions of a word.
Since: 0.1
Definition at line 1949 of file gdict-defbox.c.
References GDICT_IS_CONTEXT, GDICT_IS_DEFBOX, and NULL.
gdict_defbox_set_database()
void gdict_defbox_set_database (GdictDefbox * defbox, const gchar * database)
gdict_defbox_set_database: @defbox: a GdictDefbox @database: a database
Sets @database as the database used by the GdictContext bound to @defbox to query for word definitions.
Since: 0.1
Definition at line 1987 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, and _GdictDefbox::priv.
gdict_defbox_set_font_name()
void gdict_defbox_set_font_name (GdictDefbox * defbox, const gchar * font_name)
gdict_defbox_set_font_name: @defbox: a GdictDefbox @font_name: a font description, or NULL
Sets @font_name as the font for @defbox. It calls internally pango_font_description_from_string() and gtk_widget_modify_font().
Passing NULL for @font_name will reset any previously set font.
Since: 0.3.0
Definition at line 2801 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
gdict_defbox_set_show_find()
void gdict_defbox_set_show_find (GdictDefbox * defbox, gboolean show_find)
gdict_defbox_set_show_find: @defbox: a GdictDefbox @show_find: TRUE to show the find pane
Whether @defbox should show the find pane.
Since: 0.1
Definition at line 2051 of file gdict-defbox.c.
References FALSE, GDICT_IS_DEFBOX, and _GdictDefbox::priv.