MATE Desktop Environment: gdict-window.h File Reference
gdict-window.h File Reference
#include <gio/gio.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gtk/gtk.h>
#include <libgdict/gdict.h>
Classes
struct _GdictWindow
struct _GdictWindowClass
Macros
#define GDICT_TYPE_WINDOW (gdict_window_get_type ())
#define GDICT_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GDICT_TYPE_WINDOW, GdictWindow))
#define GDICT_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GDICT_TYPE_WINDOW))
#define GDICT_TYPE_WINDOW_ACTION (gdict_window_action_get_type ())
Typedefs
typedef struct _GdictWindow GdictWindow
typedef struct _GdictWindowClass GdictWindowClass
Enumerations
enum GdictWindowAction { GDICT_WINDOW_ACTION_LOOKUP , GDICT_WINDOW_ACTION_MATCH , GDICT_WINDOW_ACTION_CLEAR }
Functions
GType gdict_window_action_get_type (void)
GType gdict_window_get_type (void)
GtkWidget * gdict_window_new (GdictWindowAction action, GdictSourceLoader *loader, const gchar *source_name, const gchar *word)
Macro Definition Documentation
GDICT_IS_WINDOW
#define GDICT_IS_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GDICT_TYPE_WINDOW))
Definition at line 32 of file gdict-window.h.
GDICT_TYPE_WINDOW
#define GDICT_TYPE_WINDOW (gdict_window_get_type ())
Definition at line 30 of file gdict-window.h.
GDICT_TYPE_WINDOW_ACTION
#define GDICT_TYPE_WINDOW_ACTION (gdict_window_action_get_type ())
Definition at line 40 of file gdict-window.h.
GDICT_WINDOW
#define GDICT_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GDICT_TYPE_WINDOW, GdictWindow))
Definition at line 31 of file gdict-window.h.
Typedef Documentation
GdictWindow
typedef struct _GdictWindow GdictWindow
Definition at line 43 of file gdict-window.h.
GdictWindowClass
typedef struct _GdictWindowClass GdictWindowClass
Definition at line 44 of file gdict-window.h.
Enumeration Type Documentation
GdictWindowAction
enum GdictWindowAction
Enumerator
GDICT_WINDOW_ACTION_LOOKUP
GDICT_WINDOW_ACTION_MATCH
GDICT_WINDOW_ACTION_CLEAR
Definition at line 34 of file gdict-window.h.
Function Documentation
gdict_window_action_get_type()
GType gdict_window_action_get_type (void)
Definition at line 2199 of file gdict-window.c.
gdict_window_get_type()
GType gdict_window_get_type (void)
gdict_window_new()
GtkWidget * gdict_window_new (GdictWindowAction action, GdictSourceLoader * loader, const gchar * source_name, const gchar * word)
Definition at line 2119 of file gdict-window.c.
References action, _GdictWindow::defbox, _GdictWindow::entry, GDICT_DEFBOX, gdict_defbox_clear(), GDICT_IS_SOURCE_LOADER, GDICT_SIDEBAR, GDICT_SIDEBAR_SPELLER_PAGE, gdict_sidebar_view_page(), gdict_source_get_context(), gdict_source_loader_get_source(), GDICT_SPELLER, gdict_speller_match(), gdict_speller_set_context(), gdict_speller_set_strategy(), GDICT_TYPE_WINDOW, GDICT_WINDOW, GDICT_WINDOW_ACTION_CLEAR, GDICT_WINDOW_ACTION_LOOKUP, GDICT_WINDOW_ACTION_MATCH, _GdictWindow::loader, NULL, _GdictWindow::sidebar, _GdictWindow::source_name, _GdictWindow::speller, _GdictWindow::strategy, and TRUE.