MATE Desktop Environment: gdict-client-context.h File Reference
gdict-client-context.h File Reference
#include "gdict-context.h"
Classes
struct _GdictClientContext
struct _GdictClientContextClass
Macros
#define GDICT_TYPE_CLIENT_CONTEXT (gdict_client_context_get_type ())
#define GDICT_CLIENT_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GDICT_TYPE_CLIENT_CONTEXT, GdictClientContext))
#define GDICT_IS_CLIENT_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GDICT_TYPE_CLIENT_CONTEXT))
#define GDICT_CLIENT_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GDICT_TYPE_CLIENT_CONTEXT, GdictClientContextClass))
#define GDICT_CLIENT_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GDICT_TYPE_CLIENT_CONTEXT, GdictClientContextClass))
#define GDICT_CLIENT_CONTEXT_ERROR (gdict_client_context_error_quark ())
Typedefs
typedef struct _GdictClientContext GdictClientContext
typedef struct _GdictClientContextClass GdictClientContextClass
typedef struct _GdictClientContextPrivate GdictClientContextPrivate
Enumerations
enum GdictClientContextError { GDICT_CLIENT_CONTEXT_ERROR_SOCKET , GDICT_CLIENT_CONTEXT_ERROR_LOOKUP , GDICT_CLIENT_CONTEXT_ERROR_NO_CONNECTION , GDICT_CLIENT_CONTEXT_ERROR_SERVER_DOWN }
Functions
GQuark gdict_client_context_error_quark (void)
GType gdict_client_context_get_type (void)
GdictContext * gdict_client_context_new (const gchar *hostname, gint port)
void gdict_client_context_set_hostname (GdictClientContext *context, const gchar *hostname)
const gchar * gdict_client_context_get_hostname (GdictClientContext *context)
void gdict_client_context_set_port (GdictClientContext *context, gint port)
guint gdict_client_context_get_port (GdictClientContext *context)
void gdict_client_context_set_client (GdictClientContext *context, const gchar *client)
const gchar * gdict_client_context_get_client (GdictClientContext *context)
Macro Definition Documentation
GDICT_CLIENT_CONTEXT
#define GDICT_CLIENT_CONTEXT (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GDICT_TYPE_CLIENT_CONTEXT, GdictClientContext))
Definition at line 26 of file gdict-client-context.h.
GDICT_CLIENT_CONTEXT_CLASS
#define GDICT_CLIENT_CONTEXT_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GDICT_TYPE_CLIENT_CONTEXT, GdictClientContextClass))
Definition at line 28 of file gdict-client-context.h.
GDICT_CLIENT_CONTEXT_ERROR
#define GDICT_CLIENT_CONTEXT_ERROR (gdict_client_context_error_quark ())
Definition at line 35 of file gdict-client-context.h.
GDICT_CLIENT_CONTEXT_GET_CLASS
#define GDICT_CLIENT_CONTEXT_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GDICT_TYPE_CLIENT_CONTEXT, GdictClientContextClass))
Definition at line 29 of file gdict-client-context.h.
GDICT_IS_CLIENT_CONTEXT
#define GDICT_IS_CLIENT_CONTEXT (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GDICT_TYPE_CLIENT_CONTEXT))
Definition at line 27 of file gdict-client-context.h.
GDICT_TYPE_CLIENT_CONTEXT
#define GDICT_TYPE_CLIENT_CONTEXT (gdict_client_context_get_type ())
Definition at line 25 of file gdict-client-context.h.
Typedef Documentation
GdictClientContext
typedef struct _GdictClientContext GdictClientContext
Definition at line 31 of file gdict-client-context.h.
GdictClientContextClass
typedef struct _GdictClientContextClass GdictClientContextClass
Definition at line 32 of file gdict-client-context.h.
GdictClientContextPrivate
typedef struct _GdictClientContextPrivate GdictClientContextPrivate
Definition at line 33 of file gdict-client-context.h.
Enumeration Type Documentation
GdictClientContextError
enum GdictClientContextError
GdictClientContextError: @GDICT_CLIENT_CONTEXT_ERROR_SOCKET: @GDICT_CLIENT_CONTEXT_ERROR_LOOKUP: @GDICT_CLIENT_CONTEXT_ERROR_NO_CONNECTION: @GDICT_CLIENT_CONTEXT_ERROR_SERVER_DOWN:
GdictClientContext error enumeration
Enumerator
GDICT_CLIENT_CONTEXT_ERROR_SOCKET
GDICT_CLIENT_CONTEXT_ERROR_LOOKUP
GDICT_CLIENT_CONTEXT_ERROR_NO_CONNECTION
GDICT_CLIENT_CONTEXT_ERROR_SERVER_DOWN
Definition at line 46 of file gdict-client-context.h.
Function Documentation
gdict_client_context_error_quark()
GQuark gdict_client_context_error_quark (void)
Definition at line 243 of file gdict-client-context.c.
gdict_client_context_get_client()
const gchar * gdict_client_context_get_client (GdictClientContext * context)
gdict_client_context_get_client: @context: a GdictClientContext
Gets the client name used by @context. See gdict_client_context_set_client().
Return value: the client name. The returned string is owned by the GdictClientContext object and should never be modified or freed.
Definition at line 627 of file gdict-client-context.c.
References GDICT_IS_CLIENT_CONTEXT, and NULL.
gdict_client_context_get_hostname()
const gchar * gdict_client_context_get_hostname (GdictClientContext * context)
gdict_client_context_get_hostname: @context: a GdictClientContext
Gets the hostname of the dictionary server used by @context.
Return value: the hostname of a dictionary server. The returned string is owned by the GdictClientContext object and should never be modified or freed.
Definition at line 546 of file gdict-client-context.c.
References GDICT_IS_CLIENT_CONTEXT, and NULL.
Referenced by gdict_source_set_transportv().
gdict_client_context_get_port()
guint gdict_client_context_get_port (GdictClientContext * context)
gdict_client_context_get_port: @context: a GdictClientContext
Gets the port of the dictionary server used by @context.
Return value: the number of the port.
Definition at line 586 of file gdict-client-context.c.
References GDICT_IS_CLIENT_CONTEXT, and NULL.
Referenced by gdict_source_set_transportv().
gdict_client_context_get_type()
GType gdict_client_context_get_type (void)
gdict_client_context_new()
GdictContext * gdict_client_context_new (const gchar * hostname, gint port)
gdict_client_context_new: @hostname: the hostname of a dictionary server, or NULL for the default server @port: port to be used when connecting to the dictionary server, or -1 for the default port
Creates a new GdictClientContext object for @hostname. Use this object to connect and query the dictionary server using the Dictionary Protocol as defined by RFC 2229.
Return value: the newly created GdictClientContext object. You should free it using g_object_unref().
Definition at line 506 of file gdict-client-context.c.
References GDICT_DEFAULT_CLIENT, GDICT_DEFAULT_HOSTNAME, GDICT_DEFAULT_PORT, GDICT_TYPE_CLIENT_CONTEXT, and NULL.
Referenced by gdict_source_set_transportv().
gdict_client_context_set_client()
void gdict_client_context_set_client (GdictClientContext * context, const gchar * client)
gdict_client_context_set_client: @context: a GdictClientContext @client: the client name to use, or NULL
Sets @client as the client name to be used when advertising ourselves when a connection the the dictionary server has been established. If @client is NULL, the default client name will be used.
Definition at line 607 of file gdict-client-context.c.
References GDICT_DEFAULT_CLIENT, GDICT_IS_CLIENT_CONTEXT, and NULL.
gdict_client_context_set_hostname()
void gdict_client_context_set_hostname (GdictClientContext * context, const gchar * hostname)
gdict_client_context_set_hostname: @context: a GdictClientContext @hostname: the hostname of a Dictionary server, or NULL
Sets @hostname as the hostname of the dictionary server to be used. If @hostname is NULL, the default dictionary server will be used.
Definition at line 525 of file gdict-client-context.c.
References GDICT_DEFAULT_HOSTNAME, GDICT_IS_CLIENT_CONTEXT, and NULL.
gdict_client_context_set_port()
void gdict_client_context_set_port (GdictClientContext * context, gint port)
gdict_client_context_set_port: @context: a GdictClientContext @port: port of the dictionary server to be used, or -1
Sets the port of the dictionary server to be used when connecting.
If @port is -1, the default port will be used.
Definition at line 567 of file gdict-client-context.c.
References GDICT_DEFAULT_PORT, GDICT_IS_CLIENT_CONTEXT, and NULL.