MATE Desktop Environment: gdict-database-chooser.h File Reference
gdict-database-chooser.h File Reference
#include <gtk/gtk.h>
#include "gdict-context.h"
Classes
struct _GdictDatabaseChooser
struct _GdictDatabaseChooserClass
Macros
#define GDICT_TYPE_DATABASE_CHOOSER (gdict_database_chooser_get_type ())
#define GDICT_DATABASE_CHOOSER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GDICT_TYPE_DATABASE_CHOOSER, GdictDatabaseChooser))
#define GDICT_IS_DATABASE_CHOOSER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GDICT_TYPE_DATABASE_CHOOSER))
#define GDICT_DATABASE_CHOOSER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GDICT_TYPE_DATABASE_CHOOSER, GdictDatabaseChooserClass))
#define GDICT_IS_DATABASE_CHOOSER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GDICT_TYPE_DATABASE_CHOOSER))
#define GDICT_DATABASE_CHOOSER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GDICT_TYPE_DATABASE_CHOOSER, GdictDatabaseChooserClass))
Typedefs
typedef struct _GdictDatabaseChooser GdictDatabaseChooser
typedef struct _GdictDatabaseChooserPrivate GdictDatabaseChooserPrivate
typedef struct _GdictDatabaseChooserClass GdictDatabaseChooserClass
Functions
GType gdict_database_chooser_get_type (void)
GtkWidget * gdict_database_chooser_new (void)
GtkWidget * gdict_database_chooser_new_with_context (GdictContext *context)
GdictContext * gdict_database_chooser_get_context (GdictDatabaseChooser *chooser)
void gdict_database_chooser_set_context (GdictDatabaseChooser *chooser, GdictContext *context)
gboolean gdict_database_chooser_select_database (GdictDatabaseChooser *chooser, const gchar *db_name)
gboolean gdict_database_chooser_unselect_database (GdictDatabaseChooser *chooser, const gchar *db_name)
gboolean gdict_database_chooser_set_current_database (GdictDatabaseChooser *chooser, const gchar *db_name)
gchar * gdict_database_chooser_get_current_database (GdictDatabaseChooser *chooser) G_GNUC_MALLOC
gchar ** gdict_database_chooser_get_databases (GdictDatabaseChooser *chooser, gsize *length) G_GNUC_MALLOC
gint gdict_database_chooser_count_databases (GdictDatabaseChooser *chooser)
gboolean gdict_database_chooser_has_database (GdictDatabaseChooser *chooser, const gchar *database)
void gdict_database_chooser_refresh (GdictDatabaseChooser *chooser)
void gdict_database_chooser_clear (GdictDatabaseChooser *chooser)
GtkWidget * gdict_database_chooser_add_button (GdictDatabaseChooser *chooser, const gchar *button_text)
Macro Definition Documentation
GDICT_DATABASE_CHOOSER
#define GDICT_DATABASE_CHOOSER (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GDICT_TYPE_DATABASE_CHOOSER, GdictDatabaseChooser))
Definition at line 29 of file gdict-database-chooser.h.
GDICT_DATABASE_CHOOSER_CLASS
#define GDICT_DATABASE_CHOOSER_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GDICT_TYPE_DATABASE_CHOOSER, GdictDatabaseChooserClass))
Definition at line 33 of file gdict-database-chooser.h.
GDICT_DATABASE_CHOOSER_GET_CLASS
#define GDICT_DATABASE_CHOOSER_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GDICT_TYPE_DATABASE_CHOOSER, GdictDatabaseChooserClass))
Definition at line 37 of file gdict-database-chooser.h.
GDICT_IS_DATABASE_CHOOSER
#define GDICT_IS_DATABASE_CHOOSER (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GDICT_TYPE_DATABASE_CHOOSER))
Definition at line 31 of file gdict-database-chooser.h.
GDICT_IS_DATABASE_CHOOSER_CLASS
#define GDICT_IS_DATABASE_CHOOSER_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GDICT_TYPE_DATABASE_CHOOSER))
Definition at line 35 of file gdict-database-chooser.h.
GDICT_TYPE_DATABASE_CHOOSER
#define GDICT_TYPE_DATABASE_CHOOSER (gdict_database_chooser_get_type ())
Definition at line 28 of file gdict-database-chooser.h.
Typedef Documentation
GdictDatabaseChooser
typedef struct _GdictDatabaseChooser GdictDatabaseChooser
Definition at line 40 of file gdict-database-chooser.h.
GdictDatabaseChooserClass
typedef struct _GdictDatabaseChooserClass GdictDatabaseChooserClass
Definition at line 42 of file gdict-database-chooser.h.
GdictDatabaseChooserPrivate
typedef struct _GdictDatabaseChooserPrivate GdictDatabaseChooserPrivate
Definition at line 41 of file gdict-database-chooser.h.
Function Documentation
gdict_database_chooser_add_button()
GtkWidget * gdict_database_chooser_add_button (GdictDatabaseChooser * chooser, const gchar * button_text)
gdict_database_chooser_add_button: @chooser: a GdictDatabase @button_text: text of the button
Adds a #GtkButton with @button_text to the button area on the bottom of @chooser. The @button_text can also be a stock ID.
Return value: the newly packed button.
Since: 0.10
Definition at line 1116 of file gdict-database-chooser.c.
References FALSE, GDICT_IS_DATABASE_CHOOSER, NULL, _GdictDatabaseChooser::priv, and TRUE.
gdict_database_chooser_clear()
void gdict_database_chooser_clear (GdictDatabaseChooser * chooser)
gdict_database_chooser_clear: @chooser: a GdictDatabaseChooser
Clears @chooser.
Since: 0.10
Definition at line 855 of file gdict-database-chooser.c.
References GDICT_IS_DATABASE_CHOOSER, NULL, and _GdictDatabaseChooser::priv.
Referenced by gdict_database_chooser_refresh().
gdict_database_chooser_count_databases()
gint gdict_database_chooser_count_databases (GdictDatabaseChooser * chooser)
gdict_database_chooser_count_databases: @chooser: a GdictDatabaseChooser
Returns the number of databases found.
Return value: the number of databases or -1 if no context is set
Since: 0.10
Definition at line 691 of file gdict-database-chooser.c.
References GDICT_IS_DATABASE_CHOOSER, and _GdictDatabaseChooser::priv.
gdict_database_chooser_get_context()
GdictContext * gdict_database_chooser_get_context (GdictDatabaseChooser * chooser)
gdict_database_chooser_get_context: @chooser: a GdictDatabaseChooser
Retrieves the GdictContext used by @chooser.
Return value: a GdictContext or NULL
Since: 0.10
Definition at line 549 of file gdict-database-chooser.c.
References GDICT_IS_DATABASE_CHOOSER, NULL, and _GdictDatabaseChooser::priv.
gdict_database_chooser_get_current_database()
gchar * gdict_database_chooser_get_current_database (GdictDatabaseChooser * chooser)
gdict_database_chooser_get_current_database: @chooser: a GdictDatabaseChooser
Retrieves the name of the currently selected database inside @chooser
Return value: the name of the selected database. Use g_free() on the returned string when done using it
Since: 0.10
Definition at line 1078 of file gdict-database-chooser.c.
References DB_COLUMN_NAME, GDICT_IS_DATABASE_CHOOSER, NULL, and _GdictDatabaseChooser::priv.
gdict_database_chooser_get_databases()
gchar ** gdict_database_chooser_get_databases (GdictDatabaseChooser * chooser, gsize * length)
gdict_database_chooser_get_databases: @chooser: a GdictDatabaseChooser @length: return location for the length of the returned vector
Gets the list of available database names.
Return value: a newly allocated, NULL terminated string vector containing database names. Use g_strfreev() to deallocate it.
Since: 0.10
Definition at line 591 of file gdict-database-chooser.c.
References DB_COLUMN_NAME, GDICT_IS_DATABASE_CHOOSER, NULL, and _GdictDatabaseChooser::priv.
gdict_database_chooser_get_type()
GType gdict_database_chooser_get_type (void)
gdict_database_chooser_has_database()
gboolean gdict_database_chooser_has_database (GdictDatabaseChooser * chooser, const gchar * database)
gdict_database_chooser_has_database: @chooser: a GdictDatabaseChooser @database: the name of a database
Checks whether the @chooser displays @database
Return value: TRUE if the search database name is present
Since: 0.10
Definition at line 641 of file gdict-database-chooser.c.
References DB_COLUMN_NAME, FALSE, GDICT_IS_DATABASE_CHOOSER, NULL, _GdictDatabaseChooser::priv, and TRUE.
gdict_database_chooser_new()
GtkWidget * gdict_database_chooser_new (void)
gdict_database_chooser_new:
Creates a new GdictDatabaseChooser widget. A Database chooser widget can be used to display the list of available databases on a dictionary source using the GdictContext representing it. After creation, the GdictContext can be set using gdict_database_chooser_set_context().
Return value: the newly created GdictDatabaseChooser widget.
Since: 0.10
Definition at line 512 of file gdict-database-chooser.c.
References GDICT_TYPE_DATABASE_CHOOSER, and NULL.
gdict_database_chooser_new_with_context()
GtkWidget * gdict_database_chooser_new_with_context (GdictContext * context)
gdict_database_chooser_new_with_context: @context: a GdictContext
Creates a new GdictDatabaseChooser, using @context as the representation of the dictionary source to query for the list of available databases.
Return value: the newly created GdictDatabaseChooser widget.
Since: 0.10
Definition at line 529 of file gdict-database-chooser.c.
References GDICT_IS_CONTEXT, GDICT_TYPE_DATABASE_CHOOSER, and NULL.
gdict_database_chooser_refresh()
void gdict_database_chooser_refresh (GdictDatabaseChooser * chooser)
gdict_database_chooser_refresh: @chooser: a GdictDatabaseChooser
Reloads the list of available databases.
Since: 0.10
Definition at line 786 of file gdict-database-chooser.c.
References _, DATABASE_ERROR, DB_COLUMN_DESCRIPTION, DB_COLUMN_NAME, DB_COLUMN_TYPE, gdict_context_lookup_databases(), gdict_database_chooser_clear(), GDICT_IS_DATABASE_CHOOSER, NULL, and _GdictDatabaseChooser::priv.
gdict_database_chooser_select_database()
gboolean gdict_database_chooser_select_database (GdictDatabaseChooser * chooser, const gchar * db_name)
gdict_database_chooser_select_database: @chooser: a GdictDatabaseChooser @db_name: name of the database to select
Selects the database with @db_name inside the @chooser widget.
Return value: TRUE if the database was found and selected
Since: 0.10
Definition at line 948 of file gdict-database-chooser.c.
References data, FALSE, GDICT_IS_DATABASE_CHOOSER, NULL, _GdictDatabaseChooser::priv, and TRUE.
gdict_database_chooser_set_context()
void gdict_database_chooser_set_context (GdictDatabaseChooser * chooser, GdictContext * context)
gdict_database_chooser_set_context: @chooser: a GdictDatabaseChooser @context: a GdictContext
Sets the GdictContext to be used to query a dictionary source for the list of available databases.
Since: 0.10
Definition at line 567 of file gdict-database-chooser.c.
References GDICT_IS_CONTEXT, GDICT_IS_DATABASE_CHOOSER, and NULL.
gdict_database_chooser_set_current_database()
gboolean gdict_database_chooser_set_current_database (GdictDatabaseChooser * chooser, const gchar * db_name)
gdict_database_chooser_set_current_database: @chooser: a GdictDatabaseChooser @db_name: the name of the database
Sets @db_name as the current database. This function will select and activate the corresponding row, if the database is found.
Return value: TRUE if the database was found and set
Since: 0.10
Definition at line 1031 of file gdict-database-chooser.c.
References data, FALSE, GDICT_IS_DATABASE_CHOOSER, NULL, _GdictDatabaseChooser::priv, and TRUE.
gdict_database_chooser_unselect_database()
gboolean gdict_database_chooser_unselect_database (GdictDatabaseChooser * chooser, const gchar * db_name)
gdict_database_chooser_unselect_database: @chooser: a GdictDatabaseChooser @db_name: name of the database to unselect
Unselects the database @db_name inside the @chooser widget
Return value: TRUE if the database was found and unselected
Since: 0.10
Definition at line 989 of file gdict-database-chooser.c.
References data, FALSE, GDICT_IS_DATABASE_CHOOSER, NULL, and _GdictDatabaseChooser::priv.