MATE Desktop Environment: gdict-strategy-chooser.h File Reference
gdict-strategy-chooser.h File Reference
#include <gtk/gtk.h>
#include "gdict-context.h"
Classes
struct _GdictStrategyChooser
struct _GdictStrategyChooserClass
Macros
#define GDICT_TYPE_STRATEGY_CHOOSER (gdict_strategy_chooser_get_type ())
#define GDICT_STRATEGY_CHOOSER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GDICT_TYPE_STRATEGY_CHOOSER, GdictStrategyChooser))
#define GDICT_IS_STRATEGY_CHOOSER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GDICT_TYPE_STRATEGY_CHOOSER))
#define GDICT_STRATEGY_CHOOSER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GDICT_TYPE_STRATEGY_CHOOSER, GdictStrategyChooserClass))
#define GDICT_IS_STRATEGY_CHOOSER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GDICT_TYPE_STRATEGY_CHOOSER))
#define GDICT_STRATEGY_CHOOSER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GDICT_TYPE_STRATEGY_CHOOSER, GdictStrategyChooserClass))
Typedefs
typedef struct _GdictStrategyChooser GdictStrategyChooser
typedef struct _GdictStrategyChooserPrivate GdictStrategyChooserPrivate
typedef struct _GdictStrategyChooserClass GdictStrategyChooserClass
Functions
GType gdict_strategy_chooser_get_type (void)
GtkWidget * gdict_strategy_chooser_new (void)
GtkWidget * gdict_strategy_chooser_new_with_context (GdictContext *context)
GdictContext * gdict_strategy_chooser_get_context (GdictStrategyChooser *chooser)
void gdict_strategy_chooser_set_context (GdictStrategyChooser *chooser, GdictContext *context)
gboolean gdict_strategy_chooser_select_strategy (GdictStrategyChooser *chooser, const gchar *strat_name)
gboolean gdict_strategy_chooser_unselect_strategy (GdictStrategyChooser *chooser, const gchar *strat_name)
gboolean gdict_strategy_chooser_set_current_strategy (GdictStrategyChooser *chooser, const gchar *strat_name)
gchar * gdict_strategy_chooser_get_current_strategy (GdictStrategyChooser *chooser) G_GNUC_MALLOC
gchar ** gdict_strategy_chooser_get_strategies (GdictStrategyChooser *chooser, gsize *length) G_GNUC_MALLOC
gint gdict_strategy_chooser_count_strategies (GdictStrategyChooser *chooser)
gboolean gdict_strategy_chooser_has_strategy (GdictStrategyChooser *chooser, const gchar *strategy)
void gdict_strategy_chooser_refresh (GdictStrategyChooser *chooser)
void gdict_strategy_chooser_clear (GdictStrategyChooser *chooser)
GtkWidget * gdict_strategy_chooser_add_button (GdictStrategyChooser *chooser, const gchar *button_text)
Macro Definition Documentation
GDICT_IS_STRATEGY_CHOOSER
#define GDICT_IS_STRATEGY_CHOOSER (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GDICT_TYPE_STRATEGY_CHOOSER))
Definition at line 30 of file gdict-strategy-chooser.h.
GDICT_IS_STRATEGY_CHOOSER_CLASS
#define GDICT_IS_STRATEGY_CHOOSER_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GDICT_TYPE_STRATEGY_CHOOSER))
Definition at line 34 of file gdict-strategy-chooser.h.
GDICT_STRATEGY_CHOOSER
#define GDICT_STRATEGY_CHOOSER (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GDICT_TYPE_STRATEGY_CHOOSER, GdictStrategyChooser))
Definition at line 28 of file gdict-strategy-chooser.h.
GDICT_STRATEGY_CHOOSER_CLASS
#define GDICT_STRATEGY_CHOOSER_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GDICT_TYPE_STRATEGY_CHOOSER, GdictStrategyChooserClass))
Definition at line 32 of file gdict-strategy-chooser.h.
GDICT_STRATEGY_CHOOSER_GET_CLASS
#define GDICT_STRATEGY_CHOOSER_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GDICT_TYPE_STRATEGY_CHOOSER, GdictStrategyChooserClass))
Definition at line 36 of file gdict-strategy-chooser.h.
GDICT_TYPE_STRATEGY_CHOOSER
#define GDICT_TYPE_STRATEGY_CHOOSER (gdict_strategy_chooser_get_type ())
Definition at line 27 of file gdict-strategy-chooser.h.
Typedef Documentation
GdictStrategyChooser
typedef struct _GdictStrategyChooser GdictStrategyChooser
Definition at line 39 of file gdict-strategy-chooser.h.
GdictStrategyChooserClass
typedef struct _GdictStrategyChooserClass GdictStrategyChooserClass
Definition at line 41 of file gdict-strategy-chooser.h.
GdictStrategyChooserPrivate
typedef struct _GdictStrategyChooserPrivate GdictStrategyChooserPrivate
Definition at line 40 of file gdict-strategy-chooser.h.
Function Documentation
gdict_strategy_chooser_add_button()
GtkWidget * gdict_strategy_chooser_add_button (GdictStrategyChooser * chooser, const gchar * button_text)
gdict_strategy_chooser_add_button: @chooser: a GdictStrategyChooser @button_text: text of the button (can be a stock id)
Creates a new button and packs it into the GdictStrategyChooser "action area".
Return value: the packed #GtkButton
Since: 0.10
Definition at line 1066 of file gdict-strategy-chooser.c.
References FALSE, GDICT_IS_STRATEGY_CHOOSER, NULL, _GdictStrategyChooser::priv, and TRUE.
gdict_strategy_chooser_clear()
void gdict_strategy_chooser_clear (GdictStrategyChooser * chooser)
gdict_strategy_chooser_clear: @chooser: a GdictStrategyChooser
Clears @chooser.
Since: 0.10
Definition at line 803 of file gdict-strategy-chooser.c.
References GDICT_IS_STRATEGY_CHOOSER, NULL, and _GdictStrategyChooser::priv.
Referenced by gdict_strategy_chooser_refresh().
gdict_strategy_chooser_count_strategies()
gint gdict_strategy_chooser_count_strategies (GdictStrategyChooser * chooser)
gdict_strategy_chooser_count_strategies: @chooser: a GdictStrategyChooser
Returns the number of strategies found.
Return value: the number of strategies or -1 if case of error
Since:
Definition at line 640 of file gdict-strategy-chooser.c.
References GDICT_IS_STRATEGY_CHOOSER, and _GdictStrategyChooser::priv.
gdict_strategy_chooser_get_context()
GdictContext * gdict_strategy_chooser_get_context (GdictStrategyChooser * chooser)
gdict_strategy_chooser_get_context: @chooser: a GdictStrategyChooser
Retrieves the GdictContext used by @chooser.
Return value: a GdictContext
Since:
Definition at line 497 of file gdict-strategy-chooser.c.
References GDICT_IS_STRATEGY_CHOOSER, NULL, and _GdictStrategyChooser::priv.
gdict_strategy_chooser_get_current_strategy()
gchar * gdict_strategy_chooser_get_current_strategy (GdictStrategyChooser * chooser)
gdict_strategy_chooser_get_current_strategy: @chooser: a GdictStrategyChooser
Retrieves the current matching strategy.
Return value: a newly allocated string containing the name of the current matching strategy
Since: 0.10
Definition at line 1029 of file gdict-strategy-chooser.c.
References GDICT_IS_STRATEGY_CHOOSER, NULL, _GdictStrategyChooser::priv, and STRAT_COLUMN_NAME.
gdict_strategy_chooser_get_strategies()
gchar ** gdict_strategy_chooser_get_strategies (GdictStrategyChooser * chooser, gsize * length)
gdict_strategy_chooser_get_strategies: @chooser: a GdictStrategyChooser @length: return location for the length of the returned string list
Retrieves the list of matching strategies available.
Return value: a string vector containing the names of the matching strategies. Use g_strfreev() to deallocate the memory when done
Since:0.9
Definition at line 539 of file gdict-strategy-chooser.c.
References GDICT_IS_STRATEGY_CHOOSER, NULL, _GdictStrategyChooser::priv, and STRAT_COLUMN_NAME.
gdict_strategy_chooser_get_type()
GType gdict_strategy_chooser_get_type (void)
gdict_strategy_chooser_has_strategy()
gboolean gdict_strategy_chooser_has_strategy (GdictStrategyChooser * chooser, const gchar * strategy)
gdict_strategy_chooser_has_strategy: @chooser: a GdictStrategyChooser @strategy: a strategy name
Checks whether @strategy is available in the list of matching strategies displayed by @chooser.
Return value: TRUE if the strategy was found, FALSE otherwise
Since: 0.9
Definition at line 590 of file gdict-strategy-chooser.c.
References FALSE, GDICT_IS_STRATEGY_CHOOSER, NULL, _GdictStrategyChooser::priv, STRAT_COLUMN_NAME, and TRUE.
gdict_strategy_chooser_new()
GtkWidget * gdict_strategy_chooser_new (void)
gdict_strategy_chooser_new:
Creates a new GdictStrategyChooser. Use this widget to show a list of matching strategies available on a dictionary source represented by a GdictContext, set with gdict_strategy_chooser_set_context().
Return value: the newly created GdictStrategyChooser widget
Since: 0.9
Definition at line 460 of file gdict-strategy-chooser.c.
References GDICT_TYPE_STRATEGY_CHOOSER, and NULL.
gdict_strategy_chooser_new_with_context()
GtkWidget * gdict_strategy_chooser_new_with_context (GdictContext * context)
gdict_strategy_chooser_new_with_context: @context: a GdictContext
Creates a new GdictStrategyChooser widget, using @context as the representation of a dictionary source.
Return value: the newly created GdictStrategyChooser widget
Since: 0.9
Definition at line 477 of file gdict-strategy-chooser.c.
References GDICT_IS_CONTEXT, GDICT_TYPE_STRATEGY_CHOOSER, and NULL.
gdict_strategy_chooser_refresh()
void gdict_strategy_chooser_refresh (GdictStrategyChooser * chooser)
gdict_strategy_chooser_refresh: @chooser: a GdictStrategyChooser
Reloads the list of available strategies.
Since: 0.10
Definition at line 734 of file gdict-strategy-chooser.c.
References _, gdict_context_lookup_strategies(), GDICT_IS_STRATEGY_CHOOSER, gdict_strategy_chooser_clear(), NULL, _GdictStrategyChooser::priv, STRAT_COLUMN_DESCRIPTION, STRAT_COLUMN_NAME, STRAT_COLUMN_TYPE, and STRATEGY_ERROR.
gdict_strategy_chooser_select_strategy()
gboolean gdict_strategy_chooser_select_strategy (GdictStrategyChooser * chooser, const gchar * strat_name)
gdict_strategy_chooser_select_strategy: @chooser: a GdictStrategyChooser @strat_name: the name of the strategy to select
Selects @strat_name, if available.
Return value: TRUE if the matching strategy was found and selected
Since: 0.10
Definition at line 896 of file gdict-strategy-chooser.c.
References data, FALSE, GDICT_IS_STRATEGY_CHOOSER, NULL, _GdictStrategyChooser::priv, and TRUE.
gdict_strategy_chooser_set_context()
void gdict_strategy_chooser_set_context (GdictStrategyChooser * chooser, GdictContext * context)
gdict_strategy_chooser_set_context: @chooser: a GdictStrategyChooser @context: a GdictContext, or NULL to unset the context
Sets the GdictContext to be used by @chooser to retrieve the list of matching strategies.
Since: 0.9
Definition at line 515 of file gdict-strategy-chooser.c.
References GDICT_IS_CONTEXT, GDICT_IS_STRATEGY_CHOOSER, and NULL.
gdict_strategy_chooser_set_current_strategy()
gboolean gdict_strategy_chooser_set_current_strategy (GdictStrategyChooser * chooser, const gchar * strat_name)
gdict_strategy_chooser_set_current_strategy: @chooser: a GdictStrategyChooser @strat_name: the name of the matching strategy
Sets @strat_name as the current matching strategy.
Return value: TRUE if the matching strategy was found
Since: 0.10
Definition at line 979 of file gdict-strategy-chooser.c.
References data, FALSE, GDICT_IS_STRATEGY_CHOOSER, NULL, _GdictStrategyChooser::priv, and TRUE.
gdict_strategy_chooser_unselect_strategy()
gboolean gdict_strategy_chooser_unselect_strategy (GdictStrategyChooser * chooser, const gchar * strat_name)
gdict_strategy_chooser_unselect_strategy: @chooser: a GdictStrategyChooser @strat_name: the name of the strategy to unselect
Unselects @strat_name from the list.
Return value: TRUE if the matching strategy was found and successfully unselected
Since: 0.10
Definition at line 938 of file gdict-strategy-chooser.c.
References data, FALSE, GDICT_IS_STRATEGY_CHOOSER, NULL, and _GdictStrategyChooser::priv.