MATE Desktop Environment: gdict-window.c File Reference
gdict-window.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <errno.h>
#include <gtk/gtk.h>
#include <glib.h>
#include <glib/gstdio.h>
#include <glib/gi18n.h>
#include <libgdict/gdict.h>
#include "gdict-sidebar.h"
#include "gdict-print.h"
#include "gdict-pref-dialog.h"
#include "gdict-about.h"
#include "gdict-window.h"
#include "gdict-common.h"
Macros
#define GDICT_WINDOW_COLUMNS 56
#define GDICT_WINDOW_ROWS 33
#define GDICT_WINDOW_MIN_WIDTH 400
#define GDICT_WINDOW_MIN_HEIGHT 330
#define GDICT_SIDEBAR_SPELLER_PAGE "speller"
#define GDICT_SIDEBAR_DATABASES_PAGE "db-chooser"
#define GDICT_SIDEBAR_STRATEGIES_PAGE "strat-chooser"
#define GDICT_SIDEBAR_SOURCES_PAGE "source-chooser"
Enumerations
enum { COMPLETION_TEXT_COLUMN , COMPLETION_N_COLUMNS }
enum {
PROP_0 , PROP_ACTION , PROP_SOURCE_LOADER , PROP_SOURCE_NAME ,
PROP_DATABASE , PROP_STRATEGY , PROP_PRINT_FONT , PROP_DEFBOX_FONT ,
PROP_WORD , PROP_WINDOW_ID , LAST_PROP
}
enum { CREATED , LAST_SIGNAL }
Functions
G_DEFINE_TYPE (GdictWindow, gdict_window, GTK_TYPE_WINDOW)
GtkWidget * gdict_window_new (GdictWindowAction action, GdictSourceLoader *loader, const gchar *source_name, const gchar *word)
GType gdict_window_action_get_type (void)
Macro Definition Documentation
GDICT_SIDEBAR_DATABASES_PAGE
#define GDICT_SIDEBAR_DATABASES_PAGE "db-chooser"
Definition at line 52 of file gdict-window.c.
GDICT_SIDEBAR_SOURCES_PAGE
#define GDICT_SIDEBAR_SOURCES_PAGE "source-chooser"
Definition at line 54 of file gdict-window.c.
GDICT_SIDEBAR_SPELLER_PAGE
#define GDICT_SIDEBAR_SPELLER_PAGE "speller"
Definition at line 51 of file gdict-window.c.
GDICT_SIDEBAR_STRATEGIES_PAGE
#define GDICT_SIDEBAR_STRATEGIES_PAGE "strat-chooser"
Definition at line 53 of file gdict-window.c.
GDICT_WINDOW_COLUMNS
#define GDICT_WINDOW_COLUMNS 56
Definition at line 44 of file gdict-window.c.
GDICT_WINDOW_MIN_HEIGHT
#define GDICT_WINDOW_MIN_HEIGHT 330
Definition at line 48 of file gdict-window.c.
GDICT_WINDOW_MIN_WIDTH
#define GDICT_WINDOW_MIN_WIDTH 400
Definition at line 47 of file gdict-window.c.
GDICT_WINDOW_ROWS
#define GDICT_WINDOW_ROWS 33
Definition at line 45 of file gdict-window.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COMPLETION_TEXT_COLUMN
COMPLETION_N_COLUMNS
Definition at line 56 of file gdict-window.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_ACTION
PROP_SOURCE_LOADER
PROP_SOURCE_NAME
PROP_DATABASE
PROP_STRATEGY
PROP_PRINT_FONT
PROP_DEFBOX_FONT
PROP_WORD
PROP_WINDOW_ID
LAST_PROP
Definition at line 63 of file gdict-window.c.
anonymous enum
anonymous enum
Enumerator
CREATED
LAST_SIGNAL
Definition at line 80 of file gdict-window.c.
Function Documentation
G_DEFINE_TYPE()
G_DEFINE_TYPE (GdictWindow , gdict_window , GTK_TYPE_WINDOW)
gdict_window_action_get_type()
GType gdict_window_action_get_type (void)
Definition at line 2199 of file gdict-window.c.
gdict_window_new()
GtkWidget * gdict_window_new (GdictWindowAction action, GdictSourceLoader * loader, const gchar * source_name, const gchar * word)
Definition at line 2119 of file gdict-window.c.
References action, _GdictWindow::defbox, _GdictWindow::entry, GDICT_DEFBOX, gdict_defbox_clear(), GDICT_IS_SOURCE_LOADER, GDICT_SIDEBAR, GDICT_SIDEBAR_SPELLER_PAGE, gdict_sidebar_view_page(), gdict_source_get_context(), gdict_source_loader_get_source(), GDICT_SPELLER, gdict_speller_match(), gdict_speller_set_context(), gdict_speller_set_strategy(), GDICT_TYPE_WINDOW, GDICT_WINDOW, GDICT_WINDOW_ACTION_CLEAR, GDICT_WINDOW_ACTION_LOOKUP, GDICT_WINDOW_ACTION_MATCH, _GdictWindow::loader, NULL, _GdictWindow::sidebar, _GdictWindow::source_name, _GdictWindow::speller, _GdictWindow::strategy, and TRUE.
Variable Documentation
keyval
guint keyval
Definition at line 1380 of file gdict-window.c.
modifier
GdkModifierType modifier
Definition at line 1381 of file gdict-window.c.
widget_id
const gchar* widget_id
Definition at line 1382 of file gdict-window.c.