MATE Desktop Environment: gio-utils.h File Reference
gio-utils.h File Reference
#include <glib.h>
#include <gio/gio.h>
Macros
#define g_directory_list_all_async(directory, base_dir, recursive, cancellable, done_func, done_data) g_directory_list_async ((directory), (base_dir), (recursive), TRUE, FALSE, FALSE, NULL, NULL, NULL, FALSE, (cancellable), (done_func), (done_data))
Typedefs
typedef DirOp(* StartDirCallback) (const char *uri, GError **error, gpointer user_data)
typedef void(* ForEachChildCallback) (const char *uri, gboolean follow_links, GFileInfo *info, gpointer user_data)
typedef void(* ForEachDoneCallback) (GError *error, gpointer data)
typedef void(* ListReadyCallback) (GList *files, GList *dirs, GError *error, gpointer user_data)
typedef void(* CopyProgressCallback) (goffset current_file, goffset total_files, GFile *source, GFile *destination, goffset current_num_bytes, goffset total_num_bytes, gpointer user_data)
typedef void(* CopyDoneCallback) (GError *error, gpointer user_data)
Enumerations
enum DirOp { DIR_OP_CONTINUE , DIR_OP_SKIP , DIR_OP_STOP }
Functions
void g_directory_foreach_child (GFile *directory, gboolean recursive, gboolean follow_links, GCancellable *cancellable, StartDirCallback start_dir_func, ForEachChildCallback for_each_file_func, ForEachDoneCallback done_func, gpointer user_data)
void g_directory_list_async (const char *directory, const char *base_dir, gboolean recursive, gboolean follow_links, gboolean no_backup_files, gboolean no_dot_files, const char *include_files, const char *exclude_files, const char *exclude_folders, gboolean ignorecase, GCancellable *cancellable, ListReadyCallback done_func, gpointer done_data)
void g_list_items_async (GList *items, const char *base_dir, GCancellable *cancellable, ListReadyCallback done_func, gpointer done_data)
void g_copy_files_async (GList *sources, GList *destinations, GFileCopyFlags flags, int io_priority, GCancellable *cancellable, CopyProgressCallback progress_callback, gpointer progress_callback_data, CopyDoneCallback callback, gpointer user_data)
void g_copy_file_async (GFile *source, GFile *destination, GFileCopyFlags flags, int io_priority, GCancellable *cancellable, CopyProgressCallback progress_callback, gpointer progress_callback_data, CopyDoneCallback callback, gpointer user_data)
void g_directory_copy_async (const char *source, const char *destination, GFileCopyFlags flags, int io_priority, GCancellable *cancellable, CopyProgressCallback progress_callback, gpointer progress_callback_data, CopyDoneCallback callback, gpointer user_data)
gboolean g_load_file_in_buffer (GFile *file, void *buffer, gsize size, GError **error)
Macro Definition Documentation
g_directory_list_all_async
#define g_directory_list_all_async (directory, base_dir, recursive, cancellable, done_func, done_data) g_directory_list_async ((directory), (base_dir), (recursive), TRUE, FALSE, FALSE, NULL, NULL, NULL, FALSE, (cancellable), (done_func), (done_data))
g_directory_list_all_async: @directory: @base_dir: @recursive: @cancellable: @done_func: @done_data:
Definition at line 135 of file gio-utils.h.
Typedef Documentation
CopyDoneCallback
typedef void(* CopyDoneCallback) (GError *error, gpointer user_data)
Definition at line 57 of file gio-utils.h.
CopyProgressCallback
typedef void(* CopyProgressCallback) (goffset current_file, goffset total_files, GFile *source, GFile *destination, goffset current_num_bytes, goffset total_num_bytes, gpointer user_data)
Definition at line 50 of file gio-utils.h.
ForEachChildCallback
typedef void(* ForEachChildCallback) (const char *uri, gboolean follow_links, GFileInfo *info, gpointer user_data)
Definition at line 40 of file gio-utils.h.
ForEachDoneCallback
typedef void(* ForEachDoneCallback) (GError *error, gpointer data)
Definition at line 44 of file gio-utils.h.
ListReadyCallback
typedef void(* ListReadyCallback) (GList *files, GList *dirs, GError *error, gpointer user_data)
Definition at line 46 of file gio-utils.h.
StartDirCallback
typedef DirOp(* StartDirCallback) (const char *uri, GError **error, gpointer user_data)
Definition at line 37 of file gio-utils.h.
Enumeration Type Documentation
DirOp
enum DirOp
Enumerator
DIR_OP_CONTINUE
DIR_OP_SKIP
DIR_OP_STOP
Definition at line 31 of file gio-utils.h.
Function Documentation
g_copy_file_async()
void g_copy_file_async (GFile * source, GFile * destination, GFileCopyFlags flags, int io_priority, GCancellable * cancellable, CopyProgressCallback progress_callback, gpointer progress_callback_data, CopyDoneCallback callback, gpointer user_data)
Definition at line 987 of file gio-utils.c.
References g_copy_files_async(), NULL, and user_data.
g_copy_files_async()
void g_copy_files_async (GList * sources, GList * destinations, GFileCopyFlags flags, int io_priority, GCancellable * cancellable, CopyProgressCallback progress_callback, gpointer progress_callback_data, CopyDoneCallback callback, gpointer user_data)
Definition at line 962 of file gio-utils.c.
References user_data.
Referenced by g_copy_file_async().
g_directory_copy_async()
void g_directory_copy_async (const char * source, const char * destination, GFileCopyFlags flags, int io_priority, GCancellable * cancellable, CopyProgressCallback progress_callback, gpointer progress_callback_data, CopyDoneCallback callback, gpointer user_data)
Definition at line 1322 of file gio-utils.c.
References g_directory_foreach_child(), TRUE, and user_data.
g_directory_foreach_child()
void g_directory_foreach_child (GFile * directory, gboolean recursive, gboolean follow_links, GCancellable * cancellable, StartDirCallback start_dir_func, ForEachChildCallback for_each_file_func, ForEachDoneCallback done_func, gpointer user_data)
g_directory_foreach_child: @directory: The directory to visit. @recursive: Whether to traverse the @directory recursively. @follow_links: Whether to dereference the symbolic links. @cancellable: An optional @GCancellable object, used to cancel the process. @start_dir_func: the function called for each sub-directory, or NULL if not needed. @for_each_file_func: the function called for each file. Can't be NULL. @done_func: the function called at the end of the traversing process. Can't be NULL. @user_data: data to pass to @done_func
Traverse the @directory's filesystem structure calling the @for_each_file_func function for each file in the directory; the @start_dir_func function on each directory before it's going to be traversed, this includes @directory too; the @done_func function is called at the end of the process. Some traversing options are available: if @recursive is TRUE the directory is traversed recursively; if @follow_links is TRUE, symbolic links are dereferenced, otherwise they are returned as links. Each callback uses the same @user_data additional parameter.
Definition at line 394 of file gio-utils.c.
References NULL, and user_data.
Referenced by g_directory_copy_async(), and g_directory_list_async().
g_directory_list_async()
void g_directory_list_async (const char * directory, const char * base_dir, gboolean recursive, gboolean follow_links, gboolean no_backup_files, gboolean no_dot_files, const char * include_files, const char * exclude_files, const char * exclude_folders, gboolean ignorecase, GCancellable * cancellable, ListReadyCallback done_func, gpointer done_data)
Definition at line 652 of file gio-utils.c.
References FILTER_DEFAULT, FILTER_IGNORECASE, FILTER_NOBACKUPFILES, FILTER_NODOTFILES, and g_directory_foreach_child().
Referenced by fr_archive_add_with_wildcard().
g_list_items_async()
void g_list_items_async (GList * items, const char * base_dir, GCancellable * cancellable, ListReadyCallback done_func, gpointer done_data)
Definition at line 778 of file gio-utils.c.
References NULL, and uri_is_dir().
Referenced by fr_archive_add_items().
g_load_file_in_buffer()
gboolean g_load_file_in_buffer (GFile * file, void * buffer, gsize size, GError ** error)
Definition at line 1357 of file gio-utils.c.
References error, FALSE, and NULL.
Referenced by rar_check_multi_volume().