MATE Desktop Environment: gpm-idle.c File Reference
gpm-idle.c File Reference
#include "config.h"
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <errno.h>
#include <string.h>
#include <sys/time.h>
#include <sys/types.h>
#include <glib.h>
#include <glib/gi18n.h>
#include "egg-idletime.h"
#include "gpm-idle.h"
#include "gpm-load.h"
#include "gpm-session.h"
Macros
#define GPM_IDLE_CPU_LIMIT 5
#define GPM_IDLE_IDLETIME_ID 1
Enumerations
enum { IDLE_CHANGED , LAST_SIGNAL }
Functions
void gpm_idle_set_check_cpu (GpmIdle *idle, gboolean check_type_cpu)
GpmIdleMode gpm_idle_get_mode (GpmIdle *idle)
gboolean gpm_idle_set_timeout_dim (GpmIdle *idle, guint timeout)
gboolean gpm_idle_set_timeout_blank (GpmIdle *idle, guint timeout)
gboolean gpm_idle_set_timeout_sleep (GpmIdle *idle, guint timeout)
GpmIdle * gpm_idle_new (void)
Macro Definition Documentation
GPM_IDLE_CPU_LIMIT
#define GPM_IDLE_CPU_LIMIT 5
Definition at line 49 of file gpm-idle.c.
GPM_IDLE_IDLETIME_ID
#define GPM_IDLE_IDLETIME_ID 1
Definition at line 50 of file gpm-idle.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
IDLE_CHANGED
LAST_SIGNAL
Definition at line 67 of file gpm-idle.c.
Function Documentation
gpm_idle_get_mode()
GpmIdleMode gpm_idle_get_mode (GpmIdle * idle)
gpm_idle_get_mode: Return value: The current mode, e.g. GPM_IDLE_MODE_SLEEP
Definition at line 128 of file gpm-idle.c.
References GpmIdle::priv.
gpm_idle_new()
GpmIdle * gpm_idle_new (void)
gpm_idle_new: Return value: A new GpmIdle instance.
Definition at line 489 of file gpm-idle.c.
References GPM_IDLE, GPM_TYPE_IDLE, and NULL.
gpm_idle_set_check_cpu()
void gpm_idle_set_check_cpu (GpmIdle * idle, gboolean check_type_cpu)
gpm_idle_set_check_cpu: @check_type_cpu: If we should check the CPU before mode becomes GPM_IDLE_MODE_SLEEP and the event is done.
Definition at line 116 of file gpm-idle.c.
References GPM_IS_IDLE, and GpmIdle::priv.
gpm_idle_set_timeout_blank()
gboolean gpm_idle_set_timeout_blank (GpmIdle * idle, guint timeout)
gpm_idle_set_timeout_blank: @timeout: The new timeout we want to set, in seconds
Definition at line 317 of file gpm-idle.c.
References FALSE, GPM_IS_IDLE, GpmIdle::priv, and TRUE.
gpm_idle_set_timeout_dim()
gboolean gpm_idle_set_timeout_dim (GpmIdle * idle, guint timeout)
gpm_idle_set_timeout_dim: @timeout: The new timeout we want to set, in seconds
Definition at line 287 of file gpm-idle.c.
References egg_idletime_alarm_remove(), egg_idletime_alarm_set(), egg_idletime_get_time(), FALSE, GPM_IDLE_IDLETIME_ID, GPM_IS_IDLE, GpmIdle::priv, and TRUE.
gpm_idle_set_timeout_sleep()
gboolean gpm_idle_set_timeout_sleep (GpmIdle * idle, guint timeout)
gpm_idle_set_timeout_sleep: @timeout: The new timeout we want to set, in seconds
Definition at line 334 of file gpm-idle.c.
References FALSE, GPM_IS_IDLE, GpmIdle::priv, and TRUE.