MATE Desktop Environment: gpm-networkmanager.c File Reference
gpm-networkmanager.c File Reference
#include <glib.h>
#include <dbus/dbus-glib.h>
#include "gpm-networkmanager.h"
Macros
#define NM_LISTENER_SERVICE "org.freedesktop.NetworkManager"
#define NM_LISTENER_PATH "/org/freedesktop/NetworkManager"
#define NM_LISTENER_INTERFACE "org.freedesktop.NetworkManager"
Functions
gboolean gpm_networkmanager_sleep (void)
gboolean gpm_networkmanager_wake (void)
Macro Definition Documentation
NM_LISTENER_INTERFACE
#define NM_LISTENER_INTERFACE "org.freedesktop.NetworkManager"
Definition at line 34 of file gpm-networkmanager.c.
NM_LISTENER_PATH
#define NM_LISTENER_PATH "/org/freedesktop/NetworkManager"
Definition at line 33 of file gpm-networkmanager.c.
NM_LISTENER_SERVICE
#define NM_LISTENER_SERVICE "org.freedesktop.NetworkManager"
Definition at line 32 of file gpm-networkmanager.c.
Function Documentation
gpm_networkmanager_sleep()
gboolean gpm_networkmanager_sleep (void)
gpm_networkmanager_sleep:
Tell NetworkManager to put the network devices to sleep
Return value: TRUE if NetworkManager is now sleeping.
Definition at line 44 of file gpm-networkmanager.c.
References connection, error, FALSE, NM_LISTENER_INTERFACE, NM_LISTENER_PATH, NM_LISTENER_SERVICE, NULL, and TRUE.
Referenced by gpm_control_hibernate(), and gpm_control_suspend().
gpm_networkmanager_wake()
gboolean gpm_networkmanager_wake (void)
gpm_networkmanager_wake:
Tell NetworkManager to wake up all the network devices
Return value: TRUE if NetworkManager is now awake.
Definition at line 78 of file gpm-networkmanager.c.
References connection, error, FALSE, NM_LISTENER_INTERFACE, NM_LISTENER_PATH, NM_LISTENER_SERVICE, NULL, and TRUE.
Referenced by gpm_control_hibernate(), and gpm_control_suspend().