MATE Desktop Environment: gpm-idle.h File Reference
gpm-idle.h File Reference
#include <glib-object.h>
Classes
struct GpmIdle
struct GpmIdleClass
Macros
#define GPM_TYPE_IDLE (gpm_idle_get_type ())
#define GPM_IDLE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPM_TYPE_IDLE, GpmIdle))
#define GPM_IDLE_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), GPM_TYPE_IDLE, GpmIdleClass))
#define GPM_IS_IDLE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPM_TYPE_IDLE))
#define GPM_IS_IDLE_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPM_TYPE_IDLE))
#define GPM_IDLE_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPM_TYPE_IDLE, GpmIdleClass))
Typedefs
typedef struct GpmIdlePrivate GpmIdlePrivate
Enumerations
enum GpmIdleMode { GPM_IDLE_MODE_NORMAL , GPM_IDLE_MODE_DIM , GPM_IDLE_MODE_BLANK , GPM_IDLE_MODE_SLEEP }
Functions
GType gpm_idle_get_type (void)
GpmIdle * gpm_idle_new (void)
GpmIdleMode gpm_idle_get_mode (GpmIdle *idle)
void gpm_idle_set_check_cpu (GpmIdle *idle, gboolean check_type_cpu)
gboolean gpm_idle_set_timeout_dim (GpmIdle *idle, guint timeout)
gboolean gpm_idle_set_timeout_blank (GpmIdle *idle, guint timeout)
gboolean gpm_idle_set_timeout_sleep (GpmIdle *idle, guint timeout)
void gpm_idle_test (gpointer data)
Macro Definition Documentation
GPM_IDLE
#define GPM_IDLE (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPM_TYPE_IDLE, GpmIdle))
Definition at line 32 of file gpm-idle.h.
GPM_IDLE_CLASS
#define GPM_IDLE_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), GPM_TYPE_IDLE, GpmIdleClass))
Definition at line 33 of file gpm-idle.h.
GPM_IDLE_GET_CLASS
#define GPM_IDLE_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPM_TYPE_IDLE, GpmIdleClass))
Definition at line 36 of file gpm-idle.h.
GPM_IS_IDLE
#define GPM_IS_IDLE (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPM_TYPE_IDLE))
Definition at line 34 of file gpm-idle.h.
GPM_IS_IDLE_CLASS
#define GPM_IS_IDLE_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPM_TYPE_IDLE))
Definition at line 35 of file gpm-idle.h.
GPM_TYPE_IDLE
#define GPM_TYPE_IDLE (gpm_idle_get_type ())
Definition at line 31 of file gpm-idle.h.
Typedef Documentation
GpmIdlePrivate
typedef struct GpmIdlePrivate GpmIdlePrivate
Definition at line 45 of file gpm-idle.h.
Enumeration Type Documentation
GpmIdleMode
enum GpmIdleMode
Enumerator
GPM_IDLE_MODE_NORMAL
GPM_IDLE_MODE_DIM
GPM_IDLE_MODE_BLANK
GPM_IDLE_MODE_SLEEP
Definition at line 38 of file gpm-idle.h.
Function Documentation
gpm_idle_get_mode()
GpmIdleMode gpm_idle_get_mode (GpmIdle * idle)
gpm_idle_get_mode: Return value: The current mode, e.g. GPM_IDLE_MODE_SLEEP
Definition at line 128 of file gpm-idle.c.
References GpmIdle::priv.
gpm_idle_get_type()
GType gpm_idle_get_type (void)
gpm_idle_new()
GpmIdle * gpm_idle_new (void)
gpm_idle_new: Return value: A new GpmIdle instance.
Definition at line 489 of file gpm-idle.c.
References GPM_IDLE, GPM_TYPE_IDLE, and NULL.
gpm_idle_set_check_cpu()
void gpm_idle_set_check_cpu (GpmIdle * idle, gboolean check_type_cpu)
gpm_idle_set_check_cpu: @check_type_cpu: If we should check the CPU before mode becomes GPM_IDLE_MODE_SLEEP and the event is done.
Definition at line 116 of file gpm-idle.c.
References GPM_IS_IDLE, and GpmIdle::priv.
gpm_idle_set_timeout_blank()
gboolean gpm_idle_set_timeout_blank (GpmIdle * idle, guint timeout)
gpm_idle_set_timeout_blank: @timeout: The new timeout we want to set, in seconds
Definition at line 317 of file gpm-idle.c.
References FALSE, GPM_IS_IDLE, GpmIdle::priv, and TRUE.
gpm_idle_set_timeout_dim()
gboolean gpm_idle_set_timeout_dim (GpmIdle * idle, guint timeout)
gpm_idle_set_timeout_dim: @timeout: The new timeout we want to set, in seconds
Definition at line 287 of file gpm-idle.c.
References egg_idletime_alarm_remove(), egg_idletime_alarm_set(), egg_idletime_get_time(), FALSE, GPM_IDLE_IDLETIME_ID, GPM_IS_IDLE, GpmIdle::priv, and TRUE.
gpm_idle_set_timeout_sleep()
gboolean gpm_idle_set_timeout_sleep (GpmIdle * idle, guint timeout)
gpm_idle_set_timeout_sleep: @timeout: The new timeout we want to set, in seconds
Definition at line 334 of file gpm-idle.c.
References FALSE, GPM_IS_IDLE, GpmIdle::priv, and TRUE.
gpm_idle_test()
void gpm_idle_test (gpointer data)