MATE Desktop Environment: gpm-screensaver.h File Reference
gpm-screensaver.h File Reference
#include <glib-object.h>
Classes
struct GpmScreensaver
struct GpmScreensaverClass
Macros
#define GPM_TYPE_SCREENSAVER (gpm_screensaver_get_type ())
#define GPM_SCREENSAVER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPM_TYPE_SCREENSAVER, GpmScreensaver))
#define GPM_SCREENSAVER_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), GPM_TYPE_SCREENSAVER, GpmScreensaverClass))
#define GPM_IS_SCREENSAVER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPM_TYPE_SCREENSAVER))
#define GPM_IS_SCREENSAVER_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPM_TYPE_SCREENSAVER))
#define GPM_SCREENSAVER_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPM_TYPE_SCREENSAVER, GpmScreensaverClass))
Typedefs
typedef struct GpmScreensaverPrivate GpmScreensaverPrivate
Functions
GType gpm_screensaver_get_type (void)
GpmScreensaver * gpm_screensaver_new (void)
void gpm_screensaver_test (gpointer data)
gboolean gpm_screensaver_lock (GpmScreensaver *screensaver)
guint32 gpm_screensaver_add_throttle (GpmScreensaver *screensaver, const gchar *reason)
gboolean gpm_screensaver_remove_throttle (GpmScreensaver *screensaver, guint32 cookie)
gboolean gpm_screensaver_check_running (GpmScreensaver *screensaver)
gboolean gpm_screensaver_poke (GpmScreensaver *screensaver)
Macro Definition Documentation
GPM_IS_SCREENSAVER
#define GPM_IS_SCREENSAVER (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPM_TYPE_SCREENSAVER))
Definition at line 33 of file gpm-screensaver.h.
GPM_IS_SCREENSAVER_CLASS
#define GPM_IS_SCREENSAVER_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPM_TYPE_SCREENSAVER))
Definition at line 34 of file gpm-screensaver.h.
GPM_SCREENSAVER
#define GPM_SCREENSAVER (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPM_TYPE_SCREENSAVER, GpmScreensaver))
Definition at line 31 of file gpm-screensaver.h.
GPM_SCREENSAVER_CLASS
#define GPM_SCREENSAVER_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), GPM_TYPE_SCREENSAVER, GpmScreensaverClass))
Definition at line 32 of file gpm-screensaver.h.
GPM_SCREENSAVER_GET_CLASS
#define GPM_SCREENSAVER_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPM_TYPE_SCREENSAVER, GpmScreensaverClass))
Definition at line 35 of file gpm-screensaver.h.
GPM_TYPE_SCREENSAVER
#define GPM_TYPE_SCREENSAVER (gpm_screensaver_get_type ())
Definition at line 30 of file gpm-screensaver.h.
Typedef Documentation
GpmScreensaverPrivate
typedef struct GpmScreensaverPrivate GpmScreensaverPrivate
Definition at line 37 of file gpm-screensaver.h.
Function Documentation
gpm_screensaver_add_throttle()
guint32 gpm_screensaver_add_throttle (GpmScreensaver * screensaver, const gchar * reason)
gpm_screensaver_check_running()
gboolean gpm_screensaver_check_running (GpmScreensaver * screensaver)
gpm_screensaver_check_running: @screensaver: This class instance Return value: TRUE if mate-screensaver is running
Definition at line 173 of file gpm-screensaver.c.
References error, FALSE, GPM_IS_SCREENSAVER, NULL, GpmScreensaver::priv, and TRUE.
Referenced by gpm_screensaver_lock().
gpm_screensaver_get_type()
GType gpm_screensaver_get_type (void)
gpm_screensaver_lock()
gboolean gpm_screensaver_lock (GpmScreensaver * screensaver)
gpm_screensaver_lock @screensaver: This class instance Return value: Success value
Definition at line 54 of file gpm-screensaver.c.
References FALSE, GPM_IS_SCREENSAVER, gpm_screensaver_check_running(), NULL, GpmScreensaver::priv, and TRUE.
Referenced by gpm_control_hibernate(), and gpm_control_suspend().
gpm_screensaver_new()
GpmScreensaver * gpm_screensaver_new (void)
gpm_screensaver_new: Return value: new GpmScreensaver instance.
Definition at line 277 of file gpm-screensaver.c.
References GPM_SCREENSAVER, GPM_TYPE_SCREENSAVER, and NULL.
Referenced by gpm_control_hibernate(), and gpm_control_suspend().
gpm_screensaver_poke()
gboolean gpm_screensaver_poke (GpmScreensaver * screensaver)
gpm_screensaver_poke: @screensaver: This class instance
Pokes MATE Screensaver simulating hardware events. This displays the unlock dialogue when we resume, so the user doesn't have to move the mouse or press any key before the window comes up.
Definition at line 208 of file gpm-screensaver.c.
References FALSE, GPM_IS_SCREENSAVER, NULL, GpmScreensaver::priv, and TRUE.
Referenced by gpm_control_hibernate(), and gpm_control_suspend().
gpm_screensaver_remove_throttle()
gboolean gpm_screensaver_remove_throttle (GpmScreensaver * screensaver, guint32 cookie)
gpm_screensaver_test()
void gpm_screensaver_test (gpointer data)