MATE Desktop Environment: gpm-kbd-backlight.h File Reference
gpm-kbd-backlight.h File Reference
#include <gio/gio.h>
#include <glib.h>
#include <glib-object.h>
Classes
struct GpmKbdBacklight
struct GpmKbdBacklightClass
Macros
#define GPM_TYPE_KBD_BACKLIGHT (gpm_kbd_backlight_get_type ())
#define GPM_KBD_BACKLIGHT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPM_TYPE_KBD_BACKLIGHT, GpmKbdBacklight))
#define GPM_KBD_BACKLIGHT_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), GPM_TYPE_KBD_BACKLIGHT, GpmKbdBacklightClass))
#define GPM_IS_KBD_BACKLIGHT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPM_TYPE_KBD_BACKLIGHT))
#define GPM_IS_KBD_BACKLIGHT_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPM_TYPE_KBD_BACKLIGHT))
#define GPM_KBD_BACKLIGHT_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPM_TYPE_KBD_BACKLIGHT, GpmKbdBacklightClass))
#define GPM_KBD_BACKLIGHT_DIM_INTERVAL 5 /* ms */
#define GPM_KBD_BACKLIGHT_STEP 10 /* change by 10% each step */
Typedefs
typedef struct GpmKbdBacklightPrivate GpmKbdBacklightPrivate
Enumerations
enum GpmKbdBacklightError { GPM_KBD_BACKLIGHT_ERROR_GENERAL , GPM_KBD_BACKLIGHT_ERROR_DATA_NOT_AVAILABLE , GPM_KBD_BACKLIGHT_ERROR_HARDWARE_NOT_PRESENT }
Functions
GType gpm_kbd_backlight_get_type (void)
GQuark gpm_kbd_backlight_error_quark (void)
GpmKbdBacklight * gpm_kbd_backlight_new (void)
gboolean gpm_kbd_backlight_get_brightness (GpmKbdBacklight *backlight, guint *brightness, GError **error)
gboolean gpm_kbd_backlight_set_brightness (GpmKbdBacklight *backlight, guint brightness, GError **error)
void gpm_kbd_backlight_register_dbus (GpmKbdBacklight *backlight, GDBusConnection *connection, GError **error)
Macro Definition Documentation
GPM_IS_KBD_BACKLIGHT
#define GPM_IS_KBD_BACKLIGHT (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPM_TYPE_KBD_BACKLIGHT))
Definition at line 35 of file gpm-kbd-backlight.h.
GPM_IS_KBD_BACKLIGHT_CLASS
#define GPM_IS_KBD_BACKLIGHT_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPM_TYPE_KBD_BACKLIGHT))
Definition at line 36 of file gpm-kbd-backlight.h.
GPM_KBD_BACKLIGHT
#define GPM_KBD_BACKLIGHT (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPM_TYPE_KBD_BACKLIGHT, GpmKbdBacklight))
Definition at line 33 of file gpm-kbd-backlight.h.
GPM_KBD_BACKLIGHT_CLASS
#define GPM_KBD_BACKLIGHT_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), GPM_TYPE_KBD_BACKLIGHT, GpmKbdBacklightClass))
Definition at line 34 of file gpm-kbd-backlight.h.
GPM_KBD_BACKLIGHT_DIM_INTERVAL
#define GPM_KBD_BACKLIGHT_DIM_INTERVAL 5 /* ms */
Definition at line 39 of file gpm-kbd-backlight.h.
GPM_KBD_BACKLIGHT_GET_CLASS
#define GPM_KBD_BACKLIGHT_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPM_TYPE_KBD_BACKLIGHT, GpmKbdBacklightClass))
Definition at line 37 of file gpm-kbd-backlight.h.
GPM_KBD_BACKLIGHT_STEP
#define GPM_KBD_BACKLIGHT_STEP 10 /* change by 10% each step */
Definition at line 40 of file gpm-kbd-backlight.h.
GPM_TYPE_KBD_BACKLIGHT
#define GPM_TYPE_KBD_BACKLIGHT (gpm_kbd_backlight_get_type ())
Definition at line 32 of file gpm-kbd-backlight.h.
Typedef Documentation
GpmKbdBacklightPrivate
typedef struct GpmKbdBacklightPrivate GpmKbdBacklightPrivate
Definition at line 42 of file gpm-kbd-backlight.h.
Enumeration Type Documentation
GpmKbdBacklightError
enum GpmKbdBacklightError
Enumerator
GPM_KBD_BACKLIGHT_ERROR_GENERAL
GPM_KBD_BACKLIGHT_ERROR_DATA_NOT_AVAILABLE
GPM_KBD_BACKLIGHT_ERROR_HARDWARE_NOT_PRESENT
Definition at line 57 of file gpm-kbd-backlight.h.
Function Documentation
gpm_kbd_backlight_error_quark()
GQuark gpm_kbd_backlight_error_quark (void)
gpm_kbd_backlight_error_quark: Return value: Our personal error quark.
Definition at line 69 of file gpm-kbd-backlight.c.
Referenced by gpm_kbd_backlight_get_brightness(), and gpm_kbd_backlight_set_brightness().
gpm_kbd_backlight_get_brightness()
gboolean gpm_kbd_backlight_get_brightness (GpmKbdBacklight * backlight, guint * brightness, GError ** error)
gpm_kbd_backlight_get_brightness: @backlight: @brightness: @error:
Return value:
Definition at line 86 of file gpm-kbd-backlight.c.
References error, FALSE, GPM_IS_KBD_BACKLIGHT, GPM_KBD_BACKLIGHT_ERROR_HARDWARE_NOT_PRESENT, gpm_kbd_backlight_error_quark(), NULL, GpmKbdBacklight::priv, and TRUE.
gpm_kbd_backlight_get_type()
GType gpm_kbd_backlight_get_type (void)
gpm_kbd_backlight_new()
GpmKbdBacklight * gpm_kbd_backlight_new (void)
gpm_kbd_backlight_new: Return value: A new GpmKbdBacklight class instance.
Definition at line 714 of file gpm-kbd-backlight.c.
References GPM_TYPE_KBD_BACKLIGHT, and NULL.
gpm_kbd_backlight_register_dbus()
void gpm_kbd_backlight_register_dbus (GpmKbdBacklight * backlight, GDBusConnection * connection, GError ** error)
gpm_kbd_backlight_set_brightness()
gboolean gpm_kbd_backlight_set_brightness (GpmKbdBacklight * backlight, guint percentage, GError ** error)
gpm_kbd_backlight_set_brightness: @backlight: @percentage: @error:
Return value:
Definition at line 296 of file gpm-kbd-backlight.c.
References error, FALSE, GPM_IS_KBD_BACKLIGHT, GPM_KBD_BACKLIGHT_ERROR_GENERAL, GPM_KBD_BACKLIGHT_ERROR_HARDWARE_NOT_PRESENT, gpm_kbd_backlight_error_quark(), NULL, GpmKbdBacklight::priv, and TRUE.