MATE Desktop Environment: gpm-control.h File Reference
gpm-control.h File Reference
#include <glib-object.h>
Classes
struct GpmControl
struct GpmControlClass
Macros
#define GPM_TYPE_CONTROL (gpm_control_get_type ())
#define GPM_CONTROL(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPM_TYPE_CONTROL, GpmControl))
#define GPM_CONTROL_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), GPM_TYPE_CONTROL, GpmControlClass))
#define GPM_IS_CONTROL(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPM_TYPE_CONTROL))
#define GPM_IS_CONTROL_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPM_TYPE_CONTROL))
#define GPM_CONTROL_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPM_TYPE_CONTROL, GpmControlClass))
#define GPM_CONTROL_ERROR gpm_control_error_quark ()
Typedefs
typedef struct GpmControlPrivate GpmControlPrivate
Enumerations
enum GpmControlAction { GPM_CONTROL_ACTION_SUSPEND , GPM_CONTROL_ACTION_HIBERNATE , GPM_CONTROL_ACTION_LAST }
enum GpmControlError { GPM_CONTROL_ERROR_GENERAL , GPM_CONTROL_ERROR_LAST }
Functions
GQuark gpm_control_error_quark (void)
GType gpm_control_get_type (void)
GpmControl * gpm_control_new (void)
gboolean gpm_control_suspend (GpmControl *control, GError **error)
gboolean gpm_control_hibernate (GpmControl *control, GError **error)
gboolean gpm_control_shutdown (GpmControl *control, GError **error)
gboolean gpm_control_get_lock_policy (GpmControl *control, const gchar *policy)
Macro Definition Documentation
GPM_CONTROL
#define GPM_CONTROL (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPM_TYPE_CONTROL, GpmControl))
Definition at line 32 of file gpm-control.h.
GPM_CONTROL_CLASS
#define GPM_CONTROL_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), GPM_TYPE_CONTROL, GpmControlClass))
Definition at line 33 of file gpm-control.h.
GPM_CONTROL_ERROR
#define GPM_CONTROL_ERROR gpm_control_error_quark ()
Definition at line 72 of file gpm-control.h.
GPM_CONTROL_GET_CLASS
#define GPM_CONTROL_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPM_TYPE_CONTROL, GpmControlClass))
Definition at line 36 of file gpm-control.h.
GPM_IS_CONTROL
#define GPM_IS_CONTROL (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPM_TYPE_CONTROL))
Definition at line 34 of file gpm-control.h.
GPM_IS_CONTROL_CLASS
#define GPM_IS_CONTROL_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPM_TYPE_CONTROL))
Definition at line 35 of file gpm-control.h.
GPM_TYPE_CONTROL
#define GPM_TYPE_CONTROL (gpm_control_get_type ())
Definition at line 31 of file gpm-control.h.
Typedef Documentation
GpmControlPrivate
typedef struct GpmControlPrivate GpmControlPrivate
Definition at line 38 of file gpm-control.h.
Enumeration Type Documentation
GpmControlAction
enum GpmControlAction
Enumerator
GPM_CONTROL_ACTION_SUSPEND
GPM_CONTROL_ACTION_HIBERNATE
GPM_CONTROL_ACTION_LAST
Definition at line 46 of file gpm-control.h.
GpmControlError
enum GpmControlError
Enumerator
GPM_CONTROL_ERROR_GENERAL
GPM_CONTROL_ERROR_LAST
Definition at line 53 of file gpm-control.h.
Function Documentation
gpm_control_error_quark()
GQuark gpm_control_error_quark (void)
gpm_control_error_quark: Return value: Our personal error quark.
Definition at line 78 of file gpm-control.c.
gpm_control_get_lock_policy()
gboolean gpm_control_get_lock_policy (GpmControl * control, const gchar * policy)
gpm_control_get_lock_policy: @control: This class instance @policy: The policy string.
This function finds out if we should lock the screen when we do an action. It is required as we can either use the mate-screensaver policy or the custom policy. See the yelp file for more information.
Return value: TRUE if we should lock.
Definition at line 166 of file gpm-control.c.
References FALSE, GPM_SETTINGS_LOCK_USE_SCREENSAVER, GS_SETTINGS_PREF_LOCK_ENABLED, GS_SETTINGS_SCHEMA, NULL, GpmControl::priv, and TRUE.
Referenced by gpm_control_hibernate(), and gpm_control_suspend().
gpm_control_get_type()
GType gpm_control_get_type (void)
gpm_control_hibernate()
gboolean gpm_control_hibernate (GpmControl * control, GError ** error)
gpm_control_hibernate:
Definition at line 363 of file gpm-control.c.
References egg_console_kit_can_hibernate(), egg_console_kit_hibernate(), egg_console_kit_new(), error, FALSE, GPM_CONTROL_ACTION_HIBERNATE, GPM_CONTROL_ERROR, GPM_CONTROL_ERROR_GENERAL, gpm_control_get_lock_policy(), gpm_networkmanager_sleep(), gpm_networkmanager_wake(), gpm_screensaver_add_throttle(), gpm_screensaver_lock(), gpm_screensaver_new(), gpm_screensaver_poke(), gpm_screensaver_remove_throttle(), GPM_SETTINGS_LOCK_KEYRING_HIBERNATE, GPM_SETTINGS_LOCK_KEYRING_SUSPEND, GPM_SETTINGS_LOCK_ON_HIBERNATE, GPM_SETTINGS_NETWORKMANAGER_SLEEP, LOGIND_RUNNING, NULL, GpmControl::priv, proxy, RESUME, SLEEP, and TRUE.
gpm_control_new()
GpmControl * gpm_control_new (void)
gpm_control_new: Return value: A new control class instance.
Definition at line 577 of file gpm-control.c.
References GPM_CONTROL, GPM_TYPE_CONTROL, and NULL.
gpm_control_shutdown()
gboolean gpm_control_shutdown (GpmControl * control, GError ** error)
gpm_control_shutdown: @control: This class instance
Shuts down the computer
Definition at line 139 of file gpm-control.c.
References egg_console_kit_new(), egg_console_kit_stop(), error, and LOGIND_RUNNING.
gpm_control_suspend()
gboolean gpm_control_suspend (GpmControl * control, GError ** error)
gpm_control_suspend:
Definition at line 208 of file gpm-control.c.
References egg_console_kit_can_suspend(), egg_console_kit_new(), egg_console_kit_suspend(), error, FALSE, GPM_CONTROL_ACTION_SUSPEND, GPM_CONTROL_ERROR, GPM_CONTROL_ERROR_GENERAL, gpm_control_get_lock_policy(), gpm_networkmanager_sleep(), gpm_networkmanager_wake(), gpm_screensaver_add_throttle(), gpm_screensaver_lock(), gpm_screensaver_new(), gpm_screensaver_poke(), gpm_screensaver_remove_throttle(), GPM_SETTINGS_LOCK_KEYRING_SUSPEND, GPM_SETTINGS_LOCK_ON_SUSPEND, GPM_SETTINGS_NETWORKMANAGER_SLEEP, LOGIND_RUNNING, NULL, GpmControl::priv, proxy, RESUME, SLEEP, and TRUE.