MATE Desktop Environment: gpm-backlight.h File Reference
gpm-backlight.h File Reference
#include <glib-object.h>
Classes
struct GpmBacklight
struct GpmBacklightClass
Macros
#define GPM_TYPE_BACKLIGHT (gpm_backlight_get_type ())
#define GPM_BACKLIGHT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPM_TYPE_BACKLIGHT, GpmBacklight))
#define GPM_BACKLIGHT_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), GPM_TYPE_BACKLIGHT, GpmBacklightClass))
#define GPM_IS_BACKLIGHT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPM_TYPE_BACKLIGHT))
#define GPM_IS_BACKLIGHT_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPM_TYPE_BACKLIGHT))
#define GPM_BACKLIGHT_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPM_TYPE_BACKLIGHT, GpmBacklightClass))
Typedefs
typedef struct GpmBacklightPrivate GpmBacklightPrivate
Enumerations
enum GpmBacklightError { GPM_BACKLIGHT_ERROR_GENERAL , GPM_BACKLIGHT_ERROR_DATA_NOT_AVAILABLE , GPM_BACKLIGHT_ERROR_HARDWARE_NOT_PRESENT }
Functions
GType gpm_backlight_get_type (void)
GQuark gpm_backlight_error_quark (void)
GpmBacklight * gpm_backlight_new (void)
gboolean gpm_backlight_get_brightness (GpmBacklight *backlight, guint *brightness, GError **error)
gboolean gpm_backlight_set_brightness (GpmBacklight *backlight, guint brightness, GError **error)
Macro Definition Documentation
GPM_BACKLIGHT
#define GPM_BACKLIGHT (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPM_TYPE_BACKLIGHT, GpmBacklight))
Definition at line 32 of file gpm-backlight.h.
GPM_BACKLIGHT_CLASS
#define GPM_BACKLIGHT_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), GPM_TYPE_BACKLIGHT, GpmBacklightClass))
Definition at line 33 of file gpm-backlight.h.
GPM_BACKLIGHT_GET_CLASS
#define GPM_BACKLIGHT_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPM_TYPE_BACKLIGHT, GpmBacklightClass))
Definition at line 36 of file gpm-backlight.h.
GPM_IS_BACKLIGHT
#define GPM_IS_BACKLIGHT (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPM_TYPE_BACKLIGHT))
Definition at line 34 of file gpm-backlight.h.
GPM_IS_BACKLIGHT_CLASS
#define GPM_IS_BACKLIGHT_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPM_TYPE_BACKLIGHT))
Definition at line 35 of file gpm-backlight.h.
GPM_TYPE_BACKLIGHT
#define GPM_TYPE_BACKLIGHT (gpm_backlight_get_type ())
Definition at line 31 of file gpm-backlight.h.
Typedef Documentation
GpmBacklightPrivate
typedef struct GpmBacklightPrivate GpmBacklightPrivate
Definition at line 38 of file gpm-backlight.h.
Enumeration Type Documentation
GpmBacklightError
enum GpmBacklightError
Enumerator
GPM_BACKLIGHT_ERROR_GENERAL
GPM_BACKLIGHT_ERROR_DATA_NOT_AVAILABLE
GPM_BACKLIGHT_ERROR_HARDWARE_NOT_PRESENT
Definition at line 53 of file gpm-backlight.h.
Function Documentation
gpm_backlight_error_quark()
GQuark gpm_backlight_error_quark (void)
gpm_backlight_error_quark: Return value: Our personal error quark.
Definition at line 89 of file gpm-backlight.c.
Referenced by gpm_backlight_get_brightness(), and gpm_backlight_set_brightness().
gpm_backlight_get_brightness()
gboolean gpm_backlight_get_brightness (GpmBacklight * backlight, guint * brightness, GError ** error)
gpm_backlight_get_brightness:
Definition at line 101 of file gpm-backlight.c.
References error, FALSE, GPM_BACKLIGHT_ERROR_DATA_NOT_AVAILABLE, GPM_BACKLIGHT_ERROR_HARDWARE_NOT_PRESENT, gpm_backlight_error_quark(), gpm_brightness_get(), GPM_IS_BACKLIGHT, level, NULL, and GpmBacklight::priv.
gpm_backlight_get_type()
GType gpm_backlight_get_type (void)
gpm_backlight_new()
GpmBacklight * gpm_backlight_new (void)
gpm_backlight_new: Return value: A new brightness class instance.
Definition at line 819 of file gpm-backlight.c.
References GPM_TYPE_BACKLIGHT, and NULL.
gpm_backlight_set_brightness()
gboolean gpm_backlight_set_brightness (GpmBacklight * backlight, guint percentage, GError ** error)
gpm_backlight_set_brightness:
Definition at line 133 of file gpm-backlight.c.
References BRIGHTNESS_CHANGED, error, FALSE, GPM_BACKLIGHT_ERROR_GENERAL, GPM_BACKLIGHT_ERROR_HARDWARE_NOT_PRESENT, gpm_backlight_error_quark(), gpm_brightness_set(), GPM_IS_BACKLIGHT, NULL, and GpmBacklight::priv.