MATE Desktop Environment: gpm-brightness.h File Reference
gpm-brightness.h File Reference
#include <glib-object.h>
Classes
struct GpmBrightness
struct GpmBrightnessClass
Macros
#define GPM_TYPE_BRIGHTNESS (gpm_brightness_get_type ())
#define GPM_BRIGHTNESS(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPM_TYPE_BRIGHTNESS, GpmBrightness))
#define GPM_BRIGHTNESS_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), GPM_TYPE_BRIGHTNESS, GpmBrightnessClass))
#define GPM_IS_BRIGHTNESS(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPM_TYPE_BRIGHTNESS))
#define GPM_IS_BRIGHTNESS_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPM_TYPE_BRIGHTNESS))
#define GPM_BRIGHTNESS_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPM_TYPE_BRIGHTNESS, GpmBrightnessClass))
#define GPM_BRIGHTNESS_DIM_INTERVAL 5 /* ms */
Typedefs
typedef struct GpmBrightnessPrivate GpmBrightnessPrivate
Functions
GType gpm_brightness_get_type (void)
GpmBrightness * gpm_brightness_new (void)
gboolean gpm_brightness_has_hw (GpmBrightness *brightness)
gboolean gpm_brightness_up (GpmBrightness *brightness, gboolean *hw_changed)
gboolean gpm_brightness_down (GpmBrightness *brightness, gboolean *hw_changed)
gboolean gpm_brightness_get (GpmBrightness *brightness, guint *percentage)
gboolean gpm_brightness_set (GpmBrightness *brightness, guint percentage, gboolean *hw_changed)
Macro Definition Documentation
GPM_BRIGHTNESS
#define GPM_BRIGHTNESS (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPM_TYPE_BRIGHTNESS, GpmBrightness))
Definition at line 31 of file gpm-brightness.h.
GPM_BRIGHTNESS_CLASS
#define GPM_BRIGHTNESS_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), GPM_TYPE_BRIGHTNESS, GpmBrightnessClass))
Definition at line 32 of file gpm-brightness.h.
GPM_BRIGHTNESS_DIM_INTERVAL
#define GPM_BRIGHTNESS_DIM_INTERVAL 5 /* ms */
Definition at line 37 of file gpm-brightness.h.
GPM_BRIGHTNESS_GET_CLASS
#define GPM_BRIGHTNESS_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPM_TYPE_BRIGHTNESS, GpmBrightnessClass))
Definition at line 35 of file gpm-brightness.h.
GPM_IS_BRIGHTNESS
#define GPM_IS_BRIGHTNESS (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPM_TYPE_BRIGHTNESS))
Definition at line 33 of file gpm-brightness.h.
GPM_IS_BRIGHTNESS_CLASS
#define GPM_IS_BRIGHTNESS_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPM_TYPE_BRIGHTNESS))
Definition at line 34 of file gpm-brightness.h.
GPM_TYPE_BRIGHTNESS
#define GPM_TYPE_BRIGHTNESS (gpm_brightness_get_type ())
Definition at line 30 of file gpm-brightness.h.
Typedef Documentation
GpmBrightnessPrivate
typedef struct GpmBrightnessPrivate GpmBrightnessPrivate
Definition at line 39 of file gpm-brightness.h.
Function Documentation
gpm_brightness_down()
gboolean gpm_brightness_down (GpmBrightness * brightness, gboolean * hw_changed)
gpm_brightness_down: @brightness: This brightness class instance @hw_changed: If the hardware was changed, i.e. the brightness changed Return value: TRUE if success, FALSE if there was an error
If possible, put the brightness of the LCD down one unit.
Definition at line 734 of file gpm-brightness.c.
References ACTION_BACKLIGHT_DEC, FALSE, GPM_IS_BRIGHTNESS, NULL, and GpmBrightness::priv.
gpm_brightness_get()
gboolean gpm_brightness_get (GpmBrightness * brightness, guint * percentage)
gpm_brightness_get: @brightness: This brightness class instance Return value: The percentage brightness, or -1 for no hardware or error
Gets the current (or at least what this class thinks is current) percentage brightness. This is quick as no HAL inquiry is done.
Definition at line 628 of file gpm-brightness.c.
References ACTION_BACKLIGHT_GET, egg_discrete_to_percent(), FALSE, GPM_IS_BRIGHTNESS, NULL, GpmBrightness::priv, and TRUE.
Referenced by gpm_backlight_get_brightness().
gpm_brightness_get_type()
GType gpm_brightness_get_type (void)
gpm_brightness_has_hw()
gboolean gpm_brightness_has_hw (GpmBrightness * brightness)
gpm_brightness_has_hw:
Definition at line 866 of file gpm-brightness.c.
References FALSE, GPM_IS_BRIGHTNESS, GpmBrightness::priv, and TRUE.
gpm_brightness_new()
GpmBrightness * gpm_brightness_new (void)
gpm_brightness_new: Return value: A new brightness class instance. Can return NULL if no suitable hardware is found.
Definition at line 973 of file gpm-brightness.c.
References GPM_BRIGHTNESS, GPM_TYPE_BRIGHTNESS, and NULL.
gpm_brightness_set()
gboolean gpm_brightness_set (GpmBrightness * brightness, guint percentage, gboolean * hw_changed)
gpm_brightness_set: @brightness: This brightness class instance @percentage: The percentage brightness @hw_changed: If the hardware was changed, i.e. the brightness changed Return value: TRUE if success, FALSE if there was an error
Definition at line 579 of file gpm-brightness.c.
References ACTION_BACKLIGHT_SET, egg_discrete_from_percent(), FALSE, GPM_IS_BRIGHTNESS, NULL, GpmBrightness::priv, and TRUE.
Referenced by gpm_backlight_set_brightness().
gpm_brightness_up()
gboolean gpm_brightness_up (GpmBrightness * brightness, gboolean * hw_changed)
gpm_brightness_up: @brightness: This brightness class instance @hw_changed: If the hardware was changed, i.e. the brightness changed Return value: TRUE if success, FALSE if there was an error
If possible, put the brightness of the LCD up one unit.
Definition at line 683 of file gpm-brightness.c.
References ACTION_BACKLIGHT_INC, FALSE, GPM_IS_BRIGHTNESS, NULL, and GpmBrightness::priv.