MATE Desktop Environment: gradient.h File Reference
gradient.h File Reference
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gdk/gdk.h>
Enumerations
enum MetaGradientType { META_GRADIENT_VERTICAL , META_GRADIENT_HORIZONTAL , META_GRADIENT_DIAGONAL , META_GRADIENT_LAST }
Functions
GdkPixbuf * meta_gradient_create_simple (int width, int height, const GdkRGBA *from, const GdkRGBA *to, MetaGradientType style)
GdkPixbuf * meta_gradient_create_multi (int width, int height, const GdkRGBA *colors, int n_colors, MetaGradientType style)
GdkPixbuf * meta_gradient_create_interwoven (int width, int height, const GdkRGBA colors1[2], int thickness1, const GdkRGBA colors2[2], int thickness2)
void meta_gradient_add_alpha (GdkPixbuf *pixbuf, const guchar *alphas, int n_alphas, MetaGradientType type)
Enumeration Type Documentation
MetaGradientType
enum MetaGradientType
MetaGradientType: @META_GRADIENT_VERTICAL: Vertical gradient @META_GRADIENT_HORIZONTAL: Horizontal gradient @META_GRADIENT_DIAGONAL: Diagonal gradient @META_GRADIENT_LAST: Marks the end of the MetaGradientType enumeration
Enumerator
META_GRADIENT_VERTICAL
META_GRADIENT_HORIZONTAL
META_GRADIENT_DIAGONAL
META_GRADIENT_LAST
Definition at line 38 of file gradient.h.
Function Documentation
meta_gradient_add_alpha()
void meta_gradient_add_alpha (GdkPixbuf * pixbuf, const guchar * alphas, int n_alphas, MetaGradientType type)
Definition at line 859 of file gradient.c.
References META_GRADIENT_DIAGONAL, META_GRADIENT_HORIZONTAL, META_GRADIENT_LAST, META_GRADIENT_VERTICAL, and type.
meta_gradient_create_interwoven()
GdkPixbuf * meta_gradient_create_interwoven (int width, int height, const GdkRGBA colors1[2], int thickness1, const GdkRGBA colors2[2], int thickness2)
meta_gradient_create_interwoven: (skip) @width: Width in pixels @height: Height in pixels @colors1: Array of colors @thickness1: Thickness @colors2: Array of colors @thickness2: Thickness
Interwoven essentially means we have two vertical gradients, cut into horizontal strips of the given thickness, and then the strips are alternated. I'm not sure what it's good for, just copied since WindowMaker had it.
Definition at line 759 of file gradient.c.
References long(), memcpy, NULL, and RGBA_SCALING.
meta_gradient_create_multi()
GdkPixbuf * meta_gradient_create_multi (int width, int height, const GdkRGBA * colors, int n_colors, MetaGradientType style)
meta_gradient_create_multi: @width: Width in pixels @height: Height in pixels @colors: (array length=n_colors): Array of colors @n_colors: Number of colors @style: Gradient style
Returns: (transfer full): A new multi-step linear gradient
Definition at line 705 of file gradient.c.
References meta_gradient_create_simple(), META_GRADIENT_DIAGONAL, META_GRADIENT_HORIZONTAL, META_GRADIENT_LAST, META_GRADIENT_VERTICAL, and NULL.
meta_gradient_create_simple()
GdkPixbuf * meta_gradient_create_simple (int width, int height, const GdkRGBA * from, const GdkRGBA * to, MetaGradientType style)
meta_gradient_create_simple: @width: Width in pixels @height: Height in pixels @from: Starting color @to: Ending color @style: Gradient style
Returns: (transfer full): A new linear gradient
Definition at line 666 of file gradient.c.
References META_GRADIENT_DIAGONAL, META_GRADIENT_HORIZONTAL, META_GRADIENT_LAST, META_GRADIENT_VERTICAL, and NULL.
Referenced by meta_gradient_create_multi().