MATE Desktop Environment: group.c File Reference
group.c File Reference
#include <config.h>
#include "util.h"
#include "group-private.h"
#include "group-props.h"
#include "window.h"
Macros
#define N_INITIAL_PROPS 3
Functions
MetaGroup * meta_window_get_group (MetaWindow *window)
void meta_window_compute_group (MetaWindow *window)
void meta_window_group_leader_changed (MetaWindow *window)
void meta_window_shutdown_group (MetaWindow *window)
MetaGroup * meta_display_lookup_group (MetaDisplay *display, Window group_leader)
GSList * meta_group_list_windows (MetaGroup *group)
void meta_group_update_layers (MetaGroup *group)
const char * meta_group_get_startup_id (MetaGroup *group)
gboolean meta_group_property_notify (MetaGroup *group, XEvent *event)
Macro Definition Documentation
N_INITIAL_PROPS
#define N_INITIAL_PROPS 3
Function Documentation
meta_display_lookup_group()
MetaGroup * meta_display_lookup_group (MetaDisplay * display, Window group_leader)
Definition at line 201 of file group.c.
References _MetaDisplay::groups_by_leader, and NULL.
meta_group_get_startup_id()
const char * meta_group_get_startup_id (MetaGroup * group)
Definition at line 260 of file group.c.
References _MetaGroup::startup_id.
Referenced by meta_window_get_startup_id().
meta_group_list_windows()
GSList * meta_group_list_windows (MetaGroup * group)
Definition at line 216 of file group.c.
References _MetaGroup::windows.
meta_group_property_notify()
gboolean meta_group_property_notify (MetaGroup * group, XEvent * event)
Definition at line 266 of file group.c.
References meta_group_reload_property(), and TRUE.
meta_group_update_layers()
void meta_group_update_layers (MetaGroup * group)
Definition at line 222 of file group.c.
References meta_stack_freeze(), meta_stack_thaw(), meta_stack_update_layer(), NULL, _MetaWindow::screen, _MetaScreen::stack, and _MetaGroup::windows.
Referenced by meta_window_free(), and meta_window_update_layer().
meta_window_compute_group()
void meta_window_compute_group (MetaWindow * window)
Definition at line 116 of file group.c.
References _MetaWindow::desc, _MetaWindow::display, _MetaWindow::group, _MetaGroup::group_leader, _MetaDisplay::groups_by_leader, META_DEBUG_GROUPS, meta_window_find_root_ancestor(), NULL, _MetaGroup::refcount, _MetaGroup::windows, _MetaWindow::xgroup_leader, and _MetaWindow::xwindow.
Referenced by meta_window_group_leader_changed(), and meta_window_new_with_attrs().
meta_window_get_group()
MetaGroup * meta_window_get_group (MetaWindow * window)
Definition at line 107 of file group.c.
References _MetaWindow::group, NULL, and _MetaWindow::unmanaging.
Referenced by meta_window_free(), meta_window_get_startup_id(), meta_window_same_application(), and meta_window_update_layer().
meta_window_group_leader_changed()
void meta_window_group_leader_changed (MetaWindow * window)
Definition at line 188 of file group.c.
References meta_window_compute_group().
meta_window_shutdown_group()
void meta_window_shutdown_group (MetaWindow * window)
Definition at line 195 of file group.c.
Referenced by meta_window_free().