MATE Desktop Environment: gs-grab.h File Reference
gs-grab.h File Reference
#include <glib.h>
#include <gdk/gdk.h>
Classes
struct GSGrab
struct GSGrabClass
Macros
#define GS_TYPE_GRAB (gs_grab_get_type ())
#define GS_GRAB(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GS_TYPE_GRAB, GSGrab))
#define GS_GRAB_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), GS_TYPE_GRAB, GSGrabClass))
#define GS_IS_GRAB(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GS_TYPE_GRAB))
#define GS_IS_GRAB_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GS_TYPE_GRAB))
#define GS_GRAB_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GS_TYPE_GRAB, GSGrabClass))
Typedefs
typedef struct GSGrabPrivate GSGrabPrivate
Functions
GType gs_grab_get_type (void)
GSGrab * gs_grab_new (void)
void gs_grab_release (GSGrab *grab, gboolean flush)
gboolean gs_grab_grab_window (GSGrab *grab, GdkWindow *window, GdkDisplay *display, gboolean no_pointer_grab, gboolean hide_cursor)
gboolean gs_grab_grab_root (GSGrab *grab, gboolean no_pointer_grab, gboolean hide_cursor)
gboolean gs_grab_grab_offscreen (GSGrab *grab, gboolean no_pointer_grab, gboolean hide_cursor)
void gs_grab_move_to_window (GSGrab *grab, GdkWindow *window, GdkDisplay *display, gboolean no_pointer_grab, gboolean hide_cursor)
void gs_grab_reset (GSGrab *grab)
Macro Definition Documentation
GS_GRAB
#define GS_GRAB (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GS_TYPE_GRAB, GSGrab))
Definition at line 33 of file gs-grab.h.
GS_GRAB_CLASS
#define GS_GRAB_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), GS_TYPE_GRAB, GSGrabClass))
Definition at line 34 of file gs-grab.h.
GS_GRAB_GET_CLASS
#define GS_GRAB_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), GS_TYPE_GRAB, GSGrabClass))
Definition at line 37 of file gs-grab.h.
GS_IS_GRAB
#define GS_IS_GRAB (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GS_TYPE_GRAB))
Definition at line 35 of file gs-grab.h.
GS_IS_GRAB_CLASS
#define GS_IS_GRAB_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), GS_TYPE_GRAB))
Definition at line 36 of file gs-grab.h.
GS_TYPE_GRAB
#define GS_TYPE_GRAB (gs_grab_get_type ())
Definition at line 32 of file gs-grab.h.
Typedef Documentation
GSGrabPrivate
typedef struct GSGrabPrivate GSGrabPrivate
Definition at line 39 of file gs-grab.h.
Function Documentation
gs_grab_get_type()
GType gs_grab_get_type (void)
gs_grab_grab_offscreen()
gboolean gs_grab_grab_offscreen (GSGrab * grab, gboolean no_pointer_grab, gboolean hide_cursor)
Definition at line 358 of file gs-grab-x11.c.
References gs_debug, gs_grab_grab_window(), and GSGrab::priv.
gs_grab_grab_root()
gboolean gs_grab_grab_root (GSGrab * grab, gboolean no_pointer_grab, gboolean hide_cursor)
Definition at line 333 of file gs-grab-x11.c.
References gs_debug, gs_grab_grab_window(), and NULL.
gs_grab_grab_window()
gboolean gs_grab_grab_window (GSGrab * grab, GdkWindow * window, GdkDisplay * display, gboolean no_pointer_grab, gboolean hide_cursor)
Definition at line 290 of file gs-grab-x11.c.
References FALSE, gs_debug, and TRUE.
Referenced by gs_grab_grab_offscreen(), and gs_grab_grab_root().
gs_grab_move_to_window()
void gs_grab_move_to_window (GSGrab * grab, GdkWindow * window, GdkDisplay * display, gboolean no_pointer_grab, gboolean hide_cursor)
Definition at line 380 of file gs-grab-x11.c.
References FALSE, and GS_IS_GRAB.
gs_grab_new()
GSGrab * gs_grab_new (void)
Definition at line 437 of file gs-grab-x11.c.
References GS_GRAB, GS_TYPE_GRAB, and NULL.
Referenced by main().
gs_grab_release()
void gs_grab_release (GSGrab * grab, gboolean flush)
Definition at line 174 of file gs-grab-x11.c.
References gs_debug, gs_grab_reset(), and TRUE.
gs_grab_reset()
void gs_grab_reset (GSGrab * grab)
Definition at line 162 of file gs-grab-x11.c.
References NULL, and GSGrab::priv.
Referenced by gs_grab_release().