MATE Desktop Environment: gs-job.h File Reference
gs-job.h File Reference
#include <gtk/gtk.h>
Classes
struct GSJob
struct GSJobClass
Macros
#define GS_TYPE_JOB (gs_job_get_type ())
#define GS_JOB(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GS_TYPE_JOB, GSJob))
#define GS_JOB_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), GS_TYPE_JOB, GSJobClass))
#define GS_IS_JOB(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GS_TYPE_JOB))
#define GS_IS_JOB_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GS_TYPE_JOB))
#define GS_JOB_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GS_TYPE_JOB, GSJobClass))
Typedefs
typedef struct GSJobPrivate GSJobPrivate
Functions
GType gs_job_get_type (void)
GSJob * gs_job_new (void)
GSJob * gs_job_new_for_widget (GtkWidget *widget)
gboolean gs_job_is_running (GSJob *job)
gboolean gs_job_start (GSJob *job)
gboolean gs_job_stop (GSJob *job)
gboolean gs_job_suspend (GSJob *job, gboolean suspend)
void gs_job_set_widget (GSJob *job, GtkWidget *widget)
gboolean gs_job_set_command (GSJob *job, const char *command)
Macro Definition Documentation
GS_IS_JOB
#define GS_IS_JOB (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GS_TYPE_JOB))
Definition at line 34 of file gs-job.h.
GS_IS_JOB_CLASS
#define GS_IS_JOB_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), GS_TYPE_JOB))
Definition at line 35 of file gs-job.h.
GS_JOB
#define GS_JOB (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GS_TYPE_JOB, GSJob))
Definition at line 32 of file gs-job.h.
GS_JOB_CLASS
#define GS_JOB_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), GS_TYPE_JOB, GSJobClass))
Definition at line 33 of file gs-job.h.
GS_JOB_GET_CLASS
#define GS_JOB_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), GS_TYPE_JOB, GSJobClass))
Definition at line 36 of file gs-job.h.
GS_TYPE_JOB
#define GS_TYPE_JOB (gs_job_get_type ())
Definition at line 31 of file gs-job.h.
Typedef Documentation
GSJobPrivate
typedef struct GSJobPrivate GSJobPrivate
Definition at line 38 of file gs-job.h.
Function Documentation
gs_job_get_type()
GType gs_job_get_type (void)
gs_job_is_running()
gboolean gs_job_is_running (GSJob * job)
Definition at line 448 of file gs-job.c.
References FALSE, GS_IS_JOB, and GSJob::priv.
Referenced by gs_job_set_widget().
gs_job_new()
GSJob * gs_job_new (void)
Definition at line 212 of file gs-job.c.
References GS_JOB, GS_TYPE_JOB, and NULL.
Referenced by main().
gs_job_new_for_widget()
GSJob * gs_job_new_for_widget (GtkWidget * widget)
Definition at line 222 of file gs-job.c.
References GS_JOB, gs_job_set_widget(), GS_TYPE_JOB, and NULL.
gs_job_set_command()
gboolean gs_job_set_command (GSJob * job, const char * command)
Definition at line 197 of file gs-job.c.
References command, FALSE, gs_debug, GS_IS_JOB, NULL, GSJob::priv, and TRUE.
gs_job_set_widget()
void gs_job_set_widget (GSJob * job, GtkWidget * widget)
Definition at line 177 of file gs-job.c.
References GS_IS_JOB, gs_job_is_running(), gs_job_start(), gs_job_stop(), NULL, and GSJob::priv.
Referenced by gs_job_new_for_widget().
gs_job_start()
gboolean gs_job_start (GSJob * job)
Definition at line 460 of file gs-job.c.
References FALSE, gs_debug, GS_IS_JOB, GS_JOB_RUNNING, NULL, and GSJob::priv.
Referenced by gs_job_set_widget().
gs_job_stop()
gboolean gs_job_stop (GSJob * job)
Definition at line 565 of file gs-job.c.
References FALSE, gs_debug, GS_IS_JOB, GS_JOB_KILLED, GS_JOB_STOPPED, gs_job_suspend(), NULL, GSJob::priv, signal_pid(), and TRUE.
Referenced by gs_job_set_widget().
gs_job_suspend()
gboolean gs_job_suspend (GSJob * job, gboolean suspend)
Definition at line 595 of file gs-job.c.
References FALSE, gs_debug, GS_IS_JOB, GS_JOB_RUNNING, GS_JOB_STOPPED, NULL, GSJob::priv, signal_pid(), and TRUE.
Referenced by gs_job_stop().