MATE Desktop Environment: gs-manager.c File Reference
gs-manager.c File Reference
#include "config.h"
#include <time.h>
#include <gdk/gdk.h>
#include <gdk/gdkx.h>
#include <gio/gio.h>
#include <libmate-desktop/mate-bg.h>
#include "gs-prefs.h"
#include "gs-manager.h"
#include "gs-window.h"
#include "gs-theme-manager.h"
#include "gs-job.h"
#include "gs-grab.h"
#include "gs-fade.h"
#include "gs-debug.h"
Macros
#define MATE_DESKTOP_USE_UNSTABLE_API
#define FADE_TIMEOUT 250
Enumerations
enum {
ACTIVATED , DEACTIVATED , AUTH_REQUEST_BEGIN , AUTH_REQUEST_END ,
LAST_SIGNAL
}
enum {
PROP_0 , PROP_LOCK_ENABLED , PROP_LOGOUT_ENABLED , PROP_USER_SWITCH_ENABLED ,
PROP_KEYBOARD_ENABLED , PROP_LOCK_TIMEOUT , PROP_CYCLE_TIMEOUT , PROP_LOGOUT_TIMEOUT ,
PROP_LOGOUT_COMMAND , PROP_KEYBOARD_COMMAND , PROP_STATUS_MESSAGE , PROP_ACTIVE ,
PROP_THROTTLED
}
Functions
void gs_manager_set_mode (GSManager *manager, GSSaverMode mode)
void gs_manager_set_themes (GSManager *manager, GSList *themes)
void gs_manager_set_throttled (GSManager *manager, gboolean throttled)
void gs_manager_get_lock_active (GSManager *manager, gboolean *lock_active)
void gs_manager_set_lock_active (GSManager *manager, gboolean lock_active)
void gs_manager_get_lock_enabled (GSManager *manager, gboolean *lock_enabled)
void gs_manager_set_lock_enabled (GSManager *manager, gboolean lock_enabled)
void gs_manager_set_logout_enabled (GSManager *manager, gboolean logout_enabled)
void gs_manager_set_keyboard_enabled (GSManager *manager, gboolean enabled)
void gs_manager_set_user_switch_enabled (GSManager *manager, gboolean user_switch_enabled)
void gs_manager_set_lock_timeout (GSManager *manager, glong lock_timeout)
void gs_manager_set_logout_timeout (GSManager *manager, glong logout_timeout)
void gs_manager_set_logout_command (GSManager *manager, const char *command)
void gs_manager_set_keyboard_command (GSManager *manager, const char *command)
void gs_manager_set_status_message (GSManager *manager, const char *status_message)
gboolean gs_manager_cycle (GSManager *manager)
void gs_manager_set_cycle_timeout (GSManager *manager, glong cycle_timeout)
void gs_manager_show_message (GSManager *manager, const char *summary, const char *body, const char *icon)
GSManager * gs_manager_new (void)
gboolean gs_manager_set_active (GSManager *manager, gboolean active)
gboolean gs_manager_get_active (GSManager *manager)
gboolean gs_manager_request_unlock (GSManager *manager)
void gs_manager_cancel_unlock_request (GSManager *manager)
Macro Definition Documentation
FADE_TIMEOUT
#define FADE_TIMEOUT 250
Definition at line 116 of file gs-manager.c.
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 32 of file gs-manager.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ACTIVATED
DEACTIVATED
AUTH_REQUEST_BEGIN
AUTH_REQUEST_END
LAST_SIGNAL
Definition at line 90 of file gs-manager.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_LOCK_ENABLED
PROP_LOGOUT_ENABLED
PROP_USER_SWITCH_ENABLED
PROP_KEYBOARD_ENABLED
PROP_LOCK_TIMEOUT
PROP_CYCLE_TIMEOUT
PROP_LOGOUT_TIMEOUT
PROP_LOGOUT_COMMAND
PROP_KEYBOARD_COMMAND
PROP_STATUS_MESSAGE
PROP_ACTIVE
PROP_THROTTLED
Definition at line 99 of file gs-manager.c.
Function Documentation
gs_manager_cancel_unlock_request()
void gs_manager_cancel_unlock_request (GSManager * manager)
Definition at line 1960 of file gs-manager.c.
References gs_window_cancel_unlock_request(), and GSManager::priv.
gs_manager_cycle()
gboolean gs_manager_cycle (GSManager * manager)
Definition at line 707 of file gs-manager.c.
References FALSE, gs_debug, GS_IS_MANAGER, NULL, GSManager::priv, and TRUE.
gs_manager_get_active()
gboolean gs_manager_get_active (GSManager * manager)
Definition at line 1911 of file gs-manager.c.
References FALSE, GS_IS_MANAGER, NULL, and GSManager::priv.
gs_manager_get_lock_active()
void gs_manager_get_lock_active (GSManager * manager, gboolean * lock_active)
Definition at line 437 of file gs-manager.c.
References FALSE, GS_IS_MANAGER, NULL, and GSManager::priv.
gs_manager_get_lock_enabled()
void gs_manager_get_lock_enabled (GSManager * manager, gboolean * lock_enabled)
Definition at line 474 of file gs-manager.c.
References FALSE, GS_IS_MANAGER, NULL, and GSManager::priv.
gs_manager_new()
GSManager * gs_manager_new (void)
Definition at line 1762 of file gs-manager.c.
References GS_MANAGER, GS_TYPE_MANAGER, and NULL.
gs_manager_request_unlock()
gboolean gs_manager_request_unlock (GSManager * manager)
Definition at line 1920 of file gs-manager.c.
References FALSE, gs_debug, gs_fade_finish(), GS_IS_MANAGER, gs_window_request_unlock(), NULL, GSManager::priv, and TRUE.
Referenced by gs_manager_show_message().
gs_manager_set_active()
gboolean gs_manager_set_active (GSManager * manager, gboolean active)
Definition at line 1893 of file gs-manager.c.
gs_manager_set_cycle_timeout()
void gs_manager_set_cycle_timeout (GSManager * manager, glong cycle_timeout)
Definition at line 768 of file gs-manager.c.
References GS_IS_MANAGER, NULL, and GSManager::priv.
gs_manager_set_keyboard_command()
void gs_manager_set_keyboard_command (GSManager * manager, const char * command)
Definition at line 664 of file gs-manager.c.
References command, GS_IS_MANAGER, gs_window_set_keyboard_command(), NULL, and GSManager::priv.
gs_manager_set_keyboard_enabled()
void gs_manager_set_keyboard_enabled (GSManager * manager, gboolean enabled)
Definition at line 521 of file gs-manager.c.
References FALSE, GS_IS_MANAGER, gs_window_set_keyboard_enabled(), and GSManager::priv.
gs_manager_set_lock_active()
void gs_manager_set_lock_active (GSManager * manager, gboolean lock_active)
Definition at line 454 of file gs-manager.c.
References FALSE, gs_debug, GS_IS_MANAGER, gs_window_set_lock_enabled(), and GSManager::priv.
gs_manager_set_lock_enabled()
void gs_manager_set_lock_enabled (GSManager * manager, gboolean lock_enabled)
Definition at line 491 of file gs-manager.c.
References FALSE, GS_IS_MANAGER, and GSManager::priv.
gs_manager_set_lock_timeout()
void gs_manager_set_lock_timeout (GSManager * manager, glong lock_timeout)
Definition at line 589 of file gs-manager.c.
References GS_IS_MANAGER, NULL, and GSManager::priv.
gs_manager_set_logout_command()
void gs_manager_set_logout_command (GSManager * manager, const char * command)
Definition at line 639 of file gs-manager.c.
References command, GS_IS_MANAGER, gs_window_set_logout_command(), NULL, and GSManager::priv.
gs_manager_set_logout_enabled()
void gs_manager_set_logout_enabled (GSManager * manager, gboolean logout_enabled)
Definition at line 503 of file gs-manager.c.
References FALSE, GS_IS_MANAGER, gs_window_set_logout_enabled(), and GSManager::priv.
gs_manager_set_logout_timeout()
void gs_manager_set_logout_timeout (GSManager * manager, glong logout_timeout)
Definition at line 621 of file gs-manager.c.
References GS_IS_MANAGER, gs_window_set_logout_timeout(), and GSManager::priv.
gs_manager_set_mode()
void gs_manager_set_mode (GSManager * manager, GSSaverMode mode)
Definition at line 377 of file gs-manager.c.
References GS_IS_MANAGER, and GSManager::priv.
gs_manager_set_status_message()
void gs_manager_set_status_message (GSManager * manager, const char * status_message)
Definition at line 689 of file gs-manager.c.
References GS_IS_MANAGER, gs_window_set_status_message(), and GSManager::priv.
gs_manager_set_themes()
void gs_manager_set_themes (GSManager * manager, GSList * themes)
Definition at line 395 of file gs-manager.c.
References GS_IS_MANAGER, NULL, and GSManager::priv.
gs_manager_set_throttled()
void gs_manager_set_throttled (GSManager * manager, gboolean throttled)
Definition at line 412 of file gs-manager.c.
References FALSE, GS_IS_MANAGER, gs_window_clear(), and GSManager::priv.
gs_manager_set_user_switch_enabled()
void gs_manager_set_user_switch_enabled (GSManager * manager, gboolean user_switch_enabled)
Definition at line 539 of file gs-manager.c.
References FALSE, GS_IS_MANAGER, gs_window_set_user_switch_enabled(), and GSManager::priv.
gs_manager_show_message()
void gs_manager_show_message (GSManager * manager, const char * summary, const char * body, const char * icon)
Definition at line 1147 of file gs-manager.c.
References GS_IS_MANAGER, gs_manager_request_unlock(), and gs_window_show_message().