MATE Desktop Environment: gs-monitor.h File Reference
gs-monitor.h File Reference
#include <glib.h>
Classes
struct GSMonitor
struct GSMonitorClass
Macros
#define GS_TYPE_MONITOR (gs_monitor_get_type ())
#define GS_MONITOR(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GS_TYPE_MONITOR, GSMonitor))
#define GS_MONITOR_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), GS_TYPE_MONITOR, GSMonitorClass))
#define GS_IS_MONITOR(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GS_TYPE_MONITOR))
#define GS_IS_MONITOR_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GS_TYPE_MONITOR))
#define GS_MONITOR_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GS_TYPE_MONITOR, GSMonitorClass))
Typedefs
typedef struct GSMonitorPrivate GSMonitorPrivate
Functions
GType gs_monitor_get_type (void)
GSMonitor * gs_monitor_new (void)
gboolean gs_monitor_start (GSMonitor *monitor, GError **error)
void gs_monitor_set_lock_enabled (GSMonitor *monitor, gboolean lock_enabled)
Macro Definition Documentation
GS_IS_MONITOR
#define GS_IS_MONITOR (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GS_TYPE_MONITOR))
Definition at line 34 of file gs-monitor.h.
GS_IS_MONITOR_CLASS
#define GS_IS_MONITOR_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), GS_TYPE_MONITOR))
Definition at line 35 of file gs-monitor.h.
GS_MONITOR
#define GS_MONITOR (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GS_TYPE_MONITOR, GSMonitor))
Definition at line 32 of file gs-monitor.h.
GS_MONITOR_CLASS
#define GS_MONITOR_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), GS_TYPE_MONITOR, GSMonitorClass))
Definition at line 33 of file gs-monitor.h.
GS_MONITOR_GET_CLASS
#define GS_MONITOR_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), GS_TYPE_MONITOR, GSMonitorClass))
Definition at line 36 of file gs-monitor.h.
GS_TYPE_MONITOR
#define GS_TYPE_MONITOR (gs_monitor_get_type ())
Definition at line 31 of file gs-monitor.h.
Typedef Documentation
GSMonitorPrivate
typedef struct GSMonitorPrivate GSMonitorPrivate
Definition at line 38 of file gs-monitor.h.
Function Documentation
gs_monitor_get_type()
GType gs_monitor_get_type (void)
gs_monitor_new()
GSMonitor * gs_monitor_new (void)
Definition at line 464 of file gs-monitor.c.
References GS_MONITOR, GS_TYPE_MONITOR, and NULL.
Referenced by main().
gs_monitor_set_lock_enabled()
void gs_monitor_set_lock_enabled (GSMonitor * monitor, gboolean lock_enabled)
gs_monitor_start()
gboolean gs_monitor_start (GSMonitor * monitor, GError ** error)
Definition at line 473 of file gs-monitor.c.
References error, FALSE, GS_IS_MONITOR, gs_listener_acquire(), GSMonitor::priv, and TRUE.
Referenced by main().