MATE Desktop Environment: gs-theme-manager.c File Reference
gs-theme-manager.c File Reference
#include "config.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <glib-object.h>
#include <matemenu-tree.h>
#include "gs-theme-manager.h"
#include "gs-debug.h"
Functions
GSThemeInfo * gs_theme_info_ref (GSThemeInfo *info)
void gs_theme_info_unref (GSThemeInfo *info)
const char * gs_theme_info_get_id (GSThemeInfo *info)
const char * gs_theme_info_get_name (GSThemeInfo *info)
const char * gs_theme_info_get_exec (GSThemeInfo *info)
GSThemeInfo * gs_theme_manager_lookup_theme_info (GSThemeManager *theme_manager, const char *name)
GSList * gs_theme_manager_get_info_list (GSThemeManager *theme_manager)
GSThemeManager * gs_theme_manager_new (void)
Function Documentation
gs_theme_info_get_exec()
const char * gs_theme_info_get_exec (GSThemeInfo * info)
Definition at line 213 of file gs-theme-manager.c.
References NULL.
gs_theme_info_get_id()
const char * gs_theme_info_get_id (GSThemeInfo * info)
Definition at line 197 of file gs-theme-manager.c.
References NULL.
gs_theme_info_get_name()
const char * gs_theme_info_get_name (GSThemeInfo * info)
Definition at line 205 of file gs-theme-manager.c.
References NULL.
gs_theme_info_ref()
GSThemeInfo * gs_theme_info_ref (GSThemeInfo * info)
Definition at line 170 of file gs-theme-manager.c.
References NULL.
gs_theme_info_unref()
void gs_theme_info_unref (GSThemeInfo * info)
Definition at line 181 of file gs-theme-manager.c.
References NULL.
gs_theme_manager_get_info_list()
GSList * gs_theme_manager_get_info_list (GSThemeManager * theme_manager)
Definition at line 348 of file gs-theme-manager.c.
References GS_IS_THEME_MANAGER, matemenu_tree_get_root_directory(), matemenu_tree_item_unref(), NULL, and GSThemeManager::priv.
gs_theme_manager_lookup_theme_info()
GSThemeInfo * gs_theme_manager_lookup_theme_info (GSThemeManager * theme_manager, const char * name)
Definition at line 298 of file gs-theme-manager.c.
References GS_IS_THEME_MANAGER, id, name, NULL, and GSThemeManager::priv.
gs_theme_manager_new()
GSThemeManager * gs_theme_manager_new (void)
Definition at line 438 of file gs-theme-manager.c.
References GS_THEME_MANAGER, GS_TYPE_THEME_MANAGER, and NULL.
Referenced by main().