MATE Desktop Environment: gs-window-x11.c File Reference
gs-window-x11.c File Reference
#include "config.h"
#include <sys/types.h>
#include <errno.h>
#include <sys/wait.h>
#include <string.h>
#include <gdk/gdkx.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <gtk/gtkx.h>
#include "gs-window.h"
#include "gs-marshal.h"
#include "subprocs.h"
#include "gs-debug.h"
Macros
#define MAX_QUEUED_EVENTS 16
#define INFO_BAR_SECONDS 30
#define MATE_SCREENSAVER_DIALOG_PATH LIBEXECDIR "/mate-screensaver-dialog"
Enumerations
enum { DIALOG_RESPONSE_CANCEL , DIALOG_RESPONSE_OK }
enum { ACTIVITY , DEACTIVATED , LAST_SIGNAL }
enum {
PROP_0 , PROP_OBSCURED , PROP_DIALOG_UP , PROP_LOCK_ENABLED ,
PROP_LOGOUT_ENABLED , PROP_KEYBOARD_ENABLED , PROP_KEYBOARD_COMMAND , PROP_LOGOUT_COMMAND ,
PROP_LOGOUT_TIMEOUT , PROP_MONITOR , PROP_STATUS_MESSAGE
}
Functions
void gs_window_set_background_surface (GSWindow *window, cairo_surface_t *surface)
void gs_window_clear (GSWindow *window)
void gs_window_show_message (GSWindow *window, const char *summary, const char *body, const char *icon)
void gs_window_show (GSWindow *window)
void gs_window_destroy (GSWindow *window)
GdkWindow * gs_window_get_gdk_window (GSWindow *window)
GtkWidget * gs_window_get_drawing_area (GSWindow *window)
void gs_window_request_unlock (GSWindow *window)
void gs_window_cancel_unlock_request (GSWindow *window)
void gs_window_set_lock_enabled (GSWindow *window, gboolean lock_enabled)
GdkDisplay * gs_window_get_display (GSWindow *window)
void gs_window_set_keyboard_enabled (GSWindow *window, gboolean enabled)
void gs_window_set_keyboard_command (GSWindow *window, const char *command)
void gs_window_set_logout_enabled (GSWindow *window, gboolean logout_enabled)
void gs_window_set_user_switch_enabled (GSWindow *window, gboolean user_switch_enabled)
void gs_window_set_logout_timeout (GSWindow *window, glong logout_timeout)
void gs_window_set_logout_command (GSWindow *window, const char *command)
void gs_window_set_status_message (GSWindow *window, const char *status_message)
void gs_window_set_monitor (GSWindow *window, GdkMonitor *monitor)
GdkMonitor * gs_window_get_monitor (GSWindow *window)
gboolean gs_window_is_obscured (GSWindow *window)
gboolean gs_window_is_dialog_up (GSWindow *window)
GSWindow * gs_window_new (GdkMonitor *monitor, gboolean lock_enabled)
Variables
char ** environ
Macro Definition Documentation
INFO_BAR_SECONDS
#define INFO_BAR_SECONDS 30
Definition at line 58 of file gs-window-x11.c.
MATE_SCREENSAVER_DIALOG_PATH
#define MATE_SCREENSAVER_DIALOG_PATH LIBEXECDIR "/mate-screensaver-dialog"
Definition at line 59 of file gs-window-x11.c.
MAX_QUEUED_EVENTS
#define MAX_QUEUED_EVENTS 16
Definition at line 57 of file gs-window-x11.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DIALOG_RESPONSE_CANCEL
DIALOG_RESPONSE_OK
Definition at line 51 of file gs-window-x11.c.
anonymous enum
anonymous enum
Enumerator
ACTIVITY
DEACTIVATED
LAST_SIGNAL
Definition at line 119 of file gs-window-x11.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_OBSCURED
PROP_DIALOG_UP
PROP_LOCK_ENABLED
PROP_LOGOUT_ENABLED
PROP_KEYBOARD_ENABLED
PROP_KEYBOARD_COMMAND
PROP_LOGOUT_COMMAND
PROP_LOGOUT_TIMEOUT
PROP_MONITOR
PROP_STATUS_MESSAGE
Definition at line 126 of file gs-window-x11.c.
Function Documentation
gs_window_cancel_unlock_request()
void gs_window_cancel_unlock_request (GSWindow * window)
Definition at line 1795 of file gs-window-x11.c.
References GS_IS_WINDOW.
Referenced by gs_manager_cancel_unlock_request(), and gs_window_destroy().
gs_window_clear()
void gs_window_clear (GSWindow * window)
Definition at line 269 of file gs-window-x11.c.
References gs_debug, GS_IS_WINDOW, and GSWindow::priv.
Referenced by gs_manager_set_throttled().
gs_window_destroy()
void gs_window_destroy (GSWindow * window)
Definition at line 975 of file gs-window-x11.c.
References GS_IS_WINDOW, and gs_window_cancel_unlock_request().
gs_window_get_display()
GdkDisplay * gs_window_get_display (GSWindow * window)
Definition at line 1822 of file gs-window-x11.c.
References GS_IS_WINDOW, and NULL.
gs_window_get_drawing_area()
GtkWidget * gs_window_get_drawing_area (GSWindow * window)
Definition at line 993 of file gs-window-x11.c.
References GS_IS_WINDOW, NULL, and GSWindow::priv.
gs_window_get_gdk_window()
GdkWindow * gs_window_get_gdk_window (GSWindow * window)
Definition at line 985 of file gs-window-x11.c.
References GS_IS_WINDOW, and NULL.
gs_window_get_monitor()
GdkMonitor * gs_window_get_monitor (GSWindow * window)
Definition at line 1937 of file gs-window-x11.c.
References GS_IS_WINDOW, NULL, and GSWindow::priv.
gs_window_is_dialog_up()
gboolean gs_window_is_dialog_up (GSWindow * window)
Definition at line 2265 of file gs-window-x11.c.
References FALSE, GS_IS_WINDOW, and GSWindow::priv.
gs_window_is_obscured()
gboolean gs_window_is_obscured (GSWindow * window)
Definition at line 2257 of file gs-window-x11.c.
References FALSE, GS_IS_WINDOW, and GSWindow::priv.
gs_window_new()
GSWindow * gs_window_new (GdkMonitor * monitor, gboolean lock_enabled)
Definition at line 2554 of file gs-window-x11.c.
References GS_TYPE_WINDOW, GS_WINDOW, NULL, and TRUE.
gs_window_request_unlock()
void gs_window_request_unlock (GSWindow * window)
Definition at line 1762 of file gs-window-x11.c.
References gs_debug, GS_IS_WINDOW, GSWindow::priv, and TRUE.
Referenced by gs_manager_request_unlock().
gs_window_set_background_surface()
void gs_window_set_background_surface (GSWindow * window, cairo_surface_t * surface)
Definition at line 249 of file gs-window-x11.c.
References GS_IS_WINDOW, NULL, and GSWindow::priv.
gs_window_set_keyboard_command()
void gs_window_set_keyboard_command (GSWindow * window, const char * command)
Definition at line 1839 of file gs-window-x11.c.
References command, GS_IS_WINDOW, NULL, and GSWindow::priv.
Referenced by gs_manager_set_keyboard_command().
gs_window_set_keyboard_enabled()
void gs_window_set_keyboard_enabled (GSWindow * window, gboolean enabled)
Definition at line 1830 of file gs-window-x11.c.
References FALSE, GS_IS_WINDOW, and GSWindow::priv.
Referenced by gs_manager_set_keyboard_enabled().
gs_window_set_lock_enabled()
void gs_window_set_lock_enabled (GSWindow * window, gboolean lock_enabled)
Definition at line 1807 of file gs-window-x11.c.
References FALSE, GS_IS_WINDOW, and GSWindow::priv.
Referenced by gs_manager_set_lock_active().
gs_window_set_logout_command()
void gs_window_set_logout_command (GSWindow * window, const char * command)
Definition at line 1891 of file gs-window-x11.c.
References command, GS_IS_WINDOW, NULL, and GSWindow::priv.
Referenced by gs_manager_set_logout_command().
gs_window_set_logout_enabled()
void gs_window_set_logout_enabled (GSWindow * window, gboolean logout_enabled)
Definition at line 1857 of file gs-window-x11.c.
References FALSE, GS_IS_WINDOW, and GSWindow::priv.
Referenced by gs_manager_set_logout_enabled().
gs_window_set_logout_timeout()
void gs_window_set_logout_timeout (GSWindow * window, glong logout_timeout)
Definition at line 1875 of file gs-window-x11.c.
References GS_IS_WINDOW, and GSWindow::priv.
Referenced by gs_manager_set_logout_timeout().
gs_window_set_monitor()
void gs_window_set_monitor (GSWindow * window, GdkMonitor * monitor)
Definition at line 1919 of file gs-window-x11.c.
References GS_IS_WINDOW, and GSWindow::priv.
gs_window_set_status_message()
void gs_window_set_status_message (GSWindow * window, const char * status_message)
Definition at line 1909 of file gs-window-x11.c.
References GS_IS_WINDOW, and GSWindow::priv.
Referenced by gs_manager_set_status_message().
gs_window_set_user_switch_enabled()
void gs_window_set_user_switch_enabled (GSWindow * window, gboolean user_switch_enabled)
Definition at line 1866 of file gs-window-x11.c.
References FALSE, GS_IS_WINDOW, and GSWindow::priv.
Referenced by gs_manager_set_user_switch_enabled().
gs_window_show()
void gs_window_show (GSWindow * window)
Definition at line 950 of file gs-window-x11.c.
References GS_IS_WINDOW.
gs_window_show_message()
void gs_window_show_message (GSWindow * window, const char * summary, const char * body, const char * icon)
Definition at line 926 of file gs-window-x11.c.
References GS_IS_WINDOW, INFO_BAR_SECONDS, and GSWindow::priv.
Referenced by gs_manager_show_message().
Variable Documentation
environ
char** environ extern