MATE Desktop Environment: gsearchtool-support.h File Reference
gsearchtool-support.h File Reference
#include "gsearchtool.h"
Macros
#define ICON_SIZE 24
Functions
gboolean is_path_hidden (const gchar *path)
gboolean is_quick_search_excluded_path (const gchar *path)
gboolean is_second_scan_excluded_path (const gchar *path)
gboolean compare_regex (const gchar *regex, const gchar *string)
gboolean limit_string_to_x_lines (GString *string, gint x)
gchar * escape_single_quotes (const gchar *string)
gchar * escape_double_quotes (const gchar *string)
gchar * backslash_backslash_characters (const gchar *string)
gchar * backslash_special_characters (const gchar *string)
gchar * remove_mnemonic_character (const gchar *string)
gchar * get_readable_date (const CajaDateFormat date_format_enum, GDateTime *file_time_raw)
gchar * get_file_type_description (const gchar *file, GFileInfo *file_info)
GdkPixbuf * get_file_pixbuf (GSearchWindow *gsearch, GFileInfo *file_info)
gboolean open_file_with_filemanager (GtkWidget *window, const gchar *file)
gboolean open_file_with_application (GtkWidget *window, const gchar *file, GAppInfo *app)
gboolean launch_file (const gchar *file)
gchar * gsearchtool_get_unique_filename (const gchar *path, const gchar *suffix)
GtkWidget * gsearchtool_button_new_with_icon (const gchar *string, const gchar *icon_name)
GSList * gsearchtool_get_columns_order (GtkTreeView *treeview)
void gsearchtool_set_columns_order (GtkTreeView *treeview)
void gsearchtool_get_stored_window_geometry (gint *width, gint *height)
gchar * gsearchtool_get_next_duplicate_name (const gchar *basname)
Macro Definition Documentation
ICON_SIZE
#define ICON_SIZE 24
Definition at line 35 of file gsearchtool-support.h.
Function Documentation
backslash_backslash_characters()
gchar * backslash_backslash_characters (const gchar * string)
Definition at line 335 of file gsearchtool-support.c.
References FALSE, and NULL.
Referenced by build_search_command().
backslash_special_characters()
gchar * backslash_special_characters (const gchar * string)
Definition at line 359 of file gsearchtool-support.c.
References FALSE, and NULL.
Referenced by build_search_command().
compare_regex()
gboolean compare_regex (const gchar * regex, const gchar * string)
Definition at line 238 of file gsearchtool-support.c.
References FALSE, NULL, regex, and TRUE.
escape_double_quotes()
gchar * escape_double_quotes (const gchar * string)
Definition at line 311 of file gsearchtool-support.c.
References FALSE, and NULL.
Referenced by build_search_command().
escape_single_quotes()
gchar * escape_single_quotes (const gchar * string)
Definition at line 287 of file gsearchtool-support.c.
References FALSE, and NULL.
Referenced by build_search_command().
get_file_pixbuf()
GdkPixbuf * get_file_pixbuf (GSearchWindow * gsearch, GFileInfo * file_info)
Definition at line 748 of file gsearchtool-support.c.
References ICON_SIZE, NULL, _GSearchWindow::search_results_filename_hash_table, _GSearchWindow::show_thumbnails, and TRUE.
get_file_type_description()
gchar * get_file_type_description (const gchar * file, GFileInfo * file_info)
Definition at line 438 of file gsearchtool-support.c.
References _, NULL, and TRUE.
get_readable_date()
gchar * get_readable_date (const CajaDateFormat date_format_enum, GDateTime * file_time_raw)
Definition at line 408 of file gsearchtool-support.c.
References _, CAJA_DATE_FORMAT_ISO, and CAJA_DATE_FORMAT_LOCALE.
gsearchtool_button_new_with_icon()
GtkWidget * gsearchtool_button_new_with_icon (const gchar * string, const gchar * icon_name)
Definition at line 959 of file gsearchtool-support.c.
References FALSE, and label.
gsearchtool_get_columns_order()
GSList * gsearchtool_get_columns_order (GtkTreeView * treeview)
Definition at line 981 of file gsearchtool-support.c.
References id, and NULL.
Referenced by columns_changed_cb().
gsearchtool_get_next_duplicate_name()
gchar * gsearchtool_get_next_duplicate_name (const gchar * basname)
Definition at line 1405 of file gsearchtool-support.c.
References NULL.
gsearchtool_get_stored_window_geometry()
void gsearchtool_get_stored_window_geometry (gint * width, gint * height)
Definition at line 1062 of file gsearchtool-support.c.
References DEFAULT_WINDOW_HEIGHT, DEFAULT_WINDOW_WIDTH, MAX, MINIMUM_WINDOW_HEIGHT, MINIMUM_WINDOW_WIDTH, and NULL.
gsearchtool_get_unique_filename()
gchar * gsearchtool_get_unique_filename (const gchar * path, const gchar * suffix)
Definition at line 916 of file gsearchtool-support.c.
References NULL, and TRUE.
gsearchtool_set_columns_order()
void gsearchtool_set_columns_order (GtkTreeView * treeview)
Definition at line 1022 of file gsearchtool-support.c.
References gsearchtool_gtk_tree_view_get_column_with_sort_column_id(), id, item, NULL, and NUM_COLUMNS.
is_path_hidden()
gboolean is_path_hidden (const gchar * path)
Definition at line 54 of file gsearchtool-support.c.
References FALSE, NULL, and TRUE.
is_quick_search_excluded_path()
gboolean is_quick_search_excluded_path (const gchar * path)
Definition at line 84 of file gsearchtool-support.c.
References FALSE, NULL, and TRUE.
Referenced by build_search_command().
is_second_scan_excluded_path()
gboolean is_second_scan_excluded_path (const gchar * path)
Definition at line 161 of file gsearchtool-support.c.
References FALSE, NULL, and TRUE.
launch_file()
gboolean launch_file (const gchar * file)
Definition at line 902 of file gsearchtool-support.c.
References BINARY_EXEC_MIME_TYPE, FALSE, and NULL.
Referenced by open_file_cb().
limit_string_to_x_lines()
gboolean limit_string_to_x_lines (GString * string, gint x)
Definition at line 258 of file gsearchtool-support.c.
References FALSE, and TRUE.
open_file_with_application()
gboolean open_file_with_application (GtkWidget * window, const gchar * file, GAppInfo * app)
Definition at line 856 of file gsearchtool-support.c.
References FALSE, NULL, and TRUE.
open_file_with_filemanager()
gboolean open_file_with_filemanager (GtkWidget * window, const gchar * file)
Definition at line 784 of file gsearchtool-support.c.
References command, FALSE, NULL, and TRUE.
Referenced by open_file_cb(), and open_folder_cb().
remove_mnemonic_character()
gchar * remove_mnemonic_character (const gchar * string)
Definition at line 387 of file gsearchtool-support.c.
References FALSE, NULL, and TRUE.