MATE Desktop Environment: gsearchtool.c File Reference
gsearchtool.c File Reference
#include <fnmatch.h>
#include <string.h>
#include <signal.h>
#include <unistd.h>
#include <errno.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <gdk/gdk.h>
#include <gio/gio.h>
#include "gsearchtool.h"
#include "gsearchtool-callbacks.h"
#include "gsearchtool-support.h"
#include "gsearchtool-entry.h"
Macros
#define FNM_CASEFOLD 0
#define MATE_SEARCH_TOOL_DEFAULT_ICON_SIZE 16
#define MATE_SEARCH_TOOL_REFRESH_DURATION 50000
#define LEFT_LABEL_SPACING " "
Typedefs
typedef struct _GSearchOptionTemplate GSearchOptionTemplate
Enumerations
enum GSearchConstraintType {
SEARCH_CONSTRAINT_TYPE_BOOLEAN , SEARCH_CONSTRAINT_TYPE_NUMERIC , SEARCH_CONSTRAINT_TYPE_TEXT , SEARCH_CONSTRAINT_TYPE_DATE_BEFORE ,
SEARCH_CONSTRAINT_TYPE_DATE_AFTER , SEARCH_CONSTRAINT_TYPE_SEPARATOR , SEARCH_CONSTRAINT_TYPE_NONE
}
enum {
SEARCH_CONSTRAINT_CONTAINS_THE_TEXT , SEARCH_CONSTRAINT_TYPE_SEPARATOR_00 , SEARCH_CONSTRAINT_DATE_MODIFIED_BEFORE , SEARCH_CONSTRAINT_DATE_MODIFIED_AFTER ,
SEARCH_CONSTRAINT_TYPE_SEPARATOR_01 , SEARCH_CONSTRAINT_SIZE_IS_MORE_THAN , SEARCH_CONSTRAINT_SIZE_IS_LESS_THAN , SEARCH_CONSTRAINT_FILE_IS_EMPTY ,
SEARCH_CONSTRAINT_TYPE_SEPARATOR_02 , SEARCH_CONSTRAINT_OWNED_BY_USER , SEARCH_CONSTRAINT_OWNED_BY_GROUP , SEARCH_CONSTRAINT_OWNER_IS_UNRECOGNIZED ,
SEARCH_CONSTRAINT_TYPE_SEPARATOR_03 , SEARCH_CONSTRAINT_FILE_IS_NOT_NAMED , SEARCH_CONSTRAINT_FILE_MATCHES_REGULAR_EXPRESSION , SEARCH_CONSTRAINT_TYPE_SEPARATOR_04 ,
SEARCH_CONSTRAINT_SHOW_HIDDEN_FILES_AND_FOLDERS , SEARCH_CONSTRAINT_FOLLOW_SYMBOLIC_LINKS , SEARCH_CONSTRAINT_SEARCH_OTHER_FILESYSTEMS , SEARCH_CONSTRAINT_MAXIMUM_POSSIBLE
}
Functions
gchar * build_search_command (GSearchWindow *gsearch, gboolean first_pass)
void update_search_counts (GSearchWindow *gsearch)
gboolean tree_model_iter_free_monitor (GtkTreeModel *model, GtkTreePath *path, GtkTreeIter *iter, gpointer data)
void update_constraint_info (GSearchConstraint *constraint, gchar *info)
void set_constraint_selected_state (GSearchWindow *gsearch, gint constraint_id, gboolean state)
void set_constraint_gsettings_boolean (gint constraint_id, gboolean flag)
void spawn_search_command (GSearchWindow *gsearch, gchar *command)
void add_constraint (GSearchWindow *gsearch, gint constraint_id, gchar *value, gboolean show_constraint)
void set_clone_command (GSearchWindow *gsearch, gint *argcp, gchar ***argvp, gpointer client_data, gboolean escape_values)
GType gsearch_window_get_type (void)
int main (int argc, char *argv[])
Variables
struct _GSearchGOptionArguments GSearchGOptionArguments
pid_t locate_database_check_command_pid
Macro Definition Documentation
FNM_CASEFOLD
#define FNM_CASEFOLD 0
Definition at line 31 of file gsearchtool.c.
LEFT_LABEL_SPACING
#define LEFT_LABEL_SPACING " "
Definition at line 56 of file gsearchtool.c.
MATE_SEARCH_TOOL_DEFAULT_ICON_SIZE
#define MATE_SEARCH_TOOL_DEFAULT_ICON_SIZE 16
Definition at line 54 of file gsearchtool.c.
MATE_SEARCH_TOOL_REFRESH_DURATION
#define MATE_SEARCH_TOOL_REFRESH_DURATION 50000
Definition at line 55 of file gsearchtool.c.
Typedef Documentation
GSearchOptionTemplate
typedef struct _GSearchOptionTemplate GSearchOptionTemplate
Definition at line 70 of file gsearchtool.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SEARCH_CONSTRAINT_CONTAINS_THE_TEXT
SEARCH_CONSTRAINT_TYPE_SEPARATOR_00
SEARCH_CONSTRAINT_DATE_MODIFIED_BEFORE
SEARCH_CONSTRAINT_DATE_MODIFIED_AFTER
SEARCH_CONSTRAINT_TYPE_SEPARATOR_01
SEARCH_CONSTRAINT_SIZE_IS_MORE_THAN
SEARCH_CONSTRAINT_SIZE_IS_LESS_THAN
SEARCH_CONSTRAINT_FILE_IS_EMPTY
SEARCH_CONSTRAINT_TYPE_SEPARATOR_02
SEARCH_CONSTRAINT_OWNED_BY_USER
SEARCH_CONSTRAINT_OWNED_BY_GROUP
SEARCH_CONSTRAINT_OWNER_IS_UNRECOGNIZED
SEARCH_CONSTRAINT_TYPE_SEPARATOR_03
SEARCH_CONSTRAINT_FILE_IS_NOT_NAMED
SEARCH_CONSTRAINT_FILE_MATCHES_REGULAR_EXPRESSION
SEARCH_CONSTRAINT_TYPE_SEPARATOR_04
SEARCH_CONSTRAINT_SHOW_HIDDEN_FILES_AND_FOLDERS
SEARCH_CONSTRAINT_FOLLOW_SYMBOLIC_LINKS
SEARCH_CONSTRAINT_SEARCH_OTHER_FILESYSTEMS
SEARCH_CONSTRAINT_MAXIMUM_POSSIBLE
Definition at line 103 of file gsearchtool.c.
GSearchConstraintType
enum GSearchConstraintType
Enumerator
SEARCH_CONSTRAINT_TYPE_BOOLEAN
SEARCH_CONSTRAINT_TYPE_NUMERIC
SEARCH_CONSTRAINT_TYPE_TEXT
SEARCH_CONSTRAINT_TYPE_DATE_BEFORE
SEARCH_CONSTRAINT_TYPE_DATE_AFTER
SEARCH_CONSTRAINT_TYPE_SEPARATOR
SEARCH_CONSTRAINT_TYPE_NONE
Definition at line 60 of file gsearchtool.c.
Function Documentation
add_constraint()
void add_constraint (GSearchWindow * gsearch, gint constraint_id, gchar * value, gboolean show_constraint)
Definition at line 2106 of file gsearchtool.c.
References _GSearchWindow::available_options_selected_list, _GSearchWindow::available_options_vbox, _GSearchConstraint::constraint_id, FALSE, set_constraint_gsettings_boolean(), set_constraint_selected_state(), _GSearchWindow::show_more_options_expander, TRUE, _GSearchWindow::window, _GSearchWindow::window_geometry, and WINDOW_HEIGHT_STEP.
Referenced by add_constraint_cb().
build_search_command()
gchar * build_search_command (GSearchWindow * gsearch, gboolean first_pass)
Definition at line 559 of file gsearchtool.c.
References _GSearchWindow::available_options_selected_list, _GSearchWindow::available_options_vbox, backslash_backslash_characters(), backslash_special_characters(), _GSearchWindow::caja_schema_exists, _GSearchWindow::caja_settings, command, _GSearchWindow::command_details, _GSearchConstraint::constraint_id, _GSearchConstraint::data, error, escape_double_quotes(), escape_single_quotes(), FALSE, GSEARCH_HISTORY_ENTRY, gsearch_history_entry_get_entry(), gsearch_history_entry_prepend_text(), _GSearchCommandDetails::is_command_first_pass, _GSearchCommandDetails::is_command_regex_matching_enabled, _GSearchCommandDetails::is_command_second_pass_enabled, _GSearchCommandDetails::is_command_show_hidden_files_enabled, _GSearchCommandDetails::is_command_using_quick_mode, _GSearchWindow::is_locate_database_available, is_quick_search_excluded_path(), _GSearchWindow::look_in_folder_button, _GSearchCommandDetails::look_in_folder_string, _GSearchWindow::mate_search_tool_settings, _GSearchWindow::name_contains_entry, _GSearchCommandDetails::name_contains_pattern_string, _GSearchCommandDetails::name_contains_regex_string, NULL, _GSearchConstraint::number, regex, SEARCH_CONSTRAINT_TYPE_BOOLEAN, SEARCH_CONSTRAINT_TYPE_DATE_AFTER, SEARCH_CONSTRAINT_TYPE_DATE_BEFORE, SEARCH_CONSTRAINT_TYPE_NUMERIC, SEARCH_CONSTRAINT_TYPE_TEXT, _GSearchWindow::show_thumbnails, _GSearchWindow::show_thumbnails_file_size_limit, SPEED_TRADEOFF_ALWAYS, SPEED_TRADEOFF_LOCAL_ONLY, _GSearchConstraint::text, _GSearchConstraint::time, TRUE, and _GSearchWindow::window.
Referenced by click_find_cb().
gsearch_window_get_type()
GType gsearch_window_get_type (void)
Definition at line 2961 of file gsearchtool.c.
References NULL.
main()
int main (int argc, char * argv[])
Definition at line 3010 of file gsearchtool.c.
References _, egg_sm_client_get(), egg_sm_client_get_option_group(), error, FALSE, GSEARCH_TYPE_WINDOW, GSEARCH_WINDOW, key_press_cb(), MATE_SEARCH_TOOL_ICON, N_, NULL, quit_cb(), quit_session_cb(), save_session_cb(), TRUE, _GSearchWindow::window, and window_state_event_cb().
set_clone_command()
void set_clone_command (GSearchWindow * gsearch, gint * argcp, gchar *** argvp, gpointer client_data, gboolean escape_values)
Definition at line 2502 of file gsearchtool.c.
References _GSearchWindow::available_options_selected_list, _GSearchWindow::available_options_vbox, _GSearchConstraint::constraint_id, _GSearchConstraint::data, GSEARCH_HISTORY_ENTRY, gsearch_history_entry_get_entry(), _GSearchWindow::look_in_folder_button, _GSearchWindow::name_contains_entry, NULL, _GSearchConstraint::number, SEARCH_CONSTRAINT_CONTAINS_THE_TEXT, SEARCH_CONSTRAINT_DATE_MODIFIED_AFTER, SEARCH_CONSTRAINT_DATE_MODIFIED_BEFORE, SEARCH_CONSTRAINT_FILE_IS_EMPTY, SEARCH_CONSTRAINT_FILE_IS_NOT_NAMED, SEARCH_CONSTRAINT_FILE_MATCHES_REGULAR_EXPRESSION, SEARCH_CONSTRAINT_FOLLOW_SYMBOLIC_LINKS, SEARCH_CONSTRAINT_MAXIMUM_POSSIBLE, SEARCH_CONSTRAINT_OWNED_BY_GROUP, SEARCH_CONSTRAINT_OWNED_BY_USER, SEARCH_CONSTRAINT_OWNER_IS_UNRECOGNIZED, SEARCH_CONSTRAINT_SEARCH_OTHER_FILESYSTEMS, SEARCH_CONSTRAINT_SHOW_HIDDEN_FILES_AND_FOLDERS, SEARCH_CONSTRAINT_SIZE_IS_LESS_THAN, SEARCH_CONSTRAINT_SIZE_IS_MORE_THAN, _GSearchConstraint::text, and _GSearchConstraint::time.
Referenced by save_session_cb().
set_constraint_gsettings_boolean()
void set_constraint_gsettings_boolean (gint constraint_id, gboolean flag)
Definition at line 1188 of file gsearchtool.c.
References SEARCH_CONSTRAINT_CONTAINS_THE_TEXT, SEARCH_CONSTRAINT_DATE_MODIFIED_AFTER, SEARCH_CONSTRAINT_DATE_MODIFIED_BEFORE, SEARCH_CONSTRAINT_FILE_IS_EMPTY, SEARCH_CONSTRAINT_FILE_IS_NOT_NAMED, SEARCH_CONSTRAINT_FILE_MATCHES_REGULAR_EXPRESSION, SEARCH_CONSTRAINT_FOLLOW_SYMBOLIC_LINKS, SEARCH_CONSTRAINT_OWNED_BY_GROUP, SEARCH_CONSTRAINT_OWNED_BY_USER, SEARCH_CONSTRAINT_OWNER_IS_UNRECOGNIZED, SEARCH_CONSTRAINT_SEARCH_OTHER_FILESYSTEMS, SEARCH_CONSTRAINT_SHOW_HIDDEN_FILES_AND_FOLDERS, SEARCH_CONSTRAINT_SIZE_IS_LESS_THAN, and SEARCH_CONSTRAINT_SIZE_IS_MORE_THAN.
Referenced by add_constraint(), and remove_constraint_cb().
set_constraint_selected_state()
void set_constraint_selected_state (GSearchWindow * gsearch, gint constraint_id, gboolean state)
Definition at line 1165 of file gsearchtool.c.
References _GSearchWindow::available_options_add_button, _GSearchWindow::available_options_combo_box, _GSearchWindow::available_options_label, FALSE, idx, SEARCH_CONSTRAINT_TYPE_NONE, and TRUE.
Referenced by add_constraint(), and remove_constraint_cb().
spawn_search_command()
void spawn_search_command (GSearchWindow * gsearch, gchar * command)
Definition at line 1850 of file gsearchtool.c.
References _, CAJA_DATE_FORMAT_LOCALE, _GSearchWindow::caja_schema_exists, _GSearchWindow::caja_settings, command, _GSearchWindow::command_details, _GSearchCommandDetails::command_pid, _GSearchCommandDetails::command_status, error, _GSearchCommandDetails::is_command_first_pass, _GSearchCommandDetails::look_in_folder_string, _GSearchCommandDetails::name_contains_pattern_string, _GSearchCommandDetails::name_contains_regex_string, NULL, RUNNING, _GSearchWindow::search_results_date_column, _GSearchWindow::search_results_date_format, _GSearchWindow::search_results_filename_hash_table, _GSearchWindow::search_results_folder_column, _GSearchWindow::search_results_list_store, _GSearchWindow::search_results_pixbuf_hash_table, _GSearchWindow::search_results_size_column, _GSearchWindow::search_results_tree_view, _GSearchWindow::search_results_type_column, tree_model_iter_free_monitor(), TRUE, and _GSearchWindow::window.
Referenced by click_find_cb().
tree_model_iter_free_monitor()
gboolean tree_model_iter_free_monitor (GtkTreeModel * model, GtkTreePath * path, GtkTreeIter * iter, gpointer data)
Definition at line 1079 of file gsearchtool.c.
References COLUMN_MONITOR, FALSE, _GSearchMonitor::handle, and _GSearchMonitor::reference.
Referenced by file_changed_cb(), move_to_trash_cb(), and spawn_search_command().
update_constraint_info()
void update_constraint_info (GSearchConstraint * constraint, gchar * info)
Definition at line 1144 of file gsearchtool.c.
References _, _GSearchConstraint::constraint_id, _GSearchConstraint::data, _GSearchConstraint::number, SEARCH_CONSTRAINT_TYPE_DATE_AFTER, SEARCH_CONSTRAINT_TYPE_DATE_BEFORE, SEARCH_CONSTRAINT_TYPE_NUMERIC, SEARCH_CONSTRAINT_TYPE_TEXT, _GSearchConstraint::text, and _GSearchConstraint::time.
Referenced by constraint_update_info_cb().
update_search_counts()
void update_search_counts (GSearchWindow * gsearch)
Definition at line 1006 of file gsearchtool.c.
References _, ABORTED, _GSearchWindow::command_details, _GSearchCommandDetails::command_status, _GSearchWindow::files_found_label, NULL, _GSearchWindow::search_results_list_store, and _GSearchWindow::window.
Referenced by file_changed_cb(), and move_to_trash_cb().
Variable Documentation
GSearchGOptionArguments
struct _GSearchGOptionArguments GSearchGOptionArguments
locate_database_check_command_pid
pid_t locate_database_check_command_pid
Definition at line 182 of file gsearchtool.c.