MATE Desktop Environment: gsm-app-dialog.c File Reference
gsm-app-dialog.c File Reference
#include "config.h"
#include <glib.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include "gsm-util.h"
#include "gsm-app-dialog.h"
Macros
#define GTKBUILDER_FILE "session-properties.ui"
#define CAPPLET_NAME_ENTRY_WIDGET_NAME "session_properties_name_entry"
#define CAPPLET_COMMAND_ENTRY_WIDGET_NAME "session_properties_command_entry"
#define CAPPLET_COMMENT_ENTRY_WIDGET_NAME "session_properties_comment_entry"
#define CAPPLET_DELAY_SPIN_WIDGET_NAME "session_properties_delay_spin"
#define CAPPLET_BROWSE_WIDGET_NAME "session_properties_browse_button"
#define UNUSED_VARIABLE
Enumerations
enum {
PROP_0 , PROP_NAME , PROP_COMMAND , PROP_COMMENT ,
PROP_DELAY
}
Functions
const char * gsm_app_dialog_get_name (GsmAppDialog *dialog)
const char * gsm_app_dialog_get_command (GsmAppDialog *dialog)
const char * gsm_app_dialog_get_comment (GsmAppDialog *dialog)
guint gsm_app_dialog_get_delay (GsmAppDialog *dialog)
GtkWidget * gsm_app_dialog_new (const char *name, const char *command, const char *comment, guint delay)
gboolean gsm_app_dialog_run (GsmAppDialog *dialog, char **name_p, char **command_p, char **comment_p, guint *delay_p)
Macro Definition Documentation
CAPPLET_BROWSE_WIDGET_NAME
#define CAPPLET_BROWSE_WIDGET_NAME "session_properties_browse_button"
Definition at line 38 of file gsm-app-dialog.c.
CAPPLET_COMMAND_ENTRY_WIDGET_NAME
#define CAPPLET_COMMAND_ENTRY_WIDGET_NAME "session_properties_command_entry"
Definition at line 35 of file gsm-app-dialog.c.
CAPPLET_COMMENT_ENTRY_WIDGET_NAME
#define CAPPLET_COMMENT_ENTRY_WIDGET_NAME "session_properties_comment_entry"
Definition at line 36 of file gsm-app-dialog.c.
CAPPLET_DELAY_SPIN_WIDGET_NAME
#define CAPPLET_DELAY_SPIN_WIDGET_NAME "session_properties_delay_spin"
Definition at line 37 of file gsm-app-dialog.c.
CAPPLET_NAME_ENTRY_WIDGET_NAME
#define CAPPLET_NAME_ENTRY_WIDGET_NAME "session_properties_name_entry"
Definition at line 34 of file gsm-app-dialog.c.
GTKBUILDER_FILE
#define GTKBUILDER_FILE "session-properties.ui"
Definition at line 32 of file gsm-app-dialog.c.
UNUSED_VARIABLE
#define UNUSED_VARIABLE
Definition at line 43 of file gsm-app-dialog.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_NAME
PROP_COMMAND
PROP_COMMENT
PROP_DELAY
Definition at line 60 of file gsm-app-dialog.c.
Function Documentation
gsm_app_dialog_get_command()
const char * gsm_app_dialog_get_command (GsmAppDialog * dialog)
Definition at line 374 of file gsm-app-dialog.c.
References NULL.
Referenced by gsm_app_dialog_run().
gsm_app_dialog_get_comment()
const char * gsm_app_dialog_get_comment (GsmAppDialog * dialog)
Definition at line 381 of file gsm-app-dialog.c.
References NULL.
Referenced by gsm_app_dialog_run().
gsm_app_dialog_get_delay()
guint gsm_app_dialog_get_delay (GsmAppDialog * dialog)
Definition at line 388 of file gsm-app-dialog.c.
Referenced by gsm_app_dialog_run().
gsm_app_dialog_get_name()
const char * gsm_app_dialog_get_name (GsmAppDialog * dialog)
Definition at line 367 of file gsm-app-dialog.c.
References NULL.
Referenced by gsm_app_dialog_run().
gsm_app_dialog_new()
GtkWidget * gsm_app_dialog_new (const char * name, const char * command, const char * comment, guint delay)
Definition at line 497 of file gsm-app-dialog.c.
References command, comment, delay, GSM_TYPE_APP_DIALOG, name, and NULL.
gsm_app_dialog_run()
gboolean gsm_app_dialog_run (GsmAppDialog * dialog, char ** name_p, char ** command_p, char ** comment_p, guint * delay_p)
Definition at line 515 of file gsm-app-dialog.c.
References _, comment, delay, error, FALSE, gsm_app_dialog_get_command(), gsm_app_dialog_get_comment(), gsm_app_dialog_get_delay(), gsm_app_dialog_get_name(), gsm_util_text_is_blank(), name, NULL, and TRUE.