MATE Desktop Environment: gsm-util.h File Reference
gsm-util.h File Reference
#include <glib.h>
#include <gtk/gtk.h>
Macros
#define IS_STRING_EMPTY(x) ((x)==NULL||(x)[0]=='\0')
Functions
gchar ** gsm_get_screen_locker_command (void)
char * gsm_util_find_desktop_file_for_app_name (const char *app_name, char **dirs)
gchar * gsm_util_get_empty_tmp_session_dir (void)
const char * gsm_util_get_saved_session_dir (void)
gchar ** gsm_util_get_app_dirs (void)
gchar ** gsm_util_get_autostart_dirs (void)
gchar ** gsm_util_get_desktop_dirs (void)
gboolean gsm_util_text_is_blank (const char *str)
void gsm_util_init_error (gboolean fatal, const char *format,...)
char * gsm_util_generate_startup_id (void)
gboolean gsm_util_export_activation_environment (GError **error)
void gsm_util_setenv (const char *variable, const char *value)
GtkWidget * gsm_util_dialog_add_button (GtkDialog *dialog, const gchar *button_text, const gchar *icon_name, gint response_id)
Macro Definition Documentation
IS_STRING_EMPTY
#define IS_STRING_EMPTY (x) ((x)==NULL||(x)[0]=='\0')
Definition at line 31 of file gsm-util.h.
Function Documentation
gsm_get_screen_locker_command()
gchar ** gsm_get_screen_locker_command (void)
Definition at line 43 of file gsm-util.c.
References NULL.
gsm_util_dialog_add_button()
GtkWidget * gsm_util_dialog_add_button (GtkDialog * dialog, const gchar * button_text, const gchar * icon_name, gint response_id)
Definition at line 728 of file gsm-util.c.
References TRUE.
gsm_util_export_activation_environment()
gboolean gsm_util_export_activation_environment (GError ** error)
Definition at line 512 of file gsm-util.c.
References connection, ENV_NAME_PATTERN, ENV_VALUE_PATTERN, error, FALSE, NULL, and TRUE.
Referenced by main().
gsm_util_find_desktop_file_for_app_name()
char * gsm_util_find_desktop_file_for_app_name (const char * app_name, char ** dirs)
Definition at line 70 of file gsm-util.c.
References gsm_util_get_app_dirs(), name, and NULL.
gsm_util_generate_startup_id()
char * gsm_util_generate_startup_id (void)
gsm_util_generate_startup_id:
Generates a new SM client ID.
Return value: an SM client ID.
Definition at line 411 of file gsm-util.c.
References NULL.
Referenced by gsm_manager_register_client().
gsm_util_get_app_dirs()
gchar ** gsm_util_get_app_dirs (void)
Definition at line 272 of file gsm-util.c.
References FALSE, and NULL.
Referenced by gsm_util_find_desktop_file_for_app_name(), and gsm_util_get_desktop_dirs().
gsm_util_get_autostart_dirs()
gchar ** gsm_util_get_autostart_dirs (void)
Definition at line 239 of file gsm-util.c.
References FALSE, and NULL.
Referenced by gsm_util_get_desktop_dirs(), and gsp_app_manager_fill().
gsm_util_get_desktop_dirs()
gchar ** gsm_util_get_desktop_dirs (void)
Definition at line 299 of file gsm-util.c.
References gsm_util_get_app_dirs(), gsm_util_get_autostart_dirs(), gsm_util_get_saved_session_dir(), and NULL.
gsm_util_get_empty_tmp_session_dir()
gchar * gsm_util_get_empty_tmp_session_dir (void)
Definition at line 171 of file gsm-util.c.
References ensure_dir_exists(), and NULL.
Referenced by gsm_session_save().
gsm_util_get_saved_session_dir()
const char * gsm_util_get_saved_session_dir (void)
Definition at line 208 of file gsm-util.c.
References ensure_dir_exists(), FALSE, NULL, and TRUE.
Referenced by gsm_session_save(), and gsm_util_get_desktop_dirs().
gsm_util_init_error()
void gsm_util_init_error (gboolean fatal, const char * format, ...)
gsm_util_init_error: @fatal: whether or not the error is fatal to the login session @format: printf-style error message format ...: error message args
Displays the error message to the user. If @fatal is TRUE, gsm will exit after displaying the message.
This should be called for major errors that occur before the session is up and running. (Notably, it positions the dialog box itself, since no window manager will be running yet.)
Definition at line 367 of file gsm-util.c.
References _, and NULL.
Referenced by gsm_manager_initialization_error(), and main().
gsm_util_setenv()
void gsm_util_setenv (const char * variable, const char * value)
Definition at line 702 of file gsm-util.c.
References error, NULL, and TRUE.
Referenced by gsm_manager_setenv(), and main().
gsm_util_text_is_blank()
gboolean gsm_util_text_is_blank (const char * str)
Definition at line 336 of file gsm-util.c.
References FALSE, NULL, and TRUE.
Referenced by gsm_app_dialog_run(), gsp_app_create(), and gsp_app_new().