MATE Desktop Environment: gsm-store.c File Reference
gsm-store.c File Reference
#include "config.h"
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <glib-object.h>
#include "gsm-store.h"
Enumerations
enum { ADDED , REMOVED , LAST_SIGNAL }
enum { PROP_0 , PROP_LOCKED }
Functions
GQuark gsm_store_error_quark (void)
guint gsm_store_size (GsmStore *store)
gboolean gsm_store_remove (GsmStore *store, const char *id)
void gsm_store_foreach (GsmStore *store, GsmStoreFunc func, gpointer user_data)
GObject * gsm_store_find (GsmStore *store, GsmStoreFunc predicate, gpointer user_data)
GObject * gsm_store_lookup (GsmStore *store, const char *id)
guint gsm_store_foreach_remove (GsmStore *store, GsmStoreFunc func, gpointer user_data)
void gsm_store_clear (GsmStore *store)
gboolean gsm_store_add (GsmStore *store, const char *id, GObject *object)
void gsm_store_set_locked (GsmStore *store, gboolean locked)
gboolean gsm_store_get_locked (GsmStore *store)
GsmStore * gsm_store_new (void)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ADDED
REMOVED
LAST_SIGNAL
Definition at line 42 of file gsm-store.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_LOCKED
Definition at line 48 of file gsm-store.c.
Function Documentation
gsm_store_add()
gboolean gsm_store_add (GsmStore * store, const char * id, GObject * object)
Definition at line 238 of file gsm-store.c.
References ADDED, FALSE, NULL, signals, and TRUE.
Referenced by gsm_manager_inhibit(), and gsm_manager_register_client().
gsm_store_clear()
void gsm_store_clear (GsmStore * store)
Definition at line 226 of file gsm-store.c.
References gsm_store_foreach_remove(), and NULL.
gsm_store_error_quark()
GQuark gsm_store_error_quark (void)
Definition at line 60 of file gsm-store.c.
gsm_store_find()
GObject * gsm_store_find (GsmStore * store, GsmStoreFunc predicate, gpointer user_data)
Definition at line 126 of file gsm-store.c.
References NULL, and user_data.
Referenced by gsm_manager_add_autostart_app(), gsm_manager_is_autostart_condition_handled(), gsm_manager_is_inhibited(), gsm_manager_register_client(), and gsm_manager_uninhibit().
gsm_store_foreach()
void gsm_store_foreach (GsmStore * store, GsmStoreFunc func, gpointer user_data)
Definition at line 111 of file gsm-store.c.
References NULL, and user_data.
Referenced by gsm_manager_get_clients(), gsm_manager_get_inhibitors(), and gsm_session_save().
gsm_store_foreach_remove()
guint gsm_store_foreach_remove (GsmStore * store, GsmStoreFunc func, gpointer user_data)
Definition at line 183 of file gsm-store.c.
References data, id, NULL, REMOVED, signals, and user_data.
Referenced by gsm_store_clear().
gsm_store_get_locked()
gboolean gsm_store_get_locked (GsmStore * store)
Definition at line 278 of file gsm-store.c.
References FALSE.
gsm_store_lookup()
GObject * gsm_store_lookup (GsmStore * store, const char * id)
Definition at line 144 of file gsm-store.c.
References NULL.
Referenced by gsm_manager_unregister_client().
gsm_store_new()
GsmStore * gsm_store_new (void)
Definition at line 422 of file gsm-store.c.
References GSM_TYPE_STORE, and NULL.
Referenced by main().
gsm_store_remove()
gboolean gsm_store_remove (GsmStore * store, const char * id)
Definition at line 79 of file gsm-store.c.
References FALSE, NULL, REMOVED, signals, and TRUE.
Referenced by gsm_manager_uninhibit().
gsm_store_set_locked()
void gsm_store_set_locked (GsmStore * store, gboolean locked)
Definition at line 267 of file gsm-store.c.
gsm_store_size()
guint gsm_store_size (GsmStore * store)
Definition at line 71 of file gsm-store.c.
Referenced by gsm_manager_is_inhibited().