MATE Desktop Environment: gsp-app-manager.c File Reference
gsp-app-manager.c File Reference
#include <string.h>
#include "gsm-util.h"
#include "gsp-app.h"
#include "gsp-app-manager.h"
Enumerations
enum { ADDED , REMOVED , LAST_SIGNAL }
Functions
const char * gsp_app_manager_get_dir (GspAppManager *manager, unsigned int index)
void gsp_app_manager_fill (GspAppManager *manager)
void gsp_app_manager_add (GspAppManager *manager, GspApp *app)
GspApp * gsp_app_manager_find_app_with_basename (GspAppManager *manager, const char *basename)
GspAppManager * gsp_app_manager_get (void)
GSList * gsp_app_manager_get_apps (GspAppManager *manager)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ADDED
REMOVED
LAST_SIGNAL
Definition at line 43 of file gsp-app-manager.c.
Function Documentation
gsp_app_manager_add()
void gsp_app_manager_add (GspAppManager * manager, GspApp * app)
Definition at line 553 of file gsp-app-manager.c.
Referenced by gsp_app_copy_desktop_file(), and gsp_app_create().
gsp_app_manager_fill()
void gsp_app_manager_fill (GspAppManager * manager)
Definition at line 492 of file gsp-app-manager.c.
References gsm_util_get_autostart_dirs(), and NULL.
gsp_app_manager_find_app_with_basename()
GspApp * gsp_app_manager_find_app_with_basename (GspAppManager * manager, const char * basename)
Definition at line 572 of file gsp-app-manager.c.
References gsp_app_get_basename(), and NULL.
Referenced by gsp_app_new(), and msm_desktop_app_dialog_new().
gsp_app_manager_get()
GspAppManager * gsp_app_manager_get (void)
Definition at line 598 of file gsp-app-manager.c.
References GSP_TYPE_APP_MANAGER, and NULL.
Referenced by gsp_app_copy_desktop_file(), gsp_app_create(), and gsp_app_new().
gsp_app_manager_get_apps()
GSList * gsp_app_manager_get_apps (GspAppManager * manager)
Definition at line 611 of file gsp-app-manager.c.
References NULL.
gsp_app_manager_get_dir()
const char * gsp_app_manager_get_dir (GspAppManager * manager, unsigned int index)
Definition at line 222 of file gsp-app-manager.c.
References NULL.