MATE Desktop Environment: gvc-applet.h File Reference
gvc-applet.h File Reference
#include <glib.h>
#include <glib-object.h>
Classes
struct _GvcApplet
struct _GvcAppletClass
Macros
#define GVC_APPLET_DBUS_NAME "org.mate.VolumeControlApplet"
#define APPLET_ICON "multimedia-volume-control"
#define GVC_TYPE_APPLET (gvc_applet_get_type ())
#define GVC_APPLET(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GVC_TYPE_APPLET, GvcApplet))
#define GVC_APPLET_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), GVC_TYPE_APPLET, GvcAppletClass))
#define GVC_IS_APPLET(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GVC_TYPE_APPLET))
#define GVC_IS_APPLET_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GVC_TYPE_APPLET))
#define GVC_APPLET_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GVC_TYPE_APPLET, GvcAppletClass))
Typedefs
typedef struct _GvcApplet GvcApplet
typedef struct _GvcAppletClass GvcAppletClass
typedef struct _GvcAppletPrivate GvcAppletPrivate
Functions
GType gvc_applet_get_type (void)
GvcApplet * gvc_applet_new (void)
void gvc_applet_start (GvcApplet *applet)
gboolean gvc_applet_fill (GvcApplet *applet, MatePanelApplet *applet_widget)
Macro Definition Documentation
APPLET_ICON
#define APPLET_ICON "multimedia-volume-control"
Definition at line 33 of file gvc-applet.h.
GVC_APPLET
#define GVC_APPLET (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GVC_TYPE_APPLET, GvcApplet))
Definition at line 36 of file gvc-applet.h.
GVC_APPLET_CLASS
#define GVC_APPLET_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), GVC_TYPE_APPLET, GvcAppletClass))
Definition at line 37 of file gvc-applet.h.
GVC_APPLET_DBUS_NAME
#define GVC_APPLET_DBUS_NAME "org.mate.VolumeControlApplet"
Definition at line 32 of file gvc-applet.h.
GVC_APPLET_GET_CLASS
#define GVC_APPLET_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), GVC_TYPE_APPLET, GvcAppletClass))
Definition at line 40 of file gvc-applet.h.
GVC_IS_APPLET
#define GVC_IS_APPLET (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GVC_TYPE_APPLET))
Definition at line 38 of file gvc-applet.h.
GVC_IS_APPLET_CLASS
#define GVC_IS_APPLET_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), GVC_TYPE_APPLET))
Definition at line 39 of file gvc-applet.h.
GVC_TYPE_APPLET
#define GVC_TYPE_APPLET (gvc_applet_get_type ())
Definition at line 35 of file gvc-applet.h.
Typedef Documentation
GvcApplet
typedef struct _GvcApplet GvcApplet
Definition at line 42 of file gvc-applet.h.
GvcAppletClass
typedef struct _GvcAppletClass GvcAppletClass
Definition at line 43 of file gvc-applet.h.
GvcAppletPrivate
typedef struct _GvcAppletPrivate GvcAppletPrivate
Definition at line 44 of file gvc-applet.h.
Function Documentation
gvc_applet_fill()
gboolean gvc_applet_fill (GvcApplet * applet, MatePanelApplet * applet_widget)
Definition at line 512 of file gvc-applet.c.
References _, APPLET_ICON, gvc_stream_applet_icon_set_orient(), gvc_stream_applet_icon_set_size(), MATE_PANEL_APPLET_EXPAND_MINOR, mate_panel_applet_get_orient(), mate_panel_applet_get_size(), mate_panel_applet_set_flags(), mate_panel_applet_setup_menu(), NULL, _GvcApplet::priv, and TRUE.
gvc_applet_get_type()
GType gvc_applet_get_type (void)
gvc_applet_new()
GvcApplet * gvc_applet_new (void)
Definition at line 431 of file gvc-applet.c.
References GVC_TYPE_APPLET, and NULL.
gvc_applet_start()
void gvc_applet_start (GvcApplet * applet)
Definition at line 350 of file gvc-applet.c.
References FALSE, GVC_IS_APPLET, mate_mixer_context_open(), _GvcApplet::priv, and TRUE.