MATE Desktop Environment: helper_proto.c File Reference
helper_proto.c File Reference
#include "config.h"
#include <stdlib.h>
#include "helper_proto.h"
Functions
ssize_t read_msg (int fd, char *buf, size_t length)
int read_prompt (int fd, char *buf, size_t *length)
ssize_t write_msg (int fd, const void *buf, size_t length)
int write_prompt (int fd, int msg_type, const void *buf, size_t length)
Function Documentation
read_msg()
ssize_t read_msg (int fd, char * buf, size_t length)
Definition at line 57 of file helper_proto.c.
References HELPER_IO_ERR, HELPER_LENGTH_READ_ERR, HELPER_MSG_READ_ERR, and HELPER_TOO_LONG_ERR.
Referenced by read_prompt().
read_prompt()
int read_prompt (int fd, char * buf, size_t * length)
Definition at line 87 of file helper_proto.c.
References HELPER_IO_ERR, HELPER_TYPE_READ_ERR, and read_msg().
write_msg()
ssize_t write_msg (int fd, const void * buf, size_t length)
Definition at line 129 of file helper_proto.c.
References HELPER_IO_ERR, HELPER_LENGTH_WRITE_ERR, and HELPER_MSG_WRITE_ERR.
Referenced by write_prompt().
write_prompt()
int write_prompt (int fd, int msg_type, const void * buf, size_t length)
Definition at line 154 of file helper_proto.c.
References HELPER_IO_ERR, HELPER_TYPE_WRITE_ERR, and write_msg().