MATE Desktop Environment: helper_proto.h File Reference
helper_proto.h File Reference
#include "config.h"
#include <stdlib.h>
Macros
#define HELPER_IO_ERR -1
#define HELPER_LENGTH_READ_ERR -2
#define HELPER_TOO_LONG_ERR -3
#define HELPER_MSG_READ_ERR -4
#define HELPER_TYPE_READ_ERR -5
#define HELPER_LENGTH_WRITE_ERR -6
#define HELPER_MSG_WRITE_ERR -7
#define HELPER_TYPE_WRITE_ERR -8
Functions
ssize_t read_msg (int fd, char *buf, size_t length)
int read_prompt (int fd, char *buf, size_t *length)
ssize_t write_msg (int fd, const void *buf, size_t length)
int write_prompt (int fd, int msg_type, const void *buf, size_t length)
Macro Definition Documentation
HELPER_IO_ERR
#define HELPER_IO_ERR -1
Definition at line 36 of file helper_proto.h.
HELPER_LENGTH_READ_ERR
#define HELPER_LENGTH_READ_ERR -2
Definition at line 38 of file helper_proto.h.
HELPER_LENGTH_WRITE_ERR
#define HELPER_LENGTH_WRITE_ERR -6
Definition at line 46 of file helper_proto.h.
HELPER_MSG_READ_ERR
#define HELPER_MSG_READ_ERR -4
Definition at line 40 of file helper_proto.h.
HELPER_MSG_WRITE_ERR
#define HELPER_MSG_WRITE_ERR -7
Definition at line 47 of file helper_proto.h.
HELPER_TOO_LONG_ERR
#define HELPER_TOO_LONG_ERR -3
Definition at line 39 of file helper_proto.h.
HELPER_TYPE_READ_ERR
#define HELPER_TYPE_READ_ERR -5
Definition at line 41 of file helper_proto.h.
HELPER_TYPE_WRITE_ERR
#define HELPER_TYPE_WRITE_ERR -8
Definition at line 48 of file helper_proto.h.
Function Documentation
read_msg()
ssize_t read_msg (int fd, char * buf, size_t length)
Definition at line 57 of file helper_proto.c.
References HELPER_IO_ERR, HELPER_LENGTH_READ_ERR, HELPER_MSG_READ_ERR, and HELPER_TOO_LONG_ERR.
Referenced by read_prompt().
read_prompt()
int read_prompt (int fd, char * buf, size_t * length)
Definition at line 87 of file helper_proto.c.
References HELPER_IO_ERR, HELPER_TYPE_READ_ERR, and read_msg().
write_msg()
ssize_t write_msg (int fd, const void * buf, size_t length)
Definition at line 129 of file helper_proto.c.
References HELPER_IO_ERR, HELPER_LENGTH_WRITE_ERR, and HELPER_MSG_WRITE_ERR.
Referenced by write_prompt().
write_prompt()
int write_prompt (int fd, int msg_type, const void * buf, size_t length)
Definition at line 154 of file helper_proto.c.
References HELPER_IO_ERR, HELPER_TYPE_WRITE_ERR, and write_msg().