MATE Desktop Environment: interface.h File Reference
interface.h File Reference
#include <glib.h>
#include <gtk/gtk.h>
#include "procman.h"
Functions
void create_main_window (ProcData *data)
void update_sensitivity (ProcData *data)
void block_priority_changed_handlers (ProcData *data, bool block)
void do_popup_menu (ProcData *data, GdkEventButton *event)
GtkWidget * make_title_label (const char *text)
Function Documentation
block_priority_changed_handlers()
void block_priority_changed_handlers (ProcData * data, bool block)
Definition at line 644 of file interface.cpp.
References action, cb_renice(), and data.
Referenced by cb_row_selected().
create_main_window()
void create_main_window (ProcData * data)
Definition at line 459 of file interface.cpp.
References action, ProcData::action_group, ProcData::app, cb_app_delete(), cb_change_current_page(), cb_radio_processes(), cb_renice(), cb_switch_page(), ProcData::config, create_disk_view(), ProcConfig::current_tab, FALSE, ProcConfig::height, ProcConfig::maximized, NORMAL_PRIORITY, ProcData::notebook, NULL, ProcConfig::show_tree, ProcData::statusbar, ProcData::tip_message_cid, ProcData::uimanager, ProcConfig::whose_process, ProcConfig::width, ProcConfig::xpos, and ProcConfig::ypos.
do_popup_menu()
void do_popup_menu (ProcData * data, GdkEventButton * event)
Definition at line 593 of file interface.cpp.
References NULL, and ProcData::popup_menu.
Referenced by cb_tree_button_pressed(), and cb_tree_popup_menu().
make_title_label()
GtkWidget * make_title_label (const char * text)
Definition at line 227 of file interface.cpp.
References label, and TRUE.
update_sensitivity()
void update_sensitivity (ProcData * data)
Definition at line 599 of file interface.cpp.
References action, data, PROCMAN_TAB_PROCESSES, and update_sensitivity().
Referenced by cb_change_current_page(), cb_row_selected(), proctable_clear_tree(), terminal_search_dialog_new(), and update_sensitivity().