MATE Desktop Environment: keybindings.c File Reference
keybindings.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include "keybindings.h"
#include "workspace.h"
#include "errors.h"
#include "edge-resistance.h"
#include "ui.h"
#include "frame-private.h"
#include "place.h"
#include "prefs.h"
#include "effects.h"
#include "util.h"
#include <gio/gio.h>
#include <X11/keysym.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "all-keybindings.h"
#include "../include/util.h"
Macros
#define _GNU_SOURCE
#define _XOPEN_SOURCE /* for putenv() */
#define keybind(name, handler, param, flags)
#define keybind(name, handler, param, flags) { #name, handler, param, flags },
#define SMALL_INCREMENT 1
#define NORMAL_INCREMENT 10
#define SMALL_INCREMENT 1
#define NORMAL_INCREMENT 10
#define RENAME_WORKSPACE_BUFSIZE 512
Typedefs
typedef void(* MetaKeyHandlerFunc) (MetaDisplay *display, MetaScreen *screen, MetaWindow *window, XEvent *event, MetaKeyBinding *binding)
Functions
void meta_display_process_mapping_event (MetaDisplay *display, XEvent *event)
void meta_display_init_keys (MetaDisplay *display)
void meta_display_shutdown_keys (MetaDisplay *display)
void meta_screen_grab_keys (MetaScreen *screen)
void meta_screen_ungrab_keys (MetaScreen *screen)
void meta_window_grab_keys (MetaWindow *window)
void meta_window_ungrab_keys (MetaWindow *window)
gboolean meta_screen_grab_all_keys (MetaScreen *screen, guint32 timestamp)
void meta_screen_ungrab_all_keys (MetaScreen *screen, guint32 timestamp)
gboolean meta_window_grab_all_keys (MetaWindow *window, guint32 timestamp)
void meta_window_ungrab_all_keys (MetaWindow *window, guint32 timestamp)
void meta_display_process_key_event (MetaDisplay *display, MetaWindow *window, XEvent *event)
void meta_set_keybindings_disabled (gboolean setting)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 26 of file keybindings.c.
_XOPEN_SOURCE
#define _XOPEN_SOURCE /* for putenv() */
Definition at line 27 of file keybindings.c.
keybind [1/2]
#define keybind (name, handler, param, flags)
Value:
static void \
handler (MetaDisplay    *display,\
         MetaScreen     *screen,\
         MetaWindow     *window,\
         XEvent         *event,\
         MetaKeyBinding *binding);
Definition at line 63 of file keybindings.c.
keybind [2/2]
#define keybind (name, handler, param, flags) { #name, handler, param, flags },
Definition at line 63 of file keybindings.c.
NORMAL_INCREMENT [1/2]
#define NORMAL_INCREMENT 10
NORMAL_INCREMENT [2/2]
#define NORMAL_INCREMENT 10
RENAME_WORKSPACE_BUFSIZE
#define RENAME_WORKSPACE_BUFSIZE 512
Definition at line 3644 of file keybindings.c.
SMALL_INCREMENT [1/2]
#define SMALL_INCREMENT 1
SMALL_INCREMENT [2/2]
#define SMALL_INCREMENT 1
Typedef Documentation
MetaKeyHandlerFunc
typedef void(* MetaKeyHandlerFunc) (MetaDisplay *display, MetaScreen *screen, MetaWindow *window, XEvent *event, MetaKeyBinding *binding)
Definition at line 56 of file keybindings.c.
Function Documentation
meta_display_init_keys()
void meta_display_init_keys (MetaDisplay * display)
Definition at line 588 of file keybindings.c.
References _MetaDisplay::hyper_mask, _MetaDisplay::ignored_modifier_mask, _MetaDisplay::key_bindings, _MetaDisplay::keymap, _MetaDisplay::keysyms_per_keycode, _MetaDisplay::max_keycode, META_DEBUG_KEYBINDINGS, _MetaDisplay::meta_mask, meta_prefs_add_listener(), _MetaDisplay::min_keycode, _MetaDisplay::modmap, _MetaDisplay::n_key_bindings, NULL, _MetaDisplay::num_lock_mask, _MetaDisplay::scroll_lock_mask, _MetaDisplay::super_mask, and _MetaDisplay::xdisplay.
Referenced by meta_display_open().
meta_display_process_key_event()
void meta_display_process_key_event (MetaDisplay * display, MetaWindow * window, XEvent * event)
Definition at line 1280 of file keybindings.c.
References _MetaScreen::all_keys_grabbed, _MetaWindow::all_keys_grabbed, _MetaWindow::desc, _MetaDisplay::grab_op, _MetaDisplay::grab_screen, _MetaDisplay::grab_window, _MetaDisplay::key_bindings, META_DEBUG_KEYBINDINGS, meta_display_end_grab_op(), meta_display_lookup_x_window(), meta_display_screen_for_root(), meta_display_screen_for_xwindow(), META_GRAB_OP_KEYBOARD_ESCAPING_DOCK, META_GRAB_OP_KEYBOARD_ESCAPING_GROUP, META_GRAB_OP_KEYBOARD_ESCAPING_NORMAL, META_GRAB_OP_KEYBOARD_ESCAPING_NORMAL_ALL_WORKSPACES, META_GRAB_OP_KEYBOARD_MOVING, META_GRAB_OP_KEYBOARD_RESIZING_E, META_GRAB_OP_KEYBOARD_RESIZING_N, META_GRAB_OP_KEYBOARD_RESIZING_NE, META_GRAB_OP_KEYBOARD_RESIZING_NW, META_GRAB_OP_KEYBOARD_RESIZING_S, META_GRAB_OP_KEYBOARD_RESIZING_SE, META_GRAB_OP_KEYBOARD_RESIZING_SW, META_GRAB_OP_KEYBOARD_RESIZING_UNKNOWN, META_GRAB_OP_KEYBOARD_RESIZING_W, META_GRAB_OP_KEYBOARD_TABBING_DOCK, META_GRAB_OP_KEYBOARD_TABBING_GROUP, META_GRAB_OP_KEYBOARD_TABBING_NORMAL, META_GRAB_OP_KEYBOARD_TABBING_NORMAL_ALL_WORKSPACES, META_GRAB_OP_KEYBOARD_WORKSPACE_MOVING, META_GRAB_OP_KEYBOARD_WORKSPACE_SWITCHING, META_GRAB_OP_MOVING, META_GRAB_OP_NONE, META_GRAB_OP_RESIZING_E, META_GRAB_OP_RESIZING_N, META_GRAB_OP_RESIZING_NE, META_GRAB_OP_RESIZING_NW, META_GRAB_OP_RESIZING_S, META_GRAB_OP_RESIZING_SE, META_GRAB_OP_RESIZING_SW, META_GRAB_OP_RESIZING_W, meta_ui_window_is_widget(), _MetaDisplay::n_key_bindings, NULL, TRUE, _MetaScreen::ui, and _MetaDisplay::xdisplay.
meta_display_process_mapping_event()
void meta_display_process_mapping_event (MetaDisplay * display, XEvent * event)
Definition at line 513 of file keybindings.c.
References FALSE, META_DEBUG_KEYBINDINGS, and TRUE.
meta_display_shutdown_keys()
void meta_display_shutdown_keys (MetaDisplay * display)
Definition at line 636 of file keybindings.c.
References _MetaDisplay::key_bindings, _MetaDisplay::keymap, meta_prefs_remove_listener(), meta_XFree, and _MetaDisplay::modmap.
Referenced by meta_display_close().
meta_screen_grab_all_keys()
gboolean meta_screen_grab_all_keys (MetaScreen * screen, guint32 timestamp)
Definition at line 958 of file keybindings.c.
References _MetaScreen::all_keys_grabbed, _MetaScreen::display, FALSE, _MetaScreen::keys_grabbed, META_DEBUG_KEYBINDINGS, meta_screen_grab_keys(), meta_screen_ungrab_keys(), TRUE, and _MetaScreen::xroot.
Referenced by meta_display_begin_grab_op().
meta_screen_grab_keys()
void meta_screen_grab_keys (MetaScreen * screen)
Definition at line 802 of file keybindings.c.
References _MetaScreen::all_keys_grabbed, _MetaScreen::display, FALSE, _MetaDisplay::key_bindings, _MetaScreen::keys_grabbed, _MetaDisplay::n_key_bindings, TRUE, and _MetaScreen::xroot.
Referenced by meta_screen_grab_all_keys(), meta_screen_new(), and meta_screen_ungrab_all_keys().
meta_screen_ungrab_all_keys()
void meta_screen_ungrab_all_keys (MetaScreen * screen, guint32 timestamp)
Definition at line 980 of file keybindings.c.
References _MetaScreen::all_keys_grabbed, _MetaScreen::display, FALSE, _MetaScreen::keys_grabbed, and meta_screen_grab_keys().
Referenced by meta_display_end_grab_op().
meta_screen_ungrab_keys()
void meta_screen_ungrab_keys (MetaScreen * screen)
Definition at line 819 of file keybindings.c.
References _MetaScreen::display, FALSE, _MetaScreen::keys_grabbed, and _MetaScreen::xroot.
Referenced by meta_screen_free(), and meta_screen_grab_all_keys().
meta_set_keybindings_disabled()
void meta_set_keybindings_disabled (gboolean setting)
Definition at line 3599 of file keybindings.c.
References META_DEBUG_KEYBINDINGS.
Referenced by main().
meta_window_grab_all_keys()
gboolean meta_window_grab_all_keys (MetaWindow * window, guint32 timestamp)
Definition at line 995 of file keybindings.c.
References _MetaWindow::all_keys_grabbed, _MetaWindow::desc, _MetaWindow::display, FALSE, _MetaWindow::frame, _MetaWindow::grab_on_frame, _MetaWindow::keys_grabbed, META_DEBUG_FOCUS, META_DEBUG_KEYBINDINGS, meta_window_focus(), meta_window_ungrab_keys(), NULL, TRUE, _MetaFrame::xwindow, and _MetaWindow::xwindow.
Referenced by meta_display_begin_grab_op().
meta_window_grab_keys()
void meta_window_grab_keys (MetaWindow * window)
Definition at line 829 of file keybindings.c.
References _MetaWindow::all_keys_grabbed, _MetaWindow::display, FALSE, _MetaWindow::frame, _MetaWindow::grab_on_frame, _MetaDisplay::key_bindings, _MetaWindow::keys_grabbed, META_WINDOW_DOCK, _MetaDisplay::n_key_bindings, NULL, TRUE, _MetaWindow::type, _MetaFrame::xwindow, and _MetaWindow::xwindow.
Referenced by meta_window_destroy_frame(), meta_window_ensure_frame(), meta_window_new_with_attrs(), and meta_window_ungrab_all_keys().
meta_window_ungrab_all_keys()
void meta_window_ungrab_all_keys (MetaWindow * window, guint32 timestamp)
Definition at line 1031 of file keybindings.c.
References _MetaWindow::all_keys_grabbed, _MetaWindow::display, FALSE, _MetaWindow::grab_on_frame, _MetaWindow::keys_grabbed, and meta_window_grab_keys().
Referenced by meta_display_end_grab_op().
meta_window_ungrab_keys()
void meta_window_ungrab_keys (MetaWindow * window)
Definition at line 864 of file keybindings.c.
References _MetaWindow::display, FALSE, _MetaWindow::frame, _MetaWindow::grab_on_frame, _MetaWindow::keys_grabbed, NULL, _MetaFrame::xwindow, and _MetaWindow::xwindow.
Referenced by meta_window_free(), and meta_window_grab_all_keys().