MATE Desktop Environment: launcher.c File Reference
launcher.c File Reference
#include <config.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <dirent.h>
#include <string.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <libpanel-util/panel-error.h>
#include <libpanel-util/panel-glib.h>
#include <libpanel-util/panel-keyfile.h>
#include <libpanel-util/panel-launch.h>
#include <libpanel-util/panel-show.h>
#include "launcher.h"
#include "button-widget.h"
#include "panel-util.h"
#include "panel-config-global.h"
#include "panel-profile.h"
#include "panel-toplevel.h"
#include "panel-a11y.h"
#include "panel-globals.h"
#include "panel-lockdown.h"
#include "panel-ditem-editor.h"
#include "panel-icon-names.h"
#include "panel-schemas.h"
Enumerations
enum { TARGET_ICON_INTERNAL , TARGET_URI_LIST }
Functions
void launcher_launch (Launcher *launcher, const gchar *action)
void launcher_properties_destroy (Launcher *launcher)
void panel_launcher_delete (Launcher *launcher)
void launcher_properties (Launcher *launcher)
void launcher_load_from_gsettings (PanelWidget *panel_widget, gboolean locked, int position, const char *id)
void ask_about_launcher (const char *file, PanelWidget *panel, int pos, gboolean exactpos)
void panel_launcher_create_from_info (PanelToplevel *toplevel, int position, gboolean exec_info, const char *exec_or_uri, const char *name, const char *comment, const char *icon)
void panel_launcher_create_with_id (const char *toplevel_id, int position, const char *location)
void panel_launcher_create (PanelToplevel *toplevel, int position, const char *location)
gboolean panel_launcher_create_copy (PanelToplevel *toplevel, int position, const char *location)
Launcher * find_launcher (const char *path)
void panel_launcher_set_dnd_enabled (Launcher *launcher, gboolean dnd_enabled)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TARGET_ICON_INTERNAL
TARGET_URI_LIST
Definition at line 366 of file launcher.c.
Function Documentation
ask_about_launcher()
void ask_about_launcher (const char * file, PanelWidget * panel, int pos, gboolean exactpos)
Definition at line 989 of file launcher.c.
References _, NULL, PANEL_DITEM_EDITOR, panel_ditem_editor_get_key_file(), panel_ditem_editor_new(), panel_ditem_editor_sync_display(), panel_ditem_register_save_uri_func(), panel_key_file_set_string, panel_lockdown_get_disable_command_line(), and panel_widget_register_open_dialog().
find_launcher()
Launcher * find_launcher (const char * path)
Definition at line 1169 of file launcher.c.
References AppletInfo::data, Launcher::key_file, Launcher::location, mate_panel_applet_list_applets(), NULL, PANEL_OBJECT_LAUNCHER, and AppletInfo::type.
launcher_launch()
void launcher_launch (Launcher * launcher, const gchar * action)
Definition at line 134 of file launcher.c.
References _, action, error, error_dialog(), Launcher::key_file, NULL, panel_error_dialog(), panel_key_file_get_string, panel_launch_key_file(), TRUE, and type.
launcher_load_from_gsettings()
void launcher_load_from_gsettings (PanelWidget * panel_widget, gboolean locked, int position, const char * id)
Definition at line 917 of file launcher.c.
References _, FALSE, Launcher::info, mate_panel_applet_get_callback(), NULL, PANEL_OBJECT_LAUNCHER_LOCATION_KEY, PANEL_OBJECT_PATH, PANEL_OBJECT_SCHEMA, AppletUserMenu::sensitive, TRUE, and AppletInfo::user_menu.
launcher_properties()
void launcher_properties (Launcher * launcher)
Definition at line 799 of file launcher.c.
References _, Launcher::button, Launcher::info, Launcher::key_file, Launcher::location, NULL, PANEL_DITEM_EDITOR, panel_ditem_editor_new(), panel_ditem_register_save_uri_func(), PANEL_WIDGET, panel_widget_register_open_dialog(), Launcher::prop_dialog, and AppletInfo::widget.
launcher_properties_destroy()
void launcher_properties_destroy (Launcher * launcher)
Definition at line 236 of file launcher.c.
References NULL, and Launcher::prop_dialog.
panel_launcher_create()
void panel_launcher_create (PanelToplevel * toplevel, int position, const char * location)
Definition at line 1126 of file launcher.c.
References panel_launcher_create_with_id(), and panel_profile_get_toplevel_id().
Referenced by panel_launcher_create_copy(), and panel_launcher_create_from_info().
panel_launcher_create_copy()
gboolean panel_launcher_create_copy (PanelToplevel * toplevel, int position, const char * location)
Definition at line 1136 of file launcher.c.
References dest, NULL, panel_launcher_create(), panel_launcher_get_filename(), panel_launcher_get_gfile(), and panel_make_unique_desktop_uri().
panel_launcher_create_from_info()
void panel_launcher_create_from_info (PanelToplevel * toplevel, int position, gboolean exec_info, const char * exec_or_uri, const char * name, const char * comment, const char * icon)
Definition at line 1032 of file launcher.c.
References _, comment, error, name, NULL, panel_error_dialog(), panel_key_file_new_desktop(), panel_key_file_set_locale_string(), panel_key_file_set_string, panel_key_file_to_file(), panel_launcher_create(), panel_make_unique_desktop_uri(), and TRUE.
panel_launcher_create_with_id()
void panel_launcher_create_with_id (const char * toplevel_id, int position, const char * location)
Definition at line 1082 of file launcher.c.
References FALSE, id, NULL, PANEL_GSETTINGS_OBJECTS, panel_launcher_get_filename(), PANEL_OBJECT_LAUNCHER, PANEL_OBJECT_LAUNCHER_LOCATION_KEY, PANEL_OBJECT_PATH, PANEL_OBJECT_SCHEMA, panel_profile_add_to_list(), and panel_profile_prepare_object_with_id().
Referenced by panel_launcher_create().
panel_launcher_delete()
void panel_launcher_delete (Launcher * launcher)
Definition at line 264 of file launcher.c.
References error, Launcher::location, NULL, panel_launcher_get_gfile(), and panel_launcher_is_in_personal_path().
Referenced by mate_panel_applet_clean().
panel_launcher_set_dnd_enabled()
void panel_launcher_set_dnd_enabled (Launcher * launcher, gboolean dnd_enabled)
Definition at line 1196 of file launcher.c.
References Launcher::button, BUTTON_WIDGET, button_widget_get_surface(), FALSE, TARGET_ICON_INTERNAL, TARGET_URI_LIST, and TRUE.