MATE Desktop Environment: lexer.c File Reference
lexer.c File Reference
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include "lexer.h"
#include "parserfunc.h"
#include "mp-equation.h"
Functions
void l_insert_all_tokens (LexerState *state)
LexerState * l_create_lexer (const gchar *input, struct parser_state *parent)
void l_destroy_lexer (LexerState *state)
LexerToken * l_get_next_token (LexerState *state)
void l_roll_back (LexerState *state)
Function Documentation
l_create_lexer()
LexerState * l_create_lexer (const gchar * input, struct parser_state * parent)
Definition at line 547 of file lexer.c.
References LexerState::next_token, NULL, LexerState::parent, pl_create_scanner(), LexerState::prelexer, LexerState::token_count, and LexerState::tokens.
Referenced by p_create_parser().
l_destroy_lexer()
void l_destroy_lexer (LexerState * state)
Definition at line 562 of file lexer.c.
References pl_destroy_scanner(), LexerState::prelexer, LexerToken::string, LexerState::token_count, and LexerState::tokens.
Referenced by p_destroy_parser().
l_get_next_token()
LexerToken * l_get_next_token (LexerState * state)
Definition at line 576 of file lexer.c.
References LexerState::next_token, LexerState::token_count, and LexerState::tokens.
Referenced by p_parse().
l_insert_all_tokens()
void l_insert_all_tokens (LexerState * state)
Definition at line 531 of file lexer.c.
References NULL, PL_EOS, and LexerToken::token_type.
Referenced by p_parse().
l_roll_back()
void l_roll_back (LexerState * state)
Definition at line 586 of file lexer.c.
References LexerState::next_token.