MATE Desktop Environment: parser.h File Reference
parser.h File Reference
#include <libxml/xmlreader.h>
#include "mateweather-timezone.h"
Classes
struct MateWeatherParser
Functions
MateWeatherParser * mateweather_parser_new (gboolean use_regions)
void mateweather_parser_free (MateWeatherParser *parser)
char * mateweather_parser_get_value (MateWeatherParser *parser)
char * mateweather_parser_get_localized_value (MateWeatherParser *parser)
MateWeatherTimezone ** mateweather_timezones_parse_xml (MateWeatherParser *parser)
Function Documentation
mateweather_parser_free()
void mateweather_parser_free (MateWeatherParser * parser)
Definition at line 237 of file libmateweather/libmateweather/parser.c.
References MateWeatherParser::xml.
Referenced by mateweather_location_new_world(), and mateweather_parser_new().
mateweather_parser_get_localized_value()
char * mateweather_parser_get_localized_value (MateWeatherParser * parser)
mateweather_parser_get_localized_value: @parser: a MateWeatherParser
Looks at the name of the element @parser is currently pointing to, and returns the content of either that node, or a following node with the same name but an "xml:lang" attribute naming one of the locale languages. Leaves @parser pointing to the next node after the last consecutive element with the same name as the original element.
Return value: the localized (or unlocalized) text, as a libxml-allocated string, or NULL if the node is empty.
Definition at line 90 of file libmateweather/libmateweather/parser.c.
References MateWeatherParser::locales, name, NULL, and MateWeatherParser::xml.
mateweather_parser_get_value()
char * mateweather_parser_get_value (MateWeatherParser * parser)
mateweather_parser_get_value: @parser: a MateWeatherParser
Gets the text of the element whose start tag @parser is pointing to. Leaves @parser pointing at the next node after the element's end tag.
Return value: the text of the current node, as a libxml-allocated string, or NULL if the node is empty.
Definition at line 45 of file libmateweather/libmateweather/parser.c.
References NULL, and MateWeatherParser::xml.
mateweather_parser_new()
MateWeatherParser * mateweather_parser_new (gboolean use_regions)
Definition at line 157 of file libmateweather/libmateweather/parser.c.
References MateWeatherParser::locales, mateweather_parser_free(), NULL, MateWeatherParser::use_regions, MateWeatherParser::xml, MateWeatherParser::year_end, and MateWeatherParser::year_start.
Referenced by mateweather_location_new_world().
mateweather_timezones_parse_xml()
MateWeatherTimezone ** mateweather_timezones_parse_xml (MateWeatherParser * parser)
Definition at line 211 of file mateweather-timezone.c.
References FALSE, mateweather_timezone_unref(), NULL, TRUE, and MateWeatherParser::xml.