MATE Desktop Environment: libmateui-access.h File Reference
libmateui-access.h File Reference
#include <glib-object.h>
#include <atk/atk.h>
#include <gtk/gtk.h>
Typedefs
typedef void(* _AccessibilityClassInitFn) (AtkObjectClass *klass)
Functions
void _add_atk_name_desc (GtkWidget *widget, gchar *name, gchar *desc)
void _add_atk_description (GtkWidget *widget, gchar *desc)
void _add_atk_relation (GtkWidget *widget1, GtkWidget *widget2, AtkRelationType w1_to_w2, AtkRelationType w2_to_w1)
AtkObject * _accessibility_get_atk_object (gpointer object)
AtkObject * _accessibility_for_object (gpointer object)
gpointer _accessibility_get_gobject (AtkObject *object)
AtkObject * _accessibility_set_atk_object_return (gpointer object, AtkObject *atk_object)
GType _accessibility_create_derived_type (const char *type_name, GType existing_gobject_with_proxy, _AccessibilityClassInitFn class_init)
Typedef Documentation
_AccessibilityClassInitFn
typedef void(* _AccessibilityClassInitFn) (AtkObjectClass *klass)
Definition at line 39 of file libmateui-access.h.
Function Documentation
_accessibility_create_derived_type()
GType _accessibility_create_derived_type (const char * type_name, GType existing_gobject_with_proxy, _AccessibilityClassInitFn class_init)
_accessibility_create_derived_type: @type_name: the name for the new accessible type eg. CajaIconCanvasItemAccessible @existing_gobject_with_proxy: the GType of an object that has a registered factory that manufactures the type we want to inherit from. ie. to inherit from a GailCanvasItem we need to pass MATE_TYPE_CANVAS_ITEM - since GailCanvasItem is registered against that type. @class_init: the init function to run for this class
This should be run to register the type, it can subsequently be run with the same name and will not re-register it, but simply return it.
NB. to do instance init, you prolly want to override AtkObject::initialize
Return value: the registered type, or 0 on failure.
Definition at line 234 of file libmateui-access.c.
References type.
_accessibility_for_object()
AtkObject * _accessibility_for_object (gpointer object)
_accessibilty_for_object: @object: a GObject of some sort
gets an AtkObject associated with a GObject and if it doesn't exist creates a suitable accessible object.
Return value: an associated accessible.
Definition at line 156 of file libmateui-access.c.
_accessibility_get_atk_object()
AtkObject * _accessibility_get_atk_object (gpointer object)
_accessibility_get_atk_object: @object: a GObject of some sort
gets an AtkObject associated with a GObject
Return value: the associated accessible if one exists or NULL
Definition at line 141 of file libmateui-access.c.
Referenced by mate_icon_list_clear(), and mate_icon_list_remove().
_accessibility_get_gobject()
gpointer _accessibility_get_gobject (AtkObject * object)
_accessibility_get_gobject: @object: an AtkObject
gets the GObject associated with the AtkObject, for which @object provides accessibility support.
Return value: the accessible's associated GObject
Definition at line 174 of file libmateui-access.c.
_accessibility_set_atk_object_return()
AtkObject * _accessibility_set_atk_object_return (gpointer object, AtkObject * atk_object)
_accessibility_set_atk_object_return: @object: a GObject @atk_object: it's AtkObject
used to register and return a new accessible object for something
Return value: @atk_object.
Definition at line 201 of file libmateui-access.c.
_add_atk_description()
void _add_atk_description (GtkWidget * widget, gchar * desc)
Definition at line 66 of file libmateui-access.c.
References _add_atk_name_desc(), and NULL.
_add_atk_name_desc()
void _add_atk_name_desc (GtkWidget * widget, gchar * name, gchar * desc)
Definition at line 48 of file libmateui-access.c.
References name.
Referenced by _add_atk_description().
_add_atk_relation()
void _add_atk_relation (GtkWidget * widget1, GtkWidget * widget2, AtkRelationType w1_to_w2, AtkRelationType w2_to_w1)
Definition at line 73 of file libmateui-access.c.
Referenced by mate_icon_selection_show_icons().