MATE Desktop Environment: list.h File Reference
list.h File Reference
Classes
struct _List
Typedefs
typedef struct _List List
typedef void(* Callback) (void *data, void *user_data)
typedef int(* ListFindFunc) (void *data, void *user_data)
Functions
void list_foreach (List *list, Callback func, void *user_data)
List * list_prepend (List *list, void *data)
void list_free (List *list)
List * list_find (List *list, ListFindFunc func, void *user_data)
List * list_remove (List *list, const void *data)
int list_length (List *list)
List * list_copy (List *list)
Typedef Documentation
Callback
typedef void(* Callback) (void *data, void *user_data)
Definition at line 28 of file list.h.
List
typedef struct _List List
Definition at line 27 of file list.h.
ListFindFunc
typedef int(* ListFindFunc) (void *data, void *user_data)
Definition at line 38 of file list.h.
Function Documentation
list_copy()
List * list_copy (List * list)
Definition at line 123 of file mate-settings-daemon/plugins/clipboard/list.c.
References _List::data, _List::next, and NULL.
Referenced by caja_application_close_all_navigation_windows(), and caja_application_close_all_spatial_windows().
list_find()
List * list_find (List * list, ListFindFunc func, void * user_data)
Definition at line 68 of file mate-settings-daemon/plugins/clipboard/list.c.
References _List::data, _List::next, and user_data.
list_foreach()
void list_foreach (List * list, Callback func, void * user_data)
Definition at line 29 of file mate-settings-daemon/plugins/clipboard/list.c.
References _List::data, _List::next, and user_data.
Referenced by msd_clipboard_manager_stop().
list_free()
void list_free (List * list)
Definition at line 55 of file mate-settings-daemon/plugins/clipboard/list.c.
References _List::next.
Referenced by msd_clipboard_manager_stop().
list_length()
int list_length (List * list)
Definition at line 110 of file mate-settings-daemon/plugins/clipboard/list.c.
References _List::next.
list_prepend()
List * list_prepend (List * list, void * data)
Definition at line 42 of file mate-settings-daemon/plugins/clipboard/list.c.
References data, _List::data, and _List::next.
list_remove()
List * list_remove (List * list, const void * data)
Definition at line 84 of file mate-settings-daemon/plugins/clipboard/list.c.
References data, _List::data, _List::next, and NULL.