MATE Desktop Environment: load-graph.c File Reference
load-graph.c File Reference
#include <config.h>
#include <stdio.h>
#include <sys/stat.h>
#include <unistd.h>
#include <signal.h>
#include <dirent.h>
#include <string.h>
#include <time.h>
#include <glib.h>
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <mate-panel-applet.h>
#include <mate-panel-applet-gsettings.h>
#include <math.h>
#include "global.h"
Functions
void load_graph_unalloc (LoadGraph *g)
LoadGraph * load_graph_new (MultiloadApplet *ma, guint n, const gchar *label, gint id, guint speed, guint size, gboolean visible, const gchar *name, LoadGraphDataFunc get_data)
void load_graph_start (LoadGraph *g)
void load_graph_stop (LoadGraph *g)
Function Documentation
load_graph_new()
LoadGraph * load_graph_new (MultiloadApplet * ma, guint n, const gchar * label, gint id, guint speed, guint size, gboolean visible, const gchar * name, LoadGraphDataFunc get_data)
Definition at line 410 of file load-graph.c.
References _MultiloadApplet::applet, LoadGraph::disp, FALSE, id, LoadGraph::main_widget, mate_panel_applet_get_orient(), mate_panel_applet_get_size(), MatePanelAppletOrient, LoadGraph::n, name, NULL, LoadGraph::speed, LoadGraph::timer_index, and TRUE.
load_graph_start()
void load_graph_start (LoadGraph * g)
Definition at line 493 of file load-graph.c.
References LoadGraph::speed, and LoadGraph::timer_index.
Referenced by cb_change_current_page(), and multiload_applet_refresh().
load_graph_stop()
void load_graph_stop (LoadGraph * g)
Definition at line 507 of file load-graph.c.
References LoadGraph::timer_index.
Referenced by cb_change_current_page(), and multiload_applet_refresh().
load_graph_unalloc()
void load_graph_unalloc (LoadGraph * g)
Definition at line 255 of file load-graph.c.
References LoadGraph::data, LoadGraph::draw_width, FALSE, GRAPH_SIZE_KEY, GRAPH_SIZE_MAX, GRAPH_SIZE_MIN, and NULL.
Referenced by multiload_applet_refresh().