MATE Desktop Environment: logview-manager.c File Reference
logview-manager.c File Reference
#include "logview-manager.h"
#include <glib/gi18n.h>
#include "logview-prefs.h"
#include "logview-marshal.h"
#include "logview-app.h"
Enumerations
enum { LOG_ADDED , LOG_CLOSED , ACTIVE_CHANGED , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (LogviewManager, logview_manager, G_TYPE_OBJECT)
LogviewManager * logview_manager_get (void)
void logview_manager_set_active_log (LogviewManager *manager, LogviewLog *log)
LogviewLog * logview_manager_get_active_log (LogviewManager *manager)
void logview_manager_add_log_from_gfile (LogviewManager *manager, GFile *file, gboolean set_active)
void logview_manager_add_logs_from_name_list (LogviewManager *manager, GSList *names, const char *active)
void logview_manager_add_logs_from_names (LogviewManager *manager, char **names, const gchar *active)
int logview_manager_get_log_count (LogviewManager *manager)
LogviewLog * logview_manager_get_if_loaded (LogviewManager *manager, char *uri)
void logview_manager_close_active_log (LogviewManager *manager)
gboolean logview_manager_log_is_active (LogviewManager *manager, LogviewLog *log)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
LOG_ADDED
LOG_CLOSED
ACTIVE_CHANGED
LAST_SIGNAL
Definition at line 33 of file logview-manager.c.
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (LogviewManager , logview_manager , G_TYPE_OBJECT)
logview_manager_add_log_from_gfile()
void logview_manager_add_log_from_gfile (LogviewManager * manager, GFile * file, gboolean set_active)
Definition at line 313 of file logview-manager.c.
References FALSE, and LOGVIEW_IS_MANAGER.
logview_manager_add_logs_from_name_list()
void logview_manager_add_logs_from_name_list (LogviewManager * manager, GSList * names, const char * active)
Definition at line 323 of file logview-manager.c.
References LOGVIEW_IS_MANAGER, NULL, op, and TRUE.
logview_manager_add_logs_from_names()
void logview_manager_add_logs_from_names (LogviewManager * manager, char ** names, const gchar * active)
Definition at line 342 of file logview-manager.c.
References LOGVIEW_IS_MANAGER, NULL, op, and TRUE.
Referenced by logview_app_initialize().
logview_manager_close_active_log()
void logview_manager_close_active_log (LogviewManager * manager)
Definition at line 386 of file logview-manager.c.
References LOG_CLOSED, LOGVIEW_IS_MANAGER, logview_log_get_gfile(), logview_log_get_uri(), logview_prefs_get(), logview_prefs_remove_stored_log(), NULL, _LogviewManager::priv, and signals.
logview_manager_get()
LogviewManager * logview_manager_get (void)
Definition at line 264 of file logview-manager.c.
References LOGVIEW_TYPE_MANAGER, and NULL.
logview_manager_get_active_log()
LogviewLog * logview_manager_get_active_log (LogviewManager * manager)
Definition at line 303 of file logview-manager.c.
References LOGVIEW_IS_MANAGER, NULL, and _LogviewManager::priv.
logview_manager_get_if_loaded()
LogviewLog * logview_manager_get_if_loaded (LogviewManager * manager, char * uri)
Definition at line 370 of file logview-manager.c.
References LOGVIEW_IS_MANAGER, NULL, and _LogviewManager::priv.
logview_manager_get_log_count()
int logview_manager_get_log_count (LogviewManager * manager)
Definition at line 362 of file logview-manager.c.
References LOGVIEW_IS_MANAGER, and _LogviewManager::priv.
logview_manager_log_is_active()
gboolean logview_manager_log_is_active (LogviewManager * manager, LogviewLog * log)
Definition at line 417 of file logview-manager.c.
References LOGVIEW_IS_MANAGER, and _LogviewManager::priv.
logview_manager_set_active_log()
void logview_manager_set_active_log (LogviewManager * manager, LogviewLog * log)
Definition at line 274 of file logview-manager.c.
References ACTIVE_CHANGED, LOGVIEW_IS_MANAGER, logview_log_get_gfile(), logview_prefs_get(), logview_prefs_store_active_logfile(), NULL, _LogviewManager::priv, and signals.