MATE Desktop Environment: logview-window.c File Reference
logview-window.c File Reference
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <glib/gi18n.h>
#include "logview-window.h"
#include "logview-loglist.h"
#include "logview-findbar.h"
#include "logview-about.h"
#include "logview-prefs.h"
#include "logview-manager.h"
#include "logview-filter-manager.h"
Macros
#define APP_NAME _("System Log Viewer")
#define SEARCH_START_MARK "lw-search-start-mark"
#define SEARCH_END_MARK "lw-search-end-mark"
#define DEFAULT_LOGVIEW_FONT "Monospace 10"
Functions
G_DEFINE_TYPE_WITH_PRIVATE (LogviewWindow, logview_window, GTK_TYPE_WINDOW)
GtkWidget * logview_window_new ()
void logview_window_add_error (LogviewWindow *window, const char *primary, const char *secondary)
void logview_window_add_errors (LogviewWindow *window, GPtrArray *errors)
Macro Definition Documentation
APP_NAME
#define APP_NAME _("System Log Viewer")
Definition at line 41 of file logview-window.c.
DEFAULT_LOGVIEW_FONT
#define DEFAULT_LOGVIEW_FONT "Monospace 10"
Definition at line 245 of file logview-window.c.
SEARCH_END_MARK
#define SEARCH_END_MARK "lw-search-end-mark"
Definition at line 43 of file logview-window.c.
SEARCH_START_MARK
#define SEARCH_START_MARK "lw-search-start-mark"
Definition at line 42 of file logview-window.c.
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (LogviewWindow , logview_window , GTK_TYPE_WINDOW)
logview_window_add_error()
void logview_window_add_error (LogviewWindow * window, const char * primary, const char * secondary)
Definition at line 1536 of file logview-window.c.
References LOGVIEW_IS_WINDOW, and _LogviewWindow::priv.
Referenced by logview_app_add_error(), and logview_app_add_errors().
logview_window_add_errors()
void logview_window_add_errors (LogviewWindow * window, GPtrArray * errors)
Definition at line 1555 of file logview-window.c.
References _, FALSE, LOGVIEW_IS_WINDOW, NULL, and _LogviewWindow::priv.
Referenced by logview_app_add_errors().
logview_window_new()
GtkWidget * logview_window_new (void)
Definition at line 1522 of file logview-window.c.
References LOGVIEW_TYPE_WINDOW, NULL, and _LogviewWindow::priv.
Variable Documentation
action
const gchar* action
Definition at line 1178 of file logview-window.c.
keyval
guint keyval
Definition at line 897 of file logview-window.c.
modifier
GdkModifierType modifier
Definition at line 898 of file logview-window.c.
widget_id
const gchar* widget_id
Definition at line 899 of file logview-window.c.