MATE Desktop Environment: logview-log.h File Reference
logview-log.h File Reference
#include <glib-object.h>
#include <gio/gio.h>
Classes
struct _LogviewLog
struct _LogviewLogClass
Macros
#define LOGVIEW_TYPE_LOG logview_log_get_type()
#define LOGVIEW_LOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LOGVIEW_TYPE_LOG, LogviewLog))
#define LOGVIEW_LOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LOGVIEW_TYPE_LOG, LogviewLogClass))
#define LOGVIEW_IS_LOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LOGVIEW_TYPE_LOG))
#define LOGVIEW_IS_LOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LOGVIEW_TYPE_LOG))
#define LOGVIEW_LOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LOGVIEW_TYPE_LOG, LogviewLogClass))
#define LOGVIEW_ERROR_QUARK g_quark_from_static_string ("logview-error")
Typedefs
typedef struct _LogviewLog LogviewLog
typedef struct _LogviewLogClass LogviewLogClass
typedef struct _LogviewLogPrivate LogviewLogPrivate
typedef void(* LogviewCreateCallback) (LogviewLog *log, GError *error, gpointer user_data)
typedef void(* LogviewNewLinesCallback) (LogviewLog *log, const char **lines, GSList *new_days, GError *error, gpointer user_data)
Enumerations
enum LogviewErrorEnum {
LOGVIEW_ERROR_FAILED , LOGVIEW_ERROR_PERMISSION_DENIED , LOGVIEW_ERROR_ZLIB , LOGVIEW_ERROR_NOT_SUPPORTED ,
LOGVIEW_ERROR_NOT_A_LOG
}
Functions
GType logview_log_get_type (void)
void logview_log_create (const char *filename, LogviewCreateCallback callback, gpointer user_data)
void logview_log_create_from_gfile (GFile *file, LogviewCreateCallback callback, gpointer user_data)
void logview_log_read_new_lines (LogviewLog *log, GCancellable *cancellable, LogviewNewLinesCallback callback, gpointer user_data)
const char * logview_log_get_display_name (LogviewLog *log)
time_t logview_log_get_timestamp (LogviewLog *log)
goffset logview_log_get_file_size (LogviewLog *log)
const char ** logview_log_get_cached_lines (LogviewLog *log)
guint logview_log_get_cached_lines_number (LogviewLog *log)
GSList * logview_log_get_days_for_cached_lines (LogviewLog *log)
gboolean logview_log_has_new_lines (LogviewLog *log)
char * logview_log_get_uri (LogviewLog *log)
GFile * logview_log_get_gfile (LogviewLog *log)
gboolean logview_log_get_has_days (LogviewLog *log)
Macro Definition Documentation
LOGVIEW_ERROR_QUARK
#define LOGVIEW_ERROR_QUARK g_quark_from_static_string ("logview-error")
Definition at line 58 of file logview-log.h.
LOGVIEW_IS_LOG
#define LOGVIEW_IS_LOG (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LOGVIEW_TYPE_LOG))
Definition at line 36 of file logview-log.h.
LOGVIEW_IS_LOG_CLASS
#define LOGVIEW_IS_LOG_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LOGVIEW_TYPE_LOG))
Definition at line 38 of file logview-log.h.
LOGVIEW_LOG
#define LOGVIEW_LOG (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LOGVIEW_TYPE_LOG, LogviewLog))
Definition at line 32 of file logview-log.h.
LOGVIEW_LOG_CLASS
#define LOGVIEW_LOG_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LOGVIEW_TYPE_LOG, LogviewLogClass))
Definition at line 34 of file logview-log.h.
LOGVIEW_LOG_GET_CLASS
#define LOGVIEW_LOG_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LOGVIEW_TYPE_LOG, LogviewLogClass))
Definition at line 40 of file logview-log.h.
LOGVIEW_TYPE_LOG
#define LOGVIEW_TYPE_LOG logview_log_get_type()
Definition at line 31 of file logview-log.h.
Typedef Documentation
LogviewCreateCallback
typedef void(* LogviewCreateCallback) (LogviewLog *log, GError *error, gpointer user_data)
Definition at line 49 of file logview-log.h.
LogviewLog
typedef struct _LogviewLog LogviewLog
Definition at line 43 of file logview-log.h.
LogviewLogClass
typedef struct _LogviewLogClass LogviewLogClass
Definition at line 44 of file logview-log.h.
LogviewLogPrivate
typedef struct _LogviewLogPrivate LogviewLogPrivate
Definition at line 45 of file logview-log.h.
LogviewNewLinesCallback
typedef void(* LogviewNewLinesCallback) (LogviewLog *log, const char **lines, GSList *new_days, GError *error, gpointer user_data)
Definition at line 52 of file logview-log.h.
Enumeration Type Documentation
LogviewErrorEnum
enum LogviewErrorEnum
Enumerator
LOGVIEW_ERROR_FAILED
LOGVIEW_ERROR_PERMISSION_DENIED
LOGVIEW_ERROR_ZLIB
LOGVIEW_ERROR_NOT_SUPPORTED
LOGVIEW_ERROR_NOT_A_LOG
Definition at line 60 of file logview-log.h.
Function Documentation
logview_log_create()
void logview_log_create (const char * filename, LogviewCreateCallback callback, gpointer user_data)
Definition at line 821 of file logview-log.c.
References LOGVIEW_TYPE_LOG, NULL, _LogviewLog::priv, and user_data.
Referenced by main().
logview_log_create_from_gfile()
void logview_log_create_from_gfile (GFile * file, LogviewCreateCallback callback, gpointer user_data)
Definition at line 832 of file logview-log.c.
References LOGVIEW_TYPE_LOG, NULL, _LogviewLog::priv, and user_data.
logview_log_get_cached_lines()
const char ** logview_log_get_cached_lines (LogviewLog * log)
Definition at line 875 of file logview-log.c.
References LOGVIEW_IS_LOG, NULL, and _LogviewLog::priv.
logview_log_get_cached_lines_number()
guint logview_log_get_cached_lines_number (LogviewLog * log)
Definition at line 867 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
logview_log_get_days_for_cached_lines()
GSList * logview_log_get_days_for_cached_lines (LogviewLog * log)
Definition at line 889 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
Referenced by logview_loglist_update_lines().
logview_log_get_display_name()
const char * logview_log_get_display_name (LogviewLog * log)
Definition at line 843 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
logview_log_get_file_size()
goffset logview_log_get_file_size (LogviewLog * log)
Definition at line 859 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
logview_log_get_gfile()
GFile * logview_log_get_gfile (LogviewLog * log)
Definition at line 913 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
Referenced by logview_manager_close_active_log(), and logview_manager_set_active_log().
logview_log_get_has_days()
gboolean logview_log_get_has_days (LogviewLog * log)
Definition at line 921 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
logview_log_get_timestamp()
time_t logview_log_get_timestamp (LogviewLog * log)
Definition at line 851 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
logview_log_get_type()
GType logview_log_get_type (void)
logview_log_get_uri()
char * logview_log_get_uri (LogviewLog * log)
Definition at line 905 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
Referenced by logview_manager_close_active_log().
logview_log_has_new_lines()
gboolean logview_log_has_new_lines (LogviewLog * log)
Definition at line 897 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
logview_log_read_new_lines()
void logview_log_read_new_lines (LogviewLog * log, GCancellable * cancellable, LogviewNewLinesCallback callback, gpointer user_data)
Definition at line 798 of file logview-log.c.
References NULL, and user_data.