MATE Desktop Environment: logview-window.h File Reference
logview-window.h File Reference
#include <gtk/gtk.h>
Classes
struct _LogviewWindow
struct _LogviewWindowClass
Macros
#define LOGVIEW_TYPE_WINDOW (logview_window_get_type ())
#define LOGVIEW_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LOGVIEW_TYPE_WINDOW, LogviewWindow))
#define LOGVIEW_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LOGVIEW_TYPE_WINDOW, LogviewWindowClass))
#define LOGVIEW_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LOGVIEW_TYPE_WINDOW))
#define LOGVIEW_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((obj), LOGVIEW_TYPE_WINDOW))
#define LOGVIEW_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LOGVIEW_TYPE_WINDOW, LogviewWindowClass))
Typedefs
typedef struct _LogviewWindow LogviewWindow
typedef struct _LogviewWindowClass LogviewWindowClass
typedef struct _LogviewWindowPrivate LogviewWindowPrivate
Functions
GType logview_window_get_type (void)
GtkWidget * logview_window_new (void)
void logview_window_add_error (LogviewWindow *window, const char *primary, const char *secondary)
void logview_window_add_errors (LogviewWindow *window, GPtrArray *errors)
Macro Definition Documentation
LOGVIEW_IS_WINDOW
#define LOGVIEW_IS_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LOGVIEW_TYPE_WINDOW))
Definition at line 29 of file logview-window.h.
LOGVIEW_IS_WINDOW_CLASS
#define LOGVIEW_IS_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((obj), LOGVIEW_TYPE_WINDOW))
Definition at line 30 of file logview-window.h.
LOGVIEW_TYPE_WINDOW
#define LOGVIEW_TYPE_WINDOW (logview_window_get_type ())
Definition at line 26 of file logview-window.h.
LOGVIEW_WINDOW
#define LOGVIEW_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LOGVIEW_TYPE_WINDOW, LogviewWindow))
Definition at line 27 of file logview-window.h.
LOGVIEW_WINDOW_CLASS
#define LOGVIEW_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LOGVIEW_TYPE_WINDOW, LogviewWindowClass))
Definition at line 28 of file logview-window.h.
LOGVIEW_WINDOW_GET_CLASS
#define LOGVIEW_WINDOW_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LOGVIEW_TYPE_WINDOW, LogviewWindowClass))
Definition at line 31 of file logview-window.h.
Typedef Documentation
LogviewWindow
typedef struct _LogviewWindow LogviewWindow
Definition at line 33 of file logview-window.h.
LogviewWindowClass
typedef struct _LogviewWindowClass LogviewWindowClass
Definition at line 34 of file logview-window.h.
LogviewWindowPrivate
typedef struct _LogviewWindowPrivate LogviewWindowPrivate
Definition at line 35 of file logview-window.h.
Function Documentation
logview_window_add_error()
void logview_window_add_error (LogviewWindow * window, const char * primary, const char * secondary)
Definition at line 1535 of file logview-window.c.
References LOGVIEW_IS_WINDOW, and _LogviewWindow::priv.
Referenced by logview_app_add_error(), and logview_app_add_errors().
logview_window_add_errors()
void logview_window_add_errors (LogviewWindow * window, GPtrArray * errors)
Definition at line 1554 of file logview-window.c.
References _, FALSE, LOGVIEW_IS_WINDOW, NULL, and _LogviewWindow::priv.
Referenced by logview_app_add_errors().
logview_window_get_type()
GType logview_window_get_type (void)
logview_window_new()
GtkWidget * logview_window_new (void)
Definition at line 1521 of file logview-window.c.
References LOGVIEW_TYPE_WINDOW, NULL, and _LogviewWindow::priv.