MATE Desktop Environment: logview-manager.h File Reference
logview-manager.h File Reference
#include <glib-object.h>
#include "logview-log.h"
Classes
struct _LogviewManager
struct _LogviewManagerClass
Macros
#define LOGVIEW_TYPE_MANAGER logview_manager_get_type()
#define LOGVIEW_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LOGVIEW_TYPE_MANAGER, LogviewManager))
#define LOGVIEW_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LOGVIEW_TYPE_MANAGER, LogviewManagerClass))
#define LOGVIEW_IS_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LOGVIEW_TYPE_MANAGER))
#define LOGVIEW_IS_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LOGVIEW_TYPE_MANAGER))
#define LOGVIEW_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LOGVIEW_TYPE_MANAGER, LogviewManagerClass))
Typedefs
typedef struct _LogviewManager LogviewManager
typedef struct _LogviewManagerClass LogviewManagerClass
typedef struct _LogviewManagerPrivate LogviewManagerPrivate
Functions
GType logview_manager_get_type (void)
LogviewManager * logview_manager_get (void)
void logview_manager_add_logs_from_name_list (LogviewManager *manager, GSList *names, const char *active)
void logview_manager_add_log_from_gfile (LogviewManager *manager, GFile *file, gboolean set_active)
void logview_manager_add_logs_from_names (LogviewManager *manager, char **names, const gchar *active)
void logview_manager_set_active_log (LogviewManager *manager, LogviewLog *log)
LogviewLog * logview_manager_get_active_log (LogviewManager *manager)
int logview_manager_get_log_count (LogviewManager *manager)
LogviewLog * logview_manager_get_if_loaded (LogviewManager *manager, char *filename)
gboolean logview_manager_log_is_active (LogviewManager *manager, LogviewLog *log)
void logview_manager_close_active_log (LogviewManager *manager)
Macro Definition Documentation
LOGVIEW_IS_MANAGER
#define LOGVIEW_IS_MANAGER (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LOGVIEW_TYPE_MANAGER))
Definition at line 36 of file logview-manager.h.
LOGVIEW_IS_MANAGER_CLASS
#define LOGVIEW_IS_MANAGER_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LOGVIEW_TYPE_MANAGER))
Definition at line 38 of file logview-manager.h.
LOGVIEW_MANAGER
#define LOGVIEW_MANAGER (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LOGVIEW_TYPE_MANAGER, LogviewManager))
Definition at line 32 of file logview-manager.h.
LOGVIEW_MANAGER_CLASS
#define LOGVIEW_MANAGER_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LOGVIEW_TYPE_MANAGER, LogviewManagerClass))
Definition at line 34 of file logview-manager.h.
LOGVIEW_MANAGER_GET_CLASS
#define LOGVIEW_MANAGER_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LOGVIEW_TYPE_MANAGER, LogviewManagerClass))
Definition at line 40 of file logview-manager.h.
LOGVIEW_TYPE_MANAGER
#define LOGVIEW_TYPE_MANAGER logview_manager_get_type()
Definition at line 31 of file logview-manager.h.
Typedef Documentation
LogviewManager
typedef struct _LogviewManager LogviewManager
Definition at line 43 of file logview-manager.h.
LogviewManagerClass
typedef struct _LogviewManagerClass LogviewManagerClass
Definition at line 44 of file logview-manager.h.
LogviewManagerPrivate
typedef struct _LogviewManagerPrivate LogviewManagerPrivate
Definition at line 45 of file logview-manager.h.
Function Documentation
logview_manager_add_log_from_gfile()
void logview_manager_add_log_from_gfile (LogviewManager * manager, GFile * file, gboolean set_active)
Definition at line 313 of file logview-manager.c.
References FALSE, and LOGVIEW_IS_MANAGER.
logview_manager_add_logs_from_name_list()
void logview_manager_add_logs_from_name_list (LogviewManager * manager, GSList * names, const char * active)
Definition at line 323 of file logview-manager.c.
References LOGVIEW_IS_MANAGER, NULL, op, and TRUE.
logview_manager_add_logs_from_names()
void logview_manager_add_logs_from_names (LogviewManager * manager, char ** names, const gchar * active)
Definition at line 342 of file logview-manager.c.
References LOGVIEW_IS_MANAGER, NULL, op, and TRUE.
Referenced by logview_app_initialize().
logview_manager_close_active_log()
void logview_manager_close_active_log (LogviewManager * manager)
Definition at line 386 of file logview-manager.c.
References LOG_CLOSED, LOGVIEW_IS_MANAGER, logview_log_get_gfile(), logview_log_get_uri(), logview_prefs_get(), logview_prefs_remove_stored_log(), NULL, _LogviewManager::priv, and signals.
logview_manager_get()
LogviewManager * logview_manager_get (void)
Definition at line 264 of file logview-manager.c.
References LOGVIEW_TYPE_MANAGER, and NULL.
logview_manager_get_active_log()
LogviewLog * logview_manager_get_active_log (LogviewManager * manager)
Definition at line 303 of file logview-manager.c.
References LOGVIEW_IS_MANAGER, NULL, and _LogviewManager::priv.
logview_manager_get_if_loaded()
LogviewLog * logview_manager_get_if_loaded (LogviewManager * manager, char * filename)
Definition at line 370 of file logview-manager.c.
References LOGVIEW_IS_MANAGER, NULL, and _LogviewManager::priv.
logview_manager_get_log_count()
int logview_manager_get_log_count (LogviewManager * manager)
Definition at line 362 of file logview-manager.c.
References LOGVIEW_IS_MANAGER, and _LogviewManager::priv.
logview_manager_get_type()
GType logview_manager_get_type (void)
logview_manager_log_is_active()
gboolean logview_manager_log_is_active (LogviewManager * manager, LogviewLog * log)
Definition at line 417 of file logview-manager.c.
References LOGVIEW_IS_MANAGER, and _LogviewManager::priv.
logview_manager_set_active_log()
void logview_manager_set_active_log (LogviewManager * manager, LogviewLog * log)
Definition at line 274 of file logview-manager.c.
References ACTIVE_CHANGED, LOGVIEW_IS_MANAGER, logview_log_get_gfile(), logview_prefs_get(), logview_prefs_store_active_logfile(), NULL, _LogviewManager::priv, and signals.