MATE Desktop Environment: mate-druid-page-standard.h File Reference
mate-druid-page-standard.h File Reference
#include <gtk/gtk.h>
#include "mate-druid-page.h"
Classes
struct _MateDruidPageStandard
struct _MateDruidPageStandardClass
Macros
#define MATE_TYPE_DRUID_PAGE_STANDARD (mate_druid_page_standard_get_type ())
#define MATE_DRUID_PAGE_STANDARD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_DRUID_PAGE_STANDARD, MateDruidPageStandard))
#define MATE_DRUID_PAGE_STANDARD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_DRUID_PAGE_STANDARD, MateDruidPageStandardClass))
#define MATE_IS_DRUID_PAGE_STANDARD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_DRUID_PAGE_STANDARD))
#define MATE_IS_DRUID_PAGE_STANDARD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_DRUID_PAGE_STANDARD))
#define MATE_DRUID_PAGE_STANDARD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_DRUID_PAGE_STANDARD, MateDruidPageStandardClass))
#define mate_druid_page_standard_set_bg_color mate_druid_page_standard_set_background
#define mate_druid_page_standard_set_logo_bg_color mate_druid_page_standard_set_logo_background
#define mate_druid_page_standard_set_title_color mate_druid_page_standard_set_title_foreground
Typedefs
typedef struct _MateDruidPageStandard MateDruidPageStandard
typedef struct _MateDruidPageStandardPrivate MateDruidPageStandardPrivate
typedef struct _MateDruidPageStandardClass MateDruidPageStandardClass
Functions
GType mate_druid_page_standard_get_type (void)
GtkWidget * mate_druid_page_standard_new (void)
GtkWidget * mate_druid_page_standard_new_with_vals (const gchar *title, GdkPixbuf *logo, GdkPixbuf *top_watermark)
void mate_druid_page_standard_set_title (MateDruidPageStandard *druid_page_standard, const gchar *title)
void mate_druid_page_standard_set_logo (MateDruidPageStandard *druid_page_standard, GdkPixbuf *logo_image)
void mate_druid_page_standard_set_top_watermark (MateDruidPageStandard *druid_page_standard, GdkPixbuf *top_watermark_image)
void mate_druid_page_standard_set_title_foreground (MateDruidPageStandard *druid_page_standard, GdkColor *color)
void mate_druid_page_standard_set_background (MateDruidPageStandard *druid_page_standard, GdkColor *color)
void mate_druid_page_standard_set_logo_background (MateDruidPageStandard *druid_page_standard, GdkColor *color)
void mate_druid_page_standard_set_contents_background (MateDruidPageStandard *druid_page_standard, GdkColor *color)
void mate_druid_page_standard_append_item (MateDruidPageStandard *druid_page_standard, const gchar *question, GtkWidget *item, const gchar *additional_info)
Macro Definition Documentation
MATE_DRUID_PAGE_STANDARD
#define MATE_DRUID_PAGE_STANDARD (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_DRUID_PAGE_STANDARD, MateDruidPageStandard))
Definition at line 37 of file mate-druid-page-standard.h.
MATE_DRUID_PAGE_STANDARD_CLASS
#define MATE_DRUID_PAGE_STANDARD_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_DRUID_PAGE_STANDARD, MateDruidPageStandardClass))
Definition at line 38 of file mate-druid-page-standard.h.
MATE_DRUID_PAGE_STANDARD_GET_CLASS
#define MATE_DRUID_PAGE_STANDARD_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_DRUID_PAGE_STANDARD, MateDruidPageStandardClass))
Definition at line 41 of file mate-druid-page-standard.h.
mate_druid_page_standard_set_bg_color
#define mate_druid_page_standard_set_bg_color mate_druid_page_standard_set_background
Definition at line 88 of file mate-druid-page-standard.h.
mate_druid_page_standard_set_logo_bg_color
#define mate_druid_page_standard_set_logo_bg_color mate_druid_page_standard_set_logo_background
Definition at line 89 of file mate-druid-page-standard.h.
mate_druid_page_standard_set_title_color
#define mate_druid_page_standard_set_title_color mate_druid_page_standard_set_title_foreground
Definition at line 90 of file mate-druid-page-standard.h.
MATE_IS_DRUID_PAGE_STANDARD
#define MATE_IS_DRUID_PAGE_STANDARD (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_DRUID_PAGE_STANDARD))
Definition at line 39 of file mate-druid-page-standard.h.
MATE_IS_DRUID_PAGE_STANDARD_CLASS
#define MATE_IS_DRUID_PAGE_STANDARD_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_DRUID_PAGE_STANDARD))
Definition at line 40 of file mate-druid-page-standard.h.
MATE_TYPE_DRUID_PAGE_STANDARD
#define MATE_TYPE_DRUID_PAGE_STANDARD (mate_druid_page_standard_get_type ())
Definition at line 36 of file mate-druid-page-standard.h.
Typedef Documentation
MateDruidPageStandard
typedef struct _MateDruidPageStandard MateDruidPageStandard
Definition at line 44 of file mate-druid-page-standard.h.
MateDruidPageStandardClass
typedef struct _MateDruidPageStandardClass MateDruidPageStandardClass
Definition at line 46 of file mate-druid-page-standard.h.
MateDruidPageStandardPrivate
typedef struct _MateDruidPageStandardPrivate MateDruidPageStandardPrivate
Definition at line 45 of file mate-druid-page-standard.h.
Function Documentation
mate_druid_page_standard_append_item()
void mate_druid_page_standard_append_item (MateDruidPageStandard * druid_page_standard, const gchar * question, GtkWidget * item, const gchar * additional_info)
mate_druid_page_standard_append_item: @druid_page_standard: A MateDruidPageStandard instance. @question: The text to place above the item. @item: The #GtkWidget to be included. @additional_info: The text to be placed below the item in a smaller font.
Description: Convenience function to add a #GtkWidget to the MateDruidPageStandard vbox. This function creates a new contents section that has the @question text followed by the @item widget and then the @addition_info text, all stacked vertically from top to bottom.
The @item widget could be something like a set of radio checkbuttons requesting a choice from the user.
Definition at line 741 of file mate-druid-page-standard.c.
References FALSE, item, MATE_IS_DRUID_PAGE_STANDARD, NULL, TRUE, and _MateDruidPageStandard::vbox.
Referenced by main().
mate_druid_page_standard_get_type()
GType mate_druid_page_standard_get_type (void)
mate_druid_page_standard_new()
GtkWidget * mate_druid_page_standard_new (void)
mate_druid_page_standard_new
Construct a new MateDruidPageStandard.
Returns: A new MateDruidPageStandard as a #GtkWidget pointer.
Definition at line 509 of file mate-druid-page-standard.c.
References MATE_TYPE_DRUID_PAGE_STANDARD, and NULL.
mate_druid_page_standard_new_with_vals()
GtkWidget * mate_druid_page_standard_new_with_vals (const gchar * title, GdkPixbuf * logo, GdkPixbuf * top_watermark)
mate_druid_page_standard_new_with_vals: @title: The title of the druid page. @logo: The logo to put on the druid page. @top_watermark: The watermark to put at the top of the druid page.
Like mate_druid_page_standard_new(), but allows the caller to fill in some of the values at the same time.
Returns: A new MateDruidPageStandard as a #GtkWidget pointer.
Definition at line 530 of file mate-druid-page-standard.c.
References mate_druid_page_standard_set_logo(), mate_druid_page_standard_set_title(), mate_druid_page_standard_set_top_watermark(), MATE_TYPE_DRUID_PAGE_STANDARD, and NULL.
Referenced by main().
mate_druid_page_standard_set_background()
void mate_druid_page_standard_set_background (MateDruidPageStandard * druid_page_standard, GdkColor * color)
mate_druid_page_standard_set_background: @druid_page_standard: A MateDruidPageStandard instance. @color: The new background color.
Sets the background color of the top section of the druid page to @color.
Definition at line 657 of file mate-druid-page-standard.c.
References _MateDruidPageStandard::_priv, _MateDruidPageStandard::background, FALSE, MATE_IS_DRUID_PAGE_STANDARD, NULL, and TRUE.
mate_druid_page_standard_set_contents_background()
void mate_druid_page_standard_set_contents_background (MateDruidPageStandard * druid_page_standard, GdkColor * color)
mate_druid_page_standard_set_contents_background: @druid_page_standard: A MateDruidPageStandard instance. @color: The new color for the main body's background.
Sets the color of the main contents section's background to @color.
Definition at line 706 of file mate-druid-page-standard.c.
References _MateDruidPageStandard::_priv, _MateDruidPageStandard::contents_background, FALSE, MATE_IS_DRUID_PAGE_STANDARD, NULL, and TRUE.
mate_druid_page_standard_set_logo()
void mate_druid_page_standard_set_logo (MateDruidPageStandard * druid_page_standard, GdkPixbuf * logo_image)
mate_druid_page_standard_set_logo: @druid_page_standard: A MateDruidPageStandard instance. @logo_image: The #GdkPixbuf to use as a logo.
Description: Sets a #GdkPixbuf as the logo in the top right corner. If NULL, then no logo will be displayed.
Definition at line 581 of file mate-druid-page-standard.c.
References _MateDruidPageStandard::_priv, _MateDruidPageStandard::logo, MATE_IS_DRUID_PAGE_STANDARD, and NULL.
Referenced by mate_druid_page_standard_new_with_vals().
mate_druid_page_standard_set_logo_background()
void mate_druid_page_standard_set_logo_background (MateDruidPageStandard * druid_page_standard, GdkColor * color)
mate_druid_page_standard_set_logo_background: @druid_page_standard: A MateDruidPageStandard instance. @color: The new color for the logo background.
Sets the background of the logo to @color.
Definition at line 681 of file mate-druid-page-standard.c.
References _MateDruidPageStandard::_priv, FALSE, _MateDruidPageStandard::logo_background, MATE_IS_DRUID_PAGE_STANDARD, NULL, and TRUE.
mate_druid_page_standard_set_title()
void mate_druid_page_standard_set_title (MateDruidPageStandard * druid_page_standard, const gchar * title)
mate_druid_page_standard_set_title: @druid_page_standard: A MateDruidPageStandard instance. @title: The string to use as the new title text.
Description: Sets the title to the value of @title.
Definition at line 554 of file mate-druid-page-standard.c.
References _MateDruidPageStandard::_priv, MATE_IS_DRUID_PAGE_STANDARD, NULL, _MateDruidPageStandard::title, and TRUE.
Referenced by mate_druid_page_standard_new_with_vals().
mate_druid_page_standard_set_title_foreground()
void mate_druid_page_standard_set_title_foreground (MateDruidPageStandard * druid_page_standard, GdkColor * color)
mate_druid_page_standard_set_title_foreground: @druid_page_standard: A MateDruidPageStandard instance. @color: The new color of the title text.
Sets the title text to the specified color.
Definition at line 632 of file mate-druid-page-standard.c.
References _MateDruidPageStandard::_priv, FALSE, MATE_IS_DRUID_PAGE_STANDARD, NULL, _MateDruidPageStandard::title_foreground, and TRUE.
mate_druid_page_standard_set_top_watermark()
void mate_druid_page_standard_set_top_watermark (MateDruidPageStandard * druid_page_standard, GdkPixbuf * top_watermark_image)
mate_druid_page_standard_set_top_watermark: @druid_page_standard: A MateDruidPageStandard instance. @top_watermark_image: The #GdkPixbuf to use as a top watermark.
Description: Sets a #GdkPixbuf as the watermark on top of the top strip on the druid. If #top_watermark_image is NULL, it is reset to the normal color.
Definition at line 608 of file mate-druid-page-standard.c.
References _MateDruidPageStandard::_priv, MATE_IS_DRUID_PAGE_STANDARD, NULL, and _MateDruidPageStandard::top_watermark.
Referenced by mate_druid_page_standard_new_with_vals().