MATE Desktop Environment: matekbd-desktop-config.c File Reference
matekbd-desktop-config.c File Reference
#include <config.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <X11/keysym.h>
#include <glib/gi18n-lib.h>
#include <gio/gio.h>
#include <matekbd-desktop-config.h>
#include <matekbd-config-private.h>
Macros
#define MATEKBD_DESKTOP_CONFIG_SCHEMA MATEKBD_CONFIG_SCHEMA ".general"
Functions
void matekbd_desktop_config_init (MatekbdDesktopConfig *config, XklEngine *engine)
void matekbd_desktop_config_term (MatekbdDesktopConfig *config)
void matekbd_desktop_config_load_from_gsettings (MatekbdDesktopConfig *config)
void matekbd_desktop_config_save_to_gsettings (MatekbdDesktopConfig *config)
gboolean matekbd_desktop_config_activate (MatekbdDesktopConfig *config)
void matekbd_desktop_config_lock_next_group (MatekbdDesktopConfig *config)
void matekbd_desktop_config_lock_prev_group (MatekbdDesktopConfig *config)
void matekbd_desktop_config_restore_group (MatekbdDesktopConfig *config)
void matekbd_desktop_config_start_listen (MatekbdDesktopConfig *config, GCallback func, gpointer user_data)
void matekbd_desktop_config_stop_listen (MatekbdDesktopConfig *config)
gboolean matekbd_desktop_config_load_group_descriptions (MatekbdDesktopConfig *config, XklConfigRegistry *registry, const gchar **layout_ids, const gchar **variant_ids, gchar ***short_group_names, gchar ***full_group_names)
Variables
const gchar MATEKBD_DESKTOP_CONFIG_KEY_DEFAULT_GROUP [] = "default-group"
const gchar MATEKBD_DESKTOP_CONFIG_KEY_GROUP_PER_WINDOW [] = "group-per-window"
const gchar MATEKBD_DESKTOP_CONFIG_KEY_HANDLE_INDICATORS [] = "handle-indicators"
const gchar MATEKBD_DESKTOP_CONFIG_KEY_LAYOUT_NAMES_AS_GROUP_NAMES [] = "layout-names-as-group-names"
const gchar MATEKBD_DESKTOP_CONFIG_KEY_LOAD_EXTRA_ITEMS [] = "load-extra-items"
Macro Definition Documentation
MATEKBD_DESKTOP_CONFIG_SCHEMA
#define MATEKBD_DESKTOP_CONFIG_SCHEMA MATEKBD_CONFIG_SCHEMA ".general"
MatekbdDesktopConfig:
Definition at line 35 of file matekbd-desktop-config.c.
Function Documentation
matekbd_desktop_config_activate()
gboolean matekbd_desktop_config_activate (MatekbdDesktopConfig * config)
Definition at line 207 of file matekbd-desktop-config.c.
References _MatekbdDesktopConfig::default_group, _MatekbdDesktopConfig::engine, _MatekbdDesktopConfig::group_per_app, _MatekbdDesktopConfig::handle_indicators, and TRUE.
matekbd_desktop_config_init()
void matekbd_desktop_config_init (MatekbdDesktopConfig * config, XklEngine * engine)
Definition at line 130 of file matekbd-desktop-config.c.
References _MatekbdDesktopConfig::engine, engine, MATEKBD_DESKTOP_CONFIG_SCHEMA, and _MatekbdDesktopConfig::settings.
Referenced by msd_keyboard_xkb_init(), and setup_xkb_tabs().
matekbd_desktop_config_load_from_gsettings()
void matekbd_desktop_config_load_from_gsettings (MatekbdDesktopConfig * config)
Definition at line 146 of file matekbd-desktop-config.c.
References _MatekbdDesktopConfig::default_group, _MatekbdDesktopConfig::engine, _MatekbdDesktopConfig::group_per_app, _MatekbdDesktopConfig::handle_indicators, _MatekbdDesktopConfig::layout_names_as_group_names, _MatekbdDesktopConfig::load_extra_items, MATEKBD_DESKTOP_CONFIG_KEY_DEFAULT_GROUP, MATEKBD_DESKTOP_CONFIG_KEY_GROUP_PER_WINDOW, MATEKBD_DESKTOP_CONFIG_KEY_HANDLE_INDICATORS, MATEKBD_DESKTOP_CONFIG_KEY_LAYOUT_NAMES_AS_GROUP_NAMES, MATEKBD_DESKTOP_CONFIG_KEY_LOAD_EXTRA_ITEMS, and _MatekbdDesktopConfig::settings.
Referenced by setup_xkb_tabs().
matekbd_desktop_config_load_group_descriptions()
gboolean matekbd_desktop_config_load_group_descriptions (MatekbdDesktopConfig * config, XklConfigRegistry * registry, const gchar ** layout_ids, const gchar ** variant_ids, gchar *** short_group_names, gchar *** full_group_names)
Definition at line 272 of file matekbd-desktop-config.c.
References matekbd_keyboard_config_format_full_layout(), and NULL.
matekbd_desktop_config_lock_next_group()
void matekbd_desktop_config_lock_next_group (MatekbdDesktopConfig * config)
Definition at line 222 of file matekbd-desktop-config.c.
References _MatekbdDesktopConfig::engine.
matekbd_desktop_config_lock_prev_group()
void matekbd_desktop_config_lock_prev_group (MatekbdDesktopConfig * config)
Definition at line 229 of file matekbd-desktop-config.c.
References _MatekbdDesktopConfig::engine.
matekbd_desktop_config_restore_group()
void matekbd_desktop_config_restore_group (MatekbdDesktopConfig * config)
Definition at line 236 of file matekbd-desktop-config.c.
References _MatekbdDesktopConfig::engine.
matekbd_desktop_config_save_to_gsettings()
void matekbd_desktop_config_save_to_gsettings (MatekbdDesktopConfig * config)
Definition at line 183 of file matekbd-desktop-config.c.
References _MatekbdDesktopConfig::default_group, _MatekbdDesktopConfig::group_per_app, _MatekbdDesktopConfig::handle_indicators, _MatekbdDesktopConfig::layout_names_as_group_names, _MatekbdDesktopConfig::load_extra_items, MATEKBD_DESKTOP_CONFIG_KEY_DEFAULT_GROUP, MATEKBD_DESKTOP_CONFIG_KEY_GROUP_PER_WINDOW, MATEKBD_DESKTOP_CONFIG_KEY_HANDLE_INDICATORS, MATEKBD_DESKTOP_CONFIG_KEY_LAYOUT_NAMES_AS_GROUP_NAMES, MATEKBD_DESKTOP_CONFIG_KEY_LOAD_EXTRA_ITEMS, and _MatekbdDesktopConfig::settings.
matekbd_desktop_config_start_listen()
void matekbd_desktop_config_start_listen (MatekbdDesktopConfig * config, GCallback func, gpointer user_data)
matekbd_desktop_config_start_listen: @func: (scope notified): a function to call when settings are changed
Definition at line 247 of file matekbd-desktop-config.c.
References _MatekbdDesktopConfig::config_listener_id, _MatekbdDesktopConfig::settings, and user_data.
Referenced by msd_keyboard_xkb_init().
matekbd_desktop_config_stop_listen()
void matekbd_desktop_config_stop_listen (MatekbdDesktopConfig * config)
Definition at line 257 of file matekbd-desktop-config.c.
References _MatekbdDesktopConfig::config_listener_id, and _MatekbdDesktopConfig::settings.
matekbd_desktop_config_term()
void matekbd_desktop_config_term (MatekbdDesktopConfig * config)
Definition at line 139 of file matekbd-desktop-config.c.
References NULL, and _MatekbdDesktopConfig::settings.
Variable Documentation
MATEKBD_DESKTOP_CONFIG_KEY_DEFAULT_GROUP
const gchar MATEKBD_DESKTOP_CONFIG_KEY_DEFAULT_GROUP[] = "default-group"
Definition at line 37 of file matekbd-desktop-config.c.
Referenced by matekbd_desktop_config_load_from_gsettings(), and matekbd_desktop_config_save_to_gsettings().
MATEKBD_DESKTOP_CONFIG_KEY_GROUP_PER_WINDOW
const gchar MATEKBD_DESKTOP_CONFIG_KEY_GROUP_PER_WINDOW[] = "group-per-window"
Definition at line 38 of file matekbd-desktop-config.c.
Referenced by matekbd_desktop_config_load_from_gsettings(), and matekbd_desktop_config_save_to_gsettings().
MATEKBD_DESKTOP_CONFIG_KEY_HANDLE_INDICATORS
const gchar MATEKBD_DESKTOP_CONFIG_KEY_HANDLE_INDICATORS[] = "handle-indicators"
Definition at line 39 of file matekbd-desktop-config.c.
Referenced by matekbd_desktop_config_load_from_gsettings(), and matekbd_desktop_config_save_to_gsettings().
MATEKBD_DESKTOP_CONFIG_KEY_LAYOUT_NAMES_AS_GROUP_NAMES
const gchar MATEKBD_DESKTOP_CONFIG_KEY_LAYOUT_NAMES_AS_GROUP_NAMES[] = "layout-names-as-group-names"
Definition at line 40 of file matekbd-desktop-config.c.
Referenced by matekbd_desktop_config_load_from_gsettings(), and matekbd_desktop_config_save_to_gsettings().
MATEKBD_DESKTOP_CONFIG_KEY_LOAD_EXTRA_ITEMS
const gchar MATEKBD_DESKTOP_CONFIG_KEY_LOAD_EXTRA_ITEMS[] = "load-extra-items"
Definition at line 41 of file matekbd-desktop-config.c.
Referenced by matekbd_desktop_config_load_from_gsettings(), and matekbd_desktop_config_save_to_gsettings().