MATE Desktop Environment: mate-href.c File Reference
mate-href.c File Reference
#include "config.h"
#include <libmate/mate-macros.h>
#include <glib/gi18n-lib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <libmate/mate-url.h>
#include "mate-href.h"
#include "libmateui-access.h"
#include "mate-url.h"
Enumerations
enum { PROP_0 , PROP_URL , PROP_TEXT }
Functions
MATE_CLASS_BOILERPLATE (MateHRef, mate_href, GtkButton, GTK_TYPE_BUTTON)
GtkWidget * mate_href_new (const gchar *url, const gchar *text)
const gchar * mate_href_get_url (MateHRef *href)
void mate_href_set_url (MateHRef *href, const gchar *url)
const gchar * mate_href_get_text (MateHRef *href)
void mate_href_set_text (MateHRef *href, const gchar *text)
const gchar * mate_href_get_label (MateHRef *href)
void mate_href_set_label (MateHRef *href, const gchar *label)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_URL
PROP_TEXT
Definition at line 65 of file mate-href.c.
Function Documentation
MATE_CLASS_BOILERPLATE()
MATE_CLASS_BOILERPLATE (MateHRef , mate_href , GtkButton , GTK_TYPE_BUTTON)
mate_href_get_type
Returns the type assigned to the MATE href widget.
Definition at line 77 of file mate-href.c.
References _, PROP_TEXT, and PROP_URL.
mate_href_get_label()
const gchar * mate_href_get_label (MateHRef * href)
mate_href_get_label @href: Pointer to MateHRef widget
Deprecated, use mate_href_get_text.
Returns:
Definition at line 342 of file mate-href.c.
References mate_href_get_text().
mate_href_get_text()
const gchar * mate_href_get_text (MateHRef * href)
mate_href_get_text @href: Pointer to MateHRef widget
Description: Returns the contents of the label widget used to display the link text. Note that the string should not be freed as it points to internal memory.
Returns: Pointer to text contained in the label widget.
Definition at line 298 of file mate-href.c.
References _MateHRef::_priv, MATE_IS_HREF, and NULL.
Referenced by mate_href_get_label().
mate_href_get_url()
const gchar * mate_href_get_url (MateHRef * href)
mate_href_get_url @href: Pointer to MateHRef widget
Description: Returns the pointer to the URL associated with the @href href object. Note that the string should not be freed as it is internal memory.
Returns: Pointer to an internal URL string, or NULL if failure.
Definition at line 223 of file mate-href.c.
References _MateHRef::_priv, MATE_IS_HREF, and NULL.
mate_href_new()
GtkWidget * mate_href_new (const gchar * url, const gchar * text)
mate_href_new @url: URL assigned to this object. @text: Text associated with the URL.
Description: Created a MATE href object, a label widget with a clickable action and an associated URL. If @text is set to NULL, @url is used as the text for the label.
Returns: Pointer to new MATE href widget.
Definition at line 197 of file mate-href.c.
References MATE_TYPE_HREF, and NULL.
mate_href_set_label()
void mate_href_set_label (MateHRef * href, const gchar * label)
mate_href_set_label @href: Pointer to MateHRef widget @label: New link text for the href object.
Description: deprecated, use mate_href_set_text
Definition at line 359 of file mate-href.c.
References label, mate_href_set_text(), MATE_IS_HREF, and NULL.
mate_href_set_text()
void mate_href_set_text (MateHRef * href, const gchar * text)
mate_href_set_text @href: Pointer to MateHRef widget @text: New link text for the href object.
Description: Sets the internal label widget text (used to display a URL's link text) to the value given in @label.
Definition at line 318 of file mate-href.c.
References _MateHRef::_priv, MATE_IS_HREF, and NULL.
Referenced by mate_href_set_label().
mate_href_set_url()
void mate_href_set_url (MateHRef * href, const gchar * url)
mate_href_set_url @href: Pointer to MateHRef widget @url: String containing the URL to be stored within @href.
Description: Sets the internal URL value within @href to the value of @url.
Definition at line 239 of file mate-href.c.
References _MateHRef::_priv, MATE_IS_HREF, and NULL.