MATE Desktop Environment: mate-app-util.c File Reference
mate-app-util.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include <libmate/mate-util.h>
#include "mate-app-util.h"
#include "mate-dialog-util.h"
#include "mate-dialog.h"
#include "mate-uidefs.h"
#include "mate-appbar.h"
#include <gtk/gtk.h>
Macros
#define INVALID_TIMEOUT 0
Typedefs
typedef struct _MessageInfo MessageInfo
Functions
GtkWidget * mate_app_message (MateApp *app, const gchar *message)
GtkWidget * mate_app_error (MateApp *app, const gchar *error)
GtkWidget * mate_app_warning (MateApp *app, const gchar *warning)
void mate_app_flash (MateApp *app, const gchar *flash)
GtkWidget * mate_app_question (MateApp *app, const gchar *question, MateReplyCallback callback, gpointer data)
GtkWidget * mate_app_question_modal (MateApp *app, const gchar *question, MateReplyCallback callback, gpointer data)
GtkWidget * mate_app_ok_cancel (MateApp *app, const gchar *message, MateReplyCallback callback, gpointer data)
GtkWidget * mate_app_ok_cancel_modal (MateApp *app, const gchar *message, MateReplyCallback callback, gpointer data)
GtkWidget * mate_app_request_string (MateApp *app, const gchar *prompt, MateStringCallback callback, gpointer data)
GtkWidget * mate_app_request_password (MateApp *app, const gchar *prompt, MateStringCallback callback, gpointer data)
MateAppProgressKey mate_app_progress_timeout (MateApp *app, const gchar *description, guint32 interval, MateAppProgressFunc percentage_cb, MateAppProgressCancelFunc cancel_cb, gpointer data)
MateAppProgressKey mate_app_progress_manual (MateApp *app, const gchar *description, MateAppProgressCancelFunc cancel_cb, gpointer data)
void mate_app_set_progress (MateAppProgressKey key, gdouble percent)
void mate_app_progress_done (MateAppProgressKey key)
Macro Definition Documentation
INVALID_TIMEOUT
#define INVALID_TIMEOUT 0
Definition at line 650 of file mate-app-util.c.
Typedef Documentation
MessageInfo
typedef struct _MessageInfo MessageInfo
Definition at line 224 of file mate-app-util.c.
Function Documentation
mate_app_error()
GtkWidget * mate_app_error (MateApp * app, const gchar * error)
mate_app_error @app: Pointer to MATE app object @error: Text of error message to be displayed
Description: An important fatal error; if it appears in the statusbar, it might gdk_beep() and require acknowledgement.
Returns: Pointer to dialog widget, or NULL if error or message in status bar.
Definition at line 162 of file mate-app-util.c.
References error, mate_error_dialog_parented(), MATE_IS_APP, and NULL.
mate_app_flash()
void mate_app_flash (MateApp * app, const gchar * flash)
mate_app_flash @app: Pointer to MATE app object @flash: Text of message to be flashed
Description: Flash the message in the statusbar for a few moments; if no statusbar, do nothing (?). For trivial little status messages, e.g. "Auto saving..."
Definition at line 263 of file mate-app-util.c.
References MATE_APPBAR, mate_appbar_set_status(), MATE_IS_APP, MATE_IS_APPBAR, NULL, and _MateApp::statusbar.
mate_app_message()
GtkWidget * mate_app_message (MateApp * app, const gchar * message)
mate_app_message @app: Pointer to MATE app object @message: Text of message to be displayed
Description: A simple message, in an OK dialog or the status bar. Requires confirmation from the user before it goes away.
Returns: Pointer to dialog widget, or NULL if error or message in status bar.
Definition at line 121 of file mate-app-util.c.
References MATE_IS_APP, mate_ok_dialog_parented(), message(), and NULL.
mate_app_ok_cancel()
GtkWidget * mate_app_ok_cancel (MateApp * app, const gchar * message, MateReplyCallback callback, gpointer data)
mate_app_ok_cancel @app: Pointer to MATE app object @message: Text of message to be displayed @callback: @data:
Description:
Returns: Pointer to dialog widget, or NULL if error or message in status bar.
Definition at line 457 of file mate-app-util.c.
References data, FALSE, MATE_IS_APP, mate_ok_cancel_dialog_parented(), message(), and NULL.
mate_app_ok_cancel_modal()
GtkWidget * mate_app_ok_cancel_modal (MateApp * app, const gchar * message, MateReplyCallback callback, gpointer data)
mate_app_ok_cancel_modal @app: Pointer to MATE app object @message: Text of message to be displayed @callback: @data:
Description:
Returns: Pointer to dialog widget, or NULL if error or message in status bar.
Definition at line 491 of file mate-app-util.c.
References data, FALSE, MATE_IS_APP, mate_ok_cancel_dialog_modal_parented(), message(), NULL, and TRUE.
mate_app_progress_done()
void mate_app_progress_done (MateAppProgressKey key)
mate_app_progress_done @key:
Description:
Definition at line 867 of file mate-app-util.c.
References key, MATE_APPBAR, mate_appbar_set_progress_percentage(), MATE_DIALOG, mate_dialog_close(), and NULL.
mate_app_progress_manual()
MateAppProgressKey mate_app_progress_manual (MateApp * app, const gchar * description, MateAppProgressCancelFunc cancel_cb, gpointer data)
mate_app_progress_manual @app: @description: @cancel_cb: @data:
Description:
Returns:
Definition at line 795 of file mate-app-util.c.
References data, INVALID_TIMEOUT, key, MATE_IS_APP, and NULL.
mate_app_progress_timeout()
MateAppProgressKey mate_app_progress_timeout (MateApp * app, const gchar * description, guint32 interval, MateAppProgressFunc percentage_cb, MateAppProgressCancelFunc cancel_cb, gpointer data)
mate_app_progress_timeout @app: @description: @interval: @percentage_cb: @cancel_cb: @data:
Description:
Returns:
Definition at line 739 of file mate-app-util.c.
References data, key, MATE_IS_APP, and NULL.
mate_app_question()
GtkWidget * mate_app_question (MateApp * app, const gchar * question, MateReplyCallback callback, gpointer data)
mate_app_question @app: Pointer to MATE app object @question: Text of question to be displayed @callback: @data:
Description: Ask a yes or no question, and call the callback when it's answered.
Returns: Pointer to dialog widget, or NULL if error or message in status bar.
Definition at line 388 of file mate-app-util.c.
References data, FALSE, MATE_IS_APP, mate_question_dialog_parented(), NULL, and TRUE.
mate_app_question_modal()
GtkWidget * mate_app_question_modal (MateApp * app, const gchar * question, MateReplyCallback callback, gpointer data)
mate_app_question_modal @app: Pointer to MATE app object @question: Text of question to be displayed @callback: @data:
Description: Ask a yes or no question, and call the callback when it's answered.
Returns: Pointer to dialog widget, or NULL if error or message in status bar.
Definition at line 423 of file mate-app-util.c.
References data, MATE_IS_APP, mate_question_dialog_modal_parented(), NULL, and TRUE.
mate_app_request_password()
GtkWidget * mate_app_request_password (MateApp * app, const gchar * prompt, MateStringCallback callback, gpointer data)
mate_app_request_password @app: Pointer to MATE app object @prompt: Text of prompt to be displayed @callback: @data:
Description:
Returns: Pointer to dialog widget, or NULL if error or message in status bar.
Definition at line 623 of file mate-app-util.c.
References data, MATE_IS_APP, mate_request_dialog(), NULL, and TRUE.
mate_app_request_string()
GtkWidget * mate_app_request_string (MateApp * app, const gchar * prompt, MateStringCallback callback, gpointer data)
mate_app_request_string @app: Pointer to MATE app object @prompt: Text of prompt to be displayed @callback: @data:
Description:
Returns: Pointer to dialog widget, or NULL if error or message in status bar.
Definition at line 588 of file mate-app-util.c.
References data, FALSE, MATE_IS_APP, mate_request_dialog(), and NULL.
mate_app_set_progress()
void mate_app_set_progress (MateAppProgressKey key, gdouble percent)
mate_app_set_progress @key: @percent:
Description:
Definition at line 838 of file mate-app-util.c.
References key, MATE_APPBAR, mate_appbar_set_progress_percentage(), and NULL.
mate_app_warning()
GtkWidget * mate_app_warning (MateApp * app, const gchar * warning)
mate_app_warning @app: Pointer to MATE app object
Warning
: Text of warning message to be displayed
Description: A not-so-important error, but still marked better than a flash
Returns: Pointer to dialog widget, or NULL if error or message in status bar.
Definition at line 198 of file mate-app-util.c.
References MATE_IS_APP, mate_warning_dialog_parented(), and NULL.