MATE Desktop Environment: mate-client.c File Reference
mate-client.c File Reference
#include <config.h>
#include <stdlib.h>
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <errno.h>
#include <glib/gi18n-lib.h>
#include "mate-client.h"
#include "mate-uidefs.h"
#include "mate-ui-init.h"
#include "mate-ice.h"
#include "mate-marshal.h"
#include <gtk/gtk.h>
#include <gdk/gdkprivate.h>
#include <libmateuiP.h>
Macros
#define _XOPEN_SOURCE 500
#define ERROR_STRING_LENGTH 256
Enumerations
enum {
SAVE_YOURSELF , DIE , SAVE_COMPLETE , SHUTDOWN_CANCELLED ,
CONNECT , DISCONNECT , LAST_SIGNAL
}
enum { ARG_SM_CLIENT_ID =1 , ARG_SM_CONFIG_PREFIX , ARG_SM_DISABLE }
Functions
G_GNUC_INTERNAL void _mate_ui_gettext_init (gboolean bind_codeset)
const MateModuleInfo * mate_client_module_info_get (void)
void mate_client_disable_master_connection (void)
MateClient * mate_master_client (void)
MATE_CLASS_BOILERPLATE (MateClient, mate_client, GtkObject, GTK_TYPE_OBJECT)
MateClient * mate_client_new (void)
MateClient * mate_client_new_without_connection (void)
void mate_client_flush (MateClient *client)
void mate_client_connect (MateClient *client)
void mate_client_disconnect (MateClient *client)
MateClientFlags mate_client_get_flags (MateClient *client)
void mate_client_set_clone_command (MateClient *client, gint argc, gchar *argv[])
void mate_client_set_current_directory (MateClient *client, const gchar *dir)
void mate_client_set_discard_command (MateClient *client, gint argc, gchar *argv[])
: Name of the environment variable
mate_client_set_environment @client: Pointer to MATE session client object.
@value: Value of the environment variable
Description: Set an environment variable to be placed in the client's environment prior to running restart, shutdown, discard, etc. commands.
void mate_client_set_environment (MateClient *client, const gchar *name, const gchar *value)
void mate_client_set_process_id (MateClient *client, pid_t pid)
void mate_client_set_program (MateClient *client, const gchar *program)
void mate_client_set_resign_command (MateClient *client, gint argc, gchar *argv[])
void mate_client_set_restart_command (MateClient *client, gint argc, gchar *argv[])
void mate_client_set_priority (MateClient *client, guint priority)
void mate_client_set_restart_style (MateClient *client, MateRestartStyle style)
void mate_client_set_shutdown_command (MateClient *client, gint argc, gchar *argv[])
void mate_client_set_user_id (MateClient *client, const gchar *id)
void mate_client_add_static_arg (MateClient *client,...)
void mate_client_set_id (MateClient *client, const gchar *id)
const gchar * mate_client_get_id (MateClient *client)
const gchar * mate_client_get_previous_id (MateClient *client)
const gchar * mate_client_get_desktop_id (MateClient *client)
const gchar * mate_client_get_config_prefix (MateClient *client)
void mate_client_set_global_config_prefix (MateClient *client, const gchar *prefix)
const gchar * mate_client_get_global_config_prefix (MateClient *client)
void mate_client_save_any_dialog (MateClient *client, GtkDialog *dialog)
void mate_client_save_error_dialog (MateClient *client, GtkDialog *dialog)
void mate_client_request_interaction (MateClient *client, MateDialogType dialog_type, MateInteractFunction function, gpointer data)
void mate_client_request_interaction_interp (MateClient *client, MateDialogType dialog_type, GtkCallbackMarshal function, gpointer data, GDestroyNotify destroy)
void mate_client_request_phase_2 (MateClient *client)
void mate_client_request_save (MateClient *client, MateSaveStyle save_style, gboolean shutdown, MateInteractStyle interact_style, gboolean fast, gboolean global)
void mate_interaction_key_return (gint tag, gboolean cancel_shutdown)
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 500
Definition at line 26 of file mate-client.c.
ERROR_STRING_LENGTH
#define ERROR_STRING_LENGTH 256
Definition at line 1556 of file mate-client.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAVE_YOURSELF
DIE
SAVE_COMPLETE
SHUTDOWN_CANCELLED
CONNECT
DISCONNECT
LAST_SIGNAL
Definition at line 56 of file mate-client.c.
anonymous enum
anonymous enum
Enumerator
ARG_SM_CLIENT_ID
ARG_SM_CONFIG_PREFIX
ARG_SM_DISABLE
Definition at line 893 of file mate-client.c.
Function Documentation
_mate_ui_gettext_init()
void G_GNUC_INTERNAL _mate_ui_gettext_init (gboolean bind_codeset) extern
Definition at line 107 of file mate-ui-init.c.
References FALSE, and TRUE.
Referenced by libmateui_module_info_get(), and mate_client_module_info_get().
MATE_CLASS_BOILERPLATE()
MATE_CLASS_BOILERPLATE (MateClient , mate_client , GtkObject , GTK_TYPE_OBJECT)
Definition at line 1282 of file mate-client.c.
References _mate_marshal_BOOLEAN__INT_ENUM_BOOLEAN_ENUM_BOOLEAN(), CONNECT, _MateClientClass::connect, DIE, _MateClientClass::die, DISCONNECT, _MateClientClass::disconnect, mate_client_disconnect(), MATE_TYPE_INTERACT_STYLE, MATE_TYPE_SAVE_STYLE, NULL, SAVE_COMPLETE, _MateClientClass::save_complete, SAVE_YOURSELF, _MateClientClass::save_yourself, SHUTDOWN_CANCELLED, and _MateClientClass::shutdown_cancelled.
mate_client_add_static_arg()
void mate_client_add_static_arg (MateClient * client, ...)
mate_client_add_static_arg @client: Pointer to MATE session client object. ...: NULL-terminated list of arguments to add to the restart command.
Description: You can add arguments to your restart command's argv with this function. This function provides an alternative way of adding new arguments to the restart command. The arguments are placed before the arguments specified by mate_client_set_restart_command() and after the arguments recognised by GTK+ that are specified by the user on the original command line.
Definition at line 2158 of file mate-client.c.
References MATE_IS_CLIENT, NULL, and _MateClient::static_args.
mate_client_connect()
void mate_client_connect (MateClient * client)
mate_client_connect @client: A MateClient instance.
Description: Causes the client to connect to the session manager. Usually happens automatically; no need to call this function.
Definition at line 1568 of file mate-client.c.
References _MateClient::client_id, CONNECT, ERROR_STRING_LENGTH, FALSE, MATE_CLIENT_CONNECTED, MATE_CLIENT_IDLE, MATE_CLIENT_REGISTERING, MATE_IS_CLIENT, NULL, _MateClient::previous_id, and _MateClient::smc_conn.
Referenced by mate_client_new().
mate_client_disable_master_connection()
void mate_client_disable_master_connection (void)
mate_client_disable_master_connection
Description: Don't connect the master client to the session manager. Usually invoked by users when they pass the –sm-disable argument to a Mate application.
Definition at line 1223 of file mate-client.c.
References FALSE, MATE_CLIENT_PARAM_SM_CONNECT, and NULL.
mate_client_disconnect()
void mate_client_disconnect (MateClient * client)
mate_client_disconnect @client: A MateClient instance.
Description: Disconnect the client from the session manager.
Definition at line 1643 of file mate-client.c.
References DISCONNECT, MATE_CLIENT_CONNECTED, mate_client_flush(), MATE_IS_CLIENT, and NULL.
Referenced by MATE_CLASS_BOILERPLATE().
mate_client_flush()
void mate_client_flush (MateClient * client)
mate_client_flush @client: A MateClient instance.
Description: This will force the underlying connection to the session manager to be flushed. This is useful if you have some pending changes that you want to make sure get committed.
Definition at line 1541 of file mate-client.c.
References MATE_CLIENT_CONNECTED, MATE_IS_CLIENT, NULL, and _MateClient::smc_conn.
Referenced by mate_client_disconnect().
mate_client_get_config_prefix()
const gchar * mate_client_get_config_prefix (MateClient * client)
mate_client_get_config_prefix @client: Pointer to MATE session client object.
Description: Get the config prefix for a client. This config prefix provides a suitable place to store any details about the state of the client which can not be described using the app's command line arguments (as set in the restart command). You may push the returned value using mate_config_push_prefix() and read or write any values you require.
Returns: Config prefix. The returned string belongs to libmateui library and should NOT be freed by the caller.
Definition at line 2278 of file mate-client.c.
References _MateClient::config_prefix, mate_client_get_global_config_prefix(), MATE_IS_CLIENT, and NULL.
mate_client_get_desktop_id()
const gchar * mate_client_get_desktop_id (MateClient * client)
mate_client_get_desktop_id: @client: A MateClient instance.
Get the client ID of the desktop's current instance, i.e. if you consider the desktop as a whole as a session managed app, this returns its session ID using a MATE extension to session management. May return NULL for apps not running under a recent version of mate-session; apps should handle that case.
Returns: Session ID of MATE desktop instance, or NULL if none.
Definition at line 2255 of file mate-client.c.
References MATE_IS_CLIENT, and NULL.
mate_client_get_flags()
MateClientFlags mate_client_get_flags (MateClient * client)
mate_client_get_flags: @client: Pointer to MATE session client object.
Description: Determine the client's status with the session manager.,
Returns: Various #MateClientFlag flags which have been or'd together.
Definition at line 1667 of file mate-client.c.
References _MateClient::client_id, MATE_CLIENT_CONNECTED, MATE_CLIENT_IS_CONNECTED, MATE_CLIENT_RESTARTED, MATE_CLIENT_RESTORED, MATE_IS_CLIENT, NULL, and _MateClient::previous_id.
mate_client_get_global_config_prefix()
const gchar * mate_client_get_global_config_prefix (MateClient * client)
mate_client_get_global_config_prefix @client: Pointer to MATE session client object.
Description: Get the config prefix that will be returned by mate_client_get_config_prefix() for clients which have NOT been restarted or cloned (i.e. for clients started by the user without ‘--sm-’ options). This config prefix may be used to write the user's preferred config for these "new" clients.
You could also use this prefix as a place to store and retrieve config details that you wish to apply to ALL instances of the app. However, this practice limits the users freedom to configure each instance in a different way so it should be used with caution.
Returns: The config prefix as a newly allocated string.
Definition at line 2348 of file mate-client.c.
References _MateClient::global_config_prefix, MATE_IS_CLIENT, name, NULL, _MateClient::program, and strrchr.
Referenced by mate_client_get_config_prefix().
mate_client_get_id()
const gchar * mate_client_get_id (MateClient * client)
mate_client_get_id @client: A MateClient instance.
Description: Returns session management ID
Returns: Session management ID for this client; NULL if not connected to a session manager.
Definition at line 2215 of file mate-client.c.
References _MateClient::client_id, MATE_IS_CLIENT, and NULL.
mate_client_get_previous_id()
const gchar * mate_client_get_previous_id (MateClient * client)
mate_client_get_previous_id @client: A MateClient instance.
Description: Get the session management ID from the previous session.
Returns: Pointer to the session management ID the client had in the last session, or NULL if it was not in a previous session.
Definition at line 2234 of file mate-client.c.
References MATE_IS_CLIENT, NULL, and _MateClient::previous_id.
mate_client_module_info_get()
const MateModuleInfo * mate_client_module_info_get (void)
Definition at line 1024 of file mate-client.c.
References _mate_ui_gettext_init(), ARG_SM_CLIENT_ID, ARG_SM_CONFIG_PREFIX, ARG_SM_DISABLE, FALSE, mate_gtk_module_info_get(), N_, and NULL.
Referenced by libmateui_module_info_get().
mate_client_new()
MateClient * mate_client_new (void)
mate_client_new
Description: Allocates memory for a new MATE session management client object. After allocating, the client tries to connect to a session manager. You probably want to use mate_master_client() instead.
Returns: Pointer to a newly allocated MATE session management client object.
Definition at line 1486 of file mate-client.c.
References mate_client_connect(), and mate_client_new_without_connection().
mate_client_new_without_connection()
MateClient * mate_client_new_without_connection (void)
mate_client_new_without_connection
Description: Allocates memory for a new MATE session management client object. You probably want to use mate_master_client() instead.
Returns: Pointer to a newly allocated MATE session management client object.
Definition at line 1508 of file mate-client.c.
References _MateClient::clone_command, MATE_TYPE_CLIENT, NULL, _MateClient::program, and _MateClient::restart_command.
Referenced by mate_client_new().
mate_client_request_interaction()
void mate_client_request_interaction (MateClient * client, MateDialogType dialog_type, MateInteractFunction function, gpointer data)
mate_client_request_interaction @client: A MateClient object. @dialog_type: The type of dialog to create. @function: Callback to invoke to perform the interaction. @data: Callback data.
Description: Use the following functions, if you want to interact with the user during a "save_yourself" handler without being restricted to using the dialog based commands mate_client_save_any_dialog() or mate_client_save_error_dialog(). Note, however, that overriding the session manager specified preference in this way (by using arbitrary dialog boxes) is not very nice.
If and when the session manager decides that it's the app's turn to interact then 'func' will be called with the specified arguments and a unique 'MateInteractionKey'. The session manager will block other clients from interacting until this key is returned with mate_interaction_key_return().
Definition at line 2670 of file mate-client.c.
References data, FALSE, _MateClient::interact_style, MATE_CLIENT_SAVING_PHASE_1, MATE_CLIENT_SAVING_PHASE_2, MATE_DIALOG_ERROR, MATE_INTERACT_ANY, MATE_INTERACT_NONE, MATE_IS_CLIENT, NULL, and _MateClient::state.
Referenced by mate_client_save_any_dialog(), and mate_client_save_error_dialog().
mate_client_request_interaction_interp()
void mate_client_request_interaction_interp (MateClient * client, MateDialogType dialog_type, GtkCallbackMarshal function, gpointer data, GDestroyNotify destroy)
mate_client_request_interaction_interp @client: Pointer to MATE session client object. @dialog_type: Type of dialog to show. @function: Callback to perform the interaction (a MateInteractFunction). @data: Callback data. @destroy: Function to destroy callback data.
Description: Similar to mate_client_request_interaction(), but used when you need to destroy the callback data after the interaction.
Definition at line 2703 of file mate-client.c.
References data, _MateClient::interact_style, MATE_CLIENT_SAVING_PHASE_1, MATE_CLIENT_SAVING_PHASE_2, MATE_DIALOG_ERROR, MATE_INTERACT_ANY, MATE_INTERACT_NONE, MATE_IS_CLIENT, NULL, _MateClient::state, and TRUE.
mate_client_request_phase_2()
void mate_client_request_phase_2 (MateClient * client)
mate_client_request_phase_2 @client: A MateClient object.
Description: Request the session managaer to emit the "save_yourself" signal for a second time after all the clients in the session have ceased interacting with the user and entered an idle state. This might be useful if your app manages other apps and requires that they are in an idle state before saving its final data.
Definition at line 2741 of file mate-client.c.
References MATE_CLIENT_SAVING_PHASE_1, MATE_IS_CLIENT, NULL, _MateClient::save_phase_2_requested, _MateClient::state, and TRUE.
mate_client_request_save()
void mate_client_request_save (MateClient * client, MateSaveStyle save_style, gboolean shutdown, MateInteractStyle interact_style, gboolean fast, gboolean global)
mate_client_request_save @client: Pointer to MATE session client object. @save_style: Save style to request. @shutdown: Whether to log out of the session. @interact_style: Whether to allow user interaction. @fast: Minimize activity to save as soon as possible. @global: Request that all other apps in the session also save their state.
Description: Request the session manager to save the session in some way. The arguments correspond with the arguments passed to the "save_yourself" signal handler.
The save_style indicates whether the save should affect data accessible to other users (MATE_SAVE_GLOBAL) or only the state visible to the current user (MATE_SAVE_LOCAL) or both. Setting shutdown to TRUE will initiate a logout. The interact_style specifies which kinds of interaction will be available. Setting fast to TRUE will limit the save to setting the session manager properties plus any essential data. Setting the value of global to TRUE will request that all the other apps in the session do a save as well. A global save is mandatory when doing a shutdown.
Definition at line 2779 of file mate-client.c.
References DIE, MATE_CLIENT_CONNECTED, MATE_INTERACT_ANY, MATE_INTERACT_ERRORS, MATE_INTERACT_NONE, MATE_IS_CLIENT, MATE_SAVE_BOTH, MATE_SAVE_GLOBAL, MATE_SAVE_LOCAL, NULL, SAVE_YOURSELF, and _MateClient::smc_conn.
mate_client_save_any_dialog()
void mate_client_save_any_dialog (MateClient * client, GtkDialog * dialog)
mate_client_save_any_dialog @client: Pointer to MateClient object. @dialog: Pointer to MATE dialog widget (a #GtkDialog widget).
Description: May be called during a "save_youself" handler to request that a (modal) dialog is presented to the user. The session manager decides when the dialog is shown, but it will not be shown it unless the session manager is sending an interaction style of MATE_INTERACT_ANY. A "Cancel Logout" button will be added during a shutdown.
Definition at line 2606 of file mate-client.c.
References _MateClient::interact_style, mate_client_request_interaction(), MATE_DIALOG_NORMAL, MATE_INTERACT_ANY, MATE_IS_CLIENT, and NULL.
mate_client_save_error_dialog()
void mate_client_save_error_dialog (MateClient * client, GtkDialog * dialog)
mate_client_save_error_dialog @client: Pointer to MateClient object. @dialog: Pointer to MATE dialog widget (a #GtkDialog widget).
Description: May be called during a "save_youself" handler when an error has occurred during the save. The session manager decides when the dialog is shown, but it will not be shown it unless the session manager is sending an interaction style of MATE_INTERACT_ANY. A "Cancel Logout" button will be added during a shutdown.
Definition at line 2634 of file mate-client.c.
References _MateClient::interact_style, mate_client_request_interaction(), MATE_DIALOG_ERROR, MATE_INTERACT_NONE, MATE_IS_CLIENT, and NULL.
mate_client_set_clone_command()
void mate_client_set_clone_command (MateClient * client, gint argc, gchar * argv[])
mate_client_set_clone_command @client: Pointer to MATE session client object. @argc: Number of strings in the @argv vector. @argv: Argument strings, suitable for use with execv().
Description: Set a command the session manager can use to create a new instance of the application.
Definition at line 1707 of file mate-client.c.
References _MateClient::clone_command, MATE_IS_CLIENT, and NULL.
mate_client_set_current_directory()
void mate_client_set_current_directory (MateClient * client, const gchar * dir)
Definition at line 1732 of file mate-client.c.
References _MateClient::current_directory, MATE_IS_CLIENT, and NULL.
mate_client_set_discard_command()
void mate_client_set_discard_command (MateClient * client, gint argc, gchar * argv[])
Definition at line 1761 of file mate-client.c.
References _MateClient::discard_command, MATE_IS_CLIENT, and NULL.
mate_client_set_environment()
void mate_client_set_environment (MateClient * client, const gchar * name, const gchar * value)
Definition at line 1802 of file mate-client.c.
References _MateClient::environment, MATE_IS_CLIENT, name, and NULL.
Referenced by mate_window_icon_init().
mate_client_set_global_config_prefix()
void mate_client_set_global_config_prefix (MateClient * client, const gchar * prefix)
mate_client_set_global_config_prefix @client: Pointer to MATE session client object. @prefix: Prefix for saving the global configuration.
Description: Set the value used for the global config prefix. The config prefixes returned by mate_client_get_config_prefix() are formed by extending this prefix with an unique identifier.
The global config prefix defaults to a name based on the name of the executable. This function allows you to set it to a different value. It should be called BEFORE retrieving the config prefix for the first time. Later calls will be ignored.
For example, setting a global config prefix of "/app.d/session/" would ensure that all your session save files or directories would be gathered together into the app.d directory.
Definition at line 2316 of file mate-client.c.
References _MateClient::global_config_prefix, MATE_IS_CLIENT, NULL, and prefix.
mate_client_set_id()
void mate_client_set_id (MateClient * client, const gchar * id)
mate_client_set_id @client: A MateClient instance. @id: Session management ID.
Description: Set the client's session management ID; must be done before connecting to the session manager. There is usually no reason to call this function.
Definition at line 2190 of file mate-client.c.
References _MateClient::client_id, MATE_CLIENT_CONNECTED, MATE_IS_CLIENT, and NULL.
mate_client_set_priority()
void mate_client_set_priority (MateClient * client, guint priority)
mate_client_set_priority @client: Pointer to MATE session client object. @priority: Position of client in session start up ordering.
Description:
The mate-session manager restarts clients in order of their priorities in a similar way to the start up ordering in SysV. This function allows the app to suggest a position in this ordering. The value should be between 0 and 99. A default value of 50 is assigned to apps that do not provide a value. The user may assign a different priority.
Definition at line 2003 of file mate-client.c.
References MATE_IS_CLIENT, and NULL.
mate_client_set_process_id()
void mate_client_set_process_id (MateClient * client, pid_t pid)
mate_client_set_process_id @client: Pointer to MATE session client object. @pid: PID to set as the client's PID.
Description: The client should tell the session manager the result of getpid(). However, MATE does this automatically; so you do not need this function.
Definition at line 1856 of file mate-client.c.
References MATE_IS_CLIENT, NULL, and _MateClient::process_id.
mate_client_set_program()
void mate_client_set_program (MateClient * client, const gchar * program)
mate_client_set_program @client: Pointer to MATE session client object. @program: Name of the program.
Description: Used to tell the session manager the name of your program. Set automatically; this function isn't needed.
Definition at line 1884 of file mate-client.c.
References MATE_IS_CLIENT, NULL, and _MateClient::program.
mate_client_set_resign_command()
void mate_client_set_resign_command (MateClient * client, gint argc, gchar * argv[])
mate_client_set_resign_command @client: Pointer to MATE session client object. @argc: Number of strings in @argv. @argv: execv()-style command to undo the effects of the client.
Description: Some clients can be "undone," removing their effects and deleting any saved state. For example, xmodmap could register a resign command to undo the keymap changes it saved.
Used by clients that use the MATE_RESTART_ANYWAY restart style to to undo their effects (these clients usually perform initialisation functions and leave effects behind after they die). The resign command combines the effects of a shutdown command and a discard command. It is executed when the user decides that the client should cease to be restarted.
Definition at line 1924 of file mate-client.c.
References MATE_IS_CLIENT, NULL, and _MateClient::resign_command.
mate_client_set_restart_command()
void mate_client_set_restart_command (MateClient * client, gint argc, gchar * argv[])
mate_client_set_restart_command @client: Pointer to MATE session client object. @argc: Number of strings in argv. @argv: Argument vector to an execv() to restart the client.
Description: When clients crash or the user logs out and back in, they are restarted. This command should perform the restart. Executing the restart command on the local host should reproduce the state of the client at the time of the session save as closely as possible. Saving config info under the mate_client_get_config_prefix() is generally useful.
Definition at line 1968 of file mate-client.c.
References MATE_IS_CLIENT, NULL, and _MateClient::restart_command.
mate_client_set_restart_style()
void mate_client_set_restart_style (MateClient * client, MateRestartStyle style)
mate_client_set_restart_style @client: Pointer to MATE session client object. @style: When to restart the client.
Tells the session manager how the client should be restarted in future session. The options are given by the MateRestartStyle enum.
Definition at line 2026 of file mate-client.c.
References MATE_IS_CLIENT, MATE_RESTART_ANYWAY, MATE_RESTART_IF_RUNNING, MATE_RESTART_IMMEDIATELY, MATE_RESTART_NEVER, NULL, and _MateClient::restart_style.
mate_client_set_shutdown_command()
void mate_client_set_shutdown_command (MateClient * client, gint argc, gchar * argv[])
mate_client_set_shutdown_command @client: Pointer to MATE session client object. @argc: Number of strings in argv. @argv: Command to shutdown the client if the client isn't running.
Description: MATE_RESTART_ANYWAY clients can set this command to run when the user logs out but the client is no longer running.
Used by clients that use the MATE_RESTART_ANYWAY restart style to to undo their effects (these clients usually perform initialisation functions and leave effects behind after they die). The shutdown command simply undoes the effects of the client. It is executed during a normal logout.
Definition at line 2085 of file mate-client.c.
References MATE_IS_CLIENT, NULL, and _MateClient::shutdown_command.
mate_client_set_user_id()
void mate_client_set_user_id (MateClient * client, const gchar * id)
mate_client_set_user_id @client: Pointer to MATE session client object. @id: Username.
Description: Tell the session manager the user's login name. MATE does this automatically; no need to call the function.
Definition at line 2125 of file mate-client.c.
References MATE_IS_CLIENT, NULL, and _MateClient::user_id.
mate_interaction_key_return()
void mate_interaction_key_return (gint tag, gboolean cancel_shutdown)
mate_interaction_key_return @key: Key passed to interaction callback @cancel_shutdown: If TRUE, cancel the shutdown
Description: Used in interaction callback to tell the session manager you are done interacting.
Definition at line 2881 of file mate-client.c.
References FALSE, _MateClient::interaction_keys, key, NULL, _MateClient::shutdown, and _MateClient::smc_conn.
mate_master_client()
MateClient * mate_master_client (void)
mate_master_client
Description: Get the master session management client. This master client gets a client id, that may be specified by the '–sm-client-id' command line option. A master client will be generated by mate_program_init(). If possible the master client will contact the session manager after command-line parsing is finished (unless mate_client_disable_master_connection() was called). The master client will also set the SM_CLIENT_ID property on the client leader window of your application.
Additionally, the master client gets some static arguments set automatically (see mate_client_add_static_arg() for static arguments): mate_program_init() passes all the command line options which are recognised by gtk as static arguments to the master client.
Returns: Pointer to the master client
Definition at line 1273 of file mate-client.c.
Referenced by mate_window_icon_init().