MATE Desktop Environment: mate-icon-list.c File Reference
mate-icon-list.c File Reference
#include <config.h>
#include <string.h>
#include <stdio.h>
#include <gtk/gtk.h>
#include "mate-icon-list.h"
#include "mate-icon-item.h"
#include "mate-marshal.h"
#include <libmatecanvas/mate-canvas-pixbuf.h>
#include <libmatecanvas/mate-canvas-rect-ellipse.h>
#include <gdk/gdkkeysyms.h>
#include <libmateuiP.h>
#include "libmateui-access.h"
Macros
#define GIL(x) MATE_ICON_LIST(x)
#define GIL_CLASS(x) MATE_ICON_LIST_CLASS(x)
#define IS_GIL(x) MATE_IS_ICON_LIST(x)
#define DEFAULT_ROW_SPACING 4
#define DEFAULT_COL_SPACING 2
#define DEFAULT_TEXT_SPACING 2
#define DEFAULT_ICON_BORDER 2
#define SCROLL_TIMEOUT 30
#define gray50_width 2
#define gray50_height 2
Typedefs
typedef MateIconList Gil
typedef MateIconListClass GilClass
typedef MateIconListPrivate GilPrivate
Enumerations
enum {
SELECT_ICON , UNSELECT_ICON , FOCUS_ICON , UNFOCUS_ICON ,
TEXT_CHANGED , MOVE_CURSOR , TOGGLE_CURSOR_SELECTION , LAST_SIGNAL
}
enum SyncType { SYNC_INSERT , SYNC_REMOVE }
Functions
MATE_CLASS_BOILERPLATE (MateIconList, mate_icon_list, MateCanvas, MATE_TYPE_CANVAS)
int mate_icon_list_get_items_per_line (MateIconList *gil)
void mate_icon_list_select_all (MateIconList *gil)
int mate_icon_list_unselect_all (MateIconList *gil)
void mate_icon_list_insert_pixbuf (MateIconList *gil, int pos, GdkPixbuf *im, const char *icon_filename, const char *text)
void mate_icon_list_insert (MateIconList *gil, int pos, const char *icon_filename, const char *text)
int mate_icon_list_append_pixbuf (MateIconList *gil, GdkPixbuf *im, const char *icon_filename, const char *text)
int mate_icon_list_append (MateIconList *gil, const char *icon_filename, const char *text)
void mate_icon_list_remove (MateIconList *gil, int pos)
void mate_icon_list_clear (MateIconList *gil)
void mate_icon_list_focus_icon (MateIconList *gil, gint idx)
void mate_icon_list_select_icon (MateIconList *gil, int pos)
void mate_icon_list_unselect_icon (MateIconList *gil, int pos)
void mate_icon_list_set_icon_width (MateIconList *gil, int w)
void mate_icon_list_set_hadjustment (MateIconList *gil, GtkAdjustment *hadj)
void mate_icon_list_set_vadjustment (MateIconList *gil, GtkAdjustment *vadj)
void mate_icon_list_construct (MateIconList *gil, guint icon_width, GtkAdjustment *adj, int flags)
GtkWidget * mate_icon_list_new (guint icon_width, GtkAdjustment *adj, int flags)
void mate_icon_list_freeze (MateIconList *gil)
void mate_icon_list_thaw (MateIconList *gil)
GtkSelectionMode mate_icon_list_get_selection_mode (MateIconList *gil)
void mate_icon_list_set_selection_mode (MateIconList *gil, GtkSelectionMode mode)
void mate_icon_list_set_icon_data_full (MateIconList *gil, int pos, gpointer data, GDestroyNotify destroy)
void mate_icon_list_set_icon_data (MateIconList *gil, int pos, gpointer data)
gpointer mate_icon_list_get_icon_data (MateIconList *gil, int pos)
int mate_icon_list_find_icon_from_data (MateIconList *gil, gpointer data)
void mate_icon_list_set_row_spacing (MateIconList *gil, int pixels)
void mate_icon_list_set_col_spacing (MateIconList *gil, int pixels)
void mate_icon_list_set_text_spacing (MateIconList *gil, int pixels)
void mate_icon_list_set_icon_border (MateIconList *gil, int pixels)
void mate_icon_list_set_separators (MateIconList *gil, const char *sep)
void mate_icon_list_moveto (MateIconList *gil, int pos, double yalign)
GtkVisibility mate_icon_list_icon_is_visible (MateIconList *gil, int pos)
int mate_icon_list_get_icon_at (MateIconList *gil, int x, int y)
guint mate_icon_list_get_num_icons (MateIconList *gil)
GList * mate_icon_list_get_selection (MateIconList *gil)
gchar * mate_icon_list_get_icon_filename (MateIconList *gil, int idx)
int mate_icon_list_find_icon_from_filename (MateIconList *gil, const gchar *filename)
MateIconTextItem * mate_icon_list_get_icon_text_item (MateIconList *gil, int idx)
MateCanvasPixbuf * mate_icon_list_get_icon_pixbuf_item (MateIconList *gil, int idx)
Variables
Icon
Macro Definition Documentation
DEFAULT_COL_SPACING
#define DEFAULT_COL_SPACING 2
Definition at line 66 of file mate-icon-list.c.
DEFAULT_ICON_BORDER
#define DEFAULT_ICON_BORDER 2
Definition at line 68 of file mate-icon-list.c.
DEFAULT_ROW_SPACING
#define DEFAULT_ROW_SPACING 4
Definition at line 65 of file mate-icon-list.c.
DEFAULT_TEXT_SPACING
#define DEFAULT_TEXT_SPACING 2
Definition at line 67 of file mate-icon-list.c.
GIL
#define GIL (x) MATE_ICON_LIST(x)
Definition at line 56 of file mate-icon-list.c.
GIL_CLASS
#define GIL_CLASS (x) MATE_ICON_LIST_CLASS(x)
Definition at line 57 of file mate-icon-list.c.
gray50_height
#define gray50_height 2
Definition at line 1818 of file mate-icon-list.c.
gray50_width
#define gray50_width 2
Definition at line 1817 of file mate-icon-list.c.
IS_GIL
#define IS_GIL (x) MATE_IS_ICON_LIST(x)
Definition at line 58 of file mate-icon-list.c.
SCROLL_TIMEOUT
#define SCROLL_TIMEOUT 30
Definition at line 71 of file mate-icon-list.c.
Typedef Documentation
Gil
typedef MateIconList Gil
Definition at line 60 of file mate-icon-list.c.
GilClass
typedef MateIconListClass GilClass
Definition at line 61 of file mate-icon-list.c.
GilPrivate
typedef MateIconListPrivate GilPrivate
Definition at line 62 of file mate-icon-list.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SELECT_ICON
UNSELECT_ICON
FOCUS_ICON
UNFOCUS_ICON
TEXT_CHANGED
MOVE_CURSOR
TOGGLE_CURSOR_SELECTION
LAST_SIGNAL
Definition at line 75 of file mate-icon-list.c.
SyncType
enum SyncType
Enumerator
SYNC_INSERT
SYNC_REMOVE
Definition at line 86 of file mate-icon-list.c.
Function Documentation
MATE_CLASS_BOILERPLATE()
MATE_CLASS_BOILERPLATE (MateIconList , mate_icon_list , MateCanvas , MATE_TYPE_CANVAS)
mate_icon_list_get_type:
Registers the &MateIconList class if necessary, and returns the type ID associated to it.
Returns: The type ID of the &MateIconList class.
Definition at line 101 of file mate-icon-list.c.
References data.
mate_icon_list_append()
int mate_icon_list_append (MateIconList * gil, const char * icon_filename, const char * text)
mate_icon_list_append: @gil: An icon list. @icon_filename: Name of the file that holds the icon's image. @text: Text to be used for the icon's caption.
Appends an icon to the specified icon list. The icon's image is loaded from the specified file, and it is inserted at the @pos index.
Returns:
Definition at line 1252 of file mate-icon-list.c.
References Icon, IS_GIL, and NULL.
mate_icon_list_append_pixbuf()
int mate_icon_list_append_pixbuf (MateIconList * gil, GdkPixbuf * im, const char * icon_filename, const char * text)
mate_icon_list_append_pixbuf: @gil: An icon list. @im: Pixbuf image with the icon image. @icon_filename: Filename of the image file. @text: Text to be used for the icon's caption.
Appends an icon to the specified icon list. The icon is created from the specified Imlib image.
Returns:
Definition at line 1227 of file mate-icon-list.c.
References Icon, IS_GIL, and NULL.
Referenced by main().
mate_icon_list_clear()
void mate_icon_list_clear (MateIconList * gil)
mate_icon_list_clear: @gil: An icon list.
Clears the contents for the icon list by removing all the icons. If destroy handlers were specified for any of the icons, they will be called with the appropriate data.
Definition at line 1384 of file mate-icon-list.c.
References _accessibility_get_atk_object(), _MateIconList::_priv, Icon, IS_GIL, NULL, and TRUE.
Referenced by mate_icon_selection_clear().
mate_icon_list_construct()
void mate_icon_list_construct (MateIconList * gil, guint icon_width, GtkAdjustment * adj, int flags)
mate_icon_list_construct: @gil: An icon list. @icon_width: Width for the icon columns. @adj: @flags: A combination of MATE_ICON_LIST_IS_EDITABLE and MATE_ICON_LIST_STATIC_TEXT.
Constructor for the icon list, to be used by derived classes.
Definition at line 2544 of file mate-icon-list.c.
References _MateIconList::_priv, IS_GIL, MATE_ICON_LIST_IS_EDITABLE, mate_icon_list_set_icon_width(), mate_icon_list_set_vadjustment(), MATE_ICON_LIST_STATIC_TEXT, and NULL.
Referenced by mate_icon_list_new().
mate_icon_list_find_icon_from_data()
int mate_icon_list_find_icon_from_data (MateIconList * gil, gpointer data)
mate_icon_list_find_icon_from_data: @gil: An icon list. @data: Data pointer associated to an icon.
Returns: The index of the icon whose user data has been set to @data, or -1 if no icon has this data associated to it.
Definition at line 2762 of file mate-icon-list.c.
References _MateIconList::_priv, data, Icon, IS_GIL, and NULL.
mate_icon_list_find_icon_from_filename()
int mate_icon_list_find_icon_from_filename (MateIconList * gil, const gchar * filename)
mate_icon_list_find_icon_from_filename: @gil: An icon list. @filename: Filename of an icon.
Returns: The index of the icon whose filename is @filename or -1 if there is no icon with this filename.
Definition at line 3125 of file mate-icon-list.c.
References _MateIconList::_priv, Icon, IS_GIL, and NULL.
mate_icon_list_focus_icon()
void mate_icon_list_focus_icon (MateIconList * gil, gint idx)
Definition at line 1474 of file mate-icon-list.c.
References FOCUS_ICON, idx, and IS_GIL.
mate_icon_list_freeze()
void mate_icon_list_freeze (MateIconList * gil)
mate_icon_list_freeze: @gil: An icon list.
Freezes an icon list so that any changes made to it will not be reflected on the screen until it is thawed with mate_icon_list_thaw(). It is recommended to freeze the icon list before inserting or deleting many icons, for example, so that the layout process will only be executed once, when the icon list is finally thawed.
You can call this function multiple times, but it must be balanced with the same number of calls to mate_icon_list_thaw() before the changes will take effect.
Definition at line 2617 of file mate-icon-list.c.
References _MateIconList::_priv, IS_GIL, and NULL.
Referenced by mate_icon_selection_show_icons().
mate_icon_list_get_icon_at()
int mate_icon_list_get_icon_at (MateIconList * gil, int x, int y)
mate_icon_list_get_icon_at: @gil: An icon list. @x: X position in the icon list window. @y: Y position in the icon list window.
Returns: The index of the icon that is under the specified coordinates, which are relative to the icon list's window. If there is no icon in that position, -1 is returned.
Definition at line 3008 of file mate-icon-list.c.
References _MateIconList::_priv, dist, Icon, IS_GIL, item, and NULL.
mate_icon_list_get_icon_data()
gpointer mate_icon_list_get_icon_data (MateIconList * gil, int pos)
mate_icon_list_get_icon_data: @gil: An icon list. @pos: Index of an icon.
Returns: The user data pointer associated to the icon at the index specified by @pos.
Definition at line 2741 of file mate-icon-list.c.
References _MateIconList::_priv, Icon, IS_GIL, and NULL.
mate_icon_list_get_icon_filename()
gchar * mate_icon_list_get_icon_filename (MateIconList * gil, int idx)
mate_icon_list_get_icon_filename: @gil: An icon list. @idx: Index of an @icon.
Returns: The filename of the icon with index @idx.
Definition at line 3103 of file mate-icon-list.c.
References _MateIconList::_priv, Icon, idx, IS_GIL, and NULL.
Referenced by mate_icon_selection_get_icon(), and mate_icon_selection_select_icon().
mate_icon_list_get_icon_pixbuf_item()
MateCanvasPixbuf * mate_icon_list_get_icon_pixbuf_item (MateIconList * gil, int idx)
Definition at line 3166 of file mate-icon-list.c.
References _MateIconList::_priv, Icon, idx, IS_GIL, and NULL.
mate_icon_list_get_icon_text_item()
MateIconTextItem * mate_icon_list_get_icon_text_item (MateIconList * gil, int idx)
Definition at line 3149 of file mate-icon-list.c.
References _MateIconList::_priv, Icon, idx, IS_GIL, and NULL.
mate_icon_list_get_items_per_line()
int mate_icon_list_get_items_per_line (MateIconList * gil)
mate_icon_list_get_items_per_line: @gil: An icon list.
Returns: The number of icons that fit in a line or row.
Definition at line 280 of file mate-icon-list.c.
References IS_GIL, and NULL.
mate_icon_list_get_num_icons()
guint mate_icon_list_get_num_icons (MateIconList * gil)
mate_icon_list_get_num_icons: @gil: An icon list.
Returns: The number of icons in the icon list.
Definition at line 3072 of file mate-icon-list.c.
References _MateIconList::_priv, and MATE_IS_ICON_LIST.
Referenced by mate_icon_list_select_all(), and mate_icon_selection_select_icon().
mate_icon_list_get_selection()
GList * mate_icon_list_get_selection (MateIconList * gil)
mate_icon_list_get_selection: @gil: An icon list.
Returns: A list of integers with the indices of the currently selected icons.
Definition at line 3087 of file mate-icon-list.c.
References _MateIconList::_priv, MATE_IS_ICON_LIST, and NULL.
Referenced by mate_icon_selection_get_icon().
mate_icon_list_get_selection_mode()
GtkSelectionMode mate_icon_list_get_selection_mode (MateIconList * gil)
mate_icon_list_get_selection_mode: @gil: An icon list.
Returns: The current selection mode for an icon list.
Definition at line 2664 of file mate-icon-list.c.
References _MateIconList::_priv, IS_GIL, and NULL.
mate_icon_list_icon_is_visible()
GtkVisibility mate_icon_list_icon_is_visible (MateIconList * gil, int pos)
mate_icon_list_icon_is_visible: @gil: An icon list. @pos: Index of an icon.
Returns: Whether the icon at the index specified by @pos is visible. This will be GTK_VISIBILITY_NONE if the icon is not visible at all, GTK_VISIBILITY_PARTIAL if the icon is at least partially shown, and GTK_VISIBILITY_FULL if the icon is fully visible.
Definition at line 2959 of file mate-icon-list.c.
References _MateIconList::_priv, _MateIconList::adj, IS_GIL, and NULL.
mate_icon_list_insert()
void mate_icon_list_insert (MateIconList * gil, int pos, const char * icon_filename, const char * text)
mate_icon_list_insert: @gil: An icon list. @pos: Position at which the new icon should be inserted. @icon_filename: Name of the file that holds the icon's image. @text: Text to be used for the icon's caption.
Inserts an icon in the specified icon list. The icon's image is loaded from the specified file, and it is inserted at the @pos index.
Definition at line 1202 of file mate-icon-list.c.
References Icon, IS_GIL, and NULL.
mate_icon_list_insert_pixbuf()
void mate_icon_list_insert_pixbuf (MateIconList * gil, int pos, GdkPixbuf * im, const char * icon_filename, const char * text)
mate_icon_list_insert_pixbuf: @gil: An icon list. @pos: Position at which the new icon should be inserted. @im: Pixbuf image with the icon image. @icon_filename: Filename of the image file. @text: Text to be used for the icon's caption.
Inserts an icon in the specified icon list. The icon is created from the specified Imlib image, and it is inserted at the @pos index.
Definition at line 1177 of file mate-icon-list.c.
References Icon, IS_GIL, and NULL.
mate_icon_list_moveto()
void mate_icon_list_moveto (MateIconList * gil, int pos, double yalign)
mate_icon_list_moveto: @gil: An icon list. @pos: Index of an icon. @yalign: Vertical alignment of the icon.
Makes the icon whose index is @pos be visible on the screen. The icon list gets scrolled so that the icon is visible. An alignment of 0.0 represents the top of the visible part of the icon list, and 1.0 represents the bottom. An icon can be centered on the icon list.
Definition at line 2918 of file mate-icon-list.c.
References _MateIconList::_priv, _MateIconList::adj, IS_GIL, and NULL.
mate_icon_list_new()
GtkWidget * mate_icon_list_new (guint icon_width, GtkAdjustment * adj, int flags)
mate_icon_list_new: [constructor] @icon_width: Width for the icon columns. @adj: @flags: A combination of MATE_ICON_LIST_IS_EDITABLE and MATE_ICON_LIST_STATIC_TEXT.
Creates a new icon list widget. The icon columns are allocated a width of @icon_width pixels. Icon captions will be word-wrapped to this width as well.
If @flags has the MATE_ICON_LIST_IS_EDITABLE flag set, then the user will be able to edit the text in the icon captions, and the "text_changed" signal will be emitted when an icon's text is changed.
If @flags has the MATE_ICON_LIST_STATIC_TEXT flags set, then the text for the icon captions will not be copied inside the icon list; it will only store the pointers to the original text strings specified by the application. This is intended to save memory. If this flag is not set, then the text strings will be copied and managed internally.
Returns: a newly-created icon list widget
Definition at line 2588 of file mate-icon-list.c.
References mate_icon_list_construct(), MATE_TYPE_ICON_LIST, and NULL.
Referenced by main().
mate_icon_list_remove()
void mate_icon_list_remove (MateIconList * gil, int pos)
mate_icon_list_remove: @gil: An icon list. @pos: Index of the icon that should be removed.
Removes the icon at index position @pos. If a destroy handler was specified for that icon, it will be called with the appropriate data.
Definition at line 1294 of file mate-icon-list.c.
References _accessibility_get_atk_object(), _MateIconList::_priv, FALSE, Icon, IS_GIL, mate_icon_list_select_icon(), mate_icon_list_unselect_icon(), NULL, SYNC_REMOVE, and TRUE.
mate_icon_list_select_all()
void mate_icon_list_select_all (MateIconList * gil)
mate_icon_list_select_all: @gil: An icon list.
Definition at line 573 of file mate-icon-list.c.
References IS_GIL, mate_icon_list_get_num_icons(), mate_icon_list_select_icon(), and NULL.
mate_icon_list_select_icon()
void mate_icon_list_select_icon (MateIconList * gil, int pos)
mate_icon_list_select_icon: @gil: An icon list. @pos: Index of the icon to be selected.
Selects the icon at the index specified by @pos.
Definition at line 1524 of file mate-icon-list.c.
References IS_GIL, and NULL.
Referenced by mate_icon_list_remove(), mate_icon_list_select_all(), and mate_icon_selection_select_icon().
mate_icon_list_set_col_spacing()
void mate_icon_list_set_col_spacing (MateIconList * gil, int pixels)
mate_icon_list_set_col_spacing: @gil: An icon list. @pixels: Number of pixels for inter-column spacing.
Sets the spacing to be used between columns of icons.
Definition at line 2825 of file mate-icon-list.c.
References _MateIconList::_priv, IS_GIL, and NULL.
mate_icon_list_set_hadjustment()
void mate_icon_list_set_hadjustment (MateIconList * gil, GtkAdjustment * hadj)
mate_icon_list_set_hadjustment: @gil: An icon list. @hadj: Adjustment to be used for horizontal scrolling.
Sets the adjustment to be used for horizontal scrolling. This is normally not required, as the icon list can be simply inserted in a &GtkScrolledWindow and scrolling will be handled automatically.
Definition at line 2449 of file mate-icon-list.c.
References _MateIconList::hadj, IS_GIL, and NULL.
mate_icon_list_set_icon_border()
void mate_icon_list_set_icon_border (MateIconList * gil, int pixels)
mate_icon_list_set_icon_border: @gil: An icon list. @pixels: Number of border pixels to be used around an icon's image.
Sets the width of the border to be displayed around an icon's image. This is currently not implemented.
Definition at line 2864 of file mate-icon-list.c.
References _MateIconList::_priv, IS_GIL, and NULL.
mate_icon_list_set_icon_data()
void mate_icon_list_set_icon_data (MateIconList * gil, int pos, gpointer data)
mate_icon_list_get_icon_data: @gil: An icon list. @pos: Index of an icon. @data: User data to set on the icon.
Associates the @data pointer to the icon at the index specified by @pos.
Definition at line 2727 of file mate-icon-list.c.
References data, mate_icon_list_set_icon_data_full(), and NULL.
mate_icon_list_set_icon_data_full()
void mate_icon_list_set_icon_data_full (MateIconList * gil, int pos, gpointer data, GDestroyNotify destroy)
mate_icon_list_set_icon_data_full: @gil: An icon list. @pos: Index of an icon. @data: User data to set on the icon. @destroy: Destroy notification handler for the icon.
Associates the @data pointer to the icon at the index specified by @pos. The @destroy argument points to a function that will be called when the icon is destroyed, or NULL if no function is to be called when this happens.
Definition at line 2703 of file mate-icon-list.c.
References _MateIconList::_priv, data, Icon, IS_GIL, and NULL.
Referenced by mate_icon_list_set_icon_data().
mate_icon_list_set_icon_width()
void mate_icon_list_set_icon_width (MateIconList * gil, int w)
mate_icon_list_set_icon_width: @gil: An icon list. @w: New width for the icon columns.
Sets the amount of horizontal space allocated to the icons, i.e. the column width of the icon list.
Definition at line 2413 of file mate-icon-list.c.
References _MateIconList::_priv, IS_GIL, NULL, and TRUE.
Referenced by mate_icon_list_construct().
mate_icon_list_set_row_spacing()
void mate_icon_list_set_row_spacing (MateIconList * gil, int pixels)
mate_icon_list_set_row_spacing: @gil: An icon list. @pixels: Number of pixels for inter-row spacing.
Sets the spacing to be used between rows of icons.
Definition at line 2806 of file mate-icon-list.c.
References _MateIconList::_priv, IS_GIL, and NULL.
mate_icon_list_set_selection_mode()
void mate_icon_list_set_selection_mode (MateIconList * gil, GtkSelectionMode mode)
mate_icon_list_set_selection_mode: @gil: An icon list. @mode: New selection mode.
Sets the selection mode for an icon list. The GTK_SELECTION_MULTIPLE and GTK_SELECTION_EXTENDED modes are considered equivalent.
Definition at line 2681 of file mate-icon-list.c.
References _MateIconList::_priv, IS_GIL, and NULL.
Referenced by main().
mate_icon_list_set_separators()
void mate_icon_list_set_separators (MateIconList * gil, const char * sep)
mate_icon_list_set_separators: @gil: An icon list. @sep: String with characters to be used as word separators.
Sets the characters that can be used as word separators when doing word-wrapping in the icon text captions.
Definition at line 2884 of file mate-icon-list.c.
References _MateIconList::_priv, IS_GIL, NULL, and TRUE.
mate_icon_list_set_text_spacing()
void mate_icon_list_set_text_spacing (MateIconList * gil, int pixels)
mate_icon_list_set_text_spacing: @gil: An icon list. @pixels: Number of pixels between an icon's image and its caption.
Sets the spacing to be used between an icon's image and its text caption.
Definition at line 2844 of file mate-icon-list.c.
References _MateIconList::_priv, IS_GIL, and NULL.
mate_icon_list_set_vadjustment()
void mate_icon_list_set_vadjustment (MateIconList * gil, GtkAdjustment * vadj)
mate_icon_list_set_vadjustment: @gil: An icon list. @vadj: Adjustment to be used for horizontal scrolling.
Sets the adjustment to be used for vertical scrolling. This is normally not required, as the icon list can be simply inserted in a &GtkScrolledWindow and scrolling will be handled automatically.
Definition at line 2499 of file mate-icon-list.c.
References _MateIconList::adj, IS_GIL, and NULL.
Referenced by mate_icon_list_construct().
mate_icon_list_thaw()
void mate_icon_list_thaw (MateIconList * gil)
mate_icon_list_thaw: @gil: An icon list.
Thaws the icon list and performs any pending layout operations. This is to be used in conjunction with mate_icon_list_freeze().
Definition at line 2640 of file mate-icon-list.c.
References _MateIconList::_priv, IS_GIL, and NULL.
Referenced by mate_icon_selection_show_icons().
mate_icon_list_unselect_all()
int mate_icon_list_unselect_all (MateIconList * gil)
mate_icon_list_unselect_all: @gil: An icon list.
Returns: The number of icons in the icon list
Definition at line 591 of file mate-icon-list.c.
References NULL.
mate_icon_list_unselect_icon()
void mate_icon_list_unselect_icon (MateIconList * gil, int pos)
mate_icon_list_unselect_icon: @gil: An icon list. @pos: Index of the icon to be unselected.
Unselects the icon at the index specified by @pos.
Definition at line 1560 of file mate-icon-list.c.
References IS_GIL, and NULL.
Referenced by mate_icon_list_remove().
Variable Documentation
Icon
Icon
Definition at line 125 of file mate-icon-list.c.
Referenced by mate_icon_list_append(), mate_icon_list_append_pixbuf(), mate_icon_list_clear(), mate_icon_list_find_icon_from_data(), mate_icon_list_find_icon_from_filename(), mate_icon_list_get_icon_at(), mate_icon_list_get_icon_data(), mate_icon_list_get_icon_filename(), mate_icon_list_get_icon_pixbuf_item(), mate_icon_list_get_icon_text_item(), mate_icon_list_insert(), mate_icon_list_insert_pixbuf(), mate_icon_list_remove(), and mate_icon_list_set_icon_data_full().