MATE Desktop Environment: mate-theme-parser.h File Reference
mate-theme-parser.h File Reference
#include <glib.h>
Macros
#define MATE_THEME_FILE_PARSE_ERROR mate_theme_file_parse_error_quark()
Typedefs
typedef struct _MateThemeFile MateThemeFile
typedef void(* MateThemeFileSectionFunc) (MateThemeFile *df, const char *name, gpointer data)
typedef void(* MateThemeFileLineFunc) (MateThemeFile *df, const char *key, const char *locale, const char *value, gpointer data)
Enumerations
enum MateThemeFileParseError { MATE_THEME_FILE_PARSE_ERROR_INVALID_SYNTAX , MATE_THEME_FILE_PARSE_ERROR_INVALID_ESCAPES , MATE_THEME_FILE_PARSE_ERROR_INVALID_CHARS }
Functions
GQuark mate_theme_file_parse_error_quark (void)
MateThemeFile * mate_theme_file_new_from_string (char *data, GError **error)
char * mate_theme_file_to_string (MateThemeFile *df)
void mate_theme_file_free (MateThemeFile *df)
void mate_theme_file_foreach_section (MateThemeFile *df, MateThemeFileSectionFunc func, gpointer user_data)
void mate_theme_file_foreach_key (MateThemeFile *df, const char *section, gboolean include_localized, MateThemeFileLineFunc func, gpointer user_data)
gboolean mate_theme_file_get_raw (MateThemeFile *df, const char *section, const char *keyname, const char *locale, char **val)
gboolean mate_theme_file_get_integer (MateThemeFile *df, const char *section, const char *keyname, int *val)
gboolean mate_theme_file_get_string (MateThemeFile *df, const char *section, const char *keyname, char **val)
gboolean mate_theme_file_get_locale_string (MateThemeFile *df, const char *section, const char *keyname, char **val)
Macro Definition Documentation
MATE_THEME_FILE_PARSE_ERROR
#define MATE_THEME_FILE_PARSE_ERROR mate_theme_file_parse_error_quark()
Definition at line 52 of file mate-theme-parser.h.
Typedef Documentation
MateThemeFile
typedef struct _MateThemeFile MateThemeFile
Definition at line 31 of file mate-theme-parser.h.
MateThemeFileLineFunc
typedef void(* MateThemeFileLineFunc) (MateThemeFile *df, const char *key, const char *locale, const char *value, gpointer data)
Definition at line 39 of file mate-theme-parser.h.
MateThemeFileSectionFunc
typedef void(* MateThemeFileSectionFunc) (MateThemeFile *df, const char *name, gpointer data)
Definition at line 33 of file mate-theme-parser.h.
Enumeration Type Documentation
MateThemeFileParseError
enum MateThemeFileParseError
Enumerator
MATE_THEME_FILE_PARSE_ERROR_INVALID_SYNTAX
MATE_THEME_FILE_PARSE_ERROR_INVALID_ESCAPES
MATE_THEME_FILE_PARSE_ERROR_INVALID_CHARS
Definition at line 45 of file mate-theme-parser.h.
Function Documentation
mate_theme_file_foreach_key()
void mate_theme_file_foreach_key (MateThemeFile * df, const char * section_name, gboolean include_localized, MateThemeFileLineFunc func, gpointer user_data)
mate_theme_file_foreach_key: @df: a MateThemeFile.
Definition at line 808 of file mate-theme-parser.c.
References user_data.
mate_theme_file_foreach_section()
void mate_theme_file_foreach_section (MateThemeFile * df, MateThemeFileSectionFunc func, gpointer user_data)
mate_theme_file_foreach_section: @df: a MateThemeFile. @func: a MateThemeFileSectionFunc @user_data: a pointer to the user data.
Calls @func for each section in the MateThemeFile with @user_data.
Since: 2.2
Definition at line 778 of file mate-theme-parser.c.
References user_data.
mate_theme_file_free()
void mate_theme_file_free (MateThemeFile * df)
mate_theme_file_free: @df: a MateThemeFile.
Frees the MateThemeFile structure.
Since: 2.2
Definition at line 144 of file mate-theme-parser.c.
mate_theme_file_get_integer()
gboolean mate_theme_file_get_integer (MateThemeFile * df, const char * section, const char * keyname, int * val)
mate_theme_file_get_integer: @df: a MateThemeFile.
property page to display
@keyname: the key name. @val: an int*.
This function calls mate_theme_file_get_raw() with the parameters. If mate_theme_file_get_raw returns TRUE, then converts the value string filled in by the function to an integer and writes it in @val.
Returns: TRUE if mate_theme_file_get_raw returns TRUE, FALSE otherwise.
Since: 2.2
Definition at line 952 of file mate-theme-parser.c.
References FALSE, mate_theme_file_get_raw(), NULL, and TRUE.
mate_theme_file_get_locale_string()
gboolean mate_theme_file_get_locale_string (MateThemeFile * df, const char * section, const char * keyname, char ** val)
mate_theme_file_get_locale_string: @df: A MateThemeFile
property page to display
@keyname: the keyname. @val: a char **.
Calculates the locale if the current_locale field of @df is NULL. Then calls mate_theme_file_get_raw() with the parameters and returns the boolean value obtained.
Returns: a gboolean value.
Since: 2.2
Definition at line 885 of file mate-theme-parser.c.
References mate_theme_file_get_raw(), NULL, and TRUE.
mate_theme_file_get_raw()
gboolean mate_theme_file_get_raw (MateThemeFile * df, const char * section_name, const char * keyname, const char * locale, char ** val)
mate_theme_file_get_raw: @df: A MateThemeFile.
property page to display
@keyname: the string representing the key name. @locale: the string representing the locale. @val: a char**.
Searches section name and line in the MateThemeFile data structure. If found, sets the @val to value field in MateThemeFileLine and returns a boolean value.
Returns: TRUE if section and line were found in the MateThemeFile, FALSE otherwise.
Since: 2.2
Definition at line 739 of file mate-theme-parser.c.
References FALSE, NULL, and TRUE.
Referenced by mate_theme_file_get_integer(), mate_theme_file_get_locale_string(), and mate_theme_file_get_string().
mate_theme_file_get_string()
gboolean mate_theme_file_get_string (MateThemeFile * df, const char * section, const char * keyname, char ** val)
mate_theme_file_get_string: @df: A MateThemeFile.
property page to display
@keyname: the key name. @val: a char**.
This function calls mate_theme_file_get_raw() with the parameters and returns the boolean value.
Returns: a #gboolean value.
Since: 2.2
Definition at line 929 of file mate-theme-parser.c.
References mate_theme_file_get_raw(), and NULL.
mate_theme_file_new_from_string()
MateThemeFile * mate_theme_file_new_from_string (char * data, GError ** error)
mate_theme_file_new_from_string: @data: the string used to create a MateThemeFile. @error: location to store the error occuring, or NULL to ignore errors
Creates a MateThemeFile from the data string passed.
Returns: a MateThemeFile.
Since: 2.2
Definition at line 575 of file mate-theme-parser.c.
References data, error, and NULL.
mate_theme_file_parse_error_quark()
GQuark mate_theme_file_parse_error_quark (void)
mate_theme_file_parse_error_quark:
This function gets a #GQuark representing the error string.
Returns: a #GQuark.
Since: 2.2
Definition at line 102 of file mate-theme-parser.c.
mate_theme_file_to_string()
char * mate_theme_file_to_string (MateThemeFile * df)
mate_theme_file_to_string: @df: A MateThemeFile
This function retrieves the string representing the MateThemeFile.
Returns: a char *.
Since: 2.2
Definition at line 621 of file mate-theme-parser.c.
References FALSE, and TRUE.