MATE Desktop Environment: msd-osd-window.h File Reference
msd-osd-window.h File Reference
#include <glib-object.h>
#include <gtk/gtk.h>
Classes
struct MsdOsdWindow
struct MsdOsdWindowClass
Macros
#define MSD_OSD_WINDOW_FG_ALPHA 1.0
#define MSD_TYPE_OSD_WINDOW (msd_osd_window_get_type ())
#define MSD_OSD_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MSD_TYPE_OSD_WINDOW, MsdOsdWindow))
#define MSD_OSD_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MSD_TYPE_OSD_WINDOW, MsdOsdWindowClass))
#define MSD_IS_OSD_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MSD_TYPE_OSD_WINDOW))
#define MSD_IS_OSD_WINDOW_CLASS(klass) (G_TYPE_INSTANCE_GET_CLASS ((klass), MSD_TYPE_OSD_WINDOW))
#define MSD_OSD_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MSD_TYPE_OSD_WINDOW, MsdOsdWindowClass))
Typedefs
typedef struct MsdOsdWindow MsdOsdWindow
typedef struct MsdOsdWindowClass MsdOsdWindowClass
typedef struct MsdOsdWindowPrivate MsdOsdWindowPrivate
Functions
GType msd_osd_window_get_type (void)
GtkWidget * msd_osd_window_new (void)
gboolean msd_osd_window_is_composited (MsdOsdWindow *window)
gboolean msd_osd_window_is_valid (MsdOsdWindow *window)
void msd_osd_window_update_and_hide (MsdOsdWindow *window)
Macro Definition Documentation
MSD_IS_OSD_WINDOW
#define MSD_IS_OSD_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MSD_TYPE_OSD_WINDOW))
Definition at line 57 of file mate-settings-daemon/plugins/common/msd-osd-window.h.
MSD_IS_OSD_WINDOW_CLASS
#define MSD_IS_OSD_WINDOW_CLASS (klass) (G_TYPE_INSTANCE_GET_CLASS ((klass), MSD_TYPE_OSD_WINDOW))
Definition at line 58 of file mate-settings-daemon/plugins/common/msd-osd-window.h.
MSD_OSD_WINDOW
#define MSD_OSD_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MSD_TYPE_OSD_WINDOW, MsdOsdWindow))
Definition at line 55 of file mate-settings-daemon/plugins/common/msd-osd-window.h.
MSD_OSD_WINDOW_CLASS
#define MSD_OSD_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MSD_TYPE_OSD_WINDOW, MsdOsdWindowClass))
Definition at line 56 of file mate-settings-daemon/plugins/common/msd-osd-window.h.
MSD_OSD_WINDOW_FG_ALPHA
#define MSD_OSD_WINDOW_FG_ALPHA 1.0
Definition at line 52 of file mate-settings-daemon/plugins/common/msd-osd-window.h.
MSD_OSD_WINDOW_GET_CLASS
#define MSD_OSD_WINDOW_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MSD_TYPE_OSD_WINDOW, MsdOsdWindowClass))
Definition at line 59 of file mate-settings-daemon/plugins/common/msd-osd-window.h.
MSD_TYPE_OSD_WINDOW
#define MSD_TYPE_OSD_WINDOW (msd_osd_window_get_type ())
Definition at line 54 of file mate-settings-daemon/plugins/common/msd-osd-window.h.
Typedef Documentation
MsdOsdWindow
typedef struct MsdOsdWindow MsdOsdWindow
Definition at line 61 of file mate-settings-daemon/plugins/common/msd-osd-window.h.
MsdOsdWindowClass
typedef struct MsdOsdWindowClass MsdOsdWindowClass
Definition at line 62 of file mate-settings-daemon/plugins/common/msd-osd-window.h.
MsdOsdWindowPrivate
typedef struct MsdOsdWindowPrivate MsdOsdWindowPrivate
Definition at line 63 of file mate-settings-daemon/plugins/common/msd-osd-window.h.
Function Documentation
msd_osd_window_get_type()
GType msd_osd_window_get_type (void)
msd_osd_window_is_composited()
gboolean msd_osd_window_is_composited (MsdOsdWindow * window)
msd_osd_window_is_composited: @window: a MsdOsdWindow
Return value: whether the window was created on a composited screen.
Definition at line 415 of file mate-power-manager/src/msd-osd-window.c.
References MsdOsdWindow::priv.
msd_osd_window_is_valid()
gboolean msd_osd_window_is_valid (MsdOsdWindow * window)
msd_osd_window_is_valid: @window: a MsdOsdWindow
Return value: TRUE if the @window's idea of being composited matches whether its current screen is actually composited and whether the scale factor has not changed since last draw.
msd_osd_window_is_valid: @window: a MsdOsdWindow
Return value: TRUE if the @window's idea of being composited matches whether its current screen is actually composited, and whether the scale factor has not changed since last draw.
Definition at line 429 of file mate-power-manager/src/msd-osd-window.c.
References MsdOsdWindow::priv.
msd_osd_window_new()
GtkWidget * msd_osd_window_new (void)
Definition at line 475 of file mate-power-manager/src/msd-osd-window.c.
References MSD_TYPE_OSD_WINDOW, and NULL.
msd_osd_window_update_and_hide()
void msd_osd_window_update_and_hide (MsdOsdWindow * window)
msd_osd_window_update_and_hide: @window: a MsdOsdWindow
Queues the @window for immediate drawing, and queues a timer to hide the window.
Definition at line 487 of file mate-power-manager/src/msd-osd-window.c.
References MsdOsdWindow::priv.
Referenced by msd_media_keys_window_set_action(), msd_media_keys_window_set_action_custom(), and msd_media_keys_window_set_action_custom().