MATE Desktop Environment: mate-window-properties.c File Reference
mate-window-properties.c File Reference
#include <stdlib.h>
#include <glib/gi18n.h>
#include <string.h>
#include <gdk/gdkx.h>
#include "mate-metacity-support.h"
#include "wm-common.h"
#include "capplet-util.h"
#include <X11/Xlib.h>
#include <X11/keysym.h>
Macros
#define MARCO_SCHEMA "org.mate.Marco.general"
#define INTERFACE_SCHEMA "org.mate.interface"
#define GTK_BUTTON_LAYOUT_KEY "gtk-decoration-layout"
#define MARCO_CENTER_NEW_WINDOWS_KEY "center-new-windows"
#define MARCO_ALLOW_TILING_KEY "allow-tiling"
#define MARCO_ALLOW_TOP_TILING_KEY "allow-top-tiling"
#define MARCO_SHOW_TAB_BORDER_KEY "show-tab-border"
#define MARCO_BUTTON_LAYOUT_KEY "button-layout"
#define MARCO_DOUBLE_CLICK_TITLEBAR_KEY "action-double-click-titlebar"
#define MARCO_MIDDLE_CLICK_TITLEBAR_KEY "action-middle-click-titlebar"
#define MARCO_RIGHT_CLICK_TITLEBAR_KEY "action-right-click-titlebar"
#define MARCO_SCROLL_UP_TITLEBAR_KEY "action-scroll-up-titlebar"
#define MARCO_SCROLL_DOWN_TITLEBAR_KEY "action-scroll-down-titlebar"
#define MARCO_FOCUS_KEY "focus-mode"
#define MARCO_AUTORAISE_KEY "auto-raise"
#define MARCO_AUTORAISE_DELAY_KEY "auto-raise-delay"
#define MARCO_MOUSE_MODIFIER_KEY "mouse-button-modifier"
#define MARCO_COMPOSITING_MANAGER_KEY "compositing-manager"
#define MARCO_COMPOSITING_FAST_ALT_TAB_KEY "compositing-fast-alt-tab"
#define GET_WIDGET(x) GTK_WIDGET(gtk_builder_get_object(builder, x))
Enumerations
enum {
MARCO_BUTTON_LAYOUT_RIGHT_WITH_MENU = 0 , MARCO_BUTTON_LAYOUT_LEFT_WITH_MENU , MARCO_BUTTON_LAYOUT_RIGHT , MARCO_BUTTON_LAYOUT_LEFT ,
MARCO_BUTTON_LAYOUT_COUNT
}
enum {
ACTION_TITLEBAR_CLOSE , ACTION_TITLEBAR_MINIMIZE , ACTION_TITLEBAR_TOGGLE_MAXIMIZE , ACTION_TITLEBAR_TOGGLE_MAXIMIZE_HORIZONTALLY ,
ACTION_TITLEBAR_TOGGLE_MAXIMIZE_VERTICALLY , ACTION_TITLEBAR_TOGGLE_SHADE , ACTION_TITLEBAR_SHADE , ACTION_TITLEBAR_UNSHADE ,
ACTION_TITLEBAR_RAISE , ACTION_TITLEBAR_LOWER , ACTION_TITLEBAR_TOGGLE_STICK , ACTION_TITLEBAR_TOGGLE_ABOVE ,
ACTION_TITLEBAR_MENU , ACTION_TITLEBAR_NONE
}
enum { FOCUS_MODE_CLICK , FOCUS_MODE_SLOPPY , FOCUS_MODE_MOUSE }
Functions
int main (int argc, char **argv)
Macro Definition Documentation
GET_WIDGET
#define GET_WIDGET (x) GTK_WIDGET(gtk_builder_get_object(builder, x))
GTK_BUTTON_LAYOUT_KEY
#define GTK_BUTTON_LAYOUT_KEY "gtk-decoration-layout"
Definition at line 45 of file mate-window-properties.c.
INTERFACE_SCHEMA
#define INTERFACE_SCHEMA "org.mate.interface"
Definition at line 43 of file mate-window-properties.c.
MARCO_ALLOW_TILING_KEY
#define MARCO_ALLOW_TILING_KEY "allow-tiling"
Definition at line 48 of file mate-window-properties.c.
MARCO_ALLOW_TOP_TILING_KEY
#define MARCO_ALLOW_TOP_TILING_KEY "allow-top-tiling"
Definition at line 49 of file mate-window-properties.c.
MARCO_AUTORAISE_DELAY_KEY
#define MARCO_AUTORAISE_DELAY_KEY "auto-raise-delay"
Definition at line 59 of file mate-window-properties.c.
MARCO_AUTORAISE_KEY
#define MARCO_AUTORAISE_KEY "auto-raise"
Definition at line 58 of file mate-window-properties.c.
MARCO_BUTTON_LAYOUT_KEY
#define MARCO_BUTTON_LAYOUT_KEY "button-layout"
Definition at line 51 of file mate-window-properties.c.
MARCO_CENTER_NEW_WINDOWS_KEY
#define MARCO_CENTER_NEW_WINDOWS_KEY "center-new-windows"
Definition at line 47 of file mate-window-properties.c.
MARCO_COMPOSITING_FAST_ALT_TAB_KEY
#define MARCO_COMPOSITING_FAST_ALT_TAB_KEY "compositing-fast-alt-tab"
Definition at line 63 of file mate-window-properties.c.
MARCO_COMPOSITING_MANAGER_KEY
#define MARCO_COMPOSITING_MANAGER_KEY "compositing-manager"
Definition at line 62 of file mate-window-properties.c.
MARCO_DOUBLE_CLICK_TITLEBAR_KEY
#define MARCO_DOUBLE_CLICK_TITLEBAR_KEY "action-double-click-titlebar"
Definition at line 52 of file mate-window-properties.c.
MARCO_FOCUS_KEY
#define MARCO_FOCUS_KEY "focus-mode"
Definition at line 57 of file mate-window-properties.c.
MARCO_MIDDLE_CLICK_TITLEBAR_KEY
#define MARCO_MIDDLE_CLICK_TITLEBAR_KEY "action-middle-click-titlebar"
Definition at line 53 of file mate-window-properties.c.
MARCO_MOUSE_MODIFIER_KEY
#define MARCO_MOUSE_MODIFIER_KEY "mouse-button-modifier"
Definition at line 60 of file mate-window-properties.c.
MARCO_RIGHT_CLICK_TITLEBAR_KEY
#define MARCO_RIGHT_CLICK_TITLEBAR_KEY "action-right-click-titlebar"
Definition at line 54 of file mate-window-properties.c.
MARCO_SCHEMA
#define MARCO_SCHEMA "org.mate.Marco.general"
Definition at line 42 of file mate-window-properties.c.
MARCO_SCROLL_DOWN_TITLEBAR_KEY
#define MARCO_SCROLL_DOWN_TITLEBAR_KEY "action-scroll-down-titlebar"
Definition at line 56 of file mate-window-properties.c.
MARCO_SCROLL_UP_TITLEBAR_KEY
#define MARCO_SCROLL_UP_TITLEBAR_KEY "action-scroll-up-titlebar"
Definition at line 55 of file mate-window-properties.c.
MARCO_SHOW_TAB_BORDER_KEY
#define MARCO_SHOW_TAB_BORDER_KEY "show-tab-border"
Definition at line 50 of file mate-window-properties.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MARCO_BUTTON_LAYOUT_RIGHT_WITH_MENU
MARCO_BUTTON_LAYOUT_LEFT_WITH_MENU
MARCO_BUTTON_LAYOUT_RIGHT
MARCO_BUTTON_LAYOUT_LEFT
MARCO_BUTTON_LAYOUT_COUNT
Definition at line 65 of file mate-window-properties.c.
anonymous enum
anonymous enum
Enumerator
ACTION_TITLEBAR_CLOSE
ACTION_TITLEBAR_MINIMIZE
ACTION_TITLEBAR_TOGGLE_MAXIMIZE
ACTION_TITLEBAR_TOGGLE_MAXIMIZE_HORIZONTALLY
ACTION_TITLEBAR_TOGGLE_MAXIMIZE_VERTICALLY
ACTION_TITLEBAR_TOGGLE_SHADE
ACTION_TITLEBAR_SHADE
ACTION_TITLEBAR_UNSHADE
ACTION_TITLEBAR_RAISE
ACTION_TITLEBAR_LOWER
ACTION_TITLEBAR_TOGGLE_STICK
ACTION_TITLEBAR_TOGGLE_ABOVE
ACTION_TITLEBAR_MENU
ACTION_TITLEBAR_NONE
Definition at line 82 of file mate-window-properties.c.
anonymous enum
anonymous enum
Enumerator
FOCUS_MODE_CLICK
FOCUS_MODE_SLOPPY
FOCUS_MODE_MOUSE
Definition at line 100 of file mate-window-properties.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 394 of file mate-window-properties.c.
References capplet_init(), capplet_notebook_scroll_event_cb(), GET_WIDGET, INTERFACE_SCHEMA, MARCO_ALLOW_TILING_KEY, MARCO_ALLOW_TOP_TILING_KEY, MARCO_AUTORAISE_KEY, MARCO_CENTER_NEW_WINDOWS_KEY, MARCO_COMPOSITING_FAST_ALT_TAB_KEY, MARCO_COMPOSITING_MANAGER_KEY, MARCO_DOUBLE_CLICK_TITLEBAR_KEY, MARCO_FOCUS_KEY, MARCO_MIDDLE_CLICK_TITLEBAR_KEY, MARCO_RIGHT_CLICK_TITLEBAR_KEY, MARCO_SCHEMA, MARCO_SCROLL_DOWN_TITLEBAR_KEY, MARCO_SCROLL_UP_TITLEBAR_KEY, MARCO_SHOW_TAB_BORDER_KEY, mate_metacity_config_tool(), NULL, WM_COMMON_MARCO, and WM_COMMON_METACITY.