MATE Desktop Environment: mate-druid-page-edge.h File Reference
mate-druid-page-edge.h File Reference
#include <gtk/gtk.h>
#include <libmatecanvas/mate-canvas.h>
#include "mate-druid-page.h"
Classes
struct _MateDruidPageEdge
struct _MateDruidPageEdgeClass
Macros
#define MATE_TYPE_DRUID_PAGE_EDGE (mate_druid_page_edge_get_type ())
#define MATE_DRUID_PAGE_EDGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_DRUID_PAGE_EDGE, MateDruidPageEdge))
#define MATE_DRUID_PAGE_EDGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_DRUID_PAGE_EDGE, MateDruidPageEdgeClass))
#define MATE_IS_DRUID_PAGE_EDGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_DRUID_PAGE_EDGE))
#define MATE_IS_DRUID_PAGE_EDGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_DRUID_PAGE_EDGE))
#define MATE_DRUID_PAGE_EDGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_DRUID_PAGE_EDGE, MateDruidPageEdgeClass))
Typedefs
typedef struct _MateDruidPageEdge MateDruidPageEdge
typedef struct _MateDruidPageEdgePrivate MateDruidPageEdgePrivate
typedef struct _MateDruidPageEdgeClass MateDruidPageEdgeClass
Enumerations
enum MateEdgePosition { MATE_EDGE_START , MATE_EDGE_FINISH , MATE_EDGE_OTHER , MATE_EDGE_LAST }
Functions
GType mate_druid_page_edge_get_type (void)
GtkWidget * mate_druid_page_edge_new (MateEdgePosition position)
GtkWidget * mate_druid_page_edge_new_aa (MateEdgePosition position)
GtkWidget * mate_druid_page_edge_new_with_vals (MateEdgePosition position, gboolean antialiased, const gchar *title, const gchar *text, GdkPixbuf *logo, GdkPixbuf *watermark, GdkPixbuf *top_watermark)
void mate_druid_page_edge_construct (MateDruidPageEdge *druid_page_edge, MateEdgePosition position, gboolean antialiased, const gchar *title, const gchar *text, GdkPixbuf *logo, GdkPixbuf *watermark, GdkPixbuf *top_watermark)
void mate_druid_page_edge_set_bg_color (MateDruidPageEdge *druid_page_edge, GdkColor *color)
void mate_druid_page_edge_set_textbox_color (MateDruidPageEdge *druid_page_edge, GdkColor *color)
void mate_druid_page_edge_set_logo_bg_color (MateDruidPageEdge *druid_page_edge, GdkColor *color)
void mate_druid_page_edge_set_title_color (MateDruidPageEdge *druid_page_edge, GdkColor *color)
void mate_druid_page_edge_set_text_color (MateDruidPageEdge *druid_page_edge, GdkColor *color)
void mate_druid_page_edge_set_text (MateDruidPageEdge *druid_page_edge, const gchar *text)
void mate_druid_page_edge_set_title (MateDruidPageEdge *druid_page_edge, const gchar *title)
void mate_druid_page_edge_set_logo (MateDruidPageEdge *druid_page_edge, GdkPixbuf *logo_image)
void mate_druid_page_edge_set_watermark (MateDruidPageEdge *druid_page_edge, GdkPixbuf *watermark)
void mate_druid_page_edge_set_top_watermark (MateDruidPageEdge *druid_page_edge, GdkPixbuf *top_watermark_image)
Macro Definition Documentation
MATE_DRUID_PAGE_EDGE
#define MATE_DRUID_PAGE_EDGE (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_DRUID_PAGE_EDGE, MateDruidPageEdge))
Definition at line 38 of file mate-druid-page-edge.h.
MATE_DRUID_PAGE_EDGE_CLASS
#define MATE_DRUID_PAGE_EDGE_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_DRUID_PAGE_EDGE, MateDruidPageEdgeClass))
Definition at line 39 of file mate-druid-page-edge.h.
MATE_DRUID_PAGE_EDGE_GET_CLASS
#define MATE_DRUID_PAGE_EDGE_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_DRUID_PAGE_EDGE, MateDruidPageEdgeClass))
Definition at line 42 of file mate-druid-page-edge.h.
MATE_IS_DRUID_PAGE_EDGE
#define MATE_IS_DRUID_PAGE_EDGE (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_DRUID_PAGE_EDGE))
Definition at line 40 of file mate-druid-page-edge.h.
MATE_IS_DRUID_PAGE_EDGE_CLASS
#define MATE_IS_DRUID_PAGE_EDGE_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_DRUID_PAGE_EDGE))
Definition at line 41 of file mate-druid-page-edge.h.
MATE_TYPE_DRUID_PAGE_EDGE
#define MATE_TYPE_DRUID_PAGE_EDGE (mate_druid_page_edge_get_type ())
Definition at line 37 of file mate-druid-page-edge.h.
Typedef Documentation
MateDruidPageEdge
typedef struct _MateDruidPageEdge MateDruidPageEdge
Definition at line 67 of file mate-druid-page-edge.h.
MateDruidPageEdgeClass
typedef struct _MateDruidPageEdgeClass MateDruidPageEdgeClass
Definition at line 69 of file mate-druid-page-edge.h.
MateDruidPageEdgePrivate
typedef struct _MateDruidPageEdgePrivate MateDruidPageEdgePrivate
Definition at line 68 of file mate-druid-page-edge.h.
Enumeration Type Documentation
MateEdgePosition
enum MateEdgePosition
MateEdgePosition: @MATE_EDGE_START: The current page is at the beginning of the druid. @MATE_EDGE_FINISH: The current page is at the end of the druid. @MATE_EDGE_OTHER: The current page is neither the first nor the last page (usually not required). @MATE_EDGE_LAST: Used internally to indicate the last value of the enumeration. This should not be passed in to any function expecting a MateEdgePosition value.
Used to pass around information about the position of a MateDruidPage within the overall MateDruid. This enables the correct "surrounding" content for the page to be drawn.
Enumerator
MATE_EDGE_START
MATE_EDGE_FINISH
MATE_EDGE_OTHER
MATE_EDGE_LAST
Definition at line 58 of file mate-druid-page-edge.h.
Function Documentation
mate_druid_page_edge_construct()
void mate_druid_page_edge_construct (MateDruidPageEdge * druid_page_edge, MateEdgePosition position, gboolean antialiased, const gchar * title, const gchar * text, GdkPixbuf * logo, GdkPixbuf * watermark, GdkPixbuf * top_watermark)
mate_druid_page_edge_construct: @druid_page_edge: A MateDruidPageEdge instance. @position: The position of @druid_page_edge within the druid. @antialiased: Unused in the current implementation. Set to FALSE. @title: The title of the page. @text: The text in the body of the page. @logo: The logo on the page. @watermark: The watermark on the side of the page. @top_watermark: The watermark on the top of the page.
Description: Useful for subclassing and language bindings, this function fills the given pieces of information into the existing @druid_page_edge.
Definition at line 204 of file mate-druid-page-edge.c.
References mate_druid_page_edge_set_logo(), mate_druid_page_edge_set_text(), mate_druid_page_edge_set_title(), mate_druid_page_edge_set_top_watermark(), mate_druid_page_edge_set_watermark(), MATE_EDGE_LAST, MATE_EDGE_START, MATE_IS_DRUID_PAGE_EDGE, and _MateDruidPageEdge::position.
Referenced by mate_druid_page_edge_new(), mate_druid_page_edge_new_aa(), and mate_druid_page_edge_new_with_vals().
mate_druid_page_edge_get_type()
GType mate_druid_page_edge_get_type (void)
mate_druid_page_edge_new()
GtkWidget * mate_druid_page_edge_new (MateEdgePosition position)
mate_druid_page_edge_new: @position: Position in druid.
Description: Creates a new MateDruidPageEdge widget.
Returns: #GtkWidget pointer to a new MateDruidPageEdge.
Definition at line 332 of file mate-druid-page-edge.c.
References FALSE, mate_druid_page_edge_construct(), MATE_EDGE_LAST, MATE_EDGE_START, MATE_TYPE_DRUID_PAGE_EDGE, and NULL.
mate_druid_page_edge_new_aa()
GtkWidget * mate_druid_page_edge_new_aa (MateEdgePosition position)
mate_druid_page_edge_new_aa: @position: Position in druid.
Description: Creates a new MateDruidPageEdge widget. The internal canvas is created in an antialiased mode.
Returns: #GtkWidget pointer to a new MateDruidPageEdge.
Definition at line 364 of file mate-druid-page-edge.c.
References mate_druid_page_edge_construct(), MATE_EDGE_LAST, MATE_EDGE_START, MATE_TYPE_DRUID_PAGE_EDGE, NULL, and TRUE.
mate_druid_page_edge_new_with_vals()
GtkWidget * mate_druid_page_edge_new_with_vals (MateEdgePosition position, gboolean antialiased, const gchar * title, const gchar * text, GdkPixbuf * logo, GdkPixbuf * watermark, GdkPixbuf * top_watermark)
mate_druid_page_edge_new_with_vals: @position: Position in druid. @antialiased: Use an antialiased canvas @title: The title. @text: The introduction text. @logo: The logo in the upper right corner. @watermark: The watermark on the left. @top_watermark: The watermark on the left.
This will create a new MATE Druid Edge page, with the values given. It is acceptable for any of them to be NULL. Position should be MATE_EDGE_START, MATE_EDGE_FINISH or MATE_EDGE_OTHER.
Returns: #GtkWidget pointer to a new MateDruidPageEdge.
Definition at line 402 of file mate-druid-page-edge.c.
References mate_druid_page_edge_construct(), MATE_EDGE_LAST, MATE_EDGE_START, MATE_TYPE_DRUID_PAGE_EDGE, and NULL.
mate_druid_page_edge_set_bg_color()
void mate_druid_page_edge_set_bg_color (MateDruidPageEdge * druid_page_edge, GdkColor * color)
mate_druid_page_edge_set_bg_color: @druid_page_edge: A @MateDruidPageEdge instance. @color: The new background color.
Description: This will set the background color to be the @color. You do not need to allocate the color, as the @druid_page_edge will do it for you.
Definition at line 437 of file mate-druid-page-edge.c.
References _MateDruidPageEdge::_priv, _MateDruidPageEdge::background_color, MATE_IS_DRUID_PAGE_EDGE, NULL, and TRUE.
mate_druid_page_edge_set_logo()
void mate_druid_page_edge_set_logo (MateDruidPageEdge * druid_page_edge, GdkPixbuf * logo_image)
mate_druid_page_edge_set_logo: @druid_page_edge: A @MateDruidPageEdge instance. @logo_image: The #GdkPixbuf to use as a logo.
Description: Sets a #GdkPixbuf as the logo in the top right corner. If NULL, then no logo will be displayed.
Definition at line 577 of file mate-druid-page-edge.c.
References _MateDruidPageEdge::_priv, _MateDruidPageEdge::logo_image, MATE_IS_DRUID_PAGE_EDGE, and NULL.
Referenced by mate_druid_page_edge_construct().
mate_druid_page_edge_set_logo_bg_color()
void mate_druid_page_edge_set_logo_bg_color (MateDruidPageEdge * druid_page_edge, GdkColor * color)
mate_druid_page_edge_set_logo_bg_color @druid_page_edge: A @MateDruidPageEdge instance. @color: The new color of the logo's background.
Set the color behind the druid page's logo.
Definition at line 477 of file mate-druid-page-edge.c.
References _MateDruidPageEdge::_priv, _MateDruidPageEdge::logo_background_color, MATE_IS_DRUID_PAGE_EDGE, NULL, and TRUE.
mate_druid_page_edge_set_text()
void mate_druid_page_edge_set_text (MateDruidPageEdge * druid_page_edge, const gchar * text)
mate_druid_page_edge_set_text @druid_page_edge: A @MateDruidPageEdge instance. @text: The text contents.
Sets the contents of the text portion of the druid page.
Definition at line 537 of file mate-druid-page-edge.c.
References _MateDruidPageEdge::_priv, MATE_IS_DRUID_PAGE_EDGE, and _MateDruidPageEdge::text.
Referenced by mate_druid_page_edge_construct().
mate_druid_page_edge_set_text_color()
void mate_druid_page_edge_set_text_color (MateDruidPageEdge * druid_page_edge, GdkColor * color)
mate_druid_page_edge_set_text_color @druid_page_edge: A @MateDruidPageEdge instance. @color: The new test color.
Sets the color of the text in the body of the druid page.
Definition at line 517 of file mate-druid-page-edge.c.
References _MateDruidPageEdge::_priv, MATE_IS_DRUID_PAGE_EDGE, NULL, _MateDruidPageEdge::text_color, and TRUE.
mate_druid_page_edge_set_textbox_color()
void mate_druid_page_edge_set_textbox_color (MateDruidPageEdge * druid_page_edge, GdkColor * color)
mate_druid_page_edge_set_textbox_color @druid_page_edge: A @MateDruidPageEdge instance. @color: The new textbox color.
Sets the color of the background in the main text area of the page.
Definition at line 457 of file mate-druid-page-edge.c.
References _MateDruidPageEdge::_priv, MATE_IS_DRUID_PAGE_EDGE, NULL, _MateDruidPageEdge::textbox_color, and TRUE.
mate_druid_page_edge_set_title()
void mate_druid_page_edge_set_title (MateDruidPageEdge * druid_page_edge, const gchar * title)
mate_druid_page_edge_set_title @druid_page_edge: A @MateDruidPageEdge instance. @title: The title text
Sets the contents of the page's title text.
Definition at line 555 of file mate-druid-page-edge.c.
References _MateDruidPageEdge::_priv, MATE_IS_DRUID_PAGE_EDGE, NULL, _MateDruidPageEdge::title, and TRUE.
Referenced by mate_druid_page_edge_construct().
mate_druid_page_edge_set_title_color()
void mate_druid_page_edge_set_title_color (MateDruidPageEdge * druid_page_edge, GdkColor * color)
mate_druid_page_edge_set_title_color @druid_page_edge: A @MateDruidPageEdge instance. @color: The color of the title text.
Sets the color of the title text on the current page.
Definition at line 497 of file mate-druid-page-edge.c.
References _MateDruidPageEdge::_priv, MATE_IS_DRUID_PAGE_EDGE, NULL, and _MateDruidPageEdge::title_color.
mate_druid_page_edge_set_top_watermark()
void mate_druid_page_edge_set_top_watermark (MateDruidPageEdge * druid_page_edge, GdkPixbuf * top_watermark_image)
mate_druid_page_edge_set_top_watermark: @druid_page_edge: the MateDruidPageEdge to work on @top_watermark_image: The #GdkPixbuf to use as a top watermark
Description: Sets a #GdkPixbuf as the watermark on top of the top strip on the druid. If @top_watermark_image is NULL, it is reset to the normal color.
Definition at line 631 of file mate-druid-page-edge.c.
References _MateDruidPageEdge::_priv, MATE_IS_DRUID_PAGE_EDGE, NULL, and _MateDruidPageEdge::top_watermark_image.
Referenced by mate_druid_page_edge_construct().
mate_druid_page_edge_set_watermark()
void mate_druid_page_edge_set_watermark (MateDruidPageEdge * druid_page_edge, GdkPixbuf * watermark)
mate_druid_page_edge_set_watermark: @druid_page_edge: A @MateDruidPageEdge instance. @watermark: The #GdkPixbuf to use as a watermark.
Description: Sets a #GdkPixbuf as the watermark on the left strip on the druid. If @watermark is NULL, it is reset to the normal color.
Definition at line 600 of file mate-druid-page-edge.c.
References _MateDruidPageEdge::_priv, DRUID_PAGE_LEFT_WIDTH, MATE_IS_DRUID_PAGE_EDGE, NULL, and _MateDruidPageEdge::watermark_image.
Referenced by mate_druid_page_edge_construct().