MATE Desktop Environment: mate-bg.c File Reference
mate-bg.c File Reference
#include <string.h>
#include <math.h>
#include <stdarg.h>
#include <stdlib.h>
#include <glib/gstdio.h>
#include <gio/gio.h>
#include <gdk/gdkx.h>
#include <X11/Xlib.h>
#include <X11/Xatom.h>
#include <cairo.h>
#include <mate-bg.h>
#include <mate-bg-crossfade.h>
#include <cairo-xlib.h>
Macros
#define MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_BG_CACHE_DIR "mate/background"
#define KEEP_EXPENSIVE_CACHE_SECS 60
#define THUMBNAIL_SIZE 256
#define CACHE_SIZE 4
Typedefs
typedef struct _SlideShow SlideShow
typedef struct _Slide Slide
typedef struct _FileSize FileSize
typedef struct FileCacheEntry FileCacheEntry
Enumerations
enum { CHANGED , TRANSITIONED , N_SIGNALS }
enum FileType { PIXBUF , SLIDESHOW , THUMBNAIL }
Functions
void mate_bg_load_from_preferences (MateBG *bg)
void mate_bg_load_from_system_preferences (MateBG *bg)
void mate_bg_load_from_system_gsettings (MateBG *bg, GSettings *settings, gboolean reset_apply)
void mate_bg_load_from_gsettings (MateBG *bg, GSettings *settings)
void mate_bg_save_to_preferences (MateBG *bg)
void mate_bg_save_to_gsettings (MateBG *bg, GSettings *settings)
MateBG * mate_bg_new (void)
void mate_bg_set_color (MateBG *bg, MateBGColorType type, GdkRGBA *primary, GdkRGBA *secondary)
void mate_bg_set_placement (MateBG *bg, MateBGPlacement placement)
MateBGPlacement mate_bg_get_placement (MateBG *bg)
void mate_bg_get_color (MateBG *bg, MateBGColorType *type, GdkRGBA *primary, GdkRGBA *secondary)
void mate_bg_set_draw_background (MateBG *bg, gboolean draw_background)
gboolean mate_bg_get_draw_background (MateBG *bg)
const gchar * mate_bg_get_filename (MateBG *bg)
void mate_bg_set_filename (MateBG *bg, const char *filename)
void mate_bg_draw (MateBG *bg, GdkPixbuf *dest, GdkScreen *screen, gboolean is_root)
gboolean mate_bg_has_multiple_sizes (MateBG *bg)
cairo_surface_t * mate_bg_create_surface (MateBG *bg, GdkWindow *window, int width, int height, gboolean root)
cairo_surface_t * mate_bg_create_surface_scale (MateBG *bg, GdkWindow *window, int width, int height, int scale, gboolean root)
gboolean mate_bg_is_dark (MateBG *bg, int width, int height)
gboolean mate_bg_get_image_size (MateBG *bg, MateDesktopThumbnailFactory *factory, int best_width, int best_height, int *width, int *height)
GdkPixbuf * mate_bg_create_thumbnail (MateBG *bg, MateDesktopThumbnailFactory *factory, GdkScreen *screen, int dest_width, int dest_height)
cairo_surface_t * mate_bg_get_surface_from_root (GdkScreen *screen)
void mate_bg_set_surface_as_root (GdkScreen *screen, cairo_surface_t *surface)
MateBGCrossfade * mate_bg_set_surface_as_root_with_crossfade (GdkScreen *screen, cairo_surface_t *surface)
gboolean mate_bg_changes_with_time (MateBG *bg)
GdkPixbuf * mate_bg_create_frame_thumbnail (MateBG *bg, MateDesktopThumbnailFactory *factory, GdkScreen *screen, int dest_width, int dest_height, int frame_num)
Macro Definition Documentation
CACHE_SIZE
#define CACHE_SIZE 4
Definition at line 81 of file mate-bg.c.
KEEP_EXPENSIVE_CACHE_SECS
#define KEEP_EXPENSIVE_CACHE_SECS 60
Definition at line 57 of file mate-bg.c.
MATE_BG_CACHE_DIR
#define MATE_BG_CACHE_DIR "mate/background"
Definition at line 53 of file mate-bg.c.
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 47 of file mate-bg.c.
THUMBNAIL_SIZE
#define THUMBNAIL_SIZE 256
Definition at line 78 of file mate-bg.c.
Typedef Documentation
FileCacheEntry
typedef struct FileCacheEntry FileCacheEntry
Definition at line 80 of file mate-bg.c.
FileSize
typedef struct _FileSize FileSize
Definition at line 70 of file mate-bg.c.
Slide
typedef struct _Slide Slide
Definition at line 60 of file mate-bg.c.
SlideShow
typedef struct _SlideShow SlideShow
Definition at line 59 of file mate-bg.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CHANGED
TRANSITIONED
N_SIGNALS
Definition at line 114 of file mate-bg.c.
FileType
enum FileType
Enumerator
PIXBUF
SLIDESHOW
THUMBNAIL
Definition at line 1781 of file mate-bg.c.
Function Documentation
mate_bg_changes_with_time()
gboolean mate_bg_changes_with_time (MateBG * bg)
Definition at line 3189 of file mate-bg.c.
References FALSE, NULL, and TRUE.
Referenced by mate_wp_item_get_frame_thumbnail(), and mate_wp_item_update_description().
mate_bg_create_frame_thumbnail()
GdkPixbuf * mate_bg_create_frame_thumbnail (MateBG * bg, MateDesktopThumbnailFactory * factory, GdkScreen * screen, int dest_width, int dest_height, int frame_num)
mate_bg_create_frame_thumbnail:
Creates a thumbnail for a certain frame, where 'frame' is somewhat vaguely defined as 'suitable point to show while single-stepping through the slideshow'.
Returns: (transfer full): the newly created thumbnail or or NULL if frame_num is out of bounds.
Definition at line 3220 of file mate-bg.c.
References FALSE, NULL, and TRUE.
Referenced by mate_wp_item_get_frame_thumbnail().
mate_bg_create_surface()
cairo_surface_t * mate_bg_create_surface (MateBG * bg, GdkWindow * window, int width, int height, gboolean root)
mate_bg_create_surface: @bg: MateBG @window: @width: @height: @root:
Create a surface that can be set as background for @window. If @root is TRUE, the surface created will be created by a temporary X server connection so that if someone calls XKillClient on it, it won't affect the application who created it.
Definition at line 1126 of file mate-bg.c.
References mate_bg_create_surface_scale().
mate_bg_create_surface_scale()
cairo_surface_t * mate_bg_create_surface_scale (MateBG * bg, GdkWindow * window, int width, int height, int scale, gboolean root)
mate_bg_create_surface_scale: @bg: MateBG @window: @width: @height: @scale: @root:
Create a scaled surface that can be set as background for @window. If @root is TRUE, the surface created will be created by a temporary X server connection so that if someone calls XKillClient on it, it won't affect the application who created it.
Definition at line 1155 of file mate-bg.c.
References FALSE, GDK_IS_X11_DISPLAY, MATE_BG_COLOR_SOLID, mate_bg_draw(), and NULL.
Referenced by mate_bg_create_surface().
mate_bg_create_thumbnail()
GdkPixbuf * mate_bg_create_thumbnail (MateBG * bg, MateDesktopThumbnailFactory * factory, GdkScreen * screen, int dest_width, int dest_height)
mate_bg_create_thumbnail:
Returns: (transfer full): a #GdkPixbuf showing the background as a thumbnail
Definition at line 1385 of file mate-bg.c.
References FALSE, and NULL.
Referenced by mate_wp_item_get_frame_thumbnail().
mate_bg_draw()
void mate_bg_draw (MateBG * bg, GdkPixbuf * dest, GdkScreen * screen, gboolean is_root)
Definition at line 1039 of file mate-bg.c.
References dest, and MATE_BG_PLACEMENT_SPANNED.
Referenced by mate_bg_create_surface_scale().
mate_bg_get_color()
void mate_bg_get_color (MateBG * bg, MateBGColorType * type, GdkRGBA * primary, GdkRGBA * secondary)
Definition at line 561 of file mate-bg.c.
References NULL, and type.
Referenced by eel_bg_get_desktop_color().
mate_bg_get_draw_background()
gboolean mate_bg_get_draw_background (MateBG * bg)
Definition at line 592 of file mate-bg.c.
References FALSE, and NULL.
mate_bg_get_filename()
const gchar * mate_bg_get_filename (MateBG * bg)
Definition at line 600 of file mate-bg.c.
References NULL.
Referenced by eel_background_get_image_uri(), and eel_background_is_set().
mate_bg_get_image_size()
gboolean mate_bg_get_image_size (MateBG * bg, MateDesktopThumbnailFactory * factory, int best_width, int best_height, int * width, int * height)
Definition at line 1338 of file mate-bg.c.
References FALSE, NULL, and TRUE.
Referenced by mate_wp_item_get_frame_thumbnail().
mate_bg_get_placement()
MateBGPlacement mate_bg_get_placement (MateBG * bg)
Definition at line 553 of file mate-bg.c.
References NULL.
mate_bg_get_surface_from_root()
cairo_surface_t * mate_bg_get_surface_from_root (GdkScreen * screen)
mate_bg_get_surface_from_root: @screen: a #GdkScreen
This function queries the _XROOTPMAP_ID property from the root window associated with @screen to determine the current root window background surface and returns a copy of it. If the _XROOTPMAP_ID is not set, then a black surface is returned.
Return value: a #cairo_surface_t if successful or NULL
Definition at line 1425 of file mate-bg.c.
References data, NULL, and type.
Referenced by mate_bg_set_surface_as_root_with_crossfade().
mate_bg_has_multiple_sizes()
gboolean mate_bg_has_multiple_sizes (MateBG * bg)
Definition at line 1061 of file mate-bg.c.
References FALSE, and NULL.
Referenced by mate_wp_item_update_description().
mate_bg_is_dark()
gboolean mate_bg_is_dark (MateBG * bg, int width, int height)
Definition at line 1221 of file mate-bg.c.
References b, FALSE, MATE_BG_COLOR_SOLID, and NULL.
Referenced by eel_background_is_dark().
mate_bg_load_from_gsettings()
void mate_bg_load_from_gsettings (MateBG * bg, GSettings * settings)
Definition at line 328 of file mate-bg.c.
References MATE_BG_KEY_COLOR_TYPE, MATE_BG_KEY_DRAW_BACKGROUND, MATE_BG_KEY_PICTURE_FILENAME, MATE_BG_KEY_PICTURE_PLACEMENT, MATE_BG_KEY_PRIMARY_COLOR, MATE_BG_KEY_SECONDARY_COLOR, mate_bg_set_color(), mate_bg_set_filename(), mate_bg_set_placement(), MATE_IS_BG, and NULL.
Referenced by eel_bg_load_from_gsettings(), mate_bg_load_from_preferences(), and mate_bg_load_from_system_gsettings().
mate_bg_load_from_preferences()
void mate_bg_load_from_preferences (MateBG * bg)
Definition at line 265 of file mate-bg.c.
References mate_bg_load_from_gsettings(), and MATE_BG_SCHEMA.
mate_bg_load_from_system_gsettings()
void mate_bg_load_from_system_gsettings (MateBG * bg, GSettings * settings, gboolean reset_apply)
Definition at line 296 of file mate-bg.c.
References mate_bg_load_from_gsettings(), MATE_IS_BG, and NULL.
Referenced by eel_bg_load_from_system_gsettings(), and mate_bg_load_from_system_preferences().
mate_bg_load_from_system_preferences()
void mate_bg_load_from_system_preferences (MateBG * bg)
Definition at line 279 of file mate-bg.c.
References FALSE, mate_bg_load_from_system_gsettings(), and MATE_BG_SCHEMA.
mate_bg_new()
MateBG * mate_bg_new (void)
Definition at line 512 of file mate-bg.c.
References MATE_TYPE_BG, and NULL.
Referenced by mate_wp_item_ensure_mate_bg().
mate_bg_save_to_gsettings()
void mate_bg_save_to_gsettings (MateBG * bg, GSettings * settings)
Definition at line 412 of file mate-bg.c.
References MATE_BG_KEY_COLOR_TYPE, MATE_BG_KEY_DRAW_BACKGROUND, MATE_BG_KEY_PICTURE_FILENAME, MATE_BG_KEY_PICTURE_PLACEMENT, MATE_BG_KEY_PRIMARY_COLOR, MATE_BG_KEY_SECONDARY_COLOR, and MATE_IS_BG.
Referenced by eel_bg_save_to_gsettings(), and mate_bg_save_to_preferences().
mate_bg_save_to_preferences()
void mate_bg_save_to_preferences (MateBG * bg)
Definition at line 402 of file mate-bg.c.
References mate_bg_save_to_gsettings(), and MATE_BG_SCHEMA.
mate_bg_set_color()
void mate_bg_set_color (MateBG * bg, MateBGColorType type, GdkRGBA * primary, GdkRGBA * secondary)
Definition at line 518 of file mate-bg.c.
References NULL, and type.
Referenced by mate_bg_load_from_gsettings().
mate_bg_set_draw_background()
void mate_bg_set_draw_background (MateBG * bg, gboolean draw_background)
Definition at line 579 of file mate-bg.c.
References NULL.
mate_bg_set_filename()
void mate_bg_set_filename (MateBG * bg, const char * filename)
Definition at line 750 of file mate-bg.c.
References get_mtime(), and NULL.
Referenced by mate_bg_load_from_gsettings().
mate_bg_set_placement()
void mate_bg_set_placement (MateBG * bg, MateBGPlacement placement)
Definition at line 540 of file mate-bg.c.
References NULL.
Referenced by eel_background_set_dropped_image(), eel_bg_set_placement(), and mate_bg_load_from_gsettings().
mate_bg_set_surface_as_root()
void mate_bg_set_surface_as_root (GdkScreen * screen, cairo_surface_t * surface)
mate_bg_set_surface_as_root: @screen: the #GdkScreen to change root background on @surface: the #cairo_surface_t to set root background from. Must be an xlib surface backing a pixmap.
Set the root pixmap, and properties pointing to it. We do this atomically with a server grab to make sure that we won't leak the pixmap if somebody else it setting it at the same time. (This assumes that they follow the same conventions we do). @surface should come from a call to mate_bg_create_surface().
Definition at line 1607 of file mate-bg.c.
References NULL.
Referenced by mate_bg_set_surface_as_root_with_crossfade().
mate_bg_set_surface_as_root_with_crossfade()
MateBGCrossfade * mate_bg_set_surface_as_root_with_crossfade (GdkScreen * screen, cairo_surface_t * surface)
mate_bg_set_surface_as_root_with_crossfade: @screen: the #GdkScreen to change root background on @surface: the cairo xlib surface to set root background from
Set the root pixmap, and properties pointing to it. This function differs from mate_bg_set_surface_as_root() in that it adds a subtle crossfade animation from the current root pixmap to the new one.
Return value: (transfer full): a MateBGCrossfade object
Definition at line 1642 of file mate-bg.c.
References mate_bg_crossfade_new(), mate_bg_crossfade_set_end_surface(), mate_bg_crossfade_set_start_surface(), mate_bg_crossfade_start(), mate_bg_get_surface_from_root(), mate_bg_set_surface_as_root(), and NULL.