MATE Desktop Environment: mate-app-helper.h File Reference
mate-app-helper.h File Reference
#include <gtk/gtk.h>
#include <libmateui/mate-appbar.h>
#include <libmateui/mate-app.h>
Classes
struct MateUIInfo
struct _MateUIBuilderData
Macros
#define MATE_APP_CONFIGURABLE_ITEM_EXIT MATE_APP_CONFIGURABLE_ITEM_QUIT
#define MATEUIINFO_KEY_UIDATA "uidata"
#define MATEUIINFO_KEY_UIBDATA "uibdata"
#define MATEUIINFO_END
#define MATEUIINFO_SEPARATOR
#define MATEUIINFO_ITEM(label, tooltip, callback, xpm_data)
#define MATEUIINFO_ITEM_STOCK(label, tooltip, callback, stock_id)
#define MATEUIINFO_ITEM_NONE(label, tooltip, callback)
#define MATEUIINFO_ITEM_DATA(label, tooltip, callback, user_data, xpm_data)
#define MATEUIINFO_TOGGLEITEM(label, tooltip, callback, xpm_data)
#define MATEUIINFO_TOGGLEITEM_DATA(label, tooltip, callback, user_data, xpm_data)
#define MATEUIINFO_HELP(app_name)
#define MATEUIINFO_SUBTREE(label, tree)
#define MATEUIINFO_SUBTREE_HINT(label, hint, tree)
#define MATEUIINFO_SUBTREE_STOCK(label, tree, stock_id)
#define MATEUIINFO_INCLUDE(tree)
#define MATEUIINFO_RADIOLIST(list)
#define MATEUIINFO_RADIOITEM(label, tooltip, callback, xpm_data)
#define MATEUIINFO_RADIOITEM_DATA(label, tooltip, callback, user_data, xpm_data)
#define MATEUIINFO_MENU_NEW_ITEM(label, tip, cb, data)
#define MATEUIINFO_MENU_NEW_SUBTREE(tree)
#define MATEUIINFO_MENU_OPEN_ITEM(cb, data)
#define MATEUIINFO_MENU_SAVE_ITEM(cb, data)
#define MATEUIINFO_MENU_SAVE_AS_ITEM(cb, data)
#define MATEUIINFO_MENU_REVERT_ITEM(cb, data)
#define MATEUIINFO_MENU_PRINT_ITEM(cb, data)
#define MATEUIINFO_MENU_PRINT_SETUP_ITEM(cb, data)
#define MATEUIINFO_MENU_CLOSE_ITEM(cb, data)
#define MATEUIINFO_MENU_EXIT_ITEM(cb, data) MATEUIINFO_MENU_QUIT_ITEM(cb, data)
#define MATEUIINFO_MENU_QUIT_ITEM(cb, data)
#define MATEUIINFO_MENU_QUIT_ITEM(cb, data)
#define MATEUIINFO_MENU_CUT_ITEM(cb, data)
#define MATEUIINFO_MENU_COPY_ITEM(cb, data)
#define MATEUIINFO_MENU_PASTE_ITEM(cb, data)
#define MATEUIINFO_MENU_SELECT_ALL_ITEM(cb, data)
#define MATEUIINFO_MENU_CLEAR_ITEM(cb, data)
#define MATEUIINFO_MENU_UNDO_ITEM(cb, data)
#define MATEUIINFO_MENU_REDO_ITEM(cb, data)
#define MATEUIINFO_MENU_FIND_ITEM(cb, data)
#define MATEUIINFO_MENU_FIND_AGAIN_ITEM(cb, data)
#define MATEUIINFO_MENU_REPLACE_ITEM(cb, data)
#define MATEUIINFO_MENU_PROPERTIES_ITEM(cb, data)
#define MATEUIINFO_MENU_PREFERENCES_ITEM(cb, data)
#define MATEUIINFO_MENU_NEW_WINDOW_ITEM(cb, data)
#define MATEUIINFO_MENU_CLOSE_WINDOW_ITEM(cb, data)
#define MATEUIINFO_MENU_ABOUT_ITEM(cb, data)
#define MATEUIINFO_MENU_NEW_GAME_ITEM(cb, data)
#define MATEUIINFO_MENU_PAUSE_GAME_ITEM(cb, data)
#define MATEUIINFO_MENU_RESTART_GAME_ITEM(cb, data)
#define MATEUIINFO_MENU_UNDO_MOVE_ITEM(cb, data)
#define MATEUIINFO_MENU_REDO_MOVE_ITEM(cb, data)
#define MATEUIINFO_MENU_HINT_ITEM(cb, data)
#define MATEUIINFO_MENU_SCORES_ITEM(cb, data)
#define MATEUIINFO_MENU_END_GAME_ITEM(cb, data)
#define D_(x) x
#define L_(x) x
#define MATEUIINFO_MENU_FILE_TREE(tree)
#define MATEUIINFO_MENU_EDIT_TREE(tree)
#define MATEUIINFO_MENU_VIEW_TREE(tree)
#define MATEUIINFO_MENU_SETTINGS_TREE(tree)
#define MATEUIINFO_MENU_FILES_TREE(tree)
#define MATEUIINFO_MENU_WINDOWS_TREE(tree)
#define MATEUIINFO_MENU_HELP_TREE(tree)
#define MATEUIINFO_MENU_GAME_TREE(tree)
#define MATE_MENU_FILE_STRING D_("_File")
#define MATE_MENU_FILE_PATH D_("_File/")
#define MATE_MENU_EDIT_STRING D_("_Edit")
#define MATE_MENU_EDIT_PATH D_("_Edit/")
#define MATE_MENU_VIEW_STRING D_("_View")
#define MATE_MENU_VIEW_PATH D_("_View/")
#define MATE_MENU_SETTINGS_STRING D_("_Settings")
#define MATE_MENU_SETTINGS_PATH D_("_Settings/")
#define MATE_MENU_NEW_STRING D_("_New")
#define MATE_MENU_NEW_PATH D_("_New/")
#define MATE_MENU_FILES_STRING D_("Fi_les")
#define MATE_MENU_FILES_PATH D_("Fi_les/")
#define MATE_MENU_WINDOWS_STRING D_("_Windows")
#define MATE_MENU_WINDOWS_PATH D_("_Windows/")
Typedefs
typedef struct _MateUIBuilderData MateUIBuilderData
typedef void(* MateUISignalConnectFunc) (MateUIInfo *uiinfo, const char *signal_name, MateUIBuilderData *uibdata)
Enumerations
enum MateUIInfoType {
MATE_APP_UI_ENDOFINFO , MATE_APP_UI_ITEM , MATE_APP_UI_TOGGLEITEM , MATE_APP_UI_RADIOITEMS ,
MATE_APP_UI_SUBTREE , MATE_APP_UI_SEPARATOR , MATE_APP_UI_HELP , MATE_APP_UI_BUILDER_DATA ,
MATE_APP_UI_ITEM_CONFIGURABLE , MATE_APP_UI_SUBTREE_STOCK , MATE_APP_UI_INCLUDE
}
enum MateUIInfoConfigurableTypes {
MATE_APP_CONFIGURABLE_ITEM_NEW , MATE_APP_CONFIGURABLE_ITEM_OPEN , MATE_APP_CONFIGURABLE_ITEM_SAVE , MATE_APP_CONFIGURABLE_ITEM_SAVE_AS ,
MATE_APP_CONFIGURABLE_ITEM_REVERT , MATE_APP_CONFIGURABLE_ITEM_PRINT , MATE_APP_CONFIGURABLE_ITEM_PRINT_SETUP , MATE_APP_CONFIGURABLE_ITEM_CLOSE ,
MATE_APP_CONFIGURABLE_ITEM_QUIT , MATE_APP_CONFIGURABLE_ITEM_CUT , MATE_APP_CONFIGURABLE_ITEM_COPY , MATE_APP_CONFIGURABLE_ITEM_PASTE ,
MATE_APP_CONFIGURABLE_ITEM_CLEAR , MATE_APP_CONFIGURABLE_ITEM_UNDO , MATE_APP_CONFIGURABLE_ITEM_REDO , MATE_APP_CONFIGURABLE_ITEM_FIND ,
MATE_APP_CONFIGURABLE_ITEM_FIND_AGAIN , MATE_APP_CONFIGURABLE_ITEM_REPLACE , MATE_APP_CONFIGURABLE_ITEM_PROPERTIES , MATE_APP_CONFIGURABLE_ITEM_PREFERENCES ,
MATE_APP_CONFIGURABLE_ITEM_ABOUT , MATE_APP_CONFIGURABLE_ITEM_SELECT_ALL , MATE_APP_CONFIGURABLE_ITEM_NEW_WINDOW , MATE_APP_CONFIGURABLE_ITEM_CLOSE_WINDOW ,
MATE_APP_CONFIGURABLE_ITEM_NEW_GAME , MATE_APP_CONFIGURABLE_ITEM_PAUSE_GAME , MATE_APP_CONFIGURABLE_ITEM_RESTART_GAME , MATE_APP_CONFIGURABLE_ITEM_UNDO_MOVE ,
MATE_APP_CONFIGURABLE_ITEM_REDO_MOVE , MATE_APP_CONFIGURABLE_ITEM_HINT , MATE_APP_CONFIGURABLE_ITEM_SCORES , MATE_APP_CONFIGURABLE_ITEM_END_GAME
}
enum MateUIPixmapType { MATE_APP_PIXMAP_NONE , MATE_APP_PIXMAP_STOCK , MATE_APP_PIXMAP_DATA , MATE_APP_PIXMAP_FILENAME }
Functions
const gchar * mate_app_helper_gettext (const gchar *string)
void mate_accelerators_sync (void)
void mate_app_fill_menu (GtkMenuShell *menu_shell, MateUIInfo *uiinfo, GtkAccelGroup *accel_group, gboolean uline_accels, gint pos)
void mate_app_fill_menu_with_data (GtkMenuShell *menu_shell, MateUIInfo *uiinfo, GtkAccelGroup *accel_group, gboolean uline_accels, gint pos, gpointer user_data)
void mate_app_fill_menu_custom (GtkMenuShell *menu_shell, MateUIInfo *uiinfo, MateUIBuilderData *uibdata, GtkAccelGroup *accel_group, gboolean uline_accels, gint pos)
void mate_app_ui_configure_configurable (MateUIInfo *uiinfo)
void mate_app_create_menus (MateApp *app, MateUIInfo *uiinfo)
void mate_app_create_menus_interp (MateApp *app, MateUIInfo *uiinfo, GtkCallbackMarshal relay_func, gpointer data, GDestroyNotify destroy_func)
void mate_app_create_menus_with_data (MateApp *app, MateUIInfo *uiinfo, gpointer user_data)
void mate_app_create_menus_custom (MateApp *app, MateUIInfo *uiinfo, MateUIBuilderData *uibdata)
void mate_app_fill_toolbar (GtkToolbar *toolbar, MateUIInfo *uiinfo, GtkAccelGroup *accel_group)
void mate_app_fill_toolbar_with_data (GtkToolbar *toolbar, MateUIInfo *uiinfo, GtkAccelGroup *accel_group, gpointer user_data)
void mate_app_fill_toolbar_custom (GtkToolbar *toolbar, MateUIInfo *uiinfo, MateUIBuilderData *uibdata, GtkAccelGroup *accel_group)
void mate_app_create_toolbar (MateApp *app, MateUIInfo *uiinfo)
void mate_app_create_toolbar_interp (MateApp *app, MateUIInfo *uiinfo, GtkCallbackMarshal relay_func, gpointer data, GDestroyNotify destroy_func)
void mate_app_create_toolbar_with_data (MateApp *app, MateUIInfo *uiinfo, gpointer user_data)
void mate_app_create_toolbar_custom (MateApp *app, MateUIInfo *uiinfo, MateUIBuilderData *uibdata)
GtkWidget * mate_app_find_menu_pos (GtkWidget *parent, const gchar *path, gint *pos)
void mate_app_remove_menus (MateApp *app, const gchar *path, gint items)
void mate_app_remove_menu_range (MateApp *app, const gchar *path, gint start, gint items)
void mate_app_insert_menus_custom (MateApp *app, const gchar *path, MateUIInfo *uiinfo, MateUIBuilderData *uibdata)
void mate_app_insert_menus (MateApp *app, const gchar *path, MateUIInfo *menuinfo)
void mate_app_insert_menus_with_data (MateApp *app, const gchar *path, MateUIInfo *menuinfo, gpointer data)
void mate_app_insert_menus_interp (MateApp *app, const gchar *path, MateUIInfo *menuinfo, GtkCallbackMarshal relay_func, gpointer data, GDestroyNotify destroy_func)
void mate_app_install_appbar_menu_hints (MateAppBar *appbar, MateUIInfo *uiinfo)
void mate_app_install_statusbar_menu_hints (GtkStatusbar *bar, MateUIInfo *uiinfo)
void mate_app_install_menu_hints (MateApp *app, MateUIInfo *uiinfo)
void mate_app_setup_toolbar (GtkToolbar *toolbar, MateComponentDockItem *dock_item)
Macro Definition Documentation
D_
#define D_ (x) x
Definition at line 547 of file mate-app-helper.h.
L_
#define L_ (x) x
Definition at line 548 of file mate-app-helper.h.
MATE_APP_CONFIGURABLE_ITEM_EXIT
#define MATE_APP_CONFIGURABLE_ITEM_EXIT MATE_APP_CONFIGURABLE_ITEM_QUIT
Definition at line 184 of file mate-app-helper.h.
MATE_MENU_EDIT_PATH
#define MATE_MENU_EDIT_PATH D_("_Edit/")
Definition at line 581 of file mate-app-helper.h.
MATE_MENU_EDIT_STRING
#define MATE_MENU_EDIT_STRING D_("_Edit")
Definition at line 580 of file mate-app-helper.h.
MATE_MENU_FILE_PATH
#define MATE_MENU_FILE_PATH D_("_File/")
Definition at line 579 of file mate-app-helper.h.
MATE_MENU_FILE_STRING
#define MATE_MENU_FILE_STRING D_("_File")
Definition at line 578 of file mate-app-helper.h.
MATE_MENU_FILES_PATH
#define MATE_MENU_FILES_PATH D_("Fi_les/")
Definition at line 589 of file mate-app-helper.h.
MATE_MENU_FILES_STRING
#define MATE_MENU_FILES_STRING D_("Fi_les")
Definition at line 588 of file mate-app-helper.h.
MATE_MENU_NEW_PATH
#define MATE_MENU_NEW_PATH D_("_New/")
Definition at line 587 of file mate-app-helper.h.
MATE_MENU_NEW_STRING
#define MATE_MENU_NEW_STRING D_("_New")
Definition at line 586 of file mate-app-helper.h.
MATE_MENU_SETTINGS_PATH
#define MATE_MENU_SETTINGS_PATH D_("_Settings/")
Definition at line 585 of file mate-app-helper.h.
MATE_MENU_SETTINGS_STRING
#define MATE_MENU_SETTINGS_STRING D_("_Settings")
Definition at line 584 of file mate-app-helper.h.
MATE_MENU_VIEW_PATH
#define MATE_MENU_VIEW_PATH D_("_View/")
Definition at line 583 of file mate-app-helper.h.
MATE_MENU_VIEW_STRING
#define MATE_MENU_VIEW_STRING D_("_View")
Definition at line 582 of file mate-app-helper.h.
MATE_MENU_WINDOWS_PATH
#define MATE_MENU_WINDOWS_PATH D_("_Windows/")
Definition at line 591 of file mate-app-helper.h.
MATE_MENU_WINDOWS_STRING
#define MATE_MENU_WINDOWS_STRING D_("_Windows")
Definition at line 590 of file mate-app-helper.h.
MATEUIINFO_END
#define MATEUIINFO_END
Value:
                      { MATE_APP_UI_ENDOFINFO, NULL, NULL, NULL, NULL, NULL,        \
                      (MateUIPixmapType) 0, NULL, 0, (GdkModifierType) 0, NULL }
Definition at line 228 of file mate-app-helper.h.
MATEUIINFO_HELP
#define MATEUIINFO_HELP (app_name)
Value:
    { MATE_APP_UI_HELP, NULL, NULL, (void *)app_name, NULL, NULL, \
        (MateUIPixmapType) 0, NULL, 0,  (GdkModifierType) 0, NULL }
Definition at line 267 of file mate-app-helper.h.
MATEUIINFO_INCLUDE
#define MATEUIINFO_INCLUDE (tree)
Value:
    { MATE_APP_UI_INCLUDE, NULL, NULL, tree, NULL, NULL, \
        (MateUIPixmapType) 0, NULL, 0,  (GdkModifierType) 0, NULL }
Definition at line 286 of file mate-app-helper.h.
MATEUIINFO_ITEM
#define MATEUIINFO_ITEM (label, tooltip, callback, xpm_data)
Value:
    { MATE_APP_UI_ITEM, label, tooltip, (gpointer)callback, NULL, NULL, \
        MATE_APP_PIXMAP_DATA, xpm_data, 0, (GdkModifierType) 0, NULL}
Definition at line 236 of file mate-app-helper.h.
MATEUIINFO_ITEM_DATA
#define MATEUIINFO_ITEM_DATA (label, tooltip, callback, user_data, xpm_data)
Value:
    { MATE_APP_UI_ITEM, label, tooltip, (gpointer)callback, user_data, NULL, \
        MATE_APP_PIXMAP_DATA, xpm_data, 0, (GdkModifierType) 0, NULL }
Definition at line 251 of file mate-app-helper.h.
MATEUIINFO_ITEM_NONE
#define MATEUIINFO_ITEM_NONE (label, tooltip, callback)
Value:
    { MATE_APP_UI_ITEM, label, tooltip, (gpointer)callback, NULL, NULL, \
        MATE_APP_PIXMAP_NONE, NULL, 0, (GdkModifierType) 0, NULL }
Definition at line 246 of file mate-app-helper.h.
MATEUIINFO_ITEM_STOCK
#define MATEUIINFO_ITEM_STOCK (label, tooltip, callback, stock_id)
Value:
    { MATE_APP_UI_ITEM, label, tooltip, (gpointer)callback, NULL, NULL, \
        MATE_APP_PIXMAP_STOCK, stock_id, 0, (GdkModifierType) 0, NULL }
Definition at line 241 of file mate-app-helper.h.
MATEUIINFO_KEY_UIBDATA
#define MATEUIINFO_KEY_UIBDATA "uibdata"
Definition at line 223 of file mate-app-helper.h.
MATEUIINFO_KEY_UIDATA
#define MATEUIINFO_KEY_UIDATA "uidata"
Definition at line 222 of file mate-app-helper.h.
MATEUIINFO_MENU_ABOUT_ITEM
#define MATEUIINFO_MENU_ABOUT_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_ABOUT, (GdkModifierType) 0, NULL }
Definition at line 483 of file mate-app-helper.h.
MATEUIINFO_MENU_CLEAR_ITEM
#define MATEUIINFO_MENU_CLEAR_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_CLEAR, (GdkModifierType) 0, NULL }
Definition at line 414 of file mate-app-helper.h.
MATEUIINFO_MENU_CLOSE_ITEM
#define MATEUIINFO_MENU_CLOSE_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_CLOSE, (GdkModifierType) 0, NULL }
Definition at line 368 of file mate-app-helper.h.
MATEUIINFO_MENU_CLOSE_WINDOW_ITEM
#define MATEUIINFO_MENU_CLOSE_WINDOW_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_CLOSE_WINDOW, (GdkModifierType) 0, NULL }
Definition at line 474 of file mate-app-helper.h.
MATEUIINFO_MENU_COPY_ITEM
#define MATEUIINFO_MENU_COPY_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_COPY, (GdkModifierType) 0, NULL }
Definition at line 396 of file mate-app-helper.h.
MATEUIINFO_MENU_CUT_ITEM
#define MATEUIINFO_MENU_CUT_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_CUT, (GdkModifierType) 0, NULL }
Definition at line 390 of file mate-app-helper.h.
MATEUIINFO_MENU_EDIT_TREE
#define MATEUIINFO_MENU_EDIT_TREE (tree)
Value:
    { MATE_APP_UI_SUBTREE_STOCK, N_("_Edit"), NULL, tree, NULL, NULL, \
        (MateUIPixmapType) 0, NULL, 0,  (GdkModifierType) 0, NULL }
Definition at line 555 of file mate-app-helper.h.
MATEUIINFO_MENU_END_GAME_ITEM
#define MATEUIINFO_MENU_END_GAME_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_END_GAME, (GdkModifierType) 0, NULL }
Definition at line 535 of file mate-app-helper.h.
MATEUIINFO_MENU_EXIT_ITEM
#define MATEUIINFO_MENU_EXIT_ITEM (cb, data) MATEUIINFO_MENU_QUIT_ITEM(cb, data)
Definition at line 374 of file mate-app-helper.h.
MATEUIINFO_MENU_FILE_TREE
#define MATEUIINFO_MENU_FILE_TREE (tree)
Value:
    { MATE_APP_UI_SUBTREE_STOCK, N_("_File"), NULL, tree, NULL, NULL, \
        (MateUIPixmapType) 0, NULL, 0,  (GdkModifierType) 0, NULL }
Definition at line 552 of file mate-app-helper.h.
MATEUIINFO_MENU_FILES_TREE
#define MATEUIINFO_MENU_FILES_TREE (tree)
Value:
    { MATE_APP_UI_SUBTREE_STOCK, N_("Fi_les"), NULL, tree, NULL, NULL, \
        (MateUIPixmapType) 0, NULL, 0,  (GdkModifierType) 0, NULL }
Definition at line 564 of file mate-app-helper.h.
MATEUIINFO_MENU_FIND_AGAIN_ITEM
#define MATEUIINFO_MENU_FIND_AGAIN_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_FIND_AGAIN, (GdkModifierType) 0, NULL }
Definition at line 438 of file mate-app-helper.h.
MATEUIINFO_MENU_FIND_ITEM
#define MATEUIINFO_MENU_FIND_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_FIND, (GdkModifierType) 0, NULL }
Definition at line 432 of file mate-app-helper.h.
MATEUIINFO_MENU_GAME_TREE
#define MATEUIINFO_MENU_GAME_TREE (tree)
Value:
    { MATE_APP_UI_SUBTREE_STOCK, N_("_Game"), NULL, tree, NULL, NULL, \
        (MateUIPixmapType) 0, NULL, 0,  (GdkModifierType) 0, NULL }
Definition at line 573 of file mate-app-helper.h.
MATEUIINFO_MENU_HELP_TREE
#define MATEUIINFO_MENU_HELP_TREE (tree)
Value:
    { MATE_APP_UI_SUBTREE_STOCK, N_("_Help"), NULL, tree, NULL, NULL, \
        (MateUIPixmapType) 0, NULL, 0,  (GdkModifierType) 0, NULL }
Definition at line 570 of file mate-app-helper.h.
MATEUIINFO_MENU_HINT_ITEM
#define MATEUIINFO_MENU_HINT_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_HINT, (GdkModifierType) 0, NULL }
Definition at line 523 of file mate-app-helper.h.
MATEUIINFO_MENU_NEW_GAME_ITEM
#define MATEUIINFO_MENU_NEW_GAME_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_NEW_GAME, (GdkModifierType) 0, NULL }
Definition at line 493 of file mate-app-helper.h.
MATEUIINFO_MENU_NEW_ITEM
#define MATEUIINFO_MENU_NEW_ITEM (label, tip, cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, label, tip,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_NEW, (GdkModifierType) 0, NULL }
Definition at line 320 of file mate-app-helper.h.
MATEUIINFO_MENU_NEW_SUBTREE
#define MATEUIINFO_MENU_NEW_SUBTREE (tree)
Value:
        { MATE_APP_UI_SUBTREE_STOCK, N_("_New"), NULL, tree, NULL, NULL,   \
          MATE_APP_PIXMAP_STOCK, MATE_STOCK_MENU_NEW,                     \
          MATE_KEY_NAME_NEW, MATE_KEY_MOD_NEW, NULL }
Definition at line 327 of file mate-app-helper.h.
MATEUIINFO_MENU_NEW_WINDOW_ITEM
#define MATEUIINFO_MENU_NEW_WINDOW_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_NEW_WINDOW, (GdkModifierType) 0, NULL }
Definition at line 468 of file mate-app-helper.h.
MATEUIINFO_MENU_OPEN_ITEM
#define MATEUIINFO_MENU_OPEN_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_OPEN, (GdkModifierType) 0, NULL }
Definition at line 332 of file mate-app-helper.h.
MATEUIINFO_MENU_PASTE_ITEM
#define MATEUIINFO_MENU_PASTE_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_PASTE, (GdkModifierType) 0, NULL }
Definition at line 402 of file mate-app-helper.h.
MATEUIINFO_MENU_PAUSE_GAME_ITEM
#define MATEUIINFO_MENU_PAUSE_GAME_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_PAUSE_GAME, (GdkModifierType) 0, NULL }
Definition at line 499 of file mate-app-helper.h.
MATEUIINFO_MENU_PREFERENCES_ITEM
#define MATEUIINFO_MENU_PREFERENCES_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_PREFERENCES, (GdkModifierType) 0, NULL }
Definition at line 459 of file mate-app-helper.h.
MATEUIINFO_MENU_PRINT_ITEM
#define MATEUIINFO_MENU_PRINT_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_PRINT, (GdkModifierType) 0, NULL }
Definition at line 356 of file mate-app-helper.h.
MATEUIINFO_MENU_PRINT_SETUP_ITEM
#define MATEUIINFO_MENU_PRINT_SETUP_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_PRINT_SETUP, (GdkModifierType) 0, NULL }
Definition at line 362 of file mate-app-helper.h.
MATEUIINFO_MENU_PROPERTIES_ITEM
#define MATEUIINFO_MENU_PROPERTIES_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_PROPERTIES, (GdkModifierType) 0, NULL }
Definition at line 450 of file mate-app-helper.h.
MATEUIINFO_MENU_QUIT_ITEM [1/2]
#define MATEUIINFO_MENU_QUIT_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_QUIT, (GdkModifierType) 0, NULL }
Definition at line 375 of file mate-app-helper.h.
MATEUIINFO_MENU_QUIT_ITEM [2/2]
#define MATEUIINFO_MENU_QUIT_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_QUIT, (GdkModifierType) 0, NULL }
Definition at line 375 of file mate-app-helper.h.
MATEUIINFO_MENU_REDO_ITEM
#define MATEUIINFO_MENU_REDO_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_REDO, (GdkModifierType) 0, NULL }
Definition at line 426 of file mate-app-helper.h.
MATEUIINFO_MENU_REDO_MOVE_ITEM
#define MATEUIINFO_MENU_REDO_MOVE_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_REDO_MOVE, (GdkModifierType) 0, NULL }
Definition at line 517 of file mate-app-helper.h.
MATEUIINFO_MENU_REPLACE_ITEM
#define MATEUIINFO_MENU_REPLACE_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_REPLACE, (GdkModifierType) 0, NULL }
Definition at line 444 of file mate-app-helper.h.
MATEUIINFO_MENU_RESTART_GAME_ITEM
#define MATEUIINFO_MENU_RESTART_GAME_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_RESTART_GAME, (GdkModifierType) 0, NULL }
Definition at line 505 of file mate-app-helper.h.
MATEUIINFO_MENU_REVERT_ITEM
#define MATEUIINFO_MENU_REVERT_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_REVERT, (GdkModifierType) 0, NULL }
Definition at line 350 of file mate-app-helper.h.
MATEUIINFO_MENU_SAVE_AS_ITEM
#define MATEUIINFO_MENU_SAVE_AS_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_SAVE_AS, (GdkModifierType) 0, NULL }
Definition at line 344 of file mate-app-helper.h.
MATEUIINFO_MENU_SAVE_ITEM
#define MATEUIINFO_MENU_SAVE_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_SAVE, (GdkModifierType) 0, NULL }
Definition at line 338 of file mate-app-helper.h.
MATEUIINFO_MENU_SCORES_ITEM
#define MATEUIINFO_MENU_SCORES_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_SCORES, (GdkModifierType) 0, NULL }
Definition at line 529 of file mate-app-helper.h.
MATEUIINFO_MENU_SELECT_ALL_ITEM
#define MATEUIINFO_MENU_SELECT_ALL_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_SELECT_ALL, (GdkModifierType) 0, NULL }
Definition at line 408 of file mate-app-helper.h.
MATEUIINFO_MENU_SETTINGS_TREE
#define MATEUIINFO_MENU_SETTINGS_TREE (tree)
Value:
    { MATE_APP_UI_SUBTREE_STOCK, N_("_Settings"), NULL, tree, NULL, NULL, \
        (MateUIPixmapType) 0, NULL, 0,  (GdkModifierType) 0, NULL }
Definition at line 561 of file mate-app-helper.h.
MATEUIINFO_MENU_UNDO_ITEM
#define MATEUIINFO_MENU_UNDO_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_UNDO, (GdkModifierType) 0, NULL }
Definition at line 420 of file mate-app-helper.h.
MATEUIINFO_MENU_UNDO_MOVE_ITEM
#define MATEUIINFO_MENU_UNDO_MOVE_ITEM (cb, data)
Value:
        { MATE_APP_UI_ITEM_CONFIGURABLE, NULL, NULL,                       \
          (gpointer)cb, (gpointer)(data), NULL,                             \
          MATE_APP_PIXMAP_NONE, NULL,                                      \
          MATE_APP_CONFIGURABLE_ITEM_UNDO_MOVE, (GdkModifierType) 0, NULL }
Definition at line 511 of file mate-app-helper.h.
MATEUIINFO_MENU_VIEW_TREE
#define MATEUIINFO_MENU_VIEW_TREE (tree)
Value:
    { MATE_APP_UI_SUBTREE_STOCK, N_("_View"), NULL, tree, NULL, NULL, \
        (MateUIPixmapType) 0, NULL, 0,  (GdkModifierType) 0, NULL }
Definition at line 558 of file mate-app-helper.h.
MATEUIINFO_MENU_WINDOWS_TREE
#define MATEUIINFO_MENU_WINDOWS_TREE (tree)
Value:
    { MATE_APP_UI_SUBTREE_STOCK, N_("_Windows"), NULL, tree, NULL, NULL, \
        (MateUIPixmapType) 0, NULL, 0,  (GdkModifierType) 0, NULL }
Definition at line 567 of file mate-app-helper.h.
MATEUIINFO_RADIOITEM
#define MATEUIINFO_RADIOITEM (label, tooltip, callback, xpm_data)
Value:
    { MATE_APP_UI_ITEM, label, tooltip, (gpointer)callback, NULL, NULL, \
        MATE_APP_PIXMAP_DATA, xpm_data, 0, (GdkModifierType) 0, NULL }
Definition at line 296 of file mate-app-helper.h.
MATEUIINFO_RADIOITEM_DATA
#define MATEUIINFO_RADIOITEM_DATA (label, tooltip, callback, user_data, xpm_data)
Value:
                    { MATE_APP_UI_ITEM, label, tooltip, (gpointer)callback, \
                      user_data, NULL, MATE_APP_PIXMAP_DATA, xpm_data,  \
                      0, (GdkModifierType) 0, NULL }
Definition at line 301 of file mate-app-helper.h.
MATEUIINFO_RADIOLIST
#define MATEUIINFO_RADIOLIST (list)
Value:
    { MATE_APP_UI_RADIOITEMS, NULL, NULL, list, NULL, NULL, \
        (MateUIPixmapType) 0, NULL, 0,  (GdkModifierType) 0, NULL }
Definition at line 291 of file mate-app-helper.h.
MATEUIINFO_SEPARATOR
#define MATEUIINFO_SEPARATOR
Value:
                      { MATE_APP_UI_SEPARATOR, NULL, NULL, NULL, NULL, NULL,        \
                      (MateUIPixmapType) 0, NULL, 0, (GdkModifierType) 0, NULL }
Definition at line 232 of file mate-app-helper.h.
MATEUIINFO_SUBTREE
#define MATEUIINFO_SUBTREE (label, tree)
Value:
    { MATE_APP_UI_SUBTREE, label, NULL, tree, NULL, NULL, \
        (MateUIPixmapType) 0, NULL, 0,  (GdkModifierType) 0, NULL }
Definition at line 272 of file mate-app-helper.h.
MATEUIINFO_SUBTREE_HINT
#define MATEUIINFO_SUBTREE_HINT (label, hint, tree)
Value:
    { MATE_APP_UI_SUBTREE, label, hint, tree, NULL, NULL, \
        (MateUIPixmapType) 0, NULL, 0,  (GdkModifierType) 0, NULL }
Definition at line 277 of file mate-app-helper.h.
MATEUIINFO_SUBTREE_STOCK
#define MATEUIINFO_SUBTREE_STOCK (label, tree, stock_id)
Value:
    { MATE_APP_UI_SUBTREE, label, NULL, tree, NULL, NULL, \
        MATE_APP_PIXMAP_STOCK, stock_id, 0, (GdkModifierType) 0, NULL }
Definition at line 282 of file mate-app-helper.h.
MATEUIINFO_TOGGLEITEM
#define MATEUIINFO_TOGGLEITEM (label, tooltip, callback, xpm_data)
Value:
    { MATE_APP_UI_TOGGLEITEM, label, tooltip, (gpointer)callback, NULL, NULL, \
        MATE_APP_PIXMAP_DATA, xpm_data, 0, (GdkModifierType) 0, NULL }
Definition at line 256 of file mate-app-helper.h.
MATEUIINFO_TOGGLEITEM_DATA
#define MATEUIINFO_TOGGLEITEM_DATA (label, tooltip, callback, user_data, xpm_data)
Value:
                    { MATE_APP_UI_TOGGLEITEM, label, tooltip, (gpointer)callback,   \
                      user_data, NULL, MATE_APP_PIXMAP_DATA, xpm_data,  \
                      0, (GdkModifierType) 0, NULL }
Definition at line 261 of file mate-app-helper.h.
Typedef Documentation
MateUIBuilderData
typedef struct _MateUIBuilderData MateUIBuilderData
Definition at line 596 of file mate-app-helper.h.
MateUISignalConnectFunc
typedef void(* MateUISignalConnectFunc) (MateUIInfo *uiinfo, const char *signal_name, MateUIBuilderData *uibdata)
Definition at line 598 of file mate-app-helper.h.
Enumeration Type Documentation
MateUIInfoConfigurableTypes
enum MateUIInfoConfigurableTypes
MateUIInfoConfigurableTypes: @MATE_APP_CONFIGURABLE_ITEM_NEW: The "New" menu. @MATE_APP_CONFIGURABLE_ITEM_OPEN: The "Open" menu. @MATE_APP_CONFIGURABLE_ITEM_SAVE: The "Save" menu. @MATE_APP_CONFIGURABLE_ITEM_SAVE_AS: The "Save as..." menu. @MATE_APP_CONFIGURABLE_ITEM_REVERT: The "Revert" menu. @MATE_APP_CONFIGURABLE_ITEM_PRINT: The "Print" menu. @MATE_APP_CONFIGURABLE_ITEM_PRINT_SETUP: The "Print setup..." menu. @MATE_APP_CONFIGURABLE_ITEM_CLOSE: The "Close" menu. @MATE_APP_CONFIGURABLE_ITEM_QUIT: The "Quit" menu. @MATE_APP_CONFIGURABLE_ITEM_CUT: The "Cut" menu. @MATE_APP_CONFIGURABLE_ITEM_COPY: The "Copy" menu. @MATE_APP_CONFIGURABLE_ITEM_PASTE: The "Paste" menu. @MATE_APP_CONFIGURABLE_ITEM_CLEAR: The "Clear" menu. @MATE_APP_CONFIGURABLE_ITEM_UNDO: The "Undo" menu. @MATE_APP_CONFIGURABLE_ITEM_REDO: The "Redo" menu. @MATE_APP_CONFIGURABLE_ITEM_FIND: The "Find..." menu. @MATE_APP_CONFIGURABLE_ITEM_FIND_AGAIN: The "Find again" menu. @MATE_APP_CONFIGURABLE_ITEM_REPLACE: The "Replace..." menu. @MATE_APP_CONFIGURABLE_ITEM_PROPERTIES: The "Properties..." menu. @MATE_APP_CONFIGURABLE_ITEM_PREFERENCES: The "Preferences..." menu. @MATE_APP_CONFIGURABLE_ITEM_ABOUT: The "About..." menu. @MATE_APP_CONFIGURABLE_ITEM_SELECT_ALL: The "Select all" menu. @MATE_APP_CONFIGURABLE_ITEM_NEW_WINDOW: The "New window" menu. @MATE_APP_CONFIGURABLE_ITEM_CLOSE_WINDOW: The "Close window" menu. @MATE_APP_CONFIGURABLE_ITEM_NEW_GAME: The "New game" menu. @MATE_APP_CONFIGURABLE_ITEM_PAUSE_GAME: The "Pause game" menu. @MATE_APP_CONFIGURABLE_ITEM_RESTART_GAME: The "Restart game" menu. @MATE_APP_CONFIGURABLE_ITEM_UNDO_MOVE: The "Undo move" menu. @MATE_APP_CONFIGURABLE_ITEM_REDO_MOVE: The "Redo move" menu. @MATE_APP_CONFIGURABLE_ITEM_HINT: The "Hint" menu. @MATE_APP_CONFIGURABLE_ITEM_SCORES: The "Scores..." menu. @MATE_APP_CONFIGURABLE_ITEM_END_GAME: The "End game" menu.
A user can redefine the accelerator keys for each menu item (if the application supports this). This enum gives an identifier for each menu shortcut that can possible be redefined. If an application is not using one of these accelerators, then no shortcut redefinition is possible unless the application specifically implements it (moral: use standard menu items).
Enumerator
MATE_APP_CONFIGURABLE_ITEM_NEW
MATE_APP_CONFIGURABLE_ITEM_OPEN
MATE_APP_CONFIGURABLE_ITEM_SAVE
MATE_APP_CONFIGURABLE_ITEM_SAVE_AS
MATE_APP_CONFIGURABLE_ITEM_REVERT
MATE_APP_CONFIGURABLE_ITEM_PRINT
MATE_APP_CONFIGURABLE_ITEM_PRINT_SETUP
MATE_APP_CONFIGURABLE_ITEM_CLOSE
MATE_APP_CONFIGURABLE_ITEM_QUIT
MATE_APP_CONFIGURABLE_ITEM_CUT
MATE_APP_CONFIGURABLE_ITEM_COPY
MATE_APP_CONFIGURABLE_ITEM_PASTE
MATE_APP_CONFIGURABLE_ITEM_CLEAR
MATE_APP_CONFIGURABLE_ITEM_UNDO
MATE_APP_CONFIGURABLE_ITEM_REDO
MATE_APP_CONFIGURABLE_ITEM_FIND
MATE_APP_CONFIGURABLE_ITEM_FIND_AGAIN
MATE_APP_CONFIGURABLE_ITEM_REPLACE
MATE_APP_CONFIGURABLE_ITEM_PROPERTIES
MATE_APP_CONFIGURABLE_ITEM_PREFERENCES
MATE_APP_CONFIGURABLE_ITEM_ABOUT
MATE_APP_CONFIGURABLE_ITEM_SELECT_ALL
MATE_APP_CONFIGURABLE_ITEM_NEW_WINDOW
MATE_APP_CONFIGURABLE_ITEM_CLOSE_WINDOW
MATE_APP_CONFIGURABLE_ITEM_NEW_GAME
MATE_APP_CONFIGURABLE_ITEM_PAUSE_GAME
MATE_APP_CONFIGURABLE_ITEM_RESTART_GAME
MATE_APP_CONFIGURABLE_ITEM_UNDO_MOVE
MATE_APP_CONFIGURABLE_ITEM_REDO_MOVE
MATE_APP_CONFIGURABLE_ITEM_HINT
MATE_APP_CONFIGURABLE_ITEM_SCORES
MATE_APP_CONFIGURABLE_ITEM_END_GAME
Definition at line 145 of file mate-app-helper.h.
MateUIInfoType
enum MateUIInfoType
MateUIInfoType: @MATE_APP_UI_ENDOFINFO: No more items, use it at the end of an array. @MATE_APP_UI_ITEM: Normal item, or radio item if it is inside a radioitems group. @MATE_APP_UI_TOGGLEITEM: Toggle (check box) item. @MATE_APP_UI_RADIOITEMS: Radio item group. @MATE_APP_UI_SUBTREE: Item that defines a subtree/submenu. @MATE_APP_UI_SEPARATOR: Separator line (menus) or blank space (toolbars). @MATE_APP_UI_HELP: Create a list of help topics, used in the Help menu. @MATE_APP_UI_BUILDER_DATA: Specifies the builder data for the following entries, see code for further info. @MATE_APP_UI_ITEM_CONFIGURABLE: A configurable menu item. @MATE_APP_UI_SUBTREE_STOCK: Item that defines a subtree/submenu, same as MATE_APP_UI_SUBTREE, but the texts should be looked up in the libmate catalog. @MATE_APP_UI_INCLUDE: Almost like @MATE_APP_UI_SUBTREE, but inserts items into the current menu or whatever, instead of making a submenu.
These values identify the item type that a particular MateUIInfo structure specifies.
One should be careful when using mate_app_create_[custom|interp|with_data] functions with MateUIInfo arrays containing MATE_APP_UI_BUILDER_DATA items, since their MateUIBuilderData structures completely override the ones generated or supplied by the above functions.
Enumerator
MATE_APP_UI_ENDOFINFO
MATE_APP_UI_ITEM
MATE_APP_UI_TOGGLEITEM
MATE_APP_UI_RADIOITEMS
MATE_APP_UI_SUBTREE
MATE_APP_UI_SEPARATOR
MATE_APP_UI_HELP
MATE_APP_UI_BUILDER_DATA
MATE_APP_UI_ITEM_CONFIGURABLE
MATE_APP_UI_SUBTREE_STOCK
MATE_APP_UI_INCLUDE
Definition at line 86 of file mate-app-helper.h.
MateUIPixmapType
enum MateUIPixmapType
MateUIPixmapType: @MATE_APP_PIXMAP_NONE: No pixmap specified. @MATE_APP_PIXMAP_STOCK: Use a stock pixmap (#MateStock). @MATE_APP_PIXMAP_DATA: Use a pixmap from inline xpm data. @MATE_APP_PIXMAP_FILENAME: Use a pixmap from the specified filename.
These values identify the type of pixmap used in an item.
Enumerator
MATE_APP_PIXMAP_NONE
MATE_APP_PIXMAP_STOCK
MATE_APP_PIXMAP_DATA
MATE_APP_PIXMAP_FILENAME
Definition at line 195 of file mate-app-helper.h.
Function Documentation
mate_accelerators_sync()
void mate_accelerators_sync (void)
mate_accelerators_sync:
Flush the accelerator definitions into the application specific configuration file $HOME/.config/mate/accels/<app-id>.
Definition at line 929 of file mate-app-helper.c.
References NULL.
mate_app_create_menus()
void mate_app_create_menus (MateApp * app, MateUIInfo * uiinfo)
mate_app_create_menus @app: A MateApp instance representing the current application. @uiinfo: The first in an array MateUIInfo instances containing the menu data.
Description: Constructs a menu bar and attaches it to the specified application window.
Definition at line 1524 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_create_menus_custom(), MATE_IS_APP, NULL, and _MateUIBuilderData::relay_func.
mate_app_create_menus_custom()
void mate_app_create_menus_custom (MateApp * app, MateUIInfo * uiinfo, MateUIBuilderData * uibdata)
mate_app_create_menus_custom @app: A MateApp instance representing the current application. @uiinfo: The first in an array MateUIInfo instances containing the menu data. @uibdata: An appropriate MateUIBuilderData instance.
Identical to mate_app_create_menus(), except that @uibdata is also specified for creating the signal handlers. Mostly for use by language bindings.
Definition at line 1665 of file mate-app-helper.c.
References _MateApp::accel_group, MATE_APP, mate_app_fill_menu_custom(), mate_app_set_menus(), MATE_IS_APP, mate_mateconf_get_bool, NULL, and TRUE.
Referenced by mate_app_create_menus(), mate_app_create_menus_interp(), and mate_app_create_menus_with_data().
mate_app_create_menus_interp()
void mate_app_create_menus_interp (MateApp * app, MateUIInfo * uiinfo, GtkCallbackMarshal relay_func, gpointer data, GDestroyNotify destroy_func)
mate_app_create_menus_interp @app: A MateApp instance, representing the current application. @uiinfo: The first item in an array of MateUIInfo structures describing the menu bar. @relay_func: A marshaller for the signal callbacks. @data: Application specific data passed to the signal callback functions. @destroy_func: The function to call when the menu bar is destroyed.
Identical to mate_app_create_menus(), except that extra functions and data can be passed in for finer control of the destruction and marshalling.
Definition at line 1556 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, data, _MateUIBuilderData::destroy_func, _MateUIBuilderData::is_interp, mate_app_create_menus_custom(), MATE_IS_APP, NULL, _MateUIBuilderData::relay_func, and TRUE.
mate_app_create_menus_with_data()
void mate_app_create_menus_with_data (MateApp * app, MateUIInfo * uiinfo, gpointer user_data)
mate_app_create_menus_with_data @app: A MateApp instance representing the current application. @uiinfo: The first in an array MateUIInfo instances containing the menu data. @user_data: Application-specific data that is passed to every callback function.
Identical to mate_app_create_menus(), except that @user_data is passed to all the callback functions when signals are emitted.
Definition at line 1589 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_create_menus_custom(), MATE_IS_APP, NULL, _MateUIBuilderData::relay_func, and user_data.
mate_app_create_toolbar()
void mate_app_create_toolbar (MateApp * app, MateUIInfo * uiinfo)
mate_app_create_toolbar @app: A MateApp instance. @uiinfo: A MateUIInfo array specifying the contents of the toolbar.
Description: Constructs a toolbar and attaches it to the specified application window.
Definition at line 1931 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_create_toolbar_custom(), MATE_IS_APP, NULL, and _MateUIBuilderData::relay_func.
mate_app_create_toolbar_custom()
void mate_app_create_toolbar_custom (MateApp * app, MateUIInfo * uiinfo, MateUIBuilderData * uibdata)
mate_app_create_toolbar_custom @app: A MateApp instance. @uiinfo: A MateUIInfo array specifying the contents of the toolbar. @uibdata: A MateUIBuilderData instance specifying the handlers to use for the toolbar.
Description: Constructs a toolbar and attaches it to the @app window, using @uibdata builder data – intended for language bindings.
Definition at line 2025 of file mate-app-helper.c.
References _MateApp::accel_group, mate_app_fill_toolbar_custom(), mate_app_set_toolbar(), MATE_IS_APP, and NULL.
Referenced by mate_app_create_toolbar(), mate_app_create_toolbar_interp(), and mate_app_create_toolbar_with_data().
mate_app_create_toolbar_interp()
void mate_app_create_toolbar_interp (MateApp * app, MateUIInfo * uiinfo, GtkCallbackMarshal relay_func, gpointer data, GDestroyNotify destroy_func)
mate_app_create_toolbar_interp @app: A MateApp instance. @uiinfo: A MateUIInfo array specifying the contents of the toolbar. @relay_func: Argument marshalling function. @data: Application specific data to pass to signal callbacks. @destroy_func: The function to call when the toolbar is destroyed.
Description: Constructs a toolbar and attaches it to the specified application window – this version is intended for language bindings.
Definition at line 1962 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, data, _MateUIBuilderData::destroy_func, _MateUIBuilderData::is_interp, mate_app_create_toolbar_custom(), MATE_IS_APP, NULL, _MateUIBuilderData::relay_func, and TRUE.
mate_app_create_toolbar_with_data()
void mate_app_create_toolbar_with_data (MateApp * app, MateUIInfo * uiinfo, gpointer user_data)
mate_app_create_toolbar_with_data @app: A MateApp instance. @uiinfo: A MateUIInfo array specifying the contents of the toolbar. @user_data: Application specific data to be sent to each signal callback function.
Description: Constructs a toolbar, sets all the user data pointers to @user_data, and attaches it to @app.
Definition at line 1994 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_create_toolbar_custom(), MATE_IS_APP, NULL, _MateUIBuilderData::relay_func, and user_data.
mate_app_fill_menu()
void mate_app_fill_menu (GtkMenuShell * menu_shell, MateUIInfo * uiinfo, GtkAccelGroup * accel_group, gboolean uline_accels, gint pos)
mate_app_fill_menu @menu_shell: A #GtkMenuShell instance (a menu bar). @uiinfo: A pointer to the first element in an array of MateUIInfo structures. The last element of the array should have a type of MATE_APP_UI_ENDOFINFO. @accel_group: A #GtkAccelGroup. @uline_accels: TRUE if underline accelerators will be drawn for the menu item labels. @pos: The position in the menu bar at which to start inserting items.
Description: Fills the specified @menu_shell with items created from the specified @uiinfo, inserting them from the item number @pos on. The @accel_ group will be used as the accel group for all newly created sub menus and serves as the global accel group for all menu item hotkeys. If it is passed as NULL, global hotkeys will be disabled.
Definition at line 1251 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_fill_menu_custom(), NULL, and _MateUIBuilderData::relay_func.
mate_app_fill_menu_custom()
void mate_app_fill_menu_custom (GtkMenuShell * menu_shell, MateUIInfo * uiinfo, MateUIBuilderData * uibdata, GtkAccelGroup * accel_group, gboolean uline_accels, gint pos)
mate_app_fill_menu_custom @menu_shell: A #GtkMenuShell instance (a menu bar). @uiinfo: A pointer to the first element in an array of MateUIInfo structures. The last element of the array should have a type of MATE_APP_UI_ENDOFINFO. @uibdata: A #MateUIInfoBuilderData instance. @accel_group: A #GtkAccelGroup. @uline_accels: TRUE if underline accelerators will be drawn for the menu item labels. @pos: The position in the menu bar at which to start inserting items.
Description: Fills the specified menu shell with items created from the specified @uiinfo, inserting them from item number @pos on and using the specified builder data (@uibdata) – this is intended for language bindings.
The other parameters have the same meaning as in mate_app_fill_menu().
Definition at line 1391 of file mate-app-helper.c.
References FALSE, mate_app_fill_menu_custom(), MATE_APP_UI_BUILDER_DATA, MATE_APP_UI_ENDOFINFO, MATE_APP_UI_HELP, MATE_APP_UI_INCLUDE, MATE_APP_UI_ITEM, MATE_APP_UI_ITEM_CONFIGURABLE, MATE_APP_UI_RADIOITEMS, MATE_APP_UI_SEPARATOR, MATE_APP_UI_SUBTREE, MATE_APP_UI_SUBTREE_STOCK, MATE_APP_UI_TOGGLEITEM, mate_mateconf_get_bool, MateUIInfo::moreinfo, NULL, MateUIInfo::type, and MateUIInfo::widget.
Referenced by mate_app_create_menus_custom(), mate_app_fill_menu(), mate_app_fill_menu_custom(), mate_app_fill_menu_with_data(), mate_app_insert_menus_custom(), and mate_popup_menu_append().
mate_app_fill_menu_with_data()
void mate_app_fill_menu_with_data (GtkMenuShell * menu_shell, MateUIInfo * uiinfo, GtkAccelGroup * accel_group, gboolean uline_accels, gint pos, gpointer user_data)
mate_app_fill_menu_with_data @menu_shell: A #GtkMenuShell instance (a menu bar). @uiinfo: A pointer to the first element in an array of MateUIInfo structures. The last element of the array should have a type of MATE_APP_UI_ENDOFINFO. @accel_group: A #GtkAccelGroup. @uline_accels: TRUE if underline accelerators will be drawn for the menu item labels. @pos: The position in the menu bar at which to start inserting items. @user_data: Some application-specific data.
Description: This is the same as mate_app_fill_menu(), except that all the user data pointers are filled with the value of @user_data.
Definition at line 1295 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_fill_menu_custom(), NULL, _MateUIBuilderData::relay_func, and user_data.
mate_app_fill_toolbar()
void mate_app_fill_toolbar (GtkToolbar * toolbar, MateUIInfo * uiinfo, GtkAccelGroup * accel_group)
mate_app_fill_toolbar @toolbar: A #GtkToolbar instance. @uiinfo: An array of MateUIInfo structures containing the items for the toolbar. @accel_group: A #GtkAccelGroup for holding the accelerator keys of the items (or NULL).
Fills @toolbar with buttons specified in @uiinfo. If @accel_group is not NULL, the items' accelrator keys are put into it.
Definition at line 1809 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_fill_toolbar_custom(), NULL, and _MateUIBuilderData::relay_func.
mate_app_fill_toolbar_custom()
void mate_app_fill_toolbar_custom (GtkToolbar * toolbar, MateUIInfo * uiinfo, MateUIBuilderData * uibdata, GtkAccelGroup * accel_group)
mate_app_fill_toolbar_custom @toolbar: A #GtkToolbar instance. @uiinfo: An array of MateUIInfo structures containing the items for the toolbar. @uibdata: The MateUIBuilderData data for the toolbar. @accel_group: A #GtkAccelGroup for holding the accelerator keys of the items (or NULL).
The same as mate_app_fill_toolbar(), except that the sepcified @uibdata instance is used. This is mostly for the benefit of language bindings.
Definition at line 1875 of file mate-app-helper.c.
References FALSE, mate_app_fill_toolbar_custom(), mate_app_setup_toolbar(), MATE_APP_UI_BUILDER_DATA, MATE_APP_UI_ENDOFINFO, MATE_APP_UI_INCLUDE, MATE_APP_UI_ITEM, MATE_APP_UI_RADIOITEMS, MATE_APP_UI_SEPARATOR, MATE_APP_UI_TOGGLEITEM, MateUIInfo::moreinfo, NULL, MateUIInfo::type, and MateUIInfo::widget.
Referenced by mate_app_create_toolbar_custom(), mate_app_fill_toolbar(), mate_app_fill_toolbar_custom(), and mate_app_fill_toolbar_with_data().
mate_app_fill_toolbar_with_data()
void mate_app_fill_toolbar_with_data (GtkToolbar * toolbar, MateUIInfo * uiinfo, GtkAccelGroup * accel_group, gpointer user_data)
mate_app_fill_toolbar_with_data @toolbar: A #GtkToolbar instance. @uiinfo: An array of MateUIInfo structures containing the items for the toolbar. @accel_group: A #GtkAccelGroup for holding the accelerator keys of the items (or NULL). @user_data: Application specific data.
The same as mate_app_fill_toolbar(), except that the user data pointers in the signal handlers are set to @user_data.
Definition at line 1842 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_fill_toolbar_custom(), NULL, _MateUIBuilderData::relay_func, and user_data.
mate_app_find_menu_pos()
GtkWidget * mate_app_find_menu_pos (GtkWidget * parent, const gchar * path, gint * pos)
mate_app_find_menu_pos @parent: Root menu shell widget containing menu items to be searched. @path: Specifies the target menu item by menu path. @pos: Used to hold the returned menu items' position.
Description: Finds a menu item described by path starting in the #GtkMenuShell top and returns its parent #GtkMenuShell and the position after this item in @pos. The meaning of @pos is that a subsequent call to gtk_menu_shell_insert(p, w, pos) would then insert widget w in GtkMenuShell p right after the menu item described by path.
Returns: The parent menu shell of @path.
Definition at line 2099 of file mate-app-helper.c.
References item, L_, label, mate_app_find_menu_pos(), NULL, and strchr.
Referenced by _mate_mdi_child_list_menu_add_item(), _mate_mdi_child_list_menu_remove_item(), mate_app_find_menu_pos(), mate_app_insert_menus_custom(), mate_app_remove_menu_range(), and mate_app_remove_menus().
mate_app_helper_gettext()
const gchar * mate_app_helper_gettext (const gchar * string)
Definition at line 2418 of file mate-app-helper.c.
mate_app_insert_menus()
void mate_app_insert_menus (MateApp * app, const gchar * path, MateUIInfo * menuinfo)
mate_app_insert_menus @app: A MateApp instance. @path: A path to the menu item concerned. @menuinfo: A MateUIInfo array describing the menus.
Insert the menus given by @menuinfo beginning at @path into the pre-existing @app.
Definition at line 2344 of file mate-app-helper.c.
References FALSE, mate_app_insert_menus_custom(), and NULL.
mate_app_insert_menus_custom()
void mate_app_insert_menus_custom (MateApp * app, const gchar * path, MateUIInfo * uiinfo, MateUIBuilderData * uibdata)
mate_app_insert_menus_custom @app: A MateApp instance. @path: A path to the menu item concerned. @uiinfo: A MateUIInfo array describing the menus. @uibdata: A MateUIBuilderData instance describing the functions to attach as the menu's callbacks.
Description: Inserts menus described by @uiinfo in existing @app's menu structure right after the item described by @path. The @uibdata parameter makes this, again, most useful for language bindings.
Definition at line 2309 of file mate-app-helper.c.
References _MateApp::accel_group, mate_app_fill_menu_custom(), mate_app_find_menu_pos(), MATE_IS_APP, _MateApp::menubar, NULL, and TRUE.
Referenced by mate_app_insert_menus(), mate_app_insert_menus_interp(), and mate_app_insert_menus_with_data().
mate_app_insert_menus_interp()
void mate_app_insert_menus_interp (MateApp * app, const gchar * path, MateUIInfo * menuinfo, GtkCallbackMarshal relay_func, gpointer data, GDestroyNotify destroy_func)
mate_app_insert_menus_interp @app: A MateApp instance. @path: A path to the menu item concerned. @menuinfo: A MateUIInfo array describing the menus. @relay_func: A custom marshallar for signal data., @data: Application-specific data to send to each signal callback. @destroy_func: The function to call when the menu item is destroyed.
THe same as mate_app_insert_menus(), except that the given functions are attached to each menu item. Mostly of use for language bindings.
Definition at line 2399 of file mate-app-helper.c.
References _MateUIBuilderData::data, data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_insert_menus_custom(), NULL, _MateUIBuilderData::relay_func, and TRUE.
mate_app_insert_menus_with_data()
void mate_app_insert_menus_with_data (MateApp * app, const gchar * path, MateUIInfo * menuinfo, gpointer data)
mate_app_insert_menus_with_data @app: A MateApp instance. @path: A path to the menu item concerned. @menuinfo: A MateUIInfo array describing the menus. @data: Application specific data to send to each signal callback.
This is the same as mate_app_insert_menus(), except that the specified @data is passed to each signal callback.
Definition at line 2370 of file mate-app-helper.c.
References _MateUIBuilderData::data, data, FALSE, mate_app_insert_menus_custom(), and NULL.
mate_app_install_appbar_menu_hints()
void mate_app_install_appbar_menu_hints (MateAppBar * appbar, MateUIInfo * uiinfo)
mate_app_install_appbar_menu_hints @appbar: An existing MateAppBar instance. @uiinfo: A MateUIInfo array of a menu for which hints will be set.
Description: Install menu hints for the given @appbar object. This function cannot just be called automatically, since it is impossible to reliably find the correct @appbar.
Definition at line 842 of file mate-app-helper.c.
References mate_app_install_appbar_menu_hints(), mate_app_ui_configure_configurable(), MATE_APP_UI_ENDOFINFO, MATE_APP_UI_HELP, MATE_APP_UI_INCLUDE, MATE_APP_UI_ITEM, MATE_APP_UI_ITEM_CONFIGURABLE, MATE_APP_UI_RADIOITEMS, MATE_APP_UI_SEPARATOR, MATE_APP_UI_SUBTREE, MATE_APP_UI_SUBTREE_STOCK, MATE_APP_UI_TOGGLEITEM, MATE_IS_APPBAR, MateUIInfo::moreinfo, NULL, and MateUIInfo::type.
Referenced by mate_app_install_appbar_menu_hints(), and mate_app_install_menu_hints().
mate_app_install_menu_hints()
void mate_app_install_menu_hints (MateApp * app, MateUIInfo * uiinfo)
mate_app_install_menu_hints @app: An existing MateAppBar instance. @uiinfo: A MateUIInfo array of a menu for which hints will be set.
Description: Set menu hints for the @app object's attached status bar.
Definition at line 896 of file mate-app-helper.c.
References mate_app_install_appbar_menu_hints(), mate_app_install_statusbar_menu_hints(), MATE_APPBAR, MATE_IS_APP, MATE_IS_APPBAR, NULL, and _MateApp::statusbar.
mate_app_install_statusbar_menu_hints()
void mate_app_install_statusbar_menu_hints (GtkStatusbar * bar, MateUIInfo * uiinfo)
mate_app_install_statusbar_menu_hints @bar: Pointer to #GtkStatusbar instance. @uiinfo: MateUIInfo for the menu to be changed.
Description: Install menu hints for the given status bar.
Definition at line 638 of file mate-app-helper.c.
References mate_app_install_statusbar_menu_hints(), MATE_APP_UI_ENDOFINFO, MATE_APP_UI_HELP, MATE_APP_UI_INCLUDE, MATE_APP_UI_ITEM, MATE_APP_UI_RADIOITEMS, MATE_APP_UI_SEPARATOR, MATE_APP_UI_SUBTREE, MATE_APP_UI_SUBTREE_STOCK, MATE_APP_UI_TOGGLEITEM, MateUIInfo::moreinfo, NULL, and MateUIInfo::type.
Referenced by mate_app_install_menu_hints(), and mate_app_install_statusbar_menu_hints().
mate_app_remove_menu_range()
void mate_app_remove_menu_range (MateApp * app, const gchar * path, gint start, gint items)
mate_app_remove_menu_range @app: A MateApp instance. @path: A path to the menu item concerned. @start: An offset beyond the start of @path at which to begin removing. @items: The number of items to remove.
Description: Same as the mate_app_remove_menus(), except it removes the specified number of @items from the existing @app's menu structure begining with item described by (@path plus @start). This is very useful for adding and removing Recent document items in the File menu.
Definition at line 2254 of file mate-app-helper.c.
References mate_app_find_menu_pos(), MATE_IS_APP, _MateApp::menubar, and NULL.
mate_app_remove_menus()
void mate_app_remove_menus (MateApp * app, const gchar * path, gint items)
mate_app_remove_menus @app: A MateApp instance. @path: A path to the menu item concerned. @items: The number of items to remove.
Description: Removes @items items from the existing @app's menu structure, beginning with item described by @path.
The @path argument should be in the form "File/.../.../Something". "" will insert the item as the first one in the menubar, "File/" will insert it as the first one in the File menu, "File/Settings" will insert it after the Setting item in the File menu use of "File/<Separator>" should be obvious. However, the use of "<Separator>" stops after the first separator.
Definition at line 2198 of file mate-app-helper.c.
References mate_app_find_menu_pos(), MATE_IS_APP, _MateApp::menubar, and NULL.
mate_app_setup_toolbar()
void mate_app_setup_toolbar (GtkToolbar * toolbar, MateComponentDockItem * dock_item)
mate_app_setup_toolbar @toolbar: Pointer to a #GtkToolbar instance. @dock_item: Pointer to the #MateComponentDockItem the toolbar is inside, or NULL for none.
Description: Sets up a toolbar to use MATE user preferences.
Definition at line 2666 of file mate-app-helper.c.
References FALSE, mateui_mateconf_lazy_init, NULL, and TRUE.
Referenced by mate_app_add_toolbar(), and mate_app_fill_toolbar_custom().
mate_app_ui_configure_configurable()
void mate_app_ui_configure_configurable (MateUIInfo * uiinfo)
mate_app_ui_configure_configurable @uiinfo: Pointer to MATE UI menu/toolbar info
Description: Configure all user-configurable elements in the given UI info structure. This includes loading and setting previously-set options from MATE config files.
Normally, mate_app_create_menus() calls this function for the developer, but if something needs to be altered afterwards, this function can be called first. The main reason for this function being a public interface is so that it can be called from mate_popup_menu_new(), which clears a copy of the pass in MateUIInfo structures.
Definition at line 755 of file mate-app-helper.c.
References MateUIInfo::ac_mods, MateUIInfo::accelerator_key, MateUIInfo::hint, int(), label, MateUIInfo::label, MATE_APP_CONFIGURABLE_ITEM_NEW, MATE_APP_UI_ITEM, MATE_APP_UI_ITEM_CONFIGURABLE, MateUIInfo::pixmap_info, MateUIInfo::pixmap_type, MateUIInfo::type, and type.
Referenced by mate_app_install_appbar_menu_hints(), and mate_popup_menu_append().