MATE Desktop Environment: mateweather-timezone.c File Reference
mateweather-timezone.c File Reference
#include <string.h>
#include "mateweather-timezone.h"
#include "parser.h"
#include "weather-priv.h"
Macros
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
#define TZ_MAGIC "TZif"
#define TZ_HEADER_SIZE 44
#define TZ_TIMECNT_OFFSET 32
#define TZ_TRANSITIONS_OFFSET 44
#define TZ_TTINFO_SIZE 6
#define TZ_TTINFO_GMTOFF_OFFSET 0
#define TZ_TTINFO_ISDST_OFFSET 4
Functions
MateWeatherTimezone ** mateweather_timezones_parse_xml (MateWeatherParser *parser)
MateWeatherTimezone * mateweather_timezone_ref (MateWeatherTimezone *zone)
void mateweather_timezone_unref (MateWeatherTimezone *zone)
GType mateweather_timezone_get_type (void)
MateWeatherTimezone * mateweather_timezone_get_utc (void)
const char * mateweather_timezone_get_name (MateWeatherTimezone *zone)
const char * mateweather_timezone_get_tzid (MateWeatherTimezone *zone)
int mateweather_timezone_get_offset (MateWeatherTimezone *zone)
gboolean mateweather_timezone_has_dst (MateWeatherTimezone *zone)
int mateweather_timezone_get_dst_offset (MateWeatherTimezone *zone)
Macro Definition Documentation
MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
Definition at line 27 of file mateweather-timezone.c.
TZ_HEADER_SIZE
#define TZ_HEADER_SIZE 44
Definition at line 52 of file mateweather-timezone.c.
TZ_MAGIC
#define TZ_MAGIC "TZif"
Definition at line 51 of file mateweather-timezone.c.
TZ_TIMECNT_OFFSET
#define TZ_TIMECNT_OFFSET 32
Definition at line 53 of file mateweather-timezone.c.
TZ_TRANSITIONS_OFFSET
#define TZ_TRANSITIONS_OFFSET 44
Definition at line 54 of file mateweather-timezone.c.
TZ_TTINFO_GMTOFF_OFFSET
#define TZ_TTINFO_GMTOFF_OFFSET 0
Definition at line 57 of file mateweather-timezone.c.
TZ_TTINFO_ISDST_OFFSET
#define TZ_TTINFO_ISDST_OFFSET 4
Definition at line 58 of file mateweather-timezone.c.
TZ_TTINFO_SIZE
#define TZ_TTINFO_SIZE 6
Definition at line 56 of file mateweather-timezone.c.
Function Documentation
mateweather_timezone_get_dst_offset()
int mateweather_timezone_get_dst_offset (MateWeatherTimezone * zone)
mateweather_timezone_get_dst_offset: @zone: a MateWeatherTimezone
Gets @zone's daylight/summer time offset from UTC, in minutes. Eg, a value of %120 would indicate "GMT+2". This is only meaningful if mateweather_timezone_has_dst() returns TRUE.
Return value: @zone's daylight/summer time offset, in minutes
Definition at line 404 of file mateweather-timezone.c.
References NULL.
mateweather_timezone_get_name()
const char * mateweather_timezone_get_name (MateWeatherTimezone * zone)
mateweather_timezone_get_name: @zone: a MateWeatherTimezone
Gets @zone's name; a translated, user-presentable string.
Note that the returned name might not be unique among timezones, and may not make sense to the user unless it is presented along with the timezone's country's name (or in some context where the country is obvious).
Return value: @zone's name
Definition at line 341 of file mateweather-timezone.c.
References NULL.
mateweather_timezone_get_offset()
int mateweather_timezone_get_offset (MateWeatherTimezone * zone)
mateweather_timezone_get_offset: @zone: a MateWeatherTimezone
Gets @zone's standard offset from UTC, in minutes. Eg, a value of %120 would indicate "GMT+2".
Return value: @zone's standard offset, in minutes
Definition at line 372 of file mateweather-timezone.c.
References NULL.
mateweather_timezone_get_type()
GType mateweather_timezone_get_type (void)
Definition at line 290 of file mateweather-timezone.c.
References mateweather_timezone_ref(), mateweather_timezone_unref(), and type.
mateweather_timezone_get_tzid()
const char * mateweather_timezone_get_tzid (MateWeatherTimezone * zone)
mateweather_timezone_get_tzid: @zone: a MateWeatherTimezone
Gets @zone's tzdata identifier, eg "America/New_York".
Return value: @zone's tzid
Definition at line 356 of file mateweather-timezone.c.
References NULL.
Referenced by mateweather_location_get_timezone(), and mateweather_timezone_menu_get_tzid().
mateweather_timezone_get_utc()
MateWeatherTimezone * mateweather_timezone_get_utc (void)
mateweather_timezone_get_utc:
Gets the UTC timezone.
Return value: a MateWeatherTimezone for UTC, or NULL on error.
Definition at line 312 of file mateweather-timezone.c.
References _, FALSE, and NULL.
mateweather_timezone_has_dst()
gboolean mateweather_timezone_has_dst (MateWeatherTimezone * zone)
mateweather_timezone_has_dst: @zone: a MateWeatherTimezone
Checks if @zone observes daylight/summer time for part of the year.
Return value: TRUE if @zone observes daylight/summer time.
Definition at line 387 of file mateweather-timezone.c.
References FALSE, and NULL.
mateweather_timezone_ref()
MateWeatherTimezone * mateweather_timezone_ref (MateWeatherTimezone * zone)
mateweather_timezone_ref: @zone: a MateWeatherTimezone
Adds 1 to @zone's reference count.
Return value: @zone
Definition at line 263 of file mateweather-timezone.c.
References NULL.
Referenced by mateweather_timezone_get_type().
mateweather_timezone_unref()
void mateweather_timezone_unref (MateWeatherTimezone * zone)
mateweather_timezone_unref: @zone: a MateWeatherTimezone
Subtracts 1 from @zone's reference count and frees it if it reaches 0.
Definition at line 278 of file mateweather-timezone.c.
References NULL.
Referenced by mateweather_location_free_timezones(), mateweather_location_unref(), mateweather_timezone_get_type(), and mateweather_timezones_parse_xml().
mateweather_timezones_parse_xml()
MateWeatherTimezone ** mateweather_timezones_parse_xml (MateWeatherParser * parser)
Definition at line 211 of file mateweather-timezone.c.
References FALSE, mateweather_timezone_unref(), NULL, TRUE, and MateWeatherParser::xml.