MATE Desktop Environment: mate-window-icon.h File Reference
mate-window-icon.h File Reference
#include <gtk/gtk.h>
Functions
void mate_window_icon_set_from_default (GtkWindow *w)
void mate_window_icon_set_from_file (GtkWindow *w, const char *filename)
void mate_window_icon_set_from_file_list (GtkWindow *w, const char **filenames)
void mate_window_icon_set_default_from_file (const char *filename)
void mate_window_icon_set_default_from_file_list (const char **filenames)
void mate_window_icon_init (void)
Function Documentation
mate_window_icon_init()
void mate_window_icon_init (void)
mate_window_icon_init:
Description: Initialize the mate window icon by checking the MATE_DESKTOP_ICON environment variable. This function is automatically called by the mate_init process.
Definition at line 146 of file mate-window-icon.c.
References MATE_CLIENT_CONNECTED, mate_client_set_environment(), MATE_DESKTOP_ICON, mate_master_client(), and mate_window_icon_set_default_from_file().
mate_window_icon_set_default_from_file()
void mate_window_icon_set_default_from_file (const char * filename)
mate_window_icon_set_default_from_file: @filename: filename for the default window icon
Description: Set the default icon to the image in @filename, if one of the mate_window_icon_set_default_from* functions have not already been called.
Definition at line 127 of file mate-window-icon.c.
References mate_window_icon_set_default_from_file_list(), and NULL.
Referenced by mate_window_icon_init().
mate_window_icon_set_default_from_file_list()
void mate_window_icon_set_default_from_file_list (const char ** filenames)
mate_window_icon_set_default_from_file_list: @filenames: NULL terminated string array
Description: Wrapper around gtk_window_set_default_icon_list(), which loads the icons in @filenames.
Definition at line 107 of file mate-window-icon.c.
References NULL.
Referenced by mate_window_icon_set_default_from_file().
mate_window_icon_set_from_default()
void mate_window_icon_set_from_default (GtkWindow * w)
mate_window_icon_set_from_default: @w: the #GtkWidget to set the icon on
Description: Makes the #GtkWindow @w use the default icon.
Definition at line 53 of file mate-window-icon.c.
mate_window_icon_set_from_file()
void mate_window_icon_set_from_file (GtkWindow * w, const char * filename)
mate_window_icon_set_from_file: @w: the #GtkWidget to set the icon on @filename: the name of the file to load
Description: Makes the #GtkWindow @w use the icon in @filename.
Definition at line 87 of file mate-window-icon.c.
References mate_window_icon_set_from_file_list(), and NULL.
mate_window_icon_set_from_file_list()
void mate_window_icon_set_from_file_list (GtkWindow * w, const char ** filenames)
mate_window_icon_set_from_file_list: @w: window to set icons on @filenames: NULL terminated string array
Description: Convenience wrapper around gtk_window_set_icon_list(), which loads the icons in @filenames.
Definition at line 66 of file mate-window-icon.c.
References NULL.
Referenced by mate_window_icon_set_from_file().