MATE Desktop Environment: matemixer-stream.h File Reference
matemixer-stream.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer-enums.h>
#include <libmatemixer/matemixer-types.h>
Classes
struct _MateMixerStream
struct _MateMixerStreamClass
Macros
#define MATE_MIXER_TYPE_STREAM (mate_mixer_stream_get_type ())
#define MATE_MIXER_STREAM(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MATE_MIXER_TYPE_STREAM, MateMixerStream))
#define MATE_MIXER_IS_STREAM(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MATE_MIXER_TYPE_STREAM))
#define MATE_MIXER_STREAM_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MATE_MIXER_TYPE_STREAM, MateMixerStreamClass))
#define MATE_MIXER_IS_STREAM_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MATE_MIXER_TYPE_STREAM))
#define MATE_MIXER_STREAM_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MATE_MIXER_TYPE_STREAM, MateMixerStreamClass))
Typedefs
typedef struct _MateMixerStreamClass MateMixerStreamClass
typedef struct _MateMixerStreamPrivate MateMixerStreamPrivate
Functions
GType mate_mixer_stream_get_type (void)
const gchar * mate_mixer_stream_get_name (MateMixerStream *stream)
const gchar * mate_mixer_stream_get_label (MateMixerStream *stream)
MateMixerDirection mate_mixer_stream_get_direction (MateMixerStream *stream)
MateMixerDevice * mate_mixer_stream_get_device (MateMixerStream *stream)
MateMixerStreamControl * mate_mixer_stream_get_control (MateMixerStream *stream, const gchar *name)
MateMixerStreamSwitch * mate_mixer_stream_get_switch (MateMixerStream *stream, const gchar *name)
MateMixerStreamControl * mate_mixer_stream_get_default_control (MateMixerStream *stream)
const GList * mate_mixer_stream_list_controls (MateMixerStream *stream)
const GList * mate_mixer_stream_list_switches (MateMixerStream *stream)
Macro Definition Documentation
MATE_MIXER_IS_STREAM
#define MATE_MIXER_IS_STREAM (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MATE_MIXER_TYPE_STREAM))
Definition at line 33 of file matemixer-stream.h.
MATE_MIXER_IS_STREAM_CLASS
#define MATE_MIXER_IS_STREAM_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), MATE_MIXER_TYPE_STREAM))
Definition at line 37 of file matemixer-stream.h.
MATE_MIXER_STREAM
#define MATE_MIXER_STREAM (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MATE_MIXER_TYPE_STREAM, MateMixerStream))
Definition at line 31 of file matemixer-stream.h.
MATE_MIXER_STREAM_CLASS
#define MATE_MIXER_STREAM_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), MATE_MIXER_TYPE_STREAM, MateMixerStreamClass))
Definition at line 35 of file matemixer-stream.h.
MATE_MIXER_STREAM_GET_CLASS
#define MATE_MIXER_STREAM_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), MATE_MIXER_TYPE_STREAM, MateMixerStreamClass))
Definition at line 39 of file matemixer-stream.h.
MATE_MIXER_TYPE_STREAM
#define MATE_MIXER_TYPE_STREAM (mate_mixer_stream_get_type ())
Definition at line 29 of file matemixer-stream.h.
Typedef Documentation
MateMixerStreamClass
typedef struct _MateMixerStreamClass MateMixerStreamClass
Definition at line 42 of file matemixer-stream.h.
MateMixerStreamPrivate
typedef struct _MateMixerStreamPrivate MateMixerStreamPrivate
Definition at line 43 of file matemixer-stream.h.
Function Documentation
mate_mixer_stream_get_control()
MateMixerStreamControl * mate_mixer_stream_get_control (MateMixerStream * stream, const gchar * name)
Definition at line 360 of file matemixer-stream.c.
References MATE_MIXER_IS_STREAM, MATE_MIXER_STREAM_GET_CLASS, name, and NULL.
mate_mixer_stream_get_default_control()
MateMixerStreamControl * mate_mixer_stream_get_default_control (MateMixerStream * stream)
mate_mixer_stream_get_default_control: @stream: a MateMixerStream
Definition at line 391 of file matemixer-stream.c.
References MATE_MIXER_IS_STREAM, MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_list_controls(), and NULL.
Referenced by alsa_stream_get_default_control(), alsa_stream_has_default_control(), alsa_stream_remove_elements(), oss_stream_get_default_control(), and oss_stream_has_default_control().
mate_mixer_stream_get_device()
MateMixerDevice * mate_mixer_stream_get_device (MateMixerStream * stream)
mate_mixer_stream_get_device: @stream: a MateMixerStream
Definition at line 347 of file matemixer-stream.c.
References MATE_MIXER_IS_STREAM, and NULL.
Referenced by pulse_stream_get_device().
mate_mixer_stream_get_direction()
MateMixerDirection mate_mixer_stream_get_direction (MateMixerStream * stream)
mate_mixer_stream_get_direction: @stream: a MateMixerStream
Definition at line 335 of file matemixer-stream.c.
References MATE_MIXER_DIRECTION_UNKNOWN, and MATE_MIXER_IS_STREAM.
Referenced by mate_mixer_backend_set_default_input_stream(), and mate_mixer_backend_set_default_output_stream().
mate_mixer_stream_get_label()
const gchar * mate_mixer_stream_get_label (MateMixerStream * stream)
mate_mixer_stream_get_label: @stream: a MateMixerStream
Definition at line 323 of file matemixer-stream.c.
References MATE_MIXER_IS_STREAM, and NULL.
mate_mixer_stream_get_name()
const gchar * mate_mixer_stream_get_name (MateMixerStream * stream)
mate_mixer_stream_get_name: @stream: a MateMixerStream
Definition at line 311 of file matemixer-stream.c.
References MATE_MIXER_IS_STREAM, and NULL.
Referenced by _mate_mixer_backend_set_default_input_stream(), _mate_mixer_backend_set_default_output_stream(), _mate_mixer_stream_set_default_control(), alsa_device_close(), mate_mixer_backend_get_stream(), oss_device_close(), pulse_device_add_stream(), and pulse_device_remove_stream().
mate_mixer_stream_get_switch()
MateMixerStreamSwitch * mate_mixer_stream_get_switch (MateMixerStream * stream, const gchar * name)
Definition at line 378 of file matemixer-stream.c.
References MATE_MIXER_IS_STREAM, MATE_MIXER_STREAM_GET_CLASS, name, and NULL.
mate_mixer_stream_get_type()
GType mate_mixer_stream_get_type (void)
mate_mixer_stream_list_controls()
const GList * mate_mixer_stream_list_controls (MateMixerStream * stream)
mate_mixer_stream_list_controls: @stream: a MateMixerStream
Definition at line 413 of file matemixer-stream.c.
References _MateMixerStreamClass::list_controls, MATE_MIXER_IS_STREAM, MATE_MIXER_STREAM_GET_CLASS, and NULL.
Referenced by mate_mixer_stream_get_default_control(), and oss_device_load().
mate_mixer_stream_list_switches()
const GList * mate_mixer_stream_list_switches (MateMixerStream * stream)
mate_mixer_stream_list_switches: @stream: a MateMixerStream
Definition at line 432 of file matemixer-stream.c.
References _MateMixerStreamClass::list_switches, MATE_MIXER_IS_STREAM, MATE_MIXER_STREAM_GET_CLASS, and NULL.