MATE Desktop Environment: mate-marshal.c File Reference
mate-marshal.c File Reference
#include <glib-object.h>
Macros
#define g_marshal_value_peek_boolean(v) (v)->data[0].v_int
#define g_marshal_value_peek_char(v) (v)->data[0].v_int
#define g_marshal_value_peek_uchar(v) (v)->data[0].v_uint
#define g_marshal_value_peek_int(v) (v)->data[0].v_int
#define g_marshal_value_peek_uint(v) (v)->data[0].v_uint
#define g_marshal_value_peek_long(v) (v)->data[0].v_long
#define g_marshal_value_peek_ulong(v) (v)->data[0].v_ulong
#define g_marshal_value_peek_int64(v) (v)->data[0].v_int64
#define g_marshal_value_peek_uint64(v) (v)->data[0].v_uint64
#define g_marshal_value_peek_enum(v) (v)->data[0].v_long
#define g_marshal_value_peek_flags(v) (v)->data[0].v_ulong
#define g_marshal_value_peek_float(v) (v)->data[0].v_float
#define g_marshal_value_peek_double(v) (v)->data[0].v_double
#define g_marshal_value_peek_string(v) (v)->data[0].v_pointer
#define g_marshal_value_peek_param(v) (v)->data[0].v_pointer
#define g_marshal_value_peek_boxed(v) (v)->data[0].v_pointer
#define g_marshal_value_peek_pointer(v) (v)->data[0].v_pointer
#define g_marshal_value_peek_object(v) (v)->data[0].v_pointer
Functions
void _mate_marshal_BOOLEAN__INT_ENUM_BOOLEAN_ENUM_BOOLEAN (GClosure *closure, GValue *return_value G_GNUC_UNUSED, guint n_param_values, const GValue *param_values, gpointer invocation_hint G_GNUC_UNUSED, gpointer marshal_data)
void _mate_marshal_BOOLEAN__INT_STRING (GClosure *closure, GValue *return_value G_GNUC_UNUSED, guint n_param_values, const GValue *param_values, gpointer invocation_hint G_GNUC_UNUSED, gpointer marshal_data)
void _mate_marshal_BOOLEAN__OBJECT (GClosure *closure, GValue *return_value G_GNUC_UNUSED, guint n_param_values, const GValue *param_values, gpointer invocation_hint G_GNUC_UNUSED, gpointer marshal_data)
void _mate_marshal_BOOLEAN__VOID (GClosure *closure, GValue *return_value G_GNUC_UNUSED, guint n_param_values, const GValue *param_values, gpointer invocation_hint G_GNUC_UNUSED, gpointer marshal_data)
void _mate_marshal_INT__VOID (GClosure *closure, GValue *return_value G_GNUC_UNUSED, guint n_param_values, const GValue *param_values, gpointer invocation_hint G_GNUC_UNUSED, gpointer marshal_data)
void _mate_marshal_VOID__ENUM_BOOLEAN (GClosure *closure, GValue *return_value G_GNUC_UNUSED, guint n_param_values, const GValue *param_values, gpointer invocation_hint G_GNUC_UNUSED, gpointer marshal_data)
void _mate_marshal_VOID__INT_BOXED (GClosure *closure, GValue *return_value G_GNUC_UNUSED, guint n_param_values, const GValue *param_values, gpointer invocation_hint G_GNUC_UNUSED, gpointer marshal_data)
void _mate_marshal_VOID__UINT_UINT_UINT_UINT (GClosure *closure, GValue *return_value G_GNUC_UNUSED, guint n_param_values, const GValue *param_values, gpointer invocation_hint G_GNUC_UNUSED, gpointer marshal_data)
Macro Definition Documentation
g_marshal_value_peek_boolean
#define g_marshal_value_peek_boolean (v) (v)->data[0].v_int
Definition at line 29 of file mate-marshal.c.
g_marshal_value_peek_boxed
#define g_marshal_value_peek_boxed (v) (v)->data[0].v_pointer
Definition at line 44 of file mate-marshal.c.
g_marshal_value_peek_char
#define g_marshal_value_peek_char (v) (v)->data[0].v_int
Definition at line 30 of file mate-marshal.c.
g_marshal_value_peek_double
#define g_marshal_value_peek_double (v) (v)->data[0].v_double
Definition at line 41 of file mate-marshal.c.
g_marshal_value_peek_enum
#define g_marshal_value_peek_enum (v) (v)->data[0].v_long
Definition at line 38 of file mate-marshal.c.
g_marshal_value_peek_flags
#define g_marshal_value_peek_flags (v) (v)->data[0].v_ulong
Definition at line 39 of file mate-marshal.c.
g_marshal_value_peek_float
#define g_marshal_value_peek_float (v) (v)->data[0].v_float
Definition at line 40 of file mate-marshal.c.
g_marshal_value_peek_int
#define g_marshal_value_peek_int (v) (v)->data[0].v_int
Definition at line 32 of file mate-marshal.c.
g_marshal_value_peek_int64
#define g_marshal_value_peek_int64 (v) (v)->data[0].v_int64
Definition at line 36 of file mate-marshal.c.
g_marshal_value_peek_long
#define g_marshal_value_peek_long (v) (v)->data[0].v_long
Definition at line 34 of file mate-marshal.c.
g_marshal_value_peek_object
#define g_marshal_value_peek_object (v) (v)->data[0].v_pointer
Definition at line 46 of file mate-marshal.c.
g_marshal_value_peek_param
#define g_marshal_value_peek_param (v) (v)->data[0].v_pointer
Definition at line 43 of file mate-marshal.c.
g_marshal_value_peek_pointer
#define g_marshal_value_peek_pointer (v) (v)->data[0].v_pointer
Definition at line 45 of file mate-marshal.c.
g_marshal_value_peek_string
#define g_marshal_value_peek_string (v) (v)->data[0].v_pointer
Definition at line 42 of file mate-marshal.c.
g_marshal_value_peek_uchar
#define g_marshal_value_peek_uchar (v) (v)->data[0].v_uint
Definition at line 31 of file mate-marshal.c.
g_marshal_value_peek_uint
#define g_marshal_value_peek_uint (v) (v)->data[0].v_uint
Definition at line 33 of file mate-marshal.c.
g_marshal_value_peek_uint64
#define g_marshal_value_peek_uint64 (v) (v)->data[0].v_uint64
Definition at line 37 of file mate-marshal.c.
g_marshal_value_peek_ulong
#define g_marshal_value_peek_ulong (v) (v)->data[0].v_ulong
Definition at line 35 of file mate-marshal.c.
Function Documentation
_mate_marshal_BOOLEAN__INT_ENUM_BOOLEAN_ENUM_BOOLEAN()
void _mate_marshal_BOOLEAN__INT_ENUM_BOOLEAN_ENUM_BOOLEAN (GClosure * closure, GValue *return_value G_GNUC_UNUSED, guint n_param_values, const GValue * param_values, gpointer invocation_hint G_GNUC_UNUSED, gpointer marshal_data)
Definition at line 52 of file mate-marshal.c.
References closure, g_marshal_value_peek_boolean, g_marshal_value_peek_enum, g_marshal_value_peek_int, and NULL.
Referenced by MATE_CLASS_BOILERPLATE().
_mate_marshal_BOOLEAN__INT_STRING()
void _mate_marshal_BOOLEAN__INT_STRING (GClosure * closure, GValue *return_value G_GNUC_UNUSED, guint n_param_values, const GValue * param_values, gpointer invocation_hint G_GNUC_UNUSED, gpointer marshal_data)
Definition at line 99 of file mate-marshal.c.
References closure, g_marshal_value_peek_int, g_marshal_value_peek_string, and NULL.
_mate_marshal_BOOLEAN__OBJECT()
void _mate_marshal_BOOLEAN__OBJECT (GClosure * closure, GValue *return_value G_GNUC_UNUSED, guint n_param_values, const GValue * param_values, gpointer invocation_hint G_GNUC_UNUSED, gpointer marshal_data)
Definition at line 140 of file mate-marshal.c.
References closure, g_marshal_value_peek_object, and NULL.
Referenced by MATE_CLASS_BOILERPLATE(), and MATE_CLASS_BOILERPLATE().
_mate_marshal_BOOLEAN__VOID()
void _mate_marshal_BOOLEAN__VOID (GClosure * closure, GValue *return_value G_GNUC_UNUSED, guint n_param_values, const GValue * param_values, gpointer invocation_hint G_GNUC_UNUSED, gpointer marshal_data)
Definition at line 179 of file mate-marshal.c.
References closure, and NULL.
_mate_marshal_INT__VOID()
void _mate_marshal_INT__VOID (GClosure * closure, GValue *return_value G_GNUC_UNUSED, guint n_param_values, const GValue * param_values, gpointer invocation_hint G_GNUC_UNUSED, gpointer marshal_data)
Definition at line 216 of file mate-marshal.c.
References closure, and NULL.
_mate_marshal_VOID__ENUM_BOOLEAN()
void _mate_marshal_VOID__ENUM_BOOLEAN (GClosure * closure, GValue *return_value G_GNUC_UNUSED, guint n_param_values, const GValue * param_values, gpointer invocation_hint G_GNUC_UNUSED, gpointer marshal_data)
Definition at line 253 of file mate-marshal.c.
References closure, g_marshal_value_peek_boolean, and g_marshal_value_peek_enum.
_mate_marshal_VOID__INT_BOXED()
void _mate_marshal_VOID__INT_BOXED (GClosure * closure, GValue *return_value G_GNUC_UNUSED, guint n_param_values, const GValue * param_values, gpointer invocation_hint G_GNUC_UNUSED, gpointer marshal_data)
Definition at line 290 of file mate-marshal.c.
References closure, g_marshal_value_peek_boxed, and g_marshal_value_peek_int.
_mate_marshal_VOID__UINT_UINT_UINT_UINT()
void _mate_marshal_VOID__UINT_UINT_UINT_UINT (GClosure * closure, GValue *return_value G_GNUC_UNUSED, guint n_param_values, const GValue * param_values, gpointer invocation_hint G_GNUC_UNUSED, gpointer marshal_data)
Definition at line 329 of file mate-marshal.c.
References closure, and g_marshal_value_peek_uint.
Referenced by MATE_CLASS_BOILERPLATE().