MATE Desktop Environment: mate-popup-menu.c File Reference
mate-popup-menu.c File Reference
#include <config.h>
#include <gtk/gtk.h>
#include "mate-popup-menu.h"
Macros
#define TOPLEVEL_MENUSHELL_KEY "mate-popup-menu:toplevel_menushell_key"
Typedefs
typedef void(* ActivateFunc) (GtkObject *object, gpointer data, GtkWidget *for_widget)
Functions
GtkWidget * mate_popup_menu_new_with_accelgroup (MateUIInfo *uiinfo, GtkAccelGroup *accelgroup)
GtkWidget * mate_popup_menu_new (MateUIInfo *uiinfo)
GtkAccelGroup * mate_popup_menu_get_accel_group (GtkMenu *menu)
void mate_popup_menu_attach (GtkWidget *popup, GtkWidget *widget, gpointer user_data)
void mate_popup_menu_do_popup (GtkWidget *popup, GtkMenuPositionFunc pos_func, gpointer pos_data, GdkEventButton *event, gpointer user_data, GtkWidget *for_widget)
int mate_popup_menu_do_popup_modal (GtkWidget *popup, GtkMenuPositionFunc pos_func, gpointer pos_data, GdkEventButton *event, gpointer user_data, GtkWidget *for_widget)
void mate_popup_menu_append (GtkWidget *popup, MateUIInfo *uiinfo)
void mate_gtk_widget_add_popup_items (GtkWidget *widget, MateUIInfo *uiinfo, gpointer user_data)
Macro Definition Documentation
TOPLEVEL_MENUSHELL_KEY
#define TOPLEVEL_MENUSHELL_KEY "mate-popup-menu:toplevel_menushell_key"
Definition at line 32 of file mate-popup-menu.c.
Typedef Documentation
ActivateFunc
typedef void(* ActivateFunc) (GtkObject *object, gpointer data, GtkWidget *for_widget)
Definition at line 45 of file mate-popup-menu.c.
Function Documentation
mate_gtk_widget_add_popup_items()
void mate_gtk_widget_add_popup_items (GtkWidget * widget, MateUIInfo * uiinfo, gpointer user_data)
mate_gtk_widget_add_popup_items: @widget: The widget to append popup menu items for. @uiinfo: A MateUIInfo array describing new menu elements. @user_data: The user_data to pass to the callbacks for the menu items.
This creates a new popup menu for @widget if none exists, and then adds the items in @uiinfo to the popup menu of @widget.
Definition at line 541 of file mate-popup-menu.c.
References mate_popup_menu_append(), mate_popup_menu_attach(), mate_popup_menu_new(), and user_data.
mate_popup_menu_append()
void mate_popup_menu_append (GtkWidget * popup, MateUIInfo * uiinfo)
mate_popup_menu_append: @popup: An existing popup menu. @uiinfo: A MateUIInfo array describing new menu elements.
Appends the menu items in @uiinfo the @popup menu.
Definition at line 507 of file mate-popup-menu.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_fill_menu_custom(), mate_app_ui_configure_configurable(), MATE_APP_UI_ENDOFINFO, MATE_APP_UI_ITEM_CONFIGURABLE, NULL, _MateUIBuilderData::relay_func, TRUE, MateUIInfo::type, and type.
Referenced by mate_gtk_widget_add_popup_items(), and mate_popup_menu_new_with_accelgroup().
mate_popup_menu_attach()
void mate_popup_menu_attach (GtkWidget * popup, GtkWidget * widget, gpointer user_data)
mate_popup_menu_attach: @popup: A menu widget. @widget: The widget to attach the popup menu to. @user_data: Application specific data passed to the callback.
Attaches the specified popup menu to the specified widget. The menu can then be activated by pressing mouse button 3 over the widget. When a menu item callback is invoked, the specified user_data will be passed to it.
This function requires the widget to have its own window (i.e. GTK_WIDGET_NO_WINDOW (widget) == FALSE), This function will try to set the GDK_BUTTON_PRESS_MASK flag on the widget's event mask if it does not have it yet; if this is the case, then the widget must not be realized for it to work.
The popup menu can be attached to different widgets at the same time. A reference count is kept on the popup menu; when all the widgets it is attached to are destroyed, the popup menu will be destroyed as well.
Under the current implementation, setting a popup menu for a NO_WINDOW widget and then reparenting that widget will cause Bad Things to happen.
Definition at line 304 of file mate-popup-menu.c.
References closure, FALSE, NULL, and user_data.
Referenced by mate_gtk_widget_add_popup_items().
mate_popup_menu_do_popup()
void mate_popup_menu_do_popup (GtkWidget * popup, GtkMenuPositionFunc pos_func, gpointer pos_data, GdkEventButton * event, gpointer user_data, GtkWidget * for_widget)
mate_popup_menu_do_popup: @popup: A menu widget. @pos_func: A user supplied function to position the menu or NULL. @pos_data: User supplied data to pass to @pos_func. @event: A #GdkEventButton structure containing the event that triggered the menu (or NULL). @user_data: Application specific data passed to the menu callback. @for_widget: The widget for which the popup was triggered.
You can use this function to pop up a menu. When a menu item callback is invoked, the specified user_data will be passed to it.
The pos_func and pos_data parameters are the same as for gtk_menu_popup(), i.e. you can use them to specify a function to position the menu explicitly. If you want the default position (near the mouse), pass NULL for these parameters.
The event parameter is needed to figure out the mouse button that activated the menu and the time at which this happened. If you pass in NULL, then no button and the current time will be used as defaults.
Definition at line 392 of file mate-popup-menu.c.
References NULL, and user_data.
mate_popup_menu_do_popup_modal()
int mate_popup_menu_do_popup_modal (GtkWidget * popup, GtkMenuPositionFunc pos_func, gpointer pos_data, GdkEventButton * event, gpointer user_data, GtkWidget * for_widget)
mate_popup_menu_do_popup_modal: @popup: A menu widget. @pos_func: A user supplied function to position the menu or NULL. @pos_data: User supplied data to pass to @pos_func. @event: A #GdkEventButton structure containing the event that triggered the menu (or NULL). @user_data: Application specific data passed to the menu callback. @for_widget: The widget for which the popup was triggered.
Same as mate_popup_do_modal(), but runs the popup menu modally.
Returns: The index of the selected item or -1 if no item selected.
Definition at line 459 of file mate-popup-menu.c.
References id, NULL, and user_data.
mate_popup_menu_get_accel_group()
GtkAccelGroup * mate_popup_menu_get_accel_group (GtkMenu * menu)
mate_popup_menu_get_accel_group @menu: A menu widget.
This function is used to retrieve the accelgroup that was created by mate_popup_menu_new(). If you want to specify the accelgroup that the popup menu accelerators use, then use mate_popup_menu_new_with_accelgroup().
Returns: The accelgroup associated with the specified #GtkMenu.
Definition at line 154 of file mate-popup-menu.c.
References NULL.
mate_popup_menu_new()
GtkWidget * mate_popup_menu_new (MateUIInfo * uiinfo)
mate_popup_menu_new @uiinfo: A MateUIInfo array describing the new menu.
This function behaves just like mate_popup_menu_new_with_accelgroup(), except that it creates an accelgroup for you and attaches it to the menu object. Use mate_popup_menu_get_accel_group() to get the accelgroup that is created.
Returns: A menu widget.
Definition at line 138 of file mate-popup-menu.c.
References mate_popup_menu_new_with_accelgroup(), and NULL.
Referenced by mate_gtk_widget_add_popup_items().
mate_popup_menu_new_with_accelgroup()
GtkWidget * mate_popup_menu_new_with_accelgroup (MateUIInfo * uiinfo, GtkAccelGroup * accelgroup)
mate_popup_menu_new_with_accelgroup @uiinfo: A MateUIInfo array describing the new menu. @accelgroup: A #GtkAccelGroup describing the accelerator key structure.
Creates a popup menu out of the specified @uiinfo array. Use mate_popup_menu_do_popup() to pop the menu up, or attach it to a window with mate_popup_menu_attach().
Returns: A menu widget.
Definition at line 98 of file mate-popup-menu.c.
References mate_popup_menu_append().
Referenced by mate_popup_menu_new().