MATE Desktop Environment: mate-druid.c File Reference
mate-druid.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include <libmate/mate-macros.h>
#include <libmateui/mate-stock-icons.h>
#include "mate-uidefs.h"
#include "mate-druid.h"
Enumerations
enum { CANCEL , HELP , LAST_SIGNAL }
enum { PROP_0 , PROP_SHOW_FINISH , PROP_SHOW_HELP }
Functions
MATE_CLASS_BOILERPLATE (MateDruid, mate_druid, GtkContainer, GTK_TYPE_CONTAINER)
GtkWidget * mate_druid_new (void)
GtkWidget * mate_druid_new_with_window (const char *title, GtkWindow *parent, gboolean close_on_cancel, GtkWidget **window)
void mate_druid_construct_with_window (MateDruid *druid, const char *title, GtkWindow *parent, gboolean close_on_cancel, GtkWidget **window)
void mate_druid_set_buttons_sensitive (MateDruid *druid, gboolean back_sensitive, gboolean next_sensitive, gboolean cancel_sensitive, gboolean help_sensitive)
void mate_druid_set_show_finish (MateDruid *druid, gboolean show_finish)
void mate_druid_set_show_help (MateDruid *druid, gboolean show_help)
void mate_druid_prepend_page (MateDruid *druid, MateDruidPage *page)
void mate_druid_insert_page (MateDruid *druid, MateDruidPage *back_page, MateDruidPage *page)
void mate_druid_append_page (MateDruid *druid, MateDruidPage *page)
void mate_druid_set_page (MateDruid *druid, MateDruidPage *page)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CANCEL
HELP
LAST_SIGNAL
Definition at line 44 of file mate-druid.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_SHOW_FINISH
PROP_SHOW_HELP
Definition at line 49 of file mate-druid.c.
Function Documentation
MATE_CLASS_BOILERPLATE()
MATE_CLASS_BOILERPLATE (MateDruid , mate_druid , GtkContainer , GTK_TYPE_CONTAINER)
Definition at line 99 of file mate-druid.c.
References _, CANCEL, FALSE, HELP, NULL, PROP_SHOW_FINISH, and PROP_SHOW_HELP.
mate_druid_append_page()
void mate_druid_append_page (MateDruid * druid, MateDruidPage * page)
Definition at line 1026 of file mate-druid.c.
References _MateDruid::_priv, mate_druid_insert_page(), MATE_DRUID_PAGE, MATE_IS_DRUID, MATE_IS_DRUID_PAGE, and NULL.
Referenced by main().
mate_druid_construct_with_window()
void mate_druid_construct_with_window (MateDruid * druid, const char * title, GtkWindow * parent, gboolean close_on_cancel, GtkWidget ** window)
mate_druid_construct_with_window: @druid: The MateDruid. @title: A title of the window. @parent: The parent of this window (transient_for). @close_on_cancel: TRUE if the window should be closed when cancel is pressed. @window: Optional return of the #GtkWindow created.
Description: Creates a new toplevel window with the title of @title (which can be NULL) and a parent of @parent (which also can be NULL). The @druid will be placed inside this window. The window and the druid will both be shown. If you need the window widget pointer you can optionally get it through the last argument. When the druid gets destroyed, so will the window that is created here.
See also mate_druid_new_with_window().
Definition at line 810 of file mate-druid.c.
References MATE_IS_DRUID, and NULL.
Referenced by mate_druid_new_with_window().
mate_druid_insert_page()
void mate_druid_insert_page (MateDruid * druid, MateDruidPage * back_page, MateDruidPage * page)
Definition at line 977 of file mate-druid.c.
References _MateDruid::_priv, mate_druid_set_page(), MATE_IS_DRUID, MATE_IS_DRUID_PAGE, and NULL.
Referenced by mate_druid_append_page(), and mate_druid_prepend_page().
mate_druid_new()
GtkWidget * mate_druid_new (void)
mate_druid_new:
Description: Creates a new MateDruid widget. You need to add this to a dialog yourself, it is not a dialog.
Returns: A new MateDruid widget
Definition at line 743 of file mate-druid.c.
References MATE_TYPE_DRUID, and NULL.
Referenced by main().
mate_druid_new_with_window()
GtkWidget * mate_druid_new_with_window (const char * title, GtkWindow * parent, gboolean close_on_cancel, GtkWidget ** window)
mate_druid_new_with_window: @title: A title of the window. @parent: The parent of this window (transient_for). @close_on_cancel: TRUE if the window should be closed when cancel is pressed. @window: Optional return of the #GtkWindow created.
Description: Creates a new MateDruid widget. It also creates a new toplevel window with the title of @title (which can be NULL) and a parent of @parent (which also can be NULL). The window and the druid will both be shown. If you need the window widget pointer you can optionally get it through the last argument. When the druid gets destroyed, so will the window that is created here.
Returns: A new MateDruid widget.
Definition at line 766 of file mate-druid.c.
References MATE_DRUID, mate_druid_construct_with_window(), MATE_TYPE_DRUID, and NULL.
mate_druid_prepend_page()
void mate_druid_prepend_page (MateDruid * druid, MateDruidPage * page)
Definition at line 954 of file mate-druid.c.
References mate_druid_insert_page(), MATE_IS_DRUID, MATE_IS_DRUID_PAGE, and NULL.
mate_druid_set_buttons_sensitive()
void mate_druid_set_buttons_sensitive (MateDruid * druid, gboolean back_sensitive, gboolean next_sensitive, gboolean cancel_sensitive, gboolean help_sensitive)
mate_druid_set_buttons_sensitive @druid: A Druid. @back_sensitive: TRUE if the back button is sensitive. @next_sensitive: TRUE if the next button is sensitive. @cancel_sensitive: TRUE if the cancel button is sensitive. @help_sensitive: TRUE if the help button is sensitive.
Description: Sets the sensitivity of @druid's control-buttons. If the variables are TRUE, then they will be clickable. This function is used primarily by the actual MateDruidPage widgets.
Definition at line 875 of file mate-druid.c.
References _MateDruid::back, _MateDruid::cancel, _MateDruid::help, MATE_IS_DRUID, _MateDruid::next, and NULL.
mate_druid_set_page()
void mate_druid_set_page (MateDruid * druid, MateDruidPage * page)
Definition at line 1051 of file mate-druid.c.
References _MateDruid::_priv, FALSE, MATE_DRUID_PAGE, mate_druid_page_prepare(), MATE_IS_DRUID, MATE_IS_DRUID_PAGE, NULL, and TRUE.
Referenced by mate_druid_insert_page().
mate_druid_set_show_finish()
void mate_druid_set_show_finish (MateDruid * druid, gboolean show_finish)
mate_druid_set_show_finish @druid: A MateDruid widget. @show_finish: If TRUE, then the "Next" button is changed to be "Finish"
Used to specify if @druid is currently showing the last page of the sequence (and hence should display "Finish", rather than "Next").
Definition at line 899 of file mate-druid.c.
References _MateDruid::_priv, FALSE, _MateDruid::finish, MATE_IS_DRUID, _MateDruid::next, and TRUE.
mate_druid_set_show_help()
void mate_druid_set_show_help (MateDruid * druid, gboolean show_help)
mate_druid_set_show_help @druid: A MateDruid. @show_help: TRUE, if the "Help" button is to be shown, FALSE otherwise.
Sets the "Help" button on the druid to be visible in the lower left corner of the widget, if @show_help is TRUE.
Definition at line 926 of file mate-druid.c.
References _MateDruid::_priv, FALSE, _MateDruid::help, MATE_IS_DRUID, and TRUE.