MATE Desktop Environment: mate-messagebox.h File Reference
mate-messagebox.h File Reference
#include "mate-dialog.h"
Classes
struct _MateMessageBox
struct _MateMessageBoxClass
Macros
#define MATE_TYPE_MESSAGE_BOX (mate_message_box_get_type ())
#define MATE_MESSAGE_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_MESSAGE_BOX, MateMessageBox))
#define MATE_MESSAGE_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_MESSAGE_BOX, MateMessageBoxClass))
#define MATE_IS_MESSAGE_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_MESSAGE_BOX))
#define MATE_IS_MESSAGE_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_MESSAGE_BOX))
#define MATE_MESSAGE_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_MESSAGE_BOX, MateMessageBoxClass))
#define MATE_MESSAGE_BOX_INFO "info"
#define MATE_MESSAGE_BOX_WARNING "warning"
#define MATE_MESSAGE_BOX_ERROR "error"
#define MATE_MESSAGE_BOX_QUESTION "question"
#define MATE_MESSAGE_BOX_GENERIC "generic"
Typedefs
typedef struct _MateMessageBox MateMessageBox
typedef struct _MateMessageBoxPrivate MateMessageBoxPrivate
typedef struct _MateMessageBoxClass MateMessageBoxClass
typedef struct _MateMessageBoxButton MateMessageBoxButton
Functions
GType mate_message_box_get_type (void)
GtkWidget * mate_message_box_new (const gchar *message, const gchar *message_box_type,...)
GtkWidget * mate_message_box_newv (const gchar *message, const gchar *message_box_type, const gchar **buttons)
void mate_message_box_construct (MateMessageBox *messagebox, const gchar *message, const gchar *message_box_type, const gchar **buttons)
Macro Definition Documentation
MATE_IS_MESSAGE_BOX
#define MATE_IS_MESSAGE_BOX (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_MESSAGE_BOX))
Definition at line 36 of file mate-messagebox.h.
MATE_IS_MESSAGE_BOX_CLASS
#define MATE_IS_MESSAGE_BOX_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_MESSAGE_BOX))
Definition at line 37 of file mate-messagebox.h.
MATE_MESSAGE_BOX
#define MATE_MESSAGE_BOX (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_MESSAGE_BOX, MateMessageBox))
Definition at line 34 of file mate-messagebox.h.
MATE_MESSAGE_BOX_CLASS
#define MATE_MESSAGE_BOX_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_MESSAGE_BOX, MateMessageBoxClass))
Definition at line 35 of file mate-messagebox.h.
MATE_MESSAGE_BOX_ERROR
#define MATE_MESSAGE_BOX_ERROR "error"
Definition at line 43 of file mate-messagebox.h.
MATE_MESSAGE_BOX_GENERIC
#define MATE_MESSAGE_BOX_GENERIC "generic"
Definition at line 45 of file mate-messagebox.h.
MATE_MESSAGE_BOX_GET_CLASS
#define MATE_MESSAGE_BOX_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_MESSAGE_BOX, MateMessageBoxClass))
Definition at line 38 of file mate-messagebox.h.
MATE_MESSAGE_BOX_INFO
#define MATE_MESSAGE_BOX_INFO "info"
Definition at line 41 of file mate-messagebox.h.
MATE_MESSAGE_BOX_QUESTION
#define MATE_MESSAGE_BOX_QUESTION "question"
Definition at line 44 of file mate-messagebox.h.
MATE_MESSAGE_BOX_WARNING
#define MATE_MESSAGE_BOX_WARNING "warning"
Definition at line 42 of file mate-messagebox.h.
MATE_TYPE_MESSAGE_BOX
#define MATE_TYPE_MESSAGE_BOX (mate_message_box_get_type ())
Definition at line 33 of file mate-messagebox.h.
Typedef Documentation
MateMessageBox
typedef struct _MateMessageBox MateMessageBox
Definition at line 48 of file mate-messagebox.h.
MateMessageBoxButton
typedef struct _MateMessageBoxButton MateMessageBoxButton
Definition at line 51 of file mate-messagebox.h.
MateMessageBoxClass
typedef struct _MateMessageBoxClass MateMessageBoxClass
Definition at line 50 of file mate-messagebox.h.
MateMessageBoxPrivate
typedef struct _MateMessageBoxPrivate MateMessageBoxPrivate
Definition at line 49 of file mate-messagebox.h.
Function Documentation
mate_message_box_construct()
void mate_message_box_construct (MateMessageBox * messagebox, const gchar * message, const gchar * message_box_type, const gchar ** buttons)
mate_message_box_construct: @messagebox: The message box to construct @message: The message to be displayed. @message_box_type: The type of the message @buttons: a NULL terminated array with the buttons to insert.
For language bindings or subclassing, from C use mate_message_box_new or mate_message_box_newv
Definition at line 82 of file mate-messagebox.c.
References _, buttons, FALSE, label, MATE_DIALOG, mate_dialog_constructv(), mate_dialog_set_close(), MATE_IS_MESSAGE_BOX, MATE_MESSAGE_BOX_ERROR, MATE_MESSAGE_BOX_INFO, MATE_MESSAGE_BOX_QUESTION, MATE_MESSAGE_BOX_WARNING, MATE_PAD, message(), NULL, and TRUE.
Referenced by mate_message_box_new(), and mate_message_box_newv().
mate_message_box_get_type()
GType mate_message_box_get_type (void)
mate_message_box_new()
GtkWidget * mate_message_box_new (const gchar * message, const gchar * message_box_type, ...)
mate_message_box_new: @message: The message to be displayed. @message_box_type: The type of the message ...: A NULL terminated list of strings to use in each button.
Creates a dialog box of type @message_box_type with @message. A number of buttons are inserted on it. You can use the MATE stock identifiers to create mate-stock-buttons.
Returns a widget that has the dialog box.
Definition at line 186 of file mate-messagebox.c.
References buttons, data, MATE_DIALOG, mate_dialog_append_button(), mate_message_box_construct(), MATE_TYPE_MESSAGE_BOX, message(), NULL, and TRUE.
mate_message_box_newv()
GtkWidget * mate_message_box_newv (const gchar * message, const gchar * message_box_type, const gchar ** buttons)
mate_message_box_newv: @message: The message to be displayed. @message_box_type: The type of the message @buttons: a NULL terminated array with the buttons to insert.
Creates a dialog box of type @message_box_type with @message. A number of buttons are inserted on it, the messages come from the @buttons array. You can use the MATE stock identifiers to create mate-stock-buttons. The buttons array can be NULL if you wish to add buttons yourself later.
Returns a widget that has the dialog box.
Definition at line 240 of file mate-messagebox.c.
References buttons, mate_message_box_construct(), MATE_TYPE_MESSAGE_BOX, message(), and NULL.