MATE Desktop Environment: menu.c File Reference
menu.c File Reference
#include <config.h>
#include "menu.h"
#include <string.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <libmate-desktop/mate-gsettings.h>
#include <libmate-desktop/mate-image-menu-item.h>
#include <matemenu-tree.h>
#include <libpanel-util/panel-keyfile.h>
#include <libpanel-util/panel-xdg.h>
#include "launcher.h"
#include "panel-util.h"
#include "panel.h"
#include "drawer.h"
#include "panel-config-global.h"
#include "panel-stock-icons.h"
#include "panel-action-button.h"
#include "panel-profile.h"
#include "panel-menu-button.h"
#include "panel-menu-items.h"
#include "panel-globals.h"
#include "panel-run-dialog.h"
#include "panel-lockdown.h"
#include "panel-icon-names.h"
#include "panel-schemas.h"
Functions
GtkWidget * add_menu_separator (GtkWidget *menu)
PanelWidget * menu_get_panel (GtkWidget *menu)
GdkScreen * menuitem_to_screen (GtkWidget *menuitem)
GtkWidget * panel_create_menu (void)
GtkWidget * create_empty_menu (void)
gboolean menu_dummy_button_press_event (GtkWidget *menuitem, GdkEventButton *event)
void setup_menuitem_with_icon (GtkWidget *menuitem, GtkIconSize icon_size, GIcon *gicon, const char *image_filename, const char *title)
void setup_menuitem (GtkWidget *menuitem, GtkIconSize icon_size, GtkWidget *image, const char *title)
void setup_uri_drag (GtkWidget *menuitem, const char *uri, const char *icon, GdkDragAction action)
void setup_internal_applet_drag (GtkWidget *menuitem, PanelActionButtonType type)
GtkWidget * panel_image_menu_item_new (void)
GtkWidget * create_applications_menu (const char *menu_file, const char *menu_path, gboolean always_show_image)
GtkWidget * create_main_menu (PanelWidget *panel)
Function Documentation
add_menu_separator()
GtkWidget * add_menu_separator (GtkWidget * menu)
Definition at line 77 of file mate-panel/mate-panel/menu.c.
References FALSE.
Referenced by panel_menu_items_append_lock_logout(), and panel_recent_append_documents_menu().
create_applications_menu()
GtkWidget * create_applications_menu (const char * menu_file, const char * menu_path, gboolean always_show_image)
Definition at line 1214 of file mate-panel/mate-panel/menu.c.
References create_empty_menu(), error, MATEMENU_TREE_FLAGS_SORT_DISPLAY_NAME, matemenu_tree_load_sync(), matemenu_tree_new(), menu_dummy_button_press_event(), NULL, and TRUE.
Referenced by create_main_menu().
create_empty_menu()
GtkWidget * create_empty_menu (void)
Definition at line 180 of file mate-panel/mate-panel/menu.c.
References menu_dummy_button_press_event(), NULL, and panel_create_menu().
Referenced by create_applications_menu(), and panel_context_menu_create().
create_main_menu()
GtkWidget * create_main_menu (PanelWidget * panel)
Definition at line 1375 of file mate-panel/mate-panel/menu.c.
References create_applications_menu(), main_menu, NULL, and TRUE.
menu_dummy_button_press_event()
gboolean menu_dummy_button_press_event (GtkWidget * menuitem, GdkEventButton * event)
Definition at line 580 of file mate-panel/mate-panel/menu.c.
References FALSE, and TRUE.
Referenced by create_applications_menu(), create_empty_menu(), and panel_recent_append_documents_menu().
menu_get_panel()
PanelWidget * menu_get_panel (GtkWidget * menu)
Definition at line 100 of file mate-panel/mate-panel/menu.c.
References NULL, PANEL_IS_WIDGET, and panels.
Referenced by menuitem_to_screen().
menuitem_to_screen()
GdkScreen * menuitem_to_screen (GtkWidget * menuitem)
Definition at line 152 of file mate-panel/mate-panel/menu.c.
References menu_get_panel(), and _PanelWidget::toplevel.
Referenced by panel_menu_item_activate_desktop_file().
panel_create_menu()
GtkWidget * panel_create_menu (void)
Definition at line 162 of file mate-panel/mate-panel/menu.c.
References NULL, and TRUE.
Referenced by create_empty_menu().
panel_image_menu_item_new()
GtkWidget * panel_image_menu_item_new (void)
Definition at line 964 of file mate-panel/mate-panel/menu.c.
References mate_image_menu_item_new().
setup_internal_applet_drag()
void setup_internal_applet_drag (GtkWidget * menuitem, PanelActionButtonType type)
Definition at line 825 of file mate-panel/mate-panel/menu.c.
References NULL, panel_action_get_drag_id(), panel_action_get_icon_name(), panel_lockdown_get_locked_down(), and type.
setup_menuitem()
void setup_menuitem (GtkWidget * menuitem, GtkIconSize icon_size, GtkWidget * image, const char * title)
Definition at line 742 of file mate-panel/mate-panel/menu.c.
References label, MATE_IMAGE_MENU_ITEM, mate_image_menu_item_set_image(), NULL, and PANEL_DEFAULT_MENU_ICON_SIZE.
Referenced by panel_desktop_menu_item_new(), panel_place_menu_item_new(), and setup_menuitem_with_icon().
setup_menuitem_with_icon()
void setup_menuitem_with_icon (GtkWidget * menuitem, GtkIconSize icon_size, GIcon * gicon, const char * image_filename, const char * title)
Definition at line 716 of file mate-panel/mate-panel/menu.c.
References NULL, panel_gicon_from_icon_name(), and setup_menuitem().
Referenced by panel_recent_append_documents_menu().
setup_uri_drag()
void setup_uri_drag (GtkWidget * menuitem, const char * uri, const char * icon, GdkDragAction action)
Definition at line 791 of file mate-panel/mate-panel/menu.c.
References action, NULL, and panel_lockdown_get_locked_down().