MATE Desktop Environment: mate-keyboard-properties.c File Reference
mate-keyboard-properties.c File Reference
#include <stdlib.h>
#include <gio/gio.h>
#include "capplet-util.h"
#include "activate-settings-daemon.h"
#include "mate-keyboard-properties-a11y.h"
#include "mate-keyboard-properties-xkb.h"
Macros
#define KEYBOARD_SCHEMA "org.mate.peripherals-keyboard"
#define INTERFACE_SCHEMA "org.mate.interface"
#define TYPING_BREAK_SCHEMA "org.mate.typing-break"
#define GET_RANGE(s) GTK_RANGE (gtk_builder_get_object (dialog, s))
Enumerations
enum { RESPONSE_APPLY = 1 , RESPONSE_CLOSE }
Functions
int main (int argc, char **argv)
Macro Definition Documentation
GET_RANGE
#define GET_RANGE (s) GTK_RANGE (gtk_builder_get_object (dialog, s))
Definition at line 44 of file mate-keyboard-properties.c.
INTERFACE_SCHEMA
#define INTERFACE_SCHEMA "org.mate.interface"
Definition at line 41 of file mate-keyboard-properties.c.
KEYBOARD_SCHEMA
#define KEYBOARD_SCHEMA "org.mate.peripherals-keyboard"
Definition at line 40 of file mate-keyboard-properties.c.
TYPING_BREAK_SCHEMA
#define TYPING_BREAK_SCHEMA "org.mate.typing-break"
Definition at line 42 of file mate-keyboard-properties.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RESPONSE_APPLY
RESPONSE_CLOSE
Definition at line 46 of file mate-keyboard-properties.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 129 of file mate-keyboard-properties.c.
References _, activate_settings_daemon(), capplet_init(), capplet_notebook_scroll_event_cb(), capplet_set_icon(), FALSE, finalize_a11y_tabs(), INTERFACE_SCHEMA, KEYBOARD_SCHEMA, N_, NULL, TYPING_BREAK_SCHEMA, and WID.