MATE Desktop Environment: matemixer-app-info-private.h File Reference
matemixer-app-info-private.h File Reference
#include <glib.h>
#include "matemixer-types.h"
Classes
struct _MateMixerAppInfo
Functions
MateMixerAppInfo * _mate_mixer_app_info_new (void)
void _mate_mixer_app_info_set_name (MateMixerAppInfo *info, const gchar *name)
void _mate_mixer_app_info_set_id (MateMixerAppInfo *info, const gchar *id)
void _mate_mixer_app_info_set_version (MateMixerAppInfo *info, const gchar *version)
void _mate_mixer_app_info_set_icon (MateMixerAppInfo *info, const gchar *icon)
MateMixerAppInfo * _mate_mixer_app_info_copy (MateMixerAppInfo *info)
void _mate_mixer_app_info_free (MateMixerAppInfo *info)
Function Documentation
_mate_mixer_app_info_copy()
MateMixerAppInfo * _mate_mixer_app_info_copy (MateMixerAppInfo * info)
_mate_mixer_app_info_copy: @info: a MateMixerAppInfo
Creates a copy of the MateMixerAppInfo.
Returns: a copy of the given @info.
Definition at line 198 of file matemixer-app-info.c.
References _mate_mixer_app_info_new(), _MateMixerAppInfo::icon, _MateMixerAppInfo::id, _MateMixerAppInfo::name, NULL, and _MateMixerAppInfo::version.
Referenced by pulse_stream_control_set_app_info().
_mate_mixer_app_info_free()
void _mate_mixer_app_info_free (MateMixerAppInfo * info)
_mate_mixer_app_info_free: @info: a MateMixerAppInfo
Frees the MateMixerAppInfo.
Definition at line 220 of file matemixer-app-info.c.
References _MateMixerAppInfo::icon, _MateMixerAppInfo::id, _MateMixerAppInfo::name, NULL, and _MateMixerAppInfo::version.
Referenced by pulse_ext_stream_new(), and pulse_stream_control_set_app_info().
_mate_mixer_app_info_new()
MateMixerAppInfo * _mate_mixer_app_info_new (void)
_mate_mixer_app_info_new:
Creates a new empty MateMixerAppInfo structure.
Returns: a new MateMixerAppInfo.
Definition at line 116 of file matemixer-app-info.c.
Referenced by _mate_mixer_app_info_copy(), pulse_ext_stream_new(), pulse_sink_input_new(), and pulse_source_output_new().
_mate_mixer_app_info_set_icon()
void _mate_mixer_app_info_set_icon (MateMixerAppInfo * info, const gchar * icon)
_mate_mixer_app_info_set_version: @info: a MateMixerAppInfo @icon: the application icon name to set
Sets the XDG icon name of the application described by @info.
Definition at line 180 of file matemixer-app-info.c.
References _MateMixerAppInfo::icon, and NULL.
Referenced by mate_mixer_context_set_app_icon(), pulse_sink_input_new(), and pulse_source_output_new().
_mate_mixer_app_info_set_id()
void _mate_mixer_app_info_set_id (MateMixerAppInfo * info, const gchar * id)
_mate_mixer_app_info_set_id: @info: a MateMixerAppInfo @id: the application identifier to set
Sets the identifier of the application described by @info.
Definition at line 146 of file matemixer-app-info.c.
References _MateMixerAppInfo::id, and NULL.
Referenced by mate_mixer_context_set_app_id(), pulse_ext_stream_new(), pulse_sink_input_new(), and pulse_source_output_new().
_mate_mixer_app_info_set_name()
void _mate_mixer_app_info_set_name (MateMixerAppInfo * info, const gchar * name)
Definition at line 129 of file matemixer-app-info.c.
References name, _MateMixerAppInfo::name, and NULL.
Referenced by mate_mixer_context_set_app_name(), pulse_ext_stream_new(), pulse_sink_input_new(), and pulse_source_output_new().
_mate_mixer_app_info_set_version()
void _mate_mixer_app_info_set_version (MateMixerAppInfo * info, const gchar * version)
_mate_mixer_app_info_set_version: @info: a MateMixerAppInfo
Version
: the application version to set
Sets the version of the application described by @info.
Definition at line 163 of file matemixer-app-info.c.
References NULL, and _MateMixerAppInfo::version.
Referenced by mate_mixer_context_set_app_version(), pulse_sink_input_new(), and pulse_source_output_new().