MATE Desktop Environment: mate-ui-init.h File Reference
mate-ui-init.h File Reference
#include <libmate/mate-program.h>
Macros
#define LIBMATEUI_PARAM_CRASH_DIALOG "show-crash-dialog"
#define LIBMATEUI_PARAM_DISPLAY "display"
#define LIBMATEUI_PARAM_DEFAULT_ICON "default-icon"
#define LIBMATEUI_MODULE libmateui_module_info_get()
#define MATE_GTK_MODULE mate_gtk_module_info_get()
#define mate_init(app_id, app_version, argc, argv)
Functions
const MateModuleInfo * libmateui_module_info_get (void)
const MateModuleInfo * mate_gtk_module_info_get (void)
int mate_init_with_popt_table (const char *app_id, const char *app_version, int argc, char **argv, const struct poptOption *options, int flags, poptContext *return_ctx)
Macro Definition Documentation
LIBMATEUI_MODULE
#define LIBMATEUI_MODULE libmateui_module_info_get()
Definition at line 39 of file mate-ui-init.h.
LIBMATEUI_PARAM_CRASH_DIALOG
#define LIBMATEUI_PARAM_CRASH_DIALOG "show-crash-dialog"
Definition at line 35 of file mate-ui-init.h.
LIBMATEUI_PARAM_DEFAULT_ICON
#define LIBMATEUI_PARAM_DEFAULT_ICON "default-icon"
Definition at line 37 of file mate-ui-init.h.
LIBMATEUI_PARAM_DISPLAY
#define LIBMATEUI_PARAM_DISPLAY "display"
Definition at line 36 of file mate-ui-init.h.
MATE_GTK_MODULE
#define MATE_GTK_MODULE mate_gtk_module_info_get()
Definition at line 41 of file mate-ui-init.h.
mate_init
#define mate_init (app_id, app_version, argc, argv)
Value:
    mate_init_with_popt_table (app_id, app_version, \
                    argc, argv, NULL, 0, NULL)
Definition at line 53 of file mate-ui-init.h.
Function Documentation
libmateui_module_info_get()
const MateModuleInfo * libmateui_module_info_get (void)
Definition at line 153 of file mate-ui-init.c.
References _mate_ui_gettext_init(), ARG_DISABLE_CRASH_DIALOG, ARG_DISPLAY, FALSE, mate_client_module_info_get(), mate_mateconf_ui_module_info_get, N_, and NULL.
Referenced by main(), and main().
mate_gtk_module_info_get()
const MateModuleInfo * mate_gtk_module_info_get (void)
Definition at line 792 of file mate-ui-init.c.
Referenced by mate_client_module_info_get().
mate_init_with_popt_table()
int mate_init_with_popt_table (const char * app_id, const char * app_version, int argc, char ** argv, const struct poptOption * options, int flags, poptContext * return_ctx)
mate_init_with_popt_table: @app_id: Application id. @app_version: Application version. @argc: argument count (for example argc as received by main) @argv: argument vector (for example argv as received by main) @options: poptOption table with options to parse @flags: popt flags. @return_ctx: if non-NULL, the popt context is returned here.
Initializes the application. This sets up all of the MATE internals and prepares them (imlib, gdk, session-management, triggers, sound, user preferences).
Unlike mate_init, with mate_init_with_popt_table you can provide a table of popt options (popt is the command line argument parsing library).
Deprecated, use #mate_program_init with the LIBMATEUI_MODULE.
Returns: 0 (always)
Definition at line 767 of file mate-ui-init.c.
References LIBMATEUI_MODULE, and NULL.