MATE Desktop Environment: xutils.h File Reference
xutils.h File Reference
#include <glib.h>
#include <X11/Xlib.h>
#include <X11/Xatom.h>
#include <gdk/gdk.h>
#include <gdk/gdkx.h>
Functions
void _wnck_error_trap_push (void)
int _wnck_error_trap_pop (void)
void _wnck_get_wmclass (Window xwindow, char **res_class, char **res_name)
Function Documentation
_wnck_error_trap_pop()
int _wnck_error_trap_pop (void)
Definition at line 45 of file mate-netbook/maximus/xutils.c.
Referenced by _wnck_get_wmclass().
_wnck_error_trap_push()
void _wnck_error_trap_push (void)
Definition at line 39 of file mate-netbook/maximus/xutils.c.
Referenced by _wnck_get_wmclass().
_wnck_get_wmclass()
void _wnck_get_wmclass (Window xwindow, char ** res_class, char ** res_name)
Definition at line 71 of file mate-netbook/maximus/xutils.c.
References _wnck_error_trap_pop(), _wnck_error_trap_push(), NULL, and UNUSED_VARIABLE.