MATE Desktop Environment: mate-dialog-util.h File Reference
mate-dialog-util.h File Reference
#include "mate-types.h"
Functions
GtkWidget * mate_ok_dialog (const gchar *message)
GtkWidget * mate_ok_dialog_parented (const gchar *message, GtkWindow *parent)
GtkWidget * mate_error_dialog (const gchar *error)
GtkWidget * mate_error_dialog_parented (const gchar *error, GtkWindow *parent)
GtkWidget * mate_warning_dialog (const gchar *warning)
GtkWidget * mate_warning_dialog_parented (const gchar *warning, GtkWindow *parent)
GtkWidget * mate_question_dialog (const gchar *question, MateReplyCallback callback, gpointer data)
GtkWidget * mate_question_dialog_parented (const gchar *question, MateReplyCallback callback, gpointer data, GtkWindow *parent)
GtkWidget * mate_question_dialog_modal (const gchar *question, MateReplyCallback callback, gpointer data)
GtkWidget * mate_question_dialog_modal_parented (const gchar *question, MateReplyCallback callback, gpointer data, GtkWindow *parent)
GtkWidget * mate_ok_cancel_dialog (const gchar *message, MateReplyCallback callback, gpointer data)
GtkWidget * mate_ok_cancel_dialog_parented (const gchar *message, MateReplyCallback callback, gpointer data, GtkWindow *parent)
GtkWidget * mate_ok_cancel_dialog_modal (const gchar *message, MateReplyCallback callback, gpointer data)
GtkWidget * mate_ok_cancel_dialog_modal_parented (const gchar *message, MateReplyCallback callback, gpointer data, GtkWindow *parent)
GtkWidget * mate_request_string_dialog (const gchar *prompt, MateStringCallback callback, gpointer data)
GtkWidget * mate_request_string_dialog_parented (const gchar *prompt, MateStringCallback callback, gpointer data, GtkWindow *parent)
GtkWidget * mate_request_password_dialog (const gchar *prompt, MateStringCallback callback, gpointer data)
GtkWidget * mate_request_password_dialog_parented (const gchar *prompt, MateStringCallback callback, gpointer data, GtkWindow *parent)
GtkWidget * mate_request_dialog (gboolean password, const gchar *prompt, const gchar *default_text, const guint16 max_length, MateStringCallback callback, gpointer data, GtkWindow *parent)
Function Documentation
mate_error_dialog()
GtkWidget * mate_error_dialog (const gchar * error)
mate_error_dialog: @error: Message to display
Description: Creates and shows a error dialog. This is an OK dialog to display on fatally failed operations.
Returns: Pointer to new MATE dialog object.
Definition at line 95 of file mate-dialog-util.c.
References error, MATE_MESSAGE_BOX_ERROR, and NULL.
mate_error_dialog_parented()
GtkWidget * mate_error_dialog_parented (const gchar * error, GtkWindow * parent)
mate_error_dialog_parented: @error: Message to display @parent: Parent window
Description: Creates and shows a error dialog. This is an OK dialog to display on fatally failed operations.
Returns: Pointer to new MATE dialog object.
Definition at line 111 of file mate-dialog-util.c.
References error, and MATE_MESSAGE_BOX_ERROR.
Referenced by mate_app_error().
mate_ok_cancel_dialog()
GtkWidget * mate_ok_cancel_dialog (const gchar * message, MateReplyCallback callback, gpointer data)
mate_ok_cancel_dialog: @message: Message to display @callback: Callback function for handling dialog results @data: Data to pass to callback
Description: Creates an OK/Cancel dialog and calls @callback when user answers the button number is passed onto 'reply'. 0 is for 'OK', 1 for 'Cancel'.
void (* MateReplyCallback)(gint reply, gpointer data);
Returns: Pointer to new MATE dialog object.
Definition at line 321 of file mate-dialog-util.c.
References data, FALSE, message(), and NULL.
mate_ok_cancel_dialog_modal()
GtkWidget * mate_ok_cancel_dialog_modal (const gchar * message, MateReplyCallback callback, gpointer data)
mate_ok_cancel_dialog_modal: @message: Message to display @callback: Callback function for handling dialog results @data: Data to pass to callback
Description: Creates an OK/Cancel dialog and calls @callback when user answers the button number is passed onto 'reply'. 0 is for 'OK', 1 for 'Cancel'. The dialog is created as a modal dialog and the user will have to answer this before proceeding.
void (* MateReplyCallback)(gint reply, gpointer data);
Returns: Pointer to new MATE dialog object.
Definition at line 366 of file mate-dialog-util.c.
References data, FALSE, message(), NULL, and TRUE.
mate_ok_cancel_dialog_modal_parented()
GtkWidget * mate_ok_cancel_dialog_modal_parented (const gchar * message, MateReplyCallback callback, gpointer data, GtkWindow * parent)
mate_ok_cancel_dialog_modal_parented: @message: Message to display @callback: Callback function for handling dialog results @data: Data to pass to callback @parent: Parent window
Description: Creates and shows an OK/Cancel dialog and calls @callback when user answers the button number is passed onto 'reply'. 0 is for 'OK', 1 for 'Cancel'. The dialog is created as a modal dialog and the user will have to answer this before proceeding.
void (* MateReplyCallback)(gint reply, gpointer data);
Returns: Pointer to new MATE dialog object.
Definition at line 389 of file mate-dialog-util.c.
References data, FALSE, message(), and TRUE.
Referenced by mate_app_ok_cancel_modal().
mate_ok_cancel_dialog_parented()
GtkWidget * mate_ok_cancel_dialog_parented (const gchar * message, MateReplyCallback callback, gpointer data, GtkWindow * parent)
mate_ok_cancel_dialog_parented: @message: Message to display @callback: Callback function for handling dialog results @data: Data to pass to callback @parent: Parent window
Description: Creates an OK/Cancel dialog and calls @callback when user answers the button number is passed onto 'reply'. 0 is for 'OK', 1 for 'Cancel'.
void (* MateReplyCallback)(gint reply, gpointer data);
Returns: Pointer to new MATE dialog object.
Definition at line 343 of file mate-dialog-util.c.
References data, FALSE, and message().
Referenced by mate_app_ok_cancel().
mate_ok_dialog()
GtkWidget * mate_ok_dialog (const gchar * message)
mate_ok_dialog: @message: Message to display
Description: Creates and shows a simple message dialog.
Returns: Pointer to new MATE dialog object.
Definition at line 64 of file mate-dialog-util.c.
References MATE_MESSAGE_BOX_INFO, message(), and NULL.
mate_ok_dialog_parented()
GtkWidget * mate_ok_dialog_parented (const gchar * message, GtkWindow * parent)
mate_ok_dialog_parented: @message: Message to display @parent: Parent window
Description: Creates and shows a simple message dialog.
Returns: Pointer to new MATE dialog object.
Definition at line 79 of file mate-dialog-util.c.
References MATE_MESSAGE_BOX_INFO, and message().
Referenced by mate_app_message().
mate_question_dialog()
GtkWidget * mate_question_dialog (const gchar * question, MateReplyCallback callback, gpointer data)
mate_question_dialog: @question: Question to ask @callback: Callback function for handling dialog results @data: Data to pass to callback
Description: Creates a question dialog and calls @callback when user answers the button number is passed onto 'reply'. 0 is for 'Yes', 1 for 'No'
void (* MateReplyCallback)(gint reply, gpointer data);
Returns: Pointer to new MATE dialog object.
Definition at line 229 of file mate-dialog-util.c.
References data, FALSE, NULL, and TRUE.
mate_question_dialog_modal()
GtkWidget * mate_question_dialog_modal (const gchar * question, MateReplyCallback callback, gpointer data)
mate_question_dialog_modal: @question: Question to ask @callback: Callback function for handling dialog results @data: Data to pass to callback
Description: Creates a question dialog and calls @callback when user answers the button number is passed onto 'reply'. 0 is for 'Yes', 1 for 'No'. The dialog is created as a modal dialog and the user will have to answer this before proceeding.
void (* MateReplyCallback)(gint reply, gpointer data);
Returns: Pointer to new MATE dialog object.
Definition at line 274 of file mate-dialog-util.c.
References data, NULL, and TRUE.
mate_question_dialog_modal_parented()
GtkWidget * mate_question_dialog_modal_parented (const gchar * question, MateReplyCallback callback, gpointer data, GtkWindow * parent)
mate_question_dialog_modal_parented: @question: Question to ask @callback: Callback function for handling dialog results @data: Data to pass to callback @parent: Parent window
Description: Creates a question dialog and calls @callback when user answers the button number is passed onto 'reply'. 0 is for 'Yes', 1 for 'No'. The dialog is created as a modal dialog and the user will have to answer this before proceeding.
void (* MateReplyCallback)(gint reply, gpointer data);
Returns: Pointer to new MATE dialog object.
Definition at line 296 of file mate-dialog-util.c.
References data, and TRUE.
Referenced by mate_app_question_modal().
mate_question_dialog_parented()
GtkWidget * mate_question_dialog_parented (const gchar * question, MateReplyCallback callback, gpointer data, GtkWindow * parent)
mate_question_dialog_parented: @question: Question to ask @callback: Callback function for handling dialog results @data: Data to pass to callback @parent: Parent window
Description: Creates a question dialog and calls @callback when user answers the button number is passed onto 'reply'. 0 is for 'Yes', 1 for 'No'
void (* MateReplyCallback)(gint reply, gpointer data);
Returns: Pointer to new MATE dialog object.
Definition at line 251 of file mate-dialog-util.c.
References data, FALSE, and TRUE.
Referenced by mate_app_question().
mate_request_dialog()
GtkWidget * mate_request_dialog (gboolean password, const gchar * prompt, const gchar * default_text, const guint16 max_length, MateStringCallback callback, gpointer data, GtkWindow * parent)
mate_request_dialog: @password: TRUE if on-screen text input is masked @prompt: Text of the prompt to be displayed @default_text: Default text in entry widget, NULL if none @max_length: Maximum input chars allowed @callback: Callback function for handling dialog results @data: Data passed to the callback @parent: Parent window, or NULL for no parent.
Description: Creates and shows a MATE text entry request dialog. @callback is called when the dialog closes, passing the text entry input or NULL if the user cancelled. @callback is defined as
void (* MateStringCallback)(gchar * string, gpointer data);
Returns: Pointer to new MATE dialog object.
Definition at line 560 of file mate-dialog-util.c.
References data.
Referenced by mate_app_request_password(), and mate_app_request_string().
mate_request_password_dialog()
GtkWidget * mate_request_password_dialog (const gchar * prompt, MateStringCallback callback, gpointer data)
mate_request_password_dialog: @prompt: @callback: @data:
Deprecated, use mate_request_dialog instead.
Returns:
Definition at line 515 of file mate-dialog-util.c.
References data, NULL, and TRUE.
mate_request_password_dialog_parented()
GtkWidget * mate_request_password_dialog_parented (const gchar * prompt, MateStringCallback callback, gpointer data, GtkWindow * parent)
mate_request_password_dialog_parented: @prompt: @callback: @data: @parent:
Description: Deprecated, use mate_request_dialog.
Returns:
Definition at line 533 of file mate-dialog-util.c.
References data, NULL, and TRUE.
mate_request_string_dialog()
GtkWidget * mate_request_string_dialog (const gchar * prompt, MateStringCallback callback, gpointer data)
mate_request_string_dialog: @prompt: @callback: @data:
Description: Deprecated, use mate_request_dialog
Returns:
Definition at line 476 of file mate-dialog-util.c.
References data, FALSE, and NULL.
mate_request_string_dialog_parented()
GtkWidget * mate_request_string_dialog_parented (const gchar * prompt, MateStringCallback callback, gpointer data, GtkWindow * parent)
mate_request_string_dialog_parented: @prompt: @callback: @data: @parent:
Description: Deprecated, use mate_request_dialog
Returns:
Definition at line 495 of file mate-dialog-util.c.
References data, FALSE, and NULL.
mate_warning_dialog()
GtkWidget * mate_warning_dialog (const gchar * warning)
mate_warning_dialog:
Warning
: Message to display
Description: Creates and shows a warning dialog. For non-fatal warnings.
Returns: Pointer to new MATE dialog object.
Definition at line 127 of file mate-dialog-util.c.
References MATE_MESSAGE_BOX_WARNING, and NULL.
mate_warning_dialog_parented()
GtkWidget * mate_warning_dialog_parented (const gchar * warning, GtkWindow * parent)
mate_warning_dialog_parented:
Warning
: Message to display @parent: Parent window
Description: Creates and shows a warning dialog. For non-fatal warnings.
Returns: Pointer to new MATE dialog object.
Definition at line 143 of file mate-dialog-util.c.
References MATE_MESSAGE_BOX_WARNING.
Referenced by mate_app_warning().