MATE Desktop Environment: mate-notification-applet-dbus.h File Reference
mate-notification-applet-dbus.h File Reference
#include <gio/gio.h>
Classes
struct MateNotificationDBusContext
Functions
MateNotificationDBusContext * dbus_context_new (void)
void dbus_context_free (MateNotificationDBusContext *context)
gboolean dbus_context_connect (MateNotificationDBusContext *context)
void dbus_context_disconnect (MateNotificationDBusContext *context)
gboolean dbus_context_is_available (MateNotificationDBusContext *context)
guint dbus_context_get_notification_count (MateNotificationDBusContext *context)
gboolean dbus_context_clear_notification_history (MateNotificationDBusContext *context)
gboolean dbus_context_mark_all_notifications_as_read (MateNotificationDBusContext *context)
GVariant * dbus_context_get_notification_history (MateNotificationDBusContext *context)
Function Documentation
dbus_context_clear_notification_history()
gboolean dbus_context_clear_notification_history (MateNotificationDBusContext * context)
Definition at line 131 of file mate-notification-applet-dbus.c.
References MateNotificationDBusContext::daemon_proxy, dbus_context_is_available(), error, FALSE, NULL, and TRUE.
Referenced by call_clear_history().
dbus_context_connect()
gboolean dbus_context_connect (MateNotificationDBusContext * context)
Definition at line 49 of file mate-notification-applet-dbus.c.
References MateNotificationDBusContext::daemon_available, MateNotificationDBusContext::daemon_proxy, dbus_context_disconnect(), error, FALSE, NOTIFICATION_BUS_NAME, NOTIFICATION_BUS_PATH, NULL, and TRUE.
dbus_context_disconnect()
void dbus_context_disconnect (MateNotificationDBusContext * context)
Definition at line 81 of file mate-notification-applet-dbus.c.
References MateNotificationDBusContext::daemon_available, MateNotificationDBusContext::daemon_proxy, FALSE, and NULL.
Referenced by dbus_context_connect(), and dbus_context_free().
dbus_context_free()
void dbus_context_free (MateNotificationDBusContext * context)
Definition at line 40 of file mate-notification-applet-dbus.c.
References dbus_context_disconnect().
dbus_context_get_notification_count()
guint dbus_context_get_notification_count (MateNotificationDBusContext * context)
Definition at line 101 of file mate-notification-applet-dbus.c.
References MateNotificationDBusContext::daemon_available, MateNotificationDBusContext::daemon_proxy, dbus_context_is_available(), error, FALSE, and NULL.
dbus_context_get_notification_history()
GVariant * dbus_context_get_notification_history (MateNotificationDBusContext * context)
Definition at line 191 of file mate-notification-applet-dbus.c.
References MateNotificationDBusContext::daemon_proxy, dbus_context_is_available(), error, and NULL.
Referenced by show_notification_history().
dbus_context_is_available()
gboolean dbus_context_is_available (MateNotificationDBusContext * context)
Definition at line 95 of file mate-notification-applet-dbus.c.
References MateNotificationDBusContext::daemon_available, and MateNotificationDBusContext::daemon_proxy.
Referenced by dbus_context_clear_notification_history(), dbus_context_get_notification_count(), dbus_context_get_notification_history(), dbus_context_mark_all_notifications_as_read(), and show_notification_history().
dbus_context_mark_all_notifications_as_read()
gboolean dbus_context_mark_all_notifications_as_read (MateNotificationDBusContext * context)
Definition at line 161 of file mate-notification-applet-dbus.c.
References MateNotificationDBusContext::daemon_proxy, dbus_context_is_available(), error, FALSE, NULL, and TRUE.
dbus_context_new()
MateNotificationDBusContext * dbus_context_new (void)
Definition at line 30 of file mate-notification-applet-dbus.c.
References MateNotificationDBusContext::daemon_available, MateNotificationDBusContext::daemon_proxy, FALSE, NULL, and MateNotificationDBusContext::watch_id.