MATE Desktop Environment: mate-href.h File Reference
mate-href.h File Reference
#include <glib.h>
#include <gtk/gtk.h>
Classes
struct _MateHRef
struct _MateHRefClass
Macros
#define MATE_TYPE_HREF (mate_href_get_type ())
#define MATE_HREF(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), MATE_TYPE_HREF, MateHRef))
#define MATE_HREF_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), MATE_TYPE_HREF, MateHRefClass))
#define MATE_IS_HREF(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), MATE_TYPE_HREF))
#define MATE_IS_HREF_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_HREF))
#define MATE_HREF_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_HREF, MateHRefClass))
Typedefs
typedef struct _MateHRef MateHRef
typedef struct _MateHRefPrivate MateHRefPrivate
typedef struct _MateHRefClass MateHRefClass
Functions
GType mate_href_get_type (void)
GtkWidget * mate_href_new (const gchar *url, const gchar *text)
void mate_href_set_url (MateHRef *href, const gchar *url)
const gchar * mate_href_get_url (MateHRef *href)
void mate_href_set_text (MateHRef *href, const gchar *text)
const gchar * mate_href_get_text (MateHRef *href)
void mate_href_set_label (MateHRef *href, const gchar *label)
const gchar * mate_href_get_label (MateHRef *href)
Macro Definition Documentation
MATE_HREF
#define MATE_HREF (obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), MATE_TYPE_HREF, MateHRef))
Definition at line 37 of file mate-href.h.
MATE_HREF_CLASS
#define MATE_HREF_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), MATE_TYPE_HREF, MateHRefClass))
Definition at line 38 of file mate-href.h.
MATE_HREF_GET_CLASS
#define MATE_HREF_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_HREF, MateHRefClass))
Definition at line 41 of file mate-href.h.
MATE_IS_HREF
#define MATE_IS_HREF (obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), MATE_TYPE_HREF))
Definition at line 39 of file mate-href.h.
MATE_IS_HREF_CLASS
#define MATE_IS_HREF_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_HREF))
Definition at line 40 of file mate-href.h.
MATE_TYPE_HREF
#define MATE_TYPE_HREF (mate_href_get_type ())
Definition at line 36 of file mate-href.h.
Typedef Documentation
MateHRef
typedef struct _MateHRef MateHRef
Definition at line 43 of file mate-href.h.
MateHRefClass
typedef struct _MateHRefClass MateHRefClass
Definition at line 45 of file mate-href.h.
MateHRefPrivate
typedef struct _MateHRefPrivate MateHRefPrivate
Definition at line 44 of file mate-href.h.
Function Documentation
mate_href_get_label()
const gchar * mate_href_get_label (MateHRef * href)
mate_href_get_label @href: Pointer to MateHRef widget
Deprecated, use mate_href_get_text.
Returns:
Definition at line 342 of file mate-href.c.
References mate_href_get_text().
mate_href_get_text()
const gchar * mate_href_get_text (MateHRef * href)
mate_href_get_text @href: Pointer to MateHRef widget
Description: Returns the contents of the label widget used to display the link text. Note that the string should not be freed as it points to internal memory.
Returns: Pointer to text contained in the label widget.
Definition at line 298 of file mate-href.c.
References _MateHRef::_priv, MATE_IS_HREF, and NULL.
Referenced by mate_href_get_label().
mate_href_get_type()
GType mate_href_get_type (void)
mate_href_get_url()
const gchar * mate_href_get_url (MateHRef * href)
mate_href_get_url @href: Pointer to MateHRef widget
Description: Returns the pointer to the URL associated with the @href href object. Note that the string should not be freed as it is internal memory.
Returns: Pointer to an internal URL string, or NULL if failure.
Definition at line 223 of file mate-href.c.
References _MateHRef::_priv, MATE_IS_HREF, and NULL.
mate_href_new()
GtkWidget * mate_href_new (const gchar * url, const gchar * text)
mate_href_new @url: URL assigned to this object. @text: Text associated with the URL.
Description: Created a MATE href object, a label widget with a clickable action and an associated URL. If @text is set to NULL, @url is used as the text for the label.
Returns: Pointer to new MATE href widget.
Definition at line 197 of file mate-href.c.
References MATE_TYPE_HREF, and NULL.
mate_href_set_label()
void mate_href_set_label (MateHRef * href, const gchar * label)
mate_href_set_label @href: Pointer to MateHRef widget @label: New link text for the href object.
Description: deprecated, use mate_href_set_text
Definition at line 359 of file mate-href.c.
References label, mate_href_set_text(), MATE_IS_HREF, and NULL.
mate_href_set_text()
void mate_href_set_text (MateHRef * href, const gchar * text)
mate_href_set_text @href: Pointer to MateHRef widget @text: New link text for the href object.
Description: Sets the internal label widget text (used to display a URL's link text) to the value given in @label.
Definition at line 318 of file mate-href.c.
References _MateHRef::_priv, MATE_IS_HREF, and NULL.
Referenced by mate_href_set_label().
mate_href_set_url()
void mate_href_set_url (MateHRef * href, const gchar * url)
mate_href_set_url @href: Pointer to MateHRef widget @url: String containing the URL to be stored within @href.
Description: Sets the internal URL value within @href to the value of @url.
Definition at line 239 of file mate-href.c.
References _MateHRef::_priv, MATE_IS_HREF, and NULL.