MATE Desktop Environment: mate-appbar.h File Reference
mate-appbar.h File Reference
#include <gtk/gtk.h>
#include "mate-types.h"
Classes
struct _MateAppBar
struct _MateAppBarClass
Macros
#define MATE_TYPE_APPBAR (mate_appbar_get_type ())
#define MATE_APPBAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_APPBAR, MateAppBar))
#define MATE_APPBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_APPBAR, MateAppBarClass))
#define MATE_IS_APPBAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_APPBAR))
#define MATE_IS_APPBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_APPBAR))
#define MATE_APPBAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_APPBAR, MateAppBarClass))
#define MATE_APPBAR_HAS_STATUS(appbar) (mate_appbar_get_status(MATE_APPBAR(appbar)) != NULL)
#define MATE_APPBAR_HAS_PROGRESS(appbar) (mate_appbar_get_progress(MATE_APPBAR(appbar)) != NULL)
#define MATE_APPBAR_INTERACTIVE(ab) ((ab) ? (ab)->interactive : FALSE)
Typedefs
typedef struct _MateAppBar MateAppBar
typedef struct _MateAppBarPrivate MateAppBarPrivate
typedef struct _MateAppBarClass MateAppBarClass
typedef struct _MateAppBarMsg MateAppBarMsg
Functions
GType mate_appbar_get_type (void)
GtkWidget * mate_appbar_new (gboolean has_progress, gboolean has_status, MatePreferencesType interactivity)
void mate_appbar_set_status (MateAppBar *appbar, const gchar *status)
GtkWidget * mate_appbar_get_status (MateAppBar *appbar)
void mate_appbar_set_default (MateAppBar *appbar, const gchar *default_status)
void mate_appbar_push (MateAppBar *appbar, const gchar *status)
void mate_appbar_pop (MateAppBar *appbar)
void mate_appbar_clear_stack (MateAppBar *appbar)
void mate_appbar_set_progress_percentage (MateAppBar *appbar, gfloat percentage)
GtkProgressBar * mate_appbar_get_progress (MateAppBar *appbar)
void mate_appbar_refresh (MateAppBar *appbar)
void mate_appbar_set_prompt (MateAppBar *appbar, const gchar *prompt, gboolean modal)
void mate_appbar_clear_prompt (MateAppBar *appbar)
gchar * mate_appbar_get_response (MateAppBar *appbar)
Macro Definition Documentation
MATE_APPBAR
#define MATE_APPBAR (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_APPBAR, MateAppBar))
Definition at line 40 of file mate-appbar.h.
MATE_APPBAR_CLASS
#define MATE_APPBAR_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_APPBAR, MateAppBarClass))
Definition at line 41 of file mate-appbar.h.
MATE_APPBAR_GET_CLASS
#define MATE_APPBAR_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_APPBAR, MateAppBarClass))
Definition at line 44 of file mate-appbar.h.
MATE_APPBAR_HAS_PROGRESS
#define MATE_APPBAR_HAS_PROGRESS (appbar) (mate_appbar_get_progress(MATE_APPBAR(appbar)) != NULL)
Definition at line 48 of file mate-appbar.h.
MATE_APPBAR_HAS_STATUS
#define MATE_APPBAR_HAS_STATUS (appbar) (mate_appbar_get_status(MATE_APPBAR(appbar)) != NULL)
Definition at line 47 of file mate-appbar.h.
MATE_APPBAR_INTERACTIVE
#define MATE_APPBAR_INTERACTIVE (ab) ((ab) ? (ab)->interactive : FALSE)
Definition at line 77 of file mate-appbar.h.
MATE_IS_APPBAR
#define MATE_IS_APPBAR (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_APPBAR))
Definition at line 42 of file mate-appbar.h.
MATE_IS_APPBAR_CLASS
#define MATE_IS_APPBAR_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_APPBAR))
Definition at line 43 of file mate-appbar.h.
MATE_TYPE_APPBAR
#define MATE_TYPE_APPBAR (mate_appbar_get_type ())
Definition at line 39 of file mate-appbar.h.
Typedef Documentation
MateAppBar
typedef struct _MateAppBar MateAppBar
Definition at line 50 of file mate-appbar.h.
MateAppBarClass
typedef struct _MateAppBarClass MateAppBarClass
Definition at line 52 of file mate-appbar.h.
MateAppBarMsg
typedef struct _MateAppBarMsg MateAppBarMsg
Definition at line 53 of file mate-appbar.h.
MateAppBarPrivate
typedef struct _MateAppBarPrivate MateAppBarPrivate
Definition at line 51 of file mate-appbar.h.
Function Documentation
mate_appbar_clear_prompt()
void mate_appbar_clear_prompt (MateAppBar * appbar)
mate_appbar_clear_prompt @appbar: A MateAppBar instance.
Description: Remove any prompt from the status message bar.
Definition at line 283 of file mate-appbar.c.
References _MateAppBar::_priv, CLEAR_PROMPT, mate_appbar_refresh(), and NULL.
Referenced by mate_appbar_set_prompt().
mate_appbar_clear_stack()
void mate_appbar_clear_stack (MateAppBar * appbar)
mate_appbar_clear_stack @appbar: A MateAppBar instance.
Description: Remove all status messages from @appbar, and display default status message (if present).
Definition at line 473 of file mate-appbar.c.
References _MateAppBar::_priv, mate_appbar_refresh(), MATE_IS_APPBAR, and NULL.
mate_appbar_get_progress()
GtkProgressBar * mate_appbar_get_progress (MateAppBar * appbar)
mate_appbar_get_progress @appbar: A MateAppBar instance.
Description: Retrieves the progress bar widget for further manipulation.
Returns: A #GtkProgressBar widget which is @appbar's progress bar, or NULL if @appbar has no progress bar.
Definition at line 517 of file mate-appbar.c.
References _MateAppBar::_priv, MATE_IS_APPBAR, and NULL.
mate_appbar_get_response()
gchar * mate_appbar_get_response (MateAppBar * appbar)
mate_appbar_get_response @appbar: A MateAppBar instance.
Description: Get the response to the prompt, if any.
Returns: Text from @appbar entry widget, as entered by user. This string should be freed by the caller (using gfree()) when no longer required.
Definition at line 313 of file mate-appbar.c.
References _MateAppBar::_priv, and NULL.
mate_appbar_get_status()
GtkWidget * mate_appbar_get_status (MateAppBar * appbar)
mate_appbar_get_status @appbar: A MateAppBar instance.
Description: Retrieves the statusbar widget.
Returns: A pointer to the statusbar widget.
Definition at line 537 of file mate-appbar.c.
References _MateAppBar::_priv, MATE_IS_APPBAR, and NULL.
mate_appbar_get_type()
GType mate_appbar_get_type (void)
mate_appbar_new()
GtkWidget * mate_appbar_new (gboolean has_progress, gboolean has_status, MatePreferencesType interactivity)
mate_appbar_new @has_progress: TRUE if appbar needs progress bar widget, FALSE if not. @has_status: TRUE if appbar needs status bar widget, FALSE if not. @interactivity: Level of user activity required.
Description: Create a new MATE application status bar. If @has_progress is TRUE, a small progress bar widget will be created, and placed on the left side of the appbar. If @has_status is TRUE, a status bar, possibly an editable one, is created.
The @interactivity parameter determines whether the appbar is an interactive "minibuffer" or just a status bar. If it is set to MATE_PREFERENCES_NEVER, it is never interactive. If it is set to MATE_PREFERENCES_USER we respect user preferences from ui-properties. If it's MATE_PREFERENCES_ALWAYS we are interactive whether the user likes it or not. Basically, if your app supports both interactive and not (for example, if you use the mate-app-util interfaces), you should use MATE_PREFERENCES_USER. Otherwise, use the setting you support. Please note that "interactive" mode is not functional now; GtkEntry is inadequate and so a custom widget will be written eventually.
Returns: Pointer to new MateAppBar widget.
Definition at line 230 of file mate-appbar.c.
References MATE_TYPE_APPBAR, and NULL.
mate_appbar_pop()
void mate_appbar_pop (MateAppBar * appbar)
mate_appbar_pop @appbar: A MateAppBar instance.
Description: Remove current status message, and display previous status message, if any. It is fine to call this with an empty stack.
Definition at line 453 of file mate-appbar.c.
References _MateAppBar::_priv, mate_appbar_refresh(), MATE_IS_APPBAR, and NULL.
mate_appbar_push()
void mate_appbar_push (MateAppBar * appbar, const gchar * status)
mate_appbar_push @appbar: A MateAppBar instance. @status: Text of status message.
Description: Push a new status message onto the status bar stack and display it.
Definition at line 431 of file mate-appbar.c.
References _MateAppBar::_priv, mate_appbar_refresh(), MATE_IS_APPBAR, and NULL.
mate_appbar_refresh()
void mate_appbar_refresh (MateAppBar * appbar)
mate_appbar_refresh @appbar: A MateAppBar instance.
Description: Refresh the status message bar by redrawing the item on the top of the stack, or the default value if the stack is empty.. Useful to force the message from a previous call to mate_appbar_set_status() to disappear.
Definition at line 336 of file mate-appbar.c.
References _MateAppBar::_priv, FALSE, mate_appbar_set_status(), MATE_IS_APPBAR, NULL, and TRUE.
Referenced by mate_appbar_clear_prompt(), mate_appbar_clear_stack(), mate_appbar_pop(), mate_appbar_push(), mate_appbar_set_default(), and mate_appbar_set_prompt().
mate_appbar_set_default()
void mate_appbar_set_default (MateAppBar * appbar, const gchar * default_status)
mate_appbar_set_default @appbar: A MateAppBar instance. @default_status: Text for status label.
Description: What to show when showing nothing else is on the stack; defaults to the empty string.
Definition at line 407 of file mate-appbar.c.
References _MateAppBar::_priv, mate_appbar_refresh(), MATE_IS_APPBAR, and NULL.
mate_appbar_set_progress_percentage()
void mate_appbar_set_progress_percentage (MateAppBar * appbar, gfloat percentage)
mate_appbar_set_progress_percentage @appbar: A MateAppBar instance. @percentage: Percentage to which progress bar should be set.
Description: Sets progress bar to @percentage.
Definition at line 494 of file mate-appbar.c.
References _MateAppBar::_priv, MATE_IS_APPBAR, and NULL.
Referenced by mate_app_progress_done(), and mate_app_set_progress().
mate_appbar_set_prompt()
void mate_appbar_set_prompt (MateAppBar * appbar, const gchar * prompt, gboolean modal)
mate_appbar_set_prompt @appbar: A MateAppBar instance. @prompt: Text of the prompt message. @modal: If TRUE, grabs input.
Description: Put a prompt in the appbar and wait for a response. When the user responds or cancels, a 'user_response' signal is emitted.
Definition at line 253 of file mate-appbar.c.
References _MateAppBar::_priv, mate_appbar_clear_prompt(), mate_appbar_refresh(), and NULL.
mate_appbar_set_status()
void mate_appbar_set_status (MateAppBar * appbar, const gchar * status)
mate_appbar_set_status @appbar: A MateAppBar instance. @status: Text to which status label will be set.
Description: Sets the status label without changing widget state; next call to mate_appbar_set_status() or mate_appbar_push() will destroy this permanently.
Definition at line 382 of file mate-appbar.c.
References _MateAppBar::_priv, MATE_IS_APPBAR, and NULL.
Referenced by mate_app_flash(), and mate_appbar_refresh().