MATE Desktop Environment: matemixer-switch-option.h File Reference
matemixer-switch-option.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer-types.h>
Classes
struct _MateMixerSwitchOption
struct _MateMixerSwitchOptionClass
Macros
#define MATE_MIXER_TYPE_SWITCH_OPTION (mate_mixer_switch_option_get_type ())
#define MATE_MIXER_SWITCH_OPTION(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MATE_MIXER_TYPE_SWITCH_OPTION, MateMixerSwitchOption))
#define MATE_MIXER_IS_SWITCH_OPTION(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MATE_MIXER_TYPE_SWITCH_OPTION))
#define MATE_MIXER_SWITCH_OPTION_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MATE_MIXER_TYPE_SWITCH_OPTION, MateMixerSwitchOptionClass))
#define MATE_MIXER_IS_SWITCH_OPTION_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MATE_MIXER_TYPE_SWITCH_OPTION))
#define MATE_MIXER_SWITCH_OPTION_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MATE_MIXER_TYPE_SWITCH_OPTION, MateMixerSwitchOptionClass))
Typedefs
typedef struct _MateMixerSwitchOptionClass MateMixerSwitchOptionClass
typedef struct _MateMixerSwitchOptionPrivate MateMixerSwitchOptionPrivate
Functions
GType mate_mixer_switch_option_get_type (void)
const gchar * mate_mixer_switch_option_get_name (MateMixerSwitchOption *option)
const gchar * mate_mixer_switch_option_get_label (MateMixerSwitchOption *option)
const gchar * mate_mixer_switch_option_get_icon (MateMixerSwitchOption *option)
Macro Definition Documentation
MATE_MIXER_IS_SWITCH_OPTION
#define MATE_MIXER_IS_SWITCH_OPTION (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MATE_MIXER_TYPE_SWITCH_OPTION))
Definition at line 32 of file matemixer-switch-option.h.
MATE_MIXER_IS_SWITCH_OPTION_CLASS
#define MATE_MIXER_IS_SWITCH_OPTION_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), MATE_MIXER_TYPE_SWITCH_OPTION))
Definition at line 36 of file matemixer-switch-option.h.
MATE_MIXER_SWITCH_OPTION
#define MATE_MIXER_SWITCH_OPTION (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MATE_MIXER_TYPE_SWITCH_OPTION, MateMixerSwitchOption))
Definition at line 30 of file matemixer-switch-option.h.
MATE_MIXER_SWITCH_OPTION_CLASS
#define MATE_MIXER_SWITCH_OPTION_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), MATE_MIXER_TYPE_SWITCH_OPTION, MateMixerSwitchOptionClass))
Definition at line 34 of file matemixer-switch-option.h.
MATE_MIXER_SWITCH_OPTION_GET_CLASS
#define MATE_MIXER_SWITCH_OPTION_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), MATE_MIXER_TYPE_SWITCH_OPTION, MateMixerSwitchOptionClass))
Definition at line 38 of file matemixer-switch-option.h.
MATE_MIXER_TYPE_SWITCH_OPTION
#define MATE_MIXER_TYPE_SWITCH_OPTION (mate_mixer_switch_option_get_type ())
Definition at line 28 of file matemixer-switch-option.h.
Typedef Documentation
MateMixerSwitchOptionClass
typedef struct _MateMixerSwitchOptionClass MateMixerSwitchOptionClass
Definition at line 41 of file matemixer-switch-option.h.
MateMixerSwitchOptionPrivate
typedef struct _MateMixerSwitchOptionPrivate MateMixerSwitchOptionPrivate
Definition at line 42 of file matemixer-switch-option.h.
Function Documentation
mate_mixer_switch_option_get_icon()
const gchar * mate_mixer_switch_option_get_icon (MateMixerSwitchOption * option)
mate_mixer_switch_option_get_icon: @option: a MateMixerSwitchOption
Gets the XDG icon name of the switch option.
Returns: the icon name or NULL.
Definition at line 240 of file matemixer-switch-option.c.
References MATE_MIXER_IS_SWITCH_OPTION, NULL, and option.
Referenced by pulse_sink_new(), and pulse_source_new().
mate_mixer_switch_option_get_label()
const gchar * mate_mixer_switch_option_get_label (MateMixerSwitchOption * option)
mate_mixer_switch_option_get_label: @option: a MateMixerSwitchOption
Gets the label of the switch option. This is a potentially translated string that should be presented to users in the user interface.
Returns: the label of the switch option.
Definition at line 224 of file matemixer-switch-option.c.
References MATE_MIXER_IS_SWITCH_OPTION, NULL, and option.
mate_mixer_switch_option_get_name()
const gchar * mate_mixer_switch_option_get_name (MateMixerSwitchOption * option)
mate_mixer_switch_option_get_name: @option: a MateMixerSwitchOption
Gets the name of the switch option. The name serves as a unique identifier and in most cases it is not in a user-readable form.
The returned name is guaranteed to be unique across all the switch options of a particular MateMixerSwitch and may be used to get the MateMixerSwitchOption using mate_mixer_switch_get_option().
Returns: the name of the switch option.
Definition at line 207 of file matemixer-switch-option.c.
References MATE_MIXER_IS_SWITCH_OPTION, NULL, and option.
Referenced by oss_switch_load(), pulse_device_profile_get_name(), and pulse_port_get_name().
mate_mixer_switch_option_get_type()
GType mate_mixer_switch_option_get_type (void)