MATE Desktop Environment: mate-dialog.c File Reference
mate-dialog.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include "mate-dialog.h"
#include <libmate/mate-util.h>
#include <libmate/mate-config.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include "mate-uidefs.h"
#include "mate-dialog-util.h"
#include "mate-marshal.h"
Macros
#define MATE_STOCK_BUTTON_PADDING 2
Enumerations
enum { CLICKED , CLOSE , LAST_SIGNAL }
Functions
GType mate_dialog_get_type (void)
void mate_dialog_construct (MateDialog *dialog, const gchar *title, va_list ap)
void mate_dialog_constructv (MateDialog *dialog, const gchar *title, const gchar **buttons)
GtkWidget * mate_dialog_new (const gchar *title,...)
GtkWidget * mate_dialog_newv (const gchar *title, const gchar **buttons)
void mate_dialog_set_parent (MateDialog *dialog, GtkWindow *parent)
void mate_dialog_append_buttons (MateDialog *dialog, const gchar *first,...)
void mate_dialog_append_button (MateDialog *dialog, const gchar *button_name)
void mate_dialog_append_button_with_pixmap (MateDialog *dialog, const gchar *button_name, const gchar *pixmap_name)
void mate_dialog_append_buttonsv (MateDialog *dialog, const gchar **buttons)
void mate_dialog_append_buttons_with_pixmaps (MateDialog *dialog, const gchar **names, const gchar **pixmaps)
gint mate_dialog_run (MateDialog *dialog)
gint mate_dialog_run_and_close (MateDialog *dialog)
void mate_dialog_set_default (MateDialog *dialog, gint button)
void mate_dialog_grab_focus (MateDialog *dialog, gint button)
void mate_dialog_set_close (MateDialog *dialog, gboolean click_closes)
void mate_dialog_close_hides (MateDialog *dialog, gboolean just_hide)
void mate_dialog_set_sensitive (MateDialog *dialog, gint button, gboolean setting)
void mate_dialog_button_connect (MateDialog *dialog, gint button, GCallback callback, gpointer data)
void mate_dialog_button_connect_object (MateDialog *dialog, gint button, GCallback callback, GtkObject *obj)
void mate_dialog_set_accelerator (MateDialog *dialog, gint button, const guchar accelerator_key, guint8 accelerator_mods)
void mate_dialog_editable_enters (MateDialog *dialog, GtkEditable *editable)
void mate_dialog_close (MateDialog *dialog)
Macro Definition Documentation
MATE_STOCK_BUTTON_PADDING
#define MATE_STOCK_BUTTON_PADDING 2
Definition at line 421 of file mate-dialog.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CLICKED
CLOSE
LAST_SIGNAL
Definition at line 39 of file mate-dialog.c.
Function Documentation
mate_dialog_append_button()
void mate_dialog_append_button (MateDialog * dialog, const gchar * button_name)
mate_dialog_append_button: @dialog: MateDialog to add button to. @button_name: Button to add.
Add a button to a dialog after its initial construction. This function is mostly for internal library use. You should use mate_dialog_new() instead. See that function for a description of the button argument.
Definition at line 396 of file mate-dialog.c.
References _MateDialog::action_area, _MateDialog::buttons, MATE_IS_DIALOG, NULL, and TRUE.
Referenced by mate_dialog_append_buttons(), mate_dialog_append_buttonsv(), mate_dialog_construct(), mate_dialog_constructv(), and mate_message_box_new().
mate_dialog_append_button_with_pixmap()
void mate_dialog_append_button_with_pixmap (MateDialog * dialog, const gchar * button_name, const gchar * pixmap_name)
mate_dialog_append_button_with_pixmap: @dialog: MateDialog to add the button to. @button_name: Name of the button, or stock button #define. @pixmap_name: Stock pixmap name.
Add a pixmap button to a dialog. mate_dialog_new() does not permit custom buttons with pixmaps, so if you want one of those you need to use this function.
Definition at line 475 of file mate-dialog.c.
References _MateDialog::action_area, _MateDialog::buttons, MATE_IS_DIALOG, NULL, and TRUE.
Referenced by mate_dialog_append_buttons_with_pixmaps().
mate_dialog_append_buttons()
void mate_dialog_append_buttons (MateDialog * dialog, const gchar * first, ...)
mate_dialog_append_buttons: Add buttons to a dialog after its initial construction. @dialog: MateDialog to add buttons to. @first: First button to add. ...: varargs list of additional buttons, NULL-terminated.
This function is mostly for internal library use. You should use mate_dialog_new() instead. See that function for a description of the button arguments.
Definition at line 366 of file mate-dialog.c.
References mate_dialog_append_button(), MATE_IS_DIALOG, and NULL.
mate_dialog_append_buttons_with_pixmaps()
void mate_dialog_append_buttons_with_pixmaps (MateDialog * dialog, const gchar ** names, const gchar ** pixmaps)
mate_dialog_append_buttons_with_pixmaps: Like mate_dialog_append_button_with_pixmap(), but allows multiple buttons. @dialog: MateDialog to append to. @names: NULL-terminated vector of button names. @pixmaps: NULL-terminated vector of pixmap names.
Simply calls mate_dialog_append_button_with_pixmap() repeatedly.
Definition at line 538 of file mate-dialog.c.
References mate_dialog_append_button_with_pixmap(), MATE_IS_DIALOG, and NULL.
mate_dialog_append_buttonsv()
void mate_dialog_append_buttonsv (MateDialog * dialog, const gchar ** buttons)
mate_dialog_append_buttonsv: Like mate_dialog_append_buttons(), but with a vector arg instead of a varargs list. @dialog: MateDialog to append to. @buttons: NULL-terminated vector of buttons to append.
For internal use, language bindings, etc. Use mate_dialog_new() instead.
Definition at line 517 of file mate-dialog.c.
References buttons, mate_dialog_append_button(), MATE_IS_DIALOG, and NULL.
mate_dialog_button_connect()
void mate_dialog_button_connect (MateDialog * dialog, gint button, GCallback callback, gpointer data)
mate_dialog_button_connect: Connect a callback to one of the button's "clicked" signals. @dialog: MateDialog to affect. @button: Button number. @callback: A standard Gtk callback. @data: Callback data.
Simply g_signal_connect() to the "clicked" signal of the specified button.
Definition at line 861 of file mate-dialog.c.
References _MateDialog::buttons, data, MATE_IS_DIALOG, and NULL.
mate_dialog_button_connect_object()
void mate_dialog_button_connect_object (MateDialog * dialog, gint button, GCallback callback, GtkObject * obj)
mate_dialog_button_connect_object: g_signal_connect_swapped() to a button. @dialog: MateDialog to affect. @button: Button to connect to. @callback: Callback. @obj: As for g_signal_connect_swapped().
g_signal_connect_swapped() to the "clicked" signal of the given button.
Definition at line 894 of file mate-dialog.c.
References _MateDialog::buttons, MATE_IS_DIALOG, and NULL.
mate_dialog_close()
void mate_dialog_close (MateDialog * dialog)
mate_dialog_close: Close (hide or destroy) the dialog. @dialog: MateDialog to close.
See also mate_dialog_close_hides(). This function emits the "close" signal, which either hides or destroys the dialog (destroy by default). If you connect to the "close" signal, and your callback returns TRUE, the hide or destroy will be blocked. You can do this to avoid closing the dialog if the user gives invalid input, for example.
Using mate_dialog_close() in place of gtk_widget_hide() or gtk_widget_destroy() allows you to easily catch all sources of dialog closure, including delete_event and button clicks, and handle them in a central location.
Definition at line 1102 of file mate-dialog.c.
References CLOSE, FALSE, MATE_IS_DIALOG, and NULL.
Referenced by mate_app_progress_done().
mate_dialog_close_hides()
void mate_dialog_close_hides (MateDialog * dialog, gboolean just_hide)
mate_dialog_close_hides: mate_dialog_close() can destroy or hide the dialog; toggle this behavior. @dialog: MateDialog to affect. @just_hide: If TRUE, mate_dialog_close() calls gtk_widget_hide() instead of gtk_widget_destroy().
Some dialogs are expensive to create, so you want to keep them around and just gtk_widget_show() them when they are opened, and gtk_widget_hide() them when they're closed. Other dialogs are expensive to keep around, so you want to gtk_widget_destroy() them when they're closed. It's a judgment call you will need to make for each dialog.
Definition at line 812 of file mate-dialog.c.
References _MateDialog::just_hide, MATE_IS_DIALOG, and NULL.
mate_dialog_construct()
void mate_dialog_construct (MateDialog * dialog, const gchar * title, va_list ap)
mate_dialog_construct: Functionality of mate_dialog_new() for language wrappers. @dialog: Dialog to construct. @title: Title of the dialog. @ap: va_list of buttons, NULL-terminated.
See mate_dialog_new().
Definition at line 206 of file mate-dialog.c.
References mate_dialog_append_button(), NULL, and TRUE.
Referenced by mate_dialog_new().
mate_dialog_constructv()
void mate_dialog_constructv (MateDialog * dialog, const gchar * title, const gchar ** buttons)
mate_dialog_constructv: Functionality of mate_dialog_new(), for language wrappers. @dialog: Dialog to construct. @title: Title of the dialog. @buttons: NULL-terminated array of buttons.
See mate_dialog_new().
Definition at line 239 of file mate-dialog.c.
References buttons, mate_dialog_append_button(), NULL, and TRUE.
Referenced by mate_dialog_newv(), and mate_message_box_construct().
mate_dialog_editable_enters()
void mate_dialog_editable_enters (MateDialog * dialog, GtkEditable * editable)
mate_dialog_editable_enters: Make the "activate" signal of an editable click the default dialog button. @dialog: MateDialog to affect. @editable: Editable to affect.
Normally if there's an editable widget (such as #GtkEntry) in your dialog, pressing Enter will activate the editable rather than the default dialog button. However, in most cases, the user expects to type something in and then press enter to close the dialog. This function enables that behavior.
Definition at line 968 of file mate-dialog.c.
References MATE_IS_DIALOG, and NULL.
mate_dialog_get_type()
GType mate_dialog_get_type (void)
Definition at line 63 of file mate-dialog.c.
References NULL.
mate_dialog_grab_focus()
void mate_dialog_grab_focus (MateDialog * dialog, gint button)
mate_dialog_grab_focus: Makes a button grab the focus. T @dialog: MateDialog to affect. @button: Number of the default button.
The button @button will grab the focus. Use this for dialogs Where only buttons are displayed and you want to change the default button.
Definition at line 759 of file mate-dialog.c.
References _MateDialog::buttons, MATE_IS_DIALOG, and NULL.
mate_dialog_new()
GtkWidget * mate_dialog_new (const gchar * title, ...)
mate_dialog_new: Create a new MateDialog. @title: The title of the dialog; appears in window titlebar. ...: NULL-terminated varargs list of button names or MATE_STOCK_BUTTON_* defines.
Creates a new MateDialog, with the given title, and any button names in the arg list. Buttons can be simple names, such as _("My Button"), or mate-stock defines such as MATE_STOCK_BUTTON_OK, etc. The last argument should be NULL to terminate the list.
Buttons passed to this function are numbered from left to right, starting with 0. So the first button in the arglist is button 0, then button 1, etc. These numbers are used throughout the MateDialog API.
Return value: The new MateDialog.
Definition at line 286 of file mate-dialog.c.
References mate_dialog_construct(), MATE_TYPE_DIALOG, and NULL.
mate_dialog_newv()
GtkWidget * mate_dialog_newv (const gchar * title, const gchar ** buttons)
mate_dialog_newv: Create a new MateDialog. @title: Title of the dialog. @buttons: NULL-terminated vector of buttons names.
See mate_dialog_new(), this function is identical but does not use varargs.
Return value: The new MateDialog.
Definition at line 313 of file mate-dialog.c.
References buttons, mate_dialog_constructv(), MATE_TYPE_DIALOG, and NULL.
mate_dialog_run()
gint mate_dialog_run (MateDialog * dialog)
mate_dialog_run: Make the dialog modal and block waiting for user response. @dialog: MateDialog to use.
Blocks until the user clicks a button, or closes the dialog with the window manager's close decoration (or by pressing Escape).
You need to set up the dialog to do the right thing when a button is clicked or delete_event is received; you must consider both of those possibilities so that you know the status of the dialog when mate_dialog_run() returns. A common mistake is to forget about Escape and the window manager close decoration; by default, these call mate_dialog_close(), which by default destroys the dialog. If your button clicks do not destroy the dialog, you don't know whether the dialog is destroyed when mate_dialog_run() returns. This is bad.
So you should either close the dialog on button clicks as well, or change the mate_dialog_close() behavior to hide instead of destroy. You can do this with mate_dialog_close_hides().
Return value: If a button was pressed, the button number is returned. If not, -1 is returned.
Definition at line 698 of file mate-dialog.c.
References FALSE.
mate_dialog_run_and_close()
gint mate_dialog_run_and_close (MateDialog * dialog)
mate_dialog_run_and_close: Like mate_dialog_run(), but force-closes the dialog after the run, iff the dialog was not closed already. @dialog: MateDialog to use.
See mate_dialog_run(). The only difference is that this function calls mate_dialog_close() before returning, if the dialog was not already closed.
Return value: If a button was pressed, the button number. Otherwise -1.
Definition at line 713 of file mate-dialog.c.
References TRUE.
mate_dialog_set_accelerator()
void mate_dialog_set_accelerator (MateDialog * dialog, gint button, const guchar accelerator_key, guint8 accelerator_mods)
mate_dialog_set_accelerator: @dialog: MateDialog to affect. @button: Button number. @accelerator_key: Key for the accelerator. @accelerator_mods: Modifier.
Set an accelerator key for a button.
Definition at line 927 of file mate-dialog.c.
References _MateDialog::accelerators, _MateDialog::buttons, MATE_IS_DIALOG, and NULL.
mate_dialog_set_close()
void mate_dialog_set_close (MateDialog * dialog, gboolean click_closes)
mate_dialog_set_close: Whether to call mate_dialog_close() when a button is clicked. @dialog: MateDialog to affect. @click_closes: TRUE if clicking any button should call mate_dialog_close().
This is a convenience function so you don't have to connect callbacks to each button just to close the dialog. By default, MateDialog has this parameter set the FALSE and it will not close on any click. (This was a design error.) However, almost all the MateDialog subclasses, such as MateMessageBox and MatePropertyBox, have this parameter set to TRUE by default.
Definition at line 791 of file mate-dialog.c.
References _MateDialog::click_closes, MATE_IS_DIALOG, and NULL.
Referenced by mate_message_box_construct().
mate_dialog_set_default()
void mate_dialog_set_default (MateDialog * dialog, gint button)
mate_dialog_set_default: Set the default button for the dialog. The Enter key activates the default button. @dialog: MateDialog to affect. @button: Number of the default button.
The default button will be activated if the user just presses return. Usually you should make the least-destructive button the default. Otherwise, the most commonly-used button.
Definition at line 729 of file mate-dialog.c.
References _MateDialog::buttons, MATE_IS_DIALOG, and NULL.
mate_dialog_set_parent()
void mate_dialog_set_parent (MateDialog * dialog, GtkWindow * parent)
mate_dialog_set_parent: Set the logical parent window of a MateDialog. @dialog: MateDialog to set the parent of. @parent: Parent #GtkWindow.
Dialogs have "parents," usually the main application window which spawned them. This function will let the window manager know about the parent-child relationship. Usually this means the dialog must stay on top of the parent, and will be minimized when the parent is. Mate also allows users to request dialog placement above the parent window (vs. at the mouse position, or at a default window manger location).
Definition at line 338 of file mate-dialog.c.
References MATE_IS_DIALOG, and NULL.
mate_dialog_set_sensitive()
void mate_dialog_set_sensitive (MateDialog * dialog, gint button, gboolean setting)
mate_dialog_set_sensitive: Set the sensitivity of a button. @dialog: MateDialog to affect. @button: Which button to affect. @setting: TRUE means it's sensitive.
Calls gtk_widget_set_sensitive() on the specified button number.
Definition at line 830 of file mate-dialog.c.
References _MateDialog::buttons, MATE_IS_DIALOG, and NULL.