MATE Desktop Environment: mate-password-dialog.h File Reference
mate-password-dialog.h File Reference
#include <gtk/gtk.h>
Classes
struct _MatePasswordDialog
struct _MatePasswordDialogClass
Macros
#define MATE_TYPE_PASSWORD_DIALOG (mate_password_dialog_get_type ())
#define MATE_PASSWORD_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_PASSWORD_DIALOG, MatePasswordDialog))
#define MATE_PASSWORD_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_PASSWORD_DIALOG, MatePasswordDialogClass))
#define MATE_IS_PASSWORD_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_PASSWORD_DIALOG))
#define MATE_IS_PASSWORD_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_PASSWORD_DIALOG))
Typedefs
typedef struct _MatePasswordDialog MatePasswordDialog
typedef struct _MatePasswordDialogClass MatePasswordDialogClass
typedef struct _MatePasswordDialogDetails MatePasswordDialogDetails
typedef gdouble(* MatePasswordDialogQualityFunc) (MatePasswordDialog *password_dialog, const char *password, gpointer user_data)
Enumerations
enum MatePasswordDialogRemember { MATE_PASSWORD_DIALOG_REMEMBER_NOTHING , MATE_PASSWORD_DIALOG_REMEMBER_SESSION , MATE_PASSWORD_DIALOG_REMEMBER_FOREVER }
Functions
GType mate_password_dialog_get_type (void)
GtkWidget * mate_password_dialog_new (const char *dialog_title, const char *message, const char *username, const char *password, gboolean readonly_username)
gboolean mate_password_dialog_run_and_block (MatePasswordDialog *password_dialog)
void mate_password_dialog_set_show_username (MatePasswordDialog *password_dialog, gboolean show)
void mate_password_dialog_set_show_domain (MatePasswordDialog *password_dialog, gboolean show)
void mate_password_dialog_set_show_password (MatePasswordDialog *password_dialog, gboolean show)
void mate_password_dialog_set_show_new_password (MatePasswordDialog *password_dialog, gboolean show)
void mate_password_dialog_set_show_new_password_quality (MatePasswordDialog *password_dialog, gboolean show)
void mate_password_dialog_set_username (MatePasswordDialog *password_dialog, const char *username)
void mate_password_dialog_set_domain (MatePasswordDialog *password_dialog, const char *domain)
void mate_password_dialog_set_password (MatePasswordDialog *password_dialog, const char *password)
void mate_password_dialog_set_new_password (MatePasswordDialog *password_dialog, const char *password)
void mate_password_dialog_set_password_quality_func (MatePasswordDialog *password_dialog, MatePasswordDialogQualityFunc func, gpointer data, GDestroyNotify dnotify)
void mate_password_dialog_set_readonly_username (MatePasswordDialog *password_dialog, gboolean readonly)
void mate_password_dialog_set_readonly_domain (MatePasswordDialog *password_dialog, gboolean readonly)
void mate_password_dialog_set_show_remember (MatePasswordDialog *password_dialog, gboolean show_remember)
void mate_password_dialog_set_remember (MatePasswordDialog *password_dialog, MatePasswordDialogRemember remember)
MatePasswordDialogRemember mate_password_dialog_get_remember (MatePasswordDialog *password_dialog)
void mate_password_dialog_set_show_userpass_buttons (MatePasswordDialog *password_dialog, gboolean show_userpass_buttons)
char * mate_password_dialog_get_username (MatePasswordDialog *password_dialog)
char * mate_password_dialog_get_domain (MatePasswordDialog *password_dialog)
char * mate_password_dialog_get_password (MatePasswordDialog *password_dialog)
char * mate_password_dialog_get_new_password (MatePasswordDialog *password_dialog)
gboolean mate_password_dialog_anon_selected (MatePasswordDialog *password_dialog)
Macro Definition Documentation
MATE_IS_PASSWORD_DIALOG
#define MATE_IS_PASSWORD_DIALOG (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_PASSWORD_DIALOG))
Definition at line 37 of file mate-password-dialog.h.
MATE_IS_PASSWORD_DIALOG_CLASS
#define MATE_IS_PASSWORD_DIALOG_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_PASSWORD_DIALOG))
Definition at line 38 of file mate-password-dialog.h.
MATE_PASSWORD_DIALOG
#define MATE_PASSWORD_DIALOG (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_PASSWORD_DIALOG, MatePasswordDialog))
Definition at line 35 of file mate-password-dialog.h.
MATE_PASSWORD_DIALOG_CLASS
#define MATE_PASSWORD_DIALOG_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_PASSWORD_DIALOG, MatePasswordDialogClass))
Definition at line 36 of file mate-password-dialog.h.
MATE_TYPE_PASSWORD_DIALOG
#define MATE_TYPE_PASSWORD_DIALOG (mate_password_dialog_get_type ())
Definition at line 34 of file mate-password-dialog.h.
Typedef Documentation
MatePasswordDialog
typedef struct _MatePasswordDialog MatePasswordDialog
Definition at line 40 of file mate-password-dialog.h.
MatePasswordDialogClass
typedef struct _MatePasswordDialogClass MatePasswordDialogClass
Definition at line 41 of file mate-password-dialog.h.
MatePasswordDialogDetails
typedef struct _MatePasswordDialogDetails MatePasswordDialogDetails
Definition at line 42 of file mate-password-dialog.h.
MatePasswordDialogQualityFunc
typedef gdouble(* MatePasswordDialogQualityFunc) (MatePasswordDialog *password_dialog, const char *password, gpointer user_data)
Definition at line 62 of file mate-password-dialog.h.
Enumeration Type Documentation
MatePasswordDialogRemember
enum MatePasswordDialogRemember
Enumerator
MATE_PASSWORD_DIALOG_REMEMBER_NOTHING
MATE_PASSWORD_DIALOG_REMEMBER_SESSION
MATE_PASSWORD_DIALOG_REMEMBER_FOREVER
Definition at line 56 of file mate-password-dialog.h.
Function Documentation
mate_password_dialog_anon_selected()
gboolean mate_password_dialog_anon_selected (MatePasswordDialog * password_dialog)
mate_password_dialog_anon_selected: @password_dialog: A MatePasswordDialog
Description: Checks whether anonymous support is set to TRUE and the radio button for connecting as anonymous user is active.
Returns: TRUE if anonymous support is set and the radio button is active, FALSE otherwise.
Definition at line 1551 of file mate-password-dialog.c.
References _MatePasswordDialog::details, FALSE, and MATE_IS_PASSWORD_DIALOG.
mate_password_dialog_get_domain()
char * mate_password_dialog_get_domain (MatePasswordDialog * password_dialog)
mate_password_dialog_get_domain: @password_dialog: A MatePasswordDialog
Description: Gets the domain name from the password dialog.
Returns: The domain name, a char*.
Since: 2.4
Definition at line 1426 of file mate-password-dialog.c.
References _MatePasswordDialog::details, MATE_IS_PASSWORD_DIALOG, and NULL.
mate_password_dialog_get_new_password()
char * mate_password_dialog_get_new_password (MatePasswordDialog * password_dialog)
mate_password_dialog_get_new_password: @password_dialog: A MatePasswordDialog
Description: Gets the new password from the password dialog.
Returns: The password, or NULL if the entries in the new password field and the confirmation field don't match.
Since: 2.18
Definition at line 1471 of file mate-password-dialog.c.
References _MatePasswordDialog::details, MATE_IS_PASSWORD_DIALOG, and NULL.
mate_password_dialog_get_password()
char * mate_password_dialog_get_password (MatePasswordDialog * password_dialog)
mate_password_dialog_get_password: @password_dialog: A MatePasswordDialog
Description: Gets the password from the password dialog.
Returns: The password, a char*.
Since: 2.4
Definition at line 1448 of file mate-password-dialog.c.
References _MatePasswordDialog::details, MATE_IS_PASSWORD_DIALOG, and NULL.
mate_password_dialog_get_remember()
MatePasswordDialogRemember mate_password_dialog_get_remember (MatePasswordDialog * password_dialog)
mate_password_dialog_get_remember: @password_dialog: A MatePasswordDialog
Description: Gets the state of the check buttons to remember password for the session and save password to keyring.
Returns: a MatePasswordDialogRemember, which indicates whether to remember the password for the session or forever.
Since: 2.6
Definition at line 1637 of file mate-password-dialog.c.
References _MatePasswordDialog::details, MATE_IS_PASSWORD_DIALOG, MATE_PASSWORD_DIALOG_REMEMBER_FOREVER, MATE_PASSWORD_DIALOG_REMEMBER_NOTHING, and MATE_PASSWORD_DIALOG_REMEMBER_SESSION.
Referenced by mate_password_dialog_set_remember().
mate_password_dialog_get_type()
GType mate_password_dialog_get_type (void)
mate_password_dialog_get_username()
char * mate_password_dialog_get_username (MatePasswordDialog * password_dialog)
mate_password_dialog_get_username: @password_dialog: A MatePasswordDialog
Description: Gets the username from the password dialog.
Returns: The username, a char*.
Since: 2.4
Definition at line 1404 of file mate-password-dialog.c.
References _MatePasswordDialog::details, MATE_IS_PASSWORD_DIALOG, and NULL.
mate_password_dialog_new()
GtkWidget * mate_password_dialog_new (const char * dialog_title, const char * message, const char * username, const char * password, gboolean readonly_username)
mate_password_dialog_new: @dialog_title: The title of the dialog @message: Message text for the dialog @username: The username to be used in the dialog @password: Password to be used @readonly_username: Boolean value that controls whether the user can edit the username or not
Description: Creates a new password dialog with an optional title, message, username, password etc. The user will be given the option to save the password for this session only or store it permanently in her keyring.
Returns: A new password dialog.
Since: 2.4
Definition at line 987 of file mate-password-dialog.c.
References FALSE, mate_password_dialog_set_password(), mate_password_dialog_set_username(), MATE_TYPE_PASSWORD_DIALOG, message(), NULL, and TRUE.
mate_password_dialog_run_and_block()
gboolean mate_password_dialog_run_and_block (MatePasswordDialog * password_dialog)
mate_password_dialog_run_and_block: @password_dialog: A MatePasswordDialog
Description: Gets the user input from PasswordDialog.
Returns: TRUE if "Connect" button is pressed. FALSE if "Cancel" button is pressed.
Since: 2.4
Definition at line 1028 of file mate-password-dialog.c.
References FALSE, and MATE_IS_PASSWORD_DIALOG.
mate_password_dialog_set_domain()
void mate_password_dialog_set_domain (MatePasswordDialog * password_dialog, const char * domain)
mate_password_dialog_set_domain: @password_dialog: A MatePasswordDialog @domain: The domain that should be set
Description: Sets the domain field in the password dialog to @domain.
Since: 2.4
Definition at line 1162 of file mate-password-dialog.c.
References _MatePasswordDialog::details, MATE_IS_PASSWORD_DIALOG, and NULL.
mate_password_dialog_set_new_password()
void mate_password_dialog_set_new_password (MatePasswordDialog * password_dialog, const char * password)
mate_password_dialog_set_password()
void mate_password_dialog_set_password (MatePasswordDialog * password_dialog, const char * password)
mate_password_dialog_set_password: @password_dialog: A MatePasswordDialog @password: The password that should be set
Description: Sets the password in the password dialog.
Since: 2.4
Definition at line 1076 of file mate-password-dialog.c.
References _MatePasswordDialog::details, and MATE_IS_PASSWORD_DIALOG.
Referenced by mate_password_dialog_new().
mate_password_dialog_set_password_quality_func()
void mate_password_dialog_set_password_quality_func (MatePasswordDialog * password_dialog, MatePasswordDialogQualityFunc func, gpointer data, GDestroyNotify destroy_notify)
mate_password_dialog_set_password_quality_func: @password_dialog: A MatePasswordDialog @func: the new MatePasswordDialogQualityFunc @data: user data to pass to the quality func @destroy_notify:
Description: Sets the function which measures the quality of the new password as it's typed.
Since: 2.18
Definition at line 1127 of file mate-password-dialog.c.
References data, _MatePasswordDialog::details, and MATE_IS_PASSWORD_DIALOG.
mate_password_dialog_set_readonly_domain()
void mate_password_dialog_set_readonly_domain (MatePasswordDialog * password_dialog, gboolean readonly)
mate_password_dialog_set_readonly_domain: @password_dialog: A MatePasswordDialog @readonly : Boolean value that controls whether the user can edit the domain or not
Description: Sets the editable nature of the domain field in the password dialog based on the boolean value @readonly.
Since: 2.6
Definition at line 1372 of file mate-password-dialog.c.
References _MatePasswordDialog::details, FALSE, and MATE_IS_PASSWORD_DIALOG.
mate_password_dialog_set_readonly_username()
void mate_password_dialog_set_readonly_username (MatePasswordDialog * password_dialog, gboolean readonly)
mate_password_dialog_set_readonly_username: @password_dialog: A MatePasswordDialog @readonly : Boolean value that controls whether the user can edit the username or not
Description: Sets the editable nature of the username field in the password dialog based on the boolean value @readonly.
Since: 2.4
Definition at line 1341 of file mate-password-dialog.c.
References _MatePasswordDialog::details, FALSE, and MATE_IS_PASSWORD_DIALOG.
mate_password_dialog_set_remember()
void mate_password_dialog_set_remember (MatePasswordDialog * password_dialog, MatePasswordDialogRemember remember)
mate_password_dialog_set_remember: @password_dialog: A MatePasswordDialog. @remember: A MatePasswordDialogRemember.
Description: Based on the value of MatePasswordDialogRemember, sets the state of the check buttons to remember password for the session and save password to keyring .
Since: 2.6
Definition at line 1607 of file mate-password-dialog.c.
References _MatePasswordDialog::details, MATE_IS_PASSWORD_DIALOG, mate_password_dialog_get_remember(), MATE_PASSWORD_DIALOG_REMEMBER_FOREVER, MATE_PASSWORD_DIALOG_REMEMBER_NOTHING, and TRUE.
mate_password_dialog_set_show_domain()
void mate_password_dialog_set_show_domain (MatePasswordDialog * password_dialog, gboolean show)
mate_password_dialog_set_show_domain: @password_dialog: A MatePasswordDialog @show: Boolean value that controls whether the domain entry has to appear or not.
Description: Shows or hides the domain field in the password dialog based on the value of @show.
Since: 2.6
Definition at line 1219 of file mate-password-dialog.c.
References _MatePasswordDialog::details, FALSE, and MATE_IS_PASSWORD_DIALOG.
mate_password_dialog_set_show_new_password()
void mate_password_dialog_set_show_new_password (MatePasswordDialog * password_dialog, gboolean show)
mate_password_dialog_set_show_new_password: @password_dialog: A MatePasswordDialog @show: Boolean value that controls whether the new password entry has to appear or not.
Description: Shows or hides the new password and new password confirmation fields based on the value of @show.
Since: 2.18
Definition at line 1280 of file mate-password-dialog.c.
References _MatePasswordDialog::details, FALSE, and MATE_IS_PASSWORD_DIALOG.
mate_password_dialog_set_show_new_password_quality()
void mate_password_dialog_set_show_new_password_quality (MatePasswordDialog * password_dialog, gboolean show)
mate_password_dialog_set_show_new_password_quality: @password_dialog: A MatePasswordDialog @show: Boolean value that controls whether the new password quality meter will appear or not.
Description: Shows or hides the new password quality meter.
Since: 2.18
Definition at line 1310 of file mate-password-dialog.c.
References _MatePasswordDialog::details, FALSE, and MATE_IS_PASSWORD_DIALOG.
mate_password_dialog_set_show_password()
void mate_password_dialog_set_show_password (MatePasswordDialog * password_dialog, gboolean show)
mate_password_dialog_set_show_password: @password_dialog: A MatePasswordDialog @show: Boolean value that controls whether the password entry has to appear or not.
Description: Shows or hides the password field in the password dialog based on the value of @show.
Since: 2.6
Definition at line 1249 of file mate-password-dialog.c.
References _MatePasswordDialog::details, FALSE, and MATE_IS_PASSWORD_DIALOG.
mate_password_dialog_set_show_remember()
void mate_password_dialog_set_show_remember (MatePasswordDialog * password_dialog, gboolean show)
mate_password_dialog_set_show_remember: @password_dialog: A MatePasswordDialog @show_remember: Boolean value that controls whether the check buttons for password retention should appear or not.
Description: Shows or hides the check buttons to save password in keyring and remember password for session based on the value of @show_remember.
Since: 2.6
Definition at line 1576 of file mate-password-dialog.c.
References _MatePasswordDialog::details, FALSE, MATE_IS_PASSWORD_DIALOG, and NULL.
mate_password_dialog_set_show_username()
void mate_password_dialog_set_show_username (MatePasswordDialog * password_dialog, gboolean show)
mate_password_dialog_set_show_username: @password_dialog: A MatePasswordDialog @show: Boolean value that controls whether the username entry has to appear or not.
Description: Shows or hides the username entry in the password dialog based on the value of @show.
Since: 2.6
Definition at line 1189 of file mate-password-dialog.c.
References _MatePasswordDialog::details, FALSE, and MATE_IS_PASSWORD_DIALOG.
mate_password_dialog_set_show_userpass_buttons()
void mate_password_dialog_set_show_userpass_buttons (MatePasswordDialog * password_dialog, gboolean show)
mate_password_dialog_set_show_userpass_buttons: @password_dialog: A MatePasswordDialog @show_userpass_buttons: Boolean value that controls whether the radio buttons for connecting anonymously and connecting as user should be shown or not.
Description: Shows the radio buttons for connecting anonymously and connecting as user if @show_userpass_buttons is TRUE. Also makes the 'Username' and 'Password' fields greyed out if the radio button for connecting anonymously is active. If @show_userpass_buttons is FALSE, then these radio buttons are hidden and the 'Username' and 'Password' fields will be made active.
Since: 2.8
Definition at line 1503 of file mate-password-dialog.c.
References _MatePasswordDialog::details, FALSE, MATE_IS_PASSWORD_DIALOG, NULL, and TRUE.
mate_password_dialog_set_username()
void mate_password_dialog_set_username (MatePasswordDialog * password_dialog, const char * username)
mate_password_dialog_set_username: @password_dialog: A MatePasswordDialog @username: The username that should be set
Description: Sets the username in the password dialog.
Since: 2.4
Definition at line 1050 of file mate-password-dialog.c.
References _MatePasswordDialog::details, MATE_IS_PASSWORD_DIALOG, and NULL.
Referenced by mate_password_dialog_new().