MATE Desktop Environment: mate-app.c File Reference
mate-app.c File Reference
#include "config.h"
#include <libmate/mate-macros.h>
#include <string.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <mateconf/mateconf-client.h>
#include <libmate/mate-program.h>
#include <libmate/mate-util.h>
#include <libmate/mate-config.h>
#include <matecomponent/matecomponent-dock.h>
#include "mate-app-helper.h"
#include "mate-uidefs.h"
#include "mate-mateconf-ui.h"
#include "mate-window.h"
#include "mate-window-icon.h"
#include "mate-ui-init.h"
#include "mate-app.h"
Macros
#define MATECOMPONENT_UI_INTERNAL
#define LAYOUT_CONFIG_PATH "Placement/Dock"
Enumerations
enum { PROP_0 , PROP_APP_ID }
Functions
MATE_CLASS_BOILERPLATE (MateApp, mate_app, GtkWindow, GTK_TYPE_WINDOW)
GtkWidget * mate_app_new (const gchar *appname, const gchar *title)
void mate_app_construct (MateApp *app, const gchar *appname, const gchar *title)
void mate_app_set_contents (MateApp *app, GtkWidget *contents)
void mate_app_set_menus (MateApp *app, GtkMenuBar *menubar)
void mate_app_set_statusbar (MateApp *app, GtkWidget *statusbar)
void mate_app_set_statusbar_custom (MateApp *app, GtkWidget *container, GtkWidget *statusbar)
: Name for the dock item that will contain @toolbar
mate_app_add_toolbar: @app: A MateApp widget @toolbar: Toolbar to be added to @app's dock
@behavior: Behavior for the new dock item @placement: Placement for the new dock item @band_num: Number of the band where the dock item should be placed @band_position: Position of the new dock item in band @band_num @offset: Offset from the previous dock item in the band; if there is no previous item, offset from the beginning of the band.
Create a new #MateComponentDockItem widget containing @toolbar, and add it to @app's dock with the specified layout information. Notice that, if automatic layout configuration is enabled, the layout is overridden by the saved configuration, if any.
void mate_app_add_toolbar (MateApp *app, GtkToolbar *toolbar, const gchar *name, MateComponentDockItemBehavior behavior, MateComponentDockPlacement placement, gint band_num, gint band_position, gint offset)
void mate_app_set_toolbar (MateApp *app, GtkToolbar *toolbar)
void mate_app_add_dock_item (MateApp *app, MateComponentDockItem *item, MateComponentDockPlacement placement, gint band_num, gint band_position, gint offset)
: Name for the new dock item.
mate_app_add_docked: @app: A MateApp widget. @widget: Widget to be added to the MateApp.
@behavior: Behavior for the new dock item. @placement: Placement for the new dock item. @band_num: Number of the band where the dock item should be placed. @band_position: Position of the new dock item in band @band_num. @offset: Offset from the previous dock item in the band; if there is no previous item, offset from the beginning of the band.
Add @widget as a dock item according to the specified layout information. Notice that, if automatic layout configuration is enabled, the layout is overridden by the saved configuration, if any.
Returns: The dock item used to contain the widget.
GtkWidget * mate_app_add_docked (MateApp *app, GtkWidget *widget, const gchar *name, MateComponentDockItemBehavior behavior, MateComponentDockPlacement placement, gint band_num, gint band_position, gint offset)
void mate_app_enable_layout_config (MateApp *app, gboolean enable)
.
Returns: The retrieved dock item.
MateComponentDockItem * mate_app_get_dock_item_by_name (MateApp *app, const gchar *name)
MateComponentDock * mate_app_get_dock (MateApp *app)
Macro Definition Documentation
LAYOUT_CONFIG_PATH
#define LAYOUT_CONFIG_PATH "Placement/Dock"
Definition at line 67 of file mate-app.c.
MATECOMPONENT_UI_INTERNAL
#define MATECOMPONENT_UI_INTERNAL
Definition at line 48 of file mate-app.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_APP_ID
Definition at line 126 of file mate-app.c.
Function Documentation
mate_app_add_dock_item()
void mate_app_add_dock_item (MateApp * app, MateComponentDockItem * item, MateComponentDockPlacement placement, gint band_num, gint band_position, gint offset)
mate_app_add_dock_item: @app: A MateApp widget. @item: Dock item to be added to @app's dock. @placement: Placement for the dock item. @band_num: Number of the band where the dock item should be placed. @band_position: Position of the dock item in band @band_num. @offset: Offset from the previous dock item in the band; if there is no previous item, offset from the beginning of the band.
Add @item according to the specified layout information. Notice that, if automatic layout configuration is enabled, the layout is overridden by the saved configuration, if any.
Definition at line 735 of file mate-app.c.
References _MateApp::dock, FALSE, item, and _MateApp::layout.
Referenced by mate_app_add_docked().
mate_app_add_docked()
GtkWidget * mate_app_add_docked (MateApp * app, GtkWidget * widget, const gchar * name, MateComponentDockItemBehavior behavior, MateComponentDockPlacement placement, gint band_num, gint band_position, gint offset)
Definition at line 781 of file mate-app.c.
References item, mate_app_add_dock_item(), and name.
mate_app_add_toolbar()
void mate_app_add_toolbar (MateApp * app, GtkToolbar * toolbar, const gchar * name, MateComponentDockItemBehavior behavior, MateComponentDockPlacement placement, gint band_num, gint band_position, gint offset)
Definition at line 640 of file mate-app.c.
References _MateApp::dock, _MateApp::layout, mate_app_setup_toolbar(), MATE_IS_APP, name, NULL, and TRUE.
Referenced by mate_app_set_toolbar().
mate_app_construct()
void mate_app_construct (MateApp * app, const gchar * appname, const gchar * title)
mate_app_construct: @app: A newly created MateApp object. @appname: Name of program, using in file names and paths. @title: Window title for application.
Description: Constructor for language bindings; you don't normally need this.
Definition at line 390 of file mate-app.c.
References NULL.
mate_app_enable_layout_config()
void mate_app_enable_layout_config (MateApp * app, gboolean enable)
mate_app_enable_layout_config: @app: A MateApp widget. @enable: Boolean specifying whether automatic configuration saving is enabled.
Specify whether @app should automatically save the dock's layout configuration via mate-config whenever it changes or not.
Definition at line 811 of file mate-app.c.
References _MateApp::enable_layout_config.
mate_app_get_dock()
MateComponentDock * mate_app_get_dock (MateApp * app)
mate_app_get_dock: @app: A MateApp widget
Retrieves the #MateComponentDock widget contained in @app.
Returns: The relevant #MateComponentDock widget.
Definition at line 857 of file mate-app.c.
References _MateApp::dock.
mate_app_get_dock_item_by_name()
MateComponentDockItem * mate_app_get_dock_item_by_name (MateApp * app, const gchar * name)
Definition at line 826 of file mate-app.c.
References _MateApp::dock, item, _MateApp::layout, name, and NULL.
mate_app_new()
GtkWidget * mate_app_new (const gchar * appname, const gchar * title)
mate_app_new: @appname: Name of program, used in file names and paths. @title: Window title for application.
Description: Create a new (empty) application window. You must specify the @appname (used internally as an identifier). The @title param can be left as NULL, in which case the window's title will not be set.
Returns: Pointer to new MateApp object.
Definition at line 360 of file mate-app.c.
References MATE_TYPE_APP, and NULL.
mate_app_set_contents()
void mate_app_set_contents (MateApp * app, GtkWidget * contents)
mate_app_set_contents: @app: A MateApp instance. @contents: Widget to be application content area.
Description: Sets the content area of the main window of @app.
Definition at line 479 of file mate-app.c.
References _MateApp::contents, _MateApp::dock, MATE_IS_APP, and NULL.
Referenced by mate_mdi_add_toplevel_view(), mate_mdi_add_view(), mate_mdi_remove_child(), mate_mdi_set_active_view(), and mate_mdi_set_mode().
mate_app_set_menus()
void mate_app_set_menus (MateApp * app, GtkMenuBar * menubar)
mate_app_set_menus: @app: A MateApp instance. @menubar: Menu bar widget for main application window.
Description: Sets the menu bar of the application window.
Definition at line 514 of file mate-app.c.
References _MateApp::dock, _MateApp::layout, MATE_APP_MENUBAR_NAME, MATE_IS_APP, mate_mateconf_get_bool, _MateApp::menubar, NULL, and TRUE.
Referenced by mate_app_create_menus_custom().
mate_app_set_statusbar()
void mate_app_set_statusbar (MateApp * app, GtkWidget * statusbar)
mate_app_set_statusbar: @app: A MateApp instance @statusbar: Statusbar widget for main app window
Description: Sets the status bar of the application window.
Definition at line 572 of file mate-app.c.
References FALSE, MATE_IS_APP, NULL, _MateApp::statusbar, TRUE, and _MateApp::vbox.
mate_app_set_statusbar_custom()
void mate_app_set_statusbar_custom (MateApp * app, GtkWidget * container, GtkWidget * statusbar)
mate_app_set_statusbar_custom: @app: A MateApp instance @container: container widget containing the statusbar @statusbar: Statusbar widget for main app window
Description: Sets the status bar of the application window, but use @container as its container.
Definition at line 606 of file mate-app.c.
References FALSE, MATE_IS_APP, NULL, _MateApp::statusbar, and _MateApp::vbox.
mate_app_set_toolbar()
void mate_app_set_toolbar (MateApp * app, GtkToolbar * toolbar)
mate_app_set_toolbar: @app: A MateApp instance. @toolbar: Toolbar widget for main app window.
Description: Sets the main toolbar of the application window.
Definition at line 699 of file mate-app.c.
References mate_app_add_toolbar(), MATE_APP_TOOLBAR_NAME, and mate_mateconf_get_bool.
Referenced by mate_app_create_toolbar_custom().
MATE_CLASS_BOILERPLATE()
MATE_CLASS_BOILERPLATE (MateApp , mate_app , GtkWindow , GTK_TYPE_WINDOW)
Definition at line 97 of file mate-app.c.
References LAYOUT_CONFIG_PATH, and _MateApp::prefix.