MATE Desktop Environment: matemixer-backend-module.h File Reference
matemixer-backend-module.h File Reference
#include <glib.h>
#include <glib-object.h>
#include "matemixer-enums.h"
Classes
struct _MateMixerBackendModule
struct _MateMixerBackendModuleClass
struct _MateMixerBackendInfo
Macros
#define MATE_MIXER_TYPE_BACKEND_MODULE (mate_mixer_backend_module_get_type ())
#define MATE_MIXER_BACKEND_MODULE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MATE_MIXER_TYPE_BACKEND_MODULE, MateMixerBackendModule))
#define MATE_MIXER_IS_BACKEND_MODULE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MATE_MIXER_TYPE_BACKEND_MODULE))
#define MATE_MIXER_BACKEND_MODULE_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MATE_MIXER_TYPE_BACKEND_MODULE, MateMixerBackendModuleClass))
#define MATE_MIXER_IS_BACKEND_MODULE_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MATE_MIXER_TYPE_BACKEND_MODULE))
#define MATE_MIXER_BACKEND_MODULE_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MATE_MIXER_TYPE_BACKEND_MODULE, MateMixerBackendModuleClass))
Typedefs
typedef struct _MateMixerBackendInfo MateMixerBackendInfo
typedef struct _MateMixerBackendModule MateMixerBackendModule
typedef struct _MateMixerBackendModuleClass MateMixerBackendModuleClass
typedef struct _MateMixerBackendModulePrivate MateMixerBackendModulePrivate
Functions
GType mate_mixer_backend_module_get_type (void)
MateMixerBackendModule * mate_mixer_backend_module_new (const gchar *path)
const MateMixerBackendInfo * mate_mixer_backend_module_get_info (MateMixerBackendModule *module)
const gchar * mate_mixer_backend_module_get_path (MateMixerBackendModule *module)
Macro Definition Documentation
MATE_MIXER_BACKEND_MODULE
#define MATE_MIXER_BACKEND_MODULE (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MATE_MIXER_TYPE_BACKEND_MODULE, MateMixerBackendModule))
Definition at line 30 of file matemixer-backend-module.h.
MATE_MIXER_BACKEND_MODULE_CLASS
#define MATE_MIXER_BACKEND_MODULE_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), MATE_MIXER_TYPE_BACKEND_MODULE, MateMixerBackendModuleClass))
Definition at line 34 of file matemixer-backend-module.h.
MATE_MIXER_BACKEND_MODULE_GET_CLASS
#define MATE_MIXER_BACKEND_MODULE_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), MATE_MIXER_TYPE_BACKEND_MODULE, MateMixerBackendModuleClass))
Definition at line 38 of file matemixer-backend-module.h.
MATE_MIXER_IS_BACKEND_MODULE
#define MATE_MIXER_IS_BACKEND_MODULE (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MATE_MIXER_TYPE_BACKEND_MODULE))
Definition at line 32 of file matemixer-backend-module.h.
MATE_MIXER_IS_BACKEND_MODULE_CLASS
#define MATE_MIXER_IS_BACKEND_MODULE_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), MATE_MIXER_TYPE_BACKEND_MODULE))
Definition at line 36 of file matemixer-backend-module.h.
MATE_MIXER_TYPE_BACKEND_MODULE
#define MATE_MIXER_TYPE_BACKEND_MODULE (mate_mixer_backend_module_get_type ())
Definition at line 28 of file matemixer-backend-module.h.
Typedef Documentation
MateMixerBackendInfo
typedef struct _MateMixerBackendInfo MateMixerBackendInfo
Definition at line 41 of file matemixer-backend-module.h.
MateMixerBackendModule
typedef struct _MateMixerBackendModule MateMixerBackendModule
Definition at line 42 of file matemixer-backend-module.h.
MateMixerBackendModuleClass
typedef struct _MateMixerBackendModuleClass MateMixerBackendModuleClass
Definition at line 43 of file matemixer-backend-module.h.
MateMixerBackendModulePrivate
typedef struct _MateMixerBackendModulePrivate MateMixerBackendModulePrivate
Definition at line 44 of file matemixer-backend-module.h.
Function Documentation
mate_mixer_backend_module_get_info()
const MateMixerBackendInfo * mate_mixer_backend_module_get_info (MateMixerBackendModule * module)
Definition at line 195 of file matemixer-backend-module.c.
References MATE_MIXER_IS_BACKEND_MODULE, NULL, _MateMixerBackendModule::priv, and TRUE.
Referenced by mate_mixer_context_get_backend_flags(), mate_mixer_context_get_backend_name(), mate_mixer_context_get_backend_type(), mate_mixer_context_open(), and mate_mixer_context_set_backend_type().
mate_mixer_backend_module_get_path()
const gchar * mate_mixer_backend_module_get_path (MateMixerBackendModule * module)
Definition at line 212 of file matemixer-backend-module.c.
References MATE_MIXER_IS_BACKEND_MODULE, and NULL.
mate_mixer_backend_module_get_type()
GType mate_mixer_backend_module_get_type (void)
mate_mixer_backend_module_new()
MateMixerBackendModule * mate_mixer_backend_module_new (const gchar * path)
mate_mixer_backend_module_new: @path: path to a backend module
Creates a new MateMixerBackendModule instance.
Returns: a new MateMixerBackendModule instance.
Definition at line 177 of file matemixer-backend-module.c.
References MATE_MIXER_TYPE_BACKEND_MODULE, and NULL.