MATE Desktop Environment: matemixer-device.h File Reference
matemixer-device.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer-types.h>
Classes
struct _MateMixerDevice
struct _MateMixerDeviceClass
Macros
#define MATE_MIXER_TYPE_DEVICE (mate_mixer_device_get_type ())
#define MATE_MIXER_DEVICE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MATE_MIXER_TYPE_DEVICE, MateMixerDevice))
#define MATE_MIXER_IS_DEVICE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MATE_MIXER_TYPE_DEVICE))
#define MATE_MIXER_DEVICE_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), MATE_MIXER_TYPE_DEVICE, MateMixerDeviceClass))
#define MATE_MIXER_IS_DEVICE_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MATE_MIXER_TYPE_DEVICE))
#define MATE_MIXER_DEVICE_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MATE_MIXER_TYPE_DEVICE, MateMixerDeviceClass))
Typedefs
typedef struct _MateMixerDeviceClass MateMixerDeviceClass
typedef struct _MateMixerDevicePrivate MateMixerDevicePrivate
Functions
GType mate_mixer_device_get_type (void)
const gchar * mate_mixer_device_get_name (MateMixerDevice *device)
const gchar * mate_mixer_device_get_label (MateMixerDevice *device)
const gchar * mate_mixer_device_get_icon (MateMixerDevice *device)
MateMixerStream * mate_mixer_device_get_stream (MateMixerDevice *device, const gchar *name)
MateMixerDeviceSwitch * mate_mixer_device_get_switch (MateMixerDevice *device, const gchar *name)
const GList * mate_mixer_device_list_streams (MateMixerDevice *device)
const GList * mate_mixer_device_list_switches (MateMixerDevice *device)
Macro Definition Documentation
MATE_MIXER_DEVICE
#define MATE_MIXER_DEVICE (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MATE_MIXER_TYPE_DEVICE, MateMixerDevice))
Definition at line 30 of file matemixer-device.h.
MATE_MIXER_DEVICE_CLASS
#define MATE_MIXER_DEVICE_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), MATE_MIXER_TYPE_DEVICE, MateMixerDeviceClass))
Definition at line 34 of file matemixer-device.h.
MATE_MIXER_DEVICE_GET_CLASS
#define MATE_MIXER_DEVICE_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), MATE_MIXER_TYPE_DEVICE, MateMixerDeviceClass))
Definition at line 38 of file matemixer-device.h.
MATE_MIXER_IS_DEVICE
#define MATE_MIXER_IS_DEVICE (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MATE_MIXER_TYPE_DEVICE))
Definition at line 32 of file matemixer-device.h.
MATE_MIXER_IS_DEVICE_CLASS
#define MATE_MIXER_IS_DEVICE_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), MATE_MIXER_TYPE_DEVICE))
Definition at line 36 of file matemixer-device.h.
MATE_MIXER_TYPE_DEVICE
#define MATE_MIXER_TYPE_DEVICE (mate_mixer_device_get_type ())
Definition at line 28 of file matemixer-device.h.
Typedef Documentation
MateMixerDeviceClass
typedef struct _MateMixerDeviceClass MateMixerDeviceClass
Definition at line 41 of file matemixer-device.h.
MateMixerDevicePrivate
typedef struct _MateMixerDevicePrivate MateMixerDevicePrivate
Definition at line 42 of file matemixer-device.h.
Function Documentation
mate_mixer_device_get_icon()
const gchar * mate_mixer_device_get_icon (MateMixerDevice * device)
mate_mixer_device_get_icon: @device: a MateMixerDevice
Gets the XDG icon name of the device.
Returns: the icon name or NULL.
Definition at line 359 of file matemixer-device.c.
References MATE_MIXER_IS_DEVICE, NULL, and _MateMixerDevice::priv.
mate_mixer_device_get_label()
const gchar * mate_mixer_device_get_label (MateMixerDevice * device)
mate_mixer_device_get_label: @device: a MateMixerDevice
Gets the label of the device.
This is a potentially translated string that should be presented to users in the user interface.
Returns: the label of the device.
Definition at line 343 of file matemixer-device.c.
References MATE_MIXER_IS_DEVICE, NULL, and _MateMixerDevice::priv.
Referenced by alsa_device_open(), alsa_stream_new(), oss_device_open(), and oss_stream_new().
mate_mixer_device_get_name()
const gchar * mate_mixer_device_get_name (MateMixerDevice * device)
mate_mixer_device_get_name: @device: a MateMixerDevice
Gets the name of the device.
The name serves as a unique identifier and in most cases it is not in a user-readable form.
The returned name is guaranteed to be unique across all the known devices and may be used to get the MateMixerDevice using mate_mixer_context_get_device().
Returns: the name of the device.
Definition at line 324 of file matemixer-device.c.
References MATE_MIXER_IS_DEVICE, NULL, and _MateMixerDevice::priv.
Referenced by alsa_device_open(), mate_mixer_backend_get_device(), and oss_device_load().
mate_mixer_device_get_stream()
MateMixerStream * mate_mixer_device_get_stream (MateMixerDevice * device, const gchar * name)
Definition at line 376 of file matemixer-device.c.
References MATE_MIXER_DEVICE_GET_CLASS, MATE_MIXER_IS_DEVICE, name, and NULL.
mate_mixer_device_get_switch()
MateMixerDeviceSwitch * mate_mixer_device_get_switch (MateMixerDevice * device, const gchar * name)
Definition at line 401 of file matemixer-device.c.
References MATE_MIXER_DEVICE_GET_CLASS, MATE_MIXER_IS_DEVICE, name, and NULL.
mate_mixer_device_get_type()
GType mate_mixer_device_get_type (void)
mate_mixer_device_list_streams()
const GList * mate_mixer_device_list_streams (MateMixerDevice * device)
mate_mixer_device_list_streams: @device: a MateMixerDevice
Gets the list of streams that belong to the device.
The returned #GList is owned by the MateMixerDevice and may be invalidated at any time.
Returns: a #GList of the device streams or NULL if the device does not have any streams.
Definition at line 422 of file matemixer-device.c.
References _MateMixerDeviceClass::list_streams, MATE_MIXER_DEVICE_GET_CLASS, MATE_MIXER_IS_DEVICE, and NULL.
mate_mixer_device_list_switches()
const GList * mate_mixer_device_list_switches (MateMixerDevice * device)
mate_mixer_device_list_switches: @device: a MateMixerDevice
Gets the list of switches the belong to the device.
Note that a switch may belong either to a device, or to a stream. Unlike stream switches, device switches returned by this function are not classified as input or output (as streams are), but they operate on the whole device.
Use mate_mixer_stream_list_switches() to get a list of switches that belong to a stream.
The returned #GList is owned by the MateMixerDevice and may be invalidated at any time.
Returns: a #GList of the device switches or NULL if the device does not have any switches.
Definition at line 456 of file matemixer-device.c.
References _MateMixerDeviceClass::list_switches, MATE_MIXER_DEVICE_GET_CLASS, MATE_MIXER_IS_DEVICE, and NULL.