MATE Desktop Environment: mate-scores.h File Reference
mate-scores.h File Reference
#include <time.h>
#include <gtk/gtk.h>
Classes
struct _MateScores
struct _MateScoresClass
Macros
#define MATE_TYPE_SCORES (mate_scores_get_type())
#define MATE_SCORES(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), MATE_TYPE_SCORES, MateScores))
#define MATE_SCORES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), MATE_TYPE_SCORES, MateScoresClass))
#define MATE_IS_SCORES(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), MATE_TYPE_SCORES))
#define MATE_IS_SCORES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), MATE_TYPE_SCORES))
#define MATE_SCORES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), MATE_TYPE_SCORES, MateScoresClass))
Typedefs
typedef struct _MateScores MateScores
typedef struct _MateScoresPrivate MateScoresPrivate
typedef struct _MateScoresClass MateScoresClass
Functions
GType mate_scores_get_type (void)
GtkWidget * mate_scores_display (const gchar *title, const gchar *app_name, const gchar *level, int pos)
GtkWidget * mate_scores_display_with_pixmap (const gchar *pixmap_logo, const gchar *app_name, const gchar *level, int pos)
GtkWidget * mate_scores_new (guint n_scores, gchar **names, gfloat *scores, time_t *times, gboolean clear)
void mate_scores_construct (MateScores *gs, guint n_scores, gchar **names, gfloat *scores, time_t *times, gboolean clear)
void mate_scores_set_logo_label (MateScores *gs, const gchar *txt, const gchar *font, GdkColor *col)
void mate_scores_set_logo_pixmap (MateScores *gs, const gchar *pix_name)
void mate_scores_set_logo_widget (MateScores *gs, GtkWidget *w)
void mate_scores_set_color (MateScores *gs, guint n, GdkColor *col)
void mate_scores_set_def_color (MateScores *gs, GdkColor *col)
void mate_scores_set_colors (MateScores *gs, GdkColor *col)
void mate_scores_set_logo_label_title (MateScores *gs, const gchar *txt)
void mate_scores_set_current_player (MateScores *gs, gint i)
Macro Definition Documentation
MATE_IS_SCORES
#define MATE_IS_SCORES (obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), MATE_TYPE_SCORES))
Definition at line 64 of file mate-scores.h.
MATE_IS_SCORES_CLASS
#define MATE_IS_SCORES_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), MATE_TYPE_SCORES))
Definition at line 66 of file mate-scores.h.
MATE_SCORES
#define MATE_SCORES (obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), MATE_TYPE_SCORES, MateScores))
Definition at line 60 of file mate-scores.h.
MATE_SCORES_CLASS
#define MATE_SCORES_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), MATE_TYPE_SCORES, MateScoresClass))
Definition at line 62 of file mate-scores.h.
MATE_SCORES_GET_CLASS
#define MATE_SCORES_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS((obj), MATE_TYPE_SCORES, MateScoresClass))
Definition at line 68 of file mate-scores.h.
MATE_TYPE_SCORES
#define MATE_TYPE_SCORES (mate_scores_get_type())
Definition at line 58 of file mate-scores.h.
Typedef Documentation
MateScores
typedef struct _MateScores MateScores
Definition at line 71 of file mate-scores.h.
MateScoresClass
typedef struct _MateScoresClass MateScoresClass
Definition at line 73 of file mate-scores.h.
MateScoresPrivate
typedef struct _MateScoresPrivate MateScoresPrivate
Definition at line 72 of file mate-scores.h.
Function Documentation
mate_scores_construct()
void mate_scores_construct (MateScores * gs, guint n_scores, gchar ** names, gfloat * scores, time_t * times, gboolean clear)
mate_scores_construct: @gs: @n_scores: Number of positions. @names: Names of the players. @scores: Scores @times: Time in which the scores were done @clear: Add a "Clear" Button?
Description: useful for language bindings and subclassing, not to be used by itself, see mate_scores_new.
Definition at line 155 of file mate-scores.c.
References _, _MateScores::_priv, and NULL.
Referenced by mate_scores_new().
mate_scores_display()
GtkWidget * mate_scores_display (const gchar * title, const gchar * app_name, const gchar * level, int pos)
mate_scores_display: @title: Title of the app to be displayed as logo @app_name: Name of the application, as in mate_score_init. @level: Level of the game or NULL. @pos: Position in the top ten of the current player, as returned by mate_score_log.
Description: Does all the work of displaying the best scores. It calls mate_score_get_notables to retrieve the info, creates the window, and show it. If there are no scores nothing is displayed and the recommended practise is to disable the scores menu entry in this case.
USAGE:
pos = mate_score_log(score, level, TRUE); mate_scores_display (_("Mi game"), "migame", level, pos);
Returns: If a dialog is displayed return it's pointer. It can also be NULL if no dialog is displayed
Definition at line 451 of file mate-scores.c.
References level, MATE_SCORES, mate_scores_new(), mate_scores_set_current_player(), mate_scores_set_logo_label_title(), and NULL.
mate_scores_display_with_pixmap()
GtkWidget * mate_scores_display_with_pixmap (const gchar * pixmap_logo, const gchar * app_name, const gchar * level, int pos)
mate_scores_display_with_pixmap: @pixmap_logo: Filename of a logo pixmap to display @app_name: Name of the application, as in mate_score_init. @level: Level of the game or NULL. @pos: Position in the top ten of the current player, as returned by mate_score_log.
Description: Does all the work of displaying the best scores. It calls mate_score_get_notables to retrieve the info, creates the window, and show it.
Returns: If a dialog is displayed return it's pointer. It can also be NULL if no dialog is displayed
Definition at line 490 of file mate-scores.c.
References level, MATE_SCORES, mate_scores_new(), mate_scores_set_current_player(), mate_scores_set_logo_pixmap(), and NULL.
mate_scores_get_type()
GType mate_scores_get_type (void)
mate_scores_new()
GtkWidget * mate_scores_new (guint n_scores, gchar ** names, gfloat * scores, time_t * times, gboolean clear)
mate_scores_new: @n_scores: Number of positions. @names: Names of the players. @scores: Scores @times: Time in which the scores were done @clear: Add a "Clear" Button?
Description: Creates the high-scores window.
Returns: A new MateScores widget
Definition at line 219 of file mate-scores.c.
References MATE_SCORES, mate_scores_construct(), MATE_TYPE_SCORES, and NULL.
Referenced by mate_scores_display(), and mate_scores_display_with_pixmap().
mate_scores_set_color()
void mate_scores_set_color (MateScores * gs, guint n, GdkColor * col)
mate_scores_set_color: @gs: A MateScores widget
: Entry to be changed. @col: Color.
Description: Set the color of one entry.
Definition at line 236 of file mate-scores.c.
References _MateScores::_priv, MATE_IS_SCORES, memcpy, and NULL.
Referenced by mate_scores_set_colors(), and mate_scores_set_def_color().
mate_scores_set_colors()
void mate_scores_set_colors (MateScores * gs, GdkColor * col)
mate_scores_set_colors: @gs: A MateScores widget @col: Array of colors.
Description: Set the color of all the entries.
Definition at line 283 of file mate-scores.c.
References _MateScores::_priv, MATE_IS_SCORES, mate_scores_set_color(), and NULL.
mate_scores_set_current_player()
void mate_scores_set_current_player (MateScores * gs, gint i)
mate_scores_set_current_player: @gs: A MateScores widget @i: Index of the current(from 0 to 9).
Description: Set the index of the current player in top ten.
Definition at line 303 of file mate-scores.c.
References _MateScores::_priv, MATE_IS_SCORES, and NULL.
Referenced by mate_scores_display(), and mate_scores_display_with_pixmap().
mate_scores_set_def_color()
void mate_scores_set_def_color (MateScores * gs, GdkColor * col)
mate_scores_set_def_color: @gs: A MateScores widget @col: Color
Description: Set the default color of the entries.
Definition at line 263 of file mate-scores.c.
References _MateScores::_priv, MATE_IS_SCORES, mate_scores_set_color(), and NULL.
mate_scores_set_logo_label()
void mate_scores_set_logo_label (MateScores * gs, const gchar * txt, const gchar * font, GdkColor * col)
mate_scores_set_logo_label: @gs: A MateScores widget @txt: Text in the label. @font: Font to use in the label. @col: Color to use in the label.
Description: Creates a label to be the logo
Definition at line 348 of file mate-scores.c.
References _, _MateScores::_priv, MATE_IS_SCORES, and NULL.
mate_scores_set_logo_label_title()
void mate_scores_set_logo_label_title (MateScores * gs, const gchar * txt)
mate_scores_set_logo_label_title: @gs: A MateScores widget @txt: Name of the logo.
Description: Creates a label to be the logo
Definition at line 321 of file mate-scores.c.
References _MateScores::_priv, MATE_IS_SCORES, and NULL.
Referenced by mate_scores_display().
mate_scores_set_logo_pixmap()
void mate_scores_set_logo_pixmap (MateScores * gs, const gchar * pix_name)
mate_scores_set_logo_pixmap: @gs: A MateScores widget @pix_name: filename of a pixmap
Description: Sets the logo on the scores dialog box to a pixmap
Definition at line 412 of file mate-scores.c.
References _MateScores::_priv, MATE_IS_SCORES, and NULL.
Referenced by mate_scores_display_with_pixmap().
mate_scores_set_logo_widget()
void mate_scores_set_logo_widget (MateScores * gs, GtkWidget * w)
mate_scores_set_logo_widget: @gs: A MateScores widget @w: Widget to be used as logo.
Description: Set an arbitrary widget to be the logo.
Definition at line 387 of file mate-scores.c.
References _MateScores::_priv, MATE_IS_SCORES, and NULL.