MATE Desktop Environment: mate-dateedit.h File Reference
mate-dateedit.h File Reference
#include <time.h>
#include <gtk/gtk.h>
Classes
struct _MateDateEdit
struct _MateDateEditClass
Macros
#define MATE_TYPE_DATE_EDIT (mate_date_edit_get_type ())
#define MATE_DATE_EDIT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_DATE_EDIT, MateDateEdit))
#define MATE_DATE_EDIT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_DATE_EDIT, MateDateEditClass))
#define MATE_IS_DATE_EDIT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_DATE_EDIT))
#define MATE_IS_DATE_EDIT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_DATE_EDIT))
#define MATE_DATE_EDIT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_DATE_EDIT, MateDateEditClass))
Typedefs
typedef struct _MateDateEdit MateDateEdit
typedef struct _MateDateEditPrivate MateDateEditPrivate
typedef struct _MateDateEditClass MateDateEditClass
Enumerations
enum MateDateEditFlags { MATE_DATE_EDIT_SHOW_TIME = 1 << 0 , MATE_DATE_EDIT_24_HR = 1 << 1 , MATE_DATE_EDIT_WEEK_STARTS_ON_MONDAY = 1 << 2 , MATE_DATE_EDIT_DISPLAY_SECONDS = 1 << 3 }
Functions
GType mate_date_edit_get_type (void)
GtkWidget * mate_date_edit_new (time_t the_time, gboolean show_time, gboolean use_24_format)
GtkWidget * mate_date_edit_new_flags (time_t the_time, MateDateEditFlags flags)
void mate_date_edit_construct (MateDateEdit *gde, time_t the_time, MateDateEditFlags flags)
void mate_date_edit_set_time (MateDateEdit *gde, time_t the_time)
time_t mate_date_edit_get_time (MateDateEdit *gde)
void mate_date_edit_set_popup_range (MateDateEdit *gde, int low_hour, int up_hour)
void mate_date_edit_set_flags (MateDateEdit *gde, MateDateEditFlags flags)
int mate_date_edit_get_flags (MateDateEdit *gde)
time_t mate_date_edit_get_initial_time (MateDateEdit *gde)
time_t mate_date_edit_get_date (MateDateEdit *gde)
Macro Definition Documentation
MATE_DATE_EDIT
#define MATE_DATE_EDIT (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_DATE_EDIT, MateDateEdit))
Definition at line 47 of file mate-dateedit.h.
MATE_DATE_EDIT_CLASS
#define MATE_DATE_EDIT_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_DATE_EDIT, MateDateEditClass))
Definition at line 48 of file mate-dateedit.h.
MATE_DATE_EDIT_GET_CLASS
#define MATE_DATE_EDIT_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_DATE_EDIT, MateDateEditClass))
Definition at line 51 of file mate-dateedit.h.
MATE_IS_DATE_EDIT
#define MATE_IS_DATE_EDIT (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_DATE_EDIT))
Definition at line 49 of file mate-dateedit.h.
MATE_IS_DATE_EDIT_CLASS
#define MATE_IS_DATE_EDIT_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_DATE_EDIT))
Definition at line 50 of file mate-dateedit.h.
MATE_TYPE_DATE_EDIT
#define MATE_TYPE_DATE_EDIT (mate_date_edit_get_type ())
Definition at line 46 of file mate-dateedit.h.
Typedef Documentation
MateDateEdit
typedef struct _MateDateEdit MateDateEdit
Definition at line 53 of file mate-dateedit.h.
MateDateEditClass
typedef struct _MateDateEditClass MateDateEditClass
Definition at line 55 of file mate-dateedit.h.
MateDateEditPrivate
typedef struct _MateDateEditPrivate MateDateEditPrivate
Definition at line 54 of file mate-dateedit.h.
Enumeration Type Documentation
MateDateEditFlags
enum MateDateEditFlags
Enumerator
MATE_DATE_EDIT_SHOW_TIME
MATE_DATE_EDIT_24_HR
MATE_DATE_EDIT_WEEK_STARTS_ON_MONDAY
MATE_DATE_EDIT_DISPLAY_SECONDS
Definition at line 38 of file mate-dateedit.h.
Function Documentation
mate_date_edit_construct()
void mate_date_edit_construct (MateDateEdit * gde, time_t the_time, MateDateEditFlags flags)
mate_date_edit_construct: @gde: The MateDateEdit object to construct @the_time: The initial time for the date editor. @flags: A bitmask of MateDateEditFlags values.
Description: For language bindings and subclassing only
Definition at line 912 of file mate-dateedit.c.
References mate_date_edit_set_flags(), and mate_date_edit_set_time().
Referenced by mate_date_edit_new_flags().
mate_date_edit_get_date()
time_t mate_date_edit_get_date (MateDateEdit * gde)
mate_date_edit_get_date: @gde: The MateDateEdit widget
Deprecated, use mate_date_edit_get_time
Returns:
Definition at line 1029 of file mate-dateedit.c.
References _, and mate_date_edit_get_time().
mate_date_edit_get_flags()
int mate_date_edit_get_flags (MateDateEdit * gde)
mate_date_edit_get_flags: @gde: The date editor whose flags should be queried.
Queries the display flags on a date editor widget.
Return value: The current display flags for the specified date editor widget.
Definition at line 1093 of file mate-dateedit.c.
References _MateDateEdit::_priv, MATE_IS_DATE_EDIT, and NULL.
mate_date_edit_get_initial_time()
time_t mate_date_edit_get_initial_time (MateDateEdit * gde)
mate_date_edit_get_initial_time: @gde: The date editor whose initial time should be queried
Description: Queries the initial time that was set using the mate_date_edit_set_time or during creation
Returns: The initial time in seconds (standard time_t format)
Definition at line 1111 of file mate-dateedit.c.
References _MateDateEdit::_priv, MATE_IS_DATE_EDIT, and NULL.
mate_date_edit_get_time()
time_t mate_date_edit_get_time (MateDateEdit * gde)
mate_date_edit_get_time: @gde: The MateDateEdit widget
Returns the time entered in the MateDateEdit widget
Definition at line 925 of file mate-dateedit.c.
References _MateDateEdit::_priv, MATE_DATE_EDIT_SHOW_TIME, MATE_IS_DATE_EDIT, and NULL.
Referenced by mate_date_edit_get_date().
mate_date_edit_get_type()
GType mate_date_edit_get_type (void)
mate_date_edit_new()
GtkWidget * mate_date_edit_new (time_t the_time, gboolean show_time, gboolean use_24_format)
mate_date_edit_new: @the_time: date and time to be displayed on the widget @show_time: whether time should be displayed @use_24_format: whether 24-hour format is desired for the time display.
Description: Creates a new MateDateEdit widget which can be used to provide an easy to use way for entering dates and times. If @the_time is 0 then current time is used.
Returns: a new MateDateEdit widget.
Definition at line 874 of file mate-dateedit.c.
References MATE_DATE_EDIT_24_HR, mate_date_edit_new_flags(), and MATE_DATE_EDIT_SHOW_TIME.
mate_date_edit_new_flags()
GtkWidget * mate_date_edit_new_flags (time_t the_time, MateDateEditFlags flags)
mate_date_edit_new_flags: @the_time: The initial time for the date editor. @flags: A bitmask of MateDateEditFlags values.
Description: Creates a new MateDateEdit widget with the specified flags. If @the_time is 0 then current time is used.
Returns: the newly-created date editor widget.
Definition at line 892 of file mate-dateedit.c.
References mate_date_edit_construct(), MATE_TYPE_DATE_EDIT, and NULL.
Referenced by mate_date_edit_new().
mate_date_edit_set_flags()
void mate_date_edit_set_flags (MateDateEdit * gde, MateDateEditFlags flags)
mate_date_edit_set_flags: @gde: The date editor widget whose flags should be changed. @flags: The new bitmask of MateDateEditFlags values.
Changes the display flags on an existing date editor widget.
Definition at line 1046 of file mate-dateedit.c.
References _MateDateEdit::_priv, MATE_DATE_EDIT_24_HR, MATE_DATE_EDIT_SHOW_TIME, MATE_DATE_EDIT_WEEK_STARTS_ON_MONDAY, MATE_IS_DATE_EDIT, and NULL.
Referenced by mate_date_edit_construct().
mate_date_edit_set_popup_range()
void mate_date_edit_set_popup_range (MateDateEdit * gde, int low_hour, int up_hour)
mate_date_edit_set_popup_range: @gde: The MateDateEdit widget @low_hour: low boundary for the time-range display popup. @up_hour: upper boundary for the time-range display popup.
Sets the range of times that will be provide by the time popup selectors.
Definition at line 747 of file mate-dateedit.c.
References _MateDateEdit::_priv, and NULL.
mate_date_edit_set_time()
void mate_date_edit_set_time (MateDateEdit * gde, time_t the_time)
mate_date_edit_set_time: @gde: the MateDateEdit widget @the_time: The time and date that should be set on the widget
Description: Changes the displayed date and time in the MateDateEdit widget to be the one represented by @the_time. If @the_time is 0 then current time is used.
Definition at line 689 of file mate-dateedit.c.
References _MateDateEdit::_priv, MATE_DATE_EDIT_24_HR, MATE_DATE_EDIT_DISPLAY_SECONDS, and NULL.
Referenced by mate_date_edit_construct().