MATE Desktop Environment: mate-rr.c File Reference
mate-rr.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include <string.h>
#include <X11/Xlib.h>
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
#include <X11/Xatom.h>
#include "mate-rr.h"
#include "mate-rr-config.h"
#include "private.h"
#include "mate-rr-private.h"
Macros
#define MATE_DESKTOP_USE_UNSTABLE_API
#define DISPLAY(o) ((o)->info->screen->priv->xdisplay)
#define RR_Rotate_0 1
#define RR_Rotate_90 2
#define RR_Rotate_180 4
#define RR_Rotate_270 8
#define RR_Reflect_X 16
#define RR_Reflect_Y 32
Typedefs
typedef int RROutput
typedef int RRCrtc
typedef int RRMode
typedef int Rotation
Enumerations
enum { SCREEN_PROP_0 , SCREEN_PROP_GDK_SCREEN , SCREEN_PROP_LAST }
enum { SCREEN_CHANGED , SCREEN_SIGNAL_LAST }
Functions
G_DEFINE_TYPE_WITH_CODE (MateRRScreen, mate_rr_screen, G_TYPE_OBJECT, G_IMPLEMENT_INTERFACE(G_TYPE_INITABLE, mate_rr_screen_initable_iface_init))
void mate_rr_screen_class_init (MateRRScreenClass *klass)
void mate_rr_screen_init (MateRRScreen *self)
MateRRScreen * mate_rr_screen_new (GdkScreen *screen, GError **error)
void mate_rr_screen_set_size (MateRRScreen *screen, int width, int height, int mm_width, int mm_height)
void mate_rr_screen_get_ranges (MateRRScreen *screen, int *min_width, int *max_width, int *min_height, int *max_height)
void mate_rr_screen_get_timestamps (MateRRScreen *screen, guint32 *change_timestamp_ret, guint32 *config_timestamp_ret)
gboolean mate_rr_screen_refresh (MateRRScreen *screen, GError **error)
MateRRMode ** mate_rr_screen_list_modes (MateRRScreen *screen)
MateRRMode ** mate_rr_screen_list_clone_modes (MateRRScreen *screen)
MateRRCrtc ** mate_rr_screen_list_crtcs (MateRRScreen *screen)
MateRROutput ** mate_rr_screen_list_outputs (MateRRScreen *screen)
MateRRCrtc * mate_rr_screen_get_crtc_by_id (MateRRScreen *screen, guint32 id)
MateRROutput * mate_rr_screen_get_output_by_id (MateRRScreen *screen, guint32 id)
guint32 mate_rr_output_get_id (MateRROutput *output)
const guint8 * mate_rr_output_get_edid_data (MateRROutput *output)
Variables
gint screen_signals [SCREEN_SIGNAL_LAST]
mate_rr_screen_get_output_by_name:
Returns: (transfer none): the output identified by
MateRROutput * mate_rr_screen_get_output_by_name (MateRRScreen *screen, const char *name)
MateRRCrtc * mate_rr_output_get_crtc (MateRROutput *output)
MateRRCrtc ** mate_rr_output_get_possible_crtcs (MateRROutput *output)
const char * mate_rr_output_get_connector_type (MateRROutput *output)
gboolean _mate_rr_output_name_is_laptop (const char *name)
gboolean mate_rr_output_is_laptop (MateRROutput *output)
MateRRMode * mate_rr_output_get_current_mode (MateRROutput *output)
void mate_rr_output_get_position (MateRROutput *output, int *x, int *y)
const char * mate_rr_output_get_name (MateRROutput *output)
int mate_rr_output_get_width_mm (MateRROutput *output)
int mate_rr_output_get_height_mm (MateRROutput *output)
MateRRMode * mate_rr_output_get_preferred_mode (MateRROutput *output)
MateRRMode ** mate_rr_output_list_modes (MateRROutput *output)
gboolean mate_rr_output_is_connected (MateRROutput *output)
gboolean mate_rr_output_supports_mode (MateRROutput *output, MateRRMode *mode)
gboolean mate_rr_output_can_clone (MateRROutput *output, MateRROutput *clone)
gboolean mate_rr_output_get_is_primary (MateRROutput *output)
void mate_rr_screen_set_primary_output (MateRRScreen *screen, MateRROutput *output)
gboolean mate_rr_crtc_set_config (MateRRCrtc *crtc, int x, int y, MateRRMode *mode, MateRRRotation rotation, MateRROutput **outputs, int n_outputs, GError **error)
gboolean mate_rr_crtc_set_config_with_time (MateRRCrtc *crtc, guint32 timestamp, int x, int y, MateRRMode *mode, MateRRRotation rotation, MateRROutput **outputs, int n_outputs, GError **error)
MateRRMode * mate_rr_crtc_get_current_mode (MateRRCrtc *crtc)
guint32 mate_rr_crtc_get_id (MateRRCrtc *crtc)
gboolean mate_rr_crtc_can_drive_output (MateRRCrtc *crtc, MateRROutput *output)
void mate_rr_crtc_get_position (MateRRCrtc *crtc, int *x, int *y)
MateRRRotation mate_rr_crtc_get_current_rotation (MateRRCrtc *crtc)
MateRRRotation mate_rr_crtc_get_rotations (MateRRCrtc *crtc)
gboolean mate_rr_crtc_supports_rotation (MateRRCrtc *crtc, MateRRRotation rotation)
guint32 mate_rr_mode_get_id (MateRRMode *mode)
guint mate_rr_mode_get_width (MateRRMode *mode)
int mate_rr_mode_get_freq (MateRRMode *mode)
guint mate_rr_mode_get_height (MateRRMode *mode)
void mate_rr_crtc_set_gamma (MateRRCrtc *crtc, int size, unsigned short *red, unsigned short *green, unsigned short *blue)
gboolean mate_rr_crtc_get_gamma (MateRRCrtc *crtc, int *size, unsigned short **red, unsigned short **green, unsigned short **blue)
Macro Definition Documentation
DISPLAY
#define DISPLAY (o) ((o)->info->screen->priv->xdisplay)
Definition at line 47 of file mate-rr.c.
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 25 of file mate-rr.c.
RR_Reflect_X
#define RR_Reflect_X 16
Definition at line 59 of file mate-rr.c.
RR_Reflect_Y
#define RR_Reflect_Y 32
Definition at line 60 of file mate-rr.c.
RR_Rotate_0
#define RR_Rotate_0 1
Definition at line 55 of file mate-rr.c.
RR_Rotate_180
#define RR_Rotate_180 4
Definition at line 57 of file mate-rr.c.
RR_Rotate_270
#define RR_Rotate_270 8
Definition at line 58 of file mate-rr.c.
RR_Rotate_90
#define RR_Rotate_90 2
Definition at line 56 of file mate-rr.c.
Typedef Documentation
Rotation
typedef int Rotation
Definition at line 54 of file mate-rr.c.
RRCrtc
typedef int RRCrtc
Definition at line 52 of file mate-rr.c.
RRMode
typedef int RRMode
Definition at line 53 of file mate-rr.c.
RROutput
typedef int RROutput
Definition at line 51 of file mate-rr.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SCREEN_PROP_0
SCREEN_PROP_GDK_SCREEN
SCREEN_PROP_LAST
Definition at line 63 of file mate-rr.c.
anonymous enum
anonymous enum
Enumerator
SCREEN_CHANGED
SCREEN_SIGNAL_LAST
Definition at line 69 of file mate-rr.c.
Function Documentation
_mate_rr_output_name_is_laptop()
gboolean _mate_rr_output_name_is_laptop (const char * name)
Definition at line 1462 of file mate-rr.c.
References FALSE, name, and TRUE.
Referenced by mate_rr_config_ensure_primary(), and mate_rr_output_is_laptop().
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (MateRRScreen , mate_rr_screen , G_TYPE_OBJECT , G_IMPLEMENT_INTERFACE(G_TYPE_INITABLE, mate_rr_screen_initable_iface_init))
mate_rr_error_quark:
Returns the #GQuark that will be used for #GError values returned by the MateRR API.
Return value: a #GQuark used to identify errors coming from the MateRR API.
Definition at line 168 of file mate-rr.c.
mate_rr_crtc_can_drive_output()
gboolean mate_rr_crtc_can_drive_output (MateRRCrtc * crtc, MateRROutput * output)
Definition at line 1819 of file mate-rr.c.
References FALSE, NULL, and TRUE.
mate_rr_crtc_get_current_mode()
MateRRMode * mate_rr_crtc_get_current_mode (MateRRCrtc * crtc)
mate_rr_crtc_get_current_mode: @crtc: a #MateRRCrtc Returns: (transfer none): the current mode of this crtc
Definition at line 1803 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current(), and mate_rr_output_get_current_mode().
mate_rr_crtc_get_current_rotation()
MateRRRotation mate_rr_crtc_get_current_rotation (MateRRCrtc * crtc)
Definition at line 1860 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current().
mate_rr_crtc_get_gamma()
gboolean mate_rr_crtc_get_gamma (MateRRCrtc * crtc, int * size, unsigned short ** red, unsigned short ** green, unsigned short ** blue)
mate_rr_crtc_get_gamma: @crtc: a #MateRRCrtc @size: @red: (out): the minimum width @green: (out): the maximum width @blue: (out): the minimum height
Returns: TRUE for success
Definition at line 2121 of file mate-rr.c.
References b, DISPLAY, FALSE, memcpy, NULL, and TRUE.
mate_rr_crtc_get_id()
guint32 mate_rr_crtc_get_id (MateRRCrtc * crtc)
Definition at line 1811 of file mate-rr.c.
References NULL.
mate_rr_crtc_get_position()
void mate_rr_crtc_get_position (MateRRCrtc * crtc, int * x, int * y)
mate_rr_crtc_get_position: @crtc: a #MateRRCrtc @x: (out) (allow-none): @y: (out) (allow-none):
Definition at line 1845 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current(), and mate_rr_output_get_position().
mate_rr_crtc_get_rotations()
MateRRRotation mate_rr_crtc_get_rotations (MateRRCrtc * crtc)
Definition at line 1867 of file mate-rr.c.
References NULL.
mate_rr_crtc_set_config()
gboolean mate_rr_crtc_set_config (MateRRCrtc * crtc, int x, int y, MateRRMode * mode, MateRRRotation rotation, MateRROutput ** outputs, int n_outputs, GError ** error)
Definition at line 1702 of file mate-rr.c.
References error, and mate_rr_crtc_set_config_with_time().
mate_rr_crtc_set_config_with_time()
gboolean mate_rr_crtc_set_config_with_time (MateRRCrtc * crtc, guint32 timestamp, int x, int y, MateRRMode * mode, MateRRRotation rotation, MateRROutput ** outputs, int n_outputs, GError ** error)
Definition at line 1716 of file mate-rr.c.
References _, DISPLAY, error, FALSE, MATE_RR_ERROR, MATE_RR_ERROR_BOUNDS_ERROR, MATE_RR_ERROR_RANDR_ERROR, ScreenInfo::max_height, ScreenInfo::max_width, NULL, and TRUE.
Referenced by mate_rr_crtc_set_config().
mate_rr_crtc_set_gamma()
void mate_rr_crtc_set_gamma (MateRRCrtc * crtc, int size, unsigned short * red, unsigned short * green, unsigned short * blue)
Definition at line 2081 of file mate-rr.c.
References DISPLAY, memcpy, and NULL.
mate_rr_crtc_supports_rotation()
gboolean mate_rr_crtc_supports_rotation (MateRRCrtc * crtc, MateRRRotation rotation)
Definition at line 1874 of file mate-rr.c.
References FALSE, and NULL.
mate_rr_mode_get_freq()
int mate_rr_mode_get_freq (MateRRMode * mode)
Definition at line 2031 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current().
mate_rr_mode_get_height()
guint mate_rr_mode_get_height (MateRRMode * mode)
Definition at line 2038 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current().
mate_rr_mode_get_id()
guint32 mate_rr_mode_get_id (MateRRMode * mode)
Definition at line 2017 of file mate-rr.c.
References NULL.
mate_rr_mode_get_width()
guint mate_rr_mode_get_width (MateRRMode * mode)
Definition at line 2024 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current().
mate_rr_output_can_clone()
gboolean mate_rr_output_can_clone (MateRROutput * output, MateRROutput * clone)
Definition at line 1604 of file mate-rr.c.
References FALSE, NULL, and TRUE.
mate_rr_output_get_connector_type()
const char * mate_rr_output_get_connector_type (MateRROutput * output)
Definition at line 1454 of file mate-rr.c.
References NULL.
mate_rr_output_get_crtc()
MateRRCrtc * mate_rr_output_get_crtc (MateRROutput * output)
mate_rr_output_get_crtc: @output: a #MateRROutput Returns: (transfer none):
Definition at line 1432 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current(), mate_rr_output_get_current_mode(), and mate_rr_output_get_position().
mate_rr_output_get_current_mode()
MateRRMode * mate_rr_output_get_current_mode (MateRROutput * output)
mate_rr_output_get_current_mode: @output: a #MateRROutput Returns: (transfer none): the current mode of this output
Definition at line 1498 of file mate-rr.c.
References mate_rr_crtc_get_current_mode(), mate_rr_output_get_crtc(), and NULL.
mate_rr_output_get_edid_data()
const guint8 * mate_rr_output_get_edid_data (MateRROutput * output)
Definition at line 1394 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current().
mate_rr_output_get_height_mm()
int mate_rr_output_get_height_mm (MateRROutput * output)
Definition at line 1544 of file mate-rr.c.
References NULL.
mate_rr_output_get_id()
guint32 mate_rr_output_get_id (MateRROutput * output)
Definition at line 1386 of file mate-rr.c.
References NULL.
mate_rr_output_get_is_primary()
gboolean mate_rr_output_get_is_primary (MateRROutput * output)
Definition at line 1622 of file mate-rr.c.
References FALSE.
Referenced by mate_rr_config_load_current().
mate_rr_output_get_name()
const char * mate_rr_output_get_name (MateRROutput * output)
Definition at line 1530 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current().
mate_rr_output_get_position()
void mate_rr_output_get_position (MateRROutput * output, int * x, int * y)
mate_rr_output_get_position: @output: a #MateRROutput @x: (out) (allow-none): @y: (out) (allow-none):
Definition at line 1517 of file mate-rr.c.
References mate_rr_crtc_get_position(), mate_rr_output_get_crtc(), and NULL.
mate_rr_output_get_possible_crtcs()
MateRRCrtc ** mate_rr_output_get_possible_crtcs (MateRROutput * output)
mate_rr_output_get_possible_crtcs: @output: a #MateRROutput Returns: (array zero-terminated=1) (transfer none):
Definition at line 1445 of file mate-rr.c.
References NULL.
mate_rr_output_get_preferred_mode()
MateRRMode * mate_rr_output_get_preferred_mode (MateRROutput * output)
mate_rr_output_get_preferred_mode: @output: a #MateRROutput Returns: (transfer none):
Definition at line 1556 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current().
mate_rr_output_get_width_mm()
int mate_rr_output_get_width_mm (MateRROutput * output)
Definition at line 1537 of file mate-rr.c.
References NULL.
mate_rr_output_is_connected()
gboolean mate_rr_output_is_connected (MateRROutput * output)
Definition at line 1579 of file mate-rr.c.
References FALSE, and NULL.
Referenced by mate_rr_config_load_current().
mate_rr_output_is_laptop()
gboolean mate_rr_output_is_laptop (MateRROutput * output)
Definition at line 1478 of file mate-rr.c.
References _mate_rr_output_name_is_laptop(), FALSE, MATE_RR_CONNECTOR_TYPE_PANEL, NULL, and TRUE.
Referenced by mate_rr_config_load_current().
mate_rr_output_list_modes()
MateRRMode ** mate_rr_output_list_modes (MateRROutput * output)
mate_rr_output_list_modes: @output: a #MateRROutput Returns: (array zero-terminated=1) (transfer none):
Definition at line 1572 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current().
mate_rr_output_supports_mode()
gboolean mate_rr_output_supports_mode (MateRROutput * output, MateRRMode * mode)
Definition at line 1586 of file mate-rr.c.
References FALSE, NULL, and TRUE.
mate_rr_screen_class_init()
void mate_rr_screen_class_init (MateRRScreenClass * klass)
Definition at line 770 of file mate-rr.c.
References G_OBJECT_CLASS(), NULL, SCREEN_CHANGED, SCREEN_PROP_GDK_SCREEN, and screen_signals.
mate_rr_screen_get_crtc_by_id()
MateRRCrtc * mate_rr_screen_get_crtc_by_id (MateRRScreen * screen, guint32 id)
mate_rr_screen_get_crtc_by_id:
Returns: (transfer none): the CRTC identified by @id
Definition at line 1076 of file mate-rr.c.
References ScreenInfo::crtcs, MateRRScreenPrivate::info, MATE_IS_RR_SCREEN, NULL, and MateRRScreen::priv.
mate_rr_screen_get_output_by_id()
MateRROutput * mate_rr_screen_get_output_by_id (MateRRScreen * screen, guint32 id)
mate_rr_screen_get_output_by_id:
Returns: (transfer none): the output identified by @id
Definition at line 1102 of file mate-rr.c.
References MateRRScreenPrivate::info, MATE_IS_RR_SCREEN, NULL, ScreenInfo::outputs, and MateRRScreen::priv.
mate_rr_screen_get_output_by_name()
MateRROutput * mate_rr_screen_get_output_by_name (MateRRScreen * screen, const char * name)
Definition at line 1407 of file mate-rr.c.
References MateRRScreenPrivate::info, MATE_IS_RR_SCREEN, name, NULL, ScreenInfo::outputs, and MateRRScreen::priv.
mate_rr_screen_get_ranges()
void mate_rr_screen_get_ranges (MateRRScreen * screen, int * min_width, int * max_width, int * min_height, int * max_height)
mate_rr_screen_get_ranges: @screen: a MateRRScreen @min_width: (out): the minimum width @max_width: (out): the maximum width @min_height: (out): the minimum height @max_height: (out): the maximum height
Get the ranges of the screen
Definition at line 865 of file mate-rr.c.
References MateRRScreenPrivate::info, MATE_IS_RR_SCREEN, ScreenInfo::max_height, ScreenInfo::max_width, ScreenInfo::min_height, ScreenInfo::min_width, and MateRRScreen::priv.
mate_rr_screen_get_timestamps()
void mate_rr_screen_get_timestamps (MateRRScreen * screen, guint32 * change_timestamp_ret, guint32 * config_timestamp_ret)
mate_rr_screen_get_timestamps: @screen: a MateRRScreen @change_timestamp_ret: (out): Location in which to store the timestamp at which the RANDR configuration was last changed @config_timestamp_ret: (out): Location in which to store the timestamp at which the RANDR configuration was last obtained
Queries the two timestamps that the X RANDR extension maintains. The X server will prevent change requests for stale configurations, those whose timestamp is not equal to that of the latest request for configuration. The X server will also prevent change requests that have an older timestamp to the latest change request.
Definition at line 903 of file mate-rr.c.
References MateRRScreenPrivate::info, MATE_IS_RR_SCREEN, and MateRRScreen::priv.
mate_rr_screen_init()
void mate_rr_screen_init (MateRRScreen * self)
Definition at line 801 of file mate-rr.c.
References MateRRScreenPrivate::gdk_root, MateRRScreenPrivate::gdk_screen, MateRRScreenPrivate::info, NULL, MateRRScreen::priv, MateRRScreenPrivate::rr_major_version, MateRRScreenPrivate::rr_minor_version, MateRRScreenPrivate::xdisplay, MateRRScreenPrivate::xroot, and MateRRScreenPrivate::xscreen.
mate_rr_screen_list_clone_modes()
MateRRMode ** mate_rr_screen_list_clone_modes (MateRRScreen * screen)
mate_rr_screen_list_clone_modes:
List available XRandR clone modes
Returns: (array zero-terminated=1) (transfer none):
Definition at line 1030 of file mate-rr.c.
References ScreenInfo::clone_modes, MateRRScreenPrivate::info, MATE_IS_RR_SCREEN, NULL, and MateRRScreen::priv.
mate_rr_screen_list_crtcs()
MateRRCrtc ** mate_rr_screen_list_crtcs (MateRRScreen * screen)
mate_rr_screen_list_crtcs:
List all CRTCs
Returns: (array zero-terminated=1) (transfer none):
Definition at line 1046 of file mate-rr.c.
References ScreenInfo::crtcs, MateRRScreenPrivate::info, MATE_IS_RR_SCREEN, NULL, and MateRRScreen::priv.
mate_rr_screen_list_modes()
MateRRMode ** mate_rr_screen_list_modes (MateRRScreen * screen)
mate_rr_screen_list_modes:
List available XRandR modes
Returns: (array zero-terminated=1) (transfer none):
Definition at line 1014 of file mate-rr.c.
References MateRRScreenPrivate::info, MATE_IS_RR_SCREEN, ScreenInfo::modes, NULL, and MateRRScreen::priv.
mate_rr_screen_list_outputs()
MateRROutput ** mate_rr_screen_list_outputs (MateRRScreen * screen)
mate_rr_screen_list_outputs:
List all outputs
Returns: (array zero-terminated=1) (transfer none):
Definition at line 1062 of file mate-rr.c.
References MateRRScreenPrivate::info, MATE_IS_RR_SCREEN, NULL, ScreenInfo::outputs, and MateRRScreen::priv.
Referenced by mate_rr_config_load_current().
mate_rr_screen_new()
MateRRScreen * mate_rr_screen_new (GdkScreen * screen, GError ** error)
mate_rr_screen_new: @screen: the #GdkScreen on which to operate @error: will be set if XRandR is not supported
Creates a new MateRRScreen instance
Returns: a new MateRRScreen instance or NULL if screen could not be created, for instance if the driver does not support Xrandr 1.2
Definition at line 827 of file mate-rr.c.
References _mate_desktop_init_i18n(), error, MATE_TYPE_RR_SCREEN, and NULL.
Referenced by msd_xrandr_manager_start().
mate_rr_screen_refresh()
gboolean mate_rr_screen_refresh (MateRRScreen * screen, GError ** error)
mate_rr_screen_refresh: @screen: a MateRRScreen @error: location to store error, or NULL
Refreshes the screen configuration, and calls the screen's callback if it exists and if the screen's configuration changed.
Return value: TRUE if the screen's configuration changed; otherwise, the function returns FALSE and a NULL error if the configuration didn't change, or FALSE and a non-NULL error if there was an error while refreshing the configuration.
Definition at line 989 of file mate-rr.c.
References error, FALSE, MateRRScreenPrivate::gdk_screen, NULL, MateRRScreen::priv, and TRUE.
Referenced by mate_rr_config_apply_from_filename_with_time().
mate_rr_screen_set_primary_output()
void mate_rr_screen_set_primary_output (MateRRScreen * screen, MateRROutput * output)
Definition at line 1632 of file mate-rr.c.
References id, MATE_IS_RR_SCREEN, MateRRScreen::priv, MateRRScreenPrivate::xdisplay, and MateRRScreenPrivate::xroot.
mate_rr_screen_set_size()
void mate_rr_screen_set_size (MateRRScreen * screen, int width, int height, int mm_width, int mm_height)
Definition at line 835 of file mate-rr.c.
References MATE_IS_RR_SCREEN, MateRRScreen::priv, MateRRScreenPrivate::xdisplay, and MateRRScreenPrivate::xroot.
Variable Documentation
screen_signals
gint screen_signals[SCREEN_SIGNAL_LAST]
Definition at line 74 of file mate-rr.c.
Referenced by mate_rr_screen_class_init().