MATE Desktop Environment: mate-dateedit.c File Reference
mate-dateedit.c File Reference
#include <config.h>
#include <time.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <glib/gi18n-lib.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <libmate/mate-macros.h>
#include <libmate/mate-i18n.h>
#include "matetypebuiltins.h"
#include "libmateui-access.h"
#include "mate-dateedit.h"
Macros
#define _XOPEN_SOURCE
Enumerations
enum { DATE_CHANGED , TIME_CHANGED , LAST_SIGNAL }
enum {
PROP_0 , PROP_TIME , PROP_DATEEDIT_FLAGS , PROP_LOWER_HOUR ,
PROP_UPPER_HOUR , PROP_INITIAL_TIME
}
Functions
MATE_CLASS_BOILERPLATE (MateDateEdit, mate_date_edit, GtkHBox, GTK_TYPE_HBOX)
void mate_date_edit_set_time (MateDateEdit *gde, time_t the_time)
void mate_date_edit_set_popup_range (MateDateEdit *gde, int low_hour, int up_hour)
GtkWidget * mate_date_edit_new (time_t the_time, gboolean show_time, gboolean use_24_format)
GtkWidget * mate_date_edit_new_flags (time_t the_time, MateDateEditFlags flags)
void mate_date_edit_construct (MateDateEdit *gde, time_t the_time, MateDateEditFlags flags)
time_t mate_date_edit_get_time (MateDateEdit *gde)
time_t mate_date_edit_get_date (MateDateEdit *gde)
void mate_date_edit_set_flags (MateDateEdit *gde, MateDateEditFlags flags)
int mate_date_edit_get_flags (MateDateEdit *gde)
time_t mate_date_edit_get_initial_time (MateDateEdit *gde)
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE
Definition at line 32 of file mate-dateedit.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DATE_CHANGED
TIME_CHANGED
LAST_SIGNAL
Definition at line 88 of file mate-dateedit.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_TIME
PROP_DATEEDIT_FLAGS
PROP_LOWER_HOUR
PROP_UPPER_HOUR
PROP_INITIAL_TIME
Definition at line 94 of file mate-dateedit.c.
Function Documentation
MATE_CLASS_BOILERPLATE()
MATE_CLASS_BOILERPLATE (MateDateEdit , mate_date_edit , GtkHBox , GTK_TYPE_HBOX)
mate_date_edit_get_type:
Returns the GType for the MateDateEdit widget
Definition at line 128 of file mate-dateedit.c.
References _MateDateEdit::_priv.
mate_date_edit_construct()
void mate_date_edit_construct (MateDateEdit * gde, time_t the_time, MateDateEditFlags flags)
mate_date_edit_construct: @gde: The MateDateEdit object to construct @the_time: The initial time for the date editor. @flags: A bitmask of MateDateEditFlags values.
Description: For language bindings and subclassing only
Definition at line 912 of file mate-dateedit.c.
References mate_date_edit_set_flags(), and mate_date_edit_set_time().
Referenced by mate_date_edit_new_flags().
mate_date_edit_get_date()
time_t mate_date_edit_get_date (MateDateEdit * gde)
mate_date_edit_get_date: @gde: The MateDateEdit widget
Deprecated, use mate_date_edit_get_time
Returns:
Definition at line 1029 of file mate-dateedit.c.
References _, and mate_date_edit_get_time().
mate_date_edit_get_flags()
int mate_date_edit_get_flags (MateDateEdit * gde)
mate_date_edit_get_flags: @gde: The date editor whose flags should be queried.
Queries the display flags on a date editor widget.
Return value: The current display flags for the specified date editor widget.
Definition at line 1093 of file mate-dateedit.c.
References _MateDateEdit::_priv, MATE_IS_DATE_EDIT, and NULL.
mate_date_edit_get_initial_time()
time_t mate_date_edit_get_initial_time (MateDateEdit * gde)
mate_date_edit_get_initial_time: @gde: The date editor whose initial time should be queried
Description: Queries the initial time that was set using the mate_date_edit_set_time or during creation
Returns: The initial time in seconds (standard time_t format)
Definition at line 1111 of file mate-dateedit.c.
References _MateDateEdit::_priv, MATE_IS_DATE_EDIT, and NULL.
mate_date_edit_get_time()
time_t mate_date_edit_get_time (MateDateEdit * gde)
mate_date_edit_get_time: @gde: The MateDateEdit widget
Returns the time entered in the MateDateEdit widget
Definition at line 925 of file mate-dateedit.c.
References _MateDateEdit::_priv, MATE_DATE_EDIT_SHOW_TIME, MATE_IS_DATE_EDIT, and NULL.
Referenced by mate_date_edit_get_date().
mate_date_edit_new()
GtkWidget * mate_date_edit_new (time_t the_time, gboolean show_time, gboolean use_24_format)
mate_date_edit_new: @the_time: date and time to be displayed on the widget @show_time: whether time should be displayed @use_24_format: whether 24-hour format is desired for the time display.
Description: Creates a new MateDateEdit widget which can be used to provide an easy to use way for entering dates and times. If @the_time is 0 then current time is used.
Returns: a new MateDateEdit widget.
Definition at line 874 of file mate-dateedit.c.
References MATE_DATE_EDIT_24_HR, mate_date_edit_new_flags(), and MATE_DATE_EDIT_SHOW_TIME.
mate_date_edit_new_flags()
GtkWidget * mate_date_edit_new_flags (time_t the_time, MateDateEditFlags flags)
mate_date_edit_new_flags: @the_time: The initial time for the date editor. @flags: A bitmask of MateDateEditFlags values.
Description: Creates a new MateDateEdit widget with the specified flags. If @the_time is 0 then current time is used.
Returns: the newly-created date editor widget.
Definition at line 892 of file mate-dateedit.c.
References mate_date_edit_construct(), MATE_TYPE_DATE_EDIT, and NULL.
Referenced by mate_date_edit_new().
mate_date_edit_set_flags()
void mate_date_edit_set_flags (MateDateEdit * gde, MateDateEditFlags flags)
mate_date_edit_set_flags: @gde: The date editor widget whose flags should be changed. @flags: The new bitmask of MateDateEditFlags values.
Changes the display flags on an existing date editor widget.
Definition at line 1046 of file mate-dateedit.c.
References _MateDateEdit::_priv, MATE_DATE_EDIT_24_HR, MATE_DATE_EDIT_SHOW_TIME, MATE_DATE_EDIT_WEEK_STARTS_ON_MONDAY, MATE_IS_DATE_EDIT, and NULL.
Referenced by mate_date_edit_construct().
mate_date_edit_set_popup_range()
void mate_date_edit_set_popup_range (MateDateEdit * gde, int low_hour, int up_hour)
mate_date_edit_set_popup_range: @gde: The MateDateEdit widget @low_hour: low boundary for the time-range display popup. @up_hour: upper boundary for the time-range display popup.
Sets the range of times that will be provide by the time popup selectors.
Definition at line 747 of file mate-dateedit.c.
References _MateDateEdit::_priv, and NULL.
mate_date_edit_set_time()
void mate_date_edit_set_time (MateDateEdit * gde, time_t the_time)
mate_date_edit_set_time: @gde: the MateDateEdit widget @the_time: The time and date that should be set on the widget
Description: Changes the displayed date and time in the MateDateEdit widget to be the one represented by @the_time. If @the_time is 0 then current time is used.
Definition at line 689 of file mate-dateedit.c.
References _MateDateEdit::_priv, MATE_DATE_EDIT_24_HR, MATE_DATE_EDIT_DISPLAY_SECONDS, and NULL.
Referenced by mate_date_edit_construct().