MATE Desktop Environment: mate-desktop-item-edit.c File Reference
mate-desktop-item-edit.c File Reference
#include <config.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <libpanel-util/panel-error.h>
#include <libpanel-util/panel-keyfile.h>
#include "panel-ditem-editor.h"
#include "panel-icon-names.h"
#include "panel-util.h"
#include "applet.h"
#include "panel-config-global.h"
#include "panel-lockdown.h"
Functions
GSList * mate_panel_applet_list_applets (void)
gboolean panel_global_config_get_tooltips_enabled (void)
gboolean panel_lockdown_get_disable_lock_screen (void)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 96 of file mate-desktop-item-edit.c.
References _, error, NULL, PANEL_DITEM_EDITOR, panel_ditem_editor_new(), panel_ditem_editor_new_directory(), panel_ditem_register_save_uri_func(), PANEL_ICON_LAUNCHER, and type.
mate_panel_applet_list_applets()
GSList * mate_panel_applet_list_applets (void)
Definition at line 16 of file mate-desktop-item-edit.c.
References NULL.
panel_global_config_get_tooltips_enabled()
gboolean panel_global_config_get_tooltips_enabled (void)
Definition at line 18 of file mate-desktop-item-edit.c.
References FALSE.
panel_lockdown_get_disable_lock_screen()
gboolean panel_lockdown_get_disable_lock_screen (void)
Definition at line 20 of file mate-desktop-item-edit.c.
References FALSE.
Referenced by panel_lock_screen_action(), and panel_lock_screen_action_available().