MATE Desktop Environment: main.c File Reference
main.c File Reference
#include <config.h>
#include <string.h>
#include <signal.h>
#include <sys/wait.h>
#include <glib/gi18n.h>
#include <libegg/eggdesktopfile.h>
#include <libegg/eggsmclient.h>
#include <libpanel-util/panel-cleanup.h>
#include <libpanel-util/panel-glib.h>
#include "panel-profile.h"
#include "panel-config-global.h"
#include "panel-shell.h"
#include "panel-multimonitor.h"
#include "panel-session.h"
#include "panel-schemas.h"
#include "panel-stock-icons.h"
#include "panel-lockdown.h"
#include "panel-icon-names.h"
#include "panel-reset.h"
#include "panel-run-dialog.h"
Functions
int main (int argc, char **argv)
Variables
GSList * panels = NULL
GSList * panel_list = NULL
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 75 of file mate-panel/mate-panel/main.c.
References _, egg_get_desktop_file(), egg_set_desktop_file(), egg_sm_client_get_option_group(), EGG_SM_CLIENT_MODE_DISABLED, egg_sm_client_set_mode(), error, GDK_IS_X11_DISPLAY, NULL, panel_action_protocol_init(), panel_cleanup_do(), PANEL_DEFAULT_LAYOUT, panel_g_lookup_in_applications_dirs(), panel_global_config_load(), PANEL_ICON_PANEL, panel_init_stock_icons_and_items(), panel_lockdown_finalize(), panel_lockdown_init(), panel_multimonitor_init(), panel_profile_load(), panel_profile_settings_load(), panel_reset(), panel_run_dialog_present(), panel_run_dialog_quit_on_destroy(), PANEL_SCHEMA, panel_session_init(), panel_shell_register(), panel_widget_add_forbidden(), panels, TRUE, and xstuff_init().
Variable Documentation
panel_list
GSList* panel_list = NULL
Definition at line 47 of file mate-panel/mate-panel/main.c.
Referenced by panel_setup().
panels
GSList* panels = NULL
Definition at line 46 of file mate-panel/mate-panel/main.c.
Referenced by main(), mate_panel_applet_register(), and menu_get_panel().