MATE Desktop Environment: matekbd-status.c File Reference
matekbd-status.c File Reference
#include <config.h>
#include <memory.h>
#include <cairo.h>
#include <gdk/gdkkeysyms.h>
#include <gdk/gdkx.h>
#include <glib/gi18n-lib.h>
#include <glib/gprintf.h>
#include <matekbd-status.h>
#include <matekbd-desktop-config.h>
#include <matekbd-indicator-config.h>
Macros
#define ForAllIndicators()
#define NextIndicator()
Typedefs
typedef struct _gki_globals gki_globals
Functions
gchar * matekbd_indicator_extract_layout_name (int group, XklEngine *engine, MatekbdKeyboardConfig *kbd_cfg, gchar **short_group_names, gchar **full_group_names)
gchar * matekbd_indicator_create_label_title (int group, GHashTable **ln2cnt_map, gchar *layout_name)
void matekbd_status_reinit_ui (MatekbdStatus *gki)
GtkStatusIcon * matekbd_status_new (void)
XklEngine * matekbd_status_get_xkl_engine ()
gchar ** matekbd_status_get_group_names ()
gchar * matekbd_status_get_image_filename (guint group)
void matekbd_status_set_angle (MatekbdStatus *gki, gdouble angle)
Macro Definition Documentation
ForAllIndicators
#define ForAllIndicators ()
Value:
    { \
        GSList* cur; \
        for (cur = globals.widget_instances; cur != NULL; cur = cur->next) { \
            MatekbdStatus * gki = (MatekbdStatus*)cur->data;
Definition at line 73 of file matekbd-status.c.
NextIndicator
#define NextIndicator ()
Value:
        } \
    }
Definition at line 78 of file matekbd-status.c.
Typedef Documentation
gki_globals
typedef struct _gki_globals gki_globals
Function Documentation
matekbd_indicator_create_label_title()
gchar * matekbd_indicator_create_label_title (int group, GHashTable ** ln2cnt_map, gchar * layout_name) extern
Definition at line 323 of file matekbd-indicator.c.
References NULL.
matekbd_indicator_extract_layout_name()
gchar * matekbd_indicator_extract_layout_name (int group, XklEngine * engine, MatekbdKeyboardConfig * kbd_cfg, gchar ** short_group_names, gchar ** full_group_names) extern
Definition at line 279 of file matekbd-indicator.c.
References engine, _MatekbdKeyboardConfig::layouts_variants, matekbd_keyboard_config_split_items(), and NULL.
matekbd_status_get_group_names()
gchar ** matekbd_status_get_group_names (void)
matekbd_status_get_group_names:
Returns: (transfer none) (array zero-terminated=1): List of group names
Definition at line 858 of file matekbd-status.c.
matekbd_status_get_image_filename()
gchar * matekbd_status_get_image_filename (guint group)
Definition at line 864 of file matekbd-status.c.
References matekbd_indicator_config_get_images_file(), and NULL.
matekbd_status_get_xkl_engine()
XklEngine * matekbd_status_get_xkl_engine (void)
matekbd_status_get_xkl_engine:
Returns: (transfer none): The engine shared by all MatekbdStatus objects
Definition at line 847 of file matekbd-status.c.
matekbd_status_new()
GtkStatusIcon * matekbd_status_new (void)
Definition at line 835 of file matekbd-status.c.
References matekbd_status_get_type(), and NULL.
Referenced by main().
matekbd_status_reinit_ui()
void matekbd_status_reinit_ui (MatekbdStatus * gki)
Definition at line 405 of file matekbd-status.c.
matekbd_status_set_angle()
void matekbd_status_set_angle (MatekbdStatus * gki, gdouble angle)
Definition at line 874 of file matekbd-status.c.
References _MatekbdStatus::priv.