MATE Desktop Environment: parser.c File Reference
parser.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include <string.h>
#include "parser.h"
#include "parserfunc.h"
#include "mp-equation.h"
Functions
ParserState * p_create_parser (const gchar *input, MPEquationOptions *options)
guint p_parse (ParserState *state)
void p_destroy_parser (ParserState *state)
Function Documentation
p_create_parser()
ParserState * p_create_parser (const gchar * input, MPEquationOptions * options)
Definition at line 229 of file mate-calc/src/parser.c.
References l_create_lexer(), and NULL.
Referenced by mp_equation_parse().
p_destroy_parser()
void p_destroy_parser (ParserState * state)
Definition at line 289 of file mate-calc/src/parser.c.
References l_destroy_lexer().
Referenced by mp_equation_parse().
p_parse()
guint p_parse (ParserState * state)
Definition at line 247 of file mate-calc/src/parser.c.
References l_get_next_token(), l_insert_all_tokens(), mp_free(), mp_new(), mp_set_from_mp(), PARSER_ERR_INVALID, PARSER_ERR_NONE, PL_EOS, set_error(), LexerToken::string, T_ASSIGN, and LexerToken::token_type.
Referenced by mp_equation_parse().