MATE Desktop Environment: mate-mdi-child.c File Reference
mate-mdi-child.c File Reference
#include <config.h>
#include <libmate/mate-macros.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <glib/gi18n-lib.h>
#include "mate-app.h"
#include "mate-app-helper.h"
#include "mate-mdi-child.h"
#include "mate-mdi.h"
Functions
void _mate_mdi_child_list_menu_remove_item (MateMDI *, MateMDIChild *)
void _mate_mdi_child_list_menu_add_item (MateMDI *, MateMDIChild *)
MATE_CLASS_BOILERPLATE (MateMDIChild, mate_mdi_child, GtkObject, GTK_TYPE_OBJECT)
GtkWidget * mate_mdi_child_add_view (MateMDIChild *mdi_child)
void mate_mdi_child_remove_view (MateMDIChild *mdi_child, GtkWidget *view)
. @name is duplicated and stored
in @mdi_child. If @mdi_child has already been added to MateMDI, it also takes care of updating it.
void mate_mdi_child_set_name (MateMDIChild *mdi_child, const gchar *name)
void mate_mdi_child_set_menu_template (MateMDIChild *mdi_child, MateUIInfo *menu_tmpl)
Function Documentation
_mate_mdi_child_list_menu_add_item()
void _mate_mdi_child_list_menu_add_item (MateMDI * mdi, MateMDIChild * child)
Definition at line 470 of file mate-mdi.c.
References _MateMDI::child_list_path, item, label, MATE_APP, mate_app_find_menu_pos(), MATE_MDI_CHILD_KEY, _MateApp::menubar, NULL, and _MateMDI::windows.
Referenced by mate_mdi_add_child(), and mate_mdi_child_set_name().
_mate_mdi_child_list_menu_remove_item()
void _mate_mdi_child_list_menu_remove_item (MateMDI * mdi, MateMDIChild * child)
Definition at line 440 of file mate-mdi.c.
References _MateMDI::child_list_path, item, MATE_APP, mate_app_find_menu_pos(), _MateApp::menubar, NULL, and _MateMDI::windows.
Referenced by mate_mdi_child_set_name(), and mate_mdi_remove_child().
MATE_CLASS_BOILERPLATE()
MATE_CLASS_BOILERPLATE (MateMDIChild , mate_mdi_child , GtkObject , GTK_TYPE_OBJECT)
Definition at line 51 of file mate-mdi-child.c.
References _MateMDIChildClass::create_menus, _MateMDIChildClass::create_view, _MateMDIChildClass::get_config_string, NULL, and _MateMDIChildClass::set_label.
mate_mdi_child_add_view()
GtkWidget * mate_mdi_child_add_view (MateMDIChild * mdi_child)
mate_mdi_child_add_view: @mdi_child: A pointer to a MateMDIChild object.
Description: Creates a new view of a child (a GtkWidget) adds it to the list of the views and returns a pointer to it. Virtual function that has to be specified for classes derived from MateMDIChild is used to create the new view.
Return value: A pointer to the new view.
Definition at line 151 of file mate-mdi-child.c.
References NULL, and _MateMDIChild::views.
Referenced by mate_mdi_add_toplevel_view(), and mate_mdi_add_view().
mate_mdi_child_remove_view()
void mate_mdi_child_remove_view (MateMDIChild * mdi_child, GtkWidget * view)
mate_mdi_child_remove_view: @mdi_child: A pointer to a MateMDIChild object. @view: View to be removed.
Description: Removes view @view from the list of @mdi_child's views and unrefs it.
Definition at line 175 of file mate-mdi-child.c.
References _MateMDIChild::views.
Referenced by mate_mdi_add_toplevel_view(), mate_mdi_add_view(), and mate_mdi_remove_view().
mate_mdi_child_set_menu_template()
void mate_mdi_child_set_menu_template (MateMDIChild * mdi_child, MateUIInfo * menu_tmpl)
mate_mdi_child_set_menu_template: @mdi_child: A pointer to a MateMDIChild object. @menu_tmpl: A MateUIInfo array describing the child specific menus.
Description: Sets the template for menus that are added and removed when differrent children get activated. This way, each child can modify the MDI menubar to suit its needs. If no template is set, the create_menus virtual function will be used for creating these menus (it has to return a GList of menu items). If no such function is specified, the menubar will be unchanged by MDI children.
Definition at line 221 of file mate-mdi-child.c.
References _MateMDIChild::menu_template.
mate_mdi_child_set_name()
void mate_mdi_child_set_name (MateMDIChild * mdi_child, const gchar * name)
Definition at line 192 of file mate-mdi-child.c.
References _mate_mdi_child_list_menu_add_item(), _mate_mdi_child_list_menu_remove_item(), MATE_MDI, mate_mdi_update_child(), name, _MateMDIChild::name, and _MateMDIChild::parent.