MATE Desktop Environment: parser.h File Reference
parser.h File Reference
#include <lexer.h>
#include "mp-equation.h"
#include "mp.h"
Classes
struct parse_node
struct parser_state
Typedefs
typedef struct parse_node ParseNode
typedef struct parser_state ParserState
Enumerations
enum Associativity { LEFT_ASSOCIATIVE , RIGHT_ASSOCIATIVE }
enum Precedence {
P_Unknown = 0 , P_AddSubtract =1 , P_Multiply =2 , P_Mod =3 ,
P_Divide =4 , P_Not =5 , P_Root =6 , P_Function =7 ,
P_Boolean =8 , P_Percentage =9 , P_UnaryMinus =10 , P_Power =10 ,
P_Factorial =11 , P_NumberVariable =12 , P_Depth
}
Functions
ParserState * p_create_parser (const gchar *, MPEquationOptions *)
void p_destroy_parser (ParserState *)
guint p_parse (ParserState *)
Typedef Documentation
ParseNode
typedef struct parse_node ParseNode
ParserState
typedef struct parser_state ParserState
Enumeration Type Documentation
Associativity
enum Associativity
Enumerator
LEFT_ASSOCIATIVE
RIGHT_ASSOCIATIVE
Definition at line 10 of file mate-calc/src/parser.h.
Precedence
enum Precedence
Enumerator
P_Unknown
P_AddSubtract
P_Multiply
P_Mod
P_Divide
P_Not
P_Root
P_Function
P_Boolean
P_Percentage
P_UnaryMinus
P_Power
P_Factorial
P_NumberVariable
P_Depth
Definition at line 17 of file mate-calc/src/parser.h.
Function Documentation
p_create_parser()
ParserState * p_create_parser (const gchar * input, MPEquationOptions * options)
Definition at line 229 of file mate-calc/src/parser.c.
References l_create_lexer(), and NULL.
Referenced by mp_equation_parse().
p_destroy_parser()
void p_destroy_parser (ParserState * state)
Definition at line 289 of file mate-calc/src/parser.c.
References l_destroy_lexer().
Referenced by mp_equation_parse().
p_parse()
guint p_parse (ParserState * state)
Definition at line 247 of file mate-calc/src/parser.c.
References l_get_next_token(), l_insert_all_tokens(), mp_free(), mp_new(), mp_set_from_mp(), PARSER_ERR_INVALID, PARSER_ERR_NONE, PL_EOS, set_error(), LexerToken::string, T_ASSIGN, and LexerToken::token_type.
Referenced by mp_equation_parse().