MATE Desktop Environment: mate-mdi-child.h File Reference
mate-mdi-child.h File Reference
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include "libmateui/mate-app.h"
#include "libmateui/mate-app-helper.h"
Classes
struct _MateMDIChild
struct _MateMDIChildClass
Macros
#define MATE_TYPE_MDI_CHILD (mate_mdi_child_get_type ())
#define MATE_MDI_CHILD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_MDI_CHILD, MateMDIChild))
#define MATE_MDI_CHILD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_MDI_CHILD, MateMDIChildClass))
#define MATE_IS_MDI_CHILD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_MDI_CHILD))
#define MATE_IS_MDI_CHILD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_MDI_CHILD))
#define MATE_MDI_CHILD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_MDI_CHILD, MateMDIChildClass))
Typedefs
typedef struct _MateMDIChild MateMDIChild
typedef struct _MateMDIChildClass MateMDIChildClass
typedef GtkWidget *(* MateMDIChildViewCreator) (MateMDIChild *, gpointer)
typedef GList *(* MateMDIChildMenuCreator) (MateMDIChild *, GtkWidget *, gpointer)
typedef gchar *(* MateMDIChildConfigFunc) (MateMDIChild *, gpointer)
typedef GtkWidget *(* MateMDIChildLabelFunc) (MateMDIChild *, GtkWidget *, gpointer)
Functions
GType mate_mdi_child_get_type (void)
GtkWidget * mate_mdi_child_add_view (MateMDIChild *mdi_child)
void mate_mdi_child_remove_view (MateMDIChild *mdi_child, GtkWidget *view)
void mate_mdi_child_set_name (MateMDIChild *mdi_child, const gchar *name)
void mate_mdi_child_set_menu_template (MateMDIChild *mdi_child, MateUIInfo *menu_tmpl)
Macro Definition Documentation
MATE_IS_MDI_CHILD
#define MATE_IS_MDI_CHILD (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_MDI_CHILD))
Definition at line 42 of file mate-mdi-child.h.
MATE_IS_MDI_CHILD_CLASS
#define MATE_IS_MDI_CHILD_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_MDI_CHILD))
Definition at line 43 of file mate-mdi-child.h.
MATE_MDI_CHILD
#define MATE_MDI_CHILD (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_MDI_CHILD, MateMDIChild))
Definition at line 40 of file mate-mdi-child.h.
MATE_MDI_CHILD_CLASS
#define MATE_MDI_CHILD_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_MDI_CHILD, MateMDIChildClass))
Definition at line 41 of file mate-mdi-child.h.
MATE_MDI_CHILD_GET_CLASS
#define MATE_MDI_CHILD_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_MDI_CHILD, MateMDIChildClass))
Definition at line 44 of file mate-mdi-child.h.
MATE_TYPE_MDI_CHILD
#define MATE_TYPE_MDI_CHILD (mate_mdi_child_get_type ())
Definition at line 39 of file mate-mdi-child.h.
Typedef Documentation
MateMDIChild
typedef struct _MateMDIChild MateMDIChild
Definition at line 46 of file mate-mdi-child.h.
MateMDIChildClass
typedef struct _MateMDIChildClass MateMDIChildClass
Definition at line 47 of file mate-mdi-child.h.
MateMDIChildConfigFunc
typedef gchar *(* MateMDIChildConfigFunc) (MateMDIChild *, gpointer)
Definition at line 73 of file mate-mdi-child.h.
MateMDIChildLabelFunc
typedef GtkWidget *(* MateMDIChildLabelFunc) (MateMDIChild *, GtkWidget *, gpointer)
Definition at line 74 of file mate-mdi-child.h.
MateMDIChildMenuCreator
typedef GList *(* MateMDIChildMenuCreator) (MateMDIChild *, GtkWidget *, gpointer)
Definition at line 72 of file mate-mdi-child.h.
MateMDIChildViewCreator
typedef GtkWidget *(* MateMDIChildViewCreator) (MateMDIChild *, gpointer)
Definition at line 71 of file mate-mdi-child.h.
Function Documentation
mate_mdi_child_add_view()
GtkWidget * mate_mdi_child_add_view (MateMDIChild * mdi_child)
mate_mdi_child_add_view: @mdi_child: A pointer to a MateMDIChild object.
Description: Creates a new view of a child (a GtkWidget) adds it to the list of the views and returns a pointer to it. Virtual function that has to be specified for classes derived from MateMDIChild is used to create the new view.
Return value: A pointer to the new view.
Definition at line 151 of file mate-mdi-child.c.
References NULL, and _MateMDIChild::views.
Referenced by mate_mdi_add_toplevel_view(), and mate_mdi_add_view().
mate_mdi_child_get_type()
GType mate_mdi_child_get_type (void)
mate_mdi_child_remove_view()
void mate_mdi_child_remove_view (MateMDIChild * mdi_child, GtkWidget * view)
mate_mdi_child_remove_view: @mdi_child: A pointer to a MateMDIChild object. @view: View to be removed.
Description: Removes view @view from the list of @mdi_child's views and unrefs it.
Definition at line 175 of file mate-mdi-child.c.
References _MateMDIChild::views.
Referenced by mate_mdi_add_toplevel_view(), mate_mdi_add_view(), and mate_mdi_remove_view().
mate_mdi_child_set_menu_template()
void mate_mdi_child_set_menu_template (MateMDIChild * mdi_child, MateUIInfo * menu_tmpl)
mate_mdi_child_set_menu_template: @mdi_child: A pointer to a MateMDIChild object. @menu_tmpl: A MateUIInfo array describing the child specific menus.
Description: Sets the template for menus that are added and removed when differrent children get activated. This way, each child can modify the MDI menubar to suit its needs. If no template is set, the create_menus virtual function will be used for creating these menus (it has to return a GList of menu items). If no such function is specified, the menubar will be unchanged by MDI children.
Definition at line 221 of file mate-mdi-child.c.
References _MateMDIChild::menu_template.
mate_mdi_child_set_name()
void mate_mdi_child_set_name (MateMDIChild * mdi_child, const gchar * name)
Definition at line 192 of file mate-mdi-child.c.
References _mate_mdi_child_list_menu_add_item(), _mate_mdi_child_list_menu_remove_item(), MATE_MDI, mate_mdi_update_child(), name, _MateMDIChild::name, and _MateMDIChild::parent.