MATE Desktop Environment: mate-messagebox.c File Reference
mate-messagebox.c File Reference
#include <config.h>
#include <libmate/mate-macros.h>
#include <stdarg.h>
#include <glib/gi18n-lib.h>
#include "mate-messagebox.h"
#include <libmate/mate-triggers.h>
#include <libmate/mate-util.h>
#include <string.h>
#include <gtk/gtk.h>
#include <libmateui/mate-uidefs.h>
Macros
#define MATE_MESSAGE_BOX_WIDTH 425
#define MATE_MESSAGE_BOX_HEIGHT 125
Functions
MATE_CLASS_BOILERPLATE (MateMessageBox, mate_message_box, MateDialog, MATE_TYPE_DIALOG)
void mate_message_box_construct (MateMessageBox *messagebox, const gchar *message, const gchar *message_box_type, const gchar **buttons)
GtkWidget * mate_message_box_new (const gchar *message, const gchar *message_box_type,...)
GtkWidget * mate_message_box_newv (const gchar *message, const gchar *message_box_type, const gchar **buttons)
Macro Definition Documentation
MATE_MESSAGE_BOX_HEIGHT
#define MATE_MESSAGE_BOX_HEIGHT 125
Definition at line 42 of file mate-messagebox.c.
MATE_MESSAGE_BOX_WIDTH
#define MATE_MESSAGE_BOX_WIDTH 425
Definition at line 41 of file mate-messagebox.c.
Function Documentation
MATE_CLASS_BOILERPLATE()
MATE_CLASS_BOILERPLATE (MateMessageBox , mate_message_box , MateDialog , MATE_TYPE_DIALOG)
Definition at line 50 of file mate-messagebox.c.
mate_message_box_construct()
void mate_message_box_construct (MateMessageBox * messagebox, const gchar * message, const gchar * message_box_type, const gchar ** buttons)
mate_message_box_construct: @messagebox: The message box to construct @message: The message to be displayed. @message_box_type: The type of the message @buttons: a NULL terminated array with the buttons to insert.
For language bindings or subclassing, from C use mate_message_box_new or mate_message_box_newv
Definition at line 82 of file mate-messagebox.c.
References _, buttons, FALSE, label, MATE_DIALOG, mate_dialog_constructv(), mate_dialog_set_close(), MATE_IS_MESSAGE_BOX, MATE_MESSAGE_BOX_ERROR, MATE_MESSAGE_BOX_INFO, MATE_MESSAGE_BOX_QUESTION, MATE_MESSAGE_BOX_WARNING, MATE_PAD, message(), NULL, and TRUE.
Referenced by mate_message_box_new(), and mate_message_box_newv().
mate_message_box_new()
GtkWidget * mate_message_box_new (const gchar * message, const gchar * message_box_type, ...)
mate_message_box_new: @message: The message to be displayed. @message_box_type: The type of the message ...: A NULL terminated list of strings to use in each button.
Creates a dialog box of type @message_box_type with @message. A number of buttons are inserted on it. You can use the MATE stock identifiers to create mate-stock-buttons.
Returns a widget that has the dialog box.
Definition at line 186 of file mate-messagebox.c.
References buttons, data, MATE_DIALOG, mate_dialog_append_button(), mate_message_box_construct(), MATE_TYPE_MESSAGE_BOX, message(), NULL, and TRUE.
mate_message_box_newv()
GtkWidget * mate_message_box_newv (const gchar * message, const gchar * message_box_type, const gchar ** buttons)
mate_message_box_newv: @message: The message to be displayed. @message_box_type: The type of the message @buttons: a NULL terminated array with the buttons to insert.
Creates a dialog box of type @message_box_type with @message. A number of buttons are inserted on it, the messages come from the @buttons array. You can use the MATE stock identifiers to create mate-stock-buttons. The buttons array can be NULL if you wish to add buttons yourself later.
Returns a widget that has the dialog box.
Definition at line 240 of file mate-messagebox.c.
References buttons, mate_message_box_construct(), MATE_TYPE_MESSAGE_BOX, message(), and NULL.