MATE Desktop Environment: matekbd-indicator.h File Reference
matekbd-indicator.h File Reference
#include <gtk/gtk.h>
#include <libxklavier/xklavier.h>
Classes
struct _MatekbdIndicator
struct _MatekbdIndicatorClass
Macros
#define MATEKBD_TYPE_INDICATOR (matekbd_indicator_get_type ())
#define MATEKBD_INDICATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATEKBD_TYPE_INDICATOR, MatekbdIndicator))
#define MATEKBD_INDICATOR_CLASS(obj) (G_TYPE_CHECK_CLASS_CAST ((obj), MATEKBD_TYPE_INDICATOR, MatekbdIndicatorClass))
#define MATEKBD_IS_INDICATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATEKBD_TYPE_INDICATOR))
#define MATEKBD_IS_INDICATOR_CLASS(obj) (G_TYPE_CHECK_CLASS_TYPE ((obj), MATEKBD_TYPE_INDICATOR))
#define MATEKBD_INDICATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATEKBD_TYPE_INDICATOR, MatekbdIndicatorClass))
Typedefs
typedef struct _MatekbdIndicator MatekbdIndicator
typedef struct _MatekbdIndicatorPrivate MatekbdIndicatorPrivate
typedef struct _MatekbdIndicatorClass MatekbdIndicatorClass
Functions
GType matekbd_indicator_get_type (void)
GtkWidget * matekbd_indicator_new (void)
void matekbd_indicator_reinit_ui (MatekbdIndicator *gki)
void matekbd_indicator_set_angle (MatekbdIndicator *gki, gdouble angle)
XklEngine * matekbd_indicator_get_xkl_engine (void)
gchar ** matekbd_indicator_get_group_names (void)
gchar * matekbd_indicator_get_image_filename (guint group)
gdouble matekbd_indicator_get_max_width_height_ratio (void)
void matekbd_indicator_set_parent_tooltips (MatekbdIndicator *gki, gboolean ifset)
void matekbd_indicator_set_tooltips_format (const gchar str[])
Macro Definition Documentation
MATEKBD_INDICATOR
#define MATEKBD_INDICATOR (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATEKBD_TYPE_INDICATOR, MatekbdIndicator))
Definition at line 36 of file matekbd-indicator.h.
MATEKBD_INDICATOR_CLASS
#define MATEKBD_INDICATOR_CLASS (obj) (G_TYPE_CHECK_CLASS_CAST ((obj), MATEKBD_TYPE_INDICATOR, MatekbdIndicatorClass))
Definition at line 37 of file matekbd-indicator.h.
MATEKBD_INDICATOR_GET_CLASS
#define MATEKBD_INDICATOR_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATEKBD_TYPE_INDICATOR, MatekbdIndicatorClass))
Definition at line 40 of file matekbd-indicator.h.
MATEKBD_IS_INDICATOR
#define MATEKBD_IS_INDICATOR (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATEKBD_TYPE_INDICATOR))
Definition at line 38 of file matekbd-indicator.h.
MATEKBD_IS_INDICATOR_CLASS
#define MATEKBD_IS_INDICATOR_CLASS (obj) (G_TYPE_CHECK_CLASS_TYPE ((obj), MATEKBD_TYPE_INDICATOR))
Definition at line 39 of file matekbd-indicator.h.
MATEKBD_TYPE_INDICATOR
#define MATEKBD_TYPE_INDICATOR (matekbd_indicator_get_type ())
Definition at line 35 of file matekbd-indicator.h.
Typedef Documentation
MatekbdIndicator
typedef struct _MatekbdIndicator MatekbdIndicator
Definition at line 31 of file matekbd-indicator.h.
MatekbdIndicatorClass
typedef struct _MatekbdIndicatorClass MatekbdIndicatorClass
Definition at line 33 of file matekbd-indicator.h.
MatekbdIndicatorPrivate
typedef struct _MatekbdIndicatorPrivate MatekbdIndicatorPrivate
Definition at line 32 of file matekbd-indicator.h.
Function Documentation
matekbd_indicator_get_group_names()
gchar ** matekbd_indicator_get_group_names (void) extern
matekbd_indicator_get_group_names:
Returns: (transfer none) (array zero-terminated=1): List of group names
Definition at line 877 of file matekbd-indicator.c.
matekbd_indicator_get_image_filename()
gchar * matekbd_indicator_get_image_filename (guint group) extern
Definition at line 883 of file matekbd-indicator.c.
References matekbd_indicator_config_get_images_file(), and NULL.
matekbd_indicator_get_max_width_height_ratio()
gdouble matekbd_indicator_get_max_width_height_ratio (void) extern
Definition at line 893 of file matekbd-indicator.c.
References NULL.
matekbd_indicator_get_type()
GType matekbd_indicator_get_type (void) extern
Referenced by matekbd_indicator_new().
matekbd_indicator_get_xkl_engine()
XklEngine * matekbd_indicator_get_xkl_engine (void) extern
matekbd_indicator_get_xkl_engine:
Returns: (transfer none): The engine shared by all MatekbdIndicator objects
Definition at line 866 of file matekbd-indicator.c.
matekbd_indicator_new()
GtkWidget * matekbd_indicator_new (void) extern
Definition at line 838 of file matekbd-indicator.c.
References matekbd_indicator_get_type(), and NULL.
Referenced by main().
matekbd_indicator_reinit_ui()
void matekbd_indicator_reinit_ui (MatekbdIndicator * gki) extern
Definition at line 454 of file matekbd-indicator.c.
matekbd_indicator_set_angle()
void matekbd_indicator_set_angle (MatekbdIndicator * gki, gdouble angle) extern
Definition at line 912 of file matekbd-indicator.c.
References _MatekbdIndicator::priv.
matekbd_indicator_set_parent_tooltips()
void matekbd_indicator_set_parent_tooltips (MatekbdIndicator * gki, gboolean ifset) extern
Definition at line 845 of file matekbd-indicator.c.
References _MatekbdIndicator::priv.
Referenced by main().
matekbd_indicator_set_tooltips_format()
void matekbd_indicator_set_tooltips_format (const gchar str[]) extern
Definition at line 852 of file matekbd-indicator.c.
References ForAllIndicators, and NextIndicator.
Referenced by main().