MATE Desktop Environment: mate-thumbnail.c File Reference
mate-thumbnail.c File Reference
#include <config.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <unistd.h>
#include <stdlib.h>
#include <dirent.h>
#include <time.h>
#include <math.h>
#include <string.h>
#include <glib.h>
#include <stdio.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <libmate/mate-macros.h>
#include <libmate/mate-init.h>
#include <gio/gio.h>
#include "mate-thumbnail.h"
#include "mate-mateconf-ui.h"
#include <mateconf/mateconf.h>
#include <mateconf/mateconf-client.h>
#include <glib/gstdio.h>
Macros
#define GDK_PIXBUF_ENABLE_BACKEND
#define SECONDS_BETWEEN_STATS 10
#define LOAD_BUFFER_SIZE 4096
#define parent_class mate_thumbnail_factory_parent_class
Functions
G_DEFINE_TYPE (MateThumbnailFactory, mate_thumbnail_factory, G_TYPE_OBJECT)
MateThumbnailFactory * mate_thumbnail_factory_new (MateThumbnailSize size)
char * mate_thumbnail_factory_lookup (MateThumbnailFactory *factory, const char *uri, time_t mtime)
gboolean mate_thumbnail_factory_has_valid_failed_thumbnail (MateThumbnailFactory *factory, const char *uri, time_t mtime)
gboolean mate_thumbnail_factory_can_thumbnail (MateThumbnailFactory *factory, const char *uri, const char *mime_type, time_t mtime)
GdkPixbuf * mate_gdk_pixbuf_new_from_uri_at_scale (const char *uri, gint width, gint height, gboolean preserve_aspect_ratio)
GdkPixbuf * mate_thumbnail_factory_generate_thumbnail (MateThumbnailFactory *factory, const char *uri, const char *mime_type)
void mate_thumbnail_factory_save_thumbnail (MateThumbnailFactory *factory, GdkPixbuf *thumbnail, const char *uri, time_t original_mtime)
void mate_thumbnail_factory_create_failed_thumbnail (MateThumbnailFactory *factory, const char *uri, time_t mtime)
char * mate_thumbnail_md5 (const char *uri)
char * mate_thumbnail_path_for_uri (const char *uri, MateThumbnailSize size)
gboolean mate_thumbnail_has_uri (GdkPixbuf *pixbuf, const char *uri)
gboolean mate_thumbnail_is_valid (GdkPixbuf *pixbuf, const char *uri, time_t mtime)
Macro Definition Documentation
GDK_PIXBUF_ENABLE_BACKEND
#define GDK_PIXBUF_ENABLE_BACKEND
Definition at line 39 of file mate-thumbnail.c.
LOAD_BUFFER_SIZE
#define LOAD_BUFFER_SIZE 4096
Definition at line 52 of file mate-thumbnail.c.
parent_class
#define parent_class mate_thumbnail_factory_parent_class
SECONDS_BETWEEN_STATS
#define SECONDS_BETWEEN_STATS 10
Definition at line 51 of file mate-thumbnail.c.
Function Documentation
G_DEFINE_TYPE()
G_DEFINE_TYPE (MateThumbnailFactory , mate_thumbnail_factory , G_TYPE_OBJECT)
Definition at line 76 of file mate-thumbnail.c.
References G_OBJECT_CLASS(), MATE_THUMBNAIL_FACTORY, NULL, parent_class, and _MateThumbnailFactory::priv.
mate_gdk_pixbuf_new_from_uri_at_scale()
GdkPixbuf * mate_gdk_pixbuf_new_from_uri_at_scale (const char * uri, gint width, gint height, gboolean preserve_aspect_ratio)
mate_gdk_pixbuf_new_from_uri_at_scale: @uri: the uri of an image @width: The width the image should have or -1 to not constrain the width @height: The height the image should have or -1 to not constrain the height @preserve_aspect_ratio: TRUE to preserve the image's aspect ratio
Loads a GdkPixbuf from the image file @uri points to, scaling it to the desired size. If you pass -1 for @width or @height then the value specified in the file will be used.
When preserving aspect ratio, if both height and width are set the size is picked such that the scaled image fits in a width * height rectangle.
Return value: The loaded pixbuf, or NULL on error
Since: MATE 1.5.0
Definition at line 660 of file mate-thumbnail.c.
References FALSE, LOAD_BUFFER_SIZE, NULL, and TRUE.
Referenced by mate_thumbnail_factory_generate_thumbnail().
mate_thumbnail_factory_can_thumbnail()
gboolean mate_thumbnail_factory_can_thumbnail (MateThumbnailFactory * factory, const char * uri, const char * mime_type, time_t mtime)
mate_thumbnail_factory_can_thumbnail: @factory: a MateThumbnailFactory @uri: the uri of a file @mime_type: the mime type of the file @mtime: the mtime of the file
Returns TRUE if this MateIconFactory can (at least try) to thumbnail this file. Thumbnails or files with failed thumbnails won't be thumbnailed.
Usage of this function is threadsafe.
Return value: TRUE if the file can be thumbnailed.
Since: 2.2
Definition at line 498 of file mate-thumbnail.c.
References FALSE, mate_thumbnail_factory_has_valid_failed_thumbnail(), mime_type, NULL, and _MateThumbnailFactory::priv.
mate_thumbnail_factory_create_failed_thumbnail()
void mate_thumbnail_factory_create_failed_thumbnail (MateThumbnailFactory * factory, const char * uri, time_t mtime)
mate_thumbnail_factory_create_failed_thumbnail: @factory: a MateThumbnailFactory @uri: the uri of a file @mtime: the modification time of the file
Creates a failed thumbnail for the file so that we don't try to re-thumbnail the file later.
Usage of this function is threadsafe.
Since: 2.2
Definition at line 1095 of file mate-thumbnail.c.
References NULL, _MateThumbnailFactory::priv, and TRUE.
Referenced by mate_thumbnail_factory_save_thumbnail().
mate_thumbnail_factory_generate_thumbnail()
GdkPixbuf * mate_thumbnail_factory_generate_thumbnail (MateThumbnailFactory * factory, const char * uri, const char * mime_type)
mate_thumbnail_factory_generate_thumbnail: @factory: a MateThumbnailFactory @uri: the uri of a file @mime_type: the mime type of the file
Tries to generate a thumbnail for the specified file. If it succeeds it returns a pixbuf that can be used as a thumbnail.
Usage of this function is threadsafe.
Return value: thumbnail pixbuf if thumbnailing succeeded, NULL otherwise.
Since: 2.2
Definition at line 776 of file mate-thumbnail.c.
References mate_gdk_pixbuf_new_from_uri_at_scale(), mate_thumbnail_scale_down_pixbuf(), MATE_THUMBNAIL_SIZE_LARGE, MAX, mime_type, NULL, _MateThumbnailFactory::priv, and TRUE.
mate_thumbnail_factory_has_valid_failed_thumbnail()
gboolean mate_thumbnail_factory_has_valid_failed_thumbnail (MateThumbnailFactory * factory, const char * uri, time_t mtime)
mate_thumbnail_factory_has_valid_failed_thumbnail: @factory: a MateThumbnailFactory @uri: the uri of a file @mtime: the mtime of the file
Tries to locate an failed thumbnail for the file specified. Writing and looking for failed thumbnails is important to avoid to try to thumbnail e.g. broken images several times.
Usage of this function is threadsafe.
Return value: TRUE if there is a failed thumbnail for the file.
Since: 2.2
Definition at line 402 of file mate-thumbnail.c.
References FALSE, mate_thumbnail_is_valid(), NULL, and _MateThumbnailFactory::priv.
Referenced by mate_thumbnail_factory_can_thumbnail().
mate_thumbnail_factory_lookup()
char * mate_thumbnail_factory_lookup (MateThumbnailFactory * factory, const char * uri, time_t mtime)
mate_thumbnail_factory_lookup: @factory: a MateThumbnailFactory @uri: the uri of a file @mtime: the mtime of the file
Tries to locate an existing thumbnail for the file specified.
Usage of this function is threadsafe.
Return value: The absolute path of the thumbnail, or NULL if none exist.
Since: 2.2
Definition at line 338 of file mate-thumbnail.c.
References FALSE, mate_thumbnail_is_valid(), MATE_THUMBNAIL_SIZE_NORMAL, NULL, and _MateThumbnailFactory::priv.
mate_thumbnail_factory_new()
MateThumbnailFactory * mate_thumbnail_factory_new (MateThumbnailSize size)
mate_thumbnail_factory_new: @size: The thumbnail size to use
Creates a new MateThumbnailFactory.
This function must be called on the main thread.
Return value: a new MateThumbnailFactory
Since: 2.2
Definition at line 312 of file mate-thumbnail.c.
References MATE_TYPE_THUMBNAIL_FACTORY, NULL, and _MateThumbnailFactory::priv.
mate_thumbnail_factory_save_thumbnail()
void mate_thumbnail_factory_save_thumbnail (MateThumbnailFactory * factory, GdkPixbuf * thumbnail, const char * uri, time_t original_mtime)
mate_thumbnail_factory_save_thumbnail: @factory: a MateThumbnailFactory @thumbnail: the thumbnail as a pixbuf @uri: the uri of a file @original_mtime: the modification time of the original file
Saves @thumbnail at the right place. If the save fails a failed thumbnail is written.
Usage of this function is threadsafe.
Since: 2.2
Definition at line 985 of file mate-thumbnail.c.
References mate_thumbnail_factory_create_failed_thumbnail(), MATE_THUMBNAIL_SIZE_NORMAL, NULL, and _MateThumbnailFactory::priv.
mate_thumbnail_has_uri()
gboolean mate_thumbnail_has_uri (GdkPixbuf * pixbuf, const char * uri)
mate_thumbnail_has_uri: @pixbuf: an loaded thumbnail pixbuf @uri: a uri
Returns whether the thumbnail has the correct uri embedded in the Thumb::URI option in the png.
Return value: TRUE if the thumbnail is for @uri
Since: 2.2
Definition at line 1238 of file mate-thumbnail.c.
References FALSE.
mate_thumbnail_is_valid()
gboolean mate_thumbnail_is_valid (GdkPixbuf * pixbuf, const char * uri, time_t mtime)
mate_thumbnail_is_valid: @pixbuf: an loaded thumbnail #GdkPixbuf @uri: a uri @mtime: the mtime
Returns whether the thumbnail has the correct uri and mtime embedded in the png options.
Return value: TRUE if the thumbnail has the right @uri and @mtime
Since: 2.2
Definition at line 1264 of file mate-thumbnail.c.
References FALSE, and TRUE.
Referenced by mate_thumbnail_factory_has_valid_failed_thumbnail(), and mate_thumbnail_factory_lookup().
mate_thumbnail_md5()
char * mate_thumbnail_md5 (const char * uri)
mate_thumbnail_md5: @uri: an uri
Calculates the MD5 checksum of the uri. This can be useful if you want to manually handle thumbnail files.
Return value: A string with the MD5 digest of the uri string.
Since: 2.2
@Deprecated: 2.22: Use #GChecksum instead
Definition at line 1184 of file mate-thumbnail.c.
Referenced by mate_thumbnail_path_for_uri().
mate_thumbnail_path_for_uri()
char * mate_thumbnail_path_for_uri (const char * uri, MateThumbnailSize size)
mate_thumbnail_path_for_uri: @uri: an uri @size: a thumbnail size
Returns the filename that a thumbnail of size @size for @uri would have.
Return value: an absolute filename
Since: 2.2
Definition at line 1203 of file mate-thumbnail.c.
References mate_thumbnail_md5(), MATE_THUMBNAIL_SIZE_NORMAL, and NULL.