MATE Desktop Environment: matemenu-tree.h File Reference
matemenu-tree.h File Reference
#include <gio/gdesktopappinfo.h>
Classes
struct _MateMenuTreeClass
Macros
#define MATEMENU_TYPE_TREE (matemenu_tree_get_type ())
#define MATEMENU_TREE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MATEMENU_TYPE_TREE, MateMenuTree))
#define MATEMENU_TREE_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), MATEMENU_TYPE_TREE, MateMenuTreeClass))
#define MATEMENU_IS_TREE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MATEMENU_TYPE_TREE))
#define MATEMENU_IS_TREE_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MATEMENU_TYPE_TREE))
#define MATEMENU_TREE_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), G_TYPE_DESKTOP_APP_INFO, MateMenuTreeClass))
#define MATEMENU_TYPE_TREE_FLAGS (matemenu_tree_flags_get_type ())
Typedefs
typedef struct _MateMenuTree MateMenuTree
typedef struct _MateMenuTreeClass MateMenuTreeClass
typedef struct MateMenuTreeIter MateMenuTreeIter
typedef struct MateMenuTreeDirectory MateMenuTreeDirectory
typedef struct MateMenuTreeEntry MateMenuTreeEntry
typedef struct MateMenuTreeSeparator MateMenuTreeSeparator
typedef struct MateMenuTreeHeader MateMenuTreeHeader
typedef struct MateMenuTreeAlias MateMenuTreeAlias
Enumerations
enum MateMenuTreeItemType {
MATEMENU_TREE_ITEM_INVALID = 0 , MATEMENU_TREE_ITEM_DIRECTORY , MATEMENU_TREE_ITEM_ENTRY , MATEMENU_TREE_ITEM_SEPARATOR ,
MATEMENU_TREE_ITEM_HEADER , MATEMENU_TREE_ITEM_ALIAS
}
enum MateMenuTreeFlags {
MATEMENU_TREE_FLAGS_NONE = 0 , MATEMENU_TREE_FLAGS_INCLUDE_EXCLUDED = 1 << 0 , MATEMENU_TREE_FLAGS_INCLUDE_NODISPLAY = 1 << 1 , MATEMENU_TREE_FLAGS_INCLUDE_UNALLOCATED = 1 << 2 ,
MATEMENU_TREE_FLAGS_SHOW_EMPTY = 1 << 8 , MATEMENU_TREE_FLAGS_SHOW_ALL_SEPARATORS = 1 << 9 , MATEMENU_TREE_FLAGS_SORT_DISPLAY_NAME = 1 << 16
}
Functions
GType matemenu_tree_get_type (void)
GType matemenu_tree_iter_get_type (void)
GType matemenu_tree_directory_get_type (void)
GType matemenu_tree_entry_get_type (void)
GType matemenu_tree_separator_get_type (void)
GType matemenu_tree_header_get_type (void)
GType matemenu_tree_alias_get_type (void)
GType matemenu_tree_flags_get_type (void)
MateMenuTree * matemenu_tree_new (const char *menu_basename, MateMenuTreeFlags flags)
MateMenuTree * matemenu_tree_new_for_path (const char *menu_path, MateMenuTreeFlags flags)
gboolean matemenu_tree_load_sync (MateMenuTree *tree, GError **error)
const char * matemenu_tree_get_canonical_menu_path (MateMenuTree *tree)
MateMenuTreeDirectory * matemenu_tree_get_root_directory (MateMenuTree *tree)
MateMenuTreeDirectory * matemenu_tree_get_directory_from_path (MateMenuTree *tree, const char *path)
MateMenuTreeEntry * matemenu_tree_get_entry_by_id (MateMenuTree *tree, const char *id)
gpointer matemenu_tree_item_ref (gpointer item)
void matemenu_tree_item_unref (gpointer item)
MateMenuTreeDirectory * matemenu_tree_directory_get_parent (MateMenuTreeDirectory *directory)
const char * matemenu_tree_directory_get_name (MateMenuTreeDirectory *directory)
const char * matemenu_tree_directory_get_generic_name (MateMenuTreeDirectory *directory)
const char * matemenu_tree_directory_get_comment (MateMenuTreeDirectory *directory)
GIcon * matemenu_tree_directory_get_icon (MateMenuTreeDirectory *directory)
const char * matemenu_tree_directory_get_desktop_file_path (MateMenuTreeDirectory *directory)
const char * matemenu_tree_directory_get_menu_id (MateMenuTreeDirectory *directory)
MateMenuTree * matemenu_tree_directory_get_tree (MateMenuTreeDirectory *directory)
gboolean matemenu_tree_directory_get_is_nodisplay (MateMenuTreeDirectory *directory)
MateMenuTreeIter * matemenu_tree_directory_iter (MateMenuTreeDirectory *directory)
MateMenuTreeIter * matemenu_tree_iter_ref (MateMenuTreeIter *iter)
void matemenu_tree_iter_unref (MateMenuTreeIter *iter)
MateMenuTreeItemType matemenu_tree_iter_next (MateMenuTreeIter *iter)
MateMenuTreeDirectory * matemenu_tree_iter_get_directory (MateMenuTreeIter *iter)
MateMenuTreeEntry * matemenu_tree_iter_get_entry (MateMenuTreeIter *iter)
MateMenuTreeHeader * matemenu_tree_iter_get_header (MateMenuTreeIter *iter)
MateMenuTreeAlias * matemenu_tree_iter_get_alias (MateMenuTreeIter *iter)
MateMenuTreeSeparator * matemenu_tree_iter_get_separator (MateMenuTreeIter *iter)
char * matemenu_tree_directory_make_path (MateMenuTreeDirectory *directory, MateMenuTreeEntry *entry)
GDesktopAppInfo * matemenu_tree_entry_get_app_info (MateMenuTreeEntry *entry)
MateMenuTreeDirectory * matemenu_tree_entry_get_parent (MateMenuTreeEntry *entry)
MateMenuTree * matemenu_tree_entry_get_tree (MateMenuTreeEntry *entry)
const char * matemenu_tree_entry_get_desktop_file_path (MateMenuTreeEntry *entry)
const char * matemenu_tree_entry_get_desktop_file_id (MateMenuTreeEntry *entry)
gboolean matemenu_tree_entry_get_is_nodisplay_recurse (MateMenuTreeEntry *entry)
gboolean matemenu_tree_entry_get_is_excluded (MateMenuTreeEntry *entry)
gboolean matemenu_tree_entry_get_is_unallocated (MateMenuTreeEntry *entry)
MateMenuTreeDirectory * matemenu_tree_header_get_directory (MateMenuTreeHeader *header)
MateMenuTree * matemenu_tree_header_get_tree (MateMenuTreeHeader *header)
MateMenuTreeDirectory * matemenu_tree_header_get_parent (MateMenuTreeHeader *header)
MateMenuTreeDirectory * matemenu_tree_alias_get_directory (MateMenuTreeAlias *alias)
MateMenuTreeItemType matemenu_tree_alias_get_aliased_item_type (MateMenuTreeAlias *alias)
MateMenuTreeDirectory * matemenu_tree_alias_get_aliased_directory (MateMenuTreeAlias *alias)
MateMenuTreeEntry * matemenu_tree_alias_get_aliased_entry (MateMenuTreeAlias *alias)
MateMenuTree * matemenu_tree_alias_get_tree (MateMenuTreeAlias *alias)
MateMenuTreeDirectory * matemenu_tree_alias_get_parent (MateMenuTreeAlias *alias)
MateMenuTree * matemenu_tree_separator_get_tree (MateMenuTreeSeparator *separator)
MateMenuTreeDirectory * matemenu_tree_separator_get_parent (MateMenuTreeSeparator *separator)
Macro Definition Documentation
MATEMENU_IS_TREE
#define MATEMENU_IS_TREE (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MATEMENU_TYPE_TREE))
Definition at line 35 of file matemenu-tree.h.
MATEMENU_IS_TREE_CLASS
#define MATEMENU_IS_TREE_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), MATEMENU_TYPE_TREE))
Definition at line 36 of file matemenu-tree.h.
MATEMENU_TREE
#define MATEMENU_TREE (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MATEMENU_TYPE_TREE, MateMenuTree))
Definition at line 33 of file matemenu-tree.h.
MATEMENU_TREE_CLASS
#define MATEMENU_TREE_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), MATEMENU_TYPE_TREE, MateMenuTreeClass))
Definition at line 34 of file matemenu-tree.h.
MATEMENU_TREE_GET_CLASS
#define MATEMENU_TREE_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), G_TYPE_DESKTOP_APP_INFO, MateMenuTreeClass))
Definition at line 37 of file matemenu-tree.h.
MATEMENU_TYPE_TREE
#define MATEMENU_TYPE_TREE (matemenu_tree_get_type ())
Definition at line 32 of file matemenu-tree.h.
MATEMENU_TYPE_TREE_FLAGS
#define MATEMENU_TYPE_TREE_FLAGS (matemenu_tree_flags_get_type ())
Definition at line 88 of file matemenu-tree.h.
Typedef Documentation
MateMenuTree
typedef struct _MateMenuTree MateMenuTree
Definition at line 39 of file matemenu-tree.h.
MateMenuTreeAlias
typedef struct MateMenuTreeAlias MateMenuTreeAlias
Definition at line 54 of file matemenu-tree.h.
MateMenuTreeClass
typedef struct _MateMenuTreeClass MateMenuTreeClass
Definition at line 40 of file matemenu-tree.h.
MateMenuTreeDirectory
typedef struct MateMenuTreeDirectory MateMenuTreeDirectory
Definition at line 50 of file matemenu-tree.h.
MateMenuTreeEntry
typedef struct MateMenuTreeEntry MateMenuTreeEntry
Definition at line 51 of file matemenu-tree.h.
MateMenuTreeHeader
typedef struct MateMenuTreeHeader MateMenuTreeHeader
Definition at line 53 of file matemenu-tree.h.
MateMenuTreeIter
typedef struct MateMenuTreeIter MateMenuTreeIter
Definition at line 49 of file matemenu-tree.h.
MateMenuTreeSeparator
typedef struct MateMenuTreeSeparator MateMenuTreeSeparator
Definition at line 52 of file matemenu-tree.h.
Enumeration Type Documentation
MateMenuTreeFlags
enum MateMenuTreeFlags
Enumerator
MATEMENU_TREE_FLAGS_NONE
MATEMENU_TREE_FLAGS_INCLUDE_EXCLUDED
MATEMENU_TREE_FLAGS_INCLUDE_NODISPLAY
MATEMENU_TREE_FLAGS_INCLUDE_UNALLOCATED
MATEMENU_TREE_FLAGS_SHOW_EMPTY
MATEMENU_TREE_FLAGS_SHOW_ALL_SEPARATORS
MATEMENU_TREE_FLAGS_SORT_DISPLAY_NAME
Definition at line 75 of file matemenu-tree.h.
MateMenuTreeItemType
enum MateMenuTreeItemType
Enumerator
MATEMENU_TREE_ITEM_INVALID
MATEMENU_TREE_ITEM_DIRECTORY
MATEMENU_TREE_ITEM_ENTRY
MATEMENU_TREE_ITEM_SEPARATOR
MATEMENU_TREE_ITEM_HEADER
MATEMENU_TREE_ITEM_ALIAS
Definition at line 56 of file matemenu-tree.h.
Function Documentation
matemenu_tree_alias_get_aliased_directory()
MateMenuTreeDirectory * matemenu_tree_alias_get_aliased_directory (MateMenuTreeAlias * alias)
matemenu_tree_alias_get_aliased_directory: @alias: alias
Returns: (transfer full): The aliased directory entry
Definition at line 1552 of file matemenu-tree.c.
References MATEMENU_TREE_ITEM_DIRECTORY, matemenu_tree_item_ref(), and NULL.
matemenu_tree_alias_get_aliased_entry()
MateMenuTreeEntry * matemenu_tree_alias_get_aliased_entry (MateMenuTreeAlias * alias)
matemenu_tree_alias_get_aliased_entry: @alias: alias
Returns: (transfer full): The aliased entry
Definition at line 1567 of file matemenu-tree.c.
References MATEMENU_TREE_ITEM_ENTRY, matemenu_tree_item_ref(), and NULL.
matemenu_tree_alias_get_aliased_item_type()
MateMenuTreeItemType matemenu_tree_alias_get_aliased_item_type (MateMenuTreeAlias * alias)
Definition at line 1498 of file matemenu-tree.c.
References MATEMENU_TREE_ITEM_INVALID, and NULL.
matemenu_tree_alias_get_directory()
MateMenuTreeDirectory * matemenu_tree_alias_get_directory (MateMenuTreeAlias * alias)
Definition at line 1506 of file matemenu-tree.c.
References matemenu_tree_item_ref(), and NULL.
matemenu_tree_alias_get_parent()
MateMenuTreeDirectory * matemenu_tree_alias_get_parent (MateMenuTreeAlias * alias)
matemenu_tree_alias_get_parent: @alias: a #MateMenuTreeAlias
Returns: (transfer full): The parent directory, or NULL if none
Definition at line 1045 of file matemenu-tree.c.
matemenu_tree_alias_get_tree()
MateMenuTree * matemenu_tree_alias_get_tree (MateMenuTreeAlias * alias)
matemenu_tree_alias_get_tree: @alias: A #MateMenuTreeAlias
Grab the tree associated with a #MateMenuTreeAlias.
Returns: (transfer full): The MateMenuTree
Definition at line 1522 of file matemenu-tree.c.
References NULL.
matemenu_tree_alias_get_type()
GType matemenu_tree_alias_get_type (void)
Definition at line 5063 of file matemenu-tree.c.
References matemenu_tree_item_ref(), and matemenu_tree_item_unref().
matemenu_tree_directory_get_comment()
const char * matemenu_tree_directory_get_comment (MateMenuTreeDirectory * directory)
Definition at line 1278 of file matemenu-tree.c.
References desktop_entry_get_comment(), and NULL.
matemenu_tree_directory_get_desktop_file_path()
const char * matemenu_tree_directory_get_desktop_file_path (MateMenuTreeDirectory * directory)
Definition at line 1308 of file matemenu-tree.c.
References desktop_entry_get_path(), and NULL.
matemenu_tree_directory_get_generic_name()
const char * matemenu_tree_directory_get_generic_name (MateMenuTreeDirectory * directory)
Definition at line 1267 of file matemenu-tree.c.
References desktop_entry_get_generic_name(), and NULL.
matemenu_tree_directory_get_icon()
GIcon * matemenu_tree_directory_get_icon (MateMenuTreeDirectory * directory)
matemenu_tree_directory_get_icon: @directory: a #MateMenuTreeDirectory
Gets the icon for the directory.
Returns: (transfer none): The #GIcon for this directory
Definition at line 1297 of file matemenu-tree.c.
References desktop_entry_get_icon(), and NULL.
matemenu_tree_directory_get_is_nodisplay()
gboolean matemenu_tree_directory_get_is_nodisplay (MateMenuTreeDirectory * directory)
Definition at line 1327 of file matemenu-tree.c.
References FALSE, and NULL.
matemenu_tree_directory_get_menu_id()
const char * matemenu_tree_directory_get_menu_id (MateMenuTreeDirectory * directory)
Definition at line 1319 of file matemenu-tree.c.
References NULL.
matemenu_tree_directory_get_name()
const char * matemenu_tree_directory_get_name (MateMenuTreeDirectory * directory)
Definition at line 1256 of file matemenu-tree.c.
References desktop_entry_get_name(), and NULL.
Referenced by generate_categories().
matemenu_tree_directory_get_parent()
MateMenuTreeDirectory * matemenu_tree_directory_get_parent (MateMenuTreeDirectory * directory)
matemenu_tree_directory_get_parent: @directory: a #MateMenuTreeDirectory
Returns: (transfer full): The parent directory, or NULL if none
Definition at line 1021 of file matemenu-tree.c.
matemenu_tree_directory_get_tree()
MateMenuTree * matemenu_tree_directory_get_tree (MateMenuTreeDirectory * directory)
matemenu_tree_directory_get_tree: @directory: A #MateMenuTreeDirectory
Grab the tree associated with a #MateMenuTreeItem.
Returns: (transfer full): The MateMenuTree
Definition at line 1343 of file matemenu-tree.c.
References NULL.
matemenu_tree_directory_get_type()
GType matemenu_tree_directory_get_type (void)
Definition at line 5011 of file matemenu-tree.c.
References matemenu_tree_item_ref(), and matemenu_tree_item_unref().
matemenu_tree_directory_iter()
MateMenuTreeIter * matemenu_tree_directory_iter (MateMenuTreeDirectory * directory)
matemenu_tree_directory_iter: @directory: directory
Returns: (transfer full): A new iterator over the directory contents
Definition at line 1120 of file matemenu-tree.c.
References matemenu_tree_item_ref(), and NULL.
Referenced by generate_categories().
matemenu_tree_directory_make_path()
char * matemenu_tree_directory_make_path (MateMenuTreeDirectory * directory, MateMenuTreeEntry * entry)
Definition at line 1368 of file matemenu-tree.c.
References desktop_entry_get_basename(), FALSE, and NULL.
matemenu_tree_entry_get_app_info()
GDesktopAppInfo * matemenu_tree_entry_get_app_info (MateMenuTreeEntry * entry)
matemenu_tree_entry_get_app_info: @entry: a #MateMenuTreeEntry
Returns: (transfer none): The #GDesktopAppInfo for this entry
Definition at line 1393 of file matemenu-tree.c.
References desktop_entry_get_app_info(), and NULL.
Referenced by matemenu_tree_entry_get_is_nodisplay_recurse().
matemenu_tree_entry_get_desktop_file_id()
const char * matemenu_tree_entry_get_desktop_file_id (MateMenuTreeEntry * entry)
Definition at line 1409 of file matemenu-tree.c.
References NULL.
matemenu_tree_entry_get_desktop_file_path()
const char * matemenu_tree_entry_get_desktop_file_path (MateMenuTreeEntry * entry)
Definition at line 1401 of file matemenu-tree.c.
References desktop_entry_get_path(), and NULL.
matemenu_tree_entry_get_is_excluded()
gboolean matemenu_tree_entry_get_is_excluded (MateMenuTreeEntry * entry)
Definition at line 1442 of file matemenu-tree.c.
References FALSE, and NULL.
matemenu_tree_entry_get_is_nodisplay_recurse()
gboolean matemenu_tree_entry_get_is_nodisplay_recurse (MateMenuTreeEntry * entry)
Definition at line 1417 of file matemenu-tree.c.
References FALSE, matemenu_tree_entry_get_app_info(), NULL, and TRUE.
matemenu_tree_entry_get_is_unallocated()
gboolean matemenu_tree_entry_get_is_unallocated (MateMenuTreeEntry * entry)
Definition at line 1450 of file matemenu-tree.c.
References FALSE, and NULL.
matemenu_tree_entry_get_parent()
MateMenuTreeDirectory * matemenu_tree_entry_get_parent (MateMenuTreeEntry * entry)
matemenu_tree_entry_get_parent: @entry: a #MateMenuTreeEntry
Returns: (transfer full): The parent directory, or NULL if none
Definition at line 1033 of file matemenu-tree.c.
matemenu_tree_entry_get_tree()
MateMenuTree * matemenu_tree_entry_get_tree (MateMenuTreeEntry * entry)
matemenu_tree_entry_get_tree: @entry: A #MateMenuTreeEntry
Grab the tree associated with a #MateMenuTreeEntry.
Returns: (transfer full): The MateMenuTree
Definition at line 1466 of file matemenu-tree.c.
References NULL.
matemenu_tree_entry_get_type()
GType matemenu_tree_entry_get_type (void)
Definition at line 5024 of file matemenu-tree.c.
References matemenu_tree_item_ref(), and matemenu_tree_item_unref().
matemenu_tree_flags_get_type()
GType matemenu_tree_flags_get_type (void)
Definition at line 5076 of file matemenu-tree.c.
References MATEMENU_TREE_FLAGS_INCLUDE_EXCLUDED, MATEMENU_TREE_FLAGS_INCLUDE_NODISPLAY, MATEMENU_TREE_FLAGS_INCLUDE_UNALLOCATED, MATEMENU_TREE_FLAGS_NONE, MATEMENU_TREE_FLAGS_SHOW_ALL_SEPARATORS, MATEMENU_TREE_FLAGS_SHOW_EMPTY, MATEMENU_TREE_FLAGS_SORT_DISPLAY_NAME, and NULL.
matemenu_tree_get_canonical_menu_path()
const char * matemenu_tree_get_canonical_menu_path (MateMenuTree * tree)
matemenu_tree_get_canonical_menu_path: @tree: a MateMenuTree
This function is only available if the tree has been loaded via matemenu_tree_load_sync() or a variant thereof.
Returns: The absolute and canonicalized path to the loaded menu file
Definition at line 840 of file matemenu-tree.c.
References MATEMENU_IS_TREE, and NULL.
Referenced by main().
matemenu_tree_get_directory_from_path()
MateMenuTreeDirectory * matemenu_tree_get_directory_from_path (MateMenuTree * tree, const char * path)
Definition at line 955 of file matemenu-tree.c.
References matemenu_tree_get_root_directory(), matemenu_tree_item_ref(), matemenu_tree_item_unref(), and NULL.
matemenu_tree_get_entry_by_id()
MateMenuTreeEntry * matemenu_tree_get_entry_by_id (MateMenuTree * tree, const char * id)
matemenu_tree_get_entry_by_id: @tree: a MateMenuTree @id: a desktop file ID
Look up the entry corresponding to the given "desktop file id".
Returns: (transfer full): A newly referenced #MateMenuTreeEntry, or NULL if none
Definition at line 987 of file matemenu-tree.c.
References matemenu_tree_item_ref(), and NULL.
matemenu_tree_get_root_directory()
MateMenuTreeDirectory * matemenu_tree_get_root_directory (MateMenuTree * tree)
matemenu_tree_get_root_directory: @tree: a MateMenuTree
Get the root directory; you must have loaded the tree first (at least once) via matemenu_tree_load_sync() or a variant thereof.
Returns: (transfer full): Root of the tree
Definition at line 890 of file matemenu-tree.c.
References matemenu_tree_item_ref(), and NULL.
Referenced by generate_categories(), gs_theme_manager_get_info_list(), main(), and matemenu_tree_get_directory_from_path().
matemenu_tree_get_type()
GType matemenu_tree_get_type (void)
matemenu_tree_header_get_directory()
MateMenuTreeDirectory * matemenu_tree_header_get_directory (MateMenuTreeHeader * header)
Definition at line 1474 of file matemenu-tree.c.
References matemenu_tree_item_ref(), and NULL.
matemenu_tree_header_get_parent()
MateMenuTreeDirectory * matemenu_tree_header_get_parent (MateMenuTreeHeader * header)
matemenu_tree_header_get_parent: @header: a #MateMenuTreeHeader
Returns: (transfer full): The parent directory, or NULL if none
Definition at line 1057 of file matemenu-tree.c.
matemenu_tree_header_get_tree()
MateMenuTree * matemenu_tree_header_get_tree (MateMenuTreeHeader * header)
matemenu_tree_header_get_tree: @header: A #MateMenuTreeHeader
Grab the tree associated with a #MateMenuTreeHeader.
Returns: (transfer full): The MateMenuTree
Definition at line 1490 of file matemenu-tree.c.
References NULL.
matemenu_tree_header_get_type()
GType matemenu_tree_header_get_type (void)
Definition at line 5050 of file matemenu-tree.c.
References matemenu_tree_item_ref(), and matemenu_tree_item_unref().
matemenu_tree_item_ref()
gpointer matemenu_tree_item_ref (gpointer itemp)
matemenu_tree_item_ref: @item: a #MateMenuTreeItem
Returns: (transfer full): The same @item, or NULL if @item is not a valid #MateMenuTreeItem
Definition at line 1807 of file matemenu-tree.c.
References item, and NULL.
Referenced by matemenu_tree_alias_get_aliased_directory(), matemenu_tree_alias_get_aliased_entry(), matemenu_tree_alias_get_directory(), matemenu_tree_alias_get_type(), matemenu_tree_directory_get_type(), matemenu_tree_directory_iter(), matemenu_tree_entry_get_type(), matemenu_tree_get_directory_from_path(), matemenu_tree_get_entry_by_id(), matemenu_tree_get_root_directory(), matemenu_tree_header_get_directory(), matemenu_tree_header_get_type(), matemenu_tree_iter_get_alias(), matemenu_tree_iter_get_directory(), matemenu_tree_iter_get_entry(), matemenu_tree_iter_get_header(), matemenu_tree_iter_get_separator(), and matemenu_tree_separator_get_type().
matemenu_tree_item_unref()
void matemenu_tree_item_unref (gpointer item)
Definition at line 1819 of file matemenu-tree.c.
References item, MATEMENU_TREE_ALIAS, MATEMENU_TREE_DIRECTORY, MATEMENU_TREE_ENTRY, MATEMENU_TREE_HEADER, MATEMENU_TREE_ITEM_ALIAS, MATEMENU_TREE_ITEM_DIRECTORY, MATEMENU_TREE_ITEM_ENTRY, MATEMENU_TREE_ITEM_HEADER, MATEMENU_TREE_ITEM_SEPARATOR, MATEMENU_TREE_SEPARATOR, and NULL.
Referenced by generate_categories(), gs_theme_manager_get_info_list(), main(), matemenu_tree_alias_get_type(), matemenu_tree_directory_get_type(), matemenu_tree_entry_get_type(), matemenu_tree_get_directory_from_path(), matemenu_tree_header_get_type(), matemenu_tree_iter_unref(), and matemenu_tree_separator_get_type().
matemenu_tree_iter_get_alias()
MateMenuTreeAlias * matemenu_tree_iter_get_alias (MateMenuTreeIter * iter)
matemenu_tree_iter_get_alias: @iter: iter
This method may only be called if matemenu_tree_iter_next() returned MATEMENU_TREE_ITEM_ALIAS.
Returns: (transfer full): An alias
Definition at line 1227 of file matemenu-tree.c.
References MATEMENU_TREE_ITEM_ALIAS, matemenu_tree_item_ref(), and NULL.
matemenu_tree_iter_get_directory()
MateMenuTreeDirectory * matemenu_tree_iter_get_directory (MateMenuTreeIter * iter)
matemenu_tree_iter_get_directory: @iter: iter
This method may only be called if matemenu_tree_iter_next() returned MATEMENU_TREE_ITEM_DIRECTORY.
Returns: (transfer full): A directory
Definition at line 1170 of file matemenu-tree.c.
References MATEMENU_TREE_ITEM_DIRECTORY, matemenu_tree_item_ref(), and NULL.
Referenced by generate_categories().
matemenu_tree_iter_get_entry()
MateMenuTreeEntry * matemenu_tree_iter_get_entry (MateMenuTreeIter * iter)
matemenu_tree_iter_get_entry: @iter: iter
This method may only be called if matemenu_tree_iter_next() returned MATEMENU_TREE_ITEM_ENTRY.
Returns: (transfer full): An entry
Definition at line 1189 of file matemenu-tree.c.
References MATEMENU_TREE_ITEM_ENTRY, matemenu_tree_item_ref(), and NULL.
matemenu_tree_iter_get_header()
MateMenuTreeHeader * matemenu_tree_iter_get_header (MateMenuTreeIter * iter)
matemenu_tree_iter_get_header: @iter: iter
This method may only be called if matemenu_tree_iter_next() returned MATEMENU_TREE_ITEM_HEADER.
Returns: (transfer full): A header
Definition at line 1208 of file matemenu-tree.c.
References MATEMENU_TREE_ITEM_HEADER, matemenu_tree_item_ref(), and NULL.
matemenu_tree_iter_get_separator()
MateMenuTreeSeparator * matemenu_tree_iter_get_separator (MateMenuTreeIter * iter)
matemenu_tree_iter_get_separator: @iter: iter
This method may only be called if matemenu_tree_iter_next() returned MATEMENU_TREE_ITEM_SEPARATOR.
Returns: (transfer full): A separator
Definition at line 1246 of file matemenu-tree.c.
References matemenu_tree_item_ref(), MATEMENU_TREE_ITEM_SEPARATOR, and NULL.
matemenu_tree_iter_get_type()
GType matemenu_tree_iter_get_type (void)
Definition at line 4998 of file matemenu-tree.c.
References matemenu_tree_iter_ref(), and matemenu_tree_iter_unref().
matemenu_tree_iter_next()
MateMenuTreeItemType matemenu_tree_iter_next (MateMenuTreeIter * iter)
matemenu_tree_iter_next: @iter: iter
Change the iterator to the next item, and return its type. If there are no more items, MATEMENU_TREE_ITEM_INVALID is returned.
Returns: The type of the next item that can be retrived from the iterator
Definition at line 1146 of file matemenu-tree.c.
References MATEMENU_TREE_ITEM_INVALID, and NULL.
Referenced by generate_categories().
matemenu_tree_iter_ref()
MateMenuTreeIter * matemenu_tree_iter_ref (MateMenuTreeIter * iter)
matemenu_tree_iter_ref: (skip) @iter: iter
Increment the reference count of @iter
Definition at line 1090 of file matemenu-tree.c.
Referenced by matemenu_tree_iter_get_type().
matemenu_tree_iter_unref()
void matemenu_tree_iter_unref (MateMenuTreeIter * iter)
matemenu_tree_iter_unref: (skip) @iter: iter
Decrement the reference count of @iter
Definition at line 1103 of file matemenu-tree.c.
References matemenu_tree_item_unref().
Referenced by generate_categories(), and matemenu_tree_iter_get_type().
matemenu_tree_load_sync()
gboolean matemenu_tree_load_sync (MateMenuTree * tree, GError ** error)
matemenu_tree_load_sync: @tree: a MateMenuTree @error: a #GError
Synchronously load the menu contents. This function performs a significant amount of blocking I/O if the tree has not been loaded yet.
Returns: TRUE on success, FALSE on error
Definition at line 860 of file matemenu-tree.c.
References error, FALSE, NULL, and TRUE.
Referenced by create_applications_menu(), generate_categories(), and main().
matemenu_tree_new()
MateMenuTree * matemenu_tree_new (const char * menu_basename, MateMenuTreeFlags flags)
matemenu_tree_new: @menu_basename: Basename of menu file @flags: Flags controlling menu content
Returns: (transfer full): A new MateMenuTree instance
Definition at line 519 of file matemenu-tree.c.
References MATEMENU_TYPE_TREE, and NULL.
Referenced by create_applications_menu(), generate_categories(), and main().
matemenu_tree_new_for_path()
MateMenuTree * matemenu_tree_new_for_path (const char * menu_path, MateMenuTreeFlags flags)
matemenu_tree_new_fo_path: @menu_path: Path of menu file @flags: Flags controlling menu content
Returns: (transfer full): A new MateMenuTree instance
Definition at line 538 of file matemenu-tree.c.
References MATEMENU_TYPE_TREE, and NULL.
matemenu_tree_separator_get_parent()
MateMenuTreeDirectory * matemenu_tree_separator_get_parent (MateMenuTreeSeparator * separator)
matemenu_tree_separator_get_parent: @separator: a #MateMenuTreeSeparator
Returns: (transfer full): The parent directory, or NULL if none
Definition at line 1069 of file matemenu-tree.c.
matemenu_tree_separator_get_tree()
MateMenuTree * matemenu_tree_separator_get_tree (MateMenuTreeSeparator * separator)
matemenu_tree_separator_get_tree: @separator: A #MateMenuTreeSeparator
Grab the tree associated with a #MateMenuTreeSeparator.
Returns: (transfer full): The MateMenuTree
Definition at line 1538 of file matemenu-tree.c.
References NULL.
matemenu_tree_separator_get_type()
GType matemenu_tree_separator_get_type (void)
Definition at line 5037 of file matemenu-tree.c.
References matemenu_tree_item_ref(), and matemenu_tree_item_unref().