MATE Desktop Environment: matekbd-keyboard-drawing-test.c File Reference
matekbd-keyboard-drawing-test.c File Reference
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include "libmatekbd/matekbd-keyboard-drawing.h"
Functions
gint main (gint argc, gchar **argv)
Function Documentation
main()
gint main (gint argc, gchar ** argv)
Definition at line 158 of file matekbd-keyboard-drawing-test.c.
References error, MATEKBD_KEYBOARD_DRAWING, matekbd_keyboard_drawing_get_geometry(), matekbd_keyboard_drawing_get_keycodes(), matekbd_keyboard_drawing_get_symbols(), matekbd_keyboard_drawing_new(), matekbd_keyboard_drawing_set_groups_levels(), matekbd_keyboard_drawing_set_keyboard(), matekbd_keyboard_drawing_set_track_config(), matekbd_keyboard_drawing_set_track_modifiers(), NULL, and TRUE.