MATE Desktop Environment: load-graph.h File Reference
load-graph.h File Reference
#include <glib.h>
#include <glibtop/cpu.h>
Classes
struct LoadGraphLabels
struct LoadGraph
Enumerations
enum { LOAD_GRAPH_CPU , LOAD_GRAPH_MEM , LOAD_GRAPH_NET }
enum { CPU_TOTAL , CPU_USED , N_CPU_STATES }
Functions
void load_graph_queue_draw (LoadGraph *g)
void load_graph_start (LoadGraph *g)
void load_graph_stop (LoadGraph *g)
void load_graph_change_speed (LoadGraph *g, guint new_speed)
LoadGraphLabels * load_graph_get_labels (LoadGraph *g)
GtkWidget * load_graph_get_widget (LoadGraph *g)
GtkWidget * load_graph_get_mem_color_picker (LoadGraph *g)
GtkWidget * load_graph_get_swap_color_picker (LoadGraph *g)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
LOAD_GRAPH_CPU
LOAD_GRAPH_MEM
LOAD_GRAPH_NET
Definition at line 7 of file mate-system-monitor/src/load-graph.h.
anonymous enum
anonymous enum
Enumerator
CPU_TOTAL
CPU_USED
N_CPU_STATES
Definition at line 14 of file mate-system-monitor/src/load-graph.h.
Function Documentation
load_graph_change_speed()
void load_graph_change_speed (LoadGraph * g, guint new_speed)
Definition at line 810 of file load-graph.cpp.
References LoadGraph::clear_background(), LoadGraph::frames_per_unit, LoadGraph::speed, and LoadGraph::timer_index.
load_graph_get_labels()
LoadGraphLabels * load_graph_get_labels (LoadGraph * g)
Definition at line 830 of file load-graph.cpp.
References LoadGraph::labels.
load_graph_get_mem_color_picker()
GtkWidget * load_graph_get_mem_color_picker (LoadGraph * g)
Definition at line 842 of file load-graph.cpp.
References LoadGraph::mem_color_picker.
load_graph_get_swap_color_picker()
GtkWidget * load_graph_get_swap_color_picker (LoadGraph * g)
Definition at line 848 of file load-graph.cpp.
References LoadGraph::swap_color_picker.
load_graph_get_widget()
GtkWidget * load_graph_get_widget (LoadGraph * g)
Definition at line 836 of file load-graph.cpp.
References LoadGraph::main_widget.
load_graph_queue_draw()
void load_graph_queue_draw (LoadGraph * g)
Definition at line 195 of file load-graph.cpp.
References LoadGraph::disp.
load_graph_start()
void load_graph_start (LoadGraph * g)
Definition at line 493 of file load-graph.c.
References LoadGraph::draw, LoadGraph::frames_per_unit, LoadGraph::speed, LoadGraph::timer_index, and TRUE.
Referenced by cb_change_current_page(), and multiload_applet_refresh().
load_graph_stop()
void load_graph_stop (LoadGraph * g)
Definition at line 507 of file load-graph.c.
References LoadGraph::draw, FALSE, and LoadGraph::timer_index.
Referenced by cb_change_current_page(), multiload_applet_refresh(), and LoadGraph::~LoadGraph().