MATE Desktop Environment: mate-mdi-generic-child.h File Reference
mate-mdi-generic-child.h File Reference
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include "mate-mdi-child.h"
Classes
struct _MateMDIGenericChild
struct _MateMDIGenericChildClass
Macros
#define MATE_TYPE_MDI_GENERIC_CHILD (mate_mdi_generic_child_get_type ())
#define MATE_MDI_GENERIC_CHILD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_MDI_GENERIC_CHILD, MateMDIGenericChild))
#define MATE_MDI_GENERIC_CHILD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_MDI_GENERIC_CHILD, MateMDIGenericChildClass))
#define MATE_IS_MDI_GENERIC_CHILD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_MDI_GENERIC_CHILD))
#define MATE_IS_MDI_GENERIC_CHILD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_MDI_GENERIC_CHILD))
#define MATE_MDI_GENERIC_CHILD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_MDI_GENERIC_CHILD, MateMDIGenericChildClass))
Typedefs
typedef struct _MateMDIGenericChild MateMDIGenericChild
typedef struct _MateMDIGenericChildClass MateMDIGenericChildClass
Functions
GType mate_mdi_generic_child_get_type (void)
MateMDIGenericChild * mate_mdi_generic_child_new (const gchar *name)
void mate_mdi_generic_child_set_view_creator (MateMDIGenericChild *child, MateMDIChildViewCreator func, gpointer data)
void mate_mdi_generic_child_set_view_creator_full (MateMDIGenericChild *child, MateMDIChildViewCreator func, GtkCallbackMarshal marshal, gpointer data, GDestroyNotify notify)
void mate_mdi_generic_child_set_menu_creator (MateMDIGenericChild *child, MateMDIChildMenuCreator func, gpointer data)
void mate_mdi_generic_child_set_menu_creator_full (MateMDIGenericChild *child, MateMDIChildMenuCreator func, GtkCallbackMarshal marshal, gpointer data, GDestroyNotify notify)
void mate_mdi_generic_child_set_config_func (MateMDIGenericChild *child, MateMDIChildConfigFunc func, gpointer data)
void mate_mdi_generic_child_set_config_func_full (MateMDIGenericChild *child, MateMDIChildConfigFunc func, GtkCallbackMarshal marshal, gpointer data, GDestroyNotify notify)
void mate_mdi_generic_child_set_label_func (MateMDIGenericChild *child, MateMDIChildLabelFunc func, gpointer data)
void mate_mdi_generic_child_set_label_func_full (MateMDIGenericChild *child, MateMDIChildLabelFunc func, GtkCallbackMarshal marshal, gpointer data, GDestroyNotify notify)
Macro Definition Documentation
MATE_IS_MDI_GENERIC_CHILD
#define MATE_IS_MDI_GENERIC_CHILD (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_MDI_GENERIC_CHILD))
Definition at line 42 of file mate-mdi-generic-child.h.
MATE_IS_MDI_GENERIC_CHILD_CLASS
#define MATE_IS_MDI_GENERIC_CHILD_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_MDI_GENERIC_CHILD))
Definition at line 43 of file mate-mdi-generic-child.h.
MATE_MDI_GENERIC_CHILD
#define MATE_MDI_GENERIC_CHILD (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_MDI_GENERIC_CHILD, MateMDIGenericChild))
Definition at line 40 of file mate-mdi-generic-child.h.
MATE_MDI_GENERIC_CHILD_CLASS
#define MATE_MDI_GENERIC_CHILD_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_MDI_GENERIC_CHILD, MateMDIGenericChildClass))
Definition at line 41 of file mate-mdi-generic-child.h.
MATE_MDI_GENERIC_CHILD_GET_CLASS
#define MATE_MDI_GENERIC_CHILD_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_MDI_GENERIC_CHILD, MateMDIGenericChildClass))
Definition at line 44 of file mate-mdi-generic-child.h.
MATE_TYPE_MDI_GENERIC_CHILD
#define MATE_TYPE_MDI_GENERIC_CHILD (mate_mdi_generic_child_get_type ())
Definition at line 39 of file mate-mdi-generic-child.h.
Typedef Documentation
MateMDIGenericChild
typedef struct _MateMDIGenericChild MateMDIGenericChild
Definition at line 48 of file mate-mdi-generic-child.h.
MateMDIGenericChildClass
typedef struct _MateMDIGenericChildClass MateMDIGenericChildClass
Definition at line 49 of file mate-mdi-generic-child.h.
Function Documentation
mate_mdi_generic_child_get_type()
GType mate_mdi_generic_child_get_type (void)
mate_mdi_generic_child_new()
MateMDIGenericChild * mate_mdi_generic_child_new (const gchar * name)
Definition at line 103 of file mate-mdi-generic-child.c.
References MATE_MDI_CHILD, MATE_TYPE_MDI_GENERIC_CHILD, name, and NULL.
mate_mdi_generic_child_set_config_func()
void mate_mdi_generic_child_set_config_func (MateMDIGenericChild * child, MateMDIChildConfigFunc func, gpointer data)
mate_mdi_generic_child_set_config_func: @child: the mdi child object @func: a function to set the config key for session saves @data: optional user data
Sets the function used to get the config key used for session saves.
A &MateMDIGenericChild doesn't require a config func.
Definition at line 221 of file mate-mdi-generic-child.c.
References data, mate_mdi_generic_child_set_config_func_full(), and NULL.
mate_mdi_generic_child_set_config_func_full()
void mate_mdi_generic_child_set_config_func_full (MateMDIGenericChild * child, MateMDIChildConfigFunc func, GtkCallbackMarshal marshal, gpointer data, GDestroyNotify notify)
mate_mdi_generic_child_set_config_func_full: @child: the mdi child object @func: a function (not used if @marshal != NULL) @marshal: a callback marshaller @data: optional user data @notify: a destroy notify for the user data
A function similar to mate_mdi_generic_child_set_config_func(), except it gives more control to the programmer.
The &GtkArg array passed to @marshal is of length 2. The first element is @child, and the second is the return value (a pointer to a string).
Definition at line 242 of file mate-mdi-generic-child.c.
References data, _MateMDIGenericChild::get_config_string, _MateMDIGenericChild::get_config_string_cbm, _MateMDIGenericChild::get_config_string_data, and _MateMDIGenericChild::get_config_string_dn.
Referenced by mate_mdi_generic_child_set_config_func().
mate_mdi_generic_child_set_label_func()
void mate_mdi_generic_child_set_label_func (MateMDIGenericChild * child, MateMDIChildLabelFunc func, gpointer data)
mate_mdi_generic_child_set_label_func: @child: a mdi child object @func: a function @data: optional user data
Sets the function used to set (or modify) the label for @child. The first argument to @func is @child. If a label exists, it will be passed to @func as the second argument, otherwise, NULL is passed. The function should return the modified label.
A &MateMDIGenericChild doesn't require a label function.
Definition at line 269 of file mate-mdi-generic-child.c.
References data, mate_mdi_generic_child_set_label_func_full(), and NULL.
mate_mdi_generic_child_set_label_func_full()
void mate_mdi_generic_child_set_label_func_full (MateMDIGenericChild * child, MateMDIChildLabelFunc func, GtkCallbackMarshal marshal, gpointer data, GDestroyNotify notify)
mate_mdi_generic_child_set_label_func_full: @child: the mdi child object @func: a function (not used if @marshal != NULL) @marshal: a callback marshaller @data: optional user data @notify: a destroy notify for the data
Similar to mate_mdi_generic_child_set_label_func(), except it gives more flexibility to the programmer.
The &GtkArg array passed to @marshal is of length 3. The first argument is @child, the second is the old widget (or NULL), and the third is the return value (a pointer to a &GtkWidget).
Definition at line 291 of file mate-mdi-generic-child.c.
References data, _MateMDIGenericChild::set_label, _MateMDIGenericChild::set_label_cbm, _MateMDIGenericChild::set_label_data, and _MateMDIGenericChild::set_label_dn.
Referenced by mate_mdi_generic_child_set_label_func().
mate_mdi_generic_child_set_menu_creator()
void mate_mdi_generic_child_set_menu_creator (MateMDIGenericChild * child, MateMDIChildMenuCreator func, gpointer data)
mate_mdi_generic_child_set_menu_creator: @child: the mdi child object @func: a function to create a list of child specific menus @data: optional user data
Sets the function used to create child specific menus. The function should return a &GList of the menus created.
A &MateMDIGenericChild doesn't require a menu creator.
Definition at line 174 of file mate-mdi-generic-child.c.
References data, mate_mdi_generic_child_set_menu_creator_full(), and NULL.
mate_mdi_generic_child_set_menu_creator_full()
void mate_mdi_generic_child_set_menu_creator_full (MateMDIGenericChild * child, MateMDIChildMenuCreator func, GtkCallbackMarshal marshal, gpointer data, GDestroyNotify notify)
mate_mdi_generic_child_set_menu_creator_full: @child: the mdi child object @func: a menu creator function (not used if @marshal != NULL) @marshal: a callback marshaller @data: optional user data @notify: a destroy notify for the data
This function is similar to mate_mdi_generic_child_set_menu_creator(), but gives extra flexibility to the programmer, in the form of a a destroy notify for the user data, and a callback marshaller.
The &GtkArg array passed to @marshal is of length 3. The first element will be @child, the second will be a view of @child, and the third is the return value (a pointer to the returned GList).
Definition at line 197 of file mate-mdi-generic-child.c.
References _MateMDIGenericChild::create_menus, _MateMDIGenericChild::create_menus_cbm, _MateMDIGenericChild::create_menus_data, _MateMDIGenericChild::create_menus_dn, and data.
Referenced by mate_mdi_generic_child_set_menu_creator().
mate_mdi_generic_child_set_view_creator()
void mate_mdi_generic_child_set_view_creator (MateMDIGenericChild * child, MateMDIChildViewCreator func, gpointer data)
mate_mdi_generic_child_set_view_creator: @child: the mdi child object @func: a function used to create views @data: optional user data.
This function sets the function that is used to create new views for this particular mdi child object. The function should return a newly created widget (the view).
A &MateMDIGenericChild must have a view creator.
Definition at line 126 of file mate-mdi-generic-child.c.
References data, mate_mdi_generic_child_set_view_creator_full(), and NULL.
mate_mdi_generic_child_set_view_creator_full()
void mate_mdi_generic_child_set_view_creator_full (MateMDIGenericChild * child, MateMDIChildViewCreator func, GtkCallbackMarshal marshal, gpointer data, GDestroyNotify notify)
mate_mdi_generic_child_set_view_creator_full: @child: the mdi child object @func: a function to create views (not used if @marshal != NULL) @marshal: a callback marshaller @data: optional user data @notify: a function used to free the user data.
Similar to mate_mdi_generic_child_set_view_creator(), except that it gives more control to the programmer. If @marshal is not NULL, then it will be called instead of @func.
The &GtkArg array passed to @marshal will be of length 2. The first element will be @child, and the second is the return value (a pointer to a &GtkWidget).
Definition at line 149 of file mate-mdi-generic-child.c.
References _MateMDIGenericChild::create_view, _MateMDIGenericChild::create_view_cbm, _MateMDIGenericChild::create_view_data, _MateMDIGenericChild::create_view_dn, and data.
Referenced by mate_mdi_generic_child_set_view_creator().