MATE Desktop Environment: mate-icon-sel.c File Reference
mate-icon-sel.c File Reference
#include <config.h>
#include <libmate/mate-macros.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <dirent.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <libmate/mate-util.h>
#include "mate-icon-list.h"
#include "mate-uidefs.h"
#include "mate-icon-sel.h"
#include "libmateui-access.h"
#include <gio/gio.h>
Macros
#define ICON_SIZE 48
Functions
MATE_CLASS_BOILERPLATE (MateIconSelection, mate_icon_selection, GtkVBox, GTK_TYPE_VBOX)
GtkWidget * mate_icon_selection_new (void)
void mate_icon_selection_add_defaults (MateIconSelection *gis)
void mate_icon_selection_add_directory (MateIconSelection *gis, const gchar *dir)
void mate_icon_selection_show_icons (MateIconSelection *gis)
void mate_icon_selection_stop_loading (MateIconSelection *gis)
void mate_icon_selection_clear (MateIconSelection *gis, gboolean not_shown)
gchar * mate_icon_selection_get_icon (MateIconSelection *gis, gboolean full_path)
void mate_icon_selection_select_icon (MateIconSelection *gis, const gchar *filename)
GtkWidget * mate_icon_selection_get_gil (MateIconSelection *gis)
GtkWidget * mate_icon_selection_get_box (MateIconSelection *gis)
Macro Definition Documentation
ICON_SIZE
#define ICON_SIZE 48
Definition at line 46 of file mate-icon-sel.c.
Function Documentation
MATE_CLASS_BOILERPLATE()
MATE_CLASS_BOILERPLATE (MateIconSelection , mate_icon_selection , GtkVBox , GTK_TYPE_VBOX)
Definition at line 69 of file mate-icon-sel.c.
mate_icon_selection_add_defaults()
void mate_icon_selection_add_defaults (MateIconSelection * gis)
mate_icon_selection_add_defaults: @gis: MateIconSelection to work with
Description: Adds the default pixmap directory into the selection widget. It doesn't show the icons in the selection until you do mate_icon_selection_show_icons.
Definition at line 204 of file mate-icon-sel.c.
References mate_icon_selection_add_directory(), MATE_IS_ICON_SELECTION, and NULL.
mate_icon_selection_add_directory()
void mate_icon_selection_add_directory (MateIconSelection * gis, const gchar * dir)
Definition at line 282 of file mate-icon-sel.c.
References _, _MateIconSelection::_priv, MATE_IS_ICON_SELECTION, and NULL.
Referenced by mate_icon_selection_add_defaults().
mate_icon_selection_clear()
void mate_icon_selection_clear (MateIconSelection * gis, gboolean not_shown)
mate_icon_selection_clear: @gis: MateIconSelection to work with @not_shown: boolean
Description: Clear the currently shown icons, the ones that weren't shown yet are not cleared unless the not_shown parameter is given, in which case even those are cleared.
Definition at line 501 of file mate-icon-sel.c.
References _MateIconSelection::_priv, MATE_ICON_LIST, mate_icon_list_clear(), MATE_IS_ICON_SELECTION, and NULL.
mate_icon_selection_get_box()
GtkWidget * mate_icon_selection_get_box (MateIconSelection * gis)
mate_icon_selection_get_box: @gis: MateIconSelection to work with
Description: Gets the #GtkVBox widget that is used to pack the different elements of the selection into.
Returns: a #GtkWidget pointer to the interal widget
Definition at line 618 of file mate-icon-sel.c.
References _MateIconSelection::_priv, MATE_IS_ICON_SELECTION, and NULL.
mate_icon_selection_get_gil()
GtkWidget * mate_icon_selection_get_gil (MateIconSelection * gis)
mate_icon_selection_get_gil: @gis: MateIconSelection to work with
Description: Gets the MateIconList widget that is used for the display of icons
Returns: a #GtkWidget pointer to the interal widget
Definition at line 599 of file mate-icon-sel.c.
References _MateIconSelection::_priv, MATE_IS_ICON_SELECTION, and NULL.
mate_icon_selection_get_icon()
gchar * mate_icon_selection_get_icon (MateIconSelection * gis, gboolean full_path)
mate_icon_selection_get_icon: @gis: MateIconSelection to work with @full_path: boolean
Description: Gets the currently selected icon name, if full_path is true, it returns the full path to the icon, if none is selected it returns NULL
Returns: internal string, it must not be changed or freed or NULL
Definition at line 531 of file mate-icon-sel.c.
References _MateIconSelection::_priv, MATE_ICON_LIST, mate_icon_list_get_icon_filename(), mate_icon_list_get_selection(), MATE_IS_ICON_SELECTION, and NULL.
mate_icon_selection_new()
GtkWidget * mate_icon_selection_new (void)
mate_icon_selection_new:
Description: Creates a new icon selection widget, it uses MateIconList for the listing of icons
Returns: Returns the new object
Definition at line 141 of file mate-icon-sel.c.
References MATE_TYPE_ICON_SELECTION, and NULL.
mate_icon_selection_select_icon()
void mate_icon_selection_select_icon (MateIconSelection * gis, const gchar * filename)
mate_icon_selection_select_icon: @gis: MateIconSelection to work with @filename: icon filename
Description: Selects the icon @filename. This icon must have already been added and shown * (see @mate_icon_selection_show_icons)
Definition at line 562 of file mate-icon-sel.c.
References _MateIconSelection::_priv, MATE_ICON_LIST, mate_icon_list_get_icon_filename(), mate_icon_list_get_num_icons(), mate_icon_list_select_icon(), MATE_IS_ICON_SELECTION, and NULL.
mate_icon_selection_show_icons()
void mate_icon_selection_show_icons (MateIconSelection * gis)
mate_icon_selection_show_icons: @gis: MateIconSelection to work with
Description: Shows the icons inside the widget that were added with mate_icon_selection_add_defaults and mate_icon_selection_add_directory. Before this function is called the icons aren't actually added to the listing and can't be picked by the user.
Definition at line 393 of file mate-icon-sel.c.
References _, _add_atk_relation(), _MateIconSelection::_priv, FALSE, label, MATE_ICON_LIST, mate_icon_list_freeze(), mate_icon_list_thaw(), MATE_IS_ICON_SELECTION, and NULL.
mate_icon_selection_stop_loading()
void mate_icon_selection_stop_loading (MateIconSelection * gis)
mate_icon_selection_stop_loading: @gis: MateIconSelection to work with
Description: Stop the loading of images when we are in the loop in show_icons, otherwise it does nothing and is harmless, it should be used say if the dialog was hidden or when we want to quickly stop loading the images to do something else without destroying the icon selection object. The remaining icons can be shown by mate_icon_selection_show_icons.
Definition at line 481 of file mate-icon-sel.c.
References _MateIconSelection::_priv, MATE_IS_ICON_SELECTION, and NULL.