MATE Desktop Environment: matemixer-switch-private.h File Reference
matemixer-switch-private.h File Reference
#include <glib.h>
#include "matemixer-types.h"
Functions
void _mate_mixer_switch_set_active_option (MateMixerSwitch *sw, MateMixerSwitchOption *option)
Function Documentation
_mate_mixer_switch_set_active_option()
void _mate_mixer_switch_set_active_option (MateMixerSwitch * sw, MateMixerSwitchOption * option)
Definition at line 322 of file matemixer-switch.c.
References MATE_MIXER_IS_SWITCH, MATE_MIXER_IS_SWITCH_OPTION, NULL, option, _MateMixerSwitch::priv, and PROP_ACTIVE_OPTION.
Referenced by mate_mixer_switch_set_active_option(), oss_switch_load(), pulse_device_switch_set_active_profile(), and pulse_port_switch_set_active_port().