MATE Desktop Environment: mate-ui-init.c File Reference
mate-ui-init.c File Reference
#include <config.h>
#include <errno.h>
#include <stdarg.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include <sys/types.h>
#include <glib.h>
#include <sys/wait.h>
#include <glib/gi18n-lib.h>
#include <gdkconfig.h>
#include <libmate/libmate.h>
#include <matecomponent/matecomponent-ui-main.h>
#include <mateconf/mateconf-client.h>
#include "mate-client.h"
#include "mate-mateconf-ui.h"
#include "mate-ui-init.h"
#include "mate-stock-icons.h"
#include "mate-url.h"
#include <gdk-pixbuf/gdk-pixbuf.h>
#include "libmateuiP.h"
#include <gtk/gtk.h>
Enumerations
enum { ARG_DISABLE_CRASH_DIALOG =1 , ARG_DISPLAY }
Functions
G_GNUC_INTERNAL void _mate_stock_icons_init (void)
G_GNUC_INTERNAL void _mate_ui_gettext_init (gboolean)
const MateModuleInfo * libmateui_module_info_get (void)
int mate_init_with_popt_table (const char *app_id, const char *app_version, int argc, char **argv, const struct poptOption *options, int flags, poptContext *return_ctx)
const MateModuleInfo * mate_gtk_module_info_get (void)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ARG_DISABLE_CRASH_DIALOG
ARG_DISPLAY
Definition at line 102 of file mate-ui-init.c.
Function Documentation
_mate_stock_icons_init()
G_GNUC_INTERNAL void _mate_stock_icons_init (void)
Definition at line 149 of file mate-stock-icons.c.
References FALSE, and TRUE.
_mate_ui_gettext_init()
G_GNUC_INTERNAL void _mate_ui_gettext_init (gboolean bind_codeset)
Definition at line 107 of file mate-ui-init.c.
References FALSE, and TRUE.
Referenced by libmateui_module_info_get(), and mate_client_module_info_get().
libmateui_module_info_get()
const MateModuleInfo * libmateui_module_info_get (void)
Definition at line 153 of file mate-ui-init.c.
References _mate_ui_gettext_init(), ARG_DISABLE_CRASH_DIALOG, ARG_DISPLAY, FALSE, mate_client_module_info_get(), mate_mateconf_ui_module_info_get, N_, and NULL.
Referenced by main(), and main().
mate_gtk_module_info_get()
const MateModuleInfo * mate_gtk_module_info_get (void)
Definition at line 792 of file mate-ui-init.c.
Referenced by mate_client_module_info_get().
mate_init_with_popt_table()
int mate_init_with_popt_table (const char * app_id, const char * app_version, int argc, char ** argv, const struct poptOption * options, int flags, poptContext * return_ctx)
mate_init_with_popt_table: @app_id: Application id. @app_version: Application version. @argc: argument count (for example argc as received by main) @argv: argument vector (for example argv as received by main) @options: poptOption table with options to parse @flags: popt flags. @return_ctx: if non-NULL, the popt context is returned here.
Initializes the application. This sets up all of the MATE internals and prepares them (imlib, gdk, session-management, triggers, sound, user preferences).
Unlike mate_init, with mate_init_with_popt_table you can provide a table of popt options (popt is the command line argument parsing library).
Deprecated, use #mate_program_init with the LIBMATEUI_MODULE.
Returns: 0 (always)
Definition at line 767 of file mate-ui-init.c.
References LIBMATEUI_MODULE, and NULL.