MATE Desktop Environment: mate-mdi.h File Reference
mate-mdi.h File Reference
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include "mate-app.h"
#include "mate-app-helper.h"
#include "mate-mdi-child.h"
Classes
struct _MateMDI
struct _MateMDIClass
Macros
#define MATE_TYPE_MDI (mate_mdi_get_type ())
#define MATE_MDI(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_MDI, MateMDI))
#define MATE_MDI_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_MDI, MateMDIClass))
#define MATE_IS_MDI(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_MDI))
#define MATE_IS_MDI_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_MDI))
#define MATE_MDI_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_MDI, MateMDIClass))
Typedefs
typedef struct _MateMDI MateMDI
typedef struct _MateMDIClass MateMDIClass
Enumerations
enum MateMDIMode { MATE_MDI_NOTEBOOK , MATE_MDI_TOPLEVEL , MATE_MDI_MODAL , MATE_MDI_DEFAULT_MODE = 42 }
Functions
GType mate_mdi_get_type (void)
GtkObject * mate_mdi_new (const gchar *appname, const gchar *title)
void mate_mdi_set_mode (MateMDI *mdi, MateMDIMode mode)
void mate_mdi_set_menubar_template (MateMDI *mdi, MateUIInfo *menu_tmpl)
void mate_mdi_set_toolbar_template (MateMDI *mdi, MateUIInfo *tbar_tmpl)
void mate_mdi_set_child_menu_path (MateMDI *mdi, const gchar *path)
void mate_mdi_set_child_list_path (MateMDI *mdi, const gchar *path)
gint mate_mdi_add_view (MateMDI *mdi, MateMDIChild *child)
gint mate_mdi_add_toplevel_view (MateMDI *mdi, MateMDIChild *child)
gint mate_mdi_remove_view (MateMDI *mdi, GtkWidget *view, gint force)
GtkWidget * mate_mdi_get_active_view (MateMDI *mdi)
void mate_mdi_set_active_view (MateMDI *mdi, GtkWidget *view)
gint mate_mdi_add_child (MateMDI *mdi, MateMDIChild *child)
gint mate_mdi_remove_child (MateMDI *mdi, MateMDIChild *child, gint force)
gint mate_mdi_remove_all (MateMDI *mdi, gint force)
void mate_mdi_open_toplevel (MateMDI *mdi)
void mate_mdi_update_child (MateMDI *mdi, MateMDIChild *child)
MateMDIChild * mate_mdi_get_active_child (MateMDI *mdi)
MateMDIChild * mate_mdi_find_child (MateMDI *mdi, const gchar *name)
MateApp * mate_mdi_get_active_window (MateMDI *mdi)
void mate_mdi_register (MateMDI *mdi, GtkObject *object)
void mate_mdi_unregister (MateMDI *mdi, GtkObject *object)
MateApp * mate_mdi_get_app_from_view (GtkWidget *view)
MateMDIChild * mate_mdi_get_child_from_view (GtkWidget *view)
GtkWidget * mate_mdi_get_view_from_window (MateMDI *mdi, MateApp *app)
MateUIInfo * mate_mdi_get_menubar_info (MateApp *app)
MateUIInfo * mate_mdi_get_toolbar_info (MateApp *app)
MateUIInfo * mate_mdi_get_child_menu_info (MateApp *app)
Macro Definition Documentation
MATE_IS_MDI
#define MATE_IS_MDI (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_MDI))
Definition at line 43 of file mate-mdi.h.
MATE_IS_MDI_CLASS
#define MATE_IS_MDI_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_MDI))
Definition at line 44 of file mate-mdi.h.
MATE_MDI
#define MATE_MDI (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_MDI, MateMDI))
Definition at line 41 of file mate-mdi.h.
MATE_MDI_CLASS
#define MATE_MDI_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_MDI, MateMDIClass))
Definition at line 42 of file mate-mdi.h.
MATE_MDI_GET_CLASS
#define MATE_MDI_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_MDI, MateMDIClass))
Definition at line 45 of file mate-mdi.h.
MATE_TYPE_MDI
#define MATE_TYPE_MDI (mate_mdi_get_type ())
Definition at line 40 of file mate-mdi.h.
Typedef Documentation
MateMDI
typedef struct _MateMDI MateMDI
Definition at line 47 of file mate-mdi.h.
MateMDIClass
typedef struct _MateMDIClass MateMDIClass
Definition at line 48 of file mate-mdi.h.
Enumeration Type Documentation
MateMDIMode
enum MateMDIMode
Enumerator
MATE_MDI_NOTEBOOK
MATE_MDI_TOPLEVEL
MATE_MDI_MODAL
MATE_MDI_DEFAULT_MODE
Definition at line 50 of file mate-mdi.h.
Function Documentation
mate_mdi_add_child()
gint mate_mdi_add_child (MateMDI * mdi, MateMDIChild * child)
mate_mdi_add_child: @mdi: A pointer to a MateMDI object. @child: A pointer to a MateMDIChild to add to the MDI.
Description: Adds a new child to the MDI. No views are added: this has to be done with a call to mate_mdi_add_view. First an "add_child" signal is emitted to the MDI with a pointer to the child as its parameter. The child is added to the MDI only if the signal handler (if it exists) returns TRUE. If the handler returns FALSE, the child is not added to the MDI.
Return value: TRUE if the child was added successfully and FALSE otherwise.
Definition at line 1376 of file mate-mdi.c.
References _mate_mdi_child_list_menu_add_item(), ADD_CHILD, _MateMDI::children, FALSE, MATE_IS_MDI, MATE_IS_MDI_CHILD, NULL, _MateMDIChild::parent, and TRUE.
Referenced by mate_mdi_restore_state().
mate_mdi_add_toplevel_view()
gint mate_mdi_add_toplevel_view (MateMDI * mdi, MateMDIChild * child)
mate_mdi_add_toplevel_view: @mdi: A pointer to a MateMDI object. @child: A pointer to a MateMDIChild object to be added to the MDI.
Description: Creates a new view of the child and adds it to the MDI; it behaves the same way as mate_mdi_add_view in MATE_MDI_MODAL and MATE_MDI_TOPLEVEL modes, but in MATE_MDI_NOTEBOOK mode, the view is added in a new toplevel window unless the active one has no views in it.
Return value: TRUE if adding the view succeeded and FALSE otherwise.
Definition at line 1212 of file mate-mdi.c.
References _MateMDI::active_child, _MateMDI::active_window, ADD_VIEW, _MateApp::contents, FALSE, mate_app_set_contents(), MATE_IS_MDI, MATE_IS_MDI_CHILD, mate_mdi_child_add_view(), mate_mdi_child_remove_view(), MATE_MDI_MODAL, MATE_MDI_NOTEBOOK, mate_mdi_open_toplevel(), mate_mdi_remove_view(), MATE_MDI_TOPLEVEL, _MateMDI::mode, NULL, TRUE, and _MateMDIChild::views.
mate_mdi_add_view()
gint mate_mdi_add_view (MateMDI * mdi, MateMDIChild * child)
mate_mdi_add_view: @mdi: A pointer to a MateMDI object. @child: A pointer to a child.
Description: Creates a new view of the child and adds it to the MDI. MateMDIChild @child has to be added to the MDI with a call to mate_mdi_add_child before its views are added to the MDI. An "add_view" signal is emitted to the MDI after the view has been created, but before it is shown and added to the MDI, with a pointer to the created view as its parameter. The view is added to the MDI only if the signal handler (if it exists) returns TRUE. If the handler returns FALSE, the created view is destroyed and not added to the MDI.
Return value: TRUE if adding the view succeeded and FALSE otherwise.
Definition at line 1134 of file mate-mdi.c.
References _MateMDI::active_child, _MateMDI::active_window, ADD_VIEW, _MateApp::contents, FALSE, mate_app_set_contents(), MATE_IS_MDI, MATE_IS_MDI_CHILD, mate_mdi_child_add_view(), mate_mdi_child_remove_view(), MATE_MDI_MODAL, MATE_MDI_NOTEBOOK, mate_mdi_remove_view(), MATE_MDI_TOPLEVEL, _MateMDI::mode, NULL, TRUE, and _MateMDIChild::views.
Referenced by mate_mdi_remove_child().
mate_mdi_find_child()
MateMDIChild * mate_mdi_find_child (MateMDI * mdi, const gchar * name)
Definition at line 1599 of file mate-mdi.c.
References _MateMDI::children, MATE_IS_MDI, MATE_MDI_CHILD, name, and NULL.
mate_mdi_get_active_child()
MateMDIChild * mate_mdi_get_active_child (MateMDI * mdi)
mate_mdi_get_active_child: @mdi: A pointer to a MateMDI object.
Description: Returns a pointer to the active MateMDIChild object.
Return value: A pointer to the active MateMDIChild object. NULL, if there is none.
Definition at line 1761 of file mate-mdi.c.
References _MateMDI::active_view, MATE_IS_MDI, mate_mdi_get_child_from_view(), and NULL.
mate_mdi_get_active_view()
GtkWidget * mate_mdi_get_active_view (MateMDI * mdi)
mate_mdi_get_active_view: @mdi: A pointer to a MateMDI object.
Description: Returns a pointer to the active view (the one with the focus).
Return value: A pointer to a GtkWidget *.
Definition at line 1782 of file mate-mdi.c.
References _MateMDI::active_view, MATE_IS_MDI, and NULL.
mate_mdi_get_active_window()
MateApp * mate_mdi_get_active_window (MateMDI * mdi)
mate_mdi_get_active_window: @mdi: A pointer to a MateMDI object.
Description: Returns a pointer to the toplevel window containing the active view.
Return value: A pointer to a MateApp that has the focus.
Definition at line 1800 of file mate-mdi.c.
References _MateMDI::active_window, MATE_IS_MDI, and NULL.
mate_mdi_get_app_from_view()
MateApp * mate_mdi_get_app_from_view (GtkWidget * view)
mate_mdi_get_app_from_view: @view: A pointer to a GtkWidget.
Description: Returns the toplevel window for this view.
Return value: A pointer to the MateApp containg the specified view.
Definition at line 1952 of file mate-mdi.c.
References MATE_APP.
Referenced by mate_mdi_remove_view(), mate_mdi_set_active_view(), mate_mdi_set_mode(), and mate_mdi_update_child().
mate_mdi_get_child_from_view()
MateMDIChild * mate_mdi_get_child_from_view (GtkWidget * view)
mate_mdi_get_child_from_view: @view: A pointer to a GtkWidget.
Description: Returns a child that @view is a view of.
Return value: A pointer to the MateMDIChild the view belongs to.
Definition at line 1937 of file mate-mdi.c.
References MATE_MDI_CHILD, and MATE_MDI_CHILD_KEY.
Referenced by mate_mdi_get_active_child(), and mate_mdi_remove_view().
mate_mdi_get_child_menu_info()
MateUIInfo * mate_mdi_get_child_menu_info (MateApp * app)
mate_mdi_get_child_menu_info: @app: A pointer to a MateApp widget created by the MDI.
Return value: A MateUIInfo array used for child's menus in @app if they have been created with a template. NULL otherwise.
Definition at line 2022 of file mate-mdi.c.
References MATE_MDI_CHILD_MENU_INFO_KEY.
mate_mdi_get_menubar_info()
MateUIInfo * mate_mdi_get_menubar_info (MateApp * app)
mate_mdi_get_menubar_info: @app: A pointer to a MateApp widget created by the MDI.
Return value: A MateUIInfo array used for menubar in @app if the menubar has been created with a template. NULL otherwise.
Definition at line 1996 of file mate-mdi.c.
References MATE_MDI_MENUBAR_INFO_KEY.
mate_mdi_get_toolbar_info()
MateUIInfo * mate_mdi_get_toolbar_info (MateApp * app)
mate_mdi_get_toolbar_info: @app: A pointer to a MateApp widget created by the MDI.
Return value: A MateUIInfo array used for toolbar in @app if the toolbar has been created with a template. NULL otherwise.
Definition at line 2009 of file mate-mdi.c.
References MATE_MDI_TOOLBAR_INFO_KEY.
mate_mdi_get_type()
GType mate_mdi_get_type (void)
mate_mdi_get_view_from_window()
GtkWidget * mate_mdi_get_view_from_window (MateMDI * mdi, MateApp * app)
mate_mdi_get_view_from_window: @mdi: A pointer to a MateMDI object. @app: A pointer to a MateApp widget.
Description: Returns the pointer to the view in the MDI toplevel window @app. If the mode is set to MATE_MDI_NOTEBOOK, the view in the current page is returned.
Return value: A pointer to a view.
Definition at line 1970 of file mate-mdi.c.
References _MateApp::contents, MATE_IS_APP, MATE_IS_MDI, MATE_MDI_MODAL, MATE_MDI_NOTEBOOK, MATE_MDI_TOPLEVEL, _MateMDI::mode, and NULL.
Referenced by mate_mdi_remove_view(), and mate_mdi_save_state().
mate_mdi_new()
GtkObject * mate_mdi_new (const gchar * appname, const gchar * title)
mate_mdi_new: @appname: Application name as used in filenames and paths. @title: Title of the application windows.
Description: Creates a new MDI object. @appname and @title are used for MDI's calling mate_app_new().
Return value: A pointer to a new MateMDI object.
Definition at line 286 of file mate-mdi.c.
References _MateMDI::appname, MATE_TYPE_MDI, NULL, and _MateMDI::title.
Referenced by main().
mate_mdi_open_toplevel()
void mate_mdi_open_toplevel (MateMDI * mdi)
mate_mdi_open_toplevel: @mdi: A pointer to a MateMDI object.
Description: Opens a new toplevel window (unless in MATE_MDI_MODAL mode and a toplevel window is already open). This is usually used only for opening the initial window on startup (just before calling gtkmain()) if no windows were open because a session was restored or children were added because of command line args).
Definition at line 1530 of file mate-mdi.c.
References _MateMDI::active_window, MATE_IS_MDI, MATE_MDI_MODAL, MATE_MDI_NOTEBOOK, _MateMDI::mode, NULL, and _MateMDI::windows.
Referenced by main(), mate_mdi_add_toplevel_view(), and mate_mdi_set_mode().
mate_mdi_register()
void mate_mdi_register (MateMDI * mdi, GtkObject * object)
mate_mdi_register: @mdi: A pointer to a MateMDI object. @object: Object to register.
Description: Registers GtkObject @object with MDI. This is mostly intended for applications that open other windows besides those opened by the MDI and want to continue to run even when no MDI windows exist (an example of this would be GIMP's window with tools, if the pictures were MDI children). As long as there is an object registered with the MDI, the MDI will not destroy itself when the last of its windows is closed. If no objects are registered, closing the last MDI window results in MDI being destroyed.
Definition at line 1908 of file mate-mdi.c.
References _MateMDI::registered.
mate_mdi_remove_all()
gint mate_mdi_remove_all (MateMDI * mdi, gint force)
mate_mdi_remove_all: @mdi: A pointer to a MateMDI object. @force: If TRUE, the "remove_child" signal is not emitted
Description: Removes all children and all views from the MDI. A "remove_child" signal is emitted to the MDI for each child before actually trying to remove any. If signal handlers for all children (if they exist and the @force is set to FALSE) return TRUE, all children and their views are removed and none otherwise.
Return value: TRUE if the removal was successful and FALSE otherwise.
Definition at line 1486 of file mate-mdi.c.
References _MateMDI::children, FALSE, MATE_IS_MDI, MATE_MDI_CHILD, mate_mdi_remove_child(), NULL, REMOVE_CHILD, and TRUE.
mate_mdi_remove_child()
gint mate_mdi_remove_child (MateMDI * mdi, MateMDIChild * child, gint force)
mate_mdi_remove_child: @mdi: A pointer to a MateMDI object. @child: Child to remove. @force: If TRUE, the "remove_child" signal is not emitted
Description: Removes a child and all of its views from the MDI. A "remove_child" signal is emitted to the MDI with @child as its parameter before actually removing the child. The child is removed only if the signal handler (if it exists and the @force is set to FALSE) returns TRUE.
Return value: TRUE if the removal was successful and FALSE otherwise.
Definition at line 1416 of file mate-mdi.c.
References _mate_mdi_child_list_menu_remove_item(), _MateMDI::active_child, _MateMDI::active_window, _MateMDI::children, FALSE, mate_app_set_contents(), MATE_IS_MDI, MATE_IS_MDI_CHILD, mate_mdi_add_view(), MATE_MDI_MODAL, mate_mdi_remove_view(), _MateMDI::mode, NULL, _MateMDIChild::parent, REMOVE_CHILD, TRUE, and _MateMDIChild::views.
Referenced by mate_mdi_remove_all().
mate_mdi_remove_view()
gint mate_mdi_remove_view (MateMDI * mdi, GtkWidget * view, gint force)
mate_mdi_remove_view: @mdi: A pointer to a MateMDI object. @view: View to remove. @force: If TRUE, the "remove_view" signal is not emitted.
Description: Removes a view from an MDI. A "remove_view" signal is emitted to the MDI before actually removing view. The view is removed only if the signal handler (if it exists and the @force is set to FALSE) returns TRUE.
Return value: TRUE if the view was removed and FALSE otherwise.
Definition at line 1288 of file mate-mdi.c.
References _MateMDI::active_view, _MateMDI::active_window, _MateApp::contents, FALSE, MATE_IS_MDI, mate_mdi_child_remove_view(), mate_mdi_get_app_from_view(), mate_mdi_get_child_from_view(), mate_mdi_get_view_from_window(), MATE_MDI_MODAL, MATE_MDI_NOTEBOOK, mate_mdi_set_active_view(), MATE_MDI_TOPLEVEL, _MateMDI::mode, NULL, _MateMDI::registered, REMOVE_VIEW, TRUE, and _MateMDI::windows.
Referenced by mate_mdi_add_toplevel_view(), mate_mdi_add_view(), mate_mdi_remove_child(), mate_mdi_set_active_view(), and mate_mdi_set_mode().
mate_mdi_set_active_view()
void mate_mdi_set_active_view (MateMDI * mdi, GtkWidget * view)
mate_mdi_set_active_view: @mdi: A pointer to an MDI object. @view: A pointer to the view that is to become the active one.
Description: Sets the active view to @view. It also raises the window containing it and gives it focus.
Definition at line 1082 of file mate-mdi.c.
References _MateMDI::active_window, _MateApp::contents, mate_app_set_contents(), MATE_IS_MDI, mate_mdi_get_app_from_view(), MATE_MDI_MODAL, MATE_MDI_NOTEBOOK, mate_mdi_remove_view(), _MateMDI::mode, NULL, and TRUE.
Referenced by mate_mdi_remove_view(), and mate_mdi_restore_state().
mate_mdi_set_child_list_path()
void mate_mdi_set_child_list_path (MateMDI * mdi, const gchar * path)
mate_mdi_set_child_list_path: @mdi: A pointer to a MateMDI object. @path: A menu path where the child list menu should be inserted
Description: Sets the position for insertion of menu items used to activate the MDI children that were added to the MDI. See mate_app_find_menu_pos for details on menu paths. If the path is not set or set to NULL, these menu items aren't going to be inserted in the MDI menu structure. Note that if you want all menu items to be inserted in their own submenu, you have to create that submenu (and leave it empty, of course).
Definition at line 1884 of file mate-mdi.c.
References _MateMDI::child_list_path, MATE_IS_MDI, and NULL.
Referenced by main().
mate_mdi_set_child_menu_path()
void mate_mdi_set_child_menu_path (MateMDI * mdi, const gchar * path)
mate_mdi_set_child_menu_path: @mdi: A pointer to a MateMDI object. @path: A menu path where the child menus should be inserted.
Description: Sets the desired position of child-specific menus (which are added to and removed from the main menus as views of different children are activated). See mate_app_find_menu_pos for details on menu paths.
Definition at line 1862 of file mate-mdi.c.
References _MateMDI::child_menu_path, MATE_IS_MDI, and NULL.
Referenced by main().
mate_mdi_set_menubar_template()
void mate_mdi_set_menubar_template (MateMDI * mdi, MateUIInfo * menu_tmpl)
mate_mdi_set_menubar_template: @mdi: A pointer to a MateMDI object. @menu_tmpl: A MateUIInfo array describing the menu.
Description: This function sets the template for menus that appear in each toplevel window to menu_template. For each new toplevel window created by the MDI, this structure is copied, the menus are created with mate_app_create_menus_with_data() function with mdi as the callback user data. Finally, the pointer to the copy is assigned to the new toplevel window (a MateApp widget) and can be obtained by calling &mate_mdi_get_menubar_info.
Definition at line 1822 of file mate-mdi.c.
References MATE_IS_MDI, _MateMDI::menu_template, and NULL.
Referenced by main().
mate_mdi_set_mode()
void mate_mdi_set_mode (MateMDI * mdi, MateMDIMode mode)
mate_mdi_set_mode: @mdi: A pointer to a MateMDI object. @mode: New mode.
Description: Sets the MDI mode to mode. Possible values are MATE_MDI_TOPLEVEL, MATE_MDI_NOTEBOOK, MATE_MDI_MODAL and MATE_MDI_DEFAULT.
Definition at line 1626 of file mate-mdi.c.
References _MateMDI::active_view, _MateMDI::active_window, _MateMDI::children, _MateApp::contents, _MateApp::dock, MATE_APP, mate_app_set_contents(), MATE_IS_MDI, MATE_MDI_CHILD, mate_mdi_get_app_from_view(), MATE_MDI_MODAL, MATE_MDI_NOTEBOOK, mate_mdi_open_toplevel(), mate_mdi_remove_view(), MATE_MDI_TOPLEVEL, _MateMDI::mode, NULL, TRUE, _MateMDIChild::views, and _MateMDI::windows.
Referenced by main(), and mate_mdi_restore_state().
mate_mdi_set_toolbar_template()
void mate_mdi_set_toolbar_template (MateMDI * mdi, MateUIInfo * tbar_tmpl)
mate_mdi_set_toolbar_template: @mdi: A pointer to a MateMDI object. @tbar_tmpl: A MateUIInfo array describing the toolbar.
Description: This function sets the template for toolbar that appears in each toplevel window to toolbar_template. For each new toplevel window created by the MDI, this structure is copied, the toolbar is created with mate_app_create_toolbar_with_data() function with mdi as the callback user data. Finally, the pointer to the copy is assigned to the new toplevel window (a MateApp widget) and can be retrieved with a call to &mate_mdi_get_toolbar_info.
Definition at line 1844 of file mate-mdi.c.
References MATE_IS_MDI, NULL, and _MateMDI::toolbar_template.
mate_mdi_unregister()
void mate_mdi_unregister (MateMDI * mdi, GtkObject * object)
mate_mdi_unregister: @mdi: A pointer to a MateMDI object. @object: Object to unregister.
Description: Removes GtkObject @object from the list of registered objects.
Definition at line 1922 of file mate-mdi.c.
References _MateMDI::registered.
mate_mdi_update_child()
void mate_mdi_update_child (MateMDI * mdi, MateMDIChild * child)
mate_mdi_update_child: @mdi: A pointer to a MateMDI object. @child: Child to update.
Description: Updates all notebook labels of @child's views and their window titles after its name changes. It is not required if mate_mdi_child_set_name() is used for setting the child's name.
Definition at line 1555 of file mate-mdi.c.
References MATE_IS_MDI, MATE_IS_MDI_CHILD, mate_mdi_get_app_from_view(), MATE_MDI_MODAL, MATE_MDI_TOPLEVEL, _MateMDI::mode, _MateMDIChild::name, NULL, _MateMDI::title, and _MateMDIChild::views.
Referenced by mate_mdi_child_set_name().