MATE Desktop Environment: mate-app-helper.c File Reference
mate-app-helper.c File Reference
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <mateconf/mateconf.h>
#include <mateconf/mateconf-client.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <libxml/parser.h>
#include <libxml/tree.h>
#include <libmate/mate-util.h>
#include <libmate/mate-config.h>
#include <glib/gi18n.h>
#include <libmate/mate-program.h>
#include <libmate/mate-mateconf.h>
#include <libmate/mate-init.h>
#include "mate-app.h"
#include "mate-app-helper.h"
#include "mate-uidefs.h"
#include "mate-stock-icons.h"
#include "mate-mateconf-ui.h"
Macros
#define _(x) dgettext (GETTEXT_PACKAGE, x)
#define _(x) gettext (x)
Functions
void mate_app_install_statusbar_menu_hints (GtkStatusbar *bar, MateUIInfo *uiinfo)
void mate_app_ui_configure_configurable (MateUIInfo *uiinfo)
void mate_app_install_appbar_menu_hints (MateAppBar *appbar, MateUIInfo *uiinfo)
void mate_app_install_menu_hints (MateApp *app, MateUIInfo *uiinfo)
void mate_accelerators_sync (void)
void mate_app_fill_menu (GtkMenuShell *menu_shell, MateUIInfo *uiinfo, GtkAccelGroup *accel_group, gboolean uline_accels, gint pos)
void mate_app_fill_menu_with_data (GtkMenuShell *menu_shell, MateUIInfo *uiinfo, GtkAccelGroup *accel_group, gboolean uline_accels, gint pos, gpointer user_data)
void mate_app_fill_menu_custom (GtkMenuShell *menu_shell, MateUIInfo *uiinfo, MateUIBuilderData *uibdata, GtkAccelGroup *accel_group, gboolean uline_accels, gint pos)
void mate_app_create_menus (MateApp *app, MateUIInfo *uiinfo)
void mate_app_create_menus_interp (MateApp *app, MateUIInfo *uiinfo, GtkCallbackMarshal relay_func, gpointer data, GDestroyNotify destroy_func)
void mate_app_create_menus_with_data (MateApp *app, MateUIInfo *uiinfo, gpointer user_data)
void mate_app_create_menus_custom (MateApp *app, MateUIInfo *uiinfo, MateUIBuilderData *uibdata)
void mate_app_fill_toolbar (GtkToolbar *toolbar, MateUIInfo *uiinfo, GtkAccelGroup *accel_group)
void mate_app_fill_toolbar_with_data (GtkToolbar *toolbar, MateUIInfo *uiinfo, GtkAccelGroup *accel_group, gpointer user_data)
void mate_app_fill_toolbar_custom (GtkToolbar *toolbar, MateUIInfo *uiinfo, MateUIBuilderData *uibdata, GtkAccelGroup *accel_group)
void mate_app_create_toolbar (MateApp *app, MateUIInfo *uiinfo)
void mate_app_create_toolbar_interp (MateApp *app, MateUIInfo *uiinfo, GtkCallbackMarshal relay_func, gpointer data, GDestroyNotify destroy_func)
void mate_app_create_toolbar_with_data (MateApp *app, MateUIInfo *uiinfo, gpointer user_data)
void mate_app_create_toolbar_custom (MateApp *app, MateUIInfo *uiinfo, MateUIBuilderData *uibdata)
GtkWidget * mate_app_find_menu_pos (GtkWidget *parent, const gchar *path, gint *pos)
void mate_app_remove_menus (MateApp *app, const gchar *path, gint items)
void mate_app_remove_menu_range (MateApp *app, const gchar *path, gint start, gint items)
void mate_app_insert_menus_custom (MateApp *app, const gchar *path, MateUIInfo *uiinfo, MateUIBuilderData *uibdata)
void mate_app_insert_menus (MateApp *app, const gchar *path, MateUIInfo *menuinfo)
void mate_app_insert_menus_with_data (MateApp *app, const gchar *path, MateUIInfo *menuinfo, gpointer data)
void mate_app_insert_menus_interp (MateApp *app, const gchar *path, MateUIInfo *menuinfo, GtkCallbackMarshal relay_func, gpointer data, GDestroyNotify destroy_func)
const gchar * mate_app_helper_gettext (const gchar *str)
void mate_app_setup_toolbar (GtkToolbar *toolbar, MateComponentDockItem *dock_item)
Macro Definition Documentation
_ [1/2]
#define _ (x) dgettext (GETTEXT_PACKAGE, x)
Definition at line 2507 of file mate-app-helper.c.
_ [2/2]
#define _ (x) gettext (x)
Definition at line 2507 of file mate-app-helper.c.
Function Documentation
mate_accelerators_sync()
void mate_accelerators_sync (void)
mate_accelerators_sync:
Flush the accelerator definitions into the application specific configuration file $HOME/.config/mate/accels/<app-id>.
Definition at line 929 of file mate-app-helper.c.
References NULL.
mate_app_create_menus()
void mate_app_create_menus (MateApp * app, MateUIInfo * uiinfo)
mate_app_create_menus @app: A MateApp instance representing the current application. @uiinfo: The first in an array MateUIInfo instances containing the menu data.
Description: Constructs a menu bar and attaches it to the specified application window.
Definition at line 1524 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_create_menus_custom(), MATE_IS_APP, NULL, and _MateUIBuilderData::relay_func.
mate_app_create_menus_custom()
void mate_app_create_menus_custom (MateApp * app, MateUIInfo * uiinfo, MateUIBuilderData * uibdata)
mate_app_create_menus_custom @app: A MateApp instance representing the current application. @uiinfo: The first in an array MateUIInfo instances containing the menu data. @uibdata: An appropriate MateUIBuilderData instance.
Identical to mate_app_create_menus(), except that @uibdata is also specified for creating the signal handlers. Mostly for use by language bindings.
Definition at line 1665 of file mate-app-helper.c.
References _MateApp::accel_group, MATE_APP, mate_app_fill_menu_custom(), mate_app_set_menus(), MATE_IS_APP, mate_mateconf_get_bool, NULL, and TRUE.
Referenced by mate_app_create_menus(), mate_app_create_menus_interp(), and mate_app_create_menus_with_data().
mate_app_create_menus_interp()
void mate_app_create_menus_interp (MateApp * app, MateUIInfo * uiinfo, GtkCallbackMarshal relay_func, gpointer data, GDestroyNotify destroy_func)
mate_app_create_menus_interp @app: A MateApp instance, representing the current application. @uiinfo: The first item in an array of MateUIInfo structures describing the menu bar. @relay_func: A marshaller for the signal callbacks. @data: Application specific data passed to the signal callback functions. @destroy_func: The function to call when the menu bar is destroyed.
Identical to mate_app_create_menus(), except that extra functions and data can be passed in for finer control of the destruction and marshalling.
Definition at line 1556 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, data, _MateUIBuilderData::destroy_func, _MateUIBuilderData::is_interp, mate_app_create_menus_custom(), MATE_IS_APP, NULL, _MateUIBuilderData::relay_func, and TRUE.
mate_app_create_menus_with_data()
void mate_app_create_menus_with_data (MateApp * app, MateUIInfo * uiinfo, gpointer user_data)
mate_app_create_menus_with_data @app: A MateApp instance representing the current application. @uiinfo: The first in an array MateUIInfo instances containing the menu data. @user_data: Application-specific data that is passed to every callback function.
Identical to mate_app_create_menus(), except that @user_data is passed to all the callback functions when signals are emitted.
Definition at line 1589 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_create_menus_custom(), MATE_IS_APP, NULL, _MateUIBuilderData::relay_func, and user_data.
mate_app_create_toolbar()
void mate_app_create_toolbar (MateApp * app, MateUIInfo * uiinfo)
mate_app_create_toolbar @app: A MateApp instance. @uiinfo: A MateUIInfo array specifying the contents of the toolbar.
Description: Constructs a toolbar and attaches it to the specified application window.
Definition at line 1931 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_create_toolbar_custom(), MATE_IS_APP, NULL, and _MateUIBuilderData::relay_func.
mate_app_create_toolbar_custom()
void mate_app_create_toolbar_custom (MateApp * app, MateUIInfo * uiinfo, MateUIBuilderData * uibdata)
mate_app_create_toolbar_custom @app: A MateApp instance. @uiinfo: A MateUIInfo array specifying the contents of the toolbar. @uibdata: A MateUIBuilderData instance specifying the handlers to use for the toolbar.
Description: Constructs a toolbar and attaches it to the @app window, using @uibdata builder data – intended for language bindings.
Definition at line 2025 of file mate-app-helper.c.
References _MateApp::accel_group, mate_app_fill_toolbar_custom(), mate_app_set_toolbar(), MATE_IS_APP, and NULL.
Referenced by mate_app_create_toolbar(), mate_app_create_toolbar_interp(), and mate_app_create_toolbar_with_data().
mate_app_create_toolbar_interp()
void mate_app_create_toolbar_interp (MateApp * app, MateUIInfo * uiinfo, GtkCallbackMarshal relay_func, gpointer data, GDestroyNotify destroy_func)
mate_app_create_toolbar_interp @app: A MateApp instance. @uiinfo: A MateUIInfo array specifying the contents of the toolbar. @relay_func: Argument marshalling function. @data: Application specific data to pass to signal callbacks. @destroy_func: The function to call when the toolbar is destroyed.
Description: Constructs a toolbar and attaches it to the specified application window – this version is intended for language bindings.
Definition at line 1962 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, data, _MateUIBuilderData::destroy_func, _MateUIBuilderData::is_interp, mate_app_create_toolbar_custom(), MATE_IS_APP, NULL, _MateUIBuilderData::relay_func, and TRUE.
mate_app_create_toolbar_with_data()
void mate_app_create_toolbar_with_data (MateApp * app, MateUIInfo * uiinfo, gpointer user_data)
mate_app_create_toolbar_with_data @app: A MateApp instance. @uiinfo: A MateUIInfo array specifying the contents of the toolbar. @user_data: Application specific data to be sent to each signal callback function.
Description: Constructs a toolbar, sets all the user data pointers to @user_data, and attaches it to @app.
Definition at line 1994 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_create_toolbar_custom(), MATE_IS_APP, NULL, _MateUIBuilderData::relay_func, and user_data.
mate_app_fill_menu()
void mate_app_fill_menu (GtkMenuShell * menu_shell, MateUIInfo * uiinfo, GtkAccelGroup * accel_group, gboolean uline_accels, gint pos)
mate_app_fill_menu @menu_shell: A #GtkMenuShell instance (a menu bar). @uiinfo: A pointer to the first element in an array of MateUIInfo structures. The last element of the array should have a type of MATE_APP_UI_ENDOFINFO. @accel_group: A #GtkAccelGroup. @uline_accels: TRUE if underline accelerators will be drawn for the menu item labels. @pos: The position in the menu bar at which to start inserting items.
Description: Fills the specified @menu_shell with items created from the specified @uiinfo, inserting them from the item number @pos on. The @accel_ group will be used as the accel group for all newly created sub menus and serves as the global accel group for all menu item hotkeys. If it is passed as NULL, global hotkeys will be disabled.
Definition at line 1251 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_fill_menu_custom(), NULL, and _MateUIBuilderData::relay_func.
mate_app_fill_menu_custom()
void mate_app_fill_menu_custom (GtkMenuShell * menu_shell, MateUIInfo * uiinfo, MateUIBuilderData * uibdata, GtkAccelGroup * accel_group, gboolean uline_accels, gint pos)
mate_app_fill_menu_custom @menu_shell: A #GtkMenuShell instance (a menu bar). @uiinfo: A pointer to the first element in an array of MateUIInfo structures. The last element of the array should have a type of MATE_APP_UI_ENDOFINFO. @uibdata: A #MateUIInfoBuilderData instance. @accel_group: A #GtkAccelGroup. @uline_accels: TRUE if underline accelerators will be drawn for the menu item labels. @pos: The position in the menu bar at which to start inserting items.
Description: Fills the specified menu shell with items created from the specified @uiinfo, inserting them from item number @pos on and using the specified builder data (@uibdata) – this is intended for language bindings.
The other parameters have the same meaning as in mate_app_fill_menu().
Definition at line 1391 of file mate-app-helper.c.
References FALSE, mate_app_fill_menu_custom(), MATE_APP_UI_BUILDER_DATA, MATE_APP_UI_ENDOFINFO, MATE_APP_UI_HELP, MATE_APP_UI_INCLUDE, MATE_APP_UI_ITEM, MATE_APP_UI_ITEM_CONFIGURABLE, MATE_APP_UI_RADIOITEMS, MATE_APP_UI_SEPARATOR, MATE_APP_UI_SUBTREE, MATE_APP_UI_SUBTREE_STOCK, MATE_APP_UI_TOGGLEITEM, mate_mateconf_get_bool, MateUIInfo::moreinfo, NULL, MateUIInfo::type, and MateUIInfo::widget.
Referenced by mate_app_create_menus_custom(), mate_app_fill_menu(), mate_app_fill_menu_custom(), mate_app_fill_menu_with_data(), mate_app_insert_menus_custom(), and mate_popup_menu_append().
mate_app_fill_menu_with_data()
void mate_app_fill_menu_with_data (GtkMenuShell * menu_shell, MateUIInfo * uiinfo, GtkAccelGroup * accel_group, gboolean uline_accels, gint pos, gpointer user_data)
mate_app_fill_menu_with_data @menu_shell: A #GtkMenuShell instance (a menu bar). @uiinfo: A pointer to the first element in an array of MateUIInfo structures. The last element of the array should have a type of MATE_APP_UI_ENDOFINFO. @accel_group: A #GtkAccelGroup. @uline_accels: TRUE if underline accelerators will be drawn for the menu item labels. @pos: The position in the menu bar at which to start inserting items. @user_data: Some application-specific data.
Description: This is the same as mate_app_fill_menu(), except that all the user data pointers are filled with the value of @user_data.
Definition at line 1295 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_fill_menu_custom(), NULL, _MateUIBuilderData::relay_func, and user_data.
mate_app_fill_toolbar()
void mate_app_fill_toolbar (GtkToolbar * toolbar, MateUIInfo * uiinfo, GtkAccelGroup * accel_group)
mate_app_fill_toolbar @toolbar: A #GtkToolbar instance. @uiinfo: An array of MateUIInfo structures containing the items for the toolbar. @accel_group: A #GtkAccelGroup for holding the accelerator keys of the items (or NULL).
Fills @toolbar with buttons specified in @uiinfo. If @accel_group is not NULL, the items' accelrator keys are put into it.
Definition at line 1809 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_fill_toolbar_custom(), NULL, and _MateUIBuilderData::relay_func.
mate_app_fill_toolbar_custom()
void mate_app_fill_toolbar_custom (GtkToolbar * toolbar, MateUIInfo * uiinfo, MateUIBuilderData * uibdata, GtkAccelGroup * accel_group)
mate_app_fill_toolbar_custom @toolbar: A #GtkToolbar instance. @uiinfo: An array of MateUIInfo structures containing the items for the toolbar. @uibdata: The MateUIBuilderData data for the toolbar. @accel_group: A #GtkAccelGroup for holding the accelerator keys of the items (or NULL).
The same as mate_app_fill_toolbar(), except that the sepcified @uibdata instance is used. This is mostly for the benefit of language bindings.
Definition at line 1875 of file mate-app-helper.c.
References FALSE, mate_app_fill_toolbar_custom(), mate_app_setup_toolbar(), MATE_APP_UI_BUILDER_DATA, MATE_APP_UI_ENDOFINFO, MATE_APP_UI_INCLUDE, MATE_APP_UI_ITEM, MATE_APP_UI_RADIOITEMS, MATE_APP_UI_SEPARATOR, MATE_APP_UI_TOGGLEITEM, MateUIInfo::moreinfo, NULL, MateUIInfo::type, and MateUIInfo::widget.
Referenced by mate_app_create_toolbar_custom(), mate_app_fill_toolbar(), mate_app_fill_toolbar_custom(), and mate_app_fill_toolbar_with_data().
mate_app_fill_toolbar_with_data()
void mate_app_fill_toolbar_with_data (GtkToolbar * toolbar, MateUIInfo * uiinfo, GtkAccelGroup * accel_group, gpointer user_data)
mate_app_fill_toolbar_with_data @toolbar: A #GtkToolbar instance. @uiinfo: An array of MateUIInfo structures containing the items for the toolbar. @accel_group: A #GtkAccelGroup for holding the accelerator keys of the items (or NULL). @user_data: Application specific data.
The same as mate_app_fill_toolbar(), except that the user data pointers in the signal handlers are set to @user_data.
Definition at line 1842 of file mate-app-helper.c.
References _MateUIBuilderData::connect_func, _MateUIBuilderData::data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_fill_toolbar_custom(), NULL, _MateUIBuilderData::relay_func, and user_data.
mate_app_find_menu_pos()
GtkWidget * mate_app_find_menu_pos (GtkWidget * parent, const gchar * path, gint * pos)
mate_app_find_menu_pos @parent: Root menu shell widget containing menu items to be searched. @path: Specifies the target menu item by menu path. @pos: Used to hold the returned menu items' position.
Description: Finds a menu item described by path starting in the #GtkMenuShell top and returns its parent #GtkMenuShell and the position after this item in @pos. The meaning of @pos is that a subsequent call to gtk_menu_shell_insert(p, w, pos) would then insert widget w in GtkMenuShell p right after the menu item described by path.
Returns: The parent menu shell of @path.
Definition at line 2099 of file mate-app-helper.c.
References item, L_, label, mate_app_find_menu_pos(), NULL, and strchr.
Referenced by _mate_mdi_child_list_menu_add_item(), _mate_mdi_child_list_menu_remove_item(), mate_app_find_menu_pos(), mate_app_insert_menus_custom(), mate_app_remove_menu_range(), and mate_app_remove_menus().
mate_app_helper_gettext()
const gchar * mate_app_helper_gettext (const gchar * str)
Definition at line 2418 of file mate-app-helper.c.
mate_app_insert_menus()
void mate_app_insert_menus (MateApp * app, const gchar * path, MateUIInfo * menuinfo)
mate_app_insert_menus @app: A MateApp instance. @path: A path to the menu item concerned. @menuinfo: A MateUIInfo array describing the menus.
Insert the menus given by @menuinfo beginning at @path into the pre-existing @app.
Definition at line 2344 of file mate-app-helper.c.
References FALSE, mate_app_insert_menus_custom(), and NULL.
mate_app_insert_menus_custom()
void mate_app_insert_menus_custom (MateApp * app, const gchar * path, MateUIInfo * uiinfo, MateUIBuilderData * uibdata)
mate_app_insert_menus_custom @app: A MateApp instance. @path: A path to the menu item concerned. @uiinfo: A MateUIInfo array describing the menus. @uibdata: A MateUIBuilderData instance describing the functions to attach as the menu's callbacks.
Description: Inserts menus described by @uiinfo in existing @app's menu structure right after the item described by @path. The @uibdata parameter makes this, again, most useful for language bindings.
Definition at line 2309 of file mate-app-helper.c.
References _MateApp::accel_group, mate_app_fill_menu_custom(), mate_app_find_menu_pos(), MATE_IS_APP, _MateApp::menubar, NULL, and TRUE.
Referenced by mate_app_insert_menus(), mate_app_insert_menus_interp(), and mate_app_insert_menus_with_data().
mate_app_insert_menus_interp()
void mate_app_insert_menus_interp (MateApp * app, const gchar * path, MateUIInfo * menuinfo, GtkCallbackMarshal relay_func, gpointer data, GDestroyNotify destroy_func)
mate_app_insert_menus_interp @app: A MateApp instance. @path: A path to the menu item concerned. @menuinfo: A MateUIInfo array describing the menus. @relay_func: A custom marshallar for signal data., @data: Application-specific data to send to each signal callback. @destroy_func: The function to call when the menu item is destroyed.
THe same as mate_app_insert_menus(), except that the given functions are attached to each menu item. Mostly of use for language bindings.
Definition at line 2399 of file mate-app-helper.c.
References _MateUIBuilderData::data, data, _MateUIBuilderData::destroy_func, FALSE, _MateUIBuilderData::is_interp, mate_app_insert_menus_custom(), NULL, _MateUIBuilderData::relay_func, and TRUE.
mate_app_insert_menus_with_data()
void mate_app_insert_menus_with_data (MateApp * app, const gchar * path, MateUIInfo * menuinfo, gpointer data)
mate_app_insert_menus_with_data @app: A MateApp instance. @path: A path to the menu item concerned. @menuinfo: A MateUIInfo array describing the menus. @data: Application specific data to send to each signal callback.
This is the same as mate_app_insert_menus(), except that the specified @data is passed to each signal callback.
Definition at line 2370 of file mate-app-helper.c.
References _MateUIBuilderData::data, data, FALSE, mate_app_insert_menus_custom(), and NULL.
mate_app_install_appbar_menu_hints()
void mate_app_install_appbar_menu_hints (MateAppBar * appbar, MateUIInfo * uiinfo)
mate_app_install_appbar_menu_hints @appbar: An existing MateAppBar instance. @uiinfo: A MateUIInfo array of a menu for which hints will be set.
Description: Install menu hints for the given @appbar object. This function cannot just be called automatically, since it is impossible to reliably find the correct @appbar.
Definition at line 842 of file mate-app-helper.c.
References mate_app_install_appbar_menu_hints(), mate_app_ui_configure_configurable(), MATE_APP_UI_ENDOFINFO, MATE_APP_UI_HELP, MATE_APP_UI_INCLUDE, MATE_APP_UI_ITEM, MATE_APP_UI_ITEM_CONFIGURABLE, MATE_APP_UI_RADIOITEMS, MATE_APP_UI_SEPARATOR, MATE_APP_UI_SUBTREE, MATE_APP_UI_SUBTREE_STOCK, MATE_APP_UI_TOGGLEITEM, MATE_IS_APPBAR, MateUIInfo::moreinfo, NULL, and MateUIInfo::type.
Referenced by mate_app_install_appbar_menu_hints(), and mate_app_install_menu_hints().
mate_app_install_menu_hints()
void mate_app_install_menu_hints (MateApp * app, MateUIInfo * uiinfo)
mate_app_install_menu_hints @app: An existing MateAppBar instance. @uiinfo: A MateUIInfo array of a menu for which hints will be set.
Description: Set menu hints for the @app object's attached status bar.
Definition at line 896 of file mate-app-helper.c.
References mate_app_install_appbar_menu_hints(), mate_app_install_statusbar_menu_hints(), MATE_APPBAR, MATE_IS_APP, MATE_IS_APPBAR, NULL, and _MateApp::statusbar.
mate_app_install_statusbar_menu_hints()
void mate_app_install_statusbar_menu_hints (GtkStatusbar * bar, MateUIInfo * uiinfo)
mate_app_install_statusbar_menu_hints @bar: Pointer to #GtkStatusbar instance. @uiinfo: MateUIInfo for the menu to be changed.
Description: Install menu hints for the given status bar.
Definition at line 638 of file mate-app-helper.c.
References mate_app_install_statusbar_menu_hints(), MATE_APP_UI_ENDOFINFO, MATE_APP_UI_HELP, MATE_APP_UI_INCLUDE, MATE_APP_UI_ITEM, MATE_APP_UI_RADIOITEMS, MATE_APP_UI_SEPARATOR, MATE_APP_UI_SUBTREE, MATE_APP_UI_SUBTREE_STOCK, MATE_APP_UI_TOGGLEITEM, MateUIInfo::moreinfo, NULL, and MateUIInfo::type.
Referenced by mate_app_install_menu_hints(), and mate_app_install_statusbar_menu_hints().
mate_app_remove_menu_range()
void mate_app_remove_menu_range (MateApp * app, const gchar * path, gint start, gint items)
mate_app_remove_menu_range @app: A MateApp instance. @path: A path to the menu item concerned. @start: An offset beyond the start of @path at which to begin removing. @items: The number of items to remove.
Description: Same as the mate_app_remove_menus(), except it removes the specified number of @items from the existing @app's menu structure begining with item described by (@path plus @start). This is very useful for adding and removing Recent document items in the File menu.
Definition at line 2254 of file mate-app-helper.c.
References mate_app_find_menu_pos(), MATE_IS_APP, _MateApp::menubar, and NULL.
mate_app_remove_menus()
void mate_app_remove_menus (MateApp * app, const gchar * path, gint items)
mate_app_remove_menus @app: A MateApp instance. @path: A path to the menu item concerned. @items: The number of items to remove.
Description: Removes @items items from the existing @app's menu structure, beginning with item described by @path.
The @path argument should be in the form "File/.../.../Something". "" will insert the item as the first one in the menubar, "File/" will insert it as the first one in the File menu, "File/Settings" will insert it after the Setting item in the File menu use of "File/<Separator>" should be obvious. However, the use of "<Separator>" stops after the first separator.
Definition at line 2198 of file mate-app-helper.c.
References mate_app_find_menu_pos(), MATE_IS_APP, _MateApp::menubar, and NULL.
mate_app_setup_toolbar()
void mate_app_setup_toolbar (GtkToolbar * toolbar, MateComponentDockItem * dock_item)
mate_app_setup_toolbar @toolbar: Pointer to a #GtkToolbar instance. @dock_item: Pointer to the #MateComponentDockItem the toolbar is inside, or NULL for none.
Description: Sets up a toolbar to use MATE user preferences.
Definition at line 2666 of file mate-app-helper.c.
References FALSE, mateui_mateconf_lazy_init, NULL, and TRUE.
Referenced by mate_app_add_toolbar(), and mate_app_fill_toolbar_custom().
mate_app_ui_configure_configurable()
void mate_app_ui_configure_configurable (MateUIInfo * uiinfo)
mate_app_ui_configure_configurable @uiinfo: Pointer to MATE UI menu/toolbar info
Description: Configure all user-configurable elements in the given UI info structure. This includes loading and setting previously-set options from MATE config files.
Normally, mate_app_create_menus() calls this function for the developer, but if something needs to be altered afterwards, this function can be called first. The main reason for this function being a public interface is so that it can be called from mate_popup_menu_new(), which clears a copy of the pass in MateUIInfo structures.
Definition at line 755 of file mate-app-helper.c.
References MateUIInfo::ac_mods, MateUIInfo::accelerator_key, MateUIInfo::hint, int(), label, MateUIInfo::label, MATE_APP_CONFIGURABLE_ITEM_NEW, MATE_APP_UI_ITEM, MATE_APP_UI_ITEM_CONFIGURABLE, MateUIInfo::pixmap_info, MateUIInfo::pixmap_type, MateUIInfo::type, and type.
Referenced by mate_app_install_appbar_menu_hints(), and mate_popup_menu_append().