MATE Desktop Environment: matemixer-stream-control-private.h File Reference
matemixer-stream-control-private.h File Reference
#include <glib.h>
#include "matemixer-enums.h"
#include "matemixer-types.h"
Functions
void _mate_mixer_stream_control_set_flags (MateMixerStreamControl *control, MateMixerStreamControlFlags flags)
void _mate_mixer_stream_control_set_stream (MateMixerStreamControl *control, MateMixerStream *stream)
void _mate_mixer_stream_control_set_mute (MateMixerStreamControl *control, gboolean mute)
void _mate_mixer_stream_control_set_balance (MateMixerStreamControl *control, gfloat balance)
void _mate_mixer_stream_control_set_fade (MateMixerStreamControl *control, gfloat fade)
Function Documentation
_mate_mixer_stream_control_set_balance()
void _mate_mixer_stream_control_set_balance (MateMixerStreamControl * control, gfloat balance)
Definition at line 927 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, _MateMixerStreamControl::priv, and PROP_BALANCE.
Referenced by alsa_stream_control_set_data(), and mate_mixer_stream_control_set_balance().
_mate_mixer_stream_control_set_fade()
void _mate_mixer_stream_control_set_fade (MateMixerStreamControl * control, gfloat fade)
Definition at line 940 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, _MateMixerStreamControl::priv, and PROP_FADE.
Referenced by alsa_stream_control_set_data(), and mate_mixer_stream_control_set_fade().
_mate_mixer_stream_control_set_flags()
void _mate_mixer_stream_control_set_flags (MateMixerStreamControl * control, MateMixerStreamControlFlags flags)
Definition at line 876 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, _MateMixerStreamControl::priv, and PROP_FLAGS.
Referenced by alsa_stream_control_set_data(), pulse_ext_stream_update(), pulse_stream_control_set_channel_map(), and pulse_stream_control_set_cvolume().
_mate_mixer_stream_control_set_mute()
void _mate_mixer_stream_control_set_mute (MateMixerStreamControl * control, gboolean mute)
Definition at line 914 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, _MateMixerStreamControl::priv, and PROP_MUTE.
Referenced by alsa_stream_control_set_data(), mate_mixer_stream_control_set_mute(), pulse_ext_stream_update(), pulse_sink_control_update(), pulse_sink_input_update(), pulse_source_control_update(), and pulse_source_output_update().
_mate_mixer_stream_control_set_stream()
void _mate_mixer_stream_control_set_stream (MateMixerStreamControl * control, MateMixerStream * stream)
Definition at line 890 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM, MATE_MIXER_IS_STREAM_CONTROL, NULL, _MateMixerStreamControl::priv, and PROP_STREAM.
Referenced by mate_mixer_stream_control_set_stream(), and pulse_ext_stream_update().