MATE Desktop Environment: mate-druid.h File Reference
mate-druid.h File Reference
#include <gtk/gtk.h>
#include "mate-druid-page.h"
Classes
struct _MateDruid
struct _MateDruidClass
Macros
#define MATE_TYPE_DRUID (mate_druid_get_type ())
#define MATE_DRUID(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_DRUID, MateDruid))
#define MATE_DRUID_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_DRUID, MateDruidClass))
#define MATE_IS_DRUID(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_DRUID))
#define MATE_IS_DRUID_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_DRUID))
#define MATE_DRUID_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_DRUID, MateDruidClass))
Typedefs
typedef struct _MateDruid MateDruid
typedef struct _MateDruidPrivate MateDruidPrivate
typedef struct _MateDruidClass MateDruidClass
Functions
GType mate_druid_get_type (void)
GtkWidget * mate_druid_new (void)
void mate_druid_set_buttons_sensitive (MateDruid *druid, gboolean back_sensitive, gboolean next_sensitive, gboolean cancel_sensitive, gboolean help_sensitive)
void mate_druid_set_show_finish (MateDruid *druid, gboolean show_finish)
void mate_druid_set_show_help (MateDruid *druid, gboolean show_help)
void mate_druid_prepend_page (MateDruid *druid, MateDruidPage *page)
void mate_druid_insert_page (MateDruid *druid, MateDruidPage *back_page, MateDruidPage *page)
void mate_druid_append_page (MateDruid *druid, MateDruidPage *page)
void mate_druid_set_page (MateDruid *druid, MateDruidPage *page)
GtkWidget * mate_druid_new_with_window (const char *title, GtkWindow *parent, gboolean close_on_cancel, GtkWidget **window)
void mate_druid_construct_with_window (MateDruid *druid, const char *title, GtkWindow *parent, gboolean close_on_cancel, GtkWidget **window)
Macro Definition Documentation
MATE_DRUID
#define MATE_DRUID (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_DRUID, MateDruid))
Definition at line 38 of file mate-druid.h.
MATE_DRUID_CLASS
#define MATE_DRUID_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_DRUID, MateDruidClass))
Definition at line 39 of file mate-druid.h.
MATE_DRUID_GET_CLASS
#define MATE_DRUID_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_DRUID, MateDruidClass))
Definition at line 42 of file mate-druid.h.
MATE_IS_DRUID
#define MATE_IS_DRUID (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_DRUID))
Definition at line 40 of file mate-druid.h.
MATE_IS_DRUID_CLASS
#define MATE_IS_DRUID_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_DRUID))
Definition at line 41 of file mate-druid.h.
MATE_TYPE_DRUID
#define MATE_TYPE_DRUID (mate_druid_get_type ())
Definition at line 37 of file mate-druid.h.
Typedef Documentation
MateDruid
typedef struct _MateDruid MateDruid
Definition at line 45 of file mate-druid.h.
MateDruidClass
typedef struct _MateDruidClass MateDruidClass
Definition at line 47 of file mate-druid.h.
MateDruidPrivate
typedef struct _MateDruidPrivate MateDruidPrivate
Definition at line 46 of file mate-druid.h.
Function Documentation
mate_druid_append_page()
void mate_druid_append_page (MateDruid * druid, MateDruidPage * page)
Definition at line 1026 of file mate-druid.c.
References _MateDruid::_priv, mate_druid_insert_page(), MATE_DRUID_PAGE, MATE_IS_DRUID, MATE_IS_DRUID_PAGE, and NULL.
Referenced by main().
mate_druid_construct_with_window()
void mate_druid_construct_with_window (MateDruid * druid, const char * title, GtkWindow * parent, gboolean close_on_cancel, GtkWidget ** window)
mate_druid_construct_with_window: @druid: The MateDruid. @title: A title of the window. @parent: The parent of this window (transient_for). @close_on_cancel: TRUE if the window should be closed when cancel is pressed. @window: Optional return of the #GtkWindow created.
Description: Creates a new toplevel window with the title of @title (which can be NULL) and a parent of @parent (which also can be NULL). The @druid will be placed inside this window. The window and the druid will both be shown. If you need the window widget pointer you can optionally get it through the last argument. When the druid gets destroyed, so will the window that is created here.
See also mate_druid_new_with_window().
Definition at line 810 of file mate-druid.c.
References MATE_IS_DRUID, and NULL.
Referenced by mate_druid_new_with_window().
mate_druid_get_type()
GType mate_druid_get_type (void)
mate_druid_insert_page()
void mate_druid_insert_page (MateDruid * druid, MateDruidPage * back_page, MateDruidPage * page)
Definition at line 977 of file mate-druid.c.
References _MateDruid::_priv, mate_druid_set_page(), MATE_IS_DRUID, MATE_IS_DRUID_PAGE, and NULL.
Referenced by mate_druid_append_page(), and mate_druid_prepend_page().
mate_druid_new()
GtkWidget * mate_druid_new (void)
mate_druid_new:
Description: Creates a new MateDruid widget. You need to add this to a dialog yourself, it is not a dialog.
Returns: A new MateDruid widget
Definition at line 743 of file mate-druid.c.
References MATE_TYPE_DRUID, and NULL.
Referenced by main().
mate_druid_new_with_window()
GtkWidget * mate_druid_new_with_window (const char * title, GtkWindow * parent, gboolean close_on_cancel, GtkWidget ** window)
mate_druid_new_with_window: @title: A title of the window. @parent: The parent of this window (transient_for). @close_on_cancel: TRUE if the window should be closed when cancel is pressed. @window: Optional return of the #GtkWindow created.
Description: Creates a new MateDruid widget. It also creates a new toplevel window with the title of @title (which can be NULL) and a parent of @parent (which also can be NULL). The window and the druid will both be shown. If you need the window widget pointer you can optionally get it through the last argument. When the druid gets destroyed, so will the window that is created here.
Returns: A new MateDruid widget.
Definition at line 766 of file mate-druid.c.
References MATE_DRUID, mate_druid_construct_with_window(), MATE_TYPE_DRUID, and NULL.
mate_druid_prepend_page()
void mate_druid_prepend_page (MateDruid * druid, MateDruidPage * page)
Definition at line 954 of file mate-druid.c.
References mate_druid_insert_page(), MATE_IS_DRUID, MATE_IS_DRUID_PAGE, and NULL.
mate_druid_set_buttons_sensitive()
void mate_druid_set_buttons_sensitive (MateDruid * druid, gboolean back_sensitive, gboolean next_sensitive, gboolean cancel_sensitive, gboolean help_sensitive)
mate_druid_set_buttons_sensitive @druid: A Druid. @back_sensitive: TRUE if the back button is sensitive. @next_sensitive: TRUE if the next button is sensitive. @cancel_sensitive: TRUE if the cancel button is sensitive. @help_sensitive: TRUE if the help button is sensitive.
Description: Sets the sensitivity of @druid's control-buttons. If the variables are TRUE, then they will be clickable. This function is used primarily by the actual MateDruidPage widgets.
Definition at line 875 of file mate-druid.c.
References _MateDruid::back, _MateDruid::cancel, _MateDruid::help, MATE_IS_DRUID, _MateDruid::next, and NULL.
mate_druid_set_page()
void mate_druid_set_page (MateDruid * druid, MateDruidPage * page)
Definition at line 1051 of file mate-druid.c.
References _MateDruid::_priv, FALSE, MATE_DRUID_PAGE, mate_druid_page_prepare(), MATE_IS_DRUID, MATE_IS_DRUID_PAGE, NULL, and TRUE.
Referenced by mate_druid_insert_page().
mate_druid_set_show_finish()
void mate_druid_set_show_finish (MateDruid * druid, gboolean show_finish)
mate_druid_set_show_finish @druid: A MateDruid widget. @show_finish: If TRUE, then the "Next" button is changed to be "Finish"
Used to specify if @druid is currently showing the last page of the sequence (and hence should display "Finish", rather than "Next").
Definition at line 899 of file mate-druid.c.
References _MateDruid::_priv, FALSE, _MateDruid::finish, MATE_IS_DRUID, _MateDruid::next, and TRUE.
mate_druid_set_show_help()
void mate_druid_set_show_help (MateDruid * druid, gboolean show_help)
mate_druid_set_show_help @druid: A MateDruid. @show_help: TRUE, if the "Help" button is to be shown, FALSE otherwise.
Sets the "Help" button on the druid to be visible in the lower left corner of the widget, if @show_help is TRUE.
Definition at line 926 of file mate-druid.c.
References _MateDruid::_priv, FALSE, _MateDruid::help, MATE_IS_DRUID, and TRUE.