MATE Desktop Environment: mate-rr-config.c File Reference
mate-rr-config.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib/gstdio.h>
#include <X11/Xlib.h>
#include <gdk/gdkx.h>
#include "mate-rr-config.h"
#include "edid.h"
#include "mate-rr-private.h"
Macros
#define MATE_DESKTOP_USE_UNSTABLE_API
#define CONFIG_INTENDED_BASENAME "monitors.xml"
#define CONFIG_BACKUP_BASENAME "monitors.xml.backup"
#define TOPLEVEL_ELEMENT (parser->config_file_version > 0 ? "monitors" : NULL)
Typedefs
typedef struct CrtcAssignment CrtcAssignment
typedef struct Parser Parser
typedef struct CrtcInfo CrtcInfo
Enumerations
enum { PROP_0 , PROP_SCREEN , PROP_LAST }
Functions
gboolean mate_rr_config_load_current (MateRRConfig *config, GError **error)
gboolean mate_rr_config_load_filename (MateRRConfig *result, const char *filename, GError **error)
MateRRConfig * mate_rr_config_new_current (MateRRScreen *screen, GError **error)
MateRRConfig * mate_rr_config_new_stored (MateRRScreen *screen, GError **error)
gboolean mate_rr_config_match (MateRRConfig *c1, MateRRConfig *c2)
gboolean mate_rr_config_equal (MateRRConfig *c1, MateRRConfig *c2)
gboolean mate_rr_config_applicable (MateRRConfig *configuration, MateRRScreen *screen, GError **error)
char * mate_rr_config_get_backup_filename (void)
char * mate_rr_config_get_intended_filename (void)
void mate_rr_config_sanitize (MateRRConfig *config)
gboolean mate_rr_config_ensure_primary (MateRRConfig *configuration)
gboolean mate_rr_config_save (MateRRConfig *configuration, GError **error)
gboolean mate_rr_config_apply_with_time (MateRRConfig *config, MateRRScreen *screen, guint32 timestamp, GError **error)
gboolean mate_rr_config_apply_from_filename_with_time (MateRRScreen *screen, const char *filename, guint32 timestamp, GError **error)
MateRROutputInfo ** mate_rr_config_get_outputs (MateRRConfig *self)
gboolean mate_rr_config_get_clone (MateRRConfig *self)
void mate_rr_config_set_clone (MateRRConfig *self, gboolean clone)
Macro Definition Documentation
CONFIG_BACKUP_BASENAME
#define CONFIG_BACKUP_BASENAME "monitors.xml.backup"
Definition at line 45 of file mate-rr-config.c.
CONFIG_INTENDED_BASENAME
#define CONFIG_INTENDED_BASENAME "monitors.xml"
Definition at line 44 of file mate-rr-config.c.
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 27 of file mate-rr-config.c.
TOPLEVEL_ELEMENT
#define TOPLEVEL_ELEMENT (parser->config_file_version > 0 ? "monitors" : NULL)
Definition at line 260 of file mate-rr-config.c.
Typedef Documentation
CrtcAssignment
typedef struct CrtcAssignment CrtcAssignment
Definition at line 78 of file mate-rr-config.c.
CrtcInfo
typedef struct CrtcInfo CrtcInfo
Definition at line 1429 of file mate-rr-config.c.
Parser
typedef struct Parser Parser
Definition at line 96 of file mate-rr-config.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_SCREEN
PROP_LAST
Definition at line 88 of file mate-rr-config.c.
Function Documentation
mate_rr_config_applicable()
gboolean mate_rr_config_applicable (MateRRConfig * configuration, MateRRScreen * screen, GError ** error)
Definition at line 977 of file mate-rr-config.c.
References error, FALSE, MATE_IS_RR_CONFIG, MATE_IS_RR_SCREEN, NULL, and TRUE.
mate_rr_config_apply_from_filename_with_time()
gboolean mate_rr_config_apply_from_filename_with_time (MateRRScreen * screen, const char * filename, guint32 timestamp, GError ** error)
Definition at line 1351 of file mate-rr-config.c.
References error, FALSE, MATE_IS_RR_SCREEN, mate_rr_config_apply_with_time(), mate_rr_config_ensure_primary(), mate_rr_config_load_filename(), mate_rr_screen_refresh(), MATE_TYPE_RR_CONFIG, and NULL.
mate_rr_config_apply_with_time()
gboolean mate_rr_config_apply_with_time (MateRRConfig * config, MateRRScreen * screen, guint32 timestamp, GError ** error)
Definition at line 1282 of file mate-rr-config.c.
References error, FALSE, MATE_IS_RR_CONFIG, MATE_IS_RR_SCREEN, NULL, and TRUE.
Referenced by mate_rr_config_apply_from_filename_with_time().
mate_rr_config_ensure_primary()
gboolean mate_rr_config_ensure_primary (MateRRConfig * configuration)
Definition at line 1173 of file mate-rr-config.c.
References _mate_rr_output_name_is_laptop(), FALSE, MATE_IS_RR_CONFIG, MateRROutputInfoPrivate::name, NULL, MateRROutputInfoPrivate::on, MateRRConfigPrivate::outputs, MateRROutputInfoPrivate::primary, MateRROutputInfo::priv, MateRRConfig::priv, TRUE, MateRROutputInfoPrivate::x, and MateRROutputInfoPrivate::y.
Referenced by mate_rr_config_apply_from_filename_with_time().
mate_rr_config_equal()
gboolean mate_rr_config_equal (MateRRConfig * c1, MateRRConfig * c2)
Definition at line 913 of file mate-rr-config.c.
References FALSE, MATE_IS_RR_CONFIG, MateRROutputInfoPrivate::name, NULL, MateRRConfigPrivate::outputs, MateRROutputInfo::priv, MateRRConfig::priv, and TRUE.
mate_rr_config_get_backup_filename()
char * mate_rr_config_get_backup_filename (void)
Definition at line 1019 of file mate-rr-config.c.
References CONFIG_BACKUP_BASENAME, and NULL.
Referenced by mate_rr_config_save().
mate_rr_config_get_clone()
gboolean mate_rr_config_get_clone (MateRRConfig * self)
mate_rr_config_get_clone:
Returns: whether at least two outputs are at (0, 0) offset and they have the same width/height. Those outputs are of course connected and on (i.e. they have a CRTC assigned).
Definition at line 1411 of file mate-rr-config.c.
References MateRRConfigPrivate::clone, FALSE, MATE_IS_RR_CONFIG, and MateRRConfig::priv.
mate_rr_config_get_intended_filename()
char * mate_rr_config_get_intended_filename (void)
Definition at line 1026 of file mate-rr-config.c.
References CONFIG_INTENDED_BASENAME, and NULL.
Referenced by mate_rr_config_load_filename(), mate_rr_config_new_stored(), and mate_rr_config_save().
mate_rr_config_get_outputs()
MateRROutputInfo ** mate_rr_config_get_outputs (MateRRConfig * self)
mate_rr_config_get_outputs:
Returns: (array zero-terminated=1) (element-type MateDesktop.RROutputInfo) (transfer none): the output configuration for this MateRRConfig
Definition at line 1396 of file mate-rr-config.c.
References MATE_IS_RR_CONFIG, NULL, MateRRConfigPrivate::outputs, and MateRRConfig::priv.
Referenced by mate_rr_labeler_get_rgba_for_output().
mate_rr_config_load_current()
gboolean mate_rr_config_load_current (MateRRConfig * config, GError ** error)
Definition at line 495 of file mate-rr-config.c.
References _, MateRROutputInfoPrivate::aspect, MonitorInfo::aspect_ratio, MateRRConfigPrivate::clone, MateRROutputInfoPrivate::connected, decode_edid(), MateRROutputInfoPrivate::display_name, FALSE, MateRROutputInfoPrivate::height, make_display_name(), MonitorInfo::manufacturer_code, MATE_IS_RR_CONFIG, mate_rr_config_match(), mate_rr_crtc_get_current_mode(), mate_rr_crtc_get_current_rotation(), mate_rr_crtc_get_position(), mate_rr_mode_get_freq(), mate_rr_mode_get_height(), mate_rr_mode_get_width(), mate_rr_output_get_crtc(), mate_rr_output_get_edid_data(), mate_rr_output_get_is_primary(), mate_rr_output_get_name(), mate_rr_output_get_preferred_mode(), mate_rr_output_is_connected(), mate_rr_output_is_laptop(), mate_rr_output_list_modes(), MATE_RR_ROTATION_0, mate_rr_screen_list_outputs(), MATE_TYPE_RR_OUTPUT_INFO, MAX, memcpy, MateRROutputInfoPrivate::name, NULL, MateRROutputInfoPrivate::on, MateRRConfigPrivate::outputs, MateRROutputInfoPrivate::pref_height, MateRROutputInfoPrivate::pref_width, MateRROutputInfoPrivate::primary, MateRROutputInfo::priv, MateRRConfig::priv, MateRROutputInfoPrivate::product, MonitorInfo::product_code, MateRROutputInfoPrivate::rate, MateRROutputInfoPrivate::rotation, MateRRConfigPrivate::screen, MateRROutputInfoPrivate::serial, MonitorInfo::serial_number, TRUE, MateRROutputInfoPrivate::vendor, MateRROutputInfoPrivate::width, MateRROutputInfoPrivate::x, and MateRROutputInfoPrivate::y.
Referenced by mate_rr_config_new_current().
mate_rr_config_load_filename()
gboolean mate_rr_config_load_filename (MateRRConfig * result, const char * filename, GError ** error)
Definition at line 667 of file mate-rr-config.c.
References _, MateRRConfigPrivate::clone, error, FALSE, MATE_IS_RR_CONFIG, mate_rr_config_get_intended_filename(), mate_rr_config_match(), mate_rr_config_new_current(), MATE_RR_ERROR, MATE_RR_ERROR_NO_MATCHING_CONFIG, NULL, MateRRConfigPrivate::outputs, MateRRConfig::priv, MateRRConfigPrivate::screen, and TRUE.
Referenced by mate_rr_config_apply_from_filename_with_time(), and mate_rr_config_new_stored().
mate_rr_config_match()
gboolean mate_rr_config_match (MateRRConfig * c1, MateRRConfig * c2)
Definition at line 890 of file mate-rr-config.c.
References FALSE, MATE_IS_RR_CONFIG, MateRROutputInfoPrivate::name, NULL, MateRRConfigPrivate::outputs, MateRROutputInfo::priv, MateRRConfig::priv, and TRUE.
Referenced by mate_rr_config_load_current(), mate_rr_config_load_filename(), and mate_rr_config_save().
mate_rr_config_new_current()
MateRRConfig * mate_rr_config_new_current (MateRRScreen * screen, GError ** error)
Definition at line 734 of file mate-rr-config.c.
References error, mate_rr_config_load_current(), MATE_TYPE_RR_CONFIG, and NULL.
Referenced by mate_rr_config_load_filename().
mate_rr_config_new_stored()
MateRRConfig * mate_rr_config_new_stored (MateRRScreen * screen, GError ** error)
Definition at line 748 of file mate-rr-config.c.
References error, mate_rr_config_get_intended_filename(), mate_rr_config_load_filename(), MATE_TYPE_RR_CONFIG, and NULL.
mate_rr_config_sanitize()
void mate_rr_config_sanitize (MateRRConfig * config)
Definition at line 1122 of file mate-rr-config.c.
References FALSE, MIN, MateRROutputInfoPrivate::on, MateRRConfigPrivate::outputs, MateRROutputInfoPrivate::primary, MateRROutputInfo::priv, MateRRConfig::priv, TRUE, MateRROutputInfoPrivate::x, and MateRROutputInfoPrivate::y.
mate_rr_config_save()
gboolean mate_rr_config_save (MateRRConfig * configuration, GError ** error)
Definition at line 1229 of file mate-rr-config.c.
References error, FALSE, MATE_IS_RR_CONFIG, mate_rr_config_get_backup_filename(), mate_rr_config_get_intended_filename(), mate_rr_config_match(), NULL, and TRUE.
mate_rr_config_set_clone()
void mate_rr_config_set_clone (MateRRConfig * self, gboolean clone)
Definition at line 1419 of file mate-rr-config.c.
References MateRRConfigPrivate::clone, MATE_IS_RR_CONFIG, and MateRRConfig::priv.