MATE Desktop Environment: mate-bg-crossfade.h File Reference
mate-bg-crossfade.h File Reference
#include <glib.h>
#include <gdk/gdk.h>
#include <gtk/gtk.h>
Classes
struct _MateBGCrossfade
struct _MateBGCrossfadeClass
Macros
#define MATE_TYPE_BG_CROSSFADE (mate_bg_crossfade_get_type ())
#define MATE_BG_CROSSFADE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_BG_CROSSFADE, MateBGCrossfade))
#define MATE_BG_CROSSFADE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_BG_CROSSFADE, MateBGCrossfadeClass))
#define MATE_IS_BG_CROSSFADE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_BG_CROSSFADE))
#define MATE_IS_BG_CROSSFADE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_BG_CROSSFADE))
#define MATE_BG_CROSSFADE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_BG_CROSSFADE, MateBGCrossfadeClass))
Typedefs
typedef struct _MateBGCrossfadePrivate MateBGCrossfadePrivate
typedef struct _MateBGCrossfade MateBGCrossfade
typedef struct _MateBGCrossfadeClass MateBGCrossfadeClass
Functions
GType mate_bg_crossfade_get_type (void)
MateBGCrossfade * mate_bg_crossfade_new (int width, int height)
gboolean mate_bg_crossfade_set_start_surface (MateBGCrossfade *fade, cairo_surface_t *surface)
gboolean mate_bg_crossfade_set_end_surface (MateBGCrossfade *fade, cairo_surface_t *surface)
void mate_bg_crossfade_start (MateBGCrossfade *fade, GdkWindow *window)
void mate_bg_crossfade_start_widget (MateBGCrossfade *fade, GtkWidget *widget)
gboolean mate_bg_crossfade_is_started (MateBGCrossfade *fade)
void mate_bg_crossfade_stop (MateBGCrossfade *fade)
Macro Definition Documentation
MATE_BG_CROSSFADE
#define MATE_BG_CROSSFADE (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_BG_CROSSFADE, MateBGCrossfade))
Definition at line 39 of file mate-bg-crossfade.h.
MATE_BG_CROSSFADE_CLASS
#define MATE_BG_CROSSFADE_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_BG_CROSSFADE, MateBGCrossfadeClass))
Definition at line 40 of file mate-bg-crossfade.h.
MATE_BG_CROSSFADE_GET_CLASS
#define MATE_BG_CROSSFADE_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_BG_CROSSFADE, MateBGCrossfadeClass))
Definition at line 43 of file mate-bg-crossfade.h.
MATE_IS_BG_CROSSFADE
#define MATE_IS_BG_CROSSFADE (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_BG_CROSSFADE))
Definition at line 41 of file mate-bg-crossfade.h.
MATE_IS_BG_CROSSFADE_CLASS
#define MATE_IS_BG_CROSSFADE_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_BG_CROSSFADE))
Definition at line 42 of file mate-bg-crossfade.h.
MATE_TYPE_BG_CROSSFADE
#define MATE_TYPE_BG_CROSSFADE (mate_bg_crossfade_get_type ())
Definition at line 38 of file mate-bg-crossfade.h.
Typedef Documentation
MateBGCrossfade
typedef struct _MateBGCrossfade MateBGCrossfade
Definition at line 46 of file mate-bg-crossfade.h.
MateBGCrossfadeClass
typedef struct _MateBGCrossfadeClass MateBGCrossfadeClass
Definition at line 47 of file mate-bg-crossfade.h.
MateBGCrossfadePrivate
typedef struct _MateBGCrossfadePrivate MateBGCrossfadePrivate
Definition at line 45 of file mate-bg-crossfade.h.
Function Documentation
mate_bg_crossfade_get_type()
GType mate_bg_crossfade_get_type (void)
mate_bg_crossfade_is_started()
gboolean mate_bg_crossfade_is_started (MateBGCrossfade * fade)
mate_bg_crossfade_is_started: @fade: a MateBGCrossfade
This function reveals whether or not @fade is currently running on a window. See mate_bg_crossfade_start() for information on how to initiate a crossfade.
Return value: TRUE if fading, or FALSE if not fading
Definition at line 740 of file mate-bg-crossfade.c.
References FALSE, MATE_IS_BG_CROSSFADE, and _MateBGCrossfade::priv.
Referenced by eel_background_draw(), mate_bg_crossfade_start(), and mate_bg_crossfade_stop().
mate_bg_crossfade_new()
MateBGCrossfade * mate_bg_crossfade_new (int width, int height)
mate_bg_crossfade_new: @width: The width of the crossfading window @height: The height of the crossfading window
Creates a new object to manage crossfading a window background between two #cairo_surface_ts.
Return value: the new MateBGCrossfade
Definition at line 226 of file mate-bg-crossfade.c.
References MATE_TYPE_BG_CROSSFADE, and NULL.
Referenced by mate_bg_set_surface_as_root_with_crossfade().
mate_bg_crossfade_set_end_surface()
gboolean mate_bg_crossfade_set_end_surface (MateBGCrossfade * fade, cairo_surface_t * surface)
mate_bg_crossfade_set_end_surface: @fade: a MateBGCrossfade @surface: The cairo surface to fade to
Before initiating a crossfade with mate_bg_crossfade_start() a start and end surface have to be set. This function sets the surface shown at the end of the crossfade effect.
Return value: TRUE if successful, or FALSE if the surface could not be copied.
Definition at line 370 of file mate-bg-crossfade.c.
References FALSE, MATE_IS_BG_CROSSFADE, NULL, and _MateBGCrossfade::priv.
Referenced by mate_bg_set_surface_as_root_with_crossfade().
mate_bg_crossfade_set_start_surface()
gboolean mate_bg_crossfade_set_start_surface (MateBGCrossfade * fade, cairo_surface_t * surface)
mate_bg_crossfade_set_start_surface: @fade: a MateBGCrossfade @surface: The cairo surface to fade from
Before initiating a crossfade with mate_bg_crossfade_start() a start and end surface have to be set. This function sets the surface shown at the beginning of the crossfade effect.
Return value: TRUE if successful, or FALSE if the surface could not be copied.
Definition at line 312 of file mate-bg-crossfade.c.
References FALSE, MATE_IS_BG_CROSSFADE, NULL, and _MateBGCrossfade::priv.
Referenced by mate_bg_set_surface_as_root_with_crossfade().
mate_bg_crossfade_start()
void mate_bg_crossfade_start (MateBGCrossfade * fade, GdkWindow * window)
mate_bg_crossfade_start: @fade: a MateBGCrossfade @window: The #GdkWindow to draw crossfade on
This function initiates a quick crossfade between two surfaces on the background of @window. Before initiating the crossfade both mate_bg_crossfade_set_start_surface() and mate_bg_crossfade_set_end_surface() need to be called. If animations are disabled, the crossfade is skipped, and the window background is set immediately to the end surface.
Definition at line 637 of file mate-bg-crossfade.c.
References mate_bg_crossfade_is_started(), MATE_IS_BG_CROSSFADE, NULL, _MateBGCrossfade::priv, and TRUE.
Referenced by mate_bg_crossfade_start_widget(), and mate_bg_set_surface_as_root_with_crossfade().
mate_bg_crossfade_start_widget()
void mate_bg_crossfade_start_widget (MateBGCrossfade * fade, GtkWidget * widget)
mate_bg_crossfade_start_widget: @fade: a MateBGCrossfade @widget: The #GtkWidget to draw crossfade on
This function initiates a quick crossfade between two surfaces on the background of @widget. Before initiating the crossfade both mate_bg_crossfade_set_start_surface() and mate_bg_crossfade_set_end_surface() need to be called. If animations are disabled, the crossfade is skipped, and the window background is set immediately to the end surface.
Definition at line 714 of file mate-bg-crossfade.c.
References mate_bg_crossfade_start(), MATE_IS_BG_CROSSFADE, NULL, and _MateBGCrossfade::priv.
mate_bg_crossfade_stop()
void mate_bg_crossfade_stop (MateBGCrossfade * fade)
mate_bg_crossfade_stop: @fade: a MateBGCrossfade
This function stops any in progress crossfades that may be happening. It's harmless to call this function if @fade is already stopped.
Definition at line 756 of file mate-bg-crossfade.c.
References mate_bg_crossfade_is_started(), MATE_IS_BG_CROSSFADE, and _MateBGCrossfade::priv.