MATE Desktop Environment: math-display.h File Reference
math-display.h File Reference
#include <glib-object.h>
#include <gtk/gtk.h>
#include "math-equation.h"
Classes
struct MathDisplay
struct MathDisplayClass
Macros
#define MATH_DISPLAY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), math_display_get_type(), MathDisplay))
Typedefs
typedef struct MathDisplayPrivate MathDisplayPrivate
Functions
GType math_display_get_type (void)
MathDisplay * math_display_new (void)
MathDisplay * math_display_new_with_equation (MathEquation *equation)
MathEquation * math_display_get_equation (MathDisplay *display)
Macro Definition Documentation
MATH_DISPLAY
#define MATH_DISPLAY (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), math_display_get_type(), MathDisplay))
Definition at line 21 of file math-display.h.
Typedef Documentation
MathDisplayPrivate
typedef struct MathDisplayPrivate MathDisplayPrivate
Definition at line 23 of file math-display.h.
Function Documentation
math_display_get_equation()
MathEquation * math_display_get_equation (MathDisplay * display)
Definition at line 52 of file math-display.c.
References MathDisplay::priv.
math_display_get_type()
GType math_display_get_type (void)
Referenced by math_display_new(), and math_display_new_with_equation().
math_display_new()
MathDisplay * math_display_new (void)
Definition at line 40 of file math-display.c.
References math_display_get_type(), math_equation_new(), and NULL.
math_display_new_with_equation()
MathDisplay * math_display_new_with_equation (MathEquation * equation)
Definition at line 46 of file math-display.c.
References math_display_get_type(), and NULL.