MATE Desktop Environment: math-converter.h File Reference
math-converter.h File Reference
#include <glib-object.h>
#include <gtk/gtk.h>
#include "math-equation.h"
#include "unit.h"
Classes
struct MathConverter
struct MathConverterClass
Macros
#define MATH_CONVERTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), math_converter_get_type(), MathConverter))
Typedefs
typedef struct MathConverterPrivate MathConverterPrivate
Functions
GType math_converter_get_type (void)
MathConverter * math_converter_new (MathEquation *equation)
void math_converter_set_category (MathConverter *converter, const gchar *category)
const gchar * math_converter_get_category (MathConverter *converter)
void math_converter_set_conversion (MathConverter *converter, const gchar *unit_a, const gchar *unit_b)
void math_converter_get_conversion (MathConverter *converter, Unit **from_unit, Unit **to_unit)
Macro Definition Documentation
MATH_CONVERTER
#define MATH_CONVERTER (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), math_converter_get_type(), MathConverter))
Definition at line 22 of file math-converter.h.
Typedef Documentation
MathConverterPrivate
typedef struct MathConverterPrivate MathConverterPrivate
Definition at line 24 of file math-converter.h.
Function Documentation
math_converter_get_category()
const gchar * math_converter_get_category (MathConverter * converter)
Definition at line 183 of file math-converter.c.
References NULL, and MathConverter::priv.
math_converter_get_conversion()
void math_converter_get_conversion (MathConverter * converter, Unit ** from_unit, Unit ** to_unit)
Definition at line 263 of file math-converter.c.
References NULL, and MathConverter::priv.
math_converter_get_type()
GType math_converter_get_type (void)
Referenced by math_converter_new().
math_converter_new()
MathConverter * math_converter_new (MathEquation * equation)
Definition at line 41 of file math-converter.c.
References math_converter_get_type(), NULL, and MathConverter::priv.
math_converter_set_category()
void math_converter_set_category (MathConverter * converter, const gchar * category)
Definition at line 167 of file math-converter.c.
References category, NULL, and MathConverter::priv.
Referenced by math_buttons_set_mode().
math_converter_set_conversion()
void math_converter_set_conversion (MathConverter * converter, const gchar * unit_a, const gchar * unit_b)
Definition at line 231 of file math-converter.c.
References NULL, MathConverter::priv, unit_manager_get_default(), and unit_manager_get_unit_by_name().
Referenced by math_buttons_set_mode().