MATE Desktop Environment: math-history-entry.h File Reference
math-history-entry.h File Reference
#include <glib-object.h>
#include <gtk/gtk.h>
#include "math-display.h"
#include "math-history.h"
Classes
struct MathHistoryEntry
struct MathHistoryEntryClass
Macros
#define MATH_HISTORY_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), math_history_entry_get_type(), MathHistoryEntry))
Typedefs
typedef struct MathHistoryEntryPrivate MathHistoryEntryPrivate
Functions
GType math_history_entry_get_type (void)
MathHistoryEntry * math_history_entry_new (MathEquation *equation)
void math_history_entry_insert_entry (MathHistoryEntry *history_entry, const gchar *equation, MPNumber *answer, MpSerializer *serializer)
void math_history_entry_redisplay (MathHistoryEntry *history_entry, MpSerializer *serializer)
gchar * math_history_entry_get_equation (MathHistoryEntry *history_entry)
Macro Definition Documentation
MATH_HISTORY_ENTRY
#define MATH_HISTORY_ENTRY (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), math_history_entry_get_type(), MathHistoryEntry))
Definition at line 24 of file math-history-entry.h.
Typedef Documentation
MathHistoryEntryPrivate
typedef struct MathHistoryEntryPrivate MathHistoryEntryPrivate
Definition at line 26 of file math-history-entry.h.
Function Documentation
math_history_entry_get_equation()
gchar * math_history_entry_get_equation (MathHistoryEntry * history_entry)
Definition at line 99 of file math-history-entry.c.
References MathHistoryEntry::priv.
math_history_entry_get_type()
GType math_history_entry_get_type (void)
Referenced by math_history_entry_new().
math_history_entry_insert_entry()
void math_history_entry_insert_entry (MathHistoryEntry * history_entry, const gchar * equation, MPNumber * answer, MpSerializer * serializer)
Definition at line 63 of file math-history-entry.c.
References get_widget, math_history_entry_redisplay(), mp_set_from_mp(), MathHistoryEntry::priv, and UI_HISTORY_ENTRY_RESOURCE_PATH.
Referenced by math_history_insert_entry().
math_history_entry_new()
MathHistoryEntry * math_history_entry_new (MathEquation * equation)
Definition at line 33 of file math-history-entry.c.
References math_history_entry_get_type(), NULL, and MathHistoryEntry::priv.
Referenced by math_history_insert_entry().
math_history_entry_redisplay()
void math_history_entry_redisplay (MathHistoryEntry * history_entry, MpSerializer * serializer)
Definition at line 88 of file math-history-entry.c.
References mp_serializer_to_string(), and MathHistoryEntry::priv.
Referenced by math_history_entry_insert_entry(), and math_history_set_serializer().