MATE Desktop Environment: math-buttons.h File Reference
math-buttons.h File Reference
#include <glib-object.h>
#include <gtk/gtk.h>
#include "math-equation.h"
Classes
struct MathButtons
struct MathButtonsClass
Macros
#define MATH_BUTTONS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), math_buttons_get_type(), MathButtons))
Typedefs
typedef struct MathButtonsPrivate MathButtonsPrivate
Enumerations
enum ButtonMode { BASIC , ADVANCED , FINANCIAL , PROGRAMMING }
Functions
GType math_buttons_get_type (void)
MathButtons * math_buttons_new (MathEquation *equation)
void math_buttons_set_mode (MathButtons *buttons, ButtonMode mode)
ButtonMode math_buttons_get_mode (MathButtons *buttons)
void math_buttons_set_programming_base (MathButtons *buttons, gint base)
gint math_buttons_get_programming_base (MathButtons *buttons)
Macro Definition Documentation
MATH_BUTTONS
#define MATH_BUTTONS (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), math_buttons_get_type(), MathButtons))
Definition at line 20 of file math-buttons.h.
Typedef Documentation
MathButtonsPrivate
typedef struct MathButtonsPrivate MathButtonsPrivate
Definition at line 22 of file math-buttons.h.
Enumeration Type Documentation
ButtonMode
enum ButtonMode
Enumerator
BASIC
ADVANCED
FINANCIAL
PROGRAMMING
Definition at line 35 of file math-buttons.h.
Function Documentation
math_buttons_get_mode()
ButtonMode math_buttons_get_mode (MathButtons * buttons)
Definition at line 752 of file math-buttons.c.
References buttons.
math_buttons_get_programming_base()
gint math_buttons_get_programming_base (MathButtons * buttons)
Definition at line 774 of file math-buttons.c.
References buttons, and NULL.
Referenced by math_buttons_set_programming_base().
math_buttons_get_type()
GType math_buttons_get_type (void)
Referenced by math_buttons_new().
math_buttons_new()
MathButtons * math_buttons_new (MathEquation * equation)
Definition at line 305 of file math-buttons.c.
References math_buttons_get_type(), and NULL.
math_buttons_set_mode()
void math_buttons_set_mode (MathButtons * buttons, ButtonMode mode)
Definition at line 718 of file math-buttons.c.
References ADVANCED, buttons, FINANCIAL, math_converter_set_category(), math_converter_set_conversion(), math_equation_get_source_currency(), math_equation_get_source_units(), math_equation_get_target_currency(), math_equation_get_target_units(), math_equation_set_base(), NULL, and PROGRAMMING.
Referenced by main().
math_buttons_set_programming_base()
void math_buttons_set_programming_base (MathButtons * buttons, gint base)
Definition at line 758 of file math-buttons.c.
References buttons, g_settings_var, math_buttons_get_programming_base(), math_equation_set_base(), NULL, and PROGRAMMING.
Referenced by main().