MATE Desktop Environment: math-converter.c File Reference
math-converter.c File Reference
#include <glib/gi18n.h>
#include "math-converter.h"
#include "unit-manager.h"
#include "currency-manager.h"
Enumerations
enum { CHANGED , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (MathConverter, math_converter, GTK_TYPE_BOX)
MathConverter * math_converter_new (MathEquation *equation)
void math_converter_set_category (MathConverter *converter, const gchar *category)
const gchar * math_converter_get_category (MathConverter *converter)
void math_converter_set_conversion (MathConverter *converter, const gchar *unit_a, const gchar *unit_b)
void math_converter_get_conversion (MathConverter *converter, Unit **from_unit, Unit **to_unit)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CHANGED
LAST_SIGNAL
Definition at line 17 of file math-converter.c.
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (MathConverter , math_converter , GTK_TYPE_BOX)
math_converter_get_category()
const gchar * math_converter_get_category (MathConverter * converter)
Definition at line 183 of file math-converter.c.
References NULL, and MathConverter::priv.
math_converter_get_conversion()
void math_converter_get_conversion (MathConverter * converter, Unit ** from_unit, Unit ** to_unit)
Definition at line 263 of file math-converter.c.
References NULL, and MathConverter::priv.
math_converter_new()
MathConverter * math_converter_new (MathEquation * equation)
Definition at line 41 of file math-converter.c.
References math_converter_get_type(), NULL, and MathConverter::priv.
math_converter_set_category()
void math_converter_set_category (MathConverter * converter, const gchar * category)
Definition at line 167 of file math-converter.c.
References category, NULL, and MathConverter::priv.
Referenced by math_buttons_set_mode().
math_converter_set_conversion()
void math_converter_set_conversion (MathConverter * converter, const gchar * unit_a, const gchar * unit_b)
Definition at line 231 of file math-converter.c.
References NULL, MathConverter::priv, unit_manager_get_default(), and unit_manager_get_unit_by_name().
Referenced by math_buttons_set_mode().