MATE Desktop Environment: math-window.h File Reference
math-window.h File Reference
#include <gtk/gtk.h>
#include "math-equation.h"
#include "math-display.h"
#include "math-buttons.h"
#include "math-preferences.h"
Classes
struct MathWindow
struct MathWindowClass
Macros
#define MATH_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), math_window_get_type(), MathWindow))
Typedefs
typedef struct MathWindowPrivate MathWindowPrivate
Functions
GType math_window_get_type (void)
MathWindow * math_window_new (MathEquation *equation)
GtkWidget * math_window_get_menu_bar (MathWindow *window)
MathEquation * math_window_get_equation (MathWindow *window)
MathDisplay * math_window_get_display (MathWindow *window)
MathButtons * math_window_get_buttons (MathWindow *window)
gboolean math_window_get_show_history (MathWindow *window)
void math_window_set_show_history (MathWindow *window, gboolean visible)
void math_window_critical_error (MathWindow *window, const gchar *title, const gchar *contents)
Macro Definition Documentation
MATH_WINDOW
#define MATH_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), math_window_get_type(), MathWindow))
Definition at line 24 of file math-window.h.
Typedef Documentation
MathWindowPrivate
typedef struct MathWindowPrivate MathWindowPrivate
Definition at line 26 of file math-window.h.
Function Documentation
math_window_critical_error()
void math_window_critical_error (MathWindow * window, const gchar * title, const gchar * contents)
Definition at line 129 of file math-window.c.
References _, and NULL.
math_window_get_buttons()
MathButtons * math_window_get_buttons (MathWindow * window)
Definition at line 91 of file math-window.c.
References NULL, and MathWindow::priv.
math_window_get_display()
MathDisplay * math_window_get_display (MathWindow * window)
Definition at line 84 of file math-window.c.
References NULL, and MathWindow::priv.
math_window_get_equation()
MathEquation * math_window_get_equation (MathWindow * window)
Definition at line 77 of file math-window.c.
References NULL, and MathWindow::priv.
math_window_get_menu_bar()
GtkWidget * math_window_get_menu_bar (MathWindow * window)
Definition at line 71 of file math-window.c.
References MathWindow::priv.
math_window_get_show_history()
gboolean math_window_get_show_history (MathWindow * window)
Definition at line 98 of file math-window.c.
References FALSE, NULL, and MathWindow::priv.
Referenced by math_window_set_show_history().
math_window_get_type()
GType math_window_get_type (void)
Referenced by math_window_new().
math_window_new()
MathWindow * math_window_new (MathEquation * equation)
Definition at line 65 of file math-window.c.
References math_window_get_type(), and NULL.
math_window_set_show_history()
void math_window_set_show_history (MathWindow * window, gboolean visible)
Definition at line 105 of file math-window.c.
References FALSE, math_window_get_show_history(), NULL, MathWindow::priv, and TRUE.