MATE Desktop Environment: math-buttons.c File Reference
math-buttons.c File Reference
#include <glib/gi18n.h>
#include "math-buttons.h"
#include "math-converter.h"
#include "math-variable-popup.h"
#include "financial.h"
#include "mp-serializer.h"
#include "utility.h"
Macros
#define MAXBITS 64 /* Bit panel: number of bit fields. */
#define UI_BASIC_RESOURCE_PATH "/org/mate/calculator/ui/buttons-basic.ui"
#define UI_ADVANCED_RESOURCE_PATH "/org/mate/calculator/ui/buttons-advanced.ui"
#define UI_FINANCIAL_RESOURCE_PATH "/org/mate/calculator/ui/buttons-financial.ui"
#define UI_PROGRAMMING_RESOURCE_PATH "/org/mate/calculator/ui/buttons-programming.ui"
#define GET_WIDGET(ui, name) GTK_WIDGET(gtk_builder_get_object((ui), (name)))
Enumerations
enum { PROP_0 , PROP_EQUATION , PROP_MODE , PROP_PROGRAMMING_BASE }
enum ButtonClass {
NUMBER , NUMBER_BOLD , OPERATOR , FUNCTION ,
MEMORY , GROUP , ACTION
}
Functions
G_DEFINE_TYPE_WITH_PRIVATE (MathButtons, math_buttons, GTK_TYPE_BOX)
MathButtons * math_buttons_new (MathEquation *equation)
void math_buttons_set_mode (MathButtons *buttons, ButtonMode mode)
ButtonMode math_buttons_get_mode (MathButtons *buttons)
void math_buttons_set_programming_base (MathButtons *buttons, gint base)
gint math_buttons_get_programming_base (MathButtons *buttons)
void exponent_cb (GtkWidget *widget, MathButtons *buttons)
void subtract_cb (GtkWidget *widget, MathButtons *buttons)
void button_cb (GtkWidget *widget, MathButtons *buttons)
void solve_cb (GtkWidget *widget, MathButtons *buttons)
void clear_cb (GtkWidget *widget, MathButtons *buttons)
void delete_cb (GtkWidget *widget, MathButtons *buttons)
void undo_cb (GtkWidget *widget, MathButtons *buttons)
void memory_cb (GtkWidget *widget, MathButtons *buttons)
void shift_left_cb (GtkWidget *widget, MathButtons *buttons)
void shift_right_cb (GtkWidget *widget, MathButtons *buttons)
void function_cb (GtkWidget *widget, MathButtons *buttons)
void const_cb (GtkWidget *widget, MathButtons *buttons)
void factorize_cb (GtkWidget *widget, MathButtons *buttons)
void digit_cb (GtkWidget *widget, MathButtons *buttons)
void numeric_point_cb (GtkWidget *widget, MathButtons *buttons)
void finc_cb (GtkWidget *widget, MathButtons *buttons)
void insert_character_code_cb (GtkWidget *widget, MathButtons *buttons)
void finc_activate_cb (GtkWidget *widget, MathButtons *buttons)
void finc_response_cb (GtkWidget *widget, gint response_id, MathButtons *buttons)
void character_code_dialog_response_cb (GtkWidget *dialog, gint response_id, MathButtons *buttons)
void character_code_dialog_activate_cb (GtkWidget *entry, MathButtons *buttons)
gboolean character_code_dialog_delete_cb (GtkWidget *dialog, GdkEvent *event, MathButtons *buttons)
gboolean bit_toggle_cb (GtkWidget *event_box, GdkEventButton *event, MathButtons *buttons)
void set_superscript_cb (GtkWidget *widget, MathButtons *buttons)
void set_subscript_cb (GtkWidget *widget, MathButtons *buttons)
Macro Definition Documentation
GET_WIDGET
#define GET_WIDGET (ui, name) GTK_WIDGET(gtk_builder_get_object((ui), (name)))
Definition at line 69 of file math-buttons.c.
MAXBITS
#define MAXBITS 64 /* Bit panel: number of bit fields. */
Definition at line 29 of file math-buttons.c.
UI_ADVANCED_RESOURCE_PATH
#define UI_ADVANCED_RESOURCE_PATH "/org/mate/calculator/ui/buttons-advanced.ui"
Definition at line 65 of file math-buttons.c.
UI_BASIC_RESOURCE_PATH
#define UI_BASIC_RESOURCE_PATH "/org/mate/calculator/ui/buttons-basic.ui"
Definition at line 64 of file math-buttons.c.
UI_FINANCIAL_RESOURCE_PATH
#define UI_FINANCIAL_RESOURCE_PATH "/org/mate/calculator/ui/buttons-financial.ui"
Definition at line 66 of file math-buttons.c.
UI_PROGRAMMING_RESOURCE_PATH
#define UI_PROGRAMMING_RESOURCE_PATH "/org/mate/calculator/ui/buttons-programming.ui"
Definition at line 67 of file math-buttons.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_EQUATION
PROP_MODE
PROP_PROGRAMMING_BASE
Definition at line 20 of file math-buttons.c.
ButtonClass
enum ButtonClass
Enumerator
NUMBER
NUMBER_BOLD
OPERATOR
FUNCTION
MEMORY
GROUP
ACTION
Definition at line 72 of file math-buttons.c.
Function Documentation
bit_toggle_cb()
G_MODULE_EXPORT gboolean bit_toggle_cb (GtkWidget * event_box, GdkEventButton * event, MathButtons * buttons)
Definition at line 1213 of file math-buttons.c.
References buttons, math_equation_toggle_bit(), and TRUE.
button_cb()
G_MODULE_EXPORT void button_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 799 of file math-buttons.c.
References buttons, and math_equation_insert().
character_code_dialog_activate_cb()
G_MODULE_EXPORT void character_code_dialog_activate_cb (GtkWidget * entry, MathButtons * buttons)
Definition at line 1196 of file math-buttons.c.
References buttons, and character_code_dialog_response_cb().
character_code_dialog_delete_cb()
G_MODULE_EXPORT gboolean character_code_dialog_delete_cb (GtkWidget * dialog, GdkEvent * event, MathButtons * buttons)
Definition at line 1204 of file math-buttons.c.
References buttons, character_code_dialog_response_cb(), and TRUE.
character_code_dialog_response_cb()
G_MODULE_EXPORT void character_code_dialog_response_cb (GtkWidget * dialog, gint response_id, MathButtons * buttons)
Definition at line 1167 of file math-buttons.c.
References buttons, math_equation_insert_number(), mp_add_integer(), mp_clear(), mp_new(), mp_set_from_integer(), mp_shift(), and TRUE.
Referenced by character_code_dialog_activate_cb(), and character_code_dialog_delete_cb().
clear_cb()
G_MODULE_EXPORT void clear_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 815 of file math-buttons.c.
References buttons, and math_equation_clear().
const_cb()
G_MODULE_EXPORT void const_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 1012 of file math-buttons.c.
References _, buttons, FALSE, item, N_, name, and NULL.
delete_cb()
G_MODULE_EXPORT void delete_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 823 of file math-buttons.c.
References buttons, and math_equation_delete().
digit_cb()
G_MODULE_EXPORT void digit_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 1072 of file math-buttons.c.
References buttons, and math_equation_insert_digit().
exponent_cb()
G_MODULE_EXPORT void exponent_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 783 of file math-buttons.c.
References buttons, and math_equation_insert_exponent().
factorize_cb()
G_MODULE_EXPORT void factorize_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 1064 of file math-buttons.c.
References buttons, and math_equation_factorize().
finc_activate_cb()
G_MODULE_EXPORT void finc_activate_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 1108 of file math-buttons.c.
References buttons, GET_WIDGET, and NULL.
finc_cb()
G_MODULE_EXPORT void finc_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 1088 of file math-buttons.c.
References buttons, GET_WIDGET, and name.
finc_response_cb()
G_MODULE_EXPORT void finc_response_cb (GtkWidget * widget, gint response_id, MathButtons * buttons)
Definition at line 1134 of file math-buttons.c.
References buttons, do_finc_expression(), GET_WIDGET, mp_clear(), mp_new(), mp_set_from_string(), and NULL.
function_cb()
G_MODULE_EXPORT void function_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 961 of file math-buttons.c.
References _, buttons, FALSE, item, N_, name, and NULL.
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (MathButtons , math_buttons , GTK_TYPE_BOX)
insert_character_code_cb()
G_MODULE_EXPORT void insert_character_code_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 1100 of file math-buttons.c.
References buttons.
math_buttons_get_mode()
ButtonMode math_buttons_get_mode (MathButtons * buttons)
Definition at line 752 of file math-buttons.c.
References buttons.
math_buttons_get_programming_base()
gint math_buttons_get_programming_base (MathButtons * buttons)
Definition at line 774 of file math-buttons.c.
References buttons, and NULL.
Referenced by math_buttons_set_programming_base().
math_buttons_new()
MathButtons * math_buttons_new (MathEquation * equation)
Definition at line 305 of file math-buttons.c.
References math_buttons_get_type(), and NULL.
math_buttons_set_mode()
void math_buttons_set_mode (MathButtons * buttons, ButtonMode mode)
Definition at line 718 of file math-buttons.c.
References ADVANCED, buttons, FINANCIAL, math_converter_set_category(), math_converter_set_conversion(), math_equation_get_source_currency(), math_equation_get_source_units(), math_equation_get_target_currency(), math_equation_get_target_units(), math_equation_set_base(), NULL, and PROGRAMMING.
math_buttons_set_programming_base()
void math_buttons_set_programming_base (MathButtons * buttons, gint base)
Definition at line 758 of file math-buttons.c.
References buttons, g_settings_var, math_buttons_get_programming_base(), math_equation_set_base(), NULL, and PROGRAMMING.
memory_cb()
G_MODULE_EXPORT void memory_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 855 of file math-buttons.c.
References buttons, and math_variable_popup_new().
numeric_point_cb()
G_MODULE_EXPORT void numeric_point_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 1080 of file math-buttons.c.
References buttons, and math_equation_insert_numeric_point().
set_subscript_cb()
G_MODULE_EXPORT void set_subscript_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 1252 of file math-buttons.c.
References buttons, math_equation_get_number_mode(), math_equation_set_number_mode(), NORMAL, and SUBSCRIPT.
set_superscript_cb()
G_MODULE_EXPORT void set_superscript_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 1237 of file math-buttons.c.
References buttons, math_equation_get_number_mode(), math_equation_set_number_mode(), NORMAL, and SUPERSCRIPT.
shift_left_cb()
G_MODULE_EXPORT void shift_left_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 873 of file math-buttons.c.
References buttons, FALSE, item, and label.
shift_right_cb()
G_MODULE_EXPORT void shift_right_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 914 of file math-buttons.c.
References buttons, FALSE, item, and label.
solve_cb()
G_MODULE_EXPORT void solve_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 807 of file math-buttons.c.
References buttons, and math_equation_solve().
subtract_cb()
G_MODULE_EXPORT void subtract_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 791 of file math-buttons.c.
References buttons, and math_equation_insert_subtract().
undo_cb()
G_MODULE_EXPORT void undo_cb (GtkWidget * widget, MathButtons * buttons)
Definition at line 831 of file math-buttons.c.
References buttons, and math_equation_undo().