MATE Desktop Environment: math-preferences.c File Reference
math-preferences.c File Reference
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include "math-preferences.h"
#include "utility.h"
Macros
#define UI_DIALOGS_RESOURCE_PATH "/org/mate/calculator/ui/preferences.ui"
#define GET_WIDGET(ui, name) GTK_WIDGET(gtk_builder_get_object(ui, name))
Enumerations
enum { PROP_0 , PROP_EQUATION }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (MathPreferencesDialog, math_preferences, GTK_TYPE_DIALOG)
MathPreferencesDialog * math_preferences_dialog_new (MathEquation *equation)
void number_format_combobox_changed_cb (GtkWidget *combo, MathPreferencesDialog *dialog)
void angle_unit_combobox_changed_cb (GtkWidget *combo, MathPreferencesDialog *dialog)
void word_size_combobox_changed_cb (GtkWidget *combo, MathPreferencesDialog *dialog)
void decimal_places_spin_change_value_cb (GtkWidget *spin, MathPreferencesDialog *dialog)
void thousands_separator_check_toggled_cb (GtkWidget *check, MathPreferencesDialog *dialog)
void trailing_zeroes_check_toggled_cb (GtkWidget *check, MathPreferencesDialog *dialog)
Macro Definition Documentation
GET_WIDGET
#define GET_WIDGET (ui, name) GTK_WIDGET(gtk_builder_get_object(ui, name))
Definition at line 31 of file math-preferences.c.
UI_DIALOGS_RESOURCE_PATH
#define UI_DIALOGS_RESOURCE_PATH "/org/mate/calculator/ui/preferences.ui"
Definition at line 30 of file math-preferences.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_EQUATION
Definition at line 17 of file math-preferences.c.
Function Documentation
angle_unit_combobox_changed_cb()
G_MODULE_EXPORT void angle_unit_combobox_changed_cb (GtkWidget * combo, MathPreferencesDialog * dialog)
Definition at line 71 of file math-preferences.c.
References math_equation_set_angle_units(), and MathPreferencesDialog::priv.
decimal_places_spin_change_value_cb()
G_MODULE_EXPORT void decimal_places_spin_change_value_cb (GtkWidget * spin, MathPreferencesDialog * dialog)
Definition at line 101 of file math-preferences.c.
References math_equation_set_accuracy(), and MathPreferencesDialog::priv.
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (MathPreferencesDialog , math_preferences , GTK_TYPE_DIALOG)
math_preferences_dialog_new()
MathPreferencesDialog * math_preferences_dialog_new (MathEquation * equation)
Definition at line 35 of file math-preferences.c.
References math_preferences_get_type(), and NULL.
number_format_combobox_changed_cb()
G_MODULE_EXPORT void number_format_combobox_changed_cb (GtkWidget * combo, MathPreferencesDialog * dialog)
Definition at line 56 of file math-preferences.c.
References math_equation_set_number_format(), and MathPreferencesDialog::priv.
thousands_separator_check_toggled_cb()
G_MODULE_EXPORT void thousands_separator_check_toggled_cb (GtkWidget * check, MathPreferencesDialog * dialog)
Definition at line 112 of file math-preferences.c.
References math_equation_set_show_thousands_separators(), and MathPreferencesDialog::priv.
trailing_zeroes_check_toggled_cb()
G_MODULE_EXPORT void trailing_zeroes_check_toggled_cb (GtkWidget * check, MathPreferencesDialog * dialog)
Definition at line 123 of file math-preferences.c.
References math_equation_set_show_trailing_zeroes(), and MathPreferencesDialog::priv.
word_size_combobox_changed_cb()
G_MODULE_EXPORT void word_size_combobox_changed_cb (GtkWidget * combo, MathPreferencesDialog * dialog)
Definition at line 86 of file math-preferences.c.
References math_equation_set_word_size(), and MathPreferencesDialog::priv.