MATE Desktop Environment: mdi_demo.c File Reference
mdi_demo.c File Reference
#include <libmateui/mate-init.h>
#include <libmateui/mate-mdi.h>
#include <libmateui/mate-mdi-generic-child.h>
#include <libmateui/mate-mdi-child.h>
#include <matecomponent/matecomponent-ui-component.h>
Macros
#define COUNTER_KEY "counter"
Functions
int main (int argc, char **argv)
Variables
MateUIInfo real_child_menu []
MateUIInfo empty_menu []
MateUIInfo mode_list []
MateUIInfo mode_menu []
MateUIInfo mdi_menu []
MateUIInfo main_menu []
MateComponentUIVerb verbs []
Macro Definition Documentation
COUNTER_KEY
#define COUNTER_KEY "counter"
Definition at line 11 of file mdi_demo.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 244 of file mdi_demo.c.
References FALSE, mate_mdi_new(), mate_mdi_open_toplevel(), mate_mdi_set_child_list_path(), mate_mdi_set_child_menu_path(), mate_mdi_set_menubar_template(), mate_mdi_set_mode(), MATE_MDI_TOPLEVEL, and NULL.
Variable Documentation
empty_menu
MateUIInfo empty_menu[]
Initial value:
=
{
    MATEUIINFO_END
}
Definition at line 175 of file mdi_demo.c.
main_menu
MateUIInfo main_menu[]
Initial value:
=
{
    MATEUIINFO_SUBTREE("MDI", mdi_menu),
    MATEUIINFO_SUBTREE("Children", empty_menu),
    MATEUIINFO_END
}
Definition at line 208 of file mdi_demo.c.
Referenced by create_main_menu().
mdi_menu
MateUIInfo mdi_menu[]
Initial value:
=
{
    MATEUIINFO_SEPARATOR,
    MATEUIINFO_SUBTREE("Mode", mode_menu),
    MATEUIINFO_SEPARATOR,
    MATEUIINFO_MENU_EXIT_ITEM(exit_cb, NULL),
    MATEUIINFO_END
}
Definition at line 195 of file mdi_demo.c.
mode_list
MateUIInfo mode_list[]
Initial value:
=
{
    MATEUIINFO_RADIOITEM_DATA("Toplevel", NULL, mode_cb, GINT_TO_POINTER(MATE_MDI_TOPLEVEL), NULL),
    MATEUIINFO_RADIOITEM_DATA("Notebook", NULL, mode_cb, GINT_TO_POINTER(MATE_MDI_NOTEBOOK), NULL),
    MATEUIINFO_RADIOITEM_DATA("Window-in-Window", NULL, mode_cb, GINT_TO_POINTER(MATE_MDI_WIW), NULL),
    MATEUIINFO_RADIOITEM_DATA("Modal", NULL, mode_cb, GINT_TO_POINTER(MATE_MDI_MODAL), NULL),
    MATEUIINFO_END
}
Definition at line 180 of file mdi_demo.c.
mode_menu
MateUIInfo mode_menu[]
Initial value:
=
{
    MATEUIINFO_RADIOLIST(mode_list),
    MATEUIINFO_END
}
Definition at line 189 of file mdi_demo.c.
real_child_menu
MateUIInfo real_child_menu[]
Initial value:
=
{
    MATEUIINFO_ITEM("Add view", NULL, add_view_cb, NULL),
    MATEUIINFO_ITEM("Remove view", NULL, remove_view_cb, NULL),
    MATEUIINFO_SEPARATOR,
    MATEUIINFO_ITEM("Increase counter", NULL, increase_cb, NULL),
    MATEUIINFO_END
}
Definition at line 111 of file mdi_demo.c.
verbs
MateComponentUIVerb verbs[]
Initial value:
= {
    MATECOMPONENT_UI_VERB ("FileExit", quit_cmd),
    MATECOMPONENT_UI_VERB ("AddChild", add_child_cmd),
    MATECOMPONENT_UI_VERB ("RemoveChild", remove_child_cmd),
    MATECOMPONENT_UI_VERB_END
}
Definition at line 228 of file mdi_demo.c.