MATE Desktop Environment: mp-serializer.h File Reference
mp-serializer.h File Reference
#include <glib.h>
#include <glib-object.h>
#include "mp.h"
Classes
struct MpSerializer
struct MpSerializerClass
Macros
#define MP_TYPE_SERIALIZER (mp_serializer_get_type())
#define MP_SERIALIZER(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), mp_serializer_get_type(), MpSerializer))
Typedefs
typedef struct MpSerializerPrivate MpSerializerPrivate
Enumerations
enum MpDisplayFormat { MP_DISPLAY_FORMAT_AUTOMATIC , MP_DISPLAY_FORMAT_FIXED , MP_DISPLAY_FORMAT_SCIENTIFIC , MP_DISPLAY_FORMAT_ENGINEERING }
Functions
GType mp_serializer_get_type (void)
MpSerializer * mp_serializer_new (MpDisplayFormat format, int base, int trailing_digits)
gchar * mp_serializer_to_string (MpSerializer *serializer, const MPNumber *z)
gboolean mp_serializer_from_string (MpSerializer *serializer, const gchar *str, MPNumber *z)
void mp_serializer_set_number_format (MpSerializer *serializer, MpDisplayFormat format)
MpDisplayFormat mp_serializer_get_number_format (MpSerializer *serializer)
void mp_serializer_set_base (MpSerializer *serializer, int base)
int mp_serializer_get_base (MpSerializer *serializer)
void mp_serializer_set_leading_digits (MpSerializer *serializer, int leading_digits)
int mp_serializer_get_leading_digits (MpSerializer *serializer)
void mp_serializer_set_trailing_digits (MpSerializer *serializer, int trailing_digits)
int mp_serializer_get_trailing_digits (MpSerializer *serializer)
void mp_serializer_set_radix (MpSerializer *serializer, gunichar radix)
gunichar mp_serializer_get_radix (MpSerializer *serializer)
void mp_serializer_set_thousands_separator (MpSerializer *serializer, gunichar separator)
gunichar mp_serializer_get_thousands_separator (MpSerializer *serializer)
gint mp_serializer_get_thousands_separator_count (MpSerializer *serializer)
void mp_serializer_set_show_trailing_zeroes (MpSerializer *serializer, gboolean visible)
gboolean mp_serializer_get_show_trailing_zeroes (MpSerializer *serializer)
void mp_serializer_set_show_thousands_separators (MpSerializer *serializer, gboolean visible)
gboolean mp_serializer_get_show_thousands_separators (MpSerializer *serializer)
Macro Definition Documentation
MP_SERIALIZER
#define MP_SERIALIZER (obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), mp_serializer_get_type(), MpSerializer))
Definition at line 23 of file mp-serializer.h.
MP_TYPE_SERIALIZER
#define MP_TYPE_SERIALIZER (mp_serializer_get_type())
Definition at line 22 of file mp-serializer.h.
Typedef Documentation
MpSerializerPrivate
typedef struct MpSerializerPrivate MpSerializerPrivate
Definition at line 25 of file mp-serializer.h.
Enumeration Type Documentation
MpDisplayFormat
enum MpDisplayFormat
Enumerator
MP_DISPLAY_FORMAT_AUTOMATIC
MP_DISPLAY_FORMAT_FIXED
MP_DISPLAY_FORMAT_SCIENTIFIC
MP_DISPLAY_FORMAT_ENGINEERING
Definition at line 37 of file mp-serializer.h.
Function Documentation
mp_serializer_from_string()
gboolean mp_serializer_from_string (MpSerializer * serializer, const gchar * str, MPNumber * z)
Definition at line 415 of file mp-serializer.c.
References mp_set_from_string(), and MpSerializer::priv.
Referenced by math_equation_get_number().
mp_serializer_get_base()
int mp_serializer_get_base (MpSerializer * serializer)
Definition at line 427 of file mp-serializer.c.
References MpSerializer::priv.
Referenced by math_equation_get_base(), and math_equation_set_base().
mp_serializer_get_leading_digits()
int mp_serializer_get_leading_digits (MpSerializer * serializer)
Definition at line 487 of file mp-serializer.c.
References MpSerializer::priv.
mp_serializer_get_number_format()
MpDisplayFormat mp_serializer_get_number_format (MpSerializer * serializer)
Definition at line 511 of file mp-serializer.c.
References MpSerializer::priv.
Referenced by math_equation_get_number_format(), and math_equation_set_number_format().
mp_serializer_get_radix()
gunichar mp_serializer_get_radix (MpSerializer * serializer)
Definition at line 439 of file mp-serializer.c.
References MpSerializer::priv.
Referenced by math_equation_get_equation(), and math_equation_insert_numeric_point().
mp_serializer_get_show_thousands_separators()
gboolean mp_serializer_get_show_thousands_separators (MpSerializer * serializer)
Definition at line 469 of file mp-serializer.c.
References MpSerializer::priv.
Referenced by math_equation_get_show_thousands_separators(), and math_equation_set_show_thousands_separators().
mp_serializer_get_show_trailing_zeroes()
gboolean mp_serializer_get_show_trailing_zeroes (MpSerializer * serializer)
Definition at line 481 of file mp-serializer.c.
References MpSerializer::priv.
Referenced by math_equation_get_show_trailing_zeroes(), and math_equation_set_show_trailing_zeroes().
mp_serializer_get_thousands_separator()
gunichar mp_serializer_get_thousands_separator (MpSerializer * serializer)
Definition at line 451 of file mp-serializer.c.
References MpSerializer::priv.
Referenced by math_equation_get_equation().
mp_serializer_get_thousands_separator_count()
gint mp_serializer_get_thousands_separator_count (MpSerializer * serializer)
Definition at line 457 of file mp-serializer.c.
References MpSerializer::priv.
mp_serializer_get_trailing_digits()
int mp_serializer_get_trailing_digits (MpSerializer * serializer)
Definition at line 499 of file mp-serializer.c.
References MpSerializer::priv.
Referenced by math_equation_get_accuracy(), and math_equation_set_accuracy().
mp_serializer_get_type()
GType mp_serializer_get_type (void)
Referenced by mp_serializer_new().
mp_serializer_new()
MpSerializer * mp_serializer_new (MpDisplayFormat format, int base, int trailing_digits)
Definition at line 47 of file mp-serializer.c.
References mp_serializer_get_type(), mp_serializer_set_base(), mp_serializer_set_number_format(), mp_serializer_set_trailing_digits(), and NULL.
Referenced by main().
mp_serializer_set_base()
void mp_serializer_set_base (MpSerializer * serializer, int base)
mp_serializer_set_leading_digits()
void mp_serializer_set_leading_digits (MpSerializer * serializer, int leading_digits)
Definition at line 493 of file mp-serializer.c.
References MpSerializer::priv.
mp_serializer_set_number_format()
void mp_serializer_set_number_format (MpSerializer * serializer, MpDisplayFormat format)
Definition at line 517 of file mp-serializer.c.
References MpSerializer::priv.
Referenced by math_equation_set_number_format(), and mp_serializer_new().
mp_serializer_set_radix()
void mp_serializer_set_radix (MpSerializer * serializer, gunichar radix)
Definition at line 433 of file mp-serializer.c.
References MpSerializer::priv.
mp_serializer_set_show_thousands_separators()
void mp_serializer_set_show_thousands_separators (MpSerializer * serializer, gboolean visible)
Definition at line 463 of file mp-serializer.c.
References MpSerializer::priv.
Referenced by math_equation_set_show_thousands_separators().
mp_serializer_set_show_trailing_zeroes()
void mp_serializer_set_show_trailing_zeroes (MpSerializer * serializer, gboolean visible)
Definition at line 475 of file mp-serializer.c.
References MpSerializer::priv.
Referenced by math_equation_set_show_trailing_zeroes().
mp_serializer_set_thousands_separator()
void mp_serializer_set_thousands_separator (MpSerializer * serializer, gunichar separator)
Definition at line 445 of file mp-serializer.c.
References MpSerializer::priv.
mp_serializer_set_trailing_digits()
void mp_serializer_set_trailing_digits (MpSerializer * serializer, int trailing_digits)
Definition at line 505 of file mp-serializer.c.
References MpSerializer::priv.
Referenced by math_equation_set_accuracy(), and mp_serializer_new().
mp_serializer_to_string()
gchar * mp_serializer_to_string (MpSerializer * serializer, const MPNumber * z)
Definition at line 390 of file mp-serializer.c.
References FALSE, MP_DISPLAY_FORMAT_AUTOMATIC, MP_DISPLAY_FORMAT_ENGINEERING, MP_DISPLAY_FORMAT_FIXED, MP_DISPLAY_FORMAT_SCIENTIFIC, MpSerializer::priv, and TRUE.
Referenced by math_equation_insert_number(), math_equation_set_number(), math_history_entry_redisplay(), and unit_format().