MATE Desktop Environment: msd-keygrab.c File Reference
msd-keygrab.c File Reference
#include "config.h"
#include <gdk/gdk.h>
#include <gdk/gdkx.h>
#include "eggaccelerators.h"
#include "msd-keygrab.h"
Macros
#define N_BITS 32
Functions
void grab_key_unsafe (Key *key, gboolean grab, GSList *screens)
gboolean key_uses_keycode (const Key *key, guint keycode)
gboolean match_key (Key *key, XEvent *event)
Macro Definition Documentation
N_BITS
#define N_BITS 32
Definition at line 113 of file msd-keygrab.c.
Function Documentation
grab_key_unsafe()
void grab_key_unsafe (Key * key, gboolean grab, GSList * screens)
Definition at line 115 of file msd-keygrab.c.
References key, Key::keycodes, mask, N_BITS, and Key::state.
Referenced by msd_media_keys_manager_stop().
key_uses_keycode()
gboolean key_uses_keycode (const Key * key, guint keycode)
Definition at line 193 of file msd-keygrab.c.
References FALSE, key, Key::keycodes, NULL, and TRUE.
Referenced by match_key().
match_key()
gboolean match_key (Key * key, XEvent * event)
Definition at line 207 of file msd-keygrab.c.
References FALSE, key, key_uses_keycode(), Key::keysym, keyval, NULL, and Key::state.