MATE Desktop Environment: msd-xsettings-manager.h File Reference
msd-xsettings-manager.h File Reference
#include <glib-object.h>
Classes
struct MateXSettingsManager
struct MateXSettingsManagerClass
Macros
#define MATE_TYPE_XSETTINGS_MANAGER (mate_xsettings_manager_get_type ())
#define MATE_XSETTINGS_MANAGER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MATE_TYPE_XSETTINGS_MANAGER, MateXSettingsManager))
#define MATE_XSETTINGS_MANAGER_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), MATE_TYPE_XSETTINGS_MANAGER, MateXSettingsManagerClass))
#define MATE_IS_XSETTINGS_MANAGER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MATE_TYPE_XSETTINGS_MANAGER))
#define MATE_IS_XSETTINGS_MANAGER_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MATE_TYPE_XSETTINGS_MANAGER))
#define MATE_XSETTINGS_MANAGER_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MATE_TYPE_XSETTINGS_MANAGER, MateXSettingsManagerClass))
Typedefs
typedef struct MateXSettingsManagerPrivate MateXSettingsManagerPrivate
Functions
GType mate_xsettings_manager_get_type (void)
MateXSettingsManager * mate_xsettings_manager_new (void)
gboolean mate_xsettings_manager_start (MateXSettingsManager *manager, GError **error)
void mate_xsettings_manager_stop (MateXSettingsManager *manager)
Macro Definition Documentation
MATE_IS_XSETTINGS_MANAGER
#define MATE_IS_XSETTINGS_MANAGER (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MATE_TYPE_XSETTINGS_MANAGER))
Definition at line 34 of file msd-xsettings-manager.h.
MATE_IS_XSETTINGS_MANAGER_CLASS
#define MATE_IS_XSETTINGS_MANAGER_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), MATE_TYPE_XSETTINGS_MANAGER))
Definition at line 35 of file msd-xsettings-manager.h.
MATE_TYPE_XSETTINGS_MANAGER
#define MATE_TYPE_XSETTINGS_MANAGER (mate_xsettings_manager_get_type ())
Definition at line 31 of file msd-xsettings-manager.h.
MATE_XSETTINGS_MANAGER
#define MATE_XSETTINGS_MANAGER (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MATE_TYPE_XSETTINGS_MANAGER, MateXSettingsManager))
Definition at line 32 of file msd-xsettings-manager.h.
MATE_XSETTINGS_MANAGER_CLASS
#define MATE_XSETTINGS_MANAGER_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), MATE_TYPE_XSETTINGS_MANAGER, MateXSettingsManagerClass))
Definition at line 33 of file msd-xsettings-manager.h.
MATE_XSETTINGS_MANAGER_GET_CLASS
#define MATE_XSETTINGS_MANAGER_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), MATE_TYPE_XSETTINGS_MANAGER, MateXSettingsManagerClass))
Definition at line 36 of file msd-xsettings-manager.h.
Typedef Documentation
MateXSettingsManagerPrivate
typedef struct MateXSettingsManagerPrivate MateXSettingsManagerPrivate
Definition at line 38 of file msd-xsettings-manager.h.
Function Documentation
mate_xsettings_manager_get_type()
GType mate_xsettings_manager_get_type (void)
mate_xsettings_manager_new()
MateXSettingsManager * mate_xsettings_manager_new (void)
Definition at line 1063 of file msd-xsettings-manager.c.
References MATE_TYPE_XSETTINGS_MANAGER, MATE_XSETTINGS_MANAGER, and NULL.
mate_xsettings_manager_start()
gboolean mate_xsettings_manager_start (MateXSettingsManager * manager, GError ** error)
Definition at line 908 of file msd-xsettings-manager.c.
References error, FALSE, FONT_RENDER_SCHEMA, INTERFACE_SCHEMA, mate_settings_profile_end, mate_settings_profile_start, MOUSE_SCHEMA, MSD_XSETTINGS_ERROR, MSD_XSETTINGS_ERROR_INIT, NULL, MateXSettingsManager::priv, SOUND_SCHEMA, TRUE, xsettings_manager_notify(), xsettings_manager_set_overrides(), xsettings_manager_set_string(), XSETTINGS_OVERRIDE_KEY, and XSETTINGS_PLUGIN_SCHEMA.
mate_xsettings_manager_stop()
void mate_xsettings_manager_stop (MateXSettingsManager * manager)
Definition at line 999 of file msd-xsettings-manager.c.
References NULL, MateXSettingsManager::priv, and xsettings_manager_destroy().