MATE Desktop Environment: msd-locate-pointer.c File Reference
msd-locate-pointer.c File Reference
#include <gtk/gtk.h>
#include "msd-timeline.h"
#include "msd-locate-pointer.h"
#include <gdk/gdkkeysyms.h>
#include <gdk/gdkx.h>
#include <X11/keysym.h>
Macros
#define ANIMATION_LENGTH 750
#define WINDOW_SIZE 101
#define N_CIRCLES 4
#define CIRCLES_PROGRESS_INTERVAL (0.5 / N_CIRCLES)
#define CIRCLE_PROGRESS(p) (MIN (1., ((gdouble) (p) * 2.)))
#define KEYBOARD_GROUP_SHIFT 13
#define KEYBOARD_GROUP_MASK ((1 << 13) | (1 << 14))
Typedefs
typedef struct MsdLocatePointerData MsdLocatePointerData
Functions
void msd_locate_pointer (GdkDisplay *display)
int main (int argc, char *argv[])
Macro Definition Documentation
ANIMATION_LENGTH
#define ANIMATION_LENGTH 750
Definition at line 29 of file msd-locate-pointer.c.
CIRCLE_PROGRESS
#define CIRCLE_PROGRESS (p) (MIN (1., ((gdouble) (p) * 2.)))
Definition at line 39 of file msd-locate-pointer.c.
CIRCLES_PROGRESS_INTERVAL
#define CIRCLES_PROGRESS_INTERVAL (0.5 / N_CIRCLES)
Definition at line 38 of file msd-locate-pointer.c.
KEYBOARD_GROUP_MASK
#define KEYBOARD_GROUP_MASK ((1 << 13) | (1 << 14))
Definition at line 439 of file msd-locate-pointer.c.
KEYBOARD_GROUP_SHIFT
#define KEYBOARD_GROUP_SHIFT 13
Definition at line 438 of file msd-locate-pointer.c.
N_CIRCLES
#define N_CIRCLES 4
Definition at line 31 of file msd-locate-pointer.c.
WINDOW_SIZE
#define WINDOW_SIZE 101
Definition at line 30 of file msd-locate-pointer.c.
Typedef Documentation
MsdLocatePointerData
typedef struct MsdLocatePointerData MsdLocatePointerData
Definition at line 41 of file msd-locate-pointer.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 579 of file msd-locate-pointer.c.
msd_locate_pointer()
void msd_locate_pointer (GdkDisplay * display)
Definition at line 413 of file msd-locate-pointer.c.
References data, msd_timeline_pause(), msd_timeline_rewind(), msd_timeline_start(), and NULL.