MATE Desktop Environment: msd-rfkill-manager.c File Reference
msd-rfkill-manager.c File Reference
#include "config.h"
#include <gio/gio.h>
#include <string.h>
#include "mate-settings-profile.h"
#include "msd-rfkill-manager.h"
#include "rfkill-glib.h"
#include "mate-settings-bus.h"
Macros
#define MSD_DBUS_NAME "org.mate.SettingsDaemon"
#define MSD_DBUS_PATH "/org/mate/SettingsDaemon"
#define MSD_RFKILL_DBUS_NAME MSD_DBUS_NAME ".Rfkill"
#define MSD_RFKILL_DBUS_PATH MSD_DBUS_PATH "/Rfkill"
Functions
gboolean msd_rfkill_manager_start (MsdRfkillManager *manager, GError **error)
void msd_rfkill_manager_stop (MsdRfkillManager *manager)
MsdRfkillManager * msd_rfkill_manager_new (void)
Macro Definition Documentation
MSD_DBUS_NAME
#define MSD_DBUS_NAME "org.mate.SettingsDaemon"
Definition at line 62 of file msd-rfkill-manager.c.
MSD_DBUS_PATH
#define MSD_DBUS_PATH "/org/mate/SettingsDaemon"
Definition at line 63 of file msd-rfkill-manager.c.
MSD_RFKILL_DBUS_NAME
#define MSD_RFKILL_DBUS_NAME MSD_DBUS_NAME ".Rfkill"
Definition at line 65 of file msd-rfkill-manager.c.
MSD_RFKILL_DBUS_PATH
#define MSD_RFKILL_DBUS_PATH MSD_DBUS_PATH "/Rfkill"
Definition at line 66 of file msd-rfkill-manager.c.
Function Documentation
msd_rfkill_manager_new()
MsdRfkillManager * msd_rfkill_manager_new (void)
Definition at line 723 of file msd-rfkill-manager.c.
References MSD_RFKILL_MANAGER, MSD_TYPE_RFKILL_MANAGER, and NULL.
msd_rfkill_manager_start()
gboolean msd_rfkill_manager_start (MsdRfkillManager * manager, GError ** error)
Definition at line 627 of file msd-rfkill-manager.c.
References cc_rfkill_glib_new(), cc_rfkill_glib_open(), mate_settings_get_chassis_type(), mate_settings_profile_end, mate_settings_profile_start, NULL, MsdRfkillManager::priv, and TRUE.
msd_rfkill_manager_stop()
void msd_rfkill_manager_stop (MsdRfkillManager * manager)
Definition at line 675 of file msd-rfkill-manager.c.
References FALSE, and MsdRfkillManager::priv.