MATE Desktop Environment: msd-rfkill-manager.h File Reference
msd-rfkill-manager.h File Reference
#include <glib-object.h>
Classes
struct MsdRfkillManager
struct MsdRfkillManagerClass
Macros
#define MSD_TYPE_RFKILL_MANAGER (msd_rfkill_manager_get_type ())
#define MSD_RFKILL_MANAGER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MSD_TYPE_RFKILL_MANAGER, MsdRfkillManager))
#define MSD_RFKILL_MANAGER_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), MSD_TYPE_RFKILL_MANAGER, MsdRfkillManagerClass))
#define MSD_IS_RFKILL_MANAGER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MSD_TYPE_RFKILL_MANAGER))
#define MSD_IS_RFKILL_MANAGER_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MSD_TYPE_RFKILL_MANAGER))
#define MSD_RFKILL_MANAGER_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MSD_TYPE_RFKILL_MANAGER, MsdRfkillManagerClass))
Typedefs
typedef struct MsdRfkillManagerPrivate MsdRfkillManagerPrivate
Functions
GType msd_rfkill_manager_get_type (void)
MsdRfkillManager * msd_rfkill_manager_new (void)
gboolean msd_rfkill_manager_start (MsdRfkillManager *manager, GError **error)
void msd_rfkill_manager_stop (MsdRfkillManager *manager)
Macro Definition Documentation
MSD_IS_RFKILL_MANAGER
#define MSD_IS_RFKILL_MANAGER (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MSD_TYPE_RFKILL_MANAGER))
Definition at line 33 of file msd-rfkill-manager.h.
MSD_IS_RFKILL_MANAGER_CLASS
#define MSD_IS_RFKILL_MANAGER_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), MSD_TYPE_RFKILL_MANAGER))
Definition at line 34 of file msd-rfkill-manager.h.
MSD_RFKILL_MANAGER
#define MSD_RFKILL_MANAGER (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MSD_TYPE_RFKILL_MANAGER, MsdRfkillManager))
Definition at line 31 of file msd-rfkill-manager.h.
MSD_RFKILL_MANAGER_CLASS
#define MSD_RFKILL_MANAGER_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), MSD_TYPE_RFKILL_MANAGER, MsdRfkillManagerClass))
Definition at line 32 of file msd-rfkill-manager.h.
MSD_RFKILL_MANAGER_GET_CLASS
#define MSD_RFKILL_MANAGER_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), MSD_TYPE_RFKILL_MANAGER, MsdRfkillManagerClass))
Definition at line 35 of file msd-rfkill-manager.h.
MSD_TYPE_RFKILL_MANAGER
#define MSD_TYPE_RFKILL_MANAGER (msd_rfkill_manager_get_type ())
Definition at line 30 of file msd-rfkill-manager.h.
Typedef Documentation
MsdRfkillManagerPrivate
typedef struct MsdRfkillManagerPrivate MsdRfkillManagerPrivate
Definition at line 37 of file msd-rfkill-manager.h.
Function Documentation
msd_rfkill_manager_get_type()
GType msd_rfkill_manager_get_type (void)
msd_rfkill_manager_new()
MsdRfkillManager * msd_rfkill_manager_new (void)
Definition at line 723 of file msd-rfkill-manager.c.
References MSD_RFKILL_MANAGER, MSD_TYPE_RFKILL_MANAGER, and NULL.
msd_rfkill_manager_start()
gboolean msd_rfkill_manager_start (MsdRfkillManager * manager, GError ** error)
Definition at line 627 of file msd-rfkill-manager.c.
References cc_rfkill_glib_new(), cc_rfkill_glib_open(), mate_settings_get_chassis_type(), mate_settings_profile_end, mate_settings_profile_start, NULL, MsdRfkillManager::priv, and TRUE.
msd_rfkill_manager_stop()
void msd_rfkill_manager_stop (MsdRfkillManager * manager)
Definition at line 675 of file msd-rfkill-manager.c.
References FALSE, and MsdRfkillManager::priv.