MATE Desktop Environment: msd-media-keys-manager.h File Reference
msd-media-keys-manager.h File Reference
#include <glib.h>
#include <glib-object.h>
Classes
struct _MsdMediaKeysManager
struct _MsdMediaKeysManagerClass
Macros
#define MSD_TYPE_MEDIA_KEYS_MANAGER (msd_media_keys_manager_get_type ())
#define MSD_MEDIA_KEYS_MANAGER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MSD_TYPE_MEDIA_KEYS_MANAGER, MsdMediaKeysManager))
#define MSD_MEDIA_KEYS_MANAGER_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), MSD_TYPE_MEDIA_KEYS_MANAGER, MsdMediaKeysManagerClass))
#define MSD_IS_MEDIA_KEYS_MANAGER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MSD_TYPE_MEDIA_KEYS_MANAGER))
#define MSD_IS_MEDIA_KEYS_MANAGER_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), MSD_TYPE_MEDIA_KEYS_MANAGER))
#define MSD_MEDIA_KEYS_MANAGER_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), MSD_TYPE_MEDIA_KEYS_MANAGER, MsdMediaKeysManagerClass))
Typedefs
typedef struct _MsdMediaKeysManager MsdMediaKeysManager
typedef struct _MsdMediaKeysManagerClass MsdMediaKeysManagerClass
typedef struct _MsdMediaKeysManagerPrivate MsdMediaKeysManagerPrivate
Functions
GType msd_media_keys_manager_get_type (void)
MsdMediaKeysManager * msd_media_keys_manager_new (void)
gboolean msd_media_keys_manager_start (MsdMediaKeysManager *manager, GError **error)
void msd_media_keys_manager_stop (MsdMediaKeysManager *manager)
Macro Definition Documentation
MSD_IS_MEDIA_KEYS_MANAGER
#define MSD_IS_MEDIA_KEYS_MANAGER (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), MSD_TYPE_MEDIA_KEYS_MANAGER))
Definition at line 34 of file msd-media-keys-manager.h.
MSD_IS_MEDIA_KEYS_MANAGER_CLASS
#define MSD_IS_MEDIA_KEYS_MANAGER_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), MSD_TYPE_MEDIA_KEYS_MANAGER))
Definition at line 35 of file msd-media-keys-manager.h.
MSD_MEDIA_KEYS_MANAGER
#define MSD_MEDIA_KEYS_MANAGER (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), MSD_TYPE_MEDIA_KEYS_MANAGER, MsdMediaKeysManager))
Definition at line 32 of file msd-media-keys-manager.h.
MSD_MEDIA_KEYS_MANAGER_CLASS
#define MSD_MEDIA_KEYS_MANAGER_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), MSD_TYPE_MEDIA_KEYS_MANAGER, MsdMediaKeysManagerClass))
Definition at line 33 of file msd-media-keys-manager.h.
MSD_MEDIA_KEYS_MANAGER_GET_CLASS
#define MSD_MEDIA_KEYS_MANAGER_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), MSD_TYPE_MEDIA_KEYS_MANAGER, MsdMediaKeysManagerClass))
Definition at line 36 of file msd-media-keys-manager.h.
MSD_TYPE_MEDIA_KEYS_MANAGER
#define MSD_TYPE_MEDIA_KEYS_MANAGER (msd_media_keys_manager_get_type ())
Definition at line 31 of file msd-media-keys-manager.h.
Typedef Documentation
MsdMediaKeysManager
typedef struct _MsdMediaKeysManager MsdMediaKeysManager
Definition at line 38 of file msd-media-keys-manager.h.
MsdMediaKeysManagerClass
typedef struct _MsdMediaKeysManagerClass MsdMediaKeysManagerClass
Definition at line 39 of file msd-media-keys-manager.h.
MsdMediaKeysManagerPrivate
typedef struct _MsdMediaKeysManagerPrivate MsdMediaKeysManagerPrivate
Definition at line 40 of file msd-media-keys-manager.h.
Function Documentation
msd_media_keys_manager_get_type()
GType msd_media_keys_manager_get_type (void)
msd_media_keys_manager_new()
MsdMediaKeysManager * msd_media_keys_manager_new (void)
Definition at line 1834 of file msd-media-keys-manager.c.
References MSD_MEDIA_KEYS_MANAGER, MSD_TYPE_MEDIA_KEYS_MANAGER, and NULL.
Referenced by main().
msd_media_keys_manager_start()
gboolean msd_media_keys_manager_start (MsdMediaKeysManager * manager, GError ** error)
Definition at line 1604 of file msd-media-keys-manager.c.
References mate_mixer_context_new(), mate_mixer_context_open(), mate_mixer_is_initialized(), mate_settings_profile_end, mate_settings_profile_start, NULL, _MsdMediaKeysManager::priv, and TRUE.
Referenced by main().
msd_media_keys_manager_stop()
void msd_media_keys_manager_stop (MsdMediaKeysManager * manager)
Definition at line 1645 of file msd-media-keys-manager.c.
References FALSE, grab_key_unsafe(), HANDLED_KEYS, key, Key::keycodes, NULL, _MsdMediaKeysManager::priv, and TRUE.