MATE Desktop Environment: na-boxed.h File Reference
na-boxed.h File Reference
#include <glib-object.h>
Classes
struct NABoxed
struct NABoxedClass
Macros
#define NA_TYPE_BOXED (na_boxed_get_type())
#define NA_BOXED(object) (G_TYPE_CHECK_INSTANCE_CAST(object, NA_TYPE_BOXED, NABoxed))
#define NA_BOXED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, NA_TYPE_BOXED, NABoxedClass))
#define NA_IS_BOXED(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, NA_TYPE_BOXED))
#define NA_IS_BOXED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), NA_TYPE_BOXED))
#define NA_BOXED_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), NA_TYPE_BOXED, NABoxedClass))
Typedefs
typedef struct _NABoxedPrivate NABoxedPrivate
typedef struct _NABoxedClassPrivate NABoxedClassPrivate
Functions
GType na_boxed_get_type (void)
void na_boxed_set_type (NABoxed *boxed, guint type)
gboolean na_boxed_are_equal (const NABoxed *a, const NABoxed *b)
NABoxed * na_boxed_copy (const NABoxed *boxed)
void na_boxed_dump (const NABoxed *boxed)
NABoxed * na_boxed_new_from_string (guint type, const gchar *string)
gboolean na_boxed_get_boolean (const NABoxed *boxed)
gconstpointer na_boxed_get_pointer (const NABoxed *boxed)
gchar * na_boxed_get_string (const NABoxed *boxed)
GSList * na_boxed_get_string_list (const NABoxed *boxed)
guint na_boxed_get_uint (const NABoxed *boxed)
GList * na_boxed_get_uint_list (const NABoxed *boxed)
void na_boxed_get_as_value (const NABoxed *boxed, GValue *value)
void * na_boxed_get_as_void (const NABoxed *boxed)
void na_boxed_set_from_boxed (NABoxed *boxed, const NABoxed *value)
void na_boxed_set_from_string (NABoxed *boxed, const gchar *value)
void na_boxed_set_from_value (NABoxed *boxed, const GValue *value)
void na_boxed_set_from_void (NABoxed *boxed, const void *value)
Macro Definition Documentation
NA_BOXED
#define NA_BOXED (object) (G_TYPE_CHECK_INSTANCE_CAST(object, NA_TYPE_BOXED, NABoxed))
Definition at line 50 of file na-boxed.h.
NA_BOXED_CLASS
#define NA_BOXED_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, NA_TYPE_BOXED, NABoxedClass))
Definition at line 51 of file na-boxed.h.
NA_BOXED_GET_CLASS
#define NA_BOXED_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), NA_TYPE_BOXED, NABoxedClass))
Definition at line 54 of file na-boxed.h.
NA_IS_BOXED
#define NA_IS_BOXED (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, NA_TYPE_BOXED))
Definition at line 52 of file na-boxed.h.
NA_IS_BOXED_CLASS
#define NA_IS_BOXED_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), NA_TYPE_BOXED))
Definition at line 53 of file na-boxed.h.
NA_TYPE_BOXED
#define NA_TYPE_BOXED (na_boxed_get_type())
SECTION: boxed @title: NABoxed @short_description: The NABoxed Structure caja-actions/na-boxed.h
The NABoxed structure is a way of handling various types of data in an opaque structure.
Since: 3.1
Definition at line 49 of file na-boxed.h.
Typedef Documentation
NABoxedClassPrivate
typedef struct _NABoxedClassPrivate NABoxedClassPrivate
Definition at line 65 of file na-boxed.h.
NABoxedPrivate
typedef struct _NABoxedPrivate NABoxedPrivate
Definition at line 56 of file na-boxed.h.
Function Documentation
na_boxed_are_equal()
gboolean na_boxed_are_equal (const NABoxed * a, const NABoxed * b)
na_boxed_are_equal: : the first NABoxed object. : the second NABoxed object.
Returns: TRUE if and are equal, FALSE else.
Since: 3.1
Definition at line 512 of file na-boxed.c.
References b, FALSE, NA_IS_BOXED, NABoxed::private, and TRUE.
Referenced by na_factory_object_are_equal().
na_boxed_copy()
NABoxed * na_boxed_copy (const NABoxed * boxed)
na_boxed_copy: @boxed: the source NABoxed box.
Returns: a copy of @boxed, as a newly allocated NABoxed which should be g_object_unref() by the caller.
Since: 3.1
Definition at line 546 of file na-boxed.c.
References dest, FALSE, NA_IS_BOXED, NULL, NABoxed::private, and TRUE.
na_boxed_dump()
void na_boxed_dump (const NABoxed * boxed)
na_boxed_dump: @boxed: the NABoxed box to be dumped.
Dumps the @boxed box.
Since: 3.1
Definition at line 573 of file na-boxed.c.
References FALSE, NA_IS_BOXED, NULL, and NABoxed::private.
na_boxed_get_as_value()
void na_boxed_get_as_value (const NABoxed * boxed, GValue * value)
na_boxed_get_as_value: @boxed: the NABoxed whose value is to be got. @value: the #GValue which holds the string to be set.
Setup @value with the content of the @boxed.
Since: 3.1
Definition at line 782 of file na-boxed.c.
References FALSE, NA_IS_BOXED, and NABoxed::private.
Referenced by na_factory_object_get_as_value().
na_boxed_get_as_void()
void * na_boxed_get_as_void (const NABoxed * boxed)
na_boxed_get_as_void: @boxed: the NABoxed whose value is to be got.
Returns: the content of the @boxed.
If of type NA_DATA_TYPE_STRING (resp. NA_DATA_TYPE_LOCALE_STRING, NA_DATA_TYPE_STRING_LIST or NA_DATA_TYPE_UINT_LIST), then the content is returned in a newly allocated value, which should be g_free() (resp. g_free(), na_core_utils_slist_free(), g_list_free()) by the caller.
Since: 3.1
Definition at line 806 of file na-boxed.c.
References FALSE, NA_IS_BOXED, NULL, and NABoxed::private.
Referenced by cadp_writer_ifactory_provider_write_data(), and na_factory_object_get_as_void().
na_boxed_get_boolean()
gboolean na_boxed_get_boolean (const NABoxed * boxed)
na_boxed_get_boolean: @boxed: the NABoxed structure.
Returns: the boolean value if @boxed is of NA_DATA_TYPE_BOOLEAN type, FALSE else.
Since: 3.1
Definition at line 634 of file na-boxed.c.
References FALSE, NA_DATA_TYPE_BOOLEAN, NA_IS_BOXED, and NABoxed::private.
Referenced by na_settings_get_boolean_ex().
na_boxed_get_pointer()
gconstpointer na_boxed_get_pointer (const NABoxed * boxed)
na_boxed_get_pointer: @boxed: the NABoxed structure.
Returns: a const pointer to the data if @boxed is of NA_DATA_TYPE_POINTER type, NULL else.
Since: 3.1
Definition at line 659 of file na-boxed.c.
References FALSE, NA_IS_BOXED, NULL, and NABoxed::private.
na_boxed_get_string()
gchar * na_boxed_get_string (const NABoxed * boxed)
na_boxed_get_string: @boxed: the NABoxed structure.
Returns: a newly allocated string if @boxed is of NA_DATA_TYPE_STRING type, which should be g_free() by the caller, NULL else.
Since: 3.1
Definition at line 683 of file na-boxed.c.
References FALSE, NA_IS_BOXED, NULL, and NABoxed::private.
Referenced by cadp_writer_ifactory_provider_write_data(), na_factory_object_dump(), and na_settings_get_string().
na_boxed_get_string_list()
GSList * na_boxed_get_string_list (const NABoxed * boxed)
na_boxed_get_string_list: @boxed: the NABoxed structure.
Returns: a newly allocated string list if @boxed is of NA_DATA_TYPE_STRING_LIST type, which should be na_core_utils_slist_free() by the caller, NULL else.
Since: 3.1
Definition at line 707 of file na-boxed.c.
References FALSE, NA_DATA_TYPE_STRING_LIST, NA_IS_BOXED, NULL, and NABoxed::private.
Referenced by na_settings_get_string_list().
na_boxed_get_type()
GType na_boxed_get_type (void)
Definition at line 296 of file na-boxed.c.
na_boxed_get_uint()
guint na_boxed_get_uint (const NABoxed * boxed)
na_boxed_get_uint: @boxed: the NABoxed structure.
Returns: an unsigned integer if @boxed is of NA_DATA_TYPE_UINT type, zero else.
Since: 3.1
Definition at line 732 of file na-boxed.c.
References FALSE, NA_DATA_TYPE_UINT, NA_IS_BOXED, and NABoxed::private.
Referenced by na_settings_get_uint().
na_boxed_get_uint_list()
GList * na_boxed_get_uint_list (const NABoxed * boxed)
na_boxed_get_uint_list: @boxed: the NABoxed structure.
Returns: a newly allocated list if @boxed is of NA_DATA_TYPE_UINT_LIST type, which should be g_list_free() by the caller, FALSE else.
Since: 3.1
Definition at line 757 of file na-boxed.c.
References FALSE, NA_DATA_TYPE_UINT_LIST, NA_IS_BOXED, NULL, and NABoxed::private.
Referenced by na_settings_get_uint_list().
na_boxed_new_from_string()
NABoxed * na_boxed_new_from_string (guint type, const gchar * string)
na_boxed_new_from_string: @type: the type of the NABoxed to be allocated. @string: the initial value of the NABoxed as a string.
Allocates a new NABoxed of the specified @type, and initializes it with @string.
If the type is a list, then the last separator is automatically stripped.
Returns: a newly allocated NABoxed, which should be g_object_unref() by the caller, or NULL if the type is unknowned, or does not provide the 'from_string' function.
Since: 3.1
Definition at line 607 of file na-boxed.c.
References NULL, NABoxed::private, TRUE, and type.
na_boxed_set_from_boxed()
void na_boxed_set_from_boxed (NABoxed * boxed, const NABoxed * value)
na_boxed_set_from_boxed: @boxed: the NABoxed whose value is to be set. @value: the source NABoxed.
Copy value from @value to @boxed.
Since: 3.1
Definition at line 826 of file na-boxed.c.
References FALSE, NA_IS_BOXED, NABoxed::private, and TRUE.
Referenced by na_factory_object_copy().
na_boxed_set_from_string()
void na_boxed_set_from_string (NABoxed * boxed, const gchar * value)
na_boxed_set_from_string: @boxed: the NABoxed whose value is to be set. @value: the string to be set.
Evaluates the @value and set it to the @boxed.
Since: 3.1
Definition at line 852 of file na-boxed.c.
References FALSE, NA_IS_BOXED, NABoxed::private, and TRUE.
na_boxed_set_from_value()
void na_boxed_set_from_value (NABoxed * boxed, const GValue * value)
na_boxed_set_from_value: @boxed: the NABoxed whose value is to be set. @value: the value whose content is to be got.
Evaluates the @value and set it to the @boxed.
Since: 3.1
Definition at line 875 of file na-boxed.c.
References FALSE, NA_IS_BOXED, NABoxed::private, and TRUE.
Referenced by na_factory_object_set_from_value().
na_boxed_set_from_void()
void na_boxed_set_from_void (NABoxed * boxed, const void * value)
na_boxed_set_from_void: @boxed: the NABoxed whose value is to be set. @value: the value whose content is to be got.
Evaluates the @value and set it to the @boxed.
Since: 3.1
Definition at line 898 of file na-boxed.c.
References FALSE, NA_IS_BOXED, NABoxed::private, and TRUE.
Referenced by cadp_reader_ifactory_provider_read_data(), and na_factory_object_set_from_void().
na_boxed_set_type()
void na_boxed_set_type (NABoxed * boxed, guint type)
na_boxed_set_type: @boxed: this NABoxed object. @type: the required type as defined in na-data-types.h
Set the type of the just-allocated @boxed object.
Since: 3.1
Definition at line 493 of file na-boxed.c.
References FALSE, NA_IS_BOXED, NULL, NABoxed::private, and type.
Referenced by na_data_boxed_new().