MATE Desktop Environment: na-export-format.c File Reference
na-export-format.c File Reference
#include "na-export-format.h"
#include "na-ioption.h"
Functions
GType na_export_format_get_type (void)
NAExportFormat * na_export_format_new (const NAIExporterFormatv2 *exporter_format)
NAIExporter * na_export_format_get_provider (const NAExportFormat *format)
Function Documentation
na_export_format_get_provider()
NAIExporter * na_export_format_get_provider (const NAExportFormat * format)
Definition at line 346 of file na-export-format.c.
References NA_IS_EXPORT_FORMAT, NULL, and NAExportFormat::private.
Referenced by na_exporter_find_for_format().
na_export_format_get_type()
GType na_export_format_get_type (void)
Definition at line 68 of file na-export-format.c.
na_export_format_new()
NAExportFormat * na_export_format_new (const NAIExporterFormatv2 * exporter_format)
Definition at line 321 of file na-export-format.c.
References NAIExporterFormatv2::description, NAIExporterFormatv2::format, NAIExporterFormatv2::label, NA_TYPE_EXPORT_FORMAT, NULL, NAIExporterFormatv2::pixbuf, NAExportFormat::private, and NAIExporterFormatv2::provider.
Referenced by na_exporter_get_ask_option(), and na_exporter_get_formats().