MATE Desktop Environment: na-export-format.h File Reference
na-export-format.h File Reference
#include <api/na-iexporter.h>
Classes
struct NAExportFormat
struct NAExportFormatClass
Macros
#define NA_TYPE_EXPORT_FORMAT (na_export_format_get_type())
#define NA_EXPORT_FORMAT(object) (G_TYPE_CHECK_INSTANCE_CAST(object, NA_TYPE_EXPORT_FORMAT, NAExportFormat))
#define NA_EXPORT_FORMAT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, NA_TYPE_EXPORT_FORMAT, NAExportFormatClass))
#define NA_IS_EXPORT_FORMAT(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, NA_TYPE_EXPORT_FORMAT))
#define NA_IS_EXPORT_FORMAT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), NA_TYPE_EXPORT_FORMAT))
#define NA_EXPORT_FORMAT_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), NA_TYPE_EXPORT_FORMAT, NAExportFormatClass))
Typedefs
typedef struct _NAExportFormatPrivate NAExportFormatPrivate
typedef struct _NAExportFormatClassPrivate NAExportFormatClassPrivate
Functions
GType na_export_format_get_type (void)
NAExportFormat * na_export_format_new (const NAIExporterFormatv2 *exporter_format)
NAIExporter * na_export_format_get_provider (const NAExportFormat *format)
Macro Definition Documentation
NA_EXPORT_FORMAT
#define NA_EXPORT_FORMAT (object) (G_TYPE_CHECK_INSTANCE_CAST(object, NA_TYPE_EXPORT_FORMAT, NAExportFormat))
Definition at line 43 of file na-export-format.h.
NA_EXPORT_FORMAT_CLASS
#define NA_EXPORT_FORMAT_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, NA_TYPE_EXPORT_FORMAT, NAExportFormatClass))
Definition at line 44 of file na-export-format.h.
NA_EXPORT_FORMAT_GET_CLASS
#define NA_EXPORT_FORMAT_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), NA_TYPE_EXPORT_FORMAT, NAExportFormatClass))
Definition at line 47 of file na-export-format.h.
NA_IS_EXPORT_FORMAT
#define NA_IS_EXPORT_FORMAT (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, NA_TYPE_EXPORT_FORMAT))
Definition at line 45 of file na-export-format.h.
NA_IS_EXPORT_FORMAT_CLASS
#define NA_IS_EXPORT_FORMAT_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), NA_TYPE_EXPORT_FORMAT))
Definition at line 46 of file na-export-format.h.
NA_TYPE_EXPORT_FORMAT
#define NA_TYPE_EXPORT_FORMAT (na_export_format_get_type())
Definition at line 42 of file na-export-format.h.
Typedef Documentation
NAExportFormatClassPrivate
typedef struct _NAExportFormatClassPrivate NAExportFormatClassPrivate
Definition at line 57 of file na-export-format.h.
NAExportFormatPrivate
typedef struct _NAExportFormatPrivate NAExportFormatPrivate
Definition at line 49 of file na-export-format.h.
Function Documentation
na_export_format_get_provider()
NAIExporter * na_export_format_get_provider (const NAExportFormat * format)
Definition at line 346 of file na-export-format.c.
References NA_IS_EXPORT_FORMAT, NULL, and NAExportFormat::private.
Referenced by na_exporter_find_for_format().
na_export_format_get_type()
GType na_export_format_get_type (void)
Definition at line 68 of file na-export-format.c.
na_export_format_new()
NAExportFormat * na_export_format_new (const NAIExporterFormatv2 * exporter_format)
Definition at line 321 of file na-export-format.c.
References NAIExporterFormatv2::description, NAIExporterFormatv2::format, NAIExporterFormatv2::label, NA_TYPE_EXPORT_FORMAT, NULL, NAIExporterFormatv2::pixbuf, NAExportFormat::private, and NAIExporterFormatv2::provider.
Referenced by na_exporter_get_ask_option(), and na_exporter_get_formats().