MATE Desktop Environment: na-factory-object.c File Reference
na-factory-object.c File Reference
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <api/na-core-utils.h>
#include <api/na-data-boxed.h>
#include <api/na-data-types.h>
#include <api/na-iio-provider.h>
#include <api/na-ifactory-provider.h>
#include <api/na-object-api.h>
#include "na-factory-object.h"
#include "na-factory-provider.h"
Typedefs
typedef gboolean(* NADataDefIterFunc) (NADataDef *def, void *user_data)
Enumerations
enum { DATA_DEF_ITER_SET_PROPERTIES = 1 , DATA_DEF_ITER_SET_DEFAULTS , DATA_DEF_ITER_IS_VALID , DATA_DEF_ITER_READ_ITEM }
Functions
void na_factory_object_define_properties (GObjectClass *class, const NADataGroup *groups)
NADataDef * na_factory_object_get_data_def (const NAIFactoryObject *object, const gchar *name)
NADataGroup * na_factory_object_get_data_groups (const NAIFactoryObject *object)
void na_factory_object_iter_on_boxed (const NAIFactoryObject *object, NAFactoryObjectIterBoxedFn pfn, void *user_data)
gchar * na_factory_object_get_default (NAIFactoryObject *object, const gchar *name)
void na_factory_object_set_defaults (NAIFactoryObject *object)
void na_factory_object_move_boxed (NAIFactoryObject *target, const NAIFactoryObject *source, NADataBoxed *boxed)
void na_factory_object_copy (NAIFactoryObject *target, const NAIFactoryObject *source)
gboolean na_factory_object_are_equal (const NAIFactoryObject *a, const NAIFactoryObject *b)
gboolean na_factory_object_is_valid (const NAIFactoryObject *object)
void na_factory_object_dump (const NAIFactoryObject *object)
void na_factory_object_finalize (NAIFactoryObject *object)
void na_factory_object_read_item (NAIFactoryObject *object, const NAIFactoryProvider *reader, void *reader_data, GSList **messages)
guint na_factory_object_write_item (NAIFactoryObject *object, const NAIFactoryProvider *writer, void *writer_data, GSList **messages)
void na_factory_object_get_as_value (const NAIFactoryObject *object, const gchar *name, GValue *value)
void * na_factory_object_get_as_void (const NAIFactoryObject *object, const gchar *name)
gboolean na_factory_object_is_set (const NAIFactoryObject *object, const gchar *name)
void na_factory_object_set_from_value (NAIFactoryObject *object, const gchar *name, const GValue *value)
void na_factory_object_set_from_void (NAIFactoryObject *object, const gchar *name, const void *data)
Variables
gboolean ifactory_object_initialized
gboolean ifactory_object_finalized
Typedef Documentation
NADataDefIterFunc
typedef gboolean(* NADataDefIterFunc) (NADataDef *def, void *user_data)
Definition at line 48 of file na-factory-object.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DATA_DEF_ITER_SET_PROPERTIES
DATA_DEF_ITER_SET_DEFAULTS
DATA_DEF_ITER_IS_VALID
DATA_DEF_ITER_READ_ITEM
Definition at line 50 of file na-factory-object.c.
Function Documentation
na_factory_object_are_equal()
gboolean na_factory_object_are_equal (const NAIFactoryObject * a, const NAIFactoryObject * b)
Definition at line 424 of file na-factory-object.c.
References b, NADataDef::comparable, FALSE, NA_BOXED, na_boxed_are_equal(), NA_DATA_BOXED, na_data_boxed_get_data_def(), na_ifactory_object_get_data_boxed(), NA_IFACTORY_OBJECT_PROP_DATA, NADataDef::name, and TRUE.
na_factory_object_copy()
void na_factory_object_copy (NAIFactoryObject * target, const NAIFactoryObject * source)
Definition at line 355 of file na-factory-object.c.
References NADataDef::copyable, NA_BOXED, na_boxed_set_from_boxed(), NA_DATA_BOXED, na_data_boxed_get_data_def(), na_data_boxed_new(), na_ifactory_object_get_data_boxed(), NA_IFACTORY_OBJECT_PROP_DATA, NA_IS_IFACTORY_OBJECT, na_object_get_provider, na_object_get_provider_data, na_object_set_provider, na_object_set_provider_data, and NADataDef::name.
Referenced by cact_tree_ieditable_set_items().
na_factory_object_define_properties()
void na_factory_object_define_properties (GObjectClass * class, const NADataGroup * groups)
Definition at line 122 of file na-factory-object.c.
References DATA_DEF_ITER_SET_PROPERTIES.
na_factory_object_dump()
void na_factory_object_dump (const NAIFactoryObject * object)
Definition at line 543 of file na-factory-object.c.
References MAX, NA_BOXED, na_boxed_get_string(), NA_DATA_BOXED, na_data_boxed_get_data_def(), NA_IFACTORY_OBJECT_PROP_DATA, NADataDef::name, and prefix.
na_factory_object_finalize()
void na_factory_object_finalize (NAIFactoryObject * object)
Definition at line 580 of file na-factory-object.c.
na_factory_object_get_as_value()
void na_factory_object_get_as_value (const NAIFactoryObject * object, const gchar * name, GValue * value)
Definition at line 733 of file na-factory-object.c.
References NA_BOXED, na_boxed_get_as_value(), na_ifactory_object_get_data_boxed(), NA_IS_IFACTORY_OBJECT, and name.
na_factory_object_get_as_void()
void * na_factory_object_get_as_void (const NAIFactoryObject * object, const gchar * name)
Definition at line 760 of file na-factory-object.c.
References NA_BOXED, na_boxed_get_as_void(), na_ifactory_object_get_data_boxed(), NA_IS_IFACTORY_OBJECT, name, and NULL.
Referenced by na_ifactory_object_get_as_void().
na_factory_object_get_data_def()
NADataDef * na_factory_object_get_data_def (const NAIFactoryObject * object, const gchar * name)
Definition at line 167 of file na-factory-object.c.
References NADataGroup::def, NADataGroup::group, NA_IS_IFACTORY_OBJECT, name, NADataDef::name, and NULL.
Referenced by na_factory_object_get_default(), na_factory_object_move_boxed(), na_factory_object_set_from_value(), and na_factory_object_set_from_void().
na_factory_object_get_data_groups()
NADataGroup * na_factory_object_get_data_groups (const NAIFactoryObject * object)
Definition at line 198 of file na-factory-object.c.
References NA_IS_IFACTORY_OBJECT, and NULL.
na_factory_object_get_default()
gchar * na_factory_object_get_default (NAIFactoryObject * object, const gchar * name)
Definition at line 245 of file na-factory-object.c.
References NADataDef::default_value, na_factory_object_get_data_def(), NA_IS_IFACTORY_OBJECT, name, and NULL.
na_factory_object_is_set()
gboolean na_factory_object_is_set (const NAIFactoryObject * object, const gchar * name)
Definition at line 785 of file na-factory-object.c.
References FALSE, na_ifactory_object_get_data_boxed(), NA_IS_IFACTORY_OBJECT, name, and NULL.
na_factory_object_is_valid()
gboolean na_factory_object_is_valid (const NAIFactoryObject * object)
Definition at line 484 of file na-factory-object.c.
References DATA_DEF_ITER_IS_VALID, FALSE, NA_DATA_BOXED, na_data_boxed_is_valid(), NA_IFACTORY_OBJECT_PROP_DATA, NA_IS_IFACTORY_OBJECT, and TRUE.
na_factory_object_iter_on_boxed()
void na_factory_object_iter_on_boxed (const NAIFactoryObject * object, NAFactoryObjectIterBoxedFn pfn, void * user_data)
Definition at line 220 of file na-factory-object.c.
References FALSE, NA_DATA_BOXED, NA_IFACTORY_OBJECT_PROP_DATA, NA_IS_IFACTORY_OBJECT, and user_data.
Referenced by na_factory_object_write_item().
na_factory_object_move_boxed()
void na_factory_object_move_boxed (NAIFactoryObject * target, const NAIFactoryObject * source, NADataBoxed * boxed)
Definition at line 327 of file na-factory-object.c.
References na_data_boxed_get_data_def(), na_data_boxed_set_data_def(), na_factory_object_get_data_def(), NA_IFACTORY_OBJECT_PROP_DATA, NA_IS_IFACTORY_OBJECT, and NADataDef::name.
na_factory_object_read_item()
void na_factory_object_read_item (NAIFactoryObject * object, const NAIFactoryProvider * reader, void * reader_data, GSList ** messages)
Definition at line 596 of file na-factory-object.c.
References DATA_DEF_ITER_READ_ITEM, NA_IS_IFACTORY_OBJECT, and NA_IS_IFACTORY_PROVIDER.
Referenced by na_ifactory_provider_read_item().
na_factory_object_set_defaults()
void na_factory_object_set_defaults (NAIFactoryObject * object)
Definition at line 272 of file na-factory-object.c.
References DATA_DEF_ITER_SET_DEFAULTS, and NA_IS_IFACTORY_OBJECT.
Referenced by na_object_action_new_with_defaults(), na_object_menu_new_with_defaults(), and na_object_profile_new_with_defaults().
na_factory_object_set_from_value()
void na_factory_object_set_from_value (NAIFactoryObject * object, const gchar * name, const GValue * value)
Definition at line 806 of file na-factory-object.c.
References NA_BOXED, na_boxed_set_from_value(), na_data_boxed_new(), na_factory_object_get_data_def(), na_ifactory_object_get_data_boxed(), NA_IS_IFACTORY_OBJECT, and name.
na_factory_object_set_from_void()
void na_factory_object_set_from_void (NAIFactoryObject * object, const gchar * name, const void * data)
Definition at line 838 of file na-factory-object.c.
References data, NA_BOXED, na_boxed_set_from_void(), na_data_boxed_new(), na_factory_object_get_data_def(), na_ifactory_object_get_data_boxed(), NA_IS_IFACTORY_OBJECT, and name.
Referenced by na_ifactory_object_set_from_void().
na_factory_object_write_item()
guint na_factory_object_write_item (NAIFactoryObject * object, const NAIFactoryProvider * writer, void * writer_data, GSList ** messages)
Definition at line 663 of file na-factory-object.c.
References na_factory_object_iter_on_boxed(), NA_IIO_PROVIDER_CODE_OK, NA_IIO_PROVIDER_CODE_PROGRAM_ERROR, NA_IS_IFACTORY_OBJECT, and NA_IS_IFACTORY_PROVIDER.
Referenced by na_ifactory_provider_write_item().
Variable Documentation
ifactory_object_finalized
gboolean ifactory_object_finalized extern
ifactory_object_initialized
gboolean ifactory_object_initialized extern