MATE Desktop Environment: na-gtk-utils.h File Reference
na-gtk-utils.h File Reference
#include <gtk/gtk.h>
Macros
#define DEFAULT_HEIGHT 22
#define NA_TOGGLE_DATA_EDITABLE "na-toggle-data-editable"
#define NA_TOGGLE_DATA_BUTTON "na-toggle-data-button"
#define NA_TOGGLE_DATA_HANDLER "na-toggle-data-handler"
#define NA_TOGGLE_DATA_USER_DATA "na-toggle-data-user-data"
Functions
GtkWidget * na_gtk_utils_find_widget_by_name (GtkContainer *container, const gchar *name)
void na_gtk_utils_restore_window_position (GtkWindow *toplevel, const gchar *wsp_name)
void na_gtk_utils_save_window_position (GtkWindow *toplevel, const gchar *wsp_name)
void na_gtk_utils_set_editable (GObject *widget, gboolean editable)
void na_gtk_utils_radio_set_initial_state (GtkRadioButton *button, GCallback toggled_handler, void *user_data, gboolean editable, gboolean sensitive)
void na_gtk_utils_radio_reset_initial_state (GtkRadioButton *button, GCallback toggled_handler)
Macro Definition Documentation
DEFAULT_HEIGHT
#define DEFAULT_HEIGHT 22
Definition at line 67 of file na-gtk-utils.h.
NA_TOGGLE_DATA_BUTTON
#define NA_TOGGLE_DATA_BUTTON "na-toggle-data-button"
Definition at line 70 of file na-gtk-utils.h.
NA_TOGGLE_DATA_EDITABLE
#define NA_TOGGLE_DATA_EDITABLE "na-toggle-data-editable"
Definition at line 69 of file na-gtk-utils.h.
NA_TOGGLE_DATA_HANDLER
#define NA_TOGGLE_DATA_HANDLER "na-toggle-data-handler"
Definition at line 71 of file na-gtk-utils.h.
NA_TOGGLE_DATA_USER_DATA
#define NA_TOGGLE_DATA_USER_DATA "na-toggle-data-user-data"
Definition at line 72 of file na-gtk-utils.h.
Function Documentation
na_gtk_utils_find_widget_by_name()
GtkWidget * na_gtk_utils_find_widget_by_name (GtkContainer * container, const gchar * name)
Definition at line 53 of file na-gtk-utils.c.
References na_gtk_utils_find_widget_by_name(), name, and NULL.
Referenced by base_window_get_widget(), and na_gtk_utils_find_widget_by_name().
na_gtk_utils_radio_reset_initial_state()
void na_gtk_utils_radio_reset_initial_state (GtkRadioButton * button, GCallback handler)
na_gtk_utils_radio_reset_initial_state: @button: the #GtkRadioButton being toggled. @handler: the corresponding "toggled" handler. @data: data associated with the @handler callback.
When clicking on a read-only radio button, this function ensures that the radio button is not modified. It may be called whether the radio button group is editable or not (does nothing if group is actually editable).
Definition at line 401 of file na-gtk-utils.c.
References FALSE, handler, NA_TOGGLE_DATA_BUTTON, NA_TOGGLE_DATA_EDITABLE, NA_TOGGLE_DATA_HANDLER, NA_TOGGLE_DATA_USER_DATA, TRUE, and user_data.
Referenced by base_gtk_utils_radio_reset_initial_state().
na_gtk_utils_radio_set_initial_state()
void na_gtk_utils_radio_set_initial_state (GtkRadioButton * button, GCallback handler, void * user_data, gboolean editable, gboolean sensitive)
na_gtk_utils_radio_set_initial_state: @button: the #GtkRadioButton button which is initially active. @handler: the corresponding "toggled" handler. @user_data: the user data associated to the handler. @editable: whether this radio button group is editable. @sensitive: whether this radio button group is sensitive.
This function should be called for the button which is initially active inside of a radio button group when the radio group may happen to not be editable. This function should be called only once for the radio button group.
It does the following operations:
set the button as active
set other buttons of the radio button group as icactive
set all buttons of radio button group as @editable
The initially active @button, along with its @handler, are recorded as properties of the radio button group (actually as properties of each radio button of the group), so that they can later be used to reset the initial state.
Definition at line 367 of file na-gtk-utils.c.
References FALSE, handler, na_gtk_utils_set_editable(), NA_TOGGLE_DATA_BUTTON, NA_TOGGLE_DATA_EDITABLE, NA_TOGGLE_DATA_HANDLER, NA_TOGGLE_DATA_USER_DATA, TRUE, and user_data.
Referenced by base_gtk_utils_radio_set_initial_state().
na_gtk_utils_restore_window_position()
void na_gtk_utils_restore_window_position (GtkWindow * toplevel, const gchar * wsp_name)
na_gtk_utils_restore_position_window: @toplevel: the #GtkWindow window. @wsp_name: the string which handles the window size and position in user preferences.
Position the specified window on the screen.
A window position is stored as a list of integers "x,y,width,height".
Definition at line 135 of file na-gtk-utils.c.
References DEFAULT_HEIGHT, MAX, MIN, NA_IPREFS_MAIN_WINDOW_WSP, na_settings_get_uint_list(), and NULL.
Referenced by base_gtk_utils_restore_window_position().
na_gtk_utils_save_window_position()
void na_gtk_utils_save_window_position (GtkWindow * toplevel, const gchar * wsp_name)
na_gtk_utils_save_window_position: @toplevel: the #GtkWindow window. @wsp_name: the string which handles the window size and position in user preferences.
Save the size and position of the specified window.
Definition at line 202 of file na-gtk-utils.c.
References na_settings_set_uint_list().
Referenced by base_gtk_utils_save_window_position(), and na_importer_ask_user().
na_gtk_utils_set_editable()
void na_gtk_utils_set_editable (GObject * widget, gboolean editable)
na_gtk_utils_set_editable: @widget: the #GtkWdiget. @editable: whether the @widget is editable or not.
Try to set a visual indication of whether the @widget is editable or not.
Having a GtkWidget should be enough, but we also deal with a GtkTreeViewColumn. So the most-bottom common ancestor is just GObject (since GtkObject having been deprecated in Gtk+-3.0)
Note that using 'sensitivity' property is just a work-around because the two things have distinct semantics:
editable: whether we are allowed to modify the value (is not read-only)
sensitive: whether the value is relevant (has a sense in this context)
Definition at line 291 of file na-gtk-utils.c.
References NULL, and TRUE.
Referenced by base_gtk_utils_set_editable(), and na_gtk_utils_radio_set_initial_state().