MATE Desktop Environment: na-ifactory-object.h File Reference
na-ifactory-object.h File Reference
#include "na-data-def.h"
#include "na-data-boxed.h"
#include "na-ifactory-provider-provider.h"
Classes
struct NAIFactoryObjectInterface
Macros
#define NA_TYPE_IFACTORY_OBJECT (na_ifactory_object_get_type())
#define NA_IFACTORY_OBJECT(instance) (G_TYPE_CHECK_INSTANCE_CAST(instance, NA_TYPE_IFACTORY_OBJECT, NAIFactoryObject))
#define NA_IS_IFACTORY_OBJECT(instance) (G_TYPE_CHECK_INSTANCE_TYPE(instance, NA_TYPE_IFACTORY_OBJECT))
#define NA_IFACTORY_OBJECT_GET_INTERFACE(instance) (G_TYPE_INSTANCE_GET_INTERFACE((instance), NA_TYPE_IFACTORY_OBJECT, NAIFactoryObjectInterface))
Typedefs
typedef struct _NAIFactoryObject NAIFactoryObject
typedef struct _NAIFactoryObjectInterfacePrivate NAIFactoryObjectInterfacePrivate
Functions
GType na_ifactory_object_get_type (void)
NADataBoxed * na_ifactory_object_get_data_boxed (const NAIFactoryObject *object, const gchar *name)
NADataGroup * na_ifactory_object_get_data_groups (const NAIFactoryObject *object)
void * na_ifactory_object_get_as_void (const NAIFactoryObject *object, const gchar *name)
void na_ifactory_object_set_from_void (NAIFactoryObject *object, const gchar *name, const void *data)
Macro Definition Documentation
NA_IFACTORY_OBJECT
#define NA_IFACTORY_OBJECT (instance) (G_TYPE_CHECK_INSTANCE_CAST(instance, NA_TYPE_IFACTORY_OBJECT, NAIFactoryObject))
Definition at line 86 of file na-ifactory-object.h.
NA_IFACTORY_OBJECT_GET_INTERFACE
#define NA_IFACTORY_OBJECT_GET_INTERFACE (instance) (G_TYPE_INSTANCE_GET_INTERFACE((instance), NA_TYPE_IFACTORY_OBJECT, NAIFactoryObjectInterface))
Definition at line 88 of file na-ifactory-object.h.
NA_IS_IFACTORY_OBJECT
#define NA_IS_IFACTORY_OBJECT (instance) (G_TYPE_CHECK_INSTANCE_TYPE(instance, NA_TYPE_IFACTORY_OBJECT))
Definition at line 87 of file na-ifactory-object.h.
NA_TYPE_IFACTORY_OBJECT
#define NA_TYPE_IFACTORY_OBJECT (na_ifactory_object_get_type())
SECTION: ifactory-object @title: NAIFactoryObject @short_description: The NAObjectItem Interface v 1 caja-actions/na-ifactory_object.h
This interface is implemented by NAObjectItem derived objects so that they can take advantage of our data factory management system.
A NAObjectItem derived object which would implement this NAIFactoryObject interface must meet following conditions: <itemizedlist> <listitem>
accept an empty constructor
</listitem> </itemizedlist>
<refsect2> <title>Versions historic</title>
Historic of the versions of the NAIFactoryObject interface</title> <tgroup rowsep="1" colsep="1" align="center" cols="3"> <colspec colname="na-version" > <colspec colname="api-version" > <colspec colname="current" > <row> <entry>&prodname; version</entry> <entry>NAIFactoryObject interface version</entry> <entry></entry> </row> <row> <entry>since 2.30</entry> <entry>1</entry> <entry>current version</entry> </row> </tgroup>
</refsect2>
Definition at line 85 of file na-ifactory-object.h.
Typedef Documentation
NAIFactoryObject
typedef struct _NAIFactoryObject NAIFactoryObject
Definition at line 90 of file na-ifactory-object.h.
NAIFactoryObjectInterfacePrivate
typedef struct _NAIFactoryObjectInterfacePrivate NAIFactoryObjectInterfacePrivate
Definition at line 91 of file na-ifactory-object.h.
Function Documentation
na_ifactory_object_get_as_void()
void * na_ifactory_object_get_as_void (const NAIFactoryObject * object, const gchar * name)
Definition at line 219 of file na-ifactory-object.c.
References na_factory_object_get_as_void(), NA_IS_IFACTORY_OBJECT, name, and NULL.
na_ifactory_object_get_data_boxed()
NADataBoxed * na_ifactory_object_get_data_boxed (const NAIFactoryObject * object, const gchar * name)
Definition at line 156 of file na-ifactory-object.c.
References NA_DATA_BOXED, na_data_boxed_get_data_def(), NA_IFACTORY_OBJECT_PROP_DATA, NA_IS_IFACTORY_OBJECT, name, NADataDef::name, and NULL.
Referenced by na_factory_object_are_equal(), na_factory_object_copy(), na_factory_object_get_as_value(), na_factory_object_get_as_void(), na_factory_object_is_set(), na_factory_object_set_from_value(), and na_factory_object_set_from_void().
na_ifactory_object_get_data_groups()
NADataGroup * na_ifactory_object_get_data_groups (const NAIFactoryObject * object)
na_ifactory_object_get_data_groups: @object: a NAIFactoryObject object.
The returned NADataGroup is owned by the NAIFactoryObject @object, and should not be released by the caller.
Returns: The NADataGroup groups definition, or NULL.
Since: 2.30
Definition at line 189 of file na-ifactory-object.c.
References NA_IFACTORY_OBJECT_GET_INTERFACE, NA_IS_IFACTORY_OBJECT, and NULL.
na_ifactory_object_get_type()
GType na_ifactory_object_get_type (void)
Definition at line 58 of file na-ifactory-object.c.
na_ifactory_object_set_from_void()
void na_ifactory_object_set_from_void (NAIFactoryObject * object, const gchar * name, const void * data)
Definition at line 237 of file na-ifactory-object.c.
References data, na_factory_object_set_from_void(), NA_IS_IFACTORY_OBJECT, and name.