MATE Desktop Environment: na-ifactory-provider.h File Reference
na-ifactory-provider.h File Reference
#include "na-data-boxed.h"
#include "na-ifactory-object.h"
#include "na-ifactory-provider-provider.h"
Classes
struct NAIFactoryProviderInterface
Macros
#define NA_TYPE_IFACTORY_PROVIDER (na_ifactory_provider_get_type())
#define NA_IFACTORY_PROVIDER(instance) (G_TYPE_CHECK_INSTANCE_CAST(instance, NA_TYPE_IFACTORY_PROVIDER, NAIFactoryProvider))
#define NA_IS_IFACTORY_PROVIDER(instance) (G_TYPE_CHECK_INSTANCE_TYPE(instance, NA_TYPE_IFACTORY_PROVIDER))
#define NA_IFACTORY_PROVIDER_GET_INTERFACE(instance) (G_TYPE_INSTANCE_GET_INTERFACE((instance), NA_TYPE_IFACTORY_PROVIDER, NAIFactoryProviderInterface))
Typedefs
typedef struct _NAIFactoryProviderInterfacePrivate NAIFactoryProviderInterfacePrivate
Functions
GType na_ifactory_provider_get_type (void)
void na_ifactory_provider_read_item (const NAIFactoryProvider *reader, void *reader_data, NAIFactoryObject *object, GSList **messages)
guint na_ifactory_provider_write_item (const NAIFactoryProvider *writer, void *writer_data, NAIFactoryObject *object, GSList **messages)
Macro Definition Documentation
NA_IFACTORY_PROVIDER
#define NA_IFACTORY_PROVIDER (instance) (G_TYPE_CHECK_INSTANCE_CAST(instance, NA_TYPE_IFACTORY_PROVIDER, NAIFactoryProvider))
Definition at line 144 of file na-ifactory-provider.h.
NA_IFACTORY_PROVIDER_GET_INTERFACE
#define NA_IFACTORY_PROVIDER_GET_INTERFACE (instance) (G_TYPE_INSTANCE_GET_INTERFACE((instance), NA_TYPE_IFACTORY_PROVIDER, NAIFactoryProviderInterface))
Definition at line 146 of file na-ifactory-provider.h.
NA_IS_IFACTORY_PROVIDER
#define NA_IS_IFACTORY_PROVIDER (instance) (G_TYPE_CHECK_INSTANCE_TYPE(instance, NA_TYPE_IFACTORY_PROVIDER))
Definition at line 145 of file na-ifactory-provider.h.
NA_TYPE_IFACTORY_PROVIDER
#define NA_TYPE_IFACTORY_PROVIDER (na_ifactory_provider_get_type())
SECTION: ifactory-provider @title: NAIFactoryProvider @short_description: The Data Factory Provider Interface v 1 caja-actions/na-ifactory_provider.h
&prodname; has to deal with a relatively great number of elementary datas, reading them from different supports, storing and displaying them, then re-writing these same datas, with several output formats, and so on.
This has rapidly become a pain, if not just a bug generator. Each new data must be described, have a schema to be stored in (historical storage subsystem) MateConf; import and export assistants must be carefully updated to export the new data...
The NAIFactoryProvider aims to simplify and organize all the work which must be done around each and every elementary data. It is based on three main things:
<orderedlist> <listitem> <formalpara> <title>Elementary datas are banalized.</title>
whether they are a string, an integer, a boolean, a simple or double-linked list, each elementary data is encapsuled into a NADataBoxed, small sort of structure (incidentally, which acts almost as the new GLib #GVariant, but too late, guys :)).
</formalpara> </listitem> <listitem> <formalpara> <title>Our objects are de-structured.</title>
Instead of organizing our elementary datas into structures, our objects are just flat lists of NADataBoxed.
</formalpara> </listitem> <listitem> <formalpara> <title>A full, centralized, data dictionary is defined.</title>
Now that our elementary datas are banalized and de-structured, it is simple enough to describe each of these datas with all iss properties in one single, centralized, place.
</formalpara> </listitem> </orderedlist>
Of course, I/O providers are good candidates to be users of this NAIFactoryProvider interface.
Without this interface, each and every I/O provider must, for example when reading an item, have the list of data to be read for each item, then read each individual data, then organize them in a I/O structure.. Each time a new data is added to an object, as e.g. a new condition, then all available I/O providers must be updated: read the data, write the data, then display the data, and so on..
With this NAIFactoryProvider interface, the I/O provider has just to deal with reading/writing elementary types. It does need to know that it will have to read, name, tooltip, description. It just needs to know how to read a string. And while we do not introduce another data type, the I/O provider does not need any maintenance even if we add lot of new data, conditions labels, and so on.
So, this is the interface used by data factory management system for providing serialization/unserialization services. This interface may be implemented by I/O providers which would take advantage of this system.
<refsect2> <title>Versions historic</title>
Historic of the versions of the NAIFactoryProvider interface</title> <tgroup rowsep="1" colsep="1" align="center" cols="3"> <colspec colname="na-version" > <colspec colname="api-version" > <colspec colname="current" > <row> <entry>&prodname; version</entry> <entry>NAIFactoryProvider interface version</entry> <entry></entry> </row> <row> <entry>since 2.30</entry> <entry>1</entry> <entry>current version</entry> </row> </tgroup>
</refsect2>
Definition at line 143 of file na-ifactory-provider.h.
Typedef Documentation
NAIFactoryProviderInterfacePrivate
typedef struct _NAIFactoryProviderInterfacePrivate NAIFactoryProviderInterfacePrivate
Definition at line 148 of file na-ifactory-provider.h.
Function Documentation
na_ifactory_provider_get_type()
GType na_ifactory_provider_get_type (void)
na_ifactory_provider_get_type:
Registers the GType of this interface.
Returns: the NAIFactoryProvider #GType.
Definition at line 67 of file na-ifactory-provider.c.
na_ifactory_provider_read_item()
void na_ifactory_provider_read_item (const NAIFactoryProvider * reader, void * reader_data, NAIFactoryObject * object, GSList ** messages)
na_ifactory_provider_read_item: @reader: the instance which implements this NAIFactoryProvider interface. @reader_data: instance data which will be provided back to the interface methods @object: the NAIFactoryObject object to be unserialilzed. @messages: a pointer to a #GSList list of strings; the implementation may append messages to this list, but shouldn't reinitialize it.
This function is to be called by a NAIIOProvider which would wish read its items. The function takes care of collecting and structuring data, while the callback interface methods NAIFactoryProviderInterface.read_start(), NAIFactoryProviderInterface.read_data() and NAIFactoryProviderInterface.read_done() just have to fill a given NADataBoxed with the ad-hoc data type.
<programlisting> &lcomment;
allocate the object to be read &rcomment; NAObjectItem *item = NA_OBJECT_ITEM(na_object_action_new()); &lcomment;
some data we may need to have access to in callback methods &rcomment; void *data; &lcomment;
now call interface function &rcomment; na_ifactory_provider_read_item(NA_IFACTORY_PROVIDER(provider), data, NA_IFACTORY_OBJECT(item), messages); </programlisting>
Since: 2.30
Definition at line 188 of file na-ifactory-provider.c.
References na_factory_object_read_item(), NA_IS_IFACTORY_OBJECT, and NA_IS_IFACTORY_PROVIDER.
na_ifactory_provider_write_item()
guint na_ifactory_provider_write_item (const NAIFactoryProvider * writer, void * writer_data, NAIFactoryObject * object, GSList ** messages)
na_ifactory_provider_write_item: @writer: the instance which implements this NAIFactoryProvider interface. @writer_data: instance data. @object: the NAIFactoryObject derived object to be serialized. @messages: a pointer to a #GSList list of strings; the implementation may append messages to this list, but shouldn't reinitialize it.
This function is to be called by a NAIIOProvider which would wish write an item. The function takes care of collecting and writing elementary data.
Returns: a NAIIOProvider operation return code.
Since: 2.30
Definition at line 214 of file na-ifactory-provider.c.
References na_factory_object_write_item(), NA_IIO_PROVIDER_CODE_OK, NA_IIO_PROVIDER_CODE_PROGRAM_ERROR, NA_IS_IFACTORY_OBJECT, and NA_IS_IFACTORY_PROVIDER.
Referenced by cadp_writer_iexporter_export_to_buffer(), and cadp_writer_iexporter_export_to_file().