MATE Desktop Environment: na-icontext.c File Reference
na-icontext.c File Reference
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <unistd.h>
#include <glibtop/proclist.h>
#include <glibtop/procstate.h>
#include <libcaja-extension/caja-file-info.h>
#include <api/na-core-utils.h>
#include <api/na-object-api.h>
#include "na-desktop-environment.h"
#include "na-selected-info.h"
#include "na-settings.h"
Functions
GType na_icontext_get_type (void)
gboolean na_icontext_are_equal (const NAIContext *a, const NAIContext *b)
gboolean na_icontext_is_candidate (const NAIContext *context, guint target, GList *selection)
gboolean na_icontext_is_valid (const NAIContext *context)
void na_icontext_check_mimetypes (const NAIContext *context)
void na_icontext_copy (NAIContext *context, const NAIContext *source)
void na_icontext_read_done (NAIContext *context)
void na_icontext_set_scheme (NAIContext *context, const gchar *scheme, gboolean selected)
void na_icontext_set_only_desktop (NAIContext *context, const gchar *desktop, gboolean selected)
void na_icontext_set_not_desktop (NAIContext *context, const gchar *desktop, gboolean selected)
void na_icontext_replace_folder (NAIContext *context, const gchar *old, const gchar *new)
Function Documentation
na_icontext_are_equal()
gboolean na_icontext_are_equal (const NAIContext * a, const NAIContext * b)
na_icontext_are_equal: : the (original) NAIContext context. : the (duplicated) NAIContext context to be checked.
Returns: TRUE if this and are equal, FALSE else.
Since: 3.1
Definition at line 178 of file na-icontext.c.
References b, FALSE, NA_IS_ICONTEXT, and TRUE.
na_icontext_check_mimetypes()
void na_icontext_check_mimetypes (const NAIContext * context)
na_icontext_check_mimetypes: @context: the NAIContext object to be checked.
Check the current list of mimetypes to see if it covers all mimetypes, or all regular files, or something else.
Since: 2.30
Definition at line 288 of file na-icontext.c.
References FALSE, mimetypes, na_core_utils_slist_free(), NA_IS_ICONTEXT, na_object_get_mimetypes, na_object_set_all_mimetypes, and TRUE.
na_icontext_copy()
void na_icontext_copy (NAIContext * context, const NAIContext * source)
na_icontext_copy: @context: the target NAIContext context. @source: the source NAIContext context.
Copy specific data from @source to @context.
Since: 3.1
Definition at line 327 of file na-icontext.c.
na_icontext_get_type()
GType na_icontext_get_type (void)
na_icontext_get_type:
Returns: the #GType type of this interface.
Definition at line 95 of file na-icontext.c.
References type.
na_icontext_is_candidate()
gboolean na_icontext_is_candidate (const NAIContext * context, guint target, GList * selection)
na_icontext_is_candidate: @context: a NAIContext to be checked. @target: the current target. @selection: the currently selected items, as a #GList of NASelectedInfo items.
Determines if the given object may be candidate to be displayed in the Caja context menu, depending of the list of currently selected items.
This function is called by <methodname>build_caja_menus</methodname> plugin function for each item found in NAPivot items list, and, when this an action, for each profile of this action.
Returns: TRUE if this @context succeeds to all tests and is so a valid candidate to be displayed in Caja context menu, FALSE else.
Since: 2.30
Definition at line 214 of file na-icontext.c.
References FALSE, NA_ICONTEXT, and NA_IS_ICONTEXT.
Referenced by main().
na_icontext_is_valid()
gboolean na_icontext_is_valid (const NAIContext * context)
na_icontext_is_valid: @context: the NAIContext to be checked.
Returns: TRUE if this @context is valid, FALSE else.
This function is part of <methodname>NAIDuplicable::check_status</methodname> and is called by NAIDuplicable objects which also implement NAIContext interface. It so doesn't make sense of asking the object for its validity status as it has already been checked before calling the function.
Since: 2.30
Definition at line 260 of file na-icontext.c.
References FALSE, and NA_IS_ICONTEXT.
na_icontext_read_done()
void na_icontext_read_done (NAIContext * context)
na_icontext_read_done: @context: the NAIContext to be prepared.
Prepares the specified NAIContext just after it has been read.
<itemizedlist> <listitem>
This setup an internal flag when mimetypes is like 'all/all' in order to optimize computation time;
</listitem> </itemizedlist>
Since: 2.30
Definition at line 350 of file na-icontext.c.
References na_object_check_mimetypes.
na_icontext_replace_folder()
void na_icontext_replace_folder (NAIContext * context, const gchar * old, const gchar * new)
na_icontext_replace_folder: @context: the NAIContext to be updated. @old: the old uri. @new: the new uri.
Replaces the @old URI by the @new one.
Since: 2.30
Definition at line 435 of file na-icontext.c.
References na_core_utils_slist_free(), na_core_utils_slist_remove_utf8(), NA_IS_ICONTEXT, na_object_get_folders, and na_object_set_folders.
na_icontext_set_not_desktop()
void na_icontext_set_not_desktop (NAIContext * context, const gchar * desktop, gboolean selected)
na_icontext_set_only_desktop: @context: the NAIContext to be updated. @desktop: name of the desktop environment. @selected: whether this @desktop is candidate to this @context.
Sets the status of the @desktop relative to this @context for the NotShowIn list.
Since: 2.30
Definition at line 412 of file na-icontext.c.
References na_core_utils_slist_free(), na_core_utils_slist_setup_element(), NA_IS_ICONTEXT, na_object_get_not_show_in, and na_object_set_not_show_in.
na_icontext_set_only_desktop()
void na_icontext_set_only_desktop (NAIContext * context, const gchar * desktop, gboolean selected)
na_icontext_set_only_desktop: @context: the NAIContext to be updated. @desktop: name of the desktop environment. @selected: whether this @desktop is candidate to this @context.
Sets the status of the @desktop relative to this @context for the OnlyShowIn list.
Since: 2.30
Definition at line 389 of file na-icontext.c.
References na_core_utils_slist_free(), na_core_utils_slist_setup_element(), NA_IS_ICONTEXT, na_object_get_only_show_in, and na_object_set_only_show_in.
na_icontext_set_scheme()
void na_icontext_set_scheme (NAIContext * context, const gchar * scheme, gboolean selected)
na_icontext_set_scheme: @context: the NAIContext to be updated. @scheme: name of the scheme. @selected: whether this scheme is candidate to this @context.
Sets the status of a @scheme relative to this @context.
Since: 2.30
Definition at line 366 of file na-icontext.c.
References na_core_utils_slist_free(), na_core_utils_slist_setup_element(), NA_IS_ICONTEXT, na_object_get_schemes, and na_object_set_schemes.