MATE Desktop Environment: na-iprefs.c File Reference
na-iprefs.c File Reference
#include <string.h>
#include <api/na-core-utils.h>
#include "na-importer.h"
#include "na-iprefs.h"
#include "na-settings.h"
Macros
#define ORDER_ALPHA_ASC_STR "AscendingOrder"
#define ORDER_ALPHA_DESC_STR "DescendingOrder"
#define ORDER_MANUAL_STR "ManualOrder"
Functions
guint na_iprefs_get_order_mode (gboolean *mandatory)
guint na_iprefs_get_order_mode_by_label (const gchar *label)
void na_iprefs_set_order_mode (guint mode)
guint na_iprefs_get_tabs_pos (gboolean *mandatory)
void na_iprefs_set_tabs_pos (guint position)
gboolean na_iprefs_write_level_zero (const GList *items, GSList **messages)
Macro Definition Documentation
ORDER_ALPHA_ASC_STR
#define ORDER_ALPHA_ASC_STR "AscendingOrder"
Definition at line 51 of file na-iprefs.c.
ORDER_ALPHA_DESC_STR
#define ORDER_ALPHA_DESC_STR "DescendingOrder"
Definition at line 52 of file na-iprefs.c.
ORDER_MANUAL_STR
#define ORDER_MANUAL_STR "ManualOrder"
Definition at line 53 of file na-iprefs.c.
Function Documentation
na_iprefs_get_order_mode()
guint na_iprefs_get_order_mode (gboolean * mandatory)
Definition at line 81 of file na-iprefs.c.
References NA_IPREFS_ITEMS_LIST_ORDER_MODE, na_settings_get_string(), and NULL.
Referenced by cact_tree_model_new(), and na_io_provider_load_items().
na_iprefs_get_order_mode_by_label()
guint na_iprefs_get_order_mode_by_label (const gchar * label)
Definition at line 104 of file na-iprefs.c.
References label.
na_iprefs_get_tabs_pos()
guint na_iprefs_get_tabs_pos (gboolean * mandatory)
Definition at line 137 of file na-iprefs.c.
References NA_IPREFS_MAIN_TABS_POS, na_settings_get_string(), and NULL.
na_iprefs_set_order_mode()
void na_iprefs_set_order_mode (guint mode)
Definition at line 121 of file na-iprefs.c.
References NA_IPREFS_ITEMS_LIST_ORDER_MODE, and na_settings_set_string().
na_iprefs_set_tabs_pos()
void na_iprefs_set_tabs_pos (guint position)
Definition at line 156 of file na-iprefs.c.
References NA_IPREFS_MAIN_TABS_POS, and na_settings_set_string().
na_iprefs_write_level_zero()
gboolean na_iprefs_write_level_zero (const GList * items, GSList ** messages)
Definition at line 184 of file na-iprefs.c.
References FALSE, id, na_core_utils_slist_free(), NA_IPREFS_ITEMS_LEVEL_ZERO_ORDER, na_object_get_id, na_settings_set_string_list(), and NULL.
Referenced by cact_menubar_file_save_items(), and na_io_provider_load_items().