MATE Desktop Environment: na-object-menu.h File Reference
na-object-menu.h File Reference
#include "na-object-item.h"
Classes
struct NAObjectMenu
struct NAObjectMenuClass
Macros
#define NA_TYPE_OBJECT_MENU (na_object_menu_get_type())
#define NA_OBJECT_MENU(object) (G_TYPE_CHECK_INSTANCE_CAST(object, NA_TYPE_OBJECT_MENU, NAObjectMenu))
#define NA_OBJECT_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, NA_TYPE_OBJECT_MENU, NAObjectMenuClass))
#define NA_IS_OBJECT_MENU(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, NA_TYPE_OBJECT_MENU))
#define NA_IS_OBJECT_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), NA_TYPE_OBJECT_MENU))
#define NA_OBJECT_MENU_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), NA_TYPE_OBJECT_MENU, NAObjectMenuClass))
Typedefs
typedef struct _NAObjectMenuPrivate NAObjectMenuPrivate
typedef struct _NAObjectMenuClassPrivate NAObjectMenuClassPrivate
Functions
GType na_object_menu_get_type (void)
NAObjectMenu * na_object_menu_new (void)
NAObjectMenu * na_object_menu_new_with_defaults (void)
Macro Definition Documentation
NA_IS_OBJECT_MENU
#define NA_IS_OBJECT_MENU (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, NA_TYPE_OBJECT_MENU))
Definition at line 47 of file na-object-menu.h.
NA_IS_OBJECT_MENU_CLASS
#define NA_IS_OBJECT_MENU_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), NA_TYPE_OBJECT_MENU))
Definition at line 48 of file na-object-menu.h.
NA_OBJECT_MENU
#define NA_OBJECT_MENU (object) (G_TYPE_CHECK_INSTANCE_CAST(object, NA_TYPE_OBJECT_MENU, NAObjectMenu))
Definition at line 45 of file na-object-menu.h.
NA_OBJECT_MENU_CLASS
#define NA_OBJECT_MENU_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, NA_TYPE_OBJECT_MENU, NAObjectMenuClass))
Definition at line 46 of file na-object-menu.h.
NA_OBJECT_MENU_GET_CLASS
#define NA_OBJECT_MENU_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), NA_TYPE_OBJECT_MENU, NAObjectMenuClass))
Definition at line 49 of file na-object-menu.h.
NA_TYPE_OBJECT_MENU
#define NA_TYPE_OBJECT_MENU (na_object_menu_get_type())
SECTION: object-menu @title: NAObjectMenu @short_description: The Menu Class Definition caja-actions/na-object-menu.h
Definition at line 44 of file na-object-menu.h.
Typedef Documentation
NAObjectMenuClassPrivate
typedef struct _NAObjectMenuClassPrivate NAObjectMenuClassPrivate
Definition at line 60 of file na-object-menu.h.
NAObjectMenuPrivate
typedef struct _NAObjectMenuPrivate NAObjectMenuPrivate
Definition at line 51 of file na-object-menu.h.
Function Documentation
na_object_menu_get_type()
GType na_object_menu_get_type (void)
Definition at line 84 of file na-object-menu.c.
na_object_menu_new()
NAObjectMenu * na_object_menu_new (void)
na_object_menu_new:
Allocates a new NAObjectMenu object.
Returns: the newly allocated NAObjectMenu object.
Since: 2.30
Definition at line 350 of file na-object-menu.c.
References NA_TYPE_OBJECT_MENU, and NULL.
Referenced by na_object_menu_new_with_defaults().
na_object_menu_new_with_defaults()
NAObjectMenu * na_object_menu_new_with_defaults (void)
na_object_menu_new_with_defaults:
Allocates a new NAObjectMenu object, and setup default values.
Returns: the newly allocated NAObjectMenu object.
Since: 2.30
Definition at line 369 of file na-object-menu.c.
References na_factory_object_set_defaults(), NA_IFACTORY_OBJECT, na_object_menu_new(), na_object_set_label, na_object_set_new_id, NEW_CAJA_MENU, and NULL.
Referenced by cact_menubar_file_on_new_menu().