MATE Desktop Environment: na-object-item.h File Reference
na-object-item.h File Reference
#include "na-object-id.h"
Classes
struct NAObjectItem
struct NAObjectItemClass
Macros
#define NA_TYPE_OBJECT_ITEM (na_object_item_get_type())
#define NA_OBJECT_ITEM(object) (G_TYPE_CHECK_INSTANCE_CAST(object, NA_TYPE_OBJECT_ITEM, NAObjectItem))
#define NA_OBJECT_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, NA_TYPE_OBJECT_ITEM, NAObjectItemClass))
#define NA_IS_OBJECT_ITEM(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, NA_TYPE_OBJECT_ITEM))
#define NA_IS_OBJECT_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), NA_TYPE_OBJECT_ITEM))
#define NA_OBJECT_ITEM_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), NA_TYPE_OBJECT_ITEM, NAObjectItemClass))
Typedefs
typedef struct _NAObjectItemPrivate NAObjectItemPrivate
typedef struct _NAObjectItemClassPrivate NAObjectItemClassPrivate
Enumerations
enum NAItemTarget { ITEM_TARGET_SELECTION = 1 , ITEM_TARGET_LOCATION , ITEM_TARGET_TOOLBAR , ITEM_TARGET_ANY }
Functions
GType na_object_item_get_type (void)
NAObjectId * na_object_item_get_item (const NAObjectItem *item, const gchar *id)
gint na_object_item_get_position (const NAObjectItem *item, const NAObjectId *child)
void na_object_item_append_item (NAObjectItem *item, const NAObjectId *child)
void na_object_item_insert_at (NAObjectItem *item, const NAObjectId *child, gint pos)
void na_object_item_insert_item (NAObjectItem *item, const NAObjectId *child, const NAObjectId *before)
void na_object_item_remove_item (NAObjectItem *item, const NAObjectId *child)
guint na_object_item_get_items_count (const NAObjectItem *item)
void na_object_item_count_items (GList *items, gint *menus, gint *actions, gint *profiles, gboolean recurse)
GList * na_object_item_copyref_items (GList *items)
GList * na_object_item_free_items (GList *items)
void na_object_item_deals_with_version (NAObjectItem *item)
void na_object_item_rebuild_children_slist (NAObjectItem *item)
gboolean na_object_item_is_finally_writable (const NAObjectItem *item, guint *reason)
void na_object_item_set_writability_status (NAObjectItem *item, gboolean writable, guint reason)
Macro Definition Documentation
NA_IS_OBJECT_ITEM
#define NA_IS_OBJECT_ITEM (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, NA_TYPE_OBJECT_ITEM))
Definition at line 50 of file na-object-item.h.
NA_IS_OBJECT_ITEM_CLASS
#define NA_IS_OBJECT_ITEM_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), NA_TYPE_OBJECT_ITEM))
Definition at line 51 of file na-object-item.h.
NA_OBJECT_ITEM
#define NA_OBJECT_ITEM (object) (G_TYPE_CHECK_INSTANCE_CAST(object, NA_TYPE_OBJECT_ITEM, NAObjectItem))
Definition at line 48 of file na-object-item.h.
NA_OBJECT_ITEM_CLASS
#define NA_OBJECT_ITEM_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, NA_TYPE_OBJECT_ITEM, NAObjectItemClass))
Definition at line 49 of file na-object-item.h.
NA_OBJECT_ITEM_GET_CLASS
#define NA_OBJECT_ITEM_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), NA_TYPE_OBJECT_ITEM, NAObjectItemClass))
Definition at line 52 of file na-object-item.h.
NA_TYPE_OBJECT_ITEM
#define NA_TYPE_OBJECT_ITEM (na_object_item_get_type())
SECTION: object-item @title: NAObjectItem @short_description: The Object Item Base Class Definition caja-actions/na-object-item.h
This is a pure virtual class, i.e. not an instantiatable one, but serves as the base class for NAObjectAction and NAObjectMenu.
Definition at line 47 of file na-object-item.h.
Typedef Documentation
NAObjectItemClassPrivate
typedef struct _NAObjectItemClassPrivate NAObjectItemClassPrivate
Definition at line 63 of file na-object-item.h.
NAObjectItemPrivate
typedef struct _NAObjectItemPrivate NAObjectItemPrivate
Definition at line 54 of file na-object-item.h.
Enumeration Type Documentation
NAItemTarget
enum NAItemTarget
NAItemTarget: @ITEM_TARGET_SELECTION: when targeting the selection context menu. @ITEM_TARGET_LOCATION: when targeting the background context menu. @ITEM_TARGET_TOOLBAR: when targeting the toolbar. @ITEM_TARGET_ANY: a wilcard target defined in order to be able to activate an action from a keyboard shortcut, while keeping this same action hidden from the UI.
The NAItemTarget mode is Caja-driven. It determines in which part of the Caja UI our actions will be displayed.
Enumerator
ITEM_TARGET_SELECTION
ITEM_TARGET_LOCATION
ITEM_TARGET_TOOLBAR
ITEM_TARGET_ANY
Definition at line 84 of file na-object-item.h.
Function Documentation
na_object_item_append_item()
void na_object_item_append_item (NAObjectItem * item, const NAObjectId * child)
na_object_item_append_item: @item: the NAObjectItem to which add the subitem. @child: a NAObjectId to be added to list of subitems.
Appends a new @child to the list of subitems of @item, and setup the parent pointer of the child to its new parent.
Doesn't modify the reference count on @object.
Since: 2.30
Definition at line 489 of file na-object-item.c.
References item, NA_IS_OBJECT_ID, NA_IS_OBJECT_ITEM, na_object_get_items, na_object_set_items, and na_object_set_parent.
na_object_item_copyref_items()
GList * na_object_item_copyref_items (GList * items)
na_object_item_copyref_items: @items: a list of NAObject -derived items.
Creates a copy of the provided list, recursively incrementing the reference count of NAObjects.
Returns: the new list, which should be na_object_free_items() by the caller.
Since: 3.1
Definition at line 719 of file na-object-item.c.
References na_object_object_ref(), and NULL.
na_object_item_count_items()
void na_object_item_count_items (GList * items, gint * menus, gint * actions, gint * profiles, gboolean recurse)
na_object_item_count_items: @items: a list if NAObject -derived to be counted. @menus: will be set to the count of menus. @actions: will be set to the count of actions. @profiles: will be set to the count of profiles. @recurse: whether to recursively count all items, or only those in level zero of the list.
Returns: the count the numbers of items if the provided list.
As this function is recursive, the counters should be initialized by the caller before calling it.
Since: 2.30
Definition at line 671 of file na-object-item.c.
Referenced by cact_clipboard_primary_set().
na_object_item_deals_with_version()
void na_object_item_deals_with_version (NAObjectItem * item)
na_object_item_deals_with_version: @item: this NAObjectItem -derived object.
Just after the @item has been read from NAIFactoryProvider, setup the version. This is needed because some conversions may occur in this object.
Note that there is only some 2.x versions where the version string was not systematically written. If @item has been read from a .desktop file, then iversion is already set to (at least) 3.
Since: 2.30
Definition at line 772 of file na-object-item.c.
References item, NA_IS_OBJECT_ITEM, na_object_get_iversion, na_object_get_version, and na_object_set_iversion.
na_object_item_free_items()
GList * na_object_item_free_items (GList * items)
na_object_item_free_items: @items: a list of NAObject -derived items.
Free the items list.
Returns: a NULL pointer.
Since: 3.1
Definition at line 745 of file na-object-item.c.
References na_object_object_unref(), and NULL.
na_object_item_get_item()
NAObjectId * na_object_item_get_item (const NAObjectItem * item, const gchar * id)
na_object_item_get_item: @item: the NAObjectItem from which we want retrieve a subitem. @id: the id of the searched subitem.
Returns: a pointer to the NAObjectId -derived child with the required id.
The returned NAObjectId is owned by the @item object ; the caller should not try to g_free() nor g_object_unref() it.
Since: 2.30
Definition at line 419 of file na-object-item.c.
References item, NA_IS_OBJECT_ITEM, na_object_get_id, na_object_get_items, NA_OBJECT_ID, and NULL.
na_object_item_get_items_count()
guint na_object_item_get_items_count (const NAObjectItem * item)
na_object_item_get_items_count: @item: the NAObjectItem from which we want a count of subitems.
Returns: the count of subitems of @item.
Since: 2.30
Definition at line 637 of file na-object-item.c.
References item, NA_IS_OBJECT_ITEM, and na_object_get_items.
na_object_item_get_position()
gint na_object_item_get_position (const NAObjectItem * item, const NAObjectId * child)
na_object_item_get_position: @item: this NAObjectItem object. @child: a NAObjectId -derived child.
Returns: the position of @child in the subitems list of @item, starting from zero, or -1 if not found.
Since: 2.30
Definition at line 455 of file na-object-item.c.
References item, NA_IS_OBJECT_ID, NA_IS_OBJECT_ITEM, and na_object_get_items.
na_object_item_get_type()
GType na_object_item_get_type (void)
Definition at line 82 of file na-object-item.c.
na_object_item_insert_at()
void na_object_item_insert_at (NAObjectItem * item, const NAObjectId * child, gint pos)
na_object_item_insert_at: @item: the NAObjectItem in which add the subitem. @child: a NAObjectId -derived to be inserted in the list of subitems. @pos: the position at which the @child should be inserted.
Inserts a new @child in the list of subitems of @item.
Doesn't modify the reference count on @child.
Since: 2.30
Definition at line 522 of file na-object-item.c.
References item, NA_IS_OBJECT_ID, NA_IS_OBJECT_ITEM, na_object_append_item, na_object_get_items, and na_object_set_items.
na_object_item_insert_item()
void na_object_item_insert_item (NAObjectItem * item, const NAObjectId * child, const NAObjectId * before)
na_object_item_insert_item: @item: the NAObjectItem to which add the subitem. @child: a NAObjectId to be inserted in the list of subitems. @before: the NAObjectId before which the @child should be inserted.
Inserts a new @child in the list of subitems of @item.
Doesn't modify the reference count on @child.
Since: 2.30
Definition at line 562 of file na-object-item.c.
References item, NA_IS_OBJECT_ID, NA_IS_OBJECT_ITEM, na_object_get_items, na_object_set_items, and NULL.
na_object_item_is_finally_writable()
gboolean na_object_item_is_finally_writable (const NAObjectItem * item, guint * reason)
na_object_item_is_finally_writable: @item: this NAObjectItem -derived object. @reason: if not NULL, a pointer to a guint which will hold the reason code.
Returns: the writability status of the @item.
Since: 3.1
Definition at line 883 of file na-object-item.c.
References FALSE, item, NA_IIO_PROVIDER_STATUS_UNDETERMINED, and NA_IS_OBJECT_ITEM.
na_object_item_rebuild_children_slist()
void na_object_item_rebuild_children_slist (NAObjectItem * item)
na_object_item_rebuild_children_slist: @item: this NAObjectItem -derived object.
Rebuild the string list of children.
Since: 2.30
Definition at line 808 of file na-object-item.c.
References item, na_core_utils_slist_free(), na_object_set_items_slist, and NULL.
na_object_item_remove_item()
void na_object_item_remove_item (NAObjectItem * item, const NAObjectId * child)
na_object_item_remove_item: @item: the NAObjectItem from which the subitem must be removed. @child: a NAObjectId -derived to be removed from the list of subitems.
Removes a @child from the list of subitems of @item.
Doesn't modify the reference count on @child.
Since: 2.30
Definition at line 605 of file na-object-item.c.
References item, NA_IS_OBJECT_ID, NA_IS_OBJECT_ITEM, na_object_get_items, and na_object_set_items.
na_object_item_set_writability_status()
void na_object_item_set_writability_status (NAObjectItem * item, gboolean writable, guint reason)
na_object_item_set_writability_status: @item: this NAObjectItem -derived object. @writable: whether the item is finally writable. @reason: the reason code.
Set the writability status of the @item.
Since: 3.1
Definition at line 916 of file na-object-item.c.
References item, and NA_IS_OBJECT_ITEM.