MATE Desktop Environment: na-object.c File Reference
na-object.c File Reference
#include <api/na-object-api.h>
#include "na-factory-object.h"
Functions
GType na_object_object_get_type (void)
void na_object_object_check_status_rec (const NAObject *object)
void na_object_object_dump (const NAObject *object)
void na_object_object_dump_norec (const NAObject *object)
void na_object_object_dump_tree (GList *tree)
void na_object_object_reset_origin (NAObject *object, const NAObject *origin)
NAObject * na_object_object_ref (NAObject *object)
void na_object_object_unref (NAObject *object)
void na_object_object_debug_invalid (const NAObject *object, const gchar *reason)
Function Documentation
na_object_object_check_status_rec()
void na_object_object_check_status_rec (const NAObject * object)
na_object_object_check_status_rec: @object: the NAObject -derived object to be checked.
Recursively checks for the edition status of @object and its children (if any).
Internally set some properties which may be requested later. This two-steps check-request let us optimize some work in the UI.
<literallayout> na_object_object_check_status_rec(object) +- na_iduplicable_check_status(object) +- get_origin(object) +- modified_status = v_are_equal(origin, object) | +-> interface <structfield>NAObjectClass::are_equal</structfield> | which happens to be iduplicable_are_equal(a, b) | +- v_are_equal(a, b) | +- NAObjectAction::are_equal() | +- na_factory_object_are_equal() | +- check NAObjectActionPrivate data | +- call parent class | +- NAObjectItem::are_equal() | +- check NAObjectItemPrivate data | +- call parent class | +- NAObjectId::are_equal() | +- valid_status = v_is_valid(object) -> interface <structfield>NAObjectClass::is_valid</structfield> </literallayout>
Note that the recursivity is managed here, so that we can be sure that edition status of children is actually checked before those of the parent.
<formalpara> <title> As of 3.1.0: </title>
<itemizedlist> <listitem>
when the modification status of a NAObjectProfile changes, then its NAObjectAction parent is rechecked;
</listitem> <listitem>
when the validity status of an object is changed, then its parent is also rechecked.
</listitem> </itemizedlist>
</formalpara>
Since: 2.30
Definition at line 378 of file na-object.c.
References NA_IS_OBJECT, na_object_is_modified, na_object_is_valid, and NAObject::private.
na_object_object_debug_invalid()
void na_object_object_debug_invalid (const NAObject * object, const gchar * reason)
na_object_object_debug_invalid: @object: the NAObject -derived object which is invalid. @reason: the reason.
Dump the object with the invalidity reason.
Since: 2.30
Definition at line 740 of file na-object.c.
na_object_object_dump()
void na_object_object_dump (const NAObject * object)
na_object_object_dump: @object: the NAObject -derived object to be dumped.
Dumps via g_debug() the actual content of the object.
The recursivity is dealt with here because, if we would let NAObjectItem do this, the dump of NAObjectItem -derived object would be splitted, children being inserted inside.
na_object_dump() doesn't modify the reference count of the dumped object.
Since: 2.30
Definition at line 479 of file na-object.c.
References NA_IS_OBJECT, NA_IS_OBJECT_ITEM, na_object_dump, na_object_dump_norec, na_object_get_items, and NAObject::private.
na_object_object_dump_norec()
void na_object_object_dump_norec (const NAObject * object)
na_object_object_dump_norec: @object: the NAObject -derived object to be dumped.
Dumps via g_debug the actual content of the object.
This function is not recursive.
Since: 2.30
Definition at line 510 of file na-object.c.
References NA_IS_OBJECT, NA_OBJECT_GET_CLASS, and NAObject::private.
na_object_object_dump_tree()
void na_object_object_dump_tree (GList * tree)
na_object_object_dump_tree: @tree: a hierarchical list of NAObject -derived objects.
Outputs a brief, hierarchical dump of the provided list.
Since: 2.30
Definition at line 530 of file na-object.c.
na_object_object_get_type()
GType na_object_object_get_type (void)
Definition at line 73 of file na-object.c.
na_object_object_ref()
NAObject * na_object_object_ref (NAObject * object)
na_object_object_ref: @object: a NAObject -derived object.
Recursively ref the @object and all its children, incrementing their reference_count by 1.
Returns: a reference on the @object.
Since: 2.30
Definition at line 614 of file na-object.c.
References NA_IS_OBJECT, NA_IS_OBJECT_ITEM, na_object_get_items, na_object_object_ref(), NULL, and NAObject::private.
Referenced by na_object_item_copyref_items(), and na_object_object_ref().
na_object_object_reset_origin()
void na_object_object_reset_origin (NAObject * object, const NAObject * origin)
na_object_object_reset_origin: @object: a NAObject -derived object. @origin: must be a duplication of @object.
Recursively reset origin of @object and its children to @origin (and its children), so that @origin appears as the actual origin of @object.
The origin of @origin itself is set to NULL.
This only works if @origin has just been duplicated from @object, and thus we do not have to check if children lists are equal.
Since: 2.30
Definition at line 580 of file na-object.c.
References NA_IDUPLICABLE, na_iduplicable_set_origin(), NA_IS_OBJECT, na_object_get_items, na_object_reset_origin, NULL, and NAObject::private.
na_object_object_unref()
void na_object_object_unref (NAObject * object)
na_object_object_unref: @object: a NAObject -derived object.
Recursively unref the @object and all its children, decrementing their reference_count by 1.
Note that we may want to free a copy+ref of a list of items whichy have had already disposed (which is probably a bug somewhere). So first test is the object is still alive.
Since: 2.30
Definition at line 648 of file na-object.c.
References NA_IS_OBJECT, NA_IS_OBJECT_ITEM, na_object_get_items, na_object_object_unref(), NULL, and NAObject::private.
Referenced by na_object_item_free_items(), and na_object_object_unref().