MATE Desktop Environment: na-pivot.c File Reference
na-pivot.c File Reference
#include <string.h>
#include <api/na-core-utils.h>
#include <api/na-timeout.h>
#include "na-io-provider.h"
#include "na-module.h"
#include "na-pivot.h"
Enumerations
enum { PRIVOT_PROP_0 , PIVOT_PROP_LOADABLE_ID , PIVOT_PROP_TREE_ID , PIVOT_PROP_N }
enum { ITEMS_CHANGED , LAST_SIGNAL }
Functions
GType na_pivot_get_type (void)
NAPivot * na_pivot_new (void)
void na_pivot_dump (const NAPivot *pivot)
GList * na_pivot_get_providers (const NAPivot *pivot, GType type)
void na_pivot_free_providers (GList *providers)
NAObjectItem * na_pivot_get_item (const NAPivot *pivot, const gchar *id)
GList * na_pivot_get_items (const NAPivot *pivot)
void na_pivot_load_items (NAPivot *pivot)
void na_pivot_set_new_items (NAPivot *pivot, GList *items)
void na_pivot_on_item_changed_handler (NAIIOProvider *provider, NAPivot *pivot)
void na_pivot_set_loadable (NAPivot *pivot, guint loadable)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PRIVOT_PROP_0
PIVOT_PROP_LOADABLE_ID
PIVOT_PROP_TREE_ID
PIVOT_PROP_N
Definition at line 71 of file na-pivot.c.
anonymous enum
anonymous enum
Enumerator
ITEMS_CHANGED
LAST_SIGNAL
Definition at line 83 of file na-pivot.c.
Function Documentation
na_pivot_dump()
void na_pivot_dump (const NAPivot * pivot)
Definition at line 405 of file na-pivot.c.
References NAPivot::private.
na_pivot_free_providers()
void na_pivot_free_providers (GList * providers)
Definition at line 463 of file na-pivot.c.
References na_module_free_extensions_list().
Referenced by na_exporter_get_formats(), and na_importer_import_from_uris().
na_pivot_get_item()
NAObjectItem * na_pivot_get_item (const NAPivot * pivot, const gchar * id)
Definition at line 486 of file na-pivot.c.
References NA_IS_PIVOT, NULL, and NAPivot::private.
Referenced by na_updater_insert_item().
na_pivot_get_items()
GList * na_pivot_get_items (const NAPivot * pivot)
Definition at line 537 of file na-pivot.c.
References NA_IS_PIVOT, NULL, and NAPivot::private.
Referenced by na_updater_load_items().
na_pivot_get_providers()
GList * na_pivot_get_providers (const NAPivot * pivot, GType type)
Definition at line 438 of file na-pivot.c.
References NA_IS_PIVOT, na_module_get_extensions_for_type(), NULL, NAPivot::private, and type.
Referenced by na_exporter_get_formats(), and na_importer_import_from_uris().
na_pivot_get_type()
GType na_pivot_get_type (void)
Definition at line 107 of file na-pivot.c.
na_pivot_load_items()
void na_pivot_load_items (NAPivot * pivot)
Definition at line 560 of file na-pivot.c.
References na_core_utils_slist_free(), na_io_provider_load_items(), NA_IS_PIVOT, na_object_free_items, NULL, and NAPivot::private.
Referenced by main(), and na_updater_load_items().
na_pivot_new()
NAPivot * na_pivot_new (void)
Definition at line 386 of file na-pivot.c.
References NA_TYPE_PIVOT, and NULL.
Referenced by main().
na_pivot_on_item_changed_handler()
void na_pivot_on_item_changed_handler (NAIIOProvider * provider, NAPivot * pivot)
Definition at line 624 of file na-pivot.c.
References NA_IS_IIO_PROVIDER, NA_IS_PIVOT, na_timeout_event(), and NAPivot::private.
na_pivot_set_loadable()
void na_pivot_set_loadable (NAPivot * pivot, guint loadable)
Definition at line 663 of file na-pivot.c.
References NA_IS_PIVOT, and NAPivot::private.
Referenced by main().
na_pivot_set_new_items()
void na_pivot_set_new_items (NAPivot * pivot, GList * items)
Definition at line 592 of file na-pivot.c.
References NA_IS_PIVOT, na_object_free_items, and NAPivot::private.
Referenced by cact_menubar_file_save_items().