MATE Desktop Environment: na-settings.c File Reference
na-settings.c File Reference
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <api/na-boxed.h>
#include <api/na-data-types.h>
#include <api/na-core-utils.h>
#include <api/na-timeout.h>
#include "na-settings.h"
#include "na-marshal.h"
Macros
#define NA_SETTINGS_TYPE (settings_get_type())
#define NA_SETTINGS(object) (G_TYPE_CHECK_INSTANCE_CAST(object, NA_SETTINGS_TYPE, NASettings))
#define NA_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, NA_SETTINGS_TYPE, NASettingsClass))
#define NA_IS_SETTINGS(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, NA_SETTINGS_TYPE))
#define NA_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), NA_SETTINGS_TYPE))
#define NA_SETTINGS_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), NA_SETTINGS_TYPE, NASettingsClass))
#define GROUP_CACT "cact"
#define GROUP_RUNTIME "runtime"
Typedefs
typedef struct _NASettingsPrivate NASettingsPrivate
typedef struct _NASettingsClassPrivate NASettingsClassPrivate
Enumerations
enum { KEY_CHANGED , LAST_SIGNAL }
Functions
void na_settings_free (void)
void na_settings_register_key_callback (const gchar *key, GCallback callback, gpointer user_data)
gboolean na_settings_get_boolean (const gchar *key, gboolean *found, gboolean *mandatory)
gboolean na_settings_get_boolean_ex (const gchar *group, const gchar *key, gboolean *found, gboolean *mandatory)
gchar * na_settings_get_string (const gchar *key, gboolean *found, gboolean *mandatory)
GSList * na_settings_get_string_list (const gchar *key, gboolean *found, gboolean *mandatory)
guint na_settings_get_uint (const gchar *key, gboolean *found, gboolean *mandatory)
GList * na_settings_get_uint_list (const gchar *key, gboolean *found, gboolean *mandatory)
gboolean na_settings_set_boolean (const gchar *key, gboolean value)
gboolean na_settings_set_boolean_ex (const gchar *group, const gchar *key, gboolean value)
gboolean na_settings_set_string (const gchar *key, const gchar *value)
gboolean na_settings_set_string_ex (const gchar *group, const gchar *key, const gchar *value)
gboolean na_settings_set_string_list (const gchar *key, const GSList *value)
gboolean na_settings_set_int_ex (const gchar *group, const gchar *key, int value)
gboolean na_settings_set_uint (const gchar *key, guint value)
gboolean na_settings_set_uint_list (const gchar *key, const GList *value)
GSList * na_settings_get_groups (void)
Macro Definition Documentation
GROUP_CACT
#define GROUP_CACT "cact"
Definition at line 121 of file na-settings.c.
GROUP_RUNTIME
#define GROUP_RUNTIME "runtime"
Definition at line 122 of file na-settings.c.
NA_IS_SETTINGS
#define NA_IS_SETTINGS (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, NA_SETTINGS_TYPE))
Definition at line 50 of file na-settings.c.
NA_IS_SETTINGS_CLASS
#define NA_IS_SETTINGS_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), NA_SETTINGS_TYPE))
Definition at line 51 of file na-settings.c.
NA_SETTINGS
#define NA_SETTINGS (object) (G_TYPE_CHECK_INSTANCE_CAST(object, NA_SETTINGS_TYPE, NASettings))
Definition at line 48 of file na-settings.c.
NA_SETTINGS_CLASS
#define NA_SETTINGS_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, NA_SETTINGS_TYPE, NASettingsClass))
Definition at line 49 of file na-settings.c.
NA_SETTINGS_GET_CLASS
#define NA_SETTINGS_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), NA_SETTINGS_TYPE, NASettingsClass))
Definition at line 52 of file na-settings.c.
NA_SETTINGS_TYPE
#define NA_SETTINGS_TYPE (settings_get_type())
Definition at line 47 of file na-settings.c.
Typedef Documentation
NASettingsClassPrivate
typedef struct _NASettingsClassPrivate NASettingsClassPrivate
Definition at line 63 of file na-settings.c.
NASettingsPrivate
typedef struct _NASettingsPrivate NASettingsPrivate
Definition at line 54 of file na-settings.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
KEY_CHANGED
LAST_SIGNAL
Definition at line 208 of file na-settings.c.
Function Documentation
na_settings_free()
void na_settings_free (void)
na_settings_free:
Definition at line 445 of file na-settings.c.
References NULL.
na_settings_get_boolean()
gboolean na_settings_get_boolean (const gchar * key, gboolean * found, gboolean * mandatory)
na_settings_get_boolean: @key: the key whose value is to be returned. @found: if not NULL, a pointer to a gboolean in which we will store whether the searched @key has been found (TRUE), or if the returned value comes from default (FALSE). @mandatory: if not NULL, a pointer to a gboolean in which we will store whether the returned value has been read from mandatory preferences (TRUE), or from the user preferences (FALSE). When the @key has not been found, @mandatory is set to FALSE.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: the value of the key, of its default value if not found.
Since: 3.1
Definition at line 499 of file na-settings.c.
References key, na_settings_get_boolean_ex(), and NULL.
Referenced by cact_assistant_export_run(), cact_assistant_import_run(), cact_export_ask_user(), cact_preferences_editor_run(), and na_updater_should_pasted_be_relabeled().
na_settings_get_boolean_ex()
gboolean na_settings_get_boolean_ex (const gchar * group, const gchar * key, gboolean * found, gboolean * mandatory)
na_settings_get_boolean_ex: @group: the group where the @key is to be searched for. May be NULL. @key: the key whose value is to be returned. @found: if not NULL, a pointer to a gboolean in which we will store whether the searched @key has been found (TRUE), or if the returned value comes from default (FALSE). @mandatory: if not NULL, a pointer to a gboolean in which we will store whether the returned value has been read from mandatory preferences (TRUE), or from the user preferences (FALSE). When the @key has not been found, @mandatory is set to FALSE.
Returns: the value of the key, of its default value if not found.
Since: 3.1
Definition at line 521 of file na-settings.c.
References FALSE, key, KeyDef, KeyValue, and na_boxed_get_boolean().
Referenced by na_io_provider_is_conf_readable(), and na_settings_get_boolean().
na_settings_get_groups()
GSList * na_settings_get_groups (void)
na_settings_get_groups:
Returns: the list of groups in the configuration; this list should be na_core_utils_slist_free() by the caller.
This function participates to a rather bad hack to obtain the list of known i/o providers from preferences. We do not care of returning unique or sorted group names.
Since: 3.1
Definition at line 932 of file na-settings.c.
References na_core_utils_slist_from_array(), and NULL.
na_settings_get_string()
gchar * na_settings_get_string (const gchar * key, gboolean * found, gboolean * mandatory)
na_settings_get_string: @key: the key whose value is to be returned. @found: if not NULL, a pointer to a gboolean in which we will store whether the searched @key has been found (TRUE), or if the returned value comes from default (FALSE). @mandatory: if not NULL, a pointer to a gboolean in which we will store whether the returned value has been read from mandatory preferences (TRUE), or from the user preferences (FALSE). When the @key has not been found, @mandatory is set to FALSE.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: the value of the key as a newly allocated string, which should be g_free() by the caller.
Since: 3.1
Definition at line 564 of file na-settings.c.
References key, KeyDef, KeyValue, na_boxed_get_string(), and NULL.
Referenced by base_gtk_utils_select_dir(), base_gtk_utils_select_file_with_preview(), cact_export_ask_user(), na_importer_import_from_uris(), na_iprefs_get_order_mode(), and na_iprefs_get_tabs_pos().
na_settings_get_string_list()
GSList * na_settings_get_string_list (const gchar * key, gboolean * found, gboolean * mandatory)
na_settings_get_string_list: @key: the key whose value is to be returned. @found: if not NULL, a pointer to a gboolean in which we will store whether the searched @key has been found (TRUE), or if the returned value comes from default (FALSE). @mandatory: if not NULL, a pointer to a gboolean in which we will store whether the returned value has been read from mandatory preferences (TRUE), or from the user preferences (FALSE). When the @key has not been found, @mandatory is set to FALSE.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: the value of the key as a newly allocated list of strings. The returned list should be na_core_utils_slist_free() by the caller.
Since: 3.1
Definition at line 607 of file na-settings.c.
References key, KeyDef, KeyValue, na_boxed_get_string_list(), and NULL.
Referenced by na_io_provider_load_items().
na_settings_get_uint()
guint na_settings_get_uint (const gchar * key, gboolean * found, gboolean * mandatory)
na_settings_get_uint: @key: the key whose value is to be returned. @found: if not NULL, a pointer to a gboolean in which we will store whether the searched @key has been found (TRUE), or if the returned value comes from default (FALSE). @mandatory: if not NULL, a pointer to a gboolean in which we will store whether the returned value has been read from mandatory preferences (TRUE), or from the user preferences (FALSE). When the @key has not been found, @mandatory is set to FALSE.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: the value of the key.
Since: 3.1
Definition at line 649 of file na-settings.c.
References key, KeyDef, KeyValue, na_boxed_get_uint(), and NULL.
na_settings_get_uint_list()
GList * na_settings_get_uint_list (const gchar * key, gboolean * found, gboolean * mandatory)
na_settings_get_uint_list: @key: the key whose value is to be returned. @found: if not NULL, a pointer to a gboolean in which we will store whether the searched @key has been found (TRUE), or if the returned value comes from default (FALSE). @mandatory: if not NULL, a pointer to a gboolean in which we will store whether the returned value has been read from mandatory preferences (TRUE), or from the user preferences (FALSE). When the @key has not been found, @mandatory is set to FALSE.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: the value of the key as a newly allocated list of uints. The returned list should be g_list_free() by the caller.
Since: 3.1
Definition at line 692 of file na-settings.c.
References key, KeyDef, KeyValue, na_boxed_get_uint_list(), and NULL.
Referenced by na_gtk_utils_restore_window_position().
na_settings_register_key_callback()
void na_settings_register_key_callback (const gchar * key, GCallback callback, gpointer user_data)
na_settings_register_key_callback: @key: the key to be monitored. @callback: the function to be called when the value of the key changes. @user_data: data to be passed to the @callback function.
Registers a new consumer of the monitoring of the @key.
Since: 3.1
Definition at line 464 of file na-settings.c.
References key, and user_data.
na_settings_set_boolean()
gboolean na_settings_set_boolean (const gchar * key, gboolean value)
na_settings_set_boolean: @key: the key whose value is to be returned. @value: the boolean to be written.
This function writes @value as a user preference.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: TRUE is the writing has been successful, FALSE else.
Since: 3.1
Definition at line 730 of file na-settings.c.
References key, NULL, and ok.
Referenced by cact_main_toolbar_activate().
na_settings_set_boolean_ex()
gboolean na_settings_set_boolean_ex (const gchar * group, const gchar * key, gboolean value)
na_settings_set_boolean_ex: @group: the group in the keyed file; @key: the key whose value is to be returned. @value: the boolean to be written.
This function writes @value as a user preference.
Returns: TRUE is the writing has been successful, FALSE else.
Since: 3.1
Definition at line 755 of file na-settings.c.
References key, and ok.
na_settings_set_int_ex()
gboolean na_settings_set_int_ex (const gchar * group, const gchar * key, int value)
na_settings_set_int_ex: @group: the group in the keyed file; @key: the key whose value is to be returned. @value: the unsigned integer to be written.
This function writes @value as a user preference.
Returns: TRUE is the writing has been successful, FALSE else.
Since: 3.2
Definition at line 849 of file na-settings.c.
References key, and ok.
na_settings_set_string()
gboolean na_settings_set_string (const gchar * key, const gchar * value)
na_settings_set_string: @key: the key whose value is to be returned. @value: the string to be written.
This function writes @value as a user preference.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: TRUE is the writing has been successful, FALSE else.
Since: 3.1
Definition at line 782 of file na-settings.c.
References key, and NULL.
Referenced by base_gtk_utils_select_dir(), base_gtk_utils_select_file_with_preview(), na_iprefs_set_order_mode(), and na_iprefs_set_tabs_pos().
na_settings_set_string_ex()
gboolean na_settings_set_string_ex (const gchar * group, const gchar * key, const gchar * value)
na_settings_set_string_ex: @group: the group in the keyed file; @key: the key whose value is to be returned. @value: the string to be written.
This function writes @value as a user preference.
Returns: TRUE is the writing has been successful, FALSE else.
Since: 3.2
Definition at line 800 of file na-settings.c.
References key.
na_settings_set_string_list()
gboolean na_settings_set_string_list (const gchar * key, const GSList * value)
na_settings_set_string_list: @key: the key whose value is to be returned. @value: the list of strings to be written.
This function writes @value as a user preference.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: TRUE is the writing has been successful, FALSE else.
Since: 3.1
Definition at line 820 of file na-settings.c.
References key, NULL, ok, and TRUE.
Referenced by cact_providers_list_save(), cact_schemes_list_save_defaults(), and na_iprefs_write_level_zero().
na_settings_set_uint()
gboolean na_settings_set_uint (const gchar * key, guint value)
na_settings_set_uint: @key: the key whose value is to be returned. @value: the unsigned integer to be written.
This function writes @value as a user preference.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: TRUE is the writing has been successful, FALSE else.
Since: 3.1
Definition at line 876 of file na-settings.c.
References key, NULL, and ok.
na_settings_set_uint_list()
gboolean na_settings_set_uint_list (const gchar * key, const GList * value)
na_settings_set_uint_list: @key: the key whose value is to be returned. @value: the list of unsigned integers to be written.
This function writes @value as a user preference.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: TRUE is the writing has been successful, FALSE else.
Since: 3.1
Definition at line 903 of file na-settings.c.
References key, NULL, ok, and TRUE.
Referenced by na_gtk_utils_save_window_position().