MATE Desktop Environment: na-tokens.h File Reference
na-tokens.h File Reference
#include <api/na-object-profile.h>
Classes
struct NATokens
struct NATokensClass
Macros
#define NA_TYPE_TOKENS (na_tokens_get_type())
#define NA_TOKENS(object) (G_TYPE_CHECK_INSTANCE_CAST(object, NA_TYPE_TOKENS, NATokens))
#define NA_TOKENS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, NA_TYPE_TOKENS, NATokensClass))
#define NA_IS_TOKENS(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, NA_TYPE_TOKENS))
#define NA_IS_TOKENS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), NA_TYPE_TOKENS))
#define NA_TOKENS_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), NA_TYPE_TOKENS, NATokensClass))
Typedefs
typedef struct _NATokensPrivate NATokensPrivate
typedef struct _NATokensClassPrivate NATokensClassPrivate
Functions
GType na_tokens_get_type (void)
NATokens * na_tokens_new_for_example (void)
NATokens * na_tokens_new_from_selection (GList *selection)
gchar * na_tokens_parse_for_display (const NATokens *tokens, const gchar *string, gboolean utf8)
void na_tokens_execute_action (const NATokens *tokens, const NAObjectProfile *profile)
gchar * na_tokens_command_for_terminal (const gchar *pattern, const gchar *command)
Macro Definition Documentation
NA_IS_TOKENS
#define NA_IS_TOKENS (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, NA_TYPE_TOKENS))
Definition at line 89 of file na-tokens.h.
NA_IS_TOKENS_CLASS
#define NA_IS_TOKENS_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), NA_TYPE_TOKENS))
Definition at line 90 of file na-tokens.h.
NA_TOKENS
#define NA_TOKENS (object) (G_TYPE_CHECK_INSTANCE_CAST(object, NA_TYPE_TOKENS, NATokens))
Definition at line 87 of file na-tokens.h.
NA_TOKENS_CLASS
#define NA_TOKENS_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, NA_TYPE_TOKENS, NATokensClass))
Definition at line 88 of file na-tokens.h.
NA_TOKENS_GET_CLASS
#define NA_TOKENS_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), NA_TYPE_TOKENS, NATokensClass))
Definition at line 91 of file na-tokens.h.
NA_TYPE_TOKENS
#define NA_TYPE_TOKENS (na_tokens_get_type())
Definition at line 86 of file na-tokens.h.
Typedef Documentation
NATokensClassPrivate
typedef struct _NATokensClassPrivate NATokensClassPrivate
Definition at line 102 of file na-tokens.h.
NATokensPrivate
typedef struct _NATokensPrivate NATokensPrivate
Definition at line 93 of file na-tokens.h.
Function Documentation
na_tokens_command_for_terminal()
gchar * na_tokens_command_for_terminal (const gchar * pattern, const gchar * command)
na_tokens_command_for_terminal: @pattern: the command pattern; should include a 'COMMAND' keyword @command: the command to be actually run in the terminal
Returns: the command to be run, as a newly allocated string which should be g_free() by the caller.
Definition at line 649 of file na-tokens.c.
References command, and na_core_utils_str_subst().
na_tokens_execute_action()
void na_tokens_execute_action (const NATokens * tokens, const NAObjectProfile * profile)
Definition at line 389 of file na-tokens.c.
References command, FALSE, na_object_get_parameters, na_object_get_path, NATokens::private, and TRUE.
na_tokens_get_type()
GType na_tokens_get_type (void)
Definition at line 102 of file na-tokens.c.
na_tokens_new_for_example()
NATokens * na_tokens_new_for_example (void)
Definition at line 246 of file na-tokens.c.
References _, FALSE, na_core_utils_dir_split_ext(), NA_TYPE_TOKENS, NULL, NATokens::private, and TRUE.
na_tokens_new_from_selection()
NATokens * na_tokens_new_from_selection (GList * selection)
Definition at line 317 of file na-tokens.c.
References FALSE, na_core_utils_dir_split_ext(), NA_SELECTED_INFO, na_selected_info_get_basename(), na_selected_info_get_dirname(), na_selected_info_get_mime_type(), na_selected_info_get_path(), na_selected_info_get_uri(), na_selected_info_get_uri_host(), na_selected_info_get_uri_port(), na_selected_info_get_uri_scheme(), na_selected_info_get_uri_user(), NA_TYPE_TOKENS, NULL, NATokens::private, and TRUE.
na_tokens_parse_for_display()
gchar * na_tokens_parse_for_display (const NATokens * tokens, const gchar * string, gboolean utf8)
Definition at line 376 of file na-tokens.c.
References FALSE.