MATE Desktop Environment: na-tokens.c File Reference
na-tokens.c File Reference
#include <gio/gunixinputstream.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <string.h>
#include <api/na-core-utils.h>
#include <api/na-object-api.h>
#include "na-selected-info.h"
#include "na-settings.h"
#include "na-tokens.h"
Functions
GType na_tokens_get_type (void)
NATokens * na_tokens_new_for_example (void)
NATokens * na_tokens_new_from_selection (GList *selection)
gchar * na_tokens_parse_for_display (const NATokens *tokens, const gchar *string, gboolean utf8)
void na_tokens_execute_action (const NATokens *tokens, const NAObjectProfile *profile)
gchar * na_tokens_command_for_terminal (const gchar *pattern, const gchar *command)
Function Documentation
na_tokens_command_for_terminal()
gchar * na_tokens_command_for_terminal (const gchar * pattern, const gchar * command)
na_tokens_command_for_terminal: @pattern: the command pattern; should include a 'COMMAND' keyword @command: the command to be actually run in the terminal
Returns: the command to be run, as a newly allocated string which should be g_free() by the caller.
Definition at line 649 of file na-tokens.c.
References command, and na_core_utils_str_subst().
na_tokens_execute_action()
void na_tokens_execute_action (const NATokens * tokens, const NAObjectProfile * profile)
Definition at line 389 of file na-tokens.c.
References command, FALSE, na_object_get_parameters, na_object_get_path, NATokens::private, and TRUE.
na_tokens_get_type()
GType na_tokens_get_type (void)
Definition at line 102 of file na-tokens.c.
na_tokens_new_for_example()
NATokens * na_tokens_new_for_example (void)
Definition at line 246 of file na-tokens.c.
References _, FALSE, na_core_utils_dir_split_ext(), NA_TYPE_TOKENS, NULL, NATokens::private, and TRUE.
na_tokens_new_from_selection()
NATokens * na_tokens_new_from_selection (GList * selection)
Definition at line 317 of file na-tokens.c.
References FALSE, na_core_utils_dir_split_ext(), NA_SELECTED_INFO, na_selected_info_get_basename(), na_selected_info_get_dirname(), na_selected_info_get_mime_type(), na_selected_info_get_path(), na_selected_info_get_uri(), na_selected_info_get_uri_host(), na_selected_info_get_uri_port(), na_selected_info_get_uri_scheme(), na_selected_info_get_uri_user(), NA_TYPE_TOKENS, NULL, NATokens::private, and TRUE.
na_tokens_parse_for_display()
gchar * na_tokens_parse_for_display (const NATokens * tokens, const gchar * string, gboolean utf8)
Definition at line 376 of file na-tokens.c.
References FALSE.