MATE Desktop Environment: na-timeout.c File Reference
na-timeout.c File Reference
#include <api/na-timeout.h>
Functions
void na_timeout_event (NATimeout *event)
Function Documentation
na_timeout_event()
void na_timeout_event (NATimeout * event)
na_timeout_event: @timeout: the NATimeout structure which will handle this event.
Definition at line 44 of file na-timeout.c.
References NATimeout::last_time, NULL, NATimeout::source_id, and NATimeout::timeout.
Referenced by cact_main_window_block_reload(), cadp_desktop_provider_on_monitor_event(), and na_pivot_on_item_changed_handler().