MATE Desktop Environment: procman Namespace Reference
procman Namespace Reference
Namespaces
namespace settings
Classes
class IconThemeWrapper
class OptionGroup
class SelectionMemento
Functions
void memory_size_cell_data_func (GtkTreeViewColumn *col, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
void memory_size_na_cell_data_func (GtkTreeViewColumn *col, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
void storage_size_cell_data_func (GtkTreeViewColumn *col, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
void storage_size_na_cell_data_func (GtkTreeViewColumn *col, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
void io_rate_cell_data_func (GtkTreeViewColumn *, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
void duration_cell_data_func (GtkTreeViewColumn *, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
void time_cell_data_func (GtkTreeViewColumn *, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
void status_cell_data_func (GtkTreeViewColumn *, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
void priority_cell_data_func (GtkTreeViewColumn *, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
gint priority_compare_func (GtkTreeModel *model, GtkTreeIter *first, GtkTreeIter *second, gpointer user_data)
gint number_compare_func (GtkTreeModel *model, GtkTreeIter *first, GtkTreeIter *second, gpointer user_data)
template<>
void tree_store_update< const char > (GtkTreeModel *model, GtkTreeIter *iter, int column, const char *new_value)
gchar * format_duration_for_display (unsigned centiseconds)
template<typename T >
void poison (T &t, char c)
template<typename T >
void tree_store_update (GtkTreeModel *model, GtkTreeIter *iter, int column, const T &new_value)
template<typename T >
void tree_store_update (GtkTreeModel *model, GtkTreeIter *iter, int column, T *new_value)
template<>
void tree_store_update< const char > (GtkTreeModel *model, GtkTreeIter *iter, int column, const char *new_value)
template<>
void tree_store_update< char > (GtkTreeModel *model, GtkTreeIter *iter, int column, char *new_value)
gchar * get_nice_level (gint nice)
Function Documentation
duration_cell_data_func()
void procman::duration_cell_data_func (GtkTreeViewColumn * , GtkCellRenderer * renderer, GtkTreeModel * model, GtkTreeIter * iter, gpointer user_data)
Definition at line 514 of file util.cpp.
References format_duration_for_display(), ProcData::frequency, ProcData::get_instance(), NULL, and user_data.
Referenced by proctable_new().
format_duration_for_display()
gchar * procman::format_duration_for_display (unsigned centiseconds)
Definition at line 116 of file util.cpp.
References _.
Referenced by duration_cell_data_func().
get_nice_level()
gchar * procman::get_nice_level (gint nice)
Definition at line 164 of file util.cpp.
References _.
Referenced by priority_cell_data_func(), and procdialog_create_renice_dialog().
io_rate_cell_data_func()
void procman::io_rate_cell_data_func (GtkTreeViewColumn * , GtkCellRenderer * renderer, GtkTreeModel * model, GtkTreeIter * iter, gpointer user_data)
Definition at line 473 of file util.cpp.
References _, NULL, and user_data.
Referenced by proctable_new().
memory_size_cell_data_func()
void procman::memory_size_cell_data_func (GtkTreeViewColumn * col, GtkCellRenderer * renderer, GtkTreeModel * model, GtkTreeIter * iter, gpointer user_data)
Definition at line 329 of file util.cpp.
References NULL, and user_data.
Referenced by proctable_new().
memory_size_na_cell_data_func()
void procman::memory_size_na_cell_data_func (GtkTreeViewColumn * col, GtkCellRenderer * renderer, GtkTreeModel * model, GtkTreeIter * iter, gpointer user_data)
Definition at line 363 of file util.cpp.
References _, NULL, and user_data.
Referenced by proctable_new().
number_compare_func()
gint procman::number_compare_func (GtkTreeModel * model, GtkTreeIter * first, GtkTreeIter * second, gpointer user_data)
Definition at line 632 of file util.cpp.
References user_data.
Referenced by proctable_new().
poison()
template<typename T > void procman::poison (T & t, char c)
Definition at line 92 of file mate-system-monitor/src/util.h.
priority_cell_data_func()
void procman::priority_cell_data_func (GtkTreeViewColumn * , GtkCellRenderer * renderer, GtkTreeModel * model, GtkTreeIter * iter, gpointer user_data)
Definition at line 600 of file util.cpp.
References get_nice_level(), NULL, and user_data.
Referenced by proctable_new().
priority_compare_func()
gint procman::priority_compare_func (GtkTreeModel * model, GtkTreeIter * first, GtkTreeIter * second, gpointer user_data)
Definition at line 618 of file util.cpp.
References user_data.
Referenced by proctable_new().
status_cell_data_func()
void procman::status_cell_data_func (GtkTreeViewColumn * , GtkCellRenderer * renderer, GtkTreeModel * model, GtkTreeIter * iter, gpointer user_data)
Definition at line 574 of file util.cpp.
References format_process_state(), NULL, and user_data.
Referenced by proctable_new().
storage_size_cell_data_func()
void procman::storage_size_cell_data_func (GtkTreeViewColumn * col, GtkCellRenderer * renderer, GtkTreeModel * model, GtkTreeIter * iter, gpointer user_data)
Definition at line 401 of file util.cpp.
References NULL, and user_data.
Referenced by create_disk_view().
storage_size_na_cell_data_func()
void procman::storage_size_na_cell_data_func (GtkTreeViewColumn * col, GtkCellRenderer * renderer, GtkTreeModel * model, GtkTreeIter * iter, gpointer user_data)
Definition at line 435 of file util.cpp.
References _, NULL, and user_data.
Referenced by proctable_new().
time_cell_data_func()
void procman::time_cell_data_func (GtkTreeViewColumn * , GtkCellRenderer * renderer, GtkTreeModel * model, GtkTreeIter * iter, gpointer user_data)
Definition at line 547 of file util.cpp.
References NULL, procman_format_date_for_display(), and user_data.
Referenced by proctable_new().
tree_store_update() [1/2]
template<typename T > void procman::tree_store_update (GtkTreeModel * model, GtkTreeIter * iter, int column, const T & new_value)
Definition at line 102 of file mate-system-monitor/src/util.h.
tree_store_update() [2/2]
template<typename T > void procman::tree_store_update (GtkTreeModel * model, GtkTreeIter * iter, int column, T * new_value)
tree_store_update< char >()
template<> void procman::tree_store_update< char > (GtkTreeModel * model, GtkTreeIter * iter, int column, char * new_value) inline
Definition at line 123 of file mate-system-monitor/src/util.h.
References tree_store_update< const char >().
tree_store_update< const char >() [1/2]
template<> void procman::tree_store_update< const char > (GtkTreeModel * model, GtkTreeIter * iter, int column, const char * new_value)
Definition at line 649 of file util.cpp.
Referenced by tree_store_update< char >().
tree_store_update< const char >() [2/2]
template<> void procman::tree_store_update< const char > (GtkTreeModel * model, GtkTreeIter * iter, int column, const char * new_value)
Definition at line 649 of file util.cpp.
Referenced by tree_store_update< char >().