MATE Desktop Environment: obexpush.h File Reference
obexpush.h File Reference
#include <glib.h>
#include "user_share-private.h"
Functions
void obexpush_up (void)
void obexpush_down (void)
void obexpush_restart (void)
gboolean obexpush_init (void)
void obexpush_set_accept_files_policy (AcceptSetting accept_setting)
void obexpush_set_notify (gboolean enabled)
Function Documentation
obexpush_down()
void obexpush_down (void)
Definition at line 512 of file obexpush.c.
References TRUE.
obexpush_init()
gboolean obexpush_init (void)
Definition at line 525 of file obexpush.c.
References connection, FALSE, NULL, and TRUE.
Referenced by main().
obexpush_restart()
void obexpush_restart (void)
Definition at line 518 of file obexpush.c.
References FALSE, and obexpush_up().
obexpush_set_accept_files_policy()
void obexpush_set_accept_files_policy (AcceptSetting accept_setting)
Definition at line 551 of file obexpush.c.
obexpush_set_notify()
void obexpush_set_notify (gboolean enabled)
Definition at line 557 of file obexpush.c.
obexpush_up()
void obexpush_up (void)
Definition at line 420 of file obexpush.c.
References connection, FALSE, lookup_download_dir(), NULL, and TRUE.
Referenced by obexpush_restart().