MATE Desktop Environment: open-file.h File Reference
open-file.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <time.h>
Classes
struct OpenFile
Macros
#define FR_TYPE_OPEN_FILE (open_file_get_type ())
Functions
GType open_file_get_type (void)
OpenFile * open_file_new (const char *path, const char *extracted_path, const char *temp_dir)
OpenFile * open_file_copy (OpenFile *src)
void open_file_free (OpenFile *ofile)
Macro Definition Documentation
FR_TYPE_OPEN_FILE
#define FR_TYPE_OPEN_FILE (open_file_get_type ())
Definition at line 39 of file open-file.h.
Function Documentation
open_file_copy()
OpenFile * open_file_copy (OpenFile * src)
Definition at line 61 of file open-file.c.
References OpenFile::extracted_uri, OpenFile::last_modified, OpenFile::path, and OpenFile::temp_dir.
Referenced by open_file_get_type().
open_file_free()
void open_file_free (OpenFile * ofile)
Definition at line 48 of file open-file.c.
References OpenFile::extracted_uri, OpenFile::monitor, NULL, OpenFile::path, and OpenFile::temp_dir.
Referenced by open_file_get_type(), and open_file_new().
open_file_get_type()
GType open_file_get_type (void)
Definition at line 75 of file open-file.c.
References open_file_copy(), open_file_free(), and type.
open_file_new()
OpenFile * open_file_new (const char * path, const char * extracted_path, const char * temp_dir)
Definition at line 28 of file open-file.c.
References OpenFile::extracted_uri, get_file_mtime(), OpenFile::last_modified, NULL, open_file_free(), OpenFile::path, OpenFile::temp_dir, and uri_exists().