MATE Desktop Environment: oss-stream.h File Reference
oss-stream.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include "oss-types.h"
Classes
struct _OssStream
struct _OssStreamClass
Macros
#define OSS_TYPE_STREAM (oss_stream_get_type ())
#define OSS_STREAM(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), OSS_TYPE_STREAM, OssStream))
#define OSS_IS_STREAM(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), OSS_TYPE_STREAM))
#define OSS_STREAM_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), OSS_TYPE_STREAM, OssStreamClass))
#define OSS_IS_STREAM_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), OSS_TYPE_STREAM))
#define OSS_STREAM_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), OSS_TYPE_STREAM, OssStreamClass))
Typedefs
typedef struct _OssStreamClass OssStreamClass
typedef struct _OssStreamPrivate OssStreamPrivate
Functions
GType oss_stream_get_type (void)
OssStream * oss_stream_new (const gchar *name, MateMixerDevice *device, MateMixerDirection direction)
void oss_stream_add_control (OssStream *stream, OssStreamControl *control)
void oss_stream_load (OssStream *stream)
gboolean oss_stream_has_controls (OssStream *stream)
gboolean oss_stream_has_default_control (OssStream *stream)
OssStreamControl * oss_stream_get_default_control (OssStream *stream)
void oss_stream_set_default_control (OssStream *stream, OssStreamControl *control)
void oss_stream_set_switch_data (OssStream *stream, gint fd, GList *options)
void oss_stream_remove_all (OssStream *stream)
Macro Definition Documentation
OSS_IS_STREAM
#define OSS_IS_STREAM (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), OSS_TYPE_STREAM))
Definition at line 33 of file oss-stream.h.
OSS_IS_STREAM_CLASS
#define OSS_IS_STREAM_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), OSS_TYPE_STREAM))
Definition at line 37 of file oss-stream.h.
OSS_STREAM
#define OSS_STREAM (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), OSS_TYPE_STREAM, OssStream))
Definition at line 31 of file oss-stream.h.
OSS_STREAM_CLASS
#define OSS_STREAM_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), OSS_TYPE_STREAM, OssStreamClass))
Definition at line 35 of file oss-stream.h.
OSS_STREAM_GET_CLASS
#define OSS_STREAM_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), OSS_TYPE_STREAM, OssStreamClass))
Definition at line 39 of file oss-stream.h.
OSS_TYPE_STREAM
#define OSS_TYPE_STREAM (oss_stream_get_type ())
Definition at line 29 of file oss-stream.h.
Typedef Documentation
OssStreamClass
typedef struct _OssStreamClass OssStreamClass
Definition at line 42 of file oss-stream.h.
OssStreamPrivate
typedef struct _OssStreamPrivate OssStreamPrivate
Definition at line 43 of file oss-stream.h.
Function Documentation
oss_stream_add_control()
void oss_stream_add_control (OssStream * stream, OssStreamControl * control)
Definition at line 109 of file oss-stream.c.
References MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), name, OSS_IS_STREAM, and OSS_IS_STREAM_CONTROL.
oss_stream_get_default_control()
OssStreamControl * oss_stream_get_default_control (OssStream * stream)
Definition at line 168 of file oss-stream.c.
References MATE_MIXER_STREAM, mate_mixer_stream_get_default_control(), NULL, OSS_IS_STREAM, and OSS_STREAM_CONTROL.
oss_stream_get_type()
GType oss_stream_get_type (void)
oss_stream_has_controls()
gboolean oss_stream_has_controls (OssStream * stream)
Definition at line 146 of file oss-stream.c.
References FALSE, NULL, OSS_IS_STREAM, and TRUE.
Referenced by oss_device_load().
oss_stream_has_default_control()
gboolean oss_stream_has_default_control (OssStream * stream)
Definition at line 157 of file oss-stream.c.
References FALSE, MATE_MIXER_STREAM, mate_mixer_stream_get_default_control(), NULL, OSS_IS_STREAM, and TRUE.
oss_stream_load()
void oss_stream_load (OssStream * stream)
Definition at line 127 of file oss-stream.c.
References NULL, OSS_IS_STREAM, OSS_STREAM_CONTROL, oss_stream_control_load(), and oss_switch_load().
oss_stream_new()
OssStream * oss_stream_new (const gchar * name, MateMixerDevice * device, MateMixerDirection direction)
Definition at line 89 of file oss-stream.c.
References label, mate_mixer_device_get_label(), name, NULL, OSS_IS_DEVICE, and OSS_TYPE_STREAM.
Referenced by oss_device_load().
oss_stream_remove_all()
void oss_stream_remove_all (OssStream * stream)
Definition at line 226 of file oss-stream.c.
References MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), NULL, OSS_IS_STREAM, OSS_STREAM_CONTROL, oss_stream_control_close(), oss_stream_set_default_control(), OSS_STREAM_SWITCH_NAME, and oss_switch_close().
Referenced by oss_device_close().
oss_stream_set_default_control()
void oss_stream_set_default_control (OssStream * stream, OssStreamControl * control)
Definition at line 182 of file oss-stream.c.
References _mate_mixer_stream_set_default_control(), MATE_MIXER_STREAM, MATE_MIXER_STREAM_CONTROL, NULL, OSS_IS_STREAM, and OSS_IS_STREAM_CONTROL.
Referenced by oss_device_load(), and oss_stream_remove_all().
oss_stream_set_switch_data()
void oss_stream_set_switch_data (OssStream * stream, gint fd, GList * options)
Definition at line 195 of file oss-stream.c.
References _, NULL, OSS_IS_STREAM, OSS_STREAM_SWITCH_NAME, oss_switch_load(), and oss_switch_new().