MATE Desktop Environment: oss-device.c File Reference
oss-device.c File Reference
#include <errno.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <glib/gstdio.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include <libmatemixer/matemixer-private.h>
#include "oss-common.h"
#include "oss-device.h"
#include "oss-stream.h"
#include "oss-stream-control.h"
#include "oss-switch-option.h"
Macros
#define OSS_DEVICE_ICON "audio-card"
#define OSS_POLL_TIMEOUT_NORMAL 500
#define OSS_POLL_TIMEOUT_RAPID 50
#define OSS_POLL_TIMEOUT_RESTORE 3000
#define OSS_N_DEVICES MIN (G_N_ELEMENTS (oss_devices), SOUND_MIXER_NRDEVICES)
#define OSS_MASK_HAS_DEVICE(mask, i) ((gboolean) (((mask) & (1 << (i))) > 0))
Enumerations
enum OssPollMode { OSS_POLL_NORMAL , OSS_POLL_RAPID }
enum OssDevChannelType { OSS_DEV_ANY , OSS_DEV_INPUT , OSS_DEV_OUTPUT }
enum { CLOSED , N_SIGNALS }
Functions
OssDevice * oss_device_new (const gchar *name, const gchar *label, const gchar *path, gint fd)
gboolean oss_device_open (OssDevice *device)
gboolean oss_device_is_open (OssDevice *device)
void oss_device_close (OssDevice *device)
void oss_device_load (OssDevice *device)
const gchar * oss_device_get_path (OssDevice *device)
OssStream * oss_device_get_input_stream (OssDevice *device)
OssStream * oss_device_get_output_stream (OssDevice *device)
Macro Definition Documentation
OSS_DEVICE_ICON
#define OSS_DEVICE_ICON "audio-card"
Definition at line 60 of file oss-device.c.
OSS_MASK_HAS_DEVICE
#define OSS_MASK_HAS_DEVICE (mask, i) ((gboolean) (((mask) & (1 << (i))) > 0))
Definition at line 544 of file oss-device.c.
OSS_N_DEVICES
#define OSS_N_DEVICES MIN (G_N_ELEMENTS (oss_devices), SOUND_MIXER_NRDEVICES)
Definition at line 122 of file oss-device.c.
OSS_POLL_TIMEOUT_NORMAL
#define OSS_POLL_TIMEOUT_NORMAL 500
Definition at line 62 of file oss-device.c.
OSS_POLL_TIMEOUT_RAPID
#define OSS_POLL_TIMEOUT_RAPID 50
Definition at line 63 of file oss-device.c.
OSS_POLL_TIMEOUT_RESTORE
#define OSS_POLL_TIMEOUT_RESTORE 3000
Definition at line 64 of file oss-device.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CLOSED
N_SIGNALS
Definition at line 175 of file oss-device.c.
OssDevChannelType
enum OssDevChannelType
Enumerator
OSS_DEV_ANY
OSS_DEV_INPUT
OSS_DEV_OUTPUT
Definition at line 71 of file oss-device.c.
OssPollMode
enum OssPollMode
Enumerator
OSS_POLL_NORMAL
OSS_POLL_RAPID
Definition at line 66 of file oss-device.c.
Function Documentation
oss_device_close()
void oss_device_close (OssDevice * device)
Definition at line 352 of file oss-device.c.
References CLOSED, MATE_MIXER_STREAM, mate_mixer_stream_get_name(), name, NULL, OSS_IS_DEVICE, oss_stream_remove_all(), and _OssDevice::priv.
oss_device_get_input_stream()
OssStream * oss_device_get_input_stream (OssDevice * device)
Definition at line 508 of file oss-device.c.
References NULL, OSS_IS_DEVICE, and _OssDevice::priv.
oss_device_get_output_stream()
OssStream * oss_device_get_output_stream (OssDevice * device)
Definition at line 516 of file oss-device.c.
References NULL, OSS_IS_DEVICE, and _OssDevice::priv.
oss_device_get_path()
const gchar * oss_device_get_path (OssDevice * device)
Definition at line 500 of file oss-device.c.
References NULL, OSS_IS_DEVICE, and _OssDevice::priv.
oss_device_is_open()
gboolean oss_device_is_open (OssDevice * device)
Definition at line 341 of file oss-device.c.
References FALSE, OSS_IS_DEVICE, _OssDevice::priv, and TRUE.
oss_device_load()
void oss_device_load (OssDevice * device)
Definition at line 401 of file oss-device.c.
References item, MATE_MIXER_DEVICE, mate_mixer_device_get_name(), MATE_MIXER_DIRECTION_INPUT, MATE_MIXER_DIRECTION_OUTPUT, MATE_MIXER_STREAM, mate_mixer_stream_list_controls(), name, NULL, OSS_IS_DEVICE, OSS_POLL_NORMAL, OSS_STREAM_CONTROL, oss_stream_has_controls(), oss_stream_new(), oss_stream_set_default_control(), _OssDevice::priv, and TRUE.
oss_device_new()
OssDevice * oss_device_new (const gchar * name, const gchar * label, const gchar * path, gint fd)
Definition at line 267 of file oss-device.c.
References label, name, NULL, OSS_DEVICE_ICON, OSS_TYPE_DEVICE, and _OssDevice::priv.
oss_device_open()
gboolean oss_device_open (OssDevice * device)
Definition at line 299 of file oss-device.c.
References FALSE, MATE_MIXER_DEVICE, mate_mixer_device_get_label(), OSS_IS_DEVICE, _OssDevice::priv, and TRUE.