MATE Desktop Environment: oss-switch.c File Reference
oss-switch.c File Reference
#include <errno.h>
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include <libmatemixer/matemixer-private.h>
#include "oss-common.h"
#include "oss-stream.h"
#include "oss-switch.h"
#include "oss-switch-option.h"
Macros
#define OSS_SWITCH_PREFERRED_DEFAULT_DEVNUM 7 /* Microphone */
Functions
OssSwitch * oss_switch_new (OssStream *stream, const gchar *name, const gchar *label, gint fd, GList *options)
void oss_switch_load (OssSwitch *swtch)
void oss_switch_close (OssSwitch *swtch)
Macro Definition Documentation
OSS_SWITCH_PREFERRED_DEFAULT_DEVNUM
#define OSS_SWITCH_PREFERRED_DEFAULT_DEVNUM 7 /* Microphone */
Definition at line 245 of file oss-switch.c.
Function Documentation
oss_switch_close()
void oss_switch_close (OssSwitch * swtch)
Definition at line 202 of file oss-switch.c.
References OSS_IS_SWITCH, and _OssSwitch::priv.
Referenced by oss_stream_remove_all().
oss_switch_load()
void oss_switch_load (OssSwitch * swtch)
Definition at line 135 of file oss-switch.c.
References _mate_mixer_switch_set_active_option(), FALSE, MATE_MIXER_SWITCH, mate_mixer_switch_get_name(), MATE_MIXER_SWITCH_OPTION, mate_mixer_switch_option_get_name(), mate_mixer_switch_set_active_option(), NULL, option, OSS_IS_SWITCH, OSS_SWITCH_OPTION, oss_switch_option_get_devnum(), and _OssSwitch::priv.
Referenced by oss_stream_load(), and oss_stream_set_switch_data().
oss_switch_new()
OssSwitch * oss_switch_new (OssStream * stream, const gchar * name, const gchar * label, gint fd, GList * options)
Definition at line 99 of file oss-switch.c.
References label, MATE_MIXER_STREAM_SWITCH_ROLE_PORT, name, NULL, OSS_IS_STREAM, OSS_TYPE_SWITCH, and _OssSwitch::priv.
Referenced by oss_stream_set_switch_data().