MATE Desktop Environment: panel-gtk.h File Reference
panel-gtk.h File Reference
#include <gtk/gtk.h>
Macros
#define PANEL_GTK_BUILDER_GET(builder, name) GTK_WIDGET (gtk_builder_get_object (builder, name))
Functions
void panel_gtk_file_chooser_add_image_preview (GtkFileChooser *chooser)
GtkWidget * panel_dialog_add_button (GtkDialog *dialog, const gchar *button_text, const gchar *icon_name, gint response_id)
GtkWidget * panel_file_chooser_dialog_new (const gchar *title, GtkWindow *parent, GtkFileChooserAction action, const gchar *first_button_text,...)
GtkWidget * panel_image_menu_item_new_from_icon (const gchar *icon_name, const gchar *label_name)
GtkWidget * panel_image_menu_item_new_from_gicon (GIcon *gicon, const gchar *label_name)
GtkWidget * panel_check_menu_item_new (GtkWidget *widget_check)
Macro Definition Documentation
PANEL_GTK_BUILDER_GET
#define PANEL_GTK_BUILDER_GET (builder, name) GTK_WIDGET (gtk_builder_get_object (builder, name))
Definition at line 35 of file panel-gtk.h.
Function Documentation
panel_check_menu_item_new()
GtkWidget * panel_check_menu_item_new (GtkWidget * widget_check)
Definition at line 258 of file panel-gtk.c.
References FALSE, and NULL.
Referenced by mate_panel_applet_create_menu().
panel_dialog_add_button()
GtkWidget * panel_dialog_add_button (GtkDialog * dialog, const gchar * button_text, const gchar * icon_name, gint response_id)
Definition at line 94 of file panel-gtk.c.
References TRUE.
Referenced by panel_deletion_dialog().
panel_file_chooser_dialog_new()
GtkWidget * panel_file_chooser_dialog_new (const gchar * title, GtkWindow * parent, GtkFileChooserAction action, const gchar * first_button_text, ...)
Definition at line 151 of file panel-gtk.c.
References action.
panel_gtk_file_chooser_add_image_preview()
void panel_gtk_file_chooser_add_image_preview (GtkFileChooser * chooser)
Definition at line 71 of file panel-gtk.c.
panel_image_menu_item_new_from_gicon()
GtkWidget * panel_image_menu_item_new_from_gicon (GIcon * gicon, const gchar * label_name)
Definition at line 220 of file panel-gtk.c.
References NULL.
panel_image_menu_item_new_from_icon()
GtkWidget * panel_image_menu_item_new_from_icon (const gchar * icon_name, const gchar * label_name)
Definition at line 182 of file panel-gtk.c.
References NULL.
Referenced by mate_panel_applet_create_menu(), and panel_context_menu_create().