MATE Desktop Environment: panel-ditem-editor.c File Reference
panel-ditem-editor.c File Reference
#include <config.h>
#include <string.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <libpanel-util/panel-icon-chooser.h>
#include <libpanel-util/panel-keyfile.h>
#include <libpanel-util/panel-show.h>
#include <libpanel-util/panel-xdg.h>
#include <libpanel-util/panel-gtk.h>
#include "panel-ditem-editor.h"
#include "panel-icon-names.h"
#include "panel-util.h"
#include "panel-schemas.h"
#include "panel-marshal.h"
Macros
#define SAVE_FREQUENCY 2
#define CONNECT_CHANGED(widget, callback)
#define BLOCK_CHANGED(widget, callback)
#define UNBLOCK_CHANGED(widget, callback)
Enumerations
enum { REVERT_BUTTON = 1 }
enum PanelDItemEditorType {
PANEL_DITEM_EDITOR_TYPE_NULL , PANEL_DITEM_EDITOR_TYPE_APPLICATION , PANEL_DITEM_EDITOR_TYPE_TERMINAL_APPLICATION , PANEL_DITEM_EDITOR_TYPE_LINK ,
PANEL_DITEM_EDITOR_TYPE_DIRECTORY
}
enum { COLUMN_TEXT , COLUMN_TYPE , NUMBER_COLUMNS }
enum {
SAVED , CHANGED , NAME_CHANGED , COMMAND_CHANGED ,
COMMENT_CHANGED , ICON_CHANGED , ERROR_REPORTED , LAST_SIGNAL
}
enum { PROP_0 , PROP_KEYFILE , PROP_URI , PROP_TYPEDIRECTORY }
Functions
void panel_ditem_editor_sync_display (PanelDItemEditor *dialog)
GtkWidget * panel_ditem_editor_new (GtkWindow *parent, GKeyFile *key_file, const char *uri, const char *title)
GtkWidget * panel_ditem_editor_new_directory (GtkWindow *parent, GKeyFile *key_file, const char *uri, const char *title)
void panel_ditem_editor_set_uri (PanelDItemEditor *dialog, const char *uri)
GKeyFile * panel_ditem_editor_get_key_file (PanelDItemEditor *dialog)
GKeyFile * panel_ditem_editor_get_revert_key_file (PanelDItemEditor *dialog)
const char * panel_ditem_editor_get_uri (PanelDItemEditor *dialog)
void panel_ditem_register_save_uri_func (PanelDItemEditor *dialog, PanelDitemSaveUri save_uri, gpointer data)
Macro Definition Documentation
BLOCK_CHANGED
#define BLOCK_CHANGED (widget, callback)
Value:
    g_signal_handlers_block_by_func (G_OBJECT (widget), \
                     G_CALLBACK (callback), \
                     dialog); \
    g_signal_handlers_block_by_func (G_OBJECT (widget), \
                     G_CALLBACK (panel_ditem_editor_changed), \
                     dialog);
CONNECT_CHANGED
#define CONNECT_CHANGED (widget, callback)
Value:
    g_signal_connect_swapped (widget, "changed", \
                  G_CALLBACK (callback), \
                  dialog); \
    g_signal_connect_swapped (widget, "changed", \
                  G_CALLBACK (panel_ditem_editor_changed), \
                  dialog);
SAVE_FREQUENCY
#define SAVE_FREQUENCY 2
Definition at line 90 of file panel-ditem-editor.c.
UNBLOCK_CHANGED
#define UNBLOCK_CHANGED (widget, callback)
Value:
    g_signal_handlers_unblock_by_func (G_OBJECT (widget), \
                       G_CALLBACK (callback), \
                       dialog); \
    g_signal_handlers_unblock_by_func (G_OBJECT (widget), \
                       G_CALLBACK (panel_ditem_editor_changed), \
                       dialog);
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
REVERT_BUTTON
Definition at line 92 of file panel-ditem-editor.c.
anonymous enum
anonymous enum
Enumerator
COLUMN_TEXT
COLUMN_TYPE
NUMBER_COLUMNS
Definition at line 104 of file panel-ditem-editor.c.
anonymous enum
anonymous enum
Enumerator
SAVED
CHANGED
NAME_CHANGED
COMMAND_CHANGED
COMMENT_CHANGED
ICON_CHANGED
ERROR_REPORTED
LAST_SIGNAL
Definition at line 153 of file panel-ditem-editor.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_KEYFILE
PROP_URI
PROP_TYPEDIRECTORY
Definition at line 164 of file panel-ditem-editor.c.
PanelDItemEditorType
enum PanelDItemEditorType
Enumerator
PANEL_DITEM_EDITOR_TYPE_NULL
PANEL_DITEM_EDITOR_TYPE_APPLICATION
PANEL_DITEM_EDITOR_TYPE_TERMINAL_APPLICATION
PANEL_DITEM_EDITOR_TYPE_LINK
PANEL_DITEM_EDITOR_TYPE_DIRECTORY
Definition at line 96 of file panel-ditem-editor.c.
Function Documentation
panel_ditem_editor_get_key_file()
GKeyFile * panel_ditem_editor_get_key_file (PanelDItemEditor * dialog)
Definition at line 1579 of file panel-ditem-editor.c.
References NULL, PANEL_IS_DITEM_EDITOR, and _PanelDItemEditor::priv.
Referenced by ask_about_launcher().
panel_ditem_editor_get_revert_key_file()
GKeyFile * panel_ditem_editor_get_revert_key_file (PanelDItemEditor * dialog)
Definition at line 1587 of file panel-ditem-editor.c.
References NULL, PANEL_IS_DITEM_EDITOR, and _PanelDItemEditor::priv.
panel_ditem_editor_get_uri()
const char * panel_ditem_editor_get_uri (PanelDItemEditor * dialog)
Definition at line 1594 of file panel-ditem-editor.c.
References NULL, PANEL_IS_DITEM_EDITOR, and _PanelDItemEditor::priv.
panel_ditem_editor_new()
GtkWidget * panel_ditem_editor_new (GtkWindow * parent, GKeyFile * key_file, const char * uri, const char * title)
Definition at line 1507 of file panel-ditem-editor.c.
References FALSE.
Referenced by ask_about_launcher(), launcher_properties(), and main().
panel_ditem_editor_new_directory()
GtkWidget * panel_ditem_editor_new_directory (GtkWindow * parent, GKeyFile * key_file, const char * uri, const char * title)
Definition at line 1517 of file panel-ditem-editor.c.
References TRUE.
Referenced by main().
panel_ditem_editor_set_uri()
void panel_ditem_editor_set_uri (PanelDItemEditor * dialog, const char * uri)
Definition at line 1543 of file panel-ditem-editor.c.
References NULL, PANEL_IS_DITEM_EDITOR, and _PanelDItemEditor::priv.
panel_ditem_editor_sync_display()
void panel_ditem_editor_sync_display (PanelDItemEditor * dialog)
Definition at line 1069 of file panel-ditem-editor.c.
References COLUMN_TYPE, FALSE, NULL, PANEL_DITEM_EDITOR_TYPE_APPLICATION, PANEL_DITEM_EDITOR_TYPE_LINK, PANEL_DITEM_EDITOR_TYPE_NULL, PANEL_DITEM_EDITOR_TYPE_TERMINAL_APPLICATION, PANEL_IS_DITEM_EDITOR, panel_key_file_get_boolean(), panel_key_file_get_locale_string, panel_key_file_get_string, _PanelDItemEditor::priv, TRUE, and type.
Referenced by ask_about_launcher().
panel_ditem_register_save_uri_func()
void panel_ditem_register_save_uri_func (PanelDItemEditor * dialog, PanelDitemSaveUri save_uri, gpointer data)
Definition at line 1610 of file panel-ditem-editor.c.
References data, PANEL_IS_DITEM_EDITOR, and _PanelDItemEditor::priv.
Referenced by ask_about_launcher(), launcher_properties(), and main().