MATE Desktop Environment: panel-applet-frame-dbus.h File Reference
panel-applet-frame-dbus.h File Reference
#include <panel-applet-frame.h>
Classes
struct _MatePanelAppletFrameDBusClass
struct _MatePanelAppletFrameDBus
Macros
#define PANEL_TYPE_APPLET_FRAME_DBUS (mate_panel_applet_frame_dbus_get_type ())
#define MATE_PANEL_APPLET_FRAME_DBUS(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PANEL_TYPE_APPLET_FRAME_DBUS, MatePanelAppletFrameDBus))
#define MATE_PANEL_APPLET_FRAME_DBUS_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), PANEL_TYPE_APPLET_FRAME_DBUS, MatePanelAppletFrameDBusClass))
#define PANEL_IS_APPLET_FRAME_DBUS(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PANEL_TYPE_APPLET_FRAME_DBUS))
#define PANEL_IS_APPLET_FRAME_DBUS_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), PANEL_TYPE_APPLET_FRAME_DBUS))
#define MATE_PANEL_APPLET_FRAME_DBUS_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), PANEL_TYPE_APPLET_FRAME_DBUS, MatePanelAppletFrameDBusClass))
Typedefs
typedef struct _MatePanelAppletFrameDBus MatePanelAppletFrameDBus
typedef struct _MatePanelAppletFrameDBusClass MatePanelAppletFrameDBusClass
typedef struct _MatePanelAppletFrameDBusPrivate MatePanelAppletFrameDBusPrivate
Functions
GType mate_panel_applet_frame_dbus_get_type (void)
gboolean mate_panel_applet_frame_dbus_load (const gchar *iid, MatePanelAppletFrameActivating *frame_act)
Macro Definition Documentation
MATE_PANEL_APPLET_FRAME_DBUS
#define MATE_PANEL_APPLET_FRAME_DBUS (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PANEL_TYPE_APPLET_FRAME_DBUS, MatePanelAppletFrameDBus))
Definition at line 37 of file panel-applet-frame-dbus.h.
MATE_PANEL_APPLET_FRAME_DBUS_CLASS
#define MATE_PANEL_APPLET_FRAME_DBUS_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), PANEL_TYPE_APPLET_FRAME_DBUS, MatePanelAppletFrameDBusClass))
Definition at line 38 of file panel-applet-frame-dbus.h.
MATE_PANEL_APPLET_FRAME_DBUS_GET_CLASS
#define MATE_PANEL_APPLET_FRAME_DBUS_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), PANEL_TYPE_APPLET_FRAME_DBUS, MatePanelAppletFrameDBusClass))
Definition at line 41 of file panel-applet-frame-dbus.h.
PANEL_IS_APPLET_FRAME_DBUS
#define PANEL_IS_APPLET_FRAME_DBUS (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PANEL_TYPE_APPLET_FRAME_DBUS))
Definition at line 39 of file panel-applet-frame-dbus.h.
PANEL_IS_APPLET_FRAME_DBUS_CLASS
#define PANEL_IS_APPLET_FRAME_DBUS_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), PANEL_TYPE_APPLET_FRAME_DBUS))
Definition at line 40 of file panel-applet-frame-dbus.h.
PANEL_TYPE_APPLET_FRAME_DBUS
#define PANEL_TYPE_APPLET_FRAME_DBUS (mate_panel_applet_frame_dbus_get_type ())
Definition at line 36 of file panel-applet-frame-dbus.h.
Typedef Documentation
MatePanelAppletFrameDBus
typedef struct _MatePanelAppletFrameDBus MatePanelAppletFrameDBus
Definition at line 43 of file panel-applet-frame-dbus.h.
MatePanelAppletFrameDBusClass
typedef struct _MatePanelAppletFrameDBusClass MatePanelAppletFrameDBusClass
Definition at line 44 of file panel-applet-frame-dbus.h.
MatePanelAppletFrameDBusPrivate
typedef struct _MatePanelAppletFrameDBusPrivate MatePanelAppletFrameDBusPrivate
Definition at line 45 of file panel-applet-frame-dbus.h.
Function Documentation
mate_panel_applet_frame_dbus_get_type()
GType mate_panel_applet_frame_dbus_get_type (void)
mate_panel_applet_frame_dbus_load()
gboolean mate_panel_applet_frame_dbus_load (const gchar * iid, MatePanelAppletFrameActivating * frame_act)
Definition at line 405 of file panel-applet-frame-dbus.c.
References _mate_panel_applet_frame_set_iid(), FALSE, mate_panel_applet_container_add(), MATE_PANEL_APPLET_FRAME, mate_panel_applet_frame_activating_get_conf_path(), mate_panel_applet_frame_activating_get_locked(), mate_panel_applet_frame_activating_get_locked_down(), mate_panel_applet_frame_activating_get_orientation(), mate_panel_applet_frame_activating_get_size(), mate_panel_applets_manager_factory_activate(), NULL, panel_applet_frame_activating_get_screen(), PANEL_TYPE_APPLET_FRAME_DBUS, _MatePanelAppletFrameDBus::priv, and TRUE.