MATE Desktop Environment: panel-menu-items.h File Reference
panel-menu-items.h File Reference
#include <gtk/gtk.h>
#include "panel-widget.h"
#include <libmate-desktop/mate-image-menu-item.h>
Classes
struct _PanelPlaceMenuItem
struct _PanelPlaceMenuItemClass
struct _PanelDesktopMenuItem
struct _PanelDesktopMenuItemClass
Macros
#define PANEL_TYPE_PLACE_MENU_ITEM (panel_place_menu_item_get_type ())
#define PANEL_PLACE_MENU_ITEM(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PANEL_TYPE_PLACE_MENU_ITEM, PanelPlaceMenuItem))
#define PANEL_PLACE_MENU_ITEM_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), PANEL_TYPE_PLACE_MENU_ITEM, PanelPlaceMenuItemClass))
#define PANEL_IS_PLACE_MENU_ITEM(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PANEL_TYPE_PLACE_MENU_ITEM))
#define PANEL_IS_PLACE_MENU_ITEM_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), PANEL_TYPE_PLACE_MENU_ITEM))
#define PANEL_PLACE_MENU_ITEM_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), PANEL_TYPE_PLACE_MENU_ITEM, PanelPlaceMenuItemClass))
#define PANEL_TYPE_DESKTOP_MENU_ITEM (panel_desktop_menu_item_get_type ())
#define PANEL_DESKTOP_MENU_ITEM(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PANEL_TYPE_DESKTOP_MENU_ITEM, PanelDesktopMenuItem))
#define PANEL_DESKTOP_MENU_ITEM_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), PANEL_TYPE_DESKTOP_MENU_ITEM, PanelDesktopMenuItemClass))
#define PANEL_IS_DESKTOP_MENU_ITEM(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PANEL_TYPE_DESKTOP_MENU_ITEM))
#define PANEL_IS_DESKTOP_MENU_ITEM_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), PANEL_TYPE_DESKTOP_MENU_ITEM))
#define PANEL_DESKTOP_MENU_ITEM_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), PANEL_TYPE_DESKTOP_MENU_ITEM, PanelDesktopMenuItemClass))
Typedefs
typedef struct _PanelPlaceMenuItem PanelPlaceMenuItem
typedef struct _PanelPlaceMenuItemClass PanelPlaceMenuItemClass
typedef struct _PanelPlaceMenuItemPrivate PanelPlaceMenuItemPrivate
typedef struct _PanelDesktopMenuItem PanelDesktopMenuItem
typedef struct _PanelDesktopMenuItemClass PanelDesktopMenuItemClass
typedef struct _PanelDesktopMenuItemPrivate PanelDesktopMenuItemPrivate
Functions
GType panel_place_menu_item_get_type (void)
GType panel_desktop_menu_item_get_type (void)
GtkWidget * panel_place_menu_item_new (gboolean use_image)
GtkWidget * panel_desktop_menu_item_new (gboolean use_image, gboolean append_lock_logout)
void panel_place_menu_item_set_panel (GtkWidget *item, PanelWidget *panel)
void panel_desktop_menu_item_set_panel (GtkWidget *item, PanelWidget *panel)
void panel_menu_items_append_lock_logout (GtkWidget *menu)
void panel_menu_item_activate_desktop_file (GtkWidget *menuitem, const char *path)
Macro Definition Documentation
PANEL_DESKTOP_MENU_ITEM
#define PANEL_DESKTOP_MENU_ITEM (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PANEL_TYPE_DESKTOP_MENU_ITEM, PanelDesktopMenuItem))
Definition at line 59 of file panel-menu-items.h.
PANEL_DESKTOP_MENU_ITEM_CLASS
#define PANEL_DESKTOP_MENU_ITEM_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), PANEL_TYPE_DESKTOP_MENU_ITEM, PanelDesktopMenuItemClass))
Definition at line 60 of file panel-menu-items.h.
PANEL_DESKTOP_MENU_ITEM_GET_CLASS
#define PANEL_DESKTOP_MENU_ITEM_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), PANEL_TYPE_DESKTOP_MENU_ITEM, PanelDesktopMenuItemClass))
Definition at line 63 of file panel-menu-items.h.
PANEL_IS_DESKTOP_MENU_ITEM
#define PANEL_IS_DESKTOP_MENU_ITEM (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PANEL_TYPE_DESKTOP_MENU_ITEM))
Definition at line 61 of file panel-menu-items.h.
PANEL_IS_DESKTOP_MENU_ITEM_CLASS
#define PANEL_IS_DESKTOP_MENU_ITEM_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), PANEL_TYPE_DESKTOP_MENU_ITEM))
Definition at line 62 of file panel-menu-items.h.
PANEL_IS_PLACE_MENU_ITEM
#define PANEL_IS_PLACE_MENU_ITEM (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PANEL_TYPE_PLACE_MENU_ITEM))
Definition at line 38 of file panel-menu-items.h.
PANEL_IS_PLACE_MENU_ITEM_CLASS
#define PANEL_IS_PLACE_MENU_ITEM_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), PANEL_TYPE_PLACE_MENU_ITEM))
Definition at line 39 of file panel-menu-items.h.
PANEL_PLACE_MENU_ITEM
#define PANEL_PLACE_MENU_ITEM (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PANEL_TYPE_PLACE_MENU_ITEM, PanelPlaceMenuItem))
Definition at line 36 of file panel-menu-items.h.
PANEL_PLACE_MENU_ITEM_CLASS
#define PANEL_PLACE_MENU_ITEM_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), PANEL_TYPE_PLACE_MENU_ITEM, PanelPlaceMenuItemClass))
Definition at line 37 of file panel-menu-items.h.
PANEL_PLACE_MENU_ITEM_GET_CLASS
#define PANEL_PLACE_MENU_ITEM_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), PANEL_TYPE_PLACE_MENU_ITEM, PanelPlaceMenuItemClass))
Definition at line 40 of file panel-menu-items.h.
PANEL_TYPE_DESKTOP_MENU_ITEM
#define PANEL_TYPE_DESKTOP_MENU_ITEM (panel_desktop_menu_item_get_type ())
Definition at line 58 of file panel-menu-items.h.
PANEL_TYPE_PLACE_MENU_ITEM
#define PANEL_TYPE_PLACE_MENU_ITEM (panel_place_menu_item_get_type ())
Definition at line 35 of file panel-menu-items.h.
Typedef Documentation
PanelDesktopMenuItem
typedef struct _PanelDesktopMenuItem PanelDesktopMenuItem
Definition at line 65 of file panel-menu-items.h.
PanelDesktopMenuItemClass
typedef struct _PanelDesktopMenuItemClass PanelDesktopMenuItemClass
Definition at line 66 of file panel-menu-items.h.
PanelDesktopMenuItemPrivate
typedef struct _PanelDesktopMenuItemPrivate PanelDesktopMenuItemPrivate
Definition at line 67 of file panel-menu-items.h.
PanelPlaceMenuItem
typedef struct _PanelPlaceMenuItem PanelPlaceMenuItem
Definition at line 42 of file panel-menu-items.h.
PanelPlaceMenuItemClass
typedef struct _PanelPlaceMenuItemClass PanelPlaceMenuItemClass
Definition at line 43 of file panel-menu-items.h.
PanelPlaceMenuItemPrivate
typedef struct _PanelPlaceMenuItemPrivate PanelPlaceMenuItemPrivate
Definition at line 44 of file panel-menu-items.h.
Function Documentation
panel_desktop_menu_item_get_type()
GType panel_desktop_menu_item_get_type (void)
panel_desktop_menu_item_new()
GtkWidget * panel_desktop_menu_item_new (gboolean use_image, gboolean append_lock_logout)
Definition at line 1467 of file panel-menu-items.c.
References _, FALSE, NULL, panel_lockdown_notify_add(), panel_menu_icon_get_size(), PANEL_TYPE_DESKTOP_MENU_ITEM, _PanelDesktopMenuItem::priv, and setup_menuitem().
panel_desktop_menu_item_set_panel()
void panel_desktop_menu_item_set_panel (GtkWidget * item, PanelWidget * panel)
Definition at line 1514 of file panel-menu-items.c.
References item, mate_panel_applet_menu_set_recurse(), PANEL_DESKTOP_MENU_ITEM, and _PanelDesktopMenuItem::priv.
panel_menu_item_activate_desktop_file()
void panel_menu_item_activate_desktop_file (GtkWidget * menuitem, const char * path)
Definition at line 1617 of file panel-menu-items.c.
References menuitem_to_screen(), NULL, and panel_launch_desktop_file().
panel_menu_items_append_lock_logout()
void panel_menu_items_append_lock_logout (GtkWidget * menu)
Definition at line 1527 of file panel-menu-items.c.
References _, add_menu_separator(), C_, FALSE, item, label, NULL, PANEL_ACTION_LOCK, PANEL_ACTION_LOGOUT, PANEL_ACTION_SHUTDOWN, panel_lock_screen_action_available(), panel_lockdown_get_disable_log_out(), and TRUE.
panel_place_menu_item_get_type()
GType panel_place_menu_item_get_type (void)
panel_place_menu_item_new()
GtkWidget * panel_place_menu_item_new (gboolean use_image)
Definition at line 1440 of file panel-menu-items.c.
References _, FALSE, NULL, PANEL_ICON_FOLDER, panel_menu_icon_get_size(), PANEL_TYPE_PLACE_MENU_ITEM, _PanelPlaceMenuItem::priv, and setup_menuitem().
panel_place_menu_item_set_panel()
void panel_place_menu_item_set_panel (GtkWidget * item, PanelWidget * panel)
Definition at line 1501 of file panel-menu-items.c.
References item, mate_panel_applet_menu_set_recurse(), PANEL_PLACE_MENU_ITEM, and _PanelPlaceMenuItem::priv.