MATE Desktop Environment: panel-recent.c File Reference
panel-recent.c File Reference
#include <config.h>
#include <string.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <libmate-desktop/mate-image-menu-item.h>
#include <libpanel-util/panel-error.h>
#include <libpanel-util/panel-show.h>
#include <libpanel-util/panel-gtk.h>
#include "menu.h"
#include "panel-util.h"
#include "panel-globals.h"
#include "panel-recent.h"
#include "panel-stock-icons.h"
#include "panel-icon-names.h"
Functions
void panel_recent_append_documents_menu (GtkWidget *top_menu, GtkRecentManager *manager, int recent_items_limit)
Function Documentation
panel_recent_append_documents_menu()
void panel_recent_append_documents_menu (GtkWidget * top_menu, GtkRecentManager * manager, int recent_items_limit)
Definition at line 189 of file panel-recent.c.
References _, add_menu_separator(), FALSE, mate_image_menu_item_new(), menu_dummy_button_press_event(), NULL, PANEL_ICON_RECENT, panel_menu_icon_get_size(), panel_util_set_tooltip_text(), setup_menuitem_with_icon(), and TRUE.