MATE Desktop Environment: panel-applet-frame.h File Reference
panel-applet-frame.h File Reference
#include <gtk/gtk.h>
#include "panel-widget.h"
#include "applet.h"
Classes
struct _MatePanelAppletFrameClass
struct _MatePanelAppletFrame
Macros
#define PANEL_TYPE_APPLET_FRAME (mate_panel_applet_frame_get_type ())
#define MATE_PANEL_APPLET_FRAME(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PANEL_TYPE_APPLET_FRAME, MatePanelAppletFrame))
#define MATE_PANEL_APPLET_FRAME_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), PANEL_TYPE_APPLET_FRAME, MatePanelAppletFrameClass))
#define PANEL_IS_APPLET_FRAME(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PANEL_TYPE_APPLET_FRAME))
#define PANEL_IS_APPLET_FRAME_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), PANEL_TYPE_APPLET_FRAME))
#define MATE_PANEL_APPLET_FRAME_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), PANEL_TYPE_APPLET_FRAME, MatePanelAppletFrameClass))
Typedefs
typedef struct _MatePanelAppletFrame MatePanelAppletFrame
typedef struct _MatePanelAppletFrameClass MatePanelAppletFrameClass
typedef struct _MatePanelAppletFramePrivate MatePanelAppletFramePrivate
typedef struct _MatePanelAppletFrameActivating MatePanelAppletFrameActivating
Functions
GType mate_panel_applet_frame_get_type (void)
void mate_panel_applet_frame_create (PanelToplevel *toplevel, int position, const char *iid)
void mate_panel_applet_frame_load_from_gsettings (PanelWidget *panel_widget, gboolean locked, int position, const char *id)
void mate_panel_applet_frame_sync_menu_state (MatePanelAppletFrame *frame)
void mate_panel_applet_frame_change_orientation (MatePanelAppletFrame *frame, PanelOrientation orientation)
void mate_panel_applet_frame_change_size (MatePanelAppletFrame *frame, guint size)
void mate_panel_applet_frame_change_background (MatePanelAppletFrame *frame, PanelBackgroundType type)
void mate_panel_applet_frame_set_panel (MatePanelAppletFrame *frame, PanelWidget *panel)
GdkScreen * panel_applet_frame_activating_get_screen (MatePanelAppletFrameActivating *frame_act)
PanelOrientation mate_panel_applet_frame_activating_get_orientation (MatePanelAppletFrameActivating *frame_act)
guint32 mate_panel_applet_frame_activating_get_size (MatePanelAppletFrameActivating *frame_act)
gboolean mate_panel_applet_frame_activating_get_locked (MatePanelAppletFrameActivating *frame_act)
gboolean mate_panel_applet_frame_activating_get_locked_down (MatePanelAppletFrameActivating *frame_act)
gchar * mate_panel_applet_frame_activating_get_conf_path (MatePanelAppletFrameActivating *frame_act)
void _mate_panel_applet_frame_set_iid (MatePanelAppletFrame *frame, const gchar *iid)
void _mate_panel_applet_frame_activated (MatePanelAppletFrame *frame, MatePanelAppletFrameActivating *frame_act, GError *error)
void _mate_panel_applet_frame_update_flags (MatePanelAppletFrame *frame, gboolean major, gboolean minor, gboolean has_handle)
void _mate_panel_applet_frame_update_size_hints (MatePanelAppletFrame *frame, gint *size_hints, gsize n_elements)
char * _mate_panel_applet_frame_get_background_string (MatePanelAppletFrame *frame, PanelWidget *panel, PanelBackgroundType type)
void _mate_panel_applet_frame_applet_broken (MatePanelAppletFrame *frame)
void _mate_panel_applet_frame_applet_remove (MatePanelAppletFrame *frame)
void _mate_panel_applet_frame_applet_move (MatePanelAppletFrame *frame)
void _mate_panel_applet_frame_applet_lock (MatePanelAppletFrame *frame, gboolean locked)
Macro Definition Documentation
MATE_PANEL_APPLET_FRAME
#define MATE_PANEL_APPLET_FRAME (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PANEL_TYPE_APPLET_FRAME, MatePanelAppletFrame))
Definition at line 38 of file panel-applet-frame.h.
MATE_PANEL_APPLET_FRAME_CLASS
#define MATE_PANEL_APPLET_FRAME_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), PANEL_TYPE_APPLET_FRAME, MatePanelAppletFrameClass))
Definition at line 39 of file panel-applet-frame.h.
MATE_PANEL_APPLET_FRAME_GET_CLASS
#define MATE_PANEL_APPLET_FRAME_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), PANEL_TYPE_APPLET_FRAME, MatePanelAppletFrameClass))
Definition at line 42 of file panel-applet-frame.h.
PANEL_IS_APPLET_FRAME
#define PANEL_IS_APPLET_FRAME (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PANEL_TYPE_APPLET_FRAME))
Definition at line 40 of file panel-applet-frame.h.
PANEL_IS_APPLET_FRAME_CLASS
#define PANEL_IS_APPLET_FRAME_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), PANEL_TYPE_APPLET_FRAME))
Definition at line 41 of file panel-applet-frame.h.
PANEL_TYPE_APPLET_FRAME
#define PANEL_TYPE_APPLET_FRAME (mate_panel_applet_frame_get_type ())
Definition at line 37 of file panel-applet-frame.h.
Typedef Documentation
MatePanelAppletFrame
typedef struct _MatePanelAppletFrame MatePanelAppletFrame
Definition at line 44 of file panel-applet-frame.h.
MatePanelAppletFrameActivating
typedef struct _MatePanelAppletFrameActivating MatePanelAppletFrameActivating
Definition at line 107 of file panel-applet-frame.h.
MatePanelAppletFrameClass
typedef struct _MatePanelAppletFrameClass MatePanelAppletFrameClass
Definition at line 45 of file panel-applet-frame.h.
MatePanelAppletFramePrivate
typedef struct _MatePanelAppletFramePrivate MatePanelAppletFramePrivate
Definition at line 46 of file panel-applet-frame.h.
Function Documentation
_mate_panel_applet_frame_activated()
void _mate_panel_applet_frame_activated (MatePanelAppletFrame * frame, MatePanelAppletFrameActivating * frame_act, GError * error)
Definition at line 559 of file panel-applet-frame.c.
References error, mate_panel_applet_frame_sync_menu_state(), mate_panel_applet_register(), mate_panel_applet_stop_loading(), NULL, panel_lockdown_notify_add(), PANEL_OBJECT_APPLET, panel_widget_set_applet_size_constrained(), _MatePanelAppletFrame::priv, and TRUE.
_mate_panel_applet_frame_applet_broken()
void _mate_panel_applet_frame_applet_broken (MatePanelAppletFrame * frame)
Definition at line 739 of file panel-applet-frame.c.
References _, GDK_IS_X11_DISPLAY, is_using_x11(), mate_panel_applet_info_get_name(), mate_panel_applets_manager_get_applet_info(), NULL, panel_profile_id_lists_are_writable(), PANEL_RESPONSE_DELETE, PANEL_RESPONSE_DONT_RELOAD, PANEL_RESPONSE_RELOAD, panel_widget_register_open_dialog(), _MatePanelAppletFrame::priv, TRUE, and xstuff_is_display_dead().
_mate_panel_applet_frame_applet_lock()
void _mate_panel_applet_frame_applet_lock (MatePanelAppletFrame * frame, gboolean locked)
Definition at line 847 of file panel-applet-frame.c.
References mate_panel_applet_toggle_locked(), PANEL_WIDGET, panel_widget_get_applet_locked(), and _MatePanelAppletFrame::priv.
_mate_panel_applet_frame_applet_move()
void _mate_panel_applet_frame_applet_move (MatePanelAppletFrame * frame)
Definition at line 832 of file panel-applet-frame.c.
References PANEL_IS_WIDGET, PANEL_WIDGET, panel_widget_applet_drag_start(), and PW_DRAG_OFF_CENTER.
_mate_panel_applet_frame_applet_remove()
void _mate_panel_applet_frame_applet_remove (MatePanelAppletFrame * frame)
Definition at line 818 of file panel-applet-frame.c.
References NULL, panel_profile_delete_object(), and _MatePanelAppletFrame::priv.
_mate_panel_applet_frame_get_background_string()
char * _mate_panel_applet_frame_get_background_string (MatePanelAppletFrame * frame, PanelWidget * panel, PanelBackgroundType type)
_mate_panel_applet_frame_set_iid()
void _mate_panel_applet_frame_set_iid (MatePanelAppletFrame * frame, const gchar * iid)
Definition at line 551 of file panel-applet-frame.c.
References _MatePanelAppletFrame::priv.
Referenced by mate_panel_applet_frame_dbus_load().
_mate_panel_applet_frame_update_flags()
void _mate_panel_applet_frame_update_flags (MatePanelAppletFrame * frame, gboolean major, gboolean minor, gboolean has_handle)
Definition at line 605 of file panel-applet-frame.c.
References FALSE, mate_panel_applet_frame_change_background(), panel_widget_set_applet_expandable(), _MatePanelAppletFrame::priv, and _PanelBackground::type.
_mate_panel_applet_frame_update_size_hints()
void _mate_panel_applet_frame_update_size_hints (MatePanelAppletFrame * frame, gint * size_hints, gsize n_elements)
Definition at line 629 of file panel-applet-frame.c.
References HANDLE_SIZE, panel_widget_set_applet_size_hints(), and _MatePanelAppletFrame::priv.
mate_panel_applet_frame_activating_get_conf_path()
gchar * mate_panel_applet_frame_activating_get_conf_path (MatePanelAppletFrameActivating * frame_act)
Definition at line 905 of file panel-applet-frame.c.
References MATE_PANEL_APPLET_PREFS_PATH.
Referenced by mate_panel_applet_frame_dbus_load().
mate_panel_applet_frame_activating_get_locked()
gboolean mate_panel_applet_frame_activating_get_locked (MatePanelAppletFrameActivating * frame_act)
Definition at line 893 of file panel-applet-frame.c.
Referenced by mate_panel_applet_frame_dbus_load().
mate_panel_applet_frame_activating_get_locked_down()
gboolean mate_panel_applet_frame_activating_get_locked_down (MatePanelAppletFrameActivating * frame_act)
Definition at line 899 of file panel-applet-frame.c.
References panel_lockdown_get_locked_down().
Referenced by mate_panel_applet_frame_dbus_load().
mate_panel_applet_frame_activating_get_orientation()
PanelOrientation mate_panel_applet_frame_activating_get_orientation (MatePanelAppletFrameActivating * frame_act)
Definition at line 881 of file panel-applet-frame.c.
References panel_widget_get_applet_orientation().
Referenced by mate_panel_applet_frame_dbus_load().
mate_panel_applet_frame_activating_get_size()
guint32 mate_panel_applet_frame_activating_get_size (MatePanelAppletFrameActivating * frame_act)
Definition at line 887 of file panel-applet-frame.c.
Referenced by mate_panel_applet_frame_dbus_load().
mate_panel_applet_frame_change_background()
void mate_panel_applet_frame_change_background (MatePanelAppletFrame * frame, PanelBackgroundType type)
Definition at line 520 of file panel-applet-frame.c.
References MATE_PANEL_APPLET_FRAME_GET_CLASS, panel_background_apply_css(), PANEL_IS_APPLET_FRAME, PANEL_IS_WIDGET, PANEL_WIDGET, _MatePanelAppletFrame::priv, and type.
Referenced by _mate_panel_applet_frame_update_flags(), and back_change().
mate_panel_applet_frame_change_orientation()
void mate_panel_applet_frame_change_orientation (MatePanelAppletFrame * frame, PanelOrientation orientation)
Definition at line 502 of file panel-applet-frame.c.
References MATE_PANEL_APPLET_FRAME_GET_CLASS, and _MatePanelAppletFrame::priv.
Referenced by orientation_change().
mate_panel_applet_frame_change_size()
void mate_panel_applet_frame_change_size (MatePanelAppletFrame * frame, guint size)
Definition at line 513 of file panel-applet-frame.c.
References MATE_PANEL_APPLET_FRAME_GET_CLASS.
Referenced by size_change().
mate_panel_applet_frame_create()
void mate_panel_applet_frame_create (PanelToplevel * toplevel, int position, const char * iid)
Definition at line 1066 of file panel-applet-frame.c.
References FALSE, id, NULL, PANEL_GSETTINGS_OBJECTS, PANEL_OBJECT_APPLET, PANEL_OBJECT_APPLET_IID_KEY, PANEL_OBJECT_PATH, PANEL_OBJECT_SCHEMA, panel_profile_add_to_list(), and panel_profile_prepare_object().
Referenced by panel_receive_dnd_data().
mate_panel_applet_frame_get_type()
GType mate_panel_applet_frame_get_type (void)
mate_panel_applet_frame_load_from_gsettings()
void mate_panel_applet_frame_load_from_gsettings (PanelWidget * panel_widget, gboolean locked, int position, const char * id)
Definition at line 1036 of file panel-applet-frame.c.
References mate_panel_applet_stop_loading(), NULL, PANEL_OBJECT_APPLET_IID_KEY, PANEL_OBJECT_PATH, PANEL_OBJECT_SCHEMA, and TRUE.
mate_panel_applet_frame_set_panel()
void mate_panel_applet_frame_set_panel (MatePanelAppletFrame * frame, PanelWidget * panel)
Definition at line 541 of file panel-applet-frame.c.
References PANEL_IS_APPLET_FRAME, PANEL_IS_WIDGET, and _MatePanelAppletFrame::priv.
Referenced by panel_widget_reparent().
mate_panel_applet_frame_sync_menu_state()
void mate_panel_applet_frame_sync_menu_state (MatePanelAppletFrame * frame)
Definition at line 480 of file panel-applet-frame.c.
References mate_panel_applet_can_freely_move(), MATE_PANEL_APPLET_FRAME_GET_CLASS, mate_panel_applet_lockable(), panel_lockdown_get_locked_down(), panel_profile_id_lists_are_writable(), PANEL_WIDGET, panel_widget_get_applet_locked(), and _MatePanelAppletFrame::priv.
Referenced by _mate_panel_applet_frame_activated().
panel_applet_frame_activating_get_screen()
GdkScreen * panel_applet_frame_activating_get_screen (MatePanelAppletFrameActivating * frame_act)
Definition at line 875 of file panel-applet-frame.c.
Referenced by mate_panel_applet_frame_dbus_load().