MATE Desktop Environment: panel-menu-button.c File Reference
panel-menu-button.c File Reference
#include <config.h>
#include "panel-menu-button.h"
#include <string.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <matemenu-tree.h>
#include <libpanel-util/panel-error.h>
#include <libpanel-util/panel-launch.h>
#include <libpanel-util/panel-show.h>
#include "applet.h"
#include "panel-widget.h"
#include "panel-util.h"
#include "panel-profile.h"
#include "panel-globals.h"
#include "menu.h"
#include "panel-lockdown.h"
#include "panel-a11y.h"
#include "panel-icon-names.h"
#include "panel-schemas.h"
Macros
#define DEFAULT_MENU APPLICATIONS_MENU
#define PANEL_IS_MENU_BUTTON_ACCESSIBLE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), panel_menu_button_accessible_get_type ()))
Enumerations
enum {
PROP_0 , PROP_MENU_PATH , PROP_CUSTOM_ICON , PROP_TOOLTIP ,
PROP_USE_MENU_PATH , PROP_USE_CUSTOM_ICON , PROP_HAS_ARROW , PROP_DND_ENABLED
}
enum MenuPathRoot { FIRST_MENU , APPLICATIONS_MENU , SETTINGS_MENU , LAST_MENU }
Functions
void panel_menu_button_popup_menu (PanelMenuButton *button, guint n_button, guint32 activate_time)
void panel_menu_button_set_menu_path (PanelMenuButton *button, const char *menu_uri)
void panel_menu_button_set_custom_icon (PanelMenuButton *button, const char *custom_icon)
void panel_menu_button_set_tooltip (PanelMenuButton *button, const char *tooltip)
void panel_menu_button_set_use_menu_path (PanelMenuButton *button, gboolean use_menu_path)
gboolean panel_menu_button_get_use_menu_path (PanelMenuButton *button)
void panel_menu_button_set_use_custom_icon (PanelMenuButton *button, gboolean use_custom_icon)
void panel_menu_button_set_has_arrow (PanelMenuButton *button, gboolean has_arrow)
void panel_menu_button_load_from_gsettings (PanelWidget *panel, gboolean locked, int position, gboolean exactpos, const char *id)
gboolean panel_menu_button_create (PanelToplevel *toplevel, int position, const char *filename, const char *menu_path, gboolean use_menu_path, const char *tooltip)
void panel_menu_button_invoke_menu (PanelMenuButton *button, const char *callback_name)
void panel_menu_button_set_dnd_enabled (PanelMenuButton *button, gboolean dnd_enabled)
Macro Definition Documentation
DEFAULT_MENU
#define DEFAULT_MENU APPLICATIONS_MENU
Definition at line 65 of file panel-menu-button.c.
PANEL_IS_MENU_BUTTON_ACCESSIBLE
#define PANEL_IS_MENU_BUTTON_ACCESSIBLE (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), panel_menu_button_accessible_get_type ()))
Definition at line 1079 of file panel-menu-button.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_MENU_PATH
PROP_CUSTOM_ICON
PROP_TOOLTIP
PROP_USE_MENU_PATH
PROP_USE_CUSTOM_ICON
PROP_HAS_ARROW
PROP_DND_ENABLED
Definition at line 51 of file panel-menu-button.c.
MenuPathRoot
enum MenuPathRoot
Enumerator
FIRST_MENU
APPLICATIONS_MENU
SETTINGS_MENU
LAST_MENU
Definition at line 62 of file panel-menu-button.c.
Function Documentation
panel_menu_button_create()
gboolean panel_menu_button_create (PanelToplevel * toplevel, int position, const char * filename, const char * menu_path, gboolean use_menu_path, const char * tooltip)
Definition at line 960 of file panel-menu-button.c.
References FALSE, id, NULL, PANEL_GSETTINGS_OBJECTS, PANEL_OBJECT_MENU, PANEL_OBJECT_MENU_PATH_KEY, PANEL_OBJECT_PATH, PANEL_OBJECT_SCHEMA, PANEL_OBJECT_TOOLTIP_KEY, PANEL_OBJECT_USE_MENU_PATH_KEY, panel_profile_add_to_list(), panel_profile_prepare_object(), and TRUE.
panel_menu_button_get_use_menu_path()
gboolean panel_menu_button_get_use_menu_path (PanelMenuButton * button)
Definition at line 885 of file panel-menu-button.c.
References FALSE, PANEL_IS_MENU_BUTTON, and _PanelMenuButton::priv.
panel_menu_button_invoke_menu()
void panel_menu_button_invoke_menu (PanelMenuButton * button, const char * callback_name)
Definition at line 1009 of file panel-menu-button.c.
References NULL, PANEL_IS_MENU_BUTTON, panel_is_program_in_path(), panel_launch_desktop_file_with_fallback(), and panel_show_help().
panel_menu_button_load_from_gsettings()
void panel_menu_button_load_from_gsettings (PanelWidget * panel, gboolean locked, int position, gboolean exactpos, const char * id)
Definition at line 915 of file panel-menu-button.c.
References PANEL_OBJECT_CUSTOM_ICON_KEY, PANEL_OBJECT_HAS_ARROW_KEY, PANEL_OBJECT_MENU_PATH_KEY, PANEL_OBJECT_PATH, PANEL_OBJECT_SCHEMA, PANEL_OBJECT_TOOLTIP_KEY, PANEL_OBJECT_USE_CUSTOM_ICON_KEY, and PANEL_OBJECT_USE_MENU_PATH_KEY.
panel_menu_button_popup_menu()
void panel_menu_button_popup_menu (PanelMenuButton * button, guint n_button, guint32 activate_time)
Definition at line 437 of file panel-menu-button.c.
References BUTTON_WIDGET, button_widget_set_ignore_leave(), NULL, PANEL_IS_MENU_BUTTON, PANEL_ORIENTATION_BOTTOM, PANEL_ORIENTATION_LEFT, PANEL_ORIENTATION_RIGHT, PANEL_ORIENTATION_TOP, panel_toplevel_get_orientation(), panel_toplevel_push_autohide_disabler(), _PanelMenuButton::priv, and TRUE.
panel_menu_button_set_custom_icon()
void panel_menu_button_set_custom_icon (PanelMenuButton * button, const char * custom_icon)
Definition at line 834 of file panel-menu-button.c.
References NULL, PANEL_IS_MENU_BUTTON, and _PanelMenuButton::priv.
panel_menu_button_set_dnd_enabled()
void panel_menu_button_set_dnd_enabled (PanelMenuButton * button, gboolean dnd_enabled)
Definition at line 1036 of file panel-menu-button.c.
References FALSE, NULL, PANEL_IS_MENU_BUTTON, _PanelMenuButton::priv, and TRUE.
panel_menu_button_set_has_arrow()
void panel_menu_button_set_has_arrow (PanelMenuButton * button, gboolean has_arrow)
Definition at line 904 of file panel-menu-button.c.
References BUTTON_WIDGET, button_widget_set_has_arrow(), FALSE, PANEL_IS_MENU_BUTTON, and _PanelMenuButton::priv.
panel_menu_button_set_menu_path()
void panel_menu_button_set_menu_path (PanelMenuButton * button, const char * menu_uri)
Definition at line 799 of file panel-menu-button.c.
References NULL, PANEL_IS_MENU_BUTTON, and _PanelMenuButton::priv.
panel_menu_button_set_tooltip()
void panel_menu_button_set_tooltip (PanelMenuButton * button, const char * tooltip)
Definition at line 849 of file panel-menu-button.c.
References NULL, PANEL_IS_MENU_BUTTON, panel_util_set_tooltip_text(), and _PanelMenuButton::priv.
panel_menu_button_set_use_custom_icon()
void panel_menu_button_set_use_custom_icon (PanelMenuButton * button, gboolean use_custom_icon)
Definition at line 893 of file panel-menu-button.c.
References FALSE, PANEL_IS_MENU_BUTTON, and _PanelMenuButton::priv.
panel_menu_button_set_use_menu_path()
void panel_menu_button_set_use_menu_path (PanelMenuButton * button, gboolean use_menu_path)
Definition at line 864 of file panel-menu-button.c.
References FALSE, NULL, PANEL_IS_MENU_BUTTON, and _PanelMenuButton::priv.