MATE Desktop Environment: panel-background.h File Reference
panel-background.h File Reference
#include <config.h>
#include <glib.h>
#include <gtk/gtk.h>
#include "panel-enums.h"
#include "panel-types.h"
Classes
struct _PanelBackground
Typedefs
typedef struct _PanelBackground PanelBackground
typedef void(* PanelBackgroundChangedNotify) (PanelBackground *background, gpointer user_data)
Functions
void panel_background_init (PanelBackground *background, PanelBackgroundChangedNotify notify_changed, gpointer user_data)
void panel_background_free (PanelBackground *background)
void panel_background_set (PanelBackground *background, PanelBackgroundType type, const GdkRGBA *color, const char *image, gboolean fit_image, gboolean stretch_image, gboolean rotate_image)
void panel_background_set_type (PanelBackground *background, PanelBackgroundType type)
void panel_background_set_color (PanelBackground *background, const GdkRGBA *color)
void panel_background_set_image (PanelBackground *background, const char *image)
void panel_background_set_fit (PanelBackground *background, gboolean fit_image)
void panel_background_set_stretch (PanelBackground *background, gboolean stretch_image)
void panel_background_set_rotate (PanelBackground *background, gboolean rotate_image)
void panel_background_set_default_style (PanelBackground *background, const GdkRGBA *color, cairo_pattern_t *pattern)
void panel_background_realized (PanelBackground *background, GdkWindow *window)
void panel_background_unrealized (PanelBackground *background)
void panel_background_change_region (PanelBackground *background, GtkOrientation orientation, int x, int y, int width, int height)
char * panel_background_make_string (PanelBackground *background, int x, int y)
PanelBackgroundType panel_background_get_type (PanelBackground *background)
const GdkRGBA * panel_background_get_color (PanelBackground *background)
PanelBackgroundType panel_background_effective_type (PanelBackground *background)
void panel_background_apply_css (PanelBackground *background, GtkWidget *widget)
Typedef Documentation
PanelBackground
typedef struct _PanelBackground PanelBackground
Definition at line 37 of file panel-background.h.
PanelBackgroundChangedNotify
typedef void(* PanelBackgroundChangedNotify) (PanelBackground *background, gpointer user_data)
Definition at line 39 of file panel-background.h.
Function Documentation
panel_background_apply_css()
void panel_background_apply_css (PanelBackground * background, GtkWidget * widget)
Definition at line 45 of file panel-background.c.
References PANEL_BACK_COLOR, PANEL_BACK_IMAGE, PANEL_BACK_NONE, and panel_background_effective_type().
Referenced by mate_panel_applet_frame_change_background(), panel_menu_bar_change_background(), and panel_separator_change_background().
panel_background_change_region()
void panel_background_change_region (PanelBackground * background, GtkOrientation orientation, int x, int y, int width, int height)
Definition at line 644 of file panel-background.c.
References _PanelBackground::composited, FALSE, _PanelBackground::fit_image, _PanelBackground::has_alpha, _PanelBackground::orientation, PANEL_BACK_IMAGE, _PanelBackground::region, _PanelBackground::rotate_image, _PanelBackground::stretch_image, _PanelBackground::transformed, TRUE, and _PanelBackground::type.
panel_background_effective_type()
PanelBackgroundType panel_background_effective_type (PanelBackground * background)
Definition at line 822 of file panel-background.c.
References _PanelBackground::composited_pattern, PANEL_BACK_IMAGE, PANEL_BACK_NONE, and _PanelBackground::type.
Referenced by panel_background_apply_css().
panel_background_free()
void panel_background_free (PanelBackground * background)
Definition at line 752 of file panel-background.c.
References _PanelBackground::default_pattern, _PanelBackground::image, _PanelBackground::loaded_image, NULL, and _PanelBackground::window.
panel_background_get_color()
const GdkRGBA * panel_background_get_color (PanelBackground * background)
Definition at line 812 of file panel-background.c.
References _PanelBackground::color.
panel_background_get_type()
PanelBackgroundType panel_background_get_type (PanelBackground * background)
Definition at line 806 of file panel-background.c.
References _PanelBackground::type.
panel_background_init()
void panel_background_init (PanelBackground * background, PanelBackgroundChangedNotify notify_changed, gpointer user_data)
Definition at line 708 of file panel-background.c.
References _PanelBackground::color, _PanelBackground::composited, _PanelBackground::composited_pattern, _PanelBackground::default_color, _PanelBackground::default_pattern, FALSE, _PanelBackground::fit_image, _PanelBackground::has_alpha, _PanelBackground::image, _PanelBackground::loaded_image, _PanelBackground::notify_changed, NULL, _PanelBackground::orientation, PANEL_BACK_NONE, _PanelBackground::region, _PanelBackground::rotate_image, _PanelBackground::stretch_image, _PanelBackground::transformed, _PanelBackground::transformed_image, _PanelBackground::type, _PanelBackground::user_data, user_data, and _PanelBackground::window.
panel_background_make_string()
char * panel_background_make_string (PanelBackground * background, int x, int y)
panel_background_realized()
void panel_background_realized (PanelBackground * background, GdkWindow * window)
Definition at line 620 of file panel-background.c.
References NULL, and _PanelBackground::window.
panel_background_set()
void panel_background_set (PanelBackground * background, PanelBackgroundType type, const GdkRGBA * color, const char * image, gboolean fit_image, gboolean stretch_image, gboolean rotate_image)
Definition at line 583 of file panel-background.c.
References panel_background_set_type(), and type.
panel_background_set_color()
void panel_background_set_color (PanelBackground * background, const GdkRGBA * color)
Definition at line 476 of file panel-background.c.
References _PanelBackground::color, and NULL.
panel_background_set_default_style()
void panel_background_set_default_style (PanelBackground * background, const GdkRGBA * color, cairo_pattern_t * pattern)
Definition at line 600 of file panel-background.c.
References _PanelBackground::default_color, _PanelBackground::default_pattern, NULL, PANEL_BACK_NONE, and _PanelBackground::type.
panel_background_set_fit()
void panel_background_set_fit (PanelBackground * background, gboolean fit_image)
Definition at line 527 of file panel-background.c.
References FALSE, and _PanelBackground::fit_image.
panel_background_set_image()
void panel_background_set_image (PanelBackground * background, const char * image)
Definition at line 505 of file panel-background.c.
References _PanelBackground::image.
panel_background_set_rotate()
void panel_background_set_rotate (PanelBackground * background, gboolean rotate_image)
Definition at line 569 of file panel-background.c.
References FALSE, and _PanelBackground::rotate_image.
panel_background_set_stretch()
void panel_background_set_stretch (PanelBackground * background, gboolean stretch_image)
Definition at line 548 of file panel-background.c.
References FALSE, and _PanelBackground::stretch_image.
panel_background_set_type()
void panel_background_set_type (PanelBackground * background, PanelBackgroundType type)
Definition at line 447 of file panel-background.c.
References _PanelBackground::type, and type.
Referenced by panel_background_set().
panel_background_unrealized()
void panel_background_unrealized (PanelBackground * background)
Definition at line 636 of file panel-background.c.
References NULL, and _PanelBackground::window.