MATE Desktop Environment: panel-ditem-editor.h File Reference
panel-ditem-editor.h File Reference
#include <gtk/gtk.h>
Classes
struct _PanelDItemEditorClass
struct _PanelDItemEditor
Macros
#define PANEL_TYPE_DITEM_EDITOR (panel_ditem_editor_get_type ())
#define PANEL_DITEM_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PANEL_TYPE_DITEM_EDITOR, PanelDItemEditor))
#define PANEL_DITEM_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PANEL_TYPE_DITEM_EDITOR, PanelDItemEditorClass))
#define PANEL_IS_DITEM_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PANEL_TYPE_DITEM_EDITOR))
#define PANEL_IS_DITEM_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PANEL_TYPE_DITEM_EDITOR))
#define PANEL_DITEM_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PANEL_TYPE_DITEM_EDITOR, PanelDItemEditorClass))
Typedefs
typedef struct _PanelDItemEditor PanelDItemEditor
typedef struct _PanelDItemEditorClass PanelDItemEditorClass
typedef struct _PanelDItemEditorPrivate PanelDItemEditorPrivate
typedef char *(* PanelDitemSaveUri) (PanelDItemEditor *dialog, gpointer data)
Functions
GType panel_ditem_editor_get_type (void)
GtkWidget * panel_ditem_editor_new (GtkWindow *parent, GKeyFile *key_file, const char *uri, const char *title)
GtkWidget * panel_ditem_editor_new_directory (GtkWindow *parent, GKeyFile *key_file, const char *uri, const char *title)
void panel_ditem_editor_sync_display (PanelDItemEditor *dialog)
GKeyFile * panel_ditem_editor_get_key_file (PanelDItemEditor *dialog)
GKeyFile * panel_ditem_editor_get_revert_key_file (PanelDItemEditor *dialog)
void panel_ditem_editor_set_uri (PanelDItemEditor *dialog, const char *uri)
const char * panel_ditem_editor_get_uri (PanelDItemEditor *dialog)
void panel_ditem_register_save_uri_func (PanelDItemEditor *dialog, PanelDitemSaveUri save_uri, gpointer data)
Macro Definition Documentation
PANEL_DITEM_EDITOR
#define PANEL_DITEM_EDITOR (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PANEL_TYPE_DITEM_EDITOR, PanelDItemEditor))
Definition at line 36 of file panel-ditem-editor.h.
PANEL_DITEM_EDITOR_CLASS
#define PANEL_DITEM_EDITOR_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PANEL_TYPE_DITEM_EDITOR, PanelDItemEditorClass))
Definition at line 37 of file panel-ditem-editor.h.
PANEL_DITEM_EDITOR_GET_CLASS
#define PANEL_DITEM_EDITOR_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PANEL_TYPE_DITEM_EDITOR, PanelDItemEditorClass))
Definition at line 40 of file panel-ditem-editor.h.
PANEL_IS_DITEM_EDITOR
#define PANEL_IS_DITEM_EDITOR (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PANEL_TYPE_DITEM_EDITOR))
Definition at line 38 of file panel-ditem-editor.h.
PANEL_IS_DITEM_EDITOR_CLASS
#define PANEL_IS_DITEM_EDITOR_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PANEL_TYPE_DITEM_EDITOR))
Definition at line 39 of file panel-ditem-editor.h.
PANEL_TYPE_DITEM_EDITOR
#define PANEL_TYPE_DITEM_EDITOR (panel_ditem_editor_get_type ())
Definition at line 35 of file panel-ditem-editor.h.
Typedef Documentation
PanelDItemEditor
typedef struct _PanelDItemEditor PanelDItemEditor
Definition at line 42 of file panel-ditem-editor.h.
PanelDItemEditorClass
typedef struct _PanelDItemEditorClass PanelDItemEditorClass
Definition at line 43 of file panel-ditem-editor.h.
PanelDItemEditorPrivate
typedef struct _PanelDItemEditorPrivate PanelDItemEditorPrivate
Definition at line 45 of file panel-ditem-editor.h.
PanelDitemSaveUri
typedef char *(* PanelDitemSaveUri) (PanelDItemEditor *dialog, gpointer data)
Definition at line 84 of file panel-ditem-editor.h.
Function Documentation
panel_ditem_editor_get_key_file()
GKeyFile * panel_ditem_editor_get_key_file (PanelDItemEditor * dialog)
Definition at line 1579 of file panel-ditem-editor.c.
References NULL, PANEL_IS_DITEM_EDITOR, and _PanelDItemEditor::priv.
Referenced by ask_about_launcher().
panel_ditem_editor_get_revert_key_file()
GKeyFile * panel_ditem_editor_get_revert_key_file (PanelDItemEditor * dialog)
Definition at line 1587 of file panel-ditem-editor.c.
References NULL, PANEL_IS_DITEM_EDITOR, and _PanelDItemEditor::priv.
panel_ditem_editor_get_type()
GType panel_ditem_editor_get_type (void)
panel_ditem_editor_get_uri()
const char * panel_ditem_editor_get_uri (PanelDItemEditor * dialog)
Definition at line 1594 of file panel-ditem-editor.c.
References NULL, PANEL_IS_DITEM_EDITOR, and _PanelDItemEditor::priv.
panel_ditem_editor_new()
GtkWidget * panel_ditem_editor_new (GtkWindow * parent, GKeyFile * key_file, const char * uri, const char * title)
Definition at line 1507 of file panel-ditem-editor.c.
References FALSE.
Referenced by ask_about_launcher(), launcher_properties(), and main().
panel_ditem_editor_new_directory()
GtkWidget * panel_ditem_editor_new_directory (GtkWindow * parent, GKeyFile * key_file, const char * uri, const char * title)
Definition at line 1517 of file panel-ditem-editor.c.
References TRUE.
Referenced by main().
panel_ditem_editor_set_uri()
void panel_ditem_editor_set_uri (PanelDItemEditor * dialog, const char * uri)
Definition at line 1543 of file panel-ditem-editor.c.
References NULL, PANEL_IS_DITEM_EDITOR, and _PanelDItemEditor::priv.
panel_ditem_editor_sync_display()
void panel_ditem_editor_sync_display (PanelDItemEditor * dialog)
Definition at line 1069 of file panel-ditem-editor.c.
References COLUMN_TYPE, FALSE, NULL, PANEL_DITEM_EDITOR_TYPE_APPLICATION, PANEL_DITEM_EDITOR_TYPE_LINK, PANEL_DITEM_EDITOR_TYPE_NULL, PANEL_DITEM_EDITOR_TYPE_TERMINAL_APPLICATION, PANEL_IS_DITEM_EDITOR, panel_key_file_get_boolean(), panel_key_file_get_locale_string, panel_key_file_get_string, _PanelDItemEditor::priv, TRUE, and type.
Referenced by ask_about_launcher().
panel_ditem_register_save_uri_func()
void panel_ditem_register_save_uri_func (PanelDItemEditor * dialog, PanelDitemSaveUri save_uri, gpointer data)
Definition at line 1610 of file panel-ditem-editor.c.
References data, PANEL_IS_DITEM_EDITOR, and _PanelDItemEditor::priv.
Referenced by ask_about_launcher(), launcher_properties(), and main().