MATE Desktop Environment: panel-action-button.c File Reference
panel-action-button.c File Reference
#include <config.h>
#include <string.h>
#include <stdlib.h>
#include "panel-action-button.h"
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <libmate-desktop/mate-desktop-utils.h>
#include <libmate-desktop/mate-gsettings.h>
#include <libpanel-util/panel-error.h>
#include <libpanel-util/panel-launch.h>
#include <libpanel-util/panel-session-manager.h>
#include <libpanel-util/panel-show.h>
#include "applet.h"
#include "panel-config-global.h"
#include "panel-profile.h"
#include "panel-typebuiltins.h"
#include "panel-util.h"
#include "panel-session.h"
#include "panel-globals.h"
#include "panel-run-dialog.h"
#include "panel-a11y.h"
#include "panel-lockdown.h"
#include "panel-icon-names.h"
#include "panel-schemas.h"
Macros
#define MATE_DESKTOP_USE_UNSTABLE_API
#define GDK_IS_X11_DISPLAY(object) !(G_TYPE_CHECK_INSTANCE_TYPE ((object), GDK_TYPE_WAYLAND_DISPLAY))
Enumerations
enum { PROP_0 , PROP_ACTION_TYPE , PROP_DND_ENABLED }
Functions
gboolean panel_action_get_is_disabled (PanelActionButtonType type)
GCallback panel_action_get_invoke (PanelActionButtonType type)
const char * panel_action_get_icon_name (PanelActionButtonType type)
const char * panel_action_get_text (PanelActionButtonType type)
const char * panel_action_get_tooltip (PanelActionButtonType type)
const char * panel_action_get_drag_id (PanelActionButtonType type)
void panel_action_button_set_type (PanelActionButton *button, PanelActionButtonType type)
void panel_action_button_create (PanelToplevel *toplevel, int position, PanelActionButtonType type)
void panel_action_button_load_from_gsettings (PanelWidget *panel, gboolean locked, int position, gboolean exactpos, const char *id)
void panel_action_button_invoke_menu (PanelActionButton *button, const char *callback_name)
gboolean panel_action_button_load_from_drag (PanelToplevel *toplevel, int position, const char *drag_string, int *old_applet_idx)
void panel_action_button_set_dnd_enabled (PanelActionButton *button, gboolean enabled)
Macro Definition Documentation
GDK_IS_X11_DISPLAY
#define GDK_IS_X11_DISPLAY (object) !(G_TYPE_CHECK_INSTANCE_TYPE ((object), GDK_TYPE_WAYLAND_DISPLAY))
Definition at line 69 of file panel-action-button.c.
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 37 of file panel-action-button.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_ACTION_TYPE
PROP_DND_ENABLED
Definition at line 72 of file panel-action-button.c.
Function Documentation
panel_action_button_create()
void panel_action_button_create (PanelToplevel * toplevel, int position, PanelActionButtonType type)
Definition at line 938 of file panel-action-button.c.
References FALSE, id, PANEL_GSETTINGS_OBJECTS, PANEL_OBJECT_ACTION, PANEL_OBJECT_ACTION_TYPE_KEY, PANEL_OBJECT_PATH, PANEL_OBJECT_SCHEMA, panel_profile_add_to_list(), panel_profile_prepare_object(), and type.
Referenced by panel_action_button_load_from_drag().
panel_action_button_invoke_menu()
void panel_action_button_invoke_menu (PanelActionButton * button, const char * callback_name)
Definition at line 986 of file panel-action-button.c.
References NULL, PANEL_ACTION_LAST, PANEL_ACTION_NONE, PANEL_IS_ACTION_BUTTON, panel_show_help(), and _PanelActionButton::priv.
panel_action_button_load_from_drag()
gboolean panel_action_button_load_from_drag (PanelToplevel * toplevel, int position, const char * drag_string, int * old_applet_idx)
Definition at line 1013 of file panel-action-button.c.
References FALSE, NULL, panel_action_button_create(), PANEL_ACTION_LAST, PANEL_ACTION_NONE, TRUE, and type.
panel_action_button_load_from_gsettings()
void panel_action_button_load_from_gsettings (PanelWidget * panel, gboolean locked, int position, gboolean exactpos, const char * id)
Definition at line 963 of file panel-action-button.c.
References PANEL_OBJECT_ACTION_TYPE_KEY, PANEL_OBJECT_PATH, PANEL_OBJECT_SCHEMA, and type.
panel_action_button_set_dnd_enabled()
void panel_action_button_set_dnd_enabled (PanelActionButton * button, gboolean enabled)
Definition at line 1054 of file panel-action-button.c.
References FALSE, NULL, PANEL_IS_ACTION_BUTTON, _PanelActionButton::priv, and TRUE.
panel_action_button_set_type()
void panel_action_button_set_type (PanelActionButton * button, PanelActionButtonType type)
Definition at line 833 of file panel-action-button.c.
References _, BUTTON_WIDGET, button_widget_set_icon_name(), NULL, panel_a11y_set_atk_name_desc(), PANEL_ACTION_LAST, PANEL_ACTION_NONE, panel_util_set_tooltip_text(), _PanelActionButton::priv, and type.
panel_action_get_drag_id()
const char * panel_action_get_drag_id (PanelActionButtonType type)
Definition at line 648 of file panel-action-button.c.
References NULL, PANEL_ACTION_LAST, PANEL_ACTION_NONE, and type.
Referenced by setup_internal_applet_drag().
panel_action_get_icon_name()
const char * panel_action_get_icon_name (PanelActionButtonType type)
Definition at line 627 of file panel-action-button.c.
References NULL, PANEL_ACTION_LAST, PANEL_ACTION_NONE, and type.
Referenced by setup_internal_applet_drag().
panel_action_get_invoke()
GCallback panel_action_get_invoke (PanelActionButtonType type)
Definition at line 618 of file panel-action-button.c.
References NULL, PANEL_ACTION_LAST, PANEL_ACTION_NONE, and type.
panel_action_get_is_disabled()
gboolean panel_action_get_is_disabled (PanelActionButtonType type)
Definition at line 607 of file panel-action-button.c.
References FALSE, PANEL_ACTION_LAST, PANEL_ACTION_NONE, and type.
panel_action_get_text()
const char * panel_action_get_text (PanelActionButtonType type)
Definition at line 634 of file panel-action-button.c.
References _, NULL, PANEL_ACTION_LAST, PANEL_ACTION_NONE, and type.
panel_action_get_tooltip()
const char * panel_action_get_tooltip (PanelActionButtonType type)
Definition at line 641 of file panel-action-button.c.
References _, NULL, PANEL_ACTION_LAST, PANEL_ACTION_NONE, and type.