MATE Desktop Environment: panel-separator.h File Reference
panel-separator.h File Reference
#include "applet.h"
#include "panel-widget.h"
Classes
struct _PanelSeparator
struct _PanelSeparatorClass
Macros
#define PANEL_TYPE_SEPARATOR (panel_separator_get_type ())
#define PANEL_SEPARATOR(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PANEL_TYPE_SEPARATOR, PanelSeparator))
#define PANEL_SEPARATOR_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), PANEL_TYPE_SEPARATOR, PanelSeparatorClass))
#define PANEL_IS_SEPARATOR(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PANEL_TYPE_SEPARATOR))
#define PANEL_IS_SEPARATOR_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), PANEL_TYPE_SEPARATOR))
#define PANEL_SEPARATOR_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), PANEL_TYPE_SEPARATOR, PanelSeparatorClass))
Typedefs
typedef struct _PanelSeparator PanelSeparator
typedef struct _PanelSeparatorClass PanelSeparatorClass
typedef struct _PanelSeparatorPrivate PanelSeparatorPrivate
Functions
GType panel_separator_get_type (void)
void panel_separator_create (PanelToplevel *toplevel, int position)
void panel_separator_load_from_gsettings (PanelWidget *panel_widget, gboolean locked, gint position, const char *id)
void panel_separator_set_orientation (PanelSeparator *separator, PanelOrientation orientation)
void panel_separator_change_background (PanelSeparator *separator)
Macro Definition Documentation
PANEL_IS_SEPARATOR
#define PANEL_IS_SEPARATOR (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PANEL_TYPE_SEPARATOR))
Definition at line 39 of file panel-separator.h.
PANEL_IS_SEPARATOR_CLASS
#define PANEL_IS_SEPARATOR_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), PANEL_TYPE_SEPARATOR))
Definition at line 40 of file panel-separator.h.
PANEL_SEPARATOR
#define PANEL_SEPARATOR (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PANEL_TYPE_SEPARATOR, PanelSeparator))
Definition at line 37 of file panel-separator.h.
PANEL_SEPARATOR_CLASS
#define PANEL_SEPARATOR_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), PANEL_TYPE_SEPARATOR, PanelSeparatorClass))
Definition at line 38 of file panel-separator.h.
PANEL_SEPARATOR_GET_CLASS
#define PANEL_SEPARATOR_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), PANEL_TYPE_SEPARATOR, PanelSeparatorClass))
Definition at line 41 of file panel-separator.h.
PANEL_TYPE_SEPARATOR
#define PANEL_TYPE_SEPARATOR (panel_separator_get_type ())
Definition at line 36 of file panel-separator.h.
Typedef Documentation
PanelSeparator
typedef struct _PanelSeparator PanelSeparator
Definition at line 43 of file panel-separator.h.
PanelSeparatorClass
typedef struct _PanelSeparatorClass PanelSeparatorClass
Definition at line 44 of file panel-separator.h.
PanelSeparatorPrivate
typedef struct _PanelSeparatorPrivate PanelSeparatorPrivate
Definition at line 45 of file panel-separator.h.
Function Documentation
panel_separator_change_background()
void panel_separator_change_background (PanelSeparator * separator)
Definition at line 272 of file panel-separator.c.
References panel_background_apply_css(), and _PanelSeparator::priv.
Referenced by back_change().
panel_separator_create()
void panel_separator_create (PanelToplevel * toplevel, int position)
Definition at line 260 of file panel-separator.c.
References FALSE, id, PANEL_GSETTINGS_OBJECTS, PANEL_OBJECT_SEPARATOR, panel_profile_add_to_list(), and panel_profile_prepare_object().
panel_separator_get_type()
GType panel_separator_get_type (void)
panel_separator_load_from_gsettings()
void panel_separator_load_from_gsettings (PanelWidget * panel_widget, gboolean locked, gint position, const char * id)
panel_separator_set_orientation()
void panel_separator_set_orientation (PanelSeparator * separator, PanelOrientation orientation)
Definition at line 205 of file panel-separator.c.
References PANEL_IS_SEPARATOR, PANEL_ORIENTATION_BOTTOM, PANEL_ORIENTATION_LEFT, PANEL_ORIENTATION_RIGHT, PANEL_ORIENTATION_TOP, and _PanelSeparator::priv.
Referenced by orientation_change().