MATE Desktop Environment: panel-cleanup.h File Reference
panel-cleanup.h File Reference
#include <glib.h>
Macros
#define PANEL_CLEAN_FUNC(f) ((PanelCleanFunc) (f))
Typedefs
typedef void(* PanelCleanFunc) (gpointer data)
Functions
void panel_cleanup_unref_and_nullify (gpointer data)
void panel_cleanup_do (void)
void panel_cleanup_register (PanelCleanFunc func, gpointer data)
void panel_cleanup_unregister (PanelCleanFunc func, gpointer data)
Macro Definition Documentation
PANEL_CLEAN_FUNC
#define PANEL_CLEAN_FUNC (f) ((PanelCleanFunc) (f))
Definition at line 35 of file panel-cleanup.h.
Typedef Documentation
PanelCleanFunc
typedef void(* PanelCleanFunc) (gpointer data)
Definition at line 37 of file panel-cleanup.h.
Function Documentation
panel_cleanup_do()
void panel_cleanup_do (void)
Definition at line 39 of file panel-cleanup.c.
References NULL.
Referenced by main().
panel_cleanup_register()
void panel_cleanup_register (PanelCleanFunc func, gpointer data)
Definition at line 59 of file panel-cleanup.c.
References data, and NULL.
Referenced by panel_session_manager_get(), and panel_shell_register().
panel_cleanup_unref_and_nullify()
void panel_cleanup_unref_and_nullify (gpointer data)
Definition at line 100 of file panel-cleanup.c.
References data, and NULL.
Referenced by panel_session_manager_get().
panel_cleanup_unregister()
void panel_cleanup_unregister (PanelCleanFunc func, gpointer data)
Definition at line 74 of file panel-cleanup.c.
References data, and NULL.