MATE Desktop Environment: panel-stock-icons.h File Reference
panel-stock-icons.h File Reference
#include <glib.h>
#include <gtk/gtk.h>
Macros
#define PANEL_DEFAULT_MENU_ICON_SIZE 24
#define PANEL_DEFAULT_MENU_BAR_ICON_SIZE 22
#define PANEL_ADD_TO_DEFAULT_ICON_SIZE 32
Functions
void panel_init_stock_icons_and_items (void)
GtkIconSize panel_menu_icon_get_size (void)
GtkIconSize panel_menu_bar_icon_get_size (void)
GtkIconSize panel_add_to_icon_get_size (void)
Macro Definition Documentation
PANEL_ADD_TO_DEFAULT_ICON_SIZE
#define PANEL_ADD_TO_DEFAULT_ICON_SIZE 32
Definition at line 42 of file panel-stock-icons.h.
PANEL_DEFAULT_MENU_BAR_ICON_SIZE
#define PANEL_DEFAULT_MENU_BAR_ICON_SIZE 22
Definition at line 40 of file panel-stock-icons.h.
PANEL_DEFAULT_MENU_ICON_SIZE
#define PANEL_DEFAULT_MENU_ICON_SIZE 24
Definition at line 37 of file panel-stock-icons.h.
Function Documentation
panel_add_to_icon_get_size()
GtkIconSize panel_add_to_icon_get_size (void)
Definition at line 52 of file panel-stock-icons.c.
panel_init_stock_icons_and_items()
void panel_init_stock_icons_and_items (void)
Definition at line 59 of file panel-stock-icons.c.
References PANEL_ADD_TO_DEFAULT_ICON_SIZE, PANEL_DEFAULT_MENU_BAR_ICON_SIZE, PANEL_DEFAULT_MENU_ICON_SIZE, and PANEL_MENU_BAR_SCHEMA.
Referenced by main().
panel_menu_bar_icon_get_size()
GtkIconSize panel_menu_bar_icon_get_size (void)
Definition at line 47 of file panel-stock-icons.c.
panel_menu_icon_get_size()
GtkIconSize panel_menu_icon_get_size (void)
Definition at line 41 of file panel-stock-icons.c.
Referenced by panel_desktop_menu_item_new(), panel_place_menu_item_new(), and panel_recent_append_documents_menu().