MATE Desktop Environment: panel-context-menu.c File Reference
panel-context-menu.c File Reference
#include <config.h>
#include "panel-context-menu.h"
#include <string.h>
#include <glib/gi18n.h>
#include <gdk/gdkkeysyms.h>
#include <libpanel-util/panel-error.h>
#include <libpanel-util/panel-show.h>
#include <libpanel-util/panel-gtk.h>
#include "panel-util.h"
#include "panel.h"
#include "menu.h"
#include "applet.h"
#include "panel-config-global.h"
#include "panel-profile.h"
#include "panel-properties-dialog.h"
#include "panel-lockdown.h"
#include "panel-addto.h"
#include "panel-icon-names.h"
#include "panel-reset.h"
Functions
GtkWidget * panel_context_menu_create (PanelWidget *panel)
Function Documentation
panel_context_menu_create()
GtkWidget * panel_context_menu_create (PanelWidget * panel)
Definition at line 292 of file panel-context-menu.c.
References _, create_empty_menu(), _PanelWidget::master_widget, mate_panel_applet_create_menu(), AppletInfo::menu, NULL, panel_image_menu_item_new_from_icon(), and panel_lockdown_get_locked_down().