MATE Desktop Environment: panel-menu-bar.h File Reference
panel-menu-bar.h File Reference
#include <gtk/gtk.h>
#include "panel-widget.h"
Classes
struct _PanelMenuBar
struct _PanelMenuBarClass
Macros
#define PANEL_TYPE_MENU_BAR (panel_menu_bar_get_type ())
#define PANEL_MENU_BAR(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PANEL_TYPE_MENU_BAR, PanelMenuBar))
#define PANEL_MENU_BAR_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), PANEL_TYPE_MENU_BAR, PanelMenuBarClass))
#define PANEL_IS_MENU_BAR(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PANEL_TYPE_MENU_BAR))
#define PANEL_IS_MENU_BAR_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), PANEL_TYPE_MENU_BAR))
#define PANEL_MENU_BAR_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), PANEL_TYPE_MENU_BAR, PanelMenuBarClass))
Typedefs
typedef struct _PanelMenuBar PanelMenuBar
typedef struct _PanelMenuBarClass PanelMenuBarClass
typedef struct _PanelMenuBarPrivate PanelMenuBarPrivate
Functions
GType panel_menu_bar_get_type (void)
void panel_menu_bar_create (PanelToplevel *toplevel, int position)
void panel_menu_bar_load_from_gsettings (PanelWidget *panel, gboolean locked, int position, gboolean exactpos, const char *id)
void panel_menu_bar_invoke_menu (PanelMenuBar *menubar, const char *callback_name)
void panel_menu_bar_popup_menu (PanelMenuBar *menubar, guint32 activate_time)
void panel_menu_bar_change_background (PanelMenuBar *menubar)
void panel_menu_bar_set_orientation (PanelMenuBar *menubar, PanelOrientation orientation)
PanelOrientation panel_menu_bar_get_orientation (PanelMenuBar *menubar)
Macro Definition Documentation
PANEL_IS_MENU_BAR
#define PANEL_IS_MENU_BAR (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PANEL_TYPE_MENU_BAR))
Definition at line 39 of file panel-menu-bar.h.
PANEL_IS_MENU_BAR_CLASS
#define PANEL_IS_MENU_BAR_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), PANEL_TYPE_MENU_BAR))
Definition at line 40 of file panel-menu-bar.h.
PANEL_MENU_BAR
#define PANEL_MENU_BAR (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PANEL_TYPE_MENU_BAR, PanelMenuBar))
Definition at line 37 of file panel-menu-bar.h.
PANEL_MENU_BAR_CLASS
#define PANEL_MENU_BAR_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), PANEL_TYPE_MENU_BAR, PanelMenuBarClass))
Definition at line 38 of file panel-menu-bar.h.
PANEL_MENU_BAR_GET_CLASS
#define PANEL_MENU_BAR_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), PANEL_TYPE_MENU_BAR, PanelMenuBarClass))
Definition at line 41 of file panel-menu-bar.h.
PANEL_TYPE_MENU_BAR
#define PANEL_TYPE_MENU_BAR (panel_menu_bar_get_type ())
Definition at line 36 of file panel-menu-bar.h.
Typedef Documentation
PanelMenuBar
typedef struct _PanelMenuBar PanelMenuBar
Definition at line 43 of file panel-menu-bar.h.
PanelMenuBarClass
typedef struct _PanelMenuBarClass PanelMenuBarClass
Definition at line 44 of file panel-menu-bar.h.
PanelMenuBarPrivate
typedef struct _PanelMenuBarPrivate PanelMenuBarPrivate
Definition at line 45 of file panel-menu-bar.h.
Function Documentation
panel_menu_bar_change_background()
void panel_menu_bar_change_background (PanelMenuBar * menubar)
Definition at line 438 of file panel-menu-bar.c.
References panel_background_apply_css(), and _PanelMenuBar::priv.
Referenced by back_change().
panel_menu_bar_create()
void panel_menu_bar_create (PanelToplevel * toplevel, int position)
Definition at line 385 of file panel-menu-bar.c.
References FALSE, id, PANEL_GSETTINGS_OBJECTS, PANEL_OBJECT_MENU_BAR, panel_profile_add_to_list(), and panel_profile_prepare_object().
panel_menu_bar_get_orientation()
PanelOrientation panel_menu_bar_get_orientation (PanelMenuBar * menubar)
Definition at line 532 of file panel-menu-bar.c.
References PANEL_IS_MENU_BAR, and _PanelMenuBar::priv.
panel_menu_bar_get_type()
GType panel_menu_bar_get_type (void)
panel_menu_bar_invoke_menu()
void panel_menu_bar_invoke_menu (PanelMenuBar * menubar, const char * callback_name)
Definition at line 394 of file panel-menu-bar.c.
References NULL, PANEL_IS_MENU_BAR, panel_is_program_in_path(), panel_launch_desktop_file_with_fallback(), and panel_show_help().
panel_menu_bar_load_from_gsettings()
void panel_menu_bar_load_from_gsettings (PanelWidget * panel, gboolean locked, int position, gboolean exactpos, const char * id)
Definition at line 380 of file panel-menu-bar.c.
panel_menu_bar_popup_menu()
void panel_menu_bar_popup_menu (PanelMenuBar * menubar, guint32 activate_time)
Definition at line 417 of file panel-menu-bar.c.
References PANEL_IS_MENU_BAR, and _PanelMenuBar::priv.
panel_menu_bar_set_orientation()
void panel_menu_bar_set_orientation (PanelMenuBar * menubar, PanelOrientation orientation)
Definition at line 516 of file panel-menu-bar.c.
References PANEL_IS_MENU_BAR, and _PanelMenuBar::priv.
Referenced by orientation_change().