MATE Desktop Environment: parserfunc.c File Reference
parserfunc.c File Reference
#include <glib.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "parser.h"
#include "parserfunc.h"
Functions
void set_error (ParserState *state, gint errorno, const gchar *token)
void * pf_none (ParseNode *self)
void * pf_set_var (ParseNode *self)
void * pf_convert_number (ParseNode *self)
void * pf_convert_1 (ParseNode *self)
gchar * pf_make_unit (gchar *source, gchar *power)
void * pf_get_variable (ParseNode *self)
void * pf_get_variable_with_power (ParseNode *self)
void * pf_apply_func (ParseNode *self)
void * pf_apply_func_with_power (ParseNode *self)
void * pf_apply_func_with_npower (ParseNode *self)
void * pf_do_nth_root (ParseNode *self)
void * pf_do_sqrt (ParseNode *self)
void * pf_do_root_3 (ParseNode *self)
void * pf_do_root_4 (ParseNode *self)
void * pf_do_floor (ParseNode *self)
void * pf_do_ceiling (ParseNode *self)
void * pf_do_round (ParseNode *self)
void * pf_do_fraction (ParseNode *self)
void * pf_do_abs (ParseNode *self)
void * pf_do_x_pow_y (ParseNode *self)
void * pf_do_x_pow_y_int (ParseNode *self)
void * pf_do_factorial (ParseNode *self)
void * pf_unary_minus (ParseNode *self)
void * pf_do_divide (ParseNode *self)
void * pf_do_mod (ParseNode *self)
void * pf_do_multiply (ParseNode *self)
void * pf_do_subtract (ParseNode *self)
void * pf_do_add (ParseNode *self)
void * pf_do_add_percent (ParseNode *self)
void * pf_do_subtract_percent (ParseNode *self)
void * pf_do_percent (ParseNode *self)
void * pf_do_not (ParseNode *self)
void * pf_do_and (ParseNode *self)
void * pf_do_or (ParseNode *self)
void * pf_do_xor (ParseNode *self)
void * pf_constant (ParseNode *self)
Function Documentation
pf_apply_func()
void * pf_apply_func (ParseNode * self)
Definition at line 287 of file parserfunc.c.
References parse_node::evaluate, parser_state::get_function, mp_new_ptr(), NULL, PARSER_ERR_UNKNOWN_FUNCTION, parse_node::right, set_error(), parse_node::state, LexerToken::string, and parse_node::token.
pf_apply_func_with_npower()
void * pf_apply_func_with_npower (ParseNode * self)
Definition at line 358 of file parserfunc.c.
References parse_node::evaluate, parser_state::get_function, mp_free(), mp_new_ptr(), mp_xpowy_integer(), NULL, PARSER_ERR_UNKNOWN_FUNCTION, parse_node::right, set_error(), parse_node::state, LexerToken::string, super_atoi(), parse_node::token, and parse_node::value.
pf_apply_func_with_power()
void * pf_apply_func_with_power (ParseNode * self)
Definition at line 316 of file parserfunc.c.
References parse_node::evaluate, parser_state::get_function, mp_free(), mp_new_ptr(), mp_xpowy_integer(), NULL, PARSER_ERR_UNKNOWN_FUNCTION, parse_node::right, set_error(), parse_node::state, LexerToken::string, super_atoi(), parse_node::token, and parse_node::value.
pf_constant()
void * pf_constant (ParseNode * self)
Definition at line 961 of file parserfunc.c.
References MPEquationOptions::base, mp_free(), mp_new_ptr(), mp_set_from_string(), NULL, parser_state::options, PARSER_ERR_INVALID, set_error(), parse_node::state, LexerToken::string, and parse_node::token.
pf_convert_1()
void * pf_convert_1 (ParseNode * self)
Definition at line 101 of file parserfunc.c.
References parser_state::convert, parse_node::left, mp_clear(), mp_free(), mp_new(), mp_new_ptr(), mp_set_from_integer(), NULL, PARSER_ERR_UNKNOWN_CONVERSION, parse_node::right, set_error(), parse_node::state, LexerToken::string, parse_node::token, and parse_node::value.
pf_convert_number()
void * pf_convert_number (ParseNode * self)
Definition at line 43 of file parserfunc.c.
References MPEquationOptions::base, parser_state::convert, parse_node::left, mp_clear(), mp_free(), mp_new(), mp_new_ptr(), mp_set_from_string(), NULL, parser_state::options, PARSER_ERR_UNKNOWN_CONVERSION, parse_node::right, set_error(), parse_node::state, LexerToken::string, parse_node::token, and parse_node::value.
pf_do_abs()
void * pf_do_abs (ParseNode * self)
Definition at line 546 of file parserfunc.c.
References parse_node::evaluate, mp_abs(), mp_free(), mp_new_ptr(), NULL, and parse_node::right.
pf_do_add()
void * pf_do_add (ParseNode * self)
Definition at line 772 of file parserfunc.c.
References parse_node::evaluate, parse_node::left, mp_add(), mp_free(), mp_new_ptr(), NULL, and parse_node::right.
pf_do_add_percent()
void * pf_do_add_percent (ParseNode * self)
Definition at line 796 of file parserfunc.c.
References parse_node::evaluate, parse_node::left, mp_add_integer(), mp_divide_integer(), mp_free(), mp_multiply(), mp_new_ptr(), NULL, and parse_node::right.
pf_do_and()
void * pf_do_and (ParseNode * self)
Definition at line 889 of file parserfunc.c.
References parse_node::evaluate, parse_node::left, mp_and(), mp_free(), mp_new_ptr(), NULL, and parse_node::right.
pf_do_ceiling()
void * pf_do_ceiling (ParseNode * self)
Definition at line 495 of file parserfunc.c.
References parse_node::evaluate, mp_ceiling(), mp_free(), mp_new_ptr(), NULL, and parse_node::right.
pf_do_divide()
void * pf_do_divide (ParseNode * self)
Definition at line 657 of file parserfunc.c.
References parse_node::evaluate, parse_node::left, mp_divide(), mp_free(), mp_new_ptr(), NULL, and parse_node::right.
pf_do_factorial()
void * pf_do_factorial (ParseNode * self)
Definition at line 623 of file parserfunc.c.
References parse_node::evaluate, mp_factorial(), mp_free(), mp_new_ptr(), NULL, and parse_node::right.
pf_do_floor()
void * pf_do_floor (ParseNode * self)
Definition at line 479 of file parserfunc.c.
References parse_node::evaluate, mp_floor(), mp_free(), mp_new_ptr(), NULL, and parse_node::right.
pf_do_fraction()
void * pf_do_fraction (ParseNode * self)
Definition at line 529 of file parserfunc.c.
References parse_node::evaluate, mp_fractional_part(), mp_free(), mp_new_ptr(), NULL, and parse_node::right.
pf_do_mod()
void * pf_do_mod (ParseNode * self)
Definition at line 681 of file parserfunc.c.
References parse_node::evaluate, parse_node::left, mp_free(), mp_modular_exponentiation(), mp_modulus_divide(), mp_new_ptr(), NULL, pf_do_x_pow_y(), and parse_node::right.
pf_do_multiply()
void * pf_do_multiply (ParseNode * self)
Definition at line 724 of file parserfunc.c.
References parse_node::evaluate, parse_node::left, mp_free(), mp_multiply(), mp_new_ptr(), NULL, and parse_node::right.
pf_do_not()
void * pf_do_not (ParseNode * self)
Definition at line 865 of file parserfunc.c.
References parse_node::evaluate, mp_free(), mp_is_overflow(), mp_new_ptr(), mp_not(), NULL, parser_state::options, PARSER_ERR_OVERFLOW, parse_node::right, set_error(), parse_node::state, and MPEquationOptions::wordlen.
pf_do_nth_root()
void * pf_do_nth_root (ParseNode * self)
Definition at line 407 of file parserfunc.c.
References parse_node::evaluate, mp_free(), mp_new_ptr(), mp_root(), NULL, parse_node::right, sub_atoi(), and parse_node::value.
pf_do_or()
void * pf_do_or (ParseNode * self)
Definition at line 913 of file parserfunc.c.
References parse_node::evaluate, parse_node::left, mp_free(), mp_new_ptr(), mp_or(), NULL, and parse_node::right.
pf_do_percent()
void * pf_do_percent (ParseNode * self)
Definition at line 848 of file parserfunc.c.
References parse_node::evaluate, mp_divide_integer(), mp_free(), mp_new_ptr(), NULL, and parse_node::right.
pf_do_root_3()
void * pf_do_root_3 (ParseNode * self)
Definition at line 445 of file parserfunc.c.
References parse_node::evaluate, mp_free(), mp_new_ptr(), mp_root(), NULL, and parse_node::right.
pf_do_root_4()
void * pf_do_root_4 (ParseNode * self)
Definition at line 462 of file parserfunc.c.
References parse_node::evaluate, mp_free(), mp_new_ptr(), mp_root(), NULL, and parse_node::right.
pf_do_round()
void * pf_do_round (ParseNode * self)
Definition at line 512 of file parserfunc.c.
References parse_node::evaluate, mp_free(), mp_new_ptr(), mp_round(), NULL, and parse_node::right.
pf_do_sqrt()
void * pf_do_sqrt (ParseNode * self)
Definition at line 428 of file parserfunc.c.
References parse_node::evaluate, mp_new_ptr(), mp_sqrt(), NULL, and parse_node::right.
pf_do_subtract()
void * pf_do_subtract (ParseNode * self)
Definition at line 748 of file parserfunc.c.
References parse_node::evaluate, parse_node::left, mp_free(), mp_new_ptr(), mp_subtract(), NULL, and parse_node::right.
pf_do_subtract_percent()
void * pf_do_subtract_percent (ParseNode * self)
Definition at line 822 of file parserfunc.c.
References parse_node::evaluate, parse_node::left, mp_add_integer(), mp_divide_integer(), mp_free(), mp_multiply(), mp_new_ptr(), NULL, and parse_node::right.
pf_do_x_pow_y()
void * pf_do_x_pow_y (ParseNode * self)
Definition at line 563 of file parserfunc.c.
References parse_node::evaluate, parse_node::left, mp_free(), mp_new_ptr(), mp_xpowy(), NULL, and parse_node::right.
Referenced by pf_do_mod().
pf_do_x_pow_y_int()
void * pf_do_x_pow_y_int (ParseNode * self)
Definition at line 587 of file parserfunc.c.
References parse_node::evaluate, parse_node::left, mp_free(), mp_new_ptr(), mp_set_from_integer(), mp_to_integer(), mp_xpowy_integer(), NULL, parse_node::right, LexerToken::string, super_atoi(), and parse_node::token.
pf_do_xor()
void * pf_do_xor (ParseNode * self)
Definition at line 937 of file parserfunc.c.
References parse_node::evaluate, parse_node::left, mp_free(), mp_new_ptr(), mp_xor(), NULL, and parse_node::right.
pf_get_variable()
void * pf_get_variable (ParseNode * self)
Definition at line 167 of file parserfunc.c.
References parser_state::get_variable, mp_multiply(), mp_new(), mp_new_ptr(), mp_set_from_integer(), mp_set_from_mp(), NULL, PARSER_ERR_UNKNOWN_VARIABLE, set_error(), parse_node::state, LexerToken::string, and parse_node::token.
pf_get_variable_with_power()
void * pf_get_variable_with_power (ParseNode * self)
Definition at line 222 of file parserfunc.c.
References parser_state::get_variable, mp_multiply(), mp_new(), mp_new_ptr(), mp_set_from_integer(), mp_set_from_mp(), mp_xpowy_integer(), NULL, PARSER_ERR_UNKNOWN_VARIABLE, set_error(), parse_node::state, LexerToken::string, super_atoi(), parse_node::token, and parse_node::value.
pf_make_unit()
gchar * pf_make_unit (gchar * source, gchar * power)
Definition at line 151 of file parserfunc.c.
References NULL.
pf_none()
void * pf_none (ParseNode * self)
Definition at line 20 of file parserfunc.c.
References NULL.
pf_set_var()
void * pf_set_var (ParseNode * self)
Definition at line 27 of file parserfunc.c.
References parse_node::evaluate, parse_node::left, mp_free(), NULL, parse_node::right, parser_state::set_variable, parse_node::state, LexerToken::string, and parse_node::token.
pf_unary_minus()
void * pf_unary_minus (ParseNode * self)
Definition at line 640 of file parserfunc.c.
References parse_node::evaluate, mp_free(), mp_invert_sign(), mp_new_ptr(), NULL, and parse_node::right.
set_error()
void set_error (ParserState * state, gint errorno, const gchar * token)
Definition at line 11 of file parserfunc.c.
Referenced by p_parse(), pf_apply_func(), pf_apply_func_with_npower(), pf_apply_func_with_power(), pf_constant(), pf_convert_1(), pf_convert_number(), pf_do_not(), pf_get_variable(), and pf_get_variable_with_power().