MATE Desktop Environment: pluma-history-entry.h File Reference
pluma-history-entry.h File Reference
Classes
struct _PlumaHistoryEntryClass
struct _PlumaHistoryEntry
Macros
#define PLUMA_TYPE_HISTORY_ENTRY (pluma_history_entry_get_type ())
#define PLUMA_HISTORY_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_HISTORY_ENTRY, PlumaHistoryEntry))
#define PLUMA_HISTORY_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLUMA_TYPE_HISTORY_ENTRY, PlumaHistoryEntryClass))
#define PLUMA_IS_HISTORY_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLUMA_TYPE_HISTORY_ENTRY))
#define PLUMA_IS_HISTORY_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_HISTORY_ENTRY))
#define PLUMA_HISTORY_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLUMA_TYPE_HISTORY_ENTRY, PlumaHistoryEntryClass))
Typedefs
typedef struct _PlumaHistoryEntry PlumaHistoryEntry
typedef struct _PlumaHistoryEntryClass PlumaHistoryEntryClass
typedef struct _PlumaHistoryEntryPrivate PlumaHistoryEntryPrivate
typedef gchar *(* PlumaHistoryEntryEscapeFunc) (const gchar *str)
Functions
GType pluma_history_entry_get_type (void)
GtkWidget * pluma_history_entry_new (const gchar *history_id, gboolean enable_completion)
void pluma_history_entry_prepend_text (PlumaHistoryEntry *entry, const gchar *text)
void pluma_history_entry_append_text (PlumaHistoryEntry *entry, const gchar *text)
void pluma_history_entry_clear (PlumaHistoryEntry *entry)
void pluma_history_entry_set_history_length (PlumaHistoryEntry *entry, guint max_saved)
guint pluma_history_entry_get_history_length (PlumaHistoryEntry *gentry)
gchar * pluma_history_entry_get_history_id (PlumaHistoryEntry *entry)
void pluma_history_entry_set_enable_completion (PlumaHistoryEntry *entry, gboolean enable)
gboolean pluma_history_entry_get_enable_completion (PlumaHistoryEntry *entry)
GtkWidget * pluma_history_entry_get_entry (PlumaHistoryEntry *entry)
void pluma_history_entry_set_escape_func (PlumaHistoryEntry *entry, PlumaHistoryEntryEscapeFunc escape_func)
Macro Definition Documentation
PLUMA_HISTORY_ENTRY
#define PLUMA_HISTORY_ENTRY (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_HISTORY_ENTRY, PlumaHistoryEntry))
Definition at line 39 of file pluma-history-entry.h.
PLUMA_HISTORY_ENTRY_CLASS
#define PLUMA_HISTORY_ENTRY_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLUMA_TYPE_HISTORY_ENTRY, PlumaHistoryEntryClass))
Definition at line 40 of file pluma-history-entry.h.
PLUMA_HISTORY_ENTRY_GET_CLASS
#define PLUMA_HISTORY_ENTRY_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLUMA_TYPE_HISTORY_ENTRY, PlumaHistoryEntryClass))
Definition at line 43 of file pluma-history-entry.h.
PLUMA_IS_HISTORY_ENTRY
#define PLUMA_IS_HISTORY_ENTRY (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLUMA_TYPE_HISTORY_ENTRY))
Definition at line 41 of file pluma-history-entry.h.
PLUMA_IS_HISTORY_ENTRY_CLASS
#define PLUMA_IS_HISTORY_ENTRY_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_HISTORY_ENTRY))
Definition at line 42 of file pluma-history-entry.h.
PLUMA_TYPE_HISTORY_ENTRY
#define PLUMA_TYPE_HISTORY_ENTRY (pluma_history_entry_get_type ())
Definition at line 38 of file pluma-history-entry.h.
Typedef Documentation
PlumaHistoryEntry
typedef struct _PlumaHistoryEntry PlumaHistoryEntry
Definition at line 46 of file pluma-history-entry.h.
PlumaHistoryEntryClass
typedef struct _PlumaHistoryEntryClass PlumaHistoryEntryClass
Definition at line 47 of file pluma-history-entry.h.
PlumaHistoryEntryEscapeFunc
typedef gchar *(* PlumaHistoryEntryEscapeFunc) (const gchar *str)
Definition at line 91 of file pluma-history-entry.h.
PlumaHistoryEntryPrivate
typedef struct _PlumaHistoryEntryPrivate PlumaHistoryEntryPrivate
Definition at line 48 of file pluma-history-entry.h.
Function Documentation
pluma_history_entry_append_text()
void pluma_history_entry_append_text (PlumaHistoryEntry * entry, const gchar * text)
Definition at line 338 of file pluma-history-entry.c.
References FALSE, NULL, and PLUMA_IS_HISTORY_ENTRY.
pluma_history_entry_clear()
void pluma_history_entry_clear (PlumaHistoryEntry * entry)
Definition at line 380 of file pluma-history-entry.c.
References PLUMA_IS_HISTORY_ENTRY.
pluma_history_entry_get_enable_completion()
gboolean pluma_history_entry_get_enable_completion (PlumaHistoryEntry * entry)
Definition at line 479 of file pluma-history-entry.c.
References FALSE, NULL, PLUMA_IS_HISTORY_ENTRY, and _PlumaHistoryEntry::priv.
pluma_history_entry_get_entry()
GtkWidget * pluma_history_entry_get_entry (PlumaHistoryEntry * entry)
Definition at line 540 of file pluma-history-entry.c.
References NULL, and PLUMA_IS_HISTORY_ENTRY.
Referenced by pluma_history_entry_set_enable_completion().
pluma_history_entry_get_history_id()
gchar * pluma_history_entry_get_history_id (PlumaHistoryEntry * entry)
Definition at line 429 of file pluma-history-entry.c.
References NULL, PLUMA_IS_HISTORY_ENTRY, and _PlumaHistoryEntry::priv.
pluma_history_entry_get_history_length()
guint pluma_history_entry_get_history_length (PlumaHistoryEntry * gentry)
Definition at line 421 of file pluma-history-entry.c.
References PLUMA_IS_HISTORY_ENTRY, and _PlumaHistoryEntry::priv.
pluma_history_entry_get_type()
GType pluma_history_entry_get_type (void)
pluma_history_entry_new()
GtkWidget * pluma_history_entry_new (const gchar * history_id, gboolean enable_completion)
Definition at line 487 of file pluma-history-entry.c.
References NULL, PLUMA_HISTORY_ENTRY, pluma_history_entry_set_enable_completion(), PLUMA_TYPE_HISTORY_ENTRY, and TRUE.
pluma_history_entry_prepend_text()
void pluma_history_entry_prepend_text (PlumaHistoryEntry * entry, const gchar * text)
Definition at line 328 of file pluma-history-entry.c.
References NULL, PLUMA_IS_HISTORY_ENTRY, and TRUE.
pluma_history_entry_set_enable_completion()
void pluma_history_entry_set_enable_completion (PlumaHistoryEntry * entry, gboolean enable)
Definition at line 437 of file pluma-history-entry.c.
References FALSE, MIN_ITEM_LEN, NULL, pluma_history_entry_get_entry(), PLUMA_IS_HISTORY_ENTRY, _PlumaHistoryEntry::priv, and TRUE.
Referenced by pluma_history_entry_new().
pluma_history_entry_set_escape_func()
void pluma_history_entry_set_escape_func (PlumaHistoryEntry * entry, PlumaHistoryEntryEscapeFunc escape_func)
Definition at line 566 of file pluma-history-entry.c.
References NULL, and PLUMA_IS_HISTORY_ENTRY.
pluma_history_entry_set_history_length()
void pluma_history_entry_set_history_length (PlumaHistoryEntry * entry, guint max_saved)
Definition at line 409 of file pluma-history-entry.c.
References PLUMA_IS_HISTORY_ENTRY, and _PlumaHistoryEntry::priv.