MATE Desktop Environment: pluma-search-dialog.h File Reference
pluma-search-dialog.h File Reference
#include <gtk/gtk.h>
Classes
struct _PlumaSearchDialog
struct _PlumaSearchDialogClass
Macros
#define PLUMA_TYPE_SEARCH_DIALOG (pluma_search_dialog_get_type())
#define PLUMA_SEARCH_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_SEARCH_DIALOG, PlumaSearchDialog))
#define PLUMA_SEARCH_DIALOG_CONST(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_SEARCH_DIALOG, PlumaSearchDialog const))
#define PLUMA_SEARCH_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), PLUMA_TYPE_SEARCH_DIALOG, PlumaSearchDialogClass))
#define PLUMA_IS_SEARCH_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), PLUMA_TYPE_SEARCH_DIALOG))
#define PLUMA_IS_SEARCH_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_SEARCH_DIALOG))
#define PLUMA_SEARCH_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), PLUMA_TYPE_SEARCH_DIALOG, PlumaSearchDialogClass))
Typedefs
typedef struct _PlumaSearchDialogPrivate PlumaSearchDialogPrivate
typedef struct _PlumaSearchDialog PlumaSearchDialog
typedef struct _PlumaSearchDialogClass PlumaSearchDialogClass
Enumerations
enum { PLUMA_SEARCH_DIALOG_FIND_RESPONSE = 100 , PLUMA_SEARCH_DIALOG_REPLACE_RESPONSE , PLUMA_SEARCH_DIALOG_REPLACE_ALL_RESPONSE }
Functions
GType pluma_search_dialog_get_type (void)
GtkWidget * pluma_search_dialog_new (GtkWindow *parent, gboolean show_replace)
void pluma_search_dialog_present_with_time (PlumaSearchDialog *dialog, guint32 timestamp)
gboolean pluma_search_dialog_get_show_replace (PlumaSearchDialog *dialog)
void pluma_search_dialog_set_show_replace (PlumaSearchDialog *dialog, gboolean show_replace)
void pluma_search_dialog_set_search_text (PlumaSearchDialog *dialog, const gchar *text)
const gchar * pluma_search_dialog_get_search_text (PlumaSearchDialog *dialog)
void pluma_search_dialog_set_replace_text (PlumaSearchDialog *dialog, const gchar *text)
const gchar * pluma_search_dialog_get_replace_text (PlumaSearchDialog *dialog)
void pluma_search_dialog_set_match_case (PlumaSearchDialog *dialog, gboolean match_case)
gboolean pluma_search_dialog_get_match_case (PlumaSearchDialog *dialog)
void pluma_search_dialog_set_match_regex (PlumaSearchDialog *dialog, gboolean match_case)
gboolean pluma_search_dialog_get_match_regex (PlumaSearchDialog *dialog)
void pluma_search_dialog_set_entire_word (PlumaSearchDialog *dialog, gboolean entire_word)
gboolean pluma_search_dialog_get_entire_word (PlumaSearchDialog *dialog)
void pluma_search_dialog_set_backwards (PlumaSearchDialog *dialog, gboolean backwards)
gboolean pluma_search_dialog_get_backwards (PlumaSearchDialog *dialog)
void pluma_search_dialog_set_wrap_around (PlumaSearchDialog *dialog, gboolean wrap_around)
gboolean pluma_search_dialog_get_wrap_around (PlumaSearchDialog *dialog)
void pluma_search_dialog_set_parse_escapes (PlumaSearchDialog *dialog, gboolean parse_escapes)
gboolean pluma_search_dialog_get_parse_escapes (PlumaSearchDialog *dialog)
Macro Definition Documentation
PLUMA_IS_SEARCH_DIALOG
#define PLUMA_IS_SEARCH_DIALOG (obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), PLUMA_TYPE_SEARCH_DIALOG))
Definition at line 46 of file pluma-search-dialog.h.
PLUMA_IS_SEARCH_DIALOG_CLASS
#define PLUMA_IS_SEARCH_DIALOG_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_SEARCH_DIALOG))
Definition at line 47 of file pluma-search-dialog.h.
PLUMA_SEARCH_DIALOG
#define PLUMA_SEARCH_DIALOG (obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_SEARCH_DIALOG, PlumaSearchDialog))
Definition at line 43 of file pluma-search-dialog.h.
PLUMA_SEARCH_DIALOG_CLASS
#define PLUMA_SEARCH_DIALOG_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), PLUMA_TYPE_SEARCH_DIALOG, PlumaSearchDialogClass))
Definition at line 45 of file pluma-search-dialog.h.
PLUMA_SEARCH_DIALOG_CONST
#define PLUMA_SEARCH_DIALOG_CONST (obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_SEARCH_DIALOG, PlumaSearchDialog const))
Definition at line 44 of file pluma-search-dialog.h.
PLUMA_SEARCH_DIALOG_GET_CLASS
#define PLUMA_SEARCH_DIALOG_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS((obj), PLUMA_TYPE_SEARCH_DIALOG, PlumaSearchDialogClass))
Definition at line 48 of file pluma-search-dialog.h.
PLUMA_TYPE_SEARCH_DIALOG
#define PLUMA_TYPE_SEARCH_DIALOG (pluma_search_dialog_get_type())
Definition at line 42 of file pluma-search-dialog.h.
Typedef Documentation
PlumaSearchDialog
typedef struct _PlumaSearchDialog PlumaSearchDialog
Definition at line 56 of file pluma-search-dialog.h.
PlumaSearchDialogClass
typedef struct _PlumaSearchDialogClass PlumaSearchDialogClass
Definition at line 69 of file pluma-search-dialog.h.
PlumaSearchDialogPrivate
typedef struct _PlumaSearchDialogPrivate PlumaSearchDialogPrivate
Definition at line 51 of file pluma-search-dialog.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PLUMA_SEARCH_DIALOG_FIND_RESPONSE
PLUMA_SEARCH_DIALOG_REPLACE_RESPONSE
PLUMA_SEARCH_DIALOG_REPLACE_ALL_RESPONSE
Definition at line 79 of file pluma-search-dialog.h.
Function Documentation
pluma_search_dialog_get_backwards()
gboolean pluma_search_dialog_get_backwards (PlumaSearchDialog * dialog)
Definition at line 619 of file pluma-search-dialog.c.
References FALSE, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_get_entire_word()
gboolean pluma_search_dialog_get_entire_word (PlumaSearchDialog * dialog)
Definition at line 601 of file pluma-search-dialog.c.
References FALSE, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_get_match_case()
gboolean pluma_search_dialog_get_match_case (PlumaSearchDialog * dialog)
Definition at line 565 of file pluma-search-dialog.c.
References FALSE, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_get_match_regex()
gboolean pluma_search_dialog_get_match_regex (PlumaSearchDialog * dialog)
Definition at line 583 of file pluma-search-dialog.c.
References FALSE, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_get_parse_escapes()
gboolean pluma_search_dialog_get_parse_escapes (PlumaSearchDialog * dialog)
Definition at line 655 of file pluma-search-dialog.c.
References FALSE, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
Referenced by _pluma_cmd_search_find(), and _pluma_cmd_search_replace().
pluma_search_dialog_get_replace_text()
const gchar * pluma_search_dialog_get_replace_text (PlumaSearchDialog * dialog)
Definition at line 547 of file pluma-search-dialog.c.
References NULL, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_get_search_text()
const gchar * pluma_search_dialog_get_search_text (PlumaSearchDialog * dialog)
Definition at line 528 of file pluma-search-dialog.c.
References NULL, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
Referenced by _pluma_cmd_search_find(), and _pluma_cmd_search_replace().
pluma_search_dialog_get_show_replace()
gboolean pluma_search_dialog_get_show_replace (PlumaSearchDialog * dialog)
Definition at line 483 of file pluma-search-dialog.c.
References FALSE, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
Referenced by _pluma_cmd_search_find(), and _pluma_cmd_search_replace().
pluma_search_dialog_get_type()
GType pluma_search_dialog_get_type (void)
pluma_search_dialog_get_wrap_around()
gboolean pluma_search_dialog_get_wrap_around (PlumaSearchDialog * dialog)
Definition at line 637 of file pluma-search-dialog.c.
References FALSE, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_new()
GtkWidget * pluma_search_dialog_new (GtkWindow * parent, gboolean show_replace)
Definition at line 461 of file pluma-search-dialog.c.
References NULL, PLUMA_TYPE_SEARCH_DIALOG, and TRUE.
pluma_search_dialog_present_with_time()
void pluma_search_dialog_present_with_time (PlumaSearchDialog * dialog, guint32 timestamp)
Definition at line 127 of file pluma-search-dialog.c.
References PLUMA_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
Referenced by _pluma_cmd_search_find(), and _pluma_cmd_search_replace().
pluma_search_dialog_set_backwards()
void pluma_search_dialog_set_backwards (PlumaSearchDialog * dialog, gboolean backwards)
Definition at line 609 of file pluma-search-dialog.c.
References PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_set_entire_word()
void pluma_search_dialog_set_entire_word (PlumaSearchDialog * dialog, gboolean entire_word)
Definition at line 591 of file pluma-search-dialog.c.
References PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_set_match_case()
void pluma_search_dialog_set_match_case (PlumaSearchDialog * dialog, gboolean match_case)
Definition at line 555 of file pluma-search-dialog.c.
References PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_set_match_regex()
void pluma_search_dialog_set_match_regex (PlumaSearchDialog * dialog, gboolean match_case)
Definition at line 573 of file pluma-search-dialog.c.
References PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_set_parse_escapes()
void pluma_search_dialog_set_parse_escapes (PlumaSearchDialog * dialog, gboolean parse_escapes)
Definition at line 645 of file pluma-search-dialog.c.
References PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_set_replace_text()
void pluma_search_dialog_set_replace_text (PlumaSearchDialog * dialog, const gchar * text)
Definition at line 536 of file pluma-search-dialog.c.
References NULL, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_set_search_text()
void pluma_search_dialog_set_search_text (PlumaSearchDialog * dialog, const gchar * text)
Definition at line 506 of file pluma-search-dialog.c.
References NULL, PLUMA_IS_SEARCH_DIALOG, PLUMA_SEARCH_DIALOG_FIND_RESPONSE, PLUMA_SEARCH_DIALOG_REPLACE_ALL_RESPONSE, and _PlumaSearchDialog::priv.
Referenced by _pluma_cmd_search_find(), and _pluma_cmd_search_replace().
pluma_search_dialog_set_show_replace()
void pluma_search_dialog_set_show_replace (PlumaSearchDialog * dialog, gboolean show_replace)
Definition at line 491 of file pluma-search-dialog.c.
References FALSE, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
Referenced by _pluma_cmd_search_find(), and _pluma_cmd_search_replace().
pluma_search_dialog_set_wrap_around()
void pluma_search_dialog_set_wrap_around (PlumaSearchDialog * dialog, gboolean wrap_around)
Definition at line 627 of file pluma-search-dialog.c.
References PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.