MATE Desktop Environment: pluma-application.c File Reference
pluma-application.c File Reference
#include <locale.h>
#include <glib/gi18n.h>
#include "pluma-application.h"
#include "pluma-debug.h"
#include "pluma-dirs.h"
#include "pluma-plugins-engine.h"
#include "pluma-session.h"
#include "pluma-settings.h"
#include "pluma-app.h"
#include "pluma-window.h"
#include "pluma-commands.h"
#include "eggdesktopfile.h"
#include "pluma-metadata-manager.h"
Functions
void pluma_application_set_command_line_options (PlumaApplication *app, gint line_pos, const gchar *encoding, gboolean new_window, gboolean new_document, GSList *file_list)
PlumaApplication * pluma_application_new (void)
Function Documentation
pluma_application_new()
PlumaApplication * pluma_application_new (void)
Definition at line 266 of file pluma-application.c.
References NULL, and PLUMA_TYPE_APPLICATION.
Referenced by main().
pluma_application_set_command_line_options()
void pluma_application_set_command_line_options (PlumaApplication * app, gint line_pos, const gchar * encoding, gboolean new_window, gboolean new_document, GSList * file_list)
Definition at line 231 of file pluma-application.c.
References file_list, NULL, pluma_encoding_get_from_charset(), and _PlumaApplication::priv.
Referenced by main().