MATE Desktop Environment: pluma-message-type.c File Reference
pluma-message-type.c File Reference
#include "pluma-message-type.h"
Functions
PlumaMessageType * pluma_message_type_ref (PlumaMessageType *message_type)
void pluma_message_type_unref (PlumaMessageType *message_type)
GType pluma_message_type_get_type (void)
gchar * pluma_message_type_identifier (const gchar *object_path, const gchar *method)
gboolean pluma_message_type_is_valid_object_path (const gchar *object_path)
gboolean pluma_message_type_is_supported (GType type)
PlumaMessageType * pluma_message_type_new_valist (const gchar *object_path, const gchar *method, guint num_optional, va_list var_args)
PlumaMessageType * pluma_message_type_new (const gchar *object_path, const gchar *method, guint num_optional,...)
void pluma_message_type_set (PlumaMessageType *message_type, guint num_optional,...)
void pluma_message_type_set_valist (PlumaMessageType *message_type, guint num_optional, va_list var_args)
PlumaMessage * pluma_message_type_instantiate_valist (PlumaMessageType *message_type, va_list va_args)
PlumaMessage * pluma_message_type_instantiate (PlumaMessageType *message_type,...)
const gchar * pluma_message_type_get_object_path (PlumaMessageType *message_type)
const gchar * pluma_message_type_get_method (PlumaMessageType *message_type)
GType pluma_message_type_lookup (PlumaMessageType *message_type, const gchar *key)
void pluma_message_type_foreach (PlumaMessageType *message_type, PlumaMessageTypeForeach func, gpointer user_data)
Function Documentation
pluma_message_type_foreach()
void pluma_message_type_foreach (PlumaMessageType * message_type, PlumaMessageTypeForeach func, gpointer user_data)
pluma_message_type_foreach: @message_type: the PlumaMessageType @func: (scope call): the callback function @user_data: user data supplied to the callback function
Calls @func for each argument in the message type.
Definition at line 516 of file pluma-message-type.c.
References user_data.
Referenced by pluma_message_validate().
pluma_message_type_get_method()
const gchar * pluma_message_type_get_method (PlumaMessageType * message_type)
pluma_message_type_get_method: @message_type: the PlumaMessageType
Get the message type method.
Return value: the message type method
Definition at line 465 of file pluma-message-type.c.
Referenced by pluma_message_get_method().
pluma_message_type_get_object_path()
const gchar * pluma_message_type_get_object_path (PlumaMessageType * message_type)
pluma_message_type_get_object_path: @message_type: the PlumaMessageType
Get the message type object path.
Return value: the message type object path
Definition at line 450 of file pluma-message-type.c.
Referenced by pluma_message_get_object_path().
pluma_message_type_get_type()
GType pluma_message_type_get_type (void)
pluma_message_type_get_type:
Retrieves the GType object which is associated with the PlumaMessageType class.
Return value: the GType associated with PlumaMessageType.
Definition at line 107 of file pluma-message-type.c.
References pluma_message_type_ref(), and pluma_message_type_unref().
pluma_message_type_identifier()
gchar * pluma_message_type_identifier (const gchar * object_path, const gchar * method)
pluma_message_type_identifier: @object_path: (allow-none): the object path @method: (allow-none): the method
Get the string identifier for @method at @object_path.
Return value: the identifier for @method at @object_path
Definition at line 131 of file pluma-message-type.c.
References NULL.
Referenced by pluma_message_bus_is_registered(), pluma_message_bus_lookup(), and pluma_message_bus_register().
pluma_message_type_instantiate()
PlumaMessage * pluma_message_type_instantiate (PlumaMessageType * message_type, ...)
pluma_message_type_instantiate: @message_type: the PlumaMessageType ...: NULL terminated variable list of key/value pairs
Instantiate a new message from the message type with specific values for the message arguments.
Return value: (transfer full): the newly created message
Definition at line 427 of file pluma-message-type.c.
References message(), and pluma_message_type_instantiate_valist().
pluma_message_type_instantiate_valist()
PlumaMessage * pluma_message_type_instantiate_valist (PlumaMessageType * message_type, va_list va_args)
pluma_message_type_instantiate_valist: @message_type: the PlumaMessageType @va_args: NULL terminated variable list of key/value pairs
Instantiate a new message from the message type with specific values for the message arguments.
Return value: (transfer full): the newly created message
Definition at line 402 of file pluma-message-type.c.
References message(), NULL, PLUMA_MESSAGE, pluma_message_set_valist(), and PLUMA_TYPE_MESSAGE.
Referenced by pluma_message_type_instantiate().
pluma_message_type_is_supported()
gboolean pluma_message_type_is_supported (GType type)
pluma_message_type_is_supported: @type: the #GType
Returns if @type is #GType supported by the message system.
Return value: TRUE if @type is a supported #GType
Definition at line 186 of file pluma-message-type.c.
References FALSE, TRUE, and type.
Referenced by pluma_message_type_set_valist().
pluma_message_type_is_valid_object_path()
gboolean pluma_message_type_is_valid_object_path (const gchar * object_path)
pluma_message_type_is_valid_object_path: @object_path: (allow-none): the object path
Returns whether @object_path is a valid object path
Return value: TRUE if @object_path is a valid object path
Definition at line 147 of file pluma-message-type.c.
References FALSE, and TRUE.
Referenced by pluma_message_bus_register(), and pluma_message_type_new_valist().
pluma_message_type_lookup()
GType pluma_message_type_lookup (PlumaMessageType * message_type, const gchar * key)
pluma_message_type_lookup: @message_type: the PlumaMessageType @key: the argument key
Get the argument key #GType.
Return value: the #GType of @key
Definition at line 481 of file pluma-message-type.c.
References key.
Referenced by pluma_message_get_key_type().
pluma_message_type_new()
PlumaMessageType * pluma_message_type_new (const gchar * object_path, const gchar * method, guint num_optional, ...)
pluma_message_type_new: @object_path: (allow-none): the object path @method: (allow-none): the method @num_optional: number of optional arguments ...: key/gtype pair variable argument list
Create a new PlumaMessageType for @method at @object_path. Argument names and values are supplied by the NULL terminated variable argument list. The last @num_optional provided arguments are considered optional.
Return value: the newly constructed PlumaMessageType
Definition at line 281 of file pluma-message-type.c.
References pluma_message_type_new_valist().
pluma_message_type_new_valist()
PlumaMessageType * pluma_message_type_new_valist (const gchar * object_path, const gchar * method, guint num_optional, va_list var_args)
pluma_message_type_new_valist: @object_path: (allow-none): the object path @method: (allow-none): the method @num_optional: number of optional arguments @va_args: key/gtype pair variable argument list
Create a new PlumaMessageType for @method at @object_path. Argument names and values are supplied by the NULL terminated variable argument list. The last @num_optional provided arguments are considered optional.
Return value: the newly constructed PlumaMessageType
Definition at line 240 of file pluma-message-type.c.
References NULL, pluma_message_type_is_valid_object_path(), and pluma_message_type_set_valist().
Referenced by pluma_message_bus_register(), and pluma_message_type_new().
pluma_message_type_ref()
PlumaMessageType * pluma_message_type_ref (PlumaMessageType * message_type)
pluma_message_type_ref: @message_type: the PlumaMessageType
Increases the reference count on @message_type.
Return value: @message_type
Definition at line 67 of file pluma-message-type.c.
References NULL.
Referenced by pluma_message_type_get_type().
pluma_message_type_set()
void pluma_message_type_set (PlumaMessageType * message_type, guint num_optional, ...)
pluma_message_type_set: @message_type: the PlumaMessageType @num_optional: number of optional arguments ...: key/gtype pair variable argument list
Sets argument names/types supplied by the NULL terminated variable argument list. The last @num_optional provided arguments are considered optional.
Definition at line 308 of file pluma-message-type.c.
References pluma_message_type_set_valist().
pluma_message_type_set_valist()
void pluma_message_type_set_valist (PlumaMessageType * message_type, guint num_optional, va_list var_args)
pluma_message_type_set_valist: @message_type: the PlumaMessageType @num_optional: number of optional arguments @va_args: key/gtype pair variable argument list
Sets argument names/types supplied by the NULL terminated variable argument list @va_args. The last @num_optional provided arguments are considered optional.
Definition at line 331 of file pluma-message-type.c.
References FALSE, key, NULL, pluma_message_type_is_supported(), pluma_message_type_unref(), and TRUE.
Referenced by pluma_message_type_new_valist(), and pluma_message_type_set().
pluma_message_type_unref()
void pluma_message_type_unref (PlumaMessageType * message_type)
pluma_message_type_unref: @message_type: the PlumaMessageType
Decreases the reference count on @message_type. When the reference count drops to 0, @message_type is destroyed.
Definition at line 84 of file pluma-message-type.c.
References NULL.
Referenced by pluma_message_type_get_type(), and pluma_message_type_set_valist().