MATE Desktop Environment: pluma-application.h File Reference
pluma-application.h File Reference
#include <gtk/gtk.h>
Classes
struct _PlumaApplication
struct _PlumaApplicationClass
Macros
#define PLUMA_TYPE_APPLICATION (pluma_application_get_type())
#define PLUMA_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_APPLICATION, PlumaApplication))
#define PLUMA_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), PLUMA_TYPE_APPLICATION, PlumaApplicationClass))
#define PLUMA_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), PLUMA_TYPE_APPLICATION))
#define PLUMA_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_APPLICATION))
#define PLUMA_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), PLUMA_TYPE_APPLICATION, PlumaApplicationClass))
Typedefs
typedef struct _PlumaApplicationPrivate PlumaApplicationPrivate
typedef struct _PlumaApplication PlumaApplication
typedef struct _PlumaApplicationClass PlumaApplicationClass
Functions
GType pluma_application_get_type (void)
PlumaApplication * pluma_application_new (void)
void pluma_application_set_command_line_options (PlumaApplication *app, gint line_pos, const gchar *encoding, gboolean new_window, gboolean new_document, GSList *file_list)
Macro Definition Documentation
PLUMA_APPLICATION
#define PLUMA_APPLICATION (obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_APPLICATION, PlumaApplication))
Definition at line 34 of file pluma-application.h.
PLUMA_APPLICATION_CLASS
#define PLUMA_APPLICATION_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), PLUMA_TYPE_APPLICATION, PlumaApplicationClass))
Definition at line 35 of file pluma-application.h.
PLUMA_APPLICATION_GET_CLASS
#define PLUMA_APPLICATION_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS((obj), PLUMA_TYPE_APPLICATION, PlumaApplicationClass))
Definition at line 38 of file pluma-application.h.
PLUMA_IS_APPLICATION
#define PLUMA_IS_APPLICATION (obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), PLUMA_TYPE_APPLICATION))
Definition at line 36 of file pluma-application.h.
PLUMA_IS_APPLICATION_CLASS
#define PLUMA_IS_APPLICATION_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_APPLICATION))
Definition at line 37 of file pluma-application.h.
PLUMA_TYPE_APPLICATION
#define PLUMA_TYPE_APPLICATION (pluma_application_get_type())
Definition at line 33 of file pluma-application.h.
Typedef Documentation
PlumaApplication
typedef struct _PlumaApplication PlumaApplication
Definition at line 46 of file pluma-application.h.
PlumaApplicationClass
typedef struct _PlumaApplicationClass PlumaApplicationClass
Definition at line 59 of file pluma-application.h.
PlumaApplicationPrivate
typedef struct _PlumaApplicationPrivate PlumaApplicationPrivate
Definition at line 41 of file pluma-application.h.
Function Documentation
pluma_application_get_type()
GType pluma_application_get_type (void)
pluma_application_new()
PlumaApplication * pluma_application_new (void)
Definition at line 266 of file pluma-application.c.
References NULL, and PLUMA_TYPE_APPLICATION.
Referenced by main().
pluma_application_set_command_line_options()
void pluma_application_set_command_line_options (PlumaApplication * app, gint line_pos, const gchar * encoding, gboolean new_window, gboolean new_document, GSList * file_list)
Definition at line 231 of file pluma-application.c.
References file_list, NULL, pluma_encoding_get_from_charset(), and _PlumaApplication::priv.
Referenced by main().