MATE Desktop Environment: pluma-commands-view.c File Reference
pluma-commands-view.c File Reference
#include <gtk/gtk.h>
#include "pluma-commands.h"
#include "pluma-debug.h"
#include "pluma-window.h"
#include "pluma-window-private.h"
Functions
void _pluma_cmd_view_show_toolbar (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_view_show_statusbar (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_view_show_side_pane (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_view_show_bottom_pane (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_view_toggle_fullscreen_mode (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_view_leave_fullscreen_mode (GtkAction *action, PlumaWindow *window)
Function Documentation
_pluma_cmd_view_leave_fullscreen_mode()
void _pluma_cmd_view_leave_fullscreen_mode (GtkAction * action, PlumaWindow * window)
Definition at line 139 of file pluma-commands-view.c.
References _pluma_cmd_view_toggle_fullscreen_mode(), _pluma_window_unfullscreen(), _PlumaWindowPrivate::always_sensitive_action_group, FALSE, and _PlumaWindow::priv.
_pluma_cmd_view_show_bottom_pane()
void _pluma_cmd_view_show_bottom_pane (GtkAction * action, PlumaWindow * window)
Definition at line 103 of file pluma-commands-view.c.
References action, DEBUG_COMMANDS, pluma_debug(), and pluma_window_get_bottom_panel().
_pluma_cmd_view_show_side_pane()
void _pluma_cmd_view_show_side_pane (GtkAction * action, PlumaWindow * window)
Definition at line 79 of file pluma-commands-view.c.
References action, DEBUG_COMMANDS, pluma_debug(), and pluma_window_get_side_panel().
_pluma_cmd_view_show_statusbar()
void _pluma_cmd_view_show_statusbar (GtkAction * action, PlumaWindow * window)
Definition at line 63 of file pluma-commands-view.c.
References action, DEBUG_COMMANDS, pluma_debug(), _PlumaWindow::priv, and _PlumaWindowPrivate::statusbar.
_pluma_cmd_view_show_toolbar()
void _pluma_cmd_view_show_toolbar (GtkAction * action, PlumaWindow * window)
Definition at line 47 of file pluma-commands-view.c.
References action, DEBUG_COMMANDS, pluma_debug(), _PlumaWindow::priv, and _PlumaWindowPrivate::toolbar.
_pluma_cmd_view_toggle_fullscreen_mode()
void _pluma_cmd_view_toggle_fullscreen_mode (GtkAction * action, PlumaWindow * window)
Definition at line 127 of file pluma-commands-view.c.
References _pluma_window_fullscreen(), _pluma_window_is_fullscreen(), _pluma_window_unfullscreen(), DEBUG_COMMANDS, and pluma_debug().
Referenced by _pluma_cmd_view_leave_fullscreen_mode().