MATE Desktop Environment: pluma-app.h File Reference
pluma-app.h File Reference
#include <gtk/gtk.h>
#include <pluma/pluma-window.h>
Classes
struct _PlumaApp
struct _PlumaAppClass
Macros
#define PLUMA_TYPE_APP (pluma_app_get_type())
#define PLUMA_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_APP, PlumaApp))
#define PLUMA_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), PLUMA_TYPE_APP, PlumaAppClass))
#define PLUMA_IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), PLUMA_TYPE_APP))
#define PLUMA_IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_APP))
#define PLUMA_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), PLUMA_TYPE_APP, PlumaAppClass))
Typedefs
typedef struct _PlumaAppPrivate PlumaAppPrivate
typedef struct _PlumaApp PlumaApp
typedef struct _PlumaAppClass PlumaAppClass
Enumerations
enum PlumaLockdownMask {
PLUMA_LOCKDOWN_COMMAND_LINE = 1 << 0 , PLUMA_LOCKDOWN_PRINTING = 1 << 1 , PLUMA_LOCKDOWN_PRINT_SETUP = 1 << 2 , PLUMA_LOCKDOWN_SAVE_TO_DISK = 1 << 3 ,
PLUMA_LOCKDOWN_ALL = 0xF
}
Functions
GType pluma_app_get_type (void)
PlumaApp * pluma_app_get_default (void)
PlumaWindow * pluma_app_create_window (PlumaApp *app, GdkScreen *screen)
const GList * pluma_app_get_windows (PlumaApp *app)
PlumaWindow * pluma_app_get_active_window (PlumaApp *app)
GList * pluma_app_get_documents (PlumaApp *app)
GList * pluma_app_get_views (PlumaApp *app)
PlumaLockdownMask pluma_app_get_lockdown (PlumaApp *app)
PlumaWindow * _pluma_app_restore_window (PlumaApp *app, const gchar *role)
PlumaWindow * _pluma_app_get_window_in_viewport (PlumaApp *app, GdkScreen *screen, gint workspace, gint viewport_x, gint viewport_y)
void _pluma_app_set_lockdown (PlumaApp *app, PlumaLockdownMask lockdown)
void _pluma_app_set_lockdown_bit (PlumaApp *app, PlumaLockdownMask bit, gboolean value)
void _pluma_window_set_lockdown (PlumaWindow *window, PlumaLockdownMask lockdown)
GtkPageSetup * _pluma_app_get_default_page_setup (PlumaApp *app)
void _pluma_app_set_default_page_setup (PlumaApp *app, GtkPageSetup *page_setup)
GtkPrintSettings * _pluma_app_get_default_print_settings (PlumaApp *app)
void _pluma_app_set_default_print_settings (PlumaApp *app, GtkPrintSettings *settings)
Macro Definition Documentation
PLUMA_APP
#define PLUMA_APP (obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_APP, PlumaApp))
Definition at line 45 of file pluma-app.h.
PLUMA_APP_CLASS
#define PLUMA_APP_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), PLUMA_TYPE_APP, PlumaAppClass))
Definition at line 46 of file pluma-app.h.
PLUMA_APP_GET_CLASS
#define PLUMA_APP_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS((obj), PLUMA_TYPE_APP, PlumaAppClass))
Definition at line 49 of file pluma-app.h.
PLUMA_IS_APP
#define PLUMA_IS_APP (obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), PLUMA_TYPE_APP))
Definition at line 47 of file pluma-app.h.
PLUMA_IS_APP_CLASS
#define PLUMA_IS_APP_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_APP))
Definition at line 48 of file pluma-app.h.
PLUMA_TYPE_APP
#define PLUMA_TYPE_APP (pluma_app_get_type())
Definition at line 44 of file pluma-app.h.
Typedef Documentation
PlumaApp
typedef struct _PlumaApp PlumaApp
Definition at line 57 of file pluma-app.h.
PlumaAppClass
typedef struct _PlumaAppClass PlumaAppClass
Definition at line 70 of file pluma-app.h.
PlumaAppPrivate
typedef struct _PlumaAppPrivate PlumaAppPrivate
Definition at line 52 of file pluma-app.h.
Enumeration Type Documentation
PlumaLockdownMask
enum PlumaLockdownMask
Enumerator
PLUMA_LOCKDOWN_COMMAND_LINE
PLUMA_LOCKDOWN_PRINTING
PLUMA_LOCKDOWN_PRINT_SETUP
PLUMA_LOCKDOWN_SAVE_TO_DISK
PLUMA_LOCKDOWN_ALL
Definition at line 80 of file pluma-app.h.
Function Documentation
_pluma_app_get_default_page_setup()
GtkPageSetup * _pluma_app_get_default_page_setup (PlumaApp * app)
Definition at line 887 of file pluma-app.c.
References NULL, PLUMA_IS_APP, and _PlumaApp::priv.
_pluma_app_get_default_print_settings()
GtkPrintSettings * _pluma_app_get_default_print_settings (PlumaApp * app)
Definition at line 912 of file pluma-app.c.
References NULL, PLUMA_IS_APP, and _PlumaApp::priv.
_pluma_app_get_window_in_viewport()
PlumaWindow * _pluma_app_get_window_in_viewport (PlumaApp * app, GdkScreen * screen, gint workspace, gint viewport_x, gint viewport_y)
_pluma_app_get_window_in_viewport: @app: the PlumaApp @screen: the #GdkScreen @workspace: the workspace number @viewport_x: the viewport horizontal origin @viewport_y: the viewport vertical origin
Since a workspace can be larger than the screen, it is divided into several equal parts called viewports. This function retrives the PlumaWindow in the given viewport of the given workspace.
Return value: the PlumaWindow in the given viewport of the given workspace.
Definition at line 738 of file pluma-app.c.
References NULL, pluma_app_create_window(), PLUMA_IS_APP, PLUMA_IS_WINDOW, and _PlumaApp::priv.
_pluma_app_restore_window()
PlumaWindow * _pluma_app_restore_window (PlumaApp * app, const gchar * role)
Definition at line 627 of file pluma-app.c.
References FALSE.
_pluma_app_set_default_page_setup()
void _pluma_app_set_default_page_setup (PlumaApp * app, GtkPageSetup * page_setup)
Definition at line 898 of file pluma-app.c.
References NULL, PLUMA_IS_APP, and _PlumaApp::priv.
_pluma_app_set_default_print_settings()
void _pluma_app_set_default_print_settings (PlumaApp * app, GtkPrintSettings * settings)
Definition at line 923 of file pluma-app.c.
References NULL, PLUMA_IS_APP, and _PlumaApp::priv.
_pluma_app_set_lockdown()
void _pluma_app_set_lockdown (PlumaApp * app, PlumaLockdownMask lockdown)
Definition at line 860 of file pluma-app.c.
References PLUMA_IS_APP, and _PlumaApp::priv.
_pluma_app_set_lockdown_bit()
void _pluma_app_set_lockdown_bit (PlumaApp * app, PlumaLockdownMask bit, gboolean value)
Definition at line 871 of file pluma-app.c.
References PLUMA_IS_APP, and _PlumaApp::priv.
_pluma_window_set_lockdown()
void _pluma_window_set_lockdown (PlumaWindow * window, PlumaLockdownMask lockdown)
Definition at line 2610 of file pluma-window.c.
References action, _PlumaWindowPrivate::action_group, _PlumaWindowPrivate::editor_settings, _PlumaWindowPrivate::notebook, PLUMA_LOCKDOWN_SAVE_TO_DISK, PLUMA_SETTINGS_AUTO_SAVE, pluma_window_get_active_tab(), PLUMA_WINDOW_STATE_PRINTING, _PlumaWindow::priv, and _PlumaWindowPrivate::state.
pluma_app_create_window()
PlumaWindow * pluma_app_create_window (PlumaApp * app, GdkScreen * screen)
pluma_app_create_window: @app: the PlumaApp @screen: (allow-none):
Create a new PlumaWindow part of @app.
Return value: (transfer none): the new PlumaWindow
Definition at line 609 of file pluma-app.c.
References NULL, and TRUE.
Referenced by _pluma_app_get_window_in_viewport().
pluma_app_get_active_window()
PlumaWindow * pluma_app_get_active_window (PlumaApp * app)
pluma_app_get_active_window: @app: the PlumaApp
Retrives the PlumaWindow currently active.
Return value: (transfer none): the active PlumaWindow
Definition at line 663 of file pluma-app.c.
References NULL, PLUMA_IS_APP, and _PlumaApp::priv.
pluma_app_get_default()
PlumaApp * pluma_app_get_default (void)
pluma_app_get_default:
Returns the PlumaApp object. This object is a singleton and represents the running pluma instance.
Return value: (transfer none): the PlumaApp pointer
Definition at line 407 of file pluma-app.c.
References NULL, PLUMA_APP, and PLUMA_TYPE_APP.
Referenced by pluma_tab_set_auto_save_enabled().
pluma_app_get_documents()
GList * pluma_app_get_documents (PlumaApp * app)
pluma_app_get_documents: @app: the PlumaApp
Returns all the documents currently open in PlumaApp.
Return value: (element-type Pluma.Document) (transfer container): a newly allocated list of PlumaDocument objects
Definition at line 781 of file pluma-app.c.
References NULL, PLUMA_IS_APP, PLUMA_WINDOW, pluma_window_get_documents(), and _PlumaApp::priv.
pluma_app_get_lockdown()
PlumaLockdownMask pluma_app_get_lockdown (PlumaApp * app)
pluma_app_get_lockdown: @app: a PlumaApp
Gets the lockdown mask (see PlumaLockdownMask) for the application. The lockdown mask determines which functions are locked down using the MATE-wise lockdown GSettings keys.
Definition at line 840 of file pluma-app.c.
References PLUMA_IS_APP, PLUMA_LOCKDOWN_ALL, and _PlumaApp::priv.
Referenced by pluma_tab_set_auto_save_enabled().
pluma_app_get_type()
GType pluma_app_get_type (void)
pluma_app_get_views()
GList * pluma_app_get_views (PlumaApp * app)
pluma_app_get_views: @app: the PlumaApp
Returns all the views currently present in PlumaApp.
Return value: (element-type Pluma.View) (transfer container): a newly allocated list of PlumaView objects
Definition at line 811 of file pluma-app.c.
References NULL, PLUMA_IS_APP, PLUMA_WINDOW, pluma_window_get_views(), and _PlumaApp::priv.
pluma_app_get_windows()
const GList * pluma_app_get_windows (PlumaApp * app)
pluma_app_get_windows: @app: the PlumaApp
Returns all the windows currently present in PlumaApp.
Return value: (element-type Pluma.Window) (transfer none): the list of #PlumaWindows objects. The list should not be freed
Definition at line 647 of file pluma-app.c.
References NULL, PLUMA_IS_APP, and _PlumaApp::priv.