MATE Desktop Environment: pluma-document-saver.c File Reference
pluma-document-saver.c File Reference
#include <glib/gi18n.h>
#include <glib.h>
#include <gio/gio.h>
#include <string.h>
#include "pluma-document-saver.h"
#include "pluma-document-input-stream.h"
#include "pluma-debug.h"
#include "pluma-utils.h"
#include "pluma-enum-types.h"
#include "pluma-settings.h"
Macros
#define WRITE_CHUNK_SIZE 8192
#define REMOTE_QUERY_ATTRIBUTES
Enumerations
enum { SAVING , LAST_SIGNAL }
enum {
PROP_0 , PROP_DOCUMENT , PROP_URI , PROP_ENCODING ,
PROP_NEWLINE_TYPE , PROP_FLAGS
}
Functions
PlumaDocumentSaver * pluma_document_saver_new (PlumaDocument *doc, const gchar *uri, const PlumaEncoding *encoding, PlumaDocumentNewlineType newline_type, PlumaDocumentSaveFlags flags)
void pluma_document_saver_save (PlumaDocumentSaver *saver, gint64 *old_mtime)
void pluma_document_saver_saving (PlumaDocumentSaver *saver, gboolean completed, GError *error)
PlumaDocument * pluma_document_saver_get_document (PlumaDocumentSaver *saver)
const gchar * pluma_document_saver_get_uri (PlumaDocumentSaver *saver)
goffset pluma_document_saver_get_file_size (PlumaDocumentSaver *saver)
goffset pluma_document_saver_get_bytes_written (PlumaDocumentSaver *saver)
GFileInfo * pluma_document_saver_get_info (PlumaDocumentSaver *saver)
Macro Definition Documentation
REMOTE_QUERY_ATTRIBUTES
#define REMOTE_QUERY_ATTRIBUTES
Value:
                                G_FILE_ATTRIBUTE_STANDARD_CONTENT_TYPE "," \
                                G_FILE_ATTRIBUTE_TIME_MODIFIED "," \
                                G_FILE_ATTRIBUTE_TIME_MODIFIED_USEC
Definition at line 80 of file pluma-document-saver.c.
WRITE_CHUNK_SIZE
#define WRITE_CHUNK_SIZE 8192
Definition at line 47 of file pluma-document-saver.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAVING
LAST_SIGNAL
Definition at line 51 of file pluma-document-saver.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_DOCUMENT
PROP_URI
PROP_ENCODING
PROP_NEWLINE_TYPE
PROP_FLAGS
Definition at line 60 of file pluma-document-saver.c.
Function Documentation
pluma_document_saver_get_bytes_written()
goffset pluma_document_saver_get_bytes_written (PlumaDocumentSaver * saver)
Definition at line 1016 of file pluma-document-saver.c.
References PLUMA_IS_DOCUMENT_SAVER, and _PlumaDocumentSaver::priv.
pluma_document_saver_get_document()
PlumaDocument * pluma_document_saver_get_document (PlumaDocumentSaver * saver)
Definition at line 991 of file pluma-document-saver.c.
References NULL, PLUMA_IS_DOCUMENT_SAVER, and _PlumaDocumentSaver::priv.
pluma_document_saver_get_file_size()
goffset pluma_document_saver_get_file_size (PlumaDocumentSaver * saver)
Definition at line 1008 of file pluma-document-saver.c.
References PLUMA_IS_DOCUMENT_SAVER, and _PlumaDocumentSaver::priv.
pluma_document_saver_get_info()
GFileInfo * pluma_document_saver_get_info (PlumaDocumentSaver * saver)
Definition at line 1024 of file pluma-document-saver.c.
References NULL, PLUMA_IS_DOCUMENT_SAVER, and _PlumaDocumentSaver::priv.
pluma_document_saver_get_uri()
const gchar * pluma_document_saver_get_uri (PlumaDocumentSaver * saver)
Definition at line 999 of file pluma-document-saver.c.
References NULL, PLUMA_IS_DOCUMENT_SAVER, and _PlumaDocumentSaver::priv.
pluma_document_saver_new()
PlumaDocumentSaver * pluma_document_saver_new (PlumaDocument * doc, const gchar * uri, const PlumaEncoding * encoding, PlumaDocumentNewlineType newline_type, PlumaDocumentSaveFlags flags)
Definition at line 346 of file pluma-document-saver.c.
References NULL, PLUMA_DOCUMENT_SAVER, and PLUMA_TYPE_DOCUMENT_SAVER.
pluma_document_saver_save()
void pluma_document_saver_save (PlumaDocumentSaver * saver, gint64 * old_mtime)
Definition at line 927 of file pluma-document-saver.c.
References DEBUG_SAVER, FALSE, NULL, pluma_debug(), PLUMA_DOCUMENT_SAVE_PRESERVE_BACKUP, pluma_document_saver_saving(), PLUMA_IS_DOCUMENT_SAVER, PLUMA_SETTINGS_CREATE_BACKUP_COPY, _PlumaDocumentSaver::priv, and TRUE.
pluma_document_saver_saving()
void pluma_document_saver_saving (PlumaDocumentSaver * saver, gboolean completed, GError * error)
Definition at line 965 of file pluma-document-saver.c.
References DEBUG_SAVER, error, NULL, pluma_debug_message(), SAVING, and signals.
Referenced by pluma_document_saver_save().