MATE Desktop Environment: pluma-document-loader.c File Reference
pluma-document-loader.c File Reference
#include <glib/gi18n.h>
#include <glib/gstdio.h>
#include <gio/gio.h>
#include "pluma-document-loader.h"
#include "pluma-document-output-stream.h"
#include "pluma-smart-charset-converter.h"
#include "pluma-debug.h"
#include "pluma-metadata-manager.h"
#include "pluma-utils.h"
#include "pluma-enum-types.h"
#include "pluma-settings.h"
Macros
#define READ_CHUNK_SIZE 8192
#define REMOTE_QUERY_ATTRIBUTES
Enumerations
enum { LOADING , LAST_SIGNAL }
enum {
PROP_0 , PROP_DOCUMENT , PROP_URI , PROP_ENCODING ,
PROP_NEWLINE_TYPE
}
Functions
PlumaDocumentLoader * pluma_document_loader_new (PlumaDocument *doc, const gchar *uri, const PlumaEncoding *encoding)
void pluma_document_loader_loading (PlumaDocumentLoader *loader, gboolean completed, GError *error)
void pluma_document_loader_load (PlumaDocumentLoader *loader)
gboolean pluma_document_loader_cancel (PlumaDocumentLoader *loader)
PlumaDocument * pluma_document_loader_get_document (PlumaDocumentLoader *loader)
const gchar * pluma_document_loader_get_uri (PlumaDocumentLoader *loader)
goffset pluma_document_loader_get_bytes_read (PlumaDocumentLoader *loader)
const PlumaEncoding * pluma_document_loader_get_encoding (PlumaDocumentLoader *loader)
PlumaDocumentNewlineType pluma_document_loader_get_newline_type (PlumaDocumentLoader *loader)
GFileInfo * pluma_document_loader_get_info (PlumaDocumentLoader *loader)
Macro Definition Documentation
READ_CHUNK_SIZE
#define READ_CHUNK_SIZE 8192
Definition at line 82 of file pluma-document-loader.c.
REMOTE_QUERY_ATTRIBUTES
#define REMOTE_QUERY_ATTRIBUTES
Value:
                                G_FILE_ATTRIBUTE_STANDARD_CONTENT_TYPE "," \
                                G_FILE_ATTRIBUTE_STANDARD_TYPE "," \
                                G_FILE_ATTRIBUTE_TIME_MODIFIED "," \
                                G_FILE_ATTRIBUTE_TIME_MODIFIED_USEC "," \
                                G_FILE_ATTRIBUTE_STANDARD_SIZE "," \
                                G_FILE_ATTRIBUTE_ACCESS_CAN_WRITE "," \
                                PLUMA_METADATA_ATTRIBUTE_ENCODING
Definition at line 83 of file pluma-document-loader.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
LOADING
LAST_SIGNAL
Definition at line 64 of file pluma-document-loader.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_DOCUMENT
PROP_URI
PROP_ENCODING
PROP_NEWLINE_TYPE
Definition at line 73 of file pluma-document-loader.c.
Function Documentation
pluma_document_loader_cancel()
gboolean pluma_document_loader_cancel (PlumaDocumentLoader * loader)
Definition at line 867 of file pluma-document-loader.c.
References DEBUG_LOADER, FALSE, NULL, pluma_debug(), PLUMA_IS_DOCUMENT_LOADER, _PlumaDocumentLoader::priv, and TRUE.
Referenced by pluma_document_load_cancel().
pluma_document_loader_get_bytes_read()
goffset pluma_document_loader_get_bytes_read (PlumaDocumentLoader * loader)
Definition at line 906 of file pluma-document-loader.c.
References PLUMA_IS_DOCUMENT_LOADER, and _PlumaDocumentLoader::priv.
pluma_document_loader_get_document()
PlumaDocument * pluma_document_loader_get_document (PlumaDocumentLoader * loader)
Definition at line 889 of file pluma-document-loader.c.
References NULL, PLUMA_IS_DOCUMENT_LOADER, and _PlumaDocumentLoader::priv.
pluma_document_loader_get_encoding()
const PlumaEncoding * pluma_document_loader_get_encoding (PlumaDocumentLoader * loader)
Definition at line 914 of file pluma-document-loader.c.
References NULL, pluma_encoding_get_current(), PLUMA_IS_DOCUMENT_LOADER, and _PlumaDocumentLoader::priv.
pluma_document_loader_get_info()
GFileInfo * pluma_document_loader_get_info (PlumaDocumentLoader * loader)
Definition at line 937 of file pluma-document-loader.c.
References NULL, PLUMA_IS_DOCUMENT_LOADER, and _PlumaDocumentLoader::priv.
pluma_document_loader_get_newline_type()
PlumaDocumentNewlineType pluma_document_loader_get_newline_type (PlumaDocumentLoader * loader)
Definition at line 928 of file pluma-document-loader.c.
References PLUMA_DOCUMENT_NEWLINE_TYPE_LF, PLUMA_IS_DOCUMENT_LOADER, and _PlumaDocumentLoader::priv.
pluma_document_loader_get_uri()
const gchar * pluma_document_loader_get_uri (PlumaDocumentLoader * loader)
Definition at line 898 of file pluma-document-loader.c.
References NULL, PLUMA_IS_DOCUMENT_LOADER, and _PlumaDocumentLoader::priv.
pluma_document_loader_load()
void pluma_document_loader_load (PlumaDocumentLoader * loader)
Definition at line 838 of file pluma-document-loader.c.
References DEBUG_LOADER, FALSE, NULL, pluma_debug(), PLUMA_DOCUMENT_LOADER, pluma_document_loader_loading(), PLUMA_IS_DOCUMENT_LOADER, _PlumaDocumentLoader::priv, and TRUE.
pluma_document_loader_loading()
void pluma_document_loader_loading (PlumaDocumentLoader * loader, gboolean completed, GError * error)
Definition at line 811 of file pluma-document-loader.c.
References DEBUG_LOADER, error, LOADING, NULL, pluma_debug_message(), and signals.
Referenced by pluma_document_loader_load().
pluma_document_loader_new()
PlumaDocumentLoader * pluma_document_loader_new (PlumaDocument * doc, const gchar * uri, const PlumaEncoding * encoding)
Definition at line 315 of file pluma-document-loader.c.
References NULL, PLUMA_DOCUMENT_LOADER, PLUMA_IS_DOCUMENT, and PLUMA_TYPE_DOCUMENT_LOADER.