MATE Desktop Environment: pluma-metadata-manager.h File Reference
pluma-metadata-manager.h File Reference
#include <glib.h>
Functions
void pluma_metadata_manager_shutdown (void)
gchar * pluma_metadata_manager_get (const gchar *uri, const gchar *key)
void pluma_metadata_manager_set (const gchar *uri, const gchar *key, const gchar *value)
Function Documentation
pluma_metadata_manager_get()
gchar * pluma_metadata_manager_get (const gchar * uri, const gchar * key)
Definition at line 304 of file pluma-metadata-manager.c.
References DEBUG_METADATA, item, key, NULL, and pluma_debug_message().
Referenced by pluma_document_get_metadata().
pluma_metadata_manager_set()
void pluma_metadata_manager_set (const gchar * uri, const gchar * key, const gchar * value)
Definition at line 347 of file pluma-metadata-manager.c.
References DEBUG_METADATA, item, key, NULL, and pluma_debug_message().
Referenced by pluma_document_set_metadata().
pluma_metadata_manager_shutdown()
void pluma_metadata_manager_shutdown (void)
Definition at line 131 of file pluma-metadata-manager.c.
References DEBUG_METADATA, NULL, and pluma_debug().