MATE Desktop Environment: pluma-metadata-manager.c File Reference
pluma-metadata-manager.c File Reference
#include <stdlib.h>
#include <libxml/xmlreader.h>
#include "pluma-metadata-manager.h"
#include "pluma-debug.h"
#include "pluma-dirs.h"
Macros
#define METADATA_FILE "pluma-metadata.xml"
#define MAX_ITEMS 50
Typedefs
typedef struct _PlumaMetadataManager PlumaMetadataManager
typedef struct _Item Item
Functions
void pluma_metadata_manager_shutdown (void)
gchar * pluma_metadata_manager_get (const gchar *uri, const gchar *key)
void pluma_metadata_manager_set (const gchar *uri, const gchar *key, const gchar *value)
Macro Definition Documentation
MAX_ITEMS
#define MAX_ITEMS 50
Definition at line 47 of file pluma-metadata-manager.c.
METADATA_FILE
#define METADATA_FILE "pluma-metadata.xml"
Definition at line 45 of file pluma-metadata-manager.c.
Typedef Documentation
Item
typedef struct _Item Item
Definition at line 51 of file pluma-metadata-manager.c.
PlumaMetadataManager
typedef struct _PlumaMetadataManager PlumaMetadataManager
Definition at line 49 of file pluma-metadata-manager.c.
Function Documentation
pluma_metadata_manager_get()
gchar * pluma_metadata_manager_get (const gchar * uri, const gchar * key)
Definition at line 304 of file pluma-metadata-manager.c.
References DEBUG_METADATA, item, key, NULL, and pluma_debug_message().
Referenced by pluma_document_get_metadata().
pluma_metadata_manager_set()
void pluma_metadata_manager_set (const gchar * uri, const gchar * key, const gchar * value)
Definition at line 347 of file pluma-metadata-manager.c.
References DEBUG_METADATA, item, key, NULL, and pluma_debug_message().
Referenced by pluma_document_set_metadata().
pluma_metadata_manager_shutdown()
void pluma_metadata_manager_shutdown (void)
Definition at line 131 of file pluma-metadata-manager.c.
References DEBUG_METADATA, NULL, and pluma_debug().