MATE Desktop Environment: pluma-document-saver.h File Reference
pluma-document-saver.h File Reference
#include <pluma/pluma-document.h>
Classes
struct _PlumaDocumentSaver
struct _PlumaDocumentSaverClass
Macros
#define PLUMA_TYPE_DOCUMENT_SAVER (pluma_document_saver_get_type())
#define PLUMA_DOCUMENT_SAVER(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_DOCUMENT_SAVER, PlumaDocumentSaver))
#define PLUMA_DOCUMENT_SAVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), PLUMA_TYPE_DOCUMENT_SAVER, PlumaDocumentSaverClass))
#define PLUMA_IS_DOCUMENT_SAVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), PLUMA_TYPE_DOCUMENT_SAVER))
#define PLUMA_IS_DOCUMENT_SAVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_DOCUMENT_SAVER))
#define PLUMA_DOCUMENT_SAVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), PLUMA_TYPE_DOCUMENT_SAVER, PlumaDocumentSaverClass))
Typedefs
typedef struct _PlumaDocumentSaverPrivate PlumaDocumentSaverPrivate
typedef struct _PlumaDocumentSaver PlumaDocumentSaver
typedef struct _PlumaDocumentSaverClass PlumaDocumentSaverClass
Functions
GType pluma_document_saver_get_type (void)
PlumaDocumentSaver * pluma_document_saver_new (PlumaDocument *doc, const gchar *uri, const PlumaEncoding *encoding, PlumaDocumentNewlineType newline_type, PlumaDocumentSaveFlags flags)
void pluma_document_saver_saving (PlumaDocumentSaver *saver, gboolean completed, GError *error)
void pluma_document_saver_save (PlumaDocumentSaver *saver, gint64 *old_mtime)
PlumaDocument * pluma_document_saver_get_document (PlumaDocumentSaver *saver)
const gchar * pluma_document_saver_get_uri (PlumaDocumentSaver *saver)
const gchar * pluma_document_saver_get_backup_uri (PlumaDocumentSaver *saver)
void * pluma_document_saver_set_backup_uri (PlumaDocumentSaver *saver, const gchar *backup_uri)
goffset pluma_document_saver_get_file_size (PlumaDocumentSaver *saver)
goffset pluma_document_saver_get_bytes_written (PlumaDocumentSaver *saver)
GFileInfo * pluma_document_saver_get_info (PlumaDocumentSaver *saver)
Macro Definition Documentation
PLUMA_DOCUMENT_SAVER
#define PLUMA_DOCUMENT_SAVER (obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_DOCUMENT_SAVER, PlumaDocumentSaver))
Definition at line 44 of file pluma-document-saver.h.
PLUMA_DOCUMENT_SAVER_CLASS
#define PLUMA_DOCUMENT_SAVER_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), PLUMA_TYPE_DOCUMENT_SAVER, PlumaDocumentSaverClass))
Definition at line 45 of file pluma-document-saver.h.
PLUMA_DOCUMENT_SAVER_GET_CLASS
#define PLUMA_DOCUMENT_SAVER_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS((obj), PLUMA_TYPE_DOCUMENT_SAVER, PlumaDocumentSaverClass))
Definition at line 48 of file pluma-document-saver.h.
PLUMA_IS_DOCUMENT_SAVER
#define PLUMA_IS_DOCUMENT_SAVER (obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), PLUMA_TYPE_DOCUMENT_SAVER))
Definition at line 46 of file pluma-document-saver.h.
PLUMA_IS_DOCUMENT_SAVER_CLASS
#define PLUMA_IS_DOCUMENT_SAVER_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_DOCUMENT_SAVER))
Definition at line 47 of file pluma-document-saver.h.
PLUMA_TYPE_DOCUMENT_SAVER
#define PLUMA_TYPE_DOCUMENT_SAVER (pluma_document_saver_get_type())
Definition at line 43 of file pluma-document-saver.h.
Typedef Documentation
PlumaDocumentSaver
typedef struct _PlumaDocumentSaver PlumaDocumentSaver
Definition at line 56 of file pluma-document-saver.h.
PlumaDocumentSaverClass
typedef struct _PlumaDocumentSaverClass PlumaDocumentSaverClass
Definition at line 67 of file pluma-document-saver.h.
PlumaDocumentSaverPrivate
typedef struct _PlumaDocumentSaverPrivate PlumaDocumentSaverPrivate
Definition at line 51 of file pluma-document-saver.h.
Function Documentation
pluma_document_saver_get_backup_uri()
const gchar * pluma_document_saver_get_backup_uri (PlumaDocumentSaver * saver)
pluma_document_saver_get_bytes_written()
goffset pluma_document_saver_get_bytes_written (PlumaDocumentSaver * saver)
Definition at line 1016 of file pluma-document-saver.c.
References PLUMA_IS_DOCUMENT_SAVER, and _PlumaDocumentSaver::priv.
pluma_document_saver_get_document()
PlumaDocument * pluma_document_saver_get_document (PlumaDocumentSaver * saver)
Definition at line 991 of file pluma-document-saver.c.
References NULL, PLUMA_IS_DOCUMENT_SAVER, and _PlumaDocumentSaver::priv.
pluma_document_saver_get_file_size()
goffset pluma_document_saver_get_file_size (PlumaDocumentSaver * saver)
Definition at line 1008 of file pluma-document-saver.c.
References PLUMA_IS_DOCUMENT_SAVER, and _PlumaDocumentSaver::priv.
pluma_document_saver_get_info()
GFileInfo * pluma_document_saver_get_info (PlumaDocumentSaver * saver)
Definition at line 1024 of file pluma-document-saver.c.
References NULL, PLUMA_IS_DOCUMENT_SAVER, and _PlumaDocumentSaver::priv.
pluma_document_saver_get_type()
GType pluma_document_saver_get_type (void)
pluma_document_saver_get_uri()
const gchar * pluma_document_saver_get_uri (PlumaDocumentSaver * saver)
Definition at line 999 of file pluma-document-saver.c.
References NULL, PLUMA_IS_DOCUMENT_SAVER, and _PlumaDocumentSaver::priv.
pluma_document_saver_new()
PlumaDocumentSaver * pluma_document_saver_new (PlumaDocument * doc, const gchar * uri, const PlumaEncoding * encoding, PlumaDocumentNewlineType newline_type, PlumaDocumentSaveFlags flags)
Definition at line 346 of file pluma-document-saver.c.
References NULL, PLUMA_DOCUMENT_SAVER, and PLUMA_TYPE_DOCUMENT_SAVER.
pluma_document_saver_save()
void pluma_document_saver_save (PlumaDocumentSaver * saver, gint64 * old_mtime)
Definition at line 927 of file pluma-document-saver.c.
References DEBUG_SAVER, FALSE, NULL, pluma_debug(), PLUMA_DOCUMENT_SAVE_PRESERVE_BACKUP, pluma_document_saver_saving(), PLUMA_IS_DOCUMENT_SAVER, PLUMA_SETTINGS_CREATE_BACKUP_COPY, _PlumaDocumentSaver::priv, and TRUE.
pluma_document_saver_saving()
void pluma_document_saver_saving (PlumaDocumentSaver * saver, gboolean completed, GError * error)
Definition at line 965 of file pluma-document-saver.c.
References DEBUG_SAVER, error, NULL, pluma_debug_message(), SAVING, and signals.
Referenced by pluma_document_saver_save().
pluma_document_saver_set_backup_uri()
void * pluma_document_saver_set_backup_uri (PlumaDocumentSaver * saver, const gchar * backup_uri)