MATE Desktop Environment: pluma-spell-checker.h File Reference
pluma-spell-checker.h File Reference
#include <glib.h>
#include <glib-object.h>
#include "pluma-spell-checker-language.h"
Classes
struct _PlumaSpellCheckerClass
Macros
#define PLUMA_TYPE_SPELL_CHECKER (pluma_spell_checker_get_type ())
#define PLUMA_SPELL_CHECKER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_SPELL_CHECKER, PlumaSpellChecker))
#define PLUMA_SPELL_CHECKER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLUMA_TYPE_SPELL_CHECKER, PlumaSpellChecker))
#define PLUMA_IS_SPELL_CHECKER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLUMA_TYPE_SPELL_CHECKER))
#define PLUMA_IS_SPELL_CHECKER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_SPELL_CHECKER))
#define PLUMA_SPELL_CHECKER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLUMA_TYPE_SPELL_CHECKER, PlumaSpellChecker))
Typedefs
typedef struct _PlumaSpellChecker PlumaSpellChecker
typedef struct _PlumaSpellCheckerClass PlumaSpellCheckerClass
Functions
GType pluma_spell_checker_get_type (void)
PlumaSpellChecker * pluma_spell_checker_new (void)
gboolean pluma_spell_checker_set_language (PlumaSpellChecker *spell, const PlumaSpellCheckerLanguage *lang)
const PlumaSpellCheckerLanguage * pluma_spell_checker_get_language (PlumaSpellChecker *spell)
gboolean pluma_spell_checker_check_word (PlumaSpellChecker *spell, const gchar *word, gssize len)
GSList * pluma_spell_checker_get_suggestions (PlumaSpellChecker *spell, const gchar *word, gssize len)
gboolean pluma_spell_checker_add_word_to_personal (PlumaSpellChecker *spell, const gchar *word, gssize len)
gboolean pluma_spell_checker_add_word_to_session (PlumaSpellChecker *spell, const gchar *word, gssize len)
gboolean pluma_spell_checker_clear_session (PlumaSpellChecker *spell)
gboolean pluma_spell_checker_set_correction (PlumaSpellChecker *spell, const gchar *word, gssize w_len, const gchar *replacement, gssize r_len)
Macro Definition Documentation
PLUMA_IS_SPELL_CHECKER
#define PLUMA_IS_SPELL_CHECKER (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLUMA_TYPE_SPELL_CHECKER))
Definition at line 44 of file pluma-spell-checker.h.
PLUMA_IS_SPELL_CHECKER_CLASS
#define PLUMA_IS_SPELL_CHECKER_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_SPELL_CHECKER))
Definition at line 45 of file pluma-spell-checker.h.
PLUMA_SPELL_CHECKER
#define PLUMA_SPELL_CHECKER (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_SPELL_CHECKER, PlumaSpellChecker))
Definition at line 42 of file pluma-spell-checker.h.
PLUMA_SPELL_CHECKER_CLASS
#define PLUMA_SPELL_CHECKER_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLUMA_TYPE_SPELL_CHECKER, PlumaSpellChecker))
Definition at line 43 of file pluma-spell-checker.h.
PLUMA_SPELL_CHECKER_GET_CLASS
#define PLUMA_SPELL_CHECKER_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLUMA_TYPE_SPELL_CHECKER, PlumaSpellChecker))
Definition at line 46 of file pluma-spell-checker.h.
PLUMA_TYPE_SPELL_CHECKER
#define PLUMA_TYPE_SPELL_CHECKER (pluma_spell_checker_get_type ())
Definition at line 41 of file pluma-spell-checker.h.
Typedef Documentation
PlumaSpellChecker
typedef struct _PlumaSpellChecker PlumaSpellChecker
Definition at line 48 of file pluma-spell-checker.h.
PlumaSpellCheckerClass
typedef struct _PlumaSpellCheckerClass PlumaSpellCheckerClass
Definition at line 50 of file pluma-spell-checker.h.
Function Documentation
pluma_spell_checker_add_word_to_personal()
gboolean pluma_spell_checker_add_word_to_personal (PlumaSpellChecker * spell, const gchar * word, gssize len)
Definition at line 419 of file pluma-spell-checker.c.
References ADD_WORD_TO_PERSONAL, FALSE, NULL, PLUMA_IS_SPELL_CHECKER, signals, and TRUE.
pluma_spell_checker_add_word_to_session()
gboolean pluma_spell_checker_add_word_to_session (PlumaSpellChecker * spell, const gchar * word, gssize len)
Definition at line 443 of file pluma-spell-checker.c.
References ADD_WORD_TO_SESSION, FALSE, NULL, PLUMA_IS_SPELL_CHECKER, signals, and TRUE.
pluma_spell_checker_check_word()
gboolean pluma_spell_checker_check_word (PlumaSpellChecker * spell, const gchar * word, gssize len)
Definition at line 324 of file pluma-spell-checker.c.
References FALSE, NULL, PLUMA_IS_SPELL_CHECKER, pluma_spell_utils_is_digit(), and TRUE.
Referenced by pluma_spell_checker_dialog_set_misspelled_word().
pluma_spell_checker_clear_session()
gboolean pluma_spell_checker_clear_session (PlumaSpellChecker * spell)
Definition at line 466 of file pluma-spell-checker.c.
References CLEAR_SESSION, FALSE, NULL, PLUMA_IS_SPELL_CHECKER, signals, and TRUE.
pluma_spell_checker_get_language()
const PlumaSpellCheckerLanguage * pluma_spell_checker_get_language (PlumaSpellChecker * spell)
Definition at line 313 of file pluma-spell-checker.c.
References NULL, and PLUMA_IS_SPELL_CHECKER.
Referenced by pluma_spell_checker_dialog_set_spell_checker().
pluma_spell_checker_get_suggestions()
GSList * pluma_spell_checker_get_suggestions (PlumaSpellChecker * spell, const gchar * word, gssize len)
Definition at line 377 of file pluma-spell-checker.c.
References NULL, and PLUMA_IS_SPELL_CHECKER.
Referenced by pluma_spell_checker_dialog_set_misspelled_word().
pluma_spell_checker_get_type()
GType pluma_spell_checker_get_type (void)
pluma_spell_checker_new()
PlumaSpellChecker * pluma_spell_checker_new (void)
Definition at line 201 of file pluma-spell-checker.c.
References NULL, PLUMA_SPELL_CHECKER, and PLUMA_TYPE_SPELL_CHECKER.
pluma_spell_checker_set_correction()
gboolean pluma_spell_checker_set_correction (PlumaSpellChecker * spell, const gchar * word, gssize w_len, const gchar * replacement, gssize r_len)
Definition at line 490 of file pluma-spell-checker.c.
References FALSE, NULL, PLUMA_IS_SPELL_CHECKER, and TRUE.
pluma_spell_checker_set_language()
gboolean pluma_spell_checker_set_language (PlumaSpellChecker * spell, const PlumaSpellCheckerLanguage * lang)
Definition at line 288 of file pluma-spell-checker.c.
References FALSE, NULL, PLUMA_IS_SPELL_CHECKER, pluma_spell_checker_language_to_string(), SET_LANGUAGE, and signals.