MATE Desktop Environment: pluma-file-browser-messages.c File Reference
pluma-file-browser-messages.c File Reference
#include "pluma-file-browser-messages.h"
#include "pluma-file-browser-store.h"
#include <pluma/pluma-message.h>
Macros
#define MESSAGE_OBJECT_PATH "/plugins/filebrowser"
#define WINDOW_DATA_KEY "PlumaFileBrowserMessagesWindowData"
#define BUS_CONNECT(bus, name, data) pluma_message_bus_connect(bus, MESSAGE_OBJECT_PATH, #name, (PlumaMessageCallback) message_##name##_cb, data, NULL)
Functions
void pluma_file_browser_messages_register (PlumaWindow *window, PlumaFileBrowserWidget *widget)
void pluma_file_browser_messages_unregister (PlumaWindow *window)
Macro Definition Documentation
BUS_CONNECT
#define BUS_CONNECT (bus, name, data) pluma_message_bus_connect(bus, MESSAGE_OBJECT_PATH, #name, (PlumaMessageCallback) message_##name##_cb, data, NULL)
Definition at line 8 of file pluma-file-browser-messages.c.
MESSAGE_OBJECT_PATH
#define MESSAGE_OBJECT_PATH "/plugins/filebrowser"
Definition at line 5 of file pluma-file-browser-messages.c.
WINDOW_DATA_KEY
#define WINDOW_DATA_KEY "PlumaFileBrowserMessagesWindowData"
Definition at line 6 of file pluma-file-browser-messages.c.
Function Documentation
pluma_file_browser_messages_register()
void pluma_file_browser_messages_register (PlumaWindow * window, PlumaFileBrowserWidget * widget)
Definition at line 994 of file pluma-file-browser-messages.c.
References pluma_window_get_message_bus().
pluma_file_browser_messages_unregister()
void pluma_file_browser_messages_unregister (PlumaWindow * window)
Definition at line 1026 of file pluma-file-browser-messages.c.
References MESSAGE_OBJECT_PATH, pluma_message_bus_unregister_all(), and pluma_window_get_message_bus().