MATE Desktop Environment: pluma-window.h File Reference
pluma-window.h File Reference
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <pluma/pluma-tab.h>
#include <pluma/pluma-panel.h>
#include <pluma/pluma-message-bus.h>
Classes
struct _PlumaWindow
struct _PlumaWindowClass
Macros
#define PLUMA_TYPE_WINDOW (pluma_window_get_type())
#define PLUMA_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_WINDOW, PlumaWindow))
#define PLUMA_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), PLUMA_TYPE_WINDOW, PlumaWindowClass))
#define PLUMA_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), PLUMA_TYPE_WINDOW))
#define PLUMA_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_WINDOW))
#define PLUMA_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), PLUMA_TYPE_WINDOW, PlumaWindowClass))
Typedefs
typedef struct _PlumaWindowPrivate PlumaWindowPrivate
typedef struct _PlumaWindow PlumaWindow
typedef struct _PlumaWindowClass PlumaWindowClass
Enumerations
enum PlumaWindowState {
PLUMA_WINDOW_STATE_NORMAL = 0 , PLUMA_WINDOW_STATE_SAVING = 1 << 1 , PLUMA_WINDOW_STATE_PRINTING = 1 << 2 , PLUMA_WINDOW_STATE_LOADING = 1 << 3 ,
PLUMA_WINDOW_STATE_ERROR = 1 << 4 , PLUMA_WINDOW_STATE_SAVING_SESSION = 1 << 5
}
Functions
GType pluma_window_get_type (void)
PlumaTab * pluma_window_create_tab (PlumaWindow *window, gboolean jump_to)
PlumaTab * pluma_window_create_tab_from_uri (PlumaWindow *window, const gchar *uri, const PlumaEncoding *encoding, gint line_pos, gboolean create, gboolean jump_to)
void pluma_window_close_tab (PlumaWindow *window, PlumaTab *tab)
void pluma_window_close_all_tabs (PlumaWindow *window)
void pluma_window_close_tabs (PlumaWindow *window, const GList *tabs)
PlumaTab * pluma_window_get_active_tab (PlumaWindow *window)
void pluma_window_set_active_tab (PlumaWindow *window, PlumaTab *tab)
PlumaView * pluma_window_get_active_view (PlumaWindow *window)
PlumaDocument * pluma_window_get_active_document (PlumaWindow *window)
GList * pluma_window_get_documents (PlumaWindow *window)
GList * pluma_window_get_unsaved_documents (PlumaWindow *window)
GList * pluma_window_get_views (PlumaWindow *window)
GtkWindowGroup * pluma_window_get_group (PlumaWindow *window)
PlumaPanel * pluma_window_get_side_panel (PlumaWindow *window)
PlumaPanel * pluma_window_get_bottom_panel (PlumaWindow *window)
PlumaPanel * pluma_window_get_right_panel (PlumaWindow *window)
GtkWidget * pluma_window_get_statusbar (PlumaWindow *window)
GtkUIManager * pluma_window_get_ui_manager (PlumaWindow *window)
PlumaWindowState pluma_window_get_state (PlumaWindow *window)
PlumaTab * pluma_window_get_tab_from_location (PlumaWindow *window, GFile *location)
PlumaMessageBus * pluma_window_get_message_bus (PlumaWindow *window)
GtkWidget * _pluma_window_get_notebook (PlumaWindow *window)
PlumaWindow * _pluma_window_move_tab_to_new_window (PlumaWindow *window, PlumaTab *tab)
gboolean _pluma_window_is_removing_tabs (PlumaWindow *window)
GFile * _pluma_window_get_default_location (PlumaWindow *window)
void _pluma_window_set_default_location (PlumaWindow *window, GFile *location)
void _pluma_window_set_saving_session_state (PlumaWindow *window, gboolean saving_session)
void _pluma_window_fullscreen (PlumaWindow *window)
void _pluma_window_unfullscreen (PlumaWindow *window)
gboolean _pluma_window_is_fullscreen (PlumaWindow *window)
void _pluma_recent_add (PlumaWindow *window, const gchar *uri, const gchar *mime)
void _pluma_recent_remove (PlumaWindow *window, const gchar *uri)
Macro Definition Documentation
PLUMA_IS_WINDOW
#define PLUMA_IS_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), PLUMA_TYPE_WINDOW))
Definition at line 60 of file pluma-window.h.
PLUMA_IS_WINDOW_CLASS
#define PLUMA_IS_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_WINDOW))
Definition at line 61 of file pluma-window.h.
PLUMA_TYPE_WINDOW
#define PLUMA_TYPE_WINDOW (pluma_window_get_type())
Definition at line 57 of file pluma-window.h.
PLUMA_WINDOW
#define PLUMA_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_WINDOW, PlumaWindow))
Definition at line 58 of file pluma-window.h.
PLUMA_WINDOW_CLASS
#define PLUMA_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), PLUMA_TYPE_WINDOW, PlumaWindowClass))
Definition at line 59 of file pluma-window.h.
PLUMA_WINDOW_GET_CLASS
#define PLUMA_WINDOW_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS((obj), PLUMA_TYPE_WINDOW, PlumaWindowClass))
Definition at line 62 of file pluma-window.h.
Typedef Documentation
PlumaWindow
typedef struct _PlumaWindow PlumaWindow
Definition at line 70 of file pluma-window.h.
PlumaWindowClass
typedef struct _PlumaWindowClass PlumaWindowClass
Definition at line 83 of file pluma-window.h.
PlumaWindowPrivate
typedef struct _PlumaWindowPrivate PlumaWindowPrivate
Definition at line 65 of file pluma-window.h.
Enumeration Type Documentation
PlumaWindowState
enum PlumaWindowState
Enumerator
PLUMA_WINDOW_STATE_NORMAL
PLUMA_WINDOW_STATE_SAVING
PLUMA_WINDOW_STATE_PRINTING
PLUMA_WINDOW_STATE_LOADING
PLUMA_WINDOW_STATE_ERROR
PLUMA_WINDOW_STATE_SAVING_SESSION
Definition at line 44 of file pluma-window.h.
Function Documentation
_pluma_recent_add()
void _pluma_recent_add (PlumaWindow * window, const gchar * uri, const gchar * mime)
Definition at line 1187 of file pluma-window.c.
References FALSE, and NULL.
_pluma_recent_remove()
void _pluma_recent_remove (PlumaWindow * window, const gchar * uri)
Definition at line 1217 of file pluma-window.c.
References NULL.
_pluma_window_fullscreen()
void _pluma_window_fullscreen (PlumaWindow * window)
Definition at line 4798 of file pluma-window.c.
References _pluma_window_is_fullscreen(), FALSE, _PlumaWindowPrivate::menubar, _PlumaWindowPrivate::notebook, PLUMA_IS_WINDOW, _PlumaWindow::priv, _PlumaWindowPrivate::statusbar, _PlumaWindowPrivate::toolbar, and _PlumaWindow::window.
Referenced by _pluma_cmd_view_toggle_fullscreen_mode().
_pluma_window_get_default_location()
GFile * _pluma_window_get_default_location (PlumaWindow * window)
Definition at line 4697 of file pluma-window.c.
References _PlumaWindowPrivate::default_location, NULL, PLUMA_IS_WINDOW, and _PlumaWindow::priv.
Referenced by _pluma_cmd_file_open().
_pluma_window_get_notebook()
GtkWidget * _pluma_window_get_notebook (PlumaWindow * window)
Definition at line 4276 of file pluma-window.c.
References _PlumaWindowPrivate::notebook, NULL, PLUMA_IS_WINDOW, and _PlumaWindow::priv.
Referenced by _pluma_cmd_documents_move_to_new_window(), _pluma_cmd_documents_next_document(), and _pluma_cmd_documents_previous_document().
_pluma_window_is_fullscreen()
gboolean _pluma_window_is_fullscreen (PlumaWindow * window)
Definition at line 4868 of file pluma-window.c.
References FALSE, PLUMA_IS_WINDOW, _PlumaWindow::priv, and _PlumaWindowPrivate::window_state.
Referenced by _pluma_cmd_view_toggle_fullscreen_mode(), _pluma_window_fullscreen(), and _pluma_window_unfullscreen().
_pluma_window_is_removing_tabs()
gboolean _pluma_window_is_removing_tabs (PlumaWindow * window)
Definition at line 4593 of file pluma-window.c.
References FALSE, PLUMA_IS_WINDOW, _PlumaWindow::priv, and _PlumaWindowPrivate::removing_tabs.
_pluma_window_move_tab_to_new_window()
PlumaWindow * _pluma_window_move_tab_to_new_window (PlumaWindow * window, PlumaTab * tab)
Definition at line 4530 of file pluma-window.c.
References _PlumaWindowPrivate::notebook, NULL, PLUMA_IS_TAB, PLUMA_IS_WINDOW, PLUMA_NOTEBOOK, pluma_notebook_move_tab(), and _PlumaWindow::priv.
Referenced by _pluma_cmd_documents_move_to_new_window().
_pluma_window_set_default_location()
void _pluma_window_set_default_location (PlumaWindow * window, GFile * location)
Definition at line 4706 of file pluma-window.c.
References _PlumaWindowPrivate::default_location, NULL, PLUMA_IS_WINDOW, and _PlumaWindow::priv.
_pluma_window_set_saving_session_state()
void _pluma_window_set_saving_session_state (PlumaWindow * window, gboolean saving_session)
Definition at line 4767 of file pluma-window.c.
References PLUMA_IS_WINDOW, PLUMA_WINDOW_STATE_SAVING_SESSION, _PlumaWindow::priv, and _PlumaWindowPrivate::state.
_pluma_window_unfullscreen()
void _pluma_window_unfullscreen (PlumaWindow * window)
Definition at line 4828 of file pluma-window.c.
References _pluma_window_is_fullscreen(), action, _PlumaWindowPrivate::always_sensitive_action_group, _PlumaWindowPrivate::fullscreen_controls, _PlumaWindowPrivate::menubar, _PlumaWindowPrivate::notebook, PLUMA_IS_WINDOW, _PlumaWindow::priv, _PlumaWindowPrivate::statusbar, _PlumaWindowPrivate::toolbar, TRUE, and _PlumaWindow::window.
Referenced by _pluma_cmd_view_leave_fullscreen_mode(), and _pluma_cmd_view_toggle_fullscreen_mode().
pluma_window_close_all_tabs()
void pluma_window_close_all_tabs (PlumaWindow * window)
pluma_window_close_all_tabs: @window: a PlumaWindow
Closes all opened tabs.
Definition at line 4482 of file pluma-window.c.
References FALSE, _PlumaWindowPrivate::notebook, PLUMA_IS_WINDOW, PLUMA_NOTEBOOK, pluma_notebook_remove_all_tabs(), PLUMA_WINDOW_STATE_SAVING, PLUMA_WINDOW_STATE_SAVING_SESSION, _PlumaWindow::priv, _PlumaWindowPrivate::removing_tabs, _PlumaWindowPrivate::state, and TRUE.
pluma_window_close_tab()
void pluma_window_close_tab (PlumaWindow * window, PlumaTab * tab)
pluma_window_close_tab: @window: a PlumaWindow @tab: the PlumaTab to close
Closes the @tab.
Definition at line 4464 of file pluma-window.c.
References _PlumaWindowPrivate::notebook, PLUMA_IS_TAB, PLUMA_IS_WINDOW, PLUMA_NOTEBOOK, pluma_notebook_remove_tab(), pluma_tab_get_state(), PLUMA_TAB_STATE_SAVING, PLUMA_TAB_STATE_SHOWING_PRINT_PREVIEW, and _PlumaWindow::priv.
Referenced by _pluma_cmd_file_close_tab().
pluma_window_close_tabs()
void pluma_window_close_tabs (PlumaWindow * window, const GList * tabs)
pluma_window_close_tabs: @window: a PlumaWindow @tabs: (element-type Pluma.Tab): a list of PlumaTab
Closes all tabs specified by @tabs.
Definition at line 4503 of file pluma-window.c.
References FALSE, _PlumaWindowPrivate::notebook, NULL, PLUMA_IS_WINDOW, PLUMA_NOTEBOOK, pluma_notebook_remove_tab(), PLUMA_TAB, PLUMA_WINDOW_STATE_SAVING, PLUMA_WINDOW_STATE_SAVING_SESSION, _PlumaWindow::priv, _PlumaWindowPrivate::removing_tabs, _PlumaWindowPrivate::state, and TRUE.
pluma_window_create_tab()
PlumaTab * pluma_window_create_tab (PlumaWindow * window, gboolean jump_to)
pluma_window_create_tab: @window: a PlumaWindow @jump_to: TRUE to set the new PlumaTab as active
Creates a new PlumaTab and adds the new tab to the PlumaNotebook. In case @jump_to is TRUE the PlumaNotebook switches to that new PlumaTab.
Returns: (transfer none): a new PlumaTab
Definition at line 4294 of file pluma-window.c.
References _pluma_tab_new(), _PlumaWindowPrivate::notebook, NULL, PLUMA_IS_WINDOW, PLUMA_NOTEBOOK, pluma_notebook_add_tab(), PLUMA_TAB, and _PlumaWindow::priv.
Referenced by _pluma_cmd_file_new().
pluma_window_create_tab_from_uri()
PlumaTab * pluma_window_create_tab_from_uri (PlumaWindow * window, const gchar * uri, const PlumaEncoding * encoding, gint line_pos, gboolean create, gboolean jump_to)
pluma_window_create_tab_from_uri: @window: a PlumaWindow @uri: the uri of the document @encoding: a PlumaEncoding @line_pos: the line position to visualize @create: TRUE to create a new document in case @uri does exist @jump_to: TRUE to set the new PlumaTab as active
Creates a new PlumaTab loading the document specified by @uri. In case @jump_to is TRUE the PlumaNotebook swithes to that new PlumaTab. Whether @create is TRUE, creates a new empty document if location does not refer to an existing file
Returns: (transfer none): a new PlumaTab
Definition at line 4334 of file pluma-window.c.
References _pluma_tab_new_from_uri(), _PlumaWindowPrivate::notebook, NULL, PLUMA_IS_WINDOW, PLUMA_NOTEBOOK, pluma_notebook_add_tab(), PLUMA_TAB, and _PlumaWindow::priv.
pluma_window_get_active_document()
PlumaDocument * pluma_window_get_active_document (PlumaWindow * window)
pluma_window_get_active_document: @window: a PlumaWindow
Gets the active PlumaDocument.
Returns: (transfer none): the active PlumaDocument
Definition at line 4262 of file pluma-window.c.
References NULL, PLUMA_DOCUMENT, PLUMA_IS_WINDOW, and pluma_window_get_active_view().
Referenced by _pluma_cmd_file_open(), _pluma_cmd_search_clear_highlight(), _pluma_cmd_search_find(), and _pluma_cmd_search_replace().
pluma_window_get_active_tab()
PlumaTab * pluma_window_get_active_tab (PlumaWindow * window)
pluma_window_get_active_tab: @window: a PlumaWindow
Gets the active PlumaTab in the @window.
Returns: (transfer none): the active PlumaTab in the @window.
Definition at line 4377 of file pluma-window.c.
References _PlumaWindowPrivate::active_tab, NULL, PLUMA_IS_WINDOW, PLUMA_TAB, and _PlumaWindow::priv.
Referenced by _pluma_cmd_documents_move_to_new_window(), _pluma_cmd_file_close(), _pluma_cmd_file_print(), _pluma_cmd_file_print_preview(), _pluma_cmd_file_revert(), _pluma_cmd_file_save(), _pluma_cmd_file_save_as(), and _pluma_window_set_lockdown().
pluma_window_get_active_view()
PlumaView * pluma_window_get_active_view (PlumaWindow * window)
pluma_window_get_active_view: @window: a PlumaWindow
Gets the active PlumaView.
Returns: (transfer none): the active PlumaView
Definition at line 4239 of file pluma-window.c.
References _PlumaWindowPrivate::active_tab, NULL, PLUMA_IS_WINDOW, PLUMA_TAB, pluma_tab_get_view(), and _PlumaWindow::priv.
Referenced by _pluma_cmd_edit_copy(), _pluma_cmd_edit_cut(), _pluma_cmd_edit_delete(), _pluma_cmd_edit_invert_case(), _pluma_cmd_edit_lower_case(), _pluma_cmd_edit_paste(), _pluma_cmd_edit_redo(), _pluma_cmd_edit_select_all(), _pluma_cmd_edit_title_case(), _pluma_cmd_edit_undo(), _pluma_cmd_edit_upper_case(), _pluma_cmd_search_goto_line(), _pluma_cmd_search_incremental_search(), and pluma_window_get_active_document().
pluma_window_get_bottom_panel()
PlumaPanel * pluma_window_get_bottom_panel (PlumaWindow * window)
pluma_window_get_bottom_panel: @window: a PlumaWindow
Gets the bottom PlumaPanel of the @window.
Returns: (transfer none): the bottom PlumaPanel.
Definition at line 4641 of file pluma-window.c.
References _PlumaWindowPrivate::bottom_panel, NULL, PLUMA_IS_WINDOW, PLUMA_PANEL, and _PlumaWindow::priv.
Referenced by _pluma_cmd_view_show_bottom_pane().
pluma_window_get_documents()
GList * pluma_window_get_documents (PlumaWindow * window)
pluma_window_get_documents: @window: a PlumaWindow
Gets a newly allocated list with all the documents in the window. This list must be freed.
Returns: (element-type Pluma.Document) (transfer container): a newly allocated list with all the documents in the window
Definition at line 4406 of file pluma-window.c.
References _PlumaWindowPrivate::notebook, NULL, PLUMA_IS_WINDOW, and _PlumaWindow::priv.
Referenced by pluma_app_get_documents(), and pluma_commands_save_all_documents().
pluma_window_get_group()
GtkWindowGroup * pluma_window_get_group (PlumaWindow * window)
pluma_window_get_group: @window: a PlumaWindow
Gets the #GtkWindowGroup in which @window resides.
Returns: (transfer none): the #GtkWindowGroup
Definition at line 4585 of file pluma-window.c.
References NULL, PLUMA_IS_WINDOW, _PlumaWindow::priv, and _PlumaWindowPrivate::window_group.
Referenced by _pluma_cmd_file_revert(), and pluma_close_confirmation_dialog_new().
pluma_window_get_message_bus()
PlumaMessageBus * pluma_window_get_message_bus (PlumaWindow * window)
pluma_window_get_message_bus: @window: a PlumaWindow
Gets the PlumaMessageBus associated with @window. The returned reference is owned by the window and should not be unreffed.
Return value: (transfer none): the PlumaMessageBus associated with @window
Definition at line 4937 of file pluma-window.c.
References _PlumaWindowPrivate::message_bus, NULL, PLUMA_IS_WINDOW, and _PlumaWindow::priv.
Referenced by pluma_file_browser_messages_register(), and pluma_file_browser_messages_unregister().
pluma_window_get_right_panel()
PlumaPanel * pluma_window_get_right_panel (PlumaWindow * window)
pluma_window_get_right_panel: @window: a PlumaWindow
Gets the right PlumaPanel of the @window.
Returns: (transfer none): the right PlumaPanel.
Definition at line 4657 of file pluma-window.c.
References NULL, PLUMA_IS_WINDOW, PLUMA_PANEL, _PlumaWindow::priv, and _PlumaWindowPrivate::right_panel.
Referenced by _pluma_cmd_view_show_right_pane().
pluma_window_get_side_panel()
PlumaPanel * pluma_window_get_side_panel (PlumaWindow * window)
pluma_window_get_side_panel: @window: a PlumaWindow
Gets the side PlumaPanel of the @window.
Returns: (transfer none): the side PlumaPanel.
Definition at line 4625 of file pluma-window.c.
References NULL, PLUMA_IS_WINDOW, PLUMA_PANEL, _PlumaWindow::priv, and _PlumaWindowPrivate::side_panel.
Referenced by _pluma_cmd_view_show_side_pane().
pluma_window_get_state()
PlumaWindowState pluma_window_get_state (PlumaWindow * window)
pluma_window_get_state: @window: a PlumaWindow
Retrieves the state of the @window.
Returns: the current PlumaWindowState of the @window.
Definition at line 4689 of file pluma-window.c.
References PLUMA_IS_WINDOW, PLUMA_WINDOW_STATE_NORMAL, _PlumaWindow::priv, and _PlumaWindowPrivate::state.
Referenced by _pluma_cmd_file_close_all(), _pluma_cmd_file_quit(), and _pluma_cmd_file_save_documents_list().
pluma_window_get_statusbar()
GtkWidget * pluma_window_get_statusbar (PlumaWindow * window)
pluma_window_get_statusbar: @window: a PlumaWindow
Gets the PlumaStatusbar of the @window.
Returns: (transfer none): the PlumaStatusbar of the @window.
Definition at line 4673 of file pluma-window.c.
References PLUMA_IS_WINDOW, _PlumaWindow::priv, and _PlumaWindowPrivate::statusbar.
pluma_window_get_tab_from_location()
PlumaTab * pluma_window_get_tab_from_location (PlumaWindow * window, GFile * location)
pluma_window_get_tab_from_location: @window: a PlumaWindow @location: a #GFile
Gets the PlumaTab that matches with the given @location.
Returns: (transfer none): the PlumaTab that matches with the given @location.
Definition at line 4885 of file pluma-window.c.
References _PlumaWindowPrivate::notebook, NULL, pluma_document_get_location(), PLUMA_IS_WINDOW, PLUMA_TAB, pluma_tab_get_document(), and _PlumaWindow::priv.
pluma_window_get_type()
GType pluma_window_get_type (void)
pluma_window_get_ui_manager()
GtkUIManager * pluma_window_get_ui_manager (PlumaWindow * window)
pluma_window_get_ui_manager: @window: a PlumaWindow
Gets the #GtkUIManager associated with the @window.
Returns: (transfer none): the #GtkUIManager of the @window.
Definition at line 4609 of file pluma-window.c.
References _PlumaWindowPrivate::manager, NULL, PLUMA_IS_WINDOW, and _PlumaWindow::priv.
pluma_window_get_unsaved_documents()
GList * pluma_window_get_unsaved_documents (PlumaWindow * window)
pluma_window_get_unsaved_documents: @window: a PlumaWindow
Gets the list of documents that need to be saved before closing the window.
Returns: (element-type Pluma.Document) (transfer container): a list of PlumaDocument that need to be saved before closing the window
Definition at line 4733 of file pluma-window.c.
References _pluma_tab_can_close(), _PlumaWindowPrivate::notebook, NULL, PLUMA_IS_WINDOW, PLUMA_TAB, pluma_tab_get_document(), and _PlumaWindow::priv.
pluma_window_get_views()
GList * pluma_window_get_views (PlumaWindow * window)
pluma_window_get_views: @window: a PlumaWindow
Gets a list with all the views in the window. This list must be freed.
Returns: (element-type Pluma.View) (transfer container): a newly allocated list with all the views in the window
Definition at line 4441 of file pluma-window.c.
References _PlumaWindowPrivate::notebook, NULL, PLUMA_IS_WINDOW, and _PlumaWindow::priv.
Referenced by pluma_app_get_views().
pluma_window_set_active_tab()
void pluma_window_set_active_tab (PlumaWindow * window, PlumaTab * tab)
pluma_window_set_active_tab: @window: a PlumaWindow @tab: a PlumaTab
Switches to the tab that matches with @tab.
Definition at line 4560 of file pluma-window.c.
References _PlumaWindowPrivate::notebook, PLUMA_IS_TAB, PLUMA_IS_WINDOW, and _PlumaWindow::priv.
Referenced by _pluma_cmd_file_save_documents_list().