MATE Desktop Environment: pluma-encodings-combo-box.h File Reference
pluma-encodings-combo-box.h File Reference
#include <gtk/gtk.h>
#include <pluma/pluma-encodings.h>
Classes
struct _PlumaEncodingsComboBox
struct _PlumaEncodingsComboBoxClass
Macros
#define PLUMA_TYPE_ENCODINGS_COMBO_BOX (pluma_encodings_combo_box_get_type ())
#define PLUMA_ENCODINGS_COMBO_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_ENCODINGS_COMBO_BOX, PlumaEncodingsComboBox))
#define PLUMA_ENCODINGS_COMBO_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLUMA_TYPE_ENCODINGS_COMBO_BOX, PlumaEncodingsComboBoxClass))
#define PLUMA_IS_ENCODINGS_COMBO_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLUMA_TYPE_ENCODINGS_COMBO_BOX))
#define PLUMA_IS_ENCODINGS_COMBO_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_ENCODINGS_COMBO_BOX))
#define PLUMA_ENCODINGS_COMBO_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLUMA_TYPE_ENCODINGS_COMBO_BOX, PlumaEncodingsComboBoxClass))
Typedefs
typedef struct _PlumaEncodingsComboBox PlumaEncodingsComboBox
typedef struct _PlumaEncodingsComboBoxClass PlumaEncodingsComboBoxClass
typedef struct _PlumaEncodingsComboBoxPrivate PlumaEncodingsComboBoxPrivate
Functions
GType pluma_encodings_combo_box_get_type (void)
GtkWidget * pluma_encodings_combo_box_new (gboolean save_mode)
const PlumaEncoding * pluma_encodings_combo_box_get_selected_encoding (PlumaEncodingsComboBox *menu)
void pluma_encodings_combo_box_set_selected_encoding (PlumaEncodingsComboBox *menu, const PlumaEncoding *encoding)
Macro Definition Documentation
PLUMA_ENCODINGS_COMBO_BOX
#define PLUMA_ENCODINGS_COMBO_BOX (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_ENCODINGS_COMBO_BOX, PlumaEncodingsComboBox))
Definition at line 42 of file pluma-encodings-combo-box.h.
PLUMA_ENCODINGS_COMBO_BOX_CLASS
#define PLUMA_ENCODINGS_COMBO_BOX_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLUMA_TYPE_ENCODINGS_COMBO_BOX, PlumaEncodingsComboBoxClass))
Definition at line 43 of file pluma-encodings-combo-box.h.
PLUMA_ENCODINGS_COMBO_BOX_GET_CLASS
#define PLUMA_ENCODINGS_COMBO_BOX_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLUMA_TYPE_ENCODINGS_COMBO_BOX, PlumaEncodingsComboBoxClass))
Definition at line 46 of file pluma-encodings-combo-box.h.
PLUMA_IS_ENCODINGS_COMBO_BOX
#define PLUMA_IS_ENCODINGS_COMBO_BOX (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLUMA_TYPE_ENCODINGS_COMBO_BOX))
Definition at line 44 of file pluma-encodings-combo-box.h.
PLUMA_IS_ENCODINGS_COMBO_BOX_CLASS
#define PLUMA_IS_ENCODINGS_COMBO_BOX_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_ENCODINGS_COMBO_BOX))
Definition at line 45 of file pluma-encodings-combo-box.h.
PLUMA_TYPE_ENCODINGS_COMBO_BOX
#define PLUMA_TYPE_ENCODINGS_COMBO_BOX (pluma_encodings_combo_box_get_type ())
Definition at line 41 of file pluma-encodings-combo-box.h.
Typedef Documentation
PlumaEncodingsComboBox
typedef struct _PlumaEncodingsComboBox PlumaEncodingsComboBox
Definition at line 49 of file pluma-encodings-combo-box.h.
PlumaEncodingsComboBoxClass
typedef struct _PlumaEncodingsComboBoxClass PlumaEncodingsComboBoxClass
Definition at line 50 of file pluma-encodings-combo-box.h.
PlumaEncodingsComboBoxPrivate
typedef struct _PlumaEncodingsComboBoxPrivate PlumaEncodingsComboBoxPrivate
Definition at line 52 of file pluma-encodings-combo-box.h.
Function Documentation
pluma_encodings_combo_box_get_selected_encoding()
const PlumaEncoding * pluma_encodings_combo_box_get_selected_encoding (PlumaEncodingsComboBox * menu)
Definition at line 422 of file pluma-encodings-combo-box.c.
References ENCODING_COLUMN, NULL, and PLUMA_IS_ENCODINGS_COMBO_BOX.
Referenced by pluma_conversion_error_message_area_get_encoding(), and pluma_file_chooser_dialog_get_encoding().
pluma_encodings_combo_box_get_type()
GType pluma_encodings_combo_box_get_type (void)
pluma_encodings_combo_box_new()
GtkWidget * pluma_encodings_combo_box_new (gboolean save_mode)
Definition at line 414 of file pluma-encodings-combo-box.c.
References NULL, and PLUMA_TYPE_ENCODINGS_COMBO_BOX.
pluma_encodings_combo_box_set_selected_encoding()
void pluma_encodings_combo_box_set_selected_encoding (PlumaEncodingsComboBox * menu, const PlumaEncoding * encoding)
pluma_encodings_combo_box_set_selected_encoding: @menu: @encoding: (allow-none):
Definition at line 451 of file pluma-encodings-combo-box.c.
References b, ENCODING_COLUMN, and PLUMA_IS_ENCODINGS_COMBO_BOX.
Referenced by pluma_file_chooser_dialog_set_encoding().