MATE Desktop Environment: pluma-spell-checker-dialog.h File Reference
pluma-spell-checker-dialog.h File Reference
#include <gtk/gtk.h>
#include "pluma-spell-checker.h"
Classes
struct _PlumaSpellCheckerDialogClass
Macros
#define PLUMA_TYPE_SPELL_CHECKER_DIALOG (pluma_spell_checker_dialog_get_type ())
#define PLUMA_SPELL_CHECKER_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_SPELL_CHECKER_DIALOG, PlumaSpellCheckerDialog))
#define PLUMA_SPELL_CHECKER_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLUMA_TYPE_SPELL_CHECKER_DIALOG, PlumaSpellCheckerDialog))
#define PLUMA_IS_SPELL_CHECKER_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLUMA_TYPE_SPELL_CHECKER_DIALOG))
#define PLUMA_IS_SPELL_CHECKER_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_SPELL_CHECKER_DIALOG))
#define PLUMA_SPELL_CHECKER_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLUMA_TYPE_SPELL_CHECKER_DIALOG, PlumaSpellCheckerDialog))
Typedefs
typedef struct _PlumaSpellCheckerDialog PlumaSpellCheckerDialog
typedef struct _PlumaSpellCheckerDialogClass PlumaSpellCheckerDialogClass
Functions
GType pluma_spell_checker_dialog_get_type (void)
GtkWidget * pluma_spell_checker_dialog_new (const gchar *data_dir)
GtkWidget * pluma_spell_checker_dialog_new_from_spell_checker (PlumaSpellChecker *spell, const gchar *data_dir)
void pluma_spell_checker_dialog_set_spell_checker (PlumaSpellCheckerDialog *dlg, PlumaSpellChecker *spell)
void pluma_spell_checker_dialog_set_misspelled_word (PlumaSpellCheckerDialog *dlg, const gchar *word, gint len)
void pluma_spell_checker_dialog_set_completed (PlumaSpellCheckerDialog *dlg)
Macro Definition Documentation
PLUMA_IS_SPELL_CHECKER_DIALOG
#define PLUMA_IS_SPELL_CHECKER_DIALOG (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLUMA_TYPE_SPELL_CHECKER_DIALOG))
Definition at line 42 of file pluma-spell-checker-dialog.h.
PLUMA_IS_SPELL_CHECKER_DIALOG_CLASS
#define PLUMA_IS_SPELL_CHECKER_DIALOG_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_SPELL_CHECKER_DIALOG))
Definition at line 43 of file pluma-spell-checker-dialog.h.
PLUMA_SPELL_CHECKER_DIALOG
#define PLUMA_SPELL_CHECKER_DIALOG (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_SPELL_CHECKER_DIALOG, PlumaSpellCheckerDialog))
Definition at line 40 of file pluma-spell-checker-dialog.h.
PLUMA_SPELL_CHECKER_DIALOG_CLASS
#define PLUMA_SPELL_CHECKER_DIALOG_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLUMA_TYPE_SPELL_CHECKER_DIALOG, PlumaSpellCheckerDialog))
Definition at line 41 of file pluma-spell-checker-dialog.h.
PLUMA_SPELL_CHECKER_DIALOG_GET_CLASS
#define PLUMA_SPELL_CHECKER_DIALOG_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLUMA_TYPE_SPELL_CHECKER_DIALOG, PlumaSpellCheckerDialog))
Definition at line 44 of file pluma-spell-checker-dialog.h.
PLUMA_TYPE_SPELL_CHECKER_DIALOG
#define PLUMA_TYPE_SPELL_CHECKER_DIALOG (pluma_spell_checker_dialog_get_type ())
Definition at line 39 of file pluma-spell-checker-dialog.h.
Typedef Documentation
PlumaSpellCheckerDialog
typedef struct _PlumaSpellCheckerDialog PlumaSpellCheckerDialog
Definition at line 47 of file pluma-spell-checker-dialog.h.
PlumaSpellCheckerDialogClass
typedef struct _PlumaSpellCheckerDialogClass PlumaSpellCheckerDialogClass
Definition at line 49 of file pluma-spell-checker-dialog.h.
Function Documentation
pluma_spell_checker_dialog_get_type()
GType pluma_spell_checker_dialog_get_type (void)
pluma_spell_checker_dialog_new()
GtkWidget * pluma_spell_checker_dialog_new (const gchar * data_dir)
Definition at line 327 of file pluma-spell-checker-dialog.c.
References NULL, PLUMA_SPELL_CHECKER_DIALOG, and PLUMA_TYPE_SPELL_CHECKER_DIALOG.
pluma_spell_checker_dialog_new_from_spell_checker()
GtkWidget * pluma_spell_checker_dialog_new_from_spell_checker (PlumaSpellChecker * spell, const gchar * data_dir)
Definition at line 342 of file pluma-spell-checker-dialog.c.
References NULL, PLUMA_SPELL_CHECKER_DIALOG, pluma_spell_checker_dialog_set_spell_checker(), and PLUMA_TYPE_SPELL_CHECKER_DIALOG.
pluma_spell_checker_dialog_set_completed()
void pluma_spell_checker_dialog_set_completed (PlumaSpellCheckerDialog * dlg)
Definition at line 699 of file pluma-spell-checker-dialog.c.
References _, FALSE, and PLUMA_IS_SPELL_CHECKER_DIALOG.
pluma_spell_checker_dialog_set_misspelled_word()
void pluma_spell_checker_dialog_set_misspelled_word (PlumaSpellCheckerDialog * dlg, const gchar * word, gint len)
Definition at line 394 of file pluma-spell-checker-dialog.c.
References NULL, PLUMA_IS_SPELL_CHECKER_DIALOG, pluma_spell_checker_check_word(), pluma_spell_checker_get_suggestions(), and TRUE.
Referenced by pluma_spell_checker_dialog_set_spell_checker().
pluma_spell_checker_dialog_set_spell_checker()
void pluma_spell_checker_dialog_set_spell_checker (PlumaSpellCheckerDialog * dlg, PlumaSpellChecker * spell)
Definition at line 362 of file pluma-spell-checker-dialog.c.
References NULL, PLUMA_IS_SPELL_CHECKER_DIALOG, pluma_spell_checker_dialog_set_misspelled_word(), pluma_spell_checker_get_language(), and pluma_spell_checker_language_to_string().
Referenced by pluma_spell_checker_dialog_new_from_spell_checker().