MATE Desktop Environment: pluma-close-confirmation-dialog.c File Reference
pluma-close-confirmation-dialog.c File Reference
#include <glib/gi18n.h>
#include "pluma-close-confirmation-dialog.h"
#include <pluma/pluma-app.h>
#include <pluma/pluma-utils.h>
#include <pluma/pluma-window.h>
Macros
#define GET_MODE(priv)
Enumerations
enum { PROP_0 , PROP_UNSAVED_DOCUMENTS , PROP_LOGOUT_MODE }
enum { SINGLE_DOC_MODE , MULTIPLE_DOCS_MODE }
enum { SAVE_COLUMN , NAME_COLUMN , DOC_COLUMN , N_COLUMNS }
Functions
GList * pluma_close_confirmation_dialog_get_selected_documents (PlumaCloseConfirmationDialog *dlg)
GtkWidget * pluma_close_confirmation_dialog_new (GtkWindow *parent, GList *unsaved_documents, gboolean logout_mode)
GtkWidget * pluma_close_confirmation_dialog_new_single (GtkWindow *parent, PlumaDocument *doc, gboolean logout_mode)
const GList * pluma_close_confirmation_dialog_get_unsaved_documents (PlumaCloseConfirmationDialog *dlg)
Macro Definition Documentation
GET_MODE
#define GET_MODE (priv)
Value:
             (((priv->unsaved_documents != NULL) && \
             (priv->unsaved_documents->next == NULL)) ? \
              SINGLE_DOC_MODE : MULTIPLE_DOCS_MODE)
Definition at line 81 of file pluma-close-confirmation-dialog.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_UNSAVED_DOCUMENTS
PROP_LOGOUT_MODE
Definition at line 45 of file pluma-close-confirmation-dialog.c.
anonymous enum
anonymous enum
Enumerator
SINGLE_DOC_MODE
MULTIPLE_DOCS_MODE
Definition at line 53 of file pluma-close-confirmation-dialog.c.
anonymous enum
anonymous enum
Enumerator
SAVE_COLUMN
NAME_COLUMN
DOC_COLUMN
N_COLUMNS
Definition at line 60 of file pluma-close-confirmation-dialog.c.
Function Documentation
pluma_close_confirmation_dialog_get_selected_documents()
GList * pluma_close_confirmation_dialog_get_selected_documents (PlumaCloseConfirmationDialog * dlg)
Definition at line 352 of file pluma-close-confirmation-dialog.c.
References NULL, PLUMA_IS_CLOSE_CONFIRMATION_DIALOG, and _PlumaCloseConfirmationDialog::priv.
pluma_close_confirmation_dialog_get_unsaved_documents()
const GList * pluma_close_confirmation_dialog_get_unsaved_documents (PlumaCloseConfirmationDialog * dlg)
Definition at line 823 of file pluma-close-confirmation-dialog.c.
References NULL, PLUMA_IS_CLOSE_CONFIRMATION_DIALOG, and _PlumaCloseConfirmationDialog::priv.
pluma_close_confirmation_dialog_new()
GtkWidget * pluma_close_confirmation_dialog_new (GtkWindow * parent, GList * unsaved_documents, gboolean logout_mode)
Definition at line 360 of file pluma-close-confirmation-dialog.c.
References NULL, PLUMA_TYPE_CLOSE_CONFIRMATION_DIALOG, PLUMA_WINDOW, and pluma_window_get_group().
Referenced by pluma_close_confirmation_dialog_new_single().
pluma_close_confirmation_dialog_new_single()
GtkWidget * pluma_close_confirmation_dialog_new_single (GtkWindow * parent, PlumaDocument * doc, gboolean logout_mode)
Definition at line 385 of file pluma-close-confirmation-dialog.c.
References NULL, and pluma_close_confirmation_dialog_new().