MATE Desktop Environment: pluma-search-dialog.c File Reference
pluma-search-dialog.c File Reference
#include <string.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include "pluma-search-dialog.h"
#include "pluma-history-entry.h"
#include "pluma-utils.h"
#include "pluma-dirs.h"
Enumerations
enum { SHOW_REPLACE , LAST_SIGNAL }
enum { PROP_0 , PROP_SHOW_REPLACE }
Functions
void pluma_search_dialog_present_with_time (PlumaSearchDialog *dialog, guint32 timestamp)
GtkWidget * pluma_search_dialog_new (GtkWindow *parent, gboolean show_replace)
gboolean pluma_search_dialog_get_show_replace (PlumaSearchDialog *dialog)
void pluma_search_dialog_set_show_replace (PlumaSearchDialog *dialog, gboolean show_replace)
void pluma_search_dialog_set_search_text (PlumaSearchDialog *dialog, const gchar *text)
const gchar * pluma_search_dialog_get_search_text (PlumaSearchDialog *dialog)
void pluma_search_dialog_set_replace_text (PlumaSearchDialog *dialog, const gchar *text)
const gchar * pluma_search_dialog_get_replace_text (PlumaSearchDialog *dialog)
void pluma_search_dialog_set_match_case (PlumaSearchDialog *dialog, gboolean match_case)
gboolean pluma_search_dialog_get_match_case (PlumaSearchDialog *dialog)
void pluma_search_dialog_set_match_regex (PlumaSearchDialog *dialog, gboolean match_case)
gboolean pluma_search_dialog_get_match_regex (PlumaSearchDialog *dialog)
void pluma_search_dialog_set_entire_word (PlumaSearchDialog *dialog, gboolean entire_word)
gboolean pluma_search_dialog_get_entire_word (PlumaSearchDialog *dialog)
void pluma_search_dialog_set_backwards (PlumaSearchDialog *dialog, gboolean backwards)
gboolean pluma_search_dialog_get_backwards (PlumaSearchDialog *dialog)
void pluma_search_dialog_set_wrap_around (PlumaSearchDialog *dialog, gboolean wrap_around)
gboolean pluma_search_dialog_get_wrap_around (PlumaSearchDialog *dialog)
void pluma_search_dialog_set_parse_escapes (PlumaSearchDialog *dialog, gboolean parse_escapes)
gboolean pluma_search_dialog_get_parse_escapes (PlumaSearchDialog *dialog)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SHOW_REPLACE
LAST_SIGNAL
Definition at line 47 of file pluma-search-dialog.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_SHOW_REPLACE
Definition at line 81 of file pluma-search-dialog.c.
Function Documentation
pluma_search_dialog_get_backwards()
gboolean pluma_search_dialog_get_backwards (PlumaSearchDialog * dialog)
Definition at line 619 of file pluma-search-dialog.c.
References FALSE, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_get_entire_word()
gboolean pluma_search_dialog_get_entire_word (PlumaSearchDialog * dialog)
Definition at line 601 of file pluma-search-dialog.c.
References FALSE, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_get_match_case()
gboolean pluma_search_dialog_get_match_case (PlumaSearchDialog * dialog)
Definition at line 565 of file pluma-search-dialog.c.
References FALSE, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_get_match_regex()
gboolean pluma_search_dialog_get_match_regex (PlumaSearchDialog * dialog)
Definition at line 583 of file pluma-search-dialog.c.
References FALSE, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_get_parse_escapes()
gboolean pluma_search_dialog_get_parse_escapes (PlumaSearchDialog * dialog)
Definition at line 655 of file pluma-search-dialog.c.
References FALSE, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
Referenced by _pluma_cmd_search_find(), and _pluma_cmd_search_replace().
pluma_search_dialog_get_replace_text()
const gchar * pluma_search_dialog_get_replace_text (PlumaSearchDialog * dialog)
Definition at line 547 of file pluma-search-dialog.c.
References NULL, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_get_search_text()
const gchar * pluma_search_dialog_get_search_text (PlumaSearchDialog * dialog)
Definition at line 528 of file pluma-search-dialog.c.
References NULL, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
Referenced by _pluma_cmd_search_find(), and _pluma_cmd_search_replace().
pluma_search_dialog_get_show_replace()
gboolean pluma_search_dialog_get_show_replace (PlumaSearchDialog * dialog)
Definition at line 483 of file pluma-search-dialog.c.
References FALSE, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
Referenced by _pluma_cmd_search_find(), and _pluma_cmd_search_replace().
pluma_search_dialog_get_wrap_around()
gboolean pluma_search_dialog_get_wrap_around (PlumaSearchDialog * dialog)
Definition at line 637 of file pluma-search-dialog.c.
References FALSE, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_new()
GtkWidget * pluma_search_dialog_new (GtkWindow * parent, gboolean show_replace)
Definition at line 461 of file pluma-search-dialog.c.
References NULL, PLUMA_TYPE_SEARCH_DIALOG, and TRUE.
pluma_search_dialog_present_with_time()
void pluma_search_dialog_present_with_time (PlumaSearchDialog * dialog, guint32 timestamp)
Definition at line 127 of file pluma-search-dialog.c.
References PLUMA_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
Referenced by _pluma_cmd_search_find(), and _pluma_cmd_search_replace().
pluma_search_dialog_set_backwards()
void pluma_search_dialog_set_backwards (PlumaSearchDialog * dialog, gboolean backwards)
Definition at line 609 of file pluma-search-dialog.c.
References PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_set_entire_word()
void pluma_search_dialog_set_entire_word (PlumaSearchDialog * dialog, gboolean entire_word)
Definition at line 591 of file pluma-search-dialog.c.
References PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_set_match_case()
void pluma_search_dialog_set_match_case (PlumaSearchDialog * dialog, gboolean match_case)
Definition at line 555 of file pluma-search-dialog.c.
References PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_set_match_regex()
void pluma_search_dialog_set_match_regex (PlumaSearchDialog * dialog, gboolean match_case)
Definition at line 573 of file pluma-search-dialog.c.
References PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_set_parse_escapes()
void pluma_search_dialog_set_parse_escapes (PlumaSearchDialog * dialog, gboolean parse_escapes)
Definition at line 645 of file pluma-search-dialog.c.
References PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_set_replace_text()
void pluma_search_dialog_set_replace_text (PlumaSearchDialog * dialog, const gchar * text)
Definition at line 536 of file pluma-search-dialog.c.
References NULL, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
pluma_search_dialog_set_search_text()
void pluma_search_dialog_set_search_text (PlumaSearchDialog * dialog, const gchar * text)
Definition at line 506 of file pluma-search-dialog.c.
References NULL, PLUMA_IS_SEARCH_DIALOG, PLUMA_SEARCH_DIALOG_FIND_RESPONSE, PLUMA_SEARCH_DIALOG_REPLACE_ALL_RESPONSE, and _PlumaSearchDialog::priv.
Referenced by _pluma_cmd_search_find(), and _pluma_cmd_search_replace().
pluma_search_dialog_set_show_replace()
void pluma_search_dialog_set_show_replace (PlumaSearchDialog * dialog, gboolean show_replace)
Definition at line 491 of file pluma-search-dialog.c.
References FALSE, PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.
Referenced by _pluma_cmd_search_find(), and _pluma_cmd_search_replace().
pluma_search_dialog_set_wrap_around()
void pluma_search_dialog_set_wrap_around (PlumaSearchDialog * dialog, gboolean wrap_around)
Definition at line 627 of file pluma-search-dialog.c.
References PLUMA_IS_SEARCH_DIALOG, and _PlumaSearchDialog::priv.