MATE Desktop Environment: pluma-progress-message-area.h File Reference
pluma-progress-message-area.h File Reference
#include <gtk/gtk.h>
Classes
struct _PlumaProgressMessageArea
struct _PlumaProgressMessageAreaClass
Macros
#define PLUMA_TYPE_PROGRESS_MESSAGE_AREA (pluma_progress_message_area_get_type())
#define PLUMA_PROGRESS_MESSAGE_AREA(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_PROGRESS_MESSAGE_AREA, PlumaProgressMessageArea))
#define PLUMA_PROGRESS_MESSAGE_AREA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), PLUMA_TYPE_PROGRESS_MESSAGE_AREA, PlumaProgressMessageAreaClass))
#define PLUMA_IS_PROGRESS_MESSAGE_AREA(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), PLUMA_TYPE_PROGRESS_MESSAGE_AREA))
#define PLUMA_IS_PROGRESS_MESSAGE_AREA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_PROGRESS_MESSAGE_AREA))
#define PLUMA_PROGRESS_MESSAGE_AREA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS((obj), PLUMA_TYPE_PROGRESS_MESSAGE_AREA, PlumaProgressMessageAreaClass))
Typedefs
typedef struct _PlumaProgressMessageAreaPrivate PlumaProgressMessageAreaPrivate
typedef struct _PlumaProgressMessageArea PlumaProgressMessageArea
typedef struct _PlumaProgressMessageAreaClass PlumaProgressMessageAreaClass
Functions
GType pluma_progress_message_area_get_type (void)
GtkWidget * pluma_progress_message_area_new (const gchar *image_id, const gchar *markup, gboolean has_cancel)
void pluma_progress_message_area_set_image (PlumaProgressMessageArea *area, const gchar *image_id)
void pluma_progress_message_area_set_markup (PlumaProgressMessageArea *area, const gchar *markup)
void pluma_progress_message_area_set_text (PlumaProgressMessageArea *area, const gchar *text)
void pluma_progress_message_area_set_fraction (PlumaProgressMessageArea *area, gdouble fraction)
void pluma_progress_message_area_pulse (PlumaProgressMessageArea *area)
Macro Definition Documentation
PLUMA_IS_PROGRESS_MESSAGE_AREA
#define PLUMA_IS_PROGRESS_MESSAGE_AREA (obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), PLUMA_TYPE_PROGRESS_MESSAGE_AREA))
Definition at line 45 of file pluma-progress-message-area.h.
PLUMA_IS_PROGRESS_MESSAGE_AREA_CLASS
#define PLUMA_IS_PROGRESS_MESSAGE_AREA_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_PROGRESS_MESSAGE_AREA))
Definition at line 46 of file pluma-progress-message-area.h.
PLUMA_PROGRESS_MESSAGE_AREA
#define PLUMA_PROGRESS_MESSAGE_AREA (obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_PROGRESS_MESSAGE_AREA, PlumaProgressMessageArea))
Definition at line 43 of file pluma-progress-message-area.h.
PLUMA_PROGRESS_MESSAGE_AREA_CLASS
#define PLUMA_PROGRESS_MESSAGE_AREA_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST((klass), PLUMA_TYPE_PROGRESS_MESSAGE_AREA, PlumaProgressMessageAreaClass))
Definition at line 44 of file pluma-progress-message-area.h.
PLUMA_PROGRESS_MESSAGE_AREA_GET_CLASS
#define PLUMA_PROGRESS_MESSAGE_AREA_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS((obj), PLUMA_TYPE_PROGRESS_MESSAGE_AREA, PlumaProgressMessageAreaClass))
Definition at line 47 of file pluma-progress-message-area.h.
PLUMA_TYPE_PROGRESS_MESSAGE_AREA
#define PLUMA_TYPE_PROGRESS_MESSAGE_AREA (pluma_progress_message_area_get_type())
Definition at line 42 of file pluma-progress-message-area.h.
Typedef Documentation
PlumaProgressMessageArea
typedef struct _PlumaProgressMessageArea PlumaProgressMessageArea
Definition at line 55 of file pluma-progress-message-area.h.
PlumaProgressMessageAreaClass
typedef struct _PlumaProgressMessageAreaClass PlumaProgressMessageAreaClass
Definition at line 68 of file pluma-progress-message-area.h.
PlumaProgressMessageAreaPrivate
typedef struct _PlumaProgressMessageAreaPrivate PlumaProgressMessageAreaPrivate
Definition at line 50 of file pluma-progress-message-area.h.
Function Documentation
pluma_progress_message_area_get_type()
GType pluma_progress_message_area_get_type (void)
pluma_progress_message_area_new()
GtkWidget * pluma_progress_message_area_new (const gchar * image_id, const gchar * markup, gboolean has_cancel)
Definition at line 168 of file pluma-progress-message-area.c.
References NULL, PLUMA_PROGRESS_MESSAGE_AREA, pluma_progress_message_area_set_image(), pluma_progress_message_area_set_markup(), and PLUMA_TYPE_PROGRESS_MESSAGE_AREA.
pluma_progress_message_area_pulse()
void pluma_progress_message_area_pulse (PlumaProgressMessageArea * area)
Definition at line 235 of file pluma-progress-message-area.c.
References PLUMA_IS_PROGRESS_MESSAGE_AREA, and _PlumaProgressMessageArea::priv.
pluma_progress_message_area_set_fraction()
void pluma_progress_message_area_set_fraction (PlumaProgressMessageArea * area, gdouble fraction)
Definition at line 225 of file pluma-progress-message-area.c.
References PLUMA_IS_PROGRESS_MESSAGE_AREA, and _PlumaProgressMessageArea::priv.
pluma_progress_message_area_set_image()
void pluma_progress_message_area_set_image (PlumaProgressMessageArea * area, const gchar * image_id)
Definition at line 191 of file pluma-progress-message-area.c.
References NULL, PLUMA_IS_PROGRESS_MESSAGE_AREA, and _PlumaProgressMessageArea::priv.
Referenced by pluma_progress_message_area_new().
pluma_progress_message_area_set_markup()
void pluma_progress_message_area_set_markup (PlumaProgressMessageArea * area, const gchar * markup)
Definition at line 203 of file pluma-progress-message-area.c.
References NULL, PLUMA_IS_PROGRESS_MESSAGE_AREA, and _PlumaProgressMessageArea::priv.
Referenced by pluma_progress_message_area_new().
pluma_progress_message_area_set_text()
void pluma_progress_message_area_set_text (PlumaProgressMessageArea * area, const gchar * text)
Definition at line 214 of file pluma-progress-message-area.c.
References NULL, PLUMA_IS_PROGRESS_MESSAGE_AREA, and _PlumaProgressMessageArea::priv.