MATE Desktop Environment: pluma-notebook.c File Reference
pluma-notebook.c File Reference
#include <glib-object.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include "pluma-notebook.h"
#include "pluma-tab.h"
#include "pluma-tab-label.h"
#include "pluma-window.h"
#include "pluma-settings.h"
Macros
#define AFTER_ALL_TABS -1
#define NOT_IN_APP_WINDOWS -2
Enumerations
enum {
TAB_ADDED , TAB_REMOVED , TABS_REORDERED , TAB_DETACHED ,
TAB_CLOSE_REQUEST , LAST_SIGNAL
}
Functions
void pluma_notebook_move_tab (PlumaNotebook *src, PlumaNotebook *dest, PlumaTab *tab, gint dest_position)
void pluma_notebook_reorder_tab (PlumaNotebook *src, PlumaTab *tab, gint dest_position)
GtkWidget * pluma_notebook_new (void)
void pluma_notebook_add_tab (PlumaNotebook *nb, PlumaTab *tab, gint position, gboolean jump_to)
void pluma_notebook_remove_tab (PlumaNotebook *nb, PlumaTab *tab)
void pluma_notebook_remove_all_tabs (PlumaNotebook *nb)
void pluma_notebook_set_close_buttons_sensitive (PlumaNotebook *nb, gboolean sensitive)
gboolean pluma_notebook_get_close_buttons_sensitive (PlumaNotebook *nb)
void pluma_notebook_set_tab_drag_and_drop_enabled (PlumaNotebook *nb, gboolean enable)
gboolean pluma_notebook_get_tab_drag_and_drop_enabled (PlumaNotebook *nb)
Macro Definition Documentation
AFTER_ALL_TABS
#define AFTER_ALL_TABS -1
Definition at line 53 of file pluma-notebook.c.
NOT_IN_APP_WINDOWS
#define NOT_IN_APP_WINDOWS -2
Definition at line 54 of file pluma-notebook.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TAB_ADDED
TAB_REMOVED
TABS_REORDERED
TAB_DETACHED
TAB_CLOSE_REQUEST
LAST_SIGNAL
Definition at line 87 of file pluma-notebook.c.
Function Documentation
pluma_notebook_add_tab()
void pluma_notebook_add_tab (PlumaNotebook * nb, PlumaTab * tab, gint position, gboolean jump_to)
pluma_notebook_add_tab: @nb: a PlumaNotebook @tab: a PlumaTab @position: the position where the @tab should be added @jump_to: TRUE to set the @tab as active
Adds the specified @tab to the @nb.
Definition at line 961 of file pluma-notebook.c.
References PLUMA_IS_NOTEBOOK, PLUMA_IS_TAB, pluma_tab_get_view(), signals, and TAB_ADDED.
Referenced by pluma_notebook_move_tab(), pluma_window_create_tab(), and pluma_window_create_tab_from_uri().
pluma_notebook_get_close_buttons_sensitive()
gboolean pluma_notebook_get_close_buttons_sensitive (PlumaNotebook * nb)
pluma_notebook_get_close_buttons_sensitive: @nb: a PlumaNotebook
Whether the close buttons are sensitive.
Returns: TRUE if the close buttons are sensitive
Definition at line 1145 of file pluma-notebook.c.
References PLUMA_IS_NOTEBOOK, _PlumaNotebook::priv, and TRUE.
pluma_notebook_get_tab_drag_and_drop_enabled()
gboolean pluma_notebook_get_tab_drag_and_drop_enabled (PlumaNotebook * nb)
pluma_notebook_get_tab_drag_and_drop_enabled: @nb: a PlumaNotebook
Whether the drag and drop is enabled in the @nb.
Returns: TRUE if the drag and drop is enabled.
Definition at line 1182 of file pluma-notebook.c.
References PLUMA_IS_NOTEBOOK, _PlumaNotebook::priv, and TRUE.
pluma_notebook_move_tab()
void pluma_notebook_move_tab (PlumaNotebook * src, PlumaNotebook * dest, PlumaTab * tab, gint dest_position)
pluma_notebook_move_tab: @src: a PlumaNotebook @dest: a PlumaNotebook @tab: a PlumaTab @dest_position: the position for @tab
Moves @tab from @src to @dest. If dest_position is greater than or equal to the number of tabs of the destination nootebook or negative, tab will be moved to the end of the tabs.
Definition at line 343 of file pluma-notebook.c.
References dest, PLUMA_IS_NOTEBOOK, PLUMA_IS_TAB, pluma_notebook_add_tab(), pluma_notebook_remove_tab(), and TRUE.
Referenced by _pluma_window_move_tab_to_new_window().
pluma_notebook_new()
GtkWidget * pluma_notebook_new (void)
pluma_notebook_new:
Creates a new PlumaNotebook object.
Returns: a new PlumaNotebook
Definition at line 753 of file pluma-notebook.c.
References NULL, and PLUMA_TYPE_NOTEBOOK.
pluma_notebook_remove_all_tabs()
void pluma_notebook_remove_all_tabs (PlumaNotebook * nb)
pluma_notebook_remove_all_tabs: @nb: a PlumaNotebook
Removes all PlumaTab from @nb.
Definition at line 1087 of file pluma-notebook.c.
References NULL, PLUMA_IS_NOTEBOOK, and _PlumaNotebook::priv.
Referenced by pluma_window_close_all_tabs().
pluma_notebook_remove_tab()
void pluma_notebook_remove_tab (PlumaNotebook * nb, PlumaTab * tab)
pluma_notebook_remove_tab: @nb: a PlumaNotebook @tab: a PlumaTab
Removes @tab from @nb.
Definition at line 1057 of file pluma-notebook.c.
References PLUMA_IS_NOTEBOOK, PLUMA_IS_TAB, and _PlumaNotebook::priv.
Referenced by pluma_notebook_move_tab(), pluma_window_close_tab(), and pluma_window_close_tabs().
pluma_notebook_reorder_tab()
void pluma_notebook_reorder_tab (PlumaNotebook * src, PlumaTab * tab, gint dest_position)
pluma_notebook_reorder_tab: @src: a PlumaNotebook @tab: a PlumaTab @dest_position: the position for @tab
Reorders the page containing @tab, so that it appears in @dest_position position. If dest_position is greater than or equal to the number of tabs of the destination notebook or negative, tab will be moved to the end of the tabs.
Definition at line 372 of file pluma-notebook.c.
References PLUMA_IS_NOTEBOOK, PLUMA_IS_TAB, _PlumaNotebook::priv, signals, and TABS_REORDERED.
pluma_notebook_set_close_buttons_sensitive()
void pluma_notebook_set_close_buttons_sensitive (PlumaNotebook * nb, gboolean sensitive)
pluma_notebook_set_close_buttons_sensitive: @nb: a PlumaNotebook @sensitive: TRUE to make the buttons sensitive
Sets whether the close buttons in the tabs of @nb are sensitive.
Definition at line 1119 of file pluma-notebook.c.
References FALSE, PLUMA_IS_NOTEBOOK, and _PlumaNotebook::priv.
pluma_notebook_set_tab_drag_and_drop_enabled()
void pluma_notebook_set_tab_drag_and_drop_enabled (PlumaNotebook * nb, gboolean enable)
pluma_notebook_set_tab_drag_and_drop_enabled: @nb: a PlumaNotebook @enable: TRUE to enable the drag and drop
Sets whether drag and drop of tabs in the @nb is enabled.
Definition at line 1160 of file pluma-notebook.c.
References FALSE, PLUMA_IS_NOTEBOOK, and _PlumaNotebook::priv.