MATE Desktop Environment: pluma-settings.h File Reference
pluma-settings.h File Reference
#include <glib-object.h>
#include <glib.h>
#include "pluma-app.h"
Classes
struct _PlumaSettings
struct _PlumaSettingsClass
Macros
#define PLUMA_TYPE_SETTINGS (pluma_settings_get_type ())
#define PLUMA_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_SETTINGS, PlumaSettings))
#define PLUMA_SETTINGS_CONST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_SETTINGS, PlumaSettings const))
#define PLUMA_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLUMA_TYPE_SETTINGS, PlumaSettingsClass))
#define PLUMA_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLUMA_TYPE_SETTINGS))
#define PLUMA_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_SETTINGS))
#define PLUMA_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLUMA_TYPE_SETTINGS, PlumaSettingsClass))
#define PLUMA_SCHEMA_ID "org.mate.pluma"
#define PLUMA_SETTINGS_USE_DEFAULT_FONT "use-default-font"
#define PLUMA_SETTINGS_EDITOR_FONT "editor-font"
#define PLUMA_SETTINGS_COLOR_SCHEME "color-scheme"
#define PLUMA_SETTINGS_CREATE_BACKUP_COPY "create-backup-copy"
#define PLUMA_SETTINGS_AUTO_SAVE "auto-save"
#define PLUMA_SETTINGS_AUTO_SAVE_INTERVAL "auto-save-interval"
#define PLUMA_SETTINGS_MAX_UNDO_ACTIONS "max-undo-actions"
#define PLUMA_SETTINGS_WRAP_MODE "wrap-mode"
#define PLUMA_SETTINGS_TABS_SIZE "tabs-size"
#define PLUMA_SETTINGS_INSERT_SPACES "insert-spaces"
#define PLUMA_SETTINGS_AUTO_INDENT "auto-indent"
#define PLUMA_SETTINGS_DISPLAY_LINE_NUMBERS "display-line-numbers"
#define PLUMA_SETTINGS_HIGHLIGHT_CURRENT_LINE "highlight-current-line"
#define PLUMA_SETTINGS_BRACKET_MATCHING "bracket-matching"
#define PLUMA_SETTINGS_DISPLAY_RIGHT_MARGIN "display-right-margin"
#define PLUMA_SETTINGS_RIGHT_MARGIN_POSITION "right-margin-position"
#define PLUMA_SETTINGS_WRITABLE_VFS_SCHEMES "writable-vfs-schemes"
#define PLUMA_SETTINGS_RESTORE_CURSOR_POSITION "restore-cursor-position"
#define PLUMA_SETTINGS_SYNTAX_HIGHLIGHTING "syntax-highlighting"
#define PLUMA_SETTINGS_SEARCH_HIGHLIGHTING "search-highlighting"
#define PLUMA_SETTINGS_TOOLBAR_VISIBLE "toolbar-visible"
#define PLUMA_SETTINGS_STATUSBAR_VISIBLE "statusbar-visible"
#define PLUMA_SETTINGS_SIDE_PANE_VISIBLE "side-pane-visible"
#define PLUMA_SETTINGS_BOTTOM_PANE_VISIBLE "bottom-panel-visible"
#define PLUMA_SETTINGS_RIGHT_PANE_VISIBLE "right-panel-visible"
#define PLUMA_SETTINGS_MAX_RECENTS "max-recents"
#define PLUMA_SETTINGS_PRINT_SYNTAX_HIGHLIGHTING "print-syntax-highlighting"
#define PLUMA_SETTINGS_PRINT_HEADER "print-header"
#define PLUMA_SETTINGS_PRINT_WRAP_MODE "print-wrap-mode"
#define PLUMA_SETTINGS_PRINT_LINE_NUMBERS "print-line-numbers"
#define PLUMA_SETTINGS_PRINT_FONT_BODY_PANGO "print-font-body-pango"
#define PLUMA_SETTINGS_PRINT_FONT_HEADER_PANGO "print-font-header-pango"
#define PLUMA_SETTINGS_PRINT_FONT_NUMBERS_PANGO "print-font-numbers-pango"
#define PLUMA_SETTINGS_ENCODING_AUTO_DETECTED "auto-detected-encodings"
#define PLUMA_SETTINGS_ENCODING_SHOWN_IN_MENU "shown-in-menu-encodings"
#define PLUMA_SETTINGS_ACTIVE_PLUGINS "active-plugins"
#define PLUMA_SETTINGS_SHOW_SINGLE_TAB "show-single-tab"
#define PLUMA_SETTINGS_SHOW_TABS_WITH_SIDE_PANE "show-tabs-with-side-pane"
#define PLUMA_SETTINGS_CTRL_TABS_SWITCH_TABS "ctrl-tab-switch-tabs"
#define PLUMA_SETTINGS_SHOW_SAVE_CONFIRMATION "show-save-confirmation"
#define PLUMA_SETTINGS_DRAWER_SPACE "enable-space-drawer-space"
#define PLUMA_SETTINGS_DRAWER_TAB "enable-space-drawer-tab"
#define PLUMA_SETTINGS_DRAWER_NEWLINE "enable-space-drawer-newline"
#define PLUMA_SETTINGS_DRAWER_NBSP "enable-space-drawer-nbsp"
#define PLUMA_SETTINGS_DISPLAY_OVERVIEW_MAP "display-overview-map"
#define PLUMA_SETTINGS_BACKGROUND_PATTERN "background-pattern"
#define PLUMA_SETTINGS_WRITABLE_VFS_SCHEMES "writable-vfs-schemes"
#define PLUMA_SETTINGS_SMART_HOME_END "smart-home-end"
#define PLUMA_SETTINGS_WINDOW_STATE "state"
#define PLUMA_SETTINGS_WINDOW_SIZE "size"
#define PLUMA_SETTINGS_SIDE_PANEL_SIZE "side-panel-size"
#define PLUMA_SETTINGS_SIDE_PANEL_ACTIVE_PAGE "side-panel-active-page"
#define PLUMA_SETTINGS_BOTTOM_PANEL_SIZE "bottom-panel-size"
#define PLUMA_SETTINGS_BOTTOM_PANEL_ACTIVE_PAGE "bottom-panel-active-page"
#define PLUMA_SETTINGS_RIGHT_PANEL_SIZE "right-panel-size"
#define PLUMA_SETTINGS_RIGHT_PANEL_ACTIVE_PAGE "right-panel-active-page"
#define PLUMA_SETTINGS_ACTIVE_FILE_FILTER "filter-id"
Typedefs
typedef struct _PlumaSettings PlumaSettings
typedef struct _PlumaSettingsClass PlumaSettingsClass
typedef struct _PlumaSettingsPrivate PlumaSettingsPrivate
Enumerations
enum PlumaToolbarSetting { PLUMA_TOOLBAR_SYSTEM = 0 , PLUMA_TOOLBAR_ICONS , PLUMA_TOOLBAR_ICONS_AND_TEXT , PLUMA_TOOLBAR_ICONS_BOTH_HORIZ }
Functions
GType pluma_settings_get_type (void)
G_GNUC_INTERNAL PlumaSettings * _pluma_settings_get_singleton (void)
void pluma_settings_unref_singleton (void)
PlumaLockdownMask pluma_settings_get_lockdown (PlumaSettings *self)
gchar * pluma_settings_get_system_font (PlumaSettings *self)
GtkSourceSmartHomeEndType pluma_settings_get_smart_home_end (PlumaSettings *self)
PlumaToolbarSetting pluma_settings_get_toolbar_style (PlumaSettings *self)
GSList * pluma_settings_get_list (GSettings *settings, const gchar *key)
void pluma_settings_set_list (GSettings *settings, const gchar *key, GSList *list)
GtkWrapMode pluma_settings_get_wrap_mode (GSettings *settings, const gchar *key)
void pluma_settings_set_wrap_mode (GSettings *settings, const gchar *key, GtkWrapMode mode)
GSList * pluma_settings_get_writable_vfs_schemes (GSettings *settings)
Macro Definition Documentation
PLUMA_IS_SETTINGS
#define PLUMA_IS_SETTINGS (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLUMA_TYPE_SETTINGS))
Definition at line 38 of file pluma-settings.h.
PLUMA_IS_SETTINGS_CLASS
#define PLUMA_IS_SETTINGS_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_SETTINGS))
Definition at line 39 of file pluma-settings.h.
PLUMA_SCHEMA_ID
#define PLUMA_SCHEMA_ID "org.mate.pluma"
Definition at line 97 of file pluma-settings.h.
PLUMA_SETTINGS
#define PLUMA_SETTINGS (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_SETTINGS, PlumaSettings))
Definition at line 35 of file pluma-settings.h.
PLUMA_SETTINGS_ACTIVE_FILE_FILTER
#define PLUMA_SETTINGS_ACTIVE_FILE_FILTER "filter-id"
Definition at line 160 of file pluma-settings.h.
PLUMA_SETTINGS_ACTIVE_PLUGINS
#define PLUMA_SETTINGS_ACTIVE_PLUGINS "active-plugins"
Definition at line 135 of file pluma-settings.h.
PLUMA_SETTINGS_AUTO_INDENT
#define PLUMA_SETTINGS_AUTO_INDENT "auto-indent"
Definition at line 110 of file pluma-settings.h.
PLUMA_SETTINGS_AUTO_SAVE
#define PLUMA_SETTINGS_AUTO_SAVE "auto-save"
Definition at line 104 of file pluma-settings.h.
PLUMA_SETTINGS_AUTO_SAVE_INTERVAL
#define PLUMA_SETTINGS_AUTO_SAVE_INTERVAL "auto-save-interval"
Definition at line 105 of file pluma-settings.h.
PLUMA_SETTINGS_BACKGROUND_PATTERN
#define PLUMA_SETTINGS_BACKGROUND_PATTERN "background-pattern"
Definition at line 145 of file pluma-settings.h.
PLUMA_SETTINGS_BOTTOM_PANE_VISIBLE
#define PLUMA_SETTINGS_BOTTOM_PANE_VISIBLE "bottom-panel-visible"
Definition at line 123 of file pluma-settings.h.
PLUMA_SETTINGS_BOTTOM_PANEL_ACTIVE_PAGE
#define PLUMA_SETTINGS_BOTTOM_PANEL_ACTIVE_PAGE "bottom-panel-active-page"
Definition at line 157 of file pluma-settings.h.
PLUMA_SETTINGS_BOTTOM_PANEL_SIZE
#define PLUMA_SETTINGS_BOTTOM_PANEL_SIZE "bottom-panel-size"
Definition at line 156 of file pluma-settings.h.
PLUMA_SETTINGS_BRACKET_MATCHING
#define PLUMA_SETTINGS_BRACKET_MATCHING "bracket-matching"
Definition at line 113 of file pluma-settings.h.
PLUMA_SETTINGS_CLASS
#define PLUMA_SETTINGS_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), PLUMA_TYPE_SETTINGS, PlumaSettingsClass))
Definition at line 37 of file pluma-settings.h.
PLUMA_SETTINGS_COLOR_SCHEME
#define PLUMA_SETTINGS_COLOR_SCHEME "color-scheme"
Definition at line 102 of file pluma-settings.h.
PLUMA_SETTINGS_CONST
#define PLUMA_SETTINGS_CONST (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_SETTINGS, PlumaSettings const))
Definition at line 36 of file pluma-settings.h.
PLUMA_SETTINGS_CREATE_BACKUP_COPY
#define PLUMA_SETTINGS_CREATE_BACKUP_COPY "create-backup-copy"
Definition at line 103 of file pluma-settings.h.
PLUMA_SETTINGS_CTRL_TABS_SWITCH_TABS
#define PLUMA_SETTINGS_CTRL_TABS_SWITCH_TABS "ctrl-tab-switch-tabs"
Definition at line 138 of file pluma-settings.h.
PLUMA_SETTINGS_DISPLAY_LINE_NUMBERS
#define PLUMA_SETTINGS_DISPLAY_LINE_NUMBERS "display-line-numbers"
Definition at line 111 of file pluma-settings.h.
PLUMA_SETTINGS_DISPLAY_OVERVIEW_MAP
#define PLUMA_SETTINGS_DISPLAY_OVERVIEW_MAP "display-overview-map"
Definition at line 144 of file pluma-settings.h.
PLUMA_SETTINGS_DISPLAY_RIGHT_MARGIN
#define PLUMA_SETTINGS_DISPLAY_RIGHT_MARGIN "display-right-margin"
Definition at line 114 of file pluma-settings.h.
PLUMA_SETTINGS_DRAWER_NBSP
#define PLUMA_SETTINGS_DRAWER_NBSP "enable-space-drawer-nbsp"
Definition at line 143 of file pluma-settings.h.
PLUMA_SETTINGS_DRAWER_NEWLINE
#define PLUMA_SETTINGS_DRAWER_NEWLINE "enable-space-drawer-newline"
Definition at line 142 of file pluma-settings.h.
PLUMA_SETTINGS_DRAWER_SPACE
#define PLUMA_SETTINGS_DRAWER_SPACE "enable-space-drawer-space"
Definition at line 140 of file pluma-settings.h.
PLUMA_SETTINGS_DRAWER_TAB
#define PLUMA_SETTINGS_DRAWER_TAB "enable-space-drawer-tab"
Definition at line 141 of file pluma-settings.h.
PLUMA_SETTINGS_EDITOR_FONT
#define PLUMA_SETTINGS_EDITOR_FONT "editor-font"
Definition at line 101 of file pluma-settings.h.
PLUMA_SETTINGS_ENCODING_AUTO_DETECTED
#define PLUMA_SETTINGS_ENCODING_AUTO_DETECTED "auto-detected-encodings"
Definition at line 133 of file pluma-settings.h.
PLUMA_SETTINGS_ENCODING_SHOWN_IN_MENU
#define PLUMA_SETTINGS_ENCODING_SHOWN_IN_MENU "shown-in-menu-encodings"
Definition at line 134 of file pluma-settings.h.
PLUMA_SETTINGS_GET_CLASS
#define PLUMA_SETTINGS_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), PLUMA_TYPE_SETTINGS, PlumaSettingsClass))
Definition at line 40 of file pluma-settings.h.
PLUMA_SETTINGS_HIGHLIGHT_CURRENT_LINE
#define PLUMA_SETTINGS_HIGHLIGHT_CURRENT_LINE "highlight-current-line"
Definition at line 112 of file pluma-settings.h.
PLUMA_SETTINGS_INSERT_SPACES
#define PLUMA_SETTINGS_INSERT_SPACES "insert-spaces"
Definition at line 109 of file pluma-settings.h.
PLUMA_SETTINGS_MAX_RECENTS
#define PLUMA_SETTINGS_MAX_RECENTS "max-recents"
Definition at line 125 of file pluma-settings.h.
PLUMA_SETTINGS_MAX_UNDO_ACTIONS
#define PLUMA_SETTINGS_MAX_UNDO_ACTIONS "max-undo-actions"
Definition at line 106 of file pluma-settings.h.
PLUMA_SETTINGS_PRINT_FONT_BODY_PANGO
#define PLUMA_SETTINGS_PRINT_FONT_BODY_PANGO "print-font-body-pango"
Definition at line 130 of file pluma-settings.h.
PLUMA_SETTINGS_PRINT_FONT_HEADER_PANGO
#define PLUMA_SETTINGS_PRINT_FONT_HEADER_PANGO "print-font-header-pango"
Definition at line 131 of file pluma-settings.h.
PLUMA_SETTINGS_PRINT_FONT_NUMBERS_PANGO
#define PLUMA_SETTINGS_PRINT_FONT_NUMBERS_PANGO "print-font-numbers-pango"
Definition at line 132 of file pluma-settings.h.
PLUMA_SETTINGS_PRINT_HEADER
#define PLUMA_SETTINGS_PRINT_HEADER "print-header"
Definition at line 127 of file pluma-settings.h.
PLUMA_SETTINGS_PRINT_LINE_NUMBERS
#define PLUMA_SETTINGS_PRINT_LINE_NUMBERS "print-line-numbers"
Definition at line 129 of file pluma-settings.h.
PLUMA_SETTINGS_PRINT_SYNTAX_HIGHLIGHTING
#define PLUMA_SETTINGS_PRINT_SYNTAX_HIGHLIGHTING "print-syntax-highlighting"
Definition at line 126 of file pluma-settings.h.
PLUMA_SETTINGS_PRINT_WRAP_MODE
#define PLUMA_SETTINGS_PRINT_WRAP_MODE "print-wrap-mode"
Definition at line 128 of file pluma-settings.h.
PLUMA_SETTINGS_RESTORE_CURSOR_POSITION
#define PLUMA_SETTINGS_RESTORE_CURSOR_POSITION "restore-cursor-position"
Definition at line 117 of file pluma-settings.h.
PLUMA_SETTINGS_RIGHT_MARGIN_POSITION
#define PLUMA_SETTINGS_RIGHT_MARGIN_POSITION "right-margin-position"
Definition at line 115 of file pluma-settings.h.
PLUMA_SETTINGS_RIGHT_PANE_VISIBLE
#define PLUMA_SETTINGS_RIGHT_PANE_VISIBLE "right-panel-visible"
Definition at line 124 of file pluma-settings.h.
PLUMA_SETTINGS_RIGHT_PANEL_ACTIVE_PAGE
#define PLUMA_SETTINGS_RIGHT_PANEL_ACTIVE_PAGE "right-panel-active-page"
Definition at line 159 of file pluma-settings.h.
PLUMA_SETTINGS_RIGHT_PANEL_SIZE
#define PLUMA_SETTINGS_RIGHT_PANEL_SIZE "right-panel-size"
Definition at line 158 of file pluma-settings.h.
PLUMA_SETTINGS_SEARCH_HIGHLIGHTING
#define PLUMA_SETTINGS_SEARCH_HIGHLIGHTING "search-highlighting"
Definition at line 119 of file pluma-settings.h.
PLUMA_SETTINGS_SHOW_SAVE_CONFIRMATION
#define PLUMA_SETTINGS_SHOW_SAVE_CONFIRMATION "show-save-confirmation"
Definition at line 139 of file pluma-settings.h.
PLUMA_SETTINGS_SHOW_SINGLE_TAB
#define PLUMA_SETTINGS_SHOW_SINGLE_TAB "show-single-tab"
Definition at line 136 of file pluma-settings.h.
PLUMA_SETTINGS_SHOW_TABS_WITH_SIDE_PANE
#define PLUMA_SETTINGS_SHOW_TABS_WITH_SIDE_PANE "show-tabs-with-side-pane"
Definition at line 137 of file pluma-settings.h.
PLUMA_SETTINGS_SIDE_PANE_VISIBLE
#define PLUMA_SETTINGS_SIDE_PANE_VISIBLE "side-pane-visible"
Definition at line 122 of file pluma-settings.h.
PLUMA_SETTINGS_SIDE_PANEL_ACTIVE_PAGE
#define PLUMA_SETTINGS_SIDE_PANEL_ACTIVE_PAGE "side-panel-active-page"
Definition at line 155 of file pluma-settings.h.
PLUMA_SETTINGS_SIDE_PANEL_SIZE
#define PLUMA_SETTINGS_SIDE_PANEL_SIZE "side-panel-size"
Definition at line 154 of file pluma-settings.h.
PLUMA_SETTINGS_SMART_HOME_END
#define PLUMA_SETTINGS_SMART_HOME_END "smart-home-end"
Definition at line 149 of file pluma-settings.h.
PLUMA_SETTINGS_STATUSBAR_VISIBLE
#define PLUMA_SETTINGS_STATUSBAR_VISIBLE "statusbar-visible"
Definition at line 121 of file pluma-settings.h.
PLUMA_SETTINGS_SYNTAX_HIGHLIGHTING
#define PLUMA_SETTINGS_SYNTAX_HIGHLIGHTING "syntax-highlighting"
Definition at line 118 of file pluma-settings.h.
PLUMA_SETTINGS_TABS_SIZE
#define PLUMA_SETTINGS_TABS_SIZE "tabs-size"
Definition at line 108 of file pluma-settings.h.
PLUMA_SETTINGS_TOOLBAR_VISIBLE
#define PLUMA_SETTINGS_TOOLBAR_VISIBLE "toolbar-visible"
Definition at line 120 of file pluma-settings.h.
PLUMA_SETTINGS_USE_DEFAULT_FONT
#define PLUMA_SETTINGS_USE_DEFAULT_FONT "use-default-font"
Definition at line 100 of file pluma-settings.h.
PLUMA_SETTINGS_WINDOW_SIZE
#define PLUMA_SETTINGS_WINDOW_SIZE "size"
Definition at line 153 of file pluma-settings.h.
PLUMA_SETTINGS_WINDOW_STATE
#define PLUMA_SETTINGS_WINDOW_STATE "state"
Definition at line 152 of file pluma-settings.h.
PLUMA_SETTINGS_WRAP_MODE
#define PLUMA_SETTINGS_WRAP_MODE "wrap-mode"
Definition at line 107 of file pluma-settings.h.
PLUMA_SETTINGS_WRITABLE_VFS_SCHEMES [1/2]
#define PLUMA_SETTINGS_WRITABLE_VFS_SCHEMES "writable-vfs-schemes"
Definition at line 116 of file pluma-settings.h.
PLUMA_SETTINGS_WRITABLE_VFS_SCHEMES [2/2]
#define PLUMA_SETTINGS_WRITABLE_VFS_SCHEMES "writable-vfs-schemes"
Definition at line 116 of file pluma-settings.h.
PLUMA_TYPE_SETTINGS
#define PLUMA_TYPE_SETTINGS (pluma_settings_get_type ())
Definition at line 34 of file pluma-settings.h.
Typedef Documentation
PlumaSettings
typedef struct _PlumaSettings PlumaSettings
Definition at line 42 of file pluma-settings.h.
PlumaSettingsClass
typedef struct _PlumaSettingsClass PlumaSettingsClass
Definition at line 43 of file pluma-settings.h.
PlumaSettingsPrivate
typedef struct _PlumaSettingsPrivate PlumaSettingsPrivate
Definition at line 44 of file pluma-settings.h.
Enumeration Type Documentation
PlumaToolbarSetting
enum PlumaToolbarSetting
Enumerator
PLUMA_TOOLBAR_SYSTEM
PLUMA_TOOLBAR_ICONS
PLUMA_TOOLBAR_ICONS_AND_TEXT
PLUMA_TOOLBAR_ICONS_BOTH_HORIZ
Definition at line 58 of file pluma-settings.h.
Function Documentation
_pluma_settings_get_singleton()
G_GNUC_INTERNAL PlumaSettings * _pluma_settings_get_singleton (void)
Definition at line 871 of file pluma-settings.c.
References NULL, and PLUMA_TYPE_SETTINGS.
Referenced by pluma_view_set_font().
pluma_settings_get_list()
GSList * pluma_settings_get_list (GSettings * settings, const gchar * key)
Definition at line 1066 of file pluma-settings.c.
References key, and NULL.
Referenced by pluma_settings_get_writable_vfs_schemes().
pluma_settings_get_lockdown()
PlumaLockdownMask pluma_settings_get_lockdown (PlumaSettings * self)
Definition at line 896 of file pluma-settings.c.
References PLUMA_LOCKDOWN_COMMAND_LINE, PLUMA_LOCKDOWN_PRINT_SETUP, PLUMA_LOCKDOWN_PRINTING, PLUMA_LOCKDOWN_SAVE_TO_DISK, PLUMA_SETTINGS_LOCKDOWN_COMMAND_LINE, PLUMA_SETTINGS_LOCKDOWN_PRINT_SETUP, PLUMA_SETTINGS_LOCKDOWN_PRINTING, PLUMA_SETTINGS_LOCKDOWN_SAVE_TO_DISK, and _PlumaSettings::priv.
pluma_settings_get_smart_home_end()
GtkSourceSmartHomeEndType pluma_settings_get_smart_home_end (PlumaSettings * self)
Definition at line 972 of file pluma-settings.c.
References NULL, PLUMA_IS_SETTINGS, and _PlumaSettings::priv.
pluma_settings_get_system_font()
gchar * pluma_settings_get_system_font (PlumaSettings * self)
Definition at line 926 of file pluma-settings.c.
References NULL, PLUMA_IS_SETTINGS, and _PlumaSettings::priv.
Referenced by pluma_view_set_font().
pluma_settings_get_toolbar_style()
PlumaToolbarSetting pluma_settings_get_toolbar_style (PlumaSettings * self)
Definition at line 939 of file pluma-settings.c.
References NULL, PLUMA_IS_SETTINGS, PLUMA_TOOLBAR_ICONS, PLUMA_TOOLBAR_ICONS_AND_TEXT, PLUMA_TOOLBAR_ICONS_BOTH_HORIZ, PLUMA_TOOLBAR_SYSTEM, and _PlumaSettings::priv.
pluma_settings_get_type()
GType pluma_settings_get_type (void)
pluma_settings_get_wrap_mode()
GtkWrapMode pluma_settings_get_wrap_mode (GSettings * settings, const gchar * key)
Definition at line 1020 of file pluma-settings.c.
References key, and NULL.
pluma_settings_get_writable_vfs_schemes()
GSList * pluma_settings_get_writable_vfs_schemes (GSettings * settings)
Definition at line 1095 of file pluma-settings.c.
References DEBUG_PREFS, pluma_debug(), pluma_debug_message(), pluma_settings_get_list(), and PLUMA_SETTINGS_WRITABLE_VFS_SCHEMES.
Referenced by pluma_utils_uri_has_writable_scheme().
pluma_settings_set_list()
void pluma_settings_set_list (GSettings * settings, const gchar * key, GSList * list)
Definition at line 1082 of file pluma-settings.c.
References key, and TRUE.
pluma_settings_set_wrap_mode()
void pluma_settings_set_wrap_mode (GSettings * settings, const gchar * key, GtkWrapMode mode)
Definition at line 1049 of file pluma-settings.c.
References key, and NULL.
pluma_settings_unref_singleton()
void pluma_settings_unref_singleton (void)
Definition at line 882 of file pluma-settings.c.
References NULL.