MATE Desktop Environment: pluma-spell-checker.c File Reference
pluma-spell-checker.c File Reference
#include <string.h>
#include <enchant.h>
#include <glib/gi18n.h>
#include <glib.h>
#include "pluma-spell-checker.h"
#include "pluma-spell-utils.h"
Enumerations
enum { PROP_0 = 0 , PROP_LANGUAGE , LAST_PROP }
enum {
ADD_WORD_TO_PERSONAL = 0 , ADD_WORD_TO_SESSION , SET_LANGUAGE , CLEAR_SESSION ,
LAST_SIGNAL
}
Functions
PlumaSpellChecker * pluma_spell_checker_new (void)
gboolean pluma_spell_checker_set_language (PlumaSpellChecker *spell, const PlumaSpellCheckerLanguage *language)
const PlumaSpellCheckerLanguage * pluma_spell_checker_get_language (PlumaSpellChecker *spell)
gboolean pluma_spell_checker_check_word (PlumaSpellChecker *spell, const gchar *word, gssize len)
GSList * pluma_spell_checker_get_suggestions (PlumaSpellChecker *spell, const gchar *word, gssize len)
gboolean pluma_spell_checker_add_word_to_personal (PlumaSpellChecker *spell, const gchar *word, gssize len)
gboolean pluma_spell_checker_add_word_to_session (PlumaSpellChecker *spell, const gchar *word, gssize len)
gboolean pluma_spell_checker_clear_session (PlumaSpellChecker *spell)
gboolean pluma_spell_checker_set_correction (PlumaSpellChecker *spell, const gchar *word, gssize w_len, const gchar *replacement, gssize r_len)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_LANGUAGE
LAST_PROP
Definition at line 55 of file pluma-spell-checker.c.
anonymous enum
anonymous enum
Enumerator
ADD_WORD_TO_PERSONAL
ADD_WORD_TO_SESSION
SET_LANGUAGE
CLEAR_SESSION
LAST_SIGNAL
Definition at line 62 of file pluma-spell-checker.c.
Function Documentation
pluma_spell_checker_add_word_to_personal()
gboolean pluma_spell_checker_add_word_to_personal (PlumaSpellChecker * spell, const gchar * word, gssize len)
Definition at line 419 of file pluma-spell-checker.c.
References ADD_WORD_TO_PERSONAL, FALSE, NULL, PLUMA_IS_SPELL_CHECKER, signals, and TRUE.
pluma_spell_checker_add_word_to_session()
gboolean pluma_spell_checker_add_word_to_session (PlumaSpellChecker * spell, const gchar * word, gssize len)
Definition at line 443 of file pluma-spell-checker.c.
References ADD_WORD_TO_SESSION, FALSE, NULL, PLUMA_IS_SPELL_CHECKER, signals, and TRUE.
pluma_spell_checker_check_word()
gboolean pluma_spell_checker_check_word (PlumaSpellChecker * spell, const gchar * word, gssize len)
Definition at line 324 of file pluma-spell-checker.c.
References FALSE, NULL, PLUMA_IS_SPELL_CHECKER, pluma_spell_utils_is_digit(), and TRUE.
Referenced by pluma_spell_checker_dialog_set_misspelled_word().
pluma_spell_checker_clear_session()
gboolean pluma_spell_checker_clear_session (PlumaSpellChecker * spell)
Definition at line 466 of file pluma-spell-checker.c.
References CLEAR_SESSION, FALSE, NULL, PLUMA_IS_SPELL_CHECKER, signals, and TRUE.
pluma_spell_checker_get_language()
const PlumaSpellCheckerLanguage * pluma_spell_checker_get_language (PlumaSpellChecker * spell)
Definition at line 313 of file pluma-spell-checker.c.
References NULL, and PLUMA_IS_SPELL_CHECKER.
Referenced by pluma_spell_checker_dialog_set_spell_checker().
pluma_spell_checker_get_suggestions()
GSList * pluma_spell_checker_get_suggestions (PlumaSpellChecker * spell, const gchar * word, gssize len)
Definition at line 377 of file pluma-spell-checker.c.
References NULL, and PLUMA_IS_SPELL_CHECKER.
Referenced by pluma_spell_checker_dialog_set_misspelled_word().
pluma_spell_checker_new()
PlumaSpellChecker * pluma_spell_checker_new (void)
Definition at line 201 of file pluma-spell-checker.c.
References NULL, PLUMA_SPELL_CHECKER, and PLUMA_TYPE_SPELL_CHECKER.
pluma_spell_checker_set_correction()
gboolean pluma_spell_checker_set_correction (PlumaSpellChecker * spell, const gchar * word, gssize w_len, const gchar * replacement, gssize r_len)
Definition at line 490 of file pluma-spell-checker.c.
References FALSE, NULL, PLUMA_IS_SPELL_CHECKER, and TRUE.
pluma_spell_checker_set_language()
gboolean pluma_spell_checker_set_language (PlumaSpellChecker * spell, const PlumaSpellCheckerLanguage * language)
Definition at line 288 of file pluma-spell-checker.c.
References FALSE, NULL, PLUMA_IS_SPELL_CHECKER, pluma_spell_checker_language_to_string(), SET_LANGUAGE, and signals.