MATE Desktop Environment: pluma-debug.c File Reference
pluma-debug.c File Reference
#include <stdio.h>
#include "pluma-debug.h"
Macros
#define ENABLE_PROFILING
Functions
void pluma_debug_init (void)
void pluma_debug_message (PlumaDebugSection section, const gchar *file, gint line, const gchar *function, const gchar *format,...)
void pluma_debug (PlumaDebugSection section, const gchar *file, gint line, const gchar *function)
Macro Definition Documentation
ENABLE_PROFILING
#define ENABLE_PROFILING
Definition at line 41 of file pluma-debug.c.
Function Documentation
pluma_debug()
void pluma_debug (PlumaDebugSection section, const gchar * file, gint line, const gchar * function)
Definition at line 138 of file pluma-debug.c.
References debug, and NULL.
Referenced by _pluma_cmd_documents_move_to_new_window(), _pluma_cmd_documents_next_document(), _pluma_cmd_documents_previous_document(), _pluma_cmd_edit_copy(), _pluma_cmd_edit_cut(), _pluma_cmd_edit_delete(), _pluma_cmd_edit_invert_case(), _pluma_cmd_edit_lower_case(), _pluma_cmd_edit_paste(), _pluma_cmd_edit_preferences(), _pluma_cmd_edit_redo(), _pluma_cmd_edit_select_all(), _pluma_cmd_edit_title_case(), _pluma_cmd_edit_undo(), _pluma_cmd_edit_upper_case(), _pluma_cmd_file_close(), _pluma_cmd_file_close_all(), _pluma_cmd_file_close_tab(), _pluma_cmd_file_new(), _pluma_cmd_file_open(), _pluma_cmd_file_print(), _pluma_cmd_file_print_preview(), _pluma_cmd_file_quit(), _pluma_cmd_file_revert(), _pluma_cmd_file_save(), _pluma_cmd_file_save_as(), _pluma_cmd_file_save_documents_list(), _pluma_cmd_help_about(), _pluma_cmd_help_contents(), _pluma_cmd_load_files_from_prompt(), _pluma_cmd_search_clear_highlight(), _pluma_cmd_search_find(), _pluma_cmd_search_find_next(), _pluma_cmd_search_find_prev(), _pluma_cmd_search_goto_line(), _pluma_cmd_search_incremental_search(), _pluma_cmd_search_replace(), _pluma_cmd_view_show_bottom_pane(), _pluma_cmd_view_show_right_pane(), _pluma_cmd_view_show_side_pane(), _pluma_cmd_view_show_statusbar(), _pluma_cmd_view_show_toolbar(), _pluma_cmd_view_toggle_fullscreen_mode(), _pluma_document_get_seconds_since_last_save_or_load(), _pluma_document_search_region(), _pluma_document_set_readonly(), pluma_commands_load_uris(), pluma_commands_save_all_documents(), pluma_commands_save_document(), pluma_document_goto_line(), pluma_document_loader_cancel(), pluma_document_loader_load(), pluma_document_new(), pluma_document_saver_save(), pluma_metadata_manager_shutdown(), pluma_session_init(), pluma_session_is_restored(), pluma_session_load(), pluma_settings_get_writable_vfs_schemes(), pluma_show_preferences_dialog(), pluma_tab_get_auto_save_enabled(), pluma_tab_get_auto_save_interval(), pluma_tab_set_auto_save_enabled(), pluma_tab_set_auto_save_interval(), pluma_view_copy_clipboard(), pluma_view_cut_clipboard(), pluma_view_delete_selection(), pluma_view_invert_case_selection(), pluma_view_lower_case_selection(), pluma_view_paste_clipboard(), pluma_view_scroll_to_cursor(), pluma_view_select_all(), pluma_view_set_font(), pluma_view_title_case_selection(), and pluma_view_upper_case_selection().
pluma_debug_init()
void pluma_debug_init (void)
Definition at line 51 of file pluma-debug.c.
References debug, NULL, PLUMA_DEBUG_APP, PLUMA_DEBUG_COMMANDS, PLUMA_DEBUG_DOCUMENT, PLUMA_DEBUG_LOADER, PLUMA_DEBUG_METADATA, PLUMA_DEBUG_PLUGINS, PLUMA_DEBUG_PREFS, PLUMA_DEBUG_PRINT, PLUMA_DEBUG_SAVER, PLUMA_DEBUG_SEARCH, PLUMA_DEBUG_SESSION, PLUMA_DEBUG_TAB, PLUMA_DEBUG_UTILS, PLUMA_DEBUG_VIEW, PLUMA_DEBUG_WINDOW, and PLUMA_NO_DEBUG.
Referenced by main().
pluma_debug_message()
void pluma_debug_message (PlumaDebugSection section, const gchar * file, gint line, const gchar * function, const gchar * format, ...)
Definition at line 101 of file pluma-debug.c.
References debug, and NULL.
Referenced by _pluma_cmd_file_save_documents_list(), create_taglist(), free_taglist(), G_DEFINE_TYPE_WITH_CODE(), main(), pluma_commands_load_uri(), pluma_document_loader_loading(), pluma_document_saver_saving(), pluma_document_search_backward(), pluma_document_search_forward(), pluma_document_set_last_replace_text(), pluma_document_set_search_text(), pluma_metadata_manager_get(), pluma_metadata_manager_set(), pluma_session_is_restored(), pluma_settings_get_writable_vfs_schemes(), pluma_utils_escape_search_text(), pluma_utils_uri_exists(), and pluma_view_new().