MATE Desktop Environment: polkitmateauthenticator.h File Reference
polkitmateauthenticator.h File Reference
#include <glib-object.h>
Macros
#define POLKIT_MATE_TYPE_AUTHENTICATOR (polkit_mate_authenticator_get_type())
#define POLKIT_MATE_AUTHENTICATOR(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), POLKIT_MATE_TYPE_AUTHENTICATOR, PolkitMateAuthenticator))
#define POLKIT_MATE_AUTHENTICATOR_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), POLKIT_MATE_TYPE_AUTHENTICATOR, PolkitMateAuthenticatorClass))
#define POLKIT_MATE_AUTHENTICATOR_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), POLKIT_MATE_TYPE_AUTHENTICATOR, PolkitMateAuthenticatorClass))
#define POLKIT_MATE_IS_AUTHENTICATOR(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), POLKIT_MATE_TYPE_AUTHENTICATOR))
#define POLKIT_MATE_IS_AUTHENTICATOR_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), POLKIT_MATE_TYPE_AUTHENTICATOR))
Typedefs
typedef struct _PolkitMateAuthenticator PolkitMateAuthenticator
typedef struct _PolkitMateAuthenticatorClass PolkitMateAuthenticatorClass
Functions
GType polkit_mate_authenticator_get_type (void)
PolkitMateAuthenticator * polkit_mate_authenticator_new (const gchar *action_id, const gchar *message, const gchar *icon_name, PolkitDetails *details, const gchar *cookie, GList *identities)
void polkit_mate_authenticator_initiate (PolkitMateAuthenticator *authenticator)
void polkit_mate_authenticator_cancel (PolkitMateAuthenticator *authenticator)
const gchar * polkit_mate_authenticator_get_cookie (PolkitMateAuthenticator *authenticator)
Macro Definition Documentation
POLKIT_MATE_AUTHENTICATOR
#define POLKIT_MATE_AUTHENTICATOR (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), POLKIT_MATE_TYPE_AUTHENTICATOR, PolkitMateAuthenticator))
Definition at line 33 of file polkitmateauthenticator.h.
POLKIT_MATE_AUTHENTICATOR_CLASS
#define POLKIT_MATE_AUTHENTICATOR_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), POLKIT_MATE_TYPE_AUTHENTICATOR, PolkitMateAuthenticatorClass))
Definition at line 34 of file polkitmateauthenticator.h.
POLKIT_MATE_AUTHENTICATOR_GET_CLASS
#define POLKIT_MATE_AUTHENTICATOR_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), POLKIT_MATE_TYPE_AUTHENTICATOR, PolkitMateAuthenticatorClass))
Definition at line 35 of file polkitmateauthenticator.h.
POLKIT_MATE_IS_AUTHENTICATOR
#define POLKIT_MATE_IS_AUTHENTICATOR (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), POLKIT_MATE_TYPE_AUTHENTICATOR))
Definition at line 36 of file polkitmateauthenticator.h.
POLKIT_MATE_IS_AUTHENTICATOR_CLASS
#define POLKIT_MATE_IS_AUTHENTICATOR_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), POLKIT_MATE_TYPE_AUTHENTICATOR))
Definition at line 37 of file polkitmateauthenticator.h.
POLKIT_MATE_TYPE_AUTHENTICATOR
#define POLKIT_MATE_TYPE_AUTHENTICATOR (polkit_mate_authenticator_get_type())
Definition at line 32 of file polkitmateauthenticator.h.
Typedef Documentation
PolkitMateAuthenticator
typedef struct _PolkitMateAuthenticator PolkitMateAuthenticator
Definition at line 39 of file polkitmateauthenticator.h.
PolkitMateAuthenticatorClass
typedef struct _PolkitMateAuthenticatorClass PolkitMateAuthenticatorClass
Definition at line 40 of file polkitmateauthenticator.h.
Function Documentation
polkit_mate_authenticator_cancel()
void polkit_mate_authenticator_cancel (PolkitMateAuthenticator * authenticator)
Definition at line 498 of file polkitmateauthenticator.c.
References NULL, POLKIT_MATE_AUTHENTICATION_DIALOG, polkit_mate_authentication_dialog_cancel(), and TRUE.
polkit_mate_authenticator_get_cookie()
const gchar * polkit_mate_authenticator_get_cookie (PolkitMateAuthenticator * authenticator)
Definition at line 512 of file polkitmateauthenticator.c.
polkit_mate_authenticator_get_type()
GType polkit_mate_authenticator_get_type (void)
polkit_mate_authenticator_initiate()
void polkit_mate_authenticator_initiate (PolkitMateAuthenticator * authenticator)
Definition at line 491 of file polkitmateauthenticator.c.
polkit_mate_authenticator_new()
PolkitMateAuthenticator * polkit_mate_authenticator_new (const gchar * action_id, const gchar * message, const gchar * icon_name, PolkitDetails * details, const gchar * cookie, GList * identities)
Definition at line 205 of file polkitmateauthenticator.c.
References error, message(), NULL, polkit_mate_authentication_dialog_new(), POLKIT_MATE_AUTHENTICATOR, and POLKIT_MATE_TYPE_AUTHENTICATOR.