MATE Desktop Environment: power-management.c File Reference
power-management.c File Reference
#include <sys/file.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include "battstat.h"
#include "battstat-upower.h"
Macros
#define ERR_ACPID
#define ERR_OPEN_APMDEV
#define ERR_APM_E
#define ERR_NO_SUPPORT
#define ERR_FREEBSD_ACPI
Functions
const char * power_management_getinfo (BatteryStatus *status)
const char * power_management_initialise (void(*callback)(void))
void power_management_cleanup (void)
gboolean power_management_using_upower (void)
Macro Definition Documentation
ERR_ACPID
#define ERR_ACPID
Value:
                    _("Can't access ACPI events in /var/run/acpid.socket! "    \
                    "Make sure the ACPI subsystem is working and "           \
                    "the acpid daemon is running.")
Definition at line 45 of file power-management.c.
ERR_APM_E
#define ERR_APM_E
Value:
                    _("The APM Management subsystem seems to be disabled.\n"  \
                    "Try executing \"apm -e 1\" (FreeBSD) and see if \n"    \
                    "that helps.\n")
Definition at line 53 of file power-management.c.
ERR_FREEBSD_ACPI
#define ERR_FREEBSD_ACPI
Value:
                           _("There was an error reading information from "   \
                           "the ACPI subsystem.  Check to make sure the "   \
                           "ACPI subsystem is properly loaded.")
Definition at line 60 of file power-management.c.
ERR_NO_SUPPORT
#define ERR_NO_SUPPORT
Value:
                         _("Your platform is not supported!  The battery\n"   \
                         "monitor applet will not work on your system.\n")
Definition at line 57 of file power-management.c.
ERR_OPEN_APMDEV
#define ERR_OPEN_APMDEV
Value:
                          _("Can't open the APM device!\n\n"                  \
                          "Make sure you have read permission to the\n"     \
                          "APM device.")
Definition at line 49 of file power-management.c.
Function Documentation
power_management_cleanup()
void power_management_cleanup (void)
Definition at line 497 of file power-management.c.
References acpi_freebsd_cleanup(), acpi_linux_cleanup(), battstat_upower_cleanup(), FALSE, and TRUE.
power_management_getinfo()
const char * power_management_getinfo (BatteryStatus * status)
Definition at line 380 of file power-management.c.
References battstat_upower_get_battery_info(), BatteryStatus::charging, FALSE, BatteryStatus::minutes, NULL, BatteryStatus::on_ac_power, BatteryStatus::percent, BatteryStatus::present, and TRUE.
power_management_initialise()
const char * power_management_initialise (void(*)(void) callback)
Definition at line 433 of file power-management.c.
References acpi_freebsd_init(), acpi_linux_init(), apm_exists(), battstat_upower_initialise(), ERR_ACPID, FALSE, NULL, and TRUE.
power_management_using_upower()
gboolean power_management_using_upower (void)
Definition at line 526 of file power-management.c.
References FALSE.