MATE Desktop Environment: procactions.cpp File Reference
procactions.cpp File Reference
#include <config.h>
#include <errno.h>
#include <glib/gi18n.h>
#include <signal.h>
#include <sys/time.h>
#include <sys/resource.h>
#include "procactions.h"
#include "procman.h"
#include "proctable.h"
#include "procdialogs.h"
#include "callbacks.h"
Functions
void renice (ProcData *procdata, int nice)
void kill_process (ProcData *procdata, int sig)
Function Documentation
kill_process()
void kill_process (ProcData * procdata, int sig)
Definition at line 175 of file procactions.cpp.
References cb_timeout(), ProcData::config, KillArgs::procdata, proctable_update(), ProcData::selection, ProcData::timeout, and ProcConfig::update_interval.
Referenced by cb_kill_sigcont(), and cb_kill_sigstop().
renice()
void renice (ProcData * procdata, int nice)
Definition at line 95 of file procactions.cpp.
References cb_timeout(), ProcData::config, ReniceArgs::procdata, proctable_update(), ProcData::selection, ProcData::timeout, and ProcConfig::update_interval.
Referenced by cb_renice().