MATE Desktop Environment: procdialogs.h File Reference
procdialogs.h File Reference
#include <glib.h>
#include "procman.h"
Macros
#define RENICE_VAL_MIN -20
#define RENICE_VAL_MAX 20
Enumerations
enum ProcmanActionType { PROCMAN_ACTION_RENICE , PROCMAN_ACTION_KILL }
Functions
void procdialog_create_kill_dialog (ProcData *data, int signal)
void procdialog_create_renice_dialog (ProcData *data)
gboolean procdialog_create_root_password_dialog (ProcmanActionType type, ProcData *procdata, gint pid, gint extra_value)
void procdialog_create_memmaps_dialog (ProcData *data)
void procdialog_create_preferences_dialog (ProcData *data)
Macro Definition Documentation
RENICE_VAL_MAX
#define RENICE_VAL_MAX 20
Definition at line 34 of file procdialogs.h.
RENICE_VAL_MIN
#define RENICE_VAL_MIN -20
Definition at line 33 of file procdialogs.h.
Enumeration Type Documentation
ProcmanActionType
enum ProcmanActionType
Enumerator
PROCMAN_ACTION_RENICE
PROCMAN_ACTION_KILL
Definition at line 37 of file procdialogs.h.
Function Documentation
procdialog_create_kill_dialog()
void procdialog_create_kill_dialog (ProcData * data, int signal)
Definition at line 62 of file procdialogs.cpp.
References _, ProcData::app, get_last_selected(), ProcInfo::name, NULL, ProcInfo::pid, KillArgs::procdata, ProcData::selection, and KillArgs::signal.
procdialog_create_memmaps_dialog()
void procdialog_create_memmaps_dialog (ProcData * data)
procdialog_create_preferences_dialog()
void procdialog_create_preferences_dialog (ProcData * data)
Definition at line 449 of file procdialogs.cpp.
References ProcData::config, ProcConfig::current_tab, ProcData::disk_list, ProcConfig::disks_update_interval, GET_WIDGET, ProcConfig::graph_update_interval, SmoothRefresh::KEY, procman::settings::network_in_bits, NULL, PROCMAN_TAB_DISKS, PROCMAN_TAB_PROCESSES, PROCMAN_TAB_RESOURCES, PROCMAN_TAB_SYSINFO, ProcData::settings, procman::settings::solaris_mode, ProcData::tree, and ProcConfig::update_interval.
Referenced by cb_edit_preferences().
procdialog_create_renice_dialog()
void procdialog_create_renice_dialog (ProcData * data)
Definition at line 170 of file procdialogs.cpp.
References _, FALSE, get_last_selected(), procman::get_nice_level(), label, ProcInfo::name, MutableProcInfo::nice, NULL, ProcInfo::pid, KillArgs::procdata, RENICE_VAL_MAX, RENICE_VAL_MIN, ProcData::selection, and TRUE.
Referenced by cb_renice().
procdialog_create_root_password_dialog()
gboolean procdialog_create_root_password_dialog (ProcmanActionType type, ProcData * procdata, gint pid, gint extra_value)
Definition at line 571 of file procdialogs.cpp.
References command, FALSE, procman_debug, procman_gksu_create_root_password_dialog(), procman_has_gksu(), procman_has_pkexec(), procman_pkexec_create_root_password_dialog(), and type.