MATE Desktop Environment: procman.h File Reference
procman.h File Reference
#include <glibmm/refptr.h>
#include <cairo-gobject.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <glib.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <glibtop/cpu.h>
#include <time.h>
#include <sys/types.h>
#include <map>
#include <string>
#include "smooth_refresh.h"
#include "prettytable.h"
Classes
struct ProcConfig
struct MutableProcInfo
class ProcInfo
struct ProcData
struct ReniceArgs
struct KillArgs
Macros
#define GSM_GSETTINGS_SCHEMA "org.mate.system-monitor"
Enumerations
enum { ALL_PROCESSES , MY_PROCESSES , ACTIVE_PROCESSES }
enum {
VERY_HIGH_PRIORITY , HIGH_PRIORITY , NORMAL_PRIORITY , LOW_PRIORITY ,
VERY_LOW_PRIORITY , CUSTOM_PRIORITY
}
enum ProcmanTab { PROCMAN_TAB_SYSINFO , PROCMAN_TAB_PROCESSES , PROCMAN_TAB_RESOURCES , PROCMAN_TAB_DISKS }
Functions
void procman_save_config (ProcData *data)
void procman_save_tree_state (GSettings *settings, GtkWidget *tree, const gchar *prefix)
gboolean procman_get_tree_state (GSettings *settings, GtkWidget *tree, const gchar *prefix)
Macro Definition Documentation
GSM_GSETTINGS_SCHEMA
#define GSM_GSETTINGS_SCHEMA "org.mate.system-monitor"
Definition at line 44 of file procman.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ALL_PROCESSES
MY_PROCESSES
ACTIVE_PROCESSES
Definition at line 46 of file procman.h.
anonymous enum
anonymous enum
Enumerator
VERY_HIGH_PRIORITY
HIGH_PRIORITY
NORMAL_PRIORITY
LOW_PRIORITY
VERY_LOW_PRIORITY
CUSTOM_PRIORITY
Definition at line 53 of file procman.h.
ProcmanTab
enum ProcmanTab
Enumerator
PROCMAN_TAB_SYSINFO
PROCMAN_TAB_PROCESSES
PROCMAN_TAB_RESOURCES
PROCMAN_TAB_DISKS
Definition at line 66 of file procman.h.
Function Documentation
procman_get_tree_state()
gboolean procman_get_tree_state (GSettings * settings, GtkWidget * tree, const gchar * prefix)
Definition at line 53 of file procman.cpp.
References id, key, MAX, NULL, proctable_set_columns_order(), and TRUE.
Referenced by create_disk_view(), and proctable_new().
procman_save_config()
void procman_save_config (ProcData * data)
Definition at line 184 of file procman.cpp.
References data.
Referenced by cb_app_delete().
procman_save_tree_state()
void procman_save_tree_state (GSettings * settings, GtkWidget * tree, const gchar * prefix)
Definition at line 135 of file procman.cpp.
References ProcData::get_instance(), and proctable_get_columns_order().