MATE Desktop Environment: proctable.h File Reference
proctable.h File Reference
#include <glib.h>
#include <gtk/gtk.h>
#include "procman.h"
Enumerations
enum {
COL_NAME = 0 , COL_USER , COL_STATUS , COL_VMSIZE ,
COL_MEMRES , COL_MEMWRITABLE , COL_MEMSHARED , COL_MEMXSERVER ,
COL_CPU , COL_CPU_TIME , COL_START_TIME , COL_NICE ,
COL_PID , COL_SECURITYCONTEXT , COL_ARGS , COL_MEM ,
COL_WCHAN , COL_CGROUP , COL_UNIT , COL_SESSION ,
COL_SEAT , COL_OWNER , COL_DISK_WRITE_TOTAL , COL_DISK_READ_TOTAL ,
COL_DISK_WRITE_CURRENT , COL_DISK_READ_CURRENT , COL_PRIORITY , COL_SURFACE ,
COL_POINTER , COL_TOOLTIP , NUM_COLUMNS
}
Functions
GtkWidget * proctable_new (ProcData *data)
void proctable_update_table (ProcData *data)
void proctable_update (ProcData *data)
void proctable_clear_tree (ProcData *data)
void proctable_free_table (ProcData *data)
GSList * proctable_get_columns_order (GtkTreeView *treeview)
void proctable_set_columns_order (GtkTreeView *treeview, GSList *order)
char * make_loadavg_string (void)
void get_last_selected (GtkTreeModel *model, GtkTreePath *path, GtkTreeIter *iter, gpointer data)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COL_NAME
COL_USER
COL_STATUS
COL_VMSIZE
COL_MEMRES
COL_MEMWRITABLE
COL_MEMSHARED
COL_MEMXSERVER
COL_CPU
COL_CPU_TIME
COL_START_TIME
COL_NICE
COL_PID
COL_SECURITYCONTEXT
COL_ARGS
COL_MEM
COL_WCHAN
COL_CGROUP
COL_UNIT
COL_SESSION
COL_SEAT
COL_OWNER
COL_DISK_WRITE_TOTAL
COL_DISK_READ_TOTAL
COL_DISK_WRITE_CURRENT
COL_DISK_READ_CURRENT
COL_PRIORITY
COL_SURFACE
COL_POINTER
COL_TOOLTIP
NUM_COLUMNS
Definition at line 28 of file proctable.h.
Function Documentation
get_last_selected()
void get_last_selected (GtkTreeModel * model, GtkTreePath * path, GtkTreeIter * iter, gpointer data)
Definition at line 79 of file proctable.cpp.
References COL_POINTER, and data.
Referenced by cb_row_selected(), procdialog_create_kill_dialog(), and procdialog_create_renice_dialog().
make_loadavg_string()
char * make_loadavg_string (void)
Definition at line 1173 of file proctable.cpp.
References _.
Referenced by proctable_update().
proctable_clear_tree()
void proctable_clear_tree (ProcData * data)
Definition at line 1158 of file proctable.cpp.
References proctable_free_table(), ProcData::tree, and update_sensitivity().
proctable_free_table()
void proctable_free_table (ProcData * data)
Definition at line 1148 of file proctable.cpp.
References ProcInfo::all, ProcInfo::begin(), and ProcInfo::end().
Referenced by proctable_clear_tree().
proctable_get_columns_order()
GSList * proctable_get_columns_order (GtkTreeView * treeview)
Definition at line 156 of file proctable.cpp.
References id, and NULL.
Referenced by procman_save_tree_state().
proctable_new()
GtkWidget * proctable_new (ProcData * data)
Definition at line 244 of file proctable.cpp.
References _, can_show_security_context_column(), cb_row_selected(), cb_tree_button_pressed(), cb_tree_popup_menu(), cgroups_enabled(), COL_ARGS, COL_CGROUP, COL_CPU, COL_CPU_TIME, COL_DISK_READ_CURRENT, COL_DISK_READ_TOTAL, COL_DISK_WRITE_CURRENT, COL_DISK_WRITE_TOTAL, COL_MEM, COL_MEMRES, COL_MEMSHARED, COL_MEMWRITABLE, COL_MEMXSERVER, COL_NAME, COL_NICE, COL_OWNER, COL_PID, COL_PRIORITY, COL_SECURITYCONTEXT, COL_START_TIME, COL_STATUS, COL_SURFACE, COL_TOOLTIP, COL_UNIT, COL_USER, COL_VMSIZE, ProcData::config, procman::duration_cell_data_func(), FALSE, procman::io_rate_cell_data_func(), LOGIND_RUNNING, procman::memory_size_cell_data_func(), procman::memory_size_na_cell_data_func(), N_, NULL, NUM_COLUMNS, procman::number_compare_func(), procman::priority_cell_data_func(), procman::priority_compare_func(), procman_get_tree_state(), ProcData::settings, ProcConfig::show_tree, procman::status_cell_data_func(), procman::storage_size_na_cell_data_func(), procman::time_cell_data_func(), ProcData::tree, and TRUE.
proctable_set_columns_order()
void proctable_set_columns_order (GtkTreeView * treeview, GSList * order)
Definition at line 132 of file proctable.cpp.
References id, and NULL.
Referenced by procman_get_tree_state().
proctable_update()
void proctable_update (ProcData * data)
Definition at line 1135 of file proctable.cpp.
References ProcData::loadavg, and make_loadavg_string().
Referenced by cb_timeout(), cb_user_refresh(), kill_process(), and renice().
proctable_update_table()
void proctable_update_table (ProcData * data)