MATE Desktop Environment: procdialogs.cpp File Reference
procdialogs.cpp File Reference
#include <config.h>
#include <glib/gi18n.h>
#include <signal.h>
#include <string.h>
#include "procdialogs.h"
#include "proctable.h"
#include "callbacks.h"
#include "prettytable.h"
#include "procactions.h"
#include "util.h"
#include "load-graph.h"
#include "settings-keys.h"
#include "procman_gksu.h"
#include "procman_pkexec.h"
#include "cgroups.h"
Macros
#define GET_WIDGET(x) GTK_WIDGET(gtk_builder_get_object(builder, x))
Functions
void procdialog_create_kill_dialog (ProcData *procdata, int signal)
void procdialog_create_renice_dialog (ProcData *procdata)
void procdialog_create_preferences_dialog (ProcData *procdata)
gboolean procdialog_create_root_password_dialog (ProcmanActionType type, ProcData *procdata, gint pid, gint extra_value)
Macro Definition Documentation
GET_WIDGET
#define GET_WIDGET (x) GTK_WIDGET(gtk_builder_get_object(builder, x))
Definition at line 41 of file procdialogs.cpp.
Function Documentation
procdialog_create_kill_dialog()
void procdialog_create_kill_dialog (ProcData * procdata, int signal)
Definition at line 62 of file procdialogs.cpp.
References _, ProcData::app, get_last_selected(), ProcInfo::name, NULL, ProcInfo::pid, KillArgs::procdata, ProcData::selection, and KillArgs::signal.
procdialog_create_preferences_dialog()
void procdialog_create_preferences_dialog (ProcData * procdata)
Definition at line 449 of file procdialogs.cpp.
References ProcData::config, ProcConfig::current_tab, ProcData::disk_list, ProcConfig::disks_update_interval, GET_WIDGET, ProcConfig::graph_update_interval, SmoothRefresh::KEY, procman::settings::network_in_bits, NULL, PROCMAN_TAB_DISKS, PROCMAN_TAB_PROCESSES, PROCMAN_TAB_RESOURCES, PROCMAN_TAB_SYSINFO, ProcData::settings, procman::settings::solaris_mode, ProcData::tree, and ProcConfig::update_interval.
Referenced by cb_edit_preferences().
procdialog_create_renice_dialog()
void procdialog_create_renice_dialog (ProcData * procdata)
Definition at line 170 of file procdialogs.cpp.
References _, FALSE, get_last_selected(), procman::get_nice_level(), label, ProcInfo::name, MutableProcInfo::nice, NULL, ProcInfo::pid, KillArgs::procdata, RENICE_VAL_MAX, RENICE_VAL_MIN, ProcData::selection, and TRUE.
Referenced by cb_renice().
procdialog_create_root_password_dialog()
gboolean procdialog_create_root_password_dialog (ProcmanActionType type, ProcData * procdata, gint pid, gint extra_value)
Definition at line 571 of file procdialogs.cpp.
References command, FALSE, procman_debug, procman_gksu_create_root_password_dialog(), procman_has_gksu(), procman_has_pkexec(), procman_pkexec_create_root_password_dialog(), and type.