MATE Desktop Environment: procman.cpp File Reference
procman.cpp File Reference
#include <config.h>
#include <stdlib.h>
#include <locale.h>
#include <gtkmm.h>
#include <glib/gi18n.h>
#include "procman-app.h"
#include "procman.h"
#include "proctable.h"
Functions
gboolean procman_get_tree_state (GSettings *settings, GtkWidget *tree, const gchar *child_schema)
void procman_save_tree_state (GSettings *settings, GtkWidget *tree, const gchar *child_schema)
void procman_save_config (ProcData *data)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 208 of file procman.cpp.
References ProcmanApp::create().
procman_get_tree_state()
gboolean procman_get_tree_state (GSettings * settings, GtkWidget * tree, const gchar * child_schema)
Definition at line 53 of file procman.cpp.
References id, key, MAX, NULL, proctable_set_columns_order(), and TRUE.
Referenced by create_disk_view(), and proctable_new().
procman_save_config()
void procman_save_config (ProcData * data)
Definition at line 184 of file procman.cpp.
References data.
Referenced by cb_app_delete().
procman_save_tree_state()
void procman_save_tree_state (GSettings * settings, GtkWidget * tree, const gchar * child_schema)
Definition at line 135 of file procman.cpp.
References ProcData::get_instance(), and proctable_get_columns_order().