MATE Desktop Environment: pulse-source.h File Reference
pulse-source.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <pulse/pulseaudio.h>
#include "pulse-stream.h"
#include "pulse-types.h"
Classes
struct _PulseSource
struct _PulseSourceClass
Macros
#define PULSE_TYPE_SOURCE (pulse_source_get_type ())
#define PULSE_SOURCE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_SOURCE, PulseSource))
#define PULSE_IS_SOURCE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_SOURCE))
#define PULSE_SOURCE_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_SOURCE, PulseSourceClass))
#define PULSE_IS_SOURCE_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_SOURCE))
#define PULSE_SOURCE_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_SOURCE, PulseSourceClass))
Typedefs
typedef struct _PulseSourceClass PulseSourceClass
typedef struct _PulseSourcePrivate PulseSourcePrivate
Functions
GType pulse_source_get_type (void)
PulseSource * pulse_source_new (PulseConnection *connection, const pa_source_info *info, PulseDevice *device)
gboolean pulse_source_add_output (PulseSource *source, const pa_source_output_info *info)
void pulse_source_remove_output (PulseSource *source, guint32 index)
void pulse_source_update (PulseSource *source, const pa_source_info *info)
Macro Definition Documentation
PULSE_IS_SOURCE
#define PULSE_IS_SOURCE (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_SOURCE))
Definition at line 35 of file pulse-source.h.
PULSE_IS_SOURCE_CLASS
#define PULSE_IS_SOURCE_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_SOURCE))
Definition at line 39 of file pulse-source.h.
PULSE_SOURCE
#define PULSE_SOURCE (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_SOURCE, PulseSource))
Definition at line 33 of file pulse-source.h.
PULSE_SOURCE_CLASS
#define PULSE_SOURCE_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_SOURCE, PulseSourceClass))
Definition at line 37 of file pulse-source.h.
PULSE_SOURCE_GET_CLASS
#define PULSE_SOURCE_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_SOURCE, PulseSourceClass))
Definition at line 41 of file pulse-source.h.
PULSE_TYPE_SOURCE
#define PULSE_TYPE_SOURCE (pulse_source_get_type ())
Definition at line 31 of file pulse-source.h.
Typedef Documentation
PulseSourceClass
typedef struct _PulseSourceClass PulseSourceClass
Definition at line 44 of file pulse-source.h.
PulseSourcePrivate
typedef struct _PulseSourcePrivate PulseSourcePrivate
Definition at line 45 of file pulse-source.h.
Function Documentation
pulse_source_add_output()
gboolean pulse_source_add_output (PulseSource * source, const pa_source_output_info * info)
Definition at line 180 of file pulse-source.c.
References connection, FALSE, MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), name, NULL, _PulseSource::priv, PULSE_IS_SOURCE, pulse_source_output_new(), pulse_source_output_update(), PULSE_STREAM, pulse_stream_get_connection(), and TRUE.
pulse_source_get_type()
GType pulse_source_get_type (void)
pulse_source_new()
PulseSource * pulse_source_new (PulseConnection * connection, const pa_source_info * info, PulseDevice * device)
Definition at line 116 of file pulse-source.c.
References _, _mate_mixer_stream_set_default_control(), connection, MATE_MIXER_DIRECTION_INPUT, MATE_MIXER_STREAM, MATE_MIXER_STREAM_CONTROL, MATE_MIXER_SWITCH_OPTION, mate_mixer_switch_option_get_icon(), NULL, _PulseSource::priv, PULSE_DEVICE, pulse_device_get_port(), PULSE_IS_CONNECTION, PULSE_IS_DEVICE, pulse_port_new(), pulse_port_switch_add_port(), pulse_port_switch_set_active_port(), pulse_source_control_new(), pulse_source_switch_new(), pulse_source_update(), and PULSE_TYPE_SOURCE.
pulse_source_remove_output()
void pulse_source_remove_output (PulseSource * source, guint32 index)
Definition at line 215 of file pulse-source.c.
References MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), name, NULL, _PulseSource::priv, and PULSE_IS_SOURCE.
pulse_source_update()
void pulse_source_update (PulseSource * source, const pa_source_info * info)
Definition at line 238 of file pulse-source.c.
References NULL, _PulseSource::priv, PULSE_IS_SOURCE, pulse_port_switch_set_active_port_by_name(), and pulse_source_control_update().
Referenced by pulse_source_new().