MATE Desktop Environment: pulse-stream.h File Reference
pulse-stream.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include <pulse/pulseaudio.h>
#include "pulse-types.h"
Classes
struct _PulseStream
struct _PulseStreamClass
Macros
#define PULSE_TYPE_STREAM (pulse_stream_get_type ())
#define PULSE_STREAM(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_STREAM, PulseStream))
#define PULSE_IS_STREAM(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_STREAM))
#define PULSE_STREAM_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_STREAM, PulseStreamClass))
#define PULSE_IS_STREAM_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_STREAM))
#define PULSE_STREAM_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_STREAM, PulseStreamClass))
Typedefs
typedef struct _PulseStreamClass PulseStreamClass
typedef struct _PulseStreamPrivate PulseStreamPrivate
Functions
GType pulse_stream_get_type (void)
guint32 pulse_stream_get_index (PulseStream *stream)
PulseConnection * pulse_stream_get_connection (PulseStream *stream)
PulseDevice * pulse_stream_get_device (PulseStream *stream)
Macro Definition Documentation
PULSE_IS_STREAM
#define PULSE_IS_STREAM (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_STREAM))
Definition at line 35 of file pulse-stream.h.
PULSE_IS_STREAM_CLASS
#define PULSE_IS_STREAM_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_STREAM))
Definition at line 39 of file pulse-stream.h.
PULSE_STREAM
#define PULSE_STREAM (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_STREAM, PulseStream))
Definition at line 33 of file pulse-stream.h.
PULSE_STREAM_CLASS
#define PULSE_STREAM_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_STREAM, PulseStreamClass))
Definition at line 37 of file pulse-stream.h.
PULSE_STREAM_GET_CLASS
#define PULSE_STREAM_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_STREAM, PulseStreamClass))
Definition at line 41 of file pulse-stream.h.
PULSE_TYPE_STREAM
#define PULSE_TYPE_STREAM (pulse_stream_get_type ())
Definition at line 31 of file pulse-stream.h.
Typedef Documentation
PulseStreamClass
typedef struct _PulseStreamClass PulseStreamClass
Definition at line 44 of file pulse-stream.h.
PulseStreamPrivate
typedef struct _PulseStreamPrivate PulseStreamPrivate
Definition at line 45 of file pulse-stream.h.
Function Documentation
pulse_stream_get_connection()
PulseConnection * pulse_stream_get_connection (PulseStream * stream)
Definition at line 166 of file pulse-stream.c.
References NULL, and PULSE_IS_STREAM.
Referenced by pulse_sink_add_input(), and pulse_source_add_output().
pulse_stream_get_device()
PulseDevice * pulse_stream_get_device (PulseStream * stream)
Definition at line 174 of file pulse-stream.c.
References MATE_MIXER_STREAM, mate_mixer_stream_get_device(), NULL, PULSE_DEVICE, and PULSE_IS_STREAM.
pulse_stream_get_index()
guint32 pulse_stream_get_index (PulseStream * stream)
Definition at line 158 of file pulse-stream.c.
References PULSE_IS_STREAM.
Referenced by pulse_stream_control_get_stream_index().
pulse_stream_get_type()
GType pulse_stream_get_type (void)