MATE Desktop Environment: pulse-ext-stream.h File Reference
pulse-ext-stream.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <pulse/pulseaudio.h>
#include <pulse/ext-stream-restore.h>
#include "pulse-stream-control.h"
#include "pulse-types.h"
Classes
struct _PulseExtStream
struct _PulseExtStreamClass
Macros
#define PULSE_TYPE_EXT_STREAM (pulse_ext_stream_get_type ())
#define PULSE_EXT_STREAM(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_EXT_STREAM, PulseExtStream))
#define PULSE_IS_EXT_STREAM(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_EXT_STREAM))
#define PULSE_EXT_STREAM_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_EXT_STREAM, PulseExtStreamClass))
#define PULSE_IS_EXT_STREAM_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_EXT_STREAM))
#define PULSE_EXT_STREAM_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_EXT_STREAM, PulseExtStreamClass))
Typedefs
typedef struct _PulseExtStreamClass PulseExtStreamClass
typedef struct _PulseExtStreamPrivate PulseExtStreamPrivate
Functions
GType pulse_ext_stream_get_type (void)
PulseExtStream * pulse_ext_stream_new (PulseConnection *connection, const pa_ext_stream_restore_info *info, PulseStream *parent)
void pulse_ext_stream_update (PulseExtStream *ext, const pa_ext_stream_restore_info *info, PulseStream *parent)
Macro Definition Documentation
PULSE_EXT_STREAM
#define PULSE_EXT_STREAM (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_EXT_STREAM, PulseExtStream))
Definition at line 34 of file pulse-ext-stream.h.
PULSE_EXT_STREAM_CLASS
#define PULSE_EXT_STREAM_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_EXT_STREAM, PulseExtStreamClass))
Definition at line 38 of file pulse-ext-stream.h.
PULSE_EXT_STREAM_GET_CLASS
#define PULSE_EXT_STREAM_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_EXT_STREAM, PulseExtStreamClass))
Definition at line 42 of file pulse-ext-stream.h.
PULSE_IS_EXT_STREAM
#define PULSE_IS_EXT_STREAM (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_EXT_STREAM))
Definition at line 36 of file pulse-ext-stream.h.
PULSE_IS_EXT_STREAM_CLASS
#define PULSE_IS_EXT_STREAM_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_EXT_STREAM))
Definition at line 40 of file pulse-ext-stream.h.
PULSE_TYPE_EXT_STREAM
#define PULSE_TYPE_EXT_STREAM (pulse_ext_stream_get_type ())
Definition at line 32 of file pulse-ext-stream.h.
Typedef Documentation
PulseExtStreamClass
typedef struct _PulseExtStreamClass PulseExtStreamClass
Definition at line 45 of file pulse-ext-stream.h.
PulseExtStreamPrivate
typedef struct _PulseExtStreamPrivate PulseExtStreamPrivate
Definition at line 46 of file pulse-ext-stream.h.
Function Documentation
pulse_ext_stream_get_type()
GType pulse_ext_stream_get_type (void)
pulse_ext_stream_new()
PulseExtStream * pulse_ext_stream_new (PulseConnection * connection, const pa_ext_stream_restore_info * info, PulseStream * parent)
Definition at line 241 of file pulse-ext-stream.c.
References _mate_mixer_app_info_free(), _mate_mixer_app_info_new(), _mate_mixer_app_info_set_id(), _mate_mixer_app_info_set_name(), connection, MATE_MIXER_DIRECTION_INPUT, MATE_MIXER_DIRECTION_OUTPUT, MATE_MIXER_DIRECTION_UNKNOWN, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_UNKNOWN, MATE_MIXER_STREAM_CONTROL_MOVABLE, MATE_MIXER_STREAM_CONTROL_MUTE_READABLE, MATE_MIXER_STREAM_CONTROL_MUTE_WRITABLE, MATE_MIXER_STREAM_CONTROL_ROLE_APPLICATION, MATE_MIXER_STREAM_CONTROL_ROLE_UNKNOWN, MATE_MIXER_STREAM_CONTROL_STORED, NULL, pulse_convert_media_role_name(), pulse_ext_stream_update(), PULSE_IS_CONNECTION, PULSE_TYPE_EXT_STREAM, and strchr.
pulse_ext_stream_update()
void pulse_ext_stream_update (PulseExtStream * ext, const pa_ext_stream_restore_info * info, PulseStream * parent)
Definition at line 331 of file pulse-ext-stream.c.
References _mate_mixer_stream_control_set_flags(), _mate_mixer_stream_control_set_mute(), _mate_mixer_stream_control_set_stream(), FALSE, MATE_MIXER_STREAM, MATE_MIXER_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_CAN_BALANCE, MATE_MIXER_STREAM_CONTROL_CAN_FADE, mate_mixer_stream_control_get_flags(), MATE_MIXER_STREAM_CONTROL_VOLUME_READABLE, MATE_MIXER_STREAM_CONTROL_VOLUME_WRITABLE, NULL, _PulseExtStream::priv, PULSE_IS_EXT_STREAM, and TRUE.
Referenced by pulse_ext_stream_new().