MATE Desktop Environment: pulse-stream-control.h File Reference
pulse-stream-control.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include <pulse/pulseaudio.h>
#include "pulse-types.h"
Classes
struct _PulseStreamControl
struct _PulseStreamControlClass
Macros
#define PULSE_TYPE_STREAM_CONTROL (pulse_stream_control_get_type ())
#define PULSE_STREAM_CONTROL(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_STREAM_CONTROL, PulseStreamControl))
#define PULSE_IS_STREAM_CONTROL(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_STREAM_CONTROL))
#define PULSE_STREAM_CONTROL_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_STREAM_CONTROL, PulseStreamControlClass))
#define PULSE_IS_STREAM_CONTROL_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_STREAM_CONTROL))
#define PULSE_STREAM_CONTROL_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_STREAM_CONTROL, PulseStreamControlClass))
Typedefs
typedef struct _PulseStreamControlClass PulseStreamControlClass
typedef struct _PulseStreamControlPrivate PulseStreamControlPrivate
Functions
GType pulse_stream_control_get_type (void)
guint32 pulse_stream_control_get_index (PulseStreamControl *control)
guint32 pulse_stream_control_get_stream_index (PulseStreamControl *control)
PulseConnection * pulse_stream_control_get_connection (PulseStreamControl *control)
PulseMonitor * pulse_stream_control_get_monitor (PulseStreamControl *control)
const pa_cvolume * pulse_stream_control_get_cvolume (PulseStreamControl *control)
const pa_channel_map * pulse_stream_control_get_channel_map (PulseStreamControl *control)
void pulse_stream_control_set_app_info (PulseStreamControl *stream, MateMixerAppInfo *info, gboolean take)
void pulse_stream_control_set_channel_map (PulseStreamControl *control, const pa_channel_map *map)
void pulse_stream_control_set_cvolume (PulseStreamControl *control, const pa_cvolume *cvolume, pa_volume_t base_volume)
Macro Definition Documentation
PULSE_IS_STREAM_CONTROL
#define PULSE_IS_STREAM_CONTROL (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_STREAM_CONTROL))
Definition at line 35 of file pulse-stream-control.h.
PULSE_IS_STREAM_CONTROL_CLASS
#define PULSE_IS_STREAM_CONTROL_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_STREAM_CONTROL))
Definition at line 39 of file pulse-stream-control.h.
PULSE_STREAM_CONTROL
#define PULSE_STREAM_CONTROL (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_STREAM_CONTROL, PulseStreamControl))
Definition at line 33 of file pulse-stream-control.h.
PULSE_STREAM_CONTROL_CLASS
#define PULSE_STREAM_CONTROL_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_STREAM_CONTROL, PulseStreamControlClass))
Definition at line 37 of file pulse-stream-control.h.
PULSE_STREAM_CONTROL_GET_CLASS
#define PULSE_STREAM_CONTROL_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_STREAM_CONTROL, PulseStreamControlClass))
Definition at line 41 of file pulse-stream-control.h.
PULSE_TYPE_STREAM_CONTROL
#define PULSE_TYPE_STREAM_CONTROL (pulse_stream_control_get_type ())
Definition at line 31 of file pulse-stream-control.h.
Typedef Documentation
PulseStreamControlClass
typedef struct _PulseStreamControlClass PulseStreamControlClass
Definition at line 44 of file pulse-stream-control.h.
PulseStreamControlPrivate
typedef struct _PulseStreamControlPrivate PulseStreamControlPrivate
Definition at line 45 of file pulse-stream-control.h.
Function Documentation
pulse_stream_control_get_channel_map()
const pa_channel_map * pulse_stream_control_get_channel_map (PulseStreamControl * control)
Definition at line 311 of file pulse-stream-control.c.
References NULL, _PulseStreamControl::priv, and PULSE_IS_STREAM_CONTROL.
pulse_stream_control_get_connection()
PulseConnection * pulse_stream_control_get_connection (PulseStreamControl * control)
Definition at line 287 of file pulse-stream-control.c.
References NULL, _PulseStreamControl::priv, and PULSE_IS_STREAM_CONTROL.
pulse_stream_control_get_cvolume()
const pa_cvolume * pulse_stream_control_get_cvolume (PulseStreamControl * control)
Definition at line 303 of file pulse-stream-control.c.
References NULL, _PulseStreamControl::priv, and PULSE_IS_STREAM_CONTROL.
pulse_stream_control_get_index()
guint32 pulse_stream_control_get_index (PulseStreamControl * control)
Definition at line 265 of file pulse-stream-control.c.
References _PulseStreamControl::priv, and PULSE_IS_STREAM_CONTROL.
pulse_stream_control_get_monitor()
PulseMonitor * pulse_stream_control_get_monitor (PulseStreamControl * control)
Definition at line 295 of file pulse-stream-control.c.
References NULL, _PulseStreamControl::priv, and PULSE_IS_STREAM_CONTROL.
pulse_stream_control_get_stream_index()
guint32 pulse_stream_control_get_stream_index (PulseStreamControl * control)
Definition at line 273 of file pulse-stream-control.c.
References MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_stream(), NULL, PULSE_IS_STREAM_CONTROL, PULSE_STREAM, and pulse_stream_get_index().
pulse_stream_control_get_type()
GType pulse_stream_control_get_type (void)
pulse_stream_control_set_app_info()
void pulse_stream_control_set_app_info (PulseStreamControl * stream, MateMixerAppInfo * info, gboolean take)
Definition at line 319 of file pulse-stream-control.c.
References _mate_mixer_app_info_copy(), _mate_mixer_app_info_free(), NULL, _PulseStreamControl::priv, PULSE_IS_STREAM_CONTROL, and TRUE.
Referenced by pulse_sink_input_new(), and pulse_source_output_new().
pulse_stream_control_set_channel_map()
void pulse_stream_control_set_channel_map (PulseStreamControl * control, const pa_channel_map * map)
Definition at line 335 of file pulse-stream-control.c.
References _mate_mixer_stream_control_set_flags(), MATE_MIXER_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_CAN_BALANCE, MATE_MIXER_STREAM_CONTROL_CAN_FADE, mate_mixer_stream_control_get_flags(), NULL, _PulseStreamControl::priv, and PULSE_IS_STREAM_CONTROL.
Referenced by pulse_sink_control_update(), pulse_sink_input_update(), pulse_source_control_update(), and pulse_source_output_update().
pulse_stream_control_set_cvolume()
void pulse_stream_control_set_cvolume (PulseStreamControl * control, const pa_cvolume * cvolume, pa_volume_t base_volume)
Definition at line 367 of file pulse-stream-control.c.
References _mate_mixer_stream_control_set_flags(), MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_flags(), MATE_MIXER_STREAM_CONTROL_HAS_DECIBEL, MATE_MIXER_STREAM_CONTROL_VOLUME_READABLE, MATE_MIXER_STREAM_CONTROL_VOLUME_WRITABLE, NULL, _PulseStreamControl::priv, and PULSE_IS_STREAM_CONTROL.
Referenced by pulse_sink_control_update(), pulse_sink_input_update(), pulse_source_control_update(), and pulse_source_output_update().