MATE Desktop Environment: pulse-sink-input.h File Reference
pulse-sink-input.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <pulse/pulseaudio.h>
#include "pulse-stream-control.h"
#include "pulse-types.h"
Classes
struct _PulseSinkInput
struct _PulseSinkInputClass
Macros
#define PULSE_TYPE_SINK_INPUT (pulse_sink_input_get_type ())
#define PULSE_SINK_INPUT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_SINK_INPUT, PulseSinkInput))
#define PULSE_IS_SINK_INPUT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_SINK_INPUT))
#define PULSE_SINK_INPUT_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_SINK_INPUT, PulseSinkInputClass))
#define PULSE_IS_SINK_INPUT_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_SINK_INPUT))
#define PULSE_SINK_INPUT_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_SINK_INPUT, PulseSinkInputClass))
Typedefs
typedef struct _PulseSinkInputClass PulseSinkInputClass
Functions
GType pulse_sink_input_get_type (void)
PulseSinkInput * pulse_sink_input_new (PulseConnection *connection, const pa_sink_input_info *info, PulseSink *sink)
void pulse_sink_input_update (PulseSinkInput *input, const pa_sink_input_info *info)
Macro Definition Documentation
PULSE_IS_SINK_INPUT
#define PULSE_IS_SINK_INPUT (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_SINK_INPUT))
Definition at line 35 of file pulse-sink-input.h.
PULSE_IS_SINK_INPUT_CLASS
#define PULSE_IS_SINK_INPUT_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_SINK_INPUT))
Definition at line 39 of file pulse-sink-input.h.
PULSE_SINK_INPUT
#define PULSE_SINK_INPUT (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_SINK_INPUT, PulseSinkInput))
Definition at line 33 of file pulse-sink-input.h.
PULSE_SINK_INPUT_CLASS
#define PULSE_SINK_INPUT_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_SINK_INPUT, PulseSinkInputClass))
Definition at line 37 of file pulse-sink-input.h.
PULSE_SINK_INPUT_GET_CLASS
#define PULSE_SINK_INPUT_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_SINK_INPUT, PulseSinkInputClass))
Definition at line 41 of file pulse-sink-input.h.
PULSE_TYPE_SINK_INPUT
#define PULSE_TYPE_SINK_INPUT (pulse_sink_input_get_type ())
Definition at line 31 of file pulse-sink-input.h.
Typedef Documentation
PulseSinkInputClass
typedef struct _PulseSinkInputClass PulseSinkInputClass
Definition at line 44 of file pulse-sink-input.h.
Function Documentation
pulse_sink_input_get_type()
GType pulse_sink_input_get_type (void)
pulse_sink_input_new()
PulseSinkInput * pulse_sink_input_new (PulseConnection * connection, const pa_sink_input_info * info, PulseSink * sink)
Definition at line 64 of file pulse-sink-input.c.
References _mate_mixer_app_info_new(), _mate_mixer_app_info_set_icon(), _mate_mixer_app_info_set_id(), _mate_mixer_app_info_set_name(), _mate_mixer_app_info_set_version(), connection, label, MATE_MIXER_STREAM_CONTROL_HAS_DECIBEL, MATE_MIXER_STREAM_CONTROL_HAS_MONITOR, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_EVENT, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_UNKNOWN, MATE_MIXER_STREAM_CONTROL_MUTE_READABLE, MATE_MIXER_STREAM_CONTROL_MUTE_WRITABLE, MATE_MIXER_STREAM_CONTROL_ROLE_APPLICATION, MATE_MIXER_STREAM_CONTROL_ROLE_UNKNOWN, MATE_MIXER_STREAM_CONTROL_VOLUME_READABLE, MATE_MIXER_STREAM_CONTROL_VOLUME_WRITABLE, name, NULL, pulse_convert_media_role_name(), PULSE_IS_CONNECTION, PULSE_IS_SINK, pulse_sink_input_update(), PULSE_STREAM_CONTROL, pulse_stream_control_set_app_info(), PULSE_TYPE_SINK_INPUT, and TRUE.
Referenced by pulse_sink_add_input().
pulse_sink_input_update()
void pulse_sink_input_update (PulseSinkInput * input, const pa_sink_input_info * info)
Definition at line 162 of file pulse-sink-input.c.
References _mate_mixer_stream_control_set_mute(), FALSE, MATE_MIXER_STREAM_CONTROL, NULL, PULSE_IS_SINK_INPUT, PULSE_STREAM_CONTROL, pulse_stream_control_set_channel_map(), pulse_stream_control_set_cvolume(), and TRUE.
Referenced by pulse_sink_add_input(), and pulse_sink_input_new().