MATE Desktop Environment: pulse-helpers.h File Reference
pulse-helpers.h File Reference
#include <glib.h>
#include <libmatemixer/matemixer.h>
#include <pulse/pulseaudio.h>
Functions
MateMixerStreamControlMediaRole pulse_convert_media_role_name (const gchar *name)
Variables
const MateMixerChannelPosition pulse_channel_map_from [PA_CHANNEL_POSITION_MAX]
const pa_channel_position_t pulse_channel_map_to [MATE_MIXER_CHANNEL_MAX]
Function Documentation
pulse_convert_media_role_name()
MateMixerStreamControlMediaRole pulse_convert_media_role_name (const gchar * name)
Definition at line 74 of file pulse-helpers.c.
References MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_A11Y, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_ABSTRACT, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_ANIMATION, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_EVENT, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_FILTER, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_GAME, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_MUSIC, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_PHONE, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_PRODUCTION, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_TEST, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_UNKNOWN, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_VIDEO, name, and NULL.
Referenced by pulse_ext_stream_new(), pulse_sink_input_new(), and pulse_source_output_new().
Variable Documentation
pulse_channel_map_from
const MateMixerChannelPosition pulse_channel_map_from[PA_CHANNEL_POSITION_MAX] extern
Definition at line 27 of file pulse-helpers.c.
pulse_channel_map_to
const pa_channel_position_t pulse_channel_map_to[MATE_MIXER_CHANNEL_MAX] extern
Definition at line 49 of file pulse-helpers.c.