MATE Desktop Environment: pulse-device-switch.h File Reference
pulse-device-switch.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include "pulse-types.h"
Classes
struct _PulseDeviceSwitch
struct _PulseDeviceSwitchClass
Macros
#define PULSE_TYPE_DEVICE_SWITCH (pulse_device_switch_get_type ())
#define PULSE_DEVICE_SWITCH(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_DEVICE_SWITCH, PulseDeviceSwitch))
#define PULSE_IS_DEVICE_SWITCH(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_DEVICE_SWITCH))
#define PULSE_DEVICE_SWITCH_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_DEVICE_SWITCH, PulseDeviceSwitchClass))
#define PULSE_IS_DEVICE_SWITCH_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_DEVICE_SWITCH))
#define PULSE_DEVICE_SWITCH_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_DEVICE_SWITCH, PulseDeviceSwitchClass))
Typedefs
typedef struct _PulseDeviceSwitchClass PulseDeviceSwitchClass
typedef struct _PulseDeviceSwitchPrivate PulseDeviceSwitchPrivate
Functions
GType pulse_device_switch_get_type (void)
PulseDeviceSwitch * pulse_device_switch_new (const gchar *name, const gchar *label, PulseDevice *device)
void pulse_device_switch_add_profile (PulseDeviceSwitch *swtch, PulseDeviceProfile *profile)
void pulse_device_switch_set_active_profile (PulseDeviceSwitch *swtch, PulseDeviceProfile *profile)
void pulse_device_switch_set_active_profile_by_name (PulseDeviceSwitch *swtch, const gchar *name)
Macro Definition Documentation
PULSE_DEVICE_SWITCH
#define PULSE_DEVICE_SWITCH (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_DEVICE_SWITCH, PulseDeviceSwitch))
Definition at line 31 of file pulse-device-switch.h.
PULSE_DEVICE_SWITCH_CLASS
#define PULSE_DEVICE_SWITCH_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_DEVICE_SWITCH, PulseDeviceSwitchClass))
Definition at line 35 of file pulse-device-switch.h.
PULSE_DEVICE_SWITCH_GET_CLASS
#define PULSE_DEVICE_SWITCH_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_DEVICE_SWITCH, PulseDeviceSwitchClass))
Definition at line 39 of file pulse-device-switch.h.
PULSE_IS_DEVICE_SWITCH
#define PULSE_IS_DEVICE_SWITCH (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_DEVICE_SWITCH))
Definition at line 33 of file pulse-device-switch.h.
PULSE_IS_DEVICE_SWITCH_CLASS
#define PULSE_IS_DEVICE_SWITCH_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_DEVICE_SWITCH))
Definition at line 37 of file pulse-device-switch.h.
PULSE_TYPE_DEVICE_SWITCH
#define PULSE_TYPE_DEVICE_SWITCH (pulse_device_switch_get_type ())
Definition at line 29 of file pulse-device-switch.h.
Typedef Documentation
PulseDeviceSwitchClass
typedef struct _PulseDeviceSwitchClass PulseDeviceSwitchClass
Definition at line 42 of file pulse-device-switch.h.
PulseDeviceSwitchPrivate
typedef struct _PulseDeviceSwitchPrivate PulseDeviceSwitchPrivate
Definition at line 43 of file pulse-device-switch.h.
Function Documentation
pulse_device_switch_add_profile()
void pulse_device_switch_add_profile (PulseDeviceSwitch * swtch, PulseDeviceProfile * profile)
Definition at line 99 of file pulse-device-switch.c.
References _PulseDeviceSwitch::priv, PULSE_IS_DEVICE_PROFILE, and PULSE_IS_DEVICE_SWITCH.
pulse_device_switch_get_type()
GType pulse_device_switch_get_type (void)
pulse_device_switch_new()
PulseDeviceSwitch * pulse_device_switch_new (const gchar * name, const gchar * label, PulseDevice * device)
Definition at line 84 of file pulse-device-switch.c.
References label, MATE_MIXER_DEVICE_SWITCH_ROLE_PROFILE, name, NULL, PULSE_IS_DEVICE, and PULSE_TYPE_DEVICE_SWITCH.
pulse_device_switch_set_active_profile()
void pulse_device_switch_set_active_profile (PulseDeviceSwitch * swtch, PulseDeviceProfile * profile)
Definition at line 110 of file pulse-device-switch.c.
References _mate_mixer_switch_set_active_option(), MATE_MIXER_SWITCH, MATE_MIXER_SWITCH_OPTION, PULSE_IS_DEVICE_PROFILE, and PULSE_IS_DEVICE_SWITCH.
Referenced by pulse_device_switch_set_active_profile_by_name().
pulse_device_switch_set_active_profile_by_name()
void pulse_device_switch_set_active_profile_by_name (PulseDeviceSwitch * swtch, const gchar * name)
Definition at line 121 of file pulse-device-switch.c.
References item, name, NULL, _PulseDeviceSwitch::priv, PULSE_DEVICE_PROFILE, pulse_device_switch_set_active_profile(), and PULSE_IS_DEVICE_SWITCH.
Referenced by pulse_device_update().