MATE Desktop Environment: pulse-source-control.h File Reference
pulse-source-control.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <pulse/pulseaudio.h>
#include "pulse-stream-control.h"
#include "pulse-types.h"
Classes
struct _PulseSourceControl
struct _PulseSourceControlClass
Macros
#define PULSE_TYPE_SOURCE_CONTROL (pulse_source_control_get_type ())
#define PULSE_SOURCE_CONTROL(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_SOURCE_CONTROL, PulseSourceControl))
#define PULSE_IS_SOURCE_CONTROL(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_SOURCE_CONTROL))
#define PULSE_SOURCE_CONTROL_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_SOURCE_CONTROL, PulseSourceControlClass))
#define PULSE_IS_SOURCE_CONTROL_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_SOURCE_CONTROL))
#define PULSE_SOURCE_CONTROL_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_SOURCE_CONTROL, PulseSourceControlClass))
Typedefs
typedef struct _PulseSourceControlClass PulseSourceControlClass
typedef struct _PulseSourceControlPrivate PulseSourceControlPrivate
Functions
GType pulse_source_control_get_type (void)
PulseSourceControl * pulse_source_control_new (PulseConnection *connection, const pa_source_info *info, PulseSource *source)
void pulse_source_control_update (PulseSourceControl *control, const pa_source_info *info)
Macro Definition Documentation
PULSE_IS_SOURCE_CONTROL
#define PULSE_IS_SOURCE_CONTROL (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_SOURCE_CONTROL))
Definition at line 35 of file pulse-source-control.h.
PULSE_IS_SOURCE_CONTROL_CLASS
#define PULSE_IS_SOURCE_CONTROL_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_SOURCE_CONTROL))
Definition at line 39 of file pulse-source-control.h.
PULSE_SOURCE_CONTROL
#define PULSE_SOURCE_CONTROL (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_SOURCE_CONTROL, PulseSourceControl))
Definition at line 33 of file pulse-source-control.h.
PULSE_SOURCE_CONTROL_CLASS
#define PULSE_SOURCE_CONTROL_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_SOURCE_CONTROL, PulseSourceControlClass))
Definition at line 37 of file pulse-source-control.h.
PULSE_SOURCE_CONTROL_GET_CLASS
#define PULSE_SOURCE_CONTROL_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_SOURCE_CONTROL, PulseSourceControlClass))
Definition at line 41 of file pulse-source-control.h.
PULSE_TYPE_SOURCE_CONTROL
#define PULSE_TYPE_SOURCE_CONTROL (pulse_source_control_get_type ())
Definition at line 31 of file pulse-source-control.h.
Typedef Documentation
PulseSourceControlClass
typedef struct _PulseSourceControlClass PulseSourceControlClass
Definition at line 44 of file pulse-source-control.h.
PulseSourceControlPrivate
typedef struct _PulseSourceControlPrivate PulseSourceControlPrivate
Definition at line 45 of file pulse-source-control.h.
Function Documentation
pulse_source_control_get_type()
GType pulse_source_control_get_type (void)
pulse_source_control_new()
PulseSourceControl * pulse_source_control_new (PulseConnection * connection, const pa_source_info * info, PulseSource * source)
Definition at line 56 of file pulse-source-control.c.
References connection, MATE_MIXER_STREAM_CONTROL_HAS_DECIBEL, MATE_MIXER_STREAM_CONTROL_HAS_MONITOR, MATE_MIXER_STREAM_CONTROL_MUTE_READABLE, MATE_MIXER_STREAM_CONTROL_MUTE_WRITABLE, MATE_MIXER_STREAM_CONTROL_ROLE_MASTER, MATE_MIXER_STREAM_CONTROL_ROLE_PORT, MATE_MIXER_STREAM_CONTROL_VOLUME_READABLE, MATE_MIXER_STREAM_CONTROL_VOLUME_WRITABLE, NULL, PULSE_IS_CONNECTION, PULSE_IS_SOURCE, pulse_source_control_update(), and PULSE_TYPE_SOURCE_CONTROL.
Referenced by pulse_source_new().
pulse_source_control_update()
void pulse_source_control_update (PulseSourceControl * control, const pa_source_info * info)
Definition at line 95 of file pulse-source-control.c.
References _mate_mixer_stream_control_set_mute(), FALSE, MATE_MIXER_STREAM_CONTROL, NULL, PULSE_IS_SOURCE_CONTROL, PULSE_STREAM_CONTROL, pulse_stream_control_set_channel_map(), pulse_stream_control_set_cvolume(), and TRUE.
Referenced by pulse_source_control_new(), and pulse_source_update().