MATE Desktop Environment: pulse-source-output.h File Reference
pulse-source-output.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <pulse/pulseaudio.h>
#include "pulse-stream-control.h"
#include "pulse-types.h"
Classes
struct _PulseSourceOutput
struct _PulseSourceOutputClass
Macros
#define PULSE_TYPE_SOURCE_OUTPUT (pulse_source_output_get_type ())
#define PULSE_SOURCE_OUTPUT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_SOURCE_OUTPUT, PulseSourceOutput))
#define PULSE_IS_SOURCE_OUTPUT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_SOURCE_OUTPUT))
#define PULSE_SOURCE_OUTPUT_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_SOURCE_OUTPUT, PulseSourceOutputClass))
#define PULSE_IS_SOURCE_OUTPUT_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_SOURCE_OUTPUT))
#define PULSE_SOURCE_OUTPUT_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_SOURCE_OUTPUT, PulseSourceOutputClass))
Typedefs
typedef struct _PulseSourceOutputClass PulseSourceOutputClass
Functions
GType pulse_source_output_get_type (void)
PulseSourceOutput * pulse_source_output_new (PulseConnection *connection, const pa_source_output_info *info, PulseSource *source)
void pulse_source_output_update (PulseSourceOutput *output, const pa_source_output_info *info)
Macro Definition Documentation
PULSE_IS_SOURCE_OUTPUT
#define PULSE_IS_SOURCE_OUTPUT (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_SOURCE_OUTPUT))
Definition at line 35 of file pulse-source-output.h.
PULSE_IS_SOURCE_OUTPUT_CLASS
#define PULSE_IS_SOURCE_OUTPUT_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_SOURCE_OUTPUT))
Definition at line 39 of file pulse-source-output.h.
PULSE_SOURCE_OUTPUT
#define PULSE_SOURCE_OUTPUT (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_SOURCE_OUTPUT, PulseSourceOutput))
Definition at line 33 of file pulse-source-output.h.
PULSE_SOURCE_OUTPUT_CLASS
#define PULSE_SOURCE_OUTPUT_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_SOURCE_OUTPUT, PulseSourceOutputClass))
Definition at line 37 of file pulse-source-output.h.
PULSE_SOURCE_OUTPUT_GET_CLASS
#define PULSE_SOURCE_OUTPUT_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_SOURCE_OUTPUT, PulseSourceOutputClass))
Definition at line 41 of file pulse-source-output.h.
PULSE_TYPE_SOURCE_OUTPUT
#define PULSE_TYPE_SOURCE_OUTPUT (pulse_source_output_get_type ())
Definition at line 31 of file pulse-source-output.h.
Typedef Documentation
PulseSourceOutputClass
typedef struct _PulseSourceOutputClass PulseSourceOutputClass
Definition at line 44 of file pulse-source-output.h.
Function Documentation
pulse_source_output_get_type()
GType pulse_source_output_get_type (void)
pulse_source_output_new()
PulseSourceOutput * pulse_source_output_new (PulseConnection * connection, const pa_source_output_info * info, PulseSource * source)
Definition at line 64 of file pulse-source-output.c.
References _mate_mixer_app_info_new(), _mate_mixer_app_info_set_icon(), _mate_mixer_app_info_set_id(), _mate_mixer_app_info_set_name(), _mate_mixer_app_info_set_version(), connection, MATE_MIXER_STREAM_CONTROL_HAS_DECIBEL, MATE_MIXER_STREAM_CONTROL_HAS_MONITOR, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_UNKNOWN, MATE_MIXER_STREAM_CONTROL_MUTE_READABLE, MATE_MIXER_STREAM_CONTROL_MUTE_WRITABLE, MATE_MIXER_STREAM_CONTROL_ROLE_APPLICATION, MATE_MIXER_STREAM_CONTROL_ROLE_UNKNOWN, MATE_MIXER_STREAM_CONTROL_VOLUME_READABLE, MATE_MIXER_STREAM_CONTROL_VOLUME_WRITABLE, name, NULL, pulse_convert_media_role_name(), PULSE_IS_CONNECTION, PULSE_IS_SOURCE, pulse_source_output_update(), PULSE_STREAM_CONTROL, pulse_stream_control_set_app_info(), PULSE_TYPE_SOURCE_OUTPUT, and TRUE.
Referenced by pulse_source_add_output().
pulse_source_output_update()
void pulse_source_output_update (PulseSourceOutput * output, const pa_source_output_info * info)
Definition at line 149 of file pulse-source-output.c.
References _mate_mixer_stream_control_set_mute(), FALSE, MATE_MIXER_STREAM_CONTROL, NULL, PULSE_IS_SOURCE_OUTPUT, PULSE_STREAM_CONTROL, pulse_stream_control_set_channel_map(), pulse_stream_control_set_cvolume(), and TRUE.
Referenced by pulse_source_add_output(), and pulse_source_output_new().