MATE Desktop Environment: pulse-port.h File Reference
pulse-port.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include "pulse-types.h"
Classes
struct _PulsePort
struct _PulsePortClass
Macros
#define PULSE_TYPE_PORT (pulse_port_get_type ())
#define PULSE_PORT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_PORT, PulsePort))
#define PULSE_IS_PORT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_PORT))
#define PULSE_PORT_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_PORT, PulsePortClass))
#define PULSE_IS_PORT_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_PORT))
#define PULSE_PORT_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_IS_PORT, PulsePortClass))
Typedefs
typedef struct _PulsePortClass PulsePortClass
typedef struct _PulsePortPrivate PulsePortPrivate
Functions
GType pulse_port_get_type (void)
PulsePort * pulse_port_new (const gchar *name, const gchar *label, const gchar *icon, guint priority)
const gchar * pulse_port_get_name (PulsePort *port)
guint pulse_port_get_priority (PulsePort *port)
Macro Definition Documentation
PULSE_IS_PORT
#define PULSE_IS_PORT (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_PORT))
Definition at line 33 of file pulse-port.h.
PULSE_IS_PORT_CLASS
#define PULSE_IS_PORT_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_PORT))
Definition at line 37 of file pulse-port.h.
PULSE_PORT
#define PULSE_PORT (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_PORT, PulsePort))
Definition at line 31 of file pulse-port.h.
PULSE_PORT_CLASS
#define PULSE_PORT_CLASS (k) (G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_PORT, PulsePortClass))
Definition at line 35 of file pulse-port.h.
PULSE_PORT_GET_CLASS
#define PULSE_PORT_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_IS_PORT, PulsePortClass))
Definition at line 39 of file pulse-port.h.
PULSE_TYPE_PORT
#define PULSE_TYPE_PORT (pulse_port_get_type ())
Definition at line 29 of file pulse-port.h.
Typedef Documentation
PulsePortClass
typedef struct _PulsePortClass PulsePortClass
Definition at line 42 of file pulse-port.h.
PulsePortPrivate
typedef struct _PulsePortPrivate PulsePortPrivate
Definition at line 43 of file pulse-port.h.
Function Documentation
pulse_port_get_name()
const gchar * pulse_port_get_name (PulsePort * port)
Definition at line 70 of file pulse-port.c.
References MATE_MIXER_SWITCH_OPTION, mate_mixer_switch_option_get_name(), NULL, and PULSE_IS_PORT.
pulse_port_get_priority()
guint pulse_port_get_priority (PulsePort * port)
Definition at line 78 of file pulse-port.c.
References _PulsePort::priv, and PULSE_IS_PORT.
pulse_port_get_type()
GType pulse_port_get_type (void)
pulse_port_new()
PulsePort * pulse_port_new (const gchar * name, const gchar * label, const gchar * icon, guint priority)
Definition at line 49 of file pulse-port.c.
References label, name, NULL, _PulsePort::priv, and PULSE_TYPE_PORT.
Referenced by pulse_sink_new(), and pulse_source_new().