MATE Desktop Environment: rar-utils.c File Reference
rar-utils.c File Reference
#include <config.h>
#include <string.h>
#include "file-utils.h"
#include "fr-command.h"
#include "gio-utils.h"
#include "rar-utils.h"
Enumerations
enum FirstVolumeExtension { FIRST_VOLUME_IS_000 , FIRST_VOLUME_IS_001 , FIRST_VOLUME_IS_RAR }
Functions
void rar_check_multi_volume (FrCommand *comm)
Enumeration Type Documentation
FirstVolumeExtension
enum FirstVolumeExtension
Enumerator
FIRST_VOLUME_IS_000
FIRST_VOLUME_IS_001
FIRST_VOLUME_IS_RAR
Definition at line 29 of file rar-utils.c.
Function Documentation
rar_check_multi_volume()
void rar_check_multi_volume (FrCommand * comm)
Definition at line 91 of file rar-utils.c.
References file_name_from_path(), _FrCommand::filename, FIRST_VOLUME_IS_001, FIRST_VOLUME_IS_RAR, fr_command_set_multi_volume(), g_load_file_in_buffer(), name, and NULL.