MATE Desktop Environment: resizepopup.c File Reference
resizepopup.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include "resizepopup.h"
#include "util.h"
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
Functions
MetaResizePopup * meta_ui_resize_popup_new (Display *display, int screen_number)
void meta_ui_resize_popup_free (MetaResizePopup *popup)
void meta_ui_resize_popup_set (MetaResizePopup *popup, MetaRectangle rect, int base_width, int base_height, int width_inc, int height_inc)
void meta_ui_resize_popup_set_showing (MetaResizePopup *popup, gboolean showing)
Function Documentation
meta_ui_resize_popup_free()
void meta_ui_resize_popup_free (MetaResizePopup * popup)
Definition at line 62 of file resizepopup.c.
References NULL.
Referenced by meta_display_end_grab_op().
meta_ui_resize_popup_new()
MetaResizePopup * meta_ui_resize_popup_new (Display * display, int screen_number)
Definition at line 48 of file resizepopup.c.
Referenced by meta_window_refresh_resize_popup().
meta_ui_resize_popup_set()
void meta_ui_resize_popup_set (MetaResizePopup * popup, MetaRectangle rect, int base_width, int base_height, int width_inc, int height_inc)
Definition at line 171 of file resizepopup.c.
References FALSE, _MetaRectangle::height, meta_rectangle_equal(), NULL, TRUE, and _MetaRectangle::width.
Referenced by meta_window_refresh_resize_popup().
meta_ui_resize_popup_set_showing()
void meta_ui_resize_popup_set_showing (MetaResizePopup * popup, gboolean showing)
Definition at line 212 of file resizepopup.c.
References NULL.
Referenced by meta_window_refresh_resize_popup().