MATE Desktop Environment: rfkill-glib.h File Reference
rfkill-glib.h File Reference
#include <glib-object.h>
#include <gio/gio.h>
#include "rfkill.h"
Classes
struct _CcRfkillGlib
struct _CcRfkillGlibClass
Macros
#define CC_RFKILL_TYPE_GLIB (cc_rfkill_glib_get_type())
#define CC_RFKILL_GLIB(obj)
#define CC_RFKILL_GLIB_CLASS(klass)
#define RFKILL_IS_GLIB(obj)
#define RFKILL_IS_GLIB_CLASS(klass)
#define RFKILL_GET_GLIB_CLASS(obj)
Typedefs
typedef struct CcRfkillGlibPrivate CcRfkillGlibPrivate
typedef struct _CcRfkillGlib CcRfkillGlib
typedef struct _CcRfkillGlibClass CcRfkillGlibClass
Functions
GType cc_rfkill_glib_get_type (void)
CcRfkillGlib * cc_rfkill_glib_new (void)
int cc_rfkill_glib_open (CcRfkillGlib *rfkill)
void cc_rfkill_glib_send_event (CcRfkillGlib *rfkill, struct rfkill_event *event, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean cc_rfkill_glib_send_event_finish (CcRfkillGlib *rfkill, GAsyncResult *res, GError **error)
void cc_rfkill_glib_send_change_all_event (CcRfkillGlib *rfkill, guint rfkill_type, gboolean enable, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean cc_rfkill_glib_send_change_all_event_finish (CcRfkillGlib *rfkill, GAsyncResult *res, GError **error)
Macro Definition Documentation
CC_RFKILL_GLIB
#define CC_RFKILL_GLIB (obj)
Value:
        (G_TYPE_CHECK_INSTANCE_CAST((obj), \
        CC_RFKILL_TYPE_GLIB, CcRfkillGlib))
Definition at line 35 of file rfkill-glib.h.
CC_RFKILL_GLIB_CLASS
#define CC_RFKILL_GLIB_CLASS (klass)
Value:
        (G_TYPE_CHECK_CLASS_CAST((klass), \
        CC_RFKILL_TYPE_GLIB, CcRfkillGlibClass))
Definition at line 37 of file rfkill-glib.h.
CC_RFKILL_TYPE_GLIB
#define CC_RFKILL_TYPE_GLIB (cc_rfkill_glib_get_type())
Definition at line 34 of file rfkill-glib.h.
RFKILL_GET_GLIB_CLASS
#define RFKILL_GET_GLIB_CLASS (obj)
Value:
        (G_TYPE_INSTANCE_GET_CLASS((obj), \
        CC_RFKILL_TYPE_GLIB, CcRfkillGlibClass))
Definition at line 43 of file rfkill-glib.h.
RFKILL_IS_GLIB
#define RFKILL_IS_GLIB (obj)
Value:
        (G_TYPE_CHECK_INSTANCE_TYPE((obj), \
        CC_RFKILL_TYPE_GLIB))
Definition at line 39 of file rfkill-glib.h.
RFKILL_IS_GLIB_CLASS
#define RFKILL_IS_GLIB_CLASS (klass)
Value:
        (G_TYPE_CHECK_CLASS_TYPE((klass), \
        CC_RFKILL_TYPE_GLIB))
Definition at line 41 of file rfkill-glib.h.
Typedef Documentation
CcRfkillGlib
typedef struct _CcRfkillGlib CcRfkillGlib
CcRfkillGlibClass
typedef struct _CcRfkillGlibClass CcRfkillGlibClass
CcRfkillGlibPrivate
typedef struct CcRfkillGlibPrivate CcRfkillGlibPrivate
Definition at line 46 of file rfkill-glib.h.
Function Documentation
cc_rfkill_glib_get_type()
GType cc_rfkill_glib_get_type (void)
cc_rfkill_glib_new()
CcRfkillGlib * cc_rfkill_glib_new (void)
Definition at line 519 of file rfkill-glib.c.
References CC_RFKILL_GLIB, CC_RFKILL_TYPE_GLIB, and NULL.
Referenced by msd_rfkill_manager_start().
cc_rfkill_glib_open()
int cc_rfkill_glib_open (CcRfkillGlib * rfkill)
Definition at line 395 of file rfkill-glib.c.
References rfkill_event::hard, rfkill_event::idx, NULL, rfkill_event::op, _CcRfkillGlib::priv, RFKILL_EVENT_SIZE_V1, RFKILL_IS_GLIB, RFKILL_OP_ADD, rfkill_event::soft, TRUE, and rfkill_event::type.
Referenced by msd_rfkill_manager_start().
cc_rfkill_glib_send_change_all_event()
void cc_rfkill_glib_send_change_all_event (CcRfkillGlib * rfkill, guint rfkill_type, gboolean enable, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 206 of file rfkill-glib.c.
References cc_rfkill_glib_send_change_all_event(), NULL, _CcRfkillGlib::priv, RFKILL_IS_GLIB, RFKILL_OP_CHANGE_ALL, and user_data.
Referenced by cc_rfkill_glib_send_change_all_event(), and cc_rfkill_glib_send_change_all_event_finish().
cc_rfkill_glib_send_change_all_event_finish()
gboolean cc_rfkill_glib_send_change_all_event_finish (CcRfkillGlib * rfkill, GAsyncResult * res, GError ** error)
Definition at line 120 of file rfkill-glib.c.
References cc_rfkill_glib_send_change_all_event(), error, FALSE, and RFKILL_IS_GLIB.
cc_rfkill_glib_send_event()
void cc_rfkill_glib_send_event (CcRfkillGlib * rfkill, struct rfkill_event * event, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 97 of file rfkill-glib.c.
References cc_rfkill_glib_send_event(), NULL, _CcRfkillGlib::priv, RFKILL_IS_GLIB, and user_data.
Referenced by cc_rfkill_glib_send_event(), and cc_rfkill_glib_send_event_finish().
cc_rfkill_glib_send_event_finish()
gboolean cc_rfkill_glib_send_event_finish (CcRfkillGlib * rfkill, GAsyncResult * res, GError ** error)
Definition at line 69 of file rfkill-glib.c.
References cc_rfkill_glib_send_event(), error, FALSE, and RFKILL_IS_GLIB.