MATE Desktop Environment: screen.h File Reference
screen.h File Reference
#include <X11/Xlib.h>
#include <glib.h>
#include "types.h"
Functions
int meta_screen_get_screen_number (MetaScreen *screen)
MetaDisplay * meta_screen_get_display (MetaScreen *screen)
Window meta_screen_get_xroot (MetaScreen *screen)
void meta_screen_get_size (MetaScreen *screen, int *width, int *height)
gpointer meta_screen_get_compositor_data (MetaScreen *screen)
void meta_screen_set_compositor_data (MetaScreen *screen, gpointer info)
MetaScreen * meta_screen_for_x_screen (Screen *xscreen)
Function Documentation
meta_screen_for_x_screen()
MetaScreen * meta_screen_for_x_screen (Screen * xscreen)
Definition at line 871 of file screen.c.
References meta_display_for_x_display(), meta_display_screen_for_x_screen(), and NULL.
Referenced by meta_core_get_active_workspace(), and meta_core_get_num_workspaces().
meta_screen_get_compositor_data()
gpointer meta_screen_get_compositor_data (MetaScreen * screen)
Definition at line 3261 of file screen.c.
References _MetaScreen::compositor_data.
meta_screen_get_display()
MetaDisplay * meta_screen_get_display (MetaScreen * screen)
Definition at line 3240 of file screen.c.
References _MetaScreen::display.
meta_screen_get_screen_number()
int meta_screen_get_screen_number (MetaScreen * screen)
Definition at line 3234 of file screen.c.
References _MetaScreen::number.
meta_screen_get_size()
void meta_screen_get_size (MetaScreen * screen, int * width, int * height)
Definition at line 3252 of file screen.c.
References _MetaRectangle::height, _MetaScreen::rect, and _MetaRectangle::width.
meta_screen_get_xroot()
Window meta_screen_get_xroot (MetaScreen * screen)
Definition at line 3246 of file screen.c.
References _MetaScreen::xroot.
meta_screen_set_compositor_data()
void meta_screen_set_compositor_data (MetaScreen * screen, gpointer info)
Definition at line 3267 of file screen.c.
References _MetaScreen::compositor_data.