MATE Desktop Environment: scrollarea.h File Reference
scrollarea.h File Reference
#include <cairo.h>
#include <gtk/gtk.h>
Classes
struct FooScrollAreaEvent
struct FooScrollArea
struct FooScrollAreaClass
Macros
#define FOO_TYPE_SCROLL_AREA (foo_scroll_area_get_type ())
#define FOO_SCROLL_AREA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FOO_TYPE_SCROLL_AREA, FooScrollArea))
#define FOO_SCROLL_AREA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FOO_TYPE_SCROLL_AREA, FooScrollAreaClass))
#define FOO_IS_SCROLL_AREA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FOO_TYPE_SCROLL_AREA))
#define FOO_IS_SCROLL_AREA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FOO_TYPE_SCROLL_AREA))
#define FOO_SCROLL_AREA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FOO_TYPE_SCROLL_AREA, FooScrollAreaClass))
Typedefs
typedef struct FooScrollArea FooScrollArea
typedef struct FooScrollAreaClass FooScrollAreaClass
typedef struct FooScrollAreaPrivate FooScrollAreaPrivate
typedef struct FooScrollAreaEvent FooScrollAreaEvent
typedef void(* FooScrollAreaEventFunc) (FooScrollArea *area, FooScrollAreaEvent *event, gpointer data)
Enumerations
enum FooScrollAreaEventType { FOO_BUTTON_PRESS , FOO_BUTTON_RELEASE , FOO_MOTION }
Functions
GType foo_scroll_area_get_type (void)
FooScrollArea * foo_scroll_area_new (void)
void foo_scroll_area_set_min_size (FooScrollArea *scroll_area, int min_width, int min_height)
void foo_scroll_area_set_size (FooScrollArea *scroll_area, int width, int height)
void foo_scroll_area_set_size_fixed_y (FooScrollArea *scroll_area, int width, int height, int old_y, int new_y)
void foo_scroll_area_set_viewport_pos (FooScrollArea *scroll_area, int x, int y)
void foo_scroll_area_get_viewport (FooScrollArea *scroll_area, GdkRectangle *viewport)
void foo_scroll_area_add_input_from_stroke (FooScrollArea *scroll_area, cairo_t *cr, FooScrollAreaEventFunc func, gpointer data)
void foo_scroll_area_add_input_from_fill (FooScrollArea *scroll_area, cairo_t *cr, FooScrollAreaEventFunc func, gpointer data)
void foo_scroll_area_invalidate_region (FooScrollArea *area, cairo_region_t *region)
void foo_scroll_area_invalidate (FooScrollArea *scroll_area)
void foo_scroll_area_invalidate_rect (FooScrollArea *scroll_area, int x, int y, int width, int height)
void foo_scroll_area_begin_grab (FooScrollArea *scroll_area, FooScrollAreaEventFunc func, gpointer input_data)
void foo_scroll_area_end_grab (FooScrollArea *scroll_area)
gboolean foo_scroll_area_is_grabbed (FooScrollArea *scroll_area)
void foo_scroll_area_begin_auto_scroll (FooScrollArea *scroll_area)
void foo_scroll_area_auto_scroll (FooScrollArea *scroll_area, FooScrollAreaEvent *event)
void foo_scroll_area_end_auto_scroll (FooScrollArea *scroll_area)
Macro Definition Documentation
FOO_IS_SCROLL_AREA
#define FOO_IS_SCROLL_AREA (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FOO_TYPE_SCROLL_AREA))
Definition at line 28 of file scrollarea.h.
FOO_IS_SCROLL_AREA_CLASS
#define FOO_IS_SCROLL_AREA_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FOO_TYPE_SCROLL_AREA))
Definition at line 29 of file scrollarea.h.
FOO_SCROLL_AREA
#define FOO_SCROLL_AREA (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FOO_TYPE_SCROLL_AREA, FooScrollArea))
Definition at line 26 of file scrollarea.h.
FOO_SCROLL_AREA_CLASS
#define FOO_SCROLL_AREA_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FOO_TYPE_SCROLL_AREA, FooScrollAreaClass))
Definition at line 27 of file scrollarea.h.
FOO_SCROLL_AREA_GET_CLASS
#define FOO_SCROLL_AREA_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FOO_TYPE_SCROLL_AREA, FooScrollAreaClass))
Definition at line 30 of file scrollarea.h.
FOO_TYPE_SCROLL_AREA
#define FOO_TYPE_SCROLL_AREA (foo_scroll_area_get_type ())
Definition at line 25 of file scrollarea.h.
Typedef Documentation
FooScrollArea
typedef struct FooScrollArea FooScrollArea
Definition at line 32 of file scrollarea.h.
FooScrollAreaClass
typedef struct FooScrollAreaClass FooScrollAreaClass
Definition at line 33 of file scrollarea.h.
FooScrollAreaEvent
typedef struct FooScrollAreaEvent FooScrollAreaEvent
Definition at line 35 of file scrollarea.h.
FooScrollAreaEventFunc
typedef void(* FooScrollAreaEventFunc) (FooScrollArea *area, FooScrollAreaEvent *event, gpointer data)
Definition at line 51 of file scrollarea.h.
FooScrollAreaPrivate
typedef struct FooScrollAreaPrivate FooScrollAreaPrivate
Definition at line 34 of file scrollarea.h.
Enumeration Type Documentation
FooScrollAreaEventType
enum FooScrollAreaEventType
Enumerator
FOO_BUTTON_PRESS
FOO_BUTTON_RELEASE
FOO_MOTION
Definition at line 37 of file scrollarea.h.
Function Documentation
foo_scroll_area_add_input_from_fill()
void foo_scroll_area_add_input_from_fill (FooScrollArea * scroll_area, cairo_t * cr, FooScrollAreaEventFunc func, gpointer data)
Definition at line 1212 of file scrollarea.c.
References data, FALSE, FOO_IS_SCROLL_AREA, NULL, and FooScrollArea::priv.
foo_scroll_area_add_input_from_stroke()
void foo_scroll_area_add_input_from_stroke (FooScrollArea * scroll_area, cairo_t * cr, FooScrollAreaEventFunc func, gpointer data)
Definition at line 1225 of file scrollarea.c.
References data, FOO_IS_SCROLL_AREA, NULL, FooScrollArea::priv, and TRUE.
foo_scroll_area_auto_scroll()
void foo_scroll_area_auto_scroll (FooScrollArea * scroll_area, FooScrollAreaEvent * event)
Definition at line 1444 of file scrollarea.c.
References MAX, MIN, FooScrollAreaEvent::x, and FooScrollAreaEvent::y.
foo_scroll_area_begin_auto_scroll()
void foo_scroll_area_begin_auto_scroll (FooScrollArea * scroll_area)
Definition at line 1488 of file scrollarea.c.
foo_scroll_area_begin_grab()
void foo_scroll_area_begin_grab (FooScrollArea * scroll_area, FooScrollAreaEventFunc func, gpointer input_data)
Definition at line 1319 of file scrollarea.c.
References FOO_IS_SCROLL_AREA, FooScrollArea::priv, and TRUE.
foo_scroll_area_end_auto_scroll()
void foo_scroll_area_end_auto_scroll (FooScrollArea * scroll_area)
Definition at line 1494 of file scrollarea.c.
foo_scroll_area_end_grab()
void foo_scroll_area_end_grab (FooScrollArea * scroll_area)
Definition at line 1335 of file scrollarea.c.
References FALSE, FOO_IS_SCROLL_AREA, NULL, and FooScrollArea::priv.
foo_scroll_area_get_type()
GType foo_scroll_area_get_type (void)
foo_scroll_area_get_viewport()
void foo_scroll_area_get_viewport (FooScrollArea * scroll_area, GdkRectangle * viewport)
Definition at line 518 of file scrollarea.c.
References FOO_IS_SCROLL_AREA.
foo_scroll_area_invalidate()
void foo_scroll_area_invalidate (FooScrollArea * scroll_area)
Definition at line 1238 of file scrollarea.c.
References foo_scroll_area_invalidate_rect(), and FooScrollArea::priv.
foo_scroll_area_invalidate_rect()
void foo_scroll_area_invalidate_rect (FooScrollArea * scroll_area, int x, int y, int width, int height)
Definition at line 1300 of file scrollarea.c.
References FOO_IS_SCROLL_AREA, and foo_scroll_area_invalidate_region().
Referenced by foo_scroll_area_invalidate().
foo_scroll_area_invalidate_region()
void foo_scroll_area_invalidate_region (FooScrollArea * area, cairo_region_t * region)
Definition at line 1277 of file scrollarea.c.
References FOO_IS_SCROLL_AREA, FooScrollArea::priv, and TRUE.
Referenced by foo_scroll_area_invalidate_rect().
foo_scroll_area_is_grabbed()
gboolean foo_scroll_area_is_grabbed (FooScrollArea * scroll_area)
Definition at line 1345 of file scrollarea.c.
References FooScrollArea::priv.
foo_scroll_area_new()
FooScrollArea * foo_scroll_area_new (void)
Definition at line 1152 of file scrollarea.c.
References FOO_TYPE_SCROLL_AREA, and NULL.
foo_scroll_area_set_min_size()
void foo_scroll_area_set_min_size (FooScrollArea * scroll_area, int min_width, int min_height)
Definition at line 1158 of file scrollarea.c.
References FooScrollArea::priv.
foo_scroll_area_set_size()
void foo_scroll_area_set_size (FooScrollArea * scroll_area, int width, int height)
Definition at line 945 of file scrollarea.c.
References FOO_IS_SCROLL_AREA, and FooScrollArea::priv.
foo_scroll_area_set_size_fixed_y()
void foo_scroll_area_set_size_fixed_y (FooScrollArea * scroll_area, int width, int height, int old_y, int new_y)
Definition at line 928 of file scrollarea.c.
References FooScrollArea::priv.
foo_scroll_area_set_viewport_pos()
void foo_scroll_area_set_viewport_pos (FooScrollArea * scroll_area, int x, int y)
Definition at line 1351 of file scrollarea.c.
References FooScrollArea::priv.