MATE Desktop Environment: sensors-applet-plugin.h File Reference
sensors-applet-plugin.h File Reference
#include <sensors-applet/sensors-applet-sensor.h>
Macros
#define SENSORS_APPLET_PLUGIN_ERROR (sensors_applet_plugin_error_quark())
Typedefs
typedef void SensorsAppletPluginTestSensorFunc(GList **sensors, const gchar *path)
Functions
GQuark sensors_applet_plugin_error_quark (void)
GList * sensors_applet_plugin_init (void)
gdouble sensors_applet_plugin_get_sensor_value (const gchar *path, const gchar *id, SensorType type, GError **error)
const gchar * sensors_applet_plugin_name (void)
void sensors_applet_plugin_find_sensors (GList **sensors, const gchar *path, SensorsAppletPluginTestSensorFunc)
void sensors_applet_plugin_default_sensor_limits (SensorType type, gdouble *low_value, gdouble *high_value)
void sensors_applet_plugin_add_sensor (GList **sensors, const gchar *path, const gchar *id, const gchar *label, SensorType type, gboolean enable, IconType icon, const gchar *graph_color)
void sensors_applet_plugin_add_sensor_with_limits (GList **sensors, const gchar *path, const gchar *id, const gchar *label, SensorType type, gboolean enable, gdouble low_value, gdouble high_value, IconType icon, const gchar *graph_color)
Macro Definition Documentation
SENSORS_APPLET_PLUGIN_ERROR
#define SENSORS_APPLET_PLUGIN_ERROR (sensors_applet_plugin_error_quark())
Definition at line 28 of file sensors-applet-plugin.h.
Typedef Documentation
SensorsAppletPluginTestSensorFunc
typedef void SensorsAppletPluginTestSensorFunc(GList **sensors, const gchar *path)
Definition at line 42 of file sensors-applet-plugin.h.
Function Documentation
sensors_applet_plugin_add_sensor()
void sensors_applet_plugin_add_sensor (GList ** sensors, const gchar * path, const gchar * id, const gchar * label, SensorType type, gboolean enable, IconType icon, const gchar * graph_color)
Definition at line 99 of file sensors-applet-plugin.c.
References label, sensors_applet_plugin_add_sensor_with_limits(), sensors_applet_plugin_default_sensor_limits(), and type.
sensors_applet_plugin_add_sensor_with_limits()
void sensors_applet_plugin_add_sensor_with_limits (GList ** sensors, const gchar * path, const gchar * id, const gchar * label, SensorType type, gboolean enable, gdouble low_value, gdouble high_value, IconType icon, const gchar * graph_color)
Definition at line 125 of file sensors-applet-plugin.c.
References _SensorsAppletSensorInfo::enable, _SensorsAppletSensorInfo::graph_color, _SensorsAppletSensorInfo::high_value, _SensorsAppletSensorInfo::icon, _SensorsAppletSensorInfo::id, label, _SensorsAppletSensorInfo::label, _SensorsAppletSensorInfo::low_value, _SensorsAppletSensorInfo::multiplier, _SensorsAppletSensorInfo::offset, _SensorsAppletSensorInfo::path, _SensorsAppletSensorInfo::type, and type.
Referenced by sensors_applet_plugin_add_sensor().
sensors_applet_plugin_default_sensor_limits()
void sensors_applet_plugin_default_sensor_limits (SensorType type, gdouble * low_value, gdouble * high_value)
Definition at line 80 of file sensors-applet-plugin.c.
References FAN_SENSOR, TEMP_SENSOR, and type.
Referenced by sensors_applet_plugin_add_sensor().
sensors_applet_plugin_error_quark()
GQuark sensors_applet_plugin_error_quark (void)
Definition at line 66 of file sensors-applet-plugin.c.
References plugin_name.
sensors_applet_plugin_find_sensors()
void sensors_applet_plugin_find_sensors (GList ** sensors, const gchar * path, SensorsAppletPluginTestSensorFunc test_sensor)
Definition at line 33 of file sensors-applet-plugin.c.
References NULL, and sensors_applet_plugin_find_sensors().
Referenced by sensors_applet_plugin_find_sensors().
sensors_applet_plugin_get_sensor_value()
gdouble sensors_applet_plugin_get_sensor_value (const gchar * path, const gchar * id, SensorType type, GError ** error)
Definition at line 120 of file acpi-plugin.c.
References error, and type.
sensors_applet_plugin_init()
GList * sensors_applet_plugin_init (void)
Initialises the plugin, and returns the list of SensorsAppletSensorInfo structs to create the sensors for this plugin from
Definition at line 115 of file acpi-plugin.c.
sensors_applet_plugin_name()
const gchar * sensors_applet_plugin_name (void)
Definition at line 110 of file acpi-plugin.c.
References plugin_name.