MATE Desktop Environment: shell-window.c File Reference
shell-window.c File Reference
#include "shell-window.h"
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
#include "app-resizer.h"
Functions
G_DEFINE_TYPE (ShellWindow, shell_window, GTK_TYPE_FRAME)
GtkWidget * shell_window_new (AppShellData *app_data)
void shell_window_clear_resize_handler (ShellWindow *win)
void shell_window_set_contents (ShellWindow *shell, GtkWidget *left_pane, GtkWidget *right_pane)
Function Documentation
G_DEFINE_TYPE()
G_DEFINE_TYPE (ShellWindow , shell_window , GTK_TYPE_FRAME)
shell_window_clear_resize_handler()
void shell_window_clear_resize_handler (ShellWindow * win)
Definition at line 58 of file shell-window.c.
References _ShellWindow::resize_handler_id.
Referenced by show_shell().
shell_window_new()
GtkWidget * shell_window_new (AppShellData * app_data)
Definition at line 44 of file shell-window.c.
References _ShellWindow::_hbox, NULL, SHELL_WINDOW_TYPE, and TRUE.
Referenced by layout_shell().
shell_window_set_contents()
void shell_window_set_contents (ShellWindow * shell, GtkWidget * left_pane, GtkWidget * right_pane)
Definition at line 68 of file shell-window.c.
References _ShellWindow::_hbox, _ShellWindow::_left_pane, _ShellWindow::_right_pane, FALSE, and TRUE.
Referenced by layout_shell().