MATE Desktop Environment: shell-window.h File Reference
shell-window.h File Reference
#include <glib.h>
#include <gtk/gtk.h>
#include "app-shell.h"
Classes
struct _ShellWindow
struct _ShellWindowClass
Macros
#define SHELL_WINDOW_TYPE (shell_window_get_type ())
#define SHELL_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELL_WINDOW_TYPE, ShellWindow))
#define SHELL_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELL_WINDOW_TYPE, ShellWindowClass))
#define IS_SHELL_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELL_WINDOW_TYPE))
#define IS_SHELL_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELL_WINDOW_TYPE))
#define SHELL_WINDOW_GET_CLASS(obj) (G_TYPE_CHECK_GET_CLASS ((obj), SHELL_WINDOW_TYPE, ShellWindowClass))
Typedefs
typedef struct _ShellWindow ShellWindow
typedef struct _ShellWindowClass ShellWindowClass
Functions
GType shell_window_get_type (void)
GtkWidget * shell_window_new (AppShellData *app_data)
void shell_window_set_contents (ShellWindow *window, GtkWidget *left_pane, GtkWidget *right_pane)
void shell_window_clear_resize_handler (ShellWindow *win)
Macro Definition Documentation
IS_SHELL_WINDOW
#define IS_SHELL_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SHELL_WINDOW_TYPE))
Definition at line 34 of file shell-window.h.
IS_SHELL_WINDOW_CLASS
#define IS_SHELL_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SHELL_WINDOW_TYPE))
Definition at line 35 of file shell-window.h.
SHELL_WINDOW
#define SHELL_WINDOW (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SHELL_WINDOW_TYPE, ShellWindow))
Definition at line 32 of file shell-window.h.
SHELL_WINDOW_CLASS
#define SHELL_WINDOW_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SHELL_WINDOW_TYPE, ShellWindowClass))
Definition at line 33 of file shell-window.h.
SHELL_WINDOW_GET_CLASS
#define SHELL_WINDOW_GET_CLASS (obj) (G_TYPE_CHECK_GET_CLASS ((obj), SHELL_WINDOW_TYPE, ShellWindowClass))
Definition at line 36 of file shell-window.h.
SHELL_WINDOW_TYPE
#define SHELL_WINDOW_TYPE (shell_window_get_type ())
Definition at line 31 of file shell-window.h.
Typedef Documentation
ShellWindow
typedef struct _ShellWindow ShellWindow
Definition at line 38 of file shell-window.h.
ShellWindowClass
typedef struct _ShellWindowClass ShellWindowClass
Definition at line 39 of file shell-window.h.
Function Documentation
shell_window_clear_resize_handler()
void shell_window_clear_resize_handler (ShellWindow * win)
Definition at line 58 of file shell-window.c.
References _ShellWindow::resize_handler_id.
Referenced by show_shell().
shell_window_get_type()
GType shell_window_get_type (void)
shell_window_new()
GtkWidget * shell_window_new (AppShellData * app_data)
Definition at line 44 of file shell-window.c.
References _ShellWindow::_hbox, NULL, SHELL_WINDOW_TYPE, and TRUE.
Referenced by layout_shell().
shell_window_set_contents()
void shell_window_set_contents (ShellWindow * window, GtkWidget * left_pane, GtkWidget * right_pane)
Definition at line 68 of file shell-window.c.
References _ShellWindow::_hbox, _ShellWindow::_left_pane, _ShellWindow::_right_pane, FALSE, and TRUE.
Referenced by layout_shell().