MATE Desktop Environment: showdesktop.c File Reference
showdesktop.c File Reference
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <gdk/gdkwayland.h>
#include "wncklet.h"
#include "showdesktop.h"
#include <string.h>
Macros
#define GDK_IS_X11_DISPLAY(object) !(G_TYPE_CHECK_INSTANCE_TYPE ((object), GDK_TYPE_WAYLAND_DISPLAY))
#define TIMEOUT_ACTIVATE_SECONDS 1
#define SHOW_DESKTOP_ICON "user-desktop"
Functions
gboolean show_desktop_applet_fill (MatePanelApplet *applet)
Macro Definition Documentation
GDK_IS_X11_DISPLAY
#define GDK_IS_X11_DISPLAY (object) !(G_TYPE_CHECK_INSTANCE_TYPE ((object), GDK_TYPE_WAYLAND_DISPLAY))
Definition at line 40 of file showdesktop.c.
SHOW_DESKTOP_ICON
#define SHOW_DESKTOP_ICON "user-desktop"
Definition at line 54 of file showdesktop.c.
TIMEOUT_ACTIVATE_SECONDS
#define TIMEOUT_ACTIVATE_SECONDS 1
Definition at line 53 of file showdesktop.c.
Function Documentation
show_desktop_applet_fill()
gboolean show_desktop_applet_fill (MatePanelApplet * applet)
Definition at line 428 of file showdesktop.c.
References _, GDK_IS_X11_DISPLAY, MATE_PANEL_APPLET_EXPAND_MINOR, mate_panel_applet_get_orient(), mate_panel_applet_get_size(), mate_panel_applet_set_flags(), mate_panel_applet_setup_menu_from_resource(), NULL, TRUE, and WNCKLET_RESOURCE_PATH.