MATE Desktop Environment: skeyutil.c File Reference
skeyutil.c File Reference
#include <config.h>
#include <ctype.h>
#include <glib.h>
#include "skeyutil.h"
Functions
void skey_sevenbit (char *s)
void skey_lowcase (char *s)
Function Documentation
skey_lowcase()
void skey_lowcase (char * s)
Definition at line 17 of file skeyutil.c.
Referenced by MD4Keycrunch(), MD5Keycrunch(), and SHA1Keycrunch().
skey_sevenbit()
void skey_sevenbit (char * s)
Definition at line 9 of file skeyutil.c.
Referenced by MD4Keycrunch(), MD5Keycrunch(), and SHA1Keycrunch().