MATE Desktop Environment: slab-mate-util.c File Reference
slab-mate-util.c File Reference
#include "slab-mate-util.h"
#include "libslab-utils.h"
#include <gio/gio.h>
#include <string.h>
Functions
MateDesktopItem * load_desktop_item_from_unknown (const gchar *id)
gboolean open_desktop_item_exec (MateDesktopItem *desktop_item)
gboolean open_desktop_item_help (MateDesktopItem *desktop_item)
void copy_file (const gchar *src_uri, const gchar *dst_uri)
Function Documentation
copy_file()
void copy_file (const gchar * src_uri, const gchar * dst_uri)
Definition at line 138 of file slab-mate-util.c.
References error, and NULL.
load_desktop_item_from_unknown()
MateDesktopItem * load_desktop_item_from_unknown (const gchar * id)
Definition at line 28 of file slab-mate-util.c.
References error, item, mate_desktop_item_new_from_basename(), mate_desktop_item_new_from_file(), mate_desktop_item_new_from_uri(), and NULL.
Referenced by application_tile_new_full().
open_desktop_item_exec()
gboolean open_desktop_item_exec (MateDesktopItem * desktop_item)
Definition at line 81 of file slab-mate-util.c.
References error, FALSE, mate_desktop_item_get_location(), mate_desktop_item_launch(), MATE_DESKTOP_ITEM_LAUNCH_DO_NOT_REAP_CHILD, MATE_DESKTOP_ITEM_LAUNCH_ONLY_ONE, NULL, and TRUE.
Referenced by handle_static_action_clicked().
open_desktop_item_help()
gboolean open_desktop_item_help (MateDesktopItem * desktop_item)
Definition at line 103 of file slab-mate-util.c.
References error, FALSE, mate_desktop_item_get_string(), NULL, and TRUE.