MATE Desktop Environment: stickynotes_applet_callbacks.h File Reference
stickynotes_applet_callbacks.h File Reference
#include <stickynotes_applet.h>
Functions
gboolean applet_button_cb (GtkWidget *widget, GdkEventButton *event, StickyNotesApplet *applet)
gboolean applet_key_cb (GtkWidget *widget, GdkEventKey *event, StickyNotesApplet *applet)
gboolean applet_cross_cb (GtkWidget *widget, GdkEventCrossing *event, StickyNotesApplet *applet)
gboolean applet_focus_cb (GtkWidget *widget, GdkEventFocus *event, StickyNotesApplet *applet)
void install_check_click_on_desktop (GdkScreen *screen)
void applet_change_orient_cb (MatePanelApplet *mate_panel_applet, MatePanelAppletOrient orient, StickyNotesApplet *applet)
void applet_size_allocate_cb (GtkWidget *widget, GtkAllocation *allocation, StickyNotesApplet *applet)
void applet_destroy_cb (MatePanelApplet *mate_panel_applet, StickyNotesApplet *applet)
void menu_create_cb (GtkAction *action, StickyNotesApplet *applet)
void menu_new_note_cb (GtkAction *action, StickyNotesApplet *applet)
void menu_hide_notes_cb (GtkAction *action, StickyNotesApplet *applet)
void menu_destroy_all_cb (GtkAction *action, StickyNotesApplet *applet)
void menu_toggle_lock_cb (GtkAction *action, StickyNotesApplet *applet)
void menu_preferences_cb (GtkAction *action, StickyNotesApplet *applet)
void menu_help_cb (GtkAction *action, StickyNotesApplet *applet)
void menu_about_cb (GtkAction *action, StickyNotesApplet *applet)
void preferences_save_cb (gpointer data)
void preferences_color_cb (GtkWidget *button, gpointer data)
void preferences_font_cb (GtkWidget *button, gpointer data)
void preferences_apply_cb (GSettings *settings, gchar *key, gpointer data)
void preferences_response_cb (GtkWidget *dialog, gint response, gpointer data)
gboolean preferences_delete_cb (GtkWidget *widget, GdkEvent *event, gpointer data)
Function Documentation
applet_button_cb()
gboolean applet_button_cb (GtkWidget * widget, GdkEventButton * event, StickyNotesApplet * applet)
Definition at line 62 of file stickynotes_applet_callbacks.c.
References FALSE, NULL, and TRUE.
Referenced by stickynotes_applet_new().
applet_change_orient_cb()
void applet_change_orient_cb (MatePanelApplet * mate_panel_applet, MatePanelAppletOrient orient, StickyNotesApplet * applet)
Definition at line 247 of file stickynotes_applet_callbacks.c.
References StickyNotesApplet::panel_orient.
Referenced by stickynotes_applet_new().
applet_cross_cb()
gboolean applet_cross_cb (GtkWidget * widget, GdkEventCrossing * event, StickyNotesApplet * applet)
Definition at line 97 of file stickynotes_applet_callbacks.c.
References FALSE, StickyNotesApplet::prelighted, and stickynotes_applet_update_icon().
Referenced by stickynotes_applet_new().
applet_destroy_cb()
void applet_destroy_cb (MatePanelApplet * mate_panel_applet, StickyNotesApplet * applet)
Definition at line 278 of file stickynotes_applet_callbacks.c.
References StickyNotesApplet::action_group, StickyNotes::applets, StickyNotesApplet::destroy_all_dialog, StickyNotes::notes, NULL, stickynote_free(), stickynotes, and stickynotes_save_now().
Referenced by stickynotes_applet_new().
applet_focus_cb()
gboolean applet_focus_cb (GtkWidget * widget, GdkEventFocus * event, StickyNotesApplet * applet)
Definition at line 111 of file stickynotes_applet_callbacks.c.
References FALSE, and stickynotes_applet_update_icon().
Referenced by stickynotes_applet_new().
applet_key_cb()
gboolean applet_key_cb (GtkWidget * widget, GdkEventKey * event, StickyNotesApplet * applet)
Definition at line 80 of file stickynotes_applet_callbacks.c.
References FALSE, and TRUE.
Referenced by stickynotes_applet_new().
applet_size_allocate_cb()
void applet_size_allocate_cb (GtkWidget * widget, GtkAllocation * allocation, StickyNotesApplet * applet)
Definition at line 256 of file stickynotes_applet_callbacks.c.
References StickyNotesApplet::panel_orient, StickyNotesApplet::panel_size, and stickynotes_applet_update_icon().
Referenced by stickynotes_applet_new().
install_check_click_on_desktop()
void install_check_click_on_desktop (GdkScreen * screen)
Definition at line 177 of file stickynotes_applet_callbacks.c.
References data, GDK_IS_X11_DISPLAY, and NULL.
Referenced by stickynotes_applet_init().
menu_about_cb()
void menu_about_cb (GtkAction * action, StickyNotesApplet * applet)
Definition at line 433 of file stickynotes_applet_callbacks.c.
References _, N_, and NULL.
menu_create_cb()
void menu_create_cb (GtkAction * action, StickyNotesApplet * applet)
menu_destroy_all_cb()
void menu_destroy_all_cb (GtkAction * action, StickyNotesApplet * applet)
Definition at line 344 of file stickynotes_applet_callbacks.c.
References StickyNotesApplet::destroy_all_dialog, NULL, and StickyNotesApplet::w_applet.
menu_help_cb()
void menu_help_cb (GtkAction * action, StickyNotesApplet * applet)
Definition at line 401 of file stickynotes_applet_callbacks.c.
References _, error, FALSE, NULL, and StickyNotesApplet::w_applet.
menu_hide_notes_cb()
void menu_hide_notes_cb (GtkAction * action, StickyNotesApplet * applet)
Definition at line 336 of file stickynotes_applet_callbacks.c.
References FALSE.
menu_new_note_cb()
void menu_new_note_cb (GtkAction * action, StickyNotesApplet * applet)
Definition at line 328 of file stickynotes_applet_callbacks.c.
References NULL.
menu_preferences_cb()
void menu_preferences_cb (GtkAction * action, StickyNotesApplet * applet)
Definition at line 390 of file stickynotes_applet_callbacks.c.
References stickynotes, stickynotes_applet_update_prefs(), StickyNotesApplet::w_applet, and StickyNotes::w_prefs.
menu_toggle_lock_cb()
void menu_toggle_lock_cb (GtkAction * action, StickyNotesApplet * applet)
Definition at line 379 of file stickynotes_applet_callbacks.c.
References action, StickyNotes::settings, and stickynotes.
preferences_apply_cb()
void preferences_apply_cb (GSettings * settings, gchar * key, gpointer data)
Definition at line 568 of file stickynotes_applet_callbacks.c.
References StickyNote::color, FALSE, StickyNote::font, StickyNote::font_color, key, StickyNotes::notes, stickynote_set_color(), stickynote_set_font(), stickynote_set_locked(), stickynotes, stickynotes_applet_update_menus(), stickynotes_applet_update_prefs(), stickynotes_save(), and StickyNote::w_window.
Referenced by stickynotes_applet_init().
preferences_color_cb()
void preferences_color_cb (GtkWidget * button, gpointer data)
Definition at line 527 of file stickynotes_applet_callbacks.c.
References StickyNotes::settings, stickynotes, StickyNotes::w_prefs_color, and StickyNotes::w_prefs_font_color.
Referenced by stickynotes_applet_init_prefs().
preferences_delete_cb()
gboolean preferences_delete_cb (GtkWidget * widget, GdkEvent * event, gpointer data)
Definition at line 672 of file stickynotes_applet_callbacks.c.
References TRUE.
Referenced by stickynotes_applet_init_prefs().
preferences_font_cb()
void preferences_font_cb (GtkWidget * button, gpointer data)
Definition at line 555 of file stickynotes_applet_callbacks.c.
References StickyNotes::settings, and stickynotes.
Referenced by stickynotes_applet_init_prefs().
preferences_response_cb()
void preferences_response_cb (GtkWidget * dialog, gint response, gpointer data)
Definition at line 635 of file stickynotes_applet_callbacks.c.
References _, error, FALSE, and NULL.
Referenced by stickynotes_applet_init_prefs().
preferences_save_cb()
void preferences_save_cb (gpointer data)
Definition at line 472 of file stickynotes_applet_callbacks.c.
References StickyNotes::settings, stickynotes, StickyNotes::w_prefs_desktop, StickyNotes::w_prefs_force, StickyNotes::w_prefs_height, StickyNotes::w_prefs_sticky, StickyNotes::w_prefs_sys_color, StickyNotes::w_prefs_sys_font, and StickyNotes::w_prefs_width.
Referenced by stickynotes_applet_init_prefs().