MATE Desktop Environment: stickynotes_applet.h File Reference
stickynotes_applet.h File Reference
#include <glib/gi18n.h>
#include <gdk/gdk.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <mate-panel-applet.h>
Classes
struct StickyNotes
struct StickyNotesApplet
Macros
#define STICKYNOTES_SCHEMA "org.mate.stickynotes"
#define STICKYNOTES_STOCK_LOCKED "stickynotes-stock-locked"
#define STICKYNOTES_STOCK_UNLOCKED "stickynotes-stock-unlocked"
#define STICKYNOTES_STOCK_CLOSE "stickynotes-stock-close"
#define STICKYNOTES_STOCK_RESIZE_SE "stickynotes-stock-resize-se"
#define STICKYNOTES_STOCK_RESIZE_SW "stickynotes-stock-resize-sw"
Enumerations
enum StickyNotesDefaultAction { STICKYNOTES_NEW = 0 , STICKYNOTES_SET_VISIBLE , STICKYNOTES_SET_LOCKED }
Functions
void stickynotes_applet_init (MatePanelApplet *mate_panel_applet)
void stickynotes_applet_init_prefs (void)
StickyNotesApplet * stickynotes_applet_new (MatePanelApplet *mate_panel_applet)
void stickynotes_applet_update_icon (StickyNotesApplet *applet)
void stickynotes_applet_update_prefs (void)
void stickynotes_applet_update_menus (void)
void stickynotes_applet_update_tooltips (void)
void stickynotes_applet_do_default_action (GdkScreen *screen)
void stickynotes_applet_panel_icon_get_geometry (int *x, int *y, int *width, int *height)
Variables
StickyNotes * stickynotes
Macro Definition Documentation
STICKYNOTES_SCHEMA
#define STICKYNOTES_SCHEMA "org.mate.stickynotes"
Definition at line 29 of file stickynotes_applet.h.
STICKYNOTES_STOCK_CLOSE
#define STICKYNOTES_STOCK_CLOSE "stickynotes-stock-close"
Definition at line 33 of file stickynotes_applet.h.
STICKYNOTES_STOCK_LOCKED
#define STICKYNOTES_STOCK_LOCKED "stickynotes-stock-locked"
Definition at line 31 of file stickynotes_applet.h.
STICKYNOTES_STOCK_RESIZE_SE
#define STICKYNOTES_STOCK_RESIZE_SE "stickynotes-stock-resize-se"
Definition at line 34 of file stickynotes_applet.h.
STICKYNOTES_STOCK_RESIZE_SW
#define STICKYNOTES_STOCK_RESIZE_SW "stickynotes-stock-resize-sw"
Definition at line 35 of file stickynotes_applet.h.
STICKYNOTES_STOCK_UNLOCKED
#define STICKYNOTES_STOCK_UNLOCKED "stickynotes-stock-unlocked"
Definition at line 32 of file stickynotes_applet.h.
Enumeration Type Documentation
StickyNotesDefaultAction
enum StickyNotesDefaultAction
Enumerator
STICKYNOTES_NEW
STICKYNOTES_SET_VISIBLE
STICKYNOTES_SET_LOCKED
Definition at line 85 of file stickynotes_applet.h.
Function Documentation
stickynotes_applet_do_default_action()
void stickynotes_applet_do_default_action (GdkScreen * screen)
stickynotes_applet_init()
void stickynotes_applet_init (MatePanelApplet * mate_panel_applet)
Definition at line 165 of file stickynotes_applet.c.
References _, StickyNotes::applets, GDK_IS_X11_DISPLAY, StickyNotes::icon_normal, StickyNotes::icon_prelight, install_check_click_on_desktop(), int(), StickyNotes::last_timeout_data, mate_panel_applet_get_size(), StickyNotes::max_height, StickyNotes::notes, NULL, preferences_apply_cb(), StickyNotes::settings, stickynotes, stickynotes_applet_init_prefs(), stickynotes_load(), STICKYNOTES_SCHEMA, TRUE, and StickyNotes::visible.
stickynotes_applet_init_prefs()
void stickynotes_applet_init_prefs (void)
Definition at line 243 of file stickynotes_applet.c.
References StickyNotes::builder, FALSE, NULL, preferences_color_cb(), preferences_delete_cb(), preferences_font_cb(), preferences_response_cb(), preferences_save_cb(), StickyNotes::settings, stickynotes, stickynotes_applet_update_prefs(), StickyNotes::w_prefs, StickyNotes::w_prefs_color, StickyNotes::w_prefs_desktop, StickyNotes::w_prefs_font, StickyNotes::w_prefs_font_color, StickyNotes::w_prefs_force, StickyNotes::w_prefs_height, StickyNotes::w_prefs_sticky, StickyNotes::w_prefs_sys_color, StickyNotes::w_prefs_sys_font, and StickyNotes::w_prefs_width.
Referenced by stickynotes_applet_init().
stickynotes_applet_new()
StickyNotesApplet * stickynotes_applet_new (MatePanelApplet * mate_panel_applet)
Definition at line 376 of file stickynotes_applet.c.
References _, action, StickyNotesApplet::action_group, applet_button_cb(), applet_change_orient_cb(), applet_cross_cb(), applet_destroy_cb(), applet_focus_cb(), applet_key_cb(), applet_size_allocate_cb(), StickyNotesApplet::destroy_all_dialog, FALSE, MATE_PANEL_APPLET_EXPAND_MINOR, mate_panel_applet_get_locked_down(), mate_panel_applet_get_orient(), mate_panel_applet_get_size(), mate_panel_applet_set_flags(), mate_panel_applet_setup_menu_from_resource(), StickyNotesApplet::menu_tip, NULL, StickyNotesApplet::panel_orient, StickyNotesApplet::panel_size, StickyNotesApplet::prelighted, stickynotes_applet_update_icon(), StickyNotesApplet::w_applet, and StickyNotesApplet::w_image.
stickynotes_applet_panel_icon_get_geometry()
void stickynotes_applet_panel_icon_get_geometry (int * x, int * y, int * width, int * height)
Definition at line 654 of file stickynotes_applet.c.
References StickyNotes::applets, NULL, stickynotes, and StickyNotesApplet::w_image.
Referenced by stickynote_set_visible().
stickynotes_applet_update_icon()
void stickynotes_applet_update_icon (StickyNotesApplet * applet)
Definition at line 458 of file stickynotes_applet.c.
References StickyNotes::icon_normal, StickyNotes::icon_prelight, StickyNotesApplet::panel_size, StickyNotesApplet::prelighted, stickynotes, and StickyNotesApplet::w_image.
Referenced by applet_cross_cb(), applet_focus_cb(), applet_size_allocate_cb(), and stickynotes_applet_new().
stickynotes_applet_update_menus()
void stickynotes_applet_update_menus (void)
Definition at line 579 of file stickynotes_applet.c.
References action, StickyNotesApplet::action_group, StickyNotes::applets, FALSE, StickyNote::locked, StickyNotes::notes, NULL, StickyNotes::settings, stickynotes, and TRUE.
Referenced by preferences_apply_cb(), and stickynote_set_locked().
stickynotes_applet_update_prefs()
void stickynotes_applet_update_prefs (void)
Definition at line 489 of file stickynotes_applet.c.
References StickyNotes::builder, MAX, StickyNotes::settings, stickynotes, StickyNotes::w_prefs_color, StickyNotes::w_prefs_desktop, StickyNotes::w_prefs_font, StickyNotes::w_prefs_font_color, StickyNotes::w_prefs_force, StickyNotes::w_prefs_height, StickyNotes::w_prefs_sticky, StickyNotes::w_prefs_sys_color, StickyNotes::w_prefs_sys_font, and StickyNotes::w_prefs_width.
Referenced by menu_preferences_cb(), preferences_apply_cb(), and stickynotes_applet_init_prefs().
stickynotes_applet_update_tooltips()
void stickynotes_applet_update_tooltips (void)
Definition at line 620 of file stickynotes_applet.c.
References _, StickyNotes::applets, StickyNotesApplet::menu_tip, StickyNotes::notes, stickynotes, and StickyNotesApplet::w_applet.
Referenced by stickynotes_add(), and stickynotes_remove().
Variable Documentation
stickynotes
StickyNotes* stickynotes extern
Definition at line 29 of file stickynotes_applet.c.
Referenced by applet_destroy_cb(), menu_preferences_cb(), menu_toggle_lock_cb(), preferences_apply_cb(), preferences_color_cb(), preferences_font_cb(), preferences_save_cb(), stickynote_change_properties(), stickynote_set_color(), stickynote_set_font(), stickynote_set_title(), stickynote_set_visible(), stickynotes_add(), stickynotes_applet_init(), stickynotes_applet_init_prefs(), stickynotes_applet_panel_icon_get_geometry(), stickynotes_applet_update_icon(), stickynotes_applet_update_menus(), stickynotes_applet_update_prefs(), stickynotes_applet_update_tooltips(), stickynotes_load(), stickynotes_remove(), and stickynotes_save_now().