MATE Desktop Environment: stickynotes.c File Reference
stickynotes.c File Reference
#include <config.h>
#include <libxml/parser.h>
#include <X11/Xatom.h>
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
#include <libwnck/libwnck.h>
#include <string.h>
#include <sys/stat.h>
#include "stickynotes.h"
#include "stickynotes_callbacks.h"
#include "util.h"
#include "stickynotes_applet.h"
Macros
#define WNCK_I_KNOW_THIS_IS_UNSTABLE 1
#define XML_CHAR(str) ((xmlChar *) (str))
#define STICKYNOTES_ICON_SIZE 8
Functions
StickyNote * stickynote_new (GdkScreen *screen)
void stickynote_free (StickyNote *note)
void stickynote_change_properties (StickyNote *note)
gboolean stickynote_get_empty (const StickyNote *note)
void stickynote_set_title (StickyNote *note, const gchar *title)
void stickynote_set_color (StickyNote *note, const gchar *color_str, const gchar *font_color_str, gboolean save)
void stickynote_set_font (StickyNote *note, const gchar *font_str, gboolean save)
void stickynote_set_locked (StickyNote *note, gboolean locked)
void stickynote_set_visible (StickyNote *note, gboolean visible)
void stickynotes_add (GdkScreen *screen)
void stickynotes_remove (StickyNote *note)
gboolean stickynotes_save_now (void)
void stickynotes_save (void)
void stickynotes_load (GdkScreen *screen)
Macro Definition Documentation
STICKYNOTES_ICON_SIZE
#define STICKYNOTES_ICON_SIZE 8
Definition at line 37 of file stickynotes.c.
WNCK_I_KNOW_THIS_IS_UNSTABLE
#define WNCK_I_KNOW_THIS_IS_UNSTABLE 1
Definition at line 25 of file stickynotes.c.
XML_CHAR
#define XML_CHAR (str) ((xmlChar *) (str))
Definition at line 36 of file stickynotes.c.
Function Documentation
stickynote_change_properties()
void stickynote_change_properties (StickyNote * note)
Definition at line 413 of file stickynotes.c.
References StickyNote::color, StickyNote::font, StickyNote::font_color, NULL, StickyNotes::settings, stickynotes, stickynotes_save(), StickyNote::w_color, StickyNote::w_def_color, StickyNote::w_def_font, StickyNote::w_entry, StickyNote::w_font, StickyNote::w_font_color, StickyNote::w_properties, and StickyNote::w_title.
Referenced by popup_properties_cb(), and stickynote_move_cb().
stickynote_free()
void stickynote_free (StickyNote * note)
Definition at line 399 of file stickynotes.c.
References StickyNote::color, StickyNote::font, StickyNote::font_color, StickyNote::w_menu, StickyNote::w_properties, and StickyNote::w_window.
Referenced by applet_destroy_cb(), and stickynotes_remove().
stickynote_get_empty()
gboolean stickynote_get_empty (const StickyNote * note)
Definition at line 479 of file stickynotes.c.
References StickyNote::w_body.
Referenced by stickynotes_remove().
stickynote_new()
StickyNote * stickynote_new (GdkScreen * screen)
Definition at line 393 of file stickynotes.c.
Referenced by stickynotes_add().
stickynote_set_color()
void stickynote_set_color (StickyNote * note, const gchar * color_str, const gchar * font_color_str, gboolean save)
Definition at line 517 of file stickynotes.c.
References StickyNote::color, StickyNote::font_color, NULL, StickyNotes::settings, stickynotes, StickyNote::w_body, StickyNote::w_close, StickyNote::w_color, StickyNote::w_color_label, StickyNote::w_font_color, StickyNote::w_font_color_label, StickyNote::w_lock, StickyNote::w_resize_se, StickyNote::w_resize_sw, and StickyNote::w_window.
Referenced by preferences_apply_cb(), properties_apply_color_cb(), and stickynotes_load().
stickynote_set_font()
void stickynote_set_font (StickyNote * note, const gchar * font_str, gboolean save)
Definition at line 648 of file stickynotes.c.
References StickyNote::font, NULL, StickyNotes::settings, stickynotes, StickyNote::w_body, StickyNote::w_font, StickyNote::w_font_label, and StickyNote::w_window.
Referenced by preferences_apply_cb(), properties_apply_font_cb(), properties_font_cb(), and stickynotes_load().
stickynote_set_locked()
void stickynote_set_locked (StickyNote * note, gboolean locked)
Definition at line 692 of file stickynotes.c.
References _, StickyNote::img_lock, StickyNote::locked, stickynotes_applet_update_menus(), STICKYNOTES_ICON_SIZE, STICKYNOTES_STOCK_LOCKED, STICKYNOTES_STOCK_UNLOCKED, StickyNote::w_body, StickyNote::w_lock, and StickyNote::w_lock_toggle_item.
Referenced by popup_toggle_lock_cb(), preferences_apply_cb(), stickynote_toggle_lock_cb(), and stickynotes_load().
stickynote_set_title()
void stickynote_set_title (StickyNote * note, const gchar * title)
Definition at line 486 of file stickynotes.c.
References StickyNotes::settings, stickynotes, StickyNote::w_title, and StickyNote::w_window.
Referenced by properties_apply_title_cb(), and stickynotes_load().
stickynote_set_visible()
void stickynote_set_visible (StickyNote * note, gboolean visible)
Definition at line 729 of file stickynotes.c.
References GDK_IS_X11_DISPLAY, StickyNotes::settings, stickynotes, stickynotes_applet_panel_icon_get_geometry(), StickyNote::w_window, StickyNote::workspace, StickyNote::x, xstuff_change_workspace(), and StickyNote::y.
Referenced by stickynotes_add(), and stickynotes_load().
stickynotes_add()
void stickynotes_add (GdkScreen * screen)
Definition at line 768 of file stickynotes.c.
References StickyNotes::notes, stickynote_new(), stickynote_set_visible(), stickynotes, stickynotes_applet_update_tooltips(), stickynotes_save(), and TRUE.
Referenced by popup_create_cb().
stickynotes_load()
void stickynotes_load (GdkScreen * screen)
Definition at line 962 of file stickynotes.c.
References GDK_IS_X11_DISPLAY, StickyNotes::notes, NULL, stickynote_set_color(), stickynote_set_font(), stickynote_set_locked(), stickynote_set_title(), stickynote_set_visible(), stickynotes, stickynotes_save(), TRUE, StickyNotes::visible, StickyNote::w_body, StickyNote::workspace, and XML_CHAR.
Referenced by stickynotes_applet_init().
stickynotes_remove()
void stickynotes_remove (StickyNote * note)
Definition at line 782 of file stickynotes.c.
References StickyNotes::notes, NULL, StickyNotes::settings, stickynote_free(), stickynote_get_empty(), stickynotes, stickynotes_applet_update_tooltips(), stickynotes_save(), and StickyNote::w_window.
Referenced by popup_destroy_cb(), stickynote_close_cb(), and stickynote_delete_cb().
stickynotes_save()
void stickynotes_save (void)
Definition at line 951 of file stickynotes.c.
References NULL, stickynotes_save_now(), and TRUE.
Referenced by preferences_apply_cb(), stickynote_change_properties(), stickynote_configure_cb(), stickynotes_add(), stickynotes_load(), and stickynotes_remove().
stickynotes_save_now()
gboolean stickynotes_save_now (void)
Definition at line 823 of file stickynotes.c.
References StickyNote::color, FALSE, StickyNote::font, StickyNote::font_color, GDK_IS_X11_DISPLAY, StickyNote::h, StickyNote::locked, StickyNotes::notes, NULL, StickyNotes::settings, stickynotes, StickyNote::w, StickyNote::w_body, StickyNote::w_title, StickyNote::w_window, StickyNote::workspace, StickyNote::x, XML_CHAR, and StickyNote::y.
Referenced by applet_destroy_cb(), and stickynotes_save().