MATE Desktop Environment: _EvSidebarPageInterface Struct Reference
_EvSidebarPageInterface Struct Reference
#include <ev-sidebar-page.h>
Public Attributes
GTypeInterface base_iface
gboolean(* support_document)(EvSidebarPage *sidebar_page, EvDocument *document)
void(* set_model)(EvSidebarPage *sidebar_page, EvDocumentModel *model)
const gchar *(* get_label)(EvSidebarPage *sidebar_page)
Detailed Description
Definition at line 42 of file ev-sidebar-page.h.
Member Data Documentation
base_iface
GTypeInterface _EvSidebarPageInterface::base_iface
Definition at line 44 of file ev-sidebar-page.h.
get_label
const gchar *(* _EvSidebarPageInterface::get_label) (EvSidebarPage *sidebar_page)
Definition at line 51 of file ev-sidebar-page.h.
Referenced by ev_sidebar_page_get_label().
set_model
void(* _EvSidebarPageInterface::set_model) (EvSidebarPage *sidebar_page, EvDocumentModel *model)
Definition at line 49 of file ev-sidebar-page.h.
Referenced by ev_sidebar_page_set_model().
support_document
gboolean(* _EvSidebarPageInterface::support_document) (EvSidebarPage *sidebar_page, EvDocument *document)
Definition at line 47 of file ev-sidebar-page.h.
Referenced by ev_sidebar_page_support_document().
The documentation for this struct was generated from the following file:
ev-sidebar-page.h