MATE Desktop Environment: EggToolbarsItemType Struct Reference
EggToolbarsItemType Struct Reference
#include <egg-toolbars-model.h>
Public Attributes
GdkAtom type
gboolean(* has_data)(EggToolbarsItemType *type, const char *name)
char *(* get_data)(EggToolbarsItemType *type, const char *name)
char *(* new_name)(EggToolbarsItemType *type, const char *data)
char *(* get_name)(EggToolbarsItemType *type, const char *data)
Detailed Description
Definition at line 99 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.h.
Member Data Documentation
get_data
char *(* EggToolbarsItemType::get_data)(EggToolbarsItemType *type, const char *name)
Definition at line 105 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.h.
Referenced by egg_toolbars_model_get_data().
get_name
char *(* EggToolbarsItemType::get_name)(EggToolbarsItemType *type, const char *data)
Definition at line 110 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.h.
Referenced by egg_toolbars_model_get_name().
has_data
gboolean(* EggToolbarsItemType::has_data)(EggToolbarsItemType *type, const char *name)
Definition at line 103 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.h.
new_name
char *(* EggToolbarsItemType::new_name)(EggToolbarsItemType *type, const char *data)
Definition at line 108 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.h.
Referenced by egg_toolbars_model_get_name().
type
GdkAtom EggToolbarsItemType::type
Definition at line 101 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.h.
Referenced by egg_toolbars_model_get_data(), and egg_toolbars_model_get_name().
The documentation for this struct was generated from the following files:
atril/cut-n-paste/toolbar-editor/egg-toolbars-model.h
eom/cut-n-paste/toolbar-editor/egg-toolbars-model.h