MATE Desktop Environment: _EvDocumentLayersInterface Struct Reference
_EvDocumentLayersInterface Struct Reference
#include <ev-document-layers.h>
Public Attributes
GTypeInterface base_iface
gboolean(* has_layers)(EvDocumentLayers *document_layers)
GtkTreeModel *(* get_layers)(EvDocumentLayers *document_layers)
void(* show_layer)(EvDocumentLayers *document_layers, EvLayer *layer)
void(* hide_layer)(EvDocumentLayers *document_layers, EvLayer *layer)
gboolean(* layer_is_visible)(EvDocumentLayers *document_layers, EvLayer *layer)
Detailed Description
Definition at line 56 of file ev-document-layers.h.
Member Data Documentation
base_iface
GTypeInterface _EvDocumentLayersInterface::base_iface
Definition at line 58 of file ev-document-layers.h.
get_layers
GtkTreeModel *(* _EvDocumentLayersInterface::get_layers) (EvDocumentLayers *document_layers)
Definition at line 62 of file ev-document-layers.h.
Referenced by ev_document_layers_get_layers().
has_layers
gboolean(* _EvDocumentLayersInterface::has_layers) (EvDocumentLayers *document_layers)
Definition at line 61 of file ev-document-layers.h.
Referenced by ev_document_layers_has_layers().
hide_layer
void(* _EvDocumentLayersInterface::hide_layer) (EvDocumentLayers *document_layers, EvLayer *layer)
Definition at line 66 of file ev-document-layers.h.
Referenced by ev_document_layers_hide_layer().
layer_is_visible
gboolean(* _EvDocumentLayersInterface::layer_is_visible) (EvDocumentLayers *document_layers, EvLayer *layer)
Definition at line 68 of file ev-document-layers.h.
Referenced by ev_document_layers_layer_is_visible().
show_layer
void(* _EvDocumentLayersInterface::show_layer) (EvDocumentLayers *document_layers, EvLayer *layer)
Definition at line 64 of file ev-document-layers.h.
Referenced by ev_document_layers_show_layer().
The documentation for this struct was generated from the following file:
ev-document-layers.h