MATE Desktop Environment: _MateClientClass Struct Reference
_MateClientClass Struct Reference
#include <mate-client.h>
Public Attributes
GtkObjectClass parent_class
gboolean(* save_yourself)(MateClient *client, gint phase, MateSaveStyle save_style, gboolean shutdown, MateInteractStyle interact_style, gboolean fast)
void(* die)(MateClient *client)
void(* save_complete)(MateClient *client)
void(* shutdown_cancelled)(MateClient *client)
void(* connect)(MateClient *client, gboolean restarted)
void(* disconnect)(MateClient *client)
gpointer padding1
gpointer padding2
Detailed Description
Definition at line 167 of file mate-client.h.
Member Data Documentation
connect
void(* _MateClientClass::connect) (MateClient *client, gboolean restarted)
Definition at line 181 of file mate-client.h.
Referenced by MATE_CLASS_BOILERPLATE().
die
void(* _MateClientClass::die) (MateClient *client)
Definition at line 177 of file mate-client.h.
Referenced by MATE_CLASS_BOILERPLATE().
disconnect
void(* _MateClientClass::disconnect) (MateClient *client)
Definition at line 183 of file mate-client.h.
Referenced by MATE_CLASS_BOILERPLATE().
padding1
gpointer _MateClientClass::padding1
Definition at line 186 of file mate-client.h.
padding2
gpointer _MateClientClass::padding2
Definition at line 187 of file mate-client.h.
parent_class
GtkObjectClass _MateClientClass::parent_class
Definition at line 169 of file mate-client.h.
save_complete
void(* _MateClientClass::save_complete) (MateClient *client)
Definition at line 178 of file mate-client.h.
Referenced by MATE_CLASS_BOILERPLATE().
save_yourself
gboolean(* _MateClientClass::save_yourself) (MateClient *client, gint phase, MateSaveStyle save_style, gboolean shutdown, MateInteractStyle interact_style, gboolean fast)
Definition at line 171 of file mate-client.h.
Referenced by MATE_CLASS_BOILERPLATE().
shutdown_cancelled
void(* _MateClientClass::shutdown_cancelled) (MateClient *client)
Definition at line 179 of file mate-client.h.
Referenced by MATE_CLASS_BOILERPLATE().
The documentation for this struct was generated from the following file:
mate-client.h