MATE Desktop Environment: terminal-screen.h File Reference
terminal-screen.h File Reference
#include <vte/vte.h>
#include "terminal-profile.h"
Classes
struct _TerminalScreen
struct _TerminalScreenClass
struct _TerminalScreenPopupInfo
Macros
#define TERMINAL_TYPE_SCREEN (terminal_screen_get_type ())
#define TERMINAL_SCREEN(object) (G_TYPE_CHECK_INSTANCE_CAST ((object), TERMINAL_TYPE_SCREEN, TerminalScreen))
#define TERMINAL_SCREEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TERMINAL_TYPE_SCREEN, TerminalScreenClass))
#define TERMINAL_IS_SCREEN(object) (G_TYPE_CHECK_INSTANCE_TYPE ((object), TERMINAL_TYPE_SCREEN))
#define TERMINAL_IS_SCREEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TERMINAL_TYPE_SCREEN))
#define TERMINAL_SCREEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TERMINAL_TYPE_SCREEN, TerminalScreenClass))
#define TERMINAL_SCALE_XXX_SMALL (PANGO_SCALE_XX_SMALL/1.2)
#define TERMINAL_SCALE_XXXX_SMALL (TERMINAL_SCALE_XXX_SMALL/1.2)
#define TERMINAL_SCALE_XXXXX_SMALL (TERMINAL_SCALE_XXXX_SMALL/1.2)
#define TERMINAL_SCALE_XXX_LARGE (PANGO_SCALE_XX_LARGE*1.2)
#define TERMINAL_SCALE_XXXX_LARGE (TERMINAL_SCALE_XXX_LARGE*1.2)
#define TERMINAL_SCALE_XXXXX_LARGE (TERMINAL_SCALE_XXXX_LARGE*1.2)
#define TERMINAL_SCALE_MINIMUM (TERMINAL_SCALE_XXXXX_SMALL/1.2)
#define TERMINAL_SCALE_MAXIMUM (TERMINAL_SCALE_XXXXX_LARGE*1.2)
Typedefs
typedef struct _TerminalScreenPopupInfo TerminalScreenPopupInfo
typedef struct _TerminalWindow TerminalWindow
typedef struct _TerminalScreen TerminalScreen
typedef struct _TerminalScreenClass TerminalScreenClass
typedef struct _TerminalScreenPrivate TerminalScreenPrivate
Enumerations
enum TerminalURLFlavor {
FLAVOR_AS_IS , FLAVOR_DEFAULT_TO_HTTP , FLAVOR_VOIP_CALL , FLAVOR_EMAIL ,
FLAVOR_SKEY
}
Functions
GType terminal_screen_get_type (void)
TerminalScreen * terminal_screen_new (TerminalProfile *profile, char **override_command, const char *title, const char *working_dir, char **child_env, double zoom)
void terminal_screen_set_profile (TerminalScreen *screen, TerminalProfile *profile)
TerminalProfile * terminal_screen_get_profile (TerminalScreen *screen)
void terminal_screen_set_override_command (TerminalScreen *screen, char **argv)
const char ** terminal_screen_get_override_command (TerminalScreen *screen)
void terminal_screen_set_initial_environment (TerminalScreen *screen, char **argv)
char ** terminal_screen_get_initial_environment (TerminalScreen *screen)
const char * terminal_screen_get_raw_title (TerminalScreen *screen)
const char * terminal_screen_get_title (TerminalScreen *screen)
const char * terminal_screen_get_icon_title (TerminalScreen *screen)
gboolean terminal_screen_get_icon_title_set (TerminalScreen *screen)
void terminal_screen_set_user_title (TerminalScreen *screen, const char *text)
void terminal_screen_set_override_title (TerminalScreen *screen, const char *title)
const char * terminal_screen_get_dynamic_title (TerminalScreen *screen)
const char * terminal_screen_get_dynamic_icon_title (TerminalScreen *screen)
char * terminal_screen_get_current_dir (TerminalScreen *screen)
char * terminal_screen_get_current_dir_with_fallback (TerminalScreen *screen)
void terminal_screen_set_font (TerminalScreen *screen)
void terminal_screen_set_font_scale (TerminalScreen *screen, double factor)
double terminal_screen_get_font_scale (TerminalScreen *screen)
void terminal_screen_get_size (TerminalScreen *screen, int *width_chars, int *height_chars)
void terminal_screen_get_cell_size (TerminalScreen *screen, int *width_chars, int *height_chars)
void _terminal_screen_update_scrollbar (TerminalScreen *screen)
void terminal_screen_save_config (TerminalScreen *screen, GKeyFile *key_file, const char *group)
gboolean terminal_screen_has_foreground_process (TerminalScreen *screen)
TerminalScreenPopupInfo * terminal_screen_popup_info_ref (TerminalScreenPopupInfo *info)
void terminal_screen_popup_info_unref (TerminalScreenPopupInfo *info)
Macro Definition Documentation
TERMINAL_IS_SCREEN
#define TERMINAL_IS_SCREEN (object) (G_TYPE_CHECK_INSTANCE_TYPE ((object), TERMINAL_TYPE_SCREEN))
Definition at line 47 of file terminal-screen.h.
TERMINAL_IS_SCREEN_CLASS
#define TERMINAL_IS_SCREEN_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TERMINAL_TYPE_SCREEN))
Definition at line 48 of file terminal-screen.h.
TERMINAL_SCALE_MAXIMUM
#define TERMINAL_SCALE_MAXIMUM (TERMINAL_SCALE_XXXXX_LARGE*1.2)
Definition at line 143 of file terminal-screen.h.
TERMINAL_SCALE_MINIMUM
#define TERMINAL_SCALE_MINIMUM (TERMINAL_SCALE_XXXXX_SMALL/1.2)
Definition at line 142 of file terminal-screen.h.
TERMINAL_SCALE_XXX_LARGE
#define TERMINAL_SCALE_XXX_LARGE (PANGO_SCALE_XX_LARGE*1.2)
Definition at line 139 of file terminal-screen.h.
TERMINAL_SCALE_XXX_SMALL
#define TERMINAL_SCALE_XXX_SMALL (PANGO_SCALE_XX_SMALL/1.2)
Definition at line 136 of file terminal-screen.h.
TERMINAL_SCALE_XXXX_LARGE
#define TERMINAL_SCALE_XXXX_LARGE (TERMINAL_SCALE_XXX_LARGE*1.2)
Definition at line 140 of file terminal-screen.h.
TERMINAL_SCALE_XXXX_SMALL
#define TERMINAL_SCALE_XXXX_SMALL (TERMINAL_SCALE_XXX_SMALL/1.2)
Definition at line 137 of file terminal-screen.h.
TERMINAL_SCALE_XXXXX_LARGE
#define TERMINAL_SCALE_XXXXX_LARGE (TERMINAL_SCALE_XXXX_LARGE*1.2)
Definition at line 141 of file terminal-screen.h.
TERMINAL_SCALE_XXXXX_SMALL
#define TERMINAL_SCALE_XXXXX_SMALL (TERMINAL_SCALE_XXXX_SMALL/1.2)
Definition at line 138 of file terminal-screen.h.
TERMINAL_SCREEN
#define TERMINAL_SCREEN (object) (G_TYPE_CHECK_INSTANCE_CAST ((object), TERMINAL_TYPE_SCREEN, TerminalScreen))
Definition at line 45 of file terminal-screen.h.
TERMINAL_SCREEN_CLASS
#define TERMINAL_SCREEN_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TERMINAL_TYPE_SCREEN, TerminalScreenClass))
Definition at line 46 of file terminal-screen.h.
TERMINAL_SCREEN_GET_CLASS
#define TERMINAL_SCREEN_GET_CLASS (obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TERMINAL_TYPE_SCREEN, TerminalScreenClass))
Definition at line 49 of file terminal-screen.h.
TERMINAL_TYPE_SCREEN
#define TERMINAL_TYPE_SCREEN (terminal_screen_get_type ())
Definition at line 44 of file terminal-screen.h.
Typedef Documentation
TerminalScreen
typedef struct _TerminalScreen TerminalScreen
Definition at line 51 of file terminal-screen.h.
TerminalScreenClass
typedef struct _TerminalScreenClass TerminalScreenClass
Definition at line 52 of file terminal-screen.h.
TerminalScreenPopupInfo
typedef struct _TerminalScreenPopupInfo TerminalScreenPopupInfo
Definition at line 41 of file terminal-screen.h.
TerminalScreenPrivate
typedef struct _TerminalScreenPrivate TerminalScreenPrivate
Definition at line 53 of file terminal-screen.h.
TerminalWindow
typedef struct _TerminalWindow TerminalWindow
Definition at line 42 of file terminal-screen.h.
Enumeration Type Documentation
TerminalURLFlavor
enum TerminalURLFlavor
Enumerator
FLAVOR_AS_IS
FLAVOR_DEFAULT_TO_HTTP
FLAVOR_VOIP_CALL
FLAVOR_EMAIL
FLAVOR_SKEY
Definition at line 31 of file terminal-screen.h.
Function Documentation
_terminal_screen_update_scrollbar()
void _terminal_screen_update_scrollbar (TerminalScreen * screen)
Definition at line 2307 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, terminal_profile_get_property_enum(), TERMINAL_PROFILE_SCROLLBAR_POSITION, terminal_screen_container_get_from_screen(), terminal_screen_container_set_placement(), terminal_screen_container_set_policy(), TERMINAL_SCROLLBAR_HIDDEN, TERMINAL_SCROLLBAR_LEFT, and TERMINAL_SCROLLBAR_RIGHT.
terminal_screen_get_cell_size()
void terminal_screen_get_cell_size (TerminalScreen * screen, int * width_chars, int * height_chars)
Definition at line 2352 of file terminal-screen.c.
Referenced by terminal_window_update_geometry().
terminal_screen_get_current_dir()
char * terminal_screen_get_current_dir (TerminalScreen * screen)
terminal_screen_get_current_dir: @screen:
Tries to determine the current working directory of the foreground process in @screen's PTY, falling back to the current working directory of the primary child.
Returns: a newly allocated string containing the current working directory, or NULL on failure
Definition at line 1892 of file terminal-screen.c.
References NULL, and _TerminalScreen::priv.
Referenced by terminal_screen_get_current_dir_with_fallback(), and terminal_screen_save_config().
terminal_screen_get_current_dir_with_fallback()
char * terminal_screen_get_current_dir_with_fallback (TerminalScreen * screen)
terminal_screen_get_current_dir_with_fallback: @screen:
Like terminal_screen_get_current_dir(), but falls back to returning @screen's initial working directory, with a further fallback to the user's home directory.
Returns: a newly allocated string containing the current working directory, or NULL on failure
Definition at line 1929 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, and terminal_screen_get_current_dir().
terminal_screen_get_dynamic_icon_title()
const char * terminal_screen_get_dynamic_icon_title (TerminalScreen * screen)
Definition at line 1873 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, and TERMINAL_IS_SCREEN.
terminal_screen_get_dynamic_title()
const char * terminal_screen_get_dynamic_title (TerminalScreen * screen)
Definition at line 1865 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, and TERMINAL_IS_SCREEN.
terminal_screen_get_font_scale()
double terminal_screen_get_font_scale (TerminalScreen * screen)
Definition at line 1964 of file terminal-screen.c.
References _TerminalScreen::priv, and TERMINAL_IS_SCREEN.
terminal_screen_get_icon_title()
const char * terminal_screen_get_icon_title (TerminalScreen * screen)
Definition at line 794 of file terminal-screen.c.
References NULL, and _TerminalScreen::priv.
terminal_screen_get_icon_title_set()
gboolean terminal_screen_get_icon_title_set (TerminalScreen * screen)
Definition at line 809 of file terminal-screen.c.
References _TerminalScreen::priv.
terminal_screen_get_initial_environment()
char ** terminal_screen_get_initial_environment (TerminalScreen * screen)
Definition at line 1353 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, and TERMINAL_IS_SCREEN.
terminal_screen_get_override_command()
const char ** terminal_screen_get_override_command (TerminalScreen * screen)
Definition at line 1332 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, and TERMINAL_IS_SCREEN.
terminal_screen_get_profile()
TerminalProfile * terminal_screen_get_profile (TerminalScreen * screen)
Definition at line 1310 of file terminal-screen.c.
References NULL, and _TerminalScreen::priv.
Referenced by terminal_window_update_copy_selection().
terminal_screen_get_raw_title()
const char * terminal_screen_get_raw_title (TerminalScreen * screen)
Definition at line 768 of file terminal-screen.c.
References _TerminalScreen::priv.
terminal_screen_get_size()
void terminal_screen_get_size (TerminalScreen * screen, int * width_chars, int * height_chars)
Definition at line 2341 of file terminal-screen.c.
Referenced by terminal_window_save_state(), terminal_window_update_geometry(), and terminal_window_update_size_set_geometry().
terminal_screen_get_title()
const char * terminal_screen_get_title (TerminalScreen * screen)
Definition at line 779 of file terminal-screen.c.
References NULL, and _TerminalScreen::priv.
terminal_screen_get_type()
GType terminal_screen_get_type (void)
terminal_screen_has_foreground_process()
gboolean terminal_screen_has_foreground_process (TerminalScreen * screen)
terminal_screen_has_foreground_process: @screen:
Checks whether there's a foreground process running in this terminal.
Returns: TRUE iff there's a foreground process running in @screen
Definition at line 2488 of file terminal-screen.c.
References FALSE, name, NULL, _TerminalScreen::priv, and TRUE.
terminal_screen_new()
TerminalScreen * terminal_screen_new (TerminalProfile * profile, char ** override_command, const char * title, const char * working_dir, char ** child_env, double zoom)
Definition at line 723 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, TERMINAL_IS_PROFILE, TERMINAL_PROFILE_DEFAULT_SIZE_COLUMNS, TERMINAL_PROFILE_DEFAULT_SIZE_ROWS, terminal_profile_get_property_boolean(), terminal_profile_get_property_int(), TERMINAL_PROFILE_USE_CUSTOM_DEFAULT_SIZE, terminal_screen_set_font(), terminal_screen_set_font_scale(), terminal_screen_set_initial_environment(), terminal_screen_set_override_command(), terminal_screen_set_override_title(), terminal_screen_set_profile(), and TERMINAL_TYPE_SCREEN.
Referenced by terminal_app_new_terminal().
terminal_screen_popup_info_ref()
TerminalScreenPopupInfo * terminal_screen_popup_info_ref (TerminalScreenPopupInfo * info)
Definition at line 1671 of file terminal-screen.c.
References NULL, and _TerminalScreenPopupInfo::ref_count.
terminal_screen_popup_info_unref()
void terminal_screen_popup_info_unref (TerminalScreenPopupInfo * info)
Definition at line 1680 of file terminal-screen.c.
References _TerminalScreenPopupInfo::hyperlink, NULL, _TerminalScreenPopupInfo::ref_count, _TerminalScreenPopupInfo::screen, and _TerminalScreenPopupInfo::url.
terminal_screen_save_config()
void terminal_screen_save_config (TerminalScreen * screen, GKeyFile * key_file, const char * group)
Definition at line 2444 of file terminal-screen.c.
References _TerminalScreen::priv, TERMINAL_CONFIG_TERMINAL_PROP_COMMAND, TERMINAL_CONFIG_TERMINAL_PROP_HEIGHT, TERMINAL_CONFIG_TERMINAL_PROP_PROFILE_ID, TERMINAL_CONFIG_TERMINAL_PROP_TITLE, TERMINAL_CONFIG_TERMINAL_PROP_WIDTH, TERMINAL_CONFIG_TERMINAL_PROP_WORKING_DIRECTORY, TERMINAL_CONFIG_TERMINAL_PROP_ZOOM, terminal_profile_get_property_string(), TERMINAL_PROFILE_NAME, terminal_screen_get_current_dir(), terminal_util_key_file_set_argv(), and terminal_util_key_file_set_string_escape().
Referenced by terminal_window_save_state().
terminal_screen_set_font()
void terminal_screen_set_font (TerminalScreen * screen)
Definition at line 1195 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, terminal_app_get(), TERMINAL_PROFILE_FONT, terminal_profile_get_property_boolean(), and TERMINAL_PROFILE_USE_SYSTEM_FONT.
Referenced by terminal_screen_new().
terminal_screen_set_font_scale()
void terminal_screen_set_font_scale (TerminalScreen * screen, double factor)
Definition at line 1942 of file terminal-screen.c.
References _TerminalScreen::priv, TERMINAL_IS_SCREEN, TERMINAL_SCALE_MAXIMUM, and TERMINAL_SCALE_MINIMUM.
Referenced by terminal_screen_new().
terminal_screen_set_initial_environment()
void terminal_screen_set_initial_environment (TerminalScreen * screen, char ** argv)
Definition at line 1340 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, and TERMINAL_IS_SCREEN.
Referenced by terminal_screen_new().
terminal_screen_set_override_command()
void terminal_screen_set_override_command (TerminalScreen * screen, char ** argv)
Definition at line 1319 of file terminal-screen.c.
References _TerminalScreen::priv, and TERMINAL_IS_SCREEN.
Referenced by terminal_screen_new().
terminal_screen_set_override_title()
void terminal_screen_set_override_title (TerminalScreen * screen, const char * title)
Definition at line 1850 of file terminal-screen.c.
References FALSE, and _TerminalScreen::priv.
Referenced by terminal_screen_new().
terminal_screen_set_profile()
void terminal_screen_set_profile (TerminalScreen * screen, TerminalProfile * profile)
Definition at line 1260 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, PROFILE_SET, and signals.
Referenced by terminal_screen_new().
terminal_screen_set_user_title()
void terminal_screen_set_user_title (TerminalScreen * screen, const char * text)
Definition at line 2056 of file terminal-screen.c.
References FALSE, _TerminalScreen::priv, and TRUE.