MATE Desktop Environment: terminal-screen.c File Reference
terminal-screen.c File Reference
#include <config.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/wait.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <gdk/gdk.h>
#include <gdk/gdkx.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <cairo.h>
#include "terminal-accels.h"
#include "terminal-app.h"
#include "terminal-debug.h"
#include "terminal-intl.h"
#include "terminal-marshal.h"
#include "terminal-profile.h"
#include "terminal-screen-container.h"
#include "terminal-util.h"
#include "terminal-window.h"
#include "terminal-info-bar.h"
#include "eggshell.h"
#include <pcre2.h>
Macros
#define PCRE2_CODE_UNIT_WIDTH 0
#define URL_MATCH_CURSOR (GDK_HAND2)
#define SKEY_MATCH_CURSOR (GDK_HAND2)
#define USERCHARS "-[:alnum:]"
#define USERCHARS_CLASS "[" USERCHARS "]"
#define PASSCHARS_CLASS "[-[:alnum:]\\Q,?;.:/!%$^*&~\"#'\\E]"
#define HOSTCHARS_CLASS "[-[:alnum:]]"
#define HOST HOSTCHARS_CLASS "+(\\." HOSTCHARS_CLASS "+)*"
#define PORT "(?:\\:[[:digit:]]{1,5})?"
#define PATHCHARS_CLASS "[-[:alnum:]\\Q_$.+!*,:;@&=?/~#%\\E]"
#define PATHTERM_CLASS "[^\\Q]'.:}>) \t\r\n,\"\\E]"
#define SCHEME "(?:news:|telnet:|nntp:|file:\\/|https?:|ftps?:|sftp:|webcal:)"
#define USERPASS USERCHARS_CLASS "+(?:" PASSCHARS_CLASS "+)?"
#define URLPATH "(?:(/"PATHCHARS_CLASS"+(?:[(]"PATHCHARS_CLASS"*[)])*"PATHCHARS_CLASS"*)*"PATHTERM_CLASS")?"
Enumerations
enum {
PROFILE_SET , SHOW_POPUP_MENU , MATCH_CLICKED , CLOSE_SCREEN ,
LAST_SIGNAL
}
enum {
PROP_0 , PROP_PROFILE , PROP_ICON_TITLE , PROP_ICON_TITLE_SET ,
PROP_OVERRIDE_COMMAND , PROP_TITLE , PROP_INITIAL_ENVIRONMENT
}
enum {
TARGET_COLOR , TARGET_BGIMAGE , TARGET_RESET_BG , TARGET_MOZ_URL ,
TARGET_NETSCAPE_URL , TARGET_TAB
}
enum { RESPONSE_RELAUNCH , RESPONSE_EDIT_PROFILE }
Functions
TerminalScreen * terminal_screen_new (TerminalProfile *profile, char **override_command, const char *title, const char *working_dir, char **child_env, double zoom)
const char * terminal_screen_get_raw_title (TerminalScreen *screen)
const char * terminal_screen_get_title (TerminalScreen *screen)
const char * terminal_screen_get_icon_title (TerminalScreen *screen)
gboolean terminal_screen_get_icon_title_set (TerminalScreen *screen)
void terminal_screen_set_font (TerminalScreen *screen)
void terminal_screen_set_profile (TerminalScreen *screen, TerminalProfile *profile)
TerminalProfile * terminal_screen_get_profile (TerminalScreen *screen)
void terminal_screen_set_override_command (TerminalScreen *screen, char **argv)
const char ** terminal_screen_get_override_command (TerminalScreen *screen)
void terminal_screen_set_initial_environment (TerminalScreen *screen, char **argv)
char ** terminal_screen_get_initial_environment (TerminalScreen *screen)
TerminalScreenPopupInfo * terminal_screen_popup_info_ref (TerminalScreenPopupInfo *info)
void terminal_screen_popup_info_unref (TerminalScreenPopupInfo *info)
void terminal_screen_set_override_title (TerminalScreen *screen, const char *title)
const char * terminal_screen_get_dynamic_title (TerminalScreen *screen)
const char * terminal_screen_get_dynamic_icon_title (TerminalScreen *screen)
char * terminal_screen_get_current_dir (TerminalScreen *screen)
void terminal_screen_set_font_scale (TerminalScreen *screen, double factor)
double terminal_screen_get_font_scale (TerminalScreen *screen)
void terminal_screen_set_user_title (TerminalScreen *screen, const char *text)
void _terminal_screen_update_scrollbar (TerminalScreen *screen)
void terminal_screen_get_size (TerminalScreen *screen, int *width_chars, int *height_chars)
void terminal_screen_get_cell_size (TerminalScreen *screen, int *cell_width_pixels, int *cell_height_pixels)
void terminal_screen_save_config (TerminalScreen *screen, GKeyFile *key_file, const char *group)
gboolean terminal_screen_has_foreground_process (TerminalScreen *screen)
Macro Definition Documentation
HOST
#define HOST HOSTCHARS_CLASS "+(\\." HOSTCHARS_CLASS "+)*"
Definition at line 158 of file terminal-screen.c.
HOSTCHARS_CLASS
#define HOSTCHARS_CLASS "[-[:alnum:]]"
Definition at line 157 of file terminal-screen.c.
PASSCHARS_CLASS
#define PASSCHARS_CLASS "[-[:alnum:]\\Q,?;.:/!%$^*&~\"#'\\E]"
Definition at line 156 of file terminal-screen.c.
PATHCHARS_CLASS
#define PATHCHARS_CLASS "[-[:alnum:]\\Q_$.+!*,:;@&=?/~#%\\E]"
Definition at line 160 of file terminal-screen.c.
PATHTERM_CLASS
#define PATHTERM_CLASS "[^\\Q]'.:}>) \t\r\n,\"\\E]"
Definition at line 161 of file terminal-screen.c.
PCRE2_CODE_UNIT_WIDTH
#define PCRE2_CODE_UNIT_WIDTH 0
Definition at line 49 of file terminal-screen.c.
PORT
#define PORT "(?:\\:[[:digit:]]{1,5})?"
Definition at line 159 of file terminal-screen.c.
SCHEME
#define SCHEME "(?:news:|telnet:|nntp:|file:\\/|https?:|ftps?:|sftp:|webcal:)"
Definition at line 162 of file terminal-screen.c.
SKEY_MATCH_CURSOR
#define SKEY_MATCH_CURSOR (GDK_HAND2)
Definition at line 53 of file terminal-screen.c.
URL_MATCH_CURSOR
#define URL_MATCH_CURSOR (GDK_HAND2)
Definition at line 52 of file terminal-screen.c.
URLPATH
#define URLPATH "(?:(/"PATHCHARS_CLASS"+(?:[(]"PATHCHARS_CLASS"*[)])*"PATHCHARS_CLASS"*)*"PATHTERM_CLASS")?"
Definition at line 164 of file terminal-screen.c.
USERCHARS
#define USERCHARS "-[:alnum:]"
Definition at line 154 of file terminal-screen.c.
USERCHARS_CLASS
#define USERCHARS_CLASS "[" USERCHARS "]"
Definition at line 155 of file terminal-screen.c.
USERPASS
#define USERPASS USERCHARS_CLASS "+(?:" PASSCHARS_CLASS "+)?"
Definition at line 163 of file terminal-screen.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROFILE_SET
SHOW_POPUP_MENU
MATCH_CLICKED
CLOSE_SCREEN
LAST_SIGNAL
Definition at line 82 of file terminal-screen.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_PROFILE
PROP_ICON_TITLE
PROP_ICON_TITLE_SET
PROP_OVERRIDE_COMMAND
PROP_TITLE
PROP_INITIAL_ENVIRONMENT
Definition at line 91 of file terminal-screen.c.
anonymous enum
anonymous enum
Enumerator
TARGET_COLOR
TARGET_BGIMAGE
TARGET_RESET_BG
TARGET_MOZ_URL
TARGET_NETSCAPE_URL
TARGET_TAB
Definition at line 102 of file terminal-screen.c.
anonymous enum
anonymous enum
Enumerator
RESPONSE_RELAUNCH
RESPONSE_EDIT_PROFILE
Definition at line 1510 of file terminal-screen.c.
Function Documentation
_terminal_screen_update_scrollbar()
void _terminal_screen_update_scrollbar (TerminalScreen * screen)
Definition at line 2285 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, terminal_profile_get_property_enum(), TERMINAL_PROFILE_SCROLLBAR_POSITION, terminal_screen_container_get_from_screen(), terminal_screen_container_set_placement(), terminal_screen_container_set_policy(), TERMINAL_SCROLLBAR_HIDDEN, TERMINAL_SCROLLBAR_LEFT, and TERMINAL_SCROLLBAR_RIGHT.
terminal_screen_get_cell_size()
void terminal_screen_get_cell_size (TerminalScreen * screen, int * cell_width_pixels, int * cell_height_pixels)
Definition at line 2330 of file terminal-screen.c.
Referenced by terminal_window_update_geometry().
terminal_screen_get_current_dir()
char * terminal_screen_get_current_dir (TerminalScreen * screen)
terminal_screen_get_current_dir: @screen:
Tries to determine the current working directory of the terminal. First tries OSC 7 (current directory URI set by the shell), then falls back to reading /proc for the child process's cwd, and finally to the initial working directory.
Returns: a newly allocated string containing the current working directory, or NULL on failure
Definition at line 1893 of file terminal-screen.c.
References NULL, and _TerminalScreen::priv.
Referenced by terminal_screen_save_config().
terminal_screen_get_dynamic_icon_title()
const char * terminal_screen_get_dynamic_icon_title (TerminalScreen * screen)
Definition at line 1873 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, and TERMINAL_IS_SCREEN.
terminal_screen_get_dynamic_title()
const char * terminal_screen_get_dynamic_title (TerminalScreen * screen)
Definition at line 1865 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, and TERMINAL_IS_SCREEN.
terminal_screen_get_font_scale()
double terminal_screen_get_font_scale (TerminalScreen * screen)
Definition at line 1942 of file terminal-screen.c.
References _TerminalScreen::priv, and TERMINAL_IS_SCREEN.
terminal_screen_get_icon_title()
const char * terminal_screen_get_icon_title (TerminalScreen * screen)
Definition at line 794 of file terminal-screen.c.
References NULL, and _TerminalScreen::priv.
terminal_screen_get_icon_title_set()
gboolean terminal_screen_get_icon_title_set (TerminalScreen * screen)
Definition at line 809 of file terminal-screen.c.
References _TerminalScreen::priv.
terminal_screen_get_initial_environment()
char ** terminal_screen_get_initial_environment (TerminalScreen * screen)
Definition at line 1353 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, and TERMINAL_IS_SCREEN.
terminal_screen_get_override_command()
const char ** terminal_screen_get_override_command (TerminalScreen * screen)
Definition at line 1332 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, and TERMINAL_IS_SCREEN.
terminal_screen_get_profile()
TerminalProfile * terminal_screen_get_profile (TerminalScreen * screen)
Definition at line 1310 of file terminal-screen.c.
References NULL, and _TerminalScreen::priv.
Referenced by terminal_window_update_copy_selection().
terminal_screen_get_raw_title()
const char * terminal_screen_get_raw_title (TerminalScreen * screen)
Definition at line 768 of file terminal-screen.c.
References _TerminalScreen::priv.
terminal_screen_get_size()
void terminal_screen_get_size (TerminalScreen * screen, int * width_chars, int * height_chars)
Definition at line 2319 of file terminal-screen.c.
Referenced by terminal_window_save_state(), terminal_window_update_geometry(), and terminal_window_update_size_set_geometry().
terminal_screen_get_title()
const char * terminal_screen_get_title (TerminalScreen * screen)
Definition at line 779 of file terminal-screen.c.
References NULL, and _TerminalScreen::priv.
terminal_screen_has_foreground_process()
gboolean terminal_screen_has_foreground_process (TerminalScreen * screen)
terminal_screen_has_foreground_process: @screen:
Checks whether there's a foreground process running in this terminal.
Returns: TRUE iff there's a foreground process running in @screen
Definition at line 2466 of file terminal-screen.c.
References FALSE, name, NULL, _TerminalScreen::priv, and TRUE.
terminal_screen_new()
TerminalScreen * terminal_screen_new (TerminalProfile * profile, char ** override_command, const char * title, const char * working_dir, char ** child_env, double zoom)
Definition at line 723 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, TERMINAL_IS_PROFILE, TERMINAL_PROFILE_DEFAULT_SIZE_COLUMNS, TERMINAL_PROFILE_DEFAULT_SIZE_ROWS, terminal_profile_get_property_boolean(), terminal_profile_get_property_int(), TERMINAL_PROFILE_USE_CUSTOM_DEFAULT_SIZE, terminal_screen_set_font(), terminal_screen_set_font_scale(), terminal_screen_set_initial_environment(), terminal_screen_set_override_command(), terminal_screen_set_override_title(), terminal_screen_set_profile(), and TERMINAL_TYPE_SCREEN.
Referenced by terminal_app_new_terminal().
terminal_screen_popup_info_ref()
TerminalScreenPopupInfo * terminal_screen_popup_info_ref (TerminalScreenPopupInfo * info)
Definition at line 1671 of file terminal-screen.c.
References NULL, and _TerminalScreenPopupInfo::ref_count.
terminal_screen_popup_info_unref()
void terminal_screen_popup_info_unref (TerminalScreenPopupInfo * info)
Definition at line 1680 of file terminal-screen.c.
References _TerminalScreenPopupInfo::hyperlink, NULL, _TerminalScreenPopupInfo::ref_count, _TerminalScreenPopupInfo::screen, and _TerminalScreenPopupInfo::url.
terminal_screen_save_config()
void terminal_screen_save_config (TerminalScreen * screen, GKeyFile * key_file, const char * group)
Definition at line 2422 of file terminal-screen.c.
References _TerminalScreen::priv, TERMINAL_CONFIG_TERMINAL_PROP_COMMAND, TERMINAL_CONFIG_TERMINAL_PROP_HEIGHT, TERMINAL_CONFIG_TERMINAL_PROP_PROFILE_ID, TERMINAL_CONFIG_TERMINAL_PROP_TITLE, TERMINAL_CONFIG_TERMINAL_PROP_WIDTH, TERMINAL_CONFIG_TERMINAL_PROP_WORKING_DIRECTORY, TERMINAL_CONFIG_TERMINAL_PROP_ZOOM, terminal_profile_get_property_string(), TERMINAL_PROFILE_NAME, terminal_screen_get_current_dir(), terminal_util_key_file_set_argv(), and terminal_util_key_file_set_string_escape().
Referenced by terminal_window_save_state().
terminal_screen_set_font()
void terminal_screen_set_font (TerminalScreen * screen)
Definition at line 1195 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, terminal_app_get(), TERMINAL_PROFILE_FONT, terminal_profile_get_property_boolean(), and TERMINAL_PROFILE_USE_SYSTEM_FONT.
Referenced by terminal_screen_new().
terminal_screen_set_font_scale()
void terminal_screen_set_font_scale (TerminalScreen * screen, double factor)
Definition at line 1920 of file terminal-screen.c.
References _TerminalScreen::priv, TERMINAL_IS_SCREEN, TERMINAL_SCALE_MAXIMUM, and TERMINAL_SCALE_MINIMUM.
Referenced by terminal_screen_new().
terminal_screen_set_initial_environment()
void terminal_screen_set_initial_environment (TerminalScreen * screen, char ** argv)
Definition at line 1340 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, and TERMINAL_IS_SCREEN.
Referenced by terminal_screen_new().
terminal_screen_set_override_command()
void terminal_screen_set_override_command (TerminalScreen * screen, char ** argv)
Definition at line 1319 of file terminal-screen.c.
References _TerminalScreen::priv, and TERMINAL_IS_SCREEN.
Referenced by terminal_screen_new().
terminal_screen_set_override_title()
void terminal_screen_set_override_title (TerminalScreen * screen, const char * title)
Definition at line 1850 of file terminal-screen.c.
References FALSE, and _TerminalScreen::priv.
Referenced by terminal_screen_new().
terminal_screen_set_profile()
void terminal_screen_set_profile (TerminalScreen * screen, TerminalProfile * profile)
Definition at line 1260 of file terminal-screen.c.
References NULL, _TerminalScreen::priv, PROFILE_SET, and signals.
Referenced by terminal_screen_new().
terminal_screen_set_user_title()
void terminal_screen_set_user_title (TerminalScreen * screen, const char * text)
Definition at line 2034 of file terminal-screen.c.
References FALSE, _TerminalScreen::priv, and TRUE.