MATE Desktop Environment: terminal-screen-container.c File Reference
terminal-screen-container.c File Reference
#include <config.h>
#include "terminal-screen-container.h"
#include "terminal-debug.h"
#include "terminal-intl.h"
#include <gtk/gtk.h>
Enumerations
enum {
PROP_0 , PROP_SCREEN , PROP_HSCROLLBAR_POLICY , PROP_VSCROLLBAR_POLICY ,
PROP_WINDOW_PLACEMENT , PROP_WINDOW_PLACEMENT_SET
}
Functions
GtkWidget * terminal_screen_container_new (TerminalScreen *screen)
TerminalScreen * terminal_screen_container_get_screen (TerminalScreenContainer *container)
TerminalScreenContainer * terminal_screen_container_get_from_screen (TerminalScreen *screen)
void terminal_screen_container_set_policy (TerminalScreenContainer *container, GtkPolicyType hpolicy G_GNUC_UNUSED, GtkPolicyType vpolicy)
void terminal_screen_container_set_placement (TerminalScreenContainer *container, GtkCornerType corner)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_SCREEN
PROP_HSCROLLBAR_POLICY
PROP_VSCROLLBAR_POLICY
PROP_WINDOW_PLACEMENT
PROP_WINDOW_PLACEMENT_SET
Definition at line 44 of file terminal-screen-container.c.
Function Documentation
terminal_screen_container_get_from_screen()
TerminalScreenContainer * terminal_screen_container_get_from_screen (TerminalScreen * screen)
terminal_screen_container_get_from_screen: @screen: a TerminalScreenContainerPrivate
Returns the TerminalScreenContainer containing @screen.
Definition at line 338 of file terminal-screen-container.c.
References NULL, TERMINAL_IS_SCREEN, TERMINAL_SCREEN_CONTAINER, and TERMINAL_TYPE_SCREEN_CONTAINER.
Referenced by _terminal_screen_update_scrollbar(), terminal_window_move_screen(), terminal_window_remove_screen(), and terminal_window_switch_screen().
terminal_screen_container_get_screen()
TerminalScreen * terminal_screen_container_get_screen (TerminalScreenContainer * container)
terminal_screen_container_get_screen: @container: a TerminalScreenContainer
Returns: @container's TerminalScreen
Definition at line 324 of file terminal-screen-container.c.
References NULL, _TerminalScreenContainer::priv, and TERMINAL_IS_SCREEN_CONTAINER.
Referenced by terminal_window_save_state().
terminal_screen_container_new()
GtkWidget * terminal_screen_container_new (TerminalScreen * screen)
terminal_screen_container_new: @screen: a TerminalScreen
Returns: a new TerminalScreenContainer for @screen
Definition at line 310 of file terminal-screen-container.c.
References NULL, and TERMINAL_TYPE_SCREEN_CONTAINER.
Referenced by terminal_window_add_screen().
terminal_screen_container_set_placement()
void terminal_screen_container_set_placement (TerminalScreenContainer * container, GtkCornerType corner)
terminal_screen_container_set_placement: @container: a TerminalScreenContainer @corner: a #GtkCornerType
Sets @container's window placement.
Definition at line 407 of file terminal-screen-container.c.
References TERMINAL_IS_SCREEN_CONTAINER, and TRUE.
Referenced by _terminal_screen_update_scrollbar().
terminal_screen_container_set_policy()
void terminal_screen_container_set_policy (TerminalScreenContainer * container, GtkPolicyType hpolicy G_GNUC_UNUSED, GtkPolicyType vpolicy)
terminal_screen_container_set_policy: @container: a TerminalScreenContainer @hpolicy: a #GtkPolicyType @vpolicy: a #GtkPolicyType
Sets @container's scrollbar policy.
Definition at line 354 of file terminal-screen-container.c.
References _TerminalScreenContainer::priv, and TERMINAL_IS_SCREEN_CONTAINER.
Referenced by _terminal_screen_update_scrollbar().