MATE Desktop Environment: terminal-search-dialog.c File Reference
terminal-search-dialog.c File Reference
#include "config.h"
#include <string.h>
#include "terminal-search-dialog.h"
#include "terminal-util.h"
#include <pcre2.h>
Macros
#define PCRE2_CODE_UNIT_WIDTH 0
#define HISTORY_MIN_ITEM_LEN 3
#define HISTORY_LENGTH 10
#define TERMINAL_SEARCH_DIALOG_GET_PRIVATE(object) ((TerminalSearchDialogPrivate *) g_object_get_qdata (G_OBJECT (object), get_quark ()))
#define GET_FLAG(widget) gtk_toggle_button_get_active (GTK_TOGGLE_BUTTON (priv->widget))
Typedefs
typedef struct _TerminalSearchDialogPrivate TerminalSearchDialogPrivate
Functions
GtkWidget * terminal_search_dialog_new (GtkWindow *parent)
void terminal_search_dialog_present (GtkWidget *dialog)
void terminal_search_dialog_set_search_text (GtkWidget *dialog, const gchar *text)
const gchar * terminal_search_dialog_get_search_text (GtkWidget *dialog)
TerminalSearchFlags terminal_search_dialog_get_search_flags (GtkWidget *dialog)
VteRegex * terminal_search_dialog_get_regex (GtkWidget *dialog)
Macro Definition Documentation
GET_FLAG
#define GET_FLAG (widget) gtk_toggle_button_get_active (GTK_TOGGLE_BUTTON (priv->widget))
Definition at line 49 of file terminal-search-dialog.c.
HISTORY_LENGTH
#define HISTORY_LENGTH 10
Definition at line 33 of file terminal-search-dialog.c.
HISTORY_MIN_ITEM_LEN
#define HISTORY_MIN_ITEM_LEN 3
Definition at line 32 of file terminal-search-dialog.c.
PCRE2_CODE_UNIT_WIDTH
#define PCRE2_CODE_UNIT_WIDTH 0
Definition at line 29 of file terminal-search-dialog.c.
TERMINAL_SEARCH_DIALOG_GET_PRIVATE
#define TERMINAL_SEARCH_DIALOG_GET_PRIVATE (object) ((TerminalSearchDialogPrivate *) g_object_get_qdata (G_OBJECT (object), get_quark ()))
Definition at line 46 of file terminal-search-dialog.c.
Typedef Documentation
TerminalSearchDialogPrivate
typedef struct _TerminalSearchDialogPrivate TerminalSearchDialogPrivate
Function Documentation
terminal_search_dialog_get_regex()
VteRegex * terminal_search_dialog_get_regex (GtkWidget * dialog)
Definition at line 338 of file terminal-search-dialog.c.
References GET_FLAG, NULL, TERMINAL_SEARCH_DIALOG_GET_PRIVATE, and terminal_search_dialog_get_search_text().
terminal_search_dialog_get_search_flags()
TerminalSearchFlags terminal_search_dialog_get_search_flags (GtkWidget * dialog)
Definition at line 318 of file terminal-search-dialog.c.
References GET_FLAG, TERMINAL_SEARCH_DIALOG_GET_PRIVATE, TERMINAL_SEARCH_FLAG_BACKWARDS, and TERMINAL_SEARCH_FLAG_WRAP_AROUND.
terminal_search_dialog_get_search_text()
const gchar * terminal_search_dialog_get_search_text (GtkWidget * dialog)
Definition at line 305 of file terminal-search-dialog.c.
References NULL, and TERMINAL_SEARCH_DIALOG_GET_PRIVATE.
Referenced by terminal_search_dialog_get_regex().
terminal_search_dialog_new()
GtkWidget * terminal_search_dialog_new (GtkWindow * parent)
Definition at line 78 of file terminal-search-dialog.c.
References FALSE, HISTORY_MIN_ITEM_LEN, NULL, terminal_util_load_builder_resource(), TRUE, and update_sensitivity().
terminal_search_dialog_present()
void terminal_search_dialog_present (GtkWidget * dialog)
Definition at line 138 of file terminal-search-dialog.c.
References TERMINAL_SEARCH_DIALOG_GET_PRIVATE.
terminal_search_dialog_set_search_text()
void terminal_search_dialog_set_search_text (GtkWidget * dialog, const gchar * text)
Definition at line 286 of file terminal-search-dialog.c.
References NULL, and TERMINAL_SEARCH_DIALOG_GET_PRIVATE.