MATE Desktop Environment: terminal-search-dialog.h File Reference
terminal-search-dialog.h File Reference
#include <gtk/gtk.h>
#include <vte/vte.h>
Typedefs
typedef enum _TerminalSearchFlags TerminalSearchFlags
Enumerations
enum _TerminalSearchFlags { TERMINAL_SEARCH_FLAG_BACKWARDS = 1 << 0 , TERMINAL_SEARCH_FLAG_WRAP_AROUND = 1 << 1 }
Functions
GtkWidget * terminal_search_dialog_new (GtkWindow *parent)
void terminal_search_dialog_present (GtkWidget *dialog)
void terminal_search_dialog_set_search_text (GtkWidget *dialog, const gchar *text)
const gchar * terminal_search_dialog_get_search_text (GtkWidget *dialog)
TerminalSearchFlags terminal_search_dialog_get_search_flags (GtkWidget *dialog)
VteRegex * terminal_search_dialog_get_regex (GtkWidget *dialog)
Typedef Documentation
TerminalSearchFlags
typedef enum _TerminalSearchFlags TerminalSearchFlags
Enumeration Type Documentation
_TerminalSearchFlags
enum _TerminalSearchFlags
Enumerator
TERMINAL_SEARCH_FLAG_BACKWARDS
TERMINAL_SEARCH_FLAG_WRAP_AROUND
Definition at line 30 of file terminal-search-dialog.h.
Function Documentation
terminal_search_dialog_get_regex()
VteRegex * terminal_search_dialog_get_regex (GtkWidget * dialog)
Definition at line 338 of file terminal-search-dialog.c.
References GET_FLAG, NULL, TERMINAL_SEARCH_DIALOG_GET_PRIVATE, and terminal_search_dialog_get_search_text().
terminal_search_dialog_get_search_flags()
TerminalSearchFlags terminal_search_dialog_get_search_flags (GtkWidget * dialog)
Definition at line 318 of file terminal-search-dialog.c.
References GET_FLAG, TERMINAL_SEARCH_DIALOG_GET_PRIVATE, TERMINAL_SEARCH_FLAG_BACKWARDS, and TERMINAL_SEARCH_FLAG_WRAP_AROUND.
terminal_search_dialog_get_search_text()
const gchar * terminal_search_dialog_get_search_text (GtkWidget * dialog)
Definition at line 305 of file terminal-search-dialog.c.
References NULL, and TERMINAL_SEARCH_DIALOG_GET_PRIVATE.
Referenced by terminal_search_dialog_get_regex().
terminal_search_dialog_new()
GtkWidget * terminal_search_dialog_new (GtkWindow * parent)
Definition at line 78 of file terminal-search-dialog.c.
References FALSE, HISTORY_MIN_ITEM_LEN, NULL, terminal_util_load_builder_resource(), TRUE, and update_sensitivity().
terminal_search_dialog_present()
void terminal_search_dialog_present (GtkWidget * dialog)
Definition at line 138 of file terminal-search-dialog.c.
References TERMINAL_SEARCH_DIALOG_GET_PRIVATE.
terminal_search_dialog_set_search_text()
void terminal_search_dialog_set_search_text (GtkWidget * dialog, const gchar * text)
Definition at line 286 of file terminal-search-dialog.c.
References NULL, and TERMINAL_SEARCH_DIALOG_GET_PRIVATE.