MATE Desktop Environment: terminal-app.c File Reference
terminal-app.c File Reference
#include <config.h>
#include <errno.h>
#include <glib.h>
#include <dconf.h>
#include "terminal-intl.h"
#include "terminal-debug.h"
#include "terminal-app.h"
#include "terminal-accels.h"
#include "terminal-screen.h"
#include "terminal-screen-container.h"
#include "terminal-window.h"
#include "terminal-util.h"
#include "profile-editor.h"
#include "terminal-encoding.h"
#include <string.h>
#include <stdlib.h>
Macros
#define FALLBACK_PROFILE_ID "default"
#define MONOSPACE_FONT_SCHEMA "org.mate.interface"
#define MONOSPACE_FONT_KEY "monospace-font-name"
#define DEFAULT_MONOSPACE_FONT ("Monospace 10")
#define ENABLE_MNEMONICS_KEY "use-mnemonics"
#define DEFAULT_ENABLE_MNEMONICS (TRUE)
#define ENABLE_MENU_BAR_ACCEL_KEY "use-menu-accelerators"
#define DEFAULT_ENABLE_MENU_BAR_ACCEL (TRUE)
#define PROFILE_LIST_KEY "profile-list"
#define DEFAULT_PROFILE_KEY "default-profile"
#define ENCODING_LIST_KEY "active-encodings"
Enumerations
enum {
PROP_0 , PROP_DEFAULT_PROFILE , PROP_ENABLE_MENU_BAR_ACCEL , PROP_ENABLE_MNEMONICS ,
PROP_SYSTEM_FONT
}
enum { QUIT , PROFILE_LIST_CHANGED , ENCODING_LIST_CHANGED , LAST_SIGNAL }
enum { COL_PROFILE , NUM_COLUMNS }
enum { SOURCE_DEFAULT = 0 , SOURCE_SESSION = 1 }
Functions
void terminal_app_new_profile (TerminalApp *app, TerminalProfile *default_base_profile, GtkWindow *transient_parent)
void terminal_app_manage_profiles (TerminalApp *app, GtkWindow *transient_parent)
TerminalApp * terminal_app_get (void)
void terminal_app_shutdown (void)
gboolean terminal_app_handle_options (TerminalApp *app, TerminalOptions *options, gboolean allow_resume, GError **error)
TerminalWindow * terminal_app_new_window (TerminalApp *app, GdkScreen *screen)
TerminalScreen * terminal_app_new_terminal (TerminalApp *app, TerminalWindow *window, TerminalProfile *profile, char **override_command, const char *title, const char *working_dir, char **child_env, double zoom)
void terminal_app_edit_profile (TerminalApp *app, TerminalProfile *profile, GtkWindow *transient_parent, const char *widget_name)
void terminal_app_edit_keybindings (TerminalApp *app, GtkWindow *transient_parent)
void terminal_app_edit_encodings (TerminalApp *app, GtkWindow *transient_parent)
TerminalWindow * terminal_app_get_current_window (TerminalApp *app, GdkScreen *from_screen, int workspace)
GList * terminal_app_get_profile_list (TerminalApp *app)
TerminalProfile * terminal_app_get_profile_by_name (TerminalApp *app, const char *name)
TerminalProfile * terminal_app_get_profile_by_visible_name (TerminalApp *app, const char *name)
TerminalProfile * terminal_app_get_default_profile (TerminalApp *app)
TerminalProfile * terminal_app_get_profile_for_new_term (TerminalApp *app)
GHashTable * terminal_app_get_encodings (TerminalApp *app)
TerminalEncoding * terminal_app_ensure_encoding (TerminalApp *app, const char *charset)
GSList * terminal_app_get_active_encodings (TerminalApp *app)
void terminal_app_save_config (TerminalApp *app, GKeyFile *key_file)
gboolean terminal_app_save_config_file (TerminalApp *app, const char *file_name, GError **error)
Variables
GSettings * settings_global
Macro Definition Documentation
DEFAULT_ENABLE_MENU_BAR_ACCEL
#define DEFAULT_ENABLE_MENU_BAR_ACCEL (TRUE)
Definition at line 153 of file terminal-app.c.
DEFAULT_ENABLE_MNEMONICS
#define DEFAULT_ENABLE_MNEMONICS (TRUE)
Definition at line 150 of file terminal-app.c.
DEFAULT_MONOSPACE_FONT
#define DEFAULT_MONOSPACE_FONT ("Monospace 10")
Definition at line 147 of file terminal-app.c.
DEFAULT_PROFILE_KEY
#define DEFAULT_PROFILE_KEY "default-profile"
Definition at line 156 of file terminal-app.c.
ENABLE_MENU_BAR_ACCEL_KEY
#define ENABLE_MENU_BAR_ACCEL_KEY "use-menu-accelerators"
Definition at line 152 of file terminal-app.c.
ENABLE_MNEMONICS_KEY
#define ENABLE_MNEMONICS_KEY "use-mnemonics"
Definition at line 149 of file terminal-app.c.
ENCODING_LIST_KEY
#define ENCODING_LIST_KEY "active-encodings"
Definition at line 158 of file terminal-app.c.
FALLBACK_PROFILE_ID
#define FALLBACK_PROFILE_ID "default"
Definition at line 49 of file terminal-app.c.
MONOSPACE_FONT_KEY
#define MONOSPACE_FONT_KEY "monospace-font-name"
Definition at line 146 of file terminal-app.c.
MONOSPACE_FONT_SCHEMA
#define MONOSPACE_FONT_SCHEMA "org.mate.interface"
Definition at line 145 of file terminal-app.c.
PROFILE_LIST_KEY
#define PROFILE_LIST_KEY "profile-list"
Definition at line 155 of file terminal-app.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_DEFAULT_PROFILE
PROP_ENABLE_MENU_BAR_ACCEL
PROP_ENABLE_MNEMONICS
PROP_SYSTEM_FONT
Definition at line 112 of file terminal-app.c.
anonymous enum
anonymous enum
Enumerator
QUIT
PROFILE_LIST_CHANGED
ENCODING_LIST_CHANGED
LAST_SIGNAL
Definition at line 121 of file terminal-app.c.
anonymous enum
anonymous enum
Enumerator
COL_PROFILE
NUM_COLUMNS
Definition at line 131 of file terminal-app.c.
anonymous enum
anonymous enum
Enumerator
SOURCE_DEFAULT
SOURCE_SESSION
Definition at line 137 of file terminal-app.c.
Function Documentation
terminal_app_edit_encodings()
void terminal_app_edit_encodings (TerminalApp * app, GtkWindow * transient_parent)
Definition at line 1936 of file terminal-app.c.
References terminal_encoding_dialog_show().
terminal_app_edit_keybindings()
void terminal_app_edit_keybindings (TerminalApp * app, GtkWindow * transient_parent)
Definition at line 1929 of file terminal-app.c.
References terminal_edit_keys_dialog_show().
terminal_app_edit_profile()
void terminal_app_edit_profile (TerminalApp * app, TerminalProfile * profile, GtkWindow * transient_parent, const char * widget_name)
Definition at line 1920 of file terminal-app.c.
References terminal_profile_edit().
terminal_app_ensure_encoding()
TerminalEncoding * terminal_app_ensure_encoding (TerminalApp * app, const char * charset)
terminal_app_ensure_encoding: @app: @charset:
Ensures there's a TerminalEncoding for @charset available.
Definition at line 2064 of file terminal-app.c.
References _, charset, NULL, terminal_encoding_get_id(), terminal_encoding_new(), and TRUE.
terminal_app_get()
TerminalApp * terminal_app_get (void)
Definition at line 1677 of file terminal-app.c.
References NULL, and TERMINAL_TYPE_APP.
Referenced by _terminal_profile_clone(), main(), terminal_edit_keys_dialog_show(), terminal_encoding_dialog_show(), and terminal_screen_set_font().
terminal_app_get_active_encodings()
GSList * terminal_app_get_active_encodings (TerminalApp * app)
terminal_app_get_active_encodings:
Returns: a newly allocated list of newly referenced TerminalEncoding objects.
Definition at line 2090 of file terminal-app.c.
References TerminalEncoding::is_active, key, NULL, and terminal_encoding_ref().
terminal_app_get_current_window()
TerminalWindow * terminal_app_get_current_window (TerminalApp * app, GdkScreen * from_screen, int workspace)
Definition at line 1947 of file terminal-app.c.
References NULL, TERMINAL_WINDOW, and terminal_window_get_latest_focused().
Referenced by terminal_app_handle_options().
terminal_app_get_default_profile()
TerminalProfile * terminal_app_get_default_profile (TerminalApp * app)
Definition at line 2024 of file terminal-app.c.
References NULL, and TERMINAL_IS_APP.
terminal_app_get_encodings()
GHashTable * terminal_app_get_encodings (TerminalApp * app)
Definition at line 2051 of file terminal-app.c.
terminal_app_get_profile_by_name()
TerminalProfile * terminal_app_get_profile_by_name (TerminalApp * app, const char * name)
Definition at line 1996 of file terminal-app.c.
References name, NULL, and TERMINAL_IS_APP.
Referenced by _terminal_profile_clone(), and terminal_app_handle_options().
terminal_app_get_profile_by_visible_name()
TerminalProfile * terminal_app_get_profile_by_visible_name (TerminalApp * app, const char * name)
Definition at line 2006 of file terminal-app.c.
References name, NULL, and TERMINAL_IS_APP.
Referenced by terminal_app_handle_options().
terminal_app_get_profile_for_new_term()
TerminalProfile * terminal_app_get_profile_for_new_term (TerminalApp * app)
Definition at line 2032 of file terminal-app.c.
References NULL, and TERMINAL_IS_APP.
Referenced by terminal_app_handle_options().
terminal_app_get_profile_list()
GList * terminal_app_get_profile_list (TerminalApp * app)
terminal_profile_get_list:
Returns: a #GList containing all TerminalProfile objects. The content of the list is owned by the backend and should not be modified or freed. Use g_list_free() when done using the list.
Definition at line 1988 of file terminal-app.c.
References NULL, and TERMINAL_IS_APP.
terminal_app_handle_options()
gboolean terminal_app_handle_options (TerminalApp * app, TerminalOptions * options, gboolean allow_resume, GError ** error)
terminal_app_handle_options: @app: @options: a TerminalOptions @allow_resume: whether to merge the terminal configuration from the saved session on resume @error: a #GError to fill in
Processes @options. It loads or saves the terminal configuration, or opens the specified windows and tabs.
Returns: TRUE if @options could be successfully handled, or FALSE on error
Definition at line 1713 of file terminal-app.c.
References _, InitialTab::active, TerminalOptions::config_file, TerminalOptions::default_profile, TerminalOptions::default_profile_is_id, TerminalOptions::default_title, TerminalOptions::default_working_dir, TerminalOptions::display_name, egg_sm_client_get(), egg_sm_client_get_state_file(), egg_sm_client_is_resumed(), TerminalOptions::env, error, TerminalOptions::exec_argv, InitialTab::exec_argv, FALSE, InitialWindow::force_menubar_state, InitialWindow::geometry, InitialWindow::icon, TerminalOptions::initial_windows, TerminalOptions::initial_workspace, TerminalOptions::load_config, InitialWindow::menubar_state, NULL, InitialTab::profile, InitialTab::profile_is_id, TerminalOptions::remote_arguments, InitialWindow::role, TerminalOptions::save_config, SOURCE_DEFAULT, SOURCE_SESSION, InitialWindow::source_tag, InitialWindow::start_fullscreen, InitialWindow::start_maximized, TerminalOptions::startup_id, InitialWindow::tabs, terminal_app_get_current_window(), terminal_app_get_profile_by_name(), terminal_app_get_profile_by_visible_name(), terminal_app_get_profile_for_new_term(), terminal_app_new_terminal(), terminal_app_new_window(), terminal_app_save_config_file(), TERMINAL_DEBUG_FACTORY, TERMINAL_DEBUG_GEOMETRY, TERMINAL_OPTION_ERROR, TERMINAL_OPTION_ERROR_NOT_IN_FACTORY, terminal_options_ensure_window(), terminal_options_merge_config(), terminal_window_get_active(), terminal_window_set_icon(), terminal_window_set_is_restored(), terminal_window_set_menubar_visible(), terminal_window_switch_screen(), terminal_window_update_size_set_geometry(), InitialTab::title, TRUE, InitialTab::working_dir, TerminalOptions::zoom, InitialTab::zoom, and InitialTab::zoom_set.
Referenced by main().
terminal_app_manage_profiles()
void terminal_app_manage_profiles (TerminalApp * app, GtkWindow * transient_parent)
Definition at line 1303 of file terminal-app.c.
References FALSE, NULL, and terminal_util_load_builder_resource().
terminal_app_new_profile()
void terminal_app_new_profile (TerminalApp * app, TerminalProfile * default_base_profile, GtkWindow * transient_parent)
Definition at line 1207 of file terminal-app.c.
References _, FALSE, NULL, terminal_util_load_builder_resource(), terminal_util_set_atk_name_description(), and TRUE.
terminal_app_new_terminal()
TerminalScreen * terminal_app_new_terminal (TerminalApp * app, TerminalWindow * window, TerminalProfile * profile, char ** override_command, const char * title, const char * working_dir, char ** child_env, double zoom)
Definition at line 1895 of file terminal-app.c.
References NULL, TERMINAL_IS_APP, TERMINAL_IS_WINDOW, terminal_screen_new(), terminal_window_add_screen(), and terminal_window_switch_screen().
Referenced by terminal_app_handle_options().
terminal_app_new_window()
TerminalWindow * terminal_app_new_window (TerminalApp * app, GdkScreen * screen)
Definition at line 1877 of file terminal-app.c.
References terminal_window_new().
Referenced by terminal_app_handle_options().
terminal_app_save_config()
void terminal_app_save_config (TerminalApp * app, GKeyFile * key_file)
Definition at line 2111 of file terminal-app.c.
References FALSE, NULL, TERMINAL_CONFIG_COMPAT_VERSION, TERMINAL_CONFIG_GROUP, TERMINAL_CONFIG_PROP_COMPAT_VERSION, TERMINAL_CONFIG_PROP_VERSION, TERMINAL_CONFIG_PROP_WINDOWS, TERMINAL_CONFIG_VERSION, TERMINAL_WINDOW, and terminal_window_save_state().
Referenced by terminal_app_save_config_file().
terminal_app_save_config_file()
gboolean terminal_app_save_config_file (TerminalApp * app, const char * file_name, GError ** error)
Definition at line 2146 of file terminal-app.c.
References data, error, NULL, and terminal_app_save_config().
Referenced by terminal_app_handle_options().
terminal_app_shutdown()
void terminal_app_shutdown (void)
Definition at line 1689 of file terminal-app.c.
References NULL.
Referenced by main().
Variable Documentation
settings_global
GSettings* settings_global
Definition at line 73 of file terminal-app.c.