MATE Desktop Environment: terminal-options.c File Reference
terminal-options.c File Reference
#include <config.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <glib.h>
#include "terminal-options.h"
#include "terminal-screen.h"
#include "terminal-app.h"
#include "terminal-intl.h"
#include "terminal-util.h"
Functions
TerminalOptions * terminal_options_parse (const char *working_directory, const char *display_name, const char *startup_id, char **env, gboolean remote_arguments, gboolean ignore_unknown_options, int *argcp, char ***argvp, GError **error,...)
gboolean terminal_options_merge_config (TerminalOptions *options, GKeyFile *key_file, guint source_tag, GError **error)
void terminal_options_ensure_window (TerminalOptions *options)
void terminal_options_free (TerminalOptions *options)
Function Documentation
terminal_options_ensure_window()
void terminal_options_ensure_window (TerminalOptions * options)
terminal_options_ensure_window: @options:
Ensure that @options will contain at least one window to open.
Definition at line 936 of file terminal-options.c.
Referenced by terminal_app_handle_options().
terminal_options_free()
void terminal_options_free (TerminalOptions * options)
terminal_options_free: @options:
Frees @options.
Definition at line 948 of file terminal-options.c.
References TerminalOptions::default_geometry, TerminalOptions::default_icon, TerminalOptions::default_profile, TerminalOptions::default_role, TerminalOptions::default_title, TerminalOptions::default_working_dir, TerminalOptions::display_name, TerminalOptions::env, TerminalOptions::exec_argv, TerminalOptions::initial_windows, NULL, and TerminalOptions::startup_id.
Referenced by main(), and terminal_options_parse().
terminal_options_merge_config()
gboolean terminal_options_merge_config (TerminalOptions * options, GKeyFile * key_file, guint source_tag, GError ** error)
terminal_options_merge_config: @options: @key_file: a #GKeyFile containing to merge the options from @source_tag: a source_tag to use in new #InitialWindows @error: a #GError to fill in
Merges the saved options from @key_file into @options.
Returns: TRUE if @key_file was a valid key file containing a stored terminal configuration, or FALSE on error
Definition at line 822 of file terminal-options.c.
References _, error, InitialTab::exec_argv, FALSE, InitialWindow::force_menubar_state, InitialWindow::geometry, InitialWindow::icon, TerminalOptions::initial_windows, InitialWindow::menubar_state, NULL, InitialWindow::role, InitialWindow::start_fullscreen, InitialWindow::start_maximized, InitialWindow::tabs, TERMINAL_CONFIG_COMPAT_VERSION, TERMINAL_CONFIG_GROUP, TERMINAL_CONFIG_PROP_COMPAT_VERSION, TERMINAL_CONFIG_PROP_VERSION, TERMINAL_CONFIG_PROP_WINDOWS, TERMINAL_CONFIG_TERMINAL_PROP_COMMAND, TERMINAL_CONFIG_TERMINAL_PROP_PROFILE_ID, TERMINAL_CONFIG_TERMINAL_PROP_TITLE, TERMINAL_CONFIG_TERMINAL_PROP_WORKING_DIRECTORY, TERMINAL_CONFIG_WINDOW_PROP_FULLSCREEN, TERMINAL_CONFIG_WINDOW_PROP_GEOMETRY, TERMINAL_CONFIG_WINDOW_PROP_ICON, TERMINAL_CONFIG_WINDOW_PROP_MAXIMIZED, TERMINAL_CONFIG_WINDOW_PROP_MENUBAR_VISIBLE, TERMINAL_CONFIG_WINDOW_PROP_ROLE, TERMINAL_CONFIG_WINDOW_PROP_TABS, TERMINAL_OPTION_ERROR, TERMINAL_OPTION_ERROR_INCOMPATIBLE_CONFIG_FILE, TERMINAL_OPTION_ERROR_INVALID_CONFIG_FILE, terminal_util_key_file_get_argv(), terminal_util_key_file_get_string_unescape(), InitialTab::title, TRUE, and InitialTab::working_dir.
Referenced by terminal_app_handle_options().
terminal_options_parse()
TerminalOptions * terminal_options_parse (const char * working_directory, const char * display_name, const char * startup_id, char ** env, gboolean remote_arguments, gboolean ignore_unknown_options, int * argcp, char *** argvp, GError ** error, ...)
terminal_options_parse: @working_directory: the default working directory @display_name: the default X display name @startup_id: the startup notification ID @env: the environment as variable=value pairs @remote_arguments: whether the caller is the factory process or not @ignore_unknown_options: whether to ignore unknown options when parsing the arguments @argcp: (inout) address of the argument count. Changed if any arguments were handled @argvp: (inout) address of the argument vector. Any parameters understood by the terminal #GOptionContext are removed @error: a #GError to fill in ...: a NULL terminated list of extra #GOptionGroups
Parses the argument vector *@argvp.
Returns: a new TerminalOptions containing the windows and tabs to open, or NULL on error.
Definition at line 711 of file terminal-options.c.
References TerminalOptions::default_fullscreen, TerminalOptions::default_geometry, TerminalOptions::default_icon, TerminalOptions::default_maximize, TerminalOptions::default_role, TerminalOptions::default_title, TerminalOptions::default_window_menubar_forced, TerminalOptions::default_window_menubar_state, TerminalOptions::default_working_dir, TerminalOptions::display_name, TerminalOptions::env, error, TerminalOptions::exec_argv, TerminalOptions::execute, FALSE, TerminalOptions::initial_windows, TerminalOptions::initial_workspace, NULL, TerminalOptions::remote_arguments, TerminalOptions::startup_id, terminal_options_free(), TRUE, TerminalOptions::use_factory, and TerminalOptions::zoom.
Referenced by main().