MATE Desktop Environment: terminal-util.h File Reference
terminal-util.h File Reference
#include <gtk/gtk.h>
#include "terminal-screen.h"
Macros
#define CONF_PROXY_SCHEMA "org.gnome.system.proxy"
#define CONF_HTTP_PROXY_SCHEMA "org.gnome.system.proxy.http"
#define CONF_HTTPS_PROXY_SCHEMA "org.gnome.system.proxy.https"
#define CONF_FTP_PROXY_SCHEMA "org.gnome.system.proxy.ftp"
#define CONF_SOCKS_PROXY_SCHEMA "org.gnome.system.proxy.socks"
Enumerations
enum PropertyChangeFlags { FLAG_INVERT_BOOL = 1 << 0 }
Functions
void terminal_util_set_unique_role (GtkWindow *window, const char *prefix)
void terminal_util_show_error_dialog (GtkWindow *transient_parent, GtkWidget **weap_ptr, GError *error, const char *message_format,...)
void terminal_util_show_help (const char *topic, GtkWindow *transient_parent)
void terminal_util_set_labelled_by (GtkWidget *widget, GtkLabel *label)
void terminal_util_set_atk_name_description (GtkWidget *widget, const char *name, const char *desc)
void terminal_util_open_url (GtkWidget *parent, const char *orig_url, TerminalURLFlavor flavor, guint32 user_time)
char * terminal_util_resolve_relative_path (const char *path, const char *relative_path)
void terminal_util_transform_uris_to_quoted_fuse_paths (char **uris)
char * terminal_util_concat_uris (char **uris, gsize *length)
char * terminal_util_get_licence_text (void)
gboolean terminal_util_load_builder_resource (const char *path, const char *object_name,...)
gboolean terminal_util_dialog_response_on_delete (GtkWindow *widget)
void terminal_util_key_file_set_string_escape (GKeyFile *key_file, const char *group, const char *key, const char *string)
char * terminal_util_key_file_get_string_unescape (GKeyFile *key_file, const char *group, const char *key, GError **error)
void terminal_util_key_file_set_argv (GKeyFile *key_file, const char *group, const char *key, int argc, char **argv)
char ** terminal_util_key_file_get_argv (GKeyFile *key_file, const char *group, const char *key, int *argc, GError **error)
void terminal_util_add_proxy_env (GHashTable *env_table)
void terminal_util_bind_object_property_to_widget (GObject *object, const char *object_prop, GtkWidget *widget, PropertyChangeFlags flags)
void terminal_util_x11_clear_demands_attention (GdkWindow *window)
char * terminal_util_hyperlink_uri_label (const char *str)
Macro Definition Documentation
CONF_FTP_PROXY_SCHEMA
#define CONF_FTP_PROXY_SCHEMA "org.gnome.system.proxy.ftp"
Definition at line 34 of file terminal-util.h.
CONF_HTTP_PROXY_SCHEMA
#define CONF_HTTP_PROXY_SCHEMA "org.gnome.system.proxy.http"
Definition at line 32 of file terminal-util.h.
CONF_HTTPS_PROXY_SCHEMA
#define CONF_HTTPS_PROXY_SCHEMA "org.gnome.system.proxy.https"
Definition at line 33 of file terminal-util.h.
CONF_PROXY_SCHEMA
#define CONF_PROXY_SCHEMA "org.gnome.system.proxy"
Definition at line 31 of file terminal-util.h.
CONF_SOCKS_PROXY_SCHEMA
#define CONF_SOCKS_PROXY_SCHEMA "org.gnome.system.proxy.socks"
Definition at line 35 of file terminal-util.h.
Enumeration Type Documentation
PropertyChangeFlags
enum PropertyChangeFlags
Enumerator
FLAG_INVERT_BOOL
Definition at line 95 of file terminal-util.h.
Function Documentation
terminal_util_add_proxy_env()
void terminal_util_add_proxy_env (GHashTable * env_table)
terminal_util_add_proxy_env: @env_table: a #GHashTable
Adds the proxy env variables to @env_table.
Definition at line 679 of file terminal-util.c.
References CONF_FTP_PROXY_SCHEMA, CONF_HTTP_PROXY_SCHEMA, CONF_HTTPS_PROXY_SCHEMA, CONF_PROXY_SCHEMA, and CONF_SOCKS_PROXY_SCHEMA.
terminal_util_bind_object_property_to_widget()
void terminal_util_bind_object_property_to_widget (GObject * object, const char * object_prop, GtkWidget * widget, PropertyChangeFlags flags)
Definition at line 1001 of file terminal-util.c.
References NULL.
Referenced by terminal_edit_keys_dialog_show().
terminal_util_concat_uris()
char * terminal_util_concat_uris (char ** uris, gsize * length)
Definition at line 297 of file terminal-util.c.
References FALSE.
terminal_util_dialog_response_on_delete()
gboolean terminal_util_dialog_response_on_delete (GtkWindow * widget)
Definition at line 379 of file terminal-util.c.
References TRUE.
Referenced by terminal_skey_do_popup().
terminal_util_get_licence_text()
char * terminal_util_get_licence_text (void)
Definition at line 322 of file terminal-util.c.
References _, N_, and NULL.
terminal_util_hyperlink_uri_label()
char * terminal_util_hyperlink_uri_label (const char * uri)
terminal_util_hyperlink_uri_label: @uri: a URI
Formats @uri to be displayed in a tooltip. Performs URI-decoding and converts IDN hostname to UTF-8.
Returns: (transfer full): The human readable URI as plain text
Definition at line 720 of file terminal-util.c.
References NULL, and strchr.
terminal_util_key_file_get_argv()
char ** terminal_util_key_file_get_argv (GKeyFile * key_file, const char * group, const char * key, int * argc, GError ** error)
Definition at line 448 of file terminal-util.c.
References error, key, NULL, and terminal_util_key_file_get_string_unescape().
Referenced by terminal_options_merge_config().
terminal_util_key_file_get_string_unescape()
char * terminal_util_key_file_get_string_unescape (GKeyFile * key_file, const char * group, const char * key, GError ** error)
Definition at line 404 of file terminal-util.c.
References error, key, and NULL.
Referenced by terminal_options_merge_config(), and terminal_util_key_file_get_argv().
terminal_util_key_file_set_argv()
void terminal_util_key_file_set_argv (GKeyFile * key_file, const char * group, const char * key, int argc, char ** argv)
Definition at line 422 of file terminal-util.c.
References key, NULL, and terminal_util_key_file_set_string_escape().
Referenced by terminal_screen_save_config().
terminal_util_key_file_set_string_escape()
void terminal_util_key_file_set_string_escape (GKeyFile * key_file, const char * group, const char * key, const char * string)
Definition at line 390 of file terminal-util.c.
References key, and NULL.
Referenced by terminal_screen_save_config(), and terminal_util_key_file_set_argv().
terminal_util_load_builder_resource()
gboolean terminal_util_load_builder_resource (const char * path, const char * object_name, ...)
Definition at line 343 of file terminal-util.c.
References error, and NULL.
Referenced by terminal_app_manage_profiles(), terminal_app_new_profile(), terminal_edit_keys_dialog_show(), terminal_encoding_dialog_show(), terminal_search_dialog_new(), and terminal_skey_do_popup().
terminal_util_open_url()
void terminal_util_open_url (GtkWidget * parent, const char * orig_url, TerminalURLFlavor flavor, guint32 user_time)
Definition at line 183 of file terminal-util.c.
References _, error, FLAVOR_AS_IS, FLAVOR_DEFAULT_TO_HTTP, FLAVOR_EMAIL, FLAVOR_SKEY, FLAVOR_VOIP_CALL, NULL, and terminal_util_show_error_dialog().
terminal_util_resolve_relative_path()
char * terminal_util_resolve_relative_path (const char * path, const char * relative_path)
terminal_util_resolve_relative_path: @path: @relative_path:
Returns: a newly allocate string
Definition at line 235 of file terminal-util.c.
References NULL.
terminal_util_set_atk_name_description()
void terminal_util_set_atk_name_description (GtkWidget * widget, const char * name, const char * desc)
Definition at line 157 of file terminal-util.c.
References name, and NULL.
Referenced by terminal_app_new_profile().
terminal_util_set_labelled_by()
void terminal_util_set_labelled_by (GtkWidget * widget, GtkLabel * label)
terminal_util_set_unique_role()
void terminal_util_set_unique_role (GtkWindow * window, const char * prefix)
Definition at line 48 of file terminal-util.c.
References prefix.
terminal_util_show_error_dialog()
void terminal_util_show_error_dialog (GtkWindow * transient_parent, GtkWidget ** weak_ptr, GError * error, const char * message_format, ...)
terminal_util_show_error_dialog: @transient_parent: parent of the future dialog window; @weap_ptr: pointer to a #Widget pointer, to control the population. @error: a #GError, or NULL @message_format: printf() style format string
Create a #GtkMessageDialog window with the message, and present it, handling its buttons. If @weap_ptr is not NULL, only create the dialog if <literal>*weap_ptr</literal> is NULL (and in that * case, set @weap_ptr to be a weak pointer to the new dialog), otherwise just present <literal>*weak_ptr</literal>. Note that in this last case, the message <emph>will</emph> be changed.
Definition at line 72 of file terminal-util.c.
References error, FALSE, message(), and NULL.
Referenced by terminal_skey_do_popup(), terminal_util_open_url(), and terminal_util_show_help().
terminal_util_show_help()
void terminal_util_show_help (const char * topic, GtkWindow * transient_parent)
Definition at line 129 of file terminal-util.c.
References _, error, NULL, and terminal_util_show_error_dialog().
terminal_util_transform_uris_to_quoted_fuse_paths()
void terminal_util_transform_uris_to_quoted_fuse_paths (char ** uris)
terminal_util_transform_uris_to_quoted_fuse_paths: @uris:
Transforms those URIs in @uris to shell-quoted paths that point to GIO fuse paths.
Definition at line 267 of file terminal-util.c.
terminal_util_x11_clear_demands_attention()
void terminal_util_x11_clear_demands_attention (GdkWindow * window)