MATE Desktop Environment: terminal-screen-container.h File Reference
terminal-screen-container.h File Reference
#include <gtk/gtk.h>
#include "terminal-screen.h"
Classes
struct _TerminalScreenContainer
struct _TerminalScreenContainerClass
Macros
#define TERMINAL_TYPE_SCREEN_CONTAINER (terminal_screen_container_get_type ())
#define TERMINAL_SCREEN_CONTAINER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TERMINAL_TYPE_SCREEN_CONTAINER, TerminalScreenContainer))
#define TERMINAL_SCREEN_CONTAINER_CLASS(k) (G_TYPE_CHECK_CLASS_CAST((k), TERMINAL_TYPE_SCREEN_CONTAINER, TerminalScreenContainerClass))
#define TERMINAL_IS_SCREEN_CONTAINER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TERMINAL_TYPE_SCREEN_CONTAINER))
#define TERMINAL_IS_SCREEN_CONTAINER_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TERMINAL_TYPE_SCREEN_CONTAINER))
#define TERMINAL_SCREEN_CONTAINER_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TERMINAL_TYPE_SCREEN_CONTAINER, TerminalScreenContainerClass))
Typedefs
typedef struct _TerminalScreenContainer TerminalScreenContainer
typedef struct _TerminalScreenContainerClass TerminalScreenContainerClass
typedef struct _TerminalScreenContainerPrivate TerminalScreenContainerPrivate
Functions
GType terminal_screen_container_get_type (void)
GtkWidget * terminal_screen_container_new (TerminalScreen *screen)
TerminalScreen * terminal_screen_container_get_screen (TerminalScreenContainer *container)
TerminalScreenContainer * terminal_screen_container_get_from_screen (TerminalScreen *screen)
void terminal_screen_container_set_policy (TerminalScreenContainer *container, GtkPolicyType hpolicy, GtkPolicyType vpolicy)
void terminal_screen_container_set_placement (TerminalScreenContainer *container, GtkCornerType corner)
Macro Definition Documentation
TERMINAL_IS_SCREEN_CONTAINER
#define TERMINAL_IS_SCREEN_CONTAINER (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TERMINAL_TYPE_SCREEN_CONTAINER))
Definition at line 32 of file terminal-screen-container.h.
TERMINAL_IS_SCREEN_CONTAINER_CLASS
#define TERMINAL_IS_SCREEN_CONTAINER_CLASS (k) (G_TYPE_CHECK_CLASS_TYPE ((k), TERMINAL_TYPE_SCREEN_CONTAINER))
Definition at line 33 of file terminal-screen-container.h.
TERMINAL_SCREEN_CONTAINER
#define TERMINAL_SCREEN_CONTAINER (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TERMINAL_TYPE_SCREEN_CONTAINER, TerminalScreenContainer))
Definition at line 30 of file terminal-screen-container.h.
TERMINAL_SCREEN_CONTAINER_CLASS
#define TERMINAL_SCREEN_CONTAINER_CLASS (k) (G_TYPE_CHECK_CLASS_CAST((k), TERMINAL_TYPE_SCREEN_CONTAINER, TerminalScreenContainerClass))
Definition at line 31 of file terminal-screen-container.h.
TERMINAL_SCREEN_CONTAINER_GET_CLASS
#define TERMINAL_SCREEN_CONTAINER_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), TERMINAL_TYPE_SCREEN_CONTAINER, TerminalScreenContainerClass))
Definition at line 34 of file terminal-screen-container.h.
TERMINAL_TYPE_SCREEN_CONTAINER
#define TERMINAL_TYPE_SCREEN_CONTAINER (terminal_screen_container_get_type ())
Definition at line 29 of file terminal-screen-container.h.
Typedef Documentation
TerminalScreenContainer
typedef struct _TerminalScreenContainer TerminalScreenContainer
Definition at line 36 of file terminal-screen-container.h.
TerminalScreenContainerClass
typedef struct _TerminalScreenContainerClass TerminalScreenContainerClass
Definition at line 37 of file terminal-screen-container.h.
TerminalScreenContainerPrivate
typedef struct _TerminalScreenContainerPrivate TerminalScreenContainerPrivate
Definition at line 38 of file terminal-screen-container.h.
Function Documentation
terminal_screen_container_get_from_screen()
TerminalScreenContainer * terminal_screen_container_get_from_screen (TerminalScreen * screen)
terminal_screen_container_get_from_screen: @screen: a TerminalScreenContainerPrivate
Returns the TerminalScreenContainer containing @screen.
Definition at line 338 of file terminal-screen-container.c.
References NULL, TERMINAL_IS_SCREEN, TERMINAL_SCREEN_CONTAINER, and TERMINAL_TYPE_SCREEN_CONTAINER.
Referenced by _terminal_screen_update_scrollbar(), terminal_window_move_screen(), terminal_window_remove_screen(), and terminal_window_switch_screen().
terminal_screen_container_get_screen()
TerminalScreen * terminal_screen_container_get_screen (TerminalScreenContainer * container)
terminal_screen_container_get_screen: @container: a TerminalScreenContainer
Returns: @container's TerminalScreen
Definition at line 324 of file terminal-screen-container.c.
References NULL, _TerminalScreenContainer::priv, and TERMINAL_IS_SCREEN_CONTAINER.
Referenced by terminal_window_save_state().
terminal_screen_container_get_type()
GType terminal_screen_container_get_type (void)
terminal_screen_container_new()
GtkWidget * terminal_screen_container_new (TerminalScreen * screen)
terminal_screen_container_new: @screen: a TerminalScreen
Returns: a new TerminalScreenContainer for @screen
Definition at line 310 of file terminal-screen-container.c.
References NULL, and TERMINAL_TYPE_SCREEN_CONTAINER.
Referenced by terminal_window_add_screen().
terminal_screen_container_set_placement()
void terminal_screen_container_set_placement (TerminalScreenContainer * container, GtkCornerType corner)
terminal_screen_container_set_placement: @container: a TerminalScreenContainer @corner: a #GtkCornerType
Sets @container's window placement.
Definition at line 407 of file terminal-screen-container.c.
References TERMINAL_IS_SCREEN_CONTAINER, and TRUE.
Referenced by _terminal_screen_update_scrollbar().
terminal_screen_container_set_policy()
void terminal_screen_container_set_policy (TerminalScreenContainer * container, GtkPolicyType hpolicy G_GNUC_UNUSED, GtkPolicyType vpolicy)
terminal_screen_container_set_policy: @container: a TerminalScreenContainer @hpolicy: a #GtkPolicyType @vpolicy: a #GtkPolicyType
Sets @container's scrollbar policy.
Definition at line 354 of file terminal-screen-container.c.
References _TerminalScreenContainer::priv, and TERMINAL_IS_SCREEN_CONTAINER.
Referenced by _terminal_screen_update_scrollbar().