MATE Desktop Environment: terminal-encoding.c File Reference
terminal-encoding.c File Reference
#include <config.h>
#include <string.h>
#include <gtk/gtk.h>
#include "terminal-app.h"
#include "terminal-debug.h"
#include "terminal-encoding.h"
#include "terminal-intl.h"
#include "terminal-profile.h"
#include "terminal-util.h"
Enumerations
enum { COLUMN_NAME , COLUMN_CHARSET , COLUMN_DATA , N_COLUMNS }
Functions
TerminalEncoding * terminal_encoding_new (const char *charset, const char *display_name, gboolean is_custom, gboolean force_valid)
TerminalEncoding * terminal_encoding_ref (TerminalEncoding *encoding)
void terminal_encoding_unref (TerminalEncoding *encoding)
const char * terminal_encoding_get_id (TerminalEncoding *encoding)
const char * terminal_encoding_get_charset (TerminalEncoding *encoding)
gboolean terminal_encoding_is_valid (TerminalEncoding *encoding)
GType terminal_encoding_get_type (void)
void terminal_encoding_dialog_show (GtkWindow *transient_parent)
GHashTable * terminal_encodings_get_builtins (void)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COLUMN_NAME
COLUMN_CHARSET
COLUMN_DATA
N_COLUMNS
Definition at line 323 of file terminal-encoding.c.
Function Documentation
terminal_encoding_dialog_show()
void terminal_encoding_dialog_show (GtkWindow * transient_parent)
Definition at line 458 of file terminal-encoding.c.
References _, COLUMN_CHARSET, COLUMN_NAME, data, FALSE, N_COLUMNS, NULL, terminal_app_get(), TERMINAL_TYPE_ENCODING, terminal_util_load_builder_resource(), and TRUE.
Referenced by terminal_app_edit_encodings().
terminal_encoding_get_charset()
const char * terminal_encoding_get_charset (TerminalEncoding * encoding)
Definition at line 198 of file terminal-encoding.c.
References charset, TerminalEncoding::id, and NULL.
Referenced by terminal_encoding_is_valid().
terminal_encoding_get_id()
const char * terminal_encoding_get_id (TerminalEncoding * encoding)
Definition at line 190 of file terminal-encoding.c.
References TerminalEncoding::id, and NULL.
Referenced by terminal_app_ensure_encoding(), and terminal_encodings_get_builtins().
terminal_encoding_get_type()
GType terminal_encoding_get_type (void)
Definition at line 274 of file terminal-encoding.c.
References I_, terminal_encoding_ref(), terminal_encoding_unref(), and type.
terminal_encoding_is_valid()
gboolean terminal_encoding_is_valid (TerminalEncoding * encoding)
Definition at line 214 of file terminal-encoding.c.
References _TERMINAL_DEBUG_IF, error, NULL, TERMINAL_DEBUG_ENCODINGS, terminal_encoding_get_charset(), TRUE, TerminalEncoding::valid, and TerminalEncoding::validity_checked.
terminal_encoding_new()
TerminalEncoding * terminal_encoding_new (const char * charset, const char * display_name, gboolean is_custom, gboolean force_valid)
Definition at line 151 of file terminal-encoding.c.
References charset, FALSE, TerminalEncoding::id, TerminalEncoding::is_active, TerminalEncoding::is_custom, TerminalEncoding::name, TerminalEncoding::refcount, TerminalEncoding::valid, and TerminalEncoding::validity_checked.
Referenced by terminal_app_ensure_encoding(), and terminal_encodings_get_builtins().
terminal_encoding_ref()
TerminalEncoding * terminal_encoding_ref (TerminalEncoding * encoding)
Definition at line 170 of file terminal-encoding.c.
References NULL, and TerminalEncoding::refcount.
Referenced by terminal_app_get_active_encodings(), and terminal_encoding_get_type().
terminal_encoding_unref()
void terminal_encoding_unref (TerminalEncoding * encoding)
Definition at line 179 of file terminal-encoding.c.
References TerminalEncoding::id, TerminalEncoding::name, and TerminalEncoding::refcount.
Referenced by terminal_encoding_get_type(), and terminal_encodings_get_builtins().
terminal_encodings_get_builtins()
GHashTable * terminal_encodings_get_builtins (void)
Definition at line 583 of file terminal-encoding.c.
References _, charset, FALSE, name, NULL, terminal_encoding_get_id(), terminal_encoding_new(), terminal_encoding_unref(), and TRUE.
Variable Documentation
charset
const char* charset
Definition at line 50 of file terminal-encoding.c.
Referenced by _pluma_encoding_list_to_strv(), _pluma_encoding_strv_to_list(), pluma_encoding_get_from_charset(), terminal_app_ensure_encoding(), terminal_encoding_get_charset(), terminal_encoding_new(), and terminal_encodings_get_builtins().
name
const char* name
Definition at line 51 of file terminal-encoding.c.
Referenced by terminal_encodings_get_builtins().