MATE Desktop Environment: test-virtuals-without-test.c File Reference
test-virtuals-without-test.c File Reference
#include <glib-object.h>
#include <glib.h>
Macros
#define PWI_FIRST_TYPE (pwi_first_get_type())
#define PWI_FIRST(object) (G_TYPE_CHECK_INSTANCE_CAST(object, PWI_FIRST_TYPE, PwiFirst))
#define PWI_FIRST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, PWI_FIRST_TYPE, PwiFirstClass))
#define PWI_IS_FIRST(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, PWI_FIRST_TYPE))
#define PWI_IS_FIRST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), PWI_FIRST_TYPE))
#define PWI_FIRST_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), PWI_FIRST_TYPE, PwiFirstClass))
#define PWI_FIRST_SECOND_TYPE (pwi_first_second_get_type())
#define PWI_FIRST_SECOND(object) (G_TYPE_CHECK_INSTANCE_CAST(object, PWI_FIRST_SECOND_TYPE, PwiFirstSecond))
#define PWI_FIRST_SECOND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, PWI_FIRST_SECOND_TYPE, PwiFirstSecondClass))
#define PWI_IS_FIRST_SECOND(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, PWI_FIRST_SECOND_TYPE))
#define PWI_IS_FIRST_SECOND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), PWI_FIRST_SECOND_TYPE))
#define PWI_FIRST_SECOND_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), PWI_FIRST_SECOND_TYPE, PwiFirstSecondClass))
#define PWI_FIRST_SECOND_THREE_TYPE (pwi_first_second_three_get_type())
#define PWI_FIRST_SECOND_THREE(object) (G_TYPE_CHECK_INSTANCE_CAST(object, PWI_FIRST_SECOND_THREE_TYPE, PwiFirstSecondThree))
#define PWI_FIRST_SECOND_THREE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, PWI_FIRST_SECOND_THREE_TYPE, PwiFirstSecondThreeClass))
#define PWI_IS_FIRST_SECOND_THREE(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, PWI_FIRST_SECOND_THREE_TYPE))
#define PWI_IS_FIRST_SECOND_THREE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), PWI_FIRST_SECOND_THREE_TYPE))
#define PWI_FIRST_SECOND_THREE_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), PWI_FIRST_SECOND_THREE_TYPE, PwiFirstSecondThreeClass))
Typedefs
typedef struct PwiFirstPrivate PwiFirstPrivate
typedef struct PwiFirstClassPrivate PwiFirstClassPrivate
typedef struct PwiFirstSecondPrivate PwiFirstSecondPrivate
typedef struct PwiFirstSecondClassPrivate PwiFirstSecondClassPrivate
typedef struct PwiFirstSecondThreePrivate PwiFirstSecondThreePrivate
typedef struct PwiFirstSecondThreeClassPrivate PwiFirstSecondThreeClassPrivate
Functions
GType pwi_first_get_type (void)
void pwi_first_fn_a (PwiFirst *instance)
void pwi_first_fn_b (PwiFirst *instance)
void pwi_first_fn_c (PwiFirst *instance)
GType pwi_first_second_get_type (void)
GType pwi_first_second_three_get_type (void)
int main (int argc, char **argv)
Macro Definition Documentation
PWI_FIRST
#define PWI_FIRST (object) (G_TYPE_CHECK_INSTANCE_CAST(object, PWI_FIRST_TYPE, PwiFirst))
Definition at line 53 of file test-virtuals-without-test.c.
PWI_FIRST_CLASS
#define PWI_FIRST_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, PWI_FIRST_TYPE, PwiFirstClass))
Definition at line 54 of file test-virtuals-without-test.c.
PWI_FIRST_GET_CLASS
#define PWI_FIRST_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), PWI_FIRST_TYPE, PwiFirstClass))
Definition at line 57 of file test-virtuals-without-test.c.
PWI_FIRST_SECOND
#define PWI_FIRST_SECOND (object) (G_TYPE_CHECK_INSTANCE_CAST(object, PWI_FIRST_SECOND_TYPE, PwiFirstSecond))
Definition at line 87 of file test-virtuals-without-test.c.
PWI_FIRST_SECOND_CLASS
#define PWI_FIRST_SECOND_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, PWI_FIRST_SECOND_TYPE, PwiFirstSecondClass))
Definition at line 88 of file test-virtuals-without-test.c.
PWI_FIRST_SECOND_GET_CLASS
#define PWI_FIRST_SECOND_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), PWI_FIRST_SECOND_TYPE, PwiFirstSecondClass))
Definition at line 91 of file test-virtuals-without-test.c.
PWI_FIRST_SECOND_THREE
#define PWI_FIRST_SECOND_THREE (object) (G_TYPE_CHECK_INSTANCE_CAST(object, PWI_FIRST_SECOND_THREE_TYPE, PwiFirstSecondThree))
Definition at line 112 of file test-virtuals-without-test.c.
PWI_FIRST_SECOND_THREE_CLASS
#define PWI_FIRST_SECOND_THREE_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, PWI_FIRST_SECOND_THREE_TYPE, PwiFirstSecondThreeClass))
Definition at line 113 of file test-virtuals-without-test.c.
PWI_FIRST_SECOND_THREE_GET_CLASS
#define PWI_FIRST_SECOND_THREE_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), PWI_FIRST_SECOND_THREE_TYPE, PwiFirstSecondThreeClass))
Definition at line 116 of file test-virtuals-without-test.c.
PWI_FIRST_SECOND_THREE_TYPE
#define PWI_FIRST_SECOND_THREE_TYPE (pwi_first_second_three_get_type())
Definition at line 111 of file test-virtuals-without-test.c.
PWI_FIRST_SECOND_TYPE
#define PWI_FIRST_SECOND_TYPE (pwi_first_second_get_type())
Definition at line 86 of file test-virtuals-without-test.c.
PWI_FIRST_TYPE
#define PWI_FIRST_TYPE (pwi_first_get_type())
Definition at line 52 of file test-virtuals-without-test.c.
PWI_IS_FIRST
#define PWI_IS_FIRST (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, PWI_FIRST_TYPE))
Definition at line 55 of file test-virtuals-without-test.c.
PWI_IS_FIRST_CLASS
#define PWI_IS_FIRST_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), PWI_FIRST_TYPE))
Definition at line 56 of file test-virtuals-without-test.c.
PWI_IS_FIRST_SECOND
#define PWI_IS_FIRST_SECOND (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, PWI_FIRST_SECOND_TYPE))
Definition at line 89 of file test-virtuals-without-test.c.
PWI_IS_FIRST_SECOND_CLASS
#define PWI_IS_FIRST_SECOND_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), PWI_FIRST_SECOND_TYPE))
Definition at line 90 of file test-virtuals-without-test.c.
PWI_IS_FIRST_SECOND_THREE
#define PWI_IS_FIRST_SECOND_THREE (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, PWI_FIRST_SECOND_THREE_TYPE))
Definition at line 114 of file test-virtuals-without-test.c.
PWI_IS_FIRST_SECOND_THREE_CLASS
#define PWI_IS_FIRST_SECOND_THREE_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), PWI_FIRST_SECOND_THREE_TYPE))
Definition at line 115 of file test-virtuals-without-test.c.
Typedef Documentation
PwiFirstClassPrivate
typedef struct PwiFirstClassPrivate PwiFirstClassPrivate
Definition at line 67 of file test-virtuals-without-test.c.
PwiFirstPrivate
typedef struct PwiFirstPrivate PwiFirstPrivate
Definition at line 59 of file test-virtuals-without-test.c.
PwiFirstSecondClassPrivate
typedef struct PwiFirstSecondClassPrivate PwiFirstSecondClassPrivate
Definition at line 101 of file test-virtuals-without-test.c.
PwiFirstSecondPrivate
typedef struct PwiFirstSecondPrivate PwiFirstSecondPrivate
Definition at line 93 of file test-virtuals-without-test.c.
PwiFirstSecondThreeClassPrivate
typedef struct PwiFirstSecondThreeClassPrivate PwiFirstSecondThreeClassPrivate
Definition at line 126 of file test-virtuals-without-test.c.
PwiFirstSecondThreePrivate
typedef struct PwiFirstSecondThreePrivate PwiFirstSecondThreePrivate
Definition at line 118 of file test-virtuals-without-test.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 557 of file test-virtuals-without-test.c.
References b, NULL, PWI_FIRST, pwi_first_fn_a(), pwi_first_fn_b(), pwi_first_fn_c(), PWI_FIRST_SECOND_THREE_TYPE, PWI_FIRST_SECOND_TYPE, and PWI_FIRST_TYPE.
pwi_first_fn_a()
void pwi_first_fn_a (PwiFirst * instance)
Definition at line 252 of file test-virtuals-without-test.c.
References PWI_FIRST_GET_CLASS, and PWI_IS_FIRST.
Referenced by main().
pwi_first_fn_b()
void pwi_first_fn_b (PwiFirst * instance)
Definition at line 267 of file test-virtuals-without-test.c.
References PWI_FIRST_GET_CLASS, and PWI_IS_FIRST.
Referenced by main().
pwi_first_fn_c()
void pwi_first_fn_c (PwiFirst * instance)
Definition at line 282 of file test-virtuals-without-test.c.
References PWI_FIRST_GET_CLASS, and PWI_IS_FIRST.
Referenced by main().
pwi_first_get_type()
static GType pwi_first_get_type (void)
Definition at line 157 of file test-virtuals-without-test.c.
References type.
pwi_first_second_get_type()
GType pwi_first_second_get_type (void)
Definition at line 316 of file test-virtuals-without-test.c.
References type.
pwi_first_second_three_get_type()
GType pwi_first_second_three_get_type (void)
Definition at line 446 of file test-virtuals-without-test.c.
References type.