MATE Desktop Environment: testiconlist.c File Reference
testiconlist.c File Reference
#include <gtk/gtk.h>
#include <libmateui.h>
Functions
gint main (gint argc, gchar **argv)
Function Documentation
main()
gint main (gint argc, gchar ** argv)
Definition at line 19 of file testiconlist.c.
References FALSE, LIBMATEUI_MODULE, MATE_ICON_LIST, mate_icon_list_append_pixbuf(), MATE_ICON_LIST_IS_EDITABLE, mate_icon_list_new(), mate_icon_list_set_selection_mode(), name, NULL, and TRUE.