MATE Desktop Environment: test-virtuals.c File Reference
test-virtuals.c File Reference
#include <glib-object.h>
#include <glib.h>
Macros
#define PWI_TYPE_FIRST (pwi_first_get_type())
#define PWI_FIRST(object) (G_TYPE_CHECK_INSTANCE_CAST(object, PWI_TYPE_FIRST, PwiFirst))
#define PWI_FIRST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, PWI_TYPE_FIRST, PwiFirstClass))
#define PWI_IS_FIRST(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, PWI_TYPE_FIRST))
#define PWI_IS_FIRST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), PWI_TYPE_FIRST))
#define PWI_FIRST_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), PWI_TYPE_FIRST, PwiFirstClass))
#define PWI_TYPE_SECOND (pwi_second_get_type())
#define PWI_SECOND(object) (G_TYPE_CHECK_INSTANCE_CAST(object, PWI_TYPE_SECOND, PwiSecond))
#define PWI_SECOND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, PWI_TYPE_SECOND, PwiSecondClass))
#define PWI_IS_SECOND(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, PWI_TYPE_SECOND))
#define PWI_IS_SECOND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), PWI_TYPE_SECOND))
#define PWI_SECOND_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), PWI_TYPE_SECOND, PwiSecondClass))
#define PWI_TYPE_THREE (pwi_three_get_type())
#define PWI_THREE(object) (G_TYPE_CHECK_INSTANCE_CAST(object, PWI_TYPE_THREE, PwiThree))
#define PWI_THREE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST(klass, PWI_TYPE_THREE, PwiThreeClass))
#define PWI_IS_THREE(object) (G_TYPE_CHECK_INSTANCE_TYPE(object, PWI_TYPE_THREE))
#define PWI_IS_THREE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), PWI_TYPE_THREE))
#define PWI_THREE_GET_CLASS(object) (G_TYPE_INSTANCE_GET_CLASS((object), PWI_TYPE_THREE, PwiThreeClass))
Functions
void pwi_first_fn_a (PwiFirst *instance)
void pwi_first_fn_b (PwiFirst *instance)
void pwi_first_fn_c (PwiFirst *instance)
int main (int argc, char **argv)
Macro Definition Documentation
PWI_FIRST
#define PWI_FIRST (object) (G_TYPE_CHECK_INSTANCE_CAST(object, PWI_TYPE_FIRST, PwiFirst))
Definition at line 54 of file test-virtuals.c.
PWI_FIRST_CLASS
#define PWI_FIRST_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, PWI_TYPE_FIRST, PwiFirstClass))
Definition at line 55 of file test-virtuals.c.
PWI_FIRST_GET_CLASS
#define PWI_FIRST_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), PWI_TYPE_FIRST, PwiFirstClass))
Definition at line 58 of file test-virtuals.c.
PWI_IS_FIRST
#define PWI_IS_FIRST (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, PWI_TYPE_FIRST))
Definition at line 56 of file test-virtuals.c.
PWI_IS_FIRST_CLASS
#define PWI_IS_FIRST_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), PWI_TYPE_FIRST))
Definition at line 57 of file test-virtuals.c.
PWI_IS_SECOND
#define PWI_IS_SECOND (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, PWI_TYPE_SECOND))
Definition at line 218 of file test-virtuals.c.
PWI_IS_SECOND_CLASS
#define PWI_IS_SECOND_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), PWI_TYPE_SECOND))
Definition at line 219 of file test-virtuals.c.
PWI_IS_THREE
#define PWI_IS_THREE (object) (G_TYPE_CHECK_INSTANCE_TYPE(object, PWI_TYPE_THREE))
Definition at line 331 of file test-virtuals.c.
PWI_IS_THREE_CLASS
#define PWI_IS_THREE_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE((klass), PWI_TYPE_THREE))
Definition at line 332 of file test-virtuals.c.
PWI_SECOND
#define PWI_SECOND (object) (G_TYPE_CHECK_INSTANCE_CAST(object, PWI_TYPE_SECOND, PwiSecond))
Definition at line 216 of file test-virtuals.c.
PWI_SECOND_CLASS
#define PWI_SECOND_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, PWI_TYPE_SECOND, PwiSecondClass))
Definition at line 217 of file test-virtuals.c.
PWI_SECOND_GET_CLASS
#define PWI_SECOND_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), PWI_TYPE_SECOND, PwiSecondClass))
Definition at line 220 of file test-virtuals.c.
PWI_THREE
#define PWI_THREE (object) (G_TYPE_CHECK_INSTANCE_CAST(object, PWI_TYPE_THREE, PwiThree))
Definition at line 329 of file test-virtuals.c.
PWI_THREE_CLASS
#define PWI_THREE_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST(klass, PWI_TYPE_THREE, PwiThreeClass))
Definition at line 330 of file test-virtuals.c.
PWI_THREE_GET_CLASS
#define PWI_THREE_GET_CLASS (object) (G_TYPE_INSTANCE_GET_CLASS((object), PWI_TYPE_THREE, PwiThreeClass))
Definition at line 333 of file test-virtuals.c.
PWI_TYPE_FIRST
#define PWI_TYPE_FIRST (pwi_first_get_type())
Definition at line 53 of file test-virtuals.c.
PWI_TYPE_SECOND
#define PWI_TYPE_SECOND (pwi_second_get_type())
Definition at line 215 of file test-virtuals.c.
PWI_TYPE_THREE
#define PWI_TYPE_THREE (pwi_three_get_type())
Definition at line 328 of file test-virtuals.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 442 of file test-virtuals.c.
References b, NULL, PWI_FIRST, pwi_first_fn_a(), pwi_first_fn_b(), pwi_first_fn_c(), PWI_TYPE_FIRST, PWI_TYPE_SECOND, and PWI_TYPE_THREE.
pwi_first_fn_a()
void pwi_first_fn_a (PwiFirst * instance)
Definition at line 174 of file test-virtuals.c.
References PWI_FIRST_GET_CLASS, and PWI_IS_FIRST.
Referenced by main().
pwi_first_fn_b()
void pwi_first_fn_b (PwiFirst * instance)
Definition at line 188 of file test-virtuals.c.
References PWI_FIRST_GET_CLASS, and PWI_IS_FIRST.
Referenced by main().
pwi_first_fn_c()
void pwi_first_fn_c (PwiFirst * instance)
Definition at line 202 of file test-virtuals.c.
References PWI_FIRST_GET_CLASS, and PWI_IS_FIRST.
Referenced by main().