MATE Desktop Environment: tfmfile.c File Reference
tfmfile.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include "mdvi.h"
#include "private.h"
Macros
#define TFM_HASH_SIZE 31
Typedefs
typedef struct tfmpool TFMPool
Functions
int tfm_load_file (const char *filename, TFMInfo *info)
char * lookup_font_metrics (const char *name, int *type)
TFMInfo * get_font_metrics (const char *short_name, int type, const char *filename)
void free_font_metrics (TFMInfo *info)
void flush_font_metrics (void)
Macro Definition Documentation
TFM_HASH_SIZE
#define TFM_HASH_SIZE 31
Definition at line 48 of file tfmfile.c.
Typedef Documentation
TFMPool
typedef struct tfmpool TFMPool
Function Documentation
flush_font_metrics()
void flush_font_metrics (void)
Definition at line 734 of file tfmfile.c.
References ListHead::head, LIST, mdvi_free(), and mdvi_hash_reset().
free_font_metrics()
void free_font_metrics (TFMInfo * info)
Definition at line 707 of file tfmfile.c.
References ListHead::count, DBG_FONTS, DEBUG, ListHead::head, LIST, listh_remove(), mdvi_free(), mdvi_hash_remove_ptr(), MDVI_KEY, and NULL.
get_font_metrics()
TFMInfo * get_font_metrics (const char * short_name, int type, const char * filename)
Definition at line 649 of file tfmfile.c.
References ListHead::count, DBG_FONTS, DEBUG, DviFontAFM, DviFontOFM, DviFontTFM, LIST, listh_prepend(), lookup_font_metrics(), mdvi_free(), mdvi_hash_add(), mdvi_hash_create(), mdvi_hash_lookup(), MDVI_HASH_UNCHECKED, MDVI_KEY, mdvi_strdup(), NULL, TFM_HASH_SIZE, tfm_load_file(), type, and xalloc.
Referenced by mdvi_ps_get_metrics().
lookup_font_metrics()
char * lookup_font_metrics (const char * name, int * type)
Definition at line 594 of file tfmfile.c.
References DviFontAFM, DviFontAny, DviFontOFM, DviFontTFM, file_extension(), name, NULL, STREQ, and type.
Referenced by get_font_metrics().
tfm_load_file()
int tfm_load_file (const char * filename, TFMInfo * info)
Definition at line 149 of file tfmfile.c.
References _, _TFMChar::advance, cb, _TFMInfo::chars, _TFMInfo::checksum, _TFMInfo::coding, DBG_FONTS, DEBUG, _TFMChar::depth, _TFMInfo::design, DviFontTFM, error, _TFMInfo::family, _TFMChar::height, _TFMInfo::hic, int(), _TFMChar::left, _TFMInfo::loc, Max, mdvi_error(), mdvi_free(), mdvi_malloc(), mdvi_warning(), memcpy, msget1, muget2, muget4, NULL, _TFMChar::present, _TFMChar::right, ROUND, _TFMInfo::type, and xnalloc.
Referenced by get_font_metrics().