MATE Desktop Environment: theme-parser.c File Reference
theme-parser.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include "theme-parser.h"
#include "util.h"
#include <string.h>
#include <stdlib.h>
Macros
#define THEME_SUBDIR "metacity-1"
#define THEME_MAJOR_VERSION 3
#define THEME_MINOR_VERSION 5
#define THEME_VERSION (1000 * THEME_MAJOR_VERSION + THEME_MINOR_VERSION)
#define MARCO_THEME_FILENAME_FORMAT "metacity-theme-%d.xml"
#define THEME_PARSE_ERROR (theme_parse_error_quark ())
#define ATTRIBUTE_NOT_FOUND _("No \"%s\" attribute on element <%s>")
#define ELEMENT_IS(name) (strcmp (element_name, (name)) == 0)
#define MAX_ATTRS 24
#define MAX_REASONABLE 4096
#define NO_TEXT(element_name) set_error (error, context, G_MARKUP_ERROR, G_MARKUP_ERROR_PARSE, _("No text is allowed inside element <%s>"), element_name)
Enumerations
enum ParseState {
STATE_START , STATE_THEME , STATE_INFO , STATE_NAME ,
STATE_AUTHOR , STATE_COPYRIGHT , STATE_DATE , STATE_DESCRIPTION ,
STATE_CONSTANT , STATE_FRAME_GEOMETRY , STATE_DISTANCE , STATE_BORDER ,
STATE_ASPECT_RATIO , STATE_DRAW_OPS , STATE_LINE , STATE_RECTANGLE ,
STATE_ARC , STATE_CLIP , STATE_TINT , STATE_GRADIENT ,
STATE_IMAGE , STATE_GTK_ARROW , STATE_GTK_BOX , STATE_GTK_VLINE ,
STATE_ICON , STATE_TITLE , STATE_INCLUDE , STATE_TILE ,
STATE_COLOR , STATE_FRAME_STYLE , STATE_PIECE , STATE_BUTTON ,
STATE_SHADOW , STATE_PADDING , STATE_FRAME_STYLE_SET , STATE_FRAME ,
STATE_WINDOW , STATE_MENU_ICON , STATE_FALLBACK
}
enum ThemeParseError { THEME_PARSE_ERROR_TOO_OLD , THEME_PARSE_ERROR_TOO_FAILED }
Functions
MetaTheme * meta_theme_load (const char *theme_name, GError **err)
Macro Definition Documentation
ATTRIBUTE_NOT_FOUND
#define ATTRIBUTE_NOT_FOUND _("No \"%s\" attribute on element <%s>")
Definition at line 253 of file theme-parser.c.
ELEMENT_IS
#define ELEMENT_IS (name) (strcmp (element_name, (name)) == 0)
Definition at line 398 of file theme-parser.c.
MARCO_THEME_FILENAME_FORMAT
#define MARCO_THEME_FILENAME_FORMAT "metacity-theme-%d.xml"
Definition at line 46 of file theme-parser.c.
MAX_ATTRS
#define MAX_ATTRS 24
MAX_REASONABLE
#define MAX_REASONABLE 4096
Definition at line 581 of file theme-parser.c.
NO_TEXT
#define NO_TEXT (element_name) set_error (error, context, G_MARKUP_ERROR, G_MARKUP_ERROR_PARSE, _("No text is allowed inside element <%s>"), element_name)
Definition at line 4041 of file theme-parser.c.
THEME_MAJOR_VERSION
#define THEME_MAJOR_VERSION 3
Definition at line 42 of file theme-parser.c.
THEME_MINOR_VERSION
#define THEME_MINOR_VERSION 5
Definition at line 43 of file theme-parser.c.
THEME_PARSE_ERROR
#define THEME_PARSE_ERROR (theme_parse_error_quark ())
Definition at line 136 of file theme-parser.c.
THEME_SUBDIR
#define THEME_SUBDIR "metacity-1"
Definition at line 37 of file theme-parser.c.
THEME_VERSION
#define THEME_VERSION (1000 * THEME_MAJOR_VERSION + THEME_MINOR_VERSION)
Definition at line 44 of file theme-parser.c.
Enumeration Type Documentation
ParseState
enum ParseState
Enumerator
STATE_START
STATE_THEME
STATE_INFO
STATE_NAME
STATE_AUTHOR
STATE_COPYRIGHT
STATE_DATE
STATE_DESCRIPTION
STATE_CONSTANT
STATE_FRAME_GEOMETRY
STATE_DISTANCE
STATE_BORDER
STATE_ASPECT_RATIO
STATE_DRAW_OPS
STATE_LINE
STATE_RECTANGLE
STATE_ARC
STATE_CLIP
STATE_TINT
STATE_GRADIENT
STATE_IMAGE
STATE_GTK_ARROW
STATE_GTK_BOX
STATE_GTK_VLINE
STATE_ICON
STATE_TITLE
STATE_INCLUDE
STATE_TILE
STATE_COLOR
STATE_FRAME_STYLE
STATE_PIECE
STATE_BUTTON
STATE_SHADOW
STATE_PADDING
STATE_FRAME_STYLE_SET
STATE_FRAME
STATE_WINDOW
STATE_MENU_ICON
STATE_FALLBACK
Definition at line 48 of file theme-parser.c.
ThemeParseError
enum ThemeParseError
Enumerator
THEME_PARSE_ERROR_TOO_OLD
THEME_PARSE_ERROR_TOO_FAILED
Definition at line 125 of file theme-parser.c.
Function Documentation
meta_theme_load()
MetaTheme * meta_theme_load (const char * theme_name, GError ** err)
Definition at line 4339 of file theme-parser.c.
References _, error, meta_is_debugging(), META_THEME_ERROR, META_THEME_ERROR_FAILED, NULL, THEME_MAJOR_VERSION, and THEME_SUBDIR.
Referenced by main(), and meta_theme_set_current().