MATE Desktop Environment: theme-util.h File Reference
theme-util.h File Reference
Enumerations
enum { COL_THUMBNAIL , COL_LABEL , COL_NAME , NUM_COLS }
enum ThemeType {
THEME_TYPE_GTK , THEME_TYPE_WINDOW , THEME_TYPE_ICON , THEME_TYPE_META ,
THEME_TYPE_CURSOR
}
Functions
gboolean theme_is_writable (const gpointer theme)
gboolean theme_delete (const gchar *name, ThemeType type)
gboolean theme_model_iter_last (GtkTreeModel *model, GtkTreeIter *iter)
gboolean theme_find_in_model (GtkTreeModel *model, const gchar *name, GtkTreeIter *iter)
void theme_install_file (GtkWindow *parent, const gchar *path)
gboolean packagekit_available (void)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COL_THUMBNAIL
COL_LABEL
COL_NAME
NUM_COLS
Definition at line 24 of file theme-util.h.
ThemeType
enum ThemeType
Enumerator
THEME_TYPE_GTK
THEME_TYPE_WINDOW
THEME_TYPE_ICON
THEME_TYPE_META
THEME_TYPE_CURSOR
Definition at line 31 of file theme-util.h.
Function Documentation
packagekit_available()
gboolean packagekit_available (void)
Definition at line 188 of file theme-util.c.
References connection, error, FALSE, NULL, and proxy.
theme_delete()
gboolean theme_delete (const gchar * name, ThemeType type)
Definition at line 57 of file theme-util.c.
References _, capplet_file_delete_recursive(), FALSE, mate_theme_cursor_info_find(), mate_theme_icon_info_find(), mate_theme_info_find(), mate_theme_meta_info_find(), name, NULL, _MateThemeCommonInfo::path, THEME_TYPE_CURSOR, THEME_TYPE_GTK, THEME_TYPE_ICON, THEME_TYPE_META, THEME_TYPE_WINDOW, TRUE, and type.
theme_find_in_model()
gboolean theme_find_in_model (GtkTreeModel * model, const gchar * name, GtkTreeIter * iter)
Definition at line 159 of file theme-util.c.
References COL_NAME, FALSE, name, test, and TRUE.
theme_install_file()
void theme_install_file (GtkWindow * parent, const gchar * path)
Definition at line 239 of file theme-util.c.
References _, connection, error, NULL, and proxy.
theme_is_writable()
gboolean theme_is_writable (const gpointer theme)
Definition at line 30 of file theme-util.c.
References FALSE, NULL, and _MateThemeCommonInfo::path.
theme_model_iter_last()
gboolean theme_model_iter_last (GtkTreeModel * model, GtkTreeIter * iter)
Definition at line 140 of file theme-util.c.
References FALSE, and TRUE.