MATE Desktop Environment: theme-viewer.c File Reference
theme-viewer.c File Reference
#include <config.h>
#include <glib/gi18n.h>
#include "util.h"
#include "theme.h"
#include "theme-parser.h"
#include "preview-widget.h"
#include <gtk/gtk.h>
#include <time.h>
#include <stdlib.h>
#include <string.h>
Macros
#define BUTTON_LAYOUT_COMBINATIONS (MAX_BUTTONS_PER_CORNER + 1 + 1)
#define ITERATIONS 100
Enumerations
enum { FONT_SIZE_SMALL , FONT_SIZE_NORMAL , FONT_SIZE_LARGE , FONT_SIZE_LAST }
Functions
int main (int argc, char **argv)
Macro Definition Documentation
BUTTON_LAYOUT_COMBINATIONS
#define BUTTON_LAYOUT_COMBINATIONS (MAX_BUTTONS_PER_CORNER + 1 + 1)
Definition at line 47 of file theme-viewer.c.
ITERATIONS
#define ITERATIONS 100
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FONT_SIZE_SMALL
FONT_SIZE_NORMAL
FONT_SIZE_LARGE
FONT_SIZE_LAST
Definition at line 52 of file theme-viewer.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 842 of file theme-viewer.c.
References _, FONT_SIZE_LARGE, FONT_SIZE_NORMAL, FONT_SIZE_SMALL, meta_set_debugging(), meta_set_verbose(), meta_theme_load(), _MetaTheme::name, NULL, _MetaTheme::readable_name, and TRUE.