MATE Desktop Environment: tile.h File Reference
tile.h File Reference
#include <glib.h>
#include <gtk/gtk.h>
Classes
struct _Tile
struct _TileClass
struct _TileAction
struct _TileActionClass
struct _TileEvent
Macros
#define TILE_TYPE (tile_get_type ())
#define TILE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TILE_TYPE, Tile))
#define TILE_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), TILE_TYPE, TileClass))
#define IS_TILE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TILE_TYPE))
#define IS_TILE_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TILE_TYPE))
#define TILE_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TILE_TYPE, TileClass))
#define TILE_ACTION_TYPE (tile_action_get_type ())
#define TILE_ACTION(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TILE_ACTION_TYPE, TileAction))
#define TILE_ACTION_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), TILE_ACTION_TYPE, TileActionClass))
#define IS_TILE_ACTION(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TILE_ACTION_TYPE))
#define IS_TILE_ACTION_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TILE_ACTION_TYPE))
#define TILE_ACTION_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TILE_ACTION_TYPE, TileActionClass))
#define TILE_ACTION_CHECK_FLAG(action, flag) ((TILE_ACTION (action)->flags & (flag)) != 0)
#define TILE_STATE_ENTERED GTK_STATE_FLAG_PRELIGHT
#define TILE_STATE_FOCUSED GTK_STATE_FLAG_PRELIGHT
Typedefs
typedef struct _Tile Tile
typedef struct _TileClass TileClass
typedef struct _TileAction TileAction
typedef struct _TileActionClass TileActionClass
typedef struct _TileEvent TileEvent
typedef void(* TileActionFunc) (Tile *, TileEvent *, TileAction *)
Enumerations
enum TileEventType { TILE_EVENT_ACTIVATED_SINGLE_CLICK , TILE_EVENT_ACTIVATED_DOUBLE_CLICK , TILE_EVENT_ACTIVATED_KEYBOARD , TILE_EVENT_ACTION_TRIGGERED }
enum TileActionFlags { TILE_ACTION_OPENS_NEW_WINDOW = 1 << 0 , TILE_ACTION_OPENS_HELP = 1 << 1 }
Functions
GType tile_get_type (void)
GType tile_action_get_type (void)
void tile_trigger_action (Tile *tile, TileAction *action)
void tile_trigger_action_with_time (Tile *tile, TileAction *action, guint32 time)
TileAction * tile_action_new (Tile *tile, TileActionFunc func, const gchar *menu_item_markup, guint32 flags)
void tile_action_set_menu_item_label (TileAction *action, const gchar *markup)
GtkMenuItem * tile_action_get_menu_item (TileAction *action)
Macro Definition Documentation
IS_TILE
#define IS_TILE (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TILE_TYPE))
Definition at line 32 of file tile.h.
IS_TILE_ACTION
#define IS_TILE_ACTION (o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TILE_ACTION_TYPE))
Definition at line 38 of file tile.h.
IS_TILE_ACTION_CLASS
#define IS_TILE_ACTION_CLASS (c) (G_TYPE_CHECK_CLASS_TYPE ((c), TILE_ACTION_TYPE))
Definition at line 39 of file tile.h.
IS_TILE_CLASS
#define IS_TILE_CLASS (c) (G_TYPE_CHECK_CLASS_TYPE ((c), TILE_TYPE))
Definition at line 33 of file tile.h.
TILE
#define TILE (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TILE_TYPE, Tile))
Definition at line 30 of file tile.h.
TILE_ACTION
#define TILE_ACTION (o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TILE_ACTION_TYPE, TileAction))
Definition at line 36 of file tile.h.
TILE_ACTION_CHECK_FLAG
#define TILE_ACTION_CHECK_FLAG (action, flag) ((TILE_ACTION (action)->flags & (flag)) != 0)
Definition at line 41 of file tile.h.
TILE_ACTION_CLASS
#define TILE_ACTION_CLASS (c) (G_TYPE_CHECK_CLASS_CAST ((c), TILE_ACTION_TYPE, TileActionClass))
Definition at line 37 of file tile.h.
TILE_ACTION_GET_CLASS
#define TILE_ACTION_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), TILE_ACTION_TYPE, TileActionClass))
Definition at line 40 of file tile.h.
TILE_ACTION_TYPE
#define TILE_ACTION_TYPE (tile_action_get_type ())
Definition at line 35 of file tile.h.
TILE_CLASS
#define TILE_CLASS (c) (G_TYPE_CHECK_CLASS_CAST ((c), TILE_TYPE, TileClass))
Definition at line 31 of file tile.h.
TILE_GET_CLASS
#define TILE_GET_CLASS (o) (G_TYPE_INSTANCE_GET_CLASS ((o), TILE_TYPE, TileClass))
Definition at line 34 of file tile.h.
TILE_STATE_ENTERED
#define TILE_STATE_ENTERED GTK_STATE_FLAG_PRELIGHT
Definition at line 42 of file tile.h.
TILE_STATE_FOCUSED
#define TILE_STATE_FOCUSED GTK_STATE_FLAG_PRELIGHT
Definition at line 43 of file tile.h.
TILE_TYPE
#define TILE_TYPE (tile_get_type ())
Definition at line 29 of file tile.h.
Typedef Documentation
Tile
typedef struct _Tile Tile
Definition at line 45 of file tile.h.
TileAction
typedef struct _TileAction TileAction
Definition at line 47 of file tile.h.
TileActionClass
typedef struct _TileActionClass TileActionClass
Definition at line 48 of file tile.h.
TileActionFunc
typedef void(* TileActionFunc) (Tile *, TileEvent *, TileAction *)
Definition at line 51 of file tile.h.
TileClass
typedef struct _TileClass TileClass
Definition at line 46 of file tile.h.
TileEvent
typedef struct _TileEvent TileEvent
Definition at line 49 of file tile.h.
Enumeration Type Documentation
TileActionFlags
enum TileActionFlags
Enumerator
TILE_ACTION_OPENS_NEW_WINDOW
TILE_ACTION_OPENS_HELP
Definition at line 61 of file tile.h.
TileEventType
enum TileEventType
Enumerator
TILE_EVENT_ACTIVATED_SINGLE_CLICK
TILE_EVENT_ACTIVATED_DOUBLE_CLICK
TILE_EVENT_ACTIVATED_KEYBOARD
TILE_EVENT_ACTION_TRIGGERED
Definition at line 53 of file tile.h.
Function Documentation
tile_action_get_menu_item()
GtkMenuItem * tile_action_get_menu_item (TileAction * action)
Definition at line 98 of file tile-action.c.
tile_action_get_type()
GType tile_action_get_type (void)
tile_action_new()
TileAction * tile_action_new (Tile * tile, TileActionFunc func, const gchar * menu_item_markup, guint32 flags)
Definition at line 55 of file tile-action.c.
References NULL, tile_action_set_menu_item_label(), and TILE_ACTION_TYPE.
tile_action_set_menu_item_label()
void tile_action_set_menu_item_label (TileAction * action, const gchar * markup)
Definition at line 73 of file tile-action.c.
References label, and TRUE.
Referenced by tile_action_new().
tile_get_type()
GType tile_get_type (void)
tile_trigger_action()
void tile_trigger_action (Tile * tile, TileAction * action)
Definition at line 484 of file tile.c.
References action, and tile_trigger_action_with_time().
tile_trigger_action_with_time()
void tile_trigger_action_with_time (Tile * tile, TileAction * action, guint32 time)
Definition at line 490 of file tile.c.
References action, TILE_ACTION_TRIGGERED_SIGNAL, and TILE_EVENT_ACTION_TRIGGERED.
Referenced by tile_trigger_action().