MATE Desktop Environment: totem-properties-view.h File Reference
totem-properties-view.h File Reference
#include <gtk/gtk.h>
Classes
struct TotemPropertiesView
struct TotemPropertiesViewClass
Macros
#define TOTEM_TYPE_PROPERTIES_VIEW (totem_properties_view_get_type ())
#define TOTEM_PROPERTIES_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOTEM_TYPE_PROPERTIES_VIEW, TotemPropertiesView))
#define TOTEM_PROPERTIES_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOTEM_TYPE_PROPERTIES_VIEW, TotemPropertiesViewClass))
#define TOTEM_IS_PROPERTIES_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOTEM_TYPE_PROPERTIES_VIEW))
#define TOTEM_IS_PROPERTIES_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOTEM_TYPE_PROPERTIES_VIEW))
Typedefs
typedef struct TotemPropertiesViewPriv TotemPropertiesViewPriv
Functions
GType totem_properties_view_get_type (void)
void totem_properties_view_register_type (GTypeModule *module)
GtkWidget * totem_properties_view_new (const char *location, GtkWidget *label)
Macro Definition Documentation
TOTEM_IS_PROPERTIES_VIEW
#define TOTEM_IS_PROPERTIES_VIEW (obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TOTEM_TYPE_PROPERTIES_VIEW))
Definition at line 29 of file totem-properties-view.h.
TOTEM_IS_PROPERTIES_VIEW_CLASS
#define TOTEM_IS_PROPERTIES_VIEW_CLASS (klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TOTEM_TYPE_PROPERTIES_VIEW))
Definition at line 30 of file totem-properties-view.h.
TOTEM_PROPERTIES_VIEW
#define TOTEM_PROPERTIES_VIEW (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TOTEM_TYPE_PROPERTIES_VIEW, TotemPropertiesView))
Definition at line 27 of file totem-properties-view.h.
TOTEM_PROPERTIES_VIEW_CLASS
#define TOTEM_PROPERTIES_VIEW_CLASS (klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TOTEM_TYPE_PROPERTIES_VIEW, TotemPropertiesViewClass))
Definition at line 28 of file totem-properties-view.h.
TOTEM_TYPE_PROPERTIES_VIEW
#define TOTEM_TYPE_PROPERTIES_VIEW (totem_properties_view_get_type ())
Definition at line 26 of file totem-properties-view.h.
Typedef Documentation
TotemPropertiesViewPriv
typedef struct TotemPropertiesViewPriv TotemPropertiesViewPriv
Definition at line 32 of file totem-properties-view.h.
Function Documentation
totem_properties_view_get_type()
GType totem_properties_view_get_type (void)
Referenced by totem_properties_view_register_type().
totem_properties_view_new()
GtkWidget * totem_properties_view_new (const char * location, GtkWidget * label)
Definition at line 379 of file totem-properties-view.c.
References label, NULL, TotemPropertiesView::priv, and TOTEM_TYPE_PROPERTIES_VIEW.
totem_properties_view_register_type()
void totem_properties_view_register_type (GTypeModule * module)
Definition at line 46 of file totem-properties-view.c.
References totem_properties_view_get_type().
Referenced by caja_module_initialize().