MATE Desktop Environment: unit-category.h File Reference
unit-category.h File Reference
#include <glib-object.h>
#include "unit.h"
#include "mp.h"
Classes
struct UnitCategory
struct UnitCategoryClass
Macros
#define UNIT_CATEGORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), unit_category_get_type(), UnitCategory))
Typedefs
typedef struct UnitCategoryPrivate UnitCategoryPrivate
Functions
GType unit_category_get_type (void)
UnitCategory * unit_category_new (const gchar *name, const gchar *display_name)
const gchar * unit_category_get_name (UnitCategory *category)
const gchar * unit_category_get_display_name (UnitCategory *category)
Unit * unit_category_get_unit_by_name (UnitCategory *category, const gchar *name)
Unit * unit_category_get_unit_by_symbol (UnitCategory *category, const gchar *symbol)
void unit_category_add_unit (UnitCategory *category, Unit *unit)
const GList * unit_category_get_units (UnitCategory *category)
gboolean unit_category_convert (const UnitCategory *category, const MPNumber *x, Unit *x_units, Unit *z_units, MPNumber *z)
Macro Definition Documentation
UNIT_CATEGORY
#define UNIT_CATEGORY (obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), unit_category_get_type(), UnitCategory))
Definition at line 21 of file unit-category.h.
Typedef Documentation
UnitCategoryPrivate
typedef struct UnitCategoryPrivate UnitCategoryPrivate
Definition at line 23 of file unit-category.h.
Function Documentation
unit_category_add_unit()
void unit_category_add_unit (UnitCategory * category, Unit * unit)
Definition at line 49 of file unit-category.c.
References category, and NULL.
Referenced by unit_manager_get_default().
unit_category_convert()
gboolean unit_category_convert (const UnitCategory * category, const MPNumber * x, Unit * x_units, Unit * z_units, MPNumber * z)
Definition at line 99 of file unit-category.c.
References category, FALSE, mp_clear(), mp_new(), NULL, TRUE, unit_convert_from(), and unit_convert_to().
Referenced by unit_manager_convert_by_symbol().
unit_category_get_display_name()
const gchar * unit_category_get_display_name (UnitCategory * category)
Definition at line 42 of file unit-category.c.
References category, and NULL.
unit_category_get_name()
const gchar * unit_category_get_name (UnitCategory * category)
Definition at line 35 of file unit-category.c.
References category, and NULL.
Referenced by unit_manager_get_category().
unit_category_get_type()
GType unit_category_get_type (void)
Referenced by unit_category_new().
unit_category_get_unit_by_name()
Unit * unit_category_get_unit_by_name (UnitCategory * category, const gchar * name)
Definition at line 57 of file unit-category.c.
References category, name, NULL, and unit_get_name().
Referenced by unit_manager_get_unit_by_name().
unit_category_get_unit_by_symbol()
Unit * unit_category_get_unit_by_symbol (UnitCategory * category, const gchar * symbol)
Definition at line 75 of file unit-category.c.
References category, NULL, and unit_matches_symbol().
Referenced by unit_manager_convert_by_symbol(), and unit_manager_get_unit_by_symbol().
unit_category_get_units()
const GList * unit_category_get_units (UnitCategory * category)
Definition at line 92 of file unit-category.c.
References category, and NULL.
unit_category_new()
UnitCategory * unit_category_new (const gchar * name, const gchar * display_name)
Definition at line 26 of file unit-category.c.
References category, name, NULL, and unit_category_get_type().
Referenced by unit_manager_add_category().