MATE Desktop Environment: weather.c File Reference
weather.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include <ctype.h>
#include <math.h>
#include <fenv.h>
#include <time.h>
#include <unistd.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include "weather.h"
#include "weather-priv.h"
Macros
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
#define MOON_PHASES 36
Functions
const char * mateweather_gettext (const char *str)
const char * mateweather_dpgettext (const char *context, const char *str)
WeatherLocation * weather_location_new (const gchar *name, const gchar *code, const gchar *zone, const gchar *radar, const gchar *coordinates, const gchar *country_code, const gchar *tz_hint)
WeatherLocation * weather_location_clone (const WeatherLocation *location)
void weather_location_free (WeatherLocation *location)
gboolean weather_location_equal (const WeatherLocation *location1, const WeatherLocation *location2)
const gchar * weather_wind_direction_string (WeatherWindDirection wind)
const gchar * weather_sky_string (WeatherSky sky)
const gchar * weather_conditions_string (WeatherConditions cond)
gboolean requests_init (WeatherInfo *info)
void request_done (WeatherInfo *info, GError *error)
void free_forecast_list (WeatherInfo *info)
WeatherInfo * _weather_info_fill (WeatherInfo *info, WeatherLocation *location, const WeatherPrefs *prefs, WeatherInfoFunc cb, gpointer data)
void weather_info_abort (WeatherInfo *info)
WeatherInfo * weather_info_clone (const WeatherInfo *info)
void weather_info_free (WeatherInfo *info)
gboolean weather_info_is_valid (WeatherInfo *info)
gboolean weather_info_network_error (WeatherInfo *info)
void weather_info_to_metric (WeatherInfo *info)
void weather_info_to_imperial (WeatherInfo *info)
const WeatherLocation * weather_info_get_location (WeatherInfo *info)
const gchar * weather_info_get_location_name (WeatherInfo *info)
const gchar * weather_info_get_update (WeatherInfo *info)
const gchar * weather_info_get_sky (WeatherInfo *info)
const gchar * weather_info_get_conditions (WeatherInfo *info)
const gchar * weather_info_get_temp (WeatherInfo *info)
const gchar * weather_info_get_temp_min (WeatherInfo *info)
const gchar * weather_info_get_temp_max (WeatherInfo *info)
const gchar * weather_info_get_dew (WeatherInfo *info)
const gchar * weather_info_get_humidity (WeatherInfo *info)
const gchar * weather_info_get_apparent (WeatherInfo *info)
const gchar * weather_info_get_wind (WeatherInfo *info)
const gchar * weather_info_get_pressure (WeatherInfo *info)
const gchar * weather_info_get_visibility (WeatherInfo *info)
const gchar * weather_info_get_sunrise (WeatherInfo *info)
const gchar * weather_info_get_sunset (WeatherInfo *info)
const gchar * weather_info_get_forecast (WeatherInfo *info)
GSList * weather_info_get_forecast_list (WeatherInfo *info)
GdkPixbufAnimation * weather_info_get_radar (WeatherInfo *info)
const gchar * weather_info_get_temp_summary (WeatherInfo *info)
gchar * weather_info_get_weather_summary (WeatherInfo *info)
const gchar * weather_info_get_icon_name (WeatherInfo *info)
gboolean weather_info_get_value_sky (WeatherInfo *info, WeatherSky *sky)
gboolean weather_info_get_value_conditions (WeatherInfo *info, WeatherConditionPhenomenon *phenomenon, WeatherConditionQualifier *qualifier)
gboolean weather_info_get_value_temp (WeatherInfo *info, TempUnit unit, gdouble *value)
gboolean weather_info_get_value_temp_min (WeatherInfo *info, TempUnit unit, gdouble *value)
gboolean weather_info_get_value_temp_max (WeatherInfo *info, TempUnit unit, gdouble *value)
gboolean weather_info_get_value_dew (WeatherInfo *info, TempUnit unit, gdouble *value)
gboolean weather_info_get_value_apparent (WeatherInfo *info, TempUnit unit, gdouble *value)
gboolean weather_info_get_value_update (WeatherInfo *info, time_t *value)
gboolean weather_info_get_value_sunrise (WeatherInfo *info, time_t *value)
gboolean weather_info_get_value_sunset (WeatherInfo *info, time_t *value)
gboolean weather_info_get_value_moonphase (WeatherInfo *info, WeatherMoonPhase *value, WeatherMoonLatitude *lat)
gboolean weather_info_get_value_wind (WeatherInfo *info, SpeedUnit unit, gdouble *speed, WeatherWindDirection *direction)
gboolean weather_info_get_value_pressure (WeatherInfo *info, PressureUnit unit, gdouble *value)
gboolean weather_info_get_value_visibility (WeatherInfo *info, DistanceUnit unit, gdouble *value)
gboolean weather_info_get_upcoming_moonphases (WeatherInfo *info, time_t *phases)
Macro Definition Documentation
MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
Definition at line 40 of file weather.c.
MOON_PHASES
#define MOON_PHASES 36
Definition at line 44 of file weather.c.
Function Documentation
_weather_info_fill()
WeatherInfo * _weather_info_fill (WeatherInfo * info, WeatherLocation * location, const WeatherPrefs * prefs, WeatherInfoFunc cb, gpointer data)
Definition at line 480 of file weather.c.
References cb, _WeatherInfo::cb_data, _WeatherInfo::cond, data, _WeatherInfo::dew, _WeatherInfo::distance_unit, _WeatherPrefs::distance_unit, FALSE, _WeatherInfo::finish_cb, _WeatherInfo::forecast, _WeatherInfo::forecast_list, _WeatherInfo::forecast_type, free_forecast_list(), iwin_start_open(), _WeatherInfo::location, metar_start_open(), _WeatherInfo::moonlatitude, _WeatherInfo::moonphase, _WeatherInfo::moonValid, NULL, _WeatherConditions::phenomenon, PHENOMENON_NONE, _WeatherInfo::pressure, _WeatherInfo::pressure_unit, _WeatherPrefs::pressure_unit, _WeatherConditions::qualifier, QUALIFIER_NONE, _WeatherInfo::radar, _WeatherPrefs::radar, _WeatherPrefs::radar_custom_url, _WeatherInfo::radar_url, requests_init(), _WeatherInfo::requests_pending, _WeatherInfo::session, _WeatherConditions::significant, _WeatherInfo::sky, _WeatherInfo::speed_unit, _WeatherPrefs::speed_unit, _WeatherInfo::sunrise, _WeatherInfo::sunriseValid, _WeatherInfo::sunset, _WeatherInfo::sunsetValid, _WeatherInfo::temp, _WeatherInfo::temp_max, _WeatherInfo::temp_min, _WeatherInfo::temperature_unit, _WeatherPrefs::temperature_unit, _WeatherInfo::tempMinMaxValid, _WeatherPrefs::type, _WeatherInfo::update, _WeatherInfo::visibility, weather_location_clone(), _WeatherInfo::wind, _WeatherInfo::windspeed, and wx_start_open().
free_forecast_list()
void free_forecast_list (WeatherInfo * info)
Definition at line 364 of file weather.c.
References _WeatherInfo::forecast_list, NULL, and weather_info_free().
Referenced by _weather_info_fill(), iwin_start_open(), and weather_info_free().
mateweather_dpgettext()
const char * mateweather_dpgettext (const char * context, const char * str)
Definition at line 75 of file weather.c.
mateweather_gettext()
const char * mateweather_gettext (const char * str)
Definition at line 68 of file weather.c.
request_done()
void request_done (WeatherInfo * info, GError * error)
Definition at line 351 of file weather.c.
References calc_moon(), calc_sun(), _WeatherInfo::cb_data, error, _WeatherInfo::finish_cb, _WeatherInfo::moonValid, NULL, _WeatherInfo::requests_pending, and _WeatherInfo::valid.
requests_init()
gboolean requests_init (WeatherInfo * info)
Definition at line 343 of file weather.c.
References FALSE, _WeatherInfo::requests_pending, and TRUE.
Referenced by _weather_info_fill().
weather_conditions_string()
const gchar * weather_conditions_string (WeatherConditions cond)
Definition at line 322 of file weather.c.
References _, _WeatherConditions::phenomenon, PHENOMENON_INVALID, PHENOMENON_LAST, _WeatherConditions::qualifier, QUALIFIER_INVALID, QUALIFIER_LAST, and _WeatherConditions::significant.
Referenced by weather_info_get_conditions().
weather_info_abort()
void weather_info_abort (WeatherInfo * info)
Definition at line 568 of file weather.c.
References NULL, _WeatherInfo::requests_pending, and _WeatherInfo::session.
Referenced by weather_info_free().
weather_info_clone()
WeatherInfo * weather_info_clone (const WeatherInfo * info)
Definition at line 579 of file weather.c.
References _WeatherInfo::forecast, _WeatherInfo::forecast_list, _WeatherInfo::location, memmove, NULL, _WeatherInfo::radar, _WeatherInfo::radar_url, weather_info_clone(), and weather_location_clone().
Referenced by weather_info_clone().
weather_info_free()
void weather_info_free (WeatherInfo * info)
Definition at line 615 of file weather.c.
References _WeatherInfo::forecast, free_forecast_list(), _WeatherInfo::location, NULL, _WeatherInfo::radar, _WeatherInfo::session, weather_info_abort(), and weather_location_free().
Referenced by free_forecast_list(), and mateweather_update().
weather_info_get_apparent()
const gchar * weather_info_get_apparent (WeatherInfo * info)
Definition at line 891 of file weather.c.
References _, FALSE, NULL, _WeatherInfo::temperature_unit, and _WeatherInfo::valid.
Referenced by mateweather_dialog_update(), and weather_info_setup_tooltip().
weather_info_get_conditions()
const gchar * weather_info_get_conditions (WeatherInfo * info)
Definition at line 742 of file weather.c.
References _WeatherInfo::cond, NULL, _WeatherInfo::valid, and weather_conditions_string().
Referenced by main(), mateweather_dialog_update(), weather_info_get_weather_summary(), and weather_info_setup_tooltip().
weather_info_get_dew()
const gchar * weather_info_get_dew (WeatherInfo * info)
Definition at line 858 of file weather.c.
References _, _WeatherInfo::dew, FALSE, NULL, _WeatherInfo::temperature_unit, and _WeatherInfo::valid.
Referenced by main(), and mateweather_dialog_update().
weather_info_get_forecast()
const gchar * weather_info_get_forecast (WeatherInfo * info)
Definition at line 1095 of file weather.c.
References _WeatherInfo::forecast, and NULL.
Referenced by mateweather_dialog_update().
weather_info_get_forecast_list()
GSList * weather_info_get_forecast_list (WeatherInfo * info)
weather_info_get_forecast_list: Returns list of WeatherInfo* objects for the forecast. The list is owned by the 'info' object thus is alive as long as the 'info'. This list is filled only when requested with type FORECAST_LIST and if available for given location. The 'update' property is the date/time when the forecast info is used for.
Definition at line 1111 of file weather.c.
References _WeatherInfo::forecast_list, NULL, and _WeatherInfo::valid.
weather_info_get_humidity()
const gchar * weather_info_get_humidity (WeatherInfo * info)
Definition at line 871 of file weather.c.
References _, _WeatherInfo::dew, NULL, _WeatherInfo::temp, and _WeatherInfo::valid.
Referenced by mateweather_dialog_update().
weather_info_get_icon_name()
const gchar * weather_info_get_icon_name (WeatherInfo * info)
Definition at line 1156 of file weather.c.
References _WeatherInfo::cond, FALSE, _WeatherInfo::midnightSun, MOON_PHASES, _WeatherInfo::moonValid, NULL, _WeatherConditions::phenomenon, PHENOMENON_DRIZZLE, PHENOMENON_DUST, PHENOMENON_DUST_WHIRLS, PHENOMENON_DUSTSTORM, PHENOMENON_FOG, PHENOMENON_FUNNEL_CLOUD, PHENOMENON_HAIL, PHENOMENON_HAZE, PHENOMENON_ICE_CRYSTALS, PHENOMENON_ICE_PELLETS, PHENOMENON_INVALID, PHENOMENON_LAST, PHENOMENON_MIST, PHENOMENON_NONE, PHENOMENON_RAIN, PHENOMENON_SAND, PHENOMENON_SANDSTORM, PHENOMENON_SMALL_HAIL, PHENOMENON_SMOKE, PHENOMENON_SNOW, PHENOMENON_SNOW_GRAINS, PHENOMENON_SPRAY, PHENOMENON_SQUALL, PHENOMENON_TORNADO, PHENOMENON_UNKNOWN_PRECIPITATION, PHENOMENON_VOLCANIC_ASH, _WeatherInfo::polarNight, _WeatherConditions::qualifier, QUALIFIER_THUNDERSTORM, RADIANS_TO_DEGREES, _WeatherConditions::significant, _WeatherInfo::sky, SKY_BROKEN, SKY_CLEAR, SKY_FEW, SKY_INVALID, SKY_LAST, SKY_OVERCAST, SKY_SCATTERED, _WeatherInfo::sunrise, _WeatherInfo::sunriseValid, _WeatherInfo::sunset, _WeatherInfo::sunsetValid, TRUE, _WeatherInfo::valid, weather_info_get_location(), and weather_info_get_value_moonphase().
Referenced by mateweather_dialog_update(), and weather_info_setup_tooltip().
weather_info_get_location()
const WeatherLocation * weather_info_get_location (WeatherInfo * info)
Definition at line 677 of file weather.c.
References _WeatherInfo::location, and NULL.
Referenced by mateweather_update(), and weather_info_get_icon_name().
weather_info_get_location_name()
const gchar * weather_info_get_location_name (WeatherInfo * info)
Definition at line 684 of file weather.c.
References _WeatherInfo::location, _WeatherLocation::name, and NULL.
Referenced by mateweather_dialog_update(), and weather_info_get_weather_summary().
weather_info_get_pressure()
const gchar * weather_info_get_pressure (WeatherInfo * info)
Definition at line 969 of file weather.c.
References _, NULL, _WeatherInfo::pressure, PRESSURE_INCH_TO_ATM, PRESSURE_INCH_TO_HPA, PRESSURE_INCH_TO_KPA, PRESSURE_INCH_TO_MB, PRESSURE_INCH_TO_MM, _WeatherInfo::pressure_unit, PRESSURE_UNIT_ATM, PRESSURE_UNIT_DEFAULT, PRESSURE_UNIT_HPA, PRESSURE_UNIT_INCH_HG, PRESSURE_UNIT_INVALID, PRESSURE_UNIT_KPA, PRESSURE_UNIT_MB, PRESSURE_UNIT_MM_HG, and _WeatherInfo::valid.
Referenced by main(), and mateweather_dialog_update().
weather_info_get_radar()
GdkPixbufAnimation * weather_info_get_radar (WeatherInfo * info)
Definition at line 1122 of file weather.c.
References NULL, and _WeatherInfo::radar.
Referenced by mateweather_dialog_update().
weather_info_get_sky()
const gchar * weather_info_get_sky (WeatherInfo * info)
Definition at line 731 of file weather.c.
References _, NULL, _WeatherInfo::sky, _WeatherInfo::valid, and weather_sky_string().
Referenced by main(), mateweather_dialog_update(), weather_info_get_weather_summary(), and weather_info_setup_tooltip().
weather_info_get_sunrise()
const gchar * weather_info_get_sunrise (WeatherInfo * info)
Definition at line 1053 of file weather.c.
References _, calc_sun(), _WeatherLocation::latlon_valid, _WeatherInfo::location, NULL, _WeatherInfo::sunrise, and _WeatherInfo::valid.
Referenced by mateweather_dialog_update().
weather_info_get_sunset()
const gchar * weather_info_get_sunset (WeatherInfo * info)
Definition at line 1074 of file weather.c.
References _, calc_sun(), _WeatherLocation::latlon_valid, _WeatherInfo::location, NULL, _WeatherInfo::sunset, and _WeatherInfo::valid.
Referenced by mateweather_dialog_update().
weather_info_get_temp()
const gchar * weather_info_get_temp (WeatherInfo * info)
Definition at line 819 of file weather.c.
References _, FALSE, NULL, _WeatherInfo::temp, _WeatherInfo::temperature_unit, and _WeatherInfo::valid.
Referenced by main(), mateweather_dialog_update(), and weather_info_setup_tooltip().
weather_info_get_temp_max()
const gchar * weather_info_get_temp_max (WeatherInfo * info)
Definition at line 845 of file weather.c.
References _, FALSE, NULL, _WeatherInfo::temp_max, _WeatherInfo::temperature_unit, _WeatherInfo::tempMinMaxValid, and _WeatherInfo::valid.
weather_info_get_temp_min()
const gchar * weather_info_get_temp_min (WeatherInfo * info)
Definition at line 832 of file weather.c.
References _, FALSE, NULL, _WeatherInfo::temp_min, _WeatherInfo::temperature_unit, _WeatherInfo::tempMinMaxValid, and _WeatherInfo::valid.
weather_info_get_temp_summary()
const gchar * weather_info_get_temp_summary (WeatherInfo * info)
Definition at line 1129 of file weather.c.
References NULL, _WeatherInfo::temp, _WeatherInfo::temperature_unit, TRUE, and _WeatherInfo::valid.
weather_info_get_upcoming_moonphases()
gboolean weather_info_get_upcoming_moonphases (WeatherInfo * info, time_t * phases)
weather_info_get_upcoming_moonphases: @info: WeatherInfo containing the time_t of interest @phases: An array of four time_t values that will hold the returned values. The values are estimates of the time of the next new, quarter, full and three-quarter moons.
Returns: gboolean indicating success or failure
Definition at line 1658 of file weather.c.
References calc_moon_phases(), FALSE, and NULL.
weather_info_get_update()
const gchar * weather_info_get_update (WeatherInfo * info)
Definition at line 692 of file weather.c.
References _, NULL, _WeatherInfo::update, and _WeatherInfo::valid.
Referenced by mateweather_dialog_update().
weather_info_get_value_apparent()
gboolean weather_info_get_value_apparent (WeatherInfo * info, TempUnit unit, gdouble * value)
Definition at line 1533 of file weather.c.
References FALSE, NULL, _WeatherInfo::temperature_unit, and _WeatherInfo::valid.
weather_info_get_value_conditions()
gboolean weather_info_get_value_conditions (WeatherInfo * info, WeatherConditionPhenomenon * phenomenon, WeatherConditionQualifier * qualifier)
Definition at line 1460 of file weather.c.
References _WeatherInfo::cond, FALSE, NULL, _WeatherConditions::phenomenon, PHENOMENON_INVALID, PHENOMENON_LAST, _WeatherConditions::qualifier, QUALIFIER_INVALID, QUALIFIER_LAST, _WeatherConditions::significant, TRUE, and _WeatherInfo::valid.
weather_info_get_value_dew()
gboolean weather_info_get_value_dew (WeatherInfo * info, TempUnit unit, gdouble * value)
Definition at line 1521 of file weather.c.
References _WeatherInfo::dew, FALSE, NULL, _WeatherInfo::temperature_unit, and _WeatherInfo::valid.
weather_info_get_value_moonphase()
gboolean weather_info_get_value_moonphase (WeatherInfo * info, WeatherMoonPhase * value, WeatherMoonLatitude * lat)
Definition at line 1587 of file weather.c.
References FALSE, _WeatherInfo::moonlatitude, _WeatherInfo::moonphase, _WeatherInfo::moonValid, NULL, TRUE, and _WeatherInfo::valid.
Referenced by weather_info_get_icon_name().
weather_info_get_value_pressure()
gboolean weather_info_get_value_pressure (WeatherInfo * info, PressureUnit unit, gdouble * value)
Definition at line 1625 of file weather.c.
References FALSE, NULL, _WeatherInfo::pressure, _WeatherInfo::pressure_unit, and _WeatherInfo::valid.
weather_info_get_value_sky()
gboolean weather_info_get_value_sky (WeatherInfo * info, WeatherSky * sky)
Definition at line 1443 of file weather.c.
References FALSE, NULL, _WeatherInfo::sky, SKY_INVALID, SKY_LAST, TRUE, and _WeatherInfo::valid.
weather_info_get_value_sunrise()
gboolean weather_info_get_value_sunrise (WeatherInfo * info, time_t * value)
Definition at line 1559 of file weather.c.
References FALSE, NULL, _WeatherInfo::sunrise, _WeatherInfo::sunriseValid, TRUE, and _WeatherInfo::valid.
Referenced by weather_info_setup_tooltip().
weather_info_get_value_sunset()
gboolean weather_info_get_value_sunset (WeatherInfo * info, time_t * value)
Definition at line 1573 of file weather.c.
References FALSE, NULL, _WeatherInfo::sunset, _WeatherInfo::sunsetValid, TRUE, and _WeatherInfo::valid.
Referenced by weather_info_setup_tooltip().
weather_info_get_value_temp()
gboolean weather_info_get_value_temp (WeatherInfo * info, TempUnit unit, gdouble * value)
Definition at line 1485 of file weather.c.
References FALSE, NULL, _WeatherInfo::temp, _WeatherInfo::temperature_unit, and _WeatherInfo::valid.
weather_info_get_value_temp_max()
gboolean weather_info_get_value_temp_max (WeatherInfo * info, TempUnit unit, gdouble * value)
Definition at line 1509 of file weather.c.
References FALSE, NULL, _WeatherInfo::temp_max, _WeatherInfo::temperature_unit, _WeatherInfo::tempMinMaxValid, and _WeatherInfo::valid.
weather_info_get_value_temp_min()
gboolean weather_info_get_value_temp_min (WeatherInfo * info, TempUnit unit, gdouble * value)
Definition at line 1497 of file weather.c.
References FALSE, NULL, _WeatherInfo::temp_min, _WeatherInfo::temperature_unit, _WeatherInfo::tempMinMaxValid, and _WeatherInfo::valid.
weather_info_get_value_update()
gboolean weather_info_get_value_update (WeatherInfo * info, time_t * value)
Definition at line 1545 of file weather.c.
References FALSE, NULL, TRUE, _WeatherInfo::update, and _WeatherInfo::valid.
weather_info_get_value_visibility()
gboolean weather_info_get_value_visibility (WeatherInfo * info, DistanceUnit unit, gdouble * value)
Definition at line 1637 of file weather.c.
References _WeatherInfo::distance_unit, FALSE, NULL, _WeatherInfo::valid, and _WeatherInfo::visibility.
weather_info_get_value_wind()
gboolean weather_info_get_value_wind (WeatherInfo * info, SpeedUnit unit, gdouble * speed, WeatherWindDirection * direction)
Definition at line 1604 of file weather.c.
References FALSE, NULL, _WeatherInfo::speed_unit, _WeatherInfo::valid, _WeatherInfo::wind, WIND_INVALID, WIND_LAST, and _WeatherInfo::windspeed.
weather_info_get_visibility()
const gchar * weather_info_get_visibility (WeatherInfo * info)
Definition at line 1017 of file weather.c.
References _, _WeatherInfo::distance_unit, DISTANCE_UNIT_DEFAULT, DISTANCE_UNIT_INVALID, DISTANCE_UNIT_KM, DISTANCE_UNIT_METERS, DISTANCE_UNIT_MILES, NULL, _WeatherInfo::pressure_unit, _WeatherInfo::valid, _WeatherInfo::visibility, VISIBILITY_SM_TO_KM, and VISIBILITY_SM_TO_M.
Referenced by main(), and mateweather_dialog_update().
weather_info_get_weather_summary()
gchar * weather_info_get_weather_summary (WeatherInfo * info)
Definition at line 1141 of file weather.c.
References _, NULL, _WeatherInfo::valid, weather_info_get_conditions(), weather_info_get_location_name(), and weather_info_get_sky().
weather_info_get_wind()
const gchar * weather_info_get_wind (WeatherInfo * info)
Definition at line 946 of file weather.c.
References _, NULL, _WeatherInfo::speed_unit, _WeatherInfo::valid, weather_wind_direction_string(), _WeatherInfo::wind, and _WeatherInfo::windspeed.
Referenced by main(), mateweather_dialog_update(), and weather_info_setup_tooltip().
weather_info_is_valid()
gboolean weather_info_is_valid (WeatherInfo * info)
Definition at line 641 of file weather.c.
References FALSE, NULL, and _WeatherInfo::valid.
weather_info_network_error()
gboolean weather_info_network_error (WeatherInfo * info)
Definition at line 648 of file weather.c.
References FALSE, _WeatherInfo::network_error, and NULL.
weather_info_to_imperial()
void weather_info_to_imperial (WeatherInfo * info)
Definition at line 666 of file weather.c.
References _WeatherInfo::distance_unit, DISTANCE_UNIT_MILES, NULL, _WeatherInfo::pressure_unit, PRESSURE_UNIT_INCH_HG, _WeatherInfo::speed_unit, SPEED_UNIT_MPH, TEMP_UNIT_FAHRENHEIT, and _WeatherInfo::temperature_unit.
weather_info_to_metric()
void weather_info_to_metric (WeatherInfo * info)
Definition at line 655 of file weather.c.
References _WeatherInfo::distance_unit, DISTANCE_UNIT_METERS, NULL, _WeatherInfo::pressure_unit, PRESSURE_UNIT_HPA, _WeatherInfo::speed_unit, SPEED_UNIT_MS, TEMP_UNIT_CENTIGRADE, and _WeatherInfo::temperature_unit.
Referenced by main().
weather_location_clone()
WeatherLocation * weather_location_clone (const WeatherLocation * location)
Definition at line 188 of file weather.c.
References _WeatherLocation::code, _WeatherLocation::coordinates, _WeatherLocation::country_code, _WeatherLocation::latitude, _WeatherLocation::latlon_valid, _WeatherLocation::longitude, _WeatherLocation::name, NULL, _WeatherLocation::radar, _WeatherLocation::tz_hint, weather_location_new(), and _WeatherLocation::zone.
Referenced by _weather_info_fill(), and weather_info_clone().
weather_location_equal()
gboolean weather_location_equal (const WeatherLocation * location1, const WeatherLocation * location2)
Definition at line 221 of file weather.c.
References _WeatherLocation::code, _WeatherLocation::name, and NULL.
Referenced by mateweather_update().
weather_location_free()
void weather_location_free (WeatherLocation * location)
Definition at line 205 of file weather.c.
References _WeatherLocation::code, _WeatherLocation::coordinates, _WeatherLocation::country_code, _WeatherLocation::name, _WeatherLocation::radar, _WeatherLocation::tz_hint, and _WeatherLocation::zone.
Referenced by mateweather_location_get_weather(), mateweather_prefs_load(), and weather_info_free().
weather_location_new()
WeatherLocation * weather_location_new (const gchar * name, const gchar * code, const gchar * zone, const gchar * radar, const gchar * coordinates, const gchar * country_code, const gchar * tz_hint)
Definition at line 121 of file weather.c.
References _WeatherLocation::code, _WeatherLocation::coordinates, _WeatherLocation::country_code, FALSE, _WeatherLocation::latitude, _WeatherLocation::latlon_valid, _WeatherLocation::longitude, name, _WeatherLocation::name, NULL, _WeatherLocation::radar, TRUE, _WeatherLocation::tz_hint, _WeatherLocation::zone, and _WeatherLocation::zone_valid.
Referenced by mateweather_location_to_weather_location(), mateweather_prefs_load(), and weather_location_clone().
weather_sky_string()
const gchar * weather_sky_string (WeatherSky sky)
Definition at line 261 of file weather.c.
References _, and SKY_LAST.
Referenced by weather_info_get_sky().
weather_wind_direction_string()
const gchar * weather_wind_direction_string (WeatherWindDirection wind)
Definition at line 244 of file weather.c.
References _, and WIND_LAST.
Referenced by weather_info_get_wind().