MATE Desktop Environment: weather-priv.h File Reference
weather-priv.h File Reference
#include "config.h"
#include <string.h>
#include <time.h>
#include <libintl.h>
#include <math.h>
#include <libsoup/soup.h>
#include "weather.h"
#include "mateweather-location.h"
Classes
struct _WeatherConditions
struct _WeatherInfo
Macros
#define _(str) (mateweather_gettext (str))
#define C_(context, str) (mateweather_dpgettext (context, str))
#define N_(str) (str)
#define xstrnstr(haystack, hlen, needle) memmem(haystack, hlen, needle, strlen(needle))
#define WEATHER_LOCATION_CODE_LEN 4
#define DATA_SIZE 5000
#define CONST_DIGITS "0123456789"
#define CONST_ALPHABET "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
#define TEMP_F_TO_C(f) (((f) - 32.0) * (5.0/9.0))
#define TEMP_F_TO_K(f) ((f + 459.67) * (5.0/9.0))
#define TEMP_C_TO_F(c) (((c) * (9.0/5.0)) + 32.0)
#define WINDSPEED_KNOTS_TO_KPH(knots) ((knots) * 1.851965)
#define WINDSPEED_KNOTS_TO_MPH(knots) ((knots) * 1.150779)
#define WINDSPEED_KNOTS_TO_MS(knots) ((knots) * 0.514444)
#define WINDSPEED_MS_TO_KNOTS(ms) ((ms) / 0.514444)
#define WINDSPEED_KNOTS_TO_BFT(knots) (pow ((knots) * 0.615363, 0.666666))
#define PRESSURE_INCH_TO_KPA(inch) ((inch) * 3.386)
#define PRESSURE_INCH_TO_HPA(inch) ((inch) * 33.86)
#define PRESSURE_INCH_TO_MM(inch) ((inch) * 25.40005)
#define PRESSURE_INCH_TO_MB(inch) (PRESSURE_INCH_TO_HPA (inch))
#define PRESSURE_INCH_TO_ATM(inch) ((inch) * 0.033421052)
#define PRESSURE_MBAR_TO_INCH(mbar) ((mbar) * 0.029533373)
#define VISIBILITY_SM_TO_KM(sm) ((sm) * 1.609344)
#define VISIBILITY_SM_TO_M(sm) (VISIBILITY_SM_TO_KM (sm) * 1000)
#define DEGREES_TO_RADIANS(deg) ((fmod ((deg),360.) / 180.) * M_PI)
#define RADIANS_TO_DEGREES(rad) ((rad) * 180. / M_PI)
#define RADIANS_TO_HOURS(rad) ((rad) * 12. / M_PI)
#define EPOCH_TO_J2000(t) ((gdouble)(t)-946727935.816)
#define MEAN_ECLIPTIC_LONGITUDE(d) (280.46457166 + (d)/36525.*35999.37244981)
#define SOL_PROGRESSION (360./365.242191)
#define PERIGEE_LONGITUDE(d) (282.93768193 + (d)/36525.*0.32327364)
Typedefs
typedef struct _WeatherConditions WeatherConditions
typedef gdouble WeatherTemperature
typedef gdouble WeatherHumidity
typedef gdouble WeatherWindSpeed
typedef gdouble WeatherPressure
typedef gdouble WeatherVisibility
typedef time_t WeatherUpdate
Functions
const char * mateweather_gettext (const char *str) G_GNUC_FORMAT(1)
const char * mateweather_dpgettext (const char *context, const char *str) G_GNUC_FORMAT(2)
WeatherLocation * mateweather_location_to_weather_location (MateWeatherLocation *gloc, const char *name)
const gchar * weather_wind_direction_string (WeatherWindDirection wind)
const gchar * weather_sky_string (WeatherSky sky)
const gchar * weather_conditions_string (WeatherConditions cond)
void metar_start_open (WeatherInfo *info)
void iwin_start_open (WeatherInfo *info)
void metoffice_start_open (WeatherInfo *info)
void bom_start_open (WeatherInfo *info)
void wx_start_open (WeatherInfo *info)
gboolean metar_parse (gchar *metar, WeatherInfo *info)
gboolean requests_init (WeatherInfo *info)
void request_done (WeatherInfo *info, GError *error)
void ecl2equ (gdouble t, gdouble eclipLon, gdouble eclipLat, gdouble *ra, gdouble *decl)
gdouble sunEclipLongitude (time_t t)
gboolean calc_sun (WeatherInfo *info)
gboolean calc_sun_time (WeatherInfo *info, time_t t)
gboolean calc_moon (WeatherInfo *info)
gboolean calc_moon_phases (WeatherInfo *info, time_t *phases)
void free_forecast_list (WeatherInfo *info)
Macro Definition Documentation
_
#define _ (str) (mateweather_gettext (str))
Definition at line 35 of file weather-priv.h.
C_
#define C_ (context, str) (mateweather_dpgettext (context, str))
Definition at line 36 of file weather-priv.h.
CONST_ALPHABET
#define CONST_ALPHABET "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
Definition at line 122 of file weather-priv.h.
CONST_DIGITS
#define CONST_DIGITS "0123456789"
Definition at line 121 of file weather-priv.h.
DATA_SIZE
#define DATA_SIZE 5000
Definition at line 119 of file weather-priv.h.
DEGREES_TO_RADIANS
#define DEGREES_TO_RADIANS (deg) ((fmod ((deg),360.) / 180.) * M_PI)
Definition at line 147 of file weather-priv.h.
EPOCH_TO_J2000
#define EPOCH_TO_J2000 (t) ((gdouble)(t)-946727935.816)
Definition at line 156 of file weather-priv.h.
MEAN_ECLIPTIC_LONGITUDE
#define MEAN_ECLIPTIC_LONGITUDE (d) (280.46457166 + (d)/36525.*35999.37244981)
Definition at line 157 of file weather-priv.h.
N_
#define N_ (str) (str)
Definition at line 37 of file weather-priv.h.
PERIGEE_LONGITUDE
#define PERIGEE_LONGITUDE (d) (282.93768193 + (d)/36525.*0.32327364)
Definition at line 159 of file weather-priv.h.
PRESSURE_INCH_TO_ATM
#define PRESSURE_INCH_TO_ATM (inch) ((inch) * 0.033421052)
Definition at line 141 of file weather-priv.h.
PRESSURE_INCH_TO_HPA
#define PRESSURE_INCH_TO_HPA (inch) ((inch) * 33.86)
Definition at line 138 of file weather-priv.h.
PRESSURE_INCH_TO_KPA
#define PRESSURE_INCH_TO_KPA (inch) ((inch) * 3.386)
Definition at line 137 of file weather-priv.h.
PRESSURE_INCH_TO_MB
#define PRESSURE_INCH_TO_MB (inch) (PRESSURE_INCH_TO_HPA (inch))
Definition at line 140 of file weather-priv.h.
PRESSURE_INCH_TO_MM
#define PRESSURE_INCH_TO_MM (inch) ((inch) * 25.40005)
Definition at line 139 of file weather-priv.h.
PRESSURE_MBAR_TO_INCH
#define PRESSURE_MBAR_TO_INCH (mbar) ((mbar) * 0.029533373)
Definition at line 142 of file weather-priv.h.
RADIANS_TO_DEGREES
#define RADIANS_TO_DEGREES (rad) ((rad) * 180. / M_PI)
Definition at line 148 of file weather-priv.h.
RADIANS_TO_HOURS
#define RADIANS_TO_HOURS (rad) ((rad) * 12. / M_PI)
Definition at line 149 of file weather-priv.h.
SOL_PROGRESSION
#define SOL_PROGRESSION (360./365.242191)
Definition at line 158 of file weather-priv.h.
TEMP_C_TO_F
#define TEMP_C_TO_F (c) (((c) * (9.0/5.0)) + 32.0)
Definition at line 128 of file weather-priv.h.
TEMP_F_TO_C
#define TEMP_F_TO_C (f) (((f) - 32.0) * (5.0/9.0))
Definition at line 126 of file weather-priv.h.
TEMP_F_TO_K
#define TEMP_F_TO_K (f) ((f + 459.67) * (5.0/9.0))
Definition at line 127 of file weather-priv.h.
VISIBILITY_SM_TO_KM
#define VISIBILITY_SM_TO_KM (sm) ((sm) * 1.609344)
Definition at line 144 of file weather-priv.h.
VISIBILITY_SM_TO_M
#define VISIBILITY_SM_TO_M (sm) (VISIBILITY_SM_TO_KM (sm) * 1000)
Definition at line 145 of file weather-priv.h.
WEATHER_LOCATION_CODE_LEN
#define WEATHER_LOCATION_CODE_LEN 4
Definition at line 41 of file weather-priv.h.
WINDSPEED_KNOTS_TO_BFT
#define WINDSPEED_KNOTS_TO_BFT (knots) (pow ((knots) * 0.615363, 0.666666))
Definition at line 135 of file weather-priv.h.
WINDSPEED_KNOTS_TO_KPH
#define WINDSPEED_KNOTS_TO_KPH (knots) ((knots) * 1.851965)
Definition at line 130 of file weather-priv.h.
WINDSPEED_KNOTS_TO_MPH
#define WINDSPEED_KNOTS_TO_MPH (knots) ((knots) * 1.150779)
Definition at line 131 of file weather-priv.h.
WINDSPEED_KNOTS_TO_MS
#define WINDSPEED_KNOTS_TO_MS (knots) ((knots) * 0.514444)
Definition at line 132 of file weather-priv.h.
WINDSPEED_MS_TO_KNOTS
#define WINDSPEED_MS_TO_KNOTS (ms) ((ms) / 0.514444)
Definition at line 133 of file weather-priv.h.
xstrnstr
#define xstrnstr (haystack, hlen, needle) memmem(haystack, hlen, needle, strlen(needle))
Definition at line 38 of file weather-priv.h.
Typedef Documentation
WeatherConditions
typedef struct _WeatherConditions WeatherConditions
Definition at line 56 of file weather-priv.h.
WeatherHumidity
typedef gdouble WeatherHumidity
Definition at line 59 of file weather-priv.h.
WeatherPressure
typedef gdouble WeatherPressure
Definition at line 61 of file weather-priv.h.
WeatherTemperature
typedef gdouble WeatherTemperature
Definition at line 58 of file weather-priv.h.
WeatherUpdate
typedef time_t WeatherUpdate
Definition at line 63 of file weather-priv.h.
WeatherVisibility
typedef gdouble WeatherVisibility
Definition at line 62 of file weather-priv.h.
WeatherWindSpeed
typedef gdouble WeatherWindSpeed
Definition at line 60 of file weather-priv.h.
Function Documentation
bom_start_open()
void bom_start_open (WeatherInfo * info)
Definition at line 72 of file weather-bom.c.
References _WeatherInfo::location, NULL, _WeatherInfo::requests_pending, _WeatherInfo::session, and _WeatherLocation::zone.
Referenced by iwin_start_open().
calc_moon()
gboolean calc_moon (WeatherInfo * info)
calc_moon: @info: WeatherInfo containing time_t of interest. The values moonphase, moonlatitude and moonValid are updated on success.
Returns: gboolean indicating success or failure. moonphase is expressed as degrees where '0' is a new moon, '90' is first quarter, etc.
Definition at line 65 of file weather-moon.c.
References DEGREES_TO_RADIANS, ecl2equ(), EPOCH_TO_J2000, LUNAR_INCLINATION, LUNAR_MEAN_LONGITUDE, LUNAR_NODE_MEAN_LONG, LUNAR_PERIGEE_MEAN_LONG, LUNAR_PROGRESSION, MEAN_ECLIPTIC_LONGITUDE, _WeatherInfo::moonlatitude, _WeatherInfo::moonphase, _WeatherInfo::moonValid, PERIGEE_LONGITUDE, RADIANS_TO_DEGREES, sunEclipLongitude(), TRUE, and _WeatherInfo::update.
Referenced by calc_moon_phases(), main(), and request_done().
calc_moon_phases()
gboolean calc_moon_phases (WeatherInfo * info, time_t * phases)
calc_moon_phases: @info: WeatherInfo containing the time_t of interest @phases: An array of four time_t values that will hold the returned values. The values are estimates of the time of the next new, quarter, full and three-quarter moons.
Returns: gboolean indicating success or failure
Definition at line 151 of file weather-moon.c.
References calc_moon(), FALSE, idx, LUNAR_PROGRESSION, _WeatherInfo::moonphase, _WeatherInfo::moonValid, NULL, TRUE, and _WeatherInfo::update.
Referenced by main(), and weather_info_get_upcoming_moonphases().
calc_sun()
gboolean calc_sun (WeatherInfo * info)
calc_sun: @info: WeatherInfo structure containing the observer's latitude and longitude in radians, fills in the sunrise and sunset times.
Returns: gboolean indicating if the results are valid.
Definition at line 308 of file weather-sun.c.
References calc_sun_time(), and NULL.
Referenced by request_done(), weather_info_get_sunrise(), weather_info_get_sunset(), and weather_info_next_sun_event().
calc_sun_time()
gboolean calc_sun_time (WeatherInfo * info, time_t t)
calc_sun_time: @info: WeatherInfo structure containing the observer's latitude and longitude in radians, fills in the sunrise and sunset times. @t: time_t
Returns: gboolean indicating if the results are valid.
Definition at line 295 of file weather-sun.c.
References _WeatherLocation::latlon_valid, and _WeatherInfo::location.
Referenced by calc_sun(), and main().
ecl2equ()
void ecl2equ (gdouble t, gdouble eclipLon, gdouble eclipLat, gdouble * ra, gdouble * decl)
Definition at line 99 of file weather-sun.c.
References RADIANS_TO_HOURS.
Referenced by calc_moon().
free_forecast_list()
void free_forecast_list (WeatherInfo * info)
Definition at line 364 of file weather.c.
References _WeatherInfo::forecast_list, NULL, and weather_info_free().
Referenced by _weather_info_fill(), iwin_start_open(), and weather_info_free().
iwin_start_open()
void iwin_start_open (WeatherInfo * info)
Definition at line 417 of file weather-iwin.c.
References bom_start_open(), _WeatherInfo::forecast, FORECAST_LIST, _WeatherInfo::forecast_type, free_forecast_list(), _WeatherLocation::latitude, _WeatherLocation::latlon_valid, _WeatherInfo::location, _WeatherLocation::longitude, metoffice_start_open(), NULL, RADIANS_TO_DEGREES, _WeatherInfo::requests_pending, _WeatherInfo::session, and _WeatherLocation::zone.
Referenced by _weather_info_fill().
mateweather_dpgettext()
const char * mateweather_dpgettext (const char * context, const char * str)
Definition at line 75 of file weather.c.
mateweather_gettext()
const char * mateweather_gettext (const char * str)
Definition at line 68 of file weather.c.
mateweather_location_to_weather_location()
WeatherLocation * mateweather_location_to_weather_location (MateWeatherLocation * gloc, const char * name)
Definition at line 749 of file mateweather-location.c.
References MATEWEATHER_LOCATION_CITY, mateweather_location_get_country(), mateweather_location_get_name(), name, NULL, and weather_location_new().
Referenced by mateweather_location_get_weather().
metar_parse()
gboolean metar_parse (gchar * metar, WeatherInfo * info)
Definition at line 430 of file weather-metar.c.
References FALSE, NULL, RE_NUM, TIME_RE, and TRUE.
Referenced by main().
metar_start_open()
void metar_start_open (WeatherInfo * info)
Definition at line 565 of file weather-metar.c.
References _, _WeatherLocation::code, FALSE, _WeatherInfo::location, _WeatherInfo::network_error, NULL, _WeatherInfo::requests_pending, _WeatherInfo::session, and _WeatherInfo::valid.
Referenced by _weather_info_fill().
metoffice_start_open()
void metoffice_start_open (WeatherInfo * info)
Definition at line 175 of file weather-met.c.
References _WeatherInfo::location, NULL, _WeatherInfo::requests_pending, _WeatherInfo::session, and _WeatherLocation::zone.
Referenced by iwin_start_open().
request_done()
void request_done (WeatherInfo * info, GError * error)
Definition at line 351 of file weather.c.
References calc_moon(), calc_sun(), _WeatherInfo::cb_data, error, _WeatherInfo::finish_cb, _WeatherInfo::moonValid, NULL, _WeatherInfo::requests_pending, and _WeatherInfo::valid.
requests_init()
gboolean requests_init (WeatherInfo * info)
Definition at line 343 of file weather.c.
References FALSE, _WeatherInfo::requests_pending, and TRUE.
Referenced by _weather_info_fill().
sunEclipLongitude()
gdouble sunEclipLongitude (time_t t)
Definition at line 46 of file weather-sun.c.
References DEGREES_TO_RADIANS, delta, ECCENTRICITY, EPOCH_TO_J2000, MEAN_ECLIPTIC_LONGITUDE, and PERIGEE_LONGITUDE.
Referenced by calc_moon().
weather_conditions_string()
const gchar * weather_conditions_string (WeatherConditions cond)
Definition at line 322 of file weather.c.
References _, _WeatherConditions::phenomenon, PHENOMENON_INVALID, PHENOMENON_LAST, _WeatherConditions::qualifier, QUALIFIER_INVALID, QUALIFIER_LAST, and _WeatherConditions::significant.
Referenced by weather_info_get_conditions().
weather_sky_string()
const gchar * weather_sky_string (WeatherSky sky)
Definition at line 261 of file weather.c.
References _, and SKY_LAST.
Referenced by weather_info_get_sky().
weather_wind_direction_string()
const gchar * weather_wind_direction_string (WeatherWindDirection wind)
Definition at line 244 of file weather.c.
References _, and WIND_LAST.
Referenced by weather_info_get_wind().
wx_start_open()
void wx_start_open (WeatherInfo * info)
Definition at line 77 of file weather-wx.c.
References _WeatherInfo::location, NULL, _WeatherInfo::radar, _WeatherLocation::radar, _WeatherInfo::radar_url, _WeatherInfo::requests_pending, and _WeatherInfo::session.
Referenced by _weather_info_fill().