MATE Desktop Environment: weather-sun.c File Reference
weather-sun.c File Reference
#include <math.h>
#include <time.h>
#include <glib.h>
#include "weather-priv.h"
Macros
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
#define ECCENTRICITY(d) (0.01671123 - (d)/36525.*0.00004392)
Functions
gdouble sunEclipLongitude (time_t t)
void ecl2equ (gdouble time, gdouble eclipLon, gdouble eclipLat, gdouble *ra, gdouble *decl)
gboolean calc_sun_time (WeatherInfo *info, time_t t)
gboolean calc_sun (WeatherInfo *info)
gint weather_info_next_sun_event (WeatherInfo *info)
Macro Definition Documentation
ECCENTRICITY
#define ECCENTRICITY (d) (0.01671123 - (d)/36525.*0.00004392)
Definition at line 38 of file weather-sun.c.
MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
Definition at line 35 of file weather-sun.c.
Function Documentation
calc_sun()
gboolean calc_sun (WeatherInfo * info)
calc_sun: @info: WeatherInfo structure containing the observer's latitude and longitude in radians, fills in the sunrise and sunset times.
Returns: gboolean indicating if the results are valid.
Definition at line 308 of file weather-sun.c.
References calc_sun_time(), and NULL.
Referenced by request_done(), weather_info_get_sunrise(), weather_info_get_sunset(), and weather_info_next_sun_event().
calc_sun_time()
gboolean calc_sun_time (WeatherInfo * info, time_t t)
calc_sun_time: @info: WeatherInfo structure containing the observer's latitude and longitude in radians, fills in the sunrise and sunset times. @t: time_t
Returns: gboolean indicating if the results are valid.
Definition at line 295 of file weather-sun.c.
References _WeatherLocation::latlon_valid, and _WeatherInfo::location.
Referenced by calc_sun(), and main().
ecl2equ()
void ecl2equ (gdouble time, gdouble eclipLon, gdouble eclipLat, gdouble * ra, gdouble * decl)
Definition at line 99 of file weather-sun.c.
References RADIANS_TO_HOURS.
Referenced by calc_moon().
sunEclipLongitude()
gdouble sunEclipLongitude (time_t t)
Definition at line 46 of file weather-sun.c.
References DEGREES_TO_RADIANS, delta, ECCENTRICITY, EPOCH_TO_J2000, MEAN_ECLIPTIC_LONGITUDE, and PERIGEE_LONGITUDE.
Referenced by calc_moon().
weather_info_next_sun_event()
gint weather_info_next_sun_event (WeatherInfo * info)
weather_info_next_sun_event: @info: WeatherInfo structure
Returns: the interval, in seconds, until the next "sun event":
local midnight, when rise and set times are recomputed
next sunrise, when icon changes to daytime version
next sunset, when icon changes to nighttime version
Definition at line 323 of file weather-sun.c.
References calc_sun(), NULL, _WeatherInfo::sunrise, _WeatherInfo::sunriseValid, _WeatherInfo::sunset, and _WeatherInfo::sunsetValid.