MATE Desktop Environment: window-private.h File Reference
window-private.h File Reference
#include <config.h>
#include "window.h"
#include "screen-private.h"
#include "util.h"
#include "stack.h"
#include "iconcache.h"
#include <X11/Xutil.h>
#include <cairo.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gtk/gtk.h>
Classes
struct _MetaWindow
Macros
#define NUMBER_OF_QUEUES 3
#define META_WINDOW_MAXIMIZED(w)
#define META_WINDOW_MAXIMIZED_VERTICALLY(w) ((w)->maximized_vertically)
#define META_WINDOW_MAXIMIZED_HORIZONTALLY(w) ((w)->maximized_horizontally)
#define META_WINDOW_SIDE_TILED(w)
#define META_WINDOW_TILED_LEFT(w)
#define META_WINDOW_TILED_RIGHT(w)
#define META_WINDOW_CORNER_TILED(w)
#define META_WINDOW_TILED(w) (META_WINDOW_SIDE_TILED(w) || META_WINDOW_CORNER_TILED(w))
#define META_WINDOW_ALLOWS_MOVE(w) ((w)->has_move_func && !(w)->fullscreen)
#define META_WINDOW_ALLOWS_RESIZE_EXCEPT_HINTS(w) ((w)->has_resize_func && !META_WINDOW_MAXIMIZED (w) && !(w)->fullscreen && !(w)->shaded)
#define META_WINDOW_ALLOWS_RESIZE(w)
#define META_WINDOW_ALLOWS_HORIZONTAL_RESIZE(w) (META_WINDOW_ALLOWS_RESIZE_EXCEPT_HINTS (w) && (w)->size_hints.min_width < (w)->size_hints.max_width)
#define META_WINDOW_ALLOWS_VERTICAL_RESIZE(w) (META_WINDOW_ALLOWS_RESIZE_EXCEPT_HINTS (w) && !META_WINDOW_SIDE_TILED(w) && (w)->size_hints.min_height < (w)->size_hints.max_height)
#define META_WINDOW_IN_NORMAL_TAB_CHAIN_TYPE(w) ((w)->type != META_WINDOW_DOCK && (w)->type != META_WINDOW_DESKTOP)
#define META_WINDOW_IN_NORMAL_TAB_CHAIN(w) (((w)->input || (w)->take_focus) && META_WINDOW_IN_NORMAL_TAB_CHAIN_TYPE (w) && (!(w)->skip_taskbar))
#define META_WINDOW_IN_DOCK_TAB_CHAIN(w) (((w)->input || (w)->take_focus) && (! META_WINDOW_IN_NORMAL_TAB_CHAIN_TYPE (w) || (w)->skip_taskbar))
#define META_WINDOW_IN_GROUP_TAB_CHAIN(w, g) (((w)->input || (w)->take_focus) && (!g || meta_window_get_group(w)==g))
Typedefs
typedef struct _MetaGroup MetaGroup
typedef struct _MetaWindowQueue MetaWindowQueue
typedef gboolean(* MetaWindowForeachFunc) (MetaWindow *window, void *data)
Enumerations
enum MetaWindowType {
META_WINDOW_NORMAL , META_WINDOW_DESKTOP , META_WINDOW_DOCK , META_WINDOW_DIALOG ,
META_WINDOW_MODAL_DIALOG , META_WINDOW_TOOLBAR , META_WINDOW_MENU , META_WINDOW_UTILITY ,
META_WINDOW_SPLASHSCREEN
}
enum MetaMaximizeFlags { META_MAXIMIZE_HORIZONTAL = 1 << 0 , META_MAXIMIZE_VERTICAL = 1 << 1 }
enum MetaClientType { META_CLIENT_TYPE_UNKNOWN = 0 , META_CLIENT_TYPE_APPLICATION = 1 , META_CLIENT_TYPE_PAGER = 2 , META_CLIENT_TYPE_MAX_RECOGNIZED = 2 }
enum MetaQueueType { META_QUEUE_CALC_SHOWING = 1 << 0 , META_QUEUE_MOVE_RESIZE = 1 << 1 , META_QUEUE_UPDATE_ICON = 1 << 2 }
enum MetaTileCycle {
META_TILE_CYCLE_NONE , META_TILE_CYCLE_50 , META_TILE_CYCLE_33 , META_TILE_CYCLE_25 ,
META_TILE_CYCLE_100 , META_TILE_CYCLE_75 , META_TILE_CYCLE_66
}
Functions
MetaWindow * meta_window_new (MetaDisplay *display, Window xwindow, gboolean must_be_viewable)
MetaWindow * meta_window_new_with_attrs (MetaDisplay *display, Window xwindow, gboolean must_be_viewable, XWindowAttributes *attrs)
void meta_window_free (MetaWindow *window, guint32 timestamp)
void meta_window_calc_showing (MetaWindow *window)
void meta_window_queue (MetaWindow *window, guint queuebits)
void meta_window_tile (MetaWindow *window)
void meta_window_untile (MetaWindow *window)
void meta_window_minimize (MetaWindow *window)
void meta_window_unminimize (MetaWindow *window)
void meta_window_maximize (MetaWindow *window, MetaMaximizeFlags directions)
void meta_window_maximize_internal (MetaWindow *window, MetaMaximizeFlags directions, MetaRectangle *saved_rect)
void meta_window_unmaximize (MetaWindow *window, MetaMaximizeFlags directions)
void meta_window_move_to_monitor (MetaWindow *window, const MetaXineramaScreenInfo *from_monitor, const MetaXineramaScreenInfo *to_monitor)
void meta_window_make_above (MetaWindow *window)
void meta_window_unmake_above (MetaWindow *window)
void meta_window_shade (MetaWindow *window, guint32 timestamp)
void meta_window_unshade (MetaWindow *window, guint32 timestamp)
void meta_window_change_workspace (MetaWindow *window, MetaWorkspace *workspace)
void meta_window_stick (MetaWindow *window)
void meta_window_unstick (MetaWindow *window)
void meta_window_activate (MetaWindow *window, guint32 current_time)
void meta_window_activate_with_workspace (MetaWindow *window, guint32 current_time, MetaWorkspace *workspace)
void meta_window_make_fullscreen_internal (MetaWindow *window)
void meta_window_make_fullscreen (MetaWindow *window)
void meta_window_unmake_fullscreen (MetaWindow *window)
void meta_window_update_fullscreen_monitors (MetaWindow *window, unsigned long top, unsigned long bottom, unsigned long left, unsigned long right)
gboolean meta_window_appears_focused (MetaWindow *window)
void meta_window_move (MetaWindow *window, gboolean user_op, int root_x_nw, int root_y_nw)
void meta_window_resize (MetaWindow *window, gboolean user_op, int w, int h)
void meta_window_move_resize (MetaWindow *window, gboolean user_op, int root_x_nw, int root_y_nw, int w, int h)
void meta_window_resize_with_gravity (MetaWindow *window, gboolean user_op, int w, int h, int gravity)
gboolean meta_window_showing_on_its_workspace (MetaWindow *window)
gboolean meta_window_should_be_showing (MetaWindow *window)
gboolean __window_is_terminal (MetaWindow *window)
void meta_window_update_struts (MetaWindow *window)
void meta_window_get_position (MetaWindow *window, int *x, int *y)
void meta_window_get_client_root_coords (MetaWindow *window, MetaRectangle *rect)
void meta_window_get_gravity_position (MetaWindow *window, int gravity, int *x, int *y)
void meta_window_get_geometry (MetaWindow *window, int *x, int *y, int *width, int *height)
void meta_window_get_input_rect (const MetaWindow *window, MetaRectangle *rect)
void meta_window_get_outer_rect (const MetaWindow *window, MetaRectangle *rect)
void meta_window_get_xor_rect (MetaWindow *window, const MetaRectangle *grab_wireframe_rect, MetaRectangle *xor_rect)
void meta_window_begin_wireframe (MetaWindow *window)
void meta_window_update_wireframe (MetaWindow *window, int x, int y, int width, int height)
void meta_window_end_wireframe (MetaWindow *window)
void meta_window_delete (MetaWindow *window, guint32 timestamp)
void meta_window_kill (MetaWindow *window)
void meta_window_focus (MetaWindow *window, guint32 timestamp)
void meta_window_raise (MetaWindow *window)
void meta_window_lower (MetaWindow *window)
void meta_window_update_unfocused_button_grabs (MetaWindow *window)
void meta_window_send_icccm_message (MetaWindow *window, Atom atom, guint32 timestamp)
void meta_window_move_resize_request (MetaWindow *window, guint value_mask, int gravity, int x, int y, int width, int height)
gboolean meta_window_configure_request (MetaWindow *window, XEvent *event)
gboolean meta_window_property_notify (MetaWindow *window, XEvent *event)
gboolean meta_window_client_message (MetaWindow *window, XEvent *event)
gboolean meta_window_notify_focus (MetaWindow *window, XEvent *event)
void meta_window_set_current_workspace_hint (MetaWindow *window)
unsigned long meta_window_get_net_wm_desktop (MetaWindow *window)
void meta_window_show_menu (MetaWindow *window, int root_x, int root_y, int button, guint32 timestamp)
gboolean meta_window_titlebar_is_onscreen (MetaWindow *window)
void meta_window_shove_titlebar_onscreen (MetaWindow *window)
void meta_window_set_gravity (MetaWindow *window, int gravity)
void meta_window_handle_mouse_grab_op_event (MetaWindow *window, XEvent *event)
MetaWorkspace * meta_window_get_workspace (MetaWindow *window)
GList * meta_window_get_workspaces (MetaWindow *window)
gboolean meta_window_located_on_workspace (MetaWindow *window, MetaWorkspace *workspace)
void meta_window_get_work_area_current_xinerama (MetaWindow *window, MetaRectangle *area)
void meta_window_get_work_area_for_xinerama (MetaWindow *window, int which_xinerama, MetaRectangle *area)
void meta_window_get_work_area_all_xineramas (MetaWindow *window, MetaRectangle *area)
void meta_window_get_current_tile_area (MetaWindow *window, MetaRectangle *tile_area)
gboolean meta_window_same_application (MetaWindow *window, MetaWindow *other_window)
void meta_window_refresh_resize_popup (MetaWindow *window)
void meta_window_free_delete_dialog (MetaWindow *window)
void meta_window_foreach_transient (MetaWindow *window, MetaWindowForeachFunc func, void *data)
gboolean meta_window_is_ancestor_of_transient (MetaWindow *window, MetaWindow *transient)
void meta_window_foreach_ancestor (MetaWindow *window, MetaWindowForeachFunc func, void *data)
MetaWindow * meta_window_find_root_ancestor (MetaWindow *window)
void meta_window_begin_grab_op (MetaWindow *window, MetaGrabOp op, gboolean frame_action, guint32 timestamp)
void meta_window_update_keyboard_resize (MetaWindow *window, gboolean update_cursor)
void meta_window_update_keyboard_move (MetaWindow *window)
void meta_window_update_layer (MetaWindow *window)
gboolean meta_window_get_icon_geometry (MetaWindow *window, MetaRectangle *rect)
const char * meta_window_get_startup_id (MetaWindow *window)
void meta_window_recalc_features (MetaWindow *window)
void meta_window_recalc_window_type (MetaWindow *window)
void meta_window_frame_size_changed (MetaWindow *window)
void meta_window_stack_just_below (MetaWindow *window, MetaWindow *below_this_one)
void meta_window_set_user_time (MetaWindow *window, guint32 timestamp)
void meta_window_set_demands_attention (MetaWindow *window)
void meta_window_unset_demands_attention (MetaWindow *window)
void meta_window_update_icon_now (MetaWindow *window)
gboolean meta_window_is_client_decorated (MetaWindow *window)
void meta_window_update_role (MetaWindow *window)
void meta_window_update_net_wm_type (MetaWindow *window)
gboolean meta_window_can_tile (MetaWindow *window)
Detailed Description
Windows which Marco manages
Managing X windows. This file contains methods on this class which are available to routines in core but not outside it. (See window.h for the routines which the rest of the world is allowed to use.)
Definition in file window-private.h.
Macro Definition Documentation
META_WINDOW_ALLOWS_HORIZONTAL_RESIZE
#define META_WINDOW_ALLOWS_HORIZONTAL_RESIZE (w) (META_WINDOW_ALLOWS_RESIZE_EXCEPT_HINTS (w) && (w)->size_hints.min_width < (w)->size_hints.max_width)
Definition at line 445 of file window-private.h.
META_WINDOW_ALLOWS_MOVE
#define META_WINDOW_ALLOWS_MOVE (w) ((w)->has_move_func && !(w)->fullscreen)
Definition at line 440 of file window-private.h.
META_WINDOW_ALLOWS_RESIZE
#define META_WINDOW_ALLOWS_RESIZE (w)
Value:
                                        (META_WINDOW_ALLOWS_RESIZE_EXCEPT_HINTS (w) &&                \
                                        (((w)->size_hints.min_width < (w)->size_hints.max_width) ||  \
                                         ((w)->size_hints.min_height < (w)->size_hints.max_height)))
Definition at line 442 of file window-private.h.
META_WINDOW_ALLOWS_RESIZE_EXCEPT_HINTS
#define META_WINDOW_ALLOWS_RESIZE_EXCEPT_HINTS (w) ((w)->has_resize_func && !META_WINDOW_MAXIMIZED (w) && !(w)->fullscreen && !(w)->shaded)
Definition at line 441 of file window-private.h.
META_WINDOW_ALLOWS_VERTICAL_RESIZE
#define META_WINDOW_ALLOWS_VERTICAL_RESIZE (w) (META_WINDOW_ALLOWS_RESIZE_EXCEPT_HINTS (w) && !META_WINDOW_SIDE_TILED(w) && (w)->size_hints.min_height < (w)->size_hints.max_height)
Definition at line 446 of file window-private.h.
META_WINDOW_CORNER_TILED
#define META_WINDOW_CORNER_TILED (w)
Value:
                                     ((w)->tiled &&                      \
                                     ((w)->tile_mode == META_TILE_BOTTOM_RIGHT || \
                                      (w)->tile_mode == META_TILE_BOTTOM_LEFT || \
                                      (w)->tile_mode == META_TILE_TOP_RIGHT || \
                                      (w)->tile_mode == META_TILE_TOP_LEFT))
Definition at line 434 of file window-private.h.
META_WINDOW_IN_DOCK_TAB_CHAIN
#define META_WINDOW_IN_DOCK_TAB_CHAIN (w) (((w)->input || (w)->take_focus) && (! META_WINDOW_IN_NORMAL_TAB_CHAIN_TYPE (w) || (w)->skip_taskbar))
Definition at line 652 of file window-private.h.
META_WINDOW_IN_GROUP_TAB_CHAIN
#define META_WINDOW_IN_GROUP_TAB_CHAIN (w, g) (((w)->input || (w)->take_focus) && (!g || meta_window_get_group(w)==g))
Definition at line 654 of file window-private.h.
META_WINDOW_IN_NORMAL_TAB_CHAIN
#define META_WINDOW_IN_NORMAL_TAB_CHAIN (w) (((w)->input || (w)->take_focus) && META_WINDOW_IN_NORMAL_TAB_CHAIN_TYPE (w) && (!(w)->skip_taskbar))
Definition at line 650 of file window-private.h.
META_WINDOW_IN_NORMAL_TAB_CHAIN_TYPE
#define META_WINDOW_IN_NORMAL_TAB_CHAIN_TYPE (w) ((w)->type != META_WINDOW_DOCK && (w)->type != META_WINDOW_DESKTOP)
Definition at line 648 of file window-private.h.
META_WINDOW_MAXIMIZED
#define META_WINDOW_MAXIMIZED (w)
Value:
                                        ((w)->maximized_horizontally && \
                                        (w)->maximized_vertically)
Definition at line 423 of file window-private.h.
META_WINDOW_MAXIMIZED_HORIZONTALLY
#define META_WINDOW_MAXIMIZED_HORIZONTALLY (w) ((w)->maximized_horizontally)
Definition at line 426 of file window-private.h.
META_WINDOW_MAXIMIZED_VERTICALLY
#define META_WINDOW_MAXIMIZED_VERTICALLY (w) ((w)->maximized_vertically)
Definition at line 425 of file window-private.h.
META_WINDOW_SIDE_TILED
#define META_WINDOW_SIDE_TILED (w)
Value:
                                             ((w)->tiled &&              \
                                             ((w)->tile_mode == META_TILE_LEFT || \
                                              (w)->tile_mode == META_TILE_RIGHT))
Definition at line 427 of file window-private.h.
META_WINDOW_TILED
#define META_WINDOW_TILED (w) (META_WINDOW_SIDE_TILED(w) || META_WINDOW_CORNER_TILED(w))
Definition at line 439 of file window-private.h.
META_WINDOW_TILED_LEFT
#define META_WINDOW_TILED_LEFT (w)
Value:
                                   (META_WINDOW_SIDE_TILED(w) &&         \
                                   (w)->tile_mode == META_TILE_LEFT)
Definition at line 430 of file window-private.h.
META_WINDOW_TILED_RIGHT
#define META_WINDOW_TILED_RIGHT (w)
Value:
                                    (META_WINDOW_SIDE_TILED(w) && \
                                    (w)->tile_mode == META_TILE_RIGHT)
Definition at line 432 of file window-private.h.
NUMBER_OF_QUEUES
#define NUMBER_OF_QUEUES 3
Definition at line 98 of file window-private.h.
Typedef Documentation
MetaGroup
typedef struct _MetaGroup MetaGroup
Definition at line 50 of file window-private.h.
MetaWindowForeachFunc
typedef gboolean(* MetaWindowForeachFunc) (MetaWindow *window, void *data)
Definition at line 53 of file window-private.h.
MetaWindowQueue
typedef struct _MetaWindowQueue MetaWindowQueue
Definition at line 51 of file window-private.h.
Enumeration Type Documentation
MetaClientType
enum MetaClientType
Enumerator
META_CLIENT_TYPE_UNKNOWN
META_CLIENT_TYPE_APPLICATION
META_CLIENT_TYPE_PAGER
META_CLIENT_TYPE_MAX_RECOGNIZED
Definition at line 75 of file window-private.h.
MetaMaximizeFlags
enum MetaMaximizeFlags
Enumerator
META_MAXIMIZE_HORIZONTAL
META_MAXIMIZE_VERTICAL
Definition at line 69 of file window-private.h.
MetaQueueType
enum MetaQueueType
Enumerator
META_QUEUE_CALC_SHOWING
META_QUEUE_MOVE_RESIZE
META_QUEUE_UPDATE_ICON
Definition at line 82 of file window-private.h.
MetaTileCycle
enum MetaTileCycle
Enumerator
META_TILE_CYCLE_NONE
META_TILE_CYCLE_50
META_TILE_CYCLE_33
META_TILE_CYCLE_25
META_TILE_CYCLE_100
META_TILE_CYCLE_75
META_TILE_CYCLE_66
Definition at line 88 of file window-private.h.
MetaWindowType
enum MetaWindowType
Enumerator
META_WINDOW_NORMAL
META_WINDOW_DESKTOP
META_WINDOW_DOCK
META_WINDOW_DIALOG
META_WINDOW_MODAL_DIALOG
META_WINDOW_TOOLBAR
META_WINDOW_MENU
META_WINDOW_UTILITY
META_WINDOW_SPLASHSCREEN
Definition at line 56 of file window-private.h.
Function Documentation
__window_is_terminal()
gboolean __window_is_terminal (MetaWindow * window)
Definition at line 1941 of file window.c.
References FALSE, NULL, _MetaWindow::res_class, and TRUE.
Referenced by meta_window_set_user_time().
meta_window_activate()
void meta_window_activate (MetaWindow * window, guint32 current_time)
Definition at line 3240 of file window.c.
References META_CLIENT_TYPE_PAGER, NULL, _MetaWindow::on_all_workspaces, and _MetaWindow::workspace.
meta_window_activate_with_workspace()
void meta_window_activate_with_workspace (MetaWindow * window, guint32 current_time, MetaWorkspace * workspace)
Definition at line 3254 of file window.c.
References META_CLIENT_TYPE_APPLICATION.
meta_window_appears_focused()
gboolean meta_window_appears_focused (MetaWindow * window)
Definition at line 8936 of file window.c.
References FALSE, _MetaWindow::has_focus, meta_prefs_get_attach_modal_dialogs(), META_WINDOW_DOCK, meta_window_foreach_transient(), META_WINDOW_SPLASHSCREEN, TRUE, and _MetaWindow::type.
Referenced by meta_frame_get_flags().
meta_window_begin_grab_op()
void meta_window_begin_grab_op (MetaWindow * window, MetaGrabOp op, gboolean frame_action, guint32 timestamp)
Definition at line 8667 of file window.c.
References _MetaWindow::display, FALSE, meta_display_begin_grab_op(), op, and _MetaWindow::screen.
Referenced by meta_window_client_message().
meta_window_begin_wireframe()
void meta_window_begin_wireframe (MetaWindow * window)
Definition at line 4287 of file window.c.
References _MetaWindow::display, _MetaDisplay::grab_wireframe_last_display_height, _MetaDisplay::grab_wireframe_last_display_width, _MetaDisplay::grab_wireframe_last_xor_rect, _MetaDisplay::grab_wireframe_rect, meta_effects_begin_wireframe(), meta_window_get_client_root_coords(), meta_window_get_xor_rect(), and _MetaWindow::screen.
Referenced by meta_display_begin_grab_op().
meta_window_calc_showing()
void meta_window_calc_showing (MetaWindow * window)
Definition at line 1546 of file window.c.
References meta_window_should_be_showing().
Referenced by meta_display_begin_grab_op(), and meta_display_end_grab_op().
meta_window_can_tile()
gboolean meta_window_can_tile (MetaWindow * window)
Definition at line 2759 of file window.c.
References FALSE, _MetaWindow::frame, _MetaRectangle::height, meta_frame_calc_borders(), meta_screen_get_current_xinerama(), meta_window_get_work_area_for_xinerama(), _MetaXineramaScreenInfo::number, _MetaWindow::screen, _MetaWindow::shaded, _MetaWindow::size_hints, _MetaFrameBorders::visible, and _MetaRectangle::width.
meta_window_change_workspace()
void meta_window_change_workspace (MetaWindow * window, MetaWorkspace * workspace)
Definition at line 4534 of file window.c.
References meta_window_foreach_ancestor(), and meta_window_foreach_transient().
Referenced by meta_core_change_workspace(), meta_window_client_message(), meta_window_focus(), and meta_workspace_activate_with_focus().
meta_window_client_message()
gboolean meta_window_client_message (MetaWindow * window, XEvent * event)
Definition at line 5131 of file window.c.
References _NET_WM_MOVERESIZE_CANCEL, _NET_WM_MOVERESIZE_MOVE, _NET_WM_MOVERESIZE_MOVE_KEYBOARD, _NET_WM_MOVERESIZE_SIZE_BOTTOM, _NET_WM_MOVERESIZE_SIZE_BOTTOMLEFT, _NET_WM_MOVERESIZE_SIZE_BOTTOMRIGHT, _NET_WM_MOVERESIZE_SIZE_KEYBOARD, _NET_WM_MOVERESIZE_SIZE_LEFT, _NET_WM_MOVERESIZE_SIZE_RIGHT, _NET_WM_MOVERESIZE_SIZE_TOP, _NET_WM_MOVERESIZE_SIZE_TOPLEFT, _NET_WM_MOVERESIZE_SIZE_TOPRIGHT, _NET_WM_STATE_ADD, _NET_WM_STATE_TOGGLE, action, _MetaWindow::desc, _MetaWindow::display, FALSE, _MetaWindow::fullscreen, _MetaWindow::has_fullscreen_func, _MetaWindow::has_maximize_func, _MetaWindow::has_move_func, _MetaWindow::has_resize_func, _MetaWindow::has_shade_func, mask, _MetaWindow::maximized_horizontally, _MetaWindow::maximized_vertically, META_CLIENT_TYPE_MAX_RECOGNIZED, META_CLIENT_TYPE_UNKNOWN, META_DEBUG_WINDOW_OPS, meta_display_begin_grab_op(), meta_display_end_grab_op(), meta_display_get_current_time(), meta_display_get_current_time_roundtrip(), meta_error_trap_pop(), meta_error_trap_pop_with_return(), meta_error_trap_push(), META_GRAB_OP_KEYBOARD_MOVING, META_GRAB_OP_KEYBOARD_RESIZING_UNKNOWN, META_GRAB_OP_MOVING, META_GRAB_OP_NONE, META_GRAB_OP_RESIZING_E, META_GRAB_OP_RESIZING_N, META_GRAB_OP_RESIZING_NE, META_GRAB_OP_RESIZING_NW, META_GRAB_OP_RESIZING_S, META_GRAB_OP_RESIZING_SE, META_GRAB_OP_RESIZING_SW, META_GRAB_OP_RESIZING_W, meta_is_verbose(), META_MAXIMIZE_HORIZONTAL, META_MAXIMIZE_VERTICAL, meta_prefs_get_raise_on_click(), META_QUEUE_MOVE_RESIZE, meta_screen_get_workspace_by_index(), meta_warning(), meta_window_begin_grab_op(), meta_window_change_workspace(), meta_window_delete(), meta_window_make_fullscreen(), meta_window_maximize(), meta_window_minimize(), meta_window_move_resize_request(), meta_window_queue(), meta_window_raise(), meta_window_set_demands_attention(), meta_window_shade(), meta_window_show_menu(), meta_window_stick(), meta_window_unmake_fullscreen(), meta_window_unmaximize(), meta_window_unset_demands_attention(), meta_window_unshade(), meta_window_unstick(), meta_window_update_fullscreen_monitors(), meta_window_update_layer(), meta_XFree, NULL, _MetaWindow::on_all_workspaces, op, _MetaWindow::screen, _MetaWindow::shaded, _MetaWindow::size_hints, _MetaWindow::skip_pager, _MetaWindow::skip_taskbar, TRUE, _MetaWindow::wm_state_above, _MetaWindow::wm_state_below, _MetaWindow::wm_state_demands_attention, _MetaWindow::wm_state_modal, _MetaWindow::wm_state_skip_pager, _MetaWindow::wm_state_skip_taskbar, _MetaDisplay::xdisplay, and _MetaWindow::xwindow.
meta_window_configure_request()
gboolean meta_window_configure_request (MetaWindow * window, XEvent * event)
Definition at line 5027 of file window.c.
References _MetaWindow::border_width, _MetaWindow::desc, _MetaWindow::display, _MetaDisplay::expected_focus_window, META_DEBUG_STACK, meta_prefs_get_disable_workarounds(), meta_window_lower(), meta_window_move_resize_request(), meta_window_raise(), meta_window_same_application(), meta_window_set_demands_attention(), _MetaWindow::net_wm_user_time, _MetaWindow::size_hints, TRUE, and XSERVER_TIME_IS_BEFORE.
meta_window_delete()
void meta_window_delete (MetaWindow * window, guint32 timestamp)
Definition at line 123 of file delete.c.
References _MetaWindow::delete_window, _MetaWindow::desc, _MetaWindow::display, FALSE, META_DEBUG_WINDOW_OPS, meta_display_ping_window(), meta_error_trap_pop(), meta_error_trap_push(), meta_window_send_icccm_message(), _MetaDisplay::xdisplay, and _MetaWindow::xwindow.
Referenced by meta_core_delete(), and meta_window_client_message().
meta_window_end_wireframe()
void meta_window_end_wireframe (MetaWindow * window)
Definition at line 4346 of file window.c.
References _MetaWindow::display, _MetaDisplay::grab_window, _MetaDisplay::grab_wireframe_last_display_height, _MetaDisplay::grab_wireframe_last_display_width, _MetaDisplay::grab_wireframe_last_xor_rect, meta_effects_end_wireframe(), and _MetaWindow::screen.
Referenced by meta_display_end_grab_op().
meta_window_find_root_ancestor()
MetaWindow * meta_window_find_root_ancestor (MetaWindow * window)
Definition at line 4739 of file window.c.
References meta_window_foreach_ancestor().
Referenced by meta_window_compute_group(), and meta_window_raise().
meta_window_focus()
void meta_window_focus (MetaWindow * window, guint32 timestamp)
Definition at line 4410 of file window.c.
References _MetaScreen::active_workspace, _MetaWindow::all_keys_grabbed, _MetaWindow::desc, _MetaWindow::display, _MetaDisplay::expected_focus_window, FALSE, _MetaWindow::frame, _MetaDisplay::grab_window, _MetaWindow::input, _MetaWindow::mapped, META_DEBUG_FOCUS, meta_display_set_input_focus_window(), meta_effect_run_focus(), meta_window_change_workspace(), meta_window_send_icccm_message(), meta_window_unset_demands_attention(), NULL, _MetaWindow::on_all_workspaces, _MetaWindow::screen, _MetaWindow::shaded, _MetaWindow::take_focus, TRUE, _MetaWindow::unmanaging, _MetaWindow::wm_state_demands_attention, and _MetaWindow::workspace.
Referenced by meta_core_show_window_menu(), meta_core_user_focus(), meta_screen_show_desktop(), meta_window_grab_all_keys(), meta_window_shade(), meta_window_unshade(), meta_workspace_activate_with_focus(), and meta_workspace_focus_default_window().
meta_window_foreach_ancestor()
void meta_window_foreach_ancestor (MetaWindow * window, MetaWindowForeachFunc func, void * data)
Definition at line 8463 of file window.c.
References data, _MetaWindow::display, meta_display_lookup_x_window(), NULL, _MetaWindow::transient_parent_is_root_window, TRUE, and _MetaWindow::xtransient_for.
Referenced by meta_window_change_workspace(), meta_window_find_root_ancestor(), meta_window_is_ancestor_of_transient(), and meta_window_showing_on_its_workspace().
meta_window_foreach_transient()
void meta_window_foreach_transient (MetaWindow * window, MetaWindowForeachFunc func, void * data)
Definition at line 8436 of file window.c.
References data, _MetaWindow::display, meta_display_list_windows(), meta_window_is_ancestor_of_transient(), and NULL.
Referenced by meta_window_appears_focused(), meta_window_change_workspace(), meta_window_minimize(), meta_window_new_with_attrs(), meta_window_stick(), meta_window_unminimize(), and meta_window_unstick().
meta_window_frame_size_changed()
void meta_window_frame_size_changed (MetaWindow * window)
Definition at line 6621 of file window.c.
References _MetaWindow::frame, and meta_frame_clear_cached_borders().
Referenced by meta_window_make_above(), meta_window_maximize_internal(), meta_window_shade(), meta_window_unmake_above(), meta_window_unmaximize(), and meta_window_unshade().
meta_window_free()
void meta_window_free (MetaWindow * window, guint32 timestamp)
Definition at line 1004 of file window.c.
References _MetaScreen::active_workspace, _MetaWindow::border_width, _MetaDisplay::compositor, _MetaWindow::desc, _MetaWindow::display, _MetaDisplay::expected_focus_window, FALSE, _MetaDisplay::focus_window, _MetaWindow::frame, _MetaWindow::fullscreen, _MetaDisplay::grab_window, _MetaWindow::has_focus, _MetaWindow::maximized_horizontally, _MetaWindow::maximized_vertically, meta_bug(), meta_compositor_free_window(), meta_compositor_set_active_window(), META_DEBUG_FOCUS, META_DEBUG_WORKAREA, meta_display_end_grab_op(), META_DISPLAY_HAS_SHAPE, meta_display_ungrab_focus_window_button(), meta_display_ungrab_window_buttons(), meta_display_unregister_x_window(), meta_error_trap_pop(), meta_error_trap_push(), meta_group_update_layers(), META_QUEUE_CALC_SHOWING, META_QUEUE_MOVE_RESIZE, META_QUEUE_UPDATE_ICON, meta_stack_freeze(), meta_stack_remove(), meta_stack_thaw(), meta_ui_window_menu_free(), meta_window_destroy_frame(), meta_window_free_delete_dialog(), meta_window_get_group(), meta_window_shutdown_group(), meta_window_ungrab_keys(), meta_workspace_focus_default_window(), meta_workspace_remove_window(), _MetaWindow::minimized, _MetaWorkspace::mru_list, NULL, _MetaWindow::screen, _MetaScreen::stack, _MetaWindow::struts, TRUE, _MetaWindow::unmanaging, _MetaWindow::user_time_window, _MetaDisplay::window_menu, _MetaDisplay::window_with_menu, _MetaWorkspace::windows, _MetaWindow::withdrawn, _MetaWindow::workspace, _MetaScreen::workspaces, _MetaDisplay::xdisplay, and _MetaWindow::xwindow.
Referenced by meta_display_unmanage_windows_for_screen().
meta_window_free_delete_dialog()
void meta_window_free_delete_dialog (MetaWindow * window)
Definition at line 195 of file delete.c.
References _MetaWindow::dialog_pid.
Referenced by meta_window_free().
meta_window_get_client_root_coords()
void meta_window_get_client_root_coords (MetaWindow * window, MetaRectangle * rect)
Definition at line 4066 of file window.c.
References _MetaRectangle::height, meta_window_get_position(), _MetaWindow::rect, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_display_begin_grab_op(), meta_window_begin_wireframe(), meta_window_move_to_monitor(), meta_window_refresh_resize_popup(), and meta_window_unmaximize().
meta_window_get_current_tile_area()
void meta_window_get_current_tile_area (MetaWindow * window, MetaRectangle * tile_area)
Definition at line 8250 of file window.c.
References _MetaRectangle::height, int(), meta_screen_get_xinerama_for_window(), META_TILE_BOTTOM_LEFT, META_TILE_BOTTOM_RIGHT, META_TILE_CYCLE_100, META_TILE_CYCLE_25, META_TILE_CYCLE_33, META_TILE_CYCLE_50, META_TILE_CYCLE_66, META_TILE_CYCLE_75, META_TILE_CYCLE_NONE, META_TILE_MAXIMIZED, META_TILE_NONE, META_TILE_RIGHT, META_TILE_TOP_LEFT, META_TILE_TOP_RIGHT, meta_warning(), meta_window_get_work_area_for_xinerama(), _MetaScreen::n_xinerama_infos, _MetaXineramaScreenInfo::number, _MetaWindow::screen, _MetaWindow::tile_cycle, _MetaWindow::tile_mode, _MetaWindow::tile_monitor_number, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_window_unmake_fullscreen().
meta_window_get_geometry()
void meta_window_get_geometry (MetaWindow * window, int * x, int * y, int * width, int * height)
Definition at line 4159 of file window.c.
References _MetaRectangle::height, meta_window_get_gravity_position(), _MetaWindow::rect, _MetaWindow::size_hints, and _MetaRectangle::width.
meta_window_get_gravity_position()
void meta_window_get_gravity_position (MetaWindow * window, int gravity, int * x, int * y)
Definition at line 4075 of file window.c.
References _MetaFrame::child_x, _MetaFrame::child_y, _MetaWindow::frame, _MetaRectangle::height, NULL, _MetaFrame::rect, _MetaWindow::rect, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_window_get_geometry(), and meta_window_move_resize_request().
meta_window_get_icon_geometry()
gboolean meta_window_get_icon_geometry (MetaWindow * window, MetaRectangle * rect)
Definition at line 5921 of file window.c.
References _MetaWindow::desc, _MetaWindow::display, FALSE, _MetaRectangle::height, meta_prop_get_cardinal_list(), meta_XFree, NULL, TRUE, _MetaRectangle::width, _MetaRectangle::x, _MetaWindow::xwindow, and _MetaRectangle::y.
Referenced by meta_screen_ensure_tab_popup().
meta_window_get_input_rect()
void meta_window_get_input_rect (const MetaWindow * window, MetaRectangle * rect)
meta_window_get_input_rect: @window: a MetaWindow @rect: (out): pointer to an allocated MetaRectangle
Gets the rectangle that bounds @window that is responsive to mouse events. This includes decorations - the visible portion of its border - and (if present) any invisible area that we make make responsive to mouse clicks in order to allow convenient border dragging.
Definition at line 4186 of file window.c.
References _MetaWindow::frame, _MetaFrame::rect, and _MetaWindow::rect.
meta_window_get_net_wm_desktop()
unsigned long meta_window_get_net_wm_desktop (MetaWindow * window)
Definition at line 4655 of file window.c.
References meta_workspace_index(), _MetaWindow::on_all_workspaces, and _MetaWindow::workspace.
Referenced by meta_core_get(), meta_window_set_current_workspace_hint(), and meta_window_show_menu().
meta_window_get_outer_rect()
void meta_window_get_outer_rect (const MetaWindow * window, MetaRectangle * rect)
meta_window_get_outer_rect: @window: a MetaWindow @rect: (out): pointer to an allocated MetaRectangle
Gets the rectangle that bounds @window that is responsive to mouse events. This includes only what is visible; it doesn't include any extra reactive area we add to the edges of windows.
Definition at line 4205 of file window.c.
References _MetaWindow::custom_frame_extents, _MetaWindow::frame, _MetaWindow::has_custom_frame_extents, _MetaRectangle::height, _MetaFrameBorders::invisible, meta_frame_calc_borders(), _MetaFrame::rect, _MetaWindow::rect, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_screen_ensure_tab_popup(), meta_screen_get_xinerama_for_window(), meta_window_edge_resistance_for_move(), meta_window_edge_resistance_for_resize(), meta_window_place(), meta_window_set_demands_attention(), meta_window_shove_titlebar_onscreen(), and meta_window_titlebar_is_onscreen().
meta_window_get_position()
void meta_window_get_position (MetaWindow * window, int * x, int * y)
Definition at line 4045 of file window.c.
References _MetaFrame::child_x, _MetaFrame::child_y, _MetaWindow::frame, _MetaFrame::rect, _MetaWindow::rect, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_core_get(), meta_window_get_client_root_coords(), meta_window_place(), meta_window_resize(), and meta_window_resize_with_gravity().
meta_window_get_startup_id()
const char * meta_window_get_startup_id (MetaWindow * window)
Definition at line 4355 of file window.c.
References meta_group_get_startup_id(), meta_window_get_group(), NULL, and _MetaWindow::startup_id.
Referenced by meta_screen_apply_startup_properties().
meta_window_get_work_area_all_xineramas()
void meta_window_get_work_area_all_xineramas (MetaWindow * window, MetaRectangle * area)
Definition at line 8224 of file window.c.
References _MetaWindow::desc, _MetaRectangle::height, META_DEBUG_WORKAREA, meta_rectangle_intersect(), meta_window_get_workspaces(), meta_workspace_get_work_area_all_xineramas(), NULL, _MetaScreen::rect, _MetaWindow::screen, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
meta_window_get_work_area_current_xinerama()
void meta_window_get_work_area_current_xinerama (MetaWindow * window, MetaRectangle * area)
Definition at line 8199 of file window.c.
References meta_screen_get_xinerama_for_window(), meta_window_get_work_area_for_xinerama(), NULL, _MetaXineramaScreenInfo::number, and _MetaWindow::screen.
meta_window_get_work_area_for_xinerama()
void meta_window_get_work_area_for_xinerama (MetaWindow * window, int which_xinerama, MetaRectangle * area)
Definition at line 8212 of file window.c.
Referenced by meta_window_can_tile(), meta_window_get_current_tile_area(), meta_window_get_work_area_current_xinerama(), and meta_window_place().
meta_window_get_workspace()
MetaWorkspace * meta_window_get_workspace (MetaWindow * window)
Definition at line 6259 of file window.c.
References _MetaScreen::active_workspace, _MetaWindow::on_all_workspaces, _MetaWindow::screen, and _MetaWindow::workspace.
Referenced by meta_stack_lower(), and meta_stack_raise().
meta_window_get_workspaces()
GList * meta_window_get_workspaces (MetaWindow * window)
Definition at line 6268 of file window.c.
References _MetaWorkspace::list_containing_self, _MetaWindow::on_all_workspaces, _MetaWindow::screen, _MetaWindow::workspace, and _MetaScreen::workspaces.
Referenced by meta_window_get_work_area_all_xineramas().
meta_window_get_xor_rect()
void meta_window_get_xor_rect (MetaWindow * window, const MetaRectangle * grab_wireframe_rect, MetaRectangle * xor_rect)
Definition at line 4235 of file window.c.
References _MetaFrame::bottom_height, _MetaFrame::child_x, _MetaFrame::child_y, _MetaWindow::frame, _MetaRectangle::height, _MetaFrame::right_width, _MetaWindow::shaded, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_window_begin_wireframe(), meta_window_edge_resistance_for_move(), meta_window_edge_resistance_for_resize(), and meta_window_update_wireframe().
meta_window_handle_mouse_grab_op_event()
void meta_window_handle_mouse_grab_op_event (MetaWindow * window, XEvent * event)
Definition at line 8006 of file window.c.
References _MetaDisplay::compositor, _MetaWindow::disable_sync, _MetaWindow::display, FALSE, _MetaDisplay::grab_last_user_action_was_snap, _MetaDisplay::grab_latest_motion_x, _MetaDisplay::grab_latest_motion_y, _MetaDisplay::grab_op, meta_compositor_set_updates(), META_DEBUG_RESIZING, meta_display_check_threshold_reached(), meta_display_end_grab_op(), meta_grab_op_is_moving(), meta_grab_op_is_resizing(), META_GRAB_OP_KEYBOARD_RESIZING_E, META_GRAB_OP_KEYBOARD_RESIZING_N, META_GRAB_OP_KEYBOARD_RESIZING_NE, META_GRAB_OP_KEYBOARD_RESIZING_NW, META_GRAB_OP_KEYBOARD_RESIZING_S, META_GRAB_OP_KEYBOARD_RESIZING_SE, META_GRAB_OP_KEYBOARD_RESIZING_SW, META_GRAB_OP_KEYBOARD_RESIZING_W, META_GRAB_OP_RESIZING_E, META_GRAB_OP_RESIZING_N, META_GRAB_OP_RESIZING_NE, META_GRAB_OP_RESIZING_NW, META_GRAB_OP_RESIZING_S, META_GRAB_OP_RESIZING_SE, META_GRAB_OP_RESIZING_SW, META_GRAB_OP_RESIZING_W, META_MAXIMIZE_HORIZONTAL, META_MAXIMIZE_VERTICAL, META_TILE_MAXIMIZED, META_TILE_NONE, meta_window_maximize(), meta_window_tile(), _MetaWindow::screen, _MetaWindow::tile_mode, TRUE, and _MetaScreen::xroot.
meta_window_is_ancestor_of_transient()
gboolean meta_window_is_ancestor_of_transient (MetaWindow * window, MetaWindow * transient)
Definition at line 8532 of file window.c.
References FALSE, and meta_window_foreach_ancestor().
Referenced by meta_window_foreach_transient().
meta_window_is_client_decorated()
gboolean meta_window_is_client_decorated (MetaWindow * window)
meta_window_is_client_decorated:
Check if if the window has decorations drawn by the client. (window->decorated refers only to whether we should add decorations)
Definition at line 9039 of file window.c.
References _MetaWindow::has_custom_frame_extents.
Referenced by meta_window_move_resize_request().
meta_window_kill()
void meta_window_kill (MetaWindow * window)
Definition at line 154 of file delete.c.
References _, _MetaWindow::desc, _MetaWindow::display, FALSE, META_DEBUG_WINDOW_OPS, meta_error_trap_pop(), meta_error_trap_push(), meta_warning(), _MetaWindow::net_wm_pid, NULL, _MetaWindow::wm_client_machine, _MetaDisplay::xdisplay, and _MetaWindow::xwindow.
meta_window_located_on_workspace()
gboolean meta_window_located_on_workspace (MetaWindow * window, MetaWorkspace * workspace)
Definition at line 1347 of file window.c.
References _MetaWindow::on_all_workspaces, _MetaWindow::screen, _MetaWorkspace::screen, and _MetaWindow::workspace.
Referenced by meta_core_user_lower_and_unfocus(), meta_display_get_tab_current(), meta_stack_list_windows(), meta_stack_lower(), meta_stack_raise(), meta_window_notify_focus(), meta_window_should_be_showing(), and meta_workspace_list_windows().
meta_window_lower()
void meta_window_lower (MetaWindow * window)
Definition at line 4788 of file window.c.
References _MetaWindow::desc, META_DEBUG_WINDOW_OPS, meta_stack_lower(), _MetaWindow::screen, and _MetaScreen::stack.
Referenced by meta_core_user_lower_and_unfocus(), and meta_window_configure_request().
meta_window_make_above()
void meta_window_make_above (MetaWindow * window)
Definition at line 2944 of file window.c.
References meta_window_frame_size_changed(), meta_window_raise(), meta_window_update_layer(), TRUE, and _MetaWindow::wm_state_above.
Referenced by meta_core_make_above().
meta_window_make_fullscreen()
void meta_window_make_fullscreen (MetaWindow * window)
Definition at line 3002 of file window.c.
References _MetaWindow::fullscreen, META_QUEUE_MOVE_RESIZE, meta_window_make_fullscreen_internal(), and meta_window_queue().
Referenced by meta_window_client_message().
meta_window_make_fullscreen_internal()
void meta_window_make_fullscreen_internal (MetaWindow * window)
Definition at line 2966 of file window.c.
References _MetaWindow::desc, _MetaWindow::display, FALSE, _MetaWindow::force_save_user_rect, _MetaWindow::fullscreen, META_DEBUG_WINDOW_OPS, meta_display_get_current_time_roundtrip(), meta_stack_freeze(), meta_stack_thaw(), meta_window_raise(), meta_window_unshade(), meta_window_update_layer(), _MetaWindow::screen, _MetaWindow::shaded, _MetaScreen::stack, _MetaWindow::tile_resized, and TRUE.
Referenced by meta_window_make_fullscreen(), and meta_window_move_resize_request().
meta_window_maximize()
void meta_window_maximize (MetaWindow * window, MetaMaximizeFlags directions)
Definition at line 2612 of file window.c.
References _MetaDisplay::compositor, _MetaWindow::display, FALSE, _MetaWindow::maximize_horizontally_after_placement, _MetaWindow::maximize_vertically_after_placement, _MetaWindow::maximized_horizontally, _MetaWindow::maximized_vertically, meta_compositor_maximize_window(), meta_display_get_current_time_roundtrip(), META_MAXIMIZE_HORIZONTAL, META_MAXIMIZE_VERTICAL, META_QUEUE_MOVE_RESIZE, META_TILE_NONE, meta_window_maximize_internal(), meta_window_queue(), meta_window_unshade(), NULL, _MetaWindow::placed, _MetaWindow::saved_rect, _MetaWindow::shaded, and _MetaWindow::tile_mode.
Referenced by meta_core_maximize(), meta_core_toggle_maximize(), meta_core_toggle_maximize_horizontally(), meta_core_toggle_maximize_vertically(), meta_window_client_message(), and meta_window_handle_mouse_grab_op_event().
meta_window_maximize_internal()
void meta_window_maximize_internal (MetaWindow * window, MetaMaximizeFlags directions, MetaRectangle * saved_rect)
Definition at line 2566 of file window.c.
References _MetaWindow::desc, _MetaWindow::frame, _MetaWindow::maximized_horizontally, _MetaWindow::maximized_vertically, META_DEBUG_WINDOW_OPS, META_MAXIMIZE_HORIZONTAL, META_MAXIMIZE_VERTICAL, meta_window_frame_size_changed(), _MetaFrame::need_reapply_frame_shape, NULL, _MetaWindow::saved_maximize, _MetaWindow::saved_rect, and TRUE.
Referenced by meta_window_maximize(), and meta_window_tile().
meta_window_minimize()
void meta_window_minimize (MetaWindow * window)
Definition at line 2420 of file window.c.
References _MetaWindow::desc, _MetaWindow::has_focus, META_DEBUG_FOCUS, META_QUEUE_CALC_SHOWING, meta_window_foreach_transient(), meta_window_queue(), _MetaWindow::minimized, NULL, and TRUE.
Referenced by meta_core_minimize(), meta_screen_minimize_all_on_active_workspace_except(), and meta_window_client_message().
meta_window_move()
void meta_window_move (MetaWindow * window, gboolean user_op, int root_x_nw, int root_y_nw)
Definition at line 3938 of file window.c.
References _MetaRectangle::height, META_IS_MOVE_ACTION, META_IS_USER_ACTION, _MetaWindow::rect, and _MetaRectangle::width.
Referenced by meta_core_user_move(), and meta_display_end_grab_op().
meta_window_move_resize()
void meta_window_move_resize (MetaWindow * window, gboolean user_op, int root_x_nw, int root_y_nw, int w, int h)
Definition at line 3954 of file window.c.
References META_IS_MOVE_ACTION, META_IS_RESIZE_ACTION, and META_IS_USER_ACTION.
Referenced by meta_window_move_to_monitor(), meta_window_shove_titlebar_onscreen(), meta_window_unmake_fullscreen(), and meta_window_unmaximize().
meta_window_move_resize_request()
void meta_window_move_resize_request (MetaWindow * window, guint value_mask, int gravity, int x, int y, int width, int height)
Definition at line 4833 of file window.c.
References _MetaWindow::decorated, _MetaWindow::desc, _MetaWindow::display, FALSE, _MetaWindow::fullscreen, _MetaDisplay::grab_op, _MetaDisplay::grab_window, _MetaWindow::has_fullscreen_func, _MetaRectangle::height, META_DEBUG_GEOMETRY, META_GRAB_OP_MOVING, META_GRAB_OP_NONE, META_GRAB_OP_RESIZING_E, META_GRAB_OP_RESIZING_N, META_GRAB_OP_RESIZING_NE, META_GRAB_OP_RESIZING_NW, META_GRAB_OP_RESIZING_S, META_GRAB_OP_RESIZING_SE, META_GRAB_OP_RESIZING_SW, META_GRAB_OP_RESIZING_W, META_IS_CONFIGURE_REQUEST, META_IS_MOVE_ACTION, META_IS_RESIZE_ACTION, meta_prefs_get_disable_workarounds(), meta_prefs_get_force_fullscreen(), meta_rectangle_equal(), meta_screen_get_xinerama_for_rect(), META_WINDOW_DIALOG, meta_window_get_gravity_position(), meta_window_is_client_decorated(), meta_window_make_fullscreen_internal(), META_WINDOW_MODAL_DIALOG, META_WINDOW_SPLASHSCREEN, _MetaWindow::placed, _MetaXineramaScreenInfo::rect, _MetaWindow::rect, _MetaWindow::screen, _MetaWindow::size_hints, TRUE, _MetaWindow::type, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_window_client_message(), and meta_window_configure_request().
meta_window_move_to_monitor()
void meta_window_move_to_monitor (MetaWindow * window, const MetaXineramaScreenInfo * from_monitor, const MetaXineramaScreenInfo * to_monitor)
Definition at line 2884 of file window.c.
References _MetaRectangle::height, meta_window_get_client_root_coords(), meta_window_move_resize(), meta_window_tile(), META_WINDOW_TILED, _MetaXineramaScreenInfo::number, _MetaXineramaScreenInfo::rect, _MetaWindow::saved_rect, _MetaWindow::tile_monitor_number, TRUE, _MetaWindow::user_rect, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
meta_window_new()
MetaWindow * meta_window_new (MetaDisplay * display, Window xwindow, gboolean must_be_viewable)
Definition at line 211 of file window.c.
References FALSE, meta_display_grab(), meta_display_ungrab(), meta_error_trap_pop(), meta_error_trap_pop_with_return(), meta_error_trap_push(), meta_window_new_with_attrs(), NULL, TRUE, and _MetaDisplay::xdisplay.
meta_window_new_with_attrs()
MetaWindow * meta_window_new_with_attrs (MetaDisplay * display, Window xwindow, gboolean must_be_viewable, XWindowAttributes * attrs)
Definition at line 255 of file window.c.
References _MetaScreen::active_workspace, _MetaWindow::all_keys_grabbed, _MetaWindow::always_sticky, _MetaWindow::bamf_desktop_file, _MetaWindow::border_width, _MetaWindow::calc_placement, _MetaWindow::colormap, _MetaWindow::constructing, _MetaWindow::custom_frame_extents, _MetaWindow::decorated, _MetaWindow::denied_focus_and_not_transient, _MetaWindow::depth, _MetaWindow::desc, _MetaWindow::dialog_pid, _MetaWindow::disable_sync, _MetaWindow::display, _MetaDisplay::display_opening, FALSE, _MetaWindow::force_save_user_rect, _MetaWindow::frame, _MetaWindow::frame_bounds, _MetaWindow::fullscreen, _MetaWindow::fullscreen_after_placement, _MetaWindow::fullscreen_monitors, _MetaWindow::grab_on_frame, _MetaWindow::group, _MetaWindow::gtk_application_id, _MetaWindow::gtk_theme_variant, _MetaWindow::has_close_func, _MetaWindow::has_custom_frame_extents, _MetaWindow::has_focus, _MetaWindow::has_fullscreen_func, _MetaWindow::has_maximize_func, _MetaWindow::has_minimize_func, _MetaWindow::has_move_func, _MetaWindow::has_resize_func, _MetaWindow::has_shade_func, _MetaWindow::has_shape, _MetaWindow::have_focus_click_grab, _MetaRectangle::height, _MetaWindow::icon, _MetaWindow::icon_cache, _MetaWindow::icon_name, _MetaWindow::iconic, _MetaWindow::initial_timestamp, _MetaWindow::initial_timestamp_set, _MetaWindow::initial_workspace, _MetaWindow::initial_workspace_set, _MetaWindow::initially_iconic, _MetaWindow::input, _MetaWindow::is_in_queues, _MetaWindow::keys_grabbed, _MetaWindow::layer, _MetaWindow::mapped, _MetaWindow::maximize_horizontally_after_placement, _MetaWindow::maximize_vertically_after_placement, _MetaWindow::maximized_horizontally, _MetaWindow::maximized_vertically, META_DEBUG_PLACEMENT, META_DEBUG_SHAPES, meta_display_get_current_time_roundtrip(), meta_display_grab(), meta_display_grab_focus_window_button(), meta_display_grab_window_buttons(), META_DISPLAY_HAS_SHAPE, meta_display_lookup_x_window(), meta_display_register_x_window(), meta_display_ungrab(), meta_display_xwindow_is_a_no_focus_window(), meta_error_trap_pop(), meta_error_trap_pop_with_return(), meta_error_trap_push(), meta_icon_cache_init(), META_IS_CONFIGURE_REQUEST, META_IS_MOVE_ACTION, META_IS_RESIZE_ACTION, META_LAYER_LAST, meta_prop_get_cardinal_with_atom_type(), META_QUEUE_CALC_SHOWING, meta_screen_apply_startup_properties(), meta_screen_get_workspace_by_index(), meta_set_normal_hints(), meta_stack_add(), meta_stack_freeze(), meta_stack_thaw(), META_TILE_NONE, META_TYPE_WINDOW, meta_window_compute_group(), META_WINDOW_DESKTOP, META_WINDOW_DOCK, meta_window_ensure_frame(), meta_window_foreach_transient(), meta_window_grab_keys(), meta_window_lookup_saved_state(), META_WINDOW_NORMAL, meta_window_queue(), meta_window_release_saved_state(), meta_window_reload_properties(), meta_window_set_current_workspace_hint(), meta_window_set_user_time(), meta_window_update_icon_now(), meta_window_update_net_wm_type(), meta_window_update_role(), meta_window_update_struts(), meta_workspace_add_window(), _MetaWindow::mini_icon, _MetaWindow::minimize_after_placement, _MetaWindow::minimized, _MetaWindow::move_after_placement, _MetaWindow::mwm_border_only, _MetaWindow::mwm_decorated, _MetaWindow::mwm_has_close_func, _MetaWindow::mwm_has_maximize_func, _MetaWindow::mwm_has_minimize_func, _MetaWindow::mwm_has_move_func, _MetaWindow::mwm_has_resize_func, N_INITIAL_PROPS, _MetaWindow::need_reread_icon, _MetaWindow::net_wm_pid, _MetaWindow::net_wm_user_time, _MetaWindow::net_wm_user_time_set, NULL, _MetaWindow::on_all_workspaces, _MetaWindow::placed, _MetaWindow::rect, _MetaWindow::require_fully_onscreen, _MetaWindow::require_on_single_xinerama, _MetaWindow::require_titlebar_visible, _MetaWindow::res_class, _MetaWindow::res_name, _MetaWindow::role, _MetaWindow::saved_rect, _MetaWindow::screen, _MetaDisplay::screens, _MetaWindow::shaded, _MetaWindow::shaken_loose, _MetaWindow::showing_for_first_time, _MetaWindow::size_hints, _MetaWindow::skip_pager, _MetaWindow::skip_taskbar, _MetaWindow::sm_client_id, _MetaScreen::stack, _MetaWindow::stack_position, _MetaWindow::startup_id, _MetaWindow::struts, _MetaWindow::tab_unminimized, _MetaWindow::take_focus, _MetaWindow::tile_mode, _MetaWindow::tile_monitor_number, _MetaWindow::tile_resized, _MetaWindow::title, _MetaWindow::transient_parent_is_root_window, TRUE, _MetaWindow::type, _MetaWindow::type_atom, _MetaWindow::unmanaging, _MetaWindow::unmaps_pending, _MetaWindow::user_rect, _MetaWindow::user_time_window, _MetaWindow::using_net_wm_icon_name, _MetaWindow::using_net_wm_name, _MetaWindow::using_net_wm_visible_icon_name, _MetaWindow::using_net_wm_visible_name, _MetaWindow::was_minimized, _MetaRectangle::width, _MetaWindow::withdrawn, _MetaWindow::wm_client_machine, _MetaWindow::wm_hints_mask, _MetaWindow::wm_hints_pixmap, _MetaWindow::wm_state_above, _MetaWindow::wm_state_below, _MetaWindow::wm_state_demands_attention, _MetaWindow::wm_state_modal, _MetaWindow::wm_state_skip_pager, _MetaWindow::wm_state_skip_taskbar, _MetaWindow::workspace, _MetaRectangle::x, _MetaWindow::xclient_leader, _MetaDisplay::xdisplay, _MetaWindow::xgroup_leader, _MetaScreen::xroot, _MetaWindow::xtransient_for, _MetaWindow::xvisual, _MetaWindow::xwindow, and _MetaRectangle::y.
Referenced by meta_screen_manage_all_windows(), and meta_window_new().
meta_window_notify_focus()
gboolean meta_window_notify_focus (MetaWindow * window, XEvent * event)
Definition at line 5647 of file window.c.
References _MetaScreen::active_workspace, _MetaWindow::colormap, _MetaDisplay::compositor, _MetaWindow::desc, _MetaWindow::display, FALSE, _MetaDisplay::focus_window, _MetaWindow::frame, _MetaWindow::has_focus, meta_compositor_set_active_window(), META_DEBUG_FOCUS, meta_display_grab_focus_window_button(), meta_display_ungrab_focus_window_button(), meta_display_update_active_window_hint(), meta_error_trap_pop(), meta_error_trap_push(), meta_event_detail_to_string(), meta_event_mode_to_string(), META_FOCUS_MODE_CLICK, meta_prefs_get_focus_mode(), meta_prefs_get_raise_on_click(), meta_window_located_on_workspace(), meta_window_update_layer(), _MetaWorkspace::mru_list, NULL, _MetaWindow::screen, TRUE, _MetaFrame::window, _MetaDisplay::xdisplay, _MetaFrame::xwindow, and _MetaWindow::xwindow.
meta_window_property_notify()
gboolean meta_window_property_notify (MetaWindow * window, XEvent * event)
Definition at line 5111 of file window.c.
meta_window_queue()
void meta_window_queue (MetaWindow * window, guint queuebits)
Definition at line 1766 of file window.c.
References _MetaWindow::desc, _MetaWindow::is_in_queues, META_DEBUG_WINDOW_STATE, META_PRIORITY_RESIZE, NULL, NUMBER_OF_QUEUES, and _MetaWindow::unmanaging.
Referenced by meta_core_queue_frame_resize(), meta_display_queue_retheme_all_windows(), meta_window_client_message(), meta_window_destroy_frame(), meta_window_make_fullscreen(), meta_window_maximize(), meta_window_minimize(), meta_window_new_with_attrs(), meta_window_shade(), meta_window_tile(), meta_window_unminimize(), meta_window_unshade(), meta_window_update_fullscreen_monitors(), meta_workspace_add_window(), meta_workspace_invalidate_work_area(), meta_workspace_queue_calc_showing(), and meta_workspace_remove_window().
meta_window_raise()
void meta_window_raise (MetaWindow * window)
Definition at line 4748 of file window.c.
References _MetaWindow::desc, META_DEBUG_WINDOW_OPS, meta_stack_raise(), meta_warning(), meta_window_find_root_ancestor(), _MetaWindow::screen, and _MetaScreen::stack.
Referenced by meta_core_maximize(), meta_core_show_window_menu(), meta_core_toggle_maximize(), meta_core_toggle_maximize_horizontally(), meta_core_toggle_maximize_vertically(), meta_core_unmaximize(), meta_core_user_raise(), meta_display_begin_grab_op(), meta_display_end_grab_op(), meta_window_client_message(), meta_window_configure_request(), meta_window_make_above(), meta_window_make_fullscreen_internal(), meta_window_unmake_above(), and meta_workspace_activate_with_focus().
meta_window_recalc_features()
void meta_window_recalc_features (MetaWindow * window)
Definition at line 6709 of file window.c.
meta_window_recalc_window_type()
void meta_window_recalc_window_type (MetaWindow * window)
Definition at line 6551 of file window.c.
Referenced by meta_window_update_net_wm_type().
meta_window_refresh_resize_popup()
void meta_window_refresh_resize_popup (MetaWindow * window)
Definition at line 8358 of file window.c.
References _MetaWindow::display, _MetaDisplay::grab_op, _MetaDisplay::grab_resize_popup, _MetaDisplay::grab_window, _MetaDisplay::grab_wireframe_active, _MetaDisplay::grab_wireframe_rect, META_DEBUG_WINDOW_OPS, META_GRAB_OP_KEYBOARD_RESIZING_E, META_GRAB_OP_KEYBOARD_RESIZING_N, META_GRAB_OP_KEYBOARD_RESIZING_NE, META_GRAB_OP_KEYBOARD_RESIZING_NW, META_GRAB_OP_KEYBOARD_RESIZING_S, META_GRAB_OP_KEYBOARD_RESIZING_SE, META_GRAB_OP_KEYBOARD_RESIZING_SW, META_GRAB_OP_KEYBOARD_RESIZING_UNKNOWN, META_GRAB_OP_KEYBOARD_RESIZING_W, META_GRAB_OP_NONE, META_GRAB_OP_RESIZING_E, META_GRAB_OP_RESIZING_N, META_GRAB_OP_RESIZING_NE, META_GRAB_OP_RESIZING_NW, META_GRAB_OP_RESIZING_S, META_GRAB_OP_RESIZING_SE, META_GRAB_OP_RESIZING_SW, META_GRAB_OP_RESIZING_W, meta_ui_resize_popup_new(), meta_ui_resize_popup_set(), meta_ui_resize_popup_set_showing(), meta_window_get_client_root_coords(), NULL, _MetaScreen::number, _MetaWindow::screen, _MetaWindow::size_hints, TRUE, and _MetaDisplay::xdisplay.
Referenced by meta_display_begin_grab_op().
meta_window_resize()
void meta_window_resize (MetaWindow * window, gboolean user_op, int w, int h)
Definition at line 3920 of file window.c.
References META_IS_RESIZE_ACTION, META_IS_USER_ACTION, and meta_window_get_position().
meta_window_resize_with_gravity()
void meta_window_resize_with_gravity (MetaWindow * window, gboolean user_op, int w, int h, int gravity)
Definition at line 3972 of file window.c.
References META_IS_RESIZE_ACTION, META_IS_USER_ACTION, and meta_window_get_position().
Referenced by meta_core_user_resize(), and meta_display_end_grab_op().
meta_window_same_application()
gboolean meta_window_same_application (MetaWindow * window, MetaWindow * other_window)
Definition at line 8328 of file window.c.
References meta_window_get_group(), and NULL.
Referenced by meta_window_configure_request().
meta_window_send_icccm_message()
void meta_window_send_icccm_message (MetaWindow * window, Atom atom, guint32 timestamp)
Definition at line 4797 of file window.c.
References _MetaWindow::display, FALSE, meta_error_trap_pop(), meta_error_trap_push(), _MetaDisplay::xdisplay, and _MetaWindow::xwindow.
Referenced by meta_display_ping_window(), meta_window_delete(), and meta_window_focus().
meta_window_set_current_workspace_hint()
void meta_window_set_current_workspace_hint (MetaWindow * window)
Definition at line 4697 of file window.c.
References data, _MetaWindow::desc, _MetaWindow::display, FALSE, meta_error_trap_pop(), meta_error_trap_push(), meta_window_get_net_wm_desktop(), NULL, _MetaWindow::workspace, _MetaDisplay::xdisplay, and _MetaWindow::xwindow.
Referenced by meta_window_new_with_attrs(), meta_workspace_add_window(), and meta_workspace_remove_window().
meta_window_set_demands_attention()
void meta_window_set_demands_attention (MetaWindow * window)
Definition at line 8846 of file window.c.
References _MetaScreen::active_workspace, _MetaWindow::desc, FALSE, META_DEBUG_WINDOW_OPS, meta_rectangle_overlap(), meta_window_get_outer_rect(), _MetaWindow::minimized, NULL, _MetaWindow::on_all_workspaces, _MetaWindow::screen, _MetaStack::sorted, _MetaScreen::stack, TRUE, _MetaWindow::wm_state_demands_attention, and _MetaWindow::workspace.
Referenced by meta_window_client_message(), and meta_window_configure_request().
meta_window_set_gravity()
void meta_window_set_gravity (MetaWindow * window, int gravity)
Definition at line 8148 of file window.c.
References _MetaWindow::desc, _MetaWindow::display, FALSE, meta_error_trap_pop(), meta_error_trap_push(), _MetaDisplay::xdisplay, and _MetaWindow::xwindow.
meta_window_set_user_time()
void meta_window_set_user_time (MetaWindow * window, guint32 timestamp)
Definition at line 8805 of file window.c.
References __window_is_terminal(), _MetaDisplay::allow_terminal_deactivation, _MetaWindow::desc, _MetaWindow::display, FALSE, _MetaDisplay::last_user_time, META_DEBUG_STARTUP, META_FOCUS_NEW_WINDOWS_STRICT, meta_prefs_get_focus_new_windows(), _MetaWindow::net_wm_user_time, _MetaWindow::net_wm_user_time_set, TRUE, and XSERVER_TIME_IS_BEFORE.
Referenced by meta_window_new_with_attrs().
meta_window_shade()
void meta_window_shade (MetaWindow * window, guint32 timestamp)
Definition at line 3084 of file window.c.
References _MetaWindow::desc, META_DEBUG_FOCUS, META_DEBUG_WINDOW_OPS, META_QUEUE_CALC_SHOWING, META_QUEUE_MOVE_RESIZE, meta_window_focus(), meta_window_frame_size_changed(), meta_window_queue(), _MetaWindow::shaded, and TRUE.
Referenced by meta_core_shade(), and meta_window_client_message().
meta_window_should_be_showing()
gboolean meta_window_should_be_showing (MetaWindow * window)
Definition at line 1439 of file window.c.
References _MetaScreen::active_workspace, _MetaWindow::desc, meta_window_located_on_workspace(), meta_window_showing_on_its_workspace(), meta_workspace_index(), _MetaWindow::on_all_workspaces, and _MetaWindow::screen.
Referenced by meta_window_calc_showing().
meta_window_shove_titlebar_onscreen()
void meta_window_shove_titlebar_onscreen (MetaWindow * window)
Definition at line 7201 of file window.c.
References _MetaScreen::active_workspace, _MetaFrame::child_x, _MetaFrame::child_y, FALSE, FIXED_DIRECTION_X, _MetaWindow::frame, _MetaRectangle::height, meta_rectangle_expand_region(), meta_rectangle_shove_into_region(), meta_window_get_outer_rect(), meta_window_move_resize(), _MetaWindow::rect, _MetaWindow::screen, _MetaWorkspace::screen_region, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
meta_window_show_menu()
void meta_window_show_menu (MetaWindow * window, int root_x, int root_y, int button, guint32 timestamp)
Definition at line 7072 of file window.c.
References _MetaScreen::active_workspace, _MetaWindow::always_sticky, MetaWorkspaceLayout::cols, MetaWorkspaceLayout::current_col, MetaWorkspaceLayout::current_row, _MetaWindow::desc, _MetaWindow::display, _MetaWindow::has_maximize_func, _MetaWindow::has_minimize_func, _MetaWindow::has_shade_func, META_MENU_OP_ABOVE, META_MENU_OP_DELETE, META_MENU_OP_MAXIMIZE, META_MENU_OP_MINIMIZE, META_MENU_OP_MOVE, META_MENU_OP_MOVE_DOWN, META_MENU_OP_MOVE_LEFT, META_MENU_OP_MOVE_RIGHT, META_MENU_OP_MOVE_UP, META_MENU_OP_NONE, META_MENU_OP_RECOVER, META_MENU_OP_RESIZE, META_MENU_OP_SHADE, META_MENU_OP_STICK, META_MENU_OP_UNABOVE, META_MENU_OP_UNMAXIMIZE, META_MENU_OP_UNSHADE, META_MENU_OP_UNSTICK, META_MENU_OP_WORKSPACES, meta_screen_calc_workspace_layout(), meta_screen_free_workspace_layout(), meta_screen_get_n_workspaces(), META_UI_DIRECTION_LTR, meta_ui_get_direction(), meta_ui_window_menu_free(), meta_ui_window_menu_new(), meta_ui_window_menu_popup(), META_WINDOW_ALLOWS_MOVE, META_WINDOW_ALLOWS_RESIZE, META_WINDOW_DESKTOP, META_WINDOW_DOCK, meta_window_get_net_wm_desktop(), META_WINDOW_MAXIMIZED, META_WINDOW_SPLASHSCREEN, meta_window_titlebar_is_onscreen(), meta_workspace_index(), NULL, _MetaWindow::on_all_workspaces, MetaWorkspaceLayout::rows, _MetaWindow::screen, _MetaWindow::shaded, _MetaWindow::type, _MetaScreen::ui, _MetaDisplay::window_menu, _MetaDisplay::window_with_menu, _MetaWindow::wm_state_above, and _MetaWindow::xwindow.
Referenced by meta_core_show_window_menu(), and meta_window_client_message().
meta_window_showing_on_its_workspace()
gboolean meta_window_showing_on_its_workspace (MetaWindow * window)
Definition at line 1380 of file window.c.
References _MetaScreen::active_workspace, _MetaWindow::desc, _MetaWindow::display, FALSE, _MetaDisplay::grab_window, _MetaDisplay::grab_wireframe_active, meta_window_foreach_ancestor(), _MetaWindow::minimized, NULL, _MetaWindow::on_all_workspaces, _MetaWindow::screen, _MetaWorkspace::showing_desktop, TRUE, and _MetaWindow::workspace.
Referenced by meta_screen_ensure_tab_popup(), meta_window_place(), and meta_window_should_be_showing().
meta_window_stack_just_below()
void meta_window_stack_just_below (MetaWindow * window, MetaWindow * below_this_one)
Definition at line 8781 of file window.c.
References _MetaWindow::desc, META_DEBUG_STACK, meta_window_set_stack_position(), NULL, and _MetaWindow::stack_position.
meta_window_stick()
void meta_window_stick (MetaWindow * window)
Definition at line 4635 of file window.c.
References meta_window_foreach_transient(), and TRUE.
Referenced by meta_core_stick(), and meta_window_client_message().
meta_window_tile()
void meta_window_tile (MetaWindow * window)
Definition at line 2700 of file window.c.
References FALSE, _MetaWindow::frame_bounds, _MetaWindow::maximized_horizontally, _MetaWindow::maximized_vertically, META_MAXIMIZE_VERTICAL, META_QUEUE_MOVE_RESIZE, META_TILE_BOTTOM_LEFT, META_TILE_BOTTOM_RIGHT, META_TILE_LEFT, META_TILE_NONE, META_TILE_RIGHT, META_TILE_TOP_LEFT, META_TILE_TOP_RIGHT, meta_window_maximize_internal(), meta_window_queue(), NULL, _MetaWindow::saved_rect, _MetaWindow::tile_mode, _MetaWindow::tiled, and TRUE.
Referenced by meta_window_handle_mouse_grab_op_event(), and meta_window_move_to_monitor().
meta_window_titlebar_is_onscreen()
gboolean meta_window_titlebar_is_onscreen (MetaWindow * window)
Definition at line 7247 of file window.c.
References _MetaScreen::active_workspace, _MetaFrame::child_y, FALSE, _MetaWindow::frame, _MetaRectangle::height, meta_rectangle_intersect(), meta_window_get_outer_rect(), MIN, _MetaWindow::screen, _MetaWorkspace::screen_region, TRUE, and _MetaRectangle::width.
Referenced by meta_core_get(), and meta_window_show_menu().
meta_window_unmake_above()
void meta_window_unmake_above (MetaWindow * window)
Definition at line 2955 of file window.c.
References FALSE, meta_window_frame_size_changed(), meta_window_raise(), meta_window_update_layer(), and _MetaWindow::wm_state_above.
Referenced by meta_core_unmake_above().
meta_window_unmake_fullscreen()
void meta_window_unmake_fullscreen (MetaWindow * window)
Definition at line 3014 of file window.c.
References _MetaWindow::desc, FALSE, _MetaWindow::fullscreen, _MetaRectangle::height, META_DEBUG_WINDOW_OPS, meta_window_get_current_tile_area(), meta_window_move_resize(), META_WINDOW_TILED, meta_window_update_layer(), _MetaWindow::saved_rect, _MetaWindow::size_hints, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_window_client_message().
meta_window_unmaximize()
void meta_window_unmaximize (MetaWindow * window, MetaMaximizeFlags directions)
Definition at line 2788 of file window.c.
References _MetaDisplay::compositor, _MetaWindow::desc, _MetaWindow::display, FALSE, _MetaDisplay::grab_anchor_window_pos, _MetaDisplay::grab_op, _MetaDisplay::grab_window, _MetaDisplay::grab_wireframe_active, _MetaDisplay::grab_wireframe_rect, _MetaRectangle::height, _MetaWindow::maximized_horizontally, _MetaWindow::maximized_vertically, meta_compositor_unmaximize_window(), META_DEBUG_WINDOW_OPS, meta_grab_op_is_moving(), META_MAXIMIZE_HORIZONTAL, META_MAXIMIZE_VERTICAL, META_TILE_NONE, meta_window_frame_size_changed(), meta_window_get_client_root_coords(), meta_window_move_resize(), _MetaWindow::saved_maximize, _MetaWindow::saved_rect, _MetaWindow::size_hints, _MetaWindow::tile_mode, _MetaWindow::tiled, _MetaWindow::user_rect, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_core_toggle_maximize(), meta_core_toggle_maximize_horizontally(), meta_core_toggle_maximize_vertically(), meta_core_unmaximize(), meta_window_client_message(), and meta_window_untile().
meta_window_unminimize()
void meta_window_unminimize (MetaWindow * window)
Definition at line 2449 of file window.c.
References FALSE, META_QUEUE_CALC_SHOWING, meta_window_foreach_transient(), meta_window_queue(), _MetaWindow::minimized, NULL, TRUE, and _MetaWindow::was_minimized.
meta_window_unset_demands_attention()
void meta_window_unset_demands_attention (MetaWindow * window)
Definition at line 8910 of file window.c.
References _MetaWindow::desc, FALSE, META_DEBUG_WINDOW_OPS, and _MetaWindow::wm_state_demands_attention.
Referenced by meta_window_client_message(), and meta_window_focus().
meta_window_unshade()
void meta_window_unshade (MetaWindow * window, guint32 timestamp)
Definition at line 3111 of file window.c.
References _MetaWindow::desc, FALSE, META_DEBUG_FOCUS, META_DEBUG_WINDOW_OPS, META_QUEUE_CALC_SHOWING, META_QUEUE_MOVE_RESIZE, meta_window_focus(), meta_window_frame_size_changed(), meta_window_queue(), and _MetaWindow::shaded.
Referenced by meta_core_unshade(), meta_window_client_message(), meta_window_make_fullscreen_internal(), and meta_window_maximize().
meta_window_unstick()
void meta_window_unstick (MetaWindow * window)
Definition at line 4645 of file window.c.
References FALSE, and meta_window_foreach_transient().
Referenced by meta_core_unstick(), and meta_window_client_message().
meta_window_untile()
void meta_window_untile (MetaWindow * window)
Definition at line 2745 of file window.c.
References FALSE, META_MAXIMIZE_HORIZONTAL, META_MAXIMIZE_VERTICAL, meta_window_unmaximize(), and _MetaWindow::tiled.
meta_window_update_fullscreen_monitors()
void meta_window_update_fullscreen_monitors (MetaWindow * window, unsigned long top, unsigned long bottom, unsigned long left, unsigned long right)
Definition at line 3056 of file window.c.
References _MetaWindow::fullscreen, _MetaWindow::fullscreen_monitors, META_QUEUE_MOVE_RESIZE, and meta_window_queue().
Referenced by meta_window_client_message().
meta_window_update_icon_now()
void meta_window_update_icon_now (MetaWindow * window)
Definition at line 6176 of file window.c.
References _MetaWindow::icon, _MetaWindow::icon_cache, META_MINI_ICON_HEIGHT, META_MINI_ICON_WIDTH, meta_prefs_get_icon_size(), meta_read_icons(), _MetaWindow::mini_icon, NULL, _MetaWindow::screen, _MetaWindow::wm_hints_mask, _MetaWindow::wm_hints_pixmap, and _MetaWindow::xwindow.
Referenced by meta_invalidate_all_icons(), meta_invalidate_default_icons(), and meta_window_new_with_attrs().
meta_window_update_keyboard_move()
void meta_window_update_keyboard_move (MetaWindow * window)
Definition at line 8714 of file window.c.
References _MetaWindow::display, and _MetaDisplay::grab_op.
meta_window_update_keyboard_resize()
void meta_window_update_keyboard_resize (MetaWindow * window, gboolean update_cursor)
Definition at line 8690 of file window.c.
References _MetaWindow::display, _MetaDisplay::grab_op, _MetaDisplay::grab_xwindow, meta_display_set_grab_op_cursor(), NULL, and TRUE.
meta_window_update_layer()
void meta_window_update_layer (MetaWindow * window)
Definition at line 8724 of file window.c.
References meta_group_update_layers(), meta_stack_freeze(), meta_stack_thaw(), meta_stack_update_layer(), meta_window_get_group(), _MetaWindow::screen, and _MetaScreen::stack.
Referenced by meta_window_client_message(), meta_window_make_above(), meta_window_make_fullscreen_internal(), meta_window_notify_focus(), meta_window_unmake_above(), and meta_window_unmake_fullscreen().
meta_window_update_net_wm_type()
void meta_window_update_net_wm_type (MetaWindow * window)
Definition at line 6078 of file window.c.
References _MetaWindow::desc, _MetaWindow::display, meta_error_trap_pop(), meta_error_trap_push(), meta_is_verbose(), meta_prop_get_atom_list(), meta_window_recalc_window_type(), meta_XFree, NULL, TRUE, _MetaWindow::type_atom, _MetaDisplay::xdisplay, and _MetaWindow::xwindow.
Referenced by meta_window_new_with_attrs().
meta_window_update_role()
void meta_window_update_role (MetaWindow * window)
Definition at line 6057 of file window.c.
References _MetaWindow::desc, _MetaWindow::display, meta_prop_get_latin1_string(), meta_XFree, NULL, _MetaWindow::role, and _MetaWindow::xwindow.
Referenced by meta_window_new_with_attrs().
meta_window_update_struts()
void meta_window_update_struts (MetaWindow * window)
Definition at line 6291 of file window.c.
References BOX_BOTTOM, BOX_RIGHT, _MetaWindow::desc, _MetaWindow::display, _MetaStrut::edge, FALSE, _MetaRectangle::height, META_DEBUG_WORKAREA, META_EDGE_SCREEN, META_EDGE_XINERAMA, meta_prop_get_cardinal_list(), meta_rectangle_contains_rect(), meta_rectangle_equal(), META_SIDE_BOTTOM, META_SIDE_LEFT, META_SIDE_RIGHT, META_SIDE_TOP, meta_XFree, _MetaScreen::n_xinerama_infos, NULL, _MetaXineramaScreenInfo::rect, _MetaScreen::rect, _MetaStrut::rect, _MetaWindow::screen, _MetaStrut::side, _MetaWindow::struts, TRUE, _MetaRectangle::width, _MetaRectangle::x, _MetaScreen::xinerama_infos, _MetaWindow::xwindow, and _MetaRectangle::y.
Referenced by meta_window_new_with_attrs().
meta_window_update_unfocused_button_grabs()
void meta_window_update_unfocused_button_grabs (MetaWindow * window)
meta_window_update_wireframe()
void meta_window_update_wireframe (MetaWindow * window, int x, int y, int width, int height)
Definition at line 4312 of file window.c.
References _MetaWindow::display, _MetaDisplay::grab_wireframe_last_display_height, _MetaDisplay::grab_wireframe_last_display_width, _MetaDisplay::grab_wireframe_last_xor_rect, _MetaDisplay::grab_wireframe_rect, _MetaRectangle::height, meta_effects_update_wireframe(), meta_window_get_xor_rect(), _MetaWindow::screen, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.