MATE Desktop Environment: window-list.c File Reference
window-list.c File Reference
#include <config.h>
#include <string.h>
#include <mate-panel-applet.h>
#include <mate-panel-applet-gsettings.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <gdk/gdkwayland.h>
#include <libmate-desktop/mate-desktop-utils.h>
#include "wncklet.h"
#include "window-list.h"
Macros
#define GDK_IS_X11_DISPLAY(object) !(G_TYPE_CHECK_INSTANCE_TYPE ((object), GDK_TYPE_WAYLAND_DISPLAY))
#define MATE_DESKTOP_USE_UNSTABLE_API
#define WINDOW_LIST_ICON "mate-panel-window-list"
#define WINDOW_LIST_SCHEMA "org.mate.panel.applet.window-list"
#define WINDOW_LIST_PREVIEW_SCHEMA "org.mate.panel.applet.window-list-previews"
#define WID(s) GTK_WIDGET(gtk_builder_get_object(builder, s))
Enumerations
enum TasklistGroupingType { TASKLIST_NEVER_GROUP , TASKLIST_AUTO_GROUP , TASKLIST_ALWAYS_GROUP }
Functions
gboolean window_list_applet_fill (MatePanelApplet *applet)
Macro Definition Documentation
GDK_IS_X11_DISPLAY
#define GDK_IS_X11_DISPLAY (object) !(G_TYPE_CHECK_INSTANCE_TYPE ((object), GDK_TYPE_WAYLAND_DISPLAY))
Definition at line 30 of file window-list.c.
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 38 of file window-list.c.
WID
#define WID (s) GTK_WIDGET(gtk_builder_get_object(builder, s))
Definition at line 1012 of file window-list.c.
WINDOW_LIST_ICON
#define WINDOW_LIST_ICON "mate-panel-window-list"
Definition at line 44 of file window-list.c.
WINDOW_LIST_PREVIEW_SCHEMA
#define WINDOW_LIST_PREVIEW_SCHEMA "org.mate.panel.applet.window-list-previews"
Definition at line 47 of file window-list.c.
WINDOW_LIST_SCHEMA
#define WINDOW_LIST_SCHEMA "org.mate.panel.applet.window-list"
Definition at line 45 of file window-list.c.
Enumeration Type Documentation
TasklistGroupingType
enum TasklistGroupingType
Enumerator
TASKLIST_NEVER_GROUP
TASKLIST_AUTO_GROUP
TASKLIST_ALWAYS_GROUP
Definition at line 49 of file window-list.c.
Function Documentation
window_list_applet_fill()
gboolean window_list_applet_fill (MatePanelApplet * applet)
Definition at line 772 of file window-list.c.
References action, FALSE, GDK_IS_X11_DISPLAY, MATE_PANEL_APPLET_EXPAND_MAJOR, MATE_PANEL_APPLET_EXPAND_MINOR, mate_panel_applet_get_locked_down(), mate_panel_applet_get_orient(), mate_panel_applet_get_size(), MATE_PANEL_APPLET_HAS_HANDLE, mate_panel_applet_set_flags(), mate_panel_applet_setup_menu_from_resource(), NULL, TRUE, wayland_tasklist_new(), and WNCKLET_RESOURCE_PATH.