MATE Desktop Environment: window.h File Reference
window.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <cairo.h>
#include <X11/Xlib.h>
#include "boxes.h"
#include "types.h"
Macros
#define META_TYPE_WINDOW meta_window_get_type ()
Functions
G_DECLARE_FINAL_TYPE (...) MetaFrame *meta_window_get_frame(MetaWindow *window)
gboolean meta_window_has_focus (MetaWindow *window)
gboolean meta_window_is_shaded (MetaWindow *window)
MetaRectangle * meta_window_get_rect (MetaWindow *window)
MetaScreen * meta_window_get_screen (MetaWindow *window)
MetaDisplay * meta_window_get_display (MetaWindow *window)
Window meta_window_get_xwindow (MetaWindow *window)
MetaWindow * meta_window_get_transient_for (MetaWindow *window)
gboolean meta_window_is_maximized (MetaWindow *window)
cairo_region_t * meta_window_get_frame_bounds (MetaWindow *window)
gboolean meta_window_is_tiled_left (MetaWindow *window)
gboolean meta_window_is_tiled_right (MetaWindow *window)
Macro Definition Documentation
META_TYPE_WINDOW
#define META_TYPE_WINDOW meta_window_get_type ()
Definition at line 35 of file window.h.
Function Documentation
G_DECLARE_FINAL_TYPE()
G_DECLARE_FINAL_TYPE (...)
Definition at line 27 of file ev-archive.h.
meta_window_get_display()
MetaDisplay * meta_window_get_display (MetaWindow * window)
Definition at line 8980 of file window.c.
References _MetaWindow::display.
meta_window_get_frame_bounds()
cairo_region_t * meta_window_get_frame_bounds (MetaWindow * window)
meta_window_get_frame_bounds:
Gets a region representing the outer bounds of the window's frame.
Return value: (transfer none) (allow-none): a #cairo_region_t holding the outer bounds of the window, or NULL if the window doesn't have a frame.
Definition at line 9060 of file window.c.
References _MetaWindow::frame, _MetaWindow::frame_bounds, and meta_frame_get_frame_bounds().
meta_window_get_rect()
MetaRectangle * meta_window_get_rect (MetaWindow * window)
Definition at line 8968 of file window.c.
References _MetaWindow::rect.
meta_window_get_screen()
MetaScreen * meta_window_get_screen (MetaWindow * window)
Definition at line 8974 of file window.c.
References _MetaWindow::screen.
meta_window_get_transient_for()
MetaWindow * meta_window_get_transient_for (MetaWindow * window)
meta_window_get_transient_for: @window: a MetaWindow
Returns the MetaWindow for the window that is pointed to by the WM_TRANSIENT_FOR hint on this window (see XGetTransientForHint() or XSetTransientForHint()). Marco keeps transient windows above their parents. A typical usage of this hint is for a dialog that wants to stay above its associated window.
Return value: (transfer none): the window this window is transient for, or NULL if the WM_TRANSIENT_FOR hint is unset or does not point to a toplevel window that Marco knows about.
Definition at line 9006 of file window.c.
References _MetaWindow::display, meta_display_lookup_x_window(), NULL, and _MetaWindow::xtransient_for.
Referenced by meta_core_get().
meta_window_get_xwindow()
Window meta_window_get_xwindow (MetaWindow * window)
Definition at line 8986 of file window.c.
References _MetaWindow::xwindow.
meta_window_has_focus()
gboolean meta_window_has_focus (MetaWindow * window)
Definition at line 8956 of file window.c.
References _MetaWindow::has_focus.
meta_window_is_maximized()
gboolean meta_window_is_maximized (MetaWindow * window)
Definition at line 9015 of file window.c.
References META_WINDOW_MAXIMIZED.
meta_window_is_shaded()
gboolean meta_window_is_shaded (MetaWindow * window)
Definition at line 8962 of file window.c.
References _MetaWindow::shaded.
meta_window_is_tiled_left()
gboolean meta_window_is_tiled_left (MetaWindow * window)
Definition at line 9021 of file window.c.
References META_WINDOW_TILED_LEFT.
meta_window_is_tiled_right()
gboolean meta_window_is_tiled_right (MetaWindow * window)
Definition at line 9027 of file window.c.
References META_WINDOW_TILED_RIGHT.