MATE Desktop Environment: workspace.h File Reference
workspace.h File Reference
#include "window-private.h"
Classes
struct _MetaWorkspace
Enumerations
enum MetaMotionDirection {
META_MOTION_UP = -1 , META_MOTION_DOWN = -2 , META_MOTION_LEFT = -3 , META_MOTION_RIGHT = -4 ,
META_MOTION_PREV = -5
}
Functions
MetaWorkspace * meta_workspace_new (MetaScreen *screen)
void meta_workspace_free (MetaWorkspace *workspace)
void meta_workspace_add_window (MetaWorkspace *workspace, MetaWindow *window)
void meta_workspace_remove_window (MetaWorkspace *workspace, MetaWindow *window)
void meta_workspace_relocate_windows (MetaWorkspace *workspace, MetaWorkspace *new_home)
void meta_workspace_activate_with_focus (MetaWorkspace *workspace, MetaWindow *focus_this, guint32 timestamp)
void meta_workspace_activate (MetaWorkspace *workspace, guint32 timestamp)
int meta_workspace_index (MetaWorkspace *workspace)
GList * meta_workspace_list_windows (MetaWorkspace *workspace)
void meta_workspace_invalidate_work_area (MetaWorkspace *workspace)
void meta_workspace_get_work_area_for_xinerama (MetaWorkspace *workspace, int which_xinerama, MetaRectangle *area)
void meta_workspace_get_work_area_all_xineramas (MetaWorkspace *workspace, MetaRectangle *area)
GList * meta_workspace_get_onscreen_region (MetaWorkspace *workspace)
GList * meta_workspace_get_onxinerama_region (MetaWorkspace *workspace, int which_xinerama)
void meta_workspace_focus_default_window (MetaWorkspace *workspace, MetaWindow *not_this_one, guint32 timestamp)
MetaWorkspace * meta_workspace_get_neighbor (MetaWorkspace *workspace, MetaMotionDirection direction)
const char * meta_workspace_get_name (MetaWorkspace *workspace)
Detailed Description
Workspaces
A workspace is a set of windows which all live on the same screen. (You may also see the name "desktop" around the place, which is the EWMH's name for the same thing.) Only one workspace of a screen may be active at once; all windows on all other workspaces are unmapped.
Definition in file workspace.h.
Enumeration Type Documentation
MetaMotionDirection
enum MetaMotionDirection
Enumerator
META_MOTION_UP
META_MOTION_DOWN
META_MOTION_LEFT
META_MOTION_RIGHT
META_MOTION_PREV
Definition at line 41 of file workspace.h.
Function Documentation
meta_workspace_activate()
void meta_workspace_activate (MetaWorkspace * workspace, guint32 timestamp)
Definition at line 465 of file workspace.c.
References meta_workspace_activate_with_focus(), and NULL.
Referenced by meta_screen_new().
meta_workspace_activate_with_focus()
void meta_workspace_activate_with_focus (MetaWorkspace * workspace, MetaWindow * focus_this, guint32 timestamp)
Definition at line 376 of file workspace.c.
References _MetaScreen::active_workspace, _MetaScreen::display, _MetaDisplay::grab_op, _MetaDisplay::grab_window, META_DEBUG_FOCUS, meta_display_cleanup_edges(), META_GRAB_OP_KEYBOARD_MOVING, META_GRAB_OP_MOVING, meta_screen_update_showing_desktop_hint(), meta_window_change_workspace(), meta_window_focus(), meta_window_raise(), meta_workspace_add_window(), meta_workspace_focus_default_window(), meta_workspace_index(), meta_workspace_queue_calc_showing(), meta_workspace_remove_window(), NULL, _MetaWindow::on_all_workspaces, _MetaScreen::prev_workspace, _MetaWorkspace::screen, _MetaWorkspace::showing_desktop, and _MetaWindow::workspace.
Referenced by meta_workspace_activate().
meta_workspace_add_window()
void meta_workspace_add_window (MetaWorkspace * workspace, MetaWindow * window)
Definition at line 175 of file workspace.c.
References _MetaWindow::desc, META_DEBUG_WORKAREA, META_QUEUE_CALC_SHOWING, META_QUEUE_MOVE_RESIZE, meta_screen_update_dynamic_workspaces(), meta_window_queue(), meta_window_set_current_workspace_hint(), meta_workspace_index(), meta_workspace_invalidate_work_area(), _MetaWorkspace::mru_list, NULL, _MetaWindow::on_all_workspaces, _MetaWindow::screen, _MetaWorkspace::screen, _MetaWindow::struts, _MetaWorkspace::windows, _MetaWindow::workspace, and _MetaScreen::workspaces.
Referenced by meta_window_new_with_attrs(), meta_workspace_activate_with_focus(), and meta_workspace_relocate_windows().
meta_workspace_focus_default_window()
void meta_workspace_focus_default_window (MetaWorkspace * workspace, MetaWindow * not_this_one, guint32 timestamp)
Definition at line 970 of file workspace.c.
References _MetaDisplay::autoraise_window, _MetaWindow::desc, _MetaScreen::display, META_DEBUG_FOCUS, meta_display_focus_the_no_focus_window(), meta_display_queue_autoraise_callback(), META_FOCUS_MODE_CLICK, META_FOCUS_MODE_MOUSE, META_FOCUS_MODE_SLOPPY, meta_prefs_get_auto_raise(), meta_prefs_get_focus_mode(), meta_screen_get_mouse_window(), meta_warning(), META_WINDOW_DESKTOP, META_WINDOW_DOCK, meta_window_focus(), _MetaDisplay::mouse_mode, _MetaWorkspace::screen, and _MetaWindow::type.
Referenced by meta_core_user_lower_and_unfocus(), meta_window_free(), and meta_workspace_activate_with_focus().
meta_workspace_free()
void meta_workspace_free (MetaWorkspace * workspace)
Definition at line 111 of file workspace.c.
References _MetaScreen::active_workspace, _MetaWorkspace::list_containing_self, meta_workspace_remove_window(), _MetaWorkspace::mru_list, _MetaScreen::n_xinerama_infos, NULL, _MetaWorkspace::screen, _MetaWorkspace::screen_edges, _MetaWorkspace::screen_region, _MetaWorkspace::windows, _MetaWorkspace::work_area_xinerama, _MetaWorkspace::work_areas_invalid, _MetaWindow::workspace, _MetaScreen::workspaces, _MetaWorkspace::xinerama_edges, and _MetaWorkspace::xinerama_region.
meta_workspace_get_name()
const char * meta_workspace_get_name (MetaWorkspace * workspace)
Definition at line 964 of file workspace.c.
References meta_prefs_get_workspace_name(), and meta_workspace_index().
Referenced by meta_core_get_workspace_name_with_index(), and meta_screen_ensure_workspace_popup().
meta_workspace_get_neighbor()
MetaWorkspace * meta_workspace_get_neighbor (MetaWorkspace * workspace, MetaMotionDirection direction)
Definition at line 831 of file workspace.c.
References MetaWorkspaceLayout::cols, MetaWorkspaceLayout::current_col, MetaWorkspaceLayout::current_row, MetaWorkspaceLayout::grid, meta_bug(), META_MOTION_DOWN, META_MOTION_LEFT, META_MOTION_PREV, META_MOTION_RIGHT, META_MOTION_UP, meta_prefs_get_wrap_style(), meta_screen_calc_workspace_layout(), meta_screen_free_workspace_layout(), meta_screen_get_n_workspaces(), meta_screen_get_workspace_by_index(), META_UI_DIRECTION_LTR, meta_ui_get_direction(), meta_workspace_index(), META_WRAP_CLASSIC, META_WRAP_NONE, META_WRAP_TOROIDAL, MetaWorkspaceLayout::rows, and _MetaWorkspace::screen.
meta_workspace_get_onscreen_region()
GList * meta_workspace_get_onscreen_region (MetaWorkspace * workspace)
Definition at line 792 of file workspace.c.
References _MetaWorkspace::screen_region.
meta_workspace_get_onxinerama_region()
GList * meta_workspace_get_onxinerama_region (MetaWorkspace * workspace, int which_xinerama)
Definition at line 800 of file workspace.c.
References _MetaWorkspace::xinerama_region.
meta_workspace_get_work_area_all_xineramas()
void meta_workspace_get_work_area_all_xineramas (MetaWorkspace * workspace, MetaRectangle * area)
Definition at line 783 of file workspace.c.
References _MetaWorkspace::work_area_screen.
Referenced by meta_window_get_work_area_all_xineramas().
meta_workspace_get_work_area_for_xinerama()
void meta_workspace_get_work_area_for_xinerama (MetaWorkspace * workspace, int which_xinerama, MetaRectangle * area)
Definition at line 770 of file workspace.c.
References _MetaScreen::n_xinerama_infos, and _MetaWorkspace::work_area_xinerama.
meta_workspace_index()
int meta_workspace_index (MetaWorkspace * workspace)
Definition at line 472 of file workspace.c.
References meta_bug(), _MetaWorkspace::screen, and _MetaScreen::workspaces.
Referenced by meta_core_get_active_workspace(), meta_screen_ensure_workspace_popup(), meta_window_get_net_wm_desktop(), meta_window_should_be_showing(), meta_window_show_menu(), meta_workspace_activate_with_focus(), meta_workspace_add_window(), meta_workspace_get_name(), meta_workspace_get_neighbor(), meta_workspace_invalidate_work_area(), and meta_workspace_remove_window().
meta_workspace_invalidate_work_area()
void meta_workspace_invalidate_work_area (MetaWorkspace * workspace)
Definition at line 541 of file workspace.c.
References _MetaScreen::active_workspace, _MetaScreen::display, META_DEBUG_WORKAREA, meta_display_cleanup_edges(), META_QUEUE_MOVE_RESIZE, meta_screen_queue_workarea_recalc(), meta_window_queue(), meta_workspace_index(), meta_workspace_list_windows(), _MetaScreen::n_xinerama_infos, NULL, _MetaWorkspace::screen, _MetaWorkspace::screen_edges, _MetaWorkspace::screen_region, TRUE, _MetaWorkspace::work_area_xinerama, _MetaWorkspace::work_areas_invalid, _MetaWorkspace::xinerama_edges, and _MetaWorkspace::xinerama_region.
Referenced by meta_workspace_add_window(), and meta_workspace_remove_window().
meta_workspace_list_windows()
GList * meta_workspace_list_windows (MetaWorkspace * workspace)
Definition at line 488 of file workspace.c.
References _MetaScreen::display, meta_display_list_windows(), meta_window_located_on_workspace(), NULL, and _MetaWorkspace::screen.
Referenced by meta_workspace_invalidate_work_area().
meta_workspace_new()
MetaWorkspace * meta_workspace_new (MetaScreen * screen)
Definition at line 54 of file workspace.c.
References _MetaWorkspace::all_struts, FALSE, _MetaRectangle::height, _MetaWorkspace::list_containing_self, meta_screen_foreach_window(), _MetaWorkspace::mru_list, NULL, _MetaWorkspace::screen, _MetaWorkspace::screen_edges, _MetaWorkspace::screen_region, _MetaWorkspace::showing_desktop, TRUE, _MetaRectangle::width, _MetaWorkspace::windows, _MetaWorkspace::work_area_screen, _MetaWorkspace::work_area_xinerama, _MetaWorkspace::work_areas_invalid, _MetaScreen::workspaces, _MetaRectangle::x, _MetaWorkspace::xinerama_edges, _MetaWorkspace::xinerama_region, and _MetaRectangle::y.
Referenced by meta_screen_new().
meta_workspace_relocate_windows()
void meta_workspace_relocate_windows (MetaWorkspace * workspace, MetaWorkspace * new_home)
Definition at line 276 of file workspace.c.
References meta_workspace_add_window(), meta_workspace_remove_window(), NULL, and _MetaWorkspace::windows.
meta_workspace_remove_window()
void meta_workspace_remove_window (MetaWorkspace * workspace, MetaWindow * window)
Definition at line 227 of file workspace.c.
References _MetaWindow::desc, META_DEBUG_WORKAREA, META_QUEUE_CALC_SHOWING, META_QUEUE_MOVE_RESIZE, meta_screen_update_dynamic_workspaces(), meta_window_queue(), meta_window_set_current_workspace_hint(), meta_workspace_index(), meta_workspace_invalidate_work_area(), _MetaWorkspace::mru_list, NULL, _MetaWindow::on_all_workspaces, _MetaWindow::screen, _MetaWorkspace::screen, _MetaWindow::struts, _MetaWorkspace::windows, _MetaWindow::workspace, and _MetaScreen::workspaces.
Referenced by meta_window_free(), meta_workspace_activate_with_focus(), meta_workspace_free(), and meta_workspace_relocate_windows().