MATE Desktop Environment: xprops.c File Reference
xprops.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include "xprops.h"
#include "errors.h"
#include "util.h"
#include "async-getprop.h"
#include "ui.h"
#include "marco-Xatomtype.h"
#include <X11/Xatom.h>
#include <string.h>
#include "window-private.h"
Macros
#define MAX_ITEMS sizeof (MotifWmHints)/sizeof (gulong)
#define cvtINT8toInt(val) (val)
#define cvtINT16toInt(val) (val)
#define cvtINT32toInt(val) (val)
#define cvtINT8toShort(val) (val)
#define cvtINT16toShort(val) (val)
#define cvtINT32toShort(val) (val)
#define cvtINT8toLong(val) (val)
#define cvtINT16toLong(val) (val)
#define cvtINT32toLong(val) (val)
Functions
gboolean meta_prop_get_atom_list (MetaDisplay *display, Window xwindow, Atom xatom, Atom **atoms_p, int *n_atoms_p)
gboolean meta_prop_get_cardinal_list (MetaDisplay *display, Window xwindow, Atom xatom, gulong **cardinals_p, int *n_cardinals_p)
gboolean meta_prop_get_motif_hints (MetaDisplay *display, Window xwindow, Atom xatom, MotifWmHints **hints_p)
gboolean meta_prop_get_latin1_string (MetaDisplay *display, Window xwindow, Atom xatom, char **str_p)
gboolean meta_prop_get_utf8_string (MetaDisplay *display, Window xwindow, Atom xatom, char **str_p)
gboolean meta_prop_get_utf8_list (MetaDisplay *display, Window xwindow, Atom xatom, char ***str_p, int *n_str_p)
void meta_prop_set_utf8_string_hint (MetaDisplay *display, Window xwindow, Atom atom, const char *val)
gboolean meta_prop_get_window (MetaDisplay *display, Window xwindow, Atom xatom, Window *window_p)
gboolean meta_prop_get_cardinal (MetaDisplay *display, Window xwindow, Atom xatom, gulong *cardinal_p)
gboolean meta_prop_get_cardinal_with_atom_type (MetaDisplay *display, Window xwindow, Atom xatom, Atom prop_type, gulong *cardinal_p)
gboolean meta_prop_get_text_property (MetaDisplay *display, Window xwindow, Atom xatom, char **utf8_str_p)
gboolean meta_prop_get_wm_hints (MetaDisplay *display, Window xwindow, Atom xatom, XWMHints **hints_p)
gboolean meta_prop_get_class_hint (MetaDisplay *display, Window xwindow, Atom xatom, XClassHint *class_hint)
gboolean meta_prop_get_size_hints (MetaDisplay *display, Window xwindow, Atom xatom, XSizeHints **hints_p, gulong *flags_p)
void meta_prop_get_values (MetaDisplay *display, Window xwindow, MetaPropValue *values, int n_values)
void meta_prop_free_values (MetaPropValue *values, int n_values)
Macro Definition Documentation
cvtINT16toInt
#define cvtINT16toInt (val) (val)
Definition at line 730 of file xprops.c.
cvtINT16toLong
#define cvtINT16toLong (val) (val)
Definition at line 736 of file xprops.c.
cvtINT16toShort
#define cvtINT16toShort (val) (val)
Definition at line 733 of file xprops.c.
cvtINT32toInt
#define cvtINT32toInt (val) (val)
Definition at line 731 of file xprops.c.
cvtINT32toLong
#define cvtINT32toLong (val) (val)
Definition at line 737 of file xprops.c.
cvtINT32toShort
#define cvtINT32toShort (val) (val)
Definition at line 734 of file xprops.c.
cvtINT8toInt
#define cvtINT8toInt (val) (val)
Definition at line 729 of file xprops.c.
cvtINT8toLong
#define cvtINT8toLong (val) (val)
Definition at line 735 of file xprops.c.
cvtINT8toShort
#define cvtINT8toShort (val) (val)
Definition at line 732 of file xprops.c.
MAX_ITEMS
#define MAX_ITEMS sizeof (MotifWmHints)/sizeof (gulong)
Function Documentation
meta_prop_free_values()
void meta_prop_free_values (MetaPropValue * values, int n_values)
Definition at line 1267 of file xprops.c.
Referenced by meta_group_reload_properties(), and meta_window_reload_properties_from_xwindow().
meta_prop_get_atom_list()
gboolean meta_prop_get_atom_list (MetaDisplay * display, Window xwindow, Atom xatom, Atom ** atoms_p, int * n_atoms_p)
Definition at line 238 of file xprops.c.
References FALSE, and NULL.
Referenced by meta_window_update_net_wm_type().
meta_prop_get_cardinal()
gboolean meta_prop_get_cardinal (MetaDisplay * display, Window xwindow, Atom xatom, gulong * cardinal_p)
Definition at line 604 of file xprops.c.
References meta_prop_get_cardinal_with_atom_type().
Referenced by meta_screen_new().
meta_prop_get_cardinal_list()
gboolean meta_prop_get_cardinal_list (MetaDisplay * display, Window xwindow, Atom xatom, gulong ** cardinals_p, int * n_cardinals_p)
Definition at line 282 of file xprops.c.
References FALSE, and NULL.
Referenced by meta_screen_update_workspace_layout(), meta_window_get_icon_geometry(), and meta_window_update_struts().
meta_prop_get_cardinal_with_atom_type()
gboolean meta_prop_get_cardinal_with_atom_type (MetaDisplay * display, Window xwindow, Atom xatom, Atom prop_type, gulong * cardinal_p)
Definition at line 633 of file xprops.c.
References FALSE.
Referenced by meta_prop_get_cardinal(), and meta_window_new_with_attrs().
meta_prop_get_class_hint()
gboolean meta_prop_get_class_hint (MetaDisplay * display, Window xwindow, Atom xatom, XClassHint * class_hint)
Definition at line 856 of file xprops.c.
References FALSE, and NULL.
meta_prop_get_latin1_string()
gboolean meta_prop_get_latin1_string (MetaDisplay * display, Window xwindow, Atom xatom, char ** str_p)
Definition at line 380 of file xprops.c.
References FALSE, and NULL.
Referenced by meta_window_update_role().
meta_prop_get_motif_hints()
gboolean meta_prop_get_motif_hints (MetaDisplay * display, Window xwindow, Atom xatom, MotifWmHints ** hints_p)
Definition at line 348 of file xprops.c.
References FALSE, and NULL.
meta_prop_get_size_hints()
gboolean meta_prop_get_size_hints (MetaDisplay * display, Window xwindow, Atom xatom, XSizeHints ** hints_p, gulong * flags_p)
Definition at line 931 of file xprops.c.
References FALSE, and NULL.
meta_prop_get_text_property()
gboolean meta_prop_get_text_property (MetaDisplay * display, Window xwindow, Atom xatom, char ** utf8_str_p)
Definition at line 702 of file xprops.c.
References FALSE.
meta_prop_get_utf8_list()
gboolean meta_prop_get_utf8_list (MetaDisplay * display, Window xwindow, Atom xatom, char *** str_p, int * n_str_p)
Definition at line 522 of file xprops.c.
References FALSE, and NULL.
Referenced by meta_screen_update_workspace_names().
meta_prop_get_utf8_string()
gboolean meta_prop_get_utf8_string (MetaDisplay * display, Window xwindow, Atom xatom, char ** str_p)
Definition at line 428 of file xprops.c.
References FALSE, and NULL.
meta_prop_get_values()
void meta_prop_get_values (MetaDisplay * display, Window xwindow, MetaPropValue * values, int n_values)
Definition at line 980 of file xprops.c.
References ag_get_next_completed_task(), ag_task_get_reply_and_free(), ag_task_have_reply(), ag_Xmalloc(), MetaPropValue::atom, MetaPropValue::atom_list, MetaPropValue::atoms, MetaPropValue::cardinal, MetaPropValue::cardinal_list, MetaPropValue::cardinals, MetaPropValue::class_hint, MetaPropValue::flags, MetaPropValue::hints, meta_bug(), META_DEBUG_SYNC, META_PROP_VALUE_ATOM_LIST, META_PROP_VALUE_CARDINAL, META_PROP_VALUE_CARDINAL_LIST, META_PROP_VALUE_CLASS_HINT, META_PROP_VALUE_INVALID, META_PROP_VALUE_MOTIF_HINTS, META_PROP_VALUE_SIZE_HINTS, META_PROP_VALUE_STRING, META_PROP_VALUE_STRING_AS_UTF8, META_PROP_VALUE_SYNC_COUNTER, META_PROP_VALUE_TEXT_PROPERTY, META_PROP_VALUE_UTF8, META_PROP_VALUE_UTF8_LIST, META_PROP_VALUE_WINDOW, META_PROP_VALUE_WM_HINTS, meta_XFree, MetaPropValue::motif_hints, MetaPropValue::n_atoms, MetaPropValue::n_cardinals, MetaPropValue::n_strings, NULL, MetaPropValue::required_type, MetaPropValue::size_hints, MetaPropValue::str, MetaPropValue::string_list, MetaPropValue::strings, MetaPropValue::type, type, MetaPropValue::v, MetaPropValue::wm_hints, _MetaDisplay::xdisplay, and MetaPropValue::xwindow.
Referenced by meta_group_reload_properties(), and meta_window_reload_properties_from_xwindow().
meta_prop_get_window()
gboolean meta_prop_get_window (MetaDisplay * display, Window xwindow, Atom xatom, Window * window_p)
Definition at line 587 of file xprops.c.
References FALSE.
meta_prop_get_wm_hints()
gboolean meta_prop_get_wm_hints (MetaDisplay * display, Window xwindow, Atom xatom, XWMHints ** hints_p)
Definition at line 795 of file xprops.c.
References FALSE, and NULL.
meta_prop_set_utf8_string_hint()
void meta_prop_set_utf8_string_hint (MetaDisplay * display, Window xwindow, Atom atom, const char * val)
Definition at line 541 of file xprops.c.
References FALSE, meta_error_trap_pop(), meta_error_trap_push(), and _MetaDisplay::xdisplay.
Referenced by meta_display_open().