MATE Desktop Environment: xsettings-manager.h File Reference
xsettings-manager.h File Reference
#include <X11/Xlib.h>
#include <glib.h>
#include "xsettings-common.h"
Typedefs
typedef struct _XSettingsManager XSettingsManager
typedef void(* XSettingsTerminateFunc) (void *cb_data)
Functions
Bool xsettings_manager_check_running (Display *display, int screen)
XSettingsManager * xsettings_manager_new (Display *display, int screen, XSettingsTerminateFunc terminate, void *cb_data)
void xsettings_manager_destroy (XSettingsManager *manager)
Window xsettings_manager_get_window (XSettingsManager *manager)
Bool xsettings_manager_process_event (XSettingsManager *manager, XEvent *xev)
XSettingsResult xsettings_manager_delete_setting (XSettingsManager *manager, const char *name)
XSettingsResult xsettings_manager_set_setting (XSettingsManager *manager, XSettingsSetting *setting)
XSettingsResult xsettings_manager_set_int (XSettingsManager *manager, const char *name, int value)
XSettingsResult xsettings_manager_set_string (XSettingsManager *manager, const char *name, const char *value)
XSettingsResult xsettings_manager_set_color (XSettingsManager *manager, const char *name, const XSettingsColor *value)
XSettingsResult xsettings_manager_notify (XSettingsManager *manager)
void xsettings_manager_set_overrides (XSettingsManager *manager, GVariant *overrides)
Typedef Documentation
XSettingsManager
typedef struct _XSettingsManager XSettingsManager
Definition at line 35 of file xsettings-manager.h.
XSettingsTerminateFunc
typedef void(* XSettingsTerminateFunc) (void *cb_data)
Definition at line 37 of file xsettings-manager.h.
Function Documentation
xsettings_manager_check_running()
Bool xsettings_manager_check_running (Display * display, int screen)
Definition at line 108 of file xsettings-manager.c.
xsettings_manager_delete_setting()
XSettingsResult xsettings_manager_delete_setting (XSettingsManager * manager, const char * name)
Definition at line 229 of file xsettings-manager.c.
References name, and xsettings_list_delete().
Referenced by xsettings_manager_set_overrides().
xsettings_manager_destroy()
void xsettings_manager_destroy (XSettingsManager * manager)
Definition at line 195 of file xsettings-manager.c.
References xsettings_list_free().
Referenced by mate_xsettings_manager_stop().
xsettings_manager_get_window()
Window xsettings_manager_get_window (XSettingsManager * manager)
Definition at line 208 of file xsettings-manager.c.
xsettings_manager_new()
XSettingsManager * xsettings_manager_new (Display * display, int screen, XSettingsTerminateFunc terminate, void * cb_data)
Definition at line 124 of file xsettings-manager.c.
References get_server_time(), and NULL.
xsettings_manager_notify()
XSettingsResult xsettings_manager_notify (XSettingsManager * manager)
Definition at line 390 of file xsettings-manager.c.
References _XSettingsBuffer::data, _XSettingsBuffer::len, _XSettingsList::next, _XSettingsBuffer::pos, _XSettingsList::setting, xsettings_byte_order(), XSETTINGS_NO_MEM, and XSETTINGS_SUCCESS.
Referenced by mate_xsettings_manager_start().
xsettings_manager_process_event()
Bool xsettings_manager_process_event (XSettingsManager * manager, XEvent * xev)
Definition at line 214 of file xsettings-manager.c.
xsettings_manager_set_color()
XSettingsResult xsettings_manager_set_color (XSettingsManager * manager, const char * name, const XSettingsColor * value)
Definition at line 294 of file xsettings-manager.c.
References _XSettingsSetting::data, name, _XSettingsSetting::name, _XSettingsSetting::type, _XSettingsSetting::v_color, xsettings_manager_set_setting(), and XSETTINGS_TYPE_COLOR.
xsettings_manager_set_int()
XSettingsResult xsettings_manager_set_int (XSettingsManager * manager, const char * name, int value)
Definition at line 266 of file xsettings-manager.c.
References _XSettingsSetting::data, name, _XSettingsSetting::name, _XSettingsSetting::type, _XSettingsSetting::v_int, xsettings_manager_set_setting(), and XSETTINGS_TYPE_INT.
xsettings_manager_set_overrides()
void xsettings_manager_set_overrides (XSettingsManager * manager, GVariant * overrides)
Definition at line 437 of file xsettings-manager.c.
References _XSettingsColor::alpha, _XSettingsColor::blue, _XSettingsSetting::data, _XSettingsColor::green, key, _XSettingsSetting::name, NULL, _XSettingsColor::red, _XSettingsSetting::type, _XSettingsSetting::v_color, _XSettingsSetting::v_int, _XSettingsSetting::v_string, xsettings_manager_delete_setting(), xsettings_manager_set_setting(), XSETTINGS_TYPE_COLOR, XSETTINGS_TYPE_INT, XSETTINGS_TYPE_STRING, and XSETTINGS_VARIANT_TYPE_COLOR.
Referenced by mate_xsettings_manager_start().
xsettings_manager_set_setting()
XSettingsResult xsettings_manager_set_setting (XSettingsManager * manager, XSettingsSetting * setting)
Definition at line 236 of file xsettings-manager.c.
References _XSettingsSetting::last_change_serial, _XSettingsSetting::name, xsettings_list_delete(), xsettings_list_insert(), xsettings_list_lookup(), XSETTINGS_NO_MEM, xsettings_setting_copy(), xsettings_setting_equal(), xsettings_setting_free(), and XSETTINGS_SUCCESS.
Referenced by xsettings_manager_set_color(), xsettings_manager_set_int(), xsettings_manager_set_overrides(), and xsettings_manager_set_string().
xsettings_manager_set_string()
XSettingsResult xsettings_manager_set_string (XSettingsManager * manager, const char * name, const char * value)
Definition at line 280 of file xsettings-manager.c.
References _XSettingsSetting::data, name, _XSettingsSetting::name, _XSettingsSetting::type, _XSettingsSetting::v_string, xsettings_manager_set_setting(), and XSETTINGS_TYPE_STRING.
Referenced by mate_xsettings_manager_start().