MATE Desktop Environment: xsettings-common.h File Reference
xsettings-common.h File Reference
Classes
struct _XSettingsBuffer
struct _XSettingsColor
struct _XSettingsList
struct _XSettingsSetting
Macros
#define XSETTINGS_PAD(n, m) ((n + m - 1) & (~(m-1)))
Typedefs
typedef struct _XSettingsBuffer XSettingsBuffer
typedef struct _XSettingsColor XSettingsColor
typedef struct _XSettingsList XSettingsList
typedef struct _XSettingsSetting XSettingsSetting
Enumerations
enum XSettingsType { XSETTINGS_TYPE_INT = 0 , XSETTINGS_TYPE_STRING = 1 , XSETTINGS_TYPE_COLOR = 2 }
enum XSettingsResult {
XSETTINGS_SUCCESS , XSETTINGS_NO_MEM , XSETTINGS_ACCESS , XSETTINGS_FAILED ,
XSETTINGS_NO_ENTRY , XSETTINGS_DUPLICATE_ENTRY
}
Functions
XSettingsSetting * xsettings_setting_copy (XSettingsSetting *setting)
void xsettings_setting_free (XSettingsSetting *setting)
int xsettings_setting_equal (XSettingsSetting *setting_a, XSettingsSetting *setting_b)
void xsettings_list_free (XSettingsList *list)
XSettingsList * xsettings_list_copy (XSettingsList *list)
XSettingsResult xsettings_list_insert (XSettingsList **list, XSettingsSetting *setting)
XSettingsSetting * xsettings_list_lookup (XSettingsList *list, const char *name)
XSettingsResult xsettings_list_delete (XSettingsList **list, const char *name)
char xsettings_byte_order (void)
Macro Definition Documentation
XSETTINGS_PAD
#define XSETTINGS_PAD (n, m) ((n + m - 1) & (~(m-1)))
Definition at line 105 of file xsettings-common.h.
Typedef Documentation
XSettingsBuffer
typedef struct _XSettingsBuffer XSettingsBuffer
Definition at line 31 of file xsettings-common.h.
XSettingsColor
typedef struct _XSettingsColor XSettingsColor
Definition at line 32 of file xsettings-common.h.
XSettingsList
typedef struct _XSettingsList XSettingsList
Definition at line 33 of file xsettings-common.h.
XSettingsSetting
typedef struct _XSettingsSetting XSettingsSetting
Definition at line 34 of file xsettings-common.h.
Enumeration Type Documentation
XSettingsResult
enum XSettingsResult
Enumerator
XSETTINGS_SUCCESS
XSETTINGS_NO_MEM
XSETTINGS_ACCESS
XSETTINGS_FAILED
XSETTINGS_NO_ENTRY
XSETTINGS_DUPLICATE_ENTRY
Definition at line 46 of file xsettings-common.h.
XSettingsType
enum XSettingsType
Enumerator
XSETTINGS_TYPE_INT
XSETTINGS_TYPE_STRING
XSETTINGS_TYPE_COLOR
Definition at line 39 of file xsettings-common.h.
Function Documentation
xsettings_byte_order()
char xsettings_byte_order (void)
Definition at line 261 of file xsettings-common.c.
Referenced by xsettings_manager_notify().
xsettings_list_copy()
XSettingsList * xsettings_list_copy (XSettingsList * list)
Definition at line 82 of file xsettings-common.c.
References error, _XSettingsList::next, NULL, _XSettingsList::setting, xsettings_list_free(), and xsettings_setting_copy().
xsettings_list_delete()
XSettingsResult xsettings_list_delete (XSettingsList ** list, const char * name)
Definition at line 213 of file xsettings-common.c.
References name, _XSettingsSetting::name, _XSettingsList::next, NULL, _XSettingsList::setting, XSETTINGS_FAILED, xsettings_setting_free(), and XSETTINGS_SUCCESS.
Referenced by xsettings_manager_delete_setting(), and xsettings_manager_set_setting().
xsettings_list_free()
void xsettings_list_free (XSettingsList * list)
Definition at line 159 of file xsettings-common.c.
References _XSettingsList::next, _XSettingsList::setting, and xsettings_setting_free().
Referenced by xsettings_list_copy(), and xsettings_manager_destroy().
xsettings_list_insert()
XSettingsResult xsettings_list_insert (XSettingsList ** list, XSettingsSetting * setting)
Definition at line 173 of file xsettings-common.c.
References _XSettingsSetting::name, _XSettingsList::next, NULL, _XSettingsList::setting, XSETTINGS_DUPLICATE_ENTRY, XSETTINGS_NO_MEM, and XSETTINGS_SUCCESS.
Referenced by xsettings_manager_set_setting().
xsettings_list_lookup()
XSettingsSetting * xsettings_list_lookup (XSettingsList * list, const char * name)
Definition at line 243 of file xsettings-common.c.
References name, _XSettingsSetting::name, _XSettingsList::next, NULL, and _XSettingsList::setting.
Referenced by xsettings_manager_set_setting().
xsettings_setting_copy()
XSettingsSetting * xsettings_setting_copy (XSettingsSetting * setting)
Definition at line 33 of file xsettings-common.c.
References _XSettingsSetting::data, _XSettingsSetting::last_change_serial, memcpy, _XSettingsSetting::name, NULL, _XSettingsSetting::type, _XSettingsSetting::v_color, _XSettingsSetting::v_int, _XSettingsSetting::v_string, XSETTINGS_TYPE_COLOR, XSETTINGS_TYPE_INT, and XSETTINGS_TYPE_STRING.
Referenced by xsettings_list_copy(), and xsettings_manager_set_setting().
xsettings_setting_equal()
int xsettings_setting_equal (XSettingsSetting * setting_a, XSettingsSetting * setting_b)
Definition at line 121 of file xsettings-common.c.
References _XSettingsColor::alpha, _XSettingsColor::blue, _XSettingsSetting::data, _XSettingsColor::green, _XSettingsSetting::name, _XSettingsColor::red, _XSettingsSetting::type, _XSettingsSetting::v_color, _XSettingsSetting::v_int, _XSettingsSetting::v_string, XSETTINGS_TYPE_COLOR, XSETTINGS_TYPE_INT, and XSETTINGS_TYPE_STRING.
Referenced by xsettings_manager_set_setting().
xsettings_setting_free()
void xsettings_setting_free (XSettingsSetting * setting)
Definition at line 147 of file xsettings-common.c.
References _XSettingsSetting::data, _XSettingsSetting::name, _XSettingsSetting::type, _XSettingsSetting::v_string, and XSETTINGS_TYPE_STRING.
Referenced by xsettings_list_delete(), xsettings_list_free(), and xsettings_manager_set_setting().