MATE Desktop Environment: xstuff.h File Reference
xstuff.h File Reference
#include <gdk/gdk.h>
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
#include <gtk/gtkx.h>
#include "panel-enums-gsettings.h"
Functions
gboolean is_using_x11 (void)
void xstuff_zoom_animate (GtkWidget *widget, cairo_surface_t *surface, PanelOrientation orientation, GdkRectangle *opt_src_rect)
gboolean xstuff_is_display_dead (void)
void xstuff_init (void)
Function Documentation
is_using_x11()
gboolean is_using_x11 (void)
Definition at line 50 of file xstuff.c.
References GDK_IS_X11_DISPLAY.
Referenced by _mate_panel_applet_frame_applet_broken(), panel_bindings_get_mouse_button_modifier_keymask(), and panel_session_init().
xstuff_init()
void xstuff_init (void)
Definition at line 425 of file xstuff.c.
Referenced by main().
xstuff_is_display_dead()
gboolean xstuff_is_display_dead (void)
Definition at line 402 of file xstuff.c.
Referenced by _mate_panel_applet_frame_applet_broken().
xstuff_zoom_animate()
void xstuff_zoom_animate (GtkWidget * widget, cairo_surface_t * surface, PanelOrientation orientation, GdkRectangle * opt_src_rect)
Definition at line 343 of file xstuff.c.
References dest, and MINIATURIZE_ANIMATION_STEPS_Z.