MATE Desktop Environment: actions.c File Reference
actions.c File Reference
#include <config.h>
#include <glib.h>
#include <string.h>
#include <math.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include "actions.h"
#include "dlg-add-files.h"
#include "dlg-add-folder.h"
#include "dlg-extract.h"
#include "dlg-delete.h"
#include "dlg-new.h"
#include "dlg-open-with.h"
#include "dlg-password.h"
#include "dlg-prop.h"
#include "gtk-utils.h"
#include "fr-window.h"
#include "file-utils.h"
#include "fr-process.h"
#include "glib-utils.h"
#include "fr-init.h"
#include "typedefs.h"
Macros
#define ABOUT_GROUP "About"
#define EMAILIFY(string)
Functions
void init_engramp_menu_popup (FrWindow *window, GtkBuilder *ui)
void show_new_archive_dialog (FrWindow *window, const char *archive_name)
void activate_action_new (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_open (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_save_as (GSimpleAction *action, GVariant *parameter, gpointer callback_data)
void activate_action_test_archive (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_properties (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_close (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_add_files (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_add_folder (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_extract (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_copy (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_cut (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_paste (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_rename (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_delete (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_find (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_select_all (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_deselect_all (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_open_with (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_password (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_view_toolbar (GSimpleAction *action, GVariant *state, gpointer data)
void activate_action_view_statusbar (GSimpleAction *action, GVariant *state, gpointer data)
void activate_action_view_folders (GSimpleAction *action, GVariant *state, gpointer data)
void activate_action_stop (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_reload (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_last_output (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_go_back (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_go_forward (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_go_up (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_go_home (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_manual (GSimpleAction *action, GVariant *parameter, gpointer data)
void activate_action_about (GSimpleAction *action, GVariant *parameter, gpointer gp)
void activate_toggle (GSimpleAction *action, GVariant *parameter, gpointer user_data)
void activate_popup_open (GtkMenuItem *menuitem, gpointer data)
void activate_popup_open_select (GtkMenuItem *menuitem, gpointer data)
void activate_popup_extract (GtkMenuItem *menuitem, gpointer data)
void activate_popup_cut (GtkMenuItem *menuitem, gpointer data)
void activate_popup_paste (GtkMenuItem *menuitem, gpointer data)
void activate_popup_rename (GtkMenuItem *menuitem, gpointer data)
void activate_popup_delete (GtkMenuItem *menuitem, gpointer data)
void activate_popup_open_folder (GtkMenuItem *menuitem, gpointer data)
void activate_popup_copy (GtkMenuItem *menuitem, gpointer data)
void activate_popup_open_folder_from_sidebar (GtkMenuItem *menuitem, gpointer data)
void activate_popup_extract_folder_from_sidebar (GtkMenuItem *menuitem, gpointer data)
void activate_popup_copy_folder_from_sidebar (GtkMenuItem *menuitem, gpointer data)
void activate_popup_cut_folder_from_sidebar (GtkMenuItem *menuitem, gpointer data)
void activate_popup_paste_folder_from_sidebar (GtkMenuItem *menuitem, gpointer data)
void activate_popup_rename_folder_from_sidebar (GtkMenuItem *menuitem, gpointer data)
void activate_popup_delete_folder_from_sidebar (GtkMenuItem *menuitem, gpointer data)
Macro Definition Documentation
ABOUT_GROUP
#define ABOUT_GROUP "About"
Definition at line 809 of file actions.c.
EMAILIFY
#define EMAILIFY (string)
Value:
(g_strdelimit ((string), "%", '@'))
Definition at line 810 of file actions.c.
Function Documentation
activate_action_about()
void activate_action_about (GSimpleAction * action, GVariant * parameter, gpointer gp)
Definition at line 813 of file actions.c.
References _, ABOUT_GROUP, action, data, EMAILIFY, error, N_, NULL, PACKAGE_URL, TRUE, and VERSION.
activate_action_add_files()
void activate_action_add_files (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 587 of file actions.c.
References action, add_files_cb(), data, and NULL.
activate_action_add_folder()
void activate_action_add_folder (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 595 of file actions.c.
References action, add_folder_cb(), data, and NULL.
activate_action_close()
void activate_action_close (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 577 of file actions.c.
References action, data, and fr_window_close().
activate_action_copy()
void activate_action_copy (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 611 of file actions.c.
References action, data, FALSE, and fr_window_copy_selection().
activate_action_cut()
void activate_action_cut (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 619 of file actions.c.
References action, data, FALSE, and fr_window_cut_selection().
activate_action_delete()
void activate_action_delete (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 643 of file actions.c.
References action, data, dlg_delete(), and NULL.
activate_action_deselect_all()
void activate_action_deselect_all (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 671 of file actions.c.
References action, data, and fr_window_unselect_all().
activate_action_extract()
void activate_action_extract (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 603 of file actions.c.
References action, data, dlg_extract(), and NULL.
activate_action_find()
void activate_action_find (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 651 of file actions.c.
References action, data, and fr_window_find().
activate_action_go_back()
void activate_action_go_back (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 764 of file actions.c.
References action, data, and fr_window_go_back().
activate_action_go_forward()
void activate_action_go_forward (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 773 of file actions.c.
References action, data, and fr_window_go_forward().
activate_action_go_home()
void activate_action_go_home (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 791 of file actions.c.
References action, data, FALSE, and fr_window_go_to_location().
activate_action_go_up()
void activate_action_go_up (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 782 of file actions.c.
References action, data, and fr_window_go_up_one_level().
activate_action_last_output()
void activate_action_last_output (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 755 of file actions.c.
References _, action, data, and fr_window_view_last_output().
activate_action_manual()
void activate_action_manual (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 800 of file actions.c.
References action, data, NULL, and show_help_dialog().
activate_action_new()
void activate_action_new (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 373 of file actions.c.
References action, data, NULL, and show_new_archive_dialog().
activate_action_open()
void activate_action_open (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 429 of file actions.c.
References _, action, data, FALSE, fr_window_get_open_default_dir(), mime_type, mime_type_desc, NULL, open_type, and TRUE.
activate_action_open_with()
void activate_action_open_with (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 681 of file actions.c.
References action, data, NULL, and open_with_cb().
activate_action_password()
void activate_action_password (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 689 of file actions.c.
References action, data, dlg_password(), and NULL.
activate_action_paste()
void activate_action_paste (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 627 of file actions.c.
References action, data, FALSE, and fr_window_paste_selection().
activate_action_properties()
void activate_action_properties (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 567 of file actions.c.
References action, data, and dlg_prop().
activate_action_reload()
void activate_action_reload (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 745 of file actions.c.
References action, data, and fr_window_archive_reload().
activate_action_rename()
void activate_action_rename (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 635 of file actions.c.
References action, data, FALSE, and fr_window_rename_selection().
activate_action_save_as()
void activate_action_save_as (GSimpleAction * action, GVariant * parameter, gpointer callback_data)
Definition at line 515 of file actions.c.
References action, data, dlg_save_as(), fr_window_get_archive_uri(), and NULL.
activate_action_select_all()
void activate_action_select_all (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 661 of file actions.c.
References action, data, and fr_window_select_all().
activate_action_stop()
void activate_action_stop (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 736 of file actions.c.
References action, data, and fr_window_stop().
activate_action_test_archive()
void activate_action_test_archive (GSimpleAction * action, GVariant * parameter, gpointer data)
Definition at line 557 of file actions.c.
References action, data, and fr_window_archive_test().
activate_action_view_folders()
void activate_action_view_folders (GSimpleAction * action, GVariant * state, gpointer data)
Definition at line 723 of file actions.c.
References action, data, ENGRAMPA_SCHEMA_UI, and PREF_UI_VIEW_FOLDERS.
activate_action_view_statusbar()
void activate_action_view_statusbar (GSimpleAction * action, GVariant * state, gpointer data)
Definition at line 710 of file actions.c.
References action, data, ENGRAMPA_SCHEMA_UI, and PREF_UI_VIEW_STATUSBAR.
activate_action_view_toolbar()
void activate_action_view_toolbar (GSimpleAction * action, GVariant * state, gpointer data)
Definition at line 697 of file actions.c.
References action, data, ENGRAMPA_SCHEMA_UI, and PREF_UI_VIEW_TOOLBAR.
activate_popup_copy()
void activate_popup_copy (GtkMenuItem * menuitem, gpointer data)
Definition at line 958 of file actions.c.
References data, FALSE, and fr_window_copy_selection().
activate_popup_copy_folder_from_sidebar()
void activate_popup_copy_folder_from_sidebar (GtkMenuItem * menuitem, gpointer data)
Definition at line 980 of file actions.c.
References data, fr_window_copy_selection(), and TRUE.
activate_popup_cut()
void activate_popup_cut (GtkMenuItem * menuitem, gpointer data)
Definition at line 922 of file actions.c.
References data, FALSE, and fr_window_cut_selection().
activate_popup_cut_folder_from_sidebar()
void activate_popup_cut_folder_from_sidebar (GtkMenuItem * menuitem, gpointer data)
Definition at line 987 of file actions.c.
References data, fr_window_cut_selection(), and TRUE.
activate_popup_delete()
void activate_popup_delete (GtkMenuItem * menuitem, gpointer data)
Definition at line 943 of file actions.c.
References data, dlg_delete(), and NULL.
activate_popup_delete_folder_from_sidebar()
void activate_popup_delete_folder_from_sidebar (GtkMenuItem * menuitem, gpointer data)
Definition at line 1008 of file actions.c.
References data, dlg_delete_from_sidebar(), and NULL.
activate_popup_extract()
void activate_popup_extract (GtkMenuItem * menuitem, gpointer data)
Definition at line 915 of file actions.c.
References data, dlg_extract(), and NULL.
activate_popup_extract_folder_from_sidebar()
void activate_popup_extract_folder_from_sidebar (GtkMenuItem * menuitem, gpointer data)
Definition at line 973 of file actions.c.
References data, dlg_extract_folder_from_sidebar(), and NULL.
activate_popup_open()
void activate_popup_open (GtkMenuItem * menuitem, gpointer data)
Definition at line 893 of file actions.c.
References data, FALSE, file_list, fr_window_get_file_list_selection(), fr_window_open_files(), and NULL.
activate_popup_open_folder()
void activate_popup_open_folder (GtkMenuItem * menuitem, gpointer data)
Definition at line 950 of file actions.c.
References data, FALSE, and fr_window_current_folder_activated().
activate_popup_open_folder_from_sidebar()
void activate_popup_open_folder_from_sidebar (GtkMenuItem * menuitem, gpointer data)
Definition at line 965 of file actions.c.
References data, fr_window_current_folder_activated(), and TRUE.
activate_popup_open_select()
void activate_popup_open_select (GtkMenuItem * menuitem, gpointer data)
Definition at line 908 of file actions.c.
References data, NULL, and open_with_cb().
activate_popup_paste()
void activate_popup_paste (GtkMenuItem * menuitem, gpointer data)
Definition at line 929 of file actions.c.
References data, FALSE, and fr_window_paste_selection().
activate_popup_paste_folder_from_sidebar()
void activate_popup_paste_folder_from_sidebar (GtkMenuItem * menuitem, gpointer data)
Definition at line 994 of file actions.c.
References data, fr_window_paste_selection(), and TRUE.
activate_popup_rename()
void activate_popup_rename (GtkMenuItem * menuitem, gpointer data)
Definition at line 936 of file actions.c.
References data, FALSE, and fr_window_rename_selection().
activate_popup_rename_folder_from_sidebar()
void activate_popup_rename_folder_from_sidebar (GtkMenuItem * menuitem, gpointer data)
Definition at line 1001 of file actions.c.
References data, fr_window_rename_selection(), and TRUE.
activate_toggle()
void activate_toggle (GSimpleAction * action, GVariant * parameter, gpointer user_data)
Definition at line 882 of file actions.c.
References action, and user_data.
init_engramp_menu_popup()
void init_engramp_menu_popup (FrWindow * window, GtkBuilder * ui)
Definition at line 335 of file actions.c.
References activate, and NULL.
show_new_archive_dialog()
void show_new_archive_dialog (FrWindow * window, const char * archive_name)
Definition at line 355 of file actions.c.
References data, dlg_new(), dlg_save_as(), and NULL.
Referenced by activate_action_new().
Variable Documentation
activate
void(* activate) (GtkMenuItem *menuitem, gpointer user_data) (GtkMenuItem * menuitem, gpointer user_data)
Definition at line 52 of file actions.c.
Referenced by init_engramp_menu_popup(), main(), nld_search_bar_set_show_button(), and nld_search_bar_set_text().
id
const char* id
Definition at line 51 of file actions.c.