MATE Desktop Environment: alsa-element.c File Reference
alsa-element.c File Reference
#include <glib.h>
#include <glib-object.h>
#include <alsa/asoundlib.h>
#include "alsa-element.h"
Functions
snd_mixer_elem_t * alsa_element_get_snd_element (AlsaElement *element)
void alsa_element_set_snd_element (AlsaElement *element, snd_mixer_elem_t *el)
gboolean alsa_element_load (AlsaElement *element)
void alsa_element_close (AlsaElement *element)
Function Documentation
alsa_element_close()
void alsa_element_close (AlsaElement * element)
Definition at line 56 of file alsa-element.c.
References ALSA_ELEMENT_GET_INTERFACE, alsa_element_set_snd_element(), ALSA_IS_ELEMENT, _AlsaElementInterface::close, and NULL.
Referenced by alsa_stream_remove_all(), and alsa_stream_remove_elements().
alsa_element_get_snd_element()
snd_mixer_elem_t * alsa_element_get_snd_element (AlsaElement * element)
Definition at line 32 of file alsa-element.c.
References ALSA_ELEMENT_GET_INTERFACE, ALSA_IS_ELEMENT, and NULL.
alsa_element_load()
gboolean alsa_element_load (AlsaElement * element)
Definition at line 48 of file alsa-element.c.
References ALSA_ELEMENT_GET_INTERFACE, ALSA_IS_ELEMENT, and FALSE.
Referenced by alsa_stream_load_elements().
alsa_element_set_snd_element()
void alsa_element_set_snd_element (AlsaElement * element, snd_mixer_elem_t * el)
Definition at line 40 of file alsa-element.c.
References ALSA_ELEMENT_GET_INTERFACE, and ALSA_IS_ELEMENT.
Referenced by alsa_element_close().