MATE Desktop Environment: alsa-stream.h File Reference
alsa-stream.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include "alsa-types.h"
Classes
struct _AlsaStream
struct _AlsaStreamClass
Macros
#define ALSA_TYPE_STREAM (alsa_stream_get_type ())
#define ALSA_STREAM(o)
#define ALSA_IS_STREAM(o)
#define ALSA_STREAM_CLASS(k)
#define ALSA_IS_STREAM_CLASS(k)
#define ALSA_STREAM_GET_CLASS(o)
Typedefs
typedef struct _AlsaStreamClass AlsaStreamClass
typedef struct _AlsaStreamPrivate AlsaStreamPrivate
Functions
GType alsa_stream_get_type (void)
AlsaStream * alsa_stream_new (const gchar *name, MateMixerDevice *device, MateMixerDirection direction)
void alsa_stream_add_control (AlsaStream *stream, AlsaStreamControl *control)
void alsa_stream_add_switch (AlsaStream *stream, AlsaSwitch *swtch)
void alsa_stream_add_toggle (AlsaStream *stream, AlsaToggle *toggle)
gboolean alsa_stream_has_controls (AlsaStream *stream)
gboolean alsa_stream_has_switches (AlsaStream *stream)
gboolean alsa_stream_has_controls_or_switches (AlsaStream *stream)
gboolean alsa_stream_has_default_control (AlsaStream *stream)
AlsaStreamControl * alsa_stream_get_default_control (AlsaStream *stream)
void alsa_stream_set_default_control (AlsaStream *stream, AlsaStreamControl *control)
void alsa_stream_load_elements (AlsaStream *stream, const gchar *name)
gboolean alsa_stream_remove_elements (AlsaStream *stream, const gchar *name)
void alsa_stream_remove_all (AlsaStream *stream)
Macro Definition Documentation
ALSA_IS_STREAM
#define ALSA_IS_STREAM (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), ALSA_TYPE_STREAM))
Definition at line 33 of file alsa-stream.h.
Referenced by alsa_stream_add_control(), alsa_stream_add_switch(), alsa_stream_add_toggle(), alsa_stream_get_default_control(), alsa_stream_has_controls(), alsa_stream_has_controls_or_switches(), alsa_stream_has_default_control(), alsa_stream_has_switches(), alsa_stream_input_control_new(), alsa_stream_load_elements(), alsa_stream_output_control_new(), alsa_stream_remove_all(), alsa_stream_remove_elements(), alsa_stream_set_default_control(), alsa_switch_new(), and alsa_toggle_new().
ALSA_IS_STREAM_CLASS
#define ALSA_IS_STREAM_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), ALSA_TYPE_STREAM))
Definition at line 37 of file alsa-stream.h.
ALSA_STREAM
#define ALSA_STREAM (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), ALSA_TYPE_STREAM, AlsaStream))
Definition at line 31 of file alsa-stream.h.
ALSA_STREAM_CLASS
#define ALSA_STREAM_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST ((k), ALSA_TYPE_STREAM, AlsaStreamClass))
Definition at line 35 of file alsa-stream.h.
ALSA_STREAM_GET_CLASS
#define ALSA_STREAM_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), ALSA_TYPE_STREAM, AlsaStreamClass))
Definition at line 39 of file alsa-stream.h.
ALSA_TYPE_STREAM
#define ALSA_TYPE_STREAM (alsa_stream_get_type ())
Definition at line 29 of file alsa-stream.h.
Referenced by alsa_stream_new().
Typedef Documentation
AlsaStreamClass
typedef struct _AlsaStreamClass AlsaStreamClass
Definition at line 42 of file alsa-stream.h.
AlsaStreamPrivate
typedef struct _AlsaStreamPrivate AlsaStreamPrivate
Definition at line 43 of file alsa-stream.h.
Function Documentation
alsa_stream_add_control()
void alsa_stream_add_control (AlsaStream * stream, AlsaStreamControl * control)
Definition at line 108 of file alsa-stream.c.
References ALSA_IS_STREAM, ALSA_IS_STREAM_CONTROL, alsa_stream_has_default_control(), alsa_stream_set_default_control(), FALSE, MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), and name.
alsa_stream_add_switch()
void alsa_stream_add_switch (AlsaStream * stream, AlsaSwitch * swtch)
Definition at line 129 of file alsa-stream.c.
References ALSA_IS_STREAM, ALSA_IS_SWITCH, MATE_MIXER_SWITCH, mate_mixer_switch_get_name(), and name.
alsa_stream_add_toggle()
void alsa_stream_add_toggle (AlsaStream * stream, AlsaToggle * toggle)
Definition at line 147 of file alsa-stream.c.
References ALSA_IS_STREAM, ALSA_IS_TOGGLE, MATE_MIXER_SWITCH, mate_mixer_switch_get_name(), and name.
alsa_stream_get_default_control()
AlsaStreamControl * alsa_stream_get_default_control (AlsaStream * stream)
Definition at line 211 of file alsa-stream.c.
References ALSA_IS_STREAM, ALSA_STREAM_CONTROL, MATE_MIXER_STREAM, mate_mixer_stream_get_default_control(), and NULL.
alsa_stream_get_type()
GType alsa_stream_get_type (void)
References name.
alsa_stream_has_controls()
gboolean alsa_stream_has_controls (AlsaStream * stream)
Definition at line 166 of file alsa-stream.c.
References ALSA_IS_STREAM, FALSE, NULL, and TRUE.
alsa_stream_has_controls_or_switches()
gboolean alsa_stream_has_controls_or_switches (AlsaStream * stream)
Definition at line 188 of file alsa-stream.c.
References ALSA_IS_STREAM, FALSE, NULL, and TRUE.
Referenced by alsa_device_close(), alsa_device_get_input_stream(), and alsa_device_get_output_stream().
alsa_stream_has_default_control()
gboolean alsa_stream_has_default_control (AlsaStream * stream)
Definition at line 200 of file alsa-stream.c.
References ALSA_IS_STREAM, FALSE, MATE_MIXER_STREAM, mate_mixer_stream_get_default_control(), NULL, and TRUE.
Referenced by alsa_stream_add_control().
alsa_stream_has_switches()
gboolean alsa_stream_has_switches (AlsaStream * stream)
Definition at line 177 of file alsa-stream.c.
References ALSA_IS_STREAM, FALSE, NULL, and TRUE.
alsa_stream_load_elements()
void alsa_stream_load_elements (AlsaStream * stream, const gchar * name)
Definition at line 238 of file alsa-stream.c.
References ALSA_ELEMENT, alsa_element_load(), ALSA_IS_STREAM, item, name, and NULL.
alsa_stream_new()
AlsaStream * alsa_stream_new (const gchar * name, MateMixerDevice * device, MateMixerDirection direction)
Definition at line 88 of file alsa-stream.c.
References ALSA_IS_DEVICE, ALSA_TYPE_STREAM, label, mate_mixer_device_get_label(), name, and NULL.
Referenced by alsa_device_new().
alsa_stream_remove_all()
void alsa_stream_remove_all (AlsaStream * stream)
Definition at line 307 of file alsa-stream.c.
References ALSA_ELEMENT, alsa_element_close(), ALSA_IS_STREAM, alsa_stream_set_default_control(), MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), MATE_MIXER_SWITCH, mate_mixer_switch_get_name(), and NULL.
Referenced by alsa_device_close().
alsa_stream_remove_elements()
gboolean alsa_stream_remove_elements (AlsaStream * stream, const gchar * name)
Definition at line 255 of file alsa-stream.c.
References ALSA_ELEMENT, alsa_element_close(), ALSA_IS_STREAM, ALSA_STREAM_CONTROL, alsa_stream_set_default_control(), FALSE, item, MATE_MIXER_STREAM, MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), mate_mixer_stream_get_default_control(), MATE_MIXER_SWITCH, mate_mixer_switch_get_name(), name, NULL, and TRUE.
alsa_stream_set_default_control()
void alsa_stream_set_default_control (AlsaStream * stream, AlsaStreamControl * control)
Definition at line 225 of file alsa-stream.c.
References _mate_mixer_stream_set_default_control(), ALSA_IS_STREAM, ALSA_IS_STREAM_CONTROL, MATE_MIXER_STREAM, MATE_MIXER_STREAM_CONTROL, and NULL.
Referenced by alsa_stream_add_control(), alsa_stream_remove_all(), and alsa_stream_remove_elements().