MATE Desktop Environment: alsa-stream.c File Reference
alsa-stream.c File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include <libmatemixer/matemixer-private.h>
#include "alsa-device.h"
#include "alsa-element.h"
#include "alsa-stream.h"
#include "alsa-stream-control.h"
#include "alsa-switch.h"
#include "alsa-toggle.h"
Functions
AlsaStream * alsa_stream_new (const gchar *name, MateMixerDevice *device, MateMixerDirection direction)
void alsa_stream_add_control (AlsaStream *stream, AlsaStreamControl *control)
void alsa_stream_add_switch (AlsaStream *stream, AlsaSwitch *swtch)
void alsa_stream_add_toggle (AlsaStream *stream, AlsaToggle *toggle)
gboolean alsa_stream_has_controls (AlsaStream *stream)
gboolean alsa_stream_has_switches (AlsaStream *stream)
gboolean alsa_stream_has_controls_or_switches (AlsaStream *stream)
gboolean alsa_stream_has_default_control (AlsaStream *stream)
AlsaStreamControl * alsa_stream_get_default_control (AlsaStream *stream)
void alsa_stream_set_default_control (AlsaStream *stream, AlsaStreamControl *control)
void alsa_stream_load_elements (AlsaStream *stream, const gchar *name)
gboolean alsa_stream_remove_elements (AlsaStream *stream, const gchar *name)
void alsa_stream_remove_all (AlsaStream *stream)
Function Documentation
alsa_stream_add_control()
void alsa_stream_add_control (AlsaStream * stream, AlsaStreamControl * control)
Definition at line 108 of file alsa-stream.c.
References ALSA_IS_STREAM, ALSA_IS_STREAM_CONTROL, alsa_stream_has_default_control(), alsa_stream_set_default_control(), FALSE, MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), and name.
alsa_stream_add_switch()
void alsa_stream_add_switch (AlsaStream * stream, AlsaSwitch * swtch)
Definition at line 129 of file alsa-stream.c.
References ALSA_IS_STREAM, ALSA_IS_SWITCH, MATE_MIXER_SWITCH, mate_mixer_switch_get_name(), and name.
alsa_stream_add_toggle()
void alsa_stream_add_toggle (AlsaStream * stream, AlsaToggle * toggle)
Definition at line 147 of file alsa-stream.c.
References ALSA_IS_STREAM, ALSA_IS_TOGGLE, MATE_MIXER_SWITCH, mate_mixer_switch_get_name(), and name.
alsa_stream_get_default_control()
AlsaStreamControl * alsa_stream_get_default_control (AlsaStream * stream)
Definition at line 211 of file alsa-stream.c.
References ALSA_IS_STREAM, ALSA_STREAM_CONTROL, MATE_MIXER_STREAM, mate_mixer_stream_get_default_control(), and NULL.
alsa_stream_has_controls()
gboolean alsa_stream_has_controls (AlsaStream * stream)
Definition at line 166 of file alsa-stream.c.
References ALSA_IS_STREAM, FALSE, NULL, and TRUE.
alsa_stream_has_controls_or_switches()
gboolean alsa_stream_has_controls_or_switches (AlsaStream * stream)
Definition at line 188 of file alsa-stream.c.
References ALSA_IS_STREAM, FALSE, NULL, and TRUE.
Referenced by alsa_device_close(), alsa_device_get_input_stream(), and alsa_device_get_output_stream().
alsa_stream_has_default_control()
gboolean alsa_stream_has_default_control (AlsaStream * stream)
Definition at line 200 of file alsa-stream.c.
References ALSA_IS_STREAM, FALSE, MATE_MIXER_STREAM, mate_mixer_stream_get_default_control(), NULL, and TRUE.
Referenced by alsa_stream_add_control().
alsa_stream_has_switches()
gboolean alsa_stream_has_switches (AlsaStream * stream)
Definition at line 177 of file alsa-stream.c.
References ALSA_IS_STREAM, FALSE, NULL, and TRUE.
alsa_stream_load_elements()
void alsa_stream_load_elements (AlsaStream * stream, const gchar * name)
Definition at line 238 of file alsa-stream.c.
References ALSA_ELEMENT, alsa_element_load(), ALSA_IS_STREAM, item, name, and NULL.
alsa_stream_new()
AlsaStream * alsa_stream_new (const gchar * name, MateMixerDevice * device, MateMixerDirection direction)
Definition at line 88 of file alsa-stream.c.
References ALSA_IS_DEVICE, ALSA_TYPE_STREAM, label, mate_mixer_device_get_label(), name, and NULL.
Referenced by alsa_device_new().
alsa_stream_remove_all()
void alsa_stream_remove_all (AlsaStream * stream)
Definition at line 307 of file alsa-stream.c.
References ALSA_ELEMENT, alsa_element_close(), ALSA_IS_STREAM, alsa_stream_set_default_control(), MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), MATE_MIXER_SWITCH, mate_mixer_switch_get_name(), and NULL.
Referenced by alsa_device_close().
alsa_stream_remove_elements()
gboolean alsa_stream_remove_elements (AlsaStream * stream, const gchar * name)
Definition at line 255 of file alsa-stream.c.
References ALSA_ELEMENT, alsa_element_close(), ALSA_IS_STREAM, ALSA_STREAM_CONTROL, alsa_stream_set_default_control(), FALSE, item, MATE_MIXER_STREAM, MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), mate_mixer_stream_get_default_control(), MATE_MIXER_SWITCH, mate_mixer_switch_get_name(), name, NULL, and TRUE.
alsa_stream_set_default_control()
void alsa_stream_set_default_control (AlsaStream * stream, AlsaStreamControl * control)
Definition at line 225 of file alsa-stream.c.
References _mate_mixer_stream_set_default_control(), ALSA_IS_STREAM, ALSA_IS_STREAM_CONTROL, MATE_MIXER_STREAM, MATE_MIXER_STREAM_CONTROL, and NULL.
Referenced by alsa_stream_add_control(), alsa_stream_remove_all(), and alsa_stream_remove_elements().