MATE Desktop Environment: alsa-device.h File Reference
alsa-device.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include "alsa-types.h"
Classes
struct _AlsaDevice
struct _AlsaDeviceClass
Macros
#define ALSA_TYPE_DEVICE (alsa_device_get_type ())
#define ALSA_DEVICE(o)
#define ALSA_IS_DEVICE(o)
#define ALSA_DEVICE_CLASS(k)
#define ALSA_IS_DEVICE_CLASS(k)
#define ALSA_DEVICE_GET_CLASS(o)
Typedefs
typedef struct _AlsaDeviceClass AlsaDeviceClass
typedef struct _AlsaDevicePrivate AlsaDevicePrivate
Functions
GType alsa_device_get_type (void)
AlsaDevice * alsa_device_new (const gchar *name, const gchar *label)
gboolean alsa_device_open (AlsaDevice *device)
gboolean alsa_device_is_open (AlsaDevice *device)
void alsa_device_close (AlsaDevice *device)
void alsa_device_load (AlsaDevice *device)
AlsaStream * alsa_device_get_input_stream (AlsaDevice *device)
AlsaStream * alsa_device_get_output_stream (AlsaDevice *device)
Macro Definition Documentation
ALSA_DEVICE
#define ALSA_DEVICE (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), ALSA_TYPE_DEVICE, AlsaDevice))
Definition at line 31 of file alsa-device.h.
ALSA_DEVICE_CLASS
#define ALSA_DEVICE_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST ((k), ALSA_TYPE_DEVICE, AlsaDeviceClass))
Definition at line 35 of file alsa-device.h.
ALSA_DEVICE_GET_CLASS
#define ALSA_DEVICE_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), ALSA_TYPE_DEVICE, AlsaDeviceClass))
Definition at line 39 of file alsa-device.h.
ALSA_IS_DEVICE
#define ALSA_IS_DEVICE (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), ALSA_TYPE_DEVICE))
Definition at line 33 of file alsa-device.h.
Referenced by alsa_device_close(), alsa_device_get_input_stream(), alsa_device_get_output_stream(), alsa_device_is_open(), alsa_device_load(), alsa_device_open(), and alsa_stream_new().
ALSA_IS_DEVICE_CLASS
#define ALSA_IS_DEVICE_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), ALSA_TYPE_DEVICE))
Definition at line 37 of file alsa-device.h.
ALSA_TYPE_DEVICE
#define ALSA_TYPE_DEVICE (alsa_device_get_type ())
Definition at line 29 of file alsa-device.h.
Referenced by alsa_device_new().
Typedef Documentation
AlsaDeviceClass
typedef struct _AlsaDeviceClass AlsaDeviceClass
Definition at line 42 of file alsa-device.h.
AlsaDevicePrivate
typedef struct _AlsaDevicePrivate AlsaDevicePrivate
Definition at line 43 of file alsa-device.h.
Function Documentation
alsa_device_close()
void alsa_device_close (AlsaDevice * device)
Definition at line 326 of file alsa-device.c.
References ALSA_IS_DEVICE, alsa_stream_has_controls_or_switches(), alsa_stream_remove_all(), CLOSED, MATE_MIXER_STREAM, mate_mixer_stream_get_name(), name, NULL, _AlsaDevice::priv, and TRUE.
alsa_device_get_input_stream()
AlsaStream * alsa_device_get_input_stream (AlsaDevice * device)
Definition at line 403 of file alsa-device.c.
References ALSA_IS_DEVICE, alsa_stream_has_controls_or_switches(), NULL, _AlsaDevice::priv, and TRUE.
alsa_device_get_output_stream()
AlsaStream * alsa_device_get_output_stream (AlsaDevice * device)
Definition at line 416 of file alsa-device.c.
References ALSA_IS_DEVICE, alsa_stream_has_controls_or_switches(), NULL, _AlsaDevice::priv, and TRUE.
alsa_device_get_type()
GType alsa_device_get_type (void)
References label, and name.
alsa_device_is_open()
gboolean alsa_device_is_open (AlsaDevice * device)
Definition at line 315 of file alsa-device.c.
References ALSA_IS_DEVICE, FALSE, NULL, _AlsaDevice::priv, and TRUE.
alsa_device_load()
void alsa_device_load (AlsaDevice * device)
Definition at line 364 of file alsa-device.c.
References ALSA_IS_DEVICE, error, NULL, and _AlsaDevice::priv.
alsa_device_new()
AlsaDevice * alsa_device_new (const gchar * name, const gchar * label)
Definition at line 228 of file alsa-device.c.
References ALSA_DEVICE_ICON, alsa_stream_new(), ALSA_TYPE_DEVICE, label, MATE_MIXER_DEVICE, MATE_MIXER_DIRECTION_INPUT, MATE_MIXER_DIRECTION_OUTPUT, name, NULL, and _AlsaDevice::priv.
alsa_device_open()
gboolean alsa_device_open (AlsaDevice * device)
Definition at line 261 of file alsa-device.c.
References ALSA_IS_DEVICE, FALSE, MATE_MIXER_DEVICE, mate_mixer_device_get_label(), mate_mixer_device_get_name(), name, NULL, _AlsaDevice::priv, and TRUE.