MATE Desktop Environment: apm.h File Reference
apm.h File Reference
#include <linux/apm_bios.h>
#include <sys/types.h>
Classes
struct apm_info
Macros
#define APM_PROC "/proc/apm"
#define APM_DEVICE "/dev/apm_bios"
#define APM_DEV "/proc/devices"
#define APM_NAME "apm_bios"
#define APM_32_BIT_SUPPORT 0x0002
#define SUSPEND 0
#define STANDBY 1
#define IGNORE 2
#define NOIGNORE 3
Typedefs
typedef struct apm_info apm_info
Functions
int apm_exists (void)
int apm_read (apm_info *i)
dev_t apm_dev (void)
int apm_open (void)
int apm_close (int fd)
int apm_get_events (int fd, int timeout, apm_event_t *events, int n)
int apm_suspend (int fd)
int apm_standby (int fd)
int apm_set_ignore (int fd, int mode)
unsigned int apm_last_error (int fd)
const char * apm_error_name (unsigned int err)
int apm_reject (int fd)
const char * apm_event_name (apm_event_t event)
const char * apm_time (time_t t)
const char * apm_delta_time (time_t then, time_t now)
const char * apm_time_nosec (time_t t)
Macro Definition Documentation
APM_32_BIT_SUPPORT
#define APM_32_BIT_SUPPORT 0x0002
Definition at line 36 of file apm.h.
Referenced by apm_read().
APM_DEV
#define APM_DEV "/proc/devices"
Definition at line 32 of file apm.h.
Referenced by apm_dev().
APM_DEVICE
#define APM_DEVICE "/dev/apm_bios"
Definition at line 30 of file apm.h.
Referenced by apm_open().
APM_NAME
#define APM_NAME "apm_bios"
Definition at line 33 of file apm.h.
Referenced by apm_dev().
APM_PROC
#define APM_PROC "/proc/apm"
Definition at line 29 of file apm.h.
Referenced by apm_dev(), apm_exists(), apm_open(), and apm_read().
IGNORE
#define IGNORE 2
Definition at line 73 of file apm.h.
NOIGNORE
#define NOIGNORE 3
Definition at line 74 of file apm.h.
STANDBY
#define STANDBY 1
Definition at line 72 of file apm.h.
SUSPEND
#define SUSPEND 0
Definition at line 71 of file apm.h.
Typedef Documentation
apm_info
typedef struct apm_info apm_info
Function Documentation
apm_close()
int apm_close (int fd) extern
Definition at line 244 of file apmlib.c.
apm_delta_time()
const char * apm_delta_time (time_t then, time_t now) extern
Definition at line 431 of file apmlib.c.
References apm_time().
apm_dev()
dev_t apm_dev (void) extern
Definition at line 170 of file apmlib.c.
References APM_DEV, APM_NAME, APM_PROC, apm_read(), and apm_info::driver_version.
Referenced by apm_open().
apm_error_name()
const char * apm_error_name (unsigned int err) extern
Definition at line 340 of file apmlib.c.
References ERROR_COUNT, and key.
apm_event_name()
const char * apm_event_name (apm_event_t event) extern
Definition at line 388 of file apmlib.c.
apm_exists()
int apm_exists (void) extern
Definition at line 41 of file apmlib.c.
References APM_PROC, and apm_read().
Referenced by power_management_initialise().
apm_get_events()
int apm_get_events (int fd, int timeout, apm_event_t * events, int n) extern
Definition at line 260 of file apmlib.c.
References NULL.
apm_last_error()
unsigned int apm_last_error (int fd) extern
Definition at line 295 of file apmlib.c.
Referenced by apm_reject().
apm_open()
int apm_open (void) extern
Definition at line 216 of file apmlib.c.
References apm_dev(), APM_DEVICE, APM_PROC, apm_read(), and apm_info::driver_version.
apm_read()
int apm_read (apm_info * i) extern
Definition at line 54 of file apmlib.c.
References apm_info::ac_line_status, APM_32_BIT_SUPPORT, apm_info::apm_flags, APM_PROC, apm_info::apm_version_major, apm_info::apm_version_minor, apm_info::battery_flags, apm_info::battery_percentage, apm_info::battery_status, apm_info::battery_time, apm_info::driver_version, NULL, and apm_info::using_minutes.
Referenced by apm_dev(), apm_exists(), and apm_open().
apm_reject()
int apm_reject (int fd) extern
Definition at line 351 of file apmlib.c.
References apm_last_error(), and NULL.
apm_set_ignore()
int apm_set_ignore (int fd, int mode) extern
apm_standby()
int apm_standby (int fd) extern
Definition at line 287 of file apmlib.c.
References NULL.
apm_suspend()
int apm_suspend (int fd) extern
Definition at line 279 of file apmlib.c.
References NULL.
apm_time()
const char * apm_time (time_t t) extern
Definition at line 437 of file apmlib.c.
References SEC_PER_DAY, SEC_PER_HOUR, and SEC_PER_MIN.
Referenced by apm_delta_time().
apm_time_nosec()
const char * apm_time_nosec (time_t t) extern
Definition at line 463 of file apmlib.c.
References SEC_PER_DAY, SEC_PER_HOUR, and SEC_PER_MIN.