MATE Desktop Environment: apmlib.c File Reference
apmlib.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <fcntl.h>
#include <ctype.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <sys/sysmacros.h>
#include "apm.h"
Macros
#define BACKWARD_COMPAT 1
#define ERROR_COUNT (sizeof(error_table)/sizeof(lookup_t))
#define SEC_PER_DAY (60*60*24)
#define SEC_PER_HOUR (60*60)
#define SEC_PER_MIN (60)
Typedefs
typedef struct lookup_t lookup_t
Functions
int apm_exists (void)
int apm_read (apm_info *i)
dev_t apm_dev (void)
int apm_open (void)
int apm_close (int fd)
int apm_get_events (int fd, int timeout, apm_event_t *events, int n)
int apm_suspend (int fd)
int apm_standby (int fd)
unsigned int apm_last_error (int fd)
const char * apm_error_name (unsigned int err)
int apm_reject (int fd)
const char * apm_event_name (apm_event_t event)
const char * apm_delta_time (time_t then, time_t now)
const char * apm_time (time_t t)
const char * apm_time_nosec (time_t t)
Macro Definition Documentation
BACKWARD_COMPAT
#define BACKWARD_COMPAT 1
Definition at line 34 of file apmlib.c.
ERROR_COUNT
#define ERROR_COUNT (sizeof(error_table)/sizeof(lookup_t))
Definition at line 336 of file apmlib.c.
Referenced by apm_error_name().
SEC_PER_DAY
#define SEC_PER_DAY (60*60*24)
Definition at line 426 of file apmlib.c.
Referenced by apm_time(), and apm_time_nosec().
SEC_PER_HOUR
#define SEC_PER_HOUR (60*60)
Definition at line 427 of file apmlib.c.
Referenced by apm_time(), and apm_time_nosec().
SEC_PER_MIN
#define SEC_PER_MIN (60)
Definition at line 428 of file apmlib.c.
Referenced by apm_time(), and apm_time_nosec().
Typedef Documentation
lookup_t
typedef struct lookup_t lookup_t
Function Documentation
apm_close()
int apm_close (int fd)
Definition at line 244 of file apmlib.c.
apm_delta_time()
const char * apm_delta_time (time_t then, time_t now)
Definition at line 431 of file apmlib.c.
References apm_time().
apm_dev()
dev_t apm_dev (void)
Definition at line 170 of file apmlib.c.
References APM_DEV, APM_NAME, APM_PROC, apm_read(), and apm_info::driver_version.
Referenced by apm_open().
apm_error_name()
const char * apm_error_name (unsigned int err)
Definition at line 340 of file apmlib.c.
References ERROR_COUNT, and key.
apm_event_name()
const char * apm_event_name (apm_event_t event)
Definition at line 388 of file apmlib.c.
apm_exists()
int apm_exists (void)
Definition at line 41 of file apmlib.c.
References APM_PROC, and apm_read().
Referenced by power_management_initialise().
apm_get_events()
int apm_get_events (int fd, int timeout, apm_event_t * events, int n)
Definition at line 260 of file apmlib.c.
References NULL.
apm_last_error()
unsigned int apm_last_error (int fd)
Definition at line 295 of file apmlib.c.
Referenced by apm_reject().
apm_open()
int apm_open (void)
Definition at line 216 of file apmlib.c.
References apm_dev(), APM_DEVICE, APM_PROC, apm_read(), and apm_info::driver_version.
apm_read()
int apm_read (apm_info * i)
Definition at line 54 of file apmlib.c.
References apm_info::ac_line_status, APM_32_BIT_SUPPORT, apm_info::apm_flags, APM_PROC, apm_info::apm_version_major, apm_info::apm_version_minor, apm_info::battery_flags, apm_info::battery_percentage, apm_info::battery_status, apm_info::battery_time, apm_info::driver_version, NULL, and apm_info::using_minutes.
Referenced by apm_dev(), apm_exists(), and apm_open().
apm_reject()
int apm_reject (int fd)
Definition at line 351 of file apmlib.c.
References apm_last_error(), and NULL.
apm_standby()
int apm_standby (int fd)
Definition at line 287 of file apmlib.c.
References NULL.
apm_suspend()
int apm_suspend (int fd)
Definition at line 279 of file apmlib.c.
References NULL.
apm_time()
const char * apm_time (time_t t)
Definition at line 437 of file apmlib.c.
References SEC_PER_DAY, SEC_PER_HOUR, and SEC_PER_MIN.
Referenced by apm_delta_time().
apm_time_nosec()
const char * apm_time_nosec (time_t t)
Definition at line 463 of file apmlib.c.
References SEC_PER_DAY, SEC_PER_HOUR, and SEC_PER_MIN.