MATE Desktop Environment: app-shell.h File Reference
app-shell.h File Reference
#include <glib.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <matemenu-tree.h>
#include <libmate-desktop/mate-desktop-item.h>
#include "slab-section.h"
#include "tile.h"
Classes
struct NewAppConfig
struct _AppShellData
struct CategoryData
struct AppAction
struct NewAppData
Macros
#define MATEMENU_I_KNOW_THIS_IS_UNSTABLE
#define GROUP_POSITION_NUMBER_KEY "Unique Group Position Number"
#define APP_ACTION_KEY "Unique Application Action Key"
#define SIZING_SCREEN_WIDTH_LARGE 1024
#define SIZING_SCREEN_WIDTH_MEDIUM 800
#define SIZING_SCREEN_WIDTH_SMALL 640
#define SIZING_SCREEN_WIDTH_LARGE_NUMCOLS 3
#define SIZING_SCREEN_WIDTH_MEDIUM_NUMCOLS 2
#define SIZING_SCREEN_WIDTH_SMALL_NUMCOLS 1
#define SIZING_TILE_WIDTH 230
#define SIZING_HEIGHT_PERCENT 0.8
Typedefs
typedef struct _AppShellData AppShellData
Functions
void generate_categories (AppShellData *app_data)
AppShellData * appshelldata_new (const gchar *menu_name, GtkIconSize icon_size, gboolean show_tile_generic_name, gboolean exit_on_close, gint new_apps_max_items)
void layout_shell (AppShellData *app_data, const gchar *filter_title, const gchar *groups_title, const gchar *actions_title, GSList *actions, void(*actions_handler)(Tile *, TileEvent *, gpointer))
gboolean create_main_window (AppShellData *app_data, const gchar *app_name, const gchar *title, const gchar *window_icon, gint width, gint height, gboolean hidden)
void hide_shell (AppShellData *app_data)
void show_shell (AppShellData *app_data)
Macro Definition Documentation
APP_ACTION_KEY
#define APP_ACTION_KEY "Unique Application Action Key"
Definition at line 37 of file app-shell.h.
Referenced by handle_static_action_clicked().
GROUP_POSITION_NUMBER_KEY
#define GROUP_POSITION_NUMBER_KEY "Unique Group Position Number"
Definition at line 36 of file app-shell.h.
MATEMENU_I_KNOW_THIS_IS_UNSTABLE
#define MATEMENU_I_KNOW_THIS_IS_UNSTABLE
Definition at line 27 of file app-shell.h.
SIZING_HEIGHT_PERCENT
#define SIZING_HEIGHT_PERCENT 0.8
Definition at line 47 of file app-shell.h.
SIZING_SCREEN_WIDTH_LARGE
#define SIZING_SCREEN_WIDTH_LARGE 1024
Definition at line 40 of file app-shell.h.
Referenced by layout_shell().
SIZING_SCREEN_WIDTH_LARGE_NUMCOLS
#define SIZING_SCREEN_WIDTH_LARGE_NUMCOLS 3
Definition at line 43 of file app-shell.h.
Referenced by layout_shell().
SIZING_SCREEN_WIDTH_MEDIUM
#define SIZING_SCREEN_WIDTH_MEDIUM 800
Definition at line 41 of file app-shell.h.
Referenced by layout_shell().
SIZING_SCREEN_WIDTH_MEDIUM_NUMCOLS
#define SIZING_SCREEN_WIDTH_MEDIUM_NUMCOLS 2
Definition at line 44 of file app-shell.h.
Referenced by layout_shell().
SIZING_SCREEN_WIDTH_SMALL
#define SIZING_SCREEN_WIDTH_SMALL 640
Definition at line 42 of file app-shell.h.
SIZING_SCREEN_WIDTH_SMALL_NUMCOLS
#define SIZING_SCREEN_WIDTH_SMALL_NUMCOLS 1
Definition at line 45 of file app-shell.h.
Referenced by layout_shell().
SIZING_TILE_WIDTH
#define SIZING_TILE_WIDTH 230
Definition at line 46 of file app-shell.h.
Typedef Documentation
AppShellData
typedef struct _AppShellData AppShellData
Function Documentation
appshelldata_new()
AppShellData * appshelldata_new (const gchar * menu_name, GtkIconSize icon_size, gboolean show_tile_generic_name, gboolean exit_on_close, gint new_apps_max_items)
Definition at line 871 of file app-shell.c.
References _, CC_SCHEMA, _AppShellData::exit_on_close, _AppShellData::icon_size, NewAppConfig::max_items, _AppShellData::menu_name, NewAppConfig::name, _AppShellData::new_apps, _AppShellData::settings, _AppShellData::show_tile_generic_name, _AppShellData::stop_incremental_relayout, and TRUE.
create_main_window()
gboolean create_main_window (AppShellData * app_data, const gchar * app_name, const gchar * title, const gchar * window_icon, gint width, gint height, gboolean hidden)
Definition at line 122 of file app-shell.c.
References _AppShellData::main_app, _AppShellData::shell, show_shell(), and TRUE.
generate_categories()
void generate_categories (AppShellData * app_data)
Definition at line 889 of file app-shell.c.
References _, category, error, FALSE, _AppShellData::hash, item, matemenu_tree_directory_get_name(), matemenu_tree_directory_iter(), MATEMENU_TREE_FLAGS_NONE, matemenu_tree_get_root_directory(), MATEMENU_TREE_ITEM_DIRECTORY, MATEMENU_TREE_ITEM_ENTRY, MATEMENU_TREE_ITEM_INVALID, matemenu_tree_item_unref(), matemenu_tree_iter_get_directory(), matemenu_tree_iter_next(), matemenu_tree_iter_unref(), matemenu_tree_load_sync(), matemenu_tree_new(), NewAppConfig::max_items, _AppShellData::menu_name, _AppShellData::new_apps, NULL, _AppShellData::tree, and TRUE.
Referenced by regenerate_categories().
hide_shell()
void hide_shell (AppShellData * app_data)
Definition at line 95 of file app-shell.c.
References _AppShellData::main_app, _AppShellData::main_app_window_x, and _AppShellData::main_app_window_y.
Referenced by handle_static_action_clicked().
layout_shell()
void layout_shell (AppShellData * app_data, const gchar * filter_title, const gchar * groups_title, const gchar * actions_title, GSList * actions, void(* actions_handler)(Tile *, TileEvent *, gpointer))
Definition at line 246 of file app-shell.c.
References _AppShellData::actions_section, APP_RESIZER, app_resizer_new(), app_resizer_set_table_cache(), _AppShellData::cached_tables_list, _AppShellData::category_layout, FALSE, _AppShellData::filter_section, _AppShellData::groups_section, NULL, num_cols, _AppShellData::shell, SHELL_WINDOW, shell_window_new(), shell_window_set_contents(), SIZING_SCREEN_WIDTH_LARGE, SIZING_SCREEN_WIDTH_LARGE_NUMCOLS, SIZING_SCREEN_WIDTH_MEDIUM, SIZING_SCREEN_WIDTH_MEDIUM_NUMCOLS, SIZING_SCREEN_WIDTH_SMALL_NUMCOLS, _AppShellData::static_actions, and TRUE.
show_shell()
void show_shell (AppShellData * app_data)
Definition at line 105 of file app-shell.c.
References _AppShellData::actions_section, _AppShellData::main_app, _AppShellData::main_app_window_shown_once, _AppShellData::main_app_window_x, _AppShellData::main_app_window_y, _AppShellData::shell, SHELL_WINDOW, shell_window_clear_resize_handler(), _AppShellData::static_actions, and TRUE.
Referenced by create_main_window().