MATE Desktop Environment: appearance-themes.c File Reference
appearance-themes.c File Reference
#include "appearance.h"
#include "theme-thumbnail.h"
#include "mate-theme-apply.h"
#include "theme-installer.h"
#include "theme-save.h"
#include "theme-util.h"
#include "gtkrc-utils.h"
#include "appearance-themes.h"
#include <glib/gi18n.h>
#include <string.h>
#include <libmate-desktop/mate-desktop-thumbnail.h>
#include <libmate-desktop/mate-gsettings.h>
Macros
#define CUSTOM_THEME_NAME "__custom__"
Enumerations
enum { RESPONSE_APPLY_BG , RESPONSE_REVERT_FONT , RESPONSE_APPLY_FONT , RESPONSE_INSTALL_ENGINE }
enum { TARGET_URI_LIST , TARGET_NS_URL }
Functions
void themes_init (AppearanceData *data)
void themes_shutdown (AppearanceData *data)
Macro Definition Documentation
CUSTOM_THEME_NAME
#define CUSTOM_THEME_NAME "__custom__"
Definition at line 36 of file appearance-themes.c.
Referenced by custom_theme_dir_path(), and themes_init().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RESPONSE_APPLY_BG
RESPONSE_REVERT_FONT
RESPONSE_APPLY_FONT
RESPONSE_INSTALL_ENGINE
Definition at line 38 of file appearance-themes.c.
anonymous enum
anonymous enum
Enumerator
TARGET_URI_LIST
TARGET_NS_URL
Definition at line 45 of file appearance-themes.c.
Function Documentation
themes_init()
void themes_init (AppearanceData * data)
Definition at line 976 of file appearance-themes.c.
References _, appearance_capplet_get_widget, COL_LABEL, COL_NAME, COL_THUMBNAIL, CURSOR_SIZE_KEY, CURSOR_THEME_KEY, CUSTOM_THEME_NAME, data, DESKTOP_FONT_KEY, DOCUMENT_FONT_KEY, FALSE, GTK_FONT_KEY, MARCO_THEME_KEY, mate_theme_info_register_theme_change(), mate_theme_init(), mate_theme_meta_info_find_all(), MONOSPACE_FONT_KEY, MORE_THEMES_URL_KEY, _MateThemeMetaInfo::name, NULL, NUM_COLS, _MateThemeMetaInfo::readable_name, WINDOW_TITLE_FONT_KEY, and WP_FILE_KEY.
Referenced by main().
themes_shutdown()
void themes_shutdown (AppearanceData * data)
Definition at line 1135 of file appearance-themes.c.
References data, and mate_theme_meta_info_free().