MATE Desktop Environment: util.c File Reference
util.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <time.h>
#include <sys/stat.h>
#include <errno.h>
#include <unistd.h>
#include "common.h"
#include "private.h"
Macros
#define NMSGS (sizeof(messages) / sizeof(char *))
Functions
int mdvi_set_logfile (const char *filename)
int mdvi_set_logstream (FILE *file)
int mdvi_set_loglevel (int level)
void __debug (int mask, const char *format,...)
void mdvi_message (const char *format,...)
void mdvi_crash (const char *format,...)
void mdvi_error (const char *format,...)
void mdvi_warning (const char *format,...)
void mdvi_fatal (const char *format,...)
void * mdvi_malloc (size_t nelems)
void * mdvi_realloc (void *data, size_t newsize)
void * mdvi_calloc (size_t nmemb, size_t size)
void mdvi_free (void *ptr)
char * mdvi_strdup (const char *string)
char * mdvi_strncpy (char *to, const char *from, size_t length)
char * mdvi_strndup (const char *string, size_t length)
void * mdvi_memdup (const void *data, size_t length)
char * mdvi_strrstr (const char *haystack, const char *needle)
char * mdvi_build_path_from_cwd (const char *path)
double unit2pix_factor (const char *spec)
int unit2pix (int dpi, const char *spec)
Ulong get_mtime (int fd)
char * xstradd (char *dest, size_t *size, size_t n, const char *src, size_t m)
char * getword (char *string, const char *delim, char **end)
char * getstring (char *string, const char *delim, char **end)
void dstring_init (Dstring *dstr)
int dstring_append (Dstring *dstr, const char *string, int len)
int dstring_copy (Dstring *dstr, int pos, const char *string, int len)
int dstring_insert (Dstring *dstr, int pos, const char *string, int len)
int dstring_new (Dstring *dstr, const char *string, int len)
void dstring_reset (Dstring *dstr)
Variables
Uint32 _mdvi_debug_mask = 0
Macro Definition Documentation
NMSGS
#define NMSGS (sizeof(messages) / sizeof(char *))
Definition at line 44 of file atril/backend/dvi/mdvi-lib/util.c.
Referenced by mdvi_crash().
Function Documentation
__debug()
void __debug (int mask, const char * format, ...)
Definition at line 98 of file atril/backend/dvi/mdvi-lib/util.c.
References _mdvi_debug_mask, DEBUGGING, LOG_DEBUG, and mask.
Referenced by __PROTO().
dstring_append()
int dstring_append (Dstring * dstr, const char * string, int len)
Definition at line 474 of file atril/backend/dvi/mdvi-lib/util.c.
References ASSERT, Dstring::data, Dstring::length, mdvi_malloc(), mdvi_realloc(), memcpy, NULL, and Dstring::size.
Referenced by __PROTO(), dgets(), dstring_copy(), and dstring_insert().
dstring_copy()
int dstring_copy (Dstring * dstr, int pos, const char * string, int len)
Definition at line 496 of file atril/backend/dvi/mdvi-lib/util.c.
References ASSERT, Dstring::data, dstring_append(), Dstring::length, and memcpy.
Referenced by __PROTO().
dstring_init()
void dstring_init (Dstring * dstr)
Definition at line 467 of file atril/backend/dvi/mdvi-lib/util.c.
References Dstring::data, Dstring::length, NULL, and Dstring::size.
Referenced by __PROTO(), dstring_new(), dstring_reset(), mdvi_load_fontmap(), and mdvi_ps_read_fontmap().
dstring_insert()
int dstring_insert (Dstring * dstr, int pos, const char * string, int len)
Definition at line 511 of file atril/backend/dvi/mdvi-lib/util.c.
References ASSERT, Dstring::data, dstring_append(), Dstring::length, mdvi_realloc(), memcpy, memmove, and Dstring::size.
Referenced by __PROTO().
dstring_new()
int dstring_new (Dstring * dstr, const char * string, int len)
Definition at line 533 of file atril/backend/dvi/mdvi-lib/util.c.
References Dstring::data, dstring_init(), Dstring::length, mdvi_malloc(), memcpy, and Dstring::size.
Referenced by __PROTO().
dstring_reset()
void dstring_reset (Dstring * dstr)
Definition at line 546 of file atril/backend/dvi/mdvi-lib/util.c.
References Dstring::data, dstring_init(), and mdvi_free().
Referenced by __PROTO(), mdvi_load_fontmap(), and mdvi_ps_read_fontmap().
get_mtime()
Ulong get_mtime (int fd)
Definition at line 398 of file atril/backend/dvi/mdvi-lib/util.c.
Referenced by __PROTO(), mate_bg_set_filename(), mdvi_dopage(), and mdvi_init_context().
getstring()
char * getstring (char * string, const char * delim, char ** end)
Definition at line 438 of file atril/backend/dvi/mdvi-lib/util.c.
References NULL, ptr, and strchr.
Referenced by __PROTO(), and mdvi_load_fontmap().
getword()
char * getword (char * string, const char * delim, char ** end)
Definition at line 420 of file atril/backend/dvi/mdvi-lib/util.c.
References NULL, ptr, and strchr.
Referenced by __PROTO(), mdvi_load_fontmap(), and mdvi_ps_read_fontmap().
mdvi_build_path_from_cwd()
char * mdvi_build_path_from_cwd (const char * path)
Definition at line 325 of file atril/backend/dvi/mdvi-lib/util.c.
References mdvi_realloc(), NULL, and ptr.
Referenced by __PROTO(), and epsf_special().
mdvi_calloc()
void * mdvi_calloc (size_t nmemb, size_t size)
Definition at line 231 of file atril/backend/dvi/mdvi-lib/util.c.
References _, mdvi_crash(), mdvi_fatal(), and ptr.
Referenced by __PROTO(), bitmap_alloc(), bitmap_flip_diagonally(), bitmap_flip_horizontally(), bitmap_flip_rotate_clockwise(), bitmap_flip_rotate_counter_clockwise(), bitmap_flip_vertically(), bitmap_rotate_clockwise(), and bitmap_rotate_counter_clockwise().
mdvi_crash()
void mdvi_crash (const char * format, ...)
Definition at line 137 of file atril/backend/dvi/mdvi-lib/util.c.
References _, LOG_ERROR, NMSGS, NULL, and program_name.
Referenced by __PROTO(), mdvi_calloc(), mdvi_free(), and mdvi_realloc().
mdvi_error()
void mdvi_error (const char * format, ...)
Definition at line 156 of file atril/backend/dvi/mdvi-lib/util.c.
References _, LOG_ERROR, and program_name.
Referenced by __PROTO(), mdvi_dopage(), mdvi_init_context(), mdvi_parse_page_spec(), and tfm_load_file().
mdvi_fatal()
void mdvi_fatal (const char * format, ...)
Definition at line 188 of file atril/backend/dvi/mdvi-lib/util.c.
References _, LOG_ERROR, and program_name.
Referenced by __PROTO(), mdvi_calloc(), mdvi_malloc(), and mdvi_realloc().
mdvi_free()
void mdvi_free (void * ptr)
Definition at line 247 of file atril/backend/dvi/mdvi-lib/util.c.
References _, mdvi_crash(), NULL, and ptr.
Referenced by __PROTO(), bitmap_flip_diagonally(), bitmap_flip_horizontally(), bitmap_flip_rotate_clockwise(), bitmap_flip_rotate_counter_clockwise(), bitmap_flip_vertically(), bitmap_rotate_clockwise(), bitmap_rotate_counter_clockwise(), buff_free(), dstring_reset(), epsf_special(), flush_font_metrics(), font_drop_one(), font_free_unused(), free_font_metrics(), get_color_table(), get_font_metrics(), mdvi_add_font(), mdvi_add_fontmap_file(), mdvi_destroy_context(), mdvi_dopage(), mdvi_flush_specials(), mdvi_font_retry(), mdvi_free_page_spec(), mdvi_free_paper_specs(), mdvi_hash_destroy_key(), mdvi_hash_remove(), mdvi_hash_remove_ptr(), mdvi_hash_reset(), mdvi_init_context(), mdvi_load_fontmap(), mdvi_parse_page_spec(), mdvi_parse_range(), mdvi_ps_flush_fonts(), mdvi_ps_get_metrics(), mdvi_ps_read_fontmap(), mdvi_register_special(), mdvi_reload(), mdvi_unregister_font_type(), mdvi_unregister_special(), read_string(), special(), and tfm_load_file().
mdvi_malloc()
void * mdvi_malloc (size_t nelems)
Definition at line 209 of file atril/backend/dvi/mdvi-lib/util.c.
References _, mdvi_fatal(), NULL, and ptr.
Referenced by __PROTO(), bitmap_alloc_raw(), buff_gets(), dstring_append(), dstring_new(), epsf_special(), mdvi_init_context(), mdvi_memdup(), mdvi_ps_get_metrics(), mdvi_strdup(), mdvi_strndup(), read_string(), special(), and tfm_load_file().
mdvi_memdup()
void * mdvi_memdup (const void * data, size_t length)
Definition at line 286 of file atril/backend/dvi/mdvi-lib/util.c.
References data, mdvi_malloc(), memcpy, and ptr.
Referenced by __PROTO().
mdvi_message()
void mdvi_message (const char * format, ...)
Definition at line 120 of file atril/backend/dvi/mdvi-lib/util.c.
References LOG_INFO, NULL, and program_name.
Referenced by __PROTO().
mdvi_realloc()
void * mdvi_realloc (void * data, size_t newsize)
Definition at line 219 of file atril/backend/dvi/mdvi-lib/util.c.
References _, data, mdvi_crash(), mdvi_fatal(), NULL, and ptr.
Referenced by __PROTO(), buff_add(), dstring_append(), dstring_insert(), get_tfm_chars(), mdvi_build_path_from_cwd(), mdvi_parse_range(), mdvi_push_color(), and xstradd().
mdvi_set_logfile()
int mdvi_set_logfile (const char * filename)
Definition at line 62 of file atril/backend/dvi/mdvi-lib/util.c.
References NULL.
Referenced by __PROTO().
mdvi_set_loglevel()
int mdvi_set_loglevel (int level)
Definition at line 87 of file atril/backend/dvi/mdvi-lib/util.c.
References level.
Referenced by __PROTO().
mdvi_set_logstream()
int mdvi_set_logstream (FILE * file)
Definition at line 77 of file atril/backend/dvi/mdvi-lib/util.c.
References NULL.
Referenced by __PROTO().
mdvi_strdup()
char * mdvi_strdup (const char * string)
Definition at line 254 of file atril/backend/dvi/mdvi-lib/util.c.
References mdvi_malloc(), memcpy, and ptr.
Referenced by __PROTO(), get_font_metrics(), mdvi_add_font(), mdvi_add_fontmap_file(), mdvi_list_font_class(), mdvi_load_fontmap(), mdvi_parse_range(), mdvi_ps_find_font(), mdvi_ps_read_fontmap(), mdvi_register_font_type(), and mdvi_register_special().
mdvi_strncpy()
char * mdvi_strncpy (char * to, const char * from, size_t length)
Definition at line 266 of file atril/backend/dvi/mdvi-lib/util.c.
Referenced by __PROTO().
mdvi_strndup()
char * mdvi_strndup (const char * string, size_t length)
Definition at line 273 of file atril/backend/dvi/mdvi-lib/util.c.
References mdvi_malloc(), memcpy, and ptr.
Referenced by __PROTO().
mdvi_strrstr()
char * mdvi_strrstr (const char * haystack, const char * needle)
Definition at line 294 of file atril/backend/dvi/mdvi-lib/util.c.
References NULL.
Referenced by __PROTO(), and epsf_special().
mdvi_warning()
void mdvi_warning (const char * format, ...)
Definition at line 172 of file atril/backend/dvi/mdvi-lib/util.c.
References _, LOG_WARN, and program_name.
Referenced by __PROTO(), font_finish_definitions(), mdvi_dopage(), mdvi_flush_encodings(), mdvi_load_fontmap(), mdvi_lookup_font(), mdvi_parse_page_spec(), mdvi_reload(), sp_layer(), and tfm_load_file().
unit2pix()
int unit2pix (int dpi, const char * spec)
Definition at line 391 of file atril/backend/dvi/mdvi-lib/util.c.
References unit2pix_factor().
Referenced by __PROTO().
unit2pix_factor()
double unit2pix_factor (const char * spec)
Definition at line 348 of file atril/backend/dvi/mdvi-lib/util.c.
Referenced by __PROTO(), mdvi_get_paper_size(), and unit2pix().
xstradd()
char * xstradd (char * dest, size_t * size, size_t n, const char * src, size_t m)
Definition at line 407 of file atril/backend/dvi/mdvi-lib/util.c.
References dest, mdvi_realloc(), and memcpy.
Referenced by __PROTO().
Variable Documentation
_mdvi_debug_mask
Uint32 _mdvi_debug_mask = 0
Definition at line 96 of file atril/backend/dvi/mdvi-lib/util.c.
Referenced by __debug().