MATE Desktop Environment: list.c File Reference
list.c File Reference
#include <config.h>
#include "common.h"
Functions
void listh_init (ListHead *head)
void listh_prepend (ListHead *head, List *list)
void listh_append (ListHead *head, List *list)
void listh_add_before (ListHead *head, List *at, List *list)
void listh_add_after (ListHead *head, List *at, List *list)
void listh_remove (ListHead *head, List *list)
void listh_concat (ListHead *h1, ListHead *h2)
void listh_catcon (ListHead *h1, ListHead *h2)
Function Documentation
listh_add_after()
void listh_add_after (ListHead * head, List * at, List * list)
Definition at line 64 of file atril/backend/dvi/mdvi-lib/list.c.
References ListHead::count, listh_append(), _List::next, _List::prev, and ListHead::tail.
Referenced by __PROTO().
listh_add_before()
void listh_add_before (ListHead * head, List * at, List * list)
Definition at line 52 of file atril/backend/dvi/mdvi-lib/list.c.
References ListHead::count, ListHead::head, listh_prepend(), _List::next, NULL, and _List::prev.
Referenced by __PROTO().
listh_append()
void listh_append (ListHead * head, List * list)
Definition at line 40 of file atril/backend/dvi/mdvi-lib/list.c.
References ListHead::count, ListHead::head, _List::next, NULL, _List::prev, and ListHead::tail.
Referenced by __PROTO(), font_drop_one(), font_reference(), listh_add_after(), mdvi_install_fontmap(), mdvi_load_fontmap(), mdvi_ps_read_fontmap(), and mdvi_register_font_type().
listh_catcon()
void listh_catcon (ListHead * h1, ListHead * h2)
Definition at line 108 of file atril/backend/dvi/mdvi-lib/list.c.
References ListHead::count, ListHead::head, _List::next, NULL, _List::prev, and ListHead::tail.
Referenced by __PROTO().
listh_concat()
void listh_concat (ListHead * h1, ListHead * h2)
Definition at line 94 of file atril/backend/dvi/mdvi-lib/list.c.
References ListHead::count, ListHead::head, _List::next, NULL, _List::prev, and ListHead::tail.
Referenced by __PROTO().
listh_init()
void listh_init (ListHead * head)
Definition at line 22 of file atril/backend/dvi/mdvi-lib/list.c.
References ListHead::count, ListHead::head, NULL, and ListHead::tail.
Referenced by __PROTO(), mdvi_load_fontmap(), mdvi_ps_flush_fonts(), and ps_init_default_paths().
listh_prepend()
void listh_prepend (ListHead * head, List * list)
Definition at line 28 of file atril/backend/dvi/mdvi-lib/list.c.
References ListHead::count, ListHead::head, _List::next, NULL, _List::prev, and ListHead::tail.
Referenced by __PROTO(), font_reference(), get_font_metrics(), listh_add_before(), and mdvi_register_special().
listh_remove()
void listh_remove (ListHead * head, List * list)
Definition at line 76 of file atril/backend/dvi/mdvi-lib/list.c.
References ListHead::count, ListHead::head, _List::next, NULL, _List::prev, and ListHead::tail.
Referenced by __PROTO(), font_drop_one(), font_free_unused(), font_reference(), free_font_metrics(), mdvi_install_fontmap(), mdvi_unregister_font_type(), and mdvi_unregister_special().