MATE Desktop Environment: egg-editable-toolbar.c File Reference
egg-editable-toolbar.c File Reference
#include "config.h"
#include "egg-editable-toolbar.h"
#include "egg-toolbars-model.h"
#include "egg-toolbar-editor.h"
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <string.h>
Macros
#define MIN_TOOLBAR_HEIGHT 20
#define EGG_ITEM_NAME "egg-item-name"
#define STOCK_DRAG_MODE "stock_drag-mode"
#define DEFAULT_ICON_HEIGHT 20
Enumerations
enum {
PROP_0 , PROP_TOOLBARS_MODEL , PROP_UI_MANAGER , PROP_POPUP_PATH ,
PROP_SELECTED , PROP_EDIT_MODE
}
enum { ACTION_REQUEST , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (EggEditableToolbar, egg_editable_toolbar, GTK_TYPE_BOX)
void egg_editable_toolbar_set_model (EggEditableToolbar *etoolbar, EggToolbarsModel *model)
GtkWidget * egg_editable_toolbar_get_selected (EggEditableToolbar *etoolbar)
void egg_editable_toolbar_set_selected (EggEditableToolbar *etoolbar, GtkWidget *widget)
GtkWidget * egg_editable_toolbar_new (GtkUIManager *manager, const char *popup_path)
GtkWidget * egg_editable_toolbar_new_with_model (GtkUIManager *manager, EggToolbarsModel *model, const char *popup_path)
gboolean egg_editable_toolbar_get_edit_mode (EggEditableToolbar *etoolbar)
void egg_editable_toolbar_set_edit_mode (EggEditableToolbar *etoolbar, gboolean mode)
void egg_editable_toolbar_add_visibility (EggEditableToolbar *etoolbar, const char *path)
void egg_editable_toolbar_show (EggEditableToolbar *etoolbar, const char *name)
void egg_editable_toolbar_hide (EggEditableToolbar *etoolbar, const char *name)
void egg_editable_toolbar_set_fixed (EggEditableToolbar *etoolbar, GtkToolbar *toolbar)
GtkWidget * _egg_editable_toolbar_new_separator_image (void)
EggToolbarsModel * egg_editable_toolbar_get_model (EggEditableToolbar *etoolbar)
GtkUIManager * egg_editable_toolbar_get_manager (EggEditableToolbar *etoolbar)
void egg_editable_toolbar_set_primary_class (EggEditableToolbar *etoolbar, gboolean set, const gchar *name)
Macro Definition Documentation
DEFAULT_ICON_HEIGHT
#define DEFAULT_ICON_HEIGHT 20
Definition at line 1806 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
EGG_ITEM_NAME
#define EGG_ITEM_NAME "egg-item-name"
Definition at line 35 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
MIN_TOOLBAR_HEIGHT
#define MIN_TOOLBAR_HEIGHT 20
Definition at line 34 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
STOCK_DRAG_MODE
#define STOCK_DRAG_MODE "stock_drag-mode"
Definition at line 36 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_TOOLBARS_MODEL
PROP_UI_MANAGER
PROP_POPUP_PATH
PROP_SELECTED
PROP_EDIT_MODE
Definition at line 42 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
anonymous enum
anonymous enum
Enumerator
ACTION_REQUEST
LAST_SIGNAL
Definition at line 52 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
Function Documentation
_egg_editable_toolbar_new_separator_image()
GtkWidget * _egg_editable_toolbar_new_separator_image (void)
Definition at line 1872 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
egg_editable_toolbar_add_visibility()
void egg_editable_toolbar_add_visibility (EggEditableToolbar * etoolbar, const char * path)
Definition at line 1732 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References _EggEditableToolbar::priv.
egg_editable_toolbar_get_edit_mode()
gboolean egg_editable_toolbar_get_edit_mode (EggEditableToolbar * etoolbar)
Definition at line 1716 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References _EggEditableToolbar::priv.
egg_editable_toolbar_get_manager()
GtkUIManager * egg_editable_toolbar_get_manager (EggEditableToolbar * etoolbar)
egg_editable_toolbar_get_manager:
Return value: (transfer none):
Definition at line 1900 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References _EggEditableToolbar::priv.
egg_editable_toolbar_get_model()
EggToolbarsModel * egg_editable_toolbar_get_model (EggEditableToolbar * etoolbar)
egg_editable_toolbar_get_model: @etoolbar:
Returns: (transfer none):
Definition at line 1889 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References _EggEditableToolbar::priv.
egg_editable_toolbar_get_selected()
GtkWidget * egg_editable_toolbar_get_selected (EggEditableToolbar * etoolbar)
egg_editable_toolbar_get_selected: @etoolbar:
Returns: (transfer none):
Definition at line 1497 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References _EggEditableToolbar::priv.
egg_editable_toolbar_hide()
void egg_editable_toolbar_hide (EggEditableToolbar * etoolbar, const char * name)
Definition at line 1761 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References egg_toolbars_model_n_toolbars(), egg_toolbars_model_toolbar_nth(), name, and _EggEditableToolbar::priv.
egg_editable_toolbar_new()
GtkWidget * egg_editable_toolbar_new (GtkUIManager * manager, const char * popup_path)
Definition at line 1694 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References EGG_TYPE_EDITABLE_TOOLBAR, and NULL.
egg_editable_toolbar_new_with_model()
GtkWidget * egg_editable_toolbar_new_with_model (GtkUIManager * manager, EggToolbarsModel * model, const char * popup_path)
Definition at line 1704 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References EGG_TYPE_EDITABLE_TOOLBAR, and NULL.
egg_editable_toolbar_set_edit_mode()
void egg_editable_toolbar_set_edit_mode (EggEditableToolbar * etoolbar, gboolean mode)
Definition at line 1724 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
egg_editable_toolbar_set_fixed()
void egg_editable_toolbar_set_fixed (EggEditableToolbar * etoolbar, GtkToolbar * toolbar)
Definition at line 1782 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References FALSE, NULL, and _EggEditableToolbar::priv.
egg_editable_toolbar_set_model()
void egg_editable_toolbar_set_model (EggEditableToolbar * etoolbar, EggToolbarsModel * model)
Definition at line 1369 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References _EggEditableToolbar::priv.
egg_editable_toolbar_set_primary_class()
void egg_editable_toolbar_set_primary_class (EggEditableToolbar * etoolbar, gboolean set, const gchar * name)
Definition at line 1906 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References name, _EggEditableToolbar::priv, and set.
egg_editable_toolbar_set_selected()
void egg_editable_toolbar_set_selected (EggEditableToolbar * etoolbar, GtkWidget * widget)
Definition at line 1503 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References EGG_TB_MODEL_NOT_EDITABLE, egg_toolbars_model_get_flags(), FALSE, NULL, and _EggEditableToolbar::priv.
egg_editable_toolbar_show()
void egg_editable_toolbar_show (EggEditableToolbar * etoolbar, const char * name)
Definition at line 1740 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References egg_toolbars_model_n_toolbars(), egg_toolbars_model_toolbar_nth(), name, and _EggEditableToolbar::priv.
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (EggEditableToolbar , egg_editable_toolbar , GTK_TYPE_BOX)