MATE Desktop Environment: main.c File Reference
main.c File Reference
#include "config.h"
#include <stdlib.h>
#include <string.h>
#include <glib/gstdio.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include "ev-application.h"
#include "ev-debug.h"
#include "ev-init.h"
#include "ev-file-helpers.h"
#include "ev-stock-icons.h"
#include "ev-metadata.h"
#include "eggsmclient.h"
#include "eggdesktopfile.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 218 of file atril/shell/main.c.
References egg_set_desktop_file(), egg_sm_client_get_option_group(), error, ev_application_load_session(), ev_application_new(), ev_get_locale_dir(), ev_init(), ev_shutdown(), ev_stock_icons_init(), GETTEXT_PACKAGE, N_, NULL, and TRUE.