MATE Desktop Environment: backend.c File Reference
backend.c File Reference
#include <sys/socket.h>
#include <sys/types.h>
#include <ifaddrs.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <glibtop/netlist.h>
#include <glibtop/netload.h>
#include "backend.h"
Functions
gboolean is_dummy_device (const char *device)
GList * get_available_devices (void)
GSList * get_ip_address_list (const char *iface_name, gboolean ipv4)
GSList * get_ip6_address_list (const char *iface_name)
const gchar * get_default_route (void)
void free_device_info (DevInfo *devinfo)
void get_device_info (const char *device, DevInfo **info)
gboolean compare_device_info (const DevInfo *a, const DevInfo *b)
Function Documentation
compare_device_info()
gboolean compare_device_info (const DevInfo * a, const DevInfo * b)
Definition at line 399 of file backend.c.
References b, FALSE, DevInfo::ip, DevInfo::name, DevInfo::running, TRUE, and DevInfo::up.
free_device_info()
void free_device_info (DevInfo * devinfo)
Definition at line 284 of file backend.c.
References DevInfo::essid, and DevInfo::name.
get_available_devices()
GList * get_available_devices (void)
Definition at line 96 of file backend.c.
References devices, and NULL.
get_default_route()
const gchar * get_default_route (void)
Definition at line 246 of file backend.c.
References is_dummy_device(), mask, and NULL.
get_device_info()
void get_device_info (const char * device, DevInfo ** info)
Definition at line 320 of file backend.c.
References DEV_ETHERNET, DEV_LO, DEV_PLIP, DEV_PPP, DEV_SLIP, DEV_UNKNOWN, DEV_WIRELESS, FALSE, get_wireless_info(), DevInfo::hwaddr, DevInfo::ip, memcpy, DevInfo::name, DevInfo::netmask, DevInfo::running, DevInfo::rx, TRUE, DevInfo::tx, DevInfo::type, and DevInfo::up.
get_ip6_address_list()
GSList * get_ip6_address_list (const char * iface_name)
Definition at line 211 of file backend.c.
References memcpy, and NULL.
get_ip_address_list()
GSList * get_ip_address_list (const char * iface_name, gboolean ipv4)
Definition at line 115 of file backend.c.
References _, memcpy, and NULL.
is_dummy_device()
gboolean is_dummy_device (const char * device)
Definition at line 68 of file backend.c.
References FALSE, and TRUE.
Referenced by get_default_route().