MATE Desktop Environment: bacon-video-widget-properties.h File Reference
bacon-video-widget-properties.h File Reference
#include <gtk/gtk.h>
Classes
struct BaconVideoWidgetProperties
struct BaconVideoWidgetPropertiesClass
Macros
#define BACON_TYPE_VIDEO_WIDGET_PROPERTIES (bacon_video_widget_properties_get_type ())
#define BACON_VIDEO_WIDGET_PROPERTIES(obj)
#define BACON_VIDEO_WIDGET_PROPERTIES_CLASS(klass)
#define BACON_IS_VIDEO_WIDGET_PROPERTIES(obj)
#define BACON_IS_VIDEO_WIDGET_PROPERTIES_CLASS(klass)
Typedefs
typedef struct BaconVideoWidgetProperties BaconVideoWidgetProperties
typedef struct BaconVideoWidgetPropertiesClass BaconVideoWidgetPropertiesClass
typedef struct BaconVideoWidgetPropertiesPrivate BaconVideoWidgetPropertiesPrivate
Functions
GType bacon_video_widget_properties_get_type (void)
GtkWidget * bacon_video_widget_properties_new (void)
void bacon_video_widget_properties_reset (BaconVideoWidgetProperties *props)
void bacon_video_widget_properties_set_label (BaconVideoWidgetProperties *props, const char *name, const char *text)
void bacon_video_widget_properties_set_duration (BaconVideoWidgetProperties *props, int duration)
void bacon_video_widget_properties_set_has_type (BaconVideoWidgetProperties *props, gboolean has_video, gboolean has_audio)
void bacon_video_widget_properties_set_framerate (BaconVideoWidgetProperties *props, float framerate)
Macro Definition Documentation
BACON_IS_VIDEO_WIDGET_PROPERTIES
#define BACON_IS_VIDEO_WIDGET_PROPERTIES (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), BACON_TYPE_VIDEO_WIDGET_PROPERTIES))
Definition at line 31 of file bacon-video-widget-properties.h.
Referenced by bacon_video_widget_properties_reset(), bacon_video_widget_properties_set_duration(), bacon_video_widget_properties_set_framerate(), bacon_video_widget_properties_set_has_type(), and bacon_video_widget_properties_set_label().
BACON_IS_VIDEO_WIDGET_PROPERTIES_CLASS
#define BACON_IS_VIDEO_WIDGET_PROPERTIES_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), BACON_TYPE_VIDEO_WIDGET_PROPERTIES))
Definition at line 32 of file bacon-video-widget-properties.h.
BACON_TYPE_VIDEO_WIDGET_PROPERTIES
#define BACON_TYPE_VIDEO_WIDGET_PROPERTIES (bacon_video_widget_properties_get_type ())
Definition at line 28 of file bacon-video-widget-properties.h.
Referenced by bacon_video_widget_properties_new().
BACON_VIDEO_WIDGET_PROPERTIES
#define BACON_VIDEO_WIDGET_PROPERTIES (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), BACON_TYPE_VIDEO_WIDGET_PROPERTIES, BaconVideoWidgetProperties))
Definition at line 29 of file bacon-video-widget-properties.h.
Referenced by bacon_video_widget_properties_new().
BACON_VIDEO_WIDGET_PROPERTIES_CLASS
#define BACON_VIDEO_WIDGET_PROPERTIES_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), BACON_TYPE_VIDEO_WIDGET_PROPERTIES, BaconVideoWidgetPropertiesClass))
Definition at line 30 of file bacon-video-widget-properties.h.
Typedef Documentation
BaconVideoWidgetProperties
typedef struct BaconVideoWidgetProperties BaconVideoWidgetProperties
Definition at line 34 of file bacon-video-widget-properties.h.
BaconVideoWidgetPropertiesClass
typedef struct BaconVideoWidgetPropertiesClass BaconVideoWidgetPropertiesClass
Definition at line 35 of file bacon-video-widget-properties.h.
BaconVideoWidgetPropertiesPrivate
typedef struct BaconVideoWidgetPropertiesPrivate BaconVideoWidgetPropertiesPrivate
Definition at line 36 of file bacon-video-widget-properties.h.
Function Documentation
bacon_video_widget_properties_get_type()
GType bacon_video_widget_properties_get_type (void)
References name.
bacon_video_widget_properties_new()
GtkWidget * bacon_video_widget_properties_new (void)
Definition at line 242 of file bacon-video-widget-properties.c.
References BACON_TYPE_VIDEO_WIDGET_PROPERTIES, BACON_VIDEO_WIDGET_PROPERTIES, bacon_video_widget_properties_reset(), FALSE, GETTEXT_PACKAGE, NULL, and BaconVideoWidgetProperties::priv.
bacon_video_widget_properties_reset()
void bacon_video_widget_properties_reset (BaconVideoWidgetProperties * props)
Definition at line 89 of file bacon-video-widget-properties.c.
References _, BACON_IS_VIDEO_WIDGET_PROPERTIES, bacon_video_widget_properties_set_duration(), bacon_video_widget_properties_set_label(), C_, FALSE, item, NULL, and BaconVideoWidgetProperties::priv.
Referenced by bacon_video_widget_properties_new().
bacon_video_widget_properties_set_duration()
void bacon_video_widget_properties_set_duration (BaconVideoWidgetProperties * props, int duration)
Definition at line 184 of file bacon-video-widget-properties.c.
References BACON_IS_VIDEO_WIDGET_PROPERTIES, bacon_video_widget_properties_set_label(), NULL, and BaconVideoWidgetProperties::priv.
Referenced by bacon_video_widget_properties_reset().
bacon_video_widget_properties_set_framerate()
void bacon_video_widget_properties_set_framerate (BaconVideoWidgetProperties * props, float framerate)
Definition at line 224 of file bacon-video-widget-properties.c.
References BACON_IS_VIDEO_WIDGET_PROPERTIES, bacon_video_widget_properties_set_label(), C_, GETTEXT_PACKAGE, and NULL.
bacon_video_widget_properties_set_has_type()
void bacon_video_widget_properties_set_has_type (BaconVideoWidgetProperties * props, gboolean has_video, gboolean has_audio)
Definition at line 203 of file bacon-video-widget-properties.c.
References BACON_IS_VIDEO_WIDGET_PROPERTIES, item, NULL, and BaconVideoWidgetProperties::priv.
bacon_video_widget_properties_set_label()
void bacon_video_widget_properties_set_label (BaconVideoWidgetProperties * props, const char * name, const char * text)
Definition at line 73 of file bacon-video-widget-properties.c.
References BACON_IS_VIDEO_WIDGET_PROPERTIES, item, name, NULL, and BaconVideoWidgetProperties::priv.
Referenced by bacon_video_widget_properties_reset(), bacon_video_widget_properties_set_duration(), and bacon_video_widget_properties_set_framerate().