MATE Desktop Environment: bacon-message-connection.c File Reference
bacon-message-connection.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <errno.h>
#include "bacon-message-connection.h"
Macros
#define UNIX_PATH_MAX 108
Functions
BaconMessageConnection * bacon_message_connection_new (const char *prefix)
void bacon_message_connection_free (BaconMessageConnection *conn)
void bacon_message_connection_set_callback (BaconMessageConnection *conn, BaconMessageReceivedFunc func, gpointer user_data)
void bacon_message_connection_send (BaconMessageConnection *conn, const char *message)
gboolean bacon_message_connection_get_is_server (BaconMessageConnection *conn)
Macro Definition Documentation
UNIX_PATH_MAX
#define UNIX_PATH_MAX 108
Definition at line 35 of file bacon-message-connection.c.
Function Documentation
bacon_message_connection_free()
void bacon_message_connection_free (BaconMessageConnection * conn)
Definition at line 330 of file bacon-message-connection.c.
References bacon_message_connection_free(), FALSE, and NULL.
Referenced by bacon_message_connection_free(), bacon_message_connection_new(), and main().
bacon_message_connection_get_is_server()
gboolean bacon_message_connection_get_is_server (BaconMessageConnection * conn)
Definition at line 391 of file bacon-message-connection.c.
References FALSE, and NULL.
Referenced by main().
bacon_message_connection_new()
BaconMessageConnection * bacon_message_connection_new (const char * prefix)
Definition at line 290 of file bacon-message-connection.c.
References bacon_message_connection_free(), FALSE, NULL, prefix, and TRUE.
Referenced by main().
bacon_message_connection_send()
void bacon_message_connection_send (BaconMessageConnection * conn, const char * message)
Definition at line 378 of file bacon-message-connection.c.
References message(), and NULL.
bacon_message_connection_set_callback()
void bacon_message_connection_set_callback (BaconMessageConnection * conn, BaconMessageReceivedFunc func, gpointer user_data)
Definition at line 367 of file bacon-message-connection.c.
References NULL, and user_data.
Referenced by main().