MATE Desktop Environment: baobab-chart.c File Reference
baobab-chart.c File Reference
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <math.h>
#include "baobab-chart.h"
Macros
#define SNAPSHOT_DEF_FILENAME_FORMAT "%s-disk-usage"
#define BAOBAB_CHART_MAX_DEPTH 8
#define BAOBAB_CHART_MIN_DEPTH 1
Enumerations
enum { LEFT_BUTTON = 1 , MIDDLE_BUTTON = 2 , RIGHT_BUTTON = 3 }
enum { ITEM_ACTIVATED , LAST_SIGNAL }
enum { PROP_0 , PROP_MAX_DEPTH , PROP_MODEL , PROP_ROOT }
Functions
G_DEFINE_ABSTRACT_TYPE_WITH_PRIVATE (BaobabChart, baobab_chart, GTK_TYPE_WIDGET)
void baobab_chart_get_item_color (BaobabChartColor *color, gdouble rel_position, guint depth, gboolean highlighted)
GtkWidget * baobab_chart_new ()
void baobab_chart_set_model_with_columns (GtkWidget *chart, GtkTreeModel *model, guint name_column, guint size_column, guint info_column, guint percentage_column, guint valid_column, GtkTreePath *root)
void baobab_chart_set_model (GtkWidget *chart, GtkTreeModel *model)
GtkTreeModel * baobab_chart_get_model (GtkWidget *chart)
void baobab_chart_set_max_depth (GtkWidget *chart, guint max_depth)
guint baobab_chart_get_max_depth (GtkWidget *chart)
void baobab_chart_set_root (GtkWidget *chart, GtkTreePath *root)
GtkTreePath * baobab_chart_get_root (GtkWidget *chart)
void baobab_chart_freeze_updates (GtkWidget *chart)
void baobab_chart_thaw_updates (GtkWidget *chart)
void baobab_chart_zoom_in (GtkWidget *chart)
void baobab_chart_zoom_out (GtkWidget *chart)
void baobab_chart_move_up_root (GtkWidget *chart)
void baobab_chart_save_snapshot (GtkWidget *chart)
gboolean baobab_chart_is_frozen (GtkWidget *chart)
BaobabChartItem * baobab_chart_get_highlighted_item (GtkWidget *chart)
gboolean baobab_chart_can_zoom_in (GtkWidget *chart)
gboolean baobab_chart_can_zoom_out (GtkWidget *chart)
Variables
const BaobabChartColor baobab_chart_tango_colors []
Macro Definition Documentation
BAOBAB_CHART_MAX_DEPTH
#define BAOBAB_CHART_MAX_DEPTH 8
Definition at line 46 of file baobab-chart.c.
Referenced by baobab_chart_can_zoom_out(), baobab_chart_get_item_color(), and baobab_chart_set_max_depth().
BAOBAB_CHART_MIN_DEPTH
#define BAOBAB_CHART_MIN_DEPTH 1
Definition at line 47 of file baobab-chart.c.
Referenced by baobab_chart_set_max_depth().
SNAPSHOT_DEF_FILENAME_FORMAT
#define SNAPSHOT_DEF_FILENAME_FORMAT "%s-disk-usage"
Definition at line 44 of file baobab-chart.c.
Referenced by baobab_chart_save_snapshot().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_MAX_DEPTH
PROP_MODEL
PROP_ROOT
Definition at line 90 of file baobab-chart.c.
anonymous enum
anonymous enum
Enumerator
ITEM_ACTIVATED
LAST_SIGNAL
Definition at line 79 of file baobab-chart.c.
anonymous enum
anonymous enum
Enumerator
LEFT_BUTTON
MIDDLE_BUTTON
RIGHT_BUTTON
Definition at line 49 of file baobab-chart.c.
Function Documentation
baobab_chart_can_zoom_in()
gboolean baobab_chart_can_zoom_in (GtkWidget * chart)
baobab_chart_can_zoom_in: @chart: the BaobabChart to ask if can be zoomed in.
Returns a boolean telling whether the chart can be zoomed in, given its current visualization conditions.
Fails if @chart is not a BaobabChart.
Definition at line 1832 of file baobab-chart.c.
References BAOBAB_CHART, BAOBAB_IS_CHART, FALSE, and NULL.
baobab_chart_can_zoom_out()
gboolean baobab_chart_can_zoom_out (GtkWidget * chart)
baobab_chart_can_zoom_out: @chart: the BaobabChart to ask if can be zoomed out.
Returns a boolean telling whether the chart can be zoomed out, given its current visualization conditions.
Fails if @chart is not a BaobabChart.
Definition at line 1858 of file baobab-chart.c.
References BAOBAB_CHART, BAOBAB_CHART_MAX_DEPTH, BAOBAB_IS_CHART, FALSE, and NULL.
baobab_chart_freeze_updates()
void baobab_chart_freeze_updates (GtkWidget * chart)
baobab_chart_freeze_updates: @chart: the BaobabChart whose model signals are going to be frozen.
Disconnects @chart from the signals emitted by its model, and sets the window of @chart to a "processing" state, so that the window ignores changes in the chart's model and mouse events. In order to connect again the window to the model, a call to baobab_chart_thaw_updates must be done.
Fails if @chart is not a BaobabChart.
Definition at line 1472 of file baobab-chart.c.
References BAOBAB_CHART, BAOBAB_IS_CHART, NULL, and TRUE.
Referenced by baobab_set_busy().
baobab_chart_get_highlighted_item()
BaobabChartItem * baobab_chart_get_highlighted_item (GtkWidget * chart)
baobab_chart_is_frozen: @chart: the BaobabChart to obtain the highlighted it from.
Returns a BaobabChartItem corresponding to the item that currently has mouse pointer over, or NULL if no item is highlighted.
Fails if @chart is not a BaobabChart.
Definition at line 1811 of file baobab-chart.c.
References BAOBAB_CHART, BAOBAB_IS_CHART, and NULL.
baobab_chart_get_item_color()
void baobab_chart_get_item_color (BaobabChartColor * color, gdouble rel_position, guint depth, gboolean highlighted)
Definition at line 870 of file baobab-chart.c.
References BAOBAB_CHART_MAX_DEPTH, baobab_chart_tango_colors, _BaobabChartColor::blue, _BaobabChartColor::green, int(), MAX, and _BaobabChartColor::red.
baobab_chart_get_max_depth()
guint baobab_chart_get_max_depth (GtkWidget * chart)
baobab_chart_get_max_depth: @chart: a BaobabChart.
Returns the maximum number of levels that will be show in the widget.
Fails if @chart is not a BaobabChart.
Definition at line 1388 of file baobab-chart.c.
References BAOBAB_CHART, and BAOBAB_IS_CHART.
Referenced by baobab_chart_zoom_out().
baobab_chart_get_model()
GtkTreeModel * baobab_chart_get_model (GtkWidget * chart)
baobab_chart_get_model: @chart: a BaobabChart whose model will be returned.
Returns the #GtkTreeModel which is the model used by @chart.
Returns: NULL if @chart is not a BaobabChart.
Definition at line 1336 of file baobab-chart.c.
References BAOBAB_CHART, BAOBAB_IS_CHART, and NULL.
baobab_chart_get_root()
GtkTreePath * baobab_chart_get_root (GtkWidget * chart)
baobab_chart_get_root: @chart: a BaobabChart.
Returns a #GtkTreePath pointing to the root of the widget. The programmer has the responsability to free the used memory once finished with the returned value. It returns NULL if there is no root node defined
Fails if @chart is not a BaobabChart.
Definition at line 1449 of file baobab-chart.c.
References BAOBAB_CHART, BAOBAB_IS_CHART, and NULL.
baobab_chart_is_frozen()
gboolean baobab_chart_is_frozen (GtkWidget * chart)
baobab_chart_is_frozen: @chart: the BaobabChart to ask if frozen.
Returns a boolean telling whether the chart is in a frozen state, meanning that no actions should be taken uppon it.
Fails if @chart is not a BaobabChart.
Definition at line 1791 of file baobab-chart.c.
References BAOBAB_CHART, BAOBAB_IS_CHART, and FALSE.
baobab_chart_move_up_root()
void baobab_chart_move_up_root (GtkWidget * chart)
baobab_chart_move_up_root: @chart: the BaobabChart whose root is requested to move up one level.
Move root to the inmediate parent of the current root item of @chart.
Fails if @chart is not a BaobabChart.
Definition at line 1619 of file baobab-chart.c.
References BAOBAB_CHART, BAOBAB_IS_CHART, ITEM_ACTIVATED, and NULL.
Referenced by on_move_upwards_cb().
baobab_chart_new()
GtkWidget * baobab_chart_new (void)
baobab_chart_new:
Constructor for the baobab_chart class
Returns: a new BaobabChart object
Definition at line 1200 of file baobab-chart.c.
References BAOBAB_CHART_TYPE, and NULL.
baobab_chart_save_snapshot()
void baobab_chart_save_snapshot (GtkWidget * chart)
baobab_chart_save_snapshot: @chart: the BaobabChart requested to be exported to image.
Opens a dialog to allow saving the current chart's image as a PNG, JPEG or BMP image.
Fails if @chart is not a BaobabChart.
Definition at line 1677 of file baobab-chart.c.
References _, BAOBAB_CHART, BAOBAB_IS_CHART, FALSE, item, label, NULL, SNAPSHOT_DEF_FILENAME_FORMAT, and TRUE.
Referenced by on_chart_snapshot_cb().
baobab_chart_set_max_depth()
void baobab_chart_set_max_depth (GtkWidget * chart, guint max_depth)
baobab_chart_set_max_depth: @chart: a BaobabChart @max_depth: the new maximum depth to show in the widget.
Sets the maximum number of nested levels that are going to be show in the wigdet, and causes a redraw of the widget to show the new maximum depth. If max_depth is < 1 MAX_DRAWABLE_DEPTH is used.
Fails if @chart is not a BaobabChart.
Definition at line 1355 of file baobab-chart.c.
References BAOBAB_CHART, BAOBAB_CHART_MAX_DEPTH, BAOBAB_CHART_MIN_DEPTH, BAOBAB_IS_CHART, MAX, MIN, and TRUE.
Referenced by baobab_chart_zoom_in(), baobab_chart_zoom_out(), and baobab_scan_location().
baobab_chart_set_model()
void baobab_chart_set_model (GtkWidget * chart, GtkTreeModel * model)
baobab_chart_set_model: @chart: the BaobabChart whose model is going to be set @model: the #GtkTreeModel which is going to set as the model of @chart
Sets @model as the #GtkTreeModel used by @chart, and takes the needed data from the columns especified in the last call to #baobab_chart_set_model_with_colums. This function does not change the state of the signals from the model, which is controlled by he baobab_chart_freeze_updates and the baobab_chart_thaw_updates functions.
Fails if @chart is not a BaobabChart or if @model is not a #GtkTreeModel.
Definition at line 1289 of file baobab-chart.c.
References BAOBAB_CHART, BAOBAB_IS_CHART, and NULL.
Referenced by baobab_chart_set_model_with_columns().
baobab_chart_set_model_with_columns()
void baobab_chart_set_model_with_columns (GtkWidget * chart, GtkTreeModel * model, guint name_column, guint size_column, guint info_column, guint percentage_column, guint valid_column, GtkTreePath * root)
baobab_chart_set_model_with_columns: @chart: the BaobabChart whose model is going to be set @model: the #GtkTreeModel which is going to set as the model of @chart @name_column: number of column inside @model where the file name is stored @size_column: number of column inside @model where the file size is stored @info_column: number of column inside @model where the percentage of disk usage is stored @percentage_column: number of column inside @model where the disk usage percentage is stored @valid_column: number of column inside @model where the flag indicating if the row data is right or not. @root: a #GtkTreePath indicating the node of @model which will be used as root.
Sets @model as the #GtkTreeModel used by @chart. Indicates the columns inside @model where the values file name, file size, file information, disk usage percentage and data correction are stored, and the node which will be used as the root of @chart. Once the model has been successfully set, a redraw of the window is forced. This function is intended to be used the first time a #GtkTreeModel is assigned to @chart, or when the columns containing the needed data are going to change. In other cases, baobab_chart_set_model should be used. This function does not change the state of the signals from the model, which is controlled by he baobab_chart_freeze_updates and the baobab_chart_thaw_updates functions.
Fails if @chart is not a BaobabChart or if @model is not a #GtkTreeModel.
Definition at line 1241 of file baobab-chart.c.
References BAOBAB_CHART, baobab_chart_set_model(), BAOBAB_IS_CHART, and NULL.
baobab_chart_set_root()
void baobab_chart_set_root (GtkWidget * chart, GtkTreePath * root)
baobab_chart_set_root: @chart: a BaobabChart @root: a #GtkTreePath indicating the node which will be used as the widget root.
Sets the node pointed by @root as the new root of the widget @chart.
Fails if @chart is not a BaobabChart or if @chart has not a #GtkTreeModel set.
Definition at line 1408 of file baobab-chart.c.
References BAOBAB_CHART, BAOBAB_IS_CHART, and NULL.
Referenced by on_tv_selection_changed().
baobab_chart_thaw_updates()
void baobab_chart_thaw_updates (GtkWidget * chart)
baobab_chart_thaw_updates: @chart: the BaobabChart whose model signals are frozen.
Reconnects @chart to the signals emitted by its model, which were disconnected through a call to baobab_chart_freeze_updates. Takes the window out of its "processing" state and forces a redraw of the widget.
Fails if @chart is not a BaobabChart.
Definition at line 1538 of file baobab-chart.c.
References BAOBAB_CHART, BAOBAB_IS_CHART, FALSE, NULL, and TRUE.
Referenced by baobab_set_busy().
baobab_chart_zoom_in()
void baobab_chart_zoom_in (GtkWidget * chart)
baobab_chart_zoom_in: @chart: the BaobabChart requested to zoom in.
Zooms in the chart by decreasing its maximun depth.
Fails if @chart is not a BaobabChart.
Definition at line 1574 of file baobab-chart.c.
References BAOBAB_CHART, baobab_chart_set_max_depth(), BAOBAB_IS_CHART, and NULL.
Referenced by on_zoom_in_cb().
baobab_chart_zoom_out()
void baobab_chart_zoom_out (GtkWidget * chart)
baobab_chart_zoom_out: @chart: the BaobabChart requested to zoom out.
Zooms out the chart by increasing its maximun depth.
Fails if @chart is not a BaobabChart.
Definition at line 1602 of file baobab-chart.c.
References baobab_chart_get_max_depth(), baobab_chart_set_max_depth(), and BAOBAB_IS_CHART.
Referenced by on_zoom_out_cb().
G_DEFINE_ABSTRACT_TYPE_WITH_PRIVATE()
G_DEFINE_ABSTRACT_TYPE_WITH_PRIVATE (BaobabChart , baobab_chart , GTK_TYPE_WIDGET)
References LAST_SIGNAL.
Variable Documentation
baobab_chart_tango_colors
const BaobabChartColor baobab_chart_tango_colors[]
Initial value:
= {{0.94, 0.16, 0.16},
     {0.68, 0.49, 0.66},
     {0.45, 0.62, 0.82},
     {0.54, 0.89, 0.20},
     {0.91, 0.73, 0.43},
     {0.99, 0.68, 0.25}}
Definition at line 99 of file baobab-chart.c.
Referenced by baobab_chart_get_item_color().