MATE Desktop Environment: baobab-treemap.c File Reference
baobab-treemap.c File Reference
#include <math.h>
#include <string.h>
#include <gtk/gtk.h>
#include "baobab-chart.h"
#include "baobab-treemap.h"
Macros
#define ITEM_TEXT_PADDING 3
#define ITEM_BORDER_WIDTH 1
#define ITEM_PADDING 6
#define ITEM_MIN_WIDTH 3
#define ITEM_MIN_HEIGHT 3
#define ITEM_SHOW_LABEL TRUE
Functions
G_DEFINE_TYPE_WITH_PRIVATE (BaobabTreemap, baobab_treemap, BAOBAB_CHART_TYPE)
guint baobab_treemap_can_zoom_in (GtkWidget *chart)
guint baobab_treemap_can_zoom_out (GtkWidget *chart)
GtkWidget * baobab_treemap_new (void)
Macro Definition Documentation
ITEM_BORDER_WIDTH
#define ITEM_BORDER_WIDTH 1
Definition at line 38 of file baobab-treemap.c.
ITEM_MIN_HEIGHT
#define ITEM_MIN_HEIGHT 3
Definition at line 42 of file baobab-treemap.c.
ITEM_MIN_WIDTH
#define ITEM_MIN_WIDTH 3
Definition at line 41 of file baobab-treemap.c.
ITEM_PADDING
#define ITEM_PADDING 6
Definition at line 39 of file baobab-treemap.c.
ITEM_SHOW_LABEL
#define ITEM_SHOW_LABEL TRUE
Definition at line 44 of file baobab-treemap.c.
ITEM_TEXT_PADDING
#define ITEM_TEXT_PADDING 3
Definition at line 37 of file baobab-treemap.c.
Function Documentation
baobab_treemap_can_zoom_in()
guint baobab_treemap_can_zoom_in (GtkWidget * chart)
Definition at line 301 of file baobab-treemap.c.
References BAOBAB_TREEMAP, and MAX.
Referenced by G_DEFINE_TYPE_WITH_PRIVATE().
baobab_treemap_can_zoom_out()
guint baobab_treemap_can_zoom_out (GtkWidget * chart)
Definition at line 311 of file baobab-treemap.c.
References BAOBAB_TREEMAP.
Referenced by G_DEFINE_TYPE_WITH_PRIVATE().
baobab_treemap_new()
GtkWidget * baobab_treemap_new (void)
baobab_treemap_new:
Constructor for the baobab_treemap class
Returns: a new BaobabTreemap object
Definition at line 331 of file baobab-treemap.c.
References BAOBAB_TREEMAP_TYPE, and NULL.
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (BaobabTreemap , baobab_treemap , BAOBAB_CHART_TYPE)
References BAOBAB_CHART_TYPE, baobab_treemap_can_zoom_in(), baobab_treemap_can_zoom_out(), and item.