MATE Desktop Environment: base-isession.h File Reference
base-isession.h File Reference
#include <gtk/gtk.h>
Classes
struct BaseISessionInterface
Macros
#define BASE_TYPE_ISESSION (base_isession_get_type())
#define BASE_ISESSION(instance)
#define BASE_IS_ISESSION(instance)
#define BASE_ISESSION_GET_INTERFACE(instance)
#define BASE_SIGNAL_QUIT_REQUESTED "base-signal-isession-quit-requested"
#define BASE_SIGNAL_QUIT "base-signal-isession-quit"
Typedefs
typedef struct _BaseISession BaseISession
typedef struct _BaseISessionInterfacePrivate BaseISessionInterfacePrivate
Functions
GType base_isession_get_type (void)
void base_isession_init (BaseISession *instance)
gboolean base_isession_is_willing_to_quit (const BaseISession *instance)
Macro Definition Documentation
BASE_IS_ISESSION
#define BASE_IS_ISESSION (instance)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE(instance, BASE_TYPE_ISESSION))
Definition at line 51 of file base-isession.h.
Referenced by base_application_is_willing_to_quit(), base_isession_init(), and base_isession_is_willing_to_quit().
BASE_ISESSION
#define BASE_ISESSION (instance)
Value:
(G_TYPE_CHECK_INSTANCE_CAST(instance, BASE_TYPE_ISESSION, BaseISession))
Definition at line 50 of file base-isession.h.
Referenced by base_application_is_willing_to_quit().
BASE_ISESSION_GET_INTERFACE
#define BASE_ISESSION_GET_INTERFACE (instance)
Value:
(G_TYPE_INSTANCE_GET_INTERFACE((instance), BASE_TYPE_ISESSION, BaseISessionInterface))
Definition at line 52 of file base-isession.h.
BASE_SIGNAL_QUIT
#define BASE_SIGNAL_QUIT "base-signal-isession-quit"
Definition at line 68 of file base-isession.h.
BASE_SIGNAL_QUIT_REQUESTED
#define BASE_SIGNAL_QUIT_REQUESTED "base-signal-isession-quit-requested"
Signals defined by the BaseISession interface
Definition at line 67 of file base-isession.h.
BASE_TYPE_ISESSION
#define BASE_TYPE_ISESSION (base_isession_get_type())
SECTION: base_isession @short_description: BaseISession interface definition. cact/base-isession.h
This interface implements the features needed to monitor the end of the session, thus letting the application react if some modifications need to be saved before allowing to quit.
This interface is implemented by the BaseApplication class.
Definition at line 49 of file base-isession.h.
Typedef Documentation
BaseISession
typedef struct _BaseISession BaseISession
Definition at line 54 of file base-isession.h.
BaseISessionInterfacePrivate
typedef struct _BaseISessionInterfacePrivate BaseISessionInterfacePrivate
Definition at line 55 of file base-isession.h.
Function Documentation
base_isession_get_type()
GType base_isession_get_type (void)
Definition at line 79 of file base-isession.c.
base_isession_init()
void base_isession_init (BaseISession * instance)
Definition at line 249 of file base-isession.c.
References BASE_IS_ISESSION, data, egg_sm_client_get(), EGG_SM_CLIENT_MODE_NO_RESTART, egg_sm_client_set_mode(), and egg_sm_client_startup().
base_isession_is_willing_to_quit()
gboolean base_isession_is_willing_to_quit (const BaseISession * instance)
Definition at line 294 of file base-isession.c.
References BASE_IS_ISESSION, QUIT_REQUESTED, and TRUE.
Referenced by base_application_is_willing_to_quit().