MATE Desktop Environment: base-gtk-utils.h File Reference
base-gtk-utils.h File Reference
#include "base-window.h"
Functions
void base_gtk_utils_restore_window_position (const BaseWindow *window, const gchar *wsp_name)
void base_gtk_utils_save_window_position (const BaseWindow *window, const gchar *wsp_name)
void base_gtk_utils_set_editable (GObject *widget, gboolean editable)
void base_gtk_utils_radio_set_initial_state (GtkRadioButton *button, GCallback toggled_handler, void *user_data, gboolean editable, gboolean sensitive)
void base_gtk_utils_radio_reset_initial_state (GtkRadioButton *button, GCallback toggled_handler)
void base_gtk_utils_toggle_set_initial_state (BaseWindow *window, const gchar *button_name, GCallback toggled_handler, gboolean active, gboolean editable, gboolean sensitive)
void base_gtk_utils_toggle_reset_initial_state (GtkToggleButton *button)
GdkPixbuf * base_gtk_utils_get_pixbuf (const gchar *name, GtkWidget *widget, GtkIconSize size)
void base_gtk_utils_render (const gchar *name, GtkImage *widget, GtkIconSize size)
void base_gtk_utils_select_file (BaseWindow *window, const gchar *title, const gchar *wsp_name, GtkWidget *entry, const gchar *entry_name)
GtkWidget * base_gtk_utils_file_chooser_dialog_new (const gchar *title, GtkWindow *parent, GtkFileChooserAction action, const gchar *first_button_text,...)
void base_gtk_utils_select_file_with_preview (BaseWindow *window, const gchar *title, const gchar *wsp_name, GtkWidget *entry, const gchar *entry_name, GCallback update_preview_cb)
void base_gtk_utils_select_dir (BaseWindow *window, const gchar *title, const gchar *wsp_name, GtkWidget *entry, const gchar *entry_name)
void base_gtk_utils_table_to_grid (BaseWindow *window, const gchar *table_name)
Function Documentation
base_gtk_utils_file_chooser_dialog_new()
GtkWidget * base_gtk_utils_file_chooser_dialog_new (const gchar * title, GtkWindow * parent, GtkFileChooserAction action, const gchar * first_button_text, ...)
Definition at line 405 of file base-gtk-utils.c.
References action.
Referenced by base_gtk_utils_select_dir(), and base_gtk_utils_select_file_with_preview().
base_gtk_utils_get_pixbuf()
GdkPixbuf * base_gtk_utils_get_pixbuf (const gchar * name, GtkWidget * widget, GtkIconSize size)
Definition at line 235 of file base-gtk-utils.c.
References DEFAULT_HEIGHT, DEFAULT_WIDTH, error, name, and NULL.
Referenced by base_gtk_utils_render().
base_gtk_utils_radio_reset_initial_state()
void base_gtk_utils_radio_reset_initial_state (GtkRadioButton * button, GCallback handler)
base_gtk_utils_radio_reset_initial_state: @button: the #GtkRadioButton being toggled. @handler: the corresponding "toggled" handler. @data: data associated with the @handler callback.
When clicking on a read-only radio button, this function ensures that the radio button is not modified. It may be called whether the radio button group is editable or not (does nothing if group is actually editable).
Definition at line 147 of file base-gtk-utils.c.
References handler, and na_gtk_utils_radio_reset_initial_state().
base_gtk_utils_radio_set_initial_state()
void base_gtk_utils_radio_set_initial_state (GtkRadioButton * button, GCallback handler, void * user_data, gboolean editable, gboolean sensitive)
base_gtk_utils_radio_set_initial_state: @button: the #GtkRadioButton button which is initially active. @handler: the corresponding "toggled" handler. @user_data: the user data associated to the handler. @editable: whether this radio button group is editable. @sensitive: whether this radio button group is sensitive.
This function should be called for the button which is initially active inside of a radio button group when the radio group may happen to not be editable. This function should be called only once for the radio button group.
It does the following operations:
set the button as active
set other buttons of the radio button group as icactive
set all buttons of radio button group as @editable
The initially active @button, along with its @handler, are recorded as properties of the radio button group (actually as properties of each radio button of the group), so that they can later be used to reset the initial state.
Definition at line 129 of file base-gtk-utils.c.
References handler, na_gtk_utils_radio_set_initial_state(), and user_data.
base_gtk_utils_render()
void base_gtk_utils_render (const gchar * name, GtkImage * widget, GtkIconSize size)
Definition at line 297 of file base-gtk-utils.c.
References base_gtk_utils_get_pixbuf(), DEFAULT_HEIGHT, DEFAULT_WIDTH, name, and NULL.
Referenced by cact_main_statusbar_set_locked().
base_gtk_utils_restore_window_position()
void base_gtk_utils_restore_window_position (const BaseWindow * window, const gchar * wsp_name)
SECTION: base-gtk-utils @title: BaseGtkUtils @short_description: Gtk helper functions base-gtk-utils.h
base_gtk_utils_position_window: @window: this #BaseWindow-derived window. @wsp_name: the string which handles the window size and position in user preferences.
Position the specified window on the screen.
A window position is stored as a list of integers "x,y,width,height".
Definition at line 54 of file base-gtk-utils.c.
References BASE_IS_WINDOW, base_window_get_gtk_toplevel(), and na_gtk_utils_restore_window_position().
Referenced by base_gtk_utils_select_dir(), and base_gtk_utils_select_file_with_preview().
base_gtk_utils_save_window_position()
void base_gtk_utils_save_window_position (const BaseWindow * window, const gchar * wsp_name)
base_gtk_utils_save_window_position: @window: this #BaseWindow-derived window. @wsp_name: the string which handles the window size and position in user preferences.
Save the size and position of the specified window.
Definition at line 75 of file base-gtk-utils.c.
References BASE_IS_WINDOW, base_window_get_gtk_toplevel(), and na_gtk_utils_save_window_position().
Referenced by base_gtk_utils_select_dir(), and base_gtk_utils_select_file_with_preview().
base_gtk_utils_select_dir()
void base_gtk_utils_select_dir (BaseWindow * window, const gchar * title, const gchar * wsp_name, GtkWidget * entry, const gchar * entry_name)
base_gtk_utils_select_dir: @window: the BaseWindow which will be the parent of the dialog box. @title: the title of the dialog box. @wsp_name: the name of the dialog box in Preferences to read/write its size and position. @entry: the #GtkEntry which is associated with the field. @entry_name: the name of the entry in Preferences to be read/written. @default_dir_uri: the URI of the directory which should be set in there is not yet any preference (see @entry_name)
Opens a #GtkFileChooserDialog and let the user choose an existing directory -> choose and display an existing dir name -> record the dirname URI of this dir name.
If the user validates its selection, the chosen file pathname will be written in the @entry #GtkEntry, while the corresponding dirname URI will be written as @entry_name in Preferences.
Definition at line 521 of file base-gtk-utils.c.
References base_gtk_utils_file_chooser_dialog_new(), base_gtk_utils_restore_window_position(), base_gtk_utils_save_window_position(), base_window_get_gtk_toplevel(), na_settings_get_string(), na_settings_set_string(), and NULL.
base_gtk_utils_select_file()
void base_gtk_utils_select_file (BaseWindow * window, const gchar * title, const gchar * wsp_name, GtkWidget * entry, const gchar * entry_name)
base_gtk_utils_select_file: @window: the BaseWindow which will be the parent of the dialog box. @title: the title of the dialog box. @wsp_name: the name of the dialog box in Preferences to read/write its size and position. @entry: the #GtkEntry which is associated with the selected file. @entry_name: the name of the entry in Preferences to be read/written.
Opens a #GtkFileChooserDialog and let the user choose an existing file -> choose and display an existing file name -> record the dirname URI.
If the user validates its selection, the chosen file pathname will be written in the @entry #GtkEntry, while the corresponding dirname URI will be written as @entry_name in Preferences.
Definition at line 340 of file base-gtk-utils.c.
References base_gtk_utils_select_file_with_preview(), and NULL.
base_gtk_utils_select_file_with_preview()
void base_gtk_utils_select_file_with_preview (BaseWindow * window, const gchar * title, const gchar * wsp_name, GtkWidget * entry, const gchar * entry_name, GCallback update_preview_cb)
base_gtk_utils_select_file_with_preview: @window: the BaseWindow which will be the parent of the dialog box. @title: the title of the dialog box. @wsp_name: the name of the dialog box in Preferences to read/write its size and position. @entry: the #GtkEntry which is associated with the selected file. @entry_name: the name of the entry in Preferences to be read/written. @update_preview_cb: the callback function in charge of updating the preview widget. May be NULL.
Opens a #GtkFileChooserDialog and let the user choose an existing file -> choose and display an existing file name -> record the dirname URI.
If the user validates its selection, the chosen file pathname will be written in the @entry #GtkEntry, while the corresponding dirname URI will be written as @entry_name in Preferences.
Definition at line 443 of file base-gtk-utils.c.
References base_gtk_utils_file_chooser_dialog_new(), base_gtk_utils_restore_window_position(), base_gtk_utils_save_window_position(), base_window_get_gtk_toplevel(), na_settings_get_string(), na_settings_set_string(), and NULL.
Referenced by base_gtk_utils_select_file().
base_gtk_utils_set_editable()
void base_gtk_utils_set_editable (GObject * widget, gboolean editable)
base_gtk_utils_set_editable: @widget: the #GtkWdiget. @editable: whether the @widget is editable or not.
Try to set a visual indication of whether the @widget is editable or not.
Having a GtkWidget should be enough, but we also deal with a GtkTreeViewColumn. So the most-bottom common ancestor is just GObject (since GtkObject having been deprecated in Gtk+-3.0)
Definition at line 100 of file base-gtk-utils.c.
References na_gtk_utils_set_editable().
Referenced by base_gtk_utils_toggle_set_initial_state().
base_gtk_utils_table_to_grid()
void base_gtk_utils_table_to_grid (BaseWindow * window, const gchar * table_name)
base_gtk_utils_toggle_reset_initial_state()
void base_gtk_utils_toggle_reset_initial_state (GtkToggleButton * button)
base_gtk_utils_toggle_reset_initial_state: @button: the #GtkToggleButton check button.
When clicking on a read-only check button, this function ensures that the check button is not modified. It may be called whether the button is editable or not (does nothing if button is actually editable).
Definition at line 206 of file base-gtk-utils.c.
References handler, NA_TOGGLE_DATA_EDITABLE, NA_TOGGLE_DATA_HANDLER, NA_TOGGLE_DATA_USER_DATA, and user_data.
base_gtk_utils_toggle_set_initial_state()
void base_gtk_utils_toggle_set_initial_state (BaseWindow * window, const gchar * button_name, GCallback handler, gboolean active, gboolean editable, gboolean sensitive)
base_gtk_utils_toggle_set_initial_state: @button: the #GtkToggleButton button. @handler: the corresponding "toggled" handler. @window: the toplevel BaseWindow which embeds the button; it will be passed as user_data when connecting the signal. @active: whether the check button is initially active (checked). @editable: whether this radio button group is editable. @sensitive: whether this radio button group is sensitive.
This function should be called for a check button which may happen to be read-only..
It does the following operations:
connect the 'toggled' handler to the button
set the button as active or icactive depending of @active
set the button as editable or not depending of @editable
set the button as sensitive or not depending of @sensitive
explictely triggers the 'toggled' handler
Definition at line 173 of file base-gtk-utils.c.
References base_gtk_utils_set_editable(), base_window_get_widget(), base_window_signal_connect(), handler, NA_TOGGLE_DATA_EDITABLE, NA_TOGGLE_DATA_HANDLER, and NA_TOGGLE_DATA_USER_DATA.