MATE Desktop Environment: base-builder.c File Reference
base-builder.c File Reference
#include <api/na-core-utils.h>
#include "base-builder.h"
Functions
GType base_builder_get_type (void)
BaseBuilder * base_builder_new (void)
gboolean base_builder_add_from_file (BaseBuilder *builder, const gchar *filename, GError **error)
.
Returns: a pointer to the named window, or NULL. This pointer is owned by GtkBuilder instance, and must not be g_free() nor g_object_unref() by the caller.
GtkWindow * base_builder_get_toplevel_by_name (const BaseBuilder *builder, const gchar *name)
Function Documentation
base_builder_add_from_file()
gboolean base_builder_add_from_file (BaseBuilder * builder, const gchar * filename, GError ** error)
base_builder_add_from_file: @builder: this BaseBuilder object. @filename: the filename to load. @error: a #GError which will be allocated if an error occurs.
Loads the file into the GtkBuilder, taking care of not loading it twice.
Returns: TRUE if filename has been successfully loaded, or was already loaded, FALSE else.
Definition at line 228 of file base-builder.c.
References BASE_IS_BUILDER, error, FALSE, and TRUE.
base_builder_get_toplevel_by_name()
GtkWindow * base_builder_get_toplevel_by_name (const BaseBuilder * builder, const gchar * name)
Definition at line 282 of file base-builder.c.
References BASE_IS_BUILDER, na_core_utils_slist_dump(), name, and NULL.
Referenced by base_window_get_gtk_toplevel_by_name().
base_builder_get_type()
GType base_builder_get_type (void)
Definition at line 62 of file base-builder.c.
base_builder_new()
BaseBuilder * base_builder_new (void)
base_builder_new:
Returns: a newly allocated BaseBuilder object.
Definition at line 206 of file base-builder.c.
References BASE_TYPE_BUILDER, and NULL.
Referenced by base_window_init().