MATE Desktop Environment: base-builder.h File Reference
base-builder.h File Reference
#include <gtk/gtk.h>
Classes
struct BaseBuilder
struct BaseBuilderClass
Macros
#define BASE_TYPE_BUILDER (base_builder_get_type())
#define BASE_BUILDER(object)
#define BASE_BUILDER_CLASS(klass)
#define BASE_IS_BUILDER(object)
#define BASE_IS_BUILDER_CLASS(klass)
#define BASE_BUILDER_GET_CLASS(object)
Typedefs
typedef struct _BaseBuilderPrivate BaseBuilderPrivate
typedef struct _BaseBuilderClassPrivate BaseBuilderClassPrivate
Functions
GType base_builder_get_type (void)
BaseBuilder * base_builder_new (void)
gboolean base_builder_add_from_file (BaseBuilder *builder, const gchar *filename, GError **error)
GtkWindow * base_builder_get_toplevel_by_name (const BaseBuilder *builder, const gchar *name)
Macro Definition Documentation
BASE_BUILDER
#define BASE_BUILDER (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST(object, BASE_TYPE_BUILDER, BaseBuilder))
Definition at line 54 of file base-builder.h.
BASE_BUILDER_CLASS
#define BASE_BUILDER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST(klass, BASE_TYPE_BUILDER, BaseBuilderClass))
Definition at line 55 of file base-builder.h.
BASE_BUILDER_GET_CLASS
#define BASE_BUILDER_GET_CLASS (object)
Value:
(G_TYPE_INSTANCE_GET_CLASS((object), BASE_TYPE_BUILDER, BaseBuilderClass))
Definition at line 58 of file base-builder.h.
BASE_IS_BUILDER
#define BASE_IS_BUILDER (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE(object, BASE_TYPE_BUILDER))
Definition at line 56 of file base-builder.h.
Referenced by base_builder_add_from_file(), base_builder_get_toplevel_by_name(), and base_window_init().
BASE_IS_BUILDER_CLASS
#define BASE_IS_BUILDER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass), BASE_TYPE_BUILDER))
Definition at line 57 of file base-builder.h.
BASE_TYPE_BUILDER
#define BASE_TYPE_BUILDER (base_builder_get_type())
SECTION: base_builder @short_description: BaseBuilder class definition. cact/base-builder.h
This class is derived from GtkBuilder class. It adds to it two features:
do not load twice the .xml files;
destroy Gtk toplevels at dispose time.
A common #Basebuilder object is instanciated at BaseWindow class level. Each #Basewindow -derived object may later use this common BaseBuilder object, or allocate its own.
Definition at line 53 of file base-builder.h.
Referenced by base_builder_new().
Typedef Documentation
BaseBuilderClassPrivate
typedef struct _BaseBuilderClassPrivate BaseBuilderClassPrivate
Definition at line 69 of file base-builder.h.
BaseBuilderPrivate
typedef struct _BaseBuilderPrivate BaseBuilderPrivate
Definition at line 60 of file base-builder.h.
Function Documentation
base_builder_add_from_file()
gboolean base_builder_add_from_file (BaseBuilder * builder, const gchar * filename, GError ** error)
base_builder_add_from_file: @builder: this BaseBuilder object. @filename: the filename to load. @error: a #GError which will be allocated if an error occurs.
Loads the file into the GtkBuilder, taking care of not loading it twice.
Returns: TRUE if filename has been successfully loaded, or was already loaded, FALSE else.
Definition at line 228 of file base-builder.c.
References BASE_IS_BUILDER, error, FALSE, and TRUE.
base_builder_get_toplevel_by_name()
GtkWindow * base_builder_get_toplevel_by_name (const BaseBuilder * builder, const gchar * name)
Definition at line 282 of file base-builder.c.
References BASE_IS_BUILDER, na_core_utils_slist_dump(), name, and NULL.
Referenced by base_window_get_gtk_toplevel_by_name().
base_builder_get_type()
GType base_builder_get_type (void)
Definition at line 62 of file base-builder.c.
base_builder_new()
BaseBuilder * base_builder_new (void)
base_builder_new:
Returns: a newly allocated BaseBuilder object.
Definition at line 206 of file base-builder.c.
References BASE_TYPE_BUILDER, and NULL.
Referenced by base_window_init().