MATE Desktop Environment: base-isession.c File Reference
base-isession.c File Reference
#include "base-isession.h"
#include "base-marshal.h"
#include "egg-sm-client.h"
Macros
#define BASE_PROP_ISESSION_DATA "base-prop-isession-data"
Enumerations
enum { QUIT_REQUESTED , QUIT , LAST_SIGNAL }
Functions
GType base_isession_get_type (void)
void base_isession_init (BaseISession *instance)
gboolean base_isession_is_willing_to_quit (const BaseISession *instance)
Macro Definition Documentation
BASE_PROP_ISESSION_DATA
#define BASE_PROP_ISESSION_DATA "base-prop-isession-data"
Definition at line 53 of file base-isession.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
QUIT_REQUESTED
QUIT
LAST_SIGNAL
Definition at line 57 of file base-isession.c.
Function Documentation
base_isession_get_type()
GType base_isession_get_type (void)
Definition at line 79 of file base-isession.c.
base_isession_init()
void base_isession_init (BaseISession * instance)
Definition at line 249 of file base-isession.c.
References BASE_IS_ISESSION, data, egg_sm_client_get(), EGG_SM_CLIENT_MODE_NO_RESTART, egg_sm_client_set_mode(), and egg_sm_client_startup().
base_isession_is_willing_to_quit()
gboolean base_isession_is_willing_to_quit (const BaseISession * instance)
Definition at line 294 of file base-isession.c.
References BASE_IS_ISESSION, QUIT_REQUESTED, and TRUE.
Referenced by base_application_is_willing_to_quit().