MATE Desktop Environment: battstat.h File Reference
battstat.h File Reference
#include <glib.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <mate-panel-applet.h>
#include <mate-panel-applet-gsettings.h>
Classes
struct BatteryStatus
struct LayoutConfiguration
struct _ProgressData
Macros
#define DEBUG 0
#define PROGLEN 33.0
#define ORANGE_MULTIPLIER 1.5
#define YELLOW_MULTIPLIER 2.5
Typedefs
typedef struct _ProgressData ProgressData
Enumerations
enum AppletTextType { APPLET_SHOW_NONE = 0 , APPLET_SHOW_PERCENT , APPLET_SHOW_TIME }
enum StatusPixmapIndex {
STATUS_PIXMAP_BATTERY , STATUS_PIXMAP_METER , STATUS_PIXMAP_AC , STATUS_PIXMAP_CHARGE ,
STATUS_PIXMAP_WARNING , STATUS_PIXMAP_NUM
}
enum PowerStatus { POWER_STATUS_OFF = 0 , POWER_STATUS_ON , POWER_STATUS_UNKNOWN }
enum LayoutLocation {
LAYOUT_NONE , LAYOUT_LONG , LAYOUT_TOPLEFT , LAYOUT_TOP ,
LAYOUT_LEFT , LAYOUT_CENTRE , LAYOUT_RIGHT , LAYOUT_BOTTOM
}
Functions
void reconfigure_layout (ProgressData *battstat)
void battstat_show_help (ProgressData *battstat, const char *section)
void prop_cb (GtkAction *, ProgressData *)
const char * power_management_getinfo (BatteryStatus *status)
const char * power_management_initialise (void(*callback)(void))
void power_management_cleanup (void)
gboolean power_management_using_upower (void)
Macro Definition Documentation
DEBUG
#define DEBUG 0
Definition at line 32 of file battstat.h.
ORANGE_MULTIPLIER
#define ORANGE_MULTIPLIER 1.5
Definition at line 39 of file battstat.h.
PROGLEN
#define PROGLEN 33.0
Definition at line 34 of file battstat.h.
YELLOW_MULTIPLIER
#define YELLOW_MULTIPLIER 2.5
Definition at line 40 of file battstat.h.
Typedef Documentation
ProgressData
typedef struct _ProgressData ProgressData
Enumeration Type Documentation
AppletTextType
enum AppletTextType
Enumerator
APPLET_SHOW_NONE
APPLET_SHOW_PERCENT
APPLET_SHOW_TIME
Definition at line 42 of file battstat.h.
LayoutLocation
enum LayoutLocation
Enumerator
LAYOUT_NONE
LAYOUT_LONG
LAYOUT_TOPLEFT
LAYOUT_TOP
LAYOUT_LEFT
LAYOUT_CENTRE
LAYOUT_RIGHT
LAYOUT_BOTTOM
Definition at line 75 of file battstat.h.
PowerStatus
enum PowerStatus
Enumerator
POWER_STATUS_OFF
POWER_STATUS_ON
POWER_STATUS_UNKNOWN
Definition at line 59 of file battstat.h.
StatusPixmapIndex
enum StatusPixmapIndex
Enumerator
STATUS_PIXMAP_BATTERY
STATUS_PIXMAP_METER
STATUS_PIXMAP_AC
STATUS_PIXMAP_CHARGE
STATUS_PIXMAP_WARNING
STATUS_PIXMAP_NUM
Definition at line 49 of file battstat.h.
Function Documentation
battstat_show_help()
void battstat_show_help (ProgressData * battstat, const char * section)
Definition at line 769 of file battstat_applet.c.
References _, error, message(), and NULL.
power_management_cleanup()
void power_management_cleanup (void)
Definition at line 497 of file power-management.c.
References acpi_freebsd_cleanup(), acpi_linux_cleanup(), battstat_upower_cleanup(), FALSE, and TRUE.
power_management_getinfo()
const char * power_management_getinfo (BatteryStatus * status)
Definition at line 380 of file power-management.c.
References battstat_upower_get_battery_info(), BatteryStatus::charging, FALSE, BatteryStatus::minutes, NULL, BatteryStatus::on_ac_power, BatteryStatus::percent, BatteryStatus::present, and TRUE.
power_management_initialise()
const char * power_management_initialise (void(* callback)(void))
Definition at line 433 of file power-management.c.
References acpi_freebsd_init(), acpi_linux_init(), apm_exists(), battstat_upower_initialise(), ERR_ACPID, FALSE, NULL, and TRUE.
power_management_using_upower()
gboolean power_management_using_upower (void)
Definition at line 526 of file power-management.c.
References FALSE.
prop_cb()
void prop_cb (GtkAction * action, ProgressData * battstat)
Definition at line 1108 of file battstat_applet.c.
References action, and battstat_preferences_new().
reconfigure_layout()
void reconfigure_layout (ProgressData * battstat)
Definition at line 1000 of file battstat_applet.c.
References LAYOUT_BOTTOM, LAYOUT_LEFT, LAYOUT_NONE, LAYOUT_RIGHT, LAYOUT_TOP, LayoutConfiguration::status, and LayoutConfiguration::text.