MATE Desktop Environment: battstat-upower.h File Reference
battstat-upower.h File Reference
#include "battstat.h"
Functions
char * battstat_upower_initialise (void(*)(void))
void battstat_upower_cleanup (void)
void error_dialog (const char *fmt,...)
void battstat_upower_get_battery_info (BatteryStatus *status)
Function Documentation
battstat_upower_cleanup()
void battstat_upower_cleanup (void)
Referenced by power_management_cleanup().
battstat_upower_get_battery_info()
void battstat_upower_get_battery_info (BatteryStatus * status)
Referenced by power_management_getinfo().
battstat_upower_initialise()
char * battstat_upower_initialise (void(*)(void))
Referenced by power_management_initialise().
error_dialog()
void error_dialog (const char * fmt, ...)
Referenced by gdict_create_data_dir(), launcher_launch(), main(), and netspeed_applet_display_help().