MATE Desktop Environment: bitmap.c File Reference
bitmap.c File Reference
#include <config.h>
#include <stdlib.h>
#include "mdvi.h"
#include "color.h"
Macros
#define SHOW_OP_DATA (DEBUGGING(BITMAP_OPS) && DEBUGGING(BITMAP_DATA))
#define SEGMENT(m, n)
Functions
BITMAP * bitmap_convert_lsb8 (Uchar *bits, int w, int h, int stride)
BITMAP * bitmap_convert_msb8 (Uchar *data, int w, int h, int stride)
BITMAP * bitmap_copy (BITMAP *bm)
BITMAP * bitmap_alloc (int w, int h)
BITMAP * bitmap_alloc_raw (int w, int h)
void bitmap_destroy (BITMAP *bm)
void bitmap_print (FILE *out, BITMAP *bm)
void bitmap_set_col (BITMAP *bm, int row, int col, int count, int state)
void bitmap_paint_bits (BmUnit *ptr, int n, int count)
void bitmap_clear_bits (BmUnit *ptr, int n, int count)
void bitmap_set_row (BITMAP *bm, int row, int col, int count, int state)
void bitmap_flip_horizontally (BITMAP *bm)
void bitmap_flip_vertically (BITMAP *bm)
void bitmap_flip_diagonally (BITMAP *bm)
void bitmap_rotate_clockwise (BITMAP *bm)
void bitmap_rotate_counter_clockwise (BITMAP *bm)
void bitmap_flip_rotate_clockwise (BITMAP *bm)
void bitmap_flip_rotate_counter_clockwise (BITMAP *bm)
void mdvi_shrink_box (DviContext *dvi, DviFont *font, DviFontChar *pk, DviGlyph *dest)
void mdvi_shrink_glyph (DviContext *dvi, DviFont *font, DviFontChar *pk, DviGlyph *dest)
void mdvi_shrink_glyph_grey (DviContext *dvi, DviFont *font, DviFontChar *pk, DviGlyph *dest)
Macro Definition Documentation
SEGMENT
#define SEGMENT (m, n)
Value:
(bit_masks[m] << (n))
Definition at line 60 of file bitmap.c.
Referenced by bitmap_clear_bits(), and bitmap_paint_bits().
SHOW_OP_DATA
#define SHOW_OP_DATA (DEBUGGING(BITMAP_OPS) && DEBUGGING(BITMAP_DATA))
Definition at line 48 of file bitmap.c.
Referenced by bitmap_convert_lsb8(), bitmap_convert_msb8(), bitmap_flip_diagonally(), bitmap_flip_horizontally(), bitmap_flip_rotate_clockwise(), bitmap_flip_rotate_counter_clockwise(), bitmap_flip_vertically(), bitmap_rotate_clockwise(), and bitmap_rotate_counter_clockwise().
Function Documentation
bitmap_alloc()
BITMAP * bitmap_alloc (int w, int h)
Definition at line 203 of file bitmap.c.
References BM_BYTES_PER_LINE, BITMAP::data, BITMAP::height, mdvi_calloc(), NULL, BITMAP::stride, BITMAP::width, and xalloc.
Referenced by __PROTO(), bitmap_convert_msb8(), bitmap_copy(), and mdvi_shrink_glyph().
bitmap_alloc_raw()
BITMAP * bitmap_alloc_raw (int w, int h)
Definition at line 219 of file bitmap.c.
References BM_BYTES_PER_LINE, BITMAP::data, BITMAP::height, mdvi_malloc(), NULL, BITMAP::stride, BITMAP::width, and xalloc.
Referenced by __PROTO(), and bitmap_convert_lsb8().
bitmap_clear_bits()
void bitmap_clear_bits (BmUnit * ptr, int n, int count)
Definition at line 342 of file bitmap.c.
References BITMAP_BITS, ptr, and SEGMENT.
Referenced by __PROTO(), and bitmap_set_row().
bitmap_convert_lsb8()
BITMAP * bitmap_convert_lsb8 (Uchar * bits, int w, int h, int stride)
Definition at line 127 of file bitmap.c.
References bitmap_alloc_raw(), bitmap_print(), BITMAP::data, DBG_BITMAP_OPS, DEBUG, memcpy, memzero, ROUND, SHOW_OP_DATA, and BITMAP::stride.
Referenced by __PROTO().
bitmap_convert_msb8()
BITMAP * bitmap_convert_msb8 (Uchar * data, int w, int h, int stride)
Definition at line 163 of file bitmap.c.
References bitmap_alloc(), bitmap_print(), BITMAP::data, data, memcpy, memzero, ROUND, SHOW_OP_DATA, and BITMAP::stride.
Referenced by __PROTO().
bitmap_copy()
BITMAP * bitmap_copy (BITMAP * bm)
Definition at line 194 of file bitmap.c.
References bitmap_alloc(), BITMAP::data, DBG_BITMAP_OPS, DEBUG, BITMAP::height, memcpy, BITMAP::stride, and BITMAP::width.
Referenced by __PROTO().
bitmap_destroy()
void bitmap_destroy (BITMAP * bm)
Definition at line 235 of file bitmap.c.
References BITMAP::data.
Referenced by __PROTO(), and font_reset_one_glyph().
bitmap_flip_diagonally()
void bitmap_flip_diagonally (BITMAP * bm)
Definition at line 465 of file bitmap.c.
References __bm_unit_ptr, bitmap_print(), bm_offset, BITMAP::data, DBG_BITMAP_OPS, DEBUG, FIRSTMASK, FIRSTMASKAT, BITMAP::height, LASTMASK, mdvi_calloc(), mdvi_free(), NEXTMASK, PREVMASK, SHOW_OP_DATA, BITMAP::stride, and BITMAP::width.
Referenced by __PROTO(), and font_transform_glyph().
bitmap_flip_horizontally()
void bitmap_flip_horizontally (BITMAP * bm)
Definition at line 378 of file bitmap.c.
References __bm_unit_ptr, bitmap_print(), bm_offset, BITMAP::data, DBG_BITMAP_OPS, DEBUG, FIRSTMASK, FIRSTMASKAT, BITMAP::height, LASTMASK, mdvi_calloc(), mdvi_free(), NEXTMASK, PREVMASK, SHOW_OP_DATA, BITMAP::stride, and BITMAP::width.
Referenced by __PROTO(), and font_transform_glyph().
bitmap_flip_rotate_clockwise()
void bitmap_flip_rotate_clockwise (BITMAP * bm)
Definition at line 615 of file bitmap.c.
References __bm_unit_ptr, bitmap_print(), BM_BYTES_PER_LINE, bm_offset, BITMAP::data, DBG_BITMAP_OPS, DEBUG, FIRSTMASK, FIRSTMASKAT, BITMAP::height, LASTMASK, mdvi_calloc(), mdvi_free(), NEXTMASK, PREVMASK, SHOW_OP_DATA, BITMAP::stride, and BITMAP::width.
Referenced by __PROTO(), and font_transform_glyph().
bitmap_flip_rotate_counter_clockwise()
void bitmap_flip_rotate_counter_clockwise (BITMAP * bm)
Definition at line 666 of file bitmap.c.
References bitmap_print(), BM_BYTES_PER_LINE, bm_offset, BITMAP::data, DBG_BITMAP_OPS, DEBUG, FIRSTMASK, BITMAP::height, LASTMASK, mdvi_calloc(), mdvi_free(), NEXTMASK, SHOW_OP_DATA, BITMAP::stride, and BITMAP::width.
Referenced by __PROTO(), and font_transform_glyph().
bitmap_flip_vertically()
void bitmap_flip_vertically (BITMAP * bm)
Definition at line 424 of file bitmap.c.
References __bm_unit_ptr, bitmap_print(), bm_offset, BITMAP::data, DBG_BITMAP_OPS, DEBUG, FIRSTMASK, BITMAP::height, LASTMASK, mdvi_calloc(), mdvi_free(), NEXTMASK, SHOW_OP_DATA, BITMAP::stride, and BITMAP::width.
Referenced by __PROTO(), and font_transform_glyph().
bitmap_paint_bits()
void bitmap_paint_bits (BmUnit * ptr, int n, int count)
Definition at line 317 of file bitmap.c.
References BITMAP_BITS, ptr, and SEGMENT.
Referenced by __PROTO(), and bitmap_set_row().
bitmap_print()
void bitmap_print (FILE * out, BITMAP * bm)
Definition at line 242 of file bitmap.c.
References BITMAP::data, FIRSTMASK, BITMAP::height, LASTMASK, mask, NEXTMASK, BITMAP::stride, and BITMAP::width.
Referenced by __PROTO(), bitmap_convert_lsb8(), bitmap_convert_msb8(), bitmap_flip_diagonally(), bitmap_flip_horizontally(), bitmap_flip_rotate_clockwise(), bitmap_flip_rotate_counter_clockwise(), bitmap_flip_vertically(), bitmap_rotate_clockwise(), bitmap_rotate_counter_clockwise(), and mdvi_shrink_glyph().
bitmap_rotate_clockwise()
void bitmap_rotate_clockwise (BITMAP * bm)
Definition at line 511 of file bitmap.c.
References __bm_unit_ptr, bitmap_print(), BM_BYTES_PER_LINE, bm_offset, BITMAP::data, DBG_BITMAP_OPS, DEBUG, FIRSTMASK, FIRSTMASKAT, BITMAP::height, LASTMASK, mdvi_calloc(), mdvi_free(), NEXTMASK, PREVMASK, SHOW_OP_DATA, BITMAP::stride, and BITMAP::width.
Referenced by __PROTO(), and font_transform_glyph().
bitmap_rotate_counter_clockwise()
void bitmap_rotate_counter_clockwise (BITMAP * bm)
Definition at line 563 of file bitmap.c.
References __bm_unit_ptr, bitmap_print(), BM_BYTES_PER_LINE, bm_offset, BITMAP::data, DBG_BITMAP_OPS, DEBUG, FIRSTMASK, BITMAP::height, LASTMASK, mdvi_calloc(), mdvi_free(), NEXTMASK, SHOW_OP_DATA, BITMAP::stride, and BITMAP::width.
Referenced by __PROTO(), and font_transform_glyph().
bitmap_set_col()
void bitmap_set_col (BITMAP * bm, int row, int col, int count, int state)
Definition at line 289 of file bitmap.c.
References __bm_unit_ptr, bm_offset, FIRSTMASKAT, mask, ptr, and BITMAP::stride.
Referenced by __PROTO().
bitmap_set_row()
void bitmap_set_row (BITMAP * bm, int row, int col, int count, int state)
Definition at line 363 of file bitmap.c.
References __bm_unit_ptr, BITMAP_BITS, bitmap_clear_bits(), bitmap_paint_bits(), and ptr.
Referenced by __PROTO().
mdvi_shrink_box()
void mdvi_shrink_box (DviContext * dvi, DviFont * font, DviFontChar * pk, DviGlyph * dest)
Definition at line 801 of file bitmap.c.
References DBG_BITMAPS, DEBUG, dest, _DviFontChar::glyph, _DviGlyph::h, _DviParams::hshrink, int(), MDVI_GLYPH_EMPTY, _DviContext::params, ROUND, _DviParams::vshrink, _DviGlyph::w, _DviGlyph::x, and _DviGlyph::y.
Referenced by __PROTO(), and font_get_glyph().
mdvi_shrink_glyph()
void mdvi_shrink_glyph (DviContext * dvi, DviFont * font, DviFontChar * pk, DviGlyph * dest)
Definition at line 830 of file bitmap.c.
References bitmap_alloc(), bitmap_print(), bm_offset, _DviGlyph::data, BITMAP::data, DBG_BITMAPS, DEBUG, DEBUGGING, _DviParams::density, dest, FIRSTMASK, _DviFontChar::glyph, _DviGlyph::h, _DviParams::hshrink, int(), LASTMASK, NEXTMASK, _DviContext::params, ROUND, BITMAP::stride, _DviParams::vshrink, _DviGlyph::w, _DviGlyph::x, and _DviGlyph::y.
Referenced by __PROTO(), and mdvi_shrink_glyph_grey().
mdvi_shrink_glyph_grey()
void mdvi_shrink_glyph_grey (DviContext * dvi, DviFont * font, DviFontChar * pk, DviGlyph * dest)
Definition at line 919 of file bitmap.c.
References ASSERT, _DviFontChar::bg, BITMAP_BITS, bm_offset, _DviDevice::create_image, _DviGlyph::data, DBG_BITMAPS, DEBUG, _DviParams::density, dest, _DviContext::device, _DviDevice::device_data, _DviFontChar::fg, _DviParams::gamma, get_color_table(), _DviFontChar::glyph, _DviGlyph::h, _DviParams::hshrink, _DviDevice::image_done, int(), MDVI_CURRBG, MDVI_CURRFG, mdvi_shrink_glyph(), NULL, _DviContext::params, _DviDevice::put_pixel, ROUND, _DviParams::vshrink, _DviGlyph::w, _DviGlyph::x, and _DviGlyph::y.
Referenced by __PROTO().