MATE Desktop Environment: bookmark-agent.c File Reference
bookmark-agent.c File Reference
#include "bookmark-agent.h"
#include <gtk/gtk.h>
#include <string.h>
#include <stdlib.h>
#include <glib/gi18n-lib.h>
#include <glib/gstdio.h>
#include <gio/gio.h>
#include "libslab-utils.h"
Macros
#define PACKAGE "mate-main-menu"
#define USER_APPS_STORE_FILE_NAME "applications.xbel"
#define USER_DOCS_STORE_FILE_NAME "documents.xbel"
#define USER_DIRS_STORE_FILE_NAME "places.xbel"
#define SYSTEM_STORE_FILE_NAME "system-items.xbel"
#define CALC_TEMPLATE_FILE_NAME "empty.ots"
#define WRITER_TEMPLATE_FILE_NAME "empty.ott"
#define GTK_BOOKMARKS_FILE "bookmarks"
#define TYPE_IS_RECENT(type)
Enumerations
enum { PROP_0 , PROP_ITEMS , PROP_STATUS }
Functions
GType bookmark_agent_get_type ()
gboolean bookmark_agent_has_item (BookmarkAgent *this, const gchar *uri)
void bookmark_agent_add_item (BookmarkAgent *this, const BookmarkItem *item)
void bookmark_agent_move_item (BookmarkAgent *this, const gchar *uri, const gchar *uri_new)
void bookmark_agent_purge_items (BookmarkAgent *this)
void bookmark_agent_remove_item (BookmarkAgent *this, const gchar *uri)
void bookmark_agent_reorder_items (BookmarkAgent *this, const gchar **uris)
void bookmark_agent_update_from_bookmark_file (BookmarkAgent *this, GBookmarkFile *store)
void bookmark_item_free (BookmarkItem *item)
BookmarkAgent * bookmark_agent_get_instance (BookmarkStoreType type)
Macro Definition Documentation
CALC_TEMPLATE_FILE_NAME
#define CALC_TEMPLATE_FILE_NAME "empty.ots"
Definition at line 43 of file bookmark-agent.c.
GTK_BOOKMARKS_FILE
#define GTK_BOOKMARKS_FILE "bookmarks"
Definition at line 46 of file bookmark-agent.c.
PACKAGE
#define PACKAGE "mate-main-menu"
Definition at line 26 of file bookmark-agent.c.
SYSTEM_STORE_FILE_NAME
#define SYSTEM_STORE_FILE_NAME "system-items.xbel"
Definition at line 42 of file bookmark-agent.c.
TYPE_IS_RECENT
#define TYPE_IS_RECENT (type)
Value:
((type) == BOOKMARK_STORE_RECENT_APPS || (type) == BOOKMARK_STORE_RECENT_DOCS)
Definition at line 48 of file bookmark-agent.c.
Referenced by bookmark_agent_move_item(), bookmark_agent_purge_items(), and bookmark_agent_remove_item().
USER_APPS_STORE_FILE_NAME
#define USER_APPS_STORE_FILE_NAME "applications.xbel"
Definition at line 39 of file bookmark-agent.c.
USER_DIRS_STORE_FILE_NAME
#define USER_DIRS_STORE_FILE_NAME "places.xbel"
Definition at line 41 of file bookmark-agent.c.
USER_DOCS_STORE_FILE_NAME
#define USER_DOCS_STORE_FILE_NAME "documents.xbel"
Definition at line 40 of file bookmark-agent.c.
WRITER_TEMPLATE_FILE_NAME
#define WRITER_TEMPLATE_FILE_NAME "empty.ott"
Definition at line 44 of file bookmark-agent.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_ITEMS
PROP_STATUS
Definition at line 78 of file bookmark-agent.c.
Function Documentation
bookmark_agent_add_item()
void bookmark_agent_add_item (BookmarkAgent * this, const BookmarkItem * item)
Definition at line 157 of file bookmark-agent.c.
References item.
bookmark_agent_get_instance()
BookmarkAgent * bookmark_agent_get_instance (BookmarkStoreType type)
Definition at line 569 of file bookmark-agent.c.
References BOOKMARK_STORE_N_TYPES, and NULL.
bookmark_agent_get_type()
GType bookmark_agent_get_type (void)
Definition at line 125 of file bookmark-agent.c.
References NULL.
bookmark_agent_has_item()
gboolean bookmark_agent_has_item (BookmarkAgent * this, const gchar * uri)
Definition at line 150 of file bookmark-agent.c.
Referenced by bookmark_agent_remove_item().
bookmark_agent_move_item()
void bookmark_agent_move_item (BookmarkAgent * this, const gchar * uri, const gchar * uri_new)
Definition at line 188 of file bookmark-agent.c.
References error, NULL, and TYPE_IS_RECENT.
bookmark_agent_purge_items()
void bookmark_agent_purge_items (BookmarkAgent * this)
Definition at line 206 of file bookmark-agent.c.
References error, NULL, and TYPE_IS_RECENT.
bookmark_agent_remove_item()
void bookmark_agent_remove_item (BookmarkAgent * this, const gchar * uri)
Definition at line 237 of file bookmark-agent.c.
References bookmark_agent_has_item(), error, NULL, and TYPE_IS_RECENT.
bookmark_agent_reorder_items()
void bookmark_agent_reorder_items (BookmarkAgent * this, const gchar ** uris)
Definition at line 283 of file bookmark-agent.c.
bookmark_agent_update_from_bookmark_file()
void bookmark_agent_update_from_bookmark_file (BookmarkAgent * this, GBookmarkFile * store)
Definition at line 355 of file bookmark-agent.c.
References bookmark_item_free(), IS_BOOKMARK_AGENT, and item.
bookmark_item_free()
void bookmark_item_free (BookmarkItem * item)
Definition at line 391 of file bookmark-agent.c.
References item.
Referenced by bookmark_agent_update_from_bookmark_file().