MATE Desktop Environment: boxes.c File Reference
boxes.c File Reference
#include "boxes.h"
#include "util.h"
#include <X11/Xutil.h>
Functions
char * meta_rectangle_to_string (const MetaRectangle *rect, char *output)
char * meta_rectangle_region_to_string (GList *region, const char *separator_string, char *output)
char * meta_rectangle_edge_to_string (const MetaEdge *edge, char *output)
char * meta_rectangle_edge_list_to_string (GList *edge_list, const char *separator_string, char *output)
MetaRectangle meta_rect (int x, int y, int width, int height)
int meta_rectangle_area (const MetaRectangle *rect)
gboolean meta_rectangle_intersect (const MetaRectangle *src1, const MetaRectangle *src2, MetaRectangle *dest)
gboolean meta_rectangle_equal (const MetaRectangle *src1, const MetaRectangle *src2)
void meta_rectangle_union (const MetaRectangle *rect1, const MetaRectangle *rect2, MetaRectangle *dest)
gboolean meta_rectangle_overlap (const MetaRectangle *rect1, const MetaRectangle *rect2)
gboolean meta_rectangle_vert_overlap (const MetaRectangle *rect1, const MetaRectangle *rect2)
gboolean meta_rectangle_horiz_overlap (const MetaRectangle *rect1, const MetaRectangle *rect2)
gboolean meta_rectangle_could_fit_rect (const MetaRectangle *outer_rect, const MetaRectangle *inner_rect)
gboolean meta_rectangle_contains_rect (const MetaRectangle *outer_rect, const MetaRectangle *inner_rect)
void meta_rectangle_resize_with_gravity (const MetaRectangle *old_rect, MetaRectangle *rect, int gravity, int new_width, int new_height)
GList * meta_rectangle_get_minimal_spanning_set_for_region (const MetaRectangle *basic_rect, const GSList *all_struts, gboolean skip_middle_struts)
GList * meta_rectangle_expand_region (GList *region, const int left_expand, const int right_expand, const int top_expand, const int bottom_expand)
GList * meta_rectangle_expand_region_conditionally (GList *region, const int left_expand, const int right_expand, const int top_expand, const int bottom_expand, const int min_x, const int min_y)
void meta_rectangle_expand_to_avoiding_struts (MetaRectangle *rect, const MetaRectangle *expand_to, const MetaDirection direction, const GSList *all_struts)
gboolean meta_rectangle_could_fit_in_region (const GList *spanning_rects, const MetaRectangle *rect)
gboolean meta_rectangle_contained_in_region (const GList *spanning_rects, const MetaRectangle *rect)
gboolean meta_rectangle_overlaps_with_region (const GList *spanning_rects, const MetaRectangle *rect)
void meta_rectangle_clamp_to_fit_into_region (const GList *spanning_rects, FixedDirections fixed_directions, MetaRectangle *rect, const MetaRectangle *min_size)
void meta_rectangle_clip_to_region (const GList *spanning_rects, FixedDirections fixed_directions, MetaRectangle *rect)
void meta_rectangle_shove_into_region (const GList *spanning_rects, FixedDirections fixed_directions, MetaRectangle *rect)
void meta_rectangle_find_linepoint_closest_to_point (double x1, double y1, double x2, double y2, double px, double py, double *valx, double *valy)
gboolean meta_rectangle_edge_aligns (const MetaRectangle *rect, const MetaEdge *edge)
gint meta_rectangle_edge_cmp_ignore_type (gconstpointer a, gconstpointer b)
gint meta_rectangle_edge_cmp (gconstpointer a, gconstpointer b)
GList * meta_rectangle_remove_intersections_with_boxes_from_edges (GList *edges, const GSList *rectangles)
GList * meta_rectangle_find_onscreen_edges (const MetaRectangle *basic_rect, const GSList *all_struts)
GList * meta_rectangle_find_nonintersected_xinerama_edges (const MetaRectangle *screen_rect, const GList *xinerama_rects, const GSList *all_struts)
Function Documentation
meta_rect()
MetaRectangle meta_rect (int x, int y, int width, int height)
Definition at line 135 of file boxes.c.
References _MetaRectangle::height, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_frame_style_draw_with_style(), and meta_rectangle_find_nonintersected_xinerama_edges().
meta_rectangle_area()
int meta_rectangle_area (const MetaRectangle * rect)
Definition at line 147 of file boxes.c.
References _MetaRectangle::height, NULL, and _MetaRectangle::width.
Referenced by meta_rectangle_clip_to_region(), and meta_screen_get_xinerama_for_rect().
meta_rectangle_clamp_to_fit_into_region()
void meta_rectangle_clamp_to_fit_into_region (const GList * spanning_rects, FixedDirections fixed_directions, MetaRectangle * rect, const MetaRectangle * min_size)
Definition at line 839 of file boxes.c.
References FIXED_DIRECTION_X, FIXED_DIRECTION_Y, _MetaRectangle::height, meta_warning(), MIN, NULL, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
meta_rectangle_clip_to_region()
void meta_rectangle_clip_to_region (const GList * spanning_rects, FixedDirections fixed_directions, MetaRectangle * rect)
Definition at line 909 of file boxes.c.
References FIXED_DIRECTION_X, FIXED_DIRECTION_Y, _MetaRectangle::height, MAX, meta_rectangle_area(), meta_rectangle_intersect(), meta_warning(), MIN, NULL, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
meta_rectangle_contained_in_region()
gboolean meta_rectangle_contained_in_region (const GList * spanning_rects, const MetaRectangle * rect)
Definition at line 803 of file boxes.c.
References FALSE, meta_rectangle_contains_rect(), and NULL.
meta_rectangle_contains_rect()
gboolean meta_rectangle_contains_rect (const MetaRectangle * outer_rect, const MetaRectangle * inner_rect)
Definition at line 272 of file boxes.c.
References _MetaRectangle::height, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_rectangle_contained_in_region(), meta_screen_get_current_xinerama(), and meta_window_update_struts().
meta_rectangle_could_fit_in_region()
gboolean meta_rectangle_could_fit_in_region (const GList * spanning_rects, const MetaRectangle * rect)
Definition at line 785 of file boxes.c.
References FALSE, meta_rectangle_could_fit_rect(), and NULL.
meta_rectangle_could_fit_rect()
gboolean meta_rectangle_could_fit_rect (const MetaRectangle * outer_rect, const MetaRectangle * inner_rect)
Definition at line 264 of file boxes.c.
References _MetaRectangle::height, and _MetaRectangle::width.
Referenced by meta_rectangle_could_fit_in_region().
meta_rectangle_edge_aligns()
gboolean meta_rectangle_edge_aligns (const MetaRectangle * rect, const MetaEdge * edge)
Definition at line 1149 of file boxes.c.
References BOX_BOTTOM, BOX_LEFT, BOX_RIGHT, BOX_TOP, META_SIDE_BOTTOM, META_SIDE_LEFT, META_SIDE_RIGHT, META_SIDE_TOP, _MetaEdge::rect, and _MetaEdge::side_type.
meta_rectangle_edge_cmp()
gint meta_rectangle_edge_cmp (gconstpointer a, gconstpointer b)
Definition at line 1378 of file boxes.c.
References b, meta_rectangle_edge_cmp_ignore_type(), and _MetaEdge::side_type.
Referenced by meta_rectangle_find_nonintersected_xinerama_edges(), and meta_rectangle_find_onscreen_edges().
meta_rectangle_edge_cmp_ignore_type()
gint meta_rectangle_edge_cmp_ignore_type (gconstpointer a, gconstpointer b)
Definition at line 1335 of file boxes.c.
References b, _MetaRectangle::height, META_SIDE_BOTTOM, META_SIDE_LEFT, META_SIDE_RIGHT, META_SIDE_TOP, _MetaEdge::rect, _MetaEdge::side_type, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_rectangle_edge_cmp().
meta_rectangle_edge_list_to_string()
char * meta_rectangle_edge_list_to_string (GList * edge_list, const char * separator_string, char * output)
Definition at line 98 of file boxes.c.
References EDGE_LENGTH, _MetaEdge::edge_type, _MetaRectangle::height, NULL, _MetaEdge::rect, _MetaEdge::side_type, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
meta_rectangle_edge_to_string()
char * meta_rectangle_edge_to_string (const MetaEdge * edge, char * output)
Definition at line 80 of file boxes.c.
References EDGE_LENGTH, _MetaEdge::edge_type, _MetaRectangle::height, _MetaEdge::rect, _MetaEdge::side_type, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
meta_rectangle_equal()
gboolean meta_rectangle_equal (const MetaRectangle * src1, const MetaRectangle * src2)
Definition at line 191 of file boxes.c.
References _MetaRectangle::height, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_ui_resize_popup_set(), meta_window_move_resize_request(), and meta_window_update_struts().
meta_rectangle_expand_region()
GList * meta_rectangle_expand_region (GList * region, const int left_expand, const int right_expand, const int top_expand, const int bottom_expand)
Definition at line 671 of file boxes.c.
References meta_rectangle_expand_region_conditionally().
Referenced by meta_window_shove_titlebar_onscreen().
meta_rectangle_expand_region_conditionally()
GList * meta_rectangle_expand_region_conditionally (GList * region, const int left_expand, const int right_expand, const int top_expand, const int bottom_expand, const int min_x, const int min_y)
Definition at line 687 of file boxes.c.
References _MetaRectangle::height, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_rectangle_expand_region().
meta_rectangle_expand_to_avoiding_struts()
void meta_rectangle_expand_to_avoiding_struts (MetaRectangle * rect, const MetaRectangle * expand_to, const MetaDirection direction, const GSList * all_struts)
Definition at line 716 of file boxes.c.
References BOX_BOTTOM, BOX_LEFT, BOX_RIGHT, BOX_TOP, _MetaRectangle::height, META_DIRECTION_HORIZONTAL, META_DIRECTION_VERTICAL, meta_rectangle_overlap(), META_SIDE_BOTTOM, META_SIDE_LEFT, META_SIDE_RIGHT, META_SIDE_TOP, _MetaStrut::rect, _MetaStrut::side, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
meta_rectangle_find_linepoint_closest_to_point()
void meta_rectangle_find_linepoint_closest_to_point (double x1, double y1, double x2, double y2, double px, double py, double * valx, double * valy)
Definition at line 1086 of file boxes.c.
meta_rectangle_find_nonintersected_xinerama_edges()
GList * meta_rectangle_find_nonintersected_xinerama_edges (const MetaRectangle * screen_rect, const GList * xinerama_rects, const GSList * all_struts)
Definition at line 1801 of file boxes.c.
References BOX_BOTTOM, BOX_LEFT, BOX_RIGHT, BOX_TOP, _MetaEdge::edge_type, _MetaRectangle::height, META_EDGE_XINERAMA, meta_rect(), meta_rectangle_edge_cmp(), meta_rectangle_remove_intersections_with_boxes_from_edges(), META_SIDE_BOTTOM, META_SIDE_LEFT, META_SIDE_RIGHT, META_SIDE_TOP, NULL, _MetaEdge::rect, _MetaEdge::side_type, and _MetaRectangle::width.
meta_rectangle_find_onscreen_edges()
GList * meta_rectangle_find_onscreen_edges (const MetaRectangle * basic_rect, const GSList * all_struts)
Definition at line 1719 of file boxes.c.
References FALSE, meta_rectangle_edge_cmp(), NULL, and TRUE.
meta_rectangle_get_minimal_spanning_set_for_region()
GList * meta_rectangle_get_minimal_spanning_set_for_region (const MetaRectangle * basic_rect, const GSList * all_struts, gboolean skip_middle_struts)
Definition at line 523 of file boxes.c.
References BOX_BOTTOM, BOX_LEFT, BOX_RIGHT, BOX_TOP, _MetaStrut::edge, _MetaRectangle::height, META_EDGE_XINERAMA, meta_rectangle_overlap(), META_SIDE_BOTTOM, META_SIDE_LEFT, META_SIDE_RIGHT, META_SIDE_TOP, NULL, _MetaStrut::rect, _MetaStrut::side, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
meta_rectangle_horiz_overlap()
gboolean meta_rectangle_horiz_overlap (const MetaRectangle * rect1, const MetaRectangle * rect2)
Definition at line 256 of file boxes.c.
References _MetaRectangle::width, and _MetaRectangle::x.
Referenced by meta_screen_get_xinerama_neighbor().
meta_rectangle_intersect()
gboolean meta_rectangle_intersect (const MetaRectangle * src1, const MetaRectangle * src2, MetaRectangle * dest)
Definition at line 154 of file boxes.c.
References dest, FALSE, _MetaRectangle::height, MAX, MIN, NULL, TRUE, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_rectangle_clip_to_region(), meta_screen_get_xinerama_for_rect(), meta_window_get_work_area_all_xineramas(), meta_window_place(), and meta_window_titlebar_is_onscreen().
meta_rectangle_overlap()
gboolean meta_rectangle_overlap (const MetaRectangle * rect1, const MetaRectangle * rect2)
Definition at line 235 of file boxes.c.
References FALSE, _MetaRectangle::height, NULL, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_rectangle_expand_to_avoiding_struts(), meta_rectangle_get_minimal_spanning_set_for_region(), meta_rectangle_overlaps_with_region(), and meta_window_set_demands_attention().
meta_rectangle_overlaps_with_region()
gboolean meta_rectangle_overlaps_with_region (const GList * spanning_rects, const MetaRectangle * rect)
Definition at line 821 of file boxes.c.
References FALSE, meta_rectangle_overlap(), and NULL.
meta_rectangle_region_to_string()
char * meta_rectangle_region_to_string (GList * region, const char * separator_string, char * output)
Definition at line 48 of file boxes.c.
References _MetaRectangle::height, NULL, RECT_LENGTH, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
meta_rectangle_remove_intersections_with_boxes_from_edges()
GList * meta_rectangle_remove_intersections_with_boxes_from_edges (GList * edges, const GSList * rectangles)
Definition at line 1655 of file boxes.c.
References FALSE, and TRUE.
Referenced by meta_rectangle_find_nonintersected_xinerama_edges().
meta_rectangle_resize_with_gravity()
void meta_rectangle_resize_with_gravity (const MetaRectangle * old_rect, MetaRectangle * rect, int gravity, int new_width, int new_height)
Definition at line 283 of file boxes.c.
References _MetaRectangle::height, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_window_edge_resistance_for_resize().
meta_rectangle_shove_into_region()
void meta_rectangle_shove_into_region (const GList * spanning_rects, FixedDirections fixed_directions, MetaRectangle * rect)
Definition at line 986 of file boxes.c.
References FIXED_DIRECTION_X, FIXED_DIRECTION_Y, _MetaRectangle::height, meta_warning(), MIN, NULL, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_window_shove_titlebar_onscreen().
meta_rectangle_to_string()
char * meta_rectangle_to_string (const MetaRectangle * rect, char * output)
Definition at line 34 of file boxes.c.
References _MetaRectangle::height, RECT_LENGTH, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
meta_rectangle_union()
void meta_rectangle_union (const MetaRectangle * rect1, const MetaRectangle * rect2, MetaRectangle * dest)
Definition at line 201 of file boxes.c.
References dest, _MetaRectangle::height, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
meta_rectangle_vert_overlap()
gboolean meta_rectangle_vert_overlap (const MetaRectangle * rect1, const MetaRectangle * rect2)
Definition at line 248 of file boxes.c.
References _MetaRectangle::height, and _MetaRectangle::y.
Referenced by meta_screen_get_xinerama_neighbor().