MATE Desktop Environment: cact-tree-model-dnd.c File Reference
cact-tree-model-dnd.c File Reference
#include <glib.h>
#include <glib/gi18n.h>
#include <string.h>
#include <api/na-core-utils.h>
#include <api/na-object-api.h>
#include <core/na-importer.h>
#include "cact-application.h"
#include "cact-clipboard.h"
#include "cact-main-statusbar.h"
#include "cact-main-window.h"
#include "cact-tree-model.h"
#include "cact-tree-model-priv.h"
#include "cact-tree-ieditable.h"
Macros
#define MAX_XDS_ATOM_VAL_LEN 4096
#define TEXT_ATOM gdk_atom_intern("text/plain", FALSE)
#define XDS_ATOM gdk_atom_intern("XdndDirectSave0", FALSE)
#define XDS_FILENAME "xds.txt"
Functions
gboolean cact_tree_model_dnd_idrag_dest_drag_data_received (GtkTreeDragDest *drag_dest, GtkTreePath *dest, GtkSelectionData *selection_data)
gboolean cact_tree_model_dnd_idrag_dest_row_drop_possible (GtkTreeDragDest *drag_dest, GtkTreePath *dest_path, GtkSelectionData *selection_data)
gboolean cact_tree_model_dnd_imulti_drag_source_drag_data_get (EggTreeMultiDragSource *drag_source, GdkDragContext *context, GtkSelectionData *selection_data, GList *rows, guint info)
gboolean cact_tree_model_dnd_imulti_drag_source_drag_data_delete (EggTreeMultiDragSource *drag_source, GList *rows)
GdkDragAction cact_tree_model_dnd_imulti_drag_source_get_drag_actions (EggTreeMultiDragSource *drag_source)
GtkTargetList * cact_tree_model_dnd_imulti_drag_source_get_format_list (EggTreeMultiDragSource *drag_source)
gboolean cact_tree_model_dnd_imulti_drag_source_row_draggable (EggTreeMultiDragSource *drag_source, GList *rows)
void cact_tree_model_dnd_on_drag_begin (GtkWidget *widget, GdkDragContext *context, BaseWindow *window)
void cact_tree_model_dnd_on_drag_end (GtkWidget *widget, GdkDragContext *context, BaseWindow *window)
Variables
GtkTargetEntry tree_model_dnd_dest_formats []
guint tree_model_dnd_dest_formats_count = G_N_ELEMENTS(tree_model_dnd_dest_formats)
Macro Definition Documentation
MAX_XDS_ATOM_VAL_LEN
#define MAX_XDS_ATOM_VAL_LEN 4096
Definition at line 83 of file cact-tree-model-dnd.c.
TEXT_ATOM
#define TEXT_ATOM gdk_atom_intern("text/plain", FALSE)
Definition at line 84 of file cact-tree-model-dnd.c.
Referenced by cact_tree_model_dnd_on_drag_begin().
XDS_ATOM
#define XDS_ATOM gdk_atom_intern("XdndDirectSave0", FALSE)
Definition at line 85 of file cact-tree-model-dnd.c.
Referenced by cact_tree_model_dnd_on_drag_begin(), and cact_tree_model_dnd_on_drag_end().
XDS_FILENAME
#define XDS_FILENAME "xds.txt"
Definition at line 86 of file cact-tree-model-dnd.c.
Referenced by cact_tree_model_dnd_on_drag_begin().
Function Documentation
cact_tree_model_dnd_idrag_dest_drag_data_received()
gboolean cact_tree_model_dnd_idrag_dest_drag_data_received (GtkTreeDragDest * drag_dest, GtkTreePath * dest, GtkSelectionData * selection_data)
cact_tree_model_dnd_idrag_dest_drag_data_received: @drag_dest: @dest: @selection_data:
Called when a drop occurs in the treeview; this may be an import action from the outside world, or a move/copy inside of the tree.
Returns: TRUE if the specified rows were successfully inserted at the given dest, FALSE else.
When importing:
selection=XdndSelection
target=text/uri-list
type=text/uri-list
When moving/copy from the treeview to the treeview:
selection=XdndSelection
target=XdndCajaActions
type=XdndCajaActions
Definition at line 157 of file cact-tree-model-dnd.c.
References CACT_IS_TREE_MODEL, CACT_TREE_MODEL, CACT_XCHANGE_FORMAT_CACT, CACT_XCHANGE_FORMAT_URI_LIST, dest, and FALSE.
cact_tree_model_dnd_idrag_dest_row_drop_possible()
gboolean cact_tree_model_dnd_idrag_dest_row_drop_possible (GtkTreeDragDest * drag_dest, GtkTreePath * dest_path, GtkSelectionData * selection_data)
cact_tree_model_dnd_idrag_dest_row_drop_possible: @drag_dest: @dest_path: @selection_data:
Seems to only be called when the drop in on a row (a square is displayed), but not when dropped between two rows (a line is displayed), nor during the motion.
Definition at line 240 of file cact-tree-model-dnd.c.
References TRUE.
cact_tree_model_dnd_imulti_drag_source_drag_data_delete()
gboolean cact_tree_model_dnd_imulti_drag_source_drag_data_delete (EggTreeMultiDragSource * drag_source, GList * rows)
cact_tree_model_dnd_imulti_drag_source_drag_data_delete: @drag_source: @rows:
Definition at line 382 of file cact-tree-model-dnd.c.
References TRUE.
cact_tree_model_dnd_imulti_drag_source_drag_data_get()
gboolean cact_tree_model_dnd_imulti_drag_source_drag_data_get (EggTreeMultiDragSource * drag_source, GdkDragContext * context, GtkSelectionData * selection_data, GList * rows, guint info)
cact_tree_model_dnd_imulti_drag_source_drag_data_get: @context: contains
the suggested action, as chosen by the drop site, between those we have provided in imulti_drag_source_get_drag_actions()
the target folder (XDS protocol) @selection_data: @rows: list of row references which are to be dropped @info: the suggested format, as chosen by the drop site, between those we have provided in imulti_drag_source_get_target_list()
This function is called when we release the selected items onto the destination
CACT_XCHANGE_FORMAT_CACT: internal format for drag and drop inside the treeview:
copy in the clipboard the list of row references
selection data is empty
CACT_XCHANGE_FORMAT_XDS: exchange format to drop to outside:
copy in the clipboard the list of row references
set the destination folder
selection data is 'success' or 'failure'
CACT_XCHANGE_FORMAT_APPLICATION_XML: CACT_XCHANGE_FORMAT_TEXT_PLAIN: exchange format to export to outside:
do not use dnd clipboard
selection data receives the export in text format
Returns: TRUE if required data was actually provided by the source, FALSE else.
Definition at line 284 of file cact-tree-model-dnd.c.
References cact_clipboard_dnd_get_text(), cact_clipboard_dnd_set(), CACT_TREE_MODEL, CACT_XCHANGE_FORMAT_APPLICATION_XML, CACT_XCHANGE_FORMAT_CACT, CACT_XCHANGE_FORMAT_TEXT_PLAIN, CACT_XCHANGE_FORMAT_XDS, data, FALSE, na_core_utils_dir_is_writable_uri(), NULL, and TRUE.
cact_tree_model_dnd_imulti_drag_source_get_drag_actions()
GdkDragAction cact_tree_model_dnd_imulti_drag_source_get_drag_actions (EggTreeMultiDragSource * drag_source)
cact_tree_model_dnd_imulti_drag_source_get_drag_actions: @drag_source:
Definition at line 396 of file cact-tree-model-dnd.c.
cact_tree_model_dnd_imulti_drag_source_get_format_list()
GtkTargetList * cact_tree_model_dnd_imulti_drag_source_get_format_list (EggTreeMultiDragSource * drag_source)
Definition at line 402 of file cact-tree-model-dnd.c.
cact_tree_model_dnd_imulti_drag_source_row_draggable()
gboolean cact_tree_model_dnd_imulti_drag_source_row_draggable (EggTreeMultiDragSource * drag_source, GList * rows)
cact_tree_model_dnd_imulti_drag_source_row_draggable: @drag_source: @rows:
All selectable rows are draggable. Nonetheless, it's a good place to store the dragged row references. We only make use of them in on_drag_motion handler.
Definition at line 421 of file cact-tree-model-dnd.c.
References CACT_IS_TREE_MODEL, CACT_TREE_MODEL, FALSE, NA_IS_OBJECT_PROFILE, TREE_COLUMN_NAOBJECT, and TRUE.
cact_tree_model_dnd_on_drag_begin()
void cact_tree_model_dnd_on_drag_begin (GtkWidget * widget, GdkDragContext * context, BaseWindow * window)
cact_tree_model_dnd_on_drag_begin: @widget: the GtkTreeView from which item is to be dragged. @context: @window: the parent CactMainWindow instance.
This function is called once, at the beginning of the drag operation, when we are dragging from the IActionsList treeview.
Definition at line 472 of file cact-tree-model-dnd.c.
References cact_clipboard_dnd_clear(), CACT_IS_TREE_MODEL, FALSE, TEXT_ATOM, XDS_ATOM, and XDS_FILENAME.
cact_tree_model_dnd_on_drag_end()
void cact_tree_model_dnd_on_drag_end (GtkWidget * widget, GdkDragContext * context, BaseWindow * window)
cact_tree_model_dnd_on_drag_end: @widget: @context: @window:
Definition at line 511 of file cact-tree-model-dnd.c.
References cact_clipboard_dnd_clear(), cact_clipboard_dnd_drag_end(), CACT_IS_TREE_MODEL, and XDS_ATOM.
Variable Documentation
tree_model_dnd_dest_formats
GtkTargetEntry tree_model_dnd_dest_formats[]
Initial value:
                                           = {
    { "XdndCajaActions", 0, CACT_XCHANGE_FORMAT_CACT },
    { "text/uri-list",       0, CACT_XCHANGE_FORMAT_URI_LIST },
    { "application/xml",     0, CACT_XCHANGE_FORMAT_APPLICATION_XML },
    { "text/plain",          0, CACT_XCHANGE_FORMAT_TEXT_PLAIN },
}
Definition at line 108 of file cact-tree-model-dnd.c.
tree_model_dnd_dest_formats_count
guint tree_model_dnd_dest_formats_count = G_N_ELEMENTS(tree_model_dnd_dest_formats)
Definition at line 115 of file cact-tree-model-dnd.c.