MATE Desktop Environment: cact-assistant-export.c File Reference
cact-assistant-export.c File Reference
#include <glib/gi18n.h>
#include <string.h>
#include <api/na-core-utils.h>
#include <api/na-object-api.h>
#include <core/na-exporter.h>
#include <core/na-export-format.h>
#include <core/na-gtk-utils.h>
#include <core/na-ioptions-list.h>
#include "cact-application.h"
#include "cact-main-window.h"
#include "cact-assistant-export.h"
#include "cact-export-ask.h"
#include "cact-tree-view.h"
Enumerations
enum {
ASSIST_PAGE_INTRO = 0 , ASSIST_PAGE_ACTIONS_SELECTION , ASSIST_PAGE_FOLDER_SELECTION , ASSIST_PAGE_FORMAT_SELECTION ,
ASSIST_PAGE_CONFIRM , ASSIST_PAGE_DONE
}
Functions
GType cact_assistant_export_get_type (void)
void cact_assistant_export_run (BaseWindow *main_window)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ASSIST_PAGE_INTRO
ASSIST_PAGE_ACTIONS_SELECTION
ASSIST_PAGE_FOLDER_SELECTION
ASSIST_PAGE_FORMAT_SELECTION
ASSIST_PAGE_CONFIRM
ASSIST_PAGE_DONE
Definition at line 63 of file cact-assistant-export.c.
Function Documentation
cact_assistant_export_get_type()
GType cact_assistant_export_get_type (void)
Definition at line 128 of file cact-assistant-export.c.
cact_assistant_export_run()
void cact_assistant_export_run (BaseWindow * main_window)
Run the assistant.
@main: the main window of the application.
Definition at line 360 of file cact-assistant-export.c.
References BASE_PROP_HAS_OWN_BUILDER, BASE_PROP_PARENT, BASE_PROP_QUIT_ON_ESCAPE, BASE_PROP_TOPLEVEL_NAME, BASE_PROP_WARN_ON_ESCAPE, BASE_PROP_WSP_NAME, BASE_PROP_XMLUI_FILENAME, BASE_WINDOW, base_window_run(), CACT_IS_MAIN_WINDOW, CACT_TYPE_ASSISTANT_EXPORT, NA_IPREFS_ASSISTANT_ESC_CONFIRM, NA_IPREFS_ASSISTANT_ESC_QUIT, na_settings_get_boolean(), NULL, and TRUE.
Referenced by cact_menubar_tools_on_export().