MATE Desktop Environment: cact-main-statusbar.c File Reference
cact-main-statusbar.c File Reference
#include <core/na-io-provider.h>
#include "base-gtk-utils.h"
#include "cact-main-statusbar.h"
Macros
#define LOCKED_IMAGE PKGUIDIR "/locked.png"
Functions
void cact_main_statusbar_initialize_gtk_toplevel (CactMainWindow *window)
void cact_main_statusbar_display_status (CactMainWindow *window, const gchar *context, const gchar *status)
void cact_main_statusbar_display_with_timeout (CactMainWindow *window, const gchar *context, const gchar *status)
void cact_main_statusbar_hide_status (CactMainWindow *window, const gchar *context)
void cact_main_statusbar_set_locked (CactMainWindow *window, gboolean readonly, gint reason)
Macro Definition Documentation
LOCKED_IMAGE
#define LOCKED_IMAGE PKGUIDIR "/locked.png"
Definition at line 46 of file cact-main-statusbar.c.
Referenced by cact_main_statusbar_set_locked().
Function Documentation
cact_main_statusbar_display_status()
void cact_main_statusbar_display_status (CactMainWindow * window, const gchar * context, const gchar * status)
cact_main_statusbar_display_status: @window: the CactMainWindow instance. @context: the context to be displayed. @status: the message.
Push a message.
Definition at line 90 of file cact-main-statusbar.c.
cact_main_statusbar_display_with_timeout()
void cact_main_statusbar_display_with_timeout (CactMainWindow * window, const gchar * context, const gchar * status)
cact_main_statusbar_display_with_timeout: @window: the CactMainWindow instance. @context: the context to be displayed. @status: the message.
Push a message. Automatically pop it after a timeout. The timeout is not suspended when another message is pushed onto the previous one.
Definition at line 121 of file cact-main-statusbar.c.
cact_main_statusbar_hide_status()
void cact_main_statusbar_hide_status (CactMainWindow * window, const gchar * context)
cact_main_statusbar_hide_status: @window: the CactMainWindow instance. @context: the context to be hidden.
Hide the specified context.
Definition at line 159 of file cact-main-statusbar.c.
cact_main_statusbar_initialize_gtk_toplevel()
void cact_main_statusbar_initialize_gtk_toplevel (CactMainWindow * window)
cact_main_statusbar_initialize_gtk_toplevel: @window: the CactMainWindow.
Initial loading of the UI.
Definition at line 59 of file cact-main-statusbar.c.
References BASE_WINDOW, and base_window_get_widget().
cact_main_statusbar_set_locked()
void cact_main_statusbar_set_locked (CactMainWindow * window, gboolean readonly, gint reason)
cact_main_statusbar_set_locked: @window: the CactMainWindow instance. @provider: whether the current provider is locked (read-only). @item: whether the current item is locked (read-only).
Displays the writability status of the current item as an image. Installs the corresponding tooltip.
Definition at line 181 of file cact-main-statusbar.c.
References base_gtk_utils_render(), BASE_WINDOW, base_window_get_widget(), FALSE, LOCKED_IMAGE, na_io_provider_get_readonly_tooltip(), NULL, and TRUE.