MATE Desktop Environment: cact-main-tab.h File Reference
cact-main-tab.h File Reference
#include <api/na-icontext.h>
#include "cact-main-window.h"
Macros
#define TAB_UPDATABLE_SIGNAL_ITEM_UPDATED "cact-tab-updatable-item-updated"
Enumerations
enum {
TAB_ACTION = 0 , TAB_COMMAND , TAB_EXECUTION , TAB_BASENAMES ,
TAB_MIMETYPES , TAB_FOLDERS , TAB_SCHEMES , TAB_CAPABILITIES ,
TAB_ENVIRONMENT , TAB_PROPERTIES
}
Functions
void cact_main_tab_init (CactMainWindow *window, gint page)
void cact_main_tab_enable_page (CactMainWindow *window, gint page, gboolean enabled)
gboolean cact_main_tab_is_page_enabled (CactMainWindow *window, gint page)
Macro Definition Documentation
TAB_UPDATABLE_SIGNAL_ITEM_UPDATED
#define TAB_UPDATABLE_SIGNAL_ITEM_UPDATED "cact-tab-updatable-item-updated"
SECTION: cact_main_tab @short_description: Signals and properties. cact/cact-main-tab.h
Here as defined signals and properties common to all tabs.
Definition at line 49 of file cact-main-tab.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TAB_ACTION
TAB_COMMAND
TAB_EXECUTION
TAB_BASENAMES
TAB_MIMETYPES
TAB_FOLDERS
TAB_SCHEMES
TAB_CAPABILITIES
TAB_ENVIRONMENT
TAB_PROPERTIES
Definition at line 53 of file cact-main-tab.h.
Function Documentation
cact_main_tab_enable_page()
void cact_main_tab_enable_page (CactMainWindow * window, gint num_page, gboolean enabled)
cact_main_tab_enable_page: @window: the CactMainWindow. @num_page: the page number, starting from zero. @enabled: whether the tab should be set sensitive or not.
Set the sensitivity of the tab.
Definition at line 67 of file cact-main-tab.c.
References BASE_WINDOW, base_window_get_widget(), and label.
cact_main_tab_init()
void cact_main_tab_init (CactMainWindow * window, gint num_page)
cact_main_tab_init: @window: the CactMainWindow. @num_page: the page number, starting from zero.
Common initialization of each page of the notebook.
Definition at line 48 of file cact-main-tab.c.
References BASE_SIGNAL_INITIALIZE_WINDOW, BASE_WINDOW, and base_window_signal_connect_with_data().
Referenced by cact_iaction_tab_init(), cact_ibasenames_tab_init(), cact_icapabilities_tab_init(), cact_icommand_tab_init(), cact_ienvironment_tab_init(), cact_iexecution_tab_init(), cact_ifolders_tab_init(), cact_imimetypes_tab_init(), cact_iproperties_tab_init(), and cact_ischemes_tab_init().
cact_main_tab_is_page_enabled()
gboolean cact_main_tab_is_page_enabled (CactMainWindow * window, gint num_page)
cact_main_tab_is_page_enabled: @window: the CactMainWindow. @num_page: the page number, starting from zero.
Returns: TRUE if the tab is sensitive, FALSE else.
Definition at line 88 of file cact-main-tab.c.
References BASE_WINDOW, and base_window_get_widget().