MATE Desktop Environment: cact-iaction-tab.c File Reference
cact-iaction-tab.c File Reference
#include <glib/gi18n.h>
#include <string.h>
#include <api/na-core-utils.h>
#include <api/na-object-api.h>
#include <core/na-io-provider.h>
#include "base-window.h"
#include "cact-application.h"
#include "cact-main-statusbar.h"
#include "base-gtk-utils.h"
#include "cact-main-tab.h"
#include "cact-iaction-tab.h"
#include "cact-icon-chooser.h"
Macros
#define IACTION_TAB_CONTEXT "cact-iaction-tab-context"
#define IACTION_TAB_PROP_DATA "cact-iaction-tab-data"
Functions
GType cact_iaction_tab_get_type (void)
void cact_iaction_tab_init (CactIActionTab *instance)
gboolean cact_iaction_tab_has_label (CactIActionTab *instance)
Macro Definition Documentation
IACTION_TAB_CONTEXT
#define IACTION_TAB_CONTEXT "cact-iaction-tab-context"
Definition at line 58 of file cact-iaction-tab.c.
IACTION_TAB_PROP_DATA
#define IACTION_TAB_PROP_DATA "cact-iaction-tab-data"
Definition at line 67 of file cact-iaction-tab.c.
Function Documentation
cact_iaction_tab_get_type()
GType cact_iaction_tab_get_type (void)
Definition at line 100 of file cact-iaction-tab.c.
cact_iaction_tab_has_label()
gboolean cact_iaction_tab_has_label (CactIActionTab * instance)
cact_iaction_tab_has_label: @window: this CactIActionTab instance.
An action or a menu can only be written if it has at least a label.
Returns TRUE if the label of the action or of the menu is not empty.
Definition at line 352 of file cact-iaction-tab.c.
References BASE_WINDOW, base_window_get_widget(), CACT_IS_IACTION_TAB, FALSE, and label.
cact_iaction_tab_init()
void cact_iaction_tab_init (CactIActionTab * instance)
cact_iaction_tab_init: @instance: this CactIActionTab instance.
Initialize the interface Connect to BaseWindow signals
Definition at line 176 of file cact-iaction-tab.c.
References BASE_SIGNAL_INITIALIZE_GTK, BASE_SIGNAL_INITIALIZE_WINDOW, BASE_WINDOW, base_window_signal_connect(), CACT_IS_IACTION_TAB, cact_main_tab_init(), CACT_MAIN_WINDOW, data, FALSE, NULL, and TAB_ACTION.