MATE Desktop Environment: cact-menubar-edit.c File Reference
cact-menubar-edit.c File Reference
#include <glib/gi18n.h>
#include <api/na-core-utils.h>
#include <core/na-io-provider.h>
#include "cact-application.h"
#include "cact-main-tab.h"
#include "cact-menubar-priv.h"
#include "cact-preferences-editor.h"
#include "cact-tree-ieditable.h"
Functions
void cact_menubar_edit_on_update_sensitivities (const CactMenubar *bar)
void cact_menubar_edit_on_cut (GtkAction *gtk_action, BaseWindow *window)
void cact_menubar_edit_on_copy (GtkAction *gtk_action, BaseWindow *window)
void cact_menubar_edit_on_paste (GtkAction *gtk_action, BaseWindow *window)
void cact_menubar_edit_on_paste_into (GtkAction *gtk_action, BaseWindow *window)
void cact_menubar_edit_on_duplicate (GtkAction *gtk_action, BaseWindow *window)
void cact_menubar_edit_on_delete (GtkAction *gtk_action, BaseWindow *window)
void cact_menubar_edit_on_reload (GtkAction *gtk_action, BaseWindow *window)
void cact_menubar_edit_on_prefererences (GtkAction *gtk_action, BaseWindow *window)
Function Documentation
cact_menubar_edit_on_copy()
void cact_menubar_edit_on_copy (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_edit_on_copy: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
copies the visible selection
(tree) get new refs on selected items
(menu) install in clipboard a copy of selected objects renumbering actions/menus id to ensure unicity at paste time
(menu) release refs on selected items
(menu) refresh actions sensitivy (as selection doesn't change)
Definition at line 252 of file cact-menubar-edit.c.
References BAR_WINDOW_VOID, cact_clipboard_primary_set(), CACT_IS_MAIN_WINDOW, CACT_MAIN_WINDOW, cact_main_window_get_clipboard(), CLIPBOARD_MODE_COPY, MENUBAR_SIGNAL_UPDATE_SENSITIVITIES, and CactClipboard::private.
cact_menubar_edit_on_cut()
void cact_menubar_edit_on_cut (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_edit_on_cut: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Cut objects are installed both in the clipboard and in the deleted list. Parent pointer is reset to NULL. Old parent status is re-checked by the tree model delete operation. When pasting later these cut objects:
the first time, we paste the very same object, removing it from the deleted list, attaching it to a new parent the object itself is not modified, but the parent is.
the following times, we paste a copy of this object with a new identifier
cuts the visible selection
(tree) get new refs on selected items
(main) add selected items to main list of deleted, moving newref from list_from_tree to main_list_of_deleted
(menu) install in clipboard a copy of selected objects
(tree) remove selected items, unreffing objects
Definition at line 200 of file cact-menubar-edit.c.
References _, BAR_WINDOW_VOID, BASE_WINDOW, base_window_display_error_dlg(), cact_clipboard_primary_set(), CACT_MAIN_WINDOW, cact_main_window_get_clipboard(), cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_delete(), CLIPBOARD_MODE_CUT, na_core_utils_slist_free(), na_core_utils_slist_join_at_end(), na_object_copyref_items, na_object_free_items, NULL, and TREE_OPE_DELETE.
cact_menubar_edit_on_delete()
void cact_menubar_edit_on_delete (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_edit_on_delete: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
deletes the visible selection
(tree) get new refs on selected items
(tree) remove selected items, unreffing objects
(main) add selected items to main list of deleted, moving newref from list_from_tree to main_list_of_deleted
(tree) select next row (if any, or previous if any, or none)
note that we get from selection a list of trees, but we don't have yet ensured that each element of this tree is actually deletable each branch of this list must be recursively deletable in order this branch itself be deleted
Definition at line 448 of file cact-menubar-edit.c.
References _, BAR_WINDOW_VOID, BASE_WINDOW, base_window_display_error_dlg(), CACT_IS_MAIN_WINDOW, CACT_MAIN_WINDOW, cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_delete(), na_core_utils_slist_free(), na_core_utils_slist_join_at_end(), na_object_copyref_items, na_object_free_items, NULL, and TREE_OPE_DELETE.
cact_menubar_edit_on_duplicate()
void cact_menubar_edit_on_duplicate (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_edit_on_duplicate: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
duplicate is just as paste, with the difference that content comes from the current selection, instead of coming from the clipboard
this is nonetheless a bit more complicated because when we duplicate some items (e.g. a multiple selection), we expect to see the new items just besides the original ones...
Definition at line 388 of file cact-menubar-edit.c.
References action, BAR_WINDOW_VOID, CACT_IS_MAIN_WINDOW, CACT_MAIN_WINDOW, cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_insert_items(), DUPLICATE_REC, NA_IS_OBJECT_PROFILE, NA_OBJECT, NA_OBJECT_ACTION, na_object_check_status, na_object_copyref_items, na_object_duplicate, na_object_free_items, na_object_get_parent, na_object_prepare_for_paste, na_object_set_origin, na_updater_should_pasted_be_relabeled(), NULL, and TRUE.
cact_menubar_edit_on_paste()
void cact_menubar_edit_on_paste (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_edit_on_paste: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
pastes the current content of the clipboard at the current position (same path, same level)
(menu) get from clipboard a copy of installed items the clipboard will return a new copy and renumber its own data for allowing a new paste
(tree) insert new items, the tree store will ref them attaching each item to its parent recursively checking edition status of the topmost parent selecting the first item at end
(menu) unreffing the copy got from clipboard
Definition at line 287 of file cact-menubar-edit.c.
References CACT_MAIN_WINDOW, cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_insert_items(), na_object_free_items, and NULL.
cact_menubar_edit_on_paste_into()
void cact_menubar_edit_on_paste_into (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_edit_on_paste_into: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
pastes the current content of the clipboard as the first child of currently selected item
(menu) get from clipboard a copy of installed items the clipboard will return a new copy and renumber its own data for allowing a new paste
(tree) insert new items, the tree store will ref them attaching each item to its parent recursively checking edition status of the topmost parent selecting the first item at end
(menu) unreffing the copy got from clipboard
Definition at line 321 of file cact-menubar-edit.c.
References CACT_MAIN_WINDOW, cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_insert_into(), and na_object_free_items.
cact_menubar_edit_on_prefererences()
void cact_menubar_edit_on_prefererences (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_edit_on_preferences: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Edit preferences.
Definition at line 609 of file cact-menubar-edit.c.
References cact_preferences_editor_run().
cact_menubar_edit_on_reload()
void cact_menubar_edit_on_reload (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_edit_on_reload: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Reload items from I/O storage subsystems.
Definition at line 596 of file cact-menubar-edit.c.
References CACT_MAIN_WINDOW, and cact_main_window_reload().
cact_menubar_edit_on_update_sensitivities()
void cact_menubar_edit_on_update_sensitivities (const CactMenubar * bar)
cact_menubar_edit_on_update_sensitivities: @bar: this CactMenubar object.
Update sensitivity of items of the Edit menu.
Each action (cut, copy, delete, etc.) takes itself care of whether it can safely apply to all the selection or not. The action can at least assume that at least one item will be a valid candidate (this is the Menubar rule).
Definition at line 64 of file cact-menubar-edit.c.
References _CactMenubarPrivate::are_items_writable, _CactMenubarPrivate::are_parents_writable, cact_menubar_enable_item(), _CactMenubarPrivate::clipboard_actions, _CactMenubarPrivate::clipboard_menus, _CactMenubarPrivate::clipboard_profiles, _CactMenubarPrivate::count_selected, _CactMenubarPrivate::has_writable_providers, _CactMenubarPrivate::is_action_writable, _CactMenubarPrivate::is_level_zero_writable, _CactMenubarPrivate::is_parent_writable, NA_IS_OBJECT_ACTION, NA_IS_OBJECT_MENU, NA_OBJECT, na_object_get_parent, na_object_is_finally_writable, NULL, _CactMenubarPrivate::popup_handler, CactMenubar::private, _CactMenubarPrivate::selected_items, and _CactMenubarPrivate::treeview_has_focus.