MATE Desktop Environment: cact-tree-view.h File Reference
cact-tree-view.h File Reference
#include <api/na-object-item.h>
#include "base-window.h"
Classes
struct CactTreeView
struct CactTreeViewClass
Macros
#define CACT_TYPE_TREE_VIEW (cact_tree_view_get_type())
#define CACT_TREE_VIEW(object)
#define CACT_TREE_VIEW_CLASS(klass)
#define CACT_IS_TREE_VIEW(object)
#define CACT_IS_TREE_VIEW_CLASS(klass)
#define CACT_TREE_VIEW_GET_CLASS(object)
#define TREE_PROP_WINDOW "tree-prop-window"
#define TREE_PROP_PARENT "tree-prop-parent"
#define TREE_PROP_WIDGET_NAME "tree-prop-widget-name"
#define TREE_PROP_MODE "tree-prop-mode"
#define TREE_PROP_NOTIFY_ALLOWED "tree-prop-notify-allowed"
#define TREE_SIGNAL_COUNT_CHANGED "tree-signal-count-changed"
#define TREE_SIGNAL_FOCUS_IN "tree-signal-focus-in"
#define TREE_SIGNAL_FOCUS_OUT "tree-signal-focus-out"
#define TREE_SIGNAL_LEVEL_ZERO_CHANGED "tree-signal-level-zero-changed"
#define TREE_SIGNAL_MODIFIED_STATUS_CHANGED "tree-signal-modified-status-changed"
#define WINDOW_DATA_TREE_VIEW "window-data-tree-view"
Typedefs
typedef struct _CactTreeViewPrivate CactTreeViewPrivate
typedef struct _CactTreeViewClassPrivate CactTreeViewClassPrivate
Enumerations
enum CactTreeMode { TREE_MODE_EDITION = 0 , TREE_MODE_SELECTION , TREE_MODE_N_MODES }
enum { TREE_LIST_SELECTED = 1<<0 , TREE_LIST_MODIFIED = 1<<1 , TREE_LIST_ALL = 1<<7 , TREE_LIST_DELETED = 1<<8 }
Functions
GType cact_tree_view_get_type (void)
CactTreeView * cact_tree_view_new (BaseWindow *window, GtkContainer *parent, const gchar *treeview_name, CactTreeMode mode)
void cact_tree_view_fill (CactTreeView *view, GList *items)
gboolean cact_tree_view_are_notify_allowed (const CactTreeView *view)
void cact_tree_view_set_notify_allowed (CactTreeView *view, gboolean allow)
void cact_tree_view_collapse_all (const CactTreeView *view)
void cact_tree_view_expand_all (const CactTreeView *view)
NAObjectItem * cact_tree_view_get_item_by_id (const CactTreeView *view, const gchar *id)
GList * cact_tree_view_get_items (const CactTreeView *view)
GList * cact_tree_view_get_items_ex (const CactTreeView *view, guint mode)
void cact_tree_view_select_row_at_path (CactTreeView *view, GtkTreePath *path)
Macro Definition Documentation
CACT_IS_TREE_VIEW
#define CACT_IS_TREE_VIEW (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE(object, CACT_TYPE_TREE_VIEW))
Definition at line 59 of file cact-tree-view.h.
Referenced by cact_tree_view_are_notify_allowed(), cact_tree_view_collapse_all(), cact_tree_view_expand_all(), cact_tree_view_fill(), cact_tree_view_get_item_by_id(), cact_tree_view_get_items_ex(), cact_tree_view_select_row_at_path(), and cact_tree_view_set_notify_allowed().
CACT_IS_TREE_VIEW_CLASS
#define CACT_IS_TREE_VIEW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass), CACT_TYPE_TREE_VIEW))
Definition at line 60 of file cact-tree-view.h.
CACT_TREE_VIEW
#define CACT_TREE_VIEW (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST(object, CACT_TYPE_TREE_VIEW, CactTreeView))
Definition at line 57 of file cact-tree-view.h.
Referenced by cact_tree_ieditable_delete(), cact_tree_ieditable_insert_at_path(), cact_tree_ieditable_insert_into(), and cact_tree_ieditable_set_items().
CACT_TREE_VIEW_CLASS
#define CACT_TREE_VIEW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST(klass, CACT_TYPE_TREE_VIEW, CactTreeViewClass))
Definition at line 58 of file cact-tree-view.h.
CACT_TREE_VIEW_GET_CLASS
#define CACT_TREE_VIEW_GET_CLASS (object)
Value:
(G_TYPE_INSTANCE_GET_CLASS((object), CACT_TYPE_TREE_VIEW, CactTreeViewClass))
Definition at line 61 of file cact-tree-view.h.
CACT_TYPE_TREE_VIEW
#define CACT_TYPE_TREE_VIEW (cact_tree_view_get_type())
Definition at line 56 of file cact-tree-view.h.
Referenced by cact_tree_view_new().
TREE_PROP_MODE
#define TREE_PROP_MODE "tree-prop-mode"
Definition at line 94 of file cact-tree-view.h.
TREE_PROP_NOTIFY_ALLOWED
#define TREE_PROP_NOTIFY_ALLOWED "tree-prop-notify-allowed"
Definition at line 95 of file cact-tree-view.h.
TREE_PROP_PARENT
#define TREE_PROP_PARENT "tree-prop-parent"
Definition at line 92 of file cact-tree-view.h.
Referenced by cact_tree_view_new().
TREE_PROP_WIDGET_NAME
#define TREE_PROP_WIDGET_NAME "tree-prop-widget-name"
Definition at line 93 of file cact-tree-view.h.
Referenced by cact_tree_view_new().
TREE_PROP_WINDOW
#define TREE_PROP_WINDOW "tree-prop-window"
Properties defined by the CactTreeView class. They should be provided at object instantiation time.
@TREE_PROP_WINDOW: the BaseWindow. @TREE_PROP_PARENT: the widget which is parent of this tree view. @TREE_PROP_WIDGET_NAME: the tree view widget name. @TREE_PROP_MODE: management mode. @TREE_PROP_NOTIFY_ALLOWED: whether notifications are allowed.
Definition at line 91 of file cact-tree-view.h.
Referenced by cact_tree_model_new(), and cact_tree_view_new().
TREE_SIGNAL_COUNT_CHANGED
#define TREE_SIGNAL_COUNT_CHANGED "tree-signal-count-changed"
Signals emitted by the CactTreeView instance.
Definition at line 100 of file cact-tree-view.h.
Referenced by cact_tree_view_fill().
TREE_SIGNAL_FOCUS_IN
#define TREE_SIGNAL_FOCUS_IN "tree-signal-focus-in"
Definition at line 101 of file cact-tree-view.h.
TREE_SIGNAL_FOCUS_OUT
#define TREE_SIGNAL_FOCUS_OUT "tree-signal-focus-out"
Definition at line 102 of file cact-tree-view.h.
TREE_SIGNAL_LEVEL_ZERO_CHANGED
#define TREE_SIGNAL_LEVEL_ZERO_CHANGED "tree-signal-level-zero-changed"
Definition at line 103 of file cact-tree-view.h.
Referenced by cact_menubar_file_save_items(), cact_tree_ieditable_initialize(), and cact_tree_ieditable_insert_at_path().
TREE_SIGNAL_MODIFIED_STATUS_CHANGED
#define TREE_SIGNAL_MODIFIED_STATUS_CHANGED "tree-signal-modified-status-changed"
Definition at line 104 of file cact-tree-view.h.
Referenced by cact_menubar_file_save_items(), cact_tree_ieditable_delete(), cact_tree_ieditable_initialize(), cact_tree_ieditable_insert_at_path(), and cact_tree_view_fill().
WINDOW_DATA_TREE_VIEW
#define WINDOW_DATA_TREE_VIEW "window-data-tree-view"
The CactTreeView is attached to the parent BaseWindow via a GObject data. Only CactTreeView itself and CactTreeIEditable interface should use it.
Definition at line 128 of file cact-tree-view.h.
Typedef Documentation
CactTreeViewClassPrivate
typedef struct _CactTreeViewClassPrivate CactTreeViewClassPrivate
Definition at line 72 of file cact-tree-view.h.
CactTreeViewPrivate
typedef struct _CactTreeViewPrivate CactTreeViewPrivate
Definition at line 63 of file cact-tree-view.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
When getting a list of items; these indcators may be OR-ed.
Enumerator
TREE_LIST_SELECTED
TREE_LIST_MODIFIED
TREE_LIST_ALL
TREE_LIST_DELETED
Definition at line 117 of file cact-tree-view.h.
CactTreeMode
enum CactTreeMode
Enumerator
TREE_MODE_EDITION
TREE_MODE_SELECTION
TREE_MODE_N_MODES
Definition at line 106 of file cact-tree-view.h.
Function Documentation
cact_tree_view_are_notify_allowed()
gboolean cact_tree_view_are_notify_allowed (const CactTreeView * view)
cact_tree_view_are_notify_allowed: @view: this CactTreeView instance.
Returns: TRUE if notifications are allowed, FALSE else.
Definition at line 925 of file cact-tree-view.c.
References CACT_IS_TREE_VIEW, FALSE, and CactTreeView::private.
cact_tree_view_collapse_all()
void cact_tree_view_collapse_all (const CactTreeView * view)
cact_tree_view_collapse_all: @view: this CactTreeView instance.
Collapse all the tree hierarchy.
Definition at line 964 of file cact-tree-view.c.
References CACT_IS_TREE_VIEW, and CactTreeView::private.
Referenced by cact_menubar_view_on_collapse_all().
cact_tree_view_expand_all()
void cact_tree_view_expand_all (const CactTreeView * view)
cact_tree_view_expand_all: @view: this CactTreeView instance.
Collapse all the tree hierarchy.
Definition at line 981 of file cact-tree-view.c.
References CACT_IS_TREE_VIEW, and CactTreeView::private.
Referenced by cact_menubar_view_on_expand_all().
cact_tree_view_fill()
void cact_tree_view_fill (CactTreeView * view, GList * items)
cact_tree_view_fill: @view: this CactTreeView instance.
Fill the tree view with the provided list of items.
Notification of selection changes is temporary suspended during the fillup of the list, so that client is not cluttered with tons of selection-changed messages.
Definition at line 891 of file cact-tree-view.c.
References CACT_IS_TREE_VIEW, CACT_TREE_MODEL, cact_tree_model_fill(), FALSE, na_object_count_items, CactTreeView::private, TREE_SIGNAL_COUNT_CHANGED, TREE_SIGNAL_MODIFIED_STATUS_CHANGED, and TRUE.
cact_tree_view_get_item_by_id()
NAObjectItem * cact_tree_view_get_item_by_id (const CactTreeView * view, const gchar * id)
cact_tree_view_get_item_by_id: @view: this CactTreeView instance. @id: the searched NAObjectItem.
Returns: a pointer on the searched NAObjectItem if it exists, or NULL.
The returned pointer is owned by the underlying tree store, and should not be released by the caller.
Definition at line 1002 of file cact-tree-view.c.
References CACT_IS_TREE_VIEW, CACT_TREE_MODEL, cact_tree_model_get_item_by_id(), item, NULL, and CactTreeView::private.
Referenced by cact_tree_ieditable_set_items().
cact_tree_view_get_items()
GList * cact_tree_view_get_items (const CactTreeView * view)
cact_tree_view_get_items: @view: this CactTreeView instance.
Returns: the content of the current tree as a newly allocated list which should be na_object_free_items() by the caller.
Definition at line 1028 of file cact-tree-view.c.
References cact_tree_view_get_items_ex(), and TREE_LIST_ALL.
Referenced by cact_menubar_file_save_items(), and cact_menubar_maintainer_on_brief_tree_store_dump().
cact_tree_view_get_items_ex()
GList * cact_tree_view_get_items_ex (const CactTreeView * view, guint mode)
cact_tree_view_get_items_ex: @view: this CactTreeView instance. @mode: the list content
Returns: the content of the current tree as a newly allocated list which should be na_object_free_items() by the caller.
Definition at line 1042 of file cact-tree-view.c.
References CACT_IS_TREE_VIEW, CACT_TREE_IEDITABLE, cact_tree_ieditable_get_deleted(), CACT_TREE_MODEL, cact_tree_model_get_items(), NULL, CactTreeView::private, TREE_LIST_DELETED, and TREE_MODE_EDITION.
Referenced by cact_tree_view_get_items().
cact_tree_view_get_type()
GType cact_tree_view_get_type (void)
Definition at line 151 of file cact-tree-view.c.
References CACT_TREE_IEDITABLE_TYPE, and NULL.
cact_tree_view_new()
CactTreeView * cact_tree_view_new (BaseWindow * window, GtkContainer * parent, const gchar * treeview_name, CactTreeMode mode)
cact_tree_view_new: @window: the BaseWindow which embeds the tree view. @parent: the GtkContainer parent of the tree view. @treeview_name: the GtkTreeView widget name. @mode: management mode.
Returns: a newly allocated CactTreeView object, which will be owned by the caller. It is useless to unref it as it will automatically auto-destroys itself at @window finalization.
This function is called from CactMainWindow::on_base_initialize_gtk() signal handler, thus only once during the application life.
Definition at line 603 of file cact-tree-view.c.
References CACT_TYPE_TREE_VIEW, NULL, TREE_PROP_MODE, TREE_PROP_PARENT, TREE_PROP_WIDGET_NAME, and TREE_PROP_WINDOW.
cact_tree_view_select_row_at_path()
void cact_tree_view_select_row_at_path (CactTreeView * view, GtkTreePath * path)
cact_tree_view_select_row_at_path: @view: this CactTreeView object. @path: the #GtkTreePath to be selected.
Select the row at the required path, or the immediate previous, or the next following, or eventually the immediate parent.
If nothing can be selected (and notify is allowed), at least send a message with an empty selection.
Definition at line 1083 of file cact-tree-view.c.
References CACT_IS_TREE_VIEW, FALSE, MAIN_SIGNAL_SELECTION_CHANGED, NULL, CactTreeView::private, and TRUE.
Referenced by cact_tree_ieditable_delete(), cact_tree_ieditable_insert_at_path(), and cact_tree_ieditable_insert_into().
cact_tree_view_set_notify_allowed()
void cact_tree_view_set_notify_allowed (CactTreeView * view, gboolean allow)
cact_tree_view_set_notify_allowed: @view: this CactTreeView instance. @allow: whether the notifications are to be allowed.
Definition at line 947 of file cact-tree-view.c.
References CACT_IS_TREE_VIEW, and CactTreeView::private.
Referenced by cact_tree_ieditable_delete(), and cact_tree_ieditable_insert_at_path().