MATE Desktop Environment: cact-menubar-priv.h File Reference
cact-menubar-priv.h File Reference
#include <core/na-updater.h>
#include "cact-menubar.h"
#include "cact-sort-buttons.h"
Classes
struct _CactMenubarPrivate
Macros
#define MENUBAR_SIGNAL_UPDATE_SENSITIVITIES "menubar-signal-update-sensitivities"
#define WINDOW_DATA_MENUBAR "window-data-menubar"
#define BAR_WINDOW_VOID(window)
#define BAR_WINDOW_VALUE(window, value)
Functions
void cact_menubar_enable_item (const CactMenubar *bar, const gchar *name, gboolean enabled)
void cact_menubar_edit_on_update_sensitivities (const CactMenubar *bar)
void cact_menubar_edit_on_cut (GtkAction *action, BaseWindow *window)
void cact_menubar_edit_on_copy (GtkAction *action, BaseWindow *window)
void cact_menubar_edit_on_paste (GtkAction *action, BaseWindow *window)
void cact_menubar_edit_on_paste_into (GtkAction *action, BaseWindow *window)
void cact_menubar_edit_on_duplicate (GtkAction *action, BaseWindow *window)
void cact_menubar_edit_on_delete (GtkAction *action, BaseWindow *window)
void cact_menubar_edit_on_reload (GtkAction *action, BaseWindow *window)
void cact_menubar_edit_on_prefererences (GtkAction *action, BaseWindow *window)
void cact_menubar_file_initialize (CactMenubar *bar)
void cact_menubar_file_on_update_sensitivities (const CactMenubar *bar)
void cact_menubar_file_on_new_menu (GtkAction *action, BaseWindow *window)
void cact_menubar_file_on_new_action (GtkAction *action, BaseWindow *window)
void cact_menubar_file_on_new_profile (GtkAction *action, BaseWindow *window)
void cact_menubar_file_on_save (GtkAction *action, BaseWindow *window)
void cact_menubar_file_on_quit (GtkAction *action, BaseWindow *window)
void cact_menubar_file_save_items (BaseWindow *window)
void cact_menubar_help_on_update_sensitivities (const CactMenubar *bar)
void cact_menubar_help_on_help (GtkAction *action, BaseWindow *window)
void cact_menubar_help_on_about (GtkAction *action, BaseWindow *window)
void cact_menubar_maintainer_on_update_sensitivities (const CactMenubar *bar)
void cact_menubar_maintainer_on_dump_selection (GtkAction *action, BaseWindow *window)
void cact_menubar_maintainer_on_brief_tree_store_dump (GtkAction *action, BaseWindow *window)
void cact_menubar_maintainer_on_list_modified_items (GtkAction *action, BaseWindow *window)
void cact_menubar_maintainer_on_dump_clipboard (GtkAction *action, BaseWindow *window)
void cact_menubar_maintainer_on_test_function (GtkAction *action, BaseWindow *window)
void cact_menubar_tools_on_update_sensitivities (const CactMenubar *bar)
void cact_menubar_tools_on_import (GtkAction *action, BaseWindow *window)
void cact_menubar_tools_on_export (GtkAction *action, BaseWindow *window)
void cact_menubar_view_on_update_sensitivities (const CactMenubar *bar)
void cact_menubar_view_on_expand_all (GtkAction *action, BaseWindow *window)
void cact_menubar_view_on_collapse_all (GtkAction *action, BaseWindow *window)
void cact_menubar_view_on_toolbar_file (GtkToggleAction *action, BaseWindow *window)
void cact_menubar_view_on_toolbar_edit (GtkToggleAction *action, BaseWindow *window)
void cact_menubar_view_on_toolbar_tools (GtkToggleAction *action, BaseWindow *window)
void cact_menubar_view_on_toolbar_help (GtkToggleAction *action, BaseWindow *window)
void cact_menubar_view_on_tabs_pos_changed (GtkRadioAction *action, GtkRadioAction *current, BaseWindow *window)
Macro Definition Documentation
BAR_WINDOW_VALUE
#define BAR_WINDOW_VALUE (window, value)
Value:
g_return_val_if_fail(BASE_IS_WINDOW(window), value); \
CactMenubar *bar = (CactMenubar *) g_object_get_data(G_OBJECT(window), WINDOW_DATA_MENUBAR); \
g_return_val_if_fail(CACT_IS_MENUBAR(bar), value);
Definition at line 121 of file cact-menubar-priv.h.
BAR_WINDOW_VOID
#define BAR_WINDOW_VOID (window)
Value:
g_return_if_fail(BASE_IS_WINDOW(window)); \
CactMenubar *bar = (CactMenubar *) g_object_get_data(G_OBJECT(window), WINDOW_DATA_MENUBAR); \
g_return_if_fail(CACT_IS_MENUBAR(bar));
Definition at line 116 of file cact-menubar-priv.h.
Referenced by cact_menubar_edit_on_copy(), cact_menubar_edit_on_cut(), cact_menubar_edit_on_delete(), cact_menubar_edit_on_duplicate(), cact_menubar_file_save_items(), and cact_menubar_maintainer_on_dump_selection().
MENUBAR_SIGNAL_UPDATE_SENSITIVITIES
#define MENUBAR_SIGNAL_UPDATE_SENSITIVITIES "menubar-signal-update-sensitivities"
Definition at line 110 of file cact-menubar-priv.h.
Referenced by cact_menubar_edit_on_copy().
WINDOW_DATA_MENUBAR
#define WINDOW_DATA_MENUBAR "window-data-menubar"
Definition at line 114 of file cact-menubar-priv.h.
Referenced by cact_menubar_new().
Function Documentation
cact_menubar_edit_on_copy()
void cact_menubar_edit_on_copy (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_edit_on_copy: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
copies the visible selection
(tree) get new refs on selected items
(menu) install in clipboard a copy of selected objects renumbering actions/menus id to ensure unicity at paste time
(menu) release refs on selected items
(menu) refresh actions sensitivy (as selection doesn't change)
Definition at line 252 of file cact-menubar-edit.c.
References BAR_WINDOW_VOID, cact_clipboard_primary_set(), CACT_IS_MAIN_WINDOW, CACT_MAIN_WINDOW, cact_main_window_get_clipboard(), CLIPBOARD_MODE_COPY, MENUBAR_SIGNAL_UPDATE_SENSITIVITIES, and CactClipboard::private.
cact_menubar_edit_on_cut()
void cact_menubar_edit_on_cut (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_edit_on_cut: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Cut objects are installed both in the clipboard and in the deleted list. Parent pointer is reset to NULL. Old parent status is re-checked by the tree model delete operation. When pasting later these cut objects:
the first time, we paste the very same object, removing it from the deleted list, attaching it to a new parent the object itself is not modified, but the parent is.
the following times, we paste a copy of this object with a new identifier
cuts the visible selection
(tree) get new refs on selected items
(main) add selected items to main list of deleted, moving newref from list_from_tree to main_list_of_deleted
(menu) install in clipboard a copy of selected objects
(tree) remove selected items, unreffing objects
Definition at line 200 of file cact-menubar-edit.c.
References _, BAR_WINDOW_VOID, BASE_WINDOW, base_window_display_error_dlg(), cact_clipboard_primary_set(), CACT_MAIN_WINDOW, cact_main_window_get_clipboard(), cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_delete(), CLIPBOARD_MODE_CUT, na_core_utils_slist_free(), na_core_utils_slist_join_at_end(), na_object_copyref_items, na_object_free_items, NULL, and TREE_OPE_DELETE.
cact_menubar_edit_on_delete()
void cact_menubar_edit_on_delete (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_edit_on_delete: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
deletes the visible selection
(tree) get new refs on selected items
(tree) remove selected items, unreffing objects
(main) add selected items to main list of deleted, moving newref from list_from_tree to main_list_of_deleted
(tree) select next row (if any, or previous if any, or none)
note that we get from selection a list of trees, but we don't have yet ensured that each element of this tree is actually deletable each branch of this list must be recursively deletable in order this branch itself be deleted
Definition at line 448 of file cact-menubar-edit.c.
References _, BAR_WINDOW_VOID, BASE_WINDOW, base_window_display_error_dlg(), CACT_IS_MAIN_WINDOW, CACT_MAIN_WINDOW, cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_delete(), na_core_utils_slist_free(), na_core_utils_slist_join_at_end(), na_object_copyref_items, na_object_free_items, NULL, and TREE_OPE_DELETE.
cact_menubar_edit_on_duplicate()
void cact_menubar_edit_on_duplicate (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_edit_on_duplicate: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
duplicate is just as paste, with the difference that content comes from the current selection, instead of coming from the clipboard
this is nonetheless a bit more complicated because when we duplicate some items (e.g. a multiple selection), we expect to see the new items just besides the original ones...
Definition at line 388 of file cact-menubar-edit.c.
References action, BAR_WINDOW_VOID, CACT_IS_MAIN_WINDOW, CACT_MAIN_WINDOW, cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_insert_items(), DUPLICATE_REC, NA_IS_OBJECT_PROFILE, NA_OBJECT, NA_OBJECT_ACTION, na_object_check_status, na_object_copyref_items, na_object_duplicate, na_object_free_items, na_object_get_parent, na_object_prepare_for_paste, na_object_set_origin, na_updater_should_pasted_be_relabeled(), NULL, and TRUE.
cact_menubar_edit_on_paste()
void cact_menubar_edit_on_paste (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_edit_on_paste: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
pastes the current content of the clipboard at the current position (same path, same level)
(menu) get from clipboard a copy of installed items the clipboard will return a new copy and renumber its own data for allowing a new paste
(tree) insert new items, the tree store will ref them attaching each item to its parent recursively checking edition status of the topmost parent selecting the first item at end
(menu) unreffing the copy got from clipboard
Definition at line 287 of file cact-menubar-edit.c.
References CACT_MAIN_WINDOW, cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_insert_items(), na_object_free_items, and NULL.
cact_menubar_edit_on_paste_into()
void cact_menubar_edit_on_paste_into (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_edit_on_paste_into: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
pastes the current content of the clipboard as the first child of currently selected item
(menu) get from clipboard a copy of installed items the clipboard will return a new copy and renumber its own data for allowing a new paste
(tree) insert new items, the tree store will ref them attaching each item to its parent recursively checking edition status of the topmost parent selecting the first item at end
(menu) unreffing the copy got from clipboard
Definition at line 321 of file cact-menubar-edit.c.
References CACT_MAIN_WINDOW, cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_insert_into(), and na_object_free_items.
cact_menubar_edit_on_prefererences()
void cact_menubar_edit_on_prefererences (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_edit_on_preferences: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Edit preferences.
Definition at line 609 of file cact-menubar-edit.c.
References cact_preferences_editor_run().
cact_menubar_edit_on_reload()
void cact_menubar_edit_on_reload (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_edit_on_reload: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Reload items from I/O storage subsystems.
Definition at line 596 of file cact-menubar-edit.c.
References CACT_MAIN_WINDOW, and cact_main_window_reload().
cact_menubar_edit_on_update_sensitivities()
void cact_menubar_edit_on_update_sensitivities (const CactMenubar * bar)
cact_menubar_edit_on_update_sensitivities: @bar: this CactMenubar object.
Update sensitivity of items of the Edit menu.
Each action (cut, copy, delete, etc.) takes itself care of whether it can safely apply to all the selection or not. The action can at least assume that at least one item will be a valid candidate (this is the Menubar rule).
Definition at line 64 of file cact-menubar-edit.c.
References _CactMenubarPrivate::are_items_writable, _CactMenubarPrivate::are_parents_writable, cact_menubar_enable_item(), _CactMenubarPrivate::clipboard_actions, _CactMenubarPrivate::clipboard_menus, _CactMenubarPrivate::clipboard_profiles, _CactMenubarPrivate::count_selected, _CactMenubarPrivate::has_writable_providers, _CactMenubarPrivate::is_action_writable, _CactMenubarPrivate::is_level_zero_writable, _CactMenubarPrivate::is_parent_writable, NA_IS_OBJECT_ACTION, NA_IS_OBJECT_MENU, NA_OBJECT, na_object_get_parent, na_object_is_finally_writable, NULL, _CactMenubarPrivate::popup_handler, CactMenubar::private, _CactMenubarPrivate::selected_items, and _CactMenubarPrivate::treeview_has_focus.
cact_menubar_enable_item()
void cact_menubar_enable_item (const CactMenubar * bar, const gchar * name, gboolean enabled)
Definition at line 923 of file cact-menubar.c.
References action, _CactMenubarPrivate::action_group, _CactMenubarPrivate::dispose_has_run, name, and CactMenubar::private.
Referenced by cact_menubar_edit_on_update_sensitivities(), cact_menubar_file_on_update_sensitivities(), cact_menubar_help_on_update_sensitivities(), cact_menubar_tools_on_update_sensitivities(), and cact_menubar_view_on_update_sensitivities().
cact_menubar_file_initialize()
void cact_menubar_file_initialize (CactMenubar * bar)
Definition at line 69 of file cact-menubar-file.c.
cact_menubar_file_on_new_action()
void cact_menubar_file_on_new_action (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_file_on_new_action: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers File / New action item.
Definition at line 153 of file cact-menubar-file.c.
References action, base_window_get_application(), CACT_APPLICATION, cact_application_get_updater(), CACT_IS_MAIN_WINDOW, CACT_MAIN_WINDOW, cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_insert_items(), na_object_action_new_with_defaults(), na_object_check_status, na_object_free_items, NA_OBJECT_ITEM, na_updater_check_item_writability_status(), and NULL.
cact_menubar_file_on_new_menu()
void cact_menubar_file_on_new_menu (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_file_on_new_menu: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers File / New menu item.
Definition at line 123 of file cact-menubar-file.c.
References base_window_get_application(), CACT_APPLICATION, cact_application_get_updater(), CACT_IS_MAIN_WINDOW, CACT_MAIN_WINDOW, cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_insert_items(), na_object_check_status, na_object_free_items, NA_OBJECT_ITEM, na_object_menu_new_with_defaults(), na_updater_check_item_writability_status(), and NULL.
cact_menubar_file_on_new_profile()
void cact_menubar_file_on_new_profile (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_file_on_new_profile: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers File / New profile item.
Definition at line 183 of file cact-menubar-file.c.
References _, action, CACT_IS_MAIN_WINDOW, CACT_MAIN_WINDOW, cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_insert_items(), MAIN_PROP_ITEM, na_object_attach_profile, na_object_check_status, na_object_free_items, na_object_profile_new_with_defaults(), na_object_set_label, na_object_set_new_id, and NULL.
cact_menubar_file_on_quit()
void cact_menubar_file_on_quit (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_file_on_quit: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers the File / Quit item.
Definition at line 419 of file cact-menubar-file.c.
References CACT_MAIN_WINDOW, cact_main_window_quit(), and NULL.
cact_menubar_file_on_save()
void cact_menubar_file_on_save (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_file_on_save: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers File /Save item.
Saving is not only saving modified items, but also saving hierarchy (and order if alpha order is not set).
This is the same function that cact_menubar_file_save_items(), just with different arguments.
Definition at line 226 of file cact-menubar-file.c.
References CACT_IS_MAIN_WINDOW, and cact_menubar_file_save_items().
cact_menubar_file_on_update_sensitivities()
void cact_menubar_file_on_update_sensitivities (const CactMenubar * bar)
cact_menubar_file_on_update_sensitivities: @bar: this CactMenubar object.
Update sensitivity of items of the File menu.
Definition at line 81 of file cact-menubar-file.c.
References cact_menubar_enable_item(), _CactMenubarPrivate::enable_new_profile, _CactMenubarPrivate::has_writable_providers, _CactMenubarPrivate::is_action_writable, _CactMenubarPrivate::is_parent_writable, _CactMenubarPrivate::is_tree_modified, and CactMenubar::private.
cact_menubar_file_save_items()
void cact_menubar_file_save_items (BaseWindow * window)
cact_menubar_file_save_items: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Save items. This is the same function that cact_menubar_file_on_save(), just with different arguments.
Synopsis:
rewrite the level-zero items list
delete the items which are marked to be deleted
rewrite (i.e. delete/write) updated items
The difficulty here is that some sort of pseudo-transactionnal process must be setup:
if the level-zero items list cannot be updated, then an error message is displayed, and we abort the whole processus
if some items cannot be actually deleted, then an error message is displayed, and the whole processus is aborted; plus: a/ items which have not been deleted must be restored (maybe marked as deleted ?) -> so these items are modified b/ the level-zero list must be updated with these restored items and reset modified
idem if some items cannot be actually rewritten...
Definition at line 268 of file cact-menubar-file.c.
References BAR_WINDOW_VOID, base_window_display_error_dlg(), CACT_MAIN_WINDOW, cact_main_window_block_reload(), cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, cact_tree_ieditable_is_level_zero_modified(), cact_tree_ieditable_remove_deleted(), cact_tree_view_get_items(), DUPLICATE_REC, FALSE, na_core_utils_slist_free(), na_core_utils_slist_join_at_end(), na_iprefs_write_level_zero(), na_object_check_status, na_object_dump_tree, na_object_duplicate, na_object_free_items, NA_OBJECT_ITEM, na_object_reset_origin, NA_PIVOT, na_pivot_set_new_items(), NULL, TREE_SIGNAL_LEVEL_ZERO_CHANGED, and TREE_SIGNAL_MODIFIED_STATUS_CHANGED.
Referenced by cact_menubar_file_on_save(), and cact_menubar_save_items().
cact_menubar_help_on_about()
void cact_menubar_help_on_about (GtkAction * action, BaseWindow * window)
cact_menubar_help_on_about: @action: the #GtkAction of the item. @window: the BaseWindow main application window.
Triggers the "Help/About" item.
Definition at line 84 of file cact-menubar-help.c.
References action, base_window_get_gtk_toplevel(), and na_about_display().
cact_menubar_help_on_help()
void cact_menubar_help_on_help (GtkAction * action, BaseWindow * window)
cact_menubar_help_on_help: @action: the #GtkAction of the item. @window: the BaseWindow main application window.
Triggers the "Help/Help" item.
Definition at line 59 of file cact-menubar-help.c.
References action, error, and NULL.
cact_menubar_help_on_update_sensitivities()
void cact_menubar_help_on_update_sensitivities (const CactMenubar * bar)
cact_menubar_help_on_update_sensitivities: @bar: this CactMenubar object.
Update sensitivities on the Help menu.
Definition at line 45 of file cact-menubar-help.c.
References cact_menubar_enable_item(), and TRUE.
cact_menubar_maintainer_on_brief_tree_store_dump()
void cact_menubar_maintainer_on_brief_tree_store_dump (GtkAction * action, BaseWindow * window)
cact_menubar_maintainer_on_brief_tree_store_dump: @action: the #GtkAction of the item. @window: the BaseWindow main application window.
Triggers the "Maintainer/Brief treestore dump" item.
Definition at line 75 of file cact-menubar-maintainer.c.
References action, CACT_MAIN_WINDOW, cact_main_window_get_items_view(), cact_tree_view_get_items(), na_object_dump_tree, and na_object_free_items.
cact_menubar_maintainer_on_dump_clipboard()
void cact_menubar_maintainer_on_dump_clipboard (GtkAction * action, BaseWindow * window)
cact_menubar_maintainer_on_dump_clipboard: @action: the #GtkAction of the item. @window: the BaseWindow main application window.
Triggers the "Maintainer/Dump clipboard" item.
Definition at line 110 of file cact-menubar-maintainer.c.
References action, cact_clipboard_dump(), CACT_MAIN_WINDOW, and cact_main_window_get_clipboard().
cact_menubar_maintainer_on_dump_selection()
void cact_menubar_maintainer_on_dump_selection (GtkAction * action, BaseWindow * window)
cact_menubar_maintainer_on_dump_selection: @action: the #GtkAction of the item. @window: the BaseWindow main application window.
Triggers the "Maintainer/Dump selection" item.
Definition at line 60 of file cact-menubar-maintainer.c.
References action, BAR_WINDOW_VOID, and na_object_dump_tree.
cact_menubar_maintainer_on_list_modified_items()
void cact_menubar_maintainer_on_list_modified_items (GtkAction * action, BaseWindow * window)
cact_menubar_maintainer_on_list_modified_items: @action: the #GtkAction of the item. @window: the BaseWindow main application window.
Triggers the "Maintainer/List modified items" item.
Definition at line 94 of file cact-menubar-maintainer.c.
References action, CACT_MAIN_WINDOW, cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, and cact_tree_ieditable_dump_modified().
cact_menubar_maintainer_on_test_function()
void cact_menubar_maintainer_on_test_function (GtkAction * action, BaseWindow * window)
Definition at line 119 of file cact-menubar-maintainer.c.
References action, base_application_is_willing_to_quit(), and base_window_get_application().
cact_menubar_maintainer_on_update_sensitivities()
void cact_menubar_maintainer_on_update_sensitivities (const CactMenubar * bar)
cact_menubar_maintainer_on_update_sensitivities: @bar: this CactMenubar object.
Update sensitivities on the Maintainer menu.
Definition at line 48 of file cact-menubar-maintainer.c.
cact_menubar_tools_on_export()
void cact_menubar_tools_on_export (GtkAction * action, BaseWindow * window)
cact_menubar_tools_on_export: @action: the #GtkAction of the item. @window: the BaseWindow main application window.
Triggers the "Tools/Export assistant" item.
Definition at line 75 of file cact-menubar-tools.c.
References action, BASE_WINDOW, and cact_assistant_export_run().
cact_menubar_tools_on_import()
void cact_menubar_tools_on_import (GtkAction * action, BaseWindow * window)
cact_menubar_tools_on_import: @action: the #GtkAction of the item. @window: the BaseWindow main application window.
Triggers the "Tools/Import assitant" item.
Definition at line 62 of file cact-menubar-tools.c.
References action, BASE_WINDOW, and cact_assistant_import_run().
cact_menubar_tools_on_update_sensitivities()
void cact_menubar_tools_on_update_sensitivities (const CactMenubar * bar)
cact_menubar_tools_on_update_sensitivities: @bar: this CactMenubar object.
Update sensitivities on the Tools menu.
Definition at line 45 of file cact-menubar-tools.c.
References cact_menubar_enable_item(), _CactMenubarPrivate::has_writable_providers, _CactMenubarPrivate::have_exportables, and CactMenubar::private.
cact_menubar_view_on_collapse_all()
void cact_menubar_view_on_collapse_all (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_view_on_collapse_all: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers View / Collapse all item.
Definition at line 80 of file cact-menubar-view.c.
References CACT_MAIN_WINDOW, cact_main_window_get_items_view(), and cact_tree_view_collapse_all().
cact_menubar_view_on_expand_all()
void cact_menubar_view_on_expand_all (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_view_on_expand_all: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers View / Expand all item.
Definition at line 64 of file cact-menubar-view.c.
References CACT_MAIN_WINDOW, cact_main_window_get_items_view(), and cact_tree_view_expand_all().
cact_menubar_view_on_tabs_pos_changed()
void cact_menubar_view_on_tabs_pos_changed (GtkRadioAction * action, GtkRadioAction * current, BaseWindow * window)
Definition at line 167 of file cact-menubar-view.c.
References action, BASE_WINDOW, and base_window_get_widget().
cact_menubar_view_on_toolbar_edit()
void cact_menubar_view_on_toolbar_edit (GtkToggleAction * action, BaseWindow * window)
cact_menubar_view_on_toolbar_edit: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers View / Toolbar / Edit item.
Definition at line 110 of file cact-menubar-view.c.
References action, and MAIN_TOOLBAR_EDIT_ID.
cact_menubar_view_on_toolbar_file()
void cact_menubar_view_on_toolbar_file (GtkToggleAction * action, BaseWindow * window)
cact_menubar_view_on_toolbar_file: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers View / Toolbar / File item.
Definition at line 96 of file cact-menubar-view.c.
References action, and MAIN_TOOLBAR_FILE_ID.
cact_menubar_view_on_toolbar_help()
void cact_menubar_view_on_toolbar_help (GtkToggleAction * action, BaseWindow * window)
cact_menubar_view_on_toolbar_help: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers View / Toolbar / Help item.
Definition at line 138 of file cact-menubar-view.c.
References action, and MAIN_TOOLBAR_HELP_ID.
cact_menubar_view_on_toolbar_tools()
void cact_menubar_view_on_toolbar_tools (GtkToggleAction * action, BaseWindow * window)
cact_menubar_view_on_toolbar_tools: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers View / Toolbar / Tools item.
Definition at line 124 of file cact-menubar-view.c.
References action, and MAIN_TOOLBAR_TOOLS_ID.
cact_menubar_view_on_update_sensitivities()
void cact_menubar_view_on_update_sensitivities (const CactMenubar * bar)
cact_menubar_view_on_update_sensitivities: @bar: this CactMenubar object.
Update sensitivity of items of the View menu.
Definition at line 46 of file cact-menubar-view.c.
References cact_menubar_enable_item(), _CactMenubarPrivate::count_actions, _CactMenubarPrivate::count_menus, _CactMenubarPrivate::count_profiles, and CactMenubar::private.