MATE Desktop Environment: cact-preferences-editor.h File Reference
cact-preferences-editor.h File Reference
#include "base-dialog.h"
Classes
struct CactPreferencesEditor
struct CactPreferencesEditorClass
Macros
#define CACT_TYPE_PREFERENCES_EDITOR (cact_preferences_editor_get_type())
#define CACT_PREFERENCES_EDITOR(object)
#define CACT_PREFERENCES_EDITOR_CLASS(klass)
#define CACT_IS_PREFERENCES_EDITOR(object)
#define CACT_IS_PREFERENCES_EDITOR_CLASS(klass)
#define CACT_PREFERENCES_EDITOR_GET_CLASS(object)
Typedefs
typedef struct _CactPreferencesEditorPrivate CactPreferencesEditorPrivate
typedef struct _CactPreferencesEditorClassPrivate CactPreferencesEditorClassPrivate
Functions
GType cact_preferences_editor_get_type (void)
void cact_preferences_editor_run (BaseWindow *parent)
Macro Definition Documentation
CACT_IS_PREFERENCES_EDITOR
#define CACT_IS_PREFERENCES_EDITOR (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE(object, CACT_TYPE_PREFERENCES_EDITOR))
Definition at line 49 of file cact-preferences-editor.h.
CACT_IS_PREFERENCES_EDITOR_CLASS
#define CACT_IS_PREFERENCES_EDITOR_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass), CACT_TYPE_PREFERENCES_EDITOR))
Definition at line 50 of file cact-preferences-editor.h.
CACT_PREFERENCES_EDITOR
#define CACT_PREFERENCES_EDITOR (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST(object, CACT_TYPE_PREFERENCES_EDITOR, CactPreferencesEditor))
Definition at line 47 of file cact-preferences-editor.h.
CACT_PREFERENCES_EDITOR_CLASS
#define CACT_PREFERENCES_EDITOR_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST(klass, CACT_TYPE_PREFERENCES_EDITOR, CactPreferencesEditorClass))
Definition at line 48 of file cact-preferences-editor.h.
CACT_PREFERENCES_EDITOR_GET_CLASS
#define CACT_PREFERENCES_EDITOR_GET_CLASS (object)
Value:
(G_TYPE_INSTANCE_GET_CLASS((object), CACT_TYPE_PREFERENCES_EDITOR, CactPreferencesEditorClass))
Definition at line 51 of file cact-preferences-editor.h.
CACT_TYPE_PREFERENCES_EDITOR
#define CACT_TYPE_PREFERENCES_EDITOR (cact_preferences_editor_get_type())
SECTION: cact_preferences_editor @short_description: CactPreferencesEditor class definition. cact/cact-preferences-editor.h
This class is derived from CactWindow. It encapsulates the "PreferencesDialog" widget dialog.
Definition at line 46 of file cact-preferences-editor.h.
Referenced by cact_preferences_editor_run().
Typedef Documentation
CactPreferencesEditorClassPrivate
typedef struct _CactPreferencesEditorClassPrivate CactPreferencesEditorClassPrivate
Definition at line 62 of file cact-preferences-editor.h.
CactPreferencesEditorPrivate
typedef struct _CactPreferencesEditorPrivate CactPreferencesEditorPrivate
Definition at line 53 of file cact-preferences-editor.h.
Function Documentation
cact_preferences_editor_get_type()
GType cact_preferences_editor_get_type (void)
Definition at line 174 of file cact-preferences-editor.c.
cact_preferences_editor_run()
void cact_preferences_editor_run (BaseWindow * parent)
cact_preferences_editor_run: @parent: the BaseWindow parent of this dialog (usually the CactMainWindow).
Initializes and runs the dialog.
Definition at line 440 of file cact-preferences-editor.c.
References BASE_IS_WINDOW, BASE_PROP_PARENT, BASE_PROP_TOPLEVEL_NAME, BASE_PROP_WSP_NAME, BASE_PROP_XMLUI_FILENAME, BASE_WINDOW, base_window_get_widget(), base_window_run(), CACT_TYPE_PREFERENCES_EDITOR, NA_IPREFS_ADMIN_PREFERENCES_LOCKED, na_settings_get_boolean(), NULL, and CactPreferencesEditor::private.
Referenced by cact_menubar_edit_on_prefererences().