MATE Desktop Environment: cact-menubar-view.c File Reference
cact-menubar-view.c File Reference
#include "cact-main-toolbar.h"
#include "cact-menubar-priv.h"
Functions
void cact_menubar_view_on_update_sensitivities (const CactMenubar *bar)
void cact_menubar_view_on_expand_all (GtkAction *gtk_action, BaseWindow *window)
void cact_menubar_view_on_collapse_all (GtkAction *gtk_action, BaseWindow *window)
void cact_menubar_view_on_toolbar_file (GtkToggleAction *action, BaseWindow *window)
void cact_menubar_view_on_toolbar_edit (GtkToggleAction *action, BaseWindow *window)
void cact_menubar_view_on_toolbar_tools (GtkToggleAction *action, BaseWindow *window)
void cact_menubar_view_on_toolbar_help (GtkToggleAction *action, BaseWindow *window)
void cact_menubar_view_on_tabs_pos_changed (GtkRadioAction *action, GtkRadioAction *current, BaseWindow *window)
Function Documentation
cact_menubar_view_on_collapse_all()
void cact_menubar_view_on_collapse_all (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_view_on_collapse_all: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers View / Collapse all item.
Definition at line 80 of file cact-menubar-view.c.
References CACT_MAIN_WINDOW, cact_main_window_get_items_view(), and cact_tree_view_collapse_all().
cact_menubar_view_on_expand_all()
void cact_menubar_view_on_expand_all (GtkAction * gtk_action, BaseWindow * window)
cact_menubar_view_on_expand_all: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers View / Expand all item.
Definition at line 64 of file cact-menubar-view.c.
References CACT_MAIN_WINDOW, cact_main_window_get_items_view(), and cact_tree_view_expand_all().
cact_menubar_view_on_tabs_pos_changed()
void cact_menubar_view_on_tabs_pos_changed (GtkRadioAction * action, GtkRadioAction * current, BaseWindow * window)
Definition at line 167 of file cact-menubar-view.c.
References action, BASE_WINDOW, and base_window_get_widget().
cact_menubar_view_on_toolbar_edit()
void cact_menubar_view_on_toolbar_edit (GtkToggleAction * action, BaseWindow * window)
cact_menubar_view_on_toolbar_edit: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers View / Toolbar / Edit item.
Definition at line 110 of file cact-menubar-view.c.
References action, and MAIN_TOOLBAR_EDIT_ID.
cact_menubar_view_on_toolbar_file()
void cact_menubar_view_on_toolbar_file (GtkToggleAction * action, BaseWindow * window)
cact_menubar_view_on_toolbar_file: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers View / Toolbar / File item.
Definition at line 96 of file cact-menubar-view.c.
References action, and MAIN_TOOLBAR_FILE_ID.
cact_menubar_view_on_toolbar_help()
void cact_menubar_view_on_toolbar_help (GtkToggleAction * action, BaseWindow * window)
cact_menubar_view_on_toolbar_help: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers View / Toolbar / Help item.
Definition at line 138 of file cact-menubar-view.c.
References action, and MAIN_TOOLBAR_HELP_ID.
cact_menubar_view_on_toolbar_tools()
void cact_menubar_view_on_toolbar_tools (GtkToggleAction * action, BaseWindow * window)
cact_menubar_view_on_toolbar_tools: @gtk_action: the #GtkAction action. @window: the BaseWindow main window.
Triggers View / Toolbar / Tools item.
Definition at line 124 of file cact-menubar-view.c.
References action, and MAIN_TOOLBAR_TOOLS_ID.
cact_menubar_view_on_update_sensitivities()
void cact_menubar_view_on_update_sensitivities (const CactMenubar * bar)
cact_menubar_view_on_update_sensitivities: @bar: this CactMenubar object.
Update sensitivity of items of the View menu.
Definition at line 46 of file cact-menubar-view.c.
References cact_menubar_enable_item(), _CactMenubarPrivate::count_actions, _CactMenubarPrivate::count_menus, _CactMenubarPrivate::count_profiles, and CactMenubar::private.