MATE Desktop Environment: cact-tree-model.h File Reference
cact-tree-model.h File Reference
#include <api/na-object.h>
#include "cact-tree-view.h"
Classes
struct CactTreeModel
struct CactTreeModelClass
Macros
#define CACT_TYPE_TREE_MODEL (cact_tree_model_get_type())
#define CACT_TREE_MODEL(object)
#define CACT_TREE_MODEL_CLASS(klass)
#define CACT_IS_TREE_MODEL(object)
#define CACT_IS_TREE_MODEL_CLASS(klass)
#define CACT_TREE_MODEL_GET_CLASS(object)
Typedefs
typedef struct _CactTreeModelPrivate CactTreeModelPrivate
typedef struct _CactTreeModelClassPrivate CactTreeModelClassPrivate
Enumerations
enum { TREE_COLUMN_ICON = 0 , TREE_COLUMN_LABEL , TREE_COLUMN_NAOBJECT , TREE_N_COLUMN }
Functions
GType cact_tree_model_get_type (void)
CactTreeModel * cact_tree_model_new (BaseWindow *window, GtkTreeView *view, CactTreeMode mode)
GtkTreePath * cact_tree_model_delete (CactTreeModel *model, NAObject *object)
void cact_tree_model_fill (CactTreeModel *model, GList *items)
GtkTreePath * cact_tree_model_insert_before (CactTreeModel *model, const NAObject *object, GtkTreePath *path)
GtkTreePath * cact_tree_model_insert_into (CactTreeModel *model, const NAObject *object, GtkTreePath *path)
NAObjectItem * cact_tree_model_get_item_by_id (const CactTreeModel *model, const gchar *id)
GList * cact_tree_model_get_items (const CactTreeModel *model, guint mode)
NAObject * cact_tree_model_object_at_path (const CactTreeModel *model, GtkTreePath *path)
GtkTreePath * cact_tree_model_object_to_path (const CactTreeModel *model, const NAObject *object)
Macro Definition Documentation
CACT_IS_TREE_MODEL
#define CACT_IS_TREE_MODEL (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE((object), CACT_TYPE_TREE_MODEL))
Definition at line 56 of file cact-tree-model.h.
Referenced by cact_tree_model_delete(), cact_tree_model_dnd_idrag_dest_drag_data_received(), cact_tree_model_dnd_imulti_drag_source_row_draggable(), cact_tree_model_dnd_on_drag_begin(), cact_tree_model_dnd_on_drag_end(), cact_tree_model_fill(), cact_tree_model_get_item_by_id(), cact_tree_model_get_items(), cact_tree_model_insert_before(), cact_tree_model_insert_into(), cact_tree_model_object_at_path(), and cact_tree_model_object_to_path().
CACT_IS_TREE_MODEL_CLASS
#define CACT_IS_TREE_MODEL_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass), CACT_TYPE_TREE_MODEL))
Definition at line 57 of file cact-tree-model.h.
CACT_TREE_MODEL
#define CACT_TREE_MODEL (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST((object), CACT_TYPE_TREE_MODEL, CactTreeModel))
Definition at line 54 of file cact-tree-model.h.
Referenced by cact_tree_ieditable_initialize(), cact_tree_model_dnd_idrag_dest_drag_data_received(), cact_tree_model_dnd_imulti_drag_source_drag_data_get(), cact_tree_model_dnd_imulti_drag_source_row_draggable(), cact_tree_view_fill(), cact_tree_view_get_item_by_id(), and cact_tree_view_get_items_ex().
CACT_TREE_MODEL_CLASS
#define CACT_TREE_MODEL_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST((klass), CACT_TYPE_TREE_MODEL, CactTreeModelClass))
Definition at line 55 of file cact-tree-model.h.
CACT_TREE_MODEL_GET_CLASS
#define CACT_TREE_MODEL_GET_CLASS (object)
Value:
(G_TYPE_INSTANCE_GET_CLASS((object), CACT_TYPE_TREE_MODEL, CactTreeModelClass))
Definition at line 58 of file cact-tree-model.h.
CACT_TYPE_TREE_MODEL
#define CACT_TYPE_TREE_MODEL (cact_tree_model_get_type())
SECTION: cact_tree_model @short_description: CactTreeModel class definition. cact/cact-tree-model.h
CactTreeModel is derived from GtkTreeModelFilter in order to be able to selectively display profiles, whether an action has one or more profiles.
CactTreeModel implements EggTreeMultiDragSource and GtkTreeDragDest interfaces.
The GtkTreeModelFilter base class embeds a GtkTreeStore.
Definition at line 53 of file cact-tree-model.h.
Referenced by cact_tree_model_new().
Typedef Documentation
CactTreeModelClassPrivate
typedef struct _CactTreeModelClassPrivate CactTreeModelClassPrivate
Definition at line 69 of file cact-tree-model.h.
CactTreeModelPrivate
typedef struct _CactTreeModelPrivate CactTreeModelPrivate
Definition at line 60 of file cact-tree-model.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Column ordering in the tree view
Enumerator
TREE_COLUMN_ICON
TREE_COLUMN_LABEL
TREE_COLUMN_NAOBJECT
TREE_N_COLUMN
Definition at line 81 of file cact-tree-model.h.
Function Documentation
cact_tree_model_delete()
GtkTreePath * cact_tree_model_delete (CactTreeModel * model, NAObject * object)
cact_tree_model_delete: @model: this CactTreeModel instance. @object: the NAObject to be deleted.
Recursively deletes the specified object.
Returns: a path which may be suitable for the next selection.
Definition at line 600 of file cact-tree-model.c.
References CACT_IS_TREE_MODEL, cact_tree_model_object_to_path(), na_object_get_parent, na_object_remove_item, and NULL.
Referenced by cact_tree_ieditable_delete(), and cact_tree_ieditable_set_items().
cact_tree_model_fill()
void cact_tree_model_fill (CactTreeModel * model, GList * items)
cact_tree_model_fill: @model: this CactTreeModel instance. @ŧreeview: the #GtkTreeView widget. @items: this list of items, usually from NAPivot, which will be used to fill up the tree store.
Fill up the tree store with specified items.
We enter with the GSList owned by NAPivot which contains the ordered list of level-zero items. We want have a duplicate of this list in tree store, so that we are able to freely edit it.
Definition at line 654 of file cact-tree-model.c.
References CACT_IS_TREE_MODEL, DUPLICATE_REC, na_object_check_status, na_object_duplicate, na_object_unref, and NULL.
Referenced by cact_tree_view_fill().
cact_tree_model_get_item_by_id()
NAObjectItem * cact_tree_model_get_item_by_id (const CactTreeModel * model, const gchar * id)
cact_tree_model_get_item_by_id: @model: this CactTreeModel object. @id: the searched NAObjectItem.
Returns: a pointer on the searched NAObjectItem if it exists, or NULL.
The returned pointer is owned by the underlying tree store, and should not be released by the caller.
Definition at line 855 of file cact-tree-model.c.
References CACT_IS_TREE_MODEL, and NULL.
Referenced by cact_tree_view_get_item_by_id().
cact_tree_model_get_items()
GList * cact_tree_model_get_items (const CactTreeModel * model, guint mode)
cact_tree_model_get_items: @model: this CactTreeModel object. @mode: the content indicator for the returned list
Returns: the content of the current store as a newly allocated list which should be na_object_free_items() by the caller.
Definition at line 885 of file cact-tree-model.c.
References CACT_IS_TREE_MODEL, and NULL.
Referenced by cact_tree_view_get_items_ex().
cact_tree_model_get_type()
GType cact_tree_model_get_type (void)
Definition at line 153 of file cact-tree-model.c.
cact_tree_model_insert_before()
GtkTreePath * cact_tree_model_insert_before (CactTreeModel * model, const NAObject * object, GtkTreePath * path)
cact_tree_model_insert_before: @model: this CactTreeModel instance. @object: a #NAObject-derived object to be inserted. @path: the #GtkTreePath which specifies the insertion path. @parent: set to the parent or the object itself.
Insert a new row at the given position.
Gtk API uses to returns iter ; but at least when inserting a new profile in an action, we may have store_iter_path="0:1" (good), but iter_path="0:0" (bad) - so we'd rather return a string path.
Returns: the actual insertion path, which may be different from the asked insertion path if tree is sorted.
Definition at line 697 of file cact-tree-model.c.
References CACT_IS_TREE_MODEL, FALSE, NA_IS_OBJECT, na_object_append_item, na_object_insert_item, na_object_set_parent, NULL, TREE_COLUMN_NAOBJECT, and TRUE.
Referenced by cact_tree_ieditable_set_items().
cact_tree_model_insert_into()
GtkTreePath * cact_tree_model_insert_into (CactTreeModel * model, const NAObject * object, GtkTreePath * path)
cact_tree_model_insert_into: @model: this CactTreeModel instance. @object: the NAObject to be inserted. @path: the wished #GtkTreePath path.
Insert the @object at ou near the wished @path, and attaches the object to its new parent.
Returns the actual insertion path, wchich should be gtk_tree_path_free() by the caller.
Definition at line 792 of file cact-tree-model.c.
References CACT_IS_TREE_MODEL, NA_IS_OBJECT, na_object_insert_item, na_object_set_parent, NULL, and TREE_COLUMN_NAOBJECT.
cact_tree_model_new()
CactTreeModel * cact_tree_model_new (BaseWindow * window, GtkTreeView * treeview, CactTreeMode mode)
cact_tree_model_new: @window: a BaseWindow window which embeds our CactTreeView @treeview: the #GtkTreeView widget. @mode: management mode.
Returns: a newly created CactTreeModel object.
The returned reference is owned by the #GtkTreeView, which will automatically take care of g_object_unref() its tree model when destroying its widget.
Called from CactTreeView::initialize_gtk() method [..] which happens to be eventually called from CactMainWindow::on_initialize_gtk() signal handler.
Definition at line 495 of file cact-tree-model.c.
References BASE_IS_WINDOW, CACT_TYPE_TREE_MODEL, na_iprefs_get_order_mode(), NA_TYPE_OBJECT, NULL, TREE_N_COLUMN, TREE_PROP_MODE, TREE_PROP_TREEVIEW, and TREE_PROP_WINDOW.
cact_tree_model_object_at_path()
NAObject * cact_tree_model_object_at_path (const CactTreeModel * model, GtkTreePath * path)
cact_tree_model_object_at_path: @model: this CactTreeModel instance. @path: the #GtkTreePath to be searched.
Returns: the NAObject at the given @path if any, or NULL.
The reference count of the object is not modified. The returned reference is owned by the tree store and should not be released by the caller.
Definition at line 920 of file cact-tree-model.c.
References CACT_IS_TREE_MODEL, NULL, and TREE_COLUMN_NAOBJECT.
Referenced by cact_tree_ieditable_insert_items().
cact_tree_model_object_to_path()
GtkTreePath * cact_tree_model_object_to_path (const CactTreeModel * model, const NAObject * object)
cact_tree_model_object_to_path: @model: this CactTreeModel. @object: the searched NAObject.
Returns: a newly allocated GtkTreePath which is the current position of @object in the tree store, or NULL.
The returned path should be gtk_tree_path_free() by the caller.
Definition at line 953 of file cact-tree-model.c.
References CACT_IS_TREE_MODEL, and NULL.
Referenced by cact_tree_ieditable_insert_items(), and cact_tree_model_delete().