MATE Desktop Environment: cact-export-ask.h File Reference
cact-export-ask.h File Reference
#include <api/na-object-item.h>
#include "base-dialog.h"
Classes
struct CactExportAsk
struct CactExportAskClass
Macros
#define CACT_TYPE_EXPORT_ASK (cact_export_ask_get_type())
#define CACT_EXPORT_ASK(object)
#define CACT_EXPORT_ASK_CLASS(klass)
#define CACT_IS_EXPORT_ASK(object)
#define CACT_IS_EXPORT_ASK_CLASS(klass)
#define CACT_EXPORT_ASK_GET_CLASS(object)
Typedefs
typedef struct _CactExportAskPrivate CactExportAskPrivate
typedef struct _CactExportAskClassPrivate CactExportAskClassPrivate
Functions
GType cact_export_ask_get_type (void)
gchar * cact_export_ask_user (BaseWindow *window, NAObjectItem *item, gboolean first)
Macro Definition Documentation
CACT_EXPORT_ASK
#define CACT_EXPORT_ASK (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST(object, CACT_TYPE_EXPORT_ASK, CactExportAsk))
Definition at line 55 of file cact-export-ask.h.
CACT_EXPORT_ASK_CLASS
#define CACT_EXPORT_ASK_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST(klass, CACT_TYPE_EXPORT_ASK, CactExportAskClass))
Definition at line 56 of file cact-export-ask.h.
CACT_EXPORT_ASK_GET_CLASS
#define CACT_EXPORT_ASK_GET_CLASS (object)
Value:
(G_TYPE_INSTANCE_GET_CLASS((object), CACT_TYPE_EXPORT_ASK, CactExportAskClass))
Definition at line 59 of file cact-export-ask.h.
CACT_IS_EXPORT_ASK
#define CACT_IS_EXPORT_ASK (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE(object, CACT_TYPE_EXPORT_ASK))
Definition at line 57 of file cact-export-ask.h.
CACT_IS_EXPORT_ASK_CLASS
#define CACT_IS_EXPORT_ASK_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass), CACT_TYPE_EXPORT_ASK))
Definition at line 58 of file cact-export-ask.h.
CACT_TYPE_EXPORT_ASK
#define CACT_TYPE_EXPORT_ASK (cact_export_ask_get_type())
SECTION: cact_export_ask @short_description: CactExportAsk class definition. cact/cact-export-ask.h
This class is derived from BaseDialog. It is ran each time an action is to be exported, and the user want to be asked to choose the export format.
Only actually available export formats, as provided by i/o providers, are proposed here:
the 'Ask' option is obviously not proposed here
a 'NoImport' capability is provided by clicking on Cancel button.
Definition at line 54 of file cact-export-ask.h.
Referenced by cact_export_ask_user().
Typedef Documentation
CactExportAskClassPrivate
typedef struct _CactExportAskClassPrivate CactExportAskClassPrivate
Definition at line 70 of file cact-export-ask.h.
CactExportAskPrivate
typedef struct _CactExportAskPrivate CactExportAskPrivate
Definition at line 61 of file cact-export-ask.h.
Function Documentation
cact_export_ask_get_type()
GType cact_export_ask_get_type (void)
Definition at line 90 of file cact-export-ask.c.
cact_export_ask_user()
gchar * cact_export_ask_user (BaseWindow * parent, NAObjectItem * item, gboolean first)
cact_export_ask_user: @parent: the CactAssistant parent of this dialog. @item: the NAObjectItem to be exported. @first: whether this is the first call of a series. On a first call, the user is really asked for his choice. The next times, the 'keep-last-choice' flag will be considered.
Initializes and runs the dialog.
This is a small dialog which is to be ran during export operations, when the set export format is 'Ask me'. Each exported file runs this dialog, unless the user selects the 'keep same choice' box.
Returns: the export format chosen by the user as a newly allocated string which should be g_free() by the caller. The function defaults to returning NA_IPREFS_DEFAULT_EXPORT_FORMAT.
When the user selects 'Keep same choice without asking me', this choice becomes his new preferred export format.
Definition at line 304 of file cact-export-ask.c.
References BASE_IS_WINDOW, BASE_PROP_PARENT, BASE_PROP_TOPLEVEL_NAME, BASE_PROP_WSP_NAME, BASE_PROP_XMLUI_FILENAME, BASE_WINDOW, base_window_run(), CACT_TYPE_EXPORT_ASK, EXPORTER_FORMAT_NOEXPORT, item, NA_IPREFS_ADMIN_PREFERENCES_LOCKED, NA_IPREFS_EXPORT_ASK_USER_KEEP_LAST_CHOICE, NA_IPREFS_EXPORT_ASK_USER_LAST_FORMAT, na_settings_get_boolean(), na_settings_get_string(), NULL, and CactExportAsk::private.