MATE Desktop Environment: cact-clipboard.h File Reference
cact-clipboard.h File Reference
#include <gtk/gtk.h>
#include "base-window.h"
Classes
struct CactClipboard
struct CactClipboardClass
Macros
#define CACT_TYPE_CLIPBOARD (cact_clipboard_get_type())
#define CACT_CLIPBOARD(object)
#define CACT_CLIPBOARD_CLASS(klass)
#define CACT_IS_CLIPBOARD(object)
#define CACT_IS_CLIPBOARD_CLASS(klass)
#define CACT_CLIPBOARD_GET_CLASS(object)
Typedefs
typedef struct _CactClipboardPrivate CactClipboardPrivate
typedef struct _CactClipboardClassPrivate CactClipboardClassPrivate
Enumerations
enum {
CACT_XCHANGE_FORMAT_CACT = 0 , CACT_XCHANGE_FORMAT_XDS , CACT_XCHANGE_FORMAT_APPLICATION_XML , CACT_XCHANGE_FORMAT_TEXT_PLAIN ,
CACT_XCHANGE_FORMAT_URI_LIST
}
enum { CLIPBOARD_MODE_CUT = 1 , CLIPBOARD_MODE_COPY }
Functions
GType cact_clipboard_get_type (void)
CactClipboard * cact_clipboard_new (BaseWindow *window)
void cact_clipboard_dnd_set (CactClipboard *clipboard, guint target, GList *rows, const gchar *folder, gboolean copy)
GList * cact_clipboard_dnd_get_data (CactClipboard *clipboard, gboolean *copy)
gchar * cact_clipboard_dnd_get_text (CactClipboard *clipboard, GList *rows)
void cact_clipboard_dnd_drag_end (CactClipboard *clipboard)
void cact_clipboard_dnd_clear (CactClipboard *clipboard)
void cact_clipboard_primary_set (CactClipboard *clipboard, GList *items, gint mode)
GList * cact_clipboard_primary_get (CactClipboard *clipboard, gboolean *relabel)
void cact_clipboard_primary_counts (CactClipboard *clipboard, guint *actions, guint *profiles, guint *menus)
void cact_clipboard_dump (CactClipboard *clipboard)
Macro Definition Documentation
CACT_CLIPBOARD
#define CACT_CLIPBOARD (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST(object, CACT_TYPE_CLIPBOARD, CactClipboard))
Definition at line 50 of file cact-clipboard.h.
CACT_CLIPBOARD_CLASS
#define CACT_CLIPBOARD_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST(klass, CACT_TYPE_CLIPBOARD, CactClipboardClass))
Definition at line 51 of file cact-clipboard.h.
CACT_CLIPBOARD_GET_CLASS
#define CACT_CLIPBOARD_GET_CLASS (object)
Value:
(G_TYPE_INSTANCE_GET_CLASS((object), CACT_TYPE_CLIPBOARD, CactClipboardClass))
Definition at line 54 of file cact-clipboard.h.
CACT_IS_CLIPBOARD
#define CACT_IS_CLIPBOARD (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE(object, CACT_TYPE_CLIPBOARD))
Definition at line 52 of file cact-clipboard.h.
Referenced by cact_clipboard_dnd_drag_end(), cact_clipboard_dnd_get_data(), cact_clipboard_dnd_get_text(), cact_clipboard_dnd_set(), cact_clipboard_dump(), cact_clipboard_primary_counts(), cact_clipboard_primary_get(), and cact_clipboard_primary_set().
CACT_IS_CLIPBOARD_CLASS
#define CACT_IS_CLIPBOARD_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass), CACT_TYPE_CLIPBOARD))
Definition at line 53 of file cact-clipboard.h.
CACT_TYPE_CLIPBOARD
#define CACT_TYPE_CLIPBOARD (cact_clipboard_get_type())
Definition at line 49 of file cact-clipboard.h.
Referenced by cact_clipboard_new().
Typedef Documentation
CactClipboardClassPrivate
typedef struct _CactClipboardClassPrivate CactClipboardClassPrivate
Definition at line 65 of file cact-clipboard.h.
CactClipboardPrivate
typedef struct _CactClipboardPrivate CactClipboardPrivate
Definition at line 56 of file cact-clipboard.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CLIPBOARD_MODE_CUT
CLIPBOARD_MODE_COPY
Definition at line 86 of file cact-clipboard.h.
anonymous enum
anonymous enum
Enumerator
CACT_XCHANGE_FORMAT_CACT
CACT_XCHANGE_FORMAT_XDS
CACT_XCHANGE_FORMAT_APPLICATION_XML
CACT_XCHANGE_FORMAT_TEXT_PLAIN
CACT_XCHANGE_FORMAT_URI_LIST
Definition at line 76 of file cact-clipboard.h.
Function Documentation
cact_clipboard_dnd_clear()
void cact_clipboard_dnd_clear (CactClipboard * clipboard)
cact_clipboard_dnd_clear: @clipboard: this CactClipboard instance.
Clears the drag-and-drop clipboard.
At least called on drag-begin.
Definition at line 447 of file cact-clipboard.c.
References CactClipboard::private.
Referenced by cact_tree_model_dnd_on_drag_begin(), and cact_tree_model_dnd_on_drag_end().
cact_clipboard_dnd_drag_end()
void cact_clipboard_dnd_drag_end (CactClipboard * clipboard)
cact_clipboard_dnd_drag_end: @clipboard: this CactClipboard instance.
On drag-end, exports the objects if needed.
Definition at line 408 of file cact-clipboard.c.
References CACT_CLIPBOARD_CACT_ATOM, CACT_IS_CLIPBOARD, CACT_XCHANGE_FORMAT_XDS, data, and CactClipboard::private.
Referenced by cact_tree_model_dnd_on_drag_end().
cact_clipboard_dnd_get_data()
GList * cact_clipboard_dnd_get_data (CactClipboard * clipboard, gboolean * copy_data)
cact_clipboard_dnd_get_data: @clipboard: this CactClipboard instance. @copy_data: will be set to the original value of the drag and drop.
Returns the list of rows references privously stored.
The returned list should be gtk_tree_row_reference_free() by the caller.
Definition at line 329 of file cact-clipboard.c.
References CACT_CLIPBOARD_CACT_ATOM, CACT_IS_CLIPBOARD, CACT_XCHANGE_FORMAT_CACT, data, FALSE, NULL, and CactClipboard::private.
cact_clipboard_dnd_get_text()
gchar * cact_clipboard_dnd_get_text (CactClipboard * clipboard, GList * rows)
Definition at line 380 of file cact-clipboard.c.
References CACT_IS_CLIPBOARD, NULL, and CactClipboard::private.
Referenced by cact_tree_model_dnd_imulti_drag_source_drag_data_get().
cact_clipboard_dnd_set()
void cact_clipboard_dnd_set (CactClipboard * clipboard, guint target, GList * rows, const gchar * folder, gboolean copy_data)
cact_clipboard_dnd_set: @clipboard: this CactClipboard instance. @rows: the list of row references of dragged items. @folder: the URI of the target folder if any (XDS protocol to outside). @copy_data: TRUE if data is to be copied, FALSE else (only relevant when drag and drop occurs inside of the tree view).
Set the selected items into our dnd clipboard.
Definition at line 284 of file cact-clipboard.c.
References CACT_IS_CLIPBOARD, data, NULL, and CactClipboard::private.
Referenced by cact_tree_model_dnd_imulti_drag_source_drag_data_get().
cact_clipboard_dump()
void cact_clipboard_dump (CactClipboard * clipboard)
cact_clipboard_dump: @clipboard: this CactClipboard instance.
Dumps the content of the primary clipboard.
Definition at line 861 of file cact-clipboard.c.
References CACT_IS_CLIPBOARD, and CactClipboard::private.
Referenced by cact_menubar_maintainer_on_dump_clipboard().
cact_clipboard_get_type()
GType cact_clipboard_get_type (void)
Definition at line 126 of file cact-clipboard.c.
cact_clipboard_new()
CactClipboard * cact_clipboard_new (BaseWindow * window)
cact_clipboard_new:
Returns: a new CactClipboard object.
Definition at line 260 of file cact-clipboard.c.
References BASE_IS_WINDOW, CACT_TYPE_CLIPBOARD, NULL, and CactClipboard::private.
cact_clipboard_primary_counts()
void cact_clipboard_primary_counts (CactClipboard * clipboard, guint * actions, guint * profiles, guint * menus)
cact_clipboard_primary_counts: @clipboard: this CactClipboard object.
Returns some counters on content of primary clipboard.
Definition at line 777 of file cact-clipboard.c.
References CACT_IS_CLIPBOARD, CactClipboard::private, and user_data.
cact_clipboard_primary_get()
GList * cact_clipboard_primary_get (CactClipboard * clipboard, gboolean * relabel)
cact_clipboard_primary_get: @clipboard: this CactClipboard object.
Returns: a copy of the list of items previously referenced in the internal clipboard.
We allocate a new id for items in order to be ready to paste another time.
Definition at line 728 of file cact-clipboard.c.
References CACT_CLIPBOARD_CACT_ATOM, CACT_IS_CLIPBOARD, CLIPBOARD_MODE_COPY, CLIPBOARD_MODE_CUT, DUPLICATE_REC, NA_OBJECT, na_object_duplicate, na_object_set_origin, NULL, CactClipboard::private, TRUE, and user_data.
cact_clipboard_primary_set()
void cact_clipboard_primary_set (CactClipboard * clipboard, GList * items, gint mode)
cact_clipboard_primary_set: @clipboard: this CactClipboard object. @items: a list of NAObject items @mode: where do these items come from ? Or what is the operation which has led the items to the clipboard?
Installs a copy of provided items in the clipboard.
Rationale: when cutting an item to the clipboard, the next paste will keep its same original id, and it is safe because this is actually what we want when we cut/paste.
Contrarily, when we copy/paste, we are waiting for a new element which has the same characteristics that the previous one ; we so have to renumber actions/menus items when copying into the clipboard.
Note that we use NAIDuplicable interface without actually taking care of what is origin or so, as origin will be reinitialized when getting data out of the clipboard.
Definition at line 670 of file cact-clipboard.c.
References CACT_IS_CLIPBOARD, DUPLICATE_REC, FALSE, na_object_duplicate, na_object_item_count_items(), NULL, CactClipboard::private, and user_data.
Referenced by cact_menubar_edit_on_copy(), and cact_menubar_edit_on_cut().