MATE Desktop Environment: cact-assistant-import.c File Reference
cact-assistant-import.c File Reference
#include <gdk/gdk.h>
#include <glib/gi18n.h>
#include <string.h>
#include <api/na-object-api.h>
#include <api/na-core-utils.h>
#include <core/na-import-mode.h>
#include <core/na-importer.h>
#include <core/na-ioptions-list.h>
#include <core/na-gtk-utils.h>
#include <core/na-settings.h>
#include "cact-application.h"
#include "cact-assistant-import.h"
#include "cact-main-window.h"
#include "cact-tree-ieditable.h"
Enumerations
enum {
ASSIST_PAGE_INTRO = 0 , ASSIST_PAGE_FILES_SELECTION , ASSIST_PAGE_DUPLICATES , ASSIST_PAGE_CONFIRM ,
ASSIST_PAGE_DONE
}
enum {
IMAGE_COLUMN = 0 , LABEL_COLUMN , TOOLTIP_COLUMN , MODE_COLUMN ,
INDEX_COLUMN , N_COLUMN
}
Functions
GType cact_assistant_import_get_type (void)
void cact_assistant_import_run (BaseWindow *main_window)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ASSIST_PAGE_INTRO
ASSIST_PAGE_FILES_SELECTION
ASSIST_PAGE_DUPLICATES
ASSIST_PAGE_CONFIRM
ASSIST_PAGE_DONE
Definition at line 62 of file cact-assistant-import.c.
anonymous enum
anonymous enum
Enumerator
IMAGE_COLUMN
LABEL_COLUMN
TOOLTIP_COLUMN
MODE_COLUMN
INDEX_COLUMN
N_COLUMN
Definition at line 72 of file cact-assistant-import.c.
Function Documentation
cact_assistant_import_get_type()
GType cact_assistant_import_get_type (void)
Definition at line 135 of file cact-assistant-import.c.
cact_assistant_import_run()
void cact_assistant_import_run (BaseWindow * main_window)
cact_assistant_import_run: @main: the CactMainWindow parent window of this assistant.
Run the assistant.
Definition at line 320 of file cact-assistant-import.c.
References BASE_PROP_HAS_OWN_BUILDER, BASE_PROP_PARENT, BASE_PROP_QUIT_ON_ESCAPE, BASE_PROP_TOPLEVEL_NAME, BASE_PROP_WARN_ON_ESCAPE, BASE_PROP_WSP_NAME, BASE_PROP_XMLUI_FILENAME, BASE_WINDOW, base_window_run(), CACT_IS_MAIN_WINDOW, CACT_TYPE_ASSISTANT_IMPORT, NA_IPREFS_ASSISTANT_ESC_CONFIRM, NA_IPREFS_ASSISTANT_ESC_QUIT, na_settings_get_boolean(), NULL, and TRUE.
Referenced by cact_menubar_tools_on_import().