MATE Desktop Environment: cact-menubar-maintainer.c File Reference
cact-menubar-maintainer.c File Reference
#include <api/na-object-api.h>
#include "cact-clipboard.h"
#include "cact-menubar-priv.h"
#include "cact-main-window.h"
#include "cact-tree-ieditable.h"
Functions
void cact_menubar_maintainer_on_update_sensitivities (const CactMenubar *bar)
void cact_menubar_maintainer_on_dump_selection (GtkAction *action, BaseWindow *window)
void cact_menubar_maintainer_on_brief_tree_store_dump (GtkAction *action, BaseWindow *window)
void cact_menubar_maintainer_on_list_modified_items (GtkAction *action, BaseWindow *window)
void cact_menubar_maintainer_on_dump_clipboard (GtkAction *action, BaseWindow *window)
void cact_menubar_maintainer_on_test_function (GtkAction *action, BaseWindow *window)
Function Documentation
cact_menubar_maintainer_on_brief_tree_store_dump()
void cact_menubar_maintainer_on_brief_tree_store_dump (GtkAction * action, BaseWindow * window)
cact_menubar_maintainer_on_brief_tree_store_dump: @action: the #GtkAction of the item. @window: the BaseWindow main application window.
Triggers the "Maintainer/Brief treestore dump" item.
Definition at line 75 of file cact-menubar-maintainer.c.
References action, CACT_MAIN_WINDOW, cact_main_window_get_items_view(), cact_tree_view_get_items(), na_object_dump_tree, and na_object_free_items.
cact_menubar_maintainer_on_dump_clipboard()
void cact_menubar_maintainer_on_dump_clipboard (GtkAction * action, BaseWindow * window)
cact_menubar_maintainer_on_dump_clipboard: @action: the #GtkAction of the item. @window: the BaseWindow main application window.
Triggers the "Maintainer/Dump clipboard" item.
Definition at line 110 of file cact-menubar-maintainer.c.
References action, cact_clipboard_dump(), CACT_MAIN_WINDOW, and cact_main_window_get_clipboard().
cact_menubar_maintainer_on_dump_selection()
void cact_menubar_maintainer_on_dump_selection (GtkAction * action, BaseWindow * window)
cact_menubar_maintainer_on_dump_selection: @action: the #GtkAction of the item. @window: the BaseWindow main application window.
Triggers the "Maintainer/Dump selection" item.
Definition at line 60 of file cact-menubar-maintainer.c.
References action, BAR_WINDOW_VOID, and na_object_dump_tree.
cact_menubar_maintainer_on_list_modified_items()
void cact_menubar_maintainer_on_list_modified_items (GtkAction * action, BaseWindow * window)
cact_menubar_maintainer_on_list_modified_items: @action: the #GtkAction of the item. @window: the BaseWindow main application window.
Triggers the "Maintainer/List modified items" item.
Definition at line 94 of file cact-menubar-maintainer.c.
References action, CACT_MAIN_WINDOW, cact_main_window_get_items_view(), CACT_TREE_IEDITABLE, and cact_tree_ieditable_dump_modified().
cact_menubar_maintainer_on_test_function()
void cact_menubar_maintainer_on_test_function (GtkAction * action, BaseWindow * window)
Definition at line 119 of file cact-menubar-maintainer.c.
References action, base_application_is_willing_to_quit(), and base_window_get_application().
cact_menubar_maintainer_on_update_sensitivities()
void cact_menubar_maintainer_on_update_sensitivities (const CactMenubar * bar)
cact_menubar_maintainer_on_update_sensitivities: @bar: this CactMenubar object.
Update sensitivities on the Maintainer menu.
Definition at line 48 of file cact-menubar-maintainer.c.