MATE Desktop Environment: cact-export-ask.c File Reference
cact-export-ask.c File Reference
#include <glib/gi18n.h>
#include <api/na-object-api.h>
#include <core/na-exporter.h>
#include <core/na-export-format.h>
#include <core/na-gtk-utils.h>
#include <core/na-ioptions-list.h>
#include "cact-application.h"
#include "cact-export-ask.h"
#include "base-gtk-utils.h"
Functions
GType cact_export_ask_get_type (void)
gchar * cact_export_ask_user (BaseWindow *parent, NAObjectItem *item, gboolean first)
Function Documentation
cact_export_ask_get_type()
GType cact_export_ask_get_type (void)
Definition at line 90 of file cact-export-ask.c.
cact_export_ask_user()
gchar * cact_export_ask_user (BaseWindow * parent, NAObjectItem * item, gboolean first)
cact_export_ask_user: @parent: the CactAssistant parent of this dialog. @item: the NAObjectItem to be exported. @first: whether this is the first call of a series. On a first call, the user is really asked for his choice. The next times, the 'keep-last-choice' flag will be considered.
Initializes and runs the dialog.
This is a small dialog which is to be ran during export operations, when the set export format is 'Ask me'. Each exported file runs this dialog, unless the user selects the 'keep same choice' box.
Returns: the export format chosen by the user as a newly allocated string which should be g_free() by the caller. The function defaults to returning NA_IPREFS_DEFAULT_EXPORT_FORMAT.
When the user selects 'Keep same choice without asking me', this choice becomes his new preferred export format.
Definition at line 304 of file cact-export-ask.c.
References BASE_IS_WINDOW, BASE_PROP_PARENT, BASE_PROP_TOPLEVEL_NAME, BASE_PROP_WSP_NAME, BASE_PROP_XMLUI_FILENAME, BASE_WINDOW, base_window_run(), CACT_TYPE_EXPORT_ASK, EXPORTER_FORMAT_NOEXPORT, item, NA_IPREFS_ADMIN_PREFERENCES_LOCKED, NA_IPREFS_EXPORT_ASK_USER_KEEP_LAST_CHOICE, NA_IPREFS_EXPORT_ASK_USER_LAST_FORMAT, na_settings_get_boolean(), na_settings_get_string(), NULL, and CactExportAsk::private.