MATE Desktop Environment: cact-main-tab.c File Reference
cact-main-tab.c File Reference
#include <api/na-object-profile.h>
#include "cact-main-tab.h"
Functions
void cact_main_tab_init (CactMainWindow *window, gint num_page)
void cact_main_tab_enable_page (CactMainWindow *window, gint num_page, gboolean enabled)
gboolean cact_main_tab_is_page_enabled (CactMainWindow *window, gint num_page)
Function Documentation
cact_main_tab_enable_page()
void cact_main_tab_enable_page (CactMainWindow * window, gint num_page, gboolean enabled)
cact_main_tab_enable_page: @window: the CactMainWindow. @num_page: the page number, starting from zero. @enabled: whether the tab should be set sensitive or not.
Set the sensitivity of the tab.
Definition at line 67 of file cact-main-tab.c.
References BASE_WINDOW, base_window_get_widget(), and label.
cact_main_tab_init()
void cact_main_tab_init (CactMainWindow * window, gint num_page)
cact_main_tab_init: @window: the CactMainWindow. @num_page: the page number, starting from zero.
Common initialization of each page of the notebook.
Definition at line 48 of file cact-main-tab.c.
References BASE_SIGNAL_INITIALIZE_WINDOW, BASE_WINDOW, and base_window_signal_connect_with_data().
Referenced by cact_iaction_tab_init(), cact_ibasenames_tab_init(), cact_icapabilities_tab_init(), cact_icommand_tab_init(), cact_ienvironment_tab_init(), cact_iexecution_tab_init(), cact_ifolders_tab_init(), cact_imimetypes_tab_init(), cact_iproperties_tab_init(), and cact_ischemes_tab_init().
cact_main_tab_is_page_enabled()
gboolean cact_main_tab_is_page_enabled (CactMainWindow * window, gint num_page)
cact_main_tab_is_page_enabled: @window: the CactMainWindow. @num_page: the page number, starting from zero.
Returns: TRUE if the tab is sensitive, FALSE else.
Definition at line 88 of file cact-main-tab.c.
References BASE_WINDOW, and base_window_get_widget().