MATE Desktop Environment: cact-providers-list.c File Reference
cact-providers-list.c File Reference
#include <glib/gi18n.h>
#include <api/na-core-utils.h>
#include <api/na-object-api.h>
#include <core/na-io-provider.h>
#include "cact-application.h"
#include "base-gtk-utils.h"
#include "cact-providers-list.h"
Macros
#define PROVIDERS_LIST_DATA "cact-providers-list-data"
#define PROVIDERS_LIST_TREEVIEW "cact-providers-list-treeview"
Enumerations
enum {
PROVIDER_READABLE_COLUMN = 0 , PROVIDER_READABLE_MANDATORY_COLUMN , PROVIDER_WRITABLE_COLUMN , PROVIDER_WRITABLE_MANDATORY_COLUMN ,
PROVIDER_LIBELLE_COLUMN , PROVIDER_ID_COLUMN , PROVIDER_PROVIDER_COLUMN , PROVIDER_N_COLUMN
}
Functions
void cact_providers_list_create_model (GtkTreeView *treeview)
void cact_providers_list_init_view (BaseWindow *window, GtkTreeView *treeview)
void cact_providers_list_save (BaseWindow *window)
void cact_providers_list_dispose (BaseWindow *window)
Macro Definition Documentation
PROVIDERS_LIST_DATA
#define PROVIDERS_LIST_DATA "cact-providers-list-data"
Definition at line 82 of file cact-providers-list.c.
PROVIDERS_LIST_TREEVIEW
#define PROVIDERS_LIST_TREEVIEW "cact-providers-list-treeview"
Definition at line 83 of file cact-providers-list.c.
Referenced by cact_providers_list_dispose(), cact_providers_list_init_view(), and cact_providers_list_save().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROVIDER_READABLE_COLUMN
PROVIDER_READABLE_MANDATORY_COLUMN
PROVIDER_WRITABLE_COLUMN
PROVIDER_WRITABLE_MANDATORY_COLUMN
PROVIDER_LIBELLE_COLUMN
PROVIDER_ID_COLUMN
PROVIDER_PROVIDER_COLUMN
PROVIDER_N_COLUMN
Definition at line 47 of file cact-providers-list.c.
Function Documentation
cact_providers_list_create_model()
void cact_providers_list_create_model (GtkTreeView * treeview)
cact_providers_list_create_model: @treeview: the #GtkTreeView.
Create the treeview model when initially loading the widget from the UI manager.
Definition at line 112 of file cact-providers-list.c.
References _, data, FALSE, NULL, PROVIDER_LIBELLE_COLUMN, PROVIDER_N_COLUMN, PROVIDER_READABLE_COLUMN, PROVIDER_WRITABLE_COLUMN, and TRUE.
cact_providers_list_dispose()
void cact_providers_list_dispose (BaseWindow * window)
cact_providers_list_dispose: @treeview: the #GtkTreeView.
Release the content of the page when we are closing the Preferences dialog.
Definition at line 407 of file cact-providers-list.c.
References PROVIDERS_LIST_TREEVIEW.
cact_providers_list_init_view()
void cact_providers_list_init_view (BaseWindow * window, GtkTreeView * treeview)
cact_providers_list_init_view: @window: the parent BaseWindow which embeds the view. @treeview: the #GtkTreeView.
Connects signals at runtime initialization of the widget, and setup current default values.
Definition at line 196 of file cact-providers-list.c.
References BASE_IS_WINDOW, base_window_get_application(), CACT_APPLICATION, cact_application_get_updater(), data, na_updater_are_preferences_locked(), and PROVIDERS_LIST_TREEVIEW.
cact_providers_list_save()
void cact_providers_list_save (BaseWindow * window)
cact_providers_list_save: @window: the BaseWindow which embeds this treeview.
Save the I/O provider status as a user preference.
Definition at line 349 of file cact-providers-list.c.
References na_core_utils_slist_free(), NA_IPREFS_IO_PROVIDERS_WRITE_ORDER, na_settings_set_string_list(), NULL, and PROVIDERS_LIST_TREEVIEW.