MATE Desktop Environment: cact-schemes-list.h File Reference
cact-schemes-list.h File Reference
#include <gtk/gtk.h>
#include "base-window.h"
Typedefs
typedef void(* pf_new_selection_cb) (const gchar *, gboolean, void *)
Enumerations
enum { SCHEMES_LIST_FOR_PREFERENCES = 1 , SCHEMES_LIST_FOR_ADD_FROM_DEFAULTS }
Functions
void cact_schemes_list_create_model (GtkTreeView *treeview, guint mode)
void cact_schemes_list_init_view (GtkTreeView *treeview, BaseWindow *window, pf_new_selection_cb pf, void *user_data)
void cact_schemes_list_setup_values (BaseWindow *window, GSList *schemes)
void cact_schemes_list_show_all (BaseWindow *window)
gchar * cact_schemes_list_get_current_scheme (BaseWindow *window)
void cact_schemes_list_save_defaults (BaseWindow *window)
void cact_schemes_list_dispose (BaseWindow *window)
Typedef Documentation
pf_new_selection_cb
typedef void(* pf_new_selection_cb) (const gchar *, gboolean, void *)
SECTION: cact_schemes_list @short_description: Schemes list view management. cact/cact-schemes-list.h
This set of functions manages the schemes list view.
Up to 2.30.x, two modes were possible:
for action: the full list is displayed, and a check box is made active when the scheme is actually selected in the profile. Adding a scheme insert an editable new row (without the description). Inline edition of the scheme is possible. Removing a scheme is possible.
in preferences, when editing the default list of schemes the 'active' checkbox is not displayed the two columns 'scheme' and 'description' are editable inline adding/removing a scheme is possible
Starting with 2.31.x series.(future 3.0), the scheme conditions of a NAIContext are handled by cact-match-list.{c,h} set of function. This set of functions is only used: a) to edit the preferences add/remove scheme edit keyword and description In this mode, the widget is embedded in the Preferences notebook. Modifications are saved when user clicks the global OK button. b) to select a scheme from the default list schemes already used by the current NAIContext are marked as used edition of the current list is not available In this mode, widget is embedded in a dedicated CactAddSchemeDialog dialog box OK returns the current selection (only available if current scheme is not already used) Cancel returns NULL.
Definition at line 75 of file cact-schemes-list.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SCHEMES_LIST_FOR_PREFERENCES
SCHEMES_LIST_FOR_ADD_FROM_DEFAULTS
Definition at line 77 of file cact-schemes-list.h.
Function Documentation
cact_schemes_list_create_model()
void cact_schemes_list_create_model (GtkTreeView * treeview, guint mode)
cact_schemes_list_create_schemes_list: @treeview: the #GtkTreeView. @mode: whether we are opening this listview for preferences edition, or to add a new scheme from the default list.
Create the treeview model when initially loading the widget from the UI manager. Associates the SchemesListData structure to the widget.
The default list of schemes is displayed in two cases:
when adding a scheme to a NAObjectItem (cf. CactISchemesTab) so the schemes list is opened for selection
we have chosen to not allow default schemes list edition in this mode because we do not have ok/cancel buttons; the user may start with editing and does not have any way of cancel it
when editing the default schemes list in Preferences so each row may be edited edition is only allowed if preferences are not locked and default schemes list is not a mandatory pref.
Definition at line 133 of file cact-schemes-list.c.
References _, data, NULL, SCHEMES_DESC_COLUMN, SCHEMES_KEYWORD_COLUMN, SCHEMES_N_COLUMN, and TRUE.
cact_schemes_list_dispose()
void cact_schemes_list_dispose (BaseWindow * window)
cact_schemes_list_dispose: @treeview: the #GtkTreeView.
Definition at line 527 of file cact-schemes-list.c.
References SCHEMES_LIST_TREEVIEW.
cact_schemes_list_get_current_scheme()
gchar * cact_schemes_list_get_current_scheme (BaseWindow * window)
cact_schemes_list_get_current_scheme: @window: the BaseWindow which embeds this treeview.
Returns: the currently selected scheme, if any, as a newly allocated string which should be g_free() by the caller.
Definition at line 446 of file cact-schemes-list.c.
References NULL, SCHEMES_KEYWORD_COLUMN, and SCHEMES_LIST_TREEVIEW.
cact_schemes_list_init_view()
void cact_schemes_list_init_view (GtkTreeView * treeview, BaseWindow * window, pf_new_selection_cb pf, void * user_data)
cact_schemes_list_init_view: @treeview: the #GtkTreeView. @window: the parent BaseWindow which embeds the view. @pf: a callback function which will be called on selection change. @user_data: user data to be passed to the callback function.
Connects signals at runtime initialization of the widget, and displays the current default list of schemes.
When mode is for preferences, this is all that is required for runtime initialization.
When mode is for add from defaults, i.e. when editing NAIContext schemes conditions, then cact_schemes_list_setup_values() must also be called in order to actually setup the already used schemes.
Definition at line 199 of file cact-schemes-list.c.
References BASE_IS_WINDOW, base_window_get_application(), CACT_APPLICATION, cact_application_get_updater(), data, na_updater_are_preferences_locked(), SCHEMES_LIST_FOR_PREFERENCES, SCHEMES_LIST_TREEVIEW, and user_data.
cact_schemes_list_save_defaults()
void cact_schemes_list_save_defaults (BaseWindow * window)
cact_schemes_list_save_defaults: @window: the BaseWindow which embeds this treeview.
Save the list of schemes as a MateConf preference.
Default schemes are saved under a 'schemes' key as a list of strings, where each string is of the form 'keyword|description'.
Definition at line 480 of file cact-schemes-list.c.
References na_core_utils_slist_free(), NA_IPREFS_SCHEME_DEFAULT_LIST, na_settings_set_string_list(), and SCHEMES_LIST_TREEVIEW.
cact_schemes_list_setup_values()
void cact_schemes_list_setup_values (BaseWindow * window, GSList * schemes)
cact_schemes_list_setup_values: @window: the BaseWindow which embeds this treeview. @schemes: a #GSList of already used schemes.
Set the used schemes for the current NAIContext.
Definition at line 380 of file cact-schemes-list.c.
References SCHEMES_LIST_TREEVIEW.
cact_schemes_list_show_all()
void cact_schemes_list_show_all (BaseWindow * window)
cact_schemes_list_show_all: @window: the BaseWindow which embeds this treeview.
Update visibility of widgets after all widgets are showed.
Definition at line 418 of file cact-schemes-list.c.
References BASE_IS_WINDOW, data, SCHEMES_LIST_FOR_PREFERENCES, and SCHEMES_LIST_TREEVIEW.