MATE Desktop Environment: cadp-desktop-provider.c File Reference
cadp-desktop-provider.c File Reference
#include <glib/gi18n.h>
#include <string.h>
#include <api/na-core-utils.h>
#include <api/na-ifactory-provider.h>
#include "cadp-desktop-provider.h"
#include "cadp-formats.h"
#include "cadp-keys.h"
#include "cadp-monitor.h"
#include "cadp-reader.h"
#include "cadp-writer.h"
Functions
GType cadp_desktop_provider_get_type (void)
void cadp_desktop_provider_register_type (GTypeModule *module)
void cadp_desktop_provider_add_monitor (CappDesktopProvider *provider, const gchar *dir)
void cadp_desktop_provider_on_monitor_event (CappDesktopProvider *provider)
void cadp_desktop_provider_release_monitors (CappDesktopProvider *provider)
Function Documentation
cadp_desktop_provider_add_monitor()
void cadp_desktop_provider_add_monitor (CappDesktopProvider * provider, const gchar * dir)
Definition at line 348 of file cadp-desktop-provider.c.
References CADP_IS_DESKTOP_PROVIDER, cadp_monitor_new(), _CappDesktopProviderPrivate::dispose_has_run, _CappDesktopProviderPrivate::monitors, and CappDesktopProvider::private.
cadp_desktop_provider_get_type()
GType cadp_desktop_provider_get_type (void)
Definition at line 82 of file cadp-desktop-provider.c.
cadp_desktop_provider_on_monitor_event()
void cadp_desktop_provider_on_monitor_event (CappDesktopProvider * provider)
cadp_desktop_provider_on_monitor_event: @provider: this CappDesktopProvider object.
Factorize events received from GIO when monitoring desktop directories.
Definition at line 368 of file cadp-desktop-provider.c.
References CADP_IS_DESKTOP_PROVIDER, _CappDesktopProviderPrivate::dispose_has_run, na_timeout_event(), CappDesktopProvider::private, and _CappDesktopProviderPrivate::timeout.
cadp_desktop_provider_register_type()
void cadp_desktop_provider_register_type (GTypeModule * module)
Definition at line 88 of file cadp-desktop-provider.c.
References NA_TYPE_IEXPORTER, NA_TYPE_IFACTORY_PROVIDER, NA_TYPE_IIMPORTER, NA_TYPE_IIO_PROVIDER, and NULL.
Referenced by na_extension_startup().
cadp_desktop_provider_release_monitors()
void cadp_desktop_provider_release_monitors (CappDesktopProvider * provider)
cadp_desktop_provider_release_monitors: @provider: this CappDesktopProvider object.
Release previously set desktop monitors.
Definition at line 385 of file cadp-desktop-provider.c.
References CADP_IS_DESKTOP_PROVIDER, _CappDesktopProviderPrivate::monitors, NULL, and CappDesktopProvider::private.
Referenced by cadp_iio_provider_read_items().