MATE Desktop Environment: cadp-reader.c File Reference
cadp-reader.c File Reference
#include <glib/gi18n.h>
#include <stdlib.h>
#include <string.h>
#include <api/na-core-utils.h>
#include <api/na-data-types.h>
#include <api/na-ifactory-object-data.h>
#include <api/na-ifactory-provider.h>
#include <api/na-object-api.h>
#include "cadp-desktop-provider.h"
#include "cadp-keys.h"
#include "cadp-reader.h"
#include "cadp-utils.h"
#include "cadp-xdg-dirs.h"
Macros
#define ERR_NOT_DESKTOP _("The Desktop I/O Provider is not able to handle the URI")
Functions
GList * cadp_iio_provider_read_items (const NAIIOProvider *provider, GSList **messages)
guint cadp_reader_iimporter_import_from_uri (const NAIImporter *instance, void *parms_ptr)
void cadp_reader_ifactory_provider_read_start (const NAIFactoryProvider *reader, void *reader_data, const NAIFactoryObject *serializable, GSList **messages)
NADataBoxed * cadp_reader_ifactory_provider_read_data (const NAIFactoryProvider *reader, void *reader_data, const NAIFactoryObject *object, const NADataDef *def, GSList **messages)
void cadp_reader_ifactory_provider_read_done (const NAIFactoryProvider *reader, void *reader_data, const NAIFactoryObject *serializable, GSList **messages)
Macro Definition Documentation
ERR_NOT_DESKTOP
#define ERR_NOT_DESKTOP _("The Desktop I/O Provider is not able to handle the URI")
Definition at line 64 of file cadp-reader.c.
Referenced by cadp_reader_iimporter_import_from_uri().
Function Documentation
cadp_iio_provider_read_items()
GList * cadp_iio_provider_read_items (const NAIIOProvider * provider, GSList ** messages)
Definition at line 88 of file cadp-reader.c.
References CADP_DESKTOP_PROVIDER, cadp_desktop_provider_release_monitors(), item, NA_IS_IIO_PROVIDER, na_object_dump, and NULL.
cadp_reader_ifactory_provider_read_data()
NADataBoxed * cadp_reader_ifactory_provider_read_data (const NAIFactoryProvider * reader, void * reader_data, const NAIFactoryObject * object, const NADataDef * def, GSList ** messages)
Definition at line 486 of file cadp-reader.c.
References cadp_desktop_file_get_boolean(), cadp_desktop_file_get_locale_string(), cadp_desktop_file_get_string(), cadp_desktop_file_get_string_list(), cadp_desktop_file_get_uint(), CADP_DESKTOP_PROVIDER, CADP_GROUP_DESKTOP, CADP_GROUP_PROFILE, CADP_IS_DESKTOP_FILE, CADP_IS_DESKTOP_PROVIDER, NADataDef::default_value, NADataDef::desktop_entry, NA_BOXED, na_boxed_set_from_void(), na_core_utils_boolean_from_string(), na_core_utils_slist_free(), na_data_boxed_new(), NA_DATA_TYPE_BOOLEAN, NA_DATA_TYPE_LOCALE_STRING, NA_DATA_TYPE_STRING, NA_DATA_TYPE_STRING_LIST, NA_DATA_TYPE_UINT, NA_IS_IFACTORY_OBJECT, NA_IS_IFACTORY_PROVIDER, NA_IS_OBJECT_ITEM, NA_IS_OBJECT_PROFILE, na_object_get_id, NULL, and NADataDef::type.
cadp_reader_ifactory_provider_read_done()
void cadp_reader_ifactory_provider_read_done (const NAIFactoryProvider * reader, void * reader_data, const NAIFactoryObject * serializable, GSList ** messages)
Definition at line 584 of file cadp-reader.c.
References CADP_DESKTOP_PROVIDER, CADP_IS_DESKTOP_PROVIDER, NA_IS_IFACTORY_OBJECT, NA_IS_IFACTORY_PROVIDER, NA_IS_OBJECT_ACTION, NA_IS_OBJECT_ITEM, NA_OBJECT_ACTION, NA_OBJECT_ITEM, and na_object_set_readonly.
cadp_reader_ifactory_provider_read_start()
void cadp_reader_ifactory_provider_read_start (const NAIFactoryProvider * reader, void * reader_data, const NAIFactoryObject * serializable, GSList ** messages)
Definition at line 422 of file cadp-reader.c.
References CADP_DESKTOP_PROVIDER, CADP_IS_DESKTOP_PROVIDER, NA_IS_IFACTORY_OBJECT, NA_IS_IFACTORY_PROVIDER, NA_IS_OBJECT_ITEM, NA_IS_OBJECT_PROFILE, NA_OBJECT_ITEM, NA_OBJECT_PROFILE, and na_object_set_iversion.
cadp_reader_iimporter_import_from_uri()
guint cadp_reader_iimporter_import_from_uri (const NAIImporter * instance, void * parms_ptr)
cadp_reader_iimporter_import_from_uri: @instance: the NAIImporter provider. @parms: a #NAIImporterUriParms structure.
Imports an item.
Returns: the import operation code.
As soon as we have a valid .desktop file, we are most probably willing to successfully import an action or a menu of it.
GLib does not have any primitive to load a key file from an uri. So we have to load the file into memory, and then try to load the key file from the memory data.
Starting with N-A 3.2, we only honor the version 2 of NAIImporter interface, thus no more checking here against possible duplicate identifiers.
Definition at line 364 of file cadp-reader.c.
References cadp_desktop_file_new_from_uri(), CADP_DESKTOP_PROVIDER, CADP_IS_DESKTOP_PROVIDER, ERR_NOT_DESKTOP, FALSE, NAIImporterImportFromUriParmsv2::imported, IMPORTER_CODE_NOT_LOADABLE, IMPORTER_CODE_NOT_WILLING_TO, IMPORTER_CODE_OK, IMPORTER_CODE_PROGRAM_ERROR, NAIImporterImportFromUriParmsv2::messages, na_core_utils_file_is_loadable(), na_core_utils_slist_add_message(), NA_IS_IIMPORTER, NA_IS_OBJECT_ITEM, na_object_set_provider_data, na_object_set_readonly, NULL, and NAIImporterImportFromUriParmsv2::uri.