MATE Desktop Environment: cadp-xdg-dirs.h File Reference
cadp-xdg-dirs.h File Reference
#include <glib.h>
Functions
GSList * cadp_xdg_dirs_get_data_dirs (void)
gchar * cadp_xdg_dirs_get_user_data_dir (void)
GSList * cadp_xdg_dirs_get_system_data_dirs (void)
Function Documentation
cadp_xdg_dirs_get_data_dirs()
GSList * cadp_xdg_dirs_get_data_dirs (void)
cadp_xdg_dirs_get_data_dirs:
Returns: the ordered list of data directories, most important first, as a GSList of newly allocated strings.
The returned list, along with the pointed out strings, should be freed by the caller.
Definition at line 48 of file cadp-xdg-dirs.c.
References cadp_xdg_dirs_get_system_data_dirs(), cadp_xdg_dirs_get_user_data_dir(), and NULL.
cadp_xdg_dirs_get_system_data_dirs()
GSList * cadp_xdg_dirs_get_system_data_dirs (void)
cadp_xdg_dirs_get_system_data_dirs:
Returns: the set of preference ordered base directories relative to which data files should be written, as a GSList of newly allocated strings.
This set of directories is defined by the environment variable XDG_DATA_DIRS. It defaults to /usr/local/share:/usr/share.
source: http://standards.freedesktop.org/basedir-spec/basedir-spec-0.6.html
The returned list, along with the pointed out strings, should be freed by the caller.
Definition at line 102 of file cadp-xdg-dirs.c.
References na_core_utils_slist_from_array().
Referenced by cadp_xdg_dirs_get_data_dirs().
cadp_xdg_dirs_get_user_data_dir()
gchar * cadp_xdg_dirs_get_user_data_dir (void)
cadp_xdg_dirs_get_user_data_dir:
Returns: the path to the single base directory relative to which user-specific data files should be written, as a newly allocated string.
This directory is defined by the environment variable XDG_DATA_HOME. It defaults to ~/.local/share. cf. http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
The returned string should be g_free() by the caller.
Definition at line 77 of file cadp-xdg-dirs.c.
Referenced by cadp_iio_provider_is_able_to_write(), cadp_iio_provider_write_item(), and cadp_xdg_dirs_get_data_dirs().