MATE Desktop Environment: cadp-utils.c File Reference
cadp-utils.c File Reference
#include <errno.h>
#include <gio/gio.h>
#include <glib/gstdio.h>
#include <string.h>
#include <api/na-core-utils.h>
#include "cadp-desktop-provider.h"
#include "cadp-utils.h"
Functions
GSList * cadp_utils_gslist_remove_from (GSList *list, const gchar *string)
gboolean cadp_utils_uri_delete (const gchar *uri)
gboolean cadp_utils_uri_is_writable (const gchar *uri)
Function Documentation
cadp_utils_gslist_remove_from()
GSList * cadp_utils_gslist_remove_from (GSList * list, const gchar * string)
cadp_utils_gslist_remove_from: @list: the #GSList from which remove the @string. @string: the string to be removed.
Removes a @string from a string list, then frees the removed @string.
Definition at line 52 of file cadp-utils.c.
References na_core_utils_str_collate().
cadp_utils_uri_delete()
gboolean cadp_utils_uri_delete (const gchar * uri)
Definition at line 72 of file cadp-utils.c.
References FALSE, na_core_utils_file_delete(), and NULL.
Referenced by cadp_iio_provider_delete_item().
cadp_utils_uri_is_writable()
gboolean cadp_utils_uri_is_writable (const gchar * uri)
cadp_utils_uri_is_writable: @uri: the URI of the file to be tested.
Returns: TRUE if the file is writable, FALSE else.
Please note that this type of test is subject to race conditions, as the file may become unwritable after a successful test, but before the caller has been able to actually write into it.
There is no "super-test". Just try...
Definition at line 108 of file cadp-utils.c.
References error, FALSE, and NULL.