MATE Desktop Environment: caja-file-utilities.c File Reference
caja-file-utilities.c File Reference
#include <config.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <glib/gstdio.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <eel/eel-glib-extensions.h>
#include <eel/eel-stock-dialogs.h>
#include <eel/eel-string.h>
#include <eel/eel-debug.h>
#include "caja-file-utilities.h"
#include "caja-global-preferences.h"
#include "caja-lib-self-check-functions.h"
#include "caja-metadata.h"
#include "caja-file.h"
#include "caja-file-operations.h"
#include "caja-search-directory.h"
#include "caja-signaller.h"
Macros
#define DEFAULT_CAJA_DIRECTORY_MODE (0755)
#define DESKTOP_DIRECTORY_NAME "Desktop"
#define DEFAULT_DESKTOP_DIRECTORY_MODE (0755)
#define GSM_NAME "org.gnome.SessionManager"
#define GSM_PATH "/org/gnome/SessionManager"
#define GSM_INTERFACE "org.gnome.SessionManager"
#define INHIBIT_LOGOUT (1U)
#define INHIBIT_SUSPEND (4U)
Functions
char * caja_compute_title_for_location (GFile *location)
char * caja_get_user_directory (void)
char * caja_get_accel_map_file (void)
char * caja_get_xdg_dir (const char *type)
char * caja_get_desktop_directory (void)
GFile * caja_get_desktop_location (void)
char * caja_get_desktop_directory_uri (void)
char * caja_get_home_directory_uri (void)
gboolean caja_should_use_templates_directory (void)
char * caja_get_templates_directory (void)
void caja_create_templates_directory (void)
char * caja_get_templates_directory_uri (void)
gboolean caja_is_home_directory_file (GFile *dir, const char *filename)
gboolean caja_is_home_directory (GFile *dir)
gboolean caja_is_root_directory (GFile *dir)
gboolean caja_is_desktop_directory_file (GFile *dir, const char *file)
gboolean caja_is_desktop_directory (GFile *dir)
GMount * caja_get_mounted_mount_for_root (GFile *location)
char * caja_get_pixmap_directory (void)
char * caja_pixmap_file (const char *partial_path)
char * caja_get_data_file_path (const char *partial_path)
char * caja_ensure_unique_file_name (const char *directory_uri, const char *base_name, const char *extension)
GFile * caja_find_existing_uri_in_hierarchy (GFile *location)
gboolean caja_is_engrampa_installed (void)
int caja_inhibit_power_manager (const char *message)
void caja_uninhibit_power_manager (gint cookie)
gboolean caja_is_in_system_dir (GFile *file)
gboolean caja_is_in_desktop_dir (GFile *file)
GHashTable * caja_trashed_files_get_original_directories (GList *files, GList **unhandled_files)
void caja_restore_files_from_trash (GList *files, GtkWindow *parent_window)
char * caja_get_filesystem_id_by_location (GFile *location, gboolean follow)
char * caja_get_filesystem_id_by_uri (const char *uri, gboolean follow)
void caja_self_check_file_utilities (void)
Macro Definition Documentation
DEFAULT_CAJA_DIRECTORY_MODE
#define DEFAULT_CAJA_DIRECTORY_MODE (0755)
Definition at line 46 of file caja-file-utilities.c.
Referenced by caja_create_templates_directory(), and caja_get_user_directory().
DEFAULT_DESKTOP_DIRECTORY_MODE
#define DEFAULT_DESKTOP_DIRECTORY_MODE (0755)
Definition at line 49 of file caja-file-utilities.c.
Referenced by caja_get_desktop_directory().
DESKTOP_DIRECTORY_NAME
#define DESKTOP_DIRECTORY_NAME "Desktop"
Definition at line 48 of file caja-file-utilities.c.
Referenced by caja_get_xdg_dir().
GSM_INTERFACE
#define GSM_INTERFACE "org.gnome.SessionManager"
Definition at line 963 of file caja-file-utilities.c.
Referenced by caja_inhibit_power_manager(), and caja_uninhibit_power_manager().
GSM_NAME
#define GSM_NAME "org.gnome.SessionManager"
Definition at line 961 of file caja-file-utilities.c.
Referenced by caja_inhibit_power_manager(), and caja_uninhibit_power_manager().
GSM_PATH
#define GSM_PATH "/org/gnome/SessionManager"
Definition at line 962 of file caja-file-utilities.c.
Referenced by caja_inhibit_power_manager(), and caja_uninhibit_power_manager().
INHIBIT_LOGOUT
#define INHIBIT_LOGOUT (1U)
Definition at line 968 of file caja-file-utilities.c.
Referenced by caja_inhibit_power_manager().
INHIBIT_SUSPEND
#define INHIBIT_SUSPEND (4U)
Definition at line 969 of file caja-file-utilities.c.
Referenced by caja_inhibit_power_manager().
Function Documentation
caja_compute_title_for_location()
char * caja_compute_title_for_location (GFile * location)
Definition at line 56 of file caja-file-utilities.c.
References caja_file_get(), caja_file_get_description(), caja_file_get_display_name(), caja_file_unref(), and NULL.
Referenced by caja_window_slot_get_title().
caja_create_templates_directory()
void caja_create_templates_directory (void)
Definition at line 605 of file caja-file-utilities.c.
References caja_get_templates_directory(), and DEFAULT_CAJA_DIRECTORY_MODE.
caja_ensure_unique_file_name()
char * caja_ensure_unique_file_name (const char * directory_uri, const char * base_name, const char * extension)
Definition at line 870 of file caja-file-utilities.c.
References NULL.
Referenced by caja_link_local_create().
caja_find_existing_uri_in_hierarchy()
GFile * caja_find_existing_uri_in_hierarchy (GFile * location)
Definition at line 920 of file caja-file-utilities.c.
References NULL.
caja_get_accel_map_file()
char * caja_get_accel_map_file (void)
caja_get_accel_map_file:
Get the path for the filename containing caja accelerator map. The filename need not exist.
Return value: the filename path
Definition at line 178 of file caja-file-utilities.c.
References NULL.
caja_get_data_file_path()
char * caja_get_data_file_path (const char * partial_path)
Definition at line 843 of file caja-file-utilities.c.
References caja_get_user_directory(), and NULL.
caja_get_desktop_directory()
char * caja_get_desktop_directory (void)
caja_get_desktop_directory:
Get the path for the directory containing files on the desktop.
Return value: the directory path.
Definition at line 522 of file caja-file-utilities.c.
References caja_preferences, CAJA_PREFERENCES_DESKTOP_IS_HOME_DIR, and DEFAULT_DESKTOP_DIRECTORY_MODE.
Referenced by caja_get_desktop_directory_uri().
caja_get_desktop_directory_uri()
char * caja_get_desktop_directory_uri (void)
caja_get_desktop_directory_uri:
Get the uri for the directory containing files on the desktop.
Return value: the directory path.
Definition at line 568 of file caja-file-utilities.c.
References caja_get_desktop_directory(), and NULL.
Referenced by caja_link_local_create().
caja_get_desktop_location()
GFile * caja_get_desktop_location (void)
Definition at line 548 of file caja-file-utilities.c.
Referenced by caja_drag_default_drop_action_for_icons(), caja_drag_items_on_desktop(), and caja_file_operations_copy().
caja_get_filesystem_id_by_location()
char * caja_get_filesystem_id_by_location (GFile * location, gboolean follow)
Definition at line 1297 of file caja-file-utilities.c.
References NULL.
Referenced by caja_get_filesystem_id_by_uri().
caja_get_filesystem_id_by_uri()
char * caja_get_filesystem_id_by_uri (const char * uri, gboolean follow)
Definition at line 1321 of file caja-file-utilities.c.
References caja_get_filesystem_id_by_location().
caja_get_home_directory_uri()
char * caja_get_home_directory_uri (void)
Definition at line 581 of file caja-file-utilities.c.
References NULL.
caja_get_mounted_mount_for_root()
GMount * caja_get_mounted_mount_for_root (GFile * location)
Definition at line 763 of file caja-file-utilities.c.
References NULL.
caja_get_pixmap_directory()
char * caja_get_pixmap_directory (void)
caja_get_pixmap_directory
Get the path for the directory containing Caja pixmaps.
Return value: the directory path.
Definition at line 812 of file caja-file-utilities.c.
References DATADIR.
Referenced by caja_pixmap_file().
caja_get_templates_directory()
char * caja_get_templates_directory (void)
Definition at line 599 of file caja-file-utilities.c.
References caja_get_xdg_dir().
Referenced by caja_create_templates_directory(), and caja_get_templates_directory_uri().
caja_get_templates_directory_uri()
char * caja_get_templates_directory_uri (void)
Definition at line 618 of file caja-file-utilities.c.
References caja_get_templates_directory(), and NULL.
caja_get_user_directory()
char * caja_get_user_directory (void)
caja_get_user_directory:
Get the path for the directory containing caja settings.
Return value: the directory path.
Definition at line 92 of file caja-file-utilities.c.
References DEFAULT_CAJA_DIRECTORY_MODE, FALSE, NULL, and TRUE.
Referenced by caja_get_data_file_path().
caja_get_xdg_dir()
char * caja_get_xdg_dir (const char * type)
Definition at line 473 of file caja-file-utilities.c.
References DESKTOP_DIRECTORY_NAME, and NULL.
Referenced by caja_get_templates_directory(), and caja_should_use_templates_directory().
caja_inhibit_power_manager()
int caja_inhibit_power_manager (const char * message)
caja_inhibit_power_manager: @message: a human readable message for the reason why power management is being suspended.
Inhibits the power manager from logging out or suspending the machine (e.g. whenever Caja is doing file operations).
Returns: an integer cookie, which must be passed to caja_uninhibit_power_manager() to resume normal power management.
Definition at line 1005 of file caja-file-utilities.c.
References connection, error, GSM_INTERFACE, GSM_NAME, GSM_PATH, INHIBIT_LOGOUT, INHIBIT_SUSPEND, message(), and NULL.
caja_is_desktop_directory()
gboolean caja_is_desktop_directory (GFile * dir)
Definition at line 743 of file caja-file-utilities.c.
References caja_preferences, CAJA_PREFERENCES_DESKTOP_IS_HOME_DIR, NULL, and TRUE.
Referenced by caja_directory_is_desktop_directory(), and caja_file_is_in_desktop().
caja_is_desktop_directory_file()
gboolean caja_is_desktop_directory_file (GFile * dir, const char * file)
Definition at line 721 of file caja-file-utilities.c.
References caja_preferences, CAJA_PREFERENCES_DESKTOP_IS_HOME_DIR, NULL, and TRUE.
Referenced by caja_file_is_desktop_directory().
caja_is_engrampa_installed()
gboolean caja_is_engrampa_installed (void)
Definition at line 947 of file caja-file-utilities.c.
References FALSE, and TRUE.
Referenced by fm_directory_view_move_copy_items().
caja_is_home_directory()
gboolean caja_is_home_directory (GFile * dir)
Definition at line 695 of file caja-file-utilities.c.
References NULL.
caja_is_home_directory_file()
gboolean caja_is_home_directory_file (GFile * dir, const char * filename)
Definition at line 674 of file caja-file-utilities.c.
References NULL.
Referenced by caja_file_is_home().
caja_is_in_desktop_dir()
gboolean caja_is_in_desktop_dir (GFile * file)
Definition at line 1132 of file caja-file-utilities.c.
References FALSE, and TRUE.
caja_is_in_system_dir()
gboolean caja_is_in_system_dir (GFile * file)
Definition at line 1099 of file caja-file-utilities.c.
References FALSE, NULL, and TRUE.
caja_is_root_directory()
gboolean caja_is_root_directory (GFile * dir)
Definition at line 708 of file caja-file-utilities.c.
References NULL.
caja_pixmap_file()
char * caja_pixmap_file (const char * partial_path)
Definition at line 822 of file caja-file-utilities.c.
References caja_get_pixmap_directory(), DATADIR, and NULL.
Referenced by caja_customization_data_new().
caja_restore_files_from_trash()
void caja_restore_files_from_trash (GList * files, GtkWindow * parent_window)
Definition at line 1239 of file caja-file-utilities.c.
References _, CAJA_FILE, caja_file_get_display_name(), caja_file_get_location(), caja_file_list_unref(), caja_file_operations_move(), caja_trashed_files_get_original_directories(), eel_show_warning_dialog(), message(), and NULL.
caja_self_check_file_utilities()
void caja_self_check_file_utilities (void)
Definition at line 1335 of file caja-file-utilities.c.
caja_should_use_templates_directory()
gboolean caja_should_use_templates_directory (void)
Definition at line 587 of file caja-file-utilities.c.
References caja_get_xdg_dir().
caja_trashed_files_get_original_directories()
GHashTable * caja_trashed_files_get_original_directories (GList * files, GList ** unhandled_files)
Definition at line 1157 of file caja-file-utilities.c.
References CAJA_FILE, caja_file_get_parent(), caja_file_get_trash_original_file(), caja_file_list_unref(), caja_file_ref(), caja_file_unref(), and NULL.
Referenced by caja_restore_files_from_trash().
caja_uninhibit_power_manager()
void caja_uninhibit_power_manager (gint cookie)
caja_uninhibit_power_manager: @cookie: the cookie value returned by caja_inhibit_power_manager()
Uninhibits power management. This function must be called after the task which inhibited power management has finished, or the system will not return to normal power management.
Definition at line 1059 of file caja-file-utilities.c.
References connection, error, GSM_INTERFACE, GSM_NAME, GSM_PATH, and NULL.