MATE Desktop Environment: caja-undostack-manager.h File Reference
caja-undostack-manager.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
Classes
struct _CajaUndoStackMenuData
struct _CajaUndoStackManager
struct _CajaUndoStackManagerClass
Macros
#define TYPE_CAJA_UNDOSTACK_MANAGER (caja_undostack_manager_get_type())
#define CAJA_UNDOSTACK_MANAGER(object)
#define CAJA_UNDOSTACK_MANAGER_CLASS(klass)
#define IS_CAJA_UNDOSTACK_MANAGER(object)
#define IS_CAJA_UNDOSTACK_MANAGER_CLASS(klass)
#define CAJA_UNDOSTACK_MANAGER_GET_CLASS(object)
Typedefs
typedef struct _CajaUndoStackActionData CajaUndoStackActionData
typedef struct _CajaUndoStackMenuData CajaUndoStackMenuData
typedef void(* CajaUndostackFinishCallback) (gpointer data)
typedef struct _CajaUndoStackManagerPrivate CajaUndoStackManagerPrivate
typedef struct _CajaUndoStackManager CajaUndoStackManager
typedef struct _CajaUndoStackManagerClass CajaUndoStackManagerClass
Enumerations
enum CajaUndoStackActionType {
CAJA_UNDOSTACK_COPY , CAJA_UNDOSTACK_DUPLICATE , CAJA_UNDOSTACK_MOVE , CAJA_UNDOSTACK_RENAME ,
CAJA_UNDOSTACK_CREATEEMPTYFILE , CAJA_UNDOSTACK_CREATEFILEFROMTEMPLATE , CAJA_UNDOSTACK_CREATEFOLDER , CAJA_UNDOSTACK_MOVETOTRASH ,
CAJA_UNDOSTACK_CREATELINK , CAJA_UNDOSTACK_DELETE , CAJA_UNDOSTACK_RESTOREFROMTRASH , CAJA_UNDOSTACK_SETPERMISSIONS ,
CAJA_UNDOSTACK_RECURSIVESETPERMISSIONS , CAJA_UNDOSTACK_CHANGEOWNER , CAJA_UNDOSTACK_CHANGEGROUP
}
Functions
GType caja_undostack_manager_get_type (void)
void caja_undostack_manager_add_action (CajaUndoStackManager *manager, CajaUndoStackActionData *action)
void caja_undostack_manager_undo (CajaUndoStackManager *manager, GtkWidget *parent_view, CajaUndostackFinishCallback cb)
void caja_undostack_manager_redo (CajaUndoStackManager *manager, GtkWidget *parent_view, CajaUndostackFinishCallback cb)
CajaUndoStackActionData * caja_undostack_manager_data_new (CajaUndoStackActionType type, gint items_count)
gboolean caja_undostack_manager_is_undo_redo (CajaUndoStackManager *manager)
void caja_undostack_manager_trash_has_emptied (CajaUndoStackManager *manager)
CajaUndoStackManager * caja_undostack_manager_instance (void)
void caja_undostack_manager_data_set_src_dir (CajaUndoStackActionData *data, GFile *src)
void caja_undostack_manager_data_set_dest_dir (CajaUndoStackActionData *data, GFile *dest)
void caja_undostack_manager_data_add_origin_target_pair (CajaUndoStackActionData *data, GFile *origin, GFile *target)
void caja_undostack_manager_data_set_create_data (CajaUndoStackActionData *data, char *target_uri, char *template_uri)
void caja_undostack_manager_data_set_rename_information (CajaUndoStackActionData *data, GFile *old_file, GFile *new_file)
guint64 caja_undostack_manager_get_file_modification_time (GFile *file)
void caja_undostack_manager_data_add_trashed_file (CajaUndoStackActionData *data, GFile *file, guint64 mtime)
void caja_undostack_manager_request_menu_update (CajaUndoStackManager *manager)
void caja_undostack_manager_data_add_file_permissions (CajaUndoStackActionData *data, GFile *file, guint32 permission)
void caja_undostack_manager_data_set_recursive_permissions (CajaUndoStackActionData *data, guint32 file_permissions, guint32 file_mask, guint32 dir_permissions, guint32 dir_mask)
void caja_undostack_manager_data_set_file_permissions (CajaUndoStackActionData *data, char *uri, guint32 current_permissions, guint32 new_permissions)
void caja_undostack_manager_data_set_owner_change_information (CajaUndoStackActionData *data, char *uri, const char *current_user, const char *new_user)
void caja_undostack_manager_data_set_group_change_information (CajaUndoStackActionData *data, char *uri, const char *current_group, const char *new_group)
Macro Definition Documentation
CAJA_UNDOSTACK_MANAGER
#define CAJA_UNDOSTACK_MANAGER (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST((object), TYPE_CAJA_UNDOSTACK_MANAGER, CajaUndoStackManager))
Definition at line 91 of file caja-undostack-manager.h.
CAJA_UNDOSTACK_MANAGER_CLASS
#define CAJA_UNDOSTACK_MANAGER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST((klass), TYPE_CAJA_UNDOSTACK_MANAGER, CajaUndoStackManagerClass))
Definition at line 94 of file caja-undostack-manager.h.
CAJA_UNDOSTACK_MANAGER_GET_CLASS
#define CAJA_UNDOSTACK_MANAGER_GET_CLASS (object)
Value:
(G_TYPE_INSTANCE_GET_CLASS((object), TYPE_CAJA_UNDOSTACK_MANAGER, CajaUndoStackManagerClass))
Definition at line 103 of file caja-undostack-manager.h.
IS_CAJA_UNDOSTACK_MANAGER
#define IS_CAJA_UNDOSTACK_MANAGER (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE((object), TYPE_CAJA_UNDOSTACK_MANAGER))
Definition at line 97 of file caja-undostack-manager.h.
IS_CAJA_UNDOSTACK_MANAGER_CLASS
#define IS_CAJA_UNDOSTACK_MANAGER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass), TYPE_CAJA_UNDOSTACK_MANAGER))
Definition at line 100 of file caja-undostack-manager.h.
TYPE_CAJA_UNDOSTACK_MANAGER
#define TYPE_CAJA_UNDOSTACK_MANAGER (caja_undostack_manager_get_type())
Definition at line 89 of file caja-undostack-manager.h.
Referenced by caja_undostack_manager_instance().
Typedef Documentation
CajaUndoStackActionData
typedef struct _CajaUndoStackActionData CajaUndoStackActionData
Definition at line 57 of file caja-undostack-manager.h.
CajaUndostackFinishCallback
typedef void(* CajaUndostackFinishCallback) (gpointer data)
Definition at line 70 of file caja-undostack-manager.h.
CajaUndoStackManager
typedef struct _CajaUndoStackManager CajaUndoStackManager
CajaUndoStackManagerClass
typedef struct _CajaUndoStackManagerClass CajaUndoStackManagerClass
CajaUndoStackManagerPrivate
typedef struct _CajaUndoStackManagerPrivate CajaUndoStackManagerPrivate
Definition at line 73 of file caja-undostack-manager.h.
CajaUndoStackMenuData
typedef struct _CajaUndoStackMenuData CajaUndoStackMenuData
Definition at line 59 of file caja-undostack-manager.h.
Enumeration Type Documentation
CajaUndoStackActionType
enum CajaUndoStackActionType
Enumerator
CAJA_UNDOSTACK_COPY
CAJA_UNDOSTACK_DUPLICATE
CAJA_UNDOSTACK_MOVE
CAJA_UNDOSTACK_RENAME
CAJA_UNDOSTACK_CREATEEMPTYFILE
CAJA_UNDOSTACK_CREATEFILEFROMTEMPLATE
CAJA_UNDOSTACK_CREATEFOLDER
CAJA_UNDOSTACK_MOVETOTRASH
CAJA_UNDOSTACK_CREATELINK
CAJA_UNDOSTACK_DELETE
CAJA_UNDOSTACK_RESTOREFROMTRASH
CAJA_UNDOSTACK_SETPERMISSIONS
CAJA_UNDOSTACK_RECURSIVESETPERMISSIONS
CAJA_UNDOSTACK_CHANGEOWNER
CAJA_UNDOSTACK_CHANGEGROUP
Definition at line 38 of file caja-undostack-manager.h.
Function Documentation
caja_undostack_manager_add_action()
void caja_undostack_manager_add_action (CajaUndoStackManager * manager, CajaUndoStackActionData * action)
Adds an operation to the stack
Definition at line 738 of file caja-undostack-manager.c.
References action, and NULL.
Referenced by caja_file_operation_free(), caja_file_set_group(), caja_file_set_owner(), and caja_file_set_permissions().
caja_undostack_manager_data_add_file_permissions()
void caja_undostack_manager_data_add_file_permissions (CajaUndoStackActionData * data, GFile * file, guint32 permission)
Pushes a recursive permission change data in an existing undo data container
Definition at line 957 of file caja-undostack-manager.c.
References data, and TRUE.
caja_undostack_manager_data_add_origin_target_pair()
void caja_undostack_manager_data_add_origin_target_pair (CajaUndoStackActionData * data, GFile * origin, GFile * target)
Pushes an origin, target pair in an existing undo data container
Definition at line 917 of file caja-undostack-manager.c.
References data, and TRUE.
caja_undostack_manager_data_add_trashed_file()
void caja_undostack_manager_data_add_trashed_file (CajaUndoStackActionData * data, GFile * file, guint64 mtime)
Pushes an trashed file with modification time in an existing undo data container
Definition at line 936 of file caja-undostack-manager.c.
References data, and TRUE.
caja_undostack_manager_data_new()
CajaUndoStackActionData * caja_undostack_manager_data_new (CajaUndoStackActionType type, gint items_count)
Returns a new undo data container
Definition at line 869 of file caja-undostack-manager.c.
References CAJA_UNDOSTACK_MOVETOTRASH, CAJA_UNDOSTACK_RECURSIVESETPERMISSIONS, and data.
Referenced by caja_file_operations_copy(), caja_file_operations_duplicate(), caja_file_operations_link(), caja_file_operations_move(), caja_file_operations_new_file(), caja_file_operations_new_file_from_template(), caja_file_operations_new_folder(), caja_file_rename(), caja_file_set_group(), caja_file_set_owner(), caja_file_set_permissions(), and caja_file_set_permissions_recursive().
caja_undostack_manager_data_set_create_data()
void caja_undostack_manager_data_set_create_data (CajaUndoStackActionData * data, char * target_uri, char * template)
Sets create file information
Definition at line 1056 of file caja-undostack-manager.c.
References data, and TRUE.
caja_undostack_manager_data_set_dest_dir()
void caja_undostack_manager_data_set_dest_dir (CajaUndoStackActionData * data, GFile * dest)
Sets the destination directory
Definition at line 905 of file caja-undostack-manager.c.
References data, and dest.
Referenced by caja_file_operations_copy(), caja_file_operations_duplicate(), caja_file_operations_link(), caja_file_operations_move(), and caja_file_set_permissions_recursive().
caja_undostack_manager_data_set_file_permissions()
void caja_undostack_manager_data_set_file_permissions (CajaUndoStackActionData * data, char * uri, guint32 current_permissions, guint32 new_permissions)
Sets the original file permission in an existing undo data container
Definition at line 979 of file caja-undostack-manager.c.
References data, and TRUE.
Referenced by caja_file_set_permissions().
caja_undostack_manager_data_set_group_change_information()
void caja_undostack_manager_data_set_group_change_information (CajaUndoStackActionData * data, char * uri, const char * current_group, const char * new_group)
Sets the change group information in an existing undo data container
Definition at line 1017 of file caja-undostack-manager.c.
References data, and TRUE.
Referenced by caja_file_set_group().
caja_undostack_manager_data_set_owner_change_information()
void caja_undostack_manager_data_set_owner_change_information (CajaUndoStackActionData * data, char * uri, const char * current_user, const char * new_user)
Sets the change owner information in an existing undo data container
Definition at line 998 of file caja-undostack-manager.c.
References data, and TRUE.
Referenced by caja_file_set_owner().
caja_undostack_manager_data_set_recursive_permissions()
void caja_undostack_manager_data_set_recursive_permissions (CajaUndoStackActionData * data, guint32 file_permissions, guint32 file_mask, guint32 dir_permissions, guint32 dir_mask)
Sets the permission change mask
Definition at line 1036 of file caja-undostack-manager.c.
References data, and TRUE.
Referenced by caja_file_set_permissions_recursive().
caja_undostack_manager_data_set_rename_information()
void caja_undostack_manager_data_set_rename_information (CajaUndoStackActionData * data, GFile * old_file, GFile * new_file)
Sets rename information
Definition at line 1072 of file caja-undostack-manager.c.
References data, and TRUE.
caja_undostack_manager_data_set_src_dir()
void caja_undostack_manager_data_set_src_dir (CajaUndoStackActionData * data, GFile * src)
Sets the source directory
Definition at line 892 of file caja-undostack-manager.c.
References data.
Referenced by caja_file_operations_copy(), caja_file_operations_duplicate(), caja_file_operations_link(), and caja_file_operations_move().
caja_undostack_manager_get_file_modification_time()
guint64 caja_undostack_manager_get_file_modification_time (GFile * file)
Returns the modification time for the given file (used for undo trash)
Definition at line 846 of file caja-undostack-manager.c.
References FALSE, and NULL.
caja_undostack_manager_get_type()
GType caja_undostack_manager_get_type (void)
References action, cb, data, and dest.
caja_undostack_manager_instance()
CajaUndoStackManager * caja_undostack_manager_instance (void)
Returns the undo stack manager instance (singleton pattern)
Definition at line 348 of file caja-undostack-manager.c.
References NULL, and TYPE_CAJA_UNDOSTACK_MANAGER.
Referenced by caja_file_operation_free(), caja_file_operations_copy(), caja_file_operations_duplicate(), caja_file_operations_link(), caja_file_operations_move(), caja_file_operations_new_file(), caja_file_operations_new_file_from_template(), caja_file_operations_new_folder(), caja_file_rename(), caja_file_set_group(), caja_file_set_owner(), caja_file_set_permissions(), and caja_file_set_permissions_recursive().
caja_undostack_manager_is_undo_redo()
gboolean caja_undostack_manager_is_undo_redo (CajaUndoStackManager * manager)
True if undoing / redoing
Definition at line 364 of file caja-undostack-manager.c.
References FALSE, and TRUE.
Referenced by caja_file_operations_copy(), caja_file_operations_duplicate(), caja_file_operations_link(), caja_file_operations_move(), caja_file_operations_new_file(), caja_file_operations_new_file_from_template(), caja_file_operations_new_folder(), caja_file_rename(), caja_file_set_group(), caja_file_set_owner(), caja_file_set_permissions(), and caja_file_set_permissions_recursive().
caja_undostack_manager_redo()
void caja_undostack_manager_redo (CajaUndoStackManager * manager, GtkWidget * parent_view, CajaUndostackFinishCallback cb)
Redoes the last file operation
Definition at line 385 of file caja-undostack-manager.c.
References action, caja_file_get_by_uri(), caja_file_operations_copy(), caja_file_operations_duplicate(), caja_file_operations_link(), caja_file_operations_move(), caja_file_operations_new_file(), caja_file_operations_new_file_from_template(), caja_file_operations_new_folder(), caja_file_operations_trash_or_delete(), caja_file_rename(), caja_file_set_group(), caja_file_set_owner(), caja_file_set_permissions(), caja_file_set_permissions_recursive(), CAJA_UNDOSTACK_CHANGEGROUP, CAJA_UNDOSTACK_CHANGEOWNER, CAJA_UNDOSTACK_COPY, CAJA_UNDOSTACK_CREATEEMPTYFILE, CAJA_UNDOSTACK_CREATEFILEFROMTEMPLATE, CAJA_UNDOSTACK_CREATEFOLDER, CAJA_UNDOSTACK_CREATELINK, CAJA_UNDOSTACK_DELETE, CAJA_UNDOSTACK_DUPLICATE, CAJA_UNDOSTACK_MOVE, CAJA_UNDOSTACK_MOVETOTRASH, CAJA_UNDOSTACK_RECURSIVESETPERMISSIONS, CAJA_UNDOSTACK_RENAME, CAJA_UNDOSTACK_RESTOREFROMTRASH, CAJA_UNDOSTACK_SETPERMISSIONS, cb, FALSE, NULL, and TRUE.
caja_undostack_manager_request_menu_update()
void caja_undostack_manager_request_menu_update (CajaUndoStackManager * manager)
Definition at line 375 of file caja-undostack-manager.c.
caja_undostack_manager_trash_has_emptied()
void caja_undostack_manager_trash_has_emptied (CajaUndoStackManager * manager)
Callback after emptying the trash
Definition at line 805 of file caja-undostack-manager.c.
References action, CAJA_UNDOSTACK_MOVETOTRASH, and NULL.
caja_undostack_manager_undo()
void caja_undostack_manager_undo (CajaUndoStackManager * manager, GtkWidget * parent_view, CajaUndostackFinishCallback cb)
Undoes the last file operation
Definition at line 573 of file caja-undostack-manager.c.
References action, caja_file_get_by_uri(), caja_file_operations_delete(), caja_file_operations_move(), caja_file_operations_trash_or_delete(), caja_file_rename(), caja_file_set_group(), caja_file_set_owner(), caja_file_set_permissions(), CAJA_UNDOSTACK_CHANGEGROUP, CAJA_UNDOSTACK_CHANGEOWNER, CAJA_UNDOSTACK_COPY, CAJA_UNDOSTACK_CREATEEMPTYFILE, CAJA_UNDOSTACK_CREATEFILEFROMTEMPLATE, CAJA_UNDOSTACK_CREATEFOLDER, CAJA_UNDOSTACK_CREATELINK, CAJA_UNDOSTACK_DELETE, CAJA_UNDOSTACK_DUPLICATE, CAJA_UNDOSTACK_MOVE, CAJA_UNDOSTACK_MOVETOTRASH, CAJA_UNDOSTACK_RECURSIVESETPERMISSIONS, CAJA_UNDOSTACK_RENAME, CAJA_UNDOSTACK_RESTOREFROMTRASH, CAJA_UNDOSTACK_SETPERMISSIONS, cb, dest, FALSE, item, NULL, and TRUE.