MATE Desktop Environment: caja-notebook.h File Reference
caja-notebook.h File Reference
#include <glib.h>
#include <gtk/gtk.h>
#include "caja-window-slot.h"
Classes
struct _CajaNotebook
struct _CajaNotebookClass
Macros
#define CAJA_TYPE_NOTEBOOK (caja_notebook_get_type ())
#define CAJA_NOTEBOOK(o)
#define CAJA_NOTEBOOK_CLASS(k)
#define CAJA_IS_NOTEBOOK(o)
#define CAJA_IS_NOTEBOOK_CLASS(k)
#define CAJA_NOTEBOOK_GET_CLASS(o)
Typedefs
typedef struct _CajaNotebookClass CajaNotebookClass
typedef struct _CajaNotebook CajaNotebook
typedef struct _CajaNotebookPrivate CajaNotebookPrivate
Functions
GType caja_notebook_get_type (void)
int caja_notebook_add_tab (CajaNotebook *nb, CajaWindowSlot *slot, int position, gboolean jump_to)
void caja_notebook_set_show_tabs (CajaNotebook *nb, gboolean show_tabs)
void caja_notebook_set_dnd_enabled (CajaNotebook *nb, gboolean enabled)
void caja_notebook_sync_tab_label (CajaNotebook *nb, CajaWindowSlot *slot)
void caja_notebook_sync_loading (CajaNotebook *nb, CajaWindowSlot *slot)
void caja_notebook_reorder_current_child_relative (CajaNotebook *notebook, int offset)
void caja_notebook_set_current_page_relative (CajaNotebook *notebook, int offset)
gboolean caja_notebook_can_reorder_current_child_relative (CajaNotebook *notebook, int offset)
gboolean caja_notebook_can_set_current_page_relative (CajaNotebook *notebook, int offset)
Macro Definition Documentation
CAJA_IS_NOTEBOOK
#define CAJA_IS_NOTEBOOK (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), CAJA_TYPE_NOTEBOOK))
Definition at line 42 of file caja-notebook.h.
Referenced by caja_notebook_add_tab(), caja_notebook_can_reorder_current_child_relative(), caja_notebook_can_set_current_page_relative(), caja_notebook_reorder_current_child_relative(), caja_notebook_set_current_page_relative(), caja_notebook_sync_loading(), and caja_notebook_sync_tab_label().
CAJA_IS_NOTEBOOK_CLASS
#define CAJA_IS_NOTEBOOK_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), CAJA_TYPE_NOTEBOOK))
Definition at line 43 of file caja-notebook.h.
CAJA_NOTEBOOK
#define CAJA_NOTEBOOK (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), CAJA_TYPE_NOTEBOOK, CajaNotebook))
Definition at line 40 of file caja-notebook.h.
Referenced by caja_navigation_window_pane_add_slot_in_tab().
CAJA_NOTEBOOK_CLASS
#define CAJA_NOTEBOOK_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST((k), CAJA_TYPE_NOTEBOOK, CajaNotebookClass))
Definition at line 41 of file caja-notebook.h.
CAJA_NOTEBOOK_GET_CLASS
#define CAJA_NOTEBOOK_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), CAJA_TYPE_NOTEBOOK, CajaNotebookClass))
Definition at line 44 of file caja-notebook.h.
CAJA_TYPE_NOTEBOOK
#define CAJA_TYPE_NOTEBOOK (caja_notebook_get_type ())
Definition at line 39 of file caja-notebook.h.
Referenced by caja_navigation_window_pane_setup().
Typedef Documentation
CajaNotebook
typedef struct _CajaNotebook CajaNotebook
Definition at line 47 of file caja-notebook.h.
CajaNotebookClass
typedef struct _CajaNotebookClass CajaNotebookClass
Definition at line 46 of file caja-notebook.h.
CajaNotebookPrivate
typedef struct _CajaNotebookPrivate CajaNotebookPrivate
Definition at line 48 of file caja-notebook.h.
Function Documentation
caja_notebook_add_tab()
int caja_notebook_add_tab (CajaNotebook * nb, CajaWindowSlot * slot, int position, gboolean jump_to)
Definition at line 381 of file caja-notebook.c.
References CAJA_IS_NOTEBOOK, CAJA_IS_WINDOW_SLOT, caja_notebook_sync_loading(), caja_notebook_sync_tab_label(), CajaWindowSlot::content_box, NULL, and TRUE.
Referenced by caja_navigation_window_pane_add_slot_in_tab().
caja_notebook_can_reorder_current_child_relative()
gboolean caja_notebook_can_reorder_current_child_relative (CajaNotebook * notebook, int offset)
Definition at line 499 of file caja-notebook.c.
References CAJA_IS_NOTEBOOK, and FALSE.
Referenced by caja_notebook_reorder_current_child_relative().
caja_notebook_can_set_current_page_relative()
gboolean caja_notebook_can_set_current_page_relative (CajaNotebook * notebook, int offset)
Definition at line 508 of file caja-notebook.c.
References CAJA_IS_NOTEBOOK, and FALSE.
Referenced by caja_notebook_set_current_page_relative().
caja_notebook_get_type()
GType caja_notebook_get_type (void)
caja_notebook_reorder_current_child_relative()
void caja_notebook_reorder_current_child_relative (CajaNotebook * notebook, int offset)
Definition at line 434 of file caja-notebook.c.
References CAJA_IS_NOTEBOOK, and caja_notebook_can_reorder_current_child_relative().
caja_notebook_set_current_page_relative()
void caja_notebook_set_current_page_relative (CajaNotebook * notebook, int offset)
Definition at line 456 of file caja-notebook.c.
References CAJA_IS_NOTEBOOK, and caja_notebook_can_set_current_page_relative().
caja_notebook_set_dnd_enabled()
void caja_notebook_set_dnd_enabled (CajaNotebook * nb, gboolean enabled)
caja_notebook_set_show_tabs()
void caja_notebook_set_show_tabs (CajaNotebook * nb, gboolean show_tabs)
caja_notebook_sync_loading()
void caja_notebook_sync_loading (CajaNotebook * nb, CajaWindowSlot * slot)
Definition at line 203 of file caja-notebook.c.
References CajaWindowSlot::allow_stop, CAJA_IS_NOTEBOOK, CAJA_IS_WINDOW_SLOT, CajaWindowSlot::content_box, FALSE, and NULL.
Referenced by caja_notebook_add_tab().
caja_notebook_sync_tab_label()
void caja_notebook_sync_tab_label (CajaNotebook * nb, CajaWindowSlot * slot)
Definition at line 241 of file caja-notebook.c.
References CAJA_IS_NOTEBOOK, CAJA_IS_WINDOW_SLOT, CajaWindowSlot::content_box, label, CajaWindowSlot::location, NULL, and CajaWindowSlot::title.
Referenced by caja_notebook_add_tab().