MATE Desktop Environment: caja-mime-actions.h File Reference
caja-mime-actions.h File Reference
#include <gio/gio.h>
#include "caja-file.h"
#include "caja-window-info.h"
#include "caja-window-slot-info.h"
Functions
CajaFileAttributes caja_mime_actions_get_required_file_attributes (void)
GAppInfo * caja_mime_get_default_application_for_file (CajaFile *file)
GList * caja_mime_get_applications_for_file (CajaFile *file)
GAppInfo * caja_mime_get_default_application_for_files (GList *files)
GList * caja_mime_get_applications_for_files (GList *file)
gboolean caja_mime_has_any_applications_for_file (CajaFile *file)
gboolean caja_mime_file_opens_in_view (CajaFile *file)
gboolean caja_mime_file_opens_in_external_app (CajaFile *file)
void caja_mime_activate_files (GtkWindow *parent_window, CajaWindowSlotInfo *slot_info, GList *files, const char *launch_directory, CajaWindowOpenMode mode, CajaWindowOpenFlags flags, gboolean user_confirmation)
void caja_mime_activate_file (GtkWindow *parent_window, CajaWindowSlotInfo *slot_info, CajaFile *file, const char *launch_directory, CajaWindowOpenMode mode, CajaWindowOpenFlags flags)
Function Documentation
caja_mime_actions_get_required_file_attributes()
CajaFileAttributes caja_mime_actions_get_required_file_attributes (void)
Definition at line 299 of file caja-mime-actions.c.
References CAJA_FILE_ATTRIBUTE_INFO, and CAJA_FILE_ATTRIBUTE_LINK_INFO.
Referenced by caja_window_load_view_as_menus().
caja_mime_activate_file()
void caja_mime_activate_file (GtkWindow * parent_window, CajaWindowSlotInfo * slot_info, CajaFile * file, const char * launch_directory, CajaWindowOpenMode mode, CajaWindowOpenFlags flags)
Definition at line 2572 of file caja-mime-actions.c.
References CAJA_IS_FILE, caja_mime_activate_files(), FALSE, and NULL.
Referenced by fm_directory_view_activate_file().
caja_mime_activate_files()
void caja_mime_activate_files (GtkWindow * parent_window, CajaWindowSlotInfo * slot_info, GList * files, const char * launch_directory, CajaWindowOpenMode mode, CajaWindowOpenFlags flags, gboolean user_confirmation)
caja_mime_activate_files:
Activate a list of files. Each one might launch with an application or with a component. This is normally called only by subclasses. @view: FMDirectoryView in question. @files: A GList of CajaFiles to activate.
Definition at line 2477 of file caja-mime-actions.c.
References _, CAJA_DEBUG_LOG_DOMAIN_USER, caja_debug_log_with_file_list(), caja_file_can_mount(), caja_file_can_start(), caja_file_get_display_name(), caja_file_ref(), FALSE, and NULL.
Referenced by caja_mime_activate_file(), and fm_directory_view_activate_files().
caja_mime_file_opens_in_external_app()
gboolean caja_mime_file_opens_in_external_app (CajaFile * file)
Definition at line 925 of file caja-mime-actions.c.
References ACTIVATION_ACTION_OPEN_IN_APPLICATION.
caja_mime_file_opens_in_view()
gboolean caja_mime_file_opens_in_view (CajaFile * file)
Definition at line 867 of file caja-mime-actions.c.
References caja_file_is_directory().
caja_mime_get_applications_for_file()
GList * caja_mime_get_applications_for_file (CajaFile * file)
Definition at line 442 of file caja-mime-actions.c.
References caja_file_get_mime_type(), caja_file_get_uri_scheme(), mime_type, and NULL.
Referenced by caja_mime_get_applications_for_files().
caja_mime_get_applications_for_files()
GList * caja_mime_get_applications_for_files (GList * file)
Definition at line 635 of file caja-mime-actions.c.
References caja_mime_get_applications_for_file(), and NULL.
caja_mime_get_default_application_for_file()
GAppInfo * caja_mime_get_default_application_for_file (CajaFile * file)
Definition at line 333 of file caja-mime-actions.c.
References caja_file_get_mime_type(), caja_file_get_uri_scheme(), mime_type, and NULL.
Referenced by caja_mime_get_default_application_for_files().
caja_mime_get_default_application_for_files()
GAppInfo * caja_mime_get_default_application_for_files (GList * files)
Definition at line 528 of file caja-mime-actions.c.
References caja_mime_get_default_application_for_file(), and NULL.
caja_mime_has_any_applications_for_file()
gboolean caja_mime_has_any_applications_for_file (CajaFile * file)
Definition at line 481 of file caja-mime-actions.c.
References caja_file_get_mime_type(), caja_file_get_uri_scheme(), FALSE, mime_type, NULL, and TRUE.