MATE Desktop Environment: caja-navigation-window-pane.h File Reference
caja-navigation-window-pane.h File Reference
#include "caja-window-pane.h"
#include "caja-navigation-window-slot.h"
Classes
struct _CajaNavigationWindowPaneClass
struct _CajaNavigationWindowPane
Macros
#define CAJA_TYPE_NAVIGATION_WINDOW_PANE (caja_navigation_window_pane_get_type())
#define CAJA_NAVIGATION_WINDOW_PANE_CLASS(k)
#define CAJA_NAVIGATION_WINDOW_PANE(obj)
#define CAJA_IS_NAVIGATION_WINDOW_PANE(obj)
#define CAJA_IS_NAVIGATION_WINDOW_PANE_CLASS(k)
#define CAJA_NAVIGATION_WINDOW_PANE_GET_CLASS(o)
Typedefs
typedef struct _CajaNavigationWindowPaneClass CajaNavigationWindowPaneClass
typedef struct _CajaNavigationWindowPane CajaNavigationWindowPane
Functions
GType caja_navigation_window_pane_get_type (void)
CajaNavigationWindowPane * caja_navigation_window_pane_new (CajaWindow *window)
void caja_navigation_window_pane_setup (CajaNavigationWindowPane *pane)
void caja_navigation_window_pane_hide_location_bar (CajaNavigationWindowPane *pane, gboolean save_preference)
void caja_navigation_window_pane_show_location_bar (CajaNavigationWindowPane *pane, gboolean save_preference)
gboolean caja_navigation_window_pane_location_bar_showing (CajaNavigationWindowPane *pane)
void caja_navigation_window_pane_hide_path_bar (CajaNavigationWindowPane *pane)
void caja_navigation_window_pane_show_path_bar (CajaNavigationWindowPane *pane)
gboolean caja_navigation_window_pane_path_bar_showing (CajaNavigationWindowPane *pane)
gboolean caja_navigation_window_pane_search_bar_showing (CajaNavigationWindowPane *pane)
void caja_navigation_window_pane_set_bar_mode (CajaNavigationWindowPane *pane, CajaBarMode mode)
void caja_navigation_window_pane_show_location_bar_temporarily (CajaNavigationWindowPane *pane)
void caja_navigation_window_pane_show_navigation_bar_temporarily (CajaNavigationWindowPane *pane)
void caja_navigation_window_pane_always_use_location_entry (CajaNavigationWindowPane *pane, gboolean use_entry)
gboolean caja_navigation_window_pane_hide_temporary_bars (CajaNavigationWindowPane *pane)
void caja_navigation_window_pane_add_slot_in_tab (CajaNavigationWindowPane *pane, CajaWindowSlot *slot, CajaWindowOpenSlotFlags flags)
void caja_navigation_window_pane_remove_page (CajaNavigationWindowPane *pane, int page_num)
Macro Definition Documentation
CAJA_IS_NAVIGATION_WINDOW_PANE
#define CAJA_IS_NAVIGATION_WINDOW_PANE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_NAVIGATION_WINDOW_PANE))
Definition at line 34 of file caja-navigation-window-pane.h.
Referenced by caja_navigation_window_pane_hide_temporary_bars(), and caja_navigation_window_pane_location_bar_showing().
CAJA_IS_NAVIGATION_WINDOW_PANE_CLASS
#define CAJA_IS_NAVIGATION_WINDOW_PANE_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), CAJA_TYPE_NAVIGATION_WINDOW_PANE))
Definition at line 35 of file caja-navigation-window-pane.h.
CAJA_NAVIGATION_WINDOW_PANE
#define CAJA_NAVIGATION_WINDOW_PANE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_NAVIGATION_WINDOW_PANE, CajaNavigationWindowPane))
Definition at line 33 of file caja-navigation-window-pane.h.
Referenced by caja_navigation_window_hide_search(), caja_navigation_window_show_search(), caja_navigation_window_split_view_on(), caja_navigation_window_update_show_hide_menu_items(), and G_DEFINE_TYPE().
CAJA_NAVIGATION_WINDOW_PANE_CLASS
#define CAJA_NAVIGATION_WINDOW_PANE_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST((k), CAJA_TYPE_NAVIGATION_WINDOW_PANE, CajaNavigationWindowPaneClass))
Definition at line 32 of file caja-navigation-window-pane.h.
CAJA_NAVIGATION_WINDOW_PANE_GET_CLASS
#define CAJA_NAVIGATION_WINDOW_PANE_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), CAJA_TYPE_NAVIGATION_WINDOW_PANE, CajaNavigationWindowPaneClass))
Definition at line 36 of file caja-navigation-window-pane.h.
CAJA_TYPE_NAVIGATION_WINDOW_PANE
#define CAJA_TYPE_NAVIGATION_WINDOW_PANE (caja_navigation_window_pane_get_type())
Definition at line 31 of file caja-navigation-window-pane.h.
Referenced by caja_navigation_window_pane_new().
Typedef Documentation
CajaNavigationWindowPane
typedef struct _CajaNavigationWindowPane CajaNavigationWindowPane
Definition at line 39 of file caja-navigation-window-pane.h.
CajaNavigationWindowPaneClass
typedef struct _CajaNavigationWindowPaneClass CajaNavigationWindowPaneClass
Definition at line 38 of file caja-navigation-window-pane.h.
Function Documentation
caja_navigation_window_pane_add_slot_in_tab()
void caja_navigation_window_pane_add_slot_in_tab (CajaNavigationWindowPane * pane, CajaWindowSlot * slot, CajaWindowOpenSlotFlags flags)
Definition at line 538 of file caja-navigation-window-pane.c.
References CAJA_NOTEBOOK, caja_notebook_add_tab(), CAJA_WINDOW_OPEN_SLOT_APPEND, FALSE, and _CajaNavigationWindowPane::notebook.
caja_navigation_window_pane_always_use_location_entry()
void caja_navigation_window_pane_always_use_location_entry (CajaNavigationWindowPane * pane, gboolean use_entry)
Definition at line 658 of file caja-navigation-window-pane.c.
References CAJA_BAR_NAVIGATION, CAJA_BAR_PATH, caja_navigation_window_pane_set_bar_mode(), and _CajaNavigationWindowPane::location_button.
caja_navigation_window_pane_get_type()
GType caja_navigation_window_pane_get_type (void)
caja_navigation_window_pane_hide_location_bar()
void caja_navigation_window_pane_hide_location_bar (CajaNavigationWindowPane * pane, gboolean save_preference)
Definition at line 875 of file caja-navigation-window-pane.c.
References CAJA_NAVIGATION_WINDOW, caja_navigation_window_update_show_hide_menu_items(), CAJA_WINDOW_PANE, caja_window_state, CAJA_WINDOW_STATE_START_WITH_LOCATION_BAR, FALSE, _CajaNavigationWindowPane::location_bar, and _CajaNavigationWindowPane::temporary_location_bar.
Referenced by caja_navigation_window_pane_hide_temporary_bars(), and caja_navigation_window_split_view_on().
caja_navigation_window_pane_hide_path_bar()
void caja_navigation_window_pane_hide_path_bar (CajaNavigationWindowPane * pane)
caja_navigation_window_pane_hide_temporary_bars()
gboolean caja_navigation_window_pane_hide_temporary_bars (CajaNavigationWindowPane * pane)
Definition at line 595 of file caja-navigation-window-pane.c.
References CAJA_BAR_NAVIGATION, CAJA_BAR_PATH, CAJA_BAR_SEARCH, caja_directory_get(), caja_directory_unref(), CAJA_IS_NAVIGATION_WINDOW_PANE, CAJA_IS_SEARCH_DIRECTORY, CAJA_NAVIGATION_WINDOW, caja_navigation_window_pane_hide_location_bar(), caja_navigation_window_pane_location_bar_showing(), caja_navigation_window_pane_set_bar_mode(), caja_navigation_window_set_search_button(), caja_preferences, CAJA_PREFERENCES_ALWAYS_USE_LOCATION_ENTRY, CAJA_WINDOW_PANE, FALSE, CajaWindowSlot::location, _CajaNavigationWindowPane::temporary_location_bar, _CajaNavigationWindowPane::temporary_navigation_bar, _CajaNavigationWindowPane::temporary_search_bar, and TRUE.
Referenced by caja_navigation_window_hide_search().
caja_navigation_window_pane_location_bar_showing()
gboolean caja_navigation_window_pane_location_bar_showing (CajaNavigationWindowPane * pane)
Definition at line 899 of file caja-navigation-window-pane.c.
References CAJA_IS_NAVIGATION_WINDOW_PANE, FALSE, _CajaNavigationWindowPane::location_bar, NULL, and TRUE.
Referenced by caja_navigation_window_pane_hide_temporary_bars(), caja_navigation_window_pane_show_location_bar_temporarily(), and caja_navigation_window_update_show_hide_menu_items().
caja_navigation_window_pane_new()
CajaNavigationWindowPane * caja_navigation_window_pane_new (CajaWindow * window)
Definition at line 981 of file caja-navigation-window-pane.c.
References CAJA_TYPE_NAVIGATION_WINDOW_PANE, CAJA_WINDOW_PANE, and NULL.
caja_navigation_window_pane_path_bar_showing()
gboolean caja_navigation_window_pane_path_bar_showing (CajaNavigationWindowPane * pane)
Definition at line 794 of file caja-navigation-window-pane.c.
References NULL, _CajaNavigationWindowPane::path_bar, and TRUE.
Referenced by caja_navigation_window_pane_show_navigation_bar_temporarily().
caja_navigation_window_pane_remove_page()
void caja_navigation_window_pane_remove_page (CajaNavigationWindowPane * pane, int page_num)
Definition at line 523 of file caja-navigation-window-pane.c.
References _CajaNavigationWindowPane::notebook.
caja_navigation_window_pane_search_bar_showing()
gboolean caja_navigation_window_pane_search_bar_showing (CajaNavigationWindowPane * pane)
Definition at line 864 of file caja-navigation-window-pane.c.
References NULL, _CajaNavigationWindowPane::search_bar, and TRUE.
Referenced by caja_navigation_window_hide_search(), caja_navigation_window_pane_show_navigation_bar_temporarily(), and caja_navigation_window_show_search().
caja_navigation_window_pane_set_bar_mode()
void caja_navigation_window_pane_set_bar_mode (CajaNavigationWindowPane * pane, CajaBarMode mode)
Definition at line 805 of file caja-navigation-window-pane.c.
References CAJA_BAR_NAVIGATION, CAJA_BAR_PATH, CAJA_BAR_SEARCH, CAJA_NAVIGATION_WINDOW, caja_navigation_window_is_in_temporary_navigation_bar(), caja_navigation_window_is_in_temporary_search_bar(), caja_navigation_window_set_search_button(), CAJA_WINDOW_PANE, FALSE, _CajaNavigationWindowPane::location_button, _CajaNavigationWindowPane::navigation_bar, NULL, _CajaNavigationWindowPane::path_bar, _CajaNavigationWindowPane::search_bar, and TRUE.
Referenced by caja_navigation_window_pane_always_use_location_entry(), caja_navigation_window_pane_hide_temporary_bars(), caja_navigation_window_pane_show_navigation_bar_temporarily(), and caja_navigation_window_show_search().
caja_navigation_window_pane_setup()
void caja_navigation_window_pane_setup (CajaNavigationWindowPane * pane)
Definition at line 679 of file caja-navigation-window-pane.c.
References CAJA_LOCATION_BAR, caja_location_bar_get_entry(), caja_location_bar_new(), CAJA_NAVIGATION_WINDOW, caja_search_bar_new(), CAJA_TYPE_NOTEBOOK, CAJA_TYPE_PATH_BAR, CAJA_WINDOW_PANE, FALSE, _CajaNavigationWindowPane::location_bar, _CajaNavigationWindowPane::location_button, _CajaNavigationWindowPane::navigation_bar, _CajaNavigationWindowPane::notebook, NULL, _CajaNavigationWindowPane::path_bar, _CajaNavigationWindowPane::search_bar, TRUE, and _CajaNavigationWindowPane::widget.
caja_navigation_window_pane_show_location_bar()
void caja_navigation_window_pane_show_location_bar (CajaNavigationWindowPane * pane, gboolean save_preference)
Definition at line 888 of file caja-navigation-window-pane.c.
References CAJA_NAVIGATION_WINDOW, caja_navigation_window_update_show_hide_menu_items(), CAJA_WINDOW_PANE, caja_window_state, CAJA_WINDOW_STATE_START_WITH_LOCATION_BAR, _CajaNavigationWindowPane::location_bar, and TRUE.
Referenced by caja_navigation_window_pane_show_location_bar_temporarily(), and caja_navigation_window_split_view_on().
caja_navigation_window_pane_show_location_bar_temporarily()
void caja_navigation_window_pane_show_location_bar_temporarily (CajaNavigationWindowPane * pane)
Definition at line 771 of file caja-navigation-window-pane.c.
References caja_navigation_window_pane_location_bar_showing(), caja_navigation_window_pane_show_location_bar(), FALSE, _CajaNavigationWindowPane::temporary_location_bar, and TRUE.
Referenced by caja_navigation_window_show_search().
caja_navigation_window_pane_show_navigation_bar_temporarily()
void caja_navigation_window_pane_show_navigation_bar_temporarily (CajaNavigationWindowPane * pane)
Definition at line 781 of file caja-navigation-window-pane.c.
References CAJA_BAR_NAVIGATION, CAJA_LOCATION_BAR, caja_location_bar_activate(), caja_navigation_window_pane_path_bar_showing(), caja_navigation_window_pane_search_bar_showing(), caja_navigation_window_pane_set_bar_mode(), _CajaNavigationWindowPane::navigation_bar, _CajaNavigationWindowPane::temporary_navigation_bar, and TRUE.
caja_navigation_window_pane_show_path_bar()
void caja_navigation_window_pane_show_path_bar (CajaNavigationWindowPane * pane)