MATE Desktop Environment: caja-desktop-link-monitor.c File Reference
caja-desktop-link-monitor.c File Reference
#include <config.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <string.h>
#include <eel/eel-debug.h>
#include <eel/eel-gtk-macros.h>
#include <eel/eel-glib-extensions.h>
#include <eel/eel-vfs-extensions.h>
#include <eel/eel-stock-dialogs.h>
#include "caja-desktop-link-monitor.h"
#include "caja-desktop-link.h"
#include "caja-desktop-icon-file.h"
#include "caja-directory.h"
#include "caja-desktop-directory.h"
#include "caja-global-preferences.h"
#include "caja-trash-monitor.h"
Functions
EEL_CLASS_BOILERPLATE (CajaDesktopLinkMonitor, caja_desktop_link_monitor, G_TYPE_OBJECT)
CajaDesktopLinkMonitor * caja_desktop_link_monitor_get (void)
char * caja_desktop_link_monitor_make_filename_unique (CajaDesktopLinkMonitor *monitor, const char *filename)
Function Documentation
caja_desktop_link_monitor_get()
CajaDesktopLinkMonitor * caja_desktop_link_monitor_get (void)
Definition at line 82 of file caja-desktop-link-monitor.c.
References CAJA_TYPE_DESKTOP_LINK_MONITOR, eel_debug_call_at_shutdown(), and NULL.
Referenced by caja_desktop_link_new_from_mount().
caja_desktop_link_monitor_make_filename_unique()
char * caja_desktop_link_monitor_make_filename_unique (CajaDesktopLinkMonitor * monitor, const char * filename)
Definition at line 117 of file caja-desktop-link-monitor.c.
Referenced by caja_desktop_link_new_from_mount().
EEL_CLASS_BOILERPLATE()
EEL_CLASS_BOILERPLATE (CajaDesktopLinkMonitor , caja_desktop_link_monitor , G_TYPE_OBJECT)
Definition at line 66 of file caja-desktop-link-monitor.c.
References NULL.