MATE Desktop Environment: caja-extension-types.h File Reference
caja-extension-types.h File Reference
#include <glib-object.h>
Macros
#define CAJA_TYPE_OPERATION_RESULT (caja_operation_result_get_type ())
Typedefs
typedef struct _CajaOperationHandle CajaOperationHandle
Enumerations
enum CajaOperationResult { CAJA_OPERATION_COMPLETE , CAJA_OPERATION_FAILED , CAJA_OPERATION_IN_PROGRESS }
Functions
GType caja_operation_result_get_type (void)
void caja_module_initialize (GTypeModule *module)
void caja_module_shutdown (void)
void caja_module_list_types (const GType **types, int *num_types)
void caja_module_list_pyfiles (GList **pyfiles)
Macro Definition Documentation
CAJA_TYPE_OPERATION_RESULT
#define CAJA_TYPE_OPERATION_RESULT (caja_operation_result_get_type ())
Definition at line 36 of file caja-extension-types.h.
Referenced by caja_info_provider_update_complete_invoke().
Typedef Documentation
CajaOperationHandle
typedef struct _CajaOperationHandle CajaOperationHandle
CajaOperationHandle:
Handle for asynchronous interfaces. These are opaque handles that must be unique within an extension object. These are returned by operations that return CAJA_OPERATION_IN_PROGRESS.
Definition at line 45 of file caja-extension-types.h.
Enumeration Type Documentation
CajaOperationResult
enum CajaOperationResult
CajaOperationResult: @CAJA_OPERATION_COMPLETE: the operation succeeded, and the extension is done with the request. @CAJA_OPERATION_FAILED: the operation failed. @CAJA_OPERATION_IN_PROGRESS: the extension has begin an async operation. When this value is returned, the extension must set the handle parameter and call the callback closure when the operation is complete.
Enumerator
CAJA_OPERATION_COMPLETE
CAJA_OPERATION_FAILED
CAJA_OPERATION_IN_PROGRESS
Definition at line 56 of file caja-extension-types.h.
Function Documentation
caja_module_initialize()
void caja_module_initialize (GTypeModule * module)
SECTION:caja-extension-types @title: CajaModule @short_description: Initialize an extension libcaja-extension/caja-extension-types.h
Methods that each extension implements.
Definition at line 136 of file ev-properties-main.c.
References caja_actions_register_type(), caja_cwe_register_type(), caja_dropbox_register_type(), caja_fr_register_type(), caja_image_converter_register_type(), caja_nste_register_type(), caja_open_terminal_register_type(), caja_python_debug, CAJA_TYPE_DROPBOX, CAJA_TYPE_IMAGE_CONVERTER, CAJA_TYPE_OPEN_TERMINAL, caja_xattr_tags_register_type(), DATADIR, debug_enter, dropbox_use_operation_in_progress_workaround, ev_init(), ev_properties_view_register_type(), FALSE, GETTEXT_PACKAGE, LOG_INFO, MATELOCALEDIR, na_tracker_register_type(), NULL, PACKAGE_NAME, PACKAGE_STRING, PACKAGE_VERSION, totem_properties_view_register_type(), and TRUE.
caja_module_list_pyfiles()
void caja_module_list_pyfiles (GList ** pyfiles)
Definition at line 344 of file caja-python.c.
References debug_enter.
caja_module_list_types()
void caja_module_list_types (const GType ** types, int * num_types)
Definition at line 151 of file ev-properties-main.c.
References CAJA_ACTIONS_TYPE, CAJA_TYPE_CWE, CAJA_TYPE_FR, CAJA_TYPE_NSTE, CAJA_TYPE_SHARE, CAJA_TYPE_USER_SHARE, CAJA_TYPE_XATTR_TAGS, debug_enter, GKSU_TYPE_CONTEXT_MENU, int(), and NA_TYPE_TRACKER.
caja_module_shutdown()
void caja_module_shutdown (void)
Definition at line 145 of file ev-properties-main.c.
References debug_enter, ev_shutdown(), NULL, and TRUE.
caja_operation_result_get_type()
GType caja_operation_result_get_type (void)
Definition at line 28 of file caja-extension-types.c.
References CAJA_OPERATION_COMPLETE, CAJA_OPERATION_FAILED, CAJA_OPERATION_IN_PROGRESS, and NULL.