MATE Desktop Environment: caja-connect-server-dialog.h File Reference
caja-connect-server-dialog.h File Reference
#include <gio/gio.h>
#include <gtk/gtk.h>
#include "caja-window.h"
Classes
struct _CajaConnectServerDialog
struct _CajaConnectServerDialogClass
Macros
#define CAJA_TYPE_CONNECT_SERVER_DIALOG (caja_connect_server_dialog_get_type ())
#define CAJA_CONNECT_SERVER_DIALOG(obj)
#define CAJA_CONNECT_SERVER_DIALOG_CLASS(klass)
#define CAJA_IS_CONNECT_SERVER_DIALOG(obj)
Typedefs
typedef struct _CajaConnectServerDialog CajaConnectServerDialog
typedef struct _CajaConnectServerDialogClass CajaConnectServerDialogClass
typedef struct _CajaConnectServerDialogPrivate CajaConnectServerDialogPrivate
Functions
GType caja_connect_server_dialog_get_type (void)
GtkWidget * caja_connect_server_dialog_new (CajaWindow *window)
void caja_connect_server_dialog_display_location_async (CajaConnectServerDialog *self, CajaApplication *application, GFile *location, GAsyncReadyCallback callback, gpointer user_data)
gboolean caja_connect_server_dialog_display_location_finish (CajaConnectServerDialog *self, GAsyncResult *result, GError **error)
void caja_connect_server_dialog_fill_details_async (CajaConnectServerDialog *self, GMountOperation *operation, const gchar *default_user, const gchar *default_domain, GAskPasswordFlags flags, GAsyncReadyCallback callback, gpointer user_data)
gboolean caja_connect_server_dialog_fill_details_finish (CajaConnectServerDialog *self, GAsyncResult *result)
Macro Definition Documentation
CAJA_CONNECT_SERVER_DIALOG
#define CAJA_CONNECT_SERVER_DIALOG (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_CONNECT_SERVER_DIALOG,\
             CajaConnectServerDialog))
Definition at line 34 of file caja-connect-server-dialog.h.
Referenced by caja_connect_server_dialog_new().
CAJA_CONNECT_SERVER_DIALOG_CLASS
#define CAJA_CONNECT_SERVER_DIALOG_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_CONNECT_SERVER_DIALOG,\
              CajaConnectServerDialogClass))
Definition at line 37 of file caja-connect-server-dialog.h.
CAJA_IS_CONNECT_SERVER_DIALOG
#define CAJA_IS_CONNECT_SERVER_DIALOG (obj)
Value:
(G_TYPE_INSTANCE_CHECK_TYPE ((obj), CAJA_TYPE_CONNECT_SERVER_DIALOG)
Definition at line 40 of file caja-connect-server-dialog.h.
CAJA_TYPE_CONNECT_SERVER_DIALOG
#define CAJA_TYPE_CONNECT_SERVER_DIALOG (caja_connect_server_dialog_get_type ())
Definition at line 32 of file caja-connect-server-dialog.h.
Referenced by caja_connect_server_dialog_new().
Typedef Documentation
CajaConnectServerDialog
typedef struct _CajaConnectServerDialog CajaConnectServerDialog
Definition at line 43 of file caja-connect-server-dialog.h.
CajaConnectServerDialogClass
typedef struct _CajaConnectServerDialogClass CajaConnectServerDialogClass
Definition at line 44 of file caja-connect-server-dialog.h.
CajaConnectServerDialogPrivate
typedef struct _CajaConnectServerDialogPrivate CajaConnectServerDialogPrivate
Definition at line 45 of file caja-connect-server-dialog.h.
Function Documentation
caja_connect_server_dialog_display_location_async()
void caja_connect_server_dialog_display_location_async (CajaConnectServerDialog * self, CajaApplication * application, GFile * location, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 67 of file caja-connect-server-dialog-main.c.
References caja_application_create_navigation_window(), caja_application_get_spatial_window(), caja_connect_server_dialog_display_location_async(), caja_preferences, CAJA_PREFERENCES_ALWAYS_USE_BROWSER, caja_window_go_to_full(), error, NULL, and user_data.
Referenced by caja_connect_server_dialog_display_location_async().
caja_connect_server_dialog_display_location_finish()
gboolean caja_connect_server_dialog_display_location_finish (CajaConnectServerDialog * self, GAsyncResult * result, GError ** error)
Definition at line 55 of file caja-connect-server-dialog-main.c.
References error, FALSE, and TRUE.
caja_connect_server_dialog_fill_details_async()
void caja_connect_server_dialog_fill_details_async (CajaConnectServerDialog * self, GMountOperation * operation, const gchar * default_user, const gchar * default_domain, GAskPasswordFlags flags, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 1204 of file caja-connect-server-dialog.c.
References caja_connect_server_dialog_fill_details_async(), _CajaConnectServerDialog::details, NULL, TRUE, and user_data.
Referenced by caja_connect_server_dialog_fill_details_async().
caja_connect_server_dialog_fill_details_finish()
gboolean caja_connect_server_dialog_fill_details_finish (CajaConnectServerDialog * self, GAsyncResult * result)
Definition at line 1197 of file caja-connect-server-dialog.c.
caja_connect_server_dialog_get_type()
GType caja_connect_server_dialog_get_type (void)
References error, and user_data.
caja_connect_server_dialog_new()
GtkWidget * caja_connect_server_dialog_new (CajaWindow * window)
Definition at line 1178 of file caja-connect-server-dialog.c.
References CAJA_CONNECT_SERVER_DIALOG, CAJA_TYPE_CONNECT_SERVER_DIALOG, _CajaConnectServerDialog::details, and NULL.
Referenced by main().