MATE Desktop Environment: caja-notebook.c File Reference
caja-notebook.c File Reference
#include <config.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <libcaja-private/caja-dnd.h>
#include "caja-notebook.h"
#include "caja-navigation-window.h"
#include "caja-window-manage-views.h"
#include "caja-window-private.h"
#include "caja-window-slot.h"
#include "caja-navigation-window-pane.h"
Macros
#define AFTER_ALL_TABS -1
Enumerations
enum { TAB_CLOSE_REQUEST , LAST_SIGNAL }
Functions
G_DEFINE_TYPE (CajaNotebook, caja_notebook, GTK_TYPE_NOTEBOOK)
void caja_notebook_sync_loading (CajaNotebook *notebook, CajaWindowSlot *slot)
void caja_notebook_sync_tab_label (CajaNotebook *notebook, CajaWindowSlot *slot)
int caja_notebook_add_tab (CajaNotebook *notebook, CajaWindowSlot *slot, int position, gboolean jump_to)
void caja_notebook_reorder_current_child_relative (CajaNotebook *notebook, int offset)
void caja_notebook_set_current_page_relative (CajaNotebook *notebook, int offset)
gboolean caja_notebook_can_reorder_current_child_relative (CajaNotebook *notebook, int offset)
gboolean caja_notebook_can_set_current_page_relative (CajaNotebook *notebook, int offset)
Macro Definition Documentation
AFTER_ALL_TABS
#define AFTER_ALL_TABS -1
Definition at line 42 of file caja-notebook.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TAB_CLOSE_REQUEST
LAST_SIGNAL
Definition at line 58 of file caja-notebook.c.
Function Documentation
caja_notebook_add_tab()
int caja_notebook_add_tab (CajaNotebook * notebook, CajaWindowSlot * slot, int position, gboolean jump_to)
Definition at line 381 of file caja-notebook.c.
References CAJA_IS_NOTEBOOK, CAJA_IS_WINDOW_SLOT, caja_notebook_sync_loading(), caja_notebook_sync_tab_label(), CajaWindowSlot::content_box, NULL, and TRUE.
Referenced by caja_navigation_window_pane_add_slot_in_tab().
caja_notebook_can_reorder_current_child_relative()
gboolean caja_notebook_can_reorder_current_child_relative (CajaNotebook * notebook, int offset)
Definition at line 499 of file caja-notebook.c.
References CAJA_IS_NOTEBOOK, and FALSE.
Referenced by caja_notebook_reorder_current_child_relative().
caja_notebook_can_set_current_page_relative()
gboolean caja_notebook_can_set_current_page_relative (CajaNotebook * notebook, int offset)
Definition at line 508 of file caja-notebook.c.
References CAJA_IS_NOTEBOOK, and FALSE.
Referenced by caja_notebook_set_current_page_relative().
caja_notebook_reorder_current_child_relative()
void caja_notebook_reorder_current_child_relative (CajaNotebook * notebook, int offset)
Definition at line 434 of file caja-notebook.c.
References CAJA_IS_NOTEBOOK, and caja_notebook_can_reorder_current_child_relative().
caja_notebook_set_current_page_relative()
void caja_notebook_set_current_page_relative (CajaNotebook * notebook, int offset)
Definition at line 456 of file caja-notebook.c.
References CAJA_IS_NOTEBOOK, and caja_notebook_can_set_current_page_relative().
caja_notebook_sync_loading()
void caja_notebook_sync_loading (CajaNotebook * notebook, CajaWindowSlot * slot)
Definition at line 203 of file caja-notebook.c.
References CajaWindowSlot::allow_stop, CAJA_IS_NOTEBOOK, CAJA_IS_WINDOW_SLOT, CajaWindowSlot::content_box, FALSE, and NULL.
Referenced by caja_notebook_add_tab().
caja_notebook_sync_tab_label()
void caja_notebook_sync_tab_label (CajaNotebook * notebook, CajaWindowSlot * slot)
Definition at line 241 of file caja-notebook.c.
References CAJA_IS_NOTEBOOK, CAJA_IS_WINDOW_SLOT, CajaWindowSlot::content_box, label, CajaWindowSlot::location, NULL, and CajaWindowSlot::title.
Referenced by caja_notebook_add_tab().
G_DEFINE_TYPE()
G_DEFINE_TYPE (CajaNotebook , caja_notebook , GTK_TYPE_NOTEBOOK)
References CAJA_TYPE_WINDOW_SLOT, NULL, and TAB_CLOSE_REQUEST.