MATE Desktop Environment: caja-dropbox-hooks.h File Reference
caja-dropbox-hooks.h File Reference
#include <glib.h>
Classes
struct CajaDropboxHookserv
Typedefs
typedef void(* DropboxUpdateHook) (GHashTable *, gpointer)
typedef void(* DropboxHookClientConnectHook) (gpointer)
Functions
void caja_dropbox_hooks_setup (CajaDropboxHookserv *)
void caja_dropbox_hooks_start (CajaDropboxHookserv *)
gboolean caja_dropbox_hooks_is_connected (CajaDropboxHookserv *)
gboolean caja_dropbox_hooks_force_reconnect (CajaDropboxHookserv *)
void caja_dropbox_hooks_add (CajaDropboxHookserv *ndhs, const gchar *hook_name, DropboxUpdateHook hook, gpointer ud)
void caja_dropbox_hooks_add_on_disconnect_hook (CajaDropboxHookserv *hookserv, DropboxHookClientConnectHook dhcch, gpointer ud)
void caja_dropbox_hooks_add_on_connect_hook (CajaDropboxHookserv *hookserv, DropboxHookClientConnectHook dhcch, gpointer ud)
Typedef Documentation
DropboxHookClientConnectHook
typedef void(* DropboxHookClientConnectHook) (gpointer)
Definition at line 32 of file caja-dropbox-hooks.h.
DropboxUpdateHook
typedef void(* DropboxUpdateHook) (GHashTable *, gpointer)
Definition at line 31 of file caja-dropbox-hooks.h.
Function Documentation
caja_dropbox_hooks_add()
void caja_dropbox_hooks_add (CajaDropboxHookserv * ndhs, const gchar * hook_name, DropboxUpdateHook hook, gpointer ud)
Definition at line 324 of file caja-dropbox-hooks.c.
References CajaDropboxHookserv::dispatch_table.
caja_dropbox_hooks_add_on_connect_hook()
void caja_dropbox_hooks_add_on_connect_hook (CajaDropboxHookserv * hookserv, DropboxHookClientConnectHook dhcch, gpointer ud)
Definition at line 312 of file caja-dropbox-hooks.c.
References CajaDropboxHookserv::onconnect_hooklist.
Referenced by dropbox_client_setup().
caja_dropbox_hooks_add_on_disconnect_hook()
void caja_dropbox_hooks_add_on_disconnect_hook (CajaDropboxHookserv * hookserv, DropboxHookClientConnectHook dhcch, gpointer ud)
Definition at line 299 of file caja-dropbox-hooks.c.
References CajaDropboxHookserv::ondisconnect_hooklist.
Referenced by dropbox_client_setup().
caja_dropbox_hooks_force_reconnect()
gboolean caja_dropbox_hooks_force_reconnect (CajaDropboxHookserv * hookserv)
Definition at line 261 of file caja-dropbox-hooks.c.
References CajaDropboxHookserv::connected, debug, debug_enter, CajaDropboxHookserv::event_source, and FALSE.
Referenced by dropbox_client_force_reconnect().
caja_dropbox_hooks_is_connected()
gboolean caja_dropbox_hooks_is_connected (CajaDropboxHookserv * hookserv)
Definition at line 283 of file caja-dropbox-hooks.c.
References CajaDropboxHookserv::connected.
Referenced by dropbox_client_is_connected().
caja_dropbox_hooks_setup()
void caja_dropbox_hooks_setup (CajaDropboxHookserv * hookserv)
Definition at line 288 of file caja-dropbox-hooks.c.
References CajaDropboxHookserv::connected, CajaDropboxHookserv::dispatch_table, FALSE, CajaDropboxHookserv::onconnect_hooklist, and CajaDropboxHookserv::ondisconnect_hooklist.
Referenced by dropbox_client_setup().
caja_dropbox_hooks_start()
void caja_dropbox_hooks_start (CajaDropboxHookserv * hookserv)
Definition at line 335 of file caja-dropbox-hooks.c.
Referenced by dropbox_client_start().