MATE Desktop Environment: caja-ui-utilities.h File Reference
caja-ui-utilities.h File Reference
#include <gtk/gtk.h>
#include <libcaja-extension/caja-menu-item.h>
Functions
char * caja_get_ui_directory (void)
char * caja_ui_file (const char *partial_path)
void caja_ui_unmerge_ui (GtkUIManager *ui_manager, guint *merge_id, GtkActionGroup **action_group)
void caja_ui_prepare_merge_ui (GtkUIManager *ui_manager, const char *name, guint *merge_id, GtkActionGroup **action_group)
GtkAction * caja_action_from_menu_item (CajaMenuItem *item, GtkWidget *parent_widget)
GtkAction * caja_toolbar_action_from_menu_item (CajaMenuItem *item, GtkWidget *parent_widget)
const char * caja_ui_string_get (const char *filename)
void caja_ui_frame_image (GdkPixbuf **pixbuf)
Function Documentation
caja_action_from_menu_item()
GtkAction * caja_action_from_menu_item (CajaMenuItem * item, GtkWidget * parent_widget)
Definition at line 174 of file caja-ui-utilities.c.
References action, caja_get_icon_size_for_stock_size(), G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, item, label, name, and NULL.
caja_get_ui_directory()
char * caja_get_ui_directory (void)
Definition at line 75 of file caja-ui-utilities.c.
References DATADIR.
caja_toolbar_action_from_menu_item()
GtkAction * caja_toolbar_action_from_menu_item (CajaMenuItem * item, GtkWidget * parent_widget)
Definition at line 229 of file caja-ui-utilities.c.
References action, caja_get_icon_size_for_stock_size(), G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, item, label, name, and NULL.
Referenced by caja_navigation_window_load_extension_toolbar_items().
caja_ui_file()
char * caja_ui_file (const char * partial_path)
Definition at line 81 of file caja-ui-utilities.c.
References DATADIR, and NULL.
Referenced by caja_ui_string_get().
caja_ui_frame_image()
void caja_ui_frame_image (GdkPixbuf ** pixbuf)
Definition at line 313 of file caja-ui-utilities.c.
References CAJA_THUMBNAIL_FRAME_BOTTOM, CAJA_THUMBNAIL_FRAME_LEFT, CAJA_THUMBNAIL_FRAME_RIGHT, CAJA_THUMBNAIL_FRAME_TOP, eel_embed_image_in_frame(), and NULL.
Referenced by caja_file_get_icon().
caja_ui_prepare_merge_ui()
void caja_ui_prepare_merge_ui (GtkUIManager * ui_manager, const char * name, guint * merge_id, GtkActionGroup ** action_group)
Definition at line 58 of file caja-ui-utilities.c.
References G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, GETTEXT_PACKAGE, and name.
caja_ui_string_get()
const char * caja_ui_string_get (const char * filename)
Definition at line 95 of file caja-ui-utilities.c.
References caja_ui_file(), eel_debug_call_at_shutdown_with_data(), and NULL.
Referenced by caja_navigation_window_initialize_menus(), and caja_window_initialize_menus().
caja_ui_unmerge_ui()
void caja_ui_unmerge_ui (GtkUIManager * ui_manager, guint * merge_id, GtkActionGroup ** action_group)
Definition at line 39 of file caja-ui-utilities.c.
References NULL.