MATE Desktop Environment: caja-x-content-bar.c File Reference
caja-x-content-bar.c File Reference
#include <config.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <gtk/gtk.h>
#include <libcaja-private/caja-autorun.h>
#include <libcaja-private/caja-icon-info.h>
#include "caja-x-content-bar.h"
Enumerations
enum { PROP_0 , PROP_MOUNT , PROP_X_CONTENT_TYPE }
Functions
void caja_x_content_bar_set_x_content_type (CajaXContentBar *bar, const char *x_content_type)
const char * caja_x_content_bar_get_x_content_type (CajaXContentBar *bar)
GMount * caja_x_content_bar_get_mount (CajaXContentBar *bar)
void caja_x_content_bar_set_mount (CajaXContentBar *bar, GMount *mount)
GtkWidget * caja_x_content_bar_new (GMount *mount, const char *x_content_type)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_MOUNT
PROP_X_CONTENT_TYPE
Definition at line 45 of file caja-x-content-bar.c.
Function Documentation
caja_x_content_bar_get_mount()
GMount * caja_x_content_bar_get_mount (CajaXContentBar * bar)
Definition at line 171 of file caja-x-content-bar.c.
References NULL, and CajaXContentBar::priv.
caja_x_content_bar_get_x_content_type()
const char * caja_x_content_bar_get_x_content_type (CajaXContentBar * bar)
Definition at line 165 of file caja-x-content-bar.c.
References CajaXContentBar::priv.
caja_x_content_bar_new()
GtkWidget * caja_x_content_bar_new (GMount * mount, const char * x_content_type)
Definition at line 319 of file caja-x-content-bar.c.
References CAJA_TYPE_X_CONTENT_BAR, and NULL.
caja_x_content_bar_set_mount()
void caja_x_content_bar_set_mount (CajaXContentBar * bar, GMount * mount)
Definition at line 177 of file caja-x-content-bar.c.
References NULL, and CajaXContentBar::priv.
caja_x_content_bar_set_x_content_type()
void caja_x_content_bar_set_x_content_type (CajaXContentBar * bar, const char * x_content_type)
Definition at line 55 of file caja-x-content-bar.c.
References _, caja_get_icon_size_for_stock_size(), caja_icon_info_get_pixbuf_at_size(), caja_icon_info_lookup(), FALSE, message(), name, NULL, and CajaXContentBar::priv.