MATE Desktop Environment: caja-file-changes-queue.c File Reference
caja-file-changes-queue.c File Reference
#include <config.h>
#include "caja-file-changes-queue.h"
#include "caja-directory-notify.h"
Enumerations
enum CajaFileChangeKind {
CHANGE_FILE_INITIAL , CHANGE_FILE_ADDED , CHANGE_FILE_CHANGED , CHANGE_FILE_REMOVED ,
CHANGE_FILE_MOVED , CHANGE_POSITION_SET , CHANGE_POSITION_REMOVE
}
enum { CONSUME_CHANGES_MAX_CHUNK = 20 }
Functions
void caja_file_changes_queue_file_added (GFile *location)
void caja_file_changes_queue_file_changed (GFile *location)
void caja_file_changes_queue_file_removed (GFile *location)
void caja_file_changes_queue_file_moved (GFile *from, GFile *to)
void caja_file_changes_queue_schedule_position_set (GFile *location, GdkPoint point, int screen)
void caja_file_changes_queue_schedule_position_remove (GFile *location)
void caja_file_changes_consume_changes (gboolean consume_all)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CONSUME_CHANGES_MAX_CHUNK
Definition at line 214 of file caja-file-changes-queue.c.
CajaFileChangeKind
enum CajaFileChangeKind
Enumerator
CHANGE_FILE_INITIAL
CHANGE_FILE_ADDED
CHANGE_FILE_CHANGED
CHANGE_FILE_REMOVED
CHANGE_FILE_MOVED
CHANGE_POSITION_SET
CHANGE_POSITION_REMOVE
Definition at line 28 of file caja-file-changes-queue.c.
Function Documentation
caja_file_changes_consume_changes()
void caja_file_changes_consume_changes (gboolean consume_all)
Definition at line 258 of file caja-file-changes-queue.c.
References caja_directory_notify_files_added(), caja_directory_notify_files_changed(), caja_directory_notify_files_moved(), caja_directory_notify_files_removed(), caja_directory_schedule_position_set(), CHANGE_FILE_ADDED, CHANGE_FILE_CHANGED, CHANGE_FILE_MOVED, CHANGE_FILE_REMOVED, CHANGE_POSITION_REMOVE, CHANGE_POSITION_SET, CONSUME_CHANGES_MAX_CHUNK, FALSE, GFilePair::from, CajaFileChangesQueuePosition::location, NULL, CajaFileChangesQueuePosition::point, CajaFileChangesQueuePosition::screen, CajaFileChangesQueuePosition::set, GFilePair::to, and TRUE.
caja_file_changes_queue_file_added()
void caja_file_changes_queue_file_added (GFile * location)
Definition at line 95 of file caja-file-changes-queue.c.
References CHANGE_FILE_ADDED.
caja_file_changes_queue_file_changed()
void caja_file_changes_queue_file_changed (GFile * location)
Definition at line 109 of file caja-file-changes-queue.c.
References CHANGE_FILE_CHANGED.
caja_file_changes_queue_file_moved()
void caja_file_changes_queue_file_moved (GFile * from, GFile * to)
Definition at line 137 of file caja-file-changes-queue.c.
References CHANGE_FILE_MOVED.
caja_file_changes_queue_file_removed()
void caja_file_changes_queue_file_removed (GFile * location)
Definition at line 123 of file caja-file-changes-queue.c.
References CHANGE_FILE_REMOVED.
caja_file_changes_queue_schedule_position_remove()
void caja_file_changes_queue_schedule_position_remove (GFile * location)
Definition at line 171 of file caja-file-changes-queue.c.
References CHANGE_POSITION_REMOVE.
caja_file_changes_queue_schedule_position_set()
void caja_file_changes_queue_schedule_position_set (GFile * location, GdkPoint point, int screen)
Definition at line 153 of file caja-file-changes-queue.c.
References CHANGE_POSITION_SET.