MATE Desktop Environment: caja-desktop-window.c File Reference
caja-desktop-window.c File Reference
#include <config.h>
#include <X11/Xatom.h>
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <glib/gi18n.h>
#include <eel/eel-background.h>
#include <eel/eel-vfs-extensions.h>
#include <libcaja-private/caja-file-utilities.h>
#include <libcaja-private/caja-icon-names.h>
#include "caja-desktop-window.h"
#include "caja-window-private.h"
#include "caja-actions.h"
Functions
G_DEFINE_TYPE (CajaDesktopWindowAccessible, caja_desktop_window_accessible, GTK_TYPE_WINDOW_ACCESSIBLE)
G_DEFINE_TYPE_WITH_PRIVATE (CajaDesktopWindow, caja_desktop_window, CAJA_TYPE_SPATIAL_WINDOW)
void caja_desktop_window_update_directory (CajaDesktopWindow *window)
CajaDesktopWindow * caja_desktop_window_new (CajaApplication *application, GdkScreen *screen)
gboolean caja_desktop_window_loaded (CajaDesktopWindow *window)
Function Documentation
caja_desktop_window_loaded()
gboolean caja_desktop_window_loaded (CajaDesktopWindow * window)
Definition at line 434 of file caja-desktop-window.c.
Referenced by caja_window_slot_open_location_full().
caja_desktop_window_new()
CajaDesktopWindow * caja_desktop_window_new (CajaApplication * application, GdkScreen * screen)
Definition at line 187 of file caja-desktop-window.c.
References _, CAJA_DESKTOP_WINDOW, caja_desktop_window_get_type(), caja_desktop_window_update_directory(), FALSE, GDK_IS_X11_DISPLAY, NULL, and TRUE.
caja_desktop_window_update_directory()
void caja_desktop_window_update_directory (CajaDesktopWindow * window)
Definition at line 143 of file caja-desktop-window.c.
References CAJA_IS_DESKTOP_WINDOW, CAJA_WINDOW, caja_window_go_to(), EEL_DESKTOP_URI, and TRUE.
Referenced by caja_desktop_window_new().
G_DEFINE_TYPE()
G_DEFINE_TYPE (CajaDesktopWindowAccessible , caja_desktop_window_accessible , GTK_TYPE_WINDOW_ACCESSIBLE)
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (CajaDesktopWindow , caja_desktop_window , CAJA_TYPE_SPATIAL_WINDOW)
References action, CAJA_ACTION_CLOSE, CAJA_TYPE_SPATIAL_WINDOW, CAJA_WINDOW, FALSE, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, and G_GNUC_END_IGNORE_DEPRECATIONS.