MATE Desktop Environment: caja-window.c File Reference
caja-window.c File Reference
#include <config.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gdk/gdkx.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <eel/eel-debug.h>
#include <eel/eel-gtk-macros.h>
#include <eel/eel-string.h>
#include <libcaja-private/caja-file-utilities.h>
#include <libcaja-private/caja-file-attributes.h>
#include <libcaja-private/caja-global-preferences.h>
#include <libcaja-private/caja-metadata.h>
#include <libcaja-private/caja-mime-actions.h>
#include <libcaja-private/caja-program-choosing.h>
#include <libcaja-private/caja-view-factory.h>
#include <libcaja-private/caja-clipboard.h>
#include <libcaja-private/caja-search-directory.h>
#include <libcaja-private/caja-signaller.h>
#include "caja-window-private.h"
#include "caja-actions.h"
#include "caja-application.h"
#include "caja-bookmarks-window.h"
#include "caja-information-panel.h"
#include "caja-window-manage-views.h"
#include "caja-window-bookmarks.h"
#include "caja-window-slot.h"
#include "caja-navigation-window-slot.h"
#include "caja-search-bar.h"
#include "caja-navigation-window-pane.h"
#include "caja-src-marshal.h"
Macros
#define MAX_HISTORY_ITEMS 50
#define EXTRA_VIEW_WIDGETS_BACKGROUND "#a7c6e1"
#define CAJA_MENU_PATH_EXTRA_VIEWER_PLACEHOLDER "/MenuBar/View/View Choices/Extra Viewer"
#define CAJA_MENU_PATH_SHORT_LIST_PLACEHOLDER "/MenuBar/View/View Choices/Short List"
Enumerations
enum { ARG_0 , ARG_APP }
enum {
GO_UP , RELOAD , PROMPT_FOR_LOCATION , ZOOM_CHANGED ,
VIEW_AS_CHANGED , LAST_SIGNAL
}
Functions
G_DEFINE_TYPE_WITH_CODE (CajaWindow, caja_window, GTK_TYPE_WINDOW, G_IMPLEMENT_INTERFACE(CAJA_TYPE_WINDOW_INFO, caja_window_info_iface_init))
void caja_window_sync_status (CajaWindow *window)
void caja_window_go_to (CajaWindow *window, GFile *location)
void caja_window_go_to_tab (CajaWindow *window, GFile *location)
void caja_window_go_to_full (CajaWindow *window, GFile *location, CajaWindowGoToCallback callback, gpointer user_data)
void caja_window_go_to_with_selection (CajaWindow *window, GFile *location, GList *new_selection)
void caja_window_new_tab (CajaWindow *window)
void caja_window_new_window (CajaWindow *window)
void caja_window_go_up (CajaWindow *window, gboolean close_behind, gboolean new_tab)
void caja_window_allow_up (CajaWindow *window, gboolean allow)
void caja_window_sync_allow_stop (CajaWindow *window, CajaWindowSlot *slot)
void caja_window_reload (CajaWindow *window, gboolean new_tab)
void caja_window_allow_reload (CajaWindow *window, gboolean allow)
void caja_window_go_home (CajaWindow *window)
void caja_window_prompt_for_location (CajaWindow *window, const char *initial)
void caja_window_zoom_in (CajaWindow *window)
void caja_window_zoom_to_level (CajaWindow *window, CajaZoomLevel level)
void caja_window_zoom_out (CajaWindow *window)
void caja_window_zoom_to_default (CajaWindow *window)
void caja_window_show_window (CajaWindow *window)
void caja_window_close (CajaWindow *window)
CajaWindowSlot * caja_window_open_slot (CajaWindowPane *pane, CajaWindowOpenSlotFlags flags)
void caja_window_close_pane (CajaWindowPane *pane)
void caja_window_close_slot (CajaWindowSlot *slot)
CajaWindowPane * caja_window_get_active_pane (CajaWindow *window)
void caja_window_set_active_pane (CajaWindow *window, CajaWindowPane *new_pane)
void caja_window_set_active_slot (CajaWindow *window, CajaWindowSlot *new_slot)
void caja_window_slot_close (CajaWindowSlot *slot)
void caja_window_load_view_as_menus (CajaWindow *window)
void caja_window_display_error (CajaWindow *window, const char *error_msg)
void caja_window_sync_title (CajaWindow *window, CajaWindowSlot *slot)
void caja_window_sync_zoom_widgets (CajaWindow *window)
void caja_window_connect_content_view (CajaWindow *window, CajaView *view)
void caja_window_disconnect_content_view (CajaWindow *window, CajaView *view)
GtkUIManager * caja_window_get_ui_manager (CajaWindow *window)
CajaWindowPane * caja_window_get_next_pane (CajaWindow *window)
void caja_window_slot_set_viewed_file (CajaWindowSlot *slot, CajaFile *file)
void caja_send_history_list_changed (void)
gboolean caja_add_bookmark_to_history_list (CajaBookmark *bookmark)
void caja_remove_from_history_list_no_notify (GFile *location)
gboolean caja_add_to_history_list_no_notify (GFile *location, const char *name, gboolean has_custom_name, GIcon *icon)
CajaWindowSlot * caja_window_get_slot_for_view (CajaWindow *window, CajaView *view)
void caja_forget_history (void)
GList * caja_get_history_list (void)
CajaWindowSlot * caja_window_get_active_slot (CajaWindow *window)
CajaWindowSlot * caja_window_get_extra_slot (CajaWindow *window)
GList * caja_window_get_slots (CajaWindow *window)
Macro Definition Documentation
CAJA_MENU_PATH_EXTRA_VIEWER_PLACEHOLDER
#define CAJA_MENU_PATH_EXTRA_VIEWER_PLACEHOLDER "/MenuBar/View/View Choices/Extra Viewer"
Definition at line 73 of file caja-window.c.
CAJA_MENU_PATH_SHORT_LIST_PLACEHOLDER
#define CAJA_MENU_PATH_SHORT_LIST_PLACEHOLDER "/MenuBar/View/View Choices/Short List"
Definition at line 74 of file caja-window.c.
EXTRA_VIEW_WIDGETS_BACKGROUND
#define EXTRA_VIEW_WIDGETS_BACKGROUND "#a7c6e1"
Definition at line 69 of file caja-window.c.
MAX_HISTORY_ITEMS
#define MAX_HISTORY_ITEMS 50
Definition at line 67 of file caja-window.c.
Referenced by caja_add_bookmark_to_history_list().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ARG_0
ARG_APP
Definition at line 76 of file caja-window.c.
anonymous enum
anonymous enum
Enumerator
GO_UP
RELOAD
PROMPT_FOR_LOCATION
ZOOM_CHANGED
VIEW_AS_CHANGED
LAST_SIGNAL
Definition at line 81 of file caja-window.c.
Function Documentation
caja_add_bookmark_to_history_list()
gboolean caja_add_bookmark_to_history_list (CajaBookmark * bookmark)
Definition at line 1786 of file caja-window.c.
References caja_bookmark_compare_uris(), CAJA_IS_BOOKMARK, eel_debug_call_at_shutdown(), FALSE, MAX_HISTORY_ITEMS, and TRUE.
Referenced by caja_add_to_history_list_no_notify(), and caja_window_slot_add_current_location_to_history_list().
caja_add_to_history_list_no_notify()
gboolean caja_add_to_history_list_no_notify (GFile * location, const char * name, gboolean has_custom_name, GIcon * icon)
Definition at line 1844 of file caja-window.c.
References caja_add_bookmark_to_history_list(), caja_bookmark_new(), and name.
caja_forget_history()
void caja_forget_history (void)
Definition at line 1885 of file caja-window.c.
References CAJA_APPLICATION, CAJA_IS_NAVIGATION_WINDOW, CAJA_NAVIGATION_WINDOW, caja_navigation_window_allow_back(), caja_navigation_window_allow_forward(), caja_navigation_window_slot_clear_back_list(), caja_navigation_window_slot_clear_forward_list(), CAJA_WINDOW, CAJA_WINDOW_SLOT, caja_window_slot_add_current_location_to_history_list(), CajaWindowSlot::current_location_bookmark, FALSE, NULL, and _CajaWindowPane::slots.
caja_get_history_list()
GList * caja_get_history_list (void)
Definition at line 1962 of file caja-window.c.
caja_remove_from_history_list_no_notify()
void caja_remove_from_history_list_no_notify (GFile * location)
Definition at line 1834 of file caja-window.c.
References caja_bookmark_new(), FALSE, and NULL.
caja_send_history_list_changed()
void caja_send_history_list_changed (void)
Definition at line 1746 of file caja-window.c.
References caja_signaller_get_current().
Referenced by caja_window_slot_add_current_location_to_history_list().
caja_window_allow_reload()
void caja_window_allow_reload (CajaWindow * window, gboolean allow)
Definition at line 508 of file caja-window.c.
References action, CAJA_ACTION_RELOAD, CAJA_IS_WINDOW, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, and G_GNUC_END_IGNORE_DEPRECATIONS.
caja_window_allow_up()
void caja_window_allow_up (CajaWindow * window, gboolean allow)
Definition at line 419 of file caja-window.c.
References CAJA_IS_WINDOW, CAJA_WINDOW_CLASS, and EEL_CALL_METHOD.
Referenced by caja_window_update_up_button().
caja_window_close()
void caja_window_close (CajaWindow * window)
Definition at line 837 of file caja-window.c.
References CAJA_IS_WINDOW, CAJA_WINDOW_CLASS, and EEL_CALL_METHOD.
Referenced by caja_application_close_all_navigation_windows(), caja_application_close_all_spatial_windows(), caja_application_close_parent_windows(), caja_window_pane_slot_close(), and caja_window_slot_open_location_full().
caja_window_close_pane()
void caja_window_close_pane (CajaWindowPane * pane)
Definition at line 868 of file caja-window.c.
References CAJA_IS_WINDOW, CAJA_IS_WINDOW_PANE, caja_window_close_slot(), CajaWindow::details, NULL, _CajaWindowPrivate::panes, _CajaWindowPane::slots, and _CajaWindowPane::window.
Referenced by caja_navigation_window_split_view_off(), and caja_window_pane_slot_close().
caja_window_close_slot()
void caja_window_close_slot (CajaWindowSlot * slot)
Definition at line 907 of file caja-window.c.
References _CajaWindowPane::active_slots, CAJA_IS_WINDOW_PANE, CAJA_IS_WINDOW_SLOT, CAJA_WINDOW_CLASS, EEL_CALL_METHOD, NULL, CajaWindowSlot::pane, _CajaWindowPane::slots, and _CajaWindowPane::window.
Referenced by caja_window_close_pane(), and caja_window_pane_slot_close().
caja_window_connect_content_view()
void caja_window_connect_content_view (CajaWindow * window, CajaView * view)
Definition at line 1606 of file caja-window.c.
References CAJA_IS_VIEW, CAJA_IS_WINDOW, caja_view_grab_focus(), caja_window_get_active_slot(), caja_window_get_slot_for_view(), caja_window_load_view_as_menus(), NULL, and CajaWindowSlot::pending_location.
Referenced by caja_window_slot_connect_content_view().
caja_window_disconnect_content_view()
void caja_window_disconnect_content_view (CajaWindow * window, CajaView * view)
Definition at line 1635 of file caja-window.c.
References CAJA_IS_VIEW, CAJA_IS_WINDOW, caja_window_get_active_slot(), and caja_window_get_slot_for_view().
Referenced by caja_window_slot_disconnect_content_view().
caja_window_display_error()
void caja_window_display_error (CajaWindow * window, const char * error_msg)
Definition at line 1495 of file caja-window.c.
References CAJA_IS_WINDOW, and NULL.
caja_window_get_active_pane()
CajaWindowPane * caja_window_get_active_pane (CajaWindow * window)
Definition at line 930 of file caja-window.c.
References CAJA_IS_WINDOW.
caja_window_get_active_slot()
CajaWindowSlot * caja_window_get_active_slot (CajaWindow * window)
Definition at line 2078 of file caja-window.c.
References CAJA_IS_WINDOW.
Referenced by caja_application_open_location(), caja_navigation_window_split_view_on(), caja_window_connect_content_view(), caja_window_disconnect_content_view(), and caja_window_slot_connect_content_view().
caja_window_get_extra_slot()
CajaWindowSlot * caja_window_get_extra_slot (CajaWindow * window)
Definition at line 2086 of file caja-window.c.
References _CajaWindowPane::active_slot, CAJA_IS_WINDOW, FALSE, and NULL.
caja_window_get_next_pane()
CajaWindowPane * caja_window_get_next_pane (CajaWindow * window)
Definition at line 1677 of file caja-window.c.
References NULL.
Referenced by caja_navigation_window_update_split_view_actions_sensitivity(), and caja_window_pane_slot_close().
caja_window_get_slot_for_view()
CajaWindowSlot * caja_window_get_slot_for_view (CajaWindow * window, CajaView * view)
Definition at line 1860 of file caja-window.c.
References CajaWindowSlot::content_view, CajaWindowSlot::new_content_view, NULL, and _CajaWindowPane::slots.
Referenced by caja_window_connect_content_view(), caja_window_disconnect_content_view(), caja_window_report_load_complete(), caja_window_report_load_underway(), and caja_window_report_view_failed().
caja_window_get_slots()
GList * caja_window_get_slots (CajaWindow * window)
Definition at line 2118 of file caja-window.c.
References CAJA_IS_WINDOW, NULL, and _CajaWindowPane::slots.
caja_window_get_ui_manager()
GtkUIManager * caja_window_get_ui_manager (CajaWindow * window)
Definition at line 1669 of file caja-window.c.
References CAJA_IS_WINDOW, and NULL.
Referenced by caja_location_bar_new(), caja_navigation_window_initialize_actions(), caja_navigation_window_initialize_menus(), caja_navigation_window_load_extension_toolbar_items(), caja_navigation_window_remove_go_menu_items(), and caja_search_bar_new().
caja_window_go_home()
void caja_window_go_home (CajaWindow * window)
Definition at line 522 of file caja-window.c.
References CAJA_IS_WINDOW, caja_window_slot_go_home(), and FALSE.
caja_window_go_to()
void caja_window_go_to (CajaWindow * window, GFile * location)
Definition at line 234 of file caja-window.c.
References CAJA_IS_WINDOW, caja_window_slot_go_to, and FALSE.
Referenced by caja_desktop_window_update_directory().
caja_window_go_to_full()
void caja_window_go_to_full (CajaWindow * window, GFile * location, CajaWindowGoToCallback callback, gpointer user_data)
Definition at line 250 of file caja-window.c.
References CAJA_IS_WINDOW, caja_window_slot_go_to_full, FALSE, and user_data.
Referenced by caja_connect_server_dialog_display_location_async().
caja_window_go_to_tab()
void caja_window_go_to_tab (CajaWindow * window, GFile * location)
Definition at line 242 of file caja-window.c.
References CAJA_IS_WINDOW, caja_window_slot_go_to, and TRUE.
caja_window_go_to_with_selection()
void caja_window_go_to_with_selection (CajaWindow * window, GFile * location, GList * new_selection)
Definition at line 261 of file caja-window.c.
References CAJA_IS_WINDOW, and caja_window_slot_go_to_with_selection.
caja_window_go_up()
void caja_window_go_up (CajaWindow * window, gboolean close_behind, gboolean new_tab)
Definition at line 354 of file caja-window.c.
References CAJA_IS_WINDOW, CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, CAJA_WINDOW_OPEN_FLAG_CLOSE_BEHIND, CAJA_WINDOW_OPEN_FLAG_NEW_TAB, caja_window_slot_open_location_full(), CajaWindowSlot::location, and NULL.
caja_window_load_view_as_menus()
void caja_window_load_view_as_menus (CajaWindow * window)
Definition at line 1476 of file caja-window.c.
References caja_file_call_when_ready(), CAJA_IS_WINDOW, caja_mime_actions_get_required_file_attributes(), and CajaWindowSlot::viewed_file.
Referenced by caja_window_connect_content_view().
caja_window_new_tab()
void caja_window_new_tab (CajaWindow * window)
Definition at line 282 of file caja-window.c.
References CAJA_NEW_TAB_POSITION_END, caja_preferences, CAJA_PREFERENCES_NEW_TAB_POSITION, caja_window_open_slot(), CAJA_WINDOW_OPEN_SLOT_APPEND, caja_window_set_active_slot(), caja_window_slot_get_location(), caja_window_slot_go_to, FALSE, NULL, and CajaWindowSlot::pane.
caja_window_new_window()
void caja_window_new_window (CajaWindow * window)
Definition at line 319 of file caja-window.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, caja_application_create_navigation_window(), CAJA_IS_WINDOW, CAJA_IS_WINDOW_SLOT, CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, caja_window_slot_get_location(), caja_window_slot_open_location_full(), CajaWindow::details, FALSE, and NULL.
caja_window_open_slot()
CajaWindowSlot * caja_window_open_slot (CajaWindowPane * pane, CajaWindowOpenSlotFlags flags)
Definition at line 848 of file caja-window.c.
References CAJA_IS_WINDOW, CAJA_IS_WINDOW_PANE, CAJA_IS_WINDOW_SLOT, CAJA_WINDOW_CLASS, EEL_CALL_METHOD_WITH_RETURN_VALUE, CajaWindowSlot::pane, _CajaWindowPane::slots, and _CajaWindowPane::window.
Referenced by caja_window_new_tab(), and caja_window_slot_open_location_full().
caja_window_prompt_for_location()
void caja_window_prompt_for_location (CajaWindow * window, const char * initial)
Definition at line 530 of file caja-window.c.
References CAJA_IS_WINDOW, CAJA_WINDOW_CLASS, and EEL_CALL_METHOD.
caja_window_reload()
void caja_window_reload (CajaWindow * window, gboolean new_tab)
Definition at line 486 of file caja-window.c.
References CAJA_IS_WINDOW, CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, CAJA_WINDOW_OPEN_FLAG_NEW_TAB, caja_window_slot_open_location_full(), caja_window_slot_reload(), CajaWindowSlot::location, and NULL.
caja_window_set_active_pane()
void caja_window_set_active_pane (CajaWindow * window, CajaWindowPane * new_pane)
Definition at line 955 of file caja-window.c.
References _CajaWindowPane::active_slot, CAJA_IS_WINDOW_PANE, and caja_window_set_active_slot().
Referenced by caja_window_pane_zoom_in(), caja_window_pane_zoom_out(), caja_window_pane_zoom_to_default(), and caja_window_pane_zoom_to_level().
caja_window_set_active_slot()
void caja_window_set_active_slot (CajaWindow * window, CajaWindowSlot * new_slot)
Definition at line 973 of file caja-window.c.
References CAJA_IS_WINDOW, CAJA_IS_WINDOW_PANE, CAJA_IS_WINDOW_SLOT, caja_window_report_location_change(), caja_window_slot_connect_content_view(), caja_window_slot_disconnect_content_view(), CajaWindowSlot::content_view, NULL, CajaWindowSlot::pane, _CajaWindowPane::slots, and _CajaWindowPane::window.
Referenced by caja_window_new_tab(), caja_window_pane_slot_close(), and caja_window_set_active_pane().
caja_window_show_window()
void caja_window_show_window (CajaWindow * window)
Definition at line 745 of file caja-window.c.
References caja_file_set_has_open_window(), CAJA_IS_SPATIAL_WINDOW, caja_window_slot_update_icon(), caja_window_slot_update_title(), NULL, _CajaWindowPane::slots, TRUE, and CajaWindowSlot::viewed_file.
caja_window_slot_close()
void caja_window_slot_close (CajaWindowSlot * slot)
Definition at line 1047 of file caja-window.c.
References caja_window_pane_slot_close(), and CajaWindowSlot::pane.
caja_window_slot_set_viewed_file()
void caja_window_slot_set_viewed_file (CajaWindowSlot * slot, CajaFile * file)
Definition at line 1704 of file caja-window.c.
References CAJA_FILE_ATTRIBUTE_INFO, CAJA_FILE_ATTRIBUTE_LINK_INFO, caja_file_monitor_add(), caja_file_monitor_remove(), caja_file_ref(), caja_file_set_has_open_window(), caja_file_unref(), CAJA_IS_SPATIAL_WINDOW, FALSE, NULL, CajaWindowSlot::pane, CajaWindowSlot::viewed_file, and _CajaWindowPane::window.
caja_window_sync_allow_stop()
void caja_window_sync_allow_stop (CajaWindow * window, CajaWindowSlot * slot)
Definition at line 451 of file caja-window.c.
References action, CajaWindowSlot::allow_stop, CAJA_ACTION_STOP, CAJA_IS_WINDOW, CAJA_WINDOW_CLASS, EEL_CALL_METHOD, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, and G_GNUC_END_IGNORE_DEPRECATIONS.
Referenced by caja_window_slot_set_allow_stop().
caja_window_sync_status()
void caja_window_sync_status (CajaWindow * window)
Definition at line 225 of file caja-window.c.
References CajaWindowSlot::status_text.
Referenced by caja_window_slot_set_status().
caja_window_sync_title()
void caja_window_sync_title (CajaWindow * window, CajaWindowSlot * slot)
Definition at line 1526 of file caja-window.c.
References CAJA_WINDOW_CLASS, and EEL_CALL_METHOD.
caja_window_sync_zoom_widgets()
void caja_window_sync_zoom_widgets (CajaWindow * window)
Definition at line 1534 of file caja-window.c.
References action, CAJA_ACTION_ZOOM_IN, CAJA_ACTION_ZOOM_NORMAL, CAJA_ACTION_ZOOM_OUT, caja_view_can_zoom_in(), caja_view_can_zoom_out(), caja_view_get_zoom_level(), caja_view_supports_zooming(), CAJA_ZOOM_LEVEL_LARGEST, CAJA_ZOOM_LEVEL_SMALLEST, CAJA_ZOOM_LEVEL_STANDARD, CajaWindowSlot::content_view, FALSE, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, NULL, and ZOOM_CHANGED.
caja_window_zoom_in()
void caja_window_zoom_in (CajaWindow * window)
Definition at line 556 of file caja-window.c.
References caja_window_pane_zoom_in(), and NULL.
caja_window_zoom_out()
void caja_window_zoom_out (CajaWindow * window)
Definition at line 573 of file caja-window.c.
References caja_window_pane_zoom_out(), and NULL.
caja_window_zoom_to_default()
void caja_window_zoom_to_default (CajaWindow * window)
Definition at line 581 of file caja-window.c.
References caja_window_pane_zoom_to_default(), and NULL.
caja_window_zoom_to_level()
void caja_window_zoom_to_level (CajaWindow * window, CajaZoomLevel level)
Definition at line 564 of file caja-window.c.
References caja_window_pane_zoom_to_level(), level, and NULL.
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (CajaWindow , caja_window , GTK_TYPE_WINDOW , G_IMPLEMENT_INTERFACE(CAJA_TYPE_WINDOW_INFO, caja_window_info_iface_init))
References CAJA_TYPE_WINDOW_INFO.
Variable Documentation
action
const char* action
Definition at line 113 of file caja-window.c.
keyval
unsigned int keyval
Definition at line 112 of file caja-window.c.