MATE Desktop Environment: caja-directory.c File Reference
caja-directory.c File Reference
#include <config.h>
#include <gtk/gtk.h>
#include <string.h>
#include <eel/eel-glib-extensions.h>
#include <eel/eel-gtk-macros.h>
#include "caja-directory-private.h"
#include "caja-directory-notify.h"
#include "caja-file-attributes.h"
#include "caja-file-private.h"
#include "caja-file-utilities.h"
#include "caja-search-directory.h"
#include "caja-global-preferences.h"
#include "caja-lib-self-check-functions.h"
#include "caja-metadata.h"
#include "caja-desktop-directory.h"
#include "caja-vfs-directory.h"
#include <eel/eel-debug.h>
Enumerations
enum {
FILES_ADDED , FILES_CHANGED , DONE_LOADING , LOAD_ERROR ,
LAST_SIGNAL
}
Functions
CajaDirectory * caja_directory_ref (CajaDirectory *directory)
void caja_directory_unref (CajaDirectory *directory)
void emit_change_signals_for_all_files (CajaDirectory *directory)
void emit_change_signals_for_all_files_in_all_directories (void)
CajaDirectory * caja_directory_get_internal (GFile *location, gboolean create)
CajaDirectory * caja_directory_get (GFile *location)
CajaDirectory * caja_directory_get_existing (GFile *location)
CajaDirectory * caja_directory_get_by_uri (const char *uri)
CajaDirectory * caja_directory_get_for_file (CajaFile *file)
CajaFile * caja_directory_get_corresponding_file (CajaDirectory *directory)
CajaFile * caja_directory_get_existing_corresponding_file (CajaDirectory *directory)
char * caja_directory_get_name_for_self_as_new_file (CajaDirectory *directory)
char * caja_directory_get_uri (CajaDirectory *directory)
GFile * caja_directory_get_location (CajaDirectory *directory)
gboolean caja_directory_is_local (CajaDirectory *directory)
gboolean caja_directory_is_in_trash (CajaDirectory *directory)
gboolean caja_directory_are_all_files_seen (CajaDirectory *directory)
void caja_directory_add_file (CajaDirectory *directory, CajaFile *file)
void caja_directory_remove_file (CajaDirectory *directory, CajaFile *file)
GList * caja_directory_begin_file_name_change (CajaDirectory *directory, CajaFile *file)
void caja_directory_end_file_name_change (CajaDirectory *directory, CajaFile *file, GList *node)
CajaFile * caja_directory_find_file_by_name (CajaDirectory *directory, const char *name)
void caja_directory_emit_files_added (CajaDirectory *directory, GList *added_files)
void caja_directory_emit_files_changed (CajaDirectory *directory, GList *changed_files)
void caja_directory_emit_change_signals (CajaDirectory *directory, GList *changed_files)
void caja_directory_emit_done_loading (CajaDirectory *directory)
void caja_directory_emit_load_error (CajaDirectory *directory, GError *error)
void caja_directory_notify_files_added (GList *files)
void caja_directory_notify_files_changed (GList *files)
void caja_directory_notify_files_removed (GList *files)
void caja_directory_moved (const char *old_uri, const char *new_uri)
void caja_directory_notify_files_moved (GList *file_pairs)
void caja_directory_schedule_position_set (GList *position_setting_list)
gboolean caja_directory_contains_file (CajaDirectory *directory, CajaFile *file)
void caja_directory_call_when_ready (CajaDirectory *directory, CajaFileAttributes file_attributes, gboolean wait_for_all_files, CajaDirectoryCallback callback, gpointer callback_data)
void caja_directory_cancel_callback (CajaDirectory *directory, CajaDirectoryCallback callback, gpointer callback_data)
void caja_directory_file_monitor_add (CajaDirectory *directory, gconstpointer client, gboolean monitor_hidden_files, CajaFileAttributes file_attributes, CajaDirectoryCallback callback, gpointer callback_data)
void caja_directory_file_monitor_remove (CajaDirectory *directory, gconstpointer client)
void caja_directory_force_reload (CajaDirectory *directory)
gboolean caja_directory_is_not_empty (CajaDirectory *directory)
GList * caja_directory_get_file_list (CajaDirectory *directory)
gboolean caja_directory_is_editable (CajaDirectory *directory)
GList * caja_directory_match_pattern (CajaDirectory *directory, const char *pattern)
GList * caja_directory_list_ref (GList *list)
void caja_directory_list_unref (GList *list)
void caja_directory_list_free (GList *list)
GList * caja_directory_list_copy (GList *list)
GList * caja_directory_list_sort_by_uri (GList *list)
gboolean caja_directory_is_desktop_directory (CajaDirectory *directory)
int caja_directory_number_outstanding (void)
void caja_self_check_directory (void)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FILES_ADDED
FILES_CHANGED
DONE_LOADING
LOAD_ERROR
LAST_SIGNAL
Definition at line 44 of file caja-directory.c.
Function Documentation
caja_directory_add_file()
void caja_directory_add_file (CajaDirectory * directory, CajaFile * file)
Definition at line 557 of file caja-directory.c.
References caja_directory_add_file_to_work_queue(), caja_directory_has_active_request_for_file(), caja_directory_is_file_list_monitored(), caja_file_ref(), CAJA_IS_DIRECTORY, CAJA_IS_FILE, _CajaDirectoryPrivate::confirmed_file_count, CajaDirectory::details, CajaFile::details, FALSE, _CajaDirectoryPrivate::file_list, _CajaFilePrivate::name, NULL, and TRUE.
Referenced by caja_desktop_icon_file_new(), and caja_file_update_name_and_directory().
caja_directory_are_all_files_seen()
gboolean caja_directory_are_all_files_seen (CajaDirectory * directory)
Definition at line 512 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, CAJA_IS_DIRECTORY, FALSE, and NULL.
caja_directory_begin_file_name_change()
GList * caja_directory_begin_file_name_change (CajaDirectory * directory, CajaFile * file)
Definition at line 630 of file caja-directory.c.
caja_directory_call_when_ready()
void caja_directory_call_when_ready (CajaDirectory * directory, CajaFileAttributes file_attributes, gboolean wait_for_all_files, CajaDirectoryCallback callback, gpointer callback_data)
Definition at line 1401 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, CAJA_IS_DIRECTORY, and NULL.
Referenced by caja_self_check_directory().
caja_directory_cancel_callback()
void caja_directory_cancel_callback (CajaDirectory * directory, CajaDirectoryCallback callback, gpointer callback_data)
Definition at line 1421 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, CAJA_IS_DIRECTORY, and NULL.
caja_directory_contains_file()
gboolean caja_directory_contains_file (CajaDirectory * directory, CajaFile * file)
Definition at line 1383 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, caja_file_is_gone(), CAJA_IS_DIRECTORY, CAJA_IS_FILE, FALSE, and NULL.
caja_directory_emit_change_signals()
void caja_directory_emit_change_signals (CajaDirectory * directory, GList * changed_files)
Definition at line 688 of file caja-directory.c.
References caja_directory_emit_files_changed(), caja_file_emit_changed(), and NULL.
Referenced by caja_desktop_icon_file_remove(), caja_file_changed(), and emit_change_signals_for_all_files().
caja_directory_emit_done_loading()
void caja_directory_emit_done_loading (CajaDirectory * directory)
Definition at line 701 of file caja-directory.c.
References DONE_LOADING.
caja_directory_emit_files_added()
void caja_directory_emit_files_added (CajaDirectory * directory, GList * added_files)
Definition at line 664 of file caja-directory.c.
References FILES_ADDED, and NULL.
Referenced by caja_desktop_icon_file_new().
caja_directory_emit_files_changed()
void caja_directory_emit_files_changed (CajaDirectory * directory, GList * changed_files)
Definition at line 676 of file caja-directory.c.
References FILES_CHANGED, and NULL.
Referenced by caja_directory_emit_change_signals().
caja_directory_emit_load_error()
void caja_directory_emit_load_error (CajaDirectory * directory, GError * error)
Definition at line 708 of file caja-directory.c.
References error, and LOAD_ERROR.
caja_directory_end_file_name_change()
void caja_directory_end_file_name_change (CajaDirectory * directory, CajaFile * file, GList * node)
Definition at line 638 of file caja-directory.c.
References NULL.
caja_directory_file_monitor_add()
void caja_directory_file_monitor_add (CajaDirectory * directory, gconstpointer client, gboolean monitor_hidden_files, CajaFileAttributes file_attributes, CajaDirectoryCallback callback, gpointer callback_data)
Definition at line 1435 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, CAJA_IS_DIRECTORY, and NULL.
Referenced by caja_self_check_directory(), fm_directory_view_add_subdirectory(), and main().
caja_directory_file_monitor_remove()
void caja_directory_file_monitor_remove (CajaDirectory * directory, gconstpointer client)
Definition at line 1456 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, CAJA_IS_DIRECTORY, and NULL.
Referenced by caja_self_check_directory(), fm_directory_view_remove_subdirectory(), and fm_directory_view_stop().
caja_directory_find_file_by_name()
CajaFile * caja_directory_find_file_by_name (CajaDirectory * directory, const char * name)
Definition at line 650 of file caja-directory.c.
References CAJA_FILE, CAJA_IS_DIRECTORY, CajaDirectory::details, _CajaDirectoryPrivate::file_hash, name, and NULL.
caja_directory_force_reload()
void caja_directory_force_reload (CajaDirectory * directory)
Definition at line 1469 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, CAJA_IS_DIRECTORY, and NULL.
caja_directory_get()
CajaDirectory * caja_directory_get (GFile * location)
Definition at line 302 of file caja-directory.c.
References caja_directory_get_internal(), NULL, and TRUE.
Referenced by caja_navigation_window_pane_hide_temporary_bars().
caja_directory_get_by_uri()
CajaDirectory * caja_directory_get_by_uri (const char * uri)
Definition at line 324 of file caja-directory.c.
References caja_directory_get_internal(), NULL, and TRUE.
Referenced by caja_desktop_icon_file_new(), caja_directory_get_for_file(), caja_self_check_directory(), and main().
caja_directory_get_corresponding_file()
CajaFile * caja_directory_get_corresponding_file (CajaDirectory * directory)
Definition at line 358 of file caja-directory.c.
References caja_directory_get_existing_corresponding_file(), caja_directory_get_uri(), caja_file_get_by_uri(), and NULL.
Referenced by caja_file_get_parent().
caja_directory_get_existing()
CajaDirectory * caja_directory_get_existing (GFile * location)
Definition at line 313 of file caja-directory.c.
References caja_directory_get_internal(), FALSE, and NULL.
caja_directory_get_existing_corresponding_file()
CajaFile * caja_directory_get_existing_corresponding_file (CajaDirectory * directory)
Definition at line 379 of file caja-directory.c.
References _CajaDirectoryPrivate::as_file, caja_directory_get_uri(), caja_file_get_existing_by_uri(), caja_file_ref(), CajaDirectory::details, and NULL.
Referenced by caja_directory_get_corresponding_file(), and caja_directory_invalidate_count_and_mime_list().
caja_directory_get_file_list()
GList * caja_directory_get_file_list (CajaDirectory * directory)
Definition at line 1508 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, and NULL.
Referenced by caja_directory_match_pattern(), and caja_directory_monitor_add_internal().
caja_directory_get_for_file()
CajaDirectory * caja_directory_get_for_file (CajaFile * file)
Definition at line 342 of file caja-directory.c.
References caja_directory_get_by_uri(), caja_file_get_uri(), CAJA_IS_FILE, and NULL.
Referenced by caja_file_get_volume_free_space(), fm_list_model_load_subdirectory(), and G_DEFINE_TYPE_WITH_CODE().
caja_directory_get_internal()
CajaDirectory * caja_directory_get_internal (GFile * location, gboolean create)
caja_directory_get_by_uri: @uri: URI of directory to get.
Get a directory given a uri. Creates the appropriate subclass given the uri mappings. Returns a referenced object, not a floating one. Unref when finished. If two windows are viewing the same uri, the directory object is shared.
Definition at line 265 of file caja-directory.c.
References caja_directory_ref(), caja_global_preferences_init(), CajaDirectory::details, _CajaDirectoryPrivate::location, and NULL.
Referenced by caja_directory_get(), caja_directory_get_by_uri(), and caja_directory_get_existing().
caja_directory_get_location()
GFile * caja_directory_get_location (CajaDirectory * directory)
Definition at line 445 of file caja-directory.c.
References CAJA_IS_DIRECTORY, CajaDirectory::details, _CajaDirectoryPrivate::location, and NULL.
Referenced by caja_file_get_parent_location(), and caja_file_get_uri_scheme().
caja_directory_get_name_for_self_as_new_file()
char * caja_directory_get_name_for_self_as_new_file (CajaDirectory * directory)
Definition at line 404 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, CAJA_IS_DIRECTORY, and NULL.
caja_directory_get_uri()
char * caja_directory_get_uri (CajaDirectory * directory)
Definition at line 437 of file caja-directory.c.
References CAJA_IS_DIRECTORY, CajaDirectory::details, _CajaDirectoryPrivate::location, and NULL.
Referenced by caja_directory_get_corresponding_file(), caja_directory_get_existing_corresponding_file(), caja_file_get_parent_uri(), fm_directory_view_get_backing_uri(), and fm_directory_view_get_uri().
caja_directory_is_desktop_directory()
gboolean caja_directory_is_desktop_directory (CajaDirectory * directory)
Definition at line 1667 of file caja-directory.c.
References caja_is_desktop_directory(), CajaDirectory::details, FALSE, _CajaDirectoryPrivate::location, and NULL.
caja_directory_is_editable()
gboolean caja_directory_is_editable (CajaDirectory * directory)
Definition at line 1539 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, FALSE, and NULL.
Referenced by fm_directory_view_is_editable().
caja_directory_is_in_trash()
gboolean caja_directory_is_in_trash (CajaDirectory * directory)
Definition at line 499 of file caja-directory.c.
References CAJA_IS_DIRECTORY, CajaDirectory::details, FALSE, _CajaDirectoryPrivate::location, and NULL.
Referenced by caja_directory_is_local(), and caja_file_is_in_trash().
caja_directory_is_local()
gboolean caja_directory_is_local (CajaDirectory * directory)
Definition at line 485 of file caja-directory.c.
References caja_directory_is_in_trash(), CAJA_IS_DIRECTORY, CajaDirectory::details, FALSE, _CajaDirectoryPrivate::location, NULL, and TRUE.
Referenced by caja_file_is_local().
caja_directory_is_not_empty()
gboolean caja_directory_is_not_empty (CajaDirectory * directory)
Definition at line 1480 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, CAJA_IS_DIRECTORY, FALSE, and NULL.
Referenced by fm_list_model_subdirectory_done_loading().
caja_directory_list_copy()
GList * caja_directory_list_copy (GList * list)
caja_directory_list_copy
Copy the list of directories, making a new ref of each, @list: GList of directories.
Definition at line 1626 of file caja-directory.c.
References caja_directory_list_ref().
caja_directory_list_free()
void caja_directory_list_free (GList * list)
caja_directory_list_free
Free a list of directories after unrefing them. @list: GList of directories.
Definition at line 1613 of file caja-directory.c.
References caja_directory_list_unref().
caja_directory_list_ref()
GList * caja_directory_list_ref (GList * list)
caja_directory_list_ref
Ref all the directories in a list. @list: GList of directories.
Definition at line 1588 of file caja-directory.c.
References caja_directory_ref(), and NULL.
Referenced by caja_directory_list_copy().
caja_directory_list_sort_by_uri()
GList * caja_directory_list_sort_by_uri (GList * list)
caja_directory_list_sort_by_uri
Sort the list of directories by directory uri. @list: GList of directories.
Definition at line 1661 of file caja-directory.c.
caja_directory_list_unref()
void caja_directory_list_unref (GList * list)
caja_directory_list_unref
Unref all the directories in a list. @list: GList of directories.
Definition at line 1601 of file caja-directory.c.
References caja_directory_unref(), and NULL.
Referenced by caja_directory_list_free().
caja_directory_match_pattern()
GList * caja_directory_match_pattern (CajaDirectory * directory, const char * pattern)
Definition at line 1550 of file caja-directory.c.
References caja_directory_get_file_list(), CAJA_FILE, caja_file_get_display_name(), caja_file_list_free(), caja_file_ref(), name, and NULL.
caja_directory_moved()
void caja_directory_moved (const char * old_uri, const char * new_uri)
Definition at line 1159 of file caja-directory.c.
References CAJA_FILE, caja_file_list_free(), caja_file_ref(), CajaFile::details, _CajaFilePrivate::directory, hash, and NULL.
caja_directory_notify_files_added()
void caja_directory_notify_files_added (GList * files)
Definition at line 858 of file caja-directory.c.
References caja_directory_is_file_list_monitored(), caja_directory_unref(), caja_file_changed(), caja_file_get_existing(), caja_file_invalidate_count_and_mime_list(), caja_file_unref(), CajaFile::details, _CajaFilePrivate::is_added, and NULL.
Referenced by caja_directory_notify_files_moved(), caja_file_changes_consume_changes(), and caja_link_local_create().
caja_directory_notify_files_changed()
void caja_directory_notify_files_changed (GList * files)
Definition at line 947 of file caja-directory.c.
References caja_file_get_existing(), caja_file_invalidate_extension_info_internal(), CajaFile::details, _CajaFilePrivate::directory, FALSE, _CajaFilePrivate::file_info_is_up_to_date, _CajaFilePrivate::link_info_is_up_to_date, NULL, and _CajaFilePrivate::top_left_text_is_up_to_date.
Referenced by caja_file_changes_consume_changes().
caja_directory_notify_files_moved()
void caja_directory_notify_files_moved (GList * file_pairs)
Definition at line 1191 of file caja-directory.c.
References caja_directory_cancel_loading_file_attributes(), caja_directory_notify_files_added(), caja_directory_unref(), CAJA_FILE, CAJA_FILE_ATTRIBUTE_INFO, caja_file_get_all_attributes(), caja_file_get_existing(), caja_file_invalidate_attributes(), caja_file_list_free(), caja_file_mark_gone(), caja_file_update_name_and_directory(), CajaFile::details, _CajaFilePrivate::directory, GFilePair::from, name, NULL, and GFilePair::to.
Referenced by caja_file_changes_consume_changes().
caja_directory_notify_files_removed()
void caja_directory_notify_files_removed (GList * files)
Definition at line 985 of file caja-directory.c.
References caja_directory_unref(), caja_file_get_existing(), caja_file_mark_gone(), caja_file_ref(), caja_file_rename_in_progress(), caja_file_unref(), CajaFile::details, _CajaFilePrivate::directory, and NULL.
Referenced by caja_file_changes_consume_changes().
caja_directory_number_outstanding()
int caja_directory_number_outstanding (void)
Definition at line 1697 of file caja-directory.c.
Referenced by caja_self_check_file().
caja_directory_ref()
CajaDirectory * caja_directory_ref (CajaDirectory * directory)
Definition at line 126 of file caja-directory.c.
References CAJA_IS_DIRECTORY, and NULL.
Referenced by caja_desktop_directory_get_real_directory(), caja_directory_async_state_changed(), caja_directory_get_internal(), caja_directory_list_ref(), caja_file_new_from_info(), caja_file_update_name_and_directory(), fm_directory_view_add_subdirectory(), fm_directory_view_get_backing_uri(), and fm_list_model_load_subdirectory().
caja_directory_remove_file()
void caja_directory_remove_file (CajaDirectory * directory, CajaFile * file)
Definition at line 597 of file caja-directory.c.
References caja_directory_is_file_list_monitored(), caja_directory_remove_file_from_work_queue(), caja_file_unref(), CAJA_IS_DIRECTORY, CAJA_IS_FILE, _CajaDirectoryPrivate::confirmed_file_count, CajaDirectory::details, CajaFile::details, _CajaDirectoryPrivate::file_list, _CajaFilePrivate::name, NULL, and _CajaFilePrivate::unconfirmed.
Referenced by caja_desktop_icon_file_remove(), caja_file_mark_gone(), and caja_file_update_name_and_directory().
caja_directory_schedule_position_set()
void caja_directory_schedule_position_set (GList * position_setting_list)
Definition at line 1319 of file caja-directory.c.
References caja_file_get(), caja_file_set_metadata(), caja_file_set_time_metadata(), caja_file_unref(), CAJA_METADATA_KEY_ICON_POSITION, CAJA_METADATA_KEY_ICON_POSITION_TIMESTAMP, CAJA_METADATA_KEY_SCREEN, item, NULL, and UNDEFINED_TIME.
Referenced by caja_file_changes_consume_changes(), and caja_link_local_create().
caja_directory_unref()
void caja_directory_unref (CajaDirectory * directory)
Definition at line 140 of file caja-directory.c.
References CAJA_IS_DIRECTORY, and NULL.
Referenced by caja_directory_async_state_changed(), caja_directory_list_unref(), caja_directory_notify_files_added(), caja_directory_notify_files_moved(), caja_directory_notify_files_removed(), caja_file_get_volume_free_space(), caja_file_update_name_and_directory(), caja_navigation_window_pane_hide_temporary_bars(), caja_self_check_directory(), emit_change_signals_for_all_files_in_all_directories(), fm_directory_view_get_backing_uri(), fm_directory_view_remove_subdirectory(), fm_list_model_load_subdirectory(), fm_list_model_unload_subdirectory(), and G_DEFINE_TYPE_WITH_CODE().
caja_self_check_directory()
void caja_self_check_directory (void)
Definition at line 1703 of file caja-directory.c.
References caja_directory_call_when_ready(), caja_directory_file_monitor_add(), caja_directory_file_monitor_remove(), caja_directory_get_by_uri(), caja_directory_unref(), CAJA_FILE_ATTRIBUTE_DEEP_COUNTS, CAJA_FILE_ATTRIBUTE_INFO, caja_file_get_by_uri(), caja_file_unref(), CajaDirectory::details, EEL_CHECK_BOOLEAN_RESULT, EEL_CHECK_INTEGER_RESULT, FALSE, _CajaDirectoryPrivate::file_list, NULL, and TRUE.
emit_change_signals_for_all_files()
void emit_change_signals_for_all_files (CajaDirectory * directory)
Definition at line 206 of file caja-directory.c.
References _CajaDirectoryPrivate::as_file, caja_directory_emit_change_signals(), caja_file_list_free(), caja_file_list_ref(), CajaDirectory::details, _CajaDirectoryPrivate::file_list, and NULL.
Referenced by emit_change_signals_for_all_files_in_all_directories().
emit_change_signals_for_all_files_in_all_directories()
void emit_change_signals_for_all_files_in_all_directories (void)
Definition at line 235 of file caja-directory.c.
References CAJA_DIRECTORY, caja_directory_unref(), emit_change_signals_for_all_files(), and NULL.