MATE Desktop Environment: caja-debug-log.h File Reference
caja-debug-log.h File Reference
#include <glib.h>
Macros
#define CAJA_DEBUG_LOG_DOMAIN_USER "USER" /* always enabled */
#define CAJA_DEBUG_LOG_DOMAIN_ASYNC "async" /* when asynchronous notifications come in */
#define CAJA_DEBUG_LOG_DOMAIN_GLOG "GLog" /* used for GLog messages; don't use it yourself */
Functions
void caja_debug_log (gboolean is_milestone, const char *domain, const char *format,...)
void caja_debug_log_with_uri_list (gboolean is_milestone, const char *domain, const GList *uris, const char *format,...)
void caja_debug_log_with_file_list (gboolean is_milestone, const char *domain, GList *files, const char *format,...)
void caja_debug_logv (gboolean is_milestone, const char *domain, const GList *uris, const char *format, va_list args)
gboolean caja_debug_log_load_configuration (const char *filename, GError **error)
void caja_debug_log_enable_domains (const char **domains, int n_domains)
void caja_debug_log_disable_domains (const char **domains, int n_domains)
gboolean caja_debug_log_is_domain_enabled (const char *domain)
gboolean caja_debug_log_dump (const char *filename, GError **error)
void caja_debug_log_set_max_lines (int num_lines)
int caja_debug_log_get_max_lines (void)
void caja_debug_log_clear (void)
Macro Definition Documentation
CAJA_DEBUG_LOG_DOMAIN_ASYNC
#define CAJA_DEBUG_LOG_DOMAIN_ASYNC "async" /* when asynchronous notifications come in */
Definition at line 31 of file caja-debug-log.h.
CAJA_DEBUG_LOG_DOMAIN_GLOG
#define CAJA_DEBUG_LOG_DOMAIN_GLOG "GLog" /* used for GLog messages; don't use it yourself */
Definition at line 32 of file caja-debug-log.h.
CAJA_DEBUG_LOG_DOMAIN_USER
#define CAJA_DEBUG_LOG_DOMAIN_USER "USER" /* always enabled */
Definition at line 30 of file caja-debug-log.h.
Referenced by caja_application_create_navigation_window(), caja_application_get_spatial_window(), caja_debug_log_disable_domains(), caja_debug_log_enable_domains(), caja_mime_activate_files(), caja_window_slot_open_location_full(), caja_window_slot_set_content_view(), fm_directory_view_notify_selection_changed(), and fm_rename_file().
Function Documentation
caja_debug_log()
void caja_debug_log (gboolean is_milestone, const char * domain, const char * format, ...)
Definition at line 68 of file caja-debug-log.c.
References caja_debug_logv(), and NULL.
Referenced by caja_application_create_navigation_window(), caja_application_get_spatial_window(), caja_window_slot_open_location_full(), caja_window_slot_set_content_view(), and fm_rename_file().
caja_debug_log_clear()
void caja_debug_log_clear (void)
Definition at line 759 of file caja-debug-log.c.
References NULL.
caja_debug_log_disable_domains()
void caja_debug_log_disable_domains (const char ** domains, int n_domains)
Definition at line 416 of file caja-debug-log.c.
References CAJA_DEBUG_LOG_DOMAIN_USER, and NULL.
caja_debug_log_dump()
gboolean caja_debug_log_dump (const char * filename, GError ** error)
Definition at line 631 of file caja-debug-log.c.
References error, FALSE, NULL, and TRUE.
caja_debug_log_enable_domains()
void caja_debug_log_enable_domains (const char ** domains, int n_domains)
Definition at line 384 of file caja-debug-log.c.
References CAJA_DEBUG_LOG_DOMAIN_USER, and NULL.
Referenced by caja_debug_log_load_configuration().
caja_debug_log_get_max_lines()
int caja_debug_log_get_max_lines (void)
Definition at line 747 of file caja-debug-log.c.
caja_debug_log_is_domain_enabled()
gboolean caja_debug_log_is_domain_enabled (const char * domain)
Definition at line 449 of file caja-debug-log.c.
References NULL.
Referenced by caja_debug_log_with_file_list(), and fm_directory_view_notify_selection_changed().
caja_debug_log_load_configuration()
gboolean caja_debug_log_load_configuration (const char * filename, GError ** error)
Definition at line 334 of file caja-debug-log.c.
References caja_debug_log_enable_domains(), caja_debug_log_set_max_lines(), error, FALSE, KEY_FILE_DOMAINS_KEY, KEY_FILE_GROUP, KEY_FILE_MAX_LINES_KEY, NULL, and TRUE.
caja_debug_log_set_max_lines()
void caja_debug_log_set_max_lines (int num_lines)
Definition at line 692 of file caja-debug-log.c.
References idx, MIN, and NULL.
Referenced by caja_debug_log_load_configuration().
caja_debug_log_with_file_list()
void caja_debug_log_with_file_list (gboolean is_milestone, const char * domain, GList * files, const char * format, ...)
Definition at line 277 of file caja-debug-log.c.
References caja_debug_log_is_domain_enabled(), caja_debug_logv(), CAJA_FILE, caja_file_get_uri(), caja_file_is_gone(), MAX_URI_COUNT, and NULL.
Referenced by caja_mime_activate_files(), and fm_directory_view_notify_selection_changed().
caja_debug_log_with_uri_list()
void caja_debug_log_with_uri_list (gboolean is_milestone, const char * domain, const GList * uris, const char * format, ...)
Definition at line 266 of file caja-debug-log.c.
References caja_debug_logv().
caja_debug_logv()
void caja_debug_logv (gboolean is_milestone, const char * domain, const GList * uris, const char * format, va_list args)
Definition at line 153 of file caja-debug-log.c.
References MAX_URI_COUNT, and NULL.
Referenced by caja_debug_log(), caja_debug_log_with_file_list(), and caja_debug_log_with_uri_list().