MATE Desktop Environment: caja-location-bar.c File Reference
caja-location-bar.c File Reference
#include <config.h>
#include <stdio.h>
#include <string.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <eel/eel-accessibility.h>
#include <eel/eel-glib-extensions.h>
#include <eel/eel-gtk-macros.h>
#include <eel/eel-stock-dialogs.h>
#include <eel/eel-string.h>
#include <eel/eel-vfs-extensions.h>
#include <libcaja-private/caja-icon-dnd.h>
#include <libcaja-private/caja-clipboard.h>
#include "caja-location-bar.h"
#include "caja-location-entry.h"
#include "caja-window-private.h"
#include "caja-window.h"
#include "caja-navigation-window-pane.h"
Macros
#define CAJA_DND_URI_LIST_TYPE "text/uri-list"
#define CAJA_DND_TEXT_PLAIN_TYPE "text/plain"
#define LOCATION_LABEL _(untranslated_location_label)
#define GO_TO_LABEL _(untranslated_go_to_label)
Enumerations
enum { CAJA_DND_MC_DESKTOP_ICON , CAJA_DND_URI_LIST , CAJA_DND_TEXT_PLAIN , CAJA_DND_NTARGETS }
enum { CANCEL , LOCATION_CHANGED , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (CajaLocationBar, caja_location_bar, GTK_TYPE_BOX)
void caja_location_bar_activate (CajaLocationBar *bar)
GtkWidget * caja_location_bar_new (CajaNavigationWindowPane *pane)
void caja_location_bar_set_location (CajaLocationBar *bar, const char *location)
void caja_location_bar_set_active (CajaLocationBar *location_bar, gboolean is_active)
CajaEntry * caja_location_bar_get_entry (CajaLocationBar *location_bar)
Macro Definition Documentation
CAJA_DND_TEXT_PLAIN_TYPE
#define CAJA_DND_TEXT_PLAIN_TYPE "text/plain"
Definition at line 58 of file caja-location-bar.c.
CAJA_DND_URI_LIST_TYPE
#define CAJA_DND_URI_LIST_TYPE "text/uri-list"
Definition at line 57 of file caja-location-bar.c.
GO_TO_LABEL
#define GO_TO_LABEL _(untranslated_go_to_label)
Definition at line 63 of file caja-location-bar.c.
LOCATION_LABEL
#define LOCATION_LABEL _(untranslated_location_label)
Definition at line 62 of file caja-location-bar.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CAJA_DND_MC_DESKTOP_ICON
CAJA_DND_URI_LIST
CAJA_DND_TEXT_PLAIN
CAJA_DND_NTARGETS
Definition at line 75 of file caja-location-bar.c.
anonymous enum
anonymous enum
Enumerator
CANCEL
LOCATION_CHANGED
LAST_SIGNAL
Definition at line 83 of file caja-location-bar.c.
Function Documentation
caja_location_bar_activate()
void caja_location_bar_activate (CajaLocationBar * bar)
Definition at line 406 of file caja-location-bar.c.
References caja_entry_select_all(), and CajaLocationBar::details.
Referenced by caja_navigation_window_pane_show_navigation_bar_temporarily().
caja_location_bar_get_entry()
CajaEntry * caja_location_bar_get_entry (CajaLocationBar * location_bar)
Definition at line 657 of file caja-location-bar.c.
References CajaLocationBar::details.
Referenced by caja_navigation_window_pane_setup().
caja_location_bar_new()
GtkWidget * caja_location_bar_new (CajaNavigationWindowPane * pane)
Definition at line 541 of file caja-location-bar.c.
References caja_clipboard_set_up_editable(), CAJA_LOCATION_BAR, CAJA_TYPE_LOCATION_BAR, CAJA_WINDOW, caja_window_get_ui_manager(), CAJA_WINDOW_PANE, CajaLocationBar::details, NULL, and TRUE.
Referenced by caja_navigation_window_pane_setup().
caja_location_bar_set_active()
void caja_location_bar_set_active (CajaLocationBar * location_bar, gboolean is_active)
Definition at line 618 of file caja-location-bar.c.
References CajaLocationBar::details, and NULL.
Referenced by G_DEFINE_TYPE().
caja_location_bar_set_location()
void caja_location_bar_set_location (CajaLocationBar * bar, const char * location)
Definition at line 559 of file caja-location-bar.c.
References CAJA_LOCATION_ENTRY, caja_location_entry_set_special_text(), caja_location_entry_update_current_location(), CajaLocationBar::details, eel_uri_is_search(), and NULL.
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (CajaLocationBar , caja_location_bar , GTK_TYPE_BOX)
References CAJA_TYPE_WINDOW.