MATE Desktop Environment: caja-customization-data.c File Reference
caja-customization-data.c File Reference
#include <config.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <glib.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <libxml/parser.h>
#include <stdlib.h>
#include <string.h>
#include <eel/eel-gdk-extensions.h>
#include <eel/eel-gdk-pixbuf-extensions.h>
#include <eel/eel-gtk-extensions.h>
#include <eel/eel-string.h>
#include <eel/eel-vfs-extensions.h>
#include <eel/eel-xml-extensions.h>
#include "caja-customization-data.h"
#include "caja-file-utilities.h"
Enumerations
enum CustomizationReadingMode { READ_PUBLIC_CUSTOMIZATIONS , READ_PRIVATE_CUSTOMIZATIONS }
Functions
CajaCustomizationData * caja_customization_data_new (const char *customization_name, gboolean show_public_customizations, int maximum_icon_height, int maximum_icon_width)
gboolean caja_customization_data_get_next_element_for_display (CajaCustomizationData *data, char **emblem_name, GdkPixbuf **pixbuf_out, char **label_out)
gboolean caja_customization_data_private_data_was_displayed (CajaCustomizationData *data)
void caja_customization_data_destroy (CajaCustomizationData *data)
GdkPixbuf * caja_customization_make_pattern_chit (GdkPixbuf *pattern_tile, GdkPixbuf *frame, gboolean dragging, gboolean is_reset)
Enumeration Type Documentation
CustomizationReadingMode
enum CustomizationReadingMode
Enumerator
READ_PUBLIC_CUSTOMIZATIONS
READ_PRIVATE_CUSTOMIZATIONS
Definition at line 48 of file caja-customization-data.c.
Function Documentation
caja_customization_data_destroy()
void caja_customization_data_destroy (CajaCustomizationData * data)
Definition at line 298 of file caja-customization-data.c.
References data, and NULL.
caja_customization_data_get_next_element_for_display()
gboolean caja_customization_data_get_next_element_for_display (CajaCustomizationData * data, char ** emblem_name, GdkPixbuf ** pixbuf_out, char ** label_out)
Definition at line 194 of file caja-customization-data.c.
References caja_customization_data_get_next_element_for_display(), caja_customization_make_pattern_chit(), data, eel_gdk_pixbuf_scale_down_to_fit(), eel_istr_has_prefix(), FALSE, NULL, READ_PRIVATE_CUSTOMIZATIONS, READ_PUBLIC_CUSTOMIZATIONS, RESET_IMAGE_NAME, and TRUE.
Referenced by caja_customization_data_get_next_element_for_display(), and main().
caja_customization_data_new()
CajaCustomizationData * caja_customization_data_new (const char * customization_name, gboolean show_public_customizations, int maximum_icon_height, int maximum_icon_width)
Definition at line 118 of file caja-customization-data.c.
References caja_pixmap_file(), data, FALSE, NULL, READ_PRIVATE_CUSTOMIZATIONS, READ_PUBLIC_CUSTOMIZATIONS, and TRUE.
Referenced by main().
caja_customization_data_private_data_was_displayed()
gboolean caja_customization_data_private_data_was_displayed (CajaCustomizationData * data)
Definition at line 292 of file caja-customization-data.c.
References data.
caja_customization_make_pattern_chit()
GdkPixbuf * caja_customization_make_pattern_chit (GdkPixbuf * pattern_tile, GdkPixbuf * frame, gboolean dragging, gboolean is_reset)
Definition at line 379 of file caja-customization-data.c.
References NULL, and TRUE.
Referenced by caja_customization_data_get_next_element_for_display().