MATE Desktop Environment: caja-directory.h File Reference
caja-directory.h File Reference
#include <gtk/gtk.h>
#include <gio/gio.h>
#include "caja-file-attributes.h"
Classes
struct CajaDirectory
struct CajaDirectoryClass
Macros
#define CAJA_TYPE_DIRECTORY caja_directory_get_type()
#define CAJA_DIRECTORY(obj)
#define CAJA_DIRECTORY_CLASS(klass)
#define CAJA_IS_DIRECTORY(obj)
#define CAJA_IS_DIRECTORY_CLASS(klass)
#define CAJA_DIRECTORY_GET_CLASS(obj)
#define CAJA_FILE_DEFINED
Typedefs
typedef struct _CajaDirectoryPrivate CajaDirectoryPrivate
typedef void(* CajaDirectoryCallback) (CajaDirectory *directory, GList *files, gpointer callback_data)
Functions
GType caja_directory_get_type (void)
CajaDirectory * caja_directory_get (GFile *location)
CajaDirectory * caja_directory_get_by_uri (const char *uri)
CajaDirectory * caja_directory_get_for_file (CajaFile *file)
CajaDirectory * caja_directory_ref (CajaDirectory *directory)
void caja_directory_unref (CajaDirectory *directory)
char * caja_directory_get_uri (CajaDirectory *directory)
GFile * caja_directory_get_location (CajaDirectory *directory)
gboolean caja_directory_contains_file (CajaDirectory *directory, CajaFile *file)
CajaFile * caja_directory_get_corresponding_file (CajaDirectory *directory)
void caja_directory_call_when_ready (CajaDirectory *directory, CajaFileAttributes file_attributes, gboolean wait_for_all_files, CajaDirectoryCallback callback, gpointer callback_data)
void caja_directory_cancel_callback (CajaDirectory *directory, CajaDirectoryCallback callback, gpointer callback_data)
void caja_directory_file_monitor_add (CajaDirectory *directory, gconstpointer client, gboolean monitor_hidden_files, CajaFileAttributes attributes, CajaDirectoryCallback initial_files_callback, gpointer callback_data)
void caja_directory_file_monitor_remove (CajaDirectory *directory, gconstpointer client)
void caja_directory_force_reload (CajaDirectory *directory)
GList * caja_directory_get_file_list (CajaDirectory *directory)
GList * caja_directory_match_pattern (CajaDirectory *directory, const char *glob)
gboolean caja_directory_are_all_files_seen (CajaDirectory *directory)
gboolean caja_directory_is_local (CajaDirectory *directory)
gboolean caja_directory_is_in_trash (CajaDirectory *directory)
gboolean caja_directory_is_not_empty (CajaDirectory *directory)
GList * caja_directory_list_ref (GList *directory_list)
void caja_directory_list_unref (GList *directory_list)
void caja_directory_list_free (GList *directory_list)
GList * caja_directory_list_copy (GList *directory_list)
GList * caja_directory_list_sort_by_uri (GList *directory_list)
gboolean caja_directory_is_desktop_directory (CajaDirectory *directory)
gboolean caja_directory_is_editable (CajaDirectory *directory)
Macro Definition Documentation
CAJA_DIRECTORY
#define CAJA_DIRECTORY (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_DIRECTORY, CajaDirectory))
Definition at line 48 of file caja-directory.h.
Referenced by caja_search_directory_set_query(), and emit_change_signals_for_all_files_in_all_directories().
CAJA_DIRECTORY_CLASS
#define CAJA_DIRECTORY_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_DIRECTORY, CajaDirectoryClass))
Definition at line 50 of file caja-directory.h.
CAJA_DIRECTORY_GET_CLASS
#define CAJA_DIRECTORY_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_DIRECTORY, CajaDirectoryClass))
Definition at line 56 of file caja-directory.h.
Referenced by caja_directory_are_all_files_seen(), caja_directory_call_when_ready(), caja_directory_cancel_callback(), caja_directory_contains_file(), caja_directory_file_monitor_add(), caja_directory_file_monitor_remove(), caja_directory_force_reload(), caja_directory_get_file_list(), caja_directory_get_name_for_self_as_new_file(), caja_directory_is_editable(), and caja_directory_is_not_empty().
CAJA_FILE_DEFINED
#define CAJA_FILE_DEFINED
Definition at line 61 of file caja-directory.h.
CAJA_IS_DIRECTORY
#define CAJA_IS_DIRECTORY (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_DIRECTORY))
Definition at line 52 of file caja-directory.h.
Referenced by caja_directory_add_file(), caja_directory_add_file_monitors(), caja_directory_are_all_files_seen(), caja_directory_call_when_ready(), caja_directory_call_when_ready_internal(), caja_directory_cancel_callback(), caja_directory_cancel_callback_internal(), caja_directory_check_if_ready_internal(), caja_directory_contains_file(), caja_directory_file_monitor_add(), caja_directory_file_monitor_remove(), caja_directory_find_file_by_name(), caja_directory_force_reload(), caja_directory_get_location(), caja_directory_get_name_for_self_as_new_file(), caja_directory_get_uri(), caja_directory_is_in_trash(), caja_directory_is_local(), caja_directory_is_not_empty(), caja_directory_monitor_add_internal(), caja_directory_monitor_remove_internal(), caja_directory_ref(), caja_directory_remove_file(), caja_directory_remove_file_monitors(), caja_directory_unref(), caja_file_new_from_info(), and caja_file_update_name_and_directory().
CAJA_IS_DIRECTORY_CLASS
#define CAJA_IS_DIRECTORY_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_DIRECTORY))
Definition at line 54 of file caja-directory.h.
CAJA_TYPE_DIRECTORY
#define CAJA_TYPE_DIRECTORY caja_directory_get_type()
Definition at line 47 of file caja-directory.h.
Referenced by EEL_CLASS_BOILERPLATE(), G_DEFINE_TYPE(), and G_DEFINE_TYPE().
Typedef Documentation
CajaDirectoryCallback
typedef void(* CajaDirectoryCallback) (CajaDirectory *directory, GList *files, gpointer callback_data)
Definition at line 73 of file caja-directory.h.
CajaDirectoryPrivate
typedef struct _CajaDirectoryPrivate CajaDirectoryPrivate
Definition at line 65 of file caja-directory.h.
Function Documentation
caja_directory_are_all_files_seen()
gboolean caja_directory_are_all_files_seen (CajaDirectory * directory)
Definition at line 512 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, CAJA_IS_DIRECTORY, FALSE, and NULL.
caja_directory_call_when_ready()
void caja_directory_call_when_ready (CajaDirectory * directory, CajaFileAttributes file_attributes, gboolean wait_for_all_files, CajaDirectoryCallback callback, gpointer callback_data)
Definition at line 1401 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, CAJA_IS_DIRECTORY, and NULL.
Referenced by caja_self_check_directory().
caja_directory_cancel_callback()
void caja_directory_cancel_callback (CajaDirectory * directory, CajaDirectoryCallback callback, gpointer callback_data)
Definition at line 1421 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, CAJA_IS_DIRECTORY, and NULL.
caja_directory_contains_file()
gboolean caja_directory_contains_file (CajaDirectory * directory, CajaFile * file)
Definition at line 1383 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, caja_file_is_gone(), CAJA_IS_DIRECTORY, CAJA_IS_FILE, FALSE, and NULL.
caja_directory_file_monitor_add()
void caja_directory_file_monitor_add (CajaDirectory * directory, gconstpointer client, gboolean monitor_hidden_files, CajaFileAttributes attributes, CajaDirectoryCallback initial_files_callback, gpointer callback_data)
Definition at line 1435 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, CAJA_IS_DIRECTORY, and NULL.
Referenced by caja_self_check_directory(), fm_directory_view_add_subdirectory(), and main().
caja_directory_file_monitor_remove()
void caja_directory_file_monitor_remove (CajaDirectory * directory, gconstpointer client)
Definition at line 1456 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, CAJA_IS_DIRECTORY, and NULL.
Referenced by caja_self_check_directory(), fm_directory_view_remove_subdirectory(), and fm_directory_view_stop().
caja_directory_force_reload()
void caja_directory_force_reload (CajaDirectory * directory)
Definition at line 1469 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, CAJA_IS_DIRECTORY, and NULL.
caja_directory_get()
CajaDirectory * caja_directory_get (GFile * location)
Definition at line 302 of file caja-directory.c.
References caja_directory_get_internal(), NULL, and TRUE.
Referenced by caja_navigation_window_pane_hide_temporary_bars().
caja_directory_get_by_uri()
CajaDirectory * caja_directory_get_by_uri (const char * uri)
Definition at line 324 of file caja-directory.c.
References caja_directory_get_internal(), NULL, and TRUE.
Referenced by caja_desktop_icon_file_new(), caja_directory_get_for_file(), caja_self_check_directory(), and main().
caja_directory_get_corresponding_file()
CajaFile * caja_directory_get_corresponding_file (CajaDirectory * directory)
Definition at line 358 of file caja-directory.c.
References caja_directory_get_existing_corresponding_file(), caja_directory_get_uri(), caja_file_get_by_uri(), and NULL.
Referenced by caja_file_get_parent().
caja_directory_get_file_list()
GList * caja_directory_get_file_list (CajaDirectory * directory)
Definition at line 1508 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, and NULL.
Referenced by caja_directory_match_pattern(), and caja_directory_monitor_add_internal().
caja_directory_get_for_file()
CajaDirectory * caja_directory_get_for_file (CajaFile * file)
Definition at line 342 of file caja-directory.c.
References caja_directory_get_by_uri(), caja_file_get_uri(), CAJA_IS_FILE, and NULL.
Referenced by caja_file_get_volume_free_space(), fm_list_model_load_subdirectory(), and G_DEFINE_TYPE_WITH_CODE().
caja_directory_get_location()
GFile * caja_directory_get_location (CajaDirectory * directory)
Definition at line 445 of file caja-directory.c.
References CAJA_IS_DIRECTORY, CajaDirectory::details, _CajaDirectoryPrivate::location, and NULL.
Referenced by caja_file_get_parent_location(), and caja_file_get_uri_scheme().
caja_directory_get_type()
GType caja_directory_get_type (void)
caja_directory_get_uri()
char * caja_directory_get_uri (CajaDirectory * directory)
Definition at line 437 of file caja-directory.c.
References CAJA_IS_DIRECTORY, CajaDirectory::details, _CajaDirectoryPrivate::location, and NULL.
Referenced by caja_directory_get_corresponding_file(), caja_directory_get_existing_corresponding_file(), caja_file_get_parent_uri(), fm_directory_view_get_backing_uri(), and fm_directory_view_get_uri().
caja_directory_is_desktop_directory()
gboolean caja_directory_is_desktop_directory (CajaDirectory * directory)
Definition at line 1667 of file caja-directory.c.
References caja_is_desktop_directory(), CajaDirectory::details, FALSE, _CajaDirectoryPrivate::location, and NULL.
caja_directory_is_editable()
gboolean caja_directory_is_editable (CajaDirectory * directory)
Definition at line 1539 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, FALSE, and NULL.
Referenced by fm_directory_view_is_editable().
caja_directory_is_in_trash()
gboolean caja_directory_is_in_trash (CajaDirectory * directory)
Definition at line 499 of file caja-directory.c.
References CAJA_IS_DIRECTORY, CajaDirectory::details, FALSE, _CajaDirectoryPrivate::location, and NULL.
Referenced by caja_directory_is_local(), and caja_file_is_in_trash().
caja_directory_is_local()
gboolean caja_directory_is_local (CajaDirectory * directory)
Definition at line 485 of file caja-directory.c.
References caja_directory_is_in_trash(), CAJA_IS_DIRECTORY, CajaDirectory::details, FALSE, _CajaDirectoryPrivate::location, NULL, and TRUE.
Referenced by caja_file_is_local().
caja_directory_is_not_empty()
gboolean caja_directory_is_not_empty (CajaDirectory * directory)
Definition at line 1480 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, CAJA_IS_DIRECTORY, FALSE, and NULL.
Referenced by fm_list_model_subdirectory_done_loading().
caja_directory_list_copy()
GList * caja_directory_list_copy (GList * list)
caja_directory_list_copy
Copy the list of directories, making a new ref of each, @list: GList of directories.
Definition at line 1626 of file caja-directory.c.
References caja_directory_list_ref().
caja_directory_list_free()
void caja_directory_list_free (GList * list)
caja_directory_list_free
Free a list of directories after unrefing them. @list: GList of directories.
Definition at line 1613 of file caja-directory.c.
References caja_directory_list_unref().
caja_directory_list_ref()
GList * caja_directory_list_ref (GList * list)
caja_directory_list_ref
Ref all the directories in a list. @list: GList of directories.
Definition at line 1588 of file caja-directory.c.
References caja_directory_ref(), and NULL.
Referenced by caja_directory_list_copy().
caja_directory_list_sort_by_uri()
GList * caja_directory_list_sort_by_uri (GList * list)
caja_directory_list_sort_by_uri
Sort the list of directories by directory uri. @list: GList of directories.
Definition at line 1661 of file caja-directory.c.
caja_directory_list_unref()
void caja_directory_list_unref (GList * list)
caja_directory_list_unref
Unref all the directories in a list. @list: GList of directories.
Definition at line 1601 of file caja-directory.c.
References caja_directory_unref(), and NULL.
Referenced by caja_directory_list_free().
caja_directory_match_pattern()
GList * caja_directory_match_pattern (CajaDirectory * directory, const char * glob)
Definition at line 1550 of file caja-directory.c.
References caja_directory_get_file_list(), CAJA_FILE, caja_file_get_display_name(), caja_file_list_free(), caja_file_ref(), name, and NULL.
caja_directory_ref()
CajaDirectory * caja_directory_ref (CajaDirectory * directory)
Definition at line 126 of file caja-directory.c.
References CAJA_IS_DIRECTORY, and NULL.
Referenced by caja_desktop_directory_get_real_directory(), caja_directory_async_state_changed(), caja_directory_get_internal(), caja_directory_list_ref(), caja_file_new_from_info(), caja_file_update_name_and_directory(), fm_directory_view_add_subdirectory(), fm_directory_view_get_backing_uri(), and fm_list_model_load_subdirectory().
caja_directory_unref()
void caja_directory_unref (CajaDirectory * directory)
Definition at line 140 of file caja-directory.c.
References CAJA_IS_DIRECTORY, and NULL.
Referenced by caja_directory_async_state_changed(), caja_directory_list_unref(), caja_directory_notify_files_added(), caja_directory_notify_files_moved(), caja_directory_notify_files_removed(), caja_file_get_volume_free_space(), caja_file_update_name_and_directory(), caja_navigation_window_pane_hide_temporary_bars(), caja_self_check_directory(), emit_change_signals_for_all_files_in_all_directories(), fm_directory_view_get_backing_uri(), fm_directory_view_remove_subdirectory(), fm_list_model_load_subdirectory(), fm_list_model_unload_subdirectory(), and G_DEFINE_TYPE_WITH_CODE().