MATE Desktop Environment: caja-icon-container.h File Reference
caja-icon-container.h File Reference
#include <eel/eel-canvas.h>
#include "caja-icon-info.h"
Classes
struct CajaIconPosition
struct CajaIconContainer
struct CajaIconContainerClass
Macros
#define CAJA_TYPE_ICON_CONTAINER caja_icon_container_get_type()
#define CAJA_ICON_CONTAINER(obj)
#define CAJA_ICON_CONTAINER_CLASS(klass)
#define CAJA_IS_ICON_CONTAINER(obj)
#define CAJA_IS_ICON_CONTAINER_CLASS(klass)
#define CAJA_ICON_CONTAINER_GET_CLASS(obj)
#define CAJA_ICON_CONTAINER_ICON_DATA(pointer)
#define CAJA_ICON_CONTAINER_TYPESELECT_FLUSH_DELAY 1000000
#define CANVAS_WIDTH(container, allocation)
#define CANVAS_HEIGHT(container, allocation)
Typedefs
typedef void CajaIconData
typedef void(* CajaIconCallback) (CajaIconData *icon_data, gpointer callback_data)
typedef struct CajaIconContainerDetails CajaIconContainerDetails
Enumerations
enum CajaIconLayoutMode { CAJA_ICON_LAYOUT_L_R_T_B , CAJA_ICON_LAYOUT_R_L_T_B , CAJA_ICON_LAYOUT_T_B_L_R , CAJA_ICON_LAYOUT_T_B_R_L }
enum CajaIconLabelPosition { CAJA_ICON_LABEL_POSITION_UNDER , CAJA_ICON_LABEL_POSITION_BESIDE }
enum CajaDisplayGitBranch { CAJA_DISPLAY_GIT_BRANCH_DISABLED , CAJA_DISPLAY_GIT_BRANCH_ENABLED }
Functions
GType caja_icon_container_get_type (void)
GtkWidget * caja_icon_container_new (void)
void caja_icon_container_clear (CajaIconContainer *view)
gboolean caja_icon_container_add (CajaIconContainer *view, CajaIconData *data)
void caja_icon_container_layout_now (CajaIconContainer *container)
gboolean caja_icon_container_remove (CajaIconContainer *view, CajaIconData *data)
void caja_icon_container_for_each (CajaIconContainer *view, CajaIconCallback callback, gpointer callback_data)
void caja_icon_container_request_update (CajaIconContainer *view, CajaIconData *data)
void caja_icon_container_request_update_all (CajaIconContainer *container)
void caja_icon_container_reveal (CajaIconContainer *container, CajaIconData *data)
gboolean caja_icon_container_is_empty (CajaIconContainer *container)
CajaIconData * caja_icon_container_get_first_visible_icon (CajaIconContainer *container)
void caja_icon_container_scroll_to_icon (CajaIconContainer *container, CajaIconData *data)
void caja_icon_container_begin_loading (CajaIconContainer *container)
void caja_icon_container_end_loading (CajaIconContainer *container, gboolean all_icons_added)
gboolean caja_icon_container_is_auto_layout (CajaIconContainer *container)
void caja_icon_container_set_auto_layout (CajaIconContainer *container, gboolean auto_layout)
gboolean caja_icon_container_is_tighter_layout (CajaIconContainer *container)
void caja_icon_container_set_tighter_layout (CajaIconContainer *container, gboolean tighter_layout)
gboolean caja_icon_container_is_keep_aligned (CajaIconContainer *container)
void caja_icon_container_set_keep_aligned (CajaIconContainer *container, gboolean keep_aligned)
gboolean caja_icon_container_is_lock_icons_position (CajaIconContainer *container)
void caja_icon_container_set_lock_icons_position (CajaIconContainer *container, gboolean lock_icons_position)
void caja_icon_container_set_layout_mode (CajaIconContainer *container, CajaIconLayoutMode mode)
void caja_icon_container_set_label_position (CajaIconContainer *container, CajaIconLabelPosition pos)
void caja_display_git_branch_enable (CajaIconContainer *container, CajaDisplayGitBranch enabled)
void caja_icon_container_sort (CajaIconContainer *container)
void caja_icon_container_freeze_icon_positions (CajaIconContainer *container)
int caja_icon_container_get_max_layout_lines (CajaIconContainer *container)
int caja_icon_container_get_max_layout_lines_for_pango (CajaIconContainer *container)
void caja_icon_container_set_highlighted_for_clipboard (CajaIconContainer *container, GList *clipboard_icon_data)
void caja_icon_container_unselect_all (CajaIconContainer *view)
void caja_icon_container_select_all (CajaIconContainer *view)
GList * caja_icon_container_get_selection (CajaIconContainer *view)
void caja_icon_container_invert_selection (CajaIconContainer *view)
void caja_icon_container_set_selection (CajaIconContainer *view, GList *selection)
GArray * caja_icon_container_get_selected_icon_locations (CajaIconContainer *view)
gboolean caja_icon_container_has_stretch_handles (CajaIconContainer *container)
gboolean caja_icon_container_is_stretched (CajaIconContainer *container)
void caja_icon_container_show_stretch_handles (CajaIconContainer *container)
void caja_icon_container_unstretch (CajaIconContainer *container)
void caja_icon_container_start_renaming_selected_item (CajaIconContainer *container, gboolean select_all)
CajaZoomLevel caja_icon_container_get_zoom_level (CajaIconContainer *view)
void caja_icon_container_set_zoom_level (CajaIconContainer *view, int new_zoom_level)
void caja_icon_container_set_single_click_mode (CajaIconContainer *container, gboolean single_click_mode)
void caja_icon_container_enable_linger_selection (CajaIconContainer *view, gboolean enable)
gboolean caja_icon_container_get_is_fixed_size (CajaIconContainer *container)
void caja_icon_container_set_is_fixed_size (CajaIconContainer *container, gboolean is_fixed_size)
gboolean caja_icon_container_get_is_desktop (CajaIconContainer *container)
void caja_icon_container_set_is_desktop (CajaIconContainer *container, gboolean is_desktop)
void caja_icon_container_reset_scroll_region (CajaIconContainer *container)
void caja_icon_container_set_font (CajaIconContainer *container, const char *font)
void caja_icon_container_set_font_size_table (CajaIconContainer *container, const int font_size_table[CAJA_ZOOM_LEVEL_LARGEST+1])
void caja_icon_container_set_margins (CajaIconContainer *container, int left_margin, int right_margin, int top_margin, int bottom_margin)
void caja_icon_container_set_use_drop_shadows (CajaIconContainer *container, gboolean use_drop_shadows)
char * caja_icon_container_get_icon_description (CajaIconContainer *container, CajaIconData *data)
gboolean caja_icon_container_get_allow_moves (CajaIconContainer *container)
void caja_icon_container_set_allow_moves (CajaIconContainer *container, gboolean allow_moves)
void caja_icon_container_set_forced_icon_size (CajaIconContainer *container, int forced_icon_size)
void caja_icon_container_set_all_columns_same_width (CajaIconContainer *container, gboolean all_columns_same_width)
gboolean caja_icon_container_is_layout_rtl (CajaIconContainer *container)
gboolean caja_icon_container_is_layout_vertical (CajaIconContainer *container)
gboolean caja_icon_container_get_store_layout_timestamps (CajaIconContainer *container)
void caja_icon_container_set_store_layout_timestamps (CajaIconContainer *container, gboolean store_layout)
void caja_icon_container_widget_to_file_operation_position (CajaIconContainer *container, GdkPoint *position)
Macro Definition Documentation
CAJA_ICON_CONTAINER
#define CAJA_ICON_CONTAINER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_ICON_CONTAINER, CajaIconContainer))
Definition at line 34 of file caja-icon-container.h.
Referenced by caja_icon_canvas_item_get_drag_surface(), caja_icon_canvas_item_get_max_text_width(), caja_icon_canvas_item_update_bounds(), caja_icon_container_add(), and fm_icon_container_construct().
CAJA_ICON_CONTAINER_CLASS
#define CAJA_ICON_CONTAINER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_ICON_CONTAINER, CajaIconContainerClass))
Definition at line 36 of file caja-icon-container.h.
CAJA_ICON_CONTAINER_GET_CLASS
#define CAJA_ICON_CONTAINER_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_ICON_CONTAINER, CajaIconContainerClass))
Definition at line 42 of file caja-icon-container.h.
Referenced by caja_icon_container_get_icon_description().
CAJA_ICON_CONTAINER_ICON_DATA
#define CAJA_ICON_CONTAINER_ICON_DATA (pointer)
Value:
((CajaIconData *) (pointer))
Definition at line 45 of file caja-icon-container.h.
CAJA_ICON_CONTAINER_TYPESELECT_FLUSH_DELAY
#define CAJA_ICON_CONTAINER_TYPESELECT_FLUSH_DELAY 1000000
Definition at line 80 of file caja-icon-container.h.
CAJA_IS_ICON_CONTAINER
#define CAJA_IS_ICON_CONTAINER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_ICON_CONTAINER))
Definition at line 38 of file caja-icon-container.h.
Referenced by caja_display_git_branch_enable(), caja_icon_container_add(), caja_icon_container_clear(), caja_icon_container_emit_preview_signal(), caja_icon_container_for_each(), caja_icon_container_get_allow_moves(), caja_icon_container_get_is_desktop(), caja_icon_container_get_is_fixed_size(), caja_icon_container_get_selected_icon_locations(), caja_icon_container_get_selection(), caja_icon_container_invert_selection(), caja_icon_container_is_auto_layout(), caja_icon_container_is_layout_rtl(), caja_icon_container_is_layout_vertical(), caja_icon_container_is_tighter_layout(), caja_icon_container_remove(), caja_icon_container_request_update(), caja_icon_container_request_update_all(), caja_icon_container_reveal(), caja_icon_container_select_all(), caja_icon_container_select_list_unselect_others(), caja_icon_container_set_all_columns_same_width(), caja_icon_container_set_allow_moves(), caja_icon_container_set_auto_layout(), caja_icon_container_set_font(), caja_icon_container_set_font_size_table(), caja_icon_container_set_forced_icon_size(), caja_icon_container_set_highlighted_for_clipboard(), caja_icon_container_set_is_desktop(), caja_icon_container_set_is_fixed_size(), caja_icon_container_set_label_position(), caja_icon_container_set_layout_mode(), caja_icon_container_set_lock_icons_position(), caja_icon_container_set_margins(), caja_icon_container_set_selection(), caja_icon_container_set_single_click_mode(), caja_icon_container_set_tighter_layout(), caja_icon_dnd_begin_drag(), caja_icon_dnd_end_drag(), caja_icon_dnd_fini(), and caja_icon_dnd_init().
CAJA_IS_ICON_CONTAINER_CLASS
#define CAJA_IS_ICON_CONTAINER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_ICON_CONTAINER))
Definition at line 40 of file caja-icon-container.h.
CAJA_TYPE_ICON_CONTAINER
#define CAJA_TYPE_ICON_CONTAINER caja_icon_container_get_type()
Definition at line 33 of file caja-icon-container.h.
Referenced by caja_icon_container_new(), and G_DEFINE_TYPE().
CANVAS_HEIGHT
#define CANVAS_HEIGHT (container, allocation)
Value:
((allocation.height \
- container->details->top_margin \
- container->details->bottom_margin) \
/ EEL_CANVAS (container)->pixels_per_unit)
Definition at line 374 of file caja-icon-container.h.
CANVAS_WIDTH
#define CANVAS_WIDTH (container, allocation)
Value:
((allocation.width    \
- container->details->left_margin \
- container->details->right_margin) \
/  EEL_CANVAS (container)->pixels_per_unit)
Definition at line 369 of file caja-icon-container.h.
Typedef Documentation
CajaIconCallback
typedef void(* CajaIconCallback) (CajaIconData *icon_data, gpointer callback_data)
Definition at line 50 of file caja-icon-container.h.
CajaIconContainerDetails
typedef struct CajaIconContainerDetails CajaIconContainerDetails
Definition at line 82 of file caja-icon-container.h.
CajaIconData
typedef void CajaIconData
Definition at line 48 of file caja-icon-container.h.
Enumeration Type Documentation
CajaDisplayGitBranch
enum CajaDisplayGitBranch
Enumerator
CAJA_DISPLAY_GIT_BRANCH_DISABLED
CAJA_DISPLAY_GIT_BRANCH_ENABLED
Definition at line 74 of file caja-icon-container.h.
CajaIconLabelPosition
enum CajaIconLabelPosition
Enumerator
CAJA_ICON_LABEL_POSITION_UNDER
CAJA_ICON_LABEL_POSITION_BESIDE
Definition at line 68 of file caja-icon-container.h.
CajaIconLayoutMode
enum CajaIconLayoutMode
Enumerator
CAJA_ICON_LAYOUT_L_R_T_B
CAJA_ICON_LAYOUT_R_L_T_B
CAJA_ICON_LAYOUT_T_B_L_R
CAJA_ICON_LAYOUT_T_B_R_L
Definition at line 60 of file caja-icon-container.h.
Function Documentation
caja_display_git_branch_enable()
void caja_display_git_branch_enable (CajaIconContainer * container, CajaDisplayGitBranch enabled)
Definition at line 8827 of file caja-icon-container.c.
References caja_icon_container_request_update_all(), CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::display_git_branch.
caja_icon_container_add()
gboolean caja_icon_container_add (CajaIconContainer * container, CajaIconData * data)
caja_icon_container_add: @container: A CajaIconContainer @data: Icon data.
Add icon to represent @data to container. Returns FALSE if there was already such an icon.
Definition at line 7879 of file caja-icon-container.c.
References band, CAJA_ICON_CANVAS_ITEM, caja_icon_canvas_item_get_type(), CAJA_ICON_CONTAINER, CAJA_IS_ICON_CONTAINER, data, CajaIconContainer::details, EEL_CANVAS, EEL_CANVAS_GROUP, EEL_CANVAS_ITEM, eel_canvas_item_new(), eel_canvas_item_send_behind(), FALSE, CajaIconContainerDetails::icon_set, ICON_UNPOSITIONED_VALUE, CajaIconContainerDetails::icons, item, CajaIconContainerDetails::new_icons, NULL, and TRUE.
caja_icon_container_begin_loading()
void caja_icon_container_begin_loading (CajaIconContainer * container)
Definition at line 10169 of file caja-icon-container.c.
References caja_icon_container_get_store_layout_timestamps(), CajaIconContainer::details, GET_STORED_LAYOUT_TIMESTAMP, CajaIconContainerDetails::layout_timestamp, NULL, and UNDEFINED_TIME.
caja_icon_container_clear()
void caja_icon_container_clear (CajaIconContainer * view)
Definition at line 7034 of file caja-icon-container.c.
References caja_icon_container_update_scroll_region(), CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, CajaIconContainerDetails::drop_target, FALSE, CajaIconContainerDetails::icon_set, CajaIconContainerDetails::icons, CajaIconContainerDetails::layout_timestamp, CajaIconContainerDetails::new_icons, NULL, CajaIconContainerDetails::store_layout_timestamps_when_finishing_new_icons, CajaIconContainerDetails::stretch_icon, TRUE, and UNDEFINED_TIME.
caja_icon_container_enable_linger_selection()
void caja_icon_container_enable_linger_selection (CajaIconContainer * view, gboolean enable)
References CAJA_ZOOM_LEVEL_LARGEST, and data.
caja_icon_container_end_loading()
void caja_icon_container_end_loading (CajaIconContainer * container, gboolean all_icons_added)
Definition at line 10205 of file caja-icon-container.c.
References caja_icon_container_get_store_layout_timestamps(), CajaIconContainer::details, CajaIconContainerDetails::new_icons, NULL, CajaIconContainerDetails::store_layout_timestamps_when_finishing_new_icons, and TRUE.
caja_icon_container_for_each()
void caja_icon_container_for_each (CajaIconContainer * view, CajaIconCallback callback, gpointer callback_data)
Definition at line 7246 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::icons.
caja_icon_container_freeze_icon_positions()
void caja_icon_container_freeze_icon_positions (CajaIconContainer * container)
Definition at line 8848 of file caja-icon-container.c.
References CajaIconContainerDetails::auto_layout, CajaIconContainer::details, FALSE, ICON_POSITION_CHANGED, CajaIconContainerDetails::icons, LAYOUT_CHANGED, NULL, CajaIconPosition::scale, CajaIconPosition::x, and CajaIconPosition::y.
Referenced by caja_icon_container_set_auto_layout().
caja_icon_container_get_allow_moves()
gboolean caja_icon_container_get_allow_moves (CajaIconContainer * container)
Definition at line 9412 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, CajaIconContainerDetails::drag_allow_moves, and FALSE.
caja_icon_container_get_first_visible_icon()
CajaIconData * caja_icon_container_get_first_visible_icon (CajaIconContainer * container)
Definition at line 7089 of file caja-icon-container.c.
References caja_icon_container_is_layout_rtl(), caja_icon_container_is_layout_vertical(), CajaIcon::data, CajaIconContainer::details, EEL_CANVAS, eel_canvas_c2w(), EEL_CANVAS_ITEM, eel_canvas_item_get_bounds(), FALSE, ICON_PAD_LEFT, ICON_PAD_TOP, CajaIconContainerDetails::icons, NULL, and TRUE.
caja_icon_container_get_icon_description()
char * caja_icon_container_get_icon_description (CajaIconContainer * container, CajaIconData * data)
caja_icon_container_get_icon_description @container: An icon container widget. @data: Icon data
Gets the description for the icon. This function may return NULL.
Definition at line 9394 of file caja-icon-container.c.
References CAJA_ICON_CONTAINER_GET_CLASS, data, CajaIconContainerClass::get_icon_description, and NULL.
caja_icon_container_get_is_desktop()
gboolean caja_icon_container_get_is_desktop (CajaIconContainer * container)
Definition at line 9282 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, and CajaIconContainerDetails::is_desktop.
Referenced by caja_icon_container_get_max_layout_lines(), caja_icon_container_get_max_layout_lines_for_pango(), and caja_icon_dnd_init().
caja_icon_container_get_is_fixed_size()
gboolean caja_icon_container_get_is_fixed_size (CajaIconContainer * container)
Definition at line 9264 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, and CajaIconContainerDetails::is_fixed_size.
Referenced by caja_icon_container_update_scroll_region().
caja_icon_container_get_max_layout_lines()
int caja_icon_container_get_max_layout_lines (CajaIconContainer * container)
Definition at line 10147 of file caja-icon-container.c.
References caja_icon_container_get_is_desktop(), CajaIconContainer::details, and CajaIconContainerDetails::zoom_level.
caja_icon_container_get_max_layout_lines_for_pango()
int caja_icon_container_get_max_layout_lines_for_pango (CajaIconContainer * container)
Definition at line 10125 of file caja-icon-container.c.
References caja_icon_container_get_is_desktop(), CajaIconContainer::details, and CajaIconContainerDetails::zoom_level.
caja_icon_container_get_selected_icon_locations()
GArray * caja_icon_container_get_selected_icon_locations (CajaIconContainer * container)
caja_icon_container_get_selected_icon_locations: @container: An icon container widget.
Returns an array of GdkPoints of locations of the selected icons.
Definition at line 8213 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, and NULL.
caja_icon_container_get_selection()
GList * caja_icon_container_get_selection (CajaIconContainer * container)
caja_icon_container_get_selection: @container: An icon container.
Get a list of the icons currently selected in @container.
Return value: A GList of the programmer-specified data associated to each selected icon, or NULL if no icon is selected. The caller is expected to free the list when it is not needed anymore.
Definition at line 8115 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIcon::data, CajaIconContainer::details, CajaIconContainerDetails::icons, and NULL.
caja_icon_container_get_store_layout_timestamps()
gboolean caja_icon_container_get_store_layout_timestamps (CajaIconContainer * container)
Definition at line 10223 of file caja-icon-container.c.
References CajaIconContainer::details, and CajaIconContainerDetails::store_layout_timestamps.
Referenced by caja_icon_container_begin_loading(), and caja_icon_container_end_loading().
caja_icon_container_get_type()
GType caja_icon_container_get_type (void)
References data.
caja_icon_container_get_zoom_level()
CajaZoomLevel caja_icon_container_get_zoom_level (CajaIconContainer * view)
Definition at line 8011 of file caja-icon-container.c.
References CajaIconContainer::details, and CajaIconContainerDetails::zoom_level.
caja_icon_container_has_stretch_handles()
gboolean caja_icon_container_has_stretch_handles (CajaIconContainer * container)
caja_icon_container_has_stretch_handles @container: An icon container widget.
Returns true if the first selected item has stretch handles.
Definition at line 8518 of file caja-icon-container.c.
References CajaIconContainer::details, FALSE, NULL, and CajaIconContainerDetails::stretch_icon.
caja_icon_container_invert_selection()
void caja_icon_container_invert_selection (CajaIconContainer * container)
caja_icon_container_invert_selection: @container: An icon container.
Inverts the selection in @container.
Definition at line 8166 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIcon::data, CajaIconContainer::details, CajaIconContainerDetails::icons, NULL, and SELECTION_CHANGED.
caja_icon_container_is_auto_layout()
gboolean caja_icon_container_is_auto_layout (CajaIconContainer * container)
Definition at line 8894 of file caja-icon-container.c.
References CajaIconContainerDetails::auto_layout, CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and FALSE.
Referenced by caja_icon_container_scroll_to_icon(), and caja_icon_container_update_scroll_region().
caja_icon_container_is_empty()
gboolean caja_icon_container_is_empty (CajaIconContainer * container)
Definition at line 7083 of file caja-icon-container.c.
References CajaIconContainer::details, CajaIconContainerDetails::icons, and NULL.
Referenced by caja_icon_container_update_scroll_region().
caja_icon_container_is_keep_aligned()
gboolean caja_icon_container_is_keep_aligned (CajaIconContainer * container)
Definition at line 8723 of file caja-icon-container.c.
References CajaIconContainer::details, and CajaIconContainerDetails::keep_aligned.
caja_icon_container_is_layout_rtl()
gboolean caja_icon_container_is_layout_rtl (CajaIconContainer * container)
Definition at line 10107 of file caja-icon-container.c.
References CAJA_ICON_LAYOUT_R_L_T_B, CAJA_ICON_LAYOUT_T_B_R_L, CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::layout_mode.
Referenced by caja_icon_canvas_item_get_drag_surface(), caja_icon_canvas_item_update_bounds(), caja_icon_container_get_first_visible_icon(), caja_icon_container_move_icon(), caja_icon_container_scroll_to_icon(), and caja_icon_container_update_scroll_region().
caja_icon_container_is_layout_vertical()
gboolean caja_icon_container_is_layout_vertical (CajaIconContainer * container)
Definition at line 10116 of file caja-icon-container.c.
References CAJA_ICON_LAYOUT_T_B_L_R, CAJA_ICON_LAYOUT_T_B_R_L, CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, and CajaIconContainerDetails::layout_mode.
Referenced by caja_icon_container_get_first_visible_icon(), caja_icon_container_scroll_to_icon(), caja_icon_container_start_renaming_selected_item(), and caja_icon_container_update_scroll_region().
caja_icon_container_is_lock_icons_position()
gboolean caja_icon_container_is_lock_icons_position (CajaIconContainer * container)
Definition at line 8729 of file caja-icon-container.c.
References CajaIconContainer::details, and CajaIconContainerDetails::lock_icons_position.
caja_icon_container_is_stretched()
gboolean caja_icon_container_is_stretched (CajaIconContainer * container)
caja_icon_container_is_stretched @container: An icon container widget.
Returns true if the any selected item is stretched to a size other than 1.0.
Definition at line 8538 of file caja-icon-container.c.
References CajaIconContainer::details, FALSE, CajaIconContainerDetails::icons, NULL, and TRUE.
caja_icon_container_is_tighter_layout()
gboolean caja_icon_container_is_tighter_layout (CajaIconContainer * container)
Definition at line 8902 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, and CajaIconContainerDetails::tighter_layout.
Referenced by caja_icon_canvas_item_get_max_text_width().
caja_icon_container_layout_now()
void caja_icon_container_layout_now (CajaIconContainer * container)
Definition at line 7936 of file caja-icon-container.c.
References CajaIconContainer::details, and CajaIconContainerDetails::idle_id.
Referenced by caja_icon_container_scroll_to_icon().
caja_icon_container_new()
GtkWidget * caja_icon_container_new (void)
Definition at line 7027 of file caja-icon-container.c.
References CAJA_TYPE_ICON_CONTAINER, and NULL.
caja_icon_container_remove()
gboolean caja_icon_container_remove (CajaIconContainer * container, CajaIconData * data)
caja_icon_container_remove: @container: A CajaIconContainer. @data: Icon data.
Remove the icon with this data.
Definition at line 7958 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, data, CajaIconContainer::details, FALSE, ICON_REMOVED, CajaIconContainerDetails::icon_set, NULL, and TRUE.
caja_icon_container_request_update()
void caja_icon_container_request_update (CajaIconContainer * container, CajaIconData * data)
caja_icon_container_request_update: @container: A CajaIconContainer. @data: Icon data.
Update the icon with this data.
Definition at line 7991 of file caja-icon-container.c.
References caja_icon_container_update_icon(), CAJA_IS_ICON_CONTAINER, data, CajaIconContainer::details, CajaIconContainerDetails::icon_set, and NULL.
caja_icon_container_request_update_all()
void caja_icon_container_request_update_all (CajaIconContainer * container)
caja_icon_container_request_update_all: For each icon, synchronizes the displayed information (image, text) with the information from the model.
@container: An icon container.
Definition at line 8061 of file caja-icon-container.c.
References CajaIconContainerDetails::auto_layout, caja_icon_container_update_icon(), CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, CajaIconContainerDetails::icons, CajaIconContainerDetails::is_loading, NULL, and TRUE.
Referenced by caja_display_git_branch_enable(), caja_icon_container_set_all_columns_same_width(), caja_icon_container_set_font(), caja_icon_container_set_font_size_table(), caja_icon_container_set_forced_icon_size(), caja_icon_container_set_label_position(), caja_icon_container_set_tighter_layout(), and caja_icon_container_set_zoom_level().
caja_icon_container_reset_scroll_region()
void caja_icon_container_reset_scroll_region (CajaIconContainer * container)
Definition at line 1065 of file caja-icon-container.c.
References CajaIconContainer::details, CajaIconContainerDetails::reset_scroll_region_trigger, and TRUE.
caja_icon_container_reveal()
void caja_icon_container_reveal (CajaIconContainer * container, CajaIconData * data)
caja_icon_container_reveal: Change scroll position as necessary to reveal the specified item.
Definition at line 8089 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, data, CajaIconContainer::details, CajaIconContainerDetails::icon_set, and NULL.
caja_icon_container_scroll_to_icon()
void caja_icon_container_scroll_to_icon (CajaIconContainer * container, CajaIconData * data)
Definition at line 7181 of file caja-icon-container.c.
References caja_icon_container_is_auto_layout(), caja_icon_container_is_layout_rtl(), caja_icon_container_is_layout_vertical(), caja_icon_container_layout_now(), data, CajaIconContainer::details, EEL_CANVAS_ITEM, CajaIconContainerDetails::icons, NULL, TRUE, EelIRect::x0, EelIRect::x1, and EelIRect::y0.
caja_icon_container_select_all()
void caja_icon_container_select_all (CajaIconContainer * container)
caja_icon_container_select_all: @container: An icon container widget.
Select all the icons in @container at once.
Definition at line 8234 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, CajaIconContainerDetails::icons, NULL, SELECTION_CHANGED, and TRUE.
caja_icon_container_set_all_columns_same_width()
void caja_icon_container_set_all_columns_same_width (CajaIconContainer * container, gboolean all_columns_same_width)
Definition at line 9444 of file caja-icon-container.c.
References CajaIconContainerDetails::all_columns_same_width, caja_icon_container_request_update_all(), CAJA_IS_ICON_CONTAINER, and CajaIconContainer::details.
caja_icon_container_set_allow_moves()
void caja_icon_container_set_allow_moves (CajaIconContainer * container, gboolean allow_moves)
Definition at line 9420 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::drag_allow_moves.
caja_icon_container_set_auto_layout()
void caja_icon_container_set_auto_layout (CajaIconContainer * container, gboolean auto_layout)
Definition at line 8665 of file caja-icon-container.c.
References CajaIconContainerDetails::auto_layout, caja_icon_container_freeze_icon_positions(), CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, LAYOUT_CHANGED, and TRUE.
caja_icon_container_set_font()
void caja_icon_container_set_font (CajaIconContainer * container, const char * font)
Definition at line 9341 of file caja-icon-container.c.
References caja_icon_container_request_update_all(), CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::font.
caja_icon_container_set_font_size_table()
void caja_icon_container_set_font_size_table (CajaIconContainer * container, const int font_size_table[CAJA_ZOOM_LEVEL_LARGEST+1])
Definition at line 9360 of file caja-icon-container.c.
References caja_icon_container_request_update_all(), CAJA_IS_ICON_CONTAINER, CAJA_ZOOM_LEVEL_LARGEST, CajaIconContainer::details, CajaIconContainerDetails::font_size_table, NULL, and CajaIconContainerDetails::zoom_level.
caja_icon_container_set_forced_icon_size()
void caja_icon_container_set_forced_icon_size (CajaIconContainer * container, int forced_icon_size)
Definition at line 9429 of file caja-icon-container.c.
References caja_icon_container_request_update_all(), CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::forced_icon_size.
caja_icon_container_set_highlighted_for_clipboard()
void caja_icon_container_set_highlighted_for_clipboard (CajaIconContainer * container, GList * clipboard_icon_data)
caja_icon_container_set_highlighted_for_clipboard @container: An icon container widget. @data: Icon Data associated with all icons that should be highlighted. Others will be unhighlighted.
Definition at line 9465 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, EEL_CANVAS_ITEM, eel_canvas_item_set(), CajaIconContainerDetails::icons, and NULL.
caja_icon_container_set_is_desktop()
void caja_icon_container_set_is_desktop (CajaIconContainer * container, gboolean is_desktop)
Definition at line 9290 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::is_desktop.
caja_icon_container_set_is_fixed_size()
void caja_icon_container_set_is_fixed_size (CajaIconContainer * container, gboolean is_fixed_size)
Definition at line 9273 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::is_fixed_size.
caja_icon_container_set_keep_aligned()
void caja_icon_container_set_keep_aligned (CajaIconContainer * container, gboolean keep_aligned)
Definition at line 8768 of file caja-icon-container.c.
References CajaIconContainerDetails::auto_layout, CajaIconContainer::details, and CajaIconContainerDetails::keep_aligned.
caja_icon_container_set_label_position()
void caja_icon_container_set_label_position (CajaIconContainer * container, CajaIconLabelPosition pos)
Definition at line 8810 of file caja-icon-container.c.
References caja_icon_container_request_update_all(), CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::label_position.
caja_icon_container_set_layout_mode()
void caja_icon_container_set_layout_mode (CajaIconContainer * container, CajaIconLayoutMode mode)
Definition at line 8796 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, LAYOUT_CHANGED, and CajaIconContainerDetails::layout_mode.
caja_icon_container_set_lock_icons_position()
void caja_icon_container_set_lock_icons_position (CajaIconContainer * container, gboolean lock_icons_position)
Definition at line 8787 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::lock_icons_position.
caja_icon_container_set_margins()
void caja_icon_container_set_margins (CajaIconContainer * container, int left_margin, int right_margin, int top_margin, int bottom_margin)
Definition at line 9306 of file caja-icon-container.c.
References CajaIconContainerDetails::bottom_margin, CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, CajaIconContainerDetails::left_margin, CajaIconContainerDetails::right_margin, and CajaIconContainerDetails::top_margin.
caja_icon_container_set_selection()
void caja_icon_container_set_selection (CajaIconContainer * container, GList * selection)
caja_icon_container_set_selection: @container: An icon container widget. @selection: A list of CajaIconData *.
Set the selection to exactly the icons in @container which have programmer data matching one of the items in @selection.
Definition at line 8267 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, hash, CajaIconContainerDetails::icons, NULL, and SELECTION_CHANGED.
caja_icon_container_set_single_click_mode()
void caja_icon_container_set_single_click_mode (CajaIconContainer * container, gboolean single_click_mode)
Definition at line 9254 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::single_click_mode.
caja_icon_container_set_store_layout_timestamps()
void caja_icon_container_set_store_layout_timestamps (CajaIconContainer * container, gboolean store_layout)
Definition at line 10229 of file caja-icon-container.c.
References CajaIconContainer::details, FALSE, and CajaIconContainerDetails::store_layout_timestamps.
caja_icon_container_set_tighter_layout()
void caja_icon_container_set_tighter_layout (CajaIconContainer * container, gboolean tighter_layout)
Definition at line 8692 of file caja-icon-container.c.
References CajaIconContainerDetails::auto_layout, caja_icon_container_request_update_all(), CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, LAYOUT_CHANGED, CajaIconContainerDetails::tighter_layout, and TRUE.
caja_icon_container_set_use_drop_shadows()
void caja_icon_container_set_use_drop_shadows (CajaIconContainer * container, gboolean use_drop_shadows)
Definition at line 9324 of file caja-icon-container.c.
References CajaIconContainer::details, CajaIconContainerDetails::drop_shadows_requested, and CajaIconContainerDetails::use_drop_shadows.
caja_icon_container_set_zoom_level()
void caja_icon_container_set_zoom_level (CajaIconContainer * view, int new_zoom_level)
Definition at line 8017 of file caja-icon-container.c.
References caja_get_icon_size_for_zoom_level(), caja_icon_container_request_update_all(), CAJA_ICON_SIZE_STANDARD, CAJA_ZOOM_LEVEL_LARGEST, CAJA_ZOOM_LEVEL_SMALLEST, CajaIconContainer::details, EEL_CANVAS, eel_canvas_set_pixels_per_unit(), TRUE, and CajaIconContainerDetails::zoom_level.
caja_icon_container_show_stretch_handles()
void caja_icon_container_show_stretch_handles (CajaIconContainer * container)
caja_icon_container_show_stretch_handles: @container: An icon container widget.
Makes stretch handles visible on the first selected icon.
Definition at line 8471 of file caja-icon-container.c.
References caja_icon_canvas_item_set_show_stretch_handles(), CajaIconContainer::details, FALSE, CajaIcon::item, NULL, CajaIconContainerDetails::stretch_icon, CajaIconContainerDetails::stretch_initial_size, CajaIconContainerDetails::stretch_initial_x, CajaIconContainerDetails::stretch_initial_y, and TRUE.
caja_icon_container_sort()
void caja_icon_container_sort (CajaIconContainer * container)
Definition at line 8877 of file caja-icon-container.c.
References CajaIconContainerDetails::auto_layout, CajaIconContainer::details, LAYOUT_CHANGED, and TRUE.
caja_icon_container_start_renaming_selected_item()
void caja_icon_container_start_renaming_selected_item (CajaIconContainer * container, gboolean select_all)
caja_icon_container_start_renaming_selected_item @container: An icon container widget. @select_all: Whether the whole file should initially be selected, or only its basename (i.e. everything except its extension).
Displays the edit name widget on the first selected icon
Definition at line 8993 of file caja-icon-container.c.
References caja_icon_canvas_item_get_editable_text(), caja_icon_canvas_item_get_icon_rectangle(), caja_icon_canvas_item_get_max_text_width(), caja_icon_canvas_item_get_text_rectangle(), caja_icon_canvas_item_set_renaming(), caja_icon_container_is_layout_vertical(), caja_icon_container_update_icon(), CAJA_ICON_LABEL_POSITION_BESIDE, CajaIconContainer::details, EEL_CANVAS_ITEM, eel_canvas_w2c(), EEL_EDITABLE_LABEL, eel_editable_label_new(), eel_editable_label_select_region(), eel_editable_label_set_draw_outline(), eel_editable_label_set_font_description(), eel_editable_label_set_justify(), eel_editable_label_set_line_wrap(), eel_editable_label_set_line_wrap_mode(), eel_editable_label_set_text(), eel_filename_get_rename_region(), CajaIconContainerDetails::font, CajaIconContainerDetails::font_size_table, CajaIconContainerDetails::label_position, NULL, CajaIconContainerDetails::original_text, CajaIconContainerDetails::rename_widget, CajaIconContainerDetails::renaming, RENAMING_ICON, TRUE, EelDRect::x0, EelDRect::x1, EelDRect::y0, EelDRect::y1, and CajaIconContainerDetails::zoom_level.
caja_icon_container_unselect_all()
void caja_icon_container_unselect_all (CajaIconContainer * container)
caja_icon_container_unselect_all: @container: An icon container widget.
Deselect all the icons in @container.
Definition at line 8350 of file caja-icon-container.c.
References SELECTION_CHANGED.
caja_icon_container_unstretch()
void caja_icon_container_unstretch (CajaIconContainer * container)
caja_icon_container_unstretch @container: An icon container widget.
Gets rid of any icon stretching.
Definition at line 8561 of file caja-icon-container.c.
References caja_icon_container_move_icon(), CajaIconContainer::details, FALSE, CajaIconContainerDetails::icons, NULL, and TRUE.
caja_icon_container_widget_to_file_operation_position()
void caja_icon_container_widget_to_file_operation_position (CajaIconContainer * container, GdkPoint * position)
Definition at line 9882 of file caja-icon-container.c.
References caja_get_icon_size_for_zoom_level(), CajaIconContainer::details, EEL_CANVAS, eel_canvas_window_to_world(), int(), NULL, and CajaIconContainerDetails::zoom_level.