MATE Desktop Environment: caja-search-directory.c File Reference
caja-search-directory.c File Reference
#include <config.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <sys/time.h>
#include <eel/eel-glib-extensions.h>
#include "caja-search-directory.h"
#include "caja-search-directory-file.h"
#include "caja-directory-private.h"
#include "caja-file.h"
#include "caja-file-private.h"
#include "caja-file-utilities.h"
#include "caja-search-engine.h"
Functions
G_DEFINE_TYPE (CajaSearchDirectory, caja_search_directory, CAJA_TYPE_DIRECTORY)
char * caja_search_directory_generate_new_uri (void)
void caja_search_directory_set_query (CajaSearchDirectory *search, CajaQuery *query)
CajaQuery * caja_search_directory_get_query (CajaSearchDirectory *search)
CajaSearchEngine * caja_search_directory_get_engine (CajaSearchDirectory *search)
CajaSearchDirectory * caja_search_directory_new_from_saved_search (const char *uri)
gboolean caja_search_directory_is_saved_search (CajaSearchDirectory *search)
gboolean caja_search_directory_is_modified (CajaSearchDirectory *search)
gboolean caja_search_directory_is_indexed (CajaSearchDirectory *search)
void caja_search_directory_save_to_file (CajaSearchDirectory *search, const char *save_file_uri)
void caja_search_directory_save_search (CajaSearchDirectory *search)
Function Documentation
caja_search_directory_generate_new_uri()
char * caja_search_directory_generate_new_uri (void)
Definition at line 796 of file caja-search-directory.c.
References EEL_SEARCH_URI.
caja_search_directory_get_engine()
CajaSearchEngine * caja_search_directory_get_engine (CajaSearchDirectory * search)
Definition at line 850 of file caja-search-directory.c.
References CajaSearchDirectory::details.
caja_search_directory_get_query()
CajaQuery * caja_search_directory_get_query (CajaSearchDirectory * search)
Definition at line 839 of file caja-search-directory.c.
References CajaSearchDirectory::details, and NULL.
Referenced by caja_search_directory_file_update_display_name().
caja_search_directory_is_indexed()
gboolean caja_search_directory_is_indexed (CajaSearchDirectory * search)
Definition at line 900 of file caja-search-directory.c.
References caja_search_engine_is_indexed(), and CajaSearchDirectory::details.
caja_search_directory_is_modified()
gboolean caja_search_directory_is_modified (CajaSearchDirectory * search)
Definition at line 894 of file caja-search-directory.c.
References CajaSearchDirectory::details.
caja_search_directory_is_saved_search()
gboolean caja_search_directory_is_saved_search (CajaSearchDirectory * search)
Definition at line 888 of file caja-search-directory.c.
References CajaSearchDirectory::details, and NULL.
caja_search_directory_new_from_saved_search()
CajaSearchDirectory * caja_search_directory_new_from_saved_search (const char * uri)
Definition at line 856 of file caja-search-directory.c.
References caja_query_load(), CAJA_SEARCH_DIRECTORY, caja_search_directory_set_query(), CAJA_TYPE_SEARCH_DIRECTORY, CajaSearchDirectory::details, FALSE, and NULL.
caja_search_directory_save_search()
void caja_search_directory_save_search (CajaSearchDirectory * search)
Definition at line 927 of file caja-search-directory.c.
References caja_search_directory_save_to_file(), CajaSearchDirectory::details, FALSE, and NULL.
caja_search_directory_save_to_file()
void caja_search_directory_save_to_file (CajaSearchDirectory * search, const char * save_file_uri)
Definition at line 907 of file caja-search-directory.c.
References caja_query_save(), CajaSearchDirectory::details, and NULL.
Referenced by caja_search_directory_save_search().
caja_search_directory_set_query()
void caja_search_directory_set_query (CajaSearchDirectory * search, CajaQuery * query)
Definition at line 807 of file caja-search-directory.c.
References _CajaDirectoryPrivate::as_file, CAJA_DIRECTORY, CAJA_SEARCH_DIRECTORY_FILE, caja_search_directory_file_update_display_name(), CajaDirectory::details, CajaSearchDirectory::details, NULL, and TRUE.
Referenced by caja_search_directory_new_from_saved_search(), G_DEFINE_TYPE_WITH_CODE(), and main().
G_DEFINE_TYPE()
G_DEFINE_TYPE (CajaSearchDirectory , caja_search_directory , CAJA_TYPE_DIRECTORY)
References CAJA_TYPE_DIRECTORY, data, engine, and error.