MATE Desktop Environment: caja-program-choosing.h File Reference
caja-program-choosing.h File Reference
#include <gtk/gtk.h>
#include <gio/gio.h>
#include "caja-file.h"
Typedefs
typedef void(* CajaApplicationChoiceCallback) (GAppInfo *application, gpointer callback_data)
Functions
void caja_launch_application (GAppInfo *application, GList *files, GtkWindow *parent_window)
void caja_launch_application_by_uri (GAppInfo *application, GList *uris, GtkWindow *parent_window)
void caja_launch_application_from_command (GdkScreen *screen, const char *name, const char *command_string, gboolean use_terminal,...)
void caja_launch_application_from_command_array (GdkScreen *screen, const char *name, const char *command_string, gboolean use_terminal, const char *const *parameters)
void caja_launch_desktop_file (GdkScreen *screen, const char *desktop_file_uri, const GList *parameter_uris, GtkWindow *parent_window)
Typedef Documentation
CajaApplicationChoiceCallback
typedef void(* CajaApplicationChoiceCallback) (GAppInfo *application, gpointer callback_data)
Definition at line 34 of file caja-program-choosing.h.
Function Documentation
caja_launch_application()
void caja_launch_application (GAppInfo * application, GList * files, GtkWindow * parent_window)
caja_launch_application:
Fork off a process to launch an application with a given file as a parameter. Provide a parent window for error dialogs.
@application: The application to be launched. @uris: The files whose locations should be passed as a parameter to the application. @parent_window: A window to use as the parent for any error dialogs.
Definition at line 156 of file caja-program-choosing.c.
References caja_file_get_activation_uri(), caja_launch_application_by_uri(), and NULL.
Referenced by caja_autorun_launch_for_mount().
caja_launch_application_by_uri()
void caja_launch_application_by_uri (GAppInfo * application, GList * uris, GtkWindow * parent_window)
Definition at line 193 of file caja-program-choosing.c.
References caja_file_get_by_uri(), caja_file_get_icon(), caja_file_unref(), caja_icon_info_get_used_name(), caja_recent_add_file(), error, and NULL.
Referenced by caja_launch_application().
caja_launch_application_from_command()
void caja_launch_application_from_command (GdkScreen * screen, const char * name, const char * command_string, gboolean use_terminal, ...)
caja_launch_application_from_command:
Fork off a process to launch an application with a given uri as a parameter.
@command_string: The application to be launched, with any desired command-line options. ...: Passed as parameters to the application after quoting each of them.
Definition at line 313 of file caja-program-choosing.c.
References eel_mate_open_terminal_on_screen(), name, and NULL.
caja_launch_application_from_command_array()
void caja_launch_application_from_command_array (GdkScreen * screen, const char * name, const char * command_string, gboolean use_terminal, const char *const * parameters)
caja_launch_application_from_command:
Fork off a process to launch an application with a given uri as a parameter.
@command_string: The application to be launched, with any desired command-line options. @parameters: Passed as parameters to the application after quoting each of them.
Definition at line 381 of file caja-program-choosing.c.
References eel_mate_open_terminal_on_screen(), name, and NULL.
caja_launch_desktop_file()
void caja_launch_desktop_file (GdkScreen * screen, const char * desktop_file_uri, const GList * parameter_uris, GtkWindow * parent_window)
Definition at line 437 of file caja-program-choosing.c.
References _, eel_show_error_dialog(), eel_show_warning_dialog(), error, message(), and NULL.
Referenced by fm_directory_view_move_copy_items().