MATE Desktop Environment: caja-search-directory.h File Reference
caja-search-directory.h File Reference
#include "caja-directory.h"
#include "caja-query.h"
#include "caja-search-engine.h"
Classes
struct CajaSearchDirectory
struct CajaSearchDirectoryClass
Macros
#define CAJA_TYPE_SEARCH_DIRECTORY caja_search_directory_get_type()
#define CAJA_SEARCH_DIRECTORY(obj)
#define CAJA_SEARCH_DIRECTORY_CLASS(klass)
#define CAJA_IS_SEARCH_DIRECTORY(obj)
#define CAJA_IS_SEARCH_DIRECTORY_CLASS(klass)
#define CAJA_SEARCH_DIRECTORY_GET_CLASS(obj)
Typedefs
typedef struct CajaSearchDirectoryDetails CajaSearchDirectoryDetails
Functions
GType caja_search_directory_get_type (void)
char * caja_search_directory_generate_new_uri (void)
CajaSearchDirectory * caja_search_directory_new_from_saved_search (const char *uri)
gboolean caja_search_directory_is_saved_search (CajaSearchDirectory *search)
gboolean caja_search_directory_is_modified (CajaSearchDirectory *search)
gboolean caja_search_directory_is_indexed (CajaSearchDirectory *search)
void caja_search_directory_save_search (CajaSearchDirectory *search)
void caja_search_directory_save_to_file (CajaSearchDirectory *search, const char *save_file_uri)
CajaQuery * caja_search_directory_get_query (CajaSearchDirectory *search)
void caja_search_directory_set_query (CajaSearchDirectory *search, CajaQuery *query)
CajaSearchEngine * caja_search_directory_get_engine (CajaSearchDirectory *search)
Macro Definition Documentation
CAJA_IS_SEARCH_DIRECTORY
#define CAJA_IS_SEARCH_DIRECTORY (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_SEARCH_DIRECTORY))
Definition at line 37 of file caja-search-directory.h.
Referenced by caja_navigation_window_pane_hide_temporary_bars(), and G_DEFINE_TYPE_WITH_CODE().
CAJA_IS_SEARCH_DIRECTORY_CLASS
#define CAJA_IS_SEARCH_DIRECTORY_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_SEARCH_DIRECTORY))
Definition at line 39 of file caja-search-directory.h.
CAJA_SEARCH_DIRECTORY
#define CAJA_SEARCH_DIRECTORY (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_SEARCH_DIRECTORY, CajaSearchDirectory))
Definition at line 33 of file caja-search-directory.h.
Referenced by caja_search_directory_file_update_display_name(), caja_search_directory_new_from_saved_search(), G_DEFINE_TYPE_WITH_CODE(), and main().
CAJA_SEARCH_DIRECTORY_CLASS
#define CAJA_SEARCH_DIRECTORY_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_SEARCH_DIRECTORY, CajaSearchDirectoryClass))
Definition at line 35 of file caja-search-directory.h.
CAJA_SEARCH_DIRECTORY_GET_CLASS
#define CAJA_SEARCH_DIRECTORY_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_SEARCH_DIRECTORY, CajaSearchDirectoryClass))
Definition at line 41 of file caja-search-directory.h.
CAJA_TYPE_SEARCH_DIRECTORY
#define CAJA_TYPE_SEARCH_DIRECTORY caja_search_directory_get_type()
Definition at line 32 of file caja-search-directory.h.
Referenced by caja_search_directory_new_from_saved_search().
Typedef Documentation
CajaSearchDirectoryDetails
typedef struct CajaSearchDirectoryDetails CajaSearchDirectoryDetails
Definition at line 44 of file caja-search-directory.h.
Function Documentation
caja_search_directory_generate_new_uri()
char * caja_search_directory_generate_new_uri (void)
Definition at line 796 of file caja-search-directory.c.
References EEL_SEARCH_URI.
caja_search_directory_get_engine()
CajaSearchEngine * caja_search_directory_get_engine (CajaSearchDirectory * search)
Definition at line 850 of file caja-search-directory.c.
References CajaSearchDirectory::details.
caja_search_directory_get_query()
CajaQuery * caja_search_directory_get_query (CajaSearchDirectory * search)
Definition at line 839 of file caja-search-directory.c.
References CajaSearchDirectory::details, and NULL.
Referenced by caja_search_directory_file_update_display_name().
caja_search_directory_get_type()
GType caja_search_directory_get_type (void)
caja_search_directory_is_indexed()
gboolean caja_search_directory_is_indexed (CajaSearchDirectory * search)
Definition at line 900 of file caja-search-directory.c.
References caja_search_engine_is_indexed(), and CajaSearchDirectory::details.
caja_search_directory_is_modified()
gboolean caja_search_directory_is_modified (CajaSearchDirectory * search)
Definition at line 894 of file caja-search-directory.c.
References CajaSearchDirectory::details.
caja_search_directory_is_saved_search()
gboolean caja_search_directory_is_saved_search (CajaSearchDirectory * search)
Definition at line 888 of file caja-search-directory.c.
References CajaSearchDirectory::details, and NULL.
caja_search_directory_new_from_saved_search()
CajaSearchDirectory * caja_search_directory_new_from_saved_search (const char * uri)
Definition at line 856 of file caja-search-directory.c.
References caja_query_load(), CAJA_SEARCH_DIRECTORY, caja_search_directory_set_query(), CAJA_TYPE_SEARCH_DIRECTORY, CajaSearchDirectory::details, FALSE, and NULL.
caja_search_directory_save_search()
void caja_search_directory_save_search (CajaSearchDirectory * search)
Definition at line 927 of file caja-search-directory.c.
References caja_search_directory_save_to_file(), CajaSearchDirectory::details, FALSE, and NULL.
caja_search_directory_save_to_file()
void caja_search_directory_save_to_file (CajaSearchDirectory * search, const char * save_file_uri)
Definition at line 907 of file caja-search-directory.c.
References caja_query_save(), CajaSearchDirectory::details, and NULL.
Referenced by caja_search_directory_save_search().
caja_search_directory_set_query()
void caja_search_directory_set_query (CajaSearchDirectory * search, CajaQuery * query)
Definition at line 807 of file caja-search-directory.c.
References _CajaDirectoryPrivate::as_file, CAJA_DIRECTORY, CAJA_SEARCH_DIRECTORY_FILE, caja_search_directory_file_update_display_name(), CajaDirectory::details, CajaSearchDirectory::details, NULL, and TRUE.
Referenced by caja_search_directory_new_from_saved_search(), G_DEFINE_TYPE_WITH_CODE(), and main().