MATE Desktop Environment: caja-icon-canvas-item.c File Reference
caja-icon-canvas-item.c File Reference
#include <config.h>
#include <math.h>
#include <glib/gi18n.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <atk/atkimage.h>
#include <atk/atkcomponent.h>
#include <atk/atknoopobject.h>
#include <stdio.h>
#include <string.h>
#include <eel/eel-art-extensions.h>
#include <eel/eel-gdk-extensions.h>
#include <eel/eel-gdk-pixbuf-extensions.h>
#include <eel/eel-glib-extensions.h>
#include <eel/eel-graphic-effects.h>
#include <eel/eel-gtk-macros.h>
#include <eel/eel-string.h>
#include <eel/eel-accessibility.h>
#include "caja-icon-canvas-item.h"
#include "caja-file-utilities.h"
#include "caja-global-preferences.h"
#include "caja-icon-private.h"
Macros
#define EMBLEM_SPACING 2
#define LABEL_OFFSET 1
#define LABEL_LINE_SPACING 0
#define MAX_TEXT_WIDTH_STANDARD 135
#define MAX_TEXT_WIDTH_TIGHTER 80
#define MAX_TEXT_WIDTH_BESIDE 90
#define MAX_TEXT_WIDTH_BESIDE_TOP_TO_BOTTOM 150
#define PANGO_CHECK_VERSION(major, minor, micro)
#define IS_COMPACT_VIEW(container)
#define TEXT_BACK_PADDING_X 4
#define TEXT_BACK_PADDING_Y 1
#define ZERO_WIDTH_SPACE "\xE2\x80\x8B"
#define ZERO_OR_THREE_DIGITS(p)
#define GET_PRIV(o)
Typedefs
typedef AtkObjectFactory CajaIconCanvasItemAccessibleFactory
typedef AtkObjectFactoryClass CajaIconCanvasItemAccessibleFactoryClass
Enumerations
enum {
PROP_0 , PROP_EDITABLE_TEXT , PROP_ADDITIONAL_TEXT , PROP_HIGHLIGHTED_FOR_SELECTION ,
PROP_HIGHLIGHTED_AS_KEYBOARD_FOCUS , PROP_HIGHLIGHTED_FOR_DROP , PROP_HIGHLIGHTED_FOR_CLIPBOARD
}
enum RectangleSide { RIGHT_SIDE , BOTTOM_SIDE , LEFT_SIDE , TOP_SIDE }
enum { ACTION_OPEN , ACTION_MENU , LAST_ACTION }
Functions
G_DEFINE_TYPE_WITH_CODE (CajaIconCanvasItem, caja_icon_canvas_item, EEL_TYPE_CANVAS_ITEM, G_IMPLEMENT_INTERFACE(EEL_TYPE_ACCESSIBLE_TEXT, caja_icon_canvas_item_text_interface_init))
void caja_icon_canvas_item_invalidate_label_size (CajaIconCanvasItem *item)
cairo_surface_t * caja_icon_canvas_item_get_drag_surface (CajaIconCanvasItem *item)
void caja_icon_canvas_item_set_image (CajaIconCanvasItem *item, GdkPixbuf *image)
void caja_icon_canvas_item_set_emblems (CajaIconCanvasItem *item, GList *emblem_pixbufs)
void caja_icon_canvas_item_set_attach_points (CajaIconCanvasItem *item, GdkPoint *attach_points, int n_attach_points)
void caja_icon_canvas_item_set_embedded_text_rect (CajaIconCanvasItem *item, const GdkRectangle *text_rect)
void caja_icon_canvas_item_set_embedded_text (CajaIconCanvasItem *item, const char *text)
void caja_icon_canvas_item_update_bounds (CajaIconCanvasItem *item, double i2w_dx, double i2w_dy)
void caja_icon_canvas_item_set_is_visible (CajaIconCanvasItem *item, gboolean visible)
void caja_icon_canvas_item_invalidate_label (CajaIconCanvasItem *item)
void caja_icon_canvas_item_get_bounds_for_layout (CajaIconCanvasItem *icon_item, double *x1, double *y1, double *x2, double *y2)
void caja_icon_canvas_item_get_bounds_for_entire_item (CajaIconCanvasItem *icon_item, double *x1, double *y1, double *x2, double *y2)
EelDRect caja_icon_canvas_item_get_icon_rectangle (const CajaIconCanvasItem *item)
EelDRect caja_icon_canvas_item_get_text_rectangle (CajaIconCanvasItem *item, gboolean for_layout)
void caja_icon_canvas_item_set_show_stretch_handles (CajaIconCanvasItem *item, gboolean show_stretch_handles)
gboolean caja_icon_canvas_item_hit_test_stretch_handles (CajaIconCanvasItem *item, EelDPoint world_point, GtkCornerType *corner)
gboolean caja_icon_canvas_item_hit_test_rectangle (CajaIconCanvasItem *item, EelIRect canvas_rect)
const char * caja_icon_canvas_item_get_editable_text (CajaIconCanvasItem *icon_item)
void caja_icon_canvas_item_set_renaming (CajaIconCanvasItem *item, gboolean state)
double caja_icon_canvas_item_get_max_text_width (CajaIconCanvasItem *item)
void caja_icon_canvas_item_set_entire_text (CajaIconCanvasItem *item, gboolean entire_text)
G_DEFINE_TYPE_WITH_CODE (CajaIconCanvasItemAccessible, caja_icon_canvas_item_accessible, eel_canvas_item_accessible_get_type(), G_IMPLEMENT_INTERFACE(ATK_TYPE_IMAGE, caja_icon_canvas_item_accessible_image_interface_init) G_IMPLEMENT_INTERFACE(ATK_TYPE_TEXT, caja_icon_canvas_item_accessible_text_interface_init) G_IMPLEMENT_INTERFACE(ATK_TYPE_ACTION, caja_icon_canvas_item_accessible_action_interface_init))
G_DEFINE_TYPE (CajaIconCanvasItemAccessibleFactory, caja_icon_canvas_item_accessible_factory, ATK_TYPE_OBJECT_FACTORY)
Macro Definition Documentation
EMBLEM_SPACING
#define EMBLEM_SPACING 2
Definition at line 52 of file caja-icon-canvas-item.c.
GET_PRIV
#define GET_PRIV (o)
Value:
G_TYPE_INSTANCE_GET_PRIVATE(o, caja_icon_canvas_item_accessible_get_type (), CajaIconCanvasItemAccessiblePrivate);
Definition at line 2873 of file caja-icon-canvas-item.c.
IS_COMPACT_VIEW
#define IS_COMPACT_VIEW (container)
Value:
   ((container->details->layout_mode == CAJA_ICON_LAYOUT_T_B_L_R || \
 container->details->layout_mode == CAJA_ICON_LAYOUT_T_B_R_L) && \
container->details->label_position == CAJA_ICON_LABEL_POSITION_BESIDE)
Definition at line 1021 of file caja-icon-canvas-item.c.
LABEL_LINE_SPACING
#define LABEL_LINE_SPACING 0
Definition at line 56 of file caja-icon-canvas-item.c.
LABEL_OFFSET
#define LABEL_OFFSET 1
Definition at line 55 of file caja-icon-canvas-item.c.
MAX_TEXT_WIDTH_BESIDE
#define MAX_TEXT_WIDTH_BESIDE 90
Definition at line 60 of file caja-icon-canvas-item.c.
Referenced by caja_icon_canvas_item_get_max_text_width().
MAX_TEXT_WIDTH_BESIDE_TOP_TO_BOTTOM
#define MAX_TEXT_WIDTH_BESIDE_TOP_TO_BOTTOM 150
Definition at line 61 of file caja-icon-canvas-item.c.
Referenced by caja_icon_canvas_item_get_max_text_width().
MAX_TEXT_WIDTH_STANDARD
#define MAX_TEXT_WIDTH_STANDARD 135
Definition at line 58 of file caja-icon-canvas-item.c.
Referenced by caja_icon_canvas_item_get_max_text_width().
MAX_TEXT_WIDTH_TIGHTER
#define MAX_TEXT_WIDTH_TIGHTER 80
Definition at line 59 of file caja-icon-canvas-item.c.
Referenced by caja_icon_canvas_item_get_max_text_width().
PANGO_CHECK_VERSION
#define PANGO_CHECK_VERSION (major, minor, micro)
Value:
(PANGO_VERSION_MAJOR > (major) ||                                    \
(PANGO_VERSION_MAJOR == (major) && PANGO_VERSION_MINOR > (minor)) || \
(PANGO_VERSION_MAJOR == (major) && PANGO_VERSION_MINOR == (minor) && \
 PANGO_VERSION_MICRO >= (micro)))
Definition at line 64 of file caja-icon-canvas-item.c.
TEXT_BACK_PADDING_X
#define TEXT_BACK_PADDING_X 4
Definition at line 1026 of file caja-icon-canvas-item.c.
TEXT_BACK_PADDING_Y
#define TEXT_BACK_PADDING_Y 1
Definition at line 1027 of file caja-icon-canvas-item.c.
ZERO_OR_THREE_DIGITS
#define ZERO_OR_THREE_DIGITS (p)
Value:
(!g_ascii_isdigit (*p) || \
 (g_ascii_isdigit (*(p+1)) && \
  g_ascii_isdigit (*(p+2))))
Definition at line 1963 of file caja-icon-canvas-item.c.
ZERO_WIDTH_SPACE
#define ZERO_WIDTH_SPACE "\xE2\x80\x8B"
Definition at line 1961 of file caja-icon-canvas-item.c.
Typedef Documentation
CajaIconCanvasItemAccessibleFactory
typedef AtkObjectFactory CajaIconCanvasItemAccessibleFactory
Definition at line 3600 of file caja-icon-canvas-item.c.
CajaIconCanvasItemAccessibleFactoryClass
typedef AtkObjectFactoryClass CajaIconCanvasItemAccessibleFactoryClass
Definition at line 3601 of file caja-icon-canvas-item.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ACTION_OPEN
ACTION_MENU
LAST_ACTION
Definition at line 2854 of file caja-icon-canvas-item.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_EDITABLE_TEXT
PROP_ADDITIONAL_TEXT
PROP_HIGHLIGHTED_FOR_SELECTION
PROP_HIGHLIGHTED_AS_KEYBOARD_FOCUS
PROP_HIGHLIGHTED_FOR_DROP
PROP_HIGHLIGHTED_FOR_CLIPBOARD
Definition at line 167 of file caja-icon-canvas-item.c.
RectangleSide
enum RectangleSide
Enumerator
RIGHT_SIDE
BOTTOM_SIDE
LEFT_SIDE
TOP_SIDE
Definition at line 178 of file caja-icon-canvas-item.c.
Function Documentation
caja_icon_canvas_item_get_bounds_for_entire_item()
void caja_icon_canvas_item_get_bounds_for_entire_item (CajaIconCanvasItem * icon_item, double * x1, double * y1, double * x2, double * y2)
Definition at line 2354 of file caja-icon-canvas-item.c.
References CajaIconCanvasItem::details, int(), NULL, EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
caja_icon_canvas_item_get_bounds_for_layout()
void caja_icon_canvas_item_get_bounds_for_layout (CajaIconCanvasItem * icon_item, double * x1, double * y1, double * x2, double * y2)
Definition at line 2321 of file caja-icon-canvas-item.c.
References CajaIconCanvasItem::details, int(), NULL, EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
caja_icon_canvas_item_get_drag_surface()
cairo_surface_t * caja_icon_canvas_item_get_drag_surface (CajaIconCanvasItem * item)
Definition at line 531 of file caja-icon-canvas-item.c.
References CAJA_ICON_CONTAINER, caja_icon_container_is_layout_rtl(), CAJA_IS_ICON_CANVAS_ITEM, EEL_CANVAS_ITEM, eel_canvas_world_to_window(), FALSE, is_rtl, item, NULL, EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
caja_icon_canvas_item_get_editable_text()
const char * caja_icon_canvas_item_get_editable_text (CajaIconCanvasItem * icon_item)
Definition at line 2676 of file caja-icon-canvas-item.c.
References CAJA_IS_ICON_CANVAS_ITEM, CajaIconCanvasItem::details, and NULL.
Referenced by caja_icon_container_start_renaming_selected_item(), and caja_icon_container_update_icon().
caja_icon_canvas_item_get_icon_rectangle()
EelDRect caja_icon_canvas_item_get_icon_rectangle (const CajaIconCanvasItem * item)
Definition at line 2485 of file caja-icon-canvas-item.c.
References CAJA_ICON_CANVAS_ITEM, CAJA_IS_ICON_CANVAS_ITEM, EEL_CANVAS_ITEM, eel_canvas_item_i2w(), eel_drect_empty, item, EelDRect::x0, EelDRect::x1, EelDRect::y0, and EelDRect::y1.
Referenced by caja_icon_container_start_renaming_selected_item().
caja_icon_canvas_item_get_max_text_width()
double caja_icon_canvas_item_get_max_text_width (CajaIconCanvasItem * item)
Definition at line 2699 of file caja-icon-canvas-item.c.
References CajaIconContainerDetails::all_columns_same_width, CAJA_ICON_CONTAINER, caja_icon_container_is_tighter_layout(), CAJA_ICON_LABEL_POSITION_BESIDE, CAJA_ICON_LAYOUT_T_B_L_R, CAJA_ICON_LAYOUT_T_B_R_L, _EelCanvasItem::canvas, CajaIconContainer::details, EEL_CANVAS_ITEM, item, CajaIconContainerDetails::label_position, CajaIconContainerDetails::layout_mode, MAX_TEXT_WIDTH_BESIDE, MAX_TEXT_WIDTH_BESIDE_TOP_TO_BOTTOM, MAX_TEXT_WIDTH_STANDARD, MAX_TEXT_WIDTH_TIGHTER, and _EelCanvas::pixels_per_unit.
Referenced by caja_icon_container_start_renaming_selected_item().
caja_icon_canvas_item_get_text_rectangle()
EelDRect caja_icon_canvas_item_get_text_rectangle (CajaIconCanvasItem * item, gboolean for_layout)
Definition at line 2512 of file caja-icon-canvas-item.c.
References BOUNDS_USAGE_FOR_DISPLAY, BOUNDS_USAGE_FOR_LAYOUT, CAJA_IS_ICON_CANVAS_ITEM, EEL_CANVAS_ITEM, eel_canvas_item_i2w(), eel_drect_empty, FALSE, item, EelDRect::x0, EelIRect::x0, EelDRect::x1, EelIRect::x1, EelDRect::y0, EelIRect::y0, EelDRect::y1, and EelIRect::y1.
Referenced by caja_icon_container_start_renaming_selected_item().
caja_icon_canvas_item_hit_test_rectangle()
gboolean caja_icon_canvas_item_hit_test_rectangle (CajaIconCanvasItem * item, EelIRect canvas_rect)
Definition at line 2668 of file caja-icon-canvas-item.c.
References CAJA_IS_ICON_CANVAS_ITEM, FALSE, and item.
caja_icon_canvas_item_hit_test_stretch_handles()
gboolean caja_icon_canvas_item_hit_test_stretch_handles (CajaIconCanvasItem * item, EelDPoint world_point, GtkCornerType * corner)
Definition at line 2644 of file caja-icon-canvas-item.c.
References CAJA_IS_ICON_CANVAS_ITEM, EEL_CANVAS_ITEM, eel_canvas_w2c(), FALSE, item, EelDPoint::x, EelIRect::x0, EelIRect::x1, EelDPoint::y, EelIRect::y0, and EelIRect::y1.
caja_icon_canvas_item_invalidate_label()
void caja_icon_canvas_item_invalidate_label (CajaIconCanvasItem * item)
Definition at line 1443 of file caja-icon-canvas-item.c.
References caja_icon_canvas_item_invalidate_label_size(), item, and NULL.
Referenced by caja_icon_canvas_item_set_is_visible().
caja_icon_canvas_item_invalidate_label_size()
void caja_icon_canvas_item_invalidate_label_size (CajaIconCanvasItem * item)
Definition at line 337 of file caja-icon-canvas-item.c.
References item, and NULL.
Referenced by caja_icon_canvas_item_invalidate_label(), and caja_icon_canvas_item_set_entire_text().
caja_icon_canvas_item_set_attach_points()
void caja_icon_canvas_item_set_attach_points (CajaIconCanvasItem * item, GdkPoint * attach_points, int n_attach_points)
Definition at line 685 of file caja-icon-canvas-item.c.
References item, and NULL.
Referenced by caja_icon_container_update_icon().
caja_icon_canvas_item_set_embedded_text()
void caja_icon_canvas_item_set_embedded_text (CajaIconCanvasItem * item, const char * text)
Definition at line 713 of file caja-icon-canvas-item.c.
References EEL_CANVAS_ITEM, eel_canvas_item_request_update(), item, and NULL.
Referenced by caja_icon_container_update_icon().
caja_icon_canvas_item_set_embedded_text_rect()
void caja_icon_canvas_item_set_embedded_text_rect (CajaIconCanvasItem * item, const GdkRectangle * text_rect)
Definition at line 703 of file caja-icon-canvas-item.c.
References EEL_CANVAS_ITEM, eel_canvas_item_request_update(), and item.
Referenced by caja_icon_container_update_icon().
caja_icon_canvas_item_set_emblems()
void caja_icon_canvas_item_set_emblems (CajaIconCanvasItem * item, GList * emblem_pixbufs)
Definition at line 652 of file caja-icon-canvas-item.c.
References CAJA_IS_ICON_CANVAS_ITEM, EEL_CANVAS_ITEM, eel_canvas_item_request_update(), eel_g_list_equal(), item, and NULL.
Referenced by caja_icon_container_update_icon().
caja_icon_canvas_item_set_entire_text()
void caja_icon_canvas_item_set_entire_text (CajaIconCanvasItem * item, gboolean entire_text)
Definition at line 2743 of file caja-icon-canvas-item.c.
References caja_icon_canvas_item_invalidate_label_size(), EEL_CANVAS_ITEM, eel_canvas_item_request_update(), FALSE, and item.
caja_icon_canvas_item_set_image()
void caja_icon_canvas_item_set_image (CajaIconCanvasItem * item, GdkPixbuf * image)
Definition at line 617 of file caja-icon-canvas-item.c.
References CAJA_IS_ICON_CANVAS_ITEM, EEL_CANVAS_ITEM, eel_canvas_item_request_update(), item, and NULL.
Referenced by caja_icon_container_update_icon().
caja_icon_canvas_item_set_is_visible()
void caja_icon_canvas_item_set_is_visible (CajaIconCanvasItem * item, gboolean visible)
Definition at line 1428 of file caja-icon-canvas-item.c.
References caja_icon_canvas_item_invalidate_label(), FALSE, and item.
caja_icon_canvas_item_set_renaming()
void caja_icon_canvas_item_set_renaming (CajaIconCanvasItem * item, gboolean state)
Definition at line 2684 of file caja-icon-canvas-item.c.
References CAJA_IS_ICON_CANVAS_ITEM, EEL_CANVAS_ITEM, eel_canvas_item_request_update(), FALSE, item, and TRUE.
Referenced by caja_icon_container_start_renaming_selected_item().
caja_icon_canvas_item_set_show_stretch_handles()
void caja_icon_canvas_item_set_show_stretch_handles (CajaIconCanvasItem * item, gboolean show_stretch_handles)
Definition at line 2575 of file caja-icon-canvas-item.c.
References CAJA_IS_ICON_CANVAS_ITEM, EEL_CANVAS_ITEM, eel_canvas_item_request_update(), FALSE, item, and TRUE.
Referenced by caja_icon_container_show_stretch_handles().
caja_icon_canvas_item_update_bounds()
void caja_icon_canvas_item_update_bounds (CajaIconCanvasItem * item, double i2w_dx, double i2w_dy)
Definition at line 878 of file caja-icon-canvas-item.c.
References BOUNDS_USAGE_FOR_DISPLAY, CAJA_ICON_CONTAINER, caja_icon_container_is_layout_rtl(), _EelCanvasItem::canvas, EEL_CANVAS_ITEM, eel_canvas_request_redraw(), eel_irect_equal(), eel_irect_union(), is_rtl, item, TRUE, EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
G_DEFINE_TYPE()
G_DEFINE_TYPE (CajaIconCanvasItemAccessibleFactory , caja_icon_canvas_item_accessible_factory , ATK_TYPE_OBJECT_FACTORY)
References item, and NULL.
G_DEFINE_TYPE_WITH_CODE() [1/2]
G_DEFINE_TYPE_WITH_CODE (CajaIconCanvasItem , caja_icon_canvas_item , EEL_TYPE_CANVAS_ITEM , G_IMPLEMENT_INTERFACE(EEL_TYPE_ACCESSIBLE_TEXT, caja_icon_canvas_item_text_interface_init))
References caja_preferences, CAJA_PREFERENCES_CLICK_POLICY, EEL_TYPE_ACCESSIBLE_TEXT, EEL_TYPE_CANVAS_ITEM, FALSE, is_rtl, item, and TRUE.
G_DEFINE_TYPE_WITH_CODE() [2/2]
G_DEFINE_TYPE_WITH_CODE (CajaIconCanvasItemAccessible , caja_icon_canvas_item_accessible , eel_canvas_item_accessible_get_type() , G_IMPLEMENT_INTERFACE(ATK_TYPE_IMAGE, caja_icon_canvas_item_accessible_image_interface_init) G_IMPLEMENT_INTERFACE(ATK_TYPE_TEXT, caja_icon_canvas_item_accessible_text_interface_init) G_IMPLEMENT_INTERFACE(ATK_TYPE_ACTION, caja_icon_canvas_item_accessible_action_interface_init))
References eel_canvas_item_accessible_get_type(), and item.