MATE Desktop Environment: caja-desktop-metadata.h File Reference
caja-desktop-metadata.h File Reference
#include <glib.h>
#include "caja-file.h"
Functions
void caja_desktop_set_metadata_string (CajaFile *file, const gchar *name, const gchar *key, const gchar *string)
void caja_desktop_set_metadata_stringv (CajaFile *file, const char *name, const char *key, const char *const *stringv)
gboolean caja_desktop_update_metadata_from_keyfile (CajaFile *file, const gchar *name)
Function Documentation
caja_desktop_set_metadata_string()
void caja_desktop_set_metadata_string (CajaFile * file, const gchar * name, const gchar * key, const gchar * string)
Definition at line 144 of file caja-desktop-metadata.c.
References caja_desktop_update_metadata_from_keyfile(), caja_file_changed(), error, key, name, and NULL.
caja_desktop_set_metadata_stringv()
void caja_desktop_set_metadata_stringv (CajaFile * file, const char * name, const char * key, const char *const * stringv)
Definition at line 186 of file caja-desktop-metadata.c.
References caja_desktop_update_metadata_from_keyfile(), caja_file_changed(), FALSE, key, name, NULL, STRV_TERMINATOR, and TRUE.
caja_desktop_update_metadata_from_keyfile()
gboolean caja_desktop_update_metadata_from_keyfile (CajaFile * file, const gchar * name)
Definition at line 234 of file caja-desktop-metadata.c.
References caja_file_update_metadata_from_info(), FALSE, idx, key, name, NULL, and STRV_TERMINATOR.
Referenced by caja_desktop_icon_file_new(), caja_desktop_set_metadata_string(), and caja_desktop_set_metadata_stringv().