MATE Desktop Environment: caja-freedesktop-generated.c File Reference
caja-freedesktop-generated.c File Reference
#include "caja-freedesktop-generated.h"
#include <string.h>
Macros
#define g_marshal_value_peek_boolean(v)
#define g_marshal_value_peek_char(v)
#define g_marshal_value_peek_uchar(v)
#define g_marshal_value_peek_int(v)
#define g_marshal_value_peek_uint(v)
#define g_marshal_value_peek_long(v)
#define g_marshal_value_peek_ulong(v)
#define g_marshal_value_peek_int64(v)
#define g_marshal_value_peek_uint64(v)
#define g_marshal_value_peek_enum(v)
#define g_marshal_value_peek_flags(v)
#define g_marshal_value_peek_float(v)
#define g_marshal_value_peek_double(v)
#define g_marshal_value_peek_string(v)
#define g_marshal_value_peek_param(v)
#define g_marshal_value_peek_boxed(v)
#define g_marshal_value_peek_pointer(v)
#define g_marshal_value_peek_object(v)
#define g_marshal_value_peek_variant(v)
Typedefs
typedef CajaFreedesktopFileManager1Iface CajaFreedesktopFileManager1Interface
Functions
GDBusInterfaceInfo * caja_freedesktop_file_manager1_interface_info (void)
guint caja_freedesktop_file_manager1_override_properties (GObjectClass *klass G_GNUC_UNUSED, guint property_id_begin)
void caja_freedesktop_file_manager1_call_show_folders (CajaFreedesktopFileManager1 *proxy, const gchar *const *arg_URIs, const gchar *arg_StartupId, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean caja_freedesktop_file_manager1_call_show_folders_finish (CajaFreedesktopFileManager1 *proxy, GAsyncResult *res, GError **error)
gboolean caja_freedesktop_file_manager1_call_show_folders_sync (CajaFreedesktopFileManager1 *proxy, const gchar *const *arg_URIs, const gchar *arg_StartupId, GCancellable *cancellable, GError **error)
void caja_freedesktop_file_manager1_call_show_items (CajaFreedesktopFileManager1 *proxy, const gchar *const *arg_URIs, const gchar *arg_StartupId, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean caja_freedesktop_file_manager1_call_show_items_finish (CajaFreedesktopFileManager1 *proxy, GAsyncResult *res, GError **error)
gboolean caja_freedesktop_file_manager1_call_show_items_sync (CajaFreedesktopFileManager1 *proxy, const gchar *const *arg_URIs, const gchar *arg_StartupId, GCancellable *cancellable, GError **error)
void caja_freedesktop_file_manager1_call_show_item_properties (CajaFreedesktopFileManager1 *proxy, const gchar *const *arg_URIs, const gchar *arg_StartupId, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean caja_freedesktop_file_manager1_call_show_item_properties_finish (CajaFreedesktopFileManager1 *proxy, GAsyncResult *res, GError **error)
gboolean caja_freedesktop_file_manager1_call_show_item_properties_sync (CajaFreedesktopFileManager1 *proxy, const gchar *const *arg_URIs, const gchar *arg_StartupId, GCancellable *cancellable, GError **error)
void caja_freedesktop_file_manager1_complete_show_folders (CajaFreedesktopFileManager1 *object G_GNUC_UNUSED, GDBusMethodInvocation *invocation)
void caja_freedesktop_file_manager1_complete_show_items (CajaFreedesktopFileManager1 *object G_GNUC_UNUSED, GDBusMethodInvocation *invocation)
void caja_freedesktop_file_manager1_complete_show_item_properties (CajaFreedesktopFileManager1 *object G_GNUC_UNUSED, GDBusMethodInvocation *invocation)
G_DEFINE_TYPE_WITH_CODE (CajaFreedesktopFileManager1Proxy, caja_freedesktop_file_manager1_proxy, G_TYPE_DBUS_PROXY, G_IMPLEMENT_INTERFACE(CAJA_FREEDESKTOP_TYPE_FILE_MANAGER1, caja_freedesktop_file_manager1_proxy_iface_init))
: (nullable): A bus name (well-known or unique) or NULL if @connection is not a message bus connection.
caja_freedesktop_object_manager_client_new_sync: @connection: A #GDBusConnection. @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
@object_path: An object path. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL
Synchronously creates #GDBusObjectManagerClient using caja_freedesktop_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new_sync() for more details.
The calling thread is blocked until a reply is received.
See caja_freedesktop_object_manager_client_new() for the asynchronous version of this constructor.
Returns: (transfer full) (type CajaFreedesktopObjectManagerClient): The constructed object manager client or NULL if @error is set.
void caja_freedesktop_file_manager1_proxy_new (GDBusConnection *connection, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
CajaFreedesktopFileManager1 * caja_freedesktop_file_manager1_proxy_new_finish (GAsyncResult *res, GError **error)
CajaFreedesktopFileManager1 * caja_freedesktop_file_manager1_proxy_new_sync (GDBusConnection *connection, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GError **error)
void caja_freedesktop_object_manager_client_new (GDBusConnection *connection, GDBusObjectManagerClientFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
GDBusObjectManager * caja_freedesktop_object_manager_client_new_finish (GAsyncResult *res, GError **error)
GDBusObjectManager * caja_freedesktop_object_manager_client_new_sync (GDBusConnection *connection, GDBusObjectManagerClientFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GError **error)
: A bus name (well-known or unique).
caja_freedesktop_object_manager_client_new_for_bus_sync: @bus_type: A #GBusType. @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
@object_path: An object path. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL
Like caja_freedesktop_object_manager_client_new_sync() but takes a #GBusType instead of a #GDBusConnection.
The calling thread is blocked until a reply is received.
See caja_freedesktop_object_manager_client_new_for_bus() for the asynchronous version of this constructor.
Returns: (transfer full) (type CajaFreedesktopObjectManagerClient): The constructed object manager client or NULL if @error is set.
typedef CajaFreedesktopObjectIface CajaFreedesktopObjectInterface
void caja_freedesktop_file_manager1_proxy_new_for_bus (GBusType bus_type, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
CajaFreedesktopFileManager1 * caja_freedesktop_file_manager1_proxy_new_for_bus_finish (GAsyncResult *res, GError **error)
CajaFreedesktopFileManager1 * caja_freedesktop_file_manager1_proxy_new_for_bus_sync (GBusType bus_type, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GError **error)
G_DEFINE_TYPE_WITH_CODE (CajaFreedesktopFileManager1Skeleton, caja_freedesktop_file_manager1_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON, G_IMPLEMENT_INTERFACE(CAJA_FREEDESKTOP_TYPE_FILE_MANAGER1, caja_freedesktop_file_manager1_skeleton_iface_init))
CajaFreedesktopFileManager1 * caja_freedesktop_file_manager1_skeleton_new (void)
CajaFreedesktopFileManager1 * caja_freedesktop_object_get_file_manager1 (CajaFreedesktopObject *object)
CajaFreedesktopFileManager1 * caja_freedesktop_object_peek_file_manager1 (CajaFreedesktopObject *object)
G_DEFINE_TYPE_WITH_CODE (CajaFreedesktopObjectProxy, caja_freedesktop_object_proxy, G_TYPE_DBUS_OBJECT_PROXY, G_IMPLEMENT_INTERFACE(G_TYPE_DBUS_OBJECT, caja_freedesktop_object_proxy__g_dbus_object_iface_init))
CajaFreedesktopObjectProxy * caja_freedesktop_object_proxy_new (GDBusConnection *connection, const gchar *object_path)
G_DEFINE_TYPE_WITH_CODE (CajaFreedesktopObjectSkeleton, caja_freedesktop_object_skeleton, G_TYPE_DBUS_OBJECT_SKELETON, G_IMPLEMENT_INTERFACE(G_TYPE_DBUS_OBJECT, caja_freedesktop_object_skeleton__g_dbus_object_iface_init))
CajaFreedesktopObjectSkeleton * caja_freedesktop_object_skeleton_new (const gchar *object_path)
void caja_freedesktop_object_skeleton_set_file_manager1 (CajaFreedesktopObjectSkeleton *object, CajaFreedesktopFileManager1 *interface_)
GType caja_freedesktop_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager G_GNUC_UNUSED, const gchar *object_path G_GNUC_UNUSED, const gchar *interface_name, gpointer user_data G_GNUC_UNUSED)
void caja_freedesktop_object_manager_client_new_for_bus (GBusType bus_type, GDBusObjectManagerClientFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
GDBusObjectManager * caja_freedesktop_object_manager_client_new_for_bus_finish (GAsyncResult *res, GError **error)
GDBusObjectManager * caja_freedesktop_object_manager_client_new_for_bus_sync (GBusType bus_type, GDBusObjectManagerClientFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GError **error)
Macro Definition Documentation
g_marshal_value_peek_boolean
#define g_marshal_value_peek_boolean (v)
Value:
(v)->data[0].v_int
Definition at line 45 of file caja-freedesktop-generated.c.
g_marshal_value_peek_boxed
#define g_marshal_value_peek_boxed (v)
Value:
(v)->data[0].v_pointer
Definition at line 60 of file caja-freedesktop-generated.c.
g_marshal_value_peek_char
#define g_marshal_value_peek_char (v)
Value:
(v)->data[0].v_int
Definition at line 46 of file caja-freedesktop-generated.c.
g_marshal_value_peek_double
#define g_marshal_value_peek_double (v)
Value:
(v)->data[0].v_double
Definition at line 57 of file caja-freedesktop-generated.c.
g_marshal_value_peek_enum
#define g_marshal_value_peek_enum (v)
Value:
(v)->data[0].v_long
Definition at line 54 of file caja-freedesktop-generated.c.
g_marshal_value_peek_flags
#define g_marshal_value_peek_flags (v)
Value:
(v)->data[0].v_ulong
Definition at line 55 of file caja-freedesktop-generated.c.
g_marshal_value_peek_float
#define g_marshal_value_peek_float (v)
Value:
(v)->data[0].v_float
Definition at line 56 of file caja-freedesktop-generated.c.
g_marshal_value_peek_int
#define g_marshal_value_peek_int (v)
Value:
(v)->data[0].v_int
Definition at line 48 of file caja-freedesktop-generated.c.
g_marshal_value_peek_int64
#define g_marshal_value_peek_int64 (v)
Value:
(v)->data[0].v_int64
Definition at line 52 of file caja-freedesktop-generated.c.
g_marshal_value_peek_long
#define g_marshal_value_peek_long (v)
Value:
(v)->data[0].v_long
Definition at line 50 of file caja-freedesktop-generated.c.
g_marshal_value_peek_object
#define g_marshal_value_peek_object (v)
Value:
(v)->data[0].v_pointer
Definition at line 62 of file caja-freedesktop-generated.c.
g_marshal_value_peek_param
#define g_marshal_value_peek_param (v)
Value:
(v)->data[0].v_pointer
Definition at line 59 of file caja-freedesktop-generated.c.
g_marshal_value_peek_pointer
#define g_marshal_value_peek_pointer (v)
Value:
(v)->data[0].v_pointer
Definition at line 61 of file caja-freedesktop-generated.c.
g_marshal_value_peek_string
#define g_marshal_value_peek_string (v)
Value:
(v)->data[0].v_pointer
Definition at line 58 of file caja-freedesktop-generated.c.
g_marshal_value_peek_uchar
#define g_marshal_value_peek_uchar (v)
Value:
(v)->data[0].v_uint
Definition at line 47 of file caja-freedesktop-generated.c.
g_marshal_value_peek_uint
#define g_marshal_value_peek_uint (v)
Value:
(v)->data[0].v_uint
Definition at line 49 of file caja-freedesktop-generated.c.
g_marshal_value_peek_uint64
#define g_marshal_value_peek_uint64 (v)
Value:
(v)->data[0].v_uint64
Definition at line 53 of file caja-freedesktop-generated.c.
g_marshal_value_peek_ulong
#define g_marshal_value_peek_ulong (v)
Value:
(v)->data[0].v_ulong
Definition at line 51 of file caja-freedesktop-generated.c.
g_marshal_value_peek_variant
#define g_marshal_value_peek_variant (v)
Value:
(v)->data[0].v_pointer
Definition at line 63 of file caja-freedesktop-generated.c.
Typedef Documentation
CajaFreedesktopFileManager1Interface
typedef CajaFreedesktopFileManager1Iface CajaFreedesktopFileManager1Interface
CajaFreedesktopFileManager1:
Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-FileManager1.top_of_page">org.freedesktop.FileManager1</link>. CajaFreedesktopFileManager1Iface: @parent_iface: The parent interface. @handle_show_folders: Handler for the #CajaFreedesktopFileManager1::handle-show-folders signal. @handle_show_item_properties: Handler for the #CajaFreedesktopFileManager1::handle-show-item-properties signal. @handle_show_items: Handler for the #CajaFreedesktopFileManager1::handle-show-items signal.
Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-FileManager1.top_of_page">org.freedesktop.FileManager1</link>.
Definition at line 496 of file caja-freedesktop-generated.c.
CajaFreedesktopObjectInterface
typedef CajaFreedesktopObjectIface CajaFreedesktopObjectInterface
SECTION:CajaFreedesktopObject @title: CajaFreedesktopObject @short_description: Specialized GDBusObject types
This section contains the CajaFreedesktopObject, CajaFreedesktopObjectProxy, and CajaFreedesktopObjectSkeleton types which make it easier to work with objects implementing generated types for D-Bus interfaces. CajaFreedesktopObject:
The CajaFreedesktopObject type is a specialized container of interfaces. CajaFreedesktopObjectIface: @parent_iface: The parent interface.
Virtual table for the CajaFreedesktopObject interface.
Definition at line 1598 of file caja-freedesktop-generated.c.
Function Documentation
caja_freedesktop_file_manager1_call_show_folders()
void caja_freedesktop_file_manager1_call_show_folders (CajaFreedesktopFileManager1 * proxy, const gchar *const * arg_URIs, const gchar * arg_StartupId, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
caja_freedesktop_file_manager1_call_show_folders: @proxy: A CajaFreedesktopFileManager1Proxy. @arg_URIs: Argument to pass with the method invocation. @arg_StartupId: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @callback: A #GAsyncReadyCallback to call when the request is satisfied or NULL. @user_data: User data to pass to @callback.
Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-FileManager1.ShowFolders">ShowFolders()</link> D-Bus method on @proxy. When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()). You can then call caja_freedesktop_file_manager1_call_show_folders_finish() to get the result of the operation.
See caja_freedesktop_file_manager1_call_show_folders_sync() for the synchronous, blocking version of this method.
Definition at line 593 of file caja-freedesktop-generated.c.
References proxy, and user_data.
caja_freedesktop_file_manager1_call_show_folders_finish()
gboolean caja_freedesktop_file_manager1_call_show_folders_finish (CajaFreedesktopFileManager1 * proxy, GAsyncResult * res, GError ** error)
caja_freedesktop_file_manager1_call_show_folders_finish: @proxy: A CajaFreedesktopFileManager1Proxy. @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to caja_freedesktop_file_manager1_call_show_folders(). @error: Return location for error or NULL.
Finishes an operation started with caja_freedesktop_file_manager1_call_show_folders().
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 624 of file caja-freedesktop-generated.c.
References error, NULL, and proxy.
caja_freedesktop_file_manager1_call_show_folders_sync()
gboolean caja_freedesktop_file_manager1_call_show_folders_sync (CajaFreedesktopFileManager1 * proxy, const gchar *const * arg_URIs, const gchar * arg_StartupId, GCancellable * cancellable, GError ** error)
caja_freedesktop_file_manager1_call_show_folders_sync: @proxy: A CajaFreedesktopFileManager1Proxy. @arg_URIs: Argument to pass with the method invocation. @arg_StartupId: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL.
Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-FileManager1.ShowFolders">ShowFolders()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
See caja_freedesktop_file_manager1_call_show_folders() for the asynchronous version of this method.
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 655 of file caja-freedesktop-generated.c.
References error, NULL, and proxy.
caja_freedesktop_file_manager1_call_show_item_properties()
void caja_freedesktop_file_manager1_call_show_item_properties (CajaFreedesktopFileManager1 * proxy, const gchar *const * arg_URIs, const gchar * arg_StartupId, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
caja_freedesktop_file_manager1_call_show_item_properties: @proxy: A CajaFreedesktopFileManager1Proxy. @arg_URIs: Argument to pass with the method invocation. @arg_StartupId: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @callback: A #GAsyncReadyCallback to call when the request is satisfied or NULL. @user_data: User data to pass to @callback.
Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-FileManager1.ShowItemProperties">ShowItemProperties()</link> D-Bus method on @proxy. When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()). You can then call caja_freedesktop_file_manager1_call_show_item_properties_finish() to get the result of the operation.
See caja_freedesktop_file_manager1_call_show_item_properties_sync() for the synchronous, blocking version of this method.
Definition at line 801 of file caja-freedesktop-generated.c.
References proxy, and user_data.
caja_freedesktop_file_manager1_call_show_item_properties_finish()
gboolean caja_freedesktop_file_manager1_call_show_item_properties_finish (CajaFreedesktopFileManager1 * proxy, GAsyncResult * res, GError ** error)
caja_freedesktop_file_manager1_call_show_item_properties_finish: @proxy: A CajaFreedesktopFileManager1Proxy. @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to caja_freedesktop_file_manager1_call_show_item_properties(). @error: Return location for error or NULL.
Finishes an operation started with caja_freedesktop_file_manager1_call_show_item_properties().
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 832 of file caja-freedesktop-generated.c.
References error, NULL, and proxy.
caja_freedesktop_file_manager1_call_show_item_properties_sync()
gboolean caja_freedesktop_file_manager1_call_show_item_properties_sync (CajaFreedesktopFileManager1 * proxy, const gchar *const * arg_URIs, const gchar * arg_StartupId, GCancellable * cancellable, GError ** error)
caja_freedesktop_file_manager1_call_show_item_properties_sync: @proxy: A CajaFreedesktopFileManager1Proxy. @arg_URIs: Argument to pass with the method invocation. @arg_StartupId: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL.
Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-FileManager1.ShowItemProperties">ShowItemProperties()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
See caja_freedesktop_file_manager1_call_show_item_properties() for the asynchronous version of this method.
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 863 of file caja-freedesktop-generated.c.
References error, NULL, and proxy.
caja_freedesktop_file_manager1_call_show_items()
void caja_freedesktop_file_manager1_call_show_items (CajaFreedesktopFileManager1 * proxy, const gchar *const * arg_URIs, const gchar * arg_StartupId, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
caja_freedesktop_file_manager1_call_show_items: @proxy: A CajaFreedesktopFileManager1Proxy. @arg_URIs: Argument to pass with the method invocation. @arg_StartupId: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @callback: A #GAsyncReadyCallback to call when the request is satisfied or NULL. @user_data: User data to pass to @callback.
Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-FileManager1.ShowItems">ShowItems()</link> D-Bus method on @proxy. When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()). You can then call caja_freedesktop_file_manager1_call_show_items_finish() to get the result of the operation.
See caja_freedesktop_file_manager1_call_show_items_sync() for the synchronous, blocking version of this method.
Definition at line 697 of file caja-freedesktop-generated.c.
References proxy, and user_data.
caja_freedesktop_file_manager1_call_show_items_finish()
gboolean caja_freedesktop_file_manager1_call_show_items_finish (CajaFreedesktopFileManager1 * proxy, GAsyncResult * res, GError ** error)
caja_freedesktop_file_manager1_call_show_items_finish: @proxy: A CajaFreedesktopFileManager1Proxy. @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to caja_freedesktop_file_manager1_call_show_items(). @error: Return location for error or NULL.
Finishes an operation started with caja_freedesktop_file_manager1_call_show_items().
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 728 of file caja-freedesktop-generated.c.
References error, NULL, and proxy.
caja_freedesktop_file_manager1_call_show_items_sync()
gboolean caja_freedesktop_file_manager1_call_show_items_sync (CajaFreedesktopFileManager1 * proxy, const gchar *const * arg_URIs, const gchar * arg_StartupId, GCancellable * cancellable, GError ** error)
caja_freedesktop_file_manager1_call_show_items_sync: @proxy: A CajaFreedesktopFileManager1Proxy. @arg_URIs: Argument to pass with the method invocation. @arg_StartupId: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL.
Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-FileManager1.ShowItems">ShowItems()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
See caja_freedesktop_file_manager1_call_show_items() for the asynchronous version of this method.
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 759 of file caja-freedesktop-generated.c.
References error, NULL, and proxy.
caja_freedesktop_file_manager1_complete_show_folders()
void caja_freedesktop_file_manager1_complete_show_folders (CajaFreedesktopFileManager1 *object G_GNUC_UNUSED, GDBusMethodInvocation * invocation)
caja_freedesktop_file_manager1_complete_show_folders: @object: A CajaFreedesktopFileManager1. @invocation: (transfer full): A #GDBusMethodInvocation.
Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-FileManager1.ShowFolders">ShowFolders()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
This method will free @invocation, you cannot use it afterwards.
Definition at line 899 of file caja-freedesktop-generated.c.
caja_freedesktop_file_manager1_complete_show_item_properties()
void caja_freedesktop_file_manager1_complete_show_item_properties (CajaFreedesktopFileManager1 *object G_GNUC_UNUSED, GDBusMethodInvocation * invocation)
caja_freedesktop_file_manager1_complete_show_item_properties: @object: A CajaFreedesktopFileManager1. @invocation: (transfer full): A #GDBusMethodInvocation.
Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-FileManager1.ShowItemProperties">ShowItemProperties()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
This method will free @invocation, you cannot use it afterwards.
Definition at line 935 of file caja-freedesktop-generated.c.
caja_freedesktop_file_manager1_complete_show_items()
void caja_freedesktop_file_manager1_complete_show_items (CajaFreedesktopFileManager1 *object G_GNUC_UNUSED, GDBusMethodInvocation * invocation)
caja_freedesktop_file_manager1_complete_show_items: @object: A CajaFreedesktopFileManager1. @invocation: (transfer full): A #GDBusMethodInvocation.
Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-FileManager1.ShowItems">ShowItems()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
This method will free @invocation, you cannot use it afterwards.
Definition at line 917 of file caja-freedesktop-generated.c.
caja_freedesktop_file_manager1_interface_info()
GDBusInterfaceInfo * caja_freedesktop_file_manager1_interface_info (void)
caja_freedesktop_file_manager1_interface_info:
Gets a machine-readable description of the <link linkend="gdbus-interface-org-freedesktop-FileManager1.top_of_page">org.freedesktop.FileManager1</link> D-Bus interface.
Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
Definition at line 418 of file caja-freedesktop-generated.c.
caja_freedesktop_file_manager1_override_properties()
guint caja_freedesktop_file_manager1_override_properties (GObjectClass *klass G_GNUC_UNUSED, guint property_id_begin)
caja_freedesktop_file_manager1_override_properties: @klass: The class structure for a #GObject derived class. @property_id_begin: The property id to assign to the first overridden property.
Overrides all #GObject properties in the CajaFreedesktopFileManager1 interface for a concrete class. The properties are overridden in the order they are defined.
Returns: The last property id.
Definition at line 434 of file caja-freedesktop-generated.c.
caja_freedesktop_file_manager1_proxy_new()
void caja_freedesktop_file_manager1_proxy_new (GDBusConnection * connection, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 1124 of file caja-freedesktop-generated.c.
References CAJA_FREEDESKTOP_TYPE_FILE_MANAGER1_PROXY, connection, name, NULL, and user_data.
caja_freedesktop_file_manager1_proxy_new_finish()
CajaFreedesktopFileManager1 * caja_freedesktop_file_manager1_proxy_new_finish (GAsyncResult * res, GError ** error)
caja_freedesktop_file_manager1_proxy_new_finish: @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to caja_freedesktop_file_manager1_proxy_new(). @error: Return location for error or NULL
Finishes an operation started with caja_freedesktop_file_manager1_proxy_new().
Returns: (transfer full) (type CajaFreedesktopFileManager1Proxy): The constructed proxy object or NULL if @error is set.
Definition at line 1146 of file caja-freedesktop-generated.c.
References CAJA_FREEDESKTOP_FILE_MANAGER1, error, and NULL.
caja_freedesktop_file_manager1_proxy_new_for_bus()
void caja_freedesktop_file_manager1_proxy_new_for_bus (GBusType bus_type, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 1214 of file caja-freedesktop-generated.c.
References CAJA_FREEDESKTOP_TYPE_FILE_MANAGER1_PROXY, name, NULL, and user_data.
caja_freedesktop_file_manager1_proxy_new_for_bus_finish()
CajaFreedesktopFileManager1 * caja_freedesktop_file_manager1_proxy_new_for_bus_finish (GAsyncResult * res, GError ** error)
caja_freedesktop_file_manager1_proxy_new_for_bus_finish: @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to caja_freedesktop_file_manager1_proxy_new_for_bus(). @error: Return location for error or NULL
Finishes an operation started with caja_freedesktop_file_manager1_proxy_new_for_bus().
Returns: (transfer full) (type CajaFreedesktopFileManager1Proxy): The constructed proxy object or NULL if @error is set.
Definition at line 1236 of file caja-freedesktop-generated.c.
References CAJA_FREEDESKTOP_FILE_MANAGER1, error, and NULL.
caja_freedesktop_file_manager1_proxy_new_for_bus_sync()
CajaFreedesktopFileManager1 * caja_freedesktop_file_manager1_proxy_new_for_bus_sync (GBusType bus_type, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GError ** error)
Definition at line 1269 of file caja-freedesktop-generated.c.
References CAJA_FREEDESKTOP_FILE_MANAGER1, CAJA_FREEDESKTOP_TYPE_FILE_MANAGER1_PROXY, error, name, and NULL.
caja_freedesktop_file_manager1_proxy_new_sync()
CajaFreedesktopFileManager1 * caja_freedesktop_file_manager1_proxy_new_sync (GDBusConnection * connection, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GError ** error)
Definition at line 1179 of file caja-freedesktop-generated.c.
References CAJA_FREEDESKTOP_FILE_MANAGER1, CAJA_FREEDESKTOP_TYPE_FILE_MANAGER1_PROXY, connection, error, name, and NULL.
caja_freedesktop_file_manager1_skeleton_new()
CajaFreedesktopFileManager1 * caja_freedesktop_file_manager1_skeleton_new (void)
caja_freedesktop_file_manager1_skeleton_new:
Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-FileManager1.top_of_page">org.freedesktop.FileManager1</link>.
Returns: (transfer full) (type CajaFreedesktopFileManager1Skeleton): The skeleton object.
Definition at line 1567 of file caja-freedesktop-generated.c.
References CAJA_FREEDESKTOP_FILE_MANAGER1, CAJA_FREEDESKTOP_TYPE_FILE_MANAGER1_SKELETON, and NULL.
caja_freedesktop_object_get_file_manager1()
CajaFreedesktopFileManager1 * caja_freedesktop_object_get_file_manager1 (CajaFreedesktopObject * object)
caja_freedesktop_object_get_file_manager1: @object: A CajaFreedesktopObject.
Gets the CajaFreedesktopFileManager1 instance for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-FileManager1.top_of_page">org.freedesktop.FileManager1</link> on @object, if any.
Returns: (transfer full) (nullable): A CajaFreedesktopFileManager1 that must be freed with g_object_unref() or NULL if @object does not implement the interface.
Definition at line 1623 of file caja-freedesktop-generated.c.
References CAJA_FREEDESKTOP_FILE_MANAGER1, and NULL.
caja_freedesktop_object_manager_client_get_proxy_type()
GType caja_freedesktop_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager G_GNUC_UNUSED, const gchar *object_path G_GNUC_UNUSED, const gchar * interface_name, gpointer user_data G_GNUC_UNUSED)
caja_freedesktop_object_manager_client_get_proxy_type: @manager: A #GDBusObjectManagerClient. @object_path: The object path of the remote object (unused). @interface_name: (nullable): Interface name of the remote object or NULL to get the object proxy #GType. @user_data: User data (unused).
A #GDBusProxyTypeFunc that maps @interface_name to the generated #GDBusObjectProxy derived and #GDBusProxy derived types.
Returns: A #GDBusProxy derived #GType if @interface_name is not NULL, otherwise the #GType for CajaFreedesktopObjectProxy.
Definition at line 1936 of file caja-freedesktop-generated.c.
References CAJA_FREEDESKTOP_TYPE_FILE_MANAGER1_PROXY, CAJA_FREEDESKTOP_TYPE_OBJECT_PROXY, NULL, and user_data.
Referenced by caja_freedesktop_object_manager_client_new(), caja_freedesktop_object_manager_client_new_for_bus(), caja_freedesktop_object_manager_client_new_for_bus_sync(), and caja_freedesktop_object_manager_client_new_sync().
caja_freedesktop_object_manager_client_new()
void caja_freedesktop_object_manager_client_new (GDBusConnection * connection, GDBusObjectManagerClientFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 1974 of file caja-freedesktop-generated.c.
References caja_freedesktop_object_manager_client_get_proxy_type(), CAJA_FREEDESKTOP_TYPE_OBJECT_MANAGER_CLIENT, connection, name, NULL, and user_data.
caja_freedesktop_object_manager_client_new_finish()
GDBusObjectManager * caja_freedesktop_object_manager_client_new_finish (GAsyncResult * res, GError ** error)
caja_freedesktop_object_manager_client_new_finish: @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to caja_freedesktop_object_manager_client_new(). @error: Return location for error or NULL
Finishes an operation started with caja_freedesktop_object_manager_client_new().
Returns: (transfer full) (type CajaFreedesktopObjectManagerClient): The constructed object manager client or NULL if @error is set.
Definition at line 1996 of file caja-freedesktop-generated.c.
References error, and NULL.
caja_freedesktop_object_manager_client_new_for_bus()
void caja_freedesktop_object_manager_client_new_for_bus (GBusType bus_type, GDBusObjectManagerClientFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 2064 of file caja-freedesktop-generated.c.
References caja_freedesktop_object_manager_client_get_proxy_type(), CAJA_FREEDESKTOP_TYPE_OBJECT_MANAGER_CLIENT, name, NULL, and user_data.
caja_freedesktop_object_manager_client_new_for_bus_finish()
GDBusObjectManager * caja_freedesktop_object_manager_client_new_for_bus_finish (GAsyncResult * res, GError ** error)
caja_freedesktop_object_manager_client_new_for_bus_finish: @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to caja_freedesktop_object_manager_client_new_for_bus(). @error: Return location for error or NULL
Finishes an operation started with caja_freedesktop_object_manager_client_new_for_bus().
Returns: (transfer full) (type CajaFreedesktopObjectManagerClient): The constructed object manager client or NULL if @error is set.
Definition at line 2086 of file caja-freedesktop-generated.c.
References error, and NULL.
caja_freedesktop_object_manager_client_new_for_bus_sync()
GDBusObjectManager * caja_freedesktop_object_manager_client_new_for_bus_sync (GBusType bus_type, GDBusObjectManagerClientFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GError ** error)
Definition at line 2119 of file caja-freedesktop-generated.c.
References caja_freedesktop_object_manager_client_get_proxy_type(), CAJA_FREEDESKTOP_TYPE_OBJECT_MANAGER_CLIENT, error, name, and NULL.
caja_freedesktop_object_manager_client_new_sync()
GDBusObjectManager * caja_freedesktop_object_manager_client_new_sync (GDBusConnection * connection, GDBusObjectManagerClientFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GError ** error)
Definition at line 2029 of file caja-freedesktop-generated.c.
References caja_freedesktop_object_manager_client_get_proxy_type(), CAJA_FREEDESKTOP_TYPE_OBJECT_MANAGER_CLIENT, connection, error, name, and NULL.
caja_freedesktop_object_peek_file_manager1()
CajaFreedesktopFileManager1 * caja_freedesktop_object_peek_file_manager1 (CajaFreedesktopObject * object)
caja_freedesktop_object_peek_file_manager1: (skip) @object: A CajaFreedesktopObject.
Like caja_freedesktop_object_get_file_manager1() but doesn't increase the reference count on the returned object.
It is not safe to use the returned object if you are on another thread than the one where the #GDBusObjectManagerClient or #GDBusObjectManagerServer for @object is running.
Returns: (transfer none) (nullable): A CajaFreedesktopFileManager1 or NULL if @object does not implement the interface. Do not free the returned object, it is owned by @object.
Definition at line 1643 of file caja-freedesktop-generated.c.
References CAJA_FREEDESKTOP_FILE_MANAGER1, and NULL.
caja_freedesktop_object_proxy_new()
CajaFreedesktopObjectProxy * caja_freedesktop_object_proxy_new (GDBusConnection * connection, const gchar * object_path)
caja_freedesktop_object_proxy_new: @connection: A #GDBusConnection. @object_path: An object path.
Creates a new proxy object.
Returns: (transfer full): The proxy object.
Definition at line 1752 of file caja-freedesktop-generated.c.
References CAJA_FREEDESKTOP_OBJECT_PROXY, CAJA_FREEDESKTOP_TYPE_OBJECT_PROXY, connection, and NULL.
caja_freedesktop_object_skeleton_new()
CajaFreedesktopObjectSkeleton * caja_freedesktop_object_skeleton_new (const gchar * object_path)
caja_freedesktop_object_skeleton_new: @object_path: An object path.
Creates a new skeleton object.
Returns: (transfer full): The skeleton object.
Definition at line 1867 of file caja-freedesktop-generated.c.
References CAJA_FREEDESKTOP_OBJECT_SKELETON, CAJA_FREEDESKTOP_TYPE_OBJECT_SKELETON, and NULL.
caja_freedesktop_object_skeleton_set_file_manager1()
void caja_freedesktop_object_skeleton_set_file_manager1 (CajaFreedesktopObjectSkeleton * object, CajaFreedesktopFileManager1 * interface_)
caja_freedesktop_object_skeleton_set_file_manager1: @object: A CajaFreedesktopObjectSkeleton. @interface_: (nullable): A CajaFreedesktopFileManager1 or NULL to clear the interface.
Sets the CajaFreedesktopFileManager1 instance for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-FileManager1.top_of_page">org.freedesktop.FileManager1</link> on @object.
Definition at line 1880 of file caja-freedesktop-generated.c.
References NULL.
G_DEFINE_TYPE_WITH_CODE() [1/4]
G_DEFINE_TYPE_WITH_CODE (CajaFreedesktopFileManager1Proxy , caja_freedesktop_file_manager1_proxy , G_TYPE_DBUS_PROXY , G_IMPLEMENT_INTERFACE(CAJA_FREEDESKTOP_TYPE_FILE_MANAGER1, caja_freedesktop_file_manager1_proxy_iface_init))
Definition at line 966 of file caja-freedesktop-generated.c.
References CAJA_FREEDESKTOP_FILE_MANAGER1_PROXY, CAJA_FREEDESKTOP_TYPE_FILE_MANAGER1, G_OBJECT_CLASS(), and proxy.
G_DEFINE_TYPE_WITH_CODE() [2/4]
G_DEFINE_TYPE_WITH_CODE (CajaFreedesktopFileManager1Skeleton , caja_freedesktop_file_manager1_skeleton , G_TYPE_DBUS_INTERFACE_SKELETON , G_IMPLEMENT_INTERFACE(CAJA_FREEDESKTOP_TYPE_FILE_MANAGER1, caja_freedesktop_file_manager1_skeleton_iface_init))
Definition at line 1500 of file caja-freedesktop-generated.c.
References CAJA_FREEDESKTOP_FILE_MANAGER1_SKELETON, CAJA_FREEDESKTOP_TYPE_FILE_MANAGER1, G_OBJECT_CLASS(), NULL, and _CajaFreedesktopFileManager1Skeleton::priv.
G_DEFINE_TYPE_WITH_CODE() [3/4]
G_DEFINE_TYPE_WITH_CODE (CajaFreedesktopObjectProxy , caja_freedesktop_object_proxy , G_TYPE_DBUS_OBJECT_PROXY , G_IMPLEMENT_INTERFACE(G_TYPE_DBUS_OBJECT, caja_freedesktop_object_proxy__g_dbus_object_iface_init))
Definition at line 1691 of file caja-freedesktop-generated.c.
References CAJA_FREEDESKTOP_TYPE_OBJECT.
G_DEFINE_TYPE_WITH_CODE() [4/4]
G_DEFINE_TYPE_WITH_CODE (CajaFreedesktopObjectSkeleton , caja_freedesktop_object_skeleton , G_TYPE_DBUS_OBJECT_SKELETON , G_IMPLEMENT_INTERFACE(G_TYPE_DBUS_OBJECT, caja_freedesktop_object_skeleton__g_dbus_object_iface_init))
Definition at line 1786 of file caja-freedesktop-generated.c.
References CAJA_FREEDESKTOP_TYPE_OBJECT.