MATE Desktop Environment: caja-window-pane.h File Reference
caja-window-pane.h File Reference
#include "caja-window.h"
Classes
struct _CajaWindowPaneClass
struct _CajaWindowPane
Macros
#define CAJA_TYPE_WINDOW_PANE (caja_window_pane_get_type())
#define CAJA_WINDOW_PANE_CLASS(k)
#define CAJA_WINDOW_PANE(obj)
#define CAJA_IS_WINDOW_PANE(obj)
#define CAJA_IS_WINDOW_PANE_CLASS(k)
#define CAJA_WINDOW_PANE_GET_CLASS(o)
Typedefs
typedef struct _CajaWindowPaneClass CajaWindowPaneClass
Functions
GType caja_window_pane_get_type (void)
CajaWindowPane * caja_window_pane_new (CajaWindow *window)
void caja_window_pane_show (CajaWindowPane *pane)
void caja_window_pane_zoom_in (CajaWindowPane *pane)
void caja_window_pane_zoom_to_level (CajaWindowPane *pane, CajaZoomLevel level)
void caja_window_pane_zoom_out (CajaWindowPane *pane)
void caja_window_pane_zoom_to_default (CajaWindowPane *pane)
void caja_window_pane_sync_location_widgets (CajaWindowPane *pane)
void caja_window_pane_sync_search_widgets (CajaWindowPane *pane)
void caja_window_pane_set_active (CajaWindowPane *pane, gboolean is_active)
void caja_window_pane_slot_close (CajaWindowPane *pane, CajaWindowSlot *slot)
CajaWindowSlot * caja_window_pane_get_slot_for_content_box (CajaWindowPane *pane, GtkWidget *content_box)
void caja_window_pane_switch_to (CajaWindowPane *pane)
void caja_window_pane_grab_focus (CajaWindowPane *pane)
Macro Definition Documentation
CAJA_IS_WINDOW_PANE
#define CAJA_IS_WINDOW_PANE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_WINDOW_PANE))
Definition at line 33 of file caja-window-pane.h.
Referenced by caja_window_close_pane(), caja_window_close_slot(), caja_window_open_slot(), caja_window_pane_grab_focus(), caja_window_pane_sync_search_widgets(), caja_window_set_active_pane(), and caja_window_set_active_slot().
CAJA_IS_WINDOW_PANE_CLASS
#define CAJA_IS_WINDOW_PANE_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), CAJA_TYPE_WINDOW_PANE))
Definition at line 34 of file caja-window-pane.h.
CAJA_TYPE_WINDOW_PANE
#define CAJA_TYPE_WINDOW_PANE (caja_window_pane_get_type())
Definition at line 30 of file caja-window-pane.h.
Referenced by caja_window_pane_new(), and G_DEFINE_TYPE().
CAJA_WINDOW_PANE
#define CAJA_WINDOW_PANE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_WINDOW_PANE, CajaWindowPane))
Definition at line 32 of file caja-window-pane.h.
Referenced by caja_location_bar_new(), caja_navigation_window_pane_hide_location_bar(), caja_navigation_window_pane_hide_temporary_bars(), caja_navigation_window_pane_new(), caja_navigation_window_pane_set_bar_mode(), caja_navigation_window_pane_setup(), caja_navigation_window_pane_show_location_bar(), caja_navigation_window_split_view_on(), and caja_window_pane_slot_close().
CAJA_WINDOW_PANE_CLASS
#define CAJA_WINDOW_PANE_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST((k), CAJA_TYPE_WINDOW_PANE, CajaWindowPaneClass))
Definition at line 31 of file caja-window-pane.h.
Referenced by caja_window_pane_set_active(), caja_window_pane_show(), caja_window_pane_sync_location_widgets(), and caja_window_pane_sync_search_widgets().
CAJA_WINDOW_PANE_GET_CLASS
#define CAJA_WINDOW_PANE_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), CAJA_TYPE_WINDOW_PANE, CajaWindowPaneClass))
Definition at line 35 of file caja-window-pane.h.
Typedef Documentation
CajaWindowPaneClass
typedef struct _CajaWindowPaneClass CajaWindowPaneClass
Definition at line 37 of file caja-window-pane.h.
Function Documentation
caja_window_pane_get_slot_for_content_box()
CajaWindowSlot * caja_window_pane_get_slot_for_content_box (CajaWindowPane * pane, GtkWidget * content_box)
Definition at line 286 of file caja-window-pane.c.
References CAJA_WINDOW_SLOT, CajaWindowSlot::content_box, NULL, and _CajaWindowPane::slots.
caja_window_pane_get_type()
GType caja_window_pane_get_type (void)
References level.
caja_window_pane_grab_focus()
void caja_window_pane_grab_focus (CajaWindowPane * pane)
Definition at line 217 of file caja-window-pane.c.
References _CajaWindowPane::active_slot, CAJA_IS_WINDOW_PANE, caja_view_grab_focus(), and CajaWindowSlot::content_view.
Referenced by caja_window_pane_switch_to().
caja_window_pane_new()
CajaWindowPane * caja_window_pane_new (CajaWindow * window)
Definition at line 276 of file caja-window-pane.c.
References CAJA_TYPE_WINDOW_PANE, NULL, and _CajaWindowPane::window.
caja_window_pane_set_active()
void caja_window_pane_set_active (CajaWindowPane * pane, gboolean is_active)
Definition at line 241 of file caja-window-pane.c.
References _CajaWindowPane::active_slot, CAJA_WINDOW_PANE_CLASS, caja_window_slot_is_in_active_pane(), EEL_CALL_METHOD, and _CajaWindowPane::is_active.
caja_window_pane_show()
void caja_window_pane_show (CajaWindowPane * pane)
Definition at line 58 of file caja-window-pane.c.
References CAJA_WINDOW_PANE_CLASS, EEL_CALL_METHOD, TRUE, and _CajaWindowPane::visible.
caja_window_pane_slot_close()
void caja_window_pane_slot_close (CajaWindowPane * pane, CajaWindowSlot * slot)
Definition at line 131 of file caja-window-pane.c.
References _CajaWindowPane::active_slot, _CajaWindowPane::active_slots, CAJA_IS_NAVIGATION_WINDOW, CAJA_NAVIGATION_WINDOW, caja_navigation_window_update_show_hide_menu_items(), caja_window_close(), caja_window_close_pane(), caja_window_close_slot(), caja_window_get_next_pane(), CAJA_WINDOW_PANE, caja_window_pane_switch_to(), caja_window_set_active_slot(), CAJA_WINDOW_SLOT, NULL, and _CajaWindowPane::window.
Referenced by caja_window_slot_close().
caja_window_pane_switch_to()
void caja_window_pane_switch_to (CajaWindowPane * pane)
Definition at line 226 of file caja-window-pane.c.
References caja_window_pane_grab_focus().
Referenced by caja_window_pane_slot_close().
caja_window_pane_sync_location_widgets()
void caja_window_pane_sync_location_widgets (CajaWindowPane * pane)
Definition at line 201 of file caja-window-pane.c.
References CAJA_WINDOW_PANE_CLASS, and EEL_CALL_METHOD.
caja_window_pane_sync_search_widgets()
void caja_window_pane_sync_search_widgets (CajaWindowPane * pane)
Definition at line 208 of file caja-window-pane.c.
References CAJA_IS_WINDOW_PANE, CAJA_WINDOW_PANE_CLASS, and EEL_CALL_METHOD.
caja_window_pane_zoom_in()
void caja_window_pane_zoom_in (CajaWindowPane * pane)
Definition at line 66 of file caja-window-pane.c.
References _CajaWindowPane::active_slot, caja_view_bump_zoom_level(), caja_window_set_active_pane(), CajaWindowSlot::content_view, NULL, and _CajaWindowPane::window.
Referenced by caja_window_zoom_in().
caja_window_pane_zoom_out()
void caja_window_pane_zoom_out (CajaWindowPane * pane)
Definition at line 99 of file caja-window-pane.c.
References _CajaWindowPane::active_slot, caja_view_bump_zoom_level(), caja_window_set_active_pane(), CajaWindowSlot::content_view, NULL, and _CajaWindowPane::window.
Referenced by caja_window_zoom_out().
caja_window_pane_zoom_to_default()
void caja_window_pane_zoom_to_default (CajaWindowPane * pane)
Definition at line 115 of file caja-window-pane.c.
References _CajaWindowPane::active_slot, caja_view_restore_default_zoom_level(), caja_window_set_active_pane(), CajaWindowSlot::content_view, NULL, and _CajaWindowPane::window.
Referenced by caja_window_zoom_to_default().
caja_window_pane_zoom_to_level()
void caja_window_pane_zoom_to_level (CajaWindowPane * pane, CajaZoomLevel level)
Definition at line 82 of file caja-window-pane.c.
References _CajaWindowPane::active_slot, caja_view_zoom_to_level(), caja_window_set_active_pane(), CajaWindowSlot::content_view, level, NULL, and _CajaWindowPane::window.
Referenced by caja_window_zoom_to_level().