MATE Desktop Environment: caja-bookmark-list.h File Reference
caja-bookmark-list.h File Reference
#include <gio/gio.h>
#include <libcaja-private/caja-bookmark.h>
Classes
struct CajaBookmarkList
struct CajaBookmarkListClass
Macros
#define CAJA_TYPE_BOOKMARK_LIST caja_bookmark_list_get_type()
#define CAJA_BOOKMARK_LIST(obj)
#define CAJA_BOOKMARK_LIST_CLASS(klass)
#define CAJA_IS_BOOKMARK_LIST(obj)
#define CAJA_IS_BOOKMARK_LIST_CLASS(klass)
#define CAJA_BOOKMARK_LIST_GET_CLASS(obj)
Typedefs
typedef struct CajaBookmarkList CajaBookmarkList
typedef struct CajaBookmarkListClass CajaBookmarkListClass
Functions
GType caja_bookmark_list_get_type (void)
CajaBookmarkList * caja_bookmark_list_new (void)
void caja_bookmark_list_append (CajaBookmarkList *bookmarks, CajaBookmark *bookmark)
gboolean caja_bookmark_list_contains (CajaBookmarkList *bookmarks, CajaBookmark *bookmark)
void caja_bookmark_list_delete_item_at (CajaBookmarkList *bookmarks, guint index)
void caja_bookmark_list_delete_items_with_uri (CajaBookmarkList *bookmarks, const char *uri)
void caja_bookmark_list_insert_item (CajaBookmarkList *bookmarks, CajaBookmark *bookmark, guint index)
guint caja_bookmark_list_length (CajaBookmarkList *bookmarks)
CajaBookmark * caja_bookmark_list_item_at (CajaBookmarkList *bookmarks, guint index)
void caja_bookmark_list_move_item (CajaBookmarkList *bookmarks, guint index, guint destination)
void caja_bookmark_list_set_window_geometry (CajaBookmarkList *bookmarks, const char *geometry)
const char * caja_bookmark_list_get_window_geometry (CajaBookmarkList *bookmarks)
Macro Definition Documentation
CAJA_BOOKMARK_LIST
#define CAJA_BOOKMARK_LIST (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_BOOKMARK_LIST, CajaBookmarkList))
Definition at line 39 of file caja-bookmark-list.h.
Referenced by caja_bookmark_list_new().
CAJA_BOOKMARK_LIST_CLASS
#define CAJA_BOOKMARK_LIST_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_BOOKMARK_LIST, CajaBookmarkListClass))
Definition at line 41 of file caja-bookmark-list.h.
CAJA_BOOKMARK_LIST_GET_CLASS
#define CAJA_BOOKMARK_LIST_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_BOOKMARK_LIST, CajaBookmarkListClass))
Definition at line 47 of file caja-bookmark-list.h.
CAJA_IS_BOOKMARK_LIST
#define CAJA_IS_BOOKMARK_LIST (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_BOOKMARK_LIST))
Definition at line 43 of file caja-bookmark-list.h.
Referenced by caja_bookmark_list_append(), caja_bookmark_list_contains(), caja_bookmark_list_delete_item_at(), caja_bookmark_list_delete_items_with_uri(), caja_bookmark_list_insert_item(), caja_bookmark_list_item_at(), caja_bookmark_list_length(), caja_bookmark_list_set_window_geometry(), and caja_bookmarks_window_save_geometry().
CAJA_IS_BOOKMARK_LIST_CLASS
#define CAJA_IS_BOOKMARK_LIST_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_BOOKMARK_LIST))
Definition at line 45 of file caja-bookmark-list.h.
CAJA_TYPE_BOOKMARK_LIST
#define CAJA_TYPE_BOOKMARK_LIST caja_bookmark_list_get_type()
Definition at line 38 of file caja-bookmark-list.h.
Referenced by caja_bookmark_list_new().
Typedef Documentation
CajaBookmarkList
typedef struct CajaBookmarkList CajaBookmarkList
Definition at line 35 of file caja-bookmark-list.h.
CajaBookmarkListClass
typedef struct CajaBookmarkListClass CajaBookmarkListClass
Definition at line 36 of file caja-bookmark-list.h.
Function Documentation
caja_bookmark_list_append()
void caja_bookmark_list_append (CajaBookmarkList * bookmarks, CajaBookmark * bookmark)
caja_bookmark_list_append:
Append a bookmark to a bookmark list. @bookmarks: CajaBookmarkList to append to. @bookmark: Bookmark to append a copy of.
Definition at line 302 of file caja-bookmark-list.c.
References caja_bookmark_copy(), CAJA_IS_BOOKMARK, and CAJA_IS_BOOKMARK_LIST.
Referenced by caja_window_add_bookmark_for_current_location().
caja_bookmark_list_contains()
gboolean caja_bookmark_list_contains (CajaBookmarkList * bookmarks, CajaBookmark * bookmark)
caja_bookmark_list_contains:
Check whether a bookmark with matching name and url is already in the list. @bookmarks: CajaBookmarkList to check contents of. @bookmark: CajaBookmark to match against.
Return value: TRUE if matching bookmark is in list, FALSE otherwise
Definition at line 325 of file caja-bookmark-list.c.
References caja_bookmark_compare_with(), CAJA_IS_BOOKMARK, CAJA_IS_BOOKMARK_LIST, FALSE, and NULL.
Referenced by caja_window_add_bookmark_for_current_location().
caja_bookmark_list_delete_item_at()
void caja_bookmark_list_delete_item_at (CajaBookmarkList * bookmarks, guint index)
caja_bookmark_list_delete_item_at:
Delete the bookmark at the specified position. @bookmarks: the list of bookmarks. @index: index, must be less than length of list.
Definition at line 345 of file caja-bookmark-list.c.
References CAJA_BOOKMARK, CAJA_IS_BOOKMARK, CAJA_IS_BOOKMARK_LIST, and NULL.
caja_bookmark_list_delete_items_with_uri()
void caja_bookmark_list_delete_items_with_uri (CajaBookmarkList * bookmarks, const char * uri)
caja_bookmark_list_delete_items_with_uri:
Delete all bookmarks with the given uri. @bookmarks: the list of bookmarks. @uri: The uri to match.
Definition at line 416 of file caja-bookmark-list.c.
References CAJA_BOOKMARK, caja_bookmark_get_uri(), CAJA_IS_BOOKMARK_LIST, FALSE, NULL, and TRUE.
caja_bookmark_list_get_type()
GType caja_bookmark_list_get_type (void)
caja_bookmark_list_get_window_geometry()
const char * caja_bookmark_list_get_window_geometry (CajaBookmarkList * bookmarks)
caja_bookmark_list_get_window_geometry:
Get a string representing the bookmark_list's window's geometry. This is the value set earlier by caja_bookmark_list_set_window_geometry. @bookmarks: the list of bookmarks associated with the window. Return value: string representation of window's geometry, suitable for passing to mate_parse_geometry(), or NULL if no window geometry has yet been saved for this bookmark list.
Definition at line 461 of file caja-bookmark-list.c.
caja_bookmark_list_insert_item()
void caja_bookmark_list_insert_item (CajaBookmarkList * bookmarks, CajaBookmark * new_bookmark, guint index)
caja_bookmark_list_insert_item:
Insert a bookmark at a specified position. @bookmarks: the list of bookmarks. @index: the position to insert the bookmark at. @new_bookmark: the bookmark to insert a copy of.
Definition at line 475 of file caja-bookmark-list.c.
References caja_bookmark_copy(), and CAJA_IS_BOOKMARK_LIST.
caja_bookmark_list_item_at()
CajaBookmark * caja_bookmark_list_item_at (CajaBookmarkList * bookmarks, guint index)
caja_bookmark_list_item_at:
Get the bookmark at the specified position. @bookmarks: the list of bookmarks. @index: index, must be less than length of list.
Return value: the bookmark at position @index in @bookmarks.
Definition at line 499 of file caja-bookmark-list.c.
References CAJA_BOOKMARK, CAJA_IS_BOOKMARK_LIST, and NULL.
caja_bookmark_list_length()
guint caja_bookmark_list_length (CajaBookmarkList * bookmarks)
caja_bookmark_list_length:
Get the number of bookmarks in the list. @bookmarks: the list of bookmarks.
Return value: the length of the bookmark list.
Definition at line 516 of file caja-bookmark-list.c.
References CAJA_IS_BOOKMARK_LIST.
caja_bookmark_list_move_item()
void caja_bookmark_list_move_item (CajaBookmarkList * bookmarks, guint index, guint destination)
caja_bookmark_list_move_item:
Move the item from the given position to the destination. @index: the index of the first bookmark. @destination: the index of the second bookmark.
Definition at line 375 of file caja-bookmark-list.c.
References NULL.
caja_bookmark_list_new()
CajaBookmarkList * caja_bookmark_list_new (void)
caja_bookmark_list_new:
Create a new bookmark_list, with contents read from disk.
Return value: A pointer to the new widget.
Definition at line 780 of file caja-bookmark-list.c.
References CAJA_BOOKMARK_LIST, CAJA_TYPE_BOOKMARK_LIST, and NULL.
caja_bookmark_list_set_window_geometry()
void caja_bookmark_list_set_window_geometry (CajaBookmarkList * bookmarks, const char * geometry)
caja_bookmark_list_set_window_geometry:
Set a bookmarks window's geometry (position & size), in string form. This is stored to disk by this class, and can be retrieved later in the same session or in a future session. @bookmarks: the list of bookmarks associated with the window. @geometry: the new window geometry string.
Definition at line 799 of file caja-bookmark-list.c.
References CAJA_IS_BOOKMARK_LIST, and NULL.
Referenced by caja_bookmarks_window_save_geometry().