MATE Desktop Environment: caja-file-operations.h File Reference
caja-file-operations.h File Reference
#include <gtk/gtk.h>
#include <gio/gio.h>
Typedefs
typedef void(* CajaCopyCallback) (GHashTable *debuting_uris, gpointer callback_data)
typedef void(* CajaCreateCallback) (GFile *new_file, gpointer callback_data)
typedef void(* CajaOpCallback) (gpointer callback_data)
typedef void(* CajaDeleteCallback) (GHashTable *debuting_uris, gboolean user_cancel, gpointer callback_data)
typedef void(* CajaMountCallback) (GVolume *volume, GObject *callback_data_object)
typedef void(* CajaUnmountCallback) (gpointer callback_data)
Functions
void caja_file_operations_copy_move (const GList *item_uris, GArray *relative_item_points, const char *target_dir_uri, GdkDragAction copy_action, GtkWidget *parent_view, CajaCopyCallback done_callback, gpointer done_callback_data)
void caja_file_operations_empty_trash (GtkWidget *parent_view)
void caja_file_operations_new_folder (GtkWidget *parent_view, GdkPoint *target_point, const char *parent_dir_uri, CajaCreateCallback done_callback, gpointer done_callback_data)
void caja_file_operations_new_file (GtkWidget *parent_view, GdkPoint *target_point, const char *parent_dir, const char *target_filename, const char *initial_contents, int length, CajaCreateCallback done_callback, gpointer data)
void caja_file_operations_new_file_from_template (GtkWidget *parent_view, GdkPoint *target_point, const char *parent_dir, const char *target_filename, const char *template_uri, CajaCreateCallback done_callback, gpointer data)
void caja_file_operations_delete (GList *files, GtkWindow *parent_window, CajaDeleteCallback done_callback, gpointer done_callback_data)
void caja_file_operations_trash_or_delete (GList *files, GtkWindow *parent_window, CajaDeleteCallback done_callback, gpointer done_callback_data)
void caja_file_set_permissions_recursive (const char *directory, guint32 file_permissions, guint32 file_mask, guint32 folder_permissions, guint32 folder_mask, CajaOpCallback callback, gpointer callback_data)
void caja_file_operations_unmount_mount (GtkWindow *parent_window, GMount *mount, gboolean eject, gboolean check_trash)
void caja_file_operations_unmount_mount_full (GtkWindow *parent_window, GMount *mount, gboolean eject, gboolean check_trash, CajaUnmountCallback callback, gpointer callback_data)
void caja_file_operations_mount_volume (GtkWindow *parent_window, GVolume *volume, gboolean allow_autorun)
void caja_file_operations_mount_volume_full (GtkWindow *parent_window, GVolume *volume, gboolean allow_autorun, CajaMountCallback mount_callback, GObject *mount_callback_data_object)
void caja_file_operations_copy (GList *files, GArray *relative_item_points, GFile *target_dir, GtkWindow *parent_window, CajaCopyCallback done_callback, gpointer done_callback_data)
void caja_file_operations_move (GList *files, GArray *relative_item_points, GFile *target_dir, GtkWindow *parent_window, CajaCopyCallback done_callback, gpointer done_callback_data)
void caja_file_operations_duplicate (GList *files, GArray *relative_item_points, GtkWindow *parent_window, CajaCopyCallback done_callback, gpointer done_callback_data)
void caja_file_operations_link (GList *files, GArray *relative_item_points, GFile *target_dir, GtkWindow *parent_window, CajaCopyCallback done_callback, gpointer done_callback_data)
void caja_file_mark_desktop_file_trusted (GFile *file, GtkWindow *parent_window, gboolean interactive, CajaOpCallback done_callback, gpointer done_callback_data)
void caja_application_notify_unmount_show (const gchar *message)
Typedef Documentation
CajaCopyCallback
typedef void(* CajaCopyCallback) (GHashTable *debuting_uris, gpointer callback_data)
Definition at line 33 of file caja-file-operations.h.
CajaCreateCallback
typedef void(* CajaCreateCallback) (GFile *new_file, gpointer callback_data)
Definition at line 35 of file caja-file-operations.h.
CajaDeleteCallback
typedef void(* CajaDeleteCallback) (GHashTable *debuting_uris, gboolean user_cancel, gpointer callback_data)
Definition at line 38 of file caja-file-operations.h.
CajaMountCallback
typedef void(* CajaMountCallback) (GVolume *volume, GObject *callback_data_object)
Definition at line 41 of file caja-file-operations.h.
CajaOpCallback
typedef void(* CajaOpCallback) (gpointer callback_data)
Definition at line 37 of file caja-file-operations.h.
CajaUnmountCallback
typedef void(* CajaUnmountCallback) (gpointer callback_data)
Definition at line 43 of file caja-file-operations.h.
Function Documentation
caja_application_notify_unmount_show()
void caja_application_notify_unmount_show (const gchar * message)
Definition at line 198 of file caja-file-operations.c.
References caja_preferences, CAJA_PREFERENCES_SHOW_NOTIFICATIONS, message(), NULL, TRUE, and unmount_notify.
caja_file_mark_desktop_file_trusted()
void caja_file_mark_desktop_file_trusted (GFile * file, GtkWindow * parent_window, gboolean interactive, CajaOpCallback done_callback, gpointer done_callback_data)
Definition at line 6747 of file caja-file-operations.c.
References FALSE, NULL, op_job_new, and TRUE.
caja_file_operations_copy()
void caja_file_operations_copy (GList * files, GArray * relative_item_points, GFile * target_dir, GtkWindow * parent_window, CajaCopyCallback done_callback, gpointer done_callback_data)
Definition at line 4752 of file caja-file-operations.c.
References _, caja_get_desktop_location(), CAJA_UNDOSTACK_COPY, caja_undostack_manager_data_new(), caja_undostack_manager_data_set_dest_dir(), caja_undostack_manager_data_set_src_dir(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), FALSE, NULL, and op_job_new.
Referenced by caja_file_operations_copy_move(), caja_undostack_manager_redo(), and main().
caja_file_operations_copy_move()
void caja_file_operations_copy_move (const GList * item_uris, GArray * relative_item_points, const char * target_dir_uri, GdkDragAction copy_action, GtkWidget * parent_view, CajaCopyCallback done_callback, gpointer done_callback_data)
Definition at line 5889 of file caja-file-operations.c.
References caja_file_operations_copy(), caja_file_operations_duplicate(), caja_file_operations_link(), caja_file_operations_move(), caja_file_operations_trash_or_delete(), dest, FALSE, NULL, and TRUE.
Referenced by fm_directory_view_move_copy_items().
caja_file_operations_delete()
void caja_file_operations_delete (GList * files, GtkWindow * parent_window, CajaDeleteCallback done_callback, gpointer done_callback_data)
Definition at line 2120 of file caja-file-operations.c.
References FALSE.
Referenced by caja_undostack_manager_undo().
caja_file_operations_duplicate()
void caja_file_operations_duplicate (GList * files, GArray * relative_item_points, GtkWindow * parent_window, CajaCopyCallback done_callback, gpointer done_callback_data)
Definition at line 5655 of file caja-file-operations.c.
References CAJA_UNDOSTACK_DUPLICATE, caja_undostack_manager_data_new(), caja_undostack_manager_data_set_dest_dir(), caja_undostack_manager_data_set_src_dir(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), FALSE, NULL, and op_job_new.
Referenced by caja_file_operations_copy_move(), and caja_undostack_manager_redo().
caja_file_operations_empty_trash()
void caja_file_operations_empty_trash (GtkWidget * parent_view)
Definition at line 6515 of file caja-file-operations.c.
References _, FALSE, NULL, op_job_new, and TRUE.
caja_file_operations_link()
void caja_file_operations_link (GList * files, GArray * relative_item_points, GFile * target_dir, GtkWindow * parent_window, CajaCopyCallback done_callback, gpointer done_callback_data)
Definition at line 5614 of file caja-file-operations.c.
References CAJA_UNDOSTACK_CREATELINK, caja_undostack_manager_data_new(), caja_undostack_manager_data_set_dest_dir(), caja_undostack_manager_data_set_src_dir(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), FALSE, NULL, op_job_new, and TRUE.
Referenced by caja_file_operations_copy_move(), and caja_undostack_manager_redo().
caja_file_operations_mount_volume()
void caja_file_operations_mount_volume (GtkWindow * parent_window, GVolume * volume, gboolean allow_autorun)
Definition at line 2485 of file caja-file-operations.c.
References caja_file_operations_mount_volume_full(), and NULL.
caja_file_operations_mount_volume_full()
void caja_file_operations_mount_volume_full (GtkWindow * parent_window, GVolume * volume, gboolean allow_autorun, CajaMountCallback mount_callback, GObject * mount_callback_data_object)
Definition at line 2494 of file caja-file-operations.c.
References caja_allow_autorun_for_volume(), and NULL.
Referenced by caja_file_operations_mount_volume().
caja_file_operations_move()
void caja_file_operations_move (GList * files, GArray * relative_item_points, GFile * target_dir, GtkWindow * parent_window, CajaCopyCallback done_callback, gpointer done_callback_data)
Definition at line 5295 of file caja-file-operations.c.
References _, caja_undostack_manager_data_new(), caja_undostack_manager_data_set_dest_dir(), caja_undostack_manager_data_set_src_dir(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), CAJA_UNDOSTACK_MOVE, CAJA_UNDOSTACK_RESTOREFROMTRASH, data, FALSE, NULL, op_job_new, and TRUE.
Referenced by caja_file_operations_copy_move(), caja_restore_files_from_trash(), caja_undostack_manager_redo(), and caja_undostack_manager_undo().
caja_file_operations_new_file()
void caja_file_operations_new_file (GtkWidget * parent_view, GdkPoint * target_point, const char * parent_dir, const char * target_filename, const char * initial_contents, int length, CajaCreateCallback done_callback, gpointer data)
Definition at line 6373 of file caja-file-operations.c.
References CAJA_UNDOSTACK_CREATEEMPTYFILE, caja_undostack_manager_data_new(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), FALSE, NULL, op_job_new, target_filename, and TRUE.
Referenced by caja_undostack_manager_redo().
caja_file_operations_new_file_from_template()
void caja_file_operations_new_file_from_template (GtkWidget * parent_view, GdkPoint * target_point, const char * parent_dir, const char * target_filename, const char * template_uri, CajaCreateCallback done_callback, gpointer data)
Definition at line 6329 of file caja-file-operations.c.
References CAJA_UNDOSTACK_CREATEFILEFROMTEMPLATE, caja_undostack_manager_data_new(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), FALSE, NULL, op_job_new, target_filename, and TRUE.
Referenced by caja_undostack_manager_redo(), and fm_directory_view_new_file().
caja_file_operations_new_folder()
void caja_file_operations_new_folder (GtkWidget * parent_view, GdkPoint * target_point, const char * parent_dir_uri, CajaCreateCallback done_callback, gpointer done_callback_data)
Definition at line 6291 of file caja-file-operations.c.
References CAJA_UNDOSTACK_CREATEFOLDER, caja_undostack_manager_data_new(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), FALSE, NULL, op_job_new, and TRUE.
Referenced by caja_undostack_manager_redo(), and fm_directory_view_new_folder().
caja_file_operations_trash_or_delete()
void caja_file_operations_trash_or_delete (GList * files, GtkWindow * parent_window, CajaDeleteCallback done_callback, gpointer done_callback_data)
Definition at line 2109 of file caja-file-operations.c.
References TRUE.
Referenced by caja_file_operations_copy_move(), caja_undostack_manager_redo(), and caja_undostack_manager_undo().
caja_file_operations_unmount_mount()
void caja_file_operations_unmount_mount (GtkWindow * parent_window, GMount * mount, gboolean eject, gboolean check_trash)
Definition at line 2417 of file caja-file-operations.c.
References caja_file_operations_unmount_mount_full(), and NULL.
caja_file_operations_unmount_mount_full()
void caja_file_operations_unmount_mount_full (GtkWindow * parent_window, GMount * mount, gboolean eject, gboolean check_trash, CajaUnmountCallback callback, gpointer callback_data)
Definition at line 2363 of file caja-file-operations.c.
References data, eel_add_weak_pointer(), eel_remove_weak_pointer(), FALSE, NULL, op_job_new, and TRUE.
Referenced by caja_file_eject(), caja_file_operations_unmount_mount(), and caja_file_unmount().
caja_file_set_permissions_recursive()
void caja_file_set_permissions_recursive (const char * directory, guint32 file_permissions, guint32 file_mask, guint32 folder_permissions, guint32 folder_mask, CajaOpCallback callback, gpointer callback_data)
Definition at line 5822 of file caja-file-operations.c.
References caja_undostack_manager_data_new(), caja_undostack_manager_data_set_dest_dir(), caja_undostack_manager_data_set_recursive_permissions(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), CAJA_UNDOSTACK_RECURSIVESETPERMISSIONS, FALSE, NULL, op_job_new, and TRUE.
Referenced by caja_undostack_manager_redo().