MATE Desktop Environment: caja-side-pane.c File Reference
caja-side-pane.c File Reference
#include <config.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <eel/eel-glib-extensions.h>
#include <eel/eel-gtk-extensions.h>
#include <eel/eel-gtk-macros.h>
#include "caja-side-pane.h"
Enumerations
enum { CLOSE_REQUESTED , SWITCH_PAGE , LAST_SIGNAL }
Functions
CajaSidePane * caja_side_pane_new (void)
void caja_side_pane_add_panel (CajaSidePane *side_pane, GtkWidget *widget, const char *title, const char *tooltip)
void caja_side_pane_remove_panel (CajaSidePane *side_pane, GtkWidget *widget)
void caja_side_pane_show_panel (CajaSidePane *side_pane, GtkWidget *widget)
void caja_side_pane_set_panel_image (CajaSidePane *side_pane, GtkWidget *widget, GdkPixbuf *pixbuf)
GtkWidget * caja_side_pane_get_current_panel (CajaSidePane *side_pane)
GtkWidget * caja_side_pane_get_title (CajaSidePane *side_pane)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CLOSE_REQUESTED
SWITCH_PAGE
LAST_SIGNAL
Definition at line 59 of file caja-side-pane.c.
Function Documentation
caja_side_pane_add_panel()
void caja_side_pane_add_panel (CajaSidePane * side_pane, GtkWidget * widget, const char * title, const char * tooltip)
Definition at line 425 of file caja-side-pane.c.
References CAJA_IS_SIDE_PANE, CajaSidePane::details, eel_image_menu_item_new_from_icon(), and NULL.
Referenced by caja_navigation_window_add_sidebar_panel().
caja_side_pane_get_current_panel()
GtkWidget * caja_side_pane_get_current_panel (CajaSidePane * side_pane)
Definition at line 605 of file caja-side-pane.c.
References CajaSidePane::details.
caja_side_pane_get_title()
GtkWidget * caja_side_pane_get_title (CajaSidePane * side_pane)
Definition at line 614 of file caja-side-pane.c.
References CajaSidePane::details.
caja_side_pane_new()
CajaSidePane * caja_side_pane_new (void)
Definition at line 419 of file caja-side-pane.c.
References CAJA_SIDE_PANE, caja_side_pane_get_type(), and NULL.
caja_side_pane_remove_panel()
void caja_side_pane_remove_panel (CajaSidePane * side_pane, GtkWidget * widget)
Definition at line 467 of file caja-side-pane.c.
References CAJA_IS_SIDE_PANE, CajaSidePane::details, and NULL.
Referenced by caja_navigation_window_remove_sidebar_panel().
caja_side_pane_set_panel_image()
void caja_side_pane_set_panel_image (CajaSidePane * side_pane, GtkWidget * widget, GdkPixbuf * pixbuf)
Definition at line 561 of file caja-side-pane.c.
References CAJA_IS_SIDE_PANE, CajaSidePane::details, FALSE, and NULL.
Referenced by caja_navigation_window_add_sidebar_panel().
caja_side_pane_show_panel()
void caja_side_pane_show_panel (CajaSidePane * side_pane, GtkWidget * widget)
Definition at line 501 of file caja-side-pane.c.
References CAJA_IS_SIDE_PANE, CajaSidePane::details, and NULL.
Referenced by caja_navigation_window_add_sidebar_panel().