MATE Desktop Environment: caja-icon-canvas-item.h File Reference
caja-icon-canvas-item.h File Reference
#include <eel/eel-canvas.h>
#include <eel/eel-art-extensions.h>
Classes
struct CajaIconCanvasItem
struct CajaIconCanvasItemClass
Macros
#define CAJA_TYPE_ICON_CANVAS_ITEM caja_icon_canvas_item_get_type()
#define CAJA_ICON_CANVAS_ITEM(obj)
#define CAJA_ICON_CANVAS_ITEM_CLASS(klass)
#define CAJA_IS_ICON_CANVAS_ITEM(obj)
#define CAJA_IS_ICON_CANVAS_ITEM_CLASS(klass)
#define CAJA_ICON_CANVAS_ITEM_GET_CLASS(obj)
Typedefs
typedef struct CajaIconCanvasItem CajaIconCanvasItem
typedef struct CajaIconCanvasItemClass CajaIconCanvasItemClass
typedef struct _CajaIconCanvasItemPrivate CajaIconCanvasItemPrivate
Enumerations
enum CajaIconCanvasItemBoundsUsage { BOUNDS_USAGE_FOR_LAYOUT , BOUNDS_USAGE_FOR_ENTIRE_ITEM , BOUNDS_USAGE_FOR_DISPLAY }
Functions
GType caja_icon_canvas_item_get_type (void)
void caja_icon_canvas_item_set_image (CajaIconCanvasItem *item, GdkPixbuf *image)
cairo_surface_t * caja_icon_canvas_item_get_drag_surface (CajaIconCanvasItem *item)
void caja_icon_canvas_item_set_emblems (CajaIconCanvasItem *item, GList *emblem_pixbufs)
void caja_icon_canvas_item_set_show_stretch_handles (CajaIconCanvasItem *item, gboolean show_stretch_handles)
void caja_icon_canvas_item_set_attach_points (CajaIconCanvasItem *item, GdkPoint *attach_points, int n_attach_points)
void caja_icon_canvas_item_set_embedded_text_rect (CajaIconCanvasItem *item, const GdkRectangle *text_rect)
void caja_icon_canvas_item_set_embedded_text (CajaIconCanvasItem *item, const char *text)
double caja_icon_canvas_item_get_max_text_width (CajaIconCanvasItem *item)
const char * caja_icon_canvas_item_get_editable_text (CajaIconCanvasItem *icon_item)
void caja_icon_canvas_item_set_renaming (CajaIconCanvasItem *icon_item, gboolean state)
gboolean caja_icon_canvas_item_hit_test_rectangle (CajaIconCanvasItem *item, EelIRect canvas_rect)
gboolean caja_icon_canvas_item_hit_test_stretch_handles (CajaIconCanvasItem *item, EelDPoint world_point, GtkCornerType *corner)
void caja_icon_canvas_item_invalidate_label (CajaIconCanvasItem *item)
void caja_icon_canvas_item_invalidate_label_size (CajaIconCanvasItem *item)
EelDRect caja_icon_canvas_item_get_icon_rectangle (const CajaIconCanvasItem *item)
EelDRect caja_icon_canvas_item_get_text_rectangle (CajaIconCanvasItem *item, gboolean for_layout)
void caja_icon_canvas_item_get_bounds_for_layout (CajaIconCanvasItem *item, double *x1, double *y1, double *x2, double *y2)
void caja_icon_canvas_item_get_bounds_for_entire_item (CajaIconCanvasItem *item, double *x1, double *y1, double *x2, double *y2)
void caja_icon_canvas_item_update_bounds (CajaIconCanvasItem *item, double i2w_dx, double i2w_dy)
void caja_icon_canvas_item_set_is_visible (CajaIconCanvasItem *item, gboolean visible)
void caja_icon_canvas_item_set_entire_text (CajaIconCanvasItem *icon_item, gboolean entire_text)
Macro Definition Documentation
CAJA_ICON_CANVAS_ITEM
#define CAJA_ICON_CANVAS_ITEM (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_ICON_CANVAS_ITEM, CajaIconCanvasItem))
Definition at line 34 of file caja-icon-canvas-item.h.
Referenced by caja_icon_canvas_item_get_icon_rectangle(), and caja_icon_container_add().
CAJA_ICON_CANVAS_ITEM_CLASS
#define CAJA_ICON_CANVAS_ITEM_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_ICON_CANVAS_ITEM, CajaIconCanvasItemClass))
Definition at line 36 of file caja-icon-canvas-item.h.
CAJA_ICON_CANVAS_ITEM_GET_CLASS
#define CAJA_ICON_CANVAS_ITEM_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_ICON_CANVAS_ITEM, CajaIconCanvasItemClass))
Definition at line 42 of file caja-icon-canvas-item.h.
CAJA_IS_ICON_CANVAS_ITEM
#define CAJA_IS_ICON_CANVAS_ITEM (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_ICON_CANVAS_ITEM))
Definition at line 38 of file caja-icon-canvas-item.h.
Referenced by caja_icon_canvas_item_get_drag_surface(), caja_icon_canvas_item_get_editable_text(), caja_icon_canvas_item_get_icon_rectangle(), caja_icon_canvas_item_get_text_rectangle(), caja_icon_canvas_item_hit_test_rectangle(), caja_icon_canvas_item_hit_test_stretch_handles(), caja_icon_canvas_item_set_emblems(), caja_icon_canvas_item_set_image(), caja_icon_canvas_item_set_renaming(), and caja_icon_canvas_item_set_show_stretch_handles().
CAJA_IS_ICON_CANVAS_ITEM_CLASS
#define CAJA_IS_ICON_CANVAS_ITEM_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_ICON_CANVAS_ITEM))
Definition at line 40 of file caja-icon-canvas-item.h.
CAJA_TYPE_ICON_CANVAS_ITEM
#define CAJA_TYPE_ICON_CANVAS_ITEM caja_icon_canvas_item_get_type()
Definition at line 33 of file caja-icon-canvas-item.h.
Typedef Documentation
CajaIconCanvasItem
typedef struct CajaIconCanvasItem CajaIconCanvasItem
Definition at line 45 of file caja-icon-canvas-item.h.
CajaIconCanvasItemClass
typedef struct CajaIconCanvasItemClass CajaIconCanvasItemClass
Definition at line 46 of file caja-icon-canvas-item.h.
CajaIconCanvasItemPrivate
typedef struct _CajaIconCanvasItemPrivate CajaIconCanvasItemPrivate
Definition at line 47 of file caja-icon-canvas-item.h.
Enumeration Type Documentation
CajaIconCanvasItemBoundsUsage
enum CajaIconCanvasItemBoundsUsage
Enumerator
BOUNDS_USAGE_FOR_LAYOUT
BOUNDS_USAGE_FOR_ENTIRE_ITEM
BOUNDS_USAGE_FOR_DISPLAY
Definition at line 62 of file caja-icon-canvas-item.h.
Function Documentation
caja_icon_canvas_item_get_bounds_for_entire_item()
void caja_icon_canvas_item_get_bounds_for_entire_item (CajaIconCanvasItem * item, double * x1, double * y1, double * x2, double * y2)
Definition at line 2354 of file caja-icon-canvas-item.c.
References CajaIconCanvasItem::details, int(), NULL, EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
caja_icon_canvas_item_get_bounds_for_layout()
void caja_icon_canvas_item_get_bounds_for_layout (CajaIconCanvasItem * item, double * x1, double * y1, double * x2, double * y2)
Definition at line 2321 of file caja-icon-canvas-item.c.
References CajaIconCanvasItem::details, int(), NULL, EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
caja_icon_canvas_item_get_drag_surface()
cairo_surface_t * caja_icon_canvas_item_get_drag_surface (CajaIconCanvasItem * item)
Definition at line 531 of file caja-icon-canvas-item.c.
References CAJA_ICON_CONTAINER, caja_icon_container_is_layout_rtl(), CAJA_IS_ICON_CANVAS_ITEM, EEL_CANVAS_ITEM, eel_canvas_world_to_window(), FALSE, is_rtl, item, NULL, EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
caja_icon_canvas_item_get_editable_text()
const char * caja_icon_canvas_item_get_editable_text (CajaIconCanvasItem * icon_item)
Definition at line 2676 of file caja-icon-canvas-item.c.
References CAJA_IS_ICON_CANVAS_ITEM, CajaIconCanvasItem::details, and NULL.
Referenced by caja_icon_container_start_renaming_selected_item(), and caja_icon_container_update_icon().
caja_icon_canvas_item_get_icon_rectangle()
EelDRect caja_icon_canvas_item_get_icon_rectangle (const CajaIconCanvasItem * item)
Definition at line 2485 of file caja-icon-canvas-item.c.
References CAJA_ICON_CANVAS_ITEM, CAJA_IS_ICON_CANVAS_ITEM, EEL_CANVAS_ITEM, eel_canvas_item_i2w(), eel_drect_empty, item, EelDRect::x0, EelDRect::x1, EelDRect::y0, and EelDRect::y1.
Referenced by caja_icon_container_start_renaming_selected_item().
caja_icon_canvas_item_get_max_text_width()
double caja_icon_canvas_item_get_max_text_width (CajaIconCanvasItem * item)
Definition at line 2699 of file caja-icon-canvas-item.c.
References CajaIconContainerDetails::all_columns_same_width, CAJA_ICON_CONTAINER, caja_icon_container_is_tighter_layout(), CAJA_ICON_LABEL_POSITION_BESIDE, CAJA_ICON_LAYOUT_T_B_L_R, CAJA_ICON_LAYOUT_T_B_R_L, _EelCanvasItem::canvas, CajaIconContainer::details, EEL_CANVAS_ITEM, item, CajaIconContainerDetails::label_position, CajaIconContainerDetails::layout_mode, MAX_TEXT_WIDTH_BESIDE, MAX_TEXT_WIDTH_BESIDE_TOP_TO_BOTTOM, MAX_TEXT_WIDTH_STANDARD, MAX_TEXT_WIDTH_TIGHTER, and _EelCanvas::pixels_per_unit.
Referenced by caja_icon_container_start_renaming_selected_item().
caja_icon_canvas_item_get_text_rectangle()
EelDRect caja_icon_canvas_item_get_text_rectangle (CajaIconCanvasItem * item, gboolean for_layout)
Definition at line 2512 of file caja-icon-canvas-item.c.
References BOUNDS_USAGE_FOR_DISPLAY, BOUNDS_USAGE_FOR_LAYOUT, CAJA_IS_ICON_CANVAS_ITEM, EEL_CANVAS_ITEM, eel_canvas_item_i2w(), eel_drect_empty, FALSE, item, EelDRect::x0, EelIRect::x0, EelDRect::x1, EelIRect::x1, EelDRect::y0, EelIRect::y0, EelDRect::y1, and EelIRect::y1.
Referenced by caja_icon_container_start_renaming_selected_item().
caja_icon_canvas_item_get_type()
GType caja_icon_canvas_item_get_type (void)
References item.
Referenced by caja_icon_container_add().
caja_icon_canvas_item_hit_test_rectangle()
gboolean caja_icon_canvas_item_hit_test_rectangle (CajaIconCanvasItem * item, EelIRect canvas_rect)
Definition at line 2668 of file caja-icon-canvas-item.c.
References CAJA_IS_ICON_CANVAS_ITEM, FALSE, and item.
caja_icon_canvas_item_hit_test_stretch_handles()
gboolean caja_icon_canvas_item_hit_test_stretch_handles (CajaIconCanvasItem * item, EelDPoint world_point, GtkCornerType * corner)
Definition at line 2644 of file caja-icon-canvas-item.c.
References CAJA_IS_ICON_CANVAS_ITEM, EEL_CANVAS_ITEM, eel_canvas_w2c(), FALSE, item, EelDPoint::x, EelIRect::x0, EelIRect::x1, EelDPoint::y, EelIRect::y0, and EelIRect::y1.
caja_icon_canvas_item_invalidate_label()
void caja_icon_canvas_item_invalidate_label (CajaIconCanvasItem * item)
Definition at line 1443 of file caja-icon-canvas-item.c.
References caja_icon_canvas_item_invalidate_label_size(), item, and NULL.
Referenced by caja_icon_canvas_item_set_is_visible().
caja_icon_canvas_item_invalidate_label_size()
void caja_icon_canvas_item_invalidate_label_size (CajaIconCanvasItem * item)
Definition at line 337 of file caja-icon-canvas-item.c.
References item, and NULL.
Referenced by caja_icon_canvas_item_invalidate_label(), and caja_icon_canvas_item_set_entire_text().
caja_icon_canvas_item_set_attach_points()
void caja_icon_canvas_item_set_attach_points (CajaIconCanvasItem * item, GdkPoint * attach_points, int n_attach_points)
Definition at line 685 of file caja-icon-canvas-item.c.
References item, and NULL.
Referenced by caja_icon_container_update_icon().
caja_icon_canvas_item_set_embedded_text()
void caja_icon_canvas_item_set_embedded_text (CajaIconCanvasItem * item, const char * text)
Definition at line 713 of file caja-icon-canvas-item.c.
References EEL_CANVAS_ITEM, eel_canvas_item_request_update(), item, and NULL.
Referenced by caja_icon_container_update_icon().
caja_icon_canvas_item_set_embedded_text_rect()
void caja_icon_canvas_item_set_embedded_text_rect (CajaIconCanvasItem * item, const GdkRectangle * text_rect)
Definition at line 703 of file caja-icon-canvas-item.c.
References EEL_CANVAS_ITEM, eel_canvas_item_request_update(), and item.
Referenced by caja_icon_container_update_icon().
caja_icon_canvas_item_set_emblems()
void caja_icon_canvas_item_set_emblems (CajaIconCanvasItem * item, GList * emblem_pixbufs)
Definition at line 652 of file caja-icon-canvas-item.c.
References CAJA_IS_ICON_CANVAS_ITEM, EEL_CANVAS_ITEM, eel_canvas_item_request_update(), eel_g_list_equal(), item, and NULL.
Referenced by caja_icon_container_update_icon().
caja_icon_canvas_item_set_entire_text()
void caja_icon_canvas_item_set_entire_text (CajaIconCanvasItem * icon_item, gboolean entire_text)
Definition at line 2743 of file caja-icon-canvas-item.c.
References caja_icon_canvas_item_invalidate_label_size(), EEL_CANVAS_ITEM, eel_canvas_item_request_update(), FALSE, and item.
caja_icon_canvas_item_set_image()
void caja_icon_canvas_item_set_image (CajaIconCanvasItem * item, GdkPixbuf * image)
Definition at line 617 of file caja-icon-canvas-item.c.
References CAJA_IS_ICON_CANVAS_ITEM, EEL_CANVAS_ITEM, eel_canvas_item_request_update(), item, and NULL.
Referenced by caja_icon_container_update_icon().
caja_icon_canvas_item_set_is_visible()
void caja_icon_canvas_item_set_is_visible (CajaIconCanvasItem * item, gboolean visible)
Definition at line 1428 of file caja-icon-canvas-item.c.
References caja_icon_canvas_item_invalidate_label(), FALSE, and item.
caja_icon_canvas_item_set_renaming()
void caja_icon_canvas_item_set_renaming (CajaIconCanvasItem * icon_item, gboolean state)
Definition at line 2684 of file caja-icon-canvas-item.c.
References CAJA_IS_ICON_CANVAS_ITEM, EEL_CANVAS_ITEM, eel_canvas_item_request_update(), FALSE, item, and TRUE.
Referenced by caja_icon_container_start_renaming_selected_item().
caja_icon_canvas_item_set_show_stretch_handles()
void caja_icon_canvas_item_set_show_stretch_handles (CajaIconCanvasItem * item, gboolean show_stretch_handles)
Definition at line 2575 of file caja-icon-canvas-item.c.
References CAJA_IS_ICON_CANVAS_ITEM, EEL_CANVAS_ITEM, eel_canvas_item_request_update(), FALSE, item, and TRUE.
Referenced by caja_icon_container_show_stretch_handles().
caja_icon_canvas_item_update_bounds()
void caja_icon_canvas_item_update_bounds (CajaIconCanvasItem * item, double i2w_dx, double i2w_dy)
Definition at line 878 of file caja-icon-canvas-item.c.
References BOUNDS_USAGE_FOR_DISPLAY, CAJA_ICON_CONTAINER, caja_icon_container_is_layout_rtl(), _EelCanvasItem::canvas, EEL_CANVAS_ITEM, eel_canvas_request_redraw(), eel_irect_equal(), eel_irect_union(), is_rtl, item, TRUE, EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.