MATE Desktop Environment: caja-bookmark.h File Reference
caja-bookmark.h File Reference
#include <gtk/gtk.h>
#include <gio/gio.h>
Classes
struct CajaBookmark
struct CajaBookmarkClass
Macros
#define CAJA_TYPE_BOOKMARK caja_bookmark_get_type()
#define CAJA_BOOKMARK(obj)
#define CAJA_BOOKMARK_CLASS(klass)
#define CAJA_IS_BOOKMARK(obj)
#define CAJA_IS_BOOKMARK_CLASS(klass)
#define CAJA_BOOKMARK_GET_CLASS(obj)
Typedefs
typedef struct CajaBookmark CajaBookmark
typedef struct CajaBookmarkDetails CajaBookmarkDetails
typedef struct CajaBookmarkClass CajaBookmarkClass
Functions
GType caja_bookmark_get_type (void)
CajaBookmark * caja_bookmark_new (GFile *location, const char *name, gboolean has_custom_name, GIcon *icon)
CajaBookmark * caja_bookmark_copy (CajaBookmark *bookmark)
char * caja_bookmark_get_name (CajaBookmark *bookmark)
GFile * caja_bookmark_get_location (CajaBookmark *bookmark)
char * caja_bookmark_get_uri (CajaBookmark *bookmark)
GIcon * caja_bookmark_get_icon (CajaBookmark *bookmark)
gboolean caja_bookmark_get_has_custom_name (CajaBookmark *bookmark)
gboolean caja_bookmark_set_name (CajaBookmark *bookmark, const char *new_name)
gboolean caja_bookmark_uri_known_not_to_exist (CajaBookmark *bookmark)
int caja_bookmark_compare_with (gconstpointer a, gconstpointer b)
int caja_bookmark_compare_uris (gconstpointer a, gconstpointer b)
void caja_bookmark_set_scroll_pos (CajaBookmark *bookmark, const char *uri)
char * caja_bookmark_get_scroll_pos (CajaBookmark *bookmark)
cairo_surface_t * caja_bookmark_get_surface (CajaBookmark *bookmark, GtkIconSize icon_size)
GtkWidget * caja_bookmark_menu_item_new (CajaBookmark *bookmark)
Macro Definition Documentation
CAJA_BOOKMARK
#define CAJA_BOOKMARK (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_BOOKMARK, CajaBookmark))
Definition at line 33 of file caja-bookmark.h.
Referenced by caja_bookmark_compare_uris(), caja_bookmark_compare_with(), caja_bookmark_list_delete_item_at(), caja_bookmark_list_delete_items_with_uri(), caja_bookmark_list_item_at(), caja_bookmark_new(), and caja_navigation_window_slot_should_close_with_mount().
CAJA_BOOKMARK_CLASS
#define CAJA_BOOKMARK_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_BOOKMARK, CajaBookmarkClass))
Definition at line 35 of file caja-bookmark.h.
CAJA_BOOKMARK_GET_CLASS
#define CAJA_BOOKMARK_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_BOOKMARK, CajaBookmarkClass))
Definition at line 41 of file caja-bookmark.h.
CAJA_IS_BOOKMARK
#define CAJA_IS_BOOKMARK (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_BOOKMARK))
Definition at line 37 of file caja-bookmark.h.
Referenced by caja_add_bookmark_to_history_list(), caja_bookmark_compare_uris(), caja_bookmark_compare_with(), caja_bookmark_copy(), caja_bookmark_get_has_custom_name(), caja_bookmark_get_icon(), caja_bookmark_get_location(), caja_bookmark_get_name(), caja_bookmark_get_surface(), caja_bookmark_list_append(), caja_bookmark_list_contains(), caja_bookmark_list_delete_item_at(), caja_bookmark_set_name(), caja_menus_append_bookmark_to_menu(), and G_DEFINE_TYPE().
CAJA_IS_BOOKMARK_CLASS
#define CAJA_IS_BOOKMARK_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_BOOKMARK))
Definition at line 39 of file caja-bookmark.h.
CAJA_TYPE_BOOKMARK
#define CAJA_TYPE_BOOKMARK caja_bookmark_get_type()
Definition at line 32 of file caja-bookmark.h.
Referenced by caja_bookmark_new().
Typedef Documentation
CajaBookmark
typedef struct CajaBookmark CajaBookmark
Definition at line 30 of file caja-bookmark.h.
CajaBookmarkClass
typedef struct CajaBookmarkClass CajaBookmarkClass
Definition at line 69 of file caja-bookmark.h.
CajaBookmarkDetails
typedef struct CajaBookmarkDetails CajaBookmarkDetails
Definition at line 44 of file caja-bookmark.h.
Function Documentation
caja_bookmark_compare_uris()
int caja_bookmark_compare_uris (gconstpointer a, gconstpointer b)
caja_bookmark_compare_uris:
Check whether the uris of two bookmarks are for the same location. : first CajaBookmark*. : second CajaBookmark*.
Return value: 0 if and have matching uri, 1 otherwise (GCompareFunc style)
Definition at line 171 of file caja-bookmark.c.
References b, CAJA_BOOKMARK, CAJA_IS_BOOKMARK, and CajaBookmark::details.
Referenced by caja_add_bookmark_to_history_list().
caja_bookmark_compare_with()
int caja_bookmark_compare_with (gconstpointer a, gconstpointer b)
caja_bookmark_compare_with:
Check whether two bookmarks are considered identical. : first CajaBookmark*. : second CajaBookmark*.
Return value: 0 if and have same name and uri, 1 otherwise (GCompareFunc style)
Definition at line 134 of file caja-bookmark.c.
References b, CAJA_BOOKMARK, CAJA_IS_BOOKMARK, and CajaBookmark::details.
Referenced by caja_bookmark_list_contains().
caja_bookmark_copy()
CajaBookmark * caja_bookmark_copy (CajaBookmark * bookmark)
Definition at line 187 of file caja-bookmark.c.
References caja_bookmark_new(), CAJA_IS_BOOKMARK, CajaBookmark::details, and NULL.
Referenced by caja_bookmark_list_append(), and caja_bookmark_list_insert_item().
caja_bookmark_get_has_custom_name()
gboolean caja_bookmark_get_has_custom_name (CajaBookmark * bookmark)
Definition at line 207 of file caja-bookmark.c.
References CAJA_IS_BOOKMARK, CajaBookmark::details, and FALSE.
caja_bookmark_get_icon()
GIcon * caja_bookmark_get_icon (CajaBookmark * bookmark)
Definition at line 243 of file caja-bookmark.c.
References CAJA_IS_BOOKMARK, CajaBookmark::details, and NULL.
Referenced by caja_bookmark_get_surface().
caja_bookmark_get_location()
GFile * caja_bookmark_get_location (CajaBookmark * bookmark)
Definition at line 258 of file caja-bookmark.c.
References CAJA_IS_BOOKMARK, CajaBookmark::details, and NULL.
Referenced by caja_bookmark_get_uri(), caja_navigation_window_back_or_forward(), and caja_navigation_window_slot_should_close_with_mount().
caja_bookmark_get_name()
char * caja_bookmark_get_name (CajaBookmark * bookmark)
Definition at line 199 of file caja-bookmark.c.
References CAJA_IS_BOOKMARK, CajaBookmark::details, and NULL.
Referenced by caja_menus_append_bookmark_to_menu().
caja_bookmark_get_scroll_pos()
char * caja_bookmark_get_scroll_pos (CajaBookmark * bookmark)
Definition at line 684 of file caja-bookmark.c.
References CajaBookmark::details.
Referenced by caja_navigation_window_back_or_forward().
caja_bookmark_get_surface()
cairo_surface_t * caja_bookmark_get_surface (CajaBookmark * bookmark, GtkIconSize icon_size)
Definition at line 215 of file caja-bookmark.c.
References caja_bookmark_get_icon(), caja_get_icon_size_for_stock_size(), caja_icon_info_get_surface_at_size(), caja_icon_info_lookup(), CAJA_IS_BOOKMARK, and NULL.
Referenced by caja_bookmark_menu_item_new(), and caja_menus_append_bookmark_to_menu().
caja_bookmark_get_type()
GType caja_bookmark_get_type (void)
References b, and name.
caja_bookmark_get_uri()
char * caja_bookmark_get_uri (CajaBookmark * bookmark)
Definition at line 274 of file caja-bookmark.c.
References caja_bookmark_get_location(), and NULL.
Referenced by caja_bookmark_list_delete_items_with_uri().
caja_bookmark_menu_item_new()
GtkWidget * caja_bookmark_menu_item_new (CajaBookmark * bookmark)
caja_bookmark_menu_item_new:
Return a menu item representing a bookmark. @bookmark: The bookmark the menu item represents. Return value: A newly-created bookmark, not yet shown.
Definition at line 633 of file caja-bookmark.c.
References caja_bookmark_get_surface(), CajaBookmark::details, and NULL.
caja_bookmark_new()
CajaBookmark * caja_bookmark_new (GFile * location, const char * name, gboolean has_custom_name, GIcon * icon)
Definition at line 570 of file caja-bookmark.c.
References CAJA_BOOKMARK, CAJA_TYPE_BOOKMARK, CajaBookmark::details, name, and NULL.
Referenced by caja_add_to_history_list_no_notify(), caja_bookmark_copy(), and caja_remove_from_history_list_no_notify().
caja_bookmark_set_name()
gboolean caja_bookmark_set_name (CajaBookmark * bookmark, const char * new_name)
caja_bookmark_set_name:
Change the user-displayed name of a bookmark. @new_name: The new user-displayed name for this bookmark, mustn't be NULL.
Returns: TRUE if the name changed else FALSE.
Definition at line 296 of file caja-bookmark.c.
References APPEARANCE_CHANGED, CAJA_IS_BOOKMARK, CONTENTS_CHANGED, CajaBookmark::details, FALSE, NULL, and TRUE.
caja_bookmark_set_scroll_pos()
void caja_bookmark_set_scroll_pos (CajaBookmark * bookmark, const char * uri)
Definition at line 676 of file caja-bookmark.c.
References CajaBookmark::details.
caja_bookmark_uri_known_not_to_exist()
gboolean caja_bookmark_uri_known_not_to_exist (CajaBookmark * bookmark)
Definition at line 656 of file caja-bookmark.c.
References CajaBookmark::details, and FALSE.