MATE Desktop Environment: caja-desktop-icon-file.c File Reference
caja-desktop-icon-file.c File Reference
#include <config.h>
#include <glib/gi18n.h>
#include <string.h>
#include <gio/gio.h>
#include <eel/eel-glib-extensions.h>
#include "caja-desktop-icon-file.h"
#include "caja-desktop-metadata.h"
#include "caja-desktop-directory-file.h"
#include "caja-directory-notify.h"
#include "caja-directory-private.h"
#include "caja-file-attributes.h"
#include "caja-file-private.h"
#include "caja-file-utilities.h"
#include "caja-file-operations.h"
#include "caja-desktop-directory.h"
Functions
void caja_desktop_icon_file_update (CajaDesktopIconFile *icon_file)
void caja_desktop_icon_file_remove (CajaDesktopIconFile *icon_file)
CajaDesktopIconFile * caja_desktop_icon_file_new (CajaDesktopLink *link)
CajaDesktopLink * caja_desktop_icon_file_get_link (CajaDesktopIconFile *icon_file)
Function Documentation
caja_desktop_icon_file_get_link()
CajaDesktopLink * caja_desktop_icon_file_get_link (CajaDesktopIconFile * icon_file)
Definition at line 315 of file caja-desktop-icon-file.c.
References CajaDesktopIconFile::details, and NULL.
Referenced by caja_file_can_rename(), caja_file_get_drop_target_uri(), and caja_file_rename().
caja_desktop_icon_file_new()
CajaDesktopIconFile * caja_desktop_icon_file_new (CajaDesktopLink * link)
Definition at line 273 of file caja-desktop-icon-file.c.
References CAJA_DESKTOP_ICON_FILE, caja_desktop_link_get_file_name(), caja_desktop_update_metadata_from_keyfile(), caja_directory_add_file(), caja_directory_emit_files_added(), caja_directory_get_by_uri(), CAJA_FILE, CAJA_TYPE_DESKTOP_ICON_FILE, CajaDesktopIconFile::details, CajaFile::details, _CajaFilePrivate::directory, EEL_DESKTOP_URI, _CajaFilePrivate::name, name, and NULL.
caja_desktop_icon_file_remove()
void caja_desktop_icon_file_remove (CajaDesktopIconFile * icon_file)
Definition at line 245 of file caja-desktop-icon-file.c.
References caja_directory_emit_change_signals(), caja_directory_remove_file(), CAJA_FILE, caja_file_ref(), caja_file_unref(), CajaDesktopIconFile::details, CajaFile::details, _CajaFilePrivate::directory, _CajaFilePrivate::is_gone, NULL, and TRUE.
caja_desktop_icon_file_update()
void caja_desktop_icon_file_update (CajaDesktopIconFile * icon_file)
Definition at line 235 of file caja-desktop-icon-file.c.
References CAJA_FILE, and caja_file_changed().