MATE Desktop Environment: caja-directory-async.c File Reference
caja-directory-async.c File Reference
#include <config.h>
#include <gtk/gtk.h>
#include <libxml/parser.h>
#include <stdio.h>
#include <stdlib.h>
#include <eel/eel-glib-extensions.h>
#include "caja-directory-notify.h"
#include "caja-directory-private.h"
#include "caja-file-attributes.h"
#include "caja-file-private.h"
#include "caja-file-utilities.h"
#include "caja-metadata.h"
#include "caja-signaller.h"
#include "caja-global-preferences.h"
#include "caja-link.h"
#include "caja-marshal.h"
Macros
#define DIRECTORY_LOAD_ITEMS_PER_CALLBACK 100
#define MAX_ASYNC_JOBS 10
Typedefs
typedef gboolean(* RequestCheck) (Request)
typedef gboolean(* FileCheck) (CajaFile *)
Functions
Request caja_directory_set_up_request (CajaFileAttributes file_attributes)
void caja_directory_monitor_add_internal (CajaDirectory *directory, CajaFile *file, gconstpointer client, gboolean monitor_hidden_files, CajaFileAttributes file_attributes, CajaDirectoryCallback callback, gpointer callback_data)
void caja_directory_schedule_dequeue_pending (CajaDirectory *directory)
void caja_directory_monitor_remove_internal (CajaDirectory *directory, CajaFile *file, gconstpointer client)
FileMonitors * caja_directory_remove_file_monitors (CajaDirectory *directory, CajaFile *file)
void caja_directory_add_file_monitors (CajaDirectory *directory, CajaFile *file, FileMonitors *monitors)
void caja_directory_call_when_ready_internal (CajaDirectory *directory, CajaFile *file, CajaFileAttributes file_attributes, gboolean wait_for_file_list, CajaDirectoryCallback directory_callback, CajaFileCallback file_callback, gpointer callback_data)
gboolean caja_directory_check_if_ready_internal (CajaDirectory *directory, CajaFile *file, CajaFileAttributes file_attributes)
void caja_directory_cancel_callback_internal (CajaDirectory *directory, CajaFile *file, CajaDirectoryCallback directory_callback, CajaFileCallback file_callback, gpointer callback_data)
void caja_directory_get_info_for_new_files (CajaDirectory *directory, GList *location_list)
void caja_async_destroying_file (CajaFile *file)
gboolean caja_directory_has_active_request_for_file (CajaDirectory *directory, CajaFile *file)
gboolean caja_directory_is_anyone_monitoring_file_list (CajaDirectory *directory)
gboolean caja_directory_is_file_list_monitored (CajaDirectory *directory)
void caja_directory_stop_monitoring_file_list (CajaDirectory *directory)
void caja_file_invalidate_count_and_mime_list (CajaFile *file)
void caja_directory_invalidate_count_and_mime_list (CajaDirectory *directory)
void caja_directory_force_reload_internal (CajaDirectory *directory, CajaFileAttributes file_attributes)
void caja_directory_async_state_changed (CajaDirectory *directory)
void caja_directory_cancel (CajaDirectory *directory)
void caja_directory_cancel_loading_file_attributes (CajaDirectory *directory, CajaFile *file, CajaFileAttributes file_attributes)
void caja_directory_add_file_to_work_queue (CajaDirectory *directory, CajaFile *file)
void caja_directory_remove_file_from_work_queue (CajaDirectory *directory, CajaFile *file)
Variables
int cached_thumbnail_size
Macro Definition Documentation
DIRECTORY_LOAD_ITEMS_PER_CALLBACK
#define DIRECTORY_LOAD_ITEMS_PER_CALLBACK 100
Definition at line 59 of file caja-directory-async.c.
MAX_ASYNC_JOBS
#define MAX_ASYNC_JOBS 10
Definition at line 62 of file caja-directory-async.c.
Typedef Documentation
FileCheck
typedef gboolean(* FileCheck) (CajaFile *)
Definition at line 188 of file caja-directory-async.c.
RequestCheck
typedef gboolean(* RequestCheck) (Request)
Definition at line 187 of file caja-directory-async.c.
Function Documentation
caja_async_destroying_file()
void caja_async_destroying_file (CajaFile * file)
Definition at line 1644 of file caja-directory-async.c.
References caja_directory_async_state_changed(), _CajaDirectoryPrivate::call_when_ready_list, _CajaDirectoryPrivate::count_in_progress, _CajaDirectoryPrivate::deep_count_file, CajaDirectory::details, CajaFile::details, _CajaFilePrivate::directory, _CajaDirectoryPrivate::extension_info_file, FALSE, _CajaDirectoryPrivate::filesystem_info_state, _CajaDirectoryPrivate::get_info_file, _CajaDirectoryPrivate::link_info_read_state, _CajaDirectoryPrivate::mime_list_in_progress, _CajaDirectoryPrivate::monitor_list, _CajaDirectoryPrivate::mount_state, NULL, _CajaDirectoryPrivate::thumbnail_state, _CajaDirectoryPrivate::top_left_read_state, and TRUE.
caja_directory_add_file_monitors()
void caja_directory_add_file_monitors (CajaDirectory * directory, CajaFile * file, FileMonitors * monitors)
Definition at line 1254 of file caja-directory-async.c.
References caja_directory_add_file_to_work_queue(), caja_directory_async_state_changed(), CAJA_IS_DIRECTORY, CAJA_IS_FILE, CajaDirectory::details, CajaFile::details, _CajaFilePrivate::directory, _CajaDirectoryPrivate::monitor_counters, _CajaDirectoryPrivate::monitor_list, and NULL.
Referenced by caja_file_update_name_and_directory().
caja_directory_add_file_to_work_queue()
void caja_directory_add_file_to_work_queue (CajaDirectory * directory, CajaFile * file)
Definition at line 5271 of file caja-directory-async.c.
References caja_file_queue_enqueue(), CajaDirectory::details, CajaFile::details, _CajaFilePrivate::directory, and _CajaDirectoryPrivate::high_priority_queue.
Referenced by caja_directory_add_file(), caja_directory_add_file_monitors(), caja_directory_call_when_ready_internal(), caja_directory_monitor_add_internal(), caja_file_invalidate_attributes(), and caja_file_recompute_deep_counts().
caja_directory_async_state_changed()
void caja_directory_async_state_changed (CajaDirectory * directory)
Definition at line 5006 of file caja-directory-async.c.
References caja_directory_ref(), caja_directory_unref(), CajaDirectory::details, FALSE, _CajaDirectoryPrivate::in_async_service_loop, _CajaDirectoryPrivate::state_changed, and TRUE.
Referenced by caja_async_destroying_file(), caja_directory_add_file_monitors(), caja_directory_call_when_ready_internal(), caja_directory_cancel_callback_internal(), caja_directory_cancel_loading_file_attributes(), caja_directory_force_reload_internal(), caja_directory_monitor_add_internal(), caja_directory_monitor_remove_internal(), caja_directory_remove_file_monitors(), caja_file_invalidate_attributes(), and caja_file_recompute_deep_counts().
caja_directory_call_when_ready_internal()
void caja_directory_call_when_ready_internal (CajaDirectory * directory, CajaFile * file, CajaFileAttributes file_attributes, gboolean wait_for_file_list, CajaDirectoryCallback directory_callback, CajaFileCallback file_callback, gpointer callback_data)
Definition at line 1394 of file caja-directory-async.c.
References caja_directory_add_file_to_work_queue(), caja_directory_async_state_changed(), caja_directory_set_up_request(), CAJA_IS_DIRECTORY, CAJA_IS_FILE, _CajaDirectoryPrivate::call_when_ready_counters, _CajaDirectoryPrivate::call_when_ready_list, CajaDirectory::details, NULL, REQUEST_FILE_LIST, REQUEST_SET_TYPE, and TRUE.
caja_directory_cancel()
void caja_directory_cancel (CajaDirectory * directory)
Definition at line 5041 of file caja-directory-async.c.
References NULL.
caja_directory_cancel_callback_internal()
void caja_directory_cancel_callback_internal (CajaDirectory * directory, CajaFile * file, CajaDirectoryCallback directory_callback, CajaFileCallback file_callback, gpointer callback_data)
Definition at line 1507 of file caja-directory-async.c.
References caja_directory_async_state_changed(), CAJA_IS_DIRECTORY, CAJA_IS_FILE, _CajaDirectoryPrivate::call_when_ready_list, CajaDirectory::details, and NULL.
caja_directory_cancel_loading_file_attributes()
void caja_directory_cancel_loading_file_attributes (CajaDirectory * directory, CajaFile * file, CajaFileAttributes file_attributes)
Definition at line 5220 of file caja-directory-async.c.
References caja_directory_async_state_changed(), caja_directory_remove_file_from_work_queue(), caja_directory_set_up_request(), REQUEST_DEEP_COUNT, REQUEST_DIRECTORY_COUNT, REQUEST_FILE_INFO, REQUEST_FILESYSTEM_INFO, REQUEST_LINK_INFO, REQUEST_MIME_LIST, REQUEST_MOUNT, REQUEST_THUMBNAIL, REQUEST_TOP_LEFT_TEXT, and REQUEST_WANTS_TYPE.
Referenced by caja_directory_notify_files_moved(), and caja_file_invalidate_attributes().
caja_directory_check_if_ready_internal()
gboolean caja_directory_check_if_ready_internal (CajaDirectory * directory, CajaFile * file, CajaFileAttributes file_attributes)
Definition at line 1467 of file caja-directory-async.c.
References caja_directory_set_up_request(), and CAJA_IS_DIRECTORY.
caja_directory_force_reload_internal()
void caja_directory_force_reload_internal (CajaDirectory * directory, CajaFileAttributes file_attributes)
Definition at line 2411 of file caja-directory-async.c.
References caja_directory_async_state_changed(), caja_directory_invalidate_count_and_mime_list(), CajaDirectory::details, _CajaDirectoryPrivate::directory_loaded, and FALSE.
caja_directory_get_info_for_new_files()
void caja_directory_get_info_for_new_files (CajaDirectory * directory, GList * location_list)
Definition at line 1607 of file caja-directory-async.c.
References CAJA_FILE_DEFAULT_ATTRIBUTES, CajaDirectory::details, _CajaDirectoryPrivate::new_files_in_progress, and NULL.
caja_directory_has_active_request_for_file()
gboolean caja_directory_has_active_request_for_file (CajaDirectory * directory, CajaFile * file)
Definition at line 2084 of file caja-directory-async.c.
References _CajaDirectoryPrivate::call_when_ready_list, CajaDirectory::details, FALSE, _CajaDirectoryPrivate::monitor_list, NULL, and TRUE.
Referenced by caja_directory_add_file().
caja_directory_invalidate_count_and_mime_list()
void caja_directory_invalidate_count_and_mime_list (CajaDirectory * directory)
Definition at line 2376 of file caja-directory-async.c.
References caja_directory_get_existing_corresponding_file(), caja_file_invalidate_count_and_mime_list(), caja_file_unref(), and NULL.
Referenced by caja_directory_force_reload_internal().
caja_directory_is_anyone_monitoring_file_list()
gboolean caja_directory_is_anyone_monitoring_file_list (CajaDirectory * directory)
Definition at line 2118 of file caja-directory-async.c.
References _CajaDirectoryPrivate::call_when_ready_counters, CajaDirectory::details, FALSE, _CajaDirectoryPrivate::monitor_counters, REQUEST_FILE_LIST, and TRUE.
caja_directory_is_file_list_monitored()
gboolean caja_directory_is_file_list_monitored (CajaDirectory * directory)
Definition at line 2135 of file caja-directory-async.c.
References CajaDirectory::details, and _CajaDirectoryPrivate::file_list_monitored.
Referenced by caja_directory_add_file(), caja_directory_notify_files_added(), and caja_directory_remove_file().
caja_directory_monitor_add_internal()
void caja_directory_monitor_add_internal (CajaDirectory * directory, CajaFile * file, gconstpointer client, gboolean monitor_hidden_files, CajaFileAttributes file_attributes, CajaDirectoryCallback callback, gpointer callback_data)
Definition at line 789 of file caja-directory-async.c.
References caja_directory_add_file_to_work_queue(), caja_directory_async_state_changed(), caja_directory_get_file_list(), caja_directory_set_up_request(), caja_file_list_free(), CAJA_IS_DIRECTORY, caja_monitor_directory(), caja_signaller_get_current(), CajaDirectory::details, file_list, _CajaDirectoryPrivate::location, _CajaDirectoryPrivate::mime_db_monitor, _CajaDirectoryPrivate::monitor, _CajaDirectoryPrivate::monitor_counters, _CajaDirectoryPrivate::monitor_list, NULL, REQUEST_FILE_INFO, REQUEST_FILE_LIST, REQUEST_SET_TYPE, and REQUEST_WANTS_TYPE.
Referenced by EEL_CLASS_BOILERPLATE().
caja_directory_monitor_remove_internal()
void caja_directory_monitor_remove_internal (CajaDirectory * directory, CajaFile * file, gconstpointer client)
Definition at line 1196 of file caja-directory-async.c.
References caja_directory_async_state_changed(), CAJA_IS_DIRECTORY, CAJA_IS_FILE, caja_monitor_cancel(), CajaDirectory::details, _CajaDirectoryPrivate::monitor, _CajaDirectoryPrivate::monitor_list, and NULL.
caja_directory_remove_file_from_work_queue()
void caja_directory_remove_file_from_work_queue (CajaDirectory * directory, CajaFile * file)
Definition at line 5296 of file caja-directory-async.c.
References caja_file_queue_remove(), CajaDirectory::details, _CajaDirectoryPrivate::extension_queue, _CajaDirectoryPrivate::high_priority_queue, and _CajaDirectoryPrivate::low_priority_queue.
Referenced by caja_directory_cancel_loading_file_attributes(), and caja_directory_remove_file().
caja_directory_remove_file_monitors()
FileMonitors * caja_directory_remove_file_monitors (CajaDirectory * directory, CajaFile * file)
Definition at line 1219 of file caja-directory-async.c.
References caja_directory_async_state_changed(), CAJA_IS_DIRECTORY, CAJA_IS_FILE, CajaDirectory::details, CajaFile::details, _CajaFilePrivate::directory, _CajaDirectoryPrivate::monitor_counters, _CajaDirectoryPrivate::monitor_list, and NULL.
Referenced by caja_file_update_name_and_directory().
caja_directory_schedule_dequeue_pending()
void caja_directory_schedule_dequeue_pending (CajaDirectory * directory)
Definition at line 1081 of file caja-directory-async.c.
References _CajaDirectoryPrivate::dequeue_pending_idle_id, and CajaDirectory::details.
caja_directory_set_up_request()
Request caja_directory_set_up_request (CajaFileAttributes file_attributes)
Definition at line 705 of file caja-directory-async.c.
References CAJA_FILE_ATTRIBUTE_DEEP_COUNTS, CAJA_FILE_ATTRIBUTE_DIRECTORY_ITEM_COUNT, CAJA_FILE_ATTRIBUTE_DIRECTORY_ITEM_MIME_TYPES, CAJA_FILE_ATTRIBUTE_EXTENSION_INFO, CAJA_FILE_ATTRIBUTE_FILESYSTEM_INFO, CAJA_FILE_ATTRIBUTE_INFO, CAJA_FILE_ATTRIBUTE_LARGE_TOP_LEFT_TEXT, CAJA_FILE_ATTRIBUTE_LINK_INFO, CAJA_FILE_ATTRIBUTE_MOUNT, CAJA_FILE_ATTRIBUTE_THUMBNAIL, CAJA_FILE_ATTRIBUTE_TOP_LEFT_TEXT, REQUEST_DEEP_COUNT, REQUEST_DIRECTORY_COUNT, REQUEST_EXTENSION_INFO, REQUEST_FILE_INFO, REQUEST_FILESYSTEM_INFO, REQUEST_LARGE_TOP_LEFT_TEXT, REQUEST_LINK_INFO, REQUEST_MIME_LIST, REQUEST_MOUNT, REQUEST_SET_TYPE, REQUEST_THUMBNAIL, and REQUEST_TOP_LEFT_TEXT.
Referenced by caja_directory_call_when_ready_internal(), caja_directory_cancel_loading_file_attributes(), caja_directory_check_if_ready_internal(), caja_directory_monitor_add_internal(), and caja_file_invalidate_attributes_internal().
caja_directory_stop_monitoring_file_list()
void caja_directory_stop_monitoring_file_list (CajaDirectory * directory)
Definition at line 2331 of file caja-directory-async.c.
References caja_file_list_unref(), CajaDirectory::details, _CajaDirectoryPrivate::directory_load_in_progress, _CajaDirectoryPrivate::directory_loaded, FALSE, _CajaDirectoryPrivate::file_list, _CajaDirectoryPrivate::file_list_monitored, and NULL.
caja_file_invalidate_count_and_mime_list()
void caja_file_invalidate_count_and_mime_list (CajaFile * file)
Definition at line 2359 of file caja-directory-async.c.
References CAJA_FILE_ATTRIBUTE_DIRECTORY_ITEM_COUNT, CAJA_FILE_ATTRIBUTE_DIRECTORY_ITEM_MIME_TYPES, and caja_file_invalidate_attributes().
Referenced by caja_directory_invalidate_count_and_mime_list(), and caja_directory_notify_files_added().
Variable Documentation
cached_thumbnail_size
int cached_thumbnail_size extern
Definition at line 4341 of file caja-file.c.
Referenced by caja_file_get_icon().