MATE Desktop Environment: caja-dropbox.c File Reference
caja-dropbox.c File Reference
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <errno.h>
#include <unistd.h>
#include <ctype.h>
#include <glib.h>
#include <glib/gprintf.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <libcaja-extension/caja-extension-types.h>
#include <libcaja-extension/caja-menu-provider.h>
#include <libcaja-extension/caja-info-provider.h>
#include "g-util.h"
#include "dropbox-command-client.h"
#include "caja-dropbox.h"
#include "caja-dropbox-hooks.h"
Functions
gboolean caja_dropbox_finish_file_info_command (DropboxFileInfoCommandResponse *dficr)
int GhettoURLDecode (gchar *out, gchar *in, int n)
gboolean add_emblem_paths (GHashTable *emblem_paths_response)
gboolean remove_emblem_paths (GHashTable *emblem_paths_response)
void get_emblem_paths_cb (GHashTable *emblem_paths_response, CajaDropbox *cvs)
GType caja_dropbox_get_type (void)
void caja_dropbox_register_type (GTypeModule *module)
Variables
gchar * DEFAULT_EMBLEM_PATHS [2] = { EMBLEMDIR , NULL }
gboolean dropbox_use_operation_in_progress_workaround
Function Documentation
add_emblem_paths()
gboolean add_emblem_paths (GHashTable * emblem_paths_response)
Definition at line 745 of file caja-dropbox.c.
References FALSE, and NULL.
Referenced by get_emblem_paths_cb().
caja_dropbox_finish_file_info_command()
gboolean caja_dropbox_finish_file_info_command (DropboxFileInfoCommandResponse * dficr)
Definition at line 333 of file caja-dropbox.c.
References caja_file_info_add_emblem(), caja_file_info_is_directory(), caja_info_provider_update_complete_invoke(), CAJA_OPERATION_COMPLETE, CAJA_OPERATION_FAILED, DropboxFileInfoCommand::cancelled, DropboxFileInfoCommandResponse::dfic, dropbox_use_operation_in_progress_workaround, DropboxFileInfoCommandResponse::emblems_response, FALSE, DropboxFileInfoCommand::file, DropboxFileInfoCommandResponse::file_status_response, DropboxFileInfoCommandResponse::folder_tag_response, NULL, DropboxFileInfoCommand::provider, TRUE, and DropboxFileInfoCommand::update_complete.
caja_dropbox_get_type()
GType caja_dropbox_get_type (void)
Definition at line 921 of file caja-dropbox.c.
caja_dropbox_register_type()
void caja_dropbox_register_type (GTypeModule * module)
Definition at line 926 of file caja-dropbox.c.
References CAJA_TYPE_INFO_PROVIDER, CAJA_TYPE_MENU_PROVIDER, and NULL.
Referenced by caja_module_initialize().
get_emblem_paths_cb()
void get_emblem_paths_cb (GHashTable * emblem_paths_response, CajaDropbox * cvs)
Definition at line 818 of file caja-dropbox.c.
References add_emblem_paths(), DEFAULT_EMBLEM_PATHS, _CajaDropbox::emblem_paths, _CajaDropbox::emblem_paths_mutex, NULL, and remove_emblem_paths().
GhettoURLDecode()
int GhettoURLDecode (gchar * out, gchar * in, int n)
Definition at line 507 of file caja-dropbox.c.
remove_emblem_paths()
gboolean remove_emblem_paths (GHashTable * emblem_paths_response)
Definition at line 768 of file caja-dropbox.c.
References FALSE, NULL, and TRUE.
Referenced by get_emblem_paths_cb().
Variable Documentation
DEFAULT_EMBLEM_PATHS
gchar* DEFAULT_EMBLEM_PATHS[2] = { EMBLEMDIR , NULL }
Definition at line 50 of file caja-dropbox.c.
Referenced by get_emblem_paths_cb().
dropbox_use_operation_in_progress_workaround
gboolean dropbox_use_operation_in_progress_workaround
Definition at line 52 of file caja-dropbox.c.
Referenced by caja_dropbox_finish_file_info_command(), and caja_module_initialize().