MATE Desktop Environment: caja-icon-info.h File Reference
caja-icon-info.h File Reference
#include <glib-object.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gdk/gdk.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
Macros
#define CAJA_ZOOM_LEVEL_N_ENTRIES (CAJA_ZOOM_LEVEL_LARGEST + 1)
#define CAJA_ICON_SIZE_SMALLEST 16
#define CAJA_ICON_SIZE_SMALLER 24
#define CAJA_ICON_SIZE_SMALL 32
#define CAJA_ICON_SIZE_STANDARD 48
#define CAJA_ICON_SIZE_LARGE 72
#define CAJA_ICON_SIZE_LARGER 96
#define CAJA_ICON_SIZE_LARGEST 192
#define CAJA_ICON_MAXIMUM_SIZE 320
#define CAJA_TYPE_ICON_INFO (caja_icon_info_get_type ())
#define CAJA_ICON_INFO(obj)
#define CAJA_ICON_INFO_CLASS(klass)
#define CAJA_IS_ICON_INFO(obj)
#define CAJA_IS_ICON_INFO_CLASS(klass)
#define CAJA_ICON_INFO_GET_CLASS(obj)
Typedefs
typedef struct _CajaIconInfo CajaIconInfo
typedef struct _CajaIconInfoClass CajaIconInfoClass
Enumerations
enum CajaZoomLevel {
CAJA_ZOOM_LEVEL_SMALLEST = 0 , CAJA_ZOOM_LEVEL_SMALLER , CAJA_ZOOM_LEVEL_SMALL , CAJA_ZOOM_LEVEL_STANDARD ,
CAJA_ZOOM_LEVEL_LARGE , CAJA_ZOOM_LEVEL_LARGER , CAJA_ZOOM_LEVEL_LARGEST
}
Functions
GType caja_icon_info_get_type (void)
CajaIconInfo * caja_icon_info_new_for_pixbuf (GdkPixbuf *pixbuf, int scale)
CajaIconInfo * caja_icon_info_lookup (GIcon *icon, int size, int scale)
CajaIconInfo * caja_icon_info_lookup_from_name (const char *name, int size, int scale)
CajaIconInfo * caja_icon_info_lookup_from_path (const char *path, int size, int scale)
gboolean caja_icon_info_is_fallback (CajaIconInfo *icon)
GdkPixbuf * caja_icon_info_get_pixbuf (CajaIconInfo *icon)
cairo_surface_t * caja_icon_info_get_surface (CajaIconInfo *icon)
GdkPixbuf * caja_icon_info_get_pixbuf_nodefault (CajaIconInfo *icon)
cairo_surface_t * caja_icon_info_get_surface_nodefault (CajaIconInfo *icon)
GdkPixbuf * caja_icon_info_get_pixbuf_nodefault_at_size (CajaIconInfo *icon, gsize forced_size)
cairo_surface_t * caja_icon_info_get_surface_nodefault_at_size (CajaIconInfo *icon, gsize forced_size)
GdkPixbuf * caja_icon_info_get_pixbuf_at_size (CajaIconInfo *icon, gsize forced_size)
cairo_surface_t * caja_icon_info_get_surface_at_size (CajaIconInfo *icon, gsize forced_size)
gboolean caja_icon_info_get_embedded_rect (CajaIconInfo *icon, GdkRectangle *rectangle)
gboolean caja_icon_info_get_attach_points (CajaIconInfo *icon, GdkPoint **points, gint *n_points)
const char * caja_icon_info_get_display_name (CajaIconInfo *icon)
const char * caja_icon_info_get_used_name (CajaIconInfo *icon)
void caja_icon_info_clear_caches (void)
guint caja_get_icon_size_for_zoom_level (CajaZoomLevel zoom_level)
float caja_get_relative_icon_size_for_zoom_level (CajaZoomLevel zoom_level)
guint caja_icon_get_larger_icon_size (guint size)
guint caja_icon_get_smaller_icon_size (guint size)
gint caja_get_icon_size_for_stock_size (GtkIconSize size)
guint caja_icon_get_emblem_size_for_icon_size (guint size)
gboolean caja_icon_theme_can_render (GThemedIcon *icon)
GIcon * caja_user_special_directory_get_gicon (GUserDirectory directory)
Macro Definition Documentation
CAJA_ICON_INFO
#define CAJA_ICON_INFO (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_ICON_INFO, CajaIconInfo))
Definition at line 49 of file caja-icon-info.h.
CAJA_ICON_INFO_CLASS
#define CAJA_ICON_INFO_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_ICON_INFO, CajaIconInfoClass))
Definition at line 50 of file caja-icon-info.h.
CAJA_ICON_INFO_GET_CLASS
#define CAJA_ICON_INFO_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_ICON_INFO, CajaIconInfoClass))
Definition at line 53 of file caja-icon-info.h.
CAJA_ICON_MAXIMUM_SIZE
#define CAJA_ICON_MAXIMUM_SIZE 320
Definition at line 43 of file caja-icon-info.h.
Referenced by caja_icon_container_update_icon().
CAJA_ICON_SIZE_LARGE
#define CAJA_ICON_SIZE_LARGE 72
Definition at line 38 of file caja-icon-info.h.
Referenced by caja_get_icon_size_for_zoom_level(), caja_icon_get_larger_icon_size(), caja_icon_get_smaller_icon_size(), and G_DEFINE_TYPE_WITH_PRIVATE().
CAJA_ICON_SIZE_LARGER
#define CAJA_ICON_SIZE_LARGER 96
Definition at line 39 of file caja-icon-info.h.
Referenced by caja_get_icon_size_for_zoom_level(), caja_icon_get_larger_icon_size(), and caja_icon_get_smaller_icon_size().
CAJA_ICON_SIZE_LARGEST
#define CAJA_ICON_SIZE_LARGEST 192
Definition at line 40 of file caja-icon-info.h.
Referenced by caja_get_icon_size_for_zoom_level(), caja_icon_get_larger_icon_size(), and caja_icon_get_smaller_icon_size().
CAJA_ICON_SIZE_SMALL
#define CAJA_ICON_SIZE_SMALL 32
Definition at line 36 of file caja-icon-info.h.
Referenced by caja_get_icon_size_for_zoom_level(), caja_icon_get_larger_icon_size(), caja_icon_get_smaller_icon_size(), and main().
CAJA_ICON_SIZE_SMALLER
#define CAJA_ICON_SIZE_SMALLER 24
Definition at line 35 of file caja-icon-info.h.
Referenced by caja_get_icon_size_for_zoom_level(), caja_icon_get_larger_icon_size(), caja_icon_get_smaller_icon_size(), and create_bookmarks_window().
CAJA_ICON_SIZE_SMALLEST
#define CAJA_ICON_SIZE_SMALLEST 16
Definition at line 34 of file caja-icon-info.h.
Referenced by caja_file_get_icon(), caja_get_icon_size_for_zoom_level(), caja_icon_get_larger_icon_size(), and caja_icon_get_smaller_icon_size().
CAJA_ICON_SIZE_STANDARD
#define CAJA_ICON_SIZE_STANDARD 48
Definition at line 37 of file caja-icon-info.h.
Referenced by caja_emblem_load_pixbuf_for_emblem(), caja_file_get_icon(), caja_get_icon_size_for_zoom_level(), caja_get_relative_icon_size_for_zoom_level(), caja_icon_container_set_zoom_level(), caja_icon_get_larger_icon_size(), and caja_icon_get_smaller_icon_size().
CAJA_IS_ICON_INFO
#define CAJA_IS_ICON_INFO (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_ICON_INFO))
Definition at line 51 of file caja-icon-info.h.
CAJA_IS_ICON_INFO_CLASS
#define CAJA_IS_ICON_INFO_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_ICON_INFO))
Definition at line 52 of file caja-icon-info.h.
CAJA_TYPE_ICON_INFO
#define CAJA_TYPE_ICON_INFO (caja_icon_info_get_type ())
Definition at line 48 of file caja-icon-info.h.
Referenced by caja_icon_info_new_for_pixbuf().
CAJA_ZOOM_LEVEL_N_ENTRIES
#define CAJA_ZOOM_LEVEL_N_ENTRIES (CAJA_ZOOM_LEVEL_LARGEST + 1)
Definition at line 26 of file caja-icon-info.h.
Typedef Documentation
CajaIconInfo
typedef struct _CajaIconInfo CajaIconInfo
Definition at line 45 of file caja-icon-info.h.
CajaIconInfoClass
typedef struct _CajaIconInfoClass CajaIconInfoClass
Definition at line 46 of file caja-icon-info.h.
Enumeration Type Documentation
CajaZoomLevel
enum CajaZoomLevel
Enumerator
CAJA_ZOOM_LEVEL_SMALLEST
CAJA_ZOOM_LEVEL_SMALLER
CAJA_ZOOM_LEVEL_SMALL
CAJA_ZOOM_LEVEL_STANDARD
CAJA_ZOOM_LEVEL_LARGE
CAJA_ZOOM_LEVEL_LARGER
CAJA_ZOOM_LEVEL_LARGEST
Definition at line 15 of file caja-icon-info.h.
Function Documentation
caja_get_icon_size_for_stock_size()
gint caja_get_icon_size_for_stock_size (GtkIconSize size)
Definition at line 753 of file caja-icon-info.c.
References CAJA_ZOOM_LEVEL_STANDARD, and MAX.
Referenced by caja_action_from_menu_item(), caja_autorun_prepare_combo_box(), caja_bookmark_get_surface(), caja_spatial_window_set_location_button(), caja_toolbar_action_from_menu_item(), and caja_x_content_bar_set_x_content_type().
caja_get_icon_size_for_zoom_level()
guint caja_get_icon_size_for_zoom_level (CajaZoomLevel zoom_level)
Definition at line 661 of file caja-icon-info.c.
References CAJA_ICON_SIZE_LARGE, CAJA_ICON_SIZE_LARGER, CAJA_ICON_SIZE_LARGEST, CAJA_ICON_SIZE_SMALL, CAJA_ICON_SIZE_SMALLER, CAJA_ICON_SIZE_SMALLEST, CAJA_ICON_SIZE_STANDARD, CAJA_ZOOM_LEVEL_LARGE, CAJA_ZOOM_LEVEL_LARGER, CAJA_ZOOM_LEVEL_LARGEST, CAJA_ZOOM_LEVEL_SMALL, CAJA_ZOOM_LEVEL_SMALLER, CAJA_ZOOM_LEVEL_SMALLEST, and CAJA_ZOOM_LEVEL_STANDARD.
Referenced by caja_get_relative_icon_size_for_zoom_level(), caja_icon_container_set_zoom_level(), caja_icon_container_update_scroll_region(), and caja_icon_container_widget_to_file_operation_position().
caja_get_relative_icon_size_for_zoom_level()
float caja_get_relative_icon_size_for_zoom_level (CajaZoomLevel zoom_level)
Definition at line 684 of file caja-icon-info.c.
References caja_get_icon_size_for_zoom_level(), and CAJA_ICON_SIZE_STANDARD.
caja_icon_get_emblem_size_for_icon_size()
guint caja_icon_get_emblem_size_for_icon_size (guint size)
Definition at line 765 of file caja-icon-info.c.
caja_icon_get_larger_icon_size()
guint caja_icon_get_larger_icon_size (guint size)
Definition at line 693 of file caja-icon-info.c.
References CAJA_ICON_SIZE_LARGE, CAJA_ICON_SIZE_LARGER, CAJA_ICON_SIZE_LARGEST, CAJA_ICON_SIZE_SMALL, CAJA_ICON_SIZE_SMALLER, CAJA_ICON_SIZE_SMALLEST, and CAJA_ICON_SIZE_STANDARD.
caja_icon_get_smaller_icon_size()
guint caja_icon_get_smaller_icon_size (guint size)
Definition at line 723 of file caja-icon-info.c.
References CAJA_ICON_SIZE_LARGE, CAJA_ICON_SIZE_LARGER, CAJA_ICON_SIZE_LARGEST, CAJA_ICON_SIZE_SMALL, CAJA_ICON_SIZE_SMALLER, CAJA_ICON_SIZE_SMALLEST, and CAJA_ICON_SIZE_STANDARD.
caja_icon_info_clear_caches()
void caja_icon_info_clear_caches (void)
Definition at line 273 of file caja-icon-info.c.
Referenced by caja_emblem_rename_emblem().
caja_icon_info_get_attach_points()
gboolean caja_icon_info_get_attach_points (CajaIconInfo * icon, GdkPoint ** points, gint * n_points)
Definition at line 635 of file caja-icon-info.c.
Referenced by caja_icon_container_update_icon().
caja_icon_info_get_display_name()
const char * caja_icon_info_get_display_name (CajaIconInfo * icon)
Definition at line 644 of file caja-icon-info.c.
caja_icon_info_get_embedded_rect()
gboolean caja_icon_info_get_embedded_rect (CajaIconInfo * icon, GdkRectangle * rectangle)
Definition at line 627 of file caja-icon-info.c.
Referenced by caja_icon_container_update_icon().
caja_icon_info_get_pixbuf()
GdkPixbuf * caja_icon_info_get_pixbuf (CajaIconInfo * icon)
Definition at line 503 of file caja-icon-info.c.
References caja_default_file_icon, caja_default_file_icon_height, caja_default_file_icon_width, caja_icon_info_get_pixbuf_nodefault(), NULL, and TRUE.
Referenced by caja_file_get_icon(), caja_icon_container_update_icon(), caja_icon_info_get_pixbuf_at_size(), and caja_icon_info_get_surface().
caja_icon_info_get_pixbuf_at_size()
GdkPixbuf * caja_icon_info_get_pixbuf_at_size (CajaIconInfo * icon, gsize forced_size)
Definition at line 584 of file caja-icon-info.c.
References caja_icon_info_get_pixbuf(), MAX, and NULL.
Referenced by caja_icon_container_update_icon(), caja_icon_info_get_surface_at_size(), and caja_x_content_bar_set_x_content_type().
caja_icon_info_get_pixbuf_nodefault()
GdkPixbuf * caja_icon_info_get_pixbuf_nodefault (CajaIconInfo * icon)
Definition at line 465 of file caja-icon-info.c.
References FALSE, and NULL.
Referenced by caja_file_get_emblem_pixbufs(), caja_icon_info_get_pixbuf(), caja_icon_info_get_pixbuf_nodefault_at_size(), caja_icon_info_get_surface_nodefault(), and caja_window_slot_update_icon().
caja_icon_info_get_pixbuf_nodefault_at_size()
GdkPixbuf * caja_icon_info_get_pixbuf_nodefault_at_size (CajaIconInfo * icon, gsize forced_size)
Definition at line 538 of file caja-icon-info.c.
References caja_icon_info_get_pixbuf_nodefault(), MAX, and NULL.
Referenced by caja_file_get_emblem_pixbufs(), and caja_icon_info_get_surface_nodefault_at_size().
caja_icon_info_get_surface()
cairo_surface_t * caja_icon_info_get_surface (CajaIconInfo * icon)
Definition at line 525 of file caja-icon-info.c.
References caja_icon_info_get_pixbuf(), and NULL.
Referenced by caja_file_get_icon_surface().
caja_icon_info_get_surface_at_size()
cairo_surface_t * caja_icon_info_get_surface_at_size (CajaIconInfo * icon, gsize forced_size)
Definition at line 613 of file caja-icon-info.c.
References caja_icon_info_get_pixbuf_at_size(), and NULL.
Referenced by caja_autorun_prepare_combo_box(), caja_bookmark_get_surface(), and caja_file_get_icon_surface().
caja_icon_info_get_surface_nodefault()
cairo_surface_t * caja_icon_info_get_surface_nodefault (CajaIconInfo * icon)
Definition at line 490 of file caja-icon-info.c.
References caja_icon_info_get_pixbuf_nodefault(), and NULL.
caja_icon_info_get_surface_nodefault_at_size()
cairo_surface_t * caja_icon_info_get_surface_nodefault_at_size (CajaIconInfo * icon, gsize forced_size)
Definition at line 567 of file caja-icon-info.c.
References caja_icon_info_get_pixbuf_nodefault_at_size(), and NULL.
caja_icon_info_get_type()
GType caja_icon_info_get_type (void)
caja_icon_info_get_used_name()
const char * caja_icon_info_get_used_name (CajaIconInfo * icon)
Definition at line 649 of file caja-icon-info.c.
Referenced by caja_launch_application_by_uri(), and caja_window_slot_update_icon().
caja_icon_info_is_fallback()
gboolean caja_icon_info_is_fallback (CajaIconInfo * icon)
Definition at line 66 of file caja-icon-info.c.
References NULL.
caja_icon_info_lookup()
CajaIconInfo * caja_icon_info_lookup (GIcon * icon, int size, int scale)
Definition at line 324 of file caja-icon-info.c.
References caja_icon_info_new_for_pixbuf(), key, NULL, and TRUE.
Referenced by caja_autorun_prepare_combo_box(), caja_bookmark_get_surface(), caja_file_get_emblem_pixbufs(), caja_file_get_icon(), caja_icon_info_lookup_from_name(), caja_icon_info_lookup_from_path(), and caja_x_content_bar_set_x_content_type().
caja_icon_info_lookup_from_name()
CajaIconInfo * caja_icon_info_lookup_from_name (const char * name, int size, int scale)
Definition at line 434 of file caja-icon-info.c.
References caja_icon_info_lookup(), and name.
caja_icon_info_lookup_from_path()
CajaIconInfo * caja_icon_info_lookup_from_path (const char * path, int size, int scale)
Definition at line 448 of file caja-icon-info.c.
References caja_icon_info_lookup().
caja_icon_info_new_for_pixbuf()
CajaIconInfo * caja_icon_info_new_for_pixbuf (GdkPixbuf * pixbuf, int scale)
References name.
caja_icon_theme_can_render()
gboolean caja_icon_theme_can_render (GThemedIcon * icon)
Definition at line 782 of file caja-icon-info.c.
References FALSE, idx, NULL, and TRUE.
caja_user_special_directory_get_gicon()
GIcon * caja_user_special_directory_get_gicon (GUserDirectory directory)
Definition at line 802 of file caja-icon-info.c.
References ICON_CASE.