MATE Desktop Environment: caja-directory-background.h File Reference
caja-directory-background.h File Reference
#include <eel/eel-background.h>
#include "caja-file.h"
#include "caja-icon-container.h"
Functions
void caja_connect_background_to_file_metadata (GtkWidget *widget, CajaFile *file, GdkDragAction default_drag_action)
void caja_connect_desktop_background_to_settings (CajaIconContainer *icon_container)
Function Documentation
caja_connect_background_to_file_metadata()
void caja_connect_background_to_file_metadata (GtkWidget * widget, CajaFile * file, GdkDragAction default_drag_action)
Definition at line 235 of file caja-directory-background.c.
References CAJA_FILE_ATTRIBUTE_INFO, caja_file_monitor_add(), caja_file_monitor_remove(), caja_file_ref(), caja_file_unref(), CAJA_IS_FILE, caja_preferences, CAJA_PREFERENCES_BACKGROUND_COLOR, CAJA_PREFERENCES_BACKGROUND_SET, CAJA_PREFERENCES_BACKGROUND_URI, eel_get_widget_background(), and NULL.
caja_connect_desktop_background_to_settings()
void caja_connect_desktop_background_to_settings (CajaIconContainer * icon_container)
Definition at line 384 of file caja-directory-background.c.
References eel_background_set_desktop(), eel_bg_load_from_gsettings(), eel_get_widget_background(), mate_background_preferences, NULL, and TRUE.