MATE Desktop Environment: caja-file.h File Reference
caja-file.h File Reference
#include <gtk/gtk.h>
#include <gio/gio.h>
#include "caja-file-attributes.h"
#include "caja-icon-info.h"
Classes
struct CajaFile
struct CajaFileClass
Macros
#define CAJA_FILE_DEFINED
#define CAJA_TYPE_FILE caja_file_get_type()
#define CAJA_FILE(obj)
#define CAJA_FILE_CLASS(klass)
#define CAJA_IS_FILE(obj)
#define CAJA_IS_FILE_CLASS(klass)
#define CAJA_FILE_GET_CLASS(obj)
#define CAJA_FILE_EMBLEM_NAME_SYMBOLIC_LINK "symbolic-link"
#define CAJA_FILE_EMBLEM_NAME_CANT_READ "noread"
#define CAJA_FILE_EMBLEM_NAME_CANT_WRITE "nowrite"
#define CAJA_FILE_EMBLEM_NAME_TRASH "trash"
#define CAJA_FILE_EMBLEM_NAME_NOTE "note"
#define CAJA_FILE_EMBLEM_NAME_DESKTOP "desktop"
#define CAJA_FILE_EMBLEM_NAME_SHARED "shared"
#define CAJA_FILE_ATTRIBUTES_FOR_ICON (CAJA_FILE_ATTRIBUTE_INFO | CAJA_FILE_ATTRIBUTE_LINK_INFO | CAJA_FILE_ATTRIBUTE_THUMBNAIL)
#define UNDEFINED_TIME ((time_t) (-1))
Typedefs
typedef void(* CajaFileCallback) (CajaFile *file, gpointer callback_data)
typedef void(* CajaFileListCallback) (GList *file_list, gpointer callback_data)
typedef void(* CajaFileOperationCallback) (CajaFile *file, GFile *result_location, GError *error, gpointer callback_data)
typedef int(* CajaWidthMeasureCallback) (const char *string, void *context)
typedef char *(* CajaTruncateCallback) (const char *string, int width, void *context)
typedef void CajaFileListHandle
typedef struct _CajaFilePrivate CajaFilePrivate
Enumerations
enum CajaFileSortType {
CAJA_FILE_SORT_NONE , CAJA_FILE_SORT_BY_DISPLAY_NAME , CAJA_FILE_SORT_BY_DIRECTORY , CAJA_FILE_SORT_BY_SIZE ,
CAJA_FILE_SORT_BY_TYPE , CAJA_FILE_SORT_BY_MTIME , CAJA_FILE_SORT_BY_BTIME , CAJA_FILE_SORT_BY_ATIME ,
CAJA_FILE_SORT_BY_EMBLEMS , CAJA_FILE_SORT_BY_TRASHED_TIME , CAJA_FILE_SORT_BY_SIZE_ON_DISK , CAJA_FILE_SORT_BY_EXTENSION
}
enum CajaRequestStatus { CAJA_REQUEST_NOT_STARTED , CAJA_REQUEST_IN_PROGRESS , CAJA_REQUEST_DONE }
enum CajaFileIconFlags {
CAJA_FILE_ICON_FLAGS_NONE = 0 , CAJA_FILE_ICON_FLAGS_USE_THUMBNAILS = (1<<0) , CAJA_FILE_ICON_FLAGS_IGNORE_VISITING = (1<<1) , CAJA_FILE_ICON_FLAGS_EMBEDDING_TEXT = (1<<2) ,
CAJA_FILE_ICON_FLAGS_FOR_DRAG_ACCEPT = (1<<3) , CAJA_FILE_ICON_FLAGS_FOR_OPEN_FOLDER = (1<<4) , CAJA_FILE_ICON_FLAGS_FORCE_THUMBNAIL_SIZE = (1<<5) , CAJA_FILE_ICON_FLAGS_USE_MOUNT_ICON = (1<<6) ,
CAJA_FILE_ICON_FLAGS_USE_MOUNT_ICON_AS_EMBLEM = (1<<7)
}
enum CajaDateType {
CAJA_DATE_TYPE_MODIFIED , CAJA_DATE_TYPE_CREATED , CAJA_DATE_TYPE_CHANGED , CAJA_DATE_TYPE_ACCESSED ,
CAJA_DATE_TYPE_PERMISSIONS_CHANGED , CAJA_DATE_TYPE_TRASHED
}
Functions
GType caja_file_get_type (void)
CajaFile * caja_file_get (GFile *location)
CajaFile * caja_file_get_by_uri (const char *uri)
CajaFile * caja_file_get_existing (GFile *location)
CajaFile * caja_file_get_existing_by_uri (const char *uri)
CajaFile * caja_file_ref (CajaFile *file)
void caja_file_unref (CajaFile *file)
void caja_file_monitor_add (CajaFile *file, gconstpointer client, CajaFileAttributes attributes)
void caja_file_monitor_remove (CajaFile *file, gconstpointer client)
void caja_file_refresh_info (CajaFile *file)
void caja_file_call_when_ready (CajaFile *file, CajaFileAttributes attributes, CajaFileCallback callback, gpointer callback_data)
void caja_file_cancel_call_when_ready (CajaFile *file, CajaFileCallback callback, gpointer callback_data)
gboolean caja_file_check_if_ready (CajaFile *file, CajaFileAttributes attributes)
void caja_file_invalidate_attributes (CajaFile *file, CajaFileAttributes attributes)
void caja_file_invalidate_all_attributes (CajaFile *file)
gboolean caja_file_contains_text (CajaFile *file)
gboolean caja_file_is_binary (CajaFile *file)
char * caja_file_get_display_name (CajaFile *file)
char * caja_file_get_edit_name (CajaFile *file)
char * caja_file_get_name (CajaFile *file)
GFile * caja_file_get_location (CajaFile *file)
char * caja_file_get_description (CajaFile *file)
char * caja_file_get_uri (CajaFile *file)
char * caja_file_get_uri_scheme (CajaFile *file)
CajaFile * caja_file_get_parent (CajaFile *file)
GFile * caja_file_get_parent_location (CajaFile *file)
char * caja_file_get_parent_uri (CajaFile *file)
char * caja_file_get_parent_uri_for_display (CajaFile *file)
gboolean caja_file_can_get_size (CajaFile *file)
goffset caja_file_get_size (CajaFile *file)
goffset caja_file_get_size_on_disk (CajaFile *file)
time_t caja_file_get_mtime (CajaFile *file)
GFileType caja_file_get_file_type (CajaFile *file)
char * caja_file_get_mime_type (CajaFile *file)
gboolean caja_file_is_mime_type (CajaFile *file, const char *mime_type)
gboolean caja_file_is_launchable (CajaFile *file)
gboolean caja_file_is_symbolic_link (CajaFile *file)
gboolean caja_file_is_mountpoint (CajaFile *file)
GMount * caja_file_get_mount (CajaFile *file)
char * caja_file_get_volume_free_space (CajaFile *file)
char * caja_file_get_volume_name (CajaFile *file)
char * caja_file_get_symbolic_link_target_path (CajaFile *file)
char * caja_file_get_symbolic_link_target_uri (CajaFile *file)
gboolean caja_file_is_broken_symbolic_link (CajaFile *file)
gboolean caja_file_is_caja_link (CajaFile *file)
gboolean caja_file_is_executable (CajaFile *file)
gboolean caja_file_is_directory (CajaFile *file)
gboolean caja_file_is_user_special_directory (CajaFile *file, GUserDirectory special_directory)
gboolean caja_file_is_archive (CajaFile *file)
gboolean caja_file_is_in_trash (CajaFile *file)
gboolean caja_file_is_in_desktop (CajaFile *file)
gboolean caja_file_is_home (CajaFile *file)
gboolean caja_file_is_desktop_directory (CajaFile *file)
GError * caja_file_get_file_info_error (CajaFile *file)
gboolean caja_file_get_directory_item_count (CajaFile *file, guint *count, gboolean *count_unreadable)
void caja_file_recompute_deep_counts (CajaFile *file)
CajaRequestStatus caja_file_get_deep_counts (CajaFile *file, guint *directory_count, guint *file_count, guint *unreadable_directory_count, goffset *total_size, goffset *total_size_on_disk, gboolean force)
gboolean caja_file_should_show_thumbnail (CajaFile *file)
gboolean caja_file_should_show_directory_item_count (CajaFile *file)
gboolean caja_file_should_show_type (CajaFile *file)
GList * caja_file_get_keywords (CajaFile *file)
void caja_file_set_keywords (CajaFile *file, GList *keywords)
GList * caja_file_get_emblem_icons (CajaFile *file, char **exclude)
GList * caja_file_get_emblem_pixbufs (CajaFile *file, int size, gboolean force_size, char **exclude)
char * caja_file_get_top_left_text (CajaFile *file)
char * caja_file_peek_top_left_text (CajaFile *file, gboolean need_large_text, gboolean *got_top_left_text)
void caja_file_set_attributes (CajaFile *file, GFileInfo *attributes, CajaFileOperationCallback callback, gpointer callback_data)
GFilesystemPreviewType caja_file_get_filesystem_use_preview (CajaFile *file)
char * caja_file_get_filesystem_id (CajaFile *file)
CajaFile * caja_file_get_trash_original_file (CajaFile *file)
gboolean caja_file_can_get_permissions (CajaFile *file)
gboolean caja_file_can_set_permissions (CajaFile *file)
guint caja_file_get_permissions (CajaFile *file)
gboolean caja_file_can_get_owner (CajaFile *file)
gboolean caja_file_can_set_owner (CajaFile *file)
gboolean caja_file_can_get_group (CajaFile *file)
gboolean caja_file_can_set_group (CajaFile *file)
char * caja_file_get_owner_name (CajaFile *file)
char * caja_file_get_group_name (CajaFile *file)
GList * caja_get_user_names (void)
GList * caja_get_all_group_names (void)
GList * caja_file_get_settable_group_names (CajaFile *file)
gboolean caja_file_can_get_selinux_context (CajaFile *file)
char * caja_file_get_selinux_context (CajaFile *file)
gboolean caja_file_can_read (CajaFile *file)
gboolean caja_file_can_write (CajaFile *file)
gboolean caja_file_can_execute (CajaFile *file)
gboolean caja_file_can_rename (CajaFile *file)
gboolean caja_file_can_delete (CajaFile *file)
gboolean caja_file_can_trash (CajaFile *file)
gboolean caja_file_can_mount (CajaFile *file)
gboolean caja_file_can_unmount (CajaFile *file)
gboolean caja_file_can_eject (CajaFile *file)
gboolean caja_file_can_start (CajaFile *file)
gboolean caja_file_can_start_degraded (CajaFile *file)
gboolean caja_file_can_stop (CajaFile *file)
GDriveStartStopType caja_file_get_start_stop_type (CajaFile *file)
gboolean caja_file_can_poll_for_media (CajaFile *file)
gboolean caja_file_is_media_check_automatic (CajaFile *file)
void caja_file_mount (CajaFile *file, GMountOperation *mount_op, GCancellable *cancellable, CajaFileOperationCallback callback, gpointer callback_data)
void caja_file_unmount (CajaFile *file, GMountOperation *mount_op, GCancellable *cancellable, CajaFileOperationCallback callback, gpointer callback_data)
void caja_file_eject (CajaFile *file, GMountOperation *mount_op, GCancellable *cancellable, CajaFileOperationCallback callback, gpointer callback_data)
void caja_file_start (CajaFile *file, GMountOperation *start_op, GCancellable *cancellable, CajaFileOperationCallback callback, gpointer callback_data)
void caja_file_stop (CajaFile *file, GMountOperation *mount_op, GCancellable *cancellable, CajaFileOperationCallback callback, gpointer callback_data)
void caja_file_poll_for_media (CajaFile *file)
void caja_file_set_owner (CajaFile *file, const char *user_name_or_id, CajaFileOperationCallback callback, gpointer callback_data)
void caja_file_set_group (CajaFile *file, const char *group_name_or_id, CajaFileOperationCallback callback, gpointer callback_data)
void caja_file_set_permissions (CajaFile *file, guint32 permissions, CajaFileOperationCallback callback, gpointer callback_data)
void caja_file_rename (CajaFile *file, const char *new_name, CajaFileOperationCallback callback, gpointer callback_data)
void caja_file_cancel (CajaFile *file, CajaFileOperationCallback callback, gpointer callback_data)
gboolean caja_file_is_gone (CajaFile *file)
gboolean caja_file_is_not_yet_confirmed (CajaFile *file)
char * caja_file_get_metadata (CajaFile *file, const char *key, const char *default_metadata)
GList * caja_file_get_metadata_list (CajaFile *file, const char *key)
void caja_file_set_metadata (CajaFile *file, const char *key, const char *default_metadata, const char *metadata)
void caja_file_set_metadata_list (CajaFile *file, const char *key, GList *list)
gboolean caja_file_get_boolean_metadata (CajaFile *file, const char *key, gboolean default_metadata)
void caja_file_set_boolean_metadata (CajaFile *file, const char *key, gboolean default_metadata, gboolean metadata)
int caja_file_get_integer_metadata (CajaFile *file, const char *key, int default_metadata)
void caja_file_set_integer_metadata (CajaFile *file, const char *key, int default_metadata, int metadata)
time_t caja_file_get_time_metadata (CajaFile *file, const char *key)
void caja_file_set_time_metadata (CajaFile *file, const char *key, time_t time)
char * caja_file_get_string_attribute (CajaFile *file, const char *attribute_name)
char * caja_file_get_string_attribute_q (CajaFile *file, GQuark attribute_q)
char * caja_file_get_string_attribute_with_default (CajaFile *file, const char *attribute_name)
char * caja_file_get_string_attribute_with_default_q (CajaFile *file, GQuark attribute_q)
char * caja_file_fit_modified_date_as_string (CajaFile *file, int width, CajaWidthMeasureCallback measure_callback, CajaTruncateCallback truncate_callback, void *measure_truncate_context)
gboolean caja_file_matches_uri (CajaFile *file, const char *uri)
gboolean caja_file_is_local (CajaFile *file)
CajaFileSortType caja_file_get_default_sort_type (CajaFile *file, gboolean *reversed)
const gchar * caja_file_get_default_sort_attribute (CajaFile *file, gboolean *reversed)
int caja_file_compare_for_sort (CajaFile *file_1, CajaFile *file_2, CajaFileSortType sort_type, gboolean directories_first, gboolean reversed)
int caja_file_compare_for_sort_by_attribute (CajaFile *file_1, CajaFile *file_2, const char *attribute, gboolean directories_first, gboolean reversed)
int caja_file_compare_for_sort_by_attribute_q (CajaFile *file_1, CajaFile *file_2, GQuark attribute, gboolean directories_first, gboolean reversed)
gboolean caja_file_is_date_sort_attribute_q (GQuark attribute)
int caja_file_compare_display_name (CajaFile *file_1, const char *pattern)
int caja_file_compare_location (CajaFile *file_1, CajaFile *file_2)
gboolean caja_file_is_hidden_file (CajaFile *file)
gboolean caja_file_should_show (CajaFile *file, gboolean show_hidden, gboolean show_foreign, gboolean show_backup)
GList * caja_file_list_filter_hidden (GList *files, gboolean show_hidden)
gboolean caja_file_is_launcher (CajaFile *file)
gboolean caja_file_is_foreign_link (CajaFile *file)
gboolean caja_file_is_trusted_link (CajaFile *file)
gboolean caja_file_has_activation_uri (CajaFile *file)
char * caja_file_get_activation_uri (CajaFile *file)
GFile * caja_file_get_activation_location (CajaFile *file)
char * caja_file_get_drop_target_uri (CajaFile *file)
char * caja_file_get_custom_icon (CajaFile *file)
GIcon * caja_file_get_gicon (CajaFile *file, CajaFileIconFlags flags)
CajaIconInfo * caja_file_get_icon (CajaFile *file, int size, int scale, CajaFileIconFlags flags)
cairo_surface_t * caja_file_get_icon_surface (CajaFile *file, int size, gboolean force_size, int scale, CajaFileIconFlags flags)
gboolean caja_file_has_open_window (CajaFile *file)
void caja_file_set_has_open_window (CajaFile *file, gboolean has_open_window)
gboolean caja_file_is_thumbnailing (CajaFile *file)
GList * caja_file_list_ref (GList *file_list)
void caja_file_list_unref (GList *file_list)
void caja_file_list_free (GList *file_list)
GList * caja_file_list_copy (GList *file_list)
GList * caja_file_list_sort_by_display_name (GList *file_list)
void caja_file_list_call_when_ready (GList *file_list, CajaFileAttributes attributes, CajaFileListHandle **handle, CajaFileListCallback callback, gpointer callback_data)
void caja_file_list_cancel_call_when_ready (CajaFileListHandle *handle)
void caja_file_dump (CajaFile *file)
Macro Definition Documentation
CAJA_FILE
#define CAJA_FILE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_FILE, CajaFile))
Definition at line 48 of file caja-file.h.
Referenced by caja_debug_log_with_file_list(), caja_desktop_icon_file_new(), caja_desktop_icon_file_remove(), caja_desktop_icon_file_update(), caja_directory_find_file_by_name(), caja_directory_match_pattern(), caja_directory_moved(), caja_directory_notify_files_moved(), caja_file_emit_changed(), caja_file_list_call_when_ready(), caja_file_list_cancel_call_when_ready(), caja_file_new_from_info(), caja_file_queue_head(), caja_file_updated_deep_count_in_progress(), caja_restore_files_from_trash(), caja_search_directory_file_update_display_name(), caja_trashed_files_get_original_directories(), fm_properties_window_present(), and G_DEFINE_TYPE_WITH_PRIVATE().
CAJA_FILE_ATTRIBUTES_FOR_ICON
#define CAJA_FILE_ATTRIBUTES_FOR_ICON (CAJA_FILE_ATTRIBUTE_INFO | CAJA_FILE_ATTRIBUTE_LINK_INFO | CAJA_FILE_ATTRIBUTE_THUMBNAIL)
Definition at line 121 of file caja-file.h.
Referenced by fm_directory_view_add_subdirectory().
CAJA_FILE_CLASS
#define CAJA_FILE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_FILE, CajaFileClass))
Definition at line 50 of file caja-file.h.
Referenced by caja_file_call_when_ready(), caja_file_cancel_call_when_ready(), caja_file_check_if_ready(), caja_file_get_date(), caja_file_get_deep_counts(), caja_file_get_directory_item_count(), caja_file_list_cancel_call_when_ready(), caja_file_monitor_add(), caja_file_monitor_remove(), caja_file_set_metadata(), and caja_file_set_metadata_list().
CAJA_FILE_DEFINED
#define CAJA_FILE_DEFINED
Definition at line 43 of file caja-file.h.
CAJA_FILE_EMBLEM_NAME_CANT_READ
#define CAJA_FILE_EMBLEM_NAME_CANT_READ "noread"
Definition at line 100 of file caja-file.h.
CAJA_FILE_EMBLEM_NAME_CANT_WRITE
#define CAJA_FILE_EMBLEM_NAME_CANT_WRITE "nowrite"
Definition at line 101 of file caja-file.h.
CAJA_FILE_EMBLEM_NAME_DESKTOP
#define CAJA_FILE_EMBLEM_NAME_DESKTOP "desktop"
Definition at line 104 of file caja-file.h.
CAJA_FILE_EMBLEM_NAME_NOTE
#define CAJA_FILE_EMBLEM_NAME_NOTE "note"
Definition at line 103 of file caja-file.h.
CAJA_FILE_EMBLEM_NAME_SHARED
#define CAJA_FILE_EMBLEM_NAME_SHARED "shared"
Definition at line 105 of file caja-file.h.
CAJA_FILE_EMBLEM_NAME_SYMBOLIC_LINK
#define CAJA_FILE_EMBLEM_NAME_SYMBOLIC_LINK "symbolic-link"
Definition at line 99 of file caja-file.h.
CAJA_FILE_EMBLEM_NAME_TRASH
#define CAJA_FILE_EMBLEM_NAME_TRASH "trash"
Definition at line 102 of file caja-file.h.
Referenced by caja_file_get_emblem_icons().
CAJA_FILE_GET_CLASS
#define CAJA_FILE_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_FILE, CajaFileClass))
Definition at line 56 of file caja-file.h.
Referenced by caja_file_clear_info(), caja_file_eject(), caja_file_mount(), caja_file_poll_for_media(), caja_file_start(), caja_file_stop(), and caja_file_unmount().
CAJA_IS_FILE
#define CAJA_IS_FILE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_FILE))
Definition at line 52 of file caja-file.h.
Referenced by caja_connect_background_to_file_metadata(), caja_directory_add_file(), caja_directory_add_file_monitors(), caja_directory_call_when_ready_internal(), caja_directory_cancel_callback_internal(), caja_directory_contains_file(), caja_directory_get_for_file(), caja_directory_monitor_remove_internal(), caja_directory_remove_file(), caja_directory_remove_file_monitors(), caja_drag_can_accept_items(), caja_drag_file_receive_dropped_keyword(), caja_file_call_when_ready(), caja_file_can_delete(), caja_file_can_eject(), caja_file_can_execute(), caja_file_can_mount(), caja_file_can_poll_for_media(), caja_file_can_read(), caja_file_can_rename(), caja_file_can_start(), caja_file_can_start_degraded(), caja_file_can_stop(), caja_file_can_trash(), caja_file_can_unmount(), caja_file_can_write(), caja_file_cancel_call_when_ready(), caja_file_changed(), caja_file_check_if_ready(), caja_file_emit_changed(), caja_file_get_activation_location(), caja_file_get_activation_uri(), caja_file_get_boolean_metadata(), caja_file_get_date(), caja_file_get_deep_counts(), caja_file_get_directory_item_count(), caja_file_get_drop_target_uri(), caja_file_get_emblem_icons(), caja_file_get_integer_metadata(), caja_file_get_keywords(), caja_file_get_location(), caja_file_get_metadata(), caja_file_get_metadata_list(), caja_file_get_mime_type(), caja_file_get_parent(), caja_file_get_parent_location(), caja_file_get_parent_uri(), caja_file_get_parent_uri_for_display(), caja_file_get_selinux_context(), caja_file_get_start_stop_type(), caja_file_get_uri(), caja_file_get_uri_scheme(), caja_file_is_broken_symbolic_link(), caja_file_is_gone(), caja_file_is_in_trash(), caja_file_is_local(), caja_file_is_media_check_automatic(), caja_file_is_mime_type(), caja_file_is_not_yet_confirmed(), caja_file_is_thumbnailing(), caja_file_matches_uri(), caja_file_monitor_add(), caja_file_monitor_remove(), caja_file_peek_top_left_text(), caja_file_ref(), caja_file_rename(), caja_file_set_boolean_metadata(), caja_file_set_integer_metadata(), caja_file_set_is_thumbnailing(), caja_file_set_keywords(), caja_file_set_metadata(), caja_file_set_metadata_list(), caja_file_should_get_top_left_text(), caja_file_should_show_directory_item_count(), caja_file_should_show_type(), caja_file_unref(), caja_file_update_name_and_directory(), caja_file_updated_deep_count_in_progress(), caja_mime_activate_file(), fm_directory_view_can_accept_item(), and fm_rename_file().
CAJA_IS_FILE_CLASS
#define CAJA_IS_FILE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_FILE))
Definition at line 54 of file caja-file.h.
CAJA_TYPE_FILE
#define CAJA_TYPE_FILE caja_file_get_type()
Definition at line 47 of file caja-file.h.
Referenced by EEL_CLASS_BOILERPLATE(), EEL_CLASS_BOILERPLATE(), and G_DEFINE_TYPE().
UNDEFINED_TIME
#define UNDEFINED_TIME ((time_t) (-1))
Definition at line 378 of file caja-file.h.
Referenced by caja_directory_schedule_position_set(), caja_file_get_time_metadata(), caja_file_set_time_metadata(), caja_icon_container_begin_loading(), and caja_icon_container_clear().
Typedef Documentation
CajaFileCallback
typedef void(* CajaFileCallback) (CajaFile *file, gpointer callback_data)
Definition at line 107 of file caja-file.h.
CajaFileListCallback
typedef void(* CajaFileListCallback) (GList *file_list, gpointer callback_data)
Definition at line 109 of file caja-file.h.
CajaFileListHandle
typedef void CajaFileListHandle
Definition at line 123 of file caja-file.h.
CajaFileOperationCallback
typedef void(* CajaFileOperationCallback) (CajaFile *file, GFile *result_location, GError *error, gpointer callback_data)
Definition at line 111 of file caja-file.h.
CajaFilePrivate
typedef struct _CajaFilePrivate CajaFilePrivate
Definition at line 497 of file caja-file.h.
CajaTruncateCallback
typedef char *(* CajaTruncateCallback) (const char *string, int width, void *context)
Definition at line 117 of file caja-file.h.
CajaWidthMeasureCallback
typedef int(* CajaWidthMeasureCallback) (const char *string, void *context)
Definition at line 115 of file caja-file.h.
Enumeration Type Documentation
CajaDateType
enum CajaDateType
Enumerator
CAJA_DATE_TYPE_MODIFIED
CAJA_DATE_TYPE_CREATED
CAJA_DATE_TYPE_CHANGED
CAJA_DATE_TYPE_ACCESSED
CAJA_DATE_TYPE_PERMISSIONS_CHANGED
CAJA_DATE_TYPE_TRASHED
Definition at line 508 of file caja-file.h.
CajaFileIconFlags
enum CajaFileIconFlags
Enumerator
CAJA_FILE_ICON_FLAGS_NONE
CAJA_FILE_ICON_FLAGS_USE_THUMBNAILS
CAJA_FILE_ICON_FLAGS_IGNORE_VISITING
CAJA_FILE_ICON_FLAGS_EMBEDDING_TEXT
CAJA_FILE_ICON_FLAGS_FOR_DRAG_ACCEPT
CAJA_FILE_ICON_FLAGS_FOR_OPEN_FOLDER
CAJA_FILE_ICON_FLAGS_FORCE_THUMBNAIL_SIZE
CAJA_FILE_ICON_FLAGS_USE_MOUNT_ICON
CAJA_FILE_ICON_FLAGS_USE_MOUNT_ICON_AS_EMBLEM
Definition at line 82 of file caja-file.h.
CajaFileSortType
enum CajaFileSortType
Enumerator
CAJA_FILE_SORT_NONE
CAJA_FILE_SORT_BY_DISPLAY_NAME
CAJA_FILE_SORT_BY_DIRECTORY
CAJA_FILE_SORT_BY_SIZE
CAJA_FILE_SORT_BY_TYPE
CAJA_FILE_SORT_BY_MTIME
CAJA_FILE_SORT_BY_BTIME
CAJA_FILE_SORT_BY_ATIME
CAJA_FILE_SORT_BY_EMBLEMS
CAJA_FILE_SORT_BY_TRASHED_TIME
CAJA_FILE_SORT_BY_SIZE_ON_DISK
CAJA_FILE_SORT_BY_EXTENSION
Definition at line 59 of file caja-file.h.
CajaRequestStatus
enum CajaRequestStatus
Enumerator
CAJA_REQUEST_NOT_STARTED
CAJA_REQUEST_IN_PROGRESS
CAJA_REQUEST_DONE
Definition at line 75 of file caja-file.h.
Function Documentation
caja_file_call_when_ready()
void caja_file_call_when_ready (CajaFile * file, CajaFileAttributes attributes, CajaFileCallback callback, gpointer callback_data)
Definition at line 7845 of file caja-file.c.
References CAJA_FILE_CLASS, CAJA_IS_FILE, EEL_CALL_METHOD, and NULL.
Referenced by caja_file_list_call_when_ready(), caja_window_load_view_as_menus(), and fm_properties_window_present().
caja_file_can_delete()
gboolean caja_file_can_delete (CajaFile * file)
Definition at line 1546 of file caja-file.c.
References caja_file_is_gone(), caja_file_is_self_owned(), CAJA_IS_FILE, _CajaFilePrivate::can_delete, CajaFile::details, and FALSE.
caja_file_can_eject()
gboolean caja_file_can_eject (CajaFile * file)
Definition at line 1039 of file caja-file.c.
References CAJA_IS_FILE, _CajaFilePrivate::can_eject, CajaFile::details, FALSE, _CajaFilePrivate::mount, and NULL.
caja_file_can_execute()
gboolean caja_file_can_execute (CajaFile * file)
Definition at line 1013 of file caja-file.c.
References CAJA_IS_FILE, _CajaFilePrivate::can_execute, CajaFile::details, and FALSE.
Referenced by caja_file_is_launchable().
caja_file_can_get_group()
gboolean caja_file_can_get_group (CajaFile * file)
Definition at line 5866 of file caja-file.c.
References CajaFile::details, and _CajaFilePrivate::gid.
Referenced by caja_file_can_set_group().
caja_file_can_get_owner()
gboolean caja_file_can_get_owner (CajaFile * file)
Definition at line 5686 of file caja-file.c.
References CajaFile::details, and _CajaFilePrivate::uid.
Referenced by caja_file_can_set_owner().
caja_file_can_get_permissions()
gboolean caja_file_can_get_permissions (CajaFile * file)
Definition at line 5395 of file caja-file.c.
References CajaFile::details, and _CajaFilePrivate::has_permissions.
Referenced by caja_file_get_permissions(), and caja_file_is_launchable().
caja_file_can_get_selinux_context()
gboolean caja_file_can_get_selinux_context (CajaFile * file)
Definition at line 5518 of file caja-file.c.
References CajaFile::details, NULL, and _CajaFilePrivate::selinux_context.
Referenced by caja_file_get_selinux_context().
caja_file_can_get_size()
gboolean caja_file_can_get_size (CajaFile * file)
Definition at line 5257 of file caja-file.c.
References CajaFile::details, and _CajaFilePrivate::size.
Referenced by fm_directory_view_display_selection_info().
caja_file_can_mount()
gboolean caja_file_can_mount (CajaFile * file)
Definition at line 1021 of file caja-file.c.
References CAJA_IS_FILE, _CajaFilePrivate::can_mount, CajaFile::details, and FALSE.
Referenced by caja_mime_activate_files().
caja_file_can_poll_for_media()
gboolean caja_file_can_poll_for_media (CajaFile * file)
Definition at line 1103 of file caja-file.c.
References CAJA_IS_FILE, _CajaFilePrivate::can_poll_for_media, CajaFile::details, FALSE, _CajaFilePrivate::mount, NULL, and TRUE.
caja_file_can_read()
gboolean caja_file_can_read (CajaFile * file)
Definition at line 973 of file caja-file.c.
References CAJA_IS_FILE, _CajaFilePrivate::can_read, CajaFile::details, and FALSE.
Referenced by caja_file_is_binary().
caja_file_can_rename()
gboolean caja_file_can_rename (CajaFile * file)
Definition at line 1503 of file caja-file.c.
References CAJA_DESKTOP_ICON_FILE, caja_desktop_icon_file_get_link(), caja_desktop_link_can_rename(), caja_file_is_gone(), caja_file_is_home(), caja_file_is_self_owned(), CAJA_IS_DESKTOP_ICON_FILE, CAJA_IS_FILE, _CajaFilePrivate::can_rename, CajaFile::details, FALSE, NULL, and TRUE.
caja_file_can_set_group()
gboolean caja_file_can_set_group (CajaFile * file)
Definition at line 5902 of file caja-file.c.
References caja_file_can_get_group(), CajaFile::details, FALSE, TRUE, and _CajaFilePrivate::uid.
Referenced by caja_file_get_settable_group_names(), and caja_file_set_group().
caja_file_can_set_owner()
gboolean caja_file_can_set_owner (CajaFile * file)
Definition at line 5722 of file caja-file.c.
References caja_file_can_get_owner(), and FALSE.
Referenced by caja_file_set_owner().
caja_file_can_set_permissions()
gboolean caja_file_can_set_permissions (CajaFile * file)
Definition at line 5413 of file caja-file.c.
References caja_file_is_local(), CajaFile::details, FALSE, TRUE, and _CajaFilePrivate::uid.
Referenced by caja_file_set_permissions().
caja_file_can_start()
gboolean caja_file_can_start (CajaFile * file)
Definition at line 1049 of file caja-file.c.
References CAJA_IS_FILE, _CajaFilePrivate::can_start, CajaFile::details, FALSE, _CajaFilePrivate::mount, NULL, and TRUE.
Referenced by caja_mime_activate_files().
caja_file_can_start_degraded()
gboolean caja_file_can_start_degraded (CajaFile * file)
Definition at line 1076 of file caja-file.c.
References CAJA_IS_FILE, _CajaFilePrivate::can_start_degraded, CajaFile::details, FALSE, _CajaFilePrivate::mount, NULL, and TRUE.
caja_file_can_stop()
gboolean caja_file_can_stop (CajaFile * file)
Definition at line 1157 of file caja-file.c.
References CAJA_IS_FILE, _CajaFilePrivate::can_stop, CajaFile::details, FALSE, _CajaFilePrivate::mount, NULL, and TRUE.
caja_file_can_trash()
gboolean caja_file_can_trash (CajaFile * file)
Definition at line 1564 of file caja-file.c.
References caja_file_is_gone(), caja_file_is_self_owned(), CAJA_IS_FILE, _CajaFilePrivate::can_trash, CajaFile::details, and FALSE.
caja_file_can_unmount()
gboolean caja_file_can_unmount (CajaFile * file)
Definition at line 1029 of file caja-file.c.
References CAJA_IS_FILE, _CajaFilePrivate::can_unmount, CajaFile::details, FALSE, _CajaFilePrivate::mount, and NULL.
caja_file_can_write()
gboolean caja_file_can_write (CajaFile * file)
Definition at line 993 of file caja-file.c.
References CAJA_IS_FILE, _CajaFilePrivate::can_write, CajaFile::details, and FALSE.
caja_file_cancel()
void caja_file_cancel (CajaFile * file, CajaFileOperationCallback callback, gpointer callback_data)
Definition at line 1991 of file caja-file.c.
References caja_file_operation_cancel(), CajaFile::details, NULL, op, and _CajaFilePrivate::operations_in_progress.
caja_file_cancel_call_when_ready()
void caja_file_cancel_call_when_ready (CajaFile * file, CajaFileCallback callback, gpointer callback_data)
Definition at line 7865 of file caja-file.c.
References CAJA_FILE_CLASS, CAJA_IS_FILE, EEL_CALL_METHOD, and NULL.
caja_file_check_if_ready()
gboolean caja_file_check_if_ready (CajaFile * file, CajaFileAttributes attributes)
Definition at line 7827 of file caja-file.c.
References CAJA_FILE_CLASS, CAJA_IS_FILE, EEL_CALL_METHOD_WITH_RETURN_VALUE, FALSE, NULL, and TRUE.
caja_file_compare_display_name()
int caja_file_compare_display_name (CajaFile * file_1, const char * pattern)
Definition at line 3671 of file caja-file.c.
References name, and NULL.
caja_file_compare_for_sort()
int caja_file_compare_for_sort (CajaFile * file_1, CajaFile * file_2, CajaFileSortType sort_type, gboolean directories_first, gboolean reversed)
caja_file_compare_for_sort: @file_1: A file object @file_2: Another file object @sort_type: Sort criterion @directories_first: Put all directories before any non-directories @reversed: Reverse the order of the items, except that the directories_first flag is still respected.
Return value: int < 0 if @file_1 should come before file_2 in a sorted list; int > 0 if @file_2 should come before file_1 in a sorted list; 0 if @file_1 and @file_2 are equal for this sort criterion. Note that each named sort type may actually break ties several ways, with the name of the sort criterion being the primary but not only differentiator.
Definition at line 3449 of file caja-file.c.
References CAJA_DATE_TYPE_ACCESSED, CAJA_DATE_TYPE_CREATED, CAJA_DATE_TYPE_MODIFIED, CAJA_DATE_TYPE_TRASHED, CAJA_FILE_SORT_BY_ATIME, CAJA_FILE_SORT_BY_BTIME, CAJA_FILE_SORT_BY_DIRECTORY, CAJA_FILE_SORT_BY_DISPLAY_NAME, CAJA_FILE_SORT_BY_EMBLEMS, CAJA_FILE_SORT_BY_EXTENSION, CAJA_FILE_SORT_BY_MTIME, CAJA_FILE_SORT_BY_SIZE, CAJA_FILE_SORT_BY_SIZE_ON_DISK, CAJA_FILE_SORT_BY_TRASHED_TIME, CAJA_FILE_SORT_BY_TYPE, FALSE, and TRUE.
Referenced by caja_file_compare_for_sort_by_attribute_q(), caja_self_check_file(), and fm_icon_view_compare_files().
caja_file_compare_for_sort_by_attribute()
int caja_file_compare_for_sort_by_attribute (CajaFile * file_1, CajaFile * file_2, const char * attribute, gboolean directories_first, gboolean reversed)
Definition at line 3650 of file caja-file.c.
References caja_file_compare_for_sort_by_attribute_q().
caja_file_compare_for_sort_by_attribute_q()
int caja_file_compare_for_sort_by_attribute_q (CajaFile * file_1, CajaFile * file_2, GQuark attribute, gboolean directories_first, gboolean reversed)
Definition at line 3554 of file caja-file.c.
References caja_file_compare_for_sort(), caja_file_get_string_attribute_q(), CAJA_FILE_SORT_BY_ATIME, CAJA_FILE_SORT_BY_BTIME, CAJA_FILE_SORT_BY_DISPLAY_NAME, CAJA_FILE_SORT_BY_EMBLEMS, CAJA_FILE_SORT_BY_EXTENSION, CAJA_FILE_SORT_BY_MTIME, CAJA_FILE_SORT_BY_SIZE, CAJA_FILE_SORT_BY_SIZE_ON_DISK, CAJA_FILE_SORT_BY_TRASHED_TIME, CAJA_FILE_SORT_BY_TYPE, and NULL.
Referenced by caja_file_compare_for_sort_by_attribute(), and fm_list_model_compare_func().
caja_file_compare_location()
int caja_file_compare_location (CajaFile * file_1, CajaFile * file_2)
Definition at line 2028 of file caja-file.c.
References caja_file_get_location().
caja_file_contains_text()
gboolean caja_file_contains_text (CajaFile * file)
Definition at line 7494 of file caja-file.c.
References caja_file_is_mime_type(), FALSE, and NULL.
Referenced by caja_file_peek_top_left_text().
caja_file_dump()
void caja_file_dump (CajaFile * file)
Definition at line 8085 of file caja-file.c.
References caja_file_get_uri(), _CajaFilePrivate::deep_size, _CajaFilePrivate::deep_size_on_disk, CajaFile::details, _CajaFilePrivate::get_info_failed, _CajaFilePrivate::got_file_info, _CajaFilePrivate::symlink_name, and _CajaFilePrivate::type.
caja_file_eject()
void caja_file_eject (CajaFile * file, GMountOperation * mount_op, GCancellable * cancellable, CajaFileOperationCallback callback, gpointer callback_data)
Definition at line 1285 of file caja-file.c.
References _, CAJA_FILE_GET_CLASS, caja_file_operations_unmount_mount_full(), caja_file_ref(), _CajaFilePrivate::can_eject, data, CajaFile::details, error, _CajaFilePrivate::mount, NULL, and TRUE.
caja_file_fit_modified_date_as_string()
char * caja_file_fit_modified_date_as_string (CajaFile * file, int width, CajaWidthMeasureCallback measure_callback, CajaTruncateCallback truncate_callback, void * measure_truncate_context)
Definition at line 4967 of file caja-file.c.
References CAJA_DATE_TYPE_MODIFIED.
caja_file_get()
CajaFile * caja_file_get (GFile * location)
Definition at line 719 of file caja-file.c.
References TRUE.
Referenced by caja_autorun_launch_for_mount(), caja_compute_title_for_location(), caja_directory_schedule_position_set(), caja_drag_default_drop_action_for_icons(), caja_file_conflict_dialog_new(), caja_file_get_trash_original_file(), caja_spatial_window_set_location_button(), caja_window_slot_set_content_view(), and G_DEFINE_TYPE_WITH_PRIVATE().
caja_file_get_activation_location()
GFile * caja_file_get_activation_location (CajaFile * file)
Definition at line 4216 of file caja-file.c.
References _CajaFilePrivate::activation_uri, caja_file_get_location(), CAJA_IS_FILE, CajaFile::details, and NULL.
caja_file_get_activation_uri()
char * caja_file_get_activation_uri (CajaFile * file)
Definition at line 4204 of file caja-file.c.
References _CajaFilePrivate::activation_uri, caja_file_get_uri(), CAJA_IS_FILE, CajaFile::details, and NULL.
Referenced by caja_launch_application().
caja_file_get_boolean_metadata()
gboolean caja_file_get_boolean_metadata (CajaFile * file, const char * key, gboolean default_metadata)
Definition at line 3896 of file caja-file.c.
References caja_file_get_metadata(), CAJA_IS_FILE, FALSE, key, NULL, and TRUE.
caja_file_get_by_uri()
CajaFile * caja_file_get_by_uri (const char * uri)
Definition at line 744 of file caja-file.c.
References TRUE.
Referenced by caja_directory_get_corresponding_file(), caja_launch_application_by_uri(), caja_self_check_directory(), caja_self_check_file(), caja_undostack_manager_redo(), caja_undostack_manager_undo(), fm_directory_view_pop_up_location_context_menu(), fm_tree_model_add_root_uri(), and fm_tree_model_remove_root_uri().
caja_file_get_custom_icon()
char * caja_file_get_custom_icon (CajaFile * file)
Definition at line 4703 of file caja-file.c.
References _CajaFilePrivate::custom_icon, CajaFile::details, _CajaFilePrivate::got_link_info, and NULL.
caja_file_get_deep_counts()
CajaRequestStatus caja_file_get_deep_counts (CajaFile * file, guint * directory_count, guint * file_count, guint * unreadable_directory_count, goffset * total_size, goffset * total_size_on_disk, gboolean force)
Definition at line 5200 of file caja-file.c.
References CAJA_FILE_CLASS, caja_file_should_show_directory_item_count(), CAJA_IS_FILE, CAJA_REQUEST_DONE, CAJA_REQUEST_NOT_STARTED, _CajaFilePrivate::deep_counts_status, CajaFile::details, EEL_CALL_METHOD_WITH_RETURN_VALUE, and NULL.
Referenced by caja_file_get_string_attribute_with_default_q().
caja_file_get_default_sort_attribute()
const gchar * caja_file_get_default_sort_attribute (CajaFile * file, gboolean * reversed)
Definition at line 8238 of file caja-file.c.
References FALSE, and NULL.
caja_file_get_default_sort_type()
CajaFileSortType caja_file_get_default_sort_type (CajaFile * file, gboolean * reversed)
Definition at line 8212 of file caja-file.c.
References CAJA_FILE_SORT_BY_MTIME, CAJA_FILE_SORT_BY_TRASHED_TIME, CAJA_FILE_SORT_NONE, FALSE, and NULL.
caja_file_get_description()
char * caja_file_get_description (CajaFile * file)
Definition at line 4145 of file caja-file.c.
References _CajaFilePrivate::description, and CajaFile::details.
Referenced by caja_compute_title_for_location().
caja_file_get_directory_item_count()
gboolean caja_file_get_directory_item_count (CajaFile * file, guint * count, gboolean * count_unreadable)
Definition at line 5155 of file caja-file.c.
References CAJA_FILE_CLASS, caja_file_is_directory(), caja_file_should_show_directory_item_count(), CAJA_IS_FILE, EEL_CALL_METHOD_WITH_RETURN_VALUE, FALSE, and NULL.
Referenced by caja_file_get_string_attribute_with_default_q(), and fm_directory_view_display_selection_info().
caja_file_get_display_name()
char * caja_file_get_display_name (CajaFile * file)
Definition at line 4111 of file caja-file.c.
Referenced by caja_compute_title_for_location(), caja_directory_match_pattern(), caja_file_get_string_attribute_q(), caja_file_rename(), caja_mime_activate_files(), caja_restore_files_from_trash(), caja_spatial_window_set_location_button(), fm_directory_view_display_selection_info(), fm_rename_file(), fm_report_error_loading_directory(), fm_report_error_renaming_file(), fm_report_error_setting_group(), fm_report_error_setting_owner(), and fm_report_error_setting_permissions().
caja_file_get_drop_target_uri()
char * caja_file_get_drop_target_uri (CajaFile * file)
Definition at line 4228 of file caja-file.c.
References CAJA_DESKTOP_ICON_FILE, caja_desktop_icon_file_get_link(), caja_desktop_link_get_activation_location(), caja_file_get_location(), caja_file_get_uri(), caja_file_is_caja_link(), CAJA_IS_DESKTOP_ICON_FILE, CAJA_IS_FILE, caja_link_local_get_link_uri(), and NULL.
caja_file_get_edit_name()
char * caja_file_get_edit_name (CajaFile * file)
Definition at line 4117 of file caja-file.c.
References CajaFile::details, _CajaFilePrivate::edit_name, and NULL.
caja_file_get_emblem_icons()
GList * caja_file_get_emblem_icons (CajaFile * file, char ** exclude)
Definition at line 6922 of file caja-file.c.
References CAJA_FILE_EMBLEM_NAME_TRASH, caja_file_get_keywords(), caja_file_get_uri(), CAJA_IS_FILE, EEL_TRASH_URI, and NULL.
Referenced by caja_file_get_emblem_pixbufs().
caja_file_get_emblem_pixbufs()
GList * caja_file_get_emblem_pixbufs (CajaFile * file, int size, gboolean force_size, char ** exclude)
Definition at line 6983 of file caja-file.c.
References caja_file_get_emblem_icons(), caja_icon_info_get_pixbuf_nodefault(), caja_icon_info_get_pixbuf_nodefault_at_size(), caja_icon_info_lookup(), and NULL.
caja_file_get_existing()
CajaFile * caja_file_get_existing (GFile * location)
Definition at line 725 of file caja-file.c.
References FALSE.
Referenced by caja_directory_notify_files_added(), caja_directory_notify_files_changed(), caja_directory_notify_files_moved(), and caja_directory_notify_files_removed().
caja_file_get_existing_by_uri()
CajaFile * caja_file_get_existing_by_uri (const char * uri)
Definition at line 731 of file caja-file.c.
References FALSE.
Referenced by caja_directory_get_existing_corresponding_file(), caja_drag_default_drop_action_for_icons(), and fm_directory_view_move_copy_items().
caja_file_get_file_info_error()
GError * caja_file_get_file_info_error (CajaFile * file)
Definition at line 7474 of file caja-file.c.
References CajaFile::details, _CajaFilePrivate::get_info_error, _CajaFilePrivate::get_info_failed, and NULL.
Referenced by caja_spatial_window_set_location_button().
caja_file_get_file_type()
GFileType caja_file_get_file_type (CajaFile * file)
Definition at line 6838 of file caja-file.c.
References CajaFile::details, NULL, and _CajaFilePrivate::type.
Referenced by caja_file_is_broken_symbolic_link(), and caja_file_is_directory().
caja_file_get_filesystem_id()
char * caja_file_get_filesystem_id (CajaFile * file)
Definition at line 7640 of file caja-file.c.
References CajaFile::details, and _CajaFilePrivate::filesystem_id.
caja_file_get_filesystem_use_preview()
GFilesystemPreviewType caja_file_get_filesystem_use_preview (CajaFile * file)
Definition at line 4345 of file caja-file.c.
References caja_file_get_parent(), CajaFile::details, _CajaFilePrivate::filesystem_use_preview, and NULL.
Referenced by caja_file_should_show_thumbnail().
caja_file_get_gicon()
GIcon * caja_file_get_gicon (CajaFile * file, CajaFileIconFlags flags)
Definition at line 4415 of file caja-file.c.
References caja_file_get_mount(), caja_file_has_open_window(), CAJA_FILE_ICON_FLAGS_EMBEDDING_TEXT, CAJA_FILE_ICON_FLAGS_FOR_DRAG_ACCEPT, CAJA_FILE_ICON_FLAGS_FOR_OPEN_FOLDER, CAJA_FILE_ICON_FLAGS_IGNORE_VISITING, CAJA_FILE_ICON_FLAGS_USE_MOUNT_ICON, CAJA_FILE_ICON_FLAGS_USE_MOUNT_ICON_AS_EMBLEM, CajaFile::details, FALSE, _CajaFilePrivate::icon, name, NULL, and TRUE.
Referenced by caja_file_get_icon().
caja_file_get_group_name()
char * caja_file_get_group_name (CajaFile * file)
Definition at line 5884 of file caja-file.c.
References CajaFile::details, and _CajaFilePrivate::group.
Referenced by caja_file_get_string_attribute_q(), and caja_file_set_group().
caja_file_get_icon()
CajaIconInfo * caja_file_get_icon (CajaFile * file, int size, int scale, CajaFileIconFlags flags)
Definition at line 4559 of file caja-file.c.
References cached_thumbnail_size, caja_can_thumbnail(), caja_can_thumbnail_internally(), caja_create_thumbnail(), CAJA_FILE_ATTRIBUTE_THUMBNAIL, caja_file_get_gicon(), CAJA_FILE_ICON_FLAGS_FORCE_THUMBNAIL_SIZE, CAJA_FILE_ICON_FLAGS_USE_THUMBNAILS, caja_file_invalidate_attributes(), caja_file_should_show_thumbnail(), caja_icon_info_get_pixbuf(), caja_icon_info_lookup(), caja_icon_info_new_for_pixbuf(), CAJA_ICON_SIZE_SMALLEST, CAJA_ICON_SIZE_STANDARD, caja_ui_frame_image(), _CajaFilePrivate::can_read, CajaFile::details, ICON_NAME_THUMBNAIL_LOADING, _CajaFilePrivate::is_launcher, _CajaFilePrivate::is_thumbnailing, MAX, _CajaFilePrivate::mime_type, NULL, _CajaFilePrivate::thumbnail, _CajaFilePrivate::thumbnail_path, _CajaFilePrivate::thumbnail_wants_original, _CajaFilePrivate::thumbnailing_failed, and TRUE.
Referenced by caja_file_get_icon_surface(), and caja_launch_application_by_uri().
caja_file_get_icon_surface()
cairo_surface_t * caja_file_get_icon_surface (CajaFile * file, int size, gboolean force_size, int scale, CajaFileIconFlags flags)
Definition at line 4682 of file caja-file.c.
References caja_file_get_icon(), caja_icon_info_get_surface(), and caja_icon_info_get_surface_at_size().
Referenced by caja_spatial_window_set_location_button().
caja_file_get_integer_metadata()
int caja_file_get_integer_metadata (CajaFile * file, const char * key, int default_metadata)
Definition at line 3929 of file caja-file.c.
References caja_file_get_metadata(), CAJA_IS_FILE, key, and NULL.
caja_file_get_keywords()
GList * caja_file_get_keywords (CajaFile * file)
Definition at line 7055 of file caja-file.c.
References caja_file_get_metadata_list(), CAJA_IS_FILE, CAJA_METADATA_KEY_EMBLEMS, CajaFile::details, _CajaFilePrivate::extension_emblems, NULL, and _CajaFilePrivate::pending_extension_emblems.
Referenced by caja_drag_file_receive_dropped_keyword(), and caja_file_get_emblem_icons().
caja_file_get_location()
GFile * caja_file_get_location (CajaFile * file)
Definition at line 1582 of file caja-file.c.
References caja_file_is_self_owned(), CAJA_IS_FILE, CajaDirectory::details, CajaFile::details, _CajaFilePrivate::directory, _CajaDirectoryPrivate::location, _CajaFilePrivate::name, and NULL.
Referenced by caja_file_compare_location(), caja_file_get_activation_location(), caja_file_get_drop_target_uri(), caja_file_get_symbolic_link_target_uri(), caja_file_get_uri(), caja_file_get_volume_free_space(), caja_file_get_volume_name(), caja_file_is_binary(), caja_file_is_user_special_directory(), caja_file_matches_uri(), caja_file_refresh_info(), caja_file_rename(), caja_file_set_attributes(), and caja_restore_files_from_trash().
caja_file_get_metadata()
char * caja_file_get_metadata (CajaFile * file, const char * key, const char * default_metadata)
Definition at line 3784 of file caja-file.c.
References CAJA_IS_FILE, caja_metadata_get_id(), CajaFile::details, key, _CajaFilePrivate::metadata, and NULL.
Referenced by caja_file_get_boolean_metadata(), caja_file_get_integer_metadata(), and caja_file_get_time_metadata().
caja_file_get_metadata_list()
GList * caja_file_get_metadata_list (CajaFile * file, const char * key)
Definition at line 3811 of file caja-file.c.
References CAJA_IS_FILE, caja_metadata_get_id(), CajaFile::details, key, _CajaFilePrivate::metadata, METADATA_ID_IS_LIST_MASK, and NULL.
Referenced by caja_file_get_keywords().
caja_file_get_mime_type()
char * caja_file_get_mime_type (CajaFile * file)
Definition at line 6857 of file caja-file.c.
References CAJA_IS_FILE, CajaFile::details, _CajaFilePrivate::mime_type, and NULL.
Referenced by caja_can_thumbnail(), caja_can_thumbnail_internally(), caja_create_thumbnail(), caja_file_get_string_attribute_q(), caja_file_is_archive(), caja_mime_get_applications_for_file(), caja_mime_get_default_application_for_file(), caja_mime_has_any_applications_for_file(), and caja_recent_add_file().
caja_file_get_mount()
GMount * caja_file_get_mount (CajaFile * file)
Definition at line 7123 of file caja-file.c.
References CajaFile::details, _CajaFilePrivate::mount, and NULL.
Referenced by caja_file_get_gicon().
caja_file_get_mtime()
time_t caja_file_get_mtime (CajaFile * file)
Definition at line 5302 of file caja-file.c.
References CajaFile::details, and _CajaFilePrivate::mtime.
Referenced by caja_can_thumbnail().
caja_file_get_name()
char * caja_file_get_name (CajaFile * file)
Definition at line 4129 of file caja-file.c.
References CajaFile::details, and _CajaFilePrivate::name.
Referenced by caja_self_check_file().
caja_file_get_owner_name()
char * caja_file_get_owner_name (CajaFile * file)
Definition at line 5704 of file caja-file.c.
References FALSE.
caja_file_get_parent()
CajaFile * caja_file_get_parent (CajaFile * file)
Definition at line 949 of file caja-file.c.
References caja_directory_get_corresponding_file(), caja_file_is_self_owned(), CAJA_IS_FILE, CajaFile::details, _CajaFilePrivate::directory, and NULL.
Referenced by caja_file_get_filesystem_use_preview(), and caja_trashed_files_get_original_directories().
caja_file_get_parent_location()
GFile * caja_file_get_parent_location (CajaFile * file)
Definition at line 936 of file caja-file.c.
References caja_directory_get_location(), caja_file_is_self_owned(), CAJA_IS_FILE, CajaFile::details, _CajaFilePrivate::directory, and NULL.
Referenced by caja_file_get_parent_uri_for_display().
caja_file_get_parent_uri()
char * caja_file_get_parent_uri (CajaFile * file)
Definition at line 923 of file caja-file.c.
References caja_directory_get_uri(), caja_file_is_self_owned(), CAJA_IS_FILE, CajaFile::details, and _CajaFilePrivate::directory.
caja_file_get_parent_uri_for_display()
char * caja_file_get_parent_uri_for_display (CajaFile * file)
Definition at line 892 of file caja-file.c.
References caja_file_get_parent_location(), and CAJA_IS_FILE.
Referenced by caja_file_get_string_attribute_q().
caja_file_get_permissions()
guint caja_file_get_permissions (CajaFile * file)
Definition at line 5442 of file caja-file.c.
References caja_file_can_get_permissions(), CajaFile::details, and _CajaFilePrivate::permissions.
caja_file_get_selinux_context()
char * caja_file_get_selinux_context (CajaFile * file)
Definition at line 5534 of file caja-file.c.
References caja_file_can_get_selinux_context(), CAJA_IS_FILE, CajaFile::details, NULL, and _CajaFilePrivate::selinux_context.
Referenced by caja_file_get_string_attribute_q().
caja_file_get_settable_group_names()
GList * caja_file_get_settable_group_names (CajaFile * file)
Definition at line 5989 of file caja-file.c.
References caja_file_can_set_group(), caja_get_all_group_names(), CajaFile::details, NULL, and _CajaFilePrivate::uid.
caja_file_get_size()
goffset caja_file_get_size (CajaFile * file)
Definition at line 5272 of file caja-file.c.
References CajaFile::details, and _CajaFilePrivate::size.
Referenced by caja_file_should_show_thumbnail(), and fm_directory_view_display_selection_info().
caja_file_get_size_on_disk()
goffset caja_file_get_size_on_disk (CajaFile * file)
Definition at line 5293 of file caja-file.c.
References CajaFile::details, and _CajaFilePrivate::size_on_disk.
caja_file_get_start_stop_type()
GDriveStartStopType caja_file_get_start_stop_type (CajaFile * file)
Definition at line 1184 of file caja-file.c.
References CAJA_IS_FILE, CajaFile::details, FALSE, _CajaFilePrivate::mount, NULL, and _CajaFilePrivate::start_stop_type.
caja_file_get_string_attribute()
char * caja_file_get_string_attribute (CajaFile * file, const char * attribute_name)
Definition at line 6635 of file caja-file.c.
References caja_file_get_string_attribute_q().
caja_file_get_string_attribute_q()
char * caja_file_get_string_attribute_q (CajaFile * file, GQuark attribute_q)
Definition at line 6515 of file caja-file.c.
References CAJA_DATE_TYPE_ACCESSED, CAJA_DATE_TYPE_CHANGED, CAJA_DATE_TYPE_CREATED, CAJA_DATE_TYPE_MODIFIED, CAJA_DATE_TYPE_PERMISSIONS_CHANGED, CAJA_DATE_TYPE_TRASHED, caja_file_get_display_name(), caja_file_get_group_name(), caja_file_get_mime_type(), caja_file_get_parent_uri_for_display(), caja_file_get_selinux_context(), caja_file_get_symbolic_link_target_path(), caja_file_get_uri(), caja_file_get_volume_free_space(), caja_file_get_volume_name(), CajaFile::details, _CajaFilePrivate::extension_attributes, FALSE, NULL, _CajaFilePrivate::pending_extension_attributes, and TRUE.
Referenced by caja_file_compare_for_sort_by_attribute_q(), caja_file_get_string_attribute(), and caja_file_get_string_attribute_with_default_q().
caja_file_get_string_attribute_with_default()
char * caja_file_get_string_attribute_with_default (CajaFile * file, const char * attribute_name)
Definition at line 6732 of file caja-file.c.
References caja_file_get_string_attribute_with_default_q().
caja_file_get_string_attribute_with_default_q()
char * caja_file_get_string_attribute_with_default_q (CajaFile * file, GQuark attribute_q)
Definition at line 6658 of file caja-file.c.
References _, caja_file_get_deep_counts(), caja_file_get_directory_item_count(), caja_file_get_string_attribute_q(), caja_file_is_directory(), caja_file_should_show_directory_item_count(), CAJA_REQUEST_DONE, FALSE, and NULL.
Referenced by caja_file_get_string_attribute_with_default().
caja_file_get_symbolic_link_target_path()
char * caja_file_get_symbolic_link_target_path (CajaFile * file)
Definition at line 7300 of file caja-file.c.
References caja_file_is_symbolic_link(), CajaFile::details, and _CajaFilePrivate::symlink_name.
Referenced by caja_file_get_string_attribute_q().
caja_file_get_symbolic_link_target_uri()
char * caja_file_get_symbolic_link_target_uri (CajaFile * file)
Definition at line 7319 of file caja-file.c.
References caja_file_get_location(), caja_file_is_symbolic_link(), CajaFile::details, NULL, and _CajaFilePrivate::symlink_name.
caja_file_get_time_metadata()
time_t caja_file_get_time_metadata (CajaFile * file, const char * key)
Definition at line 3986 of file caja-file.c.
References caja_file_get_metadata(), key, NULL, and UNDEFINED_TIME.
caja_file_get_top_left_text()
char * caja_file_get_top_left_text (CajaFile * file)
Definition at line 7634 of file caja-file.c.
References caja_file_peek_top_left_text(), FALSE, and NULL.
caja_file_get_trash_original_file()
CajaFile * caja_file_get_trash_original_file (CajaFile * file)
Definition at line 7646 of file caja-file.c.
References caja_file_get(), CajaFile::details, NULL, and _CajaFilePrivate::trash_orig_path.
Referenced by caja_trashed_files_get_original_directories().
caja_file_get_type()
GType caja_file_get_type (void)
References key, and mime_type.
caja_file_get_uri()
char * caja_file_get_uri (CajaFile * file)
Definition at line 1599 of file caja-file.c.
References caja_file_get_location(), CAJA_IS_FILE, and NULL.
Referenced by caja_can_thumbnail(), caja_create_thumbnail(), caja_debug_log_with_file_list(), caja_directory_get_for_file(), caja_file_dump(), caja_file_get_activation_uri(), caja_file_get_drop_target_uri(), caja_file_get_emblem_icons(), caja_file_get_string_attribute_q(), caja_file_rename(), caja_file_set_group(), caja_file_set_owner(), caja_file_set_permissions(), caja_file_should_show_type(), caja_get_clipboard_callback(), caja_recent_add_file(), fm_directory_view_new_file(), and fm_rename_file().
caja_file_get_uri_scheme()
char * caja_file_get_uri_scheme (CajaFile * file)
Definition at line 1614 of file caja-file.c.
References caja_directory_get_location(), CAJA_IS_FILE, CajaDirectory::details, CajaFile::details, _CajaFilePrivate::directory, _CajaDirectoryPrivate::location, and NULL.
Referenced by caja_mime_get_applications_for_file(), caja_mime_get_default_application_for_file(), and caja_mime_has_any_applications_for_file().
caja_file_get_volume_free_space()
char * caja_file_get_volume_free_space (CajaFile * file)
Definition at line 7223 of file caja-file.c.
References caja_directory_get_for_file(), caja_directory_unref(), caja_file_get_location(), caja_preferences, CAJA_PREFERENCES_USE_IEC_UNITS, CajaDirectory::details, _CajaDirectoryPrivate::free_space, _CajaDirectoryPrivate::free_space_read, and NULL.
Referenced by caja_file_get_string_attribute_q(), and fm_directory_view_display_selection_info().
caja_file_get_volume_name()
char * caja_file_get_volume_name (CajaFile * file)
Definition at line 7271 of file caja-file.c.
References caja_file_get_location(), and NULL.
Referenced by caja_file_get_string_attribute_q().
caja_file_has_activation_uri()
gboolean caja_file_has_activation_uri (CajaFile * file)
Definition at line 4194 of file caja-file.c.
References _CajaFilePrivate::activation_uri, CajaFile::details, and NULL.
caja_file_has_open_window()
gboolean caja_file_has_open_window (CajaFile * file)
Definition at line 7992 of file caja-file.c.
References CajaFile::details, and _CajaFilePrivate::has_open_window.
Referenced by caja_file_get_gicon().
caja_file_invalidate_all_attributes()
void caja_file_invalidate_all_attributes (CajaFile * file)
Definition at line 8068 of file caja-file.c.
References caja_file_get_all_attributes(), and caja_file_invalidate_attributes().
caja_file_invalidate_attributes()
void caja_file_invalidate_attributes (CajaFile * file, CajaFileAttributes attributes)
Definition at line 8035 of file caja-file.c.
References caja_directory_add_file_to_work_queue(), caja_directory_async_state_changed(), caja_directory_cancel_loading_file_attributes(), caja_file_invalidate_attributes_internal(), CajaFile::details, and _CajaFilePrivate::directory.
Referenced by caja_directory_notify_files_moved(), caja_file_get_icon(), caja_file_invalidate_all_attributes(), caja_file_invalidate_count_and_mime_list(), caja_file_rename(), and caja_file_set_display_name().
caja_file_is_archive()
gboolean caja_file_is_archive (CajaFile * file)
Definition at line 7420 of file caja-file.c.
References caja_file_get_mime_type(), FALSE, mime_type, NULL, and TRUE.
Referenced by caja_drag_default_drop_action_for_icons(), and fm_directory_view_move_copy_items().
caja_file_is_binary()
gboolean caja_file_is_binary (CajaFile * file)
Definition at line 7516 of file caja-file.c.
References caja_file_can_read(), caja_file_get_location(), FALSE, NULL, and TRUE.
caja_file_is_broken_symbolic_link()
gboolean caja_file_is_broken_symbolic_link (CajaFile * file)
Definition at line 7169 of file caja-file.c.
References caja_file_get_file_type(), CAJA_IS_FILE, FALSE, and NULL.
caja_file_is_caja_link()
gboolean caja_file_is_caja_link (CajaFile * file)
Definition at line 7361 of file caja-file.c.
References CajaFile::details, FALSE, _CajaFilePrivate::mime_type, and NULL.
Referenced by caja_file_get_drop_target_uri().
caja_file_is_date_sort_attribute_q()
gboolean caja_file_is_date_sort_attribute_q (GQuark attribute)
Definition at line 6738 of file caja-file.c.
References FALSE, and TRUE.
caja_file_is_desktop_directory()
gboolean caja_file_is_desktop_directory (CajaFile * file)
Definition at line 1459 of file caja-file.c.
References caja_is_desktop_directory_file(), CajaDirectory::details, CajaFile::details, _CajaFilePrivate::directory, FALSE, _CajaDirectoryPrivate::location, _CajaFilePrivate::name, and NULL.
caja_file_is_directory()
gboolean caja_file_is_directory (CajaFile * file)
Definition at line 7381 of file caja-file.c.
References caja_file_get_file_type().
Referenced by caja_file_conflict_dialog_new(), caja_file_get_directory_item_count(), caja_file_get_string_attribute_with_default_q(), caja_file_is_launchable(), caja_file_updated_deep_count_in_progress(), caja_mime_file_opens_in_view(), fm_directory_view_display_selection_info(), and fm_list_model_add_file().
caja_file_is_executable()
gboolean caja_file_is_executable (CajaFile * file)
Definition at line 7567 of file caja-file.c.
References _CajaFilePrivate::can_execute, CajaFile::details, FALSE, and _CajaFilePrivate::has_permissions.
Referenced by caja_file_is_launchable().
caja_file_is_foreign_link()
gboolean caja_file_is_foreign_link (CajaFile * file)
Definition at line 4182 of file caja-file.c.
References CajaFile::details, and _CajaFilePrivate::is_foreign_link.
Referenced by caja_file_should_show().
caja_file_is_gone()
gboolean caja_file_is_gone (CajaFile * file)
Definition at line 7788 of file caja-file.c.
References CAJA_IS_FILE, CajaFile::details, FALSE, and _CajaFilePrivate::is_gone.
Referenced by caja_debug_log_with_file_list(), caja_directory_contains_file(), caja_file_can_delete(), caja_file_can_rename(), caja_file_can_trash(), caja_file_rename(), and G_DEFINE_TYPE_WITH_PRIVATE().
caja_file_is_hidden_file()
gboolean caja_file_is_hidden_file (CajaFile * file)
Definition at line 3685 of file caja-file.c.
References CajaFile::details, and _CajaFilePrivate::is_hidden.
Referenced by caja_file_should_show(), and fm_tree_model_set_show_hidden_files().
caja_file_is_home()
gboolean caja_file_is_home (CajaFile * file)
Definition at line 3724 of file caja-file.c.
References caja_is_home_directory_file(), CajaDirectory::details, CajaFile::details, _CajaFilePrivate::directory, FALSE, _CajaDirectoryPrivate::location, _CajaFilePrivate::name, and NULL.
Referenced by caja_file_can_rename().
caja_file_is_in_desktop()
gboolean caja_file_is_in_desktop (CajaFile * file)
Definition at line 3737 of file caja-file.c.
References caja_is_desktop_directory(), CajaDirectory::details, CajaFile::details, _CajaFilePrivate::directory, FALSE, and _CajaDirectoryPrivate::location.
Referenced by caja_file_should_show().
caja_file_is_in_trash()
gboolean caja_file_is_in_trash (CajaFile * file)
Definition at line 7466 of file caja-file.c.
References caja_directory_is_in_trash(), CAJA_IS_FILE, CajaFile::details, and _CajaFilePrivate::directory.
Referenced by caja_file_should_show(), and caja_get_columns_for_file().
caja_file_is_launchable()
gboolean caja_file_is_launchable (CajaFile * file)
Definition at line 6894 of file caja-file.c.
References caja_file_can_execute(), caja_file_can_get_permissions(), caja_file_is_directory(), caja_file_is_executable(), CajaFile::details, FALSE, _CajaFilePrivate::mime_type, and NULL.
caja_file_is_launcher()
gboolean caja_file_is_launcher (CajaFile * file)
Definition at line 4176 of file caja-file.c.
References CajaFile::details, and _CajaFilePrivate::is_launcher.
Referenced by caja_drag_default_drop_action_for_icons(), and fm_directory_view_move_copy_items().
caja_file_is_local()
gboolean caja_file_is_local (CajaFile * file)
Definition at line 2046 of file caja-file.c.
References caja_directory_is_local(), CAJA_IS_FILE, CajaFile::details, _CajaFilePrivate::directory, and FALSE.
Referenced by caja_file_can_set_permissions(), caja_file_should_show_thumbnail(), and fm_directory_view_new_file().
caja_file_is_media_check_automatic()
gboolean caja_file_is_media_check_automatic (CajaFile * file)
Definition at line 1130 of file caja-file.c.
References CAJA_IS_FILE, CajaFile::details, FALSE, _CajaFilePrivate::is_media_check_automatic, _CajaFilePrivate::mount, NULL, and TRUE.
caja_file_is_mime_type()
gboolean caja_file_is_mime_type (CajaFile * file, const char * mime_type)
Definition at line 6881 of file caja-file.c.
References CAJA_IS_FILE, CajaFile::details, FALSE, _CajaFilePrivate::mime_type, mime_type, and NULL.
Referenced by caja_file_contains_text().
caja_file_is_mountpoint()
gboolean caja_file_is_mountpoint (CajaFile * file)
Definition at line 7117 of file caja-file.c.
References CajaFile::details, and _CajaFilePrivate::is_mountpoint.
caja_file_is_not_yet_confirmed()
gboolean caja_file_is_not_yet_confirmed (CajaFile * file)
Definition at line 7805 of file caja-file.c.
References CAJA_IS_FILE, CajaFile::details, FALSE, and _CajaFilePrivate::got_file_info.
caja_file_is_symbolic_link()
gboolean caja_file_is_symbolic_link (CajaFile * file)
Definition at line 7111 of file caja-file.c.
References CajaFile::details, and _CajaFilePrivate::is_symlink.
Referenced by caja_file_get_symbolic_link_target_path(), and caja_file_get_symbolic_link_target_uri().
caja_file_is_thumbnailing()
gboolean caja_file_is_thumbnailing (CajaFile * file)
Definition at line 8010 of file caja-file.c.
References CAJA_IS_FILE, CajaFile::details, FALSE, and _CajaFilePrivate::is_thumbnailing.
caja_file_is_trusted_link()
gboolean caja_file_is_trusted_link (CajaFile * file)
Definition at line 4188 of file caja-file.c.
References CajaFile::details, and _CajaFilePrivate::is_trusted_link.
caja_file_is_user_special_directory()
gboolean caja_file_is_user_special_directory (CajaFile * file, GUserDirectory special_directory)
Definition at line 7396 of file caja-file.c.
References caja_file_get_location(), and FALSE.
Referenced by G_DEFINE_TYPE_WITH_CODE().
caja_file_list_call_when_ready()
void caja_file_list_call_when_ready (GList * file_list, CajaFileAttributes attributes, CajaFileListHandle ** handle, CajaFileListCallback callback, gpointer callback_data)
Definition at line 8343 of file caja-file.c.
References CAJA_FILE, caja_file_call_when_ready(), data, file_list, and NULL.
caja_file_list_cancel_call_when_ready()
void caja_file_list_cancel_call_when_ready (CajaFileListHandle * handle)
Definition at line 8377 of file caja-file.c.
References CAJA_FILE, CAJA_FILE_CLASS, data, EEL_CALL_METHOD, and NULL.
caja_file_list_copy()
GList * caja_file_list_copy (GList * list)
caja_file_list_copy
Copy the list of files, making a new ref of each, @list: GList of files.
Definition at line 8174 of file caja-file.c.
References caja_file_list_ref().
Referenced by caja_file_list_filter_hidden(), fm_list_model_set_highlight_for_files(), and fm_tree_model_set_highlight_for_files().
caja_file_list_filter_hidden()
GList * caja_file_list_filter_hidden (GList * files, gboolean show_hidden)
Definition at line 3763 of file caja-file.c.
References caja_file_list_copy(), caja_file_list_free(), eel_g_list_partition(), and SHOW_HIDDEN.
caja_file_list_free()
void caja_file_list_free (GList * list)
caja_file_list_free
Free a list of files after unrefing them. @list: GList of files.
Definition at line 8161 of file caja-file.c.
References caja_file_list_unref().
Referenced by caja_application_open_location(), caja_directory_match_pattern(), caja_directory_monitor_add_internal(), caja_directory_moved(), caja_directory_notify_files_moved(), caja_file_emit_changed(), caja_file_list_filter_hidden(), caja_file_queue_destroy(), caja_file_updated_deep_count_in_progress(), caja_self_check_file(), emit_change_signals_for_all_files(), fm_directory_view_display_selection_info(), fm_directory_view_notify_selection_changed(), fm_list_model_set_highlight_for_files(), fm_properties_window_present(), and fm_tree_model_set_highlight_for_files().
caja_file_list_ref()
GList * caja_file_list_ref (GList * list)
caja_file_list_ref
Ref all the files in a list. @list: GList of files.
Definition at line 8136 of file caja-file.c.
References caja_file_ref(), and NULL.
Referenced by caja_file_list_copy(), caja_self_check_file(), and emit_change_signals_for_all_files().
caja_file_list_sort_by_display_name()
GList * caja_file_list_sort_by_display_name (GList * list)
caja_file_list_sort_by_display_name
Sort the list of files by file name. @list: GList of files.
Definition at line 8276 of file caja-file.c.
caja_file_list_unref()
void caja_file_list_unref (GList * list)
caja_file_list_unref
Unref all the files in a list. @list: GList of files.
Definition at line 8149 of file caja-file.c.
References caja_file_unref(), and NULL.
Referenced by caja_directory_stop_monitoring_file_list(), caja_file_list_free(), caja_restore_files_from_trash(), caja_self_check_file(), and caja_trashed_files_get_original_directories().
caja_file_matches_uri()
gboolean caja_file_matches_uri (CajaFile * file, const char * uri)
Definition at line 2010 of file caja-file.c.
References caja_file_get_location(), CAJA_IS_FILE, FALSE, and NULL.
Referenced by caja_drag_can_accept_item().
caja_file_monitor_add()
void caja_file_monitor_add (CajaFile * file, gconstpointer client, CajaFileAttributes attributes)
Definition at line 4151 of file caja-file.c.
References CAJA_FILE_CLASS, CAJA_IS_FILE, EEL_CALL_METHOD, and NULL.
Referenced by caja_connect_background_to_file_metadata(), and caja_window_slot_set_viewed_file().
caja_file_monitor_remove()
void caja_file_monitor_remove (CajaFile * file, gconstpointer client)
Definition at line 4164 of file caja-file.c.
References CAJA_FILE_CLASS, CAJA_IS_FILE, EEL_CALL_METHOD, and NULL.
Referenced by caja_connect_background_to_file_metadata(), caja_window_slot_set_viewed_file(), and fm_tree_model_remove_root_uri().
caja_file_mount()
void caja_file_mount (CajaFile * file, GMountOperation * mount_op, GCancellable * cancellable, CajaFileOperationCallback callback, gpointer callback_data)
Definition at line 1210 of file caja-file.c.
References _, CAJA_FILE_GET_CLASS, error, and NULL.
caja_file_peek_top_left_text()
char * caja_file_peek_top_left_text (CajaFile * file, gboolean need_large_text, gboolean * got_top_left_text)
Definition at line 7591 of file caja-file.c.
References caja_file_contains_text(), caja_file_should_get_top_left_text(), CAJA_IS_FILE, CajaFile::details, FALSE, _CajaFilePrivate::got_large_top_left_text, _CajaFilePrivate::got_top_left_text, NULL, _CajaFilePrivate::top_left_text, and _CajaFilePrivate::top_left_text_is_up_to_date.
Referenced by caja_file_get_top_left_text().
caja_file_poll_for_media()
void caja_file_poll_for_media (CajaFile * file)
Definition at line 1430 of file caja-file.c.
References CAJA_FILE_GET_CLASS, _CajaFilePrivate::can_poll_for_media, CajaFile::details, _CajaFilePrivate::mount, and NULL.
caja_file_recompute_deep_counts()
void caja_file_recompute_deep_counts (CajaFile * file)
Definition at line 5245 of file caja-file.c.
References caja_directory_add_file_to_work_queue(), caja_directory_async_state_changed(), CAJA_REQUEST_IN_PROGRESS, CAJA_REQUEST_NOT_STARTED, _CajaFilePrivate::deep_counts_status, CajaFile::details, _CajaFilePrivate::directory, and NULL.
caja_file_ref()
CajaFile * caja_file_ref (CajaFile * file)
Definition at line 850 of file caja-file.c.
References CAJA_IS_FILE, DEBUG_REF_PRINTF, and NULL.
Referenced by caja_connect_background_to_file_metadata(), caja_desktop_icon_file_remove(), caja_directory_add_file(), caja_directory_get_existing_corresponding_file(), caja_directory_match_pattern(), caja_directory_moved(), caja_directory_notify_files_removed(), caja_file_eject(), caja_file_list_ref(), caja_file_operation_new(), caja_file_queue_enqueue(), caja_file_unmount(), caja_file_update_name_and_directory(), caja_mime_activate_files(), caja_sidebar_title_set_file(), caja_trashed_files_get_original_directories(), caja_window_slot_set_viewed_file(), fm_directory_view_pop_up_location_context_menu(), fm_list_model_add_file(), and fm_tree_model_iter_get_file().
caja_file_refresh_info()
void caja_file_refresh_info (CajaFile * file)
Definition at line 2586 of file caja-file.c.
References caja_file_changed(), CAJA_FILE_DEFAULT_ATTRIBUTES, caja_file_get_location(), caja_file_update_info(), and NULL.
caja_file_rename()
void caja_file_rename (CajaFile * file, const char * new_name, CajaFileOperationCallback callback, gpointer callback_data)
Definition at line 1801 of file caja-file.c.
References _, CAJA_DESKTOP_ICON_FILE, caja_desktop_icon_file_get_link(), caja_desktop_link_rename(), CAJA_FILE_ATTRIBUTE_INFO, CAJA_FILE_ATTRIBUTE_LINK_INFO, caja_file_changed(), caja_file_get_display_name(), caja_file_get_location(), caja_file_get_uri(), caja_file_invalidate_attributes(), caja_file_is_gone(), caja_file_is_self_owned(), caja_file_operation_new(), CAJA_IS_DESKTOP_ICON_FILE, CAJA_IS_FILE, caja_link_local_get_text(), caja_link_local_set_text(), caja_undostack_manager_data_new(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), CAJA_UNDOSTACK_RENAME, error, FALSE, NULL, op, and TRUE.
Referenced by caja_undostack_manager_redo(), caja_undostack_manager_undo(), and fm_rename_file().
caja_file_set_attributes()
void caja_file_set_attributes (CajaFile * file, GFileInfo * attributes, CajaFileOperationCallback callback, gpointer callback_data)
Definition at line 5363 of file caja-file.c.
References caja_file_get_location(), caja_file_operation_new(), and op.
Referenced by caja_file_set_group(), caja_file_set_owner(), and caja_file_set_permissions().
caja_file_set_boolean_metadata()
void caja_file_set_boolean_metadata (CajaFile * file, const char * key, gboolean default_metadata, gboolean metadata)
Definition at line 4022 of file caja-file.c.
References caja_file_set_metadata(), CAJA_IS_FILE, key, and NULL.
caja_file_set_group()
void caja_file_set_group (CajaFile * file, const char * group_name_or_id, CajaFileOperationCallback callback, gpointer callback_data)
Definition at line 6030 of file caja-file.c.
References _, caja_file_can_set_group(), caja_file_changed(), caja_file_get_group_name(), caja_file_get_uri(), caja_file_set_attributes(), CAJA_UNDOSTACK_CHANGEGROUP, caja_undostack_manager_add_action(), caja_undostack_manager_data_new(), caja_undostack_manager_data_set_group_change_information(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), CajaFile::details, error, _CajaFilePrivate::gid, and NULL.
Referenced by caja_undostack_manager_redo(), and caja_undostack_manager_undo().
caja_file_set_has_open_window()
void caja_file_set_has_open_window (CajaFile * file, gboolean has_open_window)
Definition at line 7998 of file caja-file.c.
References caja_file_changed(), CajaFile::details, FALSE, and _CajaFilePrivate::has_open_window.
Referenced by caja_window_show_window(), and caja_window_slot_set_viewed_file().
caja_file_set_integer_metadata()
void caja_file_set_integer_metadata (CajaFile * file, const char * key, int default_metadata, int metadata)
Definition at line 4037 of file caja-file.c.
References caja_file_set_metadata(), CAJA_IS_FILE, key, and NULL.
caja_file_set_keywords()
void caja_file_set_keywords (CajaFile * file, GList * keywords)
Definition at line 7084 of file caja-file.c.
References caja_file_set_metadata_list(), CAJA_IS_FILE, CAJA_METADATA_KEY_EMBLEMS, _CajaFilePrivate::compare_by_emblem_cache, CajaFile::details, and NULL.
Referenced by caja_drag_file_receive_dropped_keyword().
caja_file_set_metadata()
void caja_file_set_metadata (CajaFile * file, const char * key, const char * default_metadata, const char * metadata)
Definition at line 3847 of file caja-file.c.
References CAJA_FILE_CLASS, CAJA_IS_FILE, EEL_CALL_METHOD, key, and NULL.
Referenced by caja_directory_schedule_position_set(), caja_file_set_boolean_metadata(), caja_file_set_integer_metadata(), caja_file_set_time_metadata(), and caja_window_slot_set_content_view().
caja_file_set_metadata_list()
void caja_file_set_metadata_list (CajaFile * file, const char * key, GList * list)
Definition at line 3869 of file caja-file.c.
References CAJA_FILE_CLASS, CAJA_IS_FILE, EEL_CALL_METHOD, key, and NULL.
Referenced by caja_file_set_keywords().
caja_file_set_owner()
void caja_file_set_owner (CajaFile * file, const char * user_name_or_id, CajaFileOperationCallback callback, gpointer callback_data)
Definition at line 5751 of file caja-file.c.
References _, caja_file_can_set_owner(), caja_file_changed(), caja_file_get_uri(), caja_file_set_attributes(), CAJA_UNDOSTACK_CHANGEOWNER, caja_undostack_manager_add_action(), caja_undostack_manager_data_new(), caja_undostack_manager_data_set_owner_change_information(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), CajaFile::details, error, FALSE, NULL, and _CajaFilePrivate::uid.
Referenced by caja_undostack_manager_redo(), and caja_undostack_manager_undo().
caja_file_set_permissions()
void caja_file_set_permissions (CajaFile * file, guint32 permissions, CajaFileOperationCallback callback, gpointer callback_data)
Definition at line 5460 of file caja-file.c.
References _, caja_file_can_set_permissions(), caja_file_changed(), caja_file_get_uri(), caja_file_set_attributes(), caja_undostack_manager_add_action(), caja_undostack_manager_data_new(), caja_undostack_manager_data_set_file_permissions(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), CAJA_UNDOSTACK_SETPERMISSIONS, CajaFile::details, error, NULL, and _CajaFilePrivate::permissions.
Referenced by caja_undostack_manager_redo(), and caja_undostack_manager_undo().
caja_file_set_time_metadata()
void caja_file_set_time_metadata (CajaFile * file, const char * key, time_t time)
Definition at line 4002 of file caja-file.c.
References caja_file_set_metadata(), key, NULL, and UNDEFINED_TIME.
Referenced by caja_directory_schedule_position_set().
caja_file_should_show()
gboolean caja_file_should_show (CajaFile * file, gboolean show_hidden, gboolean show_foreign, gboolean show_backup)
Definition at line 3708 of file caja-file.c.
References caja_file_is_foreign_link(), caja_file_is_hidden_file(), caja_file_is_in_desktop(), caja_file_is_in_trash(), and TRUE.
Referenced by fm_directory_view_should_show_file().
caja_file_should_show_directory_item_count()
gboolean caja_file_should_show_directory_item_count (CajaFile * file)
Definition at line 5069 of file caja-file.c.
References CAJA_IS_FILE, caja_preferences, CAJA_PREFERENCES_SHOW_DIRECTORY_ITEM_COUNTS, CajaFile::details, FALSE, _CajaFilePrivate::mime_type, NULL, and TRUE.
Referenced by caja_file_get_deep_counts(), caja_file_get_directory_item_count(), and caja_file_get_string_attribute_with_default_q().
caja_file_should_show_thumbnail()
gboolean caja_file_should_show_thumbnail (CajaFile * file)
Definition at line 4362 of file caja-file.c.
References caja_file_get_filesystem_use_preview(), caja_file_get_size(), caja_file_is_local(), CAJA_SPEED_TRADEOFF_ALWAYS, CAJA_SPEED_TRADEOFF_NEVER, caja_thumbnail_is_mimetype_limited_by_size(), CajaFile::details, FALSE, _CajaFilePrivate::mime_type, mime_type, NULL, _CajaFilePrivate::thumbnail_path, and TRUE.
Referenced by caja_file_get_icon().
caja_file_should_show_type()
gboolean caja_file_should_show_type (CajaFile * file)
Definition at line 5096 of file caja-file.c.
References caja_file_get_uri(), CAJA_IS_FILE, and FALSE.
caja_file_start()
void caja_file_start (CajaFile * file, GMountOperation * start_op, GCancellable * cancellable, CajaFileOperationCallback callback, gpointer callback_data)
Definition at line 1319 of file caja-file.c.
References _, CAJA_FILE_GET_CLASS, _CajaFilePrivate::can_start, _CajaFilePrivate::can_start_degraded, CajaFile::details, error, and NULL.
caja_file_stop()
void caja_file_stop (CajaFile * file, GMountOperation * mount_op, GCancellable * cancellable, CajaFileOperationCallback callback, gpointer callback_data)
Definition at line 1371 of file caja-file.c.
References _, CAJA_FILE_GET_CLASS, caja_file_operation_new(), _CajaFilePrivate::can_stop, CajaFile::details, error, _CajaFilePrivate::mount, NULL, and op.
caja_file_unmount()
void caja_file_unmount (CajaFile * file, GMountOperation * mount_op, GCancellable * cancellable, CajaFileOperationCallback callback, gpointer callback_data)
Definition at line 1251 of file caja-file.c.
References _, CAJA_FILE_GET_CLASS, caja_file_operations_unmount_mount_full(), caja_file_ref(), _CajaFilePrivate::can_unmount, data, CajaFile::details, error, FALSE, _CajaFilePrivate::mount, NULL, and TRUE.
caja_file_unref()
void caja_file_unref (CajaFile * file)
Definition at line 865 of file caja-file.c.
References CAJA_IS_FILE, DEBUG_REF_PRINTF, and NULL.
Referenced by caja_compute_title_for_location(), caja_connect_background_to_file_metadata(), caja_desktop_icon_file_remove(), caja_directory_invalidate_count_and_mime_list(), caja_directory_notify_files_added(), caja_directory_notify_files_removed(), caja_directory_remove_file(), caja_directory_schedule_position_set(), caja_drag_default_drop_action_for_icons(), caja_file_list_unref(), caja_file_operation_free(), caja_file_queue_remove(), caja_file_update_name_and_directory(), caja_launch_application_by_uri(), caja_self_check_directory(), caja_self_check_file(), caja_trashed_files_get_original_directories(), caja_window_slot_set_content_view(), caja_window_slot_set_viewed_file(), fm_directory_view_move_copy_items(), fm_directory_view_pop_up_location_context_menu(), fm_tree_model_add_root_uri(), and fm_tree_model_remove_root_uri().
caja_get_all_group_names()
GList * caja_get_all_group_names (void)
caja_get_group_names:
Get a list of all group names.
Definition at line 5963 of file caja-file.c.
References eel_g_str_list_alphabetize(), and NULL.
Referenced by caja_file_get_settable_group_names().
caja_get_user_names()
GList * caja_get_user_names (void)
caja_get_user_names:
Get a list of user names. For users with a different associated "real name", the real name follows the standard user name, separated by a carriage return. The caller is responsible for freeing this list and its contents.
Definition at line 5827 of file caja-file.c.
References eel_g_str_list_alphabetize(), name, and NULL.