MATE Desktop Environment: caja-property-browser.h File Reference
caja-property-browser.h File Reference
#include <gdk/gdk.h>
#include <gtk/gtk.h>
Classes
struct CajaPropertyBrowser
struct CajaPropertyBrowserClass
Macros
#define CAJA_TYPE_PROPERTY_BROWSER caja_property_browser_get_type()
#define CAJA_PROPERTY_BROWSER(obj)
#define CAJA_PROPERTY_BROWSER_CLASS(klass)
#define CAJA_IS_PROPERTY_BROWSER(obj)
#define CAJA_IS_PROPERTY_BROWSER_CLASS(klass)
#define CAJA_PROPERTY_BROWSER_GET_CLASS(obj)
Typedefs
typedef struct CajaPropertyBrowser CajaPropertyBrowser
typedef struct CajaPropertyBrowserClass CajaPropertyBrowserClass
typedef struct _CajaPropertyBrowserPrivate CajaPropertyBrowserPrivate
Functions
GType caja_property_browser_get_type (void)
CajaPropertyBrowser * caja_property_browser_new (GdkScreen *screen)
void caja_property_browser_show (GdkScreen *screen)
void caja_property_browser_set_path (CajaPropertyBrowser *panel, const char *new_path)
Macro Definition Documentation
CAJA_IS_PROPERTY_BROWSER
#define CAJA_IS_PROPERTY_BROWSER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_PROPERTY_BROWSER))
Definition at line 45 of file caja-property-browser.h.
CAJA_IS_PROPERTY_BROWSER_CLASS
#define CAJA_IS_PROPERTY_BROWSER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_PROPERTY_BROWSER))
Definition at line 47 of file caja-property-browser.h.
CAJA_PROPERTY_BROWSER
#define CAJA_PROPERTY_BROWSER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_PROPERTY_BROWSER, CajaPropertyBrowser))
Definition at line 41 of file caja-property-browser.h.
Referenced by caja_property_browser_new().
CAJA_PROPERTY_BROWSER_CLASS
#define CAJA_PROPERTY_BROWSER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_PROPERTY_BROWSER, CajaPropertyBrowserClass))
Definition at line 43 of file caja-property-browser.h.
CAJA_PROPERTY_BROWSER_GET_CLASS
#define CAJA_PROPERTY_BROWSER_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_PROPERTY_BROWSER, CajaPropertyBrowserClass))
Definition at line 49 of file caja-property-browser.h.
CAJA_TYPE_PROPERTY_BROWSER
#define CAJA_TYPE_PROPERTY_BROWSER caja_property_browser_get_type()
Definition at line 40 of file caja-property-browser.h.
Typedef Documentation
CajaPropertyBrowser
typedef struct CajaPropertyBrowser CajaPropertyBrowser
Definition at line 37 of file caja-property-browser.h.
CajaPropertyBrowserClass
typedef struct CajaPropertyBrowserClass CajaPropertyBrowserClass
Definition at line 38 of file caja-property-browser.h.
CajaPropertyBrowserPrivate
typedef struct _CajaPropertyBrowserPrivate CajaPropertyBrowserPrivate
Definition at line 52 of file caja-property-browser.h.
Function Documentation
caja_property_browser_get_type()
GType caja_property_browser_get_type (void)
Referenced by caja_property_browser_new().
caja_property_browser_new()
CajaPropertyBrowser * caja_property_browser_new (GdkScreen * screen)
Definition at line 454 of file caja-property-browser.c.
References CAJA_PROPERTY_BROWSER, caja_property_browser_get_type(), and NULL.
Referenced by caja_property_browser_show().
caja_property_browser_set_path()
void caja_property_browser_set_path (CajaPropertyBrowser * panel, const char * new_path)
Definition at line 2485 of file caja-property-browser.c.
References CajaPropertyBrowser::details.
caja_property_browser_show()
void caja_property_browser_show (GdkScreen * screen)
Definition at line 470 of file caja-property-browser.c.
References caja_property_browser_new(), and NULL.