MATE Desktop Environment: caja-file-operations.c File Reference
caja-file-operations.c File Reference
#include <config.h>
#include <string.h>
#include <stdio.h>
#include <stdarg.h>
#include <locale.h>
#include <math.h>
#include <unistd.h>
#include <sys/types.h>
#include <stdlib.h>
#include <glib/gi18n.h>
#include <glib/gstdio.h>
#include <gdk/gdk.h>
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <glib.h>
#include <libnotify/notify.h>
#include <eel/eel-glib-extensions.h>
#include <eel/eel-gtk-extensions.h>
#include <eel/eel-stock-dialogs.h>
#include <eel/eel-vfs-extensions.h>
#include "caja-file-operations.h"
#include "caja-debug-log.h"
#include "caja-file-changes-queue.h"
#include "caja-lib-self-check-functions.h"
#include "caja-progress-info.h"
#include "caja-file-private.h"
#include "caja-desktop-icon-file.h"
#include "caja-desktop-link-monitor.h"
#include "caja-global-preferences.h"
#include "caja-link.h"
#include "caja-autorun.h"
#include "caja-trash-monitor.h"
#include "caja-file-utilities.h"
#include "caja-file-conflict-dialog.h"
#include "caja-undostack-manager.h"
#include "caja-metadata.h"
Macros
#define SECONDS_NEEDED_FOR_RELIABLE_TRANSFER_RATE 15
#define NSEC_PER_MICROSEC 1000
#define MAXIMUM_DISPLAYED_FILE_NAME_LENGTH 50
#define IS_IO_ERROR(__error, KIND)
#define CANCEL _("_Cancel")
#define SKIP _("_Skip")
#define SKIP_ALL _("S_kip All")
#define RETRY _("_Retry")
#define DELETE _("_Delete")
#define DELETE_ALL _("Delete _All")
#define REPLACE_ALL _("Replace _All")
#define MERGE_ALL _("Merge _All")
#define CONTINUE_FORCE _("Continue _Anyway")
#define COPY_DUPLICATE_TAG _(untranslated_copy_duplicate_tag)
#define ANOTHER_COPY_DUPLICATE_TAG _(untranslated_another_copy_duplicate_tag)
#define X11TH_COPY_DUPLICATE_TAG _(untranslated_x11th_copy_duplicate_tag)
#define X12TH_COPY_DUPLICATE_TAG _(untranslated_x12th_copy_duplicate_tag)
#define X13TH_COPY_DUPLICATE_TAG _(untranslated_x13th_copy_duplicate_tag)
#define ST_COPY_DUPLICATE_TAG _(untranslated_st_copy_duplicate_tag)
#define ND_COPY_DUPLICATE_TAG _(untranslated_nd_copy_duplicate_tag)
#define RD_COPY_DUPLICATE_TAG _(untranslated_rd_copy_duplicate_tag)
#define TH_COPY_DUPLICATE_TAG _(untranslated_th_copy_duplicate_tag)
#define FIRST_COPY_DUPLICATE_FORMAT _(untranslated_first_copy_duplicate_format)
#define SECOND_COPY_DUPLICATE_FORMAT _(untranslated_second_copy_duplicate_format)
#define X11TH_COPY_DUPLICATE_FORMAT _(untranslated_x11th_copy_duplicate_format)
#define X12TH_COPY_DUPLICATE_FORMAT _(untranslated_x12th_copy_duplicate_format)
#define X13TH_COPY_DUPLICATE_FORMAT _(untranslated_x13th_copy_duplicate_format)
#define ST_COPY_DUPLICATE_FORMAT _(untranslated_st_copy_duplicate_format)
#define ND_COPY_DUPLICATE_FORMAT _(untranslated_nd_copy_duplicate_format)
#define RD_COPY_DUPLICATE_FORMAT _(untranslated_rd_copy_duplicate_format)
#define TH_COPY_DUPLICATE_FORMAT _(untranslated_th_copy_duplicate_format)
#define op_job_new(__type, parent_window, should_start, can_pause)
#define FAT_FORBIDDEN_CHARACTERS "/:;*?\"<>"
#define TRUSTED_SHEBANG "#!/usr/bin/env xdg-open\n"
Enumerations
enum OpKind {
OP_KIND_CREATE , OP_KIND_LINK , OP_KIND_COPY , OP_KIND_MOVE ,
OP_KIND_DELETE , OP_KIND_TRASH
}
enum CreateDestDirResult { CREATE_DEST_DIR_RETRY , CREATE_DEST_DIR_FAILED , CREATE_DEST_DIR_SUCCESS }
Functions
void caja_application_notify_unmount_show (const gchar *message)
void caja_file_operations_trash_or_delete (GList *files, GtkWindow *parent_window, CajaDeleteCallback done_callback, gpointer done_callback_data)
void caja_file_operations_delete (GList *files, GtkWindow *parent_window, CajaDeleteCallback done_callback, gpointer done_callback_data)
void caja_file_operations_unmount_mount_full (GtkWindow *parent_window, GMount *mount, gboolean eject, gboolean check_trash, CajaUnmountCallback callback, gpointer callback_data)
void caja_file_operations_unmount_mount (GtkWindow *parent_window, GMount *mount, gboolean eject, gboolean check_trash)
void caja_file_operations_mount_volume (GtkWindow *parent_window, GVolume *volume, gboolean allow_autorun)
void caja_file_operations_mount_volume_full (GtkWindow *parent_window, GVolume *volume, gboolean allow_autorun, CajaMountCallback mount_callback, GObject *mount_callback_data_object)
void caja_file_operations_copy (GList *files, GArray *relative_item_points, GFile *target_dir, GtkWindow *parent_window, CajaCopyCallback done_callback, gpointer done_callback_data)
void caja_file_operations_move (GList *files, GArray *relative_item_points, GFile *target_dir, GtkWindow *parent_window, CajaCopyCallback done_callback, gpointer done_callback_data)
void caja_file_operations_link (GList *files, GArray *relative_item_points, GFile *target_dir, GtkWindow *parent_window, CajaCopyCallback done_callback, gpointer done_callback_data)
void caja_file_operations_duplicate (GList *files, GArray *relative_item_points, GtkWindow *parent_window, CajaCopyCallback done_callback, gpointer done_callback_data)
void caja_file_set_permissions_recursive (const char *directory, guint32 file_permissions, guint32 file_mask, guint32 dir_permissions, guint32 dir_mask, CajaOpCallback callback, gpointer callback_data)
void caja_file_operations_copy_move (const GList *item_uris, GArray *relative_item_points, const char *target_dir, GdkDragAction copy_action, GtkWidget *parent_view, CajaCopyCallback done_callback, gpointer done_callback_data)
void caja_file_operations_new_folder (GtkWidget *parent_view, GdkPoint *target_point, const char *parent_dir, CajaCreateCallback done_callback, gpointer done_callback_data)
void caja_file_operations_new_file_from_template (GtkWidget *parent_view, GdkPoint *target_point, const char *parent_dir, const char *target_filename, const char *template_uri, CajaCreateCallback done_callback, gpointer done_callback_data)
void caja_file_operations_new_file (GtkWidget *parent_view, GdkPoint *target_point, const char *parent_dir, const char *target_filename, const char *initial_contents, int length, CajaCreateCallback done_callback, gpointer done_callback_data)
void caja_file_operations_empty_trash (GtkWidget *parent_view)
void caja_file_mark_desktop_file_trusted (GFile *file, GtkWindow *parent_window, gboolean interactive, CajaOpCallback done_callback, gpointer done_callback_data)
void caja_self_check_file_operations (void)
Variables
NotifyNotification * unmount_notify
Macro Definition Documentation
ANOTHER_COPY_DUPLICATE_TAG
#define ANOTHER_COPY_DUPLICATE_TAG _(untranslated_another_copy_duplicate_tag)
Definition at line 497 of file caja-file-operations.c.
CANCEL
#define CANCEL _("_Cancel")
Definition at line 185 of file caja-file-operations.c.
CONTINUE_FORCE
#define CONTINUE_FORCE _("Continue _Anyway")
Definition at line 193 of file caja-file-operations.c.
COPY_DUPLICATE_TAG
#define COPY_DUPLICATE_TAG _(untranslated_copy_duplicate_tag)
Definition at line 496 of file caja-file-operations.c.
DELETE
#define DELETE _("_Delete")
Definition at line 189 of file caja-file-operations.c.
DELETE_ALL
#define DELETE_ALL _("Delete _All")
Definition at line 190 of file caja-file-operations.c.
FAT_FORBIDDEN_CHARACTERS
#define FAT_FORBIDDEN_CHARACTERS "/:;*?\"<>"
Definition at line 3184 of file caja-file-operations.c.
FIRST_COPY_DUPLICATE_FORMAT
#define FIRST_COPY_DUPLICATE_FORMAT _(untranslated_first_copy_duplicate_format)
Definition at line 533 of file caja-file-operations.c.
IS_IO_ERROR
#define IS_IO_ERROR (__error, KIND)
Value:
(((__error)->domain == G_IO_ERROR && (__error)->code == G_IO_ERROR_ ## KIND))
Definition at line 183 of file caja-file-operations.c.
MAXIMUM_DISPLAYED_FILE_NAME_LENGTH
#define MAXIMUM_DISPLAYED_FILE_NAME_LENGTH 50
Definition at line 181 of file caja-file-operations.c.
Referenced by fm_report_error_renaming_file().
MERGE_ALL
#define MERGE_ALL _("Merge _All")
Definition at line 192 of file caja-file-operations.c.
ND_COPY_DUPLICATE_FORMAT
#define ND_COPY_DUPLICATE_FORMAT _(untranslated_nd_copy_duplicate_format)
Definition at line 540 of file caja-file-operations.c.
ND_COPY_DUPLICATE_TAG
#define ND_COPY_DUPLICATE_TAG _(untranslated_nd_copy_duplicate_tag)
Definition at line 503 of file caja-file-operations.c.
NSEC_PER_MICROSEC
#define NSEC_PER_MICROSEC 1000
Definition at line 179 of file caja-file-operations.c.
op_job_new
#define op_job_new (__type, parent_window, should_start, can_pause)
Value:
((__type *)(init_common (sizeof(__type), parent_window, should_start, can_pause)))
Definition at line 935 of file caja-file-operations.c.
Referenced by caja_file_mark_desktop_file_trusted(), caja_file_operations_copy(), caja_file_operations_duplicate(), caja_file_operations_empty_trash(), caja_file_operations_link(), caja_file_operations_move(), caja_file_operations_new_file(), caja_file_operations_new_file_from_template(), caja_file_operations_new_folder(), caja_file_operations_unmount_mount_full(), and caja_file_set_permissions_recursive().
RD_COPY_DUPLICATE_FORMAT
#define RD_COPY_DUPLICATE_FORMAT _(untranslated_rd_copy_duplicate_format)
Definition at line 541 of file caja-file-operations.c.
RD_COPY_DUPLICATE_TAG
#define RD_COPY_DUPLICATE_TAG _(untranslated_rd_copy_duplicate_tag)
Definition at line 504 of file caja-file-operations.c.
REPLACE_ALL
#define REPLACE_ALL _("Replace _All")
Definition at line 191 of file caja-file-operations.c.
RETRY
#define RETRY _("_Retry")
Definition at line 188 of file caja-file-operations.c.
SECOND_COPY_DUPLICATE_FORMAT
#define SECOND_COPY_DUPLICATE_FORMAT _(untranslated_second_copy_duplicate_format)
Definition at line 534 of file caja-file-operations.c.
SECONDS_NEEDED_FOR_RELIABLE_TRANSFER_RATE
#define SECONDS_NEEDED_FOR_RELIABLE_TRANSFER_RATE 15
Definition at line 178 of file caja-file-operations.c.
SKIP
#define SKIP _("_Skip")
Definition at line 186 of file caja-file-operations.c.
SKIP_ALL
#define SKIP_ALL _("S_kip All")
Definition at line 187 of file caja-file-operations.c.
ST_COPY_DUPLICATE_FORMAT
#define ST_COPY_DUPLICATE_FORMAT _(untranslated_st_copy_duplicate_format)
Definition at line 539 of file caja-file-operations.c.
ST_COPY_DUPLICATE_TAG
#define ST_COPY_DUPLICATE_TAG _(untranslated_st_copy_duplicate_tag)
Definition at line 502 of file caja-file-operations.c.
TH_COPY_DUPLICATE_FORMAT
#define TH_COPY_DUPLICATE_FORMAT _(untranslated_th_copy_duplicate_format)
Definition at line 542 of file caja-file-operations.c.
TH_COPY_DUPLICATE_TAG
#define TH_COPY_DUPLICATE_TAG _(untranslated_th_copy_duplicate_tag)
Definition at line 505 of file caja-file-operations.c.
TRUSTED_SHEBANG
#define TRUSTED_SHEBANG "#!/usr/bin/env xdg-open\n"
Definition at line 6554 of file caja-file-operations.c.
X11TH_COPY_DUPLICATE_FORMAT
#define X11TH_COPY_DUPLICATE_FORMAT _(untranslated_x11th_copy_duplicate_format)
Definition at line 535 of file caja-file-operations.c.
X11TH_COPY_DUPLICATE_TAG
#define X11TH_COPY_DUPLICATE_TAG _(untranslated_x11th_copy_duplicate_tag)
Definition at line 498 of file caja-file-operations.c.
X12TH_COPY_DUPLICATE_FORMAT
#define X12TH_COPY_DUPLICATE_FORMAT _(untranslated_x12th_copy_duplicate_format)
Definition at line 536 of file caja-file-operations.c.
X12TH_COPY_DUPLICATE_TAG
#define X12TH_COPY_DUPLICATE_TAG _(untranslated_x12th_copy_duplicate_tag)
Definition at line 499 of file caja-file-operations.c.
X13TH_COPY_DUPLICATE_FORMAT
#define X13TH_COPY_DUPLICATE_FORMAT _(untranslated_x13th_copy_duplicate_format)
Definition at line 537 of file caja-file-operations.c.
X13TH_COPY_DUPLICATE_TAG
#define X13TH_COPY_DUPLICATE_TAG _(untranslated_x13th_copy_duplicate_tag)
Definition at line 500 of file caja-file-operations.c.
Enumeration Type Documentation
CreateDestDirResult
enum CreateDestDirResult
Enumerator
CREATE_DEST_DIR_RETRY
CREATE_DEST_DIR_FAILED
CREATE_DEST_DIR_SUCCESS
Definition at line 3465 of file caja-file-operations.c.
OpKind
enum OpKind
Enumerator
OP_KIND_CREATE
OP_KIND_LINK
OP_KIND_COPY
OP_KIND_MOVE
OP_KIND_DELETE
OP_KIND_TRASH
Definition at line 154 of file caja-file-operations.c.
Function Documentation
caja_application_notify_unmount_show()
void caja_application_notify_unmount_show (const gchar * message)
Definition at line 198 of file caja-file-operations.c.
References caja_preferences, CAJA_PREFERENCES_SHOW_NOTIFICATIONS, message(), NULL, TRUE, and unmount_notify.
caja_file_mark_desktop_file_trusted()
void caja_file_mark_desktop_file_trusted (GFile * file, GtkWindow * parent_window, gboolean interactive, CajaOpCallback done_callback, gpointer done_callback_data)
Definition at line 6747 of file caja-file-operations.c.
References FALSE, NULL, op_job_new, and TRUE.
caja_file_operations_copy()
void caja_file_operations_copy (GList * files, GArray * relative_item_points, GFile * target_dir, GtkWindow * parent_window, CajaCopyCallback done_callback, gpointer done_callback_data)
Definition at line 4752 of file caja-file-operations.c.
References _, caja_get_desktop_location(), CAJA_UNDOSTACK_COPY, caja_undostack_manager_data_new(), caja_undostack_manager_data_set_dest_dir(), caja_undostack_manager_data_set_src_dir(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), FALSE, NULL, and op_job_new.
Referenced by caja_file_operations_copy_move(), caja_undostack_manager_redo(), and main().
caja_file_operations_copy_move()
void caja_file_operations_copy_move (const GList * item_uris, GArray * relative_item_points, const char * target_dir, GdkDragAction copy_action, GtkWidget * parent_view, CajaCopyCallback done_callback, gpointer done_callback_data)
Definition at line 5889 of file caja-file-operations.c.
References caja_file_operations_copy(), caja_file_operations_duplicate(), caja_file_operations_link(), caja_file_operations_move(), caja_file_operations_trash_or_delete(), dest, FALSE, NULL, and TRUE.
Referenced by fm_directory_view_move_copy_items().
caja_file_operations_delete()
void caja_file_operations_delete (GList * files, GtkWindow * parent_window, CajaDeleteCallback done_callback, gpointer done_callback_data)
Definition at line 2120 of file caja-file-operations.c.
References FALSE.
Referenced by caja_undostack_manager_undo().
caja_file_operations_duplicate()
void caja_file_operations_duplicate (GList * files, GArray * relative_item_points, GtkWindow * parent_window, CajaCopyCallback done_callback, gpointer done_callback_data)
Definition at line 5655 of file caja-file-operations.c.
References CAJA_UNDOSTACK_DUPLICATE, caja_undostack_manager_data_new(), caja_undostack_manager_data_set_dest_dir(), caja_undostack_manager_data_set_src_dir(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), FALSE, NULL, and op_job_new.
Referenced by caja_file_operations_copy_move(), and caja_undostack_manager_redo().
caja_file_operations_empty_trash()
void caja_file_operations_empty_trash (GtkWidget * parent_view)
Definition at line 6515 of file caja-file-operations.c.
References _, FALSE, NULL, op_job_new, and TRUE.
caja_file_operations_link()
void caja_file_operations_link (GList * files, GArray * relative_item_points, GFile * target_dir, GtkWindow * parent_window, CajaCopyCallback done_callback, gpointer done_callback_data)
Definition at line 5614 of file caja-file-operations.c.
References CAJA_UNDOSTACK_CREATELINK, caja_undostack_manager_data_new(), caja_undostack_manager_data_set_dest_dir(), caja_undostack_manager_data_set_src_dir(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), FALSE, NULL, op_job_new, and TRUE.
Referenced by caja_file_operations_copy_move(), and caja_undostack_manager_redo().
caja_file_operations_mount_volume()
void caja_file_operations_mount_volume (GtkWindow * parent_window, GVolume * volume, gboolean allow_autorun)
Definition at line 2485 of file caja-file-operations.c.
References caja_file_operations_mount_volume_full(), and NULL.
caja_file_operations_mount_volume_full()
void caja_file_operations_mount_volume_full (GtkWindow * parent_window, GVolume * volume, gboolean allow_autorun, CajaMountCallback mount_callback, GObject * mount_callback_data_object)
Definition at line 2494 of file caja-file-operations.c.
References caja_allow_autorun_for_volume(), and NULL.
Referenced by caja_file_operations_mount_volume().
caja_file_operations_move()
void caja_file_operations_move (GList * files, GArray * relative_item_points, GFile * target_dir, GtkWindow * parent_window, CajaCopyCallback done_callback, gpointer done_callback_data)
Definition at line 5295 of file caja-file-operations.c.
References _, caja_undostack_manager_data_new(), caja_undostack_manager_data_set_dest_dir(), caja_undostack_manager_data_set_src_dir(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), CAJA_UNDOSTACK_MOVE, CAJA_UNDOSTACK_RESTOREFROMTRASH, data, FALSE, NULL, op_job_new, and TRUE.
Referenced by caja_file_operations_copy_move(), caja_restore_files_from_trash(), caja_undostack_manager_redo(), and caja_undostack_manager_undo().
caja_file_operations_new_file()
void caja_file_operations_new_file (GtkWidget * parent_view, GdkPoint * target_point, const char * parent_dir, const char * target_filename, const char * initial_contents, int length, CajaCreateCallback done_callback, gpointer done_callback_data)
Definition at line 6373 of file caja-file-operations.c.
References CAJA_UNDOSTACK_CREATEEMPTYFILE, caja_undostack_manager_data_new(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), FALSE, NULL, op_job_new, target_filename, and TRUE.
Referenced by caja_undostack_manager_redo().
caja_file_operations_new_file_from_template()
void caja_file_operations_new_file_from_template (GtkWidget * parent_view, GdkPoint * target_point, const char * parent_dir, const char * target_filename, const char * template_uri, CajaCreateCallback done_callback, gpointer done_callback_data)
Definition at line 6329 of file caja-file-operations.c.
References CAJA_UNDOSTACK_CREATEFILEFROMTEMPLATE, caja_undostack_manager_data_new(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), FALSE, NULL, op_job_new, target_filename, and TRUE.
Referenced by caja_undostack_manager_redo(), and fm_directory_view_new_file().
caja_file_operations_new_folder()
void caja_file_operations_new_folder (GtkWidget * parent_view, GdkPoint * target_point, const char * parent_dir, CajaCreateCallback done_callback, gpointer done_callback_data)
Definition at line 6291 of file caja-file-operations.c.
References CAJA_UNDOSTACK_CREATEFOLDER, caja_undostack_manager_data_new(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), FALSE, NULL, op_job_new, and TRUE.
Referenced by caja_undostack_manager_redo(), and fm_directory_view_new_folder().
caja_file_operations_trash_or_delete()
void caja_file_operations_trash_or_delete (GList * files, GtkWindow * parent_window, CajaDeleteCallback done_callback, gpointer done_callback_data)
Definition at line 2109 of file caja-file-operations.c.
References TRUE.
Referenced by caja_file_operations_copy_move(), caja_undostack_manager_redo(), and caja_undostack_manager_undo().
caja_file_operations_unmount_mount()
void caja_file_operations_unmount_mount (GtkWindow * parent_window, GMount * mount, gboolean eject, gboolean check_trash)
Definition at line 2417 of file caja-file-operations.c.
References caja_file_operations_unmount_mount_full(), and NULL.
caja_file_operations_unmount_mount_full()
void caja_file_operations_unmount_mount_full (GtkWindow * parent_window, GMount * mount, gboolean eject, gboolean check_trash, CajaUnmountCallback callback, gpointer callback_data)
Definition at line 2363 of file caja-file-operations.c.
References data, eel_add_weak_pointer(), eel_remove_weak_pointer(), FALSE, NULL, op_job_new, and TRUE.
Referenced by caja_file_eject(), caja_file_operations_unmount_mount(), and caja_file_unmount().
caja_file_set_permissions_recursive()
void caja_file_set_permissions_recursive (const char * directory, guint32 file_permissions, guint32 file_mask, guint32 dir_permissions, guint32 dir_mask, CajaOpCallback callback, gpointer callback_data)
Definition at line 5822 of file caja-file-operations.c.
References caja_undostack_manager_data_new(), caja_undostack_manager_data_set_dest_dir(), caja_undostack_manager_data_set_recursive_permissions(), caja_undostack_manager_instance(), caja_undostack_manager_is_undo_redo(), CAJA_UNDOSTACK_RECURSIVESETPERMISSIONS, FALSE, NULL, op_job_new, and TRUE.
Referenced by caja_undostack_manager_redo().
caja_self_check_file_operations()
void caja_self_check_file_operations (void)
Definition at line 6771 of file caja-file-operations.c.
References EEL_CHECK_STRING_RESULT.
Variable Documentation
unmount_notify
NotifyNotification* unmount_notify
Definition at line 195 of file caja-file-operations.c.
Referenced by caja_application_notify_unmount_show().