MATE Desktop Environment: caja-search-bar.c File Reference
caja-search-bar.c File Reference
#include <config.h>
#include <glib/gi18n.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <eel/eel-gtk-macros.h>
#include <libcaja-private/caja-clipboard.h>
#include "caja-search-bar.h"
Enumerations
enum { ACTIVATE , CANCEL , FOCUS_IN , LAST_SIGNAL }
Functions
EEL_CLASS_BOILERPLATE (CajaSearchBar, caja_search_bar, GTK_TYPE_EVENT_BOX)
GtkWidget * caja_search_bar_borrow_entry (CajaSearchBar *bar)
void caja_search_bar_return_entry (CajaSearchBar *bar)
GtkWidget * caja_search_bar_new (CajaWindow *window)
CajaQuery * caja_search_bar_get_query (CajaSearchBar *bar)
void caja_search_bar_grab_focus (CajaSearchBar *bar)
void caja_search_bar_clear (CajaSearchBar *bar)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ACTIVATE
CANCEL
FOCUS_IN
LAST_SIGNAL
Definition at line 42 of file caja-search-bar.c.
Function Documentation
caja_search_bar_borrow_entry()
GtkWidget * caja_search_bar_borrow_entry (CajaSearchBar * bar)
Definition at line 195 of file caja-search-bar.c.
References CajaSearchBar::details, and TRUE.
Referenced by caja_query_editor_new_with_bar().
caja_search_bar_clear()
void caja_search_bar_clear (CajaSearchBar * bar)
Definition at line 262 of file caja-search-bar.c.
References CajaSearchBar::details.
Referenced by caja_navigation_window_show_search().
caja_search_bar_get_query()
CajaQuery * caja_search_bar_get_query (CajaSearchBar * bar)
Definition at line 236 of file caja-search-bar.c.
References caja_query_new(), caja_query_set_text(), CajaSearchBar::details, and NULL.
caja_search_bar_grab_focus()
void caja_search_bar_grab_focus (CajaSearchBar * bar)
Definition at line 256 of file caja-search-bar.c.
References CajaSearchBar::details.
Referenced by caja_navigation_window_show_search().
caja_search_bar_new()
GtkWidget * caja_search_bar_new (CajaWindow * window)
Definition at line 218 of file caja-search-bar.c.
References caja_clipboard_set_up_editable(), CAJA_SEARCH_BAR, CAJA_TYPE_SEARCH_BAR, caja_window_get_ui_manager(), CajaSearchBar::details, FALSE, and NULL.
Referenced by caja_navigation_window_pane_setup().
caja_search_bar_return_entry()
void caja_search_bar_return_entry (CajaSearchBar * bar)
Definition at line 207 of file caja-search-bar.c.
References CajaSearchBar::details, and FALSE.
EEL_CLASS_BOILERPLATE()
EEL_CLASS_BOILERPLATE (CajaSearchBar , caja_search_bar , GTK_TYPE_EVENT_BOX)
Definition at line 55 of file caja-search-bar.c.
References CAJA_SEARCH_BAR, CajaSearchBar::details, EEL_CALL_PARENT, and G_OBJECT_CLASS().