MATE Desktop Environment: caja-window-manage-views.c File Reference
caja-window-manage-views.c File Reference
#include <config.h>
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
#include <glib/gi18n.h>
#include <eel/eel-accessibility.h>
#include <eel/eel-debug.h>
#include <eel/eel-gdk-extensions.h>
#include <eel/eel-glib-extensions.h>
#include <eel/eel-gtk-extensions.h>
#include <eel/eel-gtk-macros.h>
#include <eel/eel-stock-dialogs.h>
#include <eel/eel-string.h>
#include <eel/eel-vfs-extensions.h>
#include <libcaja-private/caja-debug-log.h>
#include <libcaja-private/caja-extensions.h>
#include <libcaja-private/caja-file-attributes.h>
#include <libcaja-private/caja-file-utilities.h>
#include <libcaja-private/caja-file.h>
#include <libcaja-private/caja-global-preferences.h>
#include <libcaja-private/caja-metadata.h>
#include <libcaja-private/caja-mime-actions.h>
#include <libcaja-private/caja-module.h>
#include <libcaja-private/caja-monitor.h>
#include <libcaja-private/caja-search-directory.h>
#include <libcaja-private/caja-view-factory.h>
#include <libcaja-private/caja-window-info.h>
#include <libcaja-private/caja-window-slot-info.h>
#include <libcaja-private/caja-autorun.h>
#include <libcaja-extension/caja-location-widget-provider.h>
#include "caja-window-manage-views.h"
#include "caja-actions.h"
#include "caja-application.h"
#include "caja-location-bar.h"
#include "caja-search-bar.h"
#include "caja-pathbar.h"
#include "caja-window-private.h"
#include "caja-window-slot.h"
#include "caja-navigation-window-slot.h"
#include "caja-trash-bar.h"
#include "caja-x-content-bar.h"
#include "caja-navigation-window-pane.h"
#include "caja-desktop-window.h"
Macros
#define MAX_URI_IN_DIALOG_LENGTH 60
Functions
void caja_window_report_selection_changed (CajaWindowInfo *window)
void caja_window_update_up_button (CajaWindow *window)
void caja_window_slot_open_location_full (CajaWindowSlot *slot, GFile *location, CajaWindowOpenMode mode, CajaWindowOpenFlags flags, GList *new_selection, CajaWindowGoToCallback callback, gpointer user_data)
void caja_window_slot_open_location (CajaWindowSlot *slot, GFile *location, gboolean close_behind)
void caja_window_slot_open_location_with_selection (CajaWindowSlot *slot, GFile *location, GList *selection, gboolean close_behind)
void caja_window_slot_go_home (CajaWindowSlot *slot, gboolean new_tab)
const char * caja_window_slot_get_content_view_id (CajaWindowSlot *slot)
gboolean caja_window_slot_content_view_matches_iid (CajaWindowSlot *slot, const char *iid)
void caja_window_report_load_underway (CajaWindow *window, CajaView *view)
void caja_window_report_location_change (CajaWindow *window)
void caja_window_report_load_complete (CajaWindow *window, CajaView *view)
void caja_window_report_view_failed (CajaWindow *window, CajaView *view)
void caja_window_slot_stop_loading (CajaWindowSlot *slot)
void caja_window_slot_set_content_view (CajaWindowSlot *slot, const char *id)
void caja_window_manage_views_close_slot (CajaWindowPane *pane, CajaWindowSlot *slot)
void caja_navigation_window_back_or_forward (CajaNavigationWindow *window, gboolean back, guint distance, gboolean new_tab)
void caja_window_slot_reload (CajaWindowSlot *slot)
Macro Definition Documentation
MAX_URI_IN_DIALOG_LENGTH
#define MAX_URI_IN_DIALOG_LENGTH 60
Definition at line 86 of file caja-window-manage-views.c.
Function Documentation
caja_navigation_window_back_or_forward()
void caja_navigation_window_back_or_forward (CajaNavigationWindow * window, gboolean back, guint distance, gboolean new_tab)
Definition at line 2306 of file caja-window-manage-views.c.
References CajaNavigationWindowSlot::back_list, caja_bookmark_get_location(), caja_bookmark_get_scroll_pos(), CAJA_LOCATION_CHANGE_BACK, CAJA_LOCATION_CHANGE_FORWARD, CAJA_WINDOW, CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, CAJA_WINDOW_OPEN_FLAG_NEW_TAB, caja_window_slot_get_location(), caja_window_slot_open_location_full(), CajaNavigationWindowSlot::forward_list, and NULL.
Referenced by caja_navigation_window_go_back(), and caja_navigation_window_go_forward().
caja_window_manage_views_close_slot()
void caja_window_manage_views_close_slot (CajaWindowPane * pane, CajaWindowSlot * slot)
Definition at line 2293 of file caja-window-manage-views.c.
References caja_window_slot_disconnect_content_view(), CajaWindowSlot::content_view, and NULL.
caja_window_report_load_complete()
void caja_window_report_load_complete (CajaWindow * window, CajaView * view)
Definition at line 1922 of file caja-window-manage-views.c.
References CAJA_IS_WINDOW, caja_view_scroll_to_file(), caja_window_get_slot_for_view(), CajaWindowSlot::content_view, NULL, and CajaWindowSlot::pending_scroll_to.
caja_window_report_load_underway()
void caja_window_report_load_underway (CajaWindow * window, CajaView * view)
Definition at line 1543 of file caja-window-manage-views.c.
References CAJA_IS_WINDOW, caja_window_get_slot_for_view(), caja_window_slot_set_allow_stop(), CajaWindowSlot::new_content_view, NULL, and TRUE.
caja_window_report_location_change()
void caja_window_report_location_change (CajaWindow * window)
Definition at line 1584 of file caja-window-manage-views.c.
References CAJA_IS_WINDOW, CAJA_IS_WINDOW_SLOT, CajaWindowSlot::location, NULL, and CajaWindowSlot::pending_location.
Referenced by caja_window_set_active_slot().
caja_window_report_selection_changed()
void caja_window_report_selection_changed (CajaWindowInfo * window)
Definition at line 117 of file caja-window-manage-views.c.
caja_window_report_view_failed()
void caja_window_report_view_failed (CajaWindow * window, CajaView * view)
Definition at line 2051 of file caja-window-manage-views.c.
References CAJA_LOCATION_CHANGE_FALLBACK, caja_window_get_slot_for_view(), caja_window_slot_disconnect_content_view(), caja_window_slot_set_content_view_widget(), CajaWindowSlot::content_view, FALSE, CajaWindowSlot::location_change_type, NULL, CajaWindowSlot::pending_location, and TRUE.
caja_window_slot_content_view_matches_iid()
gboolean caja_window_slot_content_view_matches_iid (CajaWindowSlot * slot, const char * iid)
Definition at line 845 of file caja-window-manage-views.c.
References caja_view_get_view_id(), CajaWindowSlot::content_view, FALSE, and NULL.
Referenced by caja_window_slot_set_content_view().
caja_window_slot_get_content_view_id()
const char * caja_window_slot_get_content_view_id (CajaWindowSlot * slot)
Definition at line 835 of file caja-window-manage-views.c.
References caja_view_get_view_id(), CajaWindowSlot::content_view, and NULL.
caja_window_slot_go_home()
void caja_window_slot_go_home (CajaWindowSlot * slot, gboolean new_tab)
Definition at line 757 of file caja-window-manage-views.c.
References CAJA_IS_WINDOW_SLOT, CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, CAJA_WINDOW_OPEN_FLAG_NEW_TAB, caja_window_slot_open_location_full(), and NULL.
Referenced by caja_window_go_home().
caja_window_slot_open_location()
void caja_window_slot_open_location (CajaWindowSlot * slot, GFile * location, gboolean close_behind)
Definition at line 721 of file caja-window-manage-views.c.
References CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, CAJA_WINDOW_OPEN_FLAG_CLOSE_BEHIND, caja_window_slot_open_location_full(), and NULL.
caja_window_slot_open_location_full()
void caja_window_slot_open_location_full (CajaWindowSlot * slot, GFile * location, CajaWindowOpenMode mode, CajaWindowOpenFlags flags, GList * new_selection, CajaWindowGoToCallback callback, gpointer user_data)
Definition at line 514 of file caja-window-manage-views.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, caja_application_create_navigation_window(), caja_application_get_spatial_window(), caja_debug_log(), CAJA_DEBUG_LOG_DOMAIN_USER, CAJA_DESKTOP_WINDOW, caja_desktop_window_loaded(), CAJA_IS_DESKTOP_WINDOW, CAJA_IS_NAVIGATION_WINDOW, CAJA_IS_SPATIAL_WINDOW, CAJA_LOCATION_CHANGE_RELOAD, CAJA_LOCATION_CHANGE_STANDARD, CAJA_NEW_TAB_POSITION_END, caja_preferences, CAJA_PREFERENCES_ALWAYS_USE_BROWSER, CAJA_PREFERENCES_NEW_TAB_POSITION, caja_view_set_selection(), caja_window_close(), CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, CAJA_WINDOW_OPEN_FLAG_CLOSE_BEHIND, CAJA_WINDOW_OPEN_FLAG_NEW_TAB, CAJA_WINDOW_OPEN_FLAG_NEW_WINDOW, CAJA_WINDOW_OPEN_IN_NAVIGATION, caja_window_open_slot(), CAJA_WINDOW_OPEN_SLOT_APPEND, caja_window_slot_get_location(), caja_window_slot_get_location_uri(), CajaWindowSlot::content_view, CajaWindow::details, EEL_DESKTOP_URI, FALSE, CajaWindowSlot::location, NULL, CajaWindowSlot::pane, _CajaWindowPrivate::panes, CajaWindowSlot::pending_location, TRUE, user_data, and _CajaWindowPane::window.
Referenced by caja_application_open_location(), caja_navigation_window_back_or_forward(), caja_window_go_up(), caja_window_new_window(), caja_window_reload(), caja_window_slot_go_home(), caja_window_slot_open_location(), and caja_window_slot_open_location_with_selection().
caja_window_slot_open_location_with_selection()
void caja_window_slot_open_location_with_selection (CajaWindowSlot * slot, GFile * location, GList * selection, gboolean close_behind)
Definition at line 739 of file caja-window-manage-views.c.
References CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, CAJA_WINDOW_OPEN_FLAG_CLOSE_BEHIND, caja_window_slot_open_location_full(), and NULL.
caja_window_slot_reload()
void caja_window_slot_reload (CajaWindowSlot * slot)
Definition at line 2368 of file caja-window-manage-views.c.
References CAJA_IS_WINDOW_SLOT, CAJA_LOCATION_CHANGE_RELOAD, caja_view_get_first_visible_file(), caja_view_get_selection(), CajaWindowSlot::content_view, CajaWindowSlot::location, and NULL.
Referenced by caja_window_reload(), and G_DEFINE_TYPE_WITH_CODE().
caja_window_slot_set_content_view()
void caja_window_slot_set_content_view (CajaWindowSlot * slot, const char * id)
Definition at line 2247 of file caja-window-manage-views.c.
References caja_debug_log(), CAJA_DEBUG_LOG_DOMAIN_USER, caja_file_get(), caja_file_set_metadata(), caja_file_unref(), CAJA_IS_WINDOW, CAJA_LOCATION_CHANGE_RELOAD, CAJA_METADATA_KEY_DEFAULT_VIEW, caja_view_get_first_visible_file(), caja_view_get_selection_count(), caja_window_slot_content_view_matches_iid(), caja_window_slot_get_location_uri(), caja_window_slot_set_allow_stop(), CajaWindowSlot::content_view, FALSE, CajaWindowSlot::location, CajaWindowSlot::location_change_type, NULL, CajaWindowSlot::pane, CajaWindowSlot::pending_scroll_to, TRUE, and _CajaWindowPane::window.
caja_window_slot_stop_loading()
void caja_window_slot_stop_loading (CajaWindowSlot * slot)
Definition at line 2227 of file caja-window-manage-views.c.
References CAJA_IS_WINDOW, caja_view_stop_loading(), CAJA_WINDOW, CajaWindowSlot::content_view, FALSE, CajaWindowSlot::new_content_view, NULL, CajaWindowSlot::pane, TRUE, and _CajaWindowPane::window.
caja_window_update_up_button()
void caja_window_update_up_button (CajaWindow * window)
Definition at line 313 of file caja-window-manage-views.c.
References caja_window_allow_up(), FALSE, CajaWindowSlot::location, and NULL.