MATE Desktop Environment: caja-search-engine.c File Reference
caja-search-engine.c File Reference
#include <config.h>
#include <eel/eel-gtk-macros.h>
#include "caja-search-engine.h"
#include "caja-search-engine-beagle.h"
#include "caja-search-engine-simple.h"
#include "caja-search-engine-tracker.h"
Enumerations
enum {
HITS_ADDED , HITS_SUBTRACTED , FINISHED , ERROR ,
LAST_SIGNAL
}
Functions
G_DEFINE_ABSTRACT_TYPE (CajaSearchEngine, caja_search_engine, G_TYPE_OBJECT)
CajaSearchEngine * caja_search_engine_new (void)
void caja_search_engine_set_query (CajaSearchEngine *engine, CajaQuery *query)
void caja_search_engine_set_show_hidden_files (CajaSearchEngine *engine, gboolean show_hidden_files)
void caja_search_engine_start (CajaSearchEngine *engine)
void caja_search_engine_stop (CajaSearchEngine *engine)
gboolean caja_search_engine_is_indexed (CajaSearchEngine *engine)
void caja_search_engine_hits_added (CajaSearchEngine *engine, GList *hits)
void caja_search_engine_hits_subtracted (CajaSearchEngine *engine, GList *hits)
void caja_search_engine_finished (CajaSearchEngine *engine)
void caja_search_engine_error (CajaSearchEngine *engine, const char *error_message)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HITS_ADDED
HITS_SUBTRACTED
FINISHED
ERROR
LAST_SIGNAL
Definition at line 33 of file caja-search-engine.c.
Function Documentation
caja_search_engine_error()
void caja_search_engine_error (CajaSearchEngine * engine, const char * error_message)
Definition at line 189 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, engine, and ERROR.
caja_search_engine_finished()
void caja_search_engine_finished (CajaSearchEngine * engine)
Definition at line 181 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, engine, and FINISHED.
caja_search_engine_hits_added()
void caja_search_engine_hits_added (CajaSearchEngine * engine, GList * hits)
Definition at line 165 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, engine, and HITS_ADDED.
caja_search_engine_hits_subtracted()
void caja_search_engine_hits_subtracted (CajaSearchEngine * engine, GList * hits)
Definition at line 173 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, engine, and HITS_SUBTRACTED.
caja_search_engine_is_indexed()
gboolean caja_search_engine_is_indexed (CajaSearchEngine * engine)
Definition at line 156 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, CAJA_SEARCH_ENGINE_GET_CLASS, engine, FALSE, and NULL.
Referenced by caja_search_directory_is_indexed().
caja_search_engine_new()
CajaSearchEngine * caja_search_engine_new (void)
Definition at line 98 of file caja-search-engine.c.
References caja_search_engine_beagle_new(), caja_search_engine_simple_new(), caja_search_engine_tracker_new(), and engine.
Referenced by main().
caja_search_engine_set_query()
void caja_search_engine_set_query (CajaSearchEngine * engine, CajaQuery * query)
Definition at line 119 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, CAJA_SEARCH_ENGINE_GET_CLASS, engine, and NULL.
Referenced by main().
caja_search_engine_set_show_hidden_files()
void caja_search_engine_set_show_hidden_files (CajaSearchEngine * engine, gboolean show_hidden_files)
Definition at line 128 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, CAJA_SEARCH_ENGINE_GET_CLASS, engine, and NULL.
caja_search_engine_start()
void caja_search_engine_start (CajaSearchEngine * engine)
Definition at line 138 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, CAJA_SEARCH_ENGINE_GET_CLASS, engine, and NULL.
Referenced by main().
caja_search_engine_stop()
void caja_search_engine_stop (CajaSearchEngine * engine)
Definition at line 147 of file caja-search-engine.c.
References CAJA_IS_SEARCH_ENGINE, CAJA_SEARCH_ENGINE_GET_CLASS, engine, and NULL.
G_DEFINE_ABSTRACT_TYPE()
G_DEFINE_ABSTRACT_TYPE (CajaSearchEngine , caja_search_engine , G_TYPE_OBJECT)
References ERROR, error, FINISHED, HITS_ADDED, HITS_SUBTRACTED, and NULL.