MATE Desktop Environment: caja-actions-print.c File Reference
caja-actions-print.c File Reference
#include <glib.h>
#include <glib/gi18n.h>
#include <glib/gprintf.h>
#include <locale.h>
#include <stdlib.h>
#include <string.h>
#include <api/na-core-utils.h>
#include <api/na-object-api.h>
#include <core/na-exporter.h>
#include <core/na-export-format.h>
#include <core/na-ioption.h>
#include "console-utils.h"
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 84 of file caja-actions-print.c.
References _, console_init_log_handler(), error, FALSE, item, na_core_utils_print_version(), na_exporter_find_for_format(), and NULL.