MATE Desktop Environment: caja-icon-dnd.c File Reference
caja-icon-dnd.c File Reference
#include <config.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <gdk/gdkkeysyms.h>
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <eel/eel-background.h>
#include <eel/eel-gdk-pixbuf-extensions.h>
#include <eel/eel-glib-extensions.h>
#include <eel/eel-mate-extensions.h>
#include <eel/eel-graphic-effects.h>
#include <eel/eel-gtk-extensions.h>
#include <eel/eel-gtk-macros.h>
#include <eel/eel-stock-dialogs.h>
#include <eel/eel-string.h>
#include <eel/eel-vfs-extensions.h>
#include <eel/eel-canvas-rect-ellipse.h>
#include "caja-icon-dnd.h"
#include "caja-debug-log.h"
#include "caja-file-dnd.h"
#include "caja-icon-private.h"
#include "caja-link.h"
#include "caja-metadata.h"
#include "caja-file-utilities.h"
#include "caja-file-changes-queue.h"
Functions
void caja_icon_dnd_begin_drag (CajaIconContainer *container, GdkDragAction actions, int button, GdkEventMotion *event, int start_x, int start_y)
void caja_icon_dnd_end_drag (CajaIconContainer *container)
void caja_icon_dnd_init (CajaIconContainer *container)
void caja_icon_dnd_fini (CajaIconContainer *container)
Function Documentation
caja_icon_dnd_begin_drag()
void caja_icon_dnd_begin_drag (CajaIconContainer * container, GdkDragAction actions, int button, GdkEventMotion * event, int start_x, int start_y)
Definition at line 1532 of file caja-icon-dnd.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, CajaIconContainerDetails::dnd_info, CajaIconDndInfo::drag_info, NULL, CajaDragInfo::start_x, CajaDragInfo::start_y, and CajaDragInfo::target_list.
caja_icon_dnd_end_drag()
void caja_icon_dnd_end_drag (CajaIconContainer * container)
Definition at line 1724 of file caja-icon-dnd.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, CajaIconContainerDetails::dnd_info, and NULL.
caja_icon_dnd_fini()
void caja_icon_dnd_fini (CajaIconContainer * container)
Definition at line 1984 of file caja-icon-dnd.c.
References caja_drag_finalize(), CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, CajaIconContainerDetails::dnd_info, CajaIconDndInfo::drag_info, and NULL.
caja_icon_dnd_init()
void caja_icon_dnd_init (CajaIconContainer * container)
Definition at line 1934 of file caja-icon-dnd.c.
References caja_drag_init(), caja_icon_container_get_is_desktop(), CAJA_ICON_DND_TEXT, CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, CajaIconContainerDetails::dnd_info, CajaIconDndInfo::drag_info, NULL, and TRUE.