MATE Desktop Environment: caja-column-utilities.h File Reference
caja-column-utilities.h File Reference
#include <libcaja-extension/caja-column.h>
#include "caja-file.h"
Functions
GList * caja_get_all_columns (void)
GList * caja_get_common_columns (void)
GList * caja_get_columns_for_file (CajaFile *file)
GList * caja_column_list_copy (GList *columns)
void caja_column_list_free (GList *columns)
GList * caja_sort_columns (GList *columns, char **column_order)
Function Documentation
caja_column_list_copy()
GList * caja_column_list_copy (GList * columns)
Definition at line 256 of file caja-column-utilities.c.
References NULL.
Referenced by caja_get_common_columns().
caja_column_list_free()
void caja_column_list_free (GList * columns)
Definition at line 272 of file caja-column-utilities.c.
References NULL.
caja_get_all_columns()
GList * caja_get_all_columns (void)
Definition at line 229 of file caja-column-utilities.c.
References caja_get_common_columns(), and NULL.
caja_get_columns_for_file()
GList * caja_get_columns_for_file (CajaFile * file)
Definition at line 240 of file caja-column-utilities.c.
References caja_file_is_in_trash(), caja_get_common_columns(), and NULL.
caja_get_common_columns()
GList * caja_get_common_columns (void)
Definition at line 215 of file caja-column-utilities.c.
References caja_column_list_copy(), and NULL.
Referenced by caja_get_all_columns(), and caja_get_columns_for_file().
caja_sort_columns()
GList * caja_sort_columns (GList * columns, char ** column_order)
Definition at line 342 of file caja-column-utilities.c.
References NULL.