MATE Desktop Environment: caja-icon-container.c File Reference
caja-icon-container.c File Reference
#include <config.h>
#include <math.h>
#include <atk/atkaction.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
#include <glib/gi18n.h>
#include <stdio.h>
#include <string.h>
#include <eel/eel-accessibility.h>
#include <eel/eel-background.h>
#include <eel/eel-vfs-extensions.h>
#include <eel/eel-gdk-pixbuf-extensions.h>
#include <eel/eel-mate-extensions.h>
#include <eel/eel-gtk-extensions.h>
#include <eel/eel-art-extensions.h>
#include <eel/eel-editable-label.h>
#include <eel/eel-string.h>
#include <eel/eel-canvas.h>
#include <eel/eel-canvas-rect-ellipse.h>
#include "caja-icon-container.h"
#include "caja-debug-log.h"
#include "caja-global-preferences.h"
#include "caja-icon-private.h"
#include "caja-lib-self-check-functions.h"
#include "caja-marshal.h"
Macros
#define TAB_NAVIGATION_DISABLED
#define RUBBERBAND_TIMEOUT_INTERVAL 10
#define ICON_UNPOSITIONED_VALUE -1
#define KEYBOARD_ICON_REVEAL_TIMEOUT 10
#define MAX_CLICK_TIME 1500
#define DRAG_BUTTON 1
#define RUBBERBAND_BUTTON 1
#define MIDDLE_BUTTON 2
#define CONTEXTUAL_MENU_BUTTON 3
#define DRAG_MENU_BUTTON 2
#define MINIMUM_IMAGE_SIZE 24
#define MAXIMUM_IMAGE_SIZE 96
#define ICON_PAD_LEFT 4
#define ICON_PAD_RIGHT 4
#define ICON_PAD_TOP 4
#define ICON_PAD_BOTTOM 4
#define CONTAINER_PAD_LEFT 4
#define CONTAINER_PAD_RIGHT 4
#define CONTAINER_PAD_TOP 4
#define CONTAINER_PAD_BOTTOM 4
#define STANDARD_ICON_GRID_WIDTH 155
#define DESKTOP_PAD_HORIZONTAL 10
#define DESKTOP_PAD_VERTICAL 10
#define SNAP_SIZE_X 78
#define SNAP_SIZE_Y 20
#define ICON_SIZE_FOR_LARGE_EMBEDDED_TEXT 55
#define SNAP_HORIZONTAL(func, x)
#define SNAP_VERTICAL(func, y)
#define SNAP_NEAREST_HORIZONTAL(x)
#define SNAP_NEAREST_VERTICAL(y)
#define SNAP_CEIL_HORIZONTAL(x)
#define SNAP_CEIL_VERTICAL(y)
#define CAJA_ICON_CONTAINER_SEARCH_DIALOG_TIMEOUT 5
#define UNDEFINED_TIME ((time_t) (-1))
Typedefs
typedef struct _CajaIconContainerAccessible CajaIconContainerAccessible
typedef struct _CajaIconContainerAccessibleClass CajaIconContainerAccessibleClass
typedef gboolean(* IsBetterIconFunction) (CajaIconContainer *container, CajaIcon *start_icon, CajaIcon *best_so_far, CajaIcon *candidate, void *data)
Enumerations
enum { ACTION_ACTIVATE , ACTION_MENU , LAST_ACTION }
enum {
ACTIVATE , ACTIVATE_ALTERNATE , BAND_SELECT_STARTED , BAND_SELECT_ENDED ,
BUTTON_PRESS , CAN_ACCEPT_ITEM , CONTEXT_CLICK_BACKGROUND , CONTEXT_CLICK_SELECTION ,
MIDDLE_CLICK , GET_CONTAINER_URI , GET_ICON_URI , GET_ICON_DROP_TARGET_URI ,
GET_STORED_ICON_POSITION , ICON_POSITION_CHANGED , GET_STORED_LAYOUT_TIMESTAMP , STORE_LAYOUT_TIMESTAMP ,
ICON_TEXT_CHANGED , ICON_STRETCH_STARTED , ICON_STRETCH_ENDED , RENAMING_ICON ,
LAYOUT_CHANGED , MOVE_COPY_ITEMS , HANDLE_NETSCAPE_URL , HANDLE_URI_LIST ,
HANDLE_TEXT , HANDLE_RAW , PREVIEW , SELECTION_CHANGED ,
ICON_ADDED , ICON_REMOVED , CLEARED , START_INTERACTIVE_SEARCH ,
LAST_SIGNAL
}
Functions
G_DEFINE_TYPE (CajaIconContainer, caja_icon_container, EEL_TYPE_CANVAS)
gboolean caja_icon_container_scroll (CajaIconContainer *container, int delta_x, int delta_y)
void caja_icon_container_reset_scroll_region (CajaIconContainer *container)
void caja_icon_container_update_scroll_region (CajaIconContainer *container)
void caja_icon_container_move_icon (CajaIconContainer *container, CajaIcon *icon, int x, int y, double scale, gboolean raise, gboolean snap, gboolean update_position)
GtkWidget * caja_icon_container_new (void)
void caja_icon_container_clear (CajaIconContainer *container)
gboolean caja_icon_container_is_empty (CajaIconContainer *container)
CajaIconData * caja_icon_container_get_first_visible_icon (CajaIconContainer *container)
void caja_icon_container_scroll_to_icon (CajaIconContainer *container, CajaIconData *data)
void caja_icon_container_for_each (CajaIconContainer *container, CajaIconCallback callback, gpointer callback_data)
void caja_icon_container_update_icon (CajaIconContainer *container, CajaIcon *icon)
gboolean caja_icon_container_add (CajaIconContainer *container, CajaIconData *data)
void caja_icon_container_layout_now (CajaIconContainer *container)
gboolean caja_icon_container_remove (CajaIconContainer *container, CajaIconData *data)
void caja_icon_container_request_update (CajaIconContainer *container, CajaIconData *data)
CajaZoomLevel caja_icon_container_get_zoom_level (CajaIconContainer *container)
void caja_icon_container_set_zoom_level (CajaIconContainer *container, int new_level)
void caja_icon_container_request_update_all (CajaIconContainer *container)
void caja_icon_container_reveal (CajaIconContainer *container, CajaIconData *data)
GList * caja_icon_container_get_selection (CajaIconContainer *container)
void caja_icon_container_invert_selection (CajaIconContainer *container)
GArray * caja_icon_container_get_selected_icon_locations (CajaIconContainer *container)
void caja_icon_container_select_all (CajaIconContainer *container)
void caja_icon_container_set_selection (CajaIconContainer *container, GList *selection)
void caja_icon_container_select_list_unselect_others (CajaIconContainer *container, GList *selection)
void caja_icon_container_unselect_all (CajaIconContainer *container)
CajaIcon * caja_icon_container_get_icon_by_uri (CajaIconContainer *container, const char *uri)
void caja_icon_container_show_stretch_handles (CajaIconContainer *container)
gboolean caja_icon_container_has_stretch_handles (CajaIconContainer *container)
gboolean caja_icon_container_is_stretched (CajaIconContainer *container)
void caja_icon_container_unstretch (CajaIconContainer *container)
char * caja_icon_container_get_icon_uri (CajaIconContainer *container, CajaIcon *icon)
char * caja_icon_container_get_icon_drop_target_uri (CajaIconContainer *container, CajaIcon *icon)
void caja_icon_container_set_auto_layout (CajaIconContainer *container, gboolean auto_layout)
void caja_icon_container_set_tighter_layout (CajaIconContainer *container, gboolean tighter_layout)
gboolean caja_icon_container_is_keep_aligned (CajaIconContainer *container)
gboolean caja_icon_container_is_lock_icons_position (CajaIconContainer *container)
void caja_icon_container_set_keep_aligned (CajaIconContainer *container, gboolean keep_aligned)
void caja_icon_container_set_lock_icons_position (CajaIconContainer *container, gboolean lock_icons_position)
void caja_icon_container_set_layout_mode (CajaIconContainer *container, CajaIconLayoutMode mode)
void caja_icon_container_set_label_position (CajaIconContainer *container, CajaIconLabelPosition position)
void caja_display_git_branch_enable (CajaIconContainer *container, CajaDisplayGitBranch enable)
void caja_icon_container_freeze_icon_positions (CajaIconContainer *container)
void caja_icon_container_sort (CajaIconContainer *container)
gboolean caja_icon_container_is_auto_layout (CajaIconContainer *container)
gboolean caja_icon_container_is_tighter_layout (CajaIconContainer *container)
void caja_icon_container_start_renaming_selected_item (CajaIconContainer *container, gboolean select_all)
gboolean caja_icon_container_emit_preview_signal (CajaIconContainer *icon_container, CajaIcon *icon, gboolean start_flag)
gboolean caja_icon_container_has_stored_icon_positions (CajaIconContainer *container)
void caja_icon_container_set_single_click_mode (CajaIconContainer *container, gboolean single_click_mode)
gboolean caja_icon_container_get_is_fixed_size (CajaIconContainer *container)
void caja_icon_container_set_is_fixed_size (CajaIconContainer *container, gboolean is_fixed_size)
gboolean caja_icon_container_get_is_desktop (CajaIconContainer *container)
void caja_icon_container_set_is_desktop (CajaIconContainer *container, gboolean is_desktop)
void caja_icon_container_set_margins (CajaIconContainer *container, int left_margin, int right_margin, int top_margin, int bottom_margin)
void caja_icon_container_set_use_drop_shadows (CajaIconContainer *container, gboolean use_drop_shadows)
void caja_icon_container_set_font (CajaIconContainer *container, const char *font)
void caja_icon_container_set_font_size_table (CajaIconContainer *container, const int font_size_table[CAJA_ZOOM_LEVEL_LARGEST+1])
char * caja_icon_container_get_icon_description (CajaIconContainer *container, CajaIconData *data)
gboolean caja_icon_container_get_allow_moves (CajaIconContainer *container)
void caja_icon_container_set_allow_moves (CajaIconContainer *container, gboolean allow_moves)
void caja_icon_container_set_forced_icon_size (CajaIconContainer *container, int forced_icon_size)
void caja_icon_container_set_all_columns_same_width (CajaIconContainer *container, gboolean all_columns_same_width)
void caja_icon_container_set_highlighted_for_clipboard (CajaIconContainer *container, GList *clipboard_icon_data)
void caja_icon_container_widget_to_file_operation_position (CajaIconContainer *container, GdkPoint *position)
G_DEFINE_TYPE_WITH_CODE (CajaIconContainerAccessible, caja_icon_container_accessible, eel_canvas_accessible_get_type(), G_IMPLEMENT_INTERFACE(ATK_TYPE_ACTION, caja_icon_container_accessible_action_interface_init) G_IMPLEMENT_INTERFACE(ATK_TYPE_SELECTION, caja_icon_container_accessible_selection_interface_init))
void caja_self_check_icon_container (void)
gboolean caja_icon_container_is_layout_rtl (CajaIconContainer *container)
gboolean caja_icon_container_is_layout_vertical (CajaIconContainer *container)
int caja_icon_container_get_max_layout_lines_for_pango (CajaIconContainer *container)
int caja_icon_container_get_max_layout_lines (CajaIconContainer *container)
void caja_icon_container_begin_loading (CajaIconContainer *container)
void caja_icon_container_end_loading (CajaIconContainer *container, gboolean all_icons_added)
gboolean caja_icon_container_get_store_layout_timestamps (CajaIconContainer *container)
void caja_icon_container_set_store_layout_timestamps (CajaIconContainer *container, gboolean store_layout_timestamps)
Macro Definition Documentation
CAJA_ICON_CONTAINER_SEARCH_DIALOG_TIMEOUT
#define CAJA_ICON_CONTAINER_SEARCH_DIALOG_TIMEOUT 5
Definition at line 121 of file caja-icon-container.c.
CONTAINER_PAD_BOTTOM
#define CONTAINER_PAD_BOTTOM 4
Definition at line 96 of file caja-icon-container.c.
Referenced by caja_icon_container_update_scroll_region().
CONTAINER_PAD_LEFT
#define CONTAINER_PAD_LEFT 4
Definition at line 93 of file caja-icon-container.c.
Referenced by caja_icon_container_update_scroll_region().
CONTAINER_PAD_RIGHT
#define CONTAINER_PAD_RIGHT 4
Definition at line 94 of file caja-icon-container.c.
Referenced by caja_icon_container_update_scroll_region().
CONTAINER_PAD_TOP
#define CONTAINER_PAD_TOP 4
Definition at line 95 of file caja-icon-container.c.
Referenced by caja_icon_container_update_scroll_region().
CONTEXTUAL_MENU_BUTTON
#define CONTEXTUAL_MENU_BUTTON 3
Definition at line 80 of file caja-icon-container.c.
DESKTOP_PAD_HORIZONTAL
#define DESKTOP_PAD_HORIZONTAL 10
Definition at line 101 of file caja-icon-container.c.
DESKTOP_PAD_VERTICAL
#define DESKTOP_PAD_VERTICAL 10
Definition at line 102 of file caja-icon-container.c.
DRAG_BUTTON
#define DRAG_BUTTON 1
Definition at line 77 of file caja-icon-container.c.
DRAG_MENU_BUTTON
#define DRAG_MENU_BUTTON 2
Definition at line 81 of file caja-icon-container.c.
ICON_PAD_BOTTOM
#define ICON_PAD_BOTTOM 4
Definition at line 91 of file caja-icon-container.c.
Referenced by caja_icon_container_update_scroll_region().
ICON_PAD_LEFT
#define ICON_PAD_LEFT 4
Definition at line 87 of file caja-icon-container.c.
Referenced by caja_icon_container_get_first_visible_icon(), and caja_icon_container_update_scroll_region().
ICON_PAD_RIGHT
#define ICON_PAD_RIGHT 4
Definition at line 88 of file caja-icon-container.c.
Referenced by caja_icon_container_update_scroll_region().
ICON_PAD_TOP
#define ICON_PAD_TOP 4
Definition at line 90 of file caja-icon-container.c.
Referenced by caja_icon_container_get_first_visible_icon(), and caja_icon_container_update_scroll_region().
ICON_SIZE_FOR_LARGE_EMBEDDED_TEXT
#define ICON_SIZE_FOR_LARGE_EMBEDDED_TEXT 55
Definition at line 109 of file caja-icon-container.c.
Referenced by caja_icon_container_update_icon().
ICON_UNPOSITIONED_VALUE
#define ICON_UNPOSITIONED_VALUE -1
Definition at line 63 of file caja-icon-container.c.
Referenced by caja_icon_container_add().
KEYBOARD_ICON_REVEAL_TIMEOUT
#define KEYBOARD_ICON_REVEAL_TIMEOUT 10
Definition at line 69 of file caja-icon-container.c.
MAX_CLICK_TIME
#define MAX_CLICK_TIME 1500
Definition at line 74 of file caja-icon-container.c.
MAXIMUM_IMAGE_SIZE
#define MAXIMUM_IMAGE_SIZE 96
Definition at line 85 of file caja-icon-container.c.
Referenced by caja_icon_container_update_icon().
MIDDLE_BUTTON
#define MIDDLE_BUTTON 2
Definition at line 79 of file caja-icon-container.c.
MINIMUM_IMAGE_SIZE
#define MINIMUM_IMAGE_SIZE 24
Definition at line 84 of file caja-icon-container.c.
Referenced by caja_icon_container_update_icon().
RUBBERBAND_BUTTON
#define RUBBERBAND_BUTTON 1
Definition at line 78 of file caja-icon-container.c.
RUBBERBAND_TIMEOUT_INTERVAL
#define RUBBERBAND_TIMEOUT_INTERVAL 10
Definition at line 60 of file caja-icon-container.c.
SNAP_CEIL_HORIZONTAL
#define SNAP_CEIL_HORIZONTAL (x)
Value:
SNAP_HORIZONTAL (ceil, x)
Definition at line 117 of file caja-icon-container.c.
SNAP_CEIL_VERTICAL
#define SNAP_CEIL_VERTICAL (y)
Value:
SNAP_VERTICAL (ceil, y)
Definition at line 118 of file caja-icon-container.c.
SNAP_HORIZONTAL
#define SNAP_HORIZONTAL (func, x)
Value:
((func ((double)((x) - DESKTOP_PAD_HORIZONTAL) / SNAP_SIZE_X) * SNAP_SIZE_X) + DESKTOP_PAD_HORIZONTAL)
Definition at line 111 of file caja-icon-container.c.
SNAP_NEAREST_HORIZONTAL
#define SNAP_NEAREST_HORIZONTAL (x)
Value:
SNAP_HORIZONTAL (eel_round, x)
Definition at line 114 of file caja-icon-container.c.
SNAP_NEAREST_VERTICAL
#define SNAP_NEAREST_VERTICAL (y)
Value:
SNAP_VERTICAL (eel_round, y)
Definition at line 115 of file caja-icon-container.c.
SNAP_SIZE_X
#define SNAP_SIZE_X 78
Definition at line 103 of file caja-icon-container.c.
SNAP_SIZE_Y
#define SNAP_SIZE_Y 20
Definition at line 104 of file caja-icon-container.c.
SNAP_VERTICAL
#define SNAP_VERTICAL (func, y)
Value:
((func ((double)((y) - DESKTOP_PAD_VERTICAL) / SNAP_SIZE_Y) * SNAP_SIZE_Y) + DESKTOP_PAD_VERTICAL)
Definition at line 112 of file caja-icon-container.c.
STANDARD_ICON_GRID_WIDTH
#define STANDARD_ICON_GRID_WIDTH 155
Definition at line 98 of file caja-icon-container.c.
TAB_NAVIGATION_DISABLED
#define TAB_NAVIGATION_DISABLED
Definition at line 57 of file caja-icon-container.c.
UNDEFINED_TIME
#define UNDEFINED_TIME ((time_t) (-1))
Definition at line 124 of file caja-icon-container.c.
Typedef Documentation
CajaIconContainerAccessible
typedef struct _CajaIconContainerAccessible CajaIconContainerAccessible
Definition at line 141 of file caja-icon-container.c.
CajaIconContainerAccessibleClass
typedef struct _CajaIconContainerAccessibleClass CajaIconContainerAccessibleClass
Definition at line 142 of file caja-icon-container.c.
IsBetterIconFunction
typedef gboolean(* IsBetterIconFunction) (CajaIconContainer *container, CajaIcon *start_icon, CajaIcon *best_so_far, CajaIcon *candidate, void *data)
Definition at line 3007 of file caja-icon-container.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ACTIVATE
ACTIVATE_ALTERNATE
BAND_SELECT_STARTED
BAND_SELECT_ENDED
BUTTON_PRESS
CAN_ACCEPT_ITEM
CONTEXT_CLICK_BACKGROUND
CONTEXT_CLICK_SELECTION
MIDDLE_CLICK
GET_CONTAINER_URI
GET_ICON_URI
GET_ICON_DROP_TARGET_URI
GET_STORED_ICON_POSITION
ICON_POSITION_CHANGED
GET_STORED_LAYOUT_TIMESTAMP
STORE_LAYOUT_TIMESTAMP
ICON_TEXT_CHANGED
ICON_STRETCH_STARTED
ICON_STRETCH_ENDED
RENAMING_ICON
LAYOUT_CHANGED
MOVE_COPY_ITEMS
HANDLE_NETSCAPE_URL
HANDLE_URI_LIST
HANDLE_TEXT
HANDLE_RAW
PREVIEW
SELECTION_CHANGED
ICON_ADDED
ICON_REMOVED
CLEARED
START_INTERACTIVE_SEARCH
LAST_SIGNAL
Definition at line 233 of file caja-icon-container.c.
anonymous enum
anonymous enum
Enumerator
ACTION_ACTIVATE
ACTION_MENU
LAST_ACTION
Definition at line 126 of file caja-icon-container.c.
Function Documentation
caja_display_git_branch_enable()
void caja_display_git_branch_enable (CajaIconContainer * container, CajaDisplayGitBranch enable)
Definition at line 8827 of file caja-icon-container.c.
References caja_icon_container_request_update_all(), CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::display_git_branch.
caja_icon_container_add()
gboolean caja_icon_container_add (CajaIconContainer * container, CajaIconData * data)
caja_icon_container_add: @container: A CajaIconContainer @data: Icon data.
Add icon to represent @data to container. Returns FALSE if there was already such an icon.
Definition at line 7879 of file caja-icon-container.c.
References band, CAJA_ICON_CANVAS_ITEM, caja_icon_canvas_item_get_type(), CAJA_ICON_CONTAINER, CAJA_IS_ICON_CONTAINER, data, CajaIconContainer::details, EEL_CANVAS, EEL_CANVAS_GROUP, EEL_CANVAS_ITEM, eel_canvas_item_new(), eel_canvas_item_send_behind(), FALSE, CajaIconContainerDetails::icon_set, ICON_UNPOSITIONED_VALUE, CajaIconContainerDetails::icons, item, CajaIconContainerDetails::new_icons, NULL, and TRUE.
caja_icon_container_begin_loading()
void caja_icon_container_begin_loading (CajaIconContainer * container)
Definition at line 10169 of file caja-icon-container.c.
References caja_icon_container_get_store_layout_timestamps(), CajaIconContainer::details, GET_STORED_LAYOUT_TIMESTAMP, CajaIconContainerDetails::layout_timestamp, NULL, and UNDEFINED_TIME.
caja_icon_container_clear()
void caja_icon_container_clear (CajaIconContainer * container)
Definition at line 7034 of file caja-icon-container.c.
References caja_icon_container_update_scroll_region(), CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, CajaIconContainerDetails::drop_target, FALSE, CajaIconContainerDetails::icon_set, CajaIconContainerDetails::icons, CajaIconContainerDetails::layout_timestamp, CajaIconContainerDetails::new_icons, NULL, CajaIconContainerDetails::store_layout_timestamps_when_finishing_new_icons, CajaIconContainerDetails::stretch_icon, TRUE, and UNDEFINED_TIME.
caja_icon_container_emit_preview_signal()
gboolean caja_icon_container_emit_preview_signal (CajaIconContainer * icon_container, CajaIcon * icon, gboolean start_flag)
Definition at line 9207 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, FALSE, NULL, PREVIEW, and TRUE.
caja_icon_container_end_loading()
void caja_icon_container_end_loading (CajaIconContainer * container, gboolean all_icons_added)
Definition at line 10205 of file caja-icon-container.c.
References caja_icon_container_get_store_layout_timestamps(), CajaIconContainer::details, CajaIconContainerDetails::new_icons, NULL, CajaIconContainerDetails::store_layout_timestamps_when_finishing_new_icons, and TRUE.
caja_icon_container_for_each()
void caja_icon_container_for_each (CajaIconContainer * container, CajaIconCallback callback, gpointer callback_data)
Definition at line 7246 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::icons.
caja_icon_container_freeze_icon_positions()
void caja_icon_container_freeze_icon_positions (CajaIconContainer * container)
Definition at line 8848 of file caja-icon-container.c.
References CajaIconContainerDetails::auto_layout, CajaIconContainer::details, FALSE, ICON_POSITION_CHANGED, CajaIconContainerDetails::icons, LAYOUT_CHANGED, NULL, CajaIconPosition::scale, CajaIconPosition::x, and CajaIconPosition::y.
Referenced by caja_icon_container_set_auto_layout().
caja_icon_container_get_allow_moves()
gboolean caja_icon_container_get_allow_moves (CajaIconContainer * container)
Definition at line 9412 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, CajaIconContainerDetails::drag_allow_moves, and FALSE.
caja_icon_container_get_first_visible_icon()
CajaIconData * caja_icon_container_get_first_visible_icon (CajaIconContainer * container)
Definition at line 7089 of file caja-icon-container.c.
References caja_icon_container_is_layout_rtl(), caja_icon_container_is_layout_vertical(), CajaIcon::data, CajaIconContainer::details, EEL_CANVAS, eel_canvas_c2w(), EEL_CANVAS_ITEM, eel_canvas_item_get_bounds(), FALSE, ICON_PAD_LEFT, ICON_PAD_TOP, CajaIconContainerDetails::icons, NULL, and TRUE.
caja_icon_container_get_icon_by_uri()
CajaIcon * caja_icon_container_get_icon_by_uri (CajaIconContainer * container, const char * uri)
caja_icon_container_get_icon_by_uri: @container: An icon container widget. @uri: The uri of an icon to find.
Locate an icon, given the URI. The URI must match exactly. Later we may have to have some way of figuring out if the URI specifies the same object that does not require an exact match.
Definition at line 8369 of file caja-icon-container.c.
References caja_icon_container_get_icon_uri(), CajaIcon::data, CajaIconContainer::details, CajaIconContainerDetails::icons, and NULL.
caja_icon_container_get_icon_description()
char * caja_icon_container_get_icon_description (CajaIconContainer * container, CajaIconData * data)
caja_icon_container_get_icon_description @container: An icon container widget. @data: Icon data
Gets the description for the icon. This function may return NULL.
Definition at line 9394 of file caja-icon-container.c.
References CAJA_ICON_CONTAINER_GET_CLASS, data, CajaIconContainerClass::get_icon_description, and NULL.
caja_icon_container_get_icon_drop_target_uri()
char * caja_icon_container_get_icon_drop_target_uri (CajaIconContainer * container, CajaIcon * icon)
Definition at line 8635 of file caja-icon-container.c.
References GET_ICON_DROP_TARGET_URI, and NULL.
caja_icon_container_get_icon_uri()
char * caja_icon_container_get_icon_uri (CajaIconContainer * container, CajaIcon * icon)
Definition at line 8621 of file caja-icon-container.c.
References GET_ICON_URI, and NULL.
Referenced by caja_icon_container_get_icon_by_uri().
caja_icon_container_get_is_desktop()
gboolean caja_icon_container_get_is_desktop (CajaIconContainer * container)
Definition at line 9282 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, and CajaIconContainerDetails::is_desktop.
Referenced by caja_icon_container_get_max_layout_lines(), caja_icon_container_get_max_layout_lines_for_pango(), and caja_icon_dnd_init().
caja_icon_container_get_is_fixed_size()
gboolean caja_icon_container_get_is_fixed_size (CajaIconContainer * container)
Definition at line 9264 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, and CajaIconContainerDetails::is_fixed_size.
Referenced by caja_icon_container_update_scroll_region().
caja_icon_container_get_max_layout_lines()
int caja_icon_container_get_max_layout_lines (CajaIconContainer * container)
Definition at line 10147 of file caja-icon-container.c.
References caja_icon_container_get_is_desktop(), CajaIconContainer::details, and CajaIconContainerDetails::zoom_level.
caja_icon_container_get_max_layout_lines_for_pango()
int caja_icon_container_get_max_layout_lines_for_pango (CajaIconContainer * container)
Definition at line 10125 of file caja-icon-container.c.
References caja_icon_container_get_is_desktop(), CajaIconContainer::details, and CajaIconContainerDetails::zoom_level.
caja_icon_container_get_selected_icon_locations()
GArray * caja_icon_container_get_selected_icon_locations (CajaIconContainer * container)
caja_icon_container_get_selected_icon_locations: @container: An icon container widget.
Returns an array of GdkPoints of locations of the selected icons.
Definition at line 8213 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, and NULL.
caja_icon_container_get_selection()
GList * caja_icon_container_get_selection (CajaIconContainer * container)
caja_icon_container_get_selection: @container: An icon container.
Get a list of the icons currently selected in @container.
Return value: A GList of the programmer-specified data associated to each selected icon, or NULL if no icon is selected. The caller is expected to free the list when it is not needed anymore.
Definition at line 8115 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIcon::data, CajaIconContainer::details, CajaIconContainerDetails::icons, and NULL.
caja_icon_container_get_store_layout_timestamps()
gboolean caja_icon_container_get_store_layout_timestamps (CajaIconContainer * container)
Definition at line 10223 of file caja-icon-container.c.
References CajaIconContainer::details, and CajaIconContainerDetails::store_layout_timestamps.
Referenced by caja_icon_container_begin_loading(), and caja_icon_container_end_loading().
caja_icon_container_get_zoom_level()
CajaZoomLevel caja_icon_container_get_zoom_level (CajaIconContainer * container)
Definition at line 8011 of file caja-icon-container.c.
References CajaIconContainer::details, and CajaIconContainerDetails::zoom_level.
caja_icon_container_has_stored_icon_positions()
gboolean caja_icon_container_has_stored_icon_positions (CajaIconContainer * container)
Definition at line 9228 of file caja-icon-container.c.
References CajaIconContainer::details, FALSE, GET_STORED_ICON_POSITION, CajaIconContainerDetails::icons, NULL, and TRUE.
caja_icon_container_has_stretch_handles()
gboolean caja_icon_container_has_stretch_handles (CajaIconContainer * container)
caja_icon_container_has_stretch_handles @container: An icon container widget.
Returns true if the first selected item has stretch handles.
Definition at line 8518 of file caja-icon-container.c.
References CajaIconContainer::details, FALSE, NULL, and CajaIconContainerDetails::stretch_icon.
caja_icon_container_invert_selection()
void caja_icon_container_invert_selection (CajaIconContainer * container)
caja_icon_container_invert_selection: @container: An icon container.
Inverts the selection in @container.
Definition at line 8166 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIcon::data, CajaIconContainer::details, CajaIconContainerDetails::icons, NULL, and SELECTION_CHANGED.
caja_icon_container_is_auto_layout()
gboolean caja_icon_container_is_auto_layout (CajaIconContainer * container)
Definition at line 8894 of file caja-icon-container.c.
References CajaIconContainerDetails::auto_layout, CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and FALSE.
Referenced by caja_icon_container_scroll_to_icon(), and caja_icon_container_update_scroll_region().
caja_icon_container_is_empty()
gboolean caja_icon_container_is_empty (CajaIconContainer * container)
Definition at line 7083 of file caja-icon-container.c.
References CajaIconContainer::details, CajaIconContainerDetails::icons, and NULL.
Referenced by caja_icon_container_update_scroll_region().
caja_icon_container_is_keep_aligned()
gboolean caja_icon_container_is_keep_aligned (CajaIconContainer * container)
Definition at line 8723 of file caja-icon-container.c.
References CajaIconContainer::details, and CajaIconContainerDetails::keep_aligned.
caja_icon_container_is_layout_rtl()
gboolean caja_icon_container_is_layout_rtl (CajaIconContainer * container)
Definition at line 10107 of file caja-icon-container.c.
References CAJA_ICON_LAYOUT_R_L_T_B, CAJA_ICON_LAYOUT_T_B_R_L, CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::layout_mode.
Referenced by caja_icon_canvas_item_get_drag_surface(), caja_icon_canvas_item_update_bounds(), caja_icon_container_get_first_visible_icon(), caja_icon_container_move_icon(), caja_icon_container_scroll_to_icon(), and caja_icon_container_update_scroll_region().
caja_icon_container_is_layout_vertical()
gboolean caja_icon_container_is_layout_vertical (CajaIconContainer * container)
Definition at line 10116 of file caja-icon-container.c.
References CAJA_ICON_LAYOUT_T_B_L_R, CAJA_ICON_LAYOUT_T_B_R_L, CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, and CajaIconContainerDetails::layout_mode.
Referenced by caja_icon_container_get_first_visible_icon(), caja_icon_container_scroll_to_icon(), caja_icon_container_start_renaming_selected_item(), and caja_icon_container_update_scroll_region().
caja_icon_container_is_lock_icons_position()
gboolean caja_icon_container_is_lock_icons_position (CajaIconContainer * container)
Definition at line 8729 of file caja-icon-container.c.
References CajaIconContainer::details, and CajaIconContainerDetails::lock_icons_position.
caja_icon_container_is_stretched()
gboolean caja_icon_container_is_stretched (CajaIconContainer * container)
caja_icon_container_is_stretched @container: An icon container widget.
Returns true if the any selected item is stretched to a size other than 1.0.
Definition at line 8538 of file caja-icon-container.c.
References CajaIconContainer::details, FALSE, CajaIconContainerDetails::icons, NULL, and TRUE.
caja_icon_container_is_tighter_layout()
gboolean caja_icon_container_is_tighter_layout (CajaIconContainer * container)
Definition at line 8902 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, and CajaIconContainerDetails::tighter_layout.
Referenced by caja_icon_canvas_item_get_max_text_width().
caja_icon_container_layout_now()
void caja_icon_container_layout_now (CajaIconContainer * container)
Definition at line 7936 of file caja-icon-container.c.
References CajaIconContainer::details, and CajaIconContainerDetails::idle_id.
Referenced by caja_icon_container_scroll_to_icon().
caja_icon_container_move_icon()
void caja_icon_container_move_icon (CajaIconContainer * container, CajaIcon * icon, int x, int y, double scale, gboolean raise, gboolean snap, gboolean update_position)
Definition at line 2617 of file caja-icon-container.c.
References CajaIconContainerDetails::auto_layout, caja_icon_container_is_layout_rtl(), caja_icon_container_update_icon(), CajaIconContainer::details, FALSE, ICON_POSITION_CHANGED, CajaIconContainerDetails::keep_aligned, CajaIconContainerDetails::lock_icons_position, CajaIconPosition::scale, TRUE, CajaIconPosition::x, and CajaIconPosition::y.
Referenced by caja_icon_container_unstretch().
caja_icon_container_new()
GtkWidget * caja_icon_container_new (void)
Definition at line 7027 of file caja-icon-container.c.
References CAJA_TYPE_ICON_CONTAINER, and NULL.
caja_icon_container_remove()
gboolean caja_icon_container_remove (CajaIconContainer * container, CajaIconData * data)
caja_icon_container_remove: @container: A CajaIconContainer. @data: Icon data.
Remove the icon with this data.
Definition at line 7958 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, data, CajaIconContainer::details, FALSE, ICON_REMOVED, CajaIconContainerDetails::icon_set, NULL, and TRUE.
caja_icon_container_request_update()
void caja_icon_container_request_update (CajaIconContainer * container, CajaIconData * data)
caja_icon_container_request_update: @container: A CajaIconContainer. @data: Icon data.
Update the icon with this data.
Definition at line 7991 of file caja-icon-container.c.
References caja_icon_container_update_icon(), CAJA_IS_ICON_CONTAINER, data, CajaIconContainer::details, CajaIconContainerDetails::icon_set, and NULL.
caja_icon_container_request_update_all()
void caja_icon_container_request_update_all (CajaIconContainer * container)
caja_icon_container_request_update_all: For each icon, synchronizes the displayed information (image, text) with the information from the model.
@container: An icon container.
Definition at line 8061 of file caja-icon-container.c.
References CajaIconContainerDetails::auto_layout, caja_icon_container_update_icon(), CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, CajaIconContainerDetails::icons, CajaIconContainerDetails::is_loading, NULL, and TRUE.
Referenced by caja_display_git_branch_enable(), caja_icon_container_set_all_columns_same_width(), caja_icon_container_set_font(), caja_icon_container_set_font_size_table(), caja_icon_container_set_forced_icon_size(), caja_icon_container_set_label_position(), caja_icon_container_set_tighter_layout(), and caja_icon_container_set_zoom_level().
caja_icon_container_reset_scroll_region()
void caja_icon_container_reset_scroll_region (CajaIconContainer * container)
Definition at line 1065 of file caja-icon-container.c.
References CajaIconContainer::details, CajaIconContainerDetails::reset_scroll_region_trigger, and TRUE.
caja_icon_container_reveal()
void caja_icon_container_reveal (CajaIconContainer * container, CajaIconData * data)
caja_icon_container_reveal: Change scroll position as necessary to reveal the specified item.
Definition at line 8089 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, data, CajaIconContainer::details, CajaIconContainerDetails::icon_set, and NULL.
caja_icon_container_scroll()
gboolean caja_icon_container_scroll (CajaIconContainer * container, int delta_x, int delta_y)
Definition at line 603 of file caja-icon-container.c.
caja_icon_container_scroll_to_icon()
void caja_icon_container_scroll_to_icon (CajaIconContainer * container, CajaIconData * data)
Definition at line 7181 of file caja-icon-container.c.
References caja_icon_container_is_auto_layout(), caja_icon_container_is_layout_rtl(), caja_icon_container_is_layout_vertical(), caja_icon_container_layout_now(), data, CajaIconContainer::details, EEL_CANVAS_ITEM, CajaIconContainerDetails::icons, NULL, TRUE, EelIRect::x0, EelIRect::x1, and EelIRect::y0.
caja_icon_container_select_all()
void caja_icon_container_select_all (CajaIconContainer * container)
caja_icon_container_select_all: @container: An icon container widget.
Select all the icons in @container at once.
Definition at line 8234 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, CajaIconContainerDetails::icons, NULL, SELECTION_CHANGED, and TRUE.
caja_icon_container_select_list_unselect_others()
void caja_icon_container_select_list_unselect_others (CajaIconContainer * container, GList * selection)
caja_icon_container_select_list_unselect_others. @container: An icon container widget. @selection: A list of CajaIcon *.
Set the selection to exactly the icons in @selection.
Definition at line 8309 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, hash, CajaIconContainerDetails::icons, NULL, and SELECTION_CHANGED.
caja_icon_container_set_all_columns_same_width()
void caja_icon_container_set_all_columns_same_width (CajaIconContainer * container, gboolean all_columns_same_width)
Definition at line 9444 of file caja-icon-container.c.
References CajaIconContainerDetails::all_columns_same_width, caja_icon_container_request_update_all(), CAJA_IS_ICON_CONTAINER, and CajaIconContainer::details.
caja_icon_container_set_allow_moves()
void caja_icon_container_set_allow_moves (CajaIconContainer * container, gboolean allow_moves)
Definition at line 9420 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::drag_allow_moves.
caja_icon_container_set_auto_layout()
void caja_icon_container_set_auto_layout (CajaIconContainer * container, gboolean auto_layout)
Definition at line 8665 of file caja-icon-container.c.
References CajaIconContainerDetails::auto_layout, caja_icon_container_freeze_icon_positions(), CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, LAYOUT_CHANGED, and TRUE.
caja_icon_container_set_font()
void caja_icon_container_set_font (CajaIconContainer * container, const char * font)
Definition at line 9341 of file caja-icon-container.c.
References caja_icon_container_request_update_all(), CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::font.
caja_icon_container_set_font_size_table()
void caja_icon_container_set_font_size_table (CajaIconContainer * container, const int font_size_table[CAJA_ZOOM_LEVEL_LARGEST+1])
Definition at line 9360 of file caja-icon-container.c.
References caja_icon_container_request_update_all(), CAJA_IS_ICON_CONTAINER, CAJA_ZOOM_LEVEL_LARGEST, CajaIconContainer::details, CajaIconContainerDetails::font_size_table, NULL, and CajaIconContainerDetails::zoom_level.
caja_icon_container_set_forced_icon_size()
void caja_icon_container_set_forced_icon_size (CajaIconContainer * container, int forced_icon_size)
Definition at line 9429 of file caja-icon-container.c.
References caja_icon_container_request_update_all(), CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::forced_icon_size.
caja_icon_container_set_highlighted_for_clipboard()
void caja_icon_container_set_highlighted_for_clipboard (CajaIconContainer * container, GList * clipboard_icon_data)
caja_icon_container_set_highlighted_for_clipboard @container: An icon container widget. @data: Icon Data associated with all icons that should be highlighted. Others will be unhighlighted.
Definition at line 9465 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, EEL_CANVAS_ITEM, eel_canvas_item_set(), CajaIconContainerDetails::icons, and NULL.
caja_icon_container_set_is_desktop()
void caja_icon_container_set_is_desktop (CajaIconContainer * container, gboolean is_desktop)
Definition at line 9290 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::is_desktop.
caja_icon_container_set_is_fixed_size()
void caja_icon_container_set_is_fixed_size (CajaIconContainer * container, gboolean is_fixed_size)
Definition at line 9273 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::is_fixed_size.
caja_icon_container_set_keep_aligned()
void caja_icon_container_set_keep_aligned (CajaIconContainer * container, gboolean keep_aligned)
Definition at line 8768 of file caja-icon-container.c.
References CajaIconContainerDetails::auto_layout, CajaIconContainer::details, and CajaIconContainerDetails::keep_aligned.
caja_icon_container_set_label_position()
void caja_icon_container_set_label_position (CajaIconContainer * container, CajaIconLabelPosition position)
Definition at line 8810 of file caja-icon-container.c.
References caja_icon_container_request_update_all(), CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::label_position.
caja_icon_container_set_layout_mode()
void caja_icon_container_set_layout_mode (CajaIconContainer * container, CajaIconLayoutMode mode)
Definition at line 8796 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, LAYOUT_CHANGED, and CajaIconContainerDetails::layout_mode.
caja_icon_container_set_lock_icons_position()
void caja_icon_container_set_lock_icons_position (CajaIconContainer * container, gboolean lock_icons_position)
Definition at line 8787 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::lock_icons_position.
caja_icon_container_set_margins()
void caja_icon_container_set_margins (CajaIconContainer * container, int left_margin, int right_margin, int top_margin, int bottom_margin)
Definition at line 9306 of file caja-icon-container.c.
References CajaIconContainerDetails::bottom_margin, CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, CajaIconContainerDetails::left_margin, CajaIconContainerDetails::right_margin, and CajaIconContainerDetails::top_margin.
caja_icon_container_set_selection()
void caja_icon_container_set_selection (CajaIconContainer * container, GList * selection)
caja_icon_container_set_selection: @container: An icon container widget. @selection: A list of CajaIconData *.
Set the selection to exactly the icons in @container which have programmer data matching one of the items in @selection.
Definition at line 8267 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, hash, CajaIconContainerDetails::icons, NULL, and SELECTION_CHANGED.
caja_icon_container_set_single_click_mode()
void caja_icon_container_set_single_click_mode (CajaIconContainer * container, gboolean single_click_mode)
Definition at line 9254 of file caja-icon-container.c.
References CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, and CajaIconContainerDetails::single_click_mode.
caja_icon_container_set_store_layout_timestamps()
void caja_icon_container_set_store_layout_timestamps (CajaIconContainer * container, gboolean store_layout_timestamps)
Definition at line 10229 of file caja-icon-container.c.
References CajaIconContainer::details, FALSE, and CajaIconContainerDetails::store_layout_timestamps.
caja_icon_container_set_tighter_layout()
void caja_icon_container_set_tighter_layout (CajaIconContainer * container, gboolean tighter_layout)
Definition at line 8692 of file caja-icon-container.c.
References CajaIconContainerDetails::auto_layout, caja_icon_container_request_update_all(), CAJA_IS_ICON_CONTAINER, CajaIconContainer::details, FALSE, LAYOUT_CHANGED, CajaIconContainerDetails::tighter_layout, and TRUE.
caja_icon_container_set_use_drop_shadows()
void caja_icon_container_set_use_drop_shadows (CajaIconContainer * container, gboolean use_drop_shadows)
Definition at line 9324 of file caja-icon-container.c.
References CajaIconContainer::details, CajaIconContainerDetails::drop_shadows_requested, and CajaIconContainerDetails::use_drop_shadows.
caja_icon_container_set_zoom_level()
void caja_icon_container_set_zoom_level (CajaIconContainer * container, int new_level)
Definition at line 8017 of file caja-icon-container.c.
References caja_get_icon_size_for_zoom_level(), caja_icon_container_request_update_all(), CAJA_ICON_SIZE_STANDARD, CAJA_ZOOM_LEVEL_LARGEST, CAJA_ZOOM_LEVEL_SMALLEST, CajaIconContainer::details, EEL_CANVAS, eel_canvas_set_pixels_per_unit(), TRUE, and CajaIconContainerDetails::zoom_level.
caja_icon_container_show_stretch_handles()
void caja_icon_container_show_stretch_handles (CajaIconContainer * container)
caja_icon_container_show_stretch_handles: @container: An icon container widget.
Makes stretch handles visible on the first selected icon.
Definition at line 8471 of file caja-icon-container.c.
References caja_icon_canvas_item_set_show_stretch_handles(), CajaIconContainer::details, FALSE, CajaIcon::item, NULL, CajaIconContainerDetails::stretch_icon, CajaIconContainerDetails::stretch_initial_size, CajaIconContainerDetails::stretch_initial_x, CajaIconContainerDetails::stretch_initial_y, and TRUE.
caja_icon_container_sort()
void caja_icon_container_sort (CajaIconContainer * container)
Definition at line 8877 of file caja-icon-container.c.
References CajaIconContainerDetails::auto_layout, CajaIconContainer::details, LAYOUT_CHANGED, and TRUE.
caja_icon_container_start_renaming_selected_item()
void caja_icon_container_start_renaming_selected_item (CajaIconContainer * container, gboolean select_all)
caja_icon_container_start_renaming_selected_item @container: An icon container widget. @select_all: Whether the whole file should initially be selected, or only its basename (i.e. everything except its extension).
Displays the edit name widget on the first selected icon
Definition at line 8993 of file caja-icon-container.c.
References caja_icon_canvas_item_get_editable_text(), caja_icon_canvas_item_get_icon_rectangle(), caja_icon_canvas_item_get_max_text_width(), caja_icon_canvas_item_get_text_rectangle(), caja_icon_canvas_item_set_renaming(), caja_icon_container_is_layout_vertical(), caja_icon_container_update_icon(), CAJA_ICON_LABEL_POSITION_BESIDE, CajaIconContainer::details, EEL_CANVAS_ITEM, eel_canvas_w2c(), EEL_EDITABLE_LABEL, eel_editable_label_new(), eel_editable_label_select_region(), eel_editable_label_set_draw_outline(), eel_editable_label_set_font_description(), eel_editable_label_set_justify(), eel_editable_label_set_line_wrap(), eel_editable_label_set_line_wrap_mode(), eel_editable_label_set_text(), eel_filename_get_rename_region(), CajaIconContainerDetails::font, CajaIconContainerDetails::font_size_table, CajaIconContainerDetails::label_position, NULL, CajaIconContainerDetails::original_text, CajaIconContainerDetails::rename_widget, CajaIconContainerDetails::renaming, RENAMING_ICON, TRUE, EelDRect::x0, EelDRect::x1, EelDRect::y0, EelDRect::y1, and CajaIconContainerDetails::zoom_level.
caja_icon_container_unselect_all()
void caja_icon_container_unselect_all (CajaIconContainer * container)
caja_icon_container_unselect_all: @container: An icon container widget.
Deselect all the icons in @container.
Definition at line 8350 of file caja-icon-container.c.
References SELECTION_CHANGED.
caja_icon_container_unstretch()
void caja_icon_container_unstretch (CajaIconContainer * container)
caja_icon_container_unstretch @container: An icon container widget.
Gets rid of any icon stretching.
Definition at line 8561 of file caja-icon-container.c.
References caja_icon_container_move_icon(), CajaIconContainer::details, FALSE, CajaIconContainerDetails::icons, NULL, and TRUE.
caja_icon_container_update_icon()
void caja_icon_container_update_icon (CajaIconContainer * container, CajaIcon * icon)
Definition at line 7589 of file caja-icon-container.c.
References caja_icon_canvas_item_get_editable_text(), caja_icon_canvas_item_set_attach_points(), caja_icon_canvas_item_set_embedded_text(), caja_icon_canvas_item_set_embedded_text_rect(), caja_icon_canvas_item_set_emblems(), caja_icon_canvas_item_set_image(), caja_icon_info_get_attach_points(), caja_icon_info_get_embedded_rect(), caja_icon_info_get_pixbuf(), caja_icon_info_get_pixbuf_at_size(), CAJA_ICON_MAXIMUM_SIZE, CajaIconContainer::details, CajaIconContainerDetails::drop_target, EEL_CANVAS, EEL_CANVAS_ITEM, eel_canvas_item_set(), FALSE, CajaIconContainerDetails::forced_icon_size, ICON_SIZE_FOR_LARGE_EMBEDDED_TEXT, MAX, MAXIMUM_IMAGE_SIZE, MIN, MINIMUM_IMAGE_SIZE, NULL, and TRUE.
Referenced by caja_icon_container_move_icon(), caja_icon_container_request_update(), caja_icon_container_request_update_all(), and caja_icon_container_start_renaming_selected_item().
caja_icon_container_update_scroll_region()
void caja_icon_container_update_scroll_region (CajaIconContainer * container)
Definition at line 1100 of file caja-icon-container.c.
References CajaIconContainerDetails::bottom_margin, BOUNDS_USAGE_FOR_ENTIRE_ITEM, caja_get_icon_size_for_zoom_level(), caja_icon_container_get_is_fixed_size(), caja_icon_container_is_auto_layout(), caja_icon_container_is_empty(), caja_icon_container_is_layout_rtl(), caja_icon_container_is_layout_vertical(), CONTAINER_PAD_BOTTOM, CONTAINER_PAD_LEFT, CONTAINER_PAD_RIGHT, CONTAINER_PAD_TOP, CajaIconContainer::details, EEL_CANVAS, eel_canvas_set_scroll_region(), FALSE, ICON_PAD_BOTTOM, ICON_PAD_LEFT, ICON_PAD_RIGHT, ICON_PAD_TOP, CajaIconContainerDetails::left_margin, MAX, MIN, CajaIconContainerDetails::reset_scroll_region_trigger, CajaIconContainerDetails::right_margin, CajaIconContainerDetails::top_margin, and CajaIconContainerDetails::zoom_level.
Referenced by caja_icon_container_clear().
caja_icon_container_widget_to_file_operation_position()
void caja_icon_container_widget_to_file_operation_position (CajaIconContainer * container, GdkPoint * position)
Definition at line 9882 of file caja-icon-container.c.
References caja_get_icon_size_for_zoom_level(), CajaIconContainer::details, EEL_CANVAS, eel_canvas_window_to_world(), int(), NULL, and CajaIconContainerDetails::zoom_level.
caja_self_check_icon_container()
void caja_self_check_icon_container (void)
Definition at line 10097 of file caja-icon-container.c.
References EEL_CHECK_STRING_RESULT.
G_DEFINE_TYPE()
G_DEFINE_TYPE (CajaIconContainer , caja_icon_container , EEL_TYPE_CANVAS)
References EEL_TYPE_CANVAS.
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (CajaIconContainerAccessible , caja_icon_container_accessible , eel_canvas_accessible_get_type() , G_IMPLEMENT_INTERFACE(ATK_TYPE_ACTION, caja_icon_container_accessible_action_interface_init) G_IMPLEMENT_INTERFACE(ATK_TYPE_SELECTION, caja_icon_container_accessible_selection_interface_init))
References eel_canvas_accessible_get_type().