MATE Desktop Environment: caja-application.c File Reference
caja-application.c File Reference
#include <config.h>
#include <fcntl.h>
#include <string.h>
#include <unistd.h>
#include <libxml/parser.h>
#include <libxml/xmlsave.h>
#include <glib/gstdio.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
#include <libnotify/notify.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <libmate-desktop/mate-bg.h>
#include <eel/eel-gtk-extensions.h>
#include <eel/eel-gtk-macros.h>
#include <eel/eel-stock-dialogs.h>
#include <libcaja-private/caja-debug-log.h>
#include <libcaja-private/caja-file-utilities.h>
#include <libcaja-private/caja-global-preferences.h>
#include <libcaja-private/caja-lib-self-check-functions.h>
#include <libcaja-private/caja-extensions.h>
#include <libcaja-private/caja-module.h>
#include <libcaja-private/caja-desktop-link-monitor.h>
#include <libcaja-private/caja-directory-private.h>
#include <libcaja-private/caja-signaller.h>
#include <libcaja-extension/caja-menu-provider.h>
#include <libcaja-private/caja-autorun.h>
#include "file-manager/fm-desktop-icon-view.h"
#include "file-manager/fm-icon-view.h"
#include "file-manager/fm-list-view.h"
#include "file-manager/fm-tree-view.h"
#include "file-manager/fm-widget-view.h"
#include "caja-application.h"
#include "caja-information-panel.h"
#include "caja-history-sidebar.h"
#include "caja-places-sidebar.h"
#include "caja-self-check-functions.h"
#include "caja-notes-viewer.h"
#include "caja-emblem-sidebar.h"
#include "caja-bookmarks-sidebar.h"
#include "caja-image-properties-page.h"
#include "caja-desktop-window.h"
#include "caja-spatial-window.h"
#include "caja-navigation-window.h"
#include "caja-window-slot.h"
#include "caja-navigation-window-slot.h"
#include "caja-window-bookmarks.h"
#include "libcaja-private/caja-file-operations.h"
#include "caja-window-private.h"
#include "caja-window-manage-views.h"
#include "caja-freedesktop-dbus.h"
Macros
#define MATE_DESKTOP_USE_UNSTABLE_API
#define APPLICATION_WINDOW_MIN_WIDTH 300
#define APPLICATION_WINDOW_MIN_HEIGHT 100
#define CAJA_ACCEL_MAP_SAVE_DELAY 30
Functions
void caja_application_quit (CajaApplication *self)
G_DEFINE_TYPE_WITH_PRIVATE (CajaApplication, caja_application, GTK_TYPE_APPLICATION)
void caja_application_open_location (CajaApplication *application, GFile *location, GFile *selection, const char *startup_id, const gboolean open_in_tabs)
void caja_application_close_all_navigation_windows (CajaApplication *self)
void caja_application_close_parent_windows (CajaSpatialWindow *window)
void caja_application_close_all_spatial_windows (void)
CajaWindow * caja_application_get_spatial_window (CajaApplication *application, CajaWindow *requesting_window, const char *startup_id, GFile *location, GdkScreen *screen, gboolean *existing)
CajaWindow * caja_application_create_navigation_window (CajaApplication *application, GdkScreen *screen)
CajaApplication * caja_application_new (void)
Macro Definition Documentation
APPLICATION_WINDOW_MIN_HEIGHT
#define APPLICATION_WINDOW_MIN_HEIGHT 100
Definition at line 95 of file caja-application.c.
APPLICATION_WINDOW_MIN_WIDTH
#define APPLICATION_WINDOW_MIN_WIDTH 300
Definition at line 94 of file caja-application.c.
CAJA_ACCEL_MAP_SAVE_DELAY
#define CAJA_ACCEL_MAP_SAVE_DELAY 30
Definition at line 97 of file caja-application.c.
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 45 of file caja-application.c.
Function Documentation
caja_application_close_all_navigation_windows()
void caja_application_close_all_navigation_windows (CajaApplication * self)
Definition at line 759 of file caja-application.c.
References CAJA_IS_NAVIGATION_WINDOW, CAJA_WINDOW, caja_window_close(), list_copy(), and NULL.
caja_application_close_all_spatial_windows()
void caja_application_close_all_spatial_windows (void)
Definition at line 892 of file caja-application.c.
References CAJA_IS_SPATIAL_WINDOW, CAJA_WINDOW, caja_window_close(), list_copy(), and NULL.
caja_application_close_parent_windows()
void caja_application_close_parent_windows (CajaSpatialWindow * window)
Definition at line 873 of file caja-application.c.
References CAJA_IS_SPATIAL_WINDOW, CAJA_WINDOW, and caja_window_close().
caja_application_create_navigation_window()
CajaWindow * caja_application_create_navigation_window (CajaApplication * application, GdkScreen * screen)
Definition at line 1040 of file caja-application.c.
References caja_debug_log(), CAJA_DEBUG_LOG_DOMAIN_USER, CAJA_IS_APPLICATION, CAJA_NAVIGATION_WINDOW_MIN_HEIGHT, CAJA_NAVIGATION_WINDOW_MIN_WIDTH, CAJA_TYPE_NAVIGATION_WINDOW, caja_window_state, CAJA_WINDOW_STATE_GEOMETRY, CAJA_WINDOW_STATE_MAXIMIZED, eel_gtk_window_set_initial_geometry_from_string(), FALSE, NULL, and TRUE.
Referenced by caja_application_open_location(), caja_connect_server_dialog_display_location_async(), caja_window_new_window(), and caja_window_slot_open_location_full().
caja_application_get_spatial_window()
CajaWindow * caja_application_get_spatial_window (CajaApplication * application, CajaWindow * requesting_window, const char * startup_id, GFile * location, GdkScreen * screen, gboolean * existing)
Definition at line 974 of file caja-application.c.
References caja_debug_log(), CAJA_DEBUG_LOG_DOMAIN_USER, CAJA_IS_APPLICATION, CAJA_TYPE_SPATIAL_WINDOW, CAJA_WINDOW, FALSE, NULL, and TRUE.
Referenced by caja_connect_server_dialog_display_location_async(), and caja_window_slot_open_location_full().
caja_application_new()
CajaApplication * caja_application_new (void)
Definition at line 2380 of file caja-application.c.
References CAJA_TYPE_APPLICATION, NULL, and TRUE.
Referenced by main().
caja_application_open_location()
void caja_application_open_location (CajaApplication * application, GFile * location, GFile * selection, const char * startup_id, const gboolean open_in_tabs)
Definition at line 407 of file caja-application.c.
References caja_application_create_navigation_window(), caja_file_list_free(), caja_window_get_active_slot(), CAJA_WINDOW_OPEN_FLAG_NEW_WINDOW, caja_window_slot_open_location_full(), and NULL.
caja_application_quit()
void caja_application_quit (CajaApplication * self)
Definition at line 432 of file caja-application.c.
References NULL.
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (CajaApplication , caja_application , GTK_TYPE_APPLICATION)