MATE Desktop Environment: caja-dnd.h File Reference
caja-dnd.h File Reference
#include <gtk/gtk.h>
#include "caja-window-slot-info.h"
Classes
struct CajaDragSelectionItem
struct CajaDragInfo
struct CajaDragSlotProxyInfo
Macros
#define CAJA_ICON_DND_MATE_ICON_LIST_TYPE "x-special/mate-icon-list"
#define CAJA_ICON_DND_URI_LIST_TYPE "text/uri-list"
#define CAJA_ICON_DND_NETSCAPE_URL_TYPE "_NETSCAPE_URL"
#define CAJA_ICON_DND_COLOR_TYPE "application/x-color"
#define CAJA_ICON_DND_BGIMAGE_TYPE "property/bgimage"
#define CAJA_ICON_DND_KEYWORD_TYPE "property/keyword"
#define CAJA_ICON_DND_RESET_BACKGROUND_TYPE "x-special/mate-reset-background"
#define CAJA_ICON_DND_ROOTWINDOW_DROP_TYPE "application/x-rootwindow-drop"
#define CAJA_ICON_DND_XDNDDIRECTSAVE_TYPE "XdndDirectSave0" /* XDS Protocol Type */
#define CAJA_ICON_DND_RAW_TYPE "application/octet-stream"
Typedefs
typedef void(* CajaDragEachSelectedItemDataGet) (const char *url, int x, int y, int w, int h, gpointer data)
typedef void(* CajaDragEachSelectedItemIterator) (CajaDragEachSelectedItemDataGet iteratee, gpointer iterator_context, gpointer data)
Enumerations
enum CajaIconDndTargetType {
CAJA_ICON_DND_MATE_ICON_LIST , CAJA_ICON_DND_URI_LIST , CAJA_ICON_DND_NETSCAPE_URL , CAJA_ICON_DND_COLOR ,
CAJA_ICON_DND_BGIMAGE , CAJA_ICON_DND_KEYWORD , CAJA_ICON_DND_TEXT , CAJA_ICON_DND_RESET_BACKGROUND ,
CAJA_ICON_DND_XDNDDIRECTSAVE , CAJA_ICON_DND_RAW , CAJA_ICON_DND_ROOTWINDOW_DROP
}
enum CajaDndAction { CAJA_DND_ACTION_FIRST = GDK_ACTION_ASK << 1 , CAJA_DND_ACTION_SET_AS_BACKGROUND = CAJA_DND_ACTION_FIRST << 0 , CAJA_DND_ACTION_SET_AS_FOLDER_BACKGROUND = CAJA_DND_ACTION_FIRST << 1 , CAJA_DND_ACTION_SET_AS_GLOBAL_BACKGROUND = CAJA_DND_ACTION_FIRST << 2 }
Functions
void caja_drag_init (CajaDragInfo *drag_info, const GtkTargetEntry *drag_types, int drag_type_count, gboolean add_text_targets)
void caja_drag_finalize (CajaDragInfo *drag_info)
CajaDragSelectionItem * caja_drag_selection_item_new (void)
void caja_drag_destroy_selection_list (GList *selection_list)
GList * caja_drag_build_selection_list (GtkSelectionData *data)
GList * caja_drag_uri_list_from_selection_list (const GList *selection_list)
GList * caja_drag_uri_list_from_array (const char **uris)
gboolean caja_drag_items_local (const char *target_uri, const GList *selection_list)
gboolean caja_drag_uris_local (const char *target_uri, const GList *source_uri_list)
gboolean caja_drag_items_on_desktop (const GList *selection_list)
void caja_drag_default_drop_action_for_icons (GdkDragContext *context, const char *target_uri, const GList *items, int *action)
GdkDragAction caja_drag_default_drop_action_for_netscape_url (GdkDragContext *context)
GdkDragAction caja_drag_default_drop_action_for_uri_list (GdkDragContext *context, const char *target_uri_string)
gboolean caja_drag_drag_data_get (GtkWidget *widget, GdkDragContext *context, GtkSelectionData *selection_data, guint info, guint32 time, gpointer container_context, CajaDragEachSelectedItemIterator each_selected_item_iterator)
int caja_drag_modifier_based_action (int default_action, int non_default_action)
GdkDragAction caja_drag_drop_action_ask (GtkWidget *widget, GdkDragAction possible_actions)
GdkDragAction caja_drag_drop_background_ask (GtkWidget *widget, GdkDragAction possible_actions)
gboolean caja_drag_autoscroll_in_scroll_region (GtkWidget *widget)
void caja_drag_autoscroll_calculate_delta (GtkWidget *widget, float *x_scroll_delta, float *y_scroll_delta)
void caja_drag_autoscroll_start (CajaDragInfo *drag_info, GtkWidget *widget, GSourceFunc callback, gpointer user_data)
void caja_drag_autoscroll_stop (CajaDragInfo *drag_info)
gboolean caja_drag_selection_includes_special_link (GList *selection_list)
void caja_drag_slot_proxy_init (GtkWidget *widget, CajaDragSlotProxyInfo *drag_info)
Macro Definition Documentation
CAJA_ICON_DND_BGIMAGE_TYPE
#define CAJA_ICON_DND_BGIMAGE_TYPE "property/bgimage"
Definition at line 39 of file caja-dnd.h.
CAJA_ICON_DND_COLOR_TYPE
#define CAJA_ICON_DND_COLOR_TYPE "application/x-color"
Definition at line 38 of file caja-dnd.h.
CAJA_ICON_DND_KEYWORD_TYPE
#define CAJA_ICON_DND_KEYWORD_TYPE "property/keyword"
Definition at line 40 of file caja-dnd.h.
CAJA_ICON_DND_MATE_ICON_LIST_TYPE
#define CAJA_ICON_DND_MATE_ICON_LIST_TYPE "x-special/mate-icon-list"
Definition at line 35 of file caja-dnd.h.
Referenced by caja_drag_slot_proxy_init(), and G_DEFINE_TYPE_WITH_CODE().
CAJA_ICON_DND_NETSCAPE_URL_TYPE
#define CAJA_ICON_DND_NETSCAPE_URL_TYPE "_NETSCAPE_URL"
Definition at line 37 of file caja-dnd.h.
Referenced by caja_drag_slot_proxy_init().
CAJA_ICON_DND_RAW_TYPE
#define CAJA_ICON_DND_RAW_TYPE "application/octet-stream"
Definition at line 44 of file caja-dnd.h.
CAJA_ICON_DND_RESET_BACKGROUND_TYPE
#define CAJA_ICON_DND_RESET_BACKGROUND_TYPE "x-special/mate-reset-background"
Definition at line 41 of file caja-dnd.h.
CAJA_ICON_DND_ROOTWINDOW_DROP_TYPE
#define CAJA_ICON_DND_ROOTWINDOW_DROP_TYPE "application/x-rootwindow-drop"
Definition at line 42 of file caja-dnd.h.
CAJA_ICON_DND_URI_LIST_TYPE
#define CAJA_ICON_DND_URI_LIST_TYPE "text/uri-list"
Definition at line 36 of file caja-dnd.h.
CAJA_ICON_DND_XDNDDIRECTSAVE_TYPE
#define CAJA_ICON_DND_XDNDDIRECTSAVE_TYPE "XdndDirectSave0" /* XDS Protocol Type */
Definition at line 43 of file caja-dnd.h.
Typedef Documentation
CajaDragEachSelectedItemDataGet
typedef void(* CajaDragEachSelectedItemDataGet) (const char *url, int x, int y, int w, int h, gpointer data)
Definition at line 136 of file caja-dnd.h.
CajaDragEachSelectedItemIterator
typedef void(* CajaDragEachSelectedItemIterator) (CajaDragEachSelectedItemDataGet iteratee, gpointer iterator_context, gpointer data)
Definition at line 139 of file caja-dnd.h.
Enumeration Type Documentation
CajaDndAction
enum CajaDndAction
Enumerator
CAJA_DND_ACTION_FIRST
CAJA_DND_ACTION_SET_AS_BACKGROUND
CAJA_DND_ACTION_SET_AS_FOLDER_BACKGROUND
CAJA_DND_ACTION_SET_AS_GLOBAL_BACKGROUND
Definition at line 71 of file caja-dnd.h.
CajaIconDndTargetType
enum CajaIconDndTargetType
Enumerator
CAJA_ICON_DND_MATE_ICON_LIST
CAJA_ICON_DND_URI_LIST
CAJA_ICON_DND_NETSCAPE_URL
CAJA_ICON_DND_COLOR
CAJA_ICON_DND_BGIMAGE
CAJA_ICON_DND_KEYWORD
CAJA_ICON_DND_TEXT
CAJA_ICON_DND_RESET_BACKGROUND
CAJA_ICON_DND_XDNDDIRECTSAVE
CAJA_ICON_DND_RAW
CAJA_ICON_DND_ROOTWINDOW_DROP
Definition at line 56 of file caja-dnd.h.
Function Documentation
caja_drag_autoscroll_calculate_delta()
void caja_drag_autoscroll_calculate_delta (GtkWidget * widget, float * x_scroll_delta, float * y_scroll_delta)
Definition at line 932 of file caja-dnd.c.
References AUTO_SCROLL_MARGIN, MAX_AUTOSCROLL_DELTA, MIN_AUTOSCROLL_DELTA, and NULL.
Referenced by caja_drag_autoscroll_in_scroll_region().
caja_drag_autoscroll_in_scroll_region()
gboolean caja_drag_autoscroll_in_scroll_region (GtkWidget * widget)
Definition at line 922 of file caja-dnd.c.
References caja_drag_autoscroll_calculate_delta().
Referenced by caja_drag_autoscroll_start().
caja_drag_autoscroll_start()
void caja_drag_autoscroll_start (CajaDragInfo * drag_info, GtkWidget * widget, GSourceFunc callback, gpointer user_data)
Definition at line 1019 of file caja-dnd.c.
References CajaDragInfo::auto_scroll_timeout_id, AUTOSCROLL_INITIAL_DELAY, AUTOSCROLL_TIMEOUT_INTERVAL, caja_drag_autoscroll_in_scroll_region(), CajaDragInfo::start_auto_scroll_in, TRUE, user_data, and CajaDragInfo::waiting_to_autoscroll.
caja_drag_autoscroll_stop()
void caja_drag_autoscroll_stop (CajaDragInfo * drag_info)
Definition at line 1049 of file caja-dnd.c.
References CajaDragInfo::auto_scroll_timeout_id.
caja_drag_build_selection_list()
GList * caja_drag_build_selection_list (GtkSelectionData * data)
Definition at line 166 of file caja-dnd.c.
References caja_drag_selection_item_new(), data, item, memcpy, and NULL.
caja_drag_default_drop_action_for_icons()
void caja_drag_default_drop_action_for_icons (GdkDragContext * context, const char * target_uri, const GList * items, int * action)
Definition at line 436 of file caja-dnd.c.
References action, caja_file_get(), caja_file_get_existing_by_uri(), caja_file_is_archive(), caja_file_is_launcher(), caja_file_unref(), caja_get_desktop_location(), eel_uri_is_desktop(), eel_uri_is_trash(), FALSE, NULL, and target_file.
caja_drag_default_drop_action_for_netscape_url()
GdkDragAction caja_drag_default_drop_action_for_netscape_url (GdkDragContext * context)
Definition at line 349 of file caja-dnd.c.
caja_drag_default_drop_action_for_uri_list()
GdkDragAction caja_drag_default_drop_action_for_uri_list (GdkDragContext * context, const char * target_uri_string)
Definition at line 585 of file caja-dnd.c.
References eel_uri_is_trash().
caja_drag_destroy_selection_list()
void caja_drag_destroy_selection_list (GList * selection_list)
Definition at line 111 of file caja-dnd.c.
References NULL.
Referenced by caja_drag_finalize().
caja_drag_drag_data_get()
gboolean caja_drag_drag_data_get (GtkWidget * widget, GdkDragContext * context, GtkSelectionData * selection_data, guint info, guint32 time, gpointer container_context, CajaDragEachSelectedItemIterator each_selected_item_iterator)
Definition at line 712 of file caja-dnd.c.
References CAJA_ICON_DND_MATE_ICON_LIST, CAJA_ICON_DND_TEXT, CAJA_ICON_DND_URI_LIST, FALSE, NULL, and TRUE.
caja_drag_drop_action_ask()
GdkDragAction caja_drag_drop_action_ask (GtkWidget * widget, GdkDragAction possible_actions)
Definition at line 806 of file caja-dnd.c.
References _, CAJA_DND_ACTION_SET_AS_BACKGROUND, eel_gtk_menu_append_separator(), FALSE, and NULL.
Referenced by fm_directory_view_handle_uri_list_drop().
caja_drag_drop_background_ask()
GdkDragAction caja_drag_drop_background_ask (GtkWidget * widget, GdkDragAction possible_actions)
Definition at line 869 of file caja-dnd.c.
References _, CAJA_DND_ACTION_SET_AS_FOLDER_BACKGROUND, CAJA_DND_ACTION_SET_AS_GLOBAL_BACKGROUND, eel_gtk_menu_append_separator(), FALSE, and NULL.
caja_drag_finalize()
void caja_drag_finalize (CajaDragInfo * drag_info)
Definition at line 87 of file caja-dnd.c.
References caja_drag_destroy_selection_list(), CajaDragInfo::selection_list, and CajaDragInfo::target_list.
Referenced by caja_icon_dnd_fini().
caja_drag_init()
void caja_drag_init (CajaDragInfo * drag_info, const GtkTargetEntry * drag_types, int drag_type_count, gboolean add_text_targets)
Definition at line 68 of file caja-dnd.c.
References CAJA_ICON_DND_TEXT, CajaDragInfo::drop_occured, FALSE, CajaDragInfo::need_to_destroy, and CajaDragInfo::target_list.
Referenced by caja_icon_dnd_init().
caja_drag_items_local()
gboolean caja_drag_items_local (const char * target_uri, const GList * selection_list)
Definition at line 301 of file caja-dnd.c.
caja_drag_items_on_desktop()
gboolean caja_drag_items_on_desktop (const GList * selection_list)
Definition at line 312 of file caja-dnd.c.
References caja_get_desktop_location(), eel_uri_is_desktop(), FALSE, item, and TRUE.
caja_drag_modifier_based_action()
int caja_drag_modifier_based_action (int default_action, int non_default_action)
References user_data.
caja_drag_selection_includes_special_link()
gboolean caja_drag_selection_includes_special_link (GList * selection_list)
Definition at line 1059 of file caja-dnd.c.
References eel_uri_is_desktop(), FALSE, NULL, and TRUE.
caja_drag_selection_item_new()
CajaDragSelectionItem * caja_drag_selection_item_new (void)
Definition at line 98 of file caja-dnd.c.
Referenced by caja_drag_build_selection_list().
caja_drag_slot_proxy_init()
void caja_drag_slot_proxy_init (GtkWidget * widget, CajaDragSlotProxyInfo * drag_info)
Definition at line 1387 of file caja-dnd.c.
References CAJA_ICON_DND_MATE_ICON_LIST, CAJA_ICON_DND_MATE_ICON_LIST_TYPE, CAJA_ICON_DND_NETSCAPE_URL, CAJA_ICON_DND_NETSCAPE_URL_TYPE, CAJA_ICON_DND_URI_LIST, and NULL.
caja_drag_uri_list_from_array()
GList * caja_drag_uri_list_from_array (const char ** uris)
Definition at line 145 of file caja-dnd.c.
References NULL.
caja_drag_uri_list_from_selection_list()
GList * caja_drag_uri_list_from_selection_list (const GList * selection_list)
Definition at line 125 of file caja-dnd.c.
References NULL, and CajaDragSelectionItem::uri.
caja_drag_uris_local()
gboolean caja_drag_uris_local (const char * target_uri, const GList * source_uri_list)
Definition at line 291 of file caja-dnd.c.