MATE Desktop Environment: caja-window-slot.h File Reference
caja-window-slot.h File Reference
#include "caja-window-pane.h"
#include "caja-query-editor.h"
#include <glib/gi18n.h>
Classes
struct CajaWindowSlotClass
struct CajaWindowSlot
Macros
#define CAJA_TYPE_WINDOW_SLOT (caja_window_slot_get_type())
#define CAJA_WINDOW_SLOT_CLASS(k)
#define CAJA_WINDOW_SLOT(obj)
#define CAJA_IS_WINDOW_SLOT(obj)
#define CAJA_IS_WINDOW_SLOT_CLASS(k)
#define CAJA_WINDOW_SLOT_GET_CLASS(o)
#define caja_window_slot_go_to(slot, location, new_tab)
#define caja_window_slot_go_to_full(slot, location, new_tab, callback, user_data)
#define caja_window_slot_go_to_with_selection(slot, location, new_selection)
Enumerations
enum CajaLocationChangeType {
CAJA_LOCATION_CHANGE_STANDARD , CAJA_LOCATION_CHANGE_BACK , CAJA_LOCATION_CHANGE_FORWARD , CAJA_LOCATION_CHANGE_RELOAD ,
CAJA_LOCATION_CHANGE_REDIRECT , CAJA_LOCATION_CHANGE_FALLBACK
}
Functions
GType caja_window_slot_get_type (void)
char * caja_window_slot_get_title (CajaWindowSlot *slot)
void caja_window_slot_update_title (CajaWindowSlot *slot)
void caja_window_slot_update_icon (CajaWindowSlot *slot)
void caja_window_slot_update_query_editor (CajaWindowSlot *slot)
GFile * caja_window_slot_get_location (CajaWindowSlot *slot)
char * caja_window_slot_get_location_uri (CajaWindowSlot *slot)
void caja_window_slot_close (CajaWindowSlot *slot)
void caja_window_slot_reload (CajaWindowSlot *slot)
void caja_window_slot_open_location (CajaWindowSlot *slot, GFile *location, gboolean close_behind)
void caja_window_slot_open_location_with_selection (CajaWindowSlot *slot, GFile *location, GList *selection, gboolean close_behind)
void caja_window_slot_open_location_full (CajaWindowSlot *slot, GFile *location, CajaWindowOpenMode mode, CajaWindowOpenFlags flags, GList *new_selection, CajaWindowGoToCallback callback, gpointer user_data)
void caja_window_slot_stop_loading (CajaWindowSlot *slot)
void caja_window_slot_set_content_view (CajaWindowSlot *slot, const char *id)
const char * caja_window_slot_get_content_view_id (CajaWindowSlot *slot)
gboolean caja_window_slot_content_view_matches_iid (CajaWindowSlot *slot, const char *iid)
void caja_window_slot_connect_content_view (CajaWindowSlot *slot, CajaView *view)
void caja_window_slot_disconnect_content_view (CajaWindowSlot *slot, CajaView *view)
void caja_window_slot_go_home (CajaWindowSlot *slot, gboolean new_tab)
void caja_window_slot_go_up (CajaWindowSlot *slot, gboolean close_behind)
void caja_window_slot_set_content_view_widget (CajaWindowSlot *slot, CajaView *content_view)
void caja_window_slot_set_viewed_file (CajaWindowSlot *slot, CajaFile *file)
void caja_window_slot_set_allow_stop (CajaWindowSlot *slot, gboolean allow_stop)
void caja_window_slot_set_status (CajaWindowSlot *slot, const char *status)
void caja_window_slot_add_extra_location_widget (CajaWindowSlot *slot, GtkWidget *widget)
void caja_window_slot_remove_extra_location_widgets (CajaWindowSlot *slot)
void caja_window_slot_add_current_location_to_history_list (CajaWindowSlot *slot)
void caja_window_slot_is_in_active_pane (CajaWindowSlot *slot, gboolean is_active)
Macro Definition Documentation
CAJA_IS_WINDOW_SLOT
#define CAJA_IS_WINDOW_SLOT (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_WINDOW_SLOT))
Definition at line 35 of file caja-window-slot.h.
Referenced by caja_notebook_add_tab(), caja_notebook_sync_loading(), caja_notebook_sync_tab_label(), caja_window_close_slot(), caja_window_new_window(), caja_window_open_slot(), caja_window_report_location_change(), caja_window_set_active_slot(), caja_window_slot_get_location_uri(), caja_window_slot_get_title(), caja_window_slot_go_home(), caja_window_slot_reload(), caja_window_slot_set_allow_stop(), and caja_window_slot_set_status().
CAJA_IS_WINDOW_SLOT_CLASS
#define CAJA_IS_WINDOW_SLOT_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), CAJA_TYPE_WINDOW_SLOT))
Definition at line 36 of file caja-window-slot.h.
CAJA_TYPE_WINDOW_SLOT
#define CAJA_TYPE_WINDOW_SLOT (caja_window_slot_get_type())
Definition at line 32 of file caja-window-slot.h.
Referenced by G_DEFINE_TYPE().
CAJA_WINDOW_SLOT
#define CAJA_WINDOW_SLOT (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_WINDOW_SLOT, CajaWindowSlot))
Definition at line 34 of file caja-window-slot.h.
Referenced by caja_forget_history(), caja_navigation_window_slot_should_close_with_mount(), caja_window_pane_get_slot_for_content_box(), caja_window_pane_slot_close(), and G_DEFINE_TYPE().
CAJA_WINDOW_SLOT_CLASS
#define CAJA_WINDOW_SLOT_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST((k), CAJA_TYPE_WINDOW_SLOT, CajaWindowSlotClass))
Definition at line 33 of file caja-window-slot.h.
Referenced by caja_window_slot_update_query_editor().
CAJA_WINDOW_SLOT_GET_CLASS
#define CAJA_WINDOW_SLOT_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), CAJA_TYPE_WINDOW_SLOT, CajaWindowSlotClass))
Definition at line 37 of file caja-window-slot.h.
caja_window_slot_go_to
#define caja_window_slot_go_to (slot, location, new_tab)
Value:
caja_window_slot_open_location_full(slot, location, CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, \
                    (new_tab ? CAJA_WINDOW_OPEN_FLAG_NEW_TAB : 0), \
                    NULL, NULL, NULL)
Definition at line 160 of file caja-window-slot.h.
Referenced by caja_navigation_window_split_view_on(), caja_window_go_to(), caja_window_go_to_tab(), and caja_window_new_tab().
caja_window_slot_go_to_full
#define caja_window_slot_go_to_full (slot, location, new_tab, callback, user_data)
Value:
caja_window_slot_open_location_full(slot, location, CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, \
                    (new_tab ? CAJA_WINDOW_OPEN_FLAG_NEW_TAB : 0), \
                    NULL, callback, user_data)
Definition at line 165 of file caja-window-slot.h.
Referenced by caja_window_go_to_full().
caja_window_slot_go_to_with_selection
#define caja_window_slot_go_to_with_selection (slot, location, new_selection)
Value:
caja_window_slot_open_location_with_selection(slot, location, new_selection, FALSE)
Definition at line 170 of file caja-window-slot.h.
Referenced by caja_window_go_to_with_selection().
Enumeration Type Documentation
CajaLocationChangeType
enum CajaLocationChangeType
Enumerator
CAJA_LOCATION_CHANGE_STANDARD
CAJA_LOCATION_CHANGE_BACK
CAJA_LOCATION_CHANGE_FORWARD
CAJA_LOCATION_CHANGE_RELOAD
CAJA_LOCATION_CHANGE_REDIRECT
CAJA_LOCATION_CHANGE_FALLBACK
Definition at line 39 of file caja-window-slot.h.
Function Documentation
caja_window_slot_add_current_location_to_history_list()
void caja_window_slot_add_current_location_to_history_list (CajaWindowSlot * slot)
Definition at line 590 of file caja-window-slot.c.
References caja_add_bookmark_to_history_list(), CAJA_IS_DESKTOP_WINDOW, caja_send_history_list_changed(), CajaWindowSlot::current_location_bookmark, NULL, CajaWindowSlot::pane, and _CajaWindowPane::window.
Referenced by caja_forget_history().
caja_window_slot_add_extra_location_widget()
void caja_window_slot_add_extra_location_widget (CajaWindowSlot * slot, GtkWidget * widget)
Definition at line 581 of file caja-window-slot.c.
References CajaWindowSlot::extra_location_frame, CajaWindowSlot::extra_location_widgets, and TRUE.
caja_window_slot_close()
void caja_window_slot_close (CajaWindowSlot * slot)
Definition at line 1047 of file caja-window.c.
References caja_window_pane_slot_close(), and CajaWindowSlot::pane.
caja_window_slot_connect_content_view()
void caja_window_slot_connect_content_view (CajaWindowSlot * slot, CajaView * view)
Definition at line 445 of file caja-window-slot.c.
References caja_window_connect_content_view(), caja_window_get_active_slot(), NULL, CajaWindowSlot::pane, and _CajaWindowPane::window.
Referenced by caja_window_set_active_slot(), and caja_window_slot_set_content_view_widget().
caja_window_slot_content_view_matches_iid()
gboolean caja_window_slot_content_view_matches_iid (CajaWindowSlot * slot, const char * iid)
Definition at line 845 of file caja-window-manage-views.c.
References caja_view_get_view_id(), CajaWindowSlot::content_view, FALSE, and NULL.
Referenced by caja_window_slot_set_content_view().
caja_window_slot_disconnect_content_view()
void caja_window_slot_disconnect_content_view (CajaWindowSlot * slot, CajaView * view)
Definition at line 458 of file caja-window-slot.c.
References caja_window_disconnect_content_view(), NULL, CajaWindowSlot::pane, and _CajaWindowPane::window.
Referenced by caja_window_manage_views_close_slot(), caja_window_report_view_failed(), caja_window_set_active_slot(), and caja_window_slot_set_content_view_widget().
caja_window_slot_get_content_view_id()
const char * caja_window_slot_get_content_view_id (CajaWindowSlot * slot)
Definition at line 835 of file caja-window-manage-views.c.
References caja_view_get_view_id(), CajaWindowSlot::content_view, and NULL.
caja_window_slot_get_location()
GFile * caja_window_slot_get_location (CajaWindowSlot * slot)
Definition at line 233 of file caja-window-slot.c.
References CAJA_IS_WINDOW, CajaWindowSlot::location, NULL, CajaWindowSlot::pane, and _CajaWindowPane::window.
Referenced by caja_navigation_window_back_or_forward(), caja_navigation_window_split_view_on(), caja_navigation_window_update_split_view_actions_sensitivity(), caja_window_new_tab(), caja_window_new_window(), and caja_window_slot_open_location_full().
caja_window_slot_get_location_uri()
char * caja_window_slot_get_location_uri (CajaWindowSlot * slot)
Definition at line 246 of file caja-window-slot.c.
References CAJA_IS_WINDOW_SLOT, CajaWindowSlot::location, and NULL.
Referenced by caja_window_slot_open_location_full(), and caja_window_slot_set_content_view().
caja_window_slot_get_title()
char * caja_window_slot_get_title (CajaWindowSlot * slot)
Definition at line 267 of file caja-window-slot.c.
References caja_compute_title_for_location(), CAJA_IS_WINDOW_SLOT, caja_view_get_title(), CajaWindowSlot::content_view, CajaWindowSlot::location, CajaWindowSlot::new_content_view, and NULL.
Referenced by caja_window_slot_update_title().
caja_window_slot_get_type()
GType caja_window_slot_get_type (void)
References user_data.
caja_window_slot_go_home()
void caja_window_slot_go_home (CajaWindowSlot * slot, gboolean new_tab)
Definition at line 757 of file caja-window-manage-views.c.
References CAJA_IS_WINDOW_SLOT, CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, CAJA_WINDOW_OPEN_FLAG_NEW_TAB, caja_window_slot_open_location_full(), and NULL.
Referenced by caja_window_go_home().
caja_window_slot_go_up()
void caja_window_slot_go_up (CajaWindowSlot * slot, gboolean close_behind)
caja_window_slot_is_in_active_pane()
void caja_window_slot_is_in_active_pane (CajaWindowSlot * slot, gboolean is_active)
Definition at line 423 of file caja-window-slot.c.
References caja_view_set_is_active(), CajaWindowSlot::content_view, CajaWindowSlot::new_content_view, and NULL.
Referenced by caja_window_pane_set_active().
caja_window_slot_open_location()
void caja_window_slot_open_location (CajaWindowSlot * slot, GFile * location, gboolean close_behind)
Definition at line 721 of file caja-window-manage-views.c.
References CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, CAJA_WINDOW_OPEN_FLAG_CLOSE_BEHIND, caja_window_slot_open_location_full(), and NULL.
caja_window_slot_open_location_full()
void caja_window_slot_open_location_full (CajaWindowSlot * slot, GFile * location, CajaWindowOpenMode mode, CajaWindowOpenFlags flags, GList * new_selection, CajaWindowGoToCallback callback, gpointer user_data)
Definition at line 514 of file caja-window-manage-views.c.
References _CajaWindowPrivate::active_pane, _CajaWindowPane::active_slot, caja_application_create_navigation_window(), caja_application_get_spatial_window(), caja_debug_log(), CAJA_DEBUG_LOG_DOMAIN_USER, CAJA_DESKTOP_WINDOW, caja_desktop_window_loaded(), CAJA_IS_DESKTOP_WINDOW, CAJA_IS_NAVIGATION_WINDOW, CAJA_IS_SPATIAL_WINDOW, CAJA_LOCATION_CHANGE_RELOAD, CAJA_LOCATION_CHANGE_STANDARD, CAJA_NEW_TAB_POSITION_END, caja_preferences, CAJA_PREFERENCES_ALWAYS_USE_BROWSER, CAJA_PREFERENCES_NEW_TAB_POSITION, caja_view_set_selection(), caja_window_close(), CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, CAJA_WINDOW_OPEN_FLAG_CLOSE_BEHIND, CAJA_WINDOW_OPEN_FLAG_NEW_TAB, CAJA_WINDOW_OPEN_FLAG_NEW_WINDOW, CAJA_WINDOW_OPEN_IN_NAVIGATION, caja_window_open_slot(), CAJA_WINDOW_OPEN_SLOT_APPEND, caja_window_slot_get_location(), caja_window_slot_get_location_uri(), CajaWindowSlot::content_view, CajaWindow::details, EEL_DESKTOP_URI, FALSE, CajaWindowSlot::location, NULL, CajaWindowSlot::pane, _CajaWindowPrivate::panes, CajaWindowSlot::pending_location, TRUE, user_data, and _CajaWindowPane::window.
Referenced by caja_application_open_location(), caja_navigation_window_back_or_forward(), caja_window_go_up(), caja_window_new_window(), caja_window_reload(), caja_window_slot_go_home(), caja_window_slot_open_location(), and caja_window_slot_open_location_with_selection().
caja_window_slot_open_location_with_selection()
void caja_window_slot_open_location_with_selection (CajaWindowSlot * slot, GFile * location, GList * selection, gboolean close_behind)
Definition at line 739 of file caja-window-manage-views.c.
References CAJA_WINDOW_OPEN_ACCORDING_TO_MODE, CAJA_WINDOW_OPEN_FLAG_CLOSE_BEHIND, caja_window_slot_open_location_full(), and NULL.
caja_window_slot_reload()
void caja_window_slot_reload (CajaWindowSlot * slot)
Definition at line 2368 of file caja-window-manage-views.c.
References CAJA_IS_WINDOW_SLOT, CAJA_LOCATION_CHANGE_RELOAD, caja_view_get_first_visible_file(), caja_view_get_selection(), CajaWindowSlot::content_view, CajaWindowSlot::location, and NULL.
Referenced by caja_window_reload(), and G_DEFINE_TYPE_WITH_CODE().
caja_window_slot_remove_extra_location_widgets()
void caja_window_slot_remove_extra_location_widgets (CajaWindowSlot * slot)
Definition at line 572 of file caja-window-slot.c.
References CajaWindowSlot::extra_location_frame, and CajaWindowSlot::extra_location_widgets.
caja_window_slot_set_allow_stop()
void caja_window_slot_set_allow_stop (CajaWindowSlot * slot, gboolean allow_stop)
Definition at line 508 of file caja-window-slot.c.
References CajaWindowSlot::allow_stop, CAJA_IS_WINDOW_SLOT, CAJA_WINDOW, caja_window_sync_allow_stop(), CajaWindowSlot::pane, and _CajaWindowPane::window.
Referenced by caja_window_report_load_underway(), and caja_window_slot_set_content_view().
caja_window_slot_set_content_view()
void caja_window_slot_set_content_view (CajaWindowSlot * slot, const char * id)
Definition at line 2247 of file caja-window-manage-views.c.
References caja_debug_log(), CAJA_DEBUG_LOG_DOMAIN_USER, caja_file_get(), caja_file_set_metadata(), caja_file_unref(), CAJA_IS_WINDOW, CAJA_LOCATION_CHANGE_RELOAD, CAJA_METADATA_KEY_DEFAULT_VIEW, caja_view_get_first_visible_file(), caja_view_get_selection_count(), caja_window_slot_content_view_matches_iid(), caja_window_slot_get_location_uri(), caja_window_slot_set_allow_stop(), CajaWindowSlot::content_view, FALSE, CajaWindowSlot::location, CajaWindowSlot::location_change_type, NULL, CajaWindowSlot::pane, CajaWindowSlot::pending_scroll_to, TRUE, and _CajaWindowPane::window.
caja_window_slot_set_content_view_widget()
void caja_window_slot_set_content_view_widget (CajaWindowSlot * slot, CajaView * content_view)
Definition at line 471 of file caja-window-slot.c.
References CAJA_IS_WINDOW, caja_view_get_widget(), caja_window_slot_connect_content_view(), caja_window_slot_disconnect_content_view(), CajaWindowSlot::content_view, NULL, CajaWindowSlot::pane, TRUE, CajaWindowSlot::view_box, and _CajaWindowPane::window.
Referenced by caja_window_report_view_failed().
caja_window_slot_set_status()
void caja_window_slot_set_status (CajaWindowSlot * slot, const char * status)
Definition at line 522 of file caja-window-slot.c.
References CAJA_IS_WINDOW_SLOT, CAJA_WINDOW, caja_window_sync_status(), CajaWindowSlot::pane, CajaWindowSlot::status_text, and _CajaWindowPane::window.
caja_window_slot_set_viewed_file()
void caja_window_slot_set_viewed_file (CajaWindowSlot * slot, CajaFile * file)
Definition at line 1704 of file caja-window.c.
References CAJA_FILE_ATTRIBUTE_INFO, CAJA_FILE_ATTRIBUTE_LINK_INFO, caja_file_monitor_add(), caja_file_monitor_remove(), caja_file_ref(), caja_file_set_has_open_window(), caja_file_unref(), CAJA_IS_SPATIAL_WINDOW, FALSE, NULL, CajaWindowSlot::pane, CajaWindowSlot::viewed_file, and _CajaWindowPane::window.
caja_window_slot_stop_loading()
void caja_window_slot_stop_loading (CajaWindowSlot * slot)
Definition at line 2227 of file caja-window-manage-views.c.
References CAJA_IS_WINDOW, caja_view_stop_loading(), CAJA_WINDOW, CajaWindowSlot::content_view, FALSE, CajaWindowSlot::new_content_view, NULL, CajaWindowSlot::pane, TRUE, and _CajaWindowPane::window.
caja_window_slot_update_icon()
void caja_window_slot_update_icon (CajaWindowSlot * slot)
Definition at line 365 of file caja-window-slot.c.
References _CajaWindowPane::active_slot, caja_icon_info_get_pixbuf_nodefault(), caja_icon_info_get_used_name(), CAJA_IS_WINDOW, CAJA_WINDOW_CLASS, EEL_CALL_METHOD_WITH_RETURN_VALUE, NULL, CajaWindowSlot::pane, and _CajaWindowPane::window.
Referenced by caja_window_show_window().
caja_window_slot_update_query_editor()
void caja_window_slot_update_query_editor (CajaWindowSlot * slot)
Definition at line 547 of file caja-window-slot.c.
References CAJA_WINDOW_SLOT_CLASS, eel_add_weak_pointer(), EEL_CALL_METHOD, NULL, and CajaWindowSlot::query_editor.
caja_window_slot_update_title()
void caja_window_slot_update_title (CajaWindowSlot * slot)
Definition at line 349 of file caja-window-slot.c.
References caja_window_slot_get_title().
Referenced by caja_window_show_window().