MATE Desktop Environment: caja-debug-log.c File Reference
caja-debug-log.c File Reference
#include <config.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include "caja-debug-log.h"
#include "caja-file.h"
#include <time.h>
#include <sys/time.h>
Macros
#define DEFAULT_RING_BUFFER_NUM_LINES 1000
#define KEY_FILE_GROUP "debug log"
#define KEY_FILE_DOMAINS_KEY "enable domains"
#define KEY_FILE_MAX_LINES_KEY "max lines"
#define MAX_URI_COUNT 20
Functions
void caja_debug_log (gboolean is_milestone, const char *domain, const char *format,...)
void caja_debug_logv (gboolean is_milestone, const char *domain, const GList *uris, const char *format, va_list args)
void caja_debug_log_with_uri_list (gboolean is_milestone, const char *domain, const GList *uris, const char *format,...)
void caja_debug_log_with_file_list (gboolean is_milestone, const char *domain, GList *files, const char *format,...)
gboolean caja_debug_log_load_configuration (const char *filename, GError **error)
void caja_debug_log_enable_domains (const char **domains, int n_domains)
void caja_debug_log_disable_domains (const char **domains, int n_domains)
gboolean caja_debug_log_is_domain_enabled (const char *domain)
gboolean caja_debug_log_dump (const char *filename, GError **error)
void caja_debug_log_set_max_lines (int num_lines)
int caja_debug_log_get_max_lines (void)
void caja_debug_log_clear (void)
Macro Definition Documentation
DEFAULT_RING_BUFFER_NUM_LINES
#define DEFAULT_RING_BUFFER_NUM_LINES 1000
Definition at line 36 of file caja-debug-log.c.
KEY_FILE_DOMAINS_KEY
#define KEY_FILE_DOMAINS_KEY "enable domains"
Definition at line 39 of file caja-debug-log.c.
Referenced by caja_debug_log_load_configuration().
KEY_FILE_GROUP
#define KEY_FILE_GROUP "debug log"
Definition at line 38 of file caja-debug-log.c.
Referenced by caja_debug_log_load_configuration().
KEY_FILE_MAX_LINES_KEY
#define KEY_FILE_MAX_LINES_KEY "max lines"
Definition at line 40 of file caja-debug-log.c.
Referenced by caja_debug_log_load_configuration().
MAX_URI_COUNT
#define MAX_URI_COUNT 20
Definition at line 42 of file caja-debug-log.c.
Referenced by caja_debug_log_with_file_list(), and caja_debug_logv().
Function Documentation
caja_debug_log()
void caja_debug_log (gboolean is_milestone, const char * domain, const char * format, ...)
Definition at line 68 of file caja-debug-log.c.
References caja_debug_logv(), and NULL.
Referenced by caja_application_create_navigation_window(), caja_application_get_spatial_window(), caja_window_slot_open_location_full(), caja_window_slot_set_content_view(), and fm_rename_file().
caja_debug_log_clear()
void caja_debug_log_clear (void)
Definition at line 759 of file caja-debug-log.c.
References NULL.
caja_debug_log_disable_domains()
void caja_debug_log_disable_domains (const char ** domains, int n_domains)
Definition at line 416 of file caja-debug-log.c.
References CAJA_DEBUG_LOG_DOMAIN_USER, and NULL.
caja_debug_log_dump()
gboolean caja_debug_log_dump (const char * filename, GError ** error)
Definition at line 631 of file caja-debug-log.c.
References error, FALSE, NULL, and TRUE.
caja_debug_log_enable_domains()
void caja_debug_log_enable_domains (const char ** domains, int n_domains)
Definition at line 384 of file caja-debug-log.c.
References CAJA_DEBUG_LOG_DOMAIN_USER, and NULL.
Referenced by caja_debug_log_load_configuration().
caja_debug_log_get_max_lines()
int caja_debug_log_get_max_lines (void)
Definition at line 747 of file caja-debug-log.c.
caja_debug_log_is_domain_enabled()
gboolean caja_debug_log_is_domain_enabled (const char * domain)
Definition at line 449 of file caja-debug-log.c.
References NULL.
Referenced by caja_debug_log_with_file_list(), and fm_directory_view_notify_selection_changed().
caja_debug_log_load_configuration()
gboolean caja_debug_log_load_configuration (const char * filename, GError ** error)
Definition at line 334 of file caja-debug-log.c.
References caja_debug_log_enable_domains(), caja_debug_log_set_max_lines(), error, FALSE, KEY_FILE_DOMAINS_KEY, KEY_FILE_GROUP, KEY_FILE_MAX_LINES_KEY, NULL, and TRUE.
caja_debug_log_set_max_lines()
void caja_debug_log_set_max_lines (int num_lines)
Definition at line 692 of file caja-debug-log.c.
References idx, MIN, and NULL.
Referenced by caja_debug_log_load_configuration().
caja_debug_log_with_file_list()
void caja_debug_log_with_file_list (gboolean is_milestone, const char * domain, GList * files, const char * format, ...)
Definition at line 277 of file caja-debug-log.c.
References caja_debug_log_is_domain_enabled(), caja_debug_logv(), CAJA_FILE, caja_file_get_uri(), caja_file_is_gone(), MAX_URI_COUNT, and NULL.
Referenced by caja_mime_activate_files(), and fm_directory_view_notify_selection_changed().
caja_debug_log_with_uri_list()
void caja_debug_log_with_uri_list (gboolean is_milestone, const char * domain, const GList * uris, const char * format, ...)
Definition at line 266 of file caja-debug-log.c.
References caja_debug_logv().
caja_debug_logv()
void caja_debug_logv (gboolean is_milestone, const char * domain, const GList * uris, const char * format, va_list args)
Definition at line 153 of file caja-debug-log.c.
References MAX_URI_COUNT, and NULL.
Referenced by caja_debug_log(), caja_debug_log_with_file_list(), and caja_debug_log_with_uri_list().