MATE Desktop Environment: caja-desktop-link-monitor.h File Reference
caja-desktop-link-monitor.h File Reference
#include <gtk/gtk.h>
#include "caja-desktop-link.h"
Classes
struct CajaDesktopLinkMonitor
struct CajaDesktopLinkMonitorClass
Macros
#define CAJA_TYPE_DESKTOP_LINK_MONITOR caja_desktop_link_monitor_get_type()
#define CAJA_DESKTOP_LINK_MONITOR(obj)
#define CAJA_DESKTOP_LINK_MONITOR_CLASS(klass)
#define CAJA_IS_DESKTOP_LINK_MONITOR(obj)
#define CAJA_IS_DESKTOP_LINK_MONITOR_CLASS(klass)
#define CAJA_DESKTOP_LINK_MONITOR_GET_CLASS(obj)
Typedefs
typedef struct CajaDesktopLinkMonitorDetails CajaDesktopLinkMonitorDetails
Functions
GType caja_desktop_link_monitor_get_type (void)
CajaDesktopLinkMonitor * caja_desktop_link_monitor_get (void)
char * caja_desktop_link_monitor_make_filename_unique (CajaDesktopLinkMonitor *monitor, const char *filename)
Macro Definition Documentation
CAJA_DESKTOP_LINK_MONITOR
#define CAJA_DESKTOP_LINK_MONITOR (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_DESKTOP_LINK_MONITOR, CajaDesktopLinkMonitor))
Definition at line 33 of file caja-desktop-link-monitor.h.
CAJA_DESKTOP_LINK_MONITOR_CLASS
#define CAJA_DESKTOP_LINK_MONITOR_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_DESKTOP_LINK_MONITOR, CajaDesktopLinkMonitorClass))
Definition at line 35 of file caja-desktop-link-monitor.h.
CAJA_DESKTOP_LINK_MONITOR_GET_CLASS
#define CAJA_DESKTOP_LINK_MONITOR_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_DESKTOP_LINK_MONITOR, CajaDesktopLinkMonitorClass))
Definition at line 41 of file caja-desktop-link-monitor.h.
CAJA_IS_DESKTOP_LINK_MONITOR
#define CAJA_IS_DESKTOP_LINK_MONITOR (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_DESKTOP_LINK_MONITOR))
Definition at line 37 of file caja-desktop-link-monitor.h.
CAJA_IS_DESKTOP_LINK_MONITOR_CLASS
#define CAJA_IS_DESKTOP_LINK_MONITOR_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_DESKTOP_LINK_MONITOR))
Definition at line 39 of file caja-desktop-link-monitor.h.
CAJA_TYPE_DESKTOP_LINK_MONITOR
#define CAJA_TYPE_DESKTOP_LINK_MONITOR caja_desktop_link_monitor_get_type()
Definition at line 32 of file caja-desktop-link-monitor.h.
Referenced by caja_desktop_link_monitor_get().
Typedef Documentation
CajaDesktopLinkMonitorDetails
typedef struct CajaDesktopLinkMonitorDetails CajaDesktopLinkMonitorDetails
Definition at line 44 of file caja-desktop-link-monitor.h.
Function Documentation
caja_desktop_link_monitor_get()
CajaDesktopLinkMonitor * caja_desktop_link_monitor_get (void)
Definition at line 82 of file caja-desktop-link-monitor.c.
References CAJA_TYPE_DESKTOP_LINK_MONITOR, eel_debug_call_at_shutdown(), and NULL.
Referenced by caja_desktop_link_new_from_mount().
caja_desktop_link_monitor_get_type()
GType caja_desktop_link_monitor_get_type (void)
caja_desktop_link_monitor_make_filename_unique()
char * caja_desktop_link_monitor_make_filename_unique (CajaDesktopLinkMonitor * monitor, const char * filename)
Definition at line 117 of file caja-desktop-link-monitor.c.
Referenced by caja_desktop_link_new_from_mount().