MATE Desktop Environment: caja-dropbox-hooks.c File Reference
caja-dropbox-hooks.c File Reference
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <errno.h>
#include <unistd.h>
#include <fcntl.h>
#include <string.h>
#include <glib.h>
#include "g-util.h"
#include "async-io-coroutine.h"
#include "dropbox-client-util.h"
#include "caja-dropbox-hooks.h"
Functions
gboolean caja_dropbox_hooks_force_reconnect (CajaDropboxHookserv *hookserv)
gboolean caja_dropbox_hooks_is_connected (CajaDropboxHookserv *hookserv)
void caja_dropbox_hooks_setup (CajaDropboxHookserv *hookserv)
void caja_dropbox_hooks_add_on_disconnect_hook (CajaDropboxHookserv *hookserv, DropboxHookClientConnectHook dhcch, gpointer ud)
void caja_dropbox_hooks_add_on_connect_hook (CajaDropboxHookserv *hookserv, DropboxHookClientConnectHook dhcch, gpointer ud)
void caja_dropbox_hooks_add (CajaDropboxHookserv *ndhs, const gchar *hook_name, DropboxUpdateHook hook, gpointer ud)
void caja_dropbox_hooks_start (CajaDropboxHookserv *hookserv)
Function Documentation
caja_dropbox_hooks_add()
void caja_dropbox_hooks_add (CajaDropboxHookserv * ndhs, const gchar * hook_name, DropboxUpdateHook hook, gpointer ud)
Definition at line 324 of file caja-dropbox-hooks.c.
References CajaDropboxHookserv::dispatch_table.
caja_dropbox_hooks_add_on_connect_hook()
void caja_dropbox_hooks_add_on_connect_hook (CajaDropboxHookserv * hookserv, DropboxHookClientConnectHook dhcch, gpointer ud)
Definition at line 312 of file caja-dropbox-hooks.c.
References CajaDropboxHookserv::onconnect_hooklist.
Referenced by dropbox_client_setup().
caja_dropbox_hooks_add_on_disconnect_hook()
void caja_dropbox_hooks_add_on_disconnect_hook (CajaDropboxHookserv * hookserv, DropboxHookClientConnectHook dhcch, gpointer ud)
Definition at line 299 of file caja-dropbox-hooks.c.
References CajaDropboxHookserv::ondisconnect_hooklist.
Referenced by dropbox_client_setup().
caja_dropbox_hooks_force_reconnect()
gboolean caja_dropbox_hooks_force_reconnect (CajaDropboxHookserv * hookserv)
Definition at line 261 of file caja-dropbox-hooks.c.
References CajaDropboxHookserv::connected, debug, debug_enter, CajaDropboxHookserv::event_source, and FALSE.
Referenced by dropbox_client_force_reconnect().
caja_dropbox_hooks_is_connected()
gboolean caja_dropbox_hooks_is_connected (CajaDropboxHookserv * hookserv)
Definition at line 283 of file caja-dropbox-hooks.c.
References CajaDropboxHookserv::connected.
Referenced by dropbox_client_is_connected().
caja_dropbox_hooks_setup()
void caja_dropbox_hooks_setup (CajaDropboxHookserv * hookserv)
Definition at line 288 of file caja-dropbox-hooks.c.
References CajaDropboxHookserv::connected, CajaDropboxHookserv::dispatch_table, FALSE, CajaDropboxHookserv::onconnect_hooklist, and CajaDropboxHookserv::ondisconnect_hooklist.
Referenced by dropbox_client_setup().
caja_dropbox_hooks_start()
void caja_dropbox_hooks_start (CajaDropboxHookserv * hookserv)
Definition at line 335 of file caja-dropbox-hooks.c.
Referenced by dropbox_client_start().