MATE Desktop Environment: caja-entry.c File Reference
caja-entry.c File Reference
#include <config.h>
#include <string.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <eel/eel-gdk-extensions.h>
#include <eel/eel-gtk-macros.h>
#include "caja-entry.h"
#include "caja-global-preferences.h"
Enumerations
enum { USER_CHANGED , SELECTION_CHANGED , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_CODE (CajaEntry, caja_entry, GTK_TYPE_ENTRY, G_IMPLEMENT_INTERFACE(GTK_TYPE_EDITABLE, caja_entry_editable_init))
GtkWidget * caja_entry_new (void)
void caja_entry_select_all (CajaEntry *entry)
void caja_entry_select_all_at_idle (CajaEntry *entry)
void caja_entry_set_text (CajaEntry *entry, const gchar *text)
void caja_entry_set_special_tab_handling (CajaEntry *entry, gboolean special_tab_handling)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
USER_CHANGED
SELECTION_CHANGED
LAST_SIGNAL
Definition at line 47 of file caja-entry.c.
Function Documentation
caja_entry_new()
GtkWidget * caja_entry_new (void)
Definition at line 72 of file caja-entry.c.
References CAJA_TYPE_ENTRY, and NULL.
Referenced by create_bookmarks_window().
caja_entry_select_all()
void caja_entry_select_all (CajaEntry * entry)
caja_entry_select_all
Select all text, leaving the text cursor position at the end.
@entry: A CajaEntry
Definition at line 188 of file caja-entry.c.
References CAJA_IS_ENTRY.
Referenced by caja_location_bar_activate().
caja_entry_select_all_at_idle()
void caja_entry_select_all_at_idle (CajaEntry * entry)
caja_entry_select_all_at_idle
Select all text at the next idle, not immediately. This is useful when reacting to a key press, because changing the selection and the text cursor position doesn't work in a key_press signal handler.
@entry: A CajaEntry
Definition at line 221 of file caja-entry.c.
References CAJA_IS_ENTRY, and CajaEntry::details.
caja_entry_set_special_tab_handling()
void caja_entry_set_special_tab_handling (CajaEntry * entry, gboolean special_tab_handling)
Definition at line 413 of file caja-entry.c.
References CAJA_IS_ENTRY, and CajaEntry::details.
caja_entry_set_text()
void caja_entry_set_text (CajaEntry * entry, const gchar * text)
caja_entry_set_text
This function wraps gtk_entry_set_text. It sets undo_registered to TRUE and preserves the old value for a later restore. This is done so the programmatic changes to the entry do not register with the undo manager.
@entry: A CajaEntry
Definition at line 249 of file caja-entry.c.
References CAJA_IS_ENTRY, CajaEntry::details, FALSE, SELECTION_CHANGED, and TRUE.
Referenced by caja_location_entry_update_current_location().
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (CajaEntry , caja_entry , GTK_TYPE_ENTRY , G_IMPLEMENT_INTERFACE(GTK_TYPE_EDITABLE, caja_entry_editable_init))
References NULL, and TRUE.