MATE Desktop Environment: caja-file-queue.h File Reference
caja-file-queue.h File Reference
#include "caja-file.h"
Typedefs
typedef struct CajaFileQueue CajaFileQueue
Functions
CajaFileQueue * caja_file_queue_new (void)
void caja_file_queue_destroy (CajaFileQueue *queue)
void caja_file_queue_enqueue (CajaFileQueue *queue, CajaFile *file)
CajaFile * caja_file_queue_dequeue (CajaFileQueue *queue)
void caja_file_queue_remove (CajaFileQueue *queue, CajaFile *file)
CajaFile * caja_file_queue_head (CajaFileQueue *queue)
gboolean caja_file_queue_is_empty (CajaFileQueue *queue)
Typedef Documentation
CajaFileQueue
typedef struct CajaFileQueue CajaFileQueue
Definition at line 28 of file caja-file-queue.h.
Function Documentation
caja_file_queue_dequeue()
CajaFile * caja_file_queue_dequeue (CajaFileQueue * queue)
Definition at line 80 of file caja-file-queue.c.
References caja_file_queue_head(), and caja_file_queue_remove().
caja_file_queue_destroy()
void caja_file_queue_destroy (CajaFileQueue * queue)
Definition at line 47 of file caja-file-queue.c.
References caja_file_list_free().
caja_file_queue_enqueue()
void caja_file_queue_enqueue (CajaFileQueue * queue, CajaFile * file)
Definition at line 55 of file caja-file-queue.c.
References caja_file_ref(), and NULL.
Referenced by caja_directory_add_file_to_work_queue().
caja_file_queue_head()
CajaFile * caja_file_queue_head (CajaFileQueue * queue)
Definition at line 118 of file caja-file-queue.c.
References CAJA_FILE, and NULL.
Referenced by caja_file_queue_dequeue().
caja_file_queue_is_empty()
gboolean caja_file_queue_is_empty (CajaFileQueue * queue)
Definition at line 129 of file caja-file-queue.c.
References NULL.
caja_file_queue_new()
CajaFileQueue * caja_file_queue_new (void)
Definition at line 36 of file caja-file-queue.c.
caja_file_queue_remove()
void caja_file_queue_remove (CajaFileQueue * queue, CajaFile * file)
Definition at line 91 of file caja-file-queue.c.
References caja_file_unref(), and NULL.
Referenced by caja_directory_remove_file_from_work_queue(), and caja_file_queue_dequeue().