MATE Desktop Environment: caja-directory-notify.h File Reference
caja-directory-notify.h File Reference
#include <gdk/gdk.h>
#include "caja-file.h"
Classes
struct URIPair
struct GFilePair
struct CajaFileChangesQueuePosition
Functions
void caja_directory_notify_files_added (GList *files)
void caja_directory_notify_files_moved (GList *file_pairs)
void caja_directory_notify_files_changed (GList *files)
void caja_directory_notify_files_removed (GList *files)
void caja_directory_schedule_metadata_copy (GList *file_pairs)
void caja_directory_schedule_metadata_move (GList *file_pairs)
void caja_directory_schedule_metadata_remove (GList *files)
void caja_directory_schedule_metadata_copy_by_uri (GList *uri_pairs)
void caja_directory_schedule_metadata_move_by_uri (GList *uri_pairs)
void caja_directory_schedule_metadata_remove_by_uri (GList *uris)
void caja_directory_schedule_position_set (GList *position_setting_list)
void caja_file_changed (CajaFile *file)
Function Documentation
caja_directory_notify_files_added()
void caja_directory_notify_files_added (GList * files)
Definition at line 858 of file caja-directory.c.
References caja_directory_is_file_list_monitored(), caja_directory_unref(), caja_file_changed(), caja_file_get_existing(), caja_file_invalidate_count_and_mime_list(), caja_file_unref(), CajaFile::details, _CajaFilePrivate::is_added, and NULL.
Referenced by caja_directory_notify_files_moved(), caja_file_changes_consume_changes(), and caja_link_local_create().
caja_directory_notify_files_changed()
void caja_directory_notify_files_changed (GList * files)
Definition at line 947 of file caja-directory.c.
References caja_file_get_existing(), caja_file_invalidate_extension_info_internal(), CajaFile::details, _CajaFilePrivate::directory, FALSE, _CajaFilePrivate::file_info_is_up_to_date, _CajaFilePrivate::link_info_is_up_to_date, NULL, and _CajaFilePrivate::top_left_text_is_up_to_date.
Referenced by caja_file_changes_consume_changes().
caja_directory_notify_files_moved()
void caja_directory_notify_files_moved (GList * file_pairs)
Definition at line 1191 of file caja-directory.c.
References caja_directory_cancel_loading_file_attributes(), caja_directory_notify_files_added(), caja_directory_unref(), CAJA_FILE, CAJA_FILE_ATTRIBUTE_INFO, caja_file_get_all_attributes(), caja_file_get_existing(), caja_file_invalidate_attributes(), caja_file_list_free(), caja_file_mark_gone(), caja_file_update_name_and_directory(), CajaFile::details, _CajaFilePrivate::directory, GFilePair::from, name, NULL, and GFilePair::to.
Referenced by caja_file_changes_consume_changes().
caja_directory_notify_files_removed()
void caja_directory_notify_files_removed (GList * files)
Definition at line 985 of file caja-directory.c.
References caja_directory_unref(), caja_file_get_existing(), caja_file_mark_gone(), caja_file_ref(), caja_file_rename_in_progress(), caja_file_unref(), CajaFile::details, _CajaFilePrivate::directory, and NULL.
Referenced by caja_file_changes_consume_changes().
caja_directory_schedule_metadata_copy()
void caja_directory_schedule_metadata_copy (GList * file_pairs)
caja_directory_schedule_metadata_copy_by_uri()
void caja_directory_schedule_metadata_copy_by_uri (GList * uri_pairs)
caja_directory_schedule_metadata_move()
void caja_directory_schedule_metadata_move (GList * file_pairs)
caja_directory_schedule_metadata_move_by_uri()
void caja_directory_schedule_metadata_move_by_uri (GList * uri_pairs)
caja_directory_schedule_metadata_remove()
void caja_directory_schedule_metadata_remove (GList * files)
caja_directory_schedule_metadata_remove_by_uri()
void caja_directory_schedule_metadata_remove_by_uri (GList * uris)
caja_directory_schedule_position_set()
void caja_directory_schedule_position_set (GList * position_setting_list)
Definition at line 1319 of file caja-directory.c.
References caja_file_get(), caja_file_set_metadata(), caja_file_set_time_metadata(), caja_file_unref(), CAJA_METADATA_KEY_ICON_POSITION, CAJA_METADATA_KEY_ICON_POSITION_TIMESTAMP, CAJA_METADATA_KEY_SCREEN, item, NULL, and UNDEFINED_TIME.
Referenced by caja_file_changes_consume_changes(), and caja_link_local_create().
caja_file_changed()
void caja_file_changed (CajaFile * file)
Definition at line 7702 of file caja-file.c.
References caja_directory_emit_change_signals(), caja_file_emit_changed(), caja_file_is_self_owned(), CAJA_IS_FILE, CajaFile::details, _CajaFilePrivate::directory, and NULL.
Referenced by caja_desktop_icon_file_update(), caja_desktop_set_metadata_string(), caja_desktop_set_metadata_stringv(), caja_directory_notify_files_added(), caja_file_emit_changed(), caja_file_info_providers_done(), caja_file_operation_complete(), caja_file_refresh_info(), caja_file_rename(), caja_file_set_group(), caja_file_set_has_open_window(), caja_file_set_owner(), and caja_file_set_permissions().