MATE Desktop Environment: caja-connect-server-dialog-nonmain.c File Reference
caja-connect-server-dialog-nonmain.c File Reference
#include <config.h>
#include <gio/gio.h>
#include <libcaja-private/caja-global-preferences.h>
#include "caja-connect-server-dialog.h"
Functions
gboolean caja_connect_server_dialog_display_location_finish (CajaConnectServerDialog *self, GAsyncResult *res, GError **error)
void caja_connect_server_dialog_display_location_async (CajaConnectServerDialog *self, CajaApplication *application, GFile *location, GAsyncReadyCallback callback, gpointer user_data)
Function Documentation
caja_connect_server_dialog_display_location_async()
void caja_connect_server_dialog_display_location_async (CajaConnectServerDialog * self, CajaApplication * application, GFile * location, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 67 of file caja-connect-server-dialog-nonmain.c.
References caja_application_create_navigation_window(), caja_application_get_spatial_window(), caja_connect_server_dialog_display_location_async(), caja_preferences, CAJA_PREFERENCES_ALWAYS_USE_BROWSER, caja_window_go_to_full(), NULL, and user_data.
caja_connect_server_dialog_display_location_finish()
gboolean caja_connect_server_dialog_display_location_finish (CajaConnectServerDialog * self, GAsyncResult * res, GError ** error)
Definition at line 55 of file caja-connect-server-dialog-nonmain.c.
References error, FALSE, and TRUE.