MATE Desktop Environment: caja-location-entry.c File Reference
caja-location-entry.c File Reference
#include <config.h>
#include <stdio.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <eel/eel-glib-extensions.h>
#include <eel/eel-gtk-macros.h>
#include <eel/eel-stock-dialogs.h>
#include <eel/eel-string.h>
#include <libcaja-private/caja-file-utilities.h>
#include <libcaja-private/caja-entry.h>
#include <libcaja-private/caja-icon-dnd.h>
#include <libcaja-private/caja-clipboard.h>
#include "caja-location-entry.h"
#include "caja-window-private.h"
#include "caja-window.h"
Functions
EEL_CLASS_BOILERPLATE (CajaLocationEntry, caja_location_entry, CAJA_TYPE_ENTRY)
void caja_location_entry_update_current_location (CajaLocationEntry *entry, const char *location)
void caja_location_entry_set_secondary_action (CajaLocationEntry *entry, CajaLocationEntryAction secondary_action)
GtkWidget * caja_location_entry_new (void)
void caja_location_entry_set_special_text (CajaLocationEntry *entry, const char *special_text)
Function Documentation
caja_location_entry_new()
GtkWidget * caja_location_entry_new (void)
Definition at line 470 of file caja-location-entry.c.
References CAJA_TYPE_LOCATION_ENTRY, and NULL.
caja_location_entry_set_secondary_action()
void caja_location_entry_set_secondary_action (CajaLocationEntry * entry, CajaLocationEntryAction secondary_action)
Definition at line 413 of file caja-location-entry.c.
References CAJA_LOCATION_ENTRY_ACTION_CLEAR, CAJA_LOCATION_ENTRY_ACTION_GOTO, and CajaLocationEntry::details.
caja_location_entry_set_special_text()
void caja_location_entry_set_special_text (CajaLocationEntry * entry, const char * special_text)
Definition at line 480 of file caja-location-entry.c.
References CajaLocationEntry::details, FALSE, and TRUE.
Referenced by caja_location_bar_set_location().
caja_location_entry_update_current_location()
void caja_location_entry_update_current_location (CajaLocationEntry * entry, const char * location)
Definition at line 402 of file caja-location-entry.c.
References CAJA_ENTRY, caja_entry_set_text(), and CajaLocationEntry::details.
Referenced by caja_location_bar_set_location(), caja_location_dialog_new(), and caja_location_dialog_set_location().
EEL_CLASS_BOILERPLATE()
EEL_CLASS_BOILERPLATE (CajaLocationEntry , caja_location_entry , CAJA_TYPE_ENTRY)
Definition at line 74 of file caja-location-entry.c.
References CAJA_LOCATION_ENTRY, CAJA_TYPE_ENTRY, CajaLocationEntry::details, FALSE, and NULL.