MATE Desktop Environment: caja-bookmarks-window.c File Reference
caja-bookmarks-window.c File Reference
#include <config.h>
#include <cairo-gobject.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <eel/eel-gtk-extensions.h>
#include <eel/eel-mate-extensions.h>
#include <libcaja-private/caja-global-preferences.h>
#include "caja-bookmarks-window.h"
#include "caja-window.h"
#include "caja-navigation-window.h"
#include "caja-spatial-window.h"
Macros
#define BOOKMARK_LIST_COLUMN_ICON 0
#define BOOKMARK_LIST_COLUMN_NAME 1
#define BOOKMARK_LIST_COLUMN_BOOKMARK 2
#define BOOKMARK_LIST_COLUMN_STYLE 3
#define BOOKMARK_LIST_COLUMN_COUNT 4
#define BOOKMARKS_WINDOW_MIN_WIDTH 300
#define BOOKMARKS_WINDOW_MIN_HEIGHT 100
#define BOOKMARKS_WINDOW_INITIAL_WIDTH 500
#define BOOKMARKS_WINDOW_INITIAL_HEIGHT 200
Functions
GtkWindow * create_bookmarks_window (CajaBookmarkList *list, CajaWindow *window_source)
void edit_bookmarks_dialog_set_signals (CajaWindow *window)
void caja_bookmarks_window_save_geometry (GtkWindow *window)
Macro Definition Documentation
BOOKMARK_LIST_COLUMN_BOOKMARK
#define BOOKMARK_LIST_COLUMN_BOOKMARK 2
Definition at line 129 of file caja-bookmarks-window.c.
BOOKMARK_LIST_COLUMN_COUNT
#define BOOKMARK_LIST_COLUMN_COUNT 4
Definition at line 131 of file caja-bookmarks-window.c.
BOOKMARK_LIST_COLUMN_ICON
#define BOOKMARK_LIST_COLUMN_ICON 0
Definition at line 127 of file caja-bookmarks-window.c.
Referenced by create_bookmarks_window().
BOOKMARK_LIST_COLUMN_NAME
#define BOOKMARK_LIST_COLUMN_NAME 1
Definition at line 128 of file caja-bookmarks-window.c.
Referenced by create_bookmarks_window().
BOOKMARK_LIST_COLUMN_STYLE
#define BOOKMARK_LIST_COLUMN_STYLE 3
Definition at line 130 of file caja-bookmarks-window.c.
Referenced by create_bookmarks_window().
BOOKMARKS_WINDOW_INITIAL_HEIGHT
#define BOOKMARKS_WINDOW_INITIAL_HEIGHT 200
Definition at line 141 of file caja-bookmarks-window.c.
BOOKMARKS_WINDOW_INITIAL_WIDTH
#define BOOKMARKS_WINDOW_INITIAL_WIDTH 500
Definition at line 140 of file caja-bookmarks-window.c.
BOOKMARKS_WINDOW_MIN_HEIGHT
#define BOOKMARKS_WINDOW_MIN_HEIGHT 100
Definition at line 137 of file caja-bookmarks-window.c.
BOOKMARKS_WINDOW_MIN_WIDTH
#define BOOKMARKS_WINDOW_MIN_WIDTH 300
Definition at line 136 of file caja-bookmarks-window.c.
Function Documentation
caja_bookmarks_window_save_geometry()
void caja_bookmarks_window_save_geometry (GtkWindow * window)
caja_bookmarks_window_save_geometry:
Save window size & position to disk. @window: The bookmarks window whose geometry should be saved.
Definition at line 509 of file caja-bookmarks-window.c.
References caja_bookmark_list_set_window_geometry(), CAJA_IS_BOOKMARK_LIST, and eel_gtk_window_get_geometry_string().
Referenced by caja_bookmarks_exiting().
create_bookmarks_window()
GtkWindow * create_bookmarks_window (CajaBookmarkList * list, CajaWindow * window_source)
create_bookmarks_window:
Create a new bookmark-editing window. @list: The CajaBookmarkList that this window will edit.
Return value: A pointer to the new window.
Definition at line 258 of file caja-bookmarks-window.c.
References CajaWindow::application, BOOKMARK_LIST_COLUMN_ICON, BOOKMARK_LIST_COLUMN_NAME, BOOKMARK_LIST_COLUMN_STYLE, caja_entry_new(), CAJA_ICON_SIZE_SMALLER, CAJA_IS_NAVIGATION_WINDOW, FALSE, NULL, and TRUE.
edit_bookmarks_dialog_set_signals()
void edit_bookmarks_dialog_set_signals (CajaWindow * window)
Definition at line 413 of file caja-bookmarks-window.c.