MATE Desktop Environment: caja-file-private.h File Reference
caja-file-private.h File Reference
#include <eel/eel-glib-extensions.h>
#include <eel/eel-string.h>
#include "caja-directory.h"
#include "caja-file.h"
#include "caja-monitor.h"
#include "caja-undostack-manager.h"
Classes
struct CajaFileSortByEmblemCache
struct _CajaFilePrivate
struct CajaFileOperation
Macros
#define CAJA_FILE_LARGE_TOP_LEFT_TEXT_MAXIMUM_CHARACTERS_PER_LINE 80
#define CAJA_FILE_LARGE_TOP_LEFT_TEXT_MAXIMUM_LINES 24
#define CAJA_FILE_LARGE_TOP_LEFT_TEXT_MAXIMUM_BYTES 10000
#define CAJA_FILE_TOP_LEFT_TEXT_MAXIMUM_CHARACTERS_PER_LINE 10
#define CAJA_FILE_TOP_LEFT_TEXT_MAXIMUM_LINES 5
#define CAJA_FILE_TOP_LEFT_TEXT_MAXIMUM_BYTES 1024
#define CAJA_FILE_DEFAULT_ATTRIBUTES "standard::*,access::*,mountable::*,time::*,unix::*,owner::*,selinux::*,thumbnail::*,id::filesystem,trash::orig-path,trash::deletion-date,metadata::*"
Enumerations
enum Knowledge { KNOWN , UNKNOWABLE , UNKNOWN }
Functions
CajaFile * caja_file_new_from_info (CajaDirectory *directory, GFileInfo *info)
void caja_file_emit_changed (CajaFile *file)
void caja_file_mark_gone (CajaFile *file)
char * caja_extract_top_left_text (const char *text, gboolean large, int length)
void caja_file_set_directory (CajaFile *file, CajaDirectory *directory)
gboolean caja_file_get_date (CajaFile *file, CajaDateType date_type, time_t *date)
void caja_file_updated_deep_count_in_progress (CajaFile *file)
void caja_file_clear_info (CajaFile *file)
gboolean caja_file_update_info (CajaFile *file, GFileInfo *info)
gboolean caja_file_update_name (CajaFile *file, const char *name)
gboolean caja_file_update_metadata_from_info (CajaFile *file, GFileInfo *info)
gboolean caja_file_update_name_and_directory (CajaFile *file, const char *name, CajaDirectory *directory)
gboolean caja_file_set_display_name (CajaFile *file, const char *display_name, const char *edit_name, gboolean custom)
void caja_file_set_mount (CajaFile *file, GMount *mount)
gboolean caja_file_should_get_top_left_text (CajaFile *file)
void caja_file_invalidate_attributes_internal (CajaFile *file, CajaFileAttributes file_attributes)
CajaFileAttributes caja_file_get_all_attributes (void)
gboolean caja_file_is_self_owned (CajaFile *file)
void caja_file_invalidate_count_and_mime_list (CajaFile *file)
gboolean caja_file_rename_in_progress (CajaFile *file)
void caja_file_invalidate_extension_info_internal (CajaFile *file)
void caja_file_info_providers_done (CajaFile *file)
void caja_file_set_is_thumbnailing (CajaFile *file, gboolean is_thumbnailing)
CajaFileOperation * caja_file_operation_new (CajaFile *file, CajaFileOperationCallback callback, gpointer callback_data)
void caja_file_operation_free (CajaFileOperation *op)
void caja_file_operation_complete (CajaFileOperation *op, GFile *result_location, GError *error)
void caja_file_operation_cancel (CajaFileOperation *op)
Macro Definition Documentation
CAJA_FILE_DEFAULT_ATTRIBUTES
#define CAJA_FILE_DEFAULT_ATTRIBUTES "standard::*,access::*,mountable::*,time::*,unix::*,owner::*,selinux::*,thumbnail::*,id::filesystem,trash::orig-path,trash::deletion-date,metadata::*"
Definition at line 44 of file caja-file-private.h.
Referenced by caja_directory_get_info_for_new_files(), and caja_file_refresh_info().
CAJA_FILE_LARGE_TOP_LEFT_TEXT_MAXIMUM_BYTES
#define CAJA_FILE_LARGE_TOP_LEFT_TEXT_MAXIMUM_BYTES 10000
Definition at line 38 of file caja-file-private.h.
Referenced by caja_extract_top_left_text().
CAJA_FILE_LARGE_TOP_LEFT_TEXT_MAXIMUM_CHARACTERS_PER_LINE
#define CAJA_FILE_LARGE_TOP_LEFT_TEXT_MAXIMUM_CHARACTERS_PER_LINE 80
Definition at line 36 of file caja-file-private.h.
Referenced by caja_extract_top_left_text().
CAJA_FILE_LARGE_TOP_LEFT_TEXT_MAXIMUM_LINES
#define CAJA_FILE_LARGE_TOP_LEFT_TEXT_MAXIMUM_LINES 24
Definition at line 37 of file caja-file-private.h.
Referenced by caja_extract_top_left_text().
CAJA_FILE_TOP_LEFT_TEXT_MAXIMUM_BYTES
#define CAJA_FILE_TOP_LEFT_TEXT_MAXIMUM_BYTES 1024
Definition at line 42 of file caja-file-private.h.
Referenced by caja_extract_top_left_text().
CAJA_FILE_TOP_LEFT_TEXT_MAXIMUM_CHARACTERS_PER_LINE
#define CAJA_FILE_TOP_LEFT_TEXT_MAXIMUM_CHARACTERS_PER_LINE 10
Definition at line 40 of file caja-file-private.h.
Referenced by caja_extract_top_left_text().
CAJA_FILE_TOP_LEFT_TEXT_MAXIMUM_LINES
#define CAJA_FILE_TOP_LEFT_TEXT_MAXIMUM_LINES 5
Definition at line 41 of file caja-file-private.h.
Referenced by caja_extract_top_left_text().
Enumeration Type Documentation
Knowledge
enum Knowledge
Enumerator
KNOWN
UNKNOWABLE
UNKNOWN
Definition at line 50 of file caja-file-private.h.
Function Documentation
caja_extract_top_left_text()
char * caja_extract_top_left_text (const char * text, gboolean large, int length)
Definition at line 8444 of file caja-file.c.
References CAJA_FILE_LARGE_TOP_LEFT_TEXT_MAXIMUM_BYTES, CAJA_FILE_LARGE_TOP_LEFT_TEXT_MAXIMUM_CHARACTERS_PER_LINE, CAJA_FILE_LARGE_TOP_LEFT_TEXT_MAXIMUM_LINES, CAJA_FILE_TOP_LEFT_TEXT_MAXIMUM_BYTES, CAJA_FILE_TOP_LEFT_TEXT_MAXIMUM_CHARACTERS_PER_LINE, CAJA_FILE_TOP_LEFT_TEXT_MAXIMUM_LINES, FALSE, and NULL.
caja_file_clear_info()
void caja_file_clear_info (CajaFile * file)
Definition at line 419 of file caja-file.c.
References _CajaFilePrivate::activation_uri, _CajaFilePrivate::atime, _CajaFilePrivate::btime, CAJA_FILE_GET_CLASS, _CajaFilePrivate::can_delete, _CajaFilePrivate::can_eject, _CajaFilePrivate::can_execute, _CajaFilePrivate::can_mount, _CajaFilePrivate::can_poll_for_media, _CajaFilePrivate::can_read, _CajaFilePrivate::can_rename, _CajaFilePrivate::can_start, _CajaFilePrivate::can_start_degraded, _CajaFilePrivate::can_stop, _CajaFilePrivate::can_trash, _CajaFilePrivate::can_unmount, _CajaFilePrivate::can_write, _CajaFilePrivate::ctime, _CajaFilePrivate::description, CajaFile::details, FALSE, _CajaFilePrivate::filesystem_id, _CajaFilePrivate::get_info_error, _CajaFilePrivate::gid, _CajaFilePrivate::got_custom_activation_uri, _CajaFilePrivate::got_custom_display_name, _CajaFilePrivate::got_file_info, _CajaFilePrivate::group, _CajaFilePrivate::has_permissions, _CajaFilePrivate::icon, _CajaFilePrivate::is_backup, _CajaFilePrivate::is_foreign_link, _CajaFilePrivate::is_hidden, _CajaFilePrivate::is_launcher, _CajaFilePrivate::is_media_check_automatic, _CajaFilePrivate::is_mountpoint, _CajaFilePrivate::is_symlink, _CajaFilePrivate::is_trusted_link, _CajaFilePrivate::mime_type, _CajaFilePrivate::mtime, NULL, _CajaFilePrivate::owner, _CajaFilePrivate::owner_real, _CajaFilePrivate::permissions, _CajaFilePrivate::selinux_context, _CajaFilePrivate::size, _CajaFilePrivate::size_on_disk, _CajaFilePrivate::sort_order, _CajaFilePrivate::start_stop_type, _CajaFilePrivate::symlink_name, _CajaFilePrivate::thumbnail_path, _CajaFilePrivate::thumbnailing_failed, _CajaFilePrivate::trash_time, TRUE, _CajaFilePrivate::type, and _CajaFilePrivate::uid.
Referenced by caja_file_mark_gone().
caja_file_emit_changed()
void caja_file_emit_changed (CajaFile * file)
Definition at line 7753 of file caja-file.c.
References CAJA_FILE, caja_file_changed(), caja_file_list_free(), CAJA_IS_FILE, CHANGED, _CajaFilePrivate::compare_by_emblem_cache, CajaFile::details, and NULL.
Referenced by caja_directory_emit_change_signals(), caja_file_changed(), and caja_search_directory_file_update_display_name().
caja_file_get_all_attributes()
CajaFileAttributes caja_file_get_all_attributes (void)
Definition at line 8053 of file caja-file.c.
References CAJA_FILE_ATTRIBUTE_DEEP_COUNTS, CAJA_FILE_ATTRIBUTE_DIRECTORY_ITEM_COUNT, CAJA_FILE_ATTRIBUTE_DIRECTORY_ITEM_MIME_TYPES, CAJA_FILE_ATTRIBUTE_EXTENSION_INFO, CAJA_FILE_ATTRIBUTE_INFO, CAJA_FILE_ATTRIBUTE_LARGE_TOP_LEFT_TEXT, CAJA_FILE_ATTRIBUTE_LINK_INFO, CAJA_FILE_ATTRIBUTE_MOUNT, CAJA_FILE_ATTRIBUTE_THUMBNAIL, and CAJA_FILE_ATTRIBUTE_TOP_LEFT_TEXT.
Referenced by caja_directory_notify_files_moved(), and caja_file_invalidate_all_attributes().
caja_file_get_date()
gboolean caja_file_get_date (CajaFile * file, CajaDateType date_type, time_t * date)
Definition at line 4722 of file caja-file.c.
References CAJA_DATE_TYPE_ACCESSED, CAJA_DATE_TYPE_CHANGED, CAJA_DATE_TYPE_CREATED, CAJA_DATE_TYPE_MODIFIED, CAJA_DATE_TYPE_PERMISSIONS_CHANGED, CAJA_DATE_TYPE_TRASHED, CAJA_FILE_CLASS, CAJA_IS_FILE, EEL_CALL_METHOD_WITH_RETURN_VALUE, FALSE, and NULL.
caja_file_info_providers_done()
void caja_file_info_providers_done (CajaFile * file)
Definition at line 8739 of file caja-file.c.
References caja_file_changed(), CajaFile::details, _CajaFilePrivate::extension_attributes, _CajaFilePrivate::extension_emblems, NULL, _CajaFilePrivate::pending_extension_attributes, and _CajaFilePrivate::pending_extension_emblems.
caja_file_invalidate_attributes_internal()
void caja_file_invalidate_attributes_internal (CajaFile * file, CajaFileAttributes file_attributes)
Definition at line 7941 of file caja-file.c.
References caja_directory_set_up_request(), caja_file_invalidate_extension_info_internal(), CAJA_IS_DESKTOP_ICON_FILE, NULL, REQUEST_DEEP_COUNT, REQUEST_DIRECTORY_COUNT, REQUEST_EXTENSION_INFO, REQUEST_FILE_INFO, REQUEST_LINK_INFO, REQUEST_MIME_LIST, REQUEST_MOUNT, REQUEST_THUMBNAIL, REQUEST_TOP_LEFT_TEXT, and REQUEST_WANTS_TYPE.
Referenced by caja_file_invalidate_attributes().
caja_file_invalidate_count_and_mime_list()
void caja_file_invalidate_count_and_mime_list (CajaFile * file)
Definition at line 2359 of file caja-directory-async.c.
References CAJA_FILE_ATTRIBUTE_DIRECTORY_ITEM_COUNT, CAJA_FILE_ATTRIBUTE_DIRECTORY_ITEM_MIME_TYPES, and caja_file_invalidate_attributes().
Referenced by caja_directory_invalidate_count_and_mime_list(), and caja_directory_notify_files_added().
caja_file_invalidate_extension_info_internal()
void caja_file_invalidate_extension_info_internal (CajaFile * file)
Definition at line 7931 of file caja-file.c.
References caja_extensions_get_for_type(), CAJA_TYPE_INFO_PROVIDER, CajaFile::details, and _CajaFilePrivate::pending_info_providers.
Referenced by caja_directory_notify_files_changed(), and caja_file_invalidate_attributes_internal().
caja_file_is_self_owned()
gboolean caja_file_is_self_owned (CajaFile * file)
Definition at line 757 of file caja-file.c.
References _CajaDirectoryPrivate::as_file, CajaDirectory::details, CajaFile::details, and _CajaFilePrivate::directory.
Referenced by caja_file_can_delete(), caja_file_can_rename(), caja_file_can_trash(), caja_file_changed(), caja_file_get_location(), caja_file_get_parent(), caja_file_get_parent_location(), caja_file_get_parent_uri(), caja_file_mark_gone(), caja_file_rename(), and caja_file_update_name_and_directory().
caja_file_mark_gone()
void caja_file_mark_gone (CajaFile * file)
Definition at line 7665 of file caja-file.c.
References caja_directory_remove_file(), caja_file_clear_info(), caja_file_is_self_owned(), CajaFile::details, _CajaFilePrivate::directory, _CajaFilePrivate::is_gone, and TRUE.
Referenced by caja_directory_notify_files_moved(), and caja_directory_notify_files_removed().
caja_file_new_from_info()
CajaFile * caja_file_new_from_info (CajaDirectory * directory, GFileInfo * info)
Definition at line 631 of file caja-file.c.
References caja_directory_ref(), CAJA_FILE, CAJA_IS_DIRECTORY, CAJA_SAVED_SEARCH_MIMETYPE, CAJA_TYPE_SAVED_SEARCH_FILE, CAJA_TYPE_VFS_FILE, DEBUG_REF_PRINTF, CajaFile::details, _CajaFilePrivate::directory, mime_type, and NULL.
caja_file_operation_cancel()
void caja_file_operation_cancel (CajaFileOperation * op)
Definition at line 1691 of file caja-file.c.
References op.
Referenced by caja_file_cancel().
caja_file_operation_complete()
void caja_file_operation_complete (CajaFileOperation * op, GFile * result_location, GError * error)
Definition at line 1676 of file caja-file.c.
References caja_file_changed(), caja_file_operation_free(), error, and op.
caja_file_operation_free()
void caja_file_operation_free (CajaFileOperation * op)
Definition at line 1660 of file caja-file.c.
References caja_file_unref(), caja_undostack_manager_add_action(), caja_undostack_manager_instance(), and op.
Referenced by caja_file_operation_complete().
caja_file_operation_new()
CajaFileOperation * caja_file_operation_new (CajaFile * file, CajaFileOperationCallback callback, gpointer callback_data)
Definition at line 1634 of file caja-file.c.
References caja_file_ref(), and op.
Referenced by caja_file_rename(), caja_file_set_attributes(), and caja_file_stop().
caja_file_rename_in_progress()
gboolean caja_file_rename_in_progress (CajaFile * file)
Definition at line 1976 of file caja-file.c.
References CajaFile::details, FALSE, NULL, op, _CajaFilePrivate::operations_in_progress, and TRUE.
Referenced by caja_directory_notify_files_removed().
caja_file_set_directory()
void caja_file_set_directory (CajaFile * file, CajaDirectory * directory)
Definition at line 2709 of file caja-file.c.
References caja_file_update_name_and_directory(), and NULL.
caja_file_set_display_name()
gboolean caja_file_set_display_name (CajaFile * file, const char * display_name, const char * edit_name, gboolean custom)
Definition at line 203 of file caja-file.c.
References CAJA_FILE_ATTRIBUTE_INFO, caja_file_invalidate_attributes(), CajaFile::details, _CajaFilePrivate::display_name, _CajaFilePrivate::display_name_collation_key, _CajaFilePrivate::edit_name, eel_strcmp(), FALSE, _CajaFilePrivate::got_custom_display_name, _CajaFilePrivate::name, NULL, and TRUE.
Referenced by caja_search_directory_file_update_display_name().
caja_file_set_is_thumbnailing()
void caja_file_set_is_thumbnailing (CajaFile * file, gboolean is_thumbnailing)
Definition at line 8018 of file caja-file.c.
References CAJA_IS_FILE, CajaFile::details, FALSE, and _CajaFilePrivate::is_thumbnailing.
Referenced by caja_create_thumbnail().
caja_file_set_mount()
void caja_file_set_mount (CajaFile * file, GMount * mount)
Definition at line 7143 of file caja-file.c.
References CajaFile::details, _CajaFilePrivate::mount, and NULL.
caja_file_should_get_top_left_text()
gboolean caja_file_should_get_top_left_text (CajaFile * file)
Definition at line 5113 of file caja-file.c.
References CAJA_IS_FILE, caja_preferences, CAJA_PREFERENCES_SHOW_TEXT_IN_ICONS, CAJA_SPEED_TRADEOFF_ALWAYS, CAJA_SPEED_TRADEOFF_NEVER, FALSE, NULL, and TRUE.
Referenced by caja_file_peek_top_left_text().
caja_file_update_info()
gboolean caja_file_update_info (CajaFile * file, GFileInfo * info)
Definition at line 2579 of file caja-file.c.
References FALSE.
Referenced by caja_file_refresh_info().
caja_file_update_metadata_from_info()
gboolean caja_file_update_metadata_from_info (CajaFile * file, GFileInfo * info)
Definition at line 394 of file caja-file.c.
References CajaFile::details, FALSE, _CajaFilePrivate::metadata, and TRUE.
Referenced by caja_desktop_update_metadata_from_keyfile().
caja_file_update_name()
gboolean caja_file_update_name (CajaFile * file, const char * name)
Definition at line 2642 of file caja-file.c.
References name, and TRUE.
caja_file_update_name_and_directory()
gboolean caja_file_update_name_and_directory (CajaFile * file, const char * name, CajaDirectory * directory)
Definition at line 2656 of file caja-file.c.
References caja_directory_add_file(), caja_directory_add_file_monitors(), caja_directory_ref(), caja_directory_remove_file(), caja_directory_remove_file_monitors(), caja_directory_unref(), caja_file_is_self_owned(), caja_file_ref(), caja_file_unref(), CAJA_IS_DIRECTORY, CAJA_IS_FILE, CajaFile::details, _CajaFilePrivate::directory, FALSE, _CajaFilePrivate::is_gone, name, and TRUE.
Referenced by caja_directory_notify_files_moved(), and caja_file_set_directory().
caja_file_updated_deep_count_in_progress()
void caja_file_updated_deep_count_in_progress (CajaFile * file)
caja_file_updated_deep_count_in_progress
Notify clients that a newer deep count is available for the directory in question.
Definition at line 7726 of file caja-file.c.
References CAJA_FILE, caja_file_is_directory(), caja_file_list_free(), caja_file_updated_deep_count_in_progress(), CAJA_IS_FILE, NULL, and UPDATED_DEEP_COUNT_IN_PROGRESS.
Referenced by caja_file_updated_deep_count_in_progress().