MATE Desktop Environment: caja-view-factory.h File Reference
caja-view-factory.h File Reference
#include <string.h>
#include <gio/gio.h>
#include "caja-view.h"
#include "caja-window-slot-info.h"
Classes
struct _CajaViewInfo
Typedefs
typedef struct _CajaViewInfo CajaViewInfo
Functions
void caja_view_factory_register (CajaViewInfo *view_info)
const CajaViewInfo * caja_view_factory_lookup (const char *id)
CajaView * caja_view_factory_create (const char *id, CajaWindowSlotInfo *slot)
gboolean caja_view_factory_view_supports_uri (const char *id, GFile *location, GFileType file_type, const char *mime_type)
GList * caja_view_factory_get_views_for_uri (const char *uri, GFileType file_type, const char *mime_type)
Typedef Documentation
CajaViewInfo
typedef struct _CajaViewInfo CajaViewInfo
Definition at line 39 of file caja-view-factory.h.
Function Documentation
caja_view_factory_create()
CajaView * caja_view_factory_create (const char * id, CajaWindowSlotInfo * slot)
Definition at line 60 of file caja-view-factory.c.
References caja_view_factory_lookup(), _CajaViewInfo::create, and NULL.
caja_view_factory_get_views_for_uri()
GList * caja_view_factory_get_views_for_uri (const char * uri, GFileType file_type, const char * mime_type)
Definition at line 103 of file caja-view-factory.c.
References _CajaViewInfo::id, mime_type, NULL, _CajaViewInfo::single_view, and _CajaViewInfo::supports_uri.
caja_view_factory_lookup()
const CajaViewInfo * caja_view_factory_lookup (const char * id)
Definition at line 40 of file caja-view-factory.c.
References _CajaViewInfo::id, and NULL.
Referenced by caja_view_factory_create(), caja_view_factory_register(), and caja_view_factory_view_supports_uri().
caja_view_factory_register()
void caja_view_factory_register (CajaViewInfo * view_info)
Definition at line 30 of file caja-view-factory.c.
References caja_view_factory_lookup(), _CajaViewInfo::id, and NULL.
Referenced by fm_compact_view_register(), fm_desktop_icon_view_register(), fm_empty_view_register(), fm_icon_view_register(), fm_list_view_register(), and fm_widget_view_register().
caja_view_factory_view_supports_uri()
gboolean caja_view_factory_view_supports_uri (const char * id, GFile * location, GFileType file_type, const char * mime_type)
Definition at line 81 of file caja-view-factory.c.
References caja_view_factory_lookup(), FALSE, mime_type, NULL, and _CajaViewInfo::supports_uri.