MATE Desktop Environment: caja-property-browser.c File Reference
caja-property-browser.c File Reference
#include <config.h>
#include <limits.h>
#include <math.h>
#include <libxml/parser.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <glib/gstdio.h>
#include <gio/gio.h>
#include <atk/atkrelationset.h>
#include <eel/eel-gdk-extensions.h>
#include <eel/eel-gdk-pixbuf-extensions.h>
#include <eel/eel-glib-extensions.h>
#include <eel/eel-gtk-extensions.h>
#include <eel/eel-image-table.h>
#include <eel/eel-labeled-image.h>
#include <eel/eel-stock-dialogs.h>
#include <eel/eel-vfs-extensions.h>
#include <eel/eel-xml-extensions.h>
#include <libcaja-private/caja-customization-data.h>
#include <libcaja-private/caja-directory.h>
#include <libcaja-private/caja-emblem-utils.h>
#include <libcaja-private/caja-file-utilities.h>
#include <libcaja-private/caja-file.h>
#include <libcaja-private/caja-global-preferences.h>
#include <libcaja-private/caja-metadata.h>
#include <libcaja-private/caja-signaller.h>
#include "caja-property-browser.h"
Macros
#define BROWSER_CATEGORIES_FILE_NAME "browser.xml"
#define PROPERTY_BROWSER_WIDTH 540
#define PROPERTY_BROWSER_HEIGHT 340
#define MAX_EMBLEM_HEIGHT 52
#define STANDARD_BUTTON_IMAGE_HEIGHT 42
#define MAX_ICON_WIDTH 63
#define MAX_ICON_HEIGHT 63
#define COLOR_SQUARE_SIZE 48
#define LABELED_IMAGE_SPACING 2
#define IMAGE_TABLE_X_SPACING 6
#define IMAGE_TABLE_Y_SPACING 4
#define ERASE_OBJECT_NAME "erase.png"
Enumerations
enum CajaPropertyType { CAJA_PROPERTY_NONE , CAJA_PROPERTY_PATTERN , CAJA_PROPERTY_COLOR , CAJA_PROPERTY_EMBLEM }
enum { PROPERTY_TYPE }
Functions
CajaPropertyBrowser * caja_property_browser_new (GdkScreen *screen)
void caja_property_browser_show (GdkScreen *screen)
void caja_property_browser_set_path (CajaPropertyBrowser *property_browser, const char *new_path)
Macro Definition Documentation
BROWSER_CATEGORIES_FILE_NAME
#define BROWSER_CATEGORIES_FILE_NAME "browser.xml"
Definition at line 172 of file caja-property-browser.c.
COLOR_SQUARE_SIZE
#define COLOR_SQUARE_SIZE 48
Definition at line 181 of file caja-property-browser.c.
ERASE_OBJECT_NAME
#define ERASE_OBJECT_NAME "erase.png"
Definition at line 187 of file caja-property-browser.c.
IMAGE_TABLE_X_SPACING
#define IMAGE_TABLE_X_SPACING 6
Definition at line 184 of file caja-property-browser.c.
IMAGE_TABLE_Y_SPACING
#define IMAGE_TABLE_Y_SPACING 4
Definition at line 185 of file caja-property-browser.c.
LABELED_IMAGE_SPACING
#define LABELED_IMAGE_SPACING 2
Definition at line 183 of file caja-property-browser.c.
MAX_EMBLEM_HEIGHT
#define MAX_EMBLEM_HEIGHT 52
Definition at line 176 of file caja-property-browser.c.
MAX_ICON_HEIGHT
#define MAX_ICON_HEIGHT 63
Definition at line 180 of file caja-property-browser.c.
MAX_ICON_WIDTH
#define MAX_ICON_WIDTH 63
Definition at line 179 of file caja-property-browser.c.
PROPERTY_BROWSER_HEIGHT
#define PROPERTY_BROWSER_HEIGHT 340
Definition at line 175 of file caja-property-browser.c.
PROPERTY_BROWSER_WIDTH
#define PROPERTY_BROWSER_WIDTH 540
Definition at line 174 of file caja-property-browser.c.
STANDARD_BUTTON_IMAGE_HEIGHT
#define STANDARD_BUTTON_IMAGE_HEIGHT 42
Definition at line 177 of file caja-property-browser.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROPERTY_TYPE
Definition at line 189 of file caja-property-browser.c.
CajaPropertyType
enum CajaPropertyType
Enumerator
CAJA_PROPERTY_NONE
CAJA_PROPERTY_PATTERN
CAJA_PROPERTY_COLOR
CAJA_PROPERTY_EMBLEM
Definition at line 65 of file caja-property-browser.c.
Function Documentation
caja_property_browser_new()
CajaPropertyBrowser * caja_property_browser_new (GdkScreen * screen)
Definition at line 454 of file caja-property-browser.c.
References CAJA_PROPERTY_BROWSER, caja_property_browser_get_type(), and NULL.
Referenced by caja_property_browser_show().
caja_property_browser_set_path()
void caja_property_browser_set_path (CajaPropertyBrowser * property_browser, const char * new_path)
Definition at line 2485 of file caja-property-browser.c.
References CajaPropertyBrowser::details.
caja_property_browser_show()
void caja_property_browser_show (GdkScreen * screen)
Definition at line 470 of file caja-property-browser.c.
References caja_property_browser_new(), and NULL.