MATE Desktop Environment: caja-connect-server-dialog.c File Reference
caja-connect-server-dialog.c File Reference
#include <config.h>
#include <string.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <eel/eel-stock-dialogs.h>
#include <libcaja-private/caja-global-preferences.h>
#include <libcaja-private/caja-icon-names.h>
#include "caja-connect-server-dialog.h"
#include "caja-application.h"
#include "caja-bookmark-list.h"
#include "caja-connect-server-operation.h"
#include "caja-window.h"
Enumerations
enum { COL_TYPE_COMBO_INDEX = 0 , COL_TYPE_COMBO_DESCRIPTION , COL_TYPE_COMBO_NUM }
enum {
DEFAULT_METHOD = (1 << 0) , SHOW_SHARE = (1 << 1) , SHOW_PORT = (1 << 2) , SHOW_USER = (1 << 3) ,
SHOW_DOMAIN = (1 << 4) , IS_ANONYMOUS = (1 << 5)
}
Functions
G_DEFINE_TYPE_WITH_PRIVATE (CajaConnectServerDialog, caja_connect_server_dialog, GTK_TYPE_DIALOG)
GtkWidget * caja_connect_server_dialog_new (CajaWindow *window)
gboolean caja_connect_server_dialog_fill_details_finish (CajaConnectServerDialog *self, GAsyncResult *result)
void caja_connect_server_dialog_fill_details_async (CajaConnectServerDialog *self, GMountOperation *operation, const gchar *default_user, const gchar *default_domain, GAskPasswordFlags flags, GAsyncReadyCallback callback, gpointer user_data)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COL_TYPE_COMBO_INDEX
COL_TYPE_COMBO_DESCRIPTION
COL_TYPE_COMBO_NUM
Definition at line 95 of file caja-connect-server-dialog.c.
anonymous enum
anonymous enum
Enumerator
DEFAULT_METHOD
SHOW_SHARE
SHOW_PORT
SHOW_USER
SHOW_DOMAIN
IS_ANONYMOUS
Definition at line 109 of file caja-connect-server-dialog.c.
Function Documentation
caja_connect_server_dialog_fill_details_async()
void caja_connect_server_dialog_fill_details_async (CajaConnectServerDialog * self, GMountOperation * operation, const gchar * default_user, const gchar * default_domain, GAskPasswordFlags flags, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 1204 of file caja-connect-server-dialog.c.
References caja_connect_server_dialog_fill_details_async(), _CajaConnectServerDialog::details, NULL, TRUE, and user_data.
Referenced by caja_connect_server_dialog_fill_details_async().
caja_connect_server_dialog_fill_details_finish()
gboolean caja_connect_server_dialog_fill_details_finish (CajaConnectServerDialog * self, GAsyncResult * result)
Definition at line 1197 of file caja-connect-server-dialog.c.
caja_connect_server_dialog_new()
GtkWidget * caja_connect_server_dialog_new (CajaWindow * window)
Definition at line 1178 of file caja-connect-server-dialog.c.
References CAJA_CONNECT_SERVER_DIALOG, CAJA_TYPE_CONNECT_SERVER_DIALOG, _CajaConnectServerDialog::details, and NULL.
Referenced by main().
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (CajaConnectServerDialog , caja_connect_server_dialog , GTK_TYPE_DIALOG)
Definition at line 82 of file caja-connect-server-dialog.c.
References RESPONSE_CONNECT.