MATE Desktop Environment: caja-query.h File Reference
caja-query.h File Reference
#include <glib-object.h>
Classes
struct CajaQuery
struct CajaQueryClass
Macros
#define CAJA_TYPE_QUERY (caja_query_get_type ())
#define CAJA_QUERY(obj)
#define CAJA_QUERY_CLASS(klass)
#define CAJA_IS_QUERY(obj)
#define CAJA_IS_QUERY_CLASS(klass)
#define CAJA_QUERY_GET_CLASS(obj)
Typedefs
typedef struct CajaQueryDetails CajaQueryDetails
typedef struct CajaQuery CajaQuery
Functions
GType caja_query_get_type (void)
gboolean caja_query_enabled (void)
CajaQuery * caja_query_new (void)
char * caja_query_get_text (CajaQuery *query)
void caja_query_set_text (CajaQuery *query, const char *text)
char * caja_query_get_location (CajaQuery *query)
void caja_query_set_location (CajaQuery *query, const char *uri)
GList * caja_query_get_tags (CajaQuery *query)
void caja_query_set_tags (CajaQuery *query, GList *tags)
void caja_query_add_tag (CajaQuery *query, const char *tag)
GList * caja_query_get_mime_types (CajaQuery *query)
void caja_query_set_mime_types (CajaQuery *query, GList *mime_types)
void caja_query_add_mime_type (CajaQuery *query, const char *mime_type)
char * caja_query_to_readable_string (CajaQuery *query)
CajaQuery * caja_query_load (char *file)
gboolean caja_query_save (CajaQuery *query, char *file)
gint64 caja_query_get_timestamp (CajaQuery *query)
void caja_query_set_timestamp (CajaQuery *query, gint64 sec)
gint64 caja_query_get_size (CajaQuery *query)
void caja_query_set_size (CajaQuery *query, gint64 size)
char * caja_query_get_contained_text (CajaQuery *query)
void caja_query_set_contained_text (CajaQuery *query, const char *text)
Macro Definition Documentation
CAJA_IS_QUERY
#define CAJA_IS_QUERY (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_QUERY))
Definition at line 32 of file caja-query.h.
CAJA_IS_QUERY_CLASS
#define CAJA_IS_QUERY_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_QUERY))
Definition at line 33 of file caja-query.h.
CAJA_QUERY
#define CAJA_QUERY (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_QUERY, CajaQuery))
Definition at line 30 of file caja-query.h.
CAJA_QUERY_CLASS
#define CAJA_QUERY_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_QUERY, CajaQueryClass))
Definition at line 31 of file caja-query.h.
CAJA_QUERY_GET_CLASS
#define CAJA_QUERY_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_QUERY, CajaQueryClass))
Definition at line 34 of file caja-query.h.
CAJA_TYPE_QUERY
#define CAJA_TYPE_QUERY (caja_query_get_type ())
Definition at line 29 of file caja-query.h.
Referenced by caja_query_new().
Typedef Documentation
CajaQuery
typedef struct CajaQuery CajaQuery
CajaQueryDetails
typedef struct CajaQueryDetails CajaQueryDetails
Definition at line 36 of file caja-query.h.
Function Documentation
caja_query_add_mime_type()
void caja_query_add_mime_type (CajaQuery * query, const char * mime_type)
Definition at line 129 of file caja-query.c.
References CajaQuery::details, and mime_type.
caja_query_add_tag()
void caja_query_add_tag (CajaQuery * query, const char * tag)
Definition at line 149 of file caja-query.c.
References CajaQuery::details.
caja_query_enabled()
gboolean caja_query_enabled (void)
References mime_type.
caja_query_get_contained_text()
char * caja_query_get_contained_text (CajaQuery * query)
Definition at line 482 of file caja-query.c.
References CajaQuery::details.
caja_query_get_location()
char * caja_query_get_location (CajaQuery * query)
Definition at line 103 of file caja-query.c.
References CajaQuery::details.
caja_query_get_mime_types()
GList * caja_query_get_mime_types (CajaQuery * query)
Definition at line 116 of file caja-query.c.
References CajaQuery::details, and NULL.
caja_query_get_size()
gint64 caja_query_get_size (CajaQuery * query)
Definition at line 471 of file caja-query.c.
References CajaQuery::details.
caja_query_get_tags()
GList * caja_query_get_tags (CajaQuery * query)
Definition at line 136 of file caja-query.c.
References CajaQuery::details, and NULL.
caja_query_get_text()
char * caja_query_get_text (CajaQuery * query)
Definition at line 90 of file caja-query.c.
References CajaQuery::details.
Referenced by caja_query_editor_set_query().
caja_query_get_timestamp()
gint64 caja_query_get_timestamp (CajaQuery * query)
Definition at line 461 of file caja-query.c.
References CajaQuery::details.
caja_query_get_type()
GType caja_query_get_type (void)
caja_query_load()
CajaQuery * caja_query_load (char * file)
Definition at line 349 of file caja-query.c.
References NULL.
Referenced by caja_search_directory_new_from_saved_search().
caja_query_new()
CajaQuery * caja_query_new (void)
Definition at line 84 of file caja-query.c.
References CAJA_TYPE_QUERY, and NULL.
Referenced by caja_query_editor_get_query(), caja_search_bar_get_query(), main(), and main().
caja_query_save()
gboolean caja_query_save (CajaQuery * query, char * file)
Definition at line 437 of file caja-query.c.
References FALSE, NULL, and TRUE.
Referenced by caja_search_directory_save_to_file().
caja_query_set_contained_text()
void caja_query_set_contained_text (CajaQuery * query, const char * text)
Definition at line 476 of file caja-query.c.
References CajaQuery::details.
caja_query_set_location()
void caja_query_set_location (CajaQuery * query, const char * uri)
Definition at line 109 of file caja-query.c.
References CajaQuery::details.
caja_query_set_mime_types()
void caja_query_set_mime_types (CajaQuery * query, GList * mime_types)
Definition at line 122 of file caja-query.c.
References CajaQuery::details, and NULL.
caja_query_set_size()
void caja_query_set_size (CajaQuery * query, gint64 size)
Definition at line 466 of file caja-query.c.
References CajaQuery::details.
caja_query_set_tags()
void caja_query_set_tags (CajaQuery * query, GList * tags)
Definition at line 142 of file caja-query.c.
References CajaQuery::details, and NULL.
caja_query_set_text()
void caja_query_set_text (CajaQuery * query, const char * text)
Definition at line 96 of file caja-query.c.
References CajaQuery::details.
Referenced by caja_query_editor_get_query(), caja_search_bar_get_query(), main(), and main().
caja_query_set_timestamp()
void caja_query_set_timestamp (CajaQuery * query, gint64 sec)
Definition at line 456 of file caja-query.c.
References CajaQuery::details.
caja_query_to_readable_string()
char * caja_query_to_readable_string (CajaQuery * query)
Definition at line 159 of file caja-query.c.
References _, and CajaQuery::details.
Referenced by caja_search_directory_file_update_display_name().