MATE Desktop Environment: caja-autorun.c File Reference
caja-autorun.c File Reference
#include <config.h>
#include <string.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
#include <gio/gdesktopappinfo.h>
#include <X11/XKBlib.h>
#include <gdk/gdkkeysyms.h>
#include <cairo-gobject.h>
#include <eel/eel-glib-extensions.h>
#include <eel/eel-stock-dialogs.h>
#include "caja-icon-info.h"
#include "caja-global-preferences.h"
#include "caja-file-operations.h"
#include "caja-autorun.h"
#include "caja-program-choosing.h"
#include "caja-open-with-dialog.h"
#include "caja-desktop-icon-file.h"
#include "caja-file-utilities.h"
Macros
#define INHIBIT_AUTORUN_SECONDS 10
Enumerations
enum {
AUTORUN_ASK , AUTORUN_IGNORE , AUTORUN_APP , AUTORUN_OPEN_FOLDER ,
AUTORUN_SEP , AUTORUN_OTHER_APP
}
enum {
COLUMN_AUTORUN_SURFACE , COLUMN_AUTORUN_NAME , COLUMN_AUTORUN_APP_INFO , COLUMN_AUTORUN_X_CONTENT_TYPE ,
COLUMN_AUTORUN_ITEM_TYPE
}
enum { AUTORUN_DIALOG_RESPONSE_EJECT = 0 }
Functions
void caja_autorun_get_preferences (const char *x_content_type, gboolean *pref_start_app, gboolean *pref_ignore, gboolean *pref_open_folder)
void caja_autorun_set_preferences (const char *x_content_type, gboolean pref_start_app, gboolean pref_ignore, gboolean pref_open_folder)
void caja_autorun_prepare_combo_box (GtkWidget *combo_box, const char *x_content_type, gboolean include_ask, gboolean include_open_with_other_app, gboolean update_settings, CajaAutorunComboBoxChanged changed_cb, gpointer user_data)
void caja_autorun_launch_for_mount (GMount *mount, GAppInfo *app_info)
void caja_autorun (GMount *mount, CajaAutorunOpenWindow open_window_func, gpointer user_data)
void caja_autorun_get_x_content_types_for_mount_async (GMount *mount, CajaAutorunGetContent callback, GCancellable *cancellable, gpointer user_data)
char ** caja_autorun_get_cached_x_content_types_for_mount (GMount *mount)
void caja_allow_autorun_for_volume (GVolume *volume)
void caja_allow_autorun_for_volume_finish (GVolume *volume)
Macro Definition Documentation
INHIBIT_AUTORUN_SECONDS
#define INHIBIT_AUTORUN_SECONDS 10
Definition at line 1397 of file caja-autorun.c.
Referenced by caja_allow_autorun_for_volume_finish().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COLUMN_AUTORUN_SURFACE
COLUMN_AUTORUN_NAME
COLUMN_AUTORUN_APP_INFO
COLUMN_AUTORUN_X_CONTENT_TYPE
COLUMN_AUTORUN_ITEM_TYPE
Definition at line 57 of file caja-autorun.c.
anonymous enum
anonymous enum
Enumerator
AUTORUN_DIALOG_RESPONSE_EJECT
Definition at line 785 of file caja-autorun.c.
anonymous enum
anonymous enum
Enumerator
AUTORUN_ASK
AUTORUN_IGNORE
AUTORUN_APP
AUTORUN_OPEN_FOLDER
AUTORUN_SEP
AUTORUN_OTHER_APP
Definition at line 48 of file caja-autorun.c.
Function Documentation
caja_allow_autorun_for_volume()
void caja_allow_autorun_for_volume (GVolume * volume)
Definition at line 1392 of file caja-autorun.c.
Referenced by caja_file_operations_mount_volume_full().
caja_allow_autorun_for_volume_finish()
void caja_allow_autorun_for_volume_finish (GVolume * volume)
Definition at line 1400 of file caja-autorun.c.
References INHIBIT_AUTORUN_SECONDS, and NULL.
caja_autorun()
void caja_autorun (GMount * mount, CajaAutorunOpenWindow open_window_func, gpointer user_data)
Definition at line 1272 of file caja-autorun.c.
References caja_media_preferences, CAJA_PREFERENCES_MEDIA_AUTORUN_NEVER, data, FALSE, NULL, and user_data.
caja_autorun_get_cached_x_content_types_for_mount()
char ** caja_autorun_get_cached_x_content_types_for_mount (GMount * mount)
Definition at line 1364 of file caja-autorun.c.
References NULL.
caja_autorun_get_preferences()
void caja_autorun_get_preferences (const char * x_content_type, gboolean * pref_start_app, gboolean * pref_ignore, gboolean * pref_open_folder)
Definition at line 71 of file caja-autorun.c.
References caja_media_preferences, CAJA_PREFERENCES_MEDIA_AUTORUN_X_CONTENT_IGNORE, CAJA_PREFERENCES_MEDIA_AUTORUN_X_CONTENT_OPEN_FOLDER, CAJA_PREFERENCES_MEDIA_AUTORUN_X_CONTENT_START_APP, eel_g_strv_find(), FALSE, and NULL.
Referenced by caja_autorun_prepare_combo_box().
caja_autorun_get_x_content_types_for_mount_async()
void caja_autorun_get_x_content_types_for_mount_async (GMount * mount, CajaAutorunGetContent callback, GCancellable * cancellable, gpointer user_data)
Definition at line 1325 of file caja-autorun.c.
References data, FALSE, NULL, and user_data.
caja_autorun_launch_for_mount()
void caja_autorun_launch_for_mount (GMount * mount, GAppInfo * app_info)
Definition at line 810 of file caja-autorun.c.
References caja_file_get(), caja_launch_application(), and NULL.
caja_autorun_prepare_combo_box()
void caja_autorun_prepare_combo_box (GtkWidget * combo_box, const char * x_content_type, gboolean include_ask, gboolean include_open_with_other_app, gboolean update_settings, CajaAutorunComboBoxChanged changed_cb, gpointer user_data)
Definition at line 461 of file caja-autorun.c.
References _, AUTORUN_APP, AUTORUN_ASK, AUTORUN_IGNORE, AUTORUN_OPEN_FOLDER, AUTORUN_OTHER_APP, AUTORUN_SEP, caja_autorun_get_preferences(), caja_get_icon_size_for_stock_size(), caja_icon_info_get_surface_at_size(), caja_icon_info_lookup(), COLUMN_AUTORUN_APP_INFO, COLUMN_AUTORUN_ITEM_TYPE, COLUMN_AUTORUN_NAME, COLUMN_AUTORUN_SURFACE, COLUMN_AUTORUN_X_CONTENT_TYPE, data, FALSE, NULL, TRUE, and user_data.
caja_autorun_set_preferences()
void caja_autorun_set_preferences (const char * x_content_type, gboolean pref_start_app, gboolean pref_ignore, gboolean pref_open_folder)
Definition at line 151 of file caja-autorun.c.
References caja_media_preferences, CAJA_PREFERENCES_MEDIA_AUTORUN_X_CONTENT_IGNORE, CAJA_PREFERENCES_MEDIA_AUTORUN_X_CONTENT_OPEN_FOLDER, CAJA_PREFERENCES_MEDIA_AUTORUN_X_CONTENT_START_APP, and NULL.