MATE Desktop Environment: caja-actions-new.c File Reference
caja-actions-new.c File Reference
#include <errno.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <glib/gprintf.h>
#include <locale.h>
#include <stdlib.h>
#include <api/na-core-utils.h>
#include <api/na-iio-provider.h>
#include <api/na-object-api.h>
#include <core/na-io-provider.h>
#include <core/na-exporter.h>
#include <core/na-updater.h>
#include "console-utils.h"
Macros
#define CANNOT_BOTH _("Error: '%s' and '%s' options cannot both be specified\n")
#define DEPRECATED _("'%s' option is deprecated, see %s\n")
Functions
int main (int argc, char **argv)
Variables
NADataGroup action_data_groups []
NADataGroup profile_data_groups []
Macro Definition Documentation
CANNOT_BOTH
#define CANNOT_BOTH _("Error: '%s' and '%s' options cannot both be specified\n")
Definition at line 160 of file caja-actions-new.c.
Referenced by main().
DEPRECATED
#define DEPRECATED _("'%s' option is deprecated, see %s\n")
Definition at line 161 of file caja-actions-new.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 171 of file caja-actions-new.c.
References _, action, CANNOT_BOTH, console_init_log_handler(), error, FALSE, label, na_core_utils_print_version(), na_core_utils_slist_free(), NULL, and TRUE.
Variable Documentation
action_data_groups
NADataGroup action_data_groups[] extern
Definition at line 439 of file na-object-action-factory.c.
profile_data_groups
NADataGroup profile_data_groups[] extern
Definition at line 314 of file na-object-profile-factory.c.