MATE Desktop Environment: caja-file-dnd.c File Reference
caja-file-dnd.c File Reference
#include <config.h>
#include "caja-file-dnd.h"
#include "caja-desktop-icon-file.h"
#include "caja-dnd.h"
#include "caja-directory.h"
#include "caja-file-utilities.h"
#include <string.h>
Functions
gboolean caja_drag_can_accept_item (CajaFile *drop_target_item, const char *item_uri)
gboolean caja_drag_can_accept_items (CajaFile *drop_target_item, const GList *items)
gboolean caja_drag_can_accept_info (CajaFile *drop_target_item, CajaIconDndTargetType drag_type, const GList *items)
void caja_drag_file_receive_dropped_keyword (CajaFile *file, const char *keyword)
Function Documentation
caja_drag_can_accept_info()
gboolean caja_drag_can_accept_info (CajaFile * drop_target_item, CajaIconDndTargetType drag_type, const GList * items)
Definition at line 116 of file caja-file-dnd.c.
References caja_drag_can_accept_items(), CAJA_ICON_DND_BGIMAGE, CAJA_ICON_DND_COLOR, CAJA_ICON_DND_KEYWORD, CAJA_ICON_DND_MATE_ICON_LIST, CAJA_ICON_DND_NETSCAPE_URL, CAJA_ICON_DND_RAW, CAJA_ICON_DND_RESET_BACKGROUND, CAJA_ICON_DND_ROOTWINDOW_DROP, CAJA_ICON_DND_TEXT, CAJA_ICON_DND_URI_LIST, CAJA_ICON_DND_XDNDDIRECTSAVE, FALSE, and TRUE.
caja_drag_can_accept_item()
gboolean caja_drag_can_accept_item (CajaFile * drop_target_item, const char * item_uri)
Definition at line 76 of file caja-file-dnd.c.
References caja_file_matches_uri(), and FALSE.
Referenced by caja_drag_can_accept_items(), and fm_directory_view_can_accept_item().
caja_drag_can_accept_items()
gboolean caja_drag_can_accept_items (CajaFile * drop_target_item, const GList * items)
Definition at line 89 of file caja-file-dnd.c.
References caja_drag_can_accept_item(), CAJA_IS_FILE, FALSE, NULL, and TRUE.
Referenced by caja_drag_can_accept_info().
caja_drag_file_receive_dropped_keyword()
void caja_drag_file_receive_dropped_keyword (CajaFile * file, const char * keyword)
Definition at line 153 of file caja-file-dnd.c.
References CAJA_FILE_DND_ERASE_KEYWORD, caja_file_get_keywords(), caja_file_set_keywords(), CAJA_IS_FILE, and NULL.