MATE Desktop Environment: caja-directory-private.h File Reference
caja-directory-private.h File Reference
#include <gio/gio.h>
#include <libxml/tree.h>
#include <eel/eel-vfs-extensions.h>
#include <libcaja-extension/caja-info-provider.h>
#include "caja-directory.h"
#include "caja-file-queue.h"
#include "caja-file.h"
#include "caja-monitor.h"
Classes
struct _CajaDirectoryPrivate
Macros
#define REQUEST_WANTS_TYPE(request, type)
#define REQUEST_SET_TYPE(request, type)
Typedefs
typedef struct LinkInfoReadState LinkInfoReadState
typedef struct TopLeftTextReadState TopLeftTextReadState
typedef struct FileMonitors FileMonitors
typedef struct DirectoryLoadState DirectoryLoadState
typedef struct DirectoryCountState DirectoryCountState
typedef struct DeepCountState DeepCountState
typedef struct GetInfoState GetInfoState
typedef struct NewFilesState NewFilesState
typedef struct MimeListState MimeListState
typedef struct ThumbnailState ThumbnailState
typedef struct MountState MountState
typedef struct FilesystemInfoState FilesystemInfoState
typedef guint32 Request
typedef gint32 RequestCounter[REQUEST_TYPE_LAST]
Enumerations
enum RequestType {
REQUEST_LINK_INFO , REQUEST_DEEP_COUNT , REQUEST_DIRECTORY_COUNT , REQUEST_FILE_INFO ,
REQUEST_FILE_LIST , REQUEST_MIME_LIST , REQUEST_TOP_LEFT_TEXT , REQUEST_LARGE_TOP_LEFT_TEXT ,
REQUEST_EXTENSION_INFO , REQUEST_THUMBNAIL , REQUEST_MOUNT , REQUEST_FILESYSTEM_INFO ,
REQUEST_TYPE_LAST
}
Functions
CajaDirectory * caja_directory_get_existing (GFile *location)
void caja_directory_async_state_changed (CajaDirectory *directory)
void caja_directory_call_when_ready_internal (CajaDirectory *directory, CajaFile *file, CajaFileAttributes file_attributes, gboolean wait_for_file_list, CajaDirectoryCallback directory_callback, CajaFileCallback file_callback, gpointer callback_data)
gboolean caja_directory_check_if_ready_internal (CajaDirectory *directory, CajaFile *file, CajaFileAttributes file_attributes)
void caja_directory_cancel_callback_internal (CajaDirectory *directory, CajaFile *file, CajaDirectoryCallback directory_callback, CajaFileCallback file_callback, gpointer callback_data)
void caja_directory_monitor_add_internal (CajaDirectory *directory, CajaFile *file, gconstpointer client, gboolean monitor_hidden_files, CajaFileAttributes attributes, CajaDirectoryCallback callback, gpointer callback_data)
void caja_directory_monitor_remove_internal (CajaDirectory *directory, CajaFile *file, gconstpointer client)
void caja_directory_get_info_for_new_files (CajaDirectory *directory, GList *vfs_uris)
CajaFile * caja_directory_get_existing_corresponding_file (CajaDirectory *directory)
void caja_directory_invalidate_count_and_mime_list (CajaDirectory *directory)
gboolean caja_directory_is_file_list_monitored (CajaDirectory *directory)
gboolean caja_directory_is_anyone_monitoring_file_list (CajaDirectory *directory)
gboolean caja_directory_has_active_request_for_file (CajaDirectory *directory, CajaFile *file)
void caja_directory_remove_file_monitor_link (CajaDirectory *directory, GList *link)
void caja_directory_schedule_dequeue_pending (CajaDirectory *directory)
void caja_directory_stop_monitoring_file_list (CajaDirectory *directory)
void caja_directory_cancel (CajaDirectory *directory)
void caja_async_destroying_file (CajaFile *file)
void caja_directory_force_reload_internal (CajaDirectory *directory, CajaFileAttributes file_attributes)
void caja_directory_cancel_loading_file_attributes (CajaDirectory *directory, CajaFile *file, CajaFileAttributes file_attributes)
void caja_directory_emit_files_added (CajaDirectory *directory, GList *added_files)
void caja_directory_emit_files_changed (CajaDirectory *directory, GList *changed_files)
void caja_directory_emit_change_signals (CajaDirectory *directory, GList *changed_files)
void emit_change_signals_for_all_files (CajaDirectory *directory)
void emit_change_signals_for_all_files_in_all_directories (void)
void caja_directory_emit_done_loading (CajaDirectory *directory)
void caja_directory_emit_load_error (CajaDirectory *directory, GError *error)
CajaDirectory * caja_directory_get_internal (GFile *location, gboolean create)
char * caja_directory_get_name_for_self_as_new_file (CajaDirectory *directory)
Request caja_directory_set_up_request (CajaFileAttributes file_attributes)
CajaFile * caja_directory_find_file_by_name (CajaDirectory *directory, const char *filename)
void caja_directory_add_file (CajaDirectory *directory, CajaFile *file)
void caja_directory_remove_file (CajaDirectory *directory, CajaFile *file)
FileMonitors * caja_directory_remove_file_monitors (CajaDirectory *directory, CajaFile *file)
void caja_directory_add_file_monitors (CajaDirectory *directory, CajaFile *file, FileMonitors *monitors)
GList * caja_directory_begin_file_name_change (CajaDirectory *directory, CajaFile *file)
void caja_directory_end_file_name_change (CajaDirectory *directory, CajaFile *file, GList *node)
void caja_directory_moved (const char *from_uri, const char *to_uri)
void caja_directory_add_file_to_work_queue (CajaDirectory *directory, CajaFile *file)
void caja_directory_remove_file_from_work_queue (CajaDirectory *directory, CajaFile *file)
int caja_directory_number_outstanding (void)
Macro Definition Documentation
REQUEST_SET_TYPE
#define REQUEST_SET_TYPE (request, type)
Value:
(request) |= (1<<(type))
Definition at line 75 of file caja-directory-private.h.
Referenced by caja_directory_call_when_ready_internal(), caja_directory_monitor_add_internal(), and caja_directory_set_up_request().
REQUEST_WANTS_TYPE
#define REQUEST_WANTS_TYPE (request, type)
Value:
((request) & (1<<(type)))
Definition at line 74 of file caja-directory-private.h.
Referenced by caja_directory_cancel_loading_file_attributes(), caja_directory_monitor_add_internal(), and caja_file_invalidate_attributes_internal().
Typedef Documentation
DeepCountState
typedef struct DeepCountState DeepCountState
Definition at line 45 of file caja-directory-private.h.
DirectoryCountState
typedef struct DirectoryCountState DirectoryCountState
Definition at line 44 of file caja-directory-private.h.
DirectoryLoadState
typedef struct DirectoryLoadState DirectoryLoadState
Definition at line 43 of file caja-directory-private.h.
FileMonitors
typedef struct FileMonitors FileMonitors
Definition at line 42 of file caja-directory-private.h.
FilesystemInfoState
typedef struct FilesystemInfoState FilesystemInfoState
Definition at line 51 of file caja-directory-private.h.
GetInfoState
typedef struct GetInfoState GetInfoState
Definition at line 46 of file caja-directory-private.h.
LinkInfoReadState
typedef struct LinkInfoReadState LinkInfoReadState
Definition at line 40 of file caja-directory-private.h.
MimeListState
typedef struct MimeListState MimeListState
Definition at line 48 of file caja-directory-private.h.
MountState
typedef struct MountState MountState
Definition at line 50 of file caja-directory-private.h.
NewFilesState
typedef struct NewFilesState NewFilesState
Definition at line 47 of file caja-directory-private.h.
Request
typedef guint32 Request
Definition at line 71 of file caja-directory-private.h.
RequestCounter
typedef gint32 RequestCounter[REQUEST_TYPE_LAST]
Definition at line 72 of file caja-directory-private.h.
ThumbnailState
typedef struct ThumbnailState ThumbnailState
Definition at line 49 of file caja-directory-private.h.
TopLeftTextReadState
typedef struct TopLeftTextReadState TopLeftTextReadState
Definition at line 41 of file caja-directory-private.h.
Enumeration Type Documentation
RequestType
enum RequestType
Enumerator
REQUEST_LINK_INFO
REQUEST_DEEP_COUNT
REQUEST_DIRECTORY_COUNT
REQUEST_FILE_INFO
REQUEST_FILE_LIST
REQUEST_MIME_LIST
REQUEST_TOP_LEFT_TEXT
REQUEST_LARGE_TOP_LEFT_TEXT
REQUEST_EXTENSION_INFO
REQUEST_THUMBNAIL
REQUEST_MOUNT
REQUEST_FILESYSTEM_INFO
REQUEST_TYPE_LAST
Definition at line 53 of file caja-directory-private.h.
Function Documentation
caja_async_destroying_file()
void caja_async_destroying_file (CajaFile * file)
Definition at line 1644 of file caja-directory-async.c.
References caja_directory_async_state_changed(), _CajaDirectoryPrivate::call_when_ready_list, _CajaDirectoryPrivate::count_in_progress, _CajaDirectoryPrivate::deep_count_file, CajaDirectory::details, CajaFile::details, _CajaFilePrivate::directory, _CajaDirectoryPrivate::extension_info_file, FALSE, _CajaDirectoryPrivate::filesystem_info_state, _CajaDirectoryPrivate::get_info_file, _CajaDirectoryPrivate::link_info_read_state, _CajaDirectoryPrivate::mime_list_in_progress, _CajaDirectoryPrivate::monitor_list, _CajaDirectoryPrivate::mount_state, NULL, _CajaDirectoryPrivate::thumbnail_state, _CajaDirectoryPrivate::top_left_read_state, and TRUE.
caja_directory_add_file()
void caja_directory_add_file (CajaDirectory * directory, CajaFile * file)
Definition at line 557 of file caja-directory.c.
References caja_directory_add_file_to_work_queue(), caja_directory_has_active_request_for_file(), caja_directory_is_file_list_monitored(), caja_file_ref(), CAJA_IS_DIRECTORY, CAJA_IS_FILE, _CajaDirectoryPrivate::confirmed_file_count, CajaDirectory::details, CajaFile::details, FALSE, _CajaDirectoryPrivate::file_list, _CajaFilePrivate::name, NULL, and TRUE.
Referenced by caja_desktop_icon_file_new(), and caja_file_update_name_and_directory().
caja_directory_add_file_monitors()
void caja_directory_add_file_monitors (CajaDirectory * directory, CajaFile * file, FileMonitors * monitors)
Definition at line 1254 of file caja-directory-async.c.
References caja_directory_add_file_to_work_queue(), caja_directory_async_state_changed(), CAJA_IS_DIRECTORY, CAJA_IS_FILE, CajaDirectory::details, CajaFile::details, _CajaFilePrivate::directory, _CajaDirectoryPrivate::monitor_counters, _CajaDirectoryPrivate::monitor_list, and NULL.
Referenced by caja_file_update_name_and_directory().
caja_directory_add_file_to_work_queue()
void caja_directory_add_file_to_work_queue (CajaDirectory * directory, CajaFile * file)
Definition at line 5271 of file caja-directory-async.c.
References caja_file_queue_enqueue(), CajaDirectory::details, CajaFile::details, _CajaFilePrivate::directory, and _CajaDirectoryPrivate::high_priority_queue.
Referenced by caja_directory_add_file(), caja_directory_add_file_monitors(), caja_directory_call_when_ready_internal(), caja_directory_monitor_add_internal(), caja_file_invalidate_attributes(), and caja_file_recompute_deep_counts().
caja_directory_async_state_changed()
void caja_directory_async_state_changed (CajaDirectory * directory)
Definition at line 5006 of file caja-directory-async.c.
References caja_directory_ref(), caja_directory_unref(), CajaDirectory::details, FALSE, _CajaDirectoryPrivate::in_async_service_loop, _CajaDirectoryPrivate::state_changed, and TRUE.
Referenced by caja_async_destroying_file(), caja_directory_add_file_monitors(), caja_directory_call_when_ready_internal(), caja_directory_cancel_callback_internal(), caja_directory_cancel_loading_file_attributes(), caja_directory_force_reload_internal(), caja_directory_monitor_add_internal(), caja_directory_monitor_remove_internal(), caja_directory_remove_file_monitors(), caja_file_invalidate_attributes(), and caja_file_recompute_deep_counts().
caja_directory_begin_file_name_change()
GList * caja_directory_begin_file_name_change (CajaDirectory * directory, CajaFile * file)
Definition at line 630 of file caja-directory.c.
caja_directory_call_when_ready_internal()
void caja_directory_call_when_ready_internal (CajaDirectory * directory, CajaFile * file, CajaFileAttributes file_attributes, gboolean wait_for_file_list, CajaDirectoryCallback directory_callback, CajaFileCallback file_callback, gpointer callback_data)
Definition at line 1394 of file caja-directory-async.c.
References caja_directory_add_file_to_work_queue(), caja_directory_async_state_changed(), caja_directory_set_up_request(), CAJA_IS_DIRECTORY, CAJA_IS_FILE, _CajaDirectoryPrivate::call_when_ready_counters, _CajaDirectoryPrivate::call_when_ready_list, CajaDirectory::details, NULL, REQUEST_FILE_LIST, REQUEST_SET_TYPE, and TRUE.
caja_directory_cancel()
void caja_directory_cancel (CajaDirectory * directory)
Definition at line 5041 of file caja-directory-async.c.
References NULL.
caja_directory_cancel_callback_internal()
void caja_directory_cancel_callback_internal (CajaDirectory * directory, CajaFile * file, CajaDirectoryCallback directory_callback, CajaFileCallback file_callback, gpointer callback_data)
Definition at line 1507 of file caja-directory-async.c.
References caja_directory_async_state_changed(), CAJA_IS_DIRECTORY, CAJA_IS_FILE, _CajaDirectoryPrivate::call_when_ready_list, CajaDirectory::details, and NULL.
caja_directory_cancel_loading_file_attributes()
void caja_directory_cancel_loading_file_attributes (CajaDirectory * directory, CajaFile * file, CajaFileAttributes file_attributes)
Definition at line 5220 of file caja-directory-async.c.
References caja_directory_async_state_changed(), caja_directory_remove_file_from_work_queue(), caja_directory_set_up_request(), REQUEST_DEEP_COUNT, REQUEST_DIRECTORY_COUNT, REQUEST_FILE_INFO, REQUEST_FILESYSTEM_INFO, REQUEST_LINK_INFO, REQUEST_MIME_LIST, REQUEST_MOUNT, REQUEST_THUMBNAIL, REQUEST_TOP_LEFT_TEXT, and REQUEST_WANTS_TYPE.
Referenced by caja_directory_notify_files_moved(), and caja_file_invalidate_attributes().
caja_directory_check_if_ready_internal()
gboolean caja_directory_check_if_ready_internal (CajaDirectory * directory, CajaFile * file, CajaFileAttributes file_attributes)
Definition at line 1467 of file caja-directory-async.c.
References caja_directory_set_up_request(), and CAJA_IS_DIRECTORY.
caja_directory_emit_change_signals()
void caja_directory_emit_change_signals (CajaDirectory * directory, GList * changed_files)
Definition at line 688 of file caja-directory.c.
References caja_directory_emit_files_changed(), caja_file_emit_changed(), and NULL.
Referenced by caja_desktop_icon_file_remove(), caja_file_changed(), and emit_change_signals_for_all_files().
caja_directory_emit_done_loading()
void caja_directory_emit_done_loading (CajaDirectory * directory)
Definition at line 701 of file caja-directory.c.
References DONE_LOADING.
caja_directory_emit_files_added()
void caja_directory_emit_files_added (CajaDirectory * directory, GList * added_files)
Definition at line 664 of file caja-directory.c.
References FILES_ADDED, and NULL.
Referenced by caja_desktop_icon_file_new().
caja_directory_emit_files_changed()
void caja_directory_emit_files_changed (CajaDirectory * directory, GList * changed_files)
Definition at line 676 of file caja-directory.c.
References FILES_CHANGED, and NULL.
Referenced by caja_directory_emit_change_signals().
caja_directory_emit_load_error()
void caja_directory_emit_load_error (CajaDirectory * directory, GError * error)
Definition at line 708 of file caja-directory.c.
References error, and LOAD_ERROR.
caja_directory_end_file_name_change()
void caja_directory_end_file_name_change (CajaDirectory * directory, CajaFile * file, GList * node)
Definition at line 638 of file caja-directory.c.
References NULL.
caja_directory_find_file_by_name()
CajaFile * caja_directory_find_file_by_name (CajaDirectory * directory, const char * filename)
Definition at line 650 of file caja-directory.c.
References CAJA_FILE, CAJA_IS_DIRECTORY, CajaDirectory::details, _CajaDirectoryPrivate::file_hash, name, and NULL.
caja_directory_force_reload_internal()
void caja_directory_force_reload_internal (CajaDirectory * directory, CajaFileAttributes file_attributes)
Definition at line 2411 of file caja-directory-async.c.
References caja_directory_async_state_changed(), caja_directory_invalidate_count_and_mime_list(), CajaDirectory::details, _CajaDirectoryPrivate::directory_loaded, and FALSE.
caja_directory_get_existing()
CajaDirectory * caja_directory_get_existing (GFile * location)
Definition at line 313 of file caja-directory.c.
References caja_directory_get_internal(), FALSE, and NULL.
caja_directory_get_existing_corresponding_file()
CajaFile * caja_directory_get_existing_corresponding_file (CajaDirectory * directory)
Definition at line 379 of file caja-directory.c.
References _CajaDirectoryPrivate::as_file, caja_directory_get_uri(), caja_file_get_existing_by_uri(), caja_file_ref(), CajaDirectory::details, and NULL.
Referenced by caja_directory_get_corresponding_file(), and caja_directory_invalidate_count_and_mime_list().
caja_directory_get_info_for_new_files()
void caja_directory_get_info_for_new_files (CajaDirectory * directory, GList * vfs_uris)
Definition at line 1607 of file caja-directory-async.c.
References CAJA_FILE_DEFAULT_ATTRIBUTES, CajaDirectory::details, _CajaDirectoryPrivate::new_files_in_progress, and NULL.
caja_directory_get_internal()
CajaDirectory * caja_directory_get_internal (GFile * location, gboolean create)
caja_directory_get_by_uri: @uri: URI of directory to get.
Get a directory given a uri. Creates the appropriate subclass given the uri mappings. Returns a referenced object, not a floating one. Unref when finished. If two windows are viewing the same uri, the directory object is shared.
Definition at line 265 of file caja-directory.c.
References caja_directory_ref(), caja_global_preferences_init(), CajaDirectory::details, _CajaDirectoryPrivate::location, and NULL.
Referenced by caja_directory_get(), caja_directory_get_by_uri(), and caja_directory_get_existing().
caja_directory_get_name_for_self_as_new_file()
char * caja_directory_get_name_for_self_as_new_file (CajaDirectory * directory)
Definition at line 404 of file caja-directory.c.
References CAJA_DIRECTORY_GET_CLASS, CAJA_IS_DIRECTORY, and NULL.
caja_directory_has_active_request_for_file()
gboolean caja_directory_has_active_request_for_file (CajaDirectory * directory, CajaFile * file)
Definition at line 2084 of file caja-directory-async.c.
References _CajaDirectoryPrivate::call_when_ready_list, CajaDirectory::details, FALSE, _CajaDirectoryPrivate::monitor_list, NULL, and TRUE.
Referenced by caja_directory_add_file().
caja_directory_invalidate_count_and_mime_list()
void caja_directory_invalidate_count_and_mime_list (CajaDirectory * directory)
Definition at line 2376 of file caja-directory-async.c.
References caja_directory_get_existing_corresponding_file(), caja_file_invalidate_count_and_mime_list(), caja_file_unref(), and NULL.
Referenced by caja_directory_force_reload_internal().
caja_directory_is_anyone_monitoring_file_list()
gboolean caja_directory_is_anyone_monitoring_file_list (CajaDirectory * directory)
Definition at line 2118 of file caja-directory-async.c.
References _CajaDirectoryPrivate::call_when_ready_counters, CajaDirectory::details, FALSE, _CajaDirectoryPrivate::monitor_counters, REQUEST_FILE_LIST, and TRUE.
caja_directory_is_file_list_monitored()
gboolean caja_directory_is_file_list_monitored (CajaDirectory * directory)
Definition at line 2135 of file caja-directory-async.c.
References CajaDirectory::details, and _CajaDirectoryPrivate::file_list_monitored.
Referenced by caja_directory_add_file(), caja_directory_notify_files_added(), and caja_directory_remove_file().
caja_directory_monitor_add_internal()
void caja_directory_monitor_add_internal (CajaDirectory * directory, CajaFile * file, gconstpointer client, gboolean monitor_hidden_files, CajaFileAttributes attributes, CajaDirectoryCallback callback, gpointer callback_data)
Definition at line 789 of file caja-directory-async.c.
References caja_directory_add_file_to_work_queue(), caja_directory_async_state_changed(), caja_directory_get_file_list(), caja_directory_set_up_request(), caja_file_list_free(), CAJA_IS_DIRECTORY, caja_monitor_directory(), caja_signaller_get_current(), CajaDirectory::details, file_list, _CajaDirectoryPrivate::location, _CajaDirectoryPrivate::mime_db_monitor, _CajaDirectoryPrivate::monitor, _CajaDirectoryPrivate::monitor_counters, _CajaDirectoryPrivate::monitor_list, NULL, REQUEST_FILE_INFO, REQUEST_FILE_LIST, REQUEST_SET_TYPE, and REQUEST_WANTS_TYPE.
Referenced by EEL_CLASS_BOILERPLATE().
caja_directory_monitor_remove_internal()
void caja_directory_monitor_remove_internal (CajaDirectory * directory, CajaFile * file, gconstpointer client)
Definition at line 1196 of file caja-directory-async.c.
References caja_directory_async_state_changed(), CAJA_IS_DIRECTORY, CAJA_IS_FILE, caja_monitor_cancel(), CajaDirectory::details, _CajaDirectoryPrivate::monitor, _CajaDirectoryPrivate::monitor_list, and NULL.
caja_directory_moved()
void caja_directory_moved (const char * from_uri, const char * to_uri)
Definition at line 1159 of file caja-directory.c.
References CAJA_FILE, caja_file_list_free(), caja_file_ref(), CajaFile::details, _CajaFilePrivate::directory, hash, and NULL.
caja_directory_number_outstanding()
int caja_directory_number_outstanding (void)
Definition at line 1697 of file caja-directory.c.
Referenced by caja_self_check_file().
caja_directory_remove_file()
void caja_directory_remove_file (CajaDirectory * directory, CajaFile * file)
Definition at line 597 of file caja-directory.c.
References caja_directory_is_file_list_monitored(), caja_directory_remove_file_from_work_queue(), caja_file_unref(), CAJA_IS_DIRECTORY, CAJA_IS_FILE, _CajaDirectoryPrivate::confirmed_file_count, CajaDirectory::details, CajaFile::details, _CajaDirectoryPrivate::file_list, _CajaFilePrivate::name, NULL, and _CajaFilePrivate::unconfirmed.
Referenced by caja_desktop_icon_file_remove(), caja_file_mark_gone(), and caja_file_update_name_and_directory().
caja_directory_remove_file_from_work_queue()
void caja_directory_remove_file_from_work_queue (CajaDirectory * directory, CajaFile * file)
Definition at line 5296 of file caja-directory-async.c.
References caja_file_queue_remove(), CajaDirectory::details, _CajaDirectoryPrivate::extension_queue, _CajaDirectoryPrivate::high_priority_queue, and _CajaDirectoryPrivate::low_priority_queue.
Referenced by caja_directory_cancel_loading_file_attributes(), and caja_directory_remove_file().
caja_directory_remove_file_monitor_link()
void caja_directory_remove_file_monitor_link (CajaDirectory * directory, GList * link)
References error.
caja_directory_remove_file_monitors()
FileMonitors * caja_directory_remove_file_monitors (CajaDirectory * directory, CajaFile * file)
Definition at line 1219 of file caja-directory-async.c.
References caja_directory_async_state_changed(), CAJA_IS_DIRECTORY, CAJA_IS_FILE, CajaDirectory::details, CajaFile::details, _CajaFilePrivate::directory, _CajaDirectoryPrivate::monitor_counters, _CajaDirectoryPrivate::monitor_list, and NULL.
Referenced by caja_file_update_name_and_directory().
caja_directory_schedule_dequeue_pending()
void caja_directory_schedule_dequeue_pending (CajaDirectory * directory)
Definition at line 1081 of file caja-directory-async.c.
References _CajaDirectoryPrivate::dequeue_pending_idle_id, and CajaDirectory::details.
caja_directory_set_up_request()
Request caja_directory_set_up_request (CajaFileAttributes file_attributes)
Definition at line 705 of file caja-directory-async.c.
References CAJA_FILE_ATTRIBUTE_DEEP_COUNTS, CAJA_FILE_ATTRIBUTE_DIRECTORY_ITEM_COUNT, CAJA_FILE_ATTRIBUTE_DIRECTORY_ITEM_MIME_TYPES, CAJA_FILE_ATTRIBUTE_EXTENSION_INFO, CAJA_FILE_ATTRIBUTE_FILESYSTEM_INFO, CAJA_FILE_ATTRIBUTE_INFO, CAJA_FILE_ATTRIBUTE_LARGE_TOP_LEFT_TEXT, CAJA_FILE_ATTRIBUTE_LINK_INFO, CAJA_FILE_ATTRIBUTE_MOUNT, CAJA_FILE_ATTRIBUTE_THUMBNAIL, CAJA_FILE_ATTRIBUTE_TOP_LEFT_TEXT, REQUEST_DEEP_COUNT, REQUEST_DIRECTORY_COUNT, REQUEST_EXTENSION_INFO, REQUEST_FILE_INFO, REQUEST_FILESYSTEM_INFO, REQUEST_LARGE_TOP_LEFT_TEXT, REQUEST_LINK_INFO, REQUEST_MIME_LIST, REQUEST_MOUNT, REQUEST_SET_TYPE, REQUEST_THUMBNAIL, and REQUEST_TOP_LEFT_TEXT.
Referenced by caja_directory_call_when_ready_internal(), caja_directory_cancel_loading_file_attributes(), caja_directory_check_if_ready_internal(), caja_directory_monitor_add_internal(), and caja_file_invalidate_attributes_internal().
caja_directory_stop_monitoring_file_list()
void caja_directory_stop_monitoring_file_list (CajaDirectory * directory)
Definition at line 2331 of file caja-directory-async.c.
References caja_file_list_unref(), CajaDirectory::details, _CajaDirectoryPrivate::directory_load_in_progress, _CajaDirectoryPrivate::directory_loaded, FALSE, _CajaDirectoryPrivate::file_list, _CajaDirectoryPrivate::file_list_monitored, and NULL.
emit_change_signals_for_all_files()
void emit_change_signals_for_all_files (CajaDirectory * directory)
Definition at line 206 of file caja-directory.c.
References _CajaDirectoryPrivate::as_file, caja_directory_emit_change_signals(), caja_file_list_free(), caja_file_list_ref(), CajaDirectory::details, _CajaDirectoryPrivate::file_list, and NULL.
Referenced by emit_change_signals_for_all_files_in_all_directories().
emit_change_signals_for_all_files_in_all_directories()
void emit_change_signals_for_all_files_in_all_directories (void)
Definition at line 235 of file caja-directory.c.
References CAJA_DIRECTORY, caja_directory_unref(), emit_change_signals_for_all_files(), and NULL.