MATE Desktop Environment: caja-side-pane.h File Reference
caja-side-pane.h File Reference
#include <gtk/gtk.h>
Classes
struct CajaSidePane
struct CajaSidePaneClass
Macros
#define CAJA_TYPE_SIDE_PANE caja_side_pane_get_type()
#define CAJA_SIDE_PANE(obj)
#define CAJA_SIDE_PANE_CLASS(klass)
#define CAJA_IS_SIDE_PANE(obj)
#define CAJA_IS_SIDE_PANE_CLASS(klass)
#define CAJA_SIDE_PANE_GET_CLASS(obj)
Typedefs
typedef struct _CajaSidePanePrivate CajaSidePanePrivate
Functions
GType caja_side_pane_get_type (void)
CajaSidePane * caja_side_pane_new (void)
void caja_side_pane_add_panel (CajaSidePane *side_pane, GtkWidget *widget, const char *title, const char *tooltip)
void caja_side_pane_remove_panel (CajaSidePane *side_pane, GtkWidget *widget)
void caja_side_pane_show_panel (CajaSidePane *side_pane, GtkWidget *widget)
void caja_side_pane_set_panel_image (CajaSidePane *side_pane, GtkWidget *widget, GdkPixbuf *pixbuf)
GtkWidget * caja_side_pane_get_current_panel (CajaSidePane *side_pane)
GtkWidget * caja_side_pane_get_title (CajaSidePane *side_pane)
Macro Definition Documentation
CAJA_IS_SIDE_PANE
#define CAJA_IS_SIDE_PANE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), CAJA_TYPE_SIDE_PANE))
Definition at line 36 of file caja-side-pane.h.
Referenced by caja_navigation_window_add_sidebar_panel(), caja_side_pane_add_panel(), caja_side_pane_remove_panel(), caja_side_pane_set_panel_image(), and caja_side_pane_show_panel().
CAJA_IS_SIDE_PANE_CLASS
#define CAJA_IS_SIDE_PANE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), CAJA_TYPE_SIDE_PANE))
Definition at line 38 of file caja-side-pane.h.
CAJA_SIDE_PANE
#define CAJA_SIDE_PANE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), CAJA_TYPE_SIDE_PANE, CajaSidePane))
Definition at line 32 of file caja-side-pane.h.
Referenced by caja_side_pane_new().
CAJA_SIDE_PANE_CLASS
#define CAJA_SIDE_PANE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), CAJA_TYPE_SIDE_PANE, CajaSidePaneClass))
Definition at line 34 of file caja-side-pane.h.
CAJA_SIDE_PANE_GET_CLASS
#define CAJA_SIDE_PANE_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), CAJA_TYPE_SIDE_PANE, CajaSidePaneClass))
Definition at line 40 of file caja-side-pane.h.
CAJA_TYPE_SIDE_PANE
#define CAJA_TYPE_SIDE_PANE caja_side_pane_get_type()
Definition at line 31 of file caja-side-pane.h.
Typedef Documentation
CajaSidePanePrivate
typedef struct _CajaSidePanePrivate CajaSidePanePrivate
Definition at line 43 of file caja-side-pane.h.
Function Documentation
caja_side_pane_add_panel()
void caja_side_pane_add_panel (CajaSidePane * side_pane, GtkWidget * widget, const char * title, const char * tooltip)
Definition at line 425 of file caja-side-pane.c.
References CAJA_IS_SIDE_PANE, CajaSidePane::details, eel_image_menu_item_new_from_icon(), and NULL.
Referenced by caja_navigation_window_add_sidebar_panel().
caja_side_pane_get_current_panel()
GtkWidget * caja_side_pane_get_current_panel (CajaSidePane * side_pane)
Definition at line 605 of file caja-side-pane.c.
References CajaSidePane::details.
caja_side_pane_get_title()
GtkWidget * caja_side_pane_get_title (CajaSidePane * side_pane)
Definition at line 614 of file caja-side-pane.c.
References CajaSidePane::details.
caja_side_pane_get_type()
GType caja_side_pane_get_type (void)
Referenced by caja_side_pane_new().
caja_side_pane_new()
CajaSidePane * caja_side_pane_new (void)
Definition at line 419 of file caja-side-pane.c.
References CAJA_SIDE_PANE, caja_side_pane_get_type(), and NULL.
caja_side_pane_remove_panel()
void caja_side_pane_remove_panel (CajaSidePane * side_pane, GtkWidget * widget)
Definition at line 467 of file caja-side-pane.c.
References CAJA_IS_SIDE_PANE, CajaSidePane::details, and NULL.
Referenced by caja_navigation_window_remove_sidebar_panel().
caja_side_pane_set_panel_image()
void caja_side_pane_set_panel_image (CajaSidePane * side_pane, GtkWidget * widget, GdkPixbuf * pixbuf)
Definition at line 561 of file caja-side-pane.c.
References CAJA_IS_SIDE_PANE, CajaSidePane::details, FALSE, and NULL.
Referenced by caja_navigation_window_add_sidebar_panel().
caja_side_pane_show_panel()
void caja_side_pane_show_panel (CajaSidePane * side_pane, GtkWidget * widget)
Definition at line 501 of file caja-side-pane.c.
References CAJA_IS_SIDE_PANE, CajaSidePane::details, and NULL.
Referenced by caja_navigation_window_add_sidebar_panel().