MATE Desktop Environment: caja-spatial-window.c File Reference
caja-spatial-window.c File Reference
#include <config.h>
#include <gdk/gdkkeysyms.h>
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <eel/eel-gtk-extensions.h>
#include <eel/eel-gtk-macros.h>
#include <eel/eel-string.h>
#include <libcaja-private/caja-dnd.h>
#include <libcaja-private/caja-file-utilities.h>
#include <libcaja-private/caja-ui-utilities.h>
#include <libcaja-private/caja-file-attributes.h>
#include <libcaja-private/caja-global-preferences.h>
#include <libcaja-private/caja-metadata.h>
#include <libcaja-private/caja-mime-actions.h>
#include <libcaja-private/caja-program-choosing.h>
#include <libcaja-private/caja-search-directory.h>
#include <libcaja-private/caja-search-engine.h>
#include <libcaja-private/caja-signaller.h>
#include "caja-spatial-window.h"
#include "caja-window-private.h"
#include "caja-window-bookmarks.h"
#include "caja-actions.h"
#include "caja-application.h"
#include "caja-desktop-window.h"
#include "caja-bookmarks-window.h"
#include "caja-location-dialog.h"
#include "caja-query-editor.h"
#include "caja-search-bar.h"
#include "caja-window-manage-views.h"
Macros
#define MAX_TITLE_LENGTH 180
#define MAX_SHORTNAME_PATH 16
#define SPATIAL_ACTION_PLACES "Places"
#define SPATIAL_ACTION_GO_TO_LOCATION "Go to Location"
#define SPATIAL_ACTION_CLOSE_PARENT_FOLDERS "Close Parent Folders"
#define SPATIAL_ACTION_CLOSE_ALL_FOLDERS "Close All Folders"
#define MENU_PATH_SPATIAL_BOOKMARKS_PLACEHOLDER "/MenuBar/Other Menus/Places/Bookmarks Placeholder"
Functions
void caja_spatial_window_set_location_button (CajaSpatialWindow *window, GFile *location)
Macro Definition Documentation
MAX_SHORTNAME_PATH
#define MAX_SHORTNAME_PATH 16
Definition at line 66 of file caja-spatial-window.c.
MAX_TITLE_LENGTH
#define MAX_TITLE_LENGTH 180
Definition at line 65 of file caja-spatial-window.c.
MENU_PATH_SPATIAL_BOOKMARKS_PLACEHOLDER
#define MENU_PATH_SPATIAL_BOOKMARKS_PLACEHOLDER "/MenuBar/Other Menus/Places/Bookmarks Placeholder"
Definition at line 72 of file caja-spatial-window.c.
SPATIAL_ACTION_CLOSE_ALL_FOLDERS
#define SPATIAL_ACTION_CLOSE_ALL_FOLDERS "Close All Folders"
Definition at line 71 of file caja-spatial-window.c.
SPATIAL_ACTION_CLOSE_PARENT_FOLDERS
#define SPATIAL_ACTION_CLOSE_PARENT_FOLDERS "Close Parent Folders"
Definition at line 70 of file caja-spatial-window.c.
SPATIAL_ACTION_GO_TO_LOCATION
#define SPATIAL_ACTION_GO_TO_LOCATION "Go to Location"
Definition at line 69 of file caja-spatial-window.c.
SPATIAL_ACTION_PLACES
#define SPATIAL_ACTION_PLACES "Places"
Definition at line 68 of file caja-spatial-window.c.
Function Documentation
caja_spatial_window_set_location_button()
void caja_spatial_window_set_location_button (CajaSpatialWindow * window, GFile * location)
Definition at line 833 of file caja-spatial-window.c.
References caja_file_get(), caja_file_get_display_name(), caja_file_get_file_info_error(), caja_file_get_icon_surface(), CAJA_FILE_ICON_FLAGS_IGNORE_VISITING, caja_get_icon_size_for_stock_size(), error, FALSE, name, NULL, and TRUE.