MATE Desktop Environment: capplet-util.c File Reference
capplet-util.c File Reference
#include <ctype.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <glib/gi18n.h>
#include <stdlib.h>
#include "capplet-util.h"
Functions
void capplet_help (GtkWindow *parent, char const *section)
void capplet_set_icon (GtkWidget *window, char const *icon_file_name)
gboolean capplet_file_delete_recursive (GFile *file, GError **error)
gboolean capplet_notebook_scroll_event_cb (GtkWidget *widget, GdkEventScroll *event)
void capplet_init (GOptionContext *context, int *argc, char ***argv)
Detailed Description
capplet_file_delete_recursive :
@error :
A utility routine to delete files and/or directories, including non-empty directories.
Definition in file capplet-util.c.
Function Documentation
capplet_file_delete_recursive()
gboolean capplet_file_delete_recursive (GFile * file, GError ** error)
Definition at line 150 of file capplet-util.c.
References error, FALSE, and NULL.
Referenced by delete_custom_theme_dir(), and theme_delete().
capplet_help()
void capplet_help (GtkWindow * parent, char const * section)
capplet_help : @parent : @helpfile :
Definition at line 70 of file capplet-util.c.
References _, error, and NULL.
capplet_init()
void capplet_init (GOptionContext * context, int * argc, char *** argv)
Definition at line 235 of file capplet-util.c.
References GETTEXT_PACKAGE, MATELOCALEDIR, NULL, and TRUE.
Referenced by main(), and main().
capplet_notebook_scroll_event_cb()
gboolean capplet_notebook_scroll_event_cb (GtkWidget * widget, GdkEventScroll * event)
Definition at line 174 of file capplet-util.c.
References FALSE, NULL, and TRUE.
Referenced by main().
capplet_set_icon()
void capplet_set_icon (GtkWidget * window, char const * icon_file_name)
capplet_set_icon : @window : @file_name :
A quick utility routine to avoid the cut-n-paste of bogus code that caused several bugs.
Definition at line 98 of file capplet-util.c.
Referenced by main().