MATE Desktop Environment: charpick.h File Reference
charpick.h File Reference
#include <glib.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <mate-panel-applet.h>
#include <mate-panel-applet-gsettings.h>
Classes
struct _charpick_data
struct _charpick_button_cb_data
Macros
#define NO_LAST_INDEX -1
Typedefs
typedef struct _charpick_data charpick_data
typedef struct _charpick_button_cb_data charpick_button_cb_data
Functions
void start_callback_update (void)
void register_stock_for_edit (void)
void build_table (charpick_data *curr_data)
void add_to_popup_menu (charpick_data *curr_data)
void populate_menu (charpick_data *curr_data)
void save_chartable (charpick_data *curr_data)
void show_preferences_dialog (GtkAction *action, charpick_data *curr_data)
void add_edit_dialog_create (charpick_data *curr_data, gchar *string, gchar *title)
void set_atk_name_description (GtkWidget *widget, const char *name, const char *description)
gboolean key_writable (MatePanelApplet *applet, const char *key)
Macro Definition Documentation
NO_LAST_INDEX
#define NO_LAST_INDEX -1
Definition at line 13 of file charpick.h.
Referenced by build_table().
Typedef Documentation
charpick_button_cb_data
typedef struct _charpick_button_cb_data charpick_button_cb_data
Definition at line 39 of file charpick.h.
charpick_data
typedef struct _charpick_data charpick_data
Definition at line 15 of file charpick.h.
Function Documentation
add_edit_dialog_create()
void add_edit_dialog_create (charpick_data * curr_data, gchar * string, gchar * title)
Definition at line 61 of file charpick/properties.c.
References _, _charpick_data::add_edit_dialog, _charpick_data::add_edit_entry, FALSE, label, NULL, _charpick_data::propwindow, and TRUE.
add_to_popup_menu()
void add_to_popup_menu (charpick_data * curr_data)
References action, and name.
build_table()
void build_table (charpick_data * curr_data)
Definition at line 385 of file charpick.c.
References _, _charpick_data::applet, _charpick_data::box, _charpick_data::charlist, _charpick_data::chartable, delta, label, _charpick_data::last_index, _charpick_data::last_toggle_button, mate_panel_applet_get_orient(), MAX, name, NO_LAST_INDEX, NULL, _charpick_data::panel_size, _charpick_data::panel_vertical, set_atk_name_description(), and TRUE.
Referenced by populate_menu().
key_writable()
gboolean key_writable (MatePanelApplet * applet, const char * key)
References key.
populate_menu()
void populate_menu (charpick_data * curr_data)
Definition at line 293 of file charpick.c.
References build_table(), _charpick_data::charlist, _charpick_data::chartable, _charpick_data::menu, NULL, and TRUE.
register_stock_for_edit()
void register_stock_for_edit (void)
Definition at line 19 of file charpick/properties.c.
References CHARPICK_STOCK_EDIT, FALSE, GETTEXT_PACKAGE, N_, and TRUE.
save_chartable()
void save_chartable (charpick_data * curr_data)
Definition at line 693 of file charpick.c.
References _charpick_data::chartable, mate_panel_applet_settings_set_glist(), and _charpick_data::settings.
set_atk_name_description()
void set_atk_name_description (GtkWidget * widget, const char * name, const char * description)
Definition at line 533 of file clock.c.
References name, and NULL.
show_preferences_dialog()
void show_preferences_dialog (GtkAction * action, charpick_data * curr_data)
Definition at line 555 of file charpick/properties.c.
References _, action, _charpick_data::applet, NULL, and _charpick_data::propwindow.
start_callback_update()
void start_callback_update (void)