MATE Desktop Environment: charpick.c File Reference
charpick.c File Reference
#include <gdk/gdkx.h>
#include <config.h>
#include <string.h>
#include <mate-panel-applet.h>
#include <mate-panel-applet-gsettings.h>
#include "charpick.h"
Functions
void populate_menu (charpick_data *curr_data)
void build_table (charpick_data *p_curr_data)
void save_chartable (charpick_data *curr_data)
void set_atk_name_description (GtkWidget *widget, const gchar *name, const gchar *description)
Function Documentation
build_table()
void build_table (charpick_data * p_curr_data)
Definition at line 385 of file charpick.c.
References _, _charpick_data::applet, _charpick_data::box, _charpick_data::charlist, _charpick_data::chartable, delta, label, _charpick_data::last_index, _charpick_data::last_toggle_button, mate_panel_applet_get_orient(), MAX, name, NO_LAST_INDEX, NULL, _charpick_data::panel_size, _charpick_data::panel_vertical, set_atk_name_description(), and TRUE.
Referenced by populate_menu().
populate_menu()
void populate_menu (charpick_data * curr_data)
Definition at line 293 of file charpick.c.
References build_table(), _charpick_data::charlist, _charpick_data::chartable, _charpick_data::menu, NULL, and TRUE.
save_chartable()
void save_chartable (charpick_data * curr_data)
Definition at line 693 of file charpick.c.
References _charpick_data::chartable, mate_panel_applet_settings_set_glist(), and _charpick_data::settings.
set_atk_name_description()
void set_atk_name_description (GtkWidget * widget, const gchar * name, const gchar * description)
Definition at line 736 of file charpick.c.
References FALSE, and name.
Referenced by build_table(), and G_DEFINE_TYPE_WITH_PRIVATE().