MATE Desktop Environment: clock-location-tile.c File Reference
clock-location-tile.c File Reference
#include <string.h>
#include <stdlib.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include "clock.h"
#include "clock-face.h"
#include "clock-location-tile.h"
#include "clock-location.h"
#include "clock-utils.h"
#include "clock-marshallers.h"
#include "set-timezone.h"
Enumerations
enum { TILE_PRESSED , NEED_CLOCK_FORMAT , LAST_SIGNAL }
Functions
ClockLocationTile * clock_location_tile_new (ClockLocation *loc, ClockFaceSize size)
void clock_location_tile_refresh (ClockLocationTile *this, gboolean force_refresh)
void weather_info_setup_tooltip (WeatherInfo *info, ClockLocation *location, GtkTooltip *tooltip, ClockFormat clock_format)
ClockLocation * clock_location_tile_get_location (ClockLocationTile *this)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TILE_PRESSED
NEED_CLOCK_FORMAT
LAST_SIGNAL
Definition at line 19 of file clock-location-tile.c.
Function Documentation
clock_location_tile_get_location()
ClockLocation * clock_location_tile_get_location (ClockLocationTile * this)
Definition at line 710 of file clock-location-tile.c.
References IS_CLOCK_LOCATION_TILE, and NULL.
clock_location_tile_new()
ClockLocationTile * clock_location_tile_new (ClockLocation * loc, ClockFaceSize size)
Definition at line 65 of file clock-location-tile.c.
References clock_location_get_weather_info(), CLOCK_LOCATION_TILE_TYPE, NULL, and TRUE.
clock_location_tile_refresh()
void clock_location_tile_refresh (ClockLocationTile * this, gboolean force_refresh)
Definition at line 517 of file clock-location-tile.c.
References CLOCK_FACE, clock_face_refresh(), clock_location_get_display_name(), clock_location_get_offset(), clock_location_get_tzname(), clock_location_is_current(), clock_location_localtime(), IS_CLOCK_LOCATION_TILE, and NEED_CLOCK_FORMAT.
weather_info_setup_tooltip()
void weather_info_setup_tooltip (WeatherInfo * info, ClockLocation * location, GtkTooltip * tooltip, ClockFormat clock_format)
Definition at line 571 of file clock-location-tile.c.
References _, clock_location_get_timezone(), NULL, weather_info_get_apparent(), weather_info_get_conditions(), weather_info_get_icon_name(), weather_info_get_sky(), weather_info_get_temp(), weather_info_get_value_sunrise(), weather_info_get_value_sunset(), and weather_info_get_wind().