MATE Desktop Environment: clock-location.c File Reference
clock-location.c File Reference
#include <dirent.h>
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
#include <math.h>
#include <glib.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include "clock-location.h"
#include "clock-marshallers.h"
#include "set-timezone.h"
#include "system-timezone.h"
Macros
#define WEATHER_TIMEOUT_BASE 30
#define WEATHER_TIMEOUT_MAX 1800
#define WEATHER_EMPTY_CODE "-"
Enumerations
enum { WEATHER_UPDATED , SET_CURRENT , LAST_SIGNAL }
Functions
ClockLocation * clock_location_find_and_ref (GSList *locations, const gchar *name, const gchar *city, const gchar *timezone, gfloat latitude, gfloat longitude, const gchar *code)
ClockLocation * clock_location_new (const gchar *name, const gchar *city, const gchar *timezone, gfloat latitude, gfloat longitude, const gchar *code, WeatherPrefs *prefs)
const gchar * clock_location_get_display_name (ClockLocation *loc)
const gchar * clock_location_get_name (ClockLocation *loc)
void clock_location_set_name (ClockLocation *loc, const gchar *name)
const gchar * clock_location_get_city (ClockLocation *loc)
void clock_location_set_city (ClockLocation *loc, const gchar *city)
gchar * clock_location_get_timezone (ClockLocation *loc)
void clock_location_set_timezone (ClockLocation *loc, const gchar *timezone)
gchar * clock_location_get_tzname (ClockLocation *loc)
void clock_location_get_coords (ClockLocation *loc, gfloat *latitude, gfloat *longitude)
void clock_location_set_coords (ClockLocation *loc, gfloat latitude, gfloat longitude)
void clock_location_localtime (ClockLocation *loc, struct tm *tm)
gboolean clock_location_is_current_timezone (ClockLocation *loc)
gboolean clock_location_is_current (ClockLocation *loc)
glong clock_location_get_offset (ClockLocation *loc)
void clock_location_make_current (ClockLocation *loc, GFunc callback, gpointer data, GDestroyNotify destroy)
const gchar * clock_location_get_weather_code (ClockLocation *loc)
void clock_location_set_weather_code (ClockLocation *loc, const gchar *code)
WeatherInfo * clock_location_get_weather_info (ClockLocation *loc)
void clock_location_set_weather_prefs (ClockLocation *loc, WeatherPrefs *prefs)
Macro Definition Documentation
WEATHER_EMPTY_CODE
#define WEATHER_EMPTY_CODE "-"
Definition at line 51 of file clock-location.c.
WEATHER_TIMEOUT_BASE
#define WEATHER_TIMEOUT_BASE 30
Definition at line 49 of file clock-location.c.
WEATHER_TIMEOUT_MAX
#define WEATHER_TIMEOUT_MAX 1800
Definition at line 50 of file clock-location.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
WEATHER_UPDATED
SET_CURRENT
LAST_SIGNAL
Definition at line 53 of file clock-location.c.
Function Documentation
clock_location_find_and_ref()
ClockLocation * clock_location_find_and_ref (GSList * locations, const gchar * name, const gchar * city, const gchar * timezone, gfloat latitude, gfloat longitude, const gchar * code)
Definition at line 70 of file clock-location.c.
References CLOCK_LOCATION, name, and NULL.
clock_location_get_city()
const gchar * clock_location_get_city (ClockLocation * loc)
Definition at line 264 of file clock-location.c.
clock_location_get_coords()
void clock_location_get_coords (ClockLocation * loc, gfloat * latitude, gfloat * longitude)
Definition at line 306 of file clock-location.c.
clock_location_get_display_name()
const gchar * clock_location_get_display_name (ClockLocation * loc)
Definition at line 236 of file clock-location.c.
Referenced by clock_location_tile_refresh().
clock_location_get_name()
const gchar * clock_location_get_name (ClockLocation * loc)
Definition at line 247 of file clock-location.c.
clock_location_get_offset()
glong clock_location_get_offset (ClockLocation * loc)
Definition at line 438 of file clock-location.c.
References NULL.
Referenced by clock_location_is_current_timezone(), and clock_location_tile_refresh().
clock_location_get_timezone()
gchar * clock_location_get_timezone (ClockLocation * loc)
Definition at line 281 of file clock-location.c.
Referenced by weather_info_setup_tooltip().
clock_location_get_tzname()
gchar * clock_location_get_tzname (ClockLocation * loc)
Definition at line 298 of file clock-location.c.
Referenced by clock_location_tile_refresh().
clock_location_get_weather_code()
const gchar * clock_location_get_weather_code (ClockLocation * loc)
Definition at line 567 of file clock-location.c.
clock_location_get_weather_info()
WeatherInfo * clock_location_get_weather_info (ClockLocation * loc)
Definition at line 586 of file clock-location.c.
Referenced by clock_location_tile_new().
clock_location_is_current()
gboolean clock_location_is_current (ClockLocation * loc)
Definition at line 414 of file clock-location.c.
References clock_location_is_current_timezone(), FALSE, NULL, SET_CURRENT, and TRUE.
Referenced by clock_location_tile_refresh().
clock_location_is_current_timezone()
gboolean clock_location_is_current_timezone (ClockLocation * loc)
Definition at line 400 of file clock-location.c.
References clock_location_get_offset(), and system_timezone_get().
Referenced by clock_location_is_current(), and clock_location_make_current().
clock_location_localtime()
void clock_location_localtime (ClockLocation * loc, struct tm * tm)
Definition at line 387 of file clock-location.c.
Referenced by clock_location_tile_refresh().
clock_location_make_current()
void clock_location_make_current (ClockLocation * loc, GFunc callback, gpointer data, GDestroyNotify destroy)
Definition at line 511 of file clock-location.c.
References clock_location_is_current_timezone(), data, NULL, SET_CURRENT, set_system_timezone_async(), and SYSTEM_ZONEINFODIR.
clock_location_new()
ClockLocation * clock_location_new (const gchar * name, const gchar * city, const gchar * timezone, gfloat latitude, gfloat longitude, const gchar * code, WeatherPrefs * prefs)
Definition at line 101 of file clock-location.c.
References CLOCK_LOCATION_TYPE, name, NULL, _WeatherPrefs::speed_unit, and _WeatherPrefs::temperature_unit.
clock_location_set_city()
void clock_location_set_city (ClockLocation * loc, const gchar * city)
Definition at line 272 of file clock-location.c.
clock_location_set_coords()
void clock_location_set_coords (ClockLocation * loc, gfloat latitude, gfloat longitude)
Definition at line 316 of file clock-location.c.
clock_location_set_name()
void clock_location_set_name (ClockLocation * loc, const gchar * name)
Definition at line 255 of file clock-location.c.
References name.
clock_location_set_timezone()
void clock_location_set_timezone (ClockLocation * loc, const gchar * timezone)
Definition at line 289 of file clock-location.c.
clock_location_set_weather_code()
void clock_location_set_weather_code (ClockLocation * loc, const gchar * code)
Definition at line 575 of file clock-location.c.
clock_location_set_weather_prefs()
void clock_location_set_weather_prefs (ClockLocation * loc, WeatherPrefs * prefs)
Definition at line 730 of file clock-location.c.
References _WeatherPrefs::speed_unit, and _WeatherPrefs::temperature_unit.