MATE Desktop Environment: color.c File Reference
color.c File Reference
#include <config.h>
#include "mdvi.h"
#include "color.h"
Macros
#define CCSIZE 256
#define GAMMA_DIFF 0.005
Functions
void mdvi_set_color (DviContext *dvi, Ulong fg, Ulong bg)
void mdvi_push_color (DviContext *dvi, Ulong fg, Ulong bg)
void mdvi_pop_color (DviContext *dvi)
void mdvi_reset_color (DviContext *dvi)
Ulong * get_color_table (DviDevice *dev, int nlevels, Ulong fg, Ulong bg, double gamma, int density)
Macro Definition Documentation
CCSIZE
#define CCSIZE 256
Definition at line 76 of file color.c.
Referenced by get_color_table().
GAMMA_DIFF
#define GAMMA_DIFF 0.005
Definition at line 80 of file color.c.
Referenced by get_color_table().
Function Documentation
get_color_table()
Ulong * get_color_table (DviDevice * dev, int nlevels, Ulong fg, Ulong bg, double gamma, int density)
Definition at line 83 of file color.c.
References _DviDevice::alloc_colors, CCSIZE, DBG_DEVICE, DEBUG, _DviDevice::device_data, GAMMA_DIFF, mdvi_free(), NULL, and xnalloc.
Referenced by mdvi_shrink_glyph_grey().
mdvi_pop_color()
void mdvi_pop_color (DviContext * dvi)
Definition at line 47 of file color.c.
References _DviColorPair::bg, _DviContext::color_stack, _DviContext::color_top, _DviColorPair::fg, and mdvi_set_color().
Referenced by __PROTO().
mdvi_push_color()
void mdvi_push_color (DviContext * dvi, Ulong fg, Ulong bg)
Definition at line 34 of file color.c.
References _DviColorPair::bg, _DviContext::color_size, _DviContext::color_stack, _DviContext::color_top, _DviContext::curr_bg, _DviContext::curr_fg, _DviColorPair::fg, mdvi_realloc(), and mdvi_set_color().
Referenced by __PROTO().
mdvi_reset_color()
void mdvi_reset_color (DviContext * dvi)
Definition at line 59 of file color.c.
References _DviParams::bg, _DviContext::color_top, _DviParams::fg, mdvi_set_color(), and _DviContext::params.
Referenced by __PROTO(), and mdvi_dopage().
mdvi_set_color()
void mdvi_set_color (DviContext * dvi, Ulong fg, Ulong bg)
Definition at line 23 of file color.c.
References _DviContext::curr_bg, _DviContext::curr_fg, DBG_DEVICE, DEBUG, _DviContext::device, _DviDevice::device_data, and _DviDevice::set_color.
Referenced by __PROTO(), mdvi_pop_color(), mdvi_push_color(), and mdvi_reset_color().