MATE Desktop Environment: common.c File Reference
common.c File Reference
#include <config.h>
#include <stdlib.h>
#include <string.h>
#include "common.h"
Functions
long fsgetn (FILE *p, size_t n)
Ulong fugetn (FILE *p, size_t n)
long msgetn (const Uchar *p, size_t n)
Ulong mugetn (const Uchar *p, size_t n)
char * read_string (FILE *in, int s, char *buffer, size_t len)
size_t read_bcpl (FILE *in, char *buffer, size_t maxlen, size_t wanted)
char * read_alloc_bcpl (FILE *in, size_t maxlen, size_t *size)
void buff_free (Buffer *buf)
void buff_init (Buffer *buf)
size_t buff_add (Buffer *buf, const char *data, size_t len)
char * buff_gets (Buffer *buf, size_t *length)
Function Documentation
buff_add()
size_t buff_add (Buffer * buf, const char * data, size_t len)
Definition at line 134 of file common.c.
References data, mdvi_realloc(), and memcpy.
Referenced by __PROTO().
buff_free()
void buff_free (Buffer * buf)
Definition at line 120 of file common.c.
References buff_init(), and mdvi_free().
Referenced by __PROTO().
buff_gets()
char * buff_gets (Buffer * buf, size_t * length)
Definition at line 147 of file common.c.
References mdvi_malloc(), memcpy, memmove, NULL, ptr, and strchr.
Referenced by __PROTO().
buff_init()
void buff_init (Buffer * buf)
Definition at line 127 of file common.c.
References NULL.
Referenced by __PROTO(), and buff_free().
fsgetn()
long fsgetn (FILE * p, size_t n)
Definition at line 25 of file common.c.
References fgetbyte.
Referenced by __PROTO().
fugetn()
Ulong fugetn (FILE * p, size_t n)
Definition at line 37 of file common.c.
References fgetbyte.
Referenced by __PROTO(), and read_string().
msgetn()
long msgetn (const Uchar * p, size_t n)
Definition at line 47 of file common.c.
References long().
Referenced by __PROTO().
mugetn()
Ulong mugetn (const Uchar * p, size_t n)
Definition at line 58 of file common.c.
Referenced by __PROTO().
read_alloc_bcpl()
char * read_alloc_bcpl (FILE * in, size_t maxlen, size_t * size)
Definition at line 98 of file common.c.
References fuget1, and NULL.
Referenced by __PROTO().
read_bcpl()
size_t read_bcpl (FILE * in, char * buffer, size_t maxlen, size_t wanted)
Definition at line 83 of file common.c.
References fuget1, and int().
Referenced by __PROTO().
read_string()
char * read_string (FILE * in, int s, char * buffer, size_t len)
Definition at line 67 of file common.c.
References fugetn(), mdvi_free(), mdvi_malloc(), and NULL.
Referenced by __PROTO().