MATE Desktop Environment: compositor.c File Reference
compositor.c File Reference
#include <config.h>
#include "compositor-private.h"
#include "compositor-xrender.h"
Functions
MetaCompositor * meta_compositor_new (MetaDisplay *display)
void meta_compositor_destroy (MetaCompositor *compositor)
void meta_compositor_add_window (MetaCompositor *compositor, MetaWindow *window, Window xwindow, XWindowAttributes *attrs)
void meta_compositor_remove_window (MetaCompositor *compositor, Window xwindow)
void meta_compositor_manage_screen (MetaCompositor *compositor, MetaScreen *screen)
void meta_compositor_unmanage_screen (MetaCompositor *compositor, MetaScreen *screen)
void meta_compositor_set_updates (MetaCompositor *compositor, MetaWindow *window, gboolean updates)
void meta_compositor_process_event (MetaCompositor *compositor, XEvent *event, MetaWindow *window)
cairo_surface_t * meta_compositor_get_window_surface (MetaCompositor *compositor, MetaWindow *window)
void meta_compositor_set_active_window (MetaCompositor *compositor, MetaScreen *screen, MetaWindow *window)
void meta_compositor_begin_move (MetaCompositor *compositor, MetaWindow *window, MetaRectangle *initial, int grab_x, int grab_y)
void meta_compositor_update_move (MetaCompositor *compositor, MetaWindow *window, int x, int y)
void meta_compositor_end_move (MetaCompositor *compositor, MetaWindow *window)
void meta_compositor_free_window (MetaCompositor *compositor, MetaWindow *window)
void meta_compositor_maximize_window (MetaCompositor *compositor, MetaWindow *window)
void meta_compositor_unmaximize_window (MetaCompositor *compositor, MetaWindow *window)
Function Documentation
meta_compositor_add_window()
void meta_compositor_add_window (MetaCompositor * compositor, MetaWindow * window, Window xwindow, XWindowAttributes * attrs)
Definition at line 47 of file compositor.c.
References _MetaCompositor::add_window.
Referenced by meta_screen_composite_all_windows(), and meta_screen_manage_all_windows().
meta_compositor_begin_move()
void meta_compositor_begin_move (MetaCompositor * compositor, MetaWindow * window, MetaRectangle * initial, int grab_x, int grab_y)
Definition at line 136 of file compositor.c.
Referenced by meta_display_begin_grab_op().
meta_compositor_destroy()
void meta_compositor_destroy (MetaCompositor * compositor)
Definition at line 38 of file compositor.c.
References _MetaCompositor::destroy.
Referenced by meta_display_close().
meta_compositor_end_move()
void meta_compositor_end_move (MetaCompositor * compositor, MetaWindow * window)
Definition at line 151 of file compositor.c.
Referenced by meta_display_end_grab_op().
meta_compositor_free_window()
void meta_compositor_free_window (MetaCompositor * compositor, MetaWindow * window)
Definition at line 156 of file compositor.c.
References _MetaCompositor::free_window.
Referenced by meta_window_free().
meta_compositor_get_window_surface()
cairo_surface_t * meta_compositor_get_window_surface (MetaCompositor * compositor, MetaWindow * window)
Definition at line 111 of file compositor.c.
References _MetaCompositor::get_window_surface, and NULL.
meta_compositor_manage_screen()
void meta_compositor_manage_screen (MetaCompositor * compositor, MetaScreen * screen)
Definition at line 69 of file compositor.c.
References _MetaCompositor::manage_screen.
meta_compositor_maximize_window()
void meta_compositor_maximize_window (MetaCompositor * compositor, MetaWindow * window)
Definition at line 166 of file compositor.c.
References _MetaCompositor::maximize_window.
Referenced by meta_window_maximize().
meta_compositor_new()
MetaCompositor * meta_compositor_new (MetaDisplay * display)
Definition at line 27 of file compositor.c.
References meta_compositor_xrender_new(), and NULL.
meta_compositor_process_event()
void meta_compositor_process_event (MetaCompositor * compositor, XEvent * event, MetaWindow * window)
Definition at line 100 of file compositor.c.
References _MetaCompositor::process_event.
meta_compositor_remove_window()
void meta_compositor_remove_window (MetaCompositor * compositor, Window xwindow)
Definition at line 59 of file compositor.c.
References _MetaCompositor::remove_window.
meta_compositor_set_active_window()
void meta_compositor_set_active_window (MetaCompositor * compositor, MetaScreen * screen, MetaWindow * window)
Definition at line 125 of file compositor.c.
References _MetaCompositor::set_active_window.
Referenced by meta_window_free(), and meta_window_notify_focus().
meta_compositor_set_updates()
void meta_compositor_set_updates (MetaCompositor * compositor, MetaWindow * window, gboolean updates)
Definition at line 89 of file compositor.c.
References _MetaCompositor::set_updates.
Referenced by meta_window_handle_mouse_grab_op_event().
meta_compositor_unmanage_screen()
void meta_compositor_unmanage_screen (MetaCompositor * compositor, MetaScreen * screen)
Definition at line 79 of file compositor.c.
References _MetaCompositor::unmanage_screen.
Referenced by meta_screen_free().
meta_compositor_unmaximize_window()
void meta_compositor_unmaximize_window (MetaCompositor * compositor, MetaWindow * window)
Definition at line 176 of file compositor.c.
References _MetaCompositor::unmaximize_window.
Referenced by meta_window_unmaximize().
meta_compositor_update_move()
void meta_compositor_update_move (MetaCompositor * compositor, MetaWindow * window, int x, int y)
Definition at line 144 of file compositor.c.