MATE Desktop Environment: cpufreq-utils.h File Reference
cpufreq-utils.h File Reference
#include <glib.h>
Functions
guint cpufreq_utils_get_n_cpus (void)
void cpufreq_utils_display_error (const gchar *message, const gchar *secondary)
gboolean cpufreq_utils_selector_is_available (void)
gchar * cpufreq_utils_get_frequency_label (guint freq)
gchar * cpufreq_utils_get_frequency_unit (guint freq)
gboolean cpufreq_utils_governor_is_automatic (const gchar *governor)
gboolean cpufreq_file_get_contents (const gchar *filename, gchar **contents, gsize *length, GError **error)
Function Documentation
cpufreq_file_get_contents()
gboolean cpufreq_file_get_contents (const gchar * filename, gchar ** contents, gsize * length, GError ** error)
Definition at line 254 of file cpufreq-utils.c.
References error, FALSE, NULL, and TRUE.
cpufreq_utils_display_error()
void cpufreq_utils_display_error (const gchar * message, const gchar * secondary)
Definition at line 83 of file cpufreq-utils.c.
References message(), NULL, and TRUE.
Referenced by cpufreq_monitor_factory_create_monitor().
cpufreq_utils_get_frequency_label()
gchar * cpufreq_utils_get_frequency_label (guint freq)
Definition at line 218 of file cpufreq-utils.c.
cpufreq_utils_get_frequency_unit()
gchar * cpufreq_utils_get_frequency_unit (guint freq)
Definition at line 234 of file cpufreq-utils.c.
cpufreq_utils_get_n_cpus()
guint cpufreq_utils_get_n_cpus (void)
Definition at line 40 of file cpufreq-utils.c.
References NULL.
Referenced by cpufreq_prefs_get_cpu().
cpufreq_utils_governor_is_automatic()
gboolean cpufreq_utils_governor_is_automatic (const gchar * governor)
Definition at line 243 of file cpufreq-utils.c.
References FALSE, NULL, and TRUE.
cpufreq_utils_selector_is_available()
gboolean cpufreq_utils_selector_is_available (void)
Definition at line 185 of file cpufreq-utils.c.
References FALSE, NULL, and TRUE.
Referenced by cpufreq_popup_get_menu().