MATE Desktop Environment: currency-manager.h File Reference
currency-manager.h File Reference
#include "currency.h"
#include "mp.h"
Classes
struct CurrencyManager
struct CurrencyManagerClass
Macros
#define CURRENCY_MANAGER(obj)
Typedefs
typedef struct CurrencyManagerPrivate CurrencyManagerPrivate
Functions
GType currency_manager_get_type (void)
CurrencyManager * currency_manager_get_default (void)
GList * currency_manager_get_currencies (CurrencyManager *manager)
Currency * currency_manager_get_currency (CurrencyManager *manager, const gchar *name)
const MPNumber * currency_manager_get_value (CurrencyManager *manager, const gchar *currency)
Macro Definition Documentation
CURRENCY_MANAGER
#define CURRENCY_MANAGER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), currency_manager_get_type(), CurrencyManager))
Definition at line 19 of file currency-manager.h.
Typedef Documentation
CurrencyManagerPrivate
typedef struct CurrencyManagerPrivate CurrencyManagerPrivate
Definition at line 21 of file currency-manager.h.
Function Documentation
currency_manager_get_currencies()
GList * currency_manager_get_currencies (CurrencyManager * manager)
Definition at line 134 of file currency-manager.c.
References NULL.
Referenced by unit_manager_get_default().
currency_manager_get_currency()
Currency * currency_manager_get_currency (CurrencyManager * manager, const gchar * name)
Definition at line 141 of file currency-manager.c.
References currency_get_name(), currency_get_value(), mp_is_negative(), mp_is_zero(), name, and NULL.
Referenced by currency_manager_get_value().
currency_manager_get_default()
CurrencyManager * currency_manager_get_default (void)
Definition at line 114 of file currency-manager.c.
References _, currency_manager_get_type(), currency_new(), and NULL.
Referenced by unit_convert_from(), unit_convert_to(), and unit_manager_get_default().
currency_manager_get_type()
GType currency_manager_get_type (void)
References name.
Referenced by currency_manager_get_default().
currency_manager_get_value()
const MPNumber * currency_manager_get_value (CurrencyManager * manager, const gchar * currency)
Definition at line 564 of file currency-manager.c.
References currency_get_value(), currency_manager_get_currency(), NULL, and TRUE.
Referenced by unit_convert_from(), and unit_convert_to().