MATE Desktop Environment: desktop-entries.h File Reference
desktop-entries.h File Reference
#include <gio/gdesktopappinfo.h>
Typedefs
typedef struct DesktopEntry DesktopEntry
typedef struct DesktopEntrySet DesktopEntrySet
typedef void(* DesktopEntrySetForeachFunc) (const char *file_id, DesktopEntry *entry, gpointer user_data)
Enumerations
enum DesktopEntryType { DESKTOP_ENTRY_INVALID = 0 , DESKTOP_ENTRY_DESKTOP , DESKTOP_ENTRY_DIRECTORY }
Functions
DesktopEntry * desktop_entry_new (const char *path)
DesktopEntry * desktop_entry_ref (DesktopEntry *entry)
DesktopEntry * desktop_entry_copy (DesktopEntry *entry)
DesktopEntry * desktop_entry_reload (DesktopEntry *entry)
void desktop_entry_unref (DesktopEntry *entry)
DesktopEntryType desktop_entry_get_type (DesktopEntry *entry)
const char * desktop_entry_get_path (DesktopEntry *entry)
const char * desktop_entry_get_basename (DesktopEntry *entry)
const char * desktop_entry_get_name (DesktopEntry *entry)
const char * desktop_entry_get_generic_name (DesktopEntry *entry)
const char * desktop_entry_get_comment (DesktopEntry *entry)
GIcon * desktop_entry_get_icon (DesktopEntry *entry)
gboolean desktop_entry_get_hidden (DesktopEntry *entry)
gboolean desktop_entry_get_no_display (DesktopEntry *entry)
gboolean desktop_entry_get_show_in (DesktopEntry *entry)
GDesktopAppInfo * desktop_entry_get_app_info (DesktopEntry *entry)
gboolean desktop_entry_has_categories (DesktopEntry *entry)
gboolean desktop_entry_has_category (DesktopEntry *entry, const char *category)
void desktop_entry_add_legacy_category (DesktopEntry *src)
DesktopEntrySet * desktop_entry_set_new (void)
DesktopEntrySet * desktop_entry_set_ref (DesktopEntrySet *set)
void desktop_entry_set_unref (DesktopEntrySet *set)
void desktop_entry_set_add_entry (DesktopEntrySet *set, DesktopEntry *entry, const char *file_id)
DesktopEntry * desktop_entry_set_lookup (DesktopEntrySet *set, const char *file_id)
guint desktop_entry_set_get_count (DesktopEntrySet *set)
void desktop_entry_set_union (DesktopEntrySet *set, DesktopEntrySet *with)
void desktop_entry_set_intersection (DesktopEntrySet *set, DesktopEntrySet *with)
void desktop_entry_set_subtract (DesktopEntrySet *set, DesktopEntrySet *other)
void desktop_entry_set_swap_contents (DesktopEntrySet *a, DesktopEntrySet *b)
void desktop_entry_set_foreach (DesktopEntrySet *set, DesktopEntrySetForeachFunc func, gpointer user_data)
Typedef Documentation
DesktopEntry
typedef struct DesktopEntry DesktopEntry
Definition at line 34 of file desktop-entries.h.
DesktopEntrySet
typedef struct DesktopEntrySet DesktopEntrySet
Definition at line 62 of file desktop-entries.h.
DesktopEntrySetForeachFunc
typedef void(* DesktopEntrySetForeachFunc) (const char *file_id, DesktopEntry *entry, gpointer user_data)
Definition at line 77 of file desktop-entries.h.
Enumeration Type Documentation
DesktopEntryType
enum DesktopEntryType
Enumerator
DESKTOP_ENTRY_INVALID
DESKTOP_ENTRY_DESKTOP
DESKTOP_ENTRY_DIRECTORY
Definition at line 28 of file desktop-entries.h.
Function Documentation
desktop_entry_add_legacy_category()
void desktop_entry_add_legacy_category (DesktopEntry * src)
Definition at line 626 of file desktop-entries.c.
References DESKTOP_ENTRY_DESKTOP, and NULL.
desktop_entry_copy()
DesktopEntry * desktop_entry_copy (DesktopEntry * entry)
Definition at line 410 of file desktop-entries.c.
References DESKTOP_ENTRY_DESKTOP, DESKTOP_ENTRY_DIRECTORY, and NULL.
desktop_entry_get_app_info()
GDesktopAppInfo * desktop_entry_get_app_info (DesktopEntry * entry)
Definition at line 584 of file desktop-entries.c.
References DESKTOP_ENTRY_DESKTOP, and NULL.
Referenced by matemenu_tree_entry_get_app_info().
desktop_entry_get_basename()
const char * desktop_entry_get_basename (DesktopEntry * entry)
Definition at line 520 of file desktop-entries.c.
Referenced by entry_directory_get_flat_contents(), and matemenu_tree_directory_make_path().
desktop_entry_get_comment()
const char * desktop_entry_get_comment (DesktopEntry * entry)
Definition at line 539 of file desktop-entries.c.
References DESKTOP_ENTRY_DESKTOP.
Referenced by matemenu_tree_directory_get_comment().
desktop_entry_get_generic_name()
const char * desktop_entry_get_generic_name (DesktopEntry * entry)
Definition at line 532 of file desktop-entries.c.
References DESKTOP_ENTRY_DESKTOP.
Referenced by matemenu_tree_directory_get_generic_name().
desktop_entry_get_hidden()
gboolean desktop_entry_get_hidden (DesktopEntry * entry)
Definition at line 561 of file desktop-entries.c.
References DESKTOP_ENTRY_DESKTOP.
desktop_entry_get_icon()
GIcon * desktop_entry_get_icon (DesktopEntry * entry)
Definition at line 547 of file desktop-entries.c.
References DESKTOP_ENTRY_DESKTOP.
Referenced by matemenu_tree_directory_get_icon().
desktop_entry_get_name()
const char * desktop_entry_get_name (DesktopEntry * entry)
Definition at line 525 of file desktop-entries.c.
References DESKTOP_ENTRY_DESKTOP.
Referenced by matemenu_tree_directory_get_name().
desktop_entry_get_no_display()
gboolean desktop_entry_get_no_display (DesktopEntry * entry)
Definition at line 554 of file desktop-entries.c.
References DESKTOP_ENTRY_DESKTOP.
desktop_entry_get_path()
const char * desktop_entry_get_path (DesktopEntry * entry)
Definition at line 514 of file desktop-entries.c.
Referenced by matemenu_tree_directory_get_desktop_file_path(), and matemenu_tree_entry_get_desktop_file_path().
desktop_entry_get_show_in()
gboolean desktop_entry_get_show_in (DesktopEntry * entry)
Definition at line 569 of file desktop-entries.c.
References DESKTOP_ENTRY_DESKTOP, NULL, and TRUE.
desktop_entry_get_type()
DesktopEntryType desktop_entry_get_type (DesktopEntry * entry)
Definition at line 509 of file desktop-entries.c.
Referenced by entry_directory_get_flat_contents().
desktop_entry_has_categories()
gboolean desktop_entry_has_categories (DesktopEntry * entry)
Definition at line 590 of file desktop-entries.c.
References DESKTOP_ENTRY_DESKTOP, FALSE, and NULL.
desktop_entry_has_category()
gboolean desktop_entry_has_category (DesktopEntry * entry, const char * category)
Definition at line 600 of file desktop-entries.c.
References category, DESKTOP_ENTRY_DESKTOP, FALSE, NULL, and TRUE.
desktop_entry_new()
DesktopEntry * desktop_entry_new (const char * path)
Definition at line 321 of file desktop-entries.c.
References DESKTOP_ENTRY_DESKTOP, DESKTOP_ENTRY_DIRECTORY, desktop_entry_unref(), and NULL.
desktop_entry_ref()
DesktopEntry * desktop_entry_ref (DesktopEntry * entry)
Definition at line 400 of file desktop-entries.c.
References NULL.
Referenced by desktop_entry_set_add_entry().
desktop_entry_reload()
DesktopEntry * desktop_entry_reload (DesktopEntry * entry)
Definition at line 359 of file desktop-entries.c.
References DESKTOP_ENTRY_DESKTOP, DESKTOP_ENTRY_DIRECTORY, desktop_entry_unref(), and NULL.
desktop_entry_set_add_entry()
void desktop_entry_set_add_entry (DesktopEntrySet * set, DesktopEntry * entry, const char * file_id)
Definition at line 706 of file desktop-entries.c.
References desktop_entry_ref(), desktop_entry_unref(), NULL, and set.
Referenced by entry_directory_get_flat_contents().
desktop_entry_set_foreach()
void desktop_entry_set_foreach (DesktopEntrySet * set, DesktopEntrySetForeachFunc func, gpointer user_data)
Definition at line 741 of file desktop-entries.c.
References NULL, set, and user_data.
desktop_entry_set_get_count()
guint desktop_entry_set_get_count (DesktopEntrySet * set)
Definition at line 771 of file desktop-entries.c.
References NULL, and set.
Referenced by desktop_entry_set_intersection(), desktop_entry_set_subtract(), and desktop_entry_set_union().
desktop_entry_set_intersection()
void desktop_entry_set_intersection (DesktopEntrySet * set, DesktopEntrySet * with)
Definition at line 818 of file desktop-entries.c.
References desktop_entry_set_get_count(), and set.
desktop_entry_set_lookup()
DesktopEntry * desktop_entry_set_lookup (DesktopEntrySet * set, const char * file_id)
Definition at line 723 of file desktop-entries.c.
References NULL, and set.
desktop_entry_set_new()
DesktopEntrySet * desktop_entry_set_new (void)
Definition at line 666 of file desktop-entries.c.
References set.
Referenced by _entry_directory_list_get_all_desktops().
desktop_entry_set_ref()
DesktopEntrySet * desktop_entry_set_ref (DesktopEntrySet * set)
Definition at line 678 of file desktop-entries.c.
References NULL, and set.
Referenced by _entry_directory_list_get_all_desktops().
desktop_entry_set_subtract()
void desktop_entry_set_subtract (DesktopEntrySet * set, DesktopEntrySet * other)
Definition at line 857 of file desktop-entries.c.
References desktop_entry_set_get_count(), and set.
desktop_entry_set_swap_contents()
void desktop_entry_set_swap_contents (DesktopEntrySet * a, DesktopEntrySet * b)
Definition at line 875 of file desktop-entries.c.
References b.
desktop_entry_set_union()
void desktop_entry_set_union (DesktopEntrySet * set, DesktopEntrySet * with)
Definition at line 789 of file desktop-entries.c.
References desktop_entry_set_get_count(), and set.
desktop_entry_set_unref()
void desktop_entry_set_unref (DesktopEntrySet * set)
Definition at line 688 of file desktop-entries.c.
References NULL, and set.
Referenced by _entry_directory_list_empty_desktop_cache(), and _entry_directory_list_get_all_desktops().
desktop_entry_unref()
void desktop_entry_unref (DesktopEntry * entry)
Definition at line 468 of file desktop-entries.c.
References DESKTOP_ENTRY_DESKTOP, DESKTOP_ENTRY_DIRECTORY, and NULL.
Referenced by desktop_entry_new(), desktop_entry_reload(), and desktop_entry_set_add_entry().