MATE Desktop Environment: dialog-main.c File Reference
dialog-main.c File Reference
#include "config.h"
#include <glib.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <libintl.h>
#include <gio/gio.h>
#include <libmatemixer/matemixer.h>
#include "gvc-mixer-dialog.h"
Macros
#define DIALOG_POPUP_TIMEOUT 3
Functions
int main (int argc, char **argv)
Macro Definition Documentation
DIALOG_POPUP_TIMEOUT
#define DIALOG_POPUP_TIMEOUT 3
Definition at line 35 of file dialog-main.c.
Referenced by main().
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 183 of file dialog-main.c.
References _, debug, DIALOG_POPUP_TIMEOUT, error, FALSE, GETTEXT_PACKAGE, GVC_DIALOG_DBUS_NAME, MATE_MIXER_BACKEND_ALSA, MATE_MIXER_BACKEND_NULL, MATE_MIXER_BACKEND_OSS, MATE_MIXER_BACKEND_PULSEAUDIO, mate_mixer_context_get_state(), mate_mixer_context_new(), mate_mixer_context_open(), mate_mixer_context_set_app_icon(), mate_mixer_context_set_app_id(), mate_mixer_context_set_app_name(), mate_mixer_context_set_app_version(), mate_mixer_context_set_backend_type(), mate_mixer_init(), MATE_MIXER_STATE_CONNECTING, N_, NULL, TRUE, and VERSION.