MATE Desktop Environment: display.h File Reference
display.h File Reference
#include <glib.h>
#include <X11/Xlib.h>
#include "types.h"
Macros
#define meta_XFree(p)
Functions
Display * meta_display_get_xdisplay (MetaDisplay *display)
MetaCompositor * meta_display_get_compositor (MetaDisplay *display)
GSList * meta_display_get_screens (MetaDisplay *display)
gboolean meta_display_has_shape (MetaDisplay *display)
MetaScreen * meta_display_screen_for_root (MetaDisplay *display, Window xroot)
MetaWindow * meta_display_get_focus_window (MetaDisplay *display)
int meta_display_get_damage_event_base (MetaDisplay *display)
int meta_display_get_shape_event_base (MetaDisplay *display)
Macro Definition Documentation
meta_XFree
#define meta_XFree (p)
Value:
do { if ((p)) XFree ((p)); } while (0)
Definition at line 30 of file display.h.
Referenced by meta_display_shutdown_keys(), meta_prop_get_values(), meta_screen_update_workspace_layout(), meta_window_client_message(), meta_window_get_icon_geometry(), meta_window_update_net_wm_type(), meta_window_update_role(), and meta_window_update_struts().
Function Documentation
meta_display_get_compositor()
MetaCompositor * meta_display_get_compositor (MetaDisplay * display)
Definition at line 5522 of file display.c.
References _MetaDisplay::compositor.
Referenced by meta_frames_apply_shapes().
meta_display_get_damage_event_base()
int meta_display_get_damage_event_base (MetaDisplay * display)
meta_display_get_focus_window()
MetaWindow * meta_display_get_focus_window (MetaDisplay * display)
Definition at line 5540 of file display.c.
meta_display_get_screens()
GSList * meta_display_get_screens (MetaDisplay * display)
Definition at line 5528 of file display.c.
References _MetaDisplay::screens.
meta_display_get_shape_event_base()
int meta_display_get_shape_event_base (MetaDisplay * display)
meta_display_get_xdisplay()
Display * meta_display_get_xdisplay (MetaDisplay * display)
Definition at line 5516 of file display.c.
References _MetaDisplay::xdisplay.
Referenced by meta_error_trap_pop(), meta_error_trap_pop_with_return(), and meta_error_trap_push().
meta_display_has_shape()
gboolean meta_display_has_shape (MetaDisplay * display)
Definition at line 5534 of file display.c.
References META_DISPLAY_HAS_SHAPE.
meta_display_screen_for_root()
MetaScreen * meta_display_screen_for_root (MetaDisplay * display, Window xroot)
Definition at line 962 of file display.c.
References NULL, and _MetaDisplay::screens.
Referenced by meta_core_get_workspace_name_with_index(), and meta_display_process_key_event().