MATE Desktop Environment: display-private.h File Reference
display-private.h File Reference
#include <glib.h>
#include <X11/Xlib.h>
#include "eventqueue.h"
#include "common.h"
#include "boxes.h"
#include "display.h"
#include "atomnames.h"
Classes
struct _MetaDisplay
Macros
#define _NET_WM_STATE_REMOVE 0 /* remove/unset property */
#define _NET_WM_STATE_ADD 1 /* add/set property */
#define _NET_WM_STATE_TOGGLE 2 /* toggle property */
#define N_IGNORED_SERIALS 4
#define item(x)
#define META_DISPLAY_HAS_XSYNC(display)
#define META_DISPLAY_HAS_SHAPE(display)
#define META_DISPLAY_HAS_RENDER(display)
#define META_DISPLAY_HAS_COMPOSITE(display)
#define META_DISPLAY_HAS_DAMAGE(display)
#define META_DISPLAY_HAS_XFIXES(display)
#define XSERVER_TIME_IS_BEFORE_ASSUMING_REAL_TIMESTAMPS(time1, time2)
#define XSERVER_TIME_IS_BEFORE(time1, time2)
Typedefs
typedef struct _MetaKeyBinding MetaKeyBinding
typedef struct _MetaStack MetaStack
typedef struct _MetaUISlave MetaUISlave
typedef struct _MetaWorkspace MetaWorkspace
typedef struct _MetaGroupPropHooks MetaGroupPropHooks
typedef struct MetaEdgeResistanceData MetaEdgeResistanceData
typedef void(* MetaWindowPingFunc) (MetaDisplay *display, Window xwindow, guint32 timestamp, gpointer user_data)
Enumerations
enum MetaTileMode {
META_TILE_NONE , META_TILE_LEFT , META_TILE_RIGHT , META_TILE_MAXIMIZED ,
META_TILE_TOP_LEFT , META_TILE_TOP_RIGHT , META_TILE_BOTTOM_LEFT , META_TILE_BOTTOM_RIGHT
}
enum MetaTabList { META_TAB_LIST_NORMAL , META_TAB_LIST_DOCKS , META_TAB_LIST_GROUP , META_TAB_LIST_NORMAL_ALL_WORKSPACES }
enum MetaTabShowType { META_TAB_SHOW_ICON , META_TAB_SHOW_INSTANTLY }
Functions
gboolean meta_display_open (void)
void meta_display_close (MetaDisplay *display, guint32 timestamp)
MetaScreen * meta_display_screen_for_x_screen (MetaDisplay *display, Screen *screen)
MetaScreen * meta_display_screen_for_xwindow (MetaDisplay *display, Window xindow)
void meta_display_grab (MetaDisplay *display)
void meta_display_ungrab (MetaDisplay *display)
void meta_display_unmanage_screen (MetaDisplay *display, MetaScreen *screen, guint32 timestamp)
void meta_display_unmanage_windows_for_screen (MetaDisplay *display, MetaScreen *screen, guint32 timestamp)
int meta_display_stack_cmp (const void *a, const void *b)
MetaWindow * meta_display_lookup_x_window (MetaDisplay *display, Window xwindow)
void meta_display_register_x_window (MetaDisplay *display, Window *xwindowp, MetaWindow *window)
void meta_display_unregister_x_window (MetaDisplay *display, Window xwindow)
gboolean meta_display_xwindow_is_a_no_focus_window (MetaDisplay *display, Window xwindow)
GSList * meta_display_list_windows (MetaDisplay *display)
MetaDisplay * meta_display_for_x_display (Display *xdisplay)
MetaDisplay * meta_get_display (void)
Cursor meta_display_create_x_cursor (MetaDisplay *display, MetaCursor cursor)
void meta_display_set_grab_op_cursor (MetaDisplay *display, MetaScreen *screen, MetaGrabOp op, gboolean change_pointer, Window grab_xwindow, guint32 timestamp)
gboolean meta_display_begin_grab_op (MetaDisplay *display, MetaScreen *screen, MetaWindow *window, MetaGrabOp op, gboolean pointer_already_grabbed, gboolean frame_action, int button, gulong modmask, guint32 timestamp, int root_x, int root_y)
void meta_display_end_grab_op (MetaDisplay *display, guint32 timestamp)
void meta_display_check_threshold_reached (MetaDisplay *display, int x, int y)
void meta_display_grab_window_buttons (MetaDisplay *display, Window xwindow)
void meta_display_ungrab_window_buttons (MetaDisplay *display, Window xwindow)
void meta_display_grab_focus_window_button (MetaDisplay *display, MetaWindow *window)
void meta_display_ungrab_focus_window_button (MetaDisplay *display, MetaWindow *window)
void meta_display_cleanup_edges (MetaDisplay *display)
void meta_display_increment_event_serial (MetaDisplay *display)
void meta_display_update_active_window_hint (MetaDisplay *display)
guint32 meta_display_get_current_time (MetaDisplay *display)
guint32 meta_display_get_current_time_roundtrip (MetaDisplay *display)
const char * meta_event_mode_to_string (int m)
const char * meta_event_detail_to_string (int d)
void meta_display_queue_retheme_all_windows (MetaDisplay *display)
void meta_display_retheme_all (void)
void meta_display_set_cursor_theme (const char *theme, int size)
void meta_display_ping_window (MetaDisplay *display, MetaWindow *window, guint32 timestamp, MetaWindowPingFunc ping_reply_func, MetaWindowPingFunc ping_timeout_func, void *user_data)
gboolean meta_display_window_has_pending_pings (MetaDisplay *display, MetaWindow *window)
GList * meta_display_get_tab_list (MetaDisplay *display, MetaTabList type, MetaScreen *screen, MetaWorkspace *workspace)
MetaWindow * meta_display_get_tab_next (MetaDisplay *display, MetaTabList type, MetaScreen *screen, MetaWorkspace *workspace, MetaWindow *window, gboolean backward)
MetaWindow * meta_display_get_tab_current (MetaDisplay *display, MetaTabList type, MetaScreen *screen, MetaWorkspace *workspace)
int meta_resize_gravity_from_grab_op (MetaGrabOp op)
gboolean meta_grab_op_is_moving (MetaGrabOp op)
gboolean meta_grab_op_is_resizing (MetaGrabOp op)
void meta_display_devirtualize_modifiers (MetaDisplay *display, MetaVirtualModifier modifiers, unsigned int *mask)
void meta_display_increment_focus_sentinel (MetaDisplay *display)
void meta_display_decrement_focus_sentinel (MetaDisplay *display)
gboolean meta_display_focus_sentinel_clear (MetaDisplay *display)
void meta_display_set_input_focus_window (MetaDisplay *display, MetaWindow *window, gboolean focus_frame, guint32 timestamp)
void meta_display_focus_the_no_focus_window (MetaDisplay *display, MetaScreen *screen, guint32 timestamp)
void meta_display_queue_autoraise_callback (MetaDisplay *display, MetaWindow *window)
void meta_display_remove_autoraise_callback (MetaDisplay *display)
Macro Definition Documentation
_NET_WM_STATE_ADD
#define _NET_WM_STATE_ADD 1 /* add/set property */
Definition at line 59 of file display-private.h.
Referenced by meta_window_client_message().
_NET_WM_STATE_REMOVE
#define _NET_WM_STATE_REMOVE 0 /* remove/unset property */
Definition at line 58 of file display-private.h.
_NET_WM_STATE_TOGGLE
#define _NET_WM_STATE_TOGGLE 2 /* toggle property */
Definition at line 60 of file display-private.h.
Referenced by meta_window_client_message().
item
#define item (x)
Value:
Atom atom_##x;
Definition at line 91 of file display-private.h.
Referenced by _pluma_file_browser_store_iter_collapsed(), _pluma_panel_get_active_item_id(), _pluma_panel_set_active_item_by_id(), alsa_stream_load_elements(), alsa_stream_remove_elements(), bacon_video_widget_properties_reset(), bacon_video_widget_properties_set_has_type(), bacon_video_widget_properties_set_label(), baobab_chart_save_snapshot(), bookmark_agent_add_item(), bookmark_agent_update_from_bookmark_file(), bookmark_item_free(), cact_export_ask_user(), cact_tree_ieditable_remove_deleted(), cact_tree_view_get_item_by_id(), cadp_iio_provider_delete_item(), cadp_iio_provider_read_items(), cadp_iio_provider_write_item(), caja_action_from_menu_item(), caja_directory_schedule_position_set(), caja_drag_build_selection_list(), caja_drag_items_on_desktop(), caja_icon_canvas_item_get_drag_surface(), caja_icon_canvas_item_get_icon_rectangle(), caja_icon_canvas_item_get_max_text_width(), caja_icon_canvas_item_get_text_rectangle(), caja_icon_canvas_item_get_type(), caja_icon_canvas_item_hit_test_rectangle(), caja_icon_canvas_item_hit_test_stretch_handles(), caja_icon_canvas_item_invalidate_label(), caja_icon_canvas_item_invalidate_label_size(), caja_icon_canvas_item_set_attach_points(), caja_icon_canvas_item_set_embedded_text(), caja_icon_canvas_item_set_embedded_text_rect(), caja_icon_canvas_item_set_emblems(), caja_icon_canvas_item_set_entire_text(), caja_icon_canvas_item_set_image(), caja_icon_canvas_item_set_is_visible(), caja_icon_canvas_item_set_renaming(), caja_icon_canvas_item_set_show_stretch_handles(), caja_icon_canvas_item_update_bounds(), caja_icon_container_add(), caja_image_converter_get_file_items(), caja_link_local_create(), caja_menu_append_item(), caja_menu_get_type(), caja_menu_item_activate(), caja_menu_item_new(), caja_menu_item_set_submenu(), caja_navigation_window_activate_spinner(), caja_navigation_window_load_extension_toolbar_items(), caja_toolbar_action_from_menu_item(), caja_undostack_manager_undo(), const_cb(), eel_canvas_get_item_at(), eel_canvas_item_construct(), eel_canvas_item_destroy(), eel_canvas_item_get_bounds(), eel_canvas_item_grab(), eel_canvas_item_grab_focus(), eel_canvas_item_hide(), eel_canvas_item_i2w(), eel_canvas_item_lower(), eel_canvas_item_lower_to_bottom(), eel_canvas_item_move(), eel_canvas_item_new(), eel_canvas_item_raise(), eel_canvas_item_raise_to_top(), eel_canvas_item_reparent(), eel_canvas_item_request_redraw(), eel_canvas_item_request_update(), eel_canvas_item_send_behind(), eel_canvas_item_set(), eel_canvas_item_set_valist(), eel_canvas_item_show(), eel_canvas_item_ungrab(), eel_canvas_item_w2i(), egg_toolbars_model_delete_item(), egg_toolbars_model_item_nth(), eom_thumb_view_get_selected_images(), function_cb(), G_DEFINE_ABSTRACT_TYPE_WITH_CODE(), G_DEFINE_DYNAMIC_TYPE_EXTENDED(), G_DEFINE_DYNAMIC_TYPE_EXTENDED(), G_DEFINE_INTERFACE_WITH_CODE(), G_DEFINE_TYPE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_PRIVATE(), G_DEFINE_TYPE_WITH_PRIVATE(), generate_categories(), gsearchtool_set_columns_order(), handle_static_action_clicked(), libslab_mate_desktop_item_new_from_unknown_id(), load_desktop_item_from_unknown(), main(), mate_desktop_item_attr_exists(), mate_desktop_item_clear_localestring(), mate_desktop_item_clear_section(), mate_desktop_item_copy(), mate_desktop_item_drop_uri_list(), mate_desktop_item_drop_uri_list_with_env(), mate_desktop_item_exists(), mate_desktop_item_get_attr_locale(), mate_desktop_item_get_boolean(), mate_desktop_item_get_entry_type(), mate_desktop_item_get_file_status(), mate_desktop_item_get_icon(), mate_desktop_item_get_languages(), mate_desktop_item_get_localestring(), mate_desktop_item_get_localestring_lang(), mate_desktop_item_get_location(), mate_desktop_item_get_string(), mate_desktop_item_get_strings(), mate_desktop_item_launch(), mate_desktop_item_launch_on_screen(), mate_desktop_item_launch_with_env(), mate_desktop_item_ref(), mate_desktop_item_save(), mate_desktop_item_set_boolean(), mate_desktop_item_set_entry_type(), mate_desktop_item_set_launch_time(), mate_desktop_item_set_localestring(), mate_desktop_item_set_localestring_lang(), mate_desktop_item_set_location(), mate_desktop_item_set_location_file(), mate_desktop_item_set_string(), mate_desktop_item_set_strings(), mate_desktop_item_unref(), mate_ui_context_menu_add_item(), mate_ui_menu_add_recent_chooser(), mate_ui_menu_item_new_with_action(), mate_ui_menu_item_new_with_icon(), mate_ui_menu_model_new_from_entries(), mate_ui_menu_new_from_entries(), mate_wp_item_ensure_mate_bg(), mate_wp_item_free(), mate_wp_item_get_frame_thumbnail(), mate_wp_item_get_frame_thumbnail(), mate_wp_item_get_thumbnail(), mate_wp_item_new(), mate_wp_item_update(), mate_wp_item_update_description(), matemenu_tree_item_ref(), matemenu_tree_item_unref(), meta_prefs_is_in_skip_list(), na_exporter_to_buffer(), na_exporter_to_file(), na_host_emit_item_added(), na_host_emit_item_removed(), na_host_get_type(), na_io_provider_delete_item(), na_io_provider_write_item(), na_item_draw_on_parent(), na_item_get_category(), na_item_get_id(), na_item_get_type(), na_object_item_append_item(), na_object_item_deals_with_version(), na_object_item_get_item(), na_object_item_get_items_count(), na_object_item_get_position(), na_object_item_insert_at(), na_object_item_insert_item(), na_object_item_is_finally_writable(), na_object_item_rebuild_children_slist(), na_object_item_remove_item(), na_object_item_set_writability_status(), na_selected_info_get_list_from_item(), na_updater_append_item(), na_updater_check_item_writability_status(), na_updater_delete_item(), na_updater_insert_item(), na_updater_remove_item(), na_updater_should_pasted_be_relabeled(), na_updater_write_item(), oss_device_load(), panel_addto_present(), panel_desktop_menu_item_get_type(), panel_desktop_menu_item_set_panel(), panel_menu_items_append_lock_logout(), panel_place_menu_item_set_panel(), pluma_file_browser_widget_remove_filter(), pluma_metadata_manager_get(), pluma_metadata_manager_set(), pluma_override_font(), pluma_panel_activate_item(), pluma_panel_add_item(), pluma_panel_add_item_with_icon(), pluma_panel_get_type(), pluma_panel_item_is_active(), pluma_panel_remove_item(), pluma_status_combo_box_add_item(), pluma_status_combo_box_get_item_text(), pluma_status_combo_box_get_type(), pluma_status_combo_box_remove_item(), pluma_status_combo_box_set_item(), pluma_status_combo_box_set_item_text(), popup_toggle_lock_cb(), pulse_device_switch_set_active_profile_by_name(), pulse_port_switch_set_active_port_by_name(), shift_left_cb(), shift_right_cb(), sn_dbus_menu_item_free(), sn_dbus_menu_item_new(), sn_dbus_menu_item_remove_props(), sn_dbus_menu_item_update_props(), sn_item_emit_ready(), sn_item_get_bus_name(), sn_item_get_object_path(), sn_item_get_type(), task_item_get_desktop_visible(), and task_item_new().
META_DISPLAY_HAS_COMPOSITE
#define META_DISPLAY_HAS_COMPOSITE (display)
Value:
FALSE
Definition at line 409 of file display-private.h.
META_DISPLAY_HAS_DAMAGE
#define META_DISPLAY_HAS_DAMAGE (display)
Value:
FALSE
Definition at line 410 of file display-private.h.
META_DISPLAY_HAS_RENDER
#define META_DISPLAY_HAS_RENDER (display)
Value:
FALSE
Definition at line 398 of file display-private.h.
META_DISPLAY_HAS_SHAPE
#define META_DISPLAY_HAS_SHAPE (display)
Value:
FALSE
Definition at line 391 of file display-private.h.
Referenced by meta_display_has_shape(), meta_window_free(), and meta_window_new_with_attrs().
META_DISPLAY_HAS_XFIXES
#define META_DISPLAY_HAS_XFIXES (display)
Value:
FALSE
Definition at line 411 of file display-private.h.
META_DISPLAY_HAS_XSYNC
#define META_DISPLAY_HAS_XSYNC (display)
Value:
FALSE
Definition at line 384 of file display-private.h.
N_IGNORED_SERIALS
#define N_IGNORED_SERIALS 4
Definition at line 67 of file display-private.h.
XSERVER_TIME_IS_BEFORE
#define XSERVER_TIME_IS_BEFORE (time1, time2)
Value:
((time1) == 0 || \
    (XSERVER_TIME_IS_BEFORE_ASSUMING_REAL_TIMESTAMPS(time1, time2) && \
    (time2) != 0) \
)
Definition at line 343 of file display-private.h.
Referenced by meta_window_configure_request(), and meta_window_set_user_time().
XSERVER_TIME_IS_BEFORE_ASSUMING_REAL_TIMESTAMPS
#define XSERVER_TIME_IS_BEFORE_ASSUMING_REAL_TIMESTAMPS (time1, time2)
Value:
((((time1) < (time2)) && ((time2) - (time1) < ((guint32)-1)/2)) || \
    (( (time1) > (time2) ) && ( (time1) - (time2) > ((guint32)-1)/2 )) \
)
Definition at line 339 of file display-private.h.
Typedef Documentation
MetaEdgeResistanceData
typedef struct MetaEdgeResistanceData MetaEdgeResistanceData
Definition at line 54 of file display-private.h.
MetaGroupPropHooks
typedef struct _MetaGroupPropHooks MetaGroupPropHooks
Definition at line 52 of file display-private.h.
MetaKeyBinding
typedef struct _MetaKeyBinding MetaKeyBinding
Definition at line 47 of file display-private.h.
MetaStack
typedef struct _MetaStack MetaStack
Definition at line 48 of file display-private.h.
MetaUISlave
typedef struct _MetaUISlave MetaUISlave
Definition at line 49 of file display-private.h.
MetaWindowPingFunc
typedef void(* MetaWindowPingFunc) (MetaDisplay *display, Window xwindow, guint32 timestamp, gpointer user_data)
Definition at line 56 of file display-private.h.
MetaWorkspace
typedef struct _MetaWorkspace MetaWorkspace
Definition at line 50 of file display-private.h.
Enumeration Type Documentation
MetaTabList
enum MetaTabList
Enumerator
META_TAB_LIST_NORMAL
META_TAB_LIST_DOCKS
META_TAB_LIST_GROUP
META_TAB_LIST_NORMAL_ALL_WORKSPACES
Definition at line 457 of file display-private.h.
MetaTabShowType
enum MetaTabShowType
Enumerator
META_TAB_SHOW_ICON
META_TAB_SHOW_INSTANTLY
Definition at line 465 of file display-private.h.
MetaTileMode
enum MetaTileMode
Enumerator
META_TILE_NONE
META_TILE_LEFT
META_TILE_RIGHT
META_TILE_MAXIMIZED
META_TILE_TOP_LEFT
META_TILE_TOP_RIGHT
META_TILE_BOTTOM_LEFT
META_TILE_BOTTOM_RIGHT
Definition at line 69 of file display-private.h.
Function Documentation
meta_display_begin_grab_op()
gboolean meta_display_begin_grab_op (MetaDisplay * display, MetaScreen * screen, MetaWindow * window, MetaGrabOp op, gboolean pointer_already_grabbed, gboolean frame_action, int button, gulong modmask, guint32 timestamp, int root_x, int root_y)
Definition at line 3554 of file display.c.
References _MetaDisplay::compositor, _MetaWindow::desc, FALSE, _MetaDisplay::grab_anchor_root_x, _MetaDisplay::grab_anchor_root_y, _MetaDisplay::grab_anchor_window_pos, _MetaDisplay::grab_button, _MetaDisplay::grab_frame_action, _MetaDisplay::grab_have_keyboard, _MetaDisplay::grab_have_pointer, _MetaDisplay::grab_initial_window_pos, _MetaDisplay::grab_initial_x, _MetaDisplay::grab_initial_y, _MetaDisplay::grab_last_moveresize_time, _MetaDisplay::grab_last_user_action_was_snap, _MetaDisplay::grab_latest_motion_x, _MetaDisplay::grab_latest_motion_y, _MetaDisplay::grab_mask, _MetaDisplay::grab_motion_notify_time, _MetaDisplay::grab_old_window_stacking, _MetaDisplay::grab_op, GRAB_OP_IS_WINDOW_SWITCH, _MetaDisplay::grab_resize_timeout_id, _MetaDisplay::grab_screen, _MetaDisplay::grab_threshold_movement_reached, _MetaDisplay::grab_tile_mode, _MetaDisplay::grab_tile_monitor_number, _MetaDisplay::grab_was_cancelled, _MetaDisplay::grab_window, _MetaDisplay::grab_wireframe_active, _MetaDisplay::grab_xwindow, meta_compositor_begin_move(), META_DEBUG_RESIZING, META_DEBUG_WINDOW_OPS, meta_display_set_grab_op_cursor(), meta_error_trap_pop_with_return(), meta_error_trap_push(), meta_grab_op_is_moving(), meta_grab_op_is_resizing(), META_GRAB_OP_KEYBOARD_ESCAPING_DOCK, META_GRAB_OP_KEYBOARD_ESCAPING_GROUP, META_GRAB_OP_KEYBOARD_ESCAPING_NORMAL, META_GRAB_OP_KEYBOARD_ESCAPING_NORMAL_ALL_WORKSPACES, META_GRAB_OP_KEYBOARD_TABBING_DOCK, META_GRAB_OP_KEYBOARD_TABBING_GROUP, META_GRAB_OP_KEYBOARD_TABBING_NORMAL, META_GRAB_OP_KEYBOARD_TABBING_NORMAL_ALL_WORKSPACES, META_GRAB_OP_KEYBOARD_WORKSPACE_MOVING, META_GRAB_OP_KEYBOARD_WORKSPACE_SWITCHING, META_GRAB_OP_NONE, meta_prefs_get_mate_accessibility(), meta_prefs_get_raise_on_click(), meta_prefs_get_reduced_resources(), meta_screen_ensure_tab_popup(), meta_screen_ensure_workspace_popup(), meta_screen_grab_all_keys(), meta_stack_get_positions(), META_TAB_LIST_DOCKS, META_TAB_LIST_GROUP, META_TAB_LIST_NORMAL, META_TAB_LIST_NORMAL_ALL_WORKSPACES, META_TAB_SHOW_ICON, META_TAB_SHOW_INSTANTLY, META_TILE_NONE, meta_warning(), meta_window_begin_wireframe(), meta_window_calc_showing(), meta_window_get_client_root_coords(), meta_window_grab_all_keys(), meta_window_raise(), meta_window_refresh_resize_popup(), NULL, op, _MetaDisplay::tab_popup_mouse_pressed, TRUE, and _MetaDisplay::xdisplay.
Referenced by meta_core_begin_grab_op(), meta_window_begin_grab_op(), and meta_window_client_message().
meta_display_check_threshold_reached()
void meta_display_check_threshold_reached (MetaDisplay * display, int x, int y)
Definition at line 3986 of file display.c.
References FALSE, _MetaDisplay::grab_initial_x, _MetaDisplay::grab_initial_y, _MetaDisplay::grab_threshold_movement_reached, meta_prefs_get_raise_on_click(), and TRUE.
Referenced by meta_window_handle_mouse_grab_op_event().
meta_display_cleanup_edges()
void meta_display_cleanup_edges (MetaDisplay * display)
Definition at line 672 of file edge-resistance.c.
References _MetaEdge::edge_type, _MetaDisplay::grab_edge_resistance_data, META_EDGE_WINDOW, META_SIDE_BOTTOM, META_SIDE_LEFT, META_SIDE_RIGHT, META_SIDE_TOP, NULL, _MetaEdge::side_type, and TRUE.
Referenced by meta_display_end_grab_op(), meta_workspace_activate_with_focus(), and meta_workspace_invalidate_work_area().
meta_display_close()
void meta_display_close (MetaDisplay * display, guint32 timestamp)
Definition at line 885 of file display.c.
References _MetaDisplay::closing, _MetaDisplay::compositor, _MetaDisplay::error_traps, _MetaDisplay::grab_old_window_stacking, _MetaDisplay::leader_window, meta_bug(), meta_compositor_destroy(), meta_display_free_group_prop_hooks(), meta_display_free_window_prop_hooks(), meta_display_remove_autoraise_callback(), meta_display_shutdown_keys(), META_EXIT_SUCCESS, meta_prefs_remove_listener(), meta_quit(), meta_screen_free(), meta_ui_remove_event_func(), _MetaDisplay::name, NULL, _MetaDisplay::screens, _MetaDisplay::window_ids, and _MetaDisplay::xdisplay.
Referenced by meta_display_unmanage_screen().
meta_display_create_x_cursor()
Cursor meta_display_create_x_cursor (MetaDisplay * display, MetaCursor cursor)
Definition at line 3376 of file display.c.
References META_CURSOR_BUSY, META_CURSOR_DEFAULT, META_CURSOR_EAST_RESIZE, META_CURSOR_MOVE_OR_RESIZE_WINDOW, META_CURSOR_NE_RESIZE, META_CURSOR_NORTH_RESIZE, META_CURSOR_NW_RESIZE, META_CURSOR_SE_RESIZE, META_CURSOR_SOUTH_RESIZE, META_CURSOR_SW_RESIZE, META_CURSOR_WEST_RESIZE, and _MetaDisplay::xdisplay.
Referenced by meta_frame_set_screen_cursor(), meta_screen_set_cursor(), and meta_screen_update_cursor().
meta_display_decrement_focus_sentinel()
void meta_display_decrement_focus_sentinel (MetaDisplay * display)
Definition at line 5349 of file display.c.
References _MetaDisplay::sentinel_counter.
meta_display_devirtualize_modifiers()
void meta_display_devirtualize_modifiers (MetaDisplay * display, MetaVirtualModifier modifiers, unsigned int * mask)
Definition at line 5201 of file display.c.
References _MetaDisplay::hyper_mask, mask, _MetaDisplay::meta_mask, META_VIRTUAL_ALT_MASK, META_VIRTUAL_CONTROL_MASK, META_VIRTUAL_HYPER_MASK, META_VIRTUAL_META_MASK, META_VIRTUAL_MOD2_MASK, META_VIRTUAL_MOD3_MASK, META_VIRTUAL_MOD4_MASK, META_VIRTUAL_MOD5_MASK, META_VIRTUAL_SHIFT_MASK, META_VIRTUAL_SUPER_MASK, and _MetaDisplay::super_mask.
meta_display_end_grab_op()
void meta_display_end_grab_op (MetaDisplay * display, guint32 timestamp)
Definition at line 3840 of file display.c.
References _MetaDisplay::compositor, FALSE, _MetaDisplay::grab_have_keyboard, _MetaDisplay::grab_have_pointer, _MetaDisplay::grab_old_window_stacking, _MetaDisplay::grab_op, GRAB_OP_IS_WINDOW_SWITCH, _MetaDisplay::grab_resize_popup, _MetaDisplay::grab_resize_timeout_id, _MetaDisplay::grab_screen, _MetaDisplay::grab_threshold_movement_reached, _MetaDisplay::grab_tile_mode, _MetaDisplay::grab_tile_monitor_number, _MetaDisplay::grab_was_cancelled, _MetaDisplay::grab_window, _MetaDisplay::grab_wireframe_active, _MetaDisplay::grab_wireframe_rect, _MetaDisplay::grab_xwindow, _MetaRectangle::height, meta_compositor_end_move(), META_DEBUG_WINDOW_OPS, meta_display_cleanup_edges(), meta_grab_op_is_moving(), meta_grab_op_is_resizing(), META_GRAB_OP_KEYBOARD_WORKSPACE_MOVING, META_GRAB_OP_KEYBOARD_WORKSPACE_SWITCHING, META_GRAB_OP_NONE, meta_prefs_get_raise_on_click(), meta_resize_gravity_from_grab_op(), meta_screen_ungrab_all_keys(), META_TILE_NONE, meta_tile_preview_hide(), meta_ui_resize_popup_free(), meta_ui_tab_popup_free(), meta_window_calc_showing(), meta_window_end_wireframe(), meta_window_move(), meta_window_raise(), meta_window_resize_with_gravity(), meta_window_ungrab_all_keys(), NULL, _MetaWindow::shaken_loose, _MetaScreen::tab_popup, _MetaDisplay::tab_popup_mouse_pressed, _MetaScreen::tile_preview, TRUE, _MetaDisplay::ungrab_should_not_cause_focus_window, _MetaRectangle::width, _MetaRectangle::x, _MetaDisplay::xdisplay, and _MetaRectangle::y.
Referenced by meta_core_end_grab_op(), meta_display_process_key_event(), meta_window_client_message(), meta_window_free(), and meta_window_handle_mouse_grab_op_event().
meta_display_focus_sentinel_clear()
gboolean meta_display_focus_sentinel_clear (MetaDisplay * display)
Definition at line 5358 of file display.c.
References _MetaDisplay::sentinel_counter.
meta_display_focus_the_no_focus_window()
void meta_display_focus_the_no_focus_window (MetaDisplay * display, MetaScreen * screen, guint32 timestamp)
Definition at line 5486 of file display.c.
References _MetaDisplay::active_screen, _MetaDisplay::expected_focus_window, _MetaDisplay::last_focus_time, meta_display_remove_autoraise_callback(), NULL, and _MetaDisplay::xdisplay.
Referenced by meta_workspace_focus_default_window().
meta_display_for_x_display()
MetaDisplay * meta_display_for_x_display (Display * xdisplay)
Returns the singleton MetaDisplay if "xdisplay" matches the X display it's managing; otherwise gives a warning and returns NULL. When we were claiming to be able to manage multiple displays, this was supposed to find the display out of the list which matched that display. Now it's merely an extra sanity check.
Parameters
xdisplay An X display
Returns
The singleton X display, or NULL if "xdisplay" isn't the one we're managing.
Definition at line 1068 of file display.c.
References meta_warning(), and NULL.
Referenced by meta_core_begin_grab_op(), meta_core_end_grab_op(), meta_core_get(), meta_core_get_grab_button(), meta_core_get_grab_frame(), meta_core_get_grab_op(), meta_core_get_workspace_name_with_index(), meta_core_grab_buttons(), meta_core_increment_event_serial(), meta_core_lower_beneath_focus_window(), and meta_screen_for_x_screen().
meta_display_get_current_time()
guint32 meta_display_get_current_time (MetaDisplay * display)
Definition at line 1224 of file display.c.
References _MetaDisplay::current_time.
Referenced by meta_display_get_current_time_roundtrip(), meta_display_increment_focus_sentinel(), and meta_window_client_message().
meta_display_get_current_time_roundtrip()
guint32 meta_display_get_current_time_roundtrip (MetaDisplay * display)
Definition at line 1231 of file display.c.
References meta_display_get_current_time(), NULL, _MetaDisplay::timestamp_pinging_window, and _MetaDisplay::xdisplay.
Referenced by meta_window_client_message(), meta_window_make_fullscreen_internal(), meta_window_maximize(), and meta_window_new_with_attrs().
meta_display_get_tab_current()
MetaWindow * meta_display_get_tab_current (MetaDisplay * display, MetaTabList type, MetaScreen * screen, MetaWorkspace * workspace)
Definition at line 4858 of file display.c.
References IN_TAB_CHAIN, meta_window_located_on_workspace(), and NULL.
meta_display_get_tab_list()
GList * meta_display_get_tab_list (MetaDisplay * display, MetaTabList type, MetaScreen * screen, MetaWorkspace * workspace)
Definition at line 4709 of file display.c.
References IN_TAB_CHAIN, meta_display_list_windows(), META_TAB_LIST_NORMAL, META_TAB_LIST_NORMAL_ALL_WORKSPACES, _MetaWorkspace::mru_list, NULL, _MetaWindow::wm_state_demands_attention, and _MetaWindow::workspace.
Referenced by meta_display_get_tab_next(), and meta_screen_ensure_tab_popup().
meta_display_get_tab_next()
MetaWindow * meta_display_get_tab_next (MetaDisplay * display, MetaTabList type, MetaScreen * screen, MetaWorkspace * workspace, MetaWindow * window, gboolean backward)
Definition at line 4808 of file display.c.
References meta_display_get_tab_list(), NULL, and TRUE.
meta_display_grab()
void meta_display_grab (MetaDisplay * display)
Definition at line 1025 of file display.c.
References _MetaDisplay::server_grab_count, and _MetaDisplay::xdisplay.
Referenced by meta_effects_begin_wireframe(), meta_screen_free(), meta_screen_manage_all_windows(), meta_window_ensure_frame(), meta_window_new(), and meta_window_new_with_attrs().
meta_display_grab_focus_window_button()
void meta_display_grab_focus_window_button (MetaDisplay * display, MetaWindow * window)
Definition at line 4143 of file display.c.
References MAX_FOCUS_BUTTON, META_FOCUS_MODE_CLICK, meta_prefs_get_focus_mode(), and TRUE.
Referenced by meta_window_new_with_attrs(), and meta_window_notify_focus().
meta_display_grab_window_buttons()
void meta_display_grab_window_buttons (MetaDisplay * display, Window xwindow)
Definition at line 4065 of file display.c.
References debug, FALSE, NULL, TRUE, and _MetaDisplay::window_grab_modifiers.
Referenced by meta_core_grab_buttons(), and meta_window_new_with_attrs().
meta_display_increment_event_serial()
void meta_display_increment_event_serial (MetaDisplay * display)
Definition at line 4215 of file display.c.
References _MetaDisplay::leader_window, and _MetaDisplay::xdisplay.
Referenced by meta_core_increment_event_serial().
meta_display_increment_focus_sentinel()
void meta_display_increment_focus_sentinel (MetaDisplay * display)
Definition at line 5333 of file display.c.
References data, meta_display_get_current_time(), _MetaDisplay::screens, _MetaDisplay::sentinel_counter, and _MetaDisplay::xdisplay.
meta_display_list_windows()
GSList * meta_display_list_windows (MetaDisplay * display)
Definition at line 834 of file display.c.
References NULL, and _MetaDisplay::window_ids.
Referenced by meta_display_get_tab_list(), meta_display_queue_retheme_all_windows(), meta_display_unmanage_windows_for_screen(), meta_invalidate_all_icons(), meta_invalidate_default_icons(), meta_window_foreach_transient(), meta_window_place(), and meta_workspace_list_windows().
meta_display_lookup_x_window()
MetaWindow * meta_display_lookup_x_window (MetaDisplay * display, Window xwindow)
Definition at line 3329 of file display.c.
References _MetaDisplay::window_ids.
Referenced by meta_core_get(), meta_display_process_key_event(), meta_screen_composite_all_windows(), meta_window_foreach_ancestor(), meta_window_get_transient_for(), meta_window_new_with_attrs(), and meta_window_place().
meta_display_open()
gboolean meta_display_open (void)
Referenced by main().
meta_display_ping_window()
void meta_display_ping_window (MetaDisplay * display, MetaWindow * window, guint32 timestamp, MetaWindowPingFunc ping_reply_func, MetaWindowPingFunc ping_timeout_func, void * user_data)
References user_data.
Referenced by meta_window_delete().
meta_display_queue_autoraise_callback()
void meta_display_queue_autoraise_callback (MetaDisplay * display, MetaWindow * window)
Definition at line 1365 of file display.c.
References _MetaDisplay::autoraise_timeout_id, _MetaDisplay::autoraise_window, META_DEBUG_FOCUS, and meta_prefs_get_auto_raise_delay().
Referenced by meta_workspace_focus_default_window().
meta_display_queue_retheme_all_windows()
void meta_display_queue_retheme_all_windows (MetaDisplay * display)
Definition at line 4252 of file display.c.
References meta_display_list_windows(), meta_frame_queue_draw(), META_QUEUE_MOVE_RESIZE, meta_window_queue(), NULL, and TRUE.
Referenced by meta_display_retheme_all().
meta_display_register_x_window()
void meta_display_register_x_window (MetaDisplay * display, Window * xwindowp, MetaWindow * window)
Definition at line 3336 of file display.c.
References NULL, and _MetaDisplay::window_ids.
Referenced by meta_window_ensure_frame(), and meta_window_new_with_attrs().
meta_display_remove_autoraise_callback()
void meta_display_remove_autoraise_callback (MetaDisplay * display)
Definition at line 5505 of file display.c.
References _MetaDisplay::autoraise_timeout_id, _MetaDisplay::autoraise_window, and NULL.
Referenced by meta_display_close(), meta_display_focus_the_no_focus_window(), and meta_display_set_input_focus_window().
meta_display_retheme_all()
void meta_display_retheme_all (void)
Definition at line 4278 of file display.c.
References meta_display_queue_retheme_all_windows(), and meta_get_display().
meta_display_screen_for_x_screen()
MetaScreen * meta_display_screen_for_x_screen (MetaDisplay * display, Screen * screen)
Definition at line 1004 of file display.c.
References NULL, and _MetaDisplay::screens.
Referenced by meta_display_screen_for_xwindow(), and meta_screen_for_x_screen().
meta_display_screen_for_xwindow()
MetaScreen * meta_display_screen_for_xwindow (MetaDisplay * display, Window xindow)
Definition at line 982 of file display.c.
References meta_display_screen_for_x_screen(), meta_error_trap_pop(), meta_error_trap_push(), NULL, TRUE, and _MetaDisplay::xdisplay.
Referenced by meta_core_begin_grab_op(), meta_core_lower_beneath_focus_window(), and meta_display_process_key_event().
meta_display_set_cursor_theme()
void meta_display_set_cursor_theme (const char * theme, int size)
Definition at line 4284 of file display.c.
References meta_get_display(), meta_screen_update_cursor(), NULL, _MetaDisplay::screens, and _MetaDisplay::xdisplay.
meta_display_set_grab_op_cursor()
void meta_display_set_grab_op_cursor (MetaDisplay * display, MetaScreen * screen, MetaGrabOp op, gboolean change_pointer, Window grab_xwindow, guint32 timestamp)
Definition at line 3485 of file display.c.
References FALSE, _MetaDisplay::grab_have_pointer, GRAB_MASK, META_DEBUG_WINDOW_OPS, meta_error_trap_pop(), meta_error_trap_pop_with_return(), meta_error_trap_push(), NULL, op, TRUE, and _MetaDisplay::xdisplay.
Referenced by meta_display_begin_grab_op(), and meta_window_update_keyboard_resize().
meta_display_set_input_focus_window()
void meta_display_set_input_focus_window (MetaDisplay * display, MetaWindow * window, gboolean focus_frame, guint32 timestamp)
Definition at line 5462 of file display.c.
References _MetaDisplay::active_screen, _MetaDisplay::autoraise_window, _MetaDisplay::expected_focus_window, FALSE, _MetaDisplay::last_focus_time, meta_display_remove_autoraise_callback(), meta_error_trap_pop(), meta_error_trap_push(), and _MetaDisplay::xdisplay.
Referenced by meta_window_focus().
meta_display_stack_cmp()
int meta_display_stack_cmp (const void * a, const void * b)
Definition at line 5183 of file display.c.
References b, meta_stack_windows_cmp(), _MetaScreen::number, _MetaWindow::screen, and _MetaScreen::stack.
Referenced by meta_display_unmanage_windows_for_screen().
meta_display_ungrab()
void meta_display_ungrab (MetaDisplay * display)
Definition at line 1037 of file display.c.
References meta_bug(), _MetaDisplay::server_grab_count, and _MetaDisplay::xdisplay.
Referenced by meta_effects_end_wireframe(), meta_screen_free(), meta_screen_manage_all_windows(), meta_window_ensure_frame(), meta_window_new(), and meta_window_new_with_attrs().
meta_display_ungrab_focus_window_button()
void meta_display_ungrab_focus_window_button (MetaDisplay * display, MetaWindow * window)
Definition at line 4192 of file display.c.
References FALSE, and MAX_FOCUS_BUTTON.
Referenced by meta_window_free(), and meta_window_notify_focus().
meta_display_ungrab_window_buttons()
void meta_display_ungrab_window_buttons (MetaDisplay * display, Window xwindow)
Definition at line 4115 of file display.c.
References debug, FALSE, NULL, and _MetaDisplay::window_grab_modifiers.
Referenced by meta_window_free().
meta_display_unmanage_screen()
void meta_display_unmanage_screen (MetaDisplay * display, MetaScreen * screen, guint32 timestamp)
Definition at line 5143 of file display.c.
References meta_display_close(), meta_screen_free(), _MetaDisplay::name, NULL, and _MetaDisplay::screens.
meta_display_unmanage_windows_for_screen()
void meta_display_unmanage_windows_for_screen (MetaDisplay * display, MetaScreen * screen, guint32 timestamp)
Definition at line 5161 of file display.c.
References meta_display_list_windows(), meta_display_stack_cmp(), meta_window_free(), and NULL.
Referenced by meta_screen_free().
meta_display_unregister_x_window()
void meta_display_unregister_x_window (MetaDisplay * display, Window xwindow)
Definition at line 3346 of file display.c.
References NULL, and _MetaDisplay::window_ids.
Referenced by meta_window_destroy_frame(), and meta_window_free().
meta_display_update_active_window_hint()
void meta_display_update_active_window_hint (MetaDisplay * display)
Definition at line 4223 of file display.c.
References data, FALSE, meta_error_trap_pop(), meta_error_trap_push(), NULL, _MetaDisplay::screens, and _MetaDisplay::xdisplay.
Referenced by meta_window_notify_focus().
meta_display_xwindow_is_a_no_focus_window()
gboolean meta_display_xwindow_is_a_no_focus_window (MetaDisplay * display, Window xwindow)
Definition at line 3358 of file display.c.
References FALSE, NULL, _MetaDisplay::screens, and TRUE.
Referenced by meta_window_new_with_attrs().
meta_event_detail_to_string()
const char * meta_event_detail_to_string (int d)
Referenced by meta_window_notify_focus().
meta_event_mode_to_string()
const char * meta_event_mode_to_string (int m)
Referenced by meta_window_notify_focus().
meta_get_display()
MetaDisplay * meta_get_display (void)
Accessor for the singleton MetaDisplay.
Returns
The only MetaDisplay there is. This can be NULL, but only during startup.
Definition at line 1086 of file display.c.
Referenced by meta_display_retheme_all(), meta_display_set_cursor_theme(), meta_invalidate_all_icons(), meta_invalidate_default_icons(), and meta_set_syncing().
meta_grab_op_is_moving()
gboolean meta_grab_op_is_moving (MetaGrabOp op)
Definition at line 1209 of file display.c.
References FALSE, META_GRAB_OP_KEYBOARD_MOVING, META_GRAB_OP_MOVING, op, and TRUE.
Referenced by meta_display_begin_grab_op(), meta_display_end_grab_op(), meta_window_handle_mouse_grab_op_event(), and meta_window_unmaximize().
meta_grab_op_is_resizing()
gboolean meta_grab_op_is_resizing (MetaGrabOp op)
Definition at line 1180 of file display.c.
References FALSE, META_GRAB_OP_KEYBOARD_RESIZING_E, META_GRAB_OP_KEYBOARD_RESIZING_N, META_GRAB_OP_KEYBOARD_RESIZING_NE, META_GRAB_OP_KEYBOARD_RESIZING_NW, META_GRAB_OP_KEYBOARD_RESIZING_S, META_GRAB_OP_KEYBOARD_RESIZING_SE, META_GRAB_OP_KEYBOARD_RESIZING_SW, META_GRAB_OP_KEYBOARD_RESIZING_UNKNOWN, META_GRAB_OP_KEYBOARD_RESIZING_W, META_GRAB_OP_RESIZING_E, META_GRAB_OP_RESIZING_N, META_GRAB_OP_RESIZING_NE, META_GRAB_OP_RESIZING_NW, META_GRAB_OP_RESIZING_S, META_GRAB_OP_RESIZING_SE, META_GRAB_OP_RESIZING_SW, META_GRAB_OP_RESIZING_W, op, and TRUE.
Referenced by meta_display_begin_grab_op(), meta_display_end_grab_op(), and meta_window_handle_mouse_grab_op_event().
meta_resize_gravity_from_grab_op()
int meta_resize_gravity_from_grab_op (MetaGrabOp op)
Definition at line 4878 of file display.c.
References META_GRAB_OP_KEYBOARD_RESIZING_E, META_GRAB_OP_KEYBOARD_RESIZING_N, META_GRAB_OP_KEYBOARD_RESIZING_NE, META_GRAB_OP_KEYBOARD_RESIZING_NW, META_GRAB_OP_KEYBOARD_RESIZING_S, META_GRAB_OP_KEYBOARD_RESIZING_SE, META_GRAB_OP_KEYBOARD_RESIZING_SW, META_GRAB_OP_KEYBOARD_RESIZING_UNKNOWN, META_GRAB_OP_KEYBOARD_RESIZING_W, META_GRAB_OP_RESIZING_E, META_GRAB_OP_RESIZING_N, META_GRAB_OP_RESIZING_NE, META_GRAB_OP_RESIZING_NW, META_GRAB_OP_RESIZING_S, META_GRAB_OP_RESIZING_SE, META_GRAB_OP_RESIZING_SW, META_GRAB_OP_RESIZING_W, and op.
Referenced by meta_display_end_grab_op().