MATE Desktop Environment: djvu-document.c File Reference
djvu-document.c File Reference
#include "config.h"
#include "djvu-document.h"
#include "djvu-text-page.h"
#include "djvu-links.h"
#include "djvu-document-private.h"
#include "ev-document-thumbnails.h"
#include "ev-file-exporter.h"
#include "ev-document-misc.h"
#include "ev-document-find.h"
#include "ev-document-links.h"
#include "ev-selection.h"
#include "ev-file-helpers.h"
#include <glib.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <glib/gi18n-lib.h>
#include <string.h>
Macros
#define SCALE_FACTOR 0.2
#define EV_DJVU_ERROR ev_djvu_error_quark ()
Typedefs
typedef struct _DjvuDocumentClass DjvuDocumentClass
Enumerations
enum { PROP_0 , PROP_TITLE }
Functions
EV_BACKEND_REGISTER_WITH_CODE (DjvuDocument, djvu_document, { EV_BACKEND_IMPLEMENT_INTERFACE(EV_TYPE_DOCUMENT_THUMBNAILS, djvu_document_document_thumbnails_iface_init);EV_BACKEND_IMPLEMENT_INTERFACE(EV_TYPE_FILE_EXPORTER, djvu_document_file_exporter_iface_init);EV_BACKEND_IMPLEMENT_INTERFACE(EV_TYPE_DOCUMENT_FIND, djvu_document_find_iface_init);EV_BACKEND_IMPLEMENT_INTERFACE(EV_TYPE_DOCUMENT_LINKS, djvu_document_document_links_iface_init);EV_BACKEND_IMPLEMENT_INTERFACE(EV_TYPE_SELECTION, djvu_selection_iface_init);})
void djvu_handle_events (DjvuDocument *djvu_document, int wait, GError **error)
int djvu_document_get_n_pages (EvDocument *document)
Macro Definition Documentation
EV_DJVU_ERROR
#define EV_DJVU_ERROR ev_djvu_error_quark ()
Definition at line 69 of file djvu-document.c.
SCALE_FACTOR
#define SCALE_FACTOR 0.2
Definition at line 40 of file djvu-document.c.
Typedef Documentation
DjvuDocumentClass
typedef struct _DjvuDocumentClass DjvuDocumentClass
Definition at line 52 of file djvu-document.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_TITLE
Definition at line 42 of file djvu-document.c.
Function Documentation
djvu_document_get_n_pages()
int djvu_document_get_n_pages (EvDocument * document)
Definition at line 269 of file djvu-document.c.
References _DjvuDocument::d_document, and DJVU_DOCUMENT.
djvu_handle_events()
void djvu_handle_events (DjvuDocument * djvu_document, int wait, GError ** error)
Definition at line 113 of file djvu-document.c.
References _DjvuDocument::d_context, and error.
Referenced by djvu_links_get_links(), djvu_links_get_links_model(), and djvu_links_has_document_links().
EV_BACKEND_REGISTER_WITH_CODE()
EV_BACKEND_REGISTER_WITH_CODE (DjvuDocument , djvu_document , { EV_BACKEND_IMPLEMENT_INTERFACE(EV_TYPE_DOCUMENT_THUMBNAILS, djvu_document_document_thumbnails_iface_init);EV_BACKEND_IMPLEMENT_INTERFACE(EV_TYPE_FILE_EXPORTER, djvu_document_file_exporter_iface_init);EV_BACKEND_IMPLEMENT_INTERFACE(EV_TYPE_DOCUMENT_FIND, djvu_document_find_iface_init);EV_BACKEND_IMPLEMENT_INTERFACE(EV_TYPE_DOCUMENT_LINKS, djvu_document_document_links_iface_init);EV_BACKEND_IMPLEMENT_INTERFACE(EV_TYPE_SELECTION, djvu_selection_iface_init);})
References EV_BACKEND_IMPLEMENT_INTERFACE, EV_TYPE_DOCUMENT_FIND, EV_TYPE_DOCUMENT_LINKS, EV_TYPE_DOCUMENT_THUMBNAILS, EV_TYPE_FILE_EXPORTER, and EV_TYPE_SELECTION.