MATE Desktop Environment: djvu-document-private.h File Reference
djvu-document-private.h File Reference
#include "djvu-document.h"
#include <libdjvu/ddjvuapi.h>
Classes
struct _DjvuDocument
Functions
int djvu_document_get_n_pages (EvDocument *document)
void djvu_handle_events (DjvuDocument *djvu_document, int wait, GError **error)
Function Documentation
djvu_document_get_n_pages()
int djvu_document_get_n_pages (EvDocument * document)
Definition at line 269 of file djvu-document.c.
References _DjvuDocument::d_document, and DJVU_DOCUMENT.
djvu_handle_events()
void djvu_handle_events (DjvuDocument * djvu_document, int wait, GError ** error)
Definition at line 113 of file djvu-document.c.
References _DjvuDocument::d_context, and error.
Referenced by djvu_links_get_links(), djvu_links_get_links_model(), and djvu_links_has_document_links().