MATE Desktop Environment: dlg-package-installer.c File Reference
dlg-package-installer.c File Reference
#include <config.h>
#include <string.h>
#include <glib/gi18n.h>
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
#include "dlg-package-installer.h"
#include "gtk-utils.h"
#include "fr-init.h"
Functions
void dlg_package_installer (FrWindow *window, FrArchive *archive, FrAction action)
Function Documentation
dlg_package_installer()
void dlg_package_installer (FrWindow * window, FrArchive * archive, FrAction action)
Definition at line 264 of file dlg-package-installer.c.
References _, _gtk_message_dialog_new(), action, _FrArchive::content_type, FR_COMMAND_CAN_READ, FR_COMMAND_CAN_READ_WRITE, fr_command_get_packages(), FR_PROC_ERROR_GENERIC, get_preferred_command_for_mime_type(), and NULL.