MATE Desktop Environment: drive-button.c File Reference
drive-button.c File Reference
#include <gio/gio.h>
#include "drive-button.h"
#include <glib/gi18n.h>
#include <gdk/gdkkeysyms.h>
#include <gio/gdesktopappinfo.h>
#include <libmate-desktop/mate-image-menu-item.h>
#include <string.h>
Enumerations
enum { CMD_NONE , CMD_MOUNT_OR_PLAY , CMD_UNMOUNT , CMD_EJECT }
Functions
GtkWidget * drive_button_new (GVolume *volume)
GtkWidget * drive_button_new_from_mount (GMount *mount)
void drive_button_queue_update (DriveButton *self)
void drive_button_set_size (DriveButton *self, int icon_size)
void drive_button_redraw (gpointer key, gpointer value, gpointer user_data)
int drive_button_compare (DriveButton *button, DriveButton *other_button)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CMD_NONE
CMD_MOUNT_OR_PLAY
CMD_UNMOUNT
CMD_EJECT
Definition at line 38 of file drive-button.c.
Function Documentation
drive_button_compare()
int drive_button_compare (DriveButton * button, DriveButton * other_button)
Definition at line 452 of file drive-button.c.
References _DriveButton::mount, and _DriveButton::volume.
drive_button_new()
GtkWidget * drive_button_new (GVolume * volume)
Definition at line 111 of file drive-button.c.
References DRIVE_TYPE_BUTTON, and NULL.
drive_button_new_from_mount()
GtkWidget * drive_button_new_from_mount (GMount * mount)
Definition at line 128 of file drive-button.c.
References DRIVE_TYPE_BUTTON, and NULL.
drive_button_queue_update()
void drive_button_queue_update (DriveButton * self)
Definition at line 423 of file drive-button.c.
References _DriveButton::update_tag.
Referenced by drive_button_redraw(), and drive_button_set_size().
drive_button_redraw()
void drive_button_redraw (gpointer key, gpointer value, gpointer user_data)
Definition at line 443 of file drive-button.c.
References drive_button_queue_update(), key, and user_data.
Referenced by drive_list_redraw().
drive_button_set_size()
void drive_button_set_size (DriveButton * self, int icon_size)
Definition at line 431 of file drive-button.c.
References drive_button_queue_update(), DRIVE_IS_BUTTON, and _DriveButton::icon_size.