MATE Desktop Environment: drive-list.c File Reference
drive-list.c File Reference
#include <gio/gio.h>
#include "drive-list.h"
#include "drive-button.h"
#include <glib/gi18n.h>
Functions
G_DEFINE_TYPE (DriveList, drive_list, GTK_TYPE_GRID)
GtkWidget * drive_list_new (void)
void drive_list_set_orientation (DriveList *self, GtkOrientation orientation)
void drive_list_set_panel_size (DriveList *self, int panel_size)
void drive_list_redraw (DriveList *self)
void settings_color_changed (GSettings *settings, gchar *key, DriveList *drive_list)
void drive_list_set_transparent (DriveList *self, gboolean transparent)
Function Documentation
drive_list_new()
GtkWidget * drive_list_new (void)
Definition at line 131 of file drive-list.c.
References DRIVE_TYPE_LIST, and NULL.
drive_list_redraw()
void drive_list_redraw (DriveList * self)
Definition at line 481 of file drive-list.c.
References drive_button_redraw(), _DriveList::mounts, and _DriveList::volumes.
Referenced by settings_color_changed().
drive_list_set_orientation()
void drive_list_set_orientation (DriveList * self, GtkOrientation orientation)
Definition at line 445 of file drive-list.c.
References DRIVE_IS_LIST, and _DriveList::orientation.
drive_list_set_panel_size()
void drive_list_set_panel_size (DriveList * self, int panel_size)
Definition at line 468 of file drive-list.c.
References DRIVE_IS_LIST, _DriveList::icon_size, _DriveList::mounts, and _DriveList::volumes.
drive_list_set_transparent()
void drive_list_set_transparent (DriveList * self, gboolean transparent)
Definition at line 508 of file drive-list.c.
References _DriveList::mounts, _DriveList::relief, and _DriveList::volumes.
G_DEFINE_TYPE()
G_DEFINE_TYPE (DriveList , drive_list , GTK_TYPE_GRID)
References NULL.
settings_color_changed()
void settings_color_changed (GSettings * settings, gchar * key, DriveList * drive_list)
Definition at line 488 of file drive-list.c.
References DRIVE_IS_LIST, drive_list_redraw(), and key.