MATE Desktop Environment: dropbox-client.c File Reference
dropbox-client.c File Reference
#include <glib.h>
#include "g-util.h"
#include "dropbox-command-client.h"
#include "caja-dropbox-hooks.h"
#include "dropbox-client.h"
Functions
gboolean dropbox_client_is_connected (DropboxClient *dc)
void dropbox_client_force_reconnect (DropboxClient *dc)
void dropbox_client_setup (DropboxClient *dc)
void dropbox_client_add_on_disconnect_hook (DropboxClient *dc, DropboxClientConnectHook dhcch, gpointer ud)
void dropbox_client_add_on_connect_hook (DropboxClient *dc, DropboxClientConnectHook dhcch, gpointer ud)
void dropbox_client_add_connection_attempt_hook (DropboxClient *dc, DropboxClientConnectionAttemptHook dhcch, gpointer ud)
void dropbox_client_start (DropboxClient *dc)
Function Documentation
dropbox_client_add_connection_attempt_hook()
void dropbox_client_add_connection_attempt_hook (DropboxClient * dc, DropboxClientConnectionAttemptHook dhcch, gpointer ud)
Definition at line 159 of file dropbox-client.c.
References DropboxClient::dcc, debug, and dropbox_command_client_add_connection_attempt_hook().
dropbox_client_add_on_connect_hook()
void dropbox_client_add_on_connect_hook (DropboxClient * dc, DropboxClientConnectHook dhcch, gpointer ud)
Definition at line 145 of file dropbox-client.c.
References DropboxClient::onconnect_hooklist.
dropbox_client_add_on_disconnect_hook()
void dropbox_client_add_on_disconnect_hook (DropboxClient * dc, DropboxClientConnectHook dhcch, gpointer ud)
Definition at line 131 of file dropbox-client.c.
References DropboxClient::ondisconnect_hooklist.
dropbox_client_force_reconnect()
void dropbox_client_force_reconnect (DropboxClient * dc)
Definition at line 92 of file dropbox-client.c.
References caja_dropbox_hooks_force_reconnect(), DropboxClient::dcc, debug, dropbox_client_is_connected(), dropbox_command_client_force_reconnect(), DropboxClient::hookserv, and TRUE.
dropbox_client_is_connected()
gboolean dropbox_client_is_connected (DropboxClient * dc)
Definition at line 86 of file dropbox-client.c.
References caja_dropbox_hooks_is_connected(), DropboxClient::dcc, dropbox_command_client_is_connected(), and DropboxClient::hookserv.
Referenced by dropbox_client_force_reconnect().
dropbox_client_setup()
void dropbox_client_setup (DropboxClient * dc)
Definition at line 102 of file dropbox-client.c.
References caja_dropbox_hooks_add_on_connect_hook(), caja_dropbox_hooks_add_on_disconnect_hook(), caja_dropbox_hooks_setup(), DropboxClient::command_connect_called, DropboxClient::command_disconnect_called, DropboxClient::dcc, dropbox_command_client_add_on_connect_hook(), dropbox_command_client_add_on_disconnect_hook(), dropbox_command_client_setup(), FALSE, DropboxClient::hook_connect_called, DropboxClient::hook_disconnect_called, DropboxClient::hookserv, DropboxClient::onconnect_hooklist, and DropboxClient::ondisconnect_hooklist.
dropbox_client_start()
void dropbox_client_start (DropboxClient * dc)
Definition at line 170 of file dropbox-client.c.
References caja_dropbox_hooks_start(), DropboxClient::dcc, debug, dropbox_command_client_start(), and DropboxClient::hookserv.