MATE Desktop Environment: drw-timer.h File Reference
drw-timer.h File Reference
Typedefs
typedef struct _DrwTimer DrwTimer
Functions
DrwTimer * drw_timer_new (void)
void drw_timer_start (DrwTimer *timer)
gint drw_timer_elapsed (DrwTimer *timer)
void drw_timer_destroy (DrwTimer *timer)
Typedef Documentation
DrwTimer
typedef struct _DrwTimer DrwTimer
Definition at line 36 of file drw-timer.h.
Function Documentation
drw_timer_destroy()
void drw_timer_destroy (DrwTimer * timer)
Definition at line 46 of file drw-timer.c.
drw_timer_elapsed()
gint drw_timer_elapsed (DrwTimer * timer)
Definition at line 41 of file drw-timer.c.
drw_timer_new()
DrwTimer * drw_timer_new (void)
Definition at line 29 of file drw-timer.c.
References drw_timer_start().
Referenced by drwright_new().
drw_timer_start()
void drw_timer_start (DrwTimer * timer)
Definition at line 36 of file drw-timer.c.
Referenced by drw_timer_new().