MATE Desktop Environment: drwright.h File Reference
drwright.h File Reference
Macros
#define TYPING_BREAK_SCHEMA "org.mate.typing-break"
Typedefs
typedef struct _DrWright DrWright
Functions
DrWright * drwright_new (void)
Macro Definition Documentation
TYPING_BREAK_SCHEMA
#define TYPING_BREAK_SCHEMA "org.mate.typing-break"
Definition at line 24 of file drwright.h.
Typedef Documentation
DrWright
typedef struct _DrWright DrWright
Definition at line 26 of file drwright.h.
Function Documentation
drwright_new()
DrWright * drwright_new (void)
Definition at line 564 of file drwright.c.
References debug, drw_monitor_new(), drw_timer_new(), GETTEXT_PACKAGE, MIN, NULL, STATE_START, and TYPING_BREAK_SCHEMA.
Referenced by main().