MATE Desktop Environment: dviread.c File Reference
dviread.c File Reference
#include <config.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <math.h>
#include <errno.h>
#include <unistd.h>
#include <fcntl.h>
#include "mdvi.h"
#include "private.h"
#include "color.h"
Macros
#define DVICMDDEF(x)
#define DVI_BUFLEN 4096
#define NEEDBYTES(d, n)
#define dsget4(d)
#define duget1(d)
#define duget4(d)
#define SHOWCMD(x)
#define DBGSUM(a, b, c)
Typedefs
typedef int DviCommand __PROTO((DviContext *, int))
Functions
DVICMDDEF (set_char)
DVICMDDEF (set_rule)
DVICMDDEF (no_op)
DVICMDDEF (push)
DVICMDDEF (pop)
DVICMDDEF (move_right)
DVICMDDEF (move_down)
DVICMDDEF (move_w)
DVICMDDEF (move_x)
DVICMDDEF (move_y)
DVICMDDEF (move_z)
DVICMDDEF (sel_font)
DVICMDDEF (sel_fontn)
DVICMDDEF (special)
DVICMDDEF (def_font)
DVICMDDEF (undefined)
DVICMDDEF (unexpected)
int mdvi_find_tex_page (DviContext *dvi, int tex_page)
void mdvi_sort_pages (DviContext *dvi, DviPageSort type)
int mdvi_reload (DviContext *dvi, DviParams *np)
int mdvi_configure (DviContext *dvi, DviParamCode option,...)
DviContext * mdvi_init_context (DviParams *par, DviPageSpec *spec, const char *file)
void mdvi_destroy_context (DviContext *dvi)
void mdvi_setpage (DviContext *dvi, int pageno)
int mdvi_dopage (DviContext *dvi, int pageno)
int set_char (DviContext *dvi, int opcode)
int set_rule (DviContext *dvi, int opcode)
int no_op (DviContext *dvi, int opcode)
int push (DviContext *dvi, int opcode)
int pop (DviContext *dvi, int opcode)
int move_right (DviContext *dvi, int opcode)
int move_down (DviContext *dvi, int opcode)
int move_w (DviContext *dvi, int opcode)
int move_x (DviContext *dvi, int opcode)
int move_y (DviContext *dvi, int opcode)
int move_z (DviContext *dvi, int opcode)
int sel_font (DviContext *dvi, int opcode)
int sel_fontn (DviContext *dvi, int opcode)
int special (DviContext *dvi, int opcode)
int def_font (DviContext *dvi, int opcode)
int unexpected (DviContext *dvi, int opcode)
int undefined (DviContext *dvi, int opcode)
Macro Definition Documentation
DBGSUM
#define DBGSUM (a, b, c)
Value:
(a), (b) > 0 ? '+' : '-', \
(b) > 0 ? (b) : -(b), (c)
Definition at line 1158 of file dviread.c.
Referenced by move_down(), move_right(), move_w(), move_x(), move_y(), move_z(), and set_char().
dsget4
#define dsget4 (d)
Value:
dsgetn((d), 4)
Definition at line 310 of file dviread.c.
Referenced by set_rule().
duget1
#define duget1 (d)
Value:
dugetn((d), 1)
Definition at line 311 of file dviread.c.
Referenced by def_font(), mdvi_dopage(), and mdvi_init_context().
duget4
#define duget4 (d)
Value:
dugetn((d), 4)
Definition at line 312 of file dviread.c.
DVI_BUFLEN
#define DVI_BUFLEN 4096
Definition at line 129 of file dviread.c.
DVICMDDEF
#define DVICMDDEF (x)
Value:
static int x __PROTO((DviContext *, int))
Definition at line 35 of file dviread.c.
NEEDBYTES
#define NEEDBYTES (d, n)
Value:
((d)->buffer.pos + (n) > (d)->buffer.length)
Definition at line 194 of file dviread.c.
SHOWCMD
#define SHOWCMD (x)
Value:
if(_mdvi_debug_mask & DBG_OPCODE) do { dviprint x; } while(0)
Definition at line 330 of file dviread.c.
Referenced by def_font(), move_down(), move_right(), move_w(), move_x(), move_y(), move_z(), no_op(), pop(), push(), sel_font(), sel_fontn(), set_char(), set_rule(), and special().
Typedef Documentation
__PROTO
char *pk_lookupn __PROTO
Definition at line 33 of file dviread.c.
Function Documentation
def_font()
int def_font (DviContext * dvi, int opcode)
Definition at line 1517 of file dviread.c.
References _, _DviContext::depth, duget1, DVI_FNT_DEF1, font_find_flat(), _DviFontRef::fontid, _DviFont::fontname, _DviFont::links, NULL, _DviFontRef::ref, and SHOWCMD.
Referenced by DVICMDDEF(), and DVICMDDEF().
DVICMDDEF() [1/17]
DVICMDDEF (def_font)
References def_font().
DVICMDDEF() [2/17]
DVICMDDEF (move_down)
References move_down().
DVICMDDEF() [3/17]
DVICMDDEF (move_right)
References move_right().
DVICMDDEF() [4/17]
DVICMDDEF (move_w)
References move_w().
DVICMDDEF() [5/17]
DVICMDDEF (move_x)
References move_x().
DVICMDDEF() [6/17]
DVICMDDEF (move_y)
References move_y().
DVICMDDEF() [7/17]
DVICMDDEF (move_z)
References move_z().
DVICMDDEF() [8/17]
DVICMDDEF (no_op)
References no_op().
DVICMDDEF() [9/17]
DVICMDDEF (pop)
References pop().
DVICMDDEF() [10/17]
DVICMDDEF (push)
References push().
DVICMDDEF() [11/17]
DVICMDDEF (sel_font)
References sel_font().
DVICMDDEF() [12/17]
DVICMDDEF (sel_fontn)
References sel_fontn().
DVICMDDEF() [13/17]
DVICMDDEF (set_char)
References set_char().
DVICMDDEF() [14/17]
DVICMDDEF (set_rule)
References set_rule().
DVICMDDEF() [15/17]
DVICMDDEF (special)
References special().
DVICMDDEF() [16/17]
DVICMDDEF (undefined)
References undefined().
DVICMDDEF() [17/17]
DVICMDDEF (unexpected)
References def_font(), move_down(), move_right(), move_w(), move_x(), move_y(), move_z(), no_op(), pop(), push(), sel_font(), sel_fontn(), set_char(), set_rule(), special(), undefined(), and unexpected().
mdvi_configure()
int mdvi_configure (DviContext * dvi, DviParamCode option, ...)
Definition at line 535 of file dviread.c.
References _DviParams::bg, _DviParams::conv, _DviParams::density, _DviContext::device, _DviDevice::device_data, _DviParams::dpi, _DviContext::dviconv, _DviContext::dvivconv, _DviParams::fg, font_reset_chain_glyphs(), _DviContext::fonts, _DviParams::gamma, _DviParams::hdrift, _DviParams::hshrink, _DviParams::mag, MDVI_FONTSEL_BITMAP, MDVI_FONTSEL_GLYPH, MDVI_FONTSEL_GREY, MDVI_PARAM_LAST, mdvi_reload(), MDVI_SET_BACKGROUND, MDVI_SET_DENSITY, MDVI_SET_DPI, MDVI_SET_DRIFT, MDVI_SET_FOREGROUND, MDVI_SET_GAMMA, MDVI_SET_HDRIFT, MDVI_SET_MAGNIFICATION, MDVI_SET_ORIENTATION, MDVI_SET_SHRINK, MDVI_SET_VDRIFT, MDVI_SET_XDPI, MDVI_SET_XSHRINK, MDVI_SET_YDPI, MDVI_SET_YSHRINK, option, _DviParams::orientation, _DviContext::params, _DviDevice::refresh, _DviParams::vconv, _DviParams::vdpi, _DviParams::vdrift, and _DviParams::vshrink.
Referenced by __PROTO().
mdvi_destroy_context()
void mdvi_destroy_context (DviContext * dvi)
Definition at line 905 of file dviread.c.
References _DviContext::buffer, _DviContext::color_stack, _DviBuffer::data, _DviDevice::dev_destroy, _DviContext::device, _DviDevice::device_data, _DviContext::fileid, _DviContext::filename, font_drop_chain(), font_free_unused(), _DviContext::fontmap, _DviContext::fonts, _DviBuffer::frozen, _DviContext::in, mdvi_free(), _DviContext::pagemap, and _DviContext::stack.
Referenced by __PROTO(), and mdvi_init_context().
mdvi_dopage()
int mdvi_dopage (DviContext * dvi, int pageno)
Definition at line 995 of file dviread.c.
References _, _DviContext::buffer, _DviParams::conv, _DviContext::curr_layer, _DviContext::currfont, _DviContext::currpage, _DviBuffer::data, DBG_FILES, DEBUG, _DviParams::dpi, duget1, DVI_BOP, DVI_EOP, _DviContext::filename, FROUND, _DviBuffer::frozen, fuget1, get_mtime(), _DviParams::hdrift, _DviParams::hshrink, _DviContext::in, _DviBuffer::length, mdvi_error(), mdvi_free(), mdvi_reload(), mdvi_reset_color(), mdvi_warning(), memzero, _DviContext::modtime, _DviContext::npages, NULL, op, _DviContext::pagemap, _DviContext::params, _DviBuffer::pos, _DviContext::pos, _DviContext::stacktop, _DviParams::thinsp, _DviParams::vconv, _DviParams::vdpi, _DviParams::vdrift, _DviParams::vshrink, and _DviParams::vsmallsp.
Referenced by __PROTO(), and mdvi_cairo_device_render().
mdvi_find_tex_page()
int mdvi_find_tex_page (DviContext * dvi, int tex_page)
Definition at line 336 of file dviread.c.
References _DviContext::npages, and _DviContext::pagemap.
Referenced by __PROTO().
mdvi_init_context()
DviContext * mdvi_init_context (DviParams * par, DviPageSpec * spec, const char * file)
Definition at line 660 of file dviread.c.
References _, _DviDevice::alloc_colors, _DviParams::bg, _DviContext::buffer, _DviContext::color_size, _DviContext::color_stack, _DviContext::color_top, _DviParams::conv, _DviDevice::create_image, _DviContext::curr_bg, _DviContext::curr_fg, _DviContext::curr_layer, _DviBuffer::data, DBG_DVI, DEBUG, _DviContext::den, _DviParams::density, _DviDevice::dev_destroy, _DviContext::device, _DviDevice::device_data, _DviParams::dpi, _DviDevice::draw_glyph, _DviDevice::draw_rule, duget1, DVI_BOP, DVI_FNT_DEF4, DVI_ID, DVI_NOOP, _DviContext::dvi_page_h, _DviContext::dvi_page_w, DVI_POST, DVI_POST_POST, DVI_PRE, DVI_TRAILER, _DviContext::dviconv, _DviContext::dvimag, _DviContext::dvivconv, error, _DviParams::fg, _DviContext::fileid, _DviContext::filename, _DviParams::flags, font_find_mapped(), font_finish_definitions(), _DviContext::fontmap, _DviContext::fonts, _DviDevice::free_image, fsget4, fuget1, fuget2, fuget4, _DviParams::gamma, get_mtime(), _DviParams::hdrift, _DviParams::hshrink, _DviContext::in, _DviParams::mag, mdvi_destroy_context(), MDVI_DPI, mdvi_error(), mdvi_free(), mdvi_malloc(), mdvi_page_selected(), memcpy, memmove, memzero, _DviContext::modtime, _DviFontRef::next, _DviContext::nfonts, _DviContext::npages, NULL, _DviContext::num, op, _DviParams::orientation, _DviContext::pagemap, _DviContext::pagesel, _DviContext::params, _DviDevice::put_pixel, _DviDevice::refresh, _DviDevice::set_color, _DviContext::stack, _DviContext::stacksize, _DviParams::tfm_conv, _DviParams::vconv, _DviParams::vdpi, _DviParams::vdrift, _DviParams::vshrink, xalloc, and xnalloc.
Referenced by __PROTO(), and mdvi_reload().
mdvi_reload()
int mdvi_reload (DviContext * dvi, DviParams * np)
Definition at line 462 of file dviread.c.
References _, _DviContext::currfont, _DviContext::currpage, DBG_DVI, DEBUG, _DviContext::den, _DviContext::device, _DviDevice::device_data, _DviContext::dvi_page_h, _DviContext::dvi_page_w, _DviContext::dviconv, _DviContext::dvimag, _DviContext::dvivconv, _DviContext::fileid, _DviContext::filename, font_drop_chain(), font_free_unused(), _DviContext::fontmap, _DviContext::fonts, _DviContext::in, mdvi_free(), mdvi_init_context(), mdvi_warning(), _DviContext::modtime, _DviContext::nfonts, _DviContext::npages, NULL, _DviContext::num, _DviContext::pagemap, _DviContext::pagesel, _DviContext::params, _DviDevice::refresh, _DviContext::stack, and _DviContext::stacksize.
Referenced by __PROTO(), mdvi_configure(), and mdvi_dopage().
mdvi_setpage()
void mdvi_setpage (DviContext * dvi, int pageno)
Definition at line 934 of file dviread.c.
References _DviContext::currpage, and _DviContext::npages.
Referenced by __PROTO().
mdvi_sort_pages()
void mdvi_sort_pages (DviContext * dvi, DviPageSort type)
Definition at line 368 of file dviread.c.
References int(), MDVI_PAGE_SORT_DOWN, MDVI_PAGE_SORT_DVI_DOWN, MDVI_PAGE_SORT_DVI_UP, MDVI_PAGE_SORT_NONE, MDVI_PAGE_SORT_RANDOM, MDVI_PAGE_SORT_UP, _DviContext::npages, NULL, and _DviContext::pagemap.
Referenced by __PROTO().
move_down()
int move_down (DviContext * dvi, int opcode)
Definition at line 1379 of file dviread.c.
References DBGSUM, DVI_DOWN1, _DviContext::pos, SHOWCMD, _DviState::v, and _DviState::vv.
Referenced by DVICMDDEF(), and DVICMDDEF().
move_right()
int move_right (DviContext * dvi, int opcode)
Definition at line 1364 of file dviread.c.
References DBGSUM, DVI_RIGHT1, _DviState::h, _DviState::hh, _DviContext::pos, and SHOWCMD.
Referenced by DVICMDDEF(), and DVICMDDEF().
move_w()
int move_w (DviContext * dvi, int opcode)
Definition at line 1394 of file dviread.c.
References DBGSUM, DVI_W0, _DviState::h, _DviState::hh, _DviContext::pos, SHOWCMD, and _DviState::w.
Referenced by DVICMDDEF(), and DVICMDDEF().
move_x()
int move_x (DviContext * dvi, int opcode)
Definition at line 1409 of file dviread.c.
References DBGSUM, DVI_X0, _DviState::h, _DviState::hh, _DviContext::pos, SHOWCMD, and _DviState::x.
Referenced by DVICMDDEF(), and DVICMDDEF().
move_y()
int move_y (DviContext * dvi, int opcode)
Definition at line 1424 of file dviread.c.
References DBGSUM, DVI_Y0, _DviContext::pos, SHOWCMD, _DviState::v, _DviState::vv, and _DviState::y.
Referenced by DVICMDDEF(), and DVICMDDEF().
move_z()
int move_z (DviContext * dvi, int opcode)
Definition at line 1439 of file dviread.c.
References DBGSUM, DVI_Z0, _DviContext::pos, SHOWCMD, _DviState::v, _DviState::vv, and _DviState::z.
Referenced by DVICMDDEF(), and DVICMDDEF().
no_op()
int no_op (DviContext * dvi, int opcode)
Definition at line 1323 of file dviread.c.
References SHOWCMD.
Referenced by DVICMDDEF(), and DVICMDDEF().
pop()
int pop (DviContext * dvi, int opcode)
Definition at line 1348 of file dviread.c.
References _, _DviState::h, _DviState::hh, memcpy, _DviContext::pos, SHOWCMD, _DviContext::stack, _DviContext::stacktop, _DviState::v, _DviState::vv, _DviState::w, _DviState::x, _DviState::y, and _DviState::z.
Referenced by DVICMDDEF(), and DVICMDDEF().
push()
int push (DviContext * dvi, int opcode)
Definition at line 1329 of file dviread.c.
References _, _DviContext::depth, _DviState::h, _DviState::hh, memcpy, _DviContext::pos, SHOWCMD, _DviContext::stack, _DviContext::stacksize, _DviContext::stacktop, _DviState::v, _DviState::vv, _DviState::w, _DviState::x, xresize, _DviState::y, and _DviState::z.
Referenced by DVICMDDEF(), and DVICMDDEF().
sel_font()
int sel_font (DviContext * dvi, int opcode)
Definition at line 1454 of file dviread.c.
References _, _DviContext::currfont, _DviContext::depth, DVI_FNT_NUM0, font_find_flat(), _DviFont::fontname, NULL, _DviFontRef::ref, and SHOWCMD.
Referenced by DVICMDDEF(), and DVICMDDEF().
sel_fontn()
int sel_fontn (DviContext * dvi, int opcode)
Definition at line 1476 of file dviread.c.
References _, _DviContext::currfont, _DviContext::depth, DVI_FNT1, font_find_flat(), _DviFont::fontname, NULL, _DviFontRef::ref, and SHOWCMD.
Referenced by DVICMDDEF(), and DVICMDDEF().
set_char()
int set_char (DviContext * dvi, int opcode)
Definition at line 1237 of file dviread.c.
References _, _DviContext::curr_layer, _DviContext::currfont, DBGSUM, _DviContext::device, _DviDevice::draw_glyph, DVI_PUT1, DVI_PUT4, DVI_SET1, font_get_glyph(), FONTCHAR, _DviFont::fontname, glyph_present, _DviState::h, _DviFontChar::height, _DviState::hh, ISVIRTUAL, _DviParams::layer, _DviFontChar::missing, NULL, _DviFontChar::offset, _DviContext::params, pixel_round, _DviContext::pos, _DviFont::private, _DviFontRef::ref, SHOWCMD, _DviFontChar::tfmwidth, _DviState::vv, and _DviFontChar::width.
Referenced by DVICMDDEF(), and DVICMDDEF().
set_rule()
int set_rule (DviContext * dvi, int opcode)
Definition at line 1292 of file dviread.c.
References b, _DviContext::curr_layer, dsget4, DVI_SET_RULE, _DviState::h, _DviState::hh, _DviParams::layer, _DviContext::params, _DviContext::pos, rule_round, SHOWCMD, vrule_round, and _DviState::vv.
Referenced by DVICMDDEF(), and DVICMDDEF().
special()
int special (DviContext * dvi, int opcode)
Definition at line 1497 of file dviread.c.
References _, DVI_XXX1, mdvi_do_special(), mdvi_free(), mdvi_malloc(), and SHOWCMD.
Referenced by DVICMDDEF(), DVICMDDEF(), and epsf_special().
undefined()
int undefined (DviContext * dvi, int opcode)
Definition at line 1547 of file dviread.c.
References _.
Referenced by DVICMDDEF(), and DVICMDDEF().
unexpected()
int unexpected (DviContext * dvi, int opcode)
Definition at line 1541 of file dviread.c.
References _.
Referenced by DVICMDDEF().