MATE Desktop Environment: eel-background.h File Reference
eel-background.h File Reference
#include <gdk/gdk.h>
#include <gtk/gtk.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <libmate-desktop/mate-bg.h>
Classes
struct EelBackground
struct EelBackgroundClass
Macros
#define MATE_DESKTOP_USE_UNSTABLE_API
#define EEL_TYPE_BACKGROUND eel_background_get_type()
#define EEL_BACKGROUND(obj)
#define EEL_BACKGROUND_CLASS(klass)
#define EEL_IS_BACKGROUND(obj)
#define EEL_IS_BACKGROUND_CLASS(klass)
#define EEL_BACKGROUND_GET_CLASS(obj)
Typedefs
typedef struct EelBackground EelBackground
typedef struct EelBackgroundClass EelBackgroundClass
typedef struct EelBackgroundPrivate EelBackgroundPrivate
Functions
GType eel_background_get_type (void)
EelBackground * eel_background_new (void)
void eel_background_set_use_base (EelBackground *self, gboolean use_base)
void eel_background_set_color (EelBackground *self, const gchar *color_or_gradient)
void eel_background_set_image_uri (EelBackground *self, const gchar *image_uri)
void eel_background_reset (EelBackground *self)
void eel_bg_set_placement (EelBackground *self, MateBGPlacement placement)
gboolean eel_background_is_desktop (EelBackground *self)
void eel_background_set_desktop (EelBackground *self, gboolean is_desktop)
gchar * eel_bg_get_desktop_color (EelBackground *self)
gchar * eel_background_get_color (EelBackground *self)
gchar * eel_background_get_image_uri (EelBackground *self)
gboolean eel_background_is_dark (EelBackground *self)
gboolean eel_background_is_set (EelBackground *self)
void eel_background_draw (GtkWidget *widget, cairo_t *cr)
void eel_background_set_dropped_color (EelBackground *self, GtkWidget *widget, GdkDragAction action, int drop_location_x, int drop_location_y, const GtkSelectionData *dropped_color)
void eel_background_set_dropped_image (EelBackground *self, GdkDragAction action, const gchar *image_uri)
EelBackground * eel_get_widget_background (GtkWidget *widget)
void eel_bg_save_to_gsettings (EelBackground *self, GSettings *settings)
void eel_bg_load_from_gsettings (EelBackground *self, GSettings *settings)
void eel_bg_load_from_system_gsettings (EelBackground *self, GSettings *settings, gboolean apply)
void eel_background_set_active (EelBackground *self, gboolean is_active)
Macro Definition Documentation
EEL_BACKGROUND
#define EEL_BACKGROUND (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), EEL_TYPE_BACKGROUND, EelBackground))
Definition at line 58 of file eel-background.h.
Referenced by eel_background_new(), and eel_get_widget_background().
EEL_BACKGROUND_CLASS
#define EEL_BACKGROUND_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), EEL_TYPE_BACKGROUND, EelBackgroundClass))
Definition at line 60 of file eel-background.h.
EEL_BACKGROUND_GET_CLASS
#define EEL_BACKGROUND_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), EEL_TYPE_BACKGROUND, EelBackgroundClass))
Definition at line 66 of file eel-background.h.
EEL_IS_BACKGROUND
#define EEL_IS_BACKGROUND (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), EEL_TYPE_BACKGROUND))
Definition at line 62 of file eel-background.h.
Referenced by eel_background_get_color(), eel_background_get_image_uri(), eel_background_is_set(), eel_background_reset(), eel_background_set_dropped_color(), and eel_get_widget_background().
EEL_IS_BACKGROUND_CLASS
#define EEL_IS_BACKGROUND_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), EEL_TYPE_BACKGROUND))
Definition at line 64 of file eel-background.h.
EEL_TYPE_BACKGROUND
#define EEL_TYPE_BACKGROUND eel_background_get_type()
Definition at line 57 of file eel-background.h.
Referenced by eel_background_new().
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 51 of file eel-background.h.
Typedef Documentation
EelBackground
typedef struct EelBackground EelBackground
Definition at line 54 of file eel-background.h.
EelBackgroundClass
typedef struct EelBackgroundClass EelBackgroundClass
Definition at line 55 of file eel-background.h.
EelBackgroundPrivate
typedef struct EelBackgroundPrivate EelBackgroundPrivate
Definition at line 129 of file eel-background.h.
Function Documentation
eel_background_draw()
void eel_background_draw (GtkWidget * widget, cairo_t * cr)
Definition at line 386 of file eel-background.c.
References EelBackground::details, eel_get_widget_background(), mate_bg_crossfade_is_started(), and NULL.
eel_background_get_color()
gchar * eel_background_get_color (EelBackground * self)
Definition at line 277 of file eel-background.c.
References EelBackground::details, EEL_IS_BACKGROUND, and NULL.
eel_background_get_image_uri()
gchar * eel_background_get_image_uri (EelBackground * self)
Definition at line 933 of file eel-background.c.
References EelBackground::details, EEL_IS_BACKGROUND, mate_bg_get_filename(), and NULL.
eel_background_get_type()
GType eel_background_get_type (void)
References action.
eel_background_is_dark()
gboolean eel_background_is_dark (EelBackground * self)
Definition at line 920 of file eel-background.c.
References EelBackground::details, and mate_bg_is_dark().
Referenced by caja_sidebar_title_select_text_color().
eel_background_is_desktop()
gboolean eel_background_is_desktop (EelBackground * self)
Definition at line 900 of file eel-background.c.
References EelBackground::details.
eel_background_is_set()
gboolean eel_background_is_set (EelBackground * self)
eel_background_is_set:
Check whether the background's color or image has been set.
Definition at line 850 of file eel-background.c.
References EelBackground::details, EEL_IS_BACKGROUND, mate_bg_get_filename(), and NULL.
Referenced by caja_sidebar_title_select_text_color().
eel_background_new()
EelBackground * eel_background_new (void)
Definition at line 1160 of file eel-background.c.
References EEL_BACKGROUND, EEL_TYPE_BACKGROUND, and NULL.
Referenced by eel_get_widget_background(), and eel_self_check_background().
eel_background_reset()
void eel_background_reset (EelBackground * self)
eel_background_reset:
Emit the reset signal to forget any color or image that has been set previously.
Definition at line 865 of file eel-background.c.
References EEL_IS_BACKGROUND, and RESET.
eel_background_set_active()
void eel_background_set_active (EelBackground * self, gboolean is_active)
Definition at line 906 of file eel-background.c.
References EelBackground::details.
eel_background_set_color()
void eel_background_set_color (EelBackground * self, const gchar * color_or_gradient)
Definition at line 286 of file eel-background.c.
References EelBackground::details.
Referenced by eel_self_check_background(), main(), and test_gtk_widget_set_background_color().
eel_background_set_desktop()
void eel_background_set_desktop (EelBackground * self, gboolean is_desktop)
Definition at line 873 of file eel-background.c.
References EelBackground::details.
Referenced by caja_connect_desktop_background_to_settings().
eel_background_set_dropped_color()
void eel_background_set_dropped_color (EelBackground * self, GtkWidget * widget, GdkDragAction action, int drop_location_x, int drop_location_y, const GtkSelectionData * dropped_color)
Definition at line 1067 of file eel-background.c.
References action, EelBackground::details, eel_gradient_set_bottom_color_spec(), eel_gradient_set_left_color_spec(), eel_gradient_set_right_color_spec(), eel_gradient_set_top_color_spec(), EEL_IS_BACKGROUND, and NULL.
eel_background_set_dropped_image()
void eel_background_set_dropped_image (EelBackground * self, GdkDragAction action, const gchar * image_uri)
Definition at line 1055 of file eel-background.c.
References action, EelBackground::details, MATE_BG_PLACEMENT_TILED, mate_bg_set_placement(), and NULL.
eel_background_set_image_uri()
void eel_background_set_image_uri (EelBackground * self, const gchar * image_uri)
Definition at line 971 of file eel-background.c.
References TRUE.
Referenced by main(), and test_gtk_widget_set_background_image().
eel_background_set_use_base()
void eel_background_set_use_base (EelBackground * self, gboolean use_base)
Definition at line 300 of file eel-background.c.
References EelBackground::details.
eel_bg_get_desktop_color()
gchar * eel_bg_get_desktop_color (EelBackground * self)
Definition at line 191 of file eel-background.c.
References EelBackground::details, eel_gdk_rgb_to_color_spec(), eel_gdk_rgba_to_rgb(), eel_gradient_new(), FALSE, MATE_BG_COLOR_H_GRADIENT, MATE_BG_COLOR_V_GRADIENT, mate_bg_get_color(), and TRUE.
eel_bg_load_from_gsettings()
void eel_bg_load_from_gsettings (EelBackground * self, GSettings * settings)
Definition at line 1020 of file eel-background.c.
References EelBackground::details, MATE_BG_KEY_PICTURE_FILENAME, and mate_bg_load_from_gsettings().
Referenced by caja_connect_desktop_background_to_settings().
eel_bg_load_from_system_gsettings()
void eel_bg_load_from_system_gsettings (EelBackground * self, GSettings * settings, gboolean apply)
Definition at line 1043 of file eel-background.c.
References EelBackground::details, and mate_bg_load_from_system_gsettings().
eel_bg_save_to_gsettings()
void eel_bg_save_to_gsettings (EelBackground * self, GSettings * settings)
Definition at line 1011 of file eel-background.c.
References EelBackground::details, and mate_bg_save_to_gsettings().
eel_bg_set_placement()
void eel_bg_set_placement (EelBackground * self, MateBGPlacement placement)
Definition at line 1002 of file eel-background.c.
References EelBackground::details, and mate_bg_set_placement().
eel_get_widget_background()
EelBackground * eel_get_widget_background (GtkWidget * widget)
Definition at line 745 of file eel-background.c.
References data, EelBackground::details, EEL_BACKGROUND, eel_background_new(), EEL_IS_BACKGROUND, and NULL.
Referenced by caja_connect_background_to_file_metadata(), caja_connect_desktop_background_to_settings(), eel_background_draw(), fm_directory_view_get_background(), main(), test_gtk_widget_set_background_color(), and test_gtk_widget_set_background_image().