MATE Desktop Environment: eel-image-table.c File Reference
eel-image-table.c File Reference
#include <config.h>
#include "eel-image-table.h"
#include "eel-art-extensions.h"
#include "eel-art-gtk-extensions.h"
#include "eel-gtk-extensions.h"
#include "eel-labeled-image.h"
#include "eel-marshal.h"
#include <gtk/gtk.h>
Enumerations
enum { ARG_0 , ARG_CHILD_UNDER_POINTER }
enum ImageTableSignals {
CHILD_ENTER , CHILD_LEAVE , CHILD_PRESSED , CHILD_RELEASED ,
CHILD_CLICKED , LAST_SIGNAL
}
Functions
GtkWidget * find_windowed_ancestor (GtkWidget *widget)
: Name of signal to connect to.
signal_connect_while_realized:
@object: Object to connect to.
@callback: Caller's callback. @callback_data: Caller's callback_data. @realized_widget: Widget to monitor for realized state. Signal is connected while this wigget is realized.
Connect to a signal of an object while another widget is realized. This is useful for non windowed widgets that need to monitor events in their ancestored windowed widget. The signal is automatically disconnected when &widget is unrealized. Also, the signal is automatically disconnected when either &object or &widget are destroyed.
GtkWidget * eel_image_table_new (gboolean homogeneous)
GtkWidget * eel_image_table_add_empty_image (EelImageTable *image_table)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ARG_0
ARG_CHILD_UNDER_POINTER
Definition at line 36 of file eel-image-table.c.
ImageTableSignals
enum ImageTableSignals
Enumerator
CHILD_ENTER
CHILD_LEAVE
CHILD_PRESSED
CHILD_RELEASED
CHILD_CLICKED
LAST_SIGNAL
Definition at line 50 of file eel-image-table.c.
Function Documentation
eel_image_table_add_empty_image()
GtkWidget * eel_image_table_add_empty_image (EelImageTable * image_table)
eel_image_table_add_empty_child: @image_table: A EelImageTable.
Add a "empty" child to the table. Useful when you want to have empty space between 2 children.
Returns: The empty child - A EelLabeledImage widget with no label or pixbuf.
Definition at line 646 of file eel-image-table.c.
References EEL_IS_IMAGE_TABLE, eel_labeled_image_new(), FALSE, and NULL.
eel_image_table_new()
GtkWidget * eel_image_table_new (gboolean homogeneous)
eel_image_table_new:
Definition at line 624 of file eel-image-table.c.
References EEL_IMAGE_TABLE, eel_image_table_get_type(), EEL_WRAP_TABLE, eel_wrap_table_set_homogeneous(), and NULL.
find_windowed_ancestor()
GtkWidget * find_windowed_ancestor (GtkWidget * widget)
Definition at line 360 of file eel-image-table.c.
References NULL.