MATE Desktop Environment: eel-editable-label.c File Reference
eel-editable-label.c File Reference
#include <config.h>
#include <math.h>
#include <string.h>
#include "eel-editable-label.h"
#include "eel-marshal.h"
#include "eel-accessibility.h"
#include "eel-gtk-extensions.h"
#include <libgail-util/gailmisc.h>
#include <glib/gi18n-lib.h>
#include <pango/pango.h>
#include <gtk/gtk.h>
#include <gtk/gtk-a11y.h>
#include <gdk/gdkx.h>
#include <gdk/gdkkeysyms.h>
Macros
#define PANGO_CHECK_VERSION(major, minor, micro)
Typedefs
typedef struct _LabelWrapWidth LabelWrapWidth
typedef struct _EelEditableLabelAccessible EelEditableLabelAccessible
typedef struct _EelEditableLabelAccessibleClass EelEditableLabelAccessibleClass
Enumerations
enum {
MOVE_CURSOR , POPULATE_POPUP , DELETE_FROM_CURSOR , CUT_CLIPBOARD ,
COPY_CLIPBOARD , PASTE_CLIPBOARD , TOGGLE_OVERWRITE , LAST_SIGNAL
}
enum {
PROP_0 , PROP_TEXT , PROP_JUSTIFY , PROP_WRAP ,
PROP_CURSOR_POSITION , PROP_SELECTION_BOUND
}
Functions
G_DEFINE_TYPE_WITH_CODE (EelEditableLabel, eel_editable_label, GTK_TYPE_WIDGET, G_IMPLEMENT_INTERFACE(GTK_TYPE_EDITABLE, eel_editable_label_editable_init))
GtkWidget * eel_editable_label_new (const gchar *str)
void eel_editable_label_set_text (EelEditableLabel *label, const gchar *str)
const gchar * eel_editable_label_get_text (EelEditableLabel *label)
void eel_editable_label_set_justify (EelEditableLabel *label, GtkJustification jtype)
GtkJustification eel_editable_label_get_justify (EelEditableLabel *label)
void eel_editable_label_set_draw_outline (EelEditableLabel *label, gboolean draw_outline)
void eel_editable_label_set_line_wrap (EelEditableLabel *label, gboolean wrap)
void eel_editable_label_set_line_wrap_mode (EelEditableLabel *label, PangoWrapMode mode)
gboolean eel_editable_label_get_line_wrap (EelEditableLabel *label)
void eel_editable_label_set_font_description (EelEditableLabel *label, const PangoFontDescription *desc)
void eel_editable_label_select_region (EelEditableLabel *label, gint start_offset, gint end_offset)
gboolean eel_editable_label_get_selection_bounds (EelEditableLabel *label, gint *start, gint *end)
PangoLayout * eel_editable_label_get_layout (EelEditableLabel *label)
void eel_editable_label_get_layout_offsets (EelEditableLabel *label, gint *x, gint *y)
G_DEFINE_TYPE_WITH_CODE (EelEditableLabelAccessible, eel_editable_label_accessible, GTK_TYPE_WIDGET_ACCESSIBLE, G_IMPLEMENT_INTERFACE(ATK_TYPE_EDITABLE_TEXT, atk_editable_text_interface_init) G_IMPLEMENT_INTERFACE(ATK_TYPE_TEXT, atk_text_interface_init))
Macro Definition Documentation
PANGO_CHECK_VERSION
#define PANGO_CHECK_VERSION (major, minor, micro)
Value:
(PANGO_VERSION_MAJOR > (major) ||                                    \
(PANGO_VERSION_MAJOR == (major) && PANGO_VERSION_MINOR > (minor)) || \
(PANGO_VERSION_MAJOR == (major) && PANGO_VERSION_MINOR == (minor) && \
 PANGO_VERSION_MICRO >= (micro)))
Definition at line 45 of file eel-editable-label.c.
Typedef Documentation
EelEditableLabelAccessible
typedef struct _EelEditableLabelAccessible EelEditableLabelAccessible
Definition at line 3330 of file eel-editable-label.c.
EelEditableLabelAccessibleClass
typedef struct _EelEditableLabelAccessibleClass EelEditableLabelAccessibleClass
Definition at line 3331 of file eel-editable-label.c.
LabelWrapWidth
typedef struct _LabelWrapWidth LabelWrapWidth
Definition at line 878 of file eel-editable-label.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MOVE_CURSOR
POPULATE_POPUP
DELETE_FROM_CURSOR
CUT_CLIPBOARD
COPY_CLIPBOARD
PASTE_CLIPBOARD
TOGGLE_OVERWRITE
LAST_SIGNAL
Definition at line 52 of file eel-editable-label.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_TEXT
PROP_JUSTIFY
PROP_WRAP
PROP_CURSOR_POSITION
PROP_SELECTION_BOUND
Definition at line 64 of file eel-editable-label.c.
Function Documentation
eel_editable_label_get_justify()
GtkJustification eel_editable_label_get_justify (EelEditableLabel * label)
eel_editable_label_get_justify: @label: a EelEditableLabel
Returns the justification of the label. See eel_editable_label_set_justify ().
Return value: #GtkJustification
Definition at line 751 of file eel-editable-label.c.
References EEL_IS_EDITABLE_LABEL, and label.
eel_editable_label_get_layout()
PangoLayout * eel_editable_label_get_layout (EelEditableLabel * label)
eel_editable_label_get_layout: @label: a EelEditableLabel
Gets the #PangoLayout used to display the label. The layout is useful to e.g. convert text positions to pixel positions, in combination with eel_editable_label_get_layout_offsets(). The returned layout is owned by the label so need not be freed by the caller.
Return value: the #PangoLayout for this label
Definition at line 2105 of file eel-editable-label.c.
References EEL_IS_EDITABLE_LABEL, label, NULL, and TRUE.
eel_editable_label_get_layout_offsets()
void eel_editable_label_get_layout_offsets (EelEditableLabel * label, gint * x, gint * y)
eel_editable_label_get_layout_offsets: @label: a EelEditableLabel @x: location to store X offset of layout, or NULL @y: location to store Y offset of layout, or NULL
Obtains the coordinates where the label will draw the #PangoLayout representing the text in the label; useful to convert mouse events into coordinates inside the #PangoLayout, e.g. to take some action if some part of the label is clicked. Of course you will need to create a #GtkEventBox to receive the events, and pack the label inside it, since labels are a #GTK_NO_WINDOW widget. Remember when using the #PangoLayout functions you need to convert to and from pixels using PANGO_PIXELS() or #PANGO_SCALE.
Definition at line 2131 of file eel-editable-label.c.
References EEL_IS_EDITABLE_LABEL, and label.
eel_editable_label_get_line_wrap()
gboolean eel_editable_label_get_line_wrap (EelEditableLabel * label)
eel_editable_label_get_line_wrap: @label: a EelEditableLabel
Returns whether lines in the label are automatically wrapped. See eel_editable_label_set_line_wrap ().
Return value: TRUE if the lines of the label are automatically wrapped.
Definition at line 823 of file eel-editable-label.c.
References EEL_IS_EDITABLE_LABEL, FALSE, and label.
eel_editable_label_get_selection_bounds()
gboolean eel_editable_label_get_selection_bounds (EelEditableLabel * label, gint * start, gint * end)
eel_editable_label_get_selection_bounds: @label: a EelEditableLabel @start: return location for start of selection, as a character offset @end: return location for end of selection, as a character offset
Gets the selected range of characters in the label, returning TRUE if there's a selection.
Return value: TRUE if selection is non-empty
Definition at line 2050 of file eel-editable-label.c.
References EEL_IS_EDITABLE_LABEL, FALSE, label, MAX, and MIN.
eel_editable_label_get_text()
const gchar * eel_editable_label_get_text (EelEditableLabel * label)
eel_editable_label_get_text: @label: a EelEditableLabel
Fetches the text from a label widget, as displayed on the screen. This does not include any embedded underlines indicating mnemonics or Pango markup. (See eel_editable_label_get_label())
Return value: the text in the label widget. This is the internal string used by the label, and must not be modified.
Definition at line 704 of file eel-editable-label.c.
References EEL_IS_EDITABLE_LABEL, label, and NULL.
eel_editable_label_new()
GtkWidget * eel_editable_label_new (const gchar * str)
eel_editable_label_new: @str: The text of the label
Creates a new label with the given text inside it. You can pass NULL to get an empty label widget.
Return value: the new EelEditableLabel
Definition at line 652 of file eel-editable-label.c.
References eel_editable_label_set_text(), EEL_TYPE_EDITABLE_LABEL, label, and NULL.
Referenced by caja_icon_container_start_renaming_selected_item(), and main().
eel_editable_label_select_region()
void eel_editable_label_select_region (EelEditableLabel * label, gint start_offset, gint end_offset)
eel_editable_label_select_region: @label: a EelEditableLabel @start_offset: start offset (in characters not bytes) @end_offset: end offset (in characters not bytes)
Selects a range of characters in the label, if the label is selectable. See eel_editable_label_set_selectable(). If the label is not selectable, this function has no effect. If @start_offset or @end_offset are -1, then the end of the label will be substituted.
Definition at line 2018 of file eel-editable-label.c.
References EEL_IS_EDITABLE_LABEL, and label.
Referenced by caja_icon_container_start_renaming_selected_item().
eel_editable_label_set_draw_outline()
void eel_editable_label_set_draw_outline (EelEditableLabel * label, gboolean draw_outline)
Definition at line 759 of file eel-editable-label.c.
References FALSE, and label.
Referenced by caja_icon_container_start_renaming_selected_item().
eel_editable_label_set_font_description()
void eel_editable_label_set_font_description (EelEditableLabel * label, const PangoFontDescription * desc)
Definition at line 831 of file eel-editable-label.c.
References label, and NULL.
Referenced by caja_icon_container_start_renaming_selected_item().
eel_editable_label_set_justify()
void eel_editable_label_set_justify (EelEditableLabel * label, GtkJustification jtype)
eel_editable_label_set_justify: @label: a EelEditableLabel @jtype: a #GtkJustification
Sets the alignment of the lines in the text of the label relative to each other. GTK_JUSTIFY_LEFT is the default value when the widget is first created with eel_editable_label_new(). If you instead want to set the alignment of the label as a whole, use gtk_misc_set_alignment() instead. eel_editable_label_set_justify() has no effect on labels containing only a single line.
Definition at line 724 of file eel-editable-label.c.
References EEL_IS_EDITABLE_LABEL, and label.
Referenced by caja_icon_container_start_renaming_selected_item().
eel_editable_label_set_line_wrap()
void eel_editable_label_set_line_wrap (EelEditableLabel * label, gboolean wrap)
eel_editable_label_set_line_wrap: @label: a EelEditableLabel @wrap: the setting
Toggles line wrapping within the EelEditableLabel widget. TRUE makes it break lines if text exceeds the widget's size. FALSE lets the text get cut off by the edge of the widget if it exceeds the widget size.
Definition at line 783 of file eel-editable-label.c.
References EEL_IS_EDITABLE_LABEL, FALSE, and label.
Referenced by caja_icon_container_start_renaming_selected_item(), and main().
eel_editable_label_set_line_wrap_mode()
void eel_editable_label_set_line_wrap_mode (EelEditableLabel * label, PangoWrapMode mode)
Definition at line 800 of file eel-editable-label.c.
References EEL_IS_EDITABLE_LABEL, and label.
Referenced by caja_icon_container_start_renaming_selected_item().
eel_editable_label_set_text()
void eel_editable_label_set_text (EelEditableLabel * label, const gchar * str)
eel_editable_label_set_text: @label: a EelEditableLabel @str: The text you want to set.
Sets the text within the EelEditableLabel widget. It overwrites any text that was there before.
This will also clear any previously set mnemonic accelerators.
Definition at line 675 of file eel-editable-label.c.
References EEL_IS_EDITABLE_LABEL, label, and NULL.
Referenced by caja_icon_container_start_renaming_selected_item(), and eel_editable_label_new().
G_DEFINE_TYPE_WITH_CODE() [1/2]
G_DEFINE_TYPE_WITH_CODE (EelEditableLabel , eel_editable_label , GTK_TYPE_WIDGET , G_IMPLEMENT_INTERFACE(GTK_TYPE_EDITABLE, eel_editable_label_editable_init))
References FALSE, keyval, and TRUE.
G_DEFINE_TYPE_WITH_CODE() [2/2]
G_DEFINE_TYPE_WITH_CODE (EelEditableLabelAccessible , eel_editable_label_accessible , GTK_TYPE_WIDGET_ACCESSIBLE , G_IMPLEMENT_INTERFACE(ATK_TYPE_EDITABLE_TEXT, atk_editable_text_interface_init) G_IMPLEMENT_INTERFACE(ATK_TYPE_TEXT, atk_text_interface_init))