MATE Desktop Environment: eel-wrap-table.h File Reference
eel-wrap-table.h File Reference
#include <glib.h>
#include <gtk/gtk.h>
Classes
struct EelWrapTable
struct EelWrapTableClass
Macros
#define EEL_TYPE_WRAP_TABLE eel_wrap_table_get_type()
#define EEL_WRAP_TABLE(obj)
#define EEL_WRAP_TABLE_CLASS(klass)
#define EEL_IS_WRAP_TABLE(obj)
#define EEL_IS_WRAP_TABLE_CLASS(klass)
#define EEL_WRAP_TABLE_GET_CLASS(obj)
Typedefs
typedef struct EelWrapTable EelWrapTable
typedef struct EelWrapTableClass EelWrapTableClass
typedef struct EelWrapTablePrivate EelWrapTablePrivate
Enumerations
enum EelJustification { EEL_JUSTIFICATION_BEGINNING , EEL_JUSTIFICATION_MIDDLE , EEL_JUSTIFICATION_END }
Functions
GType eel_wrap_table_get_type (void)
GtkWidget * eel_wrap_table_new (gboolean homogeneous)
void eel_wrap_table_set_x_spacing (EelWrapTable *wrap_table, guint x_spacing)
guint eel_wrap_table_get_x_spacing (const EelWrapTable *wrap_table)
void eel_wrap_table_set_y_spacing (EelWrapTable *wrap_table, guint y_spacing)
guint eel_wrap_table_get_y_spacing (const EelWrapTable *wrap_table)
GtkWidget * eel_wrap_table_find_child_at_event_point (const EelWrapTable *wrap_table, int x, int y)
void eel_wrap_table_set_x_justification (EelWrapTable *wrap_table, EelJustification justification)
EelJustification eel_wrap_table_get_x_justification (const EelWrapTable *wrap_table)
void eel_wrap_table_set_y_justification (EelWrapTable *wrap_table, EelJustification justification)
EelJustification eel_wrap_table_get_y_justification (const EelWrapTable *wrap_table)
void eel_wrap_table_set_homogeneous (EelWrapTable *wrap_table, gboolean homogeneous)
gboolean eel_wrap_table_get_homogeneous (const EelWrapTable *wrap_table)
void eel_wrap_table_reorder_child (EelWrapTable *wrap_table, GtkWidget *child, int position)
guint eel_wrap_table_get_num_children (const EelWrapTable *wrap_table)
GtkWidget * eel_scrolled_wrap_table_new (gboolean homogeneous, GtkShadowType shadow_type, GtkWidget **wrap_table_out)
Macro Definition Documentation
EEL_IS_WRAP_TABLE
#define EEL_IS_WRAP_TABLE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), EEL_TYPE_WRAP_TABLE))
Definition at line 40 of file eel-wrap-table.h.
Referenced by eel_wrap_table_find_child_at_event_point(), eel_wrap_table_get_homogeneous(), eel_wrap_table_get_num_children(), eel_wrap_table_get_x_justification(), eel_wrap_table_get_x_spacing(), eel_wrap_table_get_y_justification(), eel_wrap_table_get_y_spacing(), eel_wrap_table_reorder_child(), eel_wrap_table_set_homogeneous(), eel_wrap_table_set_x_justification(), eel_wrap_table_set_x_spacing(), eel_wrap_table_set_y_justification(), and eel_wrap_table_set_y_spacing().
EEL_IS_WRAP_TABLE_CLASS
#define EEL_IS_WRAP_TABLE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), EEL_TYPE_WRAP_TABLE))
Definition at line 42 of file eel-wrap-table.h.
EEL_TYPE_WRAP_TABLE
#define EEL_TYPE_WRAP_TABLE eel_wrap_table_get_type()
Definition at line 35 of file eel-wrap-table.h.
EEL_WRAP_TABLE
#define EEL_WRAP_TABLE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), EEL_TYPE_WRAP_TABLE, EelWrapTable))
Definition at line 36 of file eel-wrap-table.h.
Referenced by eel_image_table_new(), eel_scrolled_wrap_table_new(), and eel_wrap_table_new().
EEL_WRAP_TABLE_CLASS
#define EEL_WRAP_TABLE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), EEL_TYPE_WRAP_TABLE, EelWrapTableClass))
Definition at line 38 of file eel-wrap-table.h.
EEL_WRAP_TABLE_GET_CLASS
#define EEL_WRAP_TABLE_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), EEL_TYPE_WRAP_TABLE, EelWrapTableClass))
Definition at line 44 of file eel-wrap-table.h.
Typedef Documentation
EelWrapTable
typedef struct EelWrapTable EelWrapTable
Definition at line 47 of file eel-wrap-table.h.
EelWrapTableClass
typedef struct EelWrapTableClass EelWrapTableClass
Definition at line 48 of file eel-wrap-table.h.
EelWrapTablePrivate
typedef struct EelWrapTablePrivate EelWrapTablePrivate
Definition at line 49 of file eel-wrap-table.h.
Enumeration Type Documentation
EelJustification
enum EelJustification
Enumerator
EEL_JUSTIFICATION_BEGINNING
EEL_JUSTIFICATION_MIDDLE
EEL_JUSTIFICATION_END
Definition at line 65 of file eel-wrap-table.h.
Function Documentation
eel_scrolled_wrap_table_new()
GtkWidget * eel_scrolled_wrap_table_new (gboolean homogeneous, GtkShadowType shadow_type, GtkWidget ** wrap_table_out)
Definition at line 1094 of file eel-wrap-table.c.
References EEL_WRAP_TABLE, eel_wrap_table_new(), FALSE, and NULL.
eel_wrap_table_find_child_at_event_point()
GtkWidget * eel_wrap_table_find_child_at_event_point (const EelWrapTable * wrap_table, int x, int y)
eel_wrap_table_find_child_at_event_point: @wrap_table: A EelWrapTable. @x: Event x; @y: Event y;
Returns: Child found at given coordinates or NULL of no child is found.
Definition at line 890 of file eel-wrap-table.c.
References EelWrapTable::details, eel_gtk_widget_get_bounds(), eel_irect_contains_point(), EEL_IS_WRAP_TABLE, and NULL.
eel_wrap_table_get_homogeneous()
gboolean eel_wrap_table_get_homogeneous (const EelWrapTable * wrap_table)
eel_wrap_table_get_item_spacing: @wrap_table: A EelWrapTable.
Returns: The horizontal spacing between wraps.
Definition at line 1019 of file eel-wrap-table.c.
References EelWrapTable::details, EEL_IS_WRAP_TABLE, and FALSE.
eel_wrap_table_get_num_children()
guint eel_wrap_table_get_num_children (const EelWrapTable * wrap_table)
eel_wrap_table_get_num_children: @wrap_table: A EelWrapTable.
Returns: The number of children being managed by the wrap table.
Definition at line 1086 of file eel-wrap-table.c.
References EelWrapTable::details, and EEL_IS_WRAP_TABLE.
eel_wrap_table_get_type()
GType eel_wrap_table_get_type (void)
Referenced by eel_wrap_table_new().
eel_wrap_table_get_x_justification()
EelJustification eel_wrap_table_get_x_justification (const EelWrapTable * wrap_table)
eel_wrap_table_get_item_justification: @wrap_table: A EelWrapTable.
Returns: The horizontal justification between wraps.
Definition at line 950 of file eel-wrap-table.c.
References EelWrapTable::details, and EEL_IS_WRAP_TABLE.
eel_wrap_table_get_x_spacing()
guint eel_wrap_table_get_x_spacing (const EelWrapTable * wrap_table)
eel_wrap_table_get_item_spacing: @wrap_table: A EelWrapTable.
Returns: The horizontal spacing between wraps.
Definition at line 838 of file eel-wrap-table.c.
References EelWrapTable::details, and EEL_IS_WRAP_TABLE.
eel_wrap_table_get_y_justification()
EelJustification eel_wrap_table_get_y_justification (const EelWrapTable * wrap_table)
eel_wrap_table_get_item_justification: @wrap_table: A EelWrapTable.
Returns: The horizontal justification between wraps.
Definition at line 987 of file eel-wrap-table.c.
References EelWrapTable::details, and EEL_IS_WRAP_TABLE.
eel_wrap_table_get_y_spacing()
guint eel_wrap_table_get_y_spacing (const EelWrapTable * wrap_table)
eel_wrap_table_get_item_spacing: @wrap_table: A EelWrapTable.
Returns: The horizontal spacing between wraps.
Definition at line 874 of file eel-wrap-table.c.
References EelWrapTable::details, and EEL_IS_WRAP_TABLE.
eel_wrap_table_new()
GtkWidget * eel_wrap_table_new (gboolean homogeneous)
eel_wrap_table_new:
Definition at line 796 of file eel-wrap-table.c.
References EelWrapTable::details, EEL_WRAP_TABLE, eel_wrap_table_get_type(), eel_wrap_table_set_homogeneous(), FALSE, and NULL.
Referenced by eel_scrolled_wrap_table_new(), and main().
eel_wrap_table_reorder_child()
void eel_wrap_table_reorder_child (EelWrapTable * wrap_table, GtkWidget * child, int position)
eel_wrap_table_reorder_child: @wrap_table: A EelWrapTable. @child: Child to reorder. @position: New position to put child at.
Reorder the given chilren into the given position.
Position is interpreted as follows:
0 - Place child at start of table. -1 - Place child at end of table. n - Place child at nth position. Count starts at 0.
Definition at line 1041 of file eel-wrap-table.c.
References EelWrapTable::details, EEL_IS_WRAP_TABLE, FALSE, NULL, and TRUE.
eel_wrap_table_set_homogeneous()
void eel_wrap_table_set_homogeneous (EelWrapTable * wrap_table, gboolean homogeneous)
eel_wrap_table_set_homogeneous: @wrap_table: A EelWrapTable. @homogeneous: The new horizontal spacing between wraps.
Definition at line 1001 of file eel-wrap-table.c.
References EelWrapTable::details, and EEL_IS_WRAP_TABLE.
Referenced by eel_image_table_new(), and eel_wrap_table_new().
eel_wrap_table_set_x_justification()
void eel_wrap_table_set_x_justification (EelWrapTable * wrap_table, EelJustification x_justification)
eel_wrap_table_set_x_justification: @wrap_table: A EelWrapTable. @x_justification: The new horizontal justification between wraps.
Definition at line 927 of file eel-wrap-table.c.
References EelWrapTable::details, EEL_IS_WRAP_TABLE, EEL_JUSTIFICATION_BEGINNING, and EEL_JUSTIFICATION_END.
eel_wrap_table_set_x_spacing()
void eel_wrap_table_set_x_spacing (EelWrapTable * wrap_table, guint x_spacing)
eel_wrap_table_set_x_spacing: @wrap_table: A EelWrapTable. @x_spacing: The new horizontal spacing between wraps.
Definition at line 816 of file eel-wrap-table.c.
References EelWrapTable::details, and EEL_IS_WRAP_TABLE.
eel_wrap_table_set_y_justification()
void eel_wrap_table_set_y_justification (EelWrapTable * wrap_table, EelJustification y_justification)
eel_wrap_table_set_y_justification: @wrap_table: A EelWrapTable. @y_justification: The new horizontal justification between wraps.
Definition at line 964 of file eel-wrap-table.c.
References EelWrapTable::details, EEL_IS_WRAP_TABLE, EEL_JUSTIFICATION_BEGINNING, and EEL_JUSTIFICATION_END.
eel_wrap_table_set_y_spacing()
void eel_wrap_table_set_y_spacing (EelWrapTable * wrap_table, guint y_spacing)
eel_wrap_table_set_y_spacing: @wrap_table: A EelWrapTable. @y_spacing: The new horizontal spacing between wraps.
Definition at line 852 of file eel-wrap-table.c.
References EelWrapTable::details, and EEL_IS_WRAP_TABLE.