MATE Desktop Environment: eel-accessibility.h File Reference
eel-accessibility.h File Reference
#include <glib-object.h>
#include <atk/atkobject.h>
#include <atk/atkregistry.h>
#include <atk/atkobjectfactory.h>
#include <gtk/gtk.h>
#include <libgail-util/gailtextutil.h>
Classes
struct EelAccessibleTextIface
Macros
#define EEL_TYPE_ACCESSIBLE_TEXT (eel_accessible_text_get_type ())
#define EEL_IS_ACCESSIBLE_TEXT(obj)
#define EEL_ACCESSIBLE_TEXT(obj)
#define EEL_ACCESSIBLE_TEXT_GET_IFACE(obj)
#define EEL_ACCESSIBLE_FACTORY(type, factory_name, type_as_function, opt_create_accessible)
#define EEL_OBJECT_SET_FACTORY(object_type, type_as_function)
Typedefs
typedef struct _EelAccessibleText EelAccessibleText
Functions
void eel_accessibility_set_up_label_widget_relation (GtkWidget *label, GtkWidget *widget)
AtkObject * eel_accessibility_for_object (gpointer object)
gpointer eel_accessibility_get_gobject (AtkObject *object)
void eel_accessibility_set_name (gpointer object, const char *name)
void eel_accessibility_set_description (gpointer object, const char *description)
char * eel_accessibility_text_get_text (AtkText *text, gint start_pos, gint end_pos)
gunichar eel_accessibility_text_get_character_at_offset (AtkText *text, gint offset)
char * eel_accessibility_text_get_text_before_offset (AtkText *text, gint offset, AtkTextBoundary boundary_type, gint *start_offset, gint *end_offset)
char * eel_accessibility_text_get_text_at_offset (AtkText *text, gint offset, AtkTextBoundary boundary_type, gint *start_offset, gint *end_offset)
char * eel_accessibility_text_get_text_after_offset (AtkText *text, gint offset, AtkTextBoundary boundary_type, gint *start_offset, gint *end_offset)
gint eel_accessibility_text_get_character_count (AtkText *text)
GType eel_accessible_text_get_type (void)
Macro Definition Documentation
EEL_ACCESSIBLE_FACTORY
#define EEL_ACCESSIBLE_FACTORY (type, factory_name, type_as_function, opt_create_accessible)
Definition at line 89 of file eel-accessibility.h.
EEL_ACCESSIBLE_TEXT
#define EEL_ACCESSIBLE_TEXT (obj)
Value:
G_TYPE_CHECK_INSTANCE_CAST ((obj), EEL_TYPE_ACCESSIBLE_TEXT, EelAccessibleText)
Definition at line 72 of file eel-accessibility.h.
EEL_ACCESSIBLE_TEXT_GET_IFACE
#define EEL_ACCESSIBLE_TEXT_GET_IFACE (obj)
Value:
(G_TYPE_INSTANCE_GET_INTERFACE ((obj), EEL_TYPE_ACCESSIBLE_TEXT, EelAccessibleTextIface))
Definition at line 73 of file eel-accessibility.h.
EEL_IS_ACCESSIBLE_TEXT
#define EEL_IS_ACCESSIBLE_TEXT (obj)
Value:
G_TYPE_CHECK_INSTANCE_TYPE ((obj), EEL_TYPE_ACCESSIBLE_TEXT)
Definition at line 71 of file eel-accessibility.h.
EEL_OBJECT_SET_FACTORY
#define EEL_OBJECT_SET_FACTORY (object_type, type_as_function)
Value:
atk_registry_set_factory_type (atk_get_default_registry (),     \
                   object_type,             \
                   type_as_function ## _factory_get_type ())
Definition at line 137 of file eel-accessibility.h.
EEL_TYPE_ACCESSIBLE_TEXT
#define EEL_TYPE_ACCESSIBLE_TEXT (eel_accessible_text_get_type ())
Definition at line 70 of file eel-accessibility.h.
Referenced by G_DEFINE_TYPE_WITH_CODE().
Typedef Documentation
EelAccessibleText
typedef struct _EelAccessibleText EelAccessibleText
Definition at line 76 of file eel-accessibility.h.
Function Documentation
eel_accessibility_for_object()
AtkObject * eel_accessibility_for_object (gpointer object)
eel_accessibilty_for_object: @object: a GObject of some sort
gets an AtkObject associated with a GObject and if it doesn't exist creates a suitable accessible object.
Return value: an associated accessible.
Definition at line 70 of file eel-accessibility.c.
Referenced by eel_accessibility_set_description(), and eel_accessibility_set_name().
eel_accessibility_get_gobject()
gpointer eel_accessibility_get_gobject (AtkObject * object)
eel_accessibility_get_gobject: @object: an AtkObject
gets the GObject associated with the AtkObject, for which @object provides accessibility support.
Return value: the accessible's associated GObject
Definition at line 88 of file eel-accessibility.c.
eel_accessibility_set_description()
void eel_accessibility_set_description (gpointer object, const char * description)
Definition at line 253 of file eel-accessibility.c.
References eel_accessibility_for_object().
eel_accessibility_set_name()
void eel_accessibility_set_name (gpointer object, const char * name)
Definition at line 241 of file eel-accessibility.c.
References eel_accessibility_for_object(), and name.
eel_accessibility_set_up_label_widget_relation()
void eel_accessibility_set_up_label_widget_relation (GtkWidget * label, GtkWidget * widget)
Definition at line 32 of file eel-accessibility.c.
References label.
eel_accessibility_text_get_character_at_offset()
gunichar eel_accessibility_text_get_character_at_offset (AtkText * text, gint offset)
Definition at line 140 of file eel-accessibility.c.
References NULL.
eel_accessibility_text_get_character_count()
gint eel_accessibility_text_get_character_count (AtkText * text)
Definition at line 204 of file eel-accessibility.c.
References NULL.
eel_accessibility_text_get_text()
char * eel_accessibility_text_get_text (AtkText * text, gint start_pos, gint end_pos)
Definition at line 129 of file eel-accessibility.c.
References NULL.
eel_accessibility_text_get_text_after_offset()
char * eel_accessibility_text_get_text_after_offset (AtkText * text, gint offset, AtkTextBoundary boundary_type, gint * start_offset, gint * end_offset)
Definition at line 189 of file eel-accessibility.c.
References NULL.
eel_accessibility_text_get_text_at_offset()
char * eel_accessibility_text_get_text_at_offset (AtkText * text, gint offset, AtkTextBoundary boundary_type, gint * start_offset, gint * end_offset)
Definition at line 174 of file eel-accessibility.c.
References NULL.
eel_accessibility_text_get_text_before_offset()
char * eel_accessibility_text_get_text_before_offset (AtkText * text, gint offset, AtkTextBoundary boundary_type, gint * start_offset, gint * end_offset)
Definition at line 159 of file eel-accessibility.c.
References NULL.
eel_accessible_text_get_type()
GType eel_accessible_text_get_type (void)
Definition at line 213 of file eel-accessibility.c.
References NULL.