MATE Desktop Environment: eel-self-checks.c File Reference
eel-self-checks.c File Reference
#include <config.h>
#include "eel-self-checks.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
void eel_exit_if_self_checks_failed (void)
void eel_report_check_failure (char *result, char *expected)
void eel_before_check (const char *expression, const char *file_name, int line_number)
void eel_after_check (void)
void eel_check_boolean_result (gboolean result, gboolean expected)
void eel_check_rectangle_result (EelIRect result, int expected_x0, int expected_y0, int expected_x1, int expected_y1)
void eel_check_dimensions_result (EelDimensions result, int expected_width, int expected_height)
void eel_check_point_result (EelIPoint result, int expected_x, int expected_y)
void eel_check_integer_result (long result, long expected)
void eel_check_double_result (double result, double expected)
void eel_check_string_result (char *result, const char *expected)
void eel_before_check_function (const char *name)
void eel_after_check_function (void)
Function Documentation
eel_after_check()
void eel_after_check (void)
Definition at line 98 of file eel-self-checks.c.
Referenced by eel_check_boolean_result(), eel_check_dimensions_result(), eel_check_double_result(), eel_check_integer_result(), eel_check_point_result(), eel_check_rectangle_result(), and eel_check_string_result().
eel_after_check_function()
void eel_after_check_function (void)
Definition at line 233 of file eel-self-checks.c.
eel_before_check()
void eel_before_check (const char * expression, const char * file_name, int line_number)
Definition at line 88 of file eel-self-checks.c.
eel_before_check_function()
void eel_before_check_function (const char * name)
Definition at line 227 of file eel-self-checks.c.
References name.
eel_check_boolean_result()
void eel_check_boolean_result (gboolean result, gboolean expected)
Definition at line 104 of file eel-self-checks.c.
References eel_after_check(), and eel_report_check_failure().
eel_check_dimensions_result()
void eel_check_dimensions_result (EelDimensions result, int expected_width, int expected_height)
Definition at line 141 of file eel-self-checks.c.
References eel_after_check(), eel_report_check_failure(), EelDimensions::height, and EelDimensions::width.
eel_check_double_result()
void eel_check_double_result (double result, double expected)
Definition at line 188 of file eel-self-checks.c.
References eel_after_check(), and eel_report_check_failure().
eel_check_integer_result()
void eel_check_integer_result (long result, long expected)
Definition at line 177 of file eel-self-checks.c.
References eel_after_check(), and eel_report_check_failure().
eel_check_point_result()
void eel_check_point_result (EelIPoint result, int expected_x, int expected_y)
Definition at line 159 of file eel-self-checks.c.
References eel_after_check(), eel_report_check_failure(), EelIPoint::x, and EelIPoint::y.
eel_check_rectangle_result()
void eel_check_rectangle_result (EelIRect result, int expected_x0, int expected_y0, int expected_x1, int expected_y1)
Definition at line 115 of file eel-self-checks.c.
References eel_after_check(), eel_report_check_failure(), EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
eel_check_string_result()
void eel_check_string_result (char * result, const char * expected)
Definition at line 199 of file eel-self-checks.c.
References eel_after_check(), eel_report_check_failure(), and NULL.
eel_exit_if_self_checks_failed()
void eel_exit_if_self_checks_failed (void)
Definition at line 42 of file eel-self-checks.c.
Referenced by main().
eel_report_check_failure()
void eel_report_check_failure (char * result, char * expected)
Definition at line 55 of file eel-self-checks.c.
References NULL, and TRUE.
Referenced by eel_check_boolean_result(), eel_check_dimensions_result(), eel_check_double_result(), eel_check_integer_result(), eel_check_point_result(), eel_check_rectangle_result(), and eel_check_string_result().