MATE Desktop Environment: eel-gdk-extensions.h File Reference
eel-gdk-extensions.h File Reference
#include <gdk/gdk.h>
Macros
#define EEL_RGB_COLOR_RED 0xFF0000
#define EEL_RGB_COLOR_GREEN 0x00FF00
#define EEL_RGB_COLOR_BLUE 0x0000FF
#define EEL_RGB_COLOR_WHITE 0xFFFFFF
#define EEL_RGB_COLOR_BLACK 0x000000
#define EEL_RGBA_COLOR_OPAQUE_RED 0xFFFF0000
#define EEL_RGBA_COLOR_OPAQUE_GREEN 0xFF00FF00
#define EEL_RGBA_COLOR_OPAQUE_BLUE 0xFF0000FF
#define EEL_RGBA_COLOR_OPAQUE_WHITE 0xFFFFFFFF
#define EEL_RGBA_COLOR_OPAQUE_BLACK 0xFF000000
#define EEL_RGBA_COLOR_PACK(r, g, b, a)
#define EEL_RGB_COLOR_PACK(r, g, b)
#define EEL_RGBA_COLOR_GET_R(color)
#define EEL_RGBA_COLOR_GET_G(color)
#define EEL_RGBA_COLOR_GET_B(color)
#define EEL_RGBA_COLOR_GET_A(color)
Enumerations
enum EelGdkGeometryFlags {
EEL_GDK_NO_VALUE = 0x00 , EEL_GDK_X_VALUE = 0x01 , EEL_GDK_Y_VALUE = 0x02 , EEL_GDK_WIDTH_VALUE = 0x04 ,
EEL_GDK_HEIGHT_VALUE = 0x08 , EEL_GDK_ALL_VALUES = 0x0f , EEL_GDK_X_NEGATIVE = 0x10 , EEL_GDK_Y_NEGATIVE = 0x20
}
Functions
char * eel_gradient_new (const char *start_color, const char *end_color, gboolean is_horizontal)
char * eel_gradient_parse_one_color_spec (const char *spec, int *percent, const char **next_spec)
gboolean eel_gradient_is_gradient (const char *gradient_spec)
char * eel_gradient_get_start_color_spec (const char *gradient_spec)
char * eel_gradient_get_end_color_spec (const char *gradient_spec)
gboolean eel_gradient_is_horizontal (const char *gradient_spec)
char * eel_gradient_set_left_color_spec (const char *gradient_spec, const char *left_color)
char * eel_gradient_set_top_color_spec (const char *gradient_spec, const char *top_color)
char * eel_gradient_set_right_color_spec (const char *gradient_spec, const char *right_color)
char * eel_gradient_set_bottom_color_spec (const char *gradient_spec, const char *bottom_color)
void eel_gdk_rgba_parse_with_white_default (GdkRGBA *parsed_color, const char *color_spec)
guint32 eel_rgb16_to_rgb (gushort r, gushort g, gushort b)
guint32 eel_gdk_rgba_to_rgb (const GdkRGBA *color)
GdkRGBA eel_gdk_rgb_to_rgba (guint32 color)
char * eel_gdk_rgb_to_color_spec (guint32 color)
gboolean eel_gdk_rgba_is_dark (const GdkRGBA *color)
EelGdkGeometryFlags eel_gdk_parse_geometry (const char *string, int *x_return, int *y_return, guint *width_return, guint *height_return)
Macro Definition Documentation
EEL_RGB_COLOR_BLACK
#define EEL_RGB_COLOR_BLACK 0x000000
Definition at line 35 of file eel-gdk-extensions.h.
Referenced by EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), and EEL_CHECK_STRING_RESULT().
EEL_RGB_COLOR_BLUE
#define EEL_RGB_COLOR_BLUE 0x0000FF
Definition at line 33 of file eel-gdk-extensions.h.
Referenced by EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), and EEL_CHECK_INTEGER_RESULT().
EEL_RGB_COLOR_GREEN
#define EEL_RGB_COLOR_GREEN 0x00FF00
Definition at line 32 of file eel-gdk-extensions.h.
Referenced by EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), and EEL_CHECK_INTEGER_RESULT().
EEL_RGB_COLOR_PACK
#define EEL_RGB_COLOR_PACK (r, g, b)
Value:
EEL_RGBA_COLOR_PACK((r), (g), (b), 0xFF)
Definition at line 51 of file eel-gdk-extensions.h.
Referenced by EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), and EEL_CHECK_STRING_RESULT().
EEL_RGB_COLOR_RED
#define EEL_RGB_COLOR_RED 0xFF0000
Definition at line 31 of file eel-gdk-extensions.h.
Referenced by EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), and EEL_CHECK_STRING_RESULT().
EEL_RGB_COLOR_WHITE
#define EEL_RGB_COLOR_WHITE 0xFFFFFF
Definition at line 34 of file eel-gdk-extensions.h.
Referenced by EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), and EEL_CHECK_STRING_RESULT().
EEL_RGBA_COLOR_GET_A
#define EEL_RGBA_COLOR_GET_A (color)
Value:
(((color) >> 24) & 0xff)
Definition at line 58 of file eel-gdk-extensions.h.
Referenced by EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), and EEL_CHECK_INTEGER_RESULT().
EEL_RGBA_COLOR_GET_B
#define EEL_RGBA_COLOR_GET_B (color)
Value:
(((color) >> 0) & 0xff)
Definition at line 57 of file eel-gdk-extensions.h.
Referenced by EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), and EEL_CHECK_INTEGER_RESULT().
EEL_RGBA_COLOR_GET_G
#define EEL_RGBA_COLOR_GET_G (color)
Value:
(((color) >> 8) & 0xff)
Definition at line 56 of file eel-gdk-extensions.h.
Referenced by EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), and EEL_CHECK_INTEGER_RESULT().
EEL_RGBA_COLOR_GET_R
#define EEL_RGBA_COLOR_GET_R (color)
Value:
(((color) >> 16) & 0xff)
Definition at line 55 of file eel-gdk-extensions.h.
Referenced by EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), and EEL_CHECK_INTEGER_RESULT().
EEL_RGBA_COLOR_OPAQUE_BLACK
#define EEL_RGBA_COLOR_OPAQUE_BLACK 0xFF000000
Definition at line 41 of file eel-gdk-extensions.h.
Referenced by EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), and EEL_CHECK_INTEGER_RESULT().
EEL_RGBA_COLOR_OPAQUE_BLUE
#define EEL_RGBA_COLOR_OPAQUE_BLUE 0xFF0000FF
Definition at line 39 of file eel-gdk-extensions.h.
Referenced by EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), and EEL_CHECK_INTEGER_RESULT().
EEL_RGBA_COLOR_OPAQUE_GREEN
#define EEL_RGBA_COLOR_OPAQUE_GREEN 0xFF00FF00
Definition at line 38 of file eel-gdk-extensions.h.
Referenced by EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), and EEL_CHECK_INTEGER_RESULT().
EEL_RGBA_COLOR_OPAQUE_RED
#define EEL_RGBA_COLOR_OPAQUE_RED 0xFFFF0000
Definition at line 37 of file eel-gdk-extensions.h.
Referenced by EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), and EEL_CHECK_INTEGER_RESULT().
EEL_RGBA_COLOR_OPAQUE_WHITE
#define EEL_RGBA_COLOR_OPAQUE_WHITE 0xFFFFFFFF
Definition at line 40 of file eel-gdk-extensions.h.
Referenced by EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), and EEL_CHECK_INTEGER_RESULT().
EEL_RGBA_COLOR_PACK
#define EEL_RGBA_COLOR_PACK (r, g, b, a)
Value:
((((guint32)a) << 24) |            \
  (((guint32)r) << 16) |            \
  (((guint32)g) <<  8) |            \
  (((guint32)b) <<  0) )
Definition at line 44 of file eel-gdk-extensions.h.
Referenced by EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), EEL_CHECK_INTEGER_RESULT(), and EEL_CHECK_INTEGER_RESULT().
Enumeration Type Documentation
EelGdkGeometryFlags
enum EelGdkGeometryFlags
Enumerator
EEL_GDK_NO_VALUE
EEL_GDK_X_VALUE
EEL_GDK_Y_VALUE
EEL_GDK_WIDTH_VALUE
EEL_GDK_HEIGHT_VALUE
EEL_GDK_ALL_VALUES
EEL_GDK_X_NEGATIVE
EEL_GDK_Y_NEGATIVE
Definition at line 61 of file eel-gdk-extensions.h.
Function Documentation
eel_gdk_parse_geometry()
EelGdkGeometryFlags eel_gdk_parse_geometry (const char * string, int * x_return, int * y_return, guint * width_return, guint * height_return)
Referenced by eel_gtk_window_set_initial_geometry_from_string().
eel_gdk_rgb_to_color_spec()
char * eel_gdk_rgb_to_color_spec (const guint32 color)
eel_gdk_rgb_to_color_spec @color: a gdk_rgb style value.
Converts from a gdk_rgb value style to a string color spec. The gdk_rgb color alpha channel is ignored.
Return value: a newly allocated color spec.
Definition at line 407 of file eel-gdk-extensions.c.
Referenced by eel_bg_get_desktop_color().
eel_gdk_rgb_to_rgba()
GdkRGBA eel_gdk_rgb_to_rgba (guint32 color)
eel_gdk_rgb_to_rgba @color: a gdk_rgb style value.
Converts from a gdk_rgb value style to a GdkRGBA one. The gdk_rgb color alpha channel is ignored.
Return value: A GdkRGBA structure version of the given RGB color.
Definition at line 385 of file eel-gdk-extensions.c.
eel_gdk_rgba_is_dark()
gboolean eel_gdk_rgba_is_dark (const GdkRGBA * color)
Referenced by caja_sidebar_title_select_text_color().
eel_gdk_rgba_parse_with_white_default()
void eel_gdk_rgba_parse_with_white_default (GdkRGBA * color, const char * color_spec)
eel_gdk_rgba_parse_with_white_default @color: Pointer to place to put resulting color. @color_spec: A color spec, or NULL.
The same as gdk_rgba_parse, except sets the color to white if the spec. can't be parsed, instead of returning a boolean flag.
Definition at line 322 of file eel-gdk-extensions.c.
References FALSE, NULL, and TRUE.
eel_gdk_rgba_to_rgb()
guint32 eel_gdk_rgba_to_rgb (const GdkRGBA * color)
eel_gdk_rgba_to_rgb @color: A GdkRGBA style color. Returns: An rgb value.
Converts from a GdkRGBA style color to a gdk_rgb one. Alpha gets set to fully opaque
Definition at line 368 of file eel-gdk-extensions.c.
References eel_rgb16_to_rgb().
Referenced by eel_bg_get_desktop_color().
eel_gradient_get_end_color_spec()
char * eel_gradient_get_end_color_spec (const char * gradient_spec)
eel_gradient_get_end_color_spec @gradient_spec: A gradient spec. string.
Return the end color. This may be the entire gradient_spec if it's a solid color.
Definition at line 195 of file eel-gdk-extensions.c.
References eel_gradient_parse_one_color_spec(), and NULL.
Referenced by EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), and EEL_CHECK_STRING_RESULT().
eel_gradient_get_start_color_spec()
char * eel_gradient_get_start_color_spec (const char * gradient_spec)
eel_gradient_get_start_color_spec @gradient_spec: A gradient spec. string.
Return the start color. This may be the entire gradient_spec if it's a solid color.
Definition at line 182 of file eel-gdk-extensions.c.
References eel_gradient_parse_one_color_spec(), and NULL.
Referenced by EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), and EEL_CHECK_STRING_RESULT().
eel_gradient_is_gradient()
gboolean eel_gradient_is_gradient (const char * gradient_spec)
eel_gradient_is_gradient @gradient_spec: A gradient spec. string.
Return true if the spec. specifies a gradient instead of a solid color.
Definition at line 79 of file eel-gdk-extensions.c.
References eel_strchr(), and NULL.
Referenced by EEL_CHECK_BOOLEAN_RESULT(), EEL_CHECK_BOOLEAN_RESULT(), EEL_CHECK_BOOLEAN_RESULT(), EEL_CHECK_BOOLEAN_RESULT(), and EEL_CHECK_BOOLEAN_RESULT().
eel_gradient_is_horizontal()
gboolean eel_gradient_is_horizontal (const char * gradient_spec)
eel_gradient_is_horizontal @gradient_spec: A gradient spec. string.
Return true if the spec. specifies a horizontal gradient.
Definition at line 91 of file eel-gdk-extensions.c.
References eel_strlen().
eel_gradient_new()
char * eel_gradient_new (const char * start_color, const char * end_color, gboolean is_horizontal)
eel_gradient_new @start_color: Color for the top or left. @end_color: Color for the bottom or right. @is_horizontal: Direction of the gradient.
Create a string that combines the start and end colors along with the direction of the gradient in a standard format.
Definition at line 50 of file eel-gdk-extensions.c.
References eel_strcmp(), and NULL.
Referenced by eel_bg_get_desktop_color(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), and EEL_CHECK_STRING_RESULT().
eel_gradient_parse_one_color_spec()
char * eel_gradient_parse_one_color_spec (const char * spec, int * percent, const char ** next_spec)
Definition at line 119 of file eel-gdk-extensions.c.
References eel_strchr(), int(), and NULL.
Referenced by eel_gradient_get_end_color_spec(), and eel_gradient_get_start_color_spec().
eel_gradient_set_bottom_color_spec()
char * eel_gradient_set_bottom_color_spec (const char * gradient_spec, const char * bottom_color)
eel_gradient_set_bottom_color_spec @gradient_spec: A gradient spec. string. @bottom_color: Color spec. to replace bottom color with.
Changes the bottom color to what's passed in. This creates a vertical gradient.
Definition at line 304 of file eel-gdk-extensions.c.
References FALSE, NULL, and TRUE.
Referenced by eel_background_set_dropped_color(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), and EEL_CHECK_STRING_RESULT().
eel_gradient_set_left_color_spec()
char * eel_gradient_set_left_color_spec (const char * gradient_spec, const char * left_color)
eel_gradient_set_left_color_spec @gradient_spec: A gradient spec. string. @left_color: Color spec. to replace left color with.
Changes the left color to what's passed in. This creates a horizontal gradient.
Definition at line 250 of file eel-gdk-extensions.c.
References FALSE, NULL, and TRUE.
Referenced by eel_background_set_dropped_color(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), and EEL_CHECK_STRING_RESULT().
eel_gradient_set_right_color_spec()
char * eel_gradient_set_right_color_spec (const char * gradient_spec, const char * right_color)
eel_gradient_set_right_color_spec @gradient_spec: A gradient spec. string. @right_color: Color spec. to replace right color with.
Changes the right color to what's passed in. This creates a horizontal gradient.
Definition at line 286 of file eel-gdk-extensions.c.
References NULL, and TRUE.
Referenced by eel_background_set_dropped_color(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), and EEL_CHECK_STRING_RESULT().
eel_gradient_set_top_color_spec()
char * eel_gradient_set_top_color_spec (const char * gradient_spec, const char * top_color)
eel_gradient_set_top_color_spec @gradient_spec: A gradient spec. string. @top_color: Color spec. to replace top color with.
Changes the top color to what's passed in. This creates a vertical gradient.
Definition at line 268 of file eel-gdk-extensions.c.
References FALSE, and NULL.
Referenced by eel_background_set_dropped_color(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), and EEL_CHECK_STRING_RESULT().
eel_rgb16_to_rgb()
guint32 eel_rgb16_to_rgb (gushort r, gushort g, gushort b)
Definition at line 348 of file eel-gdk-extensions.c.
References b.
Referenced by eel_gdk_rgba_to_rgb().