MATE Desktop Environment: eel-stock-dialogs.c File Reference
eel-stock-dialogs.c File Reference
#include <config.h>
#include "eel-stock-dialogs.h"
#include "eel-glib-extensions.h"
#include "eel-gtk-extensions.h"
#include <glib/gi18n-lib.h>
#include <gtk/gtk.h>
Macros
#define TIMED_WAIT_STANDARD_DURATION 2000
#define TIMED_WAIT_MIN_TIME_UP 3000
#define TIMED_WAIT_MINIMUM_DIALOG_WIDTH 300
Functions
GtkWidget * eel_dialog_add_button (GtkDialog *dialog, const gchar *button_text, const gchar *icon_name, gint response_id)
GtkWidget * eel_file_chooser_dialog_new (const gchar *title, GtkWindow *parent, GtkFileChooserAction action, const gchar *first_button_text,...)
void eel_timed_wait_start_with_duration (int duration, EelCancelCallback cancel_callback, gpointer callback_data, const char *wait_message, GtkWindow *parent_window)
void eel_timed_wait_start (EelCancelCallback cancel_callback, gpointer callback_data, const char *wait_message, GtkWindow *parent_window)
void eel_timed_wait_stop (EelCancelCallback cancel_callback, gpointer callback_data)
int eel_run_simple_dialog (GtkWidget *parent, gboolean ignore_close_box, GtkMessageType message_type, const char *primary_text, const char *secondary_text,...)
GtkDialog * eel_show_info_dialog (const char *primary_text, const char *secondary_text, GtkWindow *parent)
GtkDialog * eel_show_info_dialog_with_details (const char *primary_text, const char *secondary_text, const char *detailed_info, GtkWindow *parent)
GtkDialog * eel_show_warning_dialog (const char *primary_text, const char *secondary_text, GtkWindow *parent)
GtkDialog * eel_show_error_dialog (const char *primary_text, const char *secondary_text, GtkWindow *parent)
GtkDialog * eel_show_yes_no_dialog (const char *primary_text, const char *secondary_text, const char *yes_label, const char *no_label, GtkWindow *parent)
GtkDialog * eel_create_question_dialog (const char *primary_text, const char *secondary_text, const char *answer_1, int response_1, const char *answer_2, int response_2, GtkWindow *parent)
Macro Definition Documentation
TIMED_WAIT_MIN_TIME_UP
#define TIMED_WAIT_MIN_TIME_UP 3000
Definition at line 35 of file eel-stock-dialogs.c.
TIMED_WAIT_MINIMUM_DIALOG_WIDTH
#define TIMED_WAIT_MINIMUM_DIALOG_WIDTH 300
Definition at line 37 of file eel-stock-dialogs.c.
TIMED_WAIT_STANDARD_DURATION
#define TIMED_WAIT_STANDARD_DURATION 2000
Definition at line 34 of file eel-stock-dialogs.c.
Referenced by eel_timed_wait_start().
Function Documentation
eel_create_question_dialog()
GtkDialog * eel_create_question_dialog (const char * primary_text, const char * secondary_text, const char * answer_1, int response_1, const char * answer_2, int response_2, GtkWindow * parent)
eel_create_question_dialog:
Create a dialog asking a question with at least two choices. The caller needs to set up any necessary callbacks for the buttons. The dialog is not yet shown, so that the caller can add additional buttons or make other visual changes without causing flashiness. @question: The text of the question. @answer_0: The label of the leftmost button (index 0) @answer_1: The label of the 2nd-to-leftmost button (index 1) @parent: The parent window for this dialog.
Definition at line 630 of file eel-stock-dialogs.c.
References _, and eel_dialog_add_button().
Referenced by eel_show_yes_no_dialog().
eel_dialog_add_button()
GtkWidget * eel_dialog_add_button (GtkDialog * dialog, const gchar * button_text, const gchar * icon_name, gint response_id)
Definition at line 193 of file eel-stock-dialogs.c.
References TRUE.
Referenced by eel_create_question_dialog(), and eel_run_simple_dialog().
eel_file_chooser_dialog_new()
GtkWidget * eel_file_chooser_dialog_new (const gchar * title, GtkWindow * parent, GtkFileChooserAction action, const gchar * first_button_text, ...)
Definition at line 251 of file eel-stock-dialogs.c.
References action.
eel_run_simple_dialog()
int eel_run_simple_dialog (GtkWidget * parent, gboolean ignore_close_box, GtkMessageType message_type, const char * primary_text, const char * secondary_text, ...)
Definition at line 402 of file eel-stock-dialogs.c.
References _, eel_dialog_add_button(), and NULL.
eel_show_error_dialog()
GtkDialog * eel_show_error_dialog (const char * primary_text, const char * secondary_text, GtkWindow * parent)
Definition at line 578 of file eel-stock-dialogs.c.
Referenced by caja_emblem_install_custom_emblem(), caja_emblem_verify_keyword(), caja_launch_desktop_file(), fm_directory_view_handle_netscape_url_drop(), fm_report_error_loading_directory(), fm_report_error_renaming_file(), fm_report_error_setting_group(), fm_report_error_setting_owner(), and fm_report_error_setting_permissions().
eel_show_info_dialog()
GtkDialog * eel_show_info_dialog (const char * primary_text, const char * secondary_text, GtkWindow * parent)
Definition at line 533 of file eel-stock-dialogs.c.
Referenced by eel_show_info_dialog_with_details().
eel_show_info_dialog_with_details()
GtkDialog * eel_show_info_dialog_with_details (const char * primary_text, const char * secondary_text, const char * detailed_info, GtkWindow * parent)
Definition at line 543 of file eel-stock-dialogs.c.
References eel_show_info_dialog(), and NULL.
eel_show_warning_dialog()
GtkDialog * eel_show_warning_dialog (const char * primary_text, const char * secondary_text, GtkWindow * parent)
Definition at line 568 of file eel-stock-dialogs.c.
Referenced by caja_launch_desktop_file(), caja_restore_files_from_trash(), fm_directory_view_handle_netscape_url_drop(), and fm_directory_view_handle_uri_list_drop().
eel_show_yes_no_dialog()
GtkDialog * eel_show_yes_no_dialog (const char * primary_text, const char * secondary_text, const char * yes_label, const char * no_label, GtkWindow * parent)
eel_show_yes_no_dialog:
Create and show a dialog asking a question with two choices. The caller needs to set up any necessary callbacks for the buttons. Use eel_create_question_dialog instead if any visual changes need to be made, to avoid flashiness. @question: The text of the question. @yes_label: The label of the "yes" button. @no_label: The label of the "no" button. @parent: The parent window for this dialog.
Definition at line 600 of file eel-stock-dialogs.c.
References eel_create_question_dialog(), and NULL.
eel_timed_wait_start()
void eel_timed_wait_start (EelCancelCallback cancel_callback, gpointer callback_data, const char * wait_message, GtkWindow * parent_window)
Definition at line 372 of file eel-stock-dialogs.c.
References eel_timed_wait_start_with_duration(), and TIMED_WAIT_STANDARD_DURATION.
Referenced by fm_properties_window_present(), and fm_rename_file().
eel_timed_wait_start_with_duration()
void eel_timed_wait_start_with_duration (int duration, EelCancelCallback cancel_callback, gpointer callback_data, const char * wait_message, GtkWindow * parent_window)
Definition at line 333 of file eel-stock-dialogs.c.
References eel_g_hash_table_new_free_at_exit(), and NULL.
Referenced by eel_timed_wait_start().
eel_timed_wait_stop()
void eel_timed_wait_stop (EelCancelCallback cancel_callback, gpointer callback_data)
Definition at line 384 of file eel-stock-dialogs.c.
References key, and NULL.