MATE Desktop Environment: eel-art-extensions.c File Reference
eel-art-extensions.c File Reference
#include <config.h>
#include "eel-art-extensions.h"
#include "eel-lib-self-check-functions.h"
#include <math.h>
Functions
void eel_irect_copy (EelIRect *dest, const EelIRect *src)
void eel_irect_union (EelIRect *dest, const EelIRect *src1, const EelIRect *src2)
void eel_irect_intersect (EelIRect *dest, const EelIRect *src1, const EelIRect *src2)
gboolean eel_irect_is_empty (const EelIRect *src)
EelIRect eel_irect_assign (int x, int y, int width, int height)
EelIRect eel_irect_assign_dimensions (int x, int y, EelDimensions dimensions)
int eel_irect_get_width (EelIRect rectangle)
int eel_irect_get_height (EelIRect rectangle)
void eel_drect_union (EelDRect *dest, const EelDRect *src1, const EelDRect *src2)
gboolean eel_irect_contains_point (EelIRect rectangle, int x, int y)
gboolean eel_irect_hits_irect (EelIRect rectangle_a, EelIRect rectangle_b)
gboolean eel_irect_equal (EelIRect rectangle_a, EelIRect rectangle_b)
EelIRect eel_irect_align (EelIRect container, int aligned_width, int aligned_height, float x_alignment, float y_alignment)
gboolean eel_dimensions_are_empty (EelDimensions dimensions)
EelIRect eel_irect_offset_by (EelIRect rectangle, int x, int y)
EelIRect eel_irect_scale_by (EelIRect rectangle, double scale)
Variables
const EelDRect eel_drect_empty = { 0.0, 0.0, 0.0, 0.0 }
const EelIRect eel_irect_empty = { 0, 0, 0, 0 }
const EelIPoint eel_ipoint_max = { G_MAXINT, G_MAXINT }
const EelIPoint eel_ipoint_min = { G_MININT, G_MININT }
const EelIPoint eel_ipoint_zero = { 0, 0 }
const EelDimensions eel_dimensions_empty = { 0, 0 }
Function Documentation
eel_dimensions_are_empty()
gboolean eel_dimensions_are_empty (EelDimensions dimensions)
eel_dimensions_are_empty:
@dimensions: A EelDimensions structure.
Returns: Whether the dimensions are empty.
Definition at line 293 of file eel-art-extensions.c.
References EelDimensions::height, and EelDimensions::width.
Referenced by eel_labeled_image_get_image_bounds(), and eel_labeled_image_get_label_bounds().
eel_drect_union()
void eel_drect_union (EelDRect * dest, const EelDRect * src1, const EelDRect * src2)
Definition at line 173 of file eel-art-extensions.c.
References dest, MAX, MIN, EelDRect::x0, EelDRect::x1, EelDRect::y0, and EelDRect::y1.
eel_irect_align()
EelIRect eel_irect_align (EelIRect container, int aligned_width, int aligned_height, float x_alignment, float y_alignment)
eel_irect_align:
@container: The rectangle that is to contain the aligned rectangle. @aligned_width: Width of rectangle being algined. @aligned_height: Height of rectangle being algined. @x_alignment: X alignment. @y_alignment: Y alignment.
Returns: A rectangle aligned within a container rectangle using the given alignment parameters.
Definition at line 248 of file eel-art-extensions.c.
References eel_irect_empty, eel_irect_get_height(), eel_irect_get_width(), eel_irect_is_empty(), MAX, MIN, EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
eel_irect_assign()
EelIRect eel_irect_assign (int x, int y, int width, int height)
Definition at line 89 of file eel-art-extensions.c.
References EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
Referenced by eel_gtk_widget_get_bounds().
eel_irect_assign_dimensions()
EelIRect eel_irect_assign_dimensions (int x, int y, EelDimensions dimensions)
eel_irect_assign_dimensions:
@x: X coodinate for resulting rectangle. @y: Y coodinate for resulting rectangle. @dimensions: A EelDimensions structure for the rect's width and height.
Returns: An EelIRect with the given coordinates and dimensions.
Definition at line 114 of file eel-art-extensions.c.
References EelDimensions::height, EelDimensions::width, EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
eel_irect_contains_point()
gboolean eel_irect_contains_point (EelIRect rectangle, int x, int y)
eel_irect_contains_point:
@rectangle: An EelIRect. @x: X coordinate to test. @y: Y coordinate to test.
Returns: A boolean value indicating whether the rectangle contains the x,y coordinate.
Definition at line 206 of file eel-art-extensions.c.
References EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
Referenced by eel_wrap_table_find_child_at_event_point().
eel_irect_copy()
void eel_irect_copy (EelIRect * dest, const EelIRect * src)
Definition at line 40 of file eel-art-extensions.c.
References dest, EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
Referenced by eel_irect_union().
eel_irect_equal()
gboolean eel_irect_equal (EelIRect rectangle_a, EelIRect rectangle_b)
Definition at line 226 of file eel-art-extensions.c.
References EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
Referenced by caja_icon_canvas_item_update_bounds().
eel_irect_get_height()
int eel_irect_get_height (EelIRect rectangle)
eel_irect_get_height:
@rectangle: An EelIRect.
Returns: The height of the rectangle.
Definition at line 151 of file eel-art-extensions.c.
References EelIRect::y0, and EelIRect::y1.
Referenced by eel_gtk_container_child_size_allocate(), eel_irect_align(), eel_labeled_image_get_image_bounds(), and eel_labeled_image_get_label_bounds().
eel_irect_get_width()
int eel_irect_get_width (EelIRect rectangle)
eel_irect_get_width:
@rectangle: An EelIRect.
Returns: The width of the rectangle.
Definition at line 137 of file eel-art-extensions.c.
References EelIRect::x0, and EelIRect::x1.
Referenced by eel_gtk_container_child_size_allocate(), eel_irect_align(), eel_labeled_image_get_image_bounds(), and eel_labeled_image_get_label_bounds().
eel_irect_hits_irect()
gboolean eel_irect_hits_irect (EelIRect rectangle_a, EelIRect rectangle_b)
Definition at line 217 of file eel-art-extensions.c.
References eel_irect_intersect(), and eel_irect_is_empty().
eel_irect_intersect()
void eel_irect_intersect (EelIRect * dest, const EelIRect * src1, const EelIRect * src2)
Definition at line 71 of file eel-art-extensions.c.
References dest, MAX, MIN, EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
Referenced by eel_irect_hits_irect().
eel_irect_is_empty()
gboolean eel_irect_is_empty (const EelIRect * src)
Definition at line 82 of file eel-art-extensions.c.
References EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
Referenced by eel_gtk_container_child_size_allocate(), eel_irect_align(), eel_irect_hits_irect(), and eel_irect_union().
eel_irect_offset_by()
EelIRect eel_irect_offset_by (EelIRect rectangle, int x, int y)
Definition at line 299 of file eel-art-extensions.c.
References EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
eel_irect_scale_by()
EelIRect eel_irect_scale_by (EelIRect rectangle, double scale)
Definition at line 310 of file eel-art-extensions.c.
References EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
eel_irect_union()
void eel_irect_union (EelIRect * dest, const EelIRect * src1, const EelIRect * src2)
Definition at line 49 of file eel-art-extensions.c.
References dest, eel_irect_copy(), eel_irect_is_empty(), MAX, MIN, EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
Referenced by caja_icon_canvas_item_update_bounds().
Variable Documentation
eel_dimensions_empty
const EelDimensions eel_dimensions_empty = { 0, 0 }
Definition at line 37 of file eel-art-extensions.c.
Referenced by eel_gtk_widget_get_dimensions().
eel_drect_empty
const EelDRect eel_drect_empty = { 0.0, 0.0, 0.0, 0.0 }
Definition at line 32 of file eel-art-extensions.c.
Referenced by caja_icon_canvas_item_get_icon_rectangle(), and caja_icon_canvas_item_get_text_rectangle().
eel_ipoint_max
const EelIPoint eel_ipoint_max = { G_MAXINT, G_MAXINT }
Definition at line 34 of file eel-art-extensions.c.
eel_ipoint_min
const EelIPoint eel_ipoint_min = { G_MININT, G_MININT }
Definition at line 35 of file eel-art-extensions.c.
eel_ipoint_zero
const EelIPoint eel_ipoint_zero = { 0, 0 }
Definition at line 36 of file eel-art-extensions.c.
eel_irect_empty
const EelIRect eel_irect_empty = { 0, 0, 0, 0 }
Definition at line 33 of file eel-art-extensions.c.
Referenced by eel_gtk_widget_get_bounds(), eel_irect_align(), eel_labeled_image_get_image_bounds(), and eel_labeled_image_get_label_bounds().