MATE Desktop Environment: eel-canvas-rect-ellipse.c File Reference
eel-canvas-rect-ellipse.c File Reference
#include <config.h>
#include <math.h>
#include "eel-canvas-rect-ellipse.h"
#include <string.h>
Macros
#define DASH_ON 0.8
#define DASH_OFF 1.7
Enumerations
enum {
PROP_0 , PROP_X1 , PROP_Y1 , PROP_X2 ,
PROP_Y2 , PROP_FILL_COLOR_RGBA , PROP_OUTLINE_COLOR_RGBA , PROP_OUTLINE_STIPPLING ,
PROP_WIDTH_PIXELS , PROP_WIDTH_UNITS
}
Functions
GType eel_canvas_re_get_type (void)
GType eel_canvas_rect_get_type (void)
Macro Definition Documentation
DASH_OFF
#define DASH_OFF 1.7
Definition at line 526 of file eel-canvas-rect-ellipse.c.
DASH_ON
#define DASH_ON 0.8
Definition at line 525 of file eel-canvas-rect-ellipse.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_X1
PROP_Y1
PROP_X2
PROP_Y2
PROP_FILL_COLOR_RGBA
PROP_OUTLINE_COLOR_RGBA
PROP_OUTLINE_STIPPLING
PROP_WIDTH_PIXELS
PROP_WIDTH_UNITS
Definition at line 42 of file eel-canvas-rect-ellipse.c.
Function Documentation
eel_canvas_re_get_type()
GType eel_canvas_re_get_type (void)
Definition at line 88 of file eel-canvas-rect-ellipse.c.
References eel_canvas_item_get_type(), and NULL.
Referenced by eel_canvas_rect_get_type().
eel_canvas_rect_get_type()
GType eel_canvas_rect_get_type (void)
Definition at line 453 of file eel-canvas-rect-ellipse.c.
References eel_canvas_re_get_type(), and NULL.