MATE Desktop Environment: eel-gdk-pixbuf-extensions.h File Reference
eel-gdk-pixbuf-extensions.h File Reference
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gdk/gdk.h>
#include <gio/gio.h>
Functions
GdkPixbuf * eel_gdk_pixbuf_load (const char *uri)
GdkPixbuf * eel_gdk_pixbuf_load_from_stream (GInputStream *stream)
GdkPixbuf * eel_gdk_pixbuf_load_from_stream_at_size (GInputStream *stream, int size)
GdkPixbuf * eel_gdk_pixbuf_scale_down_to_fit (GdkPixbuf *pixbuf, int max_width, int max_height)
GdkPixbuf * eel_gdk_pixbuf_scale_to_fit (GdkPixbuf *pixbuf, int max_width, int max_height)
double eel_gdk_scale_to_fit_factor (int width, int height, int max_width, int max_height, int *scaled_width, int *scaled_height)
GdkPixbuf * eel_gdk_pixbuf_scale_to_min (GdkPixbuf *pixbuf, int min_width, int min_height)
double eel_gdk_scale_to_min_factor (int width, int height, int min_width, int min_height, int *scaled_width, int *scaled_height)
gboolean eel_gdk_pixbuf_save_to_file (const GdkPixbuf *pixbuf, const char *file_name)
void eel_gdk_pixbuf_ref_if_not_null (GdkPixbuf *pixbuf_or_null)
void eel_gdk_pixbuf_unref_if_not_null (GdkPixbuf *pixbuf_or_null)
GdkPixbuf * eel_gdk_pixbuf_scale_down (GdkPixbuf *pixbuf, int dest_width, int dest_height)
Function Documentation
eel_gdk_pixbuf_load()
GdkPixbuf * eel_gdk_pixbuf_load (const char * uri)
Definition at line 46 of file eel-gdk-pixbuf-extensions.c.
References eel_gdk_pixbuf_load_from_stream(), and NULL.
eel_gdk_pixbuf_load_from_stream()
GdkPixbuf * eel_gdk_pixbuf_load_from_stream (GInputStream * stream)
Definition at line 73 of file eel-gdk-pixbuf-extensions.c.
References eel_gdk_pixbuf_load_from_stream_at_size().
Referenced by caja_emblem_load_pixbuf_for_emblem(), and eel_gdk_pixbuf_load().
eel_gdk_pixbuf_load_from_stream_at_size()
GdkPixbuf * eel_gdk_pixbuf_load_from_stream_at_size (GInputStream * stream, int size)
Definition at line 101 of file eel-gdk-pixbuf-extensions.c.
References FALSE, LOAD_BUFFER_SIZE, NULL, and TRUE.
Referenced by eel_gdk_pixbuf_load_from_stream().
eel_gdk_pixbuf_ref_if_not_null()
void eel_gdk_pixbuf_ref_if_not_null (GdkPixbuf * pixbuf_or_null)
Definition at line 260 of file eel-gdk-pixbuf-extensions.c.
References NULL.
eel_gdk_pixbuf_save_to_file()
gboolean eel_gdk_pixbuf_save_to_file (const GdkPixbuf * pixbuf, const char * file_name)
Definition at line 252 of file eel-gdk-pixbuf-extensions.c.
References NULL.
Referenced by caja_emblem_install_custom_emblem().
eel_gdk_pixbuf_scale_down()
GdkPixbuf * eel_gdk_pixbuf_scale_down (GdkPixbuf * pixbuf, int dest_width, int dest_height)
Definition at line 278 of file eel-gdk-pixbuf-extensions.c.
References b, dest, and NULL.
Referenced by eel_gdk_pixbuf_scale_down_to_fit(), and main().
eel_gdk_pixbuf_scale_down_to_fit()
GdkPixbuf * eel_gdk_pixbuf_scale_down_to_fit (GdkPixbuf * pixbuf, int max_width, int max_height)
Definition at line 199 of file eel-gdk-pixbuf-extensions.c.
References eel_gdk_pixbuf_scale_down(), and eel_gdk_scale_to_fit_factor().
Referenced by caja_customization_data_get_next_element_for_display(), and caja_emblem_load_pixbuf_for_emblem().
eel_gdk_pixbuf_scale_to_fit()
GdkPixbuf * eel_gdk_pixbuf_scale_to_fit (GdkPixbuf * pixbuf, int max_width, int max_height)
Definition at line 182 of file eel-gdk-pixbuf-extensions.c.
References eel_gdk_scale_to_fit_factor().
eel_gdk_pixbuf_scale_to_min()
GdkPixbuf * eel_gdk_pixbuf_scale_to_min (GdkPixbuf * pixbuf, int min_width, int min_height)
Definition at line 239 of file eel-gdk-pixbuf-extensions.c.
References eel_gdk_scale_to_min_factor().
eel_gdk_pixbuf_unref_if_not_null()
void eel_gdk_pixbuf_unref_if_not_null (GdkPixbuf * pixbuf_or_null)
Definition at line 269 of file eel-gdk-pixbuf-extensions.c.
References NULL.
Referenced by main().
eel_gdk_scale_to_fit_factor()
double eel_gdk_scale_to_fit_factor (int width, int height, int max_width, int max_height, int * scaled_width, int * scaled_height)
Definition at line 164 of file eel-gdk-pixbuf-extensions.c.
References MIN.
Referenced by eel_gdk_pixbuf_scale_down_to_fit(), and eel_gdk_pixbuf_scale_to_fit().
eel_gdk_scale_to_min_factor()
double eel_gdk_scale_to_min_factor (int width, int height, int min_width, int min_height, int * scaled_width, int * scaled_height)
Definition at line 221 of file eel-gdk-pixbuf-extensions.c.
References MAX.
Referenced by eel_gdk_pixbuf_scale_to_min().