MATE Desktop Environment: eel-graphic-effects.h File Reference
eel-graphic-effects.h File Reference
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
Functions
GdkPixbuf * eel_create_spotlight_pixbuf (GdkPixbuf *source_pixbuf)
cairo_surface_t * eel_create_spotlight_surface (cairo_surface_t *source_surface, int scale)
GdkPixbuf * eel_create_darkened_pixbuf (GdkPixbuf *source_pixbuf, int saturation, int darken)
GdkPixbuf * eel_create_colorized_pixbuf (GdkPixbuf *source_pixbuf, GdkRGBA *color)
GdkPixbuf * eel_stretch_frame_image (GdkPixbuf *frame_image, int left_offset, int top_offset, int right_offset, int bottom_offset, int dest_width, int dest_height, gboolean fill_flag)
GdkPixbuf * eel_embed_image_in_frame (GdkPixbuf *source_image, GdkPixbuf *frame_image, int left_offset, int top_offset, int right_offset, int bottom_offset)
Function Documentation
eel_create_colorized_pixbuf()
GdkPixbuf * eel_create_colorized_pixbuf (GdkPixbuf * source_pixbuf, GdkRGBA * color)
Definition at line 190 of file eel-graphic-effects.c.
References dest, eel_round(), and NULL.
eel_create_darkened_pixbuf()
GdkPixbuf * eel_create_darkened_pixbuf (GdkPixbuf * source_pixbuf, int saturation, int darken)
Definition at line 132 of file eel-graphic-effects.c.
References b, dest, and NULL.
eel_create_spotlight_pixbuf()
GdkPixbuf * eel_create_spotlight_pixbuf (GdkPixbuf * source_pixbuf)
Definition at line 68 of file eel-graphic-effects.c.
References dest, and NULL.
eel_create_spotlight_surface()
cairo_surface_t * eel_create_spotlight_surface (cairo_surface_t * source_surface, int scale)
Definition at line 113 of file eel-graphic-effects.c.
References dest, and NULL.
eel_embed_image_in_frame()
GdkPixbuf * eel_embed_image_in_frame (GdkPixbuf * source_image, GdkPixbuf * frame_image, int left_offset, int top_offset, int right_offset, int bottom_offset)
Definition at line 347 of file eel-graphic-effects.c.
References eel_stretch_frame_image(), and FALSE.
Referenced by caja_ui_frame_image().
eel_stretch_frame_image()
GdkPixbuf * eel_stretch_frame_image (GdkPixbuf * frame_image, int left_offset, int top_offset, int right_offset, int bottom_offset, int dest_width, int dest_height, gboolean fill_flag)
Definition at line 284 of file eel-graphic-effects.c.
References TRUE.
Referenced by eel_embed_image_in_frame().