MATE Desktop Environment: eel-vfs-extensions.h File Reference
eel-vfs-extensions.h File Reference
#include <glib.h>
Macros
#define EEL_TRASH_URI "trash:"
#define EEL_DESKTOP_URI "x-caja-desktop:"
#define EEL_SEARCH_URI "x-caja-search:"
Functions
gboolean eel_uri_is_trash (const char *uri)
gboolean eel_uri_is_trash_folder (const char *uri)
gboolean eel_uri_is_in_trash (const char *uri)
gboolean eel_uri_is_desktop (const char *uri)
gboolean eel_uri_is_search (const char *uri)
char * eel_make_valid_utf8 (const char *name)
char * eel_filename_strip_extension (const char *filename)
void eel_filename_get_rename_region (const char *filename, int *start_offset, int *end_offset)
Macro Definition Documentation
EEL_DESKTOP_URI
#define EEL_DESKTOP_URI "x-caja-desktop:"
Definition at line 39 of file eel-vfs-extensions.h.
Referenced by caja_desktop_icon_file_new(), caja_desktop_window_update_directory(), caja_window_slot_open_location_full(), and eel_uri_is_desktop().
EEL_SEARCH_URI
#define EEL_SEARCH_URI "x-caja-search:"
Definition at line 40 of file eel-vfs-extensions.h.
Referenced by caja_search_directory_generate_new_uri(), and eel_uri_is_search().
EEL_TRASH_URI
#define EEL_TRASH_URI "trash:"
Definition at line 38 of file eel-vfs-extensions.h.
Referenced by caja_desktop_link_new(), and caja_file_get_emblem_icons().
Function Documentation
eel_filename_get_rename_region()
void eel_filename_get_rename_region (const char * filename, int * start_offset, int * end_offset)
Definition at line 143 of file eel-vfs-extensions.c.
References eel_filename_strip_extension(), and NULL.
Referenced by caja_icon_container_start_renaming_selected_item().
eel_filename_strip_extension()
char * eel_filename_strip_extension (const char * filename)
Definition at line 105 of file eel-vfs-extensions.c.
References NULL, and strrchr.
Referenced by eel_filename_get_rename_region(), and main().
eel_make_valid_utf8()
char * eel_make_valid_utf8 (const char * name)
Definition at line 61 of file eel-vfs-extensions.c.
References _, FALSE, name, and NULL.
eel_uri_is_desktop()
gboolean eel_uri_is_desktop (const char * uri)
Definition at line 55 of file eel-vfs-extensions.c.
References EEL_DESKTOP_URI, and eel_istr_has_prefix().
Referenced by caja_drag_default_drop_action_for_icons(), caja_drag_items_on_desktop(), caja_drag_selection_includes_special_link(), caja_link_local_create(), and caja_recent_add_file().
eel_uri_is_in_trash()
gboolean eel_uri_is_in_trash (const char * uri)
References name.
eel_uri_is_search()
gboolean eel_uri_is_search (const char * uri)
Definition at line 49 of file eel-vfs-extensions.c.
References eel_istr_has_prefix(), and EEL_SEARCH_URI.
Referenced by caja_link_local_create(), caja_location_bar_set_location(), and caja_recent_add_file().
eel_uri_is_trash()
gboolean eel_uri_is_trash (const char * uri)
Definition at line 43 of file eel-vfs-extensions.c.
References eel_istr_has_prefix().
Referenced by caja_drag_default_drop_action_for_icons(), caja_drag_default_drop_action_for_uri_list(), caja_link_local_create(), and caja_recent_add_file().
eel_uri_is_trash_folder()
gboolean eel_uri_is_trash_folder (const char * uri)