MATE Desktop Environment: eel-canvas.h File Reference
eel-canvas.h File Reference
#include <gtk/gtk.h>
#include <gtk/gtk-a11y.h>
#include <gdk/gdk.h>
#include <stdarg.h>
Classes
struct _EelCanvasItem
struct _EelCanvasItemClass
struct _EelCanvasGroup
struct _EelCanvasGroupClass
struct _EelCanvas
struct _EelCanvasClass
struct _EelCanvasAccessible
struct _EelCanvasAccessibleClass
struct _EelCanvasItemAccessible
struct _EelCanvasItemAccessibleClass
Macros
#define EEL_CANVAS_EPSILON 1e-10
#define EEL_CANVAS_COLOR(r, g, b)
#define EEL_CANVAS_COLOR_A(r, g, b, a)
#define EEL_TYPE_CANVAS_ITEM (eel_canvas_item_get_type ())
#define EEL_CANVAS_ITEM(obj)
#define EEL_CANVAS_ITEM_CLASS(klass)
#define EEL_IS_CANVAS_ITEM(obj)
#define EEL_IS_CANVAS_ITEM_CLASS(klass)
#define EEL_CANVAS_ITEM_GET_CLASS(obj)
#define EEL_TYPE_CANVAS_GROUP (eel_canvas_group_get_type ())
#define EEL_CANVAS_GROUP(obj)
#define EEL_CANVAS_GROUP_CLASS(klass)
#define EEL_IS_CANVAS_GROUP(obj)
#define EEL_IS_CANVAS_GROUP_CLASS(klass)
#define EEL_CANVAS_GROUP_GET_CLASS(obj)
#define EEL_TYPE_CANVAS (eel_canvas_get_type ())
#define EEL_CANVAS(obj)
#define EEL_CANVAS_CLASS(klass)
#define EEL_IS_CANVAS(obj)
#define EEL_IS_CANVAS_CLASS(klass)
#define EEL_CANVAS_GET_CLASS(obj)
Typedefs
typedef struct _EelCanvas EelCanvas
typedef struct _EelCanvasClass EelCanvasClass
typedef struct _EelCanvasItem EelCanvasItem
typedef struct _EelCanvasItemClass EelCanvasItemClass
typedef struct _EelCanvasGroup EelCanvasGroup
typedef struct _EelCanvasGroupClass EelCanvasGroupClass
typedef struct _EelCanvasAccessible EelCanvasAccessible
typedef struct _EelCanvasAccessibleClass EelCanvasAccessibleClass
typedef struct _EelCanvasItemAccessible EelCanvasItemAccessible
typedef struct _EelCanvasItemAccessibleClass EelCanvasItemAccessibleClass
Enumerations
enum {
EEL_CANVAS_ITEM_REALIZED = 1 << 4 , EEL_CANVAS_ITEM_MAPPED = 1 << 5 , EEL_CANVAS_ITEM_ALWAYS_REDRAW = 1 << 6 , EEL_CANVAS_ITEM_VISIBLE = 1 << 7 ,
EEL_CANVAS_ITEM_NEED_UPDATE = 1 << 8 , EEL_CANVAS_ITEM_NEED_DEEP_UPDATE = 1 << 9
}
enum { EEL_CANVAS_UPDATE_REQUESTED = 1 << 0 , EEL_CANVAS_UPDATE_DEEP = 1 << 1 }
Functions
GType eel_canvas_item_get_type (void)
EelCanvasItem * eel_canvas_item_new (EelCanvasGroup *parent, GType type, const gchar *first_arg_name,...)
void eel_canvas_item_destroy (EelCanvasItem *item)
void eel_canvas_item_construct (EelCanvasItem *item, EelCanvasGroup *parent, const gchar *first_arg_name, va_list args)
void eel_canvas_item_set (EelCanvasItem *item, const gchar *first_arg_name,...)
void eel_canvas_item_set_valist (EelCanvasItem *item, const gchar *first_arg_name, va_list args)
void eel_canvas_item_move (EelCanvasItem *item, double dx, double dy)
void eel_canvas_item_raise (EelCanvasItem *item, int positions)
void eel_canvas_item_lower (EelCanvasItem *item, int positions)
void eel_canvas_item_raise_to_top (EelCanvasItem *item)
void eel_canvas_item_lower_to_bottom (EelCanvasItem *item)
void eel_canvas_item_send_behind (EelCanvasItem *item, EelCanvasItem *behind_item)
void eel_canvas_item_show (EelCanvasItem *item)
void eel_canvas_item_hide (EelCanvasItem *item)
GdkGrabStatus eel_canvas_item_grab (EelCanvasItem *item, GdkEventMask event_mask, GdkCursor *cursor, const GdkEvent *event)
void eel_canvas_item_ungrab (EelCanvasItem *item)
void eel_canvas_item_w2i (EelCanvasItem *item, double *x, double *y)
void eel_canvas_item_i2w (EelCanvasItem *item, double *x, double *y)
void eel_canvas_item_reparent (EelCanvasItem *item, EelCanvasGroup *new_group)
void eel_canvas_item_grab_focus (EelCanvasItem *item)
void eel_canvas_item_get_bounds (EelCanvasItem *item, double *x1, double *y1, double *x2, double *y2)
void eel_canvas_item_request_update (EelCanvasItem *item)
void eel_canvas_item_request_redraw (EelCanvasItem *item)
GType eel_canvas_group_get_type (void)
GType eel_canvas_get_type (void)
GtkWidget * eel_canvas_new (void)
EelCanvasGroup * eel_canvas_root (EelCanvas *canvas)
void eel_canvas_set_scroll_region (EelCanvas *canvas, double x1, double y1, double x2, double y2)
void eel_canvas_get_scroll_region (EelCanvas *canvas, double *x1, double *y1, double *x2, double *y2)
void eel_canvas_set_pixels_per_unit (EelCanvas *canvas, double n)
void eel_canvas_set_center_scroll_region (EelCanvas *canvas, gboolean center_scroll_region)
void eel_canvas_scroll_to (EelCanvas *canvas, int cx, int cy)
void eel_canvas_get_scroll_offsets (EelCanvas *canvas, int *cx, int *cy)
void eel_canvas_update_now (EelCanvas *canvas)
EelCanvasItem * eel_canvas_get_item_at (EelCanvas *canvas, double x, double y)
void eel_canvas_request_redraw (EelCanvas *canvas, int x1, int y1, int x2, int y2)
void eel_canvas_w2c_rect_d (EelCanvas *canvas, double *x1, double *y1, double *x2, double *y2)
void eel_canvas_w2c (EelCanvas *canvas, double wx, double wy, int *cx, int *cy)
void eel_canvas_w2c_d (EelCanvas *canvas, double wx, double wy, double *cx, double *cy)
void eel_canvas_c2w (EelCanvas *canvas, int cx, int cy, double *wx, double *wy)
void eel_canvas_window_to_world (EelCanvas *canvas, double winx, double winy, double *worldx, double *worldy)
void eel_canvas_world_to_window (EelCanvas *canvas, double worldx, double worldy, double *winx, double *winy)
GType eel_canvas_accessible_get_type (void)
GType eel_canvas_item_accessible_get_type (void)
Macro Definition Documentation
EEL_CANVAS
#define EEL_CANVAS (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), EEL_TYPE_CANVAS, EelCanvas))
Definition at line 343 of file eel-canvas.h.
Referenced by caja_icon_container_add(), caja_icon_container_get_first_visible_icon(), caja_icon_container_set_zoom_level(), caja_icon_container_update_icon(), caja_icon_container_update_scroll_region(), and caja_icon_container_widget_to_file_operation_position().
EEL_CANVAS_CLASS
#define EEL_CANVAS_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), EEL_TYPE_CANVAS, EelCanvasClass))
Definition at line 344 of file eel-canvas.h.
EEL_CANVAS_COLOR
#define EEL_CANVAS_COLOR (r, g, b)
Value:
((((int) (r) & 0xff) << 24)    \
| (((int) (g) & 0xff) << 16)   \
| (((int) (b) & 0xff) << 8)    \
| 0xff)
Definition at line 56 of file eel-canvas.h.
EEL_CANVAS_COLOR_A
#define EEL_CANVAS_COLOR_A (r, g, b, a)
Value:
((((int) (r) & 0xff) << 24)   \
| (((int) (g) & 0xff) << 16)  \
| (((int) (b) & 0xff) << 8)   \
| ((int) (a) & 0xff))
Definition at line 61 of file eel-canvas.h.
EEL_CANVAS_EPSILON
#define EEL_CANVAS_EPSILON 1e-10
Definition at line 50 of file eel-canvas.h.
Referenced by eel_canvas_set_pixels_per_unit().
EEL_CANVAS_GET_CLASS
#define EEL_CANVAS_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), EEL_TYPE_CANVAS, EelCanvasClass))
Definition at line 347 of file eel-canvas.h.
EEL_CANVAS_GROUP
#define EEL_CANVAS_GROUP (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), EEL_TYPE_CANVAS_GROUP, EelCanvasGroup))
Definition at line 315 of file eel-canvas.h.
Referenced by caja_icon_container_add(), eel_canvas_item_i2w(), eel_canvas_item_lower(), eel_canvas_item_lower_to_bottom(), eel_canvas_item_raise(), eel_canvas_item_raise_to_top(), eel_canvas_item_reparent(), eel_canvas_item_send_behind(), eel_canvas_item_w2i(), and eel_canvas_root().
EEL_CANVAS_GROUP_CLASS
#define EEL_CANVAS_GROUP_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), EEL_TYPE_CANVAS_GROUP, EelCanvasGroupClass))
Definition at line 316 of file eel-canvas.h.
EEL_CANVAS_GROUP_GET_CLASS
#define EEL_CANVAS_GROUP_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), EEL_TYPE_CANVAS_GROUP, EelCanvasGroupClass))
Definition at line 319 of file eel-canvas.h.
EEL_CANVAS_ITEM
#define EEL_CANVAS_ITEM (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), EEL_TYPE_CANVAS_ITEM, EelCanvasItem))
Definition at line 106 of file eel-canvas.h.
Referenced by caja_icon_canvas_item_get_drag_surface(), caja_icon_canvas_item_get_icon_rectangle(), caja_icon_canvas_item_get_max_text_width(), caja_icon_canvas_item_get_text_rectangle(), caja_icon_canvas_item_hit_test_stretch_handles(), caja_icon_canvas_item_set_embedded_text(), caja_icon_canvas_item_set_embedded_text_rect(), caja_icon_canvas_item_set_emblems(), caja_icon_canvas_item_set_entire_text(), caja_icon_canvas_item_set_image(), caja_icon_canvas_item_set_renaming(), caja_icon_canvas_item_set_show_stretch_handles(), caja_icon_canvas_item_update_bounds(), caja_icon_container_add(), caja_icon_container_get_first_visible_icon(), caja_icon_container_scroll_to_icon(), caja_icon_container_set_highlighted_for_clipboard(), caja_icon_container_start_renaming_selected_item(), caja_icon_container_update_icon(), eel_canvas_item_construct(), eel_canvas_item_new(), and eel_canvas_item_reparent().
EEL_CANVAS_ITEM_CLASS
#define EEL_CANVAS_ITEM_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), EEL_TYPE_CANVAS_ITEM, EelCanvasItemClass))
Definition at line 107 of file eel-canvas.h.
EEL_CANVAS_ITEM_GET_CLASS
#define EEL_CANVAS_ITEM_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), EEL_TYPE_CANVAS_ITEM, EelCanvasItemClass))
Definition at line 110 of file eel-canvas.h.
Referenced by eel_canvas_item_get_bounds(), eel_canvas_item_hide(), eel_canvas_item_move(), and eel_canvas_item_show().
EEL_IS_CANVAS
#define EEL_IS_CANVAS (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), EEL_TYPE_CANVAS))
Definition at line 345 of file eel-canvas.h.
Referenced by eel_canvas_c2w(), eel_canvas_get_item_at(), eel_canvas_get_scroll_offsets(), eel_canvas_get_scroll_region(), eel_canvas_request_redraw(), eel_canvas_root(), eel_canvas_scroll_to(), eel_canvas_set_center_scroll_region(), eel_canvas_set_pixels_per_unit(), eel_canvas_set_scroll_region(), eel_canvas_update_now(), eel_canvas_w2c(), eel_canvas_w2c_d(), eel_canvas_window_to_world(), and eel_canvas_world_to_window().
EEL_IS_CANVAS_CLASS
#define EEL_IS_CANVAS_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), EEL_TYPE_CANVAS))
Definition at line 346 of file eel-canvas.h.
EEL_IS_CANVAS_GROUP
#define EEL_IS_CANVAS_GROUP (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), EEL_TYPE_CANVAS_GROUP))
Definition at line 317 of file eel-canvas.h.
Referenced by eel_canvas_item_construct(), eel_canvas_item_i2w(), eel_canvas_item_new(), eel_canvas_item_reparent(), and eel_canvas_item_w2i().
EEL_IS_CANVAS_GROUP_CLASS
#define EEL_IS_CANVAS_GROUP_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), EEL_TYPE_CANVAS_GROUP))
Definition at line 318 of file eel-canvas.h.
EEL_IS_CANVAS_ITEM
#define EEL_IS_CANVAS_ITEM (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), EEL_TYPE_CANVAS_ITEM))
Definition at line 108 of file eel-canvas.h.
Referenced by eel_canvas_item_construct(), eel_canvas_item_get_bounds(), eel_canvas_item_grab(), eel_canvas_item_grab_focus(), eel_canvas_item_hide(), eel_canvas_item_i2w(), eel_canvas_item_lower(), eel_canvas_item_lower_to_bottom(), eel_canvas_item_move(), eel_canvas_item_raise(), eel_canvas_item_raise_to_top(), eel_canvas_item_reparent(), eel_canvas_item_send_behind(), eel_canvas_item_set_valist(), eel_canvas_item_show(), eel_canvas_item_ungrab(), and eel_canvas_item_w2i().
EEL_IS_CANVAS_ITEM_CLASS
#define EEL_IS_CANVAS_ITEM_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), EEL_TYPE_CANVAS_ITEM))
Definition at line 109 of file eel-canvas.h.
EEL_TYPE_CANVAS
#define EEL_TYPE_CANVAS (eel_canvas_get_type ())
Definition at line 342 of file eel-canvas.h.
Referenced by G_DEFINE_TYPE().
EEL_TYPE_CANVAS_GROUP
#define EEL_TYPE_CANVAS_GROUP (eel_canvas_group_get_type ())
Definition at line 314 of file eel-canvas.h.
EEL_TYPE_CANVAS_ITEM
#define EEL_TYPE_CANVAS_ITEM (eel_canvas_item_get_type ())
Definition at line 105 of file eel-canvas.h.
Referenced by G_DEFINE_TYPE_WITH_CODE().
Typedef Documentation
EelCanvas
typedef struct _EelCanvas EelCanvas
Definition at line 66 of file eel-canvas.h.
EelCanvasAccessible
typedef struct _EelCanvasAccessible EelCanvasAccessible
Definition at line 515 of file eel-canvas.h.
EelCanvasAccessibleClass
typedef struct _EelCanvasAccessibleClass EelCanvasAccessibleClass
Definition at line 516 of file eel-canvas.h.
EelCanvasClass
typedef struct _EelCanvasClass EelCanvasClass
Definition at line 67 of file eel-canvas.h.
EelCanvasGroup
typedef struct _EelCanvasGroup EelCanvasGroup
Definition at line 70 of file eel-canvas.h.
EelCanvasGroupClass
typedef struct _EelCanvasGroupClass EelCanvasGroupClass
Definition at line 71 of file eel-canvas.h.
EelCanvasItem
typedef struct _EelCanvasItem EelCanvasItem
Definition at line 68 of file eel-canvas.h.
EelCanvasItemAccessible
typedef struct _EelCanvasItemAccessible EelCanvasItemAccessible
Definition at line 530 of file eel-canvas.h.
EelCanvasItemAccessibleClass
typedef struct _EelCanvasItemAccessibleClass EelCanvasItemAccessibleClass
Definition at line 531 of file eel-canvas.h.
EelCanvasItemClass
typedef struct _EelCanvasItemClass EelCanvasItemClass
Definition at line 69 of file eel-canvas.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EEL_CANVAS_UPDATE_REQUESTED
EEL_CANVAS_UPDATE_DEEP
Definition at line 99 of file eel-canvas.h.
anonymous enum
anonymous enum
Enumerator
EEL_CANVAS_ITEM_REALIZED
EEL_CANVAS_ITEM_MAPPED
EEL_CANVAS_ITEM_ALWAYS_REDRAW
EEL_CANVAS_ITEM_VISIBLE
EEL_CANVAS_ITEM_NEED_UPDATE
EEL_CANVAS_ITEM_NEED_DEEP_UPDATE
Definition at line 88 of file eel-canvas.h.
Function Documentation
eel_canvas_accessible_get_type()
GType eel_canvas_accessible_get_type (void)
Referenced by G_DEFINE_TYPE_WITH_CODE().
eel_canvas_c2w()
void eel_canvas_c2w (EelCanvas * canvas, int cx, int cy, double * wx, double * wy)
eel_canvas_c2w: @canvas: A canvas. @cx: Canvas pixel X coordinate. @cy: Canvas pixel Y coordinate. @wx: X world coordinate (return value). @wy: Y world coordinate (return value).
Converts canvas pixel coordinates to world coordinates.
Definition at line 3538 of file eel-canvas.c.
References EEL_IS_CANVAS, _EelCanvas::pixels_per_unit, _EelCanvas::scroll_x1, _EelCanvas::scroll_y1, _EelCanvas::zoom_xofs, and _EelCanvas::zoom_yofs.
Referenced by caja_icon_container_get_first_visible_icon(), and eel_canvas_set_scroll_region().
eel_canvas_get_item_at()
EelCanvasItem * eel_canvas_get_item_at (EelCanvas * canvas, double x, double y)
eel_canvas_get_item_at: @canvas: A canvas. @x: X position in world coordinates. @y: Y position in world coordinates.
Looks for the item that is under the specified position, which must be specified in world coordinates.
Return value: The sought item, or NULL if no item is at the specified coordinates.
Definition at line 3393 of file eel-canvas.c.
References _EelCanvas::close_enough, dist, eel_canvas_w2c(), EEL_IS_CANVAS, item, NULL, _EelCanvas::pixels_per_unit, and _EelCanvas::root.
eel_canvas_get_scroll_offsets()
void eel_canvas_get_scroll_offsets (EelCanvas * canvas, int * cx, int * cy)
eel_canvas_get_scroll_offsets: @canvas: A canvas. @cx: Horizontal scrolling offset (return value). @cy: Vertical scrolling offset (return value).
Queries the scrolling offsets of a canvas. The values are returned in canvas pixel units.
Definition at line 3344 of file eel-canvas.c.
References EEL_IS_CANVAS.
eel_canvas_get_scroll_region()
void eel_canvas_get_scroll_region (EelCanvas * canvas, double * x1, double * y1, double * x2, double * y2)
eel_canvas_get_scroll_region: @canvas: A canvas. @x1: Leftmost limit of the scrolling region (return value). @y1: Upper limit of the scrolling region (return value). @x2: Rightmost limit of the scrolling region (return value). @y2: Lower limit of the scrolling region (return value).
Queries the scrolling region of a canvas.
Definition at line 3187 of file eel-canvas.c.
References EEL_IS_CANVAS, _EelCanvas::scroll_x1, _EelCanvas::scroll_x2, _EelCanvas::scroll_y1, and _EelCanvas::scroll_y2.
eel_canvas_get_type()
GType eel_canvas_get_type (void)
eel_canvas_get_type:
Registers the &EelCanvas class if necessary, and returns the type ID associated to it.
Return value: The type ID of the &EelCanvas class.
Definition at line 1839 of file eel-canvas.c.
References NULL.
Referenced by eel_canvas_new().
eel_canvas_group_get_type()
GType eel_canvas_group_get_type (void)
eel_canvas_group_get_type:
Registers the &EelCanvasGroup class if necessary, and returns the type ID associated to it.
Return value: The type ID of the &EelCanvasGroup class.
Definition at line 1243 of file eel-canvas.c.
References eel_canvas_item_get_type(), and NULL.
eel_canvas_item_accessible_get_type()
GType eel_canvas_item_accessible_get_type (void)
Referenced by G_DEFINE_TYPE_WITH_CODE().
eel_canvas_item_construct()
void eel_canvas_item_construct (EelCanvasItem * item, EelCanvasGroup * parent, const gchar * first_arg_name, va_list args)
eel_canvas_item_construct: @item: An unconstructed canvas item. @parent: The parent group for the item. @first_arg_name: The name of the first argument for configuring the item. @args: The list of arguments used to configure the item.
Constructs a canvas item; meant for use only by item implementations.
Definition at line 280 of file eel-canvas.c.
References EEL_CANVAS_ITEM, EEL_IS_CANVAS_GROUP, EEL_IS_CANVAS_ITEM, and item.
Referenced by eel_canvas_item_new().
eel_canvas_item_destroy()
void eel_canvas_item_destroy (EelCanvasItem * item)
Definition at line 360 of file eel-canvas.c.
References item, and NULL.
eel_canvas_item_get_bounds()
void eel_canvas_item_get_bounds (EelCanvasItem * item, double * x1, double * y1, double * x2, double * y2)
eel_canvas_item_get_bounds: @item: A canvas item. @x1: Leftmost edge of the bounding box (return value). @y1: Upper edge of the bounding box (return value). @x2: Rightmost edge of the bounding box (return value). @y2: Lower edge of the bounding box (return value).
Queries the bounding box of a canvas item. The bounds are returned in the coordinate system of the item's parent.
Definition at line 1117 of file eel-canvas.c.
References EEL_CANVAS_ITEM_GET_CLASS, EEL_IS_CANVAS_ITEM, and item.
Referenced by caja_icon_container_get_first_visible_icon().
eel_canvas_item_get_type()
GType eel_canvas_item_get_type (void)
eel_canvas_item_get_type:
Registers the &EelCanvasItem class if necessary, and returns the type ID associated to it.
Return value: The type ID of the &EelCanvasItem class.
Definition at line 124 of file eel-canvas.c.
References NULL.
Referenced by eel_canvas_group_get_type(), eel_canvas_item_new(), and eel_canvas_re_get_type().
eel_canvas_item_grab()
GdkGrabStatus eel_canvas_item_grab (EelCanvasItem * item, GdkEventMask event_mask, GdkCursor * cursor, const GdkEvent * event)
eel_canvas_item_grab: @item: A canvas item. @event_mask: Mask of events that will be sent to this item. @cursor: If non-NULL, the cursor that will be used while the grab is active. @event: The event, triggering the grab, if any.
Specifies that all events that match the specified event mask should be sent to the specified item, and also grabs the seat by calling gdk_seat_grab(). If @cursor is not NULL, then that cursor is used while the grab is active.
Return value: If an item was already grabbed, it returns GDK_GRAB_ALREADY_GRABBED. If the specified item was hidden by calling eel_canvas_item_hide(), then it returns GDK_GRAB_NOT_VIEWABLE. Else, it returns the result of calling gdk_seat_grab().
Definition at line 886 of file eel-canvas.c.
References EEL_CANVAS_ITEM_MAPPED, EEL_IS_CANVAS_ITEM, FALSE, item, and NULL.
eel_canvas_item_grab_focus()
void eel_canvas_item_grab_focus (EelCanvasItem * item)
eel_canvas_item_grab_focus: @item: A canvas item.
Makes the specified item take the keyboard focus, so all keyboard events will be sent to it. If the canvas widget itself did not have the focus, it grabs it as well.
Definition at line 1071 of file eel-canvas.c.
References EEL_IS_CANVAS_ITEM, FALSE, item, and TRUE.
eel_canvas_item_hide()
void eel_canvas_item_hide (EelCanvasItem * item)
eel_canvas_item_hide: @item: A canvas item.
Hides a canvas item. If the item was already hidden, then no action is taken.
Definition at line 839 of file eel-canvas.c.
References EEL_CANVAS_ITEM_GET_CLASS, EEL_CANVAS_ITEM_MAPPED, EEL_CANVAS_ITEM_VISIBLE, EEL_IS_CANVAS_ITEM, and item.
eel_canvas_item_i2w()
void eel_canvas_item_i2w (EelCanvasItem * item, double * x, double * y)
eel_canvas_item_i2w: @item: A canvas item. @x: X coordinate to convert (input/output value). @y: Y coordinate to convert (input/output value).
Converts a coordinate pair from item-relative coordinates to world coordinates.
Definition at line 991 of file eel-canvas.c.
References EEL_CANVAS_GROUP, EEL_IS_CANVAS_GROUP, EEL_IS_CANVAS_ITEM, item, and NULL.
Referenced by caja_icon_canvas_item_get_icon_rectangle(), and caja_icon_canvas_item_get_text_rectangle().
eel_canvas_item_lower()
void eel_canvas_item_lower (EelCanvasItem * item, int positions)
eel_canvas_item_lower: @item: A canvas item. @positions: Number of steps to lower the item.
Lowers the item in its parent's stack by the specified number of positions. If the number of positions is greater than the distance to the bottom of the stack, then the item is put at the bottom.
Definition at line 664 of file eel-canvas.c.
References EEL_CANVAS_GROUP, EEL_IS_CANVAS_ITEM, item, _EelCanvasGroup::item_list, and NULL.
Referenced by eel_canvas_item_send_behind().
eel_canvas_item_lower_to_bottom()
void eel_canvas_item_lower_to_bottom (EelCanvasItem * item)
eel_canvas_item_lower_to_bottom: @item: A canvas item.
Lowers an item to the bottom of its parent's stack.
Definition at line 725 of file eel-canvas.c.
References EEL_CANVAS_GROUP, EEL_IS_CANVAS_ITEM, item, _EelCanvasGroup::item_list, and NULL.
eel_canvas_item_move()
void eel_canvas_item_move (EelCanvasItem * item, double dx, double dy)
eel_canvas_item_move: @item: A canvas item. @dx: Horizontal offset. @dy: Vertical offset.
Moves a canvas item by creating an affine transformation matrix for translation by using the specified values. This happens in item local coordinate system, so if you have nontrivial transform, it most probably does not do, what you want.
Definition at line 523 of file eel-canvas.c.
References EEL_CANVAS_ITEM_GET_CLASS, EEL_CANVAS_ITEM_MAPPED, EEL_CANVAS_ITEM_NEED_DEEP_UPDATE, eel_canvas_item_request_update(), EEL_IS_CANVAS_ITEM, item, NULL, and TRUE.
eel_canvas_item_new()
EelCanvasItem * eel_canvas_item_new (EelCanvasGroup * parent, GType type, const gchar * first_arg_name, ...)
eel_canvas_item_new: @parent: The parent group for the new item. @type: The object type of the item. @first_arg_name: A list of object argument name/value pairs, NULL-terminated, used to configure the item. For example, "fill_color", "black", "width_units", 5.0, NULL. @Varargs:
Creates a new canvas item with @parent as its parent group. The item is created at the top of its parent's stack, and starts up as visible. The item is of the specified @type, for example, it can be eel_canvas_rect_get_type(). The list of object arguments/value pairs is used to configure the item.
Return value: The newly-created item.
Definition at line 178 of file eel-canvas.c.
References EEL_CANVAS_ITEM, eel_canvas_item_construct(), eel_canvas_item_get_type(), EEL_IS_CANVAS_GROUP, item, and NULL.
Referenced by caja_icon_container_add().
eel_canvas_item_raise()
void eel_canvas_item_raise (EelCanvasItem * item, int positions)
eel_canvas_item_raise: @item: A canvas item. @positions: Number of steps to raise the item.
Raises the item in its parent's stack by the specified number of positions. If the number of positions is greater than the distance to the top of the stack, then the item is put at the top.
Definition at line 627 of file eel-canvas.c.
References EEL_CANVAS_GROUP, EEL_IS_CANVAS_ITEM, item, _EelCanvasGroup::item_list, _EelCanvasGroup::item_list_end, and NULL.
Referenced by eel_canvas_item_send_behind().
eel_canvas_item_raise_to_top()
void eel_canvas_item_raise_to_top (EelCanvasItem * item)
eel_canvas_item_raise_to_top: @item: A canvas item.
Raises an item to the top of its parent's stack.
Definition at line 698 of file eel-canvas.c.
References EEL_CANVAS_GROUP, EEL_IS_CANVAS_ITEM, item, _EelCanvasGroup::item_list, _EelCanvasGroup::item_list_end, and NULL.
Referenced by eel_canvas_item_send_behind().
eel_canvas_item_reparent()
void eel_canvas_item_reparent (EelCanvasItem * item, EelCanvasGroup * new_group)
eel_canvas_item_reparent: @item: A canvas item. @new_group: A canvas group.
Changes the parent of the specified item to be the new group. The item keeps its group-relative coordinates as for its old parent, so the item may change its absolute position within the canvas.
Definition at line 1031 of file eel-canvas.c.
References EEL_CANVAS_GROUP, EEL_CANVAS_ITEM, eel_canvas_item_request_redraw(), EEL_IS_CANVAS_GROUP, EEL_IS_CANVAS_ITEM, and item.
eel_canvas_item_request_redraw()
void eel_canvas_item_request_redraw (EelCanvasItem * item)
eel_canvas_item_request_update @item: A canvas item.
Convenience function that informs a canvas that the specified item needs to be repainted. To be used by item implementations
Definition at line 1185 of file eel-canvas.c.
References EEL_CANVAS_ITEM_MAPPED, eel_canvas_request_redraw(), and item.
Referenced by eel_canvas_item_reparent().
eel_canvas_item_request_update()
void eel_canvas_item_request_update (EelCanvasItem * item)
eel_canvas_item_request_update @item: A canvas item.
To be used only by item implementations. Requests that the canvas queue an update for the specified item.
Definition at line 1153 of file eel-canvas.c.
References EEL_CANVAS_ITEM_NEED_UPDATE, eel_canvas_item_request_update(), item, and NULL.
Referenced by caja_icon_canvas_item_set_embedded_text(), caja_icon_canvas_item_set_embedded_text_rect(), caja_icon_canvas_item_set_emblems(), caja_icon_canvas_item_set_entire_text(), caja_icon_canvas_item_set_image(), caja_icon_canvas_item_set_renaming(), caja_icon_canvas_item_set_show_stretch_handles(), eel_canvas_item_move(), and eel_canvas_item_request_update().
eel_canvas_item_send_behind()
void eel_canvas_item_send_behind (EelCanvasItem * item, EelCanvasItem * behind_item)
eel_canvas_item_send_behind: @item: A canvas item. @behind_item: The canvas item to put item behind, or NULL
Moves item to a in the position in the stacking order so that it is placed immediately below behind_item, or at the top if behind_item is NULL.
Definition at line 755 of file eel-canvas.c.
References EEL_CANVAS_GROUP, eel_canvas_item_lower(), eel_canvas_item_raise(), eel_canvas_item_raise_to_top(), EEL_IS_CANVAS_ITEM, item, NULL, and _EelCanvasItem::parent.
Referenced by caja_icon_container_add().
eel_canvas_item_set()
void eel_canvas_item_set (EelCanvasItem * item, const gchar * first_arg_name, ...)
eel_canvas_item_set: @item: A canvas item. @first_arg_name: The list of object argument name/value pairs used to configure the item. @Varargs:
Configures a canvas item. The arguments in the item are set to the specified values, and the item is repainted as appropriate.
Definition at line 483 of file eel-canvas.c.
References eel_canvas_item_set_valist(), and item.
Referenced by caja_icon_container_set_highlighted_for_clipboard(), and caja_icon_container_update_icon().
eel_canvas_item_set_valist()
void eel_canvas_item_set_valist (EelCanvasItem * item, const gchar * first_arg_name, va_list args)
eel_canvas_item_set_valist: @item: A canvas item. @first_arg_name: The name of the first argument used to configure the item. @args: The list of object argument name/value pairs used to configure the item.
Configures a canvas item. The arguments in the item are set to the specified values, and the item is repainted as appropriate.
Definition at line 502 of file eel-canvas.c.
References EEL_IS_CANVAS_ITEM, item, and TRUE.
Referenced by eel_canvas_item_set().
eel_canvas_item_show()
void eel_canvas_item_show (EelCanvasItem * item)
eel_canvas_item_show: @item: A canvas item.
Shows a canvas item. If the item was already shown, then no action is taken.
Definition at line 802 of file eel-canvas.c.
References EEL_CANVAS_ITEM_GET_CLASS, EEL_CANVAS_ITEM_MAPPED, EEL_CANVAS_ITEM_REALIZED, EEL_CANVAS_ITEM_VISIBLE, EEL_IS_CANVAS_ITEM, item, and NULL.
eel_canvas_item_ungrab()
void eel_canvas_item_ungrab (EelCanvasItem * item)
eel_canvas_item_ungrab: @item: A canvas item that holds a grab.
Ungrabs the item, which must have been grabbed in the canvas, and ungrabs the seat.
Definition at line 935 of file eel-canvas.c.
References EEL_IS_CANVAS_ITEM, item, and NULL.
eel_canvas_item_w2i()
void eel_canvas_item_w2i (EelCanvasItem * item, double * x, double * y)
eel_canvas_item_w2i: @item: A canvas item. @x: X coordinate to convert (input/output value). @y: Y coordinate to convert (input/output value).
Converts a coordinate pair from world coordinates to item-relative coordinates.
Definition at line 962 of file eel-canvas.c.
References EEL_CANVAS_GROUP, EEL_IS_CANVAS_GROUP, EEL_IS_CANVAS_ITEM, item, and NULL.
eel_canvas_new()
GtkWidget * eel_canvas_new (void)
eel_canvas_new: @void:
Creates a new empty canvas. If you wish to use the &EelCanvasImage item inside this canvas, then you must push the gdk_imlib visual and colormap before calling this function, and they can be popped afterwards.
Return value: A newly-created canvas.
Definition at line 2179 of file eel-canvas.c.
References eel_canvas_get_type(), and NULL.
eel_canvas_request_redraw()
void eel_canvas_request_redraw (EelCanvas * canvas, int x1, int y1, int x2, int y2)
eel_canvas_request_redraw: @canvas: A canvas. @x1: Leftmost coordinate of the rectangle to be redrawn. @y1: Upper coordinate of the rectangle to be redrawn. @x2: Rightmost coordinate of the rectangle to be redrawn, plus 1. @y2: Lower coordinate of the rectangle to be redrawn, plus 1.
Convenience function that informs a canvas that the specified rectangle needs to be repainted. The rectangle includes @x1 and @y1, but not @x2 and @y2. To be used only by item implementations.
Definition at line 3437 of file eel-canvas.c.
References EEL_IS_CANVAS, and FALSE.
Referenced by caja_icon_canvas_item_update_bounds(), and eel_canvas_item_request_redraw().
eel_canvas_root()
EelCanvasGroup * eel_canvas_root (EelCanvas * canvas)
eel_canvas_root: @canvas: A canvas.
Queries the root group of a canvas.
Return value: The root group of the specified canvas.
Definition at line 3110 of file eel-canvas.c.
References EEL_CANVAS_GROUP, EEL_IS_CANVAS, NULL, and _EelCanvas::root.
eel_canvas_scroll_to()
void eel_canvas_scroll_to (EelCanvas * canvas, int cx, int cy)
eel_canvas_scroll_to: @canvas: A canvas. @cx: Horizontal scrolling offset in canvas pixel units. @cy: Vertical scrolling offset in canvas pixel units.
Makes a canvas scroll to the specified offsets, given in canvas pixel units. The canvas will adjust the view so that it is not outside the scrolling region. This function is typically not used, as it is better to hook scrollbars to the canvas layout's scrolling adjusments.
Definition at line 3327 of file eel-canvas.c.
References EEL_IS_CANVAS.
eel_canvas_set_center_scroll_region()
void eel_canvas_set_center_scroll_region (EelCanvas * canvas, gboolean center_scroll_region)
Definition at line 3205 of file eel-canvas.c.
References _EelCanvas::center_scroll_region, EEL_IS_CANVAS, and _EelCanvas::layout.
eel_canvas_set_pixels_per_unit()
void eel_canvas_set_pixels_per_unit (EelCanvas * canvas, double n)
eel_canvas_set_pixels_per_unit: @canvas: A canvas.
: The number of pixels that correspond to one canvas unit.
Sets the zooming factor of a canvas by specifying the number of pixels that correspond to one canvas unit.
Definition at line 3231 of file eel-canvas.c.
References EEL_CANVAS_EPSILON, EEL_CANVAS_ITEM_NEED_DEEP_UPDATE, EEL_IS_CANVAS, _EelCanvasItem::flags, _EelCanvas::need_repick, NULL, _EelCanvas::pixels_per_unit, _EelCanvas::root, _EelCanvas::scroll_x1, _EelCanvas::scroll_y1, TRUE, _EelCanvas::zoom_xofs, and _EelCanvas::zoom_yofs.
Referenced by caja_icon_container_set_zoom_level().
eel_canvas_set_scroll_region()
void eel_canvas_set_scroll_region (EelCanvas * canvas, double x1, double y1, double x2, double y2)
eel_canvas_set_scroll_region: @canvas: A canvas. @x1: Leftmost limit of the scrolling region. @y1: Upper limit of the scrolling region. @x2: Rightmost limit of the scrolling region. @y2: Lower limit of the scrolling region.
Sets the scrolling region of a canvas to the specified rectangle. The canvas will then be able to scroll only within this region. The view of the canvas is adjusted as appropriate to display as much of the new region as possible.
Definition at line 3130 of file eel-canvas.c.
References eel_canvas_c2w(), EEL_CANVAS_ITEM_NEED_DEEP_UPDATE, eel_canvas_w2c(), EEL_IS_CANVAS, _EelCanvasItem::flags, _EelCanvas::need_repick, _EelCanvas::root, _EelCanvas::scroll_x1, _EelCanvas::scroll_x2, _EelCanvas::scroll_y1, _EelCanvas::scroll_y2, TRUE, _EelCanvas::zoom_xofs, and _EelCanvas::zoom_yofs.
Referenced by caja_icon_container_update_scroll_region().
eel_canvas_update_now()
void eel_canvas_update_now (EelCanvas * canvas)
eel_canvas_update_now: @canvas: A canvas.
Forces an immediate update and redraw of a canvas. If the canvas does not have any pending update or redraw requests, then no action is taken. This is typically only used by applications that need explicit control of when the display is updated, like games. It is not needed by normal applications.
Definition at line 3370 of file eel-canvas.c.
References EEL_IS_CANVAS, _EelCanvas::need_redraw, and _EelCanvas::need_update.
eel_canvas_w2c()
void eel_canvas_w2c (EelCanvas * canvas, double wx, double wy, int * cx, int * cy)
eel_canvas_w2c: @canvas: A canvas. @wx: World X coordinate. @wy: World Y coordinate. @cx: X pixel coordinate (return value). @cy: Y pixel coordinate (return value).
Converts world coordinates into canvas pixel coordinates.
Definition at line 3466 of file eel-canvas.c.
References EEL_IS_CANVAS, _EelCanvas::pixels_per_unit, _EelCanvas::scroll_x1, _EelCanvas::scroll_y1, _EelCanvas::zoom_xofs, and _EelCanvas::zoom_yofs.
Referenced by caja_icon_canvas_item_hit_test_stretch_handles(), caja_icon_container_start_renaming_selected_item(), eel_canvas_get_item_at(), and eel_canvas_set_scroll_region().
eel_canvas_w2c_d()
void eel_canvas_w2c_d (EelCanvas * canvas, double wx, double wy, double * cx, double * cy)
eel_canvas_w2c_d: @canvas: A canvas. @wx: World X coordinate. @wy: World Y coordinate. @cx: X pixel coordinate (return value). @cy: Y pixel coordinate (return value).
Converts world coordinates into canvas pixel coordinates. This version produces coordinates in floating point coordinates, for greater precision.
Definition at line 3513 of file eel-canvas.c.
References EEL_IS_CANVAS, _EelCanvas::pixels_per_unit, _EelCanvas::scroll_x1, _EelCanvas::scroll_y1, _EelCanvas::zoom_xofs, and _EelCanvas::zoom_yofs.
Referenced by eel_canvas_w2c_rect_d().
eel_canvas_w2c_rect_d()
void eel_canvas_w2c_rect_d (EelCanvas * canvas, double * x1, double * y1, double * x2, double * y2)
eel_canvas_w2c: @canvas: A canvas. @world: rectangle in world coordinates. @canvas: rectangle in canvase coordinates.
Converts rectangles in world coordinates into canvas pixel coordinates.
Definition at line 3489 of file eel-canvas.c.
References eel_canvas_w2c_d().
eel_canvas_window_to_world()
void eel_canvas_window_to_world (EelCanvas * canvas, double winx, double winy, double * worldx, double * worldy)
eel_canvas_window_to_world: @canvas: A canvas. @winx: Window-relative X coordinate. @winy: Window-relative Y coordinate. @worldx: X world coordinate (return value). @worldy: Y world coordinate (return value).
Converts window-relative coordinates into world coordinates. You can use this when you need to convert mouse coordinates into world coordinates, for example. Window coordinates are really the same as canvas coordinates now, but this function is here for backwards compatibility reasons.
Definition at line 3567 of file eel-canvas.c.
References EEL_IS_CANVAS, _EelCanvas::pixels_per_unit, _EelCanvas::scroll_x1, _EelCanvas::scroll_y1, _EelCanvas::zoom_xofs, and _EelCanvas::zoom_yofs.
Referenced by caja_icon_container_widget_to_file_operation_position().
eel_canvas_world_to_window()
void eel_canvas_world_to_window (EelCanvas * canvas, double worldx, double worldy, double * winx, double * winy)
eel_canvas_world_to_window: @canvas: A canvas. @worldx: World X coordinate. @worldy: World Y coordinate. @winx: X window-relative coordinate. @winy: Y window-relative coordinate.
Converts world coordinates into window-relative coordinates. Window coordinates are really the same as canvas coordinates now, but this function is here for backwards compatibility reasons.
Definition at line 3594 of file eel-canvas.c.
References EEL_IS_CANVAS, _EelCanvas::pixels_per_unit, _EelCanvas::scroll_x1, _EelCanvas::scroll_y1, _EelCanvas::zoom_xofs, and _EelCanvas::zoom_yofs.
Referenced by caja_icon_canvas_item_get_drag_surface().