MATE Desktop Environment: eel-labeled-image.c File Reference
eel-labeled-image.c File Reference
#include <config.h>
#include "eel-labeled-image.h"
#include "eel-art-extensions.h"
#include "eel-art-gtk-extensions.h"
#include "eel-gtk-container.h"
#include "eel-gtk-extensions.h"
#include "eel-accessibility.h"
#include <gtk/gtk.h>
#include <gtk/gtk-a11y.h>
#include <gdk/gdkkeysyms.h>
#include <atk/atkimage.h>
Macros
#define DEFAULT_SPACING 0
#define DEFAULT_X_PADDING 0
#define DEFAULT_Y_PADDING 0
#define DEFAULT_X_ALIGNMENT 0.5
#define DEFAULT_Y_ALIGNMENT 0.5
#define DEFINE_LABELLED_IMAGE_BUTTON_TYPE(TN, t_n, TP, T_P, ATP, A_T_P)
Typedefs
typedef GtkContainerAccessible EelLabeledImageAccessible
typedef GtkContainerAccessibleClass EelLabeledImageAccessibleClass
Enumerations
enum { ACTIVATE , LAST_SIGNAL }
enum {
PROP_0 , PROP_FILL , PROP_LABEL , PROP_LABEL_POSITION ,
PROP_PIXBUF , PROP_SHOW_IMAGE , PROP_SHOW_LABEL , PROP_SPACING ,
PROP_X_ALIGNMENT , PROP_X_PADDING , PROP_Y_ALIGNMENT , PROP_Y_PADDING
}
Functions
EelIRect eel_labeled_image_get_image_bounds (const EelLabeledImage *labeled_image)
EelIRect eel_labeled_image_get_label_bounds (const EelLabeledImage *labeled_image)
GtkWidget * eel_labeled_image_new (const char *text, GdkPixbuf *pixbuf)
GtkWidget * eel_labeled_image_new_from_file_name (const char *text, const char *pixbuf_file_name)
void eel_labeled_image_set_label_position (EelLabeledImage *labeled_image, GtkPositionType label_position)
GtkPositionType eel_labeled_image_get_label_position (const EelLabeledImage *labeled_image)
void eel_labeled_image_set_show_label (EelLabeledImage *labeled_image, gboolean show_label)
gboolean eel_labeled_image_get_show_label (const EelLabeledImage *labeled_image)
void eel_labeled_image_set_show_image (EelLabeledImage *labeled_image, gboolean show_image)
gboolean eel_labeled_image_get_show_image (const EelLabeledImage *labeled_image)
void eel_labeled_image_set_fixed_image_height (EelLabeledImage *labeled_image, int new_height)
void eel_labeled_image_set_selected (EelLabeledImage *labeled_image, gboolean selected)
gboolean eel_labeled_image_get_selected (EelLabeledImage *labeled_image)
void eel_labeled_image_set_spacing (EelLabeledImage *labeled_image, guint spacing)
guint eel_labeled_image_get_spacing (const EelLabeledImage *labeled_image)
void eel_labeled_image_set_x_padding (EelLabeledImage *labeled_image, int x_padding)
int eel_labeled_image_get_x_padding (const EelLabeledImage *labeled_image)
void eel_labeled_image_set_y_padding (EelLabeledImage *labeled_image, int y_padding)
int eel_labeled_image_get_y_padding (const EelLabeledImage *labeled_image)
void eel_labeled_image_set_x_alignment (EelLabeledImage *labeled_image, float x_alignment)
float eel_labeled_image_get_x_alignment (const EelLabeledImage *labeled_image)
void eel_labeled_image_set_y_alignment (EelLabeledImage *labeled_image, float y_alignment)
float eel_labeled_image_get_y_alignment (const EelLabeledImage *labeled_image)
void eel_labeled_image_set_fill (EelLabeledImage *labeled_image, gboolean fill)
gboolean eel_labeled_image_get_fill (const EelLabeledImage *labeled_image)
GtkWidget * eel_labeled_image_button_new (const char *text, GdkPixbuf *pixbuf)
GtkWidget * eel_labeled_image_button_new_from_file_name (const char *text, const char *pixbuf_file_name)
GtkWidget * eel_labeled_image_toggle_button_new (const char *text, GdkPixbuf *pixbuf)
GtkWidget * eel_labeled_image_toggle_button_new_from_file_name (const char *text, const char *pixbuf_file_name)
GtkWidget * eel_labeled_image_radio_button_new (const char *text, GdkPixbuf *pixbuf)
GtkWidget * eel_labeled_image_radio_button_new_from_file_name (const char *text, const char *pixbuf_file_name)
GtkWidget * eel_labeled_image_check_button_new (const char *text, GdkPixbuf *pixbuf)
GtkWidget * eel_labeled_image_check_button_new_from_file_name (const char *text, const char *pixbuf_file_name)
void eel_labeled_image_set_pixbuf (EelLabeledImage *labeled_image, GdkPixbuf *pixbuf)
void eel_labeled_image_set_pixbuf_from_file_name (EelLabeledImage *labeled_image, const char *pixbuf_file_name)
void eel_labeled_image_set_text (EelLabeledImage *labeled_image, const char *text)
char * eel_labeled_image_get_text (const EelLabeledImage *labeled_image)
void eel_labeled_image_set_can_focus (EelLabeledImage *labeled_image, gboolean can_focus)
G_DEFINE_TYPE_WITH_CODE (EelLabeledImageAccessible, eel_labeled_image_accessible, GTK_TYPE_CONTAINER_ACCESSIBLE, G_IMPLEMENT_INTERFACE(ATK_TYPE_IMAGE, eel_labeled_image_accessible_image_interface_init))
Macro Definition Documentation
DEFAULT_SPACING
#define DEFAULT_SPACING 0
Definition at line 38 of file eel-labeled-image.c.
DEFAULT_X_ALIGNMENT
#define DEFAULT_X_ALIGNMENT 0.5
Definition at line 41 of file eel-labeled-image.c.
DEFAULT_X_PADDING
#define DEFAULT_X_PADDING 0
Definition at line 39 of file eel-labeled-image.c.
DEFAULT_Y_ALIGNMENT
#define DEFAULT_Y_ALIGNMENT 0.5
Definition at line 42 of file eel-labeled-image.c.
DEFAULT_Y_PADDING
#define DEFAULT_Y_PADDING 0
Definition at line 40 of file eel-labeled-image.c.
DEFINE_LABELLED_IMAGE_BUTTON_TYPE
#define DEFINE_LABELLED_IMAGE_BUTTON_TYPE (TN, t_n, TP, T_P, ATP, A_T_P)
Value:
typedef TP TN;                                                              \
typedef TP##Class TN##Class;                                                \
typedef ATP TN##Accessible;                                                 \
typedef ATP##Class TN##AccessibleClass;                                     \
G_DEFINE_TYPE (TN, t_n, T_P)                                                \
G_DEFINE_TYPE_WITH_CODE (TN##Accessible, t_n##_accessible, A_T_P,           \
                         G_IMPLEMENT_INTERFACE (ATK_TYPE_IMAGE,             \
                                                eel_labeled_image_accessible_image_interface_init)) \
static void t_n##_class_init(TN##Class *klass)                              \
{                                                                           \
    gtk_widget_class_set_accessible_type (GTK_WIDGET_CLASS (klass),         \
                                          t_n##_accessible_get_type ());    \
}                                                                           \
static void t_n##_init (TN *obj)                                            \
{                                                                           \
}                                                                           \
static void t_n##_accessible_class_init(TN##AccessibleClass *klass)         \
{                                                                           \
    AtkObjectClass *atk_class = ATK_OBJECT_CLASS (klass);                   \
    atk_class->get_name = eel_labeled_image_accessible_get_name;            \
}                                                                           \
static void t_n##_accessible_init (TN##Accessible *obj)                     \
{                                                                           \
}
Definition at line 2281 of file eel-labeled-image.c.
Typedef Documentation
EelLabeledImageAccessible
typedef GtkContainerAccessible EelLabeledImageAccessible
Definition at line 2244 of file eel-labeled-image.c.
EelLabeledImageAccessibleClass
typedef GtkContainerAccessibleClass EelLabeledImageAccessibleClass
Definition at line 2245 of file eel-labeled-image.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_FILL
PROP_LABEL
PROP_LABEL_POSITION
PROP_PIXBUF
PROP_SHOW_IMAGE
PROP_SHOW_LABEL
PROP_SPACING
PROP_X_ALIGNMENT
PROP_X_PADDING
PROP_Y_ALIGNMENT
PROP_Y_PADDING
Definition at line 52 of file eel-labeled-image.c.
anonymous enum
anonymous enum
Enumerator
ACTIVATE
LAST_SIGNAL
Definition at line 45 of file eel-labeled-image.c.
Function Documentation
eel_labeled_image_button_new()
GtkWidget * eel_labeled_image_button_new (const char * text, GdkPixbuf * pixbuf)
eel_labeled_image_button_new: @text: Text to use for label or NULL. @pixbuf: Pixbuf to use for image or NULL.
Create a stock GtkButton with a EelLabeledImage child.
Definition at line 1829 of file eel-labeled-image.c.
References eel_labeled_image_new(), and NULL.
eel_labeled_image_button_new_from_file_name()
GtkWidget * eel_labeled_image_button_new_from_file_name (const char * text, const char * pixbuf_file_name)
eel_labeled_image_button_new_from_file_name: @text: Text to use for label or NULL. @pixbuf_file_name: Name of pixbuf to use for image. Cannot be NULL.
Create a stock GtkToggleButton with a EelLabeledImage child.
Definition at line 1853 of file eel-labeled-image.c.
References eel_labeled_image_new_from_file_name(), and NULL.
eel_labeled_image_check_button_new()
GtkWidget * eel_labeled_image_check_button_new (const char * text, GdkPixbuf * pixbuf)
eel_labeled_image_check_button_new: @text: Text to use for label or NULL. @pixbuf: Pixbuf to use for image or NULL.
Create a stock GtkCheckButton with a EelLabeledImage child.
Definition at line 2027 of file eel-labeled-image.c.
References eel_labeled_image_new(), and NULL.
Referenced by main().
eel_labeled_image_check_button_new_from_file_name()
GtkWidget * eel_labeled_image_check_button_new_from_file_name (const char * text, const char * pixbuf_file_name)
eel_labeled_image_check_button_new_from_file_name: @text: Text to use for label or NULL. @pixbuf_file_name: Name of pixbuf to use for image. Cannot be NULL.
Create a stock GtkCheckButton with a EelLabeledImage child.
Definition at line 2060 of file eel-labeled-image.c.
References eel_labeled_image_new_from_file_name(), and NULL.
eel_labeled_image_get_fill()
gboolean eel_labeled_image_get_fill (const EelLabeledImage * labeled_image)
eel_labeled_image_get_fill: @labeled_image: A EelLabeledImage.
Retruns a boolean value indicating whether the internal widgets fill all the available allocation.
Definition at line 1798 of file eel-labeled-image.c.
References EelLabeledImage::details, and EEL_IS_LABELED_IMAGE.
eel_labeled_image_get_image_bounds()
EelIRect eel_labeled_image_get_image_bounds (const EelLabeledImage * labeled_image)
Definition at line 791 of file eel-labeled-image.c.
References EelLabeledImage::details, eel_dimensions_are_empty(), eel_irect_empty, eel_irect_get_height(), eel_irect_get_width(), EEL_IS_LABELED_IMAGE, EelDimensions::height, int(), NULL, EelDimensions::width, EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
eel_labeled_image_get_label_bounds()
EelIRect eel_labeled_image_get_label_bounds (const EelLabeledImage * labeled_image)
Definition at line 964 of file eel-labeled-image.c.
References EelLabeledImage::details, eel_dimensions_are_empty(), eel_irect_empty, eel_irect_get_height(), eel_irect_get_width(), EEL_IS_LABELED_IMAGE, EelDimensions::height, EelDimensions::width, EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
eel_labeled_image_get_label_position()
GtkPositionType eel_labeled_image_get_label_position (const EelLabeledImage * labeled_image)
eel_labeled_image_get_label_postiion: @labeled_image: A EelLabeledImage.
Returns an enumeration indicating the position of the label with respect to the image.
Definition at line 1377 of file eel-labeled-image.c.
References EelLabeledImage::details, and EEL_IS_LABELED_IMAGE.
eel_labeled_image_get_selected()
gboolean eel_labeled_image_get_selected (EelLabeledImage * labeled_image)
eel_labeled_image_get_selected: @labeled_image: A EelLabeledImage.
Returns the selected state of the labeled image.
Definition at line 1550 of file eel-labeled-image.c.
References EEL_IS_LABELED_IMAGE, and FALSE.
eel_labeled_image_get_show_image()
gboolean eel_labeled_image_get_show_image (const EelLabeledImage * labeled_image)
eel_labeled_image_get_show_image: @labeled_image: A EelLabeledImage.
Returns a boolean value indicating whether the internal image is shown.
Definition at line 1483 of file eel-labeled-image.c.
References EelLabeledImage::details, and EEL_IS_LABELED_IMAGE.
eel_labeled_image_get_show_label()
gboolean eel_labeled_image_get_show_label (const EelLabeledImage * labeled_image)
eel_labeled_image_get_show_label: @labeled_image: A EelLabeledImage.
Returns a boolean value indicating whether the internal label is shown.
Definition at line 1430 of file eel-labeled-image.c.
References EelLabeledImage::details, and EEL_IS_LABELED_IMAGE.
eel_labeled_image_get_spacing()
guint eel_labeled_image_get_spacing (const EelLabeledImage * labeled_image)
eel_labeled_image_get_spacing: @labeled_image: A EelLabeledImage.
Returns: The spacing between the label and image.
Definition at line 1592 of file eel-labeled-image.c.
References EelLabeledImage::details, and EEL_IS_LABELED_IMAGE.
eel_labeled_image_get_text()
char * eel_labeled_image_get_text (const EelLabeledImage * labeled_image)
Definition at line 2166 of file eel-labeled-image.c.
References EelLabeledImage::details, EEL_IS_LABELED_IMAGE, and NULL.
eel_labeled_image_get_x_alignment()
float eel_labeled_image_get_x_alignment (const EelLabeledImage * labeled_image)
eel_labeled_image_get_x_alignment: @labeled_image: A EelLabeledImage.
Returns: The horizontal alignment for the LabeledImage's content.
Definition at line 1713 of file eel-labeled-image.c.
References EelLabeledImage::details, and EEL_IS_LABELED_IMAGE.
eel_labeled_image_get_x_padding()
int eel_labeled_image_get_x_padding (const EelLabeledImage * labeled_image)
eel_labeled_image_get_x_padding: @labeled_image: A EelLabeledImage.
Returns: The horizontal padding for the LabeledImage's content.
Definition at line 1632 of file eel-labeled-image.c.
References EelLabeledImage::details, and EEL_IS_LABELED_IMAGE.
eel_labeled_image_get_y_alignment()
float eel_labeled_image_get_y_alignment (const EelLabeledImage * labeled_image)
eel_labeled_image_get_y_alignment: @labeled_image: A EelLabeledImage.
Returns: The vertical alignment for the LabeledImage's content.
Definition at line 1754 of file eel-labeled-image.c.
References EelLabeledImage::details, and EEL_IS_LABELED_IMAGE.
eel_labeled_image_get_y_padding()
int eel_labeled_image_get_y_padding (const EelLabeledImage * labeled_image)
eel_labeled_image_get_x_padding: @labeled_image: A EelLabeledImage.
Returns: The vertical padding for the LabeledImage's content.
Definition at line 1672 of file eel-labeled-image.c.
References EelLabeledImage::details, and EEL_IS_LABELED_IMAGE.
eel_labeled_image_new()
GtkWidget * eel_labeled_image_new (const char * text, GdkPixbuf * pixbuf)
eel_labeled_image_new: @text: Text to use for label or NULL. @pixbuf: Pixbuf to use for image or NULL.
Returns A newly allocated EelLabeledImage. If the &text parameter is not NULL then the LabeledImage will show a label. If the &pixbuf parameter is not NULL then the LabeledImage will show a pixbuf. Either of these can be NULL at creation time.
Later in the lifetime of the widget you can invoke methods that affect the label and/or the image. If at creation time these were NULL, then they will be created as neeeded.
Thus, using this widget in place of EelImage or EelLabel is "free" with only the GtkWidget and function call overhead.
Definition at line 1284 of file eel-labeled-image.c.
References EEL_LABELED_IMAGE, eel_labeled_image_get_type(), eel_labeled_image_set_pixbuf(), eel_labeled_image_set_text(), and NULL.
Referenced by eel_image_table_add_empty_image(), eel_labeled_image_button_new(), eel_labeled_image_check_button_new(), eel_labeled_image_new_from_file_name(), eel_labeled_image_radio_button_new(), and eel_labeled_image_toggle_button_new().
eel_labeled_image_new_from_file_name()
GtkWidget * eel_labeled_image_new_from_file_name (const char * text, const char * pixbuf_file_name)
eel_labeled_image_new_from_file_name: @text: Text to use for label or NULL. @file_name: File name of picture to use for pixbuf. Cannot be NULL.
Returns A newly allocated EelLabeledImage. If the &text parameter is not NULL then the LabeledImage will show a label.
Definition at line 1316 of file eel-labeled-image.c.
References EEL_LABELED_IMAGE, eel_labeled_image_new(), eel_labeled_image_set_pixbuf_from_file_name(), and NULL.
Referenced by eel_labeled_image_button_new_from_file_name(), eel_labeled_image_check_button_new_from_file_name(), eel_labeled_image_radio_button_new_from_file_name(), and eel_labeled_image_toggle_button_new_from_file_name().
eel_labeled_image_radio_button_new()
GtkWidget * eel_labeled_image_radio_button_new (const char * text, GdkPixbuf * pixbuf)
eel_labeled_image_toggle_button_new: @text: Text to use for label or NULL. @pixbuf: Pixbuf to use for image or NULL.
Create a stock GtkToggleButton with a EelLabeledImage child.
Returns: the new radio button.
Definition at line 1930 of file eel-labeled-image.c.
References eel_labeled_image_new(), and NULL.
eel_labeled_image_radio_button_new_from_file_name()
GtkWidget * eel_labeled_image_radio_button_new_from_file_name (const char * text, const char * pixbuf_file_name)
eel_labeled_image_radio_button_new_from_file_name: @text: Text to use for label or NULL. @pixbuf_file_name: Name of pixbuf to use for image. Cannot be NULL.
Create a stock GtkRadioButton with a EelLabeledImage child.
Returns: the new radio button.
Definition at line 1955 of file eel-labeled-image.c.
References eel_labeled_image_new_from_file_name(), and NULL.
eel_labeled_image_set_can_focus()
void eel_labeled_image_set_can_focus (EelLabeledImage * labeled_image, gboolean can_focus)
Definition at line 2179 of file eel-labeled-image.c.
eel_labeled_image_set_fill()
void eel_labeled_image_set_fill (EelLabeledImage * labeled_image, gboolean fill)
eel_labeled_image_set_fill: @labeled_image: A EelLabeledImage. @fill: A boolean value indicating whether the internal image and label widgets should fill all the available allocation.
By default the internal image and label wigets are sized to their natural preferred geometry. You can use the 'fill' attribute of LabeledImage to have the internal widgets fill as much of the LabeledImage allocation as is available.
Definition at line 1773 of file eel-labeled-image.c.
References EelLabeledImage::details, and EEL_IS_LABELED_IMAGE.
eel_labeled_image_set_fixed_image_height()
void eel_labeled_image_set_fixed_image_height (EelLabeledImage * labeled_image, int new_height)
eel_labeled_image_set_fixed_image_height: @labeled_image: A EelLabeledImage. @fixed_image_height: The new fixed image height.
Normally, we measure the height of images, but it's sometimes useful to use a fixed height for all the images. This routine sets the image height to the passed in value
Definition at line 1501 of file eel-labeled-image.c.
References EelLabeledImage::details, and EEL_IS_LABELED_IMAGE.
eel_labeled_image_set_label_position()
void eel_labeled_image_set_label_position (EelLabeledImage * labeled_image, GtkPositionType label_position)
eel_labeled_image_set_label_position: @labeled_image: A EelLabeledImage. @label_position: The position of the label with respect to the image.
Set the position of the label with respect to the image as follows:
GTK_POS_LEFT: [ <label> <image> ]
GTK_POS_RIGHT: [ <image> <label> ]
GTK_POS_TOP: [ <label> ] [ <image> ]
GTK_POS_BOTTOM: [ <image> ] [ <label> ]
Definition at line 1351 of file eel-labeled-image.c.
References EelLabeledImage::details, and EEL_IS_LABELED_IMAGE.
eel_labeled_image_set_pixbuf()
void eel_labeled_image_set_pixbuf (EelLabeledImage * labeled_image, GdkPixbuf * pixbuf)
eel_labeled_image_set_pixbuf: @labaled_image: A EelLabeledImage. @pixbuf: New pixbuf to use or NULL.
Change the pixbuf displayed by the LabeledImage. Note that the widget display is only updated if the show_image attribute is TRUE.
If no internal image widget exists as of yet, a new one will be created.
A NULL &pixbuf will cause the internal image widget (if alive) to be destroyed.
Definition at line 2097 of file eel-labeled-image.c.
References EelLabeledImage::details, EEL_IS_LABELED_IMAGE, and NULL.
Referenced by eel_labeled_image_new().
eel_labeled_image_set_pixbuf_from_file_name()
void eel_labeled_image_set_pixbuf_from_file_name (EelLabeledImage * labeled_image, const char * pixbuf_file_name)
Definition at line 2120 of file eel-labeled-image.c.
References EelLabeledImage::details, and EEL_IS_LABELED_IMAGE.
Referenced by eel_labeled_image_new_from_file_name().
eel_labeled_image_set_selected()
void eel_labeled_image_set_selected (EelLabeledImage * labeled_image, gboolean selected)
eel_labeled_image_set_selected: @labeled_image: A EelLabeledImage. @selected: A boolean value indicating whether the labeled image should be selected.
Selects or deselects the labeled image.
Definition at line 1528 of file eel-labeled-image.c.
References EelLabeledImage::details, EEL_IS_LABELED_IMAGE, and TRUE.
eel_labeled_image_set_show_image()
void eel_labeled_image_set_show_image (EelLabeledImage * labeled_image, gboolean show_image)
eel_labeled_image_set_show_image: @labeled_image: A EelLabeledImage. @show_image: A boolean value indicating whether the image should be shown.
Update the labeled image to either show or hide the internal image widget. This function doesnt have any effect if the LabeledImage doesnt already contain an image.
Definition at line 1447 of file eel-labeled-image.c.
References EelLabeledImage::details, EEL_IS_LABELED_IMAGE, and NULL.
eel_labeled_image_set_show_label()
void eel_labeled_image_set_show_label (EelLabeledImage * labeled_image, gboolean show_label)
eel_labeled_image_set_show_label: @labeled_image: A EelLabeledImage. @show_image: A boolean value indicating whether the label should be shown.
Update the labeled image to either show or hide the internal label widget. This function doesnt have any effect if the LabeledImage doesnt already contain an label.
Definition at line 1394 of file eel-labeled-image.c.
References EelLabeledImage::details, EEL_IS_LABELED_IMAGE, and NULL.
eel_labeled_image_set_spacing()
void eel_labeled_image_set_spacing (EelLabeledImage * labeled_image, guint spacing)
eel_labeled_image_set_spacing: @labeled_image: A EelLabeledImage. @spacing: The new spacing between label and image.
Set the spacing between label and image. This will only affect the geometry of the widget if both a label and image are currently visible.
Definition at line 1568 of file eel-labeled-image.c.
References EelLabeledImage::details, and EEL_IS_LABELED_IMAGE.
eel_labeled_image_set_text()
void eel_labeled_image_set_text (EelLabeledImage * labeled_image, const char * text)
eel_labeled_image_set_text: @labaled_image: A EelLabeledImage. @text: New text (with mnemnonic) to use or NULL.
Change the text displayed by the LabeledImage. Note that the widget display is only updated if the show_label attribute is TRUE.
If no internal label widget exists as of yet, a new one will be created.
A NULL &text will cause the internal label widget (if alive) to be destroyed.
Definition at line 2142 of file eel-labeled-image.c.
References EelLabeledImage::details, EEL_IS_LABELED_IMAGE, and NULL.
Referenced by eel_labeled_image_new().
eel_labeled_image_set_x_alignment()
void eel_labeled_image_set_x_alignment (EelLabeledImage * labeled_image, float x_alignment)
eel_labeled_image_set_x_alignment: @labeled_image: A EelLabeledImage. @x_alignment: The new horizontal alignment.
Set horizontal alignment for the EelLabeledImage's content. The 'content' is the union of the image and label. The alignment attribute work just like that in GtkMisc.
Definition at line 1689 of file eel-labeled-image.c.
References EelLabeledImage::details, EEL_IS_LABELED_IMAGE, MAX, and MIN.
eel_labeled_image_set_x_padding()
void eel_labeled_image_set_x_padding (EelLabeledImage * labeled_image, int x_padding)
eel_labeled_image_set_x_padding: @labeled_image: A EelLabeledImage. @x_padding: The new horizontal padding.
Set horizontal padding for the EelLabeledImage. The padding attribute work just like that in GtkMisc.
Definition at line 1608 of file eel-labeled-image.c.
References EelLabeledImage::details, EEL_IS_LABELED_IMAGE, and MAX.
eel_labeled_image_set_y_alignment()
void eel_labeled_image_set_y_alignment (EelLabeledImage * labeled_image, float y_alignment)
eel_labeled_image_set_y_alignment: @labeled_image: A EelLabeledImage. @y_alignment: The new vertical alignment.
Set vertical alignment for the EelLabeledImage's content. The 'content' is the union of the image and label. The alignment attribute work just like that in GtkMisc.
Definition at line 1730 of file eel-labeled-image.c.
References EelLabeledImage::details, EEL_IS_LABELED_IMAGE, MAX, and MIN.
eel_labeled_image_set_y_padding()
void eel_labeled_image_set_y_padding (EelLabeledImage * labeled_image, int y_padding)
eel_labeled_image_set_y_padding: @labeled_image: A EelLabeledImage. @x_padding: The new vertical padding.
Set vertical padding for the EelLabeledImage. The padding attribute work just like that in GtkMisc.
Definition at line 1648 of file eel-labeled-image.c.
References EelLabeledImage::details, EEL_IS_LABELED_IMAGE, and MAX.
eel_labeled_image_toggle_button_new()
GtkWidget * eel_labeled_image_toggle_button_new (const char * text, GdkPixbuf * pixbuf)
eel_labeled_image_toggle_button_new: @text: Text to use for label or NULL. @pixbuf: Pixbuf to use for image or NULL.
Create a stock GtkToggleButton with a EelLabeledImage child.
Definition at line 1879 of file eel-labeled-image.c.
References eel_labeled_image_new(), and NULL.
eel_labeled_image_toggle_button_new_from_file_name()
GtkWidget * eel_labeled_image_toggle_button_new_from_file_name (const char * text, const char * pixbuf_file_name)
eel_labeled_image_toggle_button_new_from_file_name: @text: Text to use for label or NULL. @pixbuf_file_name: Name of pixbuf to use for image. Cannot be NULL.
Create a stock GtkToggleButton with a EelLabeledImage child.
Definition at line 1903 of file eel-labeled-image.c.
References eel_labeled_image_new_from_file_name(), and NULL.
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (EelLabeledImageAccessible , eel_labeled_image_accessible , GTK_TYPE_CONTAINER_ACCESSIBLE , G_IMPLEMENT_INTERFACE(ATK_TYPE_IMAGE, eel_labeled_image_accessible_image_interface_init))