MATE Desktop Environment: eel-glib-extensions.h File Reference
eel-glib-extensions.h File Reference
#include <glib.h>
#include <gio/gio.h>
Typedefs
typedef guint eel_boolean_bit
typedef gboolean(* EelPredicateFunction) (gpointer data, gpointer callback_data)
Functions
gboolean eel_g_list_exactly_one_item (GList *list)
gboolean eel_g_list_more_than_one_item (GList *list)
gboolean eel_g_list_equal (GList *list_a, GList *list_b)
gboolean eel_g_lists_sort_and_check_for_intersection (GList **list_a, GList **list_b)
GList * eel_g_list_partition (GList *list, EelPredicateFunction predicate, gpointer user_data, GList **removed)
void eel_g_list_free_deep (GList *list)
gboolean eel_g_str_list_equal (GList *str_list_a, GList *str_list_b)
GList * eel_g_str_list_alphabetize (GList *str_list)
int eel_g_str_list_index (GList *str_list, const char *str)
GHashTable * eel_g_hash_table_new_free_at_exit (GHashFunc hash_function, GCompareFunc key_compare_function, const char *display_name)
void eel_g_hash_table_safe_for_each (GHashTable *hash_table, GHFunc callback, gpointer callback_data)
int eel_g_strv_find (char **strv, const char *find_me)
gboolean eel_g_strv_equal (char **a, char **b)
int eel_round (double d)
void eel_add_weak_pointer (gpointer pointer_location)
void eel_remove_weak_pointer (gpointer pointer_location)
void eel_g_settings_add_auto_enum (GSettings *settings, const char *key, int *storage)
void eel_g_settings_add_auto_int (GSettings *settings, const char *key, int *storage)
void eel_g_settings_add_auto_boolean (GSettings *settings, const char *key, gboolean *storage)
void eel_g_settings_add_auto_strv (GSettings *settings, const char *key, char ***storage)
void eel_g_settings_add_auto_strv_as_quarks (GSettings *settings, const char *key, GQuark **storage)
Typedef Documentation
eel_boolean_bit
typedef guint eel_boolean_bit
Definition at line 34 of file eel-glib-extensions.h.
EelPredicateFunction
typedef gboolean(* EelPredicateFunction) (gpointer data, gpointer callback_data)
Definition at line 37 of file eel-glib-extensions.h.
Function Documentation
eel_add_weak_pointer()
void eel_add_weak_pointer (gpointer pointer_location)
eel_add_weak_pointer
Nulls out a saved reference to an object when the object gets destroyed.
@pointer_location: Address of the saved pointer.
Definition at line 475 of file eel-glib-extensions.c.
References NULL.
Referenced by caja_file_operations_unmount_mount_full(), caja_query_editor_new_with_bar(), and caja_window_slot_update_query_editor().
eel_g_hash_table_new_free_at_exit()
GHashTable * eel_g_hash_table_new_free_at_exit (GHashFunc hash_function, GCompareFunc key_compare_function, const char * display_name)
Definition at line 375 of file eel-glib-extensions.c.
References eel_debug_call_at_shutdown(), hash_table, and NULL.
Referenced by eel_timed_wait_start_with_duration(), and fm_properties_window_present().
eel_g_hash_table_safe_for_each()
void eel_g_hash_table_safe_for_each (GHashTable * hash_table, GHFunc callback, gpointer callback_data)
Definition at line 424 of file eel-glib-extensions.c.
References hash_table, and NULL.
eel_g_list_equal()
gboolean eel_g_list_equal (GList * list_a, GList * list_b)
eel_g_list_equal
Compares two lists to see if they are equal. @list_a: First list. @list_b: Second list.
Return value: TRUE if the lists are the same length with the same elements.
Definition at line 84 of file eel-glib-extensions.c.
References FALSE, and NULL.
Referenced by caja_icon_canvas_item_set_emblems().
eel_g_list_exactly_one_item()
gboolean eel_g_list_exactly_one_item (GList * list)
eel_g_list_exactly_one_item
Like g_list_length (list) == 1, only O(1) instead of O(n). @list: List.
Return value: TRUE if the list has exactly one item.
Definition at line 55 of file eel-glib-extensions.c.
References NULL.
eel_g_list_free_deep()
void eel_g_list_free_deep (GList * list)
eel_g_list_free_deep
Frees the elements of a list and then the list. @list: List of elements that can be freed with g_free.
Definition at line 160 of file eel-glib-extensions.c.
eel_g_list_more_than_one_item()
gboolean eel_g_list_more_than_one_item (GList * list)
eel_g_list_more_than_one_item
Like g_list_length (list) > 1, only O(1) instead of O(n). @list: List.
Return value: TRUE if the list has more than one item.
Definition at line 69 of file eel-glib-extensions.c.
References NULL.
eel_g_list_partition()
GList * eel_g_list_partition (GList * list, EelPredicateFunction predicate, gpointer user_data, GList ** failed)
eel_g_list_partition
Parition a list into two parts depending on whether the data elements satisfy a provided predicate. Order is preserved in both of the resulting lists, and the original list is consumed. A list of the items that satisfy the predicate is returned, and the list of items not satisfying the predicate is returned via the failed out argument.
@list: List to partition. @predicate: Function to call on each element. @user_data: Data to pass to function. @failed: The GList * variable pointed to by this argument will be set to the list of elements for which the predicate returned false.
Definition at line 281 of file eel-glib-extensions.c.
References NULL, and user_data.
Referenced by caja_file_list_filter_hidden(), and eel_self_check_glib_extensions().
eel_g_lists_sort_and_check_for_intersection()
gboolean eel_g_lists_sort_and_check_for_intersection (GList ** list_a, GList ** list_b)
Definition at line 229 of file eel-glib-extensions.c.
References FALSE, NULL, and TRUE.
eel_g_settings_add_auto_boolean()
void eel_g_settings_add_auto_boolean (GSettings * settings, const char * key, gboolean * storage)
Definition at line 537 of file eel-glib-extensions.c.
References key, and NULL.
eel_g_settings_add_auto_enum()
void eel_g_settings_add_auto_enum (GSettings * settings, const char * key, int * storage)
Definition at line 589 of file eel-glib-extensions.c.
References key, and NULL.
eel_g_settings_add_auto_int()
void eel_g_settings_add_auto_int (GSettings * settings, const char * key, int * storage)
Definition at line 563 of file eel-glib-extensions.c.
References key, and NULL.
eel_g_settings_add_auto_strv()
void eel_g_settings_add_auto_strv (GSettings * settings, const char * key, char *** storage)
Definition at line 638 of file eel-glib-extensions.c.
References key, and NULL.
eel_g_settings_add_auto_strv_as_quarks()
void eel_g_settings_add_auto_strv_as_quarks (GSettings * settings, const char * key, GQuark ** storage)
Definition at line 655 of file eel-glib-extensions.c.
References key, and NULL.
eel_g_str_list_alphabetize()
GList * eel_g_str_list_alphabetize (GList * list)
eel_g_str_list_alphabetize
Sort a list of strings using locale-sensitive rules.
@list: List of strings and/or NULLs.
Return value: @list, sorted.
Definition at line 132 of file eel-glib-extensions.c.
Referenced by caja_get_all_group_names(), and caja_get_user_names().
eel_g_str_list_equal()
gboolean eel_g_str_list_equal (GList * list_a, GList * list_b)
eel_g_str_list_equal
Compares two lists of C strings to see if they are equal. @list_a: First list. @list_b: Second list.
Return value: TRUE if the lists contain the same strings.
Definition at line 108 of file eel-glib-extensions.c.
References eel_strcmp(), FALSE, and NULL.
Referenced by eel_self_check_glib_extensions().
eel_g_str_list_index()
int eel_g_str_list_index (GList * str_list, const char * str)
Definition at line 138 of file eel-glib-extensions.c.
References NULL.
eel_g_strv_equal()
gboolean eel_g_strv_equal (char ** a, char ** b)
Definition at line 195 of file eel-glib-extensions.c.
References b, FALSE, NULL, and TRUE.
eel_g_strv_find()
int eel_g_strv_find (char ** strv, const char * find_me)
eel_g_strv_find
Get index of string in array of strings.
@strv: NULL-terminated array of strings. @find_me: string to search for.
Return value: index of array entry in @strv that matches @find_me, or -1 if no matching entry.
Definition at line 177 of file eel-glib-extensions.c.
References NULL.
Referenced by caja_autorun_get_preferences(), and eel_self_check_glib_extensions().
eel_remove_weak_pointer()
void eel_remove_weak_pointer (gpointer pointer_location)
eel_remove_weak_pointer
Removes the weak pointer that was added by eel_add_weak_pointer. Also nulls out the pointer.
@pointer_location: Pointer that was passed to eel_add_weak_pointer.
Definition at line 503 of file eel-glib-extensions.c.
References NULL.
Referenced by caja_file_operations_unmount_mount_full().
eel_round()
int eel_round (double d)
Definition at line 450 of file eel-glib-extensions.c.
Referenced by eel_create_colorized_pixbuf().