MATE Desktop Environment: eel-string.c File Reference
eel-string.c File Reference
#include <config.h>
#include "eel-glib-extensions.h"
#include "eel-string.h"
#include <errno.h>
#include <locale.h>
#include <stdlib.h>
#include <string.h>
#include "eel-lib-self-check-functions.h"
Typedefs
typedef int ArgType
Enumerations
enum {
ARG_TYPE_INVALID , ARG_TYPE_INT , ARG_TYPE_LONG , ARG_TYPE_LONG_LONG ,
ARG_TYPE_SIZE , ARG_TYPE_LONG_DOUBLE , ARG_TYPE_DOUBLE , ARG_TYPE_POINTER
}
Functions
size_t eel_strlen (const char *string)
char * eel_strchr (const char *haystack, char needle)
int eel_strcmp (const char *string_a, const char *string_b)
gboolean eel_str_is_empty (const char *string_or_null)
gboolean eel_str_has_prefix (const char *haystack, const char *needle)
gboolean eel_istr_has_prefix (const char *haystack, const char *needle)
char * eel_str_get_prefix (const char *source, const char *delimiter)
char * eel_str_double_underscores (const char *string)
char * eel_str_capitalize (const char *string)
char * eel_str_middle_truncate (const char *string, guint truncate_length)
char * eel_str_strip_substring_and_after (const char *string, const char *substring)
char * eel_str_replace_substring (const char *string, const char *substring, const char *replacement)
char * eel_strdup_vprintf_with_custom (EelPrintfHandler *custom, const char *format, va_list va_orig)
char * eel_strdup_printf_with_custom (EelPrintfHandler *handlers, const char *format,...)
void eel_self_check_string (void)
Typedef Documentation
ArgType
typedef int ArgType
Definition at line 366 of file eel-string.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ARG_TYPE_INVALID
ARG_TYPE_INT
ARG_TYPE_LONG
ARG_TYPE_LONG_LONG
ARG_TYPE_SIZE
ARG_TYPE_LONG_DOUBLE
ARG_TYPE_DOUBLE
ARG_TYPE_POINTER
Definition at line 354 of file eel-string.c.
Function Documentation
eel_istr_has_prefix()
gboolean eel_istr_has_prefix (const char * haystack, const char * needle)
Definition at line 76 of file eel-string.c.
References FALSE, NULL, and TRUE.
Referenced by caja_customization_data_get_next_element_for_display(), eel_uri_is_desktop(), eel_uri_is_search(), and eel_uri_is_trash().
eel_self_check_string()
void eel_self_check_string (void)
Definition at line 829 of file eel-string.c.
References EEL_CHECK_BOOLEAN_RESULT, EEL_CHECK_INTEGER_RESULT, EEL_CHECK_STRING_RESULT, eel_str_capitalize(), eel_str_double_underscores(), eel_str_get_prefix(), eel_str_has_prefix(), eel_str_middle_truncate(), eel_str_replace_substring(), eel_str_strip_substring_and_after(), eel_strcmp(), eel_strlen(), FALSE, NULL, and TRUE.
eel_str_capitalize()
char * eel_str_capitalize (const char * string)
Definition at line 183 of file eel-string.c.
References NULL.
Referenced by eel_self_check_string().
eel_str_double_underscores()
char * eel_str_double_underscores (const char * string)
Definition at line 144 of file eel-string.c.
References NULL.
Referenced by eel_self_check_string().
eel_str_get_prefix()
char * eel_str_get_prefix (const char * source, const char * delimiter)
eel_str_get_prefix: Get a new string containing the first part of an existing string.
@source: The string whose prefix should be extracted. @delimiter: The string that marks the end of the prefix.
Return value: A newly-allocated string that that matches the first part of @source, up to but not including the first occurrence of @delimiter. If @source is NULL, returns NULL. If @delimiter is NULL, returns a copy of @source. If @delimiter does not occur in @source, returns a copy of @source.
Definition at line 118 of file eel-string.c.
References NULL.
Referenced by eel_self_check_string().
eel_str_has_prefix()
gboolean eel_str_has_prefix (const char * haystack, const char * needle)
Definition at line 69 of file eel-string.c.
References NULL.
Referenced by eel_self_check_string().
eel_str_is_empty()
gboolean eel_str_is_empty (const char * string_or_null)
Definition at line 63 of file eel-string.c.
References eel_strcmp(), and NULL.
Referenced by fm_directory_view_handle_netscape_url_drop().
eel_str_middle_truncate()
char * eel_str_middle_truncate (const char * string, guint truncate_length)
Definition at line 208 of file eel-string.c.
References NULL.
Referenced by eel_self_check_string(), and fm_report_error_renaming_file().
eel_str_replace_substring()
char * eel_str_replace_substring (const char * string, const char * substring, const char * replacement)
Definition at line 280 of file eel-string.c.
References eel_strlen(), memcpy, and NULL.
Referenced by eel_self_check_string().
eel_str_strip_substring_and_after()
char * eel_str_strip_substring_and_after (const char * string, const char * substring)
Definition at line 256 of file eel-string.c.
References NULL.
Referenced by eel_self_check_string().
eel_strchr()
char * eel_strchr (const char * haystack, char needle)
Definition at line 45 of file eel-string.c.
References NULL, and strchr.
Referenced by eel_gradient_is_gradient(), and eel_gradient_parse_one_color_spec().
eel_strcmp()
int eel_strcmp (const char * string_a, const char * string_b)
Definition at line 51 of file eel-string.c.
References NULL.
Referenced by caja_file_set_display_name(), eel_g_str_list_equal(), eel_gradient_new(), eel_self_check_string(), and eel_str_is_empty().
eel_strdup_printf_with_custom()
char * eel_strdup_printf_with_custom (EelPrintfHandler * handlers, const char * format, ...)
Definition at line 741 of file eel-string.c.
References eel_strdup_vprintf_with_custom().
eel_strdup_vprintf_with_custom()
char * eel_strdup_vprintf_with_custom (EelPrintfHandler * custom, const char * format, va_list va_orig)
Definition at line 534 of file eel-string.c.
References ARG_TYPE_INT, FALSE, NULL, EelPrintfHandler::to_string, and TRUE.
Referenced by eel_strdup_printf_with_custom().
eel_strlen()
size_t eel_strlen (const char * string)
Definition at line 39 of file eel-string.c.
References NULL.
Referenced by eel_gradient_is_horizontal(), eel_self_check_string(), and eel_str_replace_substring().