MATE Desktop Environment: eel-gdk-extensions.c File Reference
eel-gdk-extensions.c File Reference
#include <config.h>
#include "eel-gdk-extensions.h"
#include "eel-glib-extensions.h"
#include "eel-lib-self-check-functions.h"
#include "eel-string.h"
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gdk/gdkprivate.h>
#include <gdk/gdk.h>
#include <gdk/gdkx.h>
#include <stdlib.h>
#include <pango/pango.h>
Functions
char * eel_gradient_new (const char *start_color, const char *end_color, gboolean is_horizontal)
gboolean eel_gradient_is_gradient (const char *gradient_spec)
gboolean eel_gradient_is_horizontal (const char *gradient_spec)
char * eel_gradient_parse_one_color_spec (const char *spec, int *percent, const char **next_spec)
char * eel_gradient_get_start_color_spec (const char *gradient_spec)
char * eel_gradient_get_end_color_spec (const char *gradient_spec)
char * eel_gradient_set_left_color_spec (const char *gradient_spec, const char *left_color)
char * eel_gradient_set_top_color_spec (const char *gradient_spec, const char *top_color)
char * eel_gradient_set_right_color_spec (const char *gradient_spec, const char *right_color)
char * eel_gradient_set_bottom_color_spec (const char *gradient_spec, const char *bottom_color)
void eel_gdk_rgba_parse_with_white_default (GdkRGBA *color, const char *color_spec)
guint32 eel_rgb16_to_rgb (gushort r, gushort g, gushort b)
guint32 eel_gdk_rgba_to_rgb (const GdkRGBA *color)
GdkRGBA eel_gdk_rgb_to_rgba (guint32 color)
char * eel_gdk_rgb_to_color_spec (const guint32 color)
EEL_CHECK_STRING_RESULT (eel_gradient_new("", "", FALSE), "")
EEL_CHECK_STRING_RESULT (eel_gradient_new("a", "b", FALSE), "a-b")
EEL_CHECK_STRING_RESULT (eel_gradient_new("a", "b", TRUE), "a-b:h")
EEL_CHECK_STRING_RESULT (eel_gradient_new("a", "a", FALSE), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_new("a", "a", TRUE), "a")
EEL_CHECK_BOOLEAN_RESULT (eel_gradient_is_gradient(""), FALSE)
EEL_CHECK_BOOLEAN_RESULT (eel_gradient_is_gradient("-"), TRUE)
EEL_CHECK_BOOLEAN_RESULT (eel_gradient_is_gradient("a"), FALSE)
EEL_CHECK_BOOLEAN_RESULT (eel_gradient_is_gradient("a-b"), TRUE)
EEL_CHECK_BOOLEAN_RESULT (eel_gradient_is_gradient("a-b:h"), TRUE)
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec(""), "")
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("-"), "")
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("a"), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("a-b"), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("a-"), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("-b"), "")
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("a:h"), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("a:v"), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("a:c"), "a:c")
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("a:-b"), "a:")
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("a:-b:v"), "a:")
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec(""), "")
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("-"), "")
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("a"), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("a-b"), "b")
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("a-"), "")
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("-b"), "b")
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("a:h"), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("a:v"), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("a:c"), "a:c")
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("a:-b"), "b")
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("a:-b:v"), "b")
EEL_CHECK_STRING_RESULT (eel_gradient_set_left_color_spec("", ""), "")
EEL_CHECK_STRING_RESULT (eel_gradient_set_left_color_spec("", "a"), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_set_left_color_spec("a", ""), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_set_left_color_spec("a", "a"), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_set_left_color_spec("a", "b"), "b-a:h")
EEL_CHECK_STRING_RESULT (eel_gradient_set_left_color_spec("a-c:v", "b"), "b-c:h")
EEL_CHECK_STRING_RESULT (eel_gradient_set_left_color_spec("a-c:v", "c"), "c")
EEL_CHECK_STRING_RESULT (eel_gradient_set_left_color_spec("a:-b:v", "d"), "d-b:h")
EEL_CHECK_STRING_RESULT (eel_gradient_set_top_color_spec("", ""), "")
EEL_CHECK_STRING_RESULT (eel_gradient_set_top_color_spec("", "a"), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_set_top_color_spec("a", ""), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_set_top_color_spec("a", "a"), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_set_top_color_spec("a", "b"), "b-a")
EEL_CHECK_STRING_RESULT (eel_gradient_set_top_color_spec("a-c:v", "b"), "b-c")
EEL_CHECK_STRING_RESULT (eel_gradient_set_top_color_spec("a-c:v", "c"), "c")
EEL_CHECK_STRING_RESULT (eel_gradient_set_top_color_spec("a:-b:h", "d"), "d-b")
EEL_CHECK_STRING_RESULT (eel_gradient_set_right_color_spec("", ""), "")
EEL_CHECK_STRING_RESULT (eel_gradient_set_right_color_spec("", "a"), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_set_right_color_spec("a", ""), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_set_right_color_spec("a", "a"), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_set_right_color_spec("a", "b"), "a-b:h")
EEL_CHECK_STRING_RESULT (eel_gradient_set_right_color_spec("a-c:v", "b"), "a-b:h")
EEL_CHECK_STRING_RESULT (eel_gradient_set_right_color_spec("a-c:v", "c"), "a-c:h")
EEL_CHECK_STRING_RESULT (eel_gradient_set_right_color_spec("a:-b:v", "d"), "a:-d:h")
EEL_CHECK_STRING_RESULT (eel_gradient_set_bottom_color_spec("", ""), "")
EEL_CHECK_STRING_RESULT (eel_gradient_set_bottom_color_spec("", "a"), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_set_bottom_color_spec("a", ""), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_set_bottom_color_spec("a", "a"), "a")
EEL_CHECK_STRING_RESULT (eel_gradient_set_bottom_color_spec("a", "b"), "a-b")
EEL_CHECK_STRING_RESULT (eel_gradient_set_bottom_color_spec("a-c:v", "b"), "a-b")
EEL_CHECK_STRING_RESULT (eel_gradient_set_bottom_color_spec("a-c:v", "c"), "a-c")
EEL_CHECK_STRING_RESULT (eel_gradient_set_bottom_color_spec("a:-b:h", "d"), "a:-d")
EEL_CHECK_STRING_RESULT (eel_self_check_parse(""), "FFFFFFFFFFFF")
EEL_CHECK_STRING_RESULT (eel_self_check_parse("a"), "FFFFFFFFFFFF")
EEL_CHECK_STRING_RESULT (eel_self_check_parse("white"), "FFFFFFFFFFFF")
EEL_CHECK_STRING_RESULT (eel_self_check_parse("black"), "000000000000")
EEL_CHECK_STRING_RESULT (eel_self_check_parse("red"), "FFFF00000000")
EEL_CHECK_STRING_RESULT (eel_self_check_parse("#012345"), "010123234545")
EEL_CHECK_STRING_RESULT (eel_self_check_gdk_rgb_to_color(EEL_RGB_COLOR_RED), "FFFF00000000")
EEL_CHECK_STRING_RESULT (eel_self_check_gdk_rgb_to_color(EEL_RGB_COLOR_BLACK), "000000000000")
EEL_CHECK_STRING_RESULT (eel_self_check_gdk_rgb_to_color(EEL_RGB_COLOR_WHITE), "FFFFFFFFFFFF")
EEL_CHECK_STRING_RESULT (eel_self_check_gdk_rgb_to_color(EEL_RGB_COLOR_PACK(0x01, 0x23, 0x45)), "010123234545")
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0xFF, 0x00, 0x00, 00), EEL_RGB_COLOR_RED)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0x00, 0xFF, 0x00, 00), EEL_RGB_COLOR_GREEN)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0x00, 0x00, 0xFF, 00), EEL_RGB_COLOR_BLUE)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0xFF, 0xFF, 0xFF, 00), EEL_RGB_COLOR_WHITE)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0x00, 0x00, 0x00, 00), EEL_RGB_COLOR_BLACK)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0xFF, 0x00, 0x00, 0xFF), EEL_RGBA_COLOR_OPAQUE_RED)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0x00, 0xFF, 0x00, 0xFF), EEL_RGBA_COLOR_OPAQUE_GREEN)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0x00, 0x00, 0xFF, 0xFF), EEL_RGBA_COLOR_OPAQUE_BLUE)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0xFF, 0xFF, 0xFF, 0xFF), EEL_RGBA_COLOR_OPAQUE_WHITE)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0x00, 0x00, 0x00, 0xFF), EEL_RGBA_COLOR_OPAQUE_BLACK)
EEL_CHECK_INTEGER_RESULT (EEL_RGB_COLOR_PACK(0xFF, 0x00, 0x00), EEL_RGBA_COLOR_OPAQUE_RED)
EEL_CHECK_INTEGER_RESULT (EEL_RGB_COLOR_PACK(0x00, 0xFF, 0x00), EEL_RGBA_COLOR_OPAQUE_GREEN)
EEL_CHECK_INTEGER_RESULT (EEL_RGB_COLOR_PACK(0x00, 0x00, 0xFF), EEL_RGBA_COLOR_OPAQUE_BLUE)
EEL_CHECK_INTEGER_RESULT (EEL_RGB_COLOR_PACK(0xFF, 0xFF, 0xFF), EEL_RGBA_COLOR_OPAQUE_WHITE)
EEL_CHECK_INTEGER_RESULT (EEL_RGB_COLOR_PACK(0x00, 0x00, 0x00), EEL_RGBA_COLOR_OPAQUE_BLACK)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGBA_COLOR_OPAQUE_RED), 0xFF)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGBA_COLOR_OPAQUE_GREEN), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGBA_COLOR_OPAQUE_BLUE), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGBA_COLOR_OPAQUE_WHITE), 0xFF)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGBA_COLOR_OPAQUE_BLACK), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGB_COLOR_RED), 0xFF)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGB_COLOR_GREEN), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGB_COLOR_BLUE), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGB_COLOR_WHITE), 0xFF)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGB_COLOR_BLACK), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGBA_COLOR_OPAQUE_RED), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGBA_COLOR_OPAQUE_GREEN), 0xFF)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGBA_COLOR_OPAQUE_BLUE), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGBA_COLOR_OPAQUE_WHITE), 0xFF)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGBA_COLOR_OPAQUE_BLACK), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGB_COLOR_RED), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGB_COLOR_GREEN), 0xFF)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGB_COLOR_BLUE), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGB_COLOR_WHITE), 0xFF)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGB_COLOR_BLACK), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGBA_COLOR_OPAQUE_RED), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGBA_COLOR_OPAQUE_GREEN), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGBA_COLOR_OPAQUE_BLUE), 0xFF)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGBA_COLOR_OPAQUE_WHITE), 0xFF)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGBA_COLOR_OPAQUE_BLACK), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGB_COLOR_RED), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGB_COLOR_GREEN), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGB_COLOR_BLUE), 0xFF)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGB_COLOR_WHITE), 0xFF)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGB_COLOR_BLACK), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGBA_COLOR_OPAQUE_RED), 0xFF)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGBA_COLOR_OPAQUE_GREEN), 0xFF)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGBA_COLOR_OPAQUE_BLUE), 0xFF)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGBA_COLOR_OPAQUE_WHITE), 0xFF)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGBA_COLOR_OPAQUE_BLACK), 0xFF)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGB_COLOR_RED), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGB_COLOR_GREEN), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGB_COLOR_BLUE), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGB_COLOR_WHITE), 0x00)
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGB_COLOR_BLACK), 0x00)
Function Documentation
EEL_CHECK_BOOLEAN_RESULT() [1/5]
EEL_CHECK_BOOLEAN_RESULT (eel_gradient_is_gradient("") , FALSE)
References eel_gradient_is_gradient(), and FALSE.
EEL_CHECK_BOOLEAN_RESULT() [2/5]
EEL_CHECK_BOOLEAN_RESULT (eel_gradient_is_gradient("-") , TRUE)
References eel_gradient_is_gradient(), and TRUE.
EEL_CHECK_BOOLEAN_RESULT() [3/5]
EEL_CHECK_BOOLEAN_RESULT (eel_gradient_is_gradient("a") , FALSE)
References eel_gradient_is_gradient(), and FALSE.
EEL_CHECK_BOOLEAN_RESULT() [4/5]
EEL_CHECK_BOOLEAN_RESULT (eel_gradient_is_gradient("a-b") , TRUE)
References eel_gradient_is_gradient(), and TRUE.
EEL_CHECK_BOOLEAN_RESULT() [5/5]
EEL_CHECK_BOOLEAN_RESULT (eel_gradient_is_gradient("a-b:h") , TRUE)
References eel_gradient_is_gradient(), and TRUE.
EEL_CHECK_INTEGER_RESULT() [1/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGB_COLOR_PACK(0x00, 0x00, 0x00) , EEL_RGBA_COLOR_OPAQUE_BLACK)
References EEL_RGB_COLOR_PACK, and EEL_RGBA_COLOR_OPAQUE_BLACK.
EEL_CHECK_INTEGER_RESULT() [2/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGB_COLOR_PACK(0x00, 0x00, 0xFF) , EEL_RGBA_COLOR_OPAQUE_BLUE)
References EEL_RGB_COLOR_PACK, and EEL_RGBA_COLOR_OPAQUE_BLUE.
EEL_CHECK_INTEGER_RESULT() [3/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGB_COLOR_PACK(0x00, 0xFF, 0x00) , EEL_RGBA_COLOR_OPAQUE_GREEN)
References EEL_RGB_COLOR_PACK, and EEL_RGBA_COLOR_OPAQUE_GREEN.
EEL_CHECK_INTEGER_RESULT() [4/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGB_COLOR_PACK(0xFF, 0x00, 0x00) , EEL_RGBA_COLOR_OPAQUE_RED)
References EEL_RGB_COLOR_PACK, and EEL_RGBA_COLOR_OPAQUE_RED.
EEL_CHECK_INTEGER_RESULT() [5/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGB_COLOR_PACK(0xFF, 0xFF, 0xFF) , EEL_RGBA_COLOR_OPAQUE_WHITE)
References EEL_RGB_COLOR_PACK, and EEL_RGBA_COLOR_OPAQUE_WHITE.
EEL_CHECK_INTEGER_RESULT() [6/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGB_COLOR_BLACK) , 0x00)
References EEL_RGB_COLOR_BLACK, and EEL_RGBA_COLOR_GET_A.
EEL_CHECK_INTEGER_RESULT() [7/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGB_COLOR_BLUE) , 0x00)
References EEL_RGB_COLOR_BLUE, and EEL_RGBA_COLOR_GET_A.
EEL_CHECK_INTEGER_RESULT() [8/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGB_COLOR_GREEN) , 0x00)
References EEL_RGB_COLOR_GREEN, and EEL_RGBA_COLOR_GET_A.
EEL_CHECK_INTEGER_RESULT() [9/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGB_COLOR_RED) , 0x00)
References EEL_RGB_COLOR_RED, and EEL_RGBA_COLOR_GET_A.
EEL_CHECK_INTEGER_RESULT() [10/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGB_COLOR_WHITE) , 0x00)
References EEL_RGB_COLOR_WHITE, and EEL_RGBA_COLOR_GET_A.
EEL_CHECK_INTEGER_RESULT() [11/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGBA_COLOR_OPAQUE_BLACK) , 0xFF)
References EEL_RGBA_COLOR_GET_A, and EEL_RGBA_COLOR_OPAQUE_BLACK.
EEL_CHECK_INTEGER_RESULT() [12/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGBA_COLOR_OPAQUE_BLUE) , 0xFF)
References EEL_RGBA_COLOR_GET_A, and EEL_RGBA_COLOR_OPAQUE_BLUE.
EEL_CHECK_INTEGER_RESULT() [13/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGBA_COLOR_OPAQUE_GREEN) , 0xFF)
References EEL_RGBA_COLOR_GET_A, and EEL_RGBA_COLOR_OPAQUE_GREEN.
EEL_CHECK_INTEGER_RESULT() [14/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGBA_COLOR_OPAQUE_RED) , 0xFF)
References EEL_RGBA_COLOR_GET_A, and EEL_RGBA_COLOR_OPAQUE_RED.
EEL_CHECK_INTEGER_RESULT() [15/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_A(EEL_RGBA_COLOR_OPAQUE_WHITE) , 0xFF)
References EEL_RGBA_COLOR_GET_A, and EEL_RGBA_COLOR_OPAQUE_WHITE.
EEL_CHECK_INTEGER_RESULT() [16/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGB_COLOR_BLACK) , 0x00)
References EEL_RGB_COLOR_BLACK, and EEL_RGBA_COLOR_GET_B.
EEL_CHECK_INTEGER_RESULT() [17/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGB_COLOR_BLUE) , 0xFF)
References EEL_RGB_COLOR_BLUE, and EEL_RGBA_COLOR_GET_B.
EEL_CHECK_INTEGER_RESULT() [18/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGB_COLOR_GREEN) , 0x00)
References EEL_RGB_COLOR_GREEN, and EEL_RGBA_COLOR_GET_B.
EEL_CHECK_INTEGER_RESULT() [19/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGB_COLOR_RED) , 0x00)
References EEL_RGB_COLOR_RED, and EEL_RGBA_COLOR_GET_B.
EEL_CHECK_INTEGER_RESULT() [20/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGB_COLOR_WHITE) , 0xFF)
References EEL_RGB_COLOR_WHITE, and EEL_RGBA_COLOR_GET_B.
EEL_CHECK_INTEGER_RESULT() [21/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGBA_COLOR_OPAQUE_BLACK) , 0x00)
References EEL_RGBA_COLOR_GET_B, and EEL_RGBA_COLOR_OPAQUE_BLACK.
EEL_CHECK_INTEGER_RESULT() [22/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGBA_COLOR_OPAQUE_BLUE) , 0xFF)
References EEL_RGBA_COLOR_GET_B, and EEL_RGBA_COLOR_OPAQUE_BLUE.
EEL_CHECK_INTEGER_RESULT() [23/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGBA_COLOR_OPAQUE_GREEN) , 0x00)
References EEL_RGBA_COLOR_GET_B, and EEL_RGBA_COLOR_OPAQUE_GREEN.
EEL_CHECK_INTEGER_RESULT() [24/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGBA_COLOR_OPAQUE_RED) , 0x00)
References EEL_RGBA_COLOR_GET_B, and EEL_RGBA_COLOR_OPAQUE_RED.
EEL_CHECK_INTEGER_RESULT() [25/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_B(EEL_RGBA_COLOR_OPAQUE_WHITE) , 0xFF)
References EEL_RGBA_COLOR_GET_B, and EEL_RGBA_COLOR_OPAQUE_WHITE.
EEL_CHECK_INTEGER_RESULT() [26/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGB_COLOR_BLACK) , 0x00)
References EEL_RGB_COLOR_BLACK, and EEL_RGBA_COLOR_GET_G.
EEL_CHECK_INTEGER_RESULT() [27/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGB_COLOR_BLUE) , 0x00)
References EEL_RGB_COLOR_BLUE, and EEL_RGBA_COLOR_GET_G.
EEL_CHECK_INTEGER_RESULT() [28/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGB_COLOR_GREEN) , 0xFF)
References EEL_RGB_COLOR_GREEN, and EEL_RGBA_COLOR_GET_G.
EEL_CHECK_INTEGER_RESULT() [29/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGB_COLOR_RED) , 0x00)
References EEL_RGB_COLOR_RED, and EEL_RGBA_COLOR_GET_G.
EEL_CHECK_INTEGER_RESULT() [30/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGB_COLOR_WHITE) , 0xFF)
References EEL_RGB_COLOR_WHITE, and EEL_RGBA_COLOR_GET_G.
EEL_CHECK_INTEGER_RESULT() [31/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGBA_COLOR_OPAQUE_BLACK) , 0x00)
References EEL_RGBA_COLOR_GET_G, and EEL_RGBA_COLOR_OPAQUE_BLACK.
EEL_CHECK_INTEGER_RESULT() [32/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGBA_COLOR_OPAQUE_BLUE) , 0x00)
References EEL_RGBA_COLOR_GET_G, and EEL_RGBA_COLOR_OPAQUE_BLUE.
EEL_CHECK_INTEGER_RESULT() [33/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGBA_COLOR_OPAQUE_GREEN) , 0xFF)
References EEL_RGBA_COLOR_GET_G, and EEL_RGBA_COLOR_OPAQUE_GREEN.
EEL_CHECK_INTEGER_RESULT() [34/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGBA_COLOR_OPAQUE_RED) , 0x00)
References EEL_RGBA_COLOR_GET_G, and EEL_RGBA_COLOR_OPAQUE_RED.
EEL_CHECK_INTEGER_RESULT() [35/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_G(EEL_RGBA_COLOR_OPAQUE_WHITE) , 0xFF)
References EEL_RGBA_COLOR_GET_G, and EEL_RGBA_COLOR_OPAQUE_WHITE.
EEL_CHECK_INTEGER_RESULT() [36/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGB_COLOR_BLACK) , 0x00)
References EEL_RGB_COLOR_BLACK, and EEL_RGBA_COLOR_GET_R.
EEL_CHECK_INTEGER_RESULT() [37/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGB_COLOR_BLUE) , 0x00)
References EEL_RGB_COLOR_BLUE, and EEL_RGBA_COLOR_GET_R.
EEL_CHECK_INTEGER_RESULT() [38/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGB_COLOR_GREEN) , 0x00)
References EEL_RGB_COLOR_GREEN, and EEL_RGBA_COLOR_GET_R.
EEL_CHECK_INTEGER_RESULT() [39/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGB_COLOR_RED) , 0xFF)
References EEL_RGB_COLOR_RED, and EEL_RGBA_COLOR_GET_R.
EEL_CHECK_INTEGER_RESULT() [40/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGB_COLOR_WHITE) , 0xFF)
References EEL_RGB_COLOR_WHITE, and EEL_RGBA_COLOR_GET_R.
EEL_CHECK_INTEGER_RESULT() [41/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGBA_COLOR_OPAQUE_BLACK) , 0x00)
References EEL_RGBA_COLOR_GET_R, and EEL_RGBA_COLOR_OPAQUE_BLACK.
EEL_CHECK_INTEGER_RESULT() [42/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGBA_COLOR_OPAQUE_BLUE) , 0x00)
References EEL_RGBA_COLOR_GET_R, and EEL_RGBA_COLOR_OPAQUE_BLUE.
EEL_CHECK_INTEGER_RESULT() [43/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGBA_COLOR_OPAQUE_GREEN) , 0x00)
References EEL_RGBA_COLOR_GET_R, and EEL_RGBA_COLOR_OPAQUE_GREEN.
EEL_CHECK_INTEGER_RESULT() [44/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGBA_COLOR_OPAQUE_RED) , 0xFF)
References EEL_RGBA_COLOR_GET_R, and EEL_RGBA_COLOR_OPAQUE_RED.
EEL_CHECK_INTEGER_RESULT() [45/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_GET_R(EEL_RGBA_COLOR_OPAQUE_WHITE) , 0xFF)
References EEL_RGBA_COLOR_GET_R, and EEL_RGBA_COLOR_OPAQUE_WHITE.
EEL_CHECK_INTEGER_RESULT() [46/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0x00, 0x00, 0x00, 00) , EEL_RGB_COLOR_BLACK)
References EEL_RGB_COLOR_BLACK, and EEL_RGBA_COLOR_PACK.
EEL_CHECK_INTEGER_RESULT() [47/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0x00, 0x00, 0x00, 0xFF) , EEL_RGBA_COLOR_OPAQUE_BLACK)
References EEL_RGBA_COLOR_OPAQUE_BLACK, and EEL_RGBA_COLOR_PACK.
EEL_CHECK_INTEGER_RESULT() [48/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0x00, 0x00, 0xFF, 00) , EEL_RGB_COLOR_BLUE)
References EEL_RGB_COLOR_BLUE, and EEL_RGBA_COLOR_PACK.
EEL_CHECK_INTEGER_RESULT() [49/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0x00, 0x00, 0xFF, 0xFF) , EEL_RGBA_COLOR_OPAQUE_BLUE)
References EEL_RGBA_COLOR_OPAQUE_BLUE, and EEL_RGBA_COLOR_PACK.
EEL_CHECK_INTEGER_RESULT() [50/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0x00, 0xFF, 0x00, 00) , EEL_RGB_COLOR_GREEN)
References EEL_RGB_COLOR_GREEN, and EEL_RGBA_COLOR_PACK.
EEL_CHECK_INTEGER_RESULT() [51/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0x00, 0xFF, 0x00, 0xFF) , EEL_RGBA_COLOR_OPAQUE_GREEN)
References EEL_RGBA_COLOR_OPAQUE_GREEN, and EEL_RGBA_COLOR_PACK.
EEL_CHECK_INTEGER_RESULT() [52/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0xFF, 0x00, 0x00, 00) , EEL_RGB_COLOR_RED)
References EEL_RGB_COLOR_RED, and EEL_RGBA_COLOR_PACK.
EEL_CHECK_INTEGER_RESULT() [53/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0xFF, 0x00, 0x00, 0xFF) , EEL_RGBA_COLOR_OPAQUE_RED)
References EEL_RGBA_COLOR_OPAQUE_RED, and EEL_RGBA_COLOR_PACK.
EEL_CHECK_INTEGER_RESULT() [54/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0xFF, 0xFF, 0xFF, 00) , EEL_RGB_COLOR_WHITE)
References EEL_RGB_COLOR_WHITE, and EEL_RGBA_COLOR_PACK.
EEL_CHECK_INTEGER_RESULT() [55/55]
EEL_CHECK_INTEGER_RESULT (EEL_RGBA_COLOR_PACK(0xFF, 0xFF, 0xFF, 0xFF) , EEL_RGBA_COLOR_OPAQUE_WHITE)
References EEL_RGBA_COLOR_OPAQUE_WHITE, and EEL_RGBA_COLOR_PACK.
EEL_CHECK_STRING_RESULT() [1/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("") , "")
References eel_gradient_get_end_color_spec().
EEL_CHECK_STRING_RESULT() [2/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("-") , "")
References eel_gradient_get_end_color_spec().
EEL_CHECK_STRING_RESULT() [3/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("-b") , "b")
References eel_gradient_get_end_color_spec().
EEL_CHECK_STRING_RESULT() [4/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("a") , "a")
References eel_gradient_get_end_color_spec().
EEL_CHECK_STRING_RESULT() [5/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("a-") , "")
References eel_gradient_get_end_color_spec().
EEL_CHECK_STRING_RESULT() [6/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("a-b") , "b")
References eel_gradient_get_end_color_spec().
EEL_CHECK_STRING_RESULT() [7/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("a:-b") , "b")
References eel_gradient_get_end_color_spec().
EEL_CHECK_STRING_RESULT() [8/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("a:-b:v") , "b")
References eel_gradient_get_end_color_spec().
EEL_CHECK_STRING_RESULT() [9/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("a:c") , "a:c")
References eel_gradient_get_end_color_spec().
EEL_CHECK_STRING_RESULT() [10/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("a:h") , "a")
References eel_gradient_get_end_color_spec().
EEL_CHECK_STRING_RESULT() [11/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_end_color_spec("a:v") , "a")
References eel_gradient_get_end_color_spec().
EEL_CHECK_STRING_RESULT() [12/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("") , "")
References eel_gradient_get_start_color_spec().
EEL_CHECK_STRING_RESULT() [13/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("-") , "")
References eel_gradient_get_start_color_spec().
EEL_CHECK_STRING_RESULT() [14/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("-b") , "")
References eel_gradient_get_start_color_spec().
EEL_CHECK_STRING_RESULT() [15/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("a") , "a")
References eel_gradient_get_start_color_spec().
EEL_CHECK_STRING_RESULT() [16/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("a-") , "a")
References eel_gradient_get_start_color_spec().
EEL_CHECK_STRING_RESULT() [17/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("a-b") , "a")
References eel_gradient_get_start_color_spec().
EEL_CHECK_STRING_RESULT() [18/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("a:-b") , "a:")
References eel_gradient_get_start_color_spec().
EEL_CHECK_STRING_RESULT() [19/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("a:-b:v") , "a:")
References eel_gradient_get_start_color_spec().
EEL_CHECK_STRING_RESULT() [20/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("a:c") , "a:c")
References eel_gradient_get_start_color_spec().
EEL_CHECK_STRING_RESULT() [21/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("a:h") , "a")
References eel_gradient_get_start_color_spec().
EEL_CHECK_STRING_RESULT() [22/69]
EEL_CHECK_STRING_RESULT (eel_gradient_get_start_color_spec("a:v") , "a")
References eel_gradient_get_start_color_spec().
EEL_CHECK_STRING_RESULT() [23/69]
EEL_CHECK_STRING_RESULT (eel_gradient_new("", "", FALSE) , "")
eel_gdk_rgba_is_dark:
Return true if the given color is `dark' */ gboolean eel_gdk_rgba_is_dark (const GdkRGBA *color) { int intensity;
intensity = (((guint) (color->red * 0xff) * 77)
((guint) (color->green * 0xff) * 150)
((guint) (color->blue * 0xff) * 28)) >> 8;
return intensity < 128; }
EelGdkGeometryFlags eel_gdk_parse_geometry (const char *string, int *x_return, int *y_return, guint *width_return, guint *height_return) { int x11_flags; EelGdkGeometryFlags gdk_flags;
g_return_val_if_fail (string != NULL, EEL_GDK_NO_VALUE); g_return_val_if_fail (x_return != NULL, EEL_GDK_NO_VALUE); g_return_val_if_fail (y_return != NULL, EEL_GDK_NO_VALUE); g_return_val_if_fail (width_return != NULL, EEL_GDK_NO_VALUE); g_return_val_if_fail (height_return != NULL, EEL_GDK_NO_VALUE);
x11_flags = XParseGeometry (string, x_return, y_return, width_return, height_return);
gdk_flags = EEL_GDK_NO_VALUE; if (x11_flags & XValue) { gdk_flags |= EEL_GDK_X_VALUE; } if (x11_flags & YValue) { gdk_flags |= EEL_GDK_Y_VALUE; } if (x11_flags & WidthValue) { gdk_flags |= EEL_GDK_WIDTH_VALUE; } if (x11_flags & HeightValue) { gdk_flags |= EEL_GDK_HEIGHT_VALUE; } if (x11_flags & XNegative) { gdk_flags |= EEL_GDK_X_NEGATIVE; } if (x11_flags & YNegative) { gdk_flags |= EEL_GDK_Y_NEGATIVE; }
return gdk_flags; }
static char * eel_gdk_rgba_as_hex_string (GdkRGBA color) { return g_strdup_printf ("%04X%04X%04X", (guint) (color.red * 65535), (guint) (color.green * 65535), (guint) (color.blue * 65535)); }
static char * eel_self_check_parse (const char *color_spec) { GdkRGBA color;
eel_gdk_rgba_parse_with_white_default (&color, color_spec); return eel_gdk_rgba_as_hex_string (color); }
static char * eel_self_check_gdk_rgb_to_color (guint32 color) { GdkRGBA result;
result = eel_gdk_rgb_to_rgba (color);
return eel_gdk_rgba_as_hex_string (result); }
void eel_self_check_gdk_extensions (void) { /* eel_gradient_new
References eel_gradient_new(), and FALSE.
EEL_CHECK_STRING_RESULT() [24/69]
EEL_CHECK_STRING_RESULT (eel_gradient_new("a", "a", FALSE) , "a")
References eel_gradient_new(), and FALSE.
EEL_CHECK_STRING_RESULT() [25/69]
EEL_CHECK_STRING_RESULT (eel_gradient_new("a", "a", TRUE) , "a")
References eel_gradient_new(), and TRUE.
EEL_CHECK_STRING_RESULT() [26/69]
EEL_CHECK_STRING_RESULT (eel_gradient_new("a", "b", FALSE) , "a-b")
References eel_gradient_new(), and FALSE.
EEL_CHECK_STRING_RESULT() [27/69]
EEL_CHECK_STRING_RESULT (eel_gradient_new("a", "b", TRUE) , "a-b:h")
References eel_gradient_new(), and TRUE.
EEL_CHECK_STRING_RESULT() [28/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_bottom_color_spec("", "") , "")
References eel_gradient_set_bottom_color_spec().
EEL_CHECK_STRING_RESULT() [29/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_bottom_color_spec("", "a") , "a")
References eel_gradient_set_bottom_color_spec().
EEL_CHECK_STRING_RESULT() [30/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_bottom_color_spec("a", "") , "a")
References eel_gradient_set_bottom_color_spec().
EEL_CHECK_STRING_RESULT() [31/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_bottom_color_spec("a", "a") , "a")
References eel_gradient_set_bottom_color_spec().
EEL_CHECK_STRING_RESULT() [32/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_bottom_color_spec("a", "b") , "a-b")
References eel_gradient_set_bottom_color_spec().
EEL_CHECK_STRING_RESULT() [33/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_bottom_color_spec("a-c:v", "b") , "a-b")
References eel_gradient_set_bottom_color_spec().
EEL_CHECK_STRING_RESULT() [34/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_bottom_color_spec("a-c:v", "c") , "a-c")
References eel_gradient_set_bottom_color_spec().
EEL_CHECK_STRING_RESULT() [35/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_bottom_color_spec("a:-b:h", "d") , "a:-d")
References eel_gradient_set_bottom_color_spec().
EEL_CHECK_STRING_RESULT() [36/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_left_color_spec("", "") , "")
References eel_gradient_set_left_color_spec().
EEL_CHECK_STRING_RESULT() [37/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_left_color_spec("", "a") , "a")
References eel_gradient_set_left_color_spec().
EEL_CHECK_STRING_RESULT() [38/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_left_color_spec("a", "") , "a")
References eel_gradient_set_left_color_spec().
EEL_CHECK_STRING_RESULT() [39/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_left_color_spec("a", "a") , "a")
References eel_gradient_set_left_color_spec().
EEL_CHECK_STRING_RESULT() [40/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_left_color_spec("a", "b") , "b-a:h")
References eel_gradient_set_left_color_spec().
EEL_CHECK_STRING_RESULT() [41/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_left_color_spec("a-c:v", "b") , "b-c:h")
References eel_gradient_set_left_color_spec().
EEL_CHECK_STRING_RESULT() [42/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_left_color_spec("a-c:v", "c") , "c")
References eel_gradient_set_left_color_spec().
EEL_CHECK_STRING_RESULT() [43/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_left_color_spec("a:-b:v", "d") , "d-b:h")
References eel_gradient_set_left_color_spec().
EEL_CHECK_STRING_RESULT() [44/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_right_color_spec("", "") , "")
References eel_gradient_set_right_color_spec().
EEL_CHECK_STRING_RESULT() [45/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_right_color_spec("", "a") , "a")
References eel_gradient_set_right_color_spec().
EEL_CHECK_STRING_RESULT() [46/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_right_color_spec("a", "") , "a")
References eel_gradient_set_right_color_spec().
EEL_CHECK_STRING_RESULT() [47/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_right_color_spec("a", "a") , "a")
References eel_gradient_set_right_color_spec().
EEL_CHECK_STRING_RESULT() [48/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_right_color_spec("a", "b") , "a-b:h")
References eel_gradient_set_right_color_spec().
EEL_CHECK_STRING_RESULT() [49/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_right_color_spec("a-c:v", "b") , "a-b:h")
References eel_gradient_set_right_color_spec().
EEL_CHECK_STRING_RESULT() [50/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_right_color_spec("a-c:v", "c") , "a-c:h")
References eel_gradient_set_right_color_spec().
EEL_CHECK_STRING_RESULT() [51/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_right_color_spec("a:-b:v", "d") , "a:-d:h")
References eel_gradient_set_right_color_spec().
EEL_CHECK_STRING_RESULT() [52/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_top_color_spec("", "") , "")
References eel_gradient_set_top_color_spec().
EEL_CHECK_STRING_RESULT() [53/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_top_color_spec("", "a") , "a")
References eel_gradient_set_top_color_spec().
EEL_CHECK_STRING_RESULT() [54/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_top_color_spec("a", "") , "a")
References eel_gradient_set_top_color_spec().
EEL_CHECK_STRING_RESULT() [55/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_top_color_spec("a", "a") , "a")
References eel_gradient_set_top_color_spec().
EEL_CHECK_STRING_RESULT() [56/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_top_color_spec("a", "b") , "b-a")
References eel_gradient_set_top_color_spec().
EEL_CHECK_STRING_RESULT() [57/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_top_color_spec("a-c:v", "b") , "b-c")
References eel_gradient_set_top_color_spec().
EEL_CHECK_STRING_RESULT() [58/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_top_color_spec("a-c:v", "c") , "c")
References eel_gradient_set_top_color_spec().
EEL_CHECK_STRING_RESULT() [59/69]
EEL_CHECK_STRING_RESULT (eel_gradient_set_top_color_spec("a:-b:h", "d") , "d-b")
References eel_gradient_set_top_color_spec().
EEL_CHECK_STRING_RESULT() [60/69]
EEL_CHECK_STRING_RESULT (eel_self_check_gdk_rgb_to_color(EEL_RGB_COLOR_BLACK) , "000000000000")
References EEL_RGB_COLOR_BLACK.
EEL_CHECK_STRING_RESULT() [61/69]
EEL_CHECK_STRING_RESULT (eel_self_check_gdk_rgb_to_color(EEL_RGB_COLOR_PACK(0x01, 0x23, 0x45)) , "010123234545")
References EEL_RGB_COLOR_PACK.
EEL_CHECK_STRING_RESULT() [62/69]
EEL_CHECK_STRING_RESULT (eel_self_check_gdk_rgb_to_color(EEL_RGB_COLOR_RED) , "FFFF00000000")
References EEL_RGB_COLOR_RED.
EEL_CHECK_STRING_RESULT() [63/69]
EEL_CHECK_STRING_RESULT (eel_self_check_gdk_rgb_to_color(EEL_RGB_COLOR_WHITE) , "FFFFFFFFFFFF")
References EEL_RGB_COLOR_WHITE.
EEL_CHECK_STRING_RESULT() [64/69]
EEL_CHECK_STRING_RESULT (eel_self_check_parse("") , "FFFFFFFFFFFF")
EEL_CHECK_STRING_RESULT() [65/69]
EEL_CHECK_STRING_RESULT (eel_self_check_parse("#012345") , "010123234545")
EEL_CHECK_STRING_RESULT() [66/69]
EEL_CHECK_STRING_RESULT (eel_self_check_parse("a") , "FFFFFFFFFFFF")
EEL_CHECK_STRING_RESULT() [67/69]
EEL_CHECK_STRING_RESULT (eel_self_check_parse("black") , "000000000000")
EEL_CHECK_STRING_RESULT() [68/69]
EEL_CHECK_STRING_RESULT (eel_self_check_parse("red") , "FFFF00000000")
EEL_CHECK_STRING_RESULT() [69/69]
EEL_CHECK_STRING_RESULT (eel_self_check_parse("white") , "FFFFFFFFFFFF")
eel_gdk_rgb_to_color_spec()
char * eel_gdk_rgb_to_color_spec (const guint32 color)
eel_gdk_rgb_to_color_spec @color: a gdk_rgb style value.
Converts from a gdk_rgb value style to a string color spec. The gdk_rgb color alpha channel is ignored.
Return value: a newly allocated color spec.
Definition at line 407 of file eel-gdk-extensions.c.
Referenced by eel_bg_get_desktop_color().
eel_gdk_rgb_to_rgba()
GdkRGBA eel_gdk_rgb_to_rgba (guint32 color)
eel_gdk_rgb_to_rgba @color: a gdk_rgb style value.
Converts from a gdk_rgb value style to a GdkRGBA one. The gdk_rgb color alpha channel is ignored.
Return value: A GdkRGBA structure version of the given RGB color.
Definition at line 385 of file eel-gdk-extensions.c.
eel_gdk_rgba_parse_with_white_default()
void eel_gdk_rgba_parse_with_white_default (GdkRGBA * color, const char * color_spec)
eel_gdk_rgba_parse_with_white_default @color: Pointer to place to put resulting color. @color_spec: A color spec, or NULL.
The same as gdk_rgba_parse, except sets the color to white if the spec. can't be parsed, instead of returning a boolean flag.
Definition at line 322 of file eel-gdk-extensions.c.
References FALSE, NULL, and TRUE.
eel_gdk_rgba_to_rgb()
guint32 eel_gdk_rgba_to_rgb (const GdkRGBA * color)
eel_gdk_rgba_to_rgb @color: A GdkRGBA style color. Returns: An rgb value.
Converts from a GdkRGBA style color to a gdk_rgb one. Alpha gets set to fully opaque
Definition at line 368 of file eel-gdk-extensions.c.
References eel_rgb16_to_rgb().
Referenced by eel_bg_get_desktop_color().
eel_gradient_get_end_color_spec()
char * eel_gradient_get_end_color_spec (const char * gradient_spec)
eel_gradient_get_end_color_spec @gradient_spec: A gradient spec. string.
Return the end color. This may be the entire gradient_spec if it's a solid color.
Definition at line 195 of file eel-gdk-extensions.c.
References eel_gradient_parse_one_color_spec(), and NULL.
Referenced by EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), and EEL_CHECK_STRING_RESULT().
eel_gradient_get_start_color_spec()
char * eel_gradient_get_start_color_spec (const char * gradient_spec)
eel_gradient_get_start_color_spec @gradient_spec: A gradient spec. string.
Return the start color. This may be the entire gradient_spec if it's a solid color.
Definition at line 182 of file eel-gdk-extensions.c.
References eel_gradient_parse_one_color_spec(), and NULL.
Referenced by EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), and EEL_CHECK_STRING_RESULT().
eel_gradient_is_gradient()
gboolean eel_gradient_is_gradient (const char * gradient_spec)
eel_gradient_is_gradient @gradient_spec: A gradient spec. string.
Return true if the spec. specifies a gradient instead of a solid color.
Definition at line 79 of file eel-gdk-extensions.c.
References eel_strchr(), and NULL.
Referenced by EEL_CHECK_BOOLEAN_RESULT(), EEL_CHECK_BOOLEAN_RESULT(), EEL_CHECK_BOOLEAN_RESULT(), EEL_CHECK_BOOLEAN_RESULT(), and EEL_CHECK_BOOLEAN_RESULT().
eel_gradient_is_horizontal()
gboolean eel_gradient_is_horizontal (const char * gradient_spec)
eel_gradient_is_horizontal @gradient_spec: A gradient spec. string.
Return true if the spec. specifies a horizontal gradient.
Definition at line 91 of file eel-gdk-extensions.c.
References eel_strlen().
eel_gradient_new()
char * eel_gradient_new (const char * start_color, const char * end_color, gboolean is_horizontal)
eel_gradient_new @start_color: Color for the top or left. @end_color: Color for the bottom or right. @is_horizontal: Direction of the gradient.
Create a string that combines the start and end colors along with the direction of the gradient in a standard format.
Definition at line 50 of file eel-gdk-extensions.c.
References eel_strcmp(), and NULL.
Referenced by eel_bg_get_desktop_color(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), and EEL_CHECK_STRING_RESULT().
eel_gradient_parse_one_color_spec()
char * eel_gradient_parse_one_color_spec (const char * spec, int * percent, const char ** next_spec)
Definition at line 119 of file eel-gdk-extensions.c.
References eel_strchr(), int(), and NULL.
Referenced by eel_gradient_get_end_color_spec(), and eel_gradient_get_start_color_spec().
eel_gradient_set_bottom_color_spec()
char * eel_gradient_set_bottom_color_spec (const char * gradient_spec, const char * bottom_color)
eel_gradient_set_bottom_color_spec @gradient_spec: A gradient spec. string. @bottom_color: Color spec. to replace bottom color with.
Changes the bottom color to what's passed in. This creates a vertical gradient.
Definition at line 304 of file eel-gdk-extensions.c.
References FALSE, NULL, and TRUE.
Referenced by eel_background_set_dropped_color(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), and EEL_CHECK_STRING_RESULT().
eel_gradient_set_left_color_spec()
char * eel_gradient_set_left_color_spec (const char * gradient_spec, const char * left_color)
eel_gradient_set_left_color_spec @gradient_spec: A gradient spec. string. @left_color: Color spec. to replace left color with.
Changes the left color to what's passed in. This creates a horizontal gradient.
Definition at line 250 of file eel-gdk-extensions.c.
References FALSE, NULL, and TRUE.
Referenced by eel_background_set_dropped_color(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), and EEL_CHECK_STRING_RESULT().
eel_gradient_set_right_color_spec()
char * eel_gradient_set_right_color_spec (const char * gradient_spec, const char * right_color)
eel_gradient_set_right_color_spec @gradient_spec: A gradient spec. string. @right_color: Color spec. to replace right color with.
Changes the right color to what's passed in. This creates a horizontal gradient.
Definition at line 286 of file eel-gdk-extensions.c.
References NULL, and TRUE.
Referenced by eel_background_set_dropped_color(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), and EEL_CHECK_STRING_RESULT().
eel_gradient_set_top_color_spec()
char * eel_gradient_set_top_color_spec (const char * gradient_spec, const char * top_color)
eel_gradient_set_top_color_spec @gradient_spec: A gradient spec. string. @top_color: Color spec. to replace top color with.
Changes the top color to what's passed in. This creates a vertical gradient.
Definition at line 268 of file eel-gdk-extensions.c.
References FALSE, and NULL.
Referenced by eel_background_set_dropped_color(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), EEL_CHECK_STRING_RESULT(), and EEL_CHECK_STRING_RESULT().
eel_rgb16_to_rgb()
guint32 eel_rgb16_to_rgb (gushort r, gushort g, gushort b)
Definition at line 348 of file eel-gdk-extensions.c.
References b.
Referenced by eel_gdk_rgba_to_rgb().