MATE Desktop Environment: eel-self-checks.h File Reference
eel-self-checks.h File Reference
#include <glib.h>
#include "eel-art-extensions.h"
Macros
#define EEL_CHECK_RESULT(type, expression, expected_value)
#define EEL_CHECK_BOOLEAN_RESULT(expression, expected_value)
#define EEL_CHECK_INTEGER_RESULT(expression, expected_value)
#define EEL_CHECK_DOUBLE_RESULT(expression, expected_value)
#define EEL_CHECK_STRING_RESULT(expression, expected_value)
#define EEL_CHECK_RECTANGLE_RESULT(expression, expected_x0, expected_y0, expected_x1, expected_y1)
#define EEL_CHECK_DIMENSIONS_RESULT(expression, expected_width, expected_height)
#define EEL_CHECK_POINT_RESULT(expression, expected_x, expected_y)
#define EEL_SELF_CHECK_FUNCTION_PROTOTYPE(function)
#define EEL_CALL_SELF_CHECK_FUNCTION(function)
Functions
void eel_exit_if_self_checks_failed (void)
void eel_before_check_function (const char *name)
void eel_after_check_function (void)
void eel_before_check (const char *expression, const char *file_name, int line_number)
void eel_after_check (void)
void eel_report_check_failure (char *result, char *expected)
void eel_check_boolean_result (gboolean result, gboolean expected_value)
void eel_check_integer_result (long result, long expected_value)
void eel_check_double_result (double result, double expected_value)
void eel_check_rectangle_result (EelIRect result, int expected_x0, int expected_y0, int expected_x1, int expected_y1)
void eel_check_dimensions_result (EelDimensions result, int expected_width, int expected_height)
void eel_check_point_result (EelIPoint result, int expected_x, int expected_y)
void eel_check_string_result (char *result, const char *expected_value)
Macro Definition Documentation
EEL_CALL_SELF_CHECK_FUNCTION
#define EEL_CALL_SELF_CHECK_FUNCTION (function)
Value:
eel_before_check_function (#function); \
function (); \
eel_after_check_function ();
Definition at line 96 of file eel-self-checks.h.
Referenced by caja_run_lib_self_checks(), and eel_run_lib_self_checks().
EEL_CHECK_BOOLEAN_RESULT
#define EEL_CHECK_BOOLEAN_RESULT (expression, expected_value)
Value:
EEL_CHECK_RESULT(boolean, expression, expected_value)
Definition at line 38 of file eel-self-checks.h.
Referenced by caja_self_check_directory(), caja_self_check_file(), eel_self_check_glib_extensions(), and eel_self_check_string().
EEL_CHECK_DIMENSIONS_RESULT
#define EEL_CHECK_DIMENSIONS_RESULT (expression, expected_width, expected_height)
Value:
G_STMT_START { \
    eel_before_check (#expression, __FILE__, __LINE__); \
    eel_check_dimensions_result (expression, expected_width, expected_height); \
} G_STMT_END
Definition at line 51 of file eel-self-checks.h.
EEL_CHECK_DOUBLE_RESULT
#define EEL_CHECK_DOUBLE_RESULT (expression, expected_value)
Value:
EEL_CHECK_RESULT(double, expression, expected_value)
Definition at line 42 of file eel-self-checks.h.
EEL_CHECK_INTEGER_RESULT
#define EEL_CHECK_INTEGER_RESULT (expression, expected_value)
Value:
EEL_CHECK_RESULT(integer, expression, expected_value)
Definition at line 40 of file eel-self-checks.h.
Referenced by caja_self_check_directory(), caja_self_check_file(), eel_self_check_glib_extensions(), and eel_self_check_string().
EEL_CHECK_POINT_RESULT
#define EEL_CHECK_POINT_RESULT (expression, expected_x, expected_y)
Value:
G_STMT_START { \
    eel_before_check (#expression, __FILE__, __LINE__); \
    eel_check_point_result (expression, expected_x, expected_y); \
} G_STMT_END
Definition at line 56 of file eel-self-checks.h.
EEL_CHECK_RECTANGLE_RESULT
#define EEL_CHECK_RECTANGLE_RESULT (expression, expected_x0, expected_y0, expected_x1, expected_y1)
Value:
G_STMT_START { \
    eel_before_check (#expression, __FILE__, __LINE__); \
    eel_check_rectangle_result (expression, expected_x0, expected_y0, expected_x1, expected_y1); \
} G_STMT_END
Definition at line 46 of file eel-self-checks.h.
EEL_CHECK_RESULT
#define EEL_CHECK_RESULT (type, expression, expected_value)
Value:
G_STMT_START { \
    eel_before_check (#expression, __FILE__, __LINE__); \
    eel_check_##type##_result (expression, expected_value); \
} G_STMT_END
Definition at line 32 of file eel-self-checks.h.
EEL_CHECK_STRING_RESULT
#define EEL_CHECK_STRING_RESULT (expression, expected_value)
Value:
EEL_CHECK_RESULT(string, expression, expected_value)
Definition at line 44 of file eel-self-checks.h.
Referenced by caja_self_check_file(), caja_self_check_file_operations(), caja_self_check_icon_container(), and eel_self_check_string().
EEL_SELF_CHECK_FUNCTION_PROTOTYPE
#define EEL_SELF_CHECK_FUNCTION_PROTOTYPE (function)
Value:
void function (void);
Definition at line 93 of file eel-self-checks.h.
Function Documentation
eel_after_check()
void eel_after_check (void)
Definition at line 98 of file eel-self-checks.c.
Referenced by eel_check_boolean_result(), eel_check_dimensions_result(), eel_check_double_result(), eel_check_integer_result(), eel_check_point_result(), eel_check_rectangle_result(), and eel_check_string_result().
eel_after_check_function()
void eel_after_check_function (void)
Definition at line 233 of file eel-self-checks.c.
eel_before_check()
void eel_before_check (const char * expression, const char * file_name, int line_number)
Definition at line 88 of file eel-self-checks.c.
eel_before_check_function()
void eel_before_check_function (const char * name)
Definition at line 227 of file eel-self-checks.c.
References name.
eel_check_boolean_result()
void eel_check_boolean_result (gboolean result, gboolean expected_value)
Definition at line 104 of file eel-self-checks.c.
References eel_after_check(), and eel_report_check_failure().
eel_check_dimensions_result()
void eel_check_dimensions_result (EelDimensions result, int expected_width, int expected_height)
Definition at line 141 of file eel-self-checks.c.
References eel_after_check(), eel_report_check_failure(), EelDimensions::height, and EelDimensions::width.
eel_check_double_result()
void eel_check_double_result (double result, double expected_value)
Definition at line 188 of file eel-self-checks.c.
References eel_after_check(), and eel_report_check_failure().
eel_check_integer_result()
void eel_check_integer_result (long result, long expected_value)
Definition at line 177 of file eel-self-checks.c.
References eel_after_check(), and eel_report_check_failure().
eel_check_point_result()
void eel_check_point_result (EelIPoint result, int expected_x, int expected_y)
Definition at line 159 of file eel-self-checks.c.
References eel_after_check(), eel_report_check_failure(), EelIPoint::x, and EelIPoint::y.
eel_check_rectangle_result()
void eel_check_rectangle_result (EelIRect result, int expected_x0, int expected_y0, int expected_x1, int expected_y1)
Definition at line 115 of file eel-self-checks.c.
References eel_after_check(), eel_report_check_failure(), EelIRect::x0, EelIRect::x1, EelIRect::y0, and EelIRect::y1.
eel_check_string_result()
void eel_check_string_result (char * result, const char * expected_value)
Definition at line 199 of file eel-self-checks.c.
References eel_after_check(), eel_report_check_failure(), and NULL.
eel_exit_if_self_checks_failed()
void eel_exit_if_self_checks_failed (void)
Definition at line 42 of file eel-self-checks.c.
Referenced by main().
eel_report_check_failure()
void eel_report_check_failure (char * result, char * expected)
Definition at line 55 of file eel-self-checks.c.
References NULL, and TRUE.
Referenced by eel_check_boolean_result(), eel_check_dimensions_result(), eel_check_double_result(), eel_check_integer_result(), eel_check_point_result(), eel_check_rectangle_result(), and eel_check_string_result().