MATE Desktop Environment: egg-array-float.h File Reference
egg-array-float.h File Reference
#include <glib.h>
Typedefs
typedef GArray EggArrayFloat
Functions
EggArrayFloat * egg_array_float_new (guint length)
void egg_array_float_free (EggArrayFloat *array)
gfloat egg_array_float_sum (EggArrayFloat *array)
EggArrayFloat * egg_array_float_compute_gaussian (guint length, gfloat sigma)
gfloat egg_array_float_compute_integral (EggArrayFloat *array, guint x1, guint x2)
gfloat egg_array_float_get_average (EggArrayFloat *array)
gboolean egg_array_float_print (EggArrayFloat *array)
EggArrayFloat * egg_array_float_convolve (EggArrayFloat *data, EggArrayFloat *kernel)
gfloat egg_array_float_get (EggArrayFloat *array, guint i)
void egg_array_float_set (EggArrayFloat *array, guint i, gfloat value)
EggArrayFloat * egg_array_float_remove_outliers (EggArrayFloat *data, guint length, gfloat sigma)
Typedef Documentation
EggArrayFloat
typedef GArray EggArrayFloat
Definition at line 31 of file egg-array-float.h.
Function Documentation
egg_array_float_compute_gaussian()
EggArrayFloat * egg_array_float_compute_gaussian (guint length, gfloat sigma)
egg_array_float_compute_gaussian:
@length: length of output array @sigma: sigma value Return value: Gaussian array
Create a set of Gaussian array of a specified size
Definition at line 137 of file egg-array-float.c.
References egg_array_float_free(), egg_array_float_new(), egg_array_float_sum(), and NULL.
egg_array_float_compute_integral()
gfloat egg_array_float_compute_integral (EggArrayFloat * array, guint x1, guint x2)
egg_array_float_compute_integral: @array: This class instance
Computes complete discrete integral of dataset. Will only work with a step size of one.
Definition at line 264 of file egg-array-float.c.
egg_array_float_convolve()
EggArrayFloat * egg_array_float_convolve (EggArrayFloat * data, EggArrayFloat * kernel)
egg_array_float_convolve:
@data: input array @kernel: kernel array Return value: Colvolved array, same length as data
Convolves an array with a kernel, and returns an array the same size. THIS FUNCTION IS REALLY SLOW...
Definition at line 225 of file egg-array-float.c.
References data, egg_array_float_new(), and idx.
egg_array_float_free()
void egg_array_float_free (EggArrayFloat * array)
egg_array_float_free:
@array: input array
Frees the array, deallocating data
Definition at line 102 of file egg-array-float.c.
References NULL, and TRUE.
Referenced by egg_array_float_compute_gaussian().
egg_array_float_get()
gfloat egg_array_float_get (EggArrayFloat * array, guint i)
egg_array_float_get:
@array: input array
Definition at line 76 of file egg-array-float.c.
egg_array_float_get_average()
gfloat egg_array_float_get_average (EggArrayFloat * array)
egg_array_float_get_average: @array: This class instance
Gets the average value.
Definition at line 115 of file egg-array-float.c.
egg_array_float_new()
EggArrayFloat * egg_array_float_new (guint length)
egg_array_float_new:
@length: length of array Return value: Allocate array
Creates a new size array which is zeroed. Free with g_array_free();
Definition at line 57 of file egg-array-float.c.
References FALSE, and TRUE.
Referenced by egg_array_float_compute_gaussian(), egg_array_float_convolve(), and egg_array_float_remove_outliers().
egg_array_float_print()
gboolean egg_array_float_print (EggArrayFloat * array)
egg_array_float_print:
@array: input array
Print the array
Definition at line 202 of file egg-array-float.c.
References TRUE.
egg_array_float_remove_outliers()
EggArrayFloat * egg_array_float_remove_outliers (EggArrayFloat * data, guint length, gfloat sigma)
egg_array_float_remove_outliers:
@data: input array @size: size to analyse @sigma: sigma for standard deviation Return value: Data with outliers removed
Compares local sections of the data, removing outliers if they fall outside of sigma, and using the average of the other points in its place.
Definition at line 306 of file egg-array-float.c.
References data, egg_array_float_new(), and NULL.
egg_array_float_set()
void egg_array_float_set (EggArrayFloat * array, guint i, gfloat value)
egg_array_float_set:
@array: input array
Definition at line 89 of file egg-array-float.c.
egg_array_float_sum()
gfloat egg_array_float_sum (EggArrayFloat * array)
egg_array_float_sum:
@array: input array
Sum the elements of the array
Definition at line 182 of file egg-array-float.c.
Referenced by egg_array_float_compute_gaussian().