MATE Desktop Environment: egg-console-kit.c File Reference
egg-console-kit.c File Reference
#include "config.h"
#include <string.h>
#include <unistd.h>
#include <stdio.h>
#include <glib.h>
#include <dbus/dbus-glib.h>
#include <dbus/dbus.h>
#include "egg-console-kit.h"
Macros
#define CONSOLEKIT_NAME "org.freedesktop.ConsoleKit"
#define CONSOLEKIT_PATH "/org/freedesktop/ConsoleKit"
#define CONSOLEKIT_INTERFACE "org.freedesktop.ConsoleKit"
#define CONSOLEKIT_MANAGER_PATH "/org/freedesktop/ConsoleKit/Manager"
#define CONSOLEKIT_MANAGER_INTERFACE "org.freedesktop.ConsoleKit.Manager"
#define CONSOLEKIT_SEAT_INTERFACE "org.freedesktop.ConsoleKit.Seat"
#define CONSOLEKIT_SESSION_INTERFACE "org.freedesktop.ConsoleKit.Session"
Enumerations
enum { EGG_CONSOLE_KIT_ACTIVE_CHANGED , EGG_CONSOLE_KIT_LAST_SIGNAL }
Functions
gboolean egg_console_kit_restart (EggConsoleKit *console, GError **error)
gboolean egg_console_kit_stop (EggConsoleKit *console, GError **error)
gboolean egg_console_kit_suspend (EggConsoleKit *console, GError **error)
gboolean egg_console_kit_hibernate (EggConsoleKit *console, GError **error)
gboolean egg_console_kit_can_stop (EggConsoleKit *console, gboolean *can_stop, GError **error)
gboolean egg_console_kit_can_restart (EggConsoleKit *console, gboolean *can_restart, GError **error)
gboolean egg_console_kit_can_suspend (EggConsoleKit *console, gboolean *can_suspend, GError **error)
gboolean egg_console_kit_can_hibernate (EggConsoleKit *console, gboolean *can_hibernate, GError **error)
gboolean egg_console_kit_is_local (EggConsoleKit *console)
gboolean egg_console_kit_is_active (EggConsoleKit *console)
EggConsoleKit * egg_console_kit_new (void)
Macro Definition Documentation
CONSOLEKIT_INTERFACE
#define CONSOLEKIT_INTERFACE "org.freedesktop.ConsoleKit"
Definition at line 38 of file egg-console-kit.c.
CONSOLEKIT_MANAGER_INTERFACE
#define CONSOLEKIT_MANAGER_INTERFACE "org.freedesktop.ConsoleKit.Manager"
Definition at line 41 of file egg-console-kit.c.
CONSOLEKIT_MANAGER_PATH
#define CONSOLEKIT_MANAGER_PATH "/org/freedesktop/ConsoleKit/Manager"
Definition at line 40 of file egg-console-kit.c.
CONSOLEKIT_NAME
#define CONSOLEKIT_NAME "org.freedesktop.ConsoleKit"
Definition at line 36 of file egg-console-kit.c.
CONSOLEKIT_PATH
#define CONSOLEKIT_PATH "/org/freedesktop/ConsoleKit"
Definition at line 37 of file egg-console-kit.c.
CONSOLEKIT_SEAT_INTERFACE
#define CONSOLEKIT_SEAT_INTERFACE "org.freedesktop.ConsoleKit.Seat"
Definition at line 42 of file egg-console-kit.c.
CONSOLEKIT_SESSION_INTERFACE
#define CONSOLEKIT_SESSION_INTERFACE "org.freedesktop.ConsoleKit.Session"
Definition at line 43 of file egg-console-kit.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EGG_CONSOLE_KIT_ACTIVE_CHANGED
EGG_CONSOLE_KIT_LAST_SIGNAL
Definition at line 53 of file egg-console-kit.c.
Function Documentation
egg_console_kit_can_hibernate()
gboolean egg_console_kit_can_hibernate (EggConsoleKit * console, gboolean * can_hibernate, GError ** error)
egg_console_kit_can_hibernate:
Definition at line 246 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, and EggConsoleKit::priv.
Referenced by gpm_control_hibernate().
egg_console_kit_can_restart()
gboolean egg_console_kit_can_restart (EggConsoleKit * console, gboolean * can_restart, GError ** error)
egg_console_kit_can_restart:
Definition at line 188 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, EggConsoleKit::priv, and TRUE.
egg_console_kit_can_stop()
gboolean egg_console_kit_can_stop (EggConsoleKit * console, gboolean * can_stop, GError ** error)
egg_console_kit_can_stop:
Definition at line 161 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, EggConsoleKit::priv, and TRUE.
egg_console_kit_can_suspend()
gboolean egg_console_kit_can_suspend (EggConsoleKit * console, gboolean * can_suspend, GError ** error)
egg_console_kit_can_suspend:
Definition at line 215 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, and EggConsoleKit::priv.
Referenced by gpm_control_suspend().
egg_console_kit_hibernate()
gboolean egg_console_kit_hibernate (EggConsoleKit * console, GError ** error)
egg_console_kit_hibernate:
Definition at line 137 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, EggConsoleKit::priv, and TRUE.
Referenced by gpm_control_hibernate().
egg_console_kit_is_active()
gboolean egg_console_kit_is_active (EggConsoleKit * console)
egg_console_kit_is_active:
Return value: Returns whether the session is active on the Seat that it is attached to.
Definition at line 311 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, and EggConsoleKit::priv.
egg_console_kit_is_local()
gboolean egg_console_kit_is_local (EggConsoleKit * console)
egg_console_kit_is_local:
Return value: Returns whether the session is local
Definition at line 276 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, and EggConsoleKit::priv.
egg_console_kit_new()
EggConsoleKit * egg_console_kit_new (void)
egg_console_kit_new:
Return value: a new EggConsoleKit object.
Definition at line 458 of file egg-console-kit.c.
References EGG_CONSOLE_KIT, EGG_TYPE_CONSOLE_KIT, and NULL.
Referenced by gpm_control_hibernate(), gpm_control_shutdown(), and gpm_control_suspend().
egg_console_kit_restart()
gboolean egg_console_kit_restart (EggConsoleKit * console, GError ** error)
egg_console_kit_restart:
Definition at line 67 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, and EggConsoleKit::priv.
egg_console_kit_stop()
gboolean egg_console_kit_stop (EggConsoleKit * console, GError ** error)
egg_console_kit_stop:
Definition at line 90 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, and EggConsoleKit::priv.
Referenced by gpm_control_shutdown().
egg_console_kit_suspend()
gboolean egg_console_kit_suspend (EggConsoleKit * console, GError ** error)
egg_console_kit_suspend:
Definition at line 113 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, EggConsoleKit::priv, and TRUE.
Referenced by gpm_control_suspend().