MATE Desktop Environment: egg-idletime.c File Reference
egg-idletime.c File Reference
#include <glib.h>
#include <X11/Xlib.h>
#include <X11/extensions/sync.h>
#include <gdk/gdkx.h>
#include <gdk/gdk.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "egg-idletime.h"
Enumerations
enum { SIGNAL_ALARM_EXPIRED , SIGNAL_RESET , LAST_SIGNAL }
enum EggIdletimeAlarmType { EGG_IDLETIME_ALARM_TYPE_POSITIVE , EGG_IDLETIME_ALARM_TYPE_NEGATIVE , EGG_IDLETIME_ALARM_TYPE_DISABLED }
Functions
gint64 egg_idletime_get_time (EggIdletime *idletime)
void egg_idletime_alarm_reset_all (EggIdletime *idletime)
gboolean egg_idletime_alarm_set (EggIdletime *idletime, guint id, guint timeout)
gboolean egg_idletime_alarm_remove (EggIdletime *idletime, guint id)
EggIdletime * egg_idletime_new (void)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SIGNAL_ALARM_EXPIRED
SIGNAL_RESET
LAST_SIGNAL
Definition at line 58 of file egg-idletime.c.
EggIdletimeAlarmType
enum EggIdletimeAlarmType
Enumerator
EGG_IDLETIME_ALARM_TYPE_POSITIVE
EGG_IDLETIME_ALARM_TYPE_NEGATIVE
EGG_IDLETIME_ALARM_TYPE_DISABLED
Definition at line 64 of file egg-idletime.c.
Function Documentation
egg_idletime_alarm_remove()
gboolean egg_idletime_alarm_remove (EggIdletime * idletime, guint id)
egg_idletime_alarm_free:
Definition at line 343 of file egg-idletime.c.
References EGG_IS_IDLETIME, FALSE, NULL, and TRUE.
Referenced by gpm_idle_set_timeout_dim().
egg_idletime_alarm_reset_all()
void egg_idletime_alarm_reset_all (EggIdletime * idletime)
egg_idletime_alarm_reset_all:
Definition at line 141 of file egg-idletime.c.
References EGG_IDLETIME_ALARM_TYPE_DISABLED, EGG_IDLETIME_ALARM_TYPE_POSITIVE, EGG_IS_IDLETIME, FALSE, EggIdletime::priv, and SIGNAL_RESET.
egg_idletime_alarm_set()
gboolean egg_idletime_alarm_set (EggIdletime * idletime, guint id, guint timeout)
egg_idletime_alarm_set:
Definition at line 296 of file egg-idletime.c.
References EGG_IDLETIME_ALARM_TYPE_POSITIVE, EGG_IS_IDLETIME, FALSE, NULL, EggIdletime::priv, and TRUE.
Referenced by gpm_idle_set_timeout_dim().
egg_idletime_get_time()
gint64 egg_idletime_get_time (EggIdletime * idletime)
egg_idletime_get_time:
Definition at line 88 of file egg-idletime.c.
References EggIdletime::priv.
Referenced by gpm_idle_set_timeout_dim().
egg_idletime_new()
EggIdletime * egg_idletime_new (void)
egg_idletime_new:
Definition at line 460 of file egg-idletime.c.
References EGG_IDLETIME, EGG_IDLETIME_TYPE, and NULL.