MATE Desktop Environment: egg-test.h File Reference
egg-test.h File Reference
#include <glib.h>
#include <string.h>
Typedefs
typedef struct EggTest EggTest
Functions
gboolean egg_test_start (EggTest *test, const gchar *name)
void egg_test_end (EggTest *test)
void egg_test_title (EggTest *test, const gchar *format,...)
void egg_test_title_assert (EggTest *test, const gchar *text, gboolean value)
void egg_test_assert (EggTest *test, gboolean value)
void egg_test_success (EggTest *test, const gchar *format,...)
void egg_test_failed (EggTest *test, const gchar *format,...) G_GNUC_NORETURN
EggTest * egg_test_init (void)
gint egg_test_finish (EggTest *test)
guint egg_test_elapsed (EggTest *test)
void egg_test_loop_quit (EggTest *test)
void egg_test_loop_wait (EggTest *test, guint timeout)
void egg_test_loop_check (EggTest *test)
void egg_test_set_user_data (EggTest *test, gpointer user_data)
gpointer egg_test_get_user_data (EggTest *test)
gchar * egg_test_get_data_file (const gchar *filename)
Typedef Documentation
EggTest
typedef struct EggTest EggTest
Definition at line 29 of file egg-test.h.
Function Documentation
egg_test_assert()
void egg_test_assert (EggTest * test, gboolean value)
egg_test_assert:
Definition at line 291 of file egg-test.c.
References egg_test_failed(), egg_test_success(), NULL, and test.
egg_test_elapsed()
guint egg_test_elapsed (EggTest * test)
egg_test_elapsed:
Returns: time in ms
Definition at line 160 of file egg-test.c.
References NULL, and test.
Referenced by egg_test_loop_check().
egg_test_end()
void egg_test_end (EggTest * test)
egg_test_end:
Definition at line 186 of file egg-test.c.
References FALSE, and test.
egg_test_failed()
void egg_test_failed (EggTest * test, const gchar * format, ...)
egg_test_failed:
Definition at line 264 of file egg-test.c.
References NULL, and test.
Referenced by egg_test_assert(), egg_test_loop_check(), and egg_test_title_assert().
egg_test_finish()
gint egg_test_finish (EggTest * test)
egg_test_finish:
Definition at line 135 of file egg-test.c.
References test.
Referenced by main().
egg_test_get_data_file()
gchar * egg_test_get_data_file (const gchar * filename)
egg_test_get_data_file:
Definition at line 316 of file egg-test.c.
References NULL.
egg_test_get_user_data()
gpointer egg_test_get_user_data (EggTest * test)
egg_test_get_user_data:
Definition at line 126 of file egg-test.c.
References test.
egg_test_init()
EggTest * egg_test_init (void)
egg_test_init:
Definition at line 48 of file egg-test.c.
References FALSE, NULL, and test.
Referenced by main().
egg_test_loop_check()
void egg_test_loop_check (EggTest * test)
egg_test_loop_check:
Definition at line 102 of file egg-test.c.
References egg_test_elapsed(), egg_test_failed(), egg_test_success(), egg_test_title(), and test.
egg_test_loop_quit()
void egg_test_loop_quit (EggTest * test)
egg_test_loop_quit:
Definition at line 67 of file egg-test.c.
References test.
egg_test_loop_wait()
void egg_test_loop_wait (EggTest * test, guint timeout)
egg_test_loop_wait:
Definition at line 92 of file egg-test.c.
References test.
egg_test_set_user_data()
void egg_test_set_user_data (EggTest * test, gpointer user_data)
egg_test_set_user_data:
Definition at line 117 of file egg-test.c.
References test, and user_data.
egg_test_start()
gboolean egg_test_start (EggTest * test, const gchar * name)
egg_test_start:
Definition at line 171 of file egg-test.c.
References name, test, and TRUE.
egg_test_success()
void egg_test_success (EggTest * test, const gchar * format, ...)
egg_test_success:
Definition at line 236 of file egg-test.c.
References FALSE, NULL, and test.
Referenced by egg_test_assert(), egg_test_loop_check(), and egg_test_title_assert().
egg_test_title()
void egg_test_title (EggTest * test, const gchar * format, ...)
egg_test_title:
Definition at line 208 of file egg-test.c.
References NULL, test, and TRUE.
Referenced by egg_test_loop_check(), and egg_test_title_assert().
egg_test_title_assert()
void egg_test_title_assert (EggTest * test, const gchar * text, gboolean value)
egg_test_title_assert:
Definition at line 303 of file egg-test.c.
References egg_test_failed(), egg_test_success(), egg_test_title(), NULL, and test.