MATE Desktop Environment: egg-console-kit.h File Reference
egg-console-kit.h File Reference
#include <glib-object.h>
Classes
struct EggConsoleKit
struct EggConsoleKitClass
Macros
#define EGG_TYPE_CONSOLE_KIT (egg_console_kit_get_type ())
#define EGG_CONSOLE_KIT(o)
#define EGG_CONSOLE_KIT_CLASS(k)
#define EGG_IS_CONSOLE_KIT(o)
#define EGG_IS_CONSOLE_KIT_CLASS(k)
#define EGG_CONSOLE_KIT_GET_CLASS(o)
#define EGG_CONSOLE_KIT_ERROR (egg_console_kit_error_quark ())
#define EGG_CONSOLE_KIT_TYPE_ERROR (egg_console_kit_error_get_type ())
Typedefs
typedef struct EggConsoleKitPrivate EggConsoleKitPrivate
Functions
GType egg_console_kit_get_type (void)
EggConsoleKit * egg_console_kit_new (void)
gboolean egg_console_kit_is_local (EggConsoleKit *console)
gboolean egg_console_kit_is_active (EggConsoleKit *console)
gboolean egg_console_kit_stop (EggConsoleKit *console, GError **error)
gboolean egg_console_kit_restart (EggConsoleKit *console, GError **error)
gboolean egg_console_kit_suspend (EggConsoleKit *console, GError **error)
gboolean egg_console_kit_hibernate (EggConsoleKit *console, GError **error)
gboolean egg_console_kit_can_stop (EggConsoleKit *console, gboolean *can_stop, GError **error)
gboolean egg_console_kit_can_restart (EggConsoleKit *console, gboolean *can_restart, GError **error)
gboolean egg_console_kit_can_suspend (EggConsoleKit *console, gboolean *can_restart, GError **error)
gboolean egg_console_kit_can_hibernate (EggConsoleKit *console, gboolean *can_restart, GError **error)
Macro Definition Documentation
EGG_CONSOLE_KIT
#define EGG_CONSOLE_KIT (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), EGG_TYPE_CONSOLE_KIT, EggConsoleKit))
Definition at line 31 of file egg-console-kit.h.
Referenced by egg_console_kit_new().
EGG_CONSOLE_KIT_CLASS
#define EGG_CONSOLE_KIT_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST((k), EGG_TYPE_CONSOLE_KIT, EggConsoleKitClass))
Definition at line 32 of file egg-console-kit.h.
EGG_CONSOLE_KIT_ERROR
#define EGG_CONSOLE_KIT_ERROR (egg_console_kit_error_quark ())
Definition at line 36 of file egg-console-kit.h.
EGG_CONSOLE_KIT_GET_CLASS
#define EGG_CONSOLE_KIT_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), EGG_TYPE_CONSOLE_KIT, EggConsoleKitClass))
Definition at line 35 of file egg-console-kit.h.
EGG_CONSOLE_KIT_TYPE_ERROR
#define EGG_CONSOLE_KIT_TYPE_ERROR (egg_console_kit_error_get_type ())
Definition at line 37 of file egg-console-kit.h.
EGG_IS_CONSOLE_KIT
#define EGG_IS_CONSOLE_KIT (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), EGG_TYPE_CONSOLE_KIT))
Definition at line 33 of file egg-console-kit.h.
Referenced by egg_console_kit_can_hibernate(), egg_console_kit_can_restart(), egg_console_kit_can_stop(), egg_console_kit_can_suspend(), egg_console_kit_hibernate(), egg_console_kit_is_active(), egg_console_kit_is_local(), egg_console_kit_restart(), egg_console_kit_stop(), and egg_console_kit_suspend().
EGG_IS_CONSOLE_KIT_CLASS
#define EGG_IS_CONSOLE_KIT_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), EGG_TYPE_CONSOLE_KIT))
Definition at line 34 of file egg-console-kit.h.
EGG_TYPE_CONSOLE_KIT
#define EGG_TYPE_CONSOLE_KIT (egg_console_kit_get_type ())
Definition at line 30 of file egg-console-kit.h.
Referenced by egg_console_kit_new().
Typedef Documentation
EggConsoleKitPrivate
typedef struct EggConsoleKitPrivate EggConsoleKitPrivate
Definition at line 39 of file egg-console-kit.h.
Function Documentation
egg_console_kit_can_hibernate()
gboolean egg_console_kit_can_hibernate (EggConsoleKit * console, gboolean * can_hibernate, GError ** error)
egg_console_kit_can_hibernate:
Definition at line 246 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, and EggConsoleKit::priv.
Referenced by gpm_control_hibernate().
egg_console_kit_can_restart()
gboolean egg_console_kit_can_restart (EggConsoleKit * console, gboolean * can_restart, GError ** error)
egg_console_kit_can_restart:
Definition at line 188 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, EggConsoleKit::priv, and TRUE.
egg_console_kit_can_stop()
gboolean egg_console_kit_can_stop (EggConsoleKit * console, gboolean * can_stop, GError ** error)
egg_console_kit_can_stop:
Definition at line 161 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, EggConsoleKit::priv, and TRUE.
egg_console_kit_can_suspend()
gboolean egg_console_kit_can_suspend (EggConsoleKit * console, gboolean * can_suspend, GError ** error)
egg_console_kit_can_suspend:
Definition at line 215 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, and EggConsoleKit::priv.
Referenced by gpm_control_suspend().
egg_console_kit_get_type()
GType egg_console_kit_get_type (void)
References error.
egg_console_kit_hibernate()
gboolean egg_console_kit_hibernate (EggConsoleKit * console, GError ** error)
egg_console_kit_hibernate:
Definition at line 137 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, EggConsoleKit::priv, and TRUE.
Referenced by gpm_control_hibernate().
egg_console_kit_is_active()
gboolean egg_console_kit_is_active (EggConsoleKit * console)
egg_console_kit_is_active:
Return value: Returns whether the session is active on the Seat that it is attached to.
Definition at line 311 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, and EggConsoleKit::priv.
egg_console_kit_is_local()
gboolean egg_console_kit_is_local (EggConsoleKit * console)
egg_console_kit_is_local:
Return value: Returns whether the session is local
Definition at line 276 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, and EggConsoleKit::priv.
egg_console_kit_new()
EggConsoleKit * egg_console_kit_new (void)
egg_console_kit_new:
Return value: a new EggConsoleKit object.
Definition at line 458 of file egg-console-kit.c.
References EGG_CONSOLE_KIT, EGG_TYPE_CONSOLE_KIT, and NULL.
Referenced by gpm_control_hibernate(), gpm_control_shutdown(), and gpm_control_suspend().
egg_console_kit_restart()
gboolean egg_console_kit_restart (EggConsoleKit * console, GError ** error)
egg_console_kit_restart:
Definition at line 67 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, and EggConsoleKit::priv.
egg_console_kit_stop()
gboolean egg_console_kit_stop (EggConsoleKit * console, GError ** error)
egg_console_kit_stop:
Definition at line 90 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, and EggConsoleKit::priv.
Referenced by gpm_control_shutdown().
egg_console_kit_suspend()
gboolean egg_console_kit_suspend (EggConsoleKit * console, GError ** error)
egg_console_kit_suspend:
Definition at line 113 of file egg-console-kit.c.
References EGG_IS_CONSOLE_KIT, error, FALSE, NULL, EggConsoleKit::priv, and TRUE.
Referenced by gpm_control_suspend().