MATE Desktop Environment: eggfileformatchooser.c File Reference
eggfileformatchooser.c File Reference
#include "eggfileformatchooser.h"
#include "egg-macros.h"
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <string.h>
#include <ctype.h>
Typedefs
typedef struct _EggFileFormatFilterInfo EggFileFormatFilterInfo
typedef struct _EggFileFormatSearch EggFileFormatSearch
Enumerations
enum {
MODEL_COLUMN_ID , MODEL_COLUMN_NAME , MODEL_COLUMN_ICON , MODEL_COLUMN_EXTENSIONS ,
MODEL_COLUMN_FILTER , MODEL_COLUMN_DATA , MODEL_COLUMN_DESTROY
}
enum { SIGNAL_SELECTION_CHANGED , SIGNAL_LAST }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (EggFileFormatChooser, egg_file_format_chooser, GTK_TYPE_EXPANDER)
GtkWidget * egg_file_format_chooser_new (void)
guint egg_file_format_chooser_add_format (EggFileFormatChooser *self, guint parent, const gchar *name, const gchar *icon,...)
void egg_file_format_chooser_add_pixbuf_formats (EggFileFormatChooser *self, guint parent G_GNUC_UNUSED, guint **formats)
void egg_file_format_chooser_remove_format (EggFileFormatChooser *self, guint format)
void egg_file_format_chooser_set_format (EggFileFormatChooser *self, guint format)
guint egg_file_format_chooser_get_format (EggFileFormatChooser *self, const gchar *filename)
void egg_file_format_chooser_set_format_data (EggFileFormatChooser *self, guint format, gpointer data, GDestroyNotify destroy)
gpointer egg_file_format_chooser_get_format_data (EggFileFormatChooser *self, guint format)
gchar * egg_file_format_chooser_append_extension (EggFileFormatChooser *self, const gchar *filename, guint format)
void egg_file_format_chooser_emit_size_changed (EggFileFormatChooser *self)
Typedef Documentation
EggFileFormatFilterInfo
typedef struct _EggFileFormatFilterInfo EggFileFormatFilterInfo
Definition at line 27 of file eggfileformatchooser.c.
EggFileFormatSearch
typedef struct _EggFileFormatSearch EggFileFormatSearch
Definition at line 28 of file eggfileformatchooser.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MODEL_COLUMN_ID
MODEL_COLUMN_NAME
MODEL_COLUMN_ICON
MODEL_COLUMN_EXTENSIONS
MODEL_COLUMN_FILTER
MODEL_COLUMN_DATA
MODEL_COLUMN_DESTROY
Definition at line 30 of file eggfileformatchooser.c.
anonymous enum
anonymous enum
Enumerator
SIGNAL_SELECTION_CHANGED
SIGNAL_LAST
Definition at line 41 of file eggfileformatchooser.c.
Function Documentation
egg_file_format_chooser_add_format()
guint egg_file_format_chooser_add_format (EggFileFormatChooser * self, guint parent, const gchar * name, const gchar * icon, ...)
Definition at line 853 of file eggfileformatchooser.c.
References EGG_IS_FILE_FORMAT_CHOOSER, name, NULL, and TRUE.
egg_file_format_chooser_add_pixbuf_formats()
void egg_file_format_chooser_add_pixbuf_formats (EggFileFormatChooser * self, guint parent G_GNUC_UNUSED, guint ** formats)
Definition at line 927 of file eggfileformatchooser.c.
References egg_file_format_chooser_set_format_data(), EGG_IS_FILE_FORMAT_CHOOSER, name, and NULL.
Referenced by egg_file_format_chooser_get_type().
egg_file_format_chooser_append_extension()
gchar * egg_file_format_chooser_append_extension (EggFileFormatChooser * self, const gchar * filename, guint format)
Definition at line 1138 of file eggfileformatchooser.c.
References egg_file_format_chooser_get_format(), EGG_IS_FILE_FORMAT_CHOOSER, FALSE, MODEL_COLUMN_EXTENSIONS, NULL, _EggFileFormatChooser::priv, and strchr.
Referenced by egg_file_format_chooser_get_type().
egg_file_format_chooser_emit_size_changed()
void egg_file_format_chooser_emit_size_changed (EggFileFormatChooser * self)
Definition at line 1199 of file eggfileformatchooser.c.
References _EggFileFormatChooser::priv.
Referenced by egg_file_format_chooser_get_type().
egg_file_format_chooser_get_format()
guint egg_file_format_chooser_get_format (EggFileFormatChooser * self, const gchar * filename)
Definition at line 1061 of file eggfileformatchooser.c.
References EGG_IS_FILE_FORMAT_CHOOSER, FALSE, MODEL_COLUMN_ID, NULL, _EggFileFormatChooser::priv, and strrchr.
Referenced by egg_file_format_chooser_append_extension(), and egg_file_format_chooser_get_type().
egg_file_format_chooser_get_format_data()
gpointer egg_file_format_chooser_get_format_data (EggFileFormatChooser * self, guint format)
Definition at line 1114 of file eggfileformatchooser.c.
References data, EGG_IS_FILE_FORMAT_CHOOSER, FALSE, MODEL_COLUMN_DATA, NULL, and _EggFileFormatChooser::priv.
Referenced by egg_file_format_chooser_get_type().
egg_file_format_chooser_new()
GtkWidget * egg_file_format_chooser_new (void)
Definition at line 796 of file eggfileformatchooser.c.
References EGG_TYPE_FILE_FORMAT_CHOOSER, and NULL.
egg_file_format_chooser_remove_format()
void egg_file_format_chooser_remove_format (EggFileFormatChooser * self, guint format)
Definition at line 982 of file eggfileformatchooser.c.
References data, EGG_IS_FILE_FORMAT_CHOOSER, FALSE, MODEL_COLUMN_DATA, MODEL_COLUMN_DESTROY, MODEL_COLUMN_FILTER, NULL, and _EggFileFormatChooser::priv.
Referenced by egg_file_format_chooser_get_type().
egg_file_format_chooser_set_format()
void egg_file_format_chooser_set_format (EggFileFormatChooser * self, guint format)
Definition at line 1025 of file eggfileformatchooser.c.
References EGG_IS_FILE_FORMAT_CHOOSER, FALSE, and _EggFileFormatChooser::priv.
Referenced by egg_file_format_chooser_get_type().
egg_file_format_chooser_set_format_data()
void egg_file_format_chooser_set_format_data (EggFileFormatChooser * self, guint format, gpointer data, GDestroyNotify destroy)
Definition at line 1090 of file eggfileformatchooser.c.
References data, EGG_IS_FILE_FORMAT_CHOOSER, FALSE, MODEL_COLUMN_DATA, MODEL_COLUMN_DESTROY, and _EggFileFormatChooser::priv.
Referenced by egg_file_format_chooser_add_pixbuf_formats(), and egg_file_format_chooser_get_type().
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (EggFileFormatChooser , egg_file_format_chooser , GTK_TYPE_EXPANDER)
References name, and NULL.