MATE Desktop Environment: eggfileformatchooser.h File Reference
eggfileformatchooser.h File Reference
#include <gtk/gtk.h>
Classes
struct _EggFileFormatChooser
struct _EggFileFormatChooserClass
Macros
#define EGG_TYPE_FILE_FORMAT_CHOOSER (egg_file_format_chooser_get_type())
#define EGG_FILE_FORMAT_CHOOSER(obj)
#define EGG_FILE_FORMAT_CHOOSER_CLASS(klass)
#define EGG_IS_FILE_FORMAT_CHOOSER(obj)
#define EGG_IS_FILE_FORMAT_CHOOSER_CLASS(obj)
#define EGG_FILE_FORMAT_CHOOSER_GET_CLASS(obj)
Typedefs
typedef struct _EggFileFormatChooser EggFileFormatChooser
typedef struct _EggFileFormatChooserClass EggFileFormatChooserClass
typedef struct _EggFileFormatChooserPrivate EggFileFormatChooserPrivate
Functions
GType egg_file_format_chooser_get_type (void)
GtkWidget * egg_file_format_chooser_new (void)
guint egg_file_format_chooser_add_format (EggFileFormatChooser *self, guint parent, const gchar *name, const gchar *icon,...)
void egg_file_format_chooser_add_pixbuf_formats (EggFileFormatChooser *self, guint parent, guint **formats)
void egg_file_format_chooser_remove_format (EggFileFormatChooser *self, guint format)
void egg_file_format_chooser_set_format (EggFileFormatChooser *self, guint format)
guint egg_file_format_chooser_get_format (EggFileFormatChooser *self, const gchar *filename)
void egg_file_format_chooser_set_format_data (EggFileFormatChooser *self, guint format, gpointer data, GDestroyNotify destroy)
gpointer egg_file_format_chooser_get_format_data (EggFileFormatChooser *self, guint format)
gchar * egg_file_format_chooser_append_extension (EggFileFormatChooser *self, const gchar *filename, guint format)
void egg_file_format_chooser_emit_size_changed (EggFileFormatChooser *self)
Macro Definition Documentation
EGG_FILE_FORMAT_CHOOSER
#define EGG_FILE_FORMAT_CHOOSER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST(obj, EGG_TYPE_FILE_FORMAT_CHOOSER, EggFileFormatChooser))
Definition at line 27 of file eggfileformatchooser.h.
EGG_FILE_FORMAT_CHOOSER_CLASS
#define EGG_FILE_FORMAT_CHOOSER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST(klass, EGG_TYPE_FILE_FORMAT_CHOOSER, EggFileFormatChooserClass))
Definition at line 28 of file eggfileformatchooser.h.
EGG_FILE_FORMAT_CHOOSER_GET_CLASS
#define EGG_FILE_FORMAT_CHOOSER_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS((obj), EGG_TYPE_FILE_FORMAT_CHOOSER, EggFileFormatChooserClass))
Definition at line 31 of file eggfileformatchooser.h.
EGG_IS_FILE_FORMAT_CHOOSER
#define EGG_IS_FILE_FORMAT_CHOOSER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE(obj, EGG_TYPE_FILE_FORMAT_CHOOSER))
Definition at line 29 of file eggfileformatchooser.h.
Referenced by egg_file_format_chooser_add_format(), egg_file_format_chooser_add_pixbuf_formats(), egg_file_format_chooser_append_extension(), egg_file_format_chooser_get_format(), egg_file_format_chooser_get_format_data(), egg_file_format_chooser_remove_format(), egg_file_format_chooser_set_format(), and egg_file_format_chooser_set_format_data().
EGG_IS_FILE_FORMAT_CHOOSER_CLASS
#define EGG_IS_FILE_FORMAT_CHOOSER_CLASS (obj)
Value:
(G_TYPE_CHECK_CLASS_TYPE(obj, EGG_TYPE_FILE_FORMAT_CHOOSER))
Definition at line 30 of file eggfileformatchooser.h.
EGG_TYPE_FILE_FORMAT_CHOOSER
#define EGG_TYPE_FILE_FORMAT_CHOOSER (egg_file_format_chooser_get_type())
Definition at line 26 of file eggfileformatchooser.h.
Referenced by egg_file_format_chooser_new().
Typedef Documentation
EggFileFormatChooser
typedef struct _EggFileFormatChooser EggFileFormatChooser
Definition at line 33 of file eggfileformatchooser.h.
EggFileFormatChooserClass
typedef struct _EggFileFormatChooserClass EggFileFormatChooserClass
Definition at line 34 of file eggfileformatchooser.h.
EggFileFormatChooserPrivate
typedef struct _EggFileFormatChooserPrivate EggFileFormatChooserPrivate
Definition at line 35 of file eggfileformatchooser.h.
Function Documentation
egg_file_format_chooser_add_format()
guint egg_file_format_chooser_add_format (EggFileFormatChooser * self, guint parent, const gchar * name, const gchar * icon, ...)
Definition at line 853 of file eggfileformatchooser.c.
References EGG_IS_FILE_FORMAT_CHOOSER, name, NULL, and TRUE.
egg_file_format_chooser_add_pixbuf_formats()
void egg_file_format_chooser_add_pixbuf_formats (EggFileFormatChooser * self, guint parent, guint ** formats)
Definition at line 927 of file eggfileformatchooser.c.
References egg_file_format_chooser_set_format_data(), EGG_IS_FILE_FORMAT_CHOOSER, name, and NULL.
Referenced by egg_file_format_chooser_get_type().
egg_file_format_chooser_append_extension()
gchar * egg_file_format_chooser_append_extension (EggFileFormatChooser * self, const gchar * filename, guint format)
Definition at line 1138 of file eggfileformatchooser.c.
References egg_file_format_chooser_get_format(), EGG_IS_FILE_FORMAT_CHOOSER, FALSE, MODEL_COLUMN_EXTENSIONS, NULL, _EggFileFormatChooser::priv, and strchr.
Referenced by egg_file_format_chooser_get_type().
egg_file_format_chooser_emit_size_changed()
void egg_file_format_chooser_emit_size_changed (EggFileFormatChooser * self)
Definition at line 1199 of file eggfileformatchooser.c.
References _EggFileFormatChooser::priv.
Referenced by egg_file_format_chooser_get_type().
egg_file_format_chooser_get_format()
guint egg_file_format_chooser_get_format (EggFileFormatChooser * self, const gchar * filename)
Definition at line 1061 of file eggfileformatchooser.c.
References EGG_IS_FILE_FORMAT_CHOOSER, FALSE, MODEL_COLUMN_ID, NULL, _EggFileFormatChooser::priv, and strrchr.
Referenced by egg_file_format_chooser_append_extension(), and egg_file_format_chooser_get_type().
egg_file_format_chooser_get_format_data()
gpointer egg_file_format_chooser_get_format_data (EggFileFormatChooser * self, guint format)
Definition at line 1114 of file eggfileformatchooser.c.
References data, EGG_IS_FILE_FORMAT_CHOOSER, FALSE, MODEL_COLUMN_DATA, NULL, and _EggFileFormatChooser::priv.
Referenced by egg_file_format_chooser_get_type().
egg_file_format_chooser_get_type()
GType egg_file_format_chooser_get_type (void)
References data, egg_file_format_chooser_add_pixbuf_formats(), egg_file_format_chooser_append_extension(), egg_file_format_chooser_emit_size_changed(), egg_file_format_chooser_get_format(), egg_file_format_chooser_get_format_data(), egg_file_format_chooser_remove_format(), egg_file_format_chooser_set_format(), egg_file_format_chooser_set_format_data(), and name.
egg_file_format_chooser_new()
GtkWidget * egg_file_format_chooser_new (void)
Definition at line 796 of file eggfileformatchooser.c.
References EGG_TYPE_FILE_FORMAT_CHOOSER, and NULL.
egg_file_format_chooser_remove_format()
void egg_file_format_chooser_remove_format (EggFileFormatChooser * self, guint format)
Definition at line 982 of file eggfileformatchooser.c.
References data, EGG_IS_FILE_FORMAT_CHOOSER, FALSE, MODEL_COLUMN_DATA, MODEL_COLUMN_DESTROY, MODEL_COLUMN_FILTER, NULL, and _EggFileFormatChooser::priv.
Referenced by egg_file_format_chooser_get_type().
egg_file_format_chooser_set_format()
void egg_file_format_chooser_set_format (EggFileFormatChooser * self, guint format)
Definition at line 1025 of file eggfileformatchooser.c.
References EGG_IS_FILE_FORMAT_CHOOSER, FALSE, and _EggFileFormatChooser::priv.
Referenced by egg_file_format_chooser_get_type().
egg_file_format_chooser_set_format_data()
void egg_file_format_chooser_set_format_data (EggFileFormatChooser * self, guint format, gpointer data, GDestroyNotify destroy)
Definition at line 1090 of file eggfileformatchooser.c.
References data, EGG_IS_FILE_FORMAT_CHOOSER, FALSE, MODEL_COLUMN_DATA, MODEL_COLUMN_DESTROY, and _EggFileFormatChooser::priv.
Referenced by egg_file_format_chooser_add_pixbuf_formats(), and egg_file_format_chooser_get_type().