MATE Desktop Environment: engines.h File Reference
engines.h File Reference
#include <gtk/gtk.h>
Typedefs
typedef void(* UrlClickedCb) (GtkWindow *nw, const char *url)
Functions
GtkWindow * theme_create_notification (UrlClickedCb url_clicked_cb)
void theme_destroy_notification (GtkWindow *nw)
void theme_show_notification (GtkWindow *nw)
void theme_hide_notification (GtkWindow *nw)
void theme_set_notification_hints (GtkWindow *nw, GVariant *hints)
void theme_set_notification_timeout (GtkWindow *nw, glong timeout)
void theme_notification_tick (GtkWindow *nw, glong remaining)
void theme_set_notification_text (GtkWindow *nw, const char *summary, const char *body)
void theme_set_notification_icon (GtkWindow *nw, GdkPixbuf *pixbuf)
void theme_set_notification_arrow (GtkWindow *nw, gboolean visible, int x, int y)
void theme_add_notification_action (GtkWindow *nw, const char *label, const char *key, GCallback cb)
void theme_clear_notification_actions (GtkWindow *nw)
void theme_move_notification (GtkWindow *nw, int x, int y)
gboolean theme_get_always_stack (GtkWindow *nw)
Typedef Documentation
UrlClickedCb
typedef void(* UrlClickedCb) (GtkWindow *nw, const char *url)
Definition at line 30 of file engines.h.
Function Documentation
theme_add_notification_action()
void theme_add_notification_action (GtkWindow * nw, const char * label, const char * key, GCallback cb)
Definition at line 314 of file engines.c.
References cb, engine, key, and label.
theme_clear_notification_actions()
void theme_clear_notification_actions (GtkWindow * nw)
Definition at line 320 of file engines.c.
References engine.
theme_create_notification()
GtkWindow * theme_create_notification (UrlClickedCb url_clicked_cb)
Definition at line 209 of file engines.c.
References engine, and wayland_init_notification().
theme_destroy_notification()
void theme_destroy_notification (GtkWindow * nw)
Definition at line 224 of file engines.c.
References engine, and NULL.
theme_get_always_stack()
gboolean theme_get_always_stack (GtkWindow * nw)
Definition at line 338 of file engines.c.
References engine, FALSE, and NULL.
theme_hide_notification()
void theme_hide_notification (GtkWindow * nw)
Definition at line 252 of file engines.c.
References engine, and NULL.
theme_move_notification()
void theme_move_notification (GtkWindow * nw, int x, int y)
Definition at line 326 of file engines.c.
References engine, and wayland_move_notification().
Referenced by notify_stack_add_window().
theme_notification_tick()
void theme_notification_tick (GtkWindow * nw, glong remaining)
Definition at line 286 of file engines.c.
References engine, and NULL.
theme_set_notification_arrow()
void theme_set_notification_arrow (GtkWindow * nw, gboolean visible, int x, int y)
Definition at line 308 of file engines.c.
References engine.
theme_set_notification_hints()
void theme_set_notification_hints (GtkWindow * nw, GVariant * hints)
Definition at line 266 of file engines.c.
References engine, and NULL.
theme_set_notification_icon()
void theme_set_notification_icon (GtkWindow * nw, GdkPixbuf * pixbuf)
Definition at line 302 of file engines.c.
References engine.
theme_set_notification_text()
void theme_set_notification_text (GtkWindow * nw, const char * summary, const char * body)
Definition at line 296 of file engines.c.
References engine.
theme_set_notification_timeout()
void theme_set_notification_timeout (GtkWindow * nw, glong timeout)
Definition at line 276 of file engines.c.
References engine, and NULL.
theme_show_notification()
void theme_show_notification (GtkWindow * nw)
Definition at line 238 of file engines.c.
References engine, and NULL.