MATE Desktop Environment: entry-directories.c File Reference
entry-directories.c File Reference
#include <config.h>
#include "entry-directories.h"
#include <string.h>
#include <errno.h>
#include <sys/types.h>
#include <dirent.h>
#include <stdlib.h>
#include "menu-util.h"
#include "menu-monitor.h"
Macros
#define _XOPEN_SOURCE 500
Typedefs
typedef struct CachedDir CachedDir
typedef struct CachedDirMonitor CachedDirMonitor
typedef gboolean(* EntryDirectoryForeachFunc) (EntryDirectory *ed, DesktopEntry *entry, const char *file_id, DesktopEntrySet *set, gpointer user_data)
Functions
EntryDirectory * entry_directory_new (DesktopEntryType entry_type, const char *path)
EntryDirectory * entry_directory_new_legacy (DesktopEntryType entry_type, const char *path, const char *legacy_prefix)
EntryDirectory * entry_directory_ref (EntryDirectory *ed)
void entry_directory_unref (EntryDirectory *ed)
void entry_directory_get_flat_contents (EntryDirectory *ed, DesktopEntrySet *desktop_entries, DesktopEntrySet *directory_entries, GSList **subdirs)
EntryDirectoryList * entry_directory_list_new (void)
EntryDirectoryList * entry_directory_list_ref (EntryDirectoryList *list)
void entry_directory_list_unref (EntryDirectoryList *list)
void entry_directory_list_prepend (EntryDirectoryList *list, EntryDirectory *ed)
int entry_directory_list_get_length (EntryDirectoryList *list)
void entry_directory_list_append_list (EntryDirectoryList *list, EntryDirectoryList *to_append)
DesktopEntry * entry_directory_list_get_directory (EntryDirectoryList *list, const char *relative_path)
gboolean _entry_directory_list_compare (const EntryDirectoryList *a, const EntryDirectoryList *b)
void _entry_directory_list_empty_desktop_cache (void)
DesktopEntrySet * _entry_directory_list_get_all_desktops (EntryDirectoryList *list)
void entry_directory_list_add_monitors (EntryDirectoryList *list, EntryDirectoryChangedFunc callback, gpointer user_data)
void entry_directory_list_remove_monitors (EntryDirectoryList *list, EntryDirectoryChangedFunc callback, gpointer user_data)
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE 500
Definition at line 22 of file entry-directories.c.
Typedef Documentation
CachedDir
typedef struct CachedDir CachedDir
Definition at line 37 of file entry-directories.c.
CachedDirMonitor
typedef struct CachedDirMonitor CachedDirMonitor
Definition at line 38 of file entry-directories.c.
EntryDirectoryForeachFunc
typedef gboolean(* EntryDirectoryForeachFunc) (EntryDirectory *ed, DesktopEntry *entry, const char *file_id, DesktopEntrySet *set, gpointer user_data)
Definition at line 865 of file entry-directories.c.
Function Documentation
_entry_directory_list_compare()
gboolean _entry_directory_list_compare (const EntryDirectoryList * a, const EntryDirectoryList * b)
Definition at line 1103 of file entry-directories.c.
References b, FALSE, NULL, and TRUE.
Referenced by _entry_directory_list_get_all_desktops().
_entry_directory_list_empty_desktop_cache()
void _entry_directory_list_empty_desktop_cache (void)
Definition at line 1147 of file entry-directories.c.
References desktop_entry_set_unref(), entry_directory_list_unref(), and NULL.
_entry_directory_list_get_all_desktops()
DesktopEntrySet * _entry_directory_list_get_all_desktops (EntryDirectoryList * list)
Definition at line 1158 of file entry-directories.c.
References _entry_directory_list_compare(), desktop_entry_set_new(), desktop_entry_set_ref(), desktop_entry_set_unref(), entry_directory_list_ref(), entry_directory_list_unref(), NULL, and set.
entry_directory_get_flat_contents()
void entry_directory_get_flat_contents (EntryDirectory * ed, DesktopEntrySet * desktop_entries, DesktopEntrySet * directory_entries, GSList ** subdirs)
Definition at line 947 of file entry-directories.c.
References DESKTOP_ENTRY_DESKTOP, DESKTOP_ENTRY_DIRECTORY, desktop_entry_get_basename(), desktop_entry_get_type(), desktop_entry_set_add_entry(), and NULL.
entry_directory_list_add_monitors()
void entry_directory_list_add_monitors (EntryDirectoryList * list, EntryDirectoryChangedFunc callback, gpointer user_data)
Definition at line 1207 of file entry-directories.c.
References NULL, and user_data.
entry_directory_list_append_list()
void entry_directory_list_append_list (EntryDirectoryList * list, EntryDirectoryList * to_append)
Definition at line 1064 of file entry-directories.c.
References entry_directory_ref(), and NULL.
entry_directory_list_get_directory()
DesktopEntry * entry_directory_list_get_directory (EntryDirectoryList * list, const char * relative_path)
Definition at line 1086 of file entry-directories.c.
References NULL.
entry_directory_list_get_length()
int entry_directory_list_get_length (EntryDirectoryList * list)
Definition at line 1059 of file entry-directories.c.
entry_directory_list_new()
EntryDirectoryList * entry_directory_list_new (void)
Definition at line 1013 of file entry-directories.c.
References NULL.
entry_directory_list_prepend()
void entry_directory_list_prepend (EntryDirectoryList * list, EntryDirectory * ed)
Definition at line 1052 of file entry-directories.c.
References entry_directory_ref().
entry_directory_list_ref()
EntryDirectoryList * entry_directory_list_ref (EntryDirectoryList * list)
Definition at line 1026 of file entry-directories.c.
References NULL.
Referenced by _entry_directory_list_get_all_desktops().
entry_directory_list_remove_monitors()
void entry_directory_list_remove_monitors (EntryDirectoryList * list, EntryDirectoryChangedFunc callback, gpointer user_data)
Definition at line 1219 of file entry-directories.c.
References NULL, and user_data.
entry_directory_list_unref()
void entry_directory_list_unref (EntryDirectoryList * list)
Definition at line 1036 of file entry-directories.c.
References entry_directory_unref(), and NULL.
Referenced by _entry_directory_list_empty_desktop_cache(), and _entry_directory_list_get_all_desktops().
entry_directory_new()
EntryDirectory * entry_directory_new (DesktopEntryType entry_type, const char * path)
Definition at line 764 of file entry-directories.c.
References FALSE, and NULL.
entry_directory_new_legacy()
EntryDirectory * entry_directory_new_legacy (DesktopEntryType entry_type, const char * path, const char * legacy_prefix)
Definition at line 769 of file entry-directories.c.
References TRUE.
entry_directory_ref()
EntryDirectory * entry_directory_ref (EntryDirectory * ed)
Definition at line 774 of file entry-directories.c.
References NULL.
Referenced by entry_directory_list_append_list(), and entry_directory_list_prepend().
entry_directory_unref()
void entry_directory_unref (EntryDirectory * ed)
Definition at line 784 of file entry-directories.c.
References DESKTOP_ENTRY_INVALID, FALSE, and NULL.
Referenced by entry_directory_list_unref().