MATE Desktop Environment: eom-print-image-setup.c File Reference
eom-print-image-setup.c File Reference
#include <gtk/gtk.h>
#include <gtk/gtkunixprint.h>
#include <glib/gi18n.h>
#include <glib/gprintf.h>
#include "eom-print-image-setup.h"
#include "eom-print-preview.h"
Macros
#define FACTOR_INCH_TO_MM 25.4
#define FACTOR_INCH_TO_PIXEL 72.
#define FACTOR_MM_TO_INCH 0.03937007874015748
#define FACTOR_MM_TO_PIXEL 2.834645669
Enumerations
enum { PROP_0 , PROP_IMAGE , PROP_PAGE_SETUP }
enum { CENTER_NONE , CENTER_HORIZONTAL , CENTER_VERTICAL , CENTER_BOTH }
enum { CHANGE_HORIZ , CHANGE_VERT }
enum { UNIT_INCH , UNIT_MM }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (EomPrintImageSetup, eom_print_image_setup, GTK_TYPE_GRID)
GtkWidget * eom_print_image_setup_new (EomImage *image, GtkPageSetup *page_setup)
void eom_print_image_setup_get_options (EomPrintImageSetup *setup, gdouble *left, gdouble *top, gdouble *scale, GtkUnit *unit)
void eom_print_image_setup_update (GtkPrintOperation *operation, GtkWidget *custom_widget, GtkPageSetup *page_setup, GtkPrintSettings *print_settings, gpointer user_data)
Macro Definition Documentation
FACTOR_INCH_TO_MM
#define FACTOR_INCH_TO_MM 25.4
Definition at line 96 of file eom-print-image-setup.c.
FACTOR_INCH_TO_PIXEL
#define FACTOR_INCH_TO_PIXEL 72.
Definition at line 97 of file eom-print-image-setup.c.
FACTOR_MM_TO_INCH
#define FACTOR_MM_TO_INCH 0.03937007874015748
Definition at line 98 of file eom-print-image-setup.c.
Referenced by eom_print_image_setup_update().
FACTOR_MM_TO_PIXEL
#define FACTOR_MM_TO_PIXEL 2.834645669
Definition at line 99 of file eom-print-image-setup.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CENTER_NONE
CENTER_HORIZONTAL
CENTER_VERTICAL
CENTER_BOTH
Definition at line 79 of file eom-print-image-setup.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_IMAGE
PROP_PAGE_SETUP
Definition at line 73 of file eom-print-image-setup.c.
anonymous enum
anonymous enum
Enumerator
UNIT_INCH
UNIT_MM
Definition at line 91 of file eom-print-image-setup.c.
anonymous enum
anonymous enum
Enumerator
CHANGE_HORIZ
CHANGE_VERT
Definition at line 86 of file eom-print-image-setup.c.
Function Documentation
eom_print_image_setup_get_options()
void eom_print_image_setup_get_options (EomPrintImageSetup * setup, gdouble * left, gdouble * top, gdouble * scale, GtkUnit * unit)
eom_print_image_setup_get_options: @setup: a EomPrintImageSetup @left: a pointer where to store the image's left position @top: a pointer where to store the image's top position @scale: a pointer where to store the image's scale @unit: a pointer where to store the #GtkUnit used by the @left and @top values.
Gets the options set by the EomPrintImageSetup.
Definition at line 1024 of file eom-print-image-setup.c.
References EOM_IS_PRINT_IMAGE_SETUP, and _EomPrintImageSetup::priv.
eom_print_image_setup_new()
GtkWidget * eom_print_image_setup_new (EomImage * image, GtkPageSetup * page_setup)
eom_print_image_setup_new: the EomImage to print @page_setup: a #GtkPageSetup specifying the page where the image will be print
Creates a new EomPrintImageSetup widget, to be used as a custom widget in a #GtkPrintUnixDialog. This widgets allows to set the image position and scale in a page.
Returns: a new EomPrintImageSetup
Definition at line 988 of file eom-print-image-setup.c.
References EOM_PRINT_IMAGE_SETUP, EOM_PRINT_PREVIEW, eom_print_preview_set_from_page_setup(), EOM_TYPE_PRINT_IMAGE_SETUP, and NULL.
eom_print_image_setup_update()
void eom_print_image_setup_update (GtkPrintOperation * operation, GtkWidget * custom_widget, GtkPageSetup * page_setup, GtkPrintSettings * print_settings, gpointer user_data)
Definition at line 1043 of file eom-print-image-setup.c.
References EOM_PRINT_IMAGE_SETUP, EOM_PRINT_PREVIEW, eom_print_preview_set_from_page_setup(), eom_print_preview_set_image_position(), FACTOR_MM_TO_INCH, _EomPrintImageSetup::priv, and user_data.
Referenced by eom_print_operation_new().
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (EomPrintImageSetup , eom_print_image_setup , GTK_TYPE_GRID)