MATE Desktop Environment: eom-exif-util.h File Reference
eom-exif-util.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <libexif/exif-data.h>
Macros
#define EOM_TYPE_EXIF_DATA eom_exif_data_get_type()
Functions
gchar * eom_exif_util_format_date (const gchar *date)
void eom_exif_util_format_datetime_label (GtkLabel *label, ExifData *exif_data, gint tag_id, const gchar *format)
void eom_exif_util_set_label_text (GtkLabel *label, ExifData *exif_data, gint tag_id)
void eom_exif_util_set_focal_length_label_text (GtkLabel *label, ExifData *exif_data)
const gchar * eom_exif_data_get_value (ExifData *exif_data, gint tag_id, gchar *buffer, guint buf_size)
GType eom_exif_data_get_type (void)
ExifData * eom_exif_data_copy (ExifData *data)
void eom_exif_data_free (ExifData *data)
Macro Definition Documentation
EOM_TYPE_EXIF_DATA
#define EOM_TYPE_EXIF_DATA eom_exif_data_get_type()
Definition at line 37 of file eom-exif-util.h.
Function Documentation
eom_exif_data_copy()
ExifData * eom_exif_data_copy (ExifData * data)
Definition at line 345 of file eom-exif-util.c.
References data.
eom_exif_data_free()
void eom_exif_data_free (ExifData * data)
Definition at line 353 of file eom-exif-util.c.
References data.
eom_exif_data_get_type()
GType eom_exif_data_get_type (void)
References data.
eom_exif_data_get_value()
const gchar * eom_exif_data_get_value (EomExifData * exif_data, gint tag_id, gchar * buffer, guint buf_size)
eom_exif_data_get_value: @exif_data: pointer to an <structname>ExifData</structname> struct @tag_id: the requested tag's id. See <filename>exif-tag.h</filename> from the libexif package for possible values (e.g. EXIF_TAG_EXPOSURE_MODE). @buffer: a pre-allocated output buffer @buf_size: size of @buffer
Convenience function to extract a string representation of an Exif tag directly from an <structname>ExifData</structname> struct. The string is written into @buffer as far as @buf_size permits.
Returns: a pointer to @buffer.
Definition at line 330 of file eom-exif-util.c.
Referenced by eom_exif_util_format_datetime_label(), and eom_exif_util_set_label_text().
eom_exif_util_format_date()
gchar * eom_exif_util_format_date (const gchar * date)
eom_exif_util_format_date:
Date
: a date string following Exif specifications
Takes a date string formatted after Exif specifications and generates a more readable, possibly localized, string out of it.
Returns: a newly allocated date string formatted according to the current locale.
Definition at line 186 of file eom-exif-util.c.
References _.
Referenced by eom_exif_util_set_label_text().
eom_exif_util_format_datetime_label()
void eom_exif_util_format_datetime_label (GtkLabel * label, ExifData * exif_data, gint tag_id, const gchar * format)
Definition at line 224 of file eom-exif-util.c.
References eom_exif_data_get_value(), label, and NULL.
eom_exif_util_set_focal_length_label_text()
void eom_exif_util_set_focal_length_label_text (GtkLabel * label, ExifData * exif_data)
Definition at line 251 of file eom-exif-util.c.
References _, label, and NULL.
eom_exif_util_set_label_text()
void eom_exif_util_set_label_text (GtkLabel * label, ExifData * exif_data, gint tag_id)
Definition at line 199 of file eom-exif-util.c.
References eom_exif_data_get_value(), eom_exif_util_format_date(), eom_util_make_valid_utf8(), label, and NULL.