MATE Desktop Environment: eom-thumb-nav.h File Reference
eom-thumb-nav.h File Reference
#include "eom-thumb-view.h"
#include <gtk/gtk.h>
#include <glib.h>
#include <glib-object.h>
Classes
struct _EomThumbNav
struct _EomThumbNavClass
Macros
#define EOM_TYPE_THUMB_NAV (eom_thumb_nav_get_type ())
#define EOM_THUMB_NAV(obj)
#define EOM_THUMB_NAV_CLASS(klass)
#define EOM_IS_THUMB_NAV(obj)
#define EOM_IS_THUMB_NAV_CLASS(klass)
#define EOM_THUMB_NAV_GET_CLASS(obj)
Typedefs
typedef struct _EomThumbNav EomThumbNav
typedef struct _EomThumbNavClass EomThumbNavClass
typedef struct _EomThumbNavPrivate EomThumbNavPrivate
Enumerations
enum EomThumbNavMode { EOM_THUMB_NAV_MODE_ONE_ROW , EOM_THUMB_NAV_MODE_ONE_COLUMN , EOM_THUMB_NAV_MODE_MULTIPLE_ROWS , EOM_THUMB_NAV_MODE_MULTIPLE_COLUMNS }
Functions
GType eom_thumb_nav_get_type (void)
GtkWidget * eom_thumb_nav_new (GtkWidget *thumbview, EomThumbNavMode mode, gboolean show_buttons)
gboolean eom_thumb_nav_get_show_buttons (EomThumbNav *nav)
void eom_thumb_nav_set_show_buttons (EomThumbNav *nav, gboolean show_buttons)
EomThumbNavMode eom_thumb_nav_get_mode (EomThumbNav *nav)
void eom_thumb_nav_set_mode (EomThumbNav *nav, EomThumbNavMode mode)
Macro Definition Documentation
EOM_IS_THUMB_NAV
#define EOM_IS_THUMB_NAV (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE((obj), EOM_TYPE_THUMB_NAV))
Definition at line 40 of file eom-thumb-nav.h.
Referenced by eom_thumb_nav_get_mode(), eom_thumb_nav_get_show_buttons(), eom_thumb_nav_set_mode(), and eom_thumb_nav_set_show_buttons().
EOM_IS_THUMB_NAV_CLASS
#define EOM_IS_THUMB_NAV_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass),  EOM_TYPE_THUMB_NAV))
Definition at line 41 of file eom-thumb-nav.h.
EOM_THUMB_NAV
#define EOM_THUMB_NAV (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST((obj), EOM_TYPE_THUMB_NAV, EomThumbNav))
Definition at line 38 of file eom-thumb-nav.h.
EOM_THUMB_NAV_CLASS
#define EOM_THUMB_NAV_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST((klass),  EOM_TYPE_THUMB_NAV, EomThumbNavClass))
Definition at line 39 of file eom-thumb-nav.h.
EOM_THUMB_NAV_GET_CLASS
#define EOM_THUMB_NAV_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS((obj),  EOM_TYPE_THUMB_NAV, EomThumbNavClass))
Definition at line 42 of file eom-thumb-nav.h.
EOM_TYPE_THUMB_NAV
#define EOM_TYPE_THUMB_NAV (eom_thumb_nav_get_type ())
Definition at line 37 of file eom-thumb-nav.h.
Referenced by eom_thumb_nav_new().
Typedef Documentation
EomThumbNav
typedef struct _EomThumbNav EomThumbNav
Definition at line 33 of file eom-thumb-nav.h.
EomThumbNavClass
typedef struct _EomThumbNavClass EomThumbNavClass
Definition at line 34 of file eom-thumb-nav.h.
EomThumbNavPrivate
typedef struct _EomThumbNavPrivate EomThumbNavPrivate
Definition at line 35 of file eom-thumb-nav.h.
Enumeration Type Documentation
EomThumbNavMode
enum EomThumbNavMode
Enumerator
EOM_THUMB_NAV_MODE_ONE_ROW
EOM_THUMB_NAV_MODE_ONE_COLUMN
EOM_THUMB_NAV_MODE_MULTIPLE_ROWS
EOM_THUMB_NAV_MODE_MULTIPLE_COLUMNS
Definition at line 44 of file eom-thumb-nav.h.
Function Documentation
eom_thumb_nav_get_mode()
EomThumbNavMode eom_thumb_nav_get_mode (EomThumbNav * nav)
eom_thumb_nav_get_mode: @nav: an EomThumbNav.
Gets the navigation mode in @nav.
Returns: A value in EomThumbNavMode.
Definition at line 517 of file eom-thumb-nav.c.
References EOM_IS_THUMB_NAV, FALSE, and _EomThumbNav::priv.
eom_thumb_nav_get_show_buttons()
gboolean eom_thumb_nav_get_show_buttons (EomThumbNav * nav)
eom_thumb_nav_get_show_buttons: @nav: an EomThumbNav.
Gets whether the navigation buttons are visible.
Returns: TRUE if the navigation buttons are visible, FALSE otherwise.
Definition at line 474 of file eom-thumb-nav.c.
References EOM_IS_THUMB_NAV, FALSE, and _EomThumbNav::priv.
eom_thumb_nav_get_type()
GType eom_thumb_nav_get_type (void)
eom_thumb_nav_new()
GtkWidget * eom_thumb_nav_new (GtkWidget * thumbview, EomThumbNavMode mode, gboolean show_buttons)
eom_thumb_nav_new: @thumbview: an EomThumbView to embed in the navigation widget. @mode: The navigation mode. @show_buttons: Whether to show the navigation buttons.
Creates a new thumbnail navigation widget.
Returns: a new EomThumbNav object.
Definition at line 447 of file eom-thumb-nav.c.
References EOM_TYPE_THUMB_NAV, FALSE, and NULL.
eom_thumb_nav_set_mode()
void eom_thumb_nav_set_mode (EomThumbNav * nav, EomThumbNavMode mode)
eom_thumb_nav_set_mode: @nav: An EomThumbNav. @mode: One of EomThumbNavMode.
Sets the navigation mode in @nav. See EomThumbNavMode for details.
Definition at line 532 of file eom-thumb-nav.c.
References EOM_IS_THUMB_NAV, EOM_THUMB_NAV_MODE_MULTIPLE_COLUMNS, EOM_THUMB_NAV_MODE_MULTIPLE_ROWS, EOM_THUMB_NAV_MODE_ONE_COLUMN, EOM_THUMB_NAV_MODE_ONE_ROW, eom_thumb_nav_set_show_buttons(), EOM_THUMB_VIEW, eom_thumb_view_set_item_height(), and _EomThumbNav::priv.
eom_thumb_nav_set_show_buttons()
void eom_thumb_nav_set_show_buttons (EomThumbNav * nav, gboolean show_buttons)
eom_thumb_nav_set_show_buttons: @nav: an EomThumbNav. @show_buttons: TRUE to show the buttons, FALSE to hide them.
Sets whether the navigation buttons to the left and right of the widget should be visible.
Definition at line 490 of file eom-thumb-nav.c.
References EOM_IS_THUMB_NAV, EOM_THUMB_NAV_MODE_ONE_ROW, NULL, and _EomThumbNav::priv.
Referenced by eom_thumb_nav_set_mode().