MATE Desktop Environment: eom-window.h File Reference
eom-window.h File Reference
#include "eom-list-store.h"
#include "eom-image.h"
#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
Classes
struct _EomWindow
struct _EomWindowClass
Macros
#define EOM_TYPE_WINDOW (eom_window_get_type ())
#define EOM_WINDOW(obj)
#define EOM_WINDOW_CLASS(klass)
#define EOM_IS_WINDOW(obj)
#define EOM_IS_WINDOW_CLASS(klass)
#define EOM_WINDOW_GET_CLASS(obj)
#define EOM_WINDOW_ERROR (eom_window_error_quark ())
Typedefs
typedef struct _EomWindow EomWindow
typedef struct _EomWindowClass EomWindowClass
typedef struct _EomWindowPrivate EomWindowPrivate
Enumerations
enum EomWindowMode { EOM_WINDOW_MODE_UNKNOWN , EOM_WINDOW_MODE_NORMAL , EOM_WINDOW_MODE_FULLSCREEN , EOM_WINDOW_MODE_SLIDESHOW }
enum EomWindowCollectionPos { EOM_WINDOW_COLLECTION_POS_BOTTOM , EOM_WINDOW_COLLECTION_POS_LEFT , EOM_WINDOW_COLLECTION_POS_TOP , EOM_WINDOW_COLLECTION_POS_RIGHT }
enum EomWindowError {
EOM_WINDOW_ERROR_CONTROL_NOT_FOUND , EOM_WINDOW_ERROR_UI_NOT_FOUND , EOM_WINDOW_ERROR_NO_PERSIST_FILE_INTERFACE , EOM_WINDOW_ERROR_IO ,
EOM_WINDOW_ERROR_TRASH_NOT_FOUND , EOM_WINDOW_ERROR_GENERIC , EOM_WINDOW_ERROR_UNKNOWN
}
enum EomStartupFlags { EOM_STARTUP_FULLSCREEN = 1 << 0 , EOM_STARTUP_SLIDE_SHOW = 1 << 1 , EOM_STARTUP_DISABLE_COLLECTION = 1 << 2 , EOM_STARTUP_PRESERVE_ORDER = 1 << 3 }
Functions
GType eom_window_get_type (void)
GtkWidget * eom_window_new (EomStartupFlags flags)
EomWindowMode eom_window_get_mode (EomWindow *window)
void eom_window_set_mode (EomWindow *window, EomWindowMode mode)
GtkUIManager * eom_window_get_ui_manager (EomWindow *window)
EomListStore * eom_window_get_store (EomWindow *window)
GtkWidget * eom_window_get_view (EomWindow *window)
GtkWidget * eom_window_get_sidebar (EomWindow *window)
GtkWidget * eom_window_get_thumb_view (EomWindow *window)
GtkWidget * eom_window_get_thumb_nav (EomWindow *window)
GtkWidget * eom_window_get_statusbar (EomWindow *window)
EomImage * eom_window_get_image (EomWindow *window)
void eom_window_open_file_list (EomWindow *window, GSList *file_list)
gboolean eom_window_is_empty (EomWindow *window)
void eom_window_reload_image (EomWindow *window)
GtkWidget * eom_window_get_properties_dialog (EomWindow *window)
Macro Definition Documentation
EOM_IS_WINDOW
#define EOM_IS_WINDOW (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), EOM_TYPE_WINDOW))
Definition at line 47 of file eom-window.h.
Referenced by eom_window_get_image(), eom_window_get_mode(), eom_window_get_properties_dialog(), eom_window_get_sidebar(), eom_window_get_statusbar(), eom_window_get_store(), eom_window_get_thumb_nav(), eom_window_get_thumb_view(), eom_window_get_ui_manager(), eom_window_get_view(), eom_window_is_empty(), eom_window_reload_image(), and eom_window_set_mode().
EOM_IS_WINDOW_CLASS
#define EOM_IS_WINDOW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass),  EOM_TYPE_WINDOW))
Definition at line 48 of file eom-window.h.
EOM_TYPE_WINDOW
#define EOM_TYPE_WINDOW (eom_window_get_type ())
Definition at line 44 of file eom-window.h.
Referenced by eom_window_activatable_default_init(), and eom_window_new().
EOM_WINDOW
#define EOM_WINDOW (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), EOM_TYPE_WINDOW, EomWindow))
Definition at line 45 of file eom-window.h.
Referenced by eom_application_open_file_list(), and eom_window_new().
EOM_WINDOW_CLASS
#define EOM_WINDOW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass),  EOM_TYPE_WINDOW, EomWindowClass))
Definition at line 46 of file eom-window.h.
EOM_WINDOW_ERROR
#define EOM_WINDOW_ERROR (eom_window_error_quark ())
Definition at line 51 of file eom-window.h.
EOM_WINDOW_GET_CLASS
#define EOM_WINDOW_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj),  EOM_TYPE_WINDOW, EomWindowClass))
Definition at line 49 of file eom-window.h.
Typedef Documentation
EomWindow
typedef struct _EomWindow EomWindow
Definition at line 40 of file eom-window.h.
EomWindowClass
typedef struct _EomWindowClass EomWindowClass
Definition at line 41 of file eom-window.h.
EomWindowPrivate
typedef struct _EomWindowPrivate EomWindowPrivate
Definition at line 42 of file eom-window.h.
Enumeration Type Documentation
EomStartupFlags
enum EomStartupFlags
Enumerator
EOM_STARTUP_FULLSCREEN
EOM_STARTUP_SLIDE_SHOW
EOM_STARTUP_DISABLE_COLLECTION
EOM_STARTUP_PRESERVE_ORDER
Definition at line 78 of file eom-window.h.
EomWindowCollectionPos
enum EomWindowCollectionPos
Enumerator
EOM_WINDOW_COLLECTION_POS_BOTTOM
EOM_WINDOW_COLLECTION_POS_LEFT
EOM_WINDOW_COLLECTION_POS_TOP
EOM_WINDOW_COLLECTION_POS_RIGHT
Definition at line 60 of file eom-window.h.
EomWindowError
enum EomWindowError
Enumerator
EOM_WINDOW_ERROR_CONTROL_NOT_FOUND
EOM_WINDOW_ERROR_UI_NOT_FOUND
EOM_WINDOW_ERROR_NO_PERSIST_FILE_INTERFACE
EOM_WINDOW_ERROR_IO
EOM_WINDOW_ERROR_TRASH_NOT_FOUND
EOM_WINDOW_ERROR_GENERIC
EOM_WINDOW_ERROR_UNKNOWN
Definition at line 68 of file eom-window.h.
EomWindowMode
enum EomWindowMode
Enumerator
EOM_WINDOW_MODE_UNKNOWN
EOM_WINDOW_MODE_NORMAL
EOM_WINDOW_MODE_FULLSCREEN
EOM_WINDOW_MODE_SLIDESHOW
Definition at line 53 of file eom-window.h.
Function Documentation
eom_window_get_image()
EomImage * eom_window_get_image (EomWindow * window)
eom_window_get_image: @window: an EomWindow.
Gets the image currently displayed in @window or NULL if no image is being displayed.
Returns: (transfer none): an EomImage.
Definition at line 5663 of file eom-window.c.
References EOM_IS_WINDOW, and NULL.
eom_window_get_mode()
EomWindowMode eom_window_get_mode (EomWindow * window)
eom_window_get_mode: @window: An EomWindow.
Gets the mode of @window. See EomWindowMode for details.
Returns: An EomWindowMode.
Definition at line 5517 of file eom-window.c.
References EOM_IS_WINDOW, and EOM_WINDOW_MODE_UNKNOWN.
eom_window_get_properties_dialog()
GtkWidget * eom_window_get_properties_dialog (EomWindow * window)
eom_window_get_properties_dialog: @window: a EomWindow
Gets the @window property dialog. The widget will be built on the first call to this function.
Returns: (transfer none): a #GtkDialog.
Definition at line 3106 of file eom-window.c.
References EOM_CONF_UI_PROPSDIALOG_NETBOOK_MODE, EOM_IS_WINDOW, EOM_PROPERTIES_DIALOG, eom_properties_dialog_new(), eom_properties_dialog_update(), EOM_THUMB_VIEW, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, and NULL.
eom_window_get_sidebar()
GtkWidget * eom_window_get_sidebar (EomWindow * window)
eom_window_get_sidebar: @window: An EomWindow.
Gets the sidebar widget of @window.
Returns: (transfer none): the EomSidebar.
Definition at line 5598 of file eom-window.c.
References EOM_IS_WINDOW, and NULL.
eom_window_get_statusbar()
GtkWidget * eom_window_get_statusbar (EomWindow * window)
eom_window_get_statusbar: @window: an EomWindow.
Gets the statusbar in @window.
Returns: (transfer none): a #EomStatusBar.
Definition at line 5646 of file eom-window.c.
References EOM_IS_WINDOW, and NULL.
eom_window_get_store()
EomListStore * eom_window_get_store (EomWindow * window)
eom_window_get_store: @window: An EomWindow.
Gets the EomListStore that contains the images in the collection of @window.
Returns: (transfer none): an EomListStore.
Definition at line 5566 of file eom-window.c.
References EOM_IS_WINDOW, EOM_LIST_STORE, and NULL.
eom_window_get_thumb_nav()
GtkWidget * eom_window_get_thumb_nav (EomWindow * window)
eom_window_get_thumb_nav: @window: an EomWindow.
Gets the thumbnails navigation pane in @window.
Returns: (transfer none): an EomThumbNav.
Definition at line 5630 of file eom-window.c.
References EOM_IS_WINDOW, and NULL.
eom_window_get_thumb_view()
GtkWidget * eom_window_get_thumb_view (EomWindow * window)
eom_window_get_thumb_view: @window: an EomWindow.
Gets the thumbnails view in @window.
Returns: (transfer none): an EomThumbView.
Definition at line 5614 of file eom-window.c.
References EOM_IS_WINDOW, and NULL.
eom_window_get_type()
GType eom_window_get_type (void)
References file_list.
eom_window_get_ui_manager()
GtkUIManager * eom_window_get_ui_manager (EomWindow * window)
eom_window_get_ui_manager: @window: An EomWindow.
Gets the #GtkUIManager that describes the UI of @window.
Returns: (transfer none): A #GtkUIManager.
Definition at line 5501 of file eom-window.c.
References EOM_IS_WINDOW, and NULL.
eom_window_get_view()
GtkWidget * eom_window_get_view (EomWindow * window)
eom_window_get_view: @window: An EomWindow.
Gets the EomScrollView in the window.
Returns: (transfer none): the EomScrollView.
Definition at line 5582 of file eom-window.c.
References EOM_IS_WINDOW, and NULL.
Referenced by eom_window_reload_image().
eom_window_is_empty()
gboolean eom_window_is_empty (EomWindow * window)
eom_window_is_empty: @window: an EomWindow.
Tells whether @window is currently empty or not.
Returns: TRUE if @window has no images, FALSE otherwise.
Definition at line 5679 of file eom-window.c.
References DEBUG_WINDOW, eom_debug(), EOM_IS_WINDOW, EOM_LIST_STORE, eom_list_store_length(), FALSE, NULL, and TRUE.
eom_window_new()
GtkWidget * eom_window_new (EomStartupFlags flags)
eom_window_new: @flags: the initialization parameters for the new window.
Creates a new and empty EomWindow. Use @flags to indicate if the window should be initialized fullscreen, in slideshow mode, and/or without the thumbnails collection visible. Use preserve-order to maintain the order of input parameters instead of sorting. See EomStartupFlags.
Returns: a newly created EomWindow.
Definition at line 5347 of file eom-window.c.
References DEBUG_WINDOW, EOM_APP, eom_debug(), EOM_TYPE_WINDOW, EOM_WINDOW, FALSE, and NULL.
Referenced by eom_application_open_file_list(), and eom_application_open_window().
eom_window_open_file_list()
void eom_window_open_file_list (EomWindow * window, GSList * file_list)
eom_window_open_file_list: @window: An EomWindow. @file_list: (element-type GFile): A NULL-terminated list of #GFile's.
Opens a list of files, adding them to the collection in @window. Files will be checked to be readable and later filtered according with eom_list_store_add_files().
Definition at line 5471 of file eom-window.c.
References DEBUG_WINDOW, eom_debug(), eom_job_model_new(), eom_job_queue_add_job(), EOM_STARTUP_PRESERVE_ORDER, EOM_WINDOW_STATUS_INIT, file_list, and NULL.
Referenced by eom_application_open_file_list().
eom_window_reload_image()
void eom_window_reload_image (EomWindow * window)
Definition at line 5698 of file eom-window.c.
References EOM_IS_WINDOW, EOM_SCROLL_VIEW, eom_scroll_view_set_image(), EOM_THUMB_VIEW, EOM_THUMB_VIEW_SELECT_CURRENT, eom_thumb_view_select_single(), eom_window_get_view(), and NULL.
eom_window_set_mode()
void eom_window_set_mode (EomWindow * window, EomWindowMode mode)
eom_window_set_mode: @window: an EomWindow. @mode: an EomWindowMode value.
Changes the mode of @window to normal, fullscreen, or slideshow. See EomWindowMode for details.
Definition at line 5533 of file eom-window.c.
References EOM_IS_WINDOW, EOM_WINDOW_MODE_FULLSCREEN, EOM_WINDOW_MODE_NORMAL, EOM_WINDOW_MODE_SLIDESHOW, EOM_WINDOW_MODE_UNKNOWN, FALSE, and TRUE.