MATE Desktop Environment: eom-window.c File Reference
eom-window.c File Reference
#include <math.h>
#include "eom-window.h"
#include "eom-scroll-view.h"
#include "eom-debug.h"
#include "eom-file-chooser.h"
#include "eom-thumb-view.h"
#include "eom-list-store.h"
#include "eom-sidebar.h"
#include "eom-statusbar.h"
#include "eom-preferences-dialog.h"
#include "eom-properties-dialog.h"
#include "eom-print.h"
#include "eom-error-message-area.h"
#include "eom-application.h"
#include "eom-application-internal.h"
#include "eom-thumb-nav.h"
#include "eom-config-keys.h"
#include "eom-job-queue.h"
#include "eom-jobs.h"
#include "eom-util.h"
#include "eom-save-as-dialog-helper.h"
#include "eom-close-confirmation-dialog.h"
#include "eom-clipboard-handler.h"
#include "eom-window-activatable.h"
#include "eom-metadata-sidebar.h"
#include "eom-enum-types.h"
#include "egg-toolbar-editor.h"
#include "egg-editable-toolbar.h"
#include "egg-toolbars-model.h"
#include <glib.h>
#include <glib-object.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gdk/gdkkeysyms.h>
#include <gio/gdesktopappinfo.h>
#include <gtk/gtk.h>
#include <libpeas/peas-extension-set.h>
#include <libpeas/peas-activatable.h>
#include <libmate-desktop/mate-desktop-utils.h>
Macros
#define MATE_DESKTOP_USE_UNSTABLE_API
#define EOM_WINDOW_MIN_WIDTH 440
#define EOM_WINDOW_MIN_HEIGHT 350
#define EOM_WINDOW_DEFAULT_WIDTH 540
#define EOM_WINDOW_DEFAULT_HEIGHT 450
#define EOM_WINDOW_FULLSCREEN_TIMEOUT 5 * 1000
#define EOM_WINDOW_FULLSCREEN_POPUP_THRESHOLD 5
#define EOM_RECENT_FILES_GROUP "Graphics"
#define EOM_RECENT_FILES_APP_NAME "Eye of MATE Image Viewer"
#define EOM_RECENT_FILES_LIMIT 5
#define EOM_WALLPAPER_FILENAME "eom-wallpaper"
#define is_rtl (gtk_widget_get_default_direction () == GTK_TEXT_DIR_RTL)
#define EOM_TB_EDITOR_DLG_RESET_RESPONSE 128
#define ABOUT_GROUP "About"
#define EMAILIFY(string)
Enumerations
enum EomWindowStatus { EOM_WINDOW_STATUS_UNKNOWN , EOM_WINDOW_STATUS_INIT , EOM_WINDOW_STATUS_NORMAL }
enum { PROP_0 , PROP_COLLECTION_POS , PROP_COLLECTION_RESIZABLE , PROP_STARTUP_FLAGS }
enum { SIGNAL_PREPARED , SIGNAL_LAST }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (EomWindow, eom_window, GTK_TYPE_APPLICATION_WINDOW)
GtkWidget * eom_window_get_properties_dialog (EomWindow *window)
GtkWidget * eom_window_new (EomStartupFlags flags)
void eom_window_open_file_list (EomWindow *window, GSList *file_list)
GtkUIManager * eom_window_get_ui_manager (EomWindow *window)
EomWindowMode eom_window_get_mode (EomWindow *window)
void eom_window_set_mode (EomWindow *window, EomWindowMode mode)
EomListStore * eom_window_get_store (EomWindow *window)
GtkWidget * eom_window_get_view (EomWindow *window)
GtkWidget * eom_window_get_sidebar (EomWindow *window)
GtkWidget * eom_window_get_thumb_view (EomWindow *window)
GtkWidget * eom_window_get_thumb_nav (EomWindow *window)
GtkWidget * eom_window_get_statusbar (EomWindow *window)
EomImage * eom_window_get_image (EomWindow *window)
gboolean eom_window_is_empty (EomWindow *window)
void eom_window_reload_image (EomWindow *window)
Macro Definition Documentation
ABOUT_GROUP
#define ABOUT_GROUP "About"
Definition at line 2577 of file eom-window.c.
EMAILIFY
#define EMAILIFY (string)
Value:
(g_strdelimit ((string), "%", '@'))
Definition at line 2578 of file eom-window.c.
EOM_RECENT_FILES_APP_NAME
#define EOM_RECENT_FILES_APP_NAME "Eye of MATE Image Viewer"
Definition at line 98 of file eom-window.c.
EOM_RECENT_FILES_GROUP
#define EOM_RECENT_FILES_GROUP "Graphics"
Definition at line 97 of file eom-window.c.
EOM_RECENT_FILES_LIMIT
#define EOM_RECENT_FILES_LIMIT 5
Definition at line 99 of file eom-window.c.
EOM_TB_EDITOR_DLG_RESET_RESPONSE
#define EOM_TB_EDITOR_DLG_RESET_RESPONSE 128
Definition at line 2470 of file eom-window.c.
EOM_WALLPAPER_FILENAME
#define EOM_WALLPAPER_FILENAME "eom-wallpaper"
Definition at line 101 of file eom-window.c.
EOM_WINDOW_DEFAULT_HEIGHT
#define EOM_WINDOW_DEFAULT_HEIGHT 450
Definition at line 92 of file eom-window.c.
EOM_WINDOW_DEFAULT_WIDTH
#define EOM_WINDOW_DEFAULT_WIDTH 540
Definition at line 91 of file eom-window.c.
EOM_WINDOW_FULLSCREEN_POPUP_THRESHOLD
#define EOM_WINDOW_FULLSCREEN_POPUP_THRESHOLD 5
Definition at line 95 of file eom-window.c.
EOM_WINDOW_FULLSCREEN_TIMEOUT
#define EOM_WINDOW_FULLSCREEN_TIMEOUT 5 * 1000
Definition at line 94 of file eom-window.c.
EOM_WINDOW_MIN_HEIGHT
#define EOM_WINDOW_MIN_HEIGHT 350
Definition at line 89 of file eom-window.c.
EOM_WINDOW_MIN_WIDTH
#define EOM_WINDOW_MIN_WIDTH 440
Definition at line 88 of file eom-window.c.
is_rtl
#define is_rtl (gtk_widget_get_default_direction () == GTK_TEXT_DIR_RTL)
Definition at line 103 of file eom-window.c.
Referenced by caja_icon_canvas_item_get_drag_surface(), caja_icon_canvas_item_update_bounds(), and G_DEFINE_TYPE_WITH_CODE().
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 85 of file eom-window.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SIGNAL_PREPARED
SIGNAL_LAST
Definition at line 118 of file eom-window.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_COLLECTION_POS
PROP_COLLECTION_RESIZABLE
PROP_STARTUP_FLAGS
Definition at line 111 of file eom-window.c.
EomWindowStatus
enum EomWindowStatus
Enumerator
EOM_WINDOW_STATUS_UNKNOWN
EOM_WINDOW_STATUS_INIT
EOM_WINDOW_STATUS_NORMAL
Definition at line 105 of file eom-window.c.
Function Documentation
eom_window_get_image()
EomImage * eom_window_get_image (EomWindow * window)
eom_window_get_image: @window: an EomWindow.
Gets the image currently displayed in @window or NULL if no image is being displayed.
Returns: (transfer none): an EomImage.
Definition at line 5663 of file eom-window.c.
References EOM_IS_WINDOW, and NULL.
eom_window_get_mode()
EomWindowMode eom_window_get_mode (EomWindow * window)
eom_window_get_mode: @window: An EomWindow.
Gets the mode of @window. See EomWindowMode for details.
Returns: An EomWindowMode.
Definition at line 5517 of file eom-window.c.
References EOM_IS_WINDOW, and EOM_WINDOW_MODE_UNKNOWN.
eom_window_get_properties_dialog()
GtkWidget * eom_window_get_properties_dialog (EomWindow * window)
eom_window_get_properties_dialog: @window: a EomWindow
Gets the @window property dialog. The widget will be built on the first call to this function.
Returns: (transfer none): a #GtkDialog.
Definition at line 3106 of file eom-window.c.
References EOM_CONF_UI_PROPSDIALOG_NETBOOK_MODE, EOM_IS_WINDOW, EOM_PROPERTIES_DIALOG, eom_properties_dialog_new(), eom_properties_dialog_update(), EOM_THUMB_VIEW, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, and NULL.
eom_window_get_sidebar()
GtkWidget * eom_window_get_sidebar (EomWindow * window)
eom_window_get_sidebar: @window: An EomWindow.
Gets the sidebar widget of @window.
Returns: (transfer none): the EomSidebar.
Definition at line 5598 of file eom-window.c.
References EOM_IS_WINDOW, and NULL.
eom_window_get_statusbar()
GtkWidget * eom_window_get_statusbar (EomWindow * window)
eom_window_get_statusbar: @window: an EomWindow.
Gets the statusbar in @window.
Returns: (transfer none): a #EomStatusBar.
Definition at line 5646 of file eom-window.c.
References EOM_IS_WINDOW, and NULL.
eom_window_get_store()
EomListStore * eom_window_get_store (EomWindow * window)
eom_window_get_store: @window: An EomWindow.
Gets the EomListStore that contains the images in the collection of @window.
Returns: (transfer none): an EomListStore.
Definition at line 5566 of file eom-window.c.
References EOM_IS_WINDOW, EOM_LIST_STORE, and NULL.
eom_window_get_thumb_nav()
GtkWidget * eom_window_get_thumb_nav (EomWindow * window)
eom_window_get_thumb_nav: @window: an EomWindow.
Gets the thumbnails navigation pane in @window.
Returns: (transfer none): an EomThumbNav.
Definition at line 5630 of file eom-window.c.
References EOM_IS_WINDOW, and NULL.
eom_window_get_thumb_view()
GtkWidget * eom_window_get_thumb_view (EomWindow * window)
eom_window_get_thumb_view: @window: an EomWindow.
Gets the thumbnails view in @window.
Returns: (transfer none): an EomThumbView.
Definition at line 5614 of file eom-window.c.
References EOM_IS_WINDOW, and NULL.
eom_window_get_ui_manager()
GtkUIManager * eom_window_get_ui_manager (EomWindow * window)
eom_window_get_ui_manager: @window: An EomWindow.
Gets the #GtkUIManager that describes the UI of @window.
Returns: (transfer none): A #GtkUIManager.
Definition at line 5501 of file eom-window.c.
References EOM_IS_WINDOW, and NULL.
eom_window_get_view()
GtkWidget * eom_window_get_view (EomWindow * window)
eom_window_get_view: @window: An EomWindow.
Gets the EomScrollView in the window.
Returns: (transfer none): the EomScrollView.
Definition at line 5582 of file eom-window.c.
References EOM_IS_WINDOW, and NULL.
Referenced by eom_window_reload_image().
eom_window_is_empty()
gboolean eom_window_is_empty (EomWindow * window)
eom_window_is_empty: @window: an EomWindow.
Tells whether @window is currently empty or not.
Returns: TRUE if @window has no images, FALSE otherwise.
Definition at line 5679 of file eom-window.c.
References DEBUG_WINDOW, eom_debug(), EOM_IS_WINDOW, EOM_LIST_STORE, eom_list_store_length(), FALSE, NULL, and TRUE.
eom_window_new()
GtkWidget * eom_window_new (EomStartupFlags flags)
eom_window_new: @flags: the initialization parameters for the new window.
Creates a new and empty EomWindow. Use @flags to indicate if the window should be initialized fullscreen, in slideshow mode, and/or without the thumbnails collection visible. Use preserve-order to maintain the order of input parameters instead of sorting. See EomStartupFlags.
Returns: a newly created EomWindow.
Definition at line 5347 of file eom-window.c.
References DEBUG_WINDOW, EOM_APP, eom_debug(), EOM_TYPE_WINDOW, EOM_WINDOW, FALSE, and NULL.
Referenced by eom_application_open_file_list(), and eom_application_open_window().
eom_window_open_file_list()
void eom_window_open_file_list (EomWindow * window, GSList * file_list)
eom_window_open_file_list: @window: An EomWindow. @file_list: (element-type GFile): A NULL-terminated list of #GFile's.
Opens a list of files, adding them to the collection in @window. Files will be checked to be readable and later filtered according with eom_list_store_add_files().
Definition at line 5471 of file eom-window.c.
References DEBUG_WINDOW, eom_debug(), eom_job_model_new(), eom_job_queue_add_job(), EOM_STARTUP_PRESERVE_ORDER, EOM_WINDOW_STATUS_INIT, file_list, and NULL.
Referenced by eom_application_open_file_list().
eom_window_reload_image()
void eom_window_reload_image (EomWindow * window)
Definition at line 5698 of file eom-window.c.
References EOM_IS_WINDOW, EOM_SCROLL_VIEW, eom_scroll_view_set_image(), EOM_THUMB_VIEW, EOM_THUMB_VIEW_SELECT_CURRENT, eom_thumb_view_select_single(), eom_window_get_view(), and NULL.
eom_window_set_mode()
void eom_window_set_mode (EomWindow * window, EomWindowMode mode)
eom_window_set_mode: @window: an EomWindow. @mode: an EomWindowMode value.
Changes the mode of @window to normal, fullscreen, or slideshow. See EomWindowMode for details.
Definition at line 5533 of file eom-window.c.
References EOM_IS_WINDOW, EOM_WINDOW_MODE_FULLSCREEN, EOM_WINDOW_MODE_NORMAL, EOM_WINDOW_MODE_SLIDESHOW, EOM_WINDOW_MODE_UNKNOWN, FALSE, and TRUE.
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (EomWindow , eom_window , GTK_TYPE_APPLICATION_WINDOW)
References action, data, proxy, and user_data.