MATE Desktop Environment: eom-transform.c File Reference
eom-transform.c File Reference
#include <time.h>
#include <stdlib.h>
#include <math.h>
#include <gtk/gtk.h>
#include <cairo/cairo.h>
#include "eom-transform.h"
#include "eom-jobs.h"
Macros
#define EOM_TRANSFORM_N_PROG_UPDATES 20
#define EOM_DEG_TO_RAD(degree)
#define DOUBLE_EQUAL_MAX_DIFF 1e-6
#define DOUBLE_EQUAL(a, b)
Functions
GdkPixbuf * eom_transform_apply (EomTransform *trans, GdkPixbuf *pixbuf, EomJob *job)
EomTransform * eom_transform_reverse (EomTransform *trans)
EomTransform * eom_transform_compose (EomTransform *trans, EomTransform *compose)
gboolean eom_transform_is_identity (EomTransform *trans)
EomTransform * eom_transform_identity_new (void)
EomTransform * eom_transform_rotate_new (int degree)
EomTransform * eom_transform_flip_new (EomTransformType type)
EomTransform * eom_transform_new (EomTransformType type)
EomTransformType eom_transform_get_transform_type (EomTransform *trans)
gboolean eom_transform_get_affine (EomTransform *trans, cairo_matrix_t *affine)
Macro Definition Documentation
DOUBLE_EQUAL
#define DOUBLE_EQUAL (a, b)
Value:
(fabs (a - b) < DOUBLE_EQUAL_MAX_DIFF)
Definition at line 208 of file eom-transform.c.
DOUBLE_EQUAL_MAX_DIFF
#define DOUBLE_EQUAL_MAX_DIFF 1e-6
Definition at line 207 of file eom-transform.c.
EOM_DEG_TO_RAD
#define EOM_DEG_TO_RAD (degree)
Value:
((degree) * (G_PI/180.0))
Definition at line 48 of file eom-transform.c.
Referenced by eom_transform_get_transform_type(), and eom_transform_rotate_new().
EOM_TRANSFORM_N_PROG_UPDATES
#define EOM_TRANSFORM_N_PROG_UPDATES 20
Definition at line 36 of file eom-transform.c.
Referenced by eom_transform_apply().
Function Documentation
eom_transform_apply()
GdkPixbuf * eom_transform_apply (EomTransform * trans, GdkPixbuf * pixbuf, EomJob * job)
eom_transform_apply: @trans: a EomTransform @pixbuf: a #GdkPixbuf @job: a EomJob
Applies the transformation in @trans to @pixbuf, setting its progress in @job.
Returns: (transfer full): A new #GdkPixbuf with the transformation applied.
Definition at line 75 of file eom-transform.c.
References dest, eom_job_set_progress(), EOM_TRANSFORM_N_PROG_UPDATES, MAX, MIN, NULL, and _EomTransform::priv.
Referenced by eom_image_set_thumbnail().
eom_transform_compose()
EomTransform * eom_transform_compose (EomTransform * trans, EomTransform * compose)
eom_transform_compose: @trans: a EomTransform @compose: another EomTransform
Returns: (transfer full): a new transform
Definition at line 264 of file eom-transform.c.
References EOM_IS_TRANSFORM, EOM_TRANSFORM, EOM_TYPE_TRANSFORM, NULL, and _EomTransform::priv.
Referenced by eom_transform_new().
eom_transform_flip_new()
EomTransform * eom_transform_flip_new (EomTransformType type)
Definition at line 315 of file eom-transform.c.
References EOM_TRANSFORM, EOM_TRANSFORM_FLIP_HORIZONTAL, EOM_TRANSFORM_FLIP_VERTICAL, EOM_TYPE_TRANSFORM, NULL, and _EomTransform::priv.
Referenced by eom_transform_new().
eom_transform_get_affine()
gboolean eom_transform_get_affine (EomTransform * trans, cairo_matrix_t * affine)
Definition at line 438 of file eom-transform.c.
References EOM_IS_TRANSFORM, FALSE, _EomTransform::priv, and TRUE.
eom_transform_get_transform_type()
EomTransformType eom_transform_get_transform_type (EomTransform * trans)
Definition at line 382 of file eom-transform.c.
References EOM_DEG_TO_RAD, EOM_IS_TRANSFORM, EOM_TRANSFORM_FLIP_HORIZONTAL, EOM_TRANSFORM_FLIP_VERTICAL, EOM_TRANSFORM_NONE, EOM_TRANSFORM_ROT_180, EOM_TRANSFORM_ROT_270, EOM_TRANSFORM_ROT_90, EOM_TRANSFORM_TRANSPOSE, EOM_TRANSFORM_TRANSVERSE, FALSE, _EomTransform::priv, and TRUE.
eom_transform_identity_new()
EomTransform * eom_transform_identity_new (void)
Definition at line 291 of file eom-transform.c.
References EOM_TRANSFORM, EOM_TYPE_TRANSFORM, NULL, and _EomTransform::priv.
Referenced by eom_transform_new().
eom_transform_is_identity()
gboolean eom_transform_is_identity (EomTransform * trans)
Definition at line 281 of file eom-transform.c.
References EOM_IS_TRANSFORM, FALSE, and _EomTransform::priv.
Referenced by eom_image_undo().
eom_transform_new()
EomTransform * eom_transform_new (EomTransformType type)
Definition at line 335 of file eom-transform.c.
References eom_transform_compose(), EOM_TRANSFORM_FLIP_HORIZONTAL, eom_transform_flip_new(), EOM_TRANSFORM_FLIP_VERTICAL, eom_transform_identity_new(), EOM_TRANSFORM_NONE, EOM_TRANSFORM_ROT_180, EOM_TRANSFORM_ROT_270, EOM_TRANSFORM_ROT_90, eom_transform_rotate_new(), EOM_TRANSFORM_TRANSPOSE, EOM_TRANSFORM_TRANSVERSE, and NULL.
eom_transform_reverse()
EomTransform * eom_transform_reverse (EomTransform * trans)
eom_transform_reverse: @trans: a EomTransform
Creates the reverse transformation of @trans
Returns: (transfer full): a new transformation
Definition at line 239 of file eom-transform.c.
References EOM_IS_TRANSFORM, EOM_TRANSFORM, EOM_TYPE_TRANSFORM, NULL, and _EomTransform::priv.
Referenced by eom_image_undo().
eom_transform_rotate_new()
EomTransform * eom_transform_rotate_new (int degree)
Definition at line 303 of file eom-transform.c.
References EOM_DEG_TO_RAD, EOM_TRANSFORM, EOM_TYPE_TRANSFORM, NULL, and _EomTransform::priv.
Referenced by eom_transform_new().