MATE Desktop Environment: eom-scroll-view.c File Reference
eom-scroll-view.c File Reference
#include <stdlib.h>
#include <math.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gdk/gdkkeysyms.h>
#include "eom-config-keys.h"
#include "eom-enum-types.h"
#include "eom-marshal.h"
#include "eom-scroll-view.h"
#include "eom-debug.h"
#include "zoom.h"
#include <gdk/gdk.h>
Macros
#define SCROLL_STEP_SIZE 32
#define MAX_ZOOM_FACTOR 20
#define MIN_ZOOM_FACTOR 0.02
#define CHECK_MEDIUM 8
#define CHECK_BLACK "#000000"
#define CHECK_GRAY "#808080"
#define CHECK_LIGHT "#cccccc"
#define IMAGE_VIEW_ZOOM_MULTIPLIER 1.05
#define DOUBLE_EQUAL_MAX_DIFF 1e-6
#define DOUBLE_EQUAL(a, b)
Enumerations
enum ZoomMode { ZOOM_MODE_FIT , ZOOM_MODE_FREE }
enum { SIGNAL_ZOOM_CHANGED , SIGNAL_LAST }
enum EomScrollViewCursor { EOM_SCROLL_VIEW_CURSOR_NORMAL , EOM_SCROLL_VIEW_CURSOR_HIDDEN , EOM_SCROLL_VIEW_CURSOR_DRAG }
enum {
PROP_0 , PROP_ANTIALIAS_IN , PROP_ANTIALIAS_OUT , PROP_BACKGROUND_COLOR ,
PROP_IMAGE , PROP_SCROLLWHEEL_ZOOM , PROP_TRANSP_COLOR , PROP_TRANSPARENCY_STYLE ,
PROP_USE_BG_COLOR , PROP_ZOOM_MULTIPLIER
}
Functions
void eom_scroll_view_hide_cursor (EomScrollView *view)
void eom_scroll_view_show_cursor (EomScrollView *view)
void eom_scroll_view_set_zoom_upscale (EomScrollView *view, gboolean upscale)
void eom_scroll_view_set_antialiasing_in (EomScrollView *view, gboolean state)
void eom_scroll_view_set_antialiasing_out (EomScrollView *view, gboolean state)
void eom_scroll_view_set_transparency_color (EomScrollView *view, GdkRGBA *color)
void eom_scroll_view_set_transparency (EomScrollView *view, EomTransparencyStyle style)
void eom_scroll_view_zoom_in (EomScrollView *view, gboolean smooth)
void eom_scroll_view_zoom_out (EomScrollView *view, gboolean smooth)
void eom_scroll_view_zoom_fit (EomScrollView *view)
void eom_scroll_view_set_zoom (EomScrollView *view, double zoom)
double eom_scroll_view_get_zoom (EomScrollView *view)
gboolean eom_scroll_view_get_zoom_is_min (EomScrollView *view)
gboolean eom_scroll_view_get_zoom_is_max (EomScrollView *view)
void eom_scroll_view_set_image (EomScrollView *view, EomImage *image)
EomImage * eom_scroll_view_get_image (EomScrollView *view)
gboolean eom_scroll_view_scrollbars_visible (EomScrollView *view)
GtkWidget * eom_scroll_view_new (void)
void eom_scroll_view_set_popup (EomScrollView *view, GtkMenu *menu)
void eom_scroll_view_set_background_color (EomScrollView *view, const GdkRGBA *color)
void eom_scroll_view_override_bg_color (EomScrollView *view, const GdkRGBA *color)
void eom_scroll_view_set_use_bg_color (EomScrollView *view, gboolean use)
void eom_scroll_view_set_scroll_wheel_zoom (EomScrollView *view, gboolean scroll_wheel_zoom)
void eom_scroll_view_set_zoom_multiplier (EomScrollView *view, gdouble zoom_multiplier)
Macro Definition Documentation
CHECK_BLACK
#define CHECK_BLACK "#000000"
Definition at line 30 of file eom-scroll-view.c.
CHECK_GRAY
#define CHECK_GRAY "#808080"
Definition at line 31 of file eom-scroll-view.c.
CHECK_LIGHT
#define CHECK_LIGHT "#cccccc"
Definition at line 32 of file eom-scroll-view.c.
CHECK_MEDIUM
#define CHECK_MEDIUM 8
Definition at line 29 of file eom-scroll-view.c.
DOUBLE_EQUAL
#define DOUBLE_EQUAL (a, b)
Value:
(fabs (a - b) < DOUBLE_EQUAL_MAX_DIFF)
Definition at line 457 of file eom-scroll-view.c.
Referenced by eom_scroll_view_get_zoom_is_max(), and eom_scroll_view_get_zoom_is_min().
DOUBLE_EQUAL_MAX_DIFF
#define DOUBLE_EQUAL_MAX_DIFF 1e-6
Definition at line 456 of file eom-scroll-view.c.
Referenced by eom_scroll_view_zoom_in(), and eom_scroll_view_zoom_out().
IMAGE_VIEW_ZOOM_MULTIPLIER
#define IMAGE_VIEW_ZOOM_MULTIPLIER 1.05
Definition at line 38 of file eom-scroll-view.c.
MAX_ZOOM_FACTOR
#define MAX_ZOOM_FACTOR 20
Definition at line 26 of file eom-scroll-view.c.
Referenced by eom_scroll_view_get_zoom_is_max().
MIN_ZOOM_FACTOR
#define MIN_ZOOM_FACTOR 0.02
Definition at line 27 of file eom-scroll-view.c.
Referenced by eom_scroll_view_get_zoom_is_min().
SCROLL_STEP_SIZE
#define SCROLL_STEP_SIZE 32
Definition at line 23 of file eom-scroll-view.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SIGNAL_ZOOM_CHANGED
SIGNAL_LAST
Definition at line 47 of file eom-scroll-view.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_ANTIALIAS_IN
PROP_ANTIALIAS_OUT
PROP_BACKGROUND_COLOR
PROP_IMAGE
PROP_SCROLLWHEEL_ZOOM
PROP_TRANSP_COLOR
PROP_TRANSPARENCY_STYLE
PROP_USE_BG_COLOR
PROP_ZOOM_MULTIPLIER
Definition at line 65 of file eom-scroll-view.c.
EomScrollViewCursor
enum EomScrollViewCursor
Enumerator
EOM_SCROLL_VIEW_CURSOR_NORMAL
EOM_SCROLL_VIEW_CURSOR_HIDDEN
EOM_SCROLL_VIEW_CURSOR_DRAG
Definition at line 54 of file eom-scroll-view.c.
ZoomMode
enum ZoomMode
Enumerator
ZOOM_MODE_FIT
ZOOM_MODE_FREE
Definition at line 41 of file eom-scroll-view.c.
Function Documentation
eom_scroll_view_get_image()
EomImage * eom_scroll_view_get_image (EomScrollView * view)
eom_scroll_view_get_image: @view: An EomScrollView.
Gets the the currently displayed EomImage.
Returns: (transfer full): An EomImage.
Definition at line 1739 of file eom-scroll-view.c.
References EOM_IS_SCROLL_VIEW, NULL, and _EomScrollView::priv.
eom_scroll_view_get_zoom()
double eom_scroll_view_get_zoom (EomScrollView * view)
Definition at line 1642 of file eom-scroll-view.c.
References EOM_IS_SCROLL_VIEW, and _EomScrollView::priv.
eom_scroll_view_get_zoom_is_max()
gboolean eom_scroll_view_get_zoom_is_max (EomScrollView * view)
Definition at line 1661 of file eom-scroll-view.c.
References DOUBLE_EQUAL, EOM_IS_SCROLL_VIEW, FALSE, MAX_ZOOM_FACTOR, and _EomScrollView::priv.
eom_scroll_view_get_zoom_is_min()
gboolean eom_scroll_view_get_zoom_is_min (EomScrollView * view)
Definition at line 1650 of file eom-scroll-view.c.
References DOUBLE_EQUAL, EOM_IS_SCROLL_VIEW, FALSE, MIN_ZOOM_FACTOR, and _EomScrollView::priv.
eom_scroll_view_hide_cursor()
void eom_scroll_view_hide_cursor (EomScrollView * view)
Definition at line 1422 of file eom-scroll-view.c.
References EOM_SCROLL_VIEW_CURSOR_HIDDEN.
eom_scroll_view_new()
GtkWidget * eom_scroll_view_new (void)
Definition at line 2240 of file eom-scroll-view.c.
References EOM_TYPE_SCROLL_VIEW, FALSE, NULL, and TRUE.
eom_scroll_view_override_bg_color()
void eom_scroll_view_override_bg_color (EomScrollView * view, const GdkRGBA * color)
Definition at line 2341 of file eom-scroll-view.c.
References EOM_IS_SCROLL_VIEW, and _EomScrollView::priv.
eom_scroll_view_scrollbars_visible()
gboolean eom_scroll_view_scrollbars_visible (EomScrollView * view)
Definition at line 1754 of file eom-scroll-view.c.
References FALSE, _EomScrollView::priv, and TRUE.
eom_scroll_view_set_antialiasing_in()
void eom_scroll_view_set_antialiasing_in (EomScrollView * view, gboolean state)
Definition at line 1454 of file eom-scroll-view.c.
References EOM_IS_SCROLL_VIEW, and _EomScrollView::priv.
eom_scroll_view_set_antialiasing_out()
void eom_scroll_view_set_antialiasing_out (EomScrollView * view, gboolean state)
Definition at line 1473 of file eom-scroll-view.c.
References EOM_IS_SCROLL_VIEW, and _EomScrollView::priv.
eom_scroll_view_set_background_color()
void eom_scroll_view_set_background_color (EomScrollView * view, const GdkRGBA * color)
Definition at line 2331 of file eom-scroll-view.c.
References EOM_IS_SCROLL_VIEW, and _EomScrollView::priv.
eom_scroll_view_set_image()
void eom_scroll_view_set_image (EomScrollView * view, EomImage * image)
Definition at line 1685 of file eom-scroll-view.c.
References eom_image_data_ref(), eom_image_get_pixbuf(), eom_image_is_animation(), eom_image_start_animation(), EOM_IS_SCROLL_VIEW, NULL, _EomScrollView::priv, and TRUE.
Referenced by eom_window_reload_image().
eom_scroll_view_set_popup()
void eom_scroll_view_set_popup (EomScrollView * view, GtkMenu * menu)
Definition at line 2272 of file eom-scroll-view.c.
References EOM_IS_SCROLL_VIEW, NULL, and _EomScrollView::priv.
eom_scroll_view_set_scroll_wheel_zoom()
void eom_scroll_view_set_scroll_wheel_zoom (EomScrollView * view, gboolean scroll_wheel_zoom)
Definition at line 2369 of file eom-scroll-view.c.
References EOM_IS_SCROLL_VIEW, and _EomScrollView::priv.
eom_scroll_view_set_transparency()
void eom_scroll_view_set_transparency (EomScrollView * view, EomTransparencyStyle style)
Definition at line 1527 of file eom-scroll-view.c.
References EOM_IS_SCROLL_VIEW, and _EomScrollView::priv.
eom_scroll_view_set_transparency_color()
void eom_scroll_view_set_transparency_color (EomScrollView * view, GdkRGBA * color)
Definition at line 1509 of file eom-scroll-view.c.
References EOM_IS_SCROLL_VIEW, EOM_TRANSP_COLOR, and _EomScrollView::priv.
eom_scroll_view_set_use_bg_color()
void eom_scroll_view_set_use_bg_color (EomScrollView * view, gboolean use)
Definition at line 2351 of file eom-scroll-view.c.
References EOM_IS_SCROLL_VIEW, and _EomScrollView::priv.
eom_scroll_view_set_zoom()
void eom_scroll_view_set_zoom (EomScrollView * view, double zoom)
Definition at line 1634 of file eom-scroll-view.c.
References EOM_IS_SCROLL_VIEW, and FALSE.
eom_scroll_view_set_zoom_multiplier()
void eom_scroll_view_set_zoom_multiplier (EomScrollView * view, gdouble zoom_multiplier)
Definition at line 2381 of file eom-scroll-view.c.
References EOM_IS_SCROLL_VIEW, and _EomScrollView::priv.
eom_scroll_view_set_zoom_upscale()
void eom_scroll_view_set_zoom_upscale (EomScrollView * view, gboolean upscale)
Definition at line 1435 of file eom-scroll-view.c.
References EOM_IS_SCROLL_VIEW, _EomScrollView::priv, and ZOOM_MODE_FIT.
eom_scroll_view_show_cursor()
void eom_scroll_view_show_cursor (EomScrollView * view)
Definition at line 1428 of file eom-scroll-view.c.
References EOM_SCROLL_VIEW_CURSOR_NORMAL.
eom_scroll_view_zoom_fit()
void eom_scroll_view_zoom_fit (EomScrollView * view)
Definition at line 1624 of file eom-scroll-view.c.
References EOM_IS_SCROLL_VIEW, NULL, and _EomScrollView::priv.
eom_scroll_view_zoom_in()
void eom_scroll_view_zoom_in (EomScrollView * view, gboolean smooth)
Definition at line 1554 of file eom-scroll-view.c.
References DOUBLE_EQUAL_MAX_DIFF, EOM_IS_SCROLL_VIEW, FALSE, and _EomScrollView::priv.
eom_scroll_view_zoom_out()
void eom_scroll_view_zoom_out (EomScrollView * view, gboolean smooth)
Definition at line 1590 of file eom-scroll-view.c.
References DOUBLE_EQUAL_MAX_DIFF, EOM_IS_SCROLL_VIEW, FALSE, and _EomScrollView::priv.