MATE Desktop Environment: eom-thumb-nav.c File Reference
eom-thumb-nav.c File Reference
#include "eom-thumb-nav.h"
#include "eom-thumb-view.h"
#include <glib.h>
#include <glib/gi18n.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <math.h>
#include <string.h>
Macros
#define EOM_THUMB_NAV_SCROLL_INC 20
#define EOM_THUMB_NAV_SCROLL_TIMEOUT 20
Enumerations
enum { PROP_0 , PROP_SHOW_BUTTONS , PROP_THUMB_VIEW , PROP_MODE }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (EomThumbNav, eom_thumb_nav, GTK_TYPE_BOX)
GtkWidget * eom_thumb_nav_new (GtkWidget *thumbview, EomThumbNavMode mode, gboolean show_buttons)
gboolean eom_thumb_nav_get_show_buttons (EomThumbNav *nav)
void eom_thumb_nav_set_show_buttons (EomThumbNav *nav, gboolean show_buttons)
EomThumbNavMode eom_thumb_nav_get_mode (EomThumbNav *nav)
void eom_thumb_nav_set_mode (EomThumbNav *nav, EomThumbNavMode mode)
Macro Definition Documentation
EOM_THUMB_NAV_SCROLL_INC
#define EOM_THUMB_NAV_SCROLL_INC 20
Definition at line 36 of file eom-thumb-nav.c.
Referenced by G_DEFINE_TYPE_WITH_PRIVATE().
EOM_THUMB_NAV_SCROLL_TIMEOUT
#define EOM_THUMB_NAV_SCROLL_TIMEOUT 20
Definition at line 37 of file eom-thumb-nav.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_SHOW_BUTTONS
PROP_THUMB_VIEW
PROP_MODE
Definition at line 39 of file eom-thumb-nav.c.
Function Documentation
eom_thumb_nav_get_mode()
EomThumbNavMode eom_thumb_nav_get_mode (EomThumbNav * nav)
eom_thumb_nav_get_mode: @nav: an EomThumbNav.
Gets the navigation mode in @nav.
Returns: A value in EomThumbNavMode.
Definition at line 517 of file eom-thumb-nav.c.
References EOM_IS_THUMB_NAV, FALSE, and _EomThumbNav::priv.
eom_thumb_nav_get_show_buttons()
gboolean eom_thumb_nav_get_show_buttons (EomThumbNav * nav)
eom_thumb_nav_get_show_buttons: @nav: an EomThumbNav.
Gets whether the navigation buttons are visible.
Returns: TRUE if the navigation buttons are visible, FALSE otherwise.
Definition at line 474 of file eom-thumb-nav.c.
References EOM_IS_THUMB_NAV, FALSE, and _EomThumbNav::priv.
eom_thumb_nav_new()
GtkWidget * eom_thumb_nav_new (GtkWidget * thumbview, EomThumbNavMode mode, gboolean show_buttons)
eom_thumb_nav_new: @thumbview: an EomThumbView to embed in the navigation widget. @mode: The navigation mode. @show_buttons: Whether to show the navigation buttons.
Creates a new thumbnail navigation widget.
Returns: a new EomThumbNav object.
Definition at line 447 of file eom-thumb-nav.c.
References EOM_TYPE_THUMB_NAV, FALSE, and NULL.
eom_thumb_nav_set_mode()
void eom_thumb_nav_set_mode (EomThumbNav * nav, EomThumbNavMode mode)
eom_thumb_nav_set_mode: @nav: An EomThumbNav. @mode: One of EomThumbNavMode.
Sets the navigation mode in @nav. See EomThumbNavMode for details.
Definition at line 532 of file eom-thumb-nav.c.
References EOM_IS_THUMB_NAV, EOM_THUMB_NAV_MODE_MULTIPLE_COLUMNS, EOM_THUMB_NAV_MODE_MULTIPLE_ROWS, EOM_THUMB_NAV_MODE_ONE_COLUMN, EOM_THUMB_NAV_MODE_ONE_ROW, eom_thumb_nav_set_show_buttons(), EOM_THUMB_VIEW, eom_thumb_view_set_item_height(), and _EomThumbNav::priv.
eom_thumb_nav_set_show_buttons()
void eom_thumb_nav_set_show_buttons (EomThumbNav * nav, gboolean show_buttons)
eom_thumb_nav_set_show_buttons: @nav: an EomThumbNav. @show_buttons: TRUE to show the buttons, FALSE to hide them.
Sets whether the navigation buttons to the left and right of the widget should be visible.
Definition at line 490 of file eom-thumb-nav.c.
References EOM_IS_THUMB_NAV, EOM_THUMB_NAV_MODE_ONE_ROW, NULL, and _EomThumbNav::priv.
Referenced by eom_thumb_nav_set_mode().
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (EomThumbNav , eom_thumb_nav , GTK_TYPE_BOX)
References EOM_THUMB_NAV_MODE_ONE_ROW, EOM_THUMB_NAV_SCROLL_INC, FALSE, set, and user_data.