MATE Desktop Environment: eom-uri-converter.c File Reference
eom-uri-converter.c File Reference
#include <math.h>
#include <string.h>
#include <glib.h>
#include "eom-uri-converter.h"
#include "eom-pixbuf-util.h"
Enumerations
enum {
PROP_0 , PROP_CONVERT_SPACES , PROP_SPACE_CHARACTER , PROP_COUNTER_START ,
PROP_COUNTER_N_DIGITS , PROP_N_IMAGES
}
enum { PARSER_NONE , PARSER_STRING , PARSER_TOKEN }
Functions
GQuark eom_uc_error_quark (void)
void eom_uri_converter_print_list (EomURIConverter *conv)
EomURIConverter * eom_uri_converter_new (GFile *base_file, GdkPixbufFormat *img_format, const char *format_str)
gboolean eom_uri_converter_do (EomURIConverter *conv, EomImage *image, GFile **file, GdkPixbufFormat **format, GError **error)
char * eom_uri_converter_preview (const char *format_str, EomImage *img, GdkPixbufFormat *format, gulong counter, guint n_images, gboolean convert_spaces, gunichar space_char)
gboolean eom_uri_converter_requires_exif (EomURIConverter *converter)
gboolean eom_uri_converter_check (EomURIConverter *converter, GList *img_list, GError **error)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PARSER_NONE
PARSER_STRING
PARSER_TOKEN
Definition at line 259 of file eom-uri-converter.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_CONVERT_SPACES
PROP_SPACE_CHARACTER
PROP_COUNTER_START
PROP_COUNTER_N_DIGITS
PROP_N_IMAGES
Definition at line 12 of file eom-uri-converter.c.
Function Documentation
eom_uc_error_quark()
GQuark eom_uc_error_quark (void)
Definition at line 160 of file eom-uri-converter.c.
eom_uri_converter_check()
gboolean eom_uri_converter_check (EomURIConverter * converter, GList * img_list, GError ** error)
eom_uri_converter_check: @converter: a EomURIConverter @img_list: (element-type GFile): a #Gfile list @error: a #GError location to store the error occurring, or NULL to ignore
Definition at line 937 of file eom-uri-converter.c.
References _, EOM_IMAGE, EOM_IS_URI_CONVERTER, EOM_UC_ERROR, EOM_UC_ERROR_EQUAL_FILENAMES, eom_uri_converter_do(), error, FALSE, file_list, NULL, and TRUE.
eom_uri_converter_do()
gboolean eom_uri_converter_do (EomURIConverter * conv, EomImage * image, GFile ** file, GdkPixbufFormat ** format, GError ** error)
Definition at line 713 of file eom-uri-converter.c.
References EOM_IS_URI_CONVERTER, EOM_UC_COMMENT, EOM_UC_COUNTER, EOM_UC_DATE, EOM_UC_DAY, EOM_UC_FILENAME, EOM_UC_HOUR, EOM_UC_MINUTE, EOM_UC_MONTH, EOM_UC_SECOND, EOM_UC_STRING, EOM_UC_TIME, EOM_UC_YEAR, error, FALSE, NULL, _EomURIConverter::priv, and TRUE.
Referenced by eom_uri_converter_check().
eom_uri_converter_new()
EomURIConverter * eom_uri_converter_new (GFile * base_file, GdkPixbufFormat * img_format, const char * format_str)
Definition at line 499 of file eom-uri-converter.c.
References EOM_TYPE_URI_CONVERTER, NULL, and _EomURIConverter::priv.
Referenced by eom_save_as_dialog_get_converter().
eom_uri_converter_preview()
char * eom_uri_converter_preview (const char * format_str, EomImage * img, GdkPixbufFormat * format, gulong counter, guint n_images, gboolean convert_spaces, gunichar space_char)
Definition at line 800 of file eom-uri-converter.c.
References eom_image_get_file(), EOM_IS_IMAGE, eom_pixbuf_get_common_suffix(), EOM_UC_COMMENT, EOM_UC_DATE, EOM_UC_DAY, EOM_UC_HOUR, EOM_UC_MINUTE, EOM_UC_MONTH, EOM_UC_SECOND, EOM_UC_TIME, EOM_UC_YEAR, FALSE, MAX, MIN, name, NULL, and TRUE.
eom_uri_converter_print_list()
void eom_uri_converter_print_list (EomURIConverter * conv)
Definition at line 433 of file eom-uri-converter.c.
References EOM_UC_COMMENT, EOM_UC_COUNTER, EOM_UC_DATE, EOM_UC_DAY, EOM_UC_FILENAME, EOM_UC_HOUR, EOM_UC_MINUTE, EOM_UC_MONTH, EOM_UC_SECOND, EOM_UC_STRING, EOM_UC_TIME, EOM_UC_YEAR, EOM_URI_CONVERTER, NULL, and _EomURIConverter::priv.
eom_uri_converter_requires_exif()
gboolean eom_uri_converter_requires_exif (EomURIConverter * converter)
Definition at line 922 of file eom-uri-converter.c.
References EOM_IS_URI_CONVERTER, FALSE, and _EomURIConverter::priv.