MATE Desktop Environment: eom-thumb-view.c File Reference
eom-thumb-view.c File Reference
#include "eom-thumb-view.h"
#include "eom-list-store.h"
#include "eom-image.h"
#include "eom-job-queue.h"
#include "eom-util.h"
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <stdlib.h>
#include <string.h>
Macros
#define EOM_THUMB_VIEW_SPACING 0
Enumerations
enum { PROP_0 , PROP_ORIENTATION }
Functions
G_DEFINE_TYPE_WITH_CODE (EomThumbView, eom_thumb_view, GTK_TYPE_ICON_VIEW, G_IMPLEMENT_INTERFACE(GTK_TYPE_ORIENTABLE, NULL) G_ADD_PRIVATE(EomThumbView))
GtkWidget * eom_thumb_view_new (void)
void eom_thumb_view_set_model (EomThumbView *thumbview, EomListStore *store)
void eom_thumb_view_set_item_height (EomThumbView *thumbview, gint height)
guint eom_thumb_view_get_n_selected (EomThumbView *thumbview)
EomImage * eom_thumb_view_get_first_selected_image (EomThumbView *thumbview)
GList * eom_thumb_view_get_selected_images (EomThumbView *thumbview)
void eom_thumb_view_set_current_image (EomThumbView *thumbview, EomImage *image, gboolean deselect_other)
void eom_thumb_view_select_single (EomThumbView *thumbview, EomThumbViewSelectionChange change)
void eom_thumb_view_set_thumbnail_popup (EomThumbView *thumbview, GtkMenu *menu)
Macro Definition Documentation
EOM_THUMB_VIEW_SPACING
#define EOM_THUMB_VIEW_SPACING 0
Definition at line 47 of file eom-thumb-view.c.
Referenced by G_DEFINE_TYPE_WITH_CODE().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_ORIENTATION
Definition at line 42 of file eom-thumb-view.c.
Function Documentation
eom_thumb_view_get_first_selected_image()
EomImage * eom_thumb_view_get_first_selected_image (EomThumbView * thumbview)
eom_thumb_view_get_first_selected_image: @thumbview: A EomThumbView.
Returns the first selected image. Note that the returned EomImage is not ensured to be really the first selected image in @thumbview, but generally, it will be.
Returns: (transfer full): A EomImage.
Definition at line 851 of file eom-thumb-view.c.
References NULL.
eom_thumb_view_get_n_selected()
guint eom_thumb_view_get_n_selected (EomThumbView * thumbview)
eom_thumb_view_get_n_selected: @thumbview: An EomThumbView.
Gets the number of images that are currently selected in @thumbview.
Returns: the number of selected images in @thumbview.
Definition at line 804 of file eom-thumb-view.c.
Referenced by eom_thumb_view_select_single().
eom_thumb_view_get_selected_images()
GList * eom_thumb_view_get_selected_images (EomThumbView * thumbview)
eom_thumb_view_get_selected_images: @thumbview: A EomThumbView.
Gets a list with the currently selected images. Note that a new reference is hold for each image and the list must be freed with g_list_free().
Returns: (element-type EomImage) (transfer full): A newly allocated list of EomImage's.
Definition at line 883 of file eom-thumb-view.c.
References item, and NULL.
eom_thumb_view_new()
GtkWidget * eom_thumb_view_new (void)
eom_thumb_view_new:
Creates a new EomThumbView object.
Returns: a newly created EomThumbView.
Definition at line 662 of file eom-thumb-view.c.
References EOM_TYPE_THUMB_VIEW, and NULL.
eom_thumb_view_select_single()
void eom_thumb_view_select_single (EomThumbView * thumbview, EomThumbViewSelectionChange change)
eom_thumb_view_select_single: @thumbview: A EomThumbView. @change: A EomThumbViewSelectionChange, describing the desired selection change.
Changes the current selection according to a single movement described by EomThumbViewSelectionChange. If there are no thumbnails currently selected, one is selected according to the natural selection according to the EomThumbViewSelectionChange used, p.g., when EOM_THUMB_VIEW_SELECT_RIGHT is the selected change, the first thumbnail will be selected.
Definition at line 957 of file eom-thumb-view.c.
References EOM_IS_THUMB_VIEW, EOM_LIST_STORE, eom_list_store_length(), eom_thumb_view_get_n_selected(), EOM_THUMB_VIEW_SELECT_CURRENT, EOM_THUMB_VIEW_SELECT_FIRST, EOM_THUMB_VIEW_SELECT_LAST, EOM_THUMB_VIEW_SELECT_LEFT, EOM_THUMB_VIEW_SELECT_RANDOM, EOM_THUMB_VIEW_SELECT_RIGHT, FALSE, and NULL.
Referenced by eom_window_reload_image().
eom_thumb_view_set_current_image()
void eom_thumb_view_set_current_image (EomThumbView * thumbview, EomImage * image, gboolean deselect_other)
eom_thumb_view_set_current_image: @thumbview: A EomThumbView. The image to be selected. @deselect_other: Whether to deselect currently selected images.
Changes the status of a image, marking it as currently selected. If @deselect_other is TRUE, all other selected images will be deselected.
Definition at line 916 of file eom-thumb-view.c.
References EOM_LIST_STORE, eom_list_store_get_pos_by_image(), FALSE, and NULL.
eom_thumb_view_set_item_height()
void eom_thumb_view_set_item_height (EomThumbView * thumbview, gint height)
eom_thumb_view_set_item_height: @thumbview: A EomThumbView. @height: The desired height.
Sets the height of each thumbnail in @thumbview.
Definition at line 777 of file eom-thumb-view.c.
References EOM_IS_THUMB_VIEW, NULL, and _EomThumbView::priv.
Referenced by eom_thumb_nav_set_mode().
eom_thumb_view_set_model()
void eom_thumb_view_set_model (EomThumbView * thumbview, EomListStore * store)
eom_thumb_view_set_model: @thumbview: A EomThumbView. @store: A EomListStore.
Sets the EomListStore to be used with @thumbview. If an initial image was set during @store creation, its thumbnail will be selected and visible.
Definition at line 718 of file eom-thumb-view.c.
References EOM_IS_LIST_STORE, EOM_IS_THUMB_VIEW, eom_list_store_get_initial_pos(), eom_list_store_length(), FALSE, NULL, and _EomThumbView::priv.
eom_thumb_view_set_thumbnail_popup()
void eom_thumb_view_set_thumbnail_popup (EomThumbView * thumbview, GtkMenu * menu)
eom_thumb_view_set_thumbnail_popup: @thumbview: An EomThumbView. @menu: A #GtkMenu.
Set the contextual menu to be used with the thumbnails in the widget. This can be done only once.
Definition at line 1046 of file eom-thumb-view.c.
References EOM_IS_THUMB_VIEW, NULL, and _EomThumbView::priv.
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (EomThumbView , eom_thumb_view , GTK_TYPE_ICON_VIEW , G_IMPLEMENT_INTERFACE(GTK_TYPE_ORIENTABLE, NULL) G_ADD_PRIVATE(EomThumbView))
References EOM_LIST_STORE_THUMBNAIL, EOM_THUMB_VIEW_SPACING, FALSE, G_OBJECT_CLASS(), NULL, and TRUE.