MATE Desktop Environment: eom-print-preview.c File Reference
eom-print-preview.c File Reference
#include <gtk/gtk.h>
#include <cairo.h>
#include <gdk/gdkkeysyms.h>
#include "eom-image.h"
#include "eom-print-preview.h"
Enumerations
enum { SIGNAL_IMAGE_MOVED , SIGNAL_LAST }
enum {
PROP_0 , PROP_IMAGE , PROP_IMAGE_X_ALIGN , PROP_IMAGE_Y_ALIGN ,
PROP_IMAGE_SCALE , PROP_PAPER_WIDTH , PROP_PAPER_HEIGHT , PROP_PAGE_LEFT_MARGIN ,
PROP_PAGE_RIGHT_MARGIN , PROP_PAGE_TOP_MARGIN , PROP_PAGE_BOTTOM_MARGIN
}
Functions
GtkWidget * eom_print_preview_new_with_pixbuf (GdkPixbuf *pixbuf)
GtkWidget * eom_print_preview_new (void)
void eom_print_preview_set_page_margins (EomPrintPreview *preview, gfloat l_margin, gfloat r_margin, gfloat t_margin, gfloat b_margin)
void eom_print_preview_set_from_page_setup (EomPrintPreview *preview, GtkPageSetup *setup)
void eom_print_preview_get_image_position (EomPrintPreview *preview, gdouble *x, gdouble *y)
void eom_print_preview_set_image_position (EomPrintPreview *preview, gdouble x, gdouble y)
void eom_print_preview_set_scale (EomPrintPreview *preview, gfloat scale)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SIGNAL_IMAGE_MOVED
SIGNAL_LAST
Definition at line 73 of file eom-print-preview.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_IMAGE
PROP_IMAGE_X_ALIGN
PROP_IMAGE_Y_ALIGN
PROP_IMAGE_SCALE
PROP_PAPER_WIDTH
PROP_PAPER_HEIGHT
PROP_PAGE_LEFT_MARGIN
PROP_PAGE_RIGHT_MARGIN
PROP_PAGE_TOP_MARGIN
PROP_PAGE_BOTTOM_MARGIN
Definition at line 80 of file eom-print-preview.c.
Function Documentation
eom_print_preview_get_image_position()
void eom_print_preview_get_image_position (EomPrintPreview * preview, gdouble * x, gdouble * y)
eom_print_preview_get_image_position: @preview: a EomPrintPreview @x: a pointer to a #gdouble, or NULL to ignore it @y: a pointer to a #gdouble, or NULL to ignore it
Gets current image position in inches, relative to the margins. A (0, 0) position is the intersection between the left and top margins.
Definition at line 1052 of file eom-print-preview.c.
References EOM_IS_PRINT_PREVIEW, NULL, and _EomPrintPreview::priv.
eom_print_preview_new()
GtkWidget * eom_print_preview_new (void)
eom_print_preview_new:
Creates a new EomPrintPreview widget, setting it to the default values, and leaving the page empty. You still need to set the EomPrintPreview:image property to make it useful.
Returns: A new and empty EomPrintPreview widget.
Definition at line 502 of file eom-print-preview.c.
References EOM_TYPE_PRINT_PREVIEW, NULL, _EomPrintPreview::priv, and TRUE.
Referenced by eom_print_preview_new_with_pixbuf().
eom_print_preview_new_with_pixbuf()
GtkWidget * eom_print_preview_new_with_pixbuf (GdkPixbuf * pixbuf)
eom_print_preview_new_with_pixbuf: @pixbuf: a #GdkPixbuf
Creates a new EomPrintPreview widget, and sets the #GdkPixbuf to preview on it.
Returns: A new EomPrintPreview widget.
Definition at line 477 of file eom-print-preview.c.
References EOM_PRINT_PREVIEW, eom_print_preview_new(), NULL, and _EomPrintPreview::priv.
eom_print_preview_set_from_page_setup()
void eom_print_preview_set_from_page_setup (EomPrintPreview * preview, GtkPageSetup * setup)
eom_print_preview_set_from_page_setup: @preview: a EomPrintPreview @setup: a #GtkPageSetup to set the properties from
Sets up the page properties from a #GtkPageSetup. Useful when using the widget with the GtkPrint API.
Definition at line 1025 of file eom-print-preview.c.
References EOM_IS_PRINT_PREVIEW, and NULL.
Referenced by eom_print_image_setup_new(), and eom_print_image_setup_update().
eom_print_preview_set_image_position()
void eom_print_preview_set_image_position (EomPrintPreview * preview, gdouble x, gdouble y)
eom_print_preview_set_image_position: @preview: a EomPrintPreview @x: The X coordinate, in inches, or -1 to ignore it. @y: The Y coordinate, in inches, or -1 to ignore it.
Sets the image position. You can pass -1 to one of the coordinates if you only want to set the other.
Definition at line 1083 of file eom-print-preview.c.
References EOM_IS_PRINT_PREVIEW, NULL, and _EomPrintPreview::priv.
Referenced by eom_print_image_setup_update().
eom_print_preview_set_page_margins()
void eom_print_preview_set_page_margins (EomPrintPreview * preview, gfloat l_margin, gfloat r_margin, gfloat t_margin, gfloat b_margin)
eom_print_preview_set_page_margins: @preview: a EomPrintPreview @l_margin: Left margin. @r_margin: Right margin. @t_margin: Top margin. @b_margin: Bottom margin.
Manually set the margins, in inches.
Definition at line 1000 of file eom-print-preview.c.
References EOM_IS_PRINT_PREVIEW, and NULL.
eom_print_preview_set_scale()
void eom_print_preview_set_scale (EomPrintPreview * preview, gfloat scale)
eom_print_preview_set_scale: @preview: a EomPrintPreview @scale: a scale value, between 0 and 1.
Sets the scale for the image.
Definition at line 1116 of file eom-print-preview.c.
References EOM_IS_PRINT_PREVIEW, and NULL.