MATE Desktop Environment: eom-print-preview.h File Reference
eom-print-preview.h File Reference
Classes
struct _EomPrintPreview
struct _EomPrintPreviewClass
Macros
#define EOM_TYPE_PRINT_PREVIEW (eom_print_preview_get_type ())
#define EOM_PRINT_PREVIEW(obj)
#define EOM_PRINT_PREVIEW_CLASS(klass)
#define EOM_IS_PRINT_PREVIEW(obj)
#define EOM_IS_PRINT_PREVIEW_CLASS(klass)
Typedefs
typedef struct _EomPrintPreview EomPrintPreview
typedef struct _EomPrintPreviewClass EomPrintPreviewClass
typedef struct _EomPrintPreviewPrivate EomPrintPreviewPrivate
Functions
G_GNUC_INTERNAL GType eom_print_preview_get_type (void)
G_GNUC_INTERNAL GtkWidget * eom_print_preview_new (void)
G_GNUC_INTERNAL GtkWidget * eom_print_preview_new_with_pixbuf (GdkPixbuf *pixbuf)
G_GNUC_INTERNAL void eom_print_preview_set_page_margins (EomPrintPreview *preview, gfloat l_margin, gfloat r_margin, gfloat t_margin, gfloat b_margin)
G_GNUC_INTERNAL void eom_print_preview_set_from_page_setup (EomPrintPreview *preview, GtkPageSetup *setup)
G_GNUC_INTERNAL void eom_print_preview_get_image_position (EomPrintPreview *preview, gdouble *x, gdouble *y)
G_GNUC_INTERNAL void eom_print_preview_set_image_position (EomPrintPreview *preview, gdouble x, gdouble y)
G_GNUC_INTERNAL void eom_print_preview_set_scale (EomPrintPreview *preview, gfloat scale)
Macro Definition Documentation
EOM_IS_PRINT_PREVIEW
#define EOM_IS_PRINT_PREVIEW (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), EOM_TYPE_PRINT_PREVIEW))
Definition at line 34 of file eom-print-preview.h.
Referenced by eom_print_preview_get_image_position(), eom_print_preview_set_from_page_setup(), eom_print_preview_set_image_position(), eom_print_preview_set_page_margins(), and eom_print_preview_set_scale().
EOM_IS_PRINT_PREVIEW_CLASS
#define EOM_IS_PRINT_PREVIEW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), EOM_TYPE_PRINT_PREVIEW))
Definition at line 35 of file eom-print-preview.h.
EOM_PRINT_PREVIEW
#define EOM_PRINT_PREVIEW (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), EOM_TYPE_PRINT_PREVIEW, EomPrintPreview))
Definition at line 32 of file eom-print-preview.h.
Referenced by eom_print_image_setup_new(), eom_print_image_setup_update(), and eom_print_preview_new_with_pixbuf().
EOM_PRINT_PREVIEW_CLASS
#define EOM_PRINT_PREVIEW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), EOM_TYPE_PRINT_PREVIEW, EomPrintPreviewClass))
Definition at line 33 of file eom-print-preview.h.
EOM_TYPE_PRINT_PREVIEW
#define EOM_TYPE_PRINT_PREVIEW (eom_print_preview_get_type ())
Definition at line 31 of file eom-print-preview.h.
Referenced by eom_print_preview_new().
Typedef Documentation
EomPrintPreview
typedef struct _EomPrintPreview EomPrintPreview
Definition at line 27 of file eom-print-preview.h.
EomPrintPreviewClass
typedef struct _EomPrintPreviewClass EomPrintPreviewClass
Definition at line 28 of file eom-print-preview.h.
EomPrintPreviewPrivate
typedef struct _EomPrintPreviewPrivate EomPrintPreviewPrivate
Definition at line 29 of file eom-print-preview.h.
Function Documentation
eom_print_preview_get_image_position()
G_GNUC_INTERNAL void eom_print_preview_get_image_position (EomPrintPreview * preview, gdouble * x, gdouble * y)
eom_print_preview_get_image_position: @preview: a EomPrintPreview @x: a pointer to a #gdouble, or NULL to ignore it @y: a pointer to a #gdouble, or NULL to ignore it
Gets current image position in inches, relative to the margins. A (0, 0) position is the intersection between the left and top margins.
Definition at line 1052 of file eom-print-preview.c.
References EOM_IS_PRINT_PREVIEW, NULL, and _EomPrintPreview::priv.
eom_print_preview_get_type()
G_GNUC_INTERNAL GType eom_print_preview_get_type (void)
eom_print_preview_new()
G_GNUC_INTERNAL GtkWidget * eom_print_preview_new (void)
eom_print_preview_new:
Creates a new EomPrintPreview widget, setting it to the default values, and leaving the page empty. You still need to set the EomPrintPreview:image property to make it useful.
Returns: A new and empty EomPrintPreview widget.
Definition at line 502 of file eom-print-preview.c.
References EOM_TYPE_PRINT_PREVIEW, NULL, _EomPrintPreview::priv, and TRUE.
Referenced by eom_print_preview_new_with_pixbuf().
eom_print_preview_new_with_pixbuf()
G_GNUC_INTERNAL GtkWidget * eom_print_preview_new_with_pixbuf (GdkPixbuf * pixbuf)
eom_print_preview_new_with_pixbuf: @pixbuf: a #GdkPixbuf
Creates a new EomPrintPreview widget, and sets the #GdkPixbuf to preview on it.
Returns: A new EomPrintPreview widget.
Definition at line 477 of file eom-print-preview.c.
References EOM_PRINT_PREVIEW, eom_print_preview_new(), NULL, and _EomPrintPreview::priv.
eom_print_preview_set_from_page_setup()
G_GNUC_INTERNAL void eom_print_preview_set_from_page_setup (EomPrintPreview * preview, GtkPageSetup * setup)
eom_print_preview_set_from_page_setup: @preview: a EomPrintPreview @setup: a #GtkPageSetup to set the properties from
Sets up the page properties from a #GtkPageSetup. Useful when using the widget with the GtkPrint API.
Definition at line 1025 of file eom-print-preview.c.
References EOM_IS_PRINT_PREVIEW, and NULL.
Referenced by eom_print_image_setup_new(), and eom_print_image_setup_update().
eom_print_preview_set_image_position()
G_GNUC_INTERNAL void eom_print_preview_set_image_position (EomPrintPreview * preview, gdouble x, gdouble y)
eom_print_preview_set_image_position: @preview: a EomPrintPreview @x: The X coordinate, in inches, or -1 to ignore it. @y: The Y coordinate, in inches, or -1 to ignore it.
Sets the image position. You can pass -1 to one of the coordinates if you only want to set the other.
Definition at line 1083 of file eom-print-preview.c.
References EOM_IS_PRINT_PREVIEW, NULL, and _EomPrintPreview::priv.
Referenced by eom_print_image_setup_update().
eom_print_preview_set_page_margins()
G_GNUC_INTERNAL void eom_print_preview_set_page_margins (EomPrintPreview * preview, gfloat l_margin, gfloat r_margin, gfloat t_margin, gfloat b_margin)
eom_print_preview_set_page_margins: @preview: a EomPrintPreview @l_margin: Left margin. @r_margin: Right margin. @t_margin: Top margin. @b_margin: Bottom margin.
Manually set the margins, in inches.
Definition at line 1000 of file eom-print-preview.c.
References EOM_IS_PRINT_PREVIEW, and NULL.
eom_print_preview_set_scale()
G_GNUC_INTERNAL void eom_print_preview_set_scale (EomPrintPreview * preview, gfloat scale)
eom_print_preview_set_scale: @preview: a EomPrintPreview @scale: a scale value, between 0 and 1.
Sets the scale for the image.
Definition at line 1116 of file eom-print-preview.c.
References EOM_IS_PRINT_PREVIEW, and NULL.