MATE Desktop Environment: eom-util.h File Reference
eom-util.h File Reference
#include <gtk/gtk.h>
Functions
G_GNUC_INTERNAL void eom_util_show_help (const gchar *section, GtkWindow *parent)
G_GNUC_INTERNAL gchar * eom_util_make_valid_utf8 (const gchar *name)
G_GNUC_INTERNAL GSList * eom_util_parse_uri_string_list_to_file_list (const gchar *uri_list)
G_GNUC_INTERNAL GSList * eom_util_string_list_to_file_list (GSList *string_list)
G_GNUC_INTERNAL GSList * eom_util_strings_to_file_list (gchar **strings)
G_GNUC_INTERNAL GSList * eom_util_string_array_to_list (const gchar **files, gboolean create_uri)
G_GNUC_INTERNAL gchar ** eom_util_string_array_make_absolute (gchar **files)
G_GNUC_INTERNAL const gchar * eom_util_dot_dir (void)
G_GNUC_INTERNAL char * eom_util_filename_get_extension (const char *filename_with_extension)
G_GNUC_INTERNAL gboolean eom_util_file_is_persistent (GFile *file)
G_GNUC_INTERNAL void eom_util_show_file_in_filemanager (GFile *file, GtkWindow *toplevel)
gboolean eom_notebook_scroll_event_cb (GtkWidget *notebook, GdkEventScroll *event)
G_GNUC_INTERNAL const char * eom_util_get_content_type_with_fallback (GFileInfo *file_info)
Function Documentation
eom_notebook_scroll_event_cb()
gboolean eom_notebook_scroll_event_cb (GtkWidget * notebook, GdkEventScroll * event)
Definition at line 428 of file eom-util.c.
References FALSE, NULL, and TRUE.
eom_util_dot_dir()
G_GNUC_INTERNAL const gchar * eom_util_dot_dir (void)
Definition at line 247 of file eom-util.c.
References ensure_dir_exists(), FALSE, NULL, and TRUE.
Referenced by eom_plugin_engine_new().
eom_util_file_is_persistent()
G_GNUC_INTERNAL gboolean eom_util_file_is_persistent (GFile * file)
Definition at line 324 of file eom-util.c.
References FALSE, NULL, and TRUE.
eom_util_filename_get_extension()
G_GNUC_INTERNAL char * eom_util_filename_get_extension (const char * filename)
eom_util_filename_get_extension: @filename: a filename
Returns a reasonably good guess of the file extension of @filename.
Returns: a newly allocated string with the file extension of @filename.
Definition at line 282 of file eom-util.c.
References NULL, and strrchr.
eom_util_get_content_type_with_fallback()
G_GNUC_INTERNAL const char * eom_util_get_content_type_with_fallback (GFileInfo * file_info)
Definition at line 487 of file eom-util.c.
References NULL.
Referenced by eom_list_store_add_files().
eom_util_make_valid_utf8()
G_GNUC_INTERNAL gchar * eom_util_make_valid_utf8 (const gchar * name)
Definition at line 80 of file eom-util.c.
References _, FALSE, and NULL.
Referenced by eom_exif_util_set_label_text(), eom_image_get_caption(), and eom_image_load_error_message_area_new().
eom_util_parse_uri_string_list_to_file_list()
G_GNUC_INTERNAL GSList * eom_util_parse_uri_string_list_to_file_list (const gchar * uri_list)
Definition at line 121 of file eom-util.c.
References file_list, and NULL.
eom_util_show_file_in_filemanager()
G_GNUC_INTERNAL void eom_util_show_file_in_filemanager (GFile * file, GtkWindow * toplevel)
Definition at line 371 of file eom-util.c.
References FALSE, NULL, proxy, and TRUE.
eom_util_show_help()
G_GNUC_INTERNAL void eom_util_show_help (const gchar * section, GtkWindow * parent)
Definition at line 45 of file eom-util.c.
References _, error, and NULL.
eom_util_string_array_make_absolute()
G_GNUC_INTERNAL gchar ** eom_util_string_array_make_absolute (gchar ** files)
Definition at line 203 of file eom-util.c.
References NULL.
eom_util_string_array_to_list()
G_GNUC_INTERNAL GSList * eom_util_string_array_to_list (const gchar ** files, gboolean create_uri)
Definition at line 172 of file eom-util.c.
References NULL.
eom_util_string_list_to_file_list()
G_GNUC_INTERNAL GSList * eom_util_string_list_to_file_list (GSList * string_list)
Definition at line 140 of file eom-util.c.
References file_list, and NULL.
Referenced by eom_application_open_uri_list().
eom_util_strings_to_file_list()
G_GNUC_INTERNAL GSList * eom_util_strings_to_file_list (gchar ** strings)
Definition at line 158 of file eom-util.c.
References file_list, and NULL.
Referenced by eom_application_open_uris().