MATE Desktop Environment: eom-application.h File Reference
eom-application.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libpeas/peas-extension-set.h>
#include <gtk/gtk.h>
#include "eom-window.h"
Classes
struct _EomApplication
struct _EomApplicationClass
Macros
#define EOM_TYPE_APPLICATION (eom_application_get_type ())
#define EOM_APPLICATION(obj)
#define EOM_APPLICATION_CLASS(klass)
#define EOM_IS_APPLICATION(obj)
#define EOM_IS_APPLICATION_CLASS(klass)
#define EOM_APPLICATION_GET_CLASS(obj)
#define EOM_APP (eom_application_get_instance ())
Typedefs
typedef struct _EomApplication EomApplication
typedef struct _EomApplicationClass EomApplicationClass
typedef struct _EomApplicationPrivate EomApplicationPrivate
Functions
GType eom_application_get_type (void)
EomApplication * eom_application_get_instance (void)
gboolean eom_application_open_window (EomApplication *application, guint timestamp, EomStartupFlags flags, GError **error)
gboolean eom_application_open_uri_list (EomApplication *application, GSList *uri_list, guint timestamp, EomStartupFlags flags, GError **error)
gboolean eom_application_open_file_list (EomApplication *application, GSList *file_list, guint timestamp, EomStartupFlags flags, GError **error)
gboolean eom_application_open_uris (EomApplication *application, gchar **uris, guint timestamp, EomStartupFlags flags, GError **error)
Macro Definition Documentation
EOM_APP
#define EOM_APP (eom_application_get_instance ())
Definition at line 48 of file eom-application.h.
Referenced by eom_window_new(), and main().
EOM_APPLICATION
#define EOM_APPLICATION (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST((obj), EOM_TYPE_APPLICATION, EomApplication))
Definition at line 42 of file eom-application.h.
Referenced by eom_application_get_instance(), and G_DEFINE_TYPE_WITH_PRIVATE().
EOM_APPLICATION_CLASS
#define EOM_APPLICATION_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST((klass),  EOM_TYPE_APPLICATION, EomApplicationClass))
Definition at line 43 of file eom-application.h.
EOM_APPLICATION_GET_CLASS
#define EOM_APPLICATION_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS((obj),  EOM_TYPE_APPLICATION, EomApplicationClass))
Definition at line 46 of file eom-application.h.
EOM_IS_APPLICATION
#define EOM_IS_APPLICATION (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE((obj), EOM_TYPE_APPLICATION))
Definition at line 44 of file eom-application.h.
Referenced by eom_application_get_toolbars_model(), eom_application_open_uri_list(), eom_application_open_window(), eom_application_reset_toolbars_model(), and eom_session_init().
EOM_IS_APPLICATION_CLASS
#define EOM_IS_APPLICATION_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass),  EOM_TYPE_APPLICATION))
Definition at line 45 of file eom-application.h.
EOM_TYPE_APPLICATION
#define EOM_TYPE_APPLICATION (eom_application_get_type ())
Definition at line 41 of file eom-application.h.
Referenced by eom_application_activatable_default_init(), and eom_application_get_instance().
Typedef Documentation
EomApplication
typedef struct _EomApplication EomApplication
Definition at line 37 of file eom-application.h.
EomApplicationClass
typedef struct _EomApplicationClass EomApplicationClass
Definition at line 38 of file eom-application.h.
EomApplicationPrivate
typedef struct _EomApplicationPrivate EomApplicationPrivate
Definition at line 39 of file eom-application.h.
Function Documentation
eom_application_get_instance()
EomApplication * eom_application_get_instance (void)
eom_application_get_instance:
Returns a singleton instance of EomApplication currently running. If not running yet, it will create one.
Returns: (transfer none): a running EomApplication.
Definition at line 225 of file eom-application.c.
References APPLICATION_SERVICE_NAME, EOM_APPLICATION, EOM_TYPE_APPLICATION, and NULL.
eom_application_get_type()
GType eom_application_get_type (void)
eom_application_open_file_list()
gboolean eom_application_open_file_list (EomApplication * application, GSList * file_list, guint timestamp, EomStartupFlags flags, GError ** error)
eom_application_open_file_list: @application: An EomApplication. @file_list: (element-type GFile): A list of #GFiles @timestamp: The timestamp of the user interaction which triggered this call (see gtk_window_present_with_time()). @flags: A set of EomStartupFlags influencing a new windows' state. @error: Return location for a #GError, or NULL to ignore errors.
Opens a list of files in a EomWindow. If an EomWindow displaying the first image in the list is already open, this will be used. Otherwise, an empty EomWindow is used, either already existing or newly created.
Returns: Currently always TRUE.
Definition at line 358 of file eom-application.c.
References EOM_WINDOW, eom_window_new(), eom_window_open_file_list(), error, file_list, NULL, and TRUE.
Referenced by eom_application_open_uri_list(), and eom_application_open_uris().
eom_application_open_uri_list()
gboolean eom_application_open_uri_list (EomApplication * application, GSList * uri_list, guint timestamp, EomStartupFlags flags, GError ** error)
eom_application_open_uri_list: @application: An EomApplication. @uri_list: (element-type utf8): A list of URIs. @timestamp: The timestamp of the user interaction which triggered this call (see gtk_window_present_with_time()). @flags: A set of EomStartupFlags influencing a new windows' state. @error: Return location for a #GError, or NULL to ignore errors.
Opens a list of images, from a list of URIs. See eom_application_open_file_list() for details.
Returns: Currently always TRUE.
Definition at line 407 of file eom-application.c.
References eom_application_open_file_list(), EOM_IS_APPLICATION, eom_util_string_list_to_file_list(), error, FALSE, file_list, and NULL.
eom_application_open_uris()
gboolean eom_application_open_uris (EomApplication * application, gchar ** uris, guint timestamp, EomStartupFlags flags, GError ** error)
eom_application_open_uris: @application: an EomApplication @uris: A #GList of URI strings. @timestamp: The timestamp of the user interaction which triggered this call (see gtk_window_present_with_time()). @flags: A set of EomStartupFlags influencing a new windows' state. @error: Return location for a #GError, or NULL to ignore errors.
Opens a list of images, from a list of URI strings. See eom_application_open_file_list() for details.
Returns: Currently always TRUE.
Definition at line 441 of file eom-application.c.
References eom_application_open_file_list(), eom_util_strings_to_file_list(), error, file_list, and NULL.
eom_application_open_window()
gboolean eom_application_open_window (EomApplication * application, guint timestamp, EomStartupFlags flags, GError ** error)
References error, and file_list.