MATE Desktop Environment: eom-list-store.h File Reference
eom-list-store.h File Reference
#include <gtk/gtk.h>
#include <glib-object.h>
#include <gio/gio.h>
Classes
struct _EomListStore
struct _EomListStoreClass
Macros
#define __EOM_IMAGE_DECLR__
#define EOM_TYPE_LIST_STORE eom_list_store_get_type()
#define EOM_LIST_STORE(obj)
#define EOM_LIST_STORE_CLASS(klass)
#define EOM_IS_LIST_STORE(obj)
#define EOM_IS_LIST_STORE_CLASS(klass)
#define EOM_LIST_STORE_GET_CLASS(obj)
#define EOM_LIST_STORE_THUMB_SIZE 90
Typedefs
typedef struct _EomListStore EomListStore
typedef struct _EomListStoreClass EomListStoreClass
typedef struct _EomListStorePrivate EomListStorePrivate
Enumerations
enum EomListStoreColumn {
EOM_LIST_STORE_THUMBNAIL = 0 , EOM_LIST_STORE_THUMB_SET , EOM_LIST_STORE_EOM_IMAGE , EOM_LIST_STORE_EOM_JOB ,
EOM_LIST_STORE_NUM_COLUMNS
}
Functions
GType eom_list_store_get_type (void)
GtkListStore * eom_list_store_new (void)
GtkListStore * eom_list_store_new_from_glist (GList *list)
void eom_list_store_append_image (EomListStore *store, EomImage *image)
void eom_list_store_add_files (EomListStore *store, GList *file_list, gboolean preserve_order)
void eom_list_store_remove_image (EomListStore *store, EomImage *image)
gint eom_list_store_get_pos_by_image (EomListStore *store, EomImage *image)
EomImage * eom_list_store_get_image_by_pos (EomListStore *store, gint pos)
gint eom_list_store_get_pos_by_iter (EomListStore *store, GtkTreeIter *iter)
gint eom_list_store_length (EomListStore *store)
gint eom_list_store_get_initial_pos (EomListStore *store)
void eom_list_store_thumbnail_set (EomListStore *store, GtkTreeIter *iter)
void eom_list_store_thumbnail_unset (EomListStore *store, GtkTreeIter *iter)
void eom_list_store_thumbnail_refresh (EomListStore *store, GtkTreeIter *iter)
Macro Definition Documentation
__EOM_IMAGE_DECLR__
#define __EOM_IMAGE_DECLR__
Definition at line 34 of file eom-list-store.h.
EOM_IS_LIST_STORE
#define EOM_IS_LIST_STORE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), EOM_TYPE_LIST_STORE))
Definition at line 45 of file eom-list-store.h.
Referenced by eom_list_store_get_image_by_pos(), eom_list_store_get_initial_pos(), eom_list_store_get_pos_by_image(), eom_list_store_length(), eom_list_store_remove_image(), and eom_thumb_view_set_model().
EOM_IS_LIST_STORE_CLASS
#define EOM_IS_LIST_STORE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass),  EOM_TYPE_LIST_STORE))
Definition at line 46 of file eom-list-store.h.
EOM_LIST_STORE
#define EOM_LIST_STORE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), EOM_TYPE_LIST_STORE, EomListStore))
Definition at line 43 of file eom-list-store.h.
Referenced by eom_list_store_new_from_glist(), eom_thumb_view_select_single(), eom_thumb_view_set_current_image(), eom_window_get_store(), and eom_window_is_empty().
EOM_LIST_STORE_CLASS
#define EOM_LIST_STORE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass),  EOM_TYPE_LIST_STORE, EomListStoreClass))
Definition at line 44 of file eom-list-store.h.
EOM_LIST_STORE_GET_CLASS
#define EOM_LIST_STORE_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj),  EOM_TYPE_LIST_STORE, EomListStoreClass))
Definition at line 47 of file eom-list-store.h.
EOM_LIST_STORE_THUMB_SIZE
#define EOM_LIST_STORE_THUMB_SIZE 90
Definition at line 49 of file eom-list-store.h.
EOM_TYPE_LIST_STORE
#define EOM_TYPE_LIST_STORE eom_list_store_get_type()
Definition at line 42 of file eom-list-store.h.
Referenced by eom_list_store_new().
Typedef Documentation
EomListStore
typedef struct _EomListStore EomListStore
Definition at line 38 of file eom-list-store.h.
EomListStoreClass
typedef struct _EomListStoreClass EomListStoreClass
Definition at line 39 of file eom-list-store.h.
EomListStorePrivate
typedef struct _EomListStorePrivate EomListStorePrivate
Definition at line 40 of file eom-list-store.h.
Enumeration Type Documentation
EomListStoreColumn
enum EomListStoreColumn
Enumerator
EOM_LIST_STORE_THUMBNAIL
EOM_LIST_STORE_THUMB_SET
EOM_LIST_STORE_EOM_IMAGE
EOM_LIST_STORE_EOM_JOB
EOM_LIST_STORE_NUM_COLUMNS
Definition at line 51 of file eom-list-store.h.
Function Documentation
eom_list_store_add_files()
void eom_list_store_add_files (EomListStore * store, GList * file_list, gboolean preserve_order)
eom_list_store_add_files: @store: An EomListStore. @file_list: (element-type GFile): A NULL-terminated list of #GFile's. @preserve_order: Flag to indicate whether to honor the order of input parameters.
Adds a list of #GFile's to @store. The given list must be NULL-terminated.
If any of the #GFile's in @file_list is a directory, all the images in that directory will be added to @store. If the list of files contains only one file and this is a regular file, then all the images in the same directory will be added as well to @store.
Definition at line 550 of file eom-list-store.c.
References eom_image_is_supported_mime_type(), eom_list_store_get_pos_by_iter(), eom_util_get_content_type_with_fallback(), file_list, NULL, and _EomListStore::priv.
eom_list_store_append_image()
void eom_list_store_append_image (EomListStore * store, EomImage * image)
eom_list_store_append_image: @store: An EomListStore. An EomImage.
Adds an EomImage to @store. The thumbnail of the image is not loaded and will only be loaded if the thumbnail is made visible or eom_list_store_set_thumbnail() is called.
Definition at line 336 of file eom-list-store.c.
References EOM_LIST_STORE_EOM_IMAGE, EOM_LIST_STORE_THUMB_SET, EOM_LIST_STORE_THUMBNAIL, FALSE, and _EomListStore::priv.
Referenced by eom_list_store_new_from_glist().
eom_list_store_get_image_by_pos()
EomImage * eom_list_store_get_image_by_pos (EomListStore * store, gint pos)
eom_list_store_get_image_by_pos: @store: An EomListStore. @pos: the position of the required EomImage.
Gets the EomImage in the position @pos of @store. If there is no image at position @pos, NULL is returned.
Returns: (transfer full): the EomImage in position @pos or NULL.
Definition at line 742 of file eom-list-store.c.
References EOM_IS_LIST_STORE, EOM_LIST_STORE_EOM_IMAGE, and NULL.
eom_list_store_get_initial_pos()
gint eom_list_store_get_initial_pos (EomListStore * store)
eom_list_store_get_initial_pos: @store: An EomListStore.
Gets the position of the EomImage that should be loaded first. If not set, it returns -1.
Returns: the position of the image to be loaded first or -1.
Definition at line 810 of file eom-list-store.c.
References EOM_IS_LIST_STORE, and _EomListStore::priv.
Referenced by eom_thumb_view_set_model().
eom_list_store_get_pos_by_image()
gint eom_list_store_get_pos_by_image (EomListStore * store, EomImage * image)
eom_list_store_get_pos_by_image: @store: An EomListStore. An EomImage.
Gets the position wherestored in @store. Ifnot stored in @store, -1 is returned.
Returns: the position of@store or -1 if not found.
Definition at line 711 of file eom-list-store.c.
References eom_image_get_file(), EOM_IS_IMAGE, EOM_IS_LIST_STORE, and eom_list_store_get_pos_by_iter().
Referenced by eom_thumb_view_set_current_image().
eom_list_store_get_pos_by_iter()
gint eom_list_store_get_pos_by_iter (EomListStore * store, GtkTreeIter * iter)
eom_list_store_get_pos_by_iter: @store: An EomListStore. @iter: A #GtkTreeIter pointing to an image in @store.
Gets the position of the image pointed by @iter.
Returns: The position of the image pointed by @iter.
Definition at line 768 of file eom-list-store.c.
Referenced by eom_list_store_add_files(), and eom_list_store_get_pos_by_image().
eom_list_store_get_type()
GType eom_list_store_get_type (void)
References file_list.
eom_list_store_length()
gint eom_list_store_length (EomListStore * store)
eom_list_store_length: @store: An EomListStore.
Returns the number of images in the store.
Returns: The number of images in @store.
Definition at line 792 of file eom-list-store.c.
References EOM_IS_LIST_STORE, and NULL.
Referenced by eom_thumb_view_select_single(), eom_thumb_view_set_model(), and eom_window_is_empty().
eom_list_store_new()
GtkListStore * eom_list_store_new (void)
eom_list_store_new:
Creates a new and empty EomListStore.
Returns: a newly created EomListStore.
Definition at line 179 of file eom-list-store.c.
References EOM_TYPE_LIST_STORE, and NULL.
Referenced by eom_list_store_new_from_glist().
eom_list_store_new_from_glist()
GtkListStore * eom_list_store_new_from_glist (GList * list)
eom_list_store_new_from_glist: @list: (element-type EomImage): a NULL-terminated list of EomImage's.
Creates a new EomListStore from a list of EomImage's. The given list must be NULL-terminated.
Returns: a new EomListStore.
Definition at line 686 of file eom-list-store.c.
References EOM_IMAGE, EOM_LIST_STORE, eom_list_store_append_image(), eom_list_store_new(), and NULL.
eom_list_store_remove_image()
void eom_list_store_remove_image (EomListStore * store, EomImage * image)
eom_list_store_remove_image: @store: An EomListStore. An EomImage.
Removes@store.
Definition at line 660 of file eom-list-store.c.
References eom_image_get_file(), EOM_IS_IMAGE, and EOM_IS_LIST_STORE.
eom_list_store_thumbnail_refresh()
void eom_list_store_thumbnail_refresh (EomListStore * store, GtkTreeIter * iter)
eom_list_store_thumbnail_refresh: @store: An EomListStore. @iter: A #GtkTreeIter pointing to an image in @store.
Refreshes the thumbnail for the image pointed by @iter.
Definition at line 934 of file eom-list-store.c.
eom_list_store_thumbnail_set()
void eom_list_store_thumbnail_set (EomListStore * store, GtkTreeIter * iter)
eom_list_store_thumbnail_set: @store: An EomListStore. @iter: A #GtkTreeIter pointing to an image in @store.
Sets the thumbnail for the image pointed by @iter.
Definition at line 880 of file eom-list-store.c.
References EOM_LIST_STORE_THUMB_SET, and FALSE.
eom_list_store_thumbnail_unset()
void eom_list_store_thumbnail_unset (EomListStore * store, GtkTreeIter * iter)
eom_list_store_thumbnail_unset: @store: An EomListStore. @iter: A #GtkTreeIter pointing to an image in @store.
Unsets the thumbnail for the image pointed by @iter, changing it to a "busy" icon.
Definition at line 906 of file eom-list-store.c.
References eom_image_set_thumbnail(), EOM_LIST_STORE_EOM_IMAGE, EOM_LIST_STORE_THUMB_SET, EOM_LIST_STORE_THUMBNAIL, FALSE, NULL, and _EomListStore::priv.