MATE Desktop Environment: eom-debug.c File Reference
eom-debug.c File Reference
#include <stdio.h>
#include "eom-debug.h"
Macros
#define ENABLE_PROFILING
Functions
void eom_debug_init (void)
void eom_debug_message (EomDebug section, const gchar *file, gint line, const gchar *function, const gchar *format,...)
void eom_debug (EomDebug section, const gchar *file, gint line, const gchar *function)
Macro Definition Documentation
ENABLE_PROFILING
#define ENABLE_PROFILING
Definition at line 36 of file eom-debug.c.
Function Documentation
eom_debug()
void eom_debug (EomDebug section, const gchar * file, gint line, const gchar * function)
Definition at line 138 of file eom-debug.c.
References debug, and NULL.
Referenced by eom_image_load(), eom_print_operation_new(), eom_window_is_empty(), eom_window_new(), and eom_window_open_file_list().
eom_debug_init()
void eom_debug_init (void)
Definition at line 46 of file eom-debug.c.
References debug, EOM_DEBUG_IMAGE_DATA, EOM_DEBUG_IMAGE_LOAD, EOM_DEBUG_IMAGE_SAVE, EOM_DEBUG_JOBS, EOM_DEBUG_LCMS, EOM_DEBUG_LIST_STORE, EOM_DEBUG_NO_DEBUG, EOM_DEBUG_PLUGINS, EOM_DEBUG_PREFERENCES, EOM_DEBUG_PRINTING, EOM_DEBUG_THUMBNAIL, EOM_DEBUG_VIEW, EOM_DEBUG_WINDOW, and NULL.
Referenced by main().
eom_debug_message()
void eom_debug_message (EomDebug section, const gchar * file, gint line, const gchar * function, const gchar * format, ...)
Definition at line 101 of file eom-debug.c.
References debug, and NULL.
Referenced by eom_thumbnail_load().