MATE Desktop Environment: eom-image.h File Reference
eom-image.h File Reference
#include "eom-jobs.h"
#include "eom-window.h"
#include "eom-transform.h"
#include "eom-image-save-info.h"
#include "eom-enums.h"
#include <glib.h>
#include <glib-object.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
Classes
struct _EomImage
struct _EomImageClass
Macros
#define EOM_TYPE_IMAGE (eom_image_get_type ())
#define EOM_IMAGE(obj)
#define EOM_IMAGE_CLASS(klass)
#define EOM_IS_IMAGE(obj)
#define EOM_IS_IMAGE_CLASS(klass)
#define EOM_IMAGE_GET_CLASS(obj)
#define EOM_IMAGE_ERROR eom_image_error_quark ()
Typedefs
typedef struct _EomImageClass EomImageClass
typedef struct _EomImagePrivate EomImagePrivate
Enumerations
enum EomImageError {
EOM_IMAGE_ERROR_SAVE_NOT_LOCAL , EOM_IMAGE_ERROR_NOT_LOADED , EOM_IMAGE_ERROR_VFS , EOM_IMAGE_ERROR_FILE_EXISTS ,
EOM_IMAGE_ERROR_TMP_FILE_FAILED , EOM_IMAGE_ERROR_GENERIC , EOM_IMAGE_ERROR_UNKNOWN
}
enum EomImageStatus {
EOM_IMAGE_STATUS_UNKNOWN , EOM_IMAGE_STATUS_LOADING , EOM_IMAGE_STATUS_LOADED , EOM_IMAGE_STATUS_SAVING ,
EOM_IMAGE_STATUS_FAILED
}
enum EomImageMetadataStatus { EOM_IMAGE_METADATA_NOT_READ , EOM_IMAGE_METADATA_NOT_AVAILABLE , EOM_IMAGE_METADATA_READY }
Functions
GType eom_image_get_type (void)
GQuark eom_image_error_quark (void)
EomImage * eom_image_new_file (GFile *file, const gchar *caption)
gboolean eom_image_load (EomImage *img, EomImageData data2read, EomJob *job, GError **error)
void eom_image_cancel_load (EomImage *img)
gboolean eom_image_has_data (EomImage *img, EomImageData data)
void eom_image_data_ref (EomImage *img)
void eom_image_data_unref (EomImage *img)
void eom_image_set_thumbnail (EomImage *img, GdkPixbuf *pixbuf)
gboolean eom_image_save_as_by_info (EomImage *img, EomImageSaveInfo *source, EomImageSaveInfo *target, GError **error)
gboolean eom_image_save_by_info (EomImage *img, EomImageSaveInfo *source, GError **error)
GdkPixbuf * eom_image_get_pixbuf (EomImage *img)
GdkPixbuf * eom_image_get_thumbnail (EomImage *img)
void eom_image_get_size (EomImage *img, gint *width, gint *height)
goffset eom_image_get_bytes (EomImage *img)
gboolean eom_image_is_modified (EomImage *img)
void eom_image_modified (EomImage *img)
const gchar * eom_image_get_caption (EomImage *img)
const gchar * eom_image_get_collate_key (EomImage *img)
gpointer eom_image_get_xmp_info (EomImage *img)
GFile * eom_image_get_file (EomImage *img)
gchar * eom_image_get_uri_for_display (EomImage *img)
EomImageStatus eom_image_get_status (EomImage *img)
EomImageMetadataStatus eom_image_get_metadata_status (EomImage *img)
void eom_image_transform (EomImage *img, EomTransform *trans, EomJob *job)
void eom_image_autorotate (EomImage *img)
void eom_image_undo (EomImage *img)
GList * eom_image_get_supported_mime_types (void)
gboolean eom_image_is_supported_mime_type (const char *mime_type)
gboolean eom_image_is_animation (EomImage *img)
gboolean eom_image_start_animation (EomImage *img)
EomTransform * eom_image_get_transform (EomImage *img)
EomTransform * eom_image_get_autorotate_transform (EomImage *img)
gboolean eom_image_is_jpeg (EomImage *img)
void eom_image_file_changed (EomImage *img)
gboolean eom_image_is_file_changed (EomImage *img)
Macro Definition Documentation
EOM_IMAGE
#define EOM_IMAGE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST((obj), EOM_TYPE_IMAGE, EomImage))
Definition at line 62 of file eom-image.h.
Referenced by eom_image_load(), eom_image_new_file(), eom_list_store_new_from_glist(), eom_save_as_dialog_new(), and eom_uri_converter_check().
EOM_IMAGE_CLASS
#define EOM_IMAGE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST((klass),  EOM_TYPE_IMAGE, EomImageClass))
Definition at line 63 of file eom-image.h.
EOM_IMAGE_ERROR
#define EOM_IMAGE_ERROR eom_image_error_quark ()
Definition at line 78 of file eom-image.h.
Referenced by eom_image_save_as_by_info(), and eom_image_save_by_info().
EOM_IMAGE_GET_CLASS
#define EOM_IMAGE_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS((obj),  EOM_TYPE_IMAGE, EomImageClass))
Definition at line 66 of file eom-image.h.
EOM_IS_IMAGE
#define EOM_IS_IMAGE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE((obj), EOM_TYPE_IMAGE))
Definition at line 64 of file eom-image.h.
Referenced by eom_image_autorotate(), eom_image_cancel_load(), eom_image_data_ref(), eom_image_data_unref(), eom_image_file_changed(), eom_image_get_autorotate_transform(), eom_image_get_bytes(), eom_image_get_caption(), eom_image_get_collate_key(), eom_image_get_file(), eom_image_get_metadata_status(), eom_image_get_pixbuf(), eom_image_get_size(), eom_image_get_status(), eom_image_get_thumbnail(), eom_image_get_transform(), eom_image_get_uri_for_display(), eom_image_get_xmp_info(), eom_image_has_data(), eom_image_is_animation(), eom_image_is_file_changed(), eom_image_is_jpeg(), eom_image_is_modified(), eom_image_load(), eom_image_modified(), eom_image_save_as_by_info(), eom_image_save_by_info(), eom_image_save_info_new_from_image(), eom_image_set_thumbnail(), eom_image_start_animation(), eom_image_undo(), eom_list_store_get_pos_by_image(), eom_list_store_remove_image(), and eom_uri_converter_preview().
EOM_IS_IMAGE_CLASS
#define EOM_IS_IMAGE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass),  EOM_TYPE_IMAGE))
Definition at line 65 of file eom-image.h.
EOM_TYPE_IMAGE
#define EOM_TYPE_IMAGE (eom_image_get_type ())
Definition at line 61 of file eom-image.h.
Referenced by eom_image_new_file().
Typedef Documentation
EomImageClass
typedef struct _EomImageClass EomImageClass
Definition at line 58 of file eom-image.h.
EomImagePrivate
typedef struct _EomImagePrivate EomImagePrivate
Definition at line 59 of file eom-image.h.
Enumeration Type Documentation
EomImageError
enum EomImageError
Enumerator
EOM_IMAGE_ERROR_SAVE_NOT_LOCAL
EOM_IMAGE_ERROR_NOT_LOADED
EOM_IMAGE_ERROR_VFS
EOM_IMAGE_ERROR_FILE_EXISTS
EOM_IMAGE_ERROR_TMP_FILE_FAILED
EOM_IMAGE_ERROR_GENERIC
EOM_IMAGE_ERROR_UNKNOWN
Definition at line 68 of file eom-image.h.
EomImageMetadataStatus
enum EomImageMetadataStatus
Enumerator
EOM_IMAGE_METADATA_NOT_READ
EOM_IMAGE_METADATA_NOT_AVAILABLE
EOM_IMAGE_METADATA_READY
Definition at line 88 of file eom-image.h.
EomImageStatus
enum EomImageStatus
Enumerator
EOM_IMAGE_STATUS_UNKNOWN
EOM_IMAGE_STATUS_LOADING
EOM_IMAGE_STATUS_LOADED
EOM_IMAGE_STATUS_SAVING
EOM_IMAGE_STATUS_FAILED
Definition at line 80 of file eom-image.h.
Function Documentation
eom_image_autorotate()
void eom_image_autorotate (EomImage * img)
Definition at line 794 of file eom-image.c.
References _EomImagePrivate::autorotate, EOM_IS_IMAGE, _EomImage::priv, and TRUE.
eom_image_cancel_load()
void eom_image_cancel_load (EomImage * img)
Definition at line 2005 of file eom-image.c.
References _EomImagePrivate::cancel_loading, EOM_IMAGE_STATUS_LOADING, EOM_IS_IMAGE, _EomImage::priv, _EomImagePrivate::status, _EomImagePrivate::status_mutex, and TRUE.
eom_image_data_ref()
void eom_image_data_ref (EomImage * img)
Definition at line 2161 of file eom-image.c.
References _EomImagePrivate::data_ref_count, EOM_IS_IMAGE, and _EomImage::priv.
Referenced by eom_scroll_view_set_image().
eom_image_data_unref()
void eom_image_data_unref (EomImage * img)
Definition at line 2172 of file eom-image.c.
References _EomImagePrivate::data_ref_count, EOM_IS_IMAGE, and _EomImage::priv.
eom_image_error_quark()
GQuark eom_image_error_quark (void)
Definition at line 328 of file eom-image.c.
eom_image_file_changed()
void eom_image_file_changed (EomImage * img)
eom_image_file_changed: @img: a EomImage
Marks the image files contents as changed. Also, emits EomImage::file-changed signal
Definition at line 2416 of file eom-image.c.
References EOM_IS_IMAGE, _EomImagePrivate::file_is_changed, _EomImage::priv, SIGNAL_FILE_CHANGED, and TRUE.
eom_image_get_autorotate_transform()
EomTransform * eom_image_get_autorotate_transform (EomImage * img)
eom_image_get_autorotate_transform: @img: a EomImage
Get @img autorotate transform.
Returns: (transfer none): A EomTransform.
Definition at line 2401 of file eom-image.c.
References EOM_IS_IMAGE, NULL, _EomImage::priv, and _EomImagePrivate::trans_autorotate.
eom_image_get_bytes()
goffset eom_image_get_bytes (EomImage * img)
Definition at line 2097 of file eom-image.c.
References _EomImagePrivate::bytes, EOM_IS_IMAGE, and _EomImage::priv.
eom_image_get_caption()
const gchar * eom_image_get_caption (EomImage * img)
Definition at line 1911 of file eom-image.c.
References _EomImagePrivate::caption, EOM_IS_IMAGE, eom_util_make_valid_utf8(), FALSE, _EomImagePrivate::file, name, NULL, _EomImage::priv, and TRUE.
Referenced by eom_image_get_collate_key(), eom_print_operation_new(), and eom_save_as_dialog_new().
eom_image_get_collate_key()
const gchar * eom_image_get_collate_key (EomImage * img)
Definition at line 1985 of file eom-image.c.
References _EomImagePrivate::collate_key, eom_image_get_caption(), EOM_IS_IMAGE, NULL, and _EomImage::priv.
eom_image_get_file()
GFile * eom_image_get_file (EomImage * img)
eom_image_get_file: @img: a EomImage
Gets the #GFile associated with @img
Returns: (transfer full): a #GFile
Definition at line 2081 of file eom-image.c.
References EOM_IS_IMAGE, _EomImagePrivate::file, NULL, and _EomImage::priv.
Referenced by eom_clipboard_handler_new(), eom_image_save_info_new_from_image(), eom_list_store_get_pos_by_image(), eom_list_store_remove_image(), eom_thumbnail_load(), and eom_uri_converter_preview().
eom_image_get_metadata_status()
EomImageMetadataStatus eom_image_get_metadata_status (EomImage * img)
eom_image_get_metadata_status: @img: a EomImage
Returns the current status of the image metadata, that is, whether the metadata has not been read yet, is ready, or not available at all.
Returns: one of EomImageMetadataStatus
Definition at line 2153 of file eom-image.c.
References EOM_IMAGE_METADATA_NOT_AVAILABLE, EOM_IS_IMAGE, _EomImagePrivate::metadata_status, and _EomImage::priv.
eom_image_get_pixbuf()
GdkPixbuf * eom_image_get_pixbuf (EomImage * img)
eom_image_get_pixbuf: @img: a EomImage
Gets the #GdkPixbuf of the image
Returns: (transfer full): a #GdkPixbuf
Definition at line 1333 of file eom-image.c.
References EOM_IS_IMAGE, _EomImagePrivate::image, NULL, _EomImage::priv, and _EomImagePrivate::status_mutex.
Referenced by eom_clipboard_handler_new(), eom_scroll_view_set_image(), and eom_thumbnail_load().
eom_image_get_size()
void eom_image_get_size (EomImage * img, gint * width, gint * height)
References mime_type.
eom_image_get_status()
EomImageStatus eom_image_get_status (EomImage * img)
Definition at line 2136 of file eom-image.c.
References EOM_IMAGE_STATUS_UNKNOWN, EOM_IS_IMAGE, _EomImage::priv, and _EomImagePrivate::status.
eom_image_get_supported_mime_types()
GList * eom_image_get_supported_mime_types (void)
eom_image_get_supported_mime_types:
Gets the list of supported mimetypes
Returns: (transfer none)(element-type utf8): a #GList of supported mimetypes
Definition at line 2209 of file eom-image.c.
References NULL.
Referenced by eom_image_is_supported_mime_type().
eom_image_get_thumbnail()
GdkPixbuf * eom_image_get_thumbnail (EomImage * img)
eom_image_get_thumbnail: @img: a EomImage
Gets the thumbnail pixbuf for @img
Returns: (transfer full): a #GdkPixbuf with a thumbnail
Definition at line 1369 of file eom-image.c.
References EOM_IS_IMAGE, NULL, _EomImage::priv, and _EomImagePrivate::thumbnail.
eom_image_get_transform()
EomTransform * eom_image_get_transform (EomImage * img)
eom_image_get_transform: @img: a EomImage
Get @img transform.
Returns: (transfer none): A EomTransform.
Definition at line 2384 of file eom-image.c.
References EOM_IS_IMAGE, NULL, _EomImage::priv, and _EomImagePrivate::trans.
eom_image_get_type()
GType eom_image_get_type (void)
References data, and error.
eom_image_get_uri_for_display()
gchar * eom_image_get_uri_for_display (EomImage * img)
Definition at line 2113 of file eom-image.c.
References EOM_IS_IMAGE, _EomImagePrivate::file, NULL, and _EomImage::priv.
eom_image_get_xmp_info()
gpointer eom_image_get_xmp_info (EomImage * img)
eom_image_get_xmp_info: @img: a EomImage
Gets the XMP info for @img or NULL if compiled without libexempi support.
Returns: (transfer full): the xmp data
Definition at line 2054 of file eom-image.c.
References data, EOM_IS_IMAGE, NULL, _EomImage::priv, and _EomImagePrivate::status_mutex.
eom_image_has_data()
gboolean eom_image_has_data (EomImage * img, EomImageData data)
Definition at line 1203 of file eom-image.c.
References EOM_IMAGE_DATA_DIMENSION, EOM_IMAGE_DATA_EXIF, EOM_IMAGE_DATA_IMAGE, EOM_IMAGE_DATA_XMP, EOM_IS_IMAGE, _EomImagePrivate::exif_chunk, FALSE, _EomImagePrivate::height, _EomImagePrivate::image, NULL, _EomImage::priv, TRUE, and _EomImagePrivate::width.
Referenced by eom_image_load(), and eom_image_save_info_new_from_image().
eom_image_is_animation()
gboolean eom_image_is_animation (EomImage * img)
eom_image_is_animation: @img: a EomImage
Checks whether a given image is animated.
Returns: TRUE if it is an animated image, FALSE otherwise.
Definition at line 2303 of file eom-image.c.
References _EomImagePrivate::anim, EOM_IS_IMAGE, FALSE, NULL, and _EomImage::priv.
Referenced by eom_image_start_animation(), and eom_scroll_view_set_image().
eom_image_is_file_changed()
gboolean eom_image_is_file_changed (EomImage * img)
Definition at line 2425 of file eom-image.c.
References EOM_IS_IMAGE, _EomImagePrivate::file_is_changed, _EomImage::priv, and TRUE.
Referenced by eom_thumbnail_load().
eom_image_is_jpeg()
gboolean eom_image_is_jpeg (EomImage * img)
Definition at line 2433 of file eom-image.c.
References EOM_FILE_FORMAT_JPEG, EOM_IS_IMAGE, FALSE, _EomImagePrivate::file_type, NULL, and _EomImage::priv.
eom_image_is_modified()
gboolean eom_image_is_modified (EomImage * img)
Definition at line 2089 of file eom-image.c.
References EOM_IS_IMAGE, FALSE, _EomImagePrivate::modified, and _EomImage::priv.
Referenced by eom_image_save_info_new_from_image().
eom_image_is_supported_mime_type()
gboolean eom_image_is_supported_mime_type (const char * mime_type)
Definition at line 2242 of file eom-image.c.
References eom_image_get_supported_mime_types(), FALSE, mime_type, and NULL.
Referenced by eom_list_store_add_files().
eom_image_load()
gboolean eom_image_load (EomImage * img, EomImageData data2read, EomJob * job, GError ** error)
Definition at line 1247 of file eom-image.c.
References _EomImagePrivate::autorotate, DEBUG_IMAGE_LOAD, eom_debug(), EOM_IMAGE, EOM_IMAGE_DATA_IMAGE, eom_image_has_data(), EOM_IMAGE_METADATA_NOT_READ, EOM_IMAGE_STATUS_FAILED, EOM_IMAGE_STATUS_LOADED, EOM_IMAGE_STATUS_LOADING, EOM_IS_IMAGE, error, FALSE, HAVE_EXIF, _EomImagePrivate::metadata_status, _EomImagePrivate::status, and TRUE.
eom_image_modified()
void eom_image_modified (EomImage * img)
Definition at line 2105 of file eom-image.c.
References EOM_IS_IMAGE, and SIGNAL_CHANGED.
eom_image_new_file()
EomImage * eom_image_new_file (GFile * file, const gchar * caption)
Definition at line 315 of file eom-image.c.
References _EomImagePrivate::caption, EOM_IMAGE, EOM_TYPE_IMAGE, _EomImagePrivate::file, NULL, and _EomImage::priv.
eom_image_save_as_by_info()
gboolean eom_image_save_as_by_info (EomImage * img, EomImageSaveInfo * source, EomImageSaveInfo * target, GError ** error)
Definition at line 1806 of file eom-image.c.
References _, EOM_FILE_FORMAT_JPEG, EOM_IMAGE_ERROR, EOM_IMAGE_ERROR_NOT_LOADED, EOM_IMAGE_ERROR_TMP_FILE_FAILED, EOM_IMAGE_STATUS_UNKNOWN, EOM_IS_IMAGE, EOM_IS_IMAGE_SAVE_INFO, error, _EomImageSaveInfo::exists, FALSE, _EomImageSaveInfo::file, _EomImageSaveInfo::format, _EomImagePrivate::image, _EomImageSaveInfo::modified, NULL, _EomImageSaveInfo::overwrite, _EomImage::priv, and _EomImagePrivate::status.
eom_image_save_by_info()
gboolean eom_image_save_by_info (EomImage * img, EomImageSaveInfo * source, GError ** error)
Definition at line 1696 of file eom-image.c.
References _, EOM_FILE_FORMAT_JPEG, EOM_IMAGE_ERROR, EOM_IMAGE_ERROR_NOT_LOADED, EOM_IMAGE_ERROR_TMP_FILE_FAILED, EOM_IMAGE_STATUS_SAVING, EOM_IS_IMAGE, EOM_IS_IMAGE_SAVE_INFO, error, _EomImageSaveInfo::exists, FALSE, _EomImagePrivate::file, _EomImageSaveInfo::format, _EomImagePrivate::image, _EomImageSaveInfo::modified, NULL, _EomImage::priv, _EomImagePrivate::status, and TRUE.
eom_image_set_thumbnail()
void eom_image_set_thumbnail (EomImage * img, GdkPixbuf * pixbuf)
Definition at line 1295 of file eom-image.c.
References EOM_IS_IMAGE, eom_transform_apply(), NULL, _EomImage::priv, SIGNAL_THUMBNAIL_CHANGED, _EomImagePrivate::thumbnail, and _EomImagePrivate::trans.
Referenced by eom_list_store_thumbnail_unset().
eom_image_start_animation()
gboolean eom_image_start_animation (EomImage * img)
eom_image_start_animation: @img: a EomImage
Starts playing an animated image.
Returns: TRUE on success, FALSE if @img is already playing or isn't an animated image.
Definition at line 2335 of file eom-image.c.
References _EomImagePrivate::anim_iter, eom_image_is_animation(), EOM_IS_IMAGE, FALSE, _EomImagePrivate::is_playing, _EomImage::priv, _EomImagePrivate::status_mutex, and TRUE.
Referenced by eom_scroll_view_set_image().
eom_image_transform()
void eom_image_transform (EomImage * img, EomTransform * trans, EomJob * job)
Definition at line 1394 of file eom-image.c.
References FALSE.
eom_image_undo()
void eom_image_undo (EomImage * img)
Definition at line 1400 of file eom-image.c.
References EOM_IS_IMAGE, EOM_TRANSFORM, eom_transform_is_identity(), eom_transform_reverse(), _EomImagePrivate::modified, NULL, _EomImage::priv, _EomImagePrivate::trans, TRUE, and _EomImagePrivate::undo_stack.