MATE Desktop Environment: eom-transform.h File Reference
eom-transform.h File Reference
#include <glib-object.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
Classes
struct _EomTransform
struct _EomTransformClass
Macros
#define __EOM_JOB_DECLR__
#define EOM_TYPE_TRANSFORM (eom_transform_get_type ())
#define EOM_TRANSFORM(o)
#define EOM_TRANSFORM_CLASS(k)
#define EOM_IS_TRANSFORM(o)
#define EOM_IS_TRANSFORM_CLASS(k)
#define EOM_TRANSFORM_GET_CLASS(o)
Typedefs
typedef struct _EomJob EomJob
typedef struct _EomTransform EomTransform
typedef struct _EomTransformClass EomTransformClass
typedef struct _EomTransformPrivate EomTransformPrivate
Enumerations
enum EomTransformType {
EOM_TRANSFORM_NONE , EOM_TRANSFORM_ROT_90 , EOM_TRANSFORM_ROT_180 , EOM_TRANSFORM_ROT_270 ,
EOM_TRANSFORM_FLIP_HORIZONTAL , EOM_TRANSFORM_FLIP_VERTICAL , EOM_TRANSFORM_TRANSPOSE , EOM_TRANSFORM_TRANSVERSE
}
Functions
GType eom_transform_get_type (void)
GdkPixbuf * eom_transform_apply (EomTransform *trans, GdkPixbuf *pixbuf, EomJob *job)
EomTransform * eom_transform_reverse (EomTransform *trans)
EomTransform * eom_transform_compose (EomTransform *trans, EomTransform *compose)
gboolean eom_transform_is_identity (EomTransform *trans)
EomTransform * eom_transform_identity_new (void)
EomTransform * eom_transform_rotate_new (int degree)
EomTransform * eom_transform_flip_new (EomTransformType type)
EomTransform * eom_transform_new (EomTransformType trans)
EomTransformType eom_transform_get_transform_type (EomTransform *trans)
gboolean eom_transform_get_affine (EomTransform *trans, cairo_matrix_t *affine)
Macro Definition Documentation
__EOM_JOB_DECLR__
#define __EOM_JOB_DECLR__
Definition at line 10 of file eom-transform.h.
EOM_IS_TRANSFORM
#define EOM_IS_TRANSFORM (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), EOM_TYPE_TRANSFORM))
Definition at line 28 of file eom-transform.h.
Referenced by eom_transform_compose(), eom_transform_get_affine(), eom_transform_get_transform_type(), eom_transform_is_identity(), and eom_transform_reverse().
EOM_IS_TRANSFORM_CLASS
#define EOM_IS_TRANSFORM_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), EOM_TYPE_TRANSFORM))
Definition at line 29 of file eom-transform.h.
EOM_TRANSFORM
#define EOM_TRANSFORM (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), EOM_TYPE_TRANSFORM, EomTransform))
Definition at line 26 of file eom-transform.h.
Referenced by eom_image_undo(), eom_transform_compose(), eom_transform_flip_new(), eom_transform_identity_new(), eom_transform_reverse(), and eom_transform_rotate_new().
EOM_TRANSFORM_CLASS
#define EOM_TRANSFORM_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST((k), EOM_TYPE_TRANSFORM, EomTransformClass))
Definition at line 27 of file eom-transform.h.
EOM_TRANSFORM_GET_CLASS
#define EOM_TRANSFORM_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), EOM_TYPE_TRANSFORM, EomTransformClass))
Definition at line 30 of file eom-transform.h.
EOM_TYPE_TRANSFORM
#define EOM_TYPE_TRANSFORM (eom_transform_get_type ())
Definition at line 25 of file eom-transform.h.
Referenced by eom_transform_compose(), eom_transform_flip_new(), eom_transform_identity_new(), eom_transform_reverse(), and eom_transform_rotate_new().
Typedef Documentation
EomJob
typedef struct _EomJob EomJob
Definition at line 11 of file eom-transform.h.
EomTransform
typedef struct _EomTransform EomTransform
Definition at line 38 of file eom-transform.h.
EomTransformClass
typedef struct _EomTransformClass EomTransformClass
Definition at line 39 of file eom-transform.h.
EomTransformPrivate
typedef struct _EomTransformPrivate EomTransformPrivate
Definition at line 40 of file eom-transform.h.
Enumeration Type Documentation
EomTransformType
enum EomTransformType
Enumerator
EOM_TRANSFORM_NONE
EOM_TRANSFORM_ROT_90
EOM_TRANSFORM_ROT_180
EOM_TRANSFORM_ROT_270
EOM_TRANSFORM_FLIP_HORIZONTAL
EOM_TRANSFORM_FLIP_VERTICAL
EOM_TRANSFORM_TRANSPOSE
EOM_TRANSFORM_TRANSVERSE
Definition at line 14 of file eom-transform.h.
Function Documentation
eom_transform_apply()
GdkPixbuf * eom_transform_apply (EomTransform * trans, GdkPixbuf * pixbuf, EomJob * job)
eom_transform_apply: @trans: a EomTransform @pixbuf: a #GdkPixbuf @job: a EomJob
Applies the transformation in @trans to @pixbuf, setting its progress in @job.
Returns: (transfer full): A new #GdkPixbuf with the transformation applied.
Definition at line 75 of file eom-transform.c.
References dest, eom_job_set_progress(), EOM_TRANSFORM_N_PROG_UPDATES, MAX, MIN, NULL, and _EomTransform::priv.
Referenced by eom_image_set_thumbnail().
eom_transform_compose()
EomTransform * eom_transform_compose (EomTransform * trans, EomTransform * compose)
eom_transform_compose: @trans: a EomTransform @compose: another EomTransform
Returns: (transfer full): a new transform
Definition at line 264 of file eom-transform.c.
References EOM_IS_TRANSFORM, EOM_TRANSFORM, EOM_TYPE_TRANSFORM, NULL, and _EomTransform::priv.
Referenced by eom_transform_new().
eom_transform_flip_new()
EomTransform * eom_transform_flip_new (EomTransformType type)
Definition at line 315 of file eom-transform.c.
References EOM_TRANSFORM, EOM_TRANSFORM_FLIP_HORIZONTAL, EOM_TRANSFORM_FLIP_VERTICAL, EOM_TYPE_TRANSFORM, NULL, and _EomTransform::priv.
Referenced by eom_transform_new().
eom_transform_get_affine()
gboolean eom_transform_get_affine (EomTransform * trans, cairo_matrix_t * affine)
Definition at line 438 of file eom-transform.c.
References EOM_IS_TRANSFORM, FALSE, _EomTransform::priv, and TRUE.
eom_transform_get_transform_type()
EomTransformType eom_transform_get_transform_type (EomTransform * trans)
Definition at line 382 of file eom-transform.c.
References EOM_DEG_TO_RAD, EOM_IS_TRANSFORM, EOM_TRANSFORM_FLIP_HORIZONTAL, EOM_TRANSFORM_FLIP_VERTICAL, EOM_TRANSFORM_NONE, EOM_TRANSFORM_ROT_180, EOM_TRANSFORM_ROT_270, EOM_TRANSFORM_ROT_90, EOM_TRANSFORM_TRANSPOSE, EOM_TRANSFORM_TRANSVERSE, FALSE, _EomTransform::priv, and TRUE.
eom_transform_get_type()
GType eom_transform_get_type (void)
eom_transform_identity_new()
EomTransform * eom_transform_identity_new (void)
Definition at line 291 of file eom-transform.c.
References EOM_TRANSFORM, EOM_TYPE_TRANSFORM, NULL, and _EomTransform::priv.
Referenced by eom_transform_new().
eom_transform_is_identity()
gboolean eom_transform_is_identity (EomTransform * trans)
Definition at line 281 of file eom-transform.c.
References EOM_IS_TRANSFORM, FALSE, and _EomTransform::priv.
Referenced by eom_image_undo().
eom_transform_new()
EomTransform * eom_transform_new (EomTransformType trans)
Definition at line 335 of file eom-transform.c.
References eom_transform_compose(), EOM_TRANSFORM_FLIP_HORIZONTAL, eom_transform_flip_new(), EOM_TRANSFORM_FLIP_VERTICAL, eom_transform_identity_new(), EOM_TRANSFORM_NONE, EOM_TRANSFORM_ROT_180, EOM_TRANSFORM_ROT_270, EOM_TRANSFORM_ROT_90, eom_transform_rotate_new(), EOM_TRANSFORM_TRANSPOSE, EOM_TRANSFORM_TRANSVERSE, and NULL.
eom_transform_reverse()
EomTransform * eom_transform_reverse (EomTransform * trans)
eom_transform_reverse: @trans: a EomTransform
Creates the reverse transformation of @trans
Returns: (transfer full): a new transformation
Definition at line 239 of file eom-transform.c.
References EOM_IS_TRANSFORM, EOM_TRANSFORM, EOM_TYPE_TRANSFORM, NULL, and _EomTransform::priv.
Referenced by eom_image_undo().
eom_transform_rotate_new()
EomTransform * eom_transform_rotate_new (int degree)
Definition at line 303 of file eom-transform.c.
References EOM_DEG_TO_RAD, EOM_TRANSFORM, EOM_TYPE_TRANSFORM, NULL, and _EomTransform::priv.
Referenced by eom_transform_new().