MATE Desktop Environment: eom-print.c File Reference
eom-print.c File Reference
#include "config.h"
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include "eom-image.h"
#include "eom-print.h"
#include "eom-print-image-setup.h"
#include "eom-util.h"
#include "eom-debug.h"
Macros
#define EOM_PRINT_SETTINGS_FILE "eom-print-settings.ini"
#define EOM_PAGE_SETUP_GROUP "Page Setup"
#define EOM_PRINT_SETTINGS_GROUP "Print Settings"
Functions
GtkPrintOperation * eom_print_operation_new (EomImage *image, GtkPrintSettings *print_settings, GtkPageSetup *page_setup)
GtkPageSetup * eom_print_get_page_setup (void)
void eom_print_set_page_setup (GtkPageSetup *page_setup)
GtkPrintSettings * eom_print_get_print_settings (void)
void eom_print_set_print_settings (GtkPrintSettings *print_settings)
Macro Definition Documentation
EOM_PAGE_SETUP_GROUP
#define EOM_PAGE_SETUP_GROUP "Page Setup"
Definition at line 37 of file eom-print.c.
Referenced by eom_print_get_page_setup(), and eom_print_set_page_setup().
EOM_PRINT_SETTINGS_FILE
#define EOM_PRINT_SETTINGS_FILE "eom-print-settings.ini"
Definition at line 36 of file eom-print.c.
EOM_PRINT_SETTINGS_GROUP
#define EOM_PRINT_SETTINGS_GROUP "Print Settings"
Definition at line 38 of file eom-print.c.
Referenced by eom_print_get_print_settings(), and eom_print_set_print_settings().
Function Documentation
eom_print_get_page_setup()
GtkPageSetup * eom_print_get_page_setup (void)
Definition at line 411 of file eom-print.c.
References EOM_PAGE_SETUP_GROUP, error, and NULL.
eom_print_get_print_settings()
GtkPrintSettings * eom_print_get_print_settings (void)
Definition at line 479 of file eom-print.c.
References EOM_PRINT_SETTINGS_GROUP, error, and NULL.
eom_print_operation_new()
GtkPrintOperation * eom_print_operation_new (EomImage * image, GtkPrintSettings * print_settings, GtkPageSetup * page_setup)
Definition at line 314 of file eom-print.c.
References _, data, DEBUG_PRINTING, eom_debug(), eom_image_get_caption(), eom_image_get_size(), eom_print_image_setup_update(), NULL, and TRUE.
eom_print_set_page_setup()
void eom_print_set_page_setup (GtkPageSetup * page_setup)
Definition at line 462 of file eom-print.c.
References EOM_PAGE_SETUP_GROUP, and NULL.
eom_print_set_print_settings()
void eom_print_set_print_settings (GtkPrintSettings * print_settings)
Definition at line 507 of file eom-print.c.
References EOM_PRINT_SETTINGS_GROUP, and NULL.