MATE Desktop Environment: eom-save-as-dialog-helper.h File Reference
eom-save-as-dialog-helper.h File Reference
#include <gtk/gtk.h>
#include <gio/gio.h>
#include "eom-uri-converter.h"
Functions
G_GNUC_INTERNAL GtkWidget * eom_save_as_dialog_new (GtkWindow *main, GList *images, GFile *base_file)
G_GNUC_INTERNAL EomURIConverter * eom_save_as_dialog_get_converter (GtkWidget *dlg)
Function Documentation
eom_save_as_dialog_get_converter()
G_GNUC_INTERNAL EomURIConverter * eom_save_as_dialog_get_converter (GtkWidget * dlg)
Definition at line 268 of file eom-save-as-dialog-helper.c.
References data, eom_uri_converter_new(), and NULL.
eom_save_as_dialog_new()
G_GNUC_INTERNAL GtkWidget * eom_save_as_dialog_new (GtkWindow * main, GList * images, GFile * base_file)
Definition at line 202 of file eom-save-as-dialog-helper.c.
References data, EOM_IMAGE, eom_image_get_caption(), GETTEXT_PACKAGE, int(), label, and main().