MATE Desktop Environment: egg-editable-toolbar.h File Reference
egg-editable-toolbar.h File Reference
#include "egg-toolbars-model.h"
#include <gtk/gtk.h>
Classes
struct _EggEditableToolbar
struct _EggEditableToolbarClass
Macros
#define EGG_TYPE_EDITABLE_TOOLBAR (egg_editable_toolbar_get_type ())
#define EGG_EDITABLE_TOOLBAR(obj)
#define EGG_EDITABLE_TOOLBAR_CLASS(klass)
#define EGG_IS_EDITABLE_TOOLBAR(obj)
#define EGG_IS_EDITABLE_TOOLBAR_CLASS(klass)
#define EGG_EDITABLE_TOOLBAR_GET_CLASS(obj)
Functions
GType egg_editable_toolbar_get_type (void)
GtkWidget * egg_editable_toolbar_new (GtkUIManager *manager, const char *visibility_path)
GtkWidget * egg_editable_toolbar_new_with_model (GtkUIManager *manager, EggToolbarsModel *model, const char *visibility_path)
void egg_editable_toolbar_set_model (EggEditableToolbar *etoolbar, EggToolbarsModel *model)
EggToolbarsModel * egg_editable_toolbar_get_model (EggEditableToolbar *etoolbar)
GtkUIManager * egg_editable_toolbar_get_manager (EggEditableToolbar *etoolbar)
void egg_editable_toolbar_set_edit_mode (EggEditableToolbar *etoolbar, gboolean mode)
gboolean egg_editable_toolbar_get_edit_mode (EggEditableToolbar *etoolbar)
void egg_editable_toolbar_show (EggEditableToolbar *etoolbar, const char *name)
void egg_editable_toolbar_hide (EggEditableToolbar *etoolbar, const char *name)
void egg_editable_toolbar_set_fixed (EggEditableToolbar *etoolbar, GtkToolbar *fixed_toolbar)
GtkWidget * egg_editable_toolbar_get_selected (EggEditableToolbar *etoolbar)
void egg_editable_toolbar_set_selected (EggEditableToolbar *etoolbar, GtkWidget *widget)
void egg_editable_toolbar_add_visibility (EggEditableToolbar *etoolbar, const char *path)
GtkWidget * _egg_editable_toolbar_new_separator_image (void)
Macro Definition Documentation
EGG_EDITABLE_TOOLBAR
#define EGG_EDITABLE_TOOLBAR (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), EGG_TYPE_EDITABLE_TOOLBAR, EggEditableToolbar))
Definition at line 32 of file eom/cut-n-paste/toolbar-editor/egg-editable-toolbar.h.
EGG_EDITABLE_TOOLBAR_CLASS
#define EGG_EDITABLE_TOOLBAR_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), EGG_TYPE_EDITABLE_TOOLBAR, EggEditableToolbarClass))
Definition at line 33 of file eom/cut-n-paste/toolbar-editor/egg-editable-toolbar.h.
EGG_EDITABLE_TOOLBAR_GET_CLASS
#define EGG_EDITABLE_TOOLBAR_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), EGG_TYPE_EDITABLE_TOOLBAR, EggEditableToolbarClass))
Definition at line 36 of file eom/cut-n-paste/toolbar-editor/egg-editable-toolbar.h.
EGG_IS_EDITABLE_TOOLBAR
#define EGG_IS_EDITABLE_TOOLBAR (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), EGG_TYPE_EDITABLE_TOOLBAR))
Definition at line 34 of file eom/cut-n-paste/toolbar-editor/egg-editable-toolbar.h.
EGG_IS_EDITABLE_TOOLBAR_CLASS
#define EGG_IS_EDITABLE_TOOLBAR_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), EGG_TYPE_EDITABLE_TOOLBAR))
Definition at line 35 of file eom/cut-n-paste/toolbar-editor/egg-editable-toolbar.h.
EGG_TYPE_EDITABLE_TOOLBAR
#define EGG_TYPE_EDITABLE_TOOLBAR (egg_editable_toolbar_get_type ())
Definition at line 31 of file eom/cut-n-paste/toolbar-editor/egg-editable-toolbar.h.
Function Documentation
_egg_editable_toolbar_new_separator_image()
GtkWidget * _egg_editable_toolbar_new_separator_image (void)
Definition at line 1872 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
egg_editable_toolbar_add_visibility()
void egg_editable_toolbar_add_visibility (EggEditableToolbar * etoolbar, const char * path)
Definition at line 1732 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References _EggEditableToolbar::priv.
egg_editable_toolbar_get_edit_mode()
gboolean egg_editable_toolbar_get_edit_mode (EggEditableToolbar * etoolbar)
Definition at line 1716 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References _EggEditableToolbar::priv.
egg_editable_toolbar_get_manager()
GtkUIManager * egg_editable_toolbar_get_manager (EggEditableToolbar * etoolbar)
egg_editable_toolbar_get_manager:
Return value: (transfer none):
Definition at line 1900 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References _EggEditableToolbar::priv.
egg_editable_toolbar_get_model()
EggToolbarsModel * egg_editable_toolbar_get_model (EggEditableToolbar * etoolbar)
egg_editable_toolbar_get_model: @etoolbar:
Returns: (transfer none):
Definition at line 1889 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References _EggEditableToolbar::priv.
egg_editable_toolbar_get_selected()
GtkWidget * egg_editable_toolbar_get_selected (EggEditableToolbar * etoolbar)
egg_editable_toolbar_get_selected: @etoolbar:
Returns: (transfer none):
Definition at line 1497 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References _EggEditableToolbar::priv.
egg_editable_toolbar_get_type()
GType egg_editable_toolbar_get_type (void)
References name.
egg_editable_toolbar_hide()
void egg_editable_toolbar_hide (EggEditableToolbar * etoolbar, const char * name)
Definition at line 1761 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References egg_toolbars_model_n_toolbars(), egg_toolbars_model_toolbar_nth(), name, and _EggEditableToolbar::priv.
egg_editable_toolbar_new()
GtkWidget * egg_editable_toolbar_new (GtkUIManager * manager, const char * visibility_path)
Definition at line 1694 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References EGG_TYPE_EDITABLE_TOOLBAR, and NULL.
egg_editable_toolbar_new_with_model()
GtkWidget * egg_editable_toolbar_new_with_model (GtkUIManager * manager, EggToolbarsModel * model, const char * visibility_path)
Definition at line 1704 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References EGG_TYPE_EDITABLE_TOOLBAR, and NULL.
egg_editable_toolbar_set_edit_mode()
void egg_editable_toolbar_set_edit_mode (EggEditableToolbar * etoolbar, gboolean mode)
Definition at line 1724 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
egg_editable_toolbar_set_fixed()
void egg_editable_toolbar_set_fixed (EggEditableToolbar * etoolbar, GtkToolbar * fixed_toolbar)
Definition at line 1782 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References FALSE, NULL, and _EggEditableToolbar::priv.
egg_editable_toolbar_set_model()
void egg_editable_toolbar_set_model (EggEditableToolbar * etoolbar, EggToolbarsModel * model)
Definition at line 1369 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References _EggEditableToolbar::priv.
egg_editable_toolbar_set_selected()
void egg_editable_toolbar_set_selected (EggEditableToolbar * etoolbar, GtkWidget * widget)
Definition at line 1503 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References EGG_TB_MODEL_NOT_EDITABLE, egg_toolbars_model_get_flags(), FALSE, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, NULL, and _EggEditableToolbar::priv.
egg_editable_toolbar_show()
void egg_editable_toolbar_show (EggEditableToolbar * etoolbar, const char * name)
Definition at line 1740 of file atril/cut-n-paste/toolbar-editor/egg-editable-toolbar.c.
References egg_toolbars_model_n_toolbars(), egg_toolbars_model_toolbar_nth(), name, and _EggEditableToolbar::priv.