MATE Desktop Environment: egg-toolbars-model.h File Reference
egg-toolbars-model.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <gdk/gdk.h>
Classes
struct EggToolbarsModel
struct EggToolbarsModelClass
struct EggToolbarsItemType
Macros
#define EGG_TYPE_TOOLBARS_MODEL (egg_toolbars_model_get_type ())
#define EGG_TOOLBARS_MODEL(obj)
#define EGG_TOOLBARS_MODEL_CLASS(klass)
#define EGG_IS_TOOLBARS_MODEL(obj)
#define EGG_IS_TOOLBARS_MODEL_CLASS(klass)
#define EGG_TOOLBARS_MODEL_GET_CLASS(obj)
#define EGG_TOOLBAR_ITEM_TYPE "application/x-toolbar-item"
Enumerations
enum EggTbModelFlags {
EGG_TB_MODEL_NOT_REMOVABLE = 1 << 0 , EGG_TB_MODEL_NOT_EDITABLE = 1 << 1 , EGG_TB_MODEL_BOTH = 1 << 2 , EGG_TB_MODEL_BOTH_HORIZ = 1 << 3 ,
EGG_TB_MODEL_ICONS = 1 << 4 , EGG_TB_MODEL_TEXT = 1 << 5 , EGG_TB_MODEL_STYLES_MASK = 0x3C , EGG_TB_MODEL_ACCEPT_ITEMS_ONLY = 1 << 6 ,
EGG_TB_MODEL_HIDDEN = 1 << 7
}
enum EggTbModelNameFlags { EGG_TB_MODEL_NAME_USED = 1 << 0 , EGG_TB_MODEL_NAME_INFINITE = 1 << 1 , EGG_TB_MODEL_NAME_KNOWN = 1 << 2 }
Functions
GType egg_toolbars_model_get_type (void)
EggToolbarsModel * egg_toolbars_model_new (void)
gboolean egg_toolbars_model_load_names (EggToolbarsModel *model, const char *xml_file)
gboolean egg_toolbars_model_load_toolbars (EggToolbarsModel *model, const char *xml_file)
void egg_toolbars_model_save_toolbars (EggToolbarsModel *model, const char *xml_file, const char *version)
GList * egg_toolbars_model_get_types (EggToolbarsModel *model)
void egg_toolbars_model_set_types (EggToolbarsModel *model, GList *types)
char * egg_toolbars_model_get_name (EggToolbarsModel *model, GdkAtom type, const char *data, gboolean create)
char * egg_toolbars_model_get_data (EggToolbarsModel *model, GdkAtom type, const char *name)
GPtrArray * egg_toolbars_model_get_name_avail (EggToolbarsModel *model)
gint egg_toolbars_model_get_name_flags (EggToolbarsModel *model, const char *name)
void egg_toolbars_model_set_name_flags (EggToolbarsModel *model, const char *name, gint flags)
EggTbModelFlags egg_toolbars_model_get_flags (EggToolbarsModel *model, int toolbar_position)
void egg_toolbars_model_set_flags (EggToolbarsModel *model, int toolbar_position, EggTbModelFlags flags)
int egg_toolbars_model_add_toolbar (EggToolbarsModel *model, int position, const char *name)
void egg_toolbars_model_remove_toolbar (EggToolbarsModel *model, int position)
gboolean egg_toolbars_model_add_item (EggToolbarsModel *model, int toolbar_position, int position, const char *name)
void egg_toolbars_model_remove_item (EggToolbarsModel *model, int toolbar_position, int position)
void egg_toolbars_model_move_item (EggToolbarsModel *model, int toolbar_position, int position, int new_toolbar_position, int new_position)
void egg_toolbars_model_delete_item (EggToolbarsModel *model, const char *name)
int egg_toolbars_model_n_items (EggToolbarsModel *model, int toolbar_position)
const char * egg_toolbars_model_item_nth (EggToolbarsModel *model, int toolbar_position, int position)
int egg_toolbars_model_n_toolbars (EggToolbarsModel *model)
const char * egg_toolbars_model_toolbar_nth (EggToolbarsModel *model, int position)
Macro Definition Documentation
EGG_IS_TOOLBARS_MODEL
#define EGG_IS_TOOLBARS_MODEL (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), EGG_TYPE_TOOLBARS_MODEL))
Definition at line 33 of file eom/cut-n-paste/toolbar-editor/egg-toolbars-model.h.
EGG_IS_TOOLBARS_MODEL_CLASS
#define EGG_IS_TOOLBARS_MODEL_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), EGG_TYPE_TOOLBARS_MODEL))
Definition at line 34 of file eom/cut-n-paste/toolbar-editor/egg-toolbars-model.h.
EGG_TOOLBAR_ITEM_TYPE
#define EGG_TOOLBAR_ITEM_TYPE "application/x-toolbar-item"
Definition at line 41 of file eom/cut-n-paste/toolbar-editor/egg-toolbars-model.h.
EGG_TOOLBARS_MODEL
#define EGG_TOOLBARS_MODEL (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), EGG_TYPE_TOOLBARS_MODEL, EggToolbarsModel))
Definition at line 31 of file eom/cut-n-paste/toolbar-editor/egg-toolbars-model.h.
EGG_TOOLBARS_MODEL_CLASS
#define EGG_TOOLBARS_MODEL_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), EGG_TYPE_TOOLBARS_MODEL, EggToolbarsModelClass))
Definition at line 32 of file eom/cut-n-paste/toolbar-editor/egg-toolbars-model.h.
EGG_TOOLBARS_MODEL_GET_CLASS
#define EGG_TOOLBARS_MODEL_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), EGG_TYPE_TOOLBARS_MODEL, EggToolbarsModelClass))
Definition at line 35 of file eom/cut-n-paste/toolbar-editor/egg-toolbars-model.h.
EGG_TYPE_TOOLBARS_MODEL
#define EGG_TYPE_TOOLBARS_MODEL (egg_toolbars_model_get_type ())
Definition at line 30 of file eom/cut-n-paste/toolbar-editor/egg-toolbars-model.h.
Enumeration Type Documentation
EggTbModelFlags
enum EggTbModelFlags
Enumerator
EGG_TB_MODEL_NOT_REMOVABLE
EGG_TB_MODEL_NOT_EDITABLE
EGG_TB_MODEL_BOTH
EGG_TB_MODEL_BOTH_HORIZ
EGG_TB_MODEL_ICONS
EGG_TB_MODEL_TEXT
EGG_TB_MODEL_STYLES_MASK
EGG_TB_MODEL_ACCEPT_ITEMS_ONLY
EGG_TB_MODEL_HIDDEN
Definition at line 43 of file eom/cut-n-paste/toolbar-editor/egg-toolbars-model.h.
EggTbModelNameFlags
enum EggTbModelNameFlags
Enumerator
EGG_TB_MODEL_NAME_USED
EGG_TB_MODEL_NAME_INFINITE
EGG_TB_MODEL_NAME_KNOWN
Definition at line 56 of file eom/cut-n-paste/toolbar-editor/egg-toolbars-model.h.
Function Documentation
egg_toolbars_model_add_item()
gboolean egg_toolbars_model_add_item (EggToolbarsModel * model, int toolbar_position, int position, const char * name)
Definition at line 430 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References EggToolbarsModelClass::add_item, EGG_TOOLBARS_MODEL_GET_CLASS, and name.
egg_toolbars_model_add_toolbar()
int egg_toolbars_model_add_toolbar (EggToolbarsModel * model, int position, const char * name)
Definition at line 440 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References EGG_IS_TOOLBARS_MODEL, name, and TOOLBAR_ADDED.
egg_toolbars_model_delete_item()
void egg_toolbars_model_delete_item (EggToolbarsModel * model, const char * name)
Definition at line 903 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References EGG_IS_TOOLBARS_MODEL, EGG_TB_MODEL_NOT_REMOVABLE, item, ITEM_REMOVED, name, NULL, and TOOLBAR_REMOVED.
egg_toolbars_model_get_data()
char * egg_toolbars_model_get_data (EggToolbarsModel * model, GdkAtom type, const char * name)
Definition at line 335 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References data, EGG_TOOLBAR_ITEM_TYPE, FALSE, EggToolbarsItemType::get_data, name, NULL, and EggToolbarsItemType::type.
egg_toolbars_model_get_flags()
EggTbModelFlags egg_toolbars_model_get_flags (EggToolbarsModel * model, int toolbar_position)
Definition at line 301 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References NULL.
Referenced by egg_editable_toolbar_set_selected(), and egg_toolbars_model_remove_toolbar().
egg_toolbars_model_get_name()
char * egg_toolbars_model_get_name (EggToolbarsModel * model, GdkAtom type, const char * data, gboolean create)
Definition at line 364 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References data, EGG_TOOLBAR_ITEM_TYPE, FALSE, EggToolbarsItemType::get_name, name, EggToolbarsItemType::new_name, NULL, and EggToolbarsItemType::type.
egg_toolbars_model_get_name_avail()
GPtrArray * egg_toolbars_model_get_name_avail (EggToolbarsModel * model)
egg_toolbars_model_get_name_avail: @model:
Returns: (element-type utf8) (transfer container):
Definition at line 1058 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
egg_toolbars_model_get_name_flags()
gint egg_toolbars_model_get_name_flags (EggToolbarsModel * model, const char * name)
Definition at line 1066 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References name.
egg_toolbars_model_get_type()
GType egg_toolbars_model_get_type (void)
References data, and name.
egg_toolbars_model_get_types()
GList * egg_toolbars_model_get_types (EggToolbarsModel * model)
egg_toolbars_model_get_types: @model:
Returns: (transfer none) (element-type EggToolbarsItemType):
Definition at line 1026 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
egg_toolbars_model_item_nth()
const char * egg_toolbars_model_item_nth (EggToolbarsModel * model, int toolbar_position, int position)
Definition at line 980 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References item, and NULL.
egg_toolbars_model_load_names()
gboolean egg_toolbars_model_load_names (EggToolbarsModel * model, const char * xml_file)
Definition at line 684 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References EGG_IS_TOOLBARS_MODEL, FALSE, NULL, and TRUE.
Referenced by eom_application_reset_toolbars_model().
egg_toolbars_model_load_toolbars()
gboolean egg_toolbars_model_load_toolbars (EggToolbarsModel * model, const char * xml_file)
Definition at line 583 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References EGG_IS_TOOLBARS_MODEL, FALSE, NULL, and TRUE.
Referenced by eom_application_reset_toolbars_model().
egg_toolbars_model_move_item()
void egg_toolbars_model_move_item (EggToolbarsModel * model, int toolbar_position, int position, int new_toolbar_position, int new_position)
Definition at line 872 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References EGG_IS_TOOLBARS_MODEL, ITEM_ADDED, ITEM_REMOVED, and NULL.
egg_toolbars_model_n_items()
int egg_toolbars_model_n_items (EggToolbarsModel * model, int toolbar_position)
Definition at line 968 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References NULL.
egg_toolbars_model_n_toolbars()
int egg_toolbars_model_n_toolbars (EggToolbarsModel * model)
Definition at line 999 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
Referenced by egg_editable_toolbar_hide(), and egg_editable_toolbar_show().
egg_toolbars_model_new()
EggToolbarsModel * egg_toolbars_model_new (void)
Definition at line 822 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References EGG_TOOLBARS_MODEL, EGG_TYPE_TOOLBARS_MODEL, and NULL.
Referenced by eom_application_reset_toolbars_model().
egg_toolbars_model_remove_item()
void egg_toolbars_model_remove_item (EggToolbarsModel * model, int toolbar_position, int position)
Definition at line 851 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References EGG_IS_TOOLBARS_MODEL, ITEM_REMOVED, and NULL.
egg_toolbars_model_remove_toolbar()
void egg_toolbars_model_remove_toolbar (EggToolbarsModel * model, int position)
Definition at line 828 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References EGG_IS_TOOLBARS_MODEL, EGG_TB_MODEL_NOT_REMOVABLE, egg_toolbars_model_get_flags(), NULL, and TOOLBAR_REMOVED.
egg_toolbars_model_save_toolbars()
void egg_toolbars_model_save_toolbars (EggToolbarsModel * model, const char * xml_file, const char * version)
Definition at line 195 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References EGG_IS_TOOLBARS_MODEL.
Referenced by eom_application_save_toolbars_model().
egg_toolbars_model_set_flags()
void egg_toolbars_model_set_flags (EggToolbarsModel * model, int toolbar_position, EggTbModelFlags flags)
Definition at line 316 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References NULL, and TOOLBAR_CHANGED.
Referenced by eom_application_reset_toolbars_model().
egg_toolbars_model_set_name_flags()
void egg_toolbars_model_set_name_flags (EggToolbarsModel * model, const char * name, gint flags)
Definition at line 1072 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References name.
egg_toolbars_model_set_types()
void egg_toolbars_model_set_types (EggToolbarsModel * model, GList * types)
egg_toolbars_model_set_types: @model: @types: (element-type EggToolbarsItemType):
Definition at line 1038 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
egg_toolbars_model_toolbar_nth()
const char * egg_toolbars_model_toolbar_nth (EggToolbarsModel * model, int position)
Definition at line 1005 of file atril/cut-n-paste/toolbar-editor/egg-toolbars-model.c.
References NULL.
Referenced by egg_editable_toolbar_hide(), and egg_editable_toolbar_show().