MATE Desktop Environment: ev-annotation-properties-dialog.c File Reference
ev-annotation-properties-dialog.c File Reference
#include <config.h>
#include <glib/gi18n.h>
#include "ev-annotation-properties-dialog.h"
Enumerations
enum { PROP_0 , PROP_ANNOT_TYPE }
Functions
GtkWidget * ev_annotation_properties_dialog_new (EvAnnotationType annot_type)
GtkWidget * ev_annotation_properties_dialog_new_with_annotation (EvAnnotation *annot)
const gchar * ev_annotation_properties_dialog_get_author (EvAnnotationPropertiesDialog *dialog)
void ev_annotation_properties_dialog_get_rgba (EvAnnotationPropertiesDialog *dialog, GdkRGBA *rgba)
gdouble ev_annotation_properties_dialog_get_opacity (EvAnnotationPropertiesDialog *dialog)
gboolean ev_annotation_properties_dialog_get_popup_is_open (EvAnnotationPropertiesDialog *dialog)
EvAnnotationTextIcon ev_annotation_properties_dialog_get_text_icon (EvAnnotationPropertiesDialog *dialog)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_ANNOT_TYPE
Definition at line 27 of file ev-annotation-properties-dialog.c.
Function Documentation
ev_annotation_properties_dialog_get_author()
const gchar * ev_annotation_properties_dialog_get_author (EvAnnotationPropertiesDialog * dialog)
Definition at line 286 of file ev-annotation-properties-dialog.c.
ev_annotation_properties_dialog_get_opacity()
gdouble ev_annotation_properties_dialog_get_opacity (EvAnnotationPropertiesDialog * dialog)
Definition at line 299 of file ev-annotation-properties-dialog.c.
ev_annotation_properties_dialog_get_popup_is_open()
gboolean ev_annotation_properties_dialog_get_popup_is_open (EvAnnotationPropertiesDialog * dialog)
Definition at line 305 of file ev-annotation-properties-dialog.c.
ev_annotation_properties_dialog_get_rgba()
void ev_annotation_properties_dialog_get_rgba (EvAnnotationPropertiesDialog * dialog, GdkRGBA * rgba)
Definition at line 292 of file ev-annotation-properties-dialog.c.
ev_annotation_properties_dialog_get_text_icon()
EvAnnotationTextIcon ev_annotation_properties_dialog_get_text_icon (EvAnnotationPropertiesDialog * dialog)
Definition at line 311 of file ev-annotation-properties-dialog.c.
ev_annotation_properties_dialog_new()
GtkWidget * ev_annotation_properties_dialog_new (EvAnnotationType annot_type)
Definition at line 242 of file ev-annotation-properties-dialog.c.
References EV_TYPE_ANNOTATION_PROPERTIES_DIALOG, and NULL.
Referenced by ev_annotation_properties_dialog_new_with_annotation().
ev_annotation_properties_dialog_new_with_annotation()
GtkWidget * ev_annotation_properties_dialog_new_with_annotation (EvAnnotation * annot)
Definition at line 250 of file ev-annotation-properties-dialog.c.
References ev_annotation_get_annotation_type(), ev_annotation_get_rgba(), EV_ANNOTATION_MARKUP, ev_annotation_markup_get_label(), ev_annotation_markup_get_opacity(), ev_annotation_markup_get_popup_is_open(), ev_annotation_properties_dialog_new(), EV_ANNOTATION_TEXT, ev_annotation_text_get_icon(), EV_IS_ANNOTATION_TEXT, and label.