MATE Desktop Environment: ev-application.c File Reference
ev-application.c File Reference
#include <config.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <glib/gstdio.h>
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
#include "eggsmclient.h"
#include "ev-application.h"
#include "ev-file-helpers.h"
#include "ev-stock-icons.h"
Functions
EvApplication * ev_application_new (void)
gboolean ev_application_load_session (EvApplication *application)
: the name of the display to be open if it's needed.
ev_display_open_if_needed:
Search among all the open displays if any of them have the same name as the passed name. If the display isn't found it tries the open it.
Returns: a #GdkDisplay of the display with the passed name.
void ev_application_open_uri_at_dest (EvApplication *application, const char *uri, GdkScreen *screen, EvLinkDest *dest, EvWindowRunMode mode, const gchar *search_string, guint timestamp)
void ev_application_open_window (EvApplication *application, GdkScreen *screen, guint32 timestamp)
void ev_application_open_uri_list (EvApplication *application, GSList *uri_list, GdkScreen *screen, guint timestamp)
gboolean ev_application_has_window (EvApplication *application)
guint ev_application_get_n_windows (EvApplication *application)
const gchar * ev_application_get_uri (EvApplication *application)
GObject * ev_application_get_media_keys (EvApplication *application)
const gchar * ev_application_get_dot_dir (EvApplication *application, gboolean create)
Function Documentation
ev_application_get_dot_dir()
const gchar * ev_application_get_dot_dir (EvApplication * application, gboolean create)
Definition at line 1065 of file ev-application.c.
ev_application_get_media_keys()
GObject * ev_application_get_media_keys (EvApplication * application)
ev_application_get_media_keys: @application: The instance of the application.
It gives you access to the media player keys handler object.
Returns: A EvMediaPlayerKeys.
Definition at line 1055 of file ev-application.c.
References NULL.
ev_application_get_n_windows()
guint ev_application_get_n_windows (EvApplication * application)
Definition at line 1024 of file ev-application.c.
References EV_IS_WINDOW, and NULL.
ev_application_get_uri()
const gchar * ev_application_get_uri (EvApplication * application)
Definition at line 1041 of file ev-application.c.
ev_application_has_window()
gboolean ev_application_has_window (EvApplication * application)
Definition at line 1008 of file ev-application.c.
References EV_IS_WINDOW, FALSE, NULL, and TRUE.
ev_application_load_session()
gboolean ev_application_load_session (EvApplication * application)
Definition at line 114 of file ev-application.c.
References egg_sm_client_get_state_file(), egg_sm_client_is_resumed(), ev_application_open_uri_at_dest(), FALSE, NULL, and TRUE.
Referenced by main().
ev_application_new()
EvApplication * ev_application_new (void)
ev_application_new:
Creates a new EvApplication instance.
Returns: (transfer full): a newly created EvApplication
Definition at line 102 of file ev-application.c.
References EV_TYPE_APPLICATION, and NULL.
Referenced by main().
ev_application_open_uri_at_dest()
void ev_application_open_uri_at_dest (EvApplication * application, const char * uri, GdkScreen * screen, EvLinkDest * dest, EvWindowRunMode mode, const gchar * search_string, guint timestamp)
ev_application_open_uri_at_dest: @application: The instance of the application. @uri: The uri to be opened. @screen: Thee screen where the link will be shown. @dest: The EvLinkDest of the document. @mode: The run mode of the window. @timestamp: Current time value.
Definition at line 655 of file ev-application.c.
References dest, and NULL.
Referenced by ev_application_load_session(), and ev_application_open_uri_list().
ev_application_open_uri_list()
void ev_application_open_uri_list (EvApplication * application, GSList * uri_list, GdkScreen * screen, guint timestamp)
Definition at line 807 of file ev-application.c.
References ev_application_open_uri_at_dest(), and NULL.
ev_application_open_window()
void ev_application_open_window (EvApplication * application, GdkScreen * screen, guint32 timestamp)
ev_application_open_window: @application: The instance of the application. @timestamp: Current time value.
Creates a new window
Definition at line 691 of file ev-application.c.
References ev_stock_icons_set_screen(), and ev_window_new().