MATE Desktop Environment: ev-attachment.c File Reference
ev-attachment.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include <glib/gstdio.h>
#include <gdk/gdk.h>
#include "ev-file-helpers.h"
#include "ev-attachment.h"
Enumerations
enum {
PROP_0 , PROP_NAME , PROP_DESCRIPTION , PROP_MTIME ,
PROP_CTIME , PROP_SIZE , PROP_DATA
}
Functions
GQuark ev_attachment_error_quark (void)
EvAttachment * ev_attachment_new (const gchar *name, const gchar *description, gint64 mtime, gint64 ctime, gsize size, gpointer data)
const gchar * ev_attachment_get_name (EvAttachment *attachment)
const gchar * ev_attachment_get_description (EvAttachment *attachment)
gint64 ev_attachment_get_modification_date (EvAttachment *attachment)
gint64 ev_attachment_get_creation_date (EvAttachment *attachment)
const gchar * ev_attachment_get_mime_type (EvAttachment *attachment)
gboolean ev_attachment_save (EvAttachment *attachment, GFile *file, GError **error)
gboolean ev_attachment_open (EvAttachment *attachment, GdkScreen *screen, guint32 timestamp, GError **error)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_NAME
PROP_DESCRIPTION
PROP_MTIME
PROP_CTIME
PROP_SIZE
PROP_DATA
Definition at line 27 of file ev-attachment.c.
Function Documentation
ev_attachment_error_quark()
GQuark ev_attachment_error_quark (void)
Definition at line 54 of file ev-attachment.c.
ev_attachment_get_creation_date()
gint64 ev_attachment_get_creation_date (EvAttachment * attachment)
Definition at line 264 of file ev-attachment.c.
References EV_IS_ATTACHMENT, and _EvAttachment::priv.
ev_attachment_get_description()
const gchar * ev_attachment_get_description (EvAttachment * attachment)
Definition at line 248 of file ev-attachment.c.
References EV_IS_ATTACHMENT, NULL, and _EvAttachment::priv.
ev_attachment_get_mime_type()
const gchar * ev_attachment_get_mime_type (EvAttachment * attachment)
Definition at line 272 of file ev-attachment.c.
References EV_IS_ATTACHMENT, NULL, and _EvAttachment::priv.
ev_attachment_get_modification_date()
gint64 ev_attachment_get_modification_date (EvAttachment * attachment)
Definition at line 256 of file ev-attachment.c.
References EV_IS_ATTACHMENT, and _EvAttachment::priv.
ev_attachment_get_name()
const gchar * ev_attachment_get_name (EvAttachment * attachment)
Definition at line 240 of file ev-attachment.c.
References EV_IS_ATTACHMENT, NULL, and _EvAttachment::priv.
Referenced by ev_attachment_open().
ev_attachment_new()
EvAttachment * ev_attachment_new (const gchar * name, const gchar * description, gint64 mtime, gint64 ctime, gsize size, gpointer data)
Definition at line 218 of file ev-attachment.c.
References data, EV_TYPE_ATTACHMENT, name, and NULL.
ev_attachment_open()
gboolean ev_attachment_open (EvAttachment * attachment, GdkScreen * screen, guint32 timestamp, GError ** error)
Definition at line 384 of file ev-attachment.c.
References _, error, EV_ATTACHMENT_ERROR, ev_attachment_get_name(), ev_attachment_save(), EV_IS_ATTACHMENT, ev_mkstemp_file(), FALSE, NULL, and _EvAttachment::priv.
ev_attachment_save()
gboolean ev_attachment_save (EvAttachment * attachment, GFile * file, GError ** error)
Definition at line 280 of file ev-attachment.c.
References _, error, EV_ATTACHMENT_ERROR, EV_IS_ATTACHMENT, FALSE, NULL, _EvAttachment::priv, and TRUE.
Referenced by ev_attachment_open().