MATE Desktop Environment: ev-annotation-properties-dialog.h File Reference
ev-annotation-properties-dialog.h File Reference
#include <gtk/gtk.h>
#include <glib-object.h>
#include <atril-document.h>
Macros
#define EV_TYPE_ANNOTATION_PROPERTIES_DIALOG (ev_annotation_properties_dialog_get_type())
#define EV_ANNOTATION_PROPERTIES_DIALOG(o)
#define EV_ANNOTATION_PROPERTIES_DIALOG_CLASS(k)
#define EV_IS_ANNOTATION_PROPERTIES_DIALOG(o)
#define EV_IS_ANNOTATION_PROPERTIES_DIALOG_CLASS(k)
#define EV_ANNOTATION_PROPERTIES_DIALOG_GET_CLASS(o)
Typedefs
typedef struct _EvAnnotationPropertiesDialog EvAnnotationPropertiesDialog
typedef struct _EvAnnotationPropertiesDialogClass EvAnnotationPropertiesDialogClass
Functions
GType ev_annotation_properties_dialog_get_type (void)
GtkWidget * ev_annotation_properties_dialog_new (EvAnnotationType annot_type)
GtkWidget * ev_annotation_properties_dialog_new_with_annotation (EvAnnotation *annot)
const gchar * ev_annotation_properties_dialog_get_author (EvAnnotationPropertiesDialog *dialog)
void ev_annotation_properties_dialog_get_rgba (EvAnnotationPropertiesDialog *dialog, GdkRGBA *rgba)
gdouble ev_annotation_properties_dialog_get_opacity (EvAnnotationPropertiesDialog *dialog)
gboolean ev_annotation_properties_dialog_get_popup_is_open (EvAnnotationPropertiesDialog *dialog)
EvAnnotationTextIcon ev_annotation_properties_dialog_get_text_icon (EvAnnotationPropertiesDialog *dialog)
Macro Definition Documentation
EV_ANNOTATION_PROPERTIES_DIALOG
#define EV_ANNOTATION_PROPERTIES_DIALOG (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST((o), EV_TYPE_ANNOTATION_PROPERTIES_DIALOG, EvAnnotationPropertiesDialog))
Definition at line 32 of file ev-annotation-properties-dialog.h.
EV_ANNOTATION_PROPERTIES_DIALOG_CLASS
#define EV_ANNOTATION_PROPERTIES_DIALOG_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST((k), EV_TYPE_ANNOTATION_PROPERTIES_DIALOG, EvAnnotationPropertiesDialogClass))
Definition at line 33 of file ev-annotation-properties-dialog.h.
EV_ANNOTATION_PROPERTIES_DIALOG_GET_CLASS
#define EV_ANNOTATION_PROPERTIES_DIALOG_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS((o), EV_TYPE_ANNOTATION_PROPERTIES_DIALOG, EvAnnotationPropertiesDialogClass))
Definition at line 36 of file ev-annotation-properties-dialog.h.
EV_IS_ANNOTATION_PROPERTIES_DIALOG
#define EV_IS_ANNOTATION_PROPERTIES_DIALOG (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE((o), EV_TYPE_ANNOTATION_PROPERTIES_DIALOG))
Definition at line 34 of file ev-annotation-properties-dialog.h.
EV_IS_ANNOTATION_PROPERTIES_DIALOG_CLASS
#define EV_IS_ANNOTATION_PROPERTIES_DIALOG_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE((k), EV_TYPE_ANNOTATION_PROPERTIES_DIALOG))
Definition at line 35 of file ev-annotation-properties-dialog.h.
EV_TYPE_ANNOTATION_PROPERTIES_DIALOG
#define EV_TYPE_ANNOTATION_PROPERTIES_DIALOG (ev_annotation_properties_dialog_get_type())
Definition at line 31 of file ev-annotation-properties-dialog.h.
Referenced by ev_annotation_properties_dialog_new().
Typedef Documentation
EvAnnotationPropertiesDialog
typedef struct _EvAnnotationPropertiesDialog EvAnnotationPropertiesDialog
Definition at line 38 of file ev-annotation-properties-dialog.h.
EvAnnotationPropertiesDialogClass
typedef struct _EvAnnotationPropertiesDialogClass EvAnnotationPropertiesDialogClass
Definition at line 39 of file ev-annotation-properties-dialog.h.
Function Documentation
ev_annotation_properties_dialog_get_author()
const gchar * ev_annotation_properties_dialog_get_author (EvAnnotationPropertiesDialog * dialog)
Definition at line 286 of file ev-annotation-properties-dialog.c.
ev_annotation_properties_dialog_get_opacity()
gdouble ev_annotation_properties_dialog_get_opacity (EvAnnotationPropertiesDialog * dialog)
Definition at line 299 of file ev-annotation-properties-dialog.c.
ev_annotation_properties_dialog_get_popup_is_open()
gboolean ev_annotation_properties_dialog_get_popup_is_open (EvAnnotationPropertiesDialog * dialog)
Definition at line 305 of file ev-annotation-properties-dialog.c.
ev_annotation_properties_dialog_get_rgba()
void ev_annotation_properties_dialog_get_rgba (EvAnnotationPropertiesDialog * dialog, GdkRGBA * rgba)
Definition at line 292 of file ev-annotation-properties-dialog.c.
ev_annotation_properties_dialog_get_text_icon()
EvAnnotationTextIcon ev_annotation_properties_dialog_get_text_icon (EvAnnotationPropertiesDialog * dialog)
Definition at line 311 of file ev-annotation-properties-dialog.c.
ev_annotation_properties_dialog_get_type()
GType ev_annotation_properties_dialog_get_type (void)
ev_annotation_properties_dialog_new()
GtkWidget * ev_annotation_properties_dialog_new (EvAnnotationType annot_type)
Definition at line 242 of file ev-annotation-properties-dialog.c.
References EV_TYPE_ANNOTATION_PROPERTIES_DIALOG, and NULL.
Referenced by ev_annotation_properties_dialog_new_with_annotation().
ev_annotation_properties_dialog_new_with_annotation()
GtkWidget * ev_annotation_properties_dialog_new_with_annotation (EvAnnotation * annot)
Definition at line 250 of file ev-annotation-properties-dialog.c.
References ev_annotation_get_annotation_type(), ev_annotation_get_rgba(), EV_ANNOTATION_MARKUP, ev_annotation_markup_get_label(), ev_annotation_markup_get_opacity(), ev_annotation_markup_get_popup_is_open(), ev_annotation_properties_dialog_new(), EV_ANNOTATION_TEXT, ev_annotation_text_get_icon(), EV_IS_ANNOTATION_TEXT, and label.