MATE Desktop Environment: ev-application.h File Reference
ev-application.h File Reference
#include <glib.h>
#include <gtk/gtk.h>
#include "ev-window.h"
Macros
#define EV_TYPE_APPLICATION (ev_application_get_type ())
#define EV_APPLICATION(object)
#define EV_APPLICATION_CLASS(klass)
#define EV_IS_APPLICATION(object)
#define EV_IS_APPLICATION_CLASS(klass)
#define EV_APPLICATION_GET_CLASS(object)
#define EV_APP ((EvApplication *) g_application_get_default ())
Typedefs
typedef struct _EvApplication EvApplication
typedef struct _EvApplicationClass EvApplicationClass
Functions
GType ev_application_get_type (void)
EvApplication * ev_application_new (void)
gboolean ev_application_load_session (EvApplication *application)
void ev_application_open_window (EvApplication *application, GdkScreen *screen, guint32 timestamp)
void ev_application_open_uri_at_dest (EvApplication *application, const char *uri, GdkScreen *screen, EvLinkDest *dest, EvWindowRunMode mode, const gchar *search_string, guint32 timestamp)
void ev_application_open_uri_list (EvApplication *application, GSList *uri_list, GdkScreen *screen, guint32 timestamp)
gboolean ev_application_has_window (EvApplication *application)
guint ev_application_get_n_windows (EvApplication *application)
const gchar * ev_application_get_uri (EvApplication *application)
GObject * ev_application_get_media_keys (EvApplication *application)
const gchar * ev_application_get_dot_dir (EvApplication *application, gboolean create)
Macro Definition Documentation
EV_APP
#define EV_APP ((EvApplication *) g_application_get_default ())
Definition at line 47 of file ev-application.h.
EV_APPLICATION
#define EV_APPLICATION (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_APPLICATION, EvApplication))
Definition at line 41 of file ev-application.h.
EV_APPLICATION_CLASS
#define EV_APPLICATION_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_APPLICATION, EvApplicationClass))
Definition at line 42 of file ev-application.h.
EV_APPLICATION_GET_CLASS
#define EV_APPLICATION_GET_CLASS (object)
Value:
(G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_APPLICATION, EvApplicationClass))
Definition at line 45 of file ev-application.h.
EV_IS_APPLICATION
#define EV_IS_APPLICATION (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_APPLICATION))
Definition at line 43 of file ev-application.h.
EV_IS_APPLICATION_CLASS
#define EV_IS_APPLICATION_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_APPLICATION))
Definition at line 44 of file ev-application.h.
EV_TYPE_APPLICATION
#define EV_TYPE_APPLICATION (ev_application_get_type ())
Definition at line 40 of file ev-application.h.
Referenced by ev_application_new().
Typedef Documentation
EvApplication
typedef struct _EvApplication EvApplication
Definition at line 37 of file ev-application.h.
EvApplicationClass
typedef struct _EvApplicationClass EvApplicationClass
Definition at line 38 of file ev-application.h.
Function Documentation
ev_application_get_dot_dir()
const gchar * ev_application_get_dot_dir (EvApplication * application, gboolean create)
Definition at line 1065 of file ev-application.c.
ev_application_get_media_keys()
GObject * ev_application_get_media_keys (EvApplication * application)
ev_application_get_media_keys: @application: The instance of the application.
It gives you access to the media player keys handler object.
Returns: A EvMediaPlayerKeys.
Definition at line 1055 of file ev-application.c.
References NULL.
ev_application_get_n_windows()
guint ev_application_get_n_windows (EvApplication * application)
Definition at line 1024 of file ev-application.c.
References EV_IS_WINDOW, and NULL.
ev_application_get_type()
GType ev_application_get_type (void)
ev_application_get_uri()
const gchar * ev_application_get_uri (EvApplication * application)
Definition at line 1041 of file ev-application.c.
ev_application_has_window()
gboolean ev_application_has_window (EvApplication * application)
Definition at line 1008 of file ev-application.c.
References EV_IS_WINDOW, FALSE, NULL, and TRUE.
ev_application_load_session()
gboolean ev_application_load_session (EvApplication * application)
Definition at line 114 of file ev-application.c.
References egg_sm_client_get_state_file(), egg_sm_client_is_resumed(), ev_application_open_uri_at_dest(), FALSE, NULL, and TRUE.
Referenced by main().
ev_application_new()
EvApplication * ev_application_new (void)
ev_application_new:
Creates a new EvApplication instance.
Returns: (transfer full): a newly created EvApplication
Definition at line 102 of file ev-application.c.
References EV_TYPE_APPLICATION, and NULL.
Referenced by main().
ev_application_open_uri_at_dest()
void ev_application_open_uri_at_dest (EvApplication * application, const char * uri, GdkScreen * screen, EvLinkDest * dest, EvWindowRunMode mode, const gchar * search_string, guint32 timestamp)
References dest.
ev_application_open_uri_list()
void ev_application_open_uri_list (EvApplication * application, GSList * uri_list, GdkScreen * screen, guint32 timestamp)
ev_application_open_window()
void ev_application_open_window (EvApplication * application, GdkScreen * screen, guint32 timestamp)
ev_application_open_window: @application: The instance of the application. @timestamp: Current time value.
Creates a new window
Definition at line 691 of file ev-application.c.
References ev_stock_icons_set_screen(), and ev_window_new().