MATE Desktop Environment: ev-backends-manager.h File Reference
ev-backends-manager.h File Reference
#include <glib.h>
#include "ev-document.h"
#include "ev-macros.h"
Classes
struct _EvTypeInfo
Typedefs
typedef struct _EvTypeInfo EvTypeInfo
Functions
gboolean _ev_backends_manager_init (void)
void _ev_backends_manager_shutdown (void)
EvDocument * ev_backends_manager_get_document (const gchar *mime_type)
EV_DEPRECATED const gchar * ev_backends_manager_get_document_module_name (EvDocument *document)
EV_DEPRECATED EvTypeInfo * ev_backends_manager_get_document_type_info (EvDocument *document)
GList * ev_backends_manager_get_all_types_info (void)
const gchar * ev_backends_manager_get_backends_dir (void)
Typedef Documentation
EvTypeInfo
typedef struct _EvTypeInfo EvTypeInfo
Function Documentation
_ev_backends_manager_init()
gboolean _ev_backends_manager_init (void)
Definition at line 176 of file ev-backends-manager.c.
References TRUE.
Referenced by ev_init().
_ev_backends_manager_shutdown()
void _ev_backends_manager_shutdown (void)
Definition at line 190 of file ev-backends-manager.c.
References NULL.
Referenced by ev_shutdown().
ev_backends_manager_get_all_types_info()
GList * ev_backends_manager_get_all_types_info (void)
Definition at line 313 of file ev-backends-manager.c.
References NULL.
Referenced by ev_document_factory_add_filters().
ev_backends_manager_get_backends_dir()
const gchar * ev_backends_manager_get_backends_dir (void)
Definition at line 58 of file ev-backends-manager.c.
ev_backends_manager_get_document()
EvDocument * ev_backends_manager_get_document (const gchar * mime_type)
Definition at line 221 of file ev-backends-manager.c.
References EV_DOCUMENT, EV_MODULE, ev_module_get_path(), ev_module_new(), ev_module_new_object(), mime_type, and NULL.
ev_backends_manager_get_document_module_name()
EV_DEPRECATED const gchar * ev_backends_manager_get_document_module_name (EvDocument * document)
Definition at line 279 of file ev-backends-manager.c.
References NULL.
ev_backends_manager_get_document_type_info()
EV_DEPRECATED EvTypeInfo * ev_backends_manager_get_document_type_info (EvDocument * document)
Definition at line 301 of file ev-backends-manager.c.
References NULL.
Referenced by ev_document_factory_add_filters().