MATE Desktop Environment: ev-backends-manager.c File Reference
ev-backends-manager.c File Reference
#include <config.h>
#include <glib/gstdio.h>
#include <gmodule.h>
#include "ev-module.h"
#include "ev-backends-manager.h"
Macros
#define EV_BACKENDS_GROUP "Atril Backend"
#define EV_BACKENDS_EXTENSION ".atril-backend"
Typedefs
typedef struct _EvBackendInfo EvBackendInfo
Functions
const gchar * ev_backends_manager_get_backends_dir (void)
gboolean _ev_backends_manager_init (void)
void _ev_backends_manager_shutdown (void)
EvDocument * ev_backends_manager_get_document (const gchar *mime_type)
const gchar * ev_backends_manager_get_document_module_name (EvDocument *document)
EvTypeInfo * ev_backends_manager_get_document_type_info (EvDocument *document)
GList * ev_backends_manager_get_all_types_info (void)
Macro Definition Documentation
EV_BACKENDS_EXTENSION
#define EV_BACKENDS_EXTENSION ".atril-backend"
Definition at line 43 of file ev-backends-manager.c.
EV_BACKENDS_GROUP
#define EV_BACKENDS_GROUP "Atril Backend"
Definition at line 42 of file ev-backends-manager.c.
Typedef Documentation
EvBackendInfo
typedef struct _EvBackendInfo EvBackendInfo
Definition at line 30 of file ev-backends-manager.c.
Function Documentation
_ev_backends_manager_init()
gboolean _ev_backends_manager_init (void)
Definition at line 176 of file ev-backends-manager.c.
References TRUE.
Referenced by ev_init().
_ev_backends_manager_shutdown()
void _ev_backends_manager_shutdown (void)
Definition at line 190 of file ev-backends-manager.c.
References NULL.
Referenced by ev_shutdown().
ev_backends_manager_get_all_types_info()
GList * ev_backends_manager_get_all_types_info (void)
Definition at line 313 of file ev-backends-manager.c.
References NULL.
Referenced by ev_document_factory_add_filters().
ev_backends_manager_get_backends_dir()
const gchar * ev_backends_manager_get_backends_dir (void)
Definition at line 58 of file ev-backends-manager.c.
ev_backends_manager_get_document()
EvDocument * ev_backends_manager_get_document (const gchar * mime_type)
Definition at line 221 of file ev-backends-manager.c.
References EV_DOCUMENT, EV_MODULE, ev_module_get_path(), ev_module_new(), ev_module_new_object(), mime_type, and NULL.
ev_backends_manager_get_document_module_name()
const gchar * ev_backends_manager_get_document_module_name (EvDocument * document)
Definition at line 279 of file ev-backends-manager.c.
References NULL.
ev_backends_manager_get_document_type_info()
EvTypeInfo * ev_backends_manager_get_document_type_info (EvDocument * document)
Definition at line 301 of file ev-backends-manager.c.
References NULL.
Referenced by ev_document_factory_add_filters().