MATE Desktop Environment: ev-document-info.h File Reference
ev-document-info.h File Reference
#include <glib-object.h>
#include <glib.h>
Classes
struct _EvDocumentInfo
struct _EvDocumentLicense
Macros
#define EV_TYPE_DOCUMENT_INFO (ev_document_info_get_type())
#define PERMISSIONS_FULL
#define EV_TYPE_DOCUMENT_LICENSE (ev_document_license_get_type())
Typedefs
typedef struct _EvDocumentInfo EvDocumentInfo
typedef struct _EvDocumentLicense EvDocumentLicense
Enumerations
enum EvDocumentLayout {
EV_DOCUMENT_LAYOUT_SINGLE_PAGE , EV_DOCUMENT_LAYOUT_ONE_COLUMN , EV_DOCUMENT_LAYOUT_TWO_COLUMN_LEFT , EV_DOCUMENT_LAYOUT_TWO_COLUMN_RIGHT ,
EV_DOCUMENT_LAYOUT_TWO_PAGE_LEFT , EV_DOCUMENT_LAYOUT_TWO_PAGE_RIGHT
}
enum EvDocumentMode {
EV_DOCUMENT_MODE_NONE , EV_DOCUMENT_MODE_USE_OC , EV_DOCUMENT_MODE_USE_THUMBS , EV_DOCUMENT_MODE_FULL_SCREEN ,
EV_DOCUMENT_MODE_USE_ATTACHMENTS , EV_DOCUMENT_MODE_PRESENTATION = EV_DOCUMENT_MODE_FULL_SCREEN
}
enum EvDocumentUIHints {
EV_DOCUMENT_UI_HINT_HIDE_TOOLBAR = 1 << 0 , EV_DOCUMENT_UI_HINT_HIDE_MENUBAR = 1 << 1 , EV_DOCUMENT_UI_HINT_HIDE_WINDOWUI = 1 << 2 , EV_DOCUMENT_UI_HINT_FIT_WINDOW = 1 << 3 ,
EV_DOCUMENT_UI_HINT_CENTER_WINDOW = 1 << 4 , EV_DOCUMENT_UI_HINT_DISPLAY_DOC_TITLE = 1 << 5 , EV_DOCUMENT_UI_HINT_DIRECTION_RTL = 1 << 6
}
enum EvDocumentPermissions {
EV_DOCUMENT_PERMISSIONS_OK_TO_PRINT = 1 << 0 , EV_DOCUMENT_PERMISSIONS_OK_TO_MODIFY = 1 << 1 , EV_DOCUMENT_PERMISSIONS_OK_TO_COPY = 1 << 2 , EV_DOCUMENT_PERMISSIONS_OK_TO_ADD_NOTES = 1 << 3 ,
EV_DOCUMENT_PERMISSIONS_FULL = PERMISSIONS_FULL
}
enum EvDocumentInfoFields {
EV_DOCUMENT_INFO_TITLE = 1 << 0 , EV_DOCUMENT_INFO_FORMAT = 1 << 1 , EV_DOCUMENT_INFO_AUTHOR = 1 << 2 , EV_DOCUMENT_INFO_SUBJECT = 1 << 3 ,
EV_DOCUMENT_INFO_KEYWORDS = 1 << 4 , EV_DOCUMENT_INFO_LAYOUT = 1 << 5 , EV_DOCUMENT_INFO_CREATOR = 1 << 6 , EV_DOCUMENT_INFO_PRODUCER = 1 << 7 ,
EV_DOCUMENT_INFO_CREATION_DATE = 1 << 8 , EV_DOCUMENT_INFO_MOD_DATE = 1 << 9 , EV_DOCUMENT_INFO_LINEARIZED = 1 << 10 , EV_DOCUMENT_INFO_START_MODE = 1 << 11 ,
EV_DOCUMENT_INFO_UI_HINTS = 1 << 12 , EV_DOCUMENT_INFO_PERMISSIONS = 1 << 13 , EV_DOCUMENT_INFO_N_PAGES = 1 << 14 , EV_DOCUMENT_INFO_SECURITY = 1 << 15 ,
EV_DOCUMENT_INFO_PAPER_SIZE = 1 << 16 , EV_DOCUMENT_INFO_LICENSE = 1 << 17
}
Functions
GType ev_document_info_get_type (void)
EvDocumentInfo * ev_document_info_copy (EvDocumentInfo *info)
void ev_document_info_free (EvDocumentInfo *info)
GType ev_document_license_get_type (void)
EvDocumentLicense * ev_document_license_new (void)
EvDocumentLicense * ev_document_license_copy (EvDocumentLicense *license)
void ev_document_license_free (EvDocumentLicense *license)
const gchar * ev_document_license_get_text (EvDocumentLicense *license)
const gchar * ev_document_license_get_uri (EvDocumentLicense *license)
const gchar * ev_document_license_get_web_statement (EvDocumentLicense *license)
Macro Definition Documentation
EV_TYPE_DOCUMENT_INFO
#define EV_TYPE_DOCUMENT_INFO (ev_document_info_get_type())
Definition at line 36 of file ev-document-info.h.
EV_TYPE_DOCUMENT_LICENSE
#define EV_TYPE_DOCUMENT_LICENSE (ev_document_license_get_type())
Definition at line 138 of file ev-document-info.h.
PERMISSIONS_FULL
#define PERMISSIONS_FULL
Value:
(EV_DOCUMENT_PERMISSIONS_OK_TO_PRINT  \
| EV_DOCUMENT_PERMISSIONS_OK_TO_MODIFY \
| EV_DOCUMENT_PERMISSIONS_OK_TO_COPY   \
| EV_DOCUMENT_PERMISSIONS_OK_TO_ADD_NOTES)
Definition at line 70 of file ev-document-info.h.
Typedef Documentation
EvDocumentInfo
typedef struct _EvDocumentInfo EvDocumentInfo
Definition at line 33 of file ev-document-info.h.
EvDocumentLicense
typedef struct _EvDocumentLicense EvDocumentLicense
Definition at line 34 of file ev-document-info.h.
Enumeration Type Documentation
EvDocumentInfoFields
enum EvDocumentInfoFields
Enumerator
EV_DOCUMENT_INFO_TITLE
EV_DOCUMENT_INFO_FORMAT
EV_DOCUMENT_INFO_AUTHOR
EV_DOCUMENT_INFO_SUBJECT
EV_DOCUMENT_INFO_KEYWORDS
EV_DOCUMENT_INFO_LAYOUT
EV_DOCUMENT_INFO_CREATOR
EV_DOCUMENT_INFO_PRODUCER
EV_DOCUMENT_INFO_CREATION_DATE
EV_DOCUMENT_INFO_MOD_DATE
EV_DOCUMENT_INFO_LINEARIZED
EV_DOCUMENT_INFO_START_MODE
EV_DOCUMENT_INFO_UI_HINTS
EV_DOCUMENT_INFO_PERMISSIONS
EV_DOCUMENT_INFO_N_PAGES
EV_DOCUMENT_INFO_SECURITY
EV_DOCUMENT_INFO_PAPER_SIZE
EV_DOCUMENT_INFO_LICENSE
Definition at line 84 of file ev-document-info.h.
EvDocumentLayout
enum EvDocumentLayout
Enumerator
EV_DOCUMENT_LAYOUT_SINGLE_PAGE
EV_DOCUMENT_LAYOUT_ONE_COLUMN
EV_DOCUMENT_LAYOUT_TWO_COLUMN_LEFT
EV_DOCUMENT_LAYOUT_TWO_COLUMN_RIGHT
EV_DOCUMENT_LAYOUT_TWO_PAGE_LEFT
EV_DOCUMENT_LAYOUT_TWO_PAGE_RIGHT
Definition at line 38 of file ev-document-info.h.
EvDocumentMode
enum EvDocumentMode
Enumerator
EV_DOCUMENT_MODE_NONE
EV_DOCUMENT_MODE_USE_OC
EV_DOCUMENT_MODE_USE_THUMBS
EV_DOCUMENT_MODE_FULL_SCREEN
EV_DOCUMENT_MODE_USE_ATTACHMENTS
EV_DOCUMENT_MODE_PRESENTATION
Definition at line 48 of file ev-document-info.h.
EvDocumentPermissions
enum EvDocumentPermissions
Enumerator
EV_DOCUMENT_PERMISSIONS_OK_TO_PRINT
EV_DOCUMENT_PERMISSIONS_OK_TO_MODIFY
EV_DOCUMENT_PERMISSIONS_OK_TO_COPY
EV_DOCUMENT_PERMISSIONS_OK_TO_ADD_NOTES
EV_DOCUMENT_PERMISSIONS_FULL
Definition at line 75 of file ev-document-info.h.
EvDocumentUIHints
enum EvDocumentUIHints
Enumerator
EV_DOCUMENT_UI_HINT_HIDE_TOOLBAR
EV_DOCUMENT_UI_HINT_HIDE_MENUBAR
EV_DOCUMENT_UI_HINT_HIDE_WINDOWUI
EV_DOCUMENT_UI_HINT_FIT_WINDOW
EV_DOCUMENT_UI_HINT_CENTER_WINDOW
EV_DOCUMENT_UI_HINT_DISPLAY_DOC_TITLE
EV_DOCUMENT_UI_HINT_DIRECTION_RTL
Definition at line 58 of file ev-document-info.h.
Function Documentation
ev_document_info_copy()
EvDocumentInfo * ev_document_info_copy (EvDocumentInfo * info)
Definition at line 787 of file ev-document.c.
References _EvDocumentInfo::author, _EvDocumentInfo::creation_date, _EvDocumentInfo::creator, ev_document_license_copy(), _EvDocumentInfo::fields_mask, _EvDocumentInfo::format, _EvDocumentInfo::keywords, _EvDocumentInfo::layout, _EvDocumentInfo::license, _EvDocumentInfo::linearized, _EvDocumentInfo::mode, _EvDocumentInfo::modified_date, _EvDocumentInfo::n_pages, NULL, _EvDocumentInfo::permissions, _EvDocumentInfo::producer, _EvDocumentInfo::security, _EvDocumentInfo::subject, _EvDocumentInfo::title, and _EvDocumentInfo::ui_hints.
ev_document_info_free()
void ev_document_info_free (EvDocumentInfo * info)
Definition at line 819 of file ev-document.c.
References ev_document_license_free(), and NULL.
ev_document_info_get_type()
GType ev_document_info_get_type (void)
ev_document_license_copy()
EvDocumentLicense * ev_document_license_copy (EvDocumentLicense * license)
Definition at line 849 of file ev-document.c.
References ev_document_license_new(), NULL, _EvDocumentLicense::text, _EvDocumentLicense::uri, and _EvDocumentLicense::web_statement.
Referenced by ev_document_info_copy().
ev_document_license_free()
void ev_document_license_free (EvDocumentLicense * license)
Definition at line 869 of file ev-document.c.
References _EvDocumentLicense::text, _EvDocumentLicense::uri, and _EvDocumentLicense::web_statement.
Referenced by ev_document_info_free().
ev_document_license_get_text()
const gchar * ev_document_license_get_text (EvDocumentLicense * license)
Definition at line 882 of file ev-document.c.
References _EvDocumentLicense::text.
Referenced by ev_properties_license_set_license().
ev_document_license_get_type()
GType ev_document_license_get_type (void)
ev_document_license_get_uri()
const gchar * ev_document_license_get_uri (EvDocumentLicense * license)
Definition at line 888 of file ev-document.c.
References _EvDocumentLicense::uri.
Referenced by ev_properties_license_set_license().
ev_document_license_get_web_statement()
const gchar * ev_document_license_get_web_statement (EvDocumentLicense * license)
Definition at line 894 of file ev-document.c.
References _EvDocumentLicense::web_statement.
Referenced by ev_properties_license_set_license().
ev_document_license_new()
EvDocumentLicense * ev_document_license_new (void)
Definition at line 843 of file ev-document.c.
Referenced by ev_document_license_copy().