MATE Desktop Environment: ev-document-layers.c File Reference
ev-document-layers.c File Reference
#include "config.h"
#include "ev-document-layers.h"
#include "ev-document.h"
Functions
gboolean ev_document_layers_has_layers (EvDocumentLayers *document_layers)
GtkTreeModel * ev_document_layers_get_layers (EvDocumentLayers *document_layers)
void ev_document_layers_show_layer (EvDocumentLayers *document_layers, EvLayer *layer)
void ev_document_layers_hide_layer (EvDocumentLayers *document_layers, EvLayer *layer)
gboolean ev_document_layers_layer_is_visible (EvDocumentLayers *document_layers, EvLayer *layer)
Function Documentation
ev_document_layers_get_layers()
GtkTreeModel * ev_document_layers_get_layers (EvDocumentLayers * document_layers)
ev_document_layers_get_layers: @document_layers: an EvDocumentLayers
Returns: (transfer full): a #GtkTreeModel
Definition at line 48 of file ev-document-layers.c.
References EV_DOCUMENT_LAYERS_GET_IFACE, and _EvDocumentLayersInterface::get_layers.
ev_document_layers_has_layers()
gboolean ev_document_layers_has_layers (EvDocumentLayers * document_layers)
Definition at line 34 of file ev-document-layers.c.
References EV_DOCUMENT_LAYERS_GET_IFACE, and _EvDocumentLayersInterface::has_layers.
ev_document_layers_hide_layer()
void ev_document_layers_hide_layer (EvDocumentLayers * document_layers, EvLayer * layer)
Definition at line 65 of file ev-document-layers.c.
References EV_DOCUMENT_LAYERS_GET_IFACE, and _EvDocumentLayersInterface::hide_layer.
Referenced by ev_view_handle_link().
ev_document_layers_layer_is_visible()
gboolean ev_document_layers_layer_is_visible (EvDocumentLayers * document_layers, EvLayer * layer)
Definition at line 74 of file ev-document-layers.c.
References EV_DOCUMENT_LAYERS_GET_IFACE, and _EvDocumentLayersInterface::layer_is_visible.
Referenced by ev_view_handle_link().
ev_document_layers_show_layer()
void ev_document_layers_show_layer (EvDocumentLayers * document_layers, EvLayer * layer)
Definition at line 56 of file ev-document-layers.c.
References EV_DOCUMENT_LAYERS_GET_IFACE, and _EvDocumentLayersInterface::show_layer.
Referenced by ev_view_handle_link().