MATE Desktop Environment: ev-document.h File Reference
ev-document.h File Reference
#include <glib-object.h>
#include <glib.h>
#include <gmodule.h>
#include <cairo.h>
#include "ev-document-info.h"
#include "ev-page.h"
#include "ev-render-context.h"
Classes
struct EvPoint
struct _EvDocumentBackendInfo
struct _EvDocument
struct _EvDocumentClass
struct _EvRectangle
struct _EvMapping
struct _EvSourceLink
Macros
#define EV_TYPE_DOCUMENT (ev_document_get_type ())
#define EV_DOCUMENT(o)
#define EV_DOCUMENT_CLASS(k)
#define EV_IS_DOCUMENT(o)
#define EV_IS_DOCUMENT_CLASS(k)
#define EV_DOCUMENT_GET_CLASS(inst)
#define EV_DOCUMENT_ERROR ev_document_error_quark ()
#define EV_DOC_MUTEX_LOCK (ev_document_doc_mutex_lock ())
#define EV_DOC_MUTEX_UNLOCK (ev_document_doc_mutex_unlock ())
#define EV_TYPE_RECTANGLE (ev_rectangle_get_type ())
#define EV_TYPE_SOURCE_LINK (ev_source_link_get_type ())
#define EV_BACKEND_IMPLEMENT_INTERFACE(TYPE_IFACE, iface_init)
#define EV_BACKEND_REGISTER_WITH_CODE(BackendName, backend_name, CODE)
#define EV_BACKEND_REGISTER(BackendName, backend_name)
Typedefs
typedef struct _EvDocument EvDocument
typedef struct _EvDocumentClass EvDocumentClass
typedef struct _EvDocumentPrivate EvDocumentPrivate
typedef struct _EvRectangle EvRectangle
typedef struct _EvMapping EvMapping
typedef struct _EvSourceLink EvSourceLink
typedef struct _EvDocumentBackendInfo EvDocumentBackendInfo
Enumerations
enum EvDocumentError { EV_DOCUMENT_ERROR_INVALID , EV_DOCUMENT_ERROR_UNSUPPORTED_CONTENT , EV_DOCUMENT_ERROR_ENCRYPTED }
Functions
GType ev_document_get_type (void)
GQuark ev_document_error_quark (void)
GMutex * ev_document_get_doc_mutex (void)
void ev_document_doc_mutex_lock (void)
void ev_document_doc_mutex_unlock (void)
gboolean ev_document_doc_mutex_trylock (void)
GMutex * ev_document_get_fc_mutex (void)
void ev_document_fc_mutex_lock (void)
void ev_document_fc_mutex_unlock (void)
gboolean ev_document_fc_mutex_trylock (void)
EvDocumentInfo * ev_document_get_info (EvDocument *document)
gboolean ev_document_get_backend_info (EvDocument *document, EvDocumentBackendInfo *info)
gboolean ev_document_load (EvDocument *document, const char *uri, GError **error)
gboolean ev_document_save (EvDocument *document, const char *uri, GError **error)
gint ev_document_get_n_pages (EvDocument *document)
EvPage * ev_document_get_page (EvDocument *document, gint index)
void ev_document_get_page_size (EvDocument *document, gint page_index, double *width, double *height)
gchar * ev_document_get_page_label (EvDocument *document, gint page_index)
cairo_surface_t * ev_document_render (EvDocument *document, EvRenderContext *rc)
const gchar * ev_document_get_uri (EvDocument *document)
const gchar * ev_document_get_title (EvDocument *document)
gboolean ev_document_is_page_size_uniform (EvDocument *document)
void ev_document_get_max_page_size (EvDocument *document, gdouble *width, gdouble *height)
void ev_document_get_min_page_size (EvDocument *document, gdouble *width, gdouble *height)
gboolean ev_document_check_dimensions (EvDocument *document)
gint ev_document_get_max_label_len (EvDocument *document)
gboolean ev_document_has_text_page_labels (EvDocument *document)
gboolean ev_document_find_page_by_label (EvDocument *document, const gchar *page_label, gint *page_index)
gboolean ev_document_has_synctex (EvDocument *document)
EvSourceLink * ev_document_synctex_backward_search (EvDocument *document, gint page_index, gfloat x, gfloat y)
EvMapping * ev_document_synctex_forward_search (EvDocument *document, EvSourceLink *source_link)
gint ev_rect_cmp (EvRectangle *a, EvRectangle *b)
void ev_document_toggle_night_mode (EvDocument *document, gboolean night)
void ev_document_check_add_night_sheet (EvDocument *document)
GType ev_rectangle_get_type (void)
EvRectangle * ev_rectangle_new (void)
EvRectangle * ev_rectangle_copy (EvRectangle *ev_rect)
void ev_rectangle_free (EvRectangle *ev_rect)
GType ev_source_link_get_type (void)
EvSourceLink * ev_source_link_new (const gchar *filename, gint line, gint col)
EvSourceLink * ev_source_link_copy (EvSourceLink *link)
void ev_source_link_free (EvSourceLink *link)
Macro Definition Documentation
EV_BACKEND_IMPLEMENT_INTERFACE
#define EV_BACKEND_IMPLEMENT_INTERFACE (TYPE_IFACE, iface_init)
Value:
    {                \
    const GInterfaceInfo g_implement_interface_info = {                     \
        (GInterfaceInitFunc) iface_init, NULL, NULL                     \
    };                                                                      \
    g_type_module_add_interface (module,                                    \
                     g_define_type_id,                          \
                     TYPE_IFACE,                                \
                     &g_implement_interface_info);              \
}
Definition at line 232 of file ev-document.h.
Referenced by EV_BACKEND_REGISTER_WITH_CODE(), EV_BACKEND_REGISTER_WITH_CODE(), EV_BACKEND_REGISTER_WITH_CODE(), EV_BACKEND_REGISTER_WITH_CODE(), EV_BACKEND_REGISTER_WITH_CODE(), EV_BACKEND_REGISTER_WITH_CODE(), EV_BACKEND_REGISTER_WITH_CODE(), and EV_BACKEND_REGISTER_WITH_CODE().
EV_BACKEND_REGISTER
#define EV_BACKEND_REGISTER (BackendName, backend_name)
Value:
EV_BACKEND_REGISTER_WITH_CODE(BackendName, backend_name, ;)
Definition at line 297 of file ev-document.h.
EV_BACKEND_REGISTER_WITH_CODE
#define EV_BACKEND_REGISTER_WITH_CODE (BackendName, backend_name, CODE)
Definition at line 247 of file ev-document.h.
EV_DOC_MUTEX_LOCK
#define EV_DOC_MUTEX_LOCK (ev_document_doc_mutex_lock ())
Definition at line 53 of file ev-document.h.
EV_DOC_MUTEX_UNLOCK
#define EV_DOC_MUTEX_UNLOCK (ev_document_doc_mutex_unlock ())
Definition at line 54 of file ev-document.h.
EV_DOCUMENT
#define EV_DOCUMENT (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), EV_TYPE_DOCUMENT, EvDocument))
Definition at line 42 of file ev-document.h.
Referenced by ev_backends_manager_get_document(), ev_document_links_get_dest_page(), and ev_document_links_get_dest_page_label().
EV_DOCUMENT_CLASS
#define EV_DOCUMENT_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST((k), EV_TYPE_DOCUMENT, EvDocumentClass))
Definition at line 43 of file ev-document.h.
EV_DOCUMENT_ERROR
#define EV_DOCUMENT_ERROR ev_document_error_quark ()
Definition at line 52 of file ev-document.h.
Referenced by ev_document_factory_get_document(), and ev_document_load().
EV_DOCUMENT_GET_CLASS
#define EV_DOCUMENT_GET_CLASS (inst)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((inst), EV_TYPE_DOCUMENT, EvDocumentClass))
Definition at line 46 of file ev-document.h.
Referenced by ev_document_check_add_night_sheet(), ev_document_get_backend_info(), ev_document_get_page(), ev_document_load(), ev_document_render(), ev_document_save(), and ev_document_toggle_night_mode().
EV_IS_DOCUMENT
#define EV_IS_DOCUMENT (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), EV_TYPE_DOCUMENT))
Definition at line 44 of file ev-document.h.
Referenced by ev_document_check_dimensions(), ev_document_factory_add_filters(), ev_document_find_page_by_label(), ev_document_get_backend_info(), ev_document_get_info(), ev_document_get_max_label_len(), ev_document_get_max_page_size(), ev_document_get_min_page_size(), ev_document_get_n_pages(), ev_document_get_page_label(), ev_document_get_page_size(), ev_document_get_title(), ev_document_get_uri(), ev_document_has_text_page_labels(), ev_document_is_page_size_uniform(), ev_document_model_new_with_document(), ev_document_model_set_document(), ev_page_cache_new(), ev_sidebar_page_support_document(), ev_view_presentation_new(), and ev_view_set_caret_cursor_position().
EV_IS_DOCUMENT_CLASS
#define EV_IS_DOCUMENT_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), EV_TYPE_DOCUMENT))
Definition at line 45 of file ev-document.h.
EV_TYPE_DOCUMENT
#define EV_TYPE_DOCUMENT (ev_document_get_type ())
Definition at line 41 of file ev-document.h.
EV_TYPE_RECTANGLE
#define EV_TYPE_RECTANGLE (ev_rectangle_get_type ())
Definition at line 190 of file ev-document.h.
EV_TYPE_SOURCE_LINK
#define EV_TYPE_SOURCE_LINK (ev_source_link_get_type ())
Definition at line 209 of file ev-document.h.
Typedef Documentation
EvDocument
typedef struct _EvDocument EvDocument
Definition at line 48 of file ev-document.h.
EvDocumentBackendInfo
typedef struct _EvDocumentBackendInfo EvDocumentBackendInfo
Definition at line 71 of file ev-document.h.
EvDocumentClass
typedef struct _EvDocumentClass EvDocumentClass
Definition at line 49 of file ev-document.h.
EvDocumentPrivate
typedef struct _EvDocumentPrivate EvDocumentPrivate
Definition at line 50 of file ev-document.h.
EvMapping
typedef struct _EvMapping EvMapping
Definition at line 69 of file ev-document.h.
EvRectangle
typedef struct _EvRectangle EvRectangle
Definition at line 68 of file ev-document.h.
EvSourceLink
typedef struct _EvSourceLink EvSourceLink
Definition at line 70 of file ev-document.h.
Enumeration Type Documentation
EvDocumentError
enum EvDocumentError
Enumerator
EV_DOCUMENT_ERROR_INVALID
EV_DOCUMENT_ERROR_UNSUPPORTED_CONTENT
EV_DOCUMENT_ERROR_ENCRYPTED
Definition at line 56 of file ev-document.h.
Function Documentation
ev_document_check_add_night_sheet()
void ev_document_check_add_night_sheet (EvDocument * document)
Definition at line 953 of file ev-document.c.
References _EvDocumentClass::check_add_night_sheet, and EV_DOCUMENT_GET_CLASS.
ev_document_check_dimensions()
gboolean ev_document_check_dimensions (EvDocument * document)
Definition at line 669 of file ev-document.c.
References EV_IS_DOCUMENT, FALSE, and _EvDocument::priv.
ev_document_doc_mutex_lock()
void ev_document_doc_mutex_lock (void)
Definition at line 167 of file ev-document.c.
Referenced by ev_document_links_find_link_dest(), ev_document_links_find_link_page(), ev_pixbuf_cache_get_selection_region(), ev_pixbuf_cache_get_selection_surface(), and ev_view_remove_annotation().
ev_document_doc_mutex_trylock()
gboolean ev_document_doc_mutex_trylock (void)
Definition at line 179 of file ev-document.c.
ev_document_doc_mutex_unlock()
void ev_document_doc_mutex_unlock (void)
Definition at line 173 of file ev-document.c.
Referenced by ev_document_links_find_link_dest(), ev_document_links_find_link_page(), ev_pixbuf_cache_get_selection_region(), ev_pixbuf_cache_get_selection_surface(), and ev_view_remove_annotation().
ev_document_error_quark()
GQuark ev_document_error_quark (void)
Definition at line 81 of file ev-document.c.
ev_document_fc_mutex_lock()
void ev_document_fc_mutex_lock (void)
Definition at line 185 of file ev-document.c.
ev_document_fc_mutex_trylock()
gboolean ev_document_fc_mutex_trylock (void)
Definition at line 197 of file ev-document.c.
ev_document_fc_mutex_unlock()
void ev_document_fc_mutex_unlock (void)
Definition at line 191 of file ev-document.c.
ev_document_find_page_by_label()
gboolean ev_document_find_page_by_label (EvDocument * document, const gchar * page_label, gint * page_index)
Definition at line 693 of file ev-document.c.
References EV_IS_DOCUMENT, FALSE, MIN, NULL, _EvDocument::priv, and TRUE.
Referenced by ev_document_links_get_dest_page(), and ev_document_model_set_page_by_label().
ev_document_get_backend_info()
gboolean ev_document_get_backend_info (EvDocument * document, EvDocumentBackendInfo * info)
Definition at line 597 of file ev-document.c.
References EV_DOCUMENT_GET_CLASS, EV_IS_DOCUMENT, FALSE, _EvDocumentClass::get_backend_info, and NULL.
ev_document_get_doc_mutex()
GMutex * ev_document_get_doc_mutex (void)
ev_document_get_fc_mutex()
GMutex * ev_document_get_fc_mutex (void)
References error.
ev_document_get_info()
EvDocumentInfo * ev_document_get_info (EvDocument * document)
Definition at line 589 of file ev-document.c.
References EV_IS_DOCUMENT, NULL, and _EvDocument::priv.
Referenced by ev_properties_dialog_set_document().
ev_document_get_max_label_len()
gint ev_document_get_max_label_len (EvDocument * document)
Definition at line 677 of file ev-document.c.
References EV_IS_DOCUMENT, and _EvDocument::priv.
ev_document_get_max_page_size()
void ev_document_get_max_page_size (EvDocument * document, gdouble * width, gdouble * height)
Definition at line 643 of file ev-document.c.
References EV_IS_DOCUMENT, and _EvDocument::priv.
ev_document_get_min_page_size()
void ev_document_get_min_page_size (EvDocument * document, gdouble * width, gdouble * height)
Definition at line 656 of file ev-document.c.
References EV_IS_DOCUMENT, and _EvDocument::priv.
ev_document_get_n_pages()
gint ev_document_get_n_pages (EvDocument * document)
Definition at line 515 of file ev-document.c.
References EV_IS_DOCUMENT, and _EvDocument::priv.
Referenced by ev_document_model_set_document(), ev_page_cache_new(), ev_pixbuf_cache_get_selection_list(), ev_pixbuf_cache_set_page_range(), ev_pixbuf_cache_set_selection_list(), ev_view_get_page_extents(), ev_view_presentation_new(), ev_view_presentation_next_page(), ev_view_scroll(), ev_view_select_all(), ev_view_set_caret_cursor_position(), ev_window_print_range(), G_DEFINE_TYPE_EXTENDED(), and G_DEFINE_TYPE_WITH_CODE().
ev_document_get_page()
EvPage * ev_document_get_page (EvDocument * document, gint index)
Definition at line 383 of file ev-document.c.
References EV_DOCUMENT_GET_CLASS, and _EvDocumentClass::get_page.
Referenced by ev_document_load(), ev_pixbuf_cache_get_selection_region(), ev_pixbuf_cache_get_selection_surface(), and G_DEFINE_TYPE_EXTENDED().
ev_document_get_page_label()
gchar * ev_document_get_page_label (EvDocument * document, gint page_index)
Definition at line 569 of file ev-document.c.
References EV_IS_DOCUMENT, NULL, and _EvDocument::priv.
Referenced by ev_document_links_get_dest_page_label().
ev_document_get_page_size()
void ev_document_get_page_size (EvDocument * document, gint page_index, double * width, double * height)
Definition at line 534 of file ev-document.c.
References EV_IS_DOCUMENT, _EvDocument::iswebdocument, _EvDocument::priv, and TRUE.
Referenced by _get_page_size_for_scale_and_rotation(), G_DEFINE_TYPE_EXTENDED(), and G_DEFINE_TYPE_WITH_CODE().
ev_document_get_title()
const gchar * ev_document_get_title (EvDocument * document)
Definition at line 626 of file ev-document.c.
References EV_DOCUMENT_INFO_TITLE, EV_IS_DOCUMENT, _EvDocumentInfo::fields_mask, NULL, _EvDocument::priv, and _EvDocumentInfo::title.
ev_document_get_type()
GType ev_document_get_type (void)
ev_document_get_uri()
const gchar * ev_document_get_uri (EvDocument * document)
Definition at line 618 of file ev-document.c.
References EV_IS_DOCUMENT, NULL, and _EvDocument::priv.
Referenced by ev_window_open_document().
ev_document_has_synctex()
gboolean ev_document_has_synctex (EvDocument * document)
ev_document_has_text_page_labels()
gboolean ev_document_has_text_page_labels (EvDocument * document)
Definition at line 685 of file ev-document.c.
References EV_IS_DOCUMENT, FALSE, NULL, and _EvDocument::priv.
ev_document_is_page_size_uniform()
gboolean ev_document_is_page_size_uniform (EvDocument * document)
Definition at line 635 of file ev-document.c.
References EV_IS_DOCUMENT, _EvDocument::priv, and TRUE.
Referenced by G_DEFINE_TYPE_WITH_CODE().
ev_document_load()
gboolean ev_document_load (EvDocument * document, const char * uri, GError ** error)
ev_document_load: @document: a EvDocument @uri: the document's URI @error: a #GError location to store an error, or NULL
Loads @document from @uri.
On failure, FALSE is returned and @error is filled in. If the document is encrypted, EV_DEFINE_ERROR_ENCRYPTED is returned. If the backend cannot load the specific document, EV_DOCUMENT_ERROR_INVALID is returned. Other errors are possible too, depending on the backend used to load the document and the URI, e.g. #GIOError, #GFileError, and #GConvertError.
Returns: TRUE on success, or FALSE on failure.
Definition at line 220 of file ev-document.c.
References error, EV_DOCUMENT_ERROR, EV_DOCUMENT_ERROR_INVALID, EV_DOCUMENT_GET_CLASS, ev_document_get_page(), ev_file_get_mime_type(), FALSE, _EvDocument::iswebdocument, _EvDocumentClass::load, MAX, NULL, _EvDocument::priv, and TRUE.
Referenced by ev_document_factory_get_document().
ev_document_render()
cairo_surface_t * ev_document_render (EvDocument * document, EvRenderContext * rc)
Definition at line 609 of file ev-document.c.
References EV_DOCUMENT_GET_CLASS, and _EvDocumentClass::render.
ev_document_save()
gboolean ev_document_save (EvDocument * document, const char * uri, GError ** error)
ev_document_save: @document: @uri: the target URI @error: a #GError location to store an error, or NULL
Saves @document to @uri.
Returns: TRUE on success, or FALSE on error with @error filled in
Definition at line 373 of file ev-document.c.
References error, EV_DOCUMENT_GET_CLASS, and _EvDocumentClass::save.
ev_document_synctex_backward_search()
EvSourceLink * ev_document_synctex_backward_search (EvDocument * document, gint page_index, gfloat x, gfloat y)
ev_document_synctex_forward_search()
EvMapping * ev_document_synctex_forward_search (EvDocument * document, EvSourceLink * source_link)
References b.
ev_document_toggle_night_mode()
void ev_document_toggle_night_mode (EvDocument * document, gboolean night)
Definition at line 946 of file ev-document.c.
References EV_DOCUMENT_GET_CLASS, and _EvDocumentClass::toggle_night_mode.
ev_rect_cmp()
gint ev_rect_cmp (EvRectangle * a, EvRectangle * b)
Definition at line 931 of file ev-document.c.
References b, EPSILON, NULL, _EvRectangle::x1, _EvRectangle::x2, _EvRectangle::y1, and _EvRectangle::y2.
Referenced by ev_pixbuf_cache_get_selection_region(), and ev_pixbuf_cache_get_selection_surface().
ev_rectangle_copy()
EvRectangle * ev_rectangle_copy (EvRectangle * ev_rect)
Definition at line 909 of file ev-document.c.
References NULL.
ev_rectangle_free()
void ev_rectangle_free (EvRectangle * ev_rect)
Definition at line 922 of file ev-document.c.
ev_rectangle_get_type()
GType ev_rectangle_get_type (void)
ev_rectangle_new()
EvRectangle * ev_rectangle_new (void)
Definition at line 903 of file ev-document.c.
ev_source_link_copy()
EvSourceLink * ev_source_link_copy (EvSourceLink * link)
Definition at line 759 of file ev-document.c.
References _EvSourceLink::filename, and NULL.
ev_source_link_free()
void ev_source_link_free (EvSourceLink * link)
Definition at line 774 of file ev-document.c.
References _EvSourceLink::filename, and NULL.
ev_source_link_get_type()
GType ev_source_link_get_type (void)
ev_source_link_new()
EvSourceLink * ev_source_link_new (const gchar * filename, gint line, gint col)
Definition at line 745 of file ev-document.c.
References _EvSourceLink::col, _EvSourceLink::filename, and _EvSourceLink::line.