MATE Desktop Environment: ev-document.c File Reference
ev-document.c File Reference
#include "config.h"
#include <stdlib.h>
#include <string.h>
#include "ev-document.h"
#include "ev-file-helpers.h"
Macros
#define EPSILON 0.0000001
Typedefs
typedef struct _EvPageSize EvPageSize
Functions
GQuark ev_document_error_quark (void)
void ev_document_doc_mutex_lock (void)
void ev_document_doc_mutex_unlock (void)
gboolean ev_document_doc_mutex_trylock (void)
void ev_document_fc_mutex_lock (void)
void ev_document_fc_mutex_unlock (void)
gboolean ev_document_fc_mutex_trylock (void)
gboolean ev_document_load (EvDocument *document, const char *uri, GError **error)
gboolean ev_document_save (EvDocument *document, const char *uri, GError **error)
EvPage * ev_document_get_page (EvDocument *document, gint index)
gint ev_document_get_n_pages (EvDocument *document)
void ev_document_get_page_size (EvDocument *document, gint page_index, double *width, double *height)
gchar * ev_document_get_page_label (EvDocument *document, gint page_index)
EvDocumentInfo * ev_document_get_info (EvDocument *document)
gboolean ev_document_get_backend_info (EvDocument *document, EvDocumentBackendInfo *info)
cairo_surface_t * ev_document_render (EvDocument *document, EvRenderContext *rc)
const gchar * ev_document_get_uri (EvDocument *document)
const gchar * ev_document_get_title (EvDocument *document)
gboolean ev_document_is_page_size_uniform (EvDocument *document)
void ev_document_get_max_page_size (EvDocument *document, gdouble *width, gdouble *height)
void ev_document_get_min_page_size (EvDocument *document, gdouble *width, gdouble *height)
gboolean ev_document_check_dimensions (EvDocument *document)
gint ev_document_get_max_label_len (EvDocument *document)
gboolean ev_document_has_text_page_labels (EvDocument *document)
gboolean ev_document_find_page_by_label (EvDocument *document, const gchar *page_label, gint *page_index)
EvSourceLink * ev_source_link_new (const gchar *filename, gint line, gint col)
EvSourceLink * ev_source_link_copy (EvSourceLink *link)
void ev_source_link_free (EvSourceLink *link)
EvDocumentInfo * ev_document_info_copy (EvDocumentInfo *info)
void ev_document_info_free (EvDocumentInfo *info)
EvDocumentLicense * ev_document_license_new (void)
EvDocumentLicense * ev_document_license_copy (EvDocumentLicense *license)
void ev_document_license_free (EvDocumentLicense *license)
const gchar * ev_document_license_get_text (EvDocumentLicense *license)
const gchar * ev_document_license_get_uri (EvDocumentLicense *license)
const gchar * ev_document_license_get_web_statement (EvDocumentLicense *license)
EvRectangle * ev_rectangle_new (void)
EvRectangle * ev_rectangle_copy (EvRectangle *rectangle)
void ev_rectangle_free (EvRectangle *rectangle)
gint ev_rect_cmp (EvRectangle *a, EvRectangle *b)
void ev_document_toggle_night_mode (EvDocument *document, gboolean night)
void ev_document_check_add_night_sheet (EvDocument *document)
Macro Definition Documentation
EPSILON
#define EPSILON 0.0000001
Definition at line 928 of file ev-document.c.
Referenced by ev_rect_cmp().
Typedef Documentation
EvPageSize
typedef struct _EvPageSize EvPageSize
Function Documentation
ev_document_check_add_night_sheet()
void ev_document_check_add_night_sheet (EvDocument * document)
Definition at line 953 of file ev-document.c.
References _EvDocumentClass::check_add_night_sheet, and EV_DOCUMENT_GET_CLASS.
ev_document_check_dimensions()
gboolean ev_document_check_dimensions (EvDocument * document)
Definition at line 669 of file ev-document.c.
References EV_IS_DOCUMENT, FALSE, and _EvDocument::priv.
ev_document_doc_mutex_lock()
void ev_document_doc_mutex_lock (void)
Definition at line 167 of file ev-document.c.
Referenced by ev_document_links_find_link_dest(), ev_document_links_find_link_page(), ev_pixbuf_cache_get_selection_region(), ev_pixbuf_cache_get_selection_surface(), and ev_view_remove_annotation().
ev_document_doc_mutex_trylock()
gboolean ev_document_doc_mutex_trylock (void)
Definition at line 179 of file ev-document.c.
ev_document_doc_mutex_unlock()
void ev_document_doc_mutex_unlock (void)
Definition at line 173 of file ev-document.c.
Referenced by ev_document_links_find_link_dest(), ev_document_links_find_link_page(), ev_pixbuf_cache_get_selection_region(), ev_pixbuf_cache_get_selection_surface(), and ev_view_remove_annotation().
ev_document_error_quark()
GQuark ev_document_error_quark (void)
Definition at line 81 of file ev-document.c.
ev_document_fc_mutex_lock()
void ev_document_fc_mutex_lock (void)
Definition at line 185 of file ev-document.c.
ev_document_fc_mutex_trylock()
gboolean ev_document_fc_mutex_trylock (void)
Definition at line 197 of file ev-document.c.
ev_document_fc_mutex_unlock()
void ev_document_fc_mutex_unlock (void)
Definition at line 191 of file ev-document.c.
ev_document_find_page_by_label()
gboolean ev_document_find_page_by_label (EvDocument * document, const gchar * page_label, gint * page_index)
Definition at line 693 of file ev-document.c.
References EV_IS_DOCUMENT, FALSE, MIN, NULL, _EvDocument::priv, and TRUE.
Referenced by ev_document_links_get_dest_page(), and ev_document_model_set_page_by_label().
ev_document_get_backend_info()
gboolean ev_document_get_backend_info (EvDocument * document, EvDocumentBackendInfo * info)
Definition at line 597 of file ev-document.c.
References EV_DOCUMENT_GET_CLASS, EV_IS_DOCUMENT, FALSE, _EvDocumentClass::get_backend_info, and NULL.
ev_document_get_info()
EvDocumentInfo * ev_document_get_info (EvDocument * document)
Definition at line 589 of file ev-document.c.
References EV_IS_DOCUMENT, NULL, and _EvDocument::priv.
Referenced by ev_properties_dialog_set_document().
ev_document_get_max_label_len()
gint ev_document_get_max_label_len (EvDocument * document)
Definition at line 677 of file ev-document.c.
References EV_IS_DOCUMENT, and _EvDocument::priv.
ev_document_get_max_page_size()
void ev_document_get_max_page_size (EvDocument * document, gdouble * width, gdouble * height)
Definition at line 643 of file ev-document.c.
References EV_IS_DOCUMENT, and _EvDocument::priv.
ev_document_get_min_page_size()
void ev_document_get_min_page_size (EvDocument * document, gdouble * width, gdouble * height)
Definition at line 656 of file ev-document.c.
References EV_IS_DOCUMENT, and _EvDocument::priv.
ev_document_get_n_pages()
gint ev_document_get_n_pages (EvDocument * document)
Definition at line 515 of file ev-document.c.
References EV_IS_DOCUMENT, and _EvDocument::priv.
Referenced by ev_document_model_set_document(), ev_page_cache_new(), ev_pixbuf_cache_get_selection_list(), ev_pixbuf_cache_set_page_range(), ev_pixbuf_cache_set_selection_list(), ev_view_get_page_extents(), ev_view_presentation_new(), ev_view_presentation_next_page(), ev_view_scroll(), ev_view_select_all(), ev_view_set_caret_cursor_position(), ev_window_print_range(), G_DEFINE_TYPE_EXTENDED(), and G_DEFINE_TYPE_WITH_CODE().
ev_document_get_page()
EvPage * ev_document_get_page (EvDocument * document, gint index)
Definition at line 383 of file ev-document.c.
References EV_DOCUMENT_GET_CLASS, and _EvDocumentClass::get_page.
Referenced by ev_document_load(), ev_pixbuf_cache_get_selection_region(), ev_pixbuf_cache_get_selection_surface(), and G_DEFINE_TYPE_EXTENDED().
ev_document_get_page_label()
gchar * ev_document_get_page_label (EvDocument * document, gint page_index)
Definition at line 569 of file ev-document.c.
References EV_IS_DOCUMENT, NULL, and _EvDocument::priv.
Referenced by ev_document_links_get_dest_page_label().
ev_document_get_page_size()
void ev_document_get_page_size (EvDocument * document, gint page_index, double * width, double * height)
Definition at line 534 of file ev-document.c.
References EV_IS_DOCUMENT, _EvDocument::iswebdocument, _EvDocument::priv, and TRUE.
Referenced by _get_page_size_for_scale_and_rotation(), G_DEFINE_TYPE_EXTENDED(), and G_DEFINE_TYPE_WITH_CODE().
ev_document_get_title()
const gchar * ev_document_get_title (EvDocument * document)
Definition at line 626 of file ev-document.c.
References EV_DOCUMENT_INFO_TITLE, EV_IS_DOCUMENT, _EvDocumentInfo::fields_mask, NULL, _EvDocument::priv, and _EvDocumentInfo::title.
ev_document_get_uri()
const gchar * ev_document_get_uri (EvDocument * document)
Definition at line 618 of file ev-document.c.
References EV_IS_DOCUMENT, NULL, and _EvDocument::priv.
Referenced by ev_window_open_document().
ev_document_has_text_page_labels()
gboolean ev_document_has_text_page_labels (EvDocument * document)
Definition at line 685 of file ev-document.c.
References EV_IS_DOCUMENT, FALSE, NULL, and _EvDocument::priv.
ev_document_info_copy()
EvDocumentInfo * ev_document_info_copy (EvDocumentInfo * info)
Definition at line 787 of file ev-document.c.
References _EvDocumentInfo::author, _EvDocumentInfo::creation_date, _EvDocumentInfo::creator, ev_document_license_copy(), _EvDocumentInfo::fields_mask, _EvDocumentInfo::format, _EvDocumentInfo::keywords, _EvDocumentInfo::layout, _EvDocumentInfo::license, _EvDocumentInfo::linearized, _EvDocumentInfo::mode, _EvDocumentInfo::modified_date, _EvDocumentInfo::n_pages, NULL, _EvDocumentInfo::permissions, _EvDocumentInfo::producer, _EvDocumentInfo::security, _EvDocumentInfo::subject, _EvDocumentInfo::title, and _EvDocumentInfo::ui_hints.
ev_document_info_free()
void ev_document_info_free (EvDocumentInfo * info)
Definition at line 819 of file ev-document.c.
References ev_document_license_free(), and NULL.
ev_document_is_page_size_uniform()
gboolean ev_document_is_page_size_uniform (EvDocument * document)
Definition at line 635 of file ev-document.c.
References EV_IS_DOCUMENT, _EvDocument::priv, and TRUE.
Referenced by G_DEFINE_TYPE_WITH_CODE().
ev_document_license_copy()
EvDocumentLicense * ev_document_license_copy (EvDocumentLicense * license)
Definition at line 849 of file ev-document.c.
References ev_document_license_new(), NULL, _EvDocumentLicense::text, _EvDocumentLicense::uri, and _EvDocumentLicense::web_statement.
Referenced by ev_document_info_copy().
ev_document_license_free()
void ev_document_license_free (EvDocumentLicense * license)
Definition at line 869 of file ev-document.c.
References _EvDocumentLicense::text, _EvDocumentLicense::uri, and _EvDocumentLicense::web_statement.
Referenced by ev_document_info_free().
ev_document_license_get_text()
const gchar * ev_document_license_get_text (EvDocumentLicense * license)
Definition at line 882 of file ev-document.c.
References _EvDocumentLicense::text.
Referenced by ev_properties_license_set_license().
ev_document_license_get_uri()
const gchar * ev_document_license_get_uri (EvDocumentLicense * license)
Definition at line 888 of file ev-document.c.
References _EvDocumentLicense::uri.
Referenced by ev_properties_license_set_license().
ev_document_license_get_web_statement()
const gchar * ev_document_license_get_web_statement (EvDocumentLicense * license)
Definition at line 894 of file ev-document.c.
References _EvDocumentLicense::web_statement.
Referenced by ev_properties_license_set_license().
ev_document_license_new()
EvDocumentLicense * ev_document_license_new (void)
Definition at line 843 of file ev-document.c.
Referenced by ev_document_license_copy().
ev_document_load()
gboolean ev_document_load (EvDocument * document, const char * uri, GError ** error)
ev_document_load: @document: a EvDocument @uri: the document's URI @error: a #GError location to store an error, or NULL
Loads @document from @uri.
On failure, FALSE is returned and @error is filled in. If the document is encrypted, EV_DEFINE_ERROR_ENCRYPTED is returned. If the backend cannot load the specific document, EV_DOCUMENT_ERROR_INVALID is returned. Other errors are possible too, depending on the backend used to load the document and the URI, e.g. #GIOError, #GFileError, and #GConvertError.
Returns: TRUE on success, or FALSE on failure.
Definition at line 220 of file ev-document.c.
References error, EV_DOCUMENT_ERROR, EV_DOCUMENT_ERROR_INVALID, EV_DOCUMENT_GET_CLASS, ev_document_get_page(), ev_file_get_mime_type(), FALSE, _EvDocument::iswebdocument, _EvDocumentClass::load, MAX, NULL, _EvDocument::priv, and TRUE.
Referenced by ev_document_factory_get_document().
ev_document_render()
cairo_surface_t * ev_document_render (EvDocument * document, EvRenderContext * rc)
Definition at line 609 of file ev-document.c.
References EV_DOCUMENT_GET_CLASS, and _EvDocumentClass::render.
ev_document_save()
gboolean ev_document_save (EvDocument * document, const char * uri, GError ** error)
ev_document_save: @document: @uri: the target URI @error: a #GError location to store an error, or NULL
Saves @document to @uri.
Returns: TRUE on success, or FALSE on error with @error filled in
Definition at line 373 of file ev-document.c.
References error, EV_DOCUMENT_GET_CLASS, and _EvDocumentClass::save.
ev_document_toggle_night_mode()
void ev_document_toggle_night_mode (EvDocument * document, gboolean night)
Definition at line 946 of file ev-document.c.
References EV_DOCUMENT_GET_CLASS, and _EvDocumentClass::toggle_night_mode.
ev_rect_cmp()
gint ev_rect_cmp (EvRectangle * a, EvRectangle * b)
Definition at line 931 of file ev-document.c.
References b, EPSILON, NULL, _EvRectangle::x1, _EvRectangle::x2, _EvRectangle::y1, and _EvRectangle::y2.
Referenced by ev_pixbuf_cache_get_selection_region(), and ev_pixbuf_cache_get_selection_surface().
ev_rectangle_copy()
EvRectangle * ev_rectangle_copy (EvRectangle * rectangle)
Definition at line 909 of file ev-document.c.
References NULL.
ev_rectangle_free()
void ev_rectangle_free (EvRectangle * rectangle)
Definition at line 922 of file ev-document.c.
ev_rectangle_new()
EvRectangle * ev_rectangle_new (void)
Definition at line 903 of file ev-document.c.
ev_source_link_copy()
EvSourceLink * ev_source_link_copy (EvSourceLink * link)
Definition at line 759 of file ev-document.c.
References _EvSourceLink::filename, and NULL.
ev_source_link_free()
void ev_source_link_free (EvSourceLink * link)
Definition at line 774 of file ev-document.c.
References _EvSourceLink::filename, and NULL.
ev_source_link_new()
EvSourceLink * ev_source_link_new (const gchar * filename, gint line, gint col)
Definition at line 745 of file ev-document.c.
References _EvSourceLink::col, _EvSourceLink::filename, and _EvSourceLink::line.