MATE Desktop Environment: ev-daemon-gdbus-generated.c File Reference
ev-daemon-gdbus-generated.c File Reference
#include "ev-daemon-gdbus-generated.h"
#include <string.h>
Macros
#define g_marshal_value_peek_boolean(v)
#define g_marshal_value_peek_char(v)
#define g_marshal_value_peek_uchar(v)
#define g_marshal_value_peek_int(v)
#define g_marshal_value_peek_uint(v)
#define g_marshal_value_peek_long(v)
#define g_marshal_value_peek_ulong(v)
#define g_marshal_value_peek_int64(v)
#define g_marshal_value_peek_uint64(v)
#define g_marshal_value_peek_enum(v)
#define g_marshal_value_peek_flags(v)
#define g_marshal_value_peek_float(v)
#define g_marshal_value_peek_double(v)
#define g_marshal_value_peek_string(v)
#define g_marshal_value_peek_param(v)
#define g_marshal_value_peek_boxed(v)
#define g_marshal_value_peek_pointer(v)
#define g_marshal_value_peek_object(v)
#define g_marshal_value_peek_variant(v)
Typedefs
typedef EvDaemonIface EvDaemonInterface
Functions
GDBusInterfaceInfo * ev_daemon_interface_info (void)
guint ev_daemon_override_properties (GObjectClass *klass G_GNUC_UNUSED, guint property_id_begin)
void ev_daemon_call_register_document (EvDaemon *proxy, const gchar *arg_uri, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean ev_daemon_call_register_document_finish (EvDaemon *proxy, gchar **out_owner, GAsyncResult *res, GError **error)
gboolean ev_daemon_call_register_document_sync (EvDaemon *proxy, const gchar *arg_uri, gchar **out_owner, GCancellable *cancellable, GError **error)
void ev_daemon_call_unregister_document (EvDaemon *proxy, const gchar *arg_uri, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean ev_daemon_call_unregister_document_finish (EvDaemon *proxy, GAsyncResult *res, GError **error)
gboolean ev_daemon_call_unregister_document_sync (EvDaemon *proxy, const gchar *arg_uri, GCancellable *cancellable, GError **error)
void ev_daemon_call_find_document (EvDaemon *proxy, const gchar *arg_uri, gboolean arg_spawn, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean ev_daemon_call_find_document_finish (EvDaemon *proxy, gchar **out_owner, GAsyncResult *res, GError **error)
gboolean ev_daemon_call_find_document_sync (EvDaemon *proxy, const gchar *arg_uri, gboolean arg_spawn, gchar **out_owner, GCancellable *cancellable, GError **error)
void ev_daemon_complete_register_document (EvDaemon *object G_GNUC_UNUSED, GDBusMethodInvocation *invocation, const gchar *owner)
void ev_daemon_complete_unregister_document (EvDaemon *object G_GNUC_UNUSED, GDBusMethodInvocation *invocation)
void ev_daemon_complete_find_document (EvDaemon *object G_GNUC_UNUSED, GDBusMethodInvocation *invocation, const gchar *owner)
G_DEFINE_TYPE_WITH_CODE (EvDaemonProxy, ev_daemon_proxy, G_TYPE_DBUS_PROXY, G_IMPLEMENT_INTERFACE(EV_TYPE_DAEMON, ev_daemon_proxy_iface_init))
: (nullable): A bus name (well-known or unique) or NULL if @connection is not a message bus connection.
ev_object_manager_client_new_sync: @connection: A #GDBusConnection. @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
@object_path: An object path. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL
Synchronously creates #GDBusObjectManagerClient using ev_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new_sync() for more details.
The calling thread is blocked until a reply is received.
See ev_object_manager_client_new() for the asynchronous version of this constructor.
Returns: (transfer full) (type EvObjectManagerClient): The constructed object manager client or NULL if @error is set.
void ev_daemon_proxy_new (GDBusConnection *connection, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
EvDaemon * ev_daemon_proxy_new_finish (GAsyncResult *res, GError **error)
EvDaemon * ev_daemon_proxy_new_sync (GDBusConnection *connection, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GError **error)
void ev_object_manager_client_new (GDBusConnection *connection, GDBusObjectManagerClientFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
GDBusObjectManager * ev_object_manager_client_new_finish (GAsyncResult *res, GError **error)
GDBusObjectManager * ev_object_manager_client_new_sync (GDBusConnection *connection, GDBusObjectManagerClientFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GError **error)
: A bus name (well-known or unique).
ev_object_manager_client_new_for_bus_sync: @bus_type: A #GBusType. @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
@object_path: An object path. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL
Like ev_object_manager_client_new_sync() but takes a #GBusType instead of a #GDBusConnection.
The calling thread is blocked until a reply is received.
See ev_object_manager_client_new_for_bus() for the asynchronous version of this constructor.
Returns: (transfer full) (type EvObjectManagerClient): The constructed object manager client or NULL if @error is set.
typedef EvObjectIface EvObjectInterface
void ev_daemon_proxy_new_for_bus (GBusType bus_type, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
EvDaemon * ev_daemon_proxy_new_for_bus_finish (GAsyncResult *res, GError **error)
EvDaemon * ev_daemon_proxy_new_for_bus_sync (GBusType bus_type, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GError **error)
G_DEFINE_TYPE_WITH_CODE (EvDaemonSkeleton, ev_daemon_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON, G_IMPLEMENT_INTERFACE(EV_TYPE_DAEMON, ev_daemon_skeleton_iface_init))
EvDaemon * ev_daemon_skeleton_new (void)
EvDaemon * ev_object_get_daemon (EvObject *object)
EvDaemon * ev_object_peek_daemon (EvObject *object)
G_DEFINE_TYPE_WITH_CODE (EvObjectProxy, ev_object_proxy, G_TYPE_DBUS_OBJECT_PROXY, G_IMPLEMENT_INTERFACE(G_TYPE_DBUS_OBJECT, ev_object_proxy__g_dbus_object_iface_init))
EvObjectProxy * ev_object_proxy_new (GDBusConnection *connection, const gchar *object_path)
G_DEFINE_TYPE_WITH_CODE (EvObjectSkeleton, ev_object_skeleton, G_TYPE_DBUS_OBJECT_SKELETON, G_IMPLEMENT_INTERFACE(G_TYPE_DBUS_OBJECT, ev_object_skeleton__g_dbus_object_iface_init))
EvObjectSkeleton * ev_object_skeleton_new (const gchar *object_path)
void ev_object_skeleton_set_daemon (EvObjectSkeleton *object, EvDaemon *interface_)
GType ev_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager G_GNUC_UNUSED, const gchar *object_path G_GNUC_UNUSED, const gchar *interface_name, gpointer user_data G_GNUC_UNUSED)
void ev_object_manager_client_new_for_bus (GBusType bus_type, GDBusObjectManagerClientFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
GDBusObjectManager * ev_object_manager_client_new_for_bus_finish (GAsyncResult *res, GError **error)
GDBusObjectManager * ev_object_manager_client_new_for_bus_sync (GBusType bus_type, GDBusObjectManagerClientFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GError **error)
Macro Definition Documentation
g_marshal_value_peek_boolean
#define g_marshal_value_peek_boolean (v)
Value:
(v)->data[0].v_int
Definition at line 45 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_boxed
#define g_marshal_value_peek_boxed (v)
Value:
(v)->data[0].v_pointer
Definition at line 60 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_char
#define g_marshal_value_peek_char (v)
Value:
(v)->data[0].v_int
Definition at line 46 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_double
#define g_marshal_value_peek_double (v)
Value:
(v)->data[0].v_double
Definition at line 57 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_enum
#define g_marshal_value_peek_enum (v)
Value:
(v)->data[0].v_long
Definition at line 54 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_flags
#define g_marshal_value_peek_flags (v)
Value:
(v)->data[0].v_ulong
Definition at line 55 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_float
#define g_marshal_value_peek_float (v)
Value:
(v)->data[0].v_float
Definition at line 56 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_int
#define g_marshal_value_peek_int (v)
Value:
(v)->data[0].v_int
Definition at line 48 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_int64
#define g_marshal_value_peek_int64 (v)
Value:
(v)->data[0].v_int64
Definition at line 52 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_long
#define g_marshal_value_peek_long (v)
Value:
(v)->data[0].v_long
Definition at line 50 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_object
#define g_marshal_value_peek_object (v)
Value:
(v)->data[0].v_pointer
Definition at line 62 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_param
#define g_marshal_value_peek_param (v)
Value:
(v)->data[0].v_pointer
Definition at line 59 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_pointer
#define g_marshal_value_peek_pointer (v)
Value:
(v)->data[0].v_pointer
Definition at line 61 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_string
#define g_marshal_value_peek_string (v)
Value:
(v)->data[0].v_pointer
Definition at line 58 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_uchar
#define g_marshal_value_peek_uchar (v)
Value:
(v)->data[0].v_uint
Definition at line 47 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_uint
#define g_marshal_value_peek_uint (v)
Value:
(v)->data[0].v_uint
Definition at line 49 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_uint64
#define g_marshal_value_peek_uint64 (v)
Value:
(v)->data[0].v_uint64
Definition at line 53 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_ulong
#define g_marshal_value_peek_ulong (v)
Value:
(v)->data[0].v_ulong
Definition at line 51 of file ev-daemon-gdbus-generated.c.
g_marshal_value_peek_variant
#define g_marshal_value_peek_variant (v)
Value:
(v)->data[0].v_pointer
Definition at line 63 of file ev-daemon-gdbus-generated.c.
Typedef Documentation
EvDaemonInterface
typedef EvDaemonIface EvDaemonInterface
EvDaemon:
Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-mate-atril-Daemon.top_of_page">org.mate.atril.Daemon</link>. EvDaemonIface: @parent_iface: The parent interface. @handle_find_document: Handler for the #EvDaemon::handle-find-document signal. @handle_register_document: Handler for the #EvDaemon::handle-register-document signal. @handle_unregister_document: Handler for the #EvDaemon::handle-unregister-document signal.
Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-mate-atril-Daemon.top_of_page">org.mate.atril.Daemon</link>.
Definition at line 551 of file ev-daemon-gdbus-generated.c.
EvObjectInterface
typedef EvObjectIface EvObjectInterface
SECTION:EvObject @title: EvObject @short_description: Specialized GDBusObject types
This section contains the EvObject, EvObjectProxy, and EvObjectSkeleton types which make it easier to work with objects implementing generated types for D-Bus interfaces. EvObject:
The EvObject type is a specialized container of interfaces. EvObjectIface: @parent_iface: The parent interface.
Virtual table for the EvObject interface.
Definition at line 1657 of file ev-daemon-gdbus-generated.c.
Function Documentation
ev_daemon_call_find_document()
void ev_daemon_call_find_document (EvDaemon * proxy, const gchar * arg_uri, gboolean arg_spawn, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
ev_daemon_call_find_document: @proxy: A EvDaemonProxy. @arg_uri: Argument to pass with the method invocation. @arg_spawn: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @callback: A #GAsyncReadyCallback to call when the request is satisfied or NULL. @user_data: User data to pass to @callback.
Asynchronously invokes the <link linkend="gdbus-method-org-mate-atril-Daemon.FindDocument">FindDocument()</link> D-Bus method on @proxy. When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()). You can then call ev_daemon_call_find_document_finish() to get the result of the operation.
See ev_daemon_call_find_document_sync() for the synchronous, blocking version of this method.
Definition at line 848 of file ev-daemon-gdbus-generated.c.
References proxy, and user_data.
ev_daemon_call_find_document_finish()
gboolean ev_daemon_call_find_document_finish (EvDaemon * proxy, gchar ** out_owner, GAsyncResult * res, GError ** error)
ev_daemon_call_find_document_finish: @proxy: A EvDaemonProxy. @out_owner: (out) (optional): Return location for return parameter or NULL to ignore. @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_daemon_call_find_document(). @error: Return location for error or NULL.
Finishes an operation started with ev_daemon_call_find_document().
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 880 of file ev-daemon-gdbus-generated.c.
References error, NULL, and proxy.
ev_daemon_call_find_document_sync()
gboolean ev_daemon_call_find_document_sync (EvDaemon * proxy, const gchar * arg_uri, gboolean arg_spawn, gchar ** out_owner, GCancellable * cancellable, GError ** error)
ev_daemon_call_find_document_sync: @proxy: A EvDaemonProxy. @arg_uri: Argument to pass with the method invocation. @arg_spawn: Argument to pass with the method invocation. @out_owner: (out) (optional): Return location for return parameter or NULL to ignore. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL.
Synchronously invokes the <link linkend="gdbus-method-org-mate-atril-Daemon.FindDocument">FindDocument()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
See ev_daemon_call_find_document() for the asynchronous version of this method.
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 914 of file ev-daemon-gdbus-generated.c.
References error, NULL, and proxy.
ev_daemon_call_register_document()
void ev_daemon_call_register_document (EvDaemon * proxy, const gchar * arg_uri, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
ev_daemon_call_register_document: @proxy: A EvDaemonProxy. @arg_uri: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @callback: A #GAsyncReadyCallback to call when the request is satisfied or NULL. @user_data: User data to pass to @callback.
Asynchronously invokes the <link linkend="gdbus-method-org-mate-atril-Daemon.RegisterDocument">RegisterDocument()</link> D-Bus method on @proxy. When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()). You can then call ev_daemon_call_register_document_finish() to get the result of the operation.
See ev_daemon_call_register_document_sync() for the synchronous, blocking version of this method.
Definition at line 645 of file ev-daemon-gdbus-generated.c.
References proxy, and user_data.
ev_daemon_call_register_document_finish()
gboolean ev_daemon_call_register_document_finish (EvDaemon * proxy, gchar ** out_owner, GAsyncResult * res, GError ** error)
ev_daemon_call_register_document_finish: @proxy: A EvDaemonProxy. @out_owner: (out) (optional): Return location for return parameter or NULL to ignore. @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_daemon_call_register_document(). @error: Return location for error or NULL.
Finishes an operation started with ev_daemon_call_register_document().
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 675 of file ev-daemon-gdbus-generated.c.
References error, NULL, and proxy.
ev_daemon_call_register_document_sync()
gboolean ev_daemon_call_register_document_sync (EvDaemon * proxy, const gchar * arg_uri, gchar ** out_owner, GCancellable * cancellable, GError ** error)
ev_daemon_call_register_document_sync: @proxy: A EvDaemonProxy. @arg_uri: Argument to pass with the method invocation. @out_owner: (out) (optional): Return location for return parameter or NULL to ignore. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL.
Synchronously invokes the <link linkend="gdbus-method-org-mate-atril-Daemon.RegisterDocument">RegisterDocument()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
See ev_daemon_call_register_document() for the asynchronous version of this method.
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 708 of file ev-daemon-gdbus-generated.c.
References error, NULL, and proxy.
ev_daemon_call_unregister_document()
void ev_daemon_call_unregister_document (EvDaemon * proxy, const gchar * arg_uri, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
ev_daemon_call_unregister_document: @proxy: A EvDaemonProxy. @arg_uri: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @callback: A #GAsyncReadyCallback to call when the request is satisfied or NULL. @user_data: User data to pass to @callback.
Asynchronously invokes the <link linkend="gdbus-method-org-mate-atril-Daemon.UnregisterDocument">UnregisterDocument()</link> D-Bus method on @proxy. When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()). You can then call ev_daemon_call_unregister_document_finish() to get the result of the operation.
See ev_daemon_call_unregister_document_sync() for the synchronous, blocking version of this method.
Definition at line 749 of file ev-daemon-gdbus-generated.c.
References proxy, and user_data.
ev_daemon_call_unregister_document_finish()
gboolean ev_daemon_call_unregister_document_finish (EvDaemon * proxy, GAsyncResult * res, GError ** error)
ev_daemon_call_unregister_document_finish: @proxy: A EvDaemonProxy. @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_daemon_call_unregister_document(). @error: Return location for error or NULL.
Finishes an operation started with ev_daemon_call_unregister_document().
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 778 of file ev-daemon-gdbus-generated.c.
References error, NULL, and proxy.
ev_daemon_call_unregister_document_sync()
gboolean ev_daemon_call_unregister_document_sync (EvDaemon * proxy, const gchar * arg_uri, GCancellable * cancellable, GError ** error)
ev_daemon_call_unregister_document_sync: @proxy: A EvDaemonProxy. @arg_uri: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL.
Synchronously invokes the <link linkend="gdbus-method-org-mate-atril-Daemon.UnregisterDocument">UnregisterDocument()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
See ev_daemon_call_unregister_document() for the asynchronous version of this method.
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 808 of file ev-daemon-gdbus-generated.c.
References error, NULL, and proxy.
ev_daemon_complete_find_document()
void ev_daemon_complete_find_document (EvDaemon *object G_GNUC_UNUSED, GDBusMethodInvocation * invocation, const gchar * owner)
ev_daemon_complete_find_document: @object: A EvDaemon. @invocation: (transfer full): A #GDBusMethodInvocation. @owner: Parameter to return.
Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-mate-atril-Daemon.FindDocument">FindDocument()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
This method will free @invocation, you cannot use it afterwards.
Definition at line 992 of file ev-daemon-gdbus-generated.c.
ev_daemon_complete_register_document()
void ev_daemon_complete_register_document (EvDaemon *object G_GNUC_UNUSED, GDBusMethodInvocation * invocation, const gchar * owner)
ev_daemon_complete_register_document: @object: A EvDaemon. @invocation: (transfer full): A #GDBusMethodInvocation. @owner: Parameter to return.
Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-mate-atril-Daemon.RegisterDocument">RegisterDocument()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
This method will free @invocation, you cannot use it afterwards.
Definition at line 953 of file ev-daemon-gdbus-generated.c.
ev_daemon_complete_unregister_document()
void ev_daemon_complete_unregister_document (EvDaemon *object G_GNUC_UNUSED, GDBusMethodInvocation * invocation)
ev_daemon_complete_unregister_document: @object: A EvDaemon. @invocation: (transfer full): A #GDBusMethodInvocation.
Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-mate-atril-Daemon.UnregisterDocument">UnregisterDocument()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
This method will free @invocation, you cannot use it afterwards.
Definition at line 973 of file ev-daemon-gdbus-generated.c.
ev_daemon_interface_info()
GDBusInterfaceInfo * ev_daemon_interface_info (void)
ev_daemon_interface_info:
Gets a machine-readable description of the <link linkend="gdbus-interface-org-mate-atril-Daemon.top_of_page">org.mate.atril.Daemon</link> D-Bus interface.
Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
Definition at line 473 of file ev-daemon-gdbus-generated.c.
ev_daemon_override_properties()
guint ev_daemon_override_properties (GObjectClass *klass G_GNUC_UNUSED, guint property_id_begin)
ev_daemon_override_properties: @klass: The class structure for a #GObject derived class. @property_id_begin: The property id to assign to the first overridden property.
Overrides all #GObject properties in the EvDaemon interface for a concrete class. The properties are overridden in the order they are defined.
Returns: The last property id.
Definition at line 489 of file ev-daemon-gdbus-generated.c.
ev_daemon_proxy_new()
void ev_daemon_proxy_new (GDBusConnection * connection, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 1183 of file ev-daemon-gdbus-generated.c.
References connection, EV_TYPE_DAEMON_PROXY, name, NULL, and user_data.
ev_daemon_proxy_new_finish()
EvDaemon * ev_daemon_proxy_new_finish (GAsyncResult * res, GError ** error)
ev_daemon_proxy_new_finish: @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_daemon_proxy_new(). @error: Return location for error or NULL
Finishes an operation started with ev_daemon_proxy_new().
Returns: (transfer full) (type EvDaemonProxy): The constructed proxy object or NULL if @error is set.
Definition at line 1205 of file ev-daemon-gdbus-generated.c.
References error, EV_DAEMON, and NULL.
ev_daemon_proxy_new_for_bus()
void ev_daemon_proxy_new_for_bus (GBusType bus_type, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 1273 of file ev-daemon-gdbus-generated.c.
References EV_TYPE_DAEMON_PROXY, name, NULL, and user_data.
ev_daemon_proxy_new_for_bus_finish()
EvDaemon * ev_daemon_proxy_new_for_bus_finish (GAsyncResult * res, GError ** error)
ev_daemon_proxy_new_for_bus_finish: @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_daemon_proxy_new_for_bus(). @error: Return location for error or NULL
Finishes an operation started with ev_daemon_proxy_new_for_bus().
Returns: (transfer full) (type EvDaemonProxy): The constructed proxy object or NULL if @error is set.
Definition at line 1295 of file ev-daemon-gdbus-generated.c.
References error, EV_DAEMON, and NULL.
ev_daemon_proxy_new_for_bus_sync()
EvDaemon * ev_daemon_proxy_new_for_bus_sync (GBusType bus_type, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GError ** error)
Definition at line 1328 of file ev-daemon-gdbus-generated.c.
References error, EV_DAEMON, EV_TYPE_DAEMON_PROXY, name, and NULL.
ev_daemon_proxy_new_sync()
EvDaemon * ev_daemon_proxy_new_sync (GDBusConnection * connection, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GError ** error)
Definition at line 1238 of file ev-daemon-gdbus-generated.c.
References connection, error, EV_DAEMON, EV_TYPE_DAEMON_PROXY, name, and NULL.
ev_daemon_skeleton_new()
EvDaemon * ev_daemon_skeleton_new (void)
ev_daemon_skeleton_new:
Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-mate-atril-Daemon.top_of_page">org.mate.atril.Daemon</link>.
Returns: (transfer full) (type EvDaemonSkeleton): The skeleton object.
Definition at line 1626 of file ev-daemon-gdbus-generated.c.
References EV_DAEMON, EV_TYPE_DAEMON_SKELETON, and NULL.
ev_object_get_daemon()
EvDaemon * ev_object_get_daemon (EvObject * object)
ev_object_get_daemon: @object: A EvObject.
Gets the EvDaemon instance for the D-Bus interface <link linkend="gdbus-interface-org-mate-atril-Daemon.top_of_page">org.mate.atril.Daemon</link> on @object, if any.
Returns: (transfer full) (nullable): A EvDaemon that must be freed with g_object_unref() or NULL if @object does not implement the interface.
Definition at line 1682 of file ev-daemon-gdbus-generated.c.
References EV_DAEMON, and NULL.
ev_object_manager_client_get_proxy_type()
GType ev_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager G_GNUC_UNUSED, const gchar *object_path G_GNUC_UNUSED, const gchar * interface_name, gpointer user_data G_GNUC_UNUSED)
ev_object_manager_client_get_proxy_type: @manager: A #GDBusObjectManagerClient. @object_path: The object path of the remote object (unused). @interface_name: (nullable): Interface name of the remote object or NULL to get the object proxy #GType. @user_data: User data (unused).
A #GDBusProxyTypeFunc that maps @interface_name to the generated #GDBusObjectProxy derived and #GDBusProxy derived types.
Returns: A #GDBusProxy derived #GType if @interface_name is not NULL, otherwise the #GType for EvObjectProxy.
Definition at line 1995 of file ev-daemon-gdbus-generated.c.
References EV_TYPE_DAEMON_PROXY, EV_TYPE_OBJECT_PROXY, NULL, and user_data.
Referenced by ev_object_manager_client_new(), ev_object_manager_client_new_for_bus(), ev_object_manager_client_new_for_bus_sync(), and ev_object_manager_client_new_sync().
ev_object_manager_client_new()
void ev_object_manager_client_new (GDBusConnection * connection, GDBusObjectManagerClientFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 2033 of file ev-daemon-gdbus-generated.c.
References connection, ev_object_manager_client_get_proxy_type(), EV_TYPE_OBJECT_MANAGER_CLIENT, name, NULL, and user_data.
ev_object_manager_client_new_finish()
GDBusObjectManager * ev_object_manager_client_new_finish (GAsyncResult * res, GError ** error)
ev_object_manager_client_new_finish: @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_object_manager_client_new(). @error: Return location for error or NULL
Finishes an operation started with ev_object_manager_client_new().
Returns: (transfer full) (type EvObjectManagerClient): The constructed object manager client or NULL if @error is set.
Definition at line 2055 of file ev-daemon-gdbus-generated.c.
References error, and NULL.
ev_object_manager_client_new_for_bus()
void ev_object_manager_client_new_for_bus (GBusType bus_type, GDBusObjectManagerClientFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 2123 of file ev-daemon-gdbus-generated.c.
References ev_object_manager_client_get_proxy_type(), EV_TYPE_OBJECT_MANAGER_CLIENT, name, NULL, and user_data.
ev_object_manager_client_new_for_bus_finish()
GDBusObjectManager * ev_object_manager_client_new_for_bus_finish (GAsyncResult * res, GError ** error)
ev_object_manager_client_new_for_bus_finish: @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_object_manager_client_new_for_bus(). @error: Return location for error or NULL
Finishes an operation started with ev_object_manager_client_new_for_bus().
Returns: (transfer full) (type EvObjectManagerClient): The constructed object manager client or NULL if @error is set.
Definition at line 2145 of file ev-daemon-gdbus-generated.c.
References error, and NULL.
ev_object_manager_client_new_for_bus_sync()
GDBusObjectManager * ev_object_manager_client_new_for_bus_sync (GBusType bus_type, GDBusObjectManagerClientFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GError ** error)
Definition at line 2178 of file ev-daemon-gdbus-generated.c.
References error, ev_object_manager_client_get_proxy_type(), EV_TYPE_OBJECT_MANAGER_CLIENT, name, and NULL.
ev_object_manager_client_new_sync()
GDBusObjectManager * ev_object_manager_client_new_sync (GDBusConnection * connection, GDBusObjectManagerClientFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GError ** error)
Definition at line 2088 of file ev-daemon-gdbus-generated.c.
References connection, error, ev_object_manager_client_get_proxy_type(), EV_TYPE_OBJECT_MANAGER_CLIENT, name, and NULL.
ev_object_peek_daemon()
EvDaemon * ev_object_peek_daemon (EvObject * object)
ev_object_peek_daemon: (skip) @object: A EvObject.
Like ev_object_get_daemon() but doesn't increase the reference count on the returned object.
It is not safe to use the returned object if you are on another thread than the one where the #GDBusObjectManagerClient or #GDBusObjectManagerServer for @object is running.
Returns: (transfer none) (nullable): A EvDaemon or NULL if @object does not implement the interface. Do not free the returned object, it is owned by @object.
Definition at line 1702 of file ev-daemon-gdbus-generated.c.
References EV_DAEMON, and NULL.
ev_object_proxy_new()
EvObjectProxy * ev_object_proxy_new (GDBusConnection * connection, const gchar * object_path)
ev_object_proxy_new: @connection: A #GDBusConnection. @object_path: An object path.
Creates a new proxy object.
Returns: (transfer full): The proxy object.
Definition at line 1811 of file ev-daemon-gdbus-generated.c.
References connection, EV_OBJECT_PROXY, EV_TYPE_OBJECT_PROXY, and NULL.
ev_object_skeleton_new()
EvObjectSkeleton * ev_object_skeleton_new (const gchar * object_path)
ev_object_skeleton_new: @object_path: An object path.
Creates a new skeleton object.
Returns: (transfer full): The skeleton object.
Definition at line 1926 of file ev-daemon-gdbus-generated.c.
References EV_OBJECT_SKELETON, EV_TYPE_OBJECT_SKELETON, and NULL.
ev_object_skeleton_set_daemon()
void ev_object_skeleton_set_daemon (EvObjectSkeleton * object, EvDaemon * interface_)
ev_object_skeleton_set_daemon: @object: A EvObjectSkeleton. @interface_: (nullable): A EvDaemon or NULL to clear the interface.
Sets the EvDaemon instance for the D-Bus interface <link linkend="gdbus-interface-org-mate-atril-Daemon.top_of_page">org.mate.atril.Daemon</link> on @object.
Definition at line 1939 of file ev-daemon-gdbus-generated.c.
References NULL.
G_DEFINE_TYPE_WITH_CODE() [1/4]
G_DEFINE_TYPE_WITH_CODE (EvDaemonProxy , ev_daemon_proxy , G_TYPE_DBUS_PROXY , G_IMPLEMENT_INTERFACE(EV_TYPE_DAEMON, ev_daemon_proxy_iface_init))
Definition at line 1025 of file ev-daemon-gdbus-generated.c.
References EV_DAEMON_PROXY, EV_TYPE_DAEMON, G_OBJECT_CLASS(), and proxy.
G_DEFINE_TYPE_WITH_CODE() [2/4]
G_DEFINE_TYPE_WITH_CODE (EvDaemonSkeleton , ev_daemon_skeleton , G_TYPE_DBUS_INTERFACE_SKELETON , G_IMPLEMENT_INTERFACE(EV_TYPE_DAEMON, ev_daemon_skeleton_iface_init))
Definition at line 1559 of file ev-daemon-gdbus-generated.c.
References EV_DAEMON_SKELETON, EV_TYPE_DAEMON, G_OBJECT_CLASS(), NULL, and _EvDaemonSkeleton::priv.
G_DEFINE_TYPE_WITH_CODE() [3/4]
G_DEFINE_TYPE_WITH_CODE (EvObjectProxy , ev_object_proxy , G_TYPE_DBUS_OBJECT_PROXY , G_IMPLEMENT_INTERFACE(G_TYPE_DBUS_OBJECT, ev_object_proxy__g_dbus_object_iface_init))
Definition at line 1750 of file ev-daemon-gdbus-generated.c.
References EV_TYPE_OBJECT.
G_DEFINE_TYPE_WITH_CODE() [4/4]
G_DEFINE_TYPE_WITH_CODE (EvObjectSkeleton , ev_object_skeleton , G_TYPE_DBUS_OBJECT_SKELETON , G_IMPLEMENT_INTERFACE(G_TYPE_DBUS_OBJECT, ev_object_skeleton__g_dbus_object_iface_init))
Definition at line 1845 of file ev-daemon-gdbus-generated.c.
References EV_TYPE_OBJECT.