MATE Desktop Environment: ev-document-links.h File Reference
ev-document-links.h File Reference
#include <glib-object.h>
#include <glib.h>
#include <gtk/gtk.h>
#include "ev-document.h"
#include "ev-link.h"
#include "ev-mapping-list.h"
Classes
struct _EvDocumentLinksInterface
Macros
#define EV_TYPE_DOCUMENT_LINKS (ev_document_links_get_type ())
#define EV_DOCUMENT_LINKS(o)
#define EV_DOCUMENT_LINKS_IFACE(k)
#define EV_IS_DOCUMENT_LINKS(o)
#define EV_IS_DOCUMENT_LINKS_IFACE(k)
#define EV_DOCUMENT_LINKS_GET_IFACE(inst)
Typedefs
typedef struct _EvDocumentLinks EvDocumentLinks
typedef struct _EvDocumentLinksInterface EvDocumentLinksInterface
Enumerations
enum {
EV_DOCUMENT_LINKS_COLUMN_MARKUP , EV_DOCUMENT_LINKS_COLUMN_LINK , EV_DOCUMENT_LINKS_COLUMN_EXPAND , EV_DOCUMENT_LINKS_COLUMN_PAGE_LABEL ,
EV_DOCUMENT_LINKS_COLUMN_NUM_COLUMNS
}
Functions
GType ev_document_links_get_type (void)
gboolean ev_document_links_has_document_links (EvDocumentLinks *document_links)
GtkTreeModel * ev_document_links_get_links_model (EvDocumentLinks *document_links)
EvMappingList * ev_document_links_get_links (EvDocumentLinks *document_links, EvPage *page)
EvLinkDest * ev_document_links_find_link_dest (EvDocumentLinks *document_links, const gchar *link_name)
gint ev_document_links_find_link_page (EvDocumentLinks *document_links, const gchar *link_name)
gint ev_document_links_get_dest_page (EvDocumentLinks *document_links, EvLinkDest *dest)
gchar * ev_document_links_get_dest_page_label (EvDocumentLinks *document_links, EvLinkDest *dest)
gint ev_document_links_get_link_page (EvDocumentLinks *document_links, EvLink *link)
gchar * ev_document_links_get_link_page_label (EvDocumentLinks *document_links, EvLink *link)
Macro Definition Documentation
EV_DOCUMENT_LINKS
#define EV_DOCUMENT_LINKS (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), EV_TYPE_DOCUMENT_LINKS, EvDocumentLinks))
Definition at line 42 of file ev-document-links.h.
EV_DOCUMENT_LINKS_GET_IFACE
#define EV_DOCUMENT_LINKS_GET_IFACE (inst)
Value:
(G_TYPE_INSTANCE_GET_INTERFACE ((inst), EV_TYPE_DOCUMENT_LINKS, EvDocumentLinksInterface))
Definition at line 46 of file ev-document-links.h.
Referenced by ev_document_links_find_link_dest(), ev_document_links_find_link_page(), ev_document_links_get_links(), ev_document_links_get_links_model(), and ev_document_links_has_document_links().
EV_DOCUMENT_LINKS_IFACE
#define EV_DOCUMENT_LINKS_IFACE (k)
Value:
(G_TYPE_CHECK_CLASS_CAST((k), EV_TYPE_DOCUMENT_LINKS, EvDocumentLinksInterface))
Definition at line 43 of file ev-document-links.h.
EV_IS_DOCUMENT_LINKS
#define EV_IS_DOCUMENT_LINKS (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), EV_TYPE_DOCUMENT_LINKS))
Definition at line 44 of file ev-document-links.h.
EV_IS_DOCUMENT_LINKS_IFACE
#define EV_IS_DOCUMENT_LINKS_IFACE (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), EV_TYPE_DOCUMENT_LINKS))
Definition at line 45 of file ev-document-links.h.
EV_TYPE_DOCUMENT_LINKS
#define EV_TYPE_DOCUMENT_LINKS (ev_document_links_get_type ())
Definition at line 41 of file ev-document-links.h.
Referenced by EV_BACKEND_REGISTER_WITH_CODE(), EV_BACKEND_REGISTER_WITH_CODE(), and EV_BACKEND_REGISTER_WITH_CODE().
Typedef Documentation
EvDocumentLinks
typedef struct _EvDocumentLinks EvDocumentLinks
Definition at line 48 of file ev-document-links.h.
EvDocumentLinksInterface
typedef struct _EvDocumentLinksInterface EvDocumentLinksInterface
Definition at line 49 of file ev-document-links.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EV_DOCUMENT_LINKS_COLUMN_MARKUP
EV_DOCUMENT_LINKS_COLUMN_LINK
EV_DOCUMENT_LINKS_COLUMN_EXPAND
EV_DOCUMENT_LINKS_COLUMN_PAGE_LABEL
EV_DOCUMENT_LINKS_COLUMN_NUM_COLUMNS
Definition at line 51 of file ev-document-links.h.
Function Documentation
ev_document_links_find_link_dest()
EvLinkDest * ev_document_links_find_link_dest (EvDocumentLinks * document_links, const gchar * link_name)
ev_document_links_find_link_dest: @document_links: an EvDocumentLinks @link_name: the link name
Returns: (transfer full): an EvLinkDest
Definition at line 80 of file ev-document-links.c.
References ev_document_doc_mutex_lock(), ev_document_doc_mutex_unlock(), EV_DOCUMENT_LINKS_GET_IFACE, and _EvDocumentLinksInterface::find_link_dest.
ev_document_links_find_link_page()
gint ev_document_links_find_link_page (EvDocumentLinks * document_links, const gchar * link_name)
Definition at line 94 of file ev-document-links.c.
References ev_document_doc_mutex_lock(), ev_document_doc_mutex_unlock(), EV_DOCUMENT_LINKS_GET_IFACE, and _EvDocumentLinksInterface::find_link_page.
Referenced by ev_document_links_get_dest_page().
ev_document_links_get_dest_page()
gint ev_document_links_get_dest_page (EvDocumentLinks * document_links, EvLinkDest * dest)
Definition at line 109 of file ev-document-links.c.
References dest, EV_DOCUMENT, ev_document_find_page_by_label(), ev_document_links_find_link_page(), ev_link_dest_get_dest_type(), ev_link_dest_get_named_dest(), ev_link_dest_get_page(), ev_link_dest_get_page_label(), EV_LINK_DEST_TYPE_NAMED, and EV_LINK_DEST_TYPE_PAGE_LABEL.
Referenced by ev_document_links_get_dest_page_label(), and ev_document_links_get_link_page().
ev_document_links_get_dest_page_label()
gchar * ev_document_links_get_dest_page_label (EvDocumentLinks * document_links, EvLinkDest * dest)
Definition at line 133 of file ev-document-links.c.
References dest, EV_DOCUMENT, ev_document_get_page_label(), ev_document_links_get_dest_page(), ev_link_dest_get_dest_type(), ev_link_dest_get_page_label(), EV_LINK_DEST_TYPE_PAGE_LABEL, label, and NULL.
Referenced by ev_document_links_get_link_page_label().
ev_document_links_get_link_page()
gint ev_document_links_get_link_page (EvDocumentLinks * document_links, EvLink * link)
Definition at line 169 of file ev-document-links.c.
References dest, and ev_document_links_get_dest_page().
ev_document_links_get_link_page_label()
gchar * ev_document_links_get_link_page_label (EvDocumentLinks * document_links, EvLink * link)
Definition at line 180 of file ev-document-links.c.
References dest, ev_document_links_get_dest_page_label(), and NULL.
ev_document_links_get_links()
EvMappingList * ev_document_links_get_links (EvDocumentLinks * document_links, EvPage * page)
Definition at line 64 of file ev-document-links.c.
References EV_DOCUMENT_LINKS_GET_IFACE, and _EvDocumentLinksInterface::get_links.
ev_document_links_get_links_model()
GtkTreeModel * ev_document_links_get_links_model (EvDocumentLinks * document_links)
ev_document_links_get_links_model: @document_links: an EvDocumentLinks
Returns: (transfer full): a #GtkTreeModel
Definition at line 53 of file ev-document-links.c.
References EV_DOCUMENT_LINKS_GET_IFACE, and _EvDocumentLinksInterface::get_links_model.
ev_document_links_get_type()
GType ev_document_links_get_type (void)
References dest.
ev_document_links_has_document_links()
gboolean ev_document_links_has_document_links (EvDocumentLinks * document_links)
Definition at line 36 of file ev-document-links.c.
References EV_DOCUMENT_LINKS_GET_IFACE, and _EvDocumentLinksInterface::has_document_links.