MATE Desktop Environment: ev-document-model.h File Reference
ev-document-model.h File Reference
#include <glib-object.h>
#include <atril-document.h>
Macros
#define EV_TYPE_DOCUMENT_MODEL (ev_document_model_get_type ())
#define EV_DOCUMENT_MODEL(obj)
#define EV_IS_DOCUMENT_MODEL(obj)
Typedefs
typedef struct _EvDocumentModel EvDocumentModel
typedef struct _EvDocumentModelClass EvDocumentModelClass
Enumerations
enum EvSizingMode {
EV_SIZING_FIT_PAGE , EV_SIZING_BEST_FIT = EV_SIZING_FIT_PAGE , EV_SIZING_FIT_WIDTH , EV_SIZING_FREE ,
EV_SIZING_AUTOMATIC
}
enum EvPageLayout { EV_PAGE_LAYOUT_SINGLE , EV_PAGE_LAYOUT_DUAL , EV_PAGE_LAYOUT_AUTOMATIC }
Functions
GType ev_document_model_get_type (void)
EvDocumentModel * ev_document_model_new (void)
EvDocumentModel * ev_document_model_new_with_document (EvDocument *document)
void ev_document_model_set_document (EvDocumentModel *model, EvDocument *document)
EvDocument * ev_document_model_get_document (EvDocumentModel *model)
void ev_document_model_set_page (EvDocumentModel *model, gint page)
void ev_document_model_set_page_by_label (EvDocumentModel *model, const gchar *page_label)
gint ev_document_model_get_page (EvDocumentModel *model)
void ev_document_model_set_scale (EvDocumentModel *model, gdouble scale)
gdouble ev_document_model_get_scale (EvDocumentModel *model)
void ev_document_model_set_max_scale (EvDocumentModel *model, gdouble max_scale)
gdouble ev_document_model_get_max_scale (EvDocumentModel *model)
void ev_document_model_set_min_scale (EvDocumentModel *model, gdouble min_scale)
gdouble ev_document_model_get_min_scale (EvDocumentModel *model)
void ev_document_model_set_sizing_mode (EvDocumentModel *model, EvSizingMode mode)
EvSizingMode ev_document_model_get_sizing_mode (EvDocumentModel *model)
void ev_document_model_set_page_layout (EvDocumentModel *model, EvPageLayout layout)
EvPageLayout ev_document_model_get_page_layout (EvDocumentModel *model)
void ev_document_model_set_rotation (EvDocumentModel *model, gint rotation)
gint ev_document_model_get_rotation (EvDocumentModel *model)
void ev_document_model_set_inverted_colors (EvDocumentModel *model, gboolean inverted_colors)
void atril_web_document_set_inverted_colors (EvDocumentModel *model, gboolean inverted_colors)
gboolean ev_document_model_get_inverted_colors (EvDocumentModel *model)
void ev_document_model_set_continuous (EvDocumentModel *model, gboolean continuous)
gboolean ev_document_model_get_continuous (EvDocumentModel *model)
void ev_document_model_set_dual_page_odd_pages_left (EvDocumentModel *model, gboolean odd_left)
gboolean ev_document_model_get_dual_page_odd_pages_left (EvDocumentModel *model)
void ev_document_model_set_fullscreen (EvDocumentModel *model, gboolean fullscreen)
gboolean ev_document_model_get_fullscreen (EvDocumentModel *model)
void ev_document_model_set_dual_page (EvDocumentModel *model, gboolean dual_page)
gboolean ev_document_model_get_dual_page (EvDocumentModel *model)
Macro Definition Documentation
EV_DOCUMENT_MODEL
#define EV_DOCUMENT_MODEL (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), EV_TYPE_DOCUMENT_MODEL, EvDocumentModel))
Definition at line 33 of file ev-document-model.h.
EV_IS_DOCUMENT_MODEL
#define EV_IS_DOCUMENT_MODEL (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), EV_TYPE_DOCUMENT_MODEL))
Definition at line 34 of file ev-document-model.h.
Referenced by ev_document_model_get_continuous(), ev_document_model_get_document(), ev_document_model_get_dual_page(), ev_document_model_get_dual_page_odd_pages_left(), ev_document_model_get_fullscreen(), ev_document_model_get_inverted_colors(), ev_document_model_get_max_scale(), ev_document_model_get_min_scale(), ev_document_model_get_page(), ev_document_model_get_page_layout(), ev_document_model_get_rotation(), ev_document_model_get_scale(), ev_document_model_get_sizing_mode(), ev_document_model_set_continuous(), ev_document_model_set_document(), ev_document_model_set_dual_page(), ev_document_model_set_dual_page_odd_pages_left(), ev_document_model_set_fullscreen(), ev_document_model_set_inverted_colors(), ev_document_model_set_max_scale(), ev_document_model_set_min_scale(), ev_document_model_set_page(), ev_document_model_set_page_by_label(), ev_document_model_set_page_layout(), ev_document_model_set_rotation(), ev_document_model_set_scale(), ev_document_model_set_sizing_mode(), ev_page_action_set_model(), ev_sidebar_page_set_model(), ev_sidebar_set_model(), and ev_view_set_model().
EV_TYPE_DOCUMENT_MODEL
#define EV_TYPE_DOCUMENT_MODEL (ev_document_model_get_type ())
Definition at line 32 of file ev-document-model.h.
Referenced by ev_document_model_new(), and ev_document_model_new_with_document().
Typedef Documentation
EvDocumentModel
typedef struct _EvDocumentModel EvDocumentModel
Definition at line 50 of file ev-document-model.h.
EvDocumentModelClass
typedef struct _EvDocumentModelClass EvDocumentModelClass
Definition at line 51 of file ev-document-model.h.
Enumeration Type Documentation
EvPageLayout
enum EvPageLayout
Enumerator
EV_PAGE_LAYOUT_SINGLE
EV_PAGE_LAYOUT_DUAL
EV_PAGE_LAYOUT_AUTOMATIC
Definition at line 44 of file ev-document-model.h.
EvSizingMode
enum EvSizingMode
Enumerator
EV_SIZING_FIT_PAGE
EV_SIZING_BEST_FIT
EV_SIZING_FIT_WIDTH
EV_SIZING_FREE
EV_SIZING_AUTOMATIC
Definition at line 36 of file ev-document-model.h.
Function Documentation
atril_web_document_set_inverted_colors()
void atril_web_document_set_inverted_colors (EvDocumentModel * model, gboolean inverted_colors)
References ev_document_model_get_page_layout(), and ev_document_model_set_page_layout().
ev_document_model_get_continuous()
gboolean ev_document_model_get_continuous (EvDocumentModel * model)
Definition at line 599 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL, and TRUE.
Referenced by ev_view_set_model().
ev_document_model_get_document()
EvDocument * ev_document_model_get_document (EvDocumentModel * model)
ev_document_model_get_document: @model: a EvDocumentModel
Returns the EvDocument referenced by the model.
Returns: (transfer none): a EvDocument
Definition at line 350 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL, and NULL.
Referenced by ev_pixbuf_cache_new().
ev_document_model_get_dual_page()
gboolean ev_document_model_get_dual_page (EvDocumentModel * model)
Definition at line 619 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL, and FALSE.
ev_document_model_get_dual_page_odd_pages_left()
gboolean ev_document_model_get_dual_page_odd_pages_left (EvDocumentModel * model)
Definition at line 643 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL, and FALSE.
ev_document_model_get_fullscreen()
gboolean ev_document_model_get_fullscreen (EvDocumentModel * model)
Definition at line 667 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL, and FALSE.
Referenced by ev_view_set_model().
ev_document_model_get_inverted_colors()
gboolean ev_document_model_get_inverted_colors (EvDocumentModel * model)
Definition at line 575 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL, and FALSE.
ev_document_model_get_max_scale()
gdouble ev_document_model_get_max_scale (EvDocumentModel * model)
Definition at line 440 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL.
Referenced by ev_view_can_zoom_in().
ev_document_model_get_min_scale()
gdouble ev_document_model_get_min_scale (EvDocumentModel * model)
Definition at line 463 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL.
Referenced by ev_view_can_zoom_out().
ev_document_model_get_page()
gint ev_document_model_get_page (EvDocumentModel * model)
Definition at line 391 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL.
Referenced by ev_window_print_range().
ev_document_model_get_page_layout()
EvPageLayout ev_document_model_get_page_layout (EvDocumentModel * model)
Definition at line 526 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL, and EV_PAGE_LAYOUT_SINGLE.
Referenced by atril_web_document_set_inverted_colors(), and ev_view_set_model().
ev_document_model_get_rotation()
gint ev_document_model_get_rotation (EvDocumentModel * model)
Definition at line 553 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL.
Referenced by ev_pixbuf_cache_set_page_range(), and ev_view_set_model().
ev_document_model_get_scale()
gdouble ev_document_model_get_scale (EvDocumentModel * model)
Definition at line 417 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL.
Referenced by ev_pixbuf_cache_set_page_range(), ev_view_set_model(), and ev_view_zoom().
ev_document_model_get_sizing_mode()
EvSizingMode ev_document_model_get_sizing_mode (EvDocumentModel * model)
Definition at line 485 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL, and EV_SIZING_FIT_WIDTH.
Referenced by ev_view_set_model().
ev_document_model_get_type()
GType ev_document_model_get_type (void)
ev_document_model_new()
EvDocumentModel * ev_document_model_new (void)
Definition at line 307 of file ev-document-model.c.
References EV_TYPE_DOCUMENT_MODEL, and NULL.
Referenced by main().
ev_document_model_new_with_document()
EvDocumentModel * ev_document_model_new_with_document (EvDocument * document)
Definition at line 313 of file ev-document-model.c.
References EV_IS_DOCUMENT, EV_TYPE_DOCUMENT_MODEL, and NULL.
ev_document_model_set_continuous()
void ev_document_model_set_continuous (EvDocumentModel * model, gboolean continuous)
Definition at line 583 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL, and FALSE.
ev_document_model_set_document()
void ev_document_model_set_document (EvDocumentModel * model, EvDocument * document)
Definition at line 321 of file ev-document-model.c.
References ev_document_get_n_pages(), ev_document_model_set_page(), EV_IS_DOCUMENT, and EV_IS_DOCUMENT_MODEL.
Referenced by ev_window_open_document().
ev_document_model_set_dual_page()
void ev_document_model_set_dual_page (EvDocumentModel * model, gboolean dual_page)
Definition at line 607 of file ev-document-model.c.
References ev_document_model_set_page_layout(), EV_IS_DOCUMENT_MODEL, EV_PAGE_LAYOUT_DUAL, and EV_PAGE_LAYOUT_SINGLE.
ev_document_model_set_dual_page_odd_pages_left()
void ev_document_model_set_dual_page_odd_pages_left (EvDocumentModel * model, gboolean odd_left)
Definition at line 627 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL, and FALSE.
ev_document_model_set_fullscreen()
void ev_document_model_set_fullscreen (EvDocumentModel * model, gboolean fullscreen)
Definition at line 651 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL, and FALSE.
ev_document_model_set_inverted_colors()
void ev_document_model_set_inverted_colors (EvDocumentModel * model, gboolean inverted_colors)
Definition at line 561 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL, and FALSE.
ev_document_model_set_max_scale()
void ev_document_model_set_max_scale (EvDocumentModel * model, gdouble max_scale)
Definition at line 425 of file ev-document-model.c.
References ev_document_model_set_scale(), and EV_IS_DOCUMENT_MODEL.
ev_document_model_set_min_scale()
void ev_document_model_set_min_scale (EvDocumentModel * model, gdouble min_scale)
Definition at line 448 of file ev-document-model.c.
References ev_document_model_set_scale(), and EV_IS_DOCUMENT_MODEL.
ev_document_model_set_page()
void ev_document_model_set_page (EvDocumentModel * model, gint page)
Definition at line 358 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL, and PAGE_CHANGED.
Referenced by _ev_view_set_focused_element(), ev_document_model_set_document(), ev_document_model_set_page_by_label(), ev_view_next_page(), and ev_view_previous_page().
ev_document_model_set_page_by_label()
void ev_document_model_set_page_by_label (EvDocumentModel * model, const gchar * page_label)
Definition at line 378 of file ev-document-model.c.
References ev_document_find_page_by_label(), ev_document_model_set_page(), EV_IS_DOCUMENT_MODEL, and NULL.
ev_document_model_set_page_layout()
void ev_document_model_set_page_layout (EvDocumentModel * model, EvPageLayout layout)
Definition at line 509 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL, and EV_PAGE_LAYOUT_DUAL.
Referenced by atril_web_document_set_inverted_colors(), and ev_document_model_set_dual_page().
ev_document_model_set_rotation()
void ev_document_model_set_rotation (EvDocumentModel * model, gint rotation)
Definition at line 534 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL.
ev_document_model_set_scale()
void ev_document_model_set_scale (EvDocumentModel * model, gdouble scale)
Definition at line 399 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL, and EV_SIZING_FREE.
Referenced by ev_document_model_set_max_scale(), ev_document_model_set_min_scale(), ev_view_zoom(), and ev_view_zoom_reset().
ev_document_model_set_sizing_mode()
void ev_document_model_set_sizing_mode (EvDocumentModel * model, EvSizingMode mode)
Definition at line 471 of file ev-document-model.c.
References EV_IS_DOCUMENT_MODEL.