MATE Desktop Environment: ev-document-factory.c File Reference
ev-document-factory.c File Reference
#include <string.h>
#include <gio/gio.h>
#include <glib/gstdio.h>
#include <glib/gi18n-lib.h>
#include <gtk/gtk.h>
#include "ev-backends-manager.h"
#include "ev-document-factory.h"
#include "ev-file-helpers.h"
Functions
EvDocument * ev_document_factory_get_document (const char *uri, GError **error)
void ev_document_factory_add_filters (GtkWidget *chooser, EvDocument *document)
Function Documentation
ev_document_factory_add_filters()
void ev_document_factory_add_filters (GtkWidget * chooser, EvDocument * document)
ev_document_factory_add_filters: @chooser: a #GtkFileChooser @document: a EvDocument, or NULL
Adds some file filters to @chooser.
Always add a "All documents" format.
If @document is not NULL, adds a #GtkFileFilter for @document's MIME type.
If @document is NULL, adds a #GtkFileFilter for each document type that atril can handle.
Definition at line 345 of file ev-document-factory.c.
References _, ev_backends_manager_get_all_types_info(), ev_backends_manager_get_document_type_info(), EV_IS_DOCUMENT, and NULL.
ev_document_factory_get_document()
EvDocument * ev_document_factory_get_document (const char * uri, GError ** error)
ev_document_factory_get_document: @uri: an URI @error: a #GError location to store an error, or NULL
Creates a EvDocument for the document at @uri; or, if no backend handling the document's type is found, or an error occurred on opening the document, returns NULL and fills in @error. If the document is encrypted, it is returned but also @error is set to EV_DOCUMENT_ERROR_ENCRYPTED.
Returns: (transfer full): a new EvDocument, or NULL.
Definition at line 207 of file ev-document-factory.c.
References _, error, EV_DOCUMENT_ERROR, EV_DOCUMENT_ERROR_ENCRYPTED, EV_DOCUMENT_ERROR_INVALID, ev_document_load(), ev_file_uncompress(), FALSE, NULL, and TRUE.