MATE Desktop Environment: ev-form-field-accessible.c File Reference
ev-form-field-accessible.c File Reference
#include <config.h>
#include "ev-form-field-accessible.h"
#include "ev-view-private.h"
Functions
G_DEFINE_TYPE_WITH_CODE (EvFormFieldAccessible, ev_form_field_accessible, ATK_TYPE_OBJECT, G_IMPLEMENT_INTERFACE(ATK_TYPE_COMPONENT, ev_form_field_accessible_component_iface_init))
EvFormFieldAccessible * ev_form_field_accessible_new (EvPageAccessible *page, EvFormField *form_field, EvRectangle *area)
Function Documentation
ev_form_field_accessible_new()
EvFormFieldAccessible * ev_form_field_accessible_new (EvPageAccessible * page, EvFormField * form_field, EvRectangle * area)
Definition at line 228 of file ev-form-field-accessible.c.
References EV_FORM_FIELD_ACCESSIBLE, EV_TYPE_FORM_FIELD_ACCESSIBLE, NULL, and _EvFormFieldAccessible::priv.
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (EvFormFieldAccessible , ev_form_field_accessible , ATK_TYPE_OBJECT , G_IMPLEMENT_INTERFACE(ATK_TYPE_COMPONENT, ev_form_field_accessible_component_iface_init))
Definition at line 35 of file ev-form-field-accessible.c.
References _transform_doc_rect_to_atk_rect(), EV_FORM_FIELD_ACCESSIBLE, ev_page_accessible_get_page(), ev_page_accessible_get_view_accessible(), _EvFormFieldAccessible::priv, _EvRectangle::x1, _EvRectangle::x2, _EvRectangle::y1, and _EvRectangle::y2.