MATE Desktop Environment: ev-gdbus-generated.c File Reference
ev-gdbus-generated.c File Reference
#include "ev-gdbus-generated.h"
#include <string.h>
Macros
#define g_marshal_value_peek_boolean(v)
#define g_marshal_value_peek_char(v)
#define g_marshal_value_peek_uchar(v)
#define g_marshal_value_peek_int(v)
#define g_marshal_value_peek_uint(v)
#define g_marshal_value_peek_long(v)
#define g_marshal_value_peek_ulong(v)
#define g_marshal_value_peek_int64(v)
#define g_marshal_value_peek_uint64(v)
#define g_marshal_value_peek_enum(v)
#define g_marshal_value_peek_flags(v)
#define g_marshal_value_peek_float(v)
#define g_marshal_value_peek_double(v)
#define g_marshal_value_peek_string(v)
#define g_marshal_value_peek_param(v)
#define g_marshal_value_peek_boxed(v)
#define g_marshal_value_peek_pointer(v)
#define g_marshal_value_peek_object(v)
#define g_marshal_value_peek_variant(v)
Typedefs
typedef EvAtrilApplicationIface EvAtrilApplicationInterface
Functions
GDBusInterfaceInfo * ev_atril_application_interface_info (void)
guint ev_atril_application_override_properties (GObjectClass *klass G_GNUC_UNUSED, guint property_id_begin)
void ev_atril_application_call_reload (EvAtrilApplication *proxy, GVariant *arg_args, guint arg_timestamp, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean ev_atril_application_call_reload_finish (EvAtrilApplication *proxy, GAsyncResult *res, GError **error)
gboolean ev_atril_application_call_reload_sync (EvAtrilApplication *proxy, GVariant *arg_args, guint arg_timestamp, GCancellable *cancellable, GError **error)
void ev_atril_application_call_get_window_list (EvAtrilApplication *proxy, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean ev_atril_application_call_get_window_list_finish (EvAtrilApplication *proxy, gchar ***out_window_list, GAsyncResult *res, GError **error)
gboolean ev_atril_application_call_get_window_list_sync (EvAtrilApplication *proxy, gchar ***out_window_list, GCancellable *cancellable, GError **error)
void ev_atril_application_complete_reload (EvAtrilApplication *object G_GNUC_UNUSED, GDBusMethodInvocation *invocation)
void ev_atril_application_complete_get_window_list (EvAtrilApplication *object G_GNUC_UNUSED, GDBusMethodInvocation *invocation, const gchar *const *window_list)
G_DEFINE_TYPE_WITH_CODE (EvAtrilApplicationProxy, ev_atril_application_proxy, G_TYPE_DBUS_PROXY, G_IMPLEMENT_INTERFACE(EV_TYPE_ATRIL_APPLICATION, ev_atril_application_proxy_iface_init))
: (nullable): A bus name (well-known or unique) or NULL if @connection is not a message bus connection.
ev_object_manager_client_new_sync: @connection: A #GDBusConnection. @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
@object_path: An object path. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL
Synchronously creates #GDBusObjectManagerClient using ev_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new_sync() for more details.
The calling thread is blocked until a reply is received.
See ev_object_manager_client_new() for the asynchronous version of this constructor.
Returns: (transfer full) (type EvObjectManagerClient): The constructed object manager client or NULL if @error is set.
void ev_atril_application_proxy_new (GDBusConnection *connection, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
EvAtrilApplication * ev_atril_application_proxy_new_finish (GAsyncResult *res, GError **error)
EvAtrilApplication * ev_atril_application_proxy_new_sync (GDBusConnection *connection, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GError **error)
void ev_atril_window_proxy_new (GDBusConnection *connection, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
EvAtrilWindow * ev_atril_window_proxy_new_finish (GAsyncResult *res, GError **error)
EvAtrilWindow * ev_atril_window_proxy_new_sync (GDBusConnection *connection, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GError **error)
void ev_object_manager_client_new (GDBusConnection *connection, GDBusObjectManagerClientFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
GDBusObjectManager * ev_object_manager_client_new_finish (GAsyncResult *res, GError **error)
GDBusObjectManager * ev_object_manager_client_new_sync (GDBusConnection *connection, GDBusObjectManagerClientFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GError **error)
: A bus name (well-known or unique).
ev_object_manager_client_new_for_bus_sync: @bus_type: A #GBusType. @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
@object_path: An object path. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL
Like ev_object_manager_client_new_sync() but takes a #GBusType instead of a #GDBusConnection.
The calling thread is blocked until a reply is received.
See ev_object_manager_client_new_for_bus() for the asynchronous version of this constructor.
Returns: (transfer full) (type EvObjectManagerClient): The constructed object manager client or NULL if @error is set.
enum { EV__ATRIL_WINDOW_SYNC_SOURCE , EV__ATRIL_WINDOW_CLOSED , EV__ATRIL_WINDOW_DOCUMENT_LOADED }
typedef EvAtrilWindowIface EvAtrilWindowInterface
void ev_atril_application_proxy_new_for_bus (GBusType bus_type, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
EvAtrilApplication * ev_atril_application_proxy_new_for_bus_finish (GAsyncResult *res, GError **error)
EvAtrilApplication * ev_atril_application_proxy_new_for_bus_sync (GBusType bus_type, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GError **error)
G_DEFINE_TYPE_WITH_CODE (EvAtrilApplicationSkeleton, ev_atril_application_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON, G_IMPLEMENT_INTERFACE(EV_TYPE_ATRIL_APPLICATION, ev_atril_application_skeleton_iface_init))
EvAtrilApplication * ev_atril_application_skeleton_new (void)
GDBusInterfaceInfo * ev_atril_window_interface_info (void)
guint ev_atril_window_override_properties (GObjectClass *klass G_GNUC_UNUSED, guint property_id_begin)
void ev_atril_window_emit_sync_source (EvAtrilWindow *object, const gchar *arg_source_file, GVariant *arg_source_point, guint arg_timestamp)
void ev_atril_window_emit_closed (EvAtrilWindow *object)
void ev_atril_window_emit_document_loaded (EvAtrilWindow *object, const gchar *arg_uri)
void ev_atril_window_call_sync_view (EvAtrilWindow *proxy, const gchar *arg_source_file, GVariant *arg_source_point, guint arg_timestamp, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean ev_atril_window_call_sync_view_finish (EvAtrilWindow *proxy, GAsyncResult *res, GError **error)
gboolean ev_atril_window_call_sync_view_sync (EvAtrilWindow *proxy, const gchar *arg_source_file, GVariant *arg_source_point, guint arg_timestamp, GCancellable *cancellable, GError **error)
void ev_atril_window_complete_sync_view (EvAtrilWindow *object G_GNUC_UNUSED, GDBusMethodInvocation *invocation)
G_DEFINE_TYPE_WITH_CODE (EvAtrilWindowProxy, ev_atril_window_proxy, G_TYPE_DBUS_PROXY, G_IMPLEMENT_INTERFACE(EV_TYPE_ATRIL_WINDOW, ev_atril_window_proxy_iface_init))
void ev_atril_window_proxy_new_for_bus (GBusType bus_type, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
EvAtrilWindow * ev_atril_window_proxy_new_for_bus_finish (GAsyncResult *res, GError **error)
EvAtrilWindow * ev_atril_window_proxy_new_for_bus_sync (GBusType bus_type, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GError **error)
G_DEFINE_TYPE_WITH_CODE (EvAtrilWindowSkeleton, ev_atril_window_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON, G_IMPLEMENT_INTERFACE(EV_TYPE_ATRIL_WINDOW, ev_atril_window_skeleton_iface_init))
EvAtrilWindow * ev_atril_window_skeleton_new (void)
EvAtrilApplication * ev_object_get_atril_application (EvObject *object)
EvAtrilWindow * ev_object_get_atril_window (EvObject *object)
EvAtrilApplication * ev_object_peek_atril_application (EvObject *object)
EvAtrilWindow * ev_object_peek_atril_window (EvObject *object)
G_DEFINE_TYPE_WITH_CODE (EvObjectProxy, ev_object_proxy, G_TYPE_DBUS_OBJECT_PROXY, G_IMPLEMENT_INTERFACE(G_TYPE_DBUS_OBJECT, ev_object_proxy__g_dbus_object_iface_init))
EvObjectProxy * ev_object_proxy_new (GDBusConnection *connection, const gchar *object_path)
G_DEFINE_TYPE_WITH_CODE (EvObjectSkeleton, ev_object_skeleton, G_TYPE_DBUS_OBJECT_SKELETON, G_IMPLEMENT_INTERFACE(G_TYPE_DBUS_OBJECT, ev_object_skeleton__g_dbus_object_iface_init))
EvObjectSkeleton * ev_object_skeleton_new (const gchar *object_path)
void ev_object_skeleton_set_atril_application (EvObjectSkeleton *object, EvAtrilApplication *interface_)
void ev_object_skeleton_set_atril_window (EvObjectSkeleton *object, EvAtrilWindow *interface_)
GType ev_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager G_GNUC_UNUSED, const gchar *object_path G_GNUC_UNUSED, const gchar *interface_name, gpointer user_data G_GNUC_UNUSED)
void ev_object_manager_client_new_for_bus (GBusType bus_type, GDBusObjectManagerClientFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
GDBusObjectManager * ev_object_manager_client_new_for_bus_finish (GAsyncResult *res, GError **error)
GDBusObjectManager * ev_object_manager_client_new_for_bus_sync (GBusType bus_type, GDBusObjectManagerClientFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GError **error)
Macro Definition Documentation
g_marshal_value_peek_boolean
#define g_marshal_value_peek_boolean (v)
Value:
(v)->data[0].v_int
Definition at line 45 of file ev-gdbus-generated.c.
g_marshal_value_peek_boxed
#define g_marshal_value_peek_boxed (v)
Value:
(v)->data[0].v_pointer
Definition at line 60 of file ev-gdbus-generated.c.
g_marshal_value_peek_char
#define g_marshal_value_peek_char (v)
Value:
(v)->data[0].v_int
Definition at line 46 of file ev-gdbus-generated.c.
g_marshal_value_peek_double
#define g_marshal_value_peek_double (v)
Value:
(v)->data[0].v_double
Definition at line 57 of file ev-gdbus-generated.c.
g_marshal_value_peek_enum
#define g_marshal_value_peek_enum (v)
Value:
(v)->data[0].v_long
Definition at line 54 of file ev-gdbus-generated.c.
g_marshal_value_peek_flags
#define g_marshal_value_peek_flags (v)
Value:
(v)->data[0].v_ulong
Definition at line 55 of file ev-gdbus-generated.c.
g_marshal_value_peek_float
#define g_marshal_value_peek_float (v)
Value:
(v)->data[0].v_float
Definition at line 56 of file ev-gdbus-generated.c.
g_marshal_value_peek_int
#define g_marshal_value_peek_int (v)
Value:
(v)->data[0].v_int
Definition at line 48 of file ev-gdbus-generated.c.
g_marshal_value_peek_int64
#define g_marshal_value_peek_int64 (v)
Value:
(v)->data[0].v_int64
Definition at line 52 of file ev-gdbus-generated.c.
g_marshal_value_peek_long
#define g_marshal_value_peek_long (v)
Value:
(v)->data[0].v_long
Definition at line 50 of file ev-gdbus-generated.c.
g_marshal_value_peek_object
#define g_marshal_value_peek_object (v)
Value:
(v)->data[0].v_pointer
Definition at line 62 of file ev-gdbus-generated.c.
g_marshal_value_peek_param
#define g_marshal_value_peek_param (v)
Value:
(v)->data[0].v_pointer
Definition at line 59 of file ev-gdbus-generated.c.
g_marshal_value_peek_pointer
#define g_marshal_value_peek_pointer (v)
Value:
(v)->data[0].v_pointer
Definition at line 61 of file ev-gdbus-generated.c.
g_marshal_value_peek_string
#define g_marshal_value_peek_string (v)
Value:
(v)->data[0].v_pointer
Definition at line 58 of file ev-gdbus-generated.c.
g_marshal_value_peek_uchar
#define g_marshal_value_peek_uchar (v)
Value:
(v)->data[0].v_uint
Definition at line 47 of file ev-gdbus-generated.c.
g_marshal_value_peek_uint
#define g_marshal_value_peek_uint (v)
Value:
(v)->data[0].v_uint
Definition at line 49 of file ev-gdbus-generated.c.
g_marshal_value_peek_uint64
#define g_marshal_value_peek_uint64 (v)
Value:
(v)->data[0].v_uint64
Definition at line 53 of file ev-gdbus-generated.c.
g_marshal_value_peek_ulong
#define g_marshal_value_peek_ulong (v)
Value:
(v)->data[0].v_ulong
Definition at line 51 of file ev-gdbus-generated.c.
g_marshal_value_peek_variant
#define g_marshal_value_peek_variant (v)
Value:
(v)->data[0].v_pointer
Definition at line 63 of file ev-gdbus-generated.c.
Typedef Documentation
EvAtrilApplicationInterface
typedef EvAtrilApplicationIface EvAtrilApplicationInterface
EvAtrilApplication:
Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-mate-atril-Application.top_of_page">org.mate.atril.Application</link>. EvAtrilApplicationIface: @parent_iface: The parent interface. @handle_get_window_list: Handler for the #EvAtrilApplication::handle-get-window-list signal. @handle_reload: Handler for the #EvAtrilApplication::handle-reload signal.
Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-mate-atril-Application.top_of_page">org.mate.atril.Application</link>.
Definition at line 561 of file ev-gdbus-generated.c.
EvAtrilWindowInterface
typedef EvAtrilWindowIface EvAtrilWindowInterface
EvAtrilWindow:
Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-mate-atril-Window.top_of_page">org.mate.atril.Window</link>. EvAtrilWindowIface: @parent_iface: The parent interface. @handle_sync_view: Handler for the #EvAtrilWindow::handle-sync-view signal. @closed: Handler for the #EvAtrilWindow::closed signal. @document_loaded: Handler for the #EvAtrilWindow::document-loaded signal. @sync_source: Handler for the #EvAtrilWindow::sync-source signal.
Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-mate-atril-Window.top_of_page">org.mate.atril.Window</link>.
Definition at line 1783 of file ev-gdbus-generated.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
SECTION:EvAtrilWindow @title: EvAtrilWindow @short_description: Generated C code for the org.mate.atril.Window D-Bus interface
This section contains code for working with the <link linkend="gdbus-interface-org-mate-atril-Window.top_of_page">org.mate.atril.Window</link> D-Bus interface in C.
Enumerator
EV__ATRIL_WINDOW_SYNC_SOURCE
EV__ATRIL_WINDOW_CLOSED
EV__ATRIL_WINDOW_DOCUMENT_LOADED
Definition at line 1499 of file ev-gdbus-generated.c.
Function Documentation
ev_atril_application_call_get_window_list()
void ev_atril_application_call_get_window_list (EvAtrilApplication * proxy, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
ev_atril_application_call_get_window_list: @proxy: A EvAtrilApplicationProxy. @cancellable: (nullable): A #GCancellable or NULL. @callback: A #GAsyncReadyCallback to call when the request is satisfied or NULL. @user_data: User data to pass to @callback.
Asynchronously invokes the <link linkend="gdbus-method-org-mate-atril-Application.GetWindowList">GetWindowList()</link> D-Bus method on @proxy. When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()). You can then call ev_atril_application_call_get_window_list_finish() to get the result of the operation.
See ev_atril_application_call_get_window_list_sync() for the synchronous, blocking version of this method.
Definition at line 734 of file ev-gdbus-generated.c.
References proxy, and user_data.
ev_atril_application_call_get_window_list_finish()
gboolean ev_atril_application_call_get_window_list_finish (EvAtrilApplication * proxy, gchar *** out_window_list, GAsyncResult * res, GError ** error)
ev_atril_application_call_get_window_list_finish: @proxy: A EvAtrilApplicationProxy. @out_window_list: (out) (optional) (array zero-terminated=1): Return location for return parameter or NULL to ignore. @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_atril_application_call_get_window_list(). @error: Return location for error or NULL.
Finishes an operation started with ev_atril_application_call_get_window_list().
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 762 of file ev-gdbus-generated.c.
References error, NULL, and proxy.
ev_atril_application_call_get_window_list_sync()
gboolean ev_atril_application_call_get_window_list_sync (EvAtrilApplication * proxy, gchar *** out_window_list, GCancellable * cancellable, GError ** error)
ev_atril_application_call_get_window_list_sync: @proxy: A EvAtrilApplicationProxy. @out_window_list: (out) (optional) (array zero-terminated=1): Return location for return parameter or NULL to ignore. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL.
Synchronously invokes the <link linkend="gdbus-method-org-mate-atril-Application.GetWindowList">GetWindowList()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
See ev_atril_application_call_get_window_list() for the asynchronous version of this method.
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 794 of file ev-gdbus-generated.c.
References error, NULL, and proxy.
ev_atril_application_call_reload()
void ev_atril_application_call_reload (EvAtrilApplication * proxy, GVariant * arg_args, guint arg_timestamp, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
ev_atril_application_call_reload: @proxy: A EvAtrilApplicationProxy. @arg_args: Argument to pass with the method invocation. @arg_timestamp: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @callback: A #GAsyncReadyCallback to call when the request is satisfied or NULL. @user_data: User data to pass to @callback.
Asynchronously invokes the <link linkend="gdbus-method-org-mate-atril-Application.Reload">Reload()</link> D-Bus method on @proxy. When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()). You can then call ev_atril_application_call_reload_finish() to get the result of the operation.
See ev_atril_application_call_reload_sync() for the synchronous, blocking version of this method.
Definition at line 632 of file ev-gdbus-generated.c.
References proxy, and user_data.
ev_atril_application_call_reload_finish()
gboolean ev_atril_application_call_reload_finish (EvAtrilApplication * proxy, GAsyncResult * res, GError ** error)
ev_atril_application_call_reload_finish: @proxy: A EvAtrilApplicationProxy. @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_atril_application_call_reload(). @error: Return location for error or NULL.
Finishes an operation started with ev_atril_application_call_reload().
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 663 of file ev-gdbus-generated.c.
References error, NULL, and proxy.
ev_atril_application_call_reload_sync()
gboolean ev_atril_application_call_reload_sync (EvAtrilApplication * proxy, GVariant * arg_args, guint arg_timestamp, GCancellable * cancellable, GError ** error)
ev_atril_application_call_reload_sync: @proxy: A EvAtrilApplicationProxy. @arg_args: Argument to pass with the method invocation. @arg_timestamp: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL.
Synchronously invokes the <link linkend="gdbus-method-org-mate-atril-Application.Reload">Reload()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
See ev_atril_application_call_reload() for the asynchronous version of this method.
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 694 of file ev-gdbus-generated.c.
References error, NULL, and proxy.
ev_atril_application_complete_get_window_list()
void ev_atril_application_complete_get_window_list (EvAtrilApplication *object G_GNUC_UNUSED, GDBusMethodInvocation * invocation, const gchar *const * window_list)
ev_atril_application_complete_get_window_list: @object: A EvAtrilApplication. @invocation: (transfer full): A #GDBusMethodInvocation. @window_list: Parameter to return.
Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-mate-atril-Application.GetWindowList">GetWindowList()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
This method will free @invocation, you cannot use it afterwards.
Definition at line 847 of file ev-gdbus-generated.c.
ev_atril_application_complete_reload()
void ev_atril_application_complete_reload (EvAtrilApplication *object G_GNUC_UNUSED, GDBusMethodInvocation * invocation)
ev_atril_application_complete_reload: @object: A EvAtrilApplication. @invocation: (transfer full): A #GDBusMethodInvocation.
Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-mate-atril-Application.Reload">Reload()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
This method will free @invocation, you cannot use it afterwards.
Definition at line 828 of file ev-gdbus-generated.c.
ev_atril_application_interface_info()
GDBusInterfaceInfo * ev_atril_application_interface_info (void)
ev_atril_application_interface_info:
Gets a machine-readable description of the <link linkend="gdbus-interface-org-mate-atril-Application.top_of_page">org.mate.atril.Application</link> D-Bus interface.
Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
Definition at line 497 of file ev-gdbus-generated.c.
ev_atril_application_override_properties()
guint ev_atril_application_override_properties (GObjectClass *klass G_GNUC_UNUSED, guint property_id_begin)
ev_atril_application_override_properties: @klass: The class structure for a #GObject derived class. @property_id_begin: The property id to assign to the first overridden property.
Overrides all #GObject properties in the EvAtrilApplication interface for a concrete class. The properties are overridden in the order they are defined.
Returns: The last property id.
Definition at line 513 of file ev-gdbus-generated.c.
ev_atril_application_proxy_new()
void ev_atril_application_proxy_new (GDBusConnection * connection, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 1038 of file ev-gdbus-generated.c.
References connection, EV_TYPE_ATRIL_APPLICATION_PROXY, name, NULL, and user_data.
ev_atril_application_proxy_new_finish()
EvAtrilApplication * ev_atril_application_proxy_new_finish (GAsyncResult * res, GError ** error)
ev_atril_application_proxy_new_finish: @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_atril_application_proxy_new(). @error: Return location for error or NULL
Finishes an operation started with ev_atril_application_proxy_new().
Returns: (transfer full) (type EvAtrilApplicationProxy): The constructed proxy object or NULL if @error is set.
Definition at line 1060 of file ev-gdbus-generated.c.
References error, EV_ATRIL_APPLICATION, and NULL.
ev_atril_application_proxy_new_for_bus()
void ev_atril_application_proxy_new_for_bus (GBusType bus_type, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 1128 of file ev-gdbus-generated.c.
References EV_TYPE_ATRIL_APPLICATION_PROXY, name, NULL, and user_data.
ev_atril_application_proxy_new_for_bus_finish()
EvAtrilApplication * ev_atril_application_proxy_new_for_bus_finish (GAsyncResult * res, GError ** error)
ev_atril_application_proxy_new_for_bus_finish: @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_atril_application_proxy_new_for_bus(). @error: Return location for error or NULL
Finishes an operation started with ev_atril_application_proxy_new_for_bus().
Returns: (transfer full) (type EvAtrilApplicationProxy): The constructed proxy object or NULL if @error is set.
Definition at line 1150 of file ev-gdbus-generated.c.
References error, EV_ATRIL_APPLICATION, and NULL.
ev_atril_application_proxy_new_for_bus_sync()
EvAtrilApplication * ev_atril_application_proxy_new_for_bus_sync (GBusType bus_type, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GError ** error)
Definition at line 1183 of file ev-gdbus-generated.c.
References error, EV_ATRIL_APPLICATION, EV_TYPE_ATRIL_APPLICATION_PROXY, name, and NULL.
ev_atril_application_proxy_new_sync()
EvAtrilApplication * ev_atril_application_proxy_new_sync (GDBusConnection * connection, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GError ** error)
Definition at line 1093 of file ev-gdbus-generated.c.
References connection, error, EV_ATRIL_APPLICATION, EV_TYPE_ATRIL_APPLICATION_PROXY, name, and NULL.
ev_atril_application_skeleton_new()
EvAtrilApplication * ev_atril_application_skeleton_new (void)
ev_atril_application_skeleton_new:
Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-mate-atril-Application.top_of_page">org.mate.atril.Application</link>.
Returns: (transfer full) (type EvAtrilApplicationSkeleton): The skeleton object.
Definition at line 1481 of file ev-gdbus-generated.c.
References EV_ATRIL_APPLICATION, EV_TYPE_ATRIL_APPLICATION_SKELETON, and NULL.
ev_atril_window_call_sync_view()
void ev_atril_window_call_sync_view (EvAtrilWindow * proxy, const gchar * arg_source_file, GVariant * arg_source_point, guint arg_timestamp, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
ev_atril_window_call_sync_view: @proxy: A EvAtrilWindowProxy. @arg_source_file: Argument to pass with the method invocation. @arg_source_point: Argument to pass with the method invocation. @arg_timestamp: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @callback: A #GAsyncReadyCallback to call when the request is satisfied or NULL. @user_data: User data to pass to @callback.
Asynchronously invokes the <link linkend="gdbus-method-org-mate-atril-Window.SyncView">SyncView()</link> D-Bus method on @proxy. When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()). You can then call ev_atril_window_call_sync_view_finish() to get the result of the operation.
See ev_atril_window_call_sync_view_sync() for the synchronous, blocking version of this method.
Definition at line 1943 of file ev-gdbus-generated.c.
References proxy, and user_data.
ev_atril_window_call_sync_view_finish()
gboolean ev_atril_window_call_sync_view_finish (EvAtrilWindow * proxy, GAsyncResult * res, GError ** error)
ev_atril_window_call_sync_view_finish: @proxy: A EvAtrilWindowProxy. @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_atril_window_call_sync_view(). @error: Return location for error or NULL.
Finishes an operation started with ev_atril_window_call_sync_view().
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 1976 of file ev-gdbus-generated.c.
References error, NULL, and proxy.
ev_atril_window_call_sync_view_sync()
gboolean ev_atril_window_call_sync_view_sync (EvAtrilWindow * proxy, const gchar * arg_source_file, GVariant * arg_source_point, guint arg_timestamp, GCancellable * cancellable, GError ** error)
ev_atril_window_call_sync_view_sync: @proxy: A EvAtrilWindowProxy. @arg_source_file: Argument to pass with the method invocation. @arg_source_point: Argument to pass with the method invocation. @arg_timestamp: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL.
Synchronously invokes the <link linkend="gdbus-method-org-mate-atril-Window.SyncView">SyncView()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
See ev_atril_window_call_sync_view() for the asynchronous version of this method.
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 2008 of file ev-gdbus-generated.c.
References error, NULL, and proxy.
ev_atril_window_complete_sync_view()
void ev_atril_window_complete_sync_view (EvAtrilWindow *object G_GNUC_UNUSED, GDBusMethodInvocation * invocation)
ev_atril_window_complete_sync_view: @object: A EvAtrilWindow. @invocation: (transfer full): A #GDBusMethodInvocation.
Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-mate-atril-Window.SyncView">SyncView()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
This method will free @invocation, you cannot use it afterwards.
Definition at line 2046 of file ev-gdbus-generated.c.
ev_atril_window_emit_closed()
void ev_atril_window_emit_closed (EvAtrilWindow * object)
ev_atril_window_emit_closed: @object: A EvAtrilWindow.
Emits the <link linkend="gdbus-signal-org-mate-atril-Window.Closed">"Closed"</link> D-Bus signal.
Definition at line 1905 of file ev-gdbus-generated.c.
References EV__ATRIL_WINDOW_CLOSED.
ev_atril_window_emit_document_loaded()
void ev_atril_window_emit_document_loaded (EvAtrilWindow * object, const gchar * arg_uri)
ev_atril_window_emit_document_loaded: @object: A EvAtrilWindow. @arg_uri: Argument to pass with the signal.
Emits the <link linkend="gdbus-signal-org-mate-atril-Window.DocumentLoaded">"DocumentLoaded"</link> D-Bus signal.
Definition at line 1919 of file ev-gdbus-generated.c.
References EV__ATRIL_WINDOW_DOCUMENT_LOADED.
ev_atril_window_emit_sync_source()
void ev_atril_window_emit_sync_source (EvAtrilWindow * object, const gchar * arg_source_file, GVariant * arg_source_point, guint arg_timestamp)
ev_atril_window_emit_sync_source: @object: A EvAtrilWindow. @arg_source_file: Argument to pass with the signal. @arg_source_point: Argument to pass with the signal. @arg_timestamp: Argument to pass with the signal.
Emits the <link linkend="gdbus-signal-org-mate-atril-Window.SyncSource">"SyncSource"</link> D-Bus signal.
Definition at line 1889 of file ev-gdbus-generated.c.
References EV__ATRIL_WINDOW_SYNC_SOURCE.
ev_atril_window_interface_info()
GDBusInterfaceInfo * ev_atril_window_interface_info (void)
ev_atril_window_interface_info:
Gets a machine-readable description of the <link linkend="gdbus-interface-org-mate-atril-Window.top_of_page">org.mate.atril.Window</link> D-Bus interface.
Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
Definition at line 1691 of file ev-gdbus-generated.c.
ev_atril_window_override_properties()
guint ev_atril_window_override_properties (GObjectClass *klass G_GNUC_UNUSED, guint property_id_begin)
ev_atril_window_override_properties: @klass: The class structure for a #GObject derived class. @property_id_begin: The property id to assign to the first overridden property.
Overrides all #GObject properties in the EvAtrilWindow interface for a concrete class. The properties are overridden in the order they are defined.
Returns: The last property id.
Definition at line 1707 of file ev-gdbus-generated.c.
ev_atril_window_proxy_new()
void ev_atril_window_proxy_new (GDBusConnection * connection, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 2235 of file ev-gdbus-generated.c.
References connection, EV_TYPE_ATRIL_WINDOW_PROXY, name, NULL, and user_data.
ev_atril_window_proxy_new_finish()
EvAtrilWindow * ev_atril_window_proxy_new_finish (GAsyncResult * res, GError ** error)
ev_atril_window_proxy_new_finish: @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_atril_window_proxy_new(). @error: Return location for error or NULL
Finishes an operation started with ev_atril_window_proxy_new().
Returns: (transfer full) (type EvAtrilWindowProxy): The constructed proxy object or NULL if @error is set.
Definition at line 2257 of file ev-gdbus-generated.c.
References error, EV_ATRIL_WINDOW, and NULL.
ev_atril_window_proxy_new_for_bus()
void ev_atril_window_proxy_new_for_bus (GBusType bus_type, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 2325 of file ev-gdbus-generated.c.
References EV_TYPE_ATRIL_WINDOW_PROXY, name, NULL, and user_data.
ev_atril_window_proxy_new_for_bus_finish()
EvAtrilWindow * ev_atril_window_proxy_new_for_bus_finish (GAsyncResult * res, GError ** error)
ev_atril_window_proxy_new_for_bus_finish: @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_atril_window_proxy_new_for_bus(). @error: Return location for error or NULL
Finishes an operation started with ev_atril_window_proxy_new_for_bus().
Returns: (transfer full) (type EvAtrilWindowProxy): The constructed proxy object or NULL if @error is set.
Definition at line 2347 of file ev-gdbus-generated.c.
References error, EV_ATRIL_WINDOW, and NULL.
ev_atril_window_proxy_new_for_bus_sync()
EvAtrilWindow * ev_atril_window_proxy_new_for_bus_sync (GBusType bus_type, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GError ** error)
Definition at line 2380 of file ev-gdbus-generated.c.
References error, EV_ATRIL_WINDOW, EV_TYPE_ATRIL_WINDOW_PROXY, name, and NULL.
ev_atril_window_proxy_new_sync()
EvAtrilWindow * ev_atril_window_proxy_new_sync (GDBusConnection * connection, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GError ** error)
Definition at line 2290 of file ev-gdbus-generated.c.
References connection, error, EV_ATRIL_WINDOW, EV_TYPE_ATRIL_WINDOW_PROXY, name, and NULL.
ev_atril_window_skeleton_new()
EvAtrilWindow * ev_atril_window_skeleton_new (void)
ev_atril_window_skeleton_new:
Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-mate-atril-Window.top_of_page">org.mate.atril.Window</link>.
Returns: (transfer full) (type EvAtrilWindowSkeleton): The skeleton object.
Definition at line 2755 of file ev-gdbus-generated.c.
References EV_ATRIL_WINDOW, EV_TYPE_ATRIL_WINDOW_SKELETON, and NULL.
ev_object_get_atril_application()
EvAtrilApplication * ev_object_get_atril_application (EvObject * object)
ev_object_get_atril_application: @object: A EvObject.
Gets the EvAtrilApplication instance for the D-Bus interface <link linkend="gdbus-interface-org-mate-atril-Application.top_of_page">org.mate.atril.Application</link> on @object, if any.
Returns: (transfer full) (nullable): A EvAtrilApplication that must be freed with g_object_unref() or NULL if @object does not implement the interface.
Definition at line 2820 of file ev-gdbus-generated.c.
References EV_ATRIL_APPLICATION, and NULL.
ev_object_get_atril_window()
EvAtrilWindow * ev_object_get_atril_window (EvObject * object)
ev_object_get_atril_window: @object: A EvObject.
Gets the EvAtrilWindow instance for the D-Bus interface <link linkend="gdbus-interface-org-mate-atril-Window.top_of_page">org.mate.atril.Window</link> on @object, if any.
Returns: (transfer full) (nullable): A EvAtrilWindow that must be freed with g_object_unref() or NULL if @object does not implement the interface.
Definition at line 2837 of file ev-gdbus-generated.c.
References EV_ATRIL_WINDOW, and NULL.
ev_object_manager_client_get_proxy_type()
GType ev_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager G_GNUC_UNUSED, const gchar *object_path G_GNUC_UNUSED, const gchar * interface_name, gpointer user_data G_GNUC_UNUSED)
ev_object_manager_client_get_proxy_type: @manager: A #GDBusObjectManagerClient. @object_path: The object path of the remote object (unused). @interface_name: (nullable): Interface name of the remote object or NULL to get the object proxy #GType. @user_data: User data (unused).
A #GDBusProxyTypeFunc that maps @interface_name to the generated #GDBusObjectProxy derived and #GDBusProxy derived types.
Returns: A #GDBusProxy derived #GType if @interface_name is not NULL, otherwise the #GType for EvObjectProxy.
Definition at line 3207 of file ev-gdbus-generated.c.
References EV_TYPE_ATRIL_APPLICATION_PROXY, EV_TYPE_ATRIL_WINDOW_PROXY, EV_TYPE_OBJECT_PROXY, NULL, and user_data.
ev_object_manager_client_new()
void ev_object_manager_client_new (GDBusConnection * connection, GDBusObjectManagerClientFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 3246 of file ev-gdbus-generated.c.
References connection, ev_object_manager_client_get_proxy_type(), EV_TYPE_OBJECT_MANAGER_CLIENT, name, NULL, and user_data.
ev_object_manager_client_new_finish()
GDBusObjectManager * ev_object_manager_client_new_finish (GAsyncResult * res, GError ** error)
ev_object_manager_client_new_finish: @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_object_manager_client_new(). @error: Return location for error or NULL
Finishes an operation started with ev_object_manager_client_new().
Returns: (transfer full) (type EvObjectManagerClient): The constructed object manager client or NULL if @error is set.
Definition at line 3268 of file ev-gdbus-generated.c.
References error, and NULL.
ev_object_manager_client_new_for_bus()
void ev_object_manager_client_new_for_bus (GBusType bus_type, GDBusObjectManagerClientFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 3336 of file ev-gdbus-generated.c.
References ev_object_manager_client_get_proxy_type(), EV_TYPE_OBJECT_MANAGER_CLIENT, name, NULL, and user_data.
ev_object_manager_client_new_for_bus_finish()
GDBusObjectManager * ev_object_manager_client_new_for_bus_finish (GAsyncResult * res, GError ** error)
ev_object_manager_client_new_for_bus_finish: @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_object_manager_client_new_for_bus(). @error: Return location for error or NULL
Finishes an operation started with ev_object_manager_client_new_for_bus().
Returns: (transfer full) (type EvObjectManagerClient): The constructed object manager client or NULL if @error is set.
Definition at line 3358 of file ev-gdbus-generated.c.
References error, and NULL.
ev_object_manager_client_new_for_bus_sync()
GDBusObjectManager * ev_object_manager_client_new_for_bus_sync (GBusType bus_type, GDBusObjectManagerClientFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GError ** error)
Definition at line 3391 of file ev-gdbus-generated.c.
References error, ev_object_manager_client_get_proxy_type(), EV_TYPE_OBJECT_MANAGER_CLIENT, name, and NULL.
ev_object_manager_client_new_sync()
GDBusObjectManager * ev_object_manager_client_new_sync (GDBusConnection * connection, GDBusObjectManagerClientFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GError ** error)
Definition at line 3301 of file ev-gdbus-generated.c.
References connection, error, ev_object_manager_client_get_proxy_type(), EV_TYPE_OBJECT_MANAGER_CLIENT, name, and NULL.
ev_object_peek_atril_application()
EvAtrilApplication * ev_object_peek_atril_application (EvObject * object)
ev_object_peek_atril_application: (skip) @object: A EvObject.
Like ev_object_get_atril_application() but doesn't increase the reference count on the returned object.
It is not safe to use the returned object if you are on another thread than the one where the #GDBusObjectManagerClient or #GDBusObjectManagerServer for @object is running.
Returns: (transfer none) (nullable): A EvAtrilApplication or NULL if @object does not implement the interface. Do not free the returned object, it is owned by @object.
Definition at line 2857 of file ev-gdbus-generated.c.
References EV_ATRIL_APPLICATION, and NULL.
ev_object_peek_atril_window()
EvAtrilWindow * ev_object_peek_atril_window (EvObject * object)
ev_object_peek_atril_window: (skip) @object: A EvObject.
Like ev_object_get_atril_window() but doesn't increase the reference count on the returned object.
It is not safe to use the returned object if you are on another thread than the one where the #GDBusObjectManagerClient or #GDBusObjectManagerServer for @object is running.
Returns: (transfer none) (nullable): A EvAtrilWindow or NULL if @object does not implement the interface. Do not free the returned object, it is owned by @object.
Definition at line 2877 of file ev-gdbus-generated.c.
References EV_ATRIL_WINDOW, and NULL.
ev_object_proxy_new()
EvObjectProxy * ev_object_proxy_new (GDBusConnection * connection, const gchar * object_path)
ev_object_proxy_new: @connection: A #GDBusConnection. @object_path: An object path.
Creates a new proxy object.
Returns: (transfer full): The proxy object.
Definition at line 2992 of file ev-gdbus-generated.c.
References connection, EV_OBJECT_PROXY, EV_TYPE_OBJECT_PROXY, and NULL.
ev_object_skeleton_new()
EvObjectSkeleton * ev_object_skeleton_new (const gchar * object_path)
ev_object_skeleton_new: @object_path: An object path.
Creates a new skeleton object.
Returns: (transfer full): The skeleton object.
Definition at line 3126 of file ev-gdbus-generated.c.
References EV_OBJECT_SKELETON, EV_TYPE_OBJECT_SKELETON, and NULL.
ev_object_skeleton_set_atril_application()
void ev_object_skeleton_set_atril_application (EvObjectSkeleton * object, EvAtrilApplication * interface_)
ev_object_skeleton_set_atril_application: @object: A EvObjectSkeleton. @interface_: (nullable): A EvAtrilApplication or NULL to clear the interface.
Sets the EvAtrilApplication instance for the D-Bus interface <link linkend="gdbus-interface-org-mate-atril-Application.top_of_page">org.mate.atril.Application</link> on @object.
Definition at line 3139 of file ev-gdbus-generated.c.
References NULL.
ev_object_skeleton_set_atril_window()
void ev_object_skeleton_set_atril_window (EvObjectSkeleton * object, EvAtrilWindow * interface_)
ev_object_skeleton_set_atril_window: @object: A EvObjectSkeleton. @interface_: (nullable): A EvAtrilWindow or NULL to clear the interface.
Sets the EvAtrilWindow instance for the D-Bus interface <link linkend="gdbus-interface-org-mate-atril-Window.top_of_page">org.mate.atril.Window</link> on @object.
Definition at line 3151 of file ev-gdbus-generated.c.
References NULL.
G_DEFINE_TYPE_WITH_CODE() [1/6]
G_DEFINE_TYPE_WITH_CODE (EvAtrilApplicationProxy , ev_atril_application_proxy , G_TYPE_DBUS_PROXY , G_IMPLEMENT_INTERFACE(EV_TYPE_ATRIL_APPLICATION, ev_atril_application_proxy_iface_init))
Definition at line 880 of file ev-gdbus-generated.c.
References EV_ATRIL_APPLICATION_PROXY, EV_TYPE_ATRIL_APPLICATION, G_OBJECT_CLASS(), and proxy.
G_DEFINE_TYPE_WITH_CODE() [2/6]
G_DEFINE_TYPE_WITH_CODE (EvAtrilApplicationSkeleton , ev_atril_application_skeleton , G_TYPE_DBUS_INTERFACE_SKELETON , G_IMPLEMENT_INTERFACE(EV_TYPE_ATRIL_APPLICATION, ev_atril_application_skeleton_iface_init))
Definition at line 1414 of file ev-gdbus-generated.c.
References EV_ATRIL_APPLICATION_SKELETON, EV_TYPE_ATRIL_APPLICATION, G_OBJECT_CLASS(), NULL, and _EvAtrilApplicationSkeleton::priv.
G_DEFINE_TYPE_WITH_CODE() [3/6]
G_DEFINE_TYPE_WITH_CODE (EvAtrilWindowProxy , ev_atril_window_proxy , G_TYPE_DBUS_PROXY , G_IMPLEMENT_INTERFACE(EV_TYPE_ATRIL_WINDOW, ev_atril_window_proxy_iface_init))
Definition at line 2077 of file ev-gdbus-generated.c.
References EV_ATRIL_WINDOW_PROXY, EV_TYPE_ATRIL_WINDOW, G_OBJECT_CLASS(), and proxy.
G_DEFINE_TYPE_WITH_CODE() [4/6]
G_DEFINE_TYPE_WITH_CODE (EvAtrilWindowSkeleton , ev_atril_window_skeleton , G_TYPE_DBUS_INTERFACE_SKELETON , G_IMPLEMENT_INTERFACE(EV_TYPE_ATRIL_WINDOW, ev_atril_window_skeleton_iface_init))
Definition at line 2685 of file ev-gdbus-generated.c.
References EV_ATRIL_WINDOW_SKELETON, EV_TYPE_ATRIL_WINDOW, G_OBJECT_CLASS(), NULL, and _EvAtrilWindowSkeleton::priv.
G_DEFINE_TYPE_WITH_CODE() [5/6]
G_DEFINE_TYPE_WITH_CODE (EvObjectProxy , ev_object_proxy , G_TYPE_DBUS_OBJECT_PROXY , G_IMPLEMENT_INTERFACE(G_TYPE_DBUS_OBJECT, ev_object_proxy__g_dbus_object_iface_init))
Definition at line 2925 of file ev-gdbus-generated.c.
References EV_TYPE_OBJECT.
G_DEFINE_TYPE_WITH_CODE() [6/6]
G_DEFINE_TYPE_WITH_CODE (EvObjectSkeleton , ev_object_skeleton , G_TYPE_DBUS_OBJECT_SKELETON , G_IMPLEMENT_INTERFACE(G_TYPE_DBUS_OBJECT, ev_object_skeleton__g_dbus_object_iface_init))
Definition at line 3026 of file ev-gdbus-generated.c.
References EV_TYPE_OBJECT.