MATE Desktop Environment: ev-init.h File Reference
ev-init.h File Reference
#include <glib.h>
Functions
const gchar * ev_get_locale_dir (void)
gboolean ev_init (void)
void ev_shutdown (void)
gboolean _ev_is_initialized (void)
Function Documentation
_ev_is_initialized()
gboolean _ev_is_initialized (void)
Definition at line 87 of file ev-init.c.
Referenced by ev_shutdown().
ev_get_locale_dir()
const gchar * ev_get_locale_dir (void)
Definition at line 33 of file ev-init.c.
References MATELOCALEDIR.
Referenced by main(), and main().
ev_init()
gboolean ev_init (void)
ev_init:
Initializes the atril document library.
You must call this before calling any other function in the atril document library.
Returns: TRUE if any backends were found; FALSE otherwise
Definition at line 49 of file ev-init.c.
References _ev_backends_manager_init(), _ev_debug_init, and _ev_file_helpers_init().
Referenced by caja_module_initialize(), main(), and main().
ev_shutdown()
void ev_shutdown (void)
ev_shutdown:
Shuts the atril document library down.
Definition at line 69 of file ev-init.c.
References _ev_backends_manager_shutdown(), _ev_debug_shutdown, _ev_file_helpers_shutdown(), and _ev_is_initialized().
Referenced by caja_module_shutdown(), main(), and main().