MATE Desktop Environment: ev-job-scheduler.c File Reference
ev-job-scheduler.c File Reference
#include "ev-debug.h"
#include "ev-job-scheduler.h"
Typedefs
typedef struct _EvSchedulerJob EvSchedulerJob
Functions
G_LOCK_DEFINE_STATIC (job_list)
void ev_job_scheduler_push_job (EvJob *job, EvJobPriority priority)
void ev_job_scheduler_update_job (EvJob *job, EvJobPriority priority)
EvJob * ev_job_scheduler_get_running_thread_job (void)
Typedef Documentation
EvSchedulerJob
typedef struct _EvSchedulerJob EvSchedulerJob
Function Documentation
ev_job_scheduler_get_running_thread_job()
EvJob * ev_job_scheduler_get_running_thread_job (void)
ev_job_scheduler_get_running_thread_job:
Returns: (transfer none): an EvJob
Definition at line 316 of file ev-job-scheduler.c.
ev_job_scheduler_push_job()
void ev_job_scheduler_push_job (EvJob * job, EvJobPriority priority)
Definition at line 225 of file ev-job-scheduler.c.
References DEBUG_JOBS, EV_GET_TYPE_NAME, ev_job_get_run_mode(), EV_JOB_RUN_MAIN_LOOP, EV_JOB_RUN_THREAD, and NULL.
Referenced by ev_properties_fonts_set_document(), and ev_window_open_uri().
ev_job_scheduler_update_job()
void ev_job_scheduler_update_job (EvJob * job, EvJobPriority priority)
Definition at line 266 of file ev-job-scheduler.c.
References DEBUG_JOBS, EV_GET_TYPE_NAME, ev_job_get_run_mode(), EV_JOB_RUN_MAIN_LOOP, FALSE, and NULL.
G_LOCK_DEFINE_STATIC()
G_LOCK_DEFINE_STATIC (job_list)
References data, EV_JOB_N_PRIORITIES, and NULL.