MATE Desktop Environment: ev-link-dest.c File Reference
ev-link-dest.c File Reference
#include <config.h>
#include "ev-link-dest.h"
#include "ev-document-type-builtins.h"
Enumerations
enum {
PROP_0 , PROP_TYPE , PROP_PAGE , PROP_LEFT ,
PROP_TOP , PROP_BOTTOM , PROP_RIGHT , PROP_ZOOM ,
PROP_CHANGE , PROP_NAMED , PROP_PAGE_LABEL
}
enum EvDestChange { EV_DEST_CHANGE_TOP = 1 << 0 , EV_DEST_CHANGE_LEFT = 1 << 1 , EV_DEST_CHANGE_ZOOM = 1 << 2 }
Functions
EvLinkDestType ev_link_dest_get_dest_type (EvLinkDest *self)
gint ev_link_dest_get_page (EvLinkDest *self)
gdouble ev_link_dest_get_top (EvLinkDest *self, gboolean *change_top)
gdouble ev_link_dest_get_left (EvLinkDest *self, gboolean *change_left)
gdouble ev_link_dest_get_bottom (EvLinkDest *self)
gdouble ev_link_dest_get_right (EvLinkDest *self)
gdouble ev_link_dest_get_zoom (EvLinkDest *self, gboolean *change_zoom)
const gchar * ev_link_dest_get_named_dest (EvLinkDest *self)
const gchar * ev_link_dest_get_page_label (EvLinkDest *self)
EvLinkDest * ev_link_dest_new_page (gint page)
EvLinkDest * ev_link_dest_new_xyz (gint page, gdouble left, gdouble top, gdouble zoom, gboolean change_left, gboolean change_top, gboolean change_zoom)
EvLinkDest * ev_link_dest_new_fit (gint page)
EvLinkDest * ev_link_dest_new_fith (gint page, gdouble top, gboolean change_top)
EvLinkDest * ev_link_dest_new_fitv (gint page, gdouble left, gboolean change_left)
EvLinkDest * ev_link_dest_new_fitr (gint page, gdouble left, gdouble bottom, gdouble right, gdouble top)
EvLinkDest * ev_link_dest_new_named (const gchar *named_dest)
EvLinkDest * ev_link_dest_new_page_label (const gchar *page_label)
EvLinkDest * ev_link_dest_new_hlink (const gchar *hlink, gint page)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_TYPE
PROP_PAGE
PROP_LEFT
PROP_TOP
PROP_BOTTOM
PROP_RIGHT
PROP_ZOOM
PROP_CHANGE
PROP_NAMED
PROP_PAGE_LABEL
Definition at line 26 of file ev-link-dest.c.
EvDestChange
enum EvDestChange
Enumerator
EV_DEST_CHANGE_TOP
EV_DEST_CHANGE_LEFT
EV_DEST_CHANGE_ZOOM
Definition at line 40 of file ev-link-dest.c.
Function Documentation
ev_link_dest_get_bottom()
gdouble ev_link_dest_get_bottom (EvLinkDest * self)
Definition at line 112 of file ev-link-dest.c.
References EV_IS_LINK_DEST.
ev_link_dest_get_dest_type()
EvLinkDestType ev_link_dest_get_dest_type (EvLinkDest * self)
Definition at line 72 of file ev-link-dest.c.
References EV_IS_LINK_DEST.
Referenced by ev_document_links_get_dest_page(), and ev_document_links_get_dest_page_label().
ev_link_dest_get_left()
gdouble ev_link_dest_get_left (EvLinkDest * self, gboolean * change_left)
Definition at line 100 of file ev-link-dest.c.
References EV_DEST_CHANGE_LEFT, and EV_IS_LINK_DEST.
ev_link_dest_get_named_dest()
const gchar * ev_link_dest_get_named_dest (EvLinkDest * self)
Definition at line 140 of file ev-link-dest.c.
References EV_IS_LINK_DEST, and NULL.
Referenced by ev_document_links_get_dest_page().
ev_link_dest_get_page()
gint ev_link_dest_get_page (EvLinkDest * self)
Definition at line 80 of file ev-link-dest.c.
References EV_IS_LINK_DEST.
Referenced by ev_document_links_get_dest_page().
ev_link_dest_get_page_label()
const gchar * ev_link_dest_get_page_label (EvLinkDest * self)
Definition at line 148 of file ev-link-dest.c.
References EV_IS_LINK_DEST, and NULL.
Referenced by ev_document_links_get_dest_page(), and ev_document_links_get_dest_page_label().
ev_link_dest_get_right()
gdouble ev_link_dest_get_right (EvLinkDest * self)
Definition at line 120 of file ev-link-dest.c.
References EV_IS_LINK_DEST.
ev_link_dest_get_top()
gdouble ev_link_dest_get_top (EvLinkDest * self, gboolean * change_top)
Definition at line 88 of file ev-link-dest.c.
References EV_DEST_CHANGE_TOP, and EV_IS_LINK_DEST.
ev_link_dest_get_zoom()
gdouble ev_link_dest_get_zoom (EvLinkDest * self, gboolean * change_zoom)
Definition at line 128 of file ev-link-dest.c.
References EV_DEST_CHANGE_ZOOM, and EV_IS_LINK_DEST.
ev_link_dest_new_fit()
EvLinkDest * ev_link_dest_new_fit (gint page)
Definition at line 426 of file ev-link-dest.c.
References EV_LINK_DEST, EV_LINK_DEST_TYPE_FIT, EV_TYPE_LINK_DEST, and NULL.
ev_link_dest_new_fith()
EvLinkDest * ev_link_dest_new_fith (gint page, gdouble top, gboolean change_top)
Definition at line 435 of file ev-link-dest.c.
References EV_DEST_CHANGE_TOP, EV_LINK_DEST, EV_LINK_DEST_TYPE_FITH, EV_TYPE_LINK_DEST, and NULL.
ev_link_dest_new_fitr()
EvLinkDest * ev_link_dest_new_fitr (gint page, gdouble left, gdouble bottom, gdouble right, gdouble top)
Definition at line 471 of file ev-link-dest.c.
References EV_DEST_CHANGE_LEFT, EV_DEST_CHANGE_TOP, EV_LINK_DEST, EV_LINK_DEST_TYPE_FITR, EV_TYPE_LINK_DEST, and NULL.
ev_link_dest_new_fitv()
EvLinkDest * ev_link_dest_new_fitv (gint page, gdouble left, gboolean change_left)
Definition at line 453 of file ev-link-dest.c.
References EV_DEST_CHANGE_LEFT, EV_LINK_DEST, EV_LINK_DEST_TYPE_FITV, EV_TYPE_LINK_DEST, and NULL.
ev_link_dest_new_hlink()
EvLinkDest * ev_link_dest_new_hlink (const gchar * hlink, gint page)
Definition at line 509 of file ev-link-dest.c.
References EV_LINK_DEST, EV_LINK_DEST_TYPE_HLINK, EV_TYPE_LINK_DEST, and NULL.
ev_link_dest_new_named()
EvLinkDest * ev_link_dest_new_named (const gchar * named_dest)
Definition at line 491 of file ev-link-dest.c.
References EV_LINK_DEST, EV_LINK_DEST_TYPE_NAMED, EV_TYPE_LINK_DEST, and NULL.
ev_link_dest_new_page()
EvLinkDest * ev_link_dest_new_page (gint page)
Definition at line 389 of file ev-link-dest.c.
References EV_LINK_DEST, EV_LINK_DEST_TYPE_PAGE, EV_TYPE_LINK_DEST, and NULL.
ev_link_dest_new_page_label()
EvLinkDest * ev_link_dest_new_page_label (const gchar * page_label)
Definition at line 500 of file ev-link-dest.c.
References EV_LINK_DEST, EV_LINK_DEST_TYPE_PAGE_LABEL, EV_TYPE_LINK_DEST, and NULL.
ev_link_dest_new_xyz()
EvLinkDest * ev_link_dest_new_xyz (gint page, gdouble left, gdouble top, gdouble zoom, gboolean change_left, gboolean change_top, gboolean change_zoom)
Definition at line 398 of file ev-link-dest.c.
References EV_DEST_CHANGE_LEFT, EV_DEST_CHANGE_TOP, EV_DEST_CHANGE_ZOOM, EV_LINK_DEST, EV_LINK_DEST_TYPE_XYZ, EV_TYPE_LINK_DEST, and NULL.