MATE Desktop Environment: ev-link-action.c File Reference
ev-link-action.c File Reference
#include <config.h>
#include "ev-link-action.h"
#include "ev-document-type-builtins.h"
Enumerations
enum {
PROP_0 , PROP_TYPE , PROP_DEST , PROP_URI ,
PROP_FILENAME , PROP_PARAMS , PROP_NAME , PROP_SHOW_LIST ,
PROP_HIDE_LIST , PROP_TOGGLE_LIST
}
Functions
EvLinkActionType ev_link_action_get_action_type (EvLinkAction *self)
EvLinkDest * ev_link_action_get_dest (EvLinkAction *self)
const gchar * ev_link_action_get_uri (EvLinkAction *self)
const gchar * ev_link_action_get_filename (EvLinkAction *self)
const gchar * ev_link_action_get_params (EvLinkAction *self)
const gchar * ev_link_action_get_name (EvLinkAction *self)
GList * ev_link_action_get_show_list (EvLinkAction *self)
GList * ev_link_action_get_hide_list (EvLinkAction *self)
GList * ev_link_action_get_toggle_list (EvLinkAction *self)
EvLinkAction * ev_link_action_new_dest (EvLinkDest *dest)
EvLinkAction * ev_link_action_new_remote (EvLinkDest *dest, const gchar *filename)
EvLinkAction * ev_link_action_new_external_uri (const gchar *uri)
EvLinkAction * ev_link_action_new_launch (const gchar *filename, const gchar *params)
EvLinkAction * ev_link_action_new_named (const gchar *name)
EvLinkAction * ev_link_action_new_layers_state (GList *show_list, GList *hide_list, GList *toggle_list)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_TYPE
PROP_DEST
PROP_URI
PROP_FILENAME
PROP_PARAMS
PROP_NAME
PROP_SHOW_LIST
PROP_HIDE_LIST
PROP_TOGGLE_LIST
Definition at line 25 of file ev-link-action.c.
Function Documentation
ev_link_action_get_action_type()
EvLinkActionType ev_link_action_get_action_type (EvLinkAction * self)
Definition at line 63 of file ev-link-action.c.
References EV_IS_LINK_ACTION.
Referenced by ev_view_handle_link().
ev_link_action_get_dest()
EvLinkDest * ev_link_action_get_dest (EvLinkAction * self)
Definition at line 71 of file ev-link-action.c.
References EV_IS_LINK_ACTION, and NULL.
Referenced by ev_view_handle_link().
ev_link_action_get_filename()
const gchar * ev_link_action_get_filename (EvLinkAction * self)
Definition at line 87 of file ev-link-action.c.
References EV_IS_LINK_ACTION, and NULL.
ev_link_action_get_hide_list()
GList * ev_link_action_get_hide_list (EvLinkAction * self)
Definition at line 119 of file ev-link-action.c.
References EV_IS_LINK_ACTION, and NULL.
Referenced by ev_view_handle_link().
ev_link_action_get_name()
const gchar * ev_link_action_get_name (EvLinkAction * self)
Definition at line 103 of file ev-link-action.c.
References EV_IS_LINK_ACTION, and NULL.
ev_link_action_get_params()
const gchar * ev_link_action_get_params (EvLinkAction * self)
Definition at line 95 of file ev-link-action.c.
References EV_IS_LINK_ACTION, and NULL.
ev_link_action_get_show_list()
GList * ev_link_action_get_show_list (EvLinkAction * self)
Definition at line 111 of file ev-link-action.c.
References EV_IS_LINK_ACTION, and NULL.
Referenced by ev_view_handle_link().
ev_link_action_get_toggle_list()
GList * ev_link_action_get_toggle_list (EvLinkAction * self)
Definition at line 127 of file ev-link-action.c.
References EV_IS_LINK_ACTION, and NULL.
Referenced by ev_view_handle_link().
ev_link_action_get_uri()
const gchar * ev_link_action_get_uri (EvLinkAction * self)
Definition at line 79 of file ev-link-action.c.
References EV_IS_LINK_ACTION, and NULL.
Referenced by ev_view_copy_link_address().
ev_link_action_new_dest()
EvLinkAction * ev_link_action_new_dest (EvLinkDest * dest)
Definition at line 377 of file ev-link-action.c.
References dest, EV_LINK_ACTION, EV_LINK_ACTION_TYPE_GOTO_DEST, EV_TYPE_LINK_ACTION, and NULL.
Referenced by ev_window_open_document().
ev_link_action_new_external_uri()
EvLinkAction * ev_link_action_new_external_uri (const gchar * uri)
Definition at line 397 of file ev-link-action.c.
References EV_LINK_ACTION, EV_LINK_ACTION_TYPE_EXTERNAL_URI, EV_TYPE_LINK_ACTION, and NULL.
ev_link_action_new_launch()
EvLinkAction * ev_link_action_new_launch (const gchar * filename, const gchar * params)
Definition at line 406 of file ev-link-action.c.
References EV_LINK_ACTION, EV_LINK_ACTION_TYPE_LAUNCH, EV_TYPE_LINK_ACTION, and NULL.
ev_link_action_new_layers_state()
EvLinkAction * ev_link_action_new_layers_state (GList * show_list, GList * hide_list, GList * toggle_list)
Definition at line 426 of file ev-link-action.c.
References EV_LINK_ACTION, EV_LINK_ACTION_TYPE_LAYERS_STATE, EV_TYPE_LINK_ACTION, and NULL.
ev_link_action_new_named()
EvLinkAction * ev_link_action_new_named (const gchar * name)
Definition at line 417 of file ev-link-action.c.
References EV_LINK_ACTION, EV_LINK_ACTION_TYPE_NAMED, EV_TYPE_LINK_ACTION, name, and NULL.
ev_link_action_new_remote()
EvLinkAction * ev_link_action_new_remote (EvLinkDest * dest, const gchar * filename)
Definition at line 386 of file ev-link-action.c.
References dest, EV_LINK_ACTION, EV_LINK_ACTION_TYPE_GOTO_REMOTE, EV_TYPE_LINK_ACTION, and NULL.