MATE Desktop Environment: ev-mapping-list.h File Reference
ev-mapping-list.h File Reference
#include "ev-document.h"
Macros
#define EV_TYPE_MAPPING_LIST (ev_mapping_list_get_type())
Typedefs
typedef struct _EvMappingList EvMappingList
Functions
GType ev_mapping_list_get_type (void)
EvMappingList * ev_mapping_list_new (guint page, GList *list, GDestroyNotify data_destroy_func)
EvMappingList * ev_mapping_list_ref (EvMappingList *mapping_list)
void ev_mapping_list_unref (EvMappingList *mapping_list)
guint ev_mapping_list_get_page (EvMappingList *mapping_list)
GList * ev_mapping_list_get_list (EvMappingList *mapping_list)
void ev_mapping_list_remove (EvMappingList *mapping_list, EvMapping *mapping)
EvMapping * ev_mapping_list_find (EvMappingList *mapping_list, gconstpointer data)
EvMapping * ev_mapping_list_find_custom (EvMappingList *mapping_list, gconstpointer data, GCompareFunc func)
EvMapping * ev_mapping_list_get (EvMappingList *mapping_list, gdouble x, gdouble y)
gpointer ev_mapping_list_get_data (EvMappingList *mapping_list, gdouble x, gdouble y)
EvMapping * ev_mapping_list_nth (EvMappingList *mapping_list, guint n)
guint ev_mapping_list_length (EvMappingList *mapping_list)
Macro Definition Documentation
EV_TYPE_MAPPING_LIST
#define EV_TYPE_MAPPING_LIST (ev_mapping_list_get_type())
Definition at line 34 of file ev-mapping-list.h.
Typedef Documentation
EvMappingList
typedef struct _EvMappingList EvMappingList
Definition at line 32 of file ev-mapping-list.h.
Function Documentation
ev_mapping_list_find()
EvMapping * ev_mapping_list_find (EvMappingList * mapping_list, gconstpointer data)
ev_mapping_list_find: @mapping_list: an EvMappingList @data: mapping data to find
Returns: (transfer none): an EvMapping
Definition at line 40 of file ev-mapping-list.c.
References _EvMapping::data, data, and NULL.
Referenced by _ev_view_focus_form_field().
ev_mapping_list_find_custom()
EvMapping * ev_mapping_list_find_custom (EvMappingList * mapping_list, gconstpointer data, GCompareFunc func)
ev_mapping_list_find_custom: @mapping_list: an EvMappingList @data: mapping data to find @func: (scope call): function to use for equality check
Returns: (transfer none): an EvMapping
Definition at line 64 of file ev-mapping-list.c.
References _EvMapping::data, data, and NULL.
ev_mapping_list_get()
EvMapping * ev_mapping_list_get (EvMappingList * mapping_list, gdouble x, gdouble y)
ev_mapping_list_get: @mapping_list: an EvMappingList @x: X coordinate @y: Y coordinate
Returns: (transfer none): the EvMapping in the list at coordinates (x, y)
Definition at line 105 of file ev-mapping-list.c.
References _EvMapping::area, NULL, _EvRectangle::x1, and _EvRectangle::y1.
Referenced by ev_mapping_list_get_data().
ev_mapping_list_get_data()
gpointer ev_mapping_list_get_data (EvMappingList * mapping_list, gdouble x, gdouble y)
ev_mapping_list_get_data: @mapping_list: an EvMappingList @x: X coordinate @y: Y coordinate
Returns: (transfer none): the data of a mapping in the list at coordinates (x, y)
Definition at line 134 of file ev-mapping-list.c.
References _EvMapping::data, ev_mapping_list_get(), and NULL.
ev_mapping_list_get_list()
GList * ev_mapping_list_get_list (EvMappingList * mapping_list)
ev_mapping_list_get_list: @mapping_list: an EvMappingList
Returns: (transfer none) (element-type EvMapping): the data for this mapping list
Definition at line 154 of file ev-mapping-list.c.
References NULL.
ev_mapping_list_get_page()
guint ev_mapping_list_get_page (EvMappingList * mapping_list)
Definition at line 178 of file ev-mapping-list.c.
ev_mapping_list_get_type()
GType ev_mapping_list_get_type (void)
References data.
ev_mapping_list_length()
guint ev_mapping_list_length (EvMappingList * mapping_list)
Definition at line 184 of file ev-mapping-list.c.
References NULL.
ev_mapping_list_new()
EvMappingList * ev_mapping_list_new (guint page, GList * list, GDestroyNotify data_destroy_func)
Definition at line 200 of file ev-mapping-list.c.
References NULL.
Referenced by djvu_links_get_links().
ev_mapping_list_nth()
EvMapping * ev_mapping_list_nth (EvMappingList * mapping_list, guint n)
ev_mapping_list_nth: @mapping_list: an EvMappingList
: the position to retrieve
Returns: (transfer none): the #Evmapping at position
in @mapping_list
Definition at line 88 of file ev-mapping-list.c.
References NULL.
ev_mapping_list_ref()
EvMappingList * ev_mapping_list_ref (EvMappingList * mapping_list)
Definition at line 218 of file ev-mapping-list.c.
References NULL.
ev_mapping_list_remove()
void ev_mapping_list_remove (EvMappingList * mapping_list, EvMapping * mapping)
ev_mapping_list_remove: @mapping_list: an EvMappingList @mapping: EvMapping to remove
Returns: an EvMappingList
Since: 3.14
Definition at line 169 of file ev-mapping-list.c.
References _EvMapping::data.
ev_mapping_list_unref()
void ev_mapping_list_unref (EvMappingList * mapping_list)
Definition at line 237 of file ev-mapping-list.c.
References NULL.
Referenced by ev_page_cache_mark_dirty().