MATE Desktop Environment: ev-pixbuf-cache.h File Reference
ev-pixbuf-cache.h File Reference
#include <gtk/gtk.h>
#include <atril-document.h>
#include <atril-view.h>
Classes
struct EvViewSelection
Macros
#define EV_TYPE_PIXBUF_CACHE (ev_pixbuf_cache_get_type ())
#define EV_PIXBUF_CACHE(obj)
#define EV_IS_PIXBUF_CACHE(obj)
Typedefs
typedef struct _EvPixbufCache EvPixbufCache
typedef struct _EvPixbufCacheClass EvPixbufCacheClass
Functions
GType ev_pixbuf_cache_get_type (void)
EvPixbufCache * ev_pixbuf_cache_new (GtkWidget *view, EvDocumentModel *model, gsize max_size)
void ev_pixbuf_cache_set_max_size (EvPixbufCache *pixbuf_cache, gsize max_size)
void ev_pixbuf_cache_set_page_range (EvPixbufCache *pixbuf_cache, gint start_page, gint end_page, GList *selection_list)
cairo_surface_t * ev_pixbuf_cache_get_surface (EvPixbufCache *pixbuf_cache, gint page)
void ev_pixbuf_cache_clear (EvPixbufCache *pixbuf_cache)
void ev_pixbuf_cache_style_changed (EvPixbufCache *pixbuf_cache)
void ev_pixbuf_cache_reload_page (EvPixbufCache *pixbuf_cache, cairo_region_t *region, gint page, gint rotation, gdouble scale)
void ev_pixbuf_cache_set_inverted_colors (EvPixbufCache *pixbuf_cache, gboolean inverted_colors)
cairo_surface_t * ev_pixbuf_cache_get_selection_surface (EvPixbufCache *pixbuf_cache, gint page, gfloat scale)
cairo_region_t * ev_pixbuf_cache_get_selection_region (EvPixbufCache *pixbuf_cache, gint page, gfloat scale)
void ev_pixbuf_cache_set_selection_list (EvPixbufCache *pixbuf_cache, GList *selection_list)
GList * ev_pixbuf_cache_get_selection_list (EvPixbufCache *pixbuf_cache)
Macro Definition Documentation
EV_IS_PIXBUF_CACHE
#define EV_IS_PIXBUF_CACHE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), EV_TYPE_PIXBUF_CACHE))
Definition at line 40 of file ev-pixbuf-cache.h.
Referenced by ev_pixbuf_cache_get_selection_list(), ev_pixbuf_cache_set_page_range(), and ev_pixbuf_cache_set_selection_list().
EV_PIXBUF_CACHE
#define EV_PIXBUF_CACHE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), EV_TYPE_PIXBUF_CACHE, EvPixbufCache))
Definition at line 39 of file ev-pixbuf-cache.h.
EV_TYPE_PIXBUF_CACHE
#define EV_TYPE_PIXBUF_CACHE (ev_pixbuf_cache_get_type ())
Definition at line 38 of file ev-pixbuf-cache.h.
Referenced by ev_pixbuf_cache_new().
Typedef Documentation
EvPixbufCache
typedef struct _EvPixbufCache EvPixbufCache
Definition at line 52 of file ev-pixbuf-cache.h.
EvPixbufCacheClass
typedef struct _EvPixbufCacheClass EvPixbufCacheClass
Definition at line 53 of file ev-pixbuf-cache.h.
Function Documentation
ev_pixbuf_cache_clear()
void ev_pixbuf_cache_clear (EvPixbufCache * pixbuf_cache)
Definition at line 968 of file ev-pixbuf-cache.c.
References PAGE_CACHE_LEN.
Referenced by ev_pixbuf_cache_set_max_size(), and ev_view_reload().
ev_pixbuf_cache_get_selection_list()
GList * ev_pixbuf_cache_get_selection_list (EvPixbufCache * pixbuf_cache)
Definition at line 1267 of file ev-pixbuf-cache.c.
References EvViewSelection::covered_region, ev_document_get_n_pages(), EV_IS_PIXBUF_CACHE, NULL, EvViewSelection::page, PAGE_CACHE_LEN, and EvViewSelection::rect.
ev_pixbuf_cache_get_selection_region()
cairo_region_t * ev_pixbuf_cache_get_selection_region (EvPixbufCache * pixbuf_cache, gint page, gfloat scale)
Definition at line 1095 of file ev-pixbuf-cache.c.
References ev_document_doc_mutex_lock(), ev_document_doc_mutex_unlock(), ev_document_get_page(), EV_IS_SELECTION, EV_JOB_RENDER, ev_rect_cmp(), ev_render_context_new(), EV_SELECTION, ev_selection_get_selection_region(), and NULL.
ev_pixbuf_cache_get_selection_surface()
cairo_surface_t * ev_pixbuf_cache_get_selection_surface (EvPixbufCache * pixbuf_cache, gint page, gfloat scale)
Definition at line 1025 of file ev-pixbuf-cache.c.
References ev_document_doc_mutex_lock(), ev_document_doc_mutex_unlock(), ev_document_get_page(), EV_IS_SELECTION, EV_JOB_RENDER, ev_rect_cmp(), ev_render_context_new(), EV_SELECTION, ev_selection_render_selection(), EV_VIEW, NULL, and _EvRectangle::x1.
ev_pixbuf_cache_get_surface()
cairo_surface_t * ev_pixbuf_cache_get_surface (EvPixbufCache * pixbuf_cache, gint page)
Definition at line 893 of file ev-pixbuf-cache.c.
References EV_JOB_RENDER, JOB_FINISHED, and NULL.
ev_pixbuf_cache_get_type()
GType ev_pixbuf_cache_get_type (void)
ev_pixbuf_cache_new()
EvPixbufCache * ev_pixbuf_cache_new (GtkWidget * view, EvDocumentModel * model, gsize max_size)
Definition at line 225 of file ev-pixbuf-cache.c.
References ev_document_model_get_document(), EV_TYPE_PIXBUF_CACHE, and NULL.
ev_pixbuf_cache_reload_page()
void ev_pixbuf_cache_reload_page (EvPixbufCache * pixbuf_cache, cairo_region_t * region, gint page, gint rotation, gdouble scale)
Definition at line 1333 of file ev-pixbuf-cache.c.
References _get_page_size_for_scale_and_rotation(), EV_JOB_PRIORITY_URGENT, and NULL.
ev_pixbuf_cache_set_inverted_colors()
void ev_pixbuf_cache_set_inverted_colors (EvPixbufCache * pixbuf_cache, gboolean inverted_colors)
Definition at line 861 of file ev-pixbuf-cache.c.
References ev_document_misc_invert_surface(), and PAGE_CACHE_LEN.
ev_pixbuf_cache_set_max_size()
void ev_pixbuf_cache_set_max_size (EvPixbufCache * pixbuf_cache, gsize max_size)
Definition at line 242 of file ev-pixbuf-cache.c.
References ev_pixbuf_cache_clear().
Referenced by ev_view_set_page_cache_size().
ev_pixbuf_cache_set_page_range()
void ev_pixbuf_cache_set_page_range (EvPixbufCache * pixbuf_cache, gint start_page, gint end_page, GList * selection_list)
Definition at line 828 of file ev-pixbuf-cache.c.
References ev_document_get_n_pages(), ev_document_model_get_rotation(), ev_document_model_get_scale(), EV_IS_PIXBUF_CACHE, and ev_pixbuf_cache_set_selection_list().
ev_pixbuf_cache_set_selection_list()
void ev_pixbuf_cache_set_selection_list (EvPixbufCache * pixbuf_cache, GList * selection_list)
Definition at line 1182 of file ev-pixbuf-cache.c.
References ev_document_get_n_pages(), EV_IS_PIXBUF_CACHE, EV_IS_SELECTION, NULL, and PAGE_CACHE_LEN.
Referenced by ev_pixbuf_cache_set_page_range().
ev_pixbuf_cache_style_changed()
void ev_pixbuf_cache_style_changed (EvPixbufCache * pixbuf_cache)
Definition at line 986 of file ev-pixbuf-cache.c.
References NULL, PAGE_CACHE_LEN, and _EvRectangle::x1.