MATE Desktop Environment: ev-print-operation.h File Reference
ev-print-operation.h File Reference
#include <gtk/gtk.h>
#include <glib-object.h>
#include <atril-document.h>
Macros
#define EV_TYPE_PRINT_OPERATION (ev_print_operation_get_type())
#define EV_PRINT_OPERATION(object)
#define EV_PRINT_OPERATION_CLASS(klass)
#define EV_IS_PRINT_OPERATION(object)
#define EV_PRINT_OPERATION_GET_CLASS(object)
Typedefs
typedef struct _EvPrintOperation EvPrintOperation
typedef struct _EvPrintOperationClass EvPrintOperationClass
Functions
GType ev_print_operation_get_type (void)
gboolean ev_print_operation_exists_for_document (EvDocument *document)
EvPrintOperation * ev_print_operation_new (EvDocument *document)
void ev_print_operation_set_current_page (EvPrintOperation *op, gint current_page)
void ev_print_operation_set_print_settings (EvPrintOperation *op, GtkPrintSettings *print_settings)
GtkPrintSettings * ev_print_operation_get_print_settings (EvPrintOperation *op)
void ev_print_operation_set_default_page_setup (EvPrintOperation *op, GtkPageSetup *page_setup)
GtkPageSetup * ev_print_operation_get_default_page_setup (EvPrintOperation *op)
void ev_print_operation_set_job_name (EvPrintOperation *op, const gchar *job_name)
const gchar * ev_print_operation_get_job_name (EvPrintOperation *op)
void ev_print_operation_run (EvPrintOperation *op, GtkWindow *parent)
void ev_print_operation_cancel (EvPrintOperation *op)
void ev_print_operation_get_error (EvPrintOperation *op, GError **error)
void ev_print_operation_set_embed_page_setup (EvPrintOperation *op, gboolean embed)
gboolean ev_print_operation_get_embed_page_setup (EvPrintOperation *op)
const gchar * ev_print_operation_get_status (EvPrintOperation *op)
gdouble ev_print_operation_get_progress (EvPrintOperation *op)
Macro Definition Documentation
EV_IS_PRINT_OPERATION
#define EV_IS_PRINT_OPERATION (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_PRINT_OPERATION))
Definition at line 40 of file ev-print-operation.h.
Referenced by ev_print_operation_cancel(), ev_print_operation_get_default_page_setup(), ev_print_operation_get_embed_page_setup(), ev_print_operation_get_error(), ev_print_operation_get_job_name(), ev_print_operation_get_print_settings(), ev_print_operation_get_progress(), ev_print_operation_get_status(), ev_print_operation_run(), ev_print_operation_set_current_page(), ev_print_operation_set_default_page_setup(), ev_print_operation_set_embed_page_setup(), ev_print_operation_set_job_name(), and ev_print_operation_set_print_settings().
EV_PRINT_OPERATION
#define EV_PRINT_OPERATION (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_PRINT_OPERATION, EvPrintOperation))
Definition at line 38 of file ev-print-operation.h.
Referenced by ev_print_operation_new().
EV_PRINT_OPERATION_CLASS
#define EV_PRINT_OPERATION_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_PRINT_OPERATION, EvPrintOperationClass))
Definition at line 39 of file ev-print-operation.h.
EV_PRINT_OPERATION_GET_CLASS
#define EV_PRINT_OPERATION_GET_CLASS (object)
Value:
(G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_PRINT_OPERATION, EvPrintOperationClass))
Definition at line 41 of file ev-print-operation.h.
EV_TYPE_PRINT_OPERATION
#define EV_TYPE_PRINT_OPERATION (ev_print_operation_get_type())
Definition at line 37 of file ev-print-operation.h.
Typedef Documentation
EvPrintOperation
typedef struct _EvPrintOperation EvPrintOperation
Definition at line 34 of file ev-print-operation.h.
EvPrintOperationClass
typedef struct _EvPrintOperationClass EvPrintOperationClass
Definition at line 35 of file ev-print-operation.h.
Function Documentation
ev_print_operation_cancel()
void ev_print_operation_cancel (EvPrintOperation * op)
Definition at line 276 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, and op.
ev_print_operation_exists_for_document()
gboolean ev_print_operation_exists_for_document (EvDocument * document)
Definition at line 2037 of file ev-print-operation.c.
References EV_IS_DOCUMENT_PRINT, and EV_IS_FILE_EXPORTER.
Referenced by ev_print_operation_new().
ev_print_operation_get_default_page_setup()
GtkPageSetup * ev_print_operation_get_default_page_setup (EvPrintOperation * op)
ev_print_operation_get_default_page_setup: @op: an EvPrintOperation
Returns: (transfer none): a #GtkPageSetup
Definition at line 233 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, NULL, and op.
ev_print_operation_get_embed_page_setup()
gboolean ev_print_operation_get_embed_page_setup (EvPrintOperation * op)
Definition at line 308 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, FALSE, and op.
ev_print_operation_get_error()
void ev_print_operation_get_error (EvPrintOperation * op, GError ** error)
Definition at line 286 of file ev-print-operation.c.
References error, EV_IS_PRINT_OPERATION, and op.
ev_print_operation_get_job_name()
const gchar * ev_print_operation_get_job_name (EvPrintOperation * op)
Definition at line 255 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, NULL, and op.
ev_print_operation_get_print_settings()
GtkPrintSettings * ev_print_operation_get_print_settings (EvPrintOperation * op)
ev_print_operation_get_print_settings: @op: an EvPrintOperation
Returns: (transfer none): a #GtkPrintSettings
Definition at line 205 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, NULL, and op.
ev_print_operation_get_progress()
gdouble ev_print_operation_get_progress (EvPrintOperation * op)
Definition at line 326 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, and op.
ev_print_operation_get_status()
const gchar * ev_print_operation_get_status (EvPrintOperation * op)
Definition at line 318 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, NULL, and op.
ev_print_operation_get_type()
GType ev_print_operation_get_type (void)
References error, and op.
ev_print_operation_new()
EvPrintOperation * ev_print_operation_new (EvDocument * document)
Definition at line 2048 of file ev-print-operation.c.
References EV_IS_DOCUMENT_PRINT, EV_PRINT_OPERATION, ev_print_operation_exists_for_document(), EV_TYPE_PRINT_OPERATION_PRINT, NULL, and op.
Referenced by ev_window_print_range().
ev_print_operation_run()
void ev_print_operation_run (EvPrintOperation * op, GtkWindow * parent)
Definition at line 265 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, and op.
Referenced by ev_window_print_range().
ev_print_operation_set_current_page()
void ev_print_operation_set_current_page (EvPrintOperation * op, gint current_page)
Definition at line 175 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, and op.
Referenced by ev_window_print_range().
ev_print_operation_set_default_page_setup()
void ev_print_operation_set_default_page_setup (EvPrintOperation * op, GtkPageSetup * page_setup)
Definition at line 215 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, and op.
Referenced by ev_window_print_range().
ev_print_operation_set_embed_page_setup()
void ev_print_operation_set_embed_page_setup (EvPrintOperation * op, gboolean embed)
Definition at line 297 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, and op.
Referenced by ev_window_print_range().
ev_print_operation_set_job_name()
void ev_print_operation_set_job_name (EvPrintOperation * op, const gchar * job_name)
Definition at line 243 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, NULL, and op.
Referenced by ev_window_print_range().
ev_print_operation_set_print_settings()
void ev_print_operation_set_print_settings (EvPrintOperation * op, GtkPrintSettings * print_settings)
Definition at line 187 of file ev-print-operation.c.
References EV_IS_PRINT_OPERATION, and op.
Referenced by ev_window_print_range().