MATE Desktop Environment: ev-previewer-window.c File Reference
ev-previewer-window.c File Reference
#include <config.h>
#include <glib/gi18n.h>
#include <atril-view.h>
#include "ev-page-action.h"
#include "ev-previewer-window.h"
Macros
#define MIN_SCALE 0.05409
#define MAX_SCALE 4.0
Enumerations
enum { PROP_0 , PROP_MODEL }
Functions
GtkWidget * ev_previewer_window_new (EvDocumentModel *model)
void ev_previewer_window_set_print_settings (EvPreviewerWindow *window, const gchar *print_settings)
void ev_previewer_window_set_source_file (EvPreviewerWindow *window, const gchar *source_file)
Variables
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
G_GNUC_END_IGNORE_DEPRECATIONS
Macro Definition Documentation
MAX_SCALE
#define MAX_SCALE 4.0
Definition at line 66 of file ev-previewer-window.c.
MIN_SCALE
#define MIN_SCALE 0.05409
Definition at line 65 of file ev-previewer-window.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_MODEL
Definition at line 60 of file ev-previewer-window.c.
Function Documentation
ev_previewer_window_new()
GtkWidget * ev_previewer_window_new (EvDocumentModel * model)
Definition at line 645 of file ev-previewer-window.c.
References EV_TYPE_PREVIEWER_WINDOW, and NULL.
Referenced by main().
ev_previewer_window_set_print_settings()
void ev_previewer_window_set_print_settings (EvPreviewerWindow * window, const gchar * print_settings)
Definition at line 651 of file ev-previewer-window.c.
References error, and NULL.
Referenced by main().
ev_previewer_window_set_source_file()
void ev_previewer_window_set_source_file (EvPreviewerWindow * window, const gchar * source_file)
Definition at line 707 of file ev-previewer-window.c.
References source_file.
Referenced by main().
Variable Documentation
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
G_GNUC_BEGIN_IGNORE_DEPRECATIONS
Definition at line 149 of file ev-previewer-window.c.
G_GNUC_END_IGNORE_DEPRECATIONS
G_GNUC_END_IGNORE_DEPRECATIONS
Definition at line 167 of file ev-previewer-window.c.