MATE Desktop Environment: ev-page-accessible.h File Reference
ev-page-accessible.h File Reference
#include <gtk/gtk-a11y.h>
#include "ev-view-accessible.h"
#include "ev-view.h"
Classes
struct _EvPageAccessible
struct _EvPageAccessibleClass
Macros
#define EV_TYPE_PAGE_ACCESSIBLE (ev_page_accessible_get_type ())
#define EV_PAGE_ACCESSIBLE(obj)
#define EV_IS_PAGE_ACCESSIBLE(obj)
Typedefs
typedef struct _EvPageAccessible EvPageAccessible
typedef struct _EvPageAccessibleClass EvPageAccessibleClass
typedef struct _EvPageAccessiblePrivate EvPageAccessiblePrivate
Functions
GType ev_page_accessible_get_type (void)
EvPageAccessible * ev_page_accessible_new (EvViewAccessible *view_accessible, gint page)
gint ev_page_accessible_get_page (EvPageAccessible *page_accessible)
EvViewAccessible * ev_page_accessible_get_view_accessible (EvPageAccessible *page_accessible)
EvView * ev_page_accessible_get_view (EvPageAccessible *page_accessible)
Macro Definition Documentation
EV_IS_PAGE_ACCESSIBLE
#define EV_IS_PAGE_ACCESSIBLE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), EV_TYPE_PAGE_ACCESSIBLE))
Definition at line 32 of file ev-page-accessible.h.
Referenced by ev_page_accessible_get_view(), ev_page_accessible_get_view_accessible(), and G_DEFINE_TYPE_WITH_CODE().
EV_PAGE_ACCESSIBLE
#define EV_PAGE_ACCESSIBLE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), EV_TYPE_PAGE_ACCESSIBLE, EvPageAccessible))
Definition at line 31 of file ev-page-accessible.h.
Referenced by ev_page_accessible_new().
EV_TYPE_PAGE_ACCESSIBLE
#define EV_TYPE_PAGE_ACCESSIBLE (ev_page_accessible_get_type ())
Definition at line 30 of file ev-page-accessible.h.
Referenced by ev_page_accessible_new().
Typedef Documentation
EvPageAccessible
typedef struct _EvPageAccessible EvPageAccessible
Definition at line 34 of file ev-page-accessible.h.
EvPageAccessibleClass
typedef struct _EvPageAccessibleClass EvPageAccessibleClass
Definition at line 35 of file ev-page-accessible.h.
EvPageAccessiblePrivate
typedef struct _EvPageAccessiblePrivate EvPageAccessiblePrivate
Definition at line 36 of file ev-page-accessible.h.
Function Documentation
ev_page_accessible_get_page()
gint ev_page_accessible_get_page (EvPageAccessible * page_accessible)
Referenced by G_DEFINE_TYPE_WITH_CODE(), and G_DEFINE_TYPE_WITH_CODE().
ev_page_accessible_get_type()
GType ev_page_accessible_get_type (void)
ev_page_accessible_get_view()
EvView * ev_page_accessible_get_view (EvPageAccessible * page_accessible)
Definition at line 384 of file ev-page-accessible.c.
References EV_IS_PAGE_ACCESSIBLE, EV_VIEW, NULL, and _EvPageAccessible::priv.
ev_page_accessible_get_view_accessible()
EvViewAccessible * ev_page_accessible_get_view_accessible (EvPageAccessible * page_accessible)
Definition at line 65 of file ev-page-accessible.c.
References EV_IS_PAGE_ACCESSIBLE, NULL, and _EvPageAccessible::priv.
Referenced by G_DEFINE_TYPE_WITH_CODE(), and G_DEFINE_TYPE_WITH_CODE().
ev_page_accessible_new()
EvPageAccessible * ev_page_accessible_new (EvViewAccessible * view_accessible, gint page)
Definition at line 1211 of file ev-page-accessible.c.
References EV_IS_VIEW_ACCESSIBLE, EV_PAGE_ACCESSIBLE, EV_TYPE_PAGE_ACCESSIBLE, and NULL.