MATE Desktop Environment: ev-properties-view.h File Reference
ev-properties-view.h File Reference
#include <gtk/gtk.h>
#include <atril-document.h>
Macros
#define EV_TYPE_PROPERTIES (ev_properties_view_get_type())
#define EV_PROPERTIES_VIEW(object)
#define EV_PROPERTIES_VIEW_CLASS(klass)
#define EV_IS_PROPERTIES_VIEW(object)
#define EV_IS_PROPERTIES_VIEW_CLASS(klass)
#define EV_PROPERTIES_VIEW_GET_CLASS(object)
Typedefs
typedef struct _EvPropertiesView EvPropertiesView
typedef struct _EvPropertiesViewClass EvPropertiesViewClass
typedef struct _EvPropertiesViewPrivate EvPropertiesViewPrivate
Functions
GType ev_properties_view_get_type (void)
void ev_properties_view_register_type (GTypeModule *module)
GtkWidget * ev_properties_view_new (const gchar *uri)
void ev_properties_view_set_info (EvPropertiesView *properties, const EvDocumentInfo *info)
Macro Definition Documentation
EV_IS_PROPERTIES_VIEW
#define EV_IS_PROPERTIES_VIEW (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE((object), EV_TYPE_PROPERTIES))
Definition at line 37 of file ev-properties-view.h.
EV_IS_PROPERTIES_VIEW_CLASS
#define EV_IS_PROPERTIES_VIEW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass), EV_TYPE_PROPERTIES))
Definition at line 38 of file ev-properties-view.h.
EV_PROPERTIES_VIEW
#define EV_PROPERTIES_VIEW (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST((object), EV_TYPE_PROPERTIES, EvPropertiesView))
Definition at line 35 of file ev-properties-view.h.
Referenced by ev_properties_dialog_set_document().
EV_PROPERTIES_VIEW_CLASS
#define EV_PROPERTIES_VIEW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST((klass), EV_TYPE_PROPERTIES, EvPropertiesViewClass))
Definition at line 36 of file ev-properties-view.h.
EV_PROPERTIES_VIEW_GET_CLASS
#define EV_PROPERTIES_VIEW_GET_CLASS (object)
Value:
(G_TYPE_INSTANCE_GET_CLASS((object), EV_TYPE_PROPERTIES, EvPropertiesViewClass))
Definition at line 39 of file ev-properties-view.h.
EV_TYPE_PROPERTIES
#define EV_TYPE_PROPERTIES (ev_properties_view_get_type())
Definition at line 34 of file ev-properties-view.h.
Referenced by ev_properties_view_new().
Typedef Documentation
EvPropertiesView
typedef struct _EvPropertiesView EvPropertiesView
Definition at line 30 of file ev-properties-view.h.
EvPropertiesViewClass
typedef struct _EvPropertiesViewClass EvPropertiesViewClass
Definition at line 31 of file ev-properties-view.h.
EvPropertiesViewPrivate
typedef struct _EvPropertiesViewPrivate EvPropertiesViewPrivate
Definition at line 32 of file ev-properties-view.h.
Function Documentation
ev_properties_view_get_type()
GType ev_properties_view_get_type (void)
Referenced by ev_properties_view_register_type().
ev_properties_view_new()
GtkWidget * ev_properties_view_new (const gchar * uri)
Definition at line 395 of file ev-properties-view.c.
References EV_TYPE_PROPERTIES, and NULL.
Referenced by ev_properties_dialog_set_document().
ev_properties_view_register_type()
void ev_properties_view_register_type (GTypeModule * module)
Definition at line 389 of file ev-properties-view.c.
References ev_properties_view_get_type().
Referenced by caja_module_initialize().
ev_properties_view_set_info()
void ev_properties_view_set_info (EvPropertiesView * properties, const EvDocumentInfo * info)
Definition at line 318 of file ev-properties-view.c.
References AUTHOR_PROPERTY, CREATION_DATE_PROPERTY, CREATOR_PROPERTY, EV_DOCUMENT_INFO_AUTHOR, EV_DOCUMENT_INFO_CREATION_DATE, EV_DOCUMENT_INFO_CREATOR, EV_DOCUMENT_INFO_FORMAT, EV_DOCUMENT_INFO_KEYWORDS, EV_DOCUMENT_INFO_LINEARIZED, EV_DOCUMENT_INFO_MOD_DATE, EV_DOCUMENT_INFO_N_PAGES, EV_DOCUMENT_INFO_PAPER_SIZE, EV_DOCUMENT_INFO_PRODUCER, EV_DOCUMENT_INFO_SECURITY, EV_DOCUMENT_INFO_SUBJECT, EV_DOCUMENT_INFO_TITLE, ev_document_misc_format_date(), FORMAT_PROPERTY, KEYWORDS_PROPERTY, LINEARIZED_PROPERTY, MOD_DATE_PROPERTY, N_PAGES_PROPERTY, PAPER_SIZE_PROPERTY, PRODUCER_PROPERTY, SECURITY_PROPERTY, SUBJECT_PROPERTY, TITLE_PROPERTY, and URI_PROPERTY.
Referenced by ev_properties_dialog_set_document().