MATE Desktop Environment: ev-previewer.c File Reference
ev-previewer.c File Reference
#include <config.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <atril-document.h>
#include <atril-view.h>
#include "ev-previewer-window.h"
Functions
gint main (gint argc, gchar **argv)
Function Documentation
main()
gint main (gint argc, gchar ** argv)
Definition at line 92 of file ev-previewer.c.
References _, error, ev_document_model_new(), ev_get_locale_dir(), ev_init(), EV_PREVIEWER_WINDOW, ev_previewer_window_new(), ev_previewer_window_set_print_settings(), ev_previewer_window_set_source_file(), ev_shutdown(), ev_stock_icons_init(), GETTEXT_PACKAGE, NULL, and TRUE.
Referenced by eom_save_as_dialog_new().