MATE Desktop Environment: ev-page-cache.h File Reference
ev-page-cache.h File Reference
#include <glib-object.h>
#include <gdk/gdk.h>
#include <atril-document.h>
#include <atril-view.h>
Macros
#define EV_TYPE_PAGE_CACHE (ev_page_cache_get_type ())
#define EV_PAGE_CACHE(obj)
#define EV_IS_PAGE_CACHE(obj)
Typedefs
typedef struct _EvPageCache EvPageCache
typedef struct _EvPageCacheClass EvPageCacheClass
Functions
GType ev_page_cache_get_type (void)
EvPageCache * ev_page_cache_new (EvDocument *document)
void ev_page_cache_set_page_range (EvPageCache *cache, gint start, gint end)
EvJobPageDataFlags ev_page_cache_get_flags (EvPageCache *cache)
void ev_page_cache_set_flags (EvPageCache *cache, EvJobPageDataFlags flags)
void ev_page_cache_mark_dirty (EvPageCache *cache, gint page, EvJobPageDataFlags flags)
EvMappingList * ev_page_cache_get_link_mapping (EvPageCache *cache, gint page)
EvMappingList * ev_page_cache_get_image_mapping (EvPageCache *cache, gint page)
EvMappingList * ev_page_cache_get_form_field_mapping (EvPageCache *cache, gint page)
EvMappingList * ev_page_cache_get_annot_mapping (EvPageCache *cache, gint page)
cairo_region_t * ev_page_cache_get_text_mapping (EvPageCache *cache, gint page)
const gchar * ev_page_cache_get_text (EvPageCache *cache, gint page)
gboolean ev_page_cache_get_text_layout (EvPageCache *cache, gint page, EvRectangle **areas, guint *n_areas)
PangoAttrList * ev_page_cache_get_text_attrs (EvPageCache *cache, gint page)
gboolean ev_page_cache_get_text_log_attrs (EvPageCache *cache, gint page, PangoLogAttr **log_attrs, gulong *n_attrs)
void ev_page_cache_ensure_page (EvPageCache *cache, gint page)
gboolean ev_page_cache_is_page_cached (EvPageCache *cache, gint page)
Macro Definition Documentation
EV_IS_PAGE_CACHE
#define EV_IS_PAGE_CACHE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), EV_TYPE_PAGE_CACHE))
Definition at line 36 of file ev-page-cache.h.
Referenced by ev_page_cache_ensure_page(), ev_page_cache_get_annot_mapping(), ev_page_cache_get_form_field_mapping(), ev_page_cache_get_image_mapping(), ev_page_cache_get_link_mapping(), ev_page_cache_get_text(), ev_page_cache_get_text_attrs(), ev_page_cache_get_text_layout(), ev_page_cache_get_text_log_attrs(), ev_page_cache_get_text_mapping(), ev_page_cache_is_page_cached(), and ev_page_cache_mark_dirty().
EV_PAGE_CACHE
#define EV_PAGE_CACHE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), EV_TYPE_PAGE_CACHE, EvPageCache))
Definition at line 35 of file ev-page-cache.h.
Referenced by ev_page_cache_new().
EV_TYPE_PAGE_CACHE
#define EV_TYPE_PAGE_CACHE (ev_page_cache_get_type ())
Definition at line 34 of file ev-page-cache.h.
Referenced by ev_page_cache_new().
Typedef Documentation
EvPageCache
typedef struct _EvPageCache EvPageCache
Definition at line 38 of file ev-page-cache.h.
EvPageCacheClass
typedef struct _EvPageCacheClass EvPageCacheClass
Definition at line 39 of file ev-page-cache.h.
Function Documentation
ev_page_cache_ensure_page()
void ev_page_cache_ensure_page (EvPageCache * cache, gint page)
Definition at line 659 of file ev-page-cache.c.
References EV_IS_PAGE_CACHE.
ev_page_cache_get_annot_mapping()
EvMappingList * ev_page_cache_get_annot_mapping (EvPageCache * cache, gint page)
Definition at line 507 of file ev-page-cache.c.
References data, EV_IS_PAGE_CACHE, EV_JOB_PAGE_DATA, EV_PAGE_DATA_INCLUDE_ANNOTS, and NULL.
ev_page_cache_get_flags()
EvJobPageDataFlags ev_page_cache_get_flags (EvPageCache * cache)
Definition at line 385 of file ev-page-cache.c.
ev_page_cache_get_form_field_mapping()
EvMappingList * ev_page_cache_get_form_field_mapping (EvPageCache * cache, gint page)
Definition at line 485 of file ev-page-cache.c.
References data, EV_IS_PAGE_CACHE, EV_JOB_PAGE_DATA, EV_PAGE_DATA_INCLUDE_FORMS, and NULL.
Referenced by _ev_view_focus_form_field().
ev_page_cache_get_image_mapping()
EvMappingList * ev_page_cache_get_image_mapping (EvPageCache * cache, gint page)
Definition at line 463 of file ev-page-cache.c.
References data, EV_IS_PAGE_CACHE, EV_JOB_PAGE_DATA, EV_PAGE_DATA_INCLUDE_IMAGES, and NULL.
ev_page_cache_get_link_mapping()
EvMappingList * ev_page_cache_get_link_mapping (EvPageCache * cache, gint page)
Definition at line 441 of file ev-page-cache.c.
References data, EV_IS_PAGE_CACHE, EV_JOB_PAGE_DATA, EV_PAGE_DATA_INCLUDE_LINKS, and NULL.
ev_page_cache_get_text()
const gchar * ev_page_cache_get_text (EvPageCache * cache, gint page)
Definition at line 551 of file ev-page-cache.c.
References data, EV_IS_PAGE_CACHE, EV_JOB_PAGE_DATA, EV_PAGE_DATA_INCLUDE_TEXT, and NULL.
ev_page_cache_get_text_attrs()
PangoAttrList * ev_page_cache_get_text_attrs (EvPageCache * cache, gint page)
Definition at line 605 of file ev-page-cache.c.
References data, EV_IS_PAGE_CACHE, EV_JOB_PAGE_DATA, EV_PAGE_DATA_INCLUDE_TEXT_ATTRS, and NULL.
ev_page_cache_get_text_layout()
gboolean ev_page_cache_get_text_layout (EvPageCache * cache, gint page, EvRectangle ** areas, guint * n_areas)
Definition at line 573 of file ev-page-cache.c.
References data, EV_IS_PAGE_CACHE, EV_JOB_PAGE_DATA, EV_PAGE_DATA_INCLUDE_TEXT_LAYOUT, FALSE, and TRUE.
Referenced by _ev_view_get_caret_cursor_offset_at_doc_point().
ev_page_cache_get_text_log_attrs()
gboolean ev_page_cache_get_text_log_attrs (EvPageCache * cache, gint page, PangoLogAttr ** log_attrs, gulong * n_attrs)
Definition at line 627 of file ev-page-cache.c.
References data, EV_IS_PAGE_CACHE, EV_JOB_PAGE_DATA, EV_PAGE_DATA_INCLUDE_TEXT_LOG_ATTRS, FALSE, and TRUE.
ev_page_cache_get_text_mapping()
cairo_region_t * ev_page_cache_get_text_mapping (EvPageCache * cache, gint page)
Definition at line 529 of file ev-page-cache.c.
References data, EV_IS_PAGE_CACHE, EV_JOB_PAGE_DATA, EV_PAGE_DATA_INCLUDE_TEXT_MAPPING, and NULL.
ev_page_cache_get_type()
GType ev_page_cache_get_type (void)
ev_page_cache_is_page_cached()
gboolean ev_page_cache_is_page_cached (EvPageCache * cache, gint page)
Definition at line 669 of file ev-page-cache.c.
References data, EV_IS_PAGE_CACHE, and FALSE.
ev_page_cache_mark_dirty()
void ev_page_cache_mark_dirty (EvPageCache * cache, gint page, EvJobPageDataFlags flags)
Definition at line 404 of file ev-page-cache.c.
References data, EV_IS_PAGE_CACHE, ev_mapping_list_unref(), ev_page_cache_set_page_range(), EV_PAGE_DATA_INCLUDE_ANNOTS, EV_PAGE_DATA_INCLUDE_FORMS, EV_PAGE_DATA_INCLUDE_IMAGES, EV_PAGE_DATA_INCLUDE_LINKS, EV_PAGE_DATA_INCLUDE_TEXT, EV_PAGE_DATA_INCLUDE_TEXT_LAYOUT, EV_PAGE_DATA_INCLUDE_TEXT_MAPPING, and TRUE.
Referenced by ev_view_remove_annotation().
ev_page_cache_new()
EvPageCache * ev_page_cache_new (EvDocument * document)
Definition at line 260 of file ev-page-cache.c.
References ev_document_get_n_pages(), EV_IS_DOCUMENT, EV_PAGE_CACHE, EV_PAGE_DATA_FLAGS_DEFAULT, EV_TYPE_PAGE_CACHE, and NULL.
ev_page_cache_set_flags()
void ev_page_cache_set_flags (EvPageCache * cache, EvJobPageDataFlags flags)
Definition at line 391 of file ev-page-cache.c.
References ev_page_cache_set_page_range().
ev_page_cache_set_page_range()
void ev_page_cache_set_page_range (EvPageCache * cache, gint start, gint end)
Definition at line 350 of file ev-page-cache.c.
References EV_PAGE_DATA_INCLUDE_NONE, and PRE_CACHE_SIZE.
Referenced by ev_page_cache_mark_dirty(), and ev_page_cache_set_flags().