MATE Desktop Environment: ev-render-context.c File Reference
ev-render-context.c File Reference
#include <config.h>
#include "ev-render-context.h"
Functions
G_DEFINE_TYPE (EvRenderContext, ev_render_context, G_TYPE_OBJECT)
EvRenderContext * ev_render_context_new (EvPage *page, gint rotation, gdouble scale)
void ev_render_context_set_page (EvRenderContext *rc, EvPage *page)
void ev_render_context_set_rotation (EvRenderContext *rc, int rotation)
void ev_render_context_set_scale (EvRenderContext *rc, gdouble scale)
Function Documentation
ev_render_context_new()
EvRenderContext * ev_render_context_new (EvPage * page, gint rotation, gdouble scale)
Definition at line 53 of file ev-render-context.c.
References EV_TYPE_RENDER_CONTEXT, NULL, _EvRenderContext::page, _EvRenderContext::rotation, and _EvRenderContext::scale.
Referenced by ev_pixbuf_cache_get_selection_region(), ev_pixbuf_cache_get_selection_surface(), and G_DEFINE_TYPE_EXTENDED().
ev_render_context_set_page()
void ev_render_context_set_page (EvRenderContext * rc, EvPage * page)
Definition at line 69 of file ev-render-context.c.
References EV_IS_PAGE, NULL, and _EvRenderContext::page.
Referenced by G_DEFINE_TYPE_EXTENDED().
ev_render_context_set_rotation()
void ev_render_context_set_rotation (EvRenderContext * rc, int rotation)
Definition at line 81 of file ev-render-context.c.
References NULL, and _EvRenderContext::rotation.
ev_render_context_set_scale()
void ev_render_context_set_scale (EvRenderContext * rc, gdouble scale)
Definition at line 90 of file ev-render-context.c.
References NULL, and _EvRenderContext::scale.
Referenced by G_DEFINE_TYPE_EXTENDED().
G_DEFINE_TYPE()
G_DEFINE_TYPE (EvRenderContext , ev_render_context , G_TYPE_OBJECT)