MATE Desktop Environment: ev-sidebar-thumbnails.c File Reference
ev-sidebar-thumbnails.c File Reference
#include <string.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include "ev-document-misc.h"
#include "ev-document-thumbnails.h"
#include "ev-job-scheduler.h"
#include "ev-sidebar-page.h"
#include "ev-sidebar-thumbnails.h"
#include "ev-utils.h"
#include "ev-window.h"
Macros
#define THUMBNAIL_WIDTH 100
#define MAX_ICON_VIEW_PAGE_COUNT 1500
#define EV_THUMBNAILS_SIZE_CACHE_KEY "ev-thumbnails-size-cache"
Typedefs
typedef struct _EvThumbsSize EvThumbsSize
typedef struct _EvThumbsSizeCache EvThumbsSizeCache
Enumerations
enum {
COLUMN_PAGE_STRING , COLUMN_PIXBUF , COLUMN_THUMBNAIL_SET , COLUMN_JOB ,
NUM_COLUMNS
}
enum { PROP_0 , PROP_WIDGET }
Functions
G_DEFINE_TYPE_EXTENDED (EvSidebarThumbnails, ev_sidebar_thumbnails, GTK_TYPE_BOX, 0, G_IMPLEMENT_INTERFACE(EV_TYPE_SIDEBAR_PAGE, ev_sidebar_thumbnails_page_iface_init))
GtkWidget * ev_sidebar_thumbnails_new (void)
Macro Definition Documentation
EV_THUMBNAILS_SIZE_CACHE_KEY
#define EV_THUMBNAILS_SIZE_CACHE_KEY "ev-thumbnails-size-cache"
MAX_ICON_VIEW_PAGE_COUNT
#define MAX_ICON_VIEW_PAGE_COUNT 1500
Definition at line 46 of file ev-sidebar-thumbnails.c.
THUMBNAIL_WIDTH
#define THUMBNAIL_WIDTH 100
Definition at line 42 of file ev-sidebar-thumbnails.c.
Referenced by G_DEFINE_TYPE_EXTENDED().
Typedef Documentation
EvThumbsSize
typedef struct _EvThumbsSize EvThumbsSize
EvThumbsSizeCache
typedef struct _EvThumbsSizeCache EvThumbsSizeCache
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COLUMN_PAGE_STRING
COLUMN_PIXBUF
COLUMN_THUMBNAIL_SET
COLUMN_JOB
NUM_COLUMNS
Definition at line 80 of file ev-sidebar-thumbnails.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_WIDGET
Definition at line 88 of file ev-sidebar-thumbnails.c.
Function Documentation
ev_sidebar_thumbnails_new()
GtkWidget * ev_sidebar_thumbnails_new (void)
Definition at line 336 of file ev-sidebar-thumbnails.c.
References EV_TYPE_SIDEBAR_THUMBNAILS, and NULL.
G_DEFINE_TYPE_EXTENDED()
G_DEFINE_TYPE_EXTENDED (EvSidebarThumbnails , ev_sidebar_thumbnails , GTK_TYPE_BOX , 0 , G_IMPLEMENT_INTERFACE(EV_TYPE_SIDEBAR_PAGE, ev_sidebar_thumbnails_page_iface_init))
Definition at line 102 of file ev-sidebar-thumbnails.c.
References ev_document_get_n_pages(), ev_document_get_page(), ev_document_get_page_size(), EV_DOCUMENT_THUMBNAILS, ev_document_thumbnails_get_dimensions(), ev_render_context_new(), ev_render_context_set_page(), ev_render_context_set_scale(), EV_TYPE_SIDEBAR_PAGE, FALSE, _EvDocument::iswebdocument, NULL, THUMBNAIL_WIDTH, and TRUE.