MATE Desktop Environment: ev-stock-icons.h File Reference
ev-stock-icons.h File Reference
#include <gdk/gdk.h>
Macros
#define EV_STOCK_ZOOM "zoom"
#define EV_STOCK_ZOOM_PAGE "zoom-fit-height"
#define EV_STOCK_ZOOM_WIDTH "zoom-fit-width"
#define EV_STOCK_VIEW_DUAL "view-page-facing"
#define EV_STOCK_VIEW_CONTINUOUS "view-page-continuous"
#define EV_STOCK_ROTATE_LEFT "object-rotate-left"
#define EV_STOCK_ROTATE_RIGHT "object-rotate-right"
#define EV_STOCK_RUN_PRESENTATION "x-office-presentation"
#define EV_STOCK_VISIBLE "eye"
#define EV_STOCK_RESIZE_SE "resize-se"
#define EV_STOCK_RESIZE_SW "resize-sw"
#define EV_STOCK_CLOSE "close"
#define EV_STOCK_INVERTED_COLORS "stock_filters-invert"
#define EV_STOCK_ATTACHMENT "mail-attachment"
#define EV_STOCK_SEND_TO "document-send"
Functions
void ev_stock_icons_init (void)
void ev_stock_icons_set_screen (GdkScreen *screen)
Macro Definition Documentation
EV_STOCK_ATTACHMENT
#define EV_STOCK_ATTACHMENT "mail-attachment"
Definition at line 49 of file ev-stock-icons.h.
EV_STOCK_CLOSE
#define EV_STOCK_CLOSE "close"
Definition at line 47 of file ev-stock-icons.h.
EV_STOCK_INVERTED_COLORS
#define EV_STOCK_INVERTED_COLORS "stock_filters-invert"
Definition at line 48 of file ev-stock-icons.h.
EV_STOCK_RESIZE_SE
#define EV_STOCK_RESIZE_SE "resize-se"
Definition at line 45 of file ev-stock-icons.h.
EV_STOCK_RESIZE_SW
#define EV_STOCK_RESIZE_SW "resize-sw"
Definition at line 46 of file ev-stock-icons.h.
EV_STOCK_ROTATE_LEFT
#define EV_STOCK_ROTATE_LEFT "object-rotate-left"
Definition at line 41 of file ev-stock-icons.h.
EV_STOCK_ROTATE_RIGHT
#define EV_STOCK_ROTATE_RIGHT "object-rotate-right"
Definition at line 42 of file ev-stock-icons.h.
EV_STOCK_RUN_PRESENTATION
#define EV_STOCK_RUN_PRESENTATION "x-office-presentation"
Definition at line 43 of file ev-stock-icons.h.
EV_STOCK_SEND_TO
#define EV_STOCK_SEND_TO "document-send"
Definition at line 50 of file ev-stock-icons.h.
EV_STOCK_VIEW_CONTINUOUS
#define EV_STOCK_VIEW_CONTINUOUS "view-page-continuous"
Definition at line 40 of file ev-stock-icons.h.
EV_STOCK_VIEW_DUAL
#define EV_STOCK_VIEW_DUAL "view-page-facing"
Definition at line 39 of file ev-stock-icons.h.
EV_STOCK_VISIBLE
#define EV_STOCK_VISIBLE "eye"
Definition at line 44 of file ev-stock-icons.h.
EV_STOCK_ZOOM
#define EV_STOCK_ZOOM "zoom"
Definition at line 36 of file ev-stock-icons.h.
EV_STOCK_ZOOM_PAGE
#define EV_STOCK_ZOOM_PAGE "zoom-fit-height"
Definition at line 37 of file ev-stock-icons.h.
EV_STOCK_ZOOM_WIDTH
#define EV_STOCK_ZOOM_WIDTH "zoom-fit-width"
Definition at line 38 of file ev-stock-icons.h.
Function Documentation
ev_stock_icons_init()
void ev_stock_icons_init (void)
ev_stock_icons_init:
Creates a new icon factory, adding the base stock icons to it.
Definition at line 90 of file ev-stock-icons.c.
References set.
Referenced by main(), and main().
ev_stock_icons_set_screen()
void ev_stock_icons_set_screen (GdkScreen * screen)
Definition at line 121 of file ev-stock-icons.c.
Referenced by ev_application_open_window().