MATE Desktop Environment: ev-sidebar.c File Reference
ev-sidebar.c File Reference
#include <string.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <libmate-desktop/mate-image-menu-item.h>
#include "ev-sidebar.h"
#include "ev-sidebar-page.h"
Enumerations
enum { PROP_0 , PROP_CURRENT_PAGE }
enum {
PAGE_COLUMN_TITLE , PAGE_COLUMN_MENU_ITEM , PAGE_COLUMN_MAIN_WIDGET , PAGE_COLUMN_NOTEBOOK_INDEX ,
PAGE_COLUMN_NUM_COLS
}
Functions
void ev_sidebar_set_page (EvSidebar *ev_sidebar, GtkWidget *main_widget)
GtkWidget * ev_sidebar_new (void)
void ev_sidebar_add_page (EvSidebar *ev_sidebar, GtkWidget *main_widget)
void ev_sidebar_set_model (EvSidebar *sidebar, EvDocumentModel *model)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_CURRENT_PAGE
Definition at line 39 of file ev-sidebar.c.
anonymous enum
anonymous enum
Enumerator
PAGE_COLUMN_TITLE
PAGE_COLUMN_MENU_ITEM
PAGE_COLUMN_MAIN_WIDGET
PAGE_COLUMN_NOTEBOOK_INDEX
PAGE_COLUMN_NUM_COLS
Definition at line 45 of file ev-sidebar.c.
Function Documentation
ev_sidebar_add_page()
void ev_sidebar_add_page (EvSidebar * ev_sidebar, GtkWidget * main_widget)
Definition at line 412 of file ev-sidebar.c.
References EV_IS_SIDEBAR, EV_IS_SIDEBAR_PAGE, EV_SIDEBAR_PAGE, ev_sidebar_page_get_label(), ev_sidebar_page_set_model(), mate_image_menu_item_new_with_label(), NULL, PAGE_COLUMN_MAIN_WIDGET, PAGE_COLUMN_MENU_ITEM, PAGE_COLUMN_NOTEBOOK_INDEX, PAGE_COLUMN_TITLE, and _EvSidebar::priv.
ev_sidebar_new()
GtkWidget * ev_sidebar_new (void)
Definition at line 402 of file ev-sidebar.c.
References EV_TYPE_SIDEBAR, and NULL.
ev_sidebar_set_model()
void ev_sidebar_set_model (EvSidebar * sidebar, EvDocumentModel * model)
Definition at line 506 of file ev-sidebar.c.
References EV_IS_DOCUMENT_MODEL, EV_IS_SIDEBAR, and _EvSidebar::priv.
ev_sidebar_set_page()
void ev_sidebar_set_page (EvSidebar * ev_sidebar, GtkWidget * main_widget)
Definition at line 103 of file ev-sidebar.c.
References FALSE, PAGE_COLUMN_MAIN_WIDGET, and _EvSidebar::priv.