MATE Desktop Environment: ev-timeline.c File Reference
ev-timeline.c File Reference
#include <glib.h>
#include <math.h>
#include "ev-timeline.h"
Macros
#define MSECS_PER_SEC 1000
#define FRAME_INTERVAL(nframes)
#define DEFAULT_FPS 30
Typedefs
typedef struct EvTimelinePrivate EvTimelinePrivate
Enumerations
enum { PROP_0 , PROP_FPS , PROP_DURATION , PROP_LOOP }
enum {
STARTED , PAUSED , FINISHED , FRAME ,
LAST_SIGNAL
}
Functions
EvTimeline * ev_timeline_new (guint duration)
void ev_timeline_start (EvTimeline *timeline)
void ev_timeline_pause (EvTimeline *timeline)
void ev_timeline_rewind (EvTimeline *timeline)
gboolean ev_timeline_is_running (EvTimeline *timeline)
guint ev_timeline_get_fps (EvTimeline *timeline)
void ev_timeline_set_fps (EvTimeline *timeline, guint fps)
gboolean ev_timeline_get_loop (EvTimeline *timeline)
void ev_timeline_set_loop (EvTimeline *timeline, gboolean loop)
void ev_timeline_set_duration (EvTimeline *timeline, guint duration)
guint ev_timeline_get_duration (EvTimeline *timeline)
gdouble ev_timeline_get_progress (EvTimeline *timeline)
Macro Definition Documentation
DEFAULT_FPS
#define DEFAULT_FPS 30
Definition at line 28 of file ev-timeline.c.
FRAME_INTERVAL
#define FRAME_INTERVAL (nframes)
Value:
(MSECS_PER_SEC / nframes)
Definition at line 27 of file ev-timeline.c.
Referenced by ev_timeline_set_fps(), msd_timeline_set_fps(), and msd_timeline_start().
MSECS_PER_SEC
#define MSECS_PER_SEC 1000
Definition at line 26 of file ev-timeline.c.
Typedef Documentation
EvTimelinePrivate
typedef struct EvTimelinePrivate EvTimelinePrivate
Definition at line 30 of file ev-timeline.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
STARTED
PAUSED
FINISHED
FRAME
LAST_SIGNAL
Definition at line 49 of file ev-timeline.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_FPS
PROP_DURATION
PROP_LOOP
Definition at line 42 of file ev-timeline.c.
Function Documentation
ev_timeline_get_duration()
guint ev_timeline_get_duration (EvTimeline * timeline)
Definition at line 411 of file ev-timeline.c.
References EV_IS_TIMELINE.
ev_timeline_get_fps()
guint ev_timeline_get_fps (EvTimeline * timeline)
Definition at line 338 of file ev-timeline.c.
References EV_IS_TIMELINE.
ev_timeline_get_loop()
gboolean ev_timeline_get_loop (EvTimeline * timeline)
Definition at line 371 of file ev-timeline.c.
References EV_IS_TIMELINE, and FALSE.
ev_timeline_get_progress()
gdouble ev_timeline_get_progress (EvTimeline * timeline)
Definition at line 423 of file ev-timeline.c.
References EV_IS_TIMELINE, and NULL.
Referenced by ev_transition_animation_paint().
ev_timeline_is_running()
gboolean ev_timeline_is_running (EvTimeline * timeline)
Definition at line 326 of file ev-timeline.c.
References EV_IS_TIMELINE, and FALSE.
Referenced by ev_timeline_rewind(), and ev_timeline_set_fps().
ev_timeline_new()
EvTimeline * ev_timeline_new (guint duration)
Definition at line 273 of file ev-timeline.c.
References EV_TYPE_TIMELINE, and NULL.
ev_timeline_pause()
void ev_timeline_pause (EvTimeline * timeline)
Definition at line 289 of file ev-timeline.c.
References EV_IS_TIMELINE, and PAUSED.
ev_timeline_rewind()
void ev_timeline_rewind (EvTimeline * timeline)
Definition at line 306 of file ev-timeline.c.
References EV_IS_TIMELINE, ev_timeline_is_running(), and NULL.
ev_timeline_set_duration()
void ev_timeline_set_duration (EvTimeline * timeline, guint duration)
Definition at line 396 of file ev-timeline.c.
References EV_IS_TIMELINE.
ev_timeline_set_fps()
void ev_timeline_set_fps (EvTimeline * timeline, guint fps)
Definition at line 349 of file ev-timeline.c.
References EV_IS_TIMELINE, ev_timeline_is_running(), and FRAME_INTERVAL.
ev_timeline_set_loop()
void ev_timeline_set_loop (EvTimeline * timeline, gboolean loop)
Definition at line 382 of file ev-timeline.c.
References EV_IS_TIMELINE, FALSE, and loop.
ev_timeline_start()
void ev_timeline_start (EvTimeline * timeline)
Definition at line 281 of file ev-timeline.c.
References EV_IS_TIMELINE, and EV_TIMELINE_GET_CLASS.
Referenced by ev_transition_animation_set_dest_surface(), and ev_transition_animation_set_origin_surface().