MATE Desktop Environment: ev-transition-animation.c File Reference
ev-transition-animation.c File Reference
#include <cairo.h>
#include <gdk/gdk.h>
#include "ev-transition-animation.h"
#include "ev-timeline.h"
Macros
#define N_BLINDS 6
Typedefs
typedef struct EvTransitionAnimationPrivate EvTransitionAnimationPrivate
Enumerations
enum { PROP_0 , PROP_EFFECT , PROP_ORIGIN_SURFACE , PROP_DEST_SURFACE }
Functions
void ev_transition_animation_paint (EvTransitionAnimation *animation, cairo_t *cr, GdkRectangle page_area)
EvTransitionAnimation * ev_transition_animation_new (EvTransitionEffect *effect)
void ev_transition_animation_set_origin_surface (EvTransitionAnimation *animation, cairo_surface_t *origin_surface)
void ev_transition_animation_set_dest_surface (EvTransitionAnimation *animation, cairo_surface_t *dest_surface)
gboolean ev_transition_animation_ready (EvTransitionAnimation *animation)
Macro Definition Documentation
N_BLINDS
#define N_BLINDS 6
Definition at line 27 of file ev-transition-animation.c.
Typedef Documentation
EvTransitionAnimationPrivate
typedef struct EvTransitionAnimationPrivate EvTransitionAnimationPrivate
Definition at line 29 of file ev-transition-animation.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_EFFECT
PROP_ORIGIN_SURFACE
PROP_DEST_SURFACE
Definition at line 37 of file ev-transition-animation.c.
Function Documentation
ev_transition_animation_new()
EvTransitionAnimation * ev_transition_animation_new (EvTransitionEffect * effect)
Definition at line 600 of file ev-transition-animation.c.
References EV_IS_TRANSITION_EFFECT, EV_TYPE_TRANSITION_ANIMATION, and NULL.
ev_transition_animation_paint()
void ev_transition_animation_paint (EvTransitionAnimation * animation, cairo_t * cr, GdkRectangle page_area)
Definition at line 530 of file ev-transition-animation.c.
References EV_IS_TRANSITION_ANIMATION, EV_TIMELINE, ev_timeline_get_progress(), EV_TRANSITION_EFFECT_BLINDS, EV_TRANSITION_EFFECT_BOX, EV_TRANSITION_EFFECT_COVER, EV_TRANSITION_EFFECT_DISSOLVE, EV_TRANSITION_EFFECT_FADE, EV_TRANSITION_EFFECT_PUSH, EV_TRANSITION_EFFECT_REPLACE, EV_TRANSITION_EFFECT_SPLIT, EV_TRANSITION_EFFECT_UNCOVER, EV_TRANSITION_EFFECT_WIPE, EV_TYPE_TRANSITION_EFFECT_TYPE, and NULL.
ev_transition_animation_ready()
gboolean ev_transition_animation_ready (EvTransitionAnimation * animation)
Definition at line 662 of file ev-transition-animation.c.
References EV_IS_TRANSITION_ANIMATION, FALSE, and NULL.
ev_transition_animation_set_dest_surface()
void ev_transition_animation_set_dest_surface (EvTransitionAnimation * animation, cairo_surface_t * dest_surface)
Definition at line 636 of file ev-transition-animation.c.
References EV_IS_TRANSITION_ANIMATION, EV_TIMELINE, and ev_timeline_start().
ev_transition_animation_set_origin_surface()
void ev_transition_animation_set_origin_surface (EvTransitionAnimation * animation, cairo_surface_t * origin_surface)
Definition at line 610 of file ev-transition-animation.c.
References EV_IS_TRANSITION_ANIMATION, EV_TIMELINE, and ev_timeline_start().