MATE Desktop Environment: ev-view.h File Reference
ev-view.h File Reference
#include <gtk/gtk.h>
#include <atril-document.h>
#include "ev-document-model.h"
#include "ev-jobs.h"
Macros
#define EV_TYPE_VIEW (ev_view_get_type ())
#define EV_VIEW(obj)
#define EV_IS_VIEW(obj)
Typedefs
typedef struct _EvView EvView
typedef struct _EvViewClass EvViewClass
Functions
GType ev_view_get_type (void)
GtkWidget * ev_view_new (void)
void ev_view_set_model (EvView *view, EvDocumentModel *model)
EV_DEPRECATED void ev_view_set_loading (EvView *view, gboolean loading)
gboolean ev_view_is_loading (EvView *view)
void ev_view_reload (EvView *view)
void ev_view_set_page_cache_size (EvView *view, gsize cache_size)
void ev_view_copy (EvView *view)
void ev_view_copy_link_address (EvView *view, EvLinkAction *action)
void ev_view_select_all (EvView *view)
gboolean ev_view_get_has_selection (EvView *view)
gboolean ev_view_can_zoom_in (EvView *view)
void ev_view_zoom_in (EvView *view)
gboolean ev_view_can_zoom_out (EvView *view)
void ev_view_zoom_out (EvView *view)
void ev_view_zoom_reset (EvView *view)
void ev_view_zoom (EvView *view, gdouble factor)
void ev_view_find_next (EvView *view)
void ev_view_find_previous (EvView *view)
void ev_view_find_search_changed (EvView *view)
void ev_view_find_set_highlight_search (EvView *view, gboolean value)
void ev_view_find_changed (EvView *view, GList **results, gint page)
void ev_view_find_cancel (EvView *view)
void ev_view_highlight_forward_search (EvView *view, EvSourceLink *link)
void ev_view_hide_cursor (EvView *view)
void ev_view_show_cursor (EvView *view)
void ev_view_scroll (EvView *view, GtkScrollType scroll, gboolean horizontal)
void ev_view_handle_link (EvView *view, EvLink *link)
gboolean ev_view_next_page (EvView *view)
gboolean ev_view_previous_page (EvView *view)
void ev_view_autoscroll_start (EvView *view)
void ev_view_autoscroll_stop (EvView *view)
gboolean ev_view_get_page_extents (EvView *view, gint page, GdkRectangle *page_area, GtkBorder *border)
void ev_view_focus_annotation (EvView *view, EvMapping *annot_mapping)
void ev_view_begin_add_annotation (EvView *view, EvAnnotationType annot_type)
void ev_view_cancel_add_annotation (EvView *view)
void ev_view_remove_annotation (EvView *view, EvAnnotation *annot)
void ev_view_disconnect_handlers (EvView *view)
gboolean ev_view_supports_caret_navigation (EvView *view)
gboolean ev_view_is_caret_navigation_enabled (EvView *view)
void ev_view_set_caret_navigation_enabled (EvView *view, gboolean enabled)
void ev_view_set_caret_cursor_position (EvView *view, guint page, guint offset)
Macro Definition Documentation
EV_IS_VIEW
#define EV_IS_VIEW (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), EV_TYPE_VIEW))
Definition at line 38 of file ev-view.h.
Referenced by ev_view_accessible_new(), ev_view_autoscroll_start(), ev_view_autoscroll_stop(), ev_view_is_caret_navigation_enabled(), ev_view_next_page(), ev_view_previous_page(), ev_view_remove_annotation(), ev_view_set_caret_cursor_position(), ev_view_set_caret_navigation_enabled(), and ev_view_set_model().
EV_TYPE_VIEW
#define EV_TYPE_VIEW (ev_view_get_type ())
Definition at line 36 of file ev-view.h.
Referenced by ev_view_new().
EV_VIEW
#define EV_VIEW (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), EV_TYPE_VIEW, EvView))
Definition at line 37 of file ev-view.h.
Referenced by _transform_doc_rect_to_atk_rect(), ev_page_accessible_get_view(), ev_pixbuf_cache_get_selection_surface(), ev_view_accessible_get_relevant_page(), ev_view_accessible_is_doc_rect_showing(), ev_view_accessible_new(), and ev_window_open_document().
Typedef Documentation
EvView
typedef struct _EvView EvView
Definition at line 40 of file ev-view.h.
EvViewClass
typedef struct _EvViewClass EvViewClass
Definition at line 41 of file ev-view.h.
Function Documentation
ev_view_autoscroll_start()
void ev_view_autoscroll_start (EvView * view)
Definition at line 6748 of file ev-view.c.
References AutoScrollInfo::autoscrolling, ev_document_misc_get_pointer_position(), EV_IS_VIEW, _EvView::scroll_info, AutoScrollInfo::timeout_id, and TRUE.
ev_view_autoscroll_stop()
void ev_view_autoscroll_stop (EvView * view)
Definition at line 6767 of file ev-view.c.
References AutoScrollInfo::autoscrolling, ev_document_misc_get_pointer_position(), EV_IS_VIEW, FALSE, _EvView::scroll_info, and AutoScrollInfo::timeout_id.
ev_view_begin_add_annotation()
void ev_view_begin_add_annotation (EvView * view, EvAnnotationType annot_type)
Definition at line 3145 of file ev-view.c.
References _EvView::adding_annot, _EvView::adding_annot_type, EV_ANNOTATION_TYPE_UNKNOWN, EV_VIEW_CURSOR_ADD, and TRUE.
ev_view_can_zoom_in()
gboolean ev_view_can_zoom_in (EvView * view)
Definition at line 7029 of file ev-view.c.
References ev_document_model_get_max_scale(), _EvView::model, _EvView::scale, and ZOOM_IN_FACTOR.
ev_view_can_zoom_out()
gboolean ev_view_can_zoom_out (EvView * view)
Definition at line 7035 of file ev-view.c.
References ev_document_model_get_min_scale(), _EvView::model, _EvView::scale, and ZOOM_OUT_FACTOR.
ev_view_cancel_add_annotation()
void ev_view_cancel_add_annotation (EvView * view)
Definition at line 3160 of file ev-view.c.
References _EvView::adding_annot, ev_document_misc_get_pointer_position(), and FALSE.
ev_view_copy()
void ev_view_copy (EvView * view)
Definition at line 7958 of file ev-view.c.
References _EvView::document, and EV_IS_SELECTION.
ev_view_copy_link_address()
void ev_view_copy_link_address (EvView * view, EvLinkAction * action)
Definition at line 8046 of file ev-view.c.
References action, ev_link_action_get_uri(), and _EvView::link_selected.
ev_view_disconnect_handlers()
void ev_view_disconnect_handlers (EvView * view)
ev_view_disconnect_handlers @view: EvView instance
Disconnect all signal handlers from the model, to ensure error free operation of the webview, we have an equivalent function for the webview.
Definition at line 8134 of file ev-view.c.
References _EvView::model.
ev_view_find_cancel()
void ev_view_find_cancel (EvView * view)
Definition at line 7526 of file ev-view.c.
References _EvView::find_pages, and NULL.
ev_view_find_changed()
void ev_view_find_changed (EvView * view, GList ** results, gint page)
Definition at line 7463 of file ev-view.c.
References _EvView::current_page, EV_VIEW_FIND_NEXT, _EvView::find_pages, _EvView::jump_to_find_result, and TRUE.
ev_view_find_next()
void ev_view_find_next (EvView * view)
Definition at line 7478 of file ev-view.c.
References _EvView::current_page, EV_VIEW_FIND_NEXT, and _EvView::find_result.
ev_view_find_previous()
void ev_view_find_previous (EvView * view)
Definition at line 7496 of file ev-view.c.
References _EvView::current_page, EV_VIEW_FIND_PREV, _EvView::find_result, and MAX.
ev_view_find_search_changed()
void ev_view_find_search_changed (EvView * view)
Definition at line 7511 of file ev-view.c.
References _EvView::find_pages, _EvView::jump_to_find_result, NULL, and TRUE.
ev_view_find_set_highlight_search()
void ev_view_find_set_highlight_search (EvView * view, gboolean value)
Definition at line 7519 of file ev-view.c.
References _EvView::highlight_find_results.
ev_view_focus_annotation()
void ev_view_focus_annotation (EvView * view, EvMapping * annot_mapping)
Definition at line 3133 of file ev-view.c.
References _ev_view_set_focused_element(), _EvMapping::data, _EvView::document, EV_ANNOTATION, ev_annotation_get_page_index(), and EV_IS_DOCUMENT_ANNOTATIONS.
ev_view_get_has_selection()
gboolean ev_view_get_has_selection (EvView * view)
Definition at line 7895 of file ev-view.c.
References NULL, _EvView::selection_info, and SelectionInfo::selections.
ev_view_get_page_extents()
gboolean ev_view_get_page_extents (EvView * view, gint page, GdkRectangle * page_area, GtkBorder * border)
Definition at line 1175 of file ev-view.c.
References _EvView::continuous, _EvView::document, ev_document_get_n_pages(), MAX, NULL, _EvView::spacing, and TRUE.
Referenced by _ev_view_transform_doc_point_to_view_point(), and _ev_view_transform_doc_rect_to_view_rect().
ev_view_get_type()
GType ev_view_get_type (void)
References action, and EV_DEPRECATED.
ev_view_handle_link()
void ev_view_handle_link (EvView * view, EvLink * link)
Definition at line 1833 of file ev-view.c.
References action, _EvView::current_page, dest, _EvView::document, EV_DOCUMENT_LAYERS, ev_document_layers_hide_layer(), ev_document_layers_layer_is_visible(), ev_document_layers_show_layer(), EV_LAYER, ev_link_action_get_action_type(), ev_link_action_get_dest(), ev_link_action_get_hide_list(), ev_link_action_get_show_list(), ev_link_action_get_toggle_list(), EV_LINK_ACTION_TYPE_EXTERNAL_URI, EV_LINK_ACTION_TYPE_GOTO_DEST, EV_LINK_ACTION_TYPE_GOTO_REMOTE, EV_LINK_ACTION_TYPE_LAUNCH, EV_LINK_ACTION_TYPE_LAYERS_STATE, EV_LINK_ACTION_TYPE_NAMED, ev_link_get_action(), NULL, SIGNAL_EXTERNAL_LINK, SIGNAL_HANDLE_LINK, and SIGNAL_LAYERS_CHANGED.
Referenced by ev_window_open_document().
ev_view_hide_cursor()
void ev_view_hide_cursor (EvView * view)
Definition at line 8083 of file ev-view.c.
References EV_VIEW_CURSOR_HIDDEN.
ev_view_highlight_forward_search()
void ev_view_highlight_forward_search (EvView * view, EvSourceLink * link)
ev_view_is_caret_navigation_enabled()
gboolean ev_view_is_caret_navigation_enabled (EvView * view)
Definition at line 3490 of file ev-view.c.
References _EvView::caret_enabled, EV_IS_VIEW, and FALSE.
Referenced by G_DEFINE_TYPE_WITH_CODE().
ev_view_is_loading()
gboolean ev_view_is_loading (EvView * view)
Definition at line 6710 of file ev-view.c.
References _EvView::loading.
ev_view_new()
GtkWidget * ev_view_new (void)
Definition at line 6629 of file ev-view.c.
References EV_TYPE_VIEW, and NULL.
ev_view_next_page()
gboolean ev_view_next_page (EvView * view)
Definition at line 8095 of file ev-view.c.
References _EvView::current_page, ev_document_model_set_page(), EV_IS_VIEW, FALSE, _EvView::model, and TRUE.
Referenced by ev_view_scroll().
ev_view_previous_page()
gboolean ev_view_previous_page (EvView * view)
Definition at line 8111 of file ev-view.c.
References _EvView::current_page, ev_document_model_set_page(), EV_IS_VIEW, FALSE, _EvView::model, and TRUE.
Referenced by ev_view_scroll().
ev_view_reload()
void ev_view_reload (EvView * view)
Definition at line 7020 of file ev-view.c.
References ev_pixbuf_cache_clear(), and _EvView::pixbuf_cache.
ev_view_remove_annotation()
void ev_view_remove_annotation (EvView * view, EvAnnotation * annot)
Definition at line 3173 of file ev-view.c.
References _ev_view_set_focused_element(), _EvView::document, ev_annotation_get_page_index(), EV_DOCUMENT_ANNOTATIONS, ev_document_annotations_remove_annotation(), ev_document_doc_mutex_lock(), ev_document_doc_mutex_unlock(), EV_IS_ANNOTATION, EV_IS_ANNOTATION_MARKUP, EV_IS_VIEW, ev_page_cache_mark_dirty(), EV_PAGE_DATA_INCLUDE_ANNOTS, NULL, _EvView::page_cache, SIGNAL_ANNOT_REMOVED, EvViewWindowChild::window, and _EvView::window_children.
ev_view_scroll()
void ev_view_scroll (EvView * view, GtkScrollType scroll, gboolean horizontal)
Definition at line 934 of file ev-view.c.
References _EvView::current_page, _EvView::document, ev_document_get_n_pages(), ev_view_next_page(), ev_view_previous_page(), FALSE, _EvView::hadjustment, _EvView::jump_to_find_result, _EvView::key_binding_handled, MAX, MIN, TRUE, and _EvView::vadjustment.
ev_view_select_all()
void ev_view_select_all (EvView * view)
Definition at line 7865 of file ev-view.c.
References _EvView::document, ev_document_get_n_pages(), EV_SELECTION_STYLE_GLYPH, NULL, EvViewSelection::page, EvViewSelection::rect, _EvView::rotation, EvViewSelection::style, _EvRectangle::x1, _EvRectangle::x2, _EvRectangle::y1, and _EvRectangle::y2.
ev_view_set_caret_cursor_position()
void ev_view_set_caret_cursor_position (EvView * view, guint page, guint offset)
Definition at line 3498 of file ev-view.c.
References _EvView::caret_enabled, _EvView::cursor_offset, _EvView::cursor_page, _EvView::document, ev_document_get_n_pages(), EV_IS_DOCUMENT, EV_IS_VIEW, and SIGNAL_CURSOR_MOVED.
ev_view_set_caret_navigation_enabled()
void ev_view_set_caret_navigation_enabled (EvView * view, gboolean enabled)
Definition at line 3475 of file ev-view.c.
References _EvView::caret_enabled, and EV_IS_VIEW.
ev_view_set_loading()
EV_DEPRECATED void ev_view_set_loading (EvView * view, gboolean loading)
Definition at line 6699 of file ev-view.c.
References _EvView::loading.
ev_view_set_model()
void ev_view_set_model (EvView * view, EvDocumentModel * model)
Definition at line 6942 of file ev-view.c.
References _EvView::accessible, _EvView::continuous, ev_document_model_get_continuous(), ev_document_model_get_fullscreen(), ev_document_model_get_page_layout(), ev_document_model_get_rotation(), ev_document_model_get_scale(), ev_document_model_get_sizing_mode(), EV_IS_DOCUMENT_MODEL, EV_IS_VIEW, EV_VIEW_ACCESSIBLE, ev_view_accessible_set_model(), _EvView::fullscreen, _EvView::model, NULL, _EvView::page_layout, _EvView::rotation, _EvView::scale, and _EvView::sizing_mode.
ev_view_set_page_cache_size()
void ev_view_set_page_cache_size (EvView * view, gsize cache_size)
ev_view_set_page_cache_size: @view: @cache_size:
Sets the maximum size in bytes that will be used to cache rendered pages. Use 0 to disable caching rendered pages.
Note that this limit doesn't affect the current visible page range, which will always be rendered. In order to limit the total memory used you have to use ev_document_model_set_max_scale() too.
Definition at line 6687 of file ev-view.c.
References ev_pixbuf_cache_set_max_size(), _EvView::pixbuf_cache, and _EvView::pixbuf_cache_size.
ev_view_show_cursor()
void ev_view_show_cursor (EvView * view)
Definition at line 8089 of file ev-view.c.
References EV_VIEW_CURSOR_NORMAL.
ev_view_supports_caret_navigation()
gboolean ev_view_supports_caret_navigation (EvView * view)
Definition at line 3460 of file ev-view.c.
References _EvView::document, EV_DOCUMENT_TEXT_GET_IFACE, EV_IS_DOCUMENT_TEXT, FALSE, _EvDocumentTextInterface::get_text, _EvDocumentTextInterface::get_text_layout, and TRUE.
ev_view_zoom()
void ev_view_zoom (EvView * view, gdouble factor)
Definition at line 7041 of file ev-view.c.
References ev_document_model_get_scale(), ev_document_model_set_scale(), EV_SIZING_FREE, _EvView::model, _EvView::pending_scroll, SCROLL_TO_CENTER, and _EvView::sizing_mode.
Referenced by ev_view_zoom_in(), and ev_view_zoom_out().
ev_view_zoom_in()
void ev_view_zoom_in (EvView * view)
Definition at line 7053 of file ev-view.c.
References ev_view_zoom(), and ZOOM_IN_FACTOR.
ev_view_zoom_out()
void ev_view_zoom_out (EvView * view)
Definition at line 7059 of file ev-view.c.
References ev_view_zoom(), and ZOOM_OUT_FACTOR.
ev_view_zoom_reset()
void ev_view_zoom_reset (EvView * view)
Definition at line 7065 of file ev-view.c.
References ev_document_model_set_scale(), EV_SIZING_FREE, _EvView::model, and _EvView::sizing_mode.