MATE Desktop Environment: ev-view-accessible.h File Reference
ev-view-accessible.h File Reference
#include <gtk/gtk-a11y.h>
#include "ev-document-model.h"
Classes
struct _EvViewAccessible
struct _EvViewAccessibleClass
Macros
#define EV_TYPE_VIEW_ACCESSIBLE (ev_view_accessible_get_type ())
#define EV_VIEW_ACCESSIBLE(obj)
#define EV_IS_VIEW_ACCESSIBLE(obj)
Typedefs
typedef struct _EvViewAccessible EvViewAccessible
typedef struct _EvViewAccessibleClass EvViewAccessibleClass
typedef struct _EvViewAccessiblePrivate EvViewAccessiblePrivate
Functions
GType ev_view_accessible_get_type (void)
AtkObject * ev_view_accessible_new (GtkWidget *widget)
void ev_view_accessible_set_model (EvViewAccessible *accessible, EvDocumentModel *model)
gint ev_view_accessible_get_n_pages (EvViewAccessible *accessible)
gint ev_view_accessible_get_relevant_page (EvViewAccessible *accessible)
void ev_view_accessible_set_page_range (EvViewAccessible *accessible, gint start, gint end)
void _transform_doc_rect_to_atk_rect (EvViewAccessible *accessible, gint page, EvRectangle *doc_rect, EvRectangle *atk_rect, AtkCoordType coord_type)
gboolean ev_view_accessible_is_doc_rect_showing (EvViewAccessible *accessible, gint page, EvRectangle *doc_rect)
Macro Definition Documentation
EV_IS_VIEW_ACCESSIBLE
#define EV_IS_VIEW_ACCESSIBLE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), EV_TYPE_VIEW_ACCESSIBLE))
Definition at line 33 of file ev-view-accessible.h.
Referenced by ev_page_accessible_new(), ev_view_accessible_get_relevant_page(), and ev_view_accessible_set_page_range().
EV_TYPE_VIEW_ACCESSIBLE
#define EV_TYPE_VIEW_ACCESSIBLE (ev_view_accessible_get_type ())
Definition at line 31 of file ev-view-accessible.h.
Referenced by ev_view_accessible_new().
EV_VIEW_ACCESSIBLE
#define EV_VIEW_ACCESSIBLE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), EV_TYPE_VIEW_ACCESSIBLE, EvViewAccessible))
Definition at line 32 of file ev-view-accessible.h.
Referenced by ev_view_accessible_new(), and ev_view_set_model().
Typedef Documentation
EvViewAccessible
typedef struct _EvViewAccessible EvViewAccessible
Definition at line 35 of file ev-view-accessible.h.
EvViewAccessibleClass
typedef struct _EvViewAccessibleClass EvViewAccessibleClass
Definition at line 36 of file ev-view-accessible.h.
EvViewAccessiblePrivate
typedef struct _EvViewAccessiblePrivate EvViewAccessiblePrivate
Definition at line 37 of file ev-view-accessible.h.
Function Documentation
_transform_doc_rect_to_atk_rect()
void _transform_doc_rect_to_atk_rect (EvViewAccessible * accessible, gint page, EvRectangle * doc_rect, EvRectangle * atk_rect, AtkCoordType coord_type)
Definition at line 505 of file ev-view-accessible.c.
References _ev_view_transform_doc_rect_to_view_rect(), EV_VIEW, _EvView::scroll_x, _EvView::scroll_y, _EvRectangle::x1, _EvRectangle::x2, _EvRectangle::y1, and _EvRectangle::y2.
Referenced by G_DEFINE_TYPE_WITH_CODE(), and G_DEFINE_TYPE_WITH_CODE().
ev_view_accessible_get_n_pages()
gint ev_view_accessible_get_n_pages (EvViewAccessible * accessible)
Definition at line 133 of file ev-view-accessible.c.
References NULL, and _EvViewAccessible::priv.
ev_view_accessible_get_relevant_page()
gint ev_view_accessible_get_relevant_page (EvViewAccessible * accessible)
Definition at line 493 of file ev-view-accessible.c.
References EV_IS_VIEW_ACCESSIBLE, and EV_VIEW.
ev_view_accessible_get_type()
GType ev_view_accessible_get_type (void)
ev_view_accessible_is_doc_rect_showing()
gboolean ev_view_accessible_is_doc_rect_showing (EvViewAccessible * accessible, gint page, EvRectangle * doc_rect)
Definition at line 541 of file ev-view-accessible.c.
References _ev_view_transform_doc_rect_to_view_rect(), _EvView::end_page, EV_VIEW, FALSE, _EvView::hadjustment, and _EvView::vadjustment.
ev_view_accessible_new()
AtkObject * ev_view_accessible_new (GtkWidget * widget)
Definition at line 461 of file ev-view-accessible.c.
References EV_IS_VIEW, EV_TYPE_VIEW_ACCESSIBLE, EV_VIEW, EV_VIEW_ACCESSIBLE, ev_view_accessible_set_model(), _EvView::model, and NULL.
ev_view_accessible_set_model()
void ev_view_accessible_set_model (EvViewAccessible * accessible, EvDocumentModel * model)
Definition at line 415 of file ev-view-accessible.c.
References g_signal_handlers_disconnect_by_data, NULL, and _EvViewAccessible::priv.
Referenced by ev_view_accessible_new(), and ev_view_set_model().
ev_view_accessible_set_page_range()
void ev_view_accessible_set_page_range (EvViewAccessible * accessible, gint start, gint end)
Definition at line 567 of file ev-view-accessible.c.
References EV_IS_VIEW_ACCESSIBLE, FALSE, _EvViewAccessible::priv, and TRUE.