MATE Desktop Environment: ev-view-accessible.c File Reference
ev-view-accessible.c File Reference
#include <math.h>
#include <config.h>
#include <glib/gi18n-lib.h>
#include <gtk/gtk.h>
#include "ev-selection.h"
#include "ev-page-cache.h"
#include "ev-view-accessible.h"
#include "ev-view-private.h"
#include "ev-page-accessible.h"
Enumerations
enum { ACTION_SCROLL_UP , ACTION_SCROLL_DOWN , LAST_ACTION }
Functions
G_DEFINE_TYPE_WITH_CODE (EvViewAccessible, ev_view_accessible, GTK_TYPE_CONTAINER_ACCESSIBLE, G_IMPLEMENT_INTERFACE(ATK_TYPE_DOCUMENT, ev_view_accessible_document_iface_init))
gint ev_view_accessible_get_n_pages (EvViewAccessible *self)
void ev_view_accessible_set_model (EvViewAccessible *accessible, EvDocumentModel *model)
AtkObject * ev_view_accessible_new (GtkWidget *widget)
gint ev_view_accessible_get_relevant_page (EvViewAccessible *accessible)
void _transform_doc_rect_to_atk_rect (EvViewAccessible *accessible, gint page, EvRectangle *doc_rect, EvRectangle *atk_rect, AtkCoordType coord_type)
gboolean ev_view_accessible_is_doc_rect_showing (EvViewAccessible *accessible, gint page, EvRectangle *doc_rect)
void ev_view_accessible_set_page_range (EvViewAccessible *accessible, gint start, gint end)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ACTION_SCROLL_UP
ACTION_SCROLL_DOWN
LAST_ACTION
Definition at line 35 of file ev-view-accessible.c.
Function Documentation
_transform_doc_rect_to_atk_rect()
void _transform_doc_rect_to_atk_rect (EvViewAccessible * accessible, gint page, EvRectangle * doc_rect, EvRectangle * atk_rect, AtkCoordType coord_type)
Definition at line 505 of file ev-view-accessible.c.
References _ev_view_transform_doc_rect_to_view_rect(), EV_VIEW, _EvView::scroll_x, _EvView::scroll_y, _EvRectangle::x1, _EvRectangle::x2, _EvRectangle::y1, and _EvRectangle::y2.
Referenced by G_DEFINE_TYPE_WITH_CODE(), and G_DEFINE_TYPE_WITH_CODE().
ev_view_accessible_get_n_pages()
gint ev_view_accessible_get_n_pages (EvViewAccessible * self)
Definition at line 133 of file ev-view-accessible.c.
References NULL, and _EvViewAccessible::priv.
ev_view_accessible_get_relevant_page()
gint ev_view_accessible_get_relevant_page (EvViewAccessible * accessible)
Definition at line 493 of file ev-view-accessible.c.
References EV_IS_VIEW_ACCESSIBLE, and EV_VIEW.
ev_view_accessible_is_doc_rect_showing()
gboolean ev_view_accessible_is_doc_rect_showing (EvViewAccessible * accessible, gint page, EvRectangle * doc_rect)
Definition at line 541 of file ev-view-accessible.c.
References _ev_view_transform_doc_rect_to_view_rect(), _EvView::end_page, EV_VIEW, FALSE, _EvView::hadjustment, and _EvView::vadjustment.
ev_view_accessible_new()
AtkObject * ev_view_accessible_new (GtkWidget * widget)
Definition at line 461 of file ev-view-accessible.c.
References EV_IS_VIEW, EV_TYPE_VIEW_ACCESSIBLE, EV_VIEW, EV_VIEW_ACCESSIBLE, ev_view_accessible_set_model(), _EvView::model, and NULL.
ev_view_accessible_set_model()
void ev_view_accessible_set_model (EvViewAccessible * accessible, EvDocumentModel * model)
Definition at line 415 of file ev-view-accessible.c.
References g_signal_handlers_disconnect_by_data, NULL, and _EvViewAccessible::priv.
Referenced by ev_view_accessible_new(), and ev_view_set_model().
ev_view_accessible_set_page_range()
void ev_view_accessible_set_page_range (EvViewAccessible * accessible, gint start, gint end)
Definition at line 567 of file ev-view-accessible.c.
References EV_IS_VIEW_ACCESSIBLE, FALSE, _EvViewAccessible::priv, and TRUE.
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (EvViewAccessible , ev_view_accessible , GTK_TYPE_CONTAINER_ACCESSIBLE , G_IMPLEMENT_INTERFACE(ATK_TYPE_DOCUMENT, ev_view_accessible_document_iface_init))
Definition at line 70 of file ev-view-accessible.c.
References _EvView::current_page, _EvView::cursor_page, and ev_view_is_caret_navigation_enabled().