MATE Desktop Environment: ev-view-private.h File Reference
ev-view-private.h File Reference
#include "ev-view.h"
#include "ev-document-model.h"
#include "ev-pixbuf-cache.h"
#include "ev-page-cache.h"
#include "ev-jobs.h"
#include "ev-image.h"
#include "ev-form-field.h"
#include "ev-selection.h"
#include "ev-view-cursor.h"
Classes
struct DragInfo
struct AutoScrollInfo
struct SelectionInfo
struct ImageDNDInfo
struct EvViewWindowChild
struct _EvHeightToPageCache
struct _EvView
struct _EvViewClass
Macros
#define DRAG_HISTORY 10
Typedefs
typedef struct _EvHeightToPageCache EvHeightToPageCache
Enumerations
enum EvPanAction { EV_PAN_ACTION_NONE , EV_PAN_ACTION_NEXT , EV_PAN_ACTION_PREV }
enum PendingScroll { SCROLL_TO_KEEP_POSITION , SCROLL_TO_PAGE_POSITION , SCROLL_TO_CENTER , SCROLL_TO_FIND_LOCATION }
Functions
void _get_page_size_for_scale_and_rotation (EvDocument *document, gint page, gdouble scale, gint rotation, gint *page_width, gint *page_height)
void _ev_view_transform_view_point_to_doc_point (EvView *view, GdkPoint *view_point, GdkRectangle *page_area, double *doc_point_x, double *doc_point_y)
void _ev_view_transform_view_rect_to_doc_rect (EvView *view, GdkRectangle *view_rect, GdkRectangle *page_area, EvRectangle *doc_rect)
void _ev_view_transform_doc_point_to_view_point (EvView *view, int page, EvPoint *doc_point, GdkPoint *view_point)
void _ev_view_transform_doc_rect_to_view_rect (EvView *view, int page, EvRectangle *doc_rect, GdkRectangle *view_rect)
void _ev_view_get_selection_colors (EvView *view, GdkRGBA *bg_color, GdkRGBA *fg_color)
gint _ev_view_get_caret_cursor_offset_at_doc_point (EvView *view, gint page, gdouble doc_x, gdouble doc_y)
void _ev_view_clear_selection (EvView *view)
void _ev_view_set_selection (EvView *view, GdkPoint *start_point, GdkPoint *end_point)
void _ev_view_set_focused_element (EvView *view, EvMapping *element_mapping, gint page)
void _ev_view_focus_form_field (EvView *view, EvFormField *field)
Macro Definition Documentation
DRAG_HISTORY
#define DRAG_HISTORY 10
Definition at line 38 of file ev-view-private.h.
Typedef Documentation
EvHeightToPageCache
typedef struct _EvHeightToPageCache EvHeightToPageCache
Enumeration Type Documentation
EvPanAction
enum EvPanAction
Enumerator
EV_PAN_ACTION_NONE
EV_PAN_ACTION_NEXT
EV_PAN_ACTION_PREV
Definition at line 75 of file ev-view-private.h.
PendingScroll
enum PendingScroll
Enumerator
SCROLL_TO_KEEP_POSITION
SCROLL_TO_PAGE_POSITION
SCROLL_TO_CENTER
SCROLL_TO_FIND_LOCATION
Definition at line 102 of file ev-view-private.h.
Function Documentation
_ev_view_clear_selection()
void _ev_view_clear_selection (EvView * view)
Definition at line 7901 of file ev-view.c.
_ev_view_focus_form_field()
void _ev_view_focus_form_field (EvView * view, EvFormField * field)
Definition at line 2588 of file ev-view.c.
References _ev_view_set_focused_element(), _EvMapping::area, EV_IS_FORM_FIELD_BUTTON, EV_IS_FORM_FIELD_CHOICE, EV_IS_FORM_FIELD_SIGNATURE, EV_IS_FORM_FIELD_TEXT, ev_mapping_list_find(), ev_page_cache_get_form_field_mapping(), _EvPage::index, _EvFormField::is_read_only, NULL, _EvFormField::page, and _EvView::page_cache.
_ev_view_get_caret_cursor_offset_at_doc_point()
gint _ev_view_get_caret_cursor_offset_at_doc_point (EvView * view, gint page, gdouble doc_x, gdouble doc_y)
Definition at line 4281 of file ev-view.c.
References ev_page_cache_get_text_layout(), NULL, _EvView::page_cache, _EvRectangle::x1, _EvRectangle::x2, and _EvRectangle::y1.
_ev_view_get_selection_colors()
void _ev_view_get_selection_colors (EvView * view, GdkRGBA * bg_color, GdkRGBA * fg_color)
Definition at line 5743 of file ev-view.c.
_ev_view_set_focused_element()
void _ev_view_set_focused_element (EvView * view, EvMapping * element_mapping, gint page)
Definition at line 2075 of file ev-view.c.
References ev_document_model_set_page(), _EvView::focused_element, _EvView::focused_element_page, _EvView::model, NULL, _EvView::scroll_x, _EvView::scroll_y, and TRUE.
Referenced by _ev_view_focus_form_field(), ev_view_focus_annotation(), and ev_view_remove_annotation().
_ev_view_set_selection()
void _ev_view_set_selection (EvView * view, GdkPoint * start_point, GdkPoint * end_point)
Definition at line 7907 of file ev-view.c.
References EV_SELECTION_STYLE_GLYPH.
_ev_view_transform_doc_point_to_view_point()
void _ev_view_transform_doc_point_to_view_point (EvView * view, int page, EvPoint * doc_point, GdkPoint * view_point)
Definition at line 1314 of file ev-view.c.
References ev_view_get_page_extents(), _EvView::rotation, _EvView::scale, EvPoint::x, and EvPoint::y.
_ev_view_transform_doc_rect_to_view_rect()
void _ev_view_transform_doc_rect_to_view_rect (EvView * view, int page, EvRectangle * doc_rect, GdkRectangle * view_rect)
Definition at line 1351 of file ev-view.c.
References ev_view_get_page_extents(), _EvView::rotation, _EvView::scale, _EvRectangle::x1, _EvRectangle::x2, _EvRectangle::y1, and _EvRectangle::y2.
Referenced by _transform_doc_rect_to_atk_rect(), and ev_view_accessible_is_doc_rect_showing().
_ev_view_transform_view_point_to_doc_point()
void _ev_view_transform_view_point_to_doc_point (EvView * view, GdkPoint * view_point, GdkRectangle * page_area, double * doc_point_x, double * doc_point_y)
Definition at line 1291 of file ev-view.c.
References _EvView::scale.
_ev_view_transform_view_rect_to_doc_rect()
void _ev_view_transform_view_rect_to_doc_rect (EvView * view, GdkRectangle * view_rect, GdkRectangle * page_area, EvRectangle * doc_rect)
Definition at line 1302 of file ev-view.c.
References _EvView::scale, _EvRectangle::x1, _EvRectangle::x2, _EvRectangle::y1, and _EvRectangle::y2.
_get_page_size_for_scale_and_rotation()
void _get_page_size_for_scale_and_rotation (EvDocument * document, gint page, gdouble scale, gint rotation, gint * page_width, gint * page_height)
Definition at line 1096 of file ev-view.c.
References ev_document_get_page_size().
Referenced by ev_pixbuf_cache_reload_page().