MATE Desktop Environment: ev-window.c File Reference
ev-window.c File Reference
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <math.h>
#include <glib/gstdio.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
#include "egg-editable-toolbar.h"
#include "egg-toolbar-editor.h"
#include "egg-toolbars-model.h"
#include "eggfindbar.h"
#include "ephy-zoom-action.h"
#include "ephy-zoom.h"
#include "ev-application.h"
#include "ev-document-factory.h"
#include "ev-document-find.h"
#include "ev-document-fonts.h"
#include "ev-document-images.h"
#include "ev-document-links.h"
#include "ev-document-thumbnails.h"
#include "ev-document-annotations.h"
#include "ev-document-type-builtins.h"
#include "ev-document-misc.h"
#include "ev-file-exporter.h"
#include "ev-file-helpers.h"
#include "ev-file-monitor.h"
#include "ev-history.h"
#include "ev-image.h"
#include "ev-job-scheduler.h"
#include "ev-jobs.h"
#include "ev-loading-message.h"
#include "ev-message-area.h"
#include "ev-metadata.h"
#include "ev-navigation-action.h"
#include "ev-open-recent-action.h"
#include "ev-page-action.h"
#include "ev-password-view.h"
#include "ev-properties-dialog.h"
#include "ev-sidebar-annotations.h"
#include "ev-sidebar-attachments.h"
#include "ev-sidebar-bookmarks.h"
#include "ev-sidebar.h"
#include "ev-sidebar-links.h"
#include "ev-sidebar-page.h"
#include "ev-sidebar-thumbnails.h"
#include "ev-sidebar-layers.h"
#include "ev-stock-icons.h"
#include "ev-utils.h"
#include "ev-keyring.h"
#include "ev-view.h"
#include "ev-web-view.h"
#include "ev-view-presentation.h"
#include "ev-view-type-builtins.h"
#include "ev-window.h"
#include "ev-window-title.h"
#include "ev-print-operation.h"
#include "ev-progress-message-area.h"
#include "ev-annotation-properties-dialog.h"
#include "ev-bookmarks.h"
#include "ev-bookmark-action.h"
Macros
#define EV_WINDOW_IS_PRESENTATION(w)
#define PAGE_SELECTOR_ACTION "PageSelector"
#define ZOOM_CONTROL_ACTION "ViewZoom"
#define NAVIGATION_ACTION "Navigation"
#define MATE_LOCKDOWN_SCHEMA "org.mate.lockdown"
#define MATE_LOCKDOWN_SAVE "disable-save-to-disk"
#define MATE_LOCKDOWN_PRINT "disable-printing"
#define MATE_LOCKDOWN_PRINT_SETUP "disable-print-setup"
#define MATE_INTERFACE_SCHEMA "org.mate.interface"
#define MATE_INTERFACE_TB_STYLE "toolbar-style"
#define GS_SCHEMA_NAME "org.mate.Atril"
#define GS_OVERRIDE_RESTRICTIONS "override-restrictions"
#define GS_PAGE_CACHE_SIZE "page-cache-size"
#define GS_AUTO_RELOAD "auto-reload"
#define GS_LAST_DOCUMENT_DIRECTORY "document-directory"
#define GS_LAST_PICTURES_DIRECTORY "pictures-directory"
#define SIDEBAR_DEFAULT_SIZE 132
#define LINKS_SIDEBAR_ID "links"
#define THUMBNAILS_SIDEBAR_ID "thumbnails"
#define ATTACHMENTS_SIDEBAR_ID "attachments"
#define LAYERS_SIDEBAR_ID "layers"
#define ANNOTS_SIDEBAR_ID "annotations"
#define BOOKMARKS_SIDEBAR_ID "bookmarks"
#define EV_PRINT_SETTINGS_FILE "print-settings"
#define EV_PRINT_SETTINGS_GROUP "Print Settings"
#define EV_PAGE_SETUP_GROUP "Page Setup"
#define MIN_SCALE 0.05409
#define MAX_RECENT_ITEM_LEN (40)
#define TOOLBAR_RESOURCE_PATH "/org/mate/atril/shell/ui/toolbar.xml"
#define g_file_info_get_modification_date_time _g_file_info_get_modification_date_time
#define EV_HELP "help:atril"
#define ABOUT_GROUP "About"
#define EMAILIFY(string)
Typedefs
typedef struct _PageTitleData PageTitleData
Enumerations
enum EvWindowPageMode { PAGE_MODE_DOCUMENT , PAGE_MODE_PASSWORD }
enum EvChrome {
EV_CHROME_MENUBAR = 1 << 0 , EV_CHROME_TOOLBAR = 1 << 1 , EV_CHROME_FINDBAR = 1 << 2 , EV_CHROME_RAISE_TOOLBAR = 1 << 3 ,
EV_CHROME_FULLSCREEN_TOOLBAR = 1 << 4 , EV_CHROME_SIDEBAR = 1 << 5 , EV_CHROME_NORMAL = EV_CHROME_MENUBAR | EV_CHROME_TOOLBAR | EV_CHROME_SIDEBAR
}
enum EvSaveType { EV_SAVE_DOCUMENT , EV_SAVE_ATTACHMENT , EV_SAVE_IMAGE }
Functions
gboolean ev_window_is_empty (const EvWindow *ev_window)
const char * ev_window_get_uri (EvWindow *ev_window)
void ev_window_open_uri (EvWindow *ev_window, const char *uri, EvLinkDest *dest, EvWindowRunMode mode, const gchar *search_string)
void ev_window_open_document (EvWindow *ev_window, EvDocument *document, EvLinkDest *dest, EvWindowRunMode mode, const gchar *search_string)
void ev_window_print_range (EvWindow *ev_window, gint first_page, gint last_page)
GtkWidget * ev_window_new (void)
const gchar * ev_window_get_dbus_object_path (EvWindow *ev_window)
Macro Definition Documentation
ABOUT_GROUP
#define ABOUT_GROUP "About"
Definition at line 5399 of file ev-window.c.
Referenced by _pluma_cmd_help_about(), and activate_action_about().
ANNOTS_SIDEBAR_ID
#define ANNOTS_SIDEBAR_ID "annotations"
Definition at line 274 of file ev-window.c.
ATTACHMENTS_SIDEBAR_ID
#define ATTACHMENTS_SIDEBAR_ID "attachments"
Definition at line 272 of file ev-window.c.
BOOKMARKS_SIDEBAR_ID
#define BOOKMARKS_SIDEBAR_ID "bookmarks"
Definition at line 275 of file ev-window.c.
EMAILIFY
#define EMAILIFY (string)
Value:
(g_strdelimit ((string), "%", '@'))
Definition at line 5400 of file ev-window.c.
Referenced by _pluma_cmd_help_about(), and activate_action_about().
EV_HELP
#define EV_HELP "help:atril"
Definition at line 5118 of file ev-window.c.
EV_PAGE_SETUP_GROUP
#define EV_PAGE_SETUP_GROUP "Page Setup"
Definition at line 279 of file ev-window.c.
EV_PRINT_SETTINGS_FILE
#define EV_PRINT_SETTINGS_FILE "print-settings"
Definition at line 277 of file ev-window.c.
EV_PRINT_SETTINGS_GROUP
#define EV_PRINT_SETTINGS_GROUP "Print Settings"
Definition at line 278 of file ev-window.c.
EV_WINDOW_IS_PRESENTATION
#define EV_WINDOW_IS_PRESENTATION (w)
Value:
(w->priv->presentation_view != NULL)
Definition at line 244 of file ev-window.c.
g_file_info_get_modification_date_time
#define g_file_info_get_modification_date_time _g_file_info_get_modification_date_time
Definition at line 2186 of file ev-window.c.
GS_AUTO_RELOAD
#define GS_AUTO_RELOAD "auto-reload"
Definition at line 265 of file ev-window.c.
GS_LAST_DOCUMENT_DIRECTORY
#define GS_LAST_DOCUMENT_DIRECTORY "document-directory"
Definition at line 266 of file ev-window.c.
GS_LAST_PICTURES_DIRECTORY
#define GS_LAST_PICTURES_DIRECTORY "pictures-directory"
Definition at line 267 of file ev-window.c.
GS_OVERRIDE_RESTRICTIONS
#define GS_OVERRIDE_RESTRICTIONS "override-restrictions"
Definition at line 263 of file ev-window.c.
GS_PAGE_CACHE_SIZE
#define GS_PAGE_CACHE_SIZE "page-cache-size"
Definition at line 264 of file ev-window.c.
GS_SCHEMA_NAME
#define GS_SCHEMA_NAME "org.mate.Atril"
Definition at line 262 of file ev-window.c.
LAYERS_SIDEBAR_ID
#define LAYERS_SIDEBAR_ID "layers"
Definition at line 273 of file ev-window.c.
LINKS_SIDEBAR_ID
#define LINKS_SIDEBAR_ID "links"
Definition at line 270 of file ev-window.c.
MATE_INTERFACE_SCHEMA
#define MATE_INTERFACE_SCHEMA "org.mate.interface"
Definition at line 255 of file ev-window.c.
MATE_INTERFACE_TB_STYLE
#define MATE_INTERFACE_TB_STYLE "toolbar-style"
Definition at line 256 of file ev-window.c.
MATE_LOCKDOWN_PRINT
#define MATE_LOCKDOWN_PRINT "disable-printing"
Definition at line 252 of file ev-window.c.
MATE_LOCKDOWN_PRINT_SETUP
#define MATE_LOCKDOWN_PRINT_SETUP "disable-print-setup"
Definition at line 253 of file ev-window.c.
Referenced by ev_window_print_range().
MATE_LOCKDOWN_SAVE
#define MATE_LOCKDOWN_SAVE "disable-save-to-disk"
Definition at line 251 of file ev-window.c.
MATE_LOCKDOWN_SCHEMA
#define MATE_LOCKDOWN_SCHEMA "org.mate.lockdown"
Definition at line 250 of file ev-window.c.
MAX_RECENT_ITEM_LEN
#define MAX_RECENT_ITEM_LEN (40)
Definition at line 283 of file ev-window.c.
MIN_SCALE
#define MIN_SCALE 0.05409
Definition at line 281 of file ev-window.c.
NAVIGATION_ACTION
#define NAVIGATION_ACTION "Navigation"
Definition at line 248 of file ev-window.c.
PAGE_SELECTOR_ACTION
#define PAGE_SELECTOR_ACTION "PageSelector"
Definition at line 246 of file ev-window.c.
SIDEBAR_DEFAULT_SIZE
#define SIDEBAR_DEFAULT_SIZE 132
Definition at line 269 of file ev-window.c.
THUMBNAILS_SIDEBAR_ID
#define THUMBNAILS_SIDEBAR_ID "thumbnails"
Definition at line 271 of file ev-window.c.
TOOLBAR_RESOURCE_PATH
#define TOOLBAR_RESOURCE_PATH "/org/mate/atril/shell/ui/toolbar.xml"
Definition at line 285 of file ev-window.c.
ZOOM_CONTROL_ACTION
#define ZOOM_CONTROL_ACTION "ViewZoom"
Definition at line 247 of file ev-window.c.
Typedef Documentation
PageTitleData
typedef struct _PageTitleData PageTitleData
Enumeration Type Documentation
EvChrome
enum EvChrome
Enumerator
EV_CHROME_MENUBAR
EV_CHROME_TOOLBAR
EV_CHROME_FINDBAR
EV_CHROME_RAISE_TOOLBAR
EV_CHROME_FULLSCREEN_TOOLBAR
EV_CHROME_SIDEBAR
EV_CHROME_NORMAL
Definition at line 112 of file ev-window.c.
EvSaveType
enum EvSaveType
Enumerator
EV_SAVE_DOCUMENT
EV_SAVE_ATTACHMENT
EV_SAVE_IMAGE
Definition at line 122 of file ev-window.c.
EvWindowPageMode
enum EvWindowPageMode
Enumerator
PAGE_MODE_DOCUMENT
PAGE_MODE_PASSWORD
Definition at line 107 of file ev-window.c.
Function Documentation
ev_window_get_dbus_object_path()
const gchar * ev_window_get_dbus_object_path (EvWindow * ev_window)
Definition at line 8301 of file ev-window.c.
References NULL, and _EvWindow::priv.
ev_window_get_uri()
const char * ev_window_get_uri (EvWindow * ev_window)
ev_window_get_uri: @ev_window: The instance of the EvWindow.
It returns the uri of the document showed in the EvWindow.
Returns: the uri of the document showed in the EvWindow.
Definition at line 2070 of file ev-window.c.
References _EvWindow::priv.
ev_window_is_empty()
gboolean ev_window_is_empty (const EvWindow * ev_window)
ev_window_is_empty: @ev_window: The instance of the EvWindow.
It does look if there is any document loaded or if there is any job to load a document.
Returns: TRUE if there isn't any document loaded or any any documente to be loaded, FALSE in other case.
Definition at line 784 of file ev-window.c.
References EV_IS_WINDOW, FALSE, NULL, and _EvWindow::priv.
ev_window_new()
GtkWidget * ev_window_new (void)
ev_window_new:
Creates a #GtkWidget that represents the window.
Returns: the #GtkWidget that represents the window.
Definition at line 8288 of file ev-window.c.
References EV_TYPE_WINDOW, and NULL.
Referenced by ev_application_open_window().
ev_window_open_document()
void ev_window_open_document (EvWindow * ev_window, EvDocument * document, EvLinkDest * dest, EvWindowRunMode mode, const gchar * search_string)
Definition at line 2456 of file ev-window.c.
References dest, EGG_FIND_BAR, egg_find_bar_set_search_string(), ev_document_get_uri(), ev_document_model_set_document(), ev_file_monitor_new(), EV_IS_DOCUMENT_FIND, ev_link_action_new_dest(), ev_link_new(), EV_VIEW, ev_view_handle_link(), EV_WINDOW_MODE_FULLSCREEN, EV_WINDOW_MODE_PRESENTATION, FALSE, _EvDocument::iswebdocument, NULL, and _EvWindow::priv.
ev_window_open_uri()
void ev_window_open_uri (EvWindow * ev_window, const char * uri, EvLinkDest * dest, EvWindowRunMode mode, const gchar * search_string)
Definition at line 2372 of file ev-window.c.
References dest, ev_bookmarks_new(), ev_is_metadata_supported_for_file(), ev_job_load_new(), EV_JOB_PRIORITY_NONE, ev_job_scheduler_push_job(), ev_metadata_new(), EV_SIDEBAR_BOOKMARKS, ev_sidebar_bookmarks_set_bookmarks(), FALSE, NULL, _EvWindow::priv, and source_file.
ev_window_print_range()
void ev_window_print_range (EvWindow * ev_window, gint first_page, gint last_page)
Definition at line 3755 of file ev-window.c.
References ev_document_get_n_pages(), ev_document_model_get_page(), EV_IS_WINDOW, ev_print_operation_new(), ev_print_operation_run(), ev_print_operation_set_current_page(), ev_print_operation_set_default_page_setup(), ev_print_operation_set_embed_page_setup(), ev_print_operation_set_job_name(), ev_print_operation_set_print_settings(), MATE_LOCKDOWN_PRINT_SETUP, NULL, op, _EvWindow::priv, and TRUE.