MATE Desktop Environment: files.c File Reference
files.c File Reference
#include <config.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>
#include "common.h"
Functions
char * dgets (Dstring *dstr, FILE *in)
const char * file_basename (const char *filename)
const char * file_extension (const char *filename)
int file_readable (const char *filename)
int file_exists (const char *filename)
Function Documentation
dgets()
char * dgets (Dstring * dstr, FILE * in)
Definition at line 26 of file files.c.
References Dstring::data, dstring_append(), Dstring::length, and NULL.
Referenced by __PROTO(), mdvi_load_fontmap(), and mdvi_ps_read_fontmap().
file_basename()
const char * file_basename (const char * filename)
Definition at line 49 of file files.c.
References ptr, and strrchr.
Referenced by __PROTO(), and file_extension().
file_exists()
int file_exists (const char * filename)
Definition at line 72 of file files.c.
References DBG_FILES, and DEBUG.
Referenced by __PROTO(), and mdvi_ps_find_font().
file_extension()
const char * file_extension (const char * filename)
Definition at line 56 of file files.c.
References file_basename(), NULL, ptr, and strchr.
Referenced by __PROTO(), lookup_font_metrics(), mdvi_load_fontmap(), and mdvi_ps_read_fontmap().
file_readable()
int file_readable (const char * filename)
Definition at line 63 of file files.c.
References DBG_FILES, and DEBUG.
Referenced by __PROTO().