MATE Desktop Environment: file-data.c File Reference
file-data.c File Reference
#include <config.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include "glib-utils.h"
#include "file-utils.h"
#include "file-data.h"
Functions
FileData * file_data_new (void)
void file_data_free (FileData *fdata)
FileData * file_data_copy (FileData *src)
GType file_data_get_type (void)
void file_data_update_content_type (FileData *fdata)
gboolean file_data_is_dir (FileData *fdata)
void file_data_set_list_name (FileData *fdata, const char *value)
int file_data_compare_by_path (gconstpointer a, gconstpointer b)
int find_path_in_file_data_array (GPtrArray *array, const char *path)
Function Documentation
file_data_compare_by_path()
int file_data_compare_by_path (gconstpointer a, gconstpointer b)
Definition at line 133 of file file-data.c.
References b, and FileData::full_path.
file_data_copy()
FileData * file_data_copy (FileData * src)
Definition at line 60 of file file-data.c.
References FileData::content_type, FileData::dir, FileData::dir_size, FileData::encrypted, FileData::free_original_path, FileData::full_path, FileData::link, FileData::list_dir, FileData::list_name, FileData::modified, FileData::name, FileData::original_path, FileData::path, FileData::size, FileData::sort_key, and TRUE.
Referenced by file_data_get_type().
file_data_free()
void file_data_free (FileData * fdata)
Definition at line 44 of file file-data.c.
References FileData::free_original_path, FileData::full_path, FileData::link, FileData::list_name, FileData::name, NULL, FileData::original_path, FileData::path, and FileData::sort_key.
Referenced by file_data_get_type(), fr_command_list(), fr_window_current_folder_activated(), and fr_window_rename_selection().
file_data_get_type()
GType file_data_get_type (void)
Definition at line 88 of file file-data.c.
References file_data_copy(), and file_data_free().
file_data_is_dir()
gboolean file_data_is_dir (FileData * fdata)
Definition at line 113 of file file-data.c.
References FileData::dir, and FileData::list_dir.
Referenced by fr_window_current_folder_activated(), fr_window_get_file_list_from_path_list(), fr_window_get_file_list_selection(), and fr_window_rename_selection().
file_data_new()
FileData * file_data_new (void)
Definition at line 31 of file file-data.c.
References FileData::content_type, FileData::dir_size, FALSE, FileData::free_original_path, and NULL.
file_data_set_list_name()
void file_data_set_list_name (FileData * fdata, const char * value)
Definition at line 119 of file file-data.c.
References FileData::list_name, NULL, and FileData::sort_key.
file_data_update_content_type()
void file_data_update_content_type (FileData * fdata)
Definition at line 99 of file file-data.c.
References FileData::content_type, FileData::dir, FileData::full_path, get_static_string(), MIME_TYPE_DIRECTORY, and NULL.
Referenced by fr_command_add_file().
find_path_in_file_data_array()
int find_path_in_file_data_array (GPtrArray * array, const char * path)
Definition at line 143 of file file-data.c.
References NULL, and FileData::original_path.