MATE Desktop Environment: file-transfer-dialog.h File Reference
file-transfer-dialog.h File Reference
#include <glib.h>
#include <gtk/gtk.h>
Classes
struct _FileTransferDialog
struct _FileTransferDialogClass
Macros
#define FILE_TRANSFER_DIALOG(obj)
#define FILE_TRANSFER_DIALOG_CLASS(klass)
#define IS_FILE_TRANSFER_DIALOG(obj)
Typedefs
typedef struct _FileTransferDialog FileTransferDialog
typedef struct _FileTransferDialogClass FileTransferDialogClass
typedef struct _FileTransferDialogPrivate FileTransferDialogPrivate
Enumerations
enum FileTransferDialogOptions { FILE_TRANSFER_DIALOG_DEFAULT = 1 << 0 , FILE_TRANSFER_DIALOG_OVERWRITE = 1 << 1 }
Functions
GType file_transfer_dialog_get_type (void)
GtkWidget * file_transfer_dialog_new (void)
GtkWidget * file_transfer_dialog_new_with_parent (GtkWindow *parent)
void file_transfer_dialog_copy_async (FileTransferDialog *dlg, GList *source_files, GList *target_files, FileTransferDialogOptions options, int priority)
Macro Definition Documentation
FILE_TRANSFER_DIALOG
#define FILE_TRANSFER_DIALOG (obj)
Value:
G_TYPE_CHECK_INSTANCE_CAST (obj, file_transfer_dialog_get_type (), FileTransferDialog)
Definition at line 32 of file file-transfer-dialog.h.
Referenced by mate_theme_install().
FILE_TRANSFER_DIALOG_CLASS
#define FILE_TRANSFER_DIALOG_CLASS (klass)
Value:
G_TYPE_CHECK_CLASS_CAST (klass, file_transfer_dialog_get_type (), FileTransferDialogClass)
Definition at line 33 of file file-transfer-dialog.h.
IS_FILE_TRANSFER_DIALOG
#define IS_FILE_TRANSFER_DIALOG (obj)
Value:
G_TYPE_CHECK_INSTANCE_TYPE (obj, file_transfer_dialog_get_type ())
Definition at line 34 of file file-transfer-dialog.h.
Typedef Documentation
FileTransferDialog
typedef struct _FileTransferDialog FileTransferDialog
Definition at line 36 of file file-transfer-dialog.h.
FileTransferDialogClass
typedef struct _FileTransferDialogClass FileTransferDialogClass
Definition at line 37 of file file-transfer-dialog.h.
FileTransferDialogPrivate
typedef struct _FileTransferDialogPrivate FileTransferDialogPrivate
Definition at line 38 of file file-transfer-dialog.h.
Enumeration Type Documentation
FileTransferDialogOptions
enum FileTransferDialogOptions
Enumerator
FILE_TRANSFER_DIALOG_DEFAULT
FILE_TRANSFER_DIALOG_OVERWRITE
Definition at line 40 of file file-transfer-dialog.h.
Function Documentation
file_transfer_dialog_copy_async()
void file_transfer_dialog_copy_async (FileTransferDialog * dlg, GList * source_files, GList * target_files, FileTransferDialogOptions options, int priority)
Definition at line 559 of file file-transfer-dialog.c.
References NULL, and _FileTransferDialog::priv.
Referenced by mate_theme_install().
file_transfer_dialog_get_type()
GType file_transfer_dialog_get_type (void)
Referenced by file_transfer_dialog_new(), and file_transfer_dialog_new_with_parent().
file_transfer_dialog_new()
GtkWidget * file_transfer_dialog_new (void)
Definition at line 336 of file file-transfer-dialog.c.
References file_transfer_dialog_get_type(), and NULL.
file_transfer_dialog_new_with_parent()
GtkWidget * file_transfer_dialog_new_with_parent (GtkWindow * parent)
Definition at line 343 of file file-transfer-dialog.c.
References file_transfer_dialog_get_type(), and NULL.
Referenced by mate_theme_install().