MATE Desktop Environment: financial.h File Reference
financial.h File Reference
#include "mp.h"
#include "math-equation.h"
Enumerations
enum finc_dialogs {
FINC_CTRM_DIALOG , FINC_DDB_DIALOG , FINC_FV_DIALOG , FINC_GPM_DIALOG ,
FINC_PMT_DIALOG , FINC_PV_DIALOG , FINC_RATE_DIALOG , FINC_SLN_DIALOG ,
FINC_SYD_DIALOG , FINC_TERM_DIALOG
}
Functions
void do_finc_expression (MathEquation *equation, int function, MPNumber *arg1, MPNumber *arg2, MPNumber *arg3, MPNumber *arg4)
Enumeration Type Documentation
finc_dialogs
enum finc_dialogs
Enumerator
FINC_CTRM_DIALOG
FINC_DDB_DIALOG
FINC_FV_DIALOG
FINC_GPM_DIALOG
FINC_PMT_DIALOG
FINC_PV_DIALOG
FINC_RATE_DIALOG
FINC_SLN_DIALOG
FINC_SYD_DIALOG
FINC_TERM_DIALOG
Definition at line 20 of file financial.h.
Function Documentation
do_finc_expression()
void do_finc_expression (MathEquation * equation, int function, MPNumber * arg1, MPNumber * arg2, MPNumber * arg3, MPNumber * arg4)
Definition at line 306 of file financial.c.
References FINC_CTRM_DIALOG, FINC_DDB_DIALOG, FINC_FV_DIALOG, FINC_GPM_DIALOG, FINC_PMT_DIALOG, FINC_PV_DIALOG, FINC_RATE_DIALOG, FINC_SLN_DIALOG, FINC_SYD_DIALOG, FINC_TERM_DIALOG, math_equation_set_number(), mp_clear(), and mp_new().
Referenced by finc_response_cb().