MATE Desktop Environment: fm-directory-view.h File Reference
fm-directory-view.h File Reference
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <eel/eel-background.h>
#include <libcaja-private/caja-directory.h>
#include <libcaja-private/caja-file.h>
#include <libcaja-private/caja-icon-container.h>
#include <libcaja-private/caja-link.h>
#include <libcaja-private/caja-view.h>
#include <libcaja-private/caja-window-info.h>
#include <libcaja-private/caja-window-slot-info.h>
Classes
struct FMDirectoryView
struct FMDirectoryViewClass
Macros
#define FM_TYPE_DIRECTORY_VIEW fm_directory_view_get_type()
#define FM_DIRECTORY_VIEW(obj)
#define FM_DIRECTORY_VIEW_CLASS(klass)
#define FM_IS_DIRECTORY_VIEW(obj)
#define FM_IS_DIRECTORY_VIEW_CLASS(klass)
#define FM_DIRECTORY_VIEW_GET_CLASS(obj)
Typedefs
typedef struct FMDirectoryView FMDirectoryView
typedef struct FMDirectoryViewClass FMDirectoryViewClass
typedef struct FMDirectoryViewDetails FMDirectoryViewDetails
Functions
GType fm_directory_view_get_type (void)
CajaWindowInfo * fm_directory_view_get_caja_window (FMDirectoryView *view)
CajaWindowSlotInfo * fm_directory_view_get_caja_window_slot (FMDirectoryView *view)
char * fm_directory_view_get_uri (FMDirectoryView *view)
char * fm_directory_view_get_backing_uri (FMDirectoryView *view)
gboolean fm_directory_view_can_accept_item (CajaFile *target_item, const char *item_uri, FMDirectoryView *view)
void fm_directory_view_display_selection_info (FMDirectoryView *view)
GList * fm_directory_view_get_selection (FMDirectoryView *view)
GList * fm_directory_view_get_selection_for_file_transfer (FMDirectoryView *view)
void fm_directory_view_invert_selection (FMDirectoryView *view)
void fm_directory_view_stop (FMDirectoryView *view)
guint fm_directory_view_get_item_count (FMDirectoryView *view)
gboolean fm_directory_view_can_zoom_in (FMDirectoryView *view)
gboolean fm_directory_view_can_zoom_out (FMDirectoryView *view)
GtkWidget * fm_directory_view_get_background_widget (FMDirectoryView *view)
void fm_directory_view_bump_zoom_level (FMDirectoryView *view, int zoom_increment)
void fm_directory_view_zoom_to_level (FMDirectoryView *view, CajaZoomLevel zoom_level)
CajaZoomLevel fm_directory_view_get_zoom_level (FMDirectoryView *view)
void fm_directory_view_restore_default_zoom_level (FMDirectoryView *view)
void fm_directory_view_reset_to_defaults (FMDirectoryView *view)
void fm_directory_view_select_all (FMDirectoryView *view)
void fm_directory_view_set_selection (FMDirectoryView *view, GList *selection)
GArray * fm_directory_view_get_selected_icon_locations (FMDirectoryView *view)
void fm_directory_view_reveal_selection (FMDirectoryView *view)
gboolean fm_directory_view_is_empty (FMDirectoryView *view)
gboolean fm_directory_view_is_read_only (FMDirectoryView *view)
gboolean fm_directory_view_supports_creating_files (FMDirectoryView *view)
gboolean fm_directory_view_accepts_dragged_files (FMDirectoryView *view)
gboolean fm_directory_view_supports_properties (FMDirectoryView *view)
gboolean fm_directory_view_supports_zooming (FMDirectoryView *view)
gboolean fm_directory_view_using_manual_layout (FMDirectoryView *view)
void fm_directory_view_move_copy_items (const GList *item_uris, GArray *relative_item_points, const char *target_uri, int copy_action, int x, int y, FMDirectoryView *view)
GdkAtom fm_directory_view_get_copied_files_atom (FMDirectoryView *view)
gboolean fm_directory_view_get_active (FMDirectoryView *view)
void fm_directory_view_clear (FMDirectoryView *view)
void fm_directory_view_begin_loading (FMDirectoryView *view)
void fm_directory_view_end_loading (FMDirectoryView *view, gboolean all_files_seen)
gboolean fm_directory_view_get_loading (FMDirectoryView *view)
void fm_directory_view_activate_files (FMDirectoryView *view, GList *files, CajaWindowOpenMode mode, CajaWindowOpenFlags flags, gboolean confirm_multiple)
void fm_directory_view_activate_file (FMDirectoryView *view, CajaFile *file, CajaWindowOpenMode mode, CajaWindowOpenFlags flags)
void fm_directory_view_start_batching_selection_changes (FMDirectoryView *view)
void fm_directory_view_stop_batching_selection_changes (FMDirectoryView *view)
void fm_directory_view_queue_file_change (FMDirectoryView *view, CajaFile *file)
void fm_directory_view_notify_selection_changed (FMDirectoryView *view)
GtkUIManager * fm_directory_view_get_ui_manager (FMDirectoryView *view)
char ** fm_directory_view_get_emblem_names_to_exclude (FMDirectoryView *view)
CajaDirectory * fm_directory_view_get_model (FMDirectoryView *view)
GtkWindow * fm_directory_view_get_containing_window (FMDirectoryView *view)
CajaFile * fm_directory_view_get_directory_as_file (FMDirectoryView *view)
EelBackground * fm_directory_view_get_background (FMDirectoryView *view)
gboolean fm_directory_view_get_allow_moves (FMDirectoryView *view)
void fm_directory_view_pop_up_background_context_menu (FMDirectoryView *view, GdkEventButton *event)
void fm_directory_view_pop_up_selection_context_menu (FMDirectoryView *view, GdkEventButton *event)
void fm_directory_view_pop_up_location_context_menu (FMDirectoryView *view, GdkEventButton *event, const char *location)
void fm_directory_view_send_selection_change (FMDirectoryView *view)
gboolean fm_directory_view_should_show_file (FMDirectoryView *view, CajaFile *file)
gboolean fm_directory_view_should_sort_directories_first (FMDirectoryView *view)
void fm_directory_view_update_menus (FMDirectoryView *view)
void fm_directory_view_new_folder (FMDirectoryView *view)
void fm_directory_view_new_file (FMDirectoryView *view, const char *parent_uri, CajaFile *source)
void fm_directory_view_ignore_hidden_file_preferences (FMDirectoryView *view)
void fm_directory_view_set_show_foreign (FMDirectoryView *view, gboolean show_foreign)
void fm_directory_view_init_view_iface (CajaViewIface *iface)
gboolean fm_directory_view_handle_scroll_event (FMDirectoryView *view, GdkEventScroll *event)
void fm_directory_view_handle_netscape_url_drop (FMDirectoryView *view, const char *encoded_url, const char *target_uri, GdkDragAction action, int x, int y)
void fm_directory_view_handle_uri_list_drop (FMDirectoryView *view, const char *item_uris, const char *target_uri, GdkDragAction action, int x, int y)
void fm_directory_view_handle_text_drop (FMDirectoryView *view, const char *text, const char *target_uri, GdkDragAction action, int x, int y)
void fm_directory_view_handle_raw_drop (FMDirectoryView *view, const char *raw_data, int length, const char *target_uri, const char *direct_save_uri, GdkDragAction action, int x, int y)
void fm_directory_view_freeze_updates (FMDirectoryView *view)
void fm_directory_view_unfreeze_updates (FMDirectoryView *view)
void fm_directory_view_add_subdirectory (FMDirectoryView *view, CajaDirectory *directory)
void fm_directory_view_remove_subdirectory (FMDirectoryView *view, CajaDirectory *directory)
gboolean fm_directory_view_is_editable (FMDirectoryView *view)
void fm_directory_view_set_initiated_unmount (FMDirectoryView *view, gboolean inititated_unmount)
void fm_directory_view_move_copy_items_between_views (FMDirectoryView *source, FMDirectoryView *target, gboolean copy)
Macro Definition Documentation
FM_DIRECTORY_VIEW
#define FM_DIRECTORY_VIEW (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), FM_TYPE_DIRECTORY_VIEW, FMDirectoryView))
Definition at line 48 of file fm-directory-view.h.
FM_DIRECTORY_VIEW_CLASS
#define FM_DIRECTORY_VIEW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), FM_TYPE_DIRECTORY_VIEW, FMDirectoryViewClass))
Definition at line 50 of file fm-directory-view.h.
Referenced by fm_directory_view_accepts_dragged_files(), fm_directory_view_bump_zoom_level(), fm_directory_view_can_zoom_in(), fm_directory_view_can_zoom_out(), fm_directory_view_get_background_widget(), fm_directory_view_get_emblem_names_to_exclude(), fm_directory_view_get_item_count(), fm_directory_view_get_selected_icon_locations(), fm_directory_view_get_selection(), fm_directory_view_get_selection_for_file_transfer(), fm_directory_view_get_zoom_level(), fm_directory_view_invert_selection(), fm_directory_view_is_empty(), fm_directory_view_is_read_only(), fm_directory_view_reset_to_defaults(), fm_directory_view_restore_default_zoom_level(), fm_directory_view_reveal_selection(), fm_directory_view_select_all(), fm_directory_view_set_selection(), fm_directory_view_supports_creating_files(), fm_directory_view_supports_properties(), fm_directory_view_supports_zooming(), fm_directory_view_update_menus(), fm_directory_view_using_manual_layout(), and fm_directory_view_zoom_to_level().
FM_DIRECTORY_VIEW_GET_CLASS
#define FM_DIRECTORY_VIEW_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), FM_TYPE_DIRECTORY_VIEW, FMDirectoryViewClass))
Definition at line 56 of file fm-directory-view.h.
FM_IS_DIRECTORY_VIEW
#define FM_IS_DIRECTORY_VIEW (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), FM_TYPE_DIRECTORY_VIEW))
Definition at line 52 of file fm-directory-view.h.
Referenced by fm_directory_view_accepts_dragged_files(), fm_directory_view_begin_loading(), fm_directory_view_bump_zoom_level(), fm_directory_view_can_accept_item(), fm_directory_view_can_zoom_in(), fm_directory_view_can_zoom_out(), fm_directory_view_clear(), fm_directory_view_display_selection_info(), fm_directory_view_end_loading(), fm_directory_view_get_active(), fm_directory_view_get_background_widget(), fm_directory_view_get_backing_uri(), fm_directory_view_get_containing_window(), fm_directory_view_get_copied_files_atom(), fm_directory_view_get_directory_as_file(), fm_directory_view_get_emblem_names_to_exclude(), fm_directory_view_get_item_count(), fm_directory_view_get_loading(), fm_directory_view_get_model(), fm_directory_view_get_selected_icon_locations(), fm_directory_view_get_selection(), fm_directory_view_get_selection_for_file_transfer(), fm_directory_view_get_uri(), fm_directory_view_get_zoom_level(), fm_directory_view_invert_selection(), fm_directory_view_is_empty(), fm_directory_view_is_read_only(), fm_directory_view_notify_selection_changed(), fm_directory_view_pop_up_background_context_menu(), fm_directory_view_pop_up_location_context_menu(), fm_directory_view_pop_up_selection_context_menu(), fm_directory_view_reset_to_defaults(), fm_directory_view_restore_default_zoom_level(), fm_directory_view_reveal_selection(), fm_directory_view_select_all(), fm_directory_view_set_selection(), fm_directory_view_start_batching_selection_changes(), fm_directory_view_stop(), fm_directory_view_stop_batching_selection_changes(), fm_directory_view_supports_creating_files(), fm_directory_view_supports_properties(), fm_directory_view_supports_zooming(), fm_directory_view_update_menus(), fm_directory_view_using_manual_layout(), and fm_directory_view_zoom_to_level().
FM_IS_DIRECTORY_VIEW_CLASS
#define FM_IS_DIRECTORY_VIEW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), FM_TYPE_DIRECTORY_VIEW))
Definition at line 54 of file fm-directory-view.h.
FM_TYPE_DIRECTORY_VIEW
#define FM_TYPE_DIRECTORY_VIEW fm_directory_view_get_type()
Definition at line 47 of file fm-directory-view.h.
Referenced by G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), and G_DEFINE_TYPE_WITH_CODE().
Typedef Documentation
FMDirectoryView
typedef struct FMDirectoryView FMDirectoryView
Definition at line 44 of file fm-directory-view.h.
FMDirectoryViewClass
typedef struct FMDirectoryViewClass FMDirectoryViewClass
Definition at line 45 of file fm-directory-view.h.
FMDirectoryViewDetails
typedef struct FMDirectoryViewDetails FMDirectoryViewDetails
Definition at line 59 of file fm-directory-view.h.
Function Documentation
fm_directory_view_accepts_dragged_files()
gboolean fm_directory_view_accepts_dragged_files (FMDirectoryView * view)
Definition at line 10127 of file fm-directory-view.c.
References EEL_CALL_METHOD_WITH_RETURN_VALUE, FALSE, FM_DIRECTORY_VIEW_CLASS, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_activate_file()
void fm_directory_view_activate_file (FMDirectoryView * view, CajaFile * file, CajaWindowOpenMode mode, CajaWindowOpenFlags flags)
Definition at line 750 of file fm-directory-view.c.
References caja_mime_activate_file(), FMDirectoryView::details, and fm_directory_view_get_containing_window().
fm_directory_view_activate_files()
void fm_directory_view_activate_files (FMDirectoryView * view, GList * files, CajaWindowOpenMode mode, CajaWindowOpenFlags flags, gboolean confirm_multiple)
Definition at line 729 of file fm-directory-view.c.
References caja_mime_activate_files(), FMDirectoryView::details, and fm_directory_view_get_containing_window().
fm_directory_view_add_subdirectory()
void fm_directory_view_add_subdirectory (FMDirectoryView * view, CajaDirectory * directory)
Definition at line 3368 of file fm-directory-view.c.
References caja_directory_file_monitor_add(), caja_directory_ref(), CAJA_FILE_ATTRIBUTE_DIRECTORY_ITEM_COUNT, CAJA_FILE_ATTRIBUTE_EXTENSION_INFO, CAJA_FILE_ATTRIBUTE_INFO, CAJA_FILE_ATTRIBUTE_LINK_INFO, CAJA_FILE_ATTRIBUTE_MOUNT, CAJA_FILE_ATTRIBUTES_FOR_ICON, and FMDirectoryView::details.
fm_directory_view_begin_loading()
void fm_directory_view_begin_loading (FMDirectoryView * view)
fm_directory_view_begin_loading:
Emit the signal to prepare for loading the contents of a new location. Subclasses might want to override the signal handler for this signal. This is normally called only by FMDirectoryView. @view: FMDirectoryView that is switching to view a new location.
Definition at line 3450 of file fm-directory-view.c.
References BEGIN_LOADING, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_bump_zoom_level()
void fm_directory_view_bump_zoom_level (FMDirectoryView * view, int zoom_increment)
fm_directory_view_bump_zoom_level:
bump the current zoom level by invoking the relevant subclass through the slot
Definition at line 3497 of file fm-directory-view.c.
References EEL_CALL_METHOD, FM_DIRECTORY_VIEW_CLASS, fm_directory_view_supports_zooming(), and FM_IS_DIRECTORY_VIEW.
Referenced by fm_directory_view_handle_scroll_event(), and fm_directory_view_init_view_iface().
fm_directory_view_can_accept_item()
gboolean fm_directory_view_can_accept_item (CajaFile * target_item, const char * item_uri, FMDirectoryView * view)
Definition at line 10378 of file fm-directory-view.c.
References caja_drag_can_accept_item(), CAJA_IS_FILE, FALSE, FM_IS_DIRECTORY_VIEW, and NULL.
fm_directory_view_can_zoom_in()
gboolean fm_directory_view_can_zoom_in (FMDirectoryView * view)
fm_directory_view_can_zoom_in:
Determine whether the view can be zoomed any closer. @view: The zoomable FMDirectoryView.
Return value: TRUE if @view can be zoomed any closer, FALSE otherwise.
Definition at line 3575 of file fm-directory-view.c.
References EEL_CALL_METHOD_WITH_RETURN_VALUE, FALSE, FM_DIRECTORY_VIEW_CLASS, fm_directory_view_supports_zooming(), and FM_IS_DIRECTORY_VIEW.
Referenced by fm_directory_view_init_view_iface().
fm_directory_view_can_zoom_out()
gboolean fm_directory_view_can_zoom_out (FMDirectoryView * view)
fm_directory_view_can_zoom_out:
Determine whether the view can be zoomed any further away. @view: The zoomable FMDirectoryView.
Return value: TRUE if @view can be zoomed any further away, FALSE otherwise.
Definition at line 3615 of file fm-directory-view.c.
References EEL_CALL_METHOD_WITH_RETURN_VALUE, FALSE, FM_DIRECTORY_VIEW_CLASS, fm_directory_view_supports_zooming(), and FM_IS_DIRECTORY_VIEW.
Referenced by fm_directory_view_init_view_iface().
fm_directory_view_clear()
void fm_directory_view_clear (FMDirectoryView * view)
fm_directory_view_clear:
Emit the signal to clear the contents of the view. Subclasses must override the signal handler for this signal. This is normally called only by FMDirectoryView. @view: FMDirectoryView to empty.
Definition at line 3433 of file fm-directory-view.c.
References CLEAR, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_display_selection_info()
void fm_directory_view_display_selection_info (FMDirectoryView * view)
fm_directory_view_display_selection_info:
Display information about the current selection, and notify the view frame of the changed selection. @view: FMDirectoryView for which to display selection info.
Definition at line 2232 of file fm-directory-view.c.
References _, caja_file_can_get_size(), caja_file_get_directory_item_count(), caja_file_get_display_name(), caja_file_get_size(), caja_file_get_volume_free_space(), caja_file_is_directory(), caja_file_list_free(), caja_preferences, CAJA_PREFERENCES_USE_IEC_UNITS, caja_window_slot_info_set_status(), FMDirectoryView::details, FALSE, fm_directory_view_get_item_count(), fm_directory_view_get_selection(), FM_IS_DIRECTORY_VIEW, NULL, and TRUE.
fm_directory_view_end_loading()
void fm_directory_view_end_loading (FMDirectoryView * view, gboolean all_files_seen)
fm_directory_view_end_loading:
Emit the signal after loading the contents of a new location. Subclasses might want to override the signal handler for this signal. This is normally called only by FMDirectoryView. @view: FMDirectoryView that is switching to view a new location.
Definition at line 3467 of file fm-directory-view.c.
References END_LOADING, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_freeze_updates()
void fm_directory_view_freeze_updates (FMDirectoryView * view)
Definition at line 3000 of file fm-directory-view.c.
References FMDirectoryView::details, FALSE, and TRUE.
fm_directory_view_get_active()
gboolean fm_directory_view_get_active (FMDirectoryView * view)
Definition at line 10946 of file fm-directory-view.c.
References FMDirectoryView::details, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_get_allow_moves()
gboolean fm_directory_view_get_allow_moves (FMDirectoryView * view)
Definition at line 2477 of file fm-directory-view.c.
References FMDirectoryView::details.
fm_directory_view_get_background()
EelBackground * fm_directory_view_get_background (FMDirectoryView * view)
Definition at line 3639 of file fm-directory-view.c.
References eel_get_widget_background(), and fm_directory_view_get_background_widget().
fm_directory_view_get_background_widget()
GtkWidget * fm_directory_view_get_background_widget (FMDirectoryView * view)
Definition at line 3629 of file fm-directory-view.c.
References EEL_CALL_METHOD_WITH_RETURN_VALUE, FM_DIRECTORY_VIEW_CLASS, FM_IS_DIRECTORY_VIEW, and NULL.
Referenced by fm_directory_view_get_background().
fm_directory_view_get_backing_uri()
char * fm_directory_view_get_backing_uri (FMDirectoryView * view)
Definition at line 10281 of file fm-directory-view.c.
References CAJA_DESKTOP_DIRECTORY, caja_desktop_directory_get_real_directory(), caja_directory_get_uri(), caja_directory_ref(), caja_directory_unref(), CAJA_IS_DESKTOP_DIRECTORY, FMDirectoryView::details, FM_IS_DIRECTORY_VIEW, and NULL.
Referenced by fm_directory_view_handle_netscape_url_drop(), fm_directory_view_handle_raw_drop(), fm_directory_view_handle_text_drop(), fm_directory_view_handle_uri_list_drop(), fm_directory_view_new_file(), and fm_directory_view_new_folder().
fm_directory_view_get_caja_window()
CajaWindowInfo * fm_directory_view_get_caja_window (FMDirectoryView * view)
Definition at line 604 of file fm-directory-view.c.
References FMDirectoryView::details, and NULL.
fm_directory_view_get_caja_window_slot()
CajaWindowSlotInfo * fm_directory_view_get_caja_window_slot (FMDirectoryView * view)
Definition at line 612 of file fm-directory-view.c.
References FMDirectoryView::details, and NULL.
fm_directory_view_get_containing_window()
GtkWindow * fm_directory_view_get_containing_window (FMDirectoryView * view)
Definition at line 624 of file fm-directory-view.c.
References FM_IS_DIRECTORY_VIEW, and NULL.
Referenced by fm_directory_view_activate_file(), fm_directory_view_activate_files(), fm_directory_view_handle_netscape_url_drop(), fm_directory_view_handle_uri_list_drop(), fm_directory_view_move_copy_items(), and fm_directory_view_notify_selection_changed().
fm_directory_view_get_copied_files_atom()
GdkAtom fm_directory_view_get_copied_files_atom (FMDirectoryView * view)
Definition at line 3743 of file fm-directory-view.c.
References FM_IS_DIRECTORY_VIEW.
fm_directory_view_get_directory_as_file()
CajaFile * fm_directory_view_get_directory_as_file (FMDirectoryView * view)
Definition at line 4312 of file fm-directory-view.c.
References FMDirectoryView::details, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_get_emblem_names_to_exclude()
char ** fm_directory_view_get_emblem_names_to_exclude (FMDirectoryView * view)
Definition at line 9822 of file fm-directory-view.c.
References EEL_CALL_METHOD_WITH_RETURN_VALUE, FM_DIRECTORY_VIEW_CLASS, FM_IS_DIRECTORY_VIEW, and NULL.
fm_directory_view_get_item_count()
guint fm_directory_view_get_item_count (FMDirectoryView * view)
Definition at line 3707 of file fm-directory-view.c.
References EEL_CALL_METHOD_WITH_RETURN_VALUE, FM_DIRECTORY_VIEW_CLASS, and FM_IS_DIRECTORY_VIEW.
Referenced by fm_directory_view_display_selection_info().
fm_directory_view_get_loading()
gboolean fm_directory_view_get_loading (FMDirectoryView * view)
fm_directory_view_get_loading: @view: an FMDirectoryView.
Return value: #gboolean inicating whether @view is currently loaded.
Definition at line 3483 of file fm-directory-view.c.
References FMDirectoryView::details, FALSE, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_get_model()
CajaDirectory * fm_directory_view_get_model (FMDirectoryView * view)
fm_directory_view_get_model:
Get the model for this FMDirectoryView. @view: FMDirectoryView of interest.
Return value: CajaDirectory for this view.
Definition at line 3735 of file fm-directory-view.c.
References FMDirectoryView::details, FM_IS_DIRECTORY_VIEW, and NULL.
Referenced by fm_directory_view_is_editable().
fm_directory_view_get_selected_icon_locations()
GArray * fm_directory_view_get_selected_icon_locations (FMDirectoryView * view)
fm_directory_view_get_selected_icon_locations:
return an array of locations of selected icons if available Return value: GArray of GdkPoints
Definition at line 9998 of file fm-directory-view.c.
References EEL_CALL_METHOD_WITH_RETURN_VALUE, FM_DIRECTORY_VIEW_CLASS, FM_IS_DIRECTORY_VIEW, and NULL.
fm_directory_view_get_selection()
GList * fm_directory_view_get_selection (FMDirectoryView * view)
fm_directory_view_get_selection:
Get a list of CajaFile pointers that represents the currently-selected items in this view. Subclasses must override the signal handler for the 'get_selection' signal. Callers are responsible for g_free-ing the list (but not its data). @view: FMDirectoryView whose selected items are of interest.
Return value: GList of CajaFile pointers representing the selection.
Definition at line 3677 of file fm-directory-view.c.
References EEL_CALL_METHOD_WITH_RETURN_VALUE, FM_DIRECTORY_VIEW_CLASS, FM_IS_DIRECTORY_VIEW, and NULL.
Referenced by fm_directory_view_display_selection_info(), and fm_directory_view_notify_selection_changed().
fm_directory_view_get_selection_for_file_transfer()
GList * fm_directory_view_get_selection_for_file_transfer (FMDirectoryView * view)
Definition at line 3697 of file fm-directory-view.c.
References EEL_CALL_METHOD_WITH_RETURN_VALUE, FM_DIRECTORY_VIEW_CLASS, FM_IS_DIRECTORY_VIEW, and NULL.
fm_directory_view_get_type()
GType fm_directory_view_get_type (void)
fm_directory_view_get_ui_manager()
GtkUIManager * fm_directory_view_get_ui_manager (FMDirectoryView * view)
Definition at line 3717 of file fm-directory-view.c.
References caja_window_info_get_ui_manager(), FMDirectoryView::details, and NULL.
fm_directory_view_get_uri()
char * fm_directory_view_get_uri (FMDirectoryView * view)
Definition at line 10270 of file fm-directory-view.c.
References caja_directory_get_uri(), FMDirectoryView::details, FM_IS_DIRECTORY_VIEW, and NULL.
fm_directory_view_get_zoom_level()
CajaZoomLevel fm_directory_view_get_zoom_level (FMDirectoryView * view)
Definition at line 3532 of file fm-directory-view.c.
References CAJA_ZOOM_LEVEL_STANDARD, EEL_CALL_METHOD_WITH_RETURN_VALUE, FM_DIRECTORY_VIEW_CLASS, fm_directory_view_supports_zooming(), and FM_IS_DIRECTORY_VIEW.
Referenced by fm_directory_view_init_view_iface().
fm_directory_view_handle_netscape_url_drop()
void fm_directory_view_handle_netscape_url_drop (FMDirectoryView * view, const char * encoded_url, const char * target_uri, GdkDragAction action, int x, int y)
Definition at line 10598 of file fm-directory-view.c.
References _, action, caja_link_local_create(), data, eel_show_error_dialog(), eel_show_warning_dialog(), eel_str_is_empty(), error, FALSE, fm_directory_view_get_backing_uri(), fm_directory_view_get_containing_window(), fm_directory_view_move_copy_items(), NULL, and TRUE.
fm_directory_view_handle_raw_drop()
void fm_directory_view_handle_raw_drop (FMDirectoryView * view, const char * raw_data, int length, const char * target_uri, const char * direct_save_uri, GdkDragAction action, int x, int y)
Definition at line 10896 of file fm-directory-view.c.
References _, action, fm_directory_view_get_backing_uri(), and NULL.
fm_directory_view_handle_scroll_event()
gboolean fm_directory_view_handle_scroll_event (FMDirectoryView * view, GdkEventScroll * event)
Definition at line 11006 of file fm-directory-view.c.
References FALSE, fm_directory_view_bump_zoom_level(), and TRUE.
fm_directory_view_handle_text_drop()
void fm_directory_view_handle_text_drop (FMDirectoryView * view, const char * text, const char * target_uri, GdkDragAction action, int x, int y)
Definition at line 10857 of file fm-directory-view.c.
References _, action, fm_directory_view_get_backing_uri(), and NULL.
fm_directory_view_handle_uri_list_drop()
void fm_directory_view_handle_uri_list_drop (FMDirectoryView * view, const char * item_uris, const char * target_uri, GdkDragAction action, int x, int y)
Definition at line 10772 of file fm-directory-view.c.
References _, action, caja_drag_drop_action_ask(), eel_show_warning_dialog(), FALSE, fm_directory_view_get_backing_uri(), fm_directory_view_get_containing_window(), fm_directory_view_move_copy_items(), NULL, and TRUE.
fm_directory_view_ignore_hidden_file_preferences()
void fm_directory_view_ignore_hidden_file_preferences (FMDirectoryView * view)
Definition at line 10250 of file fm-directory-view.c.
References FMDirectoryView::details, FALSE, NULL, and TRUE.
fm_directory_view_init_view_iface()
void fm_directory_view_init_view_iface (CajaViewIface * iface)
Definition at line 1972 of file fm-directory-view.c.
References _CajaViewIface::bump_zoom_level, _CajaViewIface::can_zoom_in, _CajaViewIface::can_zoom_out, _CajaViewIface::drop_proxy_received_netscape_url, _CajaViewIface::drop_proxy_received_uris, fm_directory_view_bump_zoom_level(), fm_directory_view_can_zoom_in(), fm_directory_view_can_zoom_out(), fm_directory_view_get_zoom_level(), fm_directory_view_pop_up_location_context_menu(), fm_directory_view_restore_default_zoom_level(), fm_directory_view_supports_zooming(), fm_directory_view_zoom_to_level(), _CajaViewIface::get_selection, _CajaViewIface::get_selection_count, _CajaViewIface::get_widget, _CajaViewIface::get_zoom_level, _CajaViewIface::grab_focus, _CajaViewIface::load_location, _CajaViewIface::pop_up_location_context_menu, _CajaViewIface::restore_default_zoom_level, _CajaViewIface::set_is_active, _CajaViewIface::set_selection, _CajaViewIface::stop_loading, _CajaViewIface::supports_zooming, _CajaViewIface::update_menus, and _CajaViewIface::zoom_to_level.
fm_directory_view_invert_selection()
void fm_directory_view_invert_selection (FMDirectoryView * view)
Definition at line 3687 of file fm-directory-view.c.
References EEL_CALL_METHOD, FM_DIRECTORY_VIEW_CLASS, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_is_editable()
gboolean fm_directory_view_is_editable (FMDirectoryView * view)
Definition at line 10077 of file fm-directory-view.c.
References caja_directory_is_editable(), fm_directory_view_get_model(), NULL, and TRUE.
fm_directory_view_is_empty()
gboolean fm_directory_view_is_empty (FMDirectoryView * view)
Definition at line 10067 of file fm-directory-view.c.
References EEL_CALL_METHOD_WITH_RETURN_VALUE, FALSE, FM_DIRECTORY_VIEW_CLASS, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_is_read_only()
gboolean fm_directory_view_is_read_only (FMDirectoryView * view)
Definition at line 10057 of file fm-directory-view.c.
References EEL_CALL_METHOD_WITH_RETURN_VALUE, FALSE, FM_DIRECTORY_VIEW_CLASS, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_move_copy_items()
void fm_directory_view_move_copy_items (const GList * item_uris, GArray * relative_item_points, const char * target_uri, int copy_action, int x, int y, FMDirectoryView * view)
Definition at line 10308 of file fm-directory-view.c.
References caja_file_get_existing_by_uri(), caja_file_is_archive(), caja_file_is_launcher(), caja_file_operations_copy_move(), caja_file_unref(), caja_is_engrampa_installed(), caja_launch_desktop_file(), fm_directory_view_get_containing_window(), mate_gdk_spawn_command_line_on_screen(), NULL, and target_file.
Referenced by fm_directory_view_handle_netscape_url_drop(), and fm_directory_view_handle_uri_list_drop().
fm_directory_view_move_copy_items_between_views()
void fm_directory_view_move_copy_items_between_views (FMDirectoryView * source, FMDirectoryView * target, gboolean copy)
fm_directory_view_new_file()
void fm_directory_view_new_file (FMDirectoryView * view, const char * parent_uri, CajaFile * source)
Definition at line 4240 of file fm-directory-view.c.
References caja_file_get_uri(), caja_file_is_local(), caja_file_operations_new_file_from_template(), data, fm_directory_view_get_backing_uri(), and NULL.
fm_directory_view_new_folder()
void fm_directory_view_new_folder (FMDirectoryView * view)
Definition at line 4173 of file fm-directory-view.c.
References caja_file_operations_new_folder(), data, fm_directory_view_get_backing_uri(), and NULL.
fm_directory_view_notify_selection_changed()
void fm_directory_view_notify_selection_changed (FMDirectoryView * view)
fm_directory_view_notify_selection_changed:
Notify this view that the selection has changed. This is normally called only by subclasses. @view: FMDirectoryView whose selection has changed.
Definition at line 9560 of file fm-directory-view.c.
References CAJA_DEBUG_LOG_DOMAIN_USER, caja_debug_log_is_domain_enabled(), caja_debug_log_with_file_list(), caja_file_list_free(), FMDirectoryView::details, FALSE, fm_directory_view_get_containing_window(), fm_directory_view_get_selection(), FM_IS_DIRECTORY_VIEW, and TRUE.
Referenced by fm_directory_view_stop_batching_selection_changes().
fm_directory_view_pop_up_background_context_menu()
void fm_directory_view_pop_up_background_context_menu (FMDirectoryView * view, GdkEventButton * event)
fm_directory_view_pop_up_background_context_menu
Pop up a context menu appropriate to the view globally at the last right click location. @view: FMDirectoryView of interest.
Return value: CajaDirectory for this view.
Definition at line 9322 of file fm-directory-view.c.
References eel_pop_up_context_menu(), FM_DIRECTORY_VIEW_POPUP_PATH_BACKGROUND, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_pop_up_location_context_menu()
void fm_directory_view_pop_up_location_context_menu (FMDirectoryView * view, GdkEventButton * event, const char * location)
fm_directory_view_pop_up_location_context_menu
Pop up a context menu appropriate to the view globally. @view: FMDirectoryView of interest. @event: GdkEventButton triggering the popup. @location: The location the popup-menu should be created for, or NULL for the currently displayed location.
Definition at line 9421 of file fm-directory-view.c.
References caja_file_get_by_uri(), caja_file_ref(), caja_file_unref(), FMDirectoryView::details, FM_IS_DIRECTORY_VIEW, and NULL.
Referenced by fm_directory_view_init_view_iface().
fm_directory_view_pop_up_selection_context_menu()
void fm_directory_view_pop_up_selection_context_menu (FMDirectoryView * view, GdkEventButton * event)
fm_directory_view_pop_up_selection_context_menu
Pop up a context menu appropriate to the selected items. @view: FMDirectoryView of interest. @event: The event that triggered this context menu.
Return value: CajaDirectory for this view.
Definition at line 9291 of file fm-directory-view.c.
References eel_pop_up_context_menu(), FM_DIRECTORY_VIEW_POPUP_PATH_SELECTION, FM_IS_DIRECTORY_VIEW, and NULL.
fm_directory_view_queue_file_change()
void fm_directory_view_queue_file_change (FMDirectoryView * view, CajaFile * file)
References action.
fm_directory_view_remove_subdirectory()
void fm_directory_view_remove_subdirectory (FMDirectoryView * view, CajaDirectory * directory)
Definition at line 3403 of file fm-directory-view.c.
References caja_directory_file_monitor_remove(), caja_directory_unref(), and FMDirectoryView::details.
fm_directory_view_reset_to_defaults()
void fm_directory_view_reset_to_defaults (FMDirectoryView * view)
fm_directory_view_reset_to_defaults:
set sorting order, zoom level, etc. to match defaults
Definition at line 9930 of file fm-directory-view.c.
References caja_window_info_get_hidden_files_mode(), caja_window_info_set_hidden_files_mode(), CAJA_WINDOW_SHOW_HIDDEN_FILES_DEFAULT, FMDirectoryView::details, EEL_CALL_METHOD, FM_DIRECTORY_VIEW_CLASS, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_restore_default_zoom_level()
void fm_directory_view_restore_default_zoom_level (FMDirectoryView * view)
fm_directory_view_restore_default_zoom_level:
restore to the default zoom level by invoking the relevant subclass through the slot
Definition at line 3552 of file fm-directory-view.c.
References EEL_CALL_METHOD, FM_DIRECTORY_VIEW_CLASS, fm_directory_view_supports_zooming(), and FM_IS_DIRECTORY_VIEW.
Referenced by fm_directory_view_init_view_iface().
fm_directory_view_reveal_selection()
void fm_directory_view_reveal_selection (FMDirectoryView * view)
fm_directory_view_reveal_selection:
Scroll as necessary to reveal the selected items.
Definition at line 10013 of file fm-directory-view.c.
References EEL_CALL_METHOD, FM_DIRECTORY_VIEW_CLASS, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_select_all()
void fm_directory_view_select_all (FMDirectoryView * view)
fm_directory_view_select_all:
select all the items in the view
Definition at line 9953 of file fm-directory-view.c.
References EEL_CALL_METHOD, FM_DIRECTORY_VIEW_CLASS, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_send_selection_change()
void fm_directory_view_send_selection_change (FMDirectoryView * view)
Definition at line 2469 of file fm-directory-view.c.
References caja_window_info_report_selection_changed(), FMDirectoryView::details, and FALSE.
fm_directory_view_set_initiated_unmount()
void fm_directory_view_set_initiated_unmount (FMDirectoryView * view, gboolean inititated_unmount)
Definition at line 10091 of file fm-directory-view.c.
References caja_window_info_set_initiated_unmount(), FMDirectoryView::details, and NULL.
fm_directory_view_set_selection()
void fm_directory_view_set_selection (FMDirectoryView * view, GList * selection)
fm_directory_view_set_selection:
set the selection to the items identified in @selection. @selection should be a list of CajaFiles
Definition at line 9970 of file fm-directory-view.c.
References EEL_CALL_METHOD, FM_DIRECTORY_VIEW_CLASS, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_set_show_foreign()
void fm_directory_view_set_show_foreign (FMDirectoryView * view, gboolean show_foreign)
Definition at line 10263 of file fm-directory-view.c.
References FMDirectoryView::details.
fm_directory_view_should_show_file()
gboolean fm_directory_view_should_show_file (FMDirectoryView * view, CajaFile * file)
fm_directory_view_should_show_file
Returns whether or not this file should be displayed based on current filtering options.
Definition at line 10143 of file fm-directory-view.c.
References caja_file_should_show(), and FMDirectoryView::details.
fm_directory_view_should_sort_directories_first()
gboolean fm_directory_view_should_sort_directories_first (FMDirectoryView * view)
Definition at line 1650 of file fm-directory-view.c.
References FMDirectoryView::details.
Referenced by fm_icon_view_compare_files().
fm_directory_view_start_batching_selection_changes()
void fm_directory_view_start_batching_selection_changes (FMDirectoryView * view)
Definition at line 10402 of file fm-directory-view.c.
References FMDirectoryView::details, FALSE, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_stop()
void fm_directory_view_stop (FMDirectoryView * view)
fm_directory_view_stop:
Stop the current ongoing process, such as switching to a new uri. @view: FMDirectoryView in question.
Definition at line 10030 of file fm-directory-view.c.
References caja_directory_file_monitor_remove(), FMDirectoryView::details, FALSE, FM_IS_DIRECTORY_VIEW, and NULL.
fm_directory_view_stop_batching_selection_changes()
void fm_directory_view_stop_batching_selection_changes (FMDirectoryView * view)
Definition at line 10411 of file fm-directory-view.c.
References FMDirectoryView::details, fm_directory_view_notify_selection_changed(), and FM_IS_DIRECTORY_VIEW.
fm_directory_view_supports_creating_files()
gboolean fm_directory_view_supports_creating_files (FMDirectoryView * view)
Definition at line 10117 of file fm-directory-view.c.
References EEL_CALL_METHOD_WITH_RETURN_VALUE, FALSE, FM_DIRECTORY_VIEW_CLASS, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_supports_properties()
gboolean fm_directory_view_supports_properties (FMDirectoryView * view)
Definition at line 10168 of file fm-directory-view.c.
References EEL_CALL_METHOD_WITH_RETURN_VALUE, FALSE, FM_DIRECTORY_VIEW_CLASS, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_supports_zooming()
gboolean fm_directory_view_supports_zooming (FMDirectoryView * view)
Definition at line 10186 of file fm-directory-view.c.
References EEL_CALL_METHOD_WITH_RETURN_VALUE, FALSE, FM_DIRECTORY_VIEW_CLASS, and FM_IS_DIRECTORY_VIEW.
Referenced by fm_directory_view_bump_zoom_level(), fm_directory_view_can_zoom_in(), fm_directory_view_can_zoom_out(), fm_directory_view_get_zoom_level(), fm_directory_view_init_view_iface(), fm_directory_view_restore_default_zoom_level(), and fm_directory_view_zoom_to_level().
fm_directory_view_unfreeze_updates()
void fm_directory_view_unfreeze_updates (FMDirectoryView * view)
Definition at line 3008 of file fm-directory-view.c.
References FMDirectoryView::details, FALSE, and NULL.
fm_directory_view_update_menus()
void fm_directory_view_update_menus (FMDirectoryView * view)
fm_directory_view_update_menus:
Update the sensitivity and wording of dynamic menu items. @view: FMDirectoryView in question.
Definition at line 10228 of file fm-directory-view.c.
References FMDirectoryView::details, EEL_CALL_METHOD, FALSE, FM_DIRECTORY_VIEW_CLASS, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_using_manual_layout()
gboolean fm_directory_view_using_manual_layout (FMDirectoryView * view)
Definition at line 10204 of file fm-directory-view.c.
References EEL_CALL_METHOD_WITH_RETURN_VALUE, FALSE, FM_DIRECTORY_VIEW_CLASS, and FM_IS_DIRECTORY_VIEW.
fm_directory_view_zoom_to_level()
void fm_directory_view_zoom_to_level (FMDirectoryView * view, CajaZoomLevel zoom_level)
fm_directory_view_zoom_to_level:
Set the current zoom level by invoking the relevant subclass through the slot
Definition at line 3517 of file fm-directory-view.c.
References EEL_CALL_METHOD, FM_DIRECTORY_VIEW_CLASS, fm_directory_view_supports_zooming(), and FM_IS_DIRECTORY_VIEW.
Referenced by fm_directory_view_init_view_iface().