MATE Desktop Environment: fm-ditem-page.h File Reference
fm-ditem-page.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
Functions
GtkWidget * fm_ditem_page_make_box (GtkSizeGroup *label_size_group, GList *files)
gboolean fm_ditem_page_should_show (GList *files)
Function Documentation
fm_ditem_page_make_box()
GtkWidget * fm_ditem_page_make_box (GtkSizeGroup * label_size_group, GList * files)
Definition at line 522 of file fm-ditem-page.c.
References CAJA_FILE_INFO, caja_file_info_get_uri(), and fm_ditem_page_should_show().
fm_ditem_page_should_show()
gboolean fm_ditem_page_should_show (GList * files)
Definition at line 545 of file fm-ditem-page.c.
References CAJA_FILE_INFO, caja_file_info_is_mime_type(), FALSE, and TRUE.
Referenced by fm_ditem_page_make_box().