MATE Desktop Environment: fm-error-reporting.c File Reference
fm-error-reporting.c File Reference
#include <config.h>
#include <string.h>
#include <glib/gi18n.h>
#include <eel/eel-string.h>
#include <eel/eel-stock-dialogs.h>
#include <libcaja-private/caja-debug-log.h>
#include <libcaja-private/caja-file.h>
#include "fm-error-reporting.h"
Macros
#define NEW_NAME_TAG "Caja: new name"
#define MAXIMUM_DISPLAYED_FILE_NAME_LENGTH 50
Typedefs
typedef struct _FMRenameData FMRenameData
Functions
void fm_report_error_loading_directory (CajaFile *file, GError *error, GtkWindow *parent_window)
void fm_report_error_renaming_file (CajaFile *file, const char *new_name, GError *error, GtkWindow *parent_window)
void fm_report_error_setting_group (CajaFile *file, GError *error, GtkWindow *parent_window)
void fm_report_error_setting_owner (CajaFile *file, GError *error, GtkWindow *parent_window)
void fm_report_error_setting_permissions (CajaFile *file, GError *error, GtkWindow *parent_window)
void fm_rename_file (CajaFile *file, const char *new_name, CajaFileOperationCallback callback, gpointer callback_data)
Macro Definition Documentation
MAXIMUM_DISPLAYED_FILE_NAME_LENGTH
#define MAXIMUM_DISPLAYED_FILE_NAME_LENGTH 50
Definition at line 40 of file fm-error-reporting.c.
NEW_NAME_TAG
#define NEW_NAME_TAG "Caja: new name"
Definition at line 39 of file fm-error-reporting.c.
Referenced by fm_rename_file().
Typedef Documentation
FMRenameData
typedef struct _FMRenameData FMRenameData
Function Documentation
fm_rename_file()
void fm_rename_file (CajaFile * file, const char * new_name, CajaFileOperationCallback callback, gpointer callback_data)
Definition at line 335 of file fm-error-reporting.c.
References _, caja_debug_log(), CAJA_DEBUG_LOG_DOMAIN_USER, caja_file_get_display_name(), caja_file_get_uri(), caja_file_rename(), CAJA_IS_FILE, data, eel_timed_wait_start(), error, FALSE, NEW_NAME_TAG, NULL, and TRUE.
fm_report_error_loading_directory()
void fm_report_error_loading_directory (CajaFile * file, GError * error, GtkWindow * parent_window)
Definition at line 45 of file fm-error-reporting.c.
References _, caja_file_get_display_name(), eel_show_error_dialog(), error, message(), and NULL.
fm_report_error_renaming_file()
void fm_report_error_renaming_file (CajaFile * file, const char * new_name, GError * error, GtkWindow * parent_window)
Definition at line 96 of file fm-error-reporting.c.
References _, caja_file_get_display_name(), eel_show_error_dialog(), eel_str_middle_truncate(), error, MAXIMUM_DISPLAYED_FILE_NAME_LENGTH, message(), NULL, and strchr.
fm_report_error_setting_group()
void fm_report_error_setting_group (CajaFile * file, GError * error, GtkWindow * parent_window)
Definition at line 171 of file fm-error-reporting.c.
References _, caja_file_get_display_name(), eel_show_error_dialog(), error, message(), and NULL.
fm_report_error_setting_owner()
void fm_report_error_setting_owner (CajaFile * file, GError * error, GtkWindow * parent_window)
Definition at line 216 of file fm-error-reporting.c.
References _, caja_file_get_display_name(), eel_show_error_dialog(), error, message(), and NULL.
fm_report_error_setting_permissions()
void fm_report_error_setting_permissions (CajaFile * file, GError * error, GtkWindow * parent_window)
Definition at line 239 of file fm-error-reporting.c.
References _, caja_file_get_display_name(), eel_show_error_dialog(), error, message(), and NULL.