MATE Desktop Environment: fm-icon-view.c File Reference
fm-icon-view.c File Reference
#include <config.h>
#include <stdlib.h>
#include <errno.h>
#include <fcntl.h>
#include <locale.h>
#include <signal.h>
#include <stdio.h>
#include <unistd.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <eel/eel-background.h>
#include <eel/eel-canvas.h>
#include <eel/eel-glib-extensions.h>
#include <eel/eel-gtk-extensions.h>
#include <eel/eel-gtk-macros.h>
#include <eel/eel-stock-dialogs.h>
#include <eel/eel-string.h>
#include <eel/eel-vfs-extensions.h>
#include <libcaja-private/caja-clipboard-monitor.h>
#include <libcaja-private/caja-directory-background.h>
#include <libcaja-private/caja-directory.h>
#include <libcaja-private/caja-search-directory.h>
#include <libcaja-private/caja-dnd.h>
#include <libcaja-private/caja-file-utilities.h>
#include <libcaja-private/caja-ui-utilities.h>
#include <libcaja-private/caja-global-preferences.h>
#include <libcaja-private/caja-icon-canvas-item.h>
#include <libcaja-private/caja-icon-container.h>
#include <libcaja-private/caja-icon-private.h>
#include <libcaja-private/caja-icon-dnd.h>
#include <libcaja-private/caja-link.h>
#include <libcaja-private/caja-metadata.h>
#include <libcaja-private/caja-view-factory.h>
#include <libcaja-private/caja-clipboard.h>
#include <libcaja-private/caja-desktop-icon-file.h>
#include "fm-icon-view.h"
#include "fm-actions.h"
#include "fm-icon-container.h"
#include "fm-desktop-icon-view.h"
#include "fm-error-reporting.h"
#include "caja-audio-mime-types.h"
Macros
#define POPUP_PATH_ICON_APPEARANCE "/selection/Icon Appearance Items"
#define DEFAULT_ZOOM_LEVEL(icon_view)
#define TRANSLATE_VIEW_INFO(view_info)
Enumerations
enum { PROP_0 , PROP_COMPACT }
enum MenuItemType { MENU_ITEM_TYPE_STANDARD , MENU_ITEM_TYPE_CHECK , MENU_ITEM_TYPE_RADIO , MENU_ITEM_TYPE_TREE }
Functions
G_DEFINE_TYPE_WITH_CODE (FMIconView, fm_icon_view, FM_TYPE_DIRECTORY_VIEW, G_IMPLEMENT_INTERFACE(CAJA_TYPE_VIEW, fm_icon_view_iface_init))
int fm_icon_view_compare_files (FMIconView *icon_view, CajaFile *a, CajaFile *b)
void fm_icon_view_filter_by_screen (FMIconView *icon_view, gboolean filter)
gboolean fm_icon_view_is_compact (FMIconView *view)
void fm_icon_view_register (void)
void fm_compact_view_register (void)
Macro Definition Documentation
DEFAULT_ZOOM_LEVEL
#define DEFAULT_ZOOM_LEVEL (icon_view)
Value:
icon_view->details->compact ? default_compact_zoom_level : default_zoom_level
Definition at line 1265 of file fm-icon-view.c.
POPUP_PATH_ICON_APPEARANCE
#define POPUP_PATH_ICON_APPEARANCE "/selection/Icon Appearance Items"
Definition at line 74 of file fm-icon-view.c.
TRANSLATE_VIEW_INFO
#define TRANSLATE_VIEW_INFO (view_info)
Value:
view_info.view_combo_label = _(view_info.view_combo_label); \
view_info.view_menu_label_with_mnemonic = _(view_info.view_menu_label_with_mnemonic); \
view_info.error_label = _(view_info.error_label); \
view_info.startup_error_label = _(view_info.startup_error_label); \
view_info.display_location_label = _(view_info.display_location_label); \
Definition at line 3595 of file fm-icon-view.c.
Referenced by fm_compact_view_register(), and fm_icon_view_register().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_COMPACT
Definition at line 76 of file fm-icon-view.c.
MenuItemType
enum MenuItemType
Enumerator
MENU_ITEM_TYPE_STANDARD
MENU_ITEM_TYPE_CHECK
MENU_ITEM_TYPE_RADIO
MENU_ITEM_TYPE_TREE
Definition at line 89 of file fm-icon-view.c.
Function Documentation
fm_compact_view_register()
void fm_compact_view_register (void)
Definition at line 3646 of file fm-icon-view.c.
References caja_view_factory_register(), and TRANSLATE_VIEW_INFO.
fm_icon_view_compare_files()
int fm_icon_view_compare_files (FMIconView * icon_view, CajaFile * a, CajaFile * b)
Definition at line 2556 of file fm-icon-view.c.
References b, caja_file_compare_for_sort(), FMIconView::details, and fm_directory_view_should_sort_directories_first().
fm_icon_view_filter_by_screen()
void fm_icon_view_filter_by_screen (FMIconView * icon_view, gboolean filter)
Definition at line 2576 of file fm-icon-view.c.
References FMIconView::details.
fm_icon_view_is_compact()
gboolean fm_icon_view_is_compact (FMIconView * view)
Definition at line 3633 of file fm-icon-view.c.
References FMIconView::details.
fm_icon_view_register()
void fm_icon_view_register (void)
Definition at line 3639 of file fm-icon-view.c.
References caja_view_factory_register(), and TRANSLATE_VIEW_INFO.
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (FMIconView , fm_icon_view , FM_TYPE_DIRECTORY_VIEW , G_IMPLEMENT_INTERFACE(CAJA_TYPE_VIEW, fm_icon_view_iface_init))
References CAJA_TYPE_VIEW, and FM_TYPE_DIRECTORY_VIEW.