MATE Desktop Environment: fm-list-model.c File Reference
fm-list-model.c File Reference
#include <config.h>
#include <glib.h>
#include <string.h>
#include <cairo-gobject.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <libegg/eggtreemultidnd.h>
#include <eel/eel-graphic-effects.h>
#include <libcaja-private/caja-dnd.h>
#include <libcaja-private/caja-global-preferences.h>
#include "fm-list-model.h"
Typedefs
typedef struct FileEntry FileEntry
Enumerations
enum { SUBDIRECTORY_UNLOADED , GET_ICON_SCALE , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_CODE (FMListModel, fm_list_model, G_TYPE_OBJECT, G_IMPLEMENT_INTERFACE(GTK_TYPE_TREE_MODEL, fm_list_model_tree_model_init) G_IMPLEMENT_INTERFACE(GTK_TYPE_TREE_SORTABLE, fm_list_model_sortable_init) G_IMPLEMENT_INTERFACE(EGG_TYPE_TREE_MULTI_DRAG_SOURCE, fm_list_model_multi_drag_source_init))
GList * fm_list_model_get_all_iters_for_file (FMListModel *model, CajaFile *file)
gboolean fm_list_model_get_first_iter_for_file (FMListModel *model, CajaFile *file, GtkTreeIter *iter)
gboolean fm_list_model_get_tree_iter_from_file (FMListModel *model, CajaFile *file, CajaDirectory *directory, GtkTreeIter *iter)
int fm_list_model_compare_func (FMListModel *model, CajaFile *file1, CajaFile *file2)
gboolean fm_list_model_add_file (FMListModel *model, CajaFile *file, CajaDirectory *directory)
void fm_list_model_file_changed (FMListModel *model, CajaFile *file, CajaDirectory *directory)
gboolean fm_list_model_is_empty (FMListModel *model)
guint fm_list_model_get_length (FMListModel *model)
void fm_list_model_remove_file (FMListModel *model, CajaFile *file, CajaDirectory *directory)
void fm_list_model_clear (FMListModel *model)
CajaFile * fm_list_model_file_for_path (FMListModel *model, GtkTreePath *path)
gboolean fm_list_model_load_subdirectory (FMListModel *model, GtkTreePath *path, CajaDirectory **directory)
void fm_list_model_unload_subdirectory (FMListModel *model, GtkTreeIter *iter)
void fm_list_model_set_should_sort_directories_first (FMListModel *model, gboolean sort_directories_first)
int fm_list_model_get_sort_column_id_from_attribute (FMListModel *model, GQuark attribute)
GQuark fm_list_model_get_attribute_from_sort_column_id (FMListModel *model, int sort_column_id)
CajaZoomLevel fm_list_model_get_zoom_level_from_column_id (int column)
int fm_list_model_get_column_id_from_zoom_level (CajaZoomLevel zoom_level)
void fm_list_model_set_drag_view (FMListModel *model, GtkTreeView *view, int drag_begin_x, int drag_begin_y)
GtkTargetList * fm_list_model_get_drag_target_list ()
int fm_list_model_add_column (FMListModel *model, CajaColumn *column)
void fm_list_model_subdirectory_done_loading (FMListModel *model, CajaDirectory *directory)
void fm_list_model_set_highlight_for_files (FMListModel *model, GList *files)
Typedef Documentation
FileEntry
typedef struct FileEntry FileEntry
Definition at line 93 of file fm-list-model.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SUBDIRECTORY_UNLOADED
GET_ICON_SCALE
LAST_SIGNAL
Definition at line 44 of file fm-list-model.c.
Function Documentation
fm_list_model_add_column()
int fm_list_model_add_column (FMListModel * model, CajaColumn * column)
Definition at line 1638 of file fm-list-model.c.
References FM_LIST_MODEL_NUM_COLUMNS.
fm_list_model_add_file()
gboolean fm_list_model_add_file (FMListModel * model, CajaFile * file, CajaDirectory * directory)
Definition at line 1055 of file fm-list-model.c.
References caja_file_is_directory(), caja_file_ref(), FALSE, NULL, ptr, and TRUE.
fm_list_model_clear()
void fm_list_model_clear (FMListModel * model)
Definition at line 1372 of file fm-list-model.c.
References NULL.
fm_list_model_compare_func()
int fm_list_model_compare_func (FMListModel * model, CajaFile * file1, CajaFile * file2)
Definition at line 788 of file fm-list-model.c.
References caja_file_compare_for_sort_by_attribute_q(), and CajaFile::details.
fm_list_model_file_changed()
void fm_list_model_file_changed (FMListModel * model, CajaFile * file, CajaDirectory * directory)
Definition at line 1154 of file fm-list-model.c.
References FALSE, NULL, ptr, and TRUE.
fm_list_model_file_for_path()
CajaFile * fm_list_model_file_for_path (FMListModel * model, GtkTreePath * path)
Definition at line 1380 of file fm-list-model.c.
References FM_LIST_MODEL_FILE_COLUMN, and NULL.
fm_list_model_get_all_iters_for_file()
GList * fm_list_model_get_all_iters_for_file (FMListModel * model, CajaFile * file)
Definition at line 699 of file fm-list-model.c.
References data, and NULL.
Referenced by fm_list_model_get_first_iter_for_file().
fm_list_model_get_attribute_from_sort_column_id()
GQuark fm_list_model_get_attribute_from_sort_column_id (FMListModel * model, int sort_column_id)
Definition at line 1542 of file fm-list-model.c.
References CAJA_COLUMN, FM_LIST_MODEL_NUM_COLUMNS, and NULL.
fm_list_model_get_column_id_from_zoom_level()
int fm_list_model_get_column_id_from_zoom_level (CajaZoomLevel zoom_level)
Definition at line 1588 of file fm-list-model.c.
References CAJA_ZOOM_LEVEL_LARGE, CAJA_ZOOM_LEVEL_LARGER, CAJA_ZOOM_LEVEL_LARGEST, CAJA_ZOOM_LEVEL_SMALL, CAJA_ZOOM_LEVEL_SMALLER, CAJA_ZOOM_LEVEL_SMALLEST, CAJA_ZOOM_LEVEL_STANDARD, FM_LIST_MODEL_LARGE_ICON_COLUMN, FM_LIST_MODEL_LARGER_ICON_COLUMN, FM_LIST_MODEL_LARGEST_ICON_COLUMN, FM_LIST_MODEL_SMALL_ICON_COLUMN, FM_LIST_MODEL_SMALLER_ICON_COLUMN, FM_LIST_MODEL_SMALLEST_ICON_COLUMN, and FM_LIST_MODEL_STANDARD_ICON_COLUMN.
fm_list_model_get_drag_target_list()
GtkTargetList * fm_list_model_get_drag_target_list (void)
Definition at line 1627 of file fm-list-model.c.
References CAJA_ICON_DND_TEXT.
fm_list_model_get_first_iter_for_file()
gboolean fm_list_model_get_first_iter_for_file (FMListModel * model, CajaFile * file, GtkTreeIter * iter)
Definition at line 715 of file fm-list-model.c.
References FALSE, fm_list_model_get_all_iters_for_file(), NULL, and TRUE.
fm_list_model_get_length()
guint fm_list_model_get_length (FMListModel * model)
Definition at line 1238 of file fm-list-model.c.
fm_list_model_get_sort_column_id_from_attribute()
int fm_list_model_get_sort_column_id_from_attribute (FMListModel * model, GQuark attribute)
Definition at line 1504 of file fm-list-model.c.
References CAJA_COLUMN, FM_LIST_MODEL_NUM_COLUMNS, and NULL.
fm_list_model_get_tree_iter_from_file()
gboolean fm_list_model_get_tree_iter_from_file (FMListModel * model, CajaFile * file, CajaDirectory * directory, GtkTreeIter * iter)
Definition at line 736 of file fm-list-model.c.
References FALSE, ptr, and TRUE.
Referenced by fm_list_model_remove_file().
fm_list_model_get_zoom_level_from_column_id()
CajaZoomLevel fm_list_model_get_zoom_level_from_column_id (int column)
Definition at line 1564 of file fm-list-model.c.
References CAJA_ZOOM_LEVEL_LARGE, CAJA_ZOOM_LEVEL_LARGER, CAJA_ZOOM_LEVEL_LARGEST, CAJA_ZOOM_LEVEL_SMALL, CAJA_ZOOM_LEVEL_SMALLER, CAJA_ZOOM_LEVEL_SMALLEST, CAJA_ZOOM_LEVEL_STANDARD, FM_LIST_MODEL_LARGE_ICON_COLUMN, FM_LIST_MODEL_LARGER_ICON_COLUMN, FM_LIST_MODEL_LARGEST_ICON_COLUMN, FM_LIST_MODEL_SMALL_ICON_COLUMN, FM_LIST_MODEL_SMALLER_ICON_COLUMN, FM_LIST_MODEL_SMALLEST_ICON_COLUMN, and FM_LIST_MODEL_STANDARD_ICON_COLUMN.
fm_list_model_is_empty()
gboolean fm_list_model_is_empty (FMListModel * model)
Definition at line 1232 of file fm-list-model.c.
fm_list_model_load_subdirectory()
gboolean fm_list_model_load_subdirectory (FMListModel * model, GtkTreePath * path, CajaDirectory ** directory)
Definition at line 1398 of file fm-list-model.c.
References caja_directory_get_for_file(), caja_directory_ref(), caja_directory_unref(), FALSE, NULL, and TRUE.
fm_list_model_remove_file()
void fm_list_model_remove_file (FMListModel * model, CajaFile * file, CajaDirectory * directory)
Definition at line 1338 of file fm-list-model.c.
References fm_list_model_get_tree_iter_from_file().
fm_list_model_set_drag_view()
void fm_list_model_set_drag_view (FMListModel * model, GtkTreeView * view, int drag_begin_x, int drag_begin_y)
Definition at line 1612 of file fm-list-model.c.
References FM_IS_LIST_MODEL, and NULL.
fm_list_model_set_highlight_for_files()
void fm_list_model_set_highlight_for_files (FMListModel * model, GList * files)
Definition at line 1855 of file fm-list-model.c.
References caja_file_list_copy(), caja_file_list_free(), and NULL.
fm_list_model_set_should_sort_directories_first()
void fm_list_model_set_should_sort_directories_first (FMListModel * model, gboolean sort_directories_first)
Definition at line 1492 of file fm-list-model.c.
fm_list_model_subdirectory_done_loading()
void fm_list_model_subdirectory_done_loading (FMListModel * model, CajaDirectory * directory)
Definition at line 1782 of file fm-list-model.c.
References caja_directory_is_not_empty(), and NULL.
fm_list_model_unload_subdirectory()
void fm_list_model_unload_subdirectory (FMListModel * model, GtkTreeIter * iter)
Definition at line 1440 of file fm-list-model.c.
References caja_directory_unref(), NULL, and SUBDIRECTORY_UNLOADED.
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (FMListModel , fm_list_model , G_TYPE_OBJECT , G_IMPLEMENT_INTERFACE(GTK_TYPE_TREE_MODEL, fm_list_model_tree_model_init) G_IMPLEMENT_INTERFACE(GTK_TYPE_TREE_SORTABLE, fm_list_model_sortable_init) G_IMPLEMENT_INTERFACE(EGG_TYPE_TREE_MULTI_DRAG_SOURCE, fm_list_model_multi_drag_source_init))
References CAJA_ICON_DND_MATE_ICON_LIST, CAJA_ICON_DND_MATE_ICON_LIST_TYPE, and EGG_TYPE_TREE_MULTI_DRAG_SOURCE.