MATE Desktop Environment: fm-properties-window.c File Reference
fm-properties-window.c File Reference
#include <config.h>
#include <string.h>
#include <cairo.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <glib/gi18n.h>
#include <sys/stat.h>
#include <eel/eel-accessibility.h>
#include <eel/eel-gdk-pixbuf-extensions.h>
#include <eel/eel-glib-extensions.h>
#include <eel/eel-mate-extensions.h>
#include <eel/eel-gtk-extensions.h>
#include <eel/eel-labeled-image.h>
#include <eel/eel-stock-dialogs.h>
#include <eel/eel-vfs-extensions.h>
#include <eel/eel-wrap-table.h>
#include <libcaja-extension/caja-property-page-provider.h>
#include <libcaja-private/caja-mime-application-chooser.h>
#include <libcaja-private/caja-entry.h>
#include <libcaja-private/caja-extensions.h>
#include <libcaja-private/caja-file-attributes.h>
#include <libcaja-private/caja-file-operations.h>
#include <libcaja-private/caja-desktop-icon-file.h>
#include <libcaja-private/caja-global-preferences.h>
#include <libcaja-private/caja-emblem-utils.h>
#include <libcaja-private/caja-link.h>
#include <libcaja-private/caja-metadata.h>
#include <libcaja-private/caja-module.h>
#include <libcaja-private/caja-mime-actions.h>
#include "fm-properties-window.h"
#include "fm-ditem-page.h"
#include "fm-error-reporting.h"
Macros
#define USED_FILL_R 0.988235294
#define USED_FILL_G 0.91372549
#define USED_FILL_B 0.309803922
#define FREE_FILL_R 0.447058824
#define FREE_FILL_G 0.623529412
#define FREE_FILL_B 0.811764706
#define PREVIEW_IMAGE_WIDTH 96
#define ROW_PAD 6
#define DIRECTORY_CONTENTS_UPDATE_INTERVAL 200 /* milliseconds */
#define FILES_UPDATE_INTERVAL 200 /* milliseconds */
#define STANDARD_EMBLEM_HEIGHT 52
#define EMBLEM_LABEL_SPACING 2
#define CHOWN_CHGRP_TIMEOUT 300 /* milliseconds */
#define INCONSISTENT_STATE_STRING "\xE2\x80\x92"
Enumerations
enum CheckboxType { PERMISSIONS_CHECKBOXES_READ , PERMISSIONS_CHECKBOXES_WRITE , PERMISSIONS_CHECKBOXES_EXECUTE }
enum { TITLE_COLUMN , VALUE_COLUMN , COLUMN_COUNT }
enum { TARGET_URI_LIST , TARGET_MATE_URI_LIST , TARGET_RESET_BACKGROUND }
enum {
UNIX_PERM_SUID = S_ISUID , UNIX_PERM_SGID = S_ISGID , UNIX_PERM_STICKY = 01000 , UNIX_PERM_USER_READ = S_IRUSR ,
UNIX_PERM_USER_WRITE = S_IWUSR , UNIX_PERM_USER_EXEC = S_IXUSR , UNIX_PERM_USER_ALL = S_IRUSR | S_IWUSR | S_IXUSR , UNIX_PERM_GROUP_READ = S_IRGRP ,
UNIX_PERM_GROUP_WRITE = S_IWGRP , UNIX_PERM_GROUP_EXEC = S_IXGRP , UNIX_PERM_GROUP_ALL = S_IRGRP | S_IWGRP | S_IXGRP , UNIX_PERM_OTHER_READ = S_IROTH ,
UNIX_PERM_OTHER_WRITE = S_IWOTH , UNIX_PERM_OTHER_EXEC = S_IXOTH , UNIX_PERM_OTHER_ALL = S_IROTH | S_IWOTH | S_IXOTH
}
enum PermissionValue { PERMISSION_READ = (1<<0) , PERMISSION_WRITE = (1<<1) , PERMISSION_EXEC = (1<<2) }
enum PermissionType { PERMISSION_USER , PERMISSION_GROUP , PERMISSION_OTHER }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (FMPropertiesWindow, fm_properties_window, GTK_TYPE_DIALOG)
void fm_properties_window_present (GList *original_files, GtkWidget *parent_widget)
Macro Definition Documentation
CHOWN_CHGRP_TIMEOUT
#define CHOWN_CHGRP_TIMEOUT 300 /* milliseconds */
Definition at line 193 of file fm-properties-window.c.
DIRECTORY_CONTENTS_UPDATE_INTERVAL
#define DIRECTORY_CONTENTS_UPDATE_INTERVAL 200 /* milliseconds */
Definition at line 180 of file fm-properties-window.c.
EMBLEM_LABEL_SPACING
#define EMBLEM_LABEL_SPACING 2
Definition at line 183 of file fm-properties-window.c.
FILES_UPDATE_INTERVAL
#define FILES_UPDATE_INTERVAL 200 /* milliseconds */
Definition at line 181 of file fm-properties-window.c.
FREE_FILL_B
#define FREE_FILL_B 0.811764706
Definition at line 78 of file fm-properties-window.c.
FREE_FILL_G
#define FREE_FILL_G 0.623529412
Definition at line 77 of file fm-properties-window.c.
FREE_FILL_R
#define FREE_FILL_R 0.447058824
Definition at line 76 of file fm-properties-window.c.
INCONSISTENT_STATE_STRING
#define INCONSISTENT_STATE_STRING "\xE2\x80\x92"
Definition at line 2436 of file fm-properties-window.c.
PREVIEW_IMAGE_WIDTH
#define PREVIEW_IMAGE_WIDTH 96
Definition at line 80 of file fm-properties-window.c.
ROW_PAD
#define ROW_PAD 6
Definition at line 82 of file fm-properties-window.c.
STANDARD_EMBLEM_HEIGHT
#define STANDARD_EMBLEM_HEIGHT 52
Definition at line 182 of file fm-properties-window.c.
USED_FILL_B
#define USED_FILL_B 0.309803922
Definition at line 74 of file fm-properties-window.c.
USED_FILL_G
#define USED_FILL_G 0.91372549
Definition at line 73 of file fm-properties-window.c.
USED_FILL_R
#define USED_FILL_R 0.988235294
Definition at line 72 of file fm-properties-window.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TITLE_COLUMN
VALUE_COLUMN
COLUMN_COUNT
Definition at line 152 of file fm-properties-window.c.
anonymous enum
anonymous enum
Enumerator
TARGET_URI_LIST
TARGET_MATE_URI_LIST
TARGET_RESET_BACKGROUND
Definition at line 168 of file fm-properties-window.c.
anonymous enum
anonymous enum
Enumerator
UNIX_PERM_SUID
UNIX_PERM_SGID
UNIX_PERM_STICKY
UNIX_PERM_USER_READ
UNIX_PERM_USER_WRITE
UNIX_PERM_USER_EXEC
UNIX_PERM_USER_ALL
UNIX_PERM_GROUP_READ
UNIX_PERM_GROUP_WRITE
UNIX_PERM_GROUP_EXEC
UNIX_PERM_GROUP_ALL
UNIX_PERM_OTHER_READ
UNIX_PERM_OTHER_WRITE
UNIX_PERM_OTHER_EXEC
UNIX_PERM_OTHER_ALL
Definition at line 3921 of file fm-properties-window.c.
CheckboxType
enum CheckboxType
Enumerator
PERMISSIONS_CHECKBOXES_READ
PERMISSIONS_CHECKBOXES_WRITE
PERMISSIONS_CHECKBOXES_EXECUTE
Definition at line 146 of file fm-properties-window.c.
PermissionType
enum PermissionType
Enumerator
PERMISSION_USER
PERMISSION_GROUP
PERMISSION_OTHER
Definition at line 3945 of file fm-properties-window.c.
PermissionValue
enum PermissionValue
Enumerator
PERMISSION_READ
PERMISSION_WRITE
PERMISSION_EXEC
Definition at line 3939 of file fm-properties-window.c.
Function Documentation
fm_properties_window_present()
void fm_properties_window_present (GList * original_files, GtkWidget * parent_widget)
Definition at line 5419 of file fm-properties-window.c.
References _, CAJA_FILE, CAJA_FILE_ATTRIBUTE_INFO, caja_file_call_when_ready(), caja_file_list_free(), eel_g_hash_table_new_free_at_exit(), eel_timed_wait_start(), and NULL.
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (FMPropertiesWindow , fm_properties_window , GTK_TYPE_DIALOG)
References CAJA_FILE, caja_file_is_gone(), NULL, and TRUE.