MATE Desktop Environment: fm-properties-window.h File Reference
fm-properties-window.h File Reference
#include <gtk/gtk.h>
#include <libcaja-private/caja-file.h>
Classes
struct FMPropertiesWindow
struct FMPropertiesWindowClass
Macros
#define FM_TYPE_PROPERTIES_WINDOW fm_properties_window_get_type()
#define FM_PROPERTIES_WINDOW(obj)
#define FM_PROPERTIES_WINDOW_CLASS(klass)
#define FM_IS_PROPERTIES_WINDOW(obj)
#define FM_IS_PROPERTIES_WINDOW_CLASS(klass)
#define FM_PROPERTIES_WINDOW_GET_CLASS(obj)
Typedefs
typedef struct FMPropertiesWindow FMPropertiesWindow
typedef struct _FMPropertiesWindowPrivate FMPropertiesWindowPrivate
typedef struct FMPropertiesWindowClass FMPropertiesWindowClass
Functions
GType fm_properties_window_get_type (void)
void fm_properties_window_present (GList *files, GtkWidget *parent_widget)
Macro Definition Documentation
FM_IS_PROPERTIES_WINDOW
#define FM_IS_PROPERTIES_WINDOW (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), FM_TYPE_PROPERTIES_WINDOW))
Definition at line 40 of file fm-properties-window.h.
FM_IS_PROPERTIES_WINDOW_CLASS
#define FM_IS_PROPERTIES_WINDOW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), FM_TYPE_PROPERTIES_WINDOW))
Definition at line 42 of file fm-properties-window.h.
FM_PROPERTIES_WINDOW
#define FM_PROPERTIES_WINDOW (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), FM_TYPE_PROPERTIES_WINDOW, FMPropertiesWindow))
Definition at line 36 of file fm-properties-window.h.
FM_PROPERTIES_WINDOW_CLASS
#define FM_PROPERTIES_WINDOW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), FM_TYPE_PROPERTIES_WINDOW, FMPropertiesWindowClass))
Definition at line 38 of file fm-properties-window.h.
FM_PROPERTIES_WINDOW_GET_CLASS
#define FM_PROPERTIES_WINDOW_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), FM_TYPE_PROPERTIES_WINDOW, FMPropertiesWindowClass))
Definition at line 44 of file fm-properties-window.h.
FM_TYPE_PROPERTIES_WINDOW
#define FM_TYPE_PROPERTIES_WINDOW fm_properties_window_get_type()
Definition at line 35 of file fm-properties-window.h.
Typedef Documentation
FMPropertiesWindow
typedef struct FMPropertiesWindow FMPropertiesWindow
Definition at line 33 of file fm-properties-window.h.
FMPropertiesWindowClass
typedef struct FMPropertiesWindowClass FMPropertiesWindowClass
Definition at line 63 of file fm-properties-window.h.
FMPropertiesWindowPrivate
typedef struct _FMPropertiesWindowPrivate FMPropertiesWindowPrivate
Definition at line 47 of file fm-properties-window.h.
Function Documentation
fm_properties_window_get_type()
GType fm_properties_window_get_type (void)
fm_properties_window_present()
void fm_properties_window_present (GList * files, GtkWidget * parent_widget)
Definition at line 5419 of file fm-properties-window.c.
References _, CAJA_FILE, CAJA_FILE_ATTRIBUTE_INFO, caja_file_call_when_ready(), caja_file_list_free(), eel_g_hash_table_new_free_at_exit(), eel_timed_wait_start(), and NULL.