MATE Desktop Environment: fontsrch.c File Reference
fontsrch.c File Reference
#include <config.h>
#include "mdvi.h"
#include <kpathsea/tex-file.h>
#include <kpathsea/tex-glyph.h>
Macros
#define MAX_CLASS 3
Functions
int mdvi_get_font_classes (void)
char ** mdvi_list_font_class (int klass)
int mdvi_register_font_type (DviFontInfo *info, int klass)
int mdvi_unregister_font_type (const char *name, int klass)
char * mdvi_lookup_font (DviFontSearch *search)
DviFont * mdvi_add_font (const char *name, Int32 sum, int hdpi, int vdpi, Int32 scale)
int mdvi_font_retry (DviParams *params, DviFont *font)
Variables
char * _mdvi_fallback_font = MDVI_FALLBACK_FONT
Macro Definition Documentation
MAX_CLASS
#define MAX_CLASS 3
Definition at line 67 of file fontsrch.c.
Referenced by mdvi_get_font_classes(), mdvi_list_font_class(), mdvi_lookup_font(), mdvi_register_font_type(), and mdvi_unregister_font_type().
Function Documentation
mdvi_add_font()
DviFont * mdvi_add_font (const char * name, Int32 sum, int hdpi, int vdpi, Int32 scale)
Definition at line 320 of file fontsrch.c.
References _DviFontSearch::actual_hdpi, _DviFontSearch::actual_vdpi, _DviFont::chars, _DviFont::checksum, _DviFont::design, _DviFont::filename, _DviFont::fontname, _DviFont::hdpi, _DviFont::hic, _DviFont::in, _DviFont::links, _DviFont::loc, mdvi_free(), mdvi_lookup_font(), mdvi_strdup(), name, NULL, _DviFont::scale, _DviFont::search, SEARCH_INIT, _DviFont::subfonts, _DviFont::type, _DviFont::vdpi, and xalloc.
Referenced by __PROTO(), and font_reference().
mdvi_font_retry()
int mdvi_font_retry (DviParams * params, DviFont * font)
Definition at line 351 of file fontsrch.c.
References _DviFontSearch::actual_hdpi, _DviFontSearch::actual_vdpi, ASSERT, _DviFontSearch::curr, _DviFont::filename, _DviFont::hdpi, mdvi_free(), mdvi_lookup_font(), NULL, _DviFont::search, and _DviFont::vdpi.
Referenced by __PROTO().
mdvi_get_font_classes()
int mdvi_get_font_classes (void)
Definition at line 80 of file fontsrch.c.
References MAX_CLASS.
Referenced by __PROTO().
mdvi_list_font_class()
char ** mdvi_list_font_class (int klass)
Definition at line 85 of file fontsrch.c.
References MAX_CLASS, mdvi_strdup(), _DviFontInfo::name, NULL, and xnalloc.
Referenced by __PROTO().
mdvi_lookup_font()
char * mdvi_lookup_font (DviFontSearch * search)
Definition at line 198 of file fontsrch.c.
References _mdvi_fallback_font, _DviFontSearch::actual_hdpi, _DviFontSearch::actual_name, _DviFontSearch::actual_vdpi, _DviFontSearch::curr, DBG_FONTS, DEBUG, _DviFontSearch::hdpi, _DviFontSearch::id, _DviFontSearch::info, MAX_CLASS, mdvi_warning(), name, NULL, ptr, STREQ, _DviFontSearch::vdpi, and _DviFontSearch::wanted_name.
Referenced by __PROTO(), mdvi_add_font(), and mdvi_font_retry().
mdvi_register_font_type()
int mdvi_register_font_type (DviFontInfo * info, int klass)
Definition at line 105 of file fontsrch.c.
References _DviFontInfo::freedata, _DviFontInfo::getglyph, _DviFontInfo::kpse_type, LIST, listh_append(), _DviFontInfo::load, _DviFontInfo::lookup, MAX_CLASS, mdvi_strdup(), _DviFontInfo::name, _DviFontInfo::reset, _DviFontInfo::scalable, _DviFontInfo::shrink0, _DviFontInfo::shrink1, and xalloc.
Referenced by __PROTO(), and mdvi_register_fonts().
mdvi_unregister_font_type()
int mdvi_unregister_font_type (const char * name, int klass)
Definition at line 132 of file fontsrch.c.
References LIST, LIST_FOREACH, listh_remove(), MAX_CLASS, mdvi_free(), _DviFontInfo::name, name, NULL, and STREQ.
Referenced by __PROTO().
Variable Documentation
_mdvi_fallback_font
char* _mdvi_fallback_font = MDVI_FALLBACK_FONT
Definition at line 64 of file fontsrch.c.
Referenced by mdvi_lookup_font().