MATE Desktop Environment: font.c File Reference
font.c File Reference
#include <config.h>
#include <stdlib.h>
#include "mdvi.h"
#include "private.h"
Macros
#define finfo search.info
#define TYPENAME(font)
Functions
void vf_free_macros (DviFont *)
int font_reopen (DviFont *font)
void font_drop_one (DviFontRef *ref)
void font_drop_chain (DviFontRef *head)
int font_free_unused (DviDevice *dev)
DviFontRef * font_reference (DviParams *params, Int32 id, const char *name, Int32 sum, int hdpi, int vdpi, Int32 scale)
void font_transform_glyph (DviOrientation orient, DviGlyph *g)
DviFontChar * font_get_glyph (DviContext *dvi, DviFont *font, int code)
void font_reset_one_glyph (DviDevice *dev, DviFontChar *ch, int what)
void font_reset_font_glyphs (DviDevice *dev, DviFont *font, int what)
void font_reset_chain_glyphs (DviDevice *dev, DviFontRef *head, int what)
void font_finish_definitions (DviContext *dvi)
DviFontRef * font_find_flat (DviContext *dvi, Int32 id)
DviFontRef * font_find_mapped (DviContext *dvi, Int32 id)
Variables
char * _mdvi_fallback_font
Macro Definition Documentation
finfo
#define finfo search.info
Definition at line 31 of file font.c.
TYPENAME
#define TYPENAME (font)
Value:
((font)->finfo ? (font)->finfo->name : "none")
Definition at line 32 of file font.c.
Referenced by font_free_unused().
Function Documentation
font_drop_chain()
void font_drop_chain (DviFontRef * head)
Definition at line 104 of file font.c.
References font_drop_one(), and ptr.
Referenced by __PROTO(), mdvi_destroy_context(), and mdvi_reload().
font_drop_one()
void font_drop_one (DviFontRef * ref)
Definition at line 73 of file font.c.
References DBG_FONTS, DEBUG, _DviFont::fontname, _DviFont::in, _DviFont::links, LIST, listh_append(), listh_remove(), mdvi_free(), _DviFontRef::next, NULL, _DviFontRef::ref, and _DviFont::subfonts.
Referenced by __PROTO(), and font_drop_chain().
font_find_flat()
DviFontRef * font_find_flat (DviContext * dvi, Int32 id)
Definition at line 485 of file font.c.
References _DviFontRef::fontid, _DviContext::fonts, and _DviFontRef::next.
Referenced by __PROTO(), def_font(), sel_font(), and sel_fontn().
font_find_mapped()
DviFontRef * font_find_mapped (DviContext * dvi, Int32 id)
Definition at line 495 of file font.c.
References _DviContext::fontmap, _DviContext::nfonts, and NULL.
Referenced by __PROTO(), and mdvi_init_context().
font_finish_definitions()
void font_finish_definitions (DviContext * dvi)
Definition at line 465 of file font.c.
References _, _DviContext::device, _DviContext::filename, font_free_unused(), _DviContext::fontmap, _DviContext::fonts, mdvi_warning(), _DviFontRef::next, _DviContext::nfonts, NULL, and xnalloc.
Referenced by __PROTO(), and mdvi_init_context().
font_free_unused()
int font_free_unused (DviDevice * dev)
Definition at line 114 of file font.c.
References _DviFont::chars, DBG_FONTS, DEBUG, _DviFont::filename, font_reset_font_glyphs(), _DviFont::fontname, _DviFont::in, _DviFont::links, LIST, listh_remove(), MDVI_FONTSEL_GLYPH, mdvi_free(), _DviFont::next, _DviFontRef::next, _DviFont::subfonts, and TYPENAME.
Referenced by __PROTO(), font_finish_definitions(), mdvi_destroy_context(), and mdvi_reload().
font_get_glyph()
DviFontChar * font_get_glyph (DviContext * dvi, DviFont * font, int code)
Definition at line 346 of file font.c.
References _DviFontChar::bg, _DviFont::chars, _DviContext::curr_bg, _DviContext::curr_fg, _DviGlyph::data, _DviContext::device, _DviFontChar::fg, FONTCHAR, _DviDevice::free_image, _DviFontChar::glyph, glyph_present, _DviFontChar::grey, _DviFontChar::height, _DviParams::hshrink, _DviFontChar::loaded, MDVI_ENABLED, MDVI_GLYPH_ISEMPTY, MDVI_GLYPH_UNSET, MDVI_PARAM_ANTIALIASED, mdvi_shrink_box(), _DviFontChar::missing, NULL, _DviContext::params, _DviFontChar::shrunk, _DviParams::vshrink, and _DviFontChar::width.
Referenced by __PROTO(), and set_char().
font_reference()
DviFontRef * font_reference (DviParams * params, Int32 id, const char * name, Int32 sum, int hdpi, int vdpi, Int32 scale)
Definition at line 155 of file font.c.
References _DviFont::chars, _DviFont::checksum, DBG_FONTS, DEBUG, _DviFontRef::fontid, _DviFont::fontname, _DviFont::hdpi, _DviFont::links, LIST, listh_append(), listh_prepend(), listh_remove(), mdvi_add_font(), name, _DviFont::next, _DviFontRef::next, NULL, _DviFontRef::ref, _DviFont::scale, _DviFont::subfonts, _DviFont::vdpi, and xalloc.
Referenced by __PROTO().
font_reopen()
int font_reopen (DviFont * font)
Definition at line 35 of file font.c.
References DBG_FILES, DEBUG, _DviFont::filename, _DviFont::in, and NULL.
Referenced by __PROTO().
font_reset_chain_glyphs()
void font_reset_chain_glyphs (DviDevice * dev, DviFontRef * head, int what)
Definition at line 452 of file font.c.
References font_reset_font_glyphs(), _DviFontRef::next, and _DviFontRef::ref.
Referenced by __PROTO(), and mdvi_configure().
font_reset_font_glyphs()
void font_reset_font_glyphs (DviDevice * dev, DviFont * font, int what)
Definition at line 423 of file font.c.
References _DviFont::chars, DBG_FILES, DBG_FONTS, DEBUG, _DviFont::filename, font_reset_font_glyphs(), font_reset_one_glyph(), _DviFont::fontname, glyph_present, _DviFont::in, _DviFont::loc, MDVI_FONTSEL_BITMAP, MDVI_FONTSEL_GLYPH, MDVI_FONTSEL_GREY, _DviFontRef::next, NULL, _DviFontRef::ref, and _DviFont::subfonts.
Referenced by __PROTO(), font_free_unused(), font_reset_chain_glyphs(), and font_reset_font_glyphs().
font_reset_one_glyph()
void font_reset_one_glyph (DviDevice * dev, DviFontChar * ch, int what)
Definition at line 399 of file font.c.
References bitmap_destroy(), _DviGlyph::data, _DviDevice::free_image, _DviFontChar::glyph, glyph_present, _DviFontChar::grey, _DviFontChar::loaded, MDVI_FONTSEL_BITMAP, MDVI_FONTSEL_GLYPH, MDVI_FONTSEL_GREY, MDVI_GLYPH_NONEMPTY, NULL, and _DviFontChar::shrunk.
Referenced by __PROTO(), and font_reset_font_glyphs().
font_transform_glyph()
void font_transform_glyph (DviOrientation orient, DviGlyph * g)
Definition at line 209 of file font.c.
References bitmap_flip_diagonally(), bitmap_flip_horizontally(), bitmap_flip_rotate_clockwise(), bitmap_flip_rotate_counter_clockwise(), bitmap_flip_vertically(), bitmap_rotate_clockwise(), bitmap_rotate_counter_clockwise(), _DviGlyph::data, _DviGlyph::h, MDVI_GLYPH_ISEMPTY, MDVI_ORIENT_BTLR, MDVI_ORIENT_BTRL, MDVI_ORIENT_IRM90, MDVI_ORIENT_IRP90, MDVI_ORIENT_RM90, MDVI_ORIENT_RP90, MDVI_ORIENT_TBLR, MDVI_ORIENT_TBRL, NULL, SWAPINT, _DviGlyph::w, _DviGlyph::x, and _DviGlyph::y.
Referenced by __PROTO().
vf_free_macros()
void vf_free_macros (DviFont *) extern
Variable Documentation
_mdvi_fallback_font
char* _mdvi_fallback_font extern
Definition at line 64 of file fontsrch.c.
Referenced by mdvi_lookup_font().