MATE Desktop Environment: fontmap.h File Reference
fontmap.h File Reference
Classes
struct DviFontMapInfo
struct _DviEncoding
struct _DviFontMapEnt
Macros
#define MDVI_FMAP_SLANT(x)
#define MDVI_FMAP_EXTEND(x)
Typedefs
typedef struct _DviFontMapEnt DviFontMapEnt
typedef struct _DviEncoding DviEncoding
Functions
DviEncoding *mdvi_request_encoding __PROTO ((const char *))
void mdvi_release_encoding __PROTO ((DviEncoding *, int))
int mdvi_encode_glyph __PROTO ((DviEncoding *, const char *))
void mdvi_install_fontmap __PROTO ((DviFontMapEnt *))
int mdvi_load_fontmaps __PROTO ((void))
int mdvi_query_fontmap __PROTO ((DviFontMapInfo *, const char *))
int mdvi_add_fontmap_file __PROTO ((const char *, const char *))
Macro Definition Documentation
MDVI_FMAP_EXTEND
#define MDVI_FMAP_EXTEND (x)
Value:
((double)(x)->extend / 10000.0)
Definition at line 62 of file fontmap.h.
MDVI_FMAP_SLANT
#define MDVI_FMAP_SLANT (x)
Value:
((double)(x)->slant / 10000.0)
Definition at line 61 of file fontmap.h.
Typedef Documentation
DviEncoding
typedef struct _DviEncoding DviEncoding
Definition at line 22 of file fontmap.h.
DviFontMapEnt
typedef struct _DviFontMapEnt DviFontMapEnt
Definition at line 21 of file fontmap.h.
Function Documentation
__PROTO() [1/7]
DviEncoding *mdvi_request_encoding __PROTO ((const char *)) extern
References mdvi_request_encoding().
__PROTO() [2/7]
int mdvi_add_fontmap_file __PROTO ((const char *, const char *)) extern
References mdvi_add_fontmap_file(), mdvi_ps_find_font(), mdvi_ps_flush_fonts(), mdvi_ps_get_metrics(), and mdvi_ps_read_fontmap().
__PROTO() [3/7]
int mdvi_encode_glyph __PROTO ((DviEncoding *, const char *)) extern
References mdvi_encode_glyph(), and mdvi_load_fontmap().
__PROTO() [4/7]
void mdvi_release_encoding __PROTO ((DviEncoding *, int)) extern
References mdvi_release_encoding().
__PROTO() [5/7]
void mdvi_install_fontmap __PROTO ((DviFontMapEnt *)) extern
References mdvi_install_fontmap().
__PROTO() [6/7]
int mdvi_query_fontmap __PROTO ((DviFontMapInfo *, const char *)) extern
References mdvi_flush_encodings(), mdvi_flush_fontmaps(), and mdvi_query_fontmap().
__PROTO() [7/7]
int mdvi_load_fontmaps __PROTO ((void)) extern