MATE Desktop Environment: font-thumbnailer.c File Reference
font-thumbnailer.c File Reference
#include <stdio.h>
#include <ft2build.h>
#include <math.h>
#include <FT_FREETYPE_H>
#include <gdk/gdk.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gio/gio.h>
#include <glib/gi18n.h>
#include <cairo/cairo-ft.h>
#include "sushi-font-loader.h"
#include "totem-resources.h"
#include <FT_ERRORS_H>
Macros
#define FT_ERRORDEF(e, v, s)
#define FT_ERROR_START_LIST
#define FT_ERROR_END_LIST
#define THUMB_SIZE 128
#define PADDING_VERTICAL 2
#define PADDING_HORIZONTAL 4
Functions
int main (int argc, char **argv)
Macro Definition Documentation
FT_ERROR_END_LIST
#define FT_ERROR_END_LIST
FT_ERROR_START_LIST
#define FT_ERROR_START_LIST
FT_ERRORDEF
#define FT_ERRORDEF (e, v, s)
Value:
case e: return s;
PADDING_HORIZONTAL
#define PADDING_HORIZONTAL 4
Definition at line 62 of file font-thumbnailer.c.
Referenced by main().
PADDING_VERTICAL
#define PADDING_VERTICAL 2
Definition at line 61 of file font-thumbnailer.c.
Referenced by main().
THUMB_SIZE
#define THUMB_SIZE 128
Definition at line 60 of file font-thumbnailer.c.
Referenced by main().
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 167 of file font-thumbnailer.c.
References error, FALSE, GETTEXT_PACKAGE, MATELOCALEDIR, MIN, N_, NULL, PADDING_HORIZONTAL, PADDING_VERTICAL, strrchr, sushi_new_ft_face_from_uri(), THUMB_SIZE, totem_resources_monitor_start(), totem_resources_monitor_stop(), and TRUE.