MATE Desktop Environment: fr-archive.h File Reference
fr-archive.h File Reference
#include <glib.h>
#include "fr-process.h"
#include "fr-command.h"
Classes
struct _FrArchive
struct _FrArchiveClass
Macros
#define FR_TYPE_ARCHIVE (fr_archive_get_type ())
#define FR_ARCHIVE(obj)
#define FR_ARCHIVE_CLASS(klass)
#define FR_IS_ARCHIVE(obj)
#define FR_IS_ARCHIVE_CLASS(klass)
#define FR_ARCHIVE_GET_CLASS(obj)
Typedefs
typedef struct _FrArchive FrArchive
typedef struct _FrArchiveClass FrArchiveClass
typedef struct _FrArchivePrivData FrArchivePrivData
typedef gboolean(* FakeLoadFunc) (FrArchive *archive, gpointer data)
Functions
GType fr_archive_get_type (void)
FrArchive * fr_archive_new (void)
void fr_archive_set_fake_load_func (FrArchive *archive, FakeLoadFunc func, gpointer data)
gboolean fr_archive_fake_load (FrArchive *archive)
void fr_archive_stoppable (FrArchive *archive, gboolean stoppable)
void fr_archive_stop (FrArchive *archive)
void fr_archive_action_completed (FrArchive *archive, FrAction action, FrProcErrorType error_type, const char *error_details)
gboolean fr_archive_create (FrArchive *archive, const char *uri)
gboolean fr_archive_load (FrArchive *archive, const char *uri, const char *password)
gboolean fr_archive_load_local (FrArchive *archive, const char *uri, const char *password)
void fr_archive_reload (FrArchive *archive, const char *password)
void fr_archive_add (FrArchive *archive, GList *file_list, const char *base_dir, const char *dest_dir, gboolean update, gboolean recursive, const char *password, gboolean encrypt_header, FrCompression compression, guint volume_size)
void fr_archive_remove (FrArchive *archive, GList *file_list, FrCompression compression)
void fr_archive_extract (FrArchive *archive, GList *file_list, const char *dest_uri, const char *base_dir, gboolean skip_older, gboolean overwrite, gboolean junk_path, const char *password)
void fr_archive_extract_to_local (FrArchive *archive, GList *file_list, const char *dest_path, const char *base_dir, gboolean skip_older, gboolean overwrite, gboolean junk_path, const char *password)
gboolean fr_archive_extract_here (FrArchive *archive, gboolean skip_older, gboolean overwrite, gboolean junk_path, const char *password)
const char * fr_archive_get_last_extraction_destination (FrArchive *archive)
void fr_archive_add_files (FrArchive *archive, GList *file_list, const char *base_dir, const char *dest_dir, gboolean update, const char *password, gboolean encrypt_header, FrCompression compression, guint volume_size)
void fr_archive_add_with_wildcard (FrArchive *archive, const char *include_files, const char *exclude_files, const char *exclude_folders, const char *base_dir, const char *dest_dir, gboolean update, gboolean follow_links, const char *password, gboolean encrypt_header, FrCompression compression, guint volume_size)
void fr_archive_add_directory (FrArchive *archive, const char *directory, const char *base_dir, const char *dest_dir, gboolean update, const char *password, gboolean encrypt_header, FrCompression compression, guint volume_size)
void fr_archive_add_items (FrArchive *archive, GList *item_list, const char *base_dir, const char *dest_dir, gboolean update, const char *password, gboolean encrypt_header, FrCompression compression, guint volume_size)
void fr_archive_add_dropped_items (FrArchive *archive, GList *item_list, const char *base_dir, const char *dest_dir, gboolean update, const char *password, gboolean encrypt_header, FrCompression compression, guint volume_size)
void fr_archive_test (FrArchive *archive, const char *password)
gboolean uri_is_archive (const char *uri)
Macro Definition Documentation
FR_ARCHIVE
#define FR_ARCHIVE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), FR_TYPE_ARCHIVE, FrArchive))
Definition at line 31 of file fr-archive.h.
Referenced by fr_archive_new().
FR_ARCHIVE_CLASS
#define FR_ARCHIVE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), FR_TYPE_ARCHIVE, FrArchiveClass))
Definition at line 32 of file fr-archive.h.
FR_ARCHIVE_GET_CLASS
#define FR_ARCHIVE_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS((obj), FR_TYPE_ARCHIVE, FrArchiveClass))
Definition at line 35 of file fr-archive.h.
FR_IS_ARCHIVE
#define FR_IS_ARCHIVE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), FR_TYPE_ARCHIVE))
Definition at line 33 of file fr-archive.h.
FR_IS_ARCHIVE_CLASS
#define FR_IS_ARCHIVE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), FR_TYPE_ARCHIVE))
Definition at line 34 of file fr-archive.h.
FR_TYPE_ARCHIVE
#define FR_TYPE_ARCHIVE (fr_archive_get_type ())
Definition at line 30 of file fr-archive.h.
Referenced by fr_archive_new().
Typedef Documentation
FakeLoadFunc
typedef gboolean(* FakeLoadFunc) (FrArchive *archive, gpointer data)
Definition at line 41 of file fr-archive.h.
FrArchive
typedef struct _FrArchive FrArchive
Definition at line 37 of file fr-archive.h.
FrArchiveClass
typedef struct _FrArchiveClass FrArchiveClass
Definition at line 38 of file fr-archive.h.
FrArchivePrivData
typedef struct _FrArchivePrivData FrArchivePrivData
Definition at line 39 of file fr-archive.h.
Function Documentation
fr_archive_action_completed()
void fr_archive_action_completed (FrArchive * archive, FrAction action, FrProcErrorType error_type, const char * error_details)
Definition at line 304 of file fr-archive.c.
References action, DONE, _FrArchive::error, fr_error_quark(), FrProcError::gerror, NULL, FrProcError::status, and FrProcError::type.
Referenced by fr_archive_add_dropped_items(), fr_archive_extract_here(), and fr_window_archive_new().
fr_archive_add()
void fr_archive_add (FrArchive * archive, GList * file_list, const char * base_dir, const char * dest_dir, gboolean update, gboolean recursive, const char * password, gboolean encrypt_header, FrCompression compression, guint volume_size)
Definition at line 1472 of file fr-archive.c.
References _FrArchive::command, _FrCommand::creating_archive, debug, DEBUG_INFO, _FrProcess::error, error, FALSE, file_list, file_name_from_path(), fr_archive_stoppable(), fr_command_add(), fr_command_recompress(), fr_command_set_n_files(), fr_command_uncompress(), FR_PROC_ERROR_GENERIC, FR_PROC_ERROR_NONE, fr_process_add_arg(), fr_process_begin_command(), fr_process_end_command(), fr_process_set_ignore_error(), fr_process_set_sticky(), fr_process_set_working_dir(), FrProcError::gerror, get_temp_work_dir(), LIST_LENGTH_TO_USE_FILE, _FrArchive::local_copy, _FrCommand::n_files, NULL, path_list_dup(), _FrArchive::priv, _FrArchive::process, _FrCommand::propAddCanReplace, _FrCommand::propAddCanUpdate, _FrCommand::propListFromFile, _FrArchive::read_only, remove_local_directory(), FrProcError::status, TRUE, and FrProcError::type.
Referenced by fr_window_update_files().
fr_archive_add_directory()
void fr_archive_add_directory (FrArchive * archive, const char * directory, const char * base_dir, const char * dest_dir, gboolean update, const char * password, gboolean encrypt_header, FrCompression compression, guint volume_size)
Definition at line 2095 of file fr-archive.c.
References FR_ACTION_GETTING_FILE_LIST, g_directory_list_all_async, _FrArchive::priv, _FrArchive::read_only, START, and TRUE.
Referenced by fr_window_archive_add_directory().
fr_archive_add_dropped_items()
void fr_archive_add_dropped_items (FrArchive * archive, GList * item_list, const char * base_dir, const char * dest_dir, gboolean update, const char * password, gboolean encrypt_header, FrCompression compression, guint volume_size)
Definition at line 2348 of file fr-archive.c.
References _, _FrArchive::file, FR_ACTION_ADDING_FILES, fr_archive_action_completed(), FR_PROC_ERROR_GENERIC, _FrArchive::have_permissions, NULL, _FrArchive::priv, _FrArchive::read_only, and uricmp().
Referenced by fr_window_archive_add_dropped_items().
fr_archive_add_files()
void fr_archive_add_files (FrArchive * archive, GList * file_list, const char * base_dir, const char * dest_dir, gboolean update, const char * password, gboolean encrypt_header, FrCompression compression, guint volume_size)
Definition at line 1885 of file fr-archive.c.
References file_list, NULL, and uri_is_local().
Referenced by fr_window_archive_add_files().
fr_archive_add_items()
void fr_archive_add_items (FrArchive * archive, GList * item_list, const char * base_dir, const char * dest_dir, gboolean update, const char * password, gboolean encrypt_header, FrCompression compression, guint volume_size)
Definition at line 2134 of file fr-archive.c.
References FR_ACTION_GETTING_FILE_LIST, g_list_items_async(), _FrArchive::priv, _FrArchive::read_only, and START.
Referenced by fr_window_archive_add_items().
fr_archive_add_with_wildcard()
void fr_archive_add_with_wildcard (FrArchive * archive, const char * include_files, const char * exclude_files, const char * exclude_folders, const char * base_dir, const char * dest_dir, gboolean update, gboolean follow_links, const char * password, gboolean encrypt_header, FrCompression compression, guint volume_size)
Definition at line 1982 of file fr-archive.c.
References FR_ACTION_GETTING_FILE_LIST, g_directory_list_async(), IGNORE_CASE, NO_BACKUP_FILES, NO_DOT_FILES, _FrArchive::priv, _FrArchive::read_only, START, and TRUE.
Referenced by fr_window_archive_add_with_wildcard().
fr_archive_create()
gboolean fr_archive_create (FrArchive * archive, const char * uri)
Definition at line 1035 of file fr-archive.c.
References _FrArchive::command, FALSE, g_signal_handlers_disconnect_by_data, _FrArchive::local_copy, mime_type, NULL, _FrArchive::read_only, and TRUE.
Referenced by fr_window_archive_new(), and fr_window_archive_save_as().
fr_archive_extract()
void fr_archive_extract (FrArchive * archive, GList * file_list, const char * dest_uri, const char * base_dir, gboolean skip_older, gboolean overwrite, gboolean junk_path, const char * password)
Definition at line 3152 of file fr-archive.c.
References file_list, fr_archive_extract_to_local(), get_temp_work_dir(), NULL, _FrArchive::priv, and uri_is_local().
Referenced by fr_archive_extract_here().
fr_archive_extract_here()
gboolean fr_archive_extract_here (FrArchive * archive, gboolean skip_older, gboolean overwrite, gboolean junk_path, const char * password)
Definition at line 3269 of file fr-archive.c.
References error, FALSE, _FrArchive::file, FR_ACTION_EXTRACTING_FILES, fr_archive_action_completed(), fr_archive_extract(), FR_PROC_ERROR_GENERIC, NULL, _FrArchive::priv, and TRUE.
Referenced by fr_window_archive_extract_here().
fr_archive_extract_to_local()
void fr_archive_extract_to_local (FrArchive * archive, GList * file_list, const char * dest_path, const char * base_dir, gboolean skip_older, gboolean overwrite, gboolean junk_path, const char * password)
Definition at line 2946 of file fr-archive.c.
References _FrArchive::command, debug, DEBUG_INFO, FileData::dir, FALSE, file_list, file_name_from_path(), _FrCommand::files, fr_archive_stoppable(), fr_command_set_n_files(), fr_process_add_arg(), fr_process_begin_command(), fr_process_end_command(), get_file_mtime_for_path(), get_temp_work_dir(), _FrArchive::local_copy, FileData::modified, _FrCommand::n_regular_files, NULL, FileData::original_path, _FrArchive::process, _FrCommand::propCanExtractAll, _FrCommand::propExtractCanAvoidOverwrite, _FrCommand::propExtractCanJunkPaths, _FrCommand::propExtractCanSkipOlder, and TRUE.
Referenced by fr_archive_extract(), fr_window_archive_save_as(), and fr_window_open_files().
fr_archive_fake_load()
gboolean fr_archive_fake_load (FrArchive * archive)
Definition at line 1075 of file fr-archive.c.
References FALSE, NULL, and _FrArchive::priv.
Referenced by fr_archive_reload().
fr_archive_get_last_extraction_destination()
const char * fr_archive_get_last_extraction_destination (FrArchive * archive)
Definition at line 3304 of file fr-archive.c.
References _FrArchive::priv.
fr_archive_get_type()
GType fr_archive_get_type (void)
Definition at line 180 of file fr-archive.c.
References NULL.
fr_archive_load()
gboolean fr_archive_load (FrArchive * archive, const char * uri, const char * password)
Definition at line 1229 of file fr-archive.c.
References FALSE, FR_ACTION_LOADING_ARCHIVE, NULL, START, and TRUE.
Referenced by fr_archive_reload(), and fr_window_archive_open().
fr_archive_load_local()
gboolean fr_archive_load_local (FrArchive * archive, const char * uri, const char * password)
Definition at line 1247 of file fr-archive.c.
References FALSE, FR_ACTION_LOADING_ARCHIVE, NULL, START, and TRUE.
fr_archive_new()
FrArchive * fr_archive_new (void)
Definition at line 357 of file fr-archive.c.
References FR_ARCHIVE, FR_TYPE_ARCHIVE, and NULL.
Referenced by fr_window_archive_save_as().
fr_archive_reload()
void fr_archive_reload (FrArchive * archive, const char * password)
Definition at line 1265 of file fr-archive.c.
References _FrArchive::command, _FrCommand::fake_load, _FrArchive::file, fr_archive_fake_load(), fr_archive_load(), fr_archive_stoppable(), NULL, and TRUE.
Referenced by fr_window_archive_reload().
fr_archive_remove()
void fr_archive_remove (FrArchive * archive, GList * file_list, FrCompression compression)
Definition at line 2533 of file fr-archive.c.
References _FrArchive::command, _FrCommand::creating_archive, FALSE, file_list, file_name_from_path(), fr_archive_stoppable(), fr_command_recompress(), fr_command_uncompress(), fr_process_add_arg(), fr_process_begin_command(), fr_process_end_command(), fr_process_set_sticky(), fr_process_set_working_dir(), get_temp_work_dir(), _FrArchive::local_copy, NULL, _FrArchive::process, _FrArchive::read_only, and TRUE.
Referenced by fr_window_archive_remove().
fr_archive_set_fake_load_func()
void fr_archive_set_fake_load_func (FrArchive * archive, FakeLoadFunc func, gpointer data)
Definition at line 1066 of file fr-archive.c.
References data, and _FrArchive::priv.
fr_archive_stop()
void fr_archive_stop (FrArchive * archive)
Definition at line 292 of file fr-archive.c.
References fr_process_stop(), NULL, _FrArchive::priv, and _FrArchive::process.
Referenced by fr_window_stop().
fr_archive_stoppable()
void fr_archive_stoppable (FrArchive * archive, gboolean stoppable)
Definition at line 282 of file fr-archive.c.
References STOPPABLE.
Referenced by fr_archive_add(), fr_archive_extract_to_local(), fr_archive_reload(), fr_archive_remove(), and fr_archive_test().
fr_archive_test()
void fr_archive_test (FrArchive * archive, const char * password)
Definition at line 3310 of file fr-archive.c.
References _FrArchive::command, fr_archive_stoppable(), fr_command_set_n_files(), fr_command_test(), fr_process_clear(), fr_process_start(), _FrArchive::local_copy, NULL, _FrArchive::process, and TRUE.
Referenced by fr_window_archive_test().
uri_is_archive()
gboolean uri_is_archive (const char * uri)
Definition at line 3326 of file fr-archive.c.
References FALSE, mime_type, mime_type_desc, NULL, and TRUE.