MATE Desktop Environment: fr-command.h File Reference
fr-command.h File Reference
#include <config.h>
#include <glib.h>
#include "file-data.h"
#include "fr-process.h"
Classes
struct _FrCommand
struct _FrCommandClass
Macros
#define PACKAGES(x)
#define FR_TYPE_COMMAND (fr_command_get_type ())
#define FR_COMMAND(obj)
#define FR_COMMAND_CLASS(klass)
#define FR_IS_COMMAND(obj)
#define FR_IS_COMMAND_CLASS(klass)
#define FR_COMMAND_GET_CLASS(obj)
Typedefs
typedef struct _FrCommand FrCommand
typedef struct _FrCommandClass FrCommandClass
Enumerations
enum FrAction {
FR_ACTION_NONE , FR_ACTION_CREATING_NEW_ARCHIVE , FR_ACTION_LOADING_ARCHIVE , FR_ACTION_LISTING_CONTENT ,
FR_ACTION_DELETING_FILES , FR_ACTION_TESTING_ARCHIVE , FR_ACTION_GETTING_FILE_LIST , FR_ACTION_COPYING_FILES_FROM_REMOTE ,
FR_ACTION_ADDING_FILES , FR_ACTION_EXTRACTING_FILES , FR_ACTION_COPYING_FILES_TO_REMOTE , FR_ACTION_CREATING_ARCHIVE ,
FR_ACTION_SAVING_REMOTE_ARCHIVE
}
Functions
GType fr_command_get_type (void)
void fr_command_set_file (FrCommand *comm, GFile *file)
void fr_command_set_multi_volume (FrCommand *comm, GFile *file)
void fr_command_list (FrCommand *comm)
void fr_command_add (FrCommand *comm, const char *from_file, GList *file_list, const char *base_dir, gboolean update, gboolean recursive)
void fr_command_delete (FrCommand *comm, const char *from_file, GList *file_list)
void fr_command_extract (FrCommand *comm, const char *from_file, GList *file_list, const char *dest_dir, gboolean overwrite, gboolean skip_older, gboolean junk_paths)
void fr_command_test (FrCommand *comm)
void fr_command_uncompress (FrCommand *comm)
void fr_command_recompress (FrCommand *comm)
gboolean fr_command_is_capable_of (FrCommand *comm, FrCommandCaps capabilities)
const char ** fr_command_get_mime_types (FrCommand *comm)
void fr_command_update_capabilities (FrCommand *comm)
FrCommandCaps fr_command_get_capabilities (FrCommand *comm, const char *mime_type, gboolean check_command)
void fr_command_set_mime_type (FrCommand *comm, const char *mime_type)
const char * fr_command_get_packages (FrCommand *comm, const char *mime_type)
void fr_command_progress (FrCommand *comm, double fraction)
void fr_command_message (FrCommand *comm, const char *msg)
void fr_command_working_archive (FrCommand *comm, const char *archive_name)
void fr_command_set_n_files (FrCommand *comm, int n_files)
void fr_command_add_file (FrCommand *comm, FileData *fdata)
void fr_command_handle_error (FrCommand *comm, FrProcError *error)
Macro Definition Documentation
FR_COMMAND
#define FR_COMMAND (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), FR_TYPE_COMMAND, FrCommand))
Definition at line 34 of file fr-command.h.
Referenced by fr_command_add(), fr_command_delete(), fr_command_extract(), and fr_command_test().
FR_COMMAND_CLASS
#define FR_COMMAND_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), FR_TYPE_COMMAND, FrCommandClass))
Definition at line 35 of file fr-command.h.
FR_COMMAND_GET_CLASS
#define FR_COMMAND_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS((obj), FR_TYPE_COMMAND, FrCommandClass))
Definition at line 38 of file fr-command.h.
Referenced by fr_command_add(), fr_command_delete(), fr_command_extract(), fr_command_get_capabilities(), fr_command_get_mime_types(), fr_command_get_packages(), fr_command_handle_error(), fr_command_list(), fr_command_recompress(), fr_command_set_mime_type(), fr_command_test(), and fr_command_uncompress().
FR_IS_COMMAND
#define FR_IS_COMMAND (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), FR_TYPE_COMMAND))
Definition at line 36 of file fr-command.h.
Referenced by fr_command_list().
FR_IS_COMMAND_CLASS
#define FR_IS_COMMAND_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), FR_TYPE_COMMAND))
Definition at line 37 of file fr-command.h.
FR_TYPE_COMMAND
#define FR_TYPE_COMMAND (fr_command_get_type ())
Definition at line 33 of file fr-command.h.
Referenced by fr_command_7z_get_type(), fr_command_ace_get_type(), fr_command_alz_get_type(), fr_command_ar_get_type(), fr_command_arj_get_type(), fr_command_cfile_get_type(), fr_command_cpio_get_type(), fr_command_dpkg_get_type(), fr_command_iso_get_type(), fr_command_lha_get_type(), fr_command_lrzip_get_type(), fr_command_nomarch_get_type(), fr_command_rar_get_type(), fr_command_rpm_get_type(), fr_command_tar_get_type(), fr_command_unarchiver_get_type(), fr_command_unstuff_get_type(), fr_command_zip_get_type(), and fr_command_zoo_get_type().
PACKAGES
#define PACKAGES (x)
Value:
(x)
Definition at line 31 of file fr-command.h.
Typedef Documentation
FrCommand
typedef struct _FrCommand FrCommand
Definition at line 40 of file fr-command.h.
FrCommandClass
typedef struct _FrCommandClass FrCommandClass
Definition at line 41 of file fr-command.h.
Enumeration Type Documentation
FrAction
enum FrAction
Enumerator
FR_ACTION_NONE
FR_ACTION_CREATING_NEW_ARCHIVE
FR_ACTION_LOADING_ARCHIVE
FR_ACTION_LISTING_CONTENT
FR_ACTION_DELETING_FILES
FR_ACTION_TESTING_ARCHIVE
FR_ACTION_GETTING_FILE_LIST
FR_ACTION_COPYING_FILES_FROM_REMOTE
FR_ACTION_ADDING_FILES
FR_ACTION_EXTRACTING_FILES
FR_ACTION_COPYING_FILES_TO_REMOTE
FR_ACTION_CREATING_ARCHIVE
FR_ACTION_SAVING_REMOTE_ARCHIVE
Definition at line 43 of file fr-command.h.
Function Documentation
fr_command_add()
void fr_command_add (FrCommand * comm, const char * from_file, GList * file_list, const char * base_dir, gboolean update, gboolean recursive)
Definition at line 627 of file fr-command.c.
References _FrCommand::action, file_list, FR_ACTION_ADDING_FILES, FR_COMMAND, FR_COMMAND_GET_CLASS, fr_command_progress(), fr_process_set_err_line_func(), fr_process_set_out_line_func(), and NULL.
Referenced by fr_archive_add().
fr_command_add_file()
void fr_command_add_file (FrCommand * comm, FileData * fdata)
Definition at line 791 of file fr-command.c.
References FileData::dir, file_data_update_content_type(), _FrCommand::files, and _FrCommand::n_regular_files.
fr_command_delete()
void fr_command_delete (FrCommand * comm, const char * from_file, GList * file_list)
Definition at line 649 of file fr-command.c.
References _FrCommand::action, file_list, FR_ACTION_DELETING_FILES, FR_COMMAND, FR_COMMAND_GET_CLASS, fr_command_progress(), fr_process_set_err_line_func(), fr_process_set_out_line_func(), and NULL.
fr_command_extract()
void fr_command_extract (FrCommand * comm, const char * from_file, GList * file_list, const char * dest_dir, gboolean overwrite, gboolean skip_older, gboolean junk_paths)
Definition at line 663 of file fr-command.c.
References _FrCommand::action, file_list, FR_ACTION_EXTRACTING_FILES, FR_COMMAND, FR_COMMAND_GET_CLASS, fr_command_progress(), fr_process_set_err_line_func(), fr_process_set_out_line_func(), and NULL.
fr_command_get_capabilities()
FrCommandCaps fr_command_get_capabilities (FrCommand * comm, const char * mime_type, gboolean check_command)
Definition at line 725 of file fr-command.c.
References FR_COMMAND_GET_CLASS, and mime_type.
Referenced by fr_command_update_capabilities(), and update_registered_commands_capabilities().
fr_command_get_mime_types()
const char ** fr_command_get_mime_types (FrCommand * comm)
Definition at line 713 of file fr-command.c.
References FR_COMMAND_GET_CLASS.
fr_command_get_packages()
const char * fr_command_get_packages (FrCommand * comm, const char * mime_type)
Definition at line 740 of file fr-command.c.
References FR_COMMAND_GET_CLASS, and mime_type.
Referenced by dlg_package_installer().
fr_command_get_type()
GType fr_command_get_type (void)
Definition at line 90 of file fr-command.c.
References NULL.
fr_command_handle_error()
void fr_command_handle_error (FrCommand * comm, FrProcError * error)
Definition at line 808 of file fr-command.c.
References error, and FR_COMMAND_GET_CLASS.
fr_command_is_capable_of()
gboolean fr_command_is_capable_of (FrCommand * comm, FrCommandCaps capabilities)
Definition at line 733 of file fr-command.c.
References _FrCommand::capabilities.
fr_command_list()
void fr_command_list (FrCommand * comm)
Definition at line 594 of file fr-command.c.
References _FrCommand::action, DONE, _FrProcess::error, _FrCommand::fake_load, FALSE, file_data_free(), _FrCommand::files, FR_ACTION_LISTING_CONTENT, FR_COMMAND_GET_CLASS, fr_command_progress(), FR_IS_COMMAND, FR_PROC_ERROR_NONE, fr_process_set_err_line_func(), fr_process_set_out_line_func(), fr_process_use_standard_locale(), FrProcError::gerror, INITIAL_SIZE, _FrCommand::multi_volume, NULL, _FrCommand::process, FrProcError::status, TRUE, and FrProcError::type.
fr_command_message()
void fr_command_message (FrCommand * comm, const char * msg)
Definition at line 763 of file fr-command.c.
References MESSAGE.
fr_command_progress()
void fr_command_progress (FrCommand * comm, double fraction)
Definition at line 753 of file fr-command.c.
References PROGRESS.
Referenced by fr_command_add(), fr_command_delete(), fr_command_extract(), fr_command_list(), fr_command_recompress(), fr_command_test(), and fr_command_uncompress().
fr_command_recompress()
void fr_command_recompress (FrCommand * comm)
Definition at line 706 of file fr-command.c.
References FR_COMMAND_GET_CLASS, and fr_command_progress().
Referenced by fr_archive_add(), and fr_archive_remove().
fr_command_set_file()
void fr_command_set_file (FrCommand * comm, GFile * file)
Definition at line 574 of file fr-command.c.
Referenced by fr_command_set_multi_volume().
fr_command_set_mime_type()
void fr_command_set_mime_type (FrCommand * comm, const char * mime_type)
Definition at line 801 of file fr-command.c.
References FR_COMMAND_GET_CLASS, and mime_type.
fr_command_set_multi_volume()
void fr_command_set_multi_volume (FrCommand * comm, GFile * file)
Definition at line 586 of file fr-command.c.
References fr_command_set_file(), _FrCommand::multi_volume, and TRUE.
Referenced by rar_check_multi_volume().
fr_command_set_n_files()
void fr_command_set_n_files (FrCommand * comm, int n_files)
Definition at line 783 of file fr-command.c.
References _FrCommand::n_file, and _FrCommand::n_files.
Referenced by fr_archive_add(), fr_archive_extract_to_local(), and fr_archive_test().
fr_command_test()
void fr_command_test (FrCommand * comm)
Definition at line 687 of file fr-command.c.
References _FrCommand::action, FR_ACTION_TESTING_ARCHIVE, FR_COMMAND, FR_COMMAND_GET_CLASS, fr_command_progress(), fr_process_set_err_line_func(), fr_process_set_out_line_func(), and NULL.
Referenced by fr_archive_test().
fr_command_uncompress()
void fr_command_uncompress (FrCommand * comm)
Definition at line 699 of file fr-command.c.
References FR_COMMAND_GET_CLASS, and fr_command_progress().
Referenced by fr_archive_add(), and fr_archive_remove().
fr_command_update_capabilities()
void fr_command_update_capabilities (FrCommand * comm)
Definition at line 719 of file fr-command.c.
References _FrCommand::capabilities, fr_command_get_capabilities(), _FrCommand::mime_type, and TRUE.
fr_command_working_archive()
void fr_command_working_archive (FrCommand * comm, const char * archive_name)
Definition at line 773 of file fr-command.c.
References WORKING_ARCHIVE.