MATE Desktop Environment: fr-init.c File Reference
fr-init.c File Reference
#include <config.h>
#include <stdlib.h>
#include <glib/gi18n.h>
#include "file-data.h"
#include "file-utils.h"
#include "glib-utils.h"
#include "fr-command.h"
#include "fr-command-ace.h"
#include "fr-command-alz.h"
#include "fr-command-ar.h"
#include "fr-command-arj.h"
#include "fr-command-cfile.h"
#include "fr-command-cpio.h"
#include "fr-command-dpkg.h"
#include "fr-command-iso.h"
#include "fr-command-jar.h"
#include "fr-command-lha.h"
#include "fr-command-nomarch.h"
#include "fr-command-rar.h"
#include "fr-command-rpm.h"
#include "fr-command-tar.h"
#include "fr-command-unstuff.h"
#include "fr-command-zip.h"
#include "fr-command-zoo.h"
#include "fr-command-7z.h"
#include "fr-command-lrzip.h"
#include "fr-init.h"
#include "fr-process.h"
#include "fr-window.h"
#include "typedefs.h"
#include "preferences.h"
Functions
GType get_command_type_from_mime_type (const char *mime_type, FrCommandCaps requested_capabilities)
GType get_preferred_command_for_mime_type (const char *mime_type, FrCommandCaps requested_capabilities)
void update_registered_commands_capabilities (void)
const char * get_mime_type_from_extension (const char *ext)
const char * get_archive_filename_extension (const char *filename)
int get_mime_type_index (const char *mime_type)
void sort_mime_types_by_extension (int *a)
void sort_mime_types_by_description (int *a)
void initialize_data (void)
void release_data (void)
Variables
FrMimeTypeDescription mime_type_desc []
FrExtensionType file_ext_type []
GList * CommandList
gint ForceDirectoryCreation
GHashTable * ProgramsCache
GPtrArray * Registered_Commands
int single_file_save_type [G_N_ELEMENTS(mime_type_desc)]
int save_type [G_N_ELEMENTS(mime_type_desc)]
int open_type [G_N_ELEMENTS(mime_type_desc)]
int create_type [G_N_ELEMENTS(mime_type_desc)]
Function Documentation
get_archive_filename_extension()
const char * get_archive_filename_extension (const char * filename)
Definition at line 471 of file fr-init.c.
References file_ext_type, get_file_extension(), and NULL.
Referenced by remove_extension_from_path().
get_command_type_from_mime_type()
GType get_command_type_from_mime_type (const char * mime_type, FrCommandCaps requested_capabilities)
Definition at line 383 of file fr-init.c.
References capabilities, mime_type, NULL, and Registered_Commands.
get_mime_type_from_extension()
const char * get_mime_type_from_extension (const char * ext)
Definition at line 453 of file fr-init.c.
References file_ext_type, get_static_string(), mime_type, and NULL.
get_mime_type_index()
int get_mime_type_index (const char * mime_type)
Definition at line 506 of file fr-init.c.
References is_mime_type(), mime_type, mime_type_desc, and NULL.
get_preferred_command_for_mime_type()
GType get_preferred_command_for_mime_type (const char * mime_type, FrCommandCaps requested_capabilities)
Definition at line 407 of file fr-init.c.
References capabilities, mime_type, and Registered_Commands.
Referenced by dlg_package_installer().
initialize_data()
void initialize_data (void)
Definition at line 620 of file fr-init.c.
References NULL, ProgramsCache, and TRUE.
release_data()
void release_data (void)
Definition at line 669 of file fr-init.c.
References CommandList, and NULL.
Referenced by main().
sort_mime_types_by_description()
void sort_mime_types_by_description (int * a)
Definition at line 569 of file fr-init.c.
sort_mime_types_by_extension()
void sort_mime_types_by_extension (int * a)
Definition at line 563 of file fr-init.c.
Referenced by dlg_batch_add_files().
update_registered_commands_capabilities()
void update_registered_commands_capabilities (void)
Definition at line 428 of file fr-init.c.
References FrRegisteredCommand::caps, FrMimeTypeCap::current_capabilities, FALSE, fr_command_get_capabilities(), FrMimeTypeCap::mime_type, NULL, FrMimeTypeCap::potential_capabilities, ProgramsCache, Registered_Commands, TRUE, and FrRegisteredCommand::type.
Variable Documentation
CommandList
GList* CommandList
Definition at line 192 of file fr-init.c.
Referenced by release_data().
create_type
int create_type[G_N_ELEMENTS(mime_type_desc)]
Definition at line 199 of file fr-init.c.
Referenced by dlg_new().
file_ext_type
FrExtensionType file_ext_type[]
Definition at line 119 of file fr-init.c.
Referenced by get_archive_filename_extension(), and get_mime_type_from_extension().
ForceDirectoryCreation
gint ForceDirectoryCreation
Definition at line 193 of file fr-init.c.
Referenced by fr_window_archive_extract().
mime_type_desc
FrMimeTypeDescription mime_type_desc[]
Definition at line 59 of file fr-init.c.
Referenced by activate_action_open(), dlg_batch_add_files(), dlg_new_data_get_encrypt_header(), dlg_new_data_get_password(), dlg_new_data_get_volume_size(), get_mime_type_index(), and uri_is_archive().
open_type
int open_type[G_N_ELEMENTS(mime_type_desc)]
Definition at line 198 of file fr-init.c.
Referenced by activate_action_open().
ProgramsCache
GHashTable* ProgramsCache
Definition at line 194 of file fr-init.c.
Referenced by initialize_data(), is_program_in_path(), and update_registered_commands_capabilities().
Registered_Commands
GPtrArray* Registered_Commands
Definition at line 195 of file fr-init.c.
Referenced by get_command_type_from_mime_type(), get_preferred_command_for_mime_type(), and update_registered_commands_capabilities().
save_type
int save_type[G_N_ELEMENTS(mime_type_desc)]
Definition at line 197 of file fr-init.c.
Referenced by dlg_batch_add_files(), and dlg_save_as().
single_file_save_type
int single_file_save_type[G_N_ELEMENTS(mime_type_desc)]
Definition at line 196 of file fr-init.c.
Referenced by dlg_batch_add_files().