MATE Desktop Environment: fr-window.c File Reference
fr-window.c File Reference
#include <config.h>
#include <math.h>
#include <string.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gdk/gdk.h>
#include <gdk/gdkkeysyms.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include "actions.h"
#include "dlg-batch-add.h"
#include "dlg-delete.h"
#include "dlg-extract.h"
#include "dlg-open-with.h"
#include "dlg-ask-password.h"
#include "dlg-package-installer.h"
#include "dlg-update.h"
#include "eggtreemultidnd.h"
#include "fr-marshal.h"
#include "fr-list-model.h"
#include "fr-archive.h"
#include "fr-error.h"
#include "fr-window.h"
#include "file-data.h"
#include "file-utils.h"
#include "glib-utils.h"
#include "fr-init.h"
#include "gtk-utils.h"
#include "open-file.h"
#include "typedefs.h"
#include "ui.h"
Macros
#define UNUSED_VARIABLE
#define LAST_OUTPUT_DIALOG_NAME "last-output"
#define ACTIVITY_DELAY 100
#define ACTIVITY_PULSE_STEP (0.033)
#define PROGRESS_TIMEOUT_MSECS 5000
#define PROGRESS_DIALOG_DEFAULT_WIDTH 500
#define PROGRESS_BAR_HEIGHT 10
#define HIDE_PROGRESS_TIMEOUT_MSECS 500
#define DEFAULT_NAME_COLUMN_WIDTH 250
#define OTHER_COLUMNS_WIDTH 100
#define FILE_LIST_ICON_SIZE GTK_ICON_SIZE_LARGE_TOOLBAR
#define BAD_CHARS "/\\*"
#define XDS_FILENAME "xds.txt"
#define MAX_XDS_ATOM_VAL_LEN 4096
#define XDS_ATOM gdk_atom_intern ("XdndDirectSave0", FALSE)
#define TEXT_ATOM gdk_atom_intern ("text/plain", FALSE)
#define XFR_ATOM gdk_atom_intern ("XdndEngrampa0", FALSE)
#define FR_CLIPBOARD (gdk_atom_intern_static_string ("_RNGRAMPA_SPECIAL_CLIPBOARD"))
#define FR_SPECIAL_URI_LIST (gdk_atom_intern_static_string ("application/engrampa-uri-list"))
#define _FR_RESPONSE_OVERWRITE_YES_ALL 100
#define _FR_RESPONSE_OVERWRITE_YES 101
#define _FR_RESPONSE_OVERWRITE_NO 102
Enumerations
enum FRClipboardOp { FR_CLIPBOARD_OP_CUT , FR_CLIPBOARD_OP_COPY }
enum FrWindowArea {
FR_WINDOW_AREA_MENUBAR , FR_WINDOW_AREA_TOOLBAR , FR_WINDOW_AREA_LOCATIONBAR , FR_WINDOW_AREA_CONTENTS ,
FR_WINDOW_AREA_FILTERBAR , FR_WINDOW_AREA_STATUSBAR
}
enum DialogResponse {
DIALOG_RESPONSE_NONE = 1 , DIALOG_RESPONSE_OPEN_ARCHIVE , DIALOG_RESPONSE_OPEN_DESTINATION_FOLDER , DIALOG_RESPONSE_OPEN_DESTINATION_FOLDER_AND_QUIT ,
DIALOG_RESPONSE_QUIT
}
enum { ARCHIVE_LOADED , PROGRESS , READY , LAST_SIGNAL }
Functions
void fr_window_close (FrWindow *window)
GType fr_window_get_type (void)
void fr_window_update_list_order (FrWindow *window)
void fr_window_push_message (FrWindow *window, const char *msg)
void fr_window_pop_message (FrWindow *window)
void fr_window_destroy_with_error_dialog (FrWindow *window)
GList * fr_window_get_file_list_selection (FrWindow *window, gboolean recursive, gboolean *has_dirs)
GList * fr_window_get_folder_tree_selection (FrWindow *window, gboolean recursive, gboolean *has_dirs)
GList * fr_window_get_file_list_from_path_list (FrWindow *window, GList *path_list, gboolean *has_dirs)
GList * fr_window_get_file_list_pattern (FrWindow *window, const char *pattern)
int fr_window_get_n_selected_files (FrWindow *window)
void fr_window_current_folder_activated (FrWindow *window, gboolean from_sidebar)
gboolean fr_window_file_list_drag_data_get (FrWindow *window, GdkDragContext *context, GtkSelectionData *selection_data, GList *path_list)
GtkWidget * fr_window_new (void)
gboolean fr_window_archive_new (FrWindow *window, const char *uri)
FrWindow * fr_window_archive_open (FrWindow *current_window, const char *uri, GtkWindow *parent)
void fr_window_archive_close (FrWindow *window)
const char * fr_window_get_archive_uri (FrWindow *window)
const char * fr_window_get_paste_archive_uri (FrWindow *window)
gboolean fr_window_archive_is_present (FrWindow *window)
void fr_window_archive_save_as (FrWindow *window, const char *uri, const char *password, gboolean encrypt_header, guint volume_size)
void fr_window_archive_reload (FrWindow *window)
void fr_window_archive_add_files (FrWindow *window, GList *file_list, gboolean update)
void fr_window_archive_add_with_wildcard (FrWindow *window, const char *include_files, const char *exclude_files, const char *exclude_folders, const char *base_dir, const char *dest_dir, gboolean update, gboolean follow_links)
void fr_window_archive_add_directory (FrWindow *window, const char *directory, const char *base_dir, const char *dest_dir, gboolean update)
void fr_window_archive_add_items (FrWindow *window, GList *item_list, const char *base_dir, const char *dest_dir, gboolean update)
void fr_window_archive_add_dropped_items (FrWindow *window, GList *item_list, gboolean update)
void fr_window_archive_remove (FrWindow *window, GList *file_list)
void fr_window_archive_extract_here (FrWindow *window, gboolean skip_older, FrOverwrite overwrite, gboolean junk_paths)
void fr_window_archive_extract (FrWindow *window, GList *file_list, const char *extract_to_dir, const char *sub_dir, const char *base_dir, gboolean skip_older, FrOverwrite overwrite, gboolean junk_paths, gboolean ask_to_open_destination)
void fr_window_archive_test (FrWindow *window)
void fr_window_set_password (FrWindow *window, const char *password)
void fr_window_set_password_for_paste (FrWindow *window, const char *password)
const char * fr_window_get_password (FrWindow *window)
void fr_window_set_encrypt_header (FrWindow *window, gboolean encrypt_header)
gboolean fr_window_get_encrypt_header (FrWindow *window)
void fr_window_set_compression (FrWindow *window, FrCompression compression)
FrCompression fr_window_get_compression (FrWindow *window)
void fr_window_set_volume_size (FrWindow *window, guint volume_size)
guint fr_window_get_volume_size (FrWindow *window)
void fr_window_go_to_location (FrWindow *window, const char *path, gboolean force_update)
const char * fr_window_get_current_location (FrWindow *window)
void fr_window_go_up_one_level (FrWindow *window)
void fr_window_go_back (FrWindow *window)
void fr_window_go_forward (FrWindow *window)
void fr_window_set_list_mode (FrWindow *window, FrWindowListMode list_mode)
GtkTreeModel * fr_window_get_list_store (FrWindow *window)
void fr_window_find (FrWindow *window)
void fr_window_select_all (FrWindow *window)
void fr_window_unselect_all (FrWindow *window)
void fr_window_stop (FrWindow *window)
void fr_window_start_activity_mode (FrWindow *window)
void fr_window_stop_activity_mode (FrWindow *window)
void fr_window_view_last_output (FrWindow *window, const char *title)
void fr_window_rename_selection (FrWindow *window, gboolean from_sidebar)
GList * fr_window_get_selection (FrWindow *window, gboolean from_sidebar, char **return_base_dir)
void fr_window_copy_selection (FrWindow *window, gboolean from_sidebar)
void fr_window_cut_selection (FrWindow *window, gboolean from_sidebar)
void fr_window_paste_selection (FrWindow *window, gboolean from_sidebar)
void fr_window_open_files_with_command (FrWindow *window, GList *file_list, char *command)
void fr_window_open_files_with_application (FrWindow *window, GList *file_list, GAppInfo *app)
void fr_window_update_dialog_closed (FrWindow *window)
gboolean fr_window_update_files (FrWindow *window, GList *file_list)
void fr_window_open_files (FrWindow *window, GList *file_list, gboolean ask_application)
void fr_window_set_open_default_dir (FrWindow *window, const char *default_dir)
const char * fr_window_get_open_default_dir (FrWindow *window)
void fr_window_set_add_default_dir (FrWindow *window, const char *default_dir)
const char * fr_window_get_add_default_dir (FrWindow *window)
void fr_window_set_extract_default_dir (FrWindow *window, const char *default_dir, gboolean freeze)
const char * fr_window_get_extract_default_dir (FrWindow *window)
void fr_window_set_default_dir (FrWindow *window, const char *default_dir, gboolean freeze)
void fr_window_update_columns_visibility (FrWindow *window)
void fr_window_set_toolbar_visibility (FrWindow *window, gboolean visible)
void fr_window_set_statusbar_visibility (FrWindow *window, gboolean visible)
void fr_window_set_folders_visibility (FrWindow *window, gboolean value)
void fr_window_use_progress_dialog (FrWindow *window, gboolean value)
void fr_window_reset_current_batch_action (FrWindow *window)
void fr_window_set_current_batch_action (FrWindow *window, FrBatchActionType action, void *data, GFreeFunc free_func)
void fr_window_restart_current_batch_action (FrWindow *window)
void fr_window_append_batch_action (FrWindow *window, FrBatchActionType action, void *data, GFreeFunc free_func)
void fr_window_start_batch (FrWindow *window)
void fr_window_stop_batch (FrWindow *window)
void fr_window_resume_batch (FrWindow *window)
gboolean fr_window_is_batch_mode (FrWindow *window)
void fr_window_new_batch (FrWindow *window, const char *title)
void fr_window_set_batch__extract_here (FrWindow *window, const char *filename)
void fr_window_set_batch__extract (FrWindow *window, const char *filename, const char *dest_dir)
void fr_window_set_batch__add (FrWindow *window, const char *archive, GList *file_list)
void fr_window_set_close_dialog (FrWindow *window, gboolean state)
Macro Definition Documentation
_FR_RESPONSE_OVERWRITE_NO
#define _FR_RESPONSE_OVERWRITE_NO 102
Definition at line 6508 of file fr-window.c.
_FR_RESPONSE_OVERWRITE_YES
#define _FR_RESPONSE_OVERWRITE_YES 101
Definition at line 6507 of file fr-window.c.
_FR_RESPONSE_OVERWRITE_YES_ALL
#define _FR_RESPONSE_OVERWRITE_YES_ALL 100
Definition at line 6506 of file fr-window.c.
ACTIVITY_DELAY
#define ACTIVITY_DELAY 100
Definition at line 63 of file fr-window.c.
Referenced by fr_window_start_activity_mode().
ACTIVITY_PULSE_STEP
#define ACTIVITY_PULSE_STEP (0.033)
Definition at line 64 of file fr-window.c.
BAD_CHARS
#define BAD_CHARS "/\\*"
Definition at line 77 of file fr-window.c.
DEFAULT_NAME_COLUMN_WIDTH
#define DEFAULT_NAME_COLUMN_WIDTH 250
Definition at line 72 of file fr-window.c.
FILE_LIST_ICON_SIZE
#define FILE_LIST_ICON_SIZE GTK_ICON_SIZE_LARGE_TOOLBAR
Definition at line 75 of file fr-window.c.
FR_CLIPBOARD
#define FR_CLIPBOARD (gdk_atom_intern_static_string ("_RNGRAMPA_SPECIAL_CLIPBOARD"))
Definition at line 89 of file fr-window.c.
FR_SPECIAL_URI_LIST
#define FR_SPECIAL_URI_LIST (gdk_atom_intern_static_string ("application/engrampa-uri-list"))
Definition at line 90 of file fr-window.c.
HIDE_PROGRESS_TIMEOUT_MSECS
#define HIDE_PROGRESS_TIMEOUT_MSECS 500
Definition at line 71 of file fr-window.c.
LAST_OUTPUT_DIALOG_NAME
#define LAST_OUTPUT_DIALOG_NAME "last-output"
Definition at line 62 of file fr-window.c.
Referenced by fr_window_view_last_output().
MAX_XDS_ATOM_VAL_LEN
#define MAX_XDS_ATOM_VAL_LEN 4096
Definition at line 84 of file fr-window.c.
OTHER_COLUMNS_WIDTH
#define OTHER_COLUMNS_WIDTH 100
Definition at line 73 of file fr-window.c.
PROGRESS_BAR_HEIGHT
#define PROGRESS_BAR_HEIGHT 10
Definition at line 68 of file fr-window.c.
PROGRESS_DIALOG_DEFAULT_WIDTH
#define PROGRESS_DIALOG_DEFAULT_WIDTH 500
Definition at line 67 of file fr-window.c.
PROGRESS_TIMEOUT_MSECS
#define PROGRESS_TIMEOUT_MSECS 5000
Definition at line 66 of file fr-window.c.
TEXT_ATOM
#define TEXT_ATOM gdk_atom_intern ("text/plain", FALSE)
Definition at line 86 of file fr-window.c.
UNUSED_VARIABLE
#define UNUSED_VARIABLE
Definition at line 59 of file fr-window.c.
XDS_ATOM
#define XDS_ATOM gdk_atom_intern ("XdndDirectSave0", FALSE)
Definition at line 85 of file fr-window.c.
XDS_FILENAME
#define XDS_FILENAME "xds.txt"
Definition at line 83 of file fr-window.c.
XFR_ATOM
#define XFR_ATOM gdk_atom_intern ("XdndEngrampa0", FALSE)
Definition at line 87 of file fr-window.c.
Referenced by fr_window_file_list_drag_data_get().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ARCHIVE_LOADED
PROGRESS
READY
LAST_SIGNAL
Definition at line 217 of file fr-window.c.
DialogResponse
enum DialogResponse
Enumerator
DIALOG_RESPONSE_NONE
DIALOG_RESPONSE_OPEN_ARCHIVE
DIALOG_RESPONSE_OPEN_DESTINATION_FOLDER
DIALOG_RESPONSE_OPEN_DESTINATION_FOLDER_AND_QUIT
DIALOG_RESPONSE_QUIT
Definition at line 149 of file fr-window.c.
FRClipboardOp
enum FRClipboardOp
Enumerator
FR_CLIPBOARD_OP_CUT
FR_CLIPBOARD_OP_COPY
Definition at line 122 of file fr-window.c.
FrWindowArea
enum FrWindowArea
Enumerator
FR_WINDOW_AREA_MENUBAR
FR_WINDOW_AREA_TOOLBAR
FR_WINDOW_AREA_LOCATIONBAR
FR_WINDOW_AREA_CONTENTS
FR_WINDOW_AREA_FILTERBAR
FR_WINDOW_AREA_STATUSBAR
Definition at line 140 of file fr-window.c.
Function Documentation
fr_window_append_batch_action()
void fr_window_append_batch_action (FrWindow * window, FrBatchActionType action, void * data, GFreeFunc free_func)
Definition at line 8715 of file fr-window.c.
References action, data, and NULL.
Referenced by fr_window_set_batch__add(), fr_window_set_batch__extract(), and fr_window_set_batch__extract_here().
fr_window_archive_add_directory()
void fr_window_archive_add_directory (FrWindow * window, const char * directory, const char * base_dir, const char * dest_dir, gboolean update)
Definition at line 6235 of file fr-window.c.
References fr_archive_add_directory(), fr_window_get_current_location(), and NULL.
fr_window_archive_add_dropped_items()
void fr_window_archive_add_dropped_items (FrWindow * window, GList * item_list, gboolean update)
Definition at line 6271 of file fr-window.c.
References fr_archive_add_dropped_items(), and fr_window_get_current_location().
fr_window_archive_add_files()
void fr_window_archive_add_files (FrWindow * window, GList * file_list, gboolean update)
Definition at line 6163 of file fr-window.c.
References file_list, fr_archive_add_files(), fr_window_get_current_location(), and NULL.
fr_window_archive_add_items()
void fr_window_archive_add_items (FrWindow * window, GList * item_list, const char * base_dir, const char * dest_dir, gboolean update)
Definition at line 6253 of file fr-window.c.
References fr_archive_add_items(), fr_window_get_current_location(), and NULL.
fr_window_archive_add_with_wildcard()
void fr_window_archive_add_with_wildcard (FrWindow * window, const char * include_files, const char * exclude_files, const char * exclude_folders, const char * base_dir, const char * dest_dir, gboolean update, gboolean follow_links)
Definition at line 6211 of file fr-window.c.
References fr_archive_add_with_wildcard(), fr_window_get_current_location(), and NULL.
fr_window_archive_close()
void fr_window_archive_close (FrWindow * window)
Definition at line 5964 of file fr-window.c.
References FALSE, fr_window_set_password(), fr_window_set_volume_size(), and NULL.
Referenced by fr_window_archive_open(), and fr_window_stop_batch().
fr_window_archive_extract()
void fr_window_archive_extract (FrWindow * window, GList * file_list, const char * extract_to_dir, const char * sub_dir, const char * base_dir, gboolean skip_older, FrOverwrite overwrite, gboolean junk_paths, gboolean ask_to_open_destination)
Definition at line 6681 of file fr-window.c.
References _, _gtk_error_dialog_new(), _gtk_message_dialog_new(), dlg_ask_password(), ensure_dir_exists(), error, FALSE, file_list, ForceDirectoryCreation, FR_BATCH_ACTION_EXTRACT_INTERACT, FR_OVERWRITE_ASK, FR_OVERWRITE_YES, fr_window_set_current_batch_action(), fr_window_stop_batch(), NULL, TRUE, and uri_is_dir().
fr_window_archive_extract_here()
void fr_window_archive_extract_here (FrWindow * window, gboolean skip_older, FrOverwrite overwrite, gboolean junk_paths)
Definition at line 6458 of file fr-window.c.
References dlg_ask_password(), FALSE, fr_archive_extract_here(), FR_BATCH_ACTION_EXTRACT_INTERACT, fr_process_clear(), fr_process_start(), fr_window_set_current_batch_action(), NULL, and TRUE.
fr_window_archive_is_present()
gboolean fr_window_archive_is_present (FrWindow * window)
Definition at line 6010 of file fr-window.c.
References FALSE, and NULL.
Referenced by dlg_prop().
fr_window_archive_new()
gboolean fr_window_archive_new (FrWindow * window, const char * uri)
Definition at line 5905 of file fr-window.c.
References _, FALSE, FR_ACTION_CREATING_NEW_ARCHIVE, fr_archive_action_completed(), fr_archive_create(), FR_PROC_ERROR_GENERIC, FR_PROC_ERROR_NONE, NULL, and TRUE.
fr_window_archive_open()
FrWindow * fr_window_archive_open (FrWindow * current_window, const char * uri, GtkWindow * parent)
Definition at line 5935 of file fr-window.c.
References FALSE, fr_archive_load(), FR_BATCH_ACTION_LOAD, fr_window_archive_close(), fr_window_new(), fr_window_set_current_batch_action(), NULL, _FrWindow::priv, and TRUE.
fr_window_archive_reload()
void fr_window_archive_reload (FrWindow * window)
Definition at line 6148 of file fr-window.c.
References fr_archive_reload(), and NULL.
Referenced by activate_action_reload().
fr_window_archive_remove()
void fr_window_archive_remove (FrWindow * window, GList * file_list)
Definition at line 6293 of file fr-window.c.
References file_list, fr_archive_remove(), FR_BATCH_ACTION_DELETE, fr_process_clear(), fr_process_start(), fr_window_set_current_batch_action(), and NULL.
fr_window_archive_save_as()
void fr_window_archive_save_as (FrWindow * window, const char * uri, const char * password, gboolean encrypt_header, guint volume_size)
Definition at line 6054 of file fr-window.c.
References _, _gtk_error_dialog_new(), FALSE, fr_archive_create(), fr_archive_extract_to_local(), fr_archive_new(), FR_BATCH_ACTION_SAVE_AS, fr_process_clear(), fr_process_start(), fr_window_set_current_batch_action(), g_uri_display_basename(), get_temp_work_dir(), message(), NULL, and TRUE.
fr_window_archive_test()
void fr_window_archive_test (FrWindow * window)
Definition at line 6819 of file fr-window.c.
References fr_archive_test(), FR_BATCH_ACTION_TEST, fr_window_set_current_batch_action(), and NULL.
Referenced by activate_action_test_archive().
fr_window_close()
void fr_window_close (FrWindow * window)
Definition at line 658 of file fr-window.c.
References PREF_LISTING_NAME_COLUMN_WIDTH, PREF_UI_SIDEBAR_WIDTH, PREF_UI_WINDOW_HEIGHT, PREF_UI_WINDOW_WIDTH, and TRUE.
Referenced by activate_action_close().
fr_window_copy_selection()
void fr_window_copy_selection (FrWindow * window, gboolean from_sidebar)
Definition at line 7739 of file fr-window.c.
References FR_CLIPBOARD_OP_COPY.
Referenced by activate_action_copy(), activate_popup_copy(), and activate_popup_copy_folder_from_sidebar().
fr_window_current_folder_activated()
void fr_window_current_folder_activated (FrWindow * window, gboolean from_sidebar)
Definition at line 3618 of file fr-window.c.
References FALSE, file_data_free(), file_data_is_dir(), fr_window_get_current_location(), fr_window_go_to_location(), FileData::list_name, and NULL.
Referenced by activate_popup_open_folder(), and activate_popup_open_folder_from_sidebar().
fr_window_cut_selection()
void fr_window_cut_selection (FrWindow * window, gboolean from_sidebar)
Definition at line 7746 of file fr-window.c.
References FR_CLIPBOARD_OP_CUT.
Referenced by activate_action_cut(), activate_popup_cut(), and activate_popup_cut_folder_from_sidebar().
fr_window_destroy_with_error_dialog()
void fr_window_destroy_with_error_dialog (FrWindow * window)
Definition at line 2896 of file fr-window.c.
References TRUE.
fr_window_file_list_drag_data_get()
gboolean fr_window_file_list_drag_data_get (FrWindow * window, GdkDragContext * context, GtkSelectionData * selection_data, GList * path_list)
Definition at line 4373 of file fr-window.c.
References _, check_permissions(), data, debug, DEBUG_INFO, FALSE, FR_CLIPBOARD_OP_COPY, FR_ERROR, fr_window_get_current_location(), fr_window_get_file_list_from_path_list(), fr_window_get_file_list_selection(), NULL, remove_level_from_path(), TRUE, and XFR_ATOM.
fr_window_find()
void fr_window_find (FrWindow * window)
Definition at line 7025 of file fr-window.c.
References TRUE.
Referenced by activate_action_find().
fr_window_get_add_default_dir()
const char * fr_window_get_add_default_dir (FrWindow * window)
Definition at line 8421 of file fr-window.c.
References get_home_uri(), and NULL.
Referenced by add_files_cb().
fr_window_get_archive_uri()
const char * fr_window_get_archive_uri (FrWindow * window)
Definition at line 5991 of file fr-window.c.
References NULL.
Referenced by activate_action_save_as(), and dlg_prop().
fr_window_get_compression()
FrCompression fr_window_get_compression (FrWindow * window)
Definition at line 6891 of file fr-window.c.
fr_window_get_current_location()
const char * fr_window_get_current_location (FrWindow * window)
Definition at line 6944 of file fr-window.c.
References NULL.
Referenced by fr_window_archive_add_directory(), fr_window_archive_add_dropped_items(), fr_window_archive_add_files(), fr_window_archive_add_items(), fr_window_archive_add_with_wildcard(), fr_window_current_folder_activated(), fr_window_file_list_drag_data_get(), fr_window_get_selection(), fr_window_go_up_one_level(), fr_window_paste_selection(), and fr_window_rename_selection().
fr_window_get_encrypt_header()
gboolean fr_window_get_encrypt_header (FrWindow * window)
Definition at line 6876 of file fr-window.c.
Referenced by dlg_password().
fr_window_get_extract_default_dir()
const char * fr_window_get_extract_default_dir (FrWindow * window)
Definition at line 8450 of file fr-window.c.
References get_home_uri(), and NULL.
fr_window_get_file_list_from_path_list()
GList * fr_window_get_file_list_from_path_list (FrWindow * window, GList * path_list, gboolean * has_dirs)
Definition at line 3399 of file fr-window.c.
References COLUMN_FILE_DATA, FALSE, file_data_is_dir(), has_dirs, NULL, FileData::original_path, and TRUE.
Referenced by fr_window_file_list_drag_data_get().
fr_window_get_file_list_pattern()
GList * fr_window_get_file_list_pattern (FrWindow * window, const char * pattern)
Definition at line 3457 of file fr-window.c.
References free_regexps(), match_regexps(), FileData::name, NULL, FileData::original_path, and search_util_get_regexps().
fr_window_get_file_list_selection()
GList * fr_window_get_file_list_selection (FrWindow * window, gboolean recursive, gboolean * has_dirs)
Definition at line 3321 of file fr-window.c.
References FALSE, file_data_is_dir(), has_dirs, NULL, FileData::original_path, and TRUE.
Referenced by activate_popup_open(), dlg_delete(), fr_window_file_list_drag_data_get(), fr_window_get_selection(), and open_with_cb().
fr_window_get_folder_tree_selection()
GList * fr_window_get_folder_tree_selection (FrWindow * window, gboolean recursive, gboolean * has_dirs)
Definition at line 3362 of file fr-window.c.
References FALSE, has_dirs, NULL, and TRUE.
Referenced by dlg_delete_from_sidebar(), and fr_window_get_selection().
fr_window_get_list_store()
GtkTreeModel * fr_window_get_list_store (FrWindow * window)
Definition at line 7019 of file fr-window.c.
fr_window_get_n_selected_files()
int fr_window_get_n_selected_files (FrWindow * window)
Definition at line 3505 of file fr-window.c.
fr_window_get_open_default_dir()
const char * fr_window_get_open_default_dir (FrWindow * window)
Definition at line 8400 of file fr-window.c.
References get_home_uri(), and NULL.
Referenced by activate_action_open().
fr_window_get_password()
const char * fr_window_get_password (FrWindow * window)
Definition at line 6859 of file fr-window.c.
References NULL.
Referenced by dlg_password().
fr_window_get_paste_archive_uri()
const char * fr_window_get_paste_archive_uri (FrWindow * window)
Definition at line 5999 of file fr-window.c.
References NULL.
fr_window_get_selection()
GList * fr_window_get_selection (FrWindow * window, gboolean from_sidebar, char ** return_base_dir)
Definition at line 7673 of file fr-window.c.
References fr_window_get_current_location(), fr_window_get_file_list_selection(), fr_window_get_folder_tree_selection(), NULL, remove_level_from_path(), and TRUE.
Referenced by dlg_extract(), and dlg_extract_folder_from_sidebar().
fr_window_get_type()
GType fr_window_get_type (void)
Definition at line 786 of file fr-window.c.
References NULL.
fr_window_get_volume_size()
guint fr_window_get_volume_size (FrWindow * window)
Definition at line 6906 of file fr-window.c.
fr_window_go_back()
void fr_window_go_back (FrWindow * window)
Definition at line 6967 of file fr-window.c.
References FALSE, fr_window_go_to_location(), and NULL.
Referenced by activate_action_go_back().
fr_window_go_forward()
void fr_window_go_forward (FrWindow * window)
Definition at line 6983 of file fr-window.c.
References FALSE, fr_window_go_to_location(), and NULL.
Referenced by activate_action_go_forward().
fr_window_go_to_location()
void fr_window_go_to_location (FrWindow * window, const char * path, gboolean force_update)
Definition at line 6912 of file fr-window.c.
References NULL, and TRUE.
Referenced by activate_action_go_home(), fr_window_current_folder_activated(), fr_window_go_back(), fr_window_go_forward(), and fr_window_go_up_one_level().
fr_window_go_up_one_level()
void fr_window_go_up_one_level (FrWindow * window)
Definition at line 6955 of file fr-window.c.
References FALSE, fr_window_get_current_location(), fr_window_go_to_location(), and NULL.
Referenced by activate_action_go_up().
fr_window_is_batch_mode()
gboolean fr_window_is_batch_mode (FrWindow * window)
Definition at line 8807 of file fr-window.c.
fr_window_new()
GtkWidget * fr_window_new (void)
Definition at line 5885 of file fr-window.c.
References FR_TYPE_WINDOW, and NULL.
Referenced by fr_window_archive_open().
fr_window_new_batch()
void fr_window_new_batch (FrWindow * window, const char * title)
Definition at line 8813 of file fr-window.c.
References TRUE.
fr_window_open_files()
void fr_window_open_files (FrWindow * window, GList * file_list, gboolean ask_application)
Definition at line 8344 of file fr-window.c.
References FALSE, file_list, fr_archive_extract_to_local(), FR_BATCH_ACTION_OPEN_FILES, fr_process_clear(), fr_process_start(), fr_window_set_current_batch_action(), NULL, CommandData::temp_dir, and TRUE.
Referenced by activate_popup_open(), and open_with_cb().
fr_window_open_files_with_application()
void fr_window_open_files_with_application (FrWindow * window, GList * file_list, GAppInfo * app)
Definition at line 8046 of file fr-window.c.
References _, _gtk_error_dialog_run(), error, file_list, and NULL.
Referenced by fr_window_open_files_with_command().
fr_window_open_files_with_command()
void fr_window_open_files_with_command (FrWindow * window, GList * file_list, char * command)
Definition at line 8025 of file fr-window.c.
References _, _gtk_error_dialog_run(), error, file_list, fr_window_open_files_with_application(), and NULL.
fr_window_paste_selection()
void fr_window_paste_selection (FrWindow * window, gboolean from_sidebar)
Definition at line 7983 of file fr-window.c.
References _, _gtk_request_dialog_run(), build_uri(), fr_window_get_current_location(), FR_WINDOW_LIST_MODE_FLAT, and NULL.
Referenced by activate_action_paste(), activate_popup_paste(), and activate_popup_paste_folder_from_sidebar().
fr_window_pop_message()
void fr_window_pop_message (FrWindow * window)
Definition at line 2761 of file fr-window.c.
References NULL.
fr_window_push_message()
void fr_window_push_message (FrWindow * window, const char * msg)
Definition at line 2749 of file fr-window.c.
fr_window_rename_selection()
void fr_window_rename_selection (FrWindow * window, gboolean from_sidebar)
Definition at line 7513 of file fr-window.c.
References _, _gtk_error_dialog_new(), _gtk_message_dialog_new(), _gtk_request_dialog_run(), FileData::dir, FALSE, file_data_free(), file_data_is_dir(), file_name_from_path(), fr_window_get_current_location(), FileData::full_path, FileData::list_name, FileData::name, NULL, FileData::original_path, remove_ending_separator(), remove_level_from_path(), and TRUE.
Referenced by activate_action_rename(), activate_popup_rename(), and activate_popup_rename_folder_from_sidebar().
fr_window_reset_current_batch_action()
void fr_window_reset_current_batch_action (FrWindow * window)
Definition at line 8682 of file fr-window.c.
References FR_BATCH_ACTION_NONE, and NULL.
Referenced by fr_window_set_current_batch_action().
fr_window_restart_current_batch_action()
void fr_window_restart_current_batch_action (FrWindow * window)
Definition at line 8709 of file fr-window.c.
fr_window_resume_batch()
void fr_window_resume_batch (FrWindow * window)
Definition at line 8801 of file fr-window.c.
fr_window_select_all()
void fr_window_select_all (FrWindow * window)
Definition at line 7033 of file fr-window.c.
Referenced by activate_action_select_all().
fr_window_set_add_default_dir()
void fr_window_set_add_default_dir (FrWindow * window, const char * default_dir)
Definition at line 8409 of file fr-window.c.
References NULL.
Referenced by fr_window_set_default_dir().
fr_window_set_batch__add()
void fr_window_set_batch__add (FrWindow * window, const char * archive, GList * file_list)
Definition at line 8872 of file fr-window.c.
References file_list, FR_BATCH_ACTION_ADD, FR_BATCH_ACTION_CLOSE, FR_BATCH_ACTION_LOAD, FR_BATCH_ACTION_OPEN, fr_window_append_batch_action(), NULL, and uri_is_file().
fr_window_set_batch__extract()
void fr_window_set_batch__extract (FrWindow * window, const char * filename, const char * dest_dir)
Definition at line 8844 of file fr-window.c.
References FR_BATCH_ACTION_CLOSE, FR_BATCH_ACTION_EXTRACT_INTERACT, FR_BATCH_ACTION_LOAD, fr_window_append_batch_action(), and NULL.
fr_window_set_batch__extract_here()
void fr_window_set_batch__extract_here (FrWindow * window, const char * filename)
Definition at line 8823 of file fr-window.c.
References FR_BATCH_ACTION_CLOSE, FR_BATCH_ACTION_EXTRACT_HERE, FR_BATCH_ACTION_LOAD, fr_window_append_batch_action(), and NULL.
fr_window_set_close_dialog()
void fr_window_set_close_dialog (FrWindow * window, gboolean state)
Definition at line 8899 of file fr-window.c.
References NULL.
fr_window_set_compression()
void fr_window_set_compression (FrWindow * window, FrCompression compression)
Definition at line 6882 of file fr-window.c.
References NULL.
fr_window_set_current_batch_action()
void fr_window_set_current_batch_action (FrWindow * window, FrBatchActionType action, void * data, GFreeFunc free_func)
Definition at line 8694 of file fr-window.c.
References action, data, and fr_window_reset_current_batch_action().
Referenced by fr_window_archive_extract(), fr_window_archive_extract_here(), fr_window_archive_open(), fr_window_archive_remove(), fr_window_archive_save_as(), fr_window_archive_test(), and fr_window_open_files().
fr_window_set_default_dir()
void fr_window_set_default_dir (FrWindow * window, const char * default_dir, gboolean freeze)
Definition at line 8459 of file fr-window.c.
References FALSE, fr_window_set_add_default_dir(), fr_window_set_extract_default_dir(), fr_window_set_open_default_dir(), and NULL.
fr_window_set_encrypt_header()
void fr_window_set_encrypt_header (FrWindow * window, gboolean encrypt_header)
Definition at line 6867 of file fr-window.c.
References NULL.
fr_window_set_extract_default_dir()
void fr_window_set_extract_default_dir (FrWindow * window, const char * default_dir, gboolean freeze)
Definition at line 8430 of file fr-window.c.
References NULL.
Referenced by fr_window_set_default_dir().
fr_window_set_folders_visibility()
void fr_window_set_folders_visibility (FrWindow * window, gboolean value)
Definition at line 8521 of file fr-window.c.
References NULL.
fr_window_set_list_mode()
void fr_window_set_list_mode (FrWindow * window, FrWindowListMode list_mode)
Definition at line 6999 of file fr-window.c.
References FR_WINDOW_LIST_MODE_FLAT, NULL, PREF_LISTING_LIST_MODE, PREF_LISTING_SHOW_PATH, and TRUE.
fr_window_set_open_default_dir()
void fr_window_set_open_default_dir (FrWindow * window, const char * default_dir)
Definition at line 8388 of file fr-window.c.
References NULL.
Referenced by fr_window_set_default_dir().
fr_window_set_password()
void fr_window_set_password (FrWindow * window, const char * password)
Definition at line 6829 of file fr-window.c.
References NULL.
Referenced by fr_window_archive_close().
fr_window_set_password_for_paste()
void fr_window_set_password_for_paste (FrWindow * window, const char * password)
Definition at line 6844 of file fr-window.c.
References NULL.
fr_window_set_statusbar_visibility()
void fr_window_set_statusbar_visibility (FrWindow * window, gboolean visible)
Definition at line 8507 of file fr-window.c.
References NULL.
fr_window_set_toolbar_visibility()
void fr_window_set_toolbar_visibility (FrWindow * window, gboolean visible)
Definition at line 8493 of file fr-window.c.
References NULL.
fr_window_set_volume_size()
void fr_window_set_volume_size (FrWindow * window, guint volume_size)
Definition at line 6897 of file fr-window.c.
References NULL.
Referenced by fr_window_archive_close().
fr_window_start_activity_mode()
void fr_window_start_activity_mode (FrWindow * window)
Definition at line 7073 of file fr-window.c.
References ACTIVITY_DELAY, and NULL.
fr_window_start_batch()
void fr_window_start_batch (FrWindow * window)
Definition at line 8756 of file fr-window.c.
References NULL, and TRUE.
fr_window_stop()
void fr_window_stop (FrWindow * window)
Definition at line 7045 of file fr-window.c.
References fr_archive_stop(), and TRUE.
Referenced by activate_action_stop().
fr_window_stop_activity_mode()
void fr_window_stop_activity_mode (FrWindow * window)
Definition at line 7087 of file fr-window.c.
References NULL.
fr_window_stop_batch()
void fr_window_stop_batch (FrWindow * window)
Definition at line 8778 of file fr-window.c.
References FALSE, and fr_window_archive_close().
Referenced by fr_window_archive_extract().
fr_window_unselect_all()
void fr_window_unselect_all (FrWindow * window)
Definition at line 7039 of file fr-window.c.
Referenced by activate_action_deselect_all().
fr_window_update_columns_visibility()
void fr_window_update_columns_visibility (FrWindow * window)
Definition at line 8474 of file fr-window.c.
References PREF_LISTING_SHOW_PATH, PREF_LISTING_SHOW_SIZE, PREF_LISTING_SHOW_TIME, and PREF_LISTING_SHOW_TYPE.
fr_window_update_dialog_closed()
void fr_window_update_dialog_closed (FrWindow * window)
Definition at line 8130 of file fr-window.c.
References NULL.
fr_window_update_files()
gboolean fr_window_update_files (FrWindow * window, GList * file_list)
Definition at line 8136 of file fr-window.c.
References FALSE, file_list, fr_archive_add(), fr_process_clear(), fr_process_start(), NULL, OpenFile::path, OpenFile::temp_dir, and TRUE.
fr_window_update_list_order()
void fr_window_update_list_order (FrWindow * window)
Definition at line 1888 of file fr-window.c.
fr_window_use_progress_dialog()
void fr_window_use_progress_dialog (FrWindow * window, gboolean value)
Definition at line 8533 of file fr-window.c.
fr_window_view_last_output()
void fr_window_view_last_output (FrWindow * window, const char * title)
Definition at line 7148 of file fr-window.c.
References _, FALSE, LAST_OUTPUT_DIALOG_NAME, NULL, pref_util_restore_window_geometry(), and TRUE.
Referenced by activate_action_last_output().