MATE Desktop Environment: fr-window.h File Reference
fr-window.h File Reference
#include <gio/gio.h>
#include <gtk/gtk.h>
#include "typedefs.h"
#include "fr-archive.h"
Classes
struct _FrWindow
struct _FrWindowClass
Macros
#define FR_TYPE_WINDOW (fr_window_get_type ())
#define FR_WINDOW(obj)
#define FR_WINDOW_CLASS(klass)
#define FR_IS_WINDOW(obj)
#define FR_IS_WINDOW_CLASS(klass)
#define FR_WINDOW_GET_CLASS(obj)
Typedefs
typedef struct _FrWindow FrWindow
typedef struct _FrWindowClass FrWindowClass
typedef struct _FrWindowPrivateData FrWindowPrivateData
Enumerations
enum {
COLUMN_FILE_DATA , COLUMN_ICON , COLUMN_NAME , COLUMN_EMBLEM ,
COLUMN_SIZE , COLUMN_TYPE , COLUMN_TIME , COLUMN_PATH ,
NUMBER_OF_COLUMNS
}
enum {
TREE_COLUMN_PATH , TREE_COLUMN_ICON , TREE_COLUMN_NAME , TREE_COLUMN_WEIGHT ,
TREE_NUMBER_OF_COLUMNS
}
enum FrBatchActionType {
FR_BATCH_ACTION_NONE , FR_BATCH_ACTION_LOAD , FR_BATCH_ACTION_OPEN , FR_BATCH_ACTION_ADD ,
FR_BATCH_ACTION_DELETE , FR_BATCH_ACTION_EXTRACT , FR_BATCH_ACTION_EXTRACT_HERE , FR_BATCH_ACTION_EXTRACT_INTERACT ,
FR_BATCH_ACTION_RENAME , FR_BATCH_ACTION_PASTE , FR_BATCH_ACTION_OPEN_FILES , FR_BATCH_ACTION_SAVE_AS ,
FR_BATCH_ACTION_TEST , FR_BATCH_ACTION_CLOSE , FR_BATCH_ACTION_QUIT , FR_BATCH_ACTIONS
}
Functions
GType fr_window_get_type (void)
GtkWidget * fr_window_new (void)
void fr_window_close (FrWindow *window)
gboolean fr_window_archive_new (FrWindow *window, const char *uri)
FrWindow * fr_window_archive_open (FrWindow *window, const char *uri, GtkWindow *parent)
void fr_window_archive_close (FrWindow *window)
const char * fr_window_get_archive_uri (FrWindow *window)
const char * fr_window_get_paste_archive_uri (FrWindow *window)
gboolean fr_window_archive_is_present (FrWindow *window)
void fr_window_archive_save_as (FrWindow *window, const char *filename, const char *password, gboolean encrypt_header, guint volume_size)
void fr_window_archive_reload (FrWindow *window)
void fr_window_archive_add_files (FrWindow *window, GList *file_list, gboolean update)
void fr_window_archive_add_with_wildcard (FrWindow *window, const char *include_files, const char *exclude_files, const char *exclude_folders, const char *base_dir, const char *dest_dir, gboolean update, gboolean follow_links)
void fr_window_archive_add_directory (FrWindow *window, const char *directory, const char *base_dir, const char *dest_dir, gboolean update)
void fr_window_archive_add_items (FrWindow *window, GList *dir_list, const char *base_dir, const char *dest_dir, gboolean update)
void fr_window_archive_add_dropped_items (FrWindow *window, GList *item_list, gboolean update)
void fr_window_archive_remove (FrWindow *window, GList *file_list)
void fr_window_archive_extract (FrWindow *window, GList *file_list, const char *extract_to_dir, const char *sub_dir, const char *base_dir, gboolean skip_older, FrOverwrite overwrite, gboolean junk_paths, gboolean ask_to_open_destination)
void fr_window_archive_extract_here (FrWindow *window, gboolean skip_older, FrOverwrite overwrite, gboolean junk_paths)
void fr_window_archive_test (FrWindow *window)
void fr_window_set_password (FrWindow *window, const char *password)
void fr_window_set_password_for_paste (FrWindow *window, const char *password)
const char * fr_window_get_password (FrWindow *window)
void fr_window_set_encrypt_header (FrWindow *window, gboolean encrypt_header)
gboolean fr_window_get_encrypt_header (FrWindow *window)
void fr_window_set_compression (FrWindow *window, FrCompression compression)
FrCompression fr_window_get_compression (FrWindow *window)
void fr_window_set_volume_size (FrWindow *window, guint volume_size)
guint fr_window_get_volume_size (FrWindow *window)
void fr_window_go_to_location (FrWindow *window, const char *path, gboolean force_update)
const char * fr_window_get_current_location (FrWindow *window)
void fr_window_go_up_one_level (FrWindow *window)
void fr_window_go_back (FrWindow *window)
void fr_window_go_forward (FrWindow *window)
void fr_window_current_folder_activated (FrWindow *window, gboolean from_sidebar)
void fr_window_set_list_mode (FrWindow *window, FrWindowListMode list_mode)
void fr_window_update_list_order (FrWindow *window)
GList * fr_window_get_file_list_selection (FrWindow *window, gboolean recursive, gboolean *has_dirs)
GList * fr_window_get_file_list_from_path_list (FrWindow *window, GList *path_list, gboolean *has_dirs)
GList * fr_window_get_file_list_pattern (FrWindow *window, const char *pattern)
int fr_window_get_n_selected_files (FrWindow *window)
GList * fr_window_get_folder_tree_selection (FrWindow *window, gboolean recursive, gboolean *has_dirs)
GList * fr_window_get_selection (FrWindow *window, gboolean from_sidebar, char **return_base_dir)
GtkTreeModel * fr_window_get_list_store (FrWindow *window)
void fr_window_find (FrWindow *window)
void fr_window_select_all (FrWindow *window)
void fr_window_unselect_all (FrWindow *window)
void fr_window_rename_selection (FrWindow *window, gboolean from_sidebar)
void fr_window_cut_selection (FrWindow *window, gboolean from_sidebar)
void fr_window_copy_selection (FrWindow *window, gboolean from_sidebar)
void fr_window_paste_selection (FrWindow *window, gboolean from_sidebar)
void fr_window_stop (FrWindow *window)
void fr_window_start_activity_mode (FrWindow *window)
void fr_window_stop_activity_mode (FrWindow *window)
void fr_window_view_last_output (FrWindow *window, const char *title)
void fr_window_open_files (FrWindow *window, GList *file_list, gboolean ask_application)
void fr_window_open_files_with_command (FrWindow *window, GList *file_list, char *command)
void fr_window_open_files_with_application (FrWindow *window, GList *file_list, GAppInfo *app)
gboolean fr_window_update_files (FrWindow *window, GList *file_list)
void fr_window_update_columns_visibility (FrWindow *window)
void fr_window_update_history_list (FrWindow *window)
void fr_window_set_default_dir (FrWindow *window, const char *default_dir, gboolean freeze)
void fr_window_set_open_default_dir (FrWindow *window, const char *default_dir)
const char * fr_window_get_open_default_dir (FrWindow *window)
void fr_window_set_add_default_dir (FrWindow *window, const char *default_dir)
const char * fr_window_get_add_default_dir (FrWindow *window)
void fr_window_set_extract_default_dir (FrWindow *window, const char *default_dir, gboolean freeze)
const char * fr_window_get_extract_default_dir (FrWindow *window)
void fr_window_push_message (FrWindow *window, const char *msg)
void fr_window_pop_message (FrWindow *window)
void fr_window_set_toolbar_visibility (FrWindow *window, gboolean value)
void fr_window_set_statusbar_visibility (FrWindow *window, gboolean value)
void fr_window_set_folders_visibility (FrWindow *window, gboolean value)
void fr_window_use_progress_dialog (FrWindow *window, gboolean value)
void fr_window_new_batch (FrWindow *window, const char *title)
void fr_window_set_current_batch_action (FrWindow *window, FrBatchActionType action, void *data, GFreeFunc free_func)
void fr_window_reset_current_batch_action (FrWindow *window)
void fr_window_restart_current_batch_action (FrWindow *window)
void fr_window_append_batch_action (FrWindow *window, FrBatchActionType action, void *data, GFreeFunc free_func)
void fr_window_start_batch (FrWindow *window)
void fr_window_stop_batch (FrWindow *window)
void fr_window_resume_batch (FrWindow *window)
gboolean fr_window_is_batch_mode (FrWindow *window)
void fr_window_set_batch__extract (FrWindow *window, const char *filename, const char *dest_dir)
void fr_window_set_batch__extract_here (FrWindow *window, const char *filename)
void fr_window_set_batch__add (FrWindow *window, const char *archive, GList *file_list)
void fr_window_destroy_with_error_dialog (FrWindow *window)
gboolean fr_window_file_list_drag_data_get (FrWindow *window, GdkDragContext *context, GtkSelectionData *selection_data, GList *path_list)
void fr_window_update_dialog_closed (FrWindow *window)
void fr_window_set_close_dialog (FrWindow *window, gboolean state)
Macro Definition Documentation
FR_IS_WINDOW
#define FR_IS_WINDOW (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), FR_TYPE_WINDOW))
Definition at line 75 of file fr-window.h.
FR_IS_WINDOW_CLASS
#define FR_IS_WINDOW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), FR_TYPE_WINDOW))
Definition at line 76 of file fr-window.h.
FR_TYPE_WINDOW
#define FR_TYPE_WINDOW (fr_window_get_type ())
Definition at line 72 of file fr-window.h.
Referenced by fr_window_new().
FR_WINDOW
#define FR_WINDOW (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), FR_TYPE_WINDOW, FrWindow))
Definition at line 73 of file fr-window.h.
FR_WINDOW_CLASS
#define FR_WINDOW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), FR_WINDOW_TYPE, FrWindowClass))
Definition at line 74 of file fr-window.h.
FR_WINDOW_GET_CLASS
#define FR_WINDOW_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS((obj), FR_TYPE_WINDOW, FrWindowClass))
Definition at line 77 of file fr-window.h.
Typedef Documentation
FrWindow
typedef struct _FrWindow FrWindow
Definition at line 79 of file fr-window.h.
FrWindowClass
typedef struct _FrWindowClass FrWindowClass
Definition at line 80 of file fr-window.h.
FrWindowPrivateData
typedef struct _FrWindowPrivateData FrWindowPrivateData
Definition at line 81 of file fr-window.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COLUMN_FILE_DATA
COLUMN_ICON
COLUMN_NAME
COLUMN_EMBLEM
COLUMN_SIZE
COLUMN_TYPE
COLUMN_TIME
COLUMN_PATH
NUMBER_OF_COLUMNS
Definition at line 31 of file fr-window.h.
anonymous enum
anonymous enum
Enumerator
TREE_COLUMN_PATH
TREE_COLUMN_ICON
TREE_COLUMN_NAME
TREE_COLUMN_WEIGHT
TREE_NUMBER_OF_COLUMNS
Definition at line 43 of file fr-window.h.
FrBatchActionType
enum FrBatchActionType
Enumerator
FR_BATCH_ACTION_NONE
FR_BATCH_ACTION_LOAD
FR_BATCH_ACTION_OPEN
FR_BATCH_ACTION_ADD
FR_BATCH_ACTION_DELETE
FR_BATCH_ACTION_EXTRACT
FR_BATCH_ACTION_EXTRACT_HERE
FR_BATCH_ACTION_EXTRACT_INTERACT
FR_BATCH_ACTION_RENAME
FR_BATCH_ACTION_PASTE
FR_BATCH_ACTION_OPEN_FILES
FR_BATCH_ACTION_SAVE_AS
FR_BATCH_ACTION_TEST
FR_BATCH_ACTION_CLOSE
FR_BATCH_ACTION_QUIT
FR_BATCH_ACTIONS
Definition at line 51 of file fr-window.h.
Function Documentation
fr_window_append_batch_action()
void fr_window_append_batch_action (FrWindow * window, FrBatchActionType action, void * data, GFreeFunc free_func)
Definition at line 8715 of file fr-window.c.
References action, data, and NULL.
Referenced by fr_window_set_batch__add(), fr_window_set_batch__extract(), and fr_window_set_batch__extract_here().
fr_window_archive_add_directory()
void fr_window_archive_add_directory (FrWindow * window, const char * directory, const char * base_dir, const char * dest_dir, gboolean update)
Definition at line 6235 of file fr-window.c.
References fr_archive_add_directory(), fr_window_get_current_location(), and NULL.
fr_window_archive_add_dropped_items()
void fr_window_archive_add_dropped_items (FrWindow * window, GList * item_list, gboolean update)
Definition at line 6271 of file fr-window.c.
References fr_archive_add_dropped_items(), and fr_window_get_current_location().
fr_window_archive_add_files()
void fr_window_archive_add_files (FrWindow * window, GList * file_list, gboolean update)
Definition at line 6163 of file fr-window.c.
References file_list, fr_archive_add_files(), fr_window_get_current_location(), and NULL.
fr_window_archive_add_items()
void fr_window_archive_add_items (FrWindow * window, GList * dir_list, const char * base_dir, const char * dest_dir, gboolean update)
Definition at line 6253 of file fr-window.c.
References fr_archive_add_items(), fr_window_get_current_location(), and NULL.
fr_window_archive_add_with_wildcard()
void fr_window_archive_add_with_wildcard (FrWindow * window, const char * include_files, const char * exclude_files, const char * exclude_folders, const char * base_dir, const char * dest_dir, gboolean update, gboolean follow_links)
Definition at line 6211 of file fr-window.c.
References fr_archive_add_with_wildcard(), fr_window_get_current_location(), and NULL.
fr_window_archive_close()
void fr_window_archive_close (FrWindow * window)
Definition at line 5964 of file fr-window.c.
References FALSE, fr_window_set_password(), fr_window_set_volume_size(), and NULL.
Referenced by fr_window_archive_open(), and fr_window_stop_batch().
fr_window_archive_extract()
void fr_window_archive_extract (FrWindow * window, GList * file_list, const char * extract_to_dir, const char * sub_dir, const char * base_dir, gboolean skip_older, FrOverwrite overwrite, gboolean junk_paths, gboolean ask_to_open_destination)
Definition at line 6681 of file fr-window.c.
References _, _gtk_error_dialog_new(), _gtk_message_dialog_new(), dlg_ask_password(), ensure_dir_exists(), error, FALSE, file_list, ForceDirectoryCreation, FR_BATCH_ACTION_EXTRACT_INTERACT, FR_OVERWRITE_ASK, FR_OVERWRITE_YES, fr_window_set_current_batch_action(), fr_window_stop_batch(), NULL, TRUE, and uri_is_dir().
fr_window_archive_extract_here()
void fr_window_archive_extract_here (FrWindow * window, gboolean skip_older, FrOverwrite overwrite, gboolean junk_paths)
Definition at line 6458 of file fr-window.c.
References dlg_ask_password(), FALSE, fr_archive_extract_here(), FR_BATCH_ACTION_EXTRACT_INTERACT, fr_process_clear(), fr_process_start(), fr_window_set_current_batch_action(), NULL, and TRUE.
fr_window_archive_is_present()
gboolean fr_window_archive_is_present (FrWindow * window)
Definition at line 6010 of file fr-window.c.
References FALSE, and NULL.
Referenced by dlg_prop().
fr_window_archive_new()
gboolean fr_window_archive_new (FrWindow * window, const char * uri)
Definition at line 5905 of file fr-window.c.
References _, FALSE, FR_ACTION_CREATING_NEW_ARCHIVE, fr_archive_action_completed(), fr_archive_create(), FR_PROC_ERROR_GENERIC, FR_PROC_ERROR_NONE, NULL, and TRUE.
fr_window_archive_open()
FrWindow * fr_window_archive_open (FrWindow * window, const char * uri, GtkWindow * parent)
Definition at line 5935 of file fr-window.c.
References FALSE, fr_archive_load(), FR_BATCH_ACTION_LOAD, fr_window_archive_close(), fr_window_new(), fr_window_set_current_batch_action(), NULL, _FrWindow::priv, and TRUE.
fr_window_archive_reload()
void fr_window_archive_reload (FrWindow * window)
Definition at line 6148 of file fr-window.c.
References fr_archive_reload(), and NULL.
Referenced by activate_action_reload().
fr_window_archive_remove()
void fr_window_archive_remove (FrWindow * window, GList * file_list)
Definition at line 6293 of file fr-window.c.
References file_list, fr_archive_remove(), FR_BATCH_ACTION_DELETE, fr_process_clear(), fr_process_start(), fr_window_set_current_batch_action(), and NULL.
fr_window_archive_save_as()
void fr_window_archive_save_as (FrWindow * window, const char * filename, const char * password, gboolean encrypt_header, guint volume_size)
Definition at line 6054 of file fr-window.c.
References _, _gtk_error_dialog_new(), FALSE, fr_archive_create(), fr_archive_extract_to_local(), fr_archive_new(), FR_BATCH_ACTION_SAVE_AS, fr_process_clear(), fr_process_start(), fr_window_set_current_batch_action(), g_uri_display_basename(), get_temp_work_dir(), message(), NULL, and TRUE.
fr_window_archive_test()
void fr_window_archive_test (FrWindow * window)
Definition at line 6819 of file fr-window.c.
References fr_archive_test(), FR_BATCH_ACTION_TEST, fr_window_set_current_batch_action(), and NULL.
Referenced by activate_action_test_archive().
fr_window_close()
void fr_window_close (FrWindow * window)
Definition at line 658 of file fr-window.c.
References PREF_LISTING_NAME_COLUMN_WIDTH, PREF_UI_SIDEBAR_WIDTH, PREF_UI_WINDOW_HEIGHT, PREF_UI_WINDOW_WIDTH, and TRUE.
Referenced by activate_action_close().
fr_window_copy_selection()
void fr_window_copy_selection (FrWindow * window, gboolean from_sidebar)
Definition at line 7739 of file fr-window.c.
References FR_CLIPBOARD_OP_COPY.
Referenced by activate_action_copy(), activate_popup_copy(), and activate_popup_copy_folder_from_sidebar().
fr_window_current_folder_activated()
void fr_window_current_folder_activated (FrWindow * window, gboolean from_sidebar)
Definition at line 3618 of file fr-window.c.
References FALSE, file_data_free(), file_data_is_dir(), fr_window_get_current_location(), fr_window_go_to_location(), FileData::list_name, and NULL.
Referenced by activate_popup_open_folder(), and activate_popup_open_folder_from_sidebar().
fr_window_cut_selection()
void fr_window_cut_selection (FrWindow * window, gboolean from_sidebar)
Definition at line 7746 of file fr-window.c.
References FR_CLIPBOARD_OP_CUT.
Referenced by activate_action_cut(), activate_popup_cut(), and activate_popup_cut_folder_from_sidebar().
fr_window_destroy_with_error_dialog()
void fr_window_destroy_with_error_dialog (FrWindow * window)
Definition at line 2896 of file fr-window.c.
References TRUE.
fr_window_file_list_drag_data_get()
gboolean fr_window_file_list_drag_data_get (FrWindow * window, GdkDragContext * context, GtkSelectionData * selection_data, GList * path_list)
Definition at line 4373 of file fr-window.c.
References _, check_permissions(), data, debug, DEBUG_INFO, FALSE, FR_CLIPBOARD_OP_COPY, FR_ERROR, fr_window_get_current_location(), fr_window_get_file_list_from_path_list(), fr_window_get_file_list_selection(), NULL, remove_level_from_path(), TRUE, and XFR_ATOM.
fr_window_find()
void fr_window_find (FrWindow * window)
Definition at line 7025 of file fr-window.c.
References TRUE.
Referenced by activate_action_find().
fr_window_get_add_default_dir()
const char * fr_window_get_add_default_dir (FrWindow * window)
Definition at line 8421 of file fr-window.c.
References get_home_uri(), and NULL.
Referenced by add_files_cb().
fr_window_get_archive_uri()
const char * fr_window_get_archive_uri (FrWindow * window)
Definition at line 5991 of file fr-window.c.
References NULL.
Referenced by activate_action_save_as(), and dlg_prop().
fr_window_get_compression()
FrCompression fr_window_get_compression (FrWindow * window)
Definition at line 6891 of file fr-window.c.
fr_window_get_current_location()
const char * fr_window_get_current_location (FrWindow * window)
Definition at line 6944 of file fr-window.c.
References NULL.
Referenced by fr_window_archive_add_directory(), fr_window_archive_add_dropped_items(), fr_window_archive_add_files(), fr_window_archive_add_items(), fr_window_archive_add_with_wildcard(), fr_window_current_folder_activated(), fr_window_file_list_drag_data_get(), fr_window_get_selection(), fr_window_go_up_one_level(), fr_window_paste_selection(), and fr_window_rename_selection().
fr_window_get_encrypt_header()
gboolean fr_window_get_encrypt_header (FrWindow * window)
Definition at line 6876 of file fr-window.c.
Referenced by dlg_password().
fr_window_get_extract_default_dir()
const char * fr_window_get_extract_default_dir (FrWindow * window)
Definition at line 8450 of file fr-window.c.
References get_home_uri(), and NULL.
fr_window_get_file_list_from_path_list()
GList * fr_window_get_file_list_from_path_list (FrWindow * window, GList * path_list, gboolean * has_dirs)
Definition at line 3399 of file fr-window.c.
References COLUMN_FILE_DATA, FALSE, file_data_is_dir(), has_dirs, NULL, FileData::original_path, and TRUE.
Referenced by fr_window_file_list_drag_data_get().
fr_window_get_file_list_pattern()
GList * fr_window_get_file_list_pattern (FrWindow * window, const char * pattern)
Definition at line 3457 of file fr-window.c.
References free_regexps(), match_regexps(), FileData::name, NULL, FileData::original_path, and search_util_get_regexps().
fr_window_get_file_list_selection()
GList * fr_window_get_file_list_selection (FrWindow * window, gboolean recursive, gboolean * has_dirs)
Definition at line 3321 of file fr-window.c.
References FALSE, file_data_is_dir(), has_dirs, NULL, FileData::original_path, and TRUE.
Referenced by activate_popup_open(), dlg_delete(), fr_window_file_list_drag_data_get(), fr_window_get_selection(), and open_with_cb().
fr_window_get_folder_tree_selection()
GList * fr_window_get_folder_tree_selection (FrWindow * window, gboolean recursive, gboolean * has_dirs)
Definition at line 3362 of file fr-window.c.
References FALSE, has_dirs, NULL, and TRUE.
Referenced by dlg_delete_from_sidebar(), and fr_window_get_selection().
fr_window_get_list_store()
GtkTreeModel * fr_window_get_list_store (FrWindow * window)
Definition at line 7019 of file fr-window.c.
fr_window_get_n_selected_files()
int fr_window_get_n_selected_files (FrWindow * window)
Definition at line 3505 of file fr-window.c.
fr_window_get_open_default_dir()
const char * fr_window_get_open_default_dir (FrWindow * window)
Definition at line 8400 of file fr-window.c.
References get_home_uri(), and NULL.
Referenced by activate_action_open().
fr_window_get_password()
const char * fr_window_get_password (FrWindow * window)
Definition at line 6859 of file fr-window.c.
References NULL.
Referenced by dlg_password().
fr_window_get_paste_archive_uri()
const char * fr_window_get_paste_archive_uri (FrWindow * window)
Definition at line 5999 of file fr-window.c.
References NULL.
fr_window_get_selection()
GList * fr_window_get_selection (FrWindow * window, gboolean from_sidebar, char ** return_base_dir)
Definition at line 7673 of file fr-window.c.
References fr_window_get_current_location(), fr_window_get_file_list_selection(), fr_window_get_folder_tree_selection(), NULL, remove_level_from_path(), and TRUE.
Referenced by dlg_extract(), and dlg_extract_folder_from_sidebar().
fr_window_get_type()
GType fr_window_get_type (void)
Definition at line 786 of file fr-window.c.
References NULL.
fr_window_get_volume_size()
guint fr_window_get_volume_size (FrWindow * window)
Definition at line 6906 of file fr-window.c.
fr_window_go_back()
void fr_window_go_back (FrWindow * window)
Definition at line 6967 of file fr-window.c.
References FALSE, fr_window_go_to_location(), and NULL.
Referenced by activate_action_go_back().
fr_window_go_forward()
void fr_window_go_forward (FrWindow * window)
Definition at line 6983 of file fr-window.c.
References FALSE, fr_window_go_to_location(), and NULL.
Referenced by activate_action_go_forward().
fr_window_go_to_location()
void fr_window_go_to_location (FrWindow * window, const char * path, gboolean force_update)
Definition at line 6912 of file fr-window.c.
References NULL, and TRUE.
Referenced by activate_action_go_home(), fr_window_current_folder_activated(), fr_window_go_back(), fr_window_go_forward(), and fr_window_go_up_one_level().
fr_window_go_up_one_level()
void fr_window_go_up_one_level (FrWindow * window)
Definition at line 6955 of file fr-window.c.
References FALSE, fr_window_get_current_location(), fr_window_go_to_location(), and NULL.
Referenced by activate_action_go_up().
fr_window_is_batch_mode()
gboolean fr_window_is_batch_mode (FrWindow * window)
Definition at line 8807 of file fr-window.c.
fr_window_new()
GtkWidget * fr_window_new (void)
Definition at line 5885 of file fr-window.c.
References FR_TYPE_WINDOW, and NULL.
Referenced by fr_window_archive_open().
fr_window_new_batch()
void fr_window_new_batch (FrWindow * window, const char * title)
Definition at line 8813 of file fr-window.c.
References TRUE.
fr_window_open_files()
void fr_window_open_files (FrWindow * window, GList * file_list, gboolean ask_application)
Definition at line 8344 of file fr-window.c.
References FALSE, file_list, fr_archive_extract_to_local(), FR_BATCH_ACTION_OPEN_FILES, fr_process_clear(), fr_process_start(), fr_window_set_current_batch_action(), NULL, CommandData::temp_dir, and TRUE.
Referenced by activate_popup_open(), and open_with_cb().
fr_window_open_files_with_application()
void fr_window_open_files_with_application (FrWindow * window, GList * file_list, GAppInfo * app)
Definition at line 8046 of file fr-window.c.
References _, _gtk_error_dialog_run(), error, file_list, and NULL.
Referenced by fr_window_open_files_with_command().
fr_window_open_files_with_command()
void fr_window_open_files_with_command (FrWindow * window, GList * file_list, char * command)
Definition at line 8025 of file fr-window.c.
References _, _gtk_error_dialog_run(), error, file_list, fr_window_open_files_with_application(), and NULL.
fr_window_paste_selection()
void fr_window_paste_selection (FrWindow * window, gboolean from_sidebar)
Definition at line 7983 of file fr-window.c.
References _, _gtk_request_dialog_run(), build_uri(), fr_window_get_current_location(), FR_WINDOW_LIST_MODE_FLAT, and NULL.
Referenced by activate_action_paste(), activate_popup_paste(), and activate_popup_paste_folder_from_sidebar().
fr_window_pop_message()
void fr_window_pop_message (FrWindow * window)
Definition at line 2761 of file fr-window.c.
References NULL.
fr_window_push_message()
void fr_window_push_message (FrWindow * window, const char * msg)
Definition at line 2749 of file fr-window.c.
fr_window_rename_selection()
void fr_window_rename_selection (FrWindow * window, gboolean from_sidebar)
Definition at line 7513 of file fr-window.c.
References _, _gtk_error_dialog_new(), _gtk_message_dialog_new(), _gtk_request_dialog_run(), FileData::dir, FALSE, file_data_free(), file_data_is_dir(), file_name_from_path(), fr_window_get_current_location(), FileData::full_path, FileData::list_name, FileData::name, NULL, FileData::original_path, remove_ending_separator(), remove_level_from_path(), and TRUE.
Referenced by activate_action_rename(), activate_popup_rename(), and activate_popup_rename_folder_from_sidebar().
fr_window_reset_current_batch_action()
void fr_window_reset_current_batch_action (FrWindow * window)
Definition at line 8682 of file fr-window.c.
References FR_BATCH_ACTION_NONE, and NULL.
Referenced by fr_window_set_current_batch_action().
fr_window_restart_current_batch_action()
void fr_window_restart_current_batch_action (FrWindow * window)
Definition at line 8709 of file fr-window.c.
fr_window_resume_batch()
void fr_window_resume_batch (FrWindow * window)
Definition at line 8801 of file fr-window.c.
fr_window_select_all()
void fr_window_select_all (FrWindow * window)
Definition at line 7033 of file fr-window.c.
Referenced by activate_action_select_all().
fr_window_set_add_default_dir()
void fr_window_set_add_default_dir (FrWindow * window, const char * default_dir)
Definition at line 8409 of file fr-window.c.
References NULL.
Referenced by fr_window_set_default_dir().
fr_window_set_batch__add()
void fr_window_set_batch__add (FrWindow * window, const char * archive, GList * file_list)
Definition at line 8872 of file fr-window.c.
References file_list, FR_BATCH_ACTION_ADD, FR_BATCH_ACTION_CLOSE, FR_BATCH_ACTION_LOAD, FR_BATCH_ACTION_OPEN, fr_window_append_batch_action(), NULL, and uri_is_file().
fr_window_set_batch__extract()
void fr_window_set_batch__extract (FrWindow * window, const char * filename, const char * dest_dir)
Definition at line 8844 of file fr-window.c.
References FR_BATCH_ACTION_CLOSE, FR_BATCH_ACTION_EXTRACT_INTERACT, FR_BATCH_ACTION_LOAD, fr_window_append_batch_action(), and NULL.
fr_window_set_batch__extract_here()
void fr_window_set_batch__extract_here (FrWindow * window, const char * filename)
Definition at line 8823 of file fr-window.c.
References FR_BATCH_ACTION_CLOSE, FR_BATCH_ACTION_EXTRACT_HERE, FR_BATCH_ACTION_LOAD, fr_window_append_batch_action(), and NULL.
fr_window_set_close_dialog()
void fr_window_set_close_dialog (FrWindow * window, gboolean state)
Definition at line 8899 of file fr-window.c.
References NULL.
fr_window_set_compression()
void fr_window_set_compression (FrWindow * window, FrCompression compression)
Definition at line 6882 of file fr-window.c.
References NULL.
fr_window_set_current_batch_action()
void fr_window_set_current_batch_action (FrWindow * window, FrBatchActionType action, void * data, GFreeFunc free_func)
Definition at line 8694 of file fr-window.c.
References action, data, and fr_window_reset_current_batch_action().
Referenced by fr_window_archive_extract(), fr_window_archive_extract_here(), fr_window_archive_open(), fr_window_archive_remove(), fr_window_archive_save_as(), fr_window_archive_test(), and fr_window_open_files().
fr_window_set_default_dir()
void fr_window_set_default_dir (FrWindow * window, const char * default_dir, gboolean freeze)
Definition at line 8459 of file fr-window.c.
References FALSE, fr_window_set_add_default_dir(), fr_window_set_extract_default_dir(), fr_window_set_open_default_dir(), and NULL.
fr_window_set_encrypt_header()
void fr_window_set_encrypt_header (FrWindow * window, gboolean encrypt_header)
Definition at line 6867 of file fr-window.c.
References NULL.
fr_window_set_extract_default_dir()
void fr_window_set_extract_default_dir (FrWindow * window, const char * default_dir, gboolean freeze)
Definition at line 8430 of file fr-window.c.
References NULL.
Referenced by fr_window_set_default_dir().
fr_window_set_folders_visibility()
void fr_window_set_folders_visibility (FrWindow * window, gboolean value)
Definition at line 8521 of file fr-window.c.
References NULL.
fr_window_set_list_mode()
void fr_window_set_list_mode (FrWindow * window, FrWindowListMode list_mode)
Definition at line 6999 of file fr-window.c.
References FR_WINDOW_LIST_MODE_FLAT, NULL, PREF_LISTING_LIST_MODE, PREF_LISTING_SHOW_PATH, and TRUE.
fr_window_set_open_default_dir()
void fr_window_set_open_default_dir (FrWindow * window, const char * default_dir)
Definition at line 8388 of file fr-window.c.
References NULL.
Referenced by fr_window_set_default_dir().
fr_window_set_password()
void fr_window_set_password (FrWindow * window, const char * password)
Definition at line 6829 of file fr-window.c.
References NULL.
Referenced by fr_window_archive_close().
fr_window_set_password_for_paste()
void fr_window_set_password_for_paste (FrWindow * window, const char * password)
Definition at line 6844 of file fr-window.c.
References NULL.
fr_window_set_statusbar_visibility()
void fr_window_set_statusbar_visibility (FrWindow * window, gboolean value)
Definition at line 8507 of file fr-window.c.
References NULL.
fr_window_set_toolbar_visibility()
void fr_window_set_toolbar_visibility (FrWindow * window, gboolean value)
Definition at line 8493 of file fr-window.c.
References NULL.
fr_window_set_volume_size()
void fr_window_set_volume_size (FrWindow * window, guint volume_size)
Definition at line 6897 of file fr-window.c.
References NULL.
Referenced by fr_window_archive_close().
fr_window_start_activity_mode()
void fr_window_start_activity_mode (FrWindow * window)
Definition at line 7073 of file fr-window.c.
References ACTIVITY_DELAY, and NULL.
fr_window_start_batch()
void fr_window_start_batch (FrWindow * window)
Definition at line 8756 of file fr-window.c.
References NULL, and TRUE.
fr_window_stop()
void fr_window_stop (FrWindow * window)
Definition at line 7045 of file fr-window.c.
References fr_archive_stop(), and TRUE.
Referenced by activate_action_stop().
fr_window_stop_activity_mode()
void fr_window_stop_activity_mode (FrWindow * window)
Definition at line 7087 of file fr-window.c.
References NULL.
fr_window_stop_batch()
void fr_window_stop_batch (FrWindow * window)
Definition at line 8778 of file fr-window.c.
References FALSE, and fr_window_archive_close().
Referenced by fr_window_archive_extract().
fr_window_unselect_all()
void fr_window_unselect_all (FrWindow * window)
Definition at line 7039 of file fr-window.c.
Referenced by activate_action_deselect_all().
fr_window_update_columns_visibility()
void fr_window_update_columns_visibility (FrWindow * window)
Definition at line 8474 of file fr-window.c.
References PREF_LISTING_SHOW_PATH, PREF_LISTING_SHOW_SIZE, PREF_LISTING_SHOW_TIME, and PREF_LISTING_SHOW_TYPE.
fr_window_update_dialog_closed()
void fr_window_update_dialog_closed (FrWindow * window)
Definition at line 8130 of file fr-window.c.
References NULL.
fr_window_update_files()
gboolean fr_window_update_files (FrWindow * window, GList * file_list)
Definition at line 8136 of file fr-window.c.
References FALSE, file_list, fr_archive_add(), fr_process_clear(), fr_process_start(), NULL, OpenFile::path, OpenFile::temp_dir, and TRUE.
fr_window_update_history_list()
void fr_window_update_history_list (FrWindow * window)
References action, data, and file_list.
fr_window_update_list_order()
void fr_window_update_list_order (FrWindow * window)
Definition at line 1888 of file fr-window.c.
fr_window_use_progress_dialog()
void fr_window_use_progress_dialog (FrWindow * window, gboolean value)
Definition at line 8533 of file fr-window.c.
fr_window_view_last_output()
void fr_window_view_last_output (FrWindow * window, const char * title)
Definition at line 7148 of file fr-window.c.
References _, FALSE, LAST_OUTPUT_DIALOG_NAME, NULL, pref_util_restore_window_geometry(), and TRUE.
Referenced by activate_action_last_output().