MATE Desktop Environment: gdict-source-chooser.h File Reference
gdict-source-chooser.h File Reference
#include <gtk/gtk.h>
#include "gdict-source-loader.h"
Classes
struct _GdictSourceChooser
struct _GdictSourceChooserClass
Macros
#define GDICT_TYPE_SOURCE_CHOOSER (gdict_source_chooser_get_type ())
#define GDICT_SOURCE_CHOOSER(obj)
#define GDICT_IS_SOURCE_CHOOSER(obj)
#define GDICT_SOURCE_CHOOSER_CLASS(klass)
#define GDICT_IS_SOURCE_CHOOSER_CLASS(klass)
#define GDICT_SOURCE_CHOOSER_GET_CLASS(obj)
Typedefs
typedef struct _GdictSourceChooser GdictSourceChooser
typedef struct _GdictSourceChooserPrivate GdictSourceChooserPrivate
typedef struct _GdictSourceChooserClass GdictSourceChooserClass
Functions
GType gdict_source_chooser_get_type (void)
GtkWidget * gdict_source_chooser_new (void)
GtkWidget * gdict_source_chooser_new_with_loader (GdictSourceLoader *loader)
void gdict_source_chooser_set_loader (GdictSourceChooser *chooser, GdictSourceLoader *loader)
GdictSourceLoader * gdict_source_chooser_get_loader (GdictSourceChooser *chooser)
gboolean gdict_source_chooser_select_source (GdictSourceChooser *chooser, const gchar *source_name)
gboolean gdict_source_chooser_unselect_source (GdictSourceChooser *chooser, const gchar *source_name)
gboolean gdict_source_chooser_set_current_source (GdictSourceChooser *chooser, const gchar *source_name)
gchar * gdict_source_chooser_get_current_source (GdictSourceChooser *chooser) G_GNUC_MALLOC
gchar ** gdict_source_chooser_get_sources (GdictSourceChooser *chooser, gsize *length) G_GNUC_MALLOC
gint gdict_source_chooser_count_sources (GdictSourceChooser *chooser)
gboolean gdict_source_chooser_has_source (GdictSourceChooser *chooser, const gchar *source_name)
void gdict_source_chooser_refresh (GdictSourceChooser *chooser)
GtkWidget * gdict_source_chooser_add_button (GdictSourceChooser *chooser, const gchar *button_text)
Macro Definition Documentation
GDICT_IS_SOURCE_CHOOSER
#define GDICT_IS_SOURCE_CHOOSER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), GDICT_TYPE_SOURCE_CHOOSER))
Definition at line 30 of file gdict-source-chooser.h.
Referenced by gdict_source_chooser_add_button(), gdict_source_chooser_count_sources(), gdict_source_chooser_get_current_source(), gdict_source_chooser_get_loader(), gdict_source_chooser_get_sources(), gdict_source_chooser_has_source(), gdict_source_chooser_refresh(), gdict_source_chooser_select_source(), gdict_source_chooser_set_current_source(), gdict_source_chooser_set_loader(), and gdict_source_chooser_unselect_source().
GDICT_IS_SOURCE_CHOOSER_CLASS
#define GDICT_IS_SOURCE_CHOOSER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), GDICT_TYPE_SOURCE_CHOOSER))
Definition at line 32 of file gdict-source-chooser.h.
GDICT_SOURCE_CHOOSER
#define GDICT_SOURCE_CHOOSER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), GDICT_TYPE_SOURCE_CHOOSER, GdictSourceChooser))
Definition at line 29 of file gdict-source-chooser.h.
GDICT_SOURCE_CHOOSER_CLASS
#define GDICT_SOURCE_CHOOSER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), GDICT_TYPE_SOURCE_CHOOSER, GdictSourceChooserClass))
Definition at line 31 of file gdict-source-chooser.h.
GDICT_SOURCE_CHOOSER_GET_CLASS
#define GDICT_SOURCE_CHOOSER_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), GDICT_TYPE_SOURCE_CHOOSER, GdictSourceChooserClass))
Definition at line 33 of file gdict-source-chooser.h.
GDICT_TYPE_SOURCE_CHOOSER
#define GDICT_TYPE_SOURCE_CHOOSER (gdict_source_chooser_get_type ())
Definition at line 28 of file gdict-source-chooser.h.
Referenced by gdict_source_chooser_new(), and gdict_source_chooser_new_with_loader().
Typedef Documentation
GdictSourceChooser
typedef struct _GdictSourceChooser GdictSourceChooser
Definition at line 35 of file gdict-source-chooser.h.
GdictSourceChooserClass
typedef struct _GdictSourceChooserClass GdictSourceChooserClass
Definition at line 37 of file gdict-source-chooser.h.
GdictSourceChooserPrivate
typedef struct _GdictSourceChooserPrivate GdictSourceChooserPrivate
Definition at line 36 of file gdict-source-chooser.h.
Function Documentation
gdict_source_chooser_add_button()
GtkWidget * gdict_source_chooser_add_button (GdictSourceChooser * chooser, const gchar * button_text)
gdict_source_chooser_add_button: @chooser: a GdictSourceChooser @button_text: text of the button
Adds a #GtkButton with @button_text to the button area on the bottom of @chooser. The @button_text can also be a stock ID.
Return value: the newly packed button.
Since: 0.12
Definition at line 876 of file gdict-source-chooser.c.
References FALSE, GDICT_IS_SOURCE_CHOOSER, NULL, _GdictSourceChooser::priv, and TRUE.
gdict_source_chooser_count_sources()
gint gdict_source_chooser_count_sources (GdictSourceChooser * chooser)
gdict_source_chooser_count_sources: @chooser: a GdictSourceChooser
Retrieve the number of available dictionary sources.
Return value: the number of available sources, or -1 if no GdictSourceLoader has been set
Since: 0.12
Definition at line 771 of file gdict-source-chooser.c.
References GDICT_IS_SOURCE_CHOOSER, and _GdictSourceChooser::priv.
gdict_source_chooser_get_current_source()
gchar * gdict_source_chooser_get_current_source (GdictSourceChooser * chooser)
gdict_source_chooser_get_current_source: @chooser: a GdictSourceChooser
Retrieves the currently selected source.
Return value: a newly allocated string containing the name of the currently selected source. Use g_free() when done using it
Since: 0.12
Definition at line 700 of file gdict-source-chooser.c.
References GDICT_IS_SOURCE_CHOOSER, NULL, _GdictSourceChooser::priv, and SOURCE_NAME.
gdict_source_chooser_get_loader()
GdictSourceLoader * gdict_source_chooser_get_loader (GdictSourceChooser * chooser)
gdict_source_chooser_get_loader: @chooser: a GdictSourceChooser
Retrieves the GdictSourceLoader used by @chooser.
Return value: a GdictSourceLoader or NULL is none is set
Since: 0.12
Definition at line 476 of file gdict-source-chooser.c.
References GDICT_IS_SOURCE_CHOOSER, NULL, and _GdictSourceChooser::priv.
gdict_source_chooser_get_sources()
gchar ** gdict_source_chooser_get_sources (GdictSourceChooser * chooser, gsize * length)
gdict_source_chooser_get_sources: @chooser: a #GdictSouceChooser @length: return location for the length of the returned vector
Retrieves the names of the available dictionary sources.
Return value: a newly allocated, NULL terminated string vector containing the names of the available sources. Use g_strfreev() when done using it.
Since: 0.12
Definition at line 738 of file gdict-source-chooser.c.
References GDICT_IS_SOURCE_CHOOSER, gdict_source_loader_get_names(), NULL, and _GdictSourceChooser::priv.
gdict_source_chooser_get_type()
GType gdict_source_chooser_get_type (void)
gdict_source_chooser_has_source()
gboolean gdict_source_chooser_has_source (GdictSourceChooser * chooser, const gchar * source_name)
gdict_source_chooser_has_source: @chooser: a GdictSourceChooser @source_name: the name of a dictionary source
Checks whether @chooser has a dictionary source named @source_name.
Return value: TRUE if the dictionary source was found
Since: 0.12
Definition at line 790 of file gdict-source-chooser.c.
References FALSE, GDICT_IS_SOURCE_CHOOSER, gdict_source_loader_has_source(), NULL, and _GdictSourceChooser::priv.
gdict_source_chooser_new()
GtkWidget * gdict_source_chooser_new (void)
gdict_source_chooser_new:
Creates a new GdictSourceChooser widget. This widget can be used to display the list of available dictionary sources.
Return value: the newly created GdictSourceChooser widget.
Since: 0.12
Definition at line 404 of file gdict-source-chooser.c.
References GDICT_TYPE_SOURCE_CHOOSER, and NULL.
gdict_source_chooser_new_with_loader()
GtkWidget * gdict_source_chooser_new_with_loader (GdictSourceLoader * loader)
gdict_source_chooser_new_with_loader: @loader: a GdictSourceLoader
Creates a new GdictSourceChooser widget and sets @loader as the GdictSourceLoader object to be used to retrieve the list of available dictionary sources.
Return value: the newly created GdictSourceChooser widget.
Since: 0.12
Definition at line 422 of file gdict-source-chooser.c.
References GDICT_IS_SOURCE_LOADER, GDICT_TYPE_SOURCE_CHOOSER, and NULL.
gdict_source_chooser_refresh()
void gdict_source_chooser_refresh (GdictSourceChooser * chooser)
gdict_source_chooser_refresh: @chooser: a GdictSourceChooser
Forces a refresh on the contents of the source chooser widget
Since: 0.12
Definition at line 815 of file gdict-source-chooser.c.
References GDICT_IS_SOURCE_CHOOSER, gdict_source_get_description(), gdict_source_get_name(), gdict_source_get_transport(), gdict_source_loader_get_sources(), name, NULL, _GdictSourceChooser::priv, SOURCE_CURRENT, SOURCE_DESCRIPTION, SOURCE_NAME, and SOURCE_TRANSPORT.
Referenced by gdict_source_chooser_set_loader().
gdict_source_chooser_select_source()
gboolean gdict_source_chooser_select_source (GdictSourceChooser * chooser, const gchar * source_name)
gdict_source_chooser_select_source: @chooser: a GdictSourceChooser @source_name: the name of a dictionary source
Selects the dictionary source named @source_name inside @chooser. The selection is moved but the row containing the dictionary source is not activated.
Return value: TRUE if the source was found and selected
Since: 0.12
Definition at line 563 of file gdict-source-chooser.c.
References data, FALSE, GDICT_IS_SOURCE_CHOOSER, NULL, _GdictSourceChooser::priv, and TRUE.
gdict_source_chooser_set_current_source()
gboolean gdict_source_chooser_set_current_source (GdictSourceChooser * chooser, const gchar * source_name)
gdict_source_chooser_set_current_source: @chooser: a GdictSourceChooser @source_name: the name of a dictionary source
Sets the current dictionary source named @source_name. The row of the source, if found, will be selected and activated.
Return value: TRUE if the source was found
Since: 0.12
Definition at line 646 of file gdict-source-chooser.c.
References data, FALSE, GDICT_IS_SOURCE_CHOOSER, GDICT_NOTE, NULL, _GdictSourceChooser::priv, and TRUE.
gdict_source_chooser_set_loader()
void gdict_source_chooser_set_loader (GdictSourceChooser * chooser, GdictSourceLoader * loader)
gdict_source_chooser_set_loader: @chooser: a GdictSourceChooser @loader: a GdictSourceLoader or NULL to unset it
Sets the GdictSourceLoader to be used by the source chooser widget.
Since: 0.12
Definition at line 440 of file gdict-source-chooser.c.
References GDICT_IS_SOURCE_CHOOSER, GDICT_IS_SOURCE_LOADER, gdict_source_chooser_refresh(), NULL, and _GdictSourceChooser::priv.
gdict_source_chooser_unselect_source()
gboolean gdict_source_chooser_unselect_source (GdictSourceChooser * chooser, const gchar * source_name)
gdict_source_chooser_unselect_source: @chooser: a GdictSourceChooser @source_name: the name of a dictionary source
Unselects @source_name inside @chooser.
Return value: TRUE if the source was found and unselected
Since: 0.12
Definition at line 604 of file gdict-source-chooser.c.
References data, FALSE, GDICT_IS_SOURCE_CHOOSER, NULL, and _GdictSourceChooser::priv.