MATE Desktop Environment: gdict-source-loader.c File Reference
gdict-source-loader.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib/gstdio.h>
#include <glib/gi18n-lib.h>
#include "gdict-source-loader.h"
#include "gdict-utils.h"
#include "gdict-enum-types.h"
#include "gdict-marshal.h"
#include "gdict-private.h"
Macros
#define GDICT_SOURCE_FILE_SUFFIX ".desktop"
Enumerations
enum { PROP_0 , PROP_PATHS , PROP_SOURCES }
enum { SOURCE_LOADED , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (GdictSourceLoader, gdict_source_loader, G_TYPE_OBJECT)
GdictSourceLoader * gdict_source_loader_new (void)
void gdict_source_loader_update (GdictSourceLoader *loader)
void gdict_source_loader_add_search_path (GdictSourceLoader *loader, const gchar *path)
const GSList * gdict_source_loader_get_paths (GdictSourceLoader *loader)
gchar ** gdict_source_loader_get_names (GdictSourceLoader *loader, gsize *length)
const GSList * gdict_source_loader_get_sources (GdictSourceLoader *loader)
. You can use the returned
GdictSource object to create the right GdictContext for that dictionary source.
Return value: a referenced GdictSource object. You should de-reference it using g_object_unref() when you finished using it.
Since: 1.0
GdictSource * gdict_source_loader_get_source (GdictSourceLoader *loader, const gchar *name)
from @loader. This function will
also remove the dictionary source definition file bound to it.
Return value: TRUE if the dictionary source was successfully removed
Since: 1.0
gboolean gdict_source_loader_remove_source (GdictSourceLoader *loader, const gchar *name)
gboolean gdict_source_loader_has_source (GdictSourceLoader *loader, const gchar *source_name)
Macro Definition Documentation
GDICT_SOURCE_FILE_SUFFIX
#define GDICT_SOURCE_FILE_SUFFIX ".desktop"
SECTION:gdict-source-loader @short_description: Loader object for a set of dictionary sources
GdictSourceLoader allows searching for dictionary source definition files inside a set of paths and return a GdictSource using its name.
Definition at line 49 of file gdict-source-loader.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SOURCE_LOADED
LAST_SIGNAL
Definition at line 69 of file gdict-source-loader.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_PATHS
PROP_SOURCES
Definition at line 61 of file gdict-source-loader.c.
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (GdictSourceLoader , gdict_source_loader , G_TYPE_OBJECT)
References GDICT_SOURCE_LOADER, and NULL.
gdict_source_loader_add_search_path()
void gdict_source_loader_add_search_path (GdictSourceLoader * loader, const gchar * path)
gdict_source_loader_add_search_path: @loader: a GdictSourceLoader @path: a path to be added to the search path list
Adds @path to the search paths list of @loader.
Since: 1.0
Definition at line 262 of file gdict-source-loader.c.
References GDICT_IS_SOURCE_LOADER, NULL, _GdictSourceLoader::priv, and TRUE.
Referenced by gdict_init().
gdict_source_loader_get_names()
gchar ** gdict_source_loader_get_names (GdictSourceLoader * loader, gsize * length)
gdict_source_loader_get_names: @loader: a GdictSourceLoader @length: return location for the number of source names, or NULL
Retrieves the list of dictionary source names available into the search paths of @loader.
Return value: a newly allocated, NULL terminated array of strings. You should free the returned string array with g_strfreev()
Since: 1.0
Definition at line 411 of file gdict-source-loader.c.
References GDICT_IS_SOURCE_LOADER, GDICT_SOURCE, gdict_source_get_name(), NULL, and _GdictSourceLoader::priv.
Referenced by gdict_source_chooser_get_sources().
gdict_source_loader_get_paths()
const GSList * gdict_source_loader_get_paths (GdictSourceLoader * loader)
gdict_source_loader_get_paths: @loader: a GdictSourceLoader
Gets the list of paths used by @loader to search for dictionary source files.
Return value: a list containing the paths. The returned list is owned by the GdictSourceLoader object and should never be free or modified.
Since: 1.0
Definition at line 292 of file gdict-source-loader.c.
References GDICT_IS_SOURCE_LOADER, NULL, and _GdictSourceLoader::priv.
gdict_source_loader_get_source()
GdictSource * gdict_source_loader_get_source (GdictSourceLoader * loader, const gchar * name)
Definition at line 481 of file gdict-source-loader.c.
References GDICT_IS_SOURCE_LOADER, name, NULL, and _GdictSourceLoader::priv.
Referenced by gdict_window_new().
gdict_source_loader_get_sources()
const GSList * gdict_source_loader_get_sources (GdictSourceLoader * loader)
gdict_source_loader_get_sources: @loader: a GdictSourceLoader
Retrieves the list of dictionary sources available into the search paths of @loader, in form of GdictSource objects.
Return value: a list of GdictSource objects. The returned list is owned by the GdictSourceLoader object, and should never be freed or modified.
Since: 1.0
Definition at line 456 of file gdict-source-loader.c.
References GDICT_IS_SOURCE_LOADER, NULL, and _GdictSourceLoader::priv.
Referenced by gdict_source_chooser_refresh().
gdict_source_loader_has_source()
gboolean gdict_source_loader_has_source (GdictSourceLoader * loader, const gchar * source_name)
gdict_source_loader_has_source: @loader: a GdictSourceLoader @source_name: the name of a dictionary source
Checks whether @loader has a dictionary source with name @source_name.
Return value: TRUE if the dictionary source is known
Since: 0.12
Definition at line 572 of file gdict-source-loader.c.
References FALSE, GDICT_IS_SOURCE_LOADER, NULL, and _GdictSourceLoader::priv.
Referenced by gdict_source_chooser_has_source().
gdict_source_loader_new()
GdictSourceLoader * gdict_source_loader_new (void)
gdict_source_loader_new:
Creates a new GdictSourceLoader object. This object is used to search into a list of paths for dictionary source files. See GdictSource for more informations about the format of dictionary source files.
Return value: a new GdictSourceLoader object
Since: 1.0
Definition at line 231 of file gdict-source-loader.c.
References GDICT_TYPE_SOURCE_LOADER, and NULL.
Referenced by gdict_init().
gdict_source_loader_remove_source()
gboolean gdict_source_loader_remove_source (GdictSourceLoader * loader, const gchar * name)
Definition at line 512 of file gdict-source-loader.c.
References FALSE, GDICT_IS_SOURCE_LOADER, GDICT_SOURCE, gdict_source_get_name(), name, NULL, _GdictSourceLoader::priv, and TRUE.
gdict_source_loader_update()
void gdict_source_loader_update (GdictSourceLoader * loader)
gdict_source_loader_update: @loader: a GdictSourceLoader
Queue an update of the sources inside @loader.
Since: 1.0
Definition at line 245 of file gdict-source-loader.c.
References GDICT_IS_SOURCE_LOADER, _GdictSourceLoader::priv, and TRUE.