MATE Desktop Environment: gdict-client-context.c File Reference
gdict-client-context.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <fcntl.h>
#include <errno.h>
#include <glib.h>
#include <glib/gi18n-lib.h>
#include "gdict-context-private.h"
#include "gdict-context.h"
#include "gdict-client-context.h"
#include "gdict-enum-types.h"
#include "gdict-marshal.h"
#include "gdict-debug.h"
#include "gdict-utils.h"
#include "gdict-private.h"
Macros
#define IS_VALID_CMD(cmd)
#define GDICT_DEFAULT_CLIENT "MATE Dictionary (" VERSION ")"
#define GDICT_DEFAULT_HOSTNAME "dict.org"
#define GDICT_DEFAULT_PORT 2628
#define HOSTNAME_LOOKUP_EXPIRE 300
#define CONNECTION_TIMEOUT_SEC 30
Enumerations
enum GdictCommandType {
CMD_CLIENT , CMD_SHOW_DB , CMD_SHOW_STRAT , CMD_SHOW_INFO ,
CMD_SHOW_SERVER , CMD_MATCH , CMD_DEFINE , CMD_STATUS ,
CMD_OPTION_MIME , CMD_AUTH , CMD_HELP , CMD_QUIT ,
CMD_INVALID
}
enum { S_START , S_STATUS , S_DATA , S_FINISH }
enum {
PROP_0 , PROP_HOSTNAME , PROP_PORT , PROP_STATUS ,
PROP_CLIENT_NAME
}
enum { CONNECTED , DISCONNECTED , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_CODE (GdictClientContext, gdict_client_context, G_TYPE_OBJECT, G_IMPLEMENT_INTERFACE(GDICT_TYPE_CONTEXT, gdict_client_context_iface_init))
GQuark gdict_client_context_error_quark (void)
GdictContext * gdict_client_context_new (const gchar *hostname, gint port)
void gdict_client_context_set_hostname (GdictClientContext *context, const gchar *hostname)
const gchar * gdict_client_context_get_hostname (GdictClientContext *context)
void gdict_client_context_set_port (GdictClientContext *context, gint port)
guint gdict_client_context_get_port (GdictClientContext *context)
void gdict_client_context_set_client (GdictClientContext *context, const gchar *client)
const gchar * gdict_client_context_get_client (GdictClientContext *context)
Macro Definition Documentation
CONNECTION_TIMEOUT_SEC
#define CONNECTION_TIMEOUT_SEC 30
Definition at line 139 of file gdict-client-context.c.
GDICT_DEFAULT_CLIENT
#define GDICT_DEFAULT_CLIENT "MATE Dictionary (" VERSION ")"
Definition at line 129 of file gdict-client-context.c.
Referenced by gdict_client_context_new(), and gdict_client_context_set_client().
GDICT_DEFAULT_HOSTNAME
#define GDICT_DEFAULT_HOSTNAME "dict.org"
Definition at line 132 of file gdict-client-context.c.
Referenced by gdict_client_context_new(), and gdict_client_context_set_hostname().
GDICT_DEFAULT_PORT
#define GDICT_DEFAULT_PORT 2628
Definition at line 133 of file gdict-client-context.c.
Referenced by gdict_client_context_new(), and gdict_client_context_set_port().
HOSTNAME_LOOKUP_EXPIRE
#define HOSTNAME_LOOKUP_EXPIRE 300
Definition at line 136 of file gdict-client-context.c.
IS_VALID_CMD
#define IS_VALID_CMD (cmd)
Value:
(((cmd) >= CMD_CLIENT) || ((cmd) < CMD_INVALID))
Definition at line 78 of file gdict-client-context.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
S_START
S_STATUS
S_DATA
S_FINISH
Definition at line 99 of file gdict-client-context.c.
anonymous enum
anonymous enum
Enumerator
CONNECTED
DISCONNECTED
LAST_SIGNAL
Definition at line 151 of file gdict-client-context.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_HOSTNAME
PROP_PORT
PROP_STATUS
PROP_CLIENT_NAME
Definition at line 141 of file gdict-client-context.c.
GdictCommandType
enum GdictCommandType
SECTION:gdict-client-context @short_description: DICT client transport
GdictClientContext is an implementation of the GdictContext interface. It implements the Dictionary Protocol as defined by the RFC 2229 in order to connect to a dictionary server.
You should rarely instantiate this object directely: use an appropriate GdictSource instead.
Enumerator
CMD_CLIENT
CMD_SHOW_DB
CMD_SHOW_STRAT
CMD_SHOW_INFO
CMD_SHOW_SERVER
CMD_MATCH
CMD_DEFINE
CMD_STATUS
CMD_OPTION_MIME
CMD_AUTH
CMD_HELP
CMD_QUIT
CMD_INVALID
Definition at line 62 of file gdict-client-context.c.
Function Documentation
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (GdictClientContext , gdict_client_context , G_TYPE_OBJECT , G_IMPLEMENT_INTERFACE(GDICT_TYPE_CONTEXT, gdict_client_context_iface_init))
References condition, error, and GDICT_TYPE_CONTEXT.
gdict_client_context_error_quark()
GQuark gdict_client_context_error_quark (void)
Definition at line 243 of file gdict-client-context.c.
gdict_client_context_get_client()
const gchar * gdict_client_context_get_client (GdictClientContext * context)
gdict_client_context_get_client: @context: a GdictClientContext
Gets the client name used by @context. See gdict_client_context_set_client().
Return value: the client name. The returned string is owned by the GdictClientContext object and should never be modified or freed.
Definition at line 627 of file gdict-client-context.c.
References GDICT_IS_CLIENT_CONTEXT, and NULL.
gdict_client_context_get_hostname()
const gchar * gdict_client_context_get_hostname (GdictClientContext * context)
gdict_client_context_get_hostname: @context: a GdictClientContext
Gets the hostname of the dictionary server used by @context.
Return value: the hostname of a dictionary server. The returned string is owned by the GdictClientContext object and should never be modified or freed.
Definition at line 546 of file gdict-client-context.c.
References GDICT_IS_CLIENT_CONTEXT, and NULL.
Referenced by gdict_source_set_transportv().
gdict_client_context_get_port()
guint gdict_client_context_get_port (GdictClientContext * context)
gdict_client_context_get_port: @context: a GdictClientContext
Gets the port of the dictionary server used by @context.
Return value: the number of the port.
Definition at line 586 of file gdict-client-context.c.
References GDICT_IS_CLIENT_CONTEXT, and NULL.
Referenced by gdict_source_set_transportv().
gdict_client_context_new()
GdictContext * gdict_client_context_new (const gchar * hostname, gint port)
gdict_client_context_new: @hostname: the hostname of a dictionary server, or NULL for the default server @port: port to be used when connecting to the dictionary server, or -1 for the default port
Creates a new GdictClientContext object for @hostname. Use this object to connect and query the dictionary server using the Dictionary Protocol as defined by RFC 2229.
Return value: the newly created GdictClientContext object. You should free it using g_object_unref().
Definition at line 506 of file gdict-client-context.c.
References GDICT_DEFAULT_CLIENT, GDICT_DEFAULT_HOSTNAME, GDICT_DEFAULT_PORT, GDICT_TYPE_CLIENT_CONTEXT, and NULL.
Referenced by gdict_source_set_transportv().
gdict_client_context_set_client()
void gdict_client_context_set_client (GdictClientContext * context, const gchar * client)
gdict_client_context_set_client: @context: a GdictClientContext @client: the client name to use, or NULL
Sets @client as the client name to be used when advertising ourselves when a connection the the dictionary server has been established. If @client is NULL, the default client name will be used.
Definition at line 607 of file gdict-client-context.c.
References GDICT_DEFAULT_CLIENT, GDICT_IS_CLIENT_CONTEXT, and NULL.
gdict_client_context_set_hostname()
void gdict_client_context_set_hostname (GdictClientContext * context, const gchar * hostname)
gdict_client_context_set_hostname: @context: a GdictClientContext @hostname: the hostname of a Dictionary server, or NULL
Sets @hostname as the hostname of the dictionary server to be used. If @hostname is NULL, the default dictionary server will be used.
Definition at line 525 of file gdict-client-context.c.
References GDICT_DEFAULT_HOSTNAME, GDICT_IS_CLIENT_CONTEXT, and NULL.
gdict_client_context_set_port()
void gdict_client_context_set_port (GdictClientContext * context, gint port)
gdict_client_context_set_port: @context: a GdictClientContext @port: port of the dictionary server to be used, or -1
Sets the port of the dictionary server to be used when connecting.
If @port is -1, the default port will be used.
Definition at line 567 of file gdict-client-context.c.
References GDICT_DEFAULT_PORT, GDICT_IS_CLIENT_CONTEXT, and NULL.