MATE Desktop Environment: gdict-app.h File Reference
gdict-app.h File Reference
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <libgdict/gdict.h>
#include "gdict-window.h"
Classes
struct _GdictApp
Macros
#define GDICT_TYPE_APP (gdict_app_get_type ())
#define GDICT_APP(obj)
#define GDICT_IS_APP(obj)
Typedefs
typedef struct _GdictApp GdictApp
typedef struct _GdictAppClass GdictAppClass
Functions
GType gdict_app_get_type (void)
void gdict_init (int *argc, char ***argv)
void gdict_main (void)
void gdict_cleanup (void)
Macro Definition Documentation
GDICT_APP
#define GDICT_APP (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), GDICT_TYPE_APP, GdictApp))
Definition at line 32 of file gdict-app.h.
Referenced by gdict_init().
GDICT_IS_APP
#define GDICT_IS_APP (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), GDICT_TYPE_APP))
Definition at line 33 of file gdict-app.h.
Referenced by gdict_init().
GDICT_TYPE_APP
#define GDICT_TYPE_APP (gdict_app_get_type ())
Definition at line 31 of file gdict-app.h.
Referenced by gdict_init().
Typedef Documentation
GdictApp
typedef struct _GdictApp GdictApp
Definition at line 35 of file gdict-app.h.
GdictAppClass
typedef struct _GdictAppClass GdictAppClass
Definition at line 36 of file gdict-app.h.
Function Documentation
gdict_app_get_type()
GType gdict_app_get_type (void)
gdict_cleanup()
void gdict_cleanup (void)
Definition at line 426 of file gdict-app.c.
Referenced by gdict_init(), and main().
gdict_init()
void gdict_init (int * argc, char *** argv)
Definition at line 305 of file gdict-app.c.
References _, FALSE, GDICT_APP, gdict_cleanup(), gdict_create_data_dir(), gdict_get_data_dir(), gdict_get_option_group(), GDICT_IS_APP, gdict_source_loader_add_search_path(), gdict_source_loader_new(), GDICT_TYPE_APP, GETTEXT_PACKAGE, N_, NULL, and TRUE.
Referenced by main().
gdict_main()
void gdict_main (void)
Definition at line 409 of file gdict-app.c.
Referenced by main().