MATE Desktop Environment: gdict-source.h File Reference
gdict-source.h File Reference
#include <stdarg.h>
#include <glib-object.h>
#include "gdict-context.h"
Classes
struct _GdictSource
struct _GdictSourceClass
Macros
#define GDICT_TYPE_SOURCE (gdict_source_get_type ())
#define GDICT_SOURCE(obj)
#define GDICT_IS_SOURCE(obj)
#define GDICT_SOURCE_CLASS(klass)
#define GDICT_IS_SOURCE_CLASS(klass)
#define GDICT_SOURCE_GET_CLASS(obj)
#define GDICT_SOURCE_ERROR (gdict_source_error_quark ())
Typedefs
typedef struct _GdictSource GdictSource
typedef struct _GdictSourceClass GdictSourceClass
typedef struct _GdictSourcePrivate GdictSourcePrivate
Enumerations
enum GdictSourceTransport { GDICT_SOURCE_TRANSPORT_DICTD , GDICT_SOURCE_TRANSPORT_INVALID }
enum GdictSourceError { GDICT_SOURCE_ERROR_PARSE , GDICT_SOURCE_ERROR_INVALID_NAME , GDICT_SOURCE_ERROR_INVALID_TRANSPORT , GDICT_SOURCE_ERROR_INVALID_BAD_PARAMETER }
Functions
GQuark gdict_source_error_quark (void)
GType gdict_source_get_type (void)
GdictSource * gdict_source_new (void)
gboolean gdict_source_load_from_file (GdictSource *source, const gchar *filename, GError **error)
gboolean gdict_source_load_from_data (GdictSource *source, const gchar *data, gsize length, GError **error)
gchar * gdict_source_to_data (GdictSource *source, gsize *length, GError **error) G_GNUC_MALLOC
void gdict_source_set_name (GdictSource *source, const gchar *name)
const gchar * gdict_source_get_name (GdictSource *source)
void gdict_source_set_description (GdictSource *source, const gchar *description)
const gchar * gdict_source_get_description (GdictSource *source)
void gdict_source_set_database (GdictSource *source, const gchar *database)
const gchar * gdict_source_get_database (GdictSource *source)
void gdict_source_set_strategy (GdictSource *source, const gchar *strategy)
const gchar * gdict_source_get_strategy (GdictSource *source)
void gdict_source_set_transport (GdictSource *source, GdictSourceTransport transport, const gchar *first_transport_property,...)
void gdict_source_set_transportv (GdictSource *source, GdictSourceTransport transport, const gchar *first_transport_property, va_list var_args)
GdictSourceTransport gdict_source_get_transport (GdictSource *source)
GdictContext * gdict_source_get_context (GdictSource *source)
GdictContext * gdict_source_peek_context (GdictSource *source)
Macro Definition Documentation
GDICT_IS_SOURCE
#define GDICT_IS_SOURCE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), GDICT_TYPE_SOURCE))
Definition at line 31 of file gdict-source.h.
Referenced by gdict_source_get_context(), gdict_source_get_database(), gdict_source_get_description(), gdict_source_get_name(), gdict_source_get_strategy(), gdict_source_get_transport(), gdict_source_load_from_data(), gdict_source_load_from_file(), gdict_source_peek_context(), gdict_source_set_database(), gdict_source_set_description(), gdict_source_set_name(), gdict_source_set_strategy(), gdict_source_set_transport(), gdict_source_set_transportv(), and gdict_source_to_data().
GDICT_IS_SOURCE_CLASS
#define GDICT_IS_SOURCE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), GDICT_TYPE_SOURCE))
Definition at line 33 of file gdict-source.h.
GDICT_SOURCE
#define GDICT_SOURCE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), GDICT_TYPE_SOURCE, GdictSource))
Definition at line 30 of file gdict-source.h.
Referenced by gdict_source_loader_get_names(), and gdict_source_loader_remove_source().
GDICT_SOURCE_CLASS
#define GDICT_SOURCE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), GDICT_TYPE_SOURCE, GdictSourceClass))
Definition at line 32 of file gdict-source.h.
GDICT_SOURCE_ERROR
#define GDICT_SOURCE_ERROR (gdict_source_error_quark ())
Definition at line 48 of file gdict-source.h.
Referenced by gdict_source_to_data().
GDICT_SOURCE_GET_CLASS
#define GDICT_SOURCE_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), GDICT_TYPE_SOURCE, GdictSourceClass))
Definition at line 34 of file gdict-source.h.
GDICT_TYPE_SOURCE
#define GDICT_TYPE_SOURCE (gdict_source_get_type ())
Definition at line 29 of file gdict-source.h.
Referenced by gdict_source_new().
Typedef Documentation
GdictSource
typedef struct _GdictSource GdictSource
Definition at line 37 of file gdict-source.h.
GdictSourceClass
typedef struct _GdictSourceClass GdictSourceClass
Definition at line 38 of file gdict-source.h.
GdictSourcePrivate
typedef struct _GdictSourcePrivate GdictSourcePrivate
Definition at line 39 of file gdict-source.h.
Enumeration Type Documentation
GdictSourceError
enum GdictSourceError
Enumerator
GDICT_SOURCE_ERROR_PARSE
GDICT_SOURCE_ERROR_INVALID_NAME
GDICT_SOURCE_ERROR_INVALID_TRANSPORT
GDICT_SOURCE_ERROR_INVALID_BAD_PARAMETER
Definition at line 50 of file gdict-source.h.
GdictSourceTransport
enum GdictSourceTransport
Enumerator
GDICT_SOURCE_TRANSPORT_DICTD
GDICT_SOURCE_TRANSPORT_INVALID
Definition at line 41 of file gdict-source.h.
Function Documentation
gdict_source_error_quark()
GQuark gdict_source_error_quark (void)
Definition at line 104 of file gdict-source.c.
gdict_source_get_context()
GdictContext * gdict_source_get_context (GdictSource * source)
gdict_source_get_context: @source: a GdictSource
Gets the GdictContext bound to @source.
Return value: a GdictContext for @source. Use g_object_unref() when you don't need it anymore.
Since: 1.0
Definition at line 1150 of file gdict-source.c.
References GDICT_IS_SOURCE, NULL, and _GdictSource::priv.
Referenced by gdict_window_new().
gdict_source_get_database()
const gchar * gdict_source_get_database (GdictSource * source)
gdict_source_get_database: @source: a GdictSource
Retrieves the default database of @source.
Return value: the default strategy of a GdictSource. The returned string is owned by the GdictSource object, and should not be modified or freed.
Since: 1.0
Definition at line 926 of file gdict-source.c.
References GDICT_IS_SOURCE, NULL, and _GdictSource::priv.
gdict_source_get_description()
const gchar * gdict_source_get_description (GdictSource * source)
gdict_source_get_description: @source: a GdictSource
Retrieves the description of @source.
Return value: the description of a GdictSource. The returned string is owned by the GdictSource object, and should not be modified or freed.
Since: 1.0
Definition at line 864 of file gdict-source.c.
References GDICT_IS_SOURCE, NULL, and _GdictSource::priv.
Referenced by gdict_source_chooser_refresh().
gdict_source_get_name()
const gchar * gdict_source_get_name (GdictSource * source)
gdict_source_get_name: @source: a GdictSource
Retrieves the name of @source.
Return value: the name of a GdictSource. The returned string is owned by the GdictSource object, and should not be modified or freed.
Since: 1.0
Definition at line 802 of file gdict-source.c.
References GDICT_IS_SOURCE, NULL, and _GdictSource::priv.
Referenced by gdict_source_chooser_refresh(), gdict_source_loader_get_names(), and gdict_source_loader_remove_source().
gdict_source_get_strategy()
const gchar * gdict_source_get_strategy (GdictSource * source)
gdict_source_get_strategy: @source: a GdictSource
Retrieves the default strategy of @source.
Return value: the default strategy of a GdictSource. The returned string is owned by the GdictSource object, and should not be modified or freed.
Since: 1.0
Definition at line 988 of file gdict-source.c.
References GDICT_IS_SOURCE, NULL, and _GdictSource::priv.
gdict_source_get_transport()
GdictSourceTransport gdict_source_get_transport (GdictSource * source)
gdict_source_get_transport: @source: a GdictSource
FIXME
Return value: FIXME
Since: 1.0
Definition at line 1131 of file gdict-source.c.
References GDICT_IS_SOURCE, GDICT_SOURCE_TRANSPORT_INVALID, and _GdictSource::priv.
Referenced by gdict_source_chooser_refresh().
gdict_source_get_type()
GType gdict_source_get_type (void)
References data, error, and name.
gdict_source_load_from_data()
gboolean gdict_source_load_from_data (GdictSource * source, const gchar * data, gsize length, GError ** error)
gdict_source_load_from_data: @source: a GdictSource @data: string containing a dictionary source @length: length of @data @error: return location for a #GError or NULL
Loads a dictionary source definition from @data inside an empty GdictSource object.
Return value: TRUE if @filename was loaded successfully.
Since: 1.0
Definition at line 657 of file gdict-source.c.
References data, error, FALSE, GDICT_IS_SOURCE, NULL, _GdictSource::priv, and TRUE.
gdict_source_load_from_file()
gboolean gdict_source_load_from_file (GdictSource * source, const gchar * filename, GError ** error)
gdict_source_load_from_file: @source: an empty GdictSource @filename: path to a dictionary source file @error: return location for a #GError or NULL
Loads a dictionary source definition file into an empty GdictSource object.
Return value: TRUE if @filename was loaded successfully.
Since: 1.0
Definition at line 598 of file gdict-source.c.
References error, FALSE, GDICT_IS_SOURCE, NULL, _GdictSource::priv, and TRUE.
gdict_source_new()
GdictSource * gdict_source_new (void)
gdict_source_new:
Creates an empty GdictSource object. Use gdict_load_from_file() to read an existing dictionary source definition file.
Return value: an empty GdictSource
Definition at line 346 of file gdict-source.c.
References GDICT_TYPE_SOURCE, and NULL.
gdict_source_peek_context()
GdictContext * gdict_source_peek_context (GdictSource * source)
gdict_source_peek_context: @source: a GdictSource
Gets the GdictContext bound to @source. The returned object is a referenced copy of the context held by @source; if you want a different instance, use gdict_source_get_context().
Return value: a referenced GdictContext. Use g_object_unref() when finished using it.
Since: 1.0
Definition at line 1177 of file gdict-source.c.
References GDICT_IS_SOURCE, NULL, and _GdictSource::priv.
gdict_source_set_database()
void gdict_source_set_database (GdictSource * source, const gchar * database)
gdict_source_set_database: @source: a GdictSource @database: a UTF-8 encoded database name or NULL
Sets the default database of @source. If @database is NULL, unsets the currently set database.
Since: 1.0
Definition at line 882 of file gdict-source.c.
References GDICT_IS_SOURCE, NULL, _GdictSource::priv, SOURCE_GROUP, and SOURCE_KEY_DATABASE.
gdict_source_set_description()
void gdict_source_set_description (GdictSource * source, const gchar * description)
gdict_source_set_description: @source: a GdictSource @description: a UTF-8 encoded description or NULL
Sets the description of @source. If @description is NULL, unsets the currently set description.
Since: 1.0
Definition at line 820 of file gdict-source.c.
References GDICT_IS_SOURCE, NULL, _GdictSource::priv, SOURCE_GROUP, and SOURCE_KEY_DESCRIPTION.
gdict_source_set_name()
void gdict_source_set_name (GdictSource * source, const gchar * name)
Definition at line 772 of file gdict-source.c.
References GDICT_IS_SOURCE, name, NULL, _GdictSource::priv, SOURCE_GROUP, and SOURCE_KEY_NAME.
gdict_source_set_strategy()
void gdict_source_set_strategy (GdictSource * source, const gchar * strategy)
gdict_source_set_strategy: @source: a GdictSource @strategy: a UTF-8 encoded strategy or NULL
Sets the description of @source. If @strategy is NULL, unsets the currently set strategy.
Since: 1.0
Definition at line 944 of file gdict-source.c.
References GDICT_IS_SOURCE, NULL, _GdictSource::priv, SOURCE_GROUP, and SOURCE_KEY_STRATEGY.
gdict_source_set_transport()
void gdict_source_set_transport (GdictSource * source, GdictSourceTransport transport, const gchar * first_transport_property, ...)
gdict_source_set_transport: @source: a GdictSource @transport: a valid transport @first_transport_property: property for the context bound to the transport, or NULL @Varargs: property value for first property name, then additionary properties, ending with NULL
Sets @transport as the choosen transport for @source. The @transport argument is a method of retrieving dictionary data from a source; it is used to create the right GdictContext for this GdictSource. After @transport, property name/value pairs should be listed, with a NULL pointer ending the list. Properties are the same passed to a GdictContext implementation instance using g_object_set().
Here's a simple example:
<informalexample><programlisting> #include <gdict/gdict.h> GdictSource *source = gdict_source_new ();
gdict_source_set_name (source, "My Source"); gdict_source_set_transport (source, GDICT_SOURCE_TRANSPORT_DICTD, "hostname", "dictionary-server.org", "port", 2628, NULL); </programlisting></informalexample>
Since: 1.0
Definition at line 1101 of file gdict-source.c.
References GDICT_IS_SOURCE, gdict_source_set_transportv(), and IS_VALID_TRANSPORT.
gdict_source_set_transportv()
void gdict_source_set_transportv (GdictSource * source, GdictSourceTransport transport, const gchar * first_transport_property, va_list var_args)
gdict_source_set_transportv @source: a GdictSource @transport: a GdictSourceTransport @first_transport_property: FIXME @var_args: FIXME
FIXME
Since: 1.0
Definition at line 1007 of file gdict-source.c.
References GDICT_CLIENT_CONTEXT, gdict_client_context_get_hostname(), gdict_client_context_get_port(), gdict_client_context_new(), GDICT_IS_CLIENT_CONTEXT, GDICT_IS_SOURCE, GDICT_SOURCE_TRANSPORT_DICTD, GDICT_SOURCE_TRANSPORT_INVALID, IS_VALID_TRANSPORT, NULL, _GdictSource::priv, SOURCE_GROUP, SOURCE_KEY_HOSTNAME, SOURCE_KEY_PORT, and SOURCE_KEY_TRANSPORT.
Referenced by gdict_source_set_transport().
gdict_source_to_data()
gchar * gdict_source_to_data (GdictSource * source, gsize * length, GError ** error)
gdict_source_to_data: @source: a GdictSource @length: return loaction for the length of the string, or NULL @error: return location for a #GError or NULL
Outputs a dictionary source as a string.
Return value: a newly allocated string holding the contents of @source.
Since: 1.0
Definition at line 717 of file gdict-source.c.
References _, error, GDICT_IS_SOURCE, GDICT_SOURCE_ERROR, GDICT_SOURCE_ERROR_INVALID_NAME, GDICT_SOURCE_ERROR_INVALID_TRANSPORT, IS_VALID_TRANSPORT, NULL, and _GdictSource::priv.