MATE Desktop Environment: gdict-speller.h File Reference
gdict-speller.h File Reference
#include <gtk/gtk.h>
#include "gdict-context.h"
Classes
struct _GdictSpeller
struct _GdictSpellerClass
Macros
#define GDICT_TYPE_SPELLER (gdict_speller_get_type ())
#define GDICT_SPELLER(obj)
#define GDICT_SPELLER_CLASS(klass)
#define GDICT_IS_SPELLER(obj)
#define GDICT_IS_SPELLER_CLASS(klass)
#define GDICT_SPELLER_GET_CLASS(obj)
Typedefs
typedef struct _GdictSpeller GdictSpeller
typedef struct _GdictSpellerPrivate GdictSpellerPrivate
typedef struct _GdictSpellerClass GdictSpellerClass
Functions
GType gdict_speller_get_type (void)
GtkWidget * gdict_speller_new (void)
GtkWidget * gdict_speller_new_with_context (GdictContext *context)
void gdict_speller_set_context (GdictSpeller *speller, GdictContext *context)
GdictContext * gdict_speller_get_context (GdictSpeller *speller)
void gdict_speller_set_database (GdictSpeller *speller, const gchar *database)
const gchar * gdict_speller_get_database (GdictSpeller *speller)
void gdict_speller_set_strategy (GdictSpeller *speller, const gchar *strategy)
const gchar * gdict_speller_get_strategy (GdictSpeller *speller)
void gdict_speller_clear (GdictSpeller *speller)
void gdict_speller_match (GdictSpeller *speller, const gchar *word)
gint gdict_speller_count_matches (GdictSpeller *speller)
gchar ** gdict_speller_get_matches (GdictSpeller *speller, gsize length)
Macro Definition Documentation
GDICT_IS_SPELLER
#define GDICT_IS_SPELLER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), GDICT_TYPE_SPELLER))
Definition at line 31 of file gdict-speller.h.
Referenced by gdict_speller_clear(), gdict_speller_count_matches(), gdict_speller_get_context(), gdict_speller_get_database(), gdict_speller_get_matches(), gdict_speller_get_strategy(), gdict_speller_match(), gdict_speller_set_context(), gdict_speller_set_database(), and gdict_speller_set_strategy().
GDICT_IS_SPELLER_CLASS
#define GDICT_IS_SPELLER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), GDICT_TYPE_SPELLER))
Definition at line 32 of file gdict-speller.h.
GDICT_SPELLER
#define GDICT_SPELLER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), GDICT_TYPE_SPELLER, GdictSpeller))
Definition at line 29 of file gdict-speller.h.
Referenced by gdict_window_new().
GDICT_SPELLER_CLASS
#define GDICT_SPELLER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), GDICT_TYPE_SPELLER, GdictSpellerClass))
Definition at line 30 of file gdict-speller.h.
GDICT_SPELLER_GET_CLASS
#define GDICT_SPELLER_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), GDICT_TYPE_SPELLER, GdictSpellerClass))
Definition at line 33 of file gdict-speller.h.
GDICT_TYPE_SPELLER
#define GDICT_TYPE_SPELLER (gdict_speller_get_type ())
Definition at line 28 of file gdict-speller.h.
Referenced by gdict_speller_new(), and gdict_speller_new_with_context().
Typedef Documentation
GdictSpeller
typedef struct _GdictSpeller GdictSpeller
Definition at line 35 of file gdict-speller.h.
GdictSpellerClass
typedef struct _GdictSpellerClass GdictSpellerClass
Definition at line 37 of file gdict-speller.h.
GdictSpellerPrivate
typedef struct _GdictSpellerPrivate GdictSpellerPrivate
Definition at line 36 of file gdict-speller.h.
Function Documentation
gdict_speller_clear()
void gdict_speller_clear (GdictSpeller * speller)
gdict_speller_clear: @speller: a GdictSpeller
FIXME
Since: FIXME
Definition at line 600 of file gdict-speller.c.
References GDICT_IS_SPELLER, NULL, and _GdictSpeller::priv.
Referenced by gdict_speller_match().
gdict_speller_count_matches()
gint gdict_speller_count_matches (GdictSpeller * speller)
gdict_speller_count_match: @speller: a GdictSpeller
FIXME
Return value: FIXME
Since: FIXME
Definition at line 795 of file gdict-speller.c.
References GDICT_IS_SPELLER, and _GdictSpeller::priv.
gdict_speller_get_context()
GdictContext * gdict_speller_get_context (GdictSpeller * speller)
gdict_speller_get_context: @speller: a GdictSpeller
FIXME
Return value: a GdictContext
Since:
Definition at line 492 of file gdict-speller.c.
References GDICT_IS_SPELLER, NULL, and _GdictSpeller::priv.
gdict_speller_get_database()
const gchar * gdict_speller_get_database (GdictSpeller * speller)
gdict_speller_get_database: @speller: a GdictSpeller
FIXME
Return value: FIXME
Since: FIXME
Definition at line 538 of file gdict-speller.c.
References GDICT_IS_SPELLER, NULL, and _GdictSpeller::priv.
gdict_speller_get_matches()
gchar ** gdict_speller_get_matches (GdictSpeller * speller, gsize length)
gdict_speller_get_matches: @speller: a GdictSpeller @length: FIXME
FIXME
Return value: FIXME
Since: FIXME
Definition at line 814 of file gdict-speller.c.
References GDICT_IS_SPELLER, and NULL.
gdict_speller_get_strategy()
const gchar * gdict_speller_get_strategy (GdictSpeller * speller)
gdict_speller_get_strategy: @speller: a GdictSpeller
FIXME
Return value: FIXME
Since: FIXME
Definition at line 584 of file gdict-speller.c.
References GDICT_IS_SPELLER, NULL, and _GdictSpeller::priv.
gdict_speller_get_type()
GType gdict_speller_get_type (void)
gdict_speller_match()
void gdict_speller_match (GdictSpeller * speller, const gchar * word)
gdict_speller_match: @speller: a GdictSpeller @word: FIXME
FIXME
Since: FIXME
Definition at line 706 of file gdict-speller.c.
References _, _gdict_show_error_dialog(), gdict_context_match_word(), GDICT_IS_SPELLER, gdict_speller_clear(), MATCH_COLUMN_DB_NAME, MATCH_COLUMN_TYPE, MATCH_COLUMN_WORD, MATCH_ERROR, NULL, and _GdictSpeller::priv.
Referenced by gdict_window_new().
gdict_speller_new()
GtkWidget * gdict_speller_new (void)
gdict_speller_new:
FIXME
Return value: FIXME
Since:
Definition at line 435 of file gdict-speller.c.
References GDICT_TYPE_SPELLER, and NULL.
gdict_speller_new_with_context()
GtkWidget * gdict_speller_new_with_context (GdictContext * context)
gdict_speller_new_with_context: @context: a GdictContext
FIXME
Return value: FIXME
Since:
Definition at line 451 of file gdict-speller.c.
References GDICT_IS_CONTEXT, GDICT_TYPE_SPELLER, and NULL.
gdict_speller_set_context()
void gdict_speller_set_context (GdictSpeller * speller, GdictContext * context)
gdict_speller_set_context: @speller: a GdictSpeller @context: a GdictContext
FIXME
Since:
Definition at line 470 of file gdict-speller.c.
References GDICT_IS_CONTEXT, GDICT_IS_SPELLER, and NULL.
Referenced by gdict_window_new().
gdict_speller_set_database()
void gdict_speller_set_database (GdictSpeller * speller, const gchar * database)
gdict_speller_set_database: @speller: a GdictSpeller @database: FIXME
FIXME
Since:
Definition at line 509 of file gdict-speller.c.
References GDICT_DEFAULT_DATABASE, GDICT_IS_SPELLER, and _GdictSpeller::priv.
gdict_speller_set_strategy()
void gdict_speller_set_strategy (GdictSpeller * speller, const gchar * strategy)
gdict_speller_set_strategy: @speller: a GdictSpeller @strategy: FIXME
FIXME
Since: FIXME
Definition at line 555 of file gdict-speller.c.
References GDICT_DEFAULT_STRATEGY, GDICT_IS_SPELLER, and _GdictSpeller::priv.
Referenced by gdict_window_new().