MATE Desktop Environment: gdict-speller.c File Reference
gdict-speller.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include "gdict-speller.h"
#include "gdict-utils.h"
#include "gdict-enum-types.h"
#include "gdict-marshal.h"
#include "gdict-debug.h"
#include "gdict-private.h"
Enumerations
enum MatchType { MATCH_DB , MATCH_WORD , MATCH_ERROR }
enum { MATCH_COLUMN_TYPE , MATCH_COLUMN_DB_NAME , MATCH_COLUMN_WORD , MATCH_N_COLUMNS }
enum {
PROP_0 , PROP_CONTEXT , PROP_WORD , PROP_DATABASE ,
PROP_STRATEGY , PROP_COUNT
}
enum { WORD_ACTIVATED , LAST_SIGNAL }
Functions
GtkWidget * gdict_speller_new (void)
GtkWidget * gdict_speller_new_with_context (GdictContext *context)
void gdict_speller_set_context (GdictSpeller *speller, GdictContext *context)
GdictContext * gdict_speller_get_context (GdictSpeller *speller)
void gdict_speller_set_database (GdictSpeller *speller, const gchar *database)
const gchar * gdict_speller_get_database (GdictSpeller *speller)
void gdict_speller_set_strategy (GdictSpeller *speller, const gchar *strategy)
const gchar * gdict_speller_get_strategy (GdictSpeller *speller)
void gdict_speller_clear (GdictSpeller *speller)
void gdict_speller_match (GdictSpeller *speller, const gchar *word)
gint gdict_speller_count_matches (GdictSpeller *speller)
gchar ** gdict_speller_get_matches (GdictSpeller *speller, gsize length)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
WORD_ACTIVATED
LAST_SIGNAL
Definition at line 99 of file gdict-speller.c.
anonymous enum
anonymous enum
Enumerator
MATCH_COLUMN_TYPE
MATCH_COLUMN_DB_NAME
MATCH_COLUMN_WORD
MATCH_N_COLUMNS
Definition at line 79 of file gdict-speller.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_CONTEXT
PROP_WORD
PROP_DATABASE
PROP_STRATEGY
PROP_COUNT
Definition at line 88 of file gdict-speller.c.
MatchType
enum MatchType
Enumerator
MATCH_DB
MATCH_WORD
MATCH_ERROR
Definition at line 72 of file gdict-speller.c.
Function Documentation
gdict_speller_clear()
void gdict_speller_clear (GdictSpeller * speller)
gdict_speller_clear: @speller: a GdictSpeller
FIXME
Since: FIXME
Definition at line 600 of file gdict-speller.c.
References GDICT_IS_SPELLER, NULL, and _GdictSpeller::priv.
Referenced by gdict_speller_match().
gdict_speller_count_matches()
gint gdict_speller_count_matches (GdictSpeller * speller)
gdict_speller_count_match: @speller: a GdictSpeller
FIXME
Return value: FIXME
Since: FIXME
Definition at line 795 of file gdict-speller.c.
References GDICT_IS_SPELLER, and _GdictSpeller::priv.
gdict_speller_get_context()
GdictContext * gdict_speller_get_context (GdictSpeller * speller)
gdict_speller_get_context: @speller: a GdictSpeller
FIXME
Return value: a GdictContext
Since:
Definition at line 492 of file gdict-speller.c.
References GDICT_IS_SPELLER, NULL, and _GdictSpeller::priv.
gdict_speller_get_database()
const gchar * gdict_speller_get_database (GdictSpeller * speller)
gdict_speller_get_database: @speller: a GdictSpeller
FIXME
Return value: FIXME
Since: FIXME
Definition at line 538 of file gdict-speller.c.
References GDICT_IS_SPELLER, NULL, and _GdictSpeller::priv.
gdict_speller_get_matches()
gchar ** gdict_speller_get_matches (GdictSpeller * speller, gsize length)
gdict_speller_get_matches: @speller: a GdictSpeller @length: FIXME
FIXME
Return value: FIXME
Since: FIXME
Definition at line 814 of file gdict-speller.c.
References GDICT_IS_SPELLER, and NULL.
gdict_speller_get_strategy()
const gchar * gdict_speller_get_strategy (GdictSpeller * speller)
gdict_speller_get_strategy: @speller: a GdictSpeller
FIXME
Return value: FIXME
Since: FIXME
Definition at line 584 of file gdict-speller.c.
References GDICT_IS_SPELLER, NULL, and _GdictSpeller::priv.
gdict_speller_match()
void gdict_speller_match (GdictSpeller * speller, const gchar * word)
gdict_speller_match: @speller: a GdictSpeller @word: FIXME
FIXME
Since: FIXME
Definition at line 706 of file gdict-speller.c.
References _, _gdict_show_error_dialog(), gdict_context_match_word(), GDICT_IS_SPELLER, gdict_speller_clear(), MATCH_COLUMN_DB_NAME, MATCH_COLUMN_TYPE, MATCH_COLUMN_WORD, MATCH_ERROR, NULL, and _GdictSpeller::priv.
Referenced by gdict_window_new().
gdict_speller_new()
GtkWidget * gdict_speller_new (void)
gdict_speller_new:
FIXME
Return value: FIXME
Since:
Definition at line 435 of file gdict-speller.c.
References GDICT_TYPE_SPELLER, and NULL.
gdict_speller_new_with_context()
GtkWidget * gdict_speller_new_with_context (GdictContext * context)
gdict_speller_new_with_context: @context: a GdictContext
FIXME
Return value: FIXME
Since:
Definition at line 451 of file gdict-speller.c.
References GDICT_IS_CONTEXT, GDICT_TYPE_SPELLER, and NULL.
gdict_speller_set_context()
void gdict_speller_set_context (GdictSpeller * speller, GdictContext * context)
gdict_speller_set_context: @speller: a GdictSpeller @context: a GdictContext
FIXME
Since:
Definition at line 470 of file gdict-speller.c.
References GDICT_IS_CONTEXT, GDICT_IS_SPELLER, and NULL.
Referenced by gdict_window_new().
gdict_speller_set_database()
void gdict_speller_set_database (GdictSpeller * speller, const gchar * database)
gdict_speller_set_database: @speller: a GdictSpeller @database: FIXME
FIXME
Since:
Definition at line 509 of file gdict-speller.c.
References GDICT_DEFAULT_DATABASE, GDICT_IS_SPELLER, and _GdictSpeller::priv.
gdict_speller_set_strategy()
void gdict_speller_set_strategy (GdictSpeller * speller, const gchar * strategy)
gdict_speller_set_strategy: @speller: a GdictSpeller @strategy: FIXME
FIXME
Since: FIXME
Definition at line 555 of file gdict-speller.c.
References GDICT_DEFAULT_STRATEGY, GDICT_IS_SPELLER, and _GdictSpeller::priv.
Referenced by gdict_window_new().