MATE Desktop Environment: gdict-defbox.c File Reference
gdict-defbox.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <glib/gi18n-lib.h>
#include "gdict-defbox.h"
#include "gdict-utils.h"
#include "gdict-debug.h"
#include "gdict-private.h"
#include "gdict-enum-types.h"
#include "gdict-marshal.h"
Macros
#define QUERY_MARGIN 48
#define ERROR_MARGIN 24
#define GTK_TEXT_UNKNOWN_CHAR 0xFFFC
Enumerations
enum {
PROP_0 , PROP_CONTEXT , PROP_WORD , PROP_DATABASE ,
PROP_FONT_NAME , PROP_COUNT
}
enum {
SHOW_FIND , HIDE_FIND , FIND_NEXT , FIND_PREVIOUS ,
LINK_CLICKED , LAST_SIGNAL
}
Functions
GtkWidget * gdict_defbox_new (void)
GtkWidget * gdict_defbox_new_with_context (GdictContext *context)
void gdict_defbox_set_context (GdictDefbox *defbox, GdictContext *context)
GdictContext * gdict_defbox_get_context (GdictDefbox *defbox)
void gdict_defbox_set_database (GdictDefbox *defbox, const gchar *database)
const gchar * gdict_defbox_get_database (GdictDefbox *defbox)
const gchar * gdict_defbox_get_word (GdictDefbox *defbox)
void gdict_defbox_set_show_find (GdictDefbox *defbox, gboolean show_find)
gboolean gdict_defbox_get_show_find (GdictDefbox *defbox)
void gdict_defbox_lookup (GdictDefbox *defbox, const gchar *word)
void gdict_defbox_clear (GdictDefbox *defbox)
void gdict_defbox_find_next (GdictDefbox *defbox)
void gdict_defbox_find_previous (GdictDefbox *defbox)
void gdict_defbox_select_all (GdictDefbox *defbox)
void gdict_defbox_copy_to_clipboard (GdictDefbox *defbox, GtkClipboard *clipboard)
gint gdict_defbox_count_definitions (GdictDefbox *defbox)
void gdict_defbox_jump_to_definition (GdictDefbox *defbox, gint number)
gchar * gdict_defbox_get_text (GdictDefbox *defbox, gsize *length)
void gdict_defbox_set_font_name (GdictDefbox *defbox, const gchar *font_name)
const gchar * gdict_defbox_get_font_name (GdictDefbox *defbox)
gchar * gdict_defbox_get_selected_word (GdictDefbox *defbox)
Macro Definition Documentation
ERROR_MARGIN
#define ERROR_MARGIN 24
Definition at line 53 of file gdict-defbox.c.
GTK_TEXT_UNKNOWN_CHAR
#define GTK_TEXT_UNKNOWN_CHAR 0xFFFC
Definition at line 346 of file gdict-defbox.c.
QUERY_MARGIN
#define QUERY_MARGIN 48
SECTION:gdict-defbox @short_description: Display the list of definitions for a word
The GdictDefbox widget is a composite widget showing the list of definitions for a word. It queries the passed GdictContext and displays the list of #GdictDefinitions obtained.
It provides syntax highlighting, clickable links and an embedded find bar.
Definition at line 52 of file gdict-defbox.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SHOW_FIND
HIDE_FIND
FIND_NEXT
FIND_PREVIOUS
LINK_CLICKED
LAST_SIGNAL
Definition at line 113 of file gdict-defbox.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_CONTEXT
PROP_WORD
PROP_DATABASE
PROP_FONT_NAME
PROP_COUNT
Definition at line 102 of file gdict-defbox.c.
Function Documentation
gdict_defbox_clear()
void gdict_defbox_clear (GdictDefbox * defbox)
gdict_defbox_clear: @defbox: a @GdictDefbox
Clears the buffer of @defbox
Since: 0.1
Definition at line 2584 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
Referenced by gdict_defbox_lookup(), and gdict_window_new().
gdict_defbox_copy_to_clipboard()
void gdict_defbox_copy_to_clipboard (GdictDefbox * defbox, GtkClipboard * clipboard)
gdict_defbox_copy_to_clipboard: @defbox: a GdictDefbox @clipboard: a #GtkClipboard
Copies the selected text inside @defbox into @clipboard.
Since: 0.1
Definition at line 2670 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, and _GdictDefbox::priv.
gdict_defbox_count_definitions()
gint gdict_defbox_count_definitions (GdictDefbox * defbox)
gdict_defbox_count_definitions: @defbox: a GdictDefbox
Gets the number of definitions displayed by @defbox
Return value: the number of definitions.
Since: 0.1
Definition at line 2696 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, and _GdictDefbox::priv.
Referenced by gdict_defbox_jump_to_definition().
gdict_defbox_find_next()
void gdict_defbox_find_next (GdictDefbox * defbox)
gdict_defbox_find_next: @defbox: a GdictDefbox
Emits the "find-next" signal.
Since: 0.1
Definition at line 2613 of file gdict-defbox.c.
References FIND_NEXT, and GDICT_IS_DEFBOX.
gdict_defbox_find_previous()
void gdict_defbox_find_previous (GdictDefbox * defbox)
gdict_defbox_find_previous: @defbox: a GdictDefbox
Emits the "find-previous" signal.
Since: 0.1
Definition at line 2629 of file gdict-defbox.c.
References FIND_PREVIOUS, and GDICT_IS_DEFBOX.
gdict_defbox_get_context()
GdictContext * gdict_defbox_get_context (GdictDefbox * defbox)
gdict_defbox_get_context: @defbox: a GdictDefbox
Gets the GdictContext used by @defbox.
Return value: a GdictContext.
Since: 0.1
Definition at line 1969 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
gdict_defbox_get_database()
const gchar * gdict_defbox_get_database (GdictDefbox * defbox)
gdict_defbox_get_database: @defbox: a GdictDefbox
Gets the database used by @defbox. See gdict_defbox_set_database().
Return value: the name of a database. The return string is owned by the GdictDefbox widget and should not be modified or freed.
Since: 0.1
Definition at line 2014 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
gdict_defbox_get_font_name()
const gchar * gdict_defbox_get_font_name (GdictDefbox * defbox)
gdict_defbox_get_font_name: @defbox: a GdictDefbox
Retrieves the font currently used by @defbox.
Return value: a font name. The returned string is owned by @defbox and should not be modified or freed.
Since: 0.3
Definition at line 2840 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
gdict_defbox_get_selected_word()
gchar * gdict_defbox_get_selected_word (GdictDefbox * defbox)
gdict_defbox_get_selected_word: @defbox: a GdictDefbox
Retrieves the selected word from the defbox widget
Return value: a newly allocated string containing the selected word. Use g_free() when done using it.
Since: 0.12
Definition at line 2859 of file gdict-defbox.c.
References FALSE, GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
gdict_defbox_get_show_find()
gboolean gdict_defbox_get_show_find (GdictDefbox * defbox)
gdict_defbox_get_show_find: @defbox: a GdictDefbox
Gets whether the find pane should be visible or not.
Return value: TRUE if the find pane is visible.
Since: 0.1
Definition at line 2095 of file gdict-defbox.c.
References FALSE, GDICT_IS_DEFBOX, _GdictDefbox::priv, and TRUE.
gdict_defbox_get_text()
gchar * gdict_defbox_get_text (GdictDefbox * defbox, gsize * length)
gdict_defbox_get_text: @defbox: a GdictDefbox @length: return location for the text length or NULL
Gets the full contents of @defbox.
Return value: a newly allocated string containing the text displayed by @defbox.
Since: 0.1
Definition at line 2765 of file gdict-defbox.c.
References FALSE, GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
gdict_defbox_get_word()
const gchar * gdict_defbox_get_word (GdictDefbox * defbox)
gdict_defbox_get_word: @defbox: a GdictDefbox
Retrieves the word being looked up.
Return value: the word looked up, or NULL. The returned string is owned by the GdictDefbox widget and should never be modified or freed.
Since: 0.12
Definition at line 2034 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
gdict_defbox_jump_to_definition()
void gdict_defbox_jump_to_definition (GdictDefbox * defbox, gint number)
gdict_defbox_jump_to_definition: @defbox: a GdictDefbox @number: the definition to jump to
Scrolls to the definition identified by @number. If @number is -1, jumps to the last definition.
Since: 0.1
Definition at line 2720 of file gdict-defbox.c.
References gdict_defbox_count_definitions(), GDICT_IS_DEFBOX, _GdictDefbox::priv, and TRUE.
gdict_defbox_lookup()
void gdict_defbox_lookup (GdictDefbox * defbox, const gchar * word)
gdict_defbox_lookup: @defbox: a GdictDefbox @word: the word to look up
Searches @word inside the dictionary sources using the GdictContext provided when creating @defbox or set using gdict_defbox_set_context().
Since: 0.1
Definition at line 2505 of file gdict-defbox.c.
References _, _gdict_show_error_dialog(), gdict_context_define_word(), gdict_defbox_clear(), GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
gdict_defbox_new()
GtkWidget * gdict_defbox_new (void)
gdict_defbox_new:
Creates a new GdictDefbox widget. Use this widget to search for a word using a GdictContext, and to show the resulting definition(s). You must set a GdictContext for this widget using gdict_defbox_set_context().
Return value: a new GdictDefbox widget.
Since: 0.1
Definition at line 1914 of file gdict-defbox.c.
References GDICT_TYPE_DEFBOX, and NULL.
gdict_defbox_new_with_context()
GtkWidget * gdict_defbox_new_with_context (GdictContext * context)
gdict_defbox_new_with_context: @context: a GdictContext
Creates a new GdictDefbox widget. Use this widget to search for a word using @context, and to show the resulting definition.
Return value: a new GdictDefbox widget.
Since: 0.1
Definition at line 1931 of file gdict-defbox.c.
References GDICT_IS_CONTEXT, GDICT_TYPE_DEFBOX, and NULL.
gdict_defbox_select_all()
void gdict_defbox_select_all (GdictDefbox * defbox)
gdict_defbox_select_all: @defbox: a GdictDefbox
Selects all the text displayed by @defbox
Since: 0.1
Definition at line 2645 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, and _GdictDefbox::priv.
gdict_defbox_set_context()
void gdict_defbox_set_context (GdictDefbox * defbox, GdictContext * context)
gdict_defbox_set_context: @defbox: a GdictDefbox @context: a GdictContext
Sets @context as the GdictContext to be used by @defbox in order to retrieve the definitions of a word.
Since: 0.1
Definition at line 1949 of file gdict-defbox.c.
References GDICT_IS_CONTEXT, GDICT_IS_DEFBOX, and NULL.
gdict_defbox_set_database()
void gdict_defbox_set_database (GdictDefbox * defbox, const gchar * database)
gdict_defbox_set_database: @defbox: a GdictDefbox @database: a database
Sets @database as the database used by the GdictContext bound to @defbox to query for word definitions.
Since: 0.1
Definition at line 1987 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, and _GdictDefbox::priv.
gdict_defbox_set_font_name()
void gdict_defbox_set_font_name (GdictDefbox * defbox, const gchar * font_name)
gdict_defbox_set_font_name: @defbox: a GdictDefbox @font_name: a font description, or NULL
Sets @font_name as the font for @defbox. It calls internally pango_font_description_from_string() and gtk_widget_modify_font().
Passing NULL for @font_name will reset any previously set font.
Since: 0.3.0
Definition at line 2801 of file gdict-defbox.c.
References GDICT_IS_DEFBOX, NULL, and _GdictDefbox::priv.
gdict_defbox_set_show_find()
void gdict_defbox_set_show_find (GdictDefbox * defbox, gboolean show_find)
gdict_defbox_set_show_find: @defbox: a GdictDefbox @show_find: TRUE to show the find pane
Whether @defbox should show the find pane.
Since: 0.1
Definition at line 2051 of file gdict-defbox.c.
References FALSE, GDICT_IS_DEFBOX, and _GdictDefbox::priv.