MATE Desktop Environment: gdict-utils.h File Reference
gdict-utils.h File Reference
#include <glib-object.h>
#include <gtk/gtk.h>
Macros
#define GDICT_DEFAULT_DATABASE "*"
#define GDICT_DEFAULT_STRATEGY "."
#define GDICT_DEFAULT_FONT_NAME "Sans 10"
#define GDICT_IS_VALID_STATUS_CODE(x)
Enumerations
enum GdictContextProp { GDICT_CONTEXT_PROP_FIRST = 0x1000 , GDICT_CONTEXT_PROP_LOCAL_ONLY = GDICT_CONTEXT_PROP_FIRST , GDICT_CONTEXT_PROP_LAST }
enum GdictStatusCode {
GDICT_STATUS_INVALID = 0 , GDICT_STATUS_N_DATABASES_PRESENT = 110 , GDICT_STATUS_N_STRATEGIES_PRESENT = 111 , GDICT_STATUS_DATABASE_INFO = 112 ,
GDICT_STATUS_HELP_TEXT = 113 , GDICT_STATUS_SERVER_INFO = 114 , GDICT_STATUS_CHALLENGE = 130 , GDICT_STATUS_N_DEFINITIONS_RETRIEVED = 150 ,
GDICT_STATUS_WORD_DB_NAME = 151 , GDICT_STATUS_N_MATCHES_FOUND = 152 , GDICT_STATUS_CONNECT = 220 , GDICT_STATUS_QUIT = 221 ,
GDICT_STATUS_AUTH_OK = 230 , GDICT_STATUS_OK = 250 , GDICT_STATUS_SEND_RESPONSE = 330 , GDICT_STATUS_SERVER_DOWN = 420 ,
GDICT_STATUS_SHUTDOWN = 421 , GDICT_STATUS_BAD_COMMAND = 500 , GDICT_STATUS_BAD_PARAMETERS = 501 , GDICT_STATUS_COMMAND_NOT_IMPLEMENTED = 502 ,
GDICT_STATUS_PARAMETER_NOT_IMPLEMENTED = 503 , GDICT_STATUS_NO_ACCESS = 530 , GDICT_STATUS_USE_SHOW_INFO = 531 , GDICT_STATUS_UNKNOWN_MECHANISM = 532 ,
GDICT_STATUS_BAD_DATABASE = 550 , GDICT_STATUS_BAD_STRATEGY = 551 , GDICT_STATUS_NO_MATCH = 552 , GDICT_STATUS_NO_DATABASES_PRESENT = 554 ,
GDICT_STATUS_NO_STRATEGIES_PRESENT = 555
}
Functions
GOptionGroup * gdict_get_option_group (void)
void gdict_debug_init (gint *argc, gchar ***argv)
Macro Definition Documentation
GDICT_DEFAULT_DATABASE
#define GDICT_DEFAULT_DATABASE "*"
Definition at line 28 of file gdict-utils.h.
Referenced by gdict_speller_set_database().
GDICT_DEFAULT_FONT_NAME
#define GDICT_DEFAULT_FONT_NAME "Sans 10"
Definition at line 31 of file gdict-utils.h.
GDICT_DEFAULT_STRATEGY
#define GDICT_DEFAULT_STRATEGY "."
Definition at line 29 of file gdict-utils.h.
Referenced by gdict_speller_set_strategy().
GDICT_IS_VALID_STATUS_CODE
#define GDICT_IS_VALID_STATUS_CODE (x)
Value:
(((x) > GDICT_STATUS_INVALID) && \
((x) <= GDICT_STATUS_NO_STRATEGIES_PRESENT))
Definition at line 76 of file gdict-utils.h.
Enumeration Type Documentation
GdictContextProp
enum GdictContextProp
Enumerator
GDICT_CONTEXT_PROP_FIRST
GDICT_CONTEXT_PROP_LOCAL_ONLY
GDICT_CONTEXT_PROP_LAST
Definition at line 34 of file gdict-utils.h.
GdictStatusCode
enum GdictStatusCode
Enumerator
GDICT_STATUS_INVALID
GDICT_STATUS_N_DATABASES_PRESENT
GDICT_STATUS_N_STRATEGIES_PRESENT
GDICT_STATUS_DATABASE_INFO
GDICT_STATUS_HELP_TEXT
GDICT_STATUS_SERVER_INFO
GDICT_STATUS_CHALLENGE
GDICT_STATUS_N_DEFINITIONS_RETRIEVED
GDICT_STATUS_WORD_DB_NAME
GDICT_STATUS_N_MATCHES_FOUND
GDICT_STATUS_CONNECT
GDICT_STATUS_QUIT
GDICT_STATUS_AUTH_OK
GDICT_STATUS_OK
GDICT_STATUS_SEND_RESPONSE
GDICT_STATUS_SERVER_DOWN
GDICT_STATUS_SHUTDOWN
GDICT_STATUS_BAD_COMMAND
GDICT_STATUS_BAD_PARAMETERS
GDICT_STATUS_COMMAND_NOT_IMPLEMENTED
GDICT_STATUS_PARAMETER_NOT_IMPLEMENTED
GDICT_STATUS_NO_ACCESS
GDICT_STATUS_USE_SHOW_INFO
GDICT_STATUS_UNKNOWN_MECHANISM
GDICT_STATUS_BAD_DATABASE
GDICT_STATUS_BAD_STRATEGY
GDICT_STATUS_NO_MATCH
GDICT_STATUS_NO_DATABASES_PRESENT
GDICT_STATUS_NO_STRATEGIES_PRESENT
Definition at line 41 of file gdict-utils.h.
Function Documentation
gdict_debug_init()
void gdict_debug_init (gint * argc, gchar *** argv)
gdict_debug_init: @argc: FIXME @argv: FIXME
FIXME
Since: 0.12
Definition at line 177 of file gdict-utils.c.
References error, FALSE, gdict_get_option_group(), NULL, and TRUE.
gdict_get_option_group()
GOptionGroup * gdict_get_option_group (void)
gdict_get_option_group:
FIXME
Return value: FIXME
Since: 0.12
Definition at line 148 of file gdict-utils.c.
References _, GETTEXT_PACKAGE, and NULL.
Referenced by gdict_debug_init(), and gdict_init().