MATE Desktop Environment: gdict-context.c File Reference
gdict-context.c File Reference
#include <glib/gi18n-lib.h>
#include "gdict-context.h"
#include "gdict-enum-types.h"
#include "gdict-utils.h"
#include "gdict-marshal.h"
#include "gdict-context-private.h"
#include "gdict-private.h"
Functions
GType gdict_context_get_type (void)
GQuark gdict_context_error_quark (void)
void gdict_context_set_local_only (GdictContext *context, gboolean local_only)
gboolean gdict_context_get_local_only (GdictContext *context)
gboolean gdict_context_lookup_databases (GdictContext *context, GError **error)
gboolean gdict_context_lookup_strategies (GdictContext *context, GError **error)
gboolean gdict_context_match_word (GdictContext *context, const gchar *database, const gchar *strategy, const gchar *word, GError **error)
gboolean gdict_context_define_word (GdictContext *context, const gchar *database, const gchar *word, GError **error)
GDICT_DEFINE_BOXED_TYPE (GdictDatabase, gdict_database)
GdictDatabase * _gdict_database_new (const gchar *name)
GdictDatabase * gdict_database_ref (GdictDatabase *db)
void gdict_database_unref (GdictDatabase *db)
const gchar * gdict_database_get_name (GdictDatabase *db)
const gchar * gdict_database_get_full_name (GdictDatabase *db)
GDICT_DEFINE_BOXED_TYPE (GdictStrategy, gdict_strategy)
GdictStrategy * _gdict_strategy_new (const gchar *name)
GdictStrategy * gdict_strategy_ref (GdictStrategy *strat)
void gdict_strategy_unref (GdictStrategy *strat)
const gchar * gdict_strategy_get_name (GdictStrategy *strat)
const gchar * gdict_strategy_get_description (GdictStrategy *strat)
GDICT_DEFINE_BOXED_TYPE (GdictMatch, gdict_match)
GdictMatch * _gdict_match_new (const gchar *word)
GdictMatch * gdict_match_ref (GdictMatch *match)
void gdict_match_unref (GdictMatch *match)
const gchar * gdict_match_get_word (GdictMatch *match)
const gchar * gdict_match_get_database (GdictMatch *match)
GDICT_DEFINE_BOXED_TYPE (GdictDefinition, gdict_definition)
GdictDefinition * _gdict_definition_new (gint total)
GdictDefinition * gdict_definition_ref (GdictDefinition *def)
void gdict_definition_unref (GdictDefinition *def)
gint gdict_definition_get_total (GdictDefinition *def)
const gchar * gdict_definition_get_word (GdictDefinition *def)
const gchar * gdict_definition_get_database (GdictDefinition *def)
const gchar * gdict_definition_get_text (GdictDefinition *def)
Function Documentation
_gdict_database_new()
GdictDatabase * _gdict_database_new (const gchar * name)
Definition at line 424 of file gdict-context.c.
References _GdictDatabase::full_name, _GdictDatabase::name, name, NULL, and _GdictDatabase::ref_count.
_gdict_definition_new()
GdictDefinition * _gdict_definition_new (gint total)
Definition at line 744 of file gdict-context.c.
References _GdictDefinition::database_full, _GdictDefinition::database_name, NULL, _GdictDefinition::ref_count, _GdictDefinition::total, and _GdictDefinition::word.
_gdict_match_new()
GdictMatch * _gdict_match_new (const gchar * word)
Definition at line 638 of file gdict-context.c.
References _GdictMatch::database, NULL, _GdictMatch::ref_count, and _GdictMatch::word.
_gdict_strategy_new()
GdictStrategy * _gdict_strategy_new (const gchar * name)
Definition at line 532 of file gdict-context.c.
References _GdictStrategy::description, _GdictStrategy::name, name, NULL, and _GdictStrategy::ref_count.
gdict_context_define_word()
gboolean gdict_context_define_word (GdictContext * context, const gchar * database, const gchar * word, GError ** error)
gdict_context_define_word: @context: a GdictContext @database: a database name to search into, or NULL for the default database @word: the word to search @error: return location for a #GError, or NULL
Query @context for a list of definitions of @word inside @database. Each time a new definition is found, the "definition-found" signal is fired.
Return value: TRUE if the query was successfully sent.
Since: 1.0
Definition at line 394 of file gdict-context.c.
References error, FALSE, GDICT_CONTEXT_GET_IFACE, GDICT_IS_CONTEXT, and NULL.
Referenced by gdict_defbox_lookup().
gdict_context_error_quark()
GQuark gdict_context_error_quark (void)
Definition at line 228 of file gdict-context.c.
gdict_context_get_local_only()
gboolean gdict_context_get_local_only (GdictContext * context)
gdict_context_get_local_only: @context: a GdictContext
Gets whether only local resources will be used when querying.
Return value: TRUE if only local resources will be used.
Since: 1.0
Definition at line 263 of file gdict-context.c.
References FALSE, GDICT_IS_CONTEXT, and NULL.
gdict_context_get_type()
GType gdict_context_get_type (void)
Definition at line 55 of file gdict-context.c.
References NULL.
gdict_context_lookup_databases()
gboolean gdict_context_lookup_databases (GdictContext * context, GError ** error)
gdict_context_lookup_databases: @context: a GdictContext @error: return location for a #GError, or NULL
Query @context for the list of databases available. Each time a database is found, the "database-found" signal is fired.
Return value: TRUE if the query was successfully started.
Since: 1.0
Definition at line 287 of file gdict-context.c.
References error, FALSE, GDICT_CONTEXT_GET_IFACE, and GDICT_IS_CONTEXT.
Referenced by gdict_database_chooser_refresh().
gdict_context_lookup_strategies()
gboolean gdict_context_lookup_strategies (GdictContext * context, GError ** error)
gdict_context_lookup_strategies: @context: a GdictContext @error: return location for a #GError, or NULL
Query @context for the list of matching strategies available. Each time a new strategy is found, the "strategy-found" signal is fired.
Return value: TRUE if the query was successfully started.
Since: 1.0
Definition at line 317 of file gdict-context.c.
References error, FALSE, GDICT_CONTEXT_GET_IFACE, and GDICT_IS_CONTEXT.
Referenced by gdict_strategy_chooser_refresh().
gdict_context_match_word()
gboolean gdict_context_match_word (GdictContext * context, const gchar * database, const gchar * strategy, const gchar * word, GError ** error)
gdict_context_match_word: @context: a GdictContext @database: a database name to search into, or NULL for the default database @strategy: a strategy name to use for matching, or NULL for the default strategy @word: the word to match @error: return location for a #GError, or NULL
Query @context for a list of word matching @word inside @database, using @strategy as a matching strategy. Each time a matching word is found, the "match-found" signal is fired.
Return value: TRUE if the query was successfully started.
Since: 1.0
Definition at line 353 of file gdict-context.c.
References error, FALSE, GDICT_CONTEXT_GET_IFACE, GDICT_IS_CONTEXT, and NULL.
Referenced by gdict_speller_match().
gdict_context_set_local_only()
void gdict_context_set_local_only (GdictContext * context, gboolean local_only)
gdict_context_set_local_only: @context: a GdictContext @local_only: TRUE if only local resources will be used
Sets whether only local resources will be used when querying for databases, strategies, matches or definitions.
Since: 1.0
Definition at line 244 of file gdict-context.c.
References GDICT_IS_CONTEXT, and NULL.
gdict_database_get_full_name()
const gchar * gdict_database_get_full_name (GdictDatabase * db)
gdict_database_get_full_name: @db: a GdictDatabase
Gets the full name of the database, suitable for display.
Return value: the full name of the database. The string is owned by the GdictDatabase object, and should never be modified or freed.
Since: 1.0
Definition at line 518 of file gdict-context.c.
References _GdictDatabase::full_name, and NULL.
gdict_database_get_name()
const gchar * gdict_database_get_name (GdictDatabase * db)
gdict_database_get_name: @db: a GdictDatabase
Gets the short name of the database, to be used with functions like gdict_context_match_word() or gdict_context_define_word().
Return value: the short name of the database. The string is owned by the GdictDatabase object, and should never be modified or freed.
Since: 1.0
Definition at line 499 of file gdict-context.c.
References _GdictDatabase::name, and NULL.
gdict_database_ref()
GdictDatabase * gdict_database_ref (GdictDatabase * db)
gdict_database_ref: @db: a GdictDatabase
Increases the reference count of @db by one.
Return value: @db with its reference count increased
Since: 1.0
Definition at line 449 of file gdict-context.c.
References NULL, and _GdictDatabase::ref_count.
gdict_database_unref()
void gdict_database_unref (GdictDatabase * db)
gdict_database_unref: @db: a GdictDatabase
Decreases the reference count of @db by one. If the reference count reaches zero, @db is destroyed.
Since: 1.0
Definition at line 470 of file gdict-context.c.
References _GdictDatabase::full_name, _GdictDatabase::name, NULL, and _GdictDatabase::ref_count.
GDICT_DEFINE_BOXED_TYPE() [1/4]
GDICT_DEFINE_BOXED_TYPE (GdictDatabase , gdict_database)
GDICT_DEFINE_BOXED_TYPE() [2/4]
GDICT_DEFINE_BOXED_TYPE (GdictDefinition , gdict_definition)
GDICT_DEFINE_BOXED_TYPE() [3/4]
GDICT_DEFINE_BOXED_TYPE (GdictMatch , gdict_match)
GDICT_DEFINE_BOXED_TYPE() [4/4]
GDICT_DEFINE_BOXED_TYPE (GdictStrategy , gdict_strategy)
gdict_definition_get_database()
const gchar * gdict_definition_get_database (GdictDefinition * def)
Definition at line 862 of file gdict-context.c.
References _GdictDefinition::database_full, and NULL.
gdict_definition_get_text()
const gchar * gdict_definition_get_text (GdictDefinition * def)
Definition at line 882 of file gdict-context.c.
References _GdictDefinition::definition, and NULL.
gdict_definition_get_total()
gint gdict_definition_get_total (GdictDefinition * def)
Definition at line 821 of file gdict-context.c.
References NULL, and _GdictDefinition::total.
gdict_definition_get_word()
const gchar * gdict_definition_get_word (GdictDefinition * def)
Definition at line 841 of file gdict-context.c.
References NULL, and _GdictDefinition::word.
gdict_definition_ref()
GdictDefinition * gdict_definition_ref (GdictDefinition * def)
Definition at line 771 of file gdict-context.c.
References NULL, and _GdictDefinition::ref_count.
gdict_definition_unref()
void gdict_definition_unref (GdictDefinition * def)
Definition at line 792 of file gdict-context.c.
References _GdictDefinition::database_full, _GdictDefinition::database_name, NULL, _GdictDefinition::ref_count, and _GdictDefinition::word.
gdict_match_get_database()
const gchar * gdict_match_get_database (GdictMatch * match)
gdict_match_get_database: @match: a GdictMatch
FIXME
Return value: FIXME
Since: 1.0
Definition at line 729 of file gdict-context.c.
References _GdictMatch::database, and NULL.
gdict_match_get_word()
const gchar * gdict_match_get_word (GdictMatch * match)
gdict_match_get_word: @match: a GdictMatch
FIXME
Return value: FIXME
Since: 1.0
Definition at line 711 of file gdict-context.c.
References NULL, and _GdictMatch::word.
gdict_match_ref()
GdictMatch * gdict_match_ref (GdictMatch * match)
gdict_match_ref: @match: a GdictMatch
FIXME
Return value: FIXME
Since: 1.0
Definition at line 663 of file gdict-context.c.
References NULL, and _GdictMatch::ref_count.
gdict_match_unref()
void gdict_match_unref (GdictMatch * match)
gdict_match_unref: @match: a GdictMatch
FIXME
Since: 1.0
Definition at line 683 of file gdict-context.c.
References _GdictMatch::database, NULL, _GdictMatch::ref_count, and _GdictMatch::word.
gdict_strategy_get_description()
const gchar * gdict_strategy_get_description (GdictStrategy * strat)
gdict_strategy_get_description: @strat: a GdictStrategy
FIXME
Return value: FIXME
Since: 1.0
Definition at line 624 of file gdict-context.c.
References _GdictStrategy::description, and NULL.
gdict_strategy_get_name()
const gchar * gdict_strategy_get_name (GdictStrategy * strat)
gdict_strategy_get_name: @strat: a GdictStrategy
FIXME
Return value: FIXME
Since: 1.0
Definition at line 606 of file gdict-context.c.
References _GdictStrategy::name, and NULL.
gdict_strategy_ref()
GdictStrategy * gdict_strategy_ref (GdictStrategy * strat)
gdict_strategy_ref: @strat: a GdictStrategy
Increases the reference count of @strat by one.
Return value: the GdictStrategy object with its reference count increased
Since: 1.0
Definition at line 558 of file gdict-context.c.
References NULL, and _GdictStrategy::ref_count.
gdict_strategy_unref()
void gdict_strategy_unref (GdictStrategy * strat)
gdict_strategy_unref: @strat: a GdictStrategy
Decreases the reference count of @strat by one. If the reference count reaches zero, the GdictStrategy object is freed.
Since: 1.0
Definition at line 579 of file gdict-context.c.
References _GdictStrategy::description, _GdictStrategy::name, NULL, and _GdictStrategy::ref_count.