MATE Desktop Environment: gdict-database-chooser.c File Reference
gdict-database-chooser.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include "gdict-database-chooser.h"
#include "gdict-utils.h"
#include "gdict-debug.h"
#include "gdict-private.h"
#include "gdict-enum-types.h"
#include "gdict-marshal.h"
Enumerations
enum { DATABASE_NAME , DATABASE_ERROR }
enum {
DB_COLUMN_TYPE , DB_COLUMN_NAME , DB_COLUMN_DESCRIPTION , DB_COLUMN_CURRENT ,
DB_N_COLUMNS
}
enum { PROP_0 , PROP_CONTEXT , PROP_COUNT }
enum { DATABASE_ACTIVATED , SELECTION_CHANGED , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (GdictDatabaseChooser, gdict_database_chooser, GTK_TYPE_BOX)
: the name of the activated database
GtkWidget * gdict_database_chooser_new (void)
GtkWidget * gdict_database_chooser_new_with_context (GdictContext *context)
GdictContext * gdict_database_chooser_get_context (GdictDatabaseChooser *chooser)
void gdict_database_chooser_set_context (GdictDatabaseChooser *chooser, GdictContext *context)
gchar ** gdict_database_chooser_get_databases (GdictDatabaseChooser *chooser, gsize *length)
gboolean gdict_database_chooser_has_database (GdictDatabaseChooser *chooser, const gchar *database)
gint gdict_database_chooser_count_databases (GdictDatabaseChooser *chooser)
void gdict_database_chooser_refresh (GdictDatabaseChooser *chooser)
void gdict_database_chooser_clear (GdictDatabaseChooser *chooser)
gboolean gdict_database_chooser_select_database (GdictDatabaseChooser *chooser, const gchar *db_name)
gboolean gdict_database_chooser_unselect_database (GdictDatabaseChooser *chooser, const gchar *db_name)
gboolean gdict_database_chooser_set_current_database (GdictDatabaseChooser *chooser, const gchar *db_name)
gchar * gdict_database_chooser_get_current_database (GdictDatabaseChooser *chooser)
GtkWidget * gdict_database_chooser_add_button (GdictDatabaseChooser *chooser, const gchar *button_text)
Variables
enum { ... } DBType
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_CONTEXT
PROP_COUNT
Definition at line 91 of file gdict-database-chooser.c.
anonymous enum
anonymous enum
Enumerator
DB_COLUMN_TYPE
DB_COLUMN_NAME
DB_COLUMN_DESCRIPTION
DB_COLUMN_CURRENT
DB_N_COLUMNS
Definition at line 81 of file gdict-database-chooser.c.
anonymous enum
anonymous enum
Enumerator
DATABASE_ACTIVATED
SELECTION_CHANGED
LAST_SIGNAL
Definition at line 99 of file gdict-database-chooser.c.
anonymous enum
anonymous enum
Enumerator
DATABASE_NAME
DATABASE_ERROR
Definition at line 75 of file gdict-database-chooser.c.
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (GdictDatabaseChooser , gdict_database_chooser , GTK_TYPE_BOX)
References GDICT_IS_DATABASE_CHOOSER.
gdict_database_chooser_add_button()
GtkWidget * gdict_database_chooser_add_button (GdictDatabaseChooser * chooser, const gchar * button_text)
gdict_database_chooser_add_button: @chooser: a GdictDatabase @button_text: text of the button
Adds a #GtkButton with @button_text to the button area on the bottom of @chooser. The @button_text can also be a stock ID.
Return value: the newly packed button.
Since: 0.10
Definition at line 1116 of file gdict-database-chooser.c.
References FALSE, GDICT_IS_DATABASE_CHOOSER, NULL, _GdictDatabaseChooser::priv, and TRUE.
gdict_database_chooser_clear()
void gdict_database_chooser_clear (GdictDatabaseChooser * chooser)
gdict_database_chooser_clear: @chooser: a GdictDatabaseChooser
Clears @chooser.
Since: 0.10
Definition at line 855 of file gdict-database-chooser.c.
References GDICT_IS_DATABASE_CHOOSER, NULL, and _GdictDatabaseChooser::priv.
Referenced by gdict_database_chooser_refresh().
gdict_database_chooser_count_databases()
gint gdict_database_chooser_count_databases (GdictDatabaseChooser * chooser)
gdict_database_chooser_count_databases: @chooser: a GdictDatabaseChooser
Returns the number of databases found.
Return value: the number of databases or -1 if no context is set
Since: 0.10
Definition at line 691 of file gdict-database-chooser.c.
References GDICT_IS_DATABASE_CHOOSER, and _GdictDatabaseChooser::priv.
gdict_database_chooser_get_context()
GdictContext * gdict_database_chooser_get_context (GdictDatabaseChooser * chooser)
gdict_database_chooser_get_context: @chooser: a GdictDatabaseChooser
Retrieves the GdictContext used by @chooser.
Return value: a GdictContext or NULL
Since: 0.10
Definition at line 549 of file gdict-database-chooser.c.
References GDICT_IS_DATABASE_CHOOSER, NULL, and _GdictDatabaseChooser::priv.
gdict_database_chooser_get_current_database()
gchar * gdict_database_chooser_get_current_database (GdictDatabaseChooser * chooser)
gdict_database_chooser_get_current_database: @chooser: a GdictDatabaseChooser
Retrieves the name of the currently selected database inside @chooser
Return value: the name of the selected database. Use g_free() on the returned string when done using it
Since: 0.10
Definition at line 1078 of file gdict-database-chooser.c.
References DB_COLUMN_NAME, GDICT_IS_DATABASE_CHOOSER, NULL, and _GdictDatabaseChooser::priv.
gdict_database_chooser_get_databases()
gchar ** gdict_database_chooser_get_databases (GdictDatabaseChooser * chooser, gsize * length)
gdict_database_chooser_get_databases: @chooser: a GdictDatabaseChooser @length: return location for the length of the returned vector
Gets the list of available database names.
Return value: a newly allocated, NULL terminated string vector containing database names. Use g_strfreev() to deallocate it.
Since: 0.10
Definition at line 591 of file gdict-database-chooser.c.
References DB_COLUMN_NAME, GDICT_IS_DATABASE_CHOOSER, NULL, and _GdictDatabaseChooser::priv.
gdict_database_chooser_has_database()
gboolean gdict_database_chooser_has_database (GdictDatabaseChooser * chooser, const gchar * database)
gdict_database_chooser_has_database: @chooser: a GdictDatabaseChooser @database: the name of a database
Checks whether the @chooser displays @database
Return value: TRUE if the search database name is present
Since: 0.10
Definition at line 641 of file gdict-database-chooser.c.
References DB_COLUMN_NAME, FALSE, GDICT_IS_DATABASE_CHOOSER, NULL, _GdictDatabaseChooser::priv, and TRUE.
gdict_database_chooser_new()
GtkWidget * gdict_database_chooser_new (void)
gdict_database_chooser_new:
Creates a new GdictDatabaseChooser widget. A Database chooser widget can be used to display the list of available databases on a dictionary source using the GdictContext representing it. After creation, the GdictContext can be set using gdict_database_chooser_set_context().
Return value: the newly created GdictDatabaseChooser widget.
Since: 0.10
Definition at line 512 of file gdict-database-chooser.c.
References GDICT_TYPE_DATABASE_CHOOSER, and NULL.
gdict_database_chooser_new_with_context()
GtkWidget * gdict_database_chooser_new_with_context (GdictContext * context)
gdict_database_chooser_new_with_context: @context: a GdictContext
Creates a new GdictDatabaseChooser, using @context as the representation of the dictionary source to query for the list of available databases.
Return value: the newly created GdictDatabaseChooser widget.
Since: 0.10
Definition at line 529 of file gdict-database-chooser.c.
References GDICT_IS_CONTEXT, GDICT_TYPE_DATABASE_CHOOSER, and NULL.
gdict_database_chooser_refresh()
void gdict_database_chooser_refresh (GdictDatabaseChooser * chooser)
gdict_database_chooser_refresh: @chooser: a GdictDatabaseChooser
Reloads the list of available databases.
Since: 0.10
Definition at line 786 of file gdict-database-chooser.c.
References _, DATABASE_ERROR, DB_COLUMN_DESCRIPTION, DB_COLUMN_NAME, DB_COLUMN_TYPE, gdict_context_lookup_databases(), gdict_database_chooser_clear(), GDICT_IS_DATABASE_CHOOSER, NULL, and _GdictDatabaseChooser::priv.
gdict_database_chooser_select_database()
gboolean gdict_database_chooser_select_database (GdictDatabaseChooser * chooser, const gchar * db_name)
gdict_database_chooser_select_database: @chooser: a GdictDatabaseChooser @db_name: name of the database to select
Selects the database with @db_name inside the @chooser widget.
Return value: TRUE if the database was found and selected
Since: 0.10
Definition at line 948 of file gdict-database-chooser.c.
References data, FALSE, GDICT_IS_DATABASE_CHOOSER, NULL, _GdictDatabaseChooser::priv, and TRUE.
gdict_database_chooser_set_context()
void gdict_database_chooser_set_context (GdictDatabaseChooser * chooser, GdictContext * context)
gdict_database_chooser_set_context: @chooser: a GdictDatabaseChooser @context: a GdictContext
Sets the GdictContext to be used to query a dictionary source for the list of available databases.
Since: 0.10
Definition at line 567 of file gdict-database-chooser.c.
References GDICT_IS_CONTEXT, GDICT_IS_DATABASE_CHOOSER, and NULL.
gdict_database_chooser_set_current_database()
gboolean gdict_database_chooser_set_current_database (GdictDatabaseChooser * chooser, const gchar * db_name)
gdict_database_chooser_set_current_database: @chooser: a GdictDatabaseChooser @db_name: the name of the database
Sets @db_name as the current database. This function will select and activate the corresponding row, if the database is found.
Return value: TRUE if the database was found and set
Since: 0.10
Definition at line 1031 of file gdict-database-chooser.c.
References data, FALSE, GDICT_IS_DATABASE_CHOOSER, NULL, _GdictDatabaseChooser::priv, and TRUE.
gdict_database_chooser_unselect_database()
gboolean gdict_database_chooser_unselect_database (GdictDatabaseChooser * chooser, const gchar * db_name)
gdict_database_chooser_unselect_database: @chooser: a GdictDatabaseChooser @db_name: name of the database to unselect
Unselects the database @db_name inside the @chooser widget
Return value: TRUE if the database was found and unselected
Since: 0.10
Definition at line 989 of file gdict-database-chooser.c.
References data, FALSE, GDICT_IS_DATABASE_CHOOSER, NULL, and _GdictDatabaseChooser::priv.
Variable Documentation
[]
enum { ... } DBType