MATE Desktop Environment: gdict-utils.c File Reference
gdict-utils.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <glib.h>
#include <glib/gi18n-lib.h>
#include <gtk/gtk.h>
#include "gdict-context-private.h"
#include "gdict-debug.h"
#include "gdict-utils.h"
#include "gdict-version.h"
#include "gdict-private.h"
Functions
GOptionGroup * gdict_get_option_group (void)
void gdict_debug_init (gint *argc, gchar ***argv)
gboolean gdict_check_version (guint required_major, guint required_minor, guint required_micro)
gboolean _gdict_has_ipv6 (void)
void _gdict_show_error_dialog (GtkWidget *widget, const gchar *title, const gchar *detail)
void _gdict_show_gerror_dialog (GtkWidget *widget, const gchar *title, GError *error)
Variables
guint gdict_major_version = GDICT_MAJOR_VERSION
guint gdict_minor_version = GDICT_MINOR_VERSION
guint gdict_micro_version = GDICT_MICRO_VERSION
guint gdict_debug_flags = 0
Function Documentation
_gdict_has_ipv6()
gboolean _gdict_has_ipv6 (void)
Definition at line 229 of file gdict-utils.c.
References FALSE, and TRUE.
_gdict_show_error_dialog()
void _gdict_show_error_dialog (GtkWidget * widget, const gchar * title, const gchar * detail)
gdict_show_error_dialog: @widget: the widget that emits the error @title: the primary error message @message: the secondary error message or NULL
Creates and shows an error dialog bound to @widget.
Since: 1.0
Definition at line 297 of file gdict-utils.c.
References NULL.
Referenced by gdict_defbox_lookup(), and gdict_speller_match().
_gdict_show_gerror_dialog()
void _gdict_show_gerror_dialog (GtkWidget * widget, const gchar * title, GError * error)
gdict_show_gerror_dialog: @widget: the widget that emits the error @title: the primary error message @error: a #GError
Creates and shows an error dialog bound to @widget, using @error to fill the secondary text of the message dialog with the error message. Also takes care of freeing @error.
Since: 1.0
Definition at line 320 of file gdict-utils.c.
References error, and NULL.
gdict_check_version()
gboolean gdict_check_version (guint required_major, guint required_minor, guint required_micro)
Definition at line 204 of file gdict-utils.c.
References FALSE, GDICT_MAJOR_VERSION, GDICT_MICRO_VERSION, GDICT_MINOR_VERSION, and TRUE.
gdict_debug_init()
void gdict_debug_init (gint * argc, gchar *** argv)
gdict_debug_init: @argc: FIXME @argv: FIXME
FIXME
Since: 0.12
Definition at line 177 of file gdict-utils.c.
References error, FALSE, gdict_get_option_group(), NULL, and TRUE.
gdict_get_option_group()
GOptionGroup * gdict_get_option_group (void)
gdict_get_option_group:
FIXME
Return value: FIXME
Since: 0.12
Definition at line 148 of file gdict-utils.c.
References _, GETTEXT_PACKAGE, and NULL.
Referenced by gdict_debug_init(), and gdict_init().
Variable Documentation
gdict_debug_flags
guint gdict_debug_flags = 0
Definition at line 51 of file gdict-utils.c.
gdict_major_version
guint gdict_major_version = GDICT_MAJOR_VERSION
Definition at line 47 of file gdict-utils.c.
gdict_micro_version
guint gdict_micro_version = GDICT_MICRO_VERSION
Definition at line 49 of file gdict-utils.c.
gdict_minor_version
guint gdict_minor_version = GDICT_MINOR_VERSION
Definition at line 48 of file gdict-utils.c.