MATE Desktop Environment: gdict-source-loader.h File Reference
gdict-source-loader.h File Reference
#include <glib-object.h>
#include "gdict-source.h"
Classes
struct _GdictSourceLoader
struct _GdictSourceLoaderClass
Macros
#define GDICT_TYPE_SOURCE_LOADER (gdict_source_loader_get_type ())
#define GDICT_SOURCE_LOADER(obj)
#define GDICT_IS_SOURCE_LOADER(obj)
#define GDICT_SOURCE_LOADER_CLASS(klass)
#define GDICT_IS_SOURCE_LOADER_CLASS(klass)
#define GDICT_SOURCE_LOADER_GET_CLASS(obj)
Typedefs
typedef struct _GdictSourceLoader GdictSourceLoader
typedef struct _GdictSourceLoaderClass GdictSourceLoaderClass
typedef struct _GdictSourceLoaderPrivate GdictSourceLoaderPrivate
Functions
GType gdict_source_loader_get_type (void)
GdictSourceLoader * gdict_source_loader_new (void)
void gdict_source_loader_update (GdictSourceLoader *loader)
void gdict_source_loader_add_search_path (GdictSourceLoader *loader, const gchar *path)
const GSList * gdict_source_loader_get_paths (GdictSourceLoader *loader)
gchar ** gdict_source_loader_get_names (GdictSourceLoader *loader, gsize *length) G_GNUC_MALLOC
const GSList * gdict_source_loader_get_sources (GdictSourceLoader *loader)
GdictSource * gdict_source_loader_get_source (GdictSourceLoader *loader, const gchar *name)
gboolean gdict_source_loader_has_source (GdictSourceLoader *loader, const gchar *source_name)
gboolean gdict_source_loader_remove_source (GdictSourceLoader *loader, const gchar *name)
Macro Definition Documentation
GDICT_IS_SOURCE_LOADER
#define GDICT_IS_SOURCE_LOADER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), GDICT_TYPE_SOURCE_LOADER))
Definition at line 30 of file gdict-source-loader.h.
Referenced by gdict_show_pref_dialog(), gdict_source_chooser_new_with_loader(), gdict_source_chooser_set_loader(), gdict_source_dialog_new(), gdict_source_loader_add_search_path(), gdict_source_loader_get_names(), gdict_source_loader_get_paths(), gdict_source_loader_get_source(), gdict_source_loader_get_sources(), gdict_source_loader_has_source(), gdict_source_loader_remove_source(), gdict_source_loader_update(), and gdict_window_new().
GDICT_IS_SOURCE_LOADER_CLASS
#define GDICT_IS_SOURCE_LOADER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), GDICT_TYPE_SOURCE_LOADER))
Definition at line 32 of file gdict-source-loader.h.
GDICT_SOURCE_LOADER
#define GDICT_SOURCE_LOADER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), GDICT_TYPE_SOURCE_LOADER, GdictSourceLoader))
Definition at line 29 of file gdict-source-loader.h.
Referenced by G_DEFINE_TYPE_WITH_PRIVATE().
GDICT_SOURCE_LOADER_CLASS
#define GDICT_SOURCE_LOADER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), GDICT_TYPE_SOURCE_LOADER, GdictSourceLoaderClass))
Definition at line 31 of file gdict-source-loader.h.
GDICT_SOURCE_LOADER_GET_CLASS
#define GDICT_SOURCE_LOADER_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), GDICT_TYPE_SOURCE_LOADER, GdictSourceLoaderClass))
Definition at line 33 of file gdict-source-loader.h.
GDICT_TYPE_SOURCE_LOADER
#define GDICT_TYPE_SOURCE_LOADER (gdict_source_loader_get_type ())
Definition at line 28 of file gdict-source-loader.h.
Referenced by gdict_source_loader_new().
Typedef Documentation
GdictSourceLoader
typedef struct _GdictSourceLoader GdictSourceLoader
Definition at line 35 of file gdict-source-loader.h.
GdictSourceLoaderClass
typedef struct _GdictSourceLoaderClass GdictSourceLoaderClass
Definition at line 36 of file gdict-source-loader.h.
GdictSourceLoaderPrivate
typedef struct _GdictSourceLoaderPrivate GdictSourceLoaderPrivate
Definition at line 37 of file gdict-source-loader.h.
Function Documentation
gdict_source_loader_add_search_path()
void gdict_source_loader_add_search_path (GdictSourceLoader * loader, const gchar * path)
gdict_source_loader_add_search_path: @loader: a GdictSourceLoader @path: a path to be added to the search path list
Adds @path to the search paths list of @loader.
Since: 1.0
Definition at line 262 of file gdict-source-loader.c.
References GDICT_IS_SOURCE_LOADER, NULL, _GdictSourceLoader::priv, and TRUE.
Referenced by gdict_init().
gdict_source_loader_get_names()
gchar ** gdict_source_loader_get_names (GdictSourceLoader * loader, gsize * length)
gdict_source_loader_get_names: @loader: a GdictSourceLoader @length: return location for the number of source names, or NULL
Retrieves the list of dictionary source names available into the search paths of @loader.
Return value: a newly allocated, NULL terminated array of strings. You should free the returned string array with g_strfreev()
Since: 1.0
Definition at line 411 of file gdict-source-loader.c.
References GDICT_IS_SOURCE_LOADER, GDICT_SOURCE, gdict_source_get_name(), NULL, and _GdictSourceLoader::priv.
Referenced by gdict_source_chooser_get_sources().
gdict_source_loader_get_paths()
const GSList * gdict_source_loader_get_paths (GdictSourceLoader * loader)
gdict_source_loader_get_paths: @loader: a GdictSourceLoader
Gets the list of paths used by @loader to search for dictionary source files.
Return value: a list containing the paths. The returned list is owned by the GdictSourceLoader object and should never be free or modified.
Since: 1.0
Definition at line 292 of file gdict-source-loader.c.
References GDICT_IS_SOURCE_LOADER, NULL, and _GdictSourceLoader::priv.
gdict_source_loader_get_source()
GdictSource * gdict_source_loader_get_source (GdictSourceLoader * loader, const gchar * name)
Definition at line 481 of file gdict-source-loader.c.
References GDICT_IS_SOURCE_LOADER, name, NULL, and _GdictSourceLoader::priv.
Referenced by gdict_window_new().
gdict_source_loader_get_sources()
const GSList * gdict_source_loader_get_sources (GdictSourceLoader * loader)
gdict_source_loader_get_sources: @loader: a GdictSourceLoader
Retrieves the list of dictionary sources available into the search paths of @loader, in form of GdictSource objects.
Return value: a list of GdictSource objects. The returned list is owned by the GdictSourceLoader object, and should never be freed or modified.
Since: 1.0
Definition at line 456 of file gdict-source-loader.c.
References GDICT_IS_SOURCE_LOADER, NULL, and _GdictSourceLoader::priv.
Referenced by gdict_source_chooser_refresh().
gdict_source_loader_get_type()
GType gdict_source_loader_get_type (void)
References name.
gdict_source_loader_has_source()
gboolean gdict_source_loader_has_source (GdictSourceLoader * loader, const gchar * source_name)
gdict_source_loader_has_source: @loader: a GdictSourceLoader @source_name: the name of a dictionary source
Checks whether @loader has a dictionary source with name @source_name.
Return value: TRUE if the dictionary source is known
Since: 0.12
Definition at line 572 of file gdict-source-loader.c.
References FALSE, GDICT_IS_SOURCE_LOADER, NULL, and _GdictSourceLoader::priv.
Referenced by gdict_source_chooser_has_source().
gdict_source_loader_new()
GdictSourceLoader * gdict_source_loader_new (void)
gdict_source_loader_new:
Creates a new GdictSourceLoader object. This object is used to search into a list of paths for dictionary source files. See GdictSource for more informations about the format of dictionary source files.
Return value: a new GdictSourceLoader object
Since: 1.0
Definition at line 231 of file gdict-source-loader.c.
References GDICT_TYPE_SOURCE_LOADER, and NULL.
Referenced by gdict_init().
gdict_source_loader_remove_source()
gboolean gdict_source_loader_remove_source (GdictSourceLoader * loader, const gchar * name)
Definition at line 512 of file gdict-source-loader.c.
References FALSE, GDICT_IS_SOURCE_LOADER, GDICT_SOURCE, gdict_source_get_name(), name, NULL, _GdictSourceLoader::priv, and TRUE.
gdict_source_loader_update()
void gdict_source_loader_update (GdictSourceLoader * loader)
gdict_source_loader_update: @loader: a GdictSourceLoader
Queue an update of the sources inside @loader.
Since: 1.0
Definition at line 245 of file gdict-source-loader.c.
References GDICT_IS_SOURCE_LOADER, _GdictSourceLoader::priv, and TRUE.