MATE Desktop Environment: gf-sn-watcher-v0-gen.c File Reference
gf-sn-watcher-v0-gen.c File Reference
#include "gf-sn-watcher-v0-gen.h"
#include <string.h>
Macros
#define g_marshal_value_peek_boolean(v)
#define g_marshal_value_peek_char(v)
#define g_marshal_value_peek_uchar(v)
#define g_marshal_value_peek_int(v)
#define g_marshal_value_peek_uint(v)
#define g_marshal_value_peek_long(v)
#define g_marshal_value_peek_ulong(v)
#define g_marshal_value_peek_int64(v)
#define g_marshal_value_peek_uint64(v)
#define g_marshal_value_peek_enum(v)
#define g_marshal_value_peek_flags(v)
#define g_marshal_value_peek_float(v)
#define g_marshal_value_peek_double(v)
#define g_marshal_value_peek_string(v)
#define g_marshal_value_peek_param(v)
#define g_marshal_value_peek_boxed(v)
#define g_marshal_value_peek_pointer(v)
#define g_marshal_value_peek_object(v)
#define g_marshal_value_peek_variant(v)
Typedefs
typedef GfSnWatcherV0GenIface GfSnWatcherV0GenInterface
Enumerations
enum { GF__SN_WATCHER_V0_GEN_ITEM_REGISTERED , GF__SN_WATCHER_V0_GEN_ITEM_UNREGISTERED , GF__SN_WATCHER_V0_GEN_HOST_REGISTERED }
Functions
GDBusInterfaceInfo * gf_sn_watcher_v0_gen_interface_info (void)
guint gf_sn_watcher_v0_gen_override_properties (GObjectClass *klass, guint property_id_begin)
const gchar *const * gf_sn_watcher_v0_gen_get_registered_items (GfSnWatcherV0Gen *object)
gchar ** gf_sn_watcher_v0_gen_dup_registered_items (GfSnWatcherV0Gen *object)
void gf_sn_watcher_v0_gen_set_registered_items (GfSnWatcherV0Gen *object, const gchar *const *value)
gboolean gf_sn_watcher_v0_gen_get_is_host_registered (GfSnWatcherV0Gen *object)
void gf_sn_watcher_v0_gen_set_is_host_registered (GfSnWatcherV0Gen *object, gboolean value)
gint gf_sn_watcher_v0_gen_get_protocol_version (GfSnWatcherV0Gen *object)
void gf_sn_watcher_v0_gen_set_protocol_version (GfSnWatcherV0Gen *object, gint value)
void gf_sn_watcher_v0_gen_emit_item_registered (GfSnWatcherV0Gen *object, const gchar *arg_service)
void gf_sn_watcher_v0_gen_emit_item_unregistered (GfSnWatcherV0Gen *object, const gchar *arg_service)
void gf_sn_watcher_v0_gen_emit_host_registered (GfSnWatcherV0Gen *object)
void gf_sn_watcher_v0_gen_call_register_item (GfSnWatcherV0Gen *proxy, const gchar *arg_service, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean gf_sn_watcher_v0_gen_call_register_item_finish (GfSnWatcherV0Gen *proxy, GAsyncResult *res, GError **error)
gboolean gf_sn_watcher_v0_gen_call_register_item_sync (GfSnWatcherV0Gen *proxy, const gchar *arg_service, GCancellable *cancellable, GError **error)
void gf_sn_watcher_v0_gen_call_register_host (GfSnWatcherV0Gen *proxy, const gchar *arg_service, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean gf_sn_watcher_v0_gen_call_register_host_finish (GfSnWatcherV0Gen *proxy, GAsyncResult *res, GError **error)
gboolean gf_sn_watcher_v0_gen_call_register_host_sync (GfSnWatcherV0Gen *proxy, const gchar *arg_service, GCancellable *cancellable, GError **error)
void gf_sn_watcher_v0_gen_complete_register_item (GfSnWatcherV0Gen *object G_GNUC_UNUSED, GDBusMethodInvocation *invocation)
void gf_sn_watcher_v0_gen_complete_register_host (GfSnWatcherV0Gen *object G_GNUC_UNUSED, GDBusMethodInvocation *invocation)
G_DEFINE_TYPE_WITH_CODE (GfSnWatcherV0GenProxy, gf_sn_watcher_v0_gen_proxy, G_TYPE_DBUS_PROXY, G_IMPLEMENT_INTERFACE(GF_TYPE_SN_WATCHER_V0_GEN, gf_sn_watcher_v0_gen_proxy_iface_init))
: (nullable): A bus name (well-known or unique) or NULL if @connection is not a message bus connection.
gf_sn_watcher_v0_gen_proxy_new_sync: @connection: A #GDBusConnection. @flags: Flags from the #GDBusProxyFlags enumeration.
@object_path: An object path. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL
Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-kde-StatusNotifierWatcher.top_of_page">org.kde.StatusNotifierWatcher</link>. See g_dbus_proxy_new_sync() for more details.
The calling thread is blocked until a reply is received.
See gf_sn_watcher_v0_gen_proxy_new() for the asynchronous version of this constructor.
Returns: (transfer full) (type GfSnWatcherV0GenProxy): The constructed proxy object or NULL if @error is set.
void gf_sn_watcher_v0_gen_proxy_new (GDBusConnection *connection, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
GfSnWatcherV0Gen * gf_sn_watcher_v0_gen_proxy_new_finish (GAsyncResult *res, GError **error)
GfSnWatcherV0Gen * gf_sn_watcher_v0_gen_proxy_new_sync (GDBusConnection *connection, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GError **error)
: A bus name (well-known or unique).
gf_sn_watcher_v0_gen_proxy_new_for_bus_sync: @bus_type: A #GBusType. @flags: Flags from the #GDBusProxyFlags enumeration.
@object_path: An object path. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL
Like gf_sn_watcher_v0_gen_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
The calling thread is blocked until a reply is received.
See gf_sn_watcher_v0_gen_proxy_new_for_bus() for the asynchronous version of this constructor.
Returns: (transfer full) (type GfSnWatcherV0GenProxy): The constructed proxy object or NULL if @error is set.
void gf_sn_watcher_v0_gen_proxy_new_for_bus (GBusType bus_type, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
GfSnWatcherV0Gen * gf_sn_watcher_v0_gen_proxy_new_for_bus_finish (GAsyncResult *res, GError **error)
GfSnWatcherV0Gen * gf_sn_watcher_v0_gen_proxy_new_for_bus_sync (GBusType bus_type, GDBusProxyFlags flags, const gchar *name, const gchar *object_path, GCancellable *cancellable, GError **error)
G_DEFINE_TYPE_WITH_CODE (GfSnWatcherV0GenSkeleton, gf_sn_watcher_v0_gen_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON, G_IMPLEMENT_INTERFACE(GF_TYPE_SN_WATCHER_V0_GEN, gf_sn_watcher_v0_gen_skeleton_iface_init))
GfSnWatcherV0Gen * gf_sn_watcher_v0_gen_skeleton_new (void)
Macro Definition Documentation
g_marshal_value_peek_boolean
#define g_marshal_value_peek_boolean (v)
Value:
(v)->data[0].v_int
Definition at line 45 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_boxed
#define g_marshal_value_peek_boxed (v)
Value:
(v)->data[0].v_pointer
Definition at line 60 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_char
#define g_marshal_value_peek_char (v)
Value:
(v)->data[0].v_int
Definition at line 46 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_double
#define g_marshal_value_peek_double (v)
Value:
(v)->data[0].v_double
Definition at line 57 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_enum
#define g_marshal_value_peek_enum (v)
Value:
(v)->data[0].v_long
Definition at line 54 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_flags
#define g_marshal_value_peek_flags (v)
Value:
(v)->data[0].v_ulong
Definition at line 55 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_float
#define g_marshal_value_peek_float (v)
Value:
(v)->data[0].v_float
Definition at line 56 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_int
#define g_marshal_value_peek_int (v)
Value:
(v)->data[0].v_int
Definition at line 48 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_int64
#define g_marshal_value_peek_int64 (v)
Value:
(v)->data[0].v_int64
Definition at line 52 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_long
#define g_marshal_value_peek_long (v)
Value:
(v)->data[0].v_long
Definition at line 50 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_object
#define g_marshal_value_peek_object (v)
Value:
(v)->data[0].v_pointer
Definition at line 62 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_param
#define g_marshal_value_peek_param (v)
Value:
(v)->data[0].v_pointer
Definition at line 59 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_pointer
#define g_marshal_value_peek_pointer (v)
Value:
(v)->data[0].v_pointer
Definition at line 61 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_string
#define g_marshal_value_peek_string (v)
Value:
(v)->data[0].v_pointer
Definition at line 58 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_uchar
#define g_marshal_value_peek_uchar (v)
Value:
(v)->data[0].v_uint
Definition at line 47 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_uint
#define g_marshal_value_peek_uint (v)
Value:
(v)->data[0].v_uint
Definition at line 49 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_uint64
#define g_marshal_value_peek_uint64 (v)
Value:
(v)->data[0].v_uint64
Definition at line 53 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_ulong
#define g_marshal_value_peek_ulong (v)
Value:
(v)->data[0].v_ulong
Definition at line 51 of file gf-sn-watcher-v0-gen.c.
g_marshal_value_peek_variant
#define g_marshal_value_peek_variant (v)
Value:
(v)->data[0].v_pointer
Definition at line 63 of file gf-sn-watcher-v0-gen.c.
Typedef Documentation
GfSnWatcherV0GenInterface
typedef GfSnWatcherV0GenIface GfSnWatcherV0GenInterface
GfSnWatcherV0Gen:
Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-kde-StatusNotifierWatcher.top_of_page">org.kde.StatusNotifierWatcher</link>. GfSnWatcherV0GenIface: @parent_iface: The parent interface. @handle_register_host: Handler for the #GfSnWatcherV0Gen::handle-register-host signal. @handle_register_item: Handler for the #GfSnWatcherV0Gen::handle-register-item signal. @get_is_host_registered: Getter for the GfSnWatcherV0Gen:is-host-registered property. @get_protocol_version: Getter for the GfSnWatcherV0Gen:protocol-version property. @get_registered_items: Getter for the GfSnWatcherV0Gen:registered-items property. @host_registered: Handler for the #GfSnWatcherV0Gen::host-registered signal. @item_registered: Handler for the #GfSnWatcherV0Gen::item-registered signal. @item_unregistered: Handler for the #GfSnWatcherV0Gen::item-unregistered signal.
Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-kde-StatusNotifierWatcher.top_of_page">org.kde.StatusNotifierWatcher</link>.
Definition at line 595 of file gf-sn-watcher-v0-gen.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
SECTION:GfSnWatcherV0Gen @title: GfSnWatcherV0Gen @short_description: Generated C code for the org.kde.StatusNotifierWatcher D-Bus interface
This section contains code for working with the <link linkend="gdbus-interface-org-kde-StatusNotifierWatcher.top_of_page">org.kde.StatusNotifierWatcher</link> D-Bus interface in C.
Enumerator
GF__SN_WATCHER_V0_GEN_ITEM_REGISTERED
GF__SN_WATCHER_V0_GEN_ITEM_UNREGISTERED
GF__SN_WATCHER_V0_GEN_HOST_REGISTERED
Definition at line 258 of file gf-sn-watcher-v0-gen.c.
Function Documentation
G_DEFINE_TYPE_WITH_CODE() [1/2]
G_DEFINE_TYPE_WITH_CODE (GfSnWatcherV0GenProxy , gf_sn_watcher_v0_gen_proxy , G_TYPE_DBUS_PROXY , G_IMPLEMENT_INTERFACE(GF_TYPE_SN_WATCHER_V0_GEN, gf_sn_watcher_v0_gen_proxy_iface_init))
Definition at line 1155 of file gf-sn-watcher-v0-gen.c.
References G_OBJECT_CLASS(), GF_SN_WATCHER_V0_GEN_PROXY, GF_TYPE_SN_WATCHER_V0_GEN, and proxy.
G_DEFINE_TYPE_WITH_CODE() [2/2]
G_DEFINE_TYPE_WITH_CODE (GfSnWatcherV0GenSkeleton , gf_sn_watcher_v0_gen_skeleton , G_TYPE_DBUS_INTERFACE_SKELETON , G_IMPLEMENT_INTERFACE(GF_TYPE_SN_WATCHER_V0_GEN, gf_sn_watcher_v0_gen_skeleton_iface_init))
Definition at line 1880 of file gf-sn-watcher-v0-gen.c.
References G_OBJECT_CLASS(), GF_SN_WATCHER_V0_GEN_SKELETON, GF_TYPE_SN_WATCHER_V0_GEN, NULL, and _GfSnWatcherV0GenSkeleton::priv.
gf_sn_watcher_v0_gen_call_register_host()
void gf_sn_watcher_v0_gen_call_register_host (GfSnWatcherV0Gen * proxy, const gchar * arg_service, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
gf_sn_watcher_v0_gen_call_register_host: @proxy: A GfSnWatcherV0GenProxy. @arg_service: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @callback: A #GAsyncReadyCallback to call when the request is satisfied or NULL. @user_data: User data to pass to @callback.
Asynchronously invokes the <link linkend="gdbus-method-org-kde-StatusNotifierWatcher.RegisterStatusNotifierHost">RegisterStatusNotifierHost()</link> D-Bus method on @proxy. When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()). You can then call gf_sn_watcher_v0_gen_call_register_host_finish() to get the result of the operation.
See gf_sn_watcher_v0_gen_call_register_host_sync() for the synchronous, blocking version of this method.
Definition at line 1013 of file gf-sn-watcher-v0-gen.c.
References proxy, and user_data.
gf_sn_watcher_v0_gen_call_register_host_finish()
gboolean gf_sn_watcher_v0_gen_call_register_host_finish (GfSnWatcherV0Gen * proxy, GAsyncResult * res, GError ** error)
gf_sn_watcher_v0_gen_call_register_host_finish: @proxy: A GfSnWatcherV0GenProxy. @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gf_sn_watcher_v0_gen_call_register_host(). @error: Return location for error or NULL.
Finishes an operation started with gf_sn_watcher_v0_gen_call_register_host().
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 1042 of file gf-sn-watcher-v0-gen.c.
References error, NULL, and proxy.
gf_sn_watcher_v0_gen_call_register_host_sync()
gboolean gf_sn_watcher_v0_gen_call_register_host_sync (GfSnWatcherV0Gen * proxy, const gchar * arg_service, GCancellable * cancellable, GError ** error)
gf_sn_watcher_v0_gen_call_register_host_sync: @proxy: A GfSnWatcherV0GenProxy. @arg_service: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL.
Synchronously invokes the <link linkend="gdbus-method-org-kde-StatusNotifierWatcher.RegisterStatusNotifierHost">RegisterStatusNotifierHost()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
See gf_sn_watcher_v0_gen_call_register_host() for the asynchronous version of this method.
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 1072 of file gf-sn-watcher-v0-gen.c.
References error, NULL, and proxy.
gf_sn_watcher_v0_gen_call_register_item()
void gf_sn_watcher_v0_gen_call_register_item (GfSnWatcherV0Gen * proxy, const gchar * arg_service, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
gf_sn_watcher_v0_gen_call_register_item: @proxy: A GfSnWatcherV0GenProxy. @arg_service: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @callback: A #GAsyncReadyCallback to call when the request is satisfied or NULL. @user_data: User data to pass to @callback.
Asynchronously invokes the <link linkend="gdbus-method-org-kde-StatusNotifierWatcher.RegisterStatusNotifierItem">RegisterStatusNotifierItem()</link> D-Bus method on @proxy. When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()). You can then call gf_sn_watcher_v0_gen_call_register_item_finish() to get the result of the operation.
See gf_sn_watcher_v0_gen_call_register_item_sync() for the synchronous, blocking version of this method.
Definition at line 915 of file gf-sn-watcher-v0-gen.c.
References proxy, and user_data.
gf_sn_watcher_v0_gen_call_register_item_finish()
gboolean gf_sn_watcher_v0_gen_call_register_item_finish (GfSnWatcherV0Gen * proxy, GAsyncResult * res, GError ** error)
gf_sn_watcher_v0_gen_call_register_item_finish: @proxy: A GfSnWatcherV0GenProxy. @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gf_sn_watcher_v0_gen_call_register_item(). @error: Return location for error or NULL.
Finishes an operation started with gf_sn_watcher_v0_gen_call_register_item().
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 944 of file gf-sn-watcher-v0-gen.c.
References error, NULL, and proxy.
gf_sn_watcher_v0_gen_call_register_item_sync()
gboolean gf_sn_watcher_v0_gen_call_register_item_sync (GfSnWatcherV0Gen * proxy, const gchar * arg_service, GCancellable * cancellable, GError ** error)
gf_sn_watcher_v0_gen_call_register_item_sync: @proxy: A GfSnWatcherV0GenProxy. @arg_service: Argument to pass with the method invocation. @cancellable: (nullable): A #GCancellable or NULL. @error: Return location for error or NULL.
Synchronously invokes the <link linkend="gdbus-method-org-kde-StatusNotifierWatcher.RegisterStatusNotifierItem">RegisterStatusNotifierItem()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
See gf_sn_watcher_v0_gen_call_register_item() for the asynchronous version of this method.
Returns: (skip): TRUE if the call succeeded, FALSE if @error is set.
Definition at line 974 of file gf-sn-watcher-v0-gen.c.
References error, NULL, and proxy.
gf_sn_watcher_v0_gen_complete_register_host()
void gf_sn_watcher_v0_gen_complete_register_host (GfSnWatcherV0Gen *object G_GNUC_UNUSED, GDBusMethodInvocation * invocation)
gf_sn_watcher_v0_gen_complete_register_host: @object: A GfSnWatcherV0Gen. @invocation: (transfer full): A #GDBusMethodInvocation.
Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-kde-StatusNotifierWatcher.RegisterStatusNotifierHost">RegisterStatusNotifierHost()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
This method will free @invocation, you cannot use it afterwards.
Definition at line 1124 of file gf-sn-watcher-v0-gen.c.
gf_sn_watcher_v0_gen_complete_register_item()
void gf_sn_watcher_v0_gen_complete_register_item (GfSnWatcherV0Gen *object G_GNUC_UNUSED, GDBusMethodInvocation * invocation)
gf_sn_watcher_v0_gen_complete_register_item: @object: A GfSnWatcherV0Gen. @invocation: (transfer full): A #GDBusMethodInvocation.
Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-kde-StatusNotifierWatcher.RegisterStatusNotifierItem">RegisterStatusNotifierItem()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
This method will free @invocation, you cannot use it afterwards.
Definition at line 1106 of file gf-sn-watcher-v0-gen.c.
gf_sn_watcher_v0_gen_dup_registered_items()
gchar ** gf_sn_watcher_v0_gen_dup_registered_items (GfSnWatcherV0Gen * object)
gf_sn_watcher_v0_gen_dup_registered_items: (skip) @object: A GfSnWatcherV0Gen.
Gets a copy of the <link linkend="gdbus-property-org-kde-StatusNotifierWatcher.RegisteredStatusNotifierItems">"RegisteredStatusNotifierItems"</link> D-Bus property.
Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
Returns: (transfer full) (nullable): The property value or NULL if the property is not set. The returned value should be freed with g_strfreev().
Definition at line 769 of file gf-sn-watcher-v0-gen.c.
References NULL.
gf_sn_watcher_v0_gen_emit_host_registered()
void gf_sn_watcher_v0_gen_emit_host_registered (GfSnWatcherV0Gen * object)
gf_sn_watcher_v0_gen_emit_host_registered: @object: A GfSnWatcherV0Gen.
Emits the <link linkend="gdbus-signal-org-kde-StatusNotifierWatcher.StatusNotifierHostRegistered">"StatusNotifierHostRegistered"</link> D-Bus signal.
Definition at line 894 of file gf-sn-watcher-v0-gen.c.
References GF__SN_WATCHER_V0_GEN_HOST_REGISTERED.
gf_sn_watcher_v0_gen_emit_item_registered()
void gf_sn_watcher_v0_gen_emit_item_registered (GfSnWatcherV0Gen * object, const gchar * arg_service)
gf_sn_watcher_v0_gen_emit_item_registered: @object: A GfSnWatcherV0Gen. @arg_service: Argument to pass with the signal.
Emits the <link linkend="gdbus-signal-org-kde-StatusNotifierWatcher.StatusNotifierItemRegistered">"StatusNotifierItemRegistered"</link> D-Bus signal.
Definition at line 865 of file gf-sn-watcher-v0-gen.c.
References GF__SN_WATCHER_V0_GEN_ITEM_REGISTERED.
gf_sn_watcher_v0_gen_emit_item_unregistered()
void gf_sn_watcher_v0_gen_emit_item_unregistered (GfSnWatcherV0Gen * object, const gchar * arg_service)
gf_sn_watcher_v0_gen_emit_item_unregistered: @object: A GfSnWatcherV0Gen. @arg_service: Argument to pass with the signal.
Emits the <link linkend="gdbus-signal-org-kde-StatusNotifierWatcher.StatusNotifierItemUnregistered">"StatusNotifierItemUnregistered"</link> D-Bus signal.
Definition at line 880 of file gf-sn-watcher-v0-gen.c.
References GF__SN_WATCHER_V0_GEN_ITEM_UNREGISTERED.
gf_sn_watcher_v0_gen_get_is_host_registered()
gboolean gf_sn_watcher_v0_gen_get_is_host_registered (GfSnWatcherV0Gen * object)
gf_sn_watcher_v0_gen_get_is_host_registered: (skip) @object: A GfSnWatcherV0Gen.
Gets the value of the <link linkend="gdbus-property-org-kde-StatusNotifierWatcher.IsStatusNotifierHostRegistered">"IsStatusNotifierHostRegistered"</link> D-Bus property.
Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
Returns: The property value.
Definition at line 802 of file gf-sn-watcher-v0-gen.c.
References FALSE, GF_IS_SN_WATCHER_V0_GEN, and GF_SN_WATCHER_V0_GEN_GET_IFACE.
gf_sn_watcher_v0_gen_get_protocol_version()
gint gf_sn_watcher_v0_gen_get_protocol_version (GfSnWatcherV0Gen * object)
gf_sn_watcher_v0_gen_get_protocol_version: (skip) @object: A GfSnWatcherV0Gen.
Gets the value of the <link linkend="gdbus-property-org-kde-StatusNotifierWatcher.ProtocolVersion">"ProtocolVersion"</link> D-Bus property.
Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
Returns: The property value.
Definition at line 835 of file gf-sn-watcher-v0-gen.c.
References GF_IS_SN_WATCHER_V0_GEN, and GF_SN_WATCHER_V0_GEN_GET_IFACE.
gf_sn_watcher_v0_gen_get_registered_items()
const gchar *const * gf_sn_watcher_v0_gen_get_registered_items (GfSnWatcherV0Gen * object)
gf_sn_watcher_v0_gen_get_registered_items: (skip) @object: A GfSnWatcherV0Gen.
Gets the value of the <link linkend="gdbus-property-org-kde-StatusNotifierWatcher.RegisteredStatusNotifierItems">"RegisteredStatusNotifierItems"</link> D-Bus property.
Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use gf_sn_watcher_v0_gen_dup_registered_items() if on another thread.
Returns: (transfer none) (nullable): The property value or NULL if the property is not set. Do not free the returned value, it belongs to @object.
Definition at line 751 of file gf-sn-watcher-v0-gen.c.
References GF_IS_SN_WATCHER_V0_GEN, GF_SN_WATCHER_V0_GEN_GET_IFACE, and NULL.
gf_sn_watcher_v0_gen_interface_info()
GDBusInterfaceInfo * gf_sn_watcher_v0_gen_interface_info (void)
gf_sn_watcher_v0_gen_interface_info:
Gets a machine-readable description of the <link linkend="gdbus-interface-org-kde-StatusNotifierWatcher.top_of_page">org.kde.StatusNotifierWatcher</link> D-Bus interface.
Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
Definition at line 483 of file gf-sn-watcher-v0-gen.c.
gf_sn_watcher_v0_gen_override_properties()
guint gf_sn_watcher_v0_gen_override_properties (GObjectClass * klass, guint property_id_begin)
gf_sn_watcher_v0_gen_override_properties: @klass: The class structure for a #GObject derived class. @property_id_begin: The property id to assign to the first overridden property.
Overrides all #GObject properties in the GfSnWatcherV0Gen interface for a concrete class. The properties are overridden in the order they are defined.
Returns: The last property id.
Definition at line 499 of file gf-sn-watcher-v0-gen.c.
gf_sn_watcher_v0_gen_proxy_new()
void gf_sn_watcher_v0_gen_proxy_new (GDBusConnection * connection, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 1418 of file gf-sn-watcher-v0-gen.c.
References connection, GF_TYPE_SN_WATCHER_V0_GEN_PROXY, name, NULL, and user_data.
gf_sn_watcher_v0_gen_proxy_new_finish()
GfSnWatcherV0Gen * gf_sn_watcher_v0_gen_proxy_new_finish (GAsyncResult * res, GError ** error)
gf_sn_watcher_v0_gen_proxy_new_finish: @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gf_sn_watcher_v0_gen_proxy_new(). @error: Return location for error or NULL
Finishes an operation started with gf_sn_watcher_v0_gen_proxy_new().
Returns: (transfer full) (type GfSnWatcherV0GenProxy): The constructed proxy object or NULL if @error is set.
Definition at line 1440 of file gf-sn-watcher-v0-gen.c.
References error, GF_SN_WATCHER_V0_GEN, and NULL.
gf_sn_watcher_v0_gen_proxy_new_for_bus()
void gf_sn_watcher_v0_gen_proxy_new_for_bus (GBusType bus_type, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 1508 of file gf-sn-watcher-v0-gen.c.
References GF_TYPE_SN_WATCHER_V0_GEN_PROXY, name, NULL, and user_data.
gf_sn_watcher_v0_gen_proxy_new_for_bus_finish()
GfSnWatcherV0Gen * gf_sn_watcher_v0_gen_proxy_new_for_bus_finish (GAsyncResult * res, GError ** error)
gf_sn_watcher_v0_gen_proxy_new_for_bus_finish: @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gf_sn_watcher_v0_gen_proxy_new_for_bus(). @error: Return location for error or NULL
Finishes an operation started with gf_sn_watcher_v0_gen_proxy_new_for_bus().
Returns: (transfer full) (type GfSnWatcherV0GenProxy): The constructed proxy object or NULL if @error is set.
Definition at line 1530 of file gf-sn-watcher-v0-gen.c.
References error, GF_SN_WATCHER_V0_GEN, and NULL.
gf_sn_watcher_v0_gen_proxy_new_for_bus_sync()
GfSnWatcherV0Gen * gf_sn_watcher_v0_gen_proxy_new_for_bus_sync (GBusType bus_type, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GError ** error)
Definition at line 1563 of file gf-sn-watcher-v0-gen.c.
References error, GF_SN_WATCHER_V0_GEN, GF_TYPE_SN_WATCHER_V0_GEN_PROXY, name, and NULL.
gf_sn_watcher_v0_gen_proxy_new_sync()
GfSnWatcherV0Gen * gf_sn_watcher_v0_gen_proxy_new_sync (GDBusConnection * connection, GDBusProxyFlags flags, const gchar * name, const gchar * object_path, GCancellable * cancellable, GError ** error)
Definition at line 1473 of file gf-sn-watcher-v0-gen.c.
References connection, error, GF_SN_WATCHER_V0_GEN, GF_TYPE_SN_WATCHER_V0_GEN_PROXY, name, and NULL.
gf_sn_watcher_v0_gen_set_is_host_registered()
void gf_sn_watcher_v0_gen_set_is_host_registered (GfSnWatcherV0Gen * object, gboolean value)
gf_sn_watcher_v0_gen_set_is_host_registered: (skip) @object: A GfSnWatcherV0Gen. @value: The value to set.
Sets the <link linkend="gdbus-property-org-kde-StatusNotifierWatcher.IsStatusNotifierHostRegistered">"IsStatusNotifierHostRegistered"</link> D-Bus property to @value.
Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
Definition at line 819 of file gf-sn-watcher-v0-gen.c.
References NULL.
gf_sn_watcher_v0_gen_set_protocol_version()
void gf_sn_watcher_v0_gen_set_protocol_version (GfSnWatcherV0Gen * object, gint value)
gf_sn_watcher_v0_gen_set_protocol_version: (skip) @object: A GfSnWatcherV0Gen. @value: The value to set.
Sets the <link linkend="gdbus-property-org-kde-StatusNotifierWatcher.ProtocolVersion">"ProtocolVersion"</link> D-Bus property to @value.
Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
Definition at line 852 of file gf-sn-watcher-v0-gen.c.
References NULL.
gf_sn_watcher_v0_gen_set_registered_items()
void gf_sn_watcher_v0_gen_set_registered_items (GfSnWatcherV0Gen * object, const gchar *const * value)
gf_sn_watcher_v0_gen_set_registered_items: (skip) @object: A GfSnWatcherV0Gen. @value: The value to set.
Sets the <link linkend="gdbus-property-org-kde-StatusNotifierWatcher.RegisteredStatusNotifierItems">"RegisteredStatusNotifierItems"</link> D-Bus property to @value.
Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
Definition at line 786 of file gf-sn-watcher-v0-gen.c.
References NULL.
Referenced by G_DEFINE_TYPE_WITH_CODE().
gf_sn_watcher_v0_gen_skeleton_new()
GfSnWatcherV0Gen * gf_sn_watcher_v0_gen_skeleton_new (void)
gf_sn_watcher_v0_gen_skeleton_new:
Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-kde-StatusNotifierWatcher.top_of_page">org.kde.StatusNotifierWatcher</link>.
Returns: (transfer full) (type GfSnWatcherV0GenSkeleton): The skeleton object.
Definition at line 2142 of file gf-sn-watcher-v0-gen.c.
References GF_SN_WATCHER_V0_GEN, GF_TYPE_SN_WATCHER_V0_GEN_SKELETON, and NULL.