MATE Desktop Environment: glib-utils.h File Reference
glib-utils.h File Reference
#include <time.h>
Macros
#define g_signal_handlers_disconnect_by_data(instance, data)
#define __FUNCTION__ ""
#define DEBUG_INFO __FILE__, __LINE__, __FUNCTION__
Functions
void _g_object_unref (gpointer object)
gboolean strchrs (const char *str, const char *chars)
char * str_substitute (const char *str, const char *from_str, const char *to_str)
char * escape_str (const char *str, const char *meta_chars)
gboolean match_regexps (GRegex **regexps, const char *string, GRegexMatchFlags match_options)
char ** search_util_get_patterns (const char *pattern_string)
GRegex ** search_util_get_regexps (const char *pattern_string, GRegexCompileFlags compile_options)
void free_regexps (GRegex **regexps)
const char * eat_spaces (const char *line)
char ** split_line (const char *line, int n_fields)
const char * get_last_field (const char *line, int last_field)
const char * get_static_string (const char *s)
char * g_uri_display_basename (const char *uri)
const char * _g_path_get_file_name (const char *path)
const char * _g_path_get_base_name (const char *path, const char *base_dir, gboolean junk_paths)
void debug (const char *file, int line, const char *function, const char *format,...)
Macro Definition Documentation
__FUNCTION__
#define __FUNCTION__ ""
Definition at line 70 of file glib-utils.h.
DEBUG_INFO
#define DEBUG_INFO __FILE__, __LINE__, __FUNCTION__
Definition at line 73 of file glib-utils.h.
Referenced by fr_archive_add(), fr_archive_extract_to_local(), and fr_window_file_list_drag_data_get().
g_signal_handlers_disconnect_by_data
#define g_signal_handlers_disconnect_by_data (instance, data)
Value:
g_signal_handlers_disconnect_matched ((instance), G_SIGNAL_MATCH_DATA, \
                  0, 0, NULL, NULL, (data))
Definition at line 28 of file glib-utils.h.
Referenced by ev_view_accessible_set_model(), fr_archive_create(), and notify_stack_destroy().
Function Documentation
_g_object_unref()
void _g_object_unref (gpointer object)
Definition at line 37 of file glib-utils.c.
References NULL.
_g_path_get_base_name()
const char * _g_path_get_base_name (const char * path, const char * base_dir, gboolean junk_paths)
Definition at line 507 of file glib-utils.c.
References _g_path_get_file_name(), and NULL.
_g_path_get_file_name()
const char * _g_path_get_file_name (const char * path)
debug()
void debug (const char * file, int line, const char * function, const char * format, ...)
Definition at line 425 of file glib-utils.c.
References NULL.
eat_spaces()
const char * eat_spaces (const char * line)
Definition at line 362 of file glib-utils.c.
References NULL.
Referenced by get_last_field(), and split_line().
escape_str()
char * escape_str (const char * str, const char * meta_chars)
Definition at line 150 of file glib-utils.c.
free_regexps()
void free_regexps (GRegex ** regexps)
Definition at line 302 of file glib-utils.c.
References NULL.
Referenced by fr_window_get_file_list_pattern().
g_uri_display_basename()
char * g_uri_display_basename (const char * uri)
Definition at line 471 of file glib-utils.c.
References name.
Referenced by dlg_prop(), and fr_window_archive_save_as().
get_last_field()
const char * get_last_field (const char * line, int last_field)
Definition at line 403 of file glib-utils.c.
References eat_spaces(), NULL, and strchr.
get_static_string()
const char * get_static_string (const char * s)
Definition at line 450 of file glib-utils.c.
References NULL, and static_strings.
Referenced by file_data_update_content_type(), get_file_mime_type(), and get_mime_type_from_extension().
match_regexps()
gboolean match_regexps (GRegex ** regexps, const char * string, GRegexMatchFlags match_options)
Definition at line 278 of file glib-utils.c.
References FALSE, NULL, and TRUE.
Referenced by fr_window_get_file_list_pattern().
search_util_get_patterns()
char ** search_util_get_patterns (const char * pattern_string)
Definition at line 315 of file glib-utils.c.
References g_utf8_strstrip, MAX_PATTERNS, NULL, and str_substitute().
Referenced by search_util_get_regexps().
search_util_get_regexps()
GRegex ** search_util_get_regexps (const char * pattern_string, GRegexCompileFlags compile_options)
Definition at line 339 of file glib-utils.c.
References NULL, and search_util_get_patterns().
Referenced by fr_window_get_file_list_pattern().
split_line()
char ** split_line (const char * line, int n_fields)
Definition at line 372 of file glib-utils.c.
References eat_spaces(), NULL, and strchr.
str_substitute()
char * str_substitute (const char * str, const char * from_str, const char * to_str)
Definition at line 57 of file glib-utils.c.
References FALSE, and NULL.
Referenced by search_util_get_patterns().
strchrs()
gboolean strchrs (const char * str, const char * chars)
Definition at line 46 of file glib-utils.c.
References FALSE, NULL, strchr, and TRUE.