MATE Desktop Environment: gpm-brightness.c File Reference
gpm-brightness.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <errno.h>
#include <X11/Xatom.h>
#include <X11/Xlib.h>
#include <X11/extensions/Xrandr.h>
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
#include <string.h>
#include <sys/time.h>
#include <sys/types.h>
#include "egg-discrete.h"
#include "gpm-brightness.h"
#include "gpm-common.h"
#include "gpm-marshal.h"
Macros
#define GPM_SOLE_SETTER_USE_CACHE TRUE /* this may be insanity */
Enumerations
enum { BRIGHTNESS_CHANGED , LAST_SIGNAL }
enum GpmXRandROp { ACTION_BACKLIGHT_GET , ACTION_BACKLIGHT_SET , ACTION_BACKLIGHT_INC , ACTION_BACKLIGHT_DEC }
Functions
gboolean gpm_brightness_set (GpmBrightness *brightness, guint percentage, gboolean *hw_changed)
gboolean gpm_brightness_get (GpmBrightness *brightness, guint *percentage)
gboolean gpm_brightness_up (GpmBrightness *brightness, gboolean *hw_changed)
gboolean gpm_brightness_down (GpmBrightness *brightness, gboolean *hw_changed)
gboolean gpm_brightness_has_hw (GpmBrightness *brightness)
GpmBrightness * gpm_brightness_new (void)
Macro Definition Documentation
GPM_SOLE_SETTER_USE_CACHE
#define GPM_SOLE_SETTER_USE_CACHE TRUE /* this may be insanity */
Definition at line 50 of file gpm-brightness.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BRIGHTNESS_CHANGED
LAST_SIGNAL
Definition at line 70 of file gpm-brightness.c.
GpmXRandROp
enum GpmXRandROp
Enumerator
ACTION_BACKLIGHT_GET
ACTION_BACKLIGHT_SET
ACTION_BACKLIGHT_INC
ACTION_BACKLIGHT_DEC
Definition at line 75 of file gpm-brightness.c.
Function Documentation
gpm_brightness_down()
gboolean gpm_brightness_down (GpmBrightness * brightness, gboolean * hw_changed)
gpm_brightness_down: @brightness: This brightness class instance @hw_changed: If the hardware was changed, i.e. the brightness changed Return value: TRUE if success, FALSE if there was an error
If possible, put the brightness of the LCD down one unit.
Definition at line 734 of file gpm-brightness.c.
References ACTION_BACKLIGHT_DEC, FALSE, GPM_IS_BRIGHTNESS, NULL, and GpmBrightness::priv.
gpm_brightness_get()
gboolean gpm_brightness_get (GpmBrightness * brightness, guint * percentage)
gpm_brightness_get: @brightness: This brightness class instance Return value: The percentage brightness, or -1 for no hardware or error
Gets the current (or at least what this class thinks is current) percentage brightness. This is quick as no HAL inquiry is done.
Definition at line 628 of file gpm-brightness.c.
References ACTION_BACKLIGHT_GET, egg_discrete_to_percent(), FALSE, GPM_IS_BRIGHTNESS, NULL, GpmBrightness::priv, and TRUE.
Referenced by gpm_backlight_get_brightness().
gpm_brightness_has_hw()
gboolean gpm_brightness_has_hw (GpmBrightness * brightness)
gpm_brightness_has_hw:
Definition at line 866 of file gpm-brightness.c.
References FALSE, GPM_IS_BRIGHTNESS, GpmBrightness::priv, and TRUE.
gpm_brightness_new()
GpmBrightness * gpm_brightness_new (void)
gpm_brightness_new: Return value: A new brightness class instance. Can return NULL if no suitable hardware is found.
Definition at line 973 of file gpm-brightness.c.
References GPM_BRIGHTNESS, GPM_TYPE_BRIGHTNESS, and NULL.
gpm_brightness_set()
gboolean gpm_brightness_set (GpmBrightness * brightness, guint percentage, gboolean * hw_changed)
gpm_brightness_set: @brightness: This brightness class instance @percentage: The percentage brightness @hw_changed: If the hardware was changed, i.e. the brightness changed Return value: TRUE if success, FALSE if there was an error
Definition at line 579 of file gpm-brightness.c.
References ACTION_BACKLIGHT_SET, egg_discrete_from_percent(), FALSE, GPM_IS_BRIGHTNESS, NULL, GpmBrightness::priv, and TRUE.
Referenced by gpm_backlight_set_brightness().
gpm_brightness_up()
gboolean gpm_brightness_up (GpmBrightness * brightness, gboolean * hw_changed)
gpm_brightness_up: @brightness: This brightness class instance @hw_changed: If the hardware was changed, i.e. the brightness changed Return value: TRUE if success, FALSE if there was an error
If possible, put the brightness of the LCD up one unit.
Definition at line 683 of file gpm-brightness.c.
References ACTION_BACKLIGHT_INC, FALSE, GPM_IS_BRIGHTNESS, NULL, and GpmBrightness::priv.