MATE Desktop Environment: gpm-graph-widget.c File Reference
gpm-graph-widget.c File Reference
#include "config.h"
#include <gtk/gtk.h>
#include <pango/pangocairo.h>
#include <glib/gi18n.h>
#include <stdlib.h>
#include <math.h>
#include "gpm-common.h"
#include "gpm-point-obj.h"
#include "gpm-graph-widget.h"
#include "egg-color.h"
#include "egg-precision.h"
Macros
#define GPM_GRAPH_WIDGET_FONT "Sans 8"
Enumerations
enum {
PROP_0 , PROP_USE_LEGEND , PROP_USE_GRID , PROP_TYPE_X ,
PROP_TYPE_Y , PROP_AUTORANGE_X , PROP_AUTORANGE_Y , PROP_START_X ,
PROP_START_Y , PROP_STOP_X , PROP_STOP_Y
}
Functions
G_DEFINE_TYPE_WITH_PRIVATE (GpmGraphWidget, gpm_graph_widget, GTK_TYPE_DRAWING_AREA)
gboolean gpm_graph_widget_key_data_add (GpmGraphWidget *graph, guint32 color, const gchar *desc)
gboolean gpm_graph_widget_data_clear (GpmGraphWidget *graph)
gboolean gpm_graph_widget_data_assign (GpmGraphWidget *graph, GpmGraphWidgetPlot plot, GPtrArray *data)
GtkWidget * gpm_graph_widget_new (void)
Macro Definition Documentation
GPM_GRAPH_WIDGET_FONT
#define GPM_GRAPH_WIDGET_FONT "Sans 8"
Definition at line 37 of file gpm-graph-widget.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_USE_LEGEND
PROP_USE_GRID
PROP_TYPE_X
PROP_TYPE_Y
PROP_AUTORANGE_X
PROP_AUTORANGE_Y
PROP_START_X
PROP_START_Y
PROP_STOP_X
PROP_STOP_Y
Definition at line 76 of file gpm-graph-widget.c.
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (GpmGraphWidget , gpm_graph_widget , GTK_TYPE_DRAWING_AREA)
gpm_graph_widget_data_assign()
gboolean gpm_graph_widget_data_assign (GpmGraphWidget * graph, GpmGraphWidgetPlot plot, GPtrArray * data)
gpm_graph_widget_data_assign: @graph: This class instance @data: an array of GpmPointObj's
Sets the data for the graph
Definition at line 380 of file gpm-graph-widget.c.
References data, FALSE, GPM_IS_GRAPH_WIDGET, gpm_point_obj_copy(), gpm_point_obj_free(), NULL, GpmGraphWidget::priv, and TRUE.
gpm_graph_widget_data_clear()
gboolean gpm_graph_widget_data_clear (GpmGraphWidget * graph)
gpm_graph_widget_data_clear:
Definition at line 338 of file gpm-graph-widget.c.
References FALSE, GPM_IS_GRAPH_WIDGET, GpmGraphWidget::priv, and TRUE.
gpm_graph_widget_key_data_add()
gboolean gpm_graph_widget_key_data_add (GpmGraphWidget * graph, guint32 color, const gchar * desc)
gpm_graph_widget_key_data_add:
Definition at line 118 of file gpm-graph-widget.c.
References GpmGraphWidgetKeyData::color, GpmGraphWidgetKeyData::desc, FALSE, GPM_IS_GRAPH_WIDGET, GpmGraphWidget::priv, and TRUE.
gpm_graph_widget_new()
GtkWidget * gpm_graph_widget_new (void)
gpm_graph_widget_new: Return value: A new GpmGraphWidget object.
Definition at line 1140 of file gpm-graph-widget.c.
References GPM_TYPE_GRAPH_WIDGET, and NULL.
Referenced by main().