MATE Desktop Environment: gpm-self-test.c File Reference
gpm-self-test.c File Reference
#include "config.h"
#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include "egg-test.h"
#include "gpm-screensaver.h"
Functions
void egg_precision_test (EggTest *test)
void egg_discrete_test (EggTest *test)
void egg_color_test (EggTest *test)
void egg_array_float_test (EggTest *test)
void egg_idletime_test (EggTest *test)
void gpm_common_test (EggTest *test)
void gpm_idle_test (EggTest *test)
void gpm_phone_test (EggTest *test)
void gpm_dpms_test (EggTest *test)
void gpm_graph_widget_test (EggTest *test)
void gpm_proxy_test (EggTest *test)
void gpm_hal_manager_test (EggTest *test)
void gpm_device_test (EggTest *test)
void gpm_device_teststore (EggTest *test)
int main (int argc, char **argv)
Function Documentation
egg_array_float_test()
void egg_array_float_test (EggTest * test)
References test.
Referenced by main().
egg_color_test()
void egg_color_test (EggTest * test)
References test.
Referenced by main().
egg_discrete_test()
void egg_discrete_test (EggTest * test)
References test.
Referenced by main().
egg_idletime_test()
void egg_idletime_test (EggTest * test)
References test.
egg_precision_test()
void egg_precision_test (EggTest * test)
References test.
Referenced by main().
gpm_common_test()
void gpm_common_test (EggTest * test)
References test.
Referenced by main().
gpm_device_test()
void gpm_device_test (EggTest * test)
References test.
Referenced by main().
gpm_device_teststore()
void gpm_device_teststore (EggTest * test)
References test.
Referenced by main().
gpm_dpms_test()
void gpm_dpms_test (EggTest * test)
References test.
gpm_graph_widget_test()
void gpm_graph_widget_test (EggTest * test)
References test.
gpm_hal_manager_test()
void gpm_hal_manager_test (EggTest * test)
References test.
Referenced by main().
gpm_idle_test()
void gpm_idle_test (EggTest * test)
References test.
gpm_phone_test()
void gpm_phone_test (EggTest * test)
References test.
Referenced by main().
gpm_proxy_test()
void gpm_proxy_test (EggTest * test)
References test.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 50 of file gpm-self-test.c.
References egg_array_float_test(), egg_color_test(), egg_discrete_test(), egg_precision_test(), egg_test_finish(), egg_test_init(), gpm_common_test(), gpm_device_test(), gpm_device_teststore(), gpm_hal_manager_test(), gpm_phone_test(), gpm_proxy_test(), and test.