MATE Desktop Environment: gpm-screensaver.c File Reference
gpm-screensaver.c File Reference
#include "config.h"
#include <string.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <dbus/dbus-glib.h>
#include "gpm-screensaver.h"
#include "gpm-common.h"
Macros
#define GS_LISTENER_SERVICE "org.mate.ScreenSaver"
#define GS_LISTENER_PATH "/"
#define GS_LISTENER_INTERFACE "org.mate.ScreenSaver"
Functions
gboolean gpm_screensaver_lock (GpmScreensaver *screensaver)
guint gpm_screensaver_add_throttle (GpmScreensaver *screensaver, const char *reason)
gboolean gpm_screensaver_remove_throttle (GpmScreensaver *screensaver, guint cookie)
gboolean gpm_screensaver_check_running (GpmScreensaver *screensaver)
gboolean gpm_screensaver_poke (GpmScreensaver *screensaver)
GpmScreensaver * gpm_screensaver_new (void)
Macro Definition Documentation
GS_LISTENER_INTERFACE
#define GS_LISTENER_INTERFACE "org.mate.ScreenSaver"
Definition at line 37 of file gpm-screensaver.c.
GS_LISTENER_PATH
#define GS_LISTENER_PATH "/"
Definition at line 36 of file gpm-screensaver.c.
Referenced by gs_listener_acquire().
GS_LISTENER_SERVICE
#define GS_LISTENER_SERVICE "org.mate.ScreenSaver"
Definition at line 35 of file gpm-screensaver.c.
Referenced by gs_listener_acquire().
Function Documentation
gpm_screensaver_add_throttle()
guint gpm_screensaver_add_throttle (GpmScreensaver * screensaver, const char * reason)
gpm_screensaver_add_throttle: @screensaver: This class instance @reason: The reason for throttling Return value: Success value, or zero for failure
Definition at line 96 of file gpm-screensaver.c.
References error, GPM_IS_SCREENSAVER, NULL, and GpmScreensaver::priv.
Referenced by gpm_control_hibernate(), and gpm_control_suspend().
gpm_screensaver_check_running()
gboolean gpm_screensaver_check_running (GpmScreensaver * screensaver)
gpm_screensaver_check_running: @screensaver: This class instance Return value: TRUE if mate-screensaver is running
Definition at line 173 of file gpm-screensaver.c.
References error, FALSE, GPM_IS_SCREENSAVER, NULL, GpmScreensaver::priv, and TRUE.
Referenced by gpm_screensaver_lock().
gpm_screensaver_lock()
gboolean gpm_screensaver_lock (GpmScreensaver * screensaver)
gpm_screensaver_lock @screensaver: This class instance Return value: Success value
Definition at line 54 of file gpm-screensaver.c.
References FALSE, GPM_IS_SCREENSAVER, gpm_screensaver_check_running(), NULL, GpmScreensaver::priv, and TRUE.
Referenced by gpm_control_hibernate(), and gpm_control_suspend().
gpm_screensaver_new()
GpmScreensaver * gpm_screensaver_new (void)
gpm_screensaver_new: Return value: new GpmScreensaver instance.
Definition at line 277 of file gpm-screensaver.c.
References GPM_SCREENSAVER, GPM_TYPE_SCREENSAVER, and NULL.
Referenced by gpm_control_hibernate(), and gpm_control_suspend().
gpm_screensaver_poke()
gboolean gpm_screensaver_poke (GpmScreensaver * screensaver)
gpm_screensaver_poke: @screensaver: This class instance
Pokes MATE Screensaver simulating hardware events. This displays the unlock dialogue when we resume, so the user doesn't have to move the mouse or press any key before the window comes up.
Definition at line 208 of file gpm-screensaver.c.
References FALSE, GPM_IS_SCREENSAVER, NULL, GpmScreensaver::priv, and TRUE.
Referenced by gpm_control_hibernate(), and gpm_control_suspend().
gpm_screensaver_remove_throttle()
gboolean gpm_screensaver_remove_throttle (GpmScreensaver * screensaver, guint cookie)
gpm_screensaver_remove_throttle:
Definition at line 136 of file gpm-screensaver.c.
References error, FALSE, GPM_IS_SCREENSAVER, NULL, GpmScreensaver::priv, and TRUE.
Referenced by gpm_control_hibernate(), and gpm_control_suspend().