MATE Desktop Environment: gpm-graph-widget.h File Reference
gpm-graph-widget.h File Reference
#include <gtk/gtk.h>
#include "gpm-point-obj.h"
Classes
struct GpmGraphWidgetKeyData
struct GpmGraphWidget
struct GpmGraphWidgetClass
Macros
#define GPM_TYPE_GRAPH_WIDGET (gpm_graph_widget_get_type ())
#define GPM_GRAPH_WIDGET(obj)
#define GPM_GRAPH_WIDGET_CLASS(obj)
#define GPM_IS_GRAPH_WIDGET(obj)
#define GPM_IS_GRAPH_WIDGET_CLASS(obj)
#define GPM_GRAPH_WIDGET_GET_CLASS (G_TYPE_INSTANCE_GET_CLASS ((obj), GPM_TYPE_GRAPH_WIDGET, GpmGraphWidgetClass))
#define GPM_GRAPH_WIDGET_LEGEND_SPACING 17
Typedefs
typedef struct GpmGraphWidget GpmGraphWidget
typedef struct GpmGraphWidgetClass GpmGraphWidgetClass
typedef struct GpmGraphWidgetPrivate GpmGraphWidgetPrivate
Enumerations
enum GpmGraphWidgetType {
GPM_GRAPH_WIDGET_TYPE_INVALID , GPM_GRAPH_WIDGET_TYPE_PERCENTAGE , GPM_GRAPH_WIDGET_TYPE_FACTOR , GPM_GRAPH_WIDGET_TYPE_TIME ,
GPM_GRAPH_WIDGET_TYPE_POWER , GPM_GRAPH_WIDGET_TYPE_VOLTAGE , GPM_GRAPH_WIDGET_TYPE_UNKNOWN
}
enum GpmGraphWidgetPlot { GPM_GRAPH_WIDGET_PLOT_LINE , GPM_GRAPH_WIDGET_PLOT_POINTS , GPM_GRAPH_WIDGET_PLOT_BOTH }
Functions
GType gpm_graph_widget_get_type (void)
GtkWidget * gpm_graph_widget_new (void)
gboolean gpm_graph_widget_data_clear (GpmGraphWidget *graph)
gboolean gpm_graph_widget_data_assign (GpmGraphWidget *graph, GpmGraphWidgetPlot plot, GPtrArray *array)
gboolean gpm_graph_widget_key_data_add (GpmGraphWidget *graph, guint32 color, const gchar *desc)
Macro Definition Documentation
GPM_GRAPH_WIDGET
#define GPM_GRAPH_WIDGET (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), GPM_TYPE_GRAPH_WIDGET, GpmGraphWidget))
Definition at line 32 of file gpm-graph-widget.h.
GPM_GRAPH_WIDGET_CLASS
#define GPM_GRAPH_WIDGET_CLASS (obj)
Value:
(G_TYPE_CHECK_CLASS_CAST ((obj), GPM_GRAPH_WIDGET, GpmGraphWidgetClass))
Definition at line 33 of file gpm-graph-widget.h.
GPM_GRAPH_WIDGET_GET_CLASS
#define GPM_GRAPH_WIDGET_GET_CLASS (G_TYPE_INSTANCE_GET_CLASS ((obj), GPM_TYPE_GRAPH_WIDGET, GpmGraphWidgetClass))
Definition at line 36 of file gpm-graph-widget.h.
GPM_GRAPH_WIDGET_LEGEND_SPACING
#define GPM_GRAPH_WIDGET_LEGEND_SPACING 17
Definition at line 38 of file gpm-graph-widget.h.
GPM_IS_GRAPH_WIDGET
#define GPM_IS_GRAPH_WIDGET (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), GPM_TYPE_GRAPH_WIDGET))
Definition at line 34 of file gpm-graph-widget.h.
Referenced by gpm_graph_widget_data_assign(), gpm_graph_widget_data_clear(), and gpm_graph_widget_key_data_add().
GPM_IS_GRAPH_WIDGET_CLASS
#define GPM_IS_GRAPH_WIDGET_CLASS (obj)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((obj), EFF_TYPE_GRAPH_WIDGET))
Definition at line 35 of file gpm-graph-widget.h.
GPM_TYPE_GRAPH_WIDGET
#define GPM_TYPE_GRAPH_WIDGET (gpm_graph_widget_get_type ())
Definition at line 31 of file gpm-graph-widget.h.
Referenced by gpm_graph_widget_new().
Typedef Documentation
GpmGraphWidget
typedef struct GpmGraphWidget GpmGraphWidget
Definition at line 40 of file gpm-graph-widget.h.
GpmGraphWidgetClass
typedef struct GpmGraphWidgetClass GpmGraphWidgetClass
Definition at line 41 of file gpm-graph-widget.h.
GpmGraphWidgetPrivate
typedef struct GpmGraphWidgetPrivate GpmGraphWidgetPrivate
Definition at line 42 of file gpm-graph-widget.h.
Enumeration Type Documentation
GpmGraphWidgetPlot
enum GpmGraphWidgetPlot
Enumerator
GPM_GRAPH_WIDGET_PLOT_LINE
GPM_GRAPH_WIDGET_PLOT_POINTS
GPM_GRAPH_WIDGET_PLOT_BOTH
Definition at line 54 of file gpm-graph-widget.h.
GpmGraphWidgetType
enum GpmGraphWidgetType
Enumerator
GPM_GRAPH_WIDGET_TYPE_INVALID
GPM_GRAPH_WIDGET_TYPE_PERCENTAGE
GPM_GRAPH_WIDGET_TYPE_FACTOR
GPM_GRAPH_WIDGET_TYPE_TIME
GPM_GRAPH_WIDGET_TYPE_POWER
GPM_GRAPH_WIDGET_TYPE_VOLTAGE
GPM_GRAPH_WIDGET_TYPE_UNKNOWN
Definition at line 44 of file gpm-graph-widget.h.
Function Documentation
gpm_graph_widget_data_assign()
gboolean gpm_graph_widget_data_assign (GpmGraphWidget * graph, GpmGraphWidgetPlot plot, GPtrArray * data)
gpm_graph_widget_data_assign: @graph: This class instance @data: an array of GpmPointObj's
Sets the data for the graph
Definition at line 380 of file gpm-graph-widget.c.
References data, FALSE, GPM_IS_GRAPH_WIDGET, gpm_point_obj_copy(), gpm_point_obj_free(), NULL, GpmGraphWidget::priv, and TRUE.
gpm_graph_widget_data_clear()
gboolean gpm_graph_widget_data_clear (GpmGraphWidget * graph)
gpm_graph_widget_data_clear:
Definition at line 338 of file gpm-graph-widget.c.
References FALSE, GPM_IS_GRAPH_WIDGET, GpmGraphWidget::priv, and TRUE.
gpm_graph_widget_get_type()
GType gpm_graph_widget_get_type (void)
gpm_graph_widget_key_data_add()
gboolean gpm_graph_widget_key_data_add (GpmGraphWidget * graph, guint32 color, const gchar * desc)
gpm_graph_widget_key_data_add:
Definition at line 118 of file gpm-graph-widget.c.
References GpmGraphWidgetKeyData::color, GpmGraphWidgetKeyData::desc, FALSE, GPM_IS_GRAPH_WIDGET, GpmGraphWidget::priv, and TRUE.
gpm_graph_widget_new()
GtkWidget * gpm_graph_widget_new (void)
gpm_graph_widget_new: Return value: A new GpmGraphWidget object.
Definition at line 1140 of file gpm-graph-widget.c.
References GPM_TYPE_GRAPH_WIDGET, and NULL.
Referenced by main().