MATE Desktop Environment: gpm-control.c File Reference
gpm-control.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <errno.h>
#include <string.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <gio/gio.h>
#include <glib/gi18n.h>
#include "egg-console-kit.h"
#include "gpm-screensaver.h"
#include "gpm-common.h"
#include "gpm-control.h"
#include "gpm-networkmanager.h"
Enumerations
enum { RESUME , SLEEP , LAST_SIGNAL }
Functions
GQuark gpm_control_error_quark (void)
gboolean gpm_control_shutdown (GpmControl *control, GError **error)
gboolean gpm_control_get_lock_policy (GpmControl *control, const gchar *policy)
gboolean gpm_control_suspend (GpmControl *control, GError **error)
gboolean gpm_control_hibernate (GpmControl *control, GError **error)
GpmControl * gpm_control_new (void)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RESUME
SLEEP
LAST_SIGNAL
Definition at line 62 of file gpm-control.c.
Function Documentation
gpm_control_error_quark()
GQuark gpm_control_error_quark (void)
gpm_control_error_quark: Return value: Our personal error quark.
Definition at line 78 of file gpm-control.c.
gpm_control_get_lock_policy()
gboolean gpm_control_get_lock_policy (GpmControl * control, const gchar * policy)
gpm_control_get_lock_policy: @control: This class instance @policy: The policy string.
This function finds out if we should lock the screen when we do an action. It is required as we can either use the mate-screensaver policy or the custom policy. See the yelp file for more information.
Return value: TRUE if we should lock.
Definition at line 166 of file gpm-control.c.
References FALSE, GPM_SETTINGS_LOCK_USE_SCREENSAVER, GS_SETTINGS_PREF_LOCK_ENABLED, GS_SETTINGS_SCHEMA, NULL, GpmControl::priv, and TRUE.
Referenced by gpm_control_hibernate(), and gpm_control_suspend().
gpm_control_hibernate()
gboolean gpm_control_hibernate (GpmControl * control, GError ** error)
gpm_control_hibernate:
Definition at line 363 of file gpm-control.c.
References egg_console_kit_can_hibernate(), egg_console_kit_hibernate(), egg_console_kit_new(), error, FALSE, GPM_CONTROL_ACTION_HIBERNATE, GPM_CONTROL_ERROR, GPM_CONTROL_ERROR_GENERAL, gpm_control_get_lock_policy(), gpm_networkmanager_sleep(), gpm_networkmanager_wake(), gpm_screensaver_add_throttle(), gpm_screensaver_lock(), gpm_screensaver_new(), gpm_screensaver_poke(), gpm_screensaver_remove_throttle(), GPM_SETTINGS_LOCK_KEYRING_HIBERNATE, GPM_SETTINGS_LOCK_KEYRING_SUSPEND, GPM_SETTINGS_LOCK_ON_HIBERNATE, GPM_SETTINGS_NETWORKMANAGER_SLEEP, LOGIND_RUNNING, NULL, GpmControl::priv, proxy, RESUME, SLEEP, and TRUE.
gpm_control_new()
GpmControl * gpm_control_new (void)
gpm_control_new: Return value: A new control class instance.
Definition at line 577 of file gpm-control.c.
References GPM_CONTROL, GPM_TYPE_CONTROL, and NULL.
gpm_control_shutdown()
gboolean gpm_control_shutdown (GpmControl * control, GError ** error)
gpm_control_shutdown: @control: This class instance
Shuts down the computer
Definition at line 139 of file gpm-control.c.
References egg_console_kit_new(), egg_console_kit_stop(), error, and LOGIND_RUNNING.
gpm_control_suspend()
gboolean gpm_control_suspend (GpmControl * control, GError ** error)
gpm_control_suspend:
Definition at line 208 of file gpm-control.c.
References egg_console_kit_can_suspend(), egg_console_kit_new(), egg_console_kit_suspend(), error, FALSE, GPM_CONTROL_ACTION_SUSPEND, GPM_CONTROL_ERROR, GPM_CONTROL_ERROR_GENERAL, gpm_control_get_lock_policy(), gpm_networkmanager_sleep(), gpm_networkmanager_wake(), gpm_screensaver_add_throttle(), gpm_screensaver_lock(), gpm_screensaver_new(), gpm_screensaver_poke(), gpm_screensaver_remove_throttle(), GPM_SETTINGS_LOCK_KEYRING_SUSPEND, GPM_SETTINGS_LOCK_ON_SUSPEND, GPM_SETTINGS_NETWORKMANAGER_SLEEP, LOGIND_RUNNING, NULL, GpmControl::priv, proxy, RESUME, SLEEP, and TRUE.