MATE Desktop Environment: gpm-backlight.c File Reference
gpm-backlight.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <errno.h>
#include <string.h>
#include <sys/time.h>
#include <sys/types.h>
#include <math.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <libupower-glib/upower.h>
#include "gpm-button.h"
#include "gpm-backlight.h"
#include "gpm-brightness.h"
#include "gpm-control.h"
#include "gpm-common.h"
#include "gsd-media-keys-window.h"
#include "gpm-dpms.h"
#include "gpm-idle.h"
#include "gpm-marshal.h"
#include "gpm-icon-names.h"
#include "egg-console-kit.h"
Enumerations
enum { BRIGHTNESS_CHANGED , LAST_SIGNAL }
Functions
GQuark gpm_backlight_error_quark (void)
gboolean gpm_backlight_get_brightness (GpmBacklight *backlight, guint *brightness, GError **error)
gboolean gpm_backlight_set_brightness (GpmBacklight *backlight, guint percentage, GError **error)
GpmBacklight * gpm_backlight_new (void)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BRIGHTNESS_CHANGED
LAST_SIGNAL
Definition at line 75 of file gpm-backlight.c.
Function Documentation
gpm_backlight_error_quark()
GQuark gpm_backlight_error_quark (void)
gpm_backlight_error_quark: Return value: Our personal error quark.
Definition at line 89 of file gpm-backlight.c.
Referenced by gpm_backlight_get_brightness(), and gpm_backlight_set_brightness().
gpm_backlight_get_brightness()
gboolean gpm_backlight_get_brightness (GpmBacklight * backlight, guint * brightness, GError ** error)
gpm_backlight_get_brightness:
Definition at line 101 of file gpm-backlight.c.
References error, FALSE, GPM_BACKLIGHT_ERROR_DATA_NOT_AVAILABLE, GPM_BACKLIGHT_ERROR_HARDWARE_NOT_PRESENT, gpm_backlight_error_quark(), gpm_brightness_get(), GPM_IS_BACKLIGHT, level, NULL, and GpmBacklight::priv.
gpm_backlight_new()
GpmBacklight * gpm_backlight_new (void)
gpm_backlight_new: Return value: A new brightness class instance.
Definition at line 819 of file gpm-backlight.c.
References GPM_TYPE_BACKLIGHT, and NULL.
gpm_backlight_set_brightness()
gboolean gpm_backlight_set_brightness (GpmBacklight * backlight, guint percentage, GError ** error)
gpm_backlight_set_brightness:
Definition at line 133 of file gpm-backlight.c.
References BRIGHTNESS_CHANGED, error, FALSE, GPM_BACKLIGHT_ERROR_GENERAL, GPM_BACKLIGHT_ERROR_HARDWARE_NOT_PRESENT, gpm_backlight_error_quark(), gpm_brightness_set(), GPM_IS_BACKLIGHT, NULL, and GpmBacklight::priv.