MATE Desktop Environment: gpm-upower.c File Reference
gpm-upower.c File Reference
#include "config.h"
#include <glib/gi18n.h>
#include <libupower-glib/upower.h>
#include "egg-precision.h"
#include "gpm-upower.h"
#include "gpm-common.h"
Macros
#define GPM_UP_TIME_PRECISION 5*60
#define GPM_UP_TEXT_MIN_TIME 120
Functions
gchar * gpm_upower_get_device_icon (UpDevice *device)
gchar * gpm_upower_get_device_summary (UpDevice *device)
gchar * gpm_upower_get_device_description (UpDevice *device)
const gchar * gpm_device_kind_to_localised_string (UpDeviceKind kind, guint number)
const gchar * gpm_device_kind_to_icon (UpDeviceKind kind)
const gchar * gpm_device_technology_to_localised_string (UpDeviceTechnology technology_enum)
const gchar * gpm_device_state_to_localised_string (UpDeviceState state)
Macro Definition Documentation
GPM_UP_TEXT_MIN_TIME
#define GPM_UP_TEXT_MIN_TIME 120
Definition at line 34 of file gpm-upower.c.
Referenced by gpm_upower_get_device_summary().
GPM_UP_TIME_PRECISION
#define GPM_UP_TIME_PRECISION 5*60
Definition at line 33 of file gpm-upower.c.
Referenced by gpm_upower_get_device_summary().
Function Documentation
gpm_device_kind_to_icon()
const gchar * gpm_device_kind_to_icon (UpDeviceKind kind)
gpm_device_kind_to_icon:
Definition at line 547 of file gpm-upower.c.
References NULL.
gpm_device_kind_to_localised_string()
const gchar * gpm_device_kind_to_localised_string (UpDeviceKind kind, guint number)
gpm_device_kind_to_localised_string:
Definition at line 484 of file gpm-upower.c.
References NULL.
Referenced by gpm_upower_get_device_description(), and gpm_upower_get_device_summary().
gpm_device_state_to_localised_string()
const gchar * gpm_device_state_to_localised_string (UpDeviceState state)
gpm_device_state_to_localised_string:
Definition at line 638 of file gpm-upower.c.
References _, and NULL.
gpm_device_technology_to_localised_string()
const gchar * gpm_device_technology_to_localised_string (UpDeviceTechnology technology_enum)
gpm_device_technology_to_localised_string:
Definition at line 595 of file gpm-upower.c.
References _, and NULL.
Referenced by gpm_upower_get_device_description().
gpm_upower_get_device_description()
gchar * gpm_upower_get_device_description (UpDevice * device)
gpm_upower_get_device_description:
Definition at line 324 of file gpm-upower.c.
References _, condition, FALSE, gpm_device_kind_to_localised_string(), gpm_device_technology_to_localised_string(), gpm_get_timestring(), and NULL.
gpm_upower_get_device_icon()
gchar * gpm_upower_get_device_icon (UpDevice * device)
gpm_upower_get_device_icon:
Need to free the return value
Definition at line 76 of file gpm-upower.c.
References NULL, and prefix.
gpm_upower_get_device_summary()
gchar * gpm_upower_get_device_summary (UpDevice * device)
gpm_upower_get_device_summary:
Definition at line 184 of file gpm-upower.c.
References _, egg_precision_round_down(), gpm_device_kind_to_localised_string(), gpm_get_timestring(), GPM_UP_TEXT_MIN_TIME, GPM_UP_TIME_PRECISION, and NULL.
Referenced by gpm_engine_get_summary().