MATE Desktop Environment: gpm-kbd-backlight.c File Reference
gpm-kbd-backlight.c File Reference
#include <gio/gio.h>
#include <glib.h>
#include <libupower-glib/upower.h>
#include <gtk/gtk.h>
#include "gpm-button.h"
#include "gpm-common.h"
#include "gpm-control.h"
#include "gpm-idle.h"
#include "gpm-kbd-backlight.h"
#include "gsd-media-keys-window.h"
Enumerations
enum { BRIGHTNESS_CHANGED , LAST_SIGNAL }
Functions
GQuark gpm_kbd_backlight_error_quark (void)
gboolean gpm_kbd_backlight_get_brightness (GpmKbdBacklight *backlight, guint *brightness, GError **error)
gboolean gpm_kbd_backlight_set_brightness (GpmKbdBacklight *backlight, guint percentage, GError **error)
GpmKbdBacklight * gpm_kbd_backlight_new (void)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BRIGHTNESS_CHANGED
LAST_SIGNAL
Definition at line 55 of file gpm-kbd-backlight.c.
Function Documentation
gpm_kbd_backlight_error_quark()
GQuark gpm_kbd_backlight_error_quark (void)
gpm_kbd_backlight_error_quark: Return value: Our personal error quark.
Definition at line 69 of file gpm-kbd-backlight.c.
Referenced by gpm_kbd_backlight_get_brightness(), and gpm_kbd_backlight_set_brightness().
gpm_kbd_backlight_get_brightness()
gboolean gpm_kbd_backlight_get_brightness (GpmKbdBacklight * backlight, guint * brightness, GError ** error)
gpm_kbd_backlight_get_brightness: @backlight: @brightness: @error:
Return value:
Definition at line 86 of file gpm-kbd-backlight.c.
References error, FALSE, GPM_IS_KBD_BACKLIGHT, GPM_KBD_BACKLIGHT_ERROR_HARDWARE_NOT_PRESENT, gpm_kbd_backlight_error_quark(), NULL, GpmKbdBacklight::priv, and TRUE.
gpm_kbd_backlight_new()
GpmKbdBacklight * gpm_kbd_backlight_new (void)
gpm_kbd_backlight_new: Return value: A new GpmKbdBacklight class instance.
Definition at line 714 of file gpm-kbd-backlight.c.
References GPM_TYPE_KBD_BACKLIGHT, and NULL.
gpm_kbd_backlight_set_brightness()
gboolean gpm_kbd_backlight_set_brightness (GpmKbdBacklight * backlight, guint percentage, GError ** error)
gpm_kbd_backlight_set_brightness: @backlight: @percentage: @error:
Return value:
Definition at line 296 of file gpm-kbd-backlight.c.
References error, FALSE, GPM_IS_KBD_BACKLIGHT, GPM_KBD_BACKLIGHT_ERROR_GENERAL, GPM_KBD_BACKLIGHT_ERROR_HARDWARE_NOT_PRESENT, gpm_kbd_backlight_error_quark(), NULL, GpmKbdBacklight::priv, and TRUE.