MATE Desktop Environment: group-props.c File Reference
group-props.c File Reference
#include <config.h>
#include "group-props.h"
#include "group-private.h"
#include "xprops.h"
#include <X11/Xatom.h>
Macros
#define N_HOOKS 3
Typedefs
typedef void(* InitValueFunc) (MetaDisplay *display, Atom property, MetaPropValue *value)
typedef void(* ReloadValueFunc) (MetaGroup *group, MetaPropValue *value)
Functions
void meta_group_reload_property (MetaGroup *group, Atom property)
void meta_group_reload_properties (MetaGroup *group, const Atom *properties, int n_properties)
void meta_display_init_group_prop_hooks (MetaDisplay *display)
void meta_display_free_group_prop_hooks (MetaDisplay *display)
Macro Definition Documentation
N_HOOKS
#define N_HOOKS 3
Definition at line 167 of file group-props.c.
Referenced by meta_display_init_group_prop_hooks().
Typedef Documentation
InitValueFunc
typedef void(* InitValueFunc) (MetaDisplay *display, Atom property, MetaPropValue *value)
Definition at line 30 of file group-props.c.
ReloadValueFunc
typedef void(* ReloadValueFunc) (MetaGroup *group, MetaPropValue *value)
Definition at line 33 of file group-props.c.
Function Documentation
meta_display_free_group_prop_hooks()
void meta_display_free_group_prop_hooks (MetaDisplay * display)
Definition at line 204 of file group-props.c.
References _MetaDisplay::group_prop_hooks, and NULL.
Referenced by meta_display_close().
meta_display_init_group_prop_hooks()
void meta_display_init_group_prop_hooks (MetaDisplay * display)
Definition at line 170 of file group-props.c.
References _MetaDisplay::group_prop_hooks, N_HOOKS, and NULL.
meta_group_reload_properties()
void meta_group_reload_properties (MetaGroup * group, const Atom * properties, int n_properties)
Definition at line 59 of file group-props.c.
References _MetaGroup::display, _MetaGroup::group_leader, meta_prop_free_values(), meta_prop_get_values(), and NULL.
Referenced by meta_group_reload_property().
meta_group_reload_property()
void meta_group_reload_property (MetaGroup * group, Atom property)
Definition at line 52 of file group-props.c.
References meta_group_reload_properties().
Referenced by meta_group_property_notify().