MATE Desktop Environment: gs-grab-x11.c File Reference
gs-grab-x11.c File Reference
#include "config.h"
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <gdk/gdk.h>
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
#include "gs-window.h"
#include "gs-grab.h"
#include "gs-debug.h"
Functions
void gs_grab_reset (GSGrab *grab)
void gs_grab_release (GSGrab *grab, gboolean flush)
gboolean gs_grab_grab_window (GSGrab *grab, GdkWindow *window, GdkDisplay *display, gboolean no_pointer_grab, gboolean hide_cursor)
gboolean gs_grab_grab_root (GSGrab *grab, gboolean no_pointer_grab, gboolean hide_cursor)
gboolean gs_grab_grab_offscreen (GSGrab *grab, gboolean no_pointer_grab, gboolean hide_cursor)
void gs_grab_move_to_window (GSGrab *grab, GdkWindow *window, GdkDisplay *display, gboolean no_pointer_grab, gboolean hide_cursor)
GSGrab * gs_grab_new (void)
Function Documentation
gs_grab_grab_offscreen()
gboolean gs_grab_grab_offscreen (GSGrab * grab, gboolean no_pointer_grab, gboolean hide_cursor)
Definition at line 358 of file gs-grab-x11.c.
References gs_debug, and gs_grab_grab_window().
gs_grab_grab_root()
gboolean gs_grab_grab_root (GSGrab * grab, gboolean no_pointer_grab, gboolean hide_cursor)
Definition at line 333 of file gs-grab-x11.c.
References gs_debug, gs_grab_grab_window(), and NULL.
gs_grab_grab_window()
gboolean gs_grab_grab_window (GSGrab * grab, GdkWindow * window, GdkDisplay * display, gboolean no_pointer_grab, gboolean hide_cursor)
Definition at line 290 of file gs-grab-x11.c.
References FALSE, gs_debug, and TRUE.
Referenced by gs_grab_grab_offscreen(), and gs_grab_grab_root().
gs_grab_move_to_window()
void gs_grab_move_to_window (GSGrab * grab, GdkWindow * window, GdkDisplay * display, gboolean no_pointer_grab, gboolean hide_cursor)
Definition at line 380 of file gs-grab-x11.c.
References FALSE, and GS_IS_GRAB.
gs_grab_new()
GSGrab * gs_grab_new (void)
Definition at line 437 of file gs-grab-x11.c.
References GS_GRAB, GS_TYPE_GRAB, and NULL.
Referenced by main().
gs_grab_release()
void gs_grab_release (GSGrab * grab, gboolean flush)
Definition at line 174 of file gs-grab-x11.c.
References gs_debug, gs_grab_reset(), and TRUE.
gs_grab_reset()
void gs_grab_reset (GSGrab * grab)
Definition at line 162 of file gs-grab-x11.c.
References NULL.
Referenced by gs_grab_release().