MATE Desktop Environment: gs-lock-plug.h File Reference
gs-lock-plug.h File Reference
#include <glib.h>
Classes
struct GSLockPlug
struct GSLockPlugClass
Macros
#define GS_TYPE_LOCK_PLUG (gs_lock_plug_get_type ())
#define GS_LOCK_PLUG(o)
#define GS_LOCK_PLUG_CLASS(k)
#define GS_IS_LOCK_PLUG(o)
#define GS_IS_LOCK_PLUG_CLASS(k)
#define GS_LOCK_PLUG_GET_CLASS(o)
Typedefs
typedef struct GSLockPlugPrivate GSLockPlugPrivate
Enumerations
enum GSPlugResponseType { GS_LOCK_PLUG_RESPONSE_NONE = -1 , GS_LOCK_PLUG_RESPONSE_OK = -2 , GS_LOCK_PLUG_RESPONSE_CANCEL = -3 }
Functions
GType gs_lock_plug_get_type (void)
GtkWidget * gs_lock_plug_new (void)
int gs_lock_plug_run (GSLockPlug *plug)
void gs_lock_plug_set_sensitive (GSLockPlug *plug, gboolean sensitive)
void gs_lock_plug_enable_prompt (GSLockPlug *plug, const char *message, gboolean visible)
void gs_lock_plug_disable_prompt (GSLockPlug *plug)
void gs_lock_plug_set_busy (GSLockPlug *plug)
void gs_lock_plug_set_ready (GSLockPlug *plug)
void gs_lock_plug_get_text (GSLockPlug *plug, char **text)
void gs_lock_plug_show_message (GSLockPlug *plug, const char *message)
Macro Definition Documentation
GS_IS_LOCK_PLUG
#define GS_IS_LOCK_PLUG (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), GS_TYPE_LOCK_PLUG))
Definition at line 41 of file gs-lock-plug.h.
Referenced by gs_lock_plug_disable_prompt(), gs_lock_plug_enable_prompt(), gs_lock_plug_run(), gs_lock_plug_set_sensitive(), and gs_lock_plug_show_message().
GS_IS_LOCK_PLUG_CLASS
#define GS_IS_LOCK_PLUG_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), GS_TYPE_LOCK_PLUG))
Definition at line 42 of file gs-lock-plug.h.
GS_LOCK_PLUG
#define GS_LOCK_PLUG (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), GS_TYPE_LOCK_PLUG, GSLockPlug))
Definition at line 39 of file gs-lock-plug.h.
GS_LOCK_PLUG_CLASS
#define GS_LOCK_PLUG_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST((k), GS_TYPE_LOCK_PLUG, GSLockPlugClass))
Definition at line 40 of file gs-lock-plug.h.
GS_LOCK_PLUG_GET_CLASS
#define GS_LOCK_PLUG_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), GS_TYPE_LOCK_PLUG, GSLockPlugClass))
Definition at line 43 of file gs-lock-plug.h.
GS_TYPE_LOCK_PLUG
#define GS_TYPE_LOCK_PLUG (gs_lock_plug_get_type ())
Definition at line 38 of file gs-lock-plug.h.
Referenced by gs_lock_plug_new().
Typedef Documentation
GSLockPlugPrivate
typedef struct GSLockPlugPrivate GSLockPlugPrivate
Definition at line 45 of file gs-lock-plug.h.
Enumeration Type Documentation
GSPlugResponseType
enum GSPlugResponseType
Enumerator
GS_LOCK_PLUG_RESPONSE_NONE
GS_LOCK_PLUG_RESPONSE_OK
GS_LOCK_PLUG_RESPONSE_CANCEL
Definition at line 31 of file gs-lock-plug.h.
Function Documentation
gs_lock_plug_disable_prompt()
void gs_lock_plug_disable_prompt (GSLockPlug * plug)
Definition at line 1458 of file gs-lock-plug.c.
References FALSE, GS_IS_LOCK_PLUG, and GSLockPlug::priv.
gs_lock_plug_enable_prompt()
void gs_lock_plug_enable_prompt (GSLockPlug * plug, const char * message, gboolean visible)
Definition at line 1427 of file gs-lock-plug.c.
References gs_debug, GS_IS_LOCK_PLUG, message(), GSLockPlug::priv, and TRUE.
gs_lock_plug_get_text()
void gs_lock_plug_get_text (GSLockPlug * plug, char ** text)
Definition at line 508 of file gs-lock-plug.c.
References NULL, and GSLockPlug::priv.
gs_lock_plug_get_type()
GType gs_lock_plug_get_type (void)
References message().
gs_lock_plug_new()
GtkWidget * gs_lock_plug_new (void)
Definition at line 2282 of file gs-lock-plug.c.
References GS_TYPE_LOCK_PLUG, NULL, and TRUE.
gs_lock_plug_run()
int gs_lock_plug_run (GSLockPlug * plug)
Definition at line 602 of file gs-lock-plug.c.
References FALSE, GS_IS_LOCK_PLUG, NULL, and TRUE.
gs_lock_plug_set_busy()
void gs_lock_plug_set_busy (GSLockPlug * plug)
Definition at line 1396 of file gs-lock-plug.c.
gs_lock_plug_set_ready()
void gs_lock_plug_set_ready (GSLockPlug * plug)
Definition at line 1412 of file gs-lock-plug.c.
gs_lock_plug_set_sensitive()
void gs_lock_plug_set_sensitive (GSLockPlug * plug, gboolean sensitive)
Definition at line 354 of file gs-lock-plug.c.
References GS_IS_LOCK_PLUG, and GSLockPlug::priv.
gs_lock_plug_show_message()
void gs_lock_plug_show_message (GSLockPlug * plug, const char * message)
Definition at line 1472 of file gs-lock-plug.c.
References GS_IS_LOCK_PLUG, and message().