MATE Desktop Environment: gs-manager.h File Reference
gs-manager.h File Reference
#include "gs-prefs.h"
Classes
struct GSManager
struct GSManagerClass
Macros
#define GS_TYPE_MANAGER (gs_manager_get_type ())
#define GS_MANAGER(o)
#define GS_MANAGER_CLASS(k)
#define GS_IS_MANAGER(o)
#define GS_IS_MANAGER_CLASS(k)
#define GS_MANAGER_GET_CLASS(o)
Typedefs
typedef struct GSManagerPrivate GSManagerPrivate
Functions
GType gs_manager_get_type (void)
GSManager * gs_manager_new (void)
gboolean gs_manager_set_active (GSManager *manager, gboolean active)
gboolean gs_manager_get_active (GSManager *manager)
gboolean gs_manager_cycle (GSManager *manager)
void gs_manager_get_lock_active (GSManager *manager, gboolean *lock_active)
void gs_manager_set_lock_active (GSManager *manager, gboolean lock_active)
void gs_manager_set_keyboard_enabled (GSManager *manager, gboolean enabled)
void gs_manager_set_keyboard_command (GSManager *manager, const char *command)
void gs_manager_set_status_message (GSManager *manager, const char *message)
void gs_manager_get_lock_enabled (GSManager *manager, gboolean *lock_enabled)
void gs_manager_set_lock_enabled (GSManager *manager, gboolean lock_enabled)
void gs_manager_set_lock_timeout (GSManager *manager, glong lock_timeout)
void gs_manager_set_logout_enabled (GSManager *manager, gboolean logout_enabled)
void gs_manager_set_user_switch_enabled (GSManager *manager, gboolean user_switch_enabled)
void gs_manager_set_logout_timeout (GSManager *manager, glong logout_timeout)
void gs_manager_set_logout_command (GSManager *manager, const char *command)
void gs_manager_set_throttled (GSManager *manager, gboolean lock_enabled)
void gs_manager_set_cycle_timeout (GSManager *manager, glong cycle_timeout)
void gs_manager_set_themes (GSManager *manager, GSList *themes)
void gs_manager_set_mode (GSManager *manager, GSSaverMode mode)
void gs_manager_show_message (GSManager *manager, const char *summary, const char *body, const char *icon)
gboolean gs_manager_request_unlock (GSManager *manager)
void gs_manager_cancel_unlock_request (GSManager *manager)
Macro Definition Documentation
GS_IS_MANAGER
#define GS_IS_MANAGER (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), GS_TYPE_MANAGER))
Definition at line 34 of file gs-manager.h.
Referenced by gs_manager_cycle(), gs_manager_get_active(), gs_manager_get_lock_active(), gs_manager_get_lock_enabled(), gs_manager_request_unlock(), gs_manager_set_cycle_timeout(), gs_manager_set_keyboard_command(), gs_manager_set_keyboard_enabled(), gs_manager_set_lock_active(), gs_manager_set_lock_enabled(), gs_manager_set_lock_timeout(), gs_manager_set_logout_command(), gs_manager_set_logout_enabled(), gs_manager_set_logout_timeout(), gs_manager_set_mode(), gs_manager_set_status_message(), gs_manager_set_themes(), gs_manager_set_throttled(), gs_manager_set_user_switch_enabled(), and gs_manager_show_message().
GS_IS_MANAGER_CLASS
#define GS_IS_MANAGER_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), GS_TYPE_MANAGER))
Definition at line 35 of file gs-manager.h.
GS_MANAGER
#define GS_MANAGER (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), GS_TYPE_MANAGER, GSManager))
Definition at line 32 of file gs-manager.h.
Referenced by gs_manager_new().
GS_MANAGER_CLASS
#define GS_MANAGER_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST((k), GS_TYPE_MANAGER, GSManagerClass))
Definition at line 33 of file gs-manager.h.
GS_MANAGER_GET_CLASS
#define GS_MANAGER_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), GS_TYPE_MANAGER, GSManagerClass))
Definition at line 36 of file gs-manager.h.
GS_TYPE_MANAGER
#define GS_TYPE_MANAGER (gs_manager_get_type ())
Definition at line 31 of file gs-manager.h.
Referenced by gs_manager_new().
Typedef Documentation
GSManagerPrivate
typedef struct GSManagerPrivate GSManagerPrivate
Definition at line 38 of file gs-manager.h.
Function Documentation
gs_manager_cancel_unlock_request()
void gs_manager_cancel_unlock_request (GSManager * manager)
Definition at line 1960 of file gs-manager.c.
References gs_window_cancel_unlock_request().
gs_manager_cycle()
gboolean gs_manager_cycle (GSManager * manager)
Definition at line 707 of file gs-manager.c.
References FALSE, gs_debug, GS_IS_MANAGER, NULL, and TRUE.
gs_manager_get_active()
gboolean gs_manager_get_active (GSManager * manager)
Definition at line 1911 of file gs-manager.c.
References FALSE, GS_IS_MANAGER, and NULL.
gs_manager_get_lock_active()
void gs_manager_get_lock_active (GSManager * manager, gboolean * lock_active)
Definition at line 437 of file gs-manager.c.
References FALSE, GS_IS_MANAGER, and NULL.
gs_manager_get_lock_enabled()
void gs_manager_get_lock_enabled (GSManager * manager, gboolean * lock_enabled)
Definition at line 474 of file gs-manager.c.
References FALSE, GS_IS_MANAGER, and NULL.
gs_manager_get_type()
GType gs_manager_get_type (void)
References message().
gs_manager_new()
GSManager * gs_manager_new (void)
Definition at line 1762 of file gs-manager.c.
References GS_MANAGER, GS_TYPE_MANAGER, and NULL.
gs_manager_request_unlock()
gboolean gs_manager_request_unlock (GSManager * manager)
Definition at line 1920 of file gs-manager.c.
References FALSE, gs_debug, gs_fade_finish(), GS_IS_MANAGER, gs_window_request_unlock(), NULL, and TRUE.
Referenced by gs_manager_show_message().
gs_manager_set_active()
gboolean gs_manager_set_active (GSManager * manager, gboolean active)
Definition at line 1893 of file gs-manager.c.
gs_manager_set_cycle_timeout()
void gs_manager_set_cycle_timeout (GSManager * manager, glong cycle_timeout)
Definition at line 768 of file gs-manager.c.
References GS_IS_MANAGER, and NULL.
gs_manager_set_keyboard_command()
void gs_manager_set_keyboard_command (GSManager * manager, const char * command)
Definition at line 664 of file gs-manager.c.
References GS_IS_MANAGER, gs_window_set_keyboard_command(), and NULL.
gs_manager_set_keyboard_enabled()
void gs_manager_set_keyboard_enabled (GSManager * manager, gboolean enabled)
Definition at line 521 of file gs-manager.c.
References FALSE, GS_IS_MANAGER, and gs_window_set_keyboard_enabled().
gs_manager_set_lock_active()
void gs_manager_set_lock_active (GSManager * manager, gboolean lock_active)
Definition at line 454 of file gs-manager.c.
References FALSE, gs_debug, GS_IS_MANAGER, and gs_window_set_lock_enabled().
gs_manager_set_lock_enabled()
void gs_manager_set_lock_enabled (GSManager * manager, gboolean lock_enabled)
Definition at line 491 of file gs-manager.c.
References FALSE, and GS_IS_MANAGER.
gs_manager_set_lock_timeout()
void gs_manager_set_lock_timeout (GSManager * manager, glong lock_timeout)
Definition at line 589 of file gs-manager.c.
References GS_IS_MANAGER, and NULL.
gs_manager_set_logout_command()
void gs_manager_set_logout_command (GSManager * manager, const char * command)
Definition at line 639 of file gs-manager.c.
References GS_IS_MANAGER, gs_window_set_logout_command(), and NULL.
gs_manager_set_logout_enabled()
void gs_manager_set_logout_enabled (GSManager * manager, gboolean logout_enabled)
Definition at line 503 of file gs-manager.c.
References FALSE, GS_IS_MANAGER, and gs_window_set_logout_enabled().
gs_manager_set_logout_timeout()
void gs_manager_set_logout_timeout (GSManager * manager, glong logout_timeout)
Definition at line 621 of file gs-manager.c.
References GS_IS_MANAGER, and gs_window_set_logout_timeout().
gs_manager_set_mode()
void gs_manager_set_mode (GSManager * manager, GSSaverMode mode)
Definition at line 377 of file gs-manager.c.
References GS_IS_MANAGER.
gs_manager_set_status_message()
void gs_manager_set_status_message (GSManager * manager, const char * message)
Definition at line 689 of file gs-manager.c.
References GS_IS_MANAGER, and gs_window_set_status_message().
gs_manager_set_themes()
void gs_manager_set_themes (GSManager * manager, GSList * themes)
Definition at line 395 of file gs-manager.c.
References GS_IS_MANAGER, and NULL.
gs_manager_set_throttled()
void gs_manager_set_throttled (GSManager * manager, gboolean lock_enabled)
Definition at line 412 of file gs-manager.c.
References FALSE, GS_IS_MANAGER, and gs_window_clear().
gs_manager_set_user_switch_enabled()
void gs_manager_set_user_switch_enabled (GSManager * manager, gboolean user_switch_enabled)
Definition at line 539 of file gs-manager.c.
References FALSE, GS_IS_MANAGER, and gs_window_set_user_switch_enabled().
gs_manager_show_message()
void gs_manager_show_message (GSManager * manager, const char * summary, const char * body, const char * icon)
Definition at line 1147 of file gs-manager.c.
References GS_IS_MANAGER, gs_manager_request_unlock(), and gs_window_show_message().