MATE Desktop Environment: gs-monitor.c File Reference
gs-monitor.c File Reference
#include "config.h"
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <X11/extensions/scrnsaver.h>
#include <glib.h>
#include <glib-object.h>
#include <gdk/gdkx.h>
#include "mate-screensaver.h"
#include "gs-manager.h"
#include "gs-watcher.h"
#include "gs-fade.h"
#include "gs-grab.h"
#include "gs-listener-dbus.h"
#include "gs-monitor.h"
#include "gs-prefs.h"
#include "gs-debug.h"
Macros
#define FADE_TIMEOUT 10000
Functions
GSMonitor * gs_monitor_new (void)
gboolean gs_monitor_start (GSMonitor *monitor, GError **error)
Macro Definition Documentation
FADE_TIMEOUT
#define FADE_TIMEOUT 10000
Definition at line 59 of file gs-monitor.c.
Function Documentation
gs_monitor_new()
GSMonitor * gs_monitor_new (void)
Definition at line 464 of file gs-monitor.c.
References GS_MONITOR, GS_TYPE_MONITOR, and NULL.
Referenced by main().
gs_monitor_start()
gboolean gs_monitor_start (GSMonitor * monitor, GError ** error)
Definition at line 473 of file gs-monitor.c.
References error, FALSE, GS_IS_MONITOR, gs_listener_acquire(), and TRUE.
Referenced by main().