MATE Desktop Environment: gs-theme-manager.h File Reference
gs-theme-manager.h File Reference
#include <glib.h>
Classes
struct GSThemeManager
struct GSThemeManagerClass
Macros
#define GS_TYPE_THEME_MANAGER (gs_theme_manager_get_type ())
#define GS_THEME_MANAGER(o)
#define GS_THEME_MANAGER_CLASS(k)
#define GS_IS_THEME_MANAGER(o)
#define GS_IS_THEME_MANAGER_CLASS(k)
#define GS_THEME_MANAGER_GET_CLASS(o)
Typedefs
typedef struct GSThemeManagerPrivate GSThemeManagerPrivate
typedef struct _GSThemeInfo GSThemeInfo
Functions
GType gs_theme_manager_get_type (void)
GSThemeManager * gs_theme_manager_new (void)
GSList * gs_theme_manager_get_info_list (GSThemeManager *manager)
GSThemeInfo * gs_theme_manager_lookup_theme_info (GSThemeManager *manager, const char *theme)
GSThemeInfo * gs_theme_info_ref (GSThemeInfo *info)
void gs_theme_info_unref (GSThemeInfo *info)
const char * gs_theme_info_get_id (GSThemeInfo *info)
const char * gs_theme_info_get_name (GSThemeInfo *info)
const char * gs_theme_info_get_exec (GSThemeInfo *info)
Macro Definition Documentation
GS_IS_THEME_MANAGER
#define GS_IS_THEME_MANAGER (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), GS_TYPE_THEME_MANAGER))
Definition at line 34 of file gs-theme-manager.h.
Referenced by gs_theme_manager_get_info_list(), and gs_theme_manager_lookup_theme_info().
GS_IS_THEME_MANAGER_CLASS
#define GS_IS_THEME_MANAGER_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), GS_TYPE_THEME_MANAGER))
Definition at line 35 of file gs-theme-manager.h.
GS_THEME_MANAGER
#define GS_THEME_MANAGER (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), GS_TYPE_THEME_MANAGER, GSThemeManager))
Definition at line 32 of file gs-theme-manager.h.
Referenced by gs_theme_manager_new().
GS_THEME_MANAGER_CLASS
#define GS_THEME_MANAGER_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST((k), GS_TYPE_THEME_MANAGER, GSThemeManagerClass))
Definition at line 33 of file gs-theme-manager.h.
GS_THEME_MANAGER_GET_CLASS
#define GS_THEME_MANAGER_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), GS_TYPE_THEME_MANAGER, GSThemeManagerClass))
Definition at line 36 of file gs-theme-manager.h.
GS_TYPE_THEME_MANAGER
#define GS_TYPE_THEME_MANAGER (gs_theme_manager_get_type ())
Definition at line 31 of file gs-theme-manager.h.
Referenced by gs_theme_manager_new().
Typedef Documentation
GSThemeInfo
typedef struct _GSThemeInfo GSThemeInfo
Definition at line 51 of file gs-theme-manager.h.
GSThemeManagerPrivate
typedef struct GSThemeManagerPrivate GSThemeManagerPrivate
Definition at line 38 of file gs-theme-manager.h.
Function Documentation
gs_theme_info_get_exec()
const char * gs_theme_info_get_exec (GSThemeInfo * info)
Definition at line 213 of file gs-theme-manager.c.
References NULL.
gs_theme_info_get_id()
const char * gs_theme_info_get_id (GSThemeInfo * info)
Definition at line 197 of file gs-theme-manager.c.
References NULL.
gs_theme_info_get_name()
const char * gs_theme_info_get_name (GSThemeInfo * info)
Definition at line 205 of file gs-theme-manager.c.
References NULL.
gs_theme_info_ref()
GSThemeInfo * gs_theme_info_ref (GSThemeInfo * info)
Definition at line 170 of file gs-theme-manager.c.
References NULL.
gs_theme_info_unref()
void gs_theme_info_unref (GSThemeInfo * info)
Definition at line 181 of file gs-theme-manager.c.
References NULL.
gs_theme_manager_get_info_list()
GSList * gs_theme_manager_get_info_list (GSThemeManager * manager)
Definition at line 348 of file gs-theme-manager.c.
References GS_IS_THEME_MANAGER, matemenu_tree_get_root_directory(), matemenu_tree_item_unref(), and NULL.
gs_theme_manager_get_type()
GType gs_theme_manager_get_type (void)
gs_theme_manager_lookup_theme_info()
GSThemeInfo * gs_theme_manager_lookup_theme_info (GSThemeManager * manager, const char * theme)
Definition at line 298 of file gs-theme-manager.c.
References GS_IS_THEME_MANAGER, name, and NULL.
gs_theme_manager_new()
GSThemeManager * gs_theme_manager_new (void)
Definition at line 438 of file gs-theme-manager.c.
References GS_THEME_MANAGER, GS_TYPE_THEME_MANAGER, and NULL.
Referenced by main().