MATE Desktop Environment: gsearchtool-entry.c File Reference
gsearchtool-entry.c File Reference
#include <string.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include "gsearchtool-entry.h"
Macros
#define MIN_ITEM_LEN 0
#define GSEARCH_HISTORY_ENTRY_HISTORY_LENGTH_DEFAULT 10
Enumerations
enum { PROP_0 , PROP_HISTORY_ID , PROP_HISTORY_LENGTH }
Functions
void gsearch_history_entry_prepend_text (GsearchHistoryEntry *entry, const gchar *text)
void gsearch_history_entry_append_text (GsearchHistoryEntry *entry, const gchar *text)
void gsearch_history_entry_clear (GsearchHistoryEntry *entry)
void gsearch_history_entry_set_history_length (GsearchHistoryEntry *entry, guint history_length)
guint gsearch_history_entry_get_history_length (GsearchHistoryEntry *entry)
gchar * gsearch_history_entry_get_history_id (GsearchHistoryEntry *entry)
void gsearch_history_entry_set_enable_completion (GsearchHistoryEntry *entry, gboolean enable)
gboolean gsearch_history_entry_get_enable_completion (GsearchHistoryEntry *entry)
GtkWidget * gsearch_history_entry_new (const gchar *history_id, gboolean enable_completion)
GtkWidget * gsearch_history_entry_get_entry (GsearchHistoryEntry *entry)
void gsearch_history_entry_set_escape_func (GsearchHistoryEntry *entry, GsearchHistoryEntryEscapeFunc escape_func)
Macro Definition Documentation
GSEARCH_HISTORY_ENTRY_HISTORY_LENGTH_DEFAULT
#define GSEARCH_HISTORY_ENTRY_HISTORY_LENGTH_DEFAULT 10
Definition at line 41 of file gsearchtool-entry.c.
MIN_ITEM_LEN
#define MIN_ITEM_LEN 0
Definition at line 40 of file gsearchtool-entry.c.
Referenced by gsearch_history_entry_set_enable_completion(), and pluma_history_entry_set_enable_completion().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_HISTORY_ID
PROP_HISTORY_LENGTH
Definition at line 34 of file gsearchtool-entry.c.
Function Documentation
gsearch_history_entry_append_text()
void gsearch_history_entry_append_text (GsearchHistoryEntry * entry, const gchar * text)
Definition at line 369 of file gsearchtool-entry.c.
References FALSE, GSEARCH_IS_HISTORY_ENTRY, and NULL.
gsearch_history_entry_clear()
void gsearch_history_entry_clear (GsearchHistoryEntry * entry)
Definition at line 435 of file gsearchtool-entry.c.
References GSEARCH_IS_HISTORY_ENTRY.
gsearch_history_entry_get_enable_completion()
gboolean gsearch_history_entry_get_enable_completion (GsearchHistoryEntry * entry)
Definition at line 534 of file gsearchtool-entry.c.
References FALSE, GSEARCH_IS_HISTORY_ENTRY, NULL, and _GsearchHistoryEntry::priv.
gsearch_history_entry_get_entry()
GtkWidget * gsearch_history_entry_get_entry (GsearchHistoryEntry * entry)
Definition at line 595 of file gsearchtool-entry.c.
References GSEARCH_IS_HISTORY_ENTRY, and NULL.
Referenced by build_search_command(), gsearch_history_entry_set_enable_completion(), and set_clone_command().
gsearch_history_entry_get_history_id()
gchar * gsearch_history_entry_get_history_id (GsearchHistoryEntry * entry)
Definition at line 484 of file gsearchtool-entry.c.
References GSEARCH_IS_HISTORY_ENTRY, NULL, and _GsearchHistoryEntry::priv.
gsearch_history_entry_get_history_length()
guint gsearch_history_entry_get_history_length (GsearchHistoryEntry * entry)
Definition at line 476 of file gsearchtool-entry.c.
References GSEARCH_IS_HISTORY_ENTRY, and _GsearchHistoryEntry::priv.
gsearch_history_entry_new()
GtkWidget * gsearch_history_entry_new (const gchar * history_id, gboolean enable_completion)
Definition at line 542 of file gsearchtool-entry.c.
References GSEARCH_HISTORY_ENTRY, gsearch_history_entry_set_enable_completion(), GSEARCH_TYPE_HISTORY_ENTRY, NULL, and TRUE.
gsearch_history_entry_prepend_text()
void gsearch_history_entry_prepend_text (GsearchHistoryEntry * entry, const gchar * text)
Definition at line 359 of file gsearchtool-entry.c.
References GSEARCH_IS_HISTORY_ENTRY, NULL, and TRUE.
Referenced by build_search_command().
gsearch_history_entry_set_enable_completion()
void gsearch_history_entry_set_enable_completion (GsearchHistoryEntry * entry, gboolean enable)
Definition at line 492 of file gsearchtool-entry.c.
References FALSE, gsearch_history_entry_get_entry(), GSEARCH_IS_HISTORY_ENTRY, MIN_ITEM_LEN, NULL, _GsearchHistoryEntry::priv, and TRUE.
Referenced by gsearch_history_entry_new().
gsearch_history_entry_set_escape_func()
void gsearch_history_entry_set_escape_func (GsearchHistoryEntry * entry, GsearchHistoryEntryEscapeFunc escape_func)
Definition at line 621 of file gsearchtool-entry.c.
References GSEARCH_IS_HISTORY_ENTRY, and NULL.
gsearch_history_entry_set_history_length()
void gsearch_history_entry_set_history_length (GsearchHistoryEntry * entry, guint history_length)
Definition at line 464 of file gsearchtool-entry.c.
References GSEARCH_IS_HISTORY_ENTRY, and _GsearchHistoryEntry::priv.