MATE Desktop Environment: gsearchtool.h File Reference
gsearchtool.h File Reference
#include <gtk/gtk.h>
Classes
struct _GSearchWindow
struct _GSearchCommandDetails
struct _GSearchConstraint
struct _GSearchWindowClass
struct _GSearchMonitor
Macros
#define GSEARCH_TYPE_WINDOW gsearch_window_get_type()
#define GSEARCH_WINDOW(obj)
#define GSEARCH_WINDOW_CLASS(klass)
#define GSEARCH_IS_WINDOW(obj)
#define GSEARCH_IS_WINDOW_CLASS(klass)
#define GSEARCH_WINDOW_GET_CLASS(obj)
#define MATE_SEARCH_TOOL_ICON "system-search"
#define MINIMUM_WINDOW_WIDTH 420
#define MINIMUM_WINDOW_HEIGHT 310
#define DEFAULT_WINDOW_WIDTH 554
#define DEFAULT_WINDOW_HEIGHT 350
#define WINDOW_HEIGHT_STEP 35
#define NUM_VISIBLE_COLUMNS 5
#define CAJA_PREFERENCES_SCHEMA "org.mate.caja.preferences"
Typedefs
typedef struct _GSearchWindow GSearchWindow
typedef struct _GSearchWindowClass GSearchWindowClass
typedef struct _GSearchCommandDetails GSearchCommandDetails
typedef struct _GSearchConstraint GSearchConstraint
typedef struct _GSearchMonitor GSearchMonitor
Enumerations
enum GSearchCommandStatus {
STOPPED , ABORTED , RUNNING , MAKE_IT_STOP ,
MAKE_IT_QUIT
}
enum CajaSpeedTradeoff { SPEED_TRADEOFF_ALWAYS = 0 , SPEED_TRADEOFF_LOCAL_ONLY , SPEED_TRADEOFF_NEVER }
enum CajaDateFormat { CAJA_DATE_FORMAT_LOCALE = 0 , CAJA_DATE_FORMAT_ISO , CAJA_DATE_FORMAT_INFORMAL }
enum GSearchResultColumns {
COLUMN_ICON , COLUMN_NAME , COLUMN_RELATIVE_PATH , COLUMN_LOCALE_FILE ,
COLUMN_READABLE_SIZE , COLUMN_SIZE , COLUMN_TYPE , COLUMN_READABLE_DATE ,
COLUMN_DATE , COLUMN_MONITOR , COLUMN_NO_FILES_FOUND , NUM_COLUMNS
}
Functions
GType gsearch_window_get_type (void)
gchar * build_search_command (GSearchWindow *gsearch, gboolean first_pass)
void spawn_search_command (GSearchWindow *gsearch, gchar *command)
void add_constraint (GSearchWindow *gsearch, gint constraint_id, gchar *value, gboolean show_constraint)
void update_constraint_info (GSearchConstraint *constraint, gchar *info)
void remove_constraint (gint constraint_id)
void set_constraint_gsettings_boolean (gint constraint_id, gboolean flag)
void set_constraint_selected_state (GSearchWindow *gsearch, gint constraint_id, gboolean state)
void set_clone_command (GSearchWindow *gsearch, gint *argcp, gchar ***argvp, gpointer client_data, gboolean escape_values)
void update_search_counts (GSearchWindow *gsearch)
gboolean tree_model_iter_free_monitor (GtkTreeModel *model, GtkTreePath *path, GtkTreeIter *iter, gpointer data)
Macro Definition Documentation
CAJA_PREFERENCES_SCHEMA
#define CAJA_PREFERENCES_SCHEMA "org.mate.caja.preferences"
Definition at line 54 of file gsearchtool.h.
DEFAULT_WINDOW_HEIGHT
#define DEFAULT_WINDOW_HEIGHT 350
Definition at line 51 of file gsearchtool.h.
Referenced by gsearchtool_get_stored_window_geometry().
DEFAULT_WINDOW_WIDTH
#define DEFAULT_WINDOW_WIDTH 554
Definition at line 50 of file gsearchtool.h.
Referenced by gsearchtool_get_stored_window_geometry().
GSEARCH_IS_WINDOW
#define GSEARCH_IS_WINDOW (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), GSEARCH_TYPE_WINDOW))
Definition at line 40 of file gsearchtool.h.
GSEARCH_IS_WINDOW_CLASS
#define GSEARCH_IS_WINDOW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), GSEARCH_TYPE_WINDOW))
Definition at line 42 of file gsearchtool.h.
GSEARCH_TYPE_WINDOW
#define GSEARCH_TYPE_WINDOW gsearch_window_get_type()
Definition at line 35 of file gsearchtool.h.
Referenced by main().
GSEARCH_WINDOW
#define GSEARCH_WINDOW (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), GSEARCH_TYPE_WINDOW, GSearchWindow))
Definition at line 36 of file gsearchtool.h.
Referenced by main().
GSEARCH_WINDOW_CLASS
#define GSEARCH_WINDOW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), GSEARCH_TYPE_WINDOW, GSearchWindowClass))
Definition at line 38 of file gsearchtool.h.
GSEARCH_WINDOW_GET_CLASS
#define GSEARCH_WINDOW_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), GSEARCH_TYPE_WINDOW, GSearchWindowClass))
Definition at line 44 of file gsearchtool.h.
MATE_SEARCH_TOOL_ICON
#define MATE_SEARCH_TOOL_ICON "system-search"
Definition at line 47 of file gsearchtool.h.
Referenced by main().
MINIMUM_WINDOW_HEIGHT
#define MINIMUM_WINDOW_HEIGHT 310
Definition at line 49 of file gsearchtool.h.
Referenced by click_expander_cb(), and gsearchtool_get_stored_window_geometry().
MINIMUM_WINDOW_WIDTH
#define MINIMUM_WINDOW_WIDTH 420
Definition at line 48 of file gsearchtool.h.
Referenced by click_expander_cb(), and gsearchtool_get_stored_window_geometry().
NUM_VISIBLE_COLUMNS
#define NUM_VISIBLE_COLUMNS 5
Definition at line 53 of file gsearchtool.h.
Referenced by columns_changed_cb().
WINDOW_HEIGHT_STEP
#define WINDOW_HEIGHT_STEP 35
Definition at line 52 of file gsearchtool.h.
Referenced by add_constraint(), and remove_constraint_cb().
Typedef Documentation
GSearchCommandDetails
typedef struct _GSearchCommandDetails GSearchCommandDetails
Definition at line 93 of file gsearchtool.h.
GSearchConstraint
typedef struct _GSearchConstraint GSearchConstraint
Definition at line 94 of file gsearchtool.h.
GSearchMonitor
typedef struct _GSearchMonitor GSearchMonitor
Definition at line 95 of file gsearchtool.h.
GSearchWindow
typedef struct _GSearchWindow GSearchWindow
Definition at line 91 of file gsearchtool.h.
GSearchWindowClass
typedef struct _GSearchWindowClass GSearchWindowClass
Definition at line 92 of file gsearchtool.h.
Enumeration Type Documentation
CajaDateFormat
enum CajaDateFormat
Enumerator
CAJA_DATE_FORMAT_LOCALE
CAJA_DATE_FORMAT_ISO
CAJA_DATE_FORMAT_INFORMAL
Definition at line 70 of file gsearchtool.h.
CajaSpeedTradeoff
enum CajaSpeedTradeoff
Enumerator
SPEED_TRADEOFF_ALWAYS
SPEED_TRADEOFF_LOCAL_ONLY
SPEED_TRADEOFF_NEVER
Definition at line 64 of file gsearchtool.h.
GSearchCommandStatus
enum GSearchCommandStatus
Enumerator
STOPPED
ABORTED
RUNNING
MAKE_IT_STOP
MAKE_IT_QUIT
Definition at line 56 of file gsearchtool.h.
GSearchResultColumns
enum GSearchResultColumns
Enumerator
COLUMN_ICON
COLUMN_NAME
COLUMN_RELATIVE_PATH
COLUMN_LOCALE_FILE
COLUMN_READABLE_SIZE
COLUMN_SIZE
COLUMN_TYPE
COLUMN_READABLE_DATE
COLUMN_DATE
COLUMN_MONITOR
COLUMN_NO_FILES_FOUND
NUM_COLUMNS
Definition at line 76 of file gsearchtool.h.
Function Documentation
add_constraint()
void add_constraint (GSearchWindow * gsearch, gint constraint_id, gchar * value, gboolean show_constraint)
Definition at line 2106 of file gsearchtool.c.
References _GSearchWindow::available_options_selected_list, _GSearchWindow::available_options_vbox, _GSearchConstraint::constraint_id, FALSE, set_constraint_gsettings_boolean(), set_constraint_selected_state(), _GSearchWindow::show_more_options_expander, TRUE, _GSearchWindow::window, _GSearchWindow::window_geometry, and WINDOW_HEIGHT_STEP.
build_search_command()
gchar * build_search_command (GSearchWindow * gsearch, gboolean first_pass)
Definition at line 559 of file gsearchtool.c.
References _GSearchWindow::available_options_selected_list, _GSearchWindow::available_options_vbox, backslash_backslash_characters(), backslash_special_characters(), _GSearchWindow::caja_schema_exists, _GSearchWindow::caja_settings, _GSearchWindow::command_details, _GSearchConstraint::constraint_id, _GSearchConstraint::data, error, escape_double_quotes(), FALSE, GSEARCH_HISTORY_ENTRY, gsearch_history_entry_get_entry(), gsearch_history_entry_prepend_text(), _GSearchCommandDetails::is_command_first_pass, _GSearchCommandDetails::is_command_regex_matching_enabled, _GSearchCommandDetails::is_command_second_pass_enabled, _GSearchCommandDetails::is_command_show_hidden_files_enabled, _GSearchCommandDetails::is_command_using_quick_mode, _GSearchWindow::is_locate_database_available, is_quick_search_excluded_path(), _GSearchWindow::look_in_folder_button, _GSearchCommandDetails::look_in_folder_string, _GSearchWindow::mate_search_tool_settings, _GSearchWindow::name_contains_entry, _GSearchCommandDetails::name_contains_pattern_string, _GSearchCommandDetails::name_contains_regex_string, NULL, _GSearchConstraint::number, regex, SEARCH_CONSTRAINT_TYPE_BOOLEAN, SEARCH_CONSTRAINT_TYPE_DATE_AFTER, SEARCH_CONSTRAINT_TYPE_DATE_BEFORE, SEARCH_CONSTRAINT_TYPE_NUMERIC, SEARCH_CONSTRAINT_TYPE_TEXT, _GSearchWindow::show_thumbnails, _GSearchWindow::show_thumbnails_file_size_limit, SPEED_TRADEOFF_ALWAYS, SPEED_TRADEOFF_LOCAL_ONLY, _GSearchConstraint::text, _GSearchConstraint::time, TRUE, and _GSearchWindow::window.
Referenced by click_find_cb().
gsearch_window_get_type()
GType gsearch_window_get_type (void)
Definition at line 2961 of file gsearchtool.c.
References NULL.
remove_constraint()
void remove_constraint (gint constraint_id)
References data.
set_clone_command()
void set_clone_command (GSearchWindow * gsearch, gint * argcp, gchar *** argvp, gpointer client_data, gboolean escape_values)
Definition at line 2502 of file gsearchtool.c.
References _GSearchWindow::available_options_selected_list, _GSearchWindow::available_options_vbox, _GSearchConstraint::constraint_id, _GSearchConstraint::data, GSEARCH_HISTORY_ENTRY, gsearch_history_entry_get_entry(), _GSearchWindow::look_in_folder_button, _GSearchWindow::name_contains_entry, NULL, _GSearchConstraint::number, SEARCH_CONSTRAINT_CONTAINS_THE_TEXT, SEARCH_CONSTRAINT_DATE_MODIFIED_AFTER, SEARCH_CONSTRAINT_DATE_MODIFIED_BEFORE, SEARCH_CONSTRAINT_FILE_IS_EMPTY, SEARCH_CONSTRAINT_FILE_IS_NOT_NAMED, SEARCH_CONSTRAINT_FILE_MATCHES_REGULAR_EXPRESSION, SEARCH_CONSTRAINT_FOLLOW_SYMBOLIC_LINKS, SEARCH_CONSTRAINT_MAXIMUM_POSSIBLE, SEARCH_CONSTRAINT_OWNED_BY_GROUP, SEARCH_CONSTRAINT_OWNED_BY_USER, SEARCH_CONSTRAINT_OWNER_IS_UNRECOGNIZED, SEARCH_CONSTRAINT_SEARCH_OTHER_FILESYSTEMS, SEARCH_CONSTRAINT_SHOW_HIDDEN_FILES_AND_FOLDERS, SEARCH_CONSTRAINT_SIZE_IS_LESS_THAN, SEARCH_CONSTRAINT_SIZE_IS_MORE_THAN, _GSearchConstraint::text, and _GSearchConstraint::time.
Referenced by save_session_cb().
set_constraint_gsettings_boolean()
void set_constraint_gsettings_boolean (gint constraint_id, gboolean flag)
Definition at line 1188 of file gsearchtool.c.
References SEARCH_CONSTRAINT_CONTAINS_THE_TEXT, SEARCH_CONSTRAINT_DATE_MODIFIED_AFTER, SEARCH_CONSTRAINT_DATE_MODIFIED_BEFORE, SEARCH_CONSTRAINT_FILE_IS_EMPTY, SEARCH_CONSTRAINT_FILE_IS_NOT_NAMED, SEARCH_CONSTRAINT_FILE_MATCHES_REGULAR_EXPRESSION, SEARCH_CONSTRAINT_FOLLOW_SYMBOLIC_LINKS, SEARCH_CONSTRAINT_OWNED_BY_GROUP, SEARCH_CONSTRAINT_OWNED_BY_USER, SEARCH_CONSTRAINT_OWNER_IS_UNRECOGNIZED, SEARCH_CONSTRAINT_SEARCH_OTHER_FILESYSTEMS, SEARCH_CONSTRAINT_SHOW_HIDDEN_FILES_AND_FOLDERS, SEARCH_CONSTRAINT_SIZE_IS_LESS_THAN, and SEARCH_CONSTRAINT_SIZE_IS_MORE_THAN.
Referenced by add_constraint(), and remove_constraint_cb().
set_constraint_selected_state()
void set_constraint_selected_state (GSearchWindow * gsearch, gint constraint_id, gboolean state)
Definition at line 1165 of file gsearchtool.c.
References _GSearchWindow::available_options_add_button, _GSearchWindow::available_options_combo_box, _GSearchWindow::available_options_label, FALSE, idx, SEARCH_CONSTRAINT_TYPE_NONE, and TRUE.
Referenced by add_constraint(), and remove_constraint_cb().
spawn_search_command()
void spawn_search_command (GSearchWindow * gsearch, gchar * command)
Definition at line 1850 of file gsearchtool.c.
References _, CAJA_DATE_FORMAT_LOCALE, _GSearchWindow::caja_schema_exists, _GSearchWindow::caja_settings, _GSearchWindow::command_details, _GSearchCommandDetails::command_pid, _GSearchCommandDetails::command_status, error, _GSearchCommandDetails::is_command_first_pass, _GSearchCommandDetails::look_in_folder_string, _GSearchCommandDetails::name_contains_pattern_string, _GSearchCommandDetails::name_contains_regex_string, NULL, RUNNING, _GSearchWindow::search_results_date_column, _GSearchWindow::search_results_date_format, _GSearchWindow::search_results_filename_hash_table, _GSearchWindow::search_results_folder_column, _GSearchWindow::search_results_list_store, _GSearchWindow::search_results_pixbuf_hash_table, _GSearchWindow::search_results_size_column, _GSearchWindow::search_results_tree_view, _GSearchWindow::search_results_type_column, tree_model_iter_free_monitor(), TRUE, and _GSearchWindow::window.
Referenced by click_find_cb().
tree_model_iter_free_monitor()
gboolean tree_model_iter_free_monitor (GtkTreeModel * model, GtkTreePath * path, GtkTreeIter * iter, gpointer data)
Definition at line 1079 of file gsearchtool.c.
References COLUMN_MONITOR, data, and FALSE.
Referenced by file_changed_cb(), move_to_trash_cb(), and spawn_search_command().
update_constraint_info()
void update_constraint_info (GSearchConstraint * constraint, gchar * info)
Definition at line 1144 of file gsearchtool.c.
References _, _GSearchConstraint::constraint_id, _GSearchConstraint::data, _GSearchConstraint::number, SEARCH_CONSTRAINT_TYPE_DATE_AFTER, SEARCH_CONSTRAINT_TYPE_DATE_BEFORE, SEARCH_CONSTRAINT_TYPE_NUMERIC, SEARCH_CONSTRAINT_TYPE_TEXT, _GSearchConstraint::text, and _GSearchConstraint::time.
Referenced by constraint_update_info_cb().
update_search_counts()
void update_search_counts (GSearchWindow * gsearch)
Definition at line 1006 of file gsearchtool.c.
References _, ABORTED, _GSearchWindow::command_details, _GSearchCommandDetails::command_status, _GSearchWindow::files_found_label, NULL, _GSearchWindow::search_results_list_store, and _GSearchWindow::window.
Referenced by file_changed_cb(), and move_to_trash_cb().