MATE Desktop Environment: gsearchtool-callbacks.c File Reference
gsearchtool-callbacks.c File Reference
#include <string.h>
#include <signal.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <sys/types.h>
#include <unistd.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include "gsearchtool.h"
#include "gsearchtool-callbacks.h"
#include "gsearchtool-support.h"
Macros
#define SILENT_WINDOW_OPEN_LIMIT 5
Functions
void version_cb (const gchar *option_name, const gchar *value, gpointer data, GError **error)
void quit_session_cb (EggSMClient *client, gpointer data)
void quit_cb (GtkWidget *widget, GdkEvent *event, gpointer data)
void click_close_cb (GtkWidget *widget, gpointer data)
void click_find_cb (GtkWidget *widget, gpointer data)
void click_stop_cb (GtkWidget *widget, gpointer data)
void click_help_cb (GtkWidget *widget, gpointer data)
void click_expander_cb (GObject *object, GParamSpec *param_spec, gpointer data)
void size_allocate_cb (GtkWidget *widget, GtkAllocation *allocation, gpointer data)
void add_constraint_cb (GtkWidget *widget, gpointer data)
void remove_constraint_cb (GtkWidget *widget, gpointer data)
void constraint_activate_cb (GtkWidget *widget, gpointer data)
void constraint_update_info_cb (GtkWidget *widget, gpointer data)
void name_contains_activate_cb (GtkWidget *widget, gpointer data)
void look_in_folder_changed_cb (GtkWidget *widget, gpointer data)
void open_file_event_cb (GtkWidget *widget, GdkEventButton *event, gpointer data)
void open_file_cb (GtkMenuItem *action, gpointer data)
void open_folder_cb (GtkAction *action, gpointer data)
void copy_path_cb (GtkAction *action, gpointer data)
void file_changed_cb (GFileMonitor *handle, const gchar *monitor_uri, const gchar *info_uri, GFileMonitorEvent event_type, gpointer data)
void move_to_trash_cb (GtkAction *action, gpointer data)
gboolean file_button_press_event_cb (GtkWidget *widget, GdkEventButton *event, gpointer data)
gboolean file_key_press_event_cb (GtkWidget *widget, GdkEventKey *event, gpointer data)
gboolean file_button_release_event_cb (GtkWidget *widget, GdkEventButton *event, gpointer data)
gboolean file_event_after_cb (GtkWidget *widget, GdkEventButton *event, gpointer data)
gboolean file_motion_notify_cb (GtkWidget *widget, GdkEventMotion *event, gpointer user_data)
gboolean file_leave_notify_cb (GtkWidget *widget, GdkEventCrossing *event, gpointer user_data)
void drag_begin_file_cb (GtkWidget *widget, GdkDragContext *context, gpointer data)
void drag_file_cb (GtkWidget *widget, GdkDragContext *context, GtkSelectionData *selection_data, guint info, guint drag_time, gpointer data)
void show_file_selector_cb (GtkAction *action, gpointer data)
void save_results_cb (GtkWidget *chooser, gint response, gpointer data)
void save_session_cb (EggSMClient *client, GKeyFile *state_file, gpointer client_data)
gboolean key_press_cb (GtkWidget *widget, GdkEventKey *event, gpointer data)
gboolean not_running_timeout_cb (gpointer data)
void disable_quick_search_cb (GtkWidget *dialog, gint response, gpointer data)
void single_click_to_activate_key_changed_cb (GSettings *settings, gchar *key, gpointer user_data)
void columns_changed_cb (GtkTreeView *treeview, gpointer user_data)
gboolean window_state_event_cb (GtkWidget *widget, GdkEventWindowState *event, gpointer data)
Variables
gboolean row_selected_by_button_press_event
Macro Definition Documentation
SILENT_WINDOW_OPEN_LIMIT
#define SILENT_WINDOW_OPEN_LIMIT 5
Definition at line 45 of file gsearchtool-callbacks.c.
Function Documentation
add_constraint_cb()
void add_constraint_cb (GtkWidget * widget, gpointer data)
Definition at line 245 of file gsearchtool-callbacks.c.
References _GSearchWindow::available_options_combo_box, data, FALSE, idx, and NULL.
click_close_cb()
void click_close_cb (GtkWidget * widget, gpointer data)
Definition at line 120 of file gsearchtool-callbacks.c.
References data.
click_expander_cb()
void click_expander_cb (GObject * object, GParamSpec * param_spec, gpointer data)
Definition at line 210 of file gsearchtool-callbacks.c.
References _GSearchWindow::available_options_vbox, data, MINIMUM_WINDOW_HEIGHT, MINIMUM_WINDOW_WIDTH, TRUE, _GSearchWindow::window, and _GSearchWindow::window_geometry.
click_find_cb()
void click_find_cb (GtkWidget * widget, gpointer data)
Definition at line 127 of file gsearchtool-callbacks.c.
References ABORTED, build_search_command(), _GSearchWindow::command_details, _GSearchCommandDetails::command_status, data, _GSearchCommandDetails::is_command_timeout_enabled, NULL, spawn_search_command(), STOPPED, and TRUE.
Referenced by constraint_activate_cb(), and name_contains_activate_cb().
click_help_cb()
void click_help_cb (GtkWidget * widget, gpointer data)
Definition at line 176 of file gsearchtool-callbacks.c.
References _, data, error, and NULL.
click_stop_cb()
void click_stop_cb (GtkWidget * widget, gpointer data)
Definition at line 148 of file gsearchtool-callbacks.c.
References _GSearchWindow::command_details, _GSearchCommandDetails::command_pid, _GSearchCommandDetails::command_status, data, FALSE, MAKE_IT_STOP, NULL, RUNNING, and _GSearchWindow::stop_button.
Referenced by key_press_cb().
columns_changed_cb()
void columns_changed_cb (GtkTreeView * treeview, gpointer user_data)
Definition at line 2019 of file gsearchtool-callbacks.c.
References gsearchtool_get_columns_order(), _GSearchWindow::mate_search_tool_settings, NUM_VISIBLE_COLUMNS, and user_data.
constraint_activate_cb()
void constraint_activate_cb (GtkWidget * widget, gpointer data)
Definition at line 283 of file gsearchtool-callbacks.c.
References click_find_cb(), data, and _GSearchWindow::find_button.
constraint_update_info_cb()
void constraint_update_info_cb (GtkWidget * widget, gpointer data)
Definition at line 295 of file gsearchtool-callbacks.c.
References data, and update_constraint_info().
copy_path_cb()
void copy_path_cb (GtkAction * action, gpointer data)
Definition at line 663 of file gsearchtool-callbacks.c.
References action, COLUMN_LOCALE_FILE, data, _GSearchWindow::search_results_list_store, and _GSearchWindow::search_results_selection.
disable_quick_search_cb()
void disable_quick_search_cb (GtkWidget * dialog, gint response, gpointer data)
Definition at line 1989 of file gsearchtool-callbacks.c.
References data, _GSearchWindow::mate_search_tool_settings, and TRUE.
drag_begin_file_cb()
void drag_begin_file_cb (GtkWidget * widget, GdkDragContext * context, gpointer data)
Definition at line 1607 of file gsearchtool-callbacks.c.
References COLUMN_ICON, data, _GSearchWindow::search_results_list_store, and _GSearchWindow::search_results_selection.
drag_file_cb()
void drag_file_cb (GtkWidget * widget, GdkDragContext * context, GtkSelectionData * selection_data, guint info, guint drag_time, gpointer data)
Definition at line 1646 of file gsearchtool-callbacks.c.
References COLUMN_LOCALE_FILE, COLUMN_NAME, COLUMN_NO_FILES_FOUND, data, FALSE, idx, NULL, _GSearchWindow::search_results_list_store, and _GSearchWindow::search_results_selection.
file_button_press_event_cb()
gboolean file_button_press_event_cb (GtkWidget * widget, GdkEventButton * event, gpointer data)
Definition at line 961 of file gsearchtool-callbacks.c.
References data, FALSE, NULL, row_selected_by_button_press_event, and TRUE.
file_button_release_event_cb()
gboolean file_button_release_event_cb (GtkWidget * widget, GdkEventButton * event, gpointer data)
Definition at line 1353 of file gsearchtool-callbacks.c.
References COLUMN_LOCALE_FILE, COLUMN_NAME, COLUMN_NO_FILES_FOUND, data, FALSE, idx, _GSearchWindow::is_search_results_single_click_to_activate, NULL, open_file_cb(), row_selected_by_button_press_event, _GSearchWindow::search_results_list_store, _GSearchWindow::search_results_popup_menu, _GSearchWindow::search_results_selection, _GSearchWindow::search_results_tree_view, and TRUE.
file_changed_cb()
void file_changed_cb (GFileMonitor * handle, const gchar * monitor_uri, const gchar * info_uri, GFileMonitorEvent event_type, gpointer data)
Definition at line 690 of file gsearchtool-callbacks.c.
References data, NULL, tree_model_iter_free_monitor(), and update_search_counts().
file_event_after_cb()
gboolean file_event_after_cb (GtkWidget * widget, GdkEventButton * event, gpointer data)
Definition at line 1495 of file gsearchtool-callbacks.c.
References data, FALSE, _GSearchWindow::is_search_results_single_click_to_activate, NULL, open_file_cb(), _GSearchWindow::search_results_selection, _GSearchWindow::search_results_tree_view, and TRUE.
file_key_press_event_cb()
gboolean file_key_press_event_cb (GtkWidget * widget, GdkEventKey * event, gpointer data)
Definition at line 991 of file gsearchtool-callbacks.c.
References data, FALSE, move_to_trash_cb(), NULL, open_file_cb(), and TRUE.
file_leave_notify_cb()
gboolean file_leave_notify_cb (GtkWidget * widget, GdkEventCrossing * event, gpointer user_data)
Definition at line 1582 of file gsearchtool-callbacks.c.
References FALSE, _GSearchWindow::is_search_results_single_click_to_activate, NULL, _GSearchWindow::search_results_hover_path, _GSearchWindow::search_results_list_store, TRUE, and user_data.
file_motion_notify_cb()
gboolean file_motion_notify_cb (GtkWidget * widget, GdkEventMotion * event, gpointer user_data)
Definition at line 1521 of file gsearchtool-callbacks.c.
References FALSE, _GSearchWindow::is_search_results_single_click_to_activate, NULL, _GSearchWindow::search_results_hover_path, _GSearchWindow::search_results_list_store, _GSearchWindow::search_results_tree_view, and user_data.
key_press_cb()
gboolean key_press_cb (GtkWidget * widget, GdkEventKey * event, gpointer data)
Definition at line 1931 of file gsearchtool-callbacks.c.
References click_stop_cb(), COLUMN_NO_FILES_FOUND, _GSearchWindow::command_details, _GSearchCommandDetails::command_status, data, FALSE, _GSearchCommandDetails::is_command_timeout_enabled, NULL, quit_cb(), RUNNING, _GSearchWindow::search_results_list_store, _GSearchWindow::search_results_popup_menu, _GSearchWindow::search_results_selection, and TRUE.
look_in_folder_changed_cb()
void look_in_folder_changed_cb (GtkWidget * widget, gpointer data)
Definition at line 318 of file gsearchtool-callbacks.c.
References data, _GSearchWindow::look_in_folder_button, _GSearchWindow::mate_search_tool_settings, and NULL.
move_to_trash_cb()
void move_to_trash_cb (GtkAction * action, gpointer data)
Definition at line 824 of file gsearchtool-callbacks.c.
References _, action, COLUMN_LOCALE_FILE, COLUMN_NAME, COLUMN_NO_FILES_FOUND, _GSearchWindow::command_details, _GSearchCommandDetails::command_status, data, error, FALSE, idx, message(), NULL, RUNNING, _GSearchWindow::search_results_list_store, _GSearchWindow::search_results_selection, tree_model_iter_free_monitor(), TRUE, update_search_counts(), and _GSearchWindow::window.
Referenced by file_key_press_event_cb().
name_contains_activate_cb()
void name_contains_activate_cb (GtkWidget * widget, gpointer data)
Definition at line 306 of file gsearchtool-callbacks.c.
References click_find_cb(), data, and _GSearchWindow::find_button.
not_running_timeout_cb()
gboolean not_running_timeout_cb (gpointer data)
Definition at line 1980 of file gsearchtool-callbacks.c.
References _GSearchWindow::command_details, data, FALSE, and _GSearchCommandDetails::is_command_timeout_enabled.
open_file_cb()
void open_file_cb (GtkMenuItem * action, gpointer data)
Definition at line 452 of file gsearchtool-callbacks.c.
References _, action, COLUMN_LOCALE_FILE, COLUMN_NAME, COLUMN_NO_FILES_FOUND, data, FALSE, idx, launch_file(), NULL, open_file_with_application(), open_file_with_filemanager(), _GSearchWindow::search_results_list_store, _GSearchWindow::search_results_selection, SILENT_WINDOW_OPEN_LIMIT, and _GSearchWindow::window.
Referenced by file_button_release_event_cb(), file_event_after_cb(), file_key_press_event_cb(), and open_file_event_cb().
open_file_event_cb()
void open_file_event_cb (GtkWidget * widget, GdkEventButton * event, gpointer data)
Definition at line 444 of file gsearchtool-callbacks.c.
References data, and open_file_cb().
open_folder_cb()
void open_folder_cb (GtkAction * action, gpointer data)
Definition at line 585 of file gsearchtool-callbacks.c.
References action, COLUMN_LOCALE_FILE, COLUMN_RELATIVE_PATH, data, FALSE, idx, NULL, open_file_with_application(), open_file_with_filemanager(), _GSearchWindow::search_results_list_store, _GSearchWindow::search_results_selection, SILENT_WINDOW_OPEN_LIMIT, and _GSearchWindow::window.
quit_cb()
void quit_cb (GtkWidget * widget, GdkEvent * event, gpointer data)
Definition at line 112 of file gsearchtool-callbacks.c.
References data.
Referenced by key_press_cb().
quit_session_cb()
void quit_session_cb (EggSMClient * client, gpointer data)
Definition at line 105 of file gsearchtool-callbacks.c.
References data.
Referenced by main().
remove_constraint_cb()
void remove_constraint_cb (GtkWidget * widget, gpointer data)
Definition at line 256 of file gsearchtool-callbacks.c.
References _GSearchWindow::available_options_selected_list, _GSearchWindow::available_options_vbox, _GSearchConstraint::constraint_id, data, FALSE, set_constraint_gsettings_boolean(), set_constraint_selected_state(), _GSearchWindow::window, _GSearchWindow::window_geometry, and WINDOW_HEIGHT_STEP.
save_results_cb()
void save_results_cb (GtkWidget * chooser, gint response, gpointer data)
Definition at line 1844 of file gsearchtool-callbacks.c.
References _, COLUMN_LOCALE_FILE, data, idx, NULL, _GSearchWindow::save_results_as_default_filename, _GSearchWindow::search_results_list_store, TRUE, and _GSearchWindow::window.
Referenced by show_file_selector_cb().
save_session_cb()
void save_session_cb (EggSMClient * client, GKeyFile * state_file, gpointer client_data)
Definition at line 1918 of file gsearchtool-callbacks.c.
References egg_sm_client_set_restart_command(), FALSE, and set_clone_command().
Referenced by main().
show_file_selector_cb()
void show_file_selector_cb (GtkAction * action, gpointer data)
Definition at line 1709 of file gsearchtool-callbacks.c.
References _, action, data, NULL, _GSearchWindow::save_results_as_default_filename, save_results_cb(), TRUE, and _GSearchWindow::window.
single_click_to_activate_key_changed_cb()
void single_click_to_activate_key_changed_cb (GSettings * settings, gchar * key, gpointer user_data)
Definition at line 2003 of file gsearchtool-callbacks.c.
References FALSE, _GSearchWindow::is_search_results_single_click_to_activate, key, TRUE, and user_data.
size_allocate_cb()
void size_allocate_cb (GtkWidget * widget, GtkAllocation * allocation, gpointer data)
Definition at line 235 of file gsearchtool-callbacks.c.
References data.
version_cb()
void version_cb (const gchar * option_name, const gchar * value, gpointer data, GError ** error)
Definition at line 95 of file gsearchtool-callbacks.c.
References data, error, and VERSION.
window_state_event_cb()
gboolean window_state_event_cb (GtkWidget * widget, GdkEventWindowState * event, gpointer data)
Definition at line 2040 of file gsearchtool-callbacks.c.
References data, FALSE, _GSearchWindow::is_window_maximized, and TRUE.
Variable Documentation
row_selected_by_button_press_event
gboolean row_selected_by_button_press_event
Definition at line 47 of file gsearchtool-callbacks.c.
Referenced by file_button_press_event_cb(), and file_button_release_event_cb().