MATE Desktop Environment: gsearchtool-entry.h File Reference
gsearchtool-entry.h File Reference
Classes
struct _GsearchHistoryEntryClass
struct _GsearchHistoryEntry
Macros
#define GSEARCH_TYPE_HISTORY_ENTRY (gsearch_history_entry_get_type())
#define GSEARCH_HISTORY_ENTRY(obj)
#define GSEARCH_HISTORY_ENTRY_CLASS(klass)
#define GSEARCH_IS_HISTORY_ENTRY(obj)
#define GSEARCH_IS_HISTORY_ENTRY_CLASS(klass)
#define GSEARCH_HISTORY_ENTRY_GET_CLASS(obj)
Typedefs
typedef struct _GsearchHistoryEntry GsearchHistoryEntry
typedef struct _GsearchHistoryEntryClass GsearchHistoryEntryClass
typedef struct _GsearchHistoryEntryPrivate GsearchHistoryEntryPrivate
typedef gchar *(* GsearchHistoryEntryEscapeFunc) (const gchar *str)
Functions
GType gsearch_history_entry_get_type (void)
GtkWidget * gsearch_history_entry_new (const gchar *history_id, gboolean enable_completion)
void gsearch_history_entry_prepend_text (GsearchHistoryEntry *entry, const gchar *text)
void gsearch_history_entry_append_text (GsearchHistoryEntry *entry, const gchar *text)
void gsearch_history_entry_clear (GsearchHistoryEntry *entry)
void gsearch_history_entry_set_history_length (GsearchHistoryEntry *entry, guint max_saved)
guint gsearch_history_entry_get_history_length (GsearchHistoryEntry *gentry)
gchar * gsearch_history_entry_get_history_id (GsearchHistoryEntry *entry)
void gsearch_history_entry_set_enable_completion (GsearchHistoryEntry *entry, gboolean enable)
gboolean gsearch_history_entry_get_enable_completion (GsearchHistoryEntry *entry)
GtkWidget * gsearch_history_entry_get_entry (GsearchHistoryEntry *entry)
void gsearch_history_entry_set_escape_func (GsearchHistoryEntry *entry, GsearchHistoryEntryEscapeFunc escape_func)
Macro Definition Documentation
GSEARCH_HISTORY_ENTRY
#define GSEARCH_HISTORY_ENTRY (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST((obj), GSEARCH_TYPE_HISTORY_ENTRY, GsearchHistoryEntry))
Definition at line 29 of file gsearchtool-entry.h.
Referenced by build_search_command(), gsearch_history_entry_new(), and set_clone_command().
GSEARCH_HISTORY_ENTRY_CLASS
#define GSEARCH_HISTORY_ENTRY_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST((klass),  GSEARCH_TYPE_HISTORY_ENTRY, GsearchHistoryEntryClass))
Definition at line 30 of file gsearchtool-entry.h.
GSEARCH_HISTORY_ENTRY_GET_CLASS
#define GSEARCH_HISTORY_ENTRY_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS((obj),  GSEARCH_TYPE_HISTORY_ENTRY, GsearchHistoryEntryClass))
Definition at line 33 of file gsearchtool-entry.h.
GSEARCH_IS_HISTORY_ENTRY
#define GSEARCH_IS_HISTORY_ENTRY (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE((obj), GSEARCH_TYPE_HISTORY_ENTRY))
Definition at line 31 of file gsearchtool-entry.h.
Referenced by gsearch_history_entry_append_text(), gsearch_history_entry_clear(), gsearch_history_entry_get_enable_completion(), gsearch_history_entry_get_entry(), gsearch_history_entry_get_history_id(), gsearch_history_entry_get_history_length(), gsearch_history_entry_prepend_text(), gsearch_history_entry_set_enable_completion(), gsearch_history_entry_set_escape_func(), and gsearch_history_entry_set_history_length().
GSEARCH_IS_HISTORY_ENTRY_CLASS
#define GSEARCH_IS_HISTORY_ENTRY_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass),  GSEARCH_TYPE_HISTORY_ENTRY))
Definition at line 32 of file gsearchtool-entry.h.
GSEARCH_TYPE_HISTORY_ENTRY
#define GSEARCH_TYPE_HISTORY_ENTRY (gsearch_history_entry_get_type())
Definition at line 28 of file gsearchtool-entry.h.
Referenced by gsearch_history_entry_new().
Typedef Documentation
GsearchHistoryEntry
typedef struct _GsearchHistoryEntry GsearchHistoryEntry
Definition at line 36 of file gsearchtool-entry.h.
GsearchHistoryEntryClass
typedef struct _GsearchHistoryEntryClass GsearchHistoryEntryClass
Definition at line 37 of file gsearchtool-entry.h.
GsearchHistoryEntryEscapeFunc
typedef gchar *(* GsearchHistoryEntryEscapeFunc) (const gchar *str)
Definition at line 66 of file gsearchtool-entry.h.
GsearchHistoryEntryPrivate
typedef struct _GsearchHistoryEntryPrivate GsearchHistoryEntryPrivate
Definition at line 38 of file gsearchtool-entry.h.
Function Documentation
gsearch_history_entry_append_text()
void gsearch_history_entry_append_text (GsearchHistoryEntry * entry, const gchar * text)
Definition at line 369 of file gsearchtool-entry.c.
References FALSE, GSEARCH_IS_HISTORY_ENTRY, and NULL.
gsearch_history_entry_clear()
void gsearch_history_entry_clear (GsearchHistoryEntry * entry)
Definition at line 435 of file gsearchtool-entry.c.
References GSEARCH_IS_HISTORY_ENTRY.
gsearch_history_entry_get_enable_completion()
gboolean gsearch_history_entry_get_enable_completion (GsearchHistoryEntry * entry)
Definition at line 534 of file gsearchtool-entry.c.
References FALSE, GSEARCH_IS_HISTORY_ENTRY, NULL, and _GsearchHistoryEntry::priv.
gsearch_history_entry_get_entry()
GtkWidget * gsearch_history_entry_get_entry (GsearchHistoryEntry * entry)
Definition at line 595 of file gsearchtool-entry.c.
References GSEARCH_IS_HISTORY_ENTRY, and NULL.
Referenced by build_search_command(), gsearch_history_entry_set_enable_completion(), and set_clone_command().
gsearch_history_entry_get_history_id()
gchar * gsearch_history_entry_get_history_id (GsearchHistoryEntry * entry)
Definition at line 484 of file gsearchtool-entry.c.
References GSEARCH_IS_HISTORY_ENTRY, NULL, and _GsearchHistoryEntry::priv.
gsearch_history_entry_get_history_length()
guint gsearch_history_entry_get_history_length (GsearchHistoryEntry * gentry)
Definition at line 476 of file gsearchtool-entry.c.
References GSEARCH_IS_HISTORY_ENTRY, and _GsearchHistoryEntry::priv.
gsearch_history_entry_get_type()
GType gsearch_history_entry_get_type (void)
gsearch_history_entry_new()
GtkWidget * gsearch_history_entry_new (const gchar * history_id, gboolean enable_completion)
Definition at line 542 of file gsearchtool-entry.c.
References GSEARCH_HISTORY_ENTRY, gsearch_history_entry_set_enable_completion(), GSEARCH_TYPE_HISTORY_ENTRY, NULL, and TRUE.
gsearch_history_entry_prepend_text()
void gsearch_history_entry_prepend_text (GsearchHistoryEntry * entry, const gchar * text)
Definition at line 359 of file gsearchtool-entry.c.
References GSEARCH_IS_HISTORY_ENTRY, NULL, and TRUE.
Referenced by build_search_command().
gsearch_history_entry_set_enable_completion()
void gsearch_history_entry_set_enable_completion (GsearchHistoryEntry * entry, gboolean enable)
Definition at line 492 of file gsearchtool-entry.c.
References FALSE, gsearch_history_entry_get_entry(), GSEARCH_IS_HISTORY_ENTRY, MIN_ITEM_LEN, NULL, _GsearchHistoryEntry::priv, and TRUE.
Referenced by gsearch_history_entry_new().
gsearch_history_entry_set_escape_func()
void gsearch_history_entry_set_escape_func (GsearchHistoryEntry * entry, GsearchHistoryEntryEscapeFunc escape_func)
Definition at line 621 of file gsearchtool-entry.c.
References GSEARCH_IS_HISTORY_ENTRY, and NULL.
gsearch_history_entry_set_history_length()
void gsearch_history_entry_set_history_length (GsearchHistoryEntry * entry, guint max_saved)
Definition at line 464 of file gsearchtool-entry.c.
References GSEARCH_IS_HISTORY_ENTRY, and _GsearchHistoryEntry::priv.