MATE Desktop Environment: gsearchtool-support.c File Reference
gsearchtool-support.c File Reference
#include <string.h>
#include <glib/gi18n.h>
#include <glib.h>
#include <regex.h>
#include <stdlib.h>
#include <gdk/gdkx.h>
#include <gio/gio.h>
#include <gio/gdesktopappinfo.h>
#include "gsearchtool.h"
#include "gsearchtool-callbacks.h"
#include "gsearchtool-support.h"
Macros
#define C_STANDARD_STRFTIME_CHARACTERS "aAbBcdHIjmMpSUwWxXyYZ"
#define C_STANDARD_NUMERIC_STRFTIME_CHARACTERS "dHIjmMSUwWyY"
#define SUS_EXTENDED_STRFTIME_MODIFIERS "EO"
#define BINARY_EXEC_MIME_TYPE "application/x-executable"
#define COPY_DUPLICATE_TAG _(untranslated_copy_duplicate_tag)
#define ANOTHER_COPY_DUPLICATE_TAG _(untranslated_another_copy_duplicate_tag)
#define X11TH_COPY_DUPLICATE_TAG _(untranslated_x11th_copy_duplicate_tag)
#define X12TH_COPY_DUPLICATE_TAG _(untranslated_x12th_copy_duplicate_tag)
#define X13TH_COPY_DUPLICATE_TAG _(untranslated_x13th_copy_duplicate_tag)
#define ST_COPY_DUPLICATE_TAG _(untranslated_st_copy_duplicate_tag)
#define ND_COPY_DUPLICATE_TAG _(untranslated_nd_copy_duplicate_tag)
#define RD_COPY_DUPLICATE_TAG _(untranslated_rd_copy_duplicate_tag)
#define TH_COPY_DUPLICATE_TAG _(untranslated_th_copy_duplicate_tag)
#define FIRST_COPY_DUPLICATE_FORMAT _(untranslated_first_copy_duplicate_format)
#define SECOND_COPY_DUPLICATE_FORMAT _(untranslated_second_copy_duplicate_format)
#define X11TH_COPY_DUPLICATE_FORMAT _(untranslated_x11th_copy_duplicate_format)
#define X12TH_COPY_DUPLICATE_FORMAT _(untranslated_x12th_copy_duplicate_format)
#define X13TH_COPY_DUPLICATE_FORMAT _(untranslated_x13th_copy_duplicate_format)
#define ST_COPY_DUPLICATE_FORMAT _(untranslated_st_copy_duplicate_format)
#define ND_COPY_DUPLICATE_FORMAT _(untranslated_nd_copy_duplicate_format)
#define RD_COPY_DUPLICATE_FORMAT _(untranslated_rd_copy_duplicate_format)
#define TH_COPY_DUPLICATE_FORMAT _(untranslated_th_copy_duplicate_format)
Functions
GtkTreeViewColumn * gsearchtool_gtk_tree_view_get_column_with_sort_column_id (GtkTreeView *treeview, gint id)
gboolean is_path_hidden (const gchar *path)
gboolean is_quick_search_excluded_path (const gchar *path)
gboolean is_second_scan_excluded_path (const gchar *path)
gboolean compare_regex (const gchar *regex, const gchar *string)
gboolean limit_string_to_x_lines (GString *string, gint x)
gchar * escape_single_quotes (const gchar *string)
gchar * escape_double_quotes (const gchar *string)
gchar * backslash_backslash_characters (const gchar *string)
gchar * backslash_special_characters (const gchar *string)
gchar * remove_mnemonic_character (const gchar *string)
gchar * get_readable_date (const CajaDateFormat date_format_enum, GDateTime *file_date_time)
gchar * get_file_type_description (const gchar *file, GFileInfo *file_info)
GdkPixbuf * get_file_pixbuf (GSearchWindow *gsearch, GFileInfo *file_info)
gboolean open_file_with_filemanager (GtkWidget *window, const gchar *file)
gboolean open_file_with_application (GtkWidget *window, const gchar *file, GAppInfo *app)
gboolean launch_file (const gchar *file)
gchar * gsearchtool_get_unique_filename (const gchar *path, const gchar *suffix)
GtkWidget * gsearchtool_button_new_with_icon (const gchar *string, const gchar *icon_name)
GSList * gsearchtool_get_columns_order (GtkTreeView *treeview)
void gsearchtool_set_columns_order (GtkTreeView *treeview)
void gsearchtool_get_stored_window_geometry (gint *width, gint *height)
gchar * gsearchtool_get_next_duplicate_name (const gchar *basename)
Macro Definition Documentation
ANOTHER_COPY_DUPLICATE_TAG
#define ANOTHER_COPY_DUPLICATE_TAG _(untranslated_another_copy_duplicate_tag)
Definition at line 1121 of file gsearchtool-support.c.
BINARY_EXEC_MIME_TYPE
#define BINARY_EXEC_MIME_TYPE "application/x-executable"
Definition at line 45 of file gsearchtool-support.c.
Referenced by launch_file().
C_STANDARD_NUMERIC_STRFTIME_CHARACTERS
#define C_STANDARD_NUMERIC_STRFTIME_CHARACTERS "dHIjmMSUwWyY"
Definition at line 43 of file gsearchtool-support.c.
C_STANDARD_STRFTIME_CHARACTERS
#define C_STANDARD_STRFTIME_CHARACTERS "aAbBcdHIjmMpSUwWxXyYZ"
Definition at line 42 of file gsearchtool-support.c.
COPY_DUPLICATE_TAG
#define COPY_DUPLICATE_TAG _(untranslated_copy_duplicate_tag)
Definition at line 1120 of file gsearchtool-support.c.
FIRST_COPY_DUPLICATE_FORMAT
#define FIRST_COPY_DUPLICATE_FORMAT _(untranslated_first_copy_duplicate_format)
Definition at line 1152 of file gsearchtool-support.c.
ND_COPY_DUPLICATE_FORMAT
#define ND_COPY_DUPLICATE_FORMAT _(untranslated_nd_copy_duplicate_format)
Definition at line 1159 of file gsearchtool-support.c.
ND_COPY_DUPLICATE_TAG
#define ND_COPY_DUPLICATE_TAG _(untranslated_nd_copy_duplicate_tag)
Definition at line 1127 of file gsearchtool-support.c.
RD_COPY_DUPLICATE_FORMAT
#define RD_COPY_DUPLICATE_FORMAT _(untranslated_rd_copy_duplicate_format)
Definition at line 1160 of file gsearchtool-support.c.
RD_COPY_DUPLICATE_TAG
#define RD_COPY_DUPLICATE_TAG _(untranslated_rd_copy_duplicate_tag)
Definition at line 1128 of file gsearchtool-support.c.
SECOND_COPY_DUPLICATE_FORMAT
#define SECOND_COPY_DUPLICATE_FORMAT _(untranslated_second_copy_duplicate_format)
Definition at line 1153 of file gsearchtool-support.c.
ST_COPY_DUPLICATE_FORMAT
#define ST_COPY_DUPLICATE_FORMAT _(untranslated_st_copy_duplicate_format)
Definition at line 1158 of file gsearchtool-support.c.
ST_COPY_DUPLICATE_TAG
#define ST_COPY_DUPLICATE_TAG _(untranslated_st_copy_duplicate_tag)
Definition at line 1126 of file gsearchtool-support.c.
SUS_EXTENDED_STRFTIME_MODIFIERS
#define SUS_EXTENDED_STRFTIME_MODIFIERS "EO"
Definition at line 44 of file gsearchtool-support.c.
TH_COPY_DUPLICATE_FORMAT
#define TH_COPY_DUPLICATE_FORMAT _(untranslated_th_copy_duplicate_format)
Definition at line 1161 of file gsearchtool-support.c.
TH_COPY_DUPLICATE_TAG
#define TH_COPY_DUPLICATE_TAG _(untranslated_th_copy_duplicate_tag)
Definition at line 1129 of file gsearchtool-support.c.
X11TH_COPY_DUPLICATE_FORMAT
#define X11TH_COPY_DUPLICATE_FORMAT _(untranslated_x11th_copy_duplicate_format)
Definition at line 1154 of file gsearchtool-support.c.
X11TH_COPY_DUPLICATE_TAG
#define X11TH_COPY_DUPLICATE_TAG _(untranslated_x11th_copy_duplicate_tag)
Definition at line 1122 of file gsearchtool-support.c.
X12TH_COPY_DUPLICATE_FORMAT
#define X12TH_COPY_DUPLICATE_FORMAT _(untranslated_x12th_copy_duplicate_format)
Definition at line 1155 of file gsearchtool-support.c.
X12TH_COPY_DUPLICATE_TAG
#define X12TH_COPY_DUPLICATE_TAG _(untranslated_x12th_copy_duplicate_tag)
Definition at line 1123 of file gsearchtool-support.c.
X13TH_COPY_DUPLICATE_FORMAT
#define X13TH_COPY_DUPLICATE_FORMAT _(untranslated_x13th_copy_duplicate_format)
Definition at line 1156 of file gsearchtool-support.c.
X13TH_COPY_DUPLICATE_TAG
#define X13TH_COPY_DUPLICATE_TAG _(untranslated_x13th_copy_duplicate_tag)
Definition at line 1124 of file gsearchtool-support.c.
Function Documentation
backslash_backslash_characters()
gchar * backslash_backslash_characters (const gchar * string)
Definition at line 335 of file gsearchtool-support.c.
References FALSE, and NULL.
Referenced by build_search_command().
backslash_special_characters()
gchar * backslash_special_characters (const gchar * string)
Definition at line 359 of file gsearchtool-support.c.
References FALSE, and NULL.
Referenced by build_search_command().
compare_regex()
gboolean compare_regex (const gchar * regex, const gchar * string)
Definition at line 238 of file gsearchtool-support.c.
References FALSE, NULL, regex, and TRUE.
escape_double_quotes()
gchar * escape_double_quotes (const gchar * string)
Definition at line 311 of file gsearchtool-support.c.
References FALSE, and NULL.
Referenced by build_search_command().
escape_single_quotes()
gchar * escape_single_quotes (const gchar * string)
Definition at line 287 of file gsearchtool-support.c.
References FALSE, and NULL.
get_file_pixbuf()
GdkPixbuf * get_file_pixbuf (GSearchWindow * gsearch, GFileInfo * file_info)
Definition at line 748 of file gsearchtool-support.c.
References ICON_SIZE, NULL, _GSearchWindow::search_results_filename_hash_table, _GSearchWindow::show_thumbnails, and TRUE.
get_file_type_description()
gchar * get_file_type_description (const gchar * file, GFileInfo * file_info)
Definition at line 438 of file gsearchtool-support.c.
References _, NULL, and TRUE.
get_readable_date()
gchar * get_readable_date (const CajaDateFormat date_format_enum, GDateTime * file_date_time)
Definition at line 408 of file gsearchtool-support.c.
References _, CAJA_DATE_FORMAT_ISO, and CAJA_DATE_FORMAT_LOCALE.
gsearchtool_button_new_with_icon()
GtkWidget * gsearchtool_button_new_with_icon (const gchar * string, const gchar * icon_name)
Definition at line 959 of file gsearchtool-support.c.
References FALSE, and label.
gsearchtool_get_columns_order()
GSList * gsearchtool_get_columns_order (GtkTreeView * treeview)
Definition at line 981 of file gsearchtool-support.c.
References NULL.
Referenced by columns_changed_cb().
gsearchtool_get_next_duplicate_name()
gchar * gsearchtool_get_next_duplicate_name (const gchar * basename)
Definition at line 1405 of file gsearchtool-support.c.
References NULL.
gsearchtool_get_stored_window_geometry()
void gsearchtool_get_stored_window_geometry (gint * width, gint * height)
Definition at line 1062 of file gsearchtool-support.c.
References DEFAULT_WINDOW_HEIGHT, DEFAULT_WINDOW_WIDTH, MAX, MINIMUM_WINDOW_HEIGHT, MINIMUM_WINDOW_WIDTH, and NULL.
gsearchtool_get_unique_filename()
gchar * gsearchtool_get_unique_filename (const gchar * path, const gchar * suffix)
Definition at line 916 of file gsearchtool-support.c.
References NULL, and TRUE.
gsearchtool_gtk_tree_view_get_column_with_sort_column_id()
GtkTreeViewColumn * gsearchtool_gtk_tree_view_get_column_with_sort_column_id (GtkTreeView * treeview, gint id)
Definition at line 1002 of file gsearchtool-support.c.
References NULL.
Referenced by gsearchtool_set_columns_order().
gsearchtool_set_columns_order()
void gsearchtool_set_columns_order (GtkTreeView * treeview)
Definition at line 1022 of file gsearchtool-support.c.
References gsearchtool_gtk_tree_view_get_column_with_sort_column_id(), item, NULL, and NUM_COLUMNS.
is_path_hidden()
gboolean is_path_hidden (const gchar * path)
Definition at line 54 of file gsearchtool-support.c.
References FALSE, NULL, and TRUE.
is_quick_search_excluded_path()
gboolean is_quick_search_excluded_path (const gchar * path)
Definition at line 84 of file gsearchtool-support.c.
References FALSE, NULL, and TRUE.
Referenced by build_search_command().
is_second_scan_excluded_path()
gboolean is_second_scan_excluded_path (const gchar * path)
Definition at line 161 of file gsearchtool-support.c.
References FALSE, NULL, and TRUE.
launch_file()
gboolean launch_file (const gchar * file)
Definition at line 902 of file gsearchtool-support.c.
References BINARY_EXEC_MIME_TYPE, FALSE, and NULL.
Referenced by open_file_cb().
limit_string_to_x_lines()
gboolean limit_string_to_x_lines (GString * string, gint x)
Definition at line 258 of file gsearchtool-support.c.
References FALSE, and TRUE.
open_file_with_application()
gboolean open_file_with_application (GtkWidget * window, const gchar * file, GAppInfo * app)
Definition at line 856 of file gsearchtool-support.c.
References FALSE, NULL, and TRUE.
open_file_with_filemanager()
gboolean open_file_with_filemanager (GtkWidget * window, const gchar * file)
Definition at line 784 of file gsearchtool-support.c.
References FALSE, NULL, and TRUE.
Referenced by open_file_cb(), and open_folder_cb().
remove_mnemonic_character()
gchar * remove_mnemonic_character (const gchar * string)
Definition at line 387 of file gsearchtool-support.c.
References FALSE, NULL, and TRUE.