MATE Desktop Environment: gsm-app-dialog.h File Reference
gsm-app-dialog.h File Reference
#include <glib-object.h>
#include <gtk/gtk.h>
Macros
#define GSM_TYPE_APP_DIALOG (gsm_app_dialog_get_type ())
Functions
G_DECLARE_FINAL_TYPE (...) GtkWidget *gsm_app_dialog_new(const char *name
gboolean gsm_app_dialog_run (GsmAppDialog *dialog, char **name_p, char **command_p, char **comment_p, guint *delay)
const char * gsm_app_dialog_get_name (GsmAppDialog *dialog)
const char * gsm_app_dialog_get_command (GsmAppDialog *dialog)
const char * gsm_app_dialog_get_comment (GsmAppDialog *dialog)
guint gsm_app_dialog_get_delay (GsmAppDialog *dialog)
Variables
const char * command
const char const char * comment
const char const char guint delay
Macro Definition Documentation
GSM_TYPE_APP_DIALOG
#define GSM_TYPE_APP_DIALOG (gsm_app_dialog_get_type ())
Definition at line 30 of file gsm-app-dialog.h.
Referenced by gsm_app_dialog_new().
Function Documentation
G_DECLARE_FINAL_TYPE()
G_DECLARE_FINAL_TYPE (...) const
References name.
gsm_app_dialog_get_command()
const char * gsm_app_dialog_get_command (GsmAppDialog * dialog)
Definition at line 374 of file gsm-app-dialog.c.
References NULL.
Referenced by gsm_app_dialog_run().
gsm_app_dialog_get_comment()
const char * gsm_app_dialog_get_comment (GsmAppDialog * dialog)
Definition at line 381 of file gsm-app-dialog.c.
References NULL.
Referenced by gsm_app_dialog_run().
gsm_app_dialog_get_delay()
guint gsm_app_dialog_get_delay (GsmAppDialog * dialog)
Definition at line 388 of file gsm-app-dialog.c.
Referenced by gsm_app_dialog_run().
gsm_app_dialog_get_name()
const char * gsm_app_dialog_get_name (GsmAppDialog * dialog)
Definition at line 367 of file gsm-app-dialog.c.
References NULL.
Referenced by gsm_app_dialog_run().
gsm_app_dialog_run()
gboolean gsm_app_dialog_run (GsmAppDialog * dialog, char ** name_p, char ** command_p, char ** comment_p, guint * delay)
Definition at line 515 of file gsm-app-dialog.c.
References _, comment, delay, error, FALSE, gsm_app_dialog_get_command(), gsm_app_dialog_get_comment(), gsm_app_dialog_get_delay(), gsm_app_dialog_get_name(), gsm_util_text_is_blank(), name, NULL, and TRUE.
Variable Documentation
command
const char* command
Definition at line 34 of file gsm-app-dialog.h.
comment
const char const char* comment
Definition at line 35 of file gsm-app-dialog.h.
Referenced by gsm_app_dialog_new(), gsm_app_dialog_run(), gsp_app_create(), gsp_app_update(), mate_panel_applet_info_new(), and panel_launcher_create_from_info().
delay
const char const char guint delay
Definition at line 36 of file gsm-app-dialog.h.
Referenced by gsm_app_dialog_new(), gsm_app_dialog_run(), gsp_app_create(), gsp_app_update(), loop_dialog_screenshot(), main(), main(), and meta_screen_tile_preview_update().