MATE Desktop Environment: gsm-inhibitor.h File Reference
gsm-inhibitor.h File Reference
#include <glib-object.h>
#include <sys/types.h>
Macros
#define GSM_TYPE_INHIBITOR (gsm_inhibitor_get_type ())
#define GSM_INHIBITOR_ERROR (gsm_inhibitor_error_quark ())
#define GSM_INHIBITOR_TYPE_ERROR (gsm_inhibitor_error_get_type ())
Enumerations
enum GsmInhibitorError { GSM_INHIBITOR_ERROR_GENERAL = 0 , GSM_INHIBITOR_ERROR_NOT_SET , GSM_INHIBITOR_NUM_ERRORS }
Functions
G_DECLARE_FINAL_TYPE (...) typedef enum
GType gsm_inhibitor_error_get_type (void)
GQuark gsm_inhibitor_error_quark (void)
GsmInhibitor * gsm_inhibitor_new (const char *app_id, guint toplevel_xid, guint flags, const char *reason, const char *bus_name, guint cookie)
GsmInhibitor * gsm_inhibitor_new_for_client (const char *client_id, const char *app_id, guint flags, const char *reason, const char *bus_name, guint cookie)
const char * gsm_inhibitor_peek_id (GsmInhibitor *inhibitor)
const char * gsm_inhibitor_peek_app_id (GsmInhibitor *inhibitor)
const char * gsm_inhibitor_peek_client_id (GsmInhibitor *inhibitor)
const char * gsm_inhibitor_peek_reason (GsmInhibitor *inhibitor)
const char * gsm_inhibitor_peek_bus_name (GsmInhibitor *inhibitor)
guint gsm_inhibitor_peek_cookie (GsmInhibitor *inhibitor)
guint gsm_inhibitor_peek_flags (GsmInhibitor *inhibitor)
guint gsm_inhibitor_peek_toplevel_xid (GsmInhibitor *inhibitor)
gboolean gsm_inhibitor_get_app_id (GsmInhibitor *inhibitor, char **id, GError **error)
gboolean gsm_inhibitor_get_client_id (GsmInhibitor *inhibitor, char **id, GError **error)
gboolean gsm_inhibitor_get_reason (GsmInhibitor *inhibitor, char **reason, GError **error)
gboolean gsm_inhibitor_get_flags (GsmInhibitor *inhibitor, guint *flags, GError **error)
gboolean gsm_inhibitor_get_toplevel_xid (GsmInhibitor *inhibitor, guint *xid, GError **error)
Variables
GsmInhibitorFlag
Macro Definition Documentation
GSM_INHIBITOR_ERROR
#define GSM_INHIBITOR_ERROR (gsm_inhibitor_error_quark ())
Definition at line 31 of file gsm-inhibitor.h.
Referenced by gsm_inhibitor_get_client_id().
GSM_INHIBITOR_TYPE_ERROR
#define GSM_INHIBITOR_TYPE_ERROR (gsm_inhibitor_error_get_type ())
Definition at line 32 of file gsm-inhibitor.h.
GSM_TYPE_INHIBITOR
#define GSM_TYPE_INHIBITOR (gsm_inhibitor_get_type ())
Definition at line 30 of file gsm-inhibitor.h.
Referenced by gsm_inhibitor_new(), and gsm_inhibitor_new_for_client().
Enumeration Type Documentation
GsmInhibitorError
enum GsmInhibitorError
Enumerator
GSM_INHIBITOR_ERROR_GENERAL
GSM_INHIBITOR_ERROR_NOT_SET
GSM_INHIBITOR_NUM_ERRORS
Definition at line 42 of file gsm-inhibitor.h.
Function Documentation
G_DECLARE_FINAL_TYPE()
G_DECLARE_FINAL_TYPE (...)
Definition at line 33 of file gsm-inhibitor.h.
References GSM_INHIBITOR_FLAG_IDLE, GSM_INHIBITOR_FLAG_LOGOUT, GSM_INHIBITOR_FLAG_SUSPEND, and GSM_INHIBITOR_FLAG_SWITCH_USER.
gsm_inhibitor_error_get_type()
GType gsm_inhibitor_error_get_type (void)
Definition at line 79 of file gsm-inhibitor.c.
References ENUM_ENTRY, GSM_INHIBITOR_ERROR_GENERAL, GSM_INHIBITOR_ERROR_NOT_SET, and GSM_INHIBITOR_NUM_ERRORS.
gsm_inhibitor_error_quark()
GQuark gsm_inhibitor_error_quark (void)
Definition at line 66 of file gsm-inhibitor.c.
gsm_inhibitor_get_app_id()
gboolean gsm_inhibitor_get_app_id (GsmInhibitor * inhibitor, char ** id, GError ** error)
Definition at line 266 of file gsm-inhibitor.c.
References error, FALSE, NULL, and TRUE.
gsm_inhibitor_get_client_id()
gboolean gsm_inhibitor_get_client_id (GsmInhibitor * inhibitor, char ** id, GError ** error)
Definition at line 282 of file gsm-inhibitor.c.
References error, FALSE, GSM_INHIBITOR_ERROR, GSM_INHIBITOR_ERROR_NOT_SET, IS_STRING_EMPTY, and TRUE.
gsm_inhibitor_get_flags()
gboolean gsm_inhibitor_get_flags (GsmInhibitor * inhibitor, guint * flags, GError ** error)
Definition at line 321 of file gsm-inhibitor.c.
References error, FALSE, and TRUE.
gsm_inhibitor_get_reason()
gboolean gsm_inhibitor_get_reason (GsmInhibitor * inhibitor, char ** reason, GError ** error)
Definition at line 305 of file gsm-inhibitor.c.
References error, FALSE, NULL, and TRUE.
gsm_inhibitor_get_toplevel_xid()
gboolean gsm_inhibitor_get_toplevel_xid (GsmInhibitor * inhibitor, guint * xid, GError ** error)
Definition at line 333 of file gsm-inhibitor.c.
References error, FALSE, and TRUE.
gsm_inhibitor_new()
GsmInhibitor * gsm_inhibitor_new (const char * app_id, guint toplevel_xid, guint flags, const char * reason, const char * bus_name, guint cookie)
Definition at line 561 of file gsm-inhibitor.c.
References GSM_TYPE_INHIBITOR, and NULL.
Referenced by gsm_manager_inhibit().
gsm_inhibitor_new_for_client()
GsmInhibitor * gsm_inhibitor_new_for_client (const char * client_id, const char * app_id, guint flags, const char * reason, const char * bus_name, guint cookie)
Definition at line 583 of file gsm-inhibitor.c.
References GSM_TYPE_INHIBITOR, and NULL.
gsm_inhibitor_peek_app_id()
const char * gsm_inhibitor_peek_app_id (GsmInhibitor * inhibitor)
Definition at line 353 of file gsm-inhibitor.c.
References NULL.
Referenced by gsm_manager_uninhibit().
gsm_inhibitor_peek_bus_name()
const char * gsm_inhibitor_peek_bus_name (GsmInhibitor * inhibitor)
Definition at line 258 of file gsm-inhibitor.c.
References NULL.
Referenced by gsm_manager_uninhibit().
gsm_inhibitor_peek_client_id()
const char * gsm_inhibitor_peek_client_id (GsmInhibitor * inhibitor)
Definition at line 361 of file gsm-inhibitor.c.
References NULL.
gsm_inhibitor_peek_cookie()
guint gsm_inhibitor_peek_cookie (GsmInhibitor * inhibitor)
Definition at line 393 of file gsm-inhibitor.c.
gsm_inhibitor_peek_flags()
guint gsm_inhibitor_peek_flags (GsmInhibitor * inhibitor)
Definition at line 377 of file gsm-inhibitor.c.
Referenced by gsm_manager_uninhibit().
gsm_inhibitor_peek_id()
const char * gsm_inhibitor_peek_id (GsmInhibitor * inhibitor)
Definition at line 345 of file gsm-inhibitor.c.
References NULL.
Referenced by gsm_manager_inhibit(), and gsm_manager_uninhibit().
gsm_inhibitor_peek_reason()
const char * gsm_inhibitor_peek_reason (GsmInhibitor * inhibitor)
Definition at line 369 of file gsm-inhibitor.c.
References NULL.
Referenced by gsm_manager_uninhibit().
gsm_inhibitor_peek_toplevel_xid()
guint gsm_inhibitor_peek_toplevel_xid (GsmInhibitor * inhibitor)
Definition at line 385 of file gsm-inhibitor.c.
Referenced by gsm_manager_uninhibit().
Variable Documentation
GsmInhibitorFlag
GsmInhibitorFlag
Definition at line 40 of file gsm-inhibitor.h.