MATE Desktop Environment: gsm-manager.c File Reference
gsm-manager.c File Reference
#include "config.h"
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <signal.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <glib/gstdio.h>
#include <glib-object.h>
#include <dbus/dbus-glib.h>
#include <dbus/dbus-glib-lowlevel.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <gdk/gdkx.h>
#include "gsm-manager.h"
#include "gsm-manager-glue.h"
#include "gsm-store.h"
#include "gsm-inhibitor.h"
#include "gsm-presence.h"
#include "gsm-xsmp-client.h"
#include "gsm-dbus-client.h"
#include "gsm-autostart-app.h"
#include "gsm-util.h"
#include "mdm.h"
#include "gsm-logout-dialog.h"
#include "gsm-inhibit-dialog.h"
#include "gsm-consolekit.h"
#include "gsm-session-save.h"
Macros
#define GSM_MANAGER_GET_PRIVATE(o)
#define GSM_MANAGER_DBUS_PATH "/org/gnome/SessionManager"
#define GSM_MANAGER_DBUS_NAME "org.gnome.SessionManager"
#define GSM_MANAGER_PHASE_TIMEOUT 30 /* seconds */
#define GSM_MANAGER_EXIT_PHASE_TIMEOUT 1 /* seconds */
#define MDM_FLEXISERVER_COMMAND "mdmflexiserver"
#define MDM_FLEXISERVER_ARGS "--startnew Standard"
#define GDM_FLEXISERVER_COMMAND "gdmflexiserver"
#define GDM_FLEXISERVER_ARGS "--startnew Standard"
#define LOCKDOWN_SCHEMA "org.mate.lockdown"
#define KEY_LOCK_DISABLE "disable-lock-screen"
#define KEY_LOG_OUT_DISABLE "disable-log-out"
#define KEY_USER_SWITCH_DISABLE "disable-user-switching"
#define SESSION_SCHEMA "org.mate.session"
#define KEY_IDLE_DELAY "idle-delay"
#define KEY_AUTOSAVE "auto-save-session"
#define SCREENSAVER_SCHEMA "org.mate.screensaver"
#define KEY_SLEEP_LOCK "lock-enabled"
#define UNUSED_VARIABLE
#define ENUM_ENTRY(NAME, DESC)
Enumerations
enum GsmManagerLogoutType {
GSM_MANAGER_LOGOUT_NONE , GSM_MANAGER_LOGOUT_LOGOUT , GSM_MANAGER_LOGOUT_REBOOT , GSM_MANAGER_LOGOUT_REBOOT_INTERACT ,
GSM_MANAGER_LOGOUT_REBOOT_MDM , GSM_MANAGER_LOGOUT_SHUTDOWN , GSM_MANAGER_LOGOUT_SHUTDOWN_INTERACT , GSM_MANAGER_LOGOUT_SHUTDOWN_MDM
}
enum { PROP_0 , PROP_CLIENT_STORE , PROP_RENDERER , PROP_FAILSAFE }
enum {
PHASE_CHANGED , CLIENT_ADDED , CLIENT_REMOVED , INHIBITOR_ADDED ,
INHIBITOR_REMOVED , SESSION_RUNNING , SESSION_OVER , LAST_SIGNAL
}
Functions
GQuark gsm_manager_error_quark (void)
GType gsm_manager_error_get_type (void)
void gsm_manager_start (GsmManager *manager)
void _gsm_manager_set_renderer (GsmManager *manager, const char *renderer)
GsmManager * gsm_manager_new (GsmStore *client_store, gboolean failsafe)
gboolean gsm_manager_setenv (GsmManager *manager, const char *variable, const char *value, GError **error)
gboolean gsm_manager_initialization_error (GsmManager *manager, const char *message, gboolean fatal, GError **error)
gboolean gsm_manager_set_phase (GsmManager *manager, GsmManagerPhase phase)
gboolean gsm_manager_request_shutdown (GsmManager *manager, GError **error)
gboolean gsm_manager_request_reboot (GsmManager *manager, GError **error)
gboolean gsm_manager_shutdown (GsmManager *manager, GError **error)
gboolean gsm_manager_can_shutdown (GsmManager *manager, gboolean *shutdown_available, GError **error)
gboolean gsm_manager_logout (GsmManager *manager, guint logout_mode, GError **error)
gboolean gsm_manager_register_client (GsmManager *manager, const char *app_id, const char *startup_id, DBusGMethodInvocation *context)
gboolean gsm_manager_unregister_client (GsmManager *manager, const char *client_id, DBusGMethodInvocation *context)
gboolean gsm_manager_inhibit (GsmManager *manager, const char *app_id, guint toplevel_xid, const char *reason, guint flags, DBusGMethodInvocation *context)
gboolean gsm_manager_uninhibit (GsmManager *manager, guint cookie, DBusGMethodInvocation *context)
gboolean gsm_manager_is_inhibited (GsmManager *manager, guint flags, gboolean *is_inhibited, GError *error)
gboolean gsm_manager_get_clients (GsmManager *manager, GPtrArray **clients, GError **error)
gboolean gsm_manager_get_inhibitors (GsmManager *manager, GPtrArray **inhibitors, GError **error)
gboolean gsm_manager_is_autostart_condition_handled (GsmManager *manager, const char *condition, gboolean *handled, GError **error)
gboolean gsm_manager_add_autostart_app (GsmManager *manager, const char *path, const char *provides)
gboolean gsm_manager_add_autostart_apps_from_dir (GsmManager *manager, const char *path)
gboolean gsm_manager_is_session_running (GsmManager *manager, gboolean *running, GError **error)
Macro Definition Documentation
ENUM_ENTRY
#define ENUM_ENTRY (NAME, DESC)
Value:
{ NAME, "" #NAME "", DESC }
Definition at line 204 of file gsm-manager.c.
Referenced by gsm_manager_error_get_type().
GDM_FLEXISERVER_ARGS
#define GDM_FLEXISERVER_ARGS "--startnew Standard"
Definition at line 84 of file gsm-manager.c.
GDM_FLEXISERVER_COMMAND
#define GDM_FLEXISERVER_COMMAND "gdmflexiserver"
Definition at line 83 of file gsm-manager.c.
GSM_MANAGER_DBUS_NAME
#define GSM_MANAGER_DBUS_NAME "org.gnome.SessionManager"
Definition at line 71 of file gsm-manager.c.
GSM_MANAGER_DBUS_PATH
#define GSM_MANAGER_DBUS_PATH "/org/gnome/SessionManager"
Definition at line 70 of file gsm-manager.c.
GSM_MANAGER_EXIT_PHASE_TIMEOUT
#define GSM_MANAGER_EXIT_PHASE_TIMEOUT 1 /* seconds */
Definition at line 78 of file gsm-manager.c.
GSM_MANAGER_GET_PRIVATE
#define GSM_MANAGER_GET_PRIVATE (o)
Value:
(G_TYPE_INSTANCE_GET_PRIVATE ((o), GSM_TYPE_MANAGER, GsmManagerPrivate))
Definition at line 68 of file gsm-manager.c.
GSM_MANAGER_PHASE_TIMEOUT
#define GSM_MANAGER_PHASE_TIMEOUT 30 /* seconds */
Definition at line 73 of file gsm-manager.c.
KEY_AUTOSAVE
#define KEY_AUTOSAVE "auto-save-session"
Definition at line 93 of file gsm-manager.c.
KEY_IDLE_DELAY
#define KEY_IDLE_DELAY "idle-delay"
Definition at line 92 of file gsm-manager.c.
KEY_LOCK_DISABLE
#define KEY_LOCK_DISABLE "disable-lock-screen"
Definition at line 87 of file gsm-manager.c.
KEY_LOG_OUT_DISABLE
#define KEY_LOG_OUT_DISABLE "disable-log-out"
Definition at line 88 of file gsm-manager.c.
KEY_SLEEP_LOCK
#define KEY_SLEEP_LOCK "lock-enabled"
Definition at line 96 of file gsm-manager.c.
KEY_USER_SWITCH_DISABLE
#define KEY_USER_SWITCH_DISABLE "disable-user-switching"
Definition at line 89 of file gsm-manager.c.
LOCKDOWN_SCHEMA
#define LOCKDOWN_SCHEMA "org.mate.lockdown"
Definition at line 86 of file gsm-manager.c.
MDM_FLEXISERVER_ARGS
#define MDM_FLEXISERVER_ARGS "--startnew Standard"
Definition at line 81 of file gsm-manager.c.
MDM_FLEXISERVER_COMMAND
#define MDM_FLEXISERVER_COMMAND "mdmflexiserver"
Definition at line 80 of file gsm-manager.c.
SCREENSAVER_SCHEMA
#define SCREENSAVER_SCHEMA "org.mate.screensaver"
Definition at line 95 of file gsm-manager.c.
SESSION_SCHEMA
#define SESSION_SCHEMA "org.mate.session"
Definition at line 91 of file gsm-manager.c.
UNUSED_VARIABLE
#define UNUSED_VARIABLE
Definition at line 101 of file gsm-manager.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PHASE_CHANGED
CLIENT_ADDED
CLIENT_REMOVED
INHIBITOR_ADDED
INHIBITOR_REMOVED
SESSION_RUNNING
SESSION_OVER
LAST_SIGNAL
Definition at line 161 of file gsm-manager.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_CLIENT_STORE
PROP_RENDERER
PROP_FAILSAFE
Definition at line 154 of file gsm-manager.c.
GsmManagerLogoutType
enum GsmManagerLogoutType
Enumerator
GSM_MANAGER_LOGOUT_NONE
GSM_MANAGER_LOGOUT_LOGOUT
GSM_MANAGER_LOGOUT_REBOOT
GSM_MANAGER_LOGOUT_REBOOT_INTERACT
GSM_MANAGER_LOGOUT_REBOOT_MDM
GSM_MANAGER_LOGOUT_SHUTDOWN
GSM_MANAGER_LOGOUT_SHUTDOWN_INTERACT
GSM_MANAGER_LOGOUT_SHUTDOWN_MDM
Definition at line 104 of file gsm-manager.c.
Function Documentation
_gsm_manager_set_renderer()
void _gsm_manager_set_renderer (GsmManager * manager, const char * renderer)
Definition at line 1693 of file gsm-manager.c.
Referenced by main().
gsm_manager_add_autostart_app()
gboolean gsm_manager_add_autostart_app (GsmManager * manager, const char * path, const char * provides)
Definition at line 4172 of file gsm-manager.c.
References FALSE, gsm_autostart_app_new(), gsm_store_find(), NULL, and TRUE.
Referenced by gsm_manager_add_autostart_apps_from_dir().
gsm_manager_add_autostart_apps_from_dir()
gboolean gsm_manager_add_autostart_apps_from_dir (GsmManager * manager, const char * path)
Definition at line 4210 of file gsm-manager.c.
References FALSE, gsm_manager_add_autostart_app(), name, NULL, and TRUE.
gsm_manager_can_shutdown()
gboolean gsm_manager_can_shutdown (GsmManager * manager, gboolean * shutdown_available, GError ** error)
Definition at line 3662 of file gsm-manager.c.
References error, FALSE, gsm_consolekit_can_hibernate(), gsm_consolekit_can_restart(), gsm_consolekit_can_stop(), gsm_consolekit_can_suspend(), gsm_get_consolekit(), gsm_get_systemd(), gsm_systemd_can_hibernate(), gsm_systemd_can_restart(), gsm_systemd_can_stop(), gsm_systemd_can_suspend(), LOGIND_RUNNING, and TRUE.
gsm_manager_error_get_type()
GType gsm_manager_error_get_type (void)
Definition at line 207 of file gsm-manager.c.
References ENUM_ENTRY, GSM_MANAGER_ERROR_ALREADY_REGISTERED, GSM_MANAGER_ERROR_GENERAL, GSM_MANAGER_ERROR_INVALID_OPTION, GSM_MANAGER_ERROR_LOCKED_DOWN, GSM_MANAGER_ERROR_NOT_IN_INITIALIZATION, GSM_MANAGER_ERROR_NOT_IN_RUNNING, GSM_MANAGER_ERROR_NOT_REGISTERED, and GSM_MANAGER_NUM_ERRORS.
gsm_manager_error_quark()
GQuark gsm_manager_error_quark (void)
Definition at line 194 of file gsm-manager.c.
gsm_manager_get_clients()
gboolean gsm_manager_get_clients (GsmManager * manager, GPtrArray ** clients, GError ** error)
Definition at line 4055 of file gsm-manager.c.
References error, FALSE, gsm_store_foreach(), NULL, and TRUE.
gsm_manager_get_inhibitors()
gboolean gsm_manager_get_inhibitors (GsmManager * manager, GPtrArray ** inhibitors, GError ** error)
Definition at line 4074 of file gsm-manager.c.
References error, FALSE, gsm_store_foreach(), NULL, and TRUE.
gsm_manager_inhibit()
gboolean gsm_manager_inhibit (GsmManager * manager, const char * app_id, guint toplevel_xid, const char * reason, guint flags, DBusGMethodInvocation * context)
Definition at line 3889 of file gsm-manager.c.
References FALSE, gsm_inhibitor_new(), gsm_inhibitor_peek_id(), GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_GENERAL, GSM_MANAGER_LOGOUT_MODE_FORCE, gsm_store_add(), IS_STRING_EMPTY, and TRUE.
gsm_manager_initialization_error()
gboolean gsm_manager_initialization_error (GsmManager * manager, const char * message, gboolean fatal, GError ** error)
Definition at line 2965 of file gsm-manager.c.
References error, FALSE, GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_NOT_IN_INITIALIZATION, GSM_MANAGER_PHASE_INITIALIZATION, gsm_util_init_error(), message(), and TRUE.
gsm_manager_is_autostart_condition_handled()
gboolean gsm_manager_is_autostart_condition_handled (GsmManager * manager, const char * condition, gboolean * handled, GError ** error)
Definition at line 4110 of file gsm-manager.c.
References condition, error, FALSE, gsm_store_find(), NULL, and TRUE.
gsm_manager_is_inhibited()
gboolean gsm_manager_is_inhibited (GsmManager * manager, guint flags, gboolean * is_inhibited, GError * error)
Definition at line 4015 of file gsm-manager.c.
References error, FALSE, gsm_store_find(), gsm_store_size(), NULL, and TRUE.
gsm_manager_is_session_running()
gboolean gsm_manager_is_session_running (GsmManager * manager, gboolean * running, GError ** error)
Definition at line 4244 of file gsm-manager.c.
References error, FALSE, GSM_MANAGER_PHASE_RUNNING, and TRUE.
gsm_manager_logout()
gboolean gsm_manager_logout (GsmManager * manager, guint logout_mode, GError ** error)
Definition at line 3700 of file gsm-manager.c.
References error, FALSE, GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_INVALID_OPTION, GSM_MANAGER_ERROR_LOCKED_DOWN, GSM_MANAGER_ERROR_NOT_IN_RUNNING, GSM_MANAGER_LOGOUT_MODE_FORCE, GSM_MANAGER_LOGOUT_MODE_NO_CONFIRMATION, GSM_MANAGER_LOGOUT_MODE_NORMAL, GSM_MANAGER_PHASE_RUNNING, and TRUE.
gsm_manager_new()
GsmManager * gsm_manager_new (GsmStore * client_store, gboolean failsafe)
Definition at line 2915 of file gsm-manager.c.
References GSM_TYPE_MANAGER, and NULL.
Referenced by main().
gsm_manager_register_client()
gboolean gsm_manager_register_client (GsmManager * manager, const char * app_id, const char * startup_id, DBusGMethodInvocation * context)
Definition at line 3747 of file gsm-manager.c.
References FALSE, gsm_app_peek_app_id(), gsm_app_registered(), gsm_client_peek_id(), gsm_client_set_app_id(), gsm_client_set_status(), gsm_dbus_client_new(), GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_ALREADY_REGISTERED, GSM_MANAGER_ERROR_GENERAL, GSM_MANAGER_ERROR_NOT_IN_RUNNING, GSM_MANAGER_PHASE_QUERY_END_SESSION, gsm_store_add(), gsm_store_find(), gsm_util_generate_startup_id(), IS_STRING_EMPTY, NULL, and TRUE.
gsm_manager_request_reboot()
gboolean gsm_manager_request_reboot (GsmManager * manager, GError ** error)
Definition at line 3586 of file gsm-manager.c.
References error, FALSE, GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_NOT_IN_RUNNING, GSM_MANAGER_PHASE_RUNNING, and TRUE.
gsm_manager_request_shutdown()
gboolean gsm_manager_request_shutdown (GsmManager * manager, GError ** error)
Definition at line 3563 of file gsm-manager.c.
References error, FALSE, GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_NOT_IN_RUNNING, GSM_MANAGER_PHASE_RUNNING, and TRUE.
gsm_manager_set_phase()
gboolean gsm_manager_set_phase (GsmManager * manager, GsmManagerPhase phase)
Definition at line 3550 of file gsm-manager.c.
References FALSE, and TRUE.
Referenced by gsm_manager_start().
gsm_manager_setenv()
gboolean gsm_manager_setenv (GsmManager * manager, const char * variable, const char * value, GError ** error)
Definition at line 2941 of file gsm-manager.c.
References error, FALSE, GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_NOT_IN_INITIALIZATION, GSM_MANAGER_PHASE_INITIALIZATION, gsm_util_setenv(), and TRUE.
gsm_manager_shutdown()
gboolean gsm_manager_shutdown (GsmManager * manager, GError ** error)
Definition at line 3631 of file gsm-manager.c.
References error, FALSE, GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_LOCKED_DOWN, GSM_MANAGER_ERROR_NOT_IN_RUNNING, GSM_MANAGER_PHASE_RUNNING, and TRUE.
gsm_manager_start()
void gsm_manager_start (GsmManager * manager)
Definition at line 1681 of file gsm-manager.c.
References GSM_MANAGER_PHASE_INITIALIZATION, and gsm_manager_set_phase().
Referenced by main().
gsm_manager_uninhibit()
gboolean gsm_manager_uninhibit (GsmManager * manager, guint cookie, DBusGMethodInvocation * context)
Definition at line 3973 of file gsm-manager.c.
References FALSE, gsm_inhibitor_peek_app_id(), gsm_inhibitor_peek_bus_name(), gsm_inhibitor_peek_flags(), gsm_inhibitor_peek_id(), gsm_inhibitor_peek_reason(), gsm_inhibitor_peek_toplevel_xid(), GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_GENERAL, gsm_store_find(), gsm_store_remove(), NULL, and TRUE.
gsm_manager_unregister_client()
gboolean gsm_manager_unregister_client (GsmManager * manager, const char * client_id, DBusGMethodInvocation * context)
Definition at line 3853 of file gsm-manager.c.
References FALSE, gsm_client_set_status(), GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_NOT_REGISTERED, gsm_store_lookup(), NULL, and TRUE.