MATE Desktop Environment: gsm-systemd.h File Reference
gsm-systemd.h File Reference
#include <unistd.h>
#include <glib.h>
#include <glib-object.h>
Classes
struct _GsmSystemdClass
Macros
#define GSM_TYPE_SYSTEMD (gsm_systemd_get_type ())
#define GSM_SYSTEMD_ERROR (gsm_systemd_error_quark ())
#define LOGIND_RUNNING()
#define GSM_SYSTEMD_SESSION_TYPE_LOGIN_WINDOW "greeter"
Enumerations
enum _GsmSystemdError { GSM_SYSTEMD_ERROR_RESTARTING = 0 , GSM_SYSTEMD_ERROR_STOPPING }
Functions
G_DECLARE_DERIVABLE_TYPE (...) typedef enum _GsmSystemdError GsmSystemdError
GQuark gsm_systemd_error_quark (void)
GsmSystemd * gsm_systemd_new (void) G_GNUC_MALLOC
gboolean gsm_systemd_can_switch_user (GsmSystemd *manager)
gboolean gsm_systemd_get_restart_privileges (GsmSystemd *manager)
gboolean gsm_systemd_get_stop_privileges (GsmSystemd *manager)
gboolean gsm_systemd_can_stop (GsmSystemd *manager)
gboolean gsm_systemd_can_restart (GsmSystemd *manager)
gboolean gsm_systemd_can_hibernate (GsmSystemd *manager)
gboolean gsm_systemd_can_suspend (GsmSystemd *manager)
gboolean gsm_systemd_is_last_session_for_user (GsmSystemd *manager)
void gsm_systemd_attempt_stop (GsmSystemd *manager)
void gsm_systemd_attempt_restart (GsmSystemd *manager)
void gsm_systemd_attempt_hibernate (GsmSystemd *manager)
void gsm_systemd_attempt_suspend (GsmSystemd *manager)
void gsm_systemd_set_session_idle (GsmSystemd *manager, gboolean is_idle)
gchar * gsm_systemd_get_current_session_type (GsmSystemd *manager)
GsmSystemd * gsm_get_systemd (void)
Macro Definition Documentation
GSM_SYSTEMD_ERROR
#define GSM_SYSTEMD_ERROR (gsm_systemd_error_quark ())
Definition at line 34 of file gsm-systemd.h.
GSM_SYSTEMD_SESSION_TYPE_LOGIN_WINDOW
#define GSM_SYSTEMD_SESSION_TYPE_LOGIN_WINDOW "greeter"
Definition at line 58 of file gsm-systemd.h.
GSM_TYPE_SYSTEMD
#define GSM_TYPE_SYSTEMD (gsm_systemd_get_type ())
Definition at line 33 of file gsm-systemd.h.
Referenced by gsm_systemd_new().
LOGIND_RUNNING
#define LOGIND_RUNNING ()
Value:
(access("/run/systemd/seats/", F_OK) >= 0)
Enumeration Type Documentation
_GsmSystemdError
enum _GsmSystemdError
Enumerator
GSM_SYSTEMD_ERROR_RESTARTING
GSM_SYSTEMD_ERROR_STOPPING
Definition at line 53 of file gsm-systemd.h.
Function Documentation
G_DECLARE_DERIVABLE_TYPE()
G_DECLARE_DERIVABLE_TYPE (...)
MateUiApplicationClass: @parent_class: Parent class
Class structure for MateUiApplication
MateUiWindowClass: @parent_class: The parent class
The class structure for #MateUiWindow
MateUiApplicationClass: @parent_class: Parent class
Class structure for MateUiApplication
MateUiWindowClass: @parent_class: The parent class
The class structure for #MateUiWindow
MATE_PANEL_APPLETS_MANAGER_EXTENSION_POINT_NAME:
Extension point for #MatePanelAppletsManager functionality.
MateUiApplicationClass: @parent_class: Parent class
Class structure for MateUiApplication
MateUiWindowClass: @parent_class: The parent class
The class structure for #MateUiWindow
MATE_PANEL_APPLETS_MANAGER_EXTENSION_POINT_NAME:
Extension point for #MatePanelAppletsManager functionality.
Definition at line 28 of file atril/cut-n-paste/smclient/libegg/eggsmclient.h.
References condition, EGG_SM_CLIENT_END_SESSION_DEFAULT, EGG_SM_CLIENT_LOGOUT, EGG_SM_CLIENT_REBOOT, EGG_SM_CLIENT_SHUTDOWN, error, int(), and parent_class.
gsm_get_systemd()
GsmSystemd * gsm_get_systemd (void)
Definition at line 1012 of file gsm-systemd.c.
References gsm_systemd_new(), and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_systemd_attempt_hibernate()
void gsm_systemd_attempt_hibernate (GsmSystemd * manager)
Definition at line 908 of file gsm-systemd.c.
References error, FALSE, NULL, and TRUE.
gsm_systemd_attempt_restart()
void gsm_systemd_attempt_restart (GsmSystemd * manager)
Definition at line 508 of file gsm-systemd.c.
References error, NULL, and TRUE.
gsm_systemd_attempt_stop()
void gsm_systemd_attempt_stop (GsmSystemd * manager)
Definition at line 543 of file gsm-systemd.c.
References error, NULL, and TRUE.
gsm_systemd_attempt_suspend()
void gsm_systemd_attempt_suspend (GsmSystemd * manager)
Definition at line 941 of file gsm-systemd.c.
References error, FALSE, NULL, and TRUE.
gsm_systemd_can_hibernate()
gboolean gsm_systemd_can_hibernate (GsmSystemd * manager)
Definition at line 830 of file gsm-systemd.c.
References error, FALSE, and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_systemd_can_restart()
gboolean gsm_systemd_can_restart (GsmSystemd * manager)
Definition at line 751 of file gsm-systemd.c.
References error, FALSE, and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_systemd_can_stop()
gboolean gsm_systemd_can_stop (GsmSystemd * manager)
Definition at line 790 of file gsm-systemd.c.
References error, FALSE, and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_systemd_can_suspend()
gboolean gsm_systemd_can_suspend (GsmSystemd * manager)
Definition at line 869 of file gsm-systemd.c.
References error, FALSE, and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_systemd_can_switch_user()
gboolean gsm_systemd_can_switch_user (GsmSystemd * manager)
Definition at line 694 of file gsm-systemd.c.
References error, FALSE, and NULL.
gsm_systemd_error_quark()
GQuark gsm_systemd_error_quark (void)
Definition at line 356 of file gsm-systemd.c.
gsm_systemd_get_current_session_type()
gchar * gsm_systemd_get_current_session_type (GsmSystemd * manager)
Definition at line 973 of file gsm-systemd.c.
References NULL.
gsm_systemd_get_restart_privileges()
gboolean gsm_systemd_get_restart_privileges (GsmSystemd * manager)
Definition at line 731 of file gsm-systemd.c.
References NULL, PRIVILEGES_COMPLETED, and TRUE.
gsm_systemd_get_stop_privileges()
gboolean gsm_systemd_get_stop_privileges (GsmSystemd * manager)
Definition at line 741 of file gsm-systemd.c.
References NULL, PRIVILEGES_COMPLETED, and TRUE.
gsm_systemd_is_last_session_for_user()
gboolean gsm_systemd_is_last_session_for_user (GsmSystemd * manager)
Definition at line 424 of file gsm-systemd.c.
References FALSE, NULL, and TRUE.
gsm_systemd_new()
GsmSystemd * gsm_systemd_new (void)
Definition at line 368 of file gsm-systemd.c.
References GSM_TYPE_SYSTEMD, and NULL.
Referenced by gsm_get_systemd().
gsm_systemd_set_session_idle()
void gsm_systemd_set_session_idle (GsmSystemd * manager, gboolean is_idle)
Definition at line 637 of file gsm-systemd.c.
References error, message(), NULL, SD_NAME, and SD_SESSION_INTERFACE.