MATE Desktop Environment: gsm-consolekit.c File Reference
gsm-consolekit.c File Reference
#include "config.h"
#include <errno.h>
#include <string.h>
#include <unistd.h>
#include <glib.h>
#include <glib-object.h>
#include <glib/gi18n.h>
#include <dbus/dbus-glib.h>
#include <dbus/dbus-glib-lowlevel.h>
#include "gsm-marshal.h"
#include "gsm-consolekit.h"
Macros
#define CK_NAME "org.freedesktop.ConsoleKit"
#define CK_PATH "/org/freedesktop/ConsoleKit"
#define CK_INTERFACE "org.freedesktop.ConsoleKit"
#define CK_MANAGER_PATH "/org/freedesktop/ConsoleKit/Manager"
#define CK_MANAGER_INTERFACE "org.freedesktop.ConsoleKit.Manager"
#define CK_SEAT_INTERFACE "org.freedesktop.ConsoleKit.Seat"
#define CK_SESSION_INTERFACE "org.freedesktop.ConsoleKit.Session"
Enumerations
enum { PROP_0 , PROP_IS_CONNECTED }
enum { REQUEST_COMPLETED = 0 , PRIVILEGES_COMPLETED , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (GsmConsolekit, gsm_consolekit, G_TYPE_OBJECT)
GQuark gsm_consolekit_error_quark (void)
GsmConsolekit * gsm_consolekit_new (void)
void gsm_consolekit_attempt_restart (GsmConsolekit *manager)
void gsm_consolekit_attempt_stop (GsmConsolekit *manager)
void gsm_consolekit_attempt_suspend (GsmConsolekit *manager)
void gsm_consolekit_attempt_hibernate (GsmConsolekit *manager)
void gsm_consolekit_set_session_idle (GsmConsolekit *manager, gboolean is_idle)
gboolean gsm_consolekit_can_switch_user (GsmConsolekit *manager)
gboolean gsm_consolekit_get_restart_privileges (GsmConsolekit *manager)
gboolean gsm_consolekit_get_stop_privileges (GsmConsolekit *manager)
gboolean gsm_consolekit_can_restart (GsmConsolekit *manager)
gboolean gsm_consolekit_can_stop (GsmConsolekit *manager)
gboolean gsm_consolekit_can_suspend (GsmConsolekit *manager)
gboolean gsm_consolekit_can_hibernate (GsmConsolekit *manager)
gchar * gsm_consolekit_get_current_session_type (GsmConsolekit *manager)
GsmConsolekit * gsm_get_consolekit (void)
Macro Definition Documentation
CK_INTERFACE
#define CK_INTERFACE "org.freedesktop.ConsoleKit"
Definition at line 40 of file gsm-consolekit.c.
CK_MANAGER_INTERFACE
#define CK_MANAGER_INTERFACE "org.freedesktop.ConsoleKit.Manager"
Definition at line 43 of file gsm-consolekit.c.
CK_MANAGER_PATH
#define CK_MANAGER_PATH "/org/freedesktop/ConsoleKit/Manager"
Definition at line 42 of file gsm-consolekit.c.
CK_NAME
#define CK_NAME "org.freedesktop.ConsoleKit"
Definition at line 38 of file gsm-consolekit.c.
CK_PATH
#define CK_PATH "/org/freedesktop/ConsoleKit"
Definition at line 39 of file gsm-consolekit.c.
CK_SEAT_INTERFACE
#define CK_SEAT_INTERFACE "org.freedesktop.ConsoleKit.Seat"
Definition at line 44 of file gsm-consolekit.c.
CK_SESSION_INTERFACE
#define CK_SESSION_INTERFACE "org.freedesktop.ConsoleKit.Session"
Definition at line 45 of file gsm-consolekit.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_IS_CONNECTED
Definition at line 55 of file gsm-consolekit.c.
anonymous enum
anonymous enum
Enumerator
REQUEST_COMPLETED
PRIVILEGES_COMPLETED
LAST_SIGNAL
Definition at line 60 of file gsm-consolekit.c.
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (GsmConsolekit , gsm_consolekit , G_TYPE_OBJECT)
References PROP_IS_CONNECTED.
gsm_consolekit_attempt_hibernate()
void gsm_consolekit_attempt_hibernate (GsmConsolekit * manager)
Definition at line 524 of file gsm-consolekit.c.
References error, NULL, and TRUE.
gsm_consolekit_attempt_restart()
void gsm_consolekit_attempt_restart (GsmConsolekit * manager)
Definition at line 425 of file gsm-consolekit.c.
References error, and NULL.
gsm_consolekit_attempt_stop()
void gsm_consolekit_attempt_stop (GsmConsolekit * manager)
Definition at line 459 of file gsm-consolekit.c.
References error, and NULL.
gsm_consolekit_attempt_suspend()
void gsm_consolekit_attempt_suspend (GsmConsolekit * manager)
Definition at line 493 of file gsm-consolekit.c.
References error, NULL, and TRUE.
gsm_consolekit_can_hibernate()
gboolean gsm_consolekit_can_hibernate (GsmConsolekit * manager)
Definition at line 958 of file gsm-consolekit.c.
References error, FALSE, and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_consolekit_can_restart()
gboolean gsm_consolekit_can_restart (GsmConsolekit * manager)
Definition at line 847 of file gsm-consolekit.c.
References error, FALSE, and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_consolekit_can_stop()
gboolean gsm_consolekit_can_stop (GsmConsolekit * manager)
Definition at line 882 of file gsm-consolekit.c.
References error, FALSE, and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_consolekit_can_suspend()
gboolean gsm_consolekit_can_suspend (GsmConsolekit * manager)
Definition at line 918 of file gsm-consolekit.c.
References error, FALSE, and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_consolekit_can_switch_user()
gboolean gsm_consolekit_can_switch_user (GsmConsolekit * manager)
Definition at line 796 of file gsm-consolekit.c.
References error, FALSE, and NULL.
gsm_consolekit_error_quark()
GQuark gsm_consolekit_error_quark (void)
Definition at line 357 of file gsm-consolekit.c.
gsm_consolekit_get_current_session_type()
gchar * gsm_consolekit_get_current_session_type (GsmConsolekit * manager)
Definition at line 998 of file gsm-consolekit.c.
References CK_NAME, CK_SESSION_INTERFACE, connection, error, message(), and NULL.
gsm_consolekit_get_restart_privileges()
gboolean gsm_consolekit_get_restart_privileges (GsmConsolekit * manager)
Definition at line 827 of file gsm-consolekit.c.
References NULL, PRIVILEGES_COMPLETED, and TRUE.
gsm_consolekit_get_stop_privileges()
gboolean gsm_consolekit_get_stop_privileges (GsmConsolekit * manager)
Definition at line 837 of file gsm-consolekit.c.
References NULL, PRIVILEGES_COMPLETED, and TRUE.
gsm_consolekit_new()
GsmConsolekit * gsm_consolekit_new (void)
Definition at line 369 of file gsm-consolekit.c.
References GSM_TYPE_CONSOLEKIT, and NULL.
Referenced by gsm_get_consolekit().
gsm_consolekit_set_session_idle()
void gsm_consolekit_set_session_idle (GsmConsolekit * manager, gboolean is_idle)
Definition at line 683 of file gsm-consolekit.c.
References CK_NAME, CK_SESSION_INTERFACE, error, message(), and NULL.
gsm_get_consolekit()
GsmConsolekit * gsm_get_consolekit (void)
Definition at line 1067 of file gsm-consolekit.c.
References gsm_consolekit_new(), and NULL.
Referenced by gsm_manager_can_shutdown().