MATE Desktop Environment: gsm-systemd.c File Reference
gsm-systemd.c File Reference
#include "config.h"
#include <errno.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <glib.h>
#include <glib-object.h>
#include <glib/gi18n.h>
#include <dbus/dbus-glib.h>
#include <dbus/dbus-glib-lowlevel.h>
#include "gsm-marshal.h"
#include "gsm-systemd.h"
Macros
#define SD_NAME "org.freedesktop.login1"
#define SD_PATH "/org/freedesktop/login1"
#define SD_INTERFACE "org.freedesktop.login1.Manager"
#define SD_SEAT_INTERFACE "org.freedesktop.login1.Seat"
#define SD_SESSION_INTERFACE "org.freedesktop.login1.Session"
Enumerations
enum { PROP_0 , PROP_IS_CONNECTED }
enum { REQUEST_COMPLETED = 0 , PRIVILEGES_COMPLETED , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (GsmSystemd, gsm_systemd, G_TYPE_OBJECT)
GQuark gsm_systemd_error_quark (void)
GsmSystemd * gsm_systemd_new (void)
gboolean gsm_systemd_is_last_session_for_user (GsmSystemd *manager)
void gsm_systemd_attempt_restart (GsmSystemd *manager)
void gsm_systemd_attempt_stop (GsmSystemd *manager)
void gsm_systemd_set_session_idle (GsmSystemd *manager, gboolean is_idle)
gboolean gsm_systemd_can_switch_user (GsmSystemd *manager)
gboolean gsm_systemd_get_restart_privileges (GsmSystemd *manager)
gboolean gsm_systemd_get_stop_privileges (GsmSystemd *manager)
gboolean gsm_systemd_can_restart (GsmSystemd *manager)
gboolean gsm_systemd_can_stop (GsmSystemd *manager)
gboolean gsm_systemd_can_hibernate (GsmSystemd *manager)
gboolean gsm_systemd_can_suspend (GsmSystemd *manager)
void gsm_systemd_attempt_hibernate (GsmSystemd *manager)
void gsm_systemd_attempt_suspend (GsmSystemd *manager)
gchar * gsm_systemd_get_current_session_type (GsmSystemd *manager)
GsmSystemd * gsm_get_systemd (void)
Macro Definition Documentation
SD_INTERFACE
#define SD_INTERFACE "org.freedesktop.login1.Manager"
Definition at line 44 of file gsm-systemd.c.
SD_NAME
#define SD_NAME "org.freedesktop.login1"
Definition at line 42 of file gsm-systemd.c.
SD_PATH
#define SD_PATH "/org/freedesktop/login1"
Definition at line 43 of file gsm-systemd.c.
SD_SEAT_INTERFACE
#define SD_SEAT_INTERFACE "org.freedesktop.login1.Seat"
Definition at line 45 of file gsm-systemd.c.
SD_SESSION_INTERFACE
#define SD_SESSION_INTERFACE "org.freedesktop.login1.Session"
Definition at line 46 of file gsm-systemd.c.
Referenced by gsm_systemd_set_session_idle().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
REQUEST_COMPLETED
PRIVILEGES_COMPLETED
LAST_SIGNAL
Definition at line 61 of file gsm-systemd.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_IS_CONNECTED
Definition at line 56 of file gsm-systemd.c.
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (GsmSystemd , gsm_systemd , G_TYPE_OBJECT)
References PROP_IS_CONNECTED.
gsm_get_systemd()
GsmSystemd * gsm_get_systemd (void)
Definition at line 1012 of file gsm-systemd.c.
References gsm_systemd_new(), and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_systemd_attempt_hibernate()
void gsm_systemd_attempt_hibernate (GsmSystemd * manager)
Definition at line 908 of file gsm-systemd.c.
References error, FALSE, NULL, and TRUE.
gsm_systemd_attempt_restart()
void gsm_systemd_attempt_restart (GsmSystemd * manager)
Definition at line 508 of file gsm-systemd.c.
References error, NULL, and TRUE.
gsm_systemd_attempt_stop()
void gsm_systemd_attempt_stop (GsmSystemd * manager)
Definition at line 543 of file gsm-systemd.c.
References error, NULL, and TRUE.
gsm_systemd_attempt_suspend()
void gsm_systemd_attempt_suspend (GsmSystemd * manager)
Definition at line 941 of file gsm-systemd.c.
References error, FALSE, NULL, and TRUE.
gsm_systemd_can_hibernate()
gboolean gsm_systemd_can_hibernate (GsmSystemd * manager)
Definition at line 830 of file gsm-systemd.c.
References error, FALSE, and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_systemd_can_restart()
gboolean gsm_systemd_can_restart (GsmSystemd * manager)
Definition at line 751 of file gsm-systemd.c.
References error, FALSE, and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_systemd_can_stop()
gboolean gsm_systemd_can_stop (GsmSystemd * manager)
Definition at line 790 of file gsm-systemd.c.
References error, FALSE, and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_systemd_can_suspend()
gboolean gsm_systemd_can_suspend (GsmSystemd * manager)
Definition at line 869 of file gsm-systemd.c.
References error, FALSE, and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_systemd_can_switch_user()
gboolean gsm_systemd_can_switch_user (GsmSystemd * manager)
Definition at line 694 of file gsm-systemd.c.
References error, FALSE, and NULL.
gsm_systemd_error_quark()
GQuark gsm_systemd_error_quark (void)
Definition at line 356 of file gsm-systemd.c.
gsm_systemd_get_current_session_type()
gchar * gsm_systemd_get_current_session_type (GsmSystemd * manager)
Definition at line 973 of file gsm-systemd.c.
References NULL.
gsm_systemd_get_restart_privileges()
gboolean gsm_systemd_get_restart_privileges (GsmSystemd * manager)
Definition at line 731 of file gsm-systemd.c.
References NULL, PRIVILEGES_COMPLETED, and TRUE.
gsm_systemd_get_stop_privileges()
gboolean gsm_systemd_get_stop_privileges (GsmSystemd * manager)
Definition at line 741 of file gsm-systemd.c.
References NULL, PRIVILEGES_COMPLETED, and TRUE.
gsm_systemd_is_last_session_for_user()
gboolean gsm_systemd_is_last_session_for_user (GsmSystemd * manager)
Definition at line 424 of file gsm-systemd.c.
References FALSE, NULL, and TRUE.
gsm_systemd_new()
GsmSystemd * gsm_systemd_new (void)
Definition at line 368 of file gsm-systemd.c.
References GSM_TYPE_SYSTEMD, and NULL.
Referenced by gsm_get_systemd().
gsm_systemd_set_session_idle()
void gsm_systemd_set_session_idle (GsmSystemd * manager, gboolean is_idle)
Definition at line 637 of file gsm-systemd.c.
References error, message(), NULL, SD_NAME, and SD_SESSION_INTERFACE.