MATE Desktop Environment: gsm-store.h File Reference
gsm-store.h File Reference
#include <glib-object.h>
Macros
#define GSM_TYPE_STORE (gsm_store_get_type ())
#define GSM_STORE_ERROR gsm_store_error_quark ()
Typedefs
typedef gboolean(* GsmStoreFunc) (const char *id, GObject *object, gpointer user_data)
Enumerations
enum GsmStoreError { GSM_STORE_ERROR_GENERAL }
Functions
G_DECLARE_DERIVABLE_TYPE (...) struct _GsmStoreClass
GQuark gsm_store_error_quark (void)
GsmStore * gsm_store_new (void)
gboolean gsm_store_get_locked (GsmStore *store)
void gsm_store_set_locked (GsmStore *store, gboolean locked)
guint gsm_store_size (GsmStore *store)
gboolean gsm_store_add (GsmStore *store, const char *id, GObject *object)
void gsm_store_clear (GsmStore *store)
gboolean gsm_store_remove (GsmStore *store, const char *id)
void gsm_store_foreach (GsmStore *store, GsmStoreFunc func, gpointer user_data)
guint gsm_store_foreach_remove (GsmStore *store, GsmStoreFunc func, gpointer user_data)
GObject * gsm_store_find (GsmStore *store, GsmStoreFunc predicate, gpointer user_data)
GObject * gsm_store_lookup (GsmStore *store, const char *id)
Macro Definition Documentation
GSM_STORE_ERROR
#define GSM_STORE_ERROR gsm_store_error_quark ()
Definition at line 47 of file gsm-store.h.
GSM_TYPE_STORE
#define GSM_TYPE_STORE (gsm_store_get_type ())
Definition at line 29 of file gsm-store.h.
Referenced by gsm_store_new().
Typedef Documentation
GsmStoreFunc
typedef gboolean(* GsmStoreFunc) (const char *id, GObject *object, gpointer user_data)
Definition at line 49 of file gsm-store.h.
Enumeration Type Documentation
GsmStoreError
enum GsmStoreError
Enumerator
GSM_STORE_ERROR_GENERAL
Definition at line 42 of file gsm-store.h.
Function Documentation
G_DECLARE_DERIVABLE_TYPE()
G_DECLARE_DERIVABLE_TYPE (...)
MateUiApplicationClass: @parent_class: Parent class
Class structure for MateUiApplication
MateUiWindowClass: @parent_class: The parent class
The class structure for #MateUiWindow
MATE_PANEL_APPLETS_MANAGER_EXTENSION_POINT_NAME:
Extension point for #MatePanelAppletsManager functionality.
Definition at line 30 of file gsm-store.h.
References parent_class.
gsm_store_add()
gboolean gsm_store_add (GsmStore * store, const char * id, GObject * object)
Definition at line 238 of file gsm-store.c.
References ADDED, FALSE, NULL, and TRUE.
Referenced by gsm_manager_inhibit(), and gsm_manager_register_client().
gsm_store_clear()
void gsm_store_clear (GsmStore * store)
Definition at line 226 of file gsm-store.c.
References gsm_store_foreach_remove(), and NULL.
gsm_store_error_quark()
GQuark gsm_store_error_quark (void)
Definition at line 60 of file gsm-store.c.
gsm_store_find()
GObject * gsm_store_find (GsmStore * store, GsmStoreFunc predicate, gpointer user_data)
Definition at line 126 of file gsm-store.c.
References NULL, and user_data.
Referenced by gsm_manager_add_autostart_app(), gsm_manager_is_autostart_condition_handled(), gsm_manager_is_inhibited(), gsm_manager_register_client(), and gsm_manager_uninhibit().
gsm_store_foreach()
void gsm_store_foreach (GsmStore * store, GsmStoreFunc func, gpointer user_data)
Definition at line 111 of file gsm-store.c.
References NULL, and user_data.
Referenced by gsm_manager_get_clients(), gsm_manager_get_inhibitors(), and gsm_session_save().
gsm_store_foreach_remove()
guint gsm_store_foreach_remove (GsmStore * store, GsmStoreFunc func, gpointer user_data)
Definition at line 183 of file gsm-store.c.
References data, NULL, REMOVED, and user_data.
Referenced by gsm_store_clear().
gsm_store_get_locked()
gboolean gsm_store_get_locked (GsmStore * store)
Definition at line 278 of file gsm-store.c.
References FALSE.
gsm_store_lookup()
GObject * gsm_store_lookup (GsmStore * store, const char * id)
Definition at line 144 of file gsm-store.c.
References NULL.
Referenced by gsm_manager_unregister_client().
gsm_store_new()
GsmStore * gsm_store_new (void)
Definition at line 422 of file gsm-store.c.
References GSM_TYPE_STORE, and NULL.
Referenced by main().
gsm_store_remove()
gboolean gsm_store_remove (GsmStore * store, const char * id)
Definition at line 79 of file gsm-store.c.
References FALSE, NULL, REMOVED, and TRUE.
Referenced by gsm_manager_uninhibit().
gsm_store_set_locked()
void gsm_store_set_locked (GsmStore * store, gboolean locked)
Definition at line 267 of file gsm-store.c.
gsm_store_size()
guint gsm_store_size (GsmStore * store)
Definition at line 71 of file gsm-store.c.
Referenced by gsm_manager_is_inhibited().