MATE Desktop Environment: gsm-session-save.c File Reference
gsm-session-save.c File Reference
#include <config.h>
#include <glib.h>
#include <glib/gstdio.h>
#include "gsm-util.h"
#include "gsm-autostart-app.h"
#include "gsm-client.h"
#include "gsm-session-save.h"
Functions
void gsm_session_save (GsmStore *client_store, GError **error)
Function Documentation
gsm_session_save()
void gsm_session_save (GsmStore * client_store, GError ** error)
Definition at line 118 of file gsm-session-save.c.
References data, error, gsm_store_foreach(), gsm_util_get_empty_tmp_session_dir(), gsm_util_get_saved_session_dir(), and NULL.