MATE Desktop Environment: gsm-client.h File Reference
gsm-client.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <sys/types.h>
Classes
struct _GsmClientClass
Macros
#define GSM_TYPE_CLIENT (gsm_client_get_type ())
#define GSM_CLIENT_ERROR gsm_client_error_quark ()
#define GSM_CLIENT_TYPE_ERROR (gsm_client_error_get_type ())
Enumerations
enum GsmClientRestartStyle { GSM_CLIENT_RESTART_NEVER = 0 , GSM_CLIENT_RESTART_IF_RUNNING , GSM_CLIENT_RESTART_ANYWAY , GSM_CLIENT_RESTART_IMMEDIATELY }
enum GsmClientEndSessionFlag { GSM_CLIENT_END_SESSION_FLAG_FORCEFUL = 1 << 0 , GSM_CLIENT_END_SESSION_FLAG_SAVE = 1 << 1 , GSM_CLIENT_END_SESSION_FLAG_LAST = 1 << 2 }
enum GsmClientError { GSM_CLIENT_ERROR_GENERAL = 0 , GSM_CLIENT_ERROR_NOT_REGISTERED , GSM_CLIENT_NUM_ERRORS }
Functions
G_DECLARE_DERIVABLE_TYPE (...) typedef enum
GType gsm_client_error_get_type (void)
GQuark gsm_client_error_quark (void)
const char * gsm_client_peek_id (GsmClient *client)
const char * gsm_client_peek_startup_id (GsmClient *client)
const char * gsm_client_peek_app_id (GsmClient *client)
guint gsm_client_peek_restart_style_hint (GsmClient *client)
guint gsm_client_peek_status (GsmClient *client)
char * gsm_client_get_app_name (GsmClient *client)
void gsm_client_set_app_id (GsmClient *client, const char *app_id)
void gsm_client_set_status (GsmClient *client, guint status)
gboolean gsm_client_end_session (GsmClient *client, guint flags, GError **error)
gboolean gsm_client_query_end_session (GsmClient *client, guint flags, GError **error)
gboolean gsm_client_cancel_end_session (GsmClient *client, GError **error)
void gsm_client_disconnected (GsmClient *client)
GKeyFile * gsm_client_save (GsmClient *client, GError **error)
gboolean gsm_client_stop (GsmClient *client, GError **error)
gboolean gsm_client_get_startup_id (GsmClient *client, char **startup_id, GError **error)
gboolean gsm_client_get_app_id (GsmClient *client, char **app_id, GError **error)
gboolean gsm_client_get_restart_style_hint (GsmClient *client, guint *hint, GError **error)
gboolean gsm_client_get_status (GsmClient *client, guint *status, GError **error)
gboolean gsm_client_get_unix_process_id (GsmClient *client, guint *pid, GError **error)
void gsm_client_end_session_response (GsmClient *client, gboolean is_ok, gboolean do_last, gboolean cancel, const char *reason)
Variables
GsmClientStatus
Macro Definition Documentation
GSM_CLIENT_ERROR
#define GSM_CLIENT_ERROR gsm_client_error_quark ()
Definition at line 92 of file gsm-client.h.
GSM_CLIENT_TYPE_ERROR
#define GSM_CLIENT_TYPE_ERROR (gsm_client_error_get_type ())
Definition at line 93 of file gsm-client.h.
GSM_TYPE_CLIENT
#define GSM_TYPE_CLIENT (gsm_client_get_type ())
Definition at line 32 of file gsm-client.h.
Enumeration Type Documentation
GsmClientEndSessionFlag
enum GsmClientEndSessionFlag
Enumerator
GSM_CLIENT_END_SESSION_FLAG_FORCEFUL
GSM_CLIENT_END_SESSION_FLAG_SAVE
GSM_CLIENT_END_SESSION_FLAG_LAST
Definition at line 49 of file gsm-client.h.
GsmClientError
enum GsmClientError
Enumerator
GSM_CLIENT_ERROR_GENERAL
GSM_CLIENT_ERROR_NOT_REGISTERED
GSM_CLIENT_NUM_ERRORS
Definition at line 85 of file gsm-client.h.
GsmClientRestartStyle
enum GsmClientRestartStyle
Enumerator
GSM_CLIENT_RESTART_NEVER
GSM_CLIENT_RESTART_IF_RUNNING
GSM_CLIENT_RESTART_ANYWAY
GSM_CLIENT_RESTART_IMMEDIATELY
Definition at line 42 of file gsm-client.h.
Function Documentation
G_DECLARE_DERIVABLE_TYPE()
G_DECLARE_DERIVABLE_TYPE (...)
MateUiApplicationClass: @parent_class: Parent class
Class structure for MateUiApplication
MateUiWindowClass: @parent_class: The parent class
The class structure for #MateUiWindow
MATE_PANEL_APPLETS_MANAGER_EXTENSION_POINT_NAME:
Extension point for #MatePanelAppletsManager functionality.
Definition at line 33 of file gsm-client.h.
gsm_client_cancel_end_session()
gboolean gsm_client_cancel_end_session (GsmClient * client, GError ** error)
Definition at line 521 of file gsm-client.c.
References error, and FALSE.
gsm_client_disconnected()
void gsm_client_disconnected (GsmClient * client)
Definition at line 559 of file gsm-client.c.
References DISCONNECTED.
gsm_client_end_session()
gboolean gsm_client_end_session (GsmClient * client, guint flags, GError ** error)
Definition at line 540 of file gsm-client.c.
References error, and FALSE.
gsm_client_end_session_response()
void gsm_client_end_session_response (GsmClient * client, gboolean is_ok, gboolean do_last, gboolean cancel, const char * reason)
Definition at line 574 of file gsm-client.c.
References END_SESSION_RESPONSE.
gsm_client_error_get_type()
GType gsm_client_error_get_type (void)
Definition at line 76 of file gsm-client.c.
References ENUM_ENTRY, GSM_CLIENT_ERROR_GENERAL, GSM_CLIENT_ERROR_NOT_REGISTERED, and GSM_CLIENT_NUM_ERRORS.
gsm_client_error_quark()
GQuark gsm_client_error_quark (void)
Definition at line 63 of file gsm-client.c.
gsm_client_get_app_id()
gboolean gsm_client_get_app_id (GsmClient * client, char ** app_id, GError ** error)
Definition at line 452 of file gsm-client.c.
References error, FALSE, and TRUE.
gsm_client_get_app_name()
char * gsm_client_get_app_name (GsmClient * client)
gsm_client_get_app_name: @client: a #GsmClient.
Returns: a copy of the application name of the client, or NULL if no such name is known.
Definition at line 513 of file gsm-client.c.
References NULL.
gsm_client_get_restart_style_hint()
gboolean gsm_client_get_restart_style_hint (GsmClient * client, guint * hint, GError ** error)
Definition at line 467 of file gsm-client.c.
References error, FALSE, and TRUE.
gsm_client_get_startup_id()
gboolean gsm_client_get_startup_id (GsmClient * client, char ** startup_id, GError ** error)
Definition at line 437 of file gsm-client.c.
References error, FALSE, and TRUE.
gsm_client_get_status()
gboolean gsm_client_get_status (GsmClient * client, guint * status, GError ** error)
Definition at line 479 of file gsm-client.c.
References error, FALSE, and TRUE.
gsm_client_get_unix_process_id()
gboolean gsm_client_get_unix_process_id (GsmClient * client, guint * pid, GError ** error)
Definition at line 494 of file gsm-client.c.
References error, FALSE, and TRUE.
gsm_client_peek_app_id()
const char * gsm_client_peek_app_id (GsmClient * client)
gsm_client_peek_app_id: @client: a #GsmClient.
Note that the application ID might not be known; this happens when for XSMP clients that we did not start ourselves, for instance.
Returns: the application ID of the client, or NULL if no such ID is known. The string is owned by @client.
Definition at line 396 of file gsm-client.c.
References NULL.
gsm_client_peek_id()
const char * gsm_client_peek_id (GsmClient * client)
Definition at line 375 of file gsm-client.c.
References NULL.
Referenced by gsm_manager_register_client().
gsm_client_peek_restart_style_hint()
guint gsm_client_peek_restart_style_hint (GsmClient * client)
Definition at line 429 of file gsm-client.c.
References GSM_CLIENT_RESTART_NEVER.
gsm_client_peek_startup_id()
const char * gsm_client_peek_startup_id (GsmClient * client)
Definition at line 407 of file gsm-client.c.
References NULL.
gsm_client_peek_status()
guint gsm_client_peek_status (GsmClient * client)
Definition at line 418 of file gsm-client.c.
gsm_client_query_end_session()
gboolean gsm_client_query_end_session (GsmClient * client, guint flags, GError ** error)
Definition at line 530 of file gsm-client.c.
References error, and FALSE.
gsm_client_save()
GKeyFile * gsm_client_save (GsmClient * client, GError ** error)
Definition at line 565 of file gsm-client.c.
References error, and FALSE.
gsm_client_set_app_id()
void gsm_client_set_app_id (GsmClient * client, const char * app_id)
Definition at line 215 of file gsm-client.c.
References NULL.
Referenced by gsm_manager_register_client().
gsm_client_set_status()
void gsm_client_set_status (GsmClient * client, guint status)
Definition at line 182 of file gsm-client.c.
Referenced by gsm_manager_register_client(), and gsm_manager_unregister_client().
gsm_client_stop()
gboolean gsm_client_stop (GsmClient * client, GError ** error)
Definition at line 550 of file gsm-client.c.
References error, and FALSE.
Variable Documentation
GsmClientStatus
GsmClientStatus
Definition at line 40 of file gsm-client.h.