MATE Desktop Environment: gsm-app.h File Reference
gsm-app.h File Reference
#include <glib-object.h>
#include <sys/types.h>
#include "eggdesktopfile.h"
#include "gsm-manager.h"
#include "gsm-client.h"
Macros
#define GSM_TYPE_APP (gsm_app_get_type ())
#define GSM_APP_ERROR gsm_app_error_quark ()
Enumerations
enum GsmAppError { GSM_APP_ERROR_GENERAL = 0 , GSM_APP_ERROR_START , GSM_APP_ERROR_STOP , GSM_APP_NUM_ERRORS }
Functions
G_DECLARE_DERIVABLE_TYPE (...) struct _GsmAppClass
GQuark gsm_app_error_quark (void)
gboolean gsm_app_peek_autorestart (GsmApp *app)
const char * gsm_app_peek_id (GsmApp *app)
const char * gsm_app_peek_app_id (GsmApp *app)
const char * gsm_app_peek_startup_id (GsmApp *app)
GsmManagerPhase gsm_app_peek_phase (GsmApp *app)
gboolean gsm_app_peek_is_disabled (GsmApp *app)
gboolean gsm_app_peek_is_conditionally_disabled (GsmApp *app)
gboolean gsm_app_start (GsmApp *app, GError **error)
gboolean gsm_app_restart (GsmApp *app, GError **error)
gboolean gsm_app_stop (GsmApp *app, GError **error)
gboolean gsm_app_is_running (GsmApp *app)
void gsm_app_exited (GsmApp *app)
void gsm_app_died (GsmApp *app)
gboolean gsm_app_provides (GsmApp *app, const char *service)
gboolean gsm_app_has_autostart_condition (GsmApp *app, const char *condition)
void gsm_app_registered (GsmApp *app)
int gsm_app_peek_autostart_delay (GsmApp *app)
gboolean gsm_app_get_app_id (GsmApp *app, char **id, GError **error)
gboolean gsm_app_get_startup_id (GsmApp *app, char **id, GError **error)
gboolean gsm_app_get_phase (GsmApp *app, guint *phase, GError **error)
Macro Definition Documentation
GSM_APP_ERROR
#define GSM_APP_ERROR gsm_app_error_quark ()
Definition at line 76 of file gsm-app.h.
GSM_TYPE_APP
#define GSM_TYPE_APP (gsm_app_get_type ())
Definition at line 36 of file gsm-app.h.
Enumeration Type Documentation
GsmAppError
enum GsmAppError
Enumerator
GSM_APP_ERROR_GENERAL
GSM_APP_ERROR_START
GSM_APP_ERROR_STOP
GSM_APP_NUM_ERRORS
Definition at line 68 of file gsm-app.h.
Function Documentation
G_DECLARE_DERIVABLE_TYPE()
G_DECLARE_DERIVABLE_TYPE (...)
MateUiApplicationClass: @parent_class: Parent class
Class structure for MateUiApplication
MateUiWindowClass: @parent_class: The parent class
The class structure for #MateUiWindow
MATE_PANEL_APPLETS_MANAGER_EXTENSION_POINT_NAME:
Extension point for #MatePanelAppletsManager functionality.
Definition at line 37 of file gsm-app.h.
References error, int(), and parent_class.
gsm_app_died()
void gsm_app_died (GsmApp * app)
Definition at line 498 of file gsm-app.c.
References DIED.
gsm_app_error_quark()
GQuark gsm_app_error_quark (void)
Definition at line 63 of file gsm-app.c.
gsm_app_exited()
void gsm_app_exited (GsmApp * app)
Definition at line 490 of file gsm-app.c.
References EXITED.
gsm_app_get_app_id()
gboolean gsm_app_get_app_id (GsmApp * app, char ** id, GError ** error)
Definition at line 506 of file gsm-app.c.
References error, FALSE, and TRUE.
gsm_app_get_phase()
gboolean gsm_app_get_phase (GsmApp * app, guint * phase, GError ** error)
Definition at line 529 of file gsm-app.c.
References error, FALSE, and TRUE.
gsm_app_get_startup_id()
gboolean gsm_app_get_startup_id (GsmApp * app, char ** id, GError ** error)
Definition at line 516 of file gsm-app.c.
References error, FALSE, and TRUE.
gsm_app_has_autostart_condition()
gboolean gsm_app_has_autostart_condition (GsmApp * app, const char * condition)
Definition at line 426 of file gsm-app.c.
References condition, and FALSE.
gsm_app_is_running()
gboolean gsm_app_is_running (GsmApp * app)
Definition at line 391 of file gsm-app.c.
References FALSE.
gsm_app_peek_app_id()
const char * gsm_app_peek_app_id (GsmApp * app)
Definition at line 333 of file gsm-app.c.
Referenced by gsm_manager_register_client().
gsm_app_peek_autorestart()
gboolean gsm_app_peek_autorestart (GsmApp * app)
Definition at line 403 of file gsm-app.c.
References FALSE.
gsm_app_peek_autostart_delay()
int gsm_app_peek_autostart_delay (GsmApp * app)
Definition at line 478 of file gsm-app.c.
References FALSE.
gsm_app_peek_id()
const char * gsm_app_peek_id (GsmApp * app)
Definition at line 324 of file gsm-app.c.
gsm_app_peek_is_conditionally_disabled()
gboolean gsm_app_peek_is_conditionally_disabled (GsmApp * app)
Definition at line 379 of file gsm-app.c.
References FALSE.
gsm_app_peek_is_disabled()
gboolean gsm_app_peek_is_disabled (GsmApp * app)
Definition at line 367 of file gsm-app.c.
References FALSE.
gsm_app_peek_phase()
GsmManagerPhase gsm_app_peek_phase (GsmApp * app)
gsm_app_peek_phase: @app: a GsmApp
Returns @app's startup phase.
Return value: @app's startup phase
Definition at line 356 of file gsm-app.c.
References GSM_MANAGER_PHASE_APPLICATION.
gsm_app_peek_startup_id()
const char * gsm_app_peek_startup_id (GsmApp * app)
Definition at line 339 of file gsm-app.c.
gsm_app_provides()
gboolean gsm_app_provides (GsmApp * app, const char * service)
Definition at line 415 of file gsm-app.c.
References FALSE.
gsm_app_registered()
void gsm_app_registered (GsmApp * app)
Definition at line 470 of file gsm-app.c.
References REGISTERED.
Referenced by gsm_manager_register_client().
gsm_app_restart()
gboolean gsm_app_restart (GsmApp * app, GError ** error)
Definition at line 450 of file gsm-app.c.
References error.
gsm_app_start()
gboolean gsm_app_start (GsmApp * app, GError ** error)
Definition at line 438 of file gsm-app.c.
References error.
gsm_app_stop()
gboolean gsm_app_stop (GsmApp * app, GError ** error)
Definition at line 463 of file gsm-app.c.
References error.