MATE Desktop Environment: gsm-consolekit.h File Reference
gsm-consolekit.h File Reference
#include <glib.h>
#include <glib-object.h>
Classes
struct _GsmConsolekitClass
Macros
#define GSM_TYPE_CONSOLEKIT (gsm_consolekit_get_type ())
#define GSM_CONSOLEKIT_ERROR (gsm_consolekit_error_quark ())
#define GSM_CONSOLEKIT_SESSION_TYPE_LOGIN_WINDOW "LoginWindow"
Enumerations
enum _GsmConsolekitError { GSM_CONSOLEKIT_ERROR_RESTARTING = 0 , GSM_CONSOLEKIT_ERROR_STOPPING }
Functions
G_DECLARE_DERIVABLE_TYPE (...) typedef enum _GsmConsolekitError GsmConsolekitError
GQuark gsm_consolekit_error_quark (void)
GsmConsolekit * gsm_consolekit_new (void) G_GNUC_MALLOC
gboolean gsm_consolekit_can_switch_user (GsmConsolekit *manager)
gboolean gsm_consolekit_get_restart_privileges (GsmConsolekit *manager)
gboolean gsm_consolekit_get_stop_privileges (GsmConsolekit *manager)
gboolean gsm_consolekit_can_stop (GsmConsolekit *manager)
gboolean gsm_consolekit_can_restart (GsmConsolekit *manager)
gboolean gsm_consolekit_can_suspend (GsmConsolekit *manager)
gboolean gsm_consolekit_can_hibernate (GsmConsolekit *manager)
void gsm_consolekit_attempt_stop (GsmConsolekit *manager)
void gsm_consolekit_attempt_restart (GsmConsolekit *manager)
void gsm_consolekit_attempt_suspend (GsmConsolekit *manager)
void gsm_consolekit_attempt_hibernate (GsmConsolekit *manager)
void gsm_consolekit_set_session_idle (GsmConsolekit *manager, gboolean is_idle)
gchar * gsm_consolekit_get_current_session_type (GsmConsolekit *manager)
GsmConsolekit * gsm_get_consolekit (void)
Macro Definition Documentation
GSM_CONSOLEKIT_ERROR
#define GSM_CONSOLEKIT_ERROR (gsm_consolekit_error_quark ())
Definition at line 34 of file gsm-consolekit.h.
GSM_CONSOLEKIT_SESSION_TYPE_LOGIN_WINDOW
#define GSM_CONSOLEKIT_SESSION_TYPE_LOGIN_WINDOW "LoginWindow"
Definition at line 58 of file gsm-consolekit.h.
GSM_TYPE_CONSOLEKIT
#define GSM_TYPE_CONSOLEKIT (gsm_consolekit_get_type ())
Definition at line 33 of file gsm-consolekit.h.
Referenced by gsm_consolekit_new().
Enumeration Type Documentation
_GsmConsolekitError
enum _GsmConsolekitError
Enumerator
GSM_CONSOLEKIT_ERROR_RESTARTING
GSM_CONSOLEKIT_ERROR_STOPPING
Definition at line 53 of file gsm-consolekit.h.
Function Documentation
G_DECLARE_DERIVABLE_TYPE()
G_DECLARE_DERIVABLE_TYPE (...)
MateUiApplicationClass: @parent_class: Parent class
Class structure for MateUiApplication
MateUiWindowClass: @parent_class: The parent class
The class structure for #MateUiWindow
MATE_PANEL_APPLETS_MANAGER_EXTENSION_POINT_NAME:
Extension point for #MatePanelAppletsManager functionality.
Definition at line 28 of file atril/cut-n-paste/smclient/libegg/eggsmclient.h.
gsm_consolekit_attempt_hibernate()
void gsm_consolekit_attempt_hibernate (GsmConsolekit * manager)
Definition at line 524 of file gsm-consolekit.c.
References error, NULL, and TRUE.
gsm_consolekit_attempt_restart()
void gsm_consolekit_attempt_restart (GsmConsolekit * manager)
Definition at line 425 of file gsm-consolekit.c.
References error, and NULL.
gsm_consolekit_attempt_stop()
void gsm_consolekit_attempt_stop (GsmConsolekit * manager)
Definition at line 459 of file gsm-consolekit.c.
References error, and NULL.
gsm_consolekit_attempt_suspend()
void gsm_consolekit_attempt_suspend (GsmConsolekit * manager)
Definition at line 493 of file gsm-consolekit.c.
References error, NULL, and TRUE.
gsm_consolekit_can_hibernate()
gboolean gsm_consolekit_can_hibernate (GsmConsolekit * manager)
Definition at line 958 of file gsm-consolekit.c.
References error, FALSE, and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_consolekit_can_restart()
gboolean gsm_consolekit_can_restart (GsmConsolekit * manager)
Definition at line 847 of file gsm-consolekit.c.
References error, FALSE, and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_consolekit_can_stop()
gboolean gsm_consolekit_can_stop (GsmConsolekit * manager)
Definition at line 882 of file gsm-consolekit.c.
References error, FALSE, and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_consolekit_can_suspend()
gboolean gsm_consolekit_can_suspend (GsmConsolekit * manager)
Definition at line 918 of file gsm-consolekit.c.
References error, FALSE, and NULL.
Referenced by gsm_manager_can_shutdown().
gsm_consolekit_can_switch_user()
gboolean gsm_consolekit_can_switch_user (GsmConsolekit * manager)
Definition at line 796 of file gsm-consolekit.c.
References error, FALSE, and NULL.
gsm_consolekit_error_quark()
GQuark gsm_consolekit_error_quark (void)
Definition at line 357 of file gsm-consolekit.c.
gsm_consolekit_get_current_session_type()
gchar * gsm_consolekit_get_current_session_type (GsmConsolekit * manager)
Definition at line 998 of file gsm-consolekit.c.
References CK_NAME, CK_SESSION_INTERFACE, connection, error, message(), and NULL.
gsm_consolekit_get_restart_privileges()
gboolean gsm_consolekit_get_restart_privileges (GsmConsolekit * manager)
Definition at line 827 of file gsm-consolekit.c.
References NULL, PRIVILEGES_COMPLETED, and TRUE.
gsm_consolekit_get_stop_privileges()
gboolean gsm_consolekit_get_stop_privileges (GsmConsolekit * manager)
Definition at line 837 of file gsm-consolekit.c.
References NULL, PRIVILEGES_COMPLETED, and TRUE.
gsm_consolekit_new()
GsmConsolekit * gsm_consolekit_new (void)
Definition at line 369 of file gsm-consolekit.c.
References GSM_TYPE_CONSOLEKIT, and NULL.
Referenced by gsm_get_consolekit().
gsm_consolekit_set_session_idle()
void gsm_consolekit_set_session_idle (GsmConsolekit * manager, gboolean is_idle)
Definition at line 683 of file gsm-consolekit.c.
References CK_NAME, CK_SESSION_INTERFACE, error, message(), and NULL.
gsm_get_consolekit()
GsmConsolekit * gsm_get_consolekit (void)
Definition at line 1067 of file gsm-consolekit.c.
References gsm_consolekit_new(), and NULL.
Referenced by gsm_manager_can_shutdown().