MATE Desktop Environment: gsm-manager.h File Reference
gsm-manager.h File Reference
#include <glib-object.h>
#include <dbus/dbus-glib.h>
#include "gsm-store.h"
Macros
#define GSM_TYPE_MANAGER (gsm_manager_get_type ())
#define GSM_MANAGER_ERROR gsm_manager_error_quark ()
#define GSM_MANAGER_TYPE_ERROR (gsm_manager_error_get_type ())
Enumerations
enum GsmManagerPhase {
GSM_MANAGER_PHASE_STARTUP = 0 , GSM_MANAGER_PHASE_INITIALIZATION , GSM_MANAGER_PHASE_WINDOW_MANAGER , GSM_MANAGER_PHASE_PANEL ,
GSM_MANAGER_PHASE_DESKTOP , GSM_MANAGER_PHASE_APPLICATION , GSM_MANAGER_PHASE_RUNNING , GSM_MANAGER_PHASE_QUERY_END_SESSION ,
GSM_MANAGER_PHASE_END_SESSION , GSM_MANAGER_PHASE_EXIT
}
enum GsmManagerError {
GSM_MANAGER_ERROR_GENERAL = 0 , GSM_MANAGER_ERROR_NOT_IN_INITIALIZATION , GSM_MANAGER_ERROR_NOT_IN_RUNNING , GSM_MANAGER_ERROR_ALREADY_REGISTERED ,
GSM_MANAGER_ERROR_NOT_REGISTERED , GSM_MANAGER_ERROR_INVALID_OPTION , GSM_MANAGER_ERROR_LOCKED_DOWN , GSM_MANAGER_NUM_ERRORS
}
enum GsmManagerLogoutMode { GSM_MANAGER_LOGOUT_MODE_NORMAL = 0 , GSM_MANAGER_LOGOUT_MODE_NO_CONFIRMATION , GSM_MANAGER_LOGOUT_MODE_FORCE }
Functions
G_DECLARE_DERIVABLE_TYPE (...) struct _GsmManagerClass
GType gsm_manager_error_get_type (void)
GQuark gsm_manager_error_quark (void)
GsmManager * gsm_manager_new (GsmStore *client_store, gboolean failsafe)
gboolean gsm_manager_add_autostart_app (GsmManager *manager, const char *path, const char *provides)
gboolean gsm_manager_add_autostart_apps_from_dir (GsmManager *manager, const char *path)
gboolean gsm_manager_add_legacy_session_apps (GsmManager *manager, const char *path)
void gsm_manager_start (GsmManager *manager)
gboolean gsm_manager_register_client (GsmManager *manager, const char *app_id, const char *client_startup_id, DBusGMethodInvocation *context)
gboolean gsm_manager_unregister_client (GsmManager *manager, const char *session_client_id, DBusGMethodInvocation *context)
gboolean gsm_manager_inhibit (GsmManager *manager, const char *app_id, guint toplevel_xid, const char *reason, guint flags, DBusGMethodInvocation *context)
gboolean gsm_manager_uninhibit (GsmManager *manager, guint inhibit_cookie, DBusGMethodInvocation *context)
gboolean gsm_manager_is_inhibited (GsmManager *manager, guint flags, gboolean *is_inhibited, GError *error)
gboolean gsm_manager_request_shutdown (GsmManager *manager, GError **error)
gboolean gsm_manager_request_reboot (GsmManager *manager, GError **error)
gboolean gsm_manager_shutdown (GsmManager *manager, GError **error)
gboolean gsm_manager_can_shutdown (GsmManager *manager, gboolean *shutdown_available, GError **error)
gboolean gsm_manager_logout (GsmManager *manager, guint logout_mode, GError **error)
gboolean gsm_manager_setenv (GsmManager *manager, const char *variable, const char *value, GError **error)
gboolean gsm_manager_initialization_error (GsmManager *manager, const char *message, gboolean fatal, GError **error)
gboolean gsm_manager_get_clients (GsmManager *manager, GPtrArray **clients, GError **error)
gboolean gsm_manager_get_inhibitors (GsmManager *manager, GPtrArray **inhibitors, GError **error)
gboolean gsm_manager_is_autostart_condition_handled (GsmManager *manager, const char *condition, gboolean *handled, GError **error)
gboolean gsm_manager_set_phase (GsmManager *manager, GsmManagerPhase phase)
gboolean gsm_manager_is_session_running (GsmManager *manager, gboolean *running, GError **error)
void _gsm_manager_set_renderer (GsmManager *manager, const char *renderer)
Macro Definition Documentation
GSM_MANAGER_ERROR
#define GSM_MANAGER_ERROR gsm_manager_error_quark ()
Definition at line 89 of file gsm-manager.h.
Referenced by gsm_manager_inhibit(), gsm_manager_initialization_error(), gsm_manager_logout(), gsm_manager_register_client(), gsm_manager_request_reboot(), gsm_manager_request_shutdown(), gsm_manager_setenv(), gsm_manager_shutdown(), gsm_manager_uninhibit(), and gsm_manager_unregister_client().
GSM_MANAGER_TYPE_ERROR
#define GSM_MANAGER_TYPE_ERROR (gsm_manager_error_get_type ())
Definition at line 98 of file gsm-manager.h.
GSM_TYPE_MANAGER
#define GSM_TYPE_MANAGER (gsm_manager_get_type ())
Definition at line 32 of file gsm-manager.h.
Referenced by gsm_manager_new().
Enumeration Type Documentation
GsmManagerError
enum GsmManagerError
Enumerator
GSM_MANAGER_ERROR_GENERAL
GSM_MANAGER_ERROR_NOT_IN_INITIALIZATION
GSM_MANAGER_ERROR_NOT_IN_RUNNING
GSM_MANAGER_ERROR_ALREADY_REGISTERED
GSM_MANAGER_ERROR_NOT_REGISTERED
GSM_MANAGER_ERROR_INVALID_OPTION
GSM_MANAGER_ERROR_LOCKED_DOWN
GSM_MANAGER_NUM_ERRORS
Definition at line 77 of file gsm-manager.h.
GsmManagerLogoutMode
enum GsmManagerLogoutMode
Enumerator
GSM_MANAGER_LOGOUT_MODE_NORMAL
GSM_MANAGER_LOGOUT_MODE_NO_CONFIRMATION
GSM_MANAGER_LOGOUT_MODE_FORCE
Definition at line 91 of file gsm-manager.h.
GsmManagerPhase
enum GsmManagerPhase
Enumerator
GSM_MANAGER_PHASE_STARTUP
GSM_MANAGER_PHASE_INITIALIZATION
GSM_MANAGER_PHASE_WINDOW_MANAGER
GSM_MANAGER_PHASE_PANEL
GSM_MANAGER_PHASE_DESKTOP
GSM_MANAGER_PHASE_APPLICATION
GSM_MANAGER_PHASE_RUNNING
GSM_MANAGER_PHASE_QUERY_END_SESSION
GSM_MANAGER_PHASE_END_SESSION
GSM_MANAGER_PHASE_EXIT
Definition at line 56 of file gsm-manager.h.
Function Documentation
_gsm_manager_set_renderer()
void _gsm_manager_set_renderer (GsmManager * manager, const char * renderer)
Definition at line 1693 of file gsm-manager.c.
Referenced by main().
G_DECLARE_DERIVABLE_TYPE()
G_DECLARE_DERIVABLE_TYPE (...)
MateUiApplicationClass: @parent_class: Parent class
Class structure for MateUiApplication
MateUiWindowClass: @parent_class: The parent class
The class structure for #MateUiWindow
MATE_PANEL_APPLETS_MANAGER_EXTENSION_POINT_NAME:
Extension point for #MatePanelAppletsManager functionality.
Definition at line 33 of file gsm-manager.h.
References parent_class.
gsm_manager_add_autostart_app()
gboolean gsm_manager_add_autostart_app (GsmManager * manager, const char * path, const char * provides)
Definition at line 4172 of file gsm-manager.c.
References FALSE, gsm_autostart_app_new(), gsm_store_find(), NULL, and TRUE.
Referenced by gsm_manager_add_autostart_apps_from_dir().
gsm_manager_add_autostart_apps_from_dir()
gboolean gsm_manager_add_autostart_apps_from_dir (GsmManager * manager, const char * path)
Definition at line 4210 of file gsm-manager.c.
References FALSE, gsm_manager_add_autostart_app(), name, NULL, and TRUE.
gsm_manager_add_legacy_session_apps()
gboolean gsm_manager_add_legacy_session_apps (GsmManager * manager, const char * path)
References condition, error, and message().
gsm_manager_can_shutdown()
gboolean gsm_manager_can_shutdown (GsmManager * manager, gboolean * shutdown_available, GError ** error)
Definition at line 3662 of file gsm-manager.c.
References error, FALSE, gsm_consolekit_can_hibernate(), gsm_consolekit_can_restart(), gsm_consolekit_can_stop(), gsm_consolekit_can_suspend(), gsm_get_consolekit(), gsm_get_systemd(), gsm_systemd_can_hibernate(), gsm_systemd_can_restart(), gsm_systemd_can_stop(), gsm_systemd_can_suspend(), LOGIND_RUNNING, and TRUE.
gsm_manager_error_get_type()
GType gsm_manager_error_get_type (void)
Definition at line 207 of file gsm-manager.c.
References ENUM_ENTRY, GSM_MANAGER_ERROR_ALREADY_REGISTERED, GSM_MANAGER_ERROR_GENERAL, GSM_MANAGER_ERROR_INVALID_OPTION, GSM_MANAGER_ERROR_LOCKED_DOWN, GSM_MANAGER_ERROR_NOT_IN_INITIALIZATION, GSM_MANAGER_ERROR_NOT_IN_RUNNING, GSM_MANAGER_ERROR_NOT_REGISTERED, and GSM_MANAGER_NUM_ERRORS.
gsm_manager_error_quark()
GQuark gsm_manager_error_quark (void)
Definition at line 194 of file gsm-manager.c.
gsm_manager_get_clients()
gboolean gsm_manager_get_clients (GsmManager * manager, GPtrArray ** clients, GError ** error)
Definition at line 4055 of file gsm-manager.c.
References error, FALSE, gsm_store_foreach(), NULL, and TRUE.
gsm_manager_get_inhibitors()
gboolean gsm_manager_get_inhibitors (GsmManager * manager, GPtrArray ** inhibitors, GError ** error)
Definition at line 4074 of file gsm-manager.c.
References error, FALSE, gsm_store_foreach(), NULL, and TRUE.
gsm_manager_inhibit()
gboolean gsm_manager_inhibit (GsmManager * manager, const char * app_id, guint toplevel_xid, const char * reason, guint flags, DBusGMethodInvocation * context)
Definition at line 3889 of file gsm-manager.c.
References FALSE, gsm_inhibitor_new(), gsm_inhibitor_peek_id(), GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_GENERAL, GSM_MANAGER_LOGOUT_MODE_FORCE, gsm_store_add(), IS_STRING_EMPTY, and TRUE.
gsm_manager_initialization_error()
gboolean gsm_manager_initialization_error (GsmManager * manager, const char * message, gboolean fatal, GError ** error)
Definition at line 2965 of file gsm-manager.c.
References error, FALSE, GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_NOT_IN_INITIALIZATION, GSM_MANAGER_PHASE_INITIALIZATION, gsm_util_init_error(), message(), and TRUE.
gsm_manager_is_autostart_condition_handled()
gboolean gsm_manager_is_autostart_condition_handled (GsmManager * manager, const char * condition, gboolean * handled, GError ** error)
Definition at line 4110 of file gsm-manager.c.
References condition, error, FALSE, gsm_store_find(), NULL, and TRUE.
gsm_manager_is_inhibited()
gboolean gsm_manager_is_inhibited (GsmManager * manager, guint flags, gboolean * is_inhibited, GError * error)
Definition at line 4015 of file gsm-manager.c.
References error, FALSE, gsm_store_find(), gsm_store_size(), NULL, and TRUE.
gsm_manager_is_session_running()
gboolean gsm_manager_is_session_running (GsmManager * manager, gboolean * running, GError ** error)
Definition at line 4244 of file gsm-manager.c.
References error, FALSE, GSM_MANAGER_PHASE_RUNNING, and TRUE.
gsm_manager_logout()
gboolean gsm_manager_logout (GsmManager * manager, guint logout_mode, GError ** error)
Definition at line 3700 of file gsm-manager.c.
References error, FALSE, GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_INVALID_OPTION, GSM_MANAGER_ERROR_LOCKED_DOWN, GSM_MANAGER_ERROR_NOT_IN_RUNNING, GSM_MANAGER_LOGOUT_MODE_FORCE, GSM_MANAGER_LOGOUT_MODE_NO_CONFIRMATION, GSM_MANAGER_LOGOUT_MODE_NORMAL, GSM_MANAGER_PHASE_RUNNING, and TRUE.
gsm_manager_new()
GsmManager * gsm_manager_new (GsmStore * client_store, gboolean failsafe)
Definition at line 2915 of file gsm-manager.c.
References GSM_TYPE_MANAGER, and NULL.
Referenced by main().
gsm_manager_register_client()
gboolean gsm_manager_register_client (GsmManager * manager, const char * app_id, const char * client_startup_id, DBusGMethodInvocation * context)
Definition at line 3747 of file gsm-manager.c.
References FALSE, gsm_app_peek_app_id(), gsm_app_registered(), gsm_client_peek_id(), gsm_client_set_app_id(), gsm_client_set_status(), gsm_dbus_client_new(), GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_ALREADY_REGISTERED, GSM_MANAGER_ERROR_GENERAL, GSM_MANAGER_ERROR_NOT_IN_RUNNING, GSM_MANAGER_PHASE_QUERY_END_SESSION, gsm_store_add(), gsm_store_find(), gsm_util_generate_startup_id(), IS_STRING_EMPTY, NULL, and TRUE.
gsm_manager_request_reboot()
gboolean gsm_manager_request_reboot (GsmManager * manager, GError ** error)
Definition at line 3586 of file gsm-manager.c.
References error, FALSE, GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_NOT_IN_RUNNING, GSM_MANAGER_PHASE_RUNNING, and TRUE.
gsm_manager_request_shutdown()
gboolean gsm_manager_request_shutdown (GsmManager * manager, GError ** error)
Definition at line 3563 of file gsm-manager.c.
References error, FALSE, GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_NOT_IN_RUNNING, GSM_MANAGER_PHASE_RUNNING, and TRUE.
gsm_manager_set_phase()
gboolean gsm_manager_set_phase (GsmManager * manager, GsmManagerPhase phase)
Definition at line 3550 of file gsm-manager.c.
References FALSE, and TRUE.
Referenced by gsm_manager_start().
gsm_manager_setenv()
gboolean gsm_manager_setenv (GsmManager * manager, const char * variable, const char * value, GError ** error)
Definition at line 2941 of file gsm-manager.c.
References error, FALSE, GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_NOT_IN_INITIALIZATION, GSM_MANAGER_PHASE_INITIALIZATION, gsm_util_setenv(), and TRUE.
gsm_manager_shutdown()
gboolean gsm_manager_shutdown (GsmManager * manager, GError ** error)
Definition at line 3631 of file gsm-manager.c.
References error, FALSE, GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_LOCKED_DOWN, GSM_MANAGER_ERROR_NOT_IN_RUNNING, GSM_MANAGER_PHASE_RUNNING, and TRUE.
gsm_manager_start()
void gsm_manager_start (GsmManager * manager)
Definition at line 1681 of file gsm-manager.c.
References GSM_MANAGER_PHASE_INITIALIZATION, and gsm_manager_set_phase().
Referenced by main().
gsm_manager_uninhibit()
gboolean gsm_manager_uninhibit (GsmManager * manager, guint inhibit_cookie, DBusGMethodInvocation * context)
Definition at line 3973 of file gsm-manager.c.
References FALSE, gsm_inhibitor_peek_app_id(), gsm_inhibitor_peek_bus_name(), gsm_inhibitor_peek_flags(), gsm_inhibitor_peek_id(), gsm_inhibitor_peek_reason(), gsm_inhibitor_peek_toplevel_xid(), GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_GENERAL, gsm_store_find(), gsm_store_remove(), NULL, and TRUE.
gsm_manager_unregister_client()
gboolean gsm_manager_unregister_client (GsmManager * manager, const char * session_client_id, DBusGMethodInvocation * context)
Definition at line 3853 of file gsm-manager.c.
References FALSE, gsm_client_set_status(), GSM_MANAGER_ERROR, GSM_MANAGER_ERROR_NOT_REGISTERED, gsm_store_lookup(), NULL, and TRUE.