MATE Desktop Environment: gsm-client.c File Reference
gsm-client.c File Reference
#include "config.h"
#include <dbus/dbus-glib.h>
#include "eggdesktopfile.h"
#include "gsm-marshal.h"
#include "gsm-client.h"
#include "gsm-client-glue.h"
Macros
#define ENUM_ENTRY(NAME, DESC)
Enumerations
enum {
PROP_0 , PROP_ID , PROP_STARTUP_ID , PROP_APP_ID ,
PROP_STATUS
}
enum { DISCONNECTED , END_SESSION_RESPONSE , LAST_SIGNAL }
Functions
GQuark gsm_client_error_quark (void)
GType gsm_client_error_get_type (void)
void gsm_client_set_status (GsmClient *client, guint status)
void gsm_client_set_app_id (GsmClient *client, const char *app_id)
const char * gsm_client_peek_id (GsmClient *client)
const char * gsm_client_peek_app_id (GsmClient *client)
const char * gsm_client_peek_startup_id (GsmClient *client)
guint gsm_client_peek_status (GsmClient *client)
guint gsm_client_peek_restart_style_hint (GsmClient *client)
gboolean gsm_client_get_startup_id (GsmClient *client, char **id, GError **error)
gboolean gsm_client_get_app_id (GsmClient *client, char **id, GError **error)
gboolean gsm_client_get_restart_style_hint (GsmClient *client, guint *hint, GError **error)
gboolean gsm_client_get_status (GsmClient *client, guint *status, GError **error)
gboolean gsm_client_get_unix_process_id (GsmClient *client, guint *pid, GError **error)
char * gsm_client_get_app_name (GsmClient *client)
gboolean gsm_client_cancel_end_session (GsmClient *client, GError **error)
gboolean gsm_client_query_end_session (GsmClient *client, guint flags, GError **error)
gboolean gsm_client_end_session (GsmClient *client, guint flags, GError **error)
gboolean gsm_client_stop (GsmClient *client, GError **error)
void gsm_client_disconnected (GsmClient *client)
GKeyFile * gsm_client_save (GsmClient *client, GError **error)
void gsm_client_end_session_response (GsmClient *client, gboolean is_ok, gboolean do_last, gboolean cancel, const char *reason)
Macro Definition Documentation
ENUM_ENTRY
#define ENUM_ENTRY (NAME, DESC)
Value:
{ NAME, "" #NAME "", DESC }
Definition at line 73 of file gsm-client.c.
Referenced by gsm_client_error_get_type().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_ID
PROP_STARTUP_ID
PROP_APP_ID
PROP_STATUS
Definition at line 44 of file gsm-client.c.
anonymous enum
anonymous enum
Enumerator
DISCONNECTED
END_SESSION_RESPONSE
LAST_SIGNAL
Definition at line 52 of file gsm-client.c.
Function Documentation
gsm_client_cancel_end_session()
gboolean gsm_client_cancel_end_session (GsmClient * client, GError ** error)
Definition at line 521 of file gsm-client.c.
References error, and FALSE.
gsm_client_disconnected()
void gsm_client_disconnected (GsmClient * client)
Definition at line 559 of file gsm-client.c.
References DISCONNECTED.
gsm_client_end_session()
gboolean gsm_client_end_session (GsmClient * client, guint flags, GError ** error)
Definition at line 540 of file gsm-client.c.
References error, and FALSE.
gsm_client_end_session_response()
void gsm_client_end_session_response (GsmClient * client, gboolean is_ok, gboolean do_last, gboolean cancel, const char * reason)
Definition at line 574 of file gsm-client.c.
References END_SESSION_RESPONSE.
gsm_client_error_get_type()
GType gsm_client_error_get_type (void)
Definition at line 76 of file gsm-client.c.
References ENUM_ENTRY, GSM_CLIENT_ERROR_GENERAL, GSM_CLIENT_ERROR_NOT_REGISTERED, and GSM_CLIENT_NUM_ERRORS.
gsm_client_error_quark()
GQuark gsm_client_error_quark (void)
Definition at line 63 of file gsm-client.c.
gsm_client_get_app_id()
gboolean gsm_client_get_app_id (GsmClient * client, char ** id, GError ** error)
Definition at line 452 of file gsm-client.c.
References error, FALSE, and TRUE.
gsm_client_get_app_name()
char * gsm_client_get_app_name (GsmClient * client)
gsm_client_get_app_name: @client: a #GsmClient.
Returns: a copy of the application name of the client, or NULL if no such name is known.
Definition at line 513 of file gsm-client.c.
References NULL.
gsm_client_get_restart_style_hint()
gboolean gsm_client_get_restart_style_hint (GsmClient * client, guint * hint, GError ** error)
Definition at line 467 of file gsm-client.c.
References error, FALSE, and TRUE.
gsm_client_get_startup_id()
gboolean gsm_client_get_startup_id (GsmClient * client, char ** id, GError ** error)
Definition at line 437 of file gsm-client.c.
References error, FALSE, and TRUE.
gsm_client_get_status()
gboolean gsm_client_get_status (GsmClient * client, guint * status, GError ** error)
Definition at line 479 of file gsm-client.c.
References error, FALSE, and TRUE.
gsm_client_get_unix_process_id()
gboolean gsm_client_get_unix_process_id (GsmClient * client, guint * pid, GError ** error)
Definition at line 494 of file gsm-client.c.
References error, FALSE, and TRUE.
gsm_client_peek_app_id()
const char * gsm_client_peek_app_id (GsmClient * client)
gsm_client_peek_app_id: @client: a #GsmClient.
Note that the application ID might not be known; this happens when for XSMP clients that we did not start ourselves, for instance.
Returns: the application ID of the client, or NULL if no such ID is known. The string is owned by @client.
Definition at line 396 of file gsm-client.c.
References NULL.
gsm_client_peek_id()
const char * gsm_client_peek_id (GsmClient * client)
Definition at line 375 of file gsm-client.c.
References NULL.
Referenced by gsm_manager_register_client().
gsm_client_peek_restart_style_hint()
guint gsm_client_peek_restart_style_hint (GsmClient * client)
Definition at line 429 of file gsm-client.c.
References GSM_CLIENT_RESTART_NEVER.
gsm_client_peek_startup_id()
const char * gsm_client_peek_startup_id (GsmClient * client)
Definition at line 407 of file gsm-client.c.
References NULL.
gsm_client_peek_status()
guint gsm_client_peek_status (GsmClient * client)
Definition at line 418 of file gsm-client.c.
gsm_client_query_end_session()
gboolean gsm_client_query_end_session (GsmClient * client, guint flags, GError ** error)
Definition at line 530 of file gsm-client.c.
References error, and FALSE.
gsm_client_save()
GKeyFile * gsm_client_save (GsmClient * client, GError ** error)
Definition at line 565 of file gsm-client.c.
References error, and FALSE.
gsm_client_set_app_id()
void gsm_client_set_app_id (GsmClient * client, const char * app_id)
Definition at line 215 of file gsm-client.c.
References NULL.
Referenced by gsm_manager_register_client().
gsm_client_set_status()
void gsm_client_set_status (GsmClient * client, guint status)
Definition at line 182 of file gsm-client.c.
Referenced by gsm_manager_register_client(), and gsm_manager_unregister_client().
gsm_client_stop()
gboolean gsm_client_stop (GsmClient * client, GError ** error)
Definition at line 550 of file gsm-client.c.
References error, and FALSE.