MATE Desktop Environment: gsp-app-manager.h File Reference
gsp-app-manager.h File Reference
#include <glib-object.h>
#include <gsp-app.h>
Macros
#define GSP_TYPE_APP_MANAGER (gsp_app_manager_get_type ())
Functions
G_DECLARE_DERIVABLE_TYPE (...) struct _GspAppManagerClass
GspAppManager * gsp_app_manager_get (void)
void gsp_app_manager_fill (GspAppManager *manager)
GSList * gsp_app_manager_get_apps (GspAppManager *manager)
GspApp * gsp_app_manager_find_app_with_basename (GspAppManager *manager, const char *basename)
const char * gsp_app_manager_get_dir (GspAppManager *manager, unsigned int index)
void gsp_app_manager_add (GspAppManager *manager, GspApp *app)
Macro Definition Documentation
GSP_TYPE_APP_MANAGER
#define GSP_TYPE_APP_MANAGER (gsp_app_manager_get_type ())
Definition at line 34 of file gsp-app-manager.h.
Referenced by gsp_app_manager_get().
Function Documentation
G_DECLARE_DERIVABLE_TYPE()
G_DECLARE_DERIVABLE_TYPE (...)
MateUiApplicationClass: @parent_class: Parent class
Class structure for MateUiApplication
MateUiWindowClass: @parent_class: The parent class
The class structure for #MateUiWindow
MATE_PANEL_APPLETS_MANAGER_EXTENSION_POINT_NAME:
Extension point for #MatePanelAppletsManager functionality.
Definition at line 35 of file gsp-app-manager.h.
References parent_class.
gsp_app_manager_add()
void gsp_app_manager_add (GspAppManager * manager, GspApp * app)
Definition at line 553 of file gsp-app-manager.c.
Referenced by gsp_app_copy_desktop_file(), and gsp_app_create().
gsp_app_manager_fill()
void gsp_app_manager_fill (GspAppManager * manager)
Definition at line 492 of file gsp-app-manager.c.
References gsm_util_get_autostart_dirs(), and NULL.
gsp_app_manager_find_app_with_basename()
GspApp * gsp_app_manager_find_app_with_basename (GspAppManager * manager, const char * basename)
Definition at line 572 of file gsp-app-manager.c.
References gsp_app_get_basename(), and NULL.
Referenced by gsp_app_new(), and msm_desktop_app_dialog_new().
gsp_app_manager_get()
GspAppManager * gsp_app_manager_get (void)
Definition at line 598 of file gsp-app-manager.c.
References GSP_TYPE_APP_MANAGER, and NULL.
Referenced by gsp_app_copy_desktop_file(), gsp_app_create(), and gsp_app_new().
gsp_app_manager_get_apps()
GSList * gsp_app_manager_get_apps (GspAppManager * manager)
Definition at line 611 of file gsp-app-manager.c.
References NULL.
gsp_app_manager_get_dir()
const char * gsp_app_manager_get_dir (GspAppManager * manager, unsigned int index)
Definition at line 222 of file gsp-app-manager.c.
References NULL.