MATE Desktop Environment: gsp-app.c File Reference
gsp-app.c File Reference
#include <string.h>
#include <sys/stat.h>
#include <glib/gi18n.h>
#include <glib/gstdio.h>
#include "gsm-app-dialog.h"
#include "gsm-properties-dialog.h"
#include "gsm-util.h"
#include "gsp-app-manager.h"
#include "gsp-keyfile.h"
#include "gsp-app.h"
Macros
#define GSP_APP_SAVE_DELAY 2
#define GSP_ASP_SAVE_MASK_HIDDEN 0x0001
#define GSP_ASP_SAVE_MASK_NAME 0x0002
#define GSP_ASP_SAVE_MASK_EXEC 0x0004
#define GSP_ASP_SAVE_MASK_COMMENT 0x0008
#define GSP_ASP_SAVE_MASK_DELAY 0x0010
#define GSP_ASP_SAVE_MASK_ALL 0xffff
#define _GSP_FIND_MAX_TRY 10000
Enumerations
enum { CHANGED , REMOVED , LAST_SIGNAL }
Functions
const char * gsp_app_get_basename (GspApp *app)
const char * gsp_app_get_path (GspApp *app)
gboolean gsp_app_get_hidden (GspApp *app)
void gsp_app_set_hidden (GspApp *app, gboolean hidden)
gboolean gsp_app_get_nodisplay (GspApp *app)
const char * gsp_app_get_name (GspApp *app)
const char * gsp_app_get_exec (GspApp *app)
const char * gsp_app_get_comment (GspApp *app)
guint gsp_app_get_delay (GspApp *app)
GIcon * gsp_app_get_icon (GspApp *app)
unsigned int gsp_app_get_xdg_position (GspApp *app)
unsigned int gsp_app_get_xdg_system_position (GspApp *app)
void gsp_app_set_xdg_system_position (GspApp *app, unsigned int position)
const char * gsp_app_get_description (GspApp *app)
void gsp_app_update (GspApp *app, const char *name, const char *comment, const char *exec, guint delay)
void gsp_app_delete (GspApp *app)
void gsp_app_reload_at (GspApp *app, const char *path, unsigned int xdg_position)
GspApp * gsp_app_new (const char *path, unsigned int xdg_position)
void gsp_app_create (const char *name, const char *comment, const char *exec, guint delay)
gboolean gsp_app_copy_desktop_file (const char *uri)
Macro Definition Documentation
_GSP_FIND_MAX_TRY
#define _GSP_FIND_MAX_TRY 10000
GSP_APP_SAVE_DELAY
#define GSP_APP_SAVE_DELAY 2
Definition at line 43 of file gsp-app.c.
GSP_ASP_SAVE_MASK_ALL
#define GSP_ASP_SAVE_MASK_ALL 0xffff
Definition at line 50 of file gsp-app.c.
Referenced by gsp_app_create().
GSP_ASP_SAVE_MASK_COMMENT
#define GSP_ASP_SAVE_MASK_COMMENT 0x0008
Definition at line 48 of file gsp-app.c.
Referenced by gsp_app_update().
GSP_ASP_SAVE_MASK_DELAY
#define GSP_ASP_SAVE_MASK_DELAY 0x0010
Definition at line 49 of file gsp-app.c.
Referenced by gsp_app_update().
GSP_ASP_SAVE_MASK_EXEC
#define GSP_ASP_SAVE_MASK_EXEC 0x0004
Definition at line 47 of file gsp-app.c.
Referenced by gsp_app_update().
GSP_ASP_SAVE_MASK_HIDDEN
#define GSP_ASP_SAVE_MASK_HIDDEN 0x0001
Definition at line 45 of file gsp-app.c.
Referenced by gsp_app_copy_desktop_file(), gsp_app_delete(), and gsp_app_set_hidden().
GSP_ASP_SAVE_MASK_NAME
#define GSP_ASP_SAVE_MASK_NAME 0x0002
Definition at line 46 of file gsp-app.c.
Referenced by gsp_app_update().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CHANGED
REMOVED
LAST_SIGNAL
Definition at line 84 of file gsp-app.c.
Function Documentation
gsp_app_copy_desktop_file()
gboolean gsp_app_copy_desktop_file (const char * uri)
Definition at line 1122 of file gsp-app.c.
References FALSE, gsp_app_manager_add(), gsp_app_manager_get(), gsp_app_new(), GSP_ASP_SAVE_MASK_HIDDEN, NULL, and TRUE.
gsp_app_create()
void gsp_app_create (const char * name, const char * comment, const char * exec, guint delay)
Definition at line 1056 of file gsp-app.c.
References comment, delay, FALSE, gsm_util_text_is_blank(), gsp_app_manager_add(), gsp_app_manager_get(), GSP_ASP_SAVE_MASK_ALL, GSP_TYPE_APP, name, and NULL.
gsp_app_delete()
void gsp_app_delete (GspApp * app)
Definition at line 781 of file gsp-app.c.
References GSP_ASP_SAVE_MASK_HIDDEN, and TRUE.
gsp_app_get_basename()
const char * gsp_app_get_basename (GspApp * app)
Definition at line 544 of file gsp-app.c.
References NULL.
Referenced by gsp_app_manager_find_app_with_basename().
gsp_app_get_comment()
const char * gsp_app_get_comment (GspApp * app)
Definition at line 637 of file gsp-app.c.
References NULL.
gsp_app_get_delay()
guint gsp_app_get_delay (GspApp * app)
Definition at line 649 of file gsp-app.c.
gsp_app_get_description()
const char * gsp_app_get_description (GspApp * app)
Definition at line 713 of file gsp-app.c.
References NULL.
gsp_app_get_exec()
const char * gsp_app_get_exec (GspApp * app)
Definition at line 625 of file gsp-app.c.
References NULL.
gsp_app_get_hidden()
gboolean gsp_app_get_hidden (GspApp * app)
Definition at line 568 of file gsp-app.c.
References FALSE.
gsp_app_get_icon()
GIcon * gsp_app_get_icon (GspApp * app)
Definition at line 660 of file gsp-app.c.
References NULL.
gsp_app_get_name()
const char * gsp_app_get_name (GspApp * app)
Definition at line 613 of file gsp-app.c.
References NULL.
gsp_app_get_nodisplay()
gboolean gsp_app_get_nodisplay (GspApp * app)
Definition at line 601 of file gsp-app.c.
References FALSE.
gsp_app_get_path()
const char * gsp_app_get_path (GspApp * app)
Definition at line 556 of file gsp-app.c.
References NULL.
gsp_app_get_xdg_position()
unsigned int gsp_app_get_xdg_position (GspApp * app)
Definition at line 676 of file gsp-app.c.
gsp_app_get_xdg_system_position()
unsigned int gsp_app_get_xdg_system_position (GspApp * app)
Definition at line 688 of file gsp-app.c.
gsp_app_new()
GspApp * gsp_app_new (const char * path, unsigned int xdg_position)
Definition at line 872 of file gsp-app.c.
References FALSE, gsm_util_text_is_blank(), gsp_app_manager_find_app_with_basename(), gsp_app_manager_get(), gsp_key_file_get_boolean(), gsp_key_file_get_delay, gsp_key_file_get_locale_string, gsp_key_file_get_string, GSP_TYPE_APP, MIN, and NULL.
Referenced by gsp_app_copy_desktop_file(), and gsp_app_reload_at().
gsp_app_reload_at()
void gsp_app_reload_at (GspApp * app, const char * path, unsigned int xdg_position)
Definition at line 821 of file gsp-app.c.
References gsp_app_new().
gsp_app_set_hidden()
void gsp_app_set_hidden (GspApp * app, gboolean hidden)
Definition at line 580 of file gsp-app.c.
References GSP_ASP_SAVE_MASK_HIDDEN.
gsp_app_set_xdg_system_position()
void gsp_app_set_xdg_system_position (GspApp * app, unsigned int position)
Definition at line 700 of file gsp-app.c.
gsp_app_update()
void gsp_app_update (GspApp * app, const char * name, const char * comment, const char * exec, guint delay)
Definition at line 729 of file gsp-app.c.
References comment, delay, FALSE, GSP_ASP_SAVE_MASK_COMMENT, GSP_ASP_SAVE_MASK_DELAY, GSP_ASP_SAVE_MASK_EXEC, GSP_ASP_SAVE_MASK_NAME, name, and TRUE.