MATE Desktop Environment: gtk-utils.c File Reference
gtk-utils.c File Reference
#include <config.h>
#include <string.h>
#include <glib.h>
#include <gtk/gtk.h>
#include "gtk-utils.h"
Functions
GtkWidget * _gtk_message_dialog_new (GtkWindow *parent, GtkDialogFlags flags, const char *icon_name, const char *message, const char *secondary_message, const gchar *first_button_text,...)
char * _gtk_request_dialog_run (GtkWindow *parent, GtkDialogFlags flags, const char *title, const char *message, const char *default_value, int max_length, const gchar *no_button_text, const gchar *yes_button_text)
GtkWidget * _gtk_error_dialog_new (GtkWindow *parent, GtkDialogFlags flags, GList *row_output, const char *primary_text, const char *secondary_text,...)
void _gtk_error_dialog_run (GtkWindow *parent, const gchar *main_message, const gchar *format,...)
void _gtk_entry_set_locale_text (GtkEntry *entry, const char *text)
char * _gtk_entry_get_locale_text (GtkEntry *entry)
void _gtk_entry_set_filename_text (GtkEntry *entry, const char *text)
GdkPixbuf * get_icon_pixbuf (GIcon *icon, int size, GtkIconTheme *theme)
GdkPixbuf * get_mime_type_pixbuf (const char *mime_type, int icon_size, GtkIconTheme *icon_theme)
void show_help_dialog (GtkWindow *parent, const char *section)
int _gtk_widget_lookup_for_size (GtkWidget *widget, GtkIconSize icon_size)
Function Documentation
_gtk_entry_get_locale_text()
char * _gtk_entry_get_locale_text (GtkEntry * entry)
Definition at line 425 of file gtk-utils.c.
References NULL.
Referenced by _gtk_request_dialog_run().
_gtk_entry_set_filename_text()
void _gtk_entry_set_filename_text (GtkEntry * entry, const char * text)
Definition at line 440 of file gtk-utils.c.
References NULL.
Referenced by _gtk_request_dialog_run(), and dlg_batch_add_files().
_gtk_entry_set_locale_text()
void _gtk_entry_set_locale_text (GtkEntry * entry, const char * text)
Definition at line 408 of file gtk-utils.c.
References NULL.
Referenced by _gtk_request_dialog_run(), and dlg_password().
_gtk_error_dialog_new()
GtkWidget * _gtk_error_dialog_new (GtkWindow * parent, GtkDialogFlags flags, GList * row_output, const char * primary_text, const char * secondary_text, ...)
Definition at line 236 of file gtk-utils.c.
References _, FALSE, label, NULL, and TRUE.
Referenced by fr_window_archive_extract(), fr_window_archive_save_as(), and fr_window_rename_selection().
_gtk_error_dialog_run()
void _gtk_error_dialog_run (GtkWindow * parent, const gchar * main_message, const gchar * format, ...)
Definition at line 378 of file gtk-utils.c.
References _gtk_message_dialog_new(), message(), and NULL.
Referenced by _gtk_request_dialog_run(), fr_window_open_files_with_application(), and fr_window_open_files_with_command().
_gtk_message_dialog_new()
GtkWidget * _gtk_message_dialog_new (GtkWindow * parent, GtkDialogFlags flags, const char * icon_name, const char * message, const char * secondary_message, const gchar * first_button_text, ...)
Definition at line 30 of file gtk-utils.c.
References FALSE, label, message(), NULL, and TRUE.
Referenced by _gtk_error_dialog_run(), dlg_package_installer(), fr_window_archive_extract(), fr_window_rename_selection(), and show_help_dialog().
_gtk_request_dialog_run()
char * _gtk_request_dialog_run (GtkWindow * parent, GtkDialogFlags flags, const char * title, const char * message, const char * default_value, int max_length, const gchar * no_button_text, const gchar * yes_button_text)
Definition at line 148 of file gtk-utils.c.
References FALSE, label, message(), NULL, and TRUE.
Referenced by fr_window_paste_selection(), and fr_window_rename_selection().
_gtk_widget_lookup_for_size()
int _gtk_widget_lookup_for_size (GtkWidget * widget, GtkIconSize icon_size)
Definition at line 564 of file gtk-utils.c.
References MAX.
Referenced by _gtk_request_dialog_run().
get_icon_pixbuf()
GdkPixbuf * get_icon_pixbuf (GIcon * icon, int size, GtkIconTheme * theme)
Definition at line 499 of file gtk-utils.c.
References NULL.
Referenced by _gtk_request_dialog_run(), and get_mime_type_pixbuf().
get_mime_type_pixbuf()
GdkPixbuf * get_mime_type_pixbuf (const char * mime_type, int icon_size, GtkIconTheme * icon_theme)
Definition at line 513 of file gtk-utils.c.
References get_icon_pixbuf(), mime_type, and NULL.
Referenced by _gtk_request_dialog_run().
show_help_dialog()
void show_help_dialog (GtkWindow * parent, const char * section)
Definition at line 531 of file gtk-utils.c.
References _, _gtk_message_dialog_new(), error, FALSE, and NULL.
Referenced by _gtk_request_dialog_run(), and activate_action_manual().