MATE Desktop Environment: gtkrc-utils.c File Reference
gtkrc-utils.c File Reference
#include <string.h>
#include <unistd.h>
#include <glib.h>
#include <glib/gstdio.h>
#include <fcntl.h>
#include <gtk/gtk.h>
#include "gtkrc-utils.h"
Macros
#define INCLUDE_SYMBOL ((gpointer) 1)
#define ENGINE_SYMBOL ((gpointer) 2)
#define COLOR_SCHEME_SYMBOL ((gpointer) 3)
Functions
gchar * gtkrc_find_named (const gchar *name)
void gtkrc_get_details (gchar *filename, GSList **engines, GSList **symbolic_colors)
gchar * gtkrc_get_color_scheme (const gchar *gtkrc_file)
gchar * gtkrc_get_color_scheme_for_theme (const gchar *theme_name)
Macro Definition Documentation
COLOR_SCHEME_SYMBOL
#define COLOR_SCHEME_SYMBOL ((gpointer) 3)
Definition at line 37 of file gtkrc-utils.c.
Referenced by gtkrc_get_color_scheme().
ENGINE_SYMBOL
#define ENGINE_SYMBOL ((gpointer) 2)
Definition at line 36 of file gtkrc-utils.c.
Referenced by gtkrc_get_details().
INCLUDE_SYMBOL
#define INCLUDE_SYMBOL ((gpointer) 1)
Definition at line 35 of file gtkrc-utils.c.
Referenced by gtkrc_get_color_scheme(), and gtkrc_get_details().
Function Documentation
gtkrc_find_named()
gchar * gtkrc_find_named (const gchar * name)
Definition at line 39 of file gtkrc-utils.c.
References name, and NULL.
Referenced by gtk_theme_info_missing_engine(), and gtkrc_get_color_scheme_for_theme().
gtkrc_get_color_scheme()
gchar * gtkrc_get_color_scheme (const gchar * gtkrc_file)
Definition at line 225 of file gtkrc-utils.c.
References COLOR_SCHEME_SYMBOL, INCLUDE_SYMBOL, and NULL.
Referenced by gtkrc_get_color_scheme_for_theme().
gtkrc_get_color_scheme_for_theme()
gchar * gtkrc_get_color_scheme_for_theme (const gchar * theme_name)
Definition at line 289 of file gtkrc-utils.c.
References gtkrc_find_named(), gtkrc_get_color_scheme(), and NULL.
Referenced by generate_gtk_theme_thumbnail(), generate_gtk_theme_thumbnail_async(), mate_meta_theme_set(), and mate_theme_read_meta_theme().
gtkrc_get_details()
void gtkrc_get_details (gchar * filename, GSList ** engines, GSList ** symbolic_colors)
Definition at line 84 of file gtkrc-utils.c.
References ENGINE_SYMBOL, INCLUDE_SYMBOL, and NULL.
Referenced by gtk_theme_info_missing_engine().