MATE Desktop Environment: gvc-applet.c File Reference
gvc-applet.c File Reference
#include "config.h"
#include <string.h>
#include <glib.h>
#include <glib/gi18n-lib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <libmatemixer/matemixer.h>
#include <mate-panel-applet.h>
#include "gvc-applet.h"
#include "gvc-stream-applet-icon.h"
Functions
void gvc_applet_start (GvcApplet *applet)
GvcApplet * gvc_applet_new (void)
gboolean gvc_applet_fill (GvcApplet *applet, MatePanelApplet *applet_widget)
Function Documentation
gvc_applet_fill()
gboolean gvc_applet_fill (GvcApplet * applet, MatePanelApplet * applet_widget)
Definition at line 512 of file gvc-applet.c.
References _, APPLET_ICON, GETTEXT_PACKAGE, gvc_stream_applet_icon_set_orient(), gvc_stream_applet_icon_set_size(), MATE_PANEL_APPLET_EXPAND_MINOR, mate_panel_applet_get_orient(), mate_panel_applet_get_size(), mate_panel_applet_set_flags(), mate_panel_applet_setup_menu(), NULL, _GvcApplet::priv, and TRUE.
gvc_applet_new()
GvcApplet * gvc_applet_new (void)
Definition at line 431 of file gvc-applet.c.
References GVC_TYPE_APPLET, and NULL.
gvc_applet_start()
void gvc_applet_start (GvcApplet * applet)
Definition at line 350 of file gvc-applet.c.
References FALSE, GVC_IS_APPLET, mate_mixer_context_open(), _GvcApplet::priv, and TRUE.