MATE Desktop Environment: gvc-stream-applet-icon.h File Reference
gvc-stream-applet-icon.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
Classes
struct _GvcStreamAppletIcon
struct _GvcStreamAppletIconClass
Macros
#define GVC_TYPE_STREAM_APPLET_ICON (gvc_stream_applet_icon_get_type ())
#define GVC_STREAM_APPLET_ICON(o)
#define GVC_STREAM_APPLET_ICON_CLASS(k)
#define GVC_IS_STREAM_APPLET_ICON(o)
#define GVC_IS_STREAM_APPLET_ICON_CLASS(k)
#define GVC_STREAM_APPLET_ICON_GET_CLASS(o)
Typedefs
typedef struct _GvcStreamAppletIcon GvcStreamAppletIcon
typedef struct _GvcStreamAppletIconClass GvcStreamAppletIconClass
typedef struct _GvcStreamAppletIconPrivate GvcStreamAppletIconPrivate
Functions
GType gvc_stream_applet_icon_get_type (void)
GvcStreamAppletIcon * gvc_stream_applet_icon_new (MateMixerStreamControl *control, const gchar **icon_names)
void gvc_stream_applet_icon_set_icon_names (GvcStreamAppletIcon *icon, const gchar **icon_names)
void gvc_stream_applet_icon_set_display_name (GvcStreamAppletIcon *icon, const gchar *display_name)
void gvc_stream_applet_icon_set_control (GvcStreamAppletIcon *icon, MateMixerStreamControl *control)
void gvc_stream_applet_icon_set_size (GvcStreamAppletIcon *icon, guint size)
void gvc_stream_applet_icon_set_orient (GvcStreamAppletIcon *icon, MatePanelAppletOrient orient)
gboolean gvc_stream_applet_icon_get_mute (GvcStreamAppletIcon *icon)
void gvc_stream_applet_icon_set_mute (GvcStreamAppletIcon *icon, gboolean mute)
void gvc_stream_applet_icon_volume_control (GvcStreamAppletIcon *icon)
Macro Definition Documentation
GVC_IS_STREAM_APPLET_ICON
#define GVC_IS_STREAM_APPLET_ICON (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), GVC_TYPE_STREAM_APPLET_ICON))
Definition at line 36 of file gvc-stream-applet-icon.h.
Referenced by gvc_stream_applet_icon_set_control(), gvc_stream_applet_icon_set_display_name(), and gvc_stream_applet_icon_set_icon_names().
GVC_IS_STREAM_APPLET_ICON_CLASS
#define GVC_IS_STREAM_APPLET_ICON_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), GVC_TYPE_STREAM_APPLET_ICON))
Definition at line 37 of file gvc-stream-applet-icon.h.
GVC_STREAM_APPLET_ICON
#define GVC_STREAM_APPLET_ICON (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), GVC_TYPE_STREAM_APPLET_ICON, GvcStreamAppletIcon))
Definition at line 34 of file gvc-stream-applet-icon.h.
GVC_STREAM_APPLET_ICON_CLASS
#define GVC_STREAM_APPLET_ICON_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST ((k), GVC_TYPE_STREAM_APPLET_ICON, GvcStreamAppletIconClass))
Definition at line 35 of file gvc-stream-applet-icon.h.
GVC_STREAM_APPLET_ICON_GET_CLASS
#define GVC_STREAM_APPLET_ICON_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), GVC_TYPE_STREAM_APPLET_ICON, GvcStreamAppletIconClass))
Definition at line 38 of file gvc-stream-applet-icon.h.
GVC_TYPE_STREAM_APPLET_ICON
#define GVC_TYPE_STREAM_APPLET_ICON (gvc_stream_applet_icon_get_type ())
Definition at line 33 of file gvc-stream-applet-icon.h.
Referenced by gvc_stream_applet_icon_new().
Typedef Documentation
GvcStreamAppletIcon
typedef struct _GvcStreamAppletIcon GvcStreamAppletIcon
Definition at line 40 of file gvc-stream-applet-icon.h.
GvcStreamAppletIconClass
typedef struct _GvcStreamAppletIconClass GvcStreamAppletIconClass
Definition at line 41 of file gvc-stream-applet-icon.h.
GvcStreamAppletIconPrivate
typedef struct _GvcStreamAppletIconPrivate GvcStreamAppletIconPrivate
Definition at line 42 of file gvc-stream-applet-icon.h.
Function Documentation
gvc_stream_applet_icon_get_mute()
gboolean gvc_stream_applet_icon_get_mute (GvcStreamAppletIcon * icon)
Definition at line 264 of file gvc-stream-applet-icon.c.
References mate_mixer_stream_control_get_mute().
gvc_stream_applet_icon_get_type()
GType gvc_stream_applet_icon_get_type (void)
References MatePanelAppletOrient.
gvc_stream_applet_icon_new()
GvcStreamAppletIcon * gvc_stream_applet_icon_new (MateMixerStreamControl * control, const gchar ** icon_names)
Definition at line 873 of file gvc-stream-applet-icon.c.
References GVC_TYPE_STREAM_APPLET_ICON, and NULL.
gvc_stream_applet_icon_set_control()
void gvc_stream_applet_icon_set_control (GvcStreamAppletIcon * icon, MateMixerStreamControl * control)
Definition at line 592 of file gvc-stream-applet-icon.c.
References GVC_CHANNEL_BAR, gvc_channel_bar_set_control(), GVC_IS_STREAM_APPLET_ICON, NULL, and PROP_CONTROL.
gvc_stream_applet_icon_set_display_name()
void gvc_stream_applet_icon_set_display_name (GvcStreamAppletIcon * icon, const gchar * display_name)
Definition at line 578 of file gvc-stream-applet-icon.c.
References GVC_IS_STREAM_APPLET_ICON, name, and PROP_DISPLAY_NAME.
gvc_stream_applet_icon_set_icon_names()
void gvc_stream_applet_icon_set_icon_names (GvcStreamAppletIcon * icon, const gchar ** icon_names)
Definition at line 538 of file gvc-stream-applet-icon.c.
References GVC_IS_STREAM_APPLET_ICON, NULL, and PROP_ICON_NAMES.
gvc_stream_applet_icon_set_mute()
void gvc_stream_applet_icon_set_mute (GvcStreamAppletIcon * icon, gboolean mute)
Definition at line 258 of file gvc-stream-applet-icon.c.
References mate_mixer_stream_control_set_mute().
gvc_stream_applet_icon_set_orient()
void gvc_stream_applet_icon_set_orient (GvcStreamAppletIcon * icon, MatePanelAppletOrient orient)
Definition at line 524 of file gvc-stream-applet-icon.c.
References MatePanelAppletOrient.
Referenced by gvc_applet_fill().
gvc_stream_applet_icon_set_size()
void gvc_stream_applet_icon_set_size (GvcStreamAppletIcon * icon, guint size)
Definition at line 505 of file gvc-stream-applet-icon.c.
Referenced by gvc_applet_fill().
gvc_stream_applet_icon_volume_control()
void gvc_stream_applet_icon_volume_control (GvcStreamAppletIcon * icon)
Definition at line 270 of file gvc-stream-applet-icon.c.
References _, error, mate_gdk_spawn_command_line_on_screen(), and NULL.