MATE Desktop Environment: gvc-status-icon.h File Reference
gvc-status-icon.h File Reference
#include <glib.h>
#include <glib-object.h>
Classes
struct _GvcStatusIcon
struct _GvcStatusIconClass
Macros
#define GVC_STATUS_ICON_DBUS_NAME "org.mate.VolumeControlStatusIcon"
#define GVC_TYPE_STATUS_ICON (gvc_status_icon_get_type ())
#define GVC_STATUS_ICON(o)
#define GVC_STATUS_ICON_CLASS(k)
#define GVC_IS_STATUS_ICON(o)
#define GVC_IS_STATUS_ICON_CLASS(k)
#define GVC_STATUS_ICON_GET_CLASS(o)
Typedefs
typedef struct _GvcStatusIcon GvcStatusIcon
typedef struct _GvcStatusIconClass GvcStatusIconClass
typedef struct _GvcStatusIconPrivate GvcStatusIconPrivate
Functions
GType gvc_status_icon_get_type (void)
GvcStatusIcon * gvc_status_icon_new (void)
void gvc_status_icon_start (GvcStatusIcon *status_icon)
Macro Definition Documentation
GVC_IS_STATUS_ICON
#define GVC_IS_STATUS_ICON (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), GVC_TYPE_STATUS_ICON))
Definition at line 36 of file gvc-status-icon.h.
Referenced by gvc_status_icon_start().
GVC_IS_STATUS_ICON_CLASS
#define GVC_IS_STATUS_ICON_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), GVC_TYPE_STATUS_ICON))
Definition at line 37 of file gvc-status-icon.h.
GVC_STATUS_ICON
#define GVC_STATUS_ICON (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), GVC_TYPE_STATUS_ICON, GvcStatusIcon))
Definition at line 34 of file gvc-status-icon.h.
GVC_STATUS_ICON_CLASS
#define GVC_STATUS_ICON_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST ((k), GVC_TYPE_STATUS_ICON, GvcStatusIconClass))
Definition at line 35 of file gvc-status-icon.h.
GVC_STATUS_ICON_DBUS_NAME
#define GVC_STATUS_ICON_DBUS_NAME "org.mate.VolumeControlStatusIcon"
Definition at line 31 of file gvc-status-icon.h.
Referenced by main().
GVC_STATUS_ICON_GET_CLASS
#define GVC_STATUS_ICON_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), GVC_TYPE_STATUS_ICON, GvcStatusIconClass))
Definition at line 38 of file gvc-status-icon.h.
GVC_TYPE_STATUS_ICON
#define GVC_TYPE_STATUS_ICON (gvc_status_icon_get_type ())
Definition at line 33 of file gvc-status-icon.h.
Referenced by gvc_status_icon_new().
Typedef Documentation
GvcStatusIcon
typedef struct _GvcStatusIcon GvcStatusIcon
Definition at line 40 of file gvc-status-icon.h.
GvcStatusIconClass
typedef struct _GvcStatusIconClass GvcStatusIconClass
Definition at line 41 of file gvc-status-icon.h.
GvcStatusIconPrivate
typedef struct _GvcStatusIconPrivate GvcStatusIconPrivate
Definition at line 42 of file gvc-status-icon.h.
Function Documentation
gvc_status_icon_get_type()
GType gvc_status_icon_get_type (void)
gvc_status_icon_new()
GvcStatusIcon * gvc_status_icon_new (void)
Definition at line 356 of file gvc-status-icon.c.
References GVC_TYPE_STATUS_ICON, and NULL.
Referenced by main().
gvc_status_icon_start()
void gvc_status_icon_start (GvcStatusIcon * status_icon)
Definition at line 272 of file gvc-status-icon.c.
References FALSE, GVC_IS_STATUS_ICON, mate_mixer_context_open(), and TRUE.
Referenced by main().