MATE Desktop Environment: gvc-stream-applet-icon.c File Reference
gvc-stream-applet-icon.c File Reference
#include <config.h>
#include <glib.h>
#include <glib/gi18n-lib.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <libmatemixer/matemixer.h>
#include <mate-panel-applet.h>
#include <libmate-desktop/mate-desktop-utils.h>
#include "gvc-channel-bar.h"
#include "gvc-stream-applet-icon.h"
Macros
#define MATE_DESKTOP_USE_UNSTABLE_API
Enumerations
enum {
PROP_0 , PROP_CONTROL , PROP_DISPLAY_NAME , PROP_ICON_NAMES ,
N_PROPERTIES
}
Functions
void gvc_stream_applet_icon_set_mute (GvcStreamAppletIcon *icon, gboolean mute)
gboolean gvc_stream_applet_icon_get_mute (GvcStreamAppletIcon *icon)
void gvc_stream_applet_icon_volume_control (GvcStreamAppletIcon *icon)
void gvc_stream_applet_icon_set_size (GvcStreamAppletIcon *icon, guint size)
void gvc_stream_applet_icon_set_orient (GvcStreamAppletIcon *icon, MatePanelAppletOrient orient)
void gvc_stream_applet_icon_set_icon_names (GvcStreamAppletIcon *icon, const gchar **names)
void gvc_stream_applet_icon_set_display_name (GvcStreamAppletIcon *icon, const gchar *name)
void gvc_stream_applet_icon_set_control (GvcStreamAppletIcon *icon, MateMixerStreamControl *control)
GvcStreamAppletIcon * gvc_stream_applet_icon_new (MateMixerStreamControl *control, const gchar **icon_names)
Macro Definition Documentation
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 38 of file gvc-stream-applet-icon.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_CONTROL
PROP_DISPLAY_NAME
PROP_ICON_NAMES
N_PROPERTIES
Definition at line 58 of file gvc-stream-applet-icon.c.
Function Documentation
gvc_stream_applet_icon_get_mute()
gboolean gvc_stream_applet_icon_get_mute (GvcStreamAppletIcon * icon)
Definition at line 264 of file gvc-stream-applet-icon.c.
References mate_mixer_stream_control_get_mute().
gvc_stream_applet_icon_new()
GvcStreamAppletIcon * gvc_stream_applet_icon_new (MateMixerStreamControl * control, const gchar ** icon_names)
Definition at line 873 of file gvc-stream-applet-icon.c.
References GVC_TYPE_STREAM_APPLET_ICON, and NULL.
gvc_stream_applet_icon_set_control()
void gvc_stream_applet_icon_set_control (GvcStreamAppletIcon * icon, MateMixerStreamControl * control)
Definition at line 592 of file gvc-stream-applet-icon.c.
References GVC_CHANNEL_BAR, gvc_channel_bar_set_control(), GVC_IS_STREAM_APPLET_ICON, NULL, and PROP_CONTROL.
gvc_stream_applet_icon_set_display_name()
void gvc_stream_applet_icon_set_display_name (GvcStreamAppletIcon * icon, const gchar * name)
Definition at line 578 of file gvc-stream-applet-icon.c.
References GVC_IS_STREAM_APPLET_ICON, name, and PROP_DISPLAY_NAME.
gvc_stream_applet_icon_set_icon_names()
void gvc_stream_applet_icon_set_icon_names (GvcStreamAppletIcon * icon, const gchar ** names)
Definition at line 538 of file gvc-stream-applet-icon.c.
References GVC_IS_STREAM_APPLET_ICON, NULL, and PROP_ICON_NAMES.
gvc_stream_applet_icon_set_mute()
void gvc_stream_applet_icon_set_mute (GvcStreamAppletIcon * icon, gboolean mute)
Definition at line 258 of file gvc-stream-applet-icon.c.
References mate_mixer_stream_control_set_mute().
gvc_stream_applet_icon_set_orient()
void gvc_stream_applet_icon_set_orient (GvcStreamAppletIcon * icon, MatePanelAppletOrient orient)
Definition at line 524 of file gvc-stream-applet-icon.c.
References MatePanelAppletOrient.
Referenced by gvc_applet_fill().
gvc_stream_applet_icon_set_size()
void gvc_stream_applet_icon_set_size (GvcStreamAppletIcon * icon, guint size)
Definition at line 505 of file gvc-stream-applet-icon.c.
Referenced by gvc_applet_fill().
gvc_stream_applet_icon_volume_control()
void gvc_stream_applet_icon_volume_control (GvcStreamAppletIcon * icon)
Definition at line 270 of file gvc-stream-applet-icon.c.
References _, error, mate_gdk_spawn_command_line_on_screen(), and NULL.