MATE Desktop Environment: gvc-channel-bar.c File Reference
gvc-channel-bar.c File Reference
#include "config.h"
#include <sys/param.h>
#include <glib.h>
#include <glib/gi18n-lib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <canberra-gtk.h>
#include <libmatemixer/matemixer.h>
#include "gvc-channel-bar.h"
Macros
#define SCALE_SIZE 128
Enumerations
enum {
PROP_0 , PROP_CONTROL , PROP_ORIENTATION , PROP_SHOW_ICONS ,
PROP_SHOW_MUTE , PROP_SHOW_MARKS , PROP_SHOW_MARK_TEXT , PROP_EXTENDED ,
PROP_NAME , PROP_ICON_NAME , PROP_LOW_ICON_NAME , PROP_HIGH_ICON_NAME ,
N_PROPERTIES
}
Functions
MateMixerStreamControl * gvc_channel_bar_get_control (GvcChannelBar *bar)
void gvc_channel_bar_set_control (GvcChannelBar *bar, MateMixerStreamControl *control)
GtkOrientation gvc_channel_bar_get_orientation (GvcChannelBar *bar)
void gvc_channel_bar_set_orientation (GvcChannelBar *bar, GtkOrientation orientation)
gboolean gvc_channel_bar_get_show_icons (GvcChannelBar *bar)
void gvc_channel_bar_set_show_icons (GvcChannelBar *bar, gboolean show_icons)
gboolean gvc_channel_bar_get_show_mute (GvcChannelBar *bar)
void gvc_channel_bar_set_show_mute (GvcChannelBar *bar, gboolean show_mute)
gboolean gvc_channel_bar_get_show_marks (GvcChannelBar *bar)
void gvc_channel_bar_set_show_marks (GvcChannelBar *bar, gboolean show_marks)
gboolean gvc_channel_bar_get_show_mark_text (GvcChannelBar *bar)
void gvc_channel_bar_set_show_mark_text (GvcChannelBar *bar, gboolean show_mark_text)
gboolean gvc_channel_bar_get_extended (GvcChannelBar *bar)
void gvc_channel_bar_set_extended (GvcChannelBar *bar, gboolean extended)
const gchar * gvc_channel_bar_get_name (GvcChannelBar *bar)
void gvc_channel_bar_set_name (GvcChannelBar *bar, const gchar *name)
const gchar * gvc_channel_bar_get_icon_name (GvcChannelBar *bar)
void gvc_channel_bar_set_icon_name (GvcChannelBar *bar, const gchar *name)
const gchar * gvc_channel_bar_get_low_icon_name (GvcChannelBar *bar)
void gvc_channel_bar_set_low_icon_name (GvcChannelBar *bar, const gchar *name)
const gchar * gvc_channel_bar_get_high_icon_name (GvcChannelBar *bar)
void gvc_channel_bar_set_high_icon_name (GvcChannelBar *bar, const gchar *name)
gboolean gvc_channel_bar_scroll (GvcChannelBar *bar, GdkScrollDirection direction)
void gvc_channel_bar_set_size_group (GvcChannelBar *bar, GtkSizeGroup *group, gboolean symmetric)
GtkWidget * gvc_channel_bar_new (MateMixerStreamControl *control)
Macro Definition Documentation
SCALE_SIZE
#define SCALE_SIZE 128
Definition at line 37 of file gvc-channel-bar.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_CONTROL
PROP_ORIENTATION
PROP_SHOW_ICONS
PROP_SHOW_MUTE
PROP_SHOW_MARKS
PROP_SHOW_MARK_TEXT
PROP_EXTENDED
PROP_NAME
PROP_ICON_NAME
PROP_LOW_ICON_NAME
PROP_HIGH_ICON_NAME
N_PROPERTIES
Definition at line 64 of file gvc-channel-bar.c.
Function Documentation
gvc_channel_bar_get_control()
MateMixerStreamControl * gvc_channel_bar_get_control (GvcChannelBar * bar)
Definition at line 562 of file gvc-channel-bar.c.
References GVC_IS_CHANNEL_BAR, NULL, and _GvcChannelBar::priv.
gvc_channel_bar_get_extended()
gboolean gvc_channel_bar_get_extended (GvcChannelBar * bar)
Definition at line 734 of file gvc-channel-bar.c.
References FALSE, GVC_IS_CHANNEL_BAR, and _GvcChannelBar::priv.
gvc_channel_bar_get_high_icon_name()
const gchar * gvc_channel_bar_get_high_icon_name (GvcChannelBar * bar)
Definition at line 866 of file gvc-channel-bar.c.
References GVC_IS_CHANNEL_BAR, name, NULL, and _GvcChannelBar::priv.
gvc_channel_bar_get_icon_name()
const gchar * gvc_channel_bar_get_icon_name (GvcChannelBar * bar)
Definition at line 788 of file gvc-channel-bar.c.
References GVC_IS_CHANNEL_BAR, name, NULL, and _GvcChannelBar::priv.
gvc_channel_bar_get_low_icon_name()
const gchar * gvc_channel_bar_get_low_icon_name (GvcChannelBar * bar)
Definition at line 843 of file gvc-channel-bar.c.
References GVC_IS_CHANNEL_BAR, name, NULL, and _GvcChannelBar::priv.
gvc_channel_bar_get_name()
const gchar * gvc_channel_bar_get_name (GvcChannelBar * bar)
Definition at line 761 of file gvc-channel-bar.c.
References GVC_IS_CHANNEL_BAR, NULL, and _GvcChannelBar::priv.
gvc_channel_bar_get_orientation()
GtkOrientation gvc_channel_bar_get_orientation (GvcChannelBar * bar)
Definition at line 616 of file gvc-channel-bar.c.
References GVC_IS_CHANNEL_BAR, and _GvcChannelBar::priv.
gvc_channel_bar_get_show_icons()
gboolean gvc_channel_bar_get_show_icons (GvcChannelBar * bar)
Definition at line 639 of file gvc-channel-bar.c.
References FALSE, GVC_IS_CHANNEL_BAR, and _GvcChannelBar::priv.
gvc_channel_bar_get_show_mark_text()
gboolean gvc_channel_bar_get_show_mark_text (GvcChannelBar * bar)
Definition at line 712 of file gvc-channel-bar.c.
References FALSE, GVC_IS_CHANNEL_BAR, and _GvcChannelBar::priv.
gvc_channel_bar_get_show_marks()
gboolean gvc_channel_bar_get_show_marks (GvcChannelBar * bar)
Definition at line 690 of file gvc-channel-bar.c.
References FALSE, GVC_IS_CHANNEL_BAR, and _GvcChannelBar::priv.
gvc_channel_bar_get_show_mute()
gboolean gvc_channel_bar_get_show_mute (GvcChannelBar * bar)
Definition at line 668 of file gvc-channel-bar.c.
References FALSE, GVC_IS_CHANNEL_BAR, and _GvcChannelBar::priv.
gvc_channel_bar_new()
GtkWidget * gvc_channel_bar_new (MateMixerStreamControl * control)
Definition at line 1221 of file gvc-channel-bar.c.
References GVC_TYPE_CHANNEL_BAR, and NULL.
gvc_channel_bar_scroll()
gboolean gvc_channel_bar_scroll (GvcChannelBar * bar, GdkScrollDirection direction)
Definition at line 889 of file gvc-channel-bar.c.
References FALSE, GVC_IS_CHANNEL_BAR, MAX, MIN, _GvcChannelBar::priv, and TRUE.
gvc_channel_bar_set_control()
void gvc_channel_bar_set_control (GvcChannelBar * bar, MateMixerStreamControl * control)
Definition at line 570 of file gvc-channel-bar.c.
References GVC_IS_CHANNEL_BAR, mate_mixer_stream_control_get_flags(), MATE_MIXER_STREAM_CONTROL_MUTE_READABLE, MATE_MIXER_STREAM_CONTROL_NO_FLAGS, MATE_MIXER_STREAM_CONTROL_VOLUME_READABLE, NULL, and _GvcChannelBar::priv.
Referenced by gvc_stream_applet_icon_set_control(), and gvc_stream_status_icon_set_control().
gvc_channel_bar_set_extended()
void gvc_channel_bar_set_extended (GvcChannelBar * bar, gboolean extended)
Definition at line 742 of file gvc-channel-bar.c.
References GVC_IS_CHANNEL_BAR, _GvcChannelBar::priv, and PROP_EXTENDED.
gvc_channel_bar_set_high_icon_name()
void gvc_channel_bar_set_high_icon_name (GvcChannelBar * bar, const gchar * name)
Definition at line 877 of file gvc-channel-bar.c.
References GVC_IS_CHANNEL_BAR, name, _GvcChannelBar::priv, and PROP_HIGH_ICON_NAME.
gvc_channel_bar_set_icon_name()
void gvc_channel_bar_set_icon_name (GvcChannelBar * bar, const gchar * name)
Definition at line 799 of file gvc-channel-bar.c.
References error, GVC_IS_CHANNEL_BAR, name, NULL, _GvcChannelBar::priv, PROP_ICON_NAME, and TRUE.
gvc_channel_bar_set_low_icon_name()
void gvc_channel_bar_set_low_icon_name (GvcChannelBar * bar, const gchar * name)
Definition at line 854 of file gvc-channel-bar.c.
References GVC_IS_CHANNEL_BAR, name, _GvcChannelBar::priv, and PROP_LOW_ICON_NAME.
gvc_channel_bar_set_name()
void gvc_channel_bar_set_name (GvcChannelBar * bar, const gchar * name)
Definition at line 769 of file gvc-channel-bar.c.
References GVC_IS_CHANNEL_BAR, name, NULL, _GvcChannelBar::priv, and PROP_NAME.
gvc_channel_bar_set_orientation()
void gvc_channel_bar_set_orientation (GvcChannelBar * bar, GtkOrientation orientation)
Definition at line 624 of file gvc-channel-bar.c.
References GVC_IS_CHANNEL_BAR, _GvcChannelBar::priv, and PROP_ORIENTATION.
gvc_channel_bar_set_show_icons()
void gvc_channel_bar_set_show_icons (GvcChannelBar * bar, gboolean show_icons)
Definition at line 647 of file gvc-channel-bar.c.
References GVC_IS_CHANNEL_BAR, _GvcChannelBar::priv, PROP_SHOW_ICONS, and TRUE.
gvc_channel_bar_set_show_mark_text()
void gvc_channel_bar_set_show_mark_text (GvcChannelBar * bar, gboolean show_mark_text)
Definition at line 720 of file gvc-channel-bar.c.
References GVC_IS_CHANNEL_BAR, _GvcChannelBar::priv, and PROP_SHOW_MARK_TEXT.
gvc_channel_bar_set_show_marks()
void gvc_channel_bar_set_show_marks (GvcChannelBar * bar, gboolean show_marks)
Definition at line 698 of file gvc-channel-bar.c.
References GVC_IS_CHANNEL_BAR, _GvcChannelBar::priv, and PROP_SHOW_MARKS.
gvc_channel_bar_set_show_mute()
void gvc_channel_bar_set_show_mute (GvcChannelBar * bar, gboolean show_mute)
Definition at line 676 of file gvc-channel-bar.c.
References GVC_IS_CHANNEL_BAR, _GvcChannelBar::priv, and PROP_SHOW_MUTE.
gvc_channel_bar_set_size_group()
void gvc_channel_bar_set_size_group (GvcChannelBar * bar, GtkSizeGroup * group, gboolean symmetric)
Definition at line 947 of file gvc-channel-bar.c.
References GVC_IS_CHANNEL_BAR, NULL, and _GvcChannelBar::priv.