MATE Desktop Environment: hash.c File Reference
hash.c File Reference
#include <config.h>
#include "mdvi.h"
Functions
void mdvi_hash_init (DviHashTable *hash)
void mdvi_hash_create (DviHashTable *hash, int size)
int mdvi_hash_add (DviHashTable *hash, DviHashKey key, void *data, int rep)
void * mdvi_hash_lookup (DviHashTable *hash, DviHashKey key)
void * mdvi_hash_remove (DviHashTable *hash, DviHashKey key)
void * mdvi_hash_remove_ptr (DviHashTable *hash, DviHashKey key)
int mdvi_hash_destroy_key (DviHashTable *hash, DviHashKey key)
void mdvi_hash_reset (DviHashTable *hash, int reuse)
Function Documentation
mdvi_hash_add()
int mdvi_hash_add (DviHashTable * hash, DviHashKey key, void * data, int rep)
Definition at line 90 of file hash.c.
References data, hash, key, MDVI_HASH_UNCHECKED, MDVI_HASH_UNIQUE, NULL, and xalloc.
Referenced by __PROTO(), get_font_metrics(), mdvi_install_fontmap(), mdvi_ps_read_fontmap(), and mdvi_request_encoding().
mdvi_hash_create()
void mdvi_hash_create (DviHashTable * hash, int size)
Definition at line 62 of file hash.c.
References hash, NULL, and xnalloc.
Referenced by __PROTO(), get_font_metrics(), and ps_init_default_paths().
mdvi_hash_destroy_key()
int mdvi_hash_destroy_key (DviHashTable * hash, DviHashKey key)
Definition at line 191 of file hash.c.
References hash, key, mdvi_free(), and NULL.
Referenced by __PROTO().
mdvi_hash_init()
void mdvi_hash_init (DviHashTable * hash)
Definition at line 52 of file hash.c.
References hash, and NULL.
Referenced by __PROTO().
mdvi_hash_lookup()
void * mdvi_hash_lookup (DviHashTable * hash, DviHashKey key)
Definition at line 122 of file hash.c.
References hash, key, and NULL.
Referenced by __PROTO(), get_font_metrics(), mdvi_add_fontmap_file(), mdvi_encode_glyph(), mdvi_ps_find_font(), mdvi_ps_read_fontmap(), and mdvi_query_fontmap().
mdvi_hash_remove()
void * mdvi_hash_remove (DviHashTable * hash, DviHashKey key)
Definition at line 152 of file hash.c.
References data, hash, key, mdvi_free(), and NULL.
Referenced by __PROTO(), and mdvi_install_fontmap().
mdvi_hash_remove_ptr()
void * mdvi_hash_remove_ptr (DviHashTable * hash, DviHashKey key)
Definition at line 164 of file hash.c.
References hash, key, mdvi_free(), NULL, and ptr.
Referenced by __PROTO(), and free_font_metrics().
mdvi_hash_reset()
void mdvi_hash_reset (DviHashTable * hash, int reuse)
Definition at line 203 of file hash.c.
References hash, mdvi_free(), and NULL.
Referenced by __PROTO(), flush_font_metrics(), mdvi_flush_encodings(), mdvi_flush_fontmaps(), mdvi_ps_flush_fonts(), and mdvi_release_encoding().