MATE Desktop Environment: hash.h File Reference
hash.h File Reference
Classes
struct _DviHashTable
Macros
#define MDVI_KEY(x)
#define MDVI_EMPTY_HASH_TABLE {NULL, 0, 0, NULL, NULL, NULL}
#define MDVI_HASH_REPLACE 0
#define MDVI_HASH_UNIQUE 1
#define MDVI_HASH_UNCHECKED 2
#define mdvi_hash_flush(h)
#define mdvi_hash_destroy(h)
Typedefs
typedef struct _DviHashBucket DviHashBucket
typedef struct _DviHashTable DviHashTable
typedef Uchar * DviHashKey
typedef Ulong DviHashFunc __PROTO((DviHashKey key))
Functions
void mdvi_hash_init __PROTO ((DviHashTable *))
void mdvi_hash_create __PROTO ((DviHashTable *, int))
int mdvi_hash_add __PROTO ((DviHashTable *, DviHashKey, void *, int))
int mdvi_hash_destroy_key __PROTO ((DviHashTable *, DviHashKey))
Macro Definition Documentation
MDVI_EMPTY_HASH_TABLE
#define MDVI_EMPTY_HASH_TABLE {NULL, 0, 0, NULL, NULL, NULL}
Definition at line 28 of file hash.h.
mdvi_hash_destroy
#define mdvi_hash_destroy (h)
Value:
mdvi_hash_reset((h), 0)
Definition at line 44 of file hash.h.
mdvi_hash_flush
#define mdvi_hash_flush (h)
Value:
mdvi_hash_reset((h), 1)
Definition at line 43 of file hash.h.
MDVI_HASH_REPLACE
#define MDVI_HASH_REPLACE 0
Definition at line 30 of file hash.h.
Referenced by mdvi_request_encoding().
MDVI_HASH_UNCHECKED
#define MDVI_HASH_UNCHECKED 2
Definition at line 32 of file hash.h.
Referenced by get_font_metrics(), mdvi_hash_add(), mdvi_install_fontmap(), and mdvi_ps_read_fontmap().
MDVI_HASH_UNIQUE
#define MDVI_HASH_UNIQUE 1
Definition at line 31 of file hash.h.
Referenced by mdvi_hash_add().
MDVI_KEY
#define MDVI_KEY (x)
Value:
((DviHashKey)(x))
Definition at line 14 of file hash.h.
Referenced by free_font_metrics(), get_font_metrics(), mdvi_add_fontmap_file(), mdvi_encode_glyph(), mdvi_install_fontmap(), mdvi_ps_find_font(), mdvi_ps_read_fontmap(), mdvi_query_fontmap(), and mdvi_request_encoding().
Typedef Documentation
__PROTO
typedef void DviHashFree __PROTO((DviHashKey key, void *data))
Definition at line 16 of file hash.h.
DviHashBucket
typedef struct _DviHashBucket DviHashBucket
Definition at line 6 of file hash.h.
DviHashKey
typedef Uchar* DviHashKey
Definition at line 13 of file hash.h.
DviHashTable
typedef struct _DviHashTable DviHashTable
Definition at line 7 of file hash.h.
Function Documentation
__PROTO() [1/4]
void mdvi_hash_init __PROTO ((DviHashTable *)) extern
References mdvi_hash_init().
__PROTO() [2/4]
int mdvi_hash_destroy_key __PROTO ((DviHashTable *, DviHashKey)) extern
References mdvi_hash_destroy_key(), mdvi_hash_lookup(), mdvi_hash_remove(), mdvi_hash_remove_ptr(), and mdvi_hash_reset().
__PROTO() [3/4]
int mdvi_hash_add __PROTO ((DviHashTable *, DviHashKey, void *, int)) extern
References mdvi_hash_add().
__PROTO() [4/4]
void mdvi_hash_create __PROTO ((DviHashTable *, int)) extern
References mdvi_hash_create().