MATE Desktop Environment: iconcache.c File Reference
iconcache.c File Reference
#include <config.h>
#include "iconcache.h"
#include "ui.h"
#include "errors.h"
#include "window-private.h"
#include <X11/Xatom.h>
Functions
void meta_icon_cache_init (MetaIconCache *icon_cache)
void meta_icon_cache_free (MetaIconCache *icon_cache)
void meta_icon_cache_invalidate (MetaIconCache *icon_cache)
void meta_icon_cache_property_changed (MetaIconCache *icon_cache, MetaDisplay *display, Atom atom)
gboolean meta_icon_cache_get_icon_invalidated (MetaIconCache *icon_cache)
gboolean meta_read_icons (MetaScreen *screen, Window xwindow, char *desktop_id, MetaIconCache *icon_cache, Pixmap wm_hints_pixmap, Pixmap wm_hints_mask, GdkPixbuf **iconp, int ideal_width, int ideal_height, GdkPixbuf **mini_iconp, int ideal_mini_width, int ideal_mini_height)
Function Documentation
meta_icon_cache_free()
void meta_icon_cache_free (MetaIconCache * icon_cache)
Definition at line 565 of file iconcache.c.
References FALSE.
Referenced by meta_invalidate_default_icons().
meta_icon_cache_get_icon_invalidated()
gboolean meta_icon_cache_get_icon_invalidated (MetaIconCache * icon_cache)
Definition at line 597 of file iconcache.c.
References FALSE, _MetaIconCache::g_desktop_app_icon_dirty, _MetaIconCache::kwm_win_icon_dirty, _MetaIconCache::net_wm_icon_dirty, _MetaIconCache::origin, TRUE, USING_FALLBACK_ICON, USING_G_DESKTOP_APP, USING_KWM_WIN_ICON, USING_NET_WM_ICON, USING_NO_ICON, USING_WM_HINTS, _MetaIconCache::want_fallback, and _MetaIconCache::wm_hints_dirty.
Referenced by meta_read_icons().
meta_icon_cache_init()
void meta_icon_cache_init (MetaIconCache * icon_cache)
Definition at line 513 of file iconcache.c.
References _MetaIconCache::fallback_icon_dirty_forced, FALSE, _MetaIconCache::g_desktop_app_icon_dirty, _MetaIconCache::kwm_win_icon_dirty, _MetaIconCache::kwm_win_icon_dirty_forced, _MetaIconCache::net_wm_icon_dirty, NULL, _MetaIconCache::origin, _MetaIconCache::prev_mask, _MetaIconCache::prev_pixmap, TRUE, USING_NO_ICON, _MetaIconCache::want_fallback, _MetaIconCache::wm_hints_dirty, and _MetaIconCache::wm_hints_dirty_forced.
Referenced by meta_window_new_with_attrs().
meta_icon_cache_invalidate()
void meta_icon_cache_invalidate (MetaIconCache * icon_cache)
Definition at line 571 of file iconcache.c.
References _MetaIconCache::fallback_icon_dirty_forced, _MetaIconCache::g_desktop_app_icon_dirty, _MetaIconCache::kwm_win_icon_dirty, _MetaIconCache::kwm_win_icon_dirty_forced, _MetaIconCache::net_wm_icon_dirty, TRUE, _MetaIconCache::wm_hints_dirty, and _MetaIconCache::wm_hints_dirty_forced.
Referenced by meta_invalidate_all_icons().
meta_icon_cache_property_changed()
void meta_icon_cache_property_changed (MetaIconCache * icon_cache, MetaDisplay * display, Atom atom)
Definition at line 584 of file iconcache.c.
References _MetaIconCache::kwm_win_icon_dirty, _MetaIconCache::net_wm_icon_dirty, TRUE, and _MetaIconCache::wm_hints_dirty.
meta_read_icons()
gboolean meta_read_icons (MetaScreen * screen, Window xwindow, char * desktop_id, MetaIconCache * icon_cache, Pixmap wm_hints_pixmap, Pixmap wm_hints_mask, GdkPixbuf ** iconp, int ideal_width, int ideal_height, GdkPixbuf ** mini_iconp, int ideal_mini_width, int ideal_mini_height)
Definition at line 703 of file iconcache.c.
References _MetaIconCache::fallback_icon_dirty_forced, FALSE, _MetaIconCache::g_desktop_app_icon_dirty, _MetaIconCache::kwm_win_icon_dirty, _MetaIconCache::kwm_win_icon_dirty_forced, mask, meta_icon_cache_get_icon_invalidated(), meta_ui_get_mini_icon_from_desktop_id(), meta_ui_get_window_icon_from_desktop_id(), _MetaIconCache::net_wm_icon_dirty, NULL, _MetaIconCache::origin, _MetaIconCache::prev_mask, _MetaIconCache::prev_pixmap, TRUE, USING_FALLBACK_ICON, USING_G_DESKTOP_APP, USING_KWM_WIN_ICON, USING_NET_WM_ICON, USING_WM_HINTS, _MetaIconCache::want_fallback, _MetaIconCache::wm_hints_dirty, and _MetaIconCache::wm_hints_dirty_forced.
Referenced by meta_window_update_icon_now().