MATE Desktop Environment: ioapi.h File Reference
ioapi.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include "zlib.h"
Classes
struct zlib_filefunc_def_s
struct zlib_filefunc64_def_s
struct zlib_filefunc64_32_def_s
Macros
#define __USE_FILE_OFFSET64
#define __USE_LARGEFILE64
#define _LARGEFILE64_SOURCE
#define _FILE_OFFSET_BIT 64
#define MAXU32 0xffffffff
#define OF _Z_OF
#define ZLIB_FILEFUNC_SEEK_CUR (1)
#define ZLIB_FILEFUNC_SEEK_END (2)
#define ZLIB_FILEFUNC_SEEK_SET (0)
#define ZLIB_FILEFUNC_MODE_READ (1)
#define ZLIB_FILEFUNC_MODE_WRITE (2)
#define ZLIB_FILEFUNC_MODE_READWRITEFILTER (3)
#define ZLIB_FILEFUNC_MODE_EXISTING (4)
#define ZLIB_FILEFUNC_MODE_CREATE (8)
#define ZCALLBACK
#define ZREAD64(filefunc, filestream, buf, size)
#define ZWRITE64(filefunc, filestream, buf, size)
#define ZCLOSE64(filefunc, filestream)
#define ZERROR64(filefunc, filestream)
#define ZOPEN64(filefunc, filename, mode)
#define ZTELL64(filefunc, filestream)
#define ZSEEK64(filefunc, filestream, pos, mode)
Typedefs
typedef unsigned long long int ZPOS64_T
typedef const char * filename
typedef const char int mode
typedef voidpf stream
typedef voidpf void * buf
typedef voidpf void uLong size
typedef voidpf uLong offset
typedef voidpf uLong int origin
typedef struct zlib_filefunc_def_s zlib_filefunc_def
typedef struct zlib_filefunc64_def_s zlib_filefunc64_def
typedef struct zlib_filefunc64_32_def_s zlib_filefunc64_32_def
Functions
typedef voidpf (ZCALLBACK *open_file_func) OF((voidpf opaque
typedef uLong (ZCALLBACK *read_file_func) OF((voidpf opaque
typedef int (ZCALLBACK *close_file_func) OF((voidpf opaque
typedef long (ZCALLBACK *tell_file_func) OF((voidpf opaque
typedef ZPOS64_T (ZCALLBACK *tell64_file_func) OF((voidpf opaque
void fill_fopen64_filefunc OF ((zlib_filefunc64_def *pzlib_filefunc_def))
void fill_fopen_filefunc OF ((zlib_filefunc_def *pzlib_filefunc_def))
voidpf call_zopen64 OF ((const zlib_filefunc64_32_def *pfilefunc, const void *filename, int mode))
long call_zseek64 OF ((const zlib_filefunc64_32_def *pfilefunc, voidpf filestream, ZPOS64_T offset, int origin))
ZPOS64_T call_ztell64 OF ((const zlib_filefunc64_32_def *pfilefunc, voidpf filestream))
void fill_zlib_filefunc64_32_def_from_filefunc32 (zlib_filefunc64_32_def *p_filefunc64_32, const zlib_filefunc_def *p_filefunc32)
Macro Definition Documentation
__USE_FILE_OFFSET64
#define __USE_FILE_OFFSET64
Definition at line 30 of file ioapi.h.
__USE_LARGEFILE64
#define __USE_LARGEFILE64
Definition at line 33 of file ioapi.h.
_FILE_OFFSET_BIT
#define _FILE_OFFSET_BIT 64
Definition at line 39 of file ioapi.h.
_LARGEFILE64_SOURCE
#define _LARGEFILE64_SOURCE
Definition at line 36 of file ioapi.h.
MAXU32
#define MAXU32 0xffffffff
Definition at line 95 of file ioapi.h.
Referenced by call_ztell64(), and unz64local_GetCurrentFileInfoInternal().
OF
#define OF _Z_OF
Definition at line 106 of file ioapi.h.
ZCALLBACK
#define ZCALLBACK
Definition at line 128 of file ioapi.h.
Referenced by int(), long(), and ZPOS64_T().
ZCLOSE64
#define ZCLOSE64 (filefunc, filestream)
Value:
((*((filefunc).zfile_func64.zclose_file))  ((filefunc).zfile_func64.opaque,filestream))
Definition at line 186 of file ioapi.h.
Referenced by unzClose(), and unzOpenInternal().
ZERROR64
#define ZERROR64 (filefunc, filestream)
Value:
((*((filefunc).zfile_func64.zerror_file))  ((filefunc).zfile_func64.opaque,filestream))
Definition at line 187 of file ioapi.h.
Referenced by unz64local_getByte().
ZLIB_FILEFUNC_MODE_CREATE
#define ZLIB_FILEFUNC_MODE_CREATE (8)
Definition at line 122 of file ioapi.h.
ZLIB_FILEFUNC_MODE_EXISTING
#define ZLIB_FILEFUNC_MODE_EXISTING (4)
Definition at line 121 of file ioapi.h.
Referenced by unzOpenInternal().
ZLIB_FILEFUNC_MODE_READ
#define ZLIB_FILEFUNC_MODE_READ (1)
Definition at line 117 of file ioapi.h.
Referenced by unzOpenInternal().
ZLIB_FILEFUNC_MODE_READWRITEFILTER
#define ZLIB_FILEFUNC_MODE_READWRITEFILTER (3)
Definition at line 119 of file ioapi.h.
ZLIB_FILEFUNC_MODE_WRITE
#define ZLIB_FILEFUNC_MODE_WRITE (2)
Definition at line 118 of file ioapi.h.
ZLIB_FILEFUNC_SEEK_CUR
#define ZLIB_FILEFUNC_SEEK_CUR (1)
Definition at line 113 of file ioapi.h.
Referenced by unz64local_GetCurrentFileInfoInternal().
ZLIB_FILEFUNC_SEEK_END
#define ZLIB_FILEFUNC_SEEK_END (2)
Definition at line 114 of file ioapi.h.
Referenced by unz64local_SearchCentralDir(), and unz64local_SearchCentralDir64().
ZLIB_FILEFUNC_SEEK_SET
#define ZLIB_FILEFUNC_SEEK_SET (0)
Definition at line 115 of file ioapi.h.
Referenced by unz64local_CheckCurrentFileCoherencyHeader(), unz64local_GetCurrentFileInfoInternal(), unz64local_SearchCentralDir(), unz64local_SearchCentralDir64(), unzGetGlobalComment(), unzGetLocalExtrafield(), unzOpenInternal(), and unzReadCurrentFile().
ZOPEN64
#define ZOPEN64 (filefunc, filename, mode)
Value:
(call_zopen64((&(filefunc)),(filename),(mode)))
Definition at line 195 of file ioapi.h.
Referenced by unzOpenInternal().
ZREAD64
#define ZREAD64 (filefunc, filestream, buf, size)
Value:
((*((filefunc).zfile_func64.zread_file))   ((filefunc).zfile_func64.opaque,filestream,buf,size))
Definition at line 182 of file ioapi.h.
Referenced by unz64local_getByte(), unz64local_GetCurrentFileInfoInternal(), unz64local_SearchCentralDir(), unz64local_SearchCentralDir64(), unzGetGlobalComment(), unzGetLocalExtrafield(), unzOpenCurrentFile3(), and unzReadCurrentFile().
ZSEEK64
#define ZSEEK64 (filefunc, filestream, pos, mode)
Value:
(call_zseek64((&(filefunc)),(filestream),(pos),(mode)))
Definition at line 197 of file ioapi.h.
Referenced by unz64local_CheckCurrentFileCoherencyHeader(), unz64local_GetCurrentFileInfoInternal(), unz64local_SearchCentralDir(), unz64local_SearchCentralDir64(), unzGetGlobalComment(), unzGetLocalExtrafield(), unzOpenCurrentFile3(), unzOpenInternal(), and unzReadCurrentFile().
ZTELL64
#define ZTELL64 (filefunc, filestream)
Value:
(call_ztell64((&(filefunc)),(filestream)))
Definition at line 196 of file ioapi.h.
Referenced by unz64local_SearchCentralDir(), and unz64local_SearchCentralDir64().
ZWRITE64
#define ZWRITE64 (filefunc, filestream, buf, size)
Value:
((*((filefunc).zfile_func64.zwrite_file))  ((filefunc).zfile_func64.opaque,filestream,buf,size))
Definition at line 183 of file ioapi.h.
Typedef Documentation
buf
typedef voidpf const void * buf
Definition at line 133 of file ioapi.h.
filename
typedef const void * filename
Definition at line 132 of file ioapi.h.
mode
typedef const void int mode
Definition at line 132 of file ioapi.h.
offset
typedef voidpf ZPOS64_T offset
Definition at line 139 of file ioapi.h.
origin
typedef voidpf ZPOS64_T int origin
Definition at line 139 of file ioapi.h.
size
typedef voidpf const void uLong size
Definition at line 133 of file ioapi.h.
stream
typedef voidpf stream
Definition at line 133 of file ioapi.h.
zlib_filefunc64_32_def
typedef struct zlib_filefunc64_32_def_s zlib_filefunc64_32_def
zlib_filefunc64_def
typedef struct zlib_filefunc64_def_s zlib_filefunc64_def
zlib_filefunc_def
typedef struct zlib_filefunc_def_s zlib_filefunc_def
ZPOS64_T
typedef unsigned long long int ZPOS64_T
Definition at line 100 of file ioapi.h.
Function Documentation
fill_zlib_filefunc64_32_def_from_filefunc32()
void fill_zlib_filefunc64_32_def_from_filefunc32 (zlib_filefunc64_32_def * p_filefunc64_32, const zlib_filefunc_def * p_filefunc32)
Definition at line 68 of file ioapi.c.
References NULL, zlib_filefunc64_def_s::opaque, zlib_filefunc_def_s::opaque, zlib_filefunc64_def_s::zclose_file, zlib_filefunc_def_s::zclose_file, zlib_filefunc64_def_s::zerror_file, zlib_filefunc_def_s::zerror_file, zlib_filefunc64_32_def_s::zfile_func64, zlib_filefunc64_32_def_s::zopen32_file, zlib_filefunc64_def_s::zopen64_file, zlib_filefunc_def_s::zopen_file, zlib_filefunc64_def_s::zread_file, zlib_filefunc_def_s::zread_file, zlib_filefunc64_32_def_s::zseek32_file, zlib_filefunc64_def_s::zseek64_file, zlib_filefunc_def_s::zseek_file, zlib_filefunc64_32_def_s::ztell32_file, zlib_filefunc64_def_s::ztell64_file, zlib_filefunc_def_s::ztell_file, zlib_filefunc64_def_s::zwrite_file, and zlib_filefunc_def_s::zwrite_file.
Referenced by unzOpen2().
int()
typedef int (ZCALLBACK * close_file_func)
References voidpf(), and ZCALLBACK.
Referenced by baobab_chart_get_item_color(), caja_icon_canvas_item_get_bounds_for_entire_item(), caja_icon_canvas_item_get_bounds_for_layout(), caja_icon_container_widget_to_file_operation_position(), caja_module_list_types(), eel_gradient_parse_one_color_spec(), eel_gtk_widget_get_dimensions(), eel_labeled_image_get_image_bounds(), eel_stop_in_debugger(), eom_save_as_dialog_new(), G_DECLARE_DERIVABLE_TYPE(), G_DEFINE_TYPE_WITH_PRIVATE(), gpm_get_timestring(), make_display_name(), mate_theme_read_meta_theme(), mdvi_shrink_box(), mdvi_shrink_glyph(), mdvi_shrink_glyph_grey(), mdvi_sort_pages(), meta_frame_layout_calc_geometry(), meta_prefs_get_key_bindings(), meta_theme_validate(), meta_window_get_current_tile_area(), meta_window_menu_new(), read_bcpl(), stickynotes_applet_init(), tfm_load_file(), unz64local_getByte(), and unzOpenCurrentFile3().
long()
typedef long (ZCALLBACK * tell_file_func)
References voidpf(), and ZCALLBACK.
Referenced by meta_gradient_create_interwoven(), and msgetn().
OF() [1/5]
voidpf call_zopen64 OF ((const zlib_filefunc64_32_def *pfilefunc, const void *filename, int mode))
References call_zopen64(), and voidpf().
OF() [2/5]
ZPOS64_T call_ztell64 OF ((const zlib_filefunc64_32_def *pfilefunc, voidpf filestream))
References call_ztell64(), and voidpf().
OF() [3/5]
long call_zseek64 OF ((const zlib_filefunc64_32_def *pfilefunc, voidpf filestream, ZPOS64_T offset, int origin))
References call_zseek64(), and voidpf().
OF() [4/5]
void fill_fopen64_filefunc OF ((zlib_filefunc64_def *pzlib_filefunc_def))
References fill_fopen64_filefunc().
OF() [5/5]
void fill_fopen_filefunc OF ((zlib_filefunc_def *pzlib_filefunc_def))
References fill_fopen_filefunc().
uLong()
typedef uLong (ZCALLBACK * read_file_func)
Referenced by call_zseek64(), call_ztell64(), OF(), OF(), OF(), OF(), OF(), OF(), unz64local_CheckCurrentFileCoherencyHeader(), unz64local_GetCurrentFileInfoInternal(), unz64local_getLong(), unz64local_getShort(), unz64local_SearchCentralDir(), unz64local_SearchCentralDir64(), unzGetCurrentFileInfo(), unzGetCurrentFileInfo64(), unzGetFilePos(), unzGetGlobalComment(), unzGetGlobalInfo(), unzGetOffset(), unzOpenInternal(), unzReadCurrentFile(), and unzSetOffset().
voidpf()
typedef voidpf (ZCALLBACK * open_file_func)
Referenced by call_zopen64(), call_zseek64(), call_ztell64(), int(), long(), OF(), OF(), OF(), OF(), OF(), OF(), OF(), unz64local_getByte(), unz64local_getLong(), unz64local_getLong64(), unz64local_getShort(), unz64local_SearchCentralDir(), unz64local_SearchCentralDir64(), unzOpenCurrentFile3(), and ZPOS64_T().
ZPOS64_T()
typedef ZPOS64_T (ZCALLBACK * tell64_file_func)
References voidpf(), and ZCALLBACK.