MATE Desktop Environment: ioapi.c File Reference
ioapi.c File Reference
#include "ioapi.h"
Macros
#define FOPEN_FUNC(filename, mode)
#define FTELLO_FUNC(stream)
#define FSEEKO_FUNC(stream, offset, origin)
Functions
voidpf call_zopen64 (const zlib_filefunc64_32_def *pfilefunc, const void *filename, int mode)
long call_zseek64 (const zlib_filefunc64_32_def *pfilefunc, voidpf filestream, ZPOS64_T offset, int origin)
ZPOS64_T call_ztell64 (const zlib_filefunc64_32_def *pfilefunc, voidpf filestream)
void fill_zlib_filefunc64_32_def_from_filefunc32 (zlib_filefunc64_32_def *p_filefunc64_32, const zlib_filefunc_def *p_filefunc32)
void fill_fopen_filefunc (zlib_filefunc_def *pzlib_filefunc_def)
void fill_fopen64_filefunc (zlib_filefunc64_def *pzlib_filefunc_def)
Macro Definition Documentation
FOPEN_FUNC
#define FOPEN_FUNC (filename, mode)
Value:
fopen64(filename, mode)
Definition at line 23 of file ioapi.c.
FSEEKO_FUNC
#define FSEEKO_FUNC (stream, offset, origin)
Value:
fseeko64(stream, offset, origin)
Definition at line 25 of file ioapi.c.
FTELLO_FUNC
#define FTELLO_FUNC (stream)
Value:
ftello64(stream)
Definition at line 24 of file ioapi.c.
Function Documentation
call_zopen64()
voidpf call_zopen64 (const zlib_filefunc64_32_def * pfilefunc, const void * filename, int mode)
Definition at line 30 of file ioapi.c.
References NULL, zlib_filefunc64_def_s::opaque, voidpf(), zlib_filefunc64_32_def_s::zfile_func64, zlib_filefunc64_32_def_s::zopen32_file, and zlib_filefunc64_def_s::zopen64_file.
Referenced by OF().
call_zseek64()
long call_zseek64 (const zlib_filefunc64_32_def * pfilefunc, voidpf filestream, ZPOS64_T offset, int origin)
Definition at line 40 of file ioapi.c.
References NULL, zlib_filefunc64_def_s::opaque, uLong(), voidpf(), zlib_filefunc64_32_def_s::zfile_func64, zlib_filefunc64_32_def_s::zseek32_file, and zlib_filefunc64_def_s::zseek64_file.
Referenced by OF().
call_ztell64()
ZPOS64_T call_ztell64 (const zlib_filefunc64_32_def * pfilefunc, voidpf filestream)
Definition at line 54 of file ioapi.c.
References MAXU32, NULL, zlib_filefunc64_def_s::opaque, uLong(), voidpf(), zlib_filefunc64_32_def_s::zfile_func64, zlib_filefunc64_def_s::zseek64_file, zlib_filefunc64_32_def_s::ztell32_file, and zlib_filefunc64_def_s::ztell64_file.
Referenced by OF().
fill_fopen64_filefunc()
void fill_fopen64_filefunc (zlib_filefunc64_def * pzlib_filefunc_def)
Definition at line 231 of file ioapi.c.
References NULL, zlib_filefunc64_def_s::opaque, zlib_filefunc64_def_s::zclose_file, zlib_filefunc64_def_s::zerror_file, zlib_filefunc64_def_s::zopen64_file, zlib_filefunc64_def_s::zread_file, zlib_filefunc64_def_s::zseek64_file, zlib_filefunc64_def_s::ztell64_file, and zlib_filefunc64_def_s::zwrite_file.
Referenced by OF(), and unzOpenInternal().
fill_fopen_filefunc()
void fill_fopen_filefunc (zlib_filefunc_def* pzlib_filefunc_def)
Definition at line 218 of file ioapi.c.
References NULL.
Referenced by OF().
fill_zlib_filefunc64_32_def_from_filefunc32()
void fill_zlib_filefunc64_32_def_from_filefunc32 (zlib_filefunc64_32_def * p_filefunc64_32, const zlib_filefunc_def * p_filefunc32)
Definition at line 68 of file ioapi.c.
References NULL, zlib_filefunc64_def_s::opaque, zlib_filefunc_def_s::opaque, zlib_filefunc64_def_s::zclose_file, zlib_filefunc_def_s::zclose_file, zlib_filefunc64_def_s::zerror_file, zlib_filefunc_def_s::zerror_file, zlib_filefunc64_32_def_s::zfile_func64, zlib_filefunc64_32_def_s::zopen32_file, zlib_filefunc64_def_s::zopen64_file, zlib_filefunc_def_s::zopen_file, zlib_filefunc64_def_s::zread_file, zlib_filefunc_def_s::zread_file, zlib_filefunc64_32_def_s::zseek32_file, zlib_filefunc64_def_s::zseek64_file, zlib_filefunc_def_s::zseek_file, zlib_filefunc64_32_def_s::ztell32_file, zlib_filefunc64_def_s::ztell64_file, zlib_filefunc_def_s::ztell_file, zlib_filefunc64_def_s::zwrite_file, and zlib_filefunc_def_s::zwrite_file.
Referenced by unzOpen2().