MATE Desktop Environment: keybindings.h File Reference
keybindings.h File Reference
#include "display-private.h"
#include "window.h"
Macros
#define ARROW_LEFT 113
#define ARROW_LEFT_PAD 83
#define ARROW_RIGHT 114
#define ARROW_RIGHT_PAD 85
#define ARROW_UP 111
#define ARROW_UP_PAD 80
#define ARROW_DOWN 116
#define ARROW_DOWN_PAD 88
Functions
void meta_display_init_keys (MetaDisplay *display)
void meta_display_shutdown_keys (MetaDisplay *display)
void meta_screen_grab_keys (MetaScreen *screen)
void meta_screen_ungrab_keys (MetaScreen *screen)
gboolean meta_screen_grab_all_keys (MetaScreen *screen, guint32 timestamp)
void meta_screen_ungrab_all_keys (MetaScreen *screen, guint32 timestamp)
void meta_window_grab_keys (MetaWindow *window)
void meta_window_ungrab_keys (MetaWindow *window)
gboolean meta_window_grab_all_keys (MetaWindow *window, guint32 timestamp)
void meta_window_ungrab_all_keys (MetaWindow *window, guint32 timestamp)
void meta_display_process_key_event (MetaDisplay *display, MetaWindow *window, XEvent *event)
void meta_set_keybindings_disabled (gboolean setting)
void meta_display_process_mapping_event (MetaDisplay *display, XEvent *event)
Detailed Description
Grab and ungrab keys, and process the key events
Performs global X grabs on the keys we need to be told about, like the one to close a window. It also deals with incoming key events.
Definition in file keybindings.h.
Macro Definition Documentation
ARROW_DOWN
#define ARROW_DOWN 116
Definition at line 41 of file keybindings.h.
ARROW_DOWN_PAD
#define ARROW_DOWN_PAD 88
Definition at line 42 of file keybindings.h.
ARROW_LEFT
#define ARROW_LEFT 113
Definition at line 32 of file keybindings.h.
ARROW_LEFT_PAD
#define ARROW_LEFT_PAD 83
Definition at line 33 of file keybindings.h.
ARROW_RIGHT
#define ARROW_RIGHT 114
Definition at line 35 of file keybindings.h.
ARROW_RIGHT_PAD
#define ARROW_RIGHT_PAD 85
Definition at line 36 of file keybindings.h.
ARROW_UP
#define ARROW_UP 111
Definition at line 38 of file keybindings.h.
ARROW_UP_PAD
#define ARROW_UP_PAD 80
Definition at line 39 of file keybindings.h.
Function Documentation
meta_display_init_keys()
void meta_display_init_keys (MetaDisplay * display)
Definition at line 588 of file keybindings.c.
References _MetaDisplay::hyper_mask, _MetaDisplay::ignored_modifier_mask, _MetaDisplay::key_bindings, _MetaDisplay::keymap, _MetaDisplay::keysyms_per_keycode, _MetaDisplay::max_keycode, META_DEBUG_KEYBINDINGS, _MetaDisplay::meta_mask, meta_prefs_add_listener(), _MetaDisplay::min_keycode, _MetaDisplay::modmap, _MetaDisplay::n_key_bindings, NULL, _MetaDisplay::num_lock_mask, _MetaDisplay::scroll_lock_mask, _MetaDisplay::super_mask, and _MetaDisplay::xdisplay.
meta_display_process_key_event()
void meta_display_process_key_event (MetaDisplay * display, MetaWindow * window, XEvent * event)
Definition at line 1280 of file keybindings.c.
References _MetaDisplay::grab_op, _MetaDisplay::grab_screen, _MetaDisplay::grab_window, _MetaDisplay::key_bindings, META_DEBUG_KEYBINDINGS, meta_display_end_grab_op(), meta_display_lookup_x_window(), meta_display_screen_for_root(), meta_display_screen_for_xwindow(), META_GRAB_OP_KEYBOARD_ESCAPING_DOCK, META_GRAB_OP_KEYBOARD_ESCAPING_GROUP, META_GRAB_OP_KEYBOARD_ESCAPING_NORMAL, META_GRAB_OP_KEYBOARD_ESCAPING_NORMAL_ALL_WORKSPACES, META_GRAB_OP_KEYBOARD_MOVING, META_GRAB_OP_KEYBOARD_RESIZING_E, META_GRAB_OP_KEYBOARD_RESIZING_N, META_GRAB_OP_KEYBOARD_RESIZING_NE, META_GRAB_OP_KEYBOARD_RESIZING_NW, META_GRAB_OP_KEYBOARD_RESIZING_S, META_GRAB_OP_KEYBOARD_RESIZING_SE, META_GRAB_OP_KEYBOARD_RESIZING_SW, META_GRAB_OP_KEYBOARD_RESIZING_UNKNOWN, META_GRAB_OP_KEYBOARD_RESIZING_W, META_GRAB_OP_KEYBOARD_TABBING_DOCK, META_GRAB_OP_KEYBOARD_TABBING_GROUP, META_GRAB_OP_KEYBOARD_TABBING_NORMAL, META_GRAB_OP_KEYBOARD_TABBING_NORMAL_ALL_WORKSPACES, META_GRAB_OP_KEYBOARD_WORKSPACE_MOVING, META_GRAB_OP_KEYBOARD_WORKSPACE_SWITCHING, META_GRAB_OP_MOVING, META_GRAB_OP_NONE, META_GRAB_OP_RESIZING_E, META_GRAB_OP_RESIZING_N, META_GRAB_OP_RESIZING_NE, META_GRAB_OP_RESIZING_NW, META_GRAB_OP_RESIZING_S, META_GRAB_OP_RESIZING_SE, META_GRAB_OP_RESIZING_SW, META_GRAB_OP_RESIZING_W, meta_ui_window_is_widget(), _MetaDisplay::n_key_bindings, NULL, TRUE, and _MetaDisplay::xdisplay.
meta_display_process_mapping_event()
void meta_display_process_mapping_event (MetaDisplay * display, XEvent * event)
Definition at line 513 of file keybindings.c.
References FALSE, META_DEBUG_KEYBINDINGS, and TRUE.
meta_display_shutdown_keys()
void meta_display_shutdown_keys (MetaDisplay * display)
Definition at line 636 of file keybindings.c.
References _MetaDisplay::key_bindings, _MetaDisplay::keymap, meta_prefs_remove_listener(), meta_XFree, and _MetaDisplay::modmap.
Referenced by meta_display_close().
meta_screen_grab_all_keys()
gboolean meta_screen_grab_all_keys (MetaScreen * screen, guint32 timestamp)
Definition at line 958 of file keybindings.c.
References FALSE, META_DEBUG_KEYBINDINGS, meta_screen_grab_keys(), meta_screen_ungrab_keys(), and TRUE.
Referenced by meta_display_begin_grab_op().
meta_screen_grab_keys()
void meta_screen_grab_keys (MetaScreen * screen)
Definition at line 802 of file keybindings.c.
References FALSE, and TRUE.
Referenced by meta_screen_grab_all_keys(), meta_screen_new(), and meta_screen_ungrab_all_keys().
meta_screen_ungrab_all_keys()
void meta_screen_ungrab_all_keys (MetaScreen * screen, guint32 timestamp)
Definition at line 980 of file keybindings.c.
References FALSE, and meta_screen_grab_keys().
Referenced by meta_display_end_grab_op().
meta_screen_ungrab_keys()
void meta_screen_ungrab_keys (MetaScreen * screen)
Definition at line 819 of file keybindings.c.
References FALSE.
Referenced by meta_screen_free(), and meta_screen_grab_all_keys().
meta_set_keybindings_disabled()
void meta_set_keybindings_disabled (gboolean setting)
Definition at line 3605 of file keybindings.c.
References META_DEBUG_KEYBINDINGS.
Referenced by main().
meta_window_grab_all_keys()
gboolean meta_window_grab_all_keys (MetaWindow * window, guint32 timestamp)
Definition at line 995 of file keybindings.c.
References FALSE, META_DEBUG_FOCUS, META_DEBUG_KEYBINDINGS, meta_window_focus(), meta_window_ungrab_keys(), NULL, and TRUE.
Referenced by meta_display_begin_grab_op().
meta_window_grab_keys()
void meta_window_grab_keys (MetaWindow * window)
Definition at line 829 of file keybindings.c.
References FALSE, META_WINDOW_DOCK, NULL, and TRUE.
Referenced by meta_window_destroy_frame(), meta_window_ensure_frame(), meta_window_new_with_attrs(), and meta_window_ungrab_all_keys().
meta_window_ungrab_all_keys()
void meta_window_ungrab_all_keys (MetaWindow * window, guint32 timestamp)
Definition at line 1031 of file keybindings.c.
References FALSE, and meta_window_grab_keys().
Referenced by meta_display_end_grab_op().
meta_window_ungrab_keys()
void meta_window_ungrab_keys (MetaWindow * window)
Definition at line 864 of file keybindings.c.
References FALSE, and NULL.
Referenced by meta_window_free(), and meta_window_grab_all_keys().