MATE Desktop Environment: linux-proc.c File Reference
linux-proc.c File Reference
#include <config.h>
#include <sys/types.h>
#include <sys/statvfs.h>
#include <fcntl.h>
#include <unistd.h>
#include <glibtop.h>
#include <glibtop/cpu.h>
#include <glibtop/mem.h>
#include <glibtop/swap.h>
#include <glibtop/loadavg.h>
#include <glibtop/netload.h>
#include <glibtop/netlist.h>
#include <glibtop/mountlist.h>
#include <glibtop/fsusage.h>
#include "linux-proc.h"
#include "autoscaler.h"
Functions
void GetLoad (guint64 Maximum, guint64 data[cpuload_n], LoadGraph *g)
void GetDiskLoad (guint64 Maximum, guint64 data[diskload_n], LoadGraph *g)
void GetMemory (guint64 Maximum, guint64 data[memload_n], LoadGraph *g)
void GetSwap (guint64 Maximum, guint64 data[swapload_n], LoadGraph *g)
void GetLoadAvg (guint64 Maximum, guint64 data[2], LoadGraph *g)
void GetNet (guint64 Maximum, guint64 data[4], LoadGraph *g)
Function Documentation
GetDiskLoad()
void GetDiskLoad (guint64 Maximum, guint64 data[diskload_n], LoadGraph * g)
Definition at line 95 of file linux-proc.c.
References autoscaler_get_max(), autoscaler_init(), data, diskload_free, diskload_n, diskload_read, _MultiloadApplet::diskload_used_ratio, diskload_write, FALSE, NULL, _MultiloadApplet::nvme_diskstats, _MultiloadApplet::settings, LoadGraph::speed, and TRUE.
GetLoad()
void GetLoad (guint64 Maximum, guint64 data[cpuload_n], LoadGraph * g)
Definition at line 49 of file linux-proc.c.
References _MultiloadApplet::cpu_initialized, _MultiloadApplet::cpu_last, _MultiloadApplet::cpu_time, _MultiloadApplet::cpu_used_ratio, cpuload_free, cpuload_iowait, cpuload_n, cpuload_nice, cpuload_sys, cpuload_usr, data, memcpy, and TRUE.
GetLoadAvg()
void GetLoadAvg (guint64 Maximum, guint64 data[2], LoadGraph * g)
Definition at line 292 of file linux-proc.c.
References data, and _MultiloadApplet::loadavg1.
GetMemory()
void GetMemory (guint64 Maximum, guint64 data[memload_n], LoadGraph * g)
Definition at line 221 of file linux-proc.c.
References data, MAX, memload_buffer, _MultiloadApplet::memload_cache, memload_cached, memload_free, memload_n, memload_shared, _MultiloadApplet::memload_total, _MultiloadApplet::memload_user, and memload_user.
GetNet()
void GetNet (guint64 Maximum, guint64 data[4], LoadGraph * g)
Definition at line 352 of file linux-proc.c.
References data, devices, memcpy, netspeed_add(), _MultiloadApplet::netspeed_in, _MultiloadApplet::netspeed_out, and LoadGraph::speed.
GetSwap()
void GetSwap (guint64 Maximum, guint64 data[swapload_n], LoadGraph * g)
Definition at line 262 of file linux-proc.c.
References data, swapload_n, and _MultiloadApplet::swapload_used_ratio.