MATE Desktop Environment: logview-log.c File Reference
logview-log.c File Reference
#include <glib.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include "logview-log.h"
#include "logview-utils.h"
Enumerations
enum { LOG_CHANGED , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (LogviewLog, logview_log, G_TYPE_OBJECT)
void logview_log_read_new_lines (LogviewLog *log, GCancellable *cancellable, LogviewNewLinesCallback callback, gpointer user_data)
void logview_log_create (const char *filename, LogviewCreateCallback callback, gpointer user_data)
void logview_log_create_from_gfile (GFile *file, LogviewCreateCallback callback, gpointer user_data)
const char * logview_log_get_display_name (LogviewLog *log)
time_t logview_log_get_timestamp (LogviewLog *log)
goffset logview_log_get_file_size (LogviewLog *log)
guint logview_log_get_cached_lines_number (LogviewLog *log)
const char ** logview_log_get_cached_lines (LogviewLog *log)
GSList * logview_log_get_days_for_cached_lines (LogviewLog *log)
gboolean logview_log_has_new_lines (LogviewLog *log)
char * logview_log_get_uri (LogviewLog *log)
GFile * logview_log_get_gfile (LogviewLog *log)
gboolean logview_log_get_has_days (LogviewLog *log)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
LOG_CHANGED
LAST_SIGNAL
Definition at line 37 of file logview-log.c.
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (LogviewLog , logview_log , G_TYPE_OBJECT)
References NULL.
logview_log_create()
void logview_log_create (const char * filename, LogviewCreateCallback callback, gpointer user_data)
Definition at line 821 of file logview-log.c.
References LOGVIEW_TYPE_LOG, NULL, _LogviewLog::priv, and user_data.
Referenced by main().
logview_log_create_from_gfile()
void logview_log_create_from_gfile (GFile * file, LogviewCreateCallback callback, gpointer user_data)
Definition at line 832 of file logview-log.c.
References LOGVIEW_TYPE_LOG, NULL, _LogviewLog::priv, and user_data.
logview_log_get_cached_lines()
const char ** logview_log_get_cached_lines (LogviewLog * log)
Definition at line 875 of file logview-log.c.
References LOGVIEW_IS_LOG, NULL, and _LogviewLog::priv.
logview_log_get_cached_lines_number()
guint logview_log_get_cached_lines_number (LogviewLog * log)
Definition at line 867 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
logview_log_get_days_for_cached_lines()
GSList * logview_log_get_days_for_cached_lines (LogviewLog * log)
Definition at line 889 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
Referenced by logview_loglist_update_lines().
logview_log_get_display_name()
const char * logview_log_get_display_name (LogviewLog * log)
Definition at line 843 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
logview_log_get_file_size()
goffset logview_log_get_file_size (LogviewLog * log)
Definition at line 859 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
logview_log_get_gfile()
GFile * logview_log_get_gfile (LogviewLog * log)
Definition at line 913 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
Referenced by logview_manager_close_active_log(), and logview_manager_set_active_log().
logview_log_get_has_days()
gboolean logview_log_get_has_days (LogviewLog * log)
Definition at line 921 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
logview_log_get_timestamp()
time_t logview_log_get_timestamp (LogviewLog * log)
Definition at line 851 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
logview_log_get_uri()
char * logview_log_get_uri (LogviewLog * log)
Definition at line 905 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
Referenced by logview_manager_close_active_log().
logview_log_has_new_lines()
gboolean logview_log_has_new_lines (LogviewLog * log)
Definition at line 897 of file logview-log.c.
References LOGVIEW_IS_LOG, and _LogviewLog::priv.
logview_log_read_new_lines()
void logview_log_read_new_lines (LogviewLog * log, GCancellable * cancellable, LogviewNewLinesCallback callback, gpointer user_data)
Definition at line 798 of file logview-log.c.
References NULL, and user_data.