MATE Desktop Environment: logview-prefs.c File Reference
logview-prefs.c File Reference
#include <sys/stat.h>
#include <string.h>
#include <gtk/gtk.h>
#include "logview-prefs.h"
Macros
#define LOGVIEW_DEFAULT_HEIGHT 400
#define LOGVIEW_DEFAULT_WIDTH 600
#define LOGVIEW_SCHEMA "org.mate.system-log"
#define PREF_WIDTH "width"
#define PREF_HEIGHT "height"
#define PREF_LOGFILE "logfile"
#define PREF_LOGFILES "logfiles"
#define PREF_FONTSIZE "fontsize"
#define PREF_FILTERS "filters"
#define MATE_MONOSPACE_FONT_NAME "monospace-font-name"
#define MATE_MENUS_HAVE_TEAROFF "menus-have-tearoff"
#define DELIMITER ":"
Enumerations
enum { SYSTEM_FONT_CHANGED , HAVE_TEAROFF_CHANGED , LAST_SIGNAL }
enum {
FILTER_NAME , FILTER_INVISIBLE , FILTER_FOREGROUND , FILTER_BACKGROUND ,
FILTER_REGEX , MAX_TOKENS
}
Functions
G_DEFINE_TYPE_WITH_PRIVATE (LogviewPrefs, logview_prefs, G_TYPE_OBJECT)
LogviewPrefs * logview_prefs_get ()
void logview_prefs_store_window_size (LogviewPrefs *prefs, int width, int height)
void logview_prefs_get_stored_window_size (LogviewPrefs *prefs, int *width, int *height)
char * logview_prefs_get_monospace_font_name (LogviewPrefs *prefs)
gboolean logview_prefs_get_have_tearoff (LogviewPrefs *prefs)
gchar ** logview_prefs_get_stored_logfiles (LogviewPrefs *prefs)
void logview_prefs_store_log (LogviewPrefs *prefs, GFile *file)
void logview_prefs_remove_stored_log (LogviewPrefs *prefs, GFile *target)
void logview_prefs_store_fontsize (LogviewPrefs *prefs, int fontsize)
int logview_prefs_get_stored_fontsize (LogviewPrefs *prefs)
void logview_prefs_store_active_logfile (LogviewPrefs *prefs, const char *filename)
char * logview_prefs_get_active_logfile (LogviewPrefs *prefs)
GList * logview_prefs_get_filters (LogviewPrefs *prefs)
void logview_prefs_remove_filter (LogviewPrefs *prefs, const gchar *name)
void logview_prefs_add_filter (LogviewPrefs *prefs, LogviewFilter *filter)
LogviewFilter * logview_prefs_get_filter (LogviewPrefs *prefs, const gchar *name)
Macro Definition Documentation
DELIMITER
#define DELIMITER ":"
Definition at line 142 of file logview-prefs.c.
LOGVIEW_DEFAULT_HEIGHT
#define LOGVIEW_DEFAULT_HEIGHT 400
Definition at line 34 of file logview-prefs.c.
Referenced by logview_prefs_get_stored_window_size().
LOGVIEW_DEFAULT_WIDTH
#define LOGVIEW_DEFAULT_WIDTH 600
Definition at line 35 of file logview-prefs.c.
Referenced by logview_prefs_get_stored_window_size().
LOGVIEW_SCHEMA
#define LOGVIEW_SCHEMA "org.mate.system-log"
Definition at line 38 of file logview-prefs.c.
MATE_MENUS_HAVE_TEAROFF
#define MATE_MENUS_HAVE_TEAROFF "menus-have-tearoff"
Definition at line 48 of file logview-prefs.c.
Referenced by logview_prefs_get_have_tearoff().
MATE_MONOSPACE_FONT_NAME
#define MATE_MONOSPACE_FONT_NAME "monospace-font-name"
Definition at line 47 of file logview-prefs.c.
Referenced by logview_prefs_get_monospace_font_name().
PREF_FILTERS
#define PREF_FILTERS "filters"
Definition at line 44 of file logview-prefs.c.
PREF_FONTSIZE
#define PREF_FONTSIZE "fontsize"
Definition at line 43 of file logview-prefs.c.
Referenced by logview_prefs_get_stored_fontsize(), and logview_prefs_store_fontsize().
PREF_HEIGHT
#define PREF_HEIGHT "height"
Definition at line 40 of file logview-prefs.c.
Referenced by logview_prefs_get_stored_window_size(), and logview_prefs_store_window_size().
PREF_LOGFILE
#define PREF_LOGFILE "logfile"
Definition at line 41 of file logview-prefs.c.
Referenced by logview_prefs_get_active_logfile(), and logview_prefs_store_active_logfile().
PREF_LOGFILES
#define PREF_LOGFILES "logfiles"
Definition at line 42 of file logview-prefs.c.
Referenced by logview_prefs_get_stored_logfiles(), logview_prefs_remove_stored_log(), and logview_prefs_store_log().
PREF_WIDTH
#define PREF_WIDTH "width"
Definition at line 39 of file logview-prefs.c.
Referenced by logview_prefs_get_stored_window_size(), and logview_prefs_store_window_size().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FILTER_NAME
FILTER_INVISIBLE
FILTER_FOREGROUND
FILTER_BACKGROUND
FILTER_REGEX
MAX_TOKENS
Definition at line 58 of file logview-prefs.c.
anonymous enum
anonymous enum
Enumerator
SYSTEM_FONT_CHANGED
HAVE_TEAROFF_CHANGED
LAST_SIGNAL
Definition at line 52 of file logview-prefs.c.
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (LogviewPrefs , logview_prefs , G_TYPE_OBJECT)
logview_prefs_add_filter()
void logview_prefs_add_filter (LogviewPrefs * prefs, LogviewFilter * filter)
Definition at line 518 of file logview-prefs.c.
References LOGVIEW_IS_FILTER, LOGVIEW_IS_PREFS, name, NULL, and _LogviewPrefs::priv.
logview_prefs_get()
LogviewPrefs * logview_prefs_get (void)
Definition at line 316 of file logview-prefs.c.
References LOGVIEW_TYPE_PREFS, and NULL.
Referenced by logview_manager_close_active_log(), and logview_manager_set_active_log().
logview_prefs_get_active_logfile()
char * logview_prefs_get_active_logfile (LogviewPrefs * prefs)
Definition at line 483 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, PREF_LOGFILE, and _LogviewPrefs::priv.
Referenced by logview_app_initialize().
logview_prefs_get_filter()
LogviewFilter * logview_prefs_get_filter (LogviewPrefs * prefs, const gchar * name)
Definition at line 533 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, name, and _LogviewPrefs::priv.
logview_prefs_get_filters()
GList * logview_prefs_get_filters (LogviewPrefs * prefs)
Definition at line 492 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, NULL, and _LogviewPrefs::priv.
logview_prefs_get_have_tearoff()
gboolean logview_prefs_get_have_tearoff (LogviewPrefs * prefs)
Definition at line 363 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, MATE_MENUS_HAVE_TEAROFF, and _LogviewPrefs::priv.
logview_prefs_get_monospace_font_name()
char * logview_prefs_get_monospace_font_name (LogviewPrefs * prefs)
Definition at line 355 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, MATE_MONOSPACE_FONT_NAME, and _LogviewPrefs::priv.
logview_prefs_get_stored_fontsize()
int logview_prefs_get_stored_fontsize (LogviewPrefs * prefs)
Definition at line 465 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, PREF_FONTSIZE, and _LogviewPrefs::priv.
logview_prefs_get_stored_logfiles()
gchar ** logview_prefs_get_stored_logfiles (LogviewPrefs * prefs)
Definition at line 373 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, PREF_LOGFILES, and _LogviewPrefs::priv.
Referenced by logview_app_initialize(), logview_prefs_remove_stored_log(), and logview_prefs_store_log().
logview_prefs_get_stored_window_size()
void logview_prefs_get_stored_window_size (LogviewPrefs * prefs, int * width, int * height)
Definition at line 337 of file logview-prefs.c.
References LOGVIEW_DEFAULT_HEIGHT, LOGVIEW_DEFAULT_WIDTH, LOGVIEW_IS_PREFS, PREF_HEIGHT, PREF_WIDTH, and _LogviewPrefs::priv.
logview_prefs_remove_filter()
void logview_prefs_remove_filter (LogviewPrefs * prefs, const gchar * name)
Definition at line 506 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, name, and _LogviewPrefs::priv.
logview_prefs_remove_stored_log()
void logview_prefs_remove_stored_log (LogviewPrefs * prefs, GFile * target)
Definition at line 422 of file logview-prefs.c.
References FALSE, idx, LOGVIEW_IS_PREFS, logview_prefs_get_stored_logfiles(), NULL, PREF_LOGFILES, and _LogviewPrefs::priv.
Referenced by logview_manager_close_active_log().
logview_prefs_store_active_logfile()
void logview_prefs_store_active_logfile (LogviewPrefs * prefs, const char * filename)
Definition at line 473 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, PREF_LOGFILE, and _LogviewPrefs::priv.
Referenced by logview_manager_set_active_log().
logview_prefs_store_fontsize()
void logview_prefs_store_fontsize (LogviewPrefs * prefs, int fontsize)
Definition at line 456 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, PREF_FONTSIZE, and _LogviewPrefs::priv.
logview_prefs_store_log()
void logview_prefs_store_log (LogviewPrefs * prefs, GFile * file)
Definition at line 382 of file logview-prefs.c.
References FALSE, idx, LOGVIEW_IS_PREFS, logview_prefs_get_stored_logfiles(), NULL, PREF_LOGFILES, _LogviewPrefs::priv, and TRUE.
logview_prefs_store_window_size()
void logview_prefs_store_window_size (LogviewPrefs * prefs, int width, int height)
Definition at line 325 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, PREF_HEIGHT, PREF_WIDTH, and _LogviewPrefs::priv.