MATE Desktop Environment: logview-app.c File Reference
logview-app.c File Reference
#include "logview-app.h"
#include "logview-manager.h"
#include "logview-window.h"
#include "logview-prefs.h"
#include <glib/gi18n.h>
Enumerations
enum { APP_QUIT , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (LogviewApp, logview_app, G_TYPE_OBJECT)
LogviewApp * logview_app_get (void)
void logview_app_initialize (LogviewApp *app, char **log_files)
void logview_app_add_error (LogviewApp *app, const char *file_path, const char *secondary)
void logview_app_add_errors (LogviewApp *app, GPtrArray *errors)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
APP_QUIT
LAST_SIGNAL
Definition at line 39 of file logview-app.c.
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (LogviewApp , logview_app , G_TYPE_OBJECT)
References APP_QUIT, FALSE, NULL, and user_data.
logview_app_add_error()
void logview_app_add_error (LogviewApp * app, const char * file_path, const char * secondary)
Definition at line 359 of file logview-app.c.
References _, LOGVIEW_IS_APP, logview_window_add_error(), and _LogviewApp::priv.
logview_app_add_errors()
void logview_app_add_errors (LogviewApp * app, GPtrArray * errors)
Definition at line 389 of file logview-app.c.
References LOGVIEW_IS_APP, logview_window_add_error(), logview_window_add_errors(), and _LogviewApp::priv.
logview_app_get()
LogviewApp * logview_app_get (void)
Definition at line 310 of file logview-app.c.
References LOGVIEW_TYPE_APP, and NULL.
Referenced by main().
logview_app_initialize()
void logview_app_initialize (LogviewApp * app, char ** log_files)
Definition at line 325 of file logview-app.c.
References LOGVIEW_IS_APP, logview_manager_add_logs_from_names(), logview_prefs_get_active_logfile(), logview_prefs_get_stored_logfiles(), NULL, and _LogviewApp::priv.
Referenced by main().