MATE Desktop Environment: logview-prefs.h File Reference
logview-prefs.h File Reference
#include "logview-filter.h"
Classes
struct _LogviewPrefs
struct _LogviewPrefsClass
Macros
#define LOGVIEW_TYPE_PREFS logview_prefs_get_type()
#define LOGVIEW_PREFS(obj)
#define LOGVIEW_PREFS_CLASS(klass)
#define LOGVIEW_IS_PREFS(obj)
#define LOGVIEW_IS_PREFS_CLASS(klass)
#define LOGVIEW_PREFS_GET_CLASS(obj)
Typedefs
typedef struct _LogviewPrefs LogviewPrefs
typedef struct _LogviewPrefsClass LogviewPrefsClass
typedef struct _LogviewPrefsPrivate LogviewPrefsPrivate
Functions
GType logview_prefs_get_type (void)
LogviewPrefs * logview_prefs_get (void)
void logview_prefs_store_window_size (LogviewPrefs *prefs, int width, int height)
void logview_prefs_get_stored_window_size (LogviewPrefs *prefs, int *width, int *height)
char * logview_prefs_get_monospace_font_name (LogviewPrefs *prefs)
gboolean logview_prefs_get_have_tearoff (LogviewPrefs *prefs)
void logview_prefs_store_log (LogviewPrefs *prefs, GFile *file)
void logview_prefs_remove_stored_log (LogviewPrefs *prefs, GFile *target)
gchar ** logview_prefs_get_stored_logfiles (LogviewPrefs *prefs)
void logview_prefs_store_fontsize (LogviewPrefs *prefs, int fontsize)
int logview_prefs_get_stored_fontsize (LogviewPrefs *prefs)
void logview_prefs_store_active_logfile (LogviewPrefs *prefs, const char *filename)
char * logview_prefs_get_active_logfile (LogviewPrefs *prefs)
GList * logview_prefs_get_filters (LogviewPrefs *prefs)
void logview_prefs_remove_filter (LogviewPrefs *prefs, const gchar *name)
void logview_prefs_add_filter (LogviewPrefs *prefs, LogviewFilter *filter)
LogviewFilter * logview_prefs_get_filter (LogviewPrefs *prefs, const gchar *name)
Macro Definition Documentation
LOGVIEW_IS_PREFS
#define LOGVIEW_IS_PREFS (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), LOGVIEW_TYPE_PREFS))
Definition at line 31 of file logview-prefs.h.
Referenced by logview_prefs_add_filter(), logview_prefs_get_active_logfile(), logview_prefs_get_filter(), logview_prefs_get_filters(), logview_prefs_get_have_tearoff(), logview_prefs_get_monospace_font_name(), logview_prefs_get_stored_fontsize(), logview_prefs_get_stored_logfiles(), logview_prefs_get_stored_window_size(), logview_prefs_remove_filter(), logview_prefs_remove_stored_log(), logview_prefs_store_active_logfile(), logview_prefs_store_fontsize(), logview_prefs_store_log(), and logview_prefs_store_window_size().
LOGVIEW_IS_PREFS_CLASS
#define LOGVIEW_IS_PREFS_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), LOGVIEW_TYPE_PREFS))
Definition at line 33 of file logview-prefs.h.
LOGVIEW_PREFS
#define LOGVIEW_PREFS (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), LOGVIEW_TYPE_PREFS, LogviewPrefs))
Definition at line 27 of file logview-prefs.h.
LOGVIEW_PREFS_CLASS
#define LOGVIEW_PREFS_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), LOGVIEW_TYPE_PREFS, LogviewPrefsClass))
Definition at line 29 of file logview-prefs.h.
LOGVIEW_PREFS_GET_CLASS
#define LOGVIEW_PREFS_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), LOGVIEW_TYPE_PREFS, LogviewPrefsClass))
Definition at line 35 of file logview-prefs.h.
LOGVIEW_TYPE_PREFS
#define LOGVIEW_TYPE_PREFS logview_prefs_get_type()
Definition at line 26 of file logview-prefs.h.
Referenced by logview_prefs_get().
Typedef Documentation
LogviewPrefs
typedef struct _LogviewPrefs LogviewPrefs
Definition at line 38 of file logview-prefs.h.
LogviewPrefsClass
typedef struct _LogviewPrefsClass LogviewPrefsClass
Definition at line 39 of file logview-prefs.h.
LogviewPrefsPrivate
typedef struct _LogviewPrefsPrivate LogviewPrefsPrivate
Definition at line 40 of file logview-prefs.h.
Function Documentation
logview_prefs_add_filter()
void logview_prefs_add_filter (LogviewPrefs * prefs, LogviewFilter * filter)
Definition at line 518 of file logview-prefs.c.
References LOGVIEW_IS_FILTER, LOGVIEW_IS_PREFS, name, NULL, and _LogviewPrefs::priv.
logview_prefs_get()
LogviewPrefs * logview_prefs_get (void)
Definition at line 316 of file logview-prefs.c.
References LOGVIEW_TYPE_PREFS, and NULL.
Referenced by logview_manager_close_active_log(), and logview_manager_set_active_log().
logview_prefs_get_active_logfile()
char * logview_prefs_get_active_logfile (LogviewPrefs * prefs)
Definition at line 483 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, PREF_LOGFILE, and _LogviewPrefs::priv.
Referenced by logview_app_initialize().
logview_prefs_get_filter()
LogviewFilter * logview_prefs_get_filter (LogviewPrefs * prefs, const gchar * name)
Definition at line 533 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, name, and _LogviewPrefs::priv.
logview_prefs_get_filters()
GList * logview_prefs_get_filters (LogviewPrefs * prefs)
Definition at line 492 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, NULL, and _LogviewPrefs::priv.
logview_prefs_get_have_tearoff()
gboolean logview_prefs_get_have_tearoff (LogviewPrefs * prefs)
Definition at line 363 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, MATE_MENUS_HAVE_TEAROFF, and _LogviewPrefs::priv.
logview_prefs_get_monospace_font_name()
char * logview_prefs_get_monospace_font_name (LogviewPrefs * prefs)
Definition at line 355 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, MATE_MONOSPACE_FONT_NAME, and _LogviewPrefs::priv.
logview_prefs_get_stored_fontsize()
int logview_prefs_get_stored_fontsize (LogviewPrefs * prefs)
Definition at line 465 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, PREF_FONTSIZE, and _LogviewPrefs::priv.
logview_prefs_get_stored_logfiles()
gchar ** logview_prefs_get_stored_logfiles (LogviewPrefs * prefs)
Definition at line 373 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, PREF_LOGFILES, and _LogviewPrefs::priv.
Referenced by logview_app_initialize(), logview_prefs_remove_stored_log(), and logview_prefs_store_log().
logview_prefs_get_stored_window_size()
void logview_prefs_get_stored_window_size (LogviewPrefs * prefs, int * width, int * height)
Definition at line 337 of file logview-prefs.c.
References LOGVIEW_DEFAULT_HEIGHT, LOGVIEW_DEFAULT_WIDTH, LOGVIEW_IS_PREFS, PREF_HEIGHT, PREF_WIDTH, and _LogviewPrefs::priv.
logview_prefs_get_type()
GType logview_prefs_get_type (void)
References name.
logview_prefs_remove_filter()
void logview_prefs_remove_filter (LogviewPrefs * prefs, const gchar * name)
Definition at line 506 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, name, and _LogviewPrefs::priv.
logview_prefs_remove_stored_log()
void logview_prefs_remove_stored_log (LogviewPrefs * prefs, GFile * target)
Definition at line 422 of file logview-prefs.c.
References FALSE, idx, LOGVIEW_IS_PREFS, logview_prefs_get_stored_logfiles(), NULL, PREF_LOGFILES, and _LogviewPrefs::priv.
Referenced by logview_manager_close_active_log().
logview_prefs_store_active_logfile()
void logview_prefs_store_active_logfile (LogviewPrefs * prefs, const char * filename)
Definition at line 473 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, PREF_LOGFILE, and _LogviewPrefs::priv.
Referenced by logview_manager_set_active_log().
logview_prefs_store_fontsize()
void logview_prefs_store_fontsize (LogviewPrefs * prefs, int fontsize)
Definition at line 456 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, PREF_FONTSIZE, and _LogviewPrefs::priv.
logview_prefs_store_log()
void logview_prefs_store_log (LogviewPrefs * prefs, GFile * file)
Definition at line 382 of file logview-prefs.c.
References FALSE, idx, LOGVIEW_IS_PREFS, logview_prefs_get_stored_logfiles(), NULL, PREF_LOGFILES, _LogviewPrefs::priv, and TRUE.
logview_prefs_store_window_size()
void logview_prefs_store_window_size (LogviewPrefs * prefs, int width, int height)
Definition at line 325 of file logview-prefs.c.
References LOGVIEW_IS_PREFS, PREF_HEIGHT, PREF_WIDTH, and _LogviewPrefs::priv.