MATE Desktop Environment: logview-app.h File Reference
logview-app.h File Reference
#include <glib-object.h>
Classes
struct _LogviewApp
struct _LogviewAppClass
Macros
#define LOGVIEW_TYPE_APP logview_app_get_type()
#define LOGVIEW_APP(obj)
#define LOGVIEW_APP_CLASS(klass)
#define LOGVIEW_IS_APP(obj)
#define LOGVIEW_IS_APP_CLASS(klass)
#define LOGVIEW_APP_GET_CLASS(obj)
Typedefs
typedef struct _LogviewApp LogviewApp
typedef struct _LogviewAppClass LogviewAppClass
typedef struct _LogviewAppPrivate LogviewAppPrivate
Functions
GType logview_app_get_type (void)
LogviewApp * logview_app_get (void)
void logview_app_initialize (LogviewApp *app, char **log_files)
void logview_app_add_error (LogviewApp *app, const char *file_path, const char *secondary)
void logview_app_add_errors (LogviewApp *app, GPtrArray *errors)
Macro Definition Documentation
LOGVIEW_APP
#define LOGVIEW_APP (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), LOGVIEW_TYPE_APP, LogviewApp))
Definition at line 29 of file logview-app.h.
LOGVIEW_APP_CLASS
#define LOGVIEW_APP_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), LOGVIEW_TYPE_APP, LogviewAppClass))
Definition at line 31 of file logview-app.h.
LOGVIEW_APP_GET_CLASS
#define LOGVIEW_APP_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), LOGVIEW_TYPE_APP, LogviewAppClass))
Definition at line 37 of file logview-app.h.
LOGVIEW_IS_APP
#define LOGVIEW_IS_APP (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), LOGVIEW_TYPE_APP))
Definition at line 33 of file logview-app.h.
Referenced by logview_app_add_error(), logview_app_add_errors(), and logview_app_initialize().
LOGVIEW_IS_APP_CLASS
#define LOGVIEW_IS_APP_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), LOGVIEW_TYPE_APP))
Definition at line 35 of file logview-app.h.
LOGVIEW_TYPE_APP
#define LOGVIEW_TYPE_APP logview_app_get_type()
Definition at line 28 of file logview-app.h.
Referenced by logview_app_get().
Typedef Documentation
LogviewApp
typedef struct _LogviewApp LogviewApp
Definition at line 40 of file logview-app.h.
LogviewAppClass
typedef struct _LogviewAppClass LogviewAppClass
Definition at line 41 of file logview-app.h.
LogviewAppPrivate
typedef struct _LogviewAppPrivate LogviewAppPrivate
Definition at line 42 of file logview-app.h.
Function Documentation
logview_app_add_error()
void logview_app_add_error (LogviewApp * app, const char * file_path, const char * secondary)
Definition at line 359 of file logview-app.c.
References _, LOGVIEW_IS_APP, logview_window_add_error(), and _LogviewApp::priv.
logview_app_add_errors()
void logview_app_add_errors (LogviewApp * app, GPtrArray * errors)
Definition at line 389 of file logview-app.c.
References LOGVIEW_IS_APP, logview_window_add_error(), logview_window_add_errors(), and _LogviewApp::priv.
logview_app_get()
LogviewApp * logview_app_get (void)
Definition at line 310 of file logview-app.c.
References LOGVIEW_TYPE_APP, and NULL.
Referenced by main().
logview_app_get_type()
GType logview_app_get_type (void)
logview_app_initialize()
void logview_app_initialize (LogviewApp * app, char ** log_files)
Definition at line 325 of file logview-app.c.
References LOGVIEW_IS_APP, logview_manager_add_logs_from_names(), logview_prefs_get_active_logfile(), logview_prefs_get_stored_logfiles(), NULL, and _LogviewApp::priv.
Referenced by main().