MATE Desktop Environment: logview-utils.c File Reference
logview-utils.c File Reference
#include <time.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <glib.h>
#include "logview-utils.h"
Macros
#define _XOPEN_SOURCE
#define _XOPEN_SOURCE_EXTENDED 1 /* strptime is XPG4v2 */
Functions
void logview_utils_day_free (Day *day)
Day * logview_utils_day_copy (Day *day)
GSList * logview_utils_day_list_copy (GSList *days)
gint days_compare (gconstpointer a, gconstpointer b)
GSList * log_read_dates (const char **buffer_lines, time_t current)
Macro Definition Documentation
_XOPEN_SOURCE
#define _XOPEN_SOURCE
Definition at line 26 of file logview-utils.c.
_XOPEN_SOURCE_EXTENDED
#define _XOPEN_SOURCE_EXTENDED 1 /* strptime is XPG4v2 */
Definition at line 27 of file logview-utils.c.
Function Documentation
days_compare()
gint days_compare (gconstpointer a, gconstpointer b)
Definition at line 75 of file logview-utils.c.
References b, and Day::date.
Referenced by log_read_dates().
log_read_dates()
GSList * log_read_dates (const char ** buffer_lines, time_t current)
log_read_dates:
@buffer_lines: an array of text lines. @current: the mtime of the file being parsed.
Reads all the dates inside the text buffer. All dates are given with respect to the 1/1/1970 and are then corrected to the correct year once we reach the end.
Returns: a #GSList of Day structures.
Definition at line 140 of file logview-utils.c.
References Day::date, days_compare(), FALSE, Day::first_line, Day::last_line, NULL, Day::timestamp_len, and TRUE.
logview_utils_day_copy()
Day * logview_utils_day_copy (Day * day)
Definition at line 49 of file logview-utils.c.
References Day::date, Day::first_line, Day::last_line, and Day::timestamp_len.
Referenced by logview_utils_day_list_copy().
logview_utils_day_free()
void logview_utils_day_free (Day * day)
Definition at line 38 of file logview-utils.c.
References Day::date.
logview_utils_day_list_copy()
GSList * logview_utils_day_list_copy (GSList * days)
Definition at line 63 of file logview-utils.c.
References logview_utils_day_copy(), and NULL.