MATE Desktop Environment: util.h File Reference
util.h File Reference
#include <glib.h>
#include <glib-object.h>
Enumerations
enum MetaDebugTopic {
META_DEBUG_FOCUS = 1 << 0 , META_DEBUG_WORKAREA = 1 << 1 , META_DEBUG_STACK = 1 << 2 , META_DEBUG_THEMES = 1 << 3 ,
META_DEBUG_SM = 1 << 4 , META_DEBUG_EVENTS = 1 << 5 , META_DEBUG_WINDOW_STATE = 1 << 6 , META_DEBUG_WINDOW_OPS = 1 << 7 ,
META_DEBUG_GEOMETRY = 1 << 8 , META_DEBUG_PLACEMENT = 1 << 9 , META_DEBUG_PING = 1 << 10 , META_DEBUG_XINERAMA = 1 << 11 ,
META_DEBUG_KEYBINDINGS = 1 << 12 , META_DEBUG_SYNC = 1 << 13 , META_DEBUG_ERRORS = 1 << 14 , META_DEBUG_STARTUP = 1 << 15 ,
META_DEBUG_PREFS = 1 << 16 , META_DEBUG_GROUPS = 1 << 17 , META_DEBUG_RESIZING = 1 << 18 , META_DEBUG_SHAPES = 1 << 19 ,
META_DEBUG_COMPOSITOR = 1 << 20 , META_DEBUG_EDGE_RESISTANCE = 1 << 21
}
Functions
gboolean meta_is_verbose (void)
void meta_set_verbose (gboolean setting)
gboolean meta_is_debugging (void)
void meta_set_debugging (gboolean setting)
gboolean meta_is_syncing (void)
void meta_set_syncing (gboolean setting)
gboolean meta_get_replace_current_wm (void)
void meta_set_replace_current_wm (gboolean setting)
void meta_debug_spew_real (const char *format,...)
void meta_verbose_real (const char *format,...)
void meta_bug (const char *format,...) G_GNUC_NORETURN G_ANALYZER_NORETURN
void meta_warning (const char *format,...)
void meta_fatal (const char *format,...)
void meta_topic_real (MetaDebugTopic topic, const char *format,...)
void meta_push_no_msg_prefix (void)
void meta_pop_no_msg_prefix (void)
gint meta_unsigned_long_equal (gconstpointer v1, gconstpointer v2)
guint meta_unsigned_long_hash (gconstpointer v)
void meta_print_backtrace (void)
const char * meta_gravity_to_string (int gravity)
char * meta_g_utf8_strndup (const gchar *src, gsize n)
GPid meta_show_dialog (const char *type, const char *message, const char *timeout, const char *display, const char *ok_text, const char *cancel_text, const int transient_for, GSList *columns, GSList *entries)
GPid meta_show_entry_dialog (const char *message, gint *active_workspace_id, const char *entry_text, const char *display, const char *ok_text, const char *cancel_text, const int transient_for, const GIOFunc stdio_func_cb)
Enumeration Type Documentation
MetaDebugTopic
enum MetaDebugTopic
Enumerator
META_DEBUG_FOCUS
META_DEBUG_WORKAREA
META_DEBUG_STACK
META_DEBUG_THEMES
META_DEBUG_SM
META_DEBUG_EVENTS
META_DEBUG_WINDOW_STATE
META_DEBUG_WINDOW_OPS
META_DEBUG_GEOMETRY
META_DEBUG_PLACEMENT
META_DEBUG_PING
META_DEBUG_XINERAMA
META_DEBUG_KEYBINDINGS
META_DEBUG_SYNC
META_DEBUG_ERRORS
META_DEBUG_STARTUP
META_DEBUG_PREFS
META_DEBUG_GROUPS
META_DEBUG_RESIZING
META_DEBUG_SHAPES
META_DEBUG_COMPOSITOR
META_DEBUG_EDGE_RESISTANCE
Definition at line 52 of file marco/src/include/util.h.
Function Documentation
meta_bug()
void meta_bug (const char * format, ...)
Definition at line 362 of file marco/src/core/util.c.
References _, meta_print_backtrace(), and NULL.
Referenced by meta_core_get(), meta_display_close(), meta_display_ungrab(), meta_frame_layout_calc_geometry(), meta_prefs_remove_listener(), meta_prop_get_values(), meta_screen_calc_workspace_layout(), meta_stack_add(), meta_stack_remove(), meta_verbose_real(), meta_window_free(), meta_workspace_get_neighbor(), and meta_workspace_index().
meta_debug_spew_real()
void meta_debug_spew_real (const char * format, ...)
meta_fatal()
void meta_fatal (const char * format, ...)
Definition at line 423 of file marco/src/core/util.c.
References _, meta_exit(), META_EXIT_ERROR, and NULL.
Referenced by main(), meta_set_verbose(), meta_ui_init(), and meta_verbose_real().
meta_g_utf8_strndup()
char * meta_g_utf8_strndup (const gchar * src, gsize n)
Definition at line 177 of file marco/src/core/util.c.
Referenced by meta_topic_real().
meta_get_replace_current_wm()
gboolean meta_get_replace_current_wm (void)
Definition at line 165 of file marco/src/core/util.c.
Referenced by meta_screen_new().
meta_gravity_to_string()
const char * meta_gravity_to_string (int gravity)
Definition at line 494 of file marco/src/core/util.c.
Referenced by meta_topic_real().
meta_is_debugging()
gboolean meta_is_debugging (void)
Definition at line 148 of file marco/src/core/util.c.
Referenced by meta_theme_load().
meta_is_syncing()
gboolean meta_is_syncing (void)
Returns whether X synchronisation is currently enabled.
Returns
true if we must wait for events whenever we send X requests; false otherwise.
Definition at line 4325 of file display.c.
meta_is_verbose()
gboolean meta_is_verbose (void)
Definition at line 128 of file marco/src/core/util.c.
Referenced by meta_screen_calc_workspace_layout(), meta_window_client_message(), and meta_window_update_net_wm_type().
meta_pop_no_msg_prefix()
void meta_pop_no_msg_prefix (void)
Definition at line 459 of file marco/src/core/util.c.
Referenced by meta_screen_calc_workspace_layout(), and meta_topic_real().
meta_print_backtrace()
void meta_print_backtrace (void)
Definition at line 67 of file marco/src/core/util.c.
Referenced by meta_bug(), and meta_topic_real().
meta_push_no_msg_prefix()
void meta_push_no_msg_prefix (void)
Definition at line 453 of file marco/src/core/util.c.
Referenced by meta_screen_calc_workspace_layout(), and meta_topic_real().
meta_set_debugging()
void meta_set_debugging (gboolean setting)
Definition at line 154 of file marco/src/core/util.c.
Referenced by main().
meta_set_replace_current_wm()
void meta_set_replace_current_wm (gboolean setting)
Definition at line 171 of file marco/src/core/util.c.
Referenced by main().
meta_set_syncing()
void meta_set_syncing (gboolean setting)
A handy way to turn on synchronisation on or off for every display.
Definition at line 4337 of file display.c.
References meta_get_display().
Referenced by main().
meta_set_verbose()
void meta_set_verbose (gboolean setting)
Definition at line 134 of file marco/src/core/util.c.
References _, and meta_fatal().
Referenced by main().
meta_show_dialog()
GPid meta_show_dialog (const char * type, const char * message, const char * timeout, const char * display, const char * ok_text, const char * cancel_text, const int transient_for, GSList * columns, GSList * entries)
Definition at line 535 of file marco/src/core/util.c.
References _, error, message(), meta_warning(), and NULL.
Referenced by meta_topic_real().
meta_show_entry_dialog()
GPid meta_show_entry_dialog (const char * message, gint * active_workspace_id, const char * entry_text, const char * display, const char * ok_text, const char * cancel_text, const int transient_for, const GIOFunc stdio_func_cb)
Definition at line 633 of file marco/src/core/util.c.
References _, error, FALSE, message(), META_DEBUG_KEYBINDINGS, meta_warning(), NULL, and TRUE.
Referenced by meta_topic_real().
meta_topic_real()
void meta_topic_real (MetaDebugTopic topic, const char * format, ...)
References message(), meta_g_utf8_strndup(), meta_gravity_to_string(), meta_pop_no_msg_prefix(), meta_print_backtrace(), meta_push_no_msg_prefix(), meta_show_dialog(), meta_show_entry_dialog(), meta_unsigned_long_equal(), and meta_unsigned_long_hash().
meta_unsigned_long_equal()
gint meta_unsigned_long_equal (gconstpointer v1, gconstpointer v2)
Definition at line 474 of file marco/src/core/util.c.
Referenced by meta_topic_real().
meta_unsigned_long_hash()
guint meta_unsigned_long_hash (gconstpointer v)
Definition at line 481 of file marco/src/core/util.c.
Referenced by meta_topic_real().
meta_verbose_real()
void meta_verbose_real (const char * format, ...)
References meta_bug(), meta_fatal(), meta_verbose_real(), and meta_warning().
Referenced by meta_verbose_real().
meta_warning()
void meta_warning (const char * format, ...)
Definition at line 395 of file marco/src/core/util.c.
References _, and NULL.
Referenced by main(), meta_core_get(), meta_display_begin_grab_op(), meta_display_for_x_display(), meta_display_ping_window(), meta_frames_unmanage_window(), meta_rectangle_clamp_to_fit_into_region(), meta_rectangle_clip_to_region(), meta_rectangle_shove_into_region(), meta_screen_free(), meta_screen_new(), meta_screen_update_workspace_layout(), meta_show_dialog(), meta_show_entry_dialog(), meta_stack_set_positions(), meta_theme_earliest_version_with_button(), meta_theme_set_current(), meta_verbose_real(), meta_window_client_message(), meta_window_get_current_tile_area(), meta_window_kill(), meta_window_menu_popup(), meta_window_raise(), and meta_workspace_focus_default_window().