MATE Desktop Environment: util.c File Reference
util.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include "util.h"
#include "main.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <X11/Xlib.h>
#include <X11/Xutil.h>
Macros
#define _GNU_SOURCE
#define _POSIX_C_SOURCE 200112L /* for fdopen() */
Functions
void meta_print_backtrace (void)
gboolean meta_is_verbose (void)
void meta_set_verbose (gboolean setting)
gboolean meta_is_debugging (void)
void meta_set_debugging (gboolean setting)
gboolean meta_get_replace_current_wm (void)
void meta_set_replace_current_wm (gboolean setting)
char * meta_g_utf8_strndup (const gchar *src, gsize n)
void meta_bug (const char *format,...)
void meta_warning (const char *format,...)
void meta_fatal (const char *format,...)
void meta_push_no_msg_prefix (void)
void meta_pop_no_msg_prefix (void)
void meta_exit (MetaExitCode code)
gint meta_unsigned_long_equal (gconstpointer v1, gconstpointer v2)
guint meta_unsigned_long_hash (gconstpointer v)
const char * meta_gravity_to_string (int gravity)
GPid meta_show_dialog (const char *type, const char *message, const char *timeout, const char *display, const char *ok_text, const char *cancel_text, const int transient_for, GSList *columns, GSList *entries)
GPid meta_show_entry_dialog (const char *message, gint *active_workspace_id, const char *entry_text, const char *display, const char *ok_text, const char *cancel_text, const int transient_for, const GIOFunc stdio_func_cb)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 25 of file marco/src/core/util.c.
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200112L /* for fdopen() */
Definition at line 26 of file marco/src/core/util.c.
Function Documentation
meta_bug()
void meta_bug (const char * format, ...)
Definition at line 362 of file marco/src/core/util.c.
References _, meta_print_backtrace(), and NULL.
Referenced by meta_core_get(), meta_display_close(), meta_display_ungrab(), meta_frame_layout_calc_geometry(), meta_prefs_remove_listener(), meta_prop_get_values(), meta_screen_calc_workspace_layout(), meta_stack_add(), meta_stack_remove(), meta_verbose_real(), meta_window_free(), meta_workspace_get_neighbor(), and meta_workspace_index().
meta_exit()
void meta_exit (MetaExitCode code)
Definition at line 467 of file marco/src/core/util.c.
Referenced by main(), and meta_fatal().
meta_fatal()
void meta_fatal (const char * format, ...)
Definition at line 423 of file marco/src/core/util.c.
References _, meta_exit(), META_EXIT_ERROR, and NULL.
Referenced by main(), meta_set_verbose(), meta_ui_init(), and meta_verbose_real().
meta_g_utf8_strndup()
char * meta_g_utf8_strndup (const gchar * src, gsize n)
Definition at line 177 of file marco/src/core/util.c.
Referenced by meta_topic_real().
meta_get_replace_current_wm()
gboolean meta_get_replace_current_wm (void)
Definition at line 165 of file marco/src/core/util.c.
Referenced by meta_screen_new().
meta_gravity_to_string()
const char * meta_gravity_to_string (int gravity)
Definition at line 494 of file marco/src/core/util.c.
Referenced by meta_topic_real().
meta_is_debugging()
gboolean meta_is_debugging (void)
Definition at line 148 of file marco/src/core/util.c.
Referenced by meta_theme_load().
meta_is_verbose()
gboolean meta_is_verbose (void)
Definition at line 128 of file marco/src/core/util.c.
Referenced by meta_screen_calc_workspace_layout(), meta_window_client_message(), and meta_window_update_net_wm_type().
meta_pop_no_msg_prefix()
void meta_pop_no_msg_prefix (void)
Definition at line 459 of file marco/src/core/util.c.
Referenced by meta_screen_calc_workspace_layout(), and meta_topic_real().
meta_print_backtrace()
void meta_print_backtrace (void)
Definition at line 67 of file marco/src/core/util.c.
Referenced by meta_bug(), and meta_topic_real().
meta_push_no_msg_prefix()
void meta_push_no_msg_prefix (void)
Definition at line 453 of file marco/src/core/util.c.
Referenced by meta_screen_calc_workspace_layout(), and meta_topic_real().
meta_set_debugging()
void meta_set_debugging (gboolean setting)
Definition at line 154 of file marco/src/core/util.c.
Referenced by main().
meta_set_replace_current_wm()
void meta_set_replace_current_wm (gboolean setting)
Definition at line 171 of file marco/src/core/util.c.
Referenced by main().
meta_set_verbose()
void meta_set_verbose (gboolean setting)
Definition at line 134 of file marco/src/core/util.c.
References _, and meta_fatal().
Referenced by main().
meta_show_dialog()
GPid meta_show_dialog (const char * type, const char * message, const char * timeout, const char * display, const char * ok_text, const char * cancel_text, const int transient_for, GSList * columns, GSList * entries)
Definition at line 535 of file marco/src/core/util.c.
References _, error, message(), meta_warning(), and NULL.
Referenced by meta_topic_real().
meta_show_entry_dialog()
GPid meta_show_entry_dialog (const char * message, gint * active_workspace_id, const char * entry_text, const char * display, const char * ok_text, const char * cancel_text, const int transient_for, const GIOFunc stdio_func_cb)
Definition at line 633 of file marco/src/core/util.c.
References _, error, FALSE, message(), META_DEBUG_KEYBINDINGS, meta_warning(), NULL, and TRUE.
Referenced by meta_topic_real().
meta_unsigned_long_equal()
gint meta_unsigned_long_equal (gconstpointer v1, gconstpointer v2)
Definition at line 474 of file marco/src/core/util.c.
Referenced by meta_topic_real().
meta_unsigned_long_hash()
guint meta_unsigned_long_hash (gconstpointer v)
Definition at line 481 of file marco/src/core/util.c.
Referenced by meta_topic_real().
meta_warning()
void meta_warning (const char * format, ...)
Definition at line 395 of file marco/src/core/util.c.
References _, and NULL.
Referenced by main(), meta_core_get(), meta_display_begin_grab_op(), meta_display_for_x_display(), meta_display_ping_window(), meta_frames_unmanage_window(), meta_rectangle_clamp_to_fit_into_region(), meta_rectangle_clip_to_region(), meta_rectangle_shove_into_region(), meta_screen_free(), meta_screen_new(), meta_screen_update_workspace_layout(), meta_show_dialog(), meta_show_entry_dialog(), meta_stack_set_positions(), meta_theme_earliest_version_with_button(), meta_theme_set_current(), meta_verbose_real(), meta_window_client_message(), meta_window_get_current_tile_area(), meta_window_kill(), meta_window_menu_popup(), meta_window_raise(), and meta_workspace_focus_default_window().