MATE Desktop Environment: ui.h File Reference
ui.h File Reference
#include "common.h"
#include "types.h"
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <glib.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <cairo/cairo.h>
#include "tabpopup.h"
#include "tile-preview.h"
Macros
#define META_PRIORITY_RESIZE (G_PRIORITY_HIGH_IDLE + 15)
Typedefs
typedef struct _MetaUI MetaUI
typedef struct _MetaImageWindow MetaImageWindow
typedef gboolean(* MetaEventFunc) (XEvent *xevent, gpointer data)
Enumerations
enum MetaUIDirection { META_UI_DIRECTION_LTR , META_UI_DIRECTION_RTL }
Functions
void meta_ui_init (int *argc, char ***argv)
Display * meta_ui_get_display (void)
void meta_ui_add_event_func (Display *xdisplay, MetaEventFunc func, gpointer data)
void meta_ui_remove_event_func (Display *xdisplay, MetaEventFunc func, gpointer data)
MetaUI * meta_ui_new (Display *xdisplay, Screen *screen)
void meta_ui_free (MetaUI *ui)
void meta_ui_theme_get_frame_borders (MetaUI *ui, MetaFrameType type, MetaFrameFlags flags, MetaFrameBorders *borders)
void meta_ui_get_frame_borders (MetaUI *ui, Window frame_xwindow, MetaFrameBorders *borders)
Window meta_ui_create_frame_window (MetaUI *ui, Display *xdisplay, Visual *xvisual, gint x, gint y, gint width, gint height)
void meta_ui_destroy_frame_window (MetaUI *ui, Window xwindow)
void meta_ui_move_resize_frame (MetaUI *ui, Window frame, int x, int y, int width, int height)
void meta_ui_map_frame (MetaUI *ui, Window xwindow)
void meta_ui_unmap_frame (MetaUI *ui, Window xwindow)
void meta_ui_apply_frame_shape (MetaUI *ui, MetaDisplay *display, Window xwindow, int new_window_width, int new_window_height, gboolean window_has_shape)
cairo_region_t * meta_ui_get_frame_bounds (MetaUI *ui, Window xwindow, int window_width, int window_height)
void meta_ui_get_corner_radiuses (MetaUI *ui, Window xwindow, float *top_left, float *top_right, float *bottom_left, float *bottom_right)
void meta_ui_queue_frame_draw (MetaUI *ui, Window xwindow)
void meta_ui_set_frame_title (MetaUI *ui, Window xwindow, const char *title)
void meta_ui_update_frame_style (MetaUI *ui, Window window)
void meta_ui_repaint_frame (MetaUI *ui, Window xwindow)
MetaWindowMenu * meta_ui_window_menu_new (MetaUI *ui, Window client_xwindow, MetaMenuOp ops, MetaMenuOp insensitive, unsigned long active_workspace, int n_workspaces, MetaWindowMenuFunc func, gpointer data)
void meta_ui_window_menu_popup (MetaWindowMenu *menu, int root_x, int root_y, int button, guint32 timestamp)
void meta_ui_window_menu_free (MetaWindowMenu *menu)
GdkPixbuf * meta_gdk_pixbuf_get_from_pixmap (GdkPixbuf *dest, Pixmap xpixmap, int src_x, int src_y, int dest_x, int dest_y, int width, int height)
void meta_ui_push_delay_exposes (MetaUI *ui)
void meta_ui_pop_delay_exposes (MetaUI *ui)
GdkPixbuf * meta_ui_get_default_window_icon (MetaUI *ui)
GdkPixbuf * meta_ui_get_default_mini_icon (MetaUI *ui)
GdkPixbuf * meta_ui_get_window_icon_from_desktop_id (MetaUI *ui, char *desktop_id)
GdkPixbuf * meta_ui_get_mini_icon_from_desktop_id (MetaUI *ui, char *desktop_id)
gboolean meta_ui_window_should_not_cause_focus (Display *xdisplay, Window xwindow)
void meta_ui_set_current_theme (const char *name, gboolean force_reload)
gboolean meta_ui_have_a_theme (void)
gboolean meta_ui_parse_accelerator (const char *accel, unsigned int *keysym, unsigned int *keycode, MetaVirtualModifier *mask)
gboolean meta_ui_parse_modifier (const char *accel, MetaVirtualModifier *mask)
gchar * meta_ui_accelerator_name (unsigned int keysym, MetaVirtualModifier mask)
gboolean meta_ui_window_is_widget (MetaUI *ui, Window xwindow)
int meta_ui_get_drag_threshold (MetaUI *ui)
MetaUIDirection meta_ui_get_direction (void)
GdkPixbuf * meta_ui_get_pixbuf_from_surface (cairo_surface_t *surface)
Macro Definition Documentation
META_PRIORITY_RESIZE
#define META_PRIORITY_RESIZE (G_PRIORITY_HIGH_IDLE + 15)
Definition at line 37 of file marco/src/include/ui.h.
Referenced by meta_window_queue().
Typedef Documentation
MetaEventFunc
typedef gboolean(* MetaEventFunc) (XEvent *xevent, gpointer data)
Definition at line 43 of file marco/src/include/ui.h.
MetaImageWindow
typedef struct _MetaImageWindow MetaImageWindow
Definition at line 41 of file marco/src/include/ui.h.
MetaUI
typedef struct _MetaUI MetaUI
Definition at line 39 of file marco/src/include/ui.h.
Enumeration Type Documentation
MetaUIDirection
enum MetaUIDirection
Enumerator
META_UI_DIRECTION_LTR
META_UI_DIRECTION_RTL
Definition at line 45 of file marco/src/include/ui.h.
Function Documentation
meta_gdk_pixbuf_get_from_pixmap()
GdkPixbuf * meta_gdk_pixbuf_get_from_pixmap (GdkPixbuf * dest, Pixmap xpixmap, int src_x, int src_y, int dest_x, int dest_y, int width, int height)
Definition at line 535 of file ui.c.
References dest, and NULL.
meta_ui_accelerator_name()
gchar * meta_ui_accelerator_name (unsigned int keysym, MetaVirtualModifier mask)
Definition at line 869 of file ui.c.
References mask, META_VIRTUAL_ALT_MASK, META_VIRTUAL_CONTROL_MASK, META_VIRTUAL_HYPER_MASK, META_VIRTUAL_META_MASK, META_VIRTUAL_MOD2_MASK, META_VIRTUAL_MOD3_MASK, META_VIRTUAL_MOD4_MASK, META_VIRTUAL_MOD5_MASK, META_VIRTUAL_SHIFT_MASK, and META_VIRTUAL_SUPER_MASK.
meta_ui_add_event_func()
void meta_ui_add_event_func (Display * xdisplay, MetaEventFunc func, gpointer data)
Definition at line 232 of file ui.c.
References data, and NULL.
meta_ui_apply_frame_shape()
void meta_ui_apply_frame_shape (MetaUI * ui, MetaDisplay * display, Window xwindow, int new_window_width, int new_window_height, gboolean window_has_shape)
Definition at line 461 of file ui.c.
References meta_frames_apply_shapes().
Referenced by meta_window_ensure_frame().
meta_ui_create_frame_window()
Window meta_ui_create_frame_window (MetaUI * ui, Display * xdisplay, Visual * xvisual, gint x, gint y, gint width, gint height)
Definition at line 334 of file ui.c.
References FALSE, meta_frames_manage_window(), and NULL.
Referenced by meta_window_ensure_frame().
meta_ui_destroy_frame_window()
void meta_ui_destroy_frame_window (MetaUI * ui, Window xwindow)
Definition at line 399 of file ui.c.
References meta_frames_unmanage_window().
Referenced by meta_window_destroy_frame().
meta_ui_free()
void meta_ui_free (MetaUI * ui)
Definition at line 289 of file ui.c.
References NULL.
Referenced by meta_screen_free().
meta_ui_get_corner_radiuses()
void meta_ui_get_corner_radiuses (MetaUI * ui, Window xwindow, float * top_left, float * top_right, float * bottom_left, float * bottom_right)
Definition at line 310 of file ui.c.
References meta_frames_get_corner_radiuses().
Referenced by meta_frame_get_corner_radiuses().
meta_ui_get_default_mini_icon()
GdkPixbuf * meta_ui_get_default_mini_icon (MetaUI * ui)
Definition at line 635 of file ui.c.
References META_MINI_ICON_WIDTH, and NULL.
meta_ui_get_default_window_icon()
GdkPixbuf * meta_ui_get_default_window_icon (MetaUI * ui)
Definition at line 614 of file ui.c.
References meta_prefs_get_icon_size(), and NULL.
meta_ui_get_direction()
MetaUIDirection meta_ui_get_direction (void)
Definition at line 988 of file ui.c.
References META_UI_DIRECTION_LTR, and META_UI_DIRECTION_RTL.
Referenced by meta_fixed_tip_show(), meta_window_menu_popup(), meta_window_show_menu(), and meta_workspace_get_neighbor().
meta_ui_get_display()
Display * meta_ui_get_display (void)
Definition at line 68 of file ui.c.
meta_ui_get_drag_threshold()
int meta_ui_get_drag_threshold (MetaUI * ui)
Definition at line 978 of file ui.c.
References NULL.
meta_ui_get_frame_borders()
void meta_ui_get_frame_borders (MetaUI * ui, Window frame_xwindow, MetaFrameBorders * borders)
Definition at line 302 of file ui.c.
References meta_frames_get_borders().
Referenced by meta_frame_calc_borders().
meta_ui_get_frame_bounds()
cairo_region_t * meta_ui_get_frame_bounds (MetaUI * ui, Window xwindow, int window_width, int window_height)
Definition at line 474 of file ui.c.
References meta_frames_get_frame_bounds().
Referenced by meta_frame_get_frame_bounds().
meta_ui_get_mini_icon_from_desktop_id()
GdkPixbuf * meta_ui_get_mini_icon_from_desktop_id (MetaUI * ui, char * desktop_id)
Definition at line 693 of file ui.c.
References META_MINI_ICON_WIDTH.
Referenced by meta_read_icons().
meta_ui_get_pixbuf_from_surface()
GdkPixbuf * meta_ui_get_pixbuf_from_surface (cairo_surface_t * surface)
Definition at line 998 of file ui.c.
meta_ui_get_window_icon_from_desktop_id()
GdkPixbuf * meta_ui_get_window_icon_from_desktop_id (MetaUI * ui, char * desktop_id)
Definition at line 681 of file ui.c.
References meta_prefs_get_icon_size().
Referenced by meta_read_icons().
meta_ui_have_a_theme()
gboolean meta_ui_have_a_theme (void)
Definition at line 792 of file ui.c.
References meta_theme_get_current(), and NULL.
Referenced by main(), and meta_ui_theme_get_frame_borders().
meta_ui_init()
void meta_ui_init (int * argc, char *** argv)
Definition at line 52 of file ui.c.
References meta_fatal(), and NULL.
Referenced by main().
meta_ui_map_frame()
void meta_ui_map_frame (MetaUI * ui, Window xwindow)
Definition at line 417 of file ui.c.
meta_ui_move_resize_frame()
void meta_ui_move_resize_frame (MetaUI * ui, Window frame, int x, int y, int width, int height)
Definition at line 406 of file ui.c.
References meta_frames_move_resize_frame().
Referenced by meta_frame_sync_to_window().
meta_ui_new()
MetaUI * meta_ui_new (Display * xdisplay, Screen * screen)
Definition at line 260 of file ui.c.
References meta_frames_new().
Referenced by meta_screen_new().
meta_ui_parse_accelerator()
gboolean meta_ui_parse_accelerator (const char * accel, unsigned int * keysym, unsigned int * keycode, MetaVirtualModifier * mask)
Definition at line 814 of file ui.c.
References FALSE, mask, META_VIRTUAL_ALT_MASK, META_VIRTUAL_CONTROL_MASK, META_VIRTUAL_HYPER_MASK, META_VIRTUAL_META_MASK, META_VIRTUAL_MOD2_MASK, META_VIRTUAL_MOD3_MASK, META_VIRTUAL_MOD4_MASK, META_VIRTUAL_MOD5_MASK, META_VIRTUAL_SHIFT_MASK, META_VIRTUAL_SUPER_MASK, and TRUE.
meta_ui_parse_modifier()
gboolean meta_ui_parse_modifier (const char * accel, MetaVirtualModifier * mask)
Definition at line 905 of file ui.c.
References FALSE, mask, META_VIRTUAL_ALT_MASK, META_VIRTUAL_CONTROL_MASK, META_VIRTUAL_HYPER_MASK, META_VIRTUAL_META_MASK, META_VIRTUAL_MOD2_MASK, META_VIRTUAL_MOD3_MASK, META_VIRTUAL_MOD4_MASK, META_VIRTUAL_MOD5_MASK, META_VIRTUAL_SHIFT_MASK, META_VIRTUAL_SUPER_MASK, NULL, and TRUE.
meta_ui_pop_delay_exposes()
void meta_ui_pop_delay_exposes (MetaUI * ui)
Definition at line 594 of file ui.c.
References meta_frames_pop_delay_exposes().
Referenced by meta_effects_end_wireframe().
meta_ui_push_delay_exposes()
void meta_ui_push_delay_exposes (MetaUI * ui)
Definition at line 588 of file ui.c.
References meta_frames_push_delay_exposes().
Referenced by meta_effects_begin_wireframe().
meta_ui_queue_frame_draw()
void meta_ui_queue_frame_draw (MetaUI * ui, Window xwindow)
Definition at line 486 of file ui.c.
References meta_frames_queue_draw().
Referenced by meta_frame_queue_draw().
meta_ui_remove_event_func()
void meta_ui_remove_event_func (Display * xdisplay, MetaEventFunc func, gpointer data)
Definition at line 247 of file ui.c.
References data, and NULL.
Referenced by meta_display_close().
meta_ui_repaint_frame()
void meta_ui_repaint_frame (MetaUI * ui, Window xwindow)
Definition at line 454 of file ui.c.
References meta_frames_repaint_frame().
Referenced by meta_frame_sync_to_window().
meta_ui_set_current_theme()
void meta_ui_set_current_theme (const char * name, gboolean force_reload)
Definition at line 784 of file ui.c.
References meta_invalidate_default_icons(), meta_theme_set_current(), and name.
Referenced by main().
meta_ui_set_frame_title()
void meta_ui_set_frame_title (MetaUI * ui, Window xwindow, const char * title)
Definition at line 493 of file ui.c.
References meta_frames_set_title().
Referenced by meta_window_ensure_frame().
meta_ui_theme_get_frame_borders()
void meta_ui_theme_get_frame_borders (MetaUI * ui, MetaFrameType type, MetaFrameFlags flags, MetaFrameBorders * borders)
Definition at line 725 of file ui.c.
References meta_frame_borders_clear(), meta_pango_font_desc_get_text_height(), meta_prefs_get_titlebar_font(), meta_theme_get_current(), meta_theme_get_frame_borders(), meta_ui_have_a_theme(), and NULL.
meta_ui_unmap_frame()
void meta_ui_unmap_frame (MetaUI * ui, Window xwindow)
Definition at line 432 of file ui.c.
meta_ui_update_frame_style()
void meta_ui_update_frame_style (MetaUI * ui, Window window)
Definition at line 447 of file ui.c.
References meta_frames_update_frame_style().
Referenced by meta_window_ensure_frame().
meta_ui_window_is_widget()
gboolean meta_ui_window_is_widget (MetaUI * ui, Window xwindow)
Definition at line 952 of file ui.c.
References FALSE, NULL, and user_data.
Referenced by meta_display_process_key_event().
meta_ui_window_menu_free()
void meta_ui_window_menu_free (MetaWindowMenu * menu)
Definition at line 529 of file ui.c.
References meta_window_menu_free().
Referenced by meta_window_free(), and meta_window_show_menu().
meta_ui_window_menu_new()
MetaWindowMenu * meta_ui_window_menu_new (MetaUI * ui, Window client_xwindow, MetaMenuOp ops, MetaMenuOp insensitive, unsigned long active_workspace, int n_workspaces, MetaWindowMenuFunc func, gpointer data)
Definition at line 501 of file ui.c.
References data, and meta_window_menu_new().
Referenced by meta_window_show_menu().
meta_ui_window_menu_popup()
void meta_ui_window_menu_popup (MetaWindowMenu * menu, int root_x, int root_y, int button, guint32 timestamp)
Definition at line 519 of file ui.c.
References meta_window_menu_popup().
Referenced by meta_window_show_menu().
meta_ui_window_should_not_cause_focus()
gboolean meta_ui_window_should_not_cause_focus (Display * xdisplay, Window xwindow)
Definition at line 705 of file ui.c.
References FALSE, and TRUE.