MATE Desktop Environment: main.c File Reference
main.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include "main.h"
#include "util.h"
#include "display-private.h"
#include "errors.h"
#include "keybindings.h"
#include "ui.h"
#include "session.h"
#include "prefs.h"
#include "core.h"
#include <glib-object.h>
#include <glib/gprintf.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <stdio.h>
#include <string.h>
#include <signal.h>
#include <unistd.h>
#include <errno.h>
#include <fcntl.h>
#include <locale.h>
#include <time.h>
Macros
#define _GNU_SOURCE
#define _XOPEN_SOURCE /* for putenv() and some signal-related functions */
#define COMPOSITE_OPTS_FLAGS G_OPTION_FLAG_HIDDEN
Functions
int main (int argc, char **argv)
void meta_quit (MetaExitCode code)
void meta_restart (void)
Detailed Description
Program startup. Functions which parse the command-line arguments, create the display, kick everything off and then close down Marco when it's time to go.
Definition in file marco/src/core/main.c.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 44 of file marco/src/core/main.c.
_XOPEN_SOURCE
#define _XOPEN_SOURCE /* for putenv() and some signal-related functions */
Definition at line 45 of file marco/src/core/main.c.
COMPOSITE_OPTS_FLAGS
#define COMPOSITE_OPTS_FLAGS G_OPTION_FLAG_HIDDEN
Definition at line 222 of file marco/src/core/main.c.
Function Documentation
main()
int main (int argc, char ** argv)
This is where the story begins. It parses commandline options and environment variables, sets up the screen, hands control off to GTK, and cleans up afterwards.
Parameters
argc Number of arguments (as usual)
argv Array of arguments (as usual)
Definition at line 392 of file marco/src/core/main.c.
References _, FALSE, G_LOG_DOMAIN, GETTEXT_PACKAGE, meta_display_open(), meta_exit(), META_EXIT_ERROR, meta_fatal(), meta_prefs_add_listener(), meta_prefs_get_theme(), meta_prefs_init(), meta_prefs_set_force_compositing_manager(), meta_prefs_set_force_fullscreen(), meta_session_init(), meta_set_debugging(), meta_set_keybindings_disabled(), meta_set_replace_current_wm(), meta_set_syncing(), meta_set_verbose(), meta_ui_have_a_theme(), meta_ui_init(), meta_ui_set_current_theme(), meta_warning(), NULL, PACKAGE_STRING, and TRUE.
meta_quit()
void meta_quit (MetaExitCode code)
Stops Marco. This tells the event loop to stop processing; it is rather dangerous to use this rather than meta_restart() because this will leave the user with no window manager. We generally do this only if, for example, the session manager asks us to; we assume the session manager knows what it's talking about.
Parameters
code The success or failure code to return to the calling process.
Definition at line 605 of file marco/src/core/main.c.
Referenced by meta_display_close(), and meta_restart().
meta_restart()
void meta_restart (void)
Restarts Marco. In practice, this tells the event loop to stop processing, having first set the meta_restart_after_quit flag which tells Marco to spawn an identical copy of itself before quitting. This happens on receipt of a _MARCO_RESTART_MESSAGE client event.
Definition at line 620 of file marco/src/core/main.c.
References META_EXIT_SUCCESS, meta_quit(), and TRUE.