MATE Desktop Environment: main.h File Reference
main.h File Reference
#include <glib.h>
Enumerations
enum MetaExitCode { META_EXIT_SUCCESS , META_EXIT_ERROR }
Functions
void meta_exit (MetaExitCode code)
void meta_quit (MetaExitCode code)
void meta_restart (void)
Enumeration Type Documentation
MetaExitCode
enum MetaExitCode
Enumerator
META_EXIT_SUCCESS
META_EXIT_ERROR
Definition at line 29 of file marco/src/include/main.h.
Function Documentation
meta_exit()
void meta_exit (MetaExitCode code)
Definition at line 467 of file marco/src/core/util.c.
Referenced by main(), and meta_fatal().
meta_quit()
void meta_quit (MetaExitCode code)
Stops Marco. This tells the event loop to stop processing; it is rather dangerous to use this rather than meta_restart() because this will leave the user with no window manager. We generally do this only if, for example, the session manager asks us to; we assume the session manager knows what it's talking about.
Parameters
code The success or failure code to return to the calling process.
Definition at line 605 of file marco/src/core/main.c.
Referenced by meta_display_close(), and meta_restart().
meta_restart()
void meta_restart (void)
Restarts Marco. In practice, this tells the event loop to stop processing, having first set the meta_restart_after_quit flag which tells Marco to spawn an identical copy of itself before quitting. This happens on receipt of a _MARCO_RESTART_MESSAGE client event.
Definition at line 620 of file marco/src/core/main.c.
References META_EXIT_SUCCESS, meta_quit(), and TRUE.