MATE Desktop Environment: menu.h File Reference
menu.h File Reference
#include <gtk/gtk.h>
#include "frames.h"
Classes
struct _MetaWindowMenu
Macros
#define MARCO_STOCK_DELETE "window-close"
#define MARCO_STOCK_RESTORE "view-restore"
#define MARCO_STOCK_MINIMIZE "go-down"
#define MARCO_STOCK_MAXIMIZE "view-fullscreen"
Functions
MetaWindowMenu * meta_window_menu_new (MetaFrames *frames, MetaMenuOp ops, MetaMenuOp insensitive, Window client_xwindow, unsigned long active_workspace, int n_workspaces, MetaWindowMenuFunc func, gpointer data)
void meta_window_menu_popup (MetaWindowMenu *menu, int root_x, int root_y, int button, guint32 timestamp)
void meta_window_menu_free (MetaWindowMenu *menu)
Macro Definition Documentation
MARCO_STOCK_DELETE
#define MARCO_STOCK_DELETE "window-close"
Definition at line 29 of file marco/src/ui/menu.h.
MARCO_STOCK_MAXIMIZE
#define MARCO_STOCK_MAXIMIZE "view-fullscreen"
Definition at line 32 of file marco/src/ui/menu.h.
MARCO_STOCK_MINIMIZE
#define MARCO_STOCK_MINIMIZE "go-down"
Definition at line 31 of file marco/src/ui/menu.h.
MARCO_STOCK_RESTORE
#define MARCO_STOCK_RESTORE "view-restore"
Definition at line 30 of file marco/src/ui/menu.h.
Function Documentation
meta_window_menu_free()
void meta_window_menu_free (MetaWindowMenu * menu)
Definition at line 514 of file marco/src/ui/menu.c.
References _MetaWindowMenu::menu.
Referenced by meta_ui_window_menu_free().
meta_window_menu_new()
MetaWindowMenu * meta_window_menu_new (MetaFrames * frames, MetaMenuOp ops, MetaMenuOp insensitive, Window client_xwindow, unsigned long active_workspace, int n_workspaces, MetaWindowMenuFunc func, gpointer data)
Definition at line 296 of file marco/src/ui/menu.c.
References _MetaWindowMenu::client_xwindow, _MetaWindowMenu::data, data, FALSE, _MetaWindowMenu::frames, _MetaWindowMenu::func, _MetaWindowMenu::insensitive, int(), key, label, _MetaWindowMenu::menu, MENU_ITEM_NORMAL, MENU_ITEM_SEPARATOR, MENU_ITEM_WORKSPACE_LIST, meta_core_get_menu_accelerator(), META_MENU_OP_STICK, META_MENU_OP_UNSTICK, META_MENU_OP_WORKSPACES, N_, NULL, op, and _MetaWindowMenu::ops.
Referenced by meta_ui_window_menu_new().
meta_window_menu_popup()
void meta_window_menu_popup (MetaWindowMenu * menu, int root_x, int root_y, int button, guint32 timestamp)
Definition at line 472 of file marco/src/ui/menu.c.
References _MetaWindowMenu::frames, MAX, _MetaWindowMenu::menu, META_UI_DIRECTION_RTL, meta_ui_get_direction(), meta_warning(), and NULL.
Referenced by meta_ui_window_menu_popup().