MATE Desktop Environment: menu.c File Reference
menu.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include <libmate-desktop/mate-image-menu-item.h>
#include <gdk/gdkx.h>
#include <stdio.h>
#include <string.h>
#include "menu.h"
#include "main.h"
#include "util.h"
#include "core.h"
#include "metaaccellabel.h"
#include "ui.h"
Typedefs
typedef struct _MenuItem MenuItem
typedef struct _MenuData MenuData
Enumerations
enum MetaMenuItemType {
MENU_ITEM_SEPARATOR = 0 , MENU_ITEM_NORMAL , MENU_ITEM_IMAGE , MENU_ITEM_CHECKBOX ,
MENU_ITEM_RADIOBUTTON , MENU_ITEM_WORKSPACE_LIST
}
Functions
MetaWindowMenu * meta_window_menu_new (MetaFrames *frames, MetaMenuOp ops, MetaMenuOp insensitive, Window client_xwindow, unsigned long active_workspace, int n_workspaces, MetaWindowMenuFunc func, gpointer data)
void meta_window_menu_popup (MetaWindowMenu *menu, int root_x, int root_y, int button, guint32 timestamp)
void meta_window_menu_free (MetaWindowMenu *menu)
Typedef Documentation
MenuData
typedef struct _MenuData MenuData
Definition at line 40 of file marco/src/ui/menu.c.
MenuItem
typedef struct _MenuItem MenuItem
Definition at line 39 of file marco/src/ui/menu.c.
Enumeration Type Documentation
MetaMenuItemType
enum MetaMenuItemType
Enumerator
MENU_ITEM_SEPARATOR
MENU_ITEM_NORMAL
MENU_ITEM_IMAGE
MENU_ITEM_CHECKBOX
MENU_ITEM_RADIOBUTTON
MENU_ITEM_WORKSPACE_LIST
Definition at line 42 of file marco/src/ui/menu.c.
Function Documentation
meta_window_menu_free()
void meta_window_menu_free (MetaWindowMenu * menu)
Definition at line 514 of file marco/src/ui/menu.c.
References _MetaWindowMenu::menu.
Referenced by meta_ui_window_menu_free().
meta_window_menu_new()
MetaWindowMenu * meta_window_menu_new (MetaFrames * frames, MetaMenuOp ops, MetaMenuOp insensitive, Window client_xwindow, unsigned long active_workspace, int n_workspaces, MetaWindowMenuFunc func, gpointer data)
Definition at line 296 of file marco/src/ui/menu.c.
References _MetaWindowMenu::client_xwindow, _MetaWindowMenu::data, data, FALSE, _MetaWindowMenu::frames, _MetaWindowMenu::func, _MetaWindowMenu::insensitive, int(), key, label, _MetaWindowMenu::menu, MENU_ITEM_NORMAL, MENU_ITEM_SEPARATOR, MENU_ITEM_WORKSPACE_LIST, meta_core_get_menu_accelerator(), META_MENU_OP_STICK, META_MENU_OP_UNSTICK, META_MENU_OP_WORKSPACES, N_, NULL, op, and _MetaWindowMenu::ops.
Referenced by meta_ui_window_menu_new().
meta_window_menu_popup()
void meta_window_menu_popup (MetaWindowMenu * menu, int root_x, int root_y, int button, guint32 timestamp)
Definition at line 472 of file marco/src/ui/menu.c.
References _MetaWindowMenu::frames, MAX, _MetaWindowMenu::menu, META_UI_DIRECTION_RTL, meta_ui_get_direction(), meta_warning(), and NULL.
Referenced by meta_ui_window_menu_popup().