MATE Desktop Environment: stack.h File Reference
stack.h File Reference
#include <gtk/gtk.h>
#include "daemon.h"
Typedefs
typedef struct _NotifyStack NotifyStack
Enumerations
enum NotifyStackLocation {
NOTIFY_STACK_LOCATION_UNKNOWN = -1 , NOTIFY_STACK_LOCATION_TOP_LEFT , NOTIFY_STACK_LOCATION_TOP_RIGHT , NOTIFY_STACK_LOCATION_BOTTOM_LEFT ,
NOTIFY_STACK_LOCATION_BOTTOM_RIGHT , NOTIFY_STACK_LOCATION_DEFAULT = NOTIFY_STACK_LOCATION_BOTTOM_RIGHT
}
Functions
NotifyStack * notify_stack_new (NotifyDaemon *daemon, GdkScreen *screen, GdkMonitor *monitor, NotifyStackLocation stack_location)
void notify_stack_destroy (NotifyStack *stack)
void notify_stack_set_location (NotifyStack *stack, NotifyStackLocation location)
void notify_stack_add_window (NotifyStack *stack, GtkWindow *nw, gboolean new_notification)
void notify_stack_remove_window (NotifyStack *stack, GtkWindow *nw)
GList * notify_stack_get_windows (NotifyStack *stack)
GdkMonitor * notify_stack_get_monitor (NotifyStack *stack)
void notify_stack_queue_update_position (NotifyStack *stack)
Typedef Documentation
NotifyStack
typedef struct _NotifyStack NotifyStack
Definition at line 40 of file mate-notification-daemon/src/daemon/stack.h.
Enumeration Type Documentation
NotifyStackLocation
enum NotifyStackLocation
Enumerator
NOTIFY_STACK_LOCATION_UNKNOWN
NOTIFY_STACK_LOCATION_TOP_LEFT
NOTIFY_STACK_LOCATION_TOP_RIGHT
NOTIFY_STACK_LOCATION_BOTTOM_LEFT
NOTIFY_STACK_LOCATION_BOTTOM_RIGHT
NOTIFY_STACK_LOCATION_DEFAULT
Definition at line 31 of file mate-notification-daemon/src/daemon/stack.h.
Function Documentation
notify_stack_add_window()
void notify_stack_add_window (NotifyStack * stack, GtkWindow * nw, gboolean new_notification)
Definition at line 394 of file mate-notification-daemon/src/daemon/stack.c.
References notify_stack_remove_window(), NOTIFY_STACK_SPACING, NULL, and theme_move_notification().
notify_stack_destroy()
void notify_stack_destroy (NotifyStack * stack)
Definition at line 241 of file mate-notification-daemon/src/daemon/stack.c.
References g_signal_handlers_disconnect_by_data, and NULL.
notify_stack_get_monitor()
GdkMonitor * notify_stack_get_monitor (NotifyStack * stack)
Definition at line 53 of file mate-notification-daemon/src/daemon/stack.c.
notify_stack_get_windows()
GList * notify_stack_get_windows (NotifyStack * stack)
Definition at line 48 of file mate-notification-daemon/src/daemon/stack.c.
notify_stack_new()
NotifyStack * notify_stack_new (NotifyDaemon * daemon, GdkScreen * screen, GdkMonitor * monitor, NotifyStackLocation stack_location)
Definition at line 217 of file mate-notification-daemon/src/daemon/stack.c.
References NOTIFY_STACK_LOCATION_UNKNOWN, and NULL.
notify_stack_queue_update_position()
void notify_stack_queue_update_position (NotifyStack * stack)
Definition at line 384 of file mate-notification-daemon/src/daemon/stack.c.
notify_stack_remove_window()
void notify_stack_remove_window (NotifyStack * stack, GtkWindow * nw)
Definition at line 410 of file mate-notification-daemon/src/daemon/stack.c.
References NULL.
Referenced by notify_stack_add_window().
notify_stack_set_location()
void notify_stack_set_location (NotifyStack * stack, NotifyStackLocation location)
Definition at line 261 of file mate-notification-daemon/src/daemon/stack.c.