MATE Desktop Environment: matekbd-config-private.h File Reference
matekbd-config-private.h File Reference
#include "libmatekbd/matekbd-desktop-config.h"
#include "libmatekbd/matekbd-keyboard-config.h"
Macros
#define MATEKBD_CONFIG_SCHEMA "org.mate.peripherals-keyboard-xkb"
Functions
void matekbd_keyboard_config_model_set (MatekbdKeyboardConfig *kbd_config, const gchar *model_name)
void matekbd_keyboard_config_options_set (MatekbdKeyboardConfig *kbd_config, gint idx, const gchar *group_name, const gchar *option_name)
gboolean matekbd_keyboard_config_options_is_set (MatekbdKeyboardConfig *kbd_config, const gchar *group_name, const gchar *option_name)
gboolean matekbd_keyboard_config_dump_settings (MatekbdKeyboardConfig *kbd_config, const char *file_name)
gboolean matekbd_keyboard_config_get_lv_descriptions (XklConfigRegistry *config_registry, const gchar *layout_name, const gchar *variant_name, gchar **layout_short_descr, gchar **layout_descr, gchar **variant_short_descr, gchar **variant_descr)
Variables
const gchar MATEKBD_PREVIEW_CONFIG_KEY_X []
const gchar MATEKBD_PREVIEW_CONFIG_KEY_Y []
const gchar MATEKBD_PREVIEW_CONFIG_KEY_WIDTH []
const gchar MATEKBD_PREVIEW_CONFIG_KEY_HEIGHT []
Macro Definition Documentation
MATEKBD_CONFIG_SCHEMA
#define MATEKBD_CONFIG_SCHEMA "org.mate.peripherals-keyboard-xkb"
Definition at line 26 of file matekbd-config-private.h.
Function Documentation
matekbd_keyboard_config_dump_settings()
gboolean matekbd_keyboard_config_dump_settings (MatekbdKeyboardConfig * kbd_config, const char * file_name) extern
References config_registry.
matekbd_keyboard_config_get_lv_descriptions()
gboolean matekbd_keyboard_config_get_lv_descriptions (XklConfigRegistry * config_registry, const gchar * layout_name, const gchar * variant_name, gchar ** layout_short_descr, gchar ** layout_descr, gchar ** variant_short_descr, gchar ** variant_descr) extern
Definition at line 81 of file matekbd-keyboard-config.c.
References config_registry, and NULL.
Referenced by matekbd_keyboard_config_get_descriptions().
matekbd_keyboard_config_model_set()
void matekbd_keyboard_config_model_set (MatekbdKeyboardConfig * kbd_config, const gchar * model_name) extern
General config functions (private)
Definition at line 579 of file matekbd-keyboard-config.c.
References _MatekbdKeyboardConfig::model, and NULL.
Referenced by matekbd_keyboard_config_term().
matekbd_keyboard_config_options_is_set()
gboolean matekbd_keyboard_config_options_is_set (MatekbdKeyboardConfig * kbd_config, const gchar * group_name, const gchar * option_name) extern
Definition at line 606 of file matekbd-keyboard-config.c.
References FALSE, matekbd_keyboard_config_merge_items(), NULL, _MatekbdKeyboardConfig::options, and TRUE.
matekbd_keyboard_config_options_set()
void matekbd_keyboard_config_options_set (MatekbdKeyboardConfig * kbd_config, gint idx, const gchar * group_name, const gchar * option_name) extern
Definition at line 590 of file matekbd-keyboard-config.c.
References idx, matekbd_keyboard_config_merge_items(), NULL, and _MatekbdKeyboardConfig::options.
Variable Documentation
MATEKBD_PREVIEW_CONFIG_KEY_HEIGHT
const gchar MATEKBD_PREVIEW_CONFIG_KEY_HEIGHT[] extern
Definition at line 57 of file matekbd-util.c.
Referenced by matekbd_preview_load_position(), and matekbd_preview_save_position().
MATEKBD_PREVIEW_CONFIG_KEY_WIDTH
const gchar MATEKBD_PREVIEW_CONFIG_KEY_WIDTH[] extern
Definition at line 56 of file matekbd-util.c.
Referenced by matekbd_preview_load_position(), and matekbd_preview_save_position().
MATEKBD_PREVIEW_CONFIG_KEY_X
const gchar MATEKBD_PREVIEW_CONFIG_KEY_X[] extern
Definition at line 54 of file matekbd-util.c.
Referenced by matekbd_preview_load_position(), and matekbd_preview_save_position().
MATEKBD_PREVIEW_CONFIG_KEY_Y
const gchar MATEKBD_PREVIEW_CONFIG_KEY_Y[] extern
Definition at line 55 of file matekbd-util.c.
Referenced by matekbd_preview_load_position(), and matekbd_preview_save_position().