MATE Desktop Environment: eggdesktopfile.c File Reference
eggdesktopfile.c File Reference
#include "eggdesktopfile.h"
#include <string.h>
#include <unistd.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
Functions
EggDesktopFile * egg_desktop_file_new (const char *desktop_file_path, GError **error)
EggDesktopFile * egg_desktop_file_new_from_data_dirs (const char *desktop_file_path, GError **error)
EggDesktopFile * egg_desktop_file_new_from_dirs (const char *desktop_file_path, const char **search_dirs, GError **error)
EggDesktopFile * egg_desktop_file_new_from_key_file (GKeyFile *key_file, const char *source, GError **error)
void egg_desktop_file_free (EggDesktopFile *desktop_file)
const char * egg_desktop_file_get_source (EggDesktopFile *desktop_file)
EggDesktopFileType egg_desktop_file_get_desktop_file_type (EggDesktopFile *desktop_file)
const char * egg_desktop_file_get_name (EggDesktopFile *desktop_file)
const char * egg_desktop_file_get_icon (EggDesktopFile *desktop_file)
gboolean egg_desktop_file_has_key (EggDesktopFile *desktop_file, const char *key, GError **error)
char * egg_desktop_file_get_string (EggDesktopFile *desktop_file, const char *key, GError **error)
char * egg_desktop_file_get_locale_string (EggDesktopFile *desktop_file, const char *key, const char *locale, GError **error)
gboolean egg_desktop_file_get_boolean (EggDesktopFile *desktop_file, const char *key, GError **error)
double egg_desktop_file_get_numeric (EggDesktopFile *desktop_file, const char *key, GError **error)
int egg_desktop_file_get_integer (EggDesktopFile *desktop_file, const char *key, GError **error)
char ** egg_desktop_file_get_string_list (EggDesktopFile *desktop_file, const char *key, gsize *length, GError **error)
char ** egg_desktop_file_get_locale_string_list (EggDesktopFile *desktop_file, const char *key, const char *locale, gsize *length, GError **error)
gboolean egg_desktop_file_can_launch (EggDesktopFile *desktop_file, const char *desktop_environment)
gboolean egg_desktop_file_accepts_documents (EggDesktopFile *desktop_file)
gboolean egg_desktop_file_accepts_multiple (EggDesktopFile *desktop_file)
gboolean egg_desktop_file_accepts_uris (EggDesktopFile *desktop_file)
char * egg_desktop_file_parse_exec (EggDesktopFile *desktop_file, GSList *documents, GError **error)
gboolean egg_desktop_file_launch (EggDesktopFile *desktop_file, GSList *documents, GError **error,...)
GQuark egg_desktop_file_error_quark (void)
G_LOCK_DEFINE_STATIC (egg_desktop_file)
void egg_set_desktop_file (const char *desktop_file_path)
void egg_set_desktop_file_without_defaults (const char *desktop_file_path)
EggDesktopFile * egg_get_desktop_file (void)
Function Documentation
egg_desktop_file_accepts_documents()
gboolean egg_desktop_file_accepts_documents (EggDesktopFile * desktop_file)
egg_desktop_file_accepts_documents: @desktop_file: an EggDesktopFile
Tests if @desktop_file represents an application that can accept documents on the command line.
Return value: TRUE or FALSE
Definition at line 575 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
egg_desktop_file_accepts_multiple()
gboolean egg_desktop_file_accepts_multiple (EggDesktopFile * desktop_file)
egg_desktop_file_accepts_multiple: @desktop_file: an EggDesktopFile
Tests if @desktop_file can accept multiple documents at once.
If this returns FALSE, you can still pass multiple documents to egg_desktop_file_launch(), but that will result in multiple copies of the application being launched. See egg_desktop_file_launch() for more details.
Return value: TRUE or FALSE
Definition at line 594 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
egg_desktop_file_accepts_uris()
gboolean egg_desktop_file_accepts_uris (EggDesktopFile * desktop_file)
egg_desktop_file_accepts_uris: @desktop_file: an EggDesktopFile
Tests if @desktop_file can accept (non-"file:") URIs as documents to open.
Return value: TRUE or FALSE
Definition at line 610 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
egg_desktop_file_can_launch()
gboolean egg_desktop_file_can_launch (EggDesktopFile * desktop_file, const char * desktop_environment)
egg_desktop_file_can_launch: @desktop_file: an EggDesktopFile @desktop_environment: the name of the running desktop environment, or NULL
Tests if @desktop_file can/should be launched in the current environment. If @desktop_environment is non-NULL, @desktop_file's "OnlyShowIn" and "NotShowIn" keys are checked to make sure that this desktop_file is appropriate for the named environment.
Furthermore, if @desktop_file has type EGG_DESKTOP_FILE_TYPE_APPLICATION, its "TryExec" key (if any) is also checked, to make sure the binary it points to exists.
egg_desktop_file_can_launch() does NOT check the value of the "Hidden" key.
Return value: TRUE if @desktop_file can be launched
Definition at line 494 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
References EGG_DESKTOP_FILE_GROUP, EGG_DESKTOP_FILE_KEY_NOT_SHOW_IN, EGG_DESKTOP_FILE_KEY_ONLY_SHOW_IN, EGG_DESKTOP_FILE_KEY_TRY_EXEC, EGG_DESKTOP_FILE_TYPE_APPLICATION, EGG_DESKTOP_FILE_TYPE_LINK, FALSE, NULL, and TRUE.
egg_desktop_file_error_quark()
GQuark egg_desktop_file_error_quark (void)
Definition at line 1432 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
egg_desktop_file_free()
void egg_desktop_file_free (EggDesktopFile * desktop_file)
egg_desktop_file_free: @desktop_file: an EggDesktopFile
Frees @desktop_file.
Definition at line 316 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
Referenced by egg_desktop_file_launch(), and egg_desktop_file_new_from_key_file().
egg_desktop_file_get_boolean()
gboolean egg_desktop_file_get_boolean (EggDesktopFile * desktop_file, const char * key, GError ** error)
Definition at line 420 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
References EGG_DESKTOP_FILE_GROUP, error, and key.
egg_desktop_file_get_desktop_file_type()
EggDesktopFileType egg_desktop_file_get_desktop_file_type (EggDesktopFile * desktop_file)
egg_desktop_file_get_desktop_file_type: @desktop_file: an EggDesktopFile
Gets the desktop file type of @desktop_file.
Return value: @desktop_file's type
Definition at line 348 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
egg_desktop_file_get_icon()
const char * egg_desktop_file_get_icon (EggDesktopFile * desktop_file)
egg_desktop_file_get_icon: @desktop_file: an EggDesktopFile
Gets the value of @desktop_file's "Icon" key.
If the icon string is a full path (that is, if g_path_is_absolute() returns TRUE when called on it), it points to a file containing an unthemed icon. If the icon string is not a full path, it is the name of a themed icon, which can be looked up with GtkIconTheme, or passed directly to a theme-aware widget like GtkImage or GtkCellRendererPixbuf.
Return value: the icon path or name
Definition at line 383 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
egg_desktop_file_get_integer()
int egg_desktop_file_get_integer (EggDesktopFile * desktop_file, const char * key, GError ** error)
Definition at line 440 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
References EGG_DESKTOP_FILE_GROUP, error, and key.
egg_desktop_file_get_locale_string()
char * egg_desktop_file_get_locale_string (EggDesktopFile * desktop_file, const char * key, const char * locale, GError ** error)
Definition at line 409 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
References EGG_DESKTOP_FILE_GROUP, error, and key.
egg_desktop_file_get_locale_string_list()
char ** egg_desktop_file_get_locale_string_list (EggDesktopFile * desktop_file, const char * key, const char * locale, gsize * length, GError ** error)
Definition at line 461 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
References EGG_DESKTOP_FILE_GROUP, error, and key.
egg_desktop_file_get_name()
const char * egg_desktop_file_get_name (EggDesktopFile * desktop_file)
egg_desktop_file_get_name: @desktop_file: an EggDesktopFile
Gets the (localized) value of @desktop_file's "Name" key.
Return value: the application/link name
Definition at line 362 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
egg_desktop_file_get_numeric()
double egg_desktop_file_get_numeric (EggDesktopFile * desktop_file, const char * key, GError ** error)
Definition at line 430 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
References EGG_DESKTOP_FILE_GROUP, error, and key.
egg_desktop_file_get_source()
const char * egg_desktop_file_get_source (EggDesktopFile * desktop_file)
egg_desktop_file_get_source: @desktop_file: an EggDesktopFile
Gets the URI that @desktop_file was loaded from.
Return value: @desktop_file's source URI
Definition at line 334 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
egg_desktop_file_get_string()
char * egg_desktop_file_get_string (EggDesktopFile * desktop_file, const char * key, GError ** error)
Definition at line 399 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
References EGG_DESKTOP_FILE_GROUP, error, and key.
egg_desktop_file_get_string_list()
char ** egg_desktop_file_get_string_list (EggDesktopFile * desktop_file, const char * key, gsize * length, GError ** error)
Definition at line 450 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
References EGG_DESKTOP_FILE_GROUP, error, and key.
egg_desktop_file_has_key()
gboolean egg_desktop_file_has_key (EggDesktopFile * desktop_file, const char * key, GError ** error)
Definition at line 389 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
References EGG_DESKTOP_FILE_GROUP, error, and key.
egg_desktop_file_launch()
gboolean egg_desktop_file_launch (EggDesktopFile * desktop_file, GSList * documents, GError ** error, ...)
egg_desktop_file_launch: @desktop_file: an EggDesktopFile @documents: a list of URIs or paths to documents to open @error: error pointer ...: additional options
Launches @desktop_file with the given arguments. Additional options can be specified as follows:
EGG_DESKTOP_FILE_LAUNCH_CLEARENV: (no arguments) clears the environment in the child process EGG_DESKTOP_FILE_LAUNCH_PUTENV: (char **variables) adds the NAME=VALUE strings in the given NULL-terminated array to the child process's environment EGG_DESKTOP_FILE_LAUNCH_SCREEN: (GdkScreen *screen) causes the application to be launched on the given screen EGG_DESKTOP_FILE_LAUNCH_WORKSPACE: (int workspace) causes the application to be launched on the given workspace EGG_DESKTOP_FILE_LAUNCH_DIRECTORY: (char *dir) causes the application to be launched in the given directory EGG_DESKTOP_FILE_LAUNCH_TIME: (guint32 launch_time) sets the "launch time" for the application. If the user interacts with another window after @launch_time but before the launched application creates its first window, the window manager may choose to not give focus to the new application. Passing 0 for @launch_time will explicitly request that the application not receive focus. EGG_DESKTOP_FILE_LAUNCH_FLAGS (GSpawnFlags flags) Sets additional #GSpawnFlags to use. See g_spawn_async() for more details. EGG_DESKTOP_FILE_LAUNCH_SETUP_FUNC (GSpawnChildSetupFunc, gpointer) Sets the child setup callback and the data to pass to it. (See g_spawn_async() for more details.)
EGG_DESKTOP_FILE_LAUNCH_RETURN_PID (GPid **pid) On a successful launch, sets *@pid to the PID of the launched application. EGG_DESKTOP_FILE_LAUNCH_RETURN_STARTUP_ID (char **startup_id) On a successful launch, sets *@startup_id to the Startup Notification "startup id" of the launched application. EGG_DESKTOP_FILE_LAUNCH_RETURN_STDIN_PIPE (int *fd) On a successful launch, sets *@fd to the file descriptor of a pipe connected to the application's stdin. EGG_DESKTOP_FILE_LAUNCH_RETURN_STDOUT_PIPE (int *fd) On a successful launch, sets *@fd to the file descriptor of a pipe connected to the application's stdout. EGG_DESKTOP_FILE_LAUNCH_RETURN_STDERR_PIPE (int *fd) On a successful launch, sets *@fd to the file descriptor of a pipe connected to the application's stderr.
The options should be terminated with a single NULL.
If @documents contains multiple documents, but egg_desktop_file_accepts_multiple() returns FALSE for @desktop_file, then egg_desktop_file_launch() will actually launch multiple instances of the application. In that case, the return value (as well as any values passed via EGG_DESKTOP_FILE_LAUNCH_RETURN_PID, etc) will only reflect the first instance of the application that was launched (but the EGG_DESKTOP_FILE_LAUNCH_SETUP_FUNC will be called for each instance).
Return value: TRUE if the application was successfully launched.
Definition at line 1379 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
References _, EGG_DESKTOP_FILE_ERROR, EGG_DESKTOP_FILE_ERROR_NOT_LAUNCHABLE, egg_desktop_file_free(), EGG_DESKTOP_FILE_TYPE_APPLICATION, EGG_DESKTOP_FILE_TYPE_DIRECTORY, EGG_DESKTOP_FILE_TYPE_LINK, EGG_DESKTOP_FILE_TYPE_UNRECOGNIZED, error, and FALSE.
egg_desktop_file_new()
EggDesktopFile * egg_desktop_file_new (const char * desktop_file_path, GError ** error)
egg_desktop_file_new: @desktop_file_path: path to a Freedesktop-style Desktop file @error: error pointer
Creates a new EggDesktopFile for @desktop_file.
Return value: the new EggDesktopFile, or NULL on error.
Definition at line 59 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
References egg_desktop_file_new_from_key_file(), error, and NULL.
egg_desktop_file_new_from_data_dirs()
EggDesktopFile * egg_desktop_file_new_from_data_dirs (const char * desktop_file_path, GError ** error)
egg_desktop_file_new_from_data_dirs: @desktop_file_path: relative path to a Freedesktop-style Desktop file @error: error pointer
Looks for @desktop_file_path in the paths returned from g_get_user_data_dir() and g_get_system_data_dirs(), and creates a new EggDesktopFile from it.
Return value: the new EggDesktopFile, or NULL on error.
Definition at line 86 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
References egg_desktop_file_new_from_key_file(), error, and NULL.
egg_desktop_file_new_from_dirs()
EggDesktopFile * egg_desktop_file_new_from_dirs (const char * desktop_file_path, const char ** search_dirs, GError ** error)
egg_desktop_file_new_from_dirs: @desktop_file_path: relative path to a Freedesktop-style Desktop file @search_dirs: NULL-terminated array of directories to search @error: error pointer
Looks for @desktop_file_path in the paths returned from g_get_user_data_dir() and g_get_system_data_dirs(), and creates a new EggDesktopFile from it.
Return value: the new EggDesktopFile, or NULL on error.
Definition at line 121 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
References egg_desktop_file_new_from_key_file(), error, and NULL.
egg_desktop_file_new_from_key_file()
EggDesktopFile * egg_desktop_file_new_from_key_file (GKeyFile * key_file, const char * source, GError ** error)
egg_desktop_file_new_from_key_file: @key_file: a #GKeyFile representing a desktop file @source: the path or URI that @key_file was loaded from, or NULL @error: error pointer
Creates a new EggDesktopFile for @key_file. Assumes ownership of @key_file (on success or failure); you should consider @key_file to be freed after calling this function.
Return value: the new EggDesktopFile, or NULL on error.
Definition at line 157 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
References _, EGG_DESKTOP_FILE_ERROR, EGG_DESKTOP_FILE_ERROR_INVALID, egg_desktop_file_free(), EGG_DESKTOP_FILE_GROUP, EGG_DESKTOP_FILE_KEY_EXEC, EGG_DESKTOP_FILE_KEY_ICON, EGG_DESKTOP_FILE_KEY_NAME, EGG_DESKTOP_FILE_KEY_TYPE, EGG_DESKTOP_FILE_KEY_URL, EGG_DESKTOP_FILE_KEY_VERSION, EGG_DESKTOP_FILE_TYPE_APPLICATION, EGG_DESKTOP_FILE_TYPE_DIRECTORY, EGG_DESKTOP_FILE_TYPE_LINK, EGG_DESKTOP_FILE_TYPE_UNRECOGNIZED, error, NULL, strchr, and strrchr.
Referenced by egg_desktop_file_new(), egg_desktop_file_new_from_data_dirs(), and egg_desktop_file_new_from_dirs().
egg_desktop_file_parse_exec()
char * egg_desktop_file_parse_exec (EggDesktopFile * desktop_file, GSList * documents, GError ** error)
egg_desktop_file_parse_exec: @desktop_file: a EggDesktopFile @documents: a list of document paths or URIs @error: error pointer
Parses @desktop_file's Exec key, inserting @documents into it, and returns the result.
If @documents contains non-file: URIs and @desktop_file does not accept URIs, those URIs will be ignored. Likewise, if @documents contains more elements than @desktop_file accepts, the extra documents will be ignored.
Return value: the parsed Exec string
Definition at line 881 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
References error.
egg_get_desktop_file()
EggDesktopFile * egg_get_desktop_file (void)
egg_get_desktop_file:
Gets the application's EggDesktopFile, as set by egg_set_desktop_file().
Return value: the EggDesktopFile, or NULL if it hasn't been set.
Definition at line 1529 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
egg_set_desktop_file()
void egg_set_desktop_file (const char * desktop_file_path)
egg_set_desktop_file: @desktop_file_path: path to the application's desktop file
Creates an EggDesktopFile for the application from the data at @desktop_file_path. This will also call g_set_application_name() with the localized application name from the desktop file, and gtk_window_set_default_icon_name() or gtk_window_set_default_icon_from_file() with the application's icon. Other code may use additional information from the desktop file. See egg_set_desktop_file_without_defaults() for a variant of this function that does not set the application name and default window icon.
Note that for thread safety reasons, this function can only be called once, and is mutually exclusive with calling egg_set_desktop_file_without_defaults().
Definition at line 1495 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
References TRUE.
egg_set_desktop_file_without_defaults()
void egg_set_desktop_file_without_defaults (const char * desktop_file_path)
egg_set_desktop_file_without_defaults: @desktop_file_path: path to the application's desktop file
Creates an EggDesktopFile for the application from the data at @desktop_file_path. See egg_set_desktop_file() for a variant of this function that sets the application name and default window icon from the information in the desktop file.
Note that for thread safety reasons, this function can only be called once, and is mutually exclusive with calling egg_set_desktop_file().
Definition at line 1515 of file mate-session-manager/mate-submodules/libegg/eggdesktopfile.c.
References FALSE.
G_LOCK_DEFINE_STATIC()
G_LOCK_DEFINE_STATIC (egg_desktop_file)
References error, and NULL.