MATE Desktop Environment: mate-mouse-properties.c File Reference
mate-mouse-properties.c File Reference
#include <config.h>
#include <glib/gi18n.h>
#include <string.h>
#include <gio/gio.h>
#include <gdk/gdkx.h>
#include <math.h>
#include "capplet-util.h"
#include "activate-settings-daemon.h"
#include "msd-input-helper.h"
#include <X11/Xatom.h>
#include <X11/extensions/XInput.h>
Macros
#define MOUSE_SCHEMA "org.mate.peripherals-mouse"
#define INTERFACE_SCHEMA "org.mate.interface"
#define DOUBLE_CLICK_KEY "double-click"
#define TOUCHPAD_SCHEMA "org.mate.peripherals-touchpad"
Enumerations
enum { DOUBLE_CLICK_TEST_OFF , DOUBLE_CLICK_TEST_MAYBE , DOUBLE_CLICK_TEST_ON }
enum AccelProfile { ACCEL_PROFILE_DEFAULT , ACCEL_PROFILE_ADAPTIVE , ACCEL_PROFILE_FLAT }
Functions
int main (int argc, char **argv)
Macro Definition Documentation
DOUBLE_CLICK_KEY
#define DOUBLE_CLICK_KEY "double-click"
Definition at line 56 of file mate-mouse-properties.c.
INTERFACE_SCHEMA
#define INTERFACE_SCHEMA "org.mate.interface"
Definition at line 55 of file mate-mouse-properties.c.
MOUSE_SCHEMA
#define MOUSE_SCHEMA "org.mate.peripherals-mouse"
Definition at line 54 of file mate-mouse-properties.c.
TOUCHPAD_SCHEMA
#define TOUCHPAD_SCHEMA "org.mate.peripherals-touchpad"
Definition at line 58 of file mate-mouse-properties.c.
Referenced by main().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DOUBLE_CLICK_TEST_OFF
DOUBLE_CLICK_TEST_MAYBE
DOUBLE_CLICK_TEST_ON
Definition at line 41 of file mate-mouse-properties.c.
AccelProfile
enum AccelProfile
Enumerator
ACCEL_PROFILE_DEFAULT
ACCEL_PROFILE_ADAPTIVE
ACCEL_PROFILE_FLAT
Definition at line 48 of file mate-mouse-properties.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 401 of file mate-mouse-properties.c.
References _, activate_settings_daemon(), capplet_init(), capplet_notebook_scroll_event_cb(), capplet_set_icon(), GETTEXT_PACKAGE, INTERFACE_SCHEMA, MOUSE_SCHEMA, N_, NULL, TOUCHPAD_SCHEMA, and WID.