MATE Desktop Environment: mate-languages.c File Reference
mate-languages.c File Reference
#include "config.h"
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <dirent.h>
#include <locale.h>
#include <langinfo.h>
#include <sys/stat.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <glib/gstdio.h>
#include "mate-languages.h"
Macros
#define MATE_DESKTOP_USE_UNSTABLE_API
#define __LC_LAST 13
#define ISO_CODES_DATADIR ISO_CODES_PREFIX "/share/xml/iso-codes"
#define ISO_CODES_LOCALESDIR ISO_CODES_PREFIX "/share/locale"
Typedefs
typedef struct _MateLocale MateLocale
Functions
gboolean mate_parse_locale (const char *locale, char **language_codep, char **country_codep, char **codesetp, char **modifierp)
.
mate_normalize_locale: @locale: a locale string
Gets the normalized locale string in the form [language[_country][.codeset][@modifier]] for
Return value: (transfer full): normalized locale string. Caller takes ownership.
Since: 1.22
char * mate_normalize_locale (const char *locale)
Macro Definition Documentation
__LC_LAST
#define __LC_LAST 13
Definition at line 44 of file mate-languages.c.
ISO_CODES_DATADIR
#define ISO_CODES_DATADIR ISO_CODES_PREFIX "/share/xml/iso-codes"
Definition at line 47 of file mate-languages.c.
ISO_CODES_LOCALESDIR
#define ISO_CODES_LOCALESDIR ISO_CODES_PREFIX "/share/locale"
Definition at line 48 of file mate-languages.c.
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 39 of file mate-languages.c.
Typedef Documentation
MateLocale
typedef struct _MateLocale MateLocale
Function Documentation
mate_normalize_locale()
char * mate_normalize_locale (const char * locale)
Definition at line 260 of file mate-languages.c.
References mate_parse_locale(), modifier, and NULL.
Referenced by test_one_locale().
mate_parse_locale()
gboolean mate_parse_locale (const char * locale, char ** language_codep, char ** country_codep, char ** codesetp, char ** modifierp)
mate_parse_locale: @locale: a locale string @language_codep: (out) (allow-none) (transfer full): location to store the language code, or NULL @country_codep: (out) (allow-none) (transfer full): location to store the country code, or NULL @codesetp: (out) (allow-none) (transfer full): location to store the codeset, or NULL @modifierp: (out) (allow-none) (transfer full): location to store the modifier, or NULL
Extracts the various components of a locale string of the form [language[_country][.codeset][@modifier]]. See http://en.wikipedia.org/wiki/Locale.
Return value: TRUE if parsing was successful.
Since: 1.22
Definition at line 122 of file mate-languages.c.
References error, FALSE, NULL, and TRUE.
Referenced by mate_normalize_locale(), and test_one_locale().