MATE Desktop Environment: matekbd-util.h File Reference
matekbd-util.h File Reference
#include <glib.h>
#include <gdk/gdk.h>
Functions
void matekbd_install_glib_log_appender (void)
GdkRectangle * matekbd_preview_load_position (void)
void matekbd_preview_save_position (GdkRectangle *rect)
gchar ** matekbd_strv_append (gchar **arr, gchar *element)
Function Documentation
matekbd_install_glib_log_appender()
void matekbd_install_glib_log_appender (void) extern
Definition at line 47 of file matekbd-util.c.
matekbd_preview_load_position()
GdkRectangle * matekbd_preview_load_position (void) extern
matekbd_preview_load_position:
Returns: (transfer full): A rectangle to use
Definition at line 65 of file matekbd-util.c.
References MATEKBD_PREVIEW_CONFIG_KEY_HEIGHT, MATEKBD_PREVIEW_CONFIG_KEY_WIDTH, MATEKBD_PREVIEW_CONFIG_KEY_X, MATEKBD_PREVIEW_CONFIG_KEY_Y, MATEKBD_PREVIEW_CONFIG_SCHEMA, and NULL.
Referenced by matekbd_keyboard_drawing_new_dialog(), and xkb_layout_choose().
matekbd_preview_save_position()
void matekbd_preview_save_position (GdkRectangle * rect) extern
Definition at line 99 of file matekbd-util.c.
References MATEKBD_PREVIEW_CONFIG_KEY_HEIGHT, MATEKBD_PREVIEW_CONFIG_KEY_WIDTH, MATEKBD_PREVIEW_CONFIG_KEY_X, MATEKBD_PREVIEW_CONFIG_KEY_Y, and MATEKBD_PREVIEW_CONFIG_SCHEMA.
matekbd_strv_append()
gchar ** matekbd_strv_append (gchar ** arr, gchar * element) extern
matekbd_strv_append:
Returns: (transfer full) (array zero-terminated=1): Append string to strv array
Definition at line 121 of file matekbd-util.c.
References memcpy, and NULL.
Referenced by matekbd_keyboard_config_add_default_switch_option_if_necessary().