MATE Desktop Environment: mate-ui-menu.c File Reference
mate-ui-menu.c File Reference
#include "config.h"
#include "mate-ui-menu.h"
Functions
GtkWidget * mate_ui_menu_item_new_with_action (const gchar *label, const gchar *action_name, GtkAccelGroup *accel_group, const gchar *accel)
GtkWidget * mate_ui_menu_item_new_with_icon (const gchar *label, const gchar *icon_name, const gchar *action_name)
GtkWidget * mate_ui_menu_new_from_entries (const MateUiMenuEntry *entries, gsize n_entries, GtkAccelGroup *accel_group)
GtkWidget * mate_ui_menu_bar_new_from_entries (const MateUiSubmenu *submenus, gsize n_submenus, GtkAccelGroup *accel_group)
GMenuModel * mate_ui_menu_model_new_from_entries (const MateUiSubmenu *submenus, gsize n_submenus)
GtkWidget * mate_ui_menu_add_recent_chooser (GtkMenu *menu, const gchar *label, GtkRecentFilter *filter, GCallback callback, gpointer user_data)
void mate_ui_popup_menu_at_pointer (GtkMenu *menu, const GdkEvent *event)
void mate_ui_popup_menu_at_widget (GtkMenu *menu, GtkWidget *widget, GdkGravity widget_anchor, GdkGravity menu_anchor)
GtkWidget * mate_ui_context_menu_new (void)
GtkWidget * mate_ui_context_menu_add_item (GtkMenu *menu, const gchar *label, GCallback callback, gpointer user_data)
void mate_ui_context_menu_add_separator (GtkMenu *menu)
Function Documentation
mate_ui_context_menu_add_item()
GtkWidget * mate_ui_context_menu_add_item (GtkMenu * menu, const gchar * label, GCallback callback, gpointer user_data)
mate_ui_context_menu_add_item: @menu: A #GtkMenu @label: The item label @callback: Activation callback @user_data: User data for callback
Adds an item to a context menu.
Returns: (transfer none): The new menu item
Definition at line 389 of file mate-ui-menu.c.
References item, label, NULL, and user_data.
mate_ui_context_menu_add_separator()
void mate_ui_context_menu_add_separator (GtkMenu * menu)
mate_ui_context_menu_add_separator: @menu: A #GtkMenu
Adds a separator to a context menu.
Definition at line 417 of file mate-ui-menu.c.
mate_ui_context_menu_new()
GtkWidget * mate_ui_context_menu_new (void)
mate_ui_context_menu_new:
Creates a new context menu (GtkMenu).
Returns: (transfer full): A new #GtkMenu
Definition at line 372 of file mate-ui-menu.c.
mate_ui_menu_add_recent_chooser()
GtkWidget * mate_ui_menu_add_recent_chooser (GtkMenu * menu, const gchar * label, GtkRecentFilter * filter, GCallback callback, gpointer user_data)
mate_ui_menu_add_recent_chooser: @menu: A #GtkMenu @label: The submenu label @filter: (nullable): A #GtkRecentFilter or NULL @callback: Callback when a recent item is activated @user_data: User data for callback
Adds a recent files submenu to the given menu.
Returns: (transfer none): The recent chooser menu item
Definition at line 289 of file mate-ui-menu.c.
References FALSE, item, label, NULL, TRUE, and user_data.
mate_ui_menu_bar_new_from_entries()
GtkWidget * mate_ui_menu_bar_new_from_entries (const MateUiSubmenu * submenus, gsize n_submenus, GtkAccelGroup * accel_group)
mate_ui_menu_bar_new_from_entries: @submenus: Array of MateUiSubmenu structures @n_submenus: Number of submenus @accel_group: (nullable): Accelerator group to attach, or NULL
Creates a GtkMenuBar from an array of submenu definitions.
Returns: (transfer full): A new #GtkMenuBar
Definition at line 163 of file mate-ui-menu.c.
References MateUiSubmenu::entries, MateUiSubmenu::label, mate_ui_menu_new_from_entries(), MateUiSubmenu::n_entries, and NULL.
mate_ui_menu_item_new_with_action()
GtkWidget * mate_ui_menu_item_new_with_action (const gchar * label, const gchar * action_name, GtkAccelGroup * accel_group, const gchar * accel)
mate_ui_menu_item_new_with_action: @label: The menu item label @action_name: The action name @accel_group: (nullable): Accelerator group @accel: (nullable): Accelerator string (e.g., "<Control>s")
Creates a menu item connected to an action with optional accelerator.
Returns: (transfer full): A new #GtkMenuItem
Definition at line 27 of file mate-ui-menu.c.
References item, key, label, and NULL.
Referenced by mate_ui_menu_new_from_entries().
mate_ui_menu_item_new_with_icon()
GtkWidget * mate_ui_menu_item_new_with_icon (const gchar * label, const gchar * icon_name, const gchar * action_name)
mate_ui_menu_item_new_with_icon: @label: The menu item label @icon_name: The icon name @action_name: The action name
Creates a menu item with an icon.
Returns: (transfer full): A new #GtkMenuItem with icon
Definition at line 64 of file mate-ui-menu.c.
References FALSE, item, label, NULL, and TRUE.
Referenced by mate_ui_menu_new_from_entries().
mate_ui_menu_model_new_from_entries()
GMenuModel * mate_ui_menu_model_new_from_entries (const MateUiSubmenu * submenus, gsize n_submenus)
mate_ui_menu_model_new_from_entries: @submenus: Array of MateUiSubmenu structures @n_submenus: Number of submenus
Creates a GMenuModel from an array of submenu definitions.
Returns: (transfer full): A new #GMenuModel
Definition at line 198 of file mate-ui-menu.c.
References MateUiMenuEntry::accel, MateUiMenuEntry::action_name, MateUiSubmenu::entries, MateUiMenuEntry::icon_name, item, label, MateUiMenuEntry::label, MateUiSubmenu::label, MateUiSubmenu::n_entries, and NULL.
mate_ui_menu_new_from_entries()
GtkWidget * mate_ui_menu_new_from_entries (const MateUiMenuEntry * entries, gsize n_entries, GtkAccelGroup * accel_group)
mate_ui_menu_new_from_entries: @entries: Array of MateUiMenuEntry structures @n_entries: Number of entries @accel_group: (nullable): Accelerator group to attach, or NULL
Creates a GtkMenu from an array of menu entry definitions.
Returns: (transfer full): A new #GtkMenu
Definition at line 102 of file mate-ui-menu.c.
References MateUiMenuEntry::accel, MateUiMenuEntry::action_name, MateUiMenuEntry::icon_name, item, key, MateUiMenuEntry::label, mate_ui_menu_item_new_with_action(), mate_ui_menu_item_new_with_icon(), and NULL.
Referenced by mate_ui_menu_bar_new_from_entries().
mate_ui_popup_menu_at_pointer()
void mate_ui_popup_menu_at_pointer (GtkMenu * menu, const GdkEvent * event)
mate_ui_popup_menu_at_pointer: @menu: A #GtkMenu @event: (nullable): The triggering event or NULL
Shows a popup menu at the pointer position.
Definition at line 335 of file mate-ui-menu.c.
mate_ui_popup_menu_at_widget()
void mate_ui_popup_menu_at_widget (GtkMenu * menu, GtkWidget * widget, GdkGravity widget_anchor, GdkGravity menu_anchor)
mate_ui_popup_menu_at_widget: @menu: A #GtkMenu @widget: The widget to popup at @widget_anchor: Anchor point on widget @menu_anchor: Anchor point on menu
Shows a popup menu anchored to a widget.
Definition at line 353 of file mate-ui-menu.c.
References NULL.