MATE Desktop Environment: mate-panel-applet.c File Reference
mate-panel-applet.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <cairo.h>
#include <gdk/gdk.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <gdk/gdkwayland.h>
#include "mate-panel-applet.h"
#include "panel-applet-private.h"
#include "mate-panel-applet-factory.h"
#include "mate-panel-applet-marshal.h"
#include "mate-panel-applet-enums.h"
Macros
#define GDK_IS_X11_DISPLAY(object)
#define MATE_PANEL_APPLET_INTERFACE "org.mate.panel.applet.Applet"
#define MATE_PANEL_APPLET_OBJECT_PATH "/org/mate/panel/applet/%s/%d"
Enumerations
enum {
CHANGE_ORIENT , CHANGE_SIZE , CHANGE_BACKGROUND , MOVE_FOCUS_OUT_OF_APPLET ,
ACTIVATE , LAST_SIGNAL
}
enum {
PROP_0 , PROP_OUT_OF_PROCESS , PROP_ID , PROP_CLOSURE ,
PROP_CONNECTION , PROP_PREFS_PATH , PROP_ORIENT , PROP_SIZE ,
PROP_BACKGROUND , PROP_FLAGS , PROP_SIZE_HINTS , PROP_LOCKED ,
PROP_LOCKED_DOWN
}
Functions
void _mate_panel_applet_apply_css (GtkWidget *widget, MatePanelAppletBackgroundType type)
char * mate_panel_applet_get_preferences_path (MatePanelApplet *applet)
MatePanelAppletFlags mate_panel_applet_get_flags (MatePanelApplet *applet)
void mate_panel_applet_set_flags (MatePanelApplet *applet, MatePanelAppletFlags flags)
void mate_panel_applet_set_size_hints (MatePanelApplet *applet, const int *size_hints, int n_elements, int base_size)
guint mate_panel_applet_get_size (MatePanelApplet *applet)
MatePanelAppletOrient mate_panel_applet_get_orient (MatePanelApplet *applet)
gboolean mate_panel_applet_get_locked_down (MatePanelApplet *applet)
void mate_panel_applet_request_focus (MatePanelApplet *applet, guint32 timestamp)
void mate_panel_applet_setup_menu (MatePanelApplet *applet, const gchar *xml, GtkActionGroup *applet_action_group)
void mate_panel_applet_setup_menu_from_file (MatePanelApplet *applet, const gchar *filename, GtkActionGroup *applet_action_group)
void mate_panel_applet_setup_menu_from_resource (MatePanelApplet *applet, const gchar *resource_path, GtkActionGroup *action_group)
MatePanelAppletBackgroundType mate_panel_applet_get_background (MatePanelApplet *applet, GdkRGBA *color, cairo_pattern_t **pattern)
GtkWidget * mate_panel_applet_new (void)
int mate_panel_applet_factory_main (const gchar *factory_id, gboolean out_process, GType applet_type, MatePanelAppletFactoryCallback callback, gpointer user_data)
int mate_panel_applet_factory_setup_in_process (const gchar *factory_id, GType applet_type, MatePanelAppletFactoryCallback callback, gpointer user_data)
void mate_panel_applet_set_background_widget (MatePanelApplet *applet, GtkWidget *widget)
guint32 mate_panel_applet_get_xid (MatePanelApplet *applet, GdkScreen *screen)
const gchar * mate_panel_applet_get_object_path (MatePanelApplet *applet)
G_MODULE_EXPORT GtkWidget * mate_panel_applet_get_applet_widget (const gchar *factory_id, guint uid)
Macro Definition Documentation
GDK_IS_X11_DISPLAY
#define GDK_IS_X11_DISPLAY (object)
Value:
!(G_TYPE_CHECK_INSTANCE_TYPE ((object), GDK_TYPE_WAYLAND_DISPLAY))
Definition at line 50 of file mate-panel-applet.c.
MATE_PANEL_APPLET_INTERFACE
#define MATE_PANEL_APPLET_INTERFACE "org.mate.panel.applet.Applet"
Definition at line 162 of file mate-panel-applet.c.
Referenced by mate_panel_applet_container_child_popup_menu(), mate_panel_applet_set_flags(), and mate_panel_applet_set_size_hints().
MATE_PANEL_APPLET_OBJECT_PATH
#define MATE_PANEL_APPLET_OBJECT_PATH "/org/mate/panel/applet/%s/%d"
Definition at line 163 of file mate-panel-applet.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CHANGE_ORIENT
CHANGE_SIZE
CHANGE_BACKGROUND
MOVE_FOCUS_OUT_OF_APPLET
ACTIVATE
LAST_SIGNAL
Definition at line 92 of file mate-panel-applet.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_OUT_OF_PROCESS
PROP_ID
PROP_CLOSURE
PROP_CONNECTION
PROP_PREFS_PATH
PROP_ORIENT
PROP_SIZE
PROP_BACKGROUND
PROP_FLAGS
PROP_SIZE_HINTS
PROP_LOCKED
PROP_LOCKED_DOWN
Definition at line 103 of file mate-panel-applet.c.
Function Documentation
_mate_panel_applet_apply_css()
void _mate_panel_applet_apply_css (GtkWidget * widget, MatePanelAppletBackgroundType type)
Definition at line 1847 of file mate-panel-applet.c.
References PANEL_COLOR_BACKGROUND, PANEL_NO_BACKGROUND, and PANEL_PIXMAP_BACKGROUND.
mate_panel_applet_factory_main()
int mate_panel_applet_factory_main (const gchar * factory_id, gboolean out_process, GType applet_type, MatePanelAppletFactoryCallback callback, gpointer user_data)
mate_panel_applet_factory_main: @out_process: boolean, dummy to support applets sending it @factory_id: Factory ID. @applet_type: GType of the applet this factory creates. @callback: (scope call): Callback to be called when a new applet is to be created. @data: (closure): Callback data.
Returns: 0 on success, 1 if there is an error.
Definition at line 2505 of file mate-panel-applet.c.
References applet_type, TRUE, and user_data.
mate_panel_applet_factory_setup_in_process()
int mate_panel_applet_factory_setup_in_process (const gchar * factory_id, GType applet_type, MatePanelAppletFactoryCallback callback, gpointer user_data)
mate_panel_applet_factory_setup_in_process: (skip) @factory_id: Factory ID. @applet_type: GType of the applet this factory creates. @callback: (scope call): Callback to be called when a new applet is to be created. @data: (closure): Callback data.
Returns: 0 on success, 1 if there is an error.
Definition at line 2525 of file mate-panel-applet.c.
References applet_type, FALSE, and user_data.
mate_panel_applet_get_applet_widget()
G_MODULE_EXPORT GtkWidget * mate_panel_applet_get_applet_widget (const gchar * factory_id, guint uid)
Definition at line 2585 of file mate-panel-applet.c.
References mate_panel_applet_factory_get_applet_widget(), and NULL.
mate_panel_applet_get_background()
MatePanelAppletBackgroundType mate_panel_applet_get_background (MatePanelApplet * applet, GdkRGBA * color, cairo_pattern_t ** pattern)
Definition at line 1495 of file mate-panel-applet.c.
References NULL, and PANEL_NO_BACKGROUND.
mate_panel_applet_get_flags()
MatePanelAppletFlags mate_panel_applet_get_flags (MatePanelApplet * applet)
Definition at line 200 of file mate-panel-applet.c.
References MATE_PANEL_APPLET_FLAGS_NONE.
mate_panel_applet_get_locked_down()
gboolean mate_panel_applet_get_locked_down (MatePanelApplet * applet)
Definition at line 481 of file mate-panel-applet.c.
References FALSE.
Referenced by mateweather_applet_create(), stickynotes_applet_new(), window_list_applet_fill(), and workspace_switcher_applet_fill().
mate_panel_applet_get_object_path()
const gchar * mate_panel_applet_get_object_path (MatePanelApplet * applet)
Definition at line 2575 of file mate-panel-applet.c.
mate_panel_applet_get_orient()
MatePanelAppletOrient mate_panel_applet_get_orient (MatePanelApplet * applet)
Definition at line 400 of file mate-panel-applet.c.
Referenced by active_sensor_new(), build_table(), gvc_applet_fill(), load_graph_new(), mateweather_applet_create(), multiload_applet_refresh(), multiload_properties_cb(), sensors_applet_graph_size_changed(), show_desktop_applet_fill(), stickynotes_applet_new(), window_list_applet_fill(), window_menu_applet_fill(), and workspace_switcher_applet_fill().
mate_panel_applet_get_preferences_path()
char * mate_panel_applet_get_preferences_path (MatePanelApplet * applet)
Definition at line 166 of file mate-panel-applet.c.
References NULL.
Referenced by mate_panel_applet_settings_new(), sensors_applet_add_sensor(), sensors_applet_settings_load_sensors(), and sensors_applet_settings_save_sensors().
mate_panel_applet_get_size()
guint mate_panel_applet_get_size (MatePanelApplet * applet)
Definition at line 366 of file mate-panel-applet.c.
Referenced by gvc_applet_fill(), load_graph_new(), mateweather_applet_create(), show_desktop_applet_fill(), stickynotes_applet_init(), stickynotes_applet_new(), window_list_applet_fill(), and window_menu_applet_fill().
mate_panel_applet_get_xid()
guint32 mate_panel_applet_get_xid (MatePanelApplet * applet, GdkScreen * screen)
Definition at line 2553 of file mate-panel-applet.c.
References FALSE.
mate_panel_applet_new()
GtkWidget * mate_panel_applet_new (void)
Definition at line 2176 of file mate-panel-applet.c.
References NULL, and PANEL_TYPE_APPLET.
mate_panel_applet_request_focus()
void mate_panel_applet_request_focus (MatePanelApplet * applet, guint32 timestamp)
Definition at line 607 of file mate-panel-applet.c.
References GDK_IS_X11_DISPLAY.
mate_panel_applet_set_background_widget()
void mate_panel_applet_set_background_widget (MatePanelApplet * applet, GtkWidget * widget)
mate_panel_applet_set_background_widget: @applet: a #PanelApplet. @widget: a #GtkWidget.
Configure #PanelApplet to automatically draw the background of the applet on @widget. It is generally enough to call this function with @applet as @widget.
Deprecated: 3.20: Do not use this API. Since 3.20 this function does nothing.
Definition at line 2547 of file mate-panel-applet.c.
Referenced by sensors_applet_init().
mate_panel_applet_set_flags()
void mate_panel_applet_set_flags (MatePanelApplet * applet, MatePanelAppletFlags flags)
Definition at line 212 of file mate-panel-applet.c.
References error, MATE_PANEL_APPLET_INTERFACE, and NULL.
Referenced by gvc_applet_fill(), mateweather_applet_create(), sensors_applet_init(), show_desktop_applet_fill(), stickynotes_applet_new(), window_list_applet_fill(), window_menu_applet_fill(), and workspace_switcher_applet_fill().
mate_panel_applet_set_size_hints()
void mate_panel_applet_set_size_hints (MatePanelApplet * applet, const int * size_hints, int n_elements, int base_size)
mate_panel_applet_set_size_hints: @applet: applet @size_hints: (array length=n_elements): List of integers @n_elements: Length of @size_hints @base_size: base_size
Definition at line 308 of file mate-panel-applet.c.
References error, MATE_PANEL_APPLET_INTERFACE, and NULL.
mate_panel_applet_setup_menu()
void mate_panel_applet_setup_menu (MatePanelApplet * applet, const gchar * xml, GtkActionGroup * applet_action_group)
Definition at line 747 of file mate-panel-applet.c.
References error, and NULL.
Referenced by gvc_applet_fill(), mate_panel_applet_setup_menu_from_file(), and mate_panel_applet_setup_menu_from_resource().
mate_panel_applet_setup_menu_from_file()
void mate_panel_applet_setup_menu_from_file (MatePanelApplet * applet, const gchar * filename, GtkActionGroup * applet_action_group)
Definition at line 780 of file mate-panel-applet.c.
References error, mate_panel_applet_setup_menu(), and NULL.
Referenced by sensors_applet_init().
mate_panel_applet_setup_menu_from_resource()
void mate_panel_applet_setup_menu_from_resource (MatePanelApplet * applet, const gchar * resource_path, GtkActionGroup * action_group)
mate_panel_applet_setup_menu_from_resource: @applet: a #MatePanelApplet. @resource_path: a resource path @action_group: a #GtkActionGroup.
Sets up the context menu of @applet. @filename is a resource path to a menu XML file, containing a #GtkUIManager UI definition that describes how to display the menu items. @action_group contains the various #GtkAction that are referenced in @xml.
See also the <link linkend="getting-started.context-menu">Context Menu</link> section.
Since: 1.20.1
Definition at line 814 of file mate-panel-applet.c.
References error, mate_panel_applet_setup_menu(), and NULL.
Referenced by mateweather_applet_create(), show_desktop_applet_fill(), stickynotes_applet_new(), window_list_applet_fill(), window_menu_applet_fill(), and workspace_switcher_applet_fill().