MATE Desktop Environment: matekbd-indicator-config.h File Reference
matekbd-indicator-config.h File Reference
#include <gtk/gtk.h>
#include "libmatekbd/matekbd-keyboard-config.h"
Classes
struct _MatekbdIndicatorConfig
Typedefs
typedef struct _MatekbdIndicatorConfig MatekbdIndicatorConfig
Functions
void matekbd_indicator_config_init (MatekbdIndicatorConfig *applet_config, XklEngine *engine)
void matekbd_indicator_config_term (MatekbdIndicatorConfig *applet_config)
void matekbd_indicator_config_load_from_gsettings (MatekbdIndicatorConfig *applet_config)
void matekbd_indicator_config_save_to_gsettings (MatekbdIndicatorConfig *applet_config)
void matekbd_indicator_config_refresh_style (MatekbdIndicatorConfig *applet_config)
gchar * matekbd_indicator_config_get_images_file (MatekbdIndicatorConfig *applet_config, MatekbdKeyboardConfig *kbd_config, int group)
void matekbd_indicator_config_load_image_filenames (MatekbdIndicatorConfig *applet_config, MatekbdKeyboardConfig *kbd_config)
void matekbd_indicator_config_free_image_filenames (MatekbdIndicatorConfig *applet_config)
void matekbd_indicator_config_activate (MatekbdIndicatorConfig *applet_config)
void matekbd_indicator_config_start_listen (MatekbdIndicatorConfig *applet_config, GCallback func, gpointer user_data)
void matekbd_indicator_config_stop_listen (MatekbdIndicatorConfig *applet_config)
Typedef Documentation
MatekbdIndicatorConfig
typedef struct _MatekbdIndicatorConfig MatekbdIndicatorConfig
Definition at line 30 of file matekbd-indicator-config.h.
Function Documentation
matekbd_indicator_config_activate()
void matekbd_indicator_config_activate (MatekbdIndicatorConfig * applet_config) extern
Definition at line 311 of file matekbd-indicator-config.c.
References _MatekbdIndicatorConfig::engine, and _MatekbdIndicatorConfig::secondary_groups_mask.
matekbd_indicator_config_free_image_filenames()
void matekbd_indicator_config_free_image_filenames (MatekbdIndicatorConfig * applet_config) extern
Definition at line 213 of file matekbd-indicator-config.c.
References _MatekbdIndicatorConfig::image_filenames.
Referenced by matekbd_indicator_config_term().
matekbd_indicator_config_get_images_file()
gchar * matekbd_indicator_config_get_images_file (MatekbdIndicatorConfig * applet_config, MatekbdKeyboardConfig * kbd_config, int group) extern
Definition at line 140 of file matekbd-indicator-config.c.
References _MatekbdIndicatorConfig::icon_theme, _MatekbdKeyboardConfig::layouts_variants, matekbd_keyboard_config_split_items(), NULL, and _MatekbdIndicatorConfig::show_flags.
Referenced by matekbd_indicator_config_load_image_filenames(), matekbd_indicator_get_image_filename(), and matekbd_status_get_image_filename().
matekbd_indicator_config_init()
void matekbd_indicator_config_init (MatekbdIndicatorConfig * applet_config, XklEngine * engine) extern
Definition at line 226 of file matekbd-indicator-config.c.
References DATADIR, _MatekbdIndicatorConfig::engine, engine, _MatekbdIndicatorConfig::icon_theme, MATEKBD_INDICATOR_CONFIG_SCHEMA, NULL, and _MatekbdIndicatorConfig::settings.
matekbd_indicator_config_load_from_gsettings()
void matekbd_indicator_config_load_from_gsettings (MatekbdIndicatorConfig * applet_config) extern
Definition at line 280 of file matekbd-indicator-config.c.
References MATEKBD_INDICATOR_CONFIG_KEY_SECONDARIES, MATEKBD_INDICATOR_CONFIG_KEY_SHOW_FLAGS, _MatekbdIndicatorConfig::secondary_groups_mask, _MatekbdIndicatorConfig::settings, and _MatekbdIndicatorConfig::show_flags.
matekbd_indicator_config_load_image_filenames()
void matekbd_indicator_config_load_image_filenames (MatekbdIndicatorConfig * applet_config, MatekbdKeyboardConfig * kbd_config) extern
Definition at line 189 of file matekbd-indicator-config.c.
References _MatekbdIndicatorConfig::engine, _MatekbdIndicatorConfig::image_filenames, matekbd_indicator_config_get_images_file(), NULL, and _MatekbdIndicatorConfig::show_flags.
Referenced by matekbd_indicator_load_images().
matekbd_indicator_config_refresh_style()
void matekbd_indicator_config_refresh_style (MatekbdIndicatorConfig * applet_config) extern
Definition at line 130 of file matekbd-indicator-config.c.
References _MatekbdIndicatorConfig::background_color, _MatekbdIndicatorConfig::font_family, and _MatekbdIndicatorConfig::foreground_color.
matekbd_indicator_config_save_to_gsettings()
void matekbd_indicator_config_save_to_gsettings (MatekbdIndicatorConfig * applet_config) extern
Definition at line 296 of file matekbd-indicator-config.c.
References MATEKBD_INDICATOR_CONFIG_KEY_SECONDARIES, MATEKBD_INDICATOR_CONFIG_KEY_SHOW_FLAGS, _MatekbdIndicatorConfig::secondary_groups_mask, _MatekbdIndicatorConfig::settings, and _MatekbdIndicatorConfig::show_flags.
matekbd_indicator_config_start_listen()
void matekbd_indicator_config_start_listen (MatekbdIndicatorConfig * ind_config, GCallback func, gpointer user_data) extern
matekbd_indicator_config_start_listen: @func: (scope notified): a function to call when settings are changed
Definition at line 322 of file matekbd-indicator-config.c.
References _MatekbdIndicatorConfig::config_listener_id, _MatekbdIndicatorConfig::settings, and user_data.
matekbd_indicator_config_stop_listen()
void matekbd_indicator_config_stop_listen (MatekbdIndicatorConfig * applet_config) extern
Definition at line 333 of file matekbd-indicator-config.c.
References _MatekbdIndicatorConfig::config_listener_id, and _MatekbdIndicatorConfig::settings.
matekbd_indicator_config_term()
void matekbd_indicator_config_term (MatekbdIndicatorConfig * applet_config) extern
Definition at line 260 of file matekbd-indicator-config.c.
References _MatekbdIndicatorConfig::background_color, _MatekbdIndicatorConfig::font_family, _MatekbdIndicatorConfig::foreground_color, _MatekbdIndicatorConfig::icon_theme, matekbd_indicator_config_free_image_filenames(), NULL, and _MatekbdIndicatorConfig::settings.