MATE Desktop Environment: matekbd-keyboard-drawing.h File Reference
matekbd-keyboard-drawing.h File Reference
#include <gtk/gtk.h>
#include <X11/XKBlib.h>
#include <X11/extensions/XKBgeom.h>
Classes
struct _MatekbdKeyboardDrawingItem
struct _MatekbdKeyboardDrawingKey
struct _MatekbdKeyboardDrawingDoodad
struct _MatekbdKeyboardDrawingGroupLevel
struct _MatekbdKeyboardDrawingRenderContext
struct _MatekbdKeyboardDrawing
struct _MatekbdKeyboardDrawingClass
Macros
#define MATEKBD_KEYBOARD_DRAWING(obj)
#define MATEKBD_KEYBOARD_DRAWING_CLASS(clazz)
#define MATEKBD_IS_KEYBOARD_DRAWING(obj)
Typedefs
typedef struct _MatekbdKeyboardDrawing MatekbdKeyboardDrawing
typedef struct _MatekbdKeyboardDrawingClass MatekbdKeyboardDrawingClass
typedef struct _MatekbdKeyboardDrawingItem MatekbdKeyboardDrawingItem
typedef struct _MatekbdKeyboardDrawingKey MatekbdKeyboardDrawingKey
typedef struct _MatekbdKeyboardDrawingDoodad MatekbdKeyboardDrawingDoodad
typedef struct _MatekbdKeyboardDrawingGroupLevel MatekbdKeyboardDrawingGroupLevel
typedef struct _MatekbdKeyboardDrawingRenderContext MatekbdKeyboardDrawingRenderContext
Enumerations
enum MatekbdKeyboardDrawingItemType { MATEKBD_KEYBOARD_DRAWING_ITEM_TYPE_INVALID = 0 , MATEKBD_KEYBOARD_DRAWING_ITEM_TYPE_KEY , MATEKBD_KEYBOARD_DRAWING_ITEM_TYPE_KEY_EXTRA , MATEKBD_KEYBOARD_DRAWING_ITEM_TYPE_DOODAD }
enum MatekbdKeyboardDrawingGroupLevelPosition {
MATEKBD_KEYBOARD_DRAWING_POS_TOPLEFT , MATEKBD_KEYBOARD_DRAWING_POS_TOPRIGHT , MATEKBD_KEYBOARD_DRAWING_POS_BOTTOMLEFT , MATEKBD_KEYBOARD_DRAWING_POS_BOTTOMRIGHT ,
MATEKBD_KEYBOARD_DRAWING_POS_TOTAL , MATEKBD_KEYBOARD_DRAWING_POS_FIRST , MATEKBD_KEYBOARD_DRAWING_POS_LAST
}
Functions
GType matekbd_keyboard_drawing_get_type (void)
GtkWidget * matekbd_keyboard_drawing_new (void)
gboolean matekbd_keyboard_drawing_render (MatekbdKeyboardDrawing *kbdrawing, cairo_t *cr, PangoLayout *layout, double x, double y, double width, double height, gdouble dpi_x, gdouble dpi_y)
gboolean matekbd_keyboard_drawing_set_keyboard (MatekbdKeyboardDrawing *kbdrawing, XkbComponentNamesRec *names)
const gchar * matekbd_keyboard_drawing_get_keycodes (MatekbdKeyboardDrawing *kbdrawing)
const gchar * matekbd_keyboard_drawing_get_geometry (MatekbdKeyboardDrawing *kbdrawing)
const gchar * matekbd_keyboard_drawing_get_symbols (MatekbdKeyboardDrawing *kbdrawing)
const gchar * matekbd_keyboard_drawing_get_types (MatekbdKeyboardDrawing *kbdrawing)
const gchar * matekbd_keyboard_drawing_get_compat (MatekbdKeyboardDrawing *kbdrawing)
void matekbd_keyboard_drawing_set_track_modifiers (MatekbdKeyboardDrawing *kbdrawing, gboolean enable)
void matekbd_keyboard_drawing_set_track_config (MatekbdKeyboardDrawing *kbdrawing, gboolean enable)
void matekbd_keyboard_drawing_set_groups_levels (MatekbdKeyboardDrawing *kbdrawing, MatekbdKeyboardDrawingGroupLevel *groupLevels[])
void matekbd_keyboard_drawing_print (MatekbdKeyboardDrawing *drawing, GtkWindow *parent_window, const gchar *description)
GtkWidget * matekbd_keyboard_drawing_new_dialog (gint group, gchar *group_name)
Macro Definition Documentation
MATEKBD_IS_KEYBOARD_DRAWING
#define MATEKBD_IS_KEYBOARD_DRAWING (obj)
Value:
G_TYPE_CHECK_INSTANCE_TYPE ((obj), matekbd_keyboard_drawing_get_type ())
Definition at line 34 of file matekbd-keyboard-drawing.h.
MATEKBD_KEYBOARD_DRAWING
#define MATEKBD_KEYBOARD_DRAWING (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), matekbd_keyboard_drawing_get_type (), \
MatekbdKeyboardDrawing))
Definition at line 30 of file matekbd-keyboard-drawing.h.
Referenced by main(), matekbd_keyboard_drawing_new_dialog(), xkb_layout_preview_create_widget(), and xkb_layout_preview_set_drawing_layout().
MATEKBD_KEYBOARD_DRAWING_CLASS
#define MATEKBD_KEYBOARD_DRAWING_CLASS (clazz)
Value:
(G_TYPE_CHECK_CLASS_CAST ((clazz), matekbd_keyboard_drawing_get_type () \
MatekbdKeyboardDrawingClass))
Definition at line 32 of file matekbd-keyboard-drawing.h.
Typedef Documentation
MatekbdKeyboardDrawing
typedef struct _MatekbdKeyboardDrawing MatekbdKeyboardDrawing
Definition at line 35 of file matekbd-keyboard-drawing.h.
MatekbdKeyboardDrawingClass
typedef struct _MatekbdKeyboardDrawingClass MatekbdKeyboardDrawingClass
Definition at line 36 of file matekbd-keyboard-drawing.h.
MatekbdKeyboardDrawingDoodad
typedef struct _MatekbdKeyboardDrawingDoodad MatekbdKeyboardDrawingDoodad
Definition at line 40 of file matekbd-keyboard-drawing.h.
MatekbdKeyboardDrawingGroupLevel
typedef struct _MatekbdKeyboardDrawingGroupLevel MatekbdKeyboardDrawingGroupLevel
Definition at line 42 of file matekbd-keyboard-drawing.h.
MatekbdKeyboardDrawingItem
typedef struct _MatekbdKeyboardDrawingItem MatekbdKeyboardDrawingItem
Definition at line 38 of file matekbd-keyboard-drawing.h.
MatekbdKeyboardDrawingKey
typedef struct _MatekbdKeyboardDrawingKey MatekbdKeyboardDrawingKey
Definition at line 39 of file matekbd-keyboard-drawing.h.
MatekbdKeyboardDrawingRenderContext
typedef struct _MatekbdKeyboardDrawingRenderContext MatekbdKeyboardDrawingRenderContext
Definition at line 44 of file matekbd-keyboard-drawing.h.
Enumeration Type Documentation
MatekbdKeyboardDrawingGroupLevelPosition
enum MatekbdKeyboardDrawingGroupLevelPosition
Enumerator
MATEKBD_KEYBOARD_DRAWING_POS_TOPLEFT
MATEKBD_KEYBOARD_DRAWING_POS_TOPRIGHT
MATEKBD_KEYBOARD_DRAWING_POS_BOTTOMLEFT
MATEKBD_KEYBOARD_DRAWING_POS_BOTTOMRIGHT
MATEKBD_KEYBOARD_DRAWING_POS_TOTAL
MATEKBD_KEYBOARD_DRAWING_POS_FIRST
MATEKBD_KEYBOARD_DRAWING_POS_LAST
Definition at line 53 of file matekbd-keyboard-drawing.h.
MatekbdKeyboardDrawingItemType
enum MatekbdKeyboardDrawingItemType
Enumerator
MATEKBD_KEYBOARD_DRAWING_ITEM_TYPE_INVALID
MATEKBD_KEYBOARD_DRAWING_ITEM_TYPE_KEY
MATEKBD_KEYBOARD_DRAWING_ITEM_TYPE_KEY_EXTRA
MATEKBD_KEYBOARD_DRAWING_ITEM_TYPE_DOODAD
Definition at line 46 of file matekbd-keyboard-drawing.h.
Function Documentation
matekbd_keyboard_drawing_get_compat()
const gchar * matekbd_keyboard_drawing_get_compat (MatekbdKeyboardDrawing * kbdrawing)
Definition at line 2588 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::display, NULL, and _MatekbdKeyboardDrawing::xkb.
matekbd_keyboard_drawing_get_geometry()
const gchar * matekbd_keyboard_drawing_get_geometry (MatekbdKeyboardDrawing * kbdrawing)
Definition at line 2552 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::display, NULL, and _MatekbdKeyboardDrawing::xkb.
Referenced by main().
matekbd_keyboard_drawing_get_keycodes()
const gchar * matekbd_keyboard_drawing_get_keycodes (MatekbdKeyboardDrawing * kbdrawing)
Definition at line 2540 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::display, NULL, and _MatekbdKeyboardDrawing::xkb.
Referenced by main().
matekbd_keyboard_drawing_get_symbols()
const gchar * matekbd_keyboard_drawing_get_symbols (MatekbdKeyboardDrawing * kbdrawing)
Definition at line 2564 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::display, NULL, and _MatekbdKeyboardDrawing::xkb.
Referenced by main().
matekbd_keyboard_drawing_get_type()
GType matekbd_keyboard_drawing_get_type (void)
Definition at line 2377 of file matekbd-keyboard-drawing.c.
References NULL.
Referenced by matekbd_keyboard_drawing_new().
matekbd_keyboard_drawing_get_types()
const gchar * matekbd_keyboard_drawing_get_types (MatekbdKeyboardDrawing * kbdrawing)
Definition at line 2576 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::display, NULL, and _MatekbdKeyboardDrawing::xkb.
matekbd_keyboard_drawing_new()
GtkWidget * matekbd_keyboard_drawing_new (void)
Definition at line 2352 of file matekbd-keyboard-drawing.c.
References matekbd_keyboard_drawing_get_type(), and NULL.
Referenced by main(), matekbd_keyboard_drawing_new_dialog(), and xkb_layout_preview_create_widget().
matekbd_keyboard_drawing_new_dialog()
GtkWidget * matekbd_keyboard_drawing_new_dialog (gint group, gchar * group_name)
Definition at line 2776 of file matekbd-keyboard-drawing.c.
References _, engine, error, MATEKBD_KEYBOARD_DRAWING, matekbd_keyboard_drawing_new(), matekbd_keyboard_drawing_set_groups_levels(), matekbd_keyboard_drawing_set_keyboard(), matekbd_preview_load_position(), NULL, TRUE, xkl_xkb_config_native_cleanup(), and xkl_xkb_config_native_prepare().
matekbd_keyboard_drawing_print()
void matekbd_keyboard_drawing_print (MatekbdKeyboardDrawing * drawing, GtkWindow * parent_window, const gchar * description)
Definition at line 2710 of file matekbd-keyboard-drawing.c.
References data, and NULL.
matekbd_keyboard_drawing_render()
gboolean matekbd_keyboard_drawing_render (MatekbdKeyboardDrawing * kbdrawing, cairo_t * cr, PangoLayout * layout, double x, double y, double width, double height, gdouble dpi_x, gdouble dpi_y)
matekbd_keyboard_drawing_set_groups_levels()
void matekbd_keyboard_drawing_set_groups_levels (MatekbdKeyboardDrawing * kbdrawing, MatekbdKeyboardDrawingGroupLevel * groupLevels[])
Definition at line 2626 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::groupLevels, level, MATEKBD_KEYBOARD_DRAWING_POS_BOTTOMLEFT, MATEKBD_KEYBOARD_DRAWING_POS_BOTTOMRIGHT, MATEKBD_KEYBOARD_DRAWING_POS_TOPLEFT, and MATEKBD_KEYBOARD_DRAWING_POS_TOPRIGHT.
Referenced by main(), matekbd_keyboard_drawing_new_dialog(), and xkb_layout_preview_create_widget().
matekbd_keyboard_drawing_set_keyboard()
gboolean matekbd_keyboard_drawing_set_keyboard (MatekbdKeyboardDrawing * drawing, XkbComponentNamesRec * names)
matekbd_keyboard_drawing_set_keyboard: (skip)
Definition at line 2488 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::display, FALSE, NULL, TRUE, _MatekbdKeyboardDrawing::xkb, and _MatekbdKeyboardDrawing::xkbOnDisplay.
Referenced by main(), matekbd_keyboard_drawing_new_dialog(), and xkb_layout_preview_set_drawing_layout().
matekbd_keyboard_drawing_set_track_config()
void matekbd_keyboard_drawing_set_track_config (MatekbdKeyboardDrawing * kbdrawing, gboolean enable)
Definition at line 2616 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::track_config.
Referenced by main().
matekbd_keyboard_drawing_set_track_modifiers()
void matekbd_keyboard_drawing_set_track_modifiers (MatekbdKeyboardDrawing * kbdrawing, gboolean enable)
Definition at line 2601 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::display, and _MatekbdKeyboardDrawing::track_modifiers.
Referenced by main().