MATE Desktop Environment: mate-image-menu-item.c File Reference
mate-image-menu-item.c File Reference
#include "config.h"
#include <glib.h>
#include <glib/gi18n.h>
#include <glib/gstdio.h>
#include "mate-image-menu-item.h"
Enumerations
enum { PROP_0 , PROP_IMAGE }
Functions
GtkWidget * mate_image_menu_item_new (void)
GtkWidget * mate_image_menu_item_new_with_label (const gchar *label)
GtkWidget * mate_image_menu_item_new_with_mnemonic (const gchar *label)
void mate_image_menu_item_set_image (MateImageMenuItem *image_menu_item, GtkWidget *image)
GtkWidget * mate_image_menu_item_get_image (MateImageMenuItem *image_menu_item)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_IMAGE
Definition at line 30 of file mate-image-menu-item.c.
Function Documentation
mate_image_menu_item_get_image()
GtkWidget * mate_image_menu_item_get_image (MateImageMenuItem * image_menu_item)
mate_image_menu_item_get_image: @image_menu_item: a MateImageMenuItem
Gets the widget that is currently set as the image of @image_menu_item. See mate_image_menu_item_set_image().
Returns: (transfer none): the widget set as image of @image_menu_item
Definition at line 524 of file mate-image-menu-item.c.
References MATE_IS_IMAGE_MENU_ITEM, NULL, and _MateImageMenuItem::priv.
mate_image_menu_item_new()
GtkWidget * mate_image_menu_item_new (void)
mate_image_menu_item_new:
Creates a new MateImageMenuItem with an empty label.
Returns: a new MateImageMenuItem
Definition at line 428 of file mate-image-menu-item.c.
References MATE_TYPE_IMAGE_MENU_ITEM, and NULL.
Referenced by main(), panel_image_menu_item_new(), panel_recent_append_documents_menu(), and sn_dbus_menu_item_new().
mate_image_menu_item_new_with_label()
GtkWidget * mate_image_menu_item_new_with_label (const gchar * label)
mate_image_menu_item_new_with_label: @label: the text of the menu item.
Creates a new MateImageMenuItem containing a label.
Returns: a new MateImageMenuItem.
Definition at line 443 of file mate-image-menu-item.c.
References label, MATE_TYPE_IMAGE_MENU_ITEM, and NULL.
Referenced by ev_sidebar_add_page(), gdict_sidebar_add_page(), and main().
mate_image_menu_item_new_with_mnemonic()
GtkWidget * mate_image_menu_item_new_with_mnemonic (const gchar * label)
mate_image_menu_item_new_with_mnemonic: @label: the text of the menu item, with an underscore in front of the mnemonic character
Creates a new MateImageMenuItem containing a label. The label will be created using gtk_label_new_with_mnemonic(), so underscores in @label indicate the mnemonic for the menu item.
Returns: a new MateImageMenuItem
Definition at line 463 of file mate-image-menu-item.c.
References label, MATE_TYPE_IMAGE_MENU_ITEM, NULL, and TRUE.
Referenced by main().
mate_image_menu_item_set_image()
void mate_image_menu_item_set_image (MateImageMenuItem * image_menu_item, GtkWidget * image)
mate_image_menu_item_set_image: @image_menu_item: a MateImageMenuItem. (allow-none): a widget to set as the image for the menu item.
Sets the image of @image_menu_item to the given widget. Note that it depends on the show-menu-images setting whether the image will be displayed or not.
Definition at line 482 of file mate-image-menu-item.c.
References MATE_IS_IMAGE_MENU_ITEM, NULL, _MateImageMenuItem::priv, and TRUE.
Referenced by main(), setup_menuitem(), sn_dbus_menu_item_new(), sn_dbus_menu_item_remove_props(), and sn_dbus_menu_item_update_props().