MATE Desktop Environment: mate-keyboard-properties-xkblt.c File Reference
mate-keyboard-properties-xkblt.c File Reference
#include <gdk/gdkx.h>
#include <gio/gio.h>
#include <glib/gi18n.h>
#include <libmatekbd/matekbd-desktop-config.h>
#include <libmatekbd/matekbd-keyboard-drawing.h>
#include "capplet-util.h"
#include "mate-keyboard-properties-xkb.h"
Macros
#define SEL_LAYOUT_TREE_COL_DESCRIPTION 0
#define SEL_LAYOUT_TREE_COL_ID 1
#define SEL_LAYOUT_TREE_COL_ENABLED 2
Functions
void clear_xkb_elements_list (GSList *list)
GSList * xkb_layouts_get_selected_list (void)
gint xkb_get_default_group ()
void xkb_save_default_group (gint default_group)
void xkb_layouts_prepare_selected_tree (GtkBuilder *dialog)
gchar * xkb_layout_description_utf8 (const gchar *visible)
void xkb_layouts_fill_selected_tree (GtkBuilder *dialog)
void xkb_layouts_register_buttons_handlers (GtkBuilder *dialog)
void xkb_layouts_register_gsettings_listener (GtkBuilder *dialog)
Macro Definition Documentation
SEL_LAYOUT_TREE_COL_DESCRIPTION
#define SEL_LAYOUT_TREE_COL_DESCRIPTION 0
Definition at line 38 of file mate-keyboard-properties-xkblt.c.
Referenced by xkb_layouts_fill_selected_tree(), and xkb_layouts_prepare_selected_tree().
SEL_LAYOUT_TREE_COL_ENABLED
#define SEL_LAYOUT_TREE_COL_ENABLED 2
Definition at line 40 of file mate-keyboard-properties-xkblt.c.
Referenced by xkb_layouts_fill_selected_tree(), and xkb_layouts_prepare_selected_tree().
SEL_LAYOUT_TREE_COL_ID
#define SEL_LAYOUT_TREE_COL_ID 1
Definition at line 39 of file mate-keyboard-properties-xkblt.c.
Referenced by xkb_layouts_fill_selected_tree().
Function Documentation
clear_xkb_elements_list()
void clear_xkb_elements_list (GSList * list)
Definition at line 51 of file mate-keyboard-properties-xkblt.c.
References NULL.
Referenced by xkb_layouts_fill_selected_tree().
xkb_get_default_group()
gint xkb_get_default_group (void)
Definition at line 114 of file mate-keyboard-properties-xkblt.c.
References xkb_general_settings.
Referenced by setup_xkb_tabs(), and xkb_save_default_group().
xkb_layout_description_utf8()
gchar * xkb_layout_description_utf8 (const gchar * visible)
Definition at line 281 of file mate-keyboard-properties-xkblt.c.
References config_registry, matekbd_keyboard_config_format_full_layout(), and matekbd_keyboard_config_get_descriptions().
Referenced by xkb_layouts_fill_selected_tree().
xkb_layouts_fill_selected_tree()
void xkb_layouts_fill_selected_tree (GtkBuilder * dialog)
Definition at line 291 of file mate-keyboard-properties-xkblt.c.
References clear_xkb_elements_list(), FALSE, NULL, SEL_LAYOUT_TREE_COL_DESCRIPTION, SEL_LAYOUT_TREE_COL_ENABLED, SEL_LAYOUT_TREE_COL_ID, TRUE, WID, xkb_layout_description_utf8(), and xkb_layouts_get_selected_list().
Referenced by setup_xkb_tabs().
xkb_layouts_get_selected_list()
GSList * xkb_layouts_get_selected_list (void)
Definition at line 88 of file mate-keyboard-properties-xkblt.c.
References initial_config, NULL, and xkb_kbd_settings.
Referenced by xkb_layouts_fill_selected_tree().
xkb_layouts_prepare_selected_tree()
void xkb_layouts_prepare_selected_tree (GtkBuilder * dialog)
Definition at line 225 of file mate-keyboard-properties-xkblt.c.
References _, engine, NULL, SEL_LAYOUT_TREE_COL_DESCRIPTION, SEL_LAYOUT_TREE_COL_ENABLED, TRUE, and WID.
Referenced by setup_xkb_tabs().
xkb_layouts_register_buttons_handlers()
void xkb_layouts_register_buttons_handlers (GtkBuilder * dialog)
Definition at line 437 of file mate-keyboard-properties-xkblt.c.
Referenced by setup_xkb_tabs().
xkb_layouts_register_gsettings_listener()
void xkb_layouts_register_gsettings_listener (GtkBuilder * dialog)
Definition at line 464 of file mate-keyboard-properties-xkblt.c.
References xkb_kbd_settings.
Referenced by setup_xkb_tabs().
xkb_save_default_group()
void xkb_save_default_group (gint default_group)
Definition at line 120 of file mate-keyboard-properties-xkblt.c.
References xkb_general_settings, and xkb_get_default_group().