MATE Desktop Environment: mate-desktop-thumbnail.h File Reference
mate-desktop-thumbnail.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <time.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
Classes
struct _MateDesktopThumbnailFactory
struct _MateDesktopThumbnailFactoryClass
Macros
#define MATE_DESKTOP_TYPE_THUMBNAIL_FACTORY (mate_desktop_thumbnail_factory_get_type ())
#define MATE_DESKTOP_THUMBNAIL_FACTORY(obj)
#define MATE_DESKTOP_THUMBNAIL_FACTORY_CLASS(klass)
#define MATE_DESKTOP_IS_THUMBNAIL_FACTORY(obj)
#define MATE_DESKTOP_IS_THUMBNAIL_FACTORY_CLASS(klass)
Typedefs
typedef struct _MateDesktopThumbnailFactory MateDesktopThumbnailFactory
typedef struct _MateDesktopThumbnailFactoryClass MateDesktopThumbnailFactoryClass
typedef struct _MateDesktopThumbnailFactoryPrivate MateDesktopThumbnailFactoryPrivate
Enumerations
enum MateDesktopThumbnailSize { MATE_DESKTOP_THUMBNAIL_SIZE_NORMAL , MATE_DESKTOP_THUMBNAIL_SIZE_LARGE }
Functions
GType mate_desktop_thumbnail_factory_get_type (void)
MateDesktopThumbnailFactory * mate_desktop_thumbnail_factory_new (MateDesktopThumbnailSize size)
char * mate_desktop_thumbnail_factory_lookup (MateDesktopThumbnailFactory *factory, const char *uri, time_t mtime)
gboolean mate_desktop_thumbnail_factory_has_valid_failed_thumbnail (MateDesktopThumbnailFactory *factory, const char *uri, time_t mtime)
gboolean mate_desktop_thumbnail_factory_can_thumbnail (MateDesktopThumbnailFactory *factory, const char *uri, const char *mime_type, time_t mtime)
GdkPixbuf * mate_desktop_thumbnail_factory_generate_thumbnail (MateDesktopThumbnailFactory *factory, const char *uri, const char *mime_type)
void mate_desktop_thumbnail_factory_save_thumbnail (MateDesktopThumbnailFactory *factory, GdkPixbuf *thumbnail, const char *uri, time_t original_mtime)
void mate_desktop_thumbnail_factory_create_failed_thumbnail (MateDesktopThumbnailFactory *factory, const char *uri, time_t mtime)
gboolean mate_desktop_thumbnail_has_uri (GdkPixbuf *pixbuf, const char *uri)
gboolean mate_desktop_thumbnail_is_valid (GdkPixbuf *pixbuf, const char *uri, time_t mtime)
char * mate_desktop_thumbnail_path_for_uri (const char *uri, MateDesktopThumbnailSize size)
Macro Definition Documentation
MATE_DESKTOP_IS_THUMBNAIL_FACTORY
#define MATE_DESKTOP_IS_THUMBNAIL_FACTORY (obj)
Value:
(G_TYPE_INSTANCE_CHECK_TYPE ((obj), MATE_DESKTOP_TYPE_THUMBNAIL_FACTORY))
Definition at line 48 of file mate-desktop-thumbnail.h.
MATE_DESKTOP_IS_THUMBNAIL_FACTORY_CLASS
#define MATE_DESKTOP_IS_THUMBNAIL_FACTORY_CLASS (klass)
Value:
(G_TYPE_CLASS_CHECK_CLASS_TYPE ((klass), MATE_DESKTOP_TYPE_THUMBNAIL_FACTORY))
Definition at line 49 of file mate-desktop-thumbnail.h.
MATE_DESKTOP_THUMBNAIL_FACTORY
#define MATE_DESKTOP_THUMBNAIL_FACTORY (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_DESKTOP_TYPE_THUMBNAIL_FACTORY, MateDesktopThumbnailFactory))
Definition at line 46 of file mate-desktop-thumbnail.h.
MATE_DESKTOP_THUMBNAIL_FACTORY_CLASS
#define MATE_DESKTOP_THUMBNAIL_FACTORY_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), MATE_DESKTOP_TYPE_THUMBNAIL_FACTORY, MateDesktopThumbnailFactoryClass))
Definition at line 47 of file mate-desktop-thumbnail.h.
MATE_DESKTOP_TYPE_THUMBNAIL_FACTORY
#define MATE_DESKTOP_TYPE_THUMBNAIL_FACTORY (mate_desktop_thumbnail_factory_get_type ())
Definition at line 45 of file mate-desktop-thumbnail.h.
Referenced by mate_desktop_thumbnail_factory_new().
Typedef Documentation
MateDesktopThumbnailFactory
typedef struct _MateDesktopThumbnailFactory MateDesktopThumbnailFactory
Definition at line 51 of file mate-desktop-thumbnail.h.
MateDesktopThumbnailFactoryClass
typedef struct _MateDesktopThumbnailFactoryClass MateDesktopThumbnailFactoryClass
Definition at line 52 of file mate-desktop-thumbnail.h.
MateDesktopThumbnailFactoryPrivate
typedef struct _MateDesktopThumbnailFactoryPrivate MateDesktopThumbnailFactoryPrivate
Definition at line 53 of file mate-desktop-thumbnail.h.
Enumeration Type Documentation
MateDesktopThumbnailSize
enum MateDesktopThumbnailSize
Enumerator
MATE_DESKTOP_THUMBNAIL_SIZE_NORMAL
MATE_DESKTOP_THUMBNAIL_SIZE_LARGE
Definition at line 40 of file mate-desktop-thumbnail.h.
Function Documentation
mate_desktop_thumbnail_factory_can_thumbnail()
gboolean mate_desktop_thumbnail_factory_can_thumbnail (MateDesktopThumbnailFactory * factory, const char * uri, const char * mime_type, time_t mtime)
mate_desktop_thumbnail_factory_can_thumbnail: @factory: a MateDesktopThumbnailFactory @uri: the uri of a file @mime_type: the mime type of the file @mtime: the mtime of the file
Returns TRUE if this MateDesktopThumbnailFactory can (at least try) to thumbnail this file. Thumbnails or files with failed thumbnails won't be thumbnailed.
Usage of this function is threadsafe.
Return value: TRUE if the file can be thumbnailed.
Since: 2.2
Definition at line 829 of file mate-desktop-thumbnail.c.
References FALSE, mate_desktop_thumbnail_factory_has_valid_failed_thumbnail(), mime_type, NULL, and Thumbnailer.
Referenced by caja_can_thumbnail(), and eom_thumbnail_load().
mate_desktop_thumbnail_factory_create_failed_thumbnail()
void mate_desktop_thumbnail_factory_create_failed_thumbnail (MateDesktopThumbnailFactory * factory, const char * uri, time_t mtime)
mate_desktop_thumbnail_factory_create_failed_thumbnail: @factory: a MateDesktopThumbnailFactory @uri: the uri of a file @mtime: the modification time of the file
Creates a failed thumbnail for the file so that we don't try to re-thumbnail the file later.
Usage of this function is threadsafe.
Since: 2.2
Definition at line 1264 of file mate-desktop-thumbnail.c.
Referenced by eom_thumbnail_load().
mate_desktop_thumbnail_factory_generate_thumbnail()
GdkPixbuf * mate_desktop_thumbnail_factory_generate_thumbnail (MateDesktopThumbnailFactory * factory, const char * uri, const char * mime_type)
mate_desktop_thumbnail_factory_generate_thumbnail: @factory: a MateDesktopThumbnailFactory @uri: the uri of a file @mime_type: the mime type of the file
Tries to generate a thumbnail for the specified file. If it succeeds it returns a pixbuf that can be used as a thumbnail.
Usage of this function is threadsafe.
Return value: (transfer full): thumbnail pixbuf if thumbnailing succeeded, NULL otherwise.
Since: 2.2
Definition at line 1055 of file mate-desktop-thumbnail.c.
References error, MATE_DESKTOP_THUMBNAIL_SIZE_LARGE, mime_type, NULL, and Thumbnailer.
Referenced by eom_thumbnail_load(), and main().
mate_desktop_thumbnail_factory_get_type()
GType mate_desktop_thumbnail_factory_get_type (void)
References mime_type.
mate_desktop_thumbnail_factory_has_valid_failed_thumbnail()
gboolean mate_desktop_thumbnail_factory_has_valid_failed_thumbnail (MateDesktopThumbnailFactory * factory, const char * uri, time_t mtime)
mate_desktop_thumbnail_factory_has_valid_failed_thumbnail: @factory: a MateDesktopThumbnailFactory @uri: the uri of a file @mtime: the mtime of the file
Tries to locate an failed thumbnail for the file specified. Writing and looking for failed thumbnails is important to avoid to try to thumbnail e.g. broken images several times.
Usage of this function is threadsafe.
Return value: TRUE if there is a failed thumbnail for the file.
Since: 2.2
Definition at line 795 of file mate-desktop-thumbnail.c.
References FALSE, NULL, and TRUE.
Referenced by eom_thumbnail_load(), and mate_desktop_thumbnail_factory_can_thumbnail().
mate_desktop_thumbnail_factory_lookup()
char * mate_desktop_thumbnail_factory_lookup (MateDesktopThumbnailFactory * factory, const char * uri, time_t mtime)
mate_desktop_thumbnail_factory_lookup: @factory: a MateDesktopThumbnailFactory @uri: the uri of a file @mtime: the mtime of the file
Tries to locate an existing thumbnail for the file specified.
Usage of this function is threadsafe.
Return value: (transfer full): The absolute path of the thumbnail, or NULL if none exist.
Since: 2.2
Definition at line 767 of file mate-desktop-thumbnail.c.
References NULL.
Referenced by mate_wp_info_new().
mate_desktop_thumbnail_factory_new()
MateDesktopThumbnailFactory * mate_desktop_thumbnail_factory_new (MateDesktopThumbnailSize size)
mate_desktop_thumbnail_factory_new: @size: The thumbnail size to use
Creates a new MateDesktopThumbnailFactory.
This function must be called on the main thread.
Return value: a new MateDesktopThumbnailFactory
Since: 2.2
Definition at line 649 of file mate-desktop-thumbnail.c.
References MATE_DESKTOP_TYPE_THUMBNAIL_FACTORY, and NULL.
Referenced by eom_thumbnail_init(), and main().
mate_desktop_thumbnail_factory_save_thumbnail()
void mate_desktop_thumbnail_factory_save_thumbnail (MateDesktopThumbnailFactory * factory, GdkPixbuf * thumbnail, const char * uri, time_t original_mtime)
mate_desktop_thumbnail_factory_save_thumbnail: @factory: a MateDesktopThumbnailFactory @thumbnail: the thumbnail as a pixbuf @uri: the uri of a file @original_mtime: the modification time of the original file
Saves @thumbnail at the right place. If the save fails a failed thumbnail is written.
Usage of this function is threadsafe.
Since: 2.2
Definition at line 1231 of file mate-desktop-thumbnail.c.
Referenced by eom_thumbnail_load().
mate_desktop_thumbnail_has_uri()
gboolean mate_desktop_thumbnail_has_uri (GdkPixbuf * pixbuf, const char * uri)
mate_desktop_thumbnail_has_uri: @pixbuf: an loaded thumbnail pixbuf @uri: a uri
Returns whether the thumbnail has the correct uri embedded in the Thumb::URI option in the png.
Return value: TRUE if the thumbnail is for @uri
Since: 2.2
Definition at line 1310 of file mate-desktop-thumbnail.c.
mate_desktop_thumbnail_is_valid()
gboolean mate_desktop_thumbnail_is_valid (GdkPixbuf * pixbuf, const char * uri, time_t mtime)
mate_desktop_thumbnail_is_valid: @pixbuf: an loaded thumbnail #GdkPixbuf @uri: a uri @mtime: the mtime
Returns whether the thumbnail has the correct uri and mtime embedded in the png options.
Return value: TRUE if the thumbnail has the right @uri and @mtime
Since: 2.2
Definition at line 1333 of file mate-desktop-thumbnail.c.
References FALSE, NULL, and TRUE.
mate_desktop_thumbnail_path_for_uri()
char * mate_desktop_thumbnail_path_for_uri (const char * uri, MateDesktopThumbnailSize size)
mate_desktop_thumbnail_path_for_uri: @uri: an uri @size: a thumbnail size
Returns the filename that a thumbnail of size @size for @uri would have.
Return value: an absolute filename
Since: 2.2
Definition at line 1291 of file mate-desktop-thumbnail.c.