MATE Desktop Environment: matekbd-indicator-config.c File Reference
matekbd-indicator-config.c File Reference
#include <config.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <X11/keysym.h>
#include <pango/pango.h>
#include <glib/gi18n-lib.h>
#include <gdk/gdkx.h>
#include <matekbd-keyboard-config.h>
#include <matekbd-indicator-config.h>
#include <matekbd-config-private.h>
Macros
#define MATEKBD_INDICATOR_CONFIG_SCHEMA MATEKBD_CONFIG_SCHEMA ".indicator"
Functions
void matekbd_indicator_config_refresh_style (MatekbdIndicatorConfig *ind_config)
gchar * matekbd_indicator_config_get_images_file (MatekbdIndicatorConfig *ind_config, MatekbdKeyboardConfig *kbd_config, int group)
void matekbd_indicator_config_load_image_filenames (MatekbdIndicatorConfig *ind_config, MatekbdKeyboardConfig *kbd_config)
void matekbd_indicator_config_free_image_filenames (MatekbdIndicatorConfig *ind_config)
void matekbd_indicator_config_init (MatekbdIndicatorConfig *ind_config, XklEngine *engine)
void matekbd_indicator_config_term (MatekbdIndicatorConfig *ind_config)
void matekbd_indicator_config_load_from_gsettings (MatekbdIndicatorConfig *ind_config)
void matekbd_indicator_config_save_to_gsettings (MatekbdIndicatorConfig *ind_config)
void matekbd_indicator_config_activate (MatekbdIndicatorConfig *ind_config)
void matekbd_indicator_config_start_listen (MatekbdIndicatorConfig *ind_config, GCallback func, gpointer user_data)
void matekbd_indicator_config_stop_listen (MatekbdIndicatorConfig *ind_config)
Variables
const gchar MATEKBD_INDICATOR_CONFIG_KEY_SHOW_FLAGS [] = "show-flags"
const gchar MATEKBD_INDICATOR_CONFIG_KEY_SECONDARIES [] = "secondary"
const gchar MATEKBD_INDICATOR_CONFIG_KEY_FONT_FAMILY [] = "font-family"
const gchar MATEKBD_INDICATOR_CONFIG_KEY_FOREGROUND_COLOR [] = "foreground-color"
const gchar MATEKBD_INDICATOR_CONFIG_KEY_BACKGROUND_COLOR [] = "background-color"
Macro Definition Documentation
MATEKBD_INDICATOR_CONFIG_SCHEMA
#define MATEKBD_INDICATOR_CONFIG_SCHEMA MATEKBD_CONFIG_SCHEMA ".indicator"
MatekbdIndicatorConfig:
Definition at line 40 of file matekbd-indicator-config.c.
Referenced by matekbd_indicator_config_init().
Function Documentation
matekbd_indicator_config_activate()
void matekbd_indicator_config_activate (MatekbdIndicatorConfig * ind_config)
Definition at line 311 of file matekbd-indicator-config.c.
References _MatekbdIndicatorConfig::engine, and _MatekbdIndicatorConfig::secondary_groups_mask.
matekbd_indicator_config_free_image_filenames()
void matekbd_indicator_config_free_image_filenames (MatekbdIndicatorConfig * ind_config)
Definition at line 213 of file matekbd-indicator-config.c.
References _MatekbdIndicatorConfig::image_filenames.
Referenced by matekbd_indicator_config_term().
matekbd_indicator_config_get_images_file()
gchar * matekbd_indicator_config_get_images_file (MatekbdIndicatorConfig * ind_config, MatekbdKeyboardConfig * kbd_config, int group)
Definition at line 140 of file matekbd-indicator-config.c.
References _MatekbdIndicatorConfig::icon_theme, _MatekbdKeyboardConfig::layouts_variants, matekbd_keyboard_config_split_items(), NULL, and _MatekbdIndicatorConfig::show_flags.
Referenced by matekbd_indicator_config_load_image_filenames(), matekbd_indicator_get_image_filename(), and matekbd_status_get_image_filename().
matekbd_indicator_config_init()
void matekbd_indicator_config_init (MatekbdIndicatorConfig * ind_config, XklEngine * engine)
Definition at line 226 of file matekbd-indicator-config.c.
References DATADIR, _MatekbdIndicatorConfig::engine, engine, _MatekbdIndicatorConfig::icon_theme, MATEKBD_INDICATOR_CONFIG_SCHEMA, NULL, and _MatekbdIndicatorConfig::settings.
matekbd_indicator_config_load_from_gsettings()
void matekbd_indicator_config_load_from_gsettings (MatekbdIndicatorConfig * ind_config)
Definition at line 280 of file matekbd-indicator-config.c.
References MATEKBD_INDICATOR_CONFIG_KEY_SECONDARIES, MATEKBD_INDICATOR_CONFIG_KEY_SHOW_FLAGS, _MatekbdIndicatorConfig::secondary_groups_mask, _MatekbdIndicatorConfig::settings, and _MatekbdIndicatorConfig::show_flags.
matekbd_indicator_config_load_image_filenames()
void matekbd_indicator_config_load_image_filenames (MatekbdIndicatorConfig * ind_config, MatekbdKeyboardConfig * kbd_config)
Definition at line 189 of file matekbd-indicator-config.c.
References _MatekbdIndicatorConfig::engine, _MatekbdIndicatorConfig::image_filenames, matekbd_indicator_config_get_images_file(), NULL, and _MatekbdIndicatorConfig::show_flags.
Referenced by matekbd_indicator_load_images().
matekbd_indicator_config_refresh_style()
void matekbd_indicator_config_refresh_style (MatekbdIndicatorConfig * ind_config)
Definition at line 130 of file matekbd-indicator-config.c.
References _MatekbdIndicatorConfig::background_color, _MatekbdIndicatorConfig::font_family, and _MatekbdIndicatorConfig::foreground_color.
matekbd_indicator_config_save_to_gsettings()
void matekbd_indicator_config_save_to_gsettings (MatekbdIndicatorConfig * ind_config)
Definition at line 296 of file matekbd-indicator-config.c.
References MATEKBD_INDICATOR_CONFIG_KEY_SECONDARIES, MATEKBD_INDICATOR_CONFIG_KEY_SHOW_FLAGS, _MatekbdIndicatorConfig::secondary_groups_mask, _MatekbdIndicatorConfig::settings, and _MatekbdIndicatorConfig::show_flags.
matekbd_indicator_config_start_listen()
void matekbd_indicator_config_start_listen (MatekbdIndicatorConfig * ind_config, GCallback func, gpointer user_data)
matekbd_indicator_config_start_listen: @func: (scope notified): a function to call when settings are changed
Definition at line 322 of file matekbd-indicator-config.c.
References _MatekbdIndicatorConfig::config_listener_id, _MatekbdIndicatorConfig::settings, and user_data.
matekbd_indicator_config_stop_listen()
void matekbd_indicator_config_stop_listen (MatekbdIndicatorConfig * ind_config)
Definition at line 333 of file matekbd-indicator-config.c.
References _MatekbdIndicatorConfig::config_listener_id, and _MatekbdIndicatorConfig::settings.
matekbd_indicator_config_term()
void matekbd_indicator_config_term (MatekbdIndicatorConfig * ind_config)
Definition at line 260 of file matekbd-indicator-config.c.
References _MatekbdIndicatorConfig::background_color, _MatekbdIndicatorConfig::font_family, _MatekbdIndicatorConfig::foreground_color, _MatekbdIndicatorConfig::icon_theme, matekbd_indicator_config_free_image_filenames(), NULL, and _MatekbdIndicatorConfig::settings.
Variable Documentation
MATEKBD_INDICATOR_CONFIG_KEY_BACKGROUND_COLOR
const gchar MATEKBD_INDICATOR_CONFIG_KEY_BACKGROUND_COLOR[] = "background-color"
Definition at line 46 of file matekbd-indicator-config.c.
MATEKBD_INDICATOR_CONFIG_KEY_FONT_FAMILY
const gchar MATEKBD_INDICATOR_CONFIG_KEY_FONT_FAMILY[] = "font-family"
Definition at line 44 of file matekbd-indicator-config.c.
MATEKBD_INDICATOR_CONFIG_KEY_FOREGROUND_COLOR
const gchar MATEKBD_INDICATOR_CONFIG_KEY_FOREGROUND_COLOR[] = "foreground-color"
Definition at line 45 of file matekbd-indicator-config.c.
MATEKBD_INDICATOR_CONFIG_KEY_SECONDARIES
const gchar MATEKBD_INDICATOR_CONFIG_KEY_SECONDARIES[] = "secondary"
Definition at line 43 of file matekbd-indicator-config.c.
Referenced by matekbd_indicator_config_load_from_gsettings(), and matekbd_indicator_config_save_to_gsettings().
MATEKBD_INDICATOR_CONFIG_KEY_SHOW_FLAGS
const gchar MATEKBD_INDICATOR_CONFIG_KEY_SHOW_FLAGS[] = "show-flags"
Definition at line 42 of file matekbd-indicator-config.c.
Referenced by matekbd_indicator_config_load_from_gsettings(), and matekbd_indicator_config_save_to_gsettings().