MATE Desktop Environment: load-graph.h File Reference
load-graph.h File Reference
#include "global.h"
Functions
G_GNUC_INTERNAL LoadGraph * load_graph_new (MultiloadApplet *multiload, guint n, const gchar *label, gint id, guint speed, guint size, gboolean visible, const gchar *name, LoadGraphDataFunc get_data)
G_GNUC_INTERNAL void load_graph_start (LoadGraph *g)
G_GNUC_INTERNAL void load_graph_stop (LoadGraph *g)
G_GNUC_INTERNAL void load_graph_unalloc (LoadGraph *g)
Function Documentation
load_graph_new()
G_GNUC_INTERNAL LoadGraph * load_graph_new (MultiloadApplet * multiload, guint n, const gchar * label, gint id, guint speed, guint size, gboolean visible, const gchar * name, LoadGraphDataFunc get_data)
Definition at line 410 of file load-graph.c.
References _MultiloadApplet::applet, LoadGraph::disp, FALSE, label, LoadGraph::main_widget, mate_panel_applet_get_orient(), mate_panel_applet_get_size(), MatePanelAppletOrient, LoadGraph::n, name, NULL, LoadGraph::speed, LoadGraph::timer_index, and TRUE.
load_graph_start()
G_GNUC_INTERNAL void load_graph_start (LoadGraph * g)
Definition at line 493 of file load-graph.c.
load_graph_stop()
G_GNUC_INTERNAL void load_graph_stop (LoadGraph * g)
Definition at line 507 of file load-graph.c.
load_graph_unalloc()
G_GNUC_INTERNAL void load_graph_unalloc (LoadGraph * g)
Definition at line 255 of file load-graph.c.
References LoadGraph::data, LoadGraph::draw_width, FALSE, GRAPH_SIZE_KEY, GRAPH_SIZE_MAX, GRAPH_SIZE_MIN, and NULL.
Referenced by multiload_applet_refresh().