MATE Desktop Environment: eggaccelerators.c File Reference
eggaccelerators.c File Reference
#include "eggaccelerators.h"
#include <stdlib.h>
#include <string.h>
#include <gdk/gdkx.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
Macros
#define MODMAP_ENTRY_TO_MODIFIER(x)
Enumerations
enum {
EGG_MODMAP_ENTRY_SHIFT = 0 , EGG_MODMAP_ENTRY_LOCK = 1 , EGG_MODMAP_ENTRY_CONTROL = 2 , EGG_MODMAP_ENTRY_MOD1 = 3 ,
EGG_MODMAP_ENTRY_MOD2 = 4 , EGG_MODMAP_ENTRY_MOD3 = 5 , EGG_MODMAP_ENTRY_MOD4 = 6 , EGG_MODMAP_ENTRY_MOD5 = 7 ,
EGG_MODMAP_ENTRY_LAST = 8
}
Functions
const EggModmap * egg_keymap_get_modmap (GdkKeymap *keymap)
gboolean egg_accelerator_parse_virtual (const gchar *accelerator, guint *accelerator_key, guint **accelerator_codes, EggVirtualModifierType *accelerator_mods)
gchar * egg_virtual_accelerator_name (guint accelerator_key, guint keycode, EggVirtualModifierType accelerator_mods)
gchar * egg_virtual_accelerator_label (guint accelerator_key, guint keycode, EggVirtualModifierType accelerator_mods)
void egg_keymap_resolve_virtual_modifiers (GdkKeymap *keymap, EggVirtualModifierType virtual_mods, GdkModifierType *concrete_mods)
void egg_keymap_virtualize_modifiers (GdkKeymap *keymap, GdkModifierType concrete_mods, EggVirtualModifierType *virtual_mods)
Macro Definition Documentation
MODMAP_ENTRY_TO_MODIFIER
#define MODMAP_ENTRY_TO_MODIFIER (x)
Value:
(1 << (x))
Definition at line 43 of file mate-settings-daemon/plugins/common/eggaccelerators.c.
Referenced by egg_keymap_resolve_virtual_modifiers().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EGG_MODMAP_ENTRY_SHIFT
EGG_MODMAP_ENTRY_LOCK
EGG_MODMAP_ENTRY_CONTROL
EGG_MODMAP_ENTRY_MOD1
EGG_MODMAP_ENTRY_MOD2
EGG_MODMAP_ENTRY_MOD3
EGG_MODMAP_ENTRY_MOD4
EGG_MODMAP_ENTRY_MOD5
EGG_MODMAP_ENTRY_LAST
Definition at line 30 of file mate-settings-daemon/plugins/common/eggaccelerators.c.
Function Documentation
egg_accelerator_parse_virtual()
gboolean egg_accelerator_parse_virtual (const gchar * accelerator, guint * accelerator_key, guint ** accelerator_codes, EggVirtualModifierType * accelerator_mods)
egg_accelerator_parse_virtual: @accelerator: string representing an accelerator @accelerator_key: return location for accelerator keyval @accelerator_codes: return location for a 0-terminated array of accelerator keycodes @accelerator_mods: return location for accelerator modifier mask
Parses a string representing a virtual accelerator. The format looks like "&lt;Control&gt;a" or "&lt;Shift&gt;&lt;Alt&gt;F1" or "&lt;Release&gt;z" (the last one is for key release). The parser is fairly liberal and allows lower or upper case, and also abbreviations such as "&lt;Ctl&gt;" and "&lt;Ctrl&gt;".
If the parse fails, @accelerator_key and @accelerator_mods will be set to 0 (zero) and FALSE will be returned. If the string contains only modifiers, @accelerator_key will be set to 0 but TRUE will be returned.
The virtual vs. concrete accelerator distinction is a relic of how the X Window System works; there are modifiers Mod2-Mod5 that can represent various keyboard keys (numlock, meta, hyper, etc.), the virtual modifier represents the keyboard key, the concrete modifier the actual Mod2-Mod5 bits in the key press event.
Returns: TRUE on success.
Definition at line 229 of file mate-settings-daemon/plugins/common/eggaccelerators.c.
References EGG_VIRTUAL_ALT_MASK, EGG_VIRTUAL_CONTROL_MASK, EGG_VIRTUAL_HYPER_MASK, EGG_VIRTUAL_META_MASK, EGG_VIRTUAL_MOD2_MASK, EGG_VIRTUAL_MOD3_MASK, EGG_VIRTUAL_MOD4_MASK, EGG_VIRTUAL_MOD5_MASK, EGG_VIRTUAL_RELEASE_MASK, EGG_VIRTUAL_SHIFT_MASK, EGG_VIRTUAL_SUPER_MASK, FALSE, keyval, level, memcpy, NULL, and TRUE.
egg_keymap_get_modmap()
const EggModmap * egg_keymap_get_modmap (GdkKeymap * keymap)
Definition at line 646 of file mate-settings-daemon/plugins/common/eggaccelerators.c.
References NULL.
Referenced by egg_keymap_resolve_virtual_modifiers(), and egg_keymap_virtualize_modifiers().
egg_keymap_resolve_virtual_modifiers()
void egg_keymap_resolve_virtual_modifiers (GdkKeymap * keymap, EggVirtualModifierType virtual_mods, GdkModifierType * concrete_mods)
Definition at line 495 of file mate-settings-daemon/plugins/common/eggaccelerators.c.
References egg_keymap_get_modmap(), EGG_MODMAP_ENTRY_LAST, MODMAP_ENTRY_TO_MODIFIER, and NULL.
Referenced by egg_virtual_accelerator_label(), and egg_virtual_accelerator_name().
egg_keymap_virtualize_modifiers()
void egg_keymap_virtualize_modifiers (GdkKeymap * keymap, GdkModifierType concrete_mods, EggVirtualModifierType * virtual_mods)
Definition at line 521 of file mate-settings-daemon/plugins/common/eggaccelerators.c.
References egg_keymap_get_modmap(), EGG_MODMAP_ENTRY_LAST, EGG_VIRTUAL_MOD2_MASK, EGG_VIRTUAL_MOD3_MASK, EGG_VIRTUAL_MOD4_MASK, EGG_VIRTUAL_MOD5_MASK, MODMAP_ENTRY_TO_MODIFIER, and NULL.
egg_virtual_accelerator_label()
gchar * egg_virtual_accelerator_label (guint accelerator_key, guint keycode, EggVirtualModifierType accelerator_mods)
egg_virtual_accelerator_label: @accelerator_key: accelerator keyval @accelerator_mods: accelerator modifier mask
Returns
: a newly-allocated accelerator label
Converts an accelerator keyval and modifier mask into a (possibly translated) string that can be displayed to a user. For example, if you pass in #GDK_q and EGG_VIRTUAL_CONTROL_MASK, and you use a German locale, this function returns "Strg+Q".
The caller of this function must free the returned string.
Definition at line 473 of file mate-settings-daemon/plugins/common/eggaccelerators.c.
References egg_keymap_resolve_virtual_modifiers(), label, and NULL.
egg_virtual_accelerator_name()
gchar * egg_virtual_accelerator_name (guint accelerator_key, guint keycode, EggVirtualModifierType accelerator_mods)
egg_virtual_accelerator_name: @accelerator_key: accelerator keyval @accelerator_mods: accelerator modifier mask
Returns
: a newly-allocated accelerator name
Converts an accelerator keyval and modifier mask into a string parseable by egg_accelerator_parse_virtual(). For example, if you pass in #GDK_q and EGG_VIRTUAL_CONTROL_MASK, this function returns "&lt;Control&gt;q".
The caller of this function must free the returned string.
Definition at line 437 of file mate-settings-daemon/plugins/common/eggaccelerators.c.
References egg_keymap_resolve_virtual_modifiers(), name, and NULL.