MATE Desktop Environment: mate-ui-application.h File Reference
mate-ui-application.h File Reference
#include <gtk/gtk.h>
Macros
#define MATE_UI_TYPE_APPLICATION (mate_ui_application_get_type())
Functions
G_DECLARE_DERIVABLE_TYPE (...) struct _MateUiApplicationClass
MateUiApplication * mate_ui_application_new (const gchar *application_id, GApplicationFlags flags)
: Human-readable application name
mate_ui_application_set_app_name: @app: A MateUiApplication
Sets the human-readable application name.
void mate_ui_application_set_app_name (MateUiApplication *app, const gchar *name)
const gchar * mate_ui_application_get_app_name (MateUiApplication *app)
void mate_ui_application_set_version (MateUiApplication *app, const gchar *version)
const gchar * mate_ui_application_get_version (MateUiApplication *app)
void mate_ui_application_set_comments (MateUiApplication *app, const gchar *comments)
const gchar * mate_ui_application_get_comments (MateUiApplication *app)
void mate_ui_application_set_copyright (MateUiApplication *app, const gchar *copyright)
const gchar * mate_ui_application_get_copyright (MateUiApplication *app)
void mate_ui_application_set_website (MateUiApplication *app, const gchar *website)
const gchar * mate_ui_application_get_website (MateUiApplication *app)
void mate_ui_application_set_help_uri (MateUiApplication *app, const gchar *help_uri)
const gchar * mate_ui_application_get_help_uri (MateUiApplication *app)
void mate_ui_application_set_icon_name (MateUiApplication *app, const gchar *icon_name)
const gchar * mate_ui_application_get_icon_name (MateUiApplication *app)
void mate_ui_application_set_authors (MateUiApplication *app, const gchar *const *authors)
const gchar *const * mate_ui_application_get_authors (MateUiApplication *app)
void mate_ui_application_set_documenters (MateUiApplication *app, const gchar *const *documenters)
const gchar *const * mate_ui_application_get_documenters (MateUiApplication *app)
void mate_ui_application_set_license_type (MateUiApplication *app, GtkLicense license)
GtkLicense mate_ui_application_get_license_type (MateUiApplication *app)
void mate_ui_application_show_about (MateUiApplication *app)
void mate_ui_application_show_help (MateUiApplication *app, const gchar *section)
void mate_ui_application_setup_common_actions (MateUiApplication *app)
Macro Definition Documentation
MATE_UI_TYPE_APPLICATION
#define MATE_UI_TYPE_APPLICATION (mate_ui_application_get_type())
Definition at line 19 of file mate-ui-application.h.
Referenced by mate_ui_application_new().
Function Documentation
G_DECLARE_DERIVABLE_TYPE()
G_DECLARE_DERIVABLE_TYPE (...)
MateUiApplicationClass: @parent_class: Parent class
Class structure for MateUiApplication
Definition at line 20 of file mate-ui-application.h.
References parent_class.
mate_ui_application_get_app_name()
const gchar * mate_ui_application_get_app_name (MateUiApplication * app)
mate_ui_application_get_app_name: @app: A MateUiApplication
Gets the human-readable application name.
Returns: (transfer none): The application name
Definition at line 327 of file mate-ui-application.c.
References NULL.
mate_ui_application_get_authors()
const gchar *const * mate_ui_application_get_authors (MateUiApplication * app)
mate_ui_application_get_authors: @app: A MateUiApplication
Gets the list of authors.
Returns: (transfer none) (array zero-terminated=1): The authors array
Definition at line 514 of file mate-ui-application.c.
References NULL.
mate_ui_application_get_comments()
const gchar * mate_ui_application_get_comments (MateUiApplication * app)
mate_ui_application_get_comments: @app: A MateUiApplication
Gets the application description.
Returns: (transfer none): The description
Definition at line 381 of file mate-ui-application.c.
References NULL.
mate_ui_application_get_copyright()
const gchar * mate_ui_application_get_copyright (MateUiApplication * app)
mate_ui_application_get_copyright: @app: A MateUiApplication
Gets the copyright notice.
Returns: (transfer none): The copyright notice
Definition at line 408 of file mate-ui-application.c.
References NULL.
mate_ui_application_get_documenters()
const gchar *const * mate_ui_application_get_documenters (MateUiApplication * app)
mate_ui_application_get_documenters: @app: A MateUiApplication
Gets the list of documenters.
Returns: (transfer none) (array zero-terminated=1): The documenters array
Definition at line 539 of file mate-ui-application.c.
References NULL.
mate_ui_application_get_help_uri()
const gchar * mate_ui_application_get_help_uri (MateUiApplication * app)
mate_ui_application_get_help_uri: @app: A MateUiApplication
Gets the help URI.
Returns: (transfer none): The help URI
Definition at line 462 of file mate-ui-application.c.
References NULL.
mate_ui_application_get_icon_name()
const gchar * mate_ui_application_get_icon_name (MateUiApplication * app)
mate_ui_application_get_icon_name: @app: A MateUiApplication
Gets the application icon name.
Returns: (transfer none): The icon name
Definition at line 489 of file mate-ui-application.c.
References NULL.
mate_ui_application_get_license_type()
GtkLicense mate_ui_application_get_license_type (MateUiApplication * app)
mate_ui_application_get_license_type: @app: A MateUiApplication
Gets the license type.
Returns: The license type
Definition at line 565 of file mate-ui-application.c.
mate_ui_application_get_version()
const gchar * mate_ui_application_get_version (MateUiApplication * app)
mate_ui_application_get_version: @app: A MateUiApplication
Gets the application version.
Returns: (transfer none): The version string
Definition at line 354 of file mate-ui-application.c.
References NULL.
mate_ui_application_get_website()
const gchar * mate_ui_application_get_website (MateUiApplication * app)
mate_ui_application_get_website: @app: A MateUiApplication
Gets the application website.
Returns: (transfer none): The website URL
Definition at line 435 of file mate-ui-application.c.
References NULL.
mate_ui_application_new()
MateUiApplication * mate_ui_application_new (const gchar * application_id, GApplicationFlags flags)
mate_ui_application_new: @application_id: The application ID (e.g., "org.mate.Calculator") @flags: Application flags
Creates a new MateUiApplication instance.
Returns: (transfer full): A new MateUiApplication
Definition at line 299 of file mate-ui-application.c.
References MATE_UI_TYPE_APPLICATION, and NULL.
Referenced by main().
mate_ui_application_set_app_name()
void mate_ui_application_set_app_name (MateUiApplication * app, const gchar * name)
Definition at line 311 of file mate-ui-application.c.
References name, and PROP_APP_NAME.
Referenced by main().
mate_ui_application_set_authors()
void mate_ui_application_set_authors (MateUiApplication * app, const gchar *const * authors)
mate_ui_application_set_authors: @app: A MateUiApplication
Authors
: (array zero-terminated=1): Array of author names
Sets the list of authors.
Definition at line 500 of file mate-ui-application.c.
Referenced by main().
mate_ui_application_set_comments()
void mate_ui_application_set_comments (MateUiApplication * app, const gchar * comments)
mate_ui_application_set_comments: @app: A MateUiApplication @comments: Brief description of the application
Sets a brief description of the application.
Definition at line 365 of file mate-ui-application.c.
References PROP_COMMENTS.
Referenced by main().
mate_ui_application_set_copyright()
void mate_ui_application_set_copyright (MateUiApplication * app, const gchar * copyright)
mate_ui_application_set_copyright: @app: A MateUiApplication
Copyright
: Copyright notice
Sets the copyright notice.
Definition at line 392 of file mate-ui-application.c.
References PROP_COPYRIGHT.
Referenced by main().
mate_ui_application_set_documenters()
void mate_ui_application_set_documenters (MateUiApplication * app, const gchar *const * documenters)
mate_ui_application_set_documenters: @app: A MateUiApplication @documenters: (array zero-terminated=1): Array of documenter names
Sets the list of documenters.
Definition at line 525 of file mate-ui-application.c.
mate_ui_application_set_help_uri()
void mate_ui_application_set_help_uri (MateUiApplication * app, const gchar * help_uri)
mate_ui_application_set_help_uri: @app: A MateUiApplication @help_uri: Help URI (e.g., "help:mate-calculator")
Sets the help URI for the application.
Definition at line 446 of file mate-ui-application.c.
References PROP_HELP_URI.
Referenced by main().
mate_ui_application_set_icon_name()
void mate_ui_application_set_icon_name (MateUiApplication * app, const gchar * icon_name)
mate_ui_application_set_icon_name: @app: A MateUiApplication @icon_name: Icon name from the icon theme
Sets the application icon name.
Definition at line 473 of file mate-ui-application.c.
References PROP_ICON_NAME.
Referenced by main().
mate_ui_application_set_license_type()
void mate_ui_application_set_license_type (MateUiApplication * app, GtkLicense license)
mate_ui_application_set_license_type: @app: A MateUiApplication @license: A GtkLicense value
Sets the license type.
Definition at line 550 of file mate-ui-application.c.
References PROP_LICENSE_TYPE.
Referenced by main().
mate_ui_application_set_version()
void mate_ui_application_set_version (MateUiApplication * app, const gchar * version)
mate_ui_application_set_version: @app: A MateUiApplication
Version
: Version string (e.g., "1.28.0")
Sets the application version.
Definition at line 338 of file mate-ui-application.c.
References PROP_VERSION.
Referenced by main().
mate_ui_application_set_website()
void mate_ui_application_set_website (MateUiApplication * app, const gchar * website)
mate_ui_application_set_website: @app: A MateUiApplication @website: Website URL
Sets the application website.
Definition at line 419 of file mate-ui-application.c.
References PROP_WEBSITE.
Referenced by main().
mate_ui_application_setup_common_actions()
void mate_ui_application_setup_common_actions (MateUiApplication * app)
mate_ui_application_setup_common_actions: @app: A MateUiApplication
Sets up common application actions (about, help, quit, preferences). These actions will be available as "app.about", "app.help", "app.quit", and "app.preferences".
Definition at line 639 of file mate-ui-application.c.
References NULL.
mate_ui_application_show_about()
void mate_ui_application_show_about (MateUiApplication * app)
mate_ui_application_show_about: @app: A MateUiApplication
Shows the About dialog using the application's metadata.
Definition at line 576 of file mate-ui-application.c.
References mate_ui_dialogs_show_about().
mate_ui_application_show_help()
void mate_ui_application_show_help (MateUiApplication * app, const gchar * section)
mate_ui_application_show_help: @app: A MateUiApplication
Definition at line 600 of file mate-ui-application.c.
References error, and NULL.