MATE Desktop Environment: mate-languages.h File Reference
mate-languages.h File Reference
#include <glib.h>
Functions
char * mate_get_language_from_locale (const char *locale, const char *translation)
char * mate_get_country_from_locale (const char *locale, const char *translation)
char ** mate_get_all_locales (void)
gboolean mate_parse_locale (const char *locale, char **language_codep, char **country_codep, char **codesetp, char **modifierp)
char * mate_normalize_locale (const char *locale)
gboolean mate_language_has_translations (const char *code)
char * mate_get_language_from_code (const char *code, const char *translation)
char * mate_get_country_from_code (const char *code, const char *translation)
Function Documentation
mate_get_all_locales()
char ** mate_get_all_locales (void)
Referenced by test_locales().
mate_get_country_from_code()
char * mate_get_country_from_code (const char * code, const char * translation)
Referenced by test_one_locale().
mate_get_country_from_locale()
char * mate_get_country_from_locale (const char * locale, const char * translation)
Referenced by test_one_locale().
mate_get_language_from_code()
char * mate_get_language_from_code (const char * code, const char * translation)
Referenced by test_one_locale().
mate_get_language_from_locale()
char * mate_get_language_from_locale (const char * locale, const char * translation)
Referenced by test_one_locale().
mate_language_has_translations()
gboolean mate_language_has_translations (const char * code)
Referenced by test_one_locale().
mate_normalize_locale()
char * mate_normalize_locale (const char * locale)
Definition at line 260 of file mate-languages.c.
References mate_parse_locale(), modifier, and NULL.
Referenced by test_one_locale().
mate_parse_locale()
gboolean mate_parse_locale (const char * locale, char ** language_codep, char ** country_codep, char ** codesetp, char ** modifierp)
mate_parse_locale: @locale: a locale string @language_codep: (out) (allow-none) (transfer full): location to store the language code, or NULL @country_codep: (out) (allow-none) (transfer full): location to store the country code, or NULL @codesetp: (out) (allow-none) (transfer full): location to store the codeset, or NULL @modifierp: (out) (allow-none) (transfer full): location to store the modifier, or NULL
Extracts the various components of a locale string of the form [language[_country][.codeset][@modifier]]. See http://en.wikipedia.org/wiki/Locale.
Return value: TRUE if parsing was successful.
Since: 1.22
Definition at line 122 of file mate-languages.c.
References error, FALSE, NULL, and TRUE.
Referenced by mate_normalize_locale(), and test_one_locale().