MATE Desktop Environment: matekbd-keyboard-config.c File Reference
matekbd-keyboard-config.c File Reference
#include <config.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <X11/keysym.h>
#include <glib/gi18n-lib.h>
#include <matekbd-keyboard-config.h>
#include <matekbd-config-private.h>
#include <matekbd-util.h>
Macros
#define MATEKBD_KEYBOARD_CONFIG_SCHEMA MATEKBD_CONFIG_SCHEMA ".kbd"
#define GROUP_SWITCHERS_GROUP "grp"
#define DEFAULT_GROUP_SWITCH "grp:shift_caps_toggle"
Functions
gboolean matekbd_keyboard_config_get_lv_descriptions (XklConfigRegistry *config_registry, const gchar *layout_name, const gchar *variant_name, gchar **layout_short_descr, gchar **layout_descr, gchar **variant_short_descr, gchar **variant_descr)
const gchar * matekbd_keyboard_config_merge_items (const gchar *parent, const gchar *child)
gboolean matekbd_keyboard_config_split_items (const gchar *merged, gchar **parent, gchar **child)
void matekbd_keyboard_config_init (MatekbdKeyboardConfig *kbd_config, XklEngine *engine)
void matekbd_keyboard_config_term (MatekbdKeyboardConfig *kbd_config)
void matekbd_keyboard_config_load_from_gsettings (MatekbdKeyboardConfig *kbd_config, MatekbdKeyboardConfig *kbd_config_default)
void matekbd_keyboard_config_load_from_x_current (MatekbdKeyboardConfig *kbd_config, XklConfigRec *data)
void matekbd_keyboard_config_load_from_x_initial (MatekbdKeyboardConfig *kbd_config, XklConfigRec *data)
gboolean matekbd_keyboard_config_equals (MatekbdKeyboardConfig *kbd_config1, MatekbdKeyboardConfig *kbd_config2)
void matekbd_keyboard_config_save_to_gsettings (MatekbdKeyboardConfig *kbd_config)
void matekbd_keyboard_config_model_set (MatekbdKeyboardConfig *kbd_config, const gchar *model_name)
void matekbd_keyboard_config_options_set (MatekbdKeyboardConfig *kbd_config, gint idx, const gchar *group_name, const gchar *option_name)
gboolean matekbd_keyboard_config_options_is_set (MatekbdKeyboardConfig *kbd_config, const gchar *group_name, const gchar *option_name)
gboolean matekbd_keyboard_config_activate (MatekbdKeyboardConfig *kbd_config)
void matekbd_keyboard_config_start_listen (MatekbdKeyboardConfig *kbd_config, GCallback func, gpointer user_data)
void matekbd_keyboard_config_stop_listen (MatekbdKeyboardConfig *kbd_config)
gboolean matekbd_keyboard_config_get_descriptions (XklConfigRegistry *config_registry, const gchar *name, gchar **layout_short_descr, gchar **layout_descr, gchar **variant_short_descr, gchar **variant_descr)
const gchar * matekbd_keyboard_config_format_full_layout (const gchar *layout_descr, const gchar *variant_descr)
gchar * matekbd_keyboard_config_to_string (const MatekbdKeyboardConfig *config)
gchar ** matekbd_keyboard_config_add_default_switch_option_if_necessary (gchar **layouts_list, gchar **options_list, gboolean *was_appended)
Variables
const gchar MATEKBD_KEYBOARD_CONFIG_KEY_MODEL [] = "model"
const gchar MATEKBD_KEYBOARD_CONFIG_KEY_LAYOUTS [] = "layouts"
const gchar MATEKBD_KEYBOARD_CONFIG_KEY_OPTIONS [] = "options"
const gchar * MATEKBD_KEYBOARD_CONFIG_ACTIVE []
Macro Definition Documentation
DEFAULT_GROUP_SWITCH
#define DEFAULT_GROUP_SWITCH "grp:shift_caps_toggle"
Definition at line 39 of file matekbd-keyboard-config.c.
Referenced by matekbd_keyboard_config_add_default_switch_option_if_necessary().
GROUP_SWITCHERS_GROUP
#define GROUP_SWITCHERS_GROUP "grp"
Definition at line 38 of file matekbd-keyboard-config.c.
Referenced by matekbd_keyboard_config_add_default_switch_option_if_necessary().
MATEKBD_KEYBOARD_CONFIG_SCHEMA
#define MATEKBD_KEYBOARD_CONFIG_SCHEMA MATEKBD_CONFIG_SCHEMA ".kbd"
Definition at line 36 of file matekbd-keyboard-config.c.
Referenced by matekbd_keyboard_config_init().
Function Documentation
matekbd_keyboard_config_activate()
gboolean matekbd_keyboard_config_activate (MatekbdKeyboardConfig * kbd_config)
Definition at line 624 of file matekbd-keyboard-config.c.
References data, and _MatekbdKeyboardConfig::engine.
matekbd_keyboard_config_add_default_switch_option_if_necessary()
gchar ** matekbd_keyboard_config_add_default_switch_option_if_necessary (gchar ** layouts_list, gchar ** options_list, gboolean * was_appended)
matekbd_keyboard_config_add_default_switch_option_if_necessary:
Returns: (transfer full) (array zero-terminated=1): List of options
Definition at line 766 of file matekbd-keyboard-config.c.
References DEFAULT_GROUP_SWITCH, FALSE, GROUP_SWITCHERS_GROUP, matekbd_keyboard_config_merge_items(), matekbd_keyboard_config_split_items(), matekbd_strv_append(), NULL, option, and TRUE.
matekbd_keyboard_config_equals()
gboolean matekbd_keyboard_config_equals (MatekbdKeyboardConfig * kbd_config1, MatekbdKeyboardConfig * kbd_config2)
Definition at line 546 of file matekbd-keyboard-config.c.
References _MatekbdKeyboardConfig::layouts_variants, _MatekbdKeyboardConfig::model, and NULL.
Referenced by enable_disable_restoring().
matekbd_keyboard_config_format_full_layout()
const gchar * matekbd_keyboard_config_format_full_layout (const gchar * layout_descr, const gchar * variant_descr)
Definition at line 687 of file matekbd-keyboard-config.c.
References NULL.
Referenced by matekbd_desktop_config_load_group_descriptions(), and xkb_layout_description_utf8().
matekbd_keyboard_config_get_descriptions()
gboolean matekbd_keyboard_config_get_descriptions (XklConfigRegistry * config_registry, const gchar * name, gchar ** layout_short_descr, gchar ** layout_descr, gchar ** variant_short_descr, gchar ** variant_descr)
Definition at line 666 of file matekbd-keyboard-config.c.
References config_registry, FALSE, matekbd_keyboard_config_get_lv_descriptions(), matekbd_keyboard_config_split_items(), name, and NULL.
Referenced by xkb_layout_description_utf8().
matekbd_keyboard_config_get_lv_descriptions()
gboolean matekbd_keyboard_config_get_lv_descriptions (XklConfigRegistry * config_registry, const gchar * layout_name, const gchar * variant_name, gchar ** layout_short_descr, gchar ** layout_descr, gchar ** variant_short_descr, gchar ** variant_descr)
Definition at line 81 of file matekbd-keyboard-config.c.
References config_registry, and NULL.
Referenced by matekbd_keyboard_config_get_descriptions().
matekbd_keyboard_config_init()
void matekbd_keyboard_config_init (MatekbdKeyboardConfig * kbd_config, XklEngine * engine)
Definition at line 408 of file matekbd-keyboard-config.c.
References _MatekbdKeyboardConfig::engine, engine, MATEKBD_KEYBOARD_CONFIG_SCHEMA, and _MatekbdKeyboardConfig::settings.
Referenced by enable_disable_restoring(), msd_keyboard_xkb_init(), and setup_xkb_tabs().
matekbd_keyboard_config_load_from_gsettings()
void matekbd_keyboard_config_load_from_gsettings (MatekbdKeyboardConfig * kbd_config, MatekbdKeyboardConfig * kbd_config_default)
Definition at line 431 of file matekbd-keyboard-config.c.
References _MatekbdKeyboardConfig::layouts_variants, MATEKBD_KEYBOARD_CONFIG_ACTIVE, _MatekbdKeyboardConfig::model, NULL, and _MatekbdKeyboardConfig::options.
Referenced by enable_disable_restoring().
matekbd_keyboard_config_load_from_x_current()
void matekbd_keyboard_config_load_from_x_current (MatekbdKeyboardConfig * kbd_config, XklConfigRec * data)
Definition at line 458 of file matekbd-keyboard-config.c.
References data, _MatekbdKeyboardConfig::engine, and NULL.
matekbd_keyboard_config_load_from_x_initial()
void matekbd_keyboard_config_load_from_x_initial (MatekbdKeyboardConfig * kbd_config, XklConfigRec * data)
Definition at line 477 of file matekbd-keyboard-config.c.
References data, _MatekbdKeyboardConfig::engine, and NULL.
Referenced by setup_xkb_tabs().
matekbd_keyboard_config_merge_items()
const gchar * matekbd_keyboard_config_merge_items (const gchar * parent, const gchar * child)
Definition at line 131 of file matekbd-keyboard-config.c.
References NULL.
Referenced by matekbd_keyboard_config_add_default_switch_option_if_necessary(), matekbd_keyboard_config_options_is_set(), and matekbd_keyboard_config_options_set().
matekbd_keyboard_config_model_set()
void matekbd_keyboard_config_model_set (MatekbdKeyboardConfig * kbd_config, const gchar * model_name)
General config functions (private)
Definition at line 579 of file matekbd-keyboard-config.c.
References _MatekbdKeyboardConfig::model, and NULL.
Referenced by matekbd_keyboard_config_term().
matekbd_keyboard_config_options_is_set()
gboolean matekbd_keyboard_config_options_is_set (MatekbdKeyboardConfig * kbd_config, const gchar * group_name, const gchar * option_name)
Definition at line 606 of file matekbd-keyboard-config.c.
References FALSE, matekbd_keyboard_config_merge_items(), NULL, _MatekbdKeyboardConfig::options, and TRUE.
matekbd_keyboard_config_options_set()
void matekbd_keyboard_config_options_set (MatekbdKeyboardConfig * kbd_config, gint idx, const gchar * group_name, const gchar * option_name)
Definition at line 590 of file matekbd-keyboard-config.c.
References idx, matekbd_keyboard_config_merge_items(), NULL, and _MatekbdKeyboardConfig::options.
matekbd_keyboard_config_save_to_gsettings()
void matekbd_keyboard_config_save_to_gsettings (MatekbdKeyboardConfig * kbd_config)
Definition at line 568 of file matekbd-keyboard-config.c.
References MATEKBD_KEYBOARD_CONFIG_ACTIVE, and _MatekbdKeyboardConfig::settings.
matekbd_keyboard_config_split_items()
gboolean matekbd_keyboard_config_split_items (const gchar * merged, gchar ** parent, gchar ** child)
Definition at line 151 of file matekbd-keyboard-config.c.
References FALSE, memcpy, NULL, strchr, and TRUE.
Referenced by matekbd_indicator_config_get_images_file(), matekbd_indicator_extract_layout_name(), matekbd_keyboard_config_add_default_switch_option_if_necessary(), matekbd_keyboard_config_get_descriptions(), and xkb_layout_preview_set_drawing_layout().
matekbd_keyboard_config_start_listen()
void matekbd_keyboard_config_start_listen (MatekbdKeyboardConfig * kbd_config, GCallback func, gpointer user_data)
matekbd_keyboard_config_start_listen: @func: (scope notified): a function to call when settings are changed
Definition at line 641 of file matekbd-keyboard-config.c.
References _MatekbdKeyboardConfig::config_listener_id, _MatekbdKeyboardConfig::settings, and user_data.
Referenced by msd_keyboard_xkb_init().
matekbd_keyboard_config_stop_listen()
void matekbd_keyboard_config_stop_listen (MatekbdKeyboardConfig * kbd_config)
Definition at line 651 of file matekbd-keyboard-config.c.
References _MatekbdKeyboardConfig::config_listener_id, and _MatekbdKeyboardConfig::settings.
matekbd_keyboard_config_term()
void matekbd_keyboard_config_term (MatekbdKeyboardConfig * kbd_config)
Definition at line 417 of file matekbd-keyboard-config.c.
References _MatekbdKeyboardConfig::layouts_variants, matekbd_keyboard_config_model_set(), NULL, _MatekbdKeyboardConfig::options, and _MatekbdKeyboardConfig::settings.
Referenced by enable_disable_restoring().
matekbd_keyboard_config_to_string()
gchar * matekbd_keyboard_config_to_string (const MatekbdKeyboardConfig * config)
Definition at line 701 of file matekbd-keyboard-config.c.
References _, _MatekbdKeyboardConfig::layouts_variants, _MatekbdKeyboardConfig::model, NULL, _MatekbdKeyboardConfig::options, and TRUE.
Variable Documentation
MATEKBD_KEYBOARD_CONFIG_ACTIVE
const gchar* MATEKBD_KEYBOARD_CONFIG_ACTIVE[]
Initial value:
                                           = {
    MATEKBD_KEYBOARD_CONFIG_KEY_MODEL,
    MATEKBD_KEYBOARD_CONFIG_KEY_LAYOUTS,
    MATEKBD_KEYBOARD_CONFIG_KEY_OPTIONS
}
Definition at line 45 of file matekbd-keyboard-config.c.
Referenced by matekbd_keyboard_config_load_from_gsettings(), and matekbd_keyboard_config_save_to_gsettings().
MATEKBD_KEYBOARD_CONFIG_KEY_LAYOUTS
const gchar MATEKBD_KEYBOARD_CONFIG_KEY_LAYOUTS[] = "layouts"
Definition at line 42 of file matekbd-keyboard-config.c.
MATEKBD_KEYBOARD_CONFIG_KEY_MODEL
const gchar MATEKBD_KEYBOARD_CONFIG_KEY_MODEL[] = "model"
Definition at line 41 of file matekbd-keyboard-config.c.
MATEKBD_KEYBOARD_CONFIG_KEY_OPTIONS
const gchar MATEKBD_KEYBOARD_CONFIG_KEY_OPTIONS[] = "options"
Definition at line 43 of file matekbd-keyboard-config.c.