MATE Desktop Environment: mate-rr-config.h File Reference
mate-rr-config.h File Reference
#include "mate-rr.h"
#include <glib.h>
#include <glib-object.h>
Classes
struct MateRROutputInfo
struct MateRROutputInfoClass
struct MateRRConfig
struct MateRRConfigClass
Macros
#define MATE_TYPE_RR_OUTPUT_INFO (mate_rr_output_info_get_type())
#define MATE_RR_OUTPUT_INFO(obj)
#define MATE_IS_RR_OUTPUT_INFO(obj)
#define MATE_RR_OUTPUT_INFO_CLASS(klass)
#define MATE_IS_RR_OUTPUT_INFO_CLASS(klass)
#define MATE_RR_OUTPUT_INFO_GET_CLASS(obj)
#define MATE_TYPE_RR_CONFIG (mate_rr_config_get_type())
#define MATE_RR_CONFIG(obj)
#define MATE_IS_RR_CONFIG(obj)
#define MATE_RR_CONFIG_CLASS(klass)
#define MATE_IS_RR_CONFIG_CLASS(klass)
#define MATE_RR_CONFIG_GET_CLASS(obj)
Typedefs
typedef struct MateRROutputInfoPrivate MateRROutputInfoPrivate
typedef struct MateRRConfigPrivate MateRRConfigPrivate
Functions
GType mate_rr_output_info_get_type (void)
char * mate_rr_output_info_get_name (MateRROutputInfo *self)
gboolean mate_rr_output_info_is_active (MateRROutputInfo *self)
void mate_rr_output_info_set_active (MateRROutputInfo *self, gboolean active)
void mate_rr_output_info_get_geometry (MateRROutputInfo *self, int *x, int *y, int *width, int *height)
void mate_rr_output_info_set_geometry (MateRROutputInfo *self, int x, int y, int width, int height)
int mate_rr_output_info_get_refresh_rate (MateRROutputInfo *self)
void mate_rr_output_info_set_refresh_rate (MateRROutputInfo *self, int rate)
MateRRRotation mate_rr_output_info_get_rotation (MateRROutputInfo *self)
void mate_rr_output_info_set_rotation (MateRROutputInfo *self, MateRRRotation rotation)
gboolean mate_rr_output_info_is_connected (MateRROutputInfo *self)
void mate_rr_output_info_get_vendor (MateRROutputInfo *self, gchar *vendor)
guint mate_rr_output_info_get_product (MateRROutputInfo *self)
guint mate_rr_output_info_get_serial (MateRROutputInfo *self)
double mate_rr_output_info_get_aspect_ratio (MateRROutputInfo *self)
char * mate_rr_output_info_get_display_name (MateRROutputInfo *self)
gboolean mate_rr_output_info_get_primary (MateRROutputInfo *self)
void mate_rr_output_info_set_primary (MateRROutputInfo *self, gboolean primary)
int mate_rr_output_info_get_preferred_width (MateRROutputInfo *self)
int mate_rr_output_info_get_preferred_height (MateRROutputInfo *self)
GType mate_rr_config_get_type (void)
MateRRConfig * mate_rr_config_new_current (MateRRScreen *screen, GError **error)
MateRRConfig * mate_rr_config_new_stored (MateRRScreen *screen, GError **error)
gboolean mate_rr_config_load_current (MateRRConfig *self, GError **error)
gboolean mate_rr_config_load_filename (MateRRConfig *self, const gchar *filename, GError **error)
gboolean mate_rr_config_match (MateRRConfig *config1, MateRRConfig *config2)
gboolean mate_rr_config_equal (MateRRConfig *config1, MateRRConfig *config2)
gboolean mate_rr_config_save (MateRRConfig *configuration, GError **error)
void mate_rr_config_sanitize (MateRRConfig *configuration)
gboolean mate_rr_config_ensure_primary (MateRRConfig *configuration)
gboolean mate_rr_config_apply_with_time (MateRRConfig *configuration, MateRRScreen *screen, guint32 timestamp, GError **error)
gboolean mate_rr_config_apply_from_filename_with_time (MateRRScreen *screen, const char *filename, guint32 timestamp, GError **error)
gboolean mate_rr_config_applicable (MateRRConfig *configuration, MateRRScreen *screen, GError **error)
gboolean mate_rr_config_get_clone (MateRRConfig *configuration)
void mate_rr_config_set_clone (MateRRConfig *configuration, gboolean clone)
MateRROutputInfo ** mate_rr_config_get_outputs (MateRRConfig *configuration)
char * mate_rr_config_get_backup_filename (void)
char * mate_rr_config_get_intended_filename (void)
Macro Definition Documentation
MATE_IS_RR_CONFIG
#define MATE_IS_RR_CONFIG (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_RR_CONFIG))
Definition at line 104 of file mate-rr-config.h.
Referenced by mate_rr_config_applicable(), mate_rr_config_apply_with_time(), mate_rr_config_ensure_primary(), mate_rr_config_equal(), mate_rr_config_get_clone(), mate_rr_config_get_outputs(), mate_rr_config_load_current(), mate_rr_config_load_filename(), mate_rr_config_match(), mate_rr_config_save(), mate_rr_config_set_clone(), and mate_rr_labeler_new().
MATE_IS_RR_CONFIG_CLASS
#define MATE_IS_RR_CONFIG_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_RR_CONFIG))
Definition at line 106 of file mate-rr-config.h.
MATE_IS_RR_OUTPUT_INFO
#define MATE_IS_RR_OUTPUT_INFO (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_RR_OUTPUT_INFO))
Definition at line 55 of file mate-rr-config.h.
Referenced by mate_rr_labeler_get_rgba_for_output(), mate_rr_output_info_get_aspect_ratio(), mate_rr_output_info_get_display_name(), mate_rr_output_info_get_geometry(), mate_rr_output_info_get_name(), mate_rr_output_info_get_preferred_height(), mate_rr_output_info_get_preferred_width(), mate_rr_output_info_get_primary(), mate_rr_output_info_get_product(), mate_rr_output_info_get_refresh_rate(), mate_rr_output_info_get_rotation(), mate_rr_output_info_get_serial(), mate_rr_output_info_get_vendor(), mate_rr_output_info_is_active(), mate_rr_output_info_is_connected(), mate_rr_output_info_set_active(), mate_rr_output_info_set_geometry(), mate_rr_output_info_set_primary(), mate_rr_output_info_set_refresh_rate(), and mate_rr_output_info_set_rotation().
MATE_IS_RR_OUTPUT_INFO_CLASS
#define MATE_IS_RR_OUTPUT_INFO_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_RR_OUTPUT_INFO))
Definition at line 57 of file mate-rr-config.h.
MATE_RR_CONFIG
#define MATE_RR_CONFIG (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_RR_CONFIG, MateRRConfig))
Definition at line 103 of file mate-rr-config.h.
MATE_RR_CONFIG_CLASS
#define MATE_RR_CONFIG_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_RR_CONFIG, MateRRConfigClass))
Definition at line 105 of file mate-rr-config.h.
MATE_RR_CONFIG_GET_CLASS
#define MATE_RR_CONFIG_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_RR_CONFIG, MateRRConfigClass))
Definition at line 107 of file mate-rr-config.h.
MATE_RR_OUTPUT_INFO
#define MATE_RR_OUTPUT_INFO (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_RR_OUTPUT_INFO, MateRROutputInfo))
Definition at line 54 of file mate-rr-config.h.
MATE_RR_OUTPUT_INFO_CLASS
#define MATE_RR_OUTPUT_INFO_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_RR_OUTPUT_INFO, MateRROutputInfoClass))
Definition at line 56 of file mate-rr-config.h.
MATE_RR_OUTPUT_INFO_GET_CLASS
#define MATE_RR_OUTPUT_INFO_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_RR_OUTPUT_INFO, MateRROutputInfoClass))
Definition at line 58 of file mate-rr-config.h.
MATE_TYPE_RR_CONFIG
#define MATE_TYPE_RR_CONFIG (mate_rr_config_get_type())
Definition at line 102 of file mate-rr-config.h.
Referenced by mate_rr_config_apply_from_filename_with_time(), mate_rr_config_new_current(), and mate_rr_config_new_stored().
MATE_TYPE_RR_OUTPUT_INFO
#define MATE_TYPE_RR_OUTPUT_INFO (mate_rr_output_info_get_type())
Definition at line 53 of file mate-rr-config.h.
Referenced by mate_rr_config_load_current().
Typedef Documentation
MateRRConfigPrivate
typedef struct MateRRConfigPrivate MateRRConfigPrivate
Definition at line 38 of file mate-rr-config.h.
MateRROutputInfoPrivate
typedef struct MateRROutputInfoPrivate MateRROutputInfoPrivate
Definition at line 37 of file mate-rr-config.h.
Function Documentation
mate_rr_config_applicable()
gboolean mate_rr_config_applicable (MateRRConfig * configuration, MateRRScreen * screen, GError ** error)
Definition at line 977 of file mate-rr-config.c.
References error, FALSE, MATE_IS_RR_CONFIG, MATE_IS_RR_SCREEN, NULL, and TRUE.
mate_rr_config_apply_from_filename_with_time()
gboolean mate_rr_config_apply_from_filename_with_time (MateRRScreen * screen, const char * filename, guint32 timestamp, GError ** error)
Definition at line 1351 of file mate-rr-config.c.
References error, FALSE, MATE_IS_RR_SCREEN, mate_rr_config_apply_with_time(), mate_rr_config_ensure_primary(), mate_rr_config_load_filename(), mate_rr_screen_refresh(), MATE_TYPE_RR_CONFIG, and NULL.
mate_rr_config_apply_with_time()
gboolean mate_rr_config_apply_with_time (MateRRConfig * configuration, MateRRScreen * screen, guint32 timestamp, GError ** error)
Definition at line 1282 of file mate-rr-config.c.
References error, FALSE, MATE_IS_RR_CONFIG, MATE_IS_RR_SCREEN, NULL, and TRUE.
Referenced by mate_rr_config_apply_from_filename_with_time().
mate_rr_config_ensure_primary()
gboolean mate_rr_config_ensure_primary (MateRRConfig * configuration)
Definition at line 1173 of file mate-rr-config.c.
References _mate_rr_output_name_is_laptop(), FALSE, MATE_IS_RR_CONFIG, NULL, MateRRConfigPrivate::outputs, MateRROutputInfoPrivate::primary, MateRRConfig::priv, MateRROutputInfo::priv, TRUE, MateRROutputInfoPrivate::x, and MateRROutputInfoPrivate::y.
Referenced by mate_rr_config_apply_from_filename_with_time().
mate_rr_config_equal()
gboolean mate_rr_config_equal (MateRRConfig * config1, MateRRConfig * config2)
Definition at line 913 of file mate-rr-config.c.
References FALSE, MATE_IS_RR_CONFIG, MateRROutputInfoPrivate::name, NULL, MateRRConfigPrivate::outputs, MateRRConfig::priv, MateRROutputInfo::priv, and TRUE.
mate_rr_config_get_backup_filename()
char * mate_rr_config_get_backup_filename (void)
Definition at line 1019 of file mate-rr-config.c.
References CONFIG_BACKUP_BASENAME, and NULL.
Referenced by mate_rr_config_save().
mate_rr_config_get_clone()
gboolean mate_rr_config_get_clone (MateRRConfig * self)
mate_rr_config_get_clone:
Returns: whether at least two outputs are at (0, 0) offset and they have the same width/height. Those outputs are of course connected and on (i.e. they have a CRTC assigned).
Definition at line 1411 of file mate-rr-config.c.
References MateRRConfigPrivate::clone, FALSE, MATE_IS_RR_CONFIG, and MateRRConfig::priv.
mate_rr_config_get_intended_filename()
char * mate_rr_config_get_intended_filename (void)
Definition at line 1026 of file mate-rr-config.c.
References CONFIG_INTENDED_BASENAME, and NULL.
Referenced by mate_rr_config_load_filename(), mate_rr_config_new_stored(), and mate_rr_config_save().
mate_rr_config_get_outputs()
MateRROutputInfo ** mate_rr_config_get_outputs (MateRRConfig * self)
mate_rr_config_get_outputs:
Returns: (array zero-terminated=1) (element-type MateDesktop.RROutputInfo) (transfer none): the output configuration for this MateRRConfig
Definition at line 1396 of file mate-rr-config.c.
References MATE_IS_RR_CONFIG, NULL, MateRRConfigPrivate::outputs, and MateRRConfig::priv.
Referenced by mate_rr_labeler_get_rgba_for_output().
mate_rr_config_get_type()
GType mate_rr_config_get_type (void)
References error.
mate_rr_config_load_current()
gboolean mate_rr_config_load_current (MateRRConfig * self, GError ** error)
Definition at line 495 of file mate-rr-config.c.
References _, MateRROutputInfoPrivate::aspect, MateRRConfigPrivate::clone, MateRROutputInfoPrivate::connected, decode_edid(), MateRROutputInfoPrivate::display_name, error, FALSE, MateRROutputInfoPrivate::height, make_display_name(), MATE_IS_RR_CONFIG, mate_rr_config_match(), mate_rr_crtc_get_current_mode(), mate_rr_crtc_get_current_rotation(), mate_rr_crtc_get_position(), mate_rr_mode_get_freq(), mate_rr_mode_get_height(), mate_rr_mode_get_width(), mate_rr_output_get_crtc(), mate_rr_output_get_edid_data(), mate_rr_output_get_is_primary(), mate_rr_output_get_name(), mate_rr_output_get_preferred_mode(), mate_rr_output_is_connected(), mate_rr_output_is_laptop(), mate_rr_output_list_modes(), MATE_RR_ROTATION_0, mate_rr_screen_list_outputs(), MATE_TYPE_RR_OUTPUT_INFO, MAX, memcpy, MateRROutputInfoPrivate::name, NULL, MateRROutputInfoPrivate::on, MateRRConfigPrivate::outputs, MateRROutputInfoPrivate::pref_height, MateRROutputInfoPrivate::pref_width, MateRROutputInfoPrivate::primary, MateRRConfig::priv, MateRROutputInfo::priv, MateRROutputInfoPrivate::product, MateRROutputInfoPrivate::rate, MateRROutputInfoPrivate::rotation, MateRRConfigPrivate::screen, MateRROutputInfoPrivate::serial, TRUE, MateRROutputInfoPrivate::vendor, MateRROutputInfoPrivate::width, MateRROutputInfoPrivate::x, and MateRROutputInfoPrivate::y.
Referenced by mate_rr_config_new_current().
mate_rr_config_load_filename()
gboolean mate_rr_config_load_filename (MateRRConfig * self, const gchar * filename, GError ** error)
References error.
mate_rr_config_match()
gboolean mate_rr_config_match (MateRRConfig * config1, MateRRConfig * config2)
Definition at line 890 of file mate-rr-config.c.
References FALSE, MATE_IS_RR_CONFIG, MateRROutputInfoPrivate::name, NULL, MateRRConfigPrivate::outputs, MateRRConfig::priv, MateRROutputInfo::priv, and TRUE.
Referenced by mate_rr_config_load_current(), mate_rr_config_load_filename(), and mate_rr_config_save().
mate_rr_config_new_current()
MateRRConfig * mate_rr_config_new_current (MateRRScreen * screen, GError ** error)
Definition at line 734 of file mate-rr-config.c.
References error, mate_rr_config_load_current(), MATE_TYPE_RR_CONFIG, and NULL.
Referenced by mate_rr_config_load_filename().
mate_rr_config_new_stored()
MateRRConfig * mate_rr_config_new_stored (MateRRScreen * screen, GError ** error)
Definition at line 748 of file mate-rr-config.c.
References error, mate_rr_config_get_intended_filename(), mate_rr_config_load_filename(), MATE_TYPE_RR_CONFIG, and NULL.
mate_rr_config_sanitize()
void mate_rr_config_sanitize (MateRRConfig * configuration)
Definition at line 1122 of file mate-rr-config.c.
References FALSE, MIN, MateRROutputInfoPrivate::on, MateRRConfigPrivate::outputs, MateRROutputInfoPrivate::primary, MateRRConfig::priv, MateRROutputInfo::priv, TRUE, MateRROutputInfoPrivate::x, and MateRROutputInfoPrivate::y.
mate_rr_config_save()
gboolean mate_rr_config_save (MateRRConfig * configuration, GError ** error)
Definition at line 1229 of file mate-rr-config.c.
References error, FALSE, MATE_IS_RR_CONFIG, mate_rr_config_get_backup_filename(), mate_rr_config_get_intended_filename(), mate_rr_config_match(), NULL, and TRUE.
mate_rr_config_set_clone()
void mate_rr_config_set_clone (MateRRConfig * configuration, gboolean clone)
Definition at line 1419 of file mate-rr-config.c.
References MateRRConfigPrivate::clone, MATE_IS_RR_CONFIG, and MateRRConfig::priv.
mate_rr_output_info_get_aspect_ratio()
double mate_rr_output_info_get_aspect_ratio (MateRROutputInfo * self)
Definition at line 207 of file mate-rr-output-info.c.
References MateRROutputInfoPrivate::aspect, MATE_IS_RR_OUTPUT_INFO, and MateRROutputInfo::priv.
mate_rr_output_info_get_display_name()
char * mate_rr_output_info_get_display_name (MateRROutputInfo * self)
mate_rr_output_info_get_display_name:
Returns: (transfer none): the display name of this output
Definition at line 219 of file mate-rr-output-info.c.
References MateRROutputInfoPrivate::display_name, MATE_IS_RR_OUTPUT_INFO, NULL, and MateRROutputInfo::priv.
mate_rr_output_info_get_geometry()
void mate_rr_output_info_get_geometry (MateRROutputInfo * self, int * x, int * y, int * width, int * height)
mate_rr_output_info_get_geometry: @self: a MateRROutputInfo @x: (out) (allow-none): @y: (out) (allow-none): @width: (out) (allow-none): @height: (out) (allow-none):
Definition at line 103 of file mate-rr-output-info.c.
References MateRROutputInfoPrivate::height, MATE_IS_RR_OUTPUT_INFO, MateRROutputInfo::priv, MateRROutputInfoPrivate::width, MateRROutputInfoPrivate::x, and MateRROutputInfoPrivate::y.
mate_rr_output_info_get_name()
char * mate_rr_output_info_get_name (MateRROutputInfo * self)
mate_rr_output_info_get_name:
Returns: (transfer none): the output name
Definition at line 69 of file mate-rr-output-info.c.
References MATE_IS_RR_OUTPUT_INFO, MateRROutputInfoPrivate::name, NULL, and MateRROutputInfo::priv.
mate_rr_output_info_get_preferred_height()
int mate_rr_output_info_get_preferred_height (MateRROutputInfo * self)
Definition at line 247 of file mate-rr-output-info.c.
References MATE_IS_RR_OUTPUT_INFO, MateRROutputInfoPrivate::pref_height, and MateRROutputInfo::priv.
mate_rr_output_info_get_preferred_width()
int mate_rr_output_info_get_preferred_width (MateRROutputInfo * self)
Definition at line 240 of file mate-rr-output-info.c.
References MATE_IS_RR_OUTPUT_INFO, MateRROutputInfoPrivate::pref_width, and MateRROutputInfo::priv.
mate_rr_output_info_get_primary()
gboolean mate_rr_output_info_get_primary (MateRROutputInfo * self)
Definition at line 226 of file mate-rr-output-info.c.
References FALSE, MATE_IS_RR_OUTPUT_INFO, MateRROutputInfoPrivate::primary, and MateRROutputInfo::priv.
mate_rr_output_info_get_product()
guint mate_rr_output_info_get_product (MateRROutputInfo * self)
Definition at line 193 of file mate-rr-output-info.c.
References MATE_IS_RR_OUTPUT_INFO, MateRROutputInfo::priv, and MateRROutputInfoPrivate::product.
mate_rr_output_info_get_refresh_rate()
int mate_rr_output_info_get_refresh_rate (MateRROutputInfo * self)
Definition at line 137 of file mate-rr-output-info.c.
References MATE_IS_RR_OUTPUT_INFO, MateRROutputInfo::priv, and MateRROutputInfoPrivate::rate.
mate_rr_output_info_get_rotation()
MateRRRotation mate_rr_output_info_get_rotation (MateRROutputInfo * self)
Definition at line 151 of file mate-rr-output-info.c.
References MATE_IS_RR_OUTPUT_INFO, MATE_RR_ROTATION_0, MateRROutputInfo::priv, and MateRROutputInfoPrivate::rotation.
mate_rr_output_info_get_serial()
guint mate_rr_output_info_get_serial (MateRROutputInfo * self)
Definition at line 200 of file mate-rr-output-info.c.
References MATE_IS_RR_OUTPUT_INFO, MateRROutputInfo::priv, and MateRROutputInfoPrivate::serial.
mate_rr_output_info_get_type()
GType mate_rr_output_info_get_type (void)
mate_rr_output_info_get_vendor()
void mate_rr_output_info_get_vendor (MateRROutputInfo * self, gchar * vendor)
mate_rr_output_info_get_vendor: @self: a MateRROutputInfo @vendor: (out caller-allocates) (array fixed-size=4):
Definition at line 182 of file mate-rr-output-info.c.
References MATE_IS_RR_OUTPUT_INFO, NULL, MateRROutputInfo::priv, and MateRROutputInfoPrivate::vendor.
mate_rr_output_info_is_active()
gboolean mate_rr_output_info_is_active (MateRROutputInfo * self)
mate_rr_output_info_is_active:
Returns: whether there is a CRTC assigned to this output (i.e. a signal is being sent to it)
Definition at line 81 of file mate-rr-output-info.c.
References FALSE, MATE_IS_RR_OUTPUT_INFO, MateRROutputInfoPrivate::on, and MateRROutputInfo::priv.
mate_rr_output_info_is_connected()
gboolean mate_rr_output_info_is_connected (MateRROutputInfo * self)
mate_rr_output_info_is_connected:
Returns: whether the output is physically connected to a monitor
Definition at line 170 of file mate-rr-output-info.c.
References MateRROutputInfoPrivate::connected, FALSE, MATE_IS_RR_OUTPUT_INFO, and MateRROutputInfo::priv.
mate_rr_output_info_set_active()
void mate_rr_output_info_set_active (MateRROutputInfo * self, gboolean active)
Definition at line 88 of file mate-rr-output-info.c.
References MATE_IS_RR_OUTPUT_INFO, MateRROutputInfoPrivate::on, and MateRROutputInfo::priv.
mate_rr_output_info_set_geometry()
void mate_rr_output_info_set_geometry (MateRROutputInfo * self, int x, int y, int width, int height)
mate_rr_output_info_set_geometry: @self: a MateRROutputInfo @x: x offset for monitor @y: y offset for monitor @width: monitor width @height: monitor height
Set the geometry for the monitor connected to the specified output.
Definition at line 127 of file mate-rr-output-info.c.
References MateRROutputInfoPrivate::height, MATE_IS_RR_OUTPUT_INFO, MateRROutputInfo::priv, MateRROutputInfoPrivate::width, MateRROutputInfoPrivate::x, and MateRROutputInfoPrivate::y.
mate_rr_output_info_set_primary()
void mate_rr_output_info_set_primary (MateRROutputInfo * self, gboolean primary)
Definition at line 233 of file mate-rr-output-info.c.
References MATE_IS_RR_OUTPUT_INFO, MateRROutputInfoPrivate::primary, and MateRROutputInfo::priv.
mate_rr_output_info_set_refresh_rate()
void mate_rr_output_info_set_refresh_rate (MateRROutputInfo * self, int rate)
Definition at line 144 of file mate-rr-output-info.c.
References MATE_IS_RR_OUTPUT_INFO, MateRROutputInfo::priv, and MateRROutputInfoPrivate::rate.
mate_rr_output_info_set_rotation()
void mate_rr_output_info_set_rotation (MateRROutputInfo * self, MateRRRotation rotation)
Definition at line 158 of file mate-rr-output-info.c.
References MATE_IS_RR_OUTPUT_INFO, MateRROutputInfo::priv, and MateRROutputInfoPrivate::rotation.