MATE Desktop Environment: matemixer-stream-private.h File Reference
matemixer-stream-private.h File Reference
#include <glib.h>
#include "matemixer-types.h"
Functions
void _mate_mixer_stream_set_default_control (MateMixerStream *stream, MateMixerStreamControl *control)
Function Documentation
_mate_mixer_stream_set_default_control()
void _mate_mixer_stream_set_default_control (MateMixerStream * stream, MateMixerStreamControl * control)
Definition at line 487 of file matemixer-stream.c.
References MATE_MIXER_IS_STREAM, MATE_MIXER_IS_STREAM_CONTROL, mate_mixer_stream_control_get_name(), mate_mixer_stream_get_name(), NULL, and PROP_DEFAULT_CONTROL.
Referenced by alsa_stream_set_default_control(), oss_stream_set_default_control(), pulse_sink_new(), and pulse_source_new().