MATE Desktop Environment: mateweather-xml.c File Reference
mateweather-xml.c File Reference
#include <string.h>
#include <math.h>
#include <locale.h>
#include <gtk/gtk.h>
#include <libxml/xmlreader.h>
#include "mateweather-xml.h"
#include "weather-priv.h"
Macros
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
Functions
GtkTreeModel * mateweather_xml_load_locations (void)
void mateweather_xml_free_locations (GtkTreeModel *locations)
Macro Definition Documentation
MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
Definition at line 31 of file mateweather-xml.c.
Function Documentation
mateweather_xml_free_locations()
void mateweather_xml_free_locations (GtkTreeModel * locations)
Definition at line 164 of file mateweather-xml.c.
References NULL.
Referenced by mateweather_xml_load_locations().
mateweather_xml_load_locations()
GtkTreeModel * mateweather_xml_load_locations (void)
Definition at line 121 of file mateweather-xml.c.
References mateweather_location_new_world(), mateweather_location_unref(), mateweather_xml_free_locations(), NULL, and TRUE.