MATE Desktop Environment: mate-keyboard-properties-xkbpv.c File Reference
mate-keyboard-properties-xkbpv.c File Reference
#include <libmatekbd/matekbd-keyboard-drawing.h>
#include "capplet-util.h"
#include "mate-keyboard-properties-xkb.h"
Functions
GtkWidget * xkb_layout_preview_create_widget (GtkBuilder *chooserDialog)
void xkb_layout_preview_update (GtkBuilder *chooser_dialog)
void xkb_layout_preview_set_drawing_layout (GtkWidget *kbdraw, const gchar *id)
Function Documentation
xkb_layout_preview_create_widget()
GtkWidget * xkb_layout_preview_create_widget (GtkBuilder * chooserDialog)
Definition at line 58 of file mate-keyboard-properties-xkbpv.c.
References MATEKBD_KEYBOARD_DRAWING, matekbd_keyboard_drawing_new(), and matekbd_keyboard_drawing_set_groups_levels().
Referenced by xkb_layout_choose().
xkb_layout_preview_set_drawing_layout()
void xkb_layout_preview_set_drawing_layout (GtkWidget * kbdraw, const gchar * id)
Definition at line 81 of file mate-keyboard-properties-xkbpv.c.
References data, engine, matekbd_keyboard_config_split_items(), MATEKBD_KEYBOARD_DRAWING, matekbd_keyboard_drawing_set_keyboard(), NULL, xkl_xkb_config_native_cleanup(), and xkl_xkb_config_native_prepare().
Referenced by xkb_layout_preview_update().
xkb_layout_preview_update()
void xkb_layout_preview_update (GtkBuilder * chooser_dialog)
Definition at line 68 of file mate-keyboard-properties-xkbpv.c.
References CWID, xkb_layout_chooser_get_selected_id(), and xkb_layout_preview_set_drawing_layout().
Referenced by xkb_layout_choose().