MATE Desktop Environment: mate-panel-applet-gsettings.c File Reference
mate-panel-applet-gsettings.c File Reference
#include <gtk/gtk.h>
#include <gio/gio.h>
#include "mate-panel-applet.h"
#include "mate-panel-applet-gsettings.h"
Functions
GSettings * mate_panel_applet_settings_new (MatePanelApplet *applet, gchar *schema)
GList * mate_panel_applet_settings_get_glist (GSettings *settings, gchar *key)
void mate_panel_applet_settings_set_glist (GSettings *settings, gchar *key, GList *list)
GSList * mate_panel_applet_settings_get_gslist (GSettings *settings, gchar *key)
void mate_panel_applet_settings_set_gslist (GSettings *settings, gchar *key, GSList *list)
Function Documentation
mate_panel_applet_settings_get_glist()
GList * mate_panel_applet_settings_get_glist (GSettings * settings, gchar * key)
Definition at line 147 of file mate-panel-applet-gsettings.c.
References key, and NULL.
mate_panel_applet_settings_get_gslist()
GSList * mate_panel_applet_settings_get_gslist (GSettings * settings, gchar * key)
Definition at line 176 of file mate-panel-applet-gsettings.c.
References key, and NULL.
mate_panel_applet_settings_new()
GSettings * mate_panel_applet_settings_new (MatePanelApplet * applet, gchar * schema)
mate_panel_applet_settings_new: @applet A #MatePanelApplet @schema applet's schema id
Returns: (transfer full): a #GSettings. free when you used it
Definition at line 128 of file mate-panel-applet-gsettings.c.
References mate_panel_applet_get_preferences_path(), and NULL.
Referenced by sensors_applet_init().
mate_panel_applet_settings_set_glist()
void mate_panel_applet_settings_set_glist (GSettings * settings, gchar * key, GList * list)
Definition at line 163 of file mate-panel-applet-gsettings.c.
References key, and TRUE.
Referenced by save_chartable().
mate_panel_applet_settings_set_gslist()
void mate_panel_applet_settings_set_gslist (GSettings * settings, gchar * key, GSList * list)
Definition at line 192 of file mate-panel-applet-gsettings.c.
References key, and TRUE.