MATE Desktop Environment: mate-ui-accel.c File Reference
mate-ui-accel.c File Reference
#include "config.h"
#include "mate-ui-accel.h"
Functions
MateUiAccelMap * mate_ui_accel_map_new (void)
void mate_ui_accel_map_free (MateUiAccelMap *map)
void mate_ui_accel_map_add (MateUiAccelMap *map, const gchar *action_name, const gchar *accel)
void mate_ui_accel_map_add_entries (MateUiAccelMap *map, const MateUiAccelEntry *entries, gsize n_entries)
void mate_ui_accel_map_remove (MateUiAccelMap *map, const gchar *action_name)
const gchar * mate_ui_accel_map_get (MateUiAccelMap *map, const gchar *action_name)
void mate_ui_accel_map_apply_to_app (MateUiAccelMap *map, GtkApplication *app)
gboolean mate_ui_accel_map_load (MateUiAccelMap *map, const gchar *filename, GError **error)
gboolean mate_ui_accel_map_save (MateUiAccelMap *map, const gchar *filename, GError **error)
GtkAccelGroup * mate_ui_accel_group_new (void)
gboolean mate_ui_accel_group_add (GtkAccelGroup *accel_group, const gchar *accel, GCallback callback, gpointer user_data)
gboolean mate_ui_accel_group_add_action (GtkAccelGroup *accel_group, const gchar *accel, GAction *action, GVariant *parameter)
gboolean mate_ui_accel_parse (const gchar *accel, guint *key, GdkModifierType *mods)
gchar * mate_ui_accel_to_string (guint key, GdkModifierType mods)
void mate_ui_accel_label_set_accel (GtkAccelLabel *label, const gchar *accel)
void mate_ui_accel_connect_to_widget (GtkWidget *widget, const gchar *accel, const gchar *signal_name)
void mate_ui_accel_set_app_accels (GtkApplication *app, const MateUiAccelEntry *entries, gsize n_entries)
void mate_ui_accel_clear_app_accels (GtkApplication *app, const gchar *action_name)
Function Documentation
mate_ui_accel_clear_app_accels()
void mate_ui_accel_clear_app_accels (GtkApplication * app, const gchar * action_name)
mate_ui_accel_clear_app_accels: @app: A #GtkApplication @action_name: The action name
Clears all accelerators for an action.
Definition at line 525 of file mate-ui-accel.c.
References NULL.
mate_ui_accel_connect_to_widget()
void mate_ui_accel_connect_to_widget (GtkWidget * widget, const gchar * accel, const gchar * signal_name)
mate_ui_accel_connect_to_widget: @widget: A widget @accel: The accelerator string @signal_name: Signal to emit
Connects an accelerator to emit a signal on a widget.
Definition at line 466 of file mate-ui-accel.c.
References key, and NULL.
mate_ui_accel_group_add()
gboolean mate_ui_accel_group_add (GtkAccelGroup * accel_group, const gchar * accel, GCallback callback, gpointer user_data)
mate_ui_accel_group_add: @accel_group: A #GtkAccelGroup @accel: The accelerator string @callback: Callback function @user_data: User data for callback
Adds an accelerator to the group with a callback.
Returns: TRUE if successfully added
Definition at line 298 of file mate-ui-accel.c.
References closure, data, FALSE, key, NULL, TRUE, and user_data.
mate_ui_accel_group_add_action()
gboolean mate_ui_accel_group_add_action (GtkAccelGroup * accel_group, const gchar * accel, GAction * action, GVariant * parameter)
mate_ui_accel_group_add_action: @accel_group: A #GtkAccelGroup @accel: The accelerator string @action: A #GAction to activate @parameter: (nullable): Parameter for the action
Adds an accelerator that activates an action.
Returns: TRUE if successfully added
Definition at line 366 of file mate-ui-accel.c.
References action, closure, data, FALSE, key, NULL, and TRUE.
mate_ui_accel_group_new()
GtkAccelGroup * mate_ui_accel_group_new (void)
mate_ui_accel_group_new:
Creates a new accelerator group.
Returns: (transfer full): A new #GtkAccelGroup
Definition at line 255 of file mate-ui-accel.c.
mate_ui_accel_label_set_accel()
void mate_ui_accel_label_set_accel (GtkAccelLabel * label, const gchar * accel)
mate_ui_accel_label_set_accel: @label: A #GtkAccelLabel @accel: The accelerator string
Sets the accelerator shown by an accel label.
Definition at line 441 of file mate-ui-accel.c.
References key, label, and NULL.
mate_ui_accel_map_add()
void mate_ui_accel_map_add (MateUiAccelMap * map, const gchar * action_name, const gchar * accel)
mate_ui_accel_map_add: @map: A MateUiAccelMap @action_name: The action name @accel: The accelerator string
Adds an accelerator to the map.
Definition at line 60 of file mate-ui-accel.c.
References NULL.
Referenced by mate_ui_accel_map_add_entries(), and mate_ui_accel_map_load().
mate_ui_accel_map_add_entries()
void mate_ui_accel_map_add_entries (MateUiAccelMap * map, const MateUiAccelEntry * entries, gsize n_entries)
mate_ui_accel_map_add_entries: @map: A MateUiAccelMap @entries: Array of MateUiAccelEntry structures @n_entries: Number of entries
Adds multiple accelerators to the map.
Definition at line 80 of file mate-ui-accel.c.
References mate_ui_accel_map_add(), and NULL.
mate_ui_accel_map_apply_to_app()
void mate_ui_accel_map_apply_to_app (MateUiAccelMap * map, GtkApplication * app)
mate_ui_accel_map_apply_to_app: @map: A MateUiAccelMap @app: A #GtkApplication
Applies the accelerator map to an application.
Definition at line 137 of file mate-ui-accel.c.
References key, and NULL.
mate_ui_accel_map_free()
void mate_ui_accel_map_free (MateUiAccelMap * map)
mate_ui_accel_map_free: @map: A MateUiAccelMap
Frees an accelerator map.
Definition at line 42 of file mate-ui-accel.c.
References NULL.
mate_ui_accel_map_get()
const gchar * mate_ui_accel_map_get (MateUiAccelMap * map, const gchar * action_name)
mate_ui_accel_map_get: @map: A MateUiAccelMap @action_name: The action name
Gets the accelerator for an action.
Returns: (transfer none) (nullable): The accelerator string or NULL
Definition at line 120 of file mate-ui-accel.c.
References NULL.
mate_ui_accel_map_load()
gboolean mate_ui_accel_map_load (MateUiAccelMap * map, const gchar * filename, GError ** error)
mate_ui_accel_map_load: @map: A MateUiAccelMap @filename: Path to the accelerator file @error: Return location for error
Loads accelerators from a file. File format is one entry per line: action_name=<accelerator>
Returns: TRUE on success
Definition at line 169 of file mate-ui-accel.c.
References action, error, FALSE, mate_ui_accel_map_add(), NULL, and TRUE.
mate_ui_accel_map_new()
MateUiAccelMap * mate_ui_accel_map_new (void)
mate_ui_accel_map_new:
Creates a new accelerator map.
Returns: (transfer full): A new MateUiAccelMap
Definition at line 28 of file mate-ui-accel.c.
mate_ui_accel_map_remove()
void mate_ui_accel_map_remove (MateUiAccelMap * map, const gchar * action_name)
mate_ui_accel_map_remove: @map: A MateUiAccelMap @action_name: The action name to remove
Removes an accelerator from the map.
Definition at line 101 of file mate-ui-accel.c.
References NULL.
mate_ui_accel_map_save()
gboolean mate_ui_accel_map_save (MateUiAccelMap * map, const gchar * filename, GError ** error)
mate_ui_accel_map_save: @map: A MateUiAccelMap @filename: Path to save to @error: Return location for error
Saves accelerators to a file.
Returns: TRUE on success
Definition at line 222 of file mate-ui-accel.c.
References error, FALSE, key, NULL, and TRUE.
mate_ui_accel_parse()
gboolean mate_ui_accel_parse (const gchar * accel, guint * key, GdkModifierType * mods)
mate_ui_accel_parse: @accel: The accelerator string @key: (out): Return location for key @mods: (out): Return location for modifiers
Parses an accelerator string.
Returns: TRUE if parsing succeeded
Definition at line 405 of file mate-ui-accel.c.
References FALSE, key, and NULL.
mate_ui_accel_set_app_accels()
void mate_ui_accel_set_app_accels (GtkApplication * app, const MateUiAccelEntry * entries, gsize n_entries)
mate_ui_accel_set_app_accels: @app: A #GtkApplication @entries: Array of MateUiAccelEntry @n_entries: Number of entries
Sets multiple application accelerators at once.
Definition at line 503 of file mate-ui-accel.c.
References NULL.
mate_ui_accel_to_string()
gchar * mate_ui_accel_to_string (guint key, GdkModifierType mods)
mate_ui_accel_to_string: @key: The key value @mods: The modifier mask
Converts an accelerator to a string.
Returns: (transfer full): The accelerator string
Definition at line 427 of file mate-ui-accel.c.
References key.