MATE Desktop Environment: mate-theme-info.c File Reference
mate-theme-info.c File Reference
#include <glib.h>
#include <glib/gi18n.h>
#include <gmodule.h>
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
#include <gio/gio.h>
#include <string.h>
#include <libmate-desktop/mate-desktop-item.h>
#include "mate-theme-info.h"
#include "gtkrc-utils.h"
#include <X11/Xcursor/Xcursor.h>
Macros
#define THEME_NAME "X-GNOME-Metatheme/Name"
#define THEME_COMMENT "X-GNOME-Metatheme/Comment"
#define GTK_THEME_KEY "X-GNOME-Metatheme/GtkTheme"
#define GTK_COLOR_SCHEME_KEY "X-GNOME-Metatheme/GtkColorScheme"
#define MARCO_THEME_KEY "X-GNOME-Metatheme/MetacityTheme"
#define ICON_THEME_KEY "X-GNOME-Metatheme/IconTheme"
#define CURSOR_THEME_KEY "X-GNOME-Metatheme/CursorTheme"
#define NOTIFICATION_THEME_KEY "X-GNOME-Metatheme/NotificationTheme"
#define CURSOR_SIZE_KEY "X-GNOME-Metatheme/CursorSize"
#define APPLICATION_FONT_KEY "X-GNOME-Metatheme/ApplicationFont"
#define DOCUMENTS_FONT_KEY "X-GNOME-Metatheme/DocumentsFont"
#define DESKTOP_FONT_KEY "X-GNOME-Metatheme/DesktopFont"
#define WINDOWTITLE_FONT_KEY "X-GNOME-Metatheme/WindowTitleFont"
#define MONOSPACE_FONT_KEY "X-GNOME-Metatheme/MonospaceFont"
#define BACKGROUND_IMAGE_KEY "X-GNOME-Metatheme/BackgroundImage"
#define HIDDEN_KEY "X-GNOME-Metatheme/Hidden"
#define BUF_SIZE sizeof(guint32) * cursor->width * cursor->height
Typedefs
typedef struct _ThemeCallbackData ThemeCallbackData
Functions
GQuark mate_theme_info_error_quark (void)
MateThemeMetaInfo * mate_theme_read_meta_theme (GFile *meta_theme_uri)
MateThemeInfo * mate_theme_info_new (void)
void mate_theme_info_free (MateThemeInfo *theme_info)
MateThemeInfo * mate_theme_info_find (const gchar *theme_name)
GList * mate_theme_info_find_by_type (guint elements)
gchar * gtk_theme_info_missing_engine (const gchar *gtk_theme, gboolean name_only)
MateThemeIconInfo * mate_theme_icon_info_new (void)
void mate_theme_icon_info_free (MateThemeIconInfo *icon_theme_info)
MateThemeIconInfo * mate_theme_icon_info_find (const gchar *icon_theme_name)
GList * mate_theme_icon_info_find_all (void)
gint mate_theme_icon_info_compare (MateThemeIconInfo *a, MateThemeIconInfo *b)
MateThemeCursorInfo * mate_theme_cursor_info_new (void)
void mate_theme_cursor_info_free (MateThemeCursorInfo *cursor_theme_info)
MateThemeCursorInfo * mate_theme_cursor_info_find (const gchar *cursor_theme_name)
GList * mate_theme_cursor_info_find_all (void)
gint mate_theme_cursor_info_compare (MateThemeCursorInfo *a, MateThemeCursorInfo *b)
MateThemeMetaInfo * mate_theme_meta_info_new (void)
void mate_theme_meta_info_free (MateThemeMetaInfo *meta_theme_info)
gboolean mate_theme_meta_info_validate (const MateThemeMetaInfo *info, GError **error)
MateThemeMetaInfo * mate_theme_meta_info_find (const char *meta_theme_name)
GList * mate_theme_meta_info_find_all (void)
gint mate_theme_meta_info_compare (MateThemeMetaInfo *a, MateThemeMetaInfo *b)
void mate_theme_info_register_theme_change (ThemeChangedCallback func, gpointer data)
gboolean mate_theme_color_scheme_parse (const gchar *scheme, GdkRGBA *colors)
gboolean mate_theme_color_scheme_equal (const gchar *s1, const gchar *s2)
void mate_theme_init ()
Macro Definition Documentation
APPLICATION_FONT_KEY
#define APPLICATION_FONT_KEY "X-GNOME-Metatheme/ApplicationFont"
Definition at line 51 of file mate-theme-info.c.
Referenced by mate_theme_read_meta_theme().
BACKGROUND_IMAGE_KEY
#define BACKGROUND_IMAGE_KEY "X-GNOME-Metatheme/BackgroundImage"
Definition at line 56 of file mate-theme-info.c.
Referenced by mate_theme_read_meta_theme().
BUF_SIZE
#define BUF_SIZE sizeof(guint32) * cursor->width * cursor->height
CURSOR_SIZE_KEY
#define CURSOR_SIZE_KEY "X-GNOME-Metatheme/CursorSize"
Definition at line 50 of file mate-theme-info.c.
CURSOR_THEME_KEY
#define CURSOR_THEME_KEY "X-GNOME-Metatheme/CursorTheme"
Definition at line 48 of file mate-theme-info.c.
DESKTOP_FONT_KEY
#define DESKTOP_FONT_KEY "X-GNOME-Metatheme/DesktopFont"
Definition at line 53 of file mate-theme-info.c.
DOCUMENTS_FONT_KEY
#define DOCUMENTS_FONT_KEY "X-GNOME-Metatheme/DocumentsFont"
Definition at line 52 of file mate-theme-info.c.
Referenced by mate_theme_read_meta_theme().
GTK_COLOR_SCHEME_KEY
#define GTK_COLOR_SCHEME_KEY "X-GNOME-Metatheme/GtkColorScheme"
Definition at line 45 of file mate-theme-info.c.
Referenced by mate_theme_read_meta_theme().
GTK_THEME_KEY
#define GTK_THEME_KEY "X-GNOME-Metatheme/GtkTheme"
Definition at line 44 of file mate-theme-info.c.
HIDDEN_KEY
#define HIDDEN_KEY "X-GNOME-Metatheme/Hidden"
Definition at line 57 of file mate-theme-info.c.
Referenced by mate_theme_read_meta_theme().
ICON_THEME_KEY
#define ICON_THEME_KEY "X-GNOME-Metatheme/IconTheme"
Definition at line 47 of file mate-theme-info.c.
MARCO_THEME_KEY
#define MARCO_THEME_KEY "X-GNOME-Metatheme/MetacityTheme"
Definition at line 46 of file mate-theme-info.c.
MONOSPACE_FONT_KEY
#define MONOSPACE_FONT_KEY "X-GNOME-Metatheme/MonospaceFont"
Definition at line 55 of file mate-theme-info.c.
NOTIFICATION_THEME_KEY
#define NOTIFICATION_THEME_KEY "X-GNOME-Metatheme/NotificationTheme"
Definition at line 49 of file mate-theme-info.c.
THEME_COMMENT
#define THEME_COMMENT "X-GNOME-Metatheme/Comment"
Definition at line 43 of file mate-theme-info.c.
Referenced by mate_theme_read_meta_theme().
THEME_NAME
#define THEME_NAME "X-GNOME-Metatheme/Name"
Definition at line 42 of file mate-theme-info.c.
Referenced by mate_theme_read_meta_theme().
WINDOWTITLE_FONT_KEY
#define WINDOWTITLE_FONT_KEY "X-GNOME-Metatheme/WindowTitleFont"
Definition at line 54 of file mate-theme-info.c.
Referenced by mate_theme_read_meta_theme().
Typedef Documentation
ThemeCallbackData
typedef struct _ThemeCallbackData ThemeCallbackData
Function Documentation
gtk_theme_info_missing_engine()
gchar * gtk_theme_info_missing_engine (const gchar * gtk_theme, gboolean name_only)
Definition at line 1402 of file mate-theme-info.c.
References engine, gtkrc_find_named(), gtkrc_get_details(), and NULL.
mate_theme_color_scheme_equal()
gboolean mate_theme_color_scheme_equal (const gchar * s1, const gchar * s2)
Definition at line 1776 of file mate-theme-info.c.
References FALSE, mate_theme_color_scheme_parse(), NUM_SYMBOLIC_COLORS, and TRUE.
Referenced by mate_meta_theme_set().
mate_theme_color_scheme_parse()
gboolean mate_theme_color_scheme_parse (const gchar * scheme, GdkRGBA * colors)
Definition at line 1722 of file mate-theme-info.c.
References COLOR_BASE, COLOR_BG, COLOR_FG, COLOR_SELECTED_BG, COLOR_SELECTED_FG, COLOR_TEXT, COLOR_TOOLTIP_BG, COLOR_TOOLTIP_FG, FALSE, NULL, NUM_SYMBOLIC_COLORS, and TRUE.
Referenced by mate_theme_color_scheme_equal().
mate_theme_cursor_info_compare()
gint mate_theme_cursor_info_compare (MateThemeCursorInfo * a, MateThemeCursorInfo * b)
Definition at line 1548 of file mate-theme-info.c.
References b, _MateThemeCursorInfo::name, and _MateThemeCursorInfo::path.
mate_theme_cursor_info_find()
MateThemeCursorInfo * mate_theme_cursor_info_find (const gchar * cursor_theme_name)
Definition at line 1527 of file mate-theme-info.c.
References NULL.
Referenced by mate_theme_init(), and theme_delete().
mate_theme_cursor_info_find_all()
GList * mate_theme_cursor_info_find_all (void)
Definition at line 1536 of file mate-theme-info.c.
References NULL.
Referenced by main().
mate_theme_cursor_info_free()
void mate_theme_cursor_info_free (MateThemeCursorInfo * cursor_theme_info)
Definition at line 1515 of file mate-theme-info.c.
References _MateThemeCursorInfo::name, NULL, _MateThemeCursorInfo::path, _MateThemeCursorInfo::readable_name, _MateThemeCursorInfo::sizes, _MateThemeCursorInfo::thumbnail, and TRUE.
mate_theme_cursor_info_new()
MateThemeCursorInfo * mate_theme_cursor_info_new (void)
Definition at line 1504 of file mate-theme-info.c.
References MATE_THEME_TYPE_CURSOR, and _MateThemeCursorInfo::type.
mate_theme_icon_info_compare()
gint mate_theme_icon_info_compare (MateThemeIconInfo * a, MateThemeIconInfo * b)
Definition at line 1491 of file mate-theme-info.c.
References b, _MateThemeCommonInfo::name, and _MateThemeCommonInfo::path.
mate_theme_icon_info_find()
MateThemeIconInfo * mate_theme_icon_info_find (const gchar * icon_theme_name)
Definition at line 1470 of file mate-theme-info.c.
References NULL.
Referenced by mate_theme_meta_info_validate(), and theme_delete().
mate_theme_icon_info_find_all()
GList * mate_theme_icon_info_find_all (void)
Definition at line 1479 of file mate-theme-info.c.
References NULL.
Referenced by main().
mate_theme_icon_info_free()
void mate_theme_icon_info_free (MateThemeIconInfo * icon_theme_info)
Definition at line 1461 of file mate-theme-info.c.
References _MateThemeCommonInfo::name, _MateThemeCommonInfo::path, and _MateThemeCommonInfo::readable_name.
mate_theme_icon_info_new()
MateThemeIconInfo * mate_theme_icon_info_new (void)
Definition at line 1450 of file mate-theme-info.c.
References MATE_THEME_TYPE_ICON, and _MateThemeCommonInfo::type.
mate_theme_info_error_quark()
GQuark mate_theme_info_error_quark (void)
Definition at line 277 of file mate-theme-info.c.
mate_theme_info_find()
MateThemeInfo * mate_theme_info_find (const gchar * theme_name)
Definition at line 1344 of file mate-theme-info.c.
Referenced by mate_theme_meta_info_validate(), and theme_delete().
mate_theme_info_find_by_type()
GList * mate_theme_info_find_by_type (guint elements)
Definition at line 1378 of file mate-theme-info.c.
References data, and NULL.
Referenced by main().
mate_theme_info_free()
void mate_theme_info_free (MateThemeInfo * theme_info)
Definition at line 1335 of file mate-theme-info.c.
References _MateThemeInfo::name, _MateThemeInfo::path, and _MateThemeInfo::readable_name.
mate_theme_info_new()
MateThemeInfo * mate_theme_info_new (void)
Definition at line 1324 of file mate-theme-info.c.
References MATE_THEME_TYPE_REGULAR, and _MateThemeInfo::type.
mate_theme_info_register_theme_change()
void mate_theme_info_register_theme_change (ThemeChangedCallback func, gpointer data)
Definition at line 1707 of file mate-theme-info.c.
References data, and NULL.
Referenced by style_init(), and themes_init().
mate_theme_init()
void mate_theme_init (void)
Definition at line 1795 of file mate-theme-info.c.
References FALSE, mate_theme_cursor_info_find(), NULL, and TRUE.
Referenced by main(), and themes_init().
mate_theme_meta_info_compare()
gint mate_theme_meta_info_compare (MateThemeMetaInfo * a, MateThemeMetaInfo * b)
Definition at line 1650 of file mate-theme-info.c.
References _MateThemeMetaInfo::application_font, b, _MateThemeMetaInfo::background_image, _MateThemeMetaInfo::comment, _MateThemeMetaInfo::desktop_font, _MateThemeMetaInfo::documents_font, _MateThemeMetaInfo::gtk_color_scheme, _MateThemeMetaInfo::gtk_theme_name, _MateThemeMetaInfo::icon_file, _MateThemeMetaInfo::icon_theme_name, _MateThemeMetaInfo::marco_theme_name, _MateThemeMetaInfo::monospace_font, _MateThemeMetaInfo::name, _MateThemeMetaInfo::notification_theme_name, _MateThemeMetaInfo::path, _MateThemeMetaInfo::readable_name, _MateThemeMetaInfo::sound_theme_name, and _MateThemeMetaInfo::windowtitle_font.
mate_theme_meta_info_find()
MateThemeMetaInfo * mate_theme_meta_info_find (const char * meta_theme_name)
Definition at line 1630 of file mate-theme-info.c.
References NULL.
Referenced by theme_delete().
mate_theme_meta_info_find_all()
GList * mate_theme_meta_info_find_all (void)
Definition at line 1638 of file mate-theme-info.c.
References NULL.
Referenced by main(), and themes_init().
mate_theme_meta_info_free()
void mate_theme_meta_info_free (MateThemeMetaInfo * meta_theme_info)
Definition at line 1572 of file mate-theme-info.c.
References _MateThemeMetaInfo::application_font, _MateThemeMetaInfo::background_image, _MateThemeMetaInfo::comment, _MateThemeMetaInfo::cursor_theme_name, _MateThemeMetaInfo::desktop_font, _MateThemeMetaInfo::documents_font, _MateThemeMetaInfo::gtk_color_scheme, _MateThemeMetaInfo::gtk_theme_name, _MateThemeMetaInfo::icon_file, _MateThemeMetaInfo::icon_theme_name, _MateThemeMetaInfo::marco_theme_name, _MateThemeMetaInfo::monospace_font, _MateThemeMetaInfo::name, _MateThemeMetaInfo::notification_theme_name, _MateThemeMetaInfo::path, _MateThemeMetaInfo::readable_name, _MateThemeMetaInfo::sound_theme_name, and _MateThemeMetaInfo::windowtitle_font.
Referenced by mate_theme_read_meta_theme(), and themes_shutdown().
mate_theme_meta_info_new()
MateThemeMetaInfo * mate_theme_meta_info_new (void)
Definition at line 1561 of file mate-theme-info.c.
References MATE_THEME_TYPE_METATHEME, and _MateThemeMetaInfo::type.
Referenced by mate_theme_read_meta_theme().
mate_theme_meta_info_validate()
gboolean mate_theme_meta_info_validate (const MateThemeMetaInfo * info, GError ** error)
Definition at line 1596 of file mate-theme-info.c.
References _, error, FALSE, _MateThemeInfo::has_gtk, _MateThemeInfo::has_marco, MATE_THEME_ERROR, MATE_THEME_ERROR_GTK_THEME_NOT_AVAILABLE, MATE_THEME_ERROR_ICON_THEME_NOT_AVAILABLE, MATE_THEME_ERROR_WM_THEME_NOT_AVAILABLE, mate_theme_icon_info_find(), mate_theme_info_find(), NULL, and TRUE.
mate_theme_read_meta_theme()
MateThemeMetaInfo * mate_theme_read_meta_theme (GFile * meta_theme_uri)
Definition at line 283 of file mate-theme-info.c.
References _MateThemeMetaInfo::application_font, APPLICATION_FONT_KEY, _MateThemeMetaInfo::background_image, BACKGROUND_IMAGE_KEY, _MateThemeMetaInfo::comment, _MateThemeMetaInfo::cursor_size, CURSOR_SIZE_KEY, CURSOR_THEME_KEY, _MateThemeMetaInfo::cursor_theme_name, _MateThemeMetaInfo::desktop_font, DESKTOP_FONT_KEY, _MateThemeMetaInfo::documents_font, DOCUMENTS_FONT_KEY, _MateThemeMetaInfo::gtk_color_scheme, GTK_COLOR_SCHEME_KEY, GTK_THEME_KEY, _MateThemeMetaInfo::gtk_theme_name, gtkrc_get_color_scheme_for_theme(), _MateThemeMetaInfo::hidden, HIDDEN_KEY, _MateThemeMetaInfo::icon_file, ICON_THEME_KEY, _MateThemeMetaInfo::icon_theme_name, int(), MARCO_THEME_KEY, _MateThemeMetaInfo::marco_theme_name, MATE_DESKTOP_ITEM_COMMENT, mate_desktop_item_get_boolean(), mate_desktop_item_get_localestring(), mate_desktop_item_get_string(), MATE_DESKTOP_ITEM_ICON, MATE_DESKTOP_ITEM_NAME, mate_desktop_item_new_from_uri(), mate_desktop_item_unref(), mate_theme_meta_info_free(), mate_theme_meta_info_new(), _MateThemeMetaInfo::monospace_font, MONOSPACE_FONT_KEY, _MateThemeMetaInfo::name, NOTIFICATION_THEME_KEY, _MateThemeMetaInfo::notification_theme_name, NULL, _MateThemeMetaInfo::path, _MateThemeMetaInfo::readable_name, THEME_COMMENT, THEME_NAME, _MateThemeMetaInfo::windowtitle_font, and WINDOWTITLE_FONT_KEY.