MATE Desktop Environment: matemixer.h File Reference
matemixer.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer-types.h>
#include <libmatemixer/matemixer-app-info.h>
#include <libmatemixer/matemixer-context.h>
#include <libmatemixer/matemixer-device.h>
#include <libmatemixer/matemixer-device-switch.h>
#include <libmatemixer/matemixer-enums.h>
#include <libmatemixer/matemixer-enum-types.h>
#include <libmatemixer/matemixer-stored-control.h>
#include <libmatemixer/matemixer-stream.h>
#include <libmatemixer/matemixer-stream-control.h>
#include <libmatemixer/matemixer-stream-switch.h>
#include <libmatemixer/matemixer-stream-toggle.h>
#include <libmatemixer/matemixer-switch.h>
#include <libmatemixer/matemixer-switch-option.h>
#include <libmatemixer/matemixer-version.h>
Functions
gboolean mate_mixer_init (void)
gboolean mate_mixer_is_initialized (void)
Function Documentation
mate_mixer_init()
gboolean mate_mixer_init (void)
mate_mixer_init:
Initializes the library. You must call this function before using any other function from the library.
Returns: TRUE on success or FALSE if the library installation does not provide support for any sound system backends.
Definition at line 61 of file matemixer.c.
References FALSE, NULL, and TRUE.
Referenced by main(), and main().
mate_mixer_is_initialized()
gboolean mate_mixer_is_initialized (void)
mate_mixer_is_initialized:
Returns TRUE if the library has been initialized.
Returns: TRUE or FALSE.
Definition at line 103 of file matemixer.c.
Referenced by mate_mixer_context_new(), and msd_media_keys_manager_start().