MATE Desktop Environment: mate-desktop-utils.c File Reference
mate-desktop-utils.c File Reference
#include <config.h>
#include <glib.h>
#include <gio/gio.h>
#include <glib/gi18n-lib.h>
#include <gdk/gdk.h>
#include <gtk/gtk.h>
#include <mate-desktop-utils.h>
#include "private.h"
Macros
#define MATE_DESKTOP_USE_UNSTABLE_API
#define LIGHTNESS_MULT 1.3
#define DARKNESS_MULT 0.7
Functions
void mate_desktop_prepend_terminal_to_vector (int *argc, char ***argv)
gboolean mate_gdk_spawn_command_line_on_screen (GdkScreen *screen, const gchar *command, GError **error)
void _mate_desktop_init_i18n (void)
void mate_desktop_gtk_style_get_light_color (GtkStyleContext *style, GtkStateFlags state, GdkRGBA *color)
void mate_desktop_gtk_style_get_dark_color (GtkStyleContext *style, GtkStateFlags state, GdkRGBA *color)
Macro Definition Documentation
DARKNESS_MULT
#define DARKNESS_MULT 0.7
Definition at line 444 of file mate-desktop-utils.c.
LIGHTNESS_MULT
#define LIGHTNESS_MULT 1.3
Definition at line 443 of file mate-desktop-utils.c.
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 34 of file mate-desktop-utils.c.
Function Documentation
_mate_desktop_init_i18n()
void _mate_desktop_init_i18n (void)
Definition at line 220 of file mate-desktop-utils.c.
References FALSE, GETTEXT_PACKAGE, MATELOCALEDIR, and TRUE.
Referenced by mate_desktop_item_new(), mate_desktop_prepend_terminal_to_vector(), and mate_rr_screen_new().
mate_desktop_gtk_style_get_dark_color()
void mate_desktop_gtk_style_get_dark_color (GtkStyleContext * style, GtkStateFlags state, GdkRGBA * color)
Definition at line 458 of file mate-desktop-utils.c.
References DARKNESS_MULT, and NULL.
mate_desktop_gtk_style_get_light_color()
void mate_desktop_gtk_style_get_light_color (GtkStyleContext * style, GtkStateFlags state, GdkRGBA * color)
Definition at line 446 of file mate-desktop-utils.c.
References LIGHTNESS_MULT, and NULL.
mate_desktop_prepend_terminal_to_vector()
void mate_desktop_prepend_terminal_to_vector (int * argc, char *** argv)
mate_desktop_prepend_terminal_to_vector: @argc: a pointer to the vector size @argv: a pointer to the vector
Prepends a terminal (either the one configured as default in the user's MATE setup, or one of the common xterm emulators) to the passed in vector, modifying it in the process. The vector should be allocated with #g_malloc, as this will #g_free the original vector. Also all elements must have been allocated separately. That is the standard glib/MATE way of doing vectors however. If the integer that @argc points to is negative, the size will first be computed. Also note that passing in pointers to a vector that is empty, will just create a new vector for you.
Definition at line 69 of file mate-desktop-utils.c.
References _, _mate_desktop_init_i18n(), and NULL.
mate_gdk_spawn_command_line_on_screen()
gboolean mate_gdk_spawn_command_line_on_screen (GdkScreen * screen, const gchar * command, GError ** error)
mate_gdk_spawn_command_line_on_screen: @screen: a GdkScreen @command: a command line @error: return location for errors
This is a replacement for gdk_spawn_command_line_on_screen, deprecated in GDK 2.24 and removed in GDK 3.0.
gdk_spawn_command_line_on_screen is like g_spawn_command_line_async(), except the child process is spawned in such an environment that on calling gdk_display_open() it would be returned a GdkDisplay with screen as the default screen.
This is useful for applications which wish to launch an application on a specific screen.
Returns: TRUE on success, FALSE if error is set.
Since: 1.7.1
Definition at line 201 of file mate-desktop-utils.c.
References error, FALSE, and NULL.
Referenced by eel_mate_open_terminal_on_screen(), fm_directory_view_move_copy_items(), gvc_stream_applet_icon_volume_control(), and panel_lock_screen_action().