MATE Desktop Environment: mate-keyboard-properties-xkbot.c File Reference
mate-keyboard-properties-xkbot.c File Reference
#include <glib/gi18n.h>
#include <string.h>
#include <gio/gio.h>
#include "capplet-util.h"
#include "mate-keyboard-properties-xkb.h"
Macros
#define OPTION_ID_PROP "optionID"
#define SELCOUNTER_PROP "selectionCounter"
#define EXPANDERS_PROP "expandersList"
Functions
GSList * xkb_options_get_selected_list (void)
void xkb_options_load_options (GtkBuilder *dialog)
void xkb_options_popup_dialog (GtkBuilder *dialog)
void xkb_options_register_gsettings_listener (GtkBuilder *dialog)
Macro Definition Documentation
EXPANDERS_PROP
#define EXPANDERS_PROP "expandersList"
Definition at line 47 of file mate-keyboard-properties-xkbot.c.
Referenced by xkb_options_load_options().
OPTION_ID_PROP
#define OPTION_ID_PROP "optionID"
Definition at line 45 of file mate-keyboard-properties-xkbot.c.
SELCOUNTER_PROP
#define SELCOUNTER_PROP "selectionCounter"
Definition at line 46 of file mate-keyboard-properties-xkbot.c.
Function Documentation
xkb_options_get_selected_list()
GSList * xkb_options_get_selected_list (void)
Definition at line 50 of file mate-keyboard-properties-xkbot.c.
References initial_config, NULL, and xkb_kbd_settings.
xkb_options_load_options()
void xkb_options_load_options (GtkBuilder * dialog)
Definition at line 386 of file mate-keyboard-properties-xkbot.c.
References config_registry, EXPANDERS_PROP, FALSE, NULL, and WID.
Referenced by xkb_options_popup_dialog().
xkb_options_popup_dialog()
void xkb_options_popup_dialog (GtkBuilder * dialog)
Definition at line 446 of file mate-keyboard-properties-xkbot.c.
References CWID, NULL, WID, and xkb_options_load_options().
Referenced by setup_xkb_tabs().
xkb_options_register_gsettings_listener()
void xkb_options_register_gsettings_listener (GtkBuilder * dialog)
Definition at line 513 of file mate-keyboard-properties-xkbot.c.
References xkb_kbd_settings.
Referenced by setup_xkb_tabs().