MATE Desktop Environment: matemixer-device.c File Reference
matemixer-device.c File Reference
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include "matemixer-device.h"
#include "matemixer-device-switch.h"
#include "matemixer-stream.h"
#include "matemixer-switch.h"
Enumerations
enum {
PROP_0 , PROP_NAME , PROP_LABEL , PROP_ICON ,
N_PROPERTIES
}
enum {
STREAM_ADDED , STREAM_REMOVED , SWITCH_ADDED , SWITCH_REMOVED ,
N_SIGNALS
}
Functions
: name of the removed switch
const gchar * mate_mixer_device_get_name (MateMixerDevice *device)
const gchar * mate_mixer_device_get_label (MateMixerDevice *device)
const gchar * mate_mixer_device_get_icon (MateMixerDevice *device)
: a switch name
mate_mixer_device_get_switch: @device: a MateMixerDevice
Gets the device switch with the given name.
Note that this function will only return a switch that belongs to the device and not to a stream of the device. See mate_mixer_device_list_switches() for information about the difference between device and stream switches.
To get a stream switch, rather than a device switch, use mate_mixer_stream_get_switch().
Returns: a MateMixerDeviceSwitch or NULL if there is no such device switch.
MateMixerDeviceSwitch * mate_mixer_device_get_switch (MateMixerDevice *device, const gchar *name)
const GList * mate_mixer_device_list_streams (MateMixerDevice *device)
const GList * mate_mixer_device_list_switches (MateMixerDevice *device)
: a stream name
mate_mixer_device_get_stream: @device: a MateMixerDevice
Gets the device stream with the given name.
Returns: a MateMixerStream or NULL if there is no such stream.
MateMixerStream * mate_mixer_device_get_stream (MateMixerDevice *device, const gchar *name)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_NAME
PROP_LABEL
PROP_ICON
N_PROPERTIES
Definition at line 44 of file matemixer-device.c.
anonymous enum
anonymous enum
Enumerator
STREAM_ADDED
STREAM_REMOVED
SWITCH_ADDED
SWITCH_REMOVED
N_SIGNALS
Definition at line 54 of file matemixer-device.c.
Function Documentation
mate_mixer_device_get_icon()
const gchar * mate_mixer_device_get_icon (MateMixerDevice * device)
mate_mixer_device_get_icon: @device: a MateMixerDevice
Gets the XDG icon name of the device.
Returns: the icon name or NULL.
Definition at line 359 of file matemixer-device.c.
References MATE_MIXER_IS_DEVICE, NULL, and _MateMixerDevice::priv.
mate_mixer_device_get_label()
const gchar * mate_mixer_device_get_label (MateMixerDevice * device)
mate_mixer_device_get_label: @device: a MateMixerDevice
Gets the label of the device.
This is a potentially translated string that should be presented to users in the user interface.
Returns: the label of the device.
Definition at line 343 of file matemixer-device.c.
References MATE_MIXER_IS_DEVICE, NULL, and _MateMixerDevice::priv.
Referenced by alsa_device_open(), alsa_stream_new(), oss_device_open(), and oss_stream_new().
mate_mixer_device_get_name()
const gchar * mate_mixer_device_get_name (MateMixerDevice * device)
mate_mixer_device_get_name: @device: a MateMixerDevice
Gets the name of the device.
The name serves as a unique identifier and in most cases it is not in a user-readable form.
The returned name is guaranteed to be unique across all the known devices and may be used to get the MateMixerDevice using mate_mixer_context_get_device().
Returns: the name of the device.
Definition at line 324 of file matemixer-device.c.
References MATE_MIXER_IS_DEVICE, NULL, and _MateMixerDevice::priv.
Referenced by alsa_device_open(), mate_mixer_backend_get_device(), and oss_device_load().
mate_mixer_device_get_stream()
MateMixerStream * mate_mixer_device_get_stream (MateMixerDevice * device, const gchar * name)
Definition at line 376 of file matemixer-device.c.
References MATE_MIXER_DEVICE_GET_CLASS, MATE_MIXER_IS_DEVICE, name, and NULL.
mate_mixer_device_get_switch()
MateMixerDeviceSwitch * mate_mixer_device_get_switch (MateMixerDevice * device, const gchar * name)
Definition at line 401 of file matemixer-device.c.
References MATE_MIXER_DEVICE_GET_CLASS, MATE_MIXER_IS_DEVICE, name, and NULL.
mate_mixer_device_list_streams()
const GList * mate_mixer_device_list_streams (MateMixerDevice * device)
mate_mixer_device_list_streams: @device: a MateMixerDevice
Gets the list of streams that belong to the device.
The returned #GList is owned by the MateMixerDevice and may be invalidated at any time.
Returns: a #GList of the device streams or NULL if the device does not have any streams.
Definition at line 422 of file matemixer-device.c.
References _MateMixerDeviceClass::list_streams, MATE_MIXER_DEVICE_GET_CLASS, MATE_MIXER_IS_DEVICE, and NULL.
mate_mixer_device_list_switches()
const GList * mate_mixer_device_list_switches (MateMixerDevice * device)
mate_mixer_device_list_switches: @device: a MateMixerDevice
Gets the list of switches the belong to the device.
Note that a switch may belong either to a device, or to a stream. Unlike stream switches, device switches returned by this function are not classified as input or output (as streams are), but they operate on the whole device.
Use mate_mixer_stream_list_switches() to get a list of switches that belong to a stream.
The returned #GList is owned by the MateMixerDevice and may be invalidated at any time.
Returns: a #GList of the device switches or NULL if the device does not have any switches.
Definition at line 456 of file matemixer-device.c.
References _MateMixerDeviceClass::list_switches, MATE_MIXER_DEVICE_GET_CLASS, MATE_MIXER_IS_DEVICE, and NULL.