MATE Desktop Environment: mate-calc.c File Reference
mate-calc.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <locale.h>
#include <glib/gi18n.h>
#include "math-window.h"
#include "math-preferences.h"
#include "mp-equation.h"
#include "unit-manager.h"
#include "utility.h"
Functions
int main (int argc, char **argv)
Variables
GSettings * g_settings_var = NULL
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 191 of file mate-calc.c.
References FALSE, g_settings_var, GETTEXT_PACKAGE, math_buttons_set_mode(), math_buttons_set_programming_base(), math_equation_new(), math_equation_set_accuracy(), math_equation_set_angle_units(), math_equation_set_number_format(), math_equation_set_show_thousands_separators(), math_equation_set_show_trailing_zeroes(), math_equation_set_source_currency(), math_equation_set_source_units(), math_equation_set_target_currency(), math_equation_set_target_units(), math_equation_set_word_size(), math_window_get_buttons(), math_window_new(), math_window_set_show_history(), and NULL.
Variable Documentation
g_settings_var
GSettings* g_settings_var = NULL
Definition at line 28 of file mate-calc.c.
Referenced by main(), math_buttons_set_programming_base(), math_equation_set_source_currency(), math_equation_set_source_units(), math_equation_set_target_currency(), and math_equation_set_target_units().