MATE Desktop Environment: mateweather-applet.h File Reference
mateweather-applet.h File Reference
#include "mateweather.h"
Macros
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
Functions
void mateweather_applet_create (MateWeatherApplet *gw_applet)
gint timeout_cb (gpointer data)
gint suncalc_timeout_cb (gpointer data)
void mateweather_update (MateWeatherApplet *applet)
Macro Definition Documentation
MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
Definition at line 16 of file mateweather-applet.h.
Function Documentation
mateweather_applet_create()
void mateweather_applet_create (MateWeatherApplet * gw_applet) extern
Definition at line 325 of file mateweather-applet.c.
References _, action, _MateWeatherApplet::applet, _MateWeatherPrefs::detailed, _MateWeatherPrefs::distance_unit, DISTANCE_UNIT_INVALID, FALSE, GETTEXT_PACKAGE, _MateWeatherPrefs::location, MATE_PANEL_APPLET_EXPAND_MINOR, mate_panel_applet_get_locked_down(), mate_panel_applet_get_orient(), mate_panel_applet_get_size(), mate_panel_applet_set_flags(), mate_panel_applet_setup_menu_from_resource(), _MateWeatherApplet::mateweather_pref, NULL, _MateWeatherApplet::orient, _MateWeatherPrefs::pressure_unit, PRESSURE_UNIT_INVALID, _MateWeatherPrefs::radar_enabled, _MateWeatherPrefs::show_notifications, _MateWeatherApplet::size, _MateWeatherPrefs::speed_unit, SPEED_UNIT_INVALID, TEMP_UNIT_INVALID, _MateWeatherPrefs::temperature_unit, TRUE, _MateWeatherPrefs::update_enabled, and _MateWeatherPrefs::update_interval.
mateweather_update()
void mateweather_update (MateWeatherApplet * applet) extern
Definition at line 527 of file mateweather-applet.c.
References _, _MateWeatherApplet::applet, _MateWeatherPrefs::detailed, _MateWeatherPrefs::distance_unit, _WeatherPrefs::distance_unit, FORECAST_STATE, FORECAST_ZONE, _MateWeatherPrefs::location, _MateWeatherApplet::mateweather_info, _MateWeatherApplet::mateweather_pref, NULL, _MateWeatherPrefs::pressure_unit, _WeatherPrefs::pressure_unit, _MateWeatherPrefs::radar, _WeatherPrefs::radar, _WeatherPrefs::radar_custom_url, _MateWeatherPrefs::radar_enabled, _MateWeatherPrefs::speed_unit, _WeatherPrefs::speed_unit, _MateWeatherPrefs::temperature_unit, _WeatherPrefs::temperature_unit, _WeatherPrefs::type, _MateWeatherPrefs::use_custom_radar_url, weather_info_free(), weather_info_get_location(), weather_info_new, weather_info_update, and weather_location_equal().
Referenced by timeout_cb().
suncalc_timeout_cb()
gint suncalc_timeout_cb (gpointer data) extern
Definition at line 520 of file mateweather-applet.c.
References data.
timeout_cb()
gint timeout_cb (gpointer data) extern
Definition at line 406 of file mateweather-applet.c.
References data, and mateweather_update().