MATE Desktop Environment: mate-theme-info.h File Reference
mate-theme-info.h File Reference
#include <glib.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gdk/gdk.h>
Classes
struct _MateThemeCommonInfo
struct _MateThemeInfo
struct _MateThemeCursorInfo
struct _MateThemeMetaInfo
Macros
#define MATE_THEME_ERROR mate_theme_info_error_quark()
Typedefs
typedef struct _MateThemeCommonInfo MateThemeCommonInfo
typedef struct _MateThemeCommonInfo MateThemeIconInfo
typedef struct _MateThemeInfo MateThemeInfo
typedef struct _MateThemeCursorInfo MateThemeCursorInfo
typedef struct _MateThemeMetaInfo MateThemeMetaInfo
typedef void(* ThemeChangedCallback) (MateThemeCommonInfo *theme, MateThemeChangeType change_type, MateThemeElement element_type, gpointer user_data)
Enumerations
enum MateThemeType { MATE_THEME_TYPE_METATHEME , MATE_THEME_TYPE_ICON , MATE_THEME_TYPE_CURSOR , MATE_THEME_TYPE_REGULAR }
enum MateThemeChangeType { MATE_THEME_CHANGE_CREATED , MATE_THEME_CHANGE_DELETED , MATE_THEME_CHANGE_CHANGED }
enum MateThemeElement { MATE_THEME_MARCO = 1 << 0 , MATE_THEME_GTK_2 = 1 << 1 , MATE_THEME_GTK_2_KEYBINDING = 1 << 2 }
enum {
COLOR_FG , COLOR_BG , COLOR_TEXT , COLOR_BASE ,
COLOR_SELECTED_FG , COLOR_SELECTED_BG , COLOR_TOOLTIP_FG , COLOR_TOOLTIP_BG ,
NUM_SYMBOLIC_COLORS
}
enum {
MATE_THEME_ERROR_GTK_THEME_NOT_AVAILABLE = 1 , MATE_THEME_ERROR_WM_THEME_NOT_AVAILABLE , MATE_THEME_ERROR_ICON_THEME_NOT_AVAILABLE , MATE_THEME_ERROR_GTK_ENGINE_NOT_AVAILABLE ,
MATE_THEME_ERROR_UNKNOWN
}
Functions
MateThemeInfo * mate_theme_info_new (void)
void mate_theme_info_free (MateThemeInfo *theme_info)
MateThemeInfo * mate_theme_info_find (const gchar *theme_name)
GList * mate_theme_info_find_by_type (guint elements)
GQuark mate_theme_info_error_quark (void)
gchar * gtk_theme_info_missing_engine (const gchar *gtk_theme, gboolean nameOnly)
MateThemeIconInfo * mate_theme_icon_info_new (void)
void mate_theme_icon_info_free (MateThemeIconInfo *icon_theme_info)
MateThemeIconInfo * mate_theme_icon_info_find (const gchar *icon_theme_name)
GList * mate_theme_icon_info_find_all (void)
gint mate_theme_icon_info_compare (MateThemeIconInfo *a, MateThemeIconInfo *b)
MateThemeCursorInfo * mate_theme_cursor_info_new (void)
void mate_theme_cursor_info_free (MateThemeCursorInfo *info)
MateThemeCursorInfo * mate_theme_cursor_info_find (const gchar *name)
GList * mate_theme_cursor_info_find_all (void)
gint mate_theme_cursor_info_compare (MateThemeCursorInfo *a, MateThemeCursorInfo *b)
MateThemeMetaInfo * mate_theme_meta_info_new (void)
void mate_theme_meta_info_free (MateThemeMetaInfo *meta_theme_info)
MateThemeMetaInfo * mate_theme_meta_info_find (const gchar *meta_theme_name)
GList * mate_theme_meta_info_find_all (void)
gint mate_theme_meta_info_compare (MateThemeMetaInfo *a, MateThemeMetaInfo *b)
gboolean mate_theme_meta_info_validate (const MateThemeMetaInfo *info, GError **error)
MateThemeMetaInfo * mate_theme_read_meta_theme (GFile *meta_theme_uri)
void mate_theme_init (void)
void mate_theme_info_register_theme_change (ThemeChangedCallback func, gpointer data)
gboolean mate_theme_color_scheme_parse (const gchar *scheme, GdkRGBA *colors)
gboolean mate_theme_color_scheme_equal (const gchar *s1, const gchar *s2)
Macro Definition Documentation
MATE_THEME_ERROR
#define MATE_THEME_ERROR mate_theme_info_error_quark()
Definition at line 134 of file mate-theme-info.h.
Referenced by mate_theme_meta_info_validate().
Typedef Documentation
MateThemeCommonInfo
typedef struct _MateThemeCommonInfo MateThemeCommonInfo
Definition at line 51 of file mate-theme-info.h.
MateThemeCursorInfo
typedef struct _MateThemeCursorInfo MateThemeCursorInfo
Definition at line 78 of file mate-theme-info.h.
MateThemeIconInfo
typedef struct _MateThemeCommonInfo MateThemeIconInfo
Definition at line 52 of file mate-theme-info.h.
MateThemeInfo
typedef struct _MateThemeInfo MateThemeInfo
Definition at line 63 of file mate-theme-info.h.
MateThemeMetaInfo
typedef struct _MateThemeMetaInfo MateThemeMetaInfo
Definition at line 91 of file mate-theme-info.h.
ThemeChangedCallback
typedef void(* ThemeChangedCallback) (MateThemeCommonInfo *theme, MateThemeChangeType change_type, MateThemeElement element_type, gpointer user_data)
Definition at line 132 of file mate-theme-info.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COLOR_FG
COLOR_BG
COLOR_TEXT
COLOR_BASE
COLOR_SELECTED_FG
COLOR_SELECTED_BG
COLOR_TOOLTIP_FG
COLOR_TOOLTIP_BG
NUM_SYMBOLIC_COLORS
Definition at line 120 of file mate-theme-info.h.
anonymous enum
anonymous enum
Enumerator
MATE_THEME_ERROR_GTK_THEME_NOT_AVAILABLE
MATE_THEME_ERROR_WM_THEME_NOT_AVAILABLE
MATE_THEME_ERROR_ICON_THEME_NOT_AVAILABLE
MATE_THEME_ERROR_GTK_ENGINE_NOT_AVAILABLE
MATE_THEME_ERROR_UNKNOWN
Definition at line 136 of file mate-theme-info.h.
MateThemeChangeType
enum MateThemeChangeType
Enumerator
MATE_THEME_CHANGE_CREATED
MATE_THEME_CHANGE_DELETED
MATE_THEME_CHANGE_CHANGED
Definition at line 39 of file mate-theme-info.h.
MateThemeElement
enum MateThemeElement
Enumerator
MATE_THEME_MARCO
MATE_THEME_GTK_2
MATE_THEME_GTK_2_KEYBINDING
Definition at line 45 of file mate-theme-info.h.
MateThemeType
enum MateThemeType
Enumerator
MATE_THEME_TYPE_METATHEME
MATE_THEME_TYPE_ICON
MATE_THEME_TYPE_CURSOR
MATE_THEME_TYPE_REGULAR
Definition at line 32 of file mate-theme-info.h.
Function Documentation
gtk_theme_info_missing_engine()
gchar * gtk_theme_info_missing_engine (const gchar * gtk_theme, gboolean nameOnly)
Definition at line 1402 of file mate-theme-info.c.
References engine, gtkrc_find_named(), gtkrc_get_details(), and NULL.
mate_theme_color_scheme_equal()
gboolean mate_theme_color_scheme_equal (const gchar * s1, const gchar * s2)
Definition at line 1776 of file mate-theme-info.c.
References FALSE, mate_theme_color_scheme_parse(), NUM_SYMBOLIC_COLORS, and TRUE.
Referenced by mate_meta_theme_set().
mate_theme_color_scheme_parse()
gboolean mate_theme_color_scheme_parse (const gchar * scheme, GdkRGBA * colors)
Definition at line 1722 of file mate-theme-info.c.
References COLOR_BASE, COLOR_BG, COLOR_FG, COLOR_SELECTED_BG, COLOR_SELECTED_FG, COLOR_TEXT, COLOR_TOOLTIP_BG, COLOR_TOOLTIP_FG, FALSE, NULL, NUM_SYMBOLIC_COLORS, and TRUE.
Referenced by mate_theme_color_scheme_equal().
mate_theme_cursor_info_compare()
gint mate_theme_cursor_info_compare (MateThemeCursorInfo * a, MateThemeCursorInfo * b)
Definition at line 1548 of file mate-theme-info.c.
References b, _MateThemeCursorInfo::name, and _MateThemeCursorInfo::path.
mate_theme_cursor_info_find()
MateThemeCursorInfo * mate_theme_cursor_info_find (const gchar * name)
Definition at line 1527 of file mate-theme-info.c.
References NULL.
Referenced by mate_theme_init(), and theme_delete().
mate_theme_cursor_info_find_all()
GList * mate_theme_cursor_info_find_all (void)
Definition at line 1536 of file mate-theme-info.c.
References NULL.
Referenced by main().
mate_theme_cursor_info_free()
void mate_theme_cursor_info_free (MateThemeCursorInfo * info)
Definition at line 1515 of file mate-theme-info.c.
References _MateThemeCursorInfo::name, NULL, _MateThemeCursorInfo::path, _MateThemeCursorInfo::readable_name, _MateThemeCursorInfo::sizes, _MateThemeCursorInfo::thumbnail, and TRUE.
mate_theme_cursor_info_new()
MateThemeCursorInfo * mate_theme_cursor_info_new (void)
Definition at line 1504 of file mate-theme-info.c.
References MATE_THEME_TYPE_CURSOR, and _MateThemeCursorInfo::type.
mate_theme_icon_info_compare()
gint mate_theme_icon_info_compare (MateThemeIconInfo * a, MateThemeIconInfo * b)
Definition at line 1491 of file mate-theme-info.c.
References b, _MateThemeCommonInfo::name, and _MateThemeCommonInfo::path.
mate_theme_icon_info_find()
MateThemeIconInfo * mate_theme_icon_info_find (const gchar * icon_theme_name)
Definition at line 1470 of file mate-theme-info.c.
References NULL.
Referenced by mate_theme_meta_info_validate(), and theme_delete().
mate_theme_icon_info_find_all()
GList * mate_theme_icon_info_find_all (void)
Definition at line 1479 of file mate-theme-info.c.
References NULL.
Referenced by main().
mate_theme_icon_info_free()
void mate_theme_icon_info_free (MateThemeIconInfo * icon_theme_info)
Definition at line 1461 of file mate-theme-info.c.
References _MateThemeCommonInfo::name, _MateThemeCommonInfo::path, and _MateThemeCommonInfo::readable_name.
mate_theme_icon_info_new()
MateThemeIconInfo * mate_theme_icon_info_new (void)
Definition at line 1450 of file mate-theme-info.c.
References MATE_THEME_TYPE_ICON, and _MateThemeCommonInfo::type.
mate_theme_info_error_quark()
GQuark mate_theme_info_error_quark (void)
Definition at line 277 of file mate-theme-info.c.
mate_theme_info_find()
MateThemeInfo * mate_theme_info_find (const gchar * theme_name)
Definition at line 1344 of file mate-theme-info.c.
Referenced by mate_theme_meta_info_validate(), and theme_delete().
mate_theme_info_find_by_type()
GList * mate_theme_info_find_by_type (guint elements)
Definition at line 1378 of file mate-theme-info.c.
References data, and NULL.
Referenced by main().
mate_theme_info_free()
void mate_theme_info_free (MateThemeInfo * theme_info)
Definition at line 1335 of file mate-theme-info.c.
References _MateThemeInfo::name, _MateThemeInfo::path, and _MateThemeInfo::readable_name.
mate_theme_info_new()
MateThemeInfo * mate_theme_info_new (void)
Definition at line 1324 of file mate-theme-info.c.
References MATE_THEME_TYPE_REGULAR, and _MateThemeInfo::type.
mate_theme_info_register_theme_change()
void mate_theme_info_register_theme_change (ThemeChangedCallback func, gpointer data)
Definition at line 1707 of file mate-theme-info.c.
References data, and NULL.
Referenced by style_init(), and themes_init().
mate_theme_init()
void mate_theme_init (void)
Definition at line 1795 of file mate-theme-info.c.
References FALSE, mate_theme_cursor_info_find(), NULL, and TRUE.
Referenced by main(), and themes_init().
mate_theme_meta_info_compare()
gint mate_theme_meta_info_compare (MateThemeMetaInfo * a, MateThemeMetaInfo * b)
Definition at line 1650 of file mate-theme-info.c.
References _MateThemeMetaInfo::application_font, b, _MateThemeMetaInfo::background_image, _MateThemeMetaInfo::comment, _MateThemeMetaInfo::desktop_font, _MateThemeMetaInfo::documents_font, _MateThemeMetaInfo::gtk_color_scheme, _MateThemeMetaInfo::gtk_theme_name, _MateThemeMetaInfo::icon_file, _MateThemeMetaInfo::icon_theme_name, _MateThemeMetaInfo::marco_theme_name, _MateThemeMetaInfo::monospace_font, _MateThemeMetaInfo::name, _MateThemeMetaInfo::notification_theme_name, _MateThemeMetaInfo::path, _MateThemeMetaInfo::readable_name, _MateThemeMetaInfo::sound_theme_name, and _MateThemeMetaInfo::windowtitle_font.
mate_theme_meta_info_find()
MateThemeMetaInfo * mate_theme_meta_info_find (const gchar * meta_theme_name)
References b, data, and error.
mate_theme_meta_info_find_all()
GList * mate_theme_meta_info_find_all (void)
Definition at line 1638 of file mate-theme-info.c.
References NULL.
Referenced by main(), and themes_init().
mate_theme_meta_info_free()
void mate_theme_meta_info_free (MateThemeMetaInfo * meta_theme_info)
Definition at line 1572 of file mate-theme-info.c.
References _MateThemeMetaInfo::application_font, _MateThemeMetaInfo::background_image, _MateThemeMetaInfo::comment, _MateThemeMetaInfo::cursor_theme_name, _MateThemeMetaInfo::desktop_font, _MateThemeMetaInfo::documents_font, _MateThemeMetaInfo::gtk_color_scheme, _MateThemeMetaInfo::gtk_theme_name, _MateThemeMetaInfo::icon_file, _MateThemeMetaInfo::icon_theme_name, _MateThemeMetaInfo::marco_theme_name, _MateThemeMetaInfo::monospace_font, _MateThemeMetaInfo::name, _MateThemeMetaInfo::notification_theme_name, _MateThemeMetaInfo::path, _MateThemeMetaInfo::readable_name, _MateThemeMetaInfo::sound_theme_name, and _MateThemeMetaInfo::windowtitle_font.
Referenced by mate_theme_read_meta_theme(), and themes_shutdown().
mate_theme_meta_info_new()
MateThemeMetaInfo * mate_theme_meta_info_new (void)
Definition at line 1561 of file mate-theme-info.c.
References MATE_THEME_TYPE_METATHEME, and _MateThemeMetaInfo::type.
Referenced by mate_theme_read_meta_theme().
mate_theme_meta_info_validate()
gboolean mate_theme_meta_info_validate (const MateThemeMetaInfo * info, GError ** error)
Definition at line 1596 of file mate-theme-info.c.
References _, error, FALSE, _MateThemeInfo::has_gtk, _MateThemeInfo::has_marco, MATE_THEME_ERROR, MATE_THEME_ERROR_GTK_THEME_NOT_AVAILABLE, MATE_THEME_ERROR_ICON_THEME_NOT_AVAILABLE, MATE_THEME_ERROR_WM_THEME_NOT_AVAILABLE, mate_theme_icon_info_find(), mate_theme_info_find(), NULL, and TRUE.
mate_theme_read_meta_theme()
MateThemeMetaInfo * mate_theme_read_meta_theme (GFile * meta_theme_uri)
Definition at line 283 of file mate-theme-info.c.
References _MateThemeMetaInfo::application_font, APPLICATION_FONT_KEY, _MateThemeMetaInfo::background_image, BACKGROUND_IMAGE_KEY, _MateThemeMetaInfo::comment, _MateThemeMetaInfo::cursor_size, CURSOR_SIZE_KEY, CURSOR_THEME_KEY, _MateThemeMetaInfo::cursor_theme_name, _MateThemeMetaInfo::desktop_font, DESKTOP_FONT_KEY, _MateThemeMetaInfo::documents_font, DOCUMENTS_FONT_KEY, _MateThemeMetaInfo::gtk_color_scheme, GTK_COLOR_SCHEME_KEY, GTK_THEME_KEY, _MateThemeMetaInfo::gtk_theme_name, gtkrc_get_color_scheme_for_theme(), _MateThemeMetaInfo::hidden, HIDDEN_KEY, _MateThemeMetaInfo::icon_file, ICON_THEME_KEY, _MateThemeMetaInfo::icon_theme_name, int(), MARCO_THEME_KEY, _MateThemeMetaInfo::marco_theme_name, MATE_DESKTOP_ITEM_COMMENT, mate_desktop_item_get_boolean(), mate_desktop_item_get_localestring(), mate_desktop_item_get_string(), MATE_DESKTOP_ITEM_ICON, MATE_DESKTOP_ITEM_NAME, mate_desktop_item_new_from_uri(), mate_desktop_item_unref(), mate_theme_meta_info_free(), mate_theme_meta_info_new(), _MateThemeMetaInfo::monospace_font, MONOSPACE_FONT_KEY, _MateThemeMetaInfo::name, NOTIFICATION_THEME_KEY, _MateThemeMetaInfo::notification_theme_name, NULL, _MateThemeMetaInfo::path, _MateThemeMetaInfo::readable_name, THEME_COMMENT, THEME_NAME, _MateThemeMetaInfo::windowtitle_font, and WINDOWTITLE_FONT_KEY.