MATE Desktop Environment: matemixer.c File Reference
matemixer.c File Reference
#include "config.h"
#include <glib.h>
#include <glib-object.h>
#include <gmodule.h>
#include "matemixer.h"
#include "matemixer-private.h"
#include "matemixer-backend-module.h"
Functions
gboolean mate_mixer_init (void)
gboolean mate_mixer_is_initialized (void)
const GList * _mate_mixer_list_modules (void)
guint32 _mate_mixer_create_channel_mask (MateMixerChannelPosition *positions, guint n)
Function Documentation
_mate_mixer_create_channel_mask()
guint32 _mate_mixer_create_channel_mask (MateMixerChannelPosition * positions, guint n)
_mate_mixer_create_channel_mask: @positions: an array of channel positions
: number of channel positions in the array
Creates a channel mask using the given list of channel positions.
Returns: a channel mask.
Definition at line 131 of file matemixer.c.
References mask, MATE_MIXER_CHANNEL_MAX, and MATE_MIXER_CHANNEL_UNKNOWN.
Referenced by alsa_stream_control_set_data().
_mate_mixer_list_modules()
const GList * _mate_mixer_list_modules (void)
_mate_mixer_list_modules:
Gets a list of loaded backend modules.
Returns: a #GList.
Definition at line 116 of file matemixer.c.
Referenced by mate_mixer_context_open(), and mate_mixer_context_set_backend_type().
mate_mixer_init()
gboolean mate_mixer_init (void)
mate_mixer_init:
Initializes the library. You must call this function before using any other function from the library.
Returns: TRUE on success or FALSE if the library installation does not provide support for any sound system backends.
Definition at line 61 of file matemixer.c.
References FALSE, NULL, and TRUE.
Referenced by main(), and main().
mate_mixer_is_initialized()
gboolean mate_mixer_is_initialized (void)
mate_mixer_is_initialized:
Returns TRUE if the library has been initialized.
Returns: TRUE or FALSE.
Definition at line 103 of file matemixer.c.
Referenced by mate_mixer_context_new(), and msd_media_keys_manager_start().