MATE Desktop Environment: matemixer-stream-control.c File Reference
matemixer-stream-control.c File Reference
#include <glib.h>
#include <glib-object.h>
#include "matemixer-enums.h"
#include "matemixer-enum-types.h"
#include "matemixer-stream.h"
#include "matemixer-stream-control.h"
#include "matemixer-stream-control-private.h"
Enumerations
enum {
PROP_0 , PROP_NAME , PROP_LABEL , PROP_FLAGS ,
PROP_ROLE , PROP_MEDIA_ROLE , PROP_STREAM , PROP_MUTE ,
PROP_VOLUME , PROP_BALANCE , PROP_FADE , N_PROPERTIES
}
enum { MONITOR_VALUE , N_SIGNALS }
Functions
const gchar * mate_mixer_stream_control_get_name (MateMixerStreamControl *control)
const gchar * mate_mixer_stream_control_get_label (MateMixerStreamControl *control)
MateMixerStreamControlFlags mate_mixer_stream_control_get_flags (MateMixerStreamControl *control)
MateMixerStreamControlRole mate_mixer_stream_control_get_role (MateMixerStreamControl *control)
MateMixerStreamControlMediaRole mate_mixer_stream_control_get_media_role (MateMixerStreamControl *control)
MateMixerAppInfo * mate_mixer_stream_control_get_app_info (MateMixerStreamControl *control)
MateMixerStream * mate_mixer_stream_control_get_stream (MateMixerStreamControl *control)
gboolean mate_mixer_stream_control_set_stream (MateMixerStreamControl *control, MateMixerStream *stream)
gboolean mate_mixer_stream_control_get_mute (MateMixerStreamControl *control)
gboolean mate_mixer_stream_control_set_mute (MateMixerStreamControl *control, gboolean mute)
guint mate_mixer_stream_control_get_num_channels (MateMixerStreamControl *control)
guint mate_mixer_stream_control_get_volume (MateMixerStreamControl *control)
gboolean mate_mixer_stream_control_set_volume (MateMixerStreamControl *control, guint volume)
gdouble mate_mixer_stream_control_get_decibel (MateMixerStreamControl *control)
gboolean mate_mixer_stream_control_set_decibel (MateMixerStreamControl *control, gdouble decibel)
gboolean mate_mixer_stream_control_has_channel_position (MateMixerStreamControl *control, MateMixerChannelPosition position)
MateMixerChannelPosition mate_mixer_stream_control_get_channel_position (MateMixerStreamControl *control, guint channel)
guint mate_mixer_stream_control_get_channel_volume (MateMixerStreamControl *control, guint channel)
gboolean mate_mixer_stream_control_set_channel_volume (MateMixerStreamControl *control, guint channel, guint volume)
gdouble mate_mixer_stream_control_get_channel_decibel (MateMixerStreamControl *control, guint channel)
gboolean mate_mixer_stream_control_set_channel_decibel (MateMixerStreamControl *control, guint channel, gdouble decibel)
gfloat mate_mixer_stream_control_get_balance (MateMixerStreamControl *control)
gboolean mate_mixer_stream_control_set_balance (MateMixerStreamControl *control, gfloat balance)
gfloat mate_mixer_stream_control_get_fade (MateMixerStreamControl *control)
gboolean mate_mixer_stream_control_set_fade (MateMixerStreamControl *control, gfloat fade)
gboolean mate_mixer_stream_control_get_monitor_enabled (MateMixerStreamControl *control)
gboolean mate_mixer_stream_control_set_monitor_enabled (MateMixerStreamControl *control, gboolean enabled)
guint mate_mixer_stream_control_get_min_volume (MateMixerStreamControl *control)
guint mate_mixer_stream_control_get_max_volume (MateMixerStreamControl *control)
guint mate_mixer_stream_control_get_normal_volume (MateMixerStreamControl *control)
guint mate_mixer_stream_control_get_base_volume (MateMixerStreamControl *control)
void _mate_mixer_stream_control_set_flags (MateMixerStreamControl *control, MateMixerStreamControlFlags flags)
void _mate_mixer_stream_control_set_stream (MateMixerStreamControl *control, MateMixerStream *stream)
void _mate_mixer_stream_control_set_mute (MateMixerStreamControl *control, gboolean mute)
void _mate_mixer_stream_control_set_balance (MateMixerStreamControl *control, gfloat balance)
void _mate_mixer_stream_control_set_fade (MateMixerStreamControl *control, gfloat fade)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MONITOR_VALUE
N_SIGNALS
Definition at line 62 of file matemixer-stream-control.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_NAME
PROP_LABEL
PROP_FLAGS
PROP_ROLE
PROP_MEDIA_ROLE
PROP_STREAM
PROP_MUTE
PROP_VOLUME
PROP_BALANCE
PROP_FADE
N_PROPERTIES
Definition at line 45 of file matemixer-stream-control.c.
Function Documentation
_mate_mixer_stream_control_set_balance()
void _mate_mixer_stream_control_set_balance (MateMixerStreamControl * control, gfloat balance)
Definition at line 927 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, _MateMixerStreamControl::priv, and PROP_BALANCE.
Referenced by alsa_stream_control_set_data(), and mate_mixer_stream_control_set_balance().
_mate_mixer_stream_control_set_fade()
void _mate_mixer_stream_control_set_fade (MateMixerStreamControl * control, gfloat fade)
Definition at line 940 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, _MateMixerStreamControl::priv, and PROP_FADE.
Referenced by alsa_stream_control_set_data(), and mate_mixer_stream_control_set_fade().
_mate_mixer_stream_control_set_flags()
void _mate_mixer_stream_control_set_flags (MateMixerStreamControl * control, MateMixerStreamControlFlags flags)
Definition at line 876 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, _MateMixerStreamControl::priv, and PROP_FLAGS.
Referenced by alsa_stream_control_set_data(), pulse_ext_stream_update(), pulse_stream_control_set_channel_map(), and pulse_stream_control_set_cvolume().
_mate_mixer_stream_control_set_mute()
void _mate_mixer_stream_control_set_mute (MateMixerStreamControl * control, gboolean mute)
Definition at line 914 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, _MateMixerStreamControl::priv, and PROP_MUTE.
Referenced by alsa_stream_control_set_data(), mate_mixer_stream_control_set_mute(), pulse_ext_stream_update(), pulse_sink_control_update(), pulse_sink_input_update(), pulse_source_control_update(), and pulse_source_output_update().
_mate_mixer_stream_control_set_stream()
void _mate_mixer_stream_control_set_stream (MateMixerStreamControl * control, MateMixerStream * stream)
Definition at line 890 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM, MATE_MIXER_IS_STREAM_CONTROL, NULL, _MateMixerStreamControl::priv, and PROP_STREAM.
Referenced by mate_mixer_stream_control_set_stream(), and pulse_ext_stream_update().
mate_mixer_stream_control_get_app_info()
MateMixerAppInfo * mate_mixer_stream_control_get_app_info (MateMixerStreamControl * control)
mate_mixer_stream_control_get_app_info: @control: a MateMixerStreamControl
Definition at line 380 of file matemixer-stream-control.c.
References _MateMixerStreamControlClass::get_app_info, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_GET_CLASS, MATE_MIXER_STREAM_CONTROL_ROLE_APPLICATION, NULL, and _MateMixerStreamControl::priv.
mate_mixer_stream_control_get_balance()
gfloat mate_mixer_stream_control_get_balance (MateMixerStreamControl * control)
mate_mixer_stream_control_get_balance: @control: a MateMixerStreamControl
Definition at line 707 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_CAN_BALANCE, and _MateMixerStreamControl::priv.
mate_mixer_stream_control_get_base_volume()
guint mate_mixer_stream_control_get_base_volume (MateMixerStreamControl * control)
mate_mixer_stream_control_get_base_volume: @control: a MateMixerStreamControl
Definition at line 866 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, and MATE_MIXER_STREAM_CONTROL_GET_CLASS.
mate_mixer_stream_control_get_channel_decibel()
gdouble mate_mixer_stream_control_get_channel_decibel (MateMixerStreamControl * control, guint channel)
mate_mixer_stream_control_get_channel_decibel: @control: a MateMixerStreamControl @channel: a channel index
Definition at line 663 of file matemixer-stream-control.c.
References _MateMixerStreamControlClass::get_channel_decibel, MATE_MIXER_INFINITY, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_GET_CLASS, MATE_MIXER_STREAM_CONTROL_HAS_DECIBEL, MATE_MIXER_STREAM_CONTROL_VOLUME_READABLE, and _MateMixerStreamControl::priv.
mate_mixer_stream_control_get_channel_position()
MateMixerChannelPosition mate_mixer_stream_control_get_channel_position (MateMixerStreamControl * control, guint channel)
mate_mixer_stream_control_get_channel_position: @control: a MateMixerStreamControl @channel: a channel index
Definition at line 599 of file matemixer-stream-control.c.
References _MateMixerStreamControlClass::get_channel_position, MATE_MIXER_CHANNEL_UNKNOWN, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_GET_CLASS, and NULL.
mate_mixer_stream_control_get_channel_volume()
guint mate_mixer_stream_control_get_channel_volume (MateMixerStreamControl * control, guint channel)
mate_mixer_stream_control_get_channel_volume: @control: a MateMixerStreamControl @channel: a channel index
Definition at line 619 of file matemixer-stream-control.c.
References _MateMixerStreamControlClass::get_channel_volume, _MateMixerStreamControlClass::get_min_volume, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_GET_CLASS, MATE_MIXER_STREAM_CONTROL_VOLUME_READABLE, and _MateMixerStreamControl::priv.
mate_mixer_stream_control_get_decibel()
gdouble mate_mixer_stream_control_get_decibel (MateMixerStreamControl * control)
mate_mixer_stream_control_get_decibel: @control: a MateMixerStreamControl
Definition at line 536 of file matemixer-stream-control.c.
References _MateMixerStreamControlClass::get_decibel, MATE_MIXER_INFINITY, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_GET_CLASS, MATE_MIXER_STREAM_CONTROL_HAS_DECIBEL, MATE_MIXER_STREAM_CONTROL_VOLUME_READABLE, and _MateMixerStreamControl::priv.
mate_mixer_stream_control_get_fade()
gfloat mate_mixer_stream_control_get_fade (MateMixerStreamControl * control)
mate_mixer_stream_control_get_fade: @control: a MateMixerStreamControl
Definition at line 749 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_CAN_FADE, and _MateMixerStreamControl::priv.
mate_mixer_stream_control_get_flags()
MateMixerStreamControlFlags mate_mixer_stream_control_get_flags (MateMixerStreamControl * control)
mate_mixer_stream_control_get_flags: @control: a MateMixerStreamControl
Definition at line 344 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_NO_FLAGS, and _MateMixerStreamControl::priv.
Referenced by gvc_channel_bar_set_control(), pulse_ext_stream_update(), pulse_stream_control_set_channel_map(), and pulse_stream_control_set_cvolume().
mate_mixer_stream_control_get_label()
const gchar * mate_mixer_stream_control_get_label (MateMixerStreamControl * control)
mate_mixer_stream_control_get_label: @control: a MateMixerStreamControl
Definition at line 332 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, NULL, and _MateMixerStreamControl::priv.
mate_mixer_stream_control_get_max_volume()
guint mate_mixer_stream_control_get_max_volume (MateMixerStreamControl * control)
mate_mixer_stream_control_get_max_volume: @control: a MateMixerStreamControl
Definition at line 840 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, and MATE_MIXER_STREAM_CONTROL_GET_CLASS.
mate_mixer_stream_control_get_media_role()
MateMixerStreamControlMediaRole mate_mixer_stream_control_get_media_role (MateMixerStreamControl * control)
mate_mixer_stream_control_get_media_role: @control: a MateMixerStreamControl
Definition at line 368 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_UNKNOWN, and _MateMixerStreamControl::priv.
mate_mixer_stream_control_get_min_volume()
guint mate_mixer_stream_control_get_min_volume (MateMixerStreamControl * control)
mate_mixer_stream_control_get_min_volume: @control: a MateMixerStreamControl
Definition at line 827 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, and MATE_MIXER_STREAM_CONTROL_GET_CLASS.
mate_mixer_stream_control_get_monitor_enabled()
gboolean mate_mixer_stream_control_get_monitor_enabled (MateMixerStreamControl * control)
mate_mixer_stream_control_get_monitor_enabled: @control: a MateMixerStreamControl
Definition at line 791 of file matemixer-stream-control.c.
References FALSE, _MateMixerStreamControlClass::get_monitor_enabled, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_GET_CLASS, MATE_MIXER_STREAM_CONTROL_HAS_MONITOR, and _MateMixerStreamControl::priv.
mate_mixer_stream_control_get_mute()
gboolean mate_mixer_stream_control_get_mute (MateMixerStreamControl * control)
mate_mixer_stream_control_get_mute: @control: a MateMixerStreamControl
Definition at line 439 of file matemixer-stream-control.c.
References FALSE, MATE_MIXER_IS_STREAM_CONTROL, and _MateMixerStreamControl::priv.
Referenced by gvc_stream_applet_icon_get_mute().
mate_mixer_stream_control_get_name()
const gchar * mate_mixer_stream_control_get_name (MateMixerStreamControl * control)
mate_mixer_stream_control_get_name: @control: a MateMixerStreamControl
Definition at line 320 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, NULL, and _MateMixerStreamControl::priv.
Referenced by _mate_mixer_stream_set_default_control(), alsa_stream_add_control(), alsa_stream_remove_all(), alsa_stream_remove_elements(), mate_mixer_backend_get_stored_control(), oss_stream_add_control(), oss_stream_remove_all(), pulse_sink_add_input(), pulse_sink_remove_input(), pulse_source_add_output(), and pulse_source_remove_output().
mate_mixer_stream_control_get_normal_volume()
guint mate_mixer_stream_control_get_normal_volume (MateMixerStreamControl * control)
mate_mixer_stream_control_get_normal_volume: @control: a MateMixerStreamControl
Definition at line 853 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, and MATE_MIXER_STREAM_CONTROL_GET_CLASS.
mate_mixer_stream_control_get_num_channels()
guint mate_mixer_stream_control_get_num_channels (MateMixerStreamControl * control)
mate_mixer_stream_control_get_num_channels: @control: a MateMixerStreamControl
Definition at line 477 of file matemixer-stream-control.c.
References _MateMixerStreamControlClass::get_num_channels, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_GET_CLASS, and NULL.
Referenced by gvc_channel_map_to_pretty_string().
mate_mixer_stream_control_get_role()
MateMixerStreamControlRole mate_mixer_stream_control_get_role (MateMixerStreamControl * control)
mate_mixer_stream_control_get_role: @control: a MateMixerStreamControl
Definition at line 356 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_ROLE_UNKNOWN, and _MateMixerStreamControl::priv.
mate_mixer_stream_control_get_stream()
MateMixerStream * mate_mixer_stream_control_get_stream (MateMixerStreamControl * control)
mate_mixer_stream_control_get_stream: @control: a MateMixerStreamControl
Definition at line 399 of file matemixer-stream-control.c.
References MATE_MIXER_IS_STREAM_CONTROL, NULL, and _MateMixerStreamControl::priv.
Referenced by pulse_stream_control_get_stream_index().
mate_mixer_stream_control_get_volume()
guint mate_mixer_stream_control_get_volume (MateMixerStreamControl * control)
mate_mixer_stream_control_get_volume: @control: a MateMixerStreamControl
Definition at line 496 of file matemixer-stream-control.c.
References _MateMixerStreamControlClass::get_min_volume, _MateMixerStreamControlClass::get_volume, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_GET_CLASS, MATE_MIXER_STREAM_CONTROL_VOLUME_READABLE, and _MateMixerStreamControl::priv.
mate_mixer_stream_control_has_channel_position()
gboolean mate_mixer_stream_control_has_channel_position (MateMixerStreamControl * control, MateMixerChannelPosition position)
mate_mixer_stream_control_has_channel_position: @control: a MateMixerStreamControl @position: to channel position to check
Definition at line 578 of file matemixer-stream-control.c.
References FALSE, _MateMixerStreamControlClass::has_channel_position, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_GET_CLASS, and NULL.
mate_mixer_stream_control_set_balance()
gboolean mate_mixer_stream_control_set_balance (MateMixerStreamControl * control, gfloat balance)
mate_mixer_stream_control_set_balance: @control: a MateMixerStreamControl @balance: the balance value
Definition at line 723 of file matemixer-stream-control.c.
References _mate_mixer_stream_control_set_balance(), FALSE, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_CAN_BALANCE, MATE_MIXER_STREAM_CONTROL_GET_CLASS, _MateMixerStreamControl::priv, _MateMixerStreamControlClass::set_balance, and TRUE.
mate_mixer_stream_control_set_channel_decibel()
gboolean mate_mixer_stream_control_set_channel_decibel (MateMixerStreamControl * control, guint channel, gdouble decibel)
mate_mixer_stream_control_set_channel_decibel: @control: a MateMixerStreamControl @channel: a channel index @decibel: the volume to set in decibels
Definition at line 685 of file matemixer-stream-control.c.
References FALSE, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_GET_CLASS, MATE_MIXER_STREAM_CONTROL_HAS_DECIBEL, MATE_MIXER_STREAM_CONTROL_VOLUME_WRITABLE, _MateMixerStreamControl::priv, and _MateMixerStreamControlClass::set_channel_decibel.
mate_mixer_stream_control_set_channel_volume()
gboolean mate_mixer_stream_control_set_channel_volume (MateMixerStreamControl * control, guint channel, guint volume)
mate_mixer_stream_control_set_channel_volume: @control: a MateMixerStreamControl @channel: a channel index @volume: the volume to set
Definition at line 641 of file matemixer-stream-control.c.
References FALSE, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_GET_CLASS, MATE_MIXER_STREAM_CONTROL_VOLUME_WRITABLE, _MateMixerStreamControl::priv, and _MateMixerStreamControlClass::set_channel_volume.
mate_mixer_stream_control_set_decibel()
gboolean mate_mixer_stream_control_set_decibel (MateMixerStreamControl * control, gdouble decibel)
mate_mixer_stream_control_set_decibel: @control: a MateMixerStreamControl @decibel: the volume to set in decibels
Definition at line 557 of file matemixer-stream-control.c.
References FALSE, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_GET_CLASS, MATE_MIXER_STREAM_CONTROL_HAS_DECIBEL, MATE_MIXER_STREAM_CONTROL_VOLUME_WRITABLE, _MateMixerStreamControl::priv, and _MateMixerStreamControlClass::set_decibel.
mate_mixer_stream_control_set_fade()
gboolean mate_mixer_stream_control_set_fade (MateMixerStreamControl * control, gfloat fade)
mate_mixer_stream_control_set_fade: @control: a MateMixerStreamControl @fade: the fade value
Definition at line 765 of file matemixer-stream-control.c.
References _mate_mixer_stream_control_set_fade(), FALSE, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_CAN_FADE, MATE_MIXER_STREAM_CONTROL_GET_CLASS, _MateMixerStreamControl::priv, _MateMixerStreamControlClass::set_fade, and TRUE.
mate_mixer_stream_control_set_monitor_enabled()
gboolean mate_mixer_stream_control_set_monitor_enabled (MateMixerStreamControl * control, gboolean enabled)
mate_mixer_stream_control_set_monitor_enabled: @control: a MateMixerStreamControl @enabled: a boolean value
Definition at line 811 of file matemixer-stream-control.c.
References FALSE, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_GET_CLASS, MATE_MIXER_STREAM_CONTROL_HAS_MONITOR, and _MateMixerStreamControl::priv.
mate_mixer_stream_control_set_mute()
gboolean mate_mixer_stream_control_set_mute (MateMixerStreamControl * control, gboolean mute)
mate_mixer_stream_control_set_mute: @control: a MateMixerStreamControl @mute: the mute toggle state to set
Definition at line 452 of file matemixer-stream-control.c.
References _mate_mixer_stream_control_set_mute(), FALSE, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_GET_CLASS, MATE_MIXER_STREAM_CONTROL_MUTE_WRITABLE, _MateMixerStreamControl::priv, _MateMixerStreamControlClass::set_mute, and TRUE.
Referenced by gvc_stream_applet_icon_set_mute().
mate_mixer_stream_control_set_stream()
gboolean mate_mixer_stream_control_set_stream (MateMixerStreamControl * control, MateMixerStream * stream)
mate_mixer_stream_control_set_stream: @control: a MateMixerStreamControl @stream: a MateMixerStream
Definition at line 412 of file matemixer-stream-control.c.
References _mate_mixer_stream_control_set_stream(), FALSE, MATE_MIXER_IS_STREAM, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_GET_CLASS, MATE_MIXER_STREAM_CONTROL_MOVABLE, NULL, _MateMixerStreamControl::priv, _MateMixerStreamControlClass::set_stream, and TRUE.
mate_mixer_stream_control_set_volume()
gboolean mate_mixer_stream_control_set_volume (MateMixerStreamControl * control, guint volume)
mate_mixer_stream_control_set_volume: @control: a MateMixerStreamControl @volume: the volume to set
Definition at line 517 of file matemixer-stream-control.c.
References FALSE, MATE_MIXER_IS_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_GET_CLASS, MATE_MIXER_STREAM_CONTROL_VOLUME_WRITABLE, _MateMixerStreamControl::priv, and _MateMixerStreamControlClass::set_volume.