MATE Desktop Environment: matekbd-keyboard-drawing.c File Reference
matekbd-keyboard-drawing.c File Reference
#include <config.h>
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
#include <gdk/gdkkeysyms.h>
#include <X11/XKBlib.h>
#include <X11/extensions/XKBgeom.h>
#include <stdlib.h>
#include <memory.h>
#include <math.h>
#include <glib/gi18n-lib.h>
#include <libxklavier/xklavier.h>
#include <matekbd-keyboard-drawing.h>
#include <matekbd-keyboard-drawing-marshal.h>
#include <matekbd-util.h>
Macros
#define INVALID_KEYCODE ((guint)(-1))
#define GTK_RESPONSE_PRINT 2
#define KEY_FONT_SIZE 12
#define KEYSYM_NAME_MAX_LENGTH 4
#define modifier_change_mask (XkbModifierStateMask | XkbModifierBaseMask | XkbModifierLatchMask | XkbModifierLockMask)
Enumerations
enum { BAD_KEYCODE = 0 , NUM_SIGNALS }
Functions
gboolean xkl_xkb_config_native_prepare (XklEngine *engine, const XklConfigRec *data, gpointer component_names)
void xkl_xkb_config_native_cleanup (XklEngine *engine, gpointer component_names)
GtkWidget * matekbd_keyboard_drawing_new (void)
GType matekbd_keyboard_drawing_get_type (void)
gboolean matekbd_keyboard_drawing_render (MatekbdKeyboardDrawing *kbdrawing, cairo_t *cr, PangoLayout *layout, double x, double y, double width, double height, double dpi_x, double dpi_y)
gboolean matekbd_keyboard_drawing_set_keyboard (MatekbdKeyboardDrawing *drawing, XkbComponentNamesRec *names)
const gchar * matekbd_keyboard_drawing_get_keycodes (MatekbdKeyboardDrawing *drawing)
const gchar * matekbd_keyboard_drawing_get_geometry (MatekbdKeyboardDrawing *drawing)
const gchar * matekbd_keyboard_drawing_get_symbols (MatekbdKeyboardDrawing *drawing)
const gchar * matekbd_keyboard_drawing_get_types (MatekbdKeyboardDrawing *drawing)
const gchar * matekbd_keyboard_drawing_get_compat (MatekbdKeyboardDrawing *drawing)
void matekbd_keyboard_drawing_set_track_modifiers (MatekbdKeyboardDrawing *drawing, gboolean enable)
void matekbd_keyboard_drawing_set_track_config (MatekbdKeyboardDrawing *drawing, gboolean enable)
void matekbd_keyboard_drawing_set_groups_levels (MatekbdKeyboardDrawing *drawing, MatekbdKeyboardDrawingGroupLevel *groupLevels[])
void matekbd_keyboard_drawing_print (MatekbdKeyboardDrawing *drawing, GtkWindow *parent_window, const gchar *description)
GtkWidget * matekbd_keyboard_drawing_new_dialog (gint group, gchar *group_name)
Macro Definition Documentation
GTK_RESPONSE_PRINT
#define GTK_RESPONSE_PRINT 2
Definition at line 38 of file matekbd-keyboard-drawing.c.
INVALID_KEYCODE
#define INVALID_KEYCODE ((guint)(-1))
Definition at line 36 of file matekbd-keyboard-drawing.c.
KEY_FONT_SIZE
#define KEY_FONT_SIZE 12
Definition at line 40 of file matekbd-keyboard-drawing.c.
KEYSYM_NAME_MAX_LENGTH
#define KEYSYM_NAME_MAX_LENGTH 4
modifier_change_mask
#define modifier_change_mask (XkbModifierStateMask | XkbModifierBaseMask | XkbModifierLatchMask | XkbModifierLockMask)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BAD_KEYCODE
NUM_SIGNALS
Definition at line 42 of file matekbd-keyboard-drawing.c.
Function Documentation
matekbd_keyboard_drawing_get_compat()
const gchar * matekbd_keyboard_drawing_get_compat (MatekbdKeyboardDrawing * drawing)
Definition at line 2588 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::display, NULL, and _MatekbdKeyboardDrawing::xkb.
matekbd_keyboard_drawing_get_geometry()
const gchar * matekbd_keyboard_drawing_get_geometry (MatekbdKeyboardDrawing * drawing)
Definition at line 2552 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::display, NULL, and _MatekbdKeyboardDrawing::xkb.
Referenced by main().
matekbd_keyboard_drawing_get_keycodes()
const gchar * matekbd_keyboard_drawing_get_keycodes (MatekbdKeyboardDrawing * drawing)
Definition at line 2540 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::display, NULL, and _MatekbdKeyboardDrawing::xkb.
Referenced by main().
matekbd_keyboard_drawing_get_symbols()
const gchar * matekbd_keyboard_drawing_get_symbols (MatekbdKeyboardDrawing * drawing)
Definition at line 2564 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::display, NULL, and _MatekbdKeyboardDrawing::xkb.
Referenced by main().
matekbd_keyboard_drawing_get_type()
GType matekbd_keyboard_drawing_get_type (void)
Definition at line 2377 of file matekbd-keyboard-drawing.c.
References NULL.
Referenced by matekbd_keyboard_drawing_new().
matekbd_keyboard_drawing_get_types()
const gchar * matekbd_keyboard_drawing_get_types (MatekbdKeyboardDrawing * drawing)
Definition at line 2576 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::display, NULL, and _MatekbdKeyboardDrawing::xkb.
matekbd_keyboard_drawing_new()
GtkWidget * matekbd_keyboard_drawing_new (void)
Definition at line 2352 of file matekbd-keyboard-drawing.c.
References matekbd_keyboard_drawing_get_type(), and NULL.
Referenced by main(), matekbd_keyboard_drawing_new_dialog(), and xkb_layout_preview_create_widget().
matekbd_keyboard_drawing_new_dialog()
GtkWidget * matekbd_keyboard_drawing_new_dialog (gint group, gchar * group_name)
Definition at line 2776 of file matekbd-keyboard-drawing.c.
References _, engine, error, MATEKBD_KEYBOARD_DRAWING, matekbd_keyboard_drawing_new(), matekbd_keyboard_drawing_set_groups_levels(), matekbd_keyboard_drawing_set_keyboard(), matekbd_preview_load_position(), NULL, TRUE, xkl_xkb_config_native_cleanup(), and xkl_xkb_config_native_prepare().
matekbd_keyboard_drawing_print()
void matekbd_keyboard_drawing_print (MatekbdKeyboardDrawing * drawing, GtkWindow * parent_window, const gchar * description)
Definition at line 2710 of file matekbd-keyboard-drawing.c.
References data, and NULL.
matekbd_keyboard_drawing_render()
gboolean matekbd_keyboard_drawing_render (MatekbdKeyboardDrawing * kbdrawing, cairo_t * cr, PangoLayout * layout, double x, double y, double width, double height, double dpi_x, double dpi_y)
matekbd_keyboard_drawing_render: @kbdrawing: keyboard layout to render @cr: Cairo context to render to @layout: Pango layout to use to render text @x: left coordinate (pixels) of region to render in @y: top coordinate (pixels) of region to render in @width: width (pixels) of region to render in @height: height (pixels) of region to render in
Renders a keyboard layout to a cairo_t context. @cr and @layout can be got from e.g. a GtkWidget or a GtkPrintContext. @cr and @layout may be modified by the function but will not be unreffed.
Returns: TRUE on success, FALSE on failure
Definition at line 2434 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawingRenderContext::angle, FALSE, NULL, _MatekbdKeyboardDrawing::renderContext, and TRUE.
matekbd_keyboard_drawing_set_groups_levels()
void matekbd_keyboard_drawing_set_groups_levels (MatekbdKeyboardDrawing * drawing, MatekbdKeyboardDrawingGroupLevel * groupLevels[])
Definition at line 2626 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::groupLevels, level, MATEKBD_KEYBOARD_DRAWING_POS_BOTTOMLEFT, MATEKBD_KEYBOARD_DRAWING_POS_BOTTOMRIGHT, MATEKBD_KEYBOARD_DRAWING_POS_TOPLEFT, and MATEKBD_KEYBOARD_DRAWING_POS_TOPRIGHT.
Referenced by main(), matekbd_keyboard_drawing_new_dialog(), and xkb_layout_preview_create_widget().
matekbd_keyboard_drawing_set_keyboard()
gboolean matekbd_keyboard_drawing_set_keyboard (MatekbdKeyboardDrawing * drawing, XkbComponentNamesRec * names)
matekbd_keyboard_drawing_set_keyboard: (skip)
Definition at line 2488 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::display, FALSE, NULL, TRUE, _MatekbdKeyboardDrawing::xkb, and _MatekbdKeyboardDrawing::xkbOnDisplay.
Referenced by main(), matekbd_keyboard_drawing_new_dialog(), and xkb_layout_preview_set_drawing_layout().
matekbd_keyboard_drawing_set_track_config()
void matekbd_keyboard_drawing_set_track_config (MatekbdKeyboardDrawing * drawing, gboolean enable)
Definition at line 2616 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::track_config.
Referenced by main().
matekbd_keyboard_drawing_set_track_modifiers()
void matekbd_keyboard_drawing_set_track_modifiers (MatekbdKeyboardDrawing * drawing, gboolean enable)
Definition at line 2601 of file matekbd-keyboard-drawing.c.
References _MatekbdKeyboardDrawing::display, and _MatekbdKeyboardDrawing::track_modifiers.
Referenced by main().
xkl_xkb_config_native_cleanup()
void xkl_xkb_config_native_cleanup (XklEngine * engine, gpointer component_names) extern
References engine.
Referenced by matekbd_keyboard_drawing_new_dialog(), and xkb_layout_preview_set_drawing_layout().
xkl_xkb_config_native_prepare()
gboolean xkl_xkb_config_native_prepare (XklEngine * engine, const XklConfigRec * data, gpointer component_names) extern
References data, and engine.
Referenced by matekbd_keyboard_drawing_new_dialog(), and xkb_layout_preview_set_drawing_layout().