MATE Desktop Environment: mate-rr.h File Reference
mate-rr.h File Reference
#include <glib.h>
#include <gdk/gdk.h>
Classes
struct MateRRScreen
struct MateRRScreenClass
Macros
#define MATE_RR_ERROR (mate_rr_error_quark ())
#define MATE_RR_CONNECTOR_TYPE_PANEL "Panel" /* This is a laptop's built-in LCD */
#define MATE_TYPE_RR_SCREEN (mate_rr_screen_get_type())
#define MATE_RR_SCREEN(obj)
#define MATE_IS_RR_SCREEN(obj)
#define MATE_RR_SCREEN_CLASS(klass)
#define MATE_IS_RR_SCREEN_CLASS(klass)
#define MATE_RR_SCREEN_GET_CLASS(obj)
#define MATE_TYPE_RR_OUTPUT (mate_rr_output_get_type())
#define MATE_TYPE_RR_CRTC (mate_rr_crtc_get_type())
#define MATE_TYPE_RR_MODE (mate_rr_mode_get_type())
Typedefs
typedef struct MateRRScreenPrivate MateRRScreenPrivate
typedef struct MateRROutput MateRROutput
typedef struct MateRRCrtc MateRRCrtc
typedef struct MateRRMode MateRRMode
Enumerations
enum MateRRRotation {
MATE_RR_ROTATION_0 = (1 << 0) , MATE_RR_ROTATION_90 = (1 << 1) , MATE_RR_ROTATION_180 = (1 << 2) , MATE_RR_ROTATION_270 = (1 << 3) ,
MATE_RR_REFLECT_X = (1 << 4) , MATE_RR_REFLECT_Y = (1 << 5)
}
enum MateRRError {
MATE_RR_ERROR_UNKNOWN , MATE_RR_ERROR_NO_RANDR_EXTENSION , MATE_RR_ERROR_RANDR_ERROR , MATE_RR_ERROR_BOUNDS_ERROR ,
MATE_RR_ERROR_CRTC_ASSIGNMENT , MATE_RR_ERROR_NO_MATCHING_CONFIG
}
Functions
GQuark mate_rr_error_quark (void)
GType mate_rr_screen_get_type (void)
GType mate_rr_output_get_type (void)
GType mate_rr_crtc_get_type (void)
GType mate_rr_mode_get_type (void)
MateRRScreen * mate_rr_screen_new (GdkScreen *screen, GError **error)
MateRROutput ** mate_rr_screen_list_outputs (MateRRScreen *screen)
MateRRCrtc ** mate_rr_screen_list_crtcs (MateRRScreen *screen)
MateRRMode ** mate_rr_screen_list_modes (MateRRScreen *screen)
MateRRMode ** mate_rr_screen_list_clone_modes (MateRRScreen *screen)
void mate_rr_screen_set_size (MateRRScreen *screen, int width, int height, int mm_width, int mm_height)
MateRRCrtc * mate_rr_screen_get_crtc_by_id (MateRRScreen *screen, guint32 id)
gboolean mate_rr_screen_refresh (MateRRScreen *screen, GError **error)
MateRROutput * mate_rr_screen_get_output_by_id (MateRRScreen *screen, guint32 id)
MateRROutput * mate_rr_screen_get_output_by_name (MateRRScreen *screen, const char *name)
void mate_rr_screen_get_ranges (MateRRScreen *screen, int *min_width, int *max_width, int *min_height, int *max_height)
void mate_rr_screen_get_timestamps (MateRRScreen *screen, guint32 *change_timestamp_ret, guint32 *config_timestamp_ret)
void mate_rr_screen_set_primary_output (MateRRScreen *screen, MateRROutput *output)
guint32 mate_rr_output_get_id (MateRROutput *output)
const char * mate_rr_output_get_name (MateRROutput *output)
gboolean mate_rr_output_is_connected (MateRROutput *output)
int mate_rr_output_get_size_inches (MateRROutput *output)
int mate_rr_output_get_width_mm (MateRROutput *outout)
int mate_rr_output_get_height_mm (MateRROutput *output)
const guint8 * mate_rr_output_get_edid_data (MateRROutput *output)
MateRRCrtc ** mate_rr_output_get_possible_crtcs (MateRROutput *output)
MateRRMode * mate_rr_output_get_current_mode (MateRROutput *output)
MateRRCrtc * mate_rr_output_get_crtc (MateRROutput *output)
const char * mate_rr_output_get_connector_type (MateRROutput *output)
gboolean mate_rr_output_is_laptop (MateRROutput *output)
void mate_rr_output_get_position (MateRROutput *output, int *x, int *y)
gboolean mate_rr_output_can_clone (MateRROutput *output, MateRROutput *clone)
MateRRMode ** mate_rr_output_list_modes (MateRROutput *output)
MateRRMode * mate_rr_output_get_preferred_mode (MateRROutput *output)
gboolean mate_rr_output_supports_mode (MateRROutput *output, MateRRMode *mode)
gboolean mate_rr_output_get_is_primary (MateRROutput *output)
guint32 mate_rr_mode_get_id (MateRRMode *mode)
guint mate_rr_mode_get_width (MateRRMode *mode)
guint mate_rr_mode_get_height (MateRRMode *mode)
int mate_rr_mode_get_freq (MateRRMode *mode)
guint32 mate_rr_crtc_get_id (MateRRCrtc *crtc)
gboolean mate_rr_crtc_set_config (MateRRCrtc *crtc, int x, int y, MateRRMode *mode, MateRRRotation rotation, MateRROutput **outputs, int n_outputs, GError **error)
gboolean mate_rr_crtc_set_config_with_time (MateRRCrtc *crtc, guint32 timestamp, int x, int y, MateRRMode *mode, MateRRRotation rotation, MateRROutput **outputs, int n_outputs, GError **error)
gboolean mate_rr_crtc_can_drive_output (MateRRCrtc *crtc, MateRROutput *output)
MateRRMode * mate_rr_crtc_get_current_mode (MateRRCrtc *crtc)
void mate_rr_crtc_get_position (MateRRCrtc *crtc, int *x, int *y)
MateRRRotation mate_rr_crtc_get_current_rotation (MateRRCrtc *crtc)
MateRRRotation mate_rr_crtc_get_rotations (MateRRCrtc *crtc)
gboolean mate_rr_crtc_supports_rotation (MateRRCrtc *crtc, MateRRRotation rotation)
gboolean mate_rr_crtc_get_gamma (MateRRCrtc *crtc, int *size, unsigned short **red, unsigned short **green, unsigned short **blue)
void mate_rr_crtc_set_gamma (MateRRCrtc *crtc, int size, unsigned short *red, unsigned short *green, unsigned short *blue)
Macro Definition Documentation
MATE_IS_RR_SCREEN
#define MATE_IS_RR_SCREEN (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_RR_SCREEN))
Definition at line 80 of file mate-rr.h.
Referenced by mate_rr_config_applicable(), mate_rr_config_apply_from_filename_with_time(), mate_rr_config_apply_with_time(), mate_rr_screen_get_crtc_by_id(), mate_rr_screen_get_output_by_id(), mate_rr_screen_get_output_by_name(), mate_rr_screen_get_ranges(), mate_rr_screen_get_timestamps(), mate_rr_screen_list_clone_modes(), mate_rr_screen_list_crtcs(), mate_rr_screen_list_modes(), mate_rr_screen_list_outputs(), mate_rr_screen_set_primary_output(), and mate_rr_screen_set_size().
MATE_IS_RR_SCREEN_CLASS
#define MATE_IS_RR_SCREEN_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_RR_SCREEN))
Definition at line 82 of file mate-rr.h.
MATE_RR_CONNECTOR_TYPE_PANEL
#define MATE_RR_CONNECTOR_TYPE_PANEL "Panel" /* This is a laptop's built-in LCD */
Definition at line 76 of file mate-rr.h.
Referenced by mate_rr_output_is_laptop().
MATE_RR_ERROR
#define MATE_RR_ERROR (mate_rr_error_quark ())
Definition at line 63 of file mate-rr.h.
Referenced by mate_rr_config_load_filename(), and mate_rr_crtc_set_config_with_time().
MATE_RR_SCREEN
#define MATE_RR_SCREEN (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_RR_SCREEN, MateRRScreen))
Definition at line 79 of file mate-rr.h.
MATE_RR_SCREEN_CLASS
#define MATE_RR_SCREEN_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_RR_SCREEN, MateRRScreenClass))
Definition at line 81 of file mate-rr.h.
MATE_RR_SCREEN_GET_CLASS
#define MATE_RR_SCREEN_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_RR_SCREEN, MateRRScreenClass))
Definition at line 83 of file mate-rr.h.
MATE_TYPE_RR_CRTC
#define MATE_TYPE_RR_CRTC (mate_rr_crtc_get_type())
Definition at line 86 of file mate-rr.h.
MATE_TYPE_RR_MODE
#define MATE_TYPE_RR_MODE (mate_rr_mode_get_type())
Definition at line 87 of file mate-rr.h.
MATE_TYPE_RR_OUTPUT
#define MATE_TYPE_RR_OUTPUT (mate_rr_output_get_type())
Definition at line 85 of file mate-rr.h.
MATE_TYPE_RR_SCREEN
#define MATE_TYPE_RR_SCREEN (mate_rr_screen_get_type())
Definition at line 78 of file mate-rr.h.
Referenced by mate_rr_screen_new().
Typedef Documentation
MateRRCrtc
typedef struct MateRRCrtc MateRRCrtc
Definition at line 36 of file mate-rr.h.
MateRRMode
typedef struct MateRRMode MateRRMode
Definition at line 37 of file mate-rr.h.
MateRROutput
typedef struct MateRROutput MateRROutput
Definition at line 35 of file mate-rr.h.
MateRRScreenPrivate
typedef struct MateRRScreenPrivate MateRRScreenPrivate
Definition at line 34 of file mate-rr.h.
Enumeration Type Documentation
MateRRError
enum MateRRError
Enumerator
MATE_RR_ERROR_UNKNOWN
MATE_RR_ERROR_NO_RANDR_EXTENSION
MATE_RR_ERROR_RANDR_ERROR
MATE_RR_ERROR_BOUNDS_ERROR
MATE_RR_ERROR_CRTC_ASSIGNMENT
MATE_RR_ERROR_NO_MATCHING_CONFIG
Definition at line 67 of file mate-rr.h.
MateRRRotation
enum MateRRRotation
Enumerator
MATE_RR_ROTATION_0
MATE_RR_ROTATION_90
MATE_RR_ROTATION_180
MATE_RR_ROTATION_270
MATE_RR_REFLECT_X
MATE_RR_REFLECT_Y
Definition at line 51 of file mate-rr.h.
Function Documentation
mate_rr_crtc_can_drive_output()
gboolean mate_rr_crtc_can_drive_output (MateRRCrtc * crtc, MateRROutput * output)
Definition at line 1819 of file mate-rr.c.
References FALSE, NULL, and TRUE.
mate_rr_crtc_get_current_mode()
MateRRMode * mate_rr_crtc_get_current_mode (MateRRCrtc * crtc)
mate_rr_crtc_get_current_mode: @crtc: a MateRRCrtc Returns: (transfer none): the current mode of this crtc
Definition at line 1803 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current(), and mate_rr_output_get_current_mode().
mate_rr_crtc_get_current_rotation()
MateRRRotation mate_rr_crtc_get_current_rotation (MateRRCrtc * crtc)
Definition at line 1860 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current().
mate_rr_crtc_get_gamma()
gboolean mate_rr_crtc_get_gamma (MateRRCrtc * crtc, int * size, unsigned short ** red, unsigned short ** green, unsigned short ** blue)
mate_rr_crtc_get_gamma: @crtc: a MateRRCrtc @size: @red: (out): the minimum width @green: (out): the maximum width @blue: (out): the minimum height
Returns: TRUE for success
Definition at line 2121 of file mate-rr.c.
References b, DISPLAY, FALSE, memcpy, NULL, and TRUE.
mate_rr_crtc_get_id()
guint32 mate_rr_crtc_get_id (MateRRCrtc * crtc)
Definition at line 1811 of file mate-rr.c.
References NULL.
mate_rr_crtc_get_position()
void mate_rr_crtc_get_position (MateRRCrtc * crtc, int * x, int * y)
mate_rr_crtc_get_position: @crtc: a MateRRCrtc @x: (out) (allow-none): @y: (out) (allow-none):
Definition at line 1845 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current(), and mate_rr_output_get_position().
mate_rr_crtc_get_rotations()
MateRRRotation mate_rr_crtc_get_rotations (MateRRCrtc * crtc)
Definition at line 1867 of file mate-rr.c.
References NULL.
mate_rr_crtc_get_type()
GType mate_rr_crtc_get_type (void)
mate_rr_crtc_set_config()
gboolean mate_rr_crtc_set_config (MateRRCrtc * crtc, int x, int y, MateRRMode * mode, MateRRRotation rotation, MateRROutput ** outputs, int n_outputs, GError ** error)
Definition at line 1702 of file mate-rr.c.
References error, and mate_rr_crtc_set_config_with_time().
mate_rr_crtc_set_config_with_time()
gboolean mate_rr_crtc_set_config_with_time (MateRRCrtc * crtc, guint32 timestamp, int x, int y, MateRRMode * mode, MateRRRotation rotation, MateRROutput ** outputs, int n_outputs, GError ** error)
Definition at line 1716 of file mate-rr.c.
References _, DISPLAY, error, FALSE, MATE_RR_ERROR, MATE_RR_ERROR_BOUNDS_ERROR, MATE_RR_ERROR_RANDR_ERROR, NULL, and TRUE.
Referenced by mate_rr_crtc_set_config().
mate_rr_crtc_set_gamma()
void mate_rr_crtc_set_gamma (MateRRCrtc * crtc, int size, unsigned short * red, unsigned short * green, unsigned short * blue)
Definition at line 2081 of file mate-rr.c.
References DISPLAY, memcpy, and NULL.
mate_rr_crtc_supports_rotation()
gboolean mate_rr_crtc_supports_rotation (MateRRCrtc * crtc, MateRRRotation rotation)
Definition at line 1874 of file mate-rr.c.
References FALSE, and NULL.
mate_rr_error_quark()
GQuark mate_rr_error_quark (void)
mate_rr_mode_get_freq()
int mate_rr_mode_get_freq (MateRRMode * mode)
Definition at line 2031 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current().
mate_rr_mode_get_height()
guint mate_rr_mode_get_height (MateRRMode * mode)
Definition at line 2038 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current().
mate_rr_mode_get_id()
guint32 mate_rr_mode_get_id (MateRRMode * mode)
Definition at line 2017 of file mate-rr.c.
References NULL.
mate_rr_mode_get_type()
GType mate_rr_mode_get_type (void)
References error, and name.
mate_rr_mode_get_width()
guint mate_rr_mode_get_width (MateRRMode * mode)
Definition at line 2024 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current().
mate_rr_output_can_clone()
gboolean mate_rr_output_can_clone (MateRROutput * output, MateRROutput * clone)
Definition at line 1604 of file mate-rr.c.
References FALSE, NULL, and TRUE.
mate_rr_output_get_connector_type()
const char * mate_rr_output_get_connector_type (MateRROutput * output)
Definition at line 1454 of file mate-rr.c.
References NULL.
mate_rr_output_get_crtc()
MateRRCrtc * mate_rr_output_get_crtc (MateRROutput * output)
mate_rr_output_get_crtc: @output: a MateRROutput Returns: (transfer none):
Definition at line 1432 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current(), mate_rr_output_get_current_mode(), and mate_rr_output_get_position().
mate_rr_output_get_current_mode()
MateRRMode * mate_rr_output_get_current_mode (MateRROutput * output)
mate_rr_output_get_current_mode: @output: a MateRROutput Returns: (transfer none): the current mode of this output
Definition at line 1498 of file mate-rr.c.
References mate_rr_crtc_get_current_mode(), mate_rr_output_get_crtc(), and NULL.
mate_rr_output_get_edid_data()
const guint8 * mate_rr_output_get_edid_data (MateRROutput * output)
Definition at line 1394 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current().
mate_rr_output_get_height_mm()
int mate_rr_output_get_height_mm (MateRROutput * output)
Definition at line 1544 of file mate-rr.c.
References NULL.
mate_rr_output_get_id()
guint32 mate_rr_output_get_id (MateRROutput * output)
Definition at line 1386 of file mate-rr.c.
References NULL.
mate_rr_output_get_is_primary()
gboolean mate_rr_output_get_is_primary (MateRROutput * output)
Definition at line 1622 of file mate-rr.c.
References FALSE.
Referenced by mate_rr_config_load_current().
mate_rr_output_get_name()
const char * mate_rr_output_get_name (MateRROutput * output)
Definition at line 1530 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current().
mate_rr_output_get_position()
void mate_rr_output_get_position (MateRROutput * output, int * x, int * y)
mate_rr_output_get_position: @output: a MateRROutput @x: (out) (allow-none): @y: (out) (allow-none):
Definition at line 1517 of file mate-rr.c.
References mate_rr_crtc_get_position(), mate_rr_output_get_crtc(), and NULL.
mate_rr_output_get_possible_crtcs()
MateRRCrtc ** mate_rr_output_get_possible_crtcs (MateRROutput * output)
mate_rr_output_get_possible_crtcs: @output: a MateRROutput Returns: (array zero-terminated=1) (transfer none):
Definition at line 1445 of file mate-rr.c.
References NULL.
mate_rr_output_get_preferred_mode()
MateRRMode * mate_rr_output_get_preferred_mode (MateRROutput * output)
mate_rr_output_get_preferred_mode: @output: a MateRROutput Returns: (transfer none):
Definition at line 1556 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current().
mate_rr_output_get_size_inches()
int mate_rr_output_get_size_inches (MateRROutput * output)
References error.
mate_rr_output_get_type()
GType mate_rr_output_get_type (void)
mate_rr_output_get_width_mm()
int mate_rr_output_get_width_mm (MateRROutput * outout)
Definition at line 1537 of file mate-rr.c.
References NULL.
mate_rr_output_is_connected()
gboolean mate_rr_output_is_connected (MateRROutput * output)
Definition at line 1579 of file mate-rr.c.
References FALSE, and NULL.
Referenced by mate_rr_config_load_current().
mate_rr_output_is_laptop()
gboolean mate_rr_output_is_laptop (MateRROutput * output)
Definition at line 1478 of file mate-rr.c.
References _mate_rr_output_name_is_laptop(), FALSE, MATE_RR_CONNECTOR_TYPE_PANEL, NULL, and TRUE.
Referenced by mate_rr_config_load_current().
mate_rr_output_list_modes()
MateRRMode ** mate_rr_output_list_modes (MateRROutput * output)
mate_rr_output_list_modes: @output: a MateRROutput Returns: (array zero-terminated=1) (transfer none):
Definition at line 1572 of file mate-rr.c.
References NULL.
Referenced by mate_rr_config_load_current().
mate_rr_output_supports_mode()
gboolean mate_rr_output_supports_mode (MateRROutput * output, MateRRMode * mode)
Definition at line 1586 of file mate-rr.c.
References FALSE, NULL, and TRUE.
mate_rr_screen_get_crtc_by_id()
MateRRCrtc * mate_rr_screen_get_crtc_by_id (MateRRScreen * screen, guint32 id)
mate_rr_screen_get_crtc_by_id:
Returns: (transfer none): the CRTC identified by @id
Definition at line 1076 of file mate-rr.c.
References ScreenInfo::crtcs, MATE_IS_RR_SCREEN, and NULL.
mate_rr_screen_get_output_by_id()
MateRROutput * mate_rr_screen_get_output_by_id (MateRRScreen * screen, guint32 id)
mate_rr_screen_get_output_by_id:
Returns: (transfer none): the output identified by @id
Definition at line 1102 of file mate-rr.c.
References MATE_IS_RR_SCREEN, NULL, and ScreenInfo::outputs.
mate_rr_screen_get_output_by_name()
MateRROutput * mate_rr_screen_get_output_by_name (MateRRScreen * screen, const char * name)
Definition at line 1407 of file mate-rr.c.
References MATE_IS_RR_SCREEN, name, NULL, and ScreenInfo::outputs.
mate_rr_screen_get_ranges()
void mate_rr_screen_get_ranges (MateRRScreen * screen, int * min_width, int * max_width, int * min_height, int * max_height)
mate_rr_screen_get_ranges: @screen: a MateRRScreen @min_width: (out): the minimum width @max_width: (out): the maximum width @min_height: (out): the minimum height @max_height: (out): the maximum height
Get the ranges of the screen
Definition at line 865 of file mate-rr.c.
References MateRRScreenPrivate::info, MATE_IS_RR_SCREEN, ScreenInfo::max_height, ScreenInfo::max_width, ScreenInfo::min_height, and ScreenInfo::min_width.
mate_rr_screen_get_timestamps()
void mate_rr_screen_get_timestamps (MateRRScreen * screen, guint32 * change_timestamp_ret, guint32 * config_timestamp_ret)
mate_rr_screen_get_timestamps: @screen: a MateRRScreen @change_timestamp_ret: (out): Location in which to store the timestamp at which the RANDR configuration was last changed @config_timestamp_ret: (out): Location in which to store the timestamp at which the RANDR configuration was last obtained
Queries the two timestamps that the X RANDR extension maintains. The X server will prevent change requests for stale configurations, those whose timestamp is not equal to that of the latest request for configuration. The X server will also prevent change requests that have an older timestamp to the latest change request.
Definition at line 903 of file mate-rr.c.
References MateRRScreenPrivate::info, and MATE_IS_RR_SCREEN.
mate_rr_screen_get_type()
GType mate_rr_screen_get_type (void)
mate_rr_screen_list_clone_modes()
MateRRMode ** mate_rr_screen_list_clone_modes (MateRRScreen * screen)
mate_rr_screen_list_clone_modes:
List available XRandR clone modes
Returns: (array zero-terminated=1) (transfer none):
Definition at line 1030 of file mate-rr.c.
References MATE_IS_RR_SCREEN, and NULL.
mate_rr_screen_list_crtcs()
MateRRCrtc ** mate_rr_screen_list_crtcs (MateRRScreen * screen)
mate_rr_screen_list_crtcs:
List all CRTCs
Returns: (array zero-terminated=1) (transfer none):
Definition at line 1046 of file mate-rr.c.
References MATE_IS_RR_SCREEN, and NULL.
mate_rr_screen_list_modes()
MateRRMode ** mate_rr_screen_list_modes (MateRRScreen * screen)
mate_rr_screen_list_modes:
List available XRandR modes
Returns: (array zero-terminated=1) (transfer none):
Definition at line 1014 of file mate-rr.c.
References MATE_IS_RR_SCREEN, and NULL.
mate_rr_screen_list_outputs()
MateRROutput ** mate_rr_screen_list_outputs (MateRRScreen * screen)
mate_rr_screen_list_outputs:
List all outputs
Returns: (array zero-terminated=1) (transfer none):
Definition at line 1062 of file mate-rr.c.
References MATE_IS_RR_SCREEN, and NULL.
Referenced by mate_rr_config_load_current().
mate_rr_screen_new()
MateRRScreen * mate_rr_screen_new (GdkScreen * screen, GError ** error)
mate_rr_screen_new: @screen: the #GdkScreen on which to operate @error: will be set if XRandR is not supported
Creates a new MateRRScreen instance
Returns: a new MateRRScreen instance or NULL if screen could not be created, for instance if the driver does not support Xrandr 1.2
Definition at line 827 of file mate-rr.c.
References _mate_desktop_init_i18n(), error, MATE_TYPE_RR_SCREEN, and NULL.
Referenced by msd_xrandr_manager_start().
mate_rr_screen_refresh()
gboolean mate_rr_screen_refresh (MateRRScreen * screen, GError ** error)
mate_rr_screen_refresh: @screen: a MateRRScreen @error: location to store error, or NULL
Refreshes the screen configuration, and calls the screen's callback if it exists and if the screen's configuration changed.
Return value: TRUE if the screen's configuration changed; otherwise, the function returns FALSE and a NULL error if the configuration didn't change, or FALSE and a non-NULL error if there was an error while refreshing the configuration.
Definition at line 989 of file mate-rr.c.
References error, FALSE, NULL, and TRUE.
Referenced by mate_rr_config_apply_from_filename_with_time().
mate_rr_screen_set_primary_output()
void mate_rr_screen_set_primary_output (MateRRScreen * screen, MateRROutput * output)
Definition at line 1632 of file mate-rr.c.
References MATE_IS_RR_SCREEN, MateRRScreenPrivate::xdisplay, and MateRRScreenPrivate::xroot.
mate_rr_screen_set_size()
void mate_rr_screen_set_size (MateRRScreen * screen, int width, int height, int mm_width, int mm_height)
Definition at line 835 of file mate-rr.c.
References MATE_IS_RR_SCREEN.