MATE Desktop Environment: mate-panel-applet.h File Reference
mate-panel-applet.h File Reference
#include <glib.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <cairo.h>
#include <cairo-gobject.h>
Classes
struct _MatePanelAppletClass
Macros
#define PANEL_TYPE_APPLET mate_panel_applet_get_type ()
#define MATE_PANEL_APPLET_ORIENT_FIRST MATE_PANEL_APPLET_ORIENT_UP
#define MATE_PANEL_APPLET_ORIENT_LAST MATE_PANEL_APPLET_ORIENT_RIGHT
#define MATE_PANEL_APPLET_FLAGS_ALL (MATE_PANEL_APPLET_EXPAND_MAJOR|MATE_PANEL_APPLET_EXPAND_MINOR|MATE_PANEL_APPLET_HAS_HANDLE)
#define _MATE_PANEL_APPLET_SETUP_GETTEXT(call_textdomain)
#define MATE_PANEL_APPLET_OUT_PROCESS_FACTORY(factory_id, type, name, callback, data)
#define MATE_PANEL_APPLET_IN_PROCESS_FACTORY(factory_id, type, descr, callback, data)
Typedefs
typedef gboolean(* MatePanelAppletFactoryCallback) (MatePanelApplet *applet, const gchar *iid, gpointer user_data)
Enumerations
enum MatePanelAppletBackgroundType { PANEL_NO_BACKGROUND , PANEL_COLOR_BACKGROUND , PANEL_PIXMAP_BACKGROUND }
enum MatePanelAppletFlags { MATE_PANEL_APPLET_FLAGS_NONE = 0 , MATE_PANEL_APPLET_EXPAND_MAJOR = 1 << 0 , MATE_PANEL_APPLET_EXPAND_MINOR = 1 << 1 , MATE_PANEL_APPLET_HAS_HANDLE }
Functions
G_DECLARE_DERIVABLE_TYPE (...) typedef enum
GtkWidget * mate_panel_applet_new (void)
MatePanelAppletOrient mate_panel_applet_get_orient (MatePanelApplet *applet)
guint mate_panel_applet_get_size (MatePanelApplet *applet)
MatePanelAppletBackgroundType mate_panel_applet_get_background (MatePanelApplet *applet, GdkRGBA *color, cairo_pattern_t **pattern)
void mate_panel_applet_set_background_widget (MatePanelApplet *applet, GtkWidget *widget)
gchar * mate_panel_applet_get_preferences_path (MatePanelApplet *applet)
MatePanelAppletFlags mate_panel_applet_get_flags (MatePanelApplet *applet)
void mate_panel_applet_set_flags (MatePanelApplet *applet, MatePanelAppletFlags flags)
void mate_panel_applet_set_size_hints (MatePanelApplet *applet, const int *size_hints, int n_elements, int base_size)
gboolean mate_panel_applet_get_locked_down (MatePanelApplet *applet)
void mate_panel_applet_request_focus (MatePanelApplet *applet, guint32 timestamp)
void mate_panel_applet_setup_menu (MatePanelApplet *applet, const gchar *xml, GtkActionGroup *action_group)
void mate_panel_applet_setup_menu_from_file (MatePanelApplet *applet, const gchar *filename, GtkActionGroup *action_group)
void mate_panel_applet_setup_menu_from_resource (MatePanelApplet *applet, const gchar *resource_path, GtkActionGroup *action_group)
int mate_panel_applet_factory_main (const gchar *factory_id, gboolean out_process, GType applet_type, MatePanelAppletFactoryCallback callback, gpointer data)
int mate_panel_applet_factory_setup_in_process (const gchar *factory_id, GType applet_type, MatePanelAppletFactoryCallback callback, gpointer data)
Variables
MatePanelAppletOrient
Macro Definition Documentation
_MATE_PANEL_APPLET_SETUP_GETTEXT
#define _MATE_PANEL_APPLET_SETUP_GETTEXT (call_textdomain)
Value:
do { } while (0)
Definition at line 150 of file mate-panel-applet.h.
MATE_PANEL_APPLET_FLAGS_ALL
#define MATE_PANEL_APPLET_FLAGS_ALL (MATE_PANEL_APPLET_EXPAND_MAJOR|MATE_PANEL_APPLET_EXPAND_MINOR|MATE_PANEL_APPLET_HAS_HANDLE)
MATE_PANEL_APPLET_IN_PROCESS_FACTORY
#define MATE_PANEL_APPLET_IN_PROCESS_FACTORY (factory_id, type, descr, callback, data)
Value:
gboolean _mate_panel_applet_shlib_factory (void);    \
G_MODULE_EXPORT gint _mate_panel_applet_shlib_factory(void) \
{ \
    _MATE_PANEL_APPLET_SETUP_GETTEXT(FALSE); \
return mate_panel_applet_factory_setup_in_process (factory_id, type,                 \
                                               callback, data);  \
}
Definition at line 199 of file mate-panel-applet.h.
MATE_PANEL_APPLET_ORIENT_FIRST
#define MATE_PANEL_APPLET_ORIENT_FIRST MATE_PANEL_APPLET_ORIENT_UP
MATE_PANEL_APPLET_ORIENT_LAST
#define MATE_PANEL_APPLET_ORIENT_LAST MATE_PANEL_APPLET_ORIENT_RIGHT
MATE_PANEL_APPLET_OUT_PROCESS_FACTORY
#define MATE_PANEL_APPLET_OUT_PROCESS_FACTORY (factory_id, type, name, callback, data)
Definition at line 163 of file mate-panel-applet.h.
PANEL_TYPE_APPLET
#define PANEL_TYPE_APPLET mate_panel_applet_get_type ()
Definition at line 37 of file mate-panel-applet.h.
Referenced by G_DEFINE_TYPE(), G_DEFINE_TYPE(), G_DEFINE_TYPE(), G_DEFINE_TYPE_WITH_PRIVATE(), mate_panel_applet_new(), MATE_PANEL_APPLET_OUT_PROCESS_FACTORY(), PANEL_APPLET_FACTORY(), and PANEL_APPLET_FACTORY().
Typedef Documentation
MatePanelAppletFactoryCallback
typedef gboolean(* MatePanelAppletFactoryCallback) (MatePanelApplet *applet, const gchar *iid, gpointer user_data)
Definition at line 63 of file mate-panel-applet.h.
Enumeration Type Documentation
MatePanelAppletBackgroundType
enum MatePanelAppletBackgroundType
Enumerator
PANEL_NO_BACKGROUND
PANEL_COLOR_BACKGROUND
PANEL_PIXMAP_BACKGROUND
Definition at line 49 of file mate-panel-applet.h.
MatePanelAppletFlags
enum MatePanelAppletFlags
Enumerator
MATE_PANEL_APPLET_FLAGS_NONE
MATE_PANEL_APPLET_EXPAND_MAJOR
MATE_PANEL_APPLET_EXPAND_MINOR
MATE_PANEL_APPLET_HAS_HANDLE
Definition at line 55 of file mate-panel-applet.h.
Function Documentation
G_DECLARE_DERIVABLE_TYPE()
G_DECLARE_DERIVABLE_TYPE (...)
MateUiApplicationClass: @parent_class: Parent class
Class structure for MateUiApplication
MateUiWindowClass: @parent_class: The parent class
The class structure for #MateUiWindow
Definition at line 38 of file mate-panel-applet.h.
mate_panel_applet_factory_main()
int mate_panel_applet_factory_main (const gchar * factory_id, gboolean out_process, GType applet_type, MatePanelAppletFactoryCallback callback, gpointer user_data)
mate_panel_applet_factory_main: @out_process: boolean, dummy to support applets sending it @factory_id: Factory ID. @applet_type: GType of the applet this factory creates. @callback: (scope call): Callback to be called when a new applet is to be created. @data: (closure): Callback data.
Returns: 0 on success, 1 if there is an error.
Definition at line 2505 of file mate-panel-applet.c.
References applet_type, TRUE, and user_data.
mate_panel_applet_factory_setup_in_process()
int mate_panel_applet_factory_setup_in_process (const gchar * factory_id, GType applet_type, MatePanelAppletFactoryCallback callback, gpointer user_data)
mate_panel_applet_factory_setup_in_process: (skip) @factory_id: Factory ID. @applet_type: GType of the applet this factory creates. @callback: (scope call): Callback to be called when a new applet is to be created. @data: (closure): Callback data.
Returns: 0 on success, 1 if there is an error.
Definition at line 2525 of file mate-panel-applet.c.
References applet_type, FALSE, and user_data.
mate_panel_applet_get_background()
MatePanelAppletBackgroundType mate_panel_applet_get_background (MatePanelApplet * applet, GdkRGBA * color, cairo_pattern_t ** pattern)
Definition at line 1495 of file mate-panel-applet.c.
References NULL, and PANEL_NO_BACKGROUND.
mate_panel_applet_get_flags()
MatePanelAppletFlags mate_panel_applet_get_flags (MatePanelApplet * applet)
Definition at line 200 of file mate-panel-applet.c.
References MATE_PANEL_APPLET_FLAGS_NONE.
mate_panel_applet_get_locked_down()
gboolean mate_panel_applet_get_locked_down (MatePanelApplet * applet)
Definition at line 481 of file mate-panel-applet.c.
References FALSE.
Referenced by mateweather_applet_create(), stickynotes_applet_new(), window_list_applet_fill(), and workspace_switcher_applet_fill().
mate_panel_applet_get_orient()
MatePanelAppletOrient mate_panel_applet_get_orient (MatePanelApplet * applet)
Definition at line 400 of file mate-panel-applet.c.
Referenced by active_sensor_new(), build_table(), gvc_applet_fill(), load_graph_new(), mateweather_applet_create(), multiload_applet_refresh(), multiload_properties_cb(), sensors_applet_graph_size_changed(), show_desktop_applet_fill(), stickynotes_applet_new(), window_list_applet_fill(), window_menu_applet_fill(), and workspace_switcher_applet_fill().
mate_panel_applet_get_preferences_path()
gchar * mate_panel_applet_get_preferences_path (MatePanelApplet * applet)
Definition at line 166 of file mate-panel-applet.c.
References NULL.
Referenced by mate_panel_applet_settings_new(), sensors_applet_add_sensor(), sensors_applet_settings_load_sensors(), and sensors_applet_settings_save_sensors().
mate_panel_applet_get_size()
guint mate_panel_applet_get_size (MatePanelApplet * applet)
Definition at line 366 of file mate-panel-applet.c.
Referenced by gvc_applet_fill(), load_graph_new(), mateweather_applet_create(), show_desktop_applet_fill(), stickynotes_applet_init(), stickynotes_applet_new(), window_list_applet_fill(), and window_menu_applet_fill().
mate_panel_applet_new()
GtkWidget * mate_panel_applet_new (void)
Definition at line 2176 of file mate-panel-applet.c.
References NULL, and PANEL_TYPE_APPLET.
mate_panel_applet_request_focus()
void mate_panel_applet_request_focus (MatePanelApplet * applet, guint32 timestamp)
Definition at line 607 of file mate-panel-applet.c.
References GDK_IS_X11_DISPLAY.
mate_panel_applet_set_background_widget()
void mate_panel_applet_set_background_widget (MatePanelApplet * applet, GtkWidget * widget)
mate_panel_applet_set_background_widget: @applet: a #PanelApplet. @widget: a #GtkWidget.
Configure #PanelApplet to automatically draw the background of the applet on @widget. It is generally enough to call this function with @applet as @widget.
Deprecated: 3.20: Do not use this API. Since 3.20 this function does nothing.
Definition at line 2547 of file mate-panel-applet.c.
Referenced by sensors_applet_init().
mate_panel_applet_set_flags()
void mate_panel_applet_set_flags (MatePanelApplet * applet, MatePanelAppletFlags flags)
Definition at line 212 of file mate-panel-applet.c.
References error, MATE_PANEL_APPLET_INTERFACE, and NULL.
Referenced by gvc_applet_fill(), mateweather_applet_create(), sensors_applet_init(), show_desktop_applet_fill(), stickynotes_applet_new(), window_list_applet_fill(), window_menu_applet_fill(), and workspace_switcher_applet_fill().
mate_panel_applet_set_size_hints()
void mate_panel_applet_set_size_hints (MatePanelApplet * applet, const int * size_hints, int n_elements, int base_size)
mate_panel_applet_set_size_hints: @applet: applet @size_hints: (array length=n_elements): List of integers @n_elements: Length of @size_hints @base_size: base_size
Definition at line 308 of file mate-panel-applet.c.
References error, MATE_PANEL_APPLET_INTERFACE, and NULL.
mate_panel_applet_setup_menu()
void mate_panel_applet_setup_menu (MatePanelApplet * applet, const gchar * xml, GtkActionGroup * action_group)
Definition at line 747 of file mate-panel-applet.c.
References error, and NULL.
Referenced by gvc_applet_fill(), mate_panel_applet_setup_menu_from_file(), and mate_panel_applet_setup_menu_from_resource().
mate_panel_applet_setup_menu_from_file()
void mate_panel_applet_setup_menu_from_file (MatePanelApplet * applet, const gchar * filename, GtkActionGroup * action_group)
Definition at line 780 of file mate-panel-applet.c.
References error, mate_panel_applet_setup_menu(), and NULL.
Referenced by sensors_applet_init().
mate_panel_applet_setup_menu_from_resource()
void mate_panel_applet_setup_menu_from_resource (MatePanelApplet * applet, const gchar * resource_path, GtkActionGroup * action_group)
mate_panel_applet_setup_menu_from_resource: @applet: a #MatePanelApplet. @resource_path: a resource path @action_group: a #GtkActionGroup.
Sets up the context menu of @applet. @filename is a resource path to a menu XML file, containing a #GtkUIManager UI definition that describes how to display the menu items. @action_group contains the various #GtkAction that are referenced in @xml.
See also the <link linkend="getting-started.context-menu">Context Menu</link> section.
Since: 1.20.1
Definition at line 814 of file mate-panel-applet.c.
References error, mate_panel_applet_setup_menu(), and NULL.
Referenced by mateweather_applet_create(), show_desktop_applet_fill(), stickynotes_applet_new(), window_list_applet_fill(), window_menu_applet_fill(), and workspace_switcher_applet_fill().
Variable Documentation
MatePanelAppletOrient
MatePanelAppletOrient
Definition at line 47 of file mate-panel-applet.h.
Referenced by active_sensor_new(), applet_change_orient_cb(), gvc_stream_applet_icon_get_type(), gvc_stream_applet_icon_set_orient(), load_graph_new(), multiload_applet_refresh(), and multiload_properties_cb().