MATE Desktop Environment: msd-input-helper.h File Reference
msd-input-helper.h File Reference
#include <glib.h>
#include <X11/extensions/XInput.h>
#include <X11/extensions/XIproto.h>
Functions
gboolean supports_xinput_devices (void)
XDevice * device_is_touchpad (XDeviceInfo *deviceinfo)
gboolean touchpad_is_present (void)
Function Documentation
device_is_touchpad()
XDevice * device_is_touchpad (XDeviceInfo * deviceinfo)
Definition at line 72 of file mate-control-center/capplets/mouse/msd-input-helper.c.
References NULL.
Referenced by touchpad_is_present().
supports_xinput_devices()
gboolean supports_xinput_devices (void)
Definition at line 32 of file mate-control-center/capplets/mouse/msd-input-helper.c.
References error.
Referenced by msd_mouse_manager_start(), and touchpad_is_present().
touchpad_is_present()
gboolean touchpad_is_present (void)
Definition at line 96 of file mate-control-center/capplets/mouse/msd-input-helper.c.
References device_is_touchpad(), FALSE, NULL, supports_xinput_devices(), and TRUE.