MATE Desktop Environment: matekbd-indicator.c File Reference
matekbd-indicator.c File Reference
#include <config.h>
#include <memory.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <gdk/gdkx.h>
#include <glib/gi18n-lib.h>
#include <matekbd-indicator.h>
#include <matekbd-indicator-marshal.h>
#include <matekbd-desktop-config.h>
#include <matekbd-indicator-config.h>
Macros
#define ForAllIndicators()
#define NextIndicator()
Typedefs
typedef struct _gki_globals gki_globals
Functions
void matekbd_indicator_load_images ()
gchar * matekbd_indicator_extract_layout_name (int group, XklEngine *engine, MatekbdKeyboardConfig *kbd_cfg, gchar **short_group_names, gchar **full_group_names)
gchar * matekbd_indicator_create_label_title (int group, GHashTable **ln2cnt_map, gchar *layout_name)
void matekbd_indicator_reinit_ui (MatekbdIndicator *gki)
GtkWidget * matekbd_indicator_new (void)
void matekbd_indicator_set_parent_tooltips (MatekbdIndicator *gki, gboolean spt)
void matekbd_indicator_set_tooltips_format (const gchar format[])
XklEngine * matekbd_indicator_get_xkl_engine ()
gchar ** matekbd_indicator_get_group_names ()
gchar * matekbd_indicator_get_image_filename (guint group)
gdouble matekbd_indicator_get_max_width_height_ratio (void)
void matekbd_indicator_set_angle (MatekbdIndicator *gki, gdouble angle)
Macro Definition Documentation
ForAllIndicators
#define ForAllIndicators ()
Value:
{ \
    GSList* cur; \
    for (cur = globals.widget_instances; cur != NULL; cur = cur->next) { \
        MatekbdIndicator * gki = (MatekbdIndicator*)cur->data;
Definition at line 57 of file matekbd-indicator.c.
Referenced by matekbd_indicator_set_tooltips_format().
NextIndicator
#define NextIndicator ()
Value:
    } \
}
Definition at line 62 of file matekbd-indicator.c.
Referenced by matekbd_indicator_set_tooltips_format().
Typedef Documentation
gki_globals
typedef struct _gki_globals gki_globals
Function Documentation
matekbd_indicator_create_label_title()
gchar * matekbd_indicator_create_label_title (int group, GHashTable ** ln2cnt_map, gchar * layout_name)
Definition at line 323 of file matekbd-indicator.c.
References NULL.
matekbd_indicator_extract_layout_name()
gchar * matekbd_indicator_extract_layout_name (int group, XklEngine * engine, MatekbdKeyboardConfig * kbd_cfg, gchar ** short_group_names, gchar ** full_group_names)
Definition at line 279 of file matekbd-indicator.c.
References engine, _MatekbdKeyboardConfig::layouts_variants, matekbd_keyboard_config_split_items(), and NULL.
matekbd_indicator_get_group_names()
gchar ** matekbd_indicator_get_group_names (void)
matekbd_indicator_get_group_names:
Returns: (transfer none) (array zero-terminated=1): List of group names
Definition at line 877 of file matekbd-indicator.c.
matekbd_indicator_get_image_filename()
gchar * matekbd_indicator_get_image_filename (guint group)
Definition at line 883 of file matekbd-indicator.c.
References matekbd_indicator_config_get_images_file(), and NULL.
matekbd_indicator_get_max_width_height_ratio()
gdouble matekbd_indicator_get_max_width_height_ratio (void)
Definition at line 893 of file matekbd-indicator.c.
References NULL.
matekbd_indicator_get_xkl_engine()
XklEngine * matekbd_indicator_get_xkl_engine (void)
matekbd_indicator_get_xkl_engine:
Returns: (transfer none): The engine shared by all MatekbdIndicator objects
Definition at line 866 of file matekbd-indicator.c.
matekbd_indicator_load_images()
void matekbd_indicator_load_images ()
Definition at line 86 of file matekbd-indicator.c.
References _, FALSE, matekbd_indicator_config_load_image_filenames(), message(), and NULL.
matekbd_indicator_new()
GtkWidget * matekbd_indicator_new (void)
Definition at line 838 of file matekbd-indicator.c.
References matekbd_indicator_get_type(), and NULL.
Referenced by main().
matekbd_indicator_reinit_ui()
void matekbd_indicator_reinit_ui (MatekbdIndicator * gki)
Definition at line 454 of file matekbd-indicator.c.
matekbd_indicator_set_angle()
void matekbd_indicator_set_angle (MatekbdIndicator * gki, gdouble angle)
Definition at line 912 of file matekbd-indicator.c.
References _MatekbdIndicator::priv.
matekbd_indicator_set_parent_tooltips()
void matekbd_indicator_set_parent_tooltips (MatekbdIndicator * gki, gboolean spt)
Definition at line 845 of file matekbd-indicator.c.
References _MatekbdIndicator::priv.
Referenced by main().
matekbd_indicator_set_tooltips_format()
void matekbd_indicator_set_tooltips_format (const gchar format[])
Definition at line 852 of file matekbd-indicator.c.
References ForAllIndicators, and NextIndicator.
Referenced by main().