MATE Desktop Environment: matemixer-backend.h File Reference
matemixer-backend.h File Reference
#include <glib.h>
#include <glib-object.h>
#include "matemixer-enums.h"
#include "matemixer-types.h"
Classes
struct _MateMixerBackend
struct _MateMixerBackendClass
Macros
#define MATE_MIXER_TYPE_BACKEND (mate_mixer_backend_get_type ())
#define MATE_MIXER_BACKEND(o)
#define MATE_MIXER_IS_BACKEND(o)
#define MATE_MIXER_BACKEND_CLASS(k)
#define MATE_MIXER_IS_BACKEND_CLASS(k)
#define MATE_MIXER_BACKEND_GET_CLASS(o)
Typedefs
typedef struct _MateMixerBackend MateMixerBackend
typedef struct _MateMixerBackendClass MateMixerBackendClass
typedef struct _MateMixerBackendPrivate MateMixerBackendPrivate
Functions
GType mate_mixer_backend_get_type (void)
void mate_mixer_backend_set_app_info (MateMixerBackend *backend, MateMixerAppInfo *info)
void mate_mixer_backend_set_server_address (MateMixerBackend *backend, const gchar *address)
gboolean mate_mixer_backend_open (MateMixerBackend *backend)
void mate_mixer_backend_close (MateMixerBackend *backend)
MateMixerState mate_mixer_backend_get_state (MateMixerBackend *backend)
MateMixerDevice * mate_mixer_backend_get_device (MateMixerBackend *backend, const gchar *name)
MateMixerStream * mate_mixer_backend_get_stream (MateMixerBackend *backend, const gchar *name)
MateMixerStoredControl * mate_mixer_backend_get_stored_control (MateMixerBackend *backend, const gchar *name)
const GList * mate_mixer_backend_list_devices (MateMixerBackend *backend)
const GList * mate_mixer_backend_list_streams (MateMixerBackend *backend)
const GList * mate_mixer_backend_list_stored_controls (MateMixerBackend *backend)
MateMixerStream * mate_mixer_backend_get_default_input_stream (MateMixerBackend *backend)
gboolean mate_mixer_backend_set_default_input_stream (MateMixerBackend *backend, MateMixerStream *stream)
MateMixerStream * mate_mixer_backend_get_default_output_stream (MateMixerBackend *backend)
gboolean mate_mixer_backend_set_default_output_stream (MateMixerBackend *backend, MateMixerStream *stream)
void _mate_mixer_backend_set_state (MateMixerBackend *backend, MateMixerState state)
void _mate_mixer_backend_set_default_input_stream (MateMixerBackend *backend, MateMixerStream *stream)
void _mate_mixer_backend_set_default_output_stream (MateMixerBackend *backend, MateMixerStream *stream)
Macro Definition Documentation
MATE_MIXER_BACKEND
#define MATE_MIXER_BACKEND (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), MATE_MIXER_TYPE_BACKEND, MateMixerBackend))
Definition at line 31 of file matemixer-backend.h.
Referenced by mate_mixer_context_get_device(), mate_mixer_context_get_stored_control(), mate_mixer_context_get_stream(), mate_mixer_context_list_devices(), mate_mixer_context_list_stored_controls(), and mate_mixer_context_list_streams().
MATE_MIXER_BACKEND_CLASS
#define MATE_MIXER_BACKEND_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST ((k), MATE_MIXER_TYPE_BACKEND, MateMixerBackendClass))
Definition at line 35 of file matemixer-backend.h.
MATE_MIXER_BACKEND_GET_CLASS
#define MATE_MIXER_BACKEND_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), MATE_MIXER_TYPE_BACKEND, MateMixerBackendClass))
Definition at line 39 of file matemixer-backend.h.
Referenced by mate_mixer_backend_close(), mate_mixer_backend_list_devices(), mate_mixer_backend_list_stored_controls(), mate_mixer_backend_list_streams(), mate_mixer_backend_open(), mate_mixer_backend_set_app_info(), mate_mixer_backend_set_default_input_stream(), mate_mixer_backend_set_default_output_stream(), and mate_mixer_backend_set_server_address().
MATE_MIXER_IS_BACKEND
#define MATE_MIXER_IS_BACKEND (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), MATE_MIXER_TYPE_BACKEND))
Definition at line 33 of file matemixer-backend.h.
Referenced by _mate_mixer_backend_set_default_input_stream(), _mate_mixer_backend_set_default_output_stream(), _mate_mixer_backend_set_state(), mate_mixer_backend_close(), mate_mixer_backend_get_default_input_stream(), mate_mixer_backend_get_default_output_stream(), mate_mixer_backend_get_device(), mate_mixer_backend_get_state(), mate_mixer_backend_get_stored_control(), mate_mixer_backend_get_stream(), mate_mixer_backend_list_devices(), mate_mixer_backend_list_stored_controls(), mate_mixer_backend_list_streams(), mate_mixer_backend_open(), mate_mixer_backend_set_app_info(), mate_mixer_backend_set_default_input_stream(), mate_mixer_backend_set_default_output_stream(), and mate_mixer_backend_set_server_address().
MATE_MIXER_IS_BACKEND_CLASS
#define MATE_MIXER_IS_BACKEND_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), MATE_MIXER_TYPE_BACKEND))
Definition at line 37 of file matemixer-backend.h.
MATE_MIXER_TYPE_BACKEND
#define MATE_MIXER_TYPE_BACKEND (mate_mixer_backend_get_type ())
Definition at line 29 of file matemixer-backend.h.
Referenced by G_DEFINE_DYNAMIC_TYPE_EXTENDED().
Typedef Documentation
MateMixerBackend
typedef struct _MateMixerBackend MateMixerBackend
Definition at line 42 of file matemixer-backend.h.
MateMixerBackendClass
typedef struct _MateMixerBackendClass MateMixerBackendClass
Definition at line 43 of file matemixer-backend.h.
MateMixerBackendPrivate
typedef struct _MateMixerBackendPrivate MateMixerBackendPrivate
Definition at line 44 of file matemixer-backend.h.
Function Documentation
_mate_mixer_backend_set_default_input_stream()
void _mate_mixer_backend_set_default_input_stream (MateMixerBackend * backend, MateMixerStream * stream)
Definition at line 609 of file matemixer-backend.c.
References MATE_MIXER_IS_BACKEND, MATE_MIXER_IS_STREAM, mate_mixer_stream_get_name(), NULL, _MateMixerBackend::priv, and PROP_DEFAULT_INPUT_STREAM.
Referenced by mate_mixer_backend_set_default_input_stream().
_mate_mixer_backend_set_default_output_stream()
void _mate_mixer_backend_set_default_output_stream (MateMixerBackend * backend, MateMixerStream * stream)
Definition at line 634 of file matemixer-backend.c.
References MATE_MIXER_IS_BACKEND, MATE_MIXER_IS_STREAM, mate_mixer_stream_get_name(), NULL, _MateMixerBackend::priv, and PROP_DEFAULT_OUTPUT_STREAM.
Referenced by mate_mixer_backend_set_default_output_stream().
_mate_mixer_backend_set_state()
void _mate_mixer_backend_set_state (MateMixerBackend * backend, MateMixerState state)
Definition at line 596 of file matemixer-backend.c.
References MATE_MIXER_IS_BACKEND, _MateMixerBackend::priv, and PROP_STATE.
Referenced by alsa_backend_close().
mate_mixer_backend_close()
void mate_mixer_backend_close (MateMixerBackend * backend)
Definition at line 331 of file matemixer-backend.c.
References _MateMixerBackendClass::close, MATE_MIXER_BACKEND_GET_CLASS, MATE_MIXER_IS_BACKEND, and NULL.
mate_mixer_backend_get_default_input_stream()
MateMixerStream * mate_mixer_backend_get_default_input_stream (MateMixerBackend * backend)
Definition at line 457 of file matemixer-backend.c.
References MATE_MIXER_IS_BACKEND, NULL, and _MateMixerBackend::priv.
Referenced by mate_mixer_context_get_default_input_stream().
mate_mixer_backend_get_default_output_stream()
MateMixerStream * mate_mixer_backend_get_default_output_stream (MateMixerBackend * backend)
Definition at line 492 of file matemixer-backend.c.
References MATE_MIXER_IS_BACKEND, NULL, and _MateMixerBackend::priv.
Referenced by mate_mixer_context_get_default_output_stream().
mate_mixer_backend_get_device()
MateMixerDevice * mate_mixer_backend_get_device (MateMixerBackend * backend, const gchar * name)
Definition at line 352 of file matemixer-backend.c.
References mate_mixer_backend_list_devices(), MATE_MIXER_DEVICE, mate_mixer_device_get_name(), MATE_MIXER_IS_BACKEND, name, and NULL.
Referenced by mate_mixer_context_get_device().
mate_mixer_backend_get_state()
MateMixerState mate_mixer_backend_get_state (MateMixerBackend * backend)
Definition at line 344 of file matemixer-backend.c.
References MATE_MIXER_IS_BACKEND, MATE_MIXER_STATE_UNKNOWN, and _MateMixerBackend::priv.
Referenced by mate_mixer_context_open().
mate_mixer_backend_get_stored_control()
MateMixerStoredControl * mate_mixer_backend_get_stored_control (MateMixerBackend * backend, const gchar * name)
Definition at line 392 of file matemixer-backend.c.
References mate_mixer_backend_list_stored_controls(), MATE_MIXER_IS_BACKEND, MATE_MIXER_STORED_CONTROL, MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), name, and NULL.
Referenced by mate_mixer_context_get_stored_control().
mate_mixer_backend_get_stream()
MateMixerStream * mate_mixer_backend_get_stream (MateMixerBackend * backend, const gchar * name)
Definition at line 372 of file matemixer-backend.c.
References mate_mixer_backend_list_streams(), MATE_MIXER_IS_BACKEND, MATE_MIXER_STREAM, mate_mixer_stream_get_name(), name, and NULL.
Referenced by mate_mixer_context_get_stream().
mate_mixer_backend_get_type()
GType mate_mixer_backend_get_type (void)
References name.
mate_mixer_backend_list_devices()
const GList * mate_mixer_backend_list_devices (MateMixerBackend * backend)
Definition at line 412 of file matemixer-backend.c.
References _MateMixerBackendClass::list_devices, MATE_MIXER_BACKEND_GET_CLASS, MATE_MIXER_IS_BACKEND, and NULL.
Referenced by mate_mixer_backend_get_device(), and mate_mixer_context_list_devices().
mate_mixer_backend_list_stored_controls()
const GList * mate_mixer_backend_list_stored_controls (MateMixerBackend * backend)
Definition at line 442 of file matemixer-backend.c.
References _MateMixerBackendClass::list_stored_controls, MATE_MIXER_BACKEND_GET_CLASS, MATE_MIXER_IS_BACKEND, and NULL.
Referenced by mate_mixer_backend_get_stored_control(), and mate_mixer_context_list_stored_controls().
mate_mixer_backend_list_streams()
const GList * mate_mixer_backend_list_streams (MateMixerBackend * backend)
Definition at line 427 of file matemixer-backend.c.
References _MateMixerBackendClass::list_streams, MATE_MIXER_BACKEND_GET_CLASS, MATE_MIXER_IS_BACKEND, and NULL.
Referenced by mate_mixer_backend_get_stream(), and mate_mixer_context_list_streams().
mate_mixer_backend_open()
gboolean mate_mixer_backend_open (MateMixerBackend * backend)
Definition at line 322 of file matemixer-backend.c.
References FALSE, MATE_MIXER_BACKEND_GET_CLASS, and MATE_MIXER_IS_BACKEND.
Referenced by mate_mixer_context_open().
mate_mixer_backend_set_app_info()
void mate_mixer_backend_set_app_info (MateMixerBackend * backend, MateMixerAppInfo * info)
Definition at line 296 of file matemixer-backend.c.
References MATE_MIXER_BACKEND_GET_CLASS, MATE_MIXER_IS_BACKEND, NULL, and _MateMixerBackendClass::set_app_info.
Referenced by mate_mixer_context_open().
mate_mixer_backend_set_default_input_stream()
gboolean mate_mixer_backend_set_default_input_stream (MateMixerBackend * backend, MateMixerStream * stream)
Definition at line 465 of file matemixer-backend.c.
References _mate_mixer_backend_set_default_input_stream(), FALSE, MATE_MIXER_BACKEND_GET_CLASS, MATE_MIXER_DIRECTION_INPUT, MATE_MIXER_IS_BACKEND, MATE_MIXER_IS_STREAM, mate_mixer_stream_get_direction(), NULL, _MateMixerBackend::priv, _MateMixerBackendClass::set_default_input_stream, and TRUE.
Referenced by mate_mixer_context_set_default_input_stream().
mate_mixer_backend_set_default_output_stream()
gboolean mate_mixer_backend_set_default_output_stream (MateMixerBackend * backend, MateMixerStream * stream)
Definition at line 500 of file matemixer-backend.c.
References _mate_mixer_backend_set_default_output_stream(), FALSE, MATE_MIXER_BACKEND_GET_CLASS, MATE_MIXER_DIRECTION_OUTPUT, MATE_MIXER_IS_BACKEND, MATE_MIXER_IS_STREAM, mate_mixer_stream_get_direction(), NULL, _MateMixerBackend::priv, _MateMixerBackendClass::set_default_output_stream, and TRUE.
Referenced by mate_mixer_context_set_default_output_stream().
mate_mixer_backend_set_server_address()
void mate_mixer_backend_set_server_address (MateMixerBackend * backend, const gchar * address)
Definition at line 309 of file matemixer-backend.c.
References MATE_MIXER_BACKEND_GET_CLASS, MATE_MIXER_IS_BACKEND, NULL, and _MateMixerBackendClass::set_server_address.
Referenced by mate_mixer_context_open().