MATE Desktop Environment: matemixer-switch-option.c File Reference
matemixer-switch-option.c File Reference
#include <glib.h>
#include <glib-object.h>
#include "matemixer-switch-option.h"
#include "matemixer-switch-option-private.h"
Enumerations
enum {
PROP_0 , PROP_NAME , PROP_LABEL , PROP_ICON ,
N_PROPERTIES
}
Functions
const gchar * mate_mixer_switch_option_get_name (MateMixerSwitchOption *option)
const gchar * mate_mixer_switch_option_get_label (MateMixerSwitchOption *option)
const gchar * mate_mixer_switch_option_get_icon (MateMixerSwitchOption *option)
MateMixerSwitchOption * _mate_mixer_switch_option_new (const gchar *name, const gchar *label, const gchar *icon)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_NAME
PROP_LABEL
PROP_ICON
N_PROPERTIES
Definition at line 36 of file matemixer-switch-option.c.
Function Documentation
_mate_mixer_switch_option_new()
MateMixerSwitchOption * _mate_mixer_switch_option_new (const gchar * name, const gchar * label, const gchar * icon)
Definition at line 248 of file matemixer-switch-option.c.
References label, MATE_MIXER_TYPE_SWITCH_OPTION, name, and NULL.
mate_mixer_switch_option_get_icon()
const gchar * mate_mixer_switch_option_get_icon (MateMixerSwitchOption * option)
mate_mixer_switch_option_get_icon: @option: a MateMixerSwitchOption
Gets the XDG icon name of the switch option.
Returns: the icon name or NULL.
Definition at line 240 of file matemixer-switch-option.c.
References MATE_MIXER_IS_SWITCH_OPTION, NULL, and option.
Referenced by pulse_sink_new(), and pulse_source_new().
mate_mixer_switch_option_get_label()
const gchar * mate_mixer_switch_option_get_label (MateMixerSwitchOption * option)
mate_mixer_switch_option_get_label: @option: a MateMixerSwitchOption
Gets the label of the switch option. This is a potentially translated string that should be presented to users in the user interface.
Returns: the label of the switch option.
Definition at line 224 of file matemixer-switch-option.c.
References MATE_MIXER_IS_SWITCH_OPTION, NULL, and option.
mate_mixer_switch_option_get_name()
const gchar * mate_mixer_switch_option_get_name (MateMixerSwitchOption * option)
mate_mixer_switch_option_get_name: @option: a MateMixerSwitchOption
Gets the name of the switch option. The name serves as a unique identifier and in most cases it is not in a user-readable form.
The returned name is guaranteed to be unique across all the switch options of a particular MateMixerSwitch and may be used to get the MateMixerSwitchOption using mate_mixer_switch_get_option().
Returns: the name of the switch option.
Definition at line 207 of file matemixer-switch-option.c.
References MATE_MIXER_IS_SWITCH_OPTION, NULL, and option.
Referenced by oss_switch_load(), pulse_device_profile_get_name(), and pulse_port_get_name().