MATE Desktop Environment: mate-wp-item.h File Reference
mate-wp-item.h File Reference
#include <glib.h>
#include <gio/gio.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gtk/gtk.h>
#include <libmate-desktop/mate-desktop-thumbnail.h>
#include <libmate-desktop/mate-bg.h>
#include "mate-wp-info.h"
Classes
struct _MateWPItem
Typedefs
typedef struct _MateWPItem MateWPItem
Functions
MateWPItem * mate_wp_item_new (const gchar *filename, GHashTable *wallpapers, MateDesktopThumbnailFactory *thumbnails)
void mate_wp_item_free (MateWPItem *item)
GdkPixbuf * mate_wp_item_get_thumbnail (MateWPItem *item, MateDesktopThumbnailFactory *thumbs, gint width, gint height)
GdkPixbuf * mate_wp_item_get_frame_thumbnail (MateWPItem *item, MateDesktopThumbnailFactory *thumbs, gint width, gint height, gint frame)
void mate_wp_item_update (MateWPItem *item)
void mate_wp_item_update_description (MateWPItem *item)
void mate_wp_item_ensure_mate_bg (MateWPItem *item)
const gchar * wp_item_option_to_string (MateBGPlacement type)
const gchar * wp_item_shading_to_string (MateBGColorType type)
MateBGPlacement wp_item_string_to_option (const gchar *option)
MateBGColorType wp_item_string_to_shading (const gchar *shade_type)
Typedef Documentation
MateWPItem
typedef struct _MateWPItem MateWPItem
Definition at line 33 of file mate-wp-item.h.
Function Documentation
mate_wp_item_ensure_mate_bg()
void mate_wp_item_ensure_mate_bg (MateWPItem * item)
Definition at line 110 of file mate-wp-item.c.
References item, and mate_bg_new().
Referenced by mate_wp_item_new().
mate_wp_item_free()
void mate_wp_item_free (MateWPItem * item)
Definition at line 185 of file mate-wp-item.c.
References item, mate_wp_info_free(), and NULL.
Referenced by mate_wp_item_new(), and mate_wp_xml_save_list().
mate_wp_item_get_frame_thumbnail()
GdkPixbuf * mate_wp_item_get_frame_thumbnail (MateWPItem * item, MateDesktopThumbnailFactory * thumbs, gint width, gint height, gint frame)
References item, and option.
mate_wp_item_get_thumbnail()
GdkPixbuf * mate_wp_item_get_thumbnail (MateWPItem * item, MateDesktopThumbnailFactory * thumbs, gint width, gint height)
Definition at line 266 of file mate-wp-item.c.
References item, and mate_wp_item_get_frame_thumbnail().
mate_wp_item_new()
MateWPItem * mate_wp_item_new (const gchar * filename, GHashTable * wallpapers, MateDesktopThumbnailFactory * thumbnails)
Definition at line 154 of file mate-wp-item.c.
References item, mate_wp_info_new(), mate_wp_item_ensure_mate_bg(), mate_wp_item_free(), mate_wp_item_update(), mate_wp_item_update_description(), and NULL.
mate_wp_item_update()
void mate_wp_item_update (MateWPItem * item)
Definition at line 119 of file mate-wp-item.c.
References item, NULL, WP_OPTIONS_KEY, WP_PCOLOR_KEY, WP_SCHEMA, WP_SCOLOR_KEY, and WP_SHADING_KEY.
Referenced by mate_wp_item_new().
mate_wp_item_update_description()
void mate_wp_item_update_description (MateWPItem * item)
Definition at line 273 of file mate-wp-item.c.
References _, item, mate_bg_changes_with_time(), mate_bg_has_multiple_sizes(), and NULL.
Referenced by mate_wp_item_new().
wp_item_option_to_string()
const gchar * wp_item_option_to_string (MateBGPlacement type)
Definition at line 29 of file mate-wp-item.c.
References MATE_BG_PLACEMENT_CENTERED, MATE_BG_PLACEMENT_FILL_SCREEN, MATE_BG_PLACEMENT_SCALED, MATE_BG_PLACEMENT_SPANNED, MATE_BG_PLACEMENT_TILED, and MATE_BG_PLACEMENT_ZOOMED.
Referenced by mate_wp_xml_save_list().
wp_item_shading_to_string()
const gchar * wp_item_shading_to_string (MateBGColorType type)
Definition at line 55 of file mate-wp-item.c.
References MATE_BG_COLOR_H_GRADIENT, MATE_BG_COLOR_SOLID, and MATE_BG_COLOR_V_GRADIENT.
Referenced by mate_wp_xml_save_list().
wp_item_string_to_option()
MateBGPlacement wp_item_string_to_option (const gchar * option)
Definition at line 71 of file mate-wp-item.c.
References MATE_BG_PLACEMENT_CENTERED, MATE_BG_PLACEMENT_FILL_SCREEN, MATE_BG_PLACEMENT_SCALED, MATE_BG_PLACEMENT_SPANNED, MATE_BG_PLACEMENT_TILED, MATE_BG_PLACEMENT_ZOOMED, and option.
wp_item_string_to_shading()
MateBGColorType wp_item_string_to_shading (const gchar * shade_type)
Definition at line 89 of file mate-wp-item.c.
References MATE_BG_COLOR_H_GRADIENT, MATE_BG_COLOR_SOLID, and MATE_BG_COLOR_V_GRADIENT.