MATE Desktop Environment: mate-bg.h File Reference
mate-bg.h File Reference
#include <glib.h>
#include <gdk/gdk.h>
#include <gio/gio.h>
#include "mate-desktop-thumbnail.h"
#include "mate-bg-crossfade.h"
Macros
#define MATE_TYPE_BG (mate_bg_get_type ())
#define MATE_BG(obj)
#define MATE_BG_CLASS(klass)
#define MATE_IS_BG(obj)
#define MATE_IS_BG_CLASS(klass)
#define MATE_BG_GET_CLASS(obj)
#define MATE_BG_SCHEMA "org.mate.background"
#define MATE_BG_KEY_DRAW_BACKGROUND "draw-background"
#define MATE_BG_KEY_SHOW_DESKTOP "show-desktop-icons"
#define MATE_BG_KEY_BACKGROUND_FADE "background-fade"
#define MATE_BG_KEY_PRIMARY_COLOR "primary-color"
#define MATE_BG_KEY_SECONDARY_COLOR "secondary-color"
#define MATE_BG_KEY_COLOR_TYPE "color-shading-type"
#define MATE_BG_KEY_PICTURE_PLACEMENT "picture-options"
#define MATE_BG_KEY_PICTURE_OPACITY "picture-opacity"
#define MATE_BG_KEY_PICTURE_FILENAME "picture-filename"
Typedefs
typedef struct _MateBG MateBG
typedef struct _MateBGClass MateBGClass
Enumerations
enum MateBGColorType { MATE_BG_COLOR_SOLID , MATE_BG_COLOR_H_GRADIENT , MATE_BG_COLOR_V_GRADIENT }
enum MateBGPlacement {
MATE_BG_PLACEMENT_TILED , MATE_BG_PLACEMENT_ZOOMED , MATE_BG_PLACEMENT_CENTERED , MATE_BG_PLACEMENT_SCALED ,
MATE_BG_PLACEMENT_FILL_SCREEN , MATE_BG_PLACEMENT_SPANNED
}
Functions
GType mate_bg_get_type (void)
MateBG * mate_bg_new (void)
void mate_bg_load_from_preferences (MateBG *bg)
void mate_bg_load_from_system_preferences (MateBG *bg)
void mate_bg_load_from_system_gsettings (MateBG *bg, GSettings *settings, gboolean reset_apply)
void mate_bg_load_from_gsettings (MateBG *bg, GSettings *settings)
void mate_bg_save_to_preferences (MateBG *bg)
void mate_bg_save_to_gsettings (MateBG *bg, GSettings *settings)
void mate_bg_set_filename (MateBG *bg, const char *filename)
void mate_bg_set_placement (MateBG *bg, MateBGPlacement placement)
void mate_bg_set_color (MateBG *bg, MateBGColorType type, GdkRGBA *primary, GdkRGBA *secondary)
void mate_bg_set_draw_background (MateBG *bg, gboolean draw_background)
gboolean mate_bg_get_draw_background (MateBG *bg)
MateBGPlacement mate_bg_get_placement (MateBG *bg)
void mate_bg_get_color (MateBG *bg, MateBGColorType *type, GdkRGBA *primary, GdkRGBA *secondary)
const gchar * mate_bg_get_filename (MateBG *bg)
void mate_bg_draw (MateBG *bg, GdkPixbuf *dest, GdkScreen *screen, gboolean is_root)
cairo_surface_t * mate_bg_create_surface (MateBG *bg, GdkWindow *window, int width, int height, gboolean root)
cairo_surface_t * mate_bg_create_surface_scale (MateBG *bg, GdkWindow *window, int width, int height, int scale, gboolean root)
gboolean mate_bg_get_image_size (MateBG *bg, MateDesktopThumbnailFactory *factory, int best_width, int best_height, int *width, int *height)
GdkPixbuf * mate_bg_create_thumbnail (MateBG *bg, MateDesktopThumbnailFactory *factory, GdkScreen *screen, int dest_width, int dest_height)
gboolean mate_bg_is_dark (MateBG *bg, int dest_width, int dest_height)
gboolean mate_bg_has_multiple_sizes (MateBG *bg)
gboolean mate_bg_changes_with_time (MateBG *bg)
GdkPixbuf * mate_bg_create_frame_thumbnail (MateBG *bg, MateDesktopThumbnailFactory *factory, GdkScreen *screen, int dest_width, int dest_height, int frame_num)
void mate_bg_set_surface_as_root (GdkScreen *screen, cairo_surface_t *surface)
MateBGCrossfade * mate_bg_set_surface_as_root_with_crossfade (GdkScreen *screen, cairo_surface_t *surface)
cairo_surface_t * mate_bg_get_surface_from_root (GdkScreen *screen)
Macro Definition Documentation
MATE_BG
#define MATE_BG (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_BG, MateBG))
Definition at line 44 of file mate-bg.h.
MATE_BG_CLASS
#define MATE_BG_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass),  MATE_TYPE_BG, MateBGClass))
Definition at line 45 of file mate-bg.h.
MATE_BG_GET_CLASS
#define MATE_BG_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj),  MATE_TYPE_BG, MateBGClass))
Definition at line 48 of file mate-bg.h.
MATE_BG_KEY_BACKGROUND_FADE
#define MATE_BG_KEY_BACKGROUND_FADE "background-fade"
Definition at line 59 of file mate-bg.h.
MATE_BG_KEY_COLOR_TYPE
#define MATE_BG_KEY_COLOR_TYPE "color-shading-type"
Definition at line 63 of file mate-bg.h.
Referenced by mate_bg_load_from_gsettings(), and mate_bg_save_to_gsettings().
MATE_BG_KEY_DRAW_BACKGROUND
#define MATE_BG_KEY_DRAW_BACKGROUND "draw-background"
Definition at line 53 of file mate-bg.h.
Referenced by mate_bg_load_from_gsettings(), mate_bg_save_to_gsettings(), and msd_background_manager_start().
MATE_BG_KEY_PICTURE_FILENAME
#define MATE_BG_KEY_PICTURE_FILENAME "picture-filename"
Definition at line 66 of file mate-bg.h.
Referenced by eel_bg_load_from_gsettings(), mate_bg_load_from_gsettings(), and mate_bg_save_to_gsettings().
MATE_BG_KEY_PICTURE_OPACITY
#define MATE_BG_KEY_PICTURE_OPACITY "picture-opacity"
Definition at line 65 of file mate-bg.h.
MATE_BG_KEY_PICTURE_PLACEMENT
#define MATE_BG_KEY_PICTURE_PLACEMENT "picture-options"
Definition at line 64 of file mate-bg.h.
Referenced by mate_bg_load_from_gsettings(), and mate_bg_save_to_gsettings().
MATE_BG_KEY_PRIMARY_COLOR
#define MATE_BG_KEY_PRIMARY_COLOR "primary-color"
Definition at line 61 of file mate-bg.h.
Referenced by mate_bg_load_from_gsettings(), and mate_bg_save_to_gsettings().
MATE_BG_KEY_SECONDARY_COLOR
#define MATE_BG_KEY_SECONDARY_COLOR "secondary-color"
Definition at line 62 of file mate-bg.h.
Referenced by mate_bg_load_from_gsettings(), and mate_bg_save_to_gsettings().
MATE_BG_KEY_SHOW_DESKTOP
#define MATE_BG_KEY_SHOW_DESKTOP "show-desktop-icons"
Definition at line 56 of file mate-bg.h.
Referenced by msd_background_manager_start().
MATE_BG_SCHEMA
#define MATE_BG_SCHEMA "org.mate.background"
Definition at line 50 of file mate-bg.h.
Referenced by mate_bg_load_from_preferences(), mate_bg_load_from_system_preferences(), mate_bg_save_to_preferences(), and msd_background_manager_start().
MATE_IS_BG
#define MATE_IS_BG (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_BG))
Definition at line 46 of file mate-bg.h.
Referenced by mate_bg_load_from_gsettings(), mate_bg_load_from_system_gsettings(), and mate_bg_save_to_gsettings().
MATE_IS_BG_CLASS
#define MATE_IS_BG_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass),  MATE_TYPE_BG))
Definition at line 47 of file mate-bg.h.
MATE_TYPE_BG
#define MATE_TYPE_BG (mate_bg_get_type ())
Definition at line 43 of file mate-bg.h.
Referenced by mate_bg_new().
Typedef Documentation
MateBG
typedef struct _MateBG MateBG
Definition at line 68 of file mate-bg.h.
MateBGClass
typedef struct _MateBGClass MateBGClass
Definition at line 69 of file mate-bg.h.
Enumeration Type Documentation
MateBGColorType
enum MateBGColorType
Enumerator
MATE_BG_COLOR_SOLID
MATE_BG_COLOR_H_GRADIENT
MATE_BG_COLOR_V_GRADIENT
Definition at line 71 of file mate-bg.h.
MateBGPlacement
enum MateBGPlacement
Enumerator
MATE_BG_PLACEMENT_TILED
MATE_BG_PLACEMENT_ZOOMED
MATE_BG_PLACEMENT_CENTERED
MATE_BG_PLACEMENT_SCALED
MATE_BG_PLACEMENT_FILL_SCREEN
MATE_BG_PLACEMENT_SPANNED
Definition at line 77 of file mate-bg.h.
Function Documentation
mate_bg_changes_with_time()
gboolean mate_bg_changes_with_time (MateBG * bg)
Definition at line 3189 of file mate-bg.c.
References FALSE, NULL, and TRUE.
Referenced by mate_wp_item_get_frame_thumbnail(), and mate_wp_item_update_description().
mate_bg_create_frame_thumbnail()
GdkPixbuf * mate_bg_create_frame_thumbnail (MateBG * bg, MateDesktopThumbnailFactory * factory, GdkScreen * screen, int dest_width, int dest_height, int frame_num)
mate_bg_create_frame_thumbnail:
Creates a thumbnail for a certain frame, where 'frame' is somewhat vaguely defined as 'suitable point to show while single-stepping through the slideshow'.
Returns: (transfer full): the newly created thumbnail or or NULL if frame_num is out of bounds.
Definition at line 3220 of file mate-bg.c.
References FALSE, NULL, and TRUE.
Referenced by mate_wp_item_get_frame_thumbnail().
mate_bg_create_surface()
cairo_surface_t * mate_bg_create_surface (MateBG * bg, GdkWindow * window, int width, int height, gboolean root)
mate_bg_create_surface: @bg: MateBG @window: @width: @height: @root:
Create a surface that can be set as background for @window. If @root is TRUE, the surface created will be created by a temporary X server connection so that if someone calls XKillClient on it, it won't affect the application who created it.
Definition at line 1126 of file mate-bg.c.
References mate_bg_create_surface_scale().
mate_bg_create_surface_scale()
cairo_surface_t * mate_bg_create_surface_scale (MateBG * bg, GdkWindow * window, int width, int height, int scale, gboolean root)
mate_bg_create_surface_scale: @bg: MateBG @window: @width: @height: @scale: @root:
Create a scaled surface that can be set as background for @window. If @root is TRUE, the surface created will be created by a temporary X server connection so that if someone calls XKillClient on it, it won't affect the application who created it.
Definition at line 1155 of file mate-bg.c.
References FALSE, GDK_IS_X11_DISPLAY, MATE_BG_COLOR_SOLID, mate_bg_draw(), and NULL.
Referenced by mate_bg_create_surface().
mate_bg_create_thumbnail()
GdkPixbuf * mate_bg_create_thumbnail (MateBG * bg, MateDesktopThumbnailFactory * factory, GdkScreen * screen, int dest_width, int dest_height)
mate_bg_create_thumbnail:
Returns: (transfer full): a #GdkPixbuf showing the background as a thumbnail
Definition at line 1385 of file mate-bg.c.
References FALSE, and NULL.
Referenced by mate_wp_item_get_frame_thumbnail().
mate_bg_draw()
void mate_bg_draw (MateBG * bg, GdkPixbuf * dest, GdkScreen * screen, gboolean is_root)
Definition at line 1039 of file mate-bg.c.
References dest, and MATE_BG_PLACEMENT_SPANNED.
Referenced by mate_bg_create_surface_scale().
mate_bg_get_color()
void mate_bg_get_color (MateBG * bg, MateBGColorType * type, GdkRGBA * primary, GdkRGBA * secondary)
Definition at line 561 of file mate-bg.c.
References NULL.
Referenced by eel_bg_get_desktop_color().
mate_bg_get_draw_background()
gboolean mate_bg_get_draw_background (MateBG * bg)
Definition at line 592 of file mate-bg.c.
References FALSE, and NULL.
mate_bg_get_filename()
const gchar * mate_bg_get_filename (MateBG * bg)
Definition at line 600 of file mate-bg.c.
References NULL.
Referenced by eel_background_get_image_uri(), and eel_background_is_set().
mate_bg_get_image_size()
gboolean mate_bg_get_image_size (MateBG * bg, MateDesktopThumbnailFactory * factory, int best_width, int best_height, int * width, int * height)
Definition at line 1338 of file mate-bg.c.
References FALSE, NULL, and TRUE.
Referenced by mate_wp_item_get_frame_thumbnail().
mate_bg_get_placement()
MateBGPlacement mate_bg_get_placement (MateBG * bg)
Definition at line 553 of file mate-bg.c.
References NULL.
mate_bg_get_surface_from_root()
cairo_surface_t * mate_bg_get_surface_from_root (GdkScreen * screen)
mate_bg_get_surface_from_root: @screen: a #GdkScreen
This function queries the _XROOTPMAP_ID property from the root window associated with @screen to determine the current root window background surface and returns a copy of it. If the _XROOTPMAP_ID is not set, then a black surface is returned.
Return value: a #cairo_surface_t if successful or NULL
Definition at line 1425 of file mate-bg.c.
References data, and NULL.
Referenced by mate_bg_set_surface_as_root_with_crossfade().
mate_bg_get_type()
GType mate_bg_get_type (void)
References dest.
mate_bg_has_multiple_sizes()
gboolean mate_bg_has_multiple_sizes (MateBG * bg)
Definition at line 1061 of file mate-bg.c.
References FALSE, and NULL.
Referenced by mate_wp_item_update_description().
mate_bg_is_dark()
gboolean mate_bg_is_dark (MateBG * bg, int dest_width, int dest_height)
Definition at line 1221 of file mate-bg.c.
References b, FALSE, MATE_BG_COLOR_SOLID, and NULL.
Referenced by eel_background_is_dark().
mate_bg_load_from_gsettings()
void mate_bg_load_from_gsettings (MateBG * bg, GSettings * settings)
Definition at line 328 of file mate-bg.c.
References MATE_BG_KEY_COLOR_TYPE, MATE_BG_KEY_DRAW_BACKGROUND, MATE_BG_KEY_PICTURE_FILENAME, MATE_BG_KEY_PICTURE_PLACEMENT, MATE_BG_KEY_PRIMARY_COLOR, MATE_BG_KEY_SECONDARY_COLOR, mate_bg_set_color(), mate_bg_set_filename(), mate_bg_set_placement(), MATE_IS_BG, and NULL.
Referenced by eel_bg_load_from_gsettings(), mate_bg_load_from_preferences(), and mate_bg_load_from_system_gsettings().
mate_bg_load_from_preferences()
void mate_bg_load_from_preferences (MateBG * bg)
Definition at line 265 of file mate-bg.c.
References mate_bg_load_from_gsettings(), and MATE_BG_SCHEMA.
mate_bg_load_from_system_gsettings()
void mate_bg_load_from_system_gsettings (MateBG * bg, GSettings * settings, gboolean reset_apply)
Definition at line 296 of file mate-bg.c.
References mate_bg_load_from_gsettings(), MATE_IS_BG, and NULL.
Referenced by eel_bg_load_from_system_gsettings(), and mate_bg_load_from_system_preferences().
mate_bg_load_from_system_preferences()
void mate_bg_load_from_system_preferences (MateBG * bg)
Definition at line 279 of file mate-bg.c.
References FALSE, mate_bg_load_from_system_gsettings(), and MATE_BG_SCHEMA.
mate_bg_new()
MateBG * mate_bg_new (void)
Definition at line 512 of file mate-bg.c.
References MATE_TYPE_BG, and NULL.
Referenced by mate_wp_item_ensure_mate_bg().
mate_bg_save_to_gsettings()
void mate_bg_save_to_gsettings (MateBG * bg, GSettings * settings)
Definition at line 412 of file mate-bg.c.
References MATE_BG_KEY_COLOR_TYPE, MATE_BG_KEY_DRAW_BACKGROUND, MATE_BG_KEY_PICTURE_FILENAME, MATE_BG_KEY_PICTURE_PLACEMENT, MATE_BG_KEY_PRIMARY_COLOR, MATE_BG_KEY_SECONDARY_COLOR, and MATE_IS_BG.
Referenced by eel_bg_save_to_gsettings(), and mate_bg_save_to_preferences().
mate_bg_save_to_preferences()
void mate_bg_save_to_preferences (MateBG * bg)
Definition at line 402 of file mate-bg.c.
References mate_bg_save_to_gsettings(), and MATE_BG_SCHEMA.
mate_bg_set_color()
void mate_bg_set_color (MateBG * bg, MateBGColorType type, GdkRGBA * primary, GdkRGBA * secondary)
Definition at line 518 of file mate-bg.c.
References NULL.
Referenced by mate_bg_load_from_gsettings().
mate_bg_set_draw_background()
void mate_bg_set_draw_background (MateBG * bg, gboolean draw_background)
Definition at line 579 of file mate-bg.c.
References NULL.
mate_bg_set_filename()
void mate_bg_set_filename (MateBG * bg, const char * filename)
Definition at line 750 of file mate-bg.c.
References get_mtime(), and NULL.
Referenced by mate_bg_load_from_gsettings().
mate_bg_set_placement()
void mate_bg_set_placement (MateBG * bg, MateBGPlacement placement)
Definition at line 540 of file mate-bg.c.
References NULL.
Referenced by eel_background_set_dropped_image(), eel_bg_set_placement(), and mate_bg_load_from_gsettings().
mate_bg_set_surface_as_root()
void mate_bg_set_surface_as_root (GdkScreen * screen, cairo_surface_t * surface)
mate_bg_set_surface_as_root: @screen: the #GdkScreen to change root background on @surface: the #cairo_surface_t to set root background from. Must be an xlib surface backing a pixmap.
Set the root pixmap, and properties pointing to it. We do this atomically with a server grab to make sure that we won't leak the pixmap if somebody else it setting it at the same time. (This assumes that they follow the same conventions we do). @surface should come from a call to mate_bg_create_surface().
Definition at line 1607 of file mate-bg.c.
References NULL.
Referenced by mate_bg_set_surface_as_root_with_crossfade().
mate_bg_set_surface_as_root_with_crossfade()
MateBGCrossfade * mate_bg_set_surface_as_root_with_crossfade (GdkScreen * screen, cairo_surface_t * surface)
mate_bg_set_surface_as_root_with_crossfade: @screen: the #GdkScreen to change root background on @surface: the cairo xlib surface to set root background from
Set the root pixmap, and properties pointing to it. This function differs from mate_bg_set_surface_as_root() in that it adds a subtle crossfade animation from the current root pixmap to the new one.
Return value: (transfer full): a MateBGCrossfade object
Definition at line 1642 of file mate-bg.c.
References mate_bg_crossfade_new(), mate_bg_crossfade_set_end_surface(), mate_bg_crossfade_set_start_surface(), mate_bg_crossfade_start(), mate_bg_get_surface_from_root(), mate_bg_set_surface_as_root(), and NULL.