MATE Desktop Environment: matemixer-switch.c File Reference
matemixer-switch.c File Reference
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include "matemixer-enums.h"
#include "matemixer-enum-types.h"
#include "matemixer-switch.h"
#include "matemixer-switch-private.h"
#include "matemixer-switch-option.h"
Enumerations
enum {
PROP_0 , PROP_NAME , PROP_LABEL , PROP_ACTIVE_OPTION ,
N_PROPERTIES
}
Functions
const gchar * mate_mixer_switch_get_name (MateMixerSwitch *swtch)
const gchar * mate_mixer_switch_get_label (MateMixerSwitch *swtch)
: the name of an option
mate_mixer_switch_get_option: @swtch: a MateMixerSwitch
Gets the MateMixerSwitchOption with the given name.
Returns: a MateMixerSwitchOption or NULL if there is no such switch option.
MateMixerSwitchOption * mate_mixer_switch_get_option (MateMixerSwitch *swtch, const gchar *name)
MateMixerSwitchOption * mate_mixer_switch_get_active_option (MateMixerSwitch *swtch)
gboolean mate_mixer_switch_set_active_option (MateMixerSwitch *swtch, MateMixerSwitchOption *option)
const GList * mate_mixer_switch_list_options (MateMixerSwitch *swtch)
void _mate_mixer_switch_set_active_option (MateMixerSwitch *swtch, MateMixerSwitchOption *option)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_NAME
PROP_LABEL
PROP_ACTIVE_OPTION
N_PROPERTIES
Definition at line 40 of file matemixer-switch.c.
Function Documentation
_mate_mixer_switch_set_active_option()
void _mate_mixer_switch_set_active_option (MateMixerSwitch * swtch, MateMixerSwitchOption * option)
Definition at line 322 of file matemixer-switch.c.
References MATE_MIXER_IS_SWITCH, MATE_MIXER_IS_SWITCH_OPTION, NULL, option, _MateMixerSwitch::priv, and PROP_ACTIVE_OPTION.
Referenced by mate_mixer_switch_set_active_option(), oss_switch_load(), pulse_device_switch_set_active_profile(), and pulse_port_switch_set_active_port().
mate_mixer_switch_get_active_option()
MateMixerSwitchOption * mate_mixer_switch_get_active_option (MateMixerSwitch * swtch)
mate_mixer_switch_get_active_option: @swtch: a MateMixerSwitch
Gets the MateMixerSwitchOption which is currently active.
Returns: a MateMixerSwitchOption.
Definition at line 263 of file matemixer-switch.c.
References MATE_MIXER_IS_SWITCH, NULL, and _MateMixerSwitch::priv.
Referenced by mate_mixer_stream_toggle_get_state().
mate_mixer_switch_get_label()
const gchar * mate_mixer_switch_get_label (MateMixerSwitch * swtch)
mate_mixer_switch_get_label: @swtch: a MateMixerSwitch
Gets the label of the switch.
This is a potentially translated string that should be presented to users in the user interface.
Returns: the label of the switch option.
Definition at line 229 of file matemixer-switch.c.
References MATE_MIXER_IS_SWITCH, NULL, and _MateMixerSwitch::priv.
mate_mixer_switch_get_name()
const gchar * mate_mixer_switch_get_name (MateMixerSwitch * swtch)
mate_mixer_switch_get_name: @swtch: a MateMixerSwitch
Gets the name of the switch.
The name serves as a unique identifier and in most cases it is not in a user-readable form.
Returns: the name of the switch.
Definition at line 210 of file matemixer-switch.c.
References MATE_MIXER_IS_SWITCH, NULL, and _MateMixerSwitch::priv.
Referenced by alsa_stream_add_switch(), alsa_stream_add_toggle(), alsa_stream_remove_all(), alsa_stream_remove_elements(), and oss_switch_load().
mate_mixer_switch_get_option()
MateMixerSwitchOption * mate_mixer_switch_get_option (MateMixerSwitch * swtch, const gchar * name)
Definition at line 246 of file matemixer-switch.c.
References MATE_MIXER_IS_SWITCH, MATE_MIXER_SWITCH_GET_CLASS, name, and NULL.
mate_mixer_switch_list_options()
const GList * mate_mixer_switch_list_options (MateMixerSwitch * swtch)
mate_mixer_switch_list_options: @swtch: a MateMixerSwitch
Gets the list of switch options that belong to the switch.
The returned #GList is owned by the MateMixerSwitch and may be invalidated at any time.
Returns: a #GList of the switch options.
Definition at line 313 of file matemixer-switch.c.
References MATE_MIXER_IS_SWITCH, MATE_MIXER_SWITCH_GET_CLASS, and NULL.
mate_mixer_switch_set_active_option()
gboolean mate_mixer_switch_set_active_option (MateMixerSwitch * swtch, MateMixerSwitchOption * option)
mate_mixer_switch_set_active_option: @swtch: a MateMixerSwitch @option: the MateMixerSwitchOption to set as the active option
Changes the currently active switch option.
Returns: TRUE on success or FALSE on failure.
Definition at line 280 of file matemixer-switch.c.
References _mate_mixer_switch_set_active_option(), FALSE, MATE_MIXER_IS_SWITCH, MATE_MIXER_IS_SWITCH_OPTION, MATE_MIXER_SWITCH_GET_CLASS, NULL, option, _MateMixerSwitch::priv, _MateMixerSwitchClass::set_active_option, and TRUE.
Referenced by mate_mixer_stream_toggle_set_state(), and oss_switch_load().