MATE Desktop Environment: matemixer-context.h File Reference
matemixer-context.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer-enums.h>
#include <libmatemixer/matemixer-types.h>
Classes
struct _MateMixerContext
struct _MateMixerContextClass
Macros
#define MATE_MIXER_TYPE_CONTEXT (mate_mixer_context_get_type ())
#define MATE_MIXER_CONTEXT(o)
#define MATE_MIXER_IS_CONTEXT(o)
#define MATE_MIXER_CONTEXT_CLASS(k)
#define MATE_MIXER_IS_CONTEXT_CLASS(k)
#define MATE_MIXER_CONTEXT_GET_CLASS(o)
Typedefs
typedef struct _MateMixerContextClass MateMixerContextClass
typedef struct _MateMixerContextPrivate MateMixerContextPrivate
Functions
GType mate_mixer_context_get_type (void)
MateMixerContext * mate_mixer_context_new (void)
gboolean mate_mixer_context_set_backend_type (MateMixerContext *context, MateMixerBackendType backend_type)
gboolean mate_mixer_context_set_app_name (MateMixerContext *context, const gchar *app_name)
gboolean mate_mixer_context_set_app_id (MateMixerContext *context, const gchar *app_id)
gboolean mate_mixer_context_set_app_version (MateMixerContext *context, const gchar *app_version)
gboolean mate_mixer_context_set_app_icon (MateMixerContext *context, const gchar *app_icon)
gboolean mate_mixer_context_set_server_address (MateMixerContext *context, const gchar *address)
gboolean mate_mixer_context_open (MateMixerContext *context)
void mate_mixer_context_close (MateMixerContext *context)
MateMixerState mate_mixer_context_get_state (MateMixerContext *context)
MateMixerDevice * mate_mixer_context_get_device (MateMixerContext *context, const gchar *name)
MateMixerStream * mate_mixer_context_get_stream (MateMixerContext *context, const gchar *name)
MateMixerStoredControl * mate_mixer_context_get_stored_control (MateMixerContext *context, const gchar *name)
const GList * mate_mixer_context_list_devices (MateMixerContext *context)
const GList * mate_mixer_context_list_streams (MateMixerContext *context)
const GList * mate_mixer_context_list_stored_controls (MateMixerContext *context)
MateMixerStream * mate_mixer_context_get_default_input_stream (MateMixerContext *context)
gboolean mate_mixer_context_set_default_input_stream (MateMixerContext *context, MateMixerStream *stream)
MateMixerStream * mate_mixer_context_get_default_output_stream (MateMixerContext *context)
gboolean mate_mixer_context_set_default_output_stream (MateMixerContext *context, MateMixerStream *stream)
const gchar * mate_mixer_context_get_backend_name (MateMixerContext *context)
MateMixerBackendType mate_mixer_context_get_backend_type (MateMixerContext *context)
MateMixerBackendFlags mate_mixer_context_get_backend_flags (MateMixerContext *context)
Macro Definition Documentation
MATE_MIXER_CONTEXT
#define MATE_MIXER_CONTEXT (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), MATE_MIXER_TYPE_CONTEXT, MateMixerContext))
Definition at line 31 of file matemixer-context.h.
MATE_MIXER_CONTEXT_CLASS
#define MATE_MIXER_CONTEXT_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST ((k), MATE_MIXER_TYPE_CONTEXT, MateMixerContextClass))
Definition at line 35 of file matemixer-context.h.
MATE_MIXER_CONTEXT_GET_CLASS
#define MATE_MIXER_CONTEXT_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), MATE_MIXER_TYPE_CONTEXT, MateMixerContextClass))
Definition at line 39 of file matemixer-context.h.
MATE_MIXER_IS_CONTEXT
#define MATE_MIXER_IS_CONTEXT (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), MATE_MIXER_TYPE_CONTEXT))
Definition at line 33 of file matemixer-context.h.
Referenced by mate_mixer_context_close(), mate_mixer_context_get_backend_flags(), mate_mixer_context_get_backend_name(), mate_mixer_context_get_backend_type(), mate_mixer_context_get_default_input_stream(), mate_mixer_context_get_default_output_stream(), mate_mixer_context_get_device(), mate_mixer_context_get_state(), mate_mixer_context_get_stored_control(), mate_mixer_context_get_stream(), mate_mixer_context_list_devices(), mate_mixer_context_list_stored_controls(), mate_mixer_context_list_streams(), mate_mixer_context_open(), mate_mixer_context_set_app_icon(), mate_mixer_context_set_app_id(), mate_mixer_context_set_app_name(), mate_mixer_context_set_app_version(), mate_mixer_context_set_backend_type(), mate_mixer_context_set_default_input_stream(), mate_mixer_context_set_default_output_stream(), and mate_mixer_context_set_server_address().
MATE_MIXER_IS_CONTEXT_CLASS
#define MATE_MIXER_IS_CONTEXT_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), MATE_MIXER_TYPE_CONTEXT))
Definition at line 37 of file matemixer-context.h.
MATE_MIXER_TYPE_CONTEXT
#define MATE_MIXER_TYPE_CONTEXT (mate_mixer_context_get_type ())
Definition at line 29 of file matemixer-context.h.
Referenced by mate_mixer_context_new().
Typedef Documentation
MateMixerContextClass
typedef struct _MateMixerContextClass MateMixerContextClass
Definition at line 42 of file matemixer-context.h.
MateMixerContextPrivate
typedef struct _MateMixerContextPrivate MateMixerContextPrivate
Definition at line 43 of file matemixer-context.h.
Function Documentation
mate_mixer_context_close()
void mate_mixer_context_close (MateMixerContext * context)
mate_mixer_context_close: @context: a MateMixerContext
Closes an open connection to the sound system. The MateMixerContext:state will be set to MATE_MIXER_STATE_IDLE.
Definition at line 899 of file matemixer-context.c.
References MATE_MIXER_IS_CONTEXT, and MATE_MIXER_STATE_IDLE.
mate_mixer_context_get_backend_flags()
MateMixerBackendFlags mate_mixer_context_get_backend_flags (MateMixerContext * context)
mate_mixer_context_get_backend_flags: @context: a MateMixerContext
Gets the capability flags of the currently used sound system backend.
This function will not work until the @context is connected to a sound system.
Returns: the capability flags.
Definition at line 1202 of file matemixer-context.c.
References _MateMixerBackendInfo::backend_flags, FALSE, mate_mixer_backend_module_get_info(), MATE_MIXER_BACKEND_NO_FLAGS, and MATE_MIXER_IS_CONTEXT.
mate_mixer_context_get_backend_name()
const gchar * mate_mixer_context_get_backend_name (MateMixerContext * context)
mate_mixer_context_get_backend_name: @context: a MateMixerContext
Gets the name of the currently used sound system backend.
This function will not work until the @context is connected to a sound system.
Returns: the name or NULL on error.
Definition at line 1160 of file matemixer-context.c.
References FALSE, mate_mixer_backend_module_get_info(), MATE_MIXER_IS_CONTEXT, _MateMixerBackendInfo::name, and NULL.
mate_mixer_context_get_backend_type()
MateMixerBackendType mate_mixer_context_get_backend_type (MateMixerContext * context)
mate_mixer_context_get_backend_type: @context: a MateMixerContext
Gets the type of the currently used sound system backend.
This function will not work until the @context is connected to a sound system.
Returns: the backend type or MATE_MIXER_BACKEND_UNKNOWN on error.
Definition at line 1181 of file matemixer-context.c.
References _MateMixerBackendInfo::backend_type, FALSE, mate_mixer_backend_module_get_info(), MATE_MIXER_BACKEND_UNKNOWN, and MATE_MIXER_IS_CONTEXT.
mate_mixer_context_get_default_input_stream()
MateMixerStream * mate_mixer_context_get_default_input_stream (MateMixerContext * context)
mate_mixer_context_get_default_input_stream: @context: a MateMixerContext
Gets the default input stream. The returned stream is where sound input most likely comes from by default.
Returns: a MateMixerStream or NULL if there is no default input stream.
Definition at line 1068 of file matemixer-context.c.
References mate_mixer_backend_get_default_input_stream(), MATE_MIXER_IS_CONTEXT, MATE_MIXER_STATE_READY, and NULL.
mate_mixer_context_get_default_output_stream()
MateMixerStream * mate_mixer_context_get_default_output_stream (MateMixerContext * context)
mate_mixer_context_get_default_output_stream: @context: a MateMixerContext
Gets the default output stream. The returned stream is where sound output is most likely directed to by default.
Returns: a MateMixerStream or NULL if there are no output streams in the system.
Definition at line 1114 of file matemixer-context.c.
References mate_mixer_backend_get_default_output_stream(), MATE_MIXER_IS_CONTEXT, MATE_MIXER_STATE_READY, and NULL.
mate_mixer_context_get_device()
MateMixerDevice * mate_mixer_context_get_device (MateMixerContext * context, const gchar * name)
Definition at line 933 of file matemixer-context.c.
References MATE_MIXER_BACKEND, mate_mixer_backend_get_device(), MATE_MIXER_IS_CONTEXT, MATE_MIXER_STATE_READY, name, and NULL.
mate_mixer_context_get_state()
MateMixerState mate_mixer_context_get_state (MateMixerContext * context)
mate_mixer_context_get_state: @context: a MateMixerContext
Gets the state of the @context's connection to a sound system.
Returns: the connection state.
Definition at line 916 of file matemixer-context.c.
References MATE_MIXER_IS_CONTEXT, and MATE_MIXER_STATE_UNKNOWN.
Referenced by main(), and main().
mate_mixer_context_get_stored_control()
MateMixerStoredControl * mate_mixer_context_get_stored_control (MateMixerContext * context, const gchar * name)
Definition at line 975 of file matemixer-context.c.
References MATE_MIXER_BACKEND, mate_mixer_backend_get_stored_control(), MATE_MIXER_IS_CONTEXT, MATE_MIXER_STATE_READY, name, and NULL.
mate_mixer_context_get_stream()
MateMixerStream * mate_mixer_context_get_stream (MateMixerContext * context, const gchar * name)
Definition at line 954 of file matemixer-context.c.
References MATE_MIXER_BACKEND, mate_mixer_backend_get_stream(), MATE_MIXER_IS_CONTEXT, MATE_MIXER_STATE_READY, name, and NULL.
mate_mixer_context_get_type()
GType mate_mixer_context_get_type (void)
References name.
mate_mixer_context_list_devices()
const GList * mate_mixer_context_list_devices (MateMixerContext * context)
mate_mixer_context_list_devices: @context: a MateMixerContext
Gets a list of devices. Each item in the list is a MateMixerDevice representing a sound device in the system.
The returned #GList is owned by the library and may be invalidated at any time.
Returns: a #GList of all devices in the system or NULL if there are none or you are not connected to a sound system.
Definition at line 999 of file matemixer-context.c.
References MATE_MIXER_BACKEND, mate_mixer_backend_list_devices(), MATE_MIXER_IS_CONTEXT, MATE_MIXER_STATE_READY, and NULL.
mate_mixer_context_list_stored_controls()
const GList * mate_mixer_context_list_stored_controls (MateMixerContext * context)
mate_mixer_context_list_stored_controls: @context: a MateMixerContext
Gets a list of stored controls. Each item in the list is a MateMixerStoredControl.
The returned #GList is owned by the library and may be invalidated at any time.
Returns: a #GList of stored controls or NULL if there are none or you are not connected to a sound system.
Definition at line 1048 of file matemixer-context.c.
References MATE_MIXER_BACKEND, mate_mixer_backend_list_stored_controls(), MATE_MIXER_IS_CONTEXT, MATE_MIXER_STATE_READY, and NULL.
mate_mixer_context_list_streams()
const GList * mate_mixer_context_list_streams (MateMixerContext * context)
mate_mixer_context_list_streams: @context: a MateMixerContext
Gets a list of streams. Each item in the list is a MateMixerStream representing an input or output stream.
Note that the list will contain streams which belong to devices as well as streams which do not. If you are only interested in streams of a specific device, use mate_mixer_device_list_streams().
The returned #GList is owned by the library and may be invalidated at any time.
Returns: a #GList of all streams in the system or NULL if there are none or you are not connected to a sound system.
Definition at line 1026 of file matemixer-context.c.
References MATE_MIXER_BACKEND, mate_mixer_backend_list_streams(), MATE_MIXER_IS_CONTEXT, MATE_MIXER_STATE_READY, and NULL.
mate_mixer_context_new()
MateMixerContext * mate_mixer_context_new (void)
mate_mixer_context_new:
Creates a new MateMixerContext instance.
Returns: a new MateMixerContext instance or NULL if the library has not been initialized with mate_mixer_init().
Definition at line 556 of file matemixer-context.c.
References FALSE, mate_mixer_is_initialized(), MATE_MIXER_TYPE_CONTEXT, and NULL.
Referenced by main(), main(), and msd_media_keys_manager_start().
mate_mixer_context_open()
gboolean mate_mixer_context_open (MateMixerContext * context)
mate_mixer_context_open: @context: a MateMixerContext
Opens connection to a sound system. Unless the sound system backend type was chosen manually with mate_mixer_context_set_backend_type(), the library will find a working sound system automatically.
This function can complete the operation either synchronously or asynchronously and it may go through a series of connection MateMixerContext:state transitions.
If this function returns TRUE, the connection has either been established, or it hasn't been established yet and the result will be determined asynchronously. You can differentiate between these two possibilities by checking the connection MateMixerContext:state after this function returns.
The MATE_MIXER_STATE_READY state indicates that the connection has been established successfully.
The MATE_MIXER_STATE_CONNECTING state is reached when the connection has not been established yet and you should wait for the state to change to either MATE_MIXER_STATE_READY or MATE_MIXER_STATE_FAILED. It is required to have a main loop running to allow an asynchronous connection to proceed. The library will use the thread's default main context for this purpose.
If this function returns FALSE, it was not possible to connect to a sound system and the MateMixerContext:state will be set to MATE_MIXER_STATE_FAILED.
Returns: TRUE on success or if the result will be determined asynchronously, or FALSE on failure.
Definition at line 798 of file matemixer-context.c.
References _mate_mixer_list_modules(), FALSE, mate_mixer_backend_get_state(), mate_mixer_backend_module_get_info(), mate_mixer_backend_open(), mate_mixer_backend_set_app_info(), mate_mixer_backend_set_server_address(), MATE_MIXER_BACKEND_UNKNOWN, MATE_MIXER_IS_CONTEXT, MATE_MIXER_STATE_CONNECTING, MATE_MIXER_STATE_FAILED, MATE_MIXER_STATE_READY, NULL, and TRUE.
Referenced by gvc_applet_start(), gvc_status_icon_start(), main(), main(), and msd_media_keys_manager_start().
mate_mixer_context_set_app_icon()
gboolean mate_mixer_context_set_app_icon (MateMixerContext * context, const gchar * app_icon)
mate_mixer_context_set_app_icon: @context: a MateMixerContext @app_icon: the XDG icon name of your application, or NULL to unset
Sets the XDG icon name of your application. This information may be used when registering with the sound system.
This function must be used before opening a connection to a sound system with mate_mixer_context_open(), otherwise it will fail.
Returns: TRUE on success or FALSE on failure.
Definition at line 720 of file matemixer-context.c.
References _mate_mixer_app_info_set_icon(), FALSE, MATE_MIXER_IS_CONTEXT, MATE_MIXER_STATE_CONNECTING, MATE_MIXER_STATE_READY, PROP_APP_ICON, and TRUE.
Referenced by main(), and main().
mate_mixer_context_set_app_id()
gboolean mate_mixer_context_set_app_id (MateMixerContext * context, const gchar * app_id)
mate_mixer_context_set_app_id: @context: a MateMixerContext @app_id: the identifier of your application, or NULL to unset
Sets the identifier of your application (e.g. org.example.app). This information may be used when registering with the sound system.
This function must be used before opening a connection to a sound system with mate_mixer_context_open(), otherwise it will fail.
Returns: TRUE on success or FALSE on failure.
Definition at line 664 of file matemixer-context.c.
References _mate_mixer_app_info_set_id(), FALSE, MATE_MIXER_IS_CONTEXT, MATE_MIXER_STATE_CONNECTING, MATE_MIXER_STATE_READY, PROP_APP_ID, and TRUE.
Referenced by main(), and main().
mate_mixer_context_set_app_name()
gboolean mate_mixer_context_set_app_name (MateMixerContext * context, const gchar * app_name)
mate_mixer_context_set_app_name: @context: a MateMixerContext @app_name: the name of your application, or NULL to unset
Sets the name of your application. This information may be used when registering with the sound system.
This function must be used before opening a connection to a sound system with mate_mixer_context_open(), otherwise it will fail.
Returns: TRUE on success or FALSE on failure.
Definition at line 636 of file matemixer-context.c.
References _mate_mixer_app_info_set_name(), FALSE, MATE_MIXER_IS_CONTEXT, MATE_MIXER_STATE_CONNECTING, MATE_MIXER_STATE_READY, PROP_APP_NAME, and TRUE.
Referenced by main(), and main().
mate_mixer_context_set_app_version()
gboolean mate_mixer_context_set_app_version (MateMixerContext * context, const gchar * app_version)
mate_mixer_context_set_app_version: @context: a MateMixerContext @app_version: the version of your application, or NULL to unset
Sets the version of your application. This information may be used when registering with the sound system.
This function must be used before opening a connection to a sound system with mate_mixer_context_open(), otherwise it will fail.
Returns: TRUE on success or FALSE on failure.
Definition at line 692 of file matemixer-context.c.
References _mate_mixer_app_info_set_version(), FALSE, MATE_MIXER_IS_CONTEXT, MATE_MIXER_STATE_CONNECTING, MATE_MIXER_STATE_READY, PROP_APP_VERSION, and TRUE.
Referenced by main(), and main().
mate_mixer_context_set_backend_type()
gboolean mate_mixer_context_set_backend_type (MateMixerContext * context, MateMixerBackendType backend_type)
mate_mixer_context_set_backend_type: @context: a MateMixerContext @backend_type: the sound system backend to use
Makes the MateMixerContext use the given MateMixerBackendType.
By default the backend type is determined automatically. This function can be used to alter this behavior and make the @context use the selected sound system.
Setting the backend type only succeeds if the selected backend module is available in the target system.
If you have used this function before and want restore the default automatic backend type discovery, set the backend type to MATE_MIXER_BACKEND_UNKNOWN.
This function must be used before opening a connection to a sound system with mate_mixer_context_open(), otherwise it will fail.
Returns: TRUE on success or FALSE on failure.
Definition at line 589 of file matemixer-context.c.
References _mate_mixer_list_modules(), FALSE, mate_mixer_backend_module_get_info(), MATE_MIXER_BACKEND_UNKNOWN, MATE_MIXER_IS_CONTEXT, MATE_MIXER_STATE_CONNECTING, MATE_MIXER_STATE_READY, NULL, and TRUE.
Referenced by main(), and main().
mate_mixer_context_set_default_input_stream()
gboolean mate_mixer_context_set_default_input_stream (MateMixerContext * context, MateMixerStream * stream)
mate_mixer_context_set_default_input_stream: @context: a MateMixerContext @stream: a MateMixerStream to set as the default input stream
Changes the default input stream. The given @stream must be an input stream.
Changing the default input stream may not be supported by the sound system. Use mate_mixer_context_get_backend_flags() to find out.
Returns: TRUE on success or FALSE on failure.
Definition at line 1091 of file matemixer-context.c.
References FALSE, mate_mixer_backend_set_default_input_stream(), MATE_MIXER_IS_CONTEXT, MATE_MIXER_IS_STREAM, and MATE_MIXER_STATE_READY.
mate_mixer_context_set_default_output_stream()
gboolean mate_mixer_context_set_default_output_stream (MateMixerContext * context, MateMixerStream * stream)
mate_mixer_context_set_default_output_stream: @context: a MateMixerContext @stream: a MateMixerStream to set as the default output stream
Changes the default output stream. The given @stream must be an output stream.
Changing the default output stream may not be supported by the sound system. Use mate_mixer_context_get_backend_flags() to find out.
Returns: TRUE on success or FALSE on failure.
Definition at line 1137 of file matemixer-context.c.
References FALSE, mate_mixer_backend_set_default_output_stream(), MATE_MIXER_IS_CONTEXT, MATE_MIXER_IS_STREAM, and MATE_MIXER_STATE_READY.
mate_mixer_context_set_server_address()
gboolean mate_mixer_context_set_server_address (MateMixerContext * context, const gchar * address)
mate_mixer_context_set_server_address: @context: a MateMixerContext @address: the address of the sound server to connect to or NULL
Sets the address of the sound server. This feature is only supported in the PulseAudio backend. If the address is not set, the default PulseAudio sound server will be used, which is normally the local daemon.
This function must be used before opening a connection to a sound system with mate_mixer_context_open(), otherwise it will fail.
Returns: TRUE on success or FALSE on failure.
Definition at line 749 of file matemixer-context.c.
References FALSE, MATE_MIXER_IS_CONTEXT, MATE_MIXER_STATE_CONNECTING, MATE_MIXER_STATE_READY, PROP_SERVER_ADDRESS, and TRUE.
Referenced by main().