MATE Desktop Environment: util.h File Reference
util.h File Reference
#include <glib.h>
#include <gtk/gtk.h>
#include <time.h>
#include <string>
Namespaces
namespace procman
Macros
#define LOGIND_RUNNING()
#define procman_debug(FMT, ...)
Functions
GtkWidget * procman_make_label_for_mmaps_or_ofiles (const char *format, const char *process_name, unsigned pid)
gboolean load_symbols (const char *module,...)
gchar * procman_format_date_for_display (time_t time_raw)
const char * format_process_state (guint state)
void procman_debug_real (const char *file, int line, const char *func, const char *format,...)
string make_string (char *c_str)
gchar * procman::format_duration_for_display (unsigned centiseconds)
void procman::memory_size_cell_data_func (GtkTreeViewColumn *col, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
void procman::io_rate_cell_data_func (GtkTreeViewColumn *col, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
void procman::memory_size_na_cell_data_func (GtkTreeViewColumn *col, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
void procman::storage_size_cell_data_func (GtkTreeViewColumn *col, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
void procman::storage_size_na_cell_data_func (GtkTreeViewColumn *col, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
void procman::duration_cell_data_func (GtkTreeViewColumn *col, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
void procman::time_cell_data_func (GtkTreeViewColumn *col, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
void procman::status_cell_data_func (GtkTreeViewColumn *col, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
void procman::priority_cell_data_func (GtkTreeViewColumn *col, GtkCellRenderer *renderer, GtkTreeModel *model, GtkTreeIter *iter, gpointer user_data)
gint procman::priority_compare_func (GtkTreeModel *model, GtkTreeIter *first, GtkTreeIter *second, gpointer user_data)
gint procman::number_compare_func (GtkTreeModel *model, GtkTreeIter *first, GtkTreeIter *second, gpointer user_data)
template<typename T>
void procman::poison (T &t, char c)
template<typename T>
void procman::tree_store_update (GtkTreeModel *model, GtkTreeIter *iter, int column, const T &new_value)
template<typename T>
void procman::tree_store_update (GtkTreeModel *model, GtkTreeIter *iter, int column, T *new_value)
template<>
void procman::tree_store_update< const char > (GtkTreeModel *model, GtkTreeIter *iter, int column, const char *new_value)
template<>
void procman::tree_store_update< char > (GtkTreeModel *model, GtkTreeIter *iter, int column, char *new_value)
gchar * procman::get_nice_level (gint nice)
Macro Definition Documentation
LOGIND_RUNNING
#define LOGIND_RUNNING ()
Value:
(access("/run/systemd/seats/", F_OK) >= 0)
Definition at line 14 of file mate-system-monitor/src/util.h.
procman_debug
#define procman_debug (FMT, ...)
Value:
procman_debug_real(__FILE__, __LINE__, __func__, FMT, ##__VA_ARGS__)
Definition at line 34 of file mate-system-monitor/src/util.h.
Referenced by make_string().
Function Documentation
format_process_state()
const char * format_process_state (guint state)
References format_process_state().
Referenced by format_process_state().
load_symbols()
gboolean load_symbols (const char * module, ...)
make_string()
string make_string (char * c_str) inline
Definition at line 36 of file mate-system-monitor/src/util.h.
References procman_debug.
procman_debug_real()
void procman_debug_real (const char * file, int line, const char * func, const char * format, ...)
References procman_debug_real().
Referenced by procman_debug_real().
procman_format_date_for_display()
gchar * procman_format_date_for_display (time_t time_raw)
References procman_format_date_for_display().
Referenced by procman_format_date_for_display().
procman_make_label_for_mmaps_or_ofiles()
GtkWidget * procman_make_label_for_mmaps_or_ofiles (const char * format, const char * process_name, unsigned pid)