MATE Desktop Environment: mate-theme-apply.c File Reference
mate-theme-apply.c File Reference
#include <string.h>
#include <gio/gio.h>
#include <libmate-desktop/mate-gsettings.h>
#include "mate-theme-apply.h"
#include "gtkrc-utils.h"
#include <gdk/gdkx.h>
Macros
#define INTERFACE_SCHEMA "org.mate.interface"
#define INTERFACE_GNOME_SCHEMA "org.gnome.desktop.interface"
#define GTK_THEME_KEY "gtk-theme"
#define COLOR_SCHEME_KEY "gtk-color-scheme"
#define ICON_THEME_KEY "icon-theme"
#define MARCO_SCHEMA "org.mate.Marco.general"
#define MARCO_THEME_KEY "theme"
#define MOUSE_SCHEMA "org.mate.peripherals-mouse"
#define CURSOR_THEME_KEY "cursor-theme"
#define CURSOR_SIZE_KEY "cursor-size"
#define NOTIFICATION_SCHEMA "org.mate.NotificationDaemon"
#define NOTIFICATION_THEME_KEY "theme"
#define compare(x, y)
Functions
void mate_meta_theme_set (MateThemeMetaInfo *meta_theme_info)
Macro Definition Documentation
COLOR_SCHEME_KEY
#define COLOR_SCHEME_KEY "gtk-color-scheme"
Definition at line 34 of file mate-theme-apply.c.
compare
#define compare (x, y)
Value:
(!x && y) || (x && !y) || (x && y && strcmp (x, y))
Definition at line 47 of file mate-theme-apply.c.
Referenced by mate_meta_theme_set(), na_object_id_sort_alpha_asc(), and panel_g_slist_make_unique().
CURSOR_SIZE_KEY
#define CURSOR_SIZE_KEY "cursor-size"
Definition at line 42 of file mate-theme-apply.c.
CURSOR_THEME_KEY
#define CURSOR_THEME_KEY "cursor-theme"
Definition at line 41 of file mate-theme-apply.c.
GTK_THEME_KEY
#define GTK_THEME_KEY "gtk-theme"
Definition at line 33 of file mate-theme-apply.c.
ICON_THEME_KEY
#define ICON_THEME_KEY "icon-theme"
Definition at line 35 of file mate-theme-apply.c.
INTERFACE_GNOME_SCHEMA
#define INTERFACE_GNOME_SCHEMA "org.gnome.desktop.interface"
Definition at line 32 of file mate-theme-apply.c.
INTERFACE_SCHEMA
#define INTERFACE_SCHEMA "org.mate.interface"
Definition at line 31 of file mate-theme-apply.c.
MARCO_SCHEMA
#define MARCO_SCHEMA "org.mate.Marco.general"
Definition at line 37 of file mate-theme-apply.c.
MARCO_THEME_KEY
#define MARCO_THEME_KEY "theme"
Definition at line 38 of file mate-theme-apply.c.
MOUSE_SCHEMA
#define MOUSE_SCHEMA "org.mate.peripherals-mouse"
Definition at line 40 of file mate-theme-apply.c.
NOTIFICATION_SCHEMA
#define NOTIFICATION_SCHEMA "org.mate.NotificationDaemon"
Definition at line 44 of file mate-theme-apply.c.
NOTIFICATION_THEME_KEY
#define NOTIFICATION_THEME_KEY "theme"
Definition at line 45 of file mate-theme-apply.c.
Function Documentation
mate_meta_theme_set()
void mate_meta_theme_set (MateThemeMetaInfo * meta_theme_info)
Definition at line 50 of file mate-theme-apply.c.
References COLOR_SCHEME_KEY, compare, _MateThemeMetaInfo::cursor_size, CURSOR_SIZE_KEY, CURSOR_THEME_KEY, _MateThemeMetaInfo::cursor_theme_name, GDK_IS_X11_DISPLAY, _MateThemeMetaInfo::gtk_color_scheme, GTK_THEME_KEY, _MateThemeMetaInfo::gtk_theme_name, gtkrc_get_color_scheme_for_theme(), ICON_THEME_KEY, _MateThemeMetaInfo::icon_theme_name, INTERFACE_GNOME_SCHEMA, INTERFACE_SCHEMA, MARCO_SCHEMA, MARCO_THEME_KEY, _MateThemeMetaInfo::marco_theme_name, mate_gsettings_schema_exists(), mate_theme_color_scheme_equal(), MOUSE_SCHEMA, NOTIFICATION_SCHEMA, NOTIFICATION_THEME_KEY, _MateThemeMetaInfo::notification_theme_name, NULL, and TRUE.