MATE Desktop Environment: mate-keyboard-properties-xkb.h File Reference
mate-keyboard-properties-xkb.h File Reference
#include <glib.h>
#include <gio/gio.h>
#include "libmatekbd/matekbd-keyboard-config.h"
Macros
#define CWID(s)
Functions
void setup_xkb_tabs (GtkBuilder *dialog)
void xkb_layouts_fill_selected_tree (GtkBuilder *dialog)
void xkb_layouts_register_buttons_handlers (GtkBuilder *dialog)
void xkb_layouts_register_gsettings_listener (GtkBuilder *dialog)
void xkb_options_register_gsettings_listener (GtkBuilder *dialog)
void xkb_layouts_prepare_selected_tree (GtkBuilder *dialog)
void xkb_options_load_options (GtkBuilder *dialog)
void xkb_options_popup_dialog (GtkBuilder *dialog)
void clear_xkb_elements_list (GSList *list)
char * xci_desc_to_utf8 (XklConfigItem *ci)
gchar * xkb_layout_description_utf8 (const gchar *visible)
void enable_disable_restoring (GtkBuilder *dialog)
void preview_toggled (GtkBuilder *dialog, GtkWidget *button)
void choose_model (GtkBuilder *dialog)
void xkb_layout_choose (GtkBuilder *dialog)
GSList * xkb_layouts_get_selected_list (void)
GSList * xkb_options_get_selected_list (void)
void xkb_layouts_set_selected_list (GSList *list)
void xkb_options_set_selected_list (GSList *list)
GtkWidget * xkb_layout_preview_create_widget (GtkBuilder *chooser_dialog)
void xkb_layout_preview_update (GtkBuilder *chooser_dialog)
void xkb_layout_preview_set_drawing_layout (GtkWidget *kbdraw, const gchar *id)
gchar * xkb_layout_chooser_get_selected_id (GtkBuilder *chooser_dialog)
void xkb_save_default_group (gint group_no)
gint xkb_get_default_group (void)
Variables
XklEngine * engine
XklConfigRegistry * config_registry
GSettings * xkb_kbd_settings
GSettings * xkb_general_settings
MatekbdKeyboardConfig initial_config
Macro Definition Documentation
CWID
#define CWID (s)
Value:
GTK_WIDGET (gtk_builder_get_object (chooser_dialog, s))
Definition at line 34 of file mate-keyboard-properties-xkb.h.
Referenced by choose_model(), xkb_layout_choose(), xkb_layout_chooser_get_selected_id(), xkb_layout_preview_update(), and xkb_options_popup_dialog().
Function Documentation
choose_model()
void choose_model (GtkBuilder * dialog) extern
Definition at line 311 of file mate-keyboard-properties-xkbmc.c.
References CWID, NULL, WID, and xkb_kbd_settings.
Referenced by setup_xkb_tabs().
clear_xkb_elements_list()
void clear_xkb_elements_list (GSList * list) extern
Definition at line 51 of file mate-keyboard-properties-xkblt.c.
References NULL.
Referenced by xkb_layouts_fill_selected_tree().
enable_disable_restoring()
void enable_disable_restoring (GtkBuilder * dialog) extern
Definition at line 265 of file mate-keyboard-properties-xkb.c.
References engine, initial_config, matekbd_keyboard_config_equals(), matekbd_keyboard_config_init(), matekbd_keyboard_config_load_from_gsettings(), matekbd_keyboard_config_term(), NULL, and WID.
Referenced by setup_xkb_tabs().
preview_toggled()
void preview_toggled (GtkBuilder * dialog, GtkWidget * button) extern
setup_xkb_tabs()
void setup_xkb_tabs (GtkBuilder * dialog) extern
Definition at line 176 of file mate-keyboard-properties-xkb.c.
References choose_model(), config_registry, desktop_config, enable_disable_restoring(), engine, initial_config, matekbd_desktop_config_init(), matekbd_desktop_config_load_from_gsettings(), matekbd_keyboard_config_init(), matekbd_keyboard_config_load_from_x_initial(), NULL, WID, XKB_GENERAL_SCHEMA, xkb_general_settings, xkb_get_default_group(), XKB_KBD_SCHEMA, xkb_kbd_settings, xkb_layouts_fill_selected_tree(), xkb_layouts_prepare_selected_tree(), xkb_layouts_register_buttons_handlers(), xkb_layouts_register_gsettings_listener(), xkb_options_popup_dialog(), and xkb_options_register_gsettings_listener().
xci_desc_to_utf8()
char * xci_desc_to_utf8 (XklConfigItem * ci) extern
Definition at line 52 of file mate-keyboard-properties-xkb.c.
xkb_get_default_group()
gint xkb_get_default_group (void) extern
Definition at line 114 of file mate-keyboard-properties-xkblt.c.
References xkb_general_settings.
Referenced by setup_xkb_tabs(), and xkb_save_default_group().
xkb_layout_choose()
void xkb_layout_choose (GtkBuilder * dialog) extern
Definition at line 430 of file mate-keyboard-properties-xkbltadd.c.
References CWID, engine, FALSE, matekbd_preview_load_position(), NULL, TRUE, WID, xkb_layout_preview_create_widget(), and xkb_layout_preview_update().
xkb_layout_chooser_get_selected_id()
gchar * xkb_layout_chooser_get_selected_id (GtkBuilder * chooser_dialog) extern
Definition at line 531 of file mate-keyboard-properties-xkbltadd.c.
References COMBO_BOX_MODEL_COL_XKB_ID, CWID, and NULL.
Referenced by xkb_layout_preview_update().
xkb_layout_description_utf8()
gchar * xkb_layout_description_utf8 (const gchar * visible) extern
Definition at line 281 of file mate-keyboard-properties-xkblt.c.
References config_registry, matekbd_keyboard_config_format_full_layout(), and matekbd_keyboard_config_get_descriptions().
Referenced by xkb_layouts_fill_selected_tree().
xkb_layout_preview_create_widget()
GtkWidget * xkb_layout_preview_create_widget (GtkBuilder * chooser_dialog) extern
Definition at line 58 of file mate-keyboard-properties-xkbpv.c.
References MATEKBD_KEYBOARD_DRAWING, matekbd_keyboard_drawing_new(), and matekbd_keyboard_drawing_set_groups_levels().
Referenced by xkb_layout_choose().
xkb_layout_preview_set_drawing_layout()
void xkb_layout_preview_set_drawing_layout (GtkWidget * kbdraw, const gchar * id) extern
Definition at line 81 of file mate-keyboard-properties-xkbpv.c.
References data, engine, matekbd_keyboard_config_split_items(), MATEKBD_KEYBOARD_DRAWING, matekbd_keyboard_drawing_set_keyboard(), NULL, xkl_xkb_config_native_cleanup(), and xkl_xkb_config_native_prepare().
Referenced by xkb_layout_preview_update().
xkb_layout_preview_update()
void xkb_layout_preview_update (GtkBuilder * chooser_dialog) extern
Definition at line 68 of file mate-keyboard-properties-xkbpv.c.
References CWID, xkb_layout_chooser_get_selected_id(), and xkb_layout_preview_set_drawing_layout().
Referenced by xkb_layout_choose().
xkb_layouts_fill_selected_tree()
void xkb_layouts_fill_selected_tree (GtkBuilder * dialog) extern
Definition at line 291 of file mate-keyboard-properties-xkblt.c.
References clear_xkb_elements_list(), FALSE, NULL, SEL_LAYOUT_TREE_COL_DESCRIPTION, SEL_LAYOUT_TREE_COL_ENABLED, SEL_LAYOUT_TREE_COL_ID, TRUE, WID, xkb_layout_description_utf8(), and xkb_layouts_get_selected_list().
Referenced by setup_xkb_tabs().
xkb_layouts_get_selected_list()
GSList * xkb_layouts_get_selected_list (void) extern
Definition at line 88 of file mate-keyboard-properties-xkblt.c.
References initial_config, NULL, and xkb_kbd_settings.
Referenced by xkb_layouts_fill_selected_tree().
xkb_layouts_prepare_selected_tree()
void xkb_layouts_prepare_selected_tree (GtkBuilder * dialog) extern
Definition at line 225 of file mate-keyboard-properties-xkblt.c.
References _, engine, NULL, SEL_LAYOUT_TREE_COL_DESCRIPTION, SEL_LAYOUT_TREE_COL_ENABLED, TRUE, and WID.
Referenced by setup_xkb_tabs().
xkb_layouts_register_buttons_handlers()
void xkb_layouts_register_buttons_handlers (GtkBuilder * dialog) extern
Definition at line 437 of file mate-keyboard-properties-xkblt.c.
Referenced by setup_xkb_tabs().
xkb_layouts_register_gsettings_listener()
void xkb_layouts_register_gsettings_listener (GtkBuilder * dialog) extern
Definition at line 464 of file mate-keyboard-properties-xkblt.c.
References xkb_kbd_settings.
Referenced by setup_xkb_tabs().
xkb_layouts_set_selected_list()
void xkb_layouts_set_selected_list (GSList * list) extern
Definition at line 296 of file mate-keyboard-properties-xkb.c.
References XKB_KBD_SCHEMA.
xkb_options_get_selected_list()
GSList * xkb_options_get_selected_list (void) extern
Definition at line 50 of file mate-keyboard-properties-xkbot.c.
References initial_config, NULL, and xkb_kbd_settings.
xkb_options_load_options()
void xkb_options_load_options (GtkBuilder * dialog) extern
Definition at line 386 of file mate-keyboard-properties-xkbot.c.
References config_registry, EXPANDERS_PROP, FALSE, NULL, and WID.
Referenced by xkb_options_popup_dialog().
xkb_options_popup_dialog()
void xkb_options_popup_dialog (GtkBuilder * dialog) extern
Definition at line 446 of file mate-keyboard-properties-xkbot.c.
References CWID, NULL, WID, and xkb_options_load_options().
Referenced by setup_xkb_tabs().
xkb_options_register_gsettings_listener()
void xkb_options_register_gsettings_listener (GtkBuilder * dialog) extern
Definition at line 513 of file mate-keyboard-properties-xkbot.c.
References xkb_kbd_settings.
Referenced by setup_xkb_tabs().
xkb_options_set_selected_list()
void xkb_options_set_selected_list (GSList * list) extern
Definition at line 302 of file mate-keyboard-properties-xkb.c.
References XKB_KBD_SCHEMA.
xkb_save_default_group()
void xkb_save_default_group (gint group_no) extern
Definition at line 120 of file mate-keyboard-properties-xkblt.c.
References xkb_general_settings, and xkb_get_default_group().
Variable Documentation
config_registry
XklConfigRegistry* config_registry extern
Definition at line 43 of file mate-keyboard-properties-xkb.c.
Referenced by matekbd_keyboard_config_dump_settings(), matekbd_keyboard_config_get_descriptions(), matekbd_keyboard_config_get_lv_descriptions(), setup_xkb_tabs(), xkb_layout_description_utf8(), and xkb_options_load_options().
engine
XklEngine* engine extern
Definition at line 42 of file mate-keyboard-properties-xkb.c.
Referenced by caja_search_engine_beagle_new(), caja_search_engine_enabled(), caja_search_engine_error(), caja_search_engine_finished(), caja_search_engine_hits_added(), caja_search_engine_hits_subtracted(), caja_search_engine_is_indexed(), caja_search_engine_new(), caja_search_engine_set_query(), caja_search_engine_set_show_hidden_files(), caja_search_engine_simple_new(), caja_search_engine_start(), caja_search_engine_stop(), caja_search_engine_tracker_new(), enable_disable_restoring(), eom_plugin_engine_new(), G_DEFINE_TYPE(), gpm_engine_get_devices(), gpm_engine_get_icon(), gpm_engine_get_primary_device(), gpm_engine_get_summary(), gpm_engine_get_type(), gs_theme_engine_get_type(), gs_theme_engine_get_window(), gs_theme_engine_get_window_size(), gtk_theme_info_missing_engine(), main(), main(), matekbd_desktop_config_init(), matekbd_indicator_config_init(), matekbd_indicator_extract_layout_name(), matekbd_keyboard_config_init(), matekbd_keyboard_drawing_new_dialog(), setup_xkb_tabs(), theme_add_notification_action(), theme_clear_notification_actions(), theme_create_notification(), theme_destroy_notification(), theme_get_always_stack(), theme_hide_notification(), theme_move_notification(), theme_notification_tick(), theme_set_notification_arrow(), theme_set_notification_hints(), theme_set_notification_icon(), theme_set_notification_text(), theme_set_notification_timeout(), theme_show_notification(), xkb_layout_choose(), xkb_layout_preview_set_drawing_layout(), xkb_layouts_prepare_selected_tree(), xkl_xkb_config_native_cleanup(), and xkl_xkb_config_native_prepare().
initial_config
MatekbdKeyboardConfig initial_config extern
Definition at line 45 of file mate-keyboard-properties-xkb.c.
Referenced by enable_disable_restoring(), setup_xkb_tabs(), xkb_layouts_get_selected_list(), and xkb_options_get_selected_list().
xkb_general_settings
GSettings* xkb_general_settings extern
Definition at line 48 of file mate-keyboard-properties-xkb.c.
Referenced by setup_xkb_tabs(), xkb_get_default_group(), and xkb_save_default_group().
xkb_kbd_settings
GSettings* xkb_kbd_settings extern
Definition at line 49 of file mate-keyboard-properties-xkb.c.
Referenced by choose_model(), setup_xkb_tabs(), xkb_layouts_get_selected_list(), xkb_layouts_register_gsettings_listener(), xkb_options_get_selected_list(), and xkb_options_register_gsettings_listener().