MATE Desktop Environment: mate-keyboard-properties-xkbltadd.c File Reference
mate-keyboard-properties-xkbltadd.c File Reference
#include <string.h>
#include <libmatekbd/matekbd-keyboard-drawing.h>
#include <libmatekbd/matekbd-util.h>
#include "capplet-util.h"
#include "mate-keyboard-properties-xkb.h"
Typedefs
typedef void(* LayoutIterFunc) (XklConfigRegistry *config, ConfigItemProcessFunc func, gpointer data)
Enumerations
enum { COMBO_BOX_MODEL_COL_SORT , COMBO_BOX_MODEL_COL_VISIBLE , COMBO_BOX_MODEL_COL_XKB_ID , COMBO_BOX_MODEL_COL_REAL_ID }
Functions
void xkb_layout_choose (GtkBuilder *dialog)
gchar * xkb_layout_chooser_get_selected_id (GtkBuilder *chooser_dialog)
Typedef Documentation
LayoutIterFunc
typedef void(* LayoutIterFunc) (XklConfigRegistry *config, ConfigItemProcessFunc func, gpointer data)
Definition at line 43 of file mate-keyboard-properties-xkbltadd.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COMBO_BOX_MODEL_COL_SORT
COMBO_BOX_MODEL_COL_VISIBLE
COMBO_BOX_MODEL_COL_XKB_ID
COMBO_BOX_MODEL_COL_REAL_ID
Definition at line 36 of file mate-keyboard-properties-xkbltadd.c.
Function Documentation
xkb_layout_choose()
void xkb_layout_choose (GtkBuilder * dialog)
Definition at line 430 of file mate-keyboard-properties-xkbltadd.c.
References CWID, engine, FALSE, matekbd_preview_load_position(), NULL, TRUE, WID, xkb_layout_preview_create_widget(), and xkb_layout_preview_update().
xkb_layout_chooser_get_selected_id()
gchar * xkb_layout_chooser_get_selected_id (GtkBuilder * chooser_dialog)
Definition at line 531 of file mate-keyboard-properties-xkbltadd.c.
References COMBO_BOX_MODEL_COL_XKB_ID, CWID, and NULL.
Referenced by xkb_layout_preview_update().