MATE Desktop Environment: matekbd-status.h File Reference
matekbd-status.h File Reference
#include <gtk/gtk.h>
#include <libxklavier/xklavier.h>
Classes
struct _MatekbdStatus
struct _MatekbdStatusClass
Macros
#define MATEKBD_TYPE_STATUS (matekbd_status_get_type ())
#define MATEKBD_STATUS(obj)
#define MATEKBD_STATUS_CLASS(obj)
#define MATEKBD_IS_STATUS(obj)
#define MATEKBD_IS_STATUS_CLASS(obj)
#define MATEKBD_STATUS_GET_CLASS(obj)
Typedefs
typedef struct _MatekbdStatus MatekbdStatus
typedef struct _MatekbdStatusPrivate MatekbdStatusPrivate
typedef struct _MatekbdStatusClass MatekbdStatusClass
Functions
GType matekbd_status_get_type (void)
GtkStatusIcon * matekbd_status_new (void)
void matekbd_status_reinit_ui (MatekbdStatus *gki)
void matekbd_status_set_angle (MatekbdStatus *gki, gdouble angle)
XklEngine * matekbd_status_get_xkl_engine (void)
gchar ** matekbd_status_get_group_names (void)
gchar * matekbd_status_get_image_filename (guint group)
void matekbd_status_set_tooltips_format (const gchar str[])
Macro Definition Documentation
MATEKBD_IS_STATUS
#define MATEKBD_IS_STATUS (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATEKBD_TYPE_STATUS))
Definition at line 38 of file matekbd-status.h.
MATEKBD_IS_STATUS_CLASS
#define MATEKBD_IS_STATUS_CLASS (obj)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((obj), MATEKBD_TYPE_STATUS))
Definition at line 39 of file matekbd-status.h.
MATEKBD_STATUS
#define MATEKBD_STATUS (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), MATEKBD_TYPE_STATUS, MatekbdStatus))
Definition at line 36 of file matekbd-status.h.
MATEKBD_STATUS_CLASS
#define MATEKBD_STATUS_CLASS (obj)
Value:
(G_TYPE_CHECK_CLASS_CAST ((obj), MATEKBD_TYPE_STATUS,  MatekbdStatusClass))
Definition at line 37 of file matekbd-status.h.
MATEKBD_STATUS_GET_CLASS
#define MATEKBD_STATUS_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), MATEKBD_TYPE_STATUS, MatekbdStatusClass))
Definition at line 40 of file matekbd-status.h.
MATEKBD_TYPE_STATUS
#define MATEKBD_TYPE_STATUS (matekbd_status_get_type ())
Definition at line 35 of file matekbd-status.h.
Typedef Documentation
MatekbdStatus
typedef struct _MatekbdStatus MatekbdStatus
Definition at line 31 of file matekbd-status.h.
MatekbdStatusClass
typedef struct _MatekbdStatusClass MatekbdStatusClass
Definition at line 33 of file matekbd-status.h.
MatekbdStatusPrivate
typedef struct _MatekbdStatusPrivate MatekbdStatusPrivate
Definition at line 32 of file matekbd-status.h.
Function Documentation
matekbd_status_get_group_names()
gchar ** matekbd_status_get_group_names (void) extern
matekbd_status_get_group_names:
Returns: (transfer none) (array zero-terminated=1): List of group names
Definition at line 858 of file matekbd-status.c.
matekbd_status_get_image_filename()
gchar * matekbd_status_get_image_filename (guint group) extern
Definition at line 864 of file matekbd-status.c.
References matekbd_indicator_config_get_images_file(), and NULL.
matekbd_status_get_type()
GType matekbd_status_get_type (void) extern
Referenced by matekbd_status_new().
matekbd_status_get_xkl_engine()
XklEngine * matekbd_status_get_xkl_engine (void) extern
matekbd_status_get_xkl_engine:
Returns: (transfer none): The engine shared by all MatekbdStatus objects
Definition at line 847 of file matekbd-status.c.
matekbd_status_new()
GtkStatusIcon * matekbd_status_new (void) extern
Definition at line 835 of file matekbd-status.c.
References matekbd_status_get_type(), and NULL.
Referenced by main().
matekbd_status_reinit_ui()
void matekbd_status_reinit_ui (MatekbdStatus * gki) extern
Definition at line 405 of file matekbd-status.c.
matekbd_status_set_angle()
void matekbd_status_set_angle (MatekbdStatus * gki, gdouble angle) extern
Definition at line 874 of file matekbd-status.c.
References _MatekbdStatus::priv.
matekbd_status_set_tooltips_format()
void matekbd_status_set_tooltips_format (const gchar str[]) extern