MATE Desktop Environment: mate-ui-dialogs.h File Reference
mate-ui-dialogs.h File Reference
#include <gtk/gtk.h>
Classes
struct MateUiAboutInfo
Enumerations
enum MateUiLicenseType {
MATE_UI_LICENSE_GPL_2_0 , MATE_UI_LICENSE_GPL_3_0 , MATE_UI_LICENSE_LGPL_2_1 , MATE_UI_LICENSE_LGPL_3_0 ,
MATE_UI_LICENSE_BSD , MATE_UI_LICENSE_MIT , MATE_UI_LICENSE_CUSTOM
}
Functions
GtkWidget * mate_ui_dialog_about_new (GtkWindow *parent, const MateUiAboutInfo *info)
GtkWidget * mate_ui_dialog_about_new_simple (GtkWindow *parent, const gchar *program_name, const gchar *version, const gchar *copyright, const gchar *comments, const gchar *logo_icon_name)
gint mate_ui_dialog_message (GtkWindow *parent, GtkMessageType type, GtkButtonsType buttons, const gchar *primary, const gchar *secondary)
void mate_ui_dialog_error (GtkWindow *parent, const gchar *primary, const gchar *secondary)
void mate_ui_dialog_warning (GtkWindow *parent, const gchar *primary, const gchar *secondary)
void mate_ui_dialog_info (GtkWindow *parent, const gchar *primary, const gchar *secondary)
gboolean mate_ui_dialog_question (GtkWindow *parent, const gchar *primary, const gchar *secondary)
gboolean mate_ui_dialog_confirm (GtkWindow *parent, const gchar *primary, const gchar *secondary, const gchar *confirm_label, gboolean is_destructive)
gchar * mate_ui_dialog_file_chooser_open (GtkWindow *parent, const gchar *title, const gchar *filter_name, const gchar *filter_pattern)
gchar * mate_ui_dialog_file_chooser_save (GtkWindow *parent, const gchar *title, const gchar *default_name, const gchar *filter_name, const gchar *filter_pattern)
gchar * mate_ui_dialog_folder_chooser (GtkWindow *parent, const gchar *title)
const gchar * mate_ui_get_license_text (MateUiLicenseType license_type)
void mate_ui_dialogs_show_about (GtkWindow *parent, const gchar *program_name, const gchar *version, const gchar *copyright, const gchar *comments, const gchar *website, const gchar *logo_icon_name, const gchar *const *authors, const gchar *const *documenters, const gchar *translator_credits, GtkLicense license_type)
Enumeration Type Documentation
MateUiLicenseType
enum MateUiLicenseType
MateUiLicenseType: @MATE_UI_LICENSE_GPL_2_0: GPL version 2.0 @MATE_UI_LICENSE_GPL_3_0: GPL version 3.0 @MATE_UI_LICENSE_LGPL_2_1: LGPL version 2.1 @MATE_UI_LICENSE_LGPL_3_0: LGPL version 3.0 @MATE_UI_LICENSE_BSD: BSD license @MATE_UI_LICENSE_MIT: MIT license @MATE_UI_LICENSE_CUSTOM: Custom license text
Pre-defined license types for About dialogs.
Enumerator
MATE_UI_LICENSE_GPL_2_0
MATE_UI_LICENSE_GPL_3_0
MATE_UI_LICENSE_LGPL_2_1
MATE_UI_LICENSE_LGPL_3_0
MATE_UI_LICENSE_BSD
MATE_UI_LICENSE_MIT
MATE_UI_LICENSE_CUSTOM
Definition at line 64 of file mate-ui-dialogs.h.
Function Documentation
mate_ui_dialog_about_new()
GtkWidget * mate_ui_dialog_about_new (GtkWindow * parent, const MateUiAboutInfo * info)
mate_ui_dialog_about_new: @parent: (nullable): Parent window @info: About dialog information
Creates and shows an About dialog.
Returns: (transfer full): The #GtkAboutDialog
Definition at line 143 of file mate-ui-dialogs.c.
References NULL, and TRUE.
Referenced by mate_ui_dialog_about_new_simple().
mate_ui_dialog_about_new_simple()
GtkWidget * mate_ui_dialog_about_new_simple (GtkWindow * parent, const gchar * program_name, const gchar * version, const gchar * copyright, const gchar * comments, const gchar * logo_icon_name)
mate_ui_dialog_about_new_simple: @parent: (nullable): Parent window @program_name: Program name
Version
: Version string
Copyright
: Copyright notice @comments: Short description @logo_icon_name: (nullable): Logo icon name
Creates a simple About dialog with minimal information.
Returns: (transfer full): The #GtkAboutDialog
Definition at line 223 of file mate-ui-dialogs.c.
References mate_ui_dialog_about_new(), NULL, and program_name.
mate_ui_dialog_confirm()
gboolean mate_ui_dialog_confirm (GtkWindow * parent, const gchar * primary, const gchar * secondary, const gchar * confirm_label, gboolean is_destructive)
mate_ui_dialog_confirm: @parent: (nullable): Parent window @primary: Primary message @secondary: (nullable): Secondary message @confirm_label: Label for confirm button @is_destructive: Whether the action is destructive (colors button red)
Shows a confirmation dialog with custom button label.
Returns: TRUE if user confirmed, FALSE otherwise
mate_ui_dialog_confirm: @parent: (nullable): Parent window @primary: Primary message @secondary: (nullable): Secondary message @confirm_label: Label for confirm button @is_destructive: Whether the action is destructive
Shows a confirmation dialog with custom button label.
Returns: TRUE if user confirmed, FALSE otherwise
Definition at line 371 of file mate-ui-dialogs.c.
References FALSE, and NULL.
mate_ui_dialog_error()
void mate_ui_dialog_error (GtkWindow * parent, const gchar * primary, const gchar * secondary)
mate_ui_dialog_error: @parent: (nullable): Parent window @primary: Primary error message @secondary: (nullable): Secondary message with details
Shows an error dialog.
Definition at line 296 of file mate-ui-dialogs.c.
References mate_ui_dialog_message().
mate_ui_dialog_file_chooser_open()
gchar * mate_ui_dialog_file_chooser_open (GtkWindow * parent, const gchar * title, const gchar * filter_name, const gchar * filter_pattern)
mate_ui_dialog_file_chooser_open: @parent: (nullable): Parent window @title: Dialog title @filter_name: (nullable): Filter name (e.g., "Text files") @filter_pattern: (nullable): Filter pattern (e.g., "*.txt")
Shows a file open dialog.
Returns: (transfer full) (nullable): Selected filename or NULL if cancelled
mate_ui_dialog_file_chooser_open: @parent: (nullable): Parent window @title: Dialog title @filter_name: (nullable): Filter name @filter_pattern: (nullable): Filter pattern
Shows a file open dialog.
Returns: (transfer full) (nullable): Selected filename or NULL if cancelled
Definition at line 422 of file mate-ui-dialogs.c.
References NULL.
mate_ui_dialog_file_chooser_save()
gchar * mate_ui_dialog_file_chooser_save (GtkWindow * parent, const gchar * title, const gchar * default_name, const gchar * filter_name, const gchar * filter_pattern)
mate_ui_dialog_file_chooser_save: @parent: (nullable): Parent window @title: Dialog title @default_name: (nullable): Default filename @filter_name: (nullable): Filter name @filter_pattern: (nullable): Filter pattern
Shows a file save dialog.
Returns: (transfer full) (nullable): Selected filename or NULL if cancelled
Definition at line 471 of file mate-ui-dialogs.c.
References NULL, and TRUE.
mate_ui_dialog_folder_chooser()
gchar * mate_ui_dialog_folder_chooser (GtkWindow * parent, const gchar * title)
mate_ui_dialog_folder_chooser: @parent: (nullable): Parent window @title: Dialog title
Shows a folder selection dialog.
Returns: (transfer full) (nullable): Selected folder path or NULL if cancelled
Definition at line 524 of file mate-ui-dialogs.c.
References NULL.
mate_ui_dialog_info()
void mate_ui_dialog_info (GtkWindow * parent, const gchar * primary, const gchar * secondary)
mate_ui_dialog_info: @parent: (nullable): Parent window @primary: Primary info message @secondary: (nullable): Secondary message with details
Shows an information dialog.
Definition at line 330 of file mate-ui-dialogs.c.
References mate_ui_dialog_message().
mate_ui_dialog_message()
gint mate_ui_dialog_message (GtkWindow * parent, GtkMessageType type, GtkButtonsType buttons, const gchar * primary, const gchar * secondary)
mate_ui_dialog_message: @parent: (nullable): Parent window @type: Message type @buttons: Button set @primary: Primary message @secondary: (nullable): Secondary message
Shows a message dialog and returns the response.
Returns: The response ID
Definition at line 261 of file mate-ui-dialogs.c.
References NULL.
Referenced by mate_ui_dialog_error(), mate_ui_dialog_info(), mate_ui_dialog_question(), and mate_ui_dialog_warning().
mate_ui_dialog_question()
gboolean mate_ui_dialog_question (GtkWindow * parent, const gchar * primary, const gchar * secondary)
mate_ui_dialog_question: @parent: (nullable): Parent window @primary: Primary question @secondary: (nullable): Secondary message with details
Shows a Yes/No question dialog.
Returns: TRUE if user clicked Yes, FALSE otherwise
Definition at line 349 of file mate-ui-dialogs.c.
References mate_ui_dialog_message().
mate_ui_dialog_warning()
void mate_ui_dialog_warning (GtkWindow * parent, const gchar * primary, const gchar * secondary)
mate_ui_dialog_warning: @parent: (nullable): Parent window @primary: Primary warning message @secondary: (nullable): Secondary message with details
Shows a warning dialog.
Definition at line 313 of file mate-ui-dialogs.c.
References mate_ui_dialog_message().
mate_ui_dialogs_show_about()
void mate_ui_dialogs_show_about (GtkWindow * parent, const gchar * program_name, const gchar * version, const gchar * copyright, const gchar * comments, const gchar * website, const gchar * logo_icon_name, const gchar *const * authors, const gchar *const * documenters, const gchar * translator_credits, GtkLicense license_type)
mate_ui_dialogs_show_about: @parent: (nullable): Parent window @program_name: (nullable): Program name
Version
: (nullable): Version string
Copyright
: (nullable): Copyright notice @comments: (nullable): Brief description @website: (nullable): Website URL @logo_icon_name: (nullable): Logo icon name
Authors
: (nullable): NULL-terminated array of authors @documenters: (nullable): NULL-terminated array of documenters @translator_credits: (nullable): Translator credits @license_type: License type
Shows an About dialog with the given information.
Definition at line 561 of file mate-ui-dialogs.c.
References NULL, program_name, and TRUE.
Referenced by mate_ui_application_show_about().
mate_ui_get_license_text()
const gchar * mate_ui_get_license_text (MateUiLicenseType license_type)
mate_ui_get_license_text: @license_type: The license type
Gets the standard license text for a license type.
Returns: (transfer none): The license text
Definition at line 111 of file mate-ui-dialogs.c.
References MATE_UI_LICENSE_BSD, MATE_UI_LICENSE_CUSTOM, MATE_UI_LICENSE_GPL_2_0, MATE_UI_LICENSE_GPL_3_0, MATE_UI_LICENSE_LGPL_2_1, MATE_UI_LICENSE_LGPL_3_0, and MATE_UI_LICENSE_MIT.