MATE Desktop Environment: mate-keybinding-properties.c File Reference
mate-keybinding-properties.c File Reference
#include <config.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <gdk/gdkx.h>
#include <X11/Xatom.h>
#include <glib/gi18n.h>
#include <gdk/gdkkeysyms.h>
#include "wm-common.h"
#include "capplet-util.h"
#include "eggcellrendererkeys.h"
#include "activate-settings-daemon.h"
#include "dconf-util.h"
Macros
#define GSETTINGS_KEYBINDINGS_DIR "/org/mate/desktop/keybindings/"
#define CUSTOM_KEYBINDING_SCHEMA "org.mate.control-center.keybinding"
#define MAX_ELEMENTS_BEFORE_SCROLLING 10
#define MAX_CUSTOM_SHORTCUTS 1000
#define RESPONSE_ADD 0
#define RESPONSE_REMOVE 1
Enumerations
enum Comparison { COMPARISON_NONE = 0 , COMPARISON_GT , COMPARISON_LT , COMPARISON_EQ }
enum { DESCRIPTION_COLUMN , KEYENTRY_COLUMN , N_COLUMNS }
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
CUSTOM_KEYBINDING_SCHEMA
#define CUSTOM_KEYBINDING_SCHEMA "org.mate.control-center.keybinding"
Definition at line 23 of file mate-keybinding-properties.c.
GSETTINGS_KEYBINDINGS_DIR
#define GSETTINGS_KEYBINDINGS_DIR "/org/mate/desktop/keybindings/"
Definition at line 22 of file mate-keybinding-properties.c.
Referenced by msd_keybindings_manager_start().
MAX_CUSTOM_SHORTCUTS
#define MAX_CUSTOM_SHORTCUTS 1000
Definition at line 26 of file mate-keybinding-properties.c.
MAX_ELEMENTS_BEFORE_SCROLLING
#define MAX_ELEMENTS_BEFORE_SCROLLING 10
Definition at line 25 of file mate-keybinding-properties.c.
RESPONSE_ADD
#define RESPONSE_ADD 0
Definition at line 27 of file mate-keybinding-properties.c.
RESPONSE_REMOVE
#define RESPONSE_REMOVE 1
Definition at line 28 of file mate-keybinding-properties.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DESCRIPTION_COLUMN
KEYENTRY_COLUMN
N_COLUMNS
Definition at line 64 of file mate-keybinding-properties.c.
Comparison
enum Comparison
Enumerator
COMPARISON_NONE
COMPARISON_GT
COMPARISON_LT
COMPARISON_EQ
Definition at line 43 of file mate-keybinding-properties.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 1972 of file mate-keybinding-properties.c.
References activate_settings_daemon(), capplet_init(), NULL, and wm_common_register_window_manager_change().