MATE Desktop Environment: mate-desktop-item.h File Reference
mate-desktop-item.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <gdk/gdk.h>
#include <gtk/gtk.h>
Macros
#define MATE_TYPE_DESKTOP_ITEM (mate_desktop_item_get_type ())
#define MATE_DESKTOP_ITEM_ENCODING "Encoding" /* string */
#define MATE_DESKTOP_ITEM_VERSION "Version" /* numeric */
#define MATE_DESKTOP_ITEM_NAME "Name" /* localestring */
#define MATE_DESKTOP_ITEM_GENERIC_NAME "GenericName" /* localestring */
#define MATE_DESKTOP_ITEM_TYPE "Type" /* string */
#define MATE_DESKTOP_ITEM_FILE_PATTERN "FilePattern" /* regexp(s) */
#define MATE_DESKTOP_ITEM_TRY_EXEC "TryExec" /* string */
#define MATE_DESKTOP_ITEM_NO_DISPLAY "NoDisplay" /* boolean */
#define MATE_DESKTOP_ITEM_COMMENT "Comment" /* localestring */
#define MATE_DESKTOP_ITEM_EXEC "Exec" /* string */
#define MATE_DESKTOP_ITEM_ACTIONS "Actions" /* strings */
#define MATE_DESKTOP_ITEM_ICON "Icon" /* string */
#define MATE_DESKTOP_ITEM_MINI_ICON "MiniIcon" /* string */
#define MATE_DESKTOP_ITEM_HIDDEN "Hidden" /* boolean */
#define MATE_DESKTOP_ITEM_PATH "Path" /* string */
#define MATE_DESKTOP_ITEM_TERMINAL "Terminal" /* boolean */
#define MATE_DESKTOP_ITEM_TERMINAL_OPTIONS "TerminalOptions" /* string */
#define MATE_DESKTOP_ITEM_SWALLOW_TITLE "SwallowTitle" /* string */
#define MATE_DESKTOP_ITEM_SWALLOW_EXEC "SwallowExec" /* string */
#define MATE_DESKTOP_ITEM_MIME_TYPE "MimeType" /* regexp(s) */
#define MATE_DESKTOP_ITEM_PATTERNS "Patterns" /* regexp(s) */
#define MATE_DESKTOP_ITEM_DEFAULT_APP "DefaultApp" /* string */
#define MATE_DESKTOP_ITEM_DEV "Dev" /* string */
#define MATE_DESKTOP_ITEM_FS_TYPE "FSType" /* string */
#define MATE_DESKTOP_ITEM_MOUNT_POINT "MountPoint" /* string */
#define MATE_DESKTOP_ITEM_READ_ONLY "ReadOnly" /* boolean */
#define MATE_DESKTOP_ITEM_UNMOUNT_ICON "UnmountIcon" /* string */
#define MATE_DESKTOP_ITEM_SORT_ORDER "SortOrder" /* strings */
#define MATE_DESKTOP_ITEM_URL "URL" /* string */
#define MATE_DESKTOP_ITEM_DOC_PATH "X-MATE-DocPath" /* string */
#define MATE_DESKTOP_ITEM_CATEGORIES "Categories" /* string */
#define MATE_DESKTOP_ITEM_ONLY_SHOW_IN "OnlyShowIn" /* string */
#define MATE_DESKTOP_ITEM_ERROR mate_desktop_item_error_quark ()
#define mate_desktop_item_clear_attr(item, attr)
Typedefs
typedef struct _MateDesktopItem MateDesktopItem
Enumerations
enum MateDesktopItemType {
MATE_DESKTOP_ITEM_TYPE_NULL = 0 , MATE_DESKTOP_ITEM_TYPE_OTHER , MATE_DESKTOP_ITEM_TYPE_APPLICATION , MATE_DESKTOP_ITEM_TYPE_LINK ,
MATE_DESKTOP_ITEM_TYPE_FSDEVICE , MATE_DESKTOP_ITEM_TYPE_MIME_TYPE , MATE_DESKTOP_ITEM_TYPE_DIRECTORY , MATE_DESKTOP_ITEM_TYPE_SERVICE ,
MATE_DESKTOP_ITEM_TYPE_SERVICE_TYPE
}
enum MateDesktopItemStatus { MATE_DESKTOP_ITEM_UNCHANGED = 0 , MATE_DESKTOP_ITEM_CHANGED = 1 , MATE_DESKTOP_ITEM_DISAPPEARED = 2 }
enum MateDesktopItemLoadFlags { MATE_DESKTOP_ITEM_LOAD_ONLY_IF_EXISTS = 1<<0 , MATE_DESKTOP_ITEM_LOAD_NO_TRANSLATIONS = 1<<1 }
enum MateDesktopItemLaunchFlags {
MATE_DESKTOP_ITEM_LAUNCH_ONLY_ONE = 1<<0 , MATE_DESKTOP_ITEM_LAUNCH_USE_CURRENT_DIR = 1<<1 , MATE_DESKTOP_ITEM_LAUNCH_APPEND_URIS = 1<<2 , MATE_DESKTOP_ITEM_LAUNCH_APPEND_PATHS = 1<<3 ,
MATE_DESKTOP_ITEM_LAUNCH_DO_NOT_REAP_CHILD = 1<<4
}
enum MateDesktopItemIconFlags { MATE_DESKTOP_ITEM_ICON_NO_KDE = 1<<0 }
enum MateDesktopItemError {
MATE_DESKTOP_ITEM_ERROR_NO_FILENAME , MATE_DESKTOP_ITEM_ERROR_UNKNOWN_ENCODING , MATE_DESKTOP_ITEM_ERROR_CANNOT_OPEN , MATE_DESKTOP_ITEM_ERROR_NO_EXEC_STRING ,
MATE_DESKTOP_ITEM_ERROR_BAD_EXEC_STRING , MATE_DESKTOP_ITEM_ERROR_NO_URL , MATE_DESKTOP_ITEM_ERROR_NOT_LAUNCHABLE , MATE_DESKTOP_ITEM_ERROR_INVALID_TYPE
}
Functions
GType mate_desktop_item_get_type (void)
GQuark mate_desktop_item_error_quark (void)
MateDesktopItem * mate_desktop_item_new (void)
MateDesktopItem * mate_desktop_item_new_from_file (const char *file, MateDesktopItemLoadFlags flags, GError **error)
MateDesktopItem * mate_desktop_item_new_from_uri (const char *uri, MateDesktopItemLoadFlags flags, GError **error)
MateDesktopItem * mate_desktop_item_new_from_string (const char *uri, const char *string, gssize length, MateDesktopItemLoadFlags flags, GError **error)
MateDesktopItem * mate_desktop_item_new_from_basename (const char *basename, MateDesktopItemLoadFlags flags, GError **error)
MateDesktopItem * mate_desktop_item_copy (const MateDesktopItem *item)
gboolean mate_desktop_item_save (MateDesktopItem *item, const char *under, gboolean force, GError **error)
MateDesktopItem * mate_desktop_item_ref (MateDesktopItem *item)
void mate_desktop_item_unref (MateDesktopItem *item)
int mate_desktop_item_launch (const MateDesktopItem *item, GList *file_list, MateDesktopItemLaunchFlags flags, GError **error)
int mate_desktop_item_launch_with_env (const MateDesktopItem *item, GList *file_list, MateDesktopItemLaunchFlags flags, char **envp, GError **error)
int mate_desktop_item_launch_on_screen (const MateDesktopItem *item, GList *file_list, MateDesktopItemLaunchFlags flags, GdkScreen *screen, int workspace, GError **error)
int mate_desktop_item_drop_uri_list (const MateDesktopItem *item, const char *uri_list, MateDesktopItemLaunchFlags flags, GError **error)
int mate_desktop_item_drop_uri_list_with_env (const MateDesktopItem *item, const char *uri_list, MateDesktopItemLaunchFlags flags, char **envp, GError **error)
gboolean mate_desktop_item_exists (const MateDesktopItem *item)
MateDesktopItemType mate_desktop_item_get_entry_type (const MateDesktopItem *item)
void mate_desktop_item_set_entry_type (MateDesktopItem *item, MateDesktopItemType type)
const char * mate_desktop_item_get_location (const MateDesktopItem *item)
void mate_desktop_item_set_location (MateDesktopItem *item, const char *location)
void mate_desktop_item_set_location_file (MateDesktopItem *item, const char *file)
MateDesktopItemStatus mate_desktop_item_get_file_status (const MateDesktopItem *item)
char * mate_desktop_item_get_icon (const MateDesktopItem *item, GtkIconTheme *icon_theme)
char * mate_desktop_item_find_icon (GtkIconTheme *icon_theme, const char *icon, int desired_size, int flags)
gboolean mate_desktop_item_attr_exists (const MateDesktopItem *item, const char *attr)
const char * mate_desktop_item_get_string (const MateDesktopItem *item, const char *attr)
void mate_desktop_item_set_string (MateDesktopItem *item, const char *attr, const char *value)
const char * mate_desktop_item_get_attr_locale (const MateDesktopItem *item, const char *attr)
const char * mate_desktop_item_get_localestring (const MateDesktopItem *item, const char *attr)
const char * mate_desktop_item_get_localestring_lang (const MateDesktopItem *item, const char *attr, const char *language)
GList * mate_desktop_item_get_languages (const MateDesktopItem *item, const char *attr)
void mate_desktop_item_set_localestring (MateDesktopItem *item, const char *attr, const char *value)
void mate_desktop_item_set_localestring_lang (MateDesktopItem *item, const char *attr, const char *language, const char *value)
void mate_desktop_item_clear_localestring (MateDesktopItem *item, const char *attr)
char ** mate_desktop_item_get_strings (const MateDesktopItem *item, const char *attr)
void mate_desktop_item_set_strings (MateDesktopItem *item, const char *attr, char **strings)
gboolean mate_desktop_item_get_boolean (const MateDesktopItem *item, const char *attr)
void mate_desktop_item_set_boolean (MateDesktopItem *item, const char *attr, gboolean value)
void mate_desktop_item_set_launch_time (MateDesktopItem *item, guint32 timestamp)
void mate_desktop_item_clear_section (MateDesktopItem *item, const char *section)
Macro Definition Documentation
MATE_DESKTOP_ITEM_ACTIONS
#define MATE_DESKTOP_ITEM_ACTIONS "Actions" /* strings */
Definition at line 78 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_CATEGORIES
#define MATE_DESKTOP_ITEM_CATEGORIES "Categories" /* string */
Definition at line 100 of file mate-desktop-item.h.
mate_desktop_item_clear_attr
#define mate_desktop_item_clear_attr (item, attr)
Value:
mate_desktop_item_set_string(item,attr,NULL)
Definition at line 300 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_COMMENT
#define MATE_DESKTOP_ITEM_COMMENT "Comment" /* localestring */
Definition at line 76 of file mate-desktop-item.h.
Referenced by mate_theme_read_meta_theme().
MATE_DESKTOP_ITEM_DEFAULT_APP
#define MATE_DESKTOP_ITEM_DEFAULT_APP "DefaultApp" /* string */
Definition at line 89 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_DEV
#define MATE_DESKTOP_ITEM_DEV "Dev" /* string */
Definition at line 90 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_DOC_PATH
#define MATE_DESKTOP_ITEM_DOC_PATH "X-MATE-DocPath" /* string */
Definition at line 97 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_ENCODING
#define MATE_DESKTOP_ITEM_ENCODING "Encoding" /* string */
Definition at line 68 of file mate-desktop-item.h.
Referenced by mate_desktop_item_new().
MATE_DESKTOP_ITEM_ERROR
#define MATE_DESKTOP_ITEM_ERROR mate_desktop_item_error_quark ()
Definition at line 143 of file mate-desktop-item.h.
Referenced by mate_desktop_item_new_from_basename(), and mate_desktop_item_save().
MATE_DESKTOP_ITEM_EXEC
#define MATE_DESKTOP_ITEM_EXEC "Exec" /* string */
Definition at line 77 of file mate-desktop-item.h.
Referenced by mate_desktop_item_exists().
MATE_DESKTOP_ITEM_FILE_PATTERN
#define MATE_DESKTOP_ITEM_FILE_PATTERN "FilePattern" /* regexp(s) */
Definition at line 73 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_FS_TYPE
#define MATE_DESKTOP_ITEM_FS_TYPE "FSType" /* string */
Definition at line 91 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_GENERIC_NAME
#define MATE_DESKTOP_ITEM_GENERIC_NAME "GenericName" /* localestring */
Definition at line 71 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_HIDDEN
#define MATE_DESKTOP_ITEM_HIDDEN "Hidden" /* boolean */
Definition at line 81 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_ICON
#define MATE_DESKTOP_ITEM_ICON "Icon" /* string */
Definition at line 79 of file mate-desktop-item.h.
Referenced by mate_desktop_item_get_icon(), and mate_theme_read_meta_theme().
MATE_DESKTOP_ITEM_MIME_TYPE
#define MATE_DESKTOP_ITEM_MIME_TYPE "MimeType" /* regexp(s) */
Definition at line 87 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_MINI_ICON
#define MATE_DESKTOP_ITEM_MINI_ICON "MiniIcon" /* string */
Definition at line 80 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_MOUNT_POINT
#define MATE_DESKTOP_ITEM_MOUNT_POINT "MountPoint" /* string */
Definition at line 92 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_NAME
#define MATE_DESKTOP_ITEM_NAME "Name" /* localestring */
Definition at line 70 of file mate-desktop-item.h.
Referenced by mate_desktop_item_new(), and mate_theme_read_meta_theme().
MATE_DESKTOP_ITEM_NO_DISPLAY
#define MATE_DESKTOP_ITEM_NO_DISPLAY "NoDisplay" /* boolean */
Definition at line 75 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_ONLY_SHOW_IN
#define MATE_DESKTOP_ITEM_ONLY_SHOW_IN "OnlyShowIn" /* string */
Definition at line 101 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_PATH
#define MATE_DESKTOP_ITEM_PATH "Path" /* string */
Definition at line 82 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_PATTERNS
#define MATE_DESKTOP_ITEM_PATTERNS "Patterns" /* regexp(s) */
Definition at line 88 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_READ_ONLY
#define MATE_DESKTOP_ITEM_READ_ONLY "ReadOnly" /* boolean */
Definition at line 93 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_SORT_ORDER
#define MATE_DESKTOP_ITEM_SORT_ORDER "SortOrder" /* strings */
Definition at line 95 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_SWALLOW_EXEC
#define MATE_DESKTOP_ITEM_SWALLOW_EXEC "SwallowExec" /* string */
Definition at line 86 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_SWALLOW_TITLE
#define MATE_DESKTOP_ITEM_SWALLOW_TITLE "SwallowTitle" /* string */
Definition at line 85 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_TERMINAL
#define MATE_DESKTOP_ITEM_TERMINAL "Terminal" /* boolean */
Definition at line 83 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_TERMINAL_OPTIONS
#define MATE_DESKTOP_ITEM_TERMINAL_OPTIONS "TerminalOptions" /* string */
Definition at line 84 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_TRY_EXEC
#define MATE_DESKTOP_ITEM_TRY_EXEC "TryExec" /* string */
Definition at line 74 of file mate-desktop-item.h.
Referenced by mate_desktop_item_exists().
MATE_DESKTOP_ITEM_TYPE
#define MATE_DESKTOP_ITEM_TYPE "Type" /* string */
Definition at line 72 of file mate-desktop-item.h.
Referenced by mate_desktop_item_set_entry_type(), and mate_desktop_item_set_string().
MATE_DESKTOP_ITEM_UNMOUNT_ICON
#define MATE_DESKTOP_ITEM_UNMOUNT_ICON "UnmountIcon" /* string */
Definition at line 94 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_URL
#define MATE_DESKTOP_ITEM_URL "URL" /* string */
Definition at line 96 of file mate-desktop-item.h.
MATE_DESKTOP_ITEM_VERSION
#define MATE_DESKTOP_ITEM_VERSION "Version" /* numeric */
Definition at line 69 of file mate-desktop-item.h.
Referenced by mate_desktop_item_new().
MATE_TYPE_DESKTOP_ITEM
#define MATE_TYPE_DESKTOP_ITEM (mate_desktop_item_get_type ())
Definition at line 62 of file mate-desktop-item.h.
Typedef Documentation
MateDesktopItem
typedef struct _MateDesktopItem MateDesktopItem
Definition at line 65 of file mate-desktop-item.h.
Enumeration Type Documentation
MateDesktopItemError
enum MateDesktopItemError
Enumerator
MATE_DESKTOP_ITEM_ERROR_NO_FILENAME
MATE_DESKTOP_ITEM_ERROR_UNKNOWN_ENCODING
MATE_DESKTOP_ITEM_ERROR_CANNOT_OPEN
MATE_DESKTOP_ITEM_ERROR_NO_EXEC_STRING
MATE_DESKTOP_ITEM_ERROR_BAD_EXEC_STRING
MATE_DESKTOP_ITEM_ERROR_NO_URL
MATE_DESKTOP_ITEM_ERROR_NOT_LAUNCHABLE
MATE_DESKTOP_ITEM_ERROR_INVALID_TYPE
Definition at line 130 of file mate-desktop-item.h.
MateDesktopItemIconFlags
enum MateDesktopItemIconFlags
Enumerator
MATE_DESKTOP_ITEM_ICON_NO_KDE
Definition at line 125 of file mate-desktop-item.h.
MateDesktopItemLaunchFlags
enum MateDesktopItemLaunchFlags
Enumerator
MATE_DESKTOP_ITEM_LAUNCH_ONLY_ONE
MATE_DESKTOP_ITEM_LAUNCH_USE_CURRENT_DIR
MATE_DESKTOP_ITEM_LAUNCH_APPEND_URIS
MATE_DESKTOP_ITEM_LAUNCH_APPEND_PATHS
MATE_DESKTOP_ITEM_LAUNCH_DO_NOT_REAP_CHILD
Definition at line 109 of file mate-desktop-item.h.
MateDesktopItemLoadFlags
enum MateDesktopItemLoadFlags
Enumerator
MATE_DESKTOP_ITEM_LOAD_ONLY_IF_EXISTS
MATE_DESKTOP_ITEM_LOAD_NO_TRANSLATIONS
Definition at line 103 of file mate-desktop-item.h.
MateDesktopItemStatus
enum MateDesktopItemStatus
Enumerator
MATE_DESKTOP_ITEM_UNCHANGED
MATE_DESKTOP_ITEM_CHANGED
MATE_DESKTOP_ITEM_DISAPPEARED
Definition at line 56 of file mate-desktop-item.h.
MateDesktopItemType
enum MateDesktopItemType
Enumerator
MATE_DESKTOP_ITEM_TYPE_NULL
MATE_DESKTOP_ITEM_TYPE_OTHER
MATE_DESKTOP_ITEM_TYPE_APPLICATION
MATE_DESKTOP_ITEM_TYPE_LINK
MATE_DESKTOP_ITEM_TYPE_FSDEVICE
MATE_DESKTOP_ITEM_TYPE_MIME_TYPE
MATE_DESKTOP_ITEM_TYPE_DIRECTORY
MATE_DESKTOP_ITEM_TYPE_SERVICE
MATE_DESKTOP_ITEM_TYPE_SERVICE_TYPE
Definition at line 39 of file mate-desktop-item.h.
Function Documentation
mate_desktop_item_attr_exists()
gboolean mate_desktop_item_attr_exists (const MateDesktopItem * item, const char * attr)
Definition at line 2685 of file mate-desktop-item.c.
References FALSE, item, and NULL.
mate_desktop_item_clear_localestring()
void mate_desktop_item_clear_localestring (MateDesktopItem * item, const char * attr)
Definition at line 2841 of file mate-desktop-item.c.
References item, NULL, and set.
mate_desktop_item_clear_section()
void mate_desktop_item_clear_section (MateDesktopItem * item, const char * section)
Definition at line 2946 of file mate-desktop-item.c.
References item, key, NULL, and TRUE.
mate_desktop_item_copy()
MateDesktopItem * mate_desktop_item_copy (const MateDesktopItem * item)
mate_desktop_item_copy: @item: The item to be copied
Creates a copy of a MateDesktopItem. The new copy has a refcount of 1. Note: Section stack is NOT copied.
Returns: The new copy
Definition at line 425 of file mate-desktop-item.c.
References item, mate_desktop_item_new(), and NULL.
mate_desktop_item_drop_uri_list()
int mate_desktop_item_drop_uri_list (const MateDesktopItem * item, const char * uri_list, MateDesktopItemLaunchFlags flags, GError ** error)
mate_desktop_item_drop_uri_list: @item: A desktop item @uri_list: text as gotten from a text/uri-list @flags: FIXME @error: FIXME
A list of files or urls dropped onto an icon, the proper (Url or File) exec is run you can pass directly string that you got as the text/uri-list. This just parses the list and calls
Returns: The value returned by #mate_execute_async() upon execution of the specified item or -1 on error. If multiple instances are run, the return of the last one is returned.
Definition at line 2250 of file mate-desktop-item.c.
References error, item, mate_desktop_item_drop_uri_list_with_env(), and NULL.
mate_desktop_item_drop_uri_list_with_env()
int mate_desktop_item_drop_uri_list_with_env (const MateDesktopItem * item, const char * uri_list, MateDesktopItemLaunchFlags flags, char ** envp, GError ** error)
mate_desktop_item_drop_uri_list_with_env: @item: A desktop item @uri_list: text as gotten from a text/uri-list @flags: FIXME @envp: child's environment @error: FIXME
See mate_desktop_item_drop_uri_list for a full description. This function additionally passes an environment vector for the child process which is to be launched.
Returns: The value returned by #mate_execute_async() upon execution of the specified item or -1 on error. If multiple instances are run, the return of the last one is returned.
Definition at line 2276 of file mate-desktop-item.c.
References error, item, mate_desktop_item_launch_with_env(), and NULL.
Referenced by mate_desktop_item_drop_uri_list().
mate_desktop_item_error_quark()
GQuark mate_desktop_item_error_quark (void)
Definition at line 3889 of file mate-desktop-item.c.
mate_desktop_item_exists()
gboolean mate_desktop_item_exists (const MateDesktopItem * item)
mate_desktop_item_exists: @item: A desktop item
Attempt to figure out if the program that can be executed by this item actually exists. First it tries the TryExec attribute to see if that contains a program that is in the path. Then if there is no such attribute, it tries the first word of the Exec attribute.
Returns: A boolean, TRUE if it exists, FALSE otherwise.
Definition at line 2335 of file mate-desktop-item.c.
References FALSE, item, MATE_DESKTOP_ITEM_EXEC, MATE_DESKTOP_ITEM_TRY_EXEC, MATE_DESKTOP_ITEM_TYPE_APPLICATION, NULL, and TRUE.
mate_desktop_item_find_icon()
char * mate_desktop_item_find_icon (GtkIconTheme * icon_theme, const char * icon, int desired_size, int flags)
mate_desktop_item_find_icon: @icon_theme: a #GtkIconTheme @icon: icon name, something you'd get out of the Icon key @desired_size: FIXME @flags: FIXME
Description: This function goes and looks for the icon file. If the icon is not an absolute filename, this will look for it in the standard places. If it can't find the icon, it will return NULL
Returns: A newly allocated string
Definition at line 2492 of file mate-desktop-item.c.
References NULL, and strrchr.
Referenced by mate_desktop_item_get_icon().
mate_desktop_item_get_attr_locale()
const char * mate_desktop_item_get_attr_locale (const MateDesktopItem * item, const char * attr)
mate_desktop_item_get_string_locale: @item: A desktop item @attr: An attribute name
Returns the current locale that is used for the given attribute. This might not be the same for all attributes. For example, if your locale is "en_US.ISO8859-1" but attribute FOO only has "en_US" then that would be returned for attr = "FOO". If attribute BAR has "en_US.ISO8859-1" then that would be returned for "BAR".
Returns: a string equal to the current locale or NULL if the attribute is invalid or there is no matching locale.
Definition at line 2760 of file mate-desktop-item.c.
References item, and NULL.
mate_desktop_item_get_boolean()
gboolean mate_desktop_item_get_boolean (const MateDesktopItem * item, const char * attr)
Definition at line 2901 of file mate-desktop-item.c.
References FALSE, item, and NULL.
Referenced by mate_theme_read_meta_theme().
mate_desktop_item_get_entry_type()
MateDesktopItemType mate_desktop_item_get_entry_type (const MateDesktopItem * item)
mate_desktop_item_get_entry_type: @item: A desktop item
Gets the type attribute (the 'Type' field) of the item. This should usually be 'Application' for an application, but it can be 'Directory' for a directory description. There are other types available as well. The type usually indicates how the desktop item should be handeled and how the 'Exec' field should be handeled.
Returns: The type of the specified 'item'. The returned memory remains owned by the MateDesktopItem and should not be freed.
Definition at line 2392 of file mate-desktop-item.c.
References item, and NULL.
Referenced by application_tile_new_full().
mate_desktop_item_get_file_status()
MateDesktopItemStatus mate_desktop_item_get_file_status (const MateDesktopItem * item)
mate_desktop_item_get_file_status: @item: A desktop item
This function checks the modification time of the on-disk file to see if it is more recent than the in-memory data.
Returns: An enum value that specifies whether the item has changed since being loaded.
Definition at line 2449 of file mate-desktop-item.c.
References item, MATE_DESKTOP_ITEM_CHANGED, MATE_DESKTOP_ITEM_DISAPPEARED, MATE_DESKTOP_ITEM_UNCHANGED, and NULL.
mate_desktop_item_get_icon()
char * mate_desktop_item_get_icon (const MateDesktopItem * item, GtkIconTheme * icon_theme)
mate_desktop_item_get_icon: @icon_theme: a #GtkIconTheme @item: A desktop item
Description: This function goes and looks for the icon file. If the icon is not set as an absolute filename, this will look for it in the standard places. If it can't find the icon, it will return NULL
Returns: A newly allocated string
Definition at line 2556 of file mate-desktop-item.c.
References item, mate_desktop_item_find_icon(), mate_desktop_item_get_string(), MATE_DESKTOP_ITEM_ICON, and NULL.
mate_desktop_item_get_languages()
GList * mate_desktop_item_get_languages (const MateDesktopItem * item, const char * attr)
Definition at line 2779 of file mate-desktop-item.c.
References item, and NULL.
mate_desktop_item_get_localestring()
const char * mate_desktop_item_get_localestring (const MateDesktopItem * item, const char * attr)
Definition at line 2727 of file mate-desktop-item.c.
References item, and NULL.
Referenced by mate_theme_read_meta_theme().
mate_desktop_item_get_localestring_lang()
const char * mate_desktop_item_get_localestring_lang (const MateDesktopItem * item, const char * attr, const char * language)
Definition at line 2736 of file mate-desktop-item.c.
References item, and NULL.
mate_desktop_item_get_location()
const char * mate_desktop_item_get_location (const MateDesktopItem * item)
mate_desktop_item_get_location: @item: A desktop item
Returns: The file location associated with 'item'.
Definition at line 2581 of file mate-desktop-item.c.
References item, and NULL.
Referenced by application_tile_new_full(), and open_desktop_item_exec().
mate_desktop_item_get_string()
const char * mate_desktop_item_get_string (const MateDesktopItem * item, const char * attr)
Definition at line 2699 of file mate-desktop-item.c.
References item, and NULL.
Referenced by mate_desktop_item_get_icon(), mate_theme_read_meta_theme(), and open_desktop_item_help().
mate_desktop_item_get_strings()
char ** mate_desktop_item_get_strings (const MateDesktopItem * item, const char * attr)
Definition at line 2861 of file mate-desktop-item.c.
References item, and NULL.
mate_desktop_item_get_type()
GType mate_desktop_item_get_type (void)
Definition at line 3875 of file mate-desktop-item.c.
mate_desktop_item_launch()
int mate_desktop_item_launch (const MateDesktopItem * item, GList * file_list, MateDesktopItemLaunchFlags flags, GError ** error)
mate_desktop_item_launch: @item: A desktop item @file_list: Files/URIs to launch this item with, can be NULL @flags: FIXME @error: FIXME
This function runs the program listed in the specified 'item', optionally appending additional arguments to its command line. It uses #g_shell_parse_argv to parse the the exec string into a vector which is then passed to #g_spawn_async for execution. This can return all the errors from MateURL, #g_shell_parse_argv and #g_spawn_async, in addition to it's own. The files are only added if the entry defines one of the standard % strings in it's Exec field.
Returns: The the pid of the process spawned. If more then one process was spawned the last pid is returned. On error -1 is returned and @error is set.
Definition at line 2167 of file mate-desktop-item.c.
References error, file_list, item, and NULL.
Referenced by open_desktop_item_exec().
mate_desktop_item_launch_on_screen()
int mate_desktop_item_launch_on_screen (const MateDesktopItem * item, GList * file_list, MateDesktopItemLaunchFlags flags, GdkScreen * screen, int workspace, GError ** error)
mate_desktop_item_launch_on_screen: @item: A desktop item @file_list: Files/URIs to launch this item with, can be NULL @flags: FIXME @screen: the GdkScreen on which the application should be launched @workspace: the workspace on which the app should be launched (-1 for current) @error: FIXME
See mate_desktop_item_launch for a full description. This function additionally attempts to launch the application on a given screen and workspace.
Returns: The the pid of the process spawned. If more then one process was spawned the last pid is returned. On error -1 is returned and @error is set.
Definition at line 2222 of file mate-desktop-item.c.
References error, file_list, item, and NULL.
mate_desktop_item_launch_with_env()
int mate_desktop_item_launch_with_env (const MateDesktopItem * item, GList * file_list, MateDesktopItemLaunchFlags flags, char ** envp, GError ** error)
mate_desktop_item_launch_with_env: @item: A desktop item @file_list: Files/URIs to launch this item with, can be NULL @flags: FIXME @envp: child's environment, or NULL to inherit parent's @error: FIXME
See mate_desktop_item_launch for a full description. This function additionally passes an environment vector for the child process which is to be launched.
Returns: The the pid of the process spawned. If more then one process was spawned the last pid is returned. On error -1 is returned and @error is set.
Definition at line 2193 of file mate-desktop-item.c.
References error, file_list, item, and NULL.
Referenced by mate_desktop_item_drop_uri_list_with_env().
mate_desktop_item_new()
MateDesktopItem * mate_desktop_item_new (void)
mate_desktop_item_new:
Creates a MateDesktopItem object. The reference count on the returned value is set to '1'.
Returns: The new MateDesktopItem
Definition at line 358 of file mate-desktop-item.c.
References _, _mate_desktop_init_i18n(), MATE_DESKTOP_ITEM_ENCODING, MATE_DESKTOP_ITEM_NAME, mate_desktop_item_set_string(), and MATE_DESKTOP_ITEM_VERSION.
Referenced by mate_desktop_item_copy().
mate_desktop_item_new_from_basename()
MateDesktopItem * mate_desktop_item_new_from_basename (const char * basename, MateDesktopItemLoadFlags flags, GError ** error)
mate_desktop_item_new_from_basename: @basename: The basename of the MateDesktopItem to load. @flags: Flags to influence the loading process
This function loads 'basename' from a system data directory and returns its MateDesktopItem.
Returns: The newly loaded item.
Definition at line 774 of file mate-desktop-item.c.
References _, error, MATE_DESKTOP_ITEM_ERROR, MATE_DESKTOP_ITEM_ERROR_CANNOT_OPEN, mate_desktop_item_new_from_file(), and NULL.
Referenced by libslab_mate_desktop_item_new_from_unknown_id(), and load_desktop_item_from_unknown().
mate_desktop_item_new_from_file()
MateDesktopItem * mate_desktop_item_new_from_file (const char * file, MateDesktopItemLoadFlags flags, GError ** error)
Definition at line 530 of file mate-desktop-item.c.
References error, and NULL.
Referenced by libslab_mate_desktop_item_new_from_unknown_id(), load_desktop_item_from_unknown(), and mate_desktop_item_new_from_basename().
mate_desktop_item_new_from_string()
MateDesktopItem * mate_desktop_item_new_from_string (const char * uri, const char * string, gssize length, MateDesktopItemLoadFlags flags, GError ** error)
mate_desktop_item_new_from_string: @string: string to load the MateDesktopItem from @length: length of string, or -1 to use strlen @flags: Flags to influence the loading process @error: place to put errors
This function turns the contents of the string into a MateDesktopItem.
Returns: The newly loaded item.
Definition at line 696 of file mate-desktop-item.c.
References error, MATE_DESKTOP_ITEM_LOAD_NO_TRANSLATIONS, and NULL.
mate_desktop_item_new_from_uri()
MateDesktopItem * mate_desktop_item_new_from_uri (const char * uri, MateDesktopItemLoadFlags flags, GError ** error)
mate_desktop_item_new_from_uri: @uri: URI to load the MateDesktopItem from @flags: Flags to influence the loading process
This function loads 'uri' and turns it into a MateDesktopItem.
Returns: The newly loaded item.
Definition at line 556 of file mate-desktop-item.c.
References error, and NULL.
Referenced by libslab_mate_desktop_item_new_from_unknown_id(), load_desktop_item_from_unknown(), and mate_theme_read_meta_theme().
mate_desktop_item_ref()
MateDesktopItem * mate_desktop_item_ref (MateDesktopItem * item)
mate_desktop_item_ref: @item: A desktop item
Description: Increases the reference count of the specified item.
Returns: the newly referenced @item
Definition at line 855 of file mate-desktop-item.c.
References item, and NULL.
mate_desktop_item_save()
gboolean mate_desktop_item_save (MateDesktopItem * item, const char * under, gboolean force, GError ** error)
mate_desktop_item_save: @item: A desktop item @under: A new uri (location) for this MateDesktopItem @force: Save even if it wasn't modified @error: #GError return
Writes the specified item to disk. If the 'under' is NULL, the original location is used. It sets the location of this entry to point to the new location.
Returns: boolean. TRUE if the file was saved, FALSE otherwise
Definition at line 812 of file mate-desktop-item.c.
References _, error, FALSE, item, MATE_DESKTOP_ITEM_ERROR, MATE_DESKTOP_ITEM_ERROR_NO_FILENAME, NULL, and TRUE.
mate_desktop_item_set_boolean()
void mate_desktop_item_set_boolean (MateDesktopItem * item, const char * attr, gboolean value)
Definition at line 2922 of file mate-desktop-item.c.
References item, NULL, and set.
mate_desktop_item_set_entry_type()
void mate_desktop_item_set_entry_type (MateDesktopItem * item, MateDesktopItemType type)
Definition at line 2401 of file mate-desktop-item.c.
References item, MATE_DESKTOP_ITEM_TYPE, MATE_DESKTOP_ITEM_TYPE_APPLICATION, MATE_DESKTOP_ITEM_TYPE_DIRECTORY, MATE_DESKTOP_ITEM_TYPE_FSDEVICE, MATE_DESKTOP_ITEM_TYPE_LINK, MATE_DESKTOP_ITEM_TYPE_MIME_TYPE, MATE_DESKTOP_ITEM_TYPE_NULL, MATE_DESKTOP_ITEM_TYPE_SERVICE, MATE_DESKTOP_ITEM_TYPE_SERVICE_TYPE, NULL, and set.
mate_desktop_item_set_launch_time()
void mate_desktop_item_set_launch_time (MateDesktopItem * item, guint32 timestamp)
Definition at line 2934 of file mate-desktop-item.c.
References item, and NULL.
mate_desktop_item_set_localestring()
void mate_desktop_item_set_localestring (MateDesktopItem * item, const char * attr, const char * value)
Definition at line 2816 of file mate-desktop-item.c.
References item, and NULL.
mate_desktop_item_set_localestring_lang()
void mate_desktop_item_set_localestring_lang (MateDesktopItem * item, const char * attr, const char * language, const char * value)
Definition at line 2828 of file mate-desktop-item.c.
References item, and NULL.
mate_desktop_item_set_location()
void mate_desktop_item_set_location (MateDesktopItem * item, const char * location)
mate_desktop_item_set_location: @item: A desktop item @location: A uri string specifying the file location of this particular item.
Set's the 'location' uri of this item.
Definition at line 2597 of file mate-desktop-item.c.
References DONT_UPDATE_MTIME, item, NULL, and TRUE.
Referenced by mate_desktop_item_set_location_file().
mate_desktop_item_set_location_file()
void mate_desktop_item_set_location_file (MateDesktopItem * item, const char * file)
Definition at line 2647 of file mate-desktop-item.c.
References item, mate_desktop_item_set_location(), and NULL.
mate_desktop_item_set_string()
void mate_desktop_item_set_string (MateDesktopItem * item, const char * attr, const char * value)
Definition at line 2710 of file mate-desktop-item.c.
References item, MATE_DESKTOP_ITEM_TYPE, NULL, and set.
Referenced by mate_desktop_item_new().
mate_desktop_item_set_strings()
void mate_desktop_item_set_strings (MateDesktopItem * item, const char * attr, char ** strings)
Definition at line 2879 of file mate-desktop-item.c.
References item, NULL, and set.
mate_desktop_item_unref()
void mate_desktop_item_unref (MateDesktopItem * item)
mate_desktop_item_unref: @item: A desktop item
Decreases the reference count of the specified item, and destroys the item if there are no more references left.
Definition at line 885 of file mate-desktop-item.c.
References item, and NULL.
Referenced by application_tile_new_full(), and mate_theme_read_meta_theme().