MATE Desktop Environment: mate-network-properties.c File Reference
mate-network-properties.c File Reference
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <glib/gi18n.h>
#include "capplet-util.h"
Macros
#define PROXY_SCHEMA "org.gnome.system.proxy"
#define PROXY_MODE_KEY "mode"
#define PROXY_AUTOCONFIG_URL_KEY "autoconfig-url"
#define IGNORE_HOSTS_KEY "ignore-hosts"
#define HTTP_PROXY_SCHEMA "org.gnome.system.proxy.http"
#define HTTP_PROXY_HOST_KEY "host"
#define HTTP_PROXY_PORT_KEY "port"
#define HTTP_USE_AUTH_KEY "use-authentication"
#define HTTP_AUTH_USER_KEY "authentication-user"
#define HTTP_AUTH_PASSWD_KEY "authentication-password"
#define HTTPS_PROXY_SCHEMA "org.gnome.system.proxy.https"
#define SECURE_PROXY_HOST_KEY "host"
#define SECURE_PROXY_PORT_KEY "port"
#define FTP_PROXY_SCHEMA "org.gnome.system.proxy.ftp"
#define FTP_PROXY_HOST_KEY "host"
#define FTP_PROXY_PORT_KEY "port"
#define SOCKS_PROXY_SCHEMA "org.gnome.system.proxy.socks"
#define SOCKS_PROXY_HOST_KEY "host"
#define SOCKS_PROXY_PORT_KEY "port"
Enumerations
enum GDesktopProxyMode { G_DESKTOP_PROXY_MODE_NONE , G_DESKTOP_PROXY_MODE_MANUAL , G_DESKTOP_PROXY_MODE_AUTO }
enum { COL_NAME , COL_STYLE }
Functions
int main (int argc, char **argv)
Macro Definition Documentation
FTP_PROXY_HOST_KEY
#define FTP_PROXY_HOST_KEY "host"
Definition at line 77 of file mate-network-properties.c.
FTP_PROXY_PORT_KEY
#define FTP_PROXY_PORT_KEY "port"
Definition at line 78 of file mate-network-properties.c.
FTP_PROXY_SCHEMA
#define FTP_PROXY_SCHEMA "org.gnome.system.proxy.ftp"
Definition at line 76 of file mate-network-properties.c.
Referenced by main().
HTTP_AUTH_PASSWD_KEY
#define HTTP_AUTH_PASSWD_KEY "authentication-password"
Definition at line 70 of file mate-network-properties.c.
HTTP_AUTH_USER_KEY
#define HTTP_AUTH_USER_KEY "authentication-user"
Definition at line 69 of file mate-network-properties.c.
HTTP_PROXY_HOST_KEY
#define HTTP_PROXY_HOST_KEY "host"
Definition at line 66 of file mate-network-properties.c.
HTTP_PROXY_PORT_KEY
#define HTTP_PROXY_PORT_KEY "port"
Definition at line 67 of file mate-network-properties.c.
HTTP_PROXY_SCHEMA
#define HTTP_PROXY_SCHEMA "org.gnome.system.proxy.http"
Definition at line 65 of file mate-network-properties.c.
Referenced by main().
HTTP_USE_AUTH_KEY
#define HTTP_USE_AUTH_KEY "use-authentication"
Definition at line 68 of file mate-network-properties.c.
HTTPS_PROXY_SCHEMA
#define HTTPS_PROXY_SCHEMA "org.gnome.system.proxy.https"
Definition at line 72 of file mate-network-properties.c.
Referenced by main().
IGNORE_HOSTS_KEY
#define IGNORE_HOSTS_KEY "ignore-hosts"
Definition at line 63 of file mate-network-properties.c.
PROXY_AUTOCONFIG_URL_KEY
#define PROXY_AUTOCONFIG_URL_KEY "autoconfig-url"
Definition at line 62 of file mate-network-properties.c.
PROXY_MODE_KEY
#define PROXY_MODE_KEY "mode"
Definition at line 61 of file mate-network-properties.c.
PROXY_SCHEMA
#define PROXY_SCHEMA "org.gnome.system.proxy"
Definition at line 60 of file mate-network-properties.c.
Referenced by main().
SECURE_PROXY_HOST_KEY
#define SECURE_PROXY_HOST_KEY "host"
Definition at line 73 of file mate-network-properties.c.
SECURE_PROXY_PORT_KEY
#define SECURE_PROXY_PORT_KEY "port"
Definition at line 74 of file mate-network-properties.c.
SOCKS_PROXY_HOST_KEY
#define SOCKS_PROXY_HOST_KEY "host"
Definition at line 81 of file mate-network-properties.c.
SOCKS_PROXY_PORT_KEY
#define SOCKS_PROXY_PORT_KEY "port"
Definition at line 82 of file mate-network-properties.c.
SOCKS_PROXY_SCHEMA
#define SOCKS_PROXY_SCHEMA "org.gnome.system.proxy.socks"
Definition at line 80 of file mate-network-properties.c.
Referenced by main().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COL_NAME
COL_STYLE
Definition at line 55 of file mate-network-properties.c.
GDesktopProxyMode
enum GDesktopProxyMode
Enumerator
G_DESKTOP_PROXY_MODE_NONE
G_DESKTOP_PROXY_MODE_MANUAL
G_DESKTOP_PROXY_MODE_AUTO
Definition at line 48 of file mate-network-properties.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 452 of file mate-network-properties.c.
References capplet_init(), capplet_notebook_scroll_event_cb(), capplet_set_icon(), error, FTP_PROXY_SCHEMA, HTTP_PROXY_SCHEMA, HTTPS_PROXY_SCHEMA, NULL, PROXY_SCHEMA, and SOCKS_PROXY_SCHEMA.