MATE Desktop Environment: applet.c File Reference
applet.c File Reference
#include <config.h>
#include <string.h>
#include <signal.h>
#include <unistd.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <libpanel-util/panel-show.h>
#include <libpanel-util/panel-gtk.h>
#include "button-widget.h"
#include "drawer.h"
#include "launcher.h"
#include "panel-addto.h"
#include "panel-config-global.h"
#include "panel-applet-frame.h"
#include "panel-action-button.h"
#include "panel-menu-bar.h"
#include "panel-separator.h"
#include "panel-toplevel.h"
#include "panel-util.h"
#include "panel-profile.h"
#include "panel-menu-button.h"
#include "panel-globals.h"
#include "panel-properties-dialog.h"
#include "panel-lockdown.h"
#include "panel-schemas.h"
Macros
#define UNHIDE_TOPLEVELS_TIMEOUT_SECONDS 5
Functions
gboolean mate_panel_applet_toggle_locked (AppletInfo *info)
void mate_panel_applet_clean (AppletInfo *info)
AppletUserMenu * mate_panel_applet_get_callback (GList *user_menu, const char *name)
void mate_panel_applet_add_callback (AppletInfo *info, const char *callback_name, const char *icon_name, const char *menuitem_text, CallbackEnabledFunc is_enabled_func)
void mate_panel_applet_clear_user_menu (AppletInfo *info)
GtkWidget * mate_panel_applet_create_menu (AppletInfo *info)
void mate_panel_applet_menu_set_recurse (GtkMenu *menu, const gchar *key, gpointer data)
gboolean mate_panel_applet_on_load_queue (const char *id)
void mate_panel_applet_stop_loading (const char *id)
void mate_panel_applet_queue_applet_to_load (const char *id, PanelObjectType type, const char *toplevel_id, int position, gboolean right_stick, gboolean locked)
void mate_panel_applet_load_queued_applets (gboolean initial_load)
void mate_panel_applet_save_position (AppletInfo *applet_info, const char *id, gboolean immediate)
const char * mate_panel_applet_get_id (AppletInfo *info)
const char * mate_panel_applet_get_id_by_widget (GtkWidget *applet_widget)
AppletInfo * mate_panel_applet_get_by_id (const char *id)
GSList * mate_panel_applet_list_applets (void)
AppletInfo * mate_panel_applet_get_by_type (PanelObjectType object_type, GdkScreen *screen)
AppletInfo * mate_panel_applet_register (GtkWidget *applet, gpointer data, GDestroyNotify data_destroy, PanelWidget *panel, gboolean locked, gint pos, gboolean exactpos, PanelObjectType type, const char *id)
int mate_panel_applet_get_position (AppletInfo *applet)
gboolean mate_panel_applet_can_freely_move (AppletInfo *applet)
gboolean mate_panel_applet_lockable (AppletInfo *applet)
Macro Definition Documentation
UNHIDE_TOPLEVELS_TIMEOUT_SECONDS
#define UNHIDE_TOPLEVELS_TIMEOUT_SECONDS 5
Definition at line 781 of file mate-panel/mate-panel/applet.c.
Referenced by mate_panel_applet_load_queued_applets().
Function Documentation
mate_panel_applet_add_callback()
void mate_panel_applet_add_callback (AppletInfo * info, const char * callback_name, const char * icon_name, const char * menuitem_text, CallbackEnabledFunc is_enabled_func)
Definition at line 342 of file mate-panel/mate-panel/applet.c.
References AppletUserMenu::gicon, AppletUserMenu::info, AppletUserMenu::is_enabled_func, mate_panel_applet_get_callback(), AppletUserMenu::menuitem, AppletUserMenu::name, NULL, panel_gicon_from_icon_name(), AppletUserMenu::sensitive, AppletUserMenu::submenu, AppletUserMenu::text, and TRUE.
mate_panel_applet_can_freely_move()
gboolean mate_panel_applet_can_freely_move (AppletInfo * applet)
Definition at line 1353 of file mate-panel/mate-panel/applet.c.
References FALSE, panel_lockdown_get_locked_down(), PANEL_OBJECT_PANEL_RIGHT_STICK_KEY, PANEL_OBJECT_POSITION_KEY, PANEL_OBJECT_TOPLEVEL_ID_KEY, AppletInfo::settings, and TRUE.
Referenced by mate_panel_applet_create_menu(), and mate_panel_applet_frame_sync_menu_state().
mate_panel_applet_clean()
void mate_panel_applet_clean (AppletInfo * info)
Definition at line 147 of file mate-panel/mate-panel/applet.c.
References NULL, panel_launcher_delete(), and PANEL_OBJECT_LAUNCHER.
mate_panel_applet_clear_user_menu()
void mate_panel_applet_clear_user_menu (AppletInfo * info)
Definition at line 370 of file mate-panel/mate-panel/applet.c.
References AppletUserMenu::gicon, AppletUserMenu::name, NULL, and AppletUserMenu::text.
mate_panel_applet_create_menu()
GtkWidget * mate_panel_applet_create_menu (AppletInfo * info)
Definition at line 494 of file mate-panel/mate-panel/applet.c.
References _, FALSE, AppletUserMenu::is_enabled_func, mate_panel_applet_can_freely_move(), mate_panel_applet_lockable(), AppletUserMenu::name, NULL, panel_check_menu_item_new(), panel_image_menu_item_new_from_icon(), panel_lockdown_get_locked_down(), panel_profile_id_lists_are_writable(), panel_widget_get_applet_locked(), and TRUE.
Referenced by panel_context_menu_create().
mate_panel_applet_get_by_id()
AppletInfo * mate_panel_applet_get_by_id (const char * id)
Definition at line 1182 of file mate-panel/mate-panel/applet.c.
References AppletInfo::data, and NULL.
mate_panel_applet_get_by_type()
AppletInfo * mate_panel_applet_get_by_type (PanelObjectType object_type, GdkScreen * screen)
Definition at line 1203 of file mate-panel/mate-panel/applet.c.
References AppletInfo::data, and NULL.
mate_panel_applet_get_callback()
AppletUserMenu * mate_panel_applet_get_callback (GList * user_menu, const char * name)
Definition at line 326 of file mate-panel/mate-panel/applet.c.
References AppletUserMenu::name, name, and NULL.
Referenced by launcher_load_from_gsettings(), and mate_panel_applet_add_callback().
mate_panel_applet_get_id()
const char * mate_panel_applet_get_id (AppletInfo * info)
Definition at line 1155 of file mate-panel/mate-panel/applet.c.
References NULL.
Referenced by panel_profile_delete_object().
mate_panel_applet_get_id_by_widget()
const char * mate_panel_applet_get_id_by_widget (GtkWidget * applet_widget)
Definition at line 1164 of file mate-panel/mate-panel/applet.c.
References AppletInfo::data, and NULL.
Referenced by panel_profile_get_attached_object_settings().
mate_panel_applet_get_position()
int mate_panel_applet_get_position (AppletInfo * applet)
Definition at line 1340 of file mate-panel/mate-panel/applet.c.
References MATE_PANEL_APPLET_DATA, NULL, _AppletData::pos, and AppletInfo::widget.
Referenced by mate_panel_applet_save_position().
mate_panel_applet_list_applets()
GSList * mate_panel_applet_list_applets (void)
Definition at line 1197 of file mate-panel/mate-panel/applet.c.
Referenced by find_launcher(), and panel_find_applet_index().
mate_panel_applet_load_queued_applets()
void mate_panel_applet_load_queued_applets (gboolean initial_load)
Definition at line 1013 of file mate-panel/mate-panel/applet.c.
References NULL, TRUE, and UNHIDE_TOPLEVELS_TIMEOUT_SECONDS.
Referenced by panel_profile_load().
mate_panel_applet_lockable()
gboolean mate_panel_applet_lockable (AppletInfo * applet)
Definition at line 1371 of file mate-panel/mate-panel/applet.c.
References FALSE, panel_lockdown_get_locked_down(), PANEL_OBJECT_LOCKED_KEY, and AppletInfo::settings.
Referenced by mate_panel_applet_create_menu(), and mate_panel_applet_frame_sync_menu_state().
mate_panel_applet_menu_set_recurse()
void mate_panel_applet_menu_set_recurse (GtkMenu * menu, const gchar * key, gpointer data)
Definition at line 614 of file mate-panel/mate-panel/applet.c.
References data, key, and mate_panel_applet_menu_set_recurse().
Referenced by mate_panel_applet_menu_set_recurse(), panel_desktop_menu_item_set_panel(), and panel_place_menu_item_set_panel().
mate_panel_applet_on_load_queue()
gboolean mate_panel_applet_on_load_queue (const char * id)
Definition at line 795 of file mate-panel/mate-panel/applet.c.
References FALSE, NULL, and TRUE.
mate_panel_applet_queue_applet_to_load()
void mate_panel_applet_queue_applet_to_load (const char * id, PanelObjectType type, const char * toplevel_id, int position, gboolean right_stick, gboolean locked)
Definition at line 972 of file mate-panel/mate-panel/applet.c.
References FALSE.
mate_panel_applet_register()
AppletInfo * mate_panel_applet_register (GtkWidget * applet, gpointer data, GDestroyNotify data_destroy, PanelWidget * panel, gboolean locked, gint pos, gboolean exactpos, PanelObjectType type, const char * id)
Definition at line 1223 of file mate-panel/mate-panel/applet.c.
References _, APPLET_EVENT_MASK, back_change(), BUTTON_IS_WIDGET, data, _PanelWidget::master_widget, MATE_PANEL_APPLET_ASSOC_PANEL_KEY, MATE_PANEL_APPLET_FORBIDDEN_PANELS, NULL, orientation_change(), panel_lockdown_notify_add(), PANEL_OBJECT_APPLET, PANEL_OBJECT_DRAWER, PANEL_OBJECT_LOCKED_KEY, PANEL_OBJECT_PATH, PANEL_OBJECT_SCHEMA, panel_profile_delete_object(), panel_toplevel_get_panel_widget(), PANEL_WIDGET, panel_widget_add(), panels, size_change(), Drawer::toplevel, and TRUE.
Referenced by _mate_panel_applet_frame_activated(), and panel_separator_load_from_gsettings().
mate_panel_applet_save_position()
void mate_panel_applet_save_position (AppletInfo * applet_info, const char * id, gboolean immediate)
Definition at line 1084 of file mate-panel/mate-panel/applet.c.
References mate_panel_applet_get_position(), NULL, _PanelWidget::packed, panel_is_applet_right_stick(), PANEL_OBJECT_LOCKED_KEY, PANEL_OBJECT_PANEL_RIGHT_STICK_KEY, PANEL_OBJECT_POSITION_KEY, PANEL_OBJECT_TOPLEVEL_ID_KEY, panel_widget_get_applet_locked(), AppletInfo::settings, _PanelWidget::size, and AppletInfo::widget.
Referenced by mate_panel_applet_toggle_locked().
mate_panel_applet_stop_loading()
void mate_panel_applet_stop_loading (const char * id)
Definition at line 829 of file mate-panel/mate-panel/applet.c.
References NULL.
Referenced by _mate_panel_applet_frame_activated(), and mate_panel_applet_frame_load_from_gsettings().
mate_panel_applet_toggle_locked()
gboolean mate_panel_applet_toggle_locked (AppletInfo * info)
Definition at line 86 of file mate-panel/mate-panel/applet.c.
References mate_panel_applet_save_position(), panel_widget_toggle_applet_locked(), and TRUE.
Referenced by _mate_panel_applet_frame_applet_lock().