MATE Desktop Environment: msd-osd-window.c File Reference
msd-osd-window.c File Reference
#include "config.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
#include "msd-osd-window.h"
Macros
#define DIALOG_TIMEOUT 2000 /* dialog timeout in ms */
#define DIALOG_FADE_TIMEOUT 1500 /* timeout before fade starts */
#define FADE_TIMEOUT 10 /* timeout in ms between each frame of the fade */
#define BG_ALPHA 0.75
Enumerations
enum { DRAW_WHEN_COMPOSITED , LAST_SIGNAL }
Functions
gboolean msd_osd_window_is_composited (MsdOsdWindow *window)
gboolean msd_osd_window_is_valid (MsdOsdWindow *window)
GtkWidget * msd_osd_window_new (void)
void msd_osd_window_update_and_hide (MsdOsdWindow *window)
Macro Definition Documentation
BG_ALPHA
#define BG_ALPHA 0.75
Definition at line 47 of file mate-power-manager/src/msd-osd-window.c.
DIALOG_FADE_TIMEOUT
#define DIALOG_FADE_TIMEOUT 1500 /* timeout before fade starts */
Definition at line 44 of file mate-power-manager/src/msd-osd-window.c.
DIALOG_TIMEOUT
#define DIALOG_TIMEOUT 2000 /* dialog timeout in ms */
Definition at line 43 of file mate-power-manager/src/msd-osd-window.c.
FADE_TIMEOUT
#define FADE_TIMEOUT 10 /* timeout in ms between each frame of the fade */
Definition at line 45 of file mate-power-manager/src/msd-osd-window.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DRAW_WHEN_COMPOSITED
LAST_SIGNAL
Definition at line 58 of file mate-power-manager/src/msd-osd-window.c.
Function Documentation
msd_osd_window_is_composited()
gboolean msd_osd_window_is_composited (MsdOsdWindow * window)
msd_osd_window_is_composited: @window: a MsdOsdWindow
Return value: whether the window was created on a composited screen.
Definition at line 415 of file mate-power-manager/src/msd-osd-window.c.
msd_osd_window_is_valid()
gboolean msd_osd_window_is_valid (MsdOsdWindow * window)
msd_osd_window_is_valid: @window: a MsdOsdWindow
Return value: TRUE if the @window's idea of being composited matches whether its current screen is actually composited and whether the scale factor has not changed since last draw.
Definition at line 429 of file mate-power-manager/src/msd-osd-window.c.
msd_osd_window_new()
GtkWidget * msd_osd_window_new (void)
Definition at line 475 of file mate-power-manager/src/msd-osd-window.c.
References MSD_TYPE_OSD_WINDOW, and NULL.
msd_osd_window_update_and_hide()
void msd_osd_window_update_and_hide (MsdOsdWindow * window)
msd_osd_window_update_and_hide: @window: a MsdOsdWindow
Queues the @window for immediate drawing, and queues a timer to hide the window.
Definition at line 487 of file mate-power-manager/src/msd-osd-window.c.
Referenced by msd_media_keys_window_set_action(), msd_media_keys_window_set_action_custom(), and msd_media_keys_window_set_action_custom().