MATE Desktop Environment: matemixer-backend.c File Reference
matemixer-backend.c File Reference
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include "matemixer-backend.h"
#include "matemixer-device.h"
#include "matemixer-enums.h"
#include "matemixer-enum-types.h"
#include "matemixer-stream.h"
#include "matemixer-stream-control.h"
#include "matemixer-stored-control.h"
Enumerations
enum {
PROP_0 , PROP_STATE , PROP_DEFAULT_INPUT_STREAM , PROP_DEFAULT_OUTPUT_STREAM ,
N_PROPERTIES
}
enum {
DEVICE_ADDED , DEVICE_REMOVED , STREAM_ADDED , STREAM_REMOVED ,
STORED_CONTROL_ADDED , STORED_CONTROL_REMOVED , N_SIGNALS
}
Functions
void mate_mixer_backend_set_app_info (MateMixerBackend *backend, MateMixerAppInfo *info)
void mate_mixer_backend_set_server_address (MateMixerBackend *backend, const gchar *address)
gboolean mate_mixer_backend_open (MateMixerBackend *backend)
void mate_mixer_backend_close (MateMixerBackend *backend)
MateMixerState mate_mixer_backend_get_state (MateMixerBackend *backend)
MateMixerDevice * mate_mixer_backend_get_device (MateMixerBackend *backend, const gchar *name)
MateMixerStream * mate_mixer_backend_get_stream (MateMixerBackend *backend, const gchar *name)
MateMixerStoredControl * mate_mixer_backend_get_stored_control (MateMixerBackend *backend, const gchar *name)
const GList * mate_mixer_backend_list_devices (MateMixerBackend *backend)
const GList * mate_mixer_backend_list_streams (MateMixerBackend *backend)
const GList * mate_mixer_backend_list_stored_controls (MateMixerBackend *backend)
MateMixerStream * mate_mixer_backend_get_default_input_stream (MateMixerBackend *backend)
gboolean mate_mixer_backend_set_default_input_stream (MateMixerBackend *backend, MateMixerStream *stream)
MateMixerStream * mate_mixer_backend_get_default_output_stream (MateMixerBackend *backend)
gboolean mate_mixer_backend_set_default_output_stream (MateMixerBackend *backend, MateMixerStream *stream)
void _mate_mixer_backend_set_state (MateMixerBackend *backend, MateMixerState state)
void _mate_mixer_backend_set_default_input_stream (MateMixerBackend *backend, MateMixerStream *stream)
void _mate_mixer_backend_set_default_output_stream (MateMixerBackend *backend, MateMixerStream *stream)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DEVICE_ADDED
DEVICE_REMOVED
STREAM_ADDED
STREAM_REMOVED
STORED_CONTROL_ADDED
STORED_CONTROL_REMOVED
N_SIGNALS
Definition at line 49 of file matemixer-backend.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_STATE
PROP_DEFAULT_INPUT_STREAM
PROP_DEFAULT_OUTPUT_STREAM
N_PROPERTIES
Definition at line 39 of file matemixer-backend.c.
Function Documentation
_mate_mixer_backend_set_default_input_stream()
void _mate_mixer_backend_set_default_input_stream (MateMixerBackend * backend, MateMixerStream * stream)
Definition at line 609 of file matemixer-backend.c.
References MATE_MIXER_IS_BACKEND, MATE_MIXER_IS_STREAM, mate_mixer_stream_get_name(), NULL, _MateMixerBackend::priv, and PROP_DEFAULT_INPUT_STREAM.
Referenced by mate_mixer_backend_set_default_input_stream().
_mate_mixer_backend_set_default_output_stream()
void _mate_mixer_backend_set_default_output_stream (MateMixerBackend * backend, MateMixerStream * stream)
Definition at line 634 of file matemixer-backend.c.
References MATE_MIXER_IS_BACKEND, MATE_MIXER_IS_STREAM, mate_mixer_stream_get_name(), NULL, _MateMixerBackend::priv, and PROP_DEFAULT_OUTPUT_STREAM.
Referenced by mate_mixer_backend_set_default_output_stream().
_mate_mixer_backend_set_state()
void _mate_mixer_backend_set_state (MateMixerBackend * backend, MateMixerState state)
Definition at line 596 of file matemixer-backend.c.
References MATE_MIXER_IS_BACKEND, _MateMixerBackend::priv, and PROP_STATE.
Referenced by alsa_backend_close().
mate_mixer_backend_close()
void mate_mixer_backend_close (MateMixerBackend * backend)
Definition at line 331 of file matemixer-backend.c.
References _MateMixerBackendClass::close, MATE_MIXER_BACKEND_GET_CLASS, MATE_MIXER_IS_BACKEND, and NULL.
mate_mixer_backend_get_default_input_stream()
MateMixerStream * mate_mixer_backend_get_default_input_stream (MateMixerBackend * backend)
Definition at line 457 of file matemixer-backend.c.
References MATE_MIXER_IS_BACKEND, NULL, and _MateMixerBackend::priv.
Referenced by mate_mixer_context_get_default_input_stream().
mate_mixer_backend_get_default_output_stream()
MateMixerStream * mate_mixer_backend_get_default_output_stream (MateMixerBackend * backend)
Definition at line 492 of file matemixer-backend.c.
References MATE_MIXER_IS_BACKEND, NULL, and _MateMixerBackend::priv.
Referenced by mate_mixer_context_get_default_output_stream().
mate_mixer_backend_get_device()
MateMixerDevice * mate_mixer_backend_get_device (MateMixerBackend * backend, const gchar * name)
Definition at line 352 of file matemixer-backend.c.
References mate_mixer_backend_list_devices(), MATE_MIXER_DEVICE, mate_mixer_device_get_name(), MATE_MIXER_IS_BACKEND, name, and NULL.
Referenced by mate_mixer_context_get_device().
mate_mixer_backend_get_state()
MateMixerState mate_mixer_backend_get_state (MateMixerBackend * backend)
Definition at line 344 of file matemixer-backend.c.
References MATE_MIXER_IS_BACKEND, MATE_MIXER_STATE_UNKNOWN, and _MateMixerBackend::priv.
Referenced by mate_mixer_context_open().
mate_mixer_backend_get_stored_control()
MateMixerStoredControl * mate_mixer_backend_get_stored_control (MateMixerBackend * backend, const gchar * name)
Definition at line 392 of file matemixer-backend.c.
References mate_mixer_backend_list_stored_controls(), MATE_MIXER_IS_BACKEND, MATE_MIXER_STORED_CONTROL, MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), name, and NULL.
Referenced by mate_mixer_context_get_stored_control().
mate_mixer_backend_get_stream()
MateMixerStream * mate_mixer_backend_get_stream (MateMixerBackend * backend, const gchar * name)
Definition at line 372 of file matemixer-backend.c.
References mate_mixer_backend_list_streams(), MATE_MIXER_IS_BACKEND, MATE_MIXER_STREAM, mate_mixer_stream_get_name(), name, and NULL.
Referenced by mate_mixer_context_get_stream().
mate_mixer_backend_list_devices()
const GList * mate_mixer_backend_list_devices (MateMixerBackend * backend)
Definition at line 412 of file matemixer-backend.c.
References _MateMixerBackendClass::list_devices, MATE_MIXER_BACKEND_GET_CLASS, MATE_MIXER_IS_BACKEND, and NULL.
Referenced by mate_mixer_backend_get_device(), and mate_mixer_context_list_devices().
mate_mixer_backend_list_stored_controls()
const GList * mate_mixer_backend_list_stored_controls (MateMixerBackend * backend)
Definition at line 442 of file matemixer-backend.c.
References _MateMixerBackendClass::list_stored_controls, MATE_MIXER_BACKEND_GET_CLASS, MATE_MIXER_IS_BACKEND, and NULL.
Referenced by mate_mixer_backend_get_stored_control(), and mate_mixer_context_list_stored_controls().
mate_mixer_backend_list_streams()
const GList * mate_mixer_backend_list_streams (MateMixerBackend * backend)
Definition at line 427 of file matemixer-backend.c.
References _MateMixerBackendClass::list_streams, MATE_MIXER_BACKEND_GET_CLASS, MATE_MIXER_IS_BACKEND, and NULL.
Referenced by mate_mixer_backend_get_stream(), and mate_mixer_context_list_streams().
mate_mixer_backend_open()
gboolean mate_mixer_backend_open (MateMixerBackend * backend)
Definition at line 322 of file matemixer-backend.c.
References FALSE, MATE_MIXER_BACKEND_GET_CLASS, and MATE_MIXER_IS_BACKEND.
Referenced by mate_mixer_context_open().
mate_mixer_backend_set_app_info()
void mate_mixer_backend_set_app_info (MateMixerBackend * backend, MateMixerAppInfo * info)
Definition at line 296 of file matemixer-backend.c.
References MATE_MIXER_BACKEND_GET_CLASS, MATE_MIXER_IS_BACKEND, NULL, and _MateMixerBackendClass::set_app_info.
Referenced by mate_mixer_context_open().
mate_mixer_backend_set_default_input_stream()
gboolean mate_mixer_backend_set_default_input_stream (MateMixerBackend * backend, MateMixerStream * stream)
Definition at line 465 of file matemixer-backend.c.
References _mate_mixer_backend_set_default_input_stream(), FALSE, MATE_MIXER_BACKEND_GET_CLASS, MATE_MIXER_DIRECTION_INPUT, MATE_MIXER_IS_BACKEND, MATE_MIXER_IS_STREAM, mate_mixer_stream_get_direction(), NULL, _MateMixerBackend::priv, _MateMixerBackendClass::set_default_input_stream, and TRUE.
Referenced by mate_mixer_context_set_default_input_stream().
mate_mixer_backend_set_default_output_stream()
gboolean mate_mixer_backend_set_default_output_stream (MateMixerBackend * backend, MateMixerStream * stream)
Definition at line 500 of file matemixer-backend.c.
References _mate_mixer_backend_set_default_output_stream(), FALSE, MATE_MIXER_BACKEND_GET_CLASS, MATE_MIXER_DIRECTION_OUTPUT, MATE_MIXER_IS_BACKEND, MATE_MIXER_IS_STREAM, mate_mixer_stream_get_direction(), NULL, _MateMixerBackend::priv, _MateMixerBackendClass::set_default_output_stream, and TRUE.
Referenced by mate_mixer_context_set_default_output_stream().
mate_mixer_backend_set_server_address()
void mate_mixer_backend_set_server_address (MateMixerBackend * backend, const gchar * address)
Definition at line 309 of file matemixer-backend.c.
References MATE_MIXER_BACKEND_GET_CLASS, MATE_MIXER_IS_BACKEND, NULL, and _MateMixerBackendClass::set_server_address.
Referenced by mate_mixer_context_open().