MATE Desktop Environment: matemixer-private.h File Reference
matemixer-private.h File Reference
#include <glib.h>
#include "matemixer-enums.h"
#include "matemixer-app-info-private.h"
#include "matemixer-backend.h"
#include "matemixer-backend-module.h"
#include "matemixer-stream-private.h"
#include "matemixer-stream-control-private.h"
#include "matemixer-switch-private.h"
#include "matemixer-switch-option-private.h"
Macros
#define MATE_MIXER_IS_LEFT_CHANNEL(c)
#define MATE_MIXER_IS_RIGHT_CHANNEL(c)
#define MATE_MIXER_IS_FRONT_CHANNEL(c)
#define MATE_MIXER_IS_BACK_CHANNEL(c)
#define MATE_MIXER_CHANNEL_MASK_LEFT
#define MATE_MIXER_CHANNEL_MASK_RIGHT
#define MATE_MIXER_CHANNEL_MASK_FRONT
#define MATE_MIXER_CHANNEL_MASK_BACK
#define MATE_MIXER_CHANNEL_MASK_HAS_CHANNEL(m, c)
#define MATE_MIXER_CHANNEL_MASK_HAS_LEFT(m)
#define MATE_MIXER_CHANNEL_MASK_HAS_RIGHT(m)
#define MATE_MIXER_CHANNEL_MASK_HAS_FRONT(m)
#define MATE_MIXER_CHANNEL_MASK_HAS_BACK(m)
Functions
const GList * _mate_mixer_list_modules (void)
guint32 _mate_mixer_create_channel_mask (MateMixerChannelPosition *positions, guint n)
Macro Definition Documentation
MATE_MIXER_CHANNEL_MASK_BACK
#define MATE_MIXER_CHANNEL_MASK_BACK
Value:
((1 << MATE_MIXER_CHANNEL_BACK_LEFT) |              \
 (1 << MATE_MIXER_CHANNEL_BACK_RIGHT) |             \
 (1 << MATE_MIXER_CHANNEL_BACK_CENTER) |            \
 (1 << MATE_MIXER_CHANNEL_TOP_BACK_LEFT) |          \
 (1 << MATE_MIXER_CHANNEL_TOP_BACK_RIGHT) |         \
 (1 << MATE_MIXER_CHANNEL_TOP_BACK_CENTER))
Definition at line 95 of file matemixer-private.h.
MATE_MIXER_CHANNEL_MASK_FRONT
#define MATE_MIXER_CHANNEL_MASK_FRONT
Value:
((1 << MATE_MIXER_CHANNEL_FRONT_LEFT) |             \
 (1 << MATE_MIXER_CHANNEL_FRONT_RIGHT) |            \
 (1 << MATE_MIXER_CHANNEL_FRONT_CENTER) |           \
 (1 << MATE_MIXER_CHANNEL_FRONT_LEFT_CENTER) |      \
 (1 << MATE_MIXER_CHANNEL_FRONT_RIGHT_CENTER) |     \
 (1 << MATE_MIXER_CHANNEL_TOP_FRONT_LEFT) |         \
 (1 << MATE_MIXER_CHANNEL_TOP_FRONT_RIGHT) |        \
 (1 << MATE_MIXER_CHANNEL_TOP_FRONT_CENTER))
Definition at line 85 of file matemixer-private.h.
MATE_MIXER_CHANNEL_MASK_HAS_BACK
#define MATE_MIXER_CHANNEL_MASK_HAS_BACK (m)
Value:
((m) & MATE_MIXER_CHANNEL_MASK_BACK)
Definition at line 107 of file matemixer-private.h.
Referenced by alsa_stream_control_set_data().
MATE_MIXER_CHANNEL_MASK_HAS_CHANNEL
#define MATE_MIXER_CHANNEL_MASK_HAS_CHANNEL (m, c)
Value:
((m) & (1 << (c)))
Definition at line 103 of file matemixer-private.h.
MATE_MIXER_CHANNEL_MASK_HAS_FRONT
#define MATE_MIXER_CHANNEL_MASK_HAS_FRONT (m)
Value:
((m) & MATE_MIXER_CHANNEL_MASK_FRONT)
Definition at line 106 of file matemixer-private.h.
Referenced by alsa_stream_control_set_data().
MATE_MIXER_CHANNEL_MASK_HAS_LEFT
#define MATE_MIXER_CHANNEL_MASK_HAS_LEFT (m)
Value:
((m) & MATE_MIXER_CHANNEL_MASK_LEFT)
Definition at line 104 of file matemixer-private.h.
Referenced by alsa_stream_control_set_data().
MATE_MIXER_CHANNEL_MASK_HAS_RIGHT
#define MATE_MIXER_CHANNEL_MASK_HAS_RIGHT (m)
Value:
((m) & MATE_MIXER_CHANNEL_MASK_RIGHT)
Definition at line 105 of file matemixer-private.h.
Referenced by alsa_stream_control_set_data().
MATE_MIXER_CHANNEL_MASK_LEFT
#define MATE_MIXER_CHANNEL_MASK_LEFT
Value:
((1 << MATE_MIXER_CHANNEL_FRONT_LEFT) |             \
 (1 << MATE_MIXER_CHANNEL_BACK_LEFT) |              \
 (1 << MATE_MIXER_CHANNEL_FRONT_LEFT_CENTER) |      \
 (1 << MATE_MIXER_CHANNEL_SIDE_LEFT) |              \
 (1 << MATE_MIXER_CHANNEL_TOP_FRONT_LEFT) |         \
 (1 << MATE_MIXER_CHANNEL_TOP_BACK_LEFT))
Definition at line 69 of file matemixer-private.h.
MATE_MIXER_CHANNEL_MASK_RIGHT
#define MATE_MIXER_CHANNEL_MASK_RIGHT
Value:
((1 << MATE_MIXER_CHANNEL_FRONT_RIGHT) |            \
 (1 << MATE_MIXER_CHANNEL_BACK_RIGHT) |             \
 (1 << MATE_MIXER_CHANNEL_FRONT_RIGHT_CENTER) |     \
 (1 << MATE_MIXER_CHANNEL_SIDE_RIGHT) |             \
 (1 << MATE_MIXER_CHANNEL_TOP_FRONT_RIGHT) |        \
 (1 << MATE_MIXER_CHANNEL_TOP_BACK_RIGHT))
Definition at line 77 of file matemixer-private.h.
MATE_MIXER_IS_BACK_CHANNEL
#define MATE_MIXER_IS_BACK_CHANNEL (c)
Value:
((c) == MATE_MIXER_CHANNEL_BACK_LEFT ||             \
 (c) == MATE_MIXER_CHANNEL_BACK_RIGHT ||            \
 (c) == MATE_MIXER_CHANNEL_BACK_CENTER ||           \
 (c) == MATE_MIXER_CHANNEL_TOP_BACK_LEFT ||         \
 (c) == MATE_MIXER_CHANNEL_TOP_BACK_RIGHT ||        \
 (c) == MATE_MIXER_CHANNEL_TOP_BACK_CENTER)
Definition at line 61 of file matemixer-private.h.
MATE_MIXER_IS_FRONT_CHANNEL
#define MATE_MIXER_IS_FRONT_CHANNEL (c)
Value:
((c) == MATE_MIXER_CHANNEL_FRONT_LEFT ||            \
 (c) == MATE_MIXER_CHANNEL_FRONT_RIGHT ||           \
 (c) == MATE_MIXER_CHANNEL_FRONT_CENTER ||          \
 (c) == MATE_MIXER_CHANNEL_FRONT_LEFT_CENTER ||     \
 (c) == MATE_MIXER_CHANNEL_FRONT_RIGHT_CENTER ||    \
 (c) == MATE_MIXER_CHANNEL_TOP_FRONT_LEFT ||        \
 (c) == MATE_MIXER_CHANNEL_TOP_FRONT_RIGHT ||       \
 (c) == MATE_MIXER_CHANNEL_TOP_FRONT_CENTER)
Definition at line 51 of file matemixer-private.h.
MATE_MIXER_IS_LEFT_CHANNEL
#define MATE_MIXER_IS_LEFT_CHANNEL (c)
Value:
((c) == MATE_MIXER_CHANNEL_FRONT_LEFT ||            \
 (c) == MATE_MIXER_CHANNEL_BACK_LEFT ||             \
 (c) == MATE_MIXER_CHANNEL_FRONT_LEFT_CENTER ||     \
 (c) == MATE_MIXER_CHANNEL_SIDE_LEFT ||             \
 (c) == MATE_MIXER_CHANNEL_TOP_FRONT_LEFT ||        \
 (c) == MATE_MIXER_CHANNEL_TOP_BACK_LEFT)
Definition at line 35 of file matemixer-private.h.
MATE_MIXER_IS_RIGHT_CHANNEL
#define MATE_MIXER_IS_RIGHT_CHANNEL (c)
Value:
((c) == MATE_MIXER_CHANNEL_FRONT_RIGHT ||           \
 (c) == MATE_MIXER_CHANNEL_BACK_RIGHT ||            \
 (c) == MATE_MIXER_CHANNEL_FRONT_RIGHT_CENTER ||    \
 (c) == MATE_MIXER_CHANNEL_SIDE_RIGHT ||            \
 (c) == MATE_MIXER_CHANNEL_TOP_FRONT_RIGHT ||       \
 (c) == MATE_MIXER_CHANNEL_TOP_BACK_RIGHT)
Definition at line 43 of file matemixer-private.h.
Function Documentation
_mate_mixer_create_channel_mask()
guint32 _mate_mixer_create_channel_mask (MateMixerChannelPosition * positions, guint n)
_mate_mixer_create_channel_mask: @positions: an array of channel positions
: number of channel positions in the array
Creates a channel mask using the given list of channel positions.
Returns: a channel mask.
Definition at line 131 of file matemixer.c.
References mask, MATE_MIXER_CHANNEL_MAX, and MATE_MIXER_CHANNEL_UNKNOWN.
Referenced by alsa_stream_control_set_data().
_mate_mixer_list_modules()
const GList * _mate_mixer_list_modules (void)
_mate_mixer_list_modules:
Gets a list of loaded backend modules.
Returns: a #GList.
Definition at line 116 of file matemixer.c.
Referenced by mate_mixer_context_open(), and mate_mixer_context_set_backend_type().