MATE Desktop Environment: main.c File Reference
main.c File Reference
#include <config.h>
#include <signal.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <time.h>
#include <glib/gi18n.h>
#include <glib.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <dbus/dbus.h>
#include <dbus/dbus-glib.h>
#include <dbus/dbus-glib-bindings.h>
#include <dbus/dbus-glib-lowlevel.h>
#include "mdm-signal-handler.h"
#include "mdm-log.h"
#include "gsm-consolekit.h"
#include "gsm-util.h"
#include "gsm-manager.h"
#include "gsm-xsmp-server.h"
#include "gsm-store.h"
#include "msm-gnome.h"
Macros
#define GSM_SCHEMA "org.mate.session"
#define GSM_DEFAULT_SESSION_KEY "default-session"
#define GSM_REQUIRED_COMPONENTS_SCHEMA GSM_SCHEMA ".required-components"
#define GSM_REQUIRED_COMPONENTS_LIST_KEY "required-components-list"
#define ACCESSIBILITY_KEY "accessibility"
#define ACCESSIBILITY_SCHEMA "org.mate.interface"
#define DEBUG_SCHEMA "org.mate.debug"
#define DEBUG_KEY "mate-session"
#define VISUAL_SCHEMA "org.mate.applications-at-visual"
#define VISUAL_KEY "exec"
#define VISUAL_STARTUP_KEY "startup"
#define MOBILITY_SCHEMA "org.mate.applications-at-mobility"
#define MOBILITY_KEY "exec"
#define MOBILITY_STARTUP_KEY "startup"
#define MATE_INTERFACE_SCHEMA "org.mate.interface"
#define GTK_OVERLAY_SCROLL "gtk-overlay-scrolling"
#define GSM_DBUS_NAME "org.gnome.SessionManager"
#define KEY_AUTOSAVE "auto-save-session"
Functions
int main (int argc, char **argv)
Macro Definition Documentation
ACCESSIBILITY_KEY
#define ACCESSIBILITY_KEY "accessibility"
Definition at line 61 of file mate-session-manager/mate-session/main.c.
ACCESSIBILITY_SCHEMA
#define ACCESSIBILITY_SCHEMA "org.mate.interface"
Definition at line 62 of file mate-session-manager/mate-session/main.c.
DEBUG_KEY
#define DEBUG_KEY "mate-session"
Definition at line 65 of file mate-session-manager/mate-session/main.c.
Referenced by main(), and main().
DEBUG_SCHEMA
#define DEBUG_SCHEMA "org.mate.debug"
Definition at line 64 of file mate-session-manager/mate-session/main.c.
Referenced by main(), and main().
GSM_DBUS_NAME
#define GSM_DBUS_NAME "org.gnome.SessionManager"
Definition at line 78 of file mate-session-manager/mate-session/main.c.
GSM_DEFAULT_SESSION_KEY
#define GSM_DEFAULT_SESSION_KEY "default-session"
Definition at line 57 of file mate-session-manager/mate-session/main.c.
Referenced by main().
GSM_REQUIRED_COMPONENTS_LIST_KEY
#define GSM_REQUIRED_COMPONENTS_LIST_KEY "required-components-list"
Definition at line 59 of file mate-session-manager/mate-session/main.c.
GSM_REQUIRED_COMPONENTS_SCHEMA
#define GSM_REQUIRED_COMPONENTS_SCHEMA GSM_SCHEMA ".required-components"
Definition at line 58 of file mate-session-manager/mate-session/main.c.
GSM_SCHEMA
#define GSM_SCHEMA "org.mate.session"
Definition at line 56 of file mate-session-manager/mate-session/main.c.
Referenced by msm_gnome_start().
GTK_OVERLAY_SCROLL
#define GTK_OVERLAY_SCROLL "gtk-overlay-scrolling"
Definition at line 76 of file mate-session-manager/mate-session/main.c.
KEY_AUTOSAVE
#define KEY_AUTOSAVE "auto-save-session"
Definition at line 80 of file mate-session-manager/mate-session/main.c.
MATE_INTERFACE_SCHEMA
#define MATE_INTERFACE_SCHEMA "org.mate.interface"
Definition at line 75 of file mate-session-manager/mate-session/main.c.
MOBILITY_KEY
#define MOBILITY_KEY "exec"
Definition at line 72 of file mate-session-manager/mate-session/main.c.
MOBILITY_SCHEMA
#define MOBILITY_SCHEMA "org.mate.applications-at-mobility"
Definition at line 71 of file mate-session-manager/mate-session/main.c.
MOBILITY_STARTUP_KEY
#define MOBILITY_STARTUP_KEY "startup"
Definition at line 73 of file mate-session-manager/mate-session/main.c.
VISUAL_KEY
#define VISUAL_KEY "exec"
Definition at line 68 of file mate-session-manager/mate-session/main.c.
VISUAL_SCHEMA
#define VISUAL_SCHEMA "org.mate.applications-at-visual"
Definition at line 67 of file mate-session-manager/mate-session/main.c.
VISUAL_STARTUP_KEY
#define VISUAL_STARTUP_KEY "startup"
Definition at line 69 of file mate-session-manager/mate-session/main.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 595 of file mate-session-manager/mate-session/main.c.
References _, _gsm_manager_set_renderer(), ACCESSIBILITY_KEY, ACCESSIBILITY_SCHEMA, debug, DEBUG_KEY, DEBUG_SCHEMA, error, FALSE, GETTEXT_PACKAGE, GSM_DEFAULT_SESSION_KEY, gsm_manager_new(), gsm_manager_start(), gsm_store_new(), gsm_util_export_activation_environment(), gsm_util_init_error(), gsm_util_setenv(), gsm_xsmp_server_new(), gsm_xsmp_server_start(), mdm_log_init(), mdm_log_set_debug(), mdm_log_shutdown(), mdm_signal_handler_add(), mdm_signal_handler_add_fatal(), mdm_signal_handler_new(), mdm_signal_handler_set_fatal_func(), msm_gnome_start(), msm_gnome_stop(), N_, NULL, TRUE, and VERSION.