MATE Desktop Environment: mate-colorsel.c File Reference
mate-colorsel.c File Reference
#include "config.h"
#include "private.h"
#include <math.h>
#include <string.h>
#include <gdk/gdkx.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include "mate-colorsel.h"
#include "mate-hsv.h"
Macros
#define DEFAULT_COLOR_PALETTE "#ef2929:#fcaf3e:#fce94f:#8ae234:#729fcf:#ad7fa8:#e9b96e:#888a85:#eeeeec:#cc0000:#f57900:#edd400:#73d216:#3465a4:#75507b:#c17d11:#555753:#d3d7cf:#a40000:#ce5c00:#c4a000:#4e9a06:#204a87:#5c3566:#8f5902:#2e3436:#babdb6:#000000:#2e3436:#555753:#888a85:#babdb6:#d3d7cf:#eeeeec:#f3f3f3:#ffffff"
#define GTK_CUSTOM_PALETTE_WIDTH 9
#define GTK_CUSTOM_PALETTE_HEIGHT 4
#define SIZE_OF_COLOR_PALETTE (GTK_CUSTOM_PALETTE_WIDTH * GTK_CUSTOM_PALETTE_HEIGHT * 8)
#define CUSTOM_PALETTE_ENTRY_WIDTH 20
#define CUSTOM_PALETTE_ENTRY_HEIGHT 20
#define DROPPER_WIDTH 16
#define DROPPER_HEIGHT 16
#define DROPPER_STRIDE 64
#define DROPPER_X_HOT 2
#define DROPPER_Y_HOT 16
#define CHECK_SIZE 16
#define BIG_STEP 20
#define SCALE(i)
#define UNSCALE(d)
#define INTENSITY(r, g, b)
Enumerations
enum { COLOR_CHANGED , LAST_SIGNAL }
enum {
PROP_0 , PROP_HAS_PALETTE , PROP_HAS_OPACITY_CONTROL , PROP_CURRENT_RGBA ,
PROP_CURRENT_ALPHA , PROP_HEX_STRING
}
enum {
COLORSEL_RED = 0 , COLORSEL_GREEN = 1 , COLORSEL_BLUE = 2 , COLORSEL_OPACITY = 3 ,
COLORSEL_HUE , COLORSEL_SATURATION , COLORSEL_VALUE , COLORSEL_NUM_CHANNELS
}
Functions
GtkWidget * mate_color_selection_new (void)
gboolean mate_color_selection_get_has_opacity_control (MateColorSelection *colorsel)
void mate_color_selection_set_has_opacity_control (MateColorSelection *colorsel, gboolean has_opacity)
gboolean mate_color_selection_get_has_palette (MateColorSelection *colorsel)
void mate_color_selection_set_has_palette (MateColorSelection *colorsel, gboolean has_palette)
void mate_color_selection_set_current_rgba (MateColorSelection *colorsel, const GdkRGBA *rgba)
void mate_color_selection_set_current_alpha (MateColorSelection *colorsel, guint16 alpha)
void mate_color_selection_set_color (MateColorSelection *colorsel, gdouble *color)
void mate_color_selection_get_current_rgba (MateColorSelection *colorsel, GdkRGBA *color)
guint16 mate_color_selection_get_current_alpha (MateColorSelection *colorsel)
void mate_color_selection_get_color (MateColorSelection *colorsel, gdouble *color)
void mate_color_selection_set_previous_color (MateColorSelection *colorsel, const GdkRGBA *color)
void mate_color_selection_set_previous_alpha (MateColorSelection *colorsel, guint16 alpha)
void mate_color_selection_get_previous_color (MateColorSelection *colorsel, GdkRGBA *color)
guint16 mate_color_selection_get_previous_alpha (MateColorSelection *colorsel)
gboolean mate_color_selection_is_adjusting (MateColorSelection *colorsel)
gboolean mate_color_selection_palette_from_string (const gchar *str, GdkRGBA **colors, gint *n_colors)
gchar * mate_color_selection_palette_to_string (const GdkRGBA *colors, gint n_colors)
MateColorSelectionChangePaletteFunc mate_color_selection_set_change_palette_hook (MateColorSelectionChangePaletteFunc func)
MateColorSelectionChangePaletteWithScreenFunc mate_color_selection_set_change_palette_with_screen_hook (MateColorSelectionChangePaletteWithScreenFunc func)
Macro Definition Documentation
BIG_STEP
#define BIG_STEP 20
Definition at line 59 of file mate-colorsel.c.
CHECK_SIZE
#define CHECK_SIZE 16
Definition at line 58 of file mate-colorsel.c.
CUSTOM_PALETTE_ENTRY_HEIGHT
#define CUSTOM_PALETTE_ENTRY_HEIGHT 20
Definition at line 49 of file mate-colorsel.c.
CUSTOM_PALETTE_ENTRY_WIDTH
#define CUSTOM_PALETTE_ENTRY_WIDTH 20
Definition at line 48 of file mate-colorsel.c.
DEFAULT_COLOR_PALETTE
#define DEFAULT_COLOR_PALETTE "#ef2929:#fcaf3e:#fce94f:#8ae234:#729fcf:#ad7fa8:#e9b96e:#888a85:#eeeeec:#cc0000:#f57900:#edd400:#73d216:#3465a4:#75507b:#c17d11:#555753:#d3d7cf:#a40000:#ce5c00:#c4a000:#4e9a06:#204a87:#5c3566:#8f5902:#2e3436:#babdb6:#000000:#2e3436:#555753:#888a85:#babdb6:#d3d7cf:#eeeeec:#f3f3f3:#ffffff"
Definition at line 40 of file mate-colorsel.c.
DROPPER_HEIGHT
#define DROPPER_HEIGHT 16
Definition at line 53 of file mate-colorsel.c.
DROPPER_STRIDE
#define DROPPER_STRIDE 64
Definition at line 54 of file mate-colorsel.c.
DROPPER_WIDTH
#define DROPPER_WIDTH 16
Definition at line 52 of file mate-colorsel.c.
DROPPER_X_HOT
#define DROPPER_X_HOT 2
Definition at line 55 of file mate-colorsel.c.
DROPPER_Y_HOT
#define DROPPER_Y_HOT 16
Definition at line 56 of file mate-colorsel.c.
GTK_CUSTOM_PALETTE_HEIGHT
#define GTK_CUSTOM_PALETTE_HEIGHT 4
Definition at line 44 of file mate-colorsel.c.
GTK_CUSTOM_PALETTE_WIDTH
#define GTK_CUSTOM_PALETTE_WIDTH 9
Definition at line 43 of file mate-colorsel.c.
INTENSITY
#define INTENSITY (r, g, b)
Value:
((r) * 0.30 + (g) * 0.59 + (b) * 0.11)
Definition at line 66 of file mate-colorsel.c.
SCALE
#define SCALE (i)
Value:
(i / 65535.)
Definition at line 64 of file mate-colorsel.c.
Referenced by mate_color_selection_set_current_alpha(), and mate_color_selection_set_previous_alpha().
SIZE_OF_COLOR_PALETTE
#define SIZE_OF_COLOR_PALETTE (GTK_CUSTOM_PALETTE_WIDTH * GTK_CUSTOM_PALETTE_HEIGHT * 8)
Definition at line 46 of file mate-colorsel.c.
UNSCALE
#define UNSCALE (d)
Value:
((guint16)(d * 65535 + 0.5))
Definition at line 65 of file mate-colorsel.c.
Referenced by mate_color_selection_get_current_alpha(), and mate_color_selection_get_previous_alpha().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_HAS_PALETTE
PROP_HAS_OPACITY_CONTROL
PROP_CURRENT_RGBA
PROP_CURRENT_ALPHA
PROP_HEX_STRING
Definition at line 73 of file mate-colorsel.c.
anonymous enum
anonymous enum
Enumerator
COLOR_CHANGED
LAST_SIGNAL
Definition at line 68 of file mate-colorsel.c.
anonymous enum
anonymous enum
Enumerator
COLORSEL_RED
COLORSEL_GREEN
COLORSEL_BLUE
COLORSEL_OPACITY
COLORSEL_HUE
COLORSEL_SATURATION
COLORSEL_VALUE
COLORSEL_NUM_CHANNELS
Definition at line 82 of file mate-colorsel.c.
Function Documentation
mate_color_selection_get_color()
void mate_color_selection_get_color (MateColorSelection * colorsel, gdouble * color)
mate_color_selection_get_color: @colorsel: a MateColorSelection. @color: an array of 4 #gdouble to fill in with the current color.
Sets @color to be the current color in the MateColorSelection widget.
Deprecated: 2.0: Use mate_color_selection_get_current_color() instead.
Definition at line 2525 of file mate-colorsel.c.
References COLORSEL_BLUE, COLORSEL_GREEN, COLORSEL_OPACITY, COLORSEL_RED, MATE_IS_COLOR_SELECTION, and _MateColorSelection::private_data.
mate_color_selection_get_current_alpha()
guint16 mate_color_selection_get_current_alpha (MateColorSelection * colorsel)
mate_color_selection_get_current_alpha: @colorsel: a MateColorSelection.
Returns the current alpha value.
Return value: an integer between 0 and 65535.
Definition at line 2505 of file mate-colorsel.c.
References COLORSEL_OPACITY, MATE_IS_COLOR_SELECTION, _MateColorSelection::private_data, and UNSCALE.
mate_color_selection_get_current_rgba()
void mate_color_selection_get_current_rgba (MateColorSelection * colorsel, GdkRGBA * color)
mate_color_selection_get_current_rgba: @colorsel: a MateColorSelection. @color: (out): a #GdkRGBA to fill in with the current color.
Sets @color to be the current color in the MateColorSelection widget.
Definition at line 2482 of file mate-colorsel.c.
References COLORSEL_BLUE, COLORSEL_GREEN, COLORSEL_RED, MATE_IS_COLOR_SELECTION, NULL, and _MateColorSelection::private_data.
mate_color_selection_get_has_opacity_control()
gboolean mate_color_selection_get_has_opacity_control (MateColorSelection * colorsel)
mate_color_selection_get_has_opacity_control: @colorsel: a MateColorSelection.
Determines whether the colorsel has an opacity control.
Return value: TRUE if the @colorsel has an opacity control. FALSE if it does't.
Definition at line 2279 of file mate-colorsel.c.
References FALSE, MATE_IS_COLOR_SELECTION, and _MateColorSelection::private_data.
mate_color_selection_get_has_palette()
gboolean mate_color_selection_get_has_palette (MateColorSelection * colorsel)
mate_color_selection_get_has_palette: @colorsel: a MateColorSelection.
Determines whether the color selector has a color palette.
Return value: TRUE if the selector has a palette. FALSE if it hasn't.
Definition at line 2339 of file mate-colorsel.c.
References FALSE, MATE_IS_COLOR_SELECTION, and _MateColorSelection::private_data.
mate_color_selection_get_previous_alpha()
guint16 mate_color_selection_get_previous_alpha (MateColorSelection * colorsel)
mate_color_selection_get_previous_alpha: @colorsel: a MateColorSelection.
Returns the previous alpha value.
Return value: an integer between 0 and 65535.
Definition at line 2629 of file mate-colorsel.c.
References COLORSEL_OPACITY, MATE_IS_COLOR_SELECTION, _MateColorSelection::private_data, and UNSCALE.
mate_color_selection_get_previous_color()
void mate_color_selection_get_previous_color (MateColorSelection * colorsel, GdkRGBA * color)
mate_color_selection_get_previous_color: @colorsel: a MateColorSelection. @color: (out): a #GdkRGBA to fill in with the original color value.
Fills @color in with the original color value.
Definition at line 2606 of file mate-colorsel.c.
References COLORSEL_BLUE, COLORSEL_GREEN, COLORSEL_RED, MATE_IS_COLOR_SELECTION, NULL, and _MateColorSelection::private_data.
mate_color_selection_is_adjusting()
gboolean mate_color_selection_is_adjusting (MateColorSelection * colorsel)
mate_color_selection_is_adjusting: @colorsel: a MateColorSelection.
Gets the current state of the @colorsel.
Return value: TRUE if the user is currently dragging a color around, and FALSE if the selection has stopped.
Definition at line 2681 of file mate-colorsel.c.
References FALSE, MATE_HSV, mate_hsv_is_adjusting(), MATE_IS_COLOR_SELECTION, and _MateColorSelection::private_data.
mate_color_selection_new()
GtkWidget * mate_color_selection_new (void)
mate_color_selection_new:
Creates a new MateColorSelection.
Return value: a new MateColorSelection
Definition at line 2247 of file mate-colorsel.c.
References FALSE, mate_color_selection_set_has_opacity_control(), MATE_TYPE_COLOR_SELECTION, NULL, _MateColorSelection::private_data, and TRUE.
mate_color_selection_palette_from_string()
gboolean mate_color_selection_palette_from_string (const gchar * str, GdkRGBA ** colors, gint * n_colors)
mate_color_selection_palette_from_string: @str: a string encoding a color palette. @colors: (out) (array length=n_colors): return location for allocated array of #GdkRGBA. @n_colors: return location for length of array.
Parses a color palette string; the string is a colon-separated list of color names readable by gdk_color_parse().
Return value: TRUE if a palette was successfully parsed.
Definition at line 2705 of file mate-colorsel.c.
References FALSE, NULL, and TRUE.
mate_color_selection_palette_to_string()
gchar * mate_color_selection_palette_to_string (const GdkRGBA * colors, gint n_colors)
mate_color_selection_palette_to_string: @colors: (array length=n_colors): an array of colors. @n_colors: length of the array.
Encodes a palette as a string, useful for persistent storage.
Return value: allocated string encoding the palette.
Definition at line 2789 of file mate-colorsel.c.
References NULL, and ptr.
mate_color_selection_set_change_palette_hook()
MateColorSelectionChangePaletteFunc mate_color_selection_set_change_palette_hook (MateColorSelectionChangePaletteFunc func)
mate_color_selection_set_change_palette_hook: @func: a function to call when the custom palette needs saving.
Installs a global function to be called whenever the user tries to modify the palette in a color selection. This function should save the new palette contents, and update the GtkSettings property "gtk-color-palette" so all MateColorSelection widgets will be modified.
Return value: the previous change palette hook (that was replaced).
Deprecated: 2.4: This function does not work in multihead environments. Use mate_color_selection_set_change_palette_with_screen_hook() instead.
Definition at line 2842 of file mate-colorsel.c.
mate_color_selection_set_change_palette_with_screen_hook()
MateColorSelectionChangePaletteWithScreenFunc mate_color_selection_set_change_palette_with_screen_hook (MateColorSelectionChangePaletteWithScreenFunc func)
mate_color_selection_set_change_palette_with_screen_hook: @func: a function to call when the custom palette needs saving.
Installs a global function to be called whenever the user tries to modify the palette in a color selection. This function should save the new palette contents, and update the GtkSettings property "gtk-color-palette" so all MateColorSelection widgets will be modified.
Return value: the previous change palette hook (that was replaced).
Since: 1.9.1
Definition at line 2867 of file mate-colorsel.c.
mate_color_selection_set_color()
void mate_color_selection_set_color (MateColorSelection * colorsel, gdouble * color)
mate_color_selection_set_color: @colorsel: a MateColorSelection. @color: an array of 4 doubles specifying the red, green, blue and opacity to set the current color to.
Sets the current color to be @color. The first time this is called, it will also set the original color to be @color too.
Deprecated: 2.0: Use mate_color_selection_set_current_color() instead.
Definition at line 2466 of file mate-colorsel.c.
References MATE_IS_COLOR_SELECTION.
mate_color_selection_set_current_alpha()
void mate_color_selection_set_current_alpha (MateColorSelection * colorsel, guint16 alpha)
mate_color_selection_set_current_alpha: @colorsel: a MateColorSelection. @alpha: an integer between 0 and 65535.
Sets the current opacity to be @alpha. The first time this is called, it will also set the original opacity to be @alpha too.
Definition at line 2434 of file mate-colorsel.c.
References COLORSEL_NUM_CHANNELS, COLORSEL_OPACITY, FALSE, MATE_IS_COLOR_SELECTION, _MateColorSelection::private_data, SCALE, and TRUE.
mate_color_selection_set_current_rgba()
void mate_color_selection_set_current_rgba (MateColorSelection * colorsel, const GdkRGBA * rgba)
mate_color_selection_set_current_rgba: @colorsel: a MateColorSelection. @color: A #GdkRGBA to set the current color with.
Sets the current color to be @color. The first time this is called, it will also set the original color to be @color too.
Definition at line 2391 of file mate-colorsel.c.
References COLORSEL_BLUE, COLORSEL_GREEN, COLORSEL_HUE, COLORSEL_NUM_CHANNELS, COLORSEL_OPACITY, COLORSEL_RED, COLORSEL_SATURATION, COLORSEL_VALUE, FALSE, MATE_IS_COLOR_SELECTION, NULL, _MateColorSelection::private_data, and TRUE.
mate_color_selection_set_has_opacity_control()
void mate_color_selection_set_has_opacity_control (MateColorSelection * colorsel, gboolean has_opacity)
mate_color_selection_set_has_opacity_control: @colorsel: a MateColorSelection. @has_opacity: TRUE if @colorsel can set the opacity, FALSE otherwise.
Sets the @colorsel to use or not use opacity.
Definition at line 2299 of file mate-colorsel.c.
References FALSE, MATE_IS_COLOR_SELECTION, and _MateColorSelection::private_data.
Referenced by mate_color_selection_new().
mate_color_selection_set_has_palette()
void mate_color_selection_set_has_palette (MateColorSelection * colorsel, gboolean has_palette)
mate_color_selection_set_has_palette: @colorsel: a MateColorSelection. @has_palette: TRUE if palette is to be visible, FALSE otherwise.
Shows and hides the palette based upon the value of @has_palette.
Definition at line 2359 of file mate-colorsel.c.
References FALSE, MATE_IS_COLOR_SELECTION, and _MateColorSelection::private_data.
Referenced by main().
mate_color_selection_set_previous_alpha()
void mate_color_selection_set_previous_alpha (MateColorSelection * colorsel, guint16 alpha)
mate_color_selection_set_previous_alpha: @colorsel: a MateColorSelection. @alpha: an integer between 0 and 65535.
Sets the 'previous' alpha to be @alpha. This function should be called with some hesitations, as it might seem confusing to have that alpha change.
Definition at line 2583 of file mate-colorsel.c.
References COLORSEL_OPACITY, FALSE, MATE_IS_COLOR_SELECTION, _MateColorSelection::private_data, SCALE, and TRUE.
mate_color_selection_set_previous_color()
void mate_color_selection_set_previous_color (MateColorSelection * colorsel, const GdkRGBA * color)
mate_color_selection_set_previous_color: @colorsel: a MateColorSelection. @color: a #GdkRGBA to set the previous color with.
Sets the 'previous' color to be @color. This function should be called with some hesitations, as it might seem confusing to have that color change. Calling mate_color_selection_set_current_color() will also set this color the first time it is called.
Definition at line 2550 of file mate-colorsel.c.
References COLORSEL_BLUE, COLORSEL_GREEN, COLORSEL_HUE, COLORSEL_RED, COLORSEL_SATURATION, COLORSEL_VALUE, FALSE, MATE_IS_COLOR_SELECTION, NULL, _MateColorSelection::private_data, and TRUE.