MATE Desktop Environment: matemixer-backend-module.c File Reference
matemixer-backend-module.c File Reference
#include <glib.h>
#include <glib-object.h>
#include <gmodule.h>
#include "matemixer-backend-module.h"
Typedefs
typedef void(* BackendInit) (GTypeModule *type_module)
typedef const MateMixerBackendInfo *(* BackendGetInfo) (void)
Enumerations
enum { PROP_0 , PROP_PATH }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (MateMixerBackendModule, mate_mixer_backend_module, G_TYPE_TYPE_MODULE)
MateMixerBackendModule * mate_mixer_backend_module_new (const gchar *path)
const MateMixerBackendInfo * mate_mixer_backend_module_get_info (MateMixerBackendModule *module)
const gchar * mate_mixer_backend_module_get_path (MateMixerBackendModule *module)
Typedef Documentation
BackendGetInfo
typedef const MateMixerBackendInfo *(* BackendGetInfo) (void)
Definition at line 28 of file matemixer-backend-module.c.
BackendInit
typedef void(* BackendInit) (GTypeModule *type_module)
Definition at line 25 of file matemixer-backend-module.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_PATH
Definition at line 39 of file matemixer-backend-module.c.
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (MateMixerBackendModule , mate_mixer_backend_module , G_TYPE_TYPE_MODULE)
References NULL, and PROP_PATH.
mate_mixer_backend_module_get_info()
const MateMixerBackendInfo * mate_mixer_backend_module_get_info (MateMixerBackendModule * module)
Definition at line 195 of file matemixer-backend-module.c.
References MATE_MIXER_IS_BACKEND_MODULE, NULL, _MateMixerBackendModule::priv, and TRUE.
Referenced by mate_mixer_context_get_backend_flags(), mate_mixer_context_get_backend_name(), mate_mixer_context_get_backend_type(), mate_mixer_context_open(), and mate_mixer_context_set_backend_type().
mate_mixer_backend_module_get_path()
const gchar * mate_mixer_backend_module_get_path (MateMixerBackendModule * module)
Definition at line 212 of file matemixer-backend-module.c.
References MATE_MIXER_IS_BACKEND_MODULE, and NULL.
mate_mixer_backend_module_new()
MateMixerBackendModule * mate_mixer_backend_module_new (const gchar * path)
mate_mixer_backend_module_new: @path: path to a backend module
Creates a new MateMixerBackendModule instance.
Returns: a new MateMixerBackendModule instance.
Definition at line 177 of file matemixer-backend-module.c.
References MATE_MIXER_TYPE_BACKEND_MODULE, and NULL.