MATE Desktop Environment: mate-image-menu-item.h File Reference
mate-image-menu-item.h File Reference
#include <gtk/gtk.h>
Classes
struct _MateImageMenuItem
struct _MateImageMenuItemClass
Macros
#define MATE_TYPE_IMAGE_MENU_ITEM (mate_image_menu_item_get_type ())
#define MATE_IMAGE_MENU_ITEM(obj)
#define MATE_IMAGE_MENU_ITEM_CLASS(klass)
#define MATE_IS_IMAGE_MENU_ITEM(obj)
#define MATE_IS_IMAGE_MENU_ITEM_CLASS(klass)
#define MATE_IMAGE_MENU_ITEM_GET_CLASS(obj)
Typedefs
typedef struct _MateImageMenuItem MateImageMenuItem
typedef struct _MateImageMenuItemPrivate MateImageMenuItemPrivate
typedef struct _MateImageMenuItemClass MateImageMenuItemClass
Functions
GType mate_image_menu_item_get_type (void)
GtkWidget * mate_image_menu_item_new (void)
GtkWidget * mate_image_menu_item_new_with_label (const gchar *label)
GtkWidget * mate_image_menu_item_new_with_mnemonic (const gchar *label)
void mate_image_menu_item_set_image (MateImageMenuItem *image_menu_item, GtkWidget *image)
GtkWidget * mate_image_menu_item_get_image (MateImageMenuItem *image_menu_item)
Macro Definition Documentation
MATE_IMAGE_MENU_ITEM
#define MATE_IMAGE_MENU_ITEM (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), MATE_TYPE_IMAGE_MENU_ITEM, MateImageMenuItem))
Definition at line 26 of file mate-image-menu-item.h.
Referenced by main(), setup_menuitem(), sn_dbus_menu_item_new(), sn_dbus_menu_item_remove_props(), and sn_dbus_menu_item_update_props().
MATE_IMAGE_MENU_ITEM_CLASS
#define MATE_IMAGE_MENU_ITEM_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), MATE_TYPE_IMAGE_MENU_ITEM, MateImageMenuItemClass))
Definition at line 27 of file mate-image-menu-item.h.
MATE_IMAGE_MENU_ITEM_GET_CLASS
#define MATE_IMAGE_MENU_ITEM_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), MATE_TYPE_IMAGE_MENU_ITEM, MateImageMenuItemClass))
Definition at line 30 of file mate-image-menu-item.h.
MATE_IS_IMAGE_MENU_ITEM
#define MATE_IS_IMAGE_MENU_ITEM (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), MATE_TYPE_IMAGE_MENU_ITEM))
Definition at line 28 of file mate-image-menu-item.h.
Referenced by mate_image_menu_item_get_image(), mate_image_menu_item_set_image(), and sn_dbus_menu_item_remove_props().
MATE_IS_IMAGE_MENU_ITEM_CLASS
#define MATE_IS_IMAGE_MENU_ITEM_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), MATE_TYPE_IMAGE_MENU_ITEM))
Definition at line 29 of file mate-image-menu-item.h.
MATE_TYPE_IMAGE_MENU_ITEM
#define MATE_TYPE_IMAGE_MENU_ITEM (mate_image_menu_item_get_type ())
Definition at line 25 of file mate-image-menu-item.h.
Referenced by mate_image_menu_item_new(), mate_image_menu_item_new_with_label(), and mate_image_menu_item_new_with_mnemonic().
Typedef Documentation
MateImageMenuItem
typedef struct _MateImageMenuItem MateImageMenuItem
Definition at line 32 of file mate-image-menu-item.h.
MateImageMenuItemClass
typedef struct _MateImageMenuItemClass MateImageMenuItemClass
Definition at line 34 of file mate-image-menu-item.h.
MateImageMenuItemPrivate
typedef struct _MateImageMenuItemPrivate MateImageMenuItemPrivate
Definition at line 33 of file mate-image-menu-item.h.
Function Documentation
mate_image_menu_item_get_image()
GtkWidget * mate_image_menu_item_get_image (MateImageMenuItem * image_menu_item)
mate_image_menu_item_get_image: @image_menu_item: a MateImageMenuItem
Gets the widget that is currently set as the image of @image_menu_item. See mate_image_menu_item_set_image().
Returns: (transfer none): the widget set as image of @image_menu_item
Definition at line 524 of file mate-image-menu-item.c.
References MATE_IS_IMAGE_MENU_ITEM, NULL, and _MateImageMenuItem::priv.
mate_image_menu_item_get_type()
GType mate_image_menu_item_get_type (void)
References label.
mate_image_menu_item_new()
GtkWidget * mate_image_menu_item_new (void)
mate_image_menu_item_new:
Creates a new MateImageMenuItem with an empty label.
Returns: a new MateImageMenuItem
Definition at line 428 of file mate-image-menu-item.c.
References MATE_TYPE_IMAGE_MENU_ITEM, and NULL.
Referenced by main(), panel_image_menu_item_new(), panel_recent_append_documents_menu(), and sn_dbus_menu_item_new().
mate_image_menu_item_new_with_label()
GtkWidget * mate_image_menu_item_new_with_label (const gchar * label)
mate_image_menu_item_new_with_label: @label: the text of the menu item.
Creates a new MateImageMenuItem containing a label.
Returns: a new MateImageMenuItem.
Definition at line 443 of file mate-image-menu-item.c.
References label, MATE_TYPE_IMAGE_MENU_ITEM, and NULL.
Referenced by ev_sidebar_add_page(), gdict_sidebar_add_page(), and main().
mate_image_menu_item_new_with_mnemonic()
GtkWidget * mate_image_menu_item_new_with_mnemonic (const gchar * label)
mate_image_menu_item_new_with_mnemonic: @label: the text of the menu item, with an underscore in front of the mnemonic character
Creates a new MateImageMenuItem containing a label. The label will be created using gtk_label_new_with_mnemonic(), so underscores in @label indicate the mnemonic for the menu item.
Returns: a new MateImageMenuItem
Definition at line 463 of file mate-image-menu-item.c.
References label, MATE_TYPE_IMAGE_MENU_ITEM, NULL, and TRUE.
Referenced by main().
mate_image_menu_item_set_image()
void mate_image_menu_item_set_image (MateImageMenuItem * image_menu_item, GtkWidget * image)
mate_image_menu_item_set_image: @image_menu_item: a MateImageMenuItem. (allow-none): a widget to set as the image for the menu item.
Sets the image of @image_menu_item to the given widget. Note that it depends on the show-menu-images setting whether the image will be displayed or not.
Definition at line 482 of file mate-image-menu-item.c.
References MATE_IS_IMAGE_MENU_ITEM, NULL, _MateImageMenuItem::priv, and TRUE.
Referenced by main(), setup_menuitem(), sn_dbus_menu_item_new(), sn_dbus_menu_item_remove_props(), and sn_dbus_menu_item_update_props().