MATE Desktop Environment: xutils.c File Reference
xutils.c File Reference
#include <config.h>
#include "xutils.h"
#include <string.h>
#include <stdio.h>
#include <libwnck/libwnck.h>
Macros
#define WNCK_I_KNOW_THIS_IS_UNSTABLE
#define UNUSED_VARIABLE
Functions
void _wnck_error_trap_push (void)
int _wnck_error_trap_pop (void)
void _wnck_get_wmclass (Window xwindow, char **res_class, char **res_name)
Macro Definition Documentation
UNUSED_VARIABLE
#define UNUSED_VARIABLE
Definition at line 35 of file mate-netbook/maximus/xutils.c.
WNCK_I_KNOW_THIS_IS_UNSTABLE
#define WNCK_I_KNOW_THIS_IS_UNSTABLE
Definition at line 29 of file mate-netbook/maximus/xutils.c.
Function Documentation
_wnck_error_trap_pop()
int _wnck_error_trap_pop (void)
Definition at line 45 of file mate-netbook/maximus/xutils.c.
Referenced by _wnck_get_wmclass().
_wnck_error_trap_push()
void _wnck_error_trap_push (void)
Definition at line 39 of file mate-netbook/maximus/xutils.c.
Referenced by _wnck_get_wmclass().
_wnck_get_wmclass()
void _wnck_get_wmclass (Window xwindow, char ** res_class, char ** res_name)
Definition at line 71 of file mate-netbook/maximus/xutils.c.
References _wnck_error_trap_pop(), _wnck_error_trap_push(), NULL, and UNUSED_VARIABLE.