MATE Desktop Environment: mateweather-dialog.c File Reference
mateweather-dialog.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <gio/gio.h>
#include "mateweather.h"
#include "mateweather-applet.h"
#include "mateweather-pref.h"
#include "mateweather-dialog.h"
Macros
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
#define MONOSPACE_FONT_SCHEMA "org.mate.interface"
#define MONOSPACE_FONT_KEY "monospace-font-name"
Enumerations
enum { PROP_0 , PROP_MATEWEATHER_APPLET }
Functions
G_DEFINE_TYPE (MateWeatherDialog, mateweather_dialog, GTK_TYPE_DIALOG)
void mateweather_dialog_update (MateWeatherDialog *dialog)
GtkWidget * mateweather_dialog_new (MateWeatherApplet *applet)
Macro Definition Documentation
MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
Definition at line 23 of file mateweather-dialog.c.
MONOSPACE_FONT_KEY
#define MONOSPACE_FONT_KEY "monospace-font-name"
Definition at line 62 of file mateweather-dialog.c.
Referenced by font_init(), mate_theme_read_meta_theme(), and themes_init().
MONOSPACE_FONT_SCHEMA
#define MONOSPACE_FONT_SCHEMA "org.mate.interface"
Definition at line 61 of file mateweather-dialog.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_MATEWEATHER_APPLET
Definition at line 54 of file mateweather-dialog.c.
Function Documentation
G_DEFINE_TYPE()
G_DEFINE_TYPE (MateWeatherDialog , mateweather_dialog , GTK_TYPE_DIALOG)
mateweather_dialog_new()
GtkWidget * mateweather_dialog_new (MateWeatherApplet * applet)
Definition at line 320 of file mateweather-dialog.c.
References MATEWEATHER_TYPE_DIALOG, and NULL.
mateweather_dialog_update()
void mateweather_dialog_update (MateWeatherDialog * dialog)
Definition at line 182 of file mateweather-dialog.c.
References _, NULL, weather_info_get_apparent(), weather_info_get_conditions(), weather_info_get_dew(), weather_info_get_forecast(), weather_info_get_humidity(), weather_info_get_icon_name(), weather_info_get_location_name(), weather_info_get_pressure(), weather_info_get_radar(), weather_info_get_sky(), weather_info_get_sunrise(), weather_info_get_sunset(), weather_info_get_temp(), weather_info_get_update(), weather_info_get_visibility(), and weather_info_get_wind().