MATE Desktop Environment: matemixer-stream.c File Reference
matemixer-stream.c File Reference
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include "matemixer-device.h"
#include "matemixer-enums.h"
#include "matemixer-enum-types.h"
#include "matemixer-stream.h"
#include "matemixer-stream-control.h"
#include "matemixer-stream-private.h"
#include "matemixer-stream-switch.h"
#include "matemixer-switch.h"
Enumerations
enum {
PROP_0 , PROP_NAME , PROP_LABEL , PROP_DIRECTION ,
PROP_DEVICE , PROP_DEFAULT_CONTROL , N_PROPERTIES
}
enum {
CONTROL_ADDED , CONTROL_REMOVED , SWITCH_ADDED , SWITCH_REMOVED ,
N_SIGNALS
}
Functions
const gchar * mate_mixer_stream_get_name (MateMixerStream *stream)
const gchar * mate_mixer_stream_get_label (MateMixerStream *stream)
MateMixerDirection mate_mixer_stream_get_direction (MateMixerStream *stream)
MateMixerDevice * mate_mixer_stream_get_device (MateMixerStream *stream)
: the name of a stream switch
mate_mixer_stream_get_switch: @stream: a MateMixerStream
Gets the switch with the given name.
Returns: a MateMixerStreamSwitch or NULL if there is no such switch.
MateMixerStreamSwitch * mate_mixer_stream_get_switch (MateMixerStream *stream, const gchar *name)
MateMixerStreamControl * mate_mixer_stream_get_default_control (MateMixerStream *stream)
const GList * mate_mixer_stream_list_controls (MateMixerStream *stream)
const GList * mate_mixer_stream_list_switches (MateMixerStream *stream)
void _mate_mixer_stream_set_default_control (MateMixerStream *stream, MateMixerStreamControl *control)
: the name of a stream control
mate_mixer_stream_get_control: @stream: a MateMixerStream
MateMixerStreamControl * mate_mixer_stream_get_control (MateMixerStream *stream, const gchar *name)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CONTROL_ADDED
CONTROL_REMOVED
SWITCH_ADDED
SWITCH_REMOVED
N_SIGNALS
Definition at line 57 of file matemixer-stream.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_NAME
PROP_LABEL
PROP_DIRECTION
PROP_DEVICE
PROP_DEFAULT_CONTROL
N_PROPERTIES
Definition at line 45 of file matemixer-stream.c.
Function Documentation
_mate_mixer_stream_set_default_control()
void _mate_mixer_stream_set_default_control (MateMixerStream * stream, MateMixerStreamControl * control)
Definition at line 487 of file matemixer-stream.c.
References MATE_MIXER_IS_STREAM, MATE_MIXER_IS_STREAM_CONTROL, mate_mixer_stream_control_get_name(), mate_mixer_stream_get_name(), NULL, and PROP_DEFAULT_CONTROL.
Referenced by alsa_stream_set_default_control(), oss_stream_set_default_control(), pulse_sink_new(), and pulse_source_new().
mate_mixer_stream_get_control()
MateMixerStreamControl * mate_mixer_stream_get_control (MateMixerStream * stream, const gchar * name)
Definition at line 360 of file matemixer-stream.c.
References MATE_MIXER_IS_STREAM, MATE_MIXER_STREAM_GET_CLASS, name, and NULL.
mate_mixer_stream_get_default_control()
MateMixerStreamControl * mate_mixer_stream_get_default_control (MateMixerStream * stream)
mate_mixer_stream_get_default_control: @stream: a MateMixerStream
Definition at line 391 of file matemixer-stream.c.
References MATE_MIXER_IS_STREAM, MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_list_controls(), and NULL.
Referenced by alsa_stream_get_default_control(), alsa_stream_has_default_control(), alsa_stream_remove_elements(), oss_stream_get_default_control(), and oss_stream_has_default_control().
mate_mixer_stream_get_device()
MateMixerDevice * mate_mixer_stream_get_device (MateMixerStream * stream)
mate_mixer_stream_get_device: @stream: a MateMixerStream
Definition at line 347 of file matemixer-stream.c.
References MATE_MIXER_IS_STREAM, and NULL.
Referenced by pulse_stream_get_device().
mate_mixer_stream_get_direction()
MateMixerDirection mate_mixer_stream_get_direction (MateMixerStream * stream)
mate_mixer_stream_get_direction: @stream: a MateMixerStream
Definition at line 335 of file matemixer-stream.c.
References MATE_MIXER_DIRECTION_UNKNOWN, and MATE_MIXER_IS_STREAM.
Referenced by mate_mixer_backend_set_default_input_stream(), and mate_mixer_backend_set_default_output_stream().
mate_mixer_stream_get_label()
const gchar * mate_mixer_stream_get_label (MateMixerStream * stream)
mate_mixer_stream_get_label: @stream: a MateMixerStream
Definition at line 323 of file matemixer-stream.c.
References MATE_MIXER_IS_STREAM, and NULL.
mate_mixer_stream_get_name()
const gchar * mate_mixer_stream_get_name (MateMixerStream * stream)
mate_mixer_stream_get_name: @stream: a MateMixerStream
Definition at line 311 of file matemixer-stream.c.
References MATE_MIXER_IS_STREAM, and NULL.
Referenced by _mate_mixer_backend_set_default_input_stream(), _mate_mixer_backend_set_default_output_stream(), _mate_mixer_stream_set_default_control(), alsa_device_close(), mate_mixer_backend_get_stream(), oss_device_close(), pulse_device_add_stream(), and pulse_device_remove_stream().
mate_mixer_stream_get_switch()
MateMixerStreamSwitch * mate_mixer_stream_get_switch (MateMixerStream * stream, const gchar * name)
Definition at line 378 of file matemixer-stream.c.
References MATE_MIXER_IS_STREAM, MATE_MIXER_STREAM_GET_CLASS, name, and NULL.
mate_mixer_stream_list_controls()
const GList * mate_mixer_stream_list_controls (MateMixerStream * stream)
mate_mixer_stream_list_controls: @stream: a MateMixerStream
Definition at line 413 of file matemixer-stream.c.
References _MateMixerStreamClass::list_controls, MATE_MIXER_IS_STREAM, MATE_MIXER_STREAM_GET_CLASS, and NULL.
Referenced by mate_mixer_stream_get_default_control(), and oss_device_load().
mate_mixer_stream_list_switches()
const GList * mate_mixer_stream_list_switches (MateMixerStream * stream)
mate_mixer_stream_list_switches: @stream: a MateMixerStream
Definition at line 432 of file matemixer-stream.c.
References _MateMixerStreamClass::list_switches, MATE_MIXER_IS_STREAM, MATE_MIXER_STREAM_GET_CLASS, and NULL.