MATE Desktop Environment: mateweather-location.c File Reference
mateweather-location.c File Reference
#include <string.h>
#include <math.h>
#include <locale.h>
#include <libxml/xmlreader.h>
#include "mateweather-location.h"
#include "mateweather-timezone.h"
#include "parser.h"
#include "weather-priv.h"
Macros
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
Functions
MateWeatherLocation * mateweather_location_new_world (gboolean use_regions)
MateWeatherLocation * mateweather_location_ref (MateWeatherLocation *loc)
void mateweather_location_unref (MateWeatherLocation *loc)
GType mateweather_location_get_type (void)
const char * mateweather_location_get_name (MateWeatherLocation *loc)
const char * mateweather_location_get_sort_name (MateWeatherLocation *loc)
MateWeatherLocationLevel mateweather_location_get_level (MateWeatherLocation *loc)
MateWeatherLocation * mateweather_location_get_parent (MateWeatherLocation *loc)
MateWeatherLocation ** mateweather_location_get_children (MateWeatherLocation *loc)
void mateweather_location_free_children (MateWeatherLocation *loc, MateWeatherLocation **children)
gboolean mateweather_location_has_coords (MateWeatherLocation *loc)
void mateweather_location_get_coords (MateWeatherLocation *loc, double *latitude, double *longitude)
double mateweather_location_get_distance (MateWeatherLocation *loc, MateWeatherLocation *loc2)
const char * mateweather_location_get_country (MateWeatherLocation *loc)
MateWeatherTimezone * mateweather_location_get_timezone (MateWeatherLocation *loc)
MateWeatherTimezone ** mateweather_location_get_timezones (MateWeatherLocation *loc)
void mateweather_location_free_timezones (MateWeatherLocation *loc, MateWeatherTimezone **zones)
const char * mateweather_location_get_code (MateWeatherLocation *loc)
char * mateweather_location_get_city_name (MateWeatherLocation *loc)
WeatherLocation * mateweather_location_to_weather_location (MateWeatherLocation *gloc, const char *name)
WeatherInfo * mateweather_location_get_weather (MateWeatherLocation *loc)
Macro Definition Documentation
MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
Definition at line 30 of file mateweather-location.c.
Function Documentation
mateweather_location_free_children()
void mateweather_location_free_children (MateWeatherLocation * loc, MateWeatherLocation ** children)
mateweather_location_free_children: @loc: a MateWeatherLocation @children: an array of @loc's children
This is a no-op. Do not use it.
Deprecated: This is a no-op.
Definition at line 515 of file mateweather-location.c.
mateweather_location_free_timezones()
void mateweather_location_free_timezones (MateWeatherLocation * loc, MateWeatherTimezone ** zones)
mateweather_location_free_timezones: @loc: a MateWeatherLocation @zones: an array returned from mateweather_location_get_timezones()
Frees the array of timezones returned by mateweather_location_get_timezones().
Definition at line 692 of file mateweather-location.c.
References mateweather_timezone_unref(), and NULL.
mateweather_location_get_children()
MateWeatherLocation ** mateweather_location_get_children (MateWeatherLocation * loc)
mateweather_location_get_children: @loc: a MateWeatherLocation
Gets an array of @loc's children; this is owned by @loc and will not remain valid if @loc is freed.
Return value: (transfer none) (array zero-terminated=1): @loc's children. (May be empty, but will not be NULL.)
Definition at line 493 of file mateweather-location.c.
References NULL.
mateweather_location_get_city_name()
char * mateweather_location_get_city_name (MateWeatherLocation * loc)
mateweather_location_get_city_name: @loc: a MateWeatherLocation
For a MATEWEATHER_LOCATION_CITY location, this is equivalent to mateweather_location_get_name(). For a MATEWEATHER_LOCATION_WEATHER_STATION location, it is equivalent to calling mateweather_location_get_name() on the location's parent. For other locations it will return NULL.
Return value: (allow-none) @loc's city name, or NULL
Definition at line 734 of file mateweather-location.c.
References MATEWEATHER_LOCATION_CITY, MATEWEATHER_LOCATION_WEATHER_STATION, and NULL.
mateweather_location_get_code()
const char * mateweather_location_get_code (MateWeatherLocation * loc)
mateweather_location_get_code: @loc: a MateWeatherLocation
Gets the METAR station code associated with a MATEWEATHER_LOCATION_WEATHER_STATION location.
Return value: (allow-none): @loc's METAR station code, or NULL
Definition at line 715 of file mateweather-location.c.
References NULL.
mateweather_location_get_coords()
void mateweather_location_get_coords (MateWeatherLocation * loc, double * latitude, double * longitude)
mateweather_location_get_coords: @loc: a MateWeatherLocation @latitude: (out): on return will contain @loc's latitude @longitude: (out): on return will contain @loc's longitude
Gets @loc's coordinates; you must check mateweather_location_has_coords() before calling this.
Definition at line 546 of file mateweather-location.c.
References NULL.
mateweather_location_get_country()
const char * mateweather_location_get_country (MateWeatherLocation * loc)
mateweather_location_get_country: @loc: a MateWeatherLocation
Gets the ISO 3166 country code of @loc (or NULL if @loc is a region- or world-level location)
Return value: (allow-none): @loc's country code (or NULL if @loc is a region- or world-level location)
Definition at line 594 of file mateweather-location.c.
References NULL.
Referenced by mateweather_location_to_weather_location().
mateweather_location_get_distance()
double mateweather_location_get_distance (MateWeatherLocation * loc, MateWeatherLocation * loc2)
mateweather_location_get_distance: @loc: a MateWeatherLocation @loc2: a second MateWeatherLocation
Determines the distance in kilometers between @loc and @loc2.
Return value: the distance between @loc and @loc2.
Definition at line 568 of file mateweather-location.c.
References NULL.
mateweather_location_get_level()
MateWeatherLocationLevel mateweather_location_get_level (MateWeatherLocation * loc)
mateweather_location_get_level: @loc: a MateWeatherLocation
Gets @loc's level, from MATEWEATHER_LOCATION_WORLD, to MATEWEATHER_LOCATION_WEATHER_STATION.
Return value: @loc's level
Definition at line 460 of file mateweather-location.c.
References MATEWEATHER_LOCATION_WORLD, and NULL.
mateweather_location_get_name()
const char * mateweather_location_get_name (MateWeatherLocation * loc)
mateweather_location_get_name: @loc: a MateWeatherLocation
Gets @loc's name, localized into the current language.
Note that MATEWEATHER_LOCATION_WEATHER_STATION nodes are not localized, and so the name returned for those nodes will always be in English, and should therefore not be displayed to the user. (FIXME: should we just not return a name?)
Return value: @loc's name
Definition at line 426 of file mateweather-location.c.
References NULL.
Referenced by mateweather_location_to_weather_location().
mateweather_location_get_parent()
MateWeatherLocation * mateweather_location_get_parent (MateWeatherLocation * loc)
mateweather_location_get_parent: @loc: a MateWeatherLocation
Gets @loc's parent location.
Return value: (transfer none) (allow-none): @loc's parent, or NULL if @loc is a MATEWEATHER_LOCATION_WORLD node.
Definition at line 476 of file mateweather-location.c.
References NULL.
mateweather_location_get_sort_name()
const char * mateweather_location_get_sort_name (MateWeatherLocation * loc)
mateweather_location_get_sort_name: @loc: a MateWeatherLocation
Gets @loc's "sort name", which is the name after having g_utf8_normalize() (with G_NORMALIZE_ALL) and g_utf8_casefold() called on it. You can use this to sort locations, or to comparing user input against a location name.
Return value: @loc's sort name
Definition at line 444 of file mateweather-location.c.
References NULL.
mateweather_location_get_timezone()
MateWeatherTimezone * mateweather_location_get_timezone (MateWeatherLocation * loc)
mateweather_location_get_timezone: @loc: a MateWeatherLocation
Gets the timezone associated with @loc, if known.
The timezone is owned either by @loc or by one of its parents. FIXME.
Return value: (transfer none) (allow-none): @loc's timezone, or NULL
Definition at line 616 of file mateweather-location.c.
References mateweather_timezone_get_tzid(), and NULL.
mateweather_location_get_timezones()
MateWeatherTimezone ** mateweather_location_get_timezones (MateWeatherLocation * loc)
mateweather_location_get_timezones: @loc: a MateWeatherLocation
Gets an array of all timezones associated with any location under @loc. You can use mateweather_location_free_timezones() to free this array.
Return value: (transfer full) (array zero-terminated=1): an array of timezones. May be empty but will not be NULL.
Definition at line 671 of file mateweather-location.c.
References FALSE, and NULL.
mateweather_location_get_type()
GType mateweather_location_get_type (void)
Definition at line 398 of file mateweather-location.c.
References mateweather_location_ref(), and mateweather_location_unref().
mateweather_location_get_weather()
WeatherInfo * mateweather_location_get_weather (MateWeatherLocation * loc)
mateweather_location_get_weather: @loc: a MateWeatherLocation
Creates a WeatherInfo corresponding to @loc; you can use weather_info_update() to fill it in.
Return value: (transfer full): a WeatherInfo corresponding to @loc.
Definition at line 802 of file mateweather-location.c.
References mateweather_location_to_weather_location(), NULL, weather_info_new, and weather_location_free().
mateweather_location_has_coords()
gboolean mateweather_location_has_coords (MateWeatherLocation * loc)
mateweather_location_has_coords: @loc: a MateWeatherLocation
Checks if @loc has valid latitude and longitude.
Return value: TRUE if @loc has valid latitude and longitude.
Definition at line 530 of file mateweather-location.c.
References FALSE, and NULL.
mateweather_location_new_world()
MateWeatherLocation * mateweather_location_new_world (gboolean use_regions)
mateweather_location_new_world: @use_regions: whether or not to divide the world into regions
Creates a new MateWeatherLocation of type MATEWEATHER_LOCATION_WORLD, representing a hierarchy containing all of the locations from Locations.xml.
If @use_regions is TRUE, the immediate children of the returned location will be MATEWEATHER_LOCATION_REGION nodes, representing the top-level "regions" of Locations.xml (the continents and a few other divisions), and the country-level nodes will be the children of the regions. If @use_regions is FALSE, the regions will be skipped, and the children of the returned location will be the MATEWEATHER_LOCATION_COUNTRY nodes.
Return value: (allow-none): a MATEWEATHER_LOCATION_WORLD location, or NULL if Locations.xml could not be found or could not be parsed.
Definition at line 323 of file mateweather-location.c.
References MATEWEATHER_LOCATION_WORLD, mateweather_parser_free(), mateweather_parser_new(), and NULL.
Referenced by main(), and mateweather_xml_load_locations().
mateweather_location_ref()
MateWeatherLocation * mateweather_location_ref (MateWeatherLocation * loc)
mateweather_location_ref: @loc: a MateWeatherLocation
Adds 1 to @loc's reference count.
Return value: @loc
Definition at line 347 of file mateweather-location.c.
References NULL.
Referenced by mateweather_location_entry_get_location(), and mateweather_location_get_type().
mateweather_location_to_weather_location()
WeatherLocation * mateweather_location_to_weather_location (MateWeatherLocation * gloc, const char * name)
Definition at line 749 of file mateweather-location.c.
References MATEWEATHER_LOCATION_CITY, mateweather_location_get_country(), mateweather_location_get_name(), name, NULL, and weather_location_new().
Referenced by mateweather_location_get_weather().
mateweather_location_unref()
void mateweather_location_unref (MateWeatherLocation * loc)
mateweather_location_unref: @loc: a MateWeatherLocation
Subtracts 1 from @loc's reference count, and frees it if the reference count reaches 0.
Definition at line 363 of file mateweather-location.c.
References mateweather_location_unref(), mateweather_timezone_unref(), and NULL.
Referenced by main(), mateweather_location_get_type(), mateweather_location_unref(), and mateweather_xml_load_locations().