MATE Desktop Environment: main.c File Reference
main.c File Reference
#include <config.h>
#include <stdio.h>
#include <sys/stat.h>
#include <unistd.h>
#include <signal.h>
#include <dirent.h>
#include <string.h>
#include <time.h>
#include <glibtop.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gio/gio.h>
#include <gio/gdesktopappinfo.h>
#include <mate-panel-applet.h>
#include <mate-panel-applet-gsettings.h>
#include "global.h"
Functions
void multiload_applet_tooltip_update (LoadGraph *g)
void multiload_applet_refresh (MultiloadApplet *ma)
Function Documentation
multiload_applet_refresh()
void multiload_applet_refresh (MultiloadApplet * ma)
Definition at line 411 of file mate-applets/multiload/src/main.c.
References _MultiloadApplet::applet, _MultiloadApplet::box, graph_n, _MultiloadApplet::graphs, load_graph_start(), load_graph_stop(), load_graph_unalloc(), _LoadGraph::main_widget, mate_panel_applet_get_orient(), MatePanelAppletOrient, TRUE, and _LoadGraph::visible.
multiload_applet_tooltip_update()
void multiload_applet_tooltip_update (LoadGraph * g)
Definition at line 266 of file mate-applets/multiload/src/main.c.
References _, _MultiloadApplet::cpu_used_ratio, _MultiloadApplet::diskload_used_ratio, LoadGraph::disp, graph_cpuload, graph_diskload, graph_loadavg, graph_memload, graph_n, graph_netload2, graph_swapload, _MultiloadApplet::loadavg1, _MultiloadApplet::memload_cache, _MultiloadApplet::memload_total, _MultiloadApplet::memload_user, MIN, N_, name, netspeed_get(), _MultiloadApplet::netspeed_in, _MultiloadApplet::netspeed_out, and _MultiloadApplet::swapload_used_ratio.