MATE Desktop Environment: math-window.c File Reference
math-window.c File Reference
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include "math-window.h"
#include "math-history.h"
#include "utility.h"
Macros
#define GDK_KEY_F1 GDK_F1
#define GDK_KEY_W GDK_w
#define GDK_KEY_Z GDK_z
#define ABOUT_GROUP "About"
#define EMAILIFY(string)
#define CALCULATOR_MENU_LABEL _("_Calculator")
#define MODE_MENU_LABEL _("_Mode")
#define VIEW_MENU_LABEL _("_View")
#define HELP_MENU_LABEL _("_Help")
#define MODE_BASIC_LABEL _("_Basic")
#define MODE_ADVANCED_LABEL _("_Advanced")
#define MODE_FINANCIAL_LABEL _("_Financial")
#define MODE_PROGRAMMING_LABEL _("_Programming")
#define VIEW_HISTORY_LABEL _("_History")
#define HELP_CONTENTS_LABEL _("_Contents")
Enumerations
enum { PROP_0 , PROP_EQUATION , PROP_SHOW_HISTORY }
enum { QUIT , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (MathWindow, math_window, GTK_TYPE_WINDOW)
MathWindow * math_window_new (MathEquation *equation)
GtkWidget * math_window_get_menu_bar (MathWindow *window)
MathEquation * math_window_get_equation (MathWindow *window)
MathDisplay * math_window_get_display (MathWindow *window)
MathButtons * math_window_get_buttons (MathWindow *window)
gboolean math_window_get_show_history (MathWindow *window)
void math_window_set_show_history (MathWindow *window, gboolean visible)
void math_window_critical_error (MathWindow *window, const gchar *title, const gchar *contents)
Macro Definition Documentation
ABOUT_GROUP
#define ABOUT_GROUP "About"
Definition at line 304 of file math-window.c.
CALCULATOR_MENU_LABEL
#define CALCULATOR_MENU_LABEL _("_Calculator")
EMAILIFY
#define EMAILIFY (string)
Value:
(g_strdelimit ((string), "%", '@'))
Definition at line 305 of file math-window.c.
GDK_KEY_F1
#define GDK_KEY_F1 GDK_F1
Definition at line 26 of file math-window.c.
GDK_KEY_W
#define GDK_KEY_W GDK_w
Definition at line 30 of file math-window.c.
GDK_KEY_Z
#define GDK_KEY_Z GDK_z
Definition at line 34 of file math-window.c.
HELP_CONTENTS_LABEL
#define HELP_CONTENTS_LABEL _("_Contents")
HELP_MENU_LABEL
#define HELP_MENU_LABEL _("_Help")
MODE_ADVANCED_LABEL
#define MODE_ADVANCED_LABEL _("_Advanced")
MODE_BASIC_LABEL
#define MODE_BASIC_LABEL _("_Basic")
MODE_FINANCIAL_LABEL
#define MODE_FINANCIAL_LABEL _("_Financial")
MODE_MENU_LABEL
#define MODE_MENU_LABEL _("_Mode")
MODE_PROGRAMMING_LABEL
#define MODE_PROGRAMMING_LABEL _("_Programming")
VIEW_HISTORY_LABEL
#define VIEW_HISTORY_LABEL _("_History")
VIEW_MENU_LABEL
#define VIEW_MENU_LABEL _("_View")
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_EQUATION
PROP_SHOW_HISTORY
Definition at line 37 of file math-window.c.
anonymous enum
anonymous enum
Enumerator
QUIT
LAST_SIGNAL
Definition at line 62 of file math-window.c.
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (MathWindow , math_window , GTK_TYPE_WINDOW)
math_window_critical_error()
void math_window_critical_error (MathWindow * window, const gchar * title, const gchar * contents)
Definition at line 135 of file math-window.c.
References NULL, and QUIT.
math_window_get_buttons()
MathButtons * math_window_get_buttons (MathWindow * window)
Definition at line 97 of file math-window.c.
References NULL.
Referenced by main().
math_window_get_display()
MathDisplay * math_window_get_display (MathWindow * window)
Definition at line 90 of file math-window.c.
References NULL.
math_window_get_equation()
MathEquation * math_window_get_equation (MathWindow * window)
Definition at line 83 of file math-window.c.
References NULL.
math_window_get_menu_bar()
GtkWidget * math_window_get_menu_bar (MathWindow * window)
Definition at line 77 of file math-window.c.
math_window_get_show_history()
gboolean math_window_get_show_history (MathWindow * window)
Definition at line 104 of file math-window.c.
References FALSE, and NULL.
Referenced by math_window_set_show_history().
math_window_new()
MathWindow * math_window_new (MathEquation * equation)
Definition at line 71 of file math-window.c.
References math_window_get_type(), and NULL.
Referenced by main().
math_window_set_show_history()
void math_window_set_show_history (MathWindow * window, gboolean visible)
Definition at line 111 of file math-window.c.
References FALSE, math_window_get_show_history(), NULL, and TRUE.
Referenced by main().