MATE Desktop Environment: math-variable-popup.h File Reference
math-variable-popup.h File Reference
#include <gtk/gtk.h>
#include "math-equation.h"
Classes
struct MathVariablePopup
struct MathVariablePopupClass
Macros
#define MATH_VARIABLE_POPUP(obj)
Typedefs
typedef struct MathVariablePopupPrivate MathVariablePopupPrivate
Functions
GType math_variable_popup_get_type (void)
MathVariablePopup * math_variable_popup_new (MathEquation *equation)
Macro Definition Documentation
MATH_VARIABLE_POPUP
#define MATH_VARIABLE_POPUP (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), math_variable_popup_get_type(), MathVariablePopup))
Definition at line 19 of file math-variable-popup.h.
Typedef Documentation
MathVariablePopupPrivate
typedef struct MathVariablePopupPrivate MathVariablePopupPrivate
Definition at line 21 of file math-variable-popup.h.
Function Documentation
math_variable_popup_get_type()
GType math_variable_popup_get_type (void)
Referenced by math_variable_popup_new().
math_variable_popup_new()
MathVariablePopup * math_variable_popup_new (MathEquation * equation)
Definition at line 33 of file math-variable-popup.c.
References math_variable_popup_get_type(), and NULL.
Referenced by memory_cb().