MATE Desktop Environment: math-equation.h File Reference
math-equation.h File Reference
#include <glib-object.h>
#include <gtk/gtk.h>
#include "mp.h"
#include "math-variables.h"
#include "mp-serializer.h"
Classes
struct MathEquation
struct MathEquationClass
Macros
#define MATH_TYPE_EQUATION (math_equation_get_type ())
#define MATH_EQUATION(obj)
#define MATH_EQUATION_GET_CLASS(obj)
Typedefs
typedef struct MathEquationPrivate MathEquationPrivate
Enumerations
enum NumberMode { NORMAL , SUPERSCRIPT , SUBSCRIPT }
Functions
GType math_equation_get_type (void)
MathEquation * math_equation_new (void)
MathVariables * math_equation_get_variables (MathEquation *equation)
gunichar math_equation_get_digit_text (MathEquation *equation, guint digit)
void math_equation_set_status (MathEquation *equation, const gchar *status)
const gchar * math_equation_get_status (MathEquation *equation)
gboolean math_equation_is_empty (MathEquation *equation)
gboolean math_equation_is_result (MathEquation *equation)
gchar * math_equation_get_display (MathEquation *equation)
gchar * math_equation_get_equation (MathEquation *equation)
gboolean math_equation_get_number (MathEquation *equation, MPNumber *z)
void math_equation_set_number_mode (MathEquation *equation, NumberMode mode)
NumberMode math_equation_get_number_mode (MathEquation *equation)
void math_equation_set_accuracy (MathEquation *equation, gint accuracy)
gint math_equation_get_accuracy (MathEquation *equation)
void math_equation_set_show_thousands_separators (MathEquation *equation, gboolean visible)
gboolean math_equation_get_show_thousands_separators (MathEquation *equation)
void math_equation_set_show_trailing_zeroes (MathEquation *equation, gboolean visible)
gboolean math_equation_get_show_trailing_zeroes (MathEquation *equation)
void math_equation_set_number_format (MathEquation *equation, MpDisplayFormat format)
MpDisplayFormat math_equation_get_number_format (MathEquation *equation)
void math_equation_set_base (MathEquation *equation, gint base)
gint math_equation_get_base (MathEquation *equation)
void math_equation_set_word_size (MathEquation *equation, gint word_size)
gint math_equation_get_word_size (MathEquation *equation)
void math_equation_set_angle_units (MathEquation *equation, MPAngleUnit angle_unit)
MPAngleUnit math_equation_get_angle_units (MathEquation *equation)
void math_equation_set_source_currency (MathEquation *equation, const gchar *currency)
const gchar * math_equation_get_source_currency (MathEquation *equation)
void math_equation_set_target_currency (MathEquation *equation, const gchar *currency)
const gchar * math_equation_get_target_currency (MathEquation *equation)
void math_equation_set_source_units (MathEquation *equation, const gchar *units)
const gchar * math_equation_get_source_units (MathEquation *equation)
void math_equation_set_target_units (MathEquation *equation, const gchar *units)
const gchar * math_equation_get_target_units (MathEquation *equation)
gboolean math_equation_in_solve (MathEquation *equation)
const MPNumber * math_equation_get_answer (MathEquation *equation)
MpSerializer * math_equation_get_serializer (MathEquation *equation)
void math_equation_copy (MathEquation *equation)
void math_equation_paste (MathEquation *equation)
void math_equation_undo (MathEquation *equation)
void math_equation_redo (MathEquation *equation)
void math_equation_store (MathEquation *equation, const gchar *name)
void math_equation_recall (MathEquation *equation, const gchar *name)
void math_equation_set (MathEquation *equation, const gchar *text)
void math_equation_set_number (MathEquation *equation, const MPNumber *x)
void math_equation_insert (MathEquation *equation, const gchar *text)
void math_equation_insert_digit (MathEquation *equation, guint digit)
void math_equation_insert_numeric_point (MathEquation *equation)
void math_equation_insert_number (MathEquation *equation, const MPNumber *x)
void math_equation_insert_subtract (MathEquation *equation)
void math_equation_insert_exponent (MathEquation *equation)
void math_equation_solve (MathEquation *equation)
void math_equation_factorize (MathEquation *equation)
void math_equation_delete (MathEquation *equation)
void math_equation_backspace (MathEquation *equation)
void math_equation_clear (MathEquation *equation)
void math_equation_shift (MathEquation *equation, gint count)
void math_equation_toggle_bit (MathEquation *equation, guint bit)
Macro Definition Documentation
MATH_EQUATION
#define MATH_EQUATION (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), math_equation_get_type(), MathEquation))
Definition at line 25 of file math-equation.h.
MATH_EQUATION_GET_CLASS
#define MATH_EQUATION_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), MATH_TYPE_EQUATION, MathEquationClass))
Definition at line 26 of file math-equation.h.
MATH_TYPE_EQUATION
#define MATH_TYPE_EQUATION (math_equation_get_type ())
Definition at line 24 of file math-equation.h.
Typedef Documentation
MathEquationPrivate
typedef struct MathEquationPrivate MathEquationPrivate
Definition at line 28 of file math-equation.h.
Enumeration Type Documentation
NumberMode
enum NumberMode
Enumerator
NORMAL
SUPERSCRIPT
SUBSCRIPT
Definition at line 41 of file math-equation.h.
Function Documentation
math_equation_backspace()
void math_equation_backspace (MathEquation * equation)
Definition at line 1401 of file math-equation.c.
References FALSE, math_equation_is_empty(), NULL, and TRUE.
math_equation_clear()
void math_equation_clear (MathEquation * equation)
Definition at line 1419 of file math-equation.c.
References FALSE, math_equation_set_number_mode(), NORMAL, and NULL.
Referenced by clear_cb().
math_equation_copy()
void math_equation_copy (MathEquation * equation)
Definition at line 403 of file math-equation.c.
References FALSE, and NULL.
math_equation_delete()
void math_equation_delete (MathEquation * equation)
Definition at line 1384 of file math-equation.c.
References NULL.
Referenced by delete_cb().
math_equation_factorize()
void math_equation_factorize (MathEquation * equation)
Definition at line 1358 of file math-equation.c.
References _, math_equation_get_number(), math_equation_set_status(), mp_clear(), mp_is_integer(), mp_new(), NULL, and MathEquation::priv.
Referenced by factorize_cb().
math_equation_get_accuracy()
gint math_equation_get_accuracy (MathEquation * equation)
Definition at line 507 of file math-equation.c.
References mp_serializer_get_trailing_digits(), NULL, and MathEquation::priv.
math_equation_get_angle_units()
MPAngleUnit math_equation_get_angle_units (MathEquation * equation)
Definition at line 626 of file math-equation.c.
References MP_DEGREES, NULL, and MathEquation::priv.
math_equation_get_answer()
const MPNumber * math_equation_get_answer (MathEquation * equation)
Definition at line 882 of file math-equation.c.
References FALSE, NULL, and MathEquation::priv.
Referenced by math_equation_get_number().
math_equation_get_base()
gint math_equation_get_base (MathEquation * equation)
Definition at line 588 of file math-equation.c.
References mp_serializer_get_base(), NULL, and MathEquation::priv.
math_equation_get_digit_text()
gunichar math_equation_get_digit_text (MathEquation * equation, guint digit)
Definition at line 486 of file math-equation.c.
References NULL, and MathEquation::priv.
Referenced by math_equation_insert_digit().
math_equation_get_display()
gchar * math_equation_get_display (MathEquation * equation)
Definition at line 762 of file math-equation.c.
References FALSE, and NULL.
Referenced by math_equation_get_equation().
math_equation_get_equation()
gchar * math_equation_get_equation (MathEquation * equation)
Definition at line 773 of file math-equation.c.
References FALSE, math_equation_get_display(), mp_serializer_get_radix(), mp_serializer_get_thousands_separator(), NULL, and MathEquation::priv.
Referenced by math_equation_get_number(), and math_equation_is_result().
math_equation_get_number()
gboolean math_equation_get_number (MathEquation * equation, MPNumber * z)
Definition at line 826 of file math-equation.c.
References FALSE, math_equation_get_answer(), math_equation_get_equation(), math_equation_is_result(), mp_serializer_from_string(), mp_set_from_mp(), NULL, MathEquation::priv, and TRUE.
Referenced by math_equation_factorize(), math_equation_shift(), math_equation_store(), and math_equation_toggle_bit().
math_equation_get_number_format()
MpDisplayFormat math_equation_get_number_format (MathEquation * equation)
Definition at line 568 of file math-equation.c.
References MP_DISPLAY_FORMAT_AUTOMATIC, mp_serializer_get_number_format(), NULL, and MathEquation::priv.
math_equation_get_number_mode()
NumberMode math_equation_get_number_mode (MathEquation * equation)
Definition at line 868 of file math-equation.c.
References NORMAL, NULL, and MathEquation::priv.
Referenced by set_subscript_cb(), and set_superscript_cb().
math_equation_get_serializer()
MpSerializer * math_equation_get_serializer (MathEquation * equation)
Definition at line 847 of file math-equation.c.
References NULL, and MathEquation::priv.
math_equation_get_show_thousands_separators()
gboolean math_equation_get_show_thousands_separators (MathEquation * equation)
Definition at line 528 of file math-equation.c.
References FALSE, mp_serializer_get_show_thousands_separators(), NULL, and MathEquation::priv.
math_equation_get_show_trailing_zeroes()
gboolean math_equation_get_show_trailing_zeroes (MathEquation * equation)
Definition at line 548 of file math-equation.c.
References FALSE, mp_serializer_get_show_trailing_zeroes(), NULL, and MathEquation::priv.
math_equation_get_source_currency()
const gchar * math_equation_get_source_currency (MathEquation * equation)
Definition at line 647 of file math-equation.c.
References NULL, and MathEquation::priv.
Referenced by math_buttons_set_mode(), and math_equation_set_source_currency().
math_equation_get_source_units()
const gchar * math_equation_get_source_units (MathEquation * equation)
Definition at line 690 of file math-equation.c.
References NULL, and MathEquation::priv.
Referenced by math_buttons_set_mode(), and math_equation_set_source_units().
math_equation_get_status()
const gchar * math_equation_get_status (MathEquation * equation)
Definition at line 733 of file math-equation.c.
References NULL, and MathEquation::priv.
math_equation_get_target_currency()
const gchar * math_equation_get_target_currency (MathEquation * equation)
Definition at line 668 of file math-equation.c.
References NULL, and MathEquation::priv.
Referenced by math_buttons_set_mode(), and math_equation_set_target_currency().
math_equation_get_target_units()
const gchar * math_equation_get_target_units (MathEquation * equation)
Definition at line 712 of file math-equation.c.
References NULL, and MathEquation::priv.
Referenced by math_buttons_set_mode(), and math_equation_set_target_units().
math_equation_get_type()
GType math_equation_get_type (void)
References name.
Referenced by math_equation_new().
math_equation_get_variables()
MathVariables * math_equation_get_variables (MathEquation * equation)
Definition at line 113 of file math-equation.c.
References MathEquation::priv.
math_equation_get_word_size()
gint math_equation_get_word_size (MathEquation * equation)
Definition at line 607 of file math-equation.c.
References NULL, and MathEquation::priv.
math_equation_in_solve()
gboolean math_equation_in_solve (MathEquation * equation)
Definition at line 875 of file math-equation.c.
References FALSE, NULL, and MathEquation::priv.
math_equation_insert()
void math_equation_insert (MathEquation * equation, const gchar * text)
Definition at line 970 of file math-equation.c.
References FALSE, math_equation_set_number_mode(), NORMAL, NULL, MathEquation::priv, and TRUE.
Referenced by answer_clicked_cb(), button_cb(), math_equation_insert_digit(), math_equation_insert_exponent(), math_equation_insert_number(), math_equation_insert_numeric_point(), math_equation_insert_subtract(), and math_equation_recall().
math_equation_insert_digit()
void math_equation_insert_digit (MathEquation * equation, guint digit)
Definition at line 999 of file math-equation.c.
References math_equation_get_digit_text(), math_equation_insert(), NORMAL, NULL, MathEquation::priv, SUBSCRIPT, and SUPERSCRIPT.
Referenced by digit_cb().
math_equation_insert_exponent()
void math_equation_insert_exponent (MathEquation * equation)
Definition at line 1047 of file math-equation.c.
References math_equation_insert(), math_equation_set_number_mode(), NULL, and SUPERSCRIPT.
Referenced by exponent_cb().
math_equation_insert_number()
void math_equation_insert_number (MathEquation * equation, const MPNumber * x)
Definition at line 1034 of file math-equation.c.
References math_equation_insert(), mp_serializer_to_string(), NULL, and MathEquation::priv.
Referenced by character_code_dialog_response_cb().
math_equation_insert_numeric_point()
void math_equation_insert_numeric_point (MathEquation * equation)
Definition at line 1021 of file math-equation.c.
References math_equation_insert(), mp_serializer_get_radix(), NULL, and MathEquation::priv.
Referenced by numeric_point_cb().
math_equation_insert_subtract()
void math_equation_insert_subtract (MathEquation * equation)
Definition at line 1055 of file math-equation.c.
References FALSE, math_equation_insert(), math_equation_set_number_mode(), NORMAL, NULL, MathEquation::priv, and SUPERSCRIPT.
Referenced by subtract_cb().
math_equation_is_empty()
gboolean math_equation_is_empty (MathEquation * equation)
Definition at line 740 of file math-equation.c.
References FALSE, and NULL.
Referenced by math_equation_backspace(), and math_equation_solve().
math_equation_is_result()
gboolean math_equation_is_result (MathEquation * equation)
Definition at line 747 of file math-equation.c.
References FALSE, math_equation_get_equation(), and NULL.
Referenced by math_equation_get_number(), and math_equation_solve().
math_equation_new()
MathEquation * math_equation_new (void)
Definition at line 107 of file math-equation.c.
References math_equation_get_type(), and NULL.
Referenced by main(), and math_display_new().
math_equation_paste()
void math_equation_paste (MathEquation * equation)
Definition at line 427 of file math-equation.c.
References NULL.
math_equation_recall()
void math_equation_recall (MathEquation * equation, const gchar * name)
Definition at line 904 of file math-equation.c.
References math_equation_insert(), name, and NULL.
math_equation_redo()
void math_equation_redo (MathEquation * equation)
Definition at line 460 of file math-equation.c.
References _, math_equation_set_status(), NULL, and MathEquation::priv.
math_equation_set()
void math_equation_set (MathEquation * equation, const gchar * text)
Definition at line 912 of file math-equation.c.
References FALSE, and NULL.
Referenced by equation_clicked_cb().
math_equation_set_accuracy()
void math_equation_set_accuracy (MathEquation * equation, gint accuracy)
Definition at line 495 of file math-equation.c.
References mp_serializer_get_trailing_digits(), mp_serializer_set_trailing_digits(), NULL, and MathEquation::priv.
Referenced by decimal_places_spin_change_value_cb(), and main().
math_equation_set_angle_units()
void math_equation_set_angle_units (MathEquation * equation, MPAngleUnit angle_unit)
Definition at line 614 of file math-equation.c.
References NULL, and MathEquation::priv.
Referenced by angle_unit_combobox_changed_cb(), and main().
math_equation_set_base()
void math_equation_set_base (MathEquation * equation, gint base)
Definition at line 575 of file math-equation.c.
References mp_serializer_get_base(), mp_serializer_set_base(), NULL, and MathEquation::priv.
Referenced by math_buttons_set_mode(), and math_buttons_set_programming_base().
math_equation_set_number()
void math_equation_set_number (MathEquation * equation, const MPNumber * x)
Definition at line 938 of file math-equation.c.
References FALSE, mp_serializer_to_string(), mp_set_from_mp(), NULL, MathEquation::priv, and TRUE.
Referenced by do_finc_expression(), math_equation_shift(), and math_equation_toggle_bit().
math_equation_set_number_format()
void math_equation_set_number_format (MathEquation * equation, MpDisplayFormat format)
Definition at line 555 of file math-equation.c.
References mp_serializer_get_number_format(), mp_serializer_set_number_format(), NULL, and MathEquation::priv.
Referenced by main(), and number_format_combobox_changed_cb().
math_equation_set_number_mode()
void math_equation_set_number_mode (MathEquation * equation, NumberMode mode)
Definition at line 854 of file math-equation.c.
References NULL, MathEquation::priv, and SUPERSCRIPT.
Referenced by math_equation_clear(), math_equation_insert(), math_equation_insert_exponent(), math_equation_insert_subtract(), math_equation_solve(), set_subscript_cb(), and set_superscript_cb().
math_equation_set_show_thousands_separators()
void math_equation_set_show_thousands_separators (MathEquation * equation, gboolean visible)
Definition at line 515 of file math-equation.c.
References mp_serializer_get_show_thousands_separators(), mp_serializer_set_show_thousands_separators(), NULL, and MathEquation::priv.
Referenced by main(), and thousands_separator_check_toggled_cb().
math_equation_set_show_trailing_zeroes()
void math_equation_set_show_trailing_zeroes (MathEquation * equation, gboolean visible)
Definition at line 535 of file math-equation.c.
References mp_serializer_get_show_trailing_zeroes(), mp_serializer_set_show_trailing_zeroes(), NULL, and MathEquation::priv.
Referenced by main(), and trailing_zeroes_check_toggled_cb().
math_equation_set_source_currency()
void math_equation_set_source_currency (MathEquation * equation, const gchar * currency)
Definition at line 633 of file math-equation.c.
References g_settings_var, math_equation_get_source_currency(), NULL, and MathEquation::priv.
Referenced by main().
math_equation_set_source_units()
void math_equation_set_source_units (MathEquation * equation, const gchar * units)
Definition at line 675 of file math-equation.c.
References g_settings_var, math_equation_get_source_units(), NULL, and MathEquation::priv.
Referenced by main().
math_equation_set_status()
void math_equation_set_status (MathEquation * equation, const gchar * status)
Definition at line 719 of file math-equation.c.
References NULL, and MathEquation::priv.
Referenced by math_equation_factorize(), math_equation_redo(), math_equation_shift(), math_equation_store(), math_equation_toggle_bit(), and math_equation_undo().
math_equation_set_target_currency()
void math_equation_set_target_currency (MathEquation * equation, const gchar * currency)
Definition at line 654 of file math-equation.c.
References g_settings_var, math_equation_get_target_currency(), NULL, and MathEquation::priv.
Referenced by main().
math_equation_set_target_units()
void math_equation_set_target_units (MathEquation * equation, const gchar * units)
Definition at line 697 of file math-equation.c.
References g_settings_var, math_equation_get_target_units(), NULL, and MathEquation::priv.
Referenced by main().
math_equation_set_word_size()
void math_equation_set_word_size (MathEquation * equation, gint word_size)
Definition at line 595 of file math-equation.c.
References NULL, and MathEquation::priv.
Referenced by main(), and word_size_combobox_changed_cb().
math_equation_shift()
void math_equation_shift (MathEquation * equation, gint count)
Definition at line 1429 of file math-equation.c.
References _, math_equation_get_number(), math_equation_set_number(), math_equation_set_status(), mp_clear(), mp_new(), mp_shift(), and NULL.
math_equation_solve()
void math_equation_solve (MathEquation * equation)
Definition at line 1272 of file math-equation.c.
References math_equation_is_empty(), math_equation_is_result(), math_equation_set_number_mode(), math_equation_undo(), NORMAL, NULL, and MathEquation::priv.
Referenced by solve_cb().
math_equation_store()
void math_equation_store (MathEquation * equation, const gchar * name)
Definition at line 889 of file math-equation.c.
References _, math_equation_get_number(), math_equation_set_status(), math_variables_set(), mp_clear(), mp_new(), name, NULL, and MathEquation::priv.
math_equation_toggle_bit()
void math_equation_toggle_bit (MathEquation * equation, guint bit)
Definition at line 1449 of file math-equation.c.
References _, FALSE, math_equation_get_number(), math_equation_set_number(), math_equation_set_status(), mp_clear(), mp_is_greater_than(), mp_is_negative(), mp_new(), mp_set_from_unsigned_integer(), mp_to_unsigned_integer(), and NULL.
Referenced by bit_toggle_cb().
math_equation_undo()
void math_equation_undo (MathEquation * equation)
Definition at line 434 of file math-equation.c.
References _, math_equation_set_status(), NULL, and MathEquation::priv.
Referenced by math_equation_solve(), and undo_cb().