MATE Desktop Environment: math-variables.h File Reference
math-variables.h File Reference
#include <glib-object.h>
#include "mp.h"
Classes
struct MathVariables
struct MathVariablesClass
Macros
#define MATH_VARIABLES(obj)
Typedefs
typedef struct MathVariablesPrivate MathVariablesPrivate
Functions
GType math_variables_get_type (void)
MathVariables * math_variables_new (void)
gchar ** math_variables_get_names (MathVariables *variables)
void math_variables_set (MathVariables *variables, const char *name, const MPNumber *value)
MPNumber * math_variables_get (MathVariables *variables, const char *name)
void math_variables_delete (MathVariables *variables, const char *name)
Macro Definition Documentation
MATH_VARIABLES
#define MATH_VARIABLES (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), math_equation_get_type(), MathVariables))
Definition at line 19 of file math-variables.h.
Typedef Documentation
MathVariablesPrivate
typedef struct MathVariablesPrivate MathVariablesPrivate
Definition at line 21 of file math-variables.h.
Function Documentation
math_variables_delete()
void math_variables_delete (MathVariables * variables, const char * name)
Definition at line 151 of file math-variables.c.
References name, NULL, and MathVariables::priv.
math_variables_get()
MPNumber * math_variables_get (MathVariables * variables, const char * name)
Definition at line 143 of file math-variables.c.
References name, NULL, and MathVariables::priv.
math_variables_get_names()
gchar ** math_variables_get_names (MathVariables * variables)
Definition at line 103 of file math-variables.c.
References key, name, NULL, and MathVariables::priv.
math_variables_get_type()
GType math_variables_get_type (void)
References name.
Referenced by math_variables_new().
math_variables_new()
MathVariables * math_variables_new (void)
Definition at line 27 of file math-variables.c.
References math_variables_get_type(), and NULL.
math_variables_set()
void math_variables_set (MathVariables * variables, const char * name, const MPNumber * value)
Definition at line 127 of file math-variables.c.
References mp_new(), mp_set_from_mp(), name, NULL, and MathVariables::priv.
Referenced by math_equation_store().