MATE Desktop Environment: math-display.c File Reference
math-display.c File Reference
#include <string.h>
#include <glib/gi18n.h>
#include <gdk/gdkkeysyms.h>
#include "math-display.h"
Enumerations
enum { PROP_0 , PROP_EQUATION }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (MathDisplay, math_display, GTK_TYPE_VIEWPORT)
MathDisplay * math_display_new ()
MathDisplay * math_display_new_with_equation (MathEquation *equation)
MathEquation * math_display_get_equation (MathDisplay *display)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_EQUATION
Definition at line 17 of file math-display.c.
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (MathDisplay , math_display , GTK_TYPE_VIEWPORT)
math_display_get_equation()
MathEquation * math_display_get_equation (MathDisplay * display)
Definition at line 52 of file math-display.c.
References MathDisplay::priv.
math_display_new()
MathDisplay * math_display_new (void)
Definition at line 40 of file math-display.c.
References math_display_get_type(), math_equation_new(), and NULL.
math_display_new_with_equation()
MathDisplay * math_display_new_with_equation (MathEquation * equation)
Definition at line 46 of file math-display.c.
References math_display_get_type(), and NULL.