MATE Desktop Environment: math-history-entry.c File Reference
math-history-entry.c File Reference
#include <string.h>
#include <glib/gi18n.h>
#include <gdk/gdkkeysyms.h>
#include "math-history-entry.h"
Macros
#define UI_HISTORY_ENTRY_RESOURCE_PATH "/org/mate/calculator/ui/history-entry.ui"
#define get_widget(x)
Functions
G_DEFINE_TYPE_WITH_PRIVATE (MathHistoryEntry, math_history_entry, GTK_TYPE_LIST_BOX_ROW)
MathHistoryEntry * math_history_entry_new (MathEquation *equation)
void answer_clicked_cb (GtkWidget *widget, GdkEventButton *eventbutton, MathHistoryEntry *history_entry)
void equation_clicked_cb (GtkWidget *widget, GdkEventButton *eventbutton, MathHistoryEntry *history_entry)
void math_history_entry_insert_entry (MathHistoryEntry *history_entry, const gchar *equation, MPNumber *answer, MpSerializer *serializer)
void math_history_entry_redisplay (MathHistoryEntry *history_entry, MpSerializer *serializer)
gchar * math_history_entry_get_equation (MathHistoryEntry *history_entry)
Macro Definition Documentation
get_widget
#define get_widget (x)
Value:
GTK_WIDGET(gtk_builder_get_object(builder, x))
Referenced by caja_location_widget_provider_get_widget(), caja_view_get_widget(), caja_widget_view_provider_get_widget(), and math_history_entry_insert_entry().
UI_HISTORY_ENTRY_RESOURCE_PATH
#define UI_HISTORY_ENTRY_RESOURCE_PATH "/org/mate/calculator/ui/history-entry.ui"
Definition at line 30 of file math-history-entry.c.
Referenced by math_history_entry_insert_entry().
Function Documentation
answer_clicked_cb()
G_MODULE_EXPORT void answer_clicked_cb (GtkWidget * widget, GdkEventButton * eventbutton, MathHistoryEntry * history_entry)
Definition at line 43 of file math-history-entry.c.
References math_equation_insert(), NULL, and MathHistoryEntry::priv.
equation_clicked_cb()
G_MODULE_EXPORT void equation_clicked_cb (GtkWidget * widget, GdkEventButton * eventbutton, MathHistoryEntry * history_entry)
Definition at line 54 of file math-history-entry.c.
References math_equation_set(), NULL, and MathHistoryEntry::priv.
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (MathHistoryEntry , math_history_entry , GTK_TYPE_LIST_BOX_ROW)
math_history_entry_get_equation()
gchar * math_history_entry_get_equation (MathHistoryEntry * history_entry)
Definition at line 99 of file math-history-entry.c.
References MathHistoryEntry::priv.
math_history_entry_insert_entry()
void math_history_entry_insert_entry (MathHistoryEntry * history_entry, const gchar * equation, MPNumber * answer, MpSerializer * serializer)
Definition at line 63 of file math-history-entry.c.
References get_widget, math_history_entry_redisplay(), mp_set_from_mp(), MathHistoryEntry::priv, and UI_HISTORY_ENTRY_RESOURCE_PATH.
Referenced by math_history_insert_entry().
math_history_entry_new()
MathHistoryEntry * math_history_entry_new (MathEquation * equation)
Definition at line 33 of file math-history-entry.c.
References math_history_entry_get_type(), NULL, and MathHistoryEntry::priv.
Referenced by math_history_insert_entry().
math_history_entry_redisplay()
void math_history_entry_redisplay (MathHistoryEntry * history_entry, MpSerializer * serializer)
Definition at line 88 of file math-history-entry.c.
References mp_serializer_to_string(), and MathHistoryEntry::priv.
Referenced by math_history_entry_insert_entry(), and math_history_set_serializer().