MATE Desktop Environment: math-history.h File Reference
math-history.h File Reference
#include <glib-object.h>
#include <gtk/gtk.h>
#include "math-history-entry.h"
#include "math-display.h"
#include "math-equation.h"
Classes
struct MathHistory
struct MathHistoryClass
Macros
#define MATH_HISTORY(obj)
Typedefs
typedef struct MathHistoryPrivate MathHistoryPrivate
Functions
GType math_history_get_type (void)
MathHistory * math_history_new (MathEquation *equation)
void math_history_insert_entry (MathHistory *history, char *equation, MPNumber *answer)
gpointer math_history_get_entry_at (MathHistory *history, int index)
void math_history_set_current (MathHistory *history, int value)
int math_history_get_current (MathHistory *history)
void math_history_clear (MathHistory *history)
void math_history_set_serializer (MathHistory *history, MpSerializer *serializer)
Macro Definition Documentation
MATH_HISTORY
#define MATH_HISTORY (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), math_history_get_type(), MathHistory))
Definition at line 25 of file math-history.h.
Typedef Documentation
MathHistoryPrivate
typedef struct MathHistoryPrivate MathHistoryPrivate
Definition at line 27 of file math-history.h.
Function Documentation
math_history_clear()
void math_history_clear (MathHistory * history)
Definition at line 79 of file math-history.c.
References NULL, and MathHistory::priv.
math_history_get_current()
int math_history_get_current (MathHistory * history)
Definition at line 106 of file math-history.c.
References MathHistory::priv.
math_history_get_entry_at()
gpointer math_history_get_entry_at (MathHistory * history, int index)
Definition at line 92 of file math-history.c.
References MATH_HISTORY_ENTRY, NULL, and MathHistory::priv.
math_history_get_type()
GType math_history_get_type (void)
Referenced by math_history_new().
math_history_insert_entry()
void math_history_insert_entry (MathHistory * history, char * equation, MPNumber * answer)
Definition at line 55 of file math-history.c.
References FALSE, math_history_entry_insert_entry(), math_history_entry_new(), and MathHistory::priv.
math_history_new()
MathHistory * math_history_new (MathEquation * equation)
Definition at line 33 of file math-history.c.
References math_history_get_type(), NULL, and MathHistory::priv.
math_history_set_current()
void math_history_set_current (MathHistory * history, int value)
Definition at line 100 of file math-history.c.
References MathHistory::priv.
math_history_set_serializer()
void math_history_set_serializer (MathHistory * history, MpSerializer * serializer)
Definition at line 112 of file math-history.c.
References MATH_HISTORY_ENTRY, math_history_entry_redisplay(), NULL, and MathHistory::priv.