MATE Desktop Environment: md4.c File Reference
md4.c File Reference
#include <string.h>
#include <stdlib.h>
#include "config.h"
#include "skey.h"
#include "skeyutil.h"
#include "md4.h"
Macros
#define byteReverse(buf, len)
#define rotl32(x, n)
#define F(x, y, z)
#define G(x, y, z)
#define H(x, y, z)
#define FF(a, b, c, d, x, s)
#define GG(a, b, c, d, x, s)
#define HH(a, b, c, d, x, s)
Functions
void MD4Init (MD4_CTX *ctx)
void MD4Update (MD4_CTX *ctx, unsigned char const *buf, unsigned len)
void MD4Final (unsigned char *digest, MD4_CTX *ctx)
void MD4Transform (guint32 buf[4], guint32 const in[16])
int MD4Keycrunch (char *result, const char *seed, const char *passphrase)
void MD4SKey (char *x)
Macro Definition Documentation
byteReverse
#define byteReverse (buf, len)
Value:
/* Nothing */
Definition at line 34 of file md4.c.
Referenced by MD4Final(), MD4Update(), SHA1Keycrunch(), and SHA1SKey().
F
#define F (x, y, z)
Value:
(((x) & (y)) | ((~x) & (z)))
Definition at line 176 of file md4.c.
FF
#define FF (a, b, c, d, x, s)
Value:
  { \
  (a) += F ((b), (c), (d)) + (x); \
  (a) = rotl32 ((a), (s)); \
}
Definition at line 180 of file md4.c.
Referenced by MD4Transform().
G
#define G (x, y, z)
Value:
(((x) & (y)) | ((x) & (z)) | ((y) & (z)))
Definition at line 177 of file md4.c.
Referenced by gs_visual_gl_get_best_for_display().
GG
#define GG (a, b, c, d, x, s)
Value:
  { \
  (a) += G ((b), (c), (d)) + (x) + (guint32)0x5a827999; \
  (a) = rotl32 ((a), (s)); \
}
Definition at line 184 of file md4.c.
Referenced by MD4Transform().
H
#define H (x, y, z)
Value:
((x) ^ (y) ^ (z))
Definition at line 178 of file md4.c.
HH
#define HH (a, b, c, d, x, s)
Value:
  { \
  (a) += H ((b), (c), (d)) + (x) + (guint32)0x6ed9eba1; \
  (a) = rotl32 ((a), (s)); \
}
Definition at line 188 of file md4.c.
Referenced by MD4Transform().
rotl32
#define rotl32 (x, n)
Value:
(((x) << ((guint32)(n))) | ((x) >> (32 - (guint32)(n))))
Definition at line 55 of file md4.c.
Function Documentation
MD4Final()
void MD4Final (unsigned char * digest, MD4_CTX * ctx)
Definition at line 128 of file md4.c.
References MD4_CTX::bits, MD4_CTX::buf, byteReverse, MD4_CTX::in, MD4Transform(), memcpy, and NULL.
Referenced by MD4Keycrunch(), and MD4SKey().
MD4Init()
void MD4Init (MD4_CTX * ctx)
Definition at line 61 of file md4.c.
References MD4_CTX::bits, and MD4_CTX::buf.
Referenced by MD4Keycrunch(), and MD4SKey().
MD4Keycrunch()
int MD4Keycrunch (char * result, const char * seed, const char * passphrase)
Definition at line 262 of file md4.c.
References MD4Final(), MD4Init(), MD4Update(), memcpy, NULL, skey_lowcase(), skey_sevenbit(), and SKEY_SIZE.
MD4SKey()
void MD4SKey (char * x)
Definition at line 291 of file md4.c.
References MD4Final(), MD4Init(), MD4Update(), memcpy, and SKEY_SIZE.
MD4Transform()
void MD4Transform (guint32 buf[4], guint32 const in[16])
Definition at line 196 of file md4.c.
References b, FF, GG, and HH.
Referenced by MD4Final(), and MD4Update().
MD4Update()
void MD4Update (MD4_CTX * ctx, unsigned char const * buf, unsigned len)
Definition at line 76 of file md4.c.
References MD4_CTX::bits, MD4_CTX::buf, byteReverse, MD4_CTX::in, MD4Transform(), and memcpy.
Referenced by MD4Keycrunch(), and MD4SKey().