MATE Desktop Environment: md4.h File Reference
md4.h File Reference
#include <glib.h>
Classes
struct MD4_CTX
Functions
void MD4Transform (guint32 buf[4], guint32 const in[16])
void MD4Init (MD4_CTX *context)
void MD4Update (MD4_CTX *context, unsigned char const *buf, unsigned len)
void MD4Final (unsigned char *digest, MD4_CTX *context)
int MD4Keycrunch (char *result, const char *seed, const char *passphrase)
void MD4SKey (char *x)
Function Documentation
MD4Final()
void MD4Final (unsigned char * digest, MD4_CTX * context)
Definition at line 128 of file md4.c.
References MD4_CTX::bits, MD4_CTX::buf, byteReverse, MD4_CTX::in, MD4Transform(), memcpy, and NULL.
Referenced by MD4Keycrunch(), and MD4SKey().
MD4Init()
void MD4Init (MD4_CTX * context)
Definition at line 61 of file md4.c.
References MD4_CTX::bits, and MD4_CTX::buf.
Referenced by MD4Keycrunch(), and MD4SKey().
MD4Keycrunch()
int MD4Keycrunch (char * result, const char * seed, const char * passphrase)
Definition at line 262 of file md4.c.
References MD4Final(), MD4Init(), MD4Update(), memcpy, NULL, skey_lowcase(), skey_sevenbit(), and SKEY_SIZE.
MD4SKey()
void MD4SKey (char * x)
Definition at line 291 of file md4.c.
References MD4Final(), MD4Init(), MD4Update(), memcpy, and SKEY_SIZE.
MD4Transform()
void MD4Transform (guint32 buf[4], guint32 const in[16])
Definition at line 196 of file md4.c.
References b, FF, GG, and HH.
Referenced by MD4Final(), and MD4Update().
MD4Update()
void MD4Update (MD4_CTX * context, unsigned char const * buf, unsigned len)
Definition at line 76 of file md4.c.
References MD4_CTX::bits, MD4_CTX::buf, byteReverse, MD4_CTX::in, MD4Transform(), and memcpy.
Referenced by MD4Keycrunch(), and MD4SKey().