MATE Desktop Environment: mdm-log.h File Reference
mdm-log.h File Reference
#include <stdarg.h>
#include <glib.h>
Macros
#define mdm_fail g_critical
#define mdm_error g_warning
#define mdm_info g_message
#define mdm_debug g_debug
#define mdm_assert g_assert
#define mdm_assert_not_reached g_assert_not_reached
Functions
void mdm_log_default_handler (const gchar *log_domain, GLogLevelFlags log_level, const gchar *message, gpointer unused_data)
void mdm_log_set_debug (gboolean debug)
void mdm_log_toggle_debug (void)
void mdm_log_init (void)
void mdm_log_shutdown (void)
Macro Definition Documentation
mdm_assert
#define mdm_assert g_assert
Definition at line 49 of file mdm-log.h.
mdm_assert_not_reached
#define mdm_assert_not_reached g_assert_not_reached
Definition at line 50 of file mdm-log.h.
mdm_debug
#define mdm_debug g_debug
Definition at line 47 of file mdm-log.h.
mdm_error
#define mdm_error g_warning
Definition at line 45 of file mdm-log.h.
mdm_fail
#define mdm_fail g_critical
Definition at line 44 of file mdm-log.h.
mdm_info
#define mdm_info g_message
Definition at line 46 of file mdm-log.h.
Function Documentation
mdm_log_default_handler()
void mdm_log_default_handler (const gchar * log_domain, GLogLevelFlags log_level, const gchar * message, gpointer unused_data)
Definition at line 103 of file mdm-log.c.
References FALSE, mdm_log_init(), message(), and NULL.
Referenced by mdm_log_init().
mdm_log_init()
void mdm_log_init (void)
Definition at line 182 of file mdm-log.c.
References mdm_log_default_handler(), NULL, and TRUE.
Referenced by main(), and mdm_log_default_handler().
mdm_log_set_debug()
void mdm_log_set_debug (gboolean debug)
Definition at line 170 of file mdm-log.c.
References debug.
Referenced by main().
mdm_log_shutdown()
void mdm_log_shutdown (void)
Definition at line 202 of file mdm-log.c.
References FALSE.
Referenced by main().
mdm_log_toggle_debug()
void mdm_log_toggle_debug (void)
Definition at line 158 of file mdm-log.c.