MATE Desktop Environment: mdm-signal-handler.c File Reference
mdm-signal-handler.c File Reference
#include "config.h"
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <signal.h>
#include <syslog.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <glib/gstdio.h>
#include <glib-object.h>
#include "mdm-signal-handler.h"
Macros
#define UNUSED_VARIABLE
Functions
guint mdm_signal_handler_add (MdmSignalHandler *handler, int signal_number, MdmSignalHandlerFunc callback, gpointer data)
void mdm_signal_handler_add_fatal (MdmSignalHandler *handler)
void mdm_signal_handler_remove (MdmSignalHandler *handler, guint id)
void mdm_signal_handler_remove_func (MdmSignalHandler *handler, guint signal_number, MdmSignalHandlerFunc callback, gpointer data)
void mdm_signal_handler_set_fatal_func (MdmSignalHandler *handler, MdmShutdownHandlerFunc func, gpointer user_data)
MdmSignalHandler * mdm_signal_handler_new (void)
Macro Definition Documentation
UNUSED_VARIABLE
#define UNUSED_VARIABLE
Definition at line 48 of file mdm-signal-handler.c.
Function Documentation
mdm_signal_handler_add()
guint mdm_signal_handler_add (MdmSignalHandler * handler, int signal_number, MdmSignalHandlerFunc callback, gpointer data)
Definition at line 326 of file mdm-signal-handler.c.
References data, handler, and NULL.
Referenced by main(), and mdm_signal_handler_add_fatal().
mdm_signal_handler_add_fatal()
void mdm_signal_handler_add_fatal (MdmSignalHandler * handler)
Definition at line 357 of file mdm-signal-handler.c.
References handler, mdm_signal_handler_add(), and NULL.
Referenced by main().
mdm_signal_handler_new()
MdmSignalHandler * mdm_signal_handler_new (void)
Definition at line 536 of file mdm-signal-handler.c.
References MDM_TYPE_SIGNAL_HANDLER, and NULL.
Referenced by main().
mdm_signal_handler_remove()
void mdm_signal_handler_remove (MdmSignalHandler * handler, guint id)
Definition at line 394 of file mdm-signal-handler.c.
References handler, and NULL.
mdm_signal_handler_remove_func()
void mdm_signal_handler_remove_func (MdmSignalHandler * handler, guint signal_number, MdmSignalHandlerFunc callback, gpointer data)
Definition at line 438 of file mdm-signal-handler.c.
References data, handler, and NULL.
mdm_signal_handler_set_fatal_func()
void mdm_signal_handler_set_fatal_func (MdmSignalHandler * handler, MdmShutdownHandlerFunc func, gpointer user_data)
Definition at line 467 of file mdm-signal-handler.c.
References handler, and user_data.
Referenced by main().