MATE Desktop Environment: mdvi.h File Reference
mdvi.h File Reference
#include <stdio.h>
#include <sys/types.h>
#include <math.h>
#include "sysdeps.h"
#include "bitmap.h"
#include "common.h"
#include "defaults.h"
#include "dviopcodes.h"
#include "hash.h"
#include "paper.h"
#include "fontmap.h"
Classes
struct _DviDevice
struct _TFMChar
struct _TFMInfo
struct _DviGlyph
struct _DviFontInfo
struct _DviFontChar
struct _DviFontRef
struct _DviFontSearch
struct _DviFont
struct _DviParams
struct _DviBuffer
struct _DviState
struct _DviColorPair
struct _DviContext
struct _DviRange
Macros
#define ISVIRTUAL(font)
#define SEARCH_DONE(s)
#define SEARCH_INIT(s, name, h, v)
#define RANGE_HAS_LOWER(x)
#define RANGE_HAS_UPPER(x)
#define MDVI_PARAM_ANTIALIASED 1
#define MDVI_PARAM_MONO 2
#define MDVI_PARAM_CHARBOXES 4
#define MDVI_PARAM_SHOWUNDEF 8
#define MDVI_PARAM_DELAYFONTS 16
#define MDVI_FONTPRIO_FALLBACK -3
#define MDVI_FONTPRIO_LOWEST -2
#define MDVI_FONTPRIO_LOW -1
#define MDVI_FONTPRIO_NORMAL 0
#define MDVI_FONTPRIO_HIGH 1
#define MDVI_FONTPRIO_HIGHEST 2
#define MDVI_FONT_ENCODED (1 << 0)
#define MDVI_GLYPH_EMPTY ((void *)1)
#define MDVI_GLYPH_NONEMPTY(x)
#define MDVI_GLYPH_UNSET(x)
#define MDVI_GLYPH_ISEMPTY(x)
#define MDVI_ENABLED(d, x)
#define MDVI_DISABLED(d, x)
#define MDVI_LASTPAGE(d)
#define MDVI_NPAGES(d)
#define MDVI_VALIDPAGE(d, p)
#define MDVI_FLAGS(d)
#define MDVI_SHRINK_FROM_DPI(d)
#define MDVI_CURRFG(d)
#define MDVI_CURRBG(d)
#define pixel_round(d, v)
#define vpixel_round(d, v)
#define rule_round(d, v)
#define vrule_round(d, v)
#define get_metrics(name)
#define mdvi_config_one(d, x, y)
#define mdvi_set_dpi(d, x)
#define mdvi_set_xdpi(d, x)
#define mdvi_set_ydpi(d, x)
#define mdvi_set_hshrink(d, h)
#define mdvi_set_vshrink(d, h)
#define mdvi_set_gamma(d, g)
#define mdvi_set_density(d, x)
#define mdvi_set_drift(d, x)
#define mdvi_set_hdrift(d, h)
#define mdvi_set_vdrift(d, v)
#define mdvi_set_mag(d, m)
#define mdvi_set_foreground(d, x)
#define mdvi_set_background(d, x)
#define mdvi_set_orientation(d, x)
#define mdvi_set_shrink(d, h, v)
#define MDVI_FONTSEL_BITMAP (1 << 0)
#define MDVI_FONTSEL_GREY (1 << 1)
#define MDVI_FONTSEL_GLYPH (1 << 2)
#define FONTCHAR(font, code)
#define FONT_GLYPH_COUNT(font)
#define glyph_present(x)
#define font_free_glyph(dev, font, code)
#define mdvi_stop_logging(x)
Typedefs
typedef struct _DviGlyph DviGlyph
typedef struct _DviDevice DviDevice
typedef struct _DviFontChar DviFontChar
typedef struct _DviFontRef DviFontRef
typedef struct _DviFontInfo DviFontInfo
typedef struct _DviFont DviFont
typedef struct _DviState DviState
typedef struct _DviPageSpec * DviPageSpec
typedef struct _DviParams DviParams
typedef struct _DviBuffer DviBuffer
typedef struct _DviContext DviContext
typedef struct _DviRange DviRange
typedef struct _DviColorPair DviColorPair
typedef struct _DviSection DviSection
typedef struct _TFMChar TFMChar
typedef struct _TFMInfo TFMInfo
typedef struct _DviFontSearch DviFontSearch
typedef struct _DviFontClass DviFontClass
typedef void DviFreeFunc __PROTO((void *))
typedef Ulong DviColor
typedef long PageNum[11]
Enumerations
enum DviBool { FALSE = 0 , TRUE = 1 }
enum DviFontType {
DviFontAny = -1 , DviFontPK = 0 , DviFontGF = 1 , DviFontVF = 2 ,
DviFontTFM = 3 , DviFontT1 = 4 , DviFontTT = 5 , DviFontAFM = 6 ,
DviFontOFM = 7
}
enum DviOrientation {
MDVI_ORIENT_TBLR = 0 , MDVI_ORIENT_TBRL = 1 , MDVI_ORIENT_BTLR = 2 , MDVI_ORIENT_BTRL = 3 ,
MDVI_ORIENT_RP90 = 4 , MDVI_ORIENT_RM90 = 5 , MDVI_ORIENT_IRP90 = 6 , MDVI_ORIENT_IRM90 = 7
}
enum DviPageSort {
MDVI_PAGE_SORT_UP , MDVI_PAGE_SORT_DOWN , MDVI_PAGE_SORT_RANDOM , MDVI_PAGE_SORT_DVI_UP ,
MDVI_PAGE_SORT_DVI_DOWN , MDVI_PAGE_SORT_NONE
}
enum DviParamCode {
MDVI_PARAM_LAST = 0 , MDVI_SET_DPI = 1 , MDVI_SET_XDPI = 2 , MDVI_SET_YDPI = 3 ,
MDVI_SET_SHRINK = 4 , MDVI_SET_XSHRINK = 5 , MDVI_SET_YSHRINK = 6 , MDVI_SET_GAMMA = 7 ,
MDVI_SET_DENSITY = 8 , MDVI_SET_MAGNIFICATION = 9 , MDVI_SET_DRIFT = 10 , MDVI_SET_HDRIFT = 11 ,
MDVI_SET_VDRIFT = 12 , MDVI_SET_ORIENTATION = 13 , MDVI_SET_FOREGROUND = 14 , MDVI_SET_BACKGROUND = 15
}
enum DviRangeType { MDVI_RANGE_BOUNDED , MDVI_RANGE_LOWER , MDVI_RANGE_UPPER , MDVI_RANGE_UNBOUNDED }
Functions
int mdvi_reload __PROTO ((DviContext *, DviParams *))
void mdvi_setpage __PROTO ((DviContext *, int))
void mdvi_shrink_glyph __PROTO ((DviContext *, DviFont *, DviFontChar *, DviGlyph *))
int mdvi_configure __PROTO ((DviContext *, DviParamCode,...))
int get_tfm_chars __PROTO ((DviParams *, DviFont *, TFMInfo *, int))
int tfm_load_file __PROTO ((const char *, TFMInfo *))
TFMInfo *get_font_metrics __PROTO ((const char *, int, const char *))
char *lookup_font_metrics __PROTO ((const char *, int *))
void free_font_metrics __PROTO ((TFMInfo *))
void flush_font_metrics __PROTO ((void))
void mdvi_sort_pages __PROTO ((DviContext *, DviPageSort))
void mdvi_init_kpathsea __PROTO ((const char *, const char *, const char *, int, const char *))
DviContext *mdvi_init_context __PROTO ((DviParams *, DviPageSpec *, const char *))
void mdvi_destroy_context __PROTO ((DviContext *))
DviRange *mdvi_parse_range __PROTO ((const char *, DviRange *, int *, char **))
DviPageSpec *mdvi_parse_page_spec __PROTO ((const char *))
void mdvi_free_page_spec __PROTO ((DviPageSpec *))
int mdvi_in_range __PROTO ((DviRange *, int, int))
int mdvi_range_length __PROTO ((DviRange *, int))
int mdvi_page_selected __PROTO ((DviPageSpec *, PageNum, int))
int mdvi_register_special __PROTO ((const char *label, const char *prefix, const char *regex, DviSpecialHandler handler, int replace))
int mdvi_unregister_special __PROTO ((const char *prefix))
int mdvi_do_special __PROTO ((DviContext *dvi, char *dvi_special))
DviFontRef *font_reference __PROTO ((DviParams *params, Int32 dvi_id, const char *font_name, Int32 checksum, int xdpi, int ydpi, Int32 scale_factor))
void font_drop_one __PROTO ((DviFontRef *))
void font_reset_one_glyph __PROTO ((DviDevice *, DviFontChar *, int))
void font_reset_font_glyphs __PROTO ((DviDevice *, DviFont *, int))
void font_reset_chain_glyphs __PROTO ((DviDevice *, DviFontRef *, int))
DviFontRef *font_find_flat __PROTO ((DviContext *, Int32))
int font_reopen __PROTO ((DviFont *))
DviFontChar *font_get_glyph __PROTO ((DviContext *, DviFont *, int))
void font_transform_glyph __PROTO ((DviOrientation, DviGlyph *))
int font_free_unused __PROTO ((DviDevice *))
int mdvi_encode_font __PROTO ((DviParams *, DviFont *))
int mdvi_register_font_type __PROTO ((DviFontInfo *, int))
char **mdvi_list_font_class __PROTO ((int))
int mdvi_unregister_font_type __PROTO ((const char *, int))
char *mdvi_lookup_font __PROTO ((DviFontSearch *))
DviFont *mdvi_add_font __PROTO ((const char *, Int32, int, int, Int32))
int mdvi_set_logstream __PROTO ((FILE *))
Macro Definition Documentation
font_free_glyph
#define font_free_glyph (dev, font, code)
Value:
font_reset_one_glyph((dev), \
FONTCHAR((font), (code)), MDVI_FONTSEL_GLYPH)
Definition at line 596 of file mdvi.h.
FONT_GLYPH_COUNT
#define FONT_GLYPH_COUNT (font)
Value:
((font)->hic - (font)->loc + 1)
Definition at line 550 of file mdvi.h.
Referenced by get_tfm_chars().
FONTCHAR
#define FONTCHAR (font, code)
Value:
(((code) < font->loc || (code) > font->hic || !(font)->chars) ? \
    NULL : &font->chars[(code) - (font)->loc])
Definition at line 547 of file mdvi.h.
Referenced by font_get_glyph(), and set_char().
get_metrics
#define get_metrics (name)
Value:
get_font_metrics((name), DviFontAny, NULL)
Definition at line 490 of file mdvi.h.
glyph_present
#define glyph_present (x)
Value:
((x) && (x)->offset)
Definition at line 552 of file mdvi.h.
Referenced by font_get_glyph(), font_reset_font_glyphs(), font_reset_one_glyph(), and set_char().
ISVIRTUAL
#define ISVIRTUAL (font)
Value:
((font)->search.info->getglyph == NULL)
Definition at line 237 of file mdvi.h.
Referenced by set_char().
mdvi_config_one
#define mdvi_config_one (d, x, y)
Value:
mdvi_configure((d), (x), (y), MDVI_PARAM_LAST)
Definition at line 500 of file mdvi.h.
MDVI_CURRBG
#define MDVI_CURRBG (d)
Value:
(d)->curr_bg
Definition at line 466 of file mdvi.h.
Referenced by mdvi_shrink_glyph_grey().
MDVI_CURRFG
#define MDVI_CURRFG (d)
Value:
(d)->curr_fg
Definition at line 465 of file mdvi.h.
Referenced by mdvi_shrink_glyph_grey().
MDVI_DISABLED
#define MDVI_DISABLED (d, x)
Value:
!MDVI_ENABLED((d), (x))
Definition at line 458 of file mdvi.h.
MDVI_ENABLED
#define MDVI_ENABLED (d, x)
Value:
((d)->params.flags & (x))
Definition at line 457 of file mdvi.h.
Referenced by font_get_glyph().
MDVI_FLAGS
#define MDVI_FLAGS (d)
Value:
(d)->params.flags
Definition at line 463 of file mdvi.h.
MDVI_FONT_ENCODED
#define MDVI_FONT_ENCODED (1 << 0)
Definition at line 447 of file mdvi.h.
MDVI_FONTPRIO_FALLBACK
#define MDVI_FONTPRIO_FALLBACK -3
Definition at line 440 of file mdvi.h.
MDVI_FONTPRIO_HIGH
#define MDVI_FONTPRIO_HIGH 1
Definition at line 444 of file mdvi.h.
MDVI_FONTPRIO_HIGHEST
#define MDVI_FONTPRIO_HIGHEST 2
Definition at line 445 of file mdvi.h.
MDVI_FONTPRIO_LOW
#define MDVI_FONTPRIO_LOW -1
Definition at line 442 of file mdvi.h.
MDVI_FONTPRIO_LOWEST
#define MDVI_FONTPRIO_LOWEST -2
Definition at line 441 of file mdvi.h.
MDVI_FONTPRIO_NORMAL
#define MDVI_FONTPRIO_NORMAL 0
Definition at line 443 of file mdvi.h.
MDVI_FONTSEL_BITMAP
#define MDVI_FONTSEL_BITMAP (1 << 0)
Definition at line 543 of file mdvi.h.
Referenced by font_reset_font_glyphs(), font_reset_one_glyph(), and mdvi_configure().
MDVI_FONTSEL_GLYPH
#define MDVI_FONTSEL_GLYPH (1 << 2)
Definition at line 545 of file mdvi.h.
Referenced by font_free_unused(), font_reset_font_glyphs(), font_reset_one_glyph(), and mdvi_configure().
MDVI_FONTSEL_GREY
#define MDVI_FONTSEL_GREY (1 << 1)
Definition at line 544 of file mdvi.h.
Referenced by font_reset_font_glyphs(), font_reset_one_glyph(), and mdvi_configure().
MDVI_GLYPH_EMPTY
#define MDVI_GLYPH_EMPTY ((void *)1)
Definition at line 449 of file mdvi.h.
Referenced by mdvi_shrink_box().
MDVI_GLYPH_ISEMPTY
#define MDVI_GLYPH_ISEMPTY (x)
Value:
((x) == MDVI_GLYPH_EMPTY)
Definition at line 455 of file mdvi.h.
Referenced by font_get_glyph(), and font_transform_glyph().
MDVI_GLYPH_NONEMPTY
#define MDVI_GLYPH_NONEMPTY (x)
Value:
((x) && (x) != MDVI_GLYPH_EMPTY)
Definition at line 451 of file mdvi.h.
Referenced by font_reset_one_glyph().
MDVI_GLYPH_UNSET
#define MDVI_GLYPH_UNSET (x)
Value:
((x) == NULL)
Definition at line 453 of file mdvi.h.
Referenced by font_get_glyph().
MDVI_LASTPAGE
#define MDVI_LASTPAGE (d)
Value:
((d)->npages - 1)
Definition at line 460 of file mdvi.h.
MDVI_NPAGES
#define MDVI_NPAGES (d)
Value:
(d)->npages
Definition at line 461 of file mdvi.h.
MDVI_PARAM_ANTIALIASED
#define MDVI_PARAM_ANTIALIASED 1
Definition at line 429 of file mdvi.h.
Referenced by font_get_glyph().
MDVI_PARAM_CHARBOXES
#define MDVI_PARAM_CHARBOXES 4
Definition at line 431 of file mdvi.h.
MDVI_PARAM_DELAYFONTS
#define MDVI_PARAM_DELAYFONTS 16
Definition at line 433 of file mdvi.h.
MDVI_PARAM_MONO
#define MDVI_PARAM_MONO 2
Definition at line 430 of file mdvi.h.
MDVI_PARAM_SHOWUNDEF
#define MDVI_PARAM_SHOWUNDEF 8
Definition at line 432 of file mdvi.h.
mdvi_set_background
#define mdvi_set_background (d, x)
Value:
mdvi_config_one((d), MDVI_SET_BACKGROUND, (x))
Definition at line 515 of file mdvi.h.
mdvi_set_density
#define mdvi_set_density (d, x)
Value:
mdvi_config_one((d), MDVI_SET_DENSITY, (x))
Definition at line 507 of file mdvi.h.
mdvi_set_dpi
#define mdvi_set_dpi (d, x)
Value:
mdvi_config_one((d), MDVI_SET_DPI, (x))
Definition at line 501 of file mdvi.h.
mdvi_set_drift
#define mdvi_set_drift (d, x)
Value:
mdvi_config_one((d), MDVI_SET_DRIFT, (x))
Definition at line 508 of file mdvi.h.
mdvi_set_foreground
#define mdvi_set_foreground (d, x)
Value:
mdvi_config_one((d), MDVI_SET_FOREGROUND, (x))
Definition at line 513 of file mdvi.h.
mdvi_set_gamma
#define mdvi_set_gamma (d, g)
Value:
mdvi_config_one((d), MDVI_SET_GAMMA, (g))
Definition at line 506 of file mdvi.h.
mdvi_set_hdrift
#define mdvi_set_hdrift (d, h)
Value:
mdvi_config_one((d), MDVI_SET_HDRIFT, (h))
Definition at line 509 of file mdvi.h.
mdvi_set_hshrink
#define mdvi_set_hshrink (d, h)
Value:
mdvi_config_one((d), MDVI_SET_XSHRINK, (h))
Definition at line 504 of file mdvi.h.
mdvi_set_mag
#define mdvi_set_mag (d, m)
Value:
mdvi_config_one((d), MDVI_SET_MAGNIFICATION, (m))
Definition at line 511 of file mdvi.h.
mdvi_set_orientation
#define mdvi_set_orientation (d, x)
Value:
mdvi_config_one((d), MDVI_SET_ORIENTATION, (x))
Definition at line 517 of file mdvi.h.
mdvi_set_shrink
#define mdvi_set_shrink (d, h, v)
Value:
mdvi_configure((d), MDVI_SET_XSHRINK, (h), \
MDVI_SET_YSHRINK, (v), MDVI_PARAM_LAST)
Definition at line 519 of file mdvi.h.
mdvi_set_vdrift
#define mdvi_set_vdrift (d, v)
Value:
mdvi_config_one((d), MDVI_SET_VDRIFT, (v))
Definition at line 510 of file mdvi.h.
mdvi_set_vshrink
#define mdvi_set_vshrink (d, h)
Value:
mdvi_config_one((d), MDVI_SET_YSHRINK, (h))
Definition at line 505 of file mdvi.h.
mdvi_set_xdpi
#define mdvi_set_xdpi (d, x)
Value:
mdvi_config_one((d), MDVI_SET_XDPI, (x))
Definition at line 502 of file mdvi.h.
mdvi_set_ydpi
#define mdvi_set_ydpi (d, x)
Value:
mdvi_config_one((d), MDVI_SET_YDPI, (x))
Definition at line 503 of file mdvi.h.
MDVI_SHRINK_FROM_DPI
#define MDVI_SHRINK_FROM_DPI (d)
Value:
Max(1, (d) / 75)
Definition at line 464 of file mdvi.h.
mdvi_stop_logging
#define mdvi_stop_logging (x)
Value:
mdvi_set_logstream(NULL)
Definition at line 617 of file mdvi.h.
MDVI_VALIDPAGE
#define MDVI_VALIDPAGE (d, p)
Value:
((p) >= 0 && (p) <= MDVI_LASTPAGE(d))
Definition at line 462 of file mdvi.h.
pixel_round
#define pixel_round (d, v)
Value:
(int)((d)->params.conv * (v) + 0.5)
Definition at line 468 of file mdvi.h.
Referenced by set_char().
RANGE_HAS_LOWER
#define RANGE_HAS_LOWER (x)
Value:
((x) == MDVI_RANGE_BOUNDED || (x) == MDVI_RANGE_LOWER)
Definition at line 420 of file mdvi.h.
Referenced by mdvi_parse_range().
RANGE_HAS_UPPER
#define RANGE_HAS_UPPER (x)
Value:
((x) == MDVI_RANGE_BOUNDED || (x) == MDVI_RANGE_UPPER)
Definition at line 422 of file mdvi.h.
Referenced by mdvi_parse_range().
rule_round
#define rule_round (d, v)
Value:
(int)((d)->params.conv * (v) + 0.99999) /*9999999)*/
Definition at line 470 of file mdvi.h.
Referenced by set_rule().
SEARCH_DONE
#define SEARCH_DONE (s)
Value:
((s).id < 0)
Definition at line 238 of file mdvi.h.
SEARCH_INIT
#define SEARCH_INIT (s, name, h, v)
Value:
do { \
(s).id = 0; \
(s).curr = NULL; \
(s).hdpi = (h); \
(s).vdpi = (v); \
(s).wanted_name = (name); \
(s).actual_name = NULL; \
} while(0)
Definition at line 239 of file mdvi.h.
Referenced by mdvi_add_font().
vpixel_round
#define vpixel_round (d, v)
Value:
(int)((d)->params.vconv * (v) + 0.5)
Definition at line 469 of file mdvi.h.
vrule_round
#define vrule_round (d, v)
Value:
(int)((d)->params.vconv * (v) + 0.99999)
Definition at line 471 of file mdvi.h.
Referenced by set_rule().
Typedef Documentation
__PROTO
typedef void DviSpecialHandler __PROTO((DviContext *dvi, const char *prefix, const char *arg))
Definition at line 51 of file mdvi.h.
DviBuffer
typedef struct _DviBuffer DviBuffer
Definition at line 40 of file mdvi.h.
DviColor
typedef Ulong DviColor
Definition at line 54 of file mdvi.h.
DviColorPair
typedef struct _DviColorPair DviColorPair
Definition at line 43 of file mdvi.h.
DviContext
typedef struct _DviContext DviContext
Definition at line 41 of file mdvi.h.
DviDevice
typedef struct _DviDevice DviDevice
Definition at line 32 of file mdvi.h.
DviFont
typedef struct _DviFont DviFont
Definition at line 36 of file mdvi.h.
DviFontChar
typedef struct _DviFontChar DviFontChar
Definition at line 33 of file mdvi.h.
DviFontClass
typedef struct _DviFontClass DviFontClass
Definition at line 49 of file mdvi.h.
DviFontInfo
typedef struct _DviFontInfo DviFontInfo
Definition at line 35 of file mdvi.h.
DviFontRef
typedef struct _DviFontRef DviFontRef
Definition at line 34 of file mdvi.h.
DviFontSearch
typedef struct _DviFontSearch DviFontSearch
Definition at line 47 of file mdvi.h.
DviGlyph
typedef struct _DviGlyph DviGlyph
Definition at line 31 of file mdvi.h.
DviPageSpec
typedef struct _DviPageSpec* DviPageSpec
Definition at line 38 of file mdvi.h.
DviParams
typedef struct _DviParams DviParams
Definition at line 39 of file mdvi.h.
DviRange
typedef struct _DviRange DviRange
Definition at line 42 of file mdvi.h.
DviSection
typedef struct _DviSection DviSection
Definition at line 44 of file mdvi.h.
DviState
typedef struct _DviState DviState
Definition at line 37 of file mdvi.h.
PageNum
typedef long PageNum[11]
Definition at line 76 of file mdvi.h.
TFMChar
typedef struct _TFMChar TFMChar
Definition at line 45 of file mdvi.h.
TFMInfo
typedef struct _TFMInfo TFMInfo
Definition at line 46 of file mdvi.h.
Enumeration Type Documentation
DviBool
enum DviBool
Enumerator
FALSE
TRUE
Definition at line 63 of file mdvi.h.
DviFontType
enum DviFontType
Enumerator
DviFontAny
DviFontPK
DviFontGF
DviFontVF
DviFontTFM
DviFontT1
DviFontTT
DviFontAFM
DviFontOFM
Definition at line 212 of file mdvi.h.
DviOrientation
enum DviOrientation
Enumerator
MDVI_ORIENT_TBLR
MDVI_ORIENT_TBRL
MDVI_ORIENT_BTLR
MDVI_ORIENT_BTRL
MDVI_ORIENT_RP90
MDVI_ORIENT_RM90
MDVI_ORIENT_IRP90
MDVI_ORIENT_IRM90
Definition at line 274 of file mdvi.h.
DviPageSort
enum DviPageSort
Enumerator
MDVI_PAGE_SORT_UP
MDVI_PAGE_SORT_DOWN
MDVI_PAGE_SORT_RANDOM
MDVI_PAGE_SORT_DVI_UP
MDVI_PAGE_SORT_DVI_DOWN
MDVI_PAGE_SORT_NONE
Definition at line 285 of file mdvi.h.
DviParamCode
enum DviParamCode
Enumerator
MDVI_PARAM_LAST
MDVI_SET_DPI
MDVI_SET_XDPI
MDVI_SET_YDPI
MDVI_SET_SHRINK
MDVI_SET_XSHRINK
MDVI_SET_YSHRINK
MDVI_SET_GAMMA
MDVI_SET_DENSITY
MDVI_SET_MAGNIFICATION
MDVI_SET_DRIFT
MDVI_SET_HDRIFT
MDVI_SET_VDRIFT
MDVI_SET_ORIENTATION
MDVI_SET_FOREGROUND
MDVI_SET_BACKGROUND
Definition at line 318 of file mdvi.h.
DviRangeType
enum DviRangeType
Enumerator
MDVI_RANGE_BOUNDED
MDVI_RANGE_LOWER
MDVI_RANGE_UPPER
MDVI_RANGE_UNBOUNDED
Definition at line 403 of file mdvi.h.
Function Documentation
__PROTO() [1/40]
DviPageSpec *mdvi_parse_page_spec __PROTO ((const char *)) extern
References mdvi_parse_page_spec().
__PROTO() [2/40]
void mdvi_init_kpathsea __PROTO ((const char *, const char *, const char *, int, const char *)) extern
References mdvi_init_kpathsea().
__PROTO() [3/40]
DviRange *mdvi_parse_range __PROTO ((const char *, DviRange *, int *, char **)) extern
References mdvi_parse_range().
__PROTO() [4/40]
char *lookup_font_metrics __PROTO ((const char *, int *)) extern
References lookup_font_metrics().
__PROTO() [5/40]
int mdvi_unregister_font_type __PROTO ((const char *, int)) extern
References mdvi_unregister_font_type().
__PROTO() [6/40]
TFMInfo *get_font_metrics __PROTO ((const char *, int, const char *)) extern
References get_font_metrics().
__PROTO() [7/40]
DviFont *mdvi_add_font __PROTO ((const char *, Int32, int, int, Int32)) extern
References mdvi_add_font(), mdvi_font_retry(), and mdvi_set_logfile().
__PROTO() [8/40]
int tfm_load_file __PROTO ((const char *, TFMInfo *)) extern
References tfm_load_file().
__PROTO() [9/40]
int mdvi_register_special __PROTO ((const char *label, const char *prefix, const char *regex, DviSpecialHandler handler, int replace)) extern
References handler, label, mdvi_register_special(), prefix, and regex.
__PROTO() [10/40]
int mdvi_unregister_special __PROTO ((const char *prefix)) extern
References mdvi_unregister_special(), and prefix.
__PROTO() [11/40]
void mdvi_destroy_context __PROTO ((DviContext *)) extern
References mdvi_destroy_context().
__PROTO() [12/40]
void mdvi_shrink_glyph __PROTO ((DviContext *, DviFont *, DviFontChar *, DviGlyph *)) extern
References mdvi_find_tex_page(), mdvi_shrink_box(), mdvi_shrink_glyph(), and mdvi_shrink_glyph_grey().
__PROTO() [13/40]
DviFontChar *font_get_glyph __PROTO ((DviContext *, DviFont *, int)) extern
References font_get_glyph().
__PROTO() [14/40]
void mdvi_sort_pages __PROTO ((DviContext *, DviPageSort)) extern
References mdvi_sort_pages().
__PROTO() [15/40]
int mdvi_configure __PROTO ((DviContext *, DviParamCode,...)) extern
References mdvi_configure().
__PROTO() [16/40]
int mdvi_reload __PROTO ((DviContext *, DviParams *)) extern
References mdvi_reload().
__PROTO() [17/40]
void mdvi_setpage __PROTO ((DviContext *, int)) extern
References mdvi_dopage(), and mdvi_setpage().
__PROTO() [18/40]
DviFontRef *font_find_flat __PROTO ((DviContext *, Int32)) extern
References font_find_flat(), and font_find_mapped().
__PROTO() [19/40]
int mdvi_do_special __PROTO ((DviContext *dvi, char *dvi_special)) extern
References mdvi_do_special(), and mdvi_flush_specials().
__PROTO() [20/40]
int font_free_unused __PROTO ((DviDevice *)) extern
References font_free_unused().
__PROTO() [21/40]
void font_reset_font_glyphs __PROTO ((DviDevice *, DviFont *, int)) extern
References font_reset_font_glyphs().
__PROTO() [22/40]
void font_reset_one_glyph __PROTO ((DviDevice *, DviFontChar *, int)) extern
References font_reset_one_glyph().
__PROTO() [23/40]
void font_reset_chain_glyphs __PROTO ((DviDevice *, DviFontRef *, int)) extern
References font_finish_definitions(), and font_reset_chain_glyphs().
__PROTO() [24/40]
int font_reopen __PROTO ((DviFont *)) extern
References font_reopen().
__PROTO() [25/40]
int mdvi_register_font_type __PROTO ((DviFontInfo *, int)) extern
References mdvi_register_font_type().
__PROTO() [26/40]
void font_drop_one __PROTO ((DviFontRef *)) extern
References font_drop_chain(), and font_drop_one().
__PROTO() [27/40]
char *mdvi_lookup_font __PROTO ((DviFontSearch *)) extern
References mdvi_lookup_font().
__PROTO() [28/40]
void font_transform_glyph __PROTO ((DviOrientation, DviGlyph *)) extern
References font_transform_glyph().
__PROTO() [29/40]
void mdvi_free_page_spec __PROTO ((DviPageSpec *)) extern
References mdvi_free_page_spec().
__PROTO() [30/40]
int mdvi_page_selected __PROTO ((DviPageSpec *, PageNum, int)) extern
References mdvi_page_selected().
__PROTO() [31/40]
int mdvi_encode_font __PROTO ((DviParams *, DviFont *)) extern
__PROTO() [32/40]
int get_tfm_chars __PROTO ((DviParams *, DviFont *, TFMInfo *, int)) extern
References get_tfm_chars().
__PROTO() [33/40]
DviContext *mdvi_init_context __PROTO ((DviParams *, DviPageSpec *, const char *)) extern
References mdvi_init_context().
__PROTO() [34/40]
DviFontRef *font_reference __PROTO ((DviParams *params, Int32 dvi_id, const char *font_name, Int32 checksum, int xdpi, int ydpi, Int32 scale_factor)) extern
References font_reference().
__PROTO() [35/40]
int mdvi_range_length __PROTO ((DviRange *, int)) extern
References mdvi_range_length().
__PROTO() [36/40]
int mdvi_in_range __PROTO ((DviRange *, int, int)) extern
References mdvi_in_range().
__PROTO() [37/40]
int mdvi_set_logstream __PROTO ((FILE *)) extern
References mdvi_set_loglevel(), and mdvi_set_logstream().
__PROTO() [38/40]
char **mdvi_list_font_class __PROTO ((int)) extern
References mdvi_get_font_classes(), and mdvi_list_font_class().
__PROTO() [39/40]
void free_font_metrics __PROTO ((TFMInfo *)) extern
References free_font_metrics().
__PROTO() [40/40]
void flush_font_metrics __PROTO ((void)) extern
References flush_font_metrics().