MATE Desktop Environment: menu-layout.c File Reference
menu-layout.c File Reference
#include <config.h>
#include "menu-layout.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include "entry-directories.h"
#include "menu-util.h"
Macros
#define RETURN_IF_NO_PARENT(node)
#define RETURN_IF_HAS_ENTRY_DIRS(node)
#define ELEMENT_IS(name)
#define MAX_ATTRS 24
Typedefs
typedef struct MenuLayoutNodeMenu MenuLayoutNodeMenu
typedef struct MenuLayoutNodeRoot MenuLayoutNodeRoot
typedef struct MenuLayoutNodeLegacyDir MenuLayoutNodeLegacyDir
typedef struct MenuLayoutNodeMergeFile MenuLayoutNodeMergeFile
typedef struct MenuLayoutNodeDefaultLayout MenuLayoutNodeDefaultLayout
typedef struct MenuLayoutNodeMenuname MenuLayoutNodeMenuname
typedef struct MenuLayoutNodeMerge MenuLayoutNodeMerge
Functions
MenuLayoutNode * menu_layout_node_ref (MenuLayoutNode *node)
void menu_layout_node_unref (MenuLayoutNode *node)
MenuLayoutNode * menu_layout_node_new (MenuLayoutNodeType type)
MenuLayoutNode * menu_layout_node_get_next (MenuLayoutNode *node)
MenuLayoutNode * menu_layout_node_get_parent (MenuLayoutNode *node)
MenuLayoutNode * menu_layout_node_get_children (MenuLayoutNode *node)
MenuLayoutNode * menu_layout_node_get_root (MenuLayoutNode *node)
char * menu_layout_node_get_content_as_path (MenuLayoutNode *node)
void menu_layout_node_insert_before (MenuLayoutNode *node, MenuLayoutNode *new_sibling)
void menu_layout_node_insert_after (MenuLayoutNode *node, MenuLayoutNode *new_sibling)
void menu_layout_node_prepend_child (MenuLayoutNode *parent, MenuLayoutNode *new_child)
void menu_layout_node_append_child (MenuLayoutNode *parent, MenuLayoutNode *new_child)
void menu_layout_node_unlink (MenuLayoutNode *node)
void menu_layout_node_steal (MenuLayoutNode *node)
MenuLayoutNodeType menu_layout_node_get_type (MenuLayoutNode *node)
const char * menu_layout_node_get_content (MenuLayoutNode *node)
void menu_layout_node_set_content (MenuLayoutNode *node, const char *content)
const char * menu_layout_node_root_get_name (MenuLayoutNode *node)
const char * menu_layout_node_root_get_basedir (MenuLayoutNode *node)
const char * menu_layout_node_menu_get_name (MenuLayoutNode *node)
EntryDirectoryList * menu_layout_node_menu_get_app_dirs (MenuLayoutNode *node)
EntryDirectoryList * menu_layout_node_menu_get_directory_dirs (MenuLayoutNode *node)
const char * menu_layout_node_move_get_old (MenuLayoutNode *node)
const char * menu_layout_node_move_get_new (MenuLayoutNode *node)
const char * menu_layout_node_legacy_dir_get_prefix (MenuLayoutNode *node)
void menu_layout_node_legacy_dir_set_prefix (MenuLayoutNode *node, const char *prefix)
MenuMergeFileType menu_layout_node_merge_file_get_type (MenuLayoutNode *node)
void menu_layout_node_merge_file_set_type (MenuLayoutNode *node, MenuMergeFileType type)
MenuLayoutMergeType menu_layout_node_merge_get_type (MenuLayoutNode *node)
void menu_layout_node_default_layout_get_values (MenuLayoutNode *node, MenuLayoutValues *values)
void menu_layout_node_menuname_get_values (MenuLayoutNode *node, MenuLayoutValues *values)
void menu_layout_node_root_add_entries_monitor (MenuLayoutNode *node, MenuLayoutNodeEntriesChangedFunc callback, gpointer user_data)
void menu_layout_node_root_remove_entries_monitor (MenuLayoutNode *node, MenuLayoutNodeEntriesChangedFunc callback, gpointer user_data)
MenuLayoutNode * menu_layout_load (const char *filename, const char *non_prefixed_basename, GError **err)
Macro Definition Documentation
ELEMENT_IS
#define ELEMENT_IS (name)
Value:
(strcmp (element_name, (name)) == 0)
Definition at line 1224 of file menu-layout.c.
MAX_ATTRS
#define MAX_ATTRS 24
RETURN_IF_HAS_ENTRY_DIRS
#define RETURN_IF_HAS_ENTRY_DIRS (node)
Value:
  G_STMT_START {             \
  if ((node)->type == MENU_LAYOUT_NODE_MENU &&                  \
      (((MenuLayoutNodeMenu*)(node))->app_dirs != NULL ||       \
       ((MenuLayoutNodeMenu*)(node))->dir_dirs != NULL))        \
    {                                                           \
      g_warning ("node acquired ->app_dirs or ->dir_dirs "      \
                 "while not rooted in a tree\n");               \
      return;                                                   \
    }                                                           \
} G_STMT_END                                                    \
Definition at line 395 of file menu-layout.c.
Referenced by menu_layout_node_append_child(), menu_layout_node_insert_after(), menu_layout_node_insert_before(), and menu_layout_node_prepend_child().
RETURN_IF_NO_PARENT
#define RETURN_IF_NO_PARENT (node)
Value:
  G_STMT_START {                  \
  if ((node)->parent == NULL)                                   \
    {                                                           \
      g_warning ("To add siblings to a menu node, "             \
                 "it must not be the root node, "               \
                 "and must be linked in below some root node\n" \
                 "node parent = %p and type = %d",              \
                 (node)->parent, (node)->type);                 \
      return;                                                   \
    }                                                           \
} G_STMT_END
Definition at line 383 of file menu-layout.c.
Referenced by menu_layout_node_insert_after(), and menu_layout_node_insert_before().
Typedef Documentation
MenuLayoutNodeDefaultLayout
typedef struct MenuLayoutNodeDefaultLayout MenuLayoutNodeDefaultLayout
Definition at line 40 of file menu-layout.c.
MenuLayoutNodeLegacyDir
typedef struct MenuLayoutNodeLegacyDir MenuLayoutNodeLegacyDir
Definition at line 38 of file menu-layout.c.
MenuLayoutNodeMenu
typedef struct MenuLayoutNodeMenu MenuLayoutNodeMenu
Definition at line 36 of file menu-layout.c.
MenuLayoutNodeMenuname
typedef struct MenuLayoutNodeMenuname MenuLayoutNodeMenuname
Definition at line 41 of file menu-layout.c.
MenuLayoutNodeMerge
typedef struct MenuLayoutNodeMerge MenuLayoutNodeMerge
Definition at line 42 of file menu-layout.c.
MenuLayoutNodeMergeFile
typedef struct MenuLayoutNodeMergeFile MenuLayoutNodeMergeFile
Definition at line 39 of file menu-layout.c.
MenuLayoutNodeRoot
typedef struct MenuLayoutNodeRoot MenuLayoutNodeRoot
Definition at line 37 of file menu-layout.c.
Function Documentation
menu_layout_load()
MenuLayoutNode * menu_layout_load (const char * filename, const char * non_prefixed_basename, GError ** err)
Definition at line 2296 of file menu-layout.c.
References error, FALSE, MENU_LAYOUT_NODE_MENU, and NULL.
menu_layout_node_append_child()
void menu_layout_node_append_child (MenuLayoutNode * parent, MenuLayoutNode * new_child)
Definition at line 469 of file menu-layout.c.
References menu_layout_node_insert_after(), menu_layout_node_ref(), and RETURN_IF_HAS_ENTRY_DIRS.
menu_layout_node_default_layout_get_values()
void menu_layout_node_default_layout_get_values (MenuLayoutNode * node, MenuLayoutValues * values)
Definition at line 944 of file menu-layout.c.
References MENU_LAYOUT_NODE_DEFAULT_LAYOUT, and NULL.
menu_layout_node_get_children()
MenuLayoutNode * menu_layout_node_get_children (MenuLayoutNode * node)
Definition at line 330 of file menu-layout.c.
menu_layout_node_get_content()
const char * menu_layout_node_get_content (MenuLayoutNode * node)
Definition at line 583 of file menu-layout.c.
Referenced by menu_layout_node_menu_get_name().
menu_layout_node_get_content_as_path()
char * menu_layout_node_get_content_as_path (MenuLayoutNode * node)
Definition at line 350 of file menu-layout.c.
References menu_layout_node_get_root(), and NULL.
menu_layout_node_get_next()
MenuLayoutNode * menu_layout_node_get_next (MenuLayoutNode * node)
Definition at line 318 of file menu-layout.c.
menu_layout_node_get_parent()
MenuLayoutNode * menu_layout_node_get_parent (MenuLayoutNode * node)
Definition at line 324 of file menu-layout.c.
menu_layout_node_get_root()
MenuLayoutNode * menu_layout_node_get_root (MenuLayoutNode * node)
Definition at line 336 of file menu-layout.c.
References MENU_LAYOUT_NODE_ROOT, and NULL.
Referenced by menu_layout_node_get_content_as_path().
menu_layout_node_get_type()
MenuLayoutNodeType menu_layout_node_get_type (MenuLayoutNode * node)
Definition at line 577 of file menu-layout.c.
menu_layout_node_insert_after()
void menu_layout_node_insert_after (MenuLayoutNode * node, MenuLayoutNode * new_sibling)
Definition at line 431 of file menu-layout.c.
References menu_layout_node_ref(), NULL, RETURN_IF_HAS_ENTRY_DIRS, and RETURN_IF_NO_PARENT.
Referenced by menu_layout_node_append_child().
menu_layout_node_insert_before()
void menu_layout_node_insert_before (MenuLayoutNode * node, MenuLayoutNode * new_sibling)
Definition at line 407 of file menu-layout.c.
References menu_layout_node_ref(), NULL, RETURN_IF_HAS_ENTRY_DIRS, and RETURN_IF_NO_PARENT.
Referenced by menu_layout_node_prepend_child().
menu_layout_node_legacy_dir_get_prefix()
const char * menu_layout_node_legacy_dir_get_prefix (MenuLayoutNode * node)
Definition at line 855 of file menu-layout.c.
References MENU_LAYOUT_NODE_LEGACY_DIR, and NULL.
menu_layout_node_legacy_dir_set_prefix()
void menu_layout_node_legacy_dir_set_prefix (MenuLayoutNode * node, const char * prefix)
Definition at line 867 of file menu-layout.c.
References MENU_LAYOUT_NODE_LEGACY_DIR, and prefix.
menu_layout_node_menu_get_app_dirs()
EntryDirectoryList * menu_layout_node_menu_get_app_dirs (MenuLayoutNode * node)
Definition at line 793 of file menu-layout.c.
References MENU_LAYOUT_NODE_MENU, and NULL.
menu_layout_node_menu_get_directory_dirs()
EntryDirectoryList * menu_layout_node_menu_get_directory_dirs (MenuLayoutNode * node)
Definition at line 807 of file menu-layout.c.
References MENU_LAYOUT_NODE_MENU, and NULL.
menu_layout_node_menu_get_name()
const char * menu_layout_node_menu_get_name (MenuLayoutNode * node)
Definition at line 624 of file menu-layout.c.
References menu_layout_node_get_content(), MENU_LAYOUT_NODE_MENU, MENU_LAYOUT_NODE_NAME, menu_layout_node_ref(), and NULL.
menu_layout_node_menuname_get_values()
void menu_layout_node_menuname_get_values (MenuLayoutNode * node, MenuLayoutValues * values)
Definition at line 958 of file menu-layout.c.
References MENU_LAYOUT_NODE_MENUNAME, and NULL.
menu_layout_node_merge_file_get_type()
MenuMergeFileType menu_layout_node_merge_file_get_type (MenuLayoutNode * node)
Definition at line 881 of file menu-layout.c.
References FALSE, and MENU_LAYOUT_NODE_MERGE_FILE.
menu_layout_node_merge_file_set_type()
void menu_layout_node_merge_file_set_type (MenuLayoutNode * node, MenuMergeFileType type)
Definition at line 893 of file menu-layout.c.
References MENU_LAYOUT_NODE_MERGE_FILE.
menu_layout_node_merge_get_type()
MenuLayoutMergeType menu_layout_node_merge_get_type (MenuLayoutNode * node)
Definition at line 906 of file menu-layout.c.
References MENU_LAYOUT_NODE_MERGE.
menu_layout_node_move_get_new()
const char * menu_layout_node_move_get_new (MenuLayoutNode * node)
Definition at line 838 of file menu-layout.c.
References MENU_LAYOUT_NODE_NEW, and NULL.
menu_layout_node_move_get_old()
const char * menu_layout_node_move_get_old (MenuLayoutNode * node)
Definition at line 821 of file menu-layout.c.
References MENU_LAYOUT_NODE_OLD, and NULL.
menu_layout_node_new()
MenuLayoutNode * menu_layout_node_new (MenuLayoutNodeType type)
Definition at line 267 of file menu-layout.c.
References MENU_LAYOUT_NODE_DEFAULT_LAYOUT, MENU_LAYOUT_NODE_LEGACY_DIR, MENU_LAYOUT_NODE_MENU, MENU_LAYOUT_NODE_MENUNAME, MENU_LAYOUT_NODE_MERGE, MENU_LAYOUT_NODE_MERGE_FILE, and MENU_LAYOUT_NODE_ROOT.
menu_layout_node_prepend_child()
void menu_layout_node_prepend_child (MenuLayoutNode * parent, MenuLayoutNode * new_child)
Definition at line 452 of file menu-layout.c.
References menu_layout_node_insert_before(), menu_layout_node_ref(), and RETURN_IF_HAS_ENTRY_DIRS.
menu_layout_node_ref()
MenuLayoutNode * menu_layout_node_ref (MenuLayoutNode * node)
Definition at line 196 of file menu-layout.c.
References NULL.
Referenced by menu_layout_node_append_child(), menu_layout_node_insert_after(), menu_layout_node_insert_before(), menu_layout_node_menu_get_name(), and menu_layout_node_prepend_child().
menu_layout_node_root_add_entries_monitor()
void menu_layout_node_root_add_entries_monitor (MenuLayoutNode * node, MenuLayoutNodeEntriesChangedFunc callback, gpointer user_data)
Definition at line 1069 of file menu-layout.c.
References MENU_LAYOUT_NODE_ROOT, NULL, and user_data.
menu_layout_node_root_get_basedir()
const char * menu_layout_node_root_get_basedir (MenuLayoutNode * node)
Definition at line 612 of file menu-layout.c.
References MENU_LAYOUT_NODE_ROOT, and NULL.
menu_layout_node_root_get_name()
const char * menu_layout_node_root_get_name (MenuLayoutNode * node)
Definition at line 600 of file menu-layout.c.
References MENU_LAYOUT_NODE_ROOT, and NULL.
menu_layout_node_root_remove_entries_monitor()
void menu_layout_node_root_remove_entries_monitor (MenuLayoutNode * node, MenuLayoutNodeEntriesChangedFunc callback, gpointer user_data)
Definition at line 1104 of file menu-layout.c.
References MENU_LAYOUT_NODE_ROOT, NULL, and user_data.
menu_layout_node_set_content()
void menu_layout_node_set_content (MenuLayoutNode * node, const char * content)
Definition at line 589 of file menu-layout.c.
menu_layout_node_steal()
void menu_layout_node_steal (MenuLayoutNode * node)
Definition at line 526 of file menu-layout.c.
References FALSE, MENU_LAYOUT_NODE_APP_DIR, MENU_LAYOUT_NODE_DIRECTORY_DIR, MENU_LAYOUT_NODE_NAME, menu_layout_node_unref(), NULL, and TRUE.
Referenced by menu_layout_node_unlink().
menu_layout_node_unlink()
void menu_layout_node_unlink (MenuLayoutNode * node)
Definition at line 486 of file menu-layout.c.
References menu_layout_node_steal(), menu_layout_node_unref(), and NULL.
menu_layout_node_unref()
void menu_layout_node_unref (MenuLayoutNode * node)
Definition at line 206 of file menu-layout.c.
References MENU_LAYOUT_NODE_LEGACY_DIR, MENU_LAYOUT_NODE_MENU, MENU_LAYOUT_NODE_ROOT, menu_layout_node_unref(), and NULL.
Referenced by menu_layout_node_steal(), menu_layout_node_unlink(), and menu_layout_node_unref().