MATE Desktop Environment: menu-layout.h File Reference
menu-layout.h File Reference
#include <glib.h>
#include "entry-directories.h"
Classes
struct MenuLayoutValues
Typedefs
typedef struct MenuLayoutNode MenuLayoutNode
typedef void(* MenuLayoutNodeEntriesChangedFunc) (MenuLayoutNode *node, gpointer user_data)
Enumerations
enum MenuLayoutNodeType {
MENU_LAYOUT_NODE_ROOT , MENU_LAYOUT_NODE_PASSTHROUGH , MENU_LAYOUT_NODE_MENU , MENU_LAYOUT_NODE_APP_DIR ,
MENU_LAYOUT_NODE_DEFAULT_APP_DIRS , MENU_LAYOUT_NODE_DIRECTORY_DIR , MENU_LAYOUT_NODE_DEFAULT_DIRECTORY_DIRS , MENU_LAYOUT_NODE_DEFAULT_MERGE_DIRS ,
MENU_LAYOUT_NODE_NAME , MENU_LAYOUT_NODE_DIRECTORY , MENU_LAYOUT_NODE_ONLY_UNALLOCATED , MENU_LAYOUT_NODE_NOT_ONLY_UNALLOCATED ,
MENU_LAYOUT_NODE_INCLUDE , MENU_LAYOUT_NODE_EXCLUDE , MENU_LAYOUT_NODE_FILENAME , MENU_LAYOUT_NODE_CATEGORY ,
MENU_LAYOUT_NODE_ALL , MENU_LAYOUT_NODE_AND , MENU_LAYOUT_NODE_OR , MENU_LAYOUT_NODE_NOT ,
MENU_LAYOUT_NODE_MERGE_FILE , MENU_LAYOUT_NODE_MERGE_DIR , MENU_LAYOUT_NODE_LEGACY_DIR , MENU_LAYOUT_NODE_KDE_LEGACY_DIRS ,
MENU_LAYOUT_NODE_MOVE , MENU_LAYOUT_NODE_OLD , MENU_LAYOUT_NODE_NEW , MENU_LAYOUT_NODE_DELETED ,
MENU_LAYOUT_NODE_NOT_DELETED , MENU_LAYOUT_NODE_LAYOUT , MENU_LAYOUT_NODE_DEFAULT_LAYOUT , MENU_LAYOUT_NODE_MENUNAME ,
MENU_LAYOUT_NODE_SEPARATOR , MENU_LAYOUT_NODE_MERGE
}
enum MenuMergeFileType { MENU_MERGE_FILE_TYPE_PATH = 0 , MENU_MERGE_FILE_TYPE_PARENT }
enum MenuLayoutMergeType { MENU_LAYOUT_MERGE_NONE , MENU_LAYOUT_MERGE_MENUS , MENU_LAYOUT_MERGE_FILES , MENU_LAYOUT_MERGE_ALL }
enum MenuLayoutValuesMask {
MENU_LAYOUT_VALUES_NONE = 0 , MENU_LAYOUT_VALUES_SHOW_EMPTY = 1 << 0 , MENU_LAYOUT_VALUES_INLINE_MENUS = 1 << 1 , MENU_LAYOUT_VALUES_INLINE_LIMIT = 1 << 2 ,
MENU_LAYOUT_VALUES_INLINE_HEADER = 1 << 3 , MENU_LAYOUT_VALUES_INLINE_ALIAS = 1 << 4
}
Functions
MenuLayoutNode * menu_layout_load (const char *filename, const char *non_prefixed_basename, GError **error)
MenuLayoutNode * menu_layout_node_new (MenuLayoutNodeType type)
MenuLayoutNode * menu_layout_node_ref (MenuLayoutNode *node)
void menu_layout_node_unref (MenuLayoutNode *node)
MenuLayoutNodeType menu_layout_node_get_type (MenuLayoutNode *node)
MenuLayoutNode * menu_layout_node_get_root (MenuLayoutNode *node)
MenuLayoutNode * menu_layout_node_get_parent (MenuLayoutNode *node)
MenuLayoutNode * menu_layout_node_get_children (MenuLayoutNode *node)
MenuLayoutNode * menu_layout_node_get_next (MenuLayoutNode *node)
void menu_layout_node_insert_before (MenuLayoutNode *node, MenuLayoutNode *new_sibling)
void menu_layout_node_insert_after (MenuLayoutNode *node, MenuLayoutNode *new_sibling)
void menu_layout_node_prepend_child (MenuLayoutNode *parent, MenuLayoutNode *new_child)
void menu_layout_node_append_child (MenuLayoutNode *parent, MenuLayoutNode *new_child)
void menu_layout_node_unlink (MenuLayoutNode *node)
void menu_layout_node_steal (MenuLayoutNode *node)
const char * menu_layout_node_get_content (MenuLayoutNode *node)
void menu_layout_node_set_content (MenuLayoutNode *node, const char *content)
char * menu_layout_node_get_content_as_path (MenuLayoutNode *node)
const char * menu_layout_node_root_get_name (MenuLayoutNode *node)
const char * menu_layout_node_root_get_basedir (MenuLayoutNode *node)
const char * menu_layout_node_menu_get_name (MenuLayoutNode *node)
EntryDirectoryList * menu_layout_node_menu_get_app_dirs (MenuLayoutNode *node)
EntryDirectoryList * menu_layout_node_menu_get_directory_dirs (MenuLayoutNode *node)
const char * menu_layout_node_move_get_old (MenuLayoutNode *node)
const char * menu_layout_node_move_get_new (MenuLayoutNode *node)
const char * menu_layout_node_legacy_dir_get_prefix (MenuLayoutNode *node)
void menu_layout_node_legacy_dir_set_prefix (MenuLayoutNode *node, const char *prefix)
MenuMergeFileType menu_layout_node_merge_file_get_type (MenuLayoutNode *node)
void menu_layout_node_merge_file_set_type (MenuLayoutNode *node, MenuMergeFileType type)
MenuLayoutMergeType menu_layout_node_merge_get_type (MenuLayoutNode *node)
void menu_layout_node_default_layout_get_values (MenuLayoutNode *node, MenuLayoutValues *values)
void menu_layout_node_menuname_get_values (MenuLayoutNode *node, MenuLayoutValues *values)
void menu_layout_node_root_add_entries_monitor (MenuLayoutNode *node, MenuLayoutNodeEntriesChangedFunc callback, gpointer user_data)
void menu_layout_node_root_remove_entries_monitor (MenuLayoutNode *node, MenuLayoutNodeEntriesChangedFunc callback, gpointer user_data)
Typedef Documentation
MenuLayoutNode
typedef struct MenuLayoutNode MenuLayoutNode
Definition at line 32 of file menu-layout.h.
MenuLayoutNodeEntriesChangedFunc
typedef void(* MenuLayoutNodeEntriesChangedFunc) (MenuLayoutNode *node, gpointer user_data)
Definition at line 151 of file menu-layout.h.
Enumeration Type Documentation
MenuLayoutMergeType
enum MenuLayoutMergeType
Enumerator
MENU_LAYOUT_MERGE_NONE
MENU_LAYOUT_MERGE_MENUS
MENU_LAYOUT_MERGE_FILES
MENU_LAYOUT_MERGE_ALL
Definition at line 76 of file menu-layout.h.
MenuLayoutNodeType
enum MenuLayoutNodeType
Enumerator
MENU_LAYOUT_NODE_ROOT
MENU_LAYOUT_NODE_PASSTHROUGH
MENU_LAYOUT_NODE_MENU
MENU_LAYOUT_NODE_APP_DIR
MENU_LAYOUT_NODE_DEFAULT_APP_DIRS
MENU_LAYOUT_NODE_DIRECTORY_DIR
MENU_LAYOUT_NODE_DEFAULT_DIRECTORY_DIRS
MENU_LAYOUT_NODE_DEFAULT_MERGE_DIRS
MENU_LAYOUT_NODE_NAME
MENU_LAYOUT_NODE_DIRECTORY
MENU_LAYOUT_NODE_ONLY_UNALLOCATED
MENU_LAYOUT_NODE_NOT_ONLY_UNALLOCATED
MENU_LAYOUT_NODE_INCLUDE
MENU_LAYOUT_NODE_EXCLUDE
MENU_LAYOUT_NODE_FILENAME
MENU_LAYOUT_NODE_CATEGORY
MENU_LAYOUT_NODE_ALL
MENU_LAYOUT_NODE_AND
MENU_LAYOUT_NODE_OR
MENU_LAYOUT_NODE_NOT
MENU_LAYOUT_NODE_MERGE_FILE
MENU_LAYOUT_NODE_MERGE_DIR
MENU_LAYOUT_NODE_LEGACY_DIR
MENU_LAYOUT_NODE_KDE_LEGACY_DIRS
MENU_LAYOUT_NODE_MOVE
MENU_LAYOUT_NODE_OLD
MENU_LAYOUT_NODE_NEW
MENU_LAYOUT_NODE_DELETED
MENU_LAYOUT_NODE_NOT_DELETED
MENU_LAYOUT_NODE_LAYOUT
MENU_LAYOUT_NODE_DEFAULT_LAYOUT
MENU_LAYOUT_NODE_MENUNAME
MENU_LAYOUT_NODE_SEPARATOR
MENU_LAYOUT_NODE_MERGE
Definition at line 34 of file menu-layout.h.
MenuLayoutValuesMask
enum MenuLayoutValuesMask
Enumerator
MENU_LAYOUT_VALUES_NONE
MENU_LAYOUT_VALUES_SHOW_EMPTY
MENU_LAYOUT_VALUES_INLINE_MENUS
MENU_LAYOUT_VALUES_INLINE_LIMIT
MENU_LAYOUT_VALUES_INLINE_HEADER
MENU_LAYOUT_VALUES_INLINE_ALIAS
Definition at line 83 of file menu-layout.h.
MenuMergeFileType
enum MenuMergeFileType
Enumerator
MENU_MERGE_FILE_TYPE_PATH
MENU_MERGE_FILE_TYPE_PARENT
Definition at line 71 of file menu-layout.h.
Function Documentation
menu_layout_load()
MenuLayoutNode * menu_layout_load (const char * filename, const char * non_prefixed_basename, GError ** error)
Definition at line 2296 of file menu-layout.c.
References error, FALSE, MENU_LAYOUT_NODE_MENU, and NULL.
menu_layout_node_append_child()
void menu_layout_node_append_child (MenuLayoutNode * parent, MenuLayoutNode * new_child)
Definition at line 469 of file menu-layout.c.
References menu_layout_node_insert_after(), menu_layout_node_ref(), and RETURN_IF_HAS_ENTRY_DIRS.
menu_layout_node_default_layout_get_values()
void menu_layout_node_default_layout_get_values (MenuLayoutNode * node, MenuLayoutValues * values)
Definition at line 944 of file menu-layout.c.
References MENU_LAYOUT_NODE_DEFAULT_LAYOUT, and NULL.
menu_layout_node_get_children()
MenuLayoutNode * menu_layout_node_get_children (MenuLayoutNode * node)
Definition at line 330 of file menu-layout.c.
menu_layout_node_get_content()
const char * menu_layout_node_get_content (MenuLayoutNode * node)
Definition at line 583 of file menu-layout.c.
Referenced by menu_layout_node_menu_get_name().
menu_layout_node_get_content_as_path()
char * menu_layout_node_get_content_as_path (MenuLayoutNode * node)
Definition at line 350 of file menu-layout.c.
References menu_layout_node_get_root(), and NULL.
menu_layout_node_get_next()
MenuLayoutNode * menu_layout_node_get_next (MenuLayoutNode * node)
Definition at line 318 of file menu-layout.c.
menu_layout_node_get_parent()
MenuLayoutNode * menu_layout_node_get_parent (MenuLayoutNode * node)
Definition at line 324 of file menu-layout.c.
menu_layout_node_get_root()
MenuLayoutNode * menu_layout_node_get_root (MenuLayoutNode * node)
Definition at line 336 of file menu-layout.c.
References MENU_LAYOUT_NODE_ROOT, and NULL.
Referenced by menu_layout_node_get_content_as_path().
menu_layout_node_get_type()
MenuLayoutNodeType menu_layout_node_get_type (MenuLayoutNode * node)
Definition at line 577 of file menu-layout.c.
menu_layout_node_insert_after()
void menu_layout_node_insert_after (MenuLayoutNode * node, MenuLayoutNode * new_sibling)
Definition at line 431 of file menu-layout.c.
References menu_layout_node_ref(), NULL, RETURN_IF_HAS_ENTRY_DIRS, and RETURN_IF_NO_PARENT.
Referenced by menu_layout_node_append_child().
menu_layout_node_insert_before()
void menu_layout_node_insert_before (MenuLayoutNode * node, MenuLayoutNode * new_sibling)
Definition at line 407 of file menu-layout.c.
References menu_layout_node_ref(), NULL, RETURN_IF_HAS_ENTRY_DIRS, and RETURN_IF_NO_PARENT.
Referenced by menu_layout_node_prepend_child().
menu_layout_node_legacy_dir_get_prefix()
const char * menu_layout_node_legacy_dir_get_prefix (MenuLayoutNode * node)
Definition at line 855 of file menu-layout.c.
References MENU_LAYOUT_NODE_LEGACY_DIR, and NULL.
menu_layout_node_legacy_dir_set_prefix()
void menu_layout_node_legacy_dir_set_prefix (MenuLayoutNode * node, const char * prefix)
Definition at line 867 of file menu-layout.c.
References MENU_LAYOUT_NODE_LEGACY_DIR, and prefix.
menu_layout_node_menu_get_app_dirs()
EntryDirectoryList * menu_layout_node_menu_get_app_dirs (MenuLayoutNode * node)
Definition at line 793 of file menu-layout.c.
References MENU_LAYOUT_NODE_MENU, and NULL.
menu_layout_node_menu_get_directory_dirs()
EntryDirectoryList * menu_layout_node_menu_get_directory_dirs (MenuLayoutNode * node)
Definition at line 807 of file menu-layout.c.
References MENU_LAYOUT_NODE_MENU, and NULL.
menu_layout_node_menu_get_name()
const char * menu_layout_node_menu_get_name (MenuLayoutNode * node)
Definition at line 624 of file menu-layout.c.
References menu_layout_node_get_content(), MENU_LAYOUT_NODE_MENU, MENU_LAYOUT_NODE_NAME, menu_layout_node_ref(), and NULL.
menu_layout_node_menuname_get_values()
void menu_layout_node_menuname_get_values (MenuLayoutNode * node, MenuLayoutValues * values)
Definition at line 958 of file menu-layout.c.
References MENU_LAYOUT_NODE_MENUNAME, and NULL.
menu_layout_node_merge_file_get_type()
MenuMergeFileType menu_layout_node_merge_file_get_type (MenuLayoutNode * node)
Definition at line 881 of file menu-layout.c.
References FALSE, and MENU_LAYOUT_NODE_MERGE_FILE.
menu_layout_node_merge_file_set_type()
void menu_layout_node_merge_file_set_type (MenuLayoutNode * node, MenuMergeFileType type)
Definition at line 893 of file menu-layout.c.
References MENU_LAYOUT_NODE_MERGE_FILE.
menu_layout_node_merge_get_type()
MenuLayoutMergeType menu_layout_node_merge_get_type (MenuLayoutNode * node)
Definition at line 906 of file menu-layout.c.
References MENU_LAYOUT_NODE_MERGE.
menu_layout_node_move_get_new()
const char * menu_layout_node_move_get_new (MenuLayoutNode * node)
Definition at line 838 of file menu-layout.c.
References MENU_LAYOUT_NODE_NEW, and NULL.
menu_layout_node_move_get_old()
const char * menu_layout_node_move_get_old (MenuLayoutNode * node)
Definition at line 821 of file menu-layout.c.
References MENU_LAYOUT_NODE_OLD, and NULL.
menu_layout_node_new()
MenuLayoutNode * menu_layout_node_new (MenuLayoutNodeType type)
Definition at line 267 of file menu-layout.c.
References MENU_LAYOUT_NODE_DEFAULT_LAYOUT, MENU_LAYOUT_NODE_LEGACY_DIR, MENU_LAYOUT_NODE_MENU, MENU_LAYOUT_NODE_MENUNAME, MENU_LAYOUT_NODE_MERGE, MENU_LAYOUT_NODE_MERGE_FILE, and MENU_LAYOUT_NODE_ROOT.
menu_layout_node_prepend_child()
void menu_layout_node_prepend_child (MenuLayoutNode * parent, MenuLayoutNode * new_child)
Definition at line 452 of file menu-layout.c.
References menu_layout_node_insert_before(), menu_layout_node_ref(), and RETURN_IF_HAS_ENTRY_DIRS.
menu_layout_node_ref()
MenuLayoutNode * menu_layout_node_ref (MenuLayoutNode * node)
Definition at line 196 of file menu-layout.c.
References NULL.
Referenced by menu_layout_node_append_child(), menu_layout_node_insert_after(), menu_layout_node_insert_before(), menu_layout_node_menu_get_name(), and menu_layout_node_prepend_child().
menu_layout_node_root_add_entries_monitor()
void menu_layout_node_root_add_entries_monitor (MenuLayoutNode * node, MenuLayoutNodeEntriesChangedFunc callback, gpointer user_data)
Definition at line 1069 of file menu-layout.c.
References MENU_LAYOUT_NODE_ROOT, NULL, and user_data.
menu_layout_node_root_get_basedir()
const char * menu_layout_node_root_get_basedir (MenuLayoutNode * node)
Definition at line 612 of file menu-layout.c.
References MENU_LAYOUT_NODE_ROOT, and NULL.
menu_layout_node_root_get_name()
const char * menu_layout_node_root_get_name (MenuLayoutNode * node)
Definition at line 600 of file menu-layout.c.
References MENU_LAYOUT_NODE_ROOT, and NULL.
menu_layout_node_root_remove_entries_monitor()
void menu_layout_node_root_remove_entries_monitor (MenuLayoutNode * node, MenuLayoutNodeEntriesChangedFunc callback, gpointer user_data)
Definition at line 1104 of file menu-layout.c.
References MENU_LAYOUT_NODE_ROOT, NULL, and user_data.
menu_layout_node_set_content()
void menu_layout_node_set_content (MenuLayoutNode * node, const char * content)
Definition at line 589 of file menu-layout.c.
menu_layout_node_steal()
void menu_layout_node_steal (MenuLayoutNode * node)
Definition at line 526 of file menu-layout.c.
References FALSE, MENU_LAYOUT_NODE_APP_DIR, MENU_LAYOUT_NODE_DIRECTORY_DIR, MENU_LAYOUT_NODE_NAME, menu_layout_node_unref(), NULL, and TRUE.
Referenced by menu_layout_node_unlink().
menu_layout_node_unlink()
void menu_layout_node_unlink (MenuLayoutNode * node)
Definition at line 486 of file menu-layout.c.
References menu_layout_node_steal(), menu_layout_node_unref(), and NULL.
menu_layout_node_unref()
void menu_layout_node_unref (MenuLayoutNode * node)
Definition at line 206 of file menu-layout.c.
References MENU_LAYOUT_NODE_LEGACY_DIR, MENU_LAYOUT_NODE_MENU, MENU_LAYOUT_NODE_ROOT, menu_layout_node_unref(), and NULL.
Referenced by menu_layout_node_steal(), menu_layout_node_unlink(), and menu_layout_node_unref().