MATE Desktop Environment: mp-binary.c File Reference
mp-binary.c File Reference
#include <stdio.h>
#include "mp.h"
#include "mp-serializer.h"
Macros
#define MAX_DIGITS 1000
Functions
bool mp_is_overflow (const MPNumber *x, int wordlen)
void mp_and (const MPNumber *x, const MPNumber *y, MPNumber *z)
void mp_or (const MPNumber *x, const MPNumber *y, MPNumber *z)
void mp_xor (const MPNumber *x, const MPNumber *y, MPNumber *z)
void mp_not (const MPNumber *x, int wordlen, MPNumber *z)
void mp_shift (const MPNumber *x, int count, MPNumber *z)
void mp_ones_complement (const MPNumber *x, int wordlen, MPNumber *z)
void mp_twos_complement (const MPNumber *x, int wordlen, MPNumber *z)
Macro Definition Documentation
MAX_DIGITS
#define MAX_DIGITS 1000
Definition at line 18 of file mp-binary.c.
Function Documentation
mp_and()
void mp_and (const MPNumber * x, const MPNumber * y, MPNumber * z)
Definition at line 109 of file mp-binary.c.
References _, mp_is_positive_integer(), and mperr().
Referenced by mp_set_from_float(), and pf_do_and().
mp_is_overflow()
bool mp_is_overflow (const MPNumber * x, int wordlen)
Definition at line 95 of file mp-binary.c.
References mp_clear(), mp_is_greater_than(), mp_new(), mp_set_from_integer(), and mp_xpowy_integer().
Referenced by mp_set_from_float(), and pf_do_not().
mp_not()
void mp_not (const MPNumber * x, int wordlen, MPNumber * z)
Definition at line 145 of file mp-binary.c.
References _, mp_clear(), mp_is_positive_integer(), mp_new(), mp_set_from_integer(), and mperr().
Referenced by mp_ones_complement(), mp_xnor(), and pf_do_not().
mp_ones_complement()
void mp_ones_complement (const MPNumber * x, int wordlen, MPNumber * z)
Definition at line 187 of file mp-binary.c.
References mp_clear(), mp_new(), mp_not(), and mp_set_from_integer().
Referenced by mp_twos_complement(), and mp_xnor().
mp_or()
void mp_or (const MPNumber * x, const MPNumber * y, MPNumber * z)
Definition at line 121 of file mp-binary.c.
References _, mp_is_positive_integer(), and mperr().
Referenced by mp_set_from_float(), and pf_do_or().
mp_shift()
void mp_shift (const MPNumber * x, int count, MPNumber * z)
Definition at line 162 of file mp-binary.c.
References _, mp_clear(), mp_divide(), mp_floor(), mp_is_integer(), mp_multiply(), mp_multiply_integer(), mp_new(), mp_set_from_integer(), and mperr().
Referenced by character_code_dialog_response_cb(), math_equation_shift(), and mp_xnor().
mp_twos_complement()
void mp_twos_complement (const MPNumber * x, int wordlen, MPNumber * z)
Definition at line 197 of file mp-binary.c.
References mp_add_integer(), and mp_ones_complement().
Referenced by mp_xnor().
mp_xor()
void mp_xor (const MPNumber * x, const MPNumber * y, MPNumber * z)
Definition at line 133 of file mp-binary.c.
References _, mp_is_positive_integer(), and mperr().
Referenced by mp_set_from_float(), and pf_do_xor().