MATE Desktop Environment: mp-convert.c File Reference
mp-convert.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <math.h>
#include <langinfo.h>
#include "mp.h"
Functions
void mp_set_from_mp (const MPNumber *x, MPNumber *z)
void mp_set_from_double (double dx, MPNumber *z)
void mp_set_from_integer (long x, MPNumber *z)
void mp_set_from_unsigned_integer (ulong x, MPNumber *z)
void mp_set_from_fraction (long numerator, long denominator, MPNumber *z)
void mp_set_from_polar (const MPNumber *r, MPAngleUnit unit, const MPNumber *theta, MPNumber *z)
void mp_set_from_complex (const MPNumber *x, const MPNumber *y, MPNumber *z)
void mp_set_from_random (MPNumber *z)
long mp_to_integer (const MPNumber *x)
ulong mp_to_unsigned_integer (const MPNumber *x)
float mp_to_float (const MPNumber *x)
double mp_to_double (const MPNumber *x)
bool mp_set_from_string (const char *str, int default_base, MPNumber *z)
Function Documentation
mp_set_from_complex()
void mp_set_from_complex (const MPNumber * x, const MPNumber * y, MPNumber * z)
Definition at line 75 of file mp-convert.c.
References MPNumber::num.
Referenced by mp_set_from_float(), and mp_set_from_polar().
mp_set_from_double()
void mp_set_from_double (double dx, MPNumber * z)
Definition at line 28 of file mp-convert.c.
References MPNumber::num.
Referenced by mp_set_from_float(), and mp_set_from_random().
mp_set_from_fraction()
void mp_set_from_fraction (long numerator, long denominator, MPNumber * z)
Definition at line 46 of file mp-convert.c.
References mp_divide_integer(), and mp_set_from_integer().
Referenced by mp_set_from_float(), and mp_set_from_string().
mp_set_from_integer()
void mp_set_from_integer (long x, MPNumber * z)
Definition at line 34 of file mp-convert.c.
References MPNumber::num.
Referenced by character_code_dialog_response_cb(), mp_acos(), mp_acosh(), mp_arg(), mp_asin(), mp_atan(), mp_atanh(), mp_divide(), mp_divide_integer(), mp_erf(), mp_factorial(), mp_factorize(), mp_is_overflow(), mp_ln(), mp_logarithm(), mp_modular_exponentiation(), mp_modulus_divide(), mp_not(), mp_ones_complement(), mp_root(), mp_set_from_float(), mp_set_from_fraction(), mp_set_from_string(), mp_shift(), mp_tan(), mp_xpowy(), mp_xpowy_integer(), mp_zeta(), pf_convert_1(), pf_do_x_pow_y_int(), pf_get_variable(), and pf_get_variable_with_power().
mp_set_from_mp()
void mp_set_from_mp (const MPNumber * x, MPNumber * z)
Definition at line 22 of file mp-convert.c.
References MPNumber::num.
Referenced by convert_from_radians(), convert_to_radians(), currency_set_value(), math_equation_get_number(), math_equation_set_number(), math_history_entry_insert_entry(), math_variables_set(), mp_cos(), mp_equation_parse(), mp_factorize(), mp_factorize_unit64(), mp_modular_exponentiation(), mp_root(), mp_sin(), mp_tan(), mperr(), p_parse(), pf_get_variable(), and pf_get_variable_with_power().
mp_set_from_polar()
void mp_set_from_polar (const MPNumber * r, MPAngleUnit unit, const MPNumber * theta, MPNumber * z)
Definition at line 59 of file mp-convert.c.
References mp_clear(), mp_cos(), mp_multiply(), mp_new(), mp_set_from_complex(), and mp_sin().
Referenced by mp_set_from_float().
mp_set_from_random()
void mp_set_from_random (MPNumber * z)
Definition at line 81 of file mp-convert.c.
References mp_set_from_double().
Referenced by mp_set_from_float().
mp_set_from_string()
bool mp_set_from_string (const char * str, int default_base, MPNumber * z)
Definition at line 221 of file mp-convert.c.
References FALSE, mp_add(), mp_add_integer(), mp_clear(), mp_divide(), mp_invert_sign(), mp_multiply(), mp_multiply_integer(), mp_new(), mp_set_from_fraction(), mp_set_from_integer(), mp_xpowy_integer(), NULL, and TRUE.
Referenced by finc_response_cb(), mp_serializer_from_string(), mp_set_from_float(), pf_constant(), and pf_convert_number().
mp_set_from_unsigned_integer()
void mp_set_from_unsigned_integer (ulong x, MPNumber * z)
Definition at line 40 of file mp-convert.c.
References MPNumber::num.
Referenced by math_equation_toggle_bit(), mp_factorize(), mp_factorize_unit64(), and mp_set_from_float().
mp_to_double()
double mp_to_double (const MPNumber * x)
Definition at line 105 of file mp-convert.c.
References MPNumber::num.
Referenced by mp_set_from_float().
mp_to_float()
float mp_to_float (const MPNumber * x)
Definition at line 99 of file mp-convert.c.
References MPNumber::num.
Referenced by mp_set_from_float().
mp_to_integer()
long mp_to_integer (const MPNumber * x)
Definition at line 87 of file mp-convert.c.
References MPNumber::num.
Referenced by mp_set_from_float(), mp_xpowy(), and pf_do_x_pow_y_int().
mp_to_unsigned_integer()
ulong mp_to_unsigned_integer (const MPNumber * x)
Definition at line 93 of file mp-convert.c.
References MPNumber::num.
Referenced by math_equation_toggle_bit(), mp_factorial(), mp_factorize(), and mp_set_from_float().