MATE Desktop Environment: mp-trigonometric.c File Reference
mp-trigonometric.c File Reference
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <libintl.h>
#include "mp.h"
Functions
void convert_to_radians (const MPNumber *x, MPAngleUnit unit, MPNumber *z)
void convert_from_radians (const MPNumber *x, MPAngleUnit unit, MPNumber *z)
void mp_get_pi (MPNumber *z)
void mp_sin (const MPNumber *x, MPAngleUnit unit, MPNumber *z)
void mp_cos (const MPNumber *x, MPAngleUnit unit, MPNumber *z)
void mp_tan (const MPNumber *x, MPAngleUnit unit, MPNumber *z)
void mp_asin (const MPNumber *x, MPAngleUnit unit, MPNumber *z)
void mp_acos (const MPNumber *x, MPAngleUnit unit, MPNumber *z)
void mp_atan (const MPNumber *x, MPAngleUnit unit, MPNumber *z)
void mp_sinh (const MPNumber *x, MPNumber *z)
void mp_cosh (const MPNumber *x, MPNumber *z)
void mp_tanh (const MPNumber *x, MPNumber *z)
void mp_asinh (const MPNumber *x, MPNumber *z)
void mp_acosh (const MPNumber *x, MPNumber *z)
void mp_atanh (const MPNumber *x, MPNumber *z)
Function Documentation
convert_from_radians()
void convert_from_radians (const MPNumber * x, MPAngleUnit unit, MPNumber * z)
Definition at line 48 of file mp-trigonometric.c.
References MP_DEGREES, MP_GRADIANS, MP_RADIANS, mp_set_from_mp(), MPNumber::num, and PRECISION.
Referenced by mp_acos(), mp_arg(), mp_asin(), mp_atan(), and mp_xnor().
convert_to_radians()
void convert_to_radians (const MPNumber * x, MPAngleUnit unit, MPNumber * z)
Definition at line 21 of file mp-trigonometric.c.
References MP_DEGREES, MP_GRADIANS, MP_RADIANS, mp_set_from_mp(), MPNumber::num, and PRECISION.
Referenced by mp_cos(), mp_sin(), mp_tan(), and mp_xnor().
mp_acos()
void mp_acos (const MPNumber * x, MPAngleUnit unit, MPNumber * z)
Definition at line 159 of file mp-trigonometric.c.
References _, convert_from_radians(), mp_clear(), mp_compare(), mp_is_complex(), mp_new(), mp_set_from_integer(), mperr(), and MPNumber::num.
Referenced by mp_set_from_float().
mp_acosh()
void mp_acosh (const MPNumber * x, MPNumber * z)
Definition at line 232 of file mp-trigonometric.c.
References _, mp_clear(), mp_is_less_than(), mp_new(), mp_set_from_integer(), mperr(), and MPNumber::num.
Referenced by mp_set_from_float().
mp_asin()
void mp_asin (const MPNumber * x, MPAngleUnit unit, MPNumber * z)
Definition at line 135 of file mp-trigonometric.c.
References _, convert_from_radians(), mp_clear(), mp_compare(), mp_is_complex(), mp_new(), mp_set_from_integer(), mperr(), and MPNumber::num.
Referenced by mp_set_from_float().
mp_asinh()
void mp_asinh (const MPNumber * x, MPNumber * z)
Definition at line 226 of file mp-trigonometric.c.
References MPNumber::num.
Referenced by mp_set_from_float().
mp_atan()
void mp_atan (const MPNumber * x, MPAngleUnit unit, MPNumber * z)
Definition at line 183 of file mp-trigonometric.c.
References _, convert_from_radians(), mp_clear(), mp_is_complex(), mp_is_equal(), mp_new(), mp_set_from_integer(), mperr(), and MPNumber::num.
Referenced by mp_set_from_float().
mp_atanh()
void mp_atanh (const MPNumber * x, MPNumber * z)
Definition at line 252 of file mp-trigonometric.c.
References _, mp_clear(), mp_compare(), mp_new(), mp_set_from_integer(), mperr(), and MPNumber::num.
Referenced by mp_set_from_float().
mp_cos()
void mp_cos (const MPNumber * x, MPAngleUnit unit, MPNumber * z)
Definition at line 92 of file mp-trigonometric.c.
References convert_to_radians(), mp_is_complex(), mp_set_from_mp(), and MPNumber::num.
Referenced by mp_set_from_float(), and mp_set_from_polar().
mp_cosh()
void mp_cosh (const MPNumber * x, MPNumber * z)
Definition at line 214 of file mp-trigonometric.c.
References MPNumber::num.
Referenced by mp_set_from_float().
mp_get_pi()
void mp_get_pi (MPNumber * z)
Definition at line 75 of file mp-trigonometric.c.
References MPNumber::num.
Referenced by mp_tan(), and mperr().
mp_sin()
void mp_sin (const MPNumber * x, MPAngleUnit unit, MPNumber * z)
Definition at line 82 of file mp-trigonometric.c.
References convert_to_radians(), mp_is_complex(), mp_set_from_mp(), and MPNumber::num.
Referenced by mp_set_from_float(), and mp_set_from_polar().
mp_sinh()
void mp_sinh (const MPNumber * x, MPNumber * z)
Definition at line 208 of file mp-trigonometric.c.
References MPNumber::num.
Referenced by mp_set_from_float().
mp_tan()
void mp_tan (const MPNumber * x, MPAngleUnit unit, MPNumber * z)
Definition at line 102 of file mp-trigonometric.c.
References _, convert_to_radians(), mp_clear(), mp_divide(), mp_divide_integer(), mp_get_pi(), mp_is_complex(), mp_is_integer(), mp_new(), mp_set_from_integer(), mp_set_from_mp(), mp_subtract(), mperr(), and MPNumber::num.
Referenced by mp_set_from_float().
mp_tanh()
void mp_tanh (const MPNumber * x, MPNumber * z)
Definition at line 220 of file mp-trigonometric.c.
References MPNumber::num.
Referenced by mp_set_from_float().