MATE Desktop Environment: mp.h File Reference
mp.h File Reference
#include <stdbool.h>
#include <stdint.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <mpfr.h>
#include <mpc.h>
Classes
struct MPNumber
Macros
#define __attribute__(x)
#define PRECISION 1000
Enumerations
enum MPAngleUnit { MP_RADIANS , MP_DEGREES , MP_GRADIANS }
Functions
const char * mp_get_error (void)
void mp_clear_error (void)
void mperr (const char *format,...) __attribute__((format(printf
void MPNumber mp_new (void)
MPNumber mp_new_from_unsigned_integer (ulong x)
MPNumber * mp_new_ptr (void)
void mp_clear (MPNumber *z)
void mp_free (MPNumber *z)
int mp_compare (const MPNumber *x, const MPNumber *y)
bool mp_is_zero (const MPNumber *x)
bool mp_is_negative (const MPNumber *x)
bool mp_is_integer (const MPNumber *x)
bool mp_is_positive_integer (const MPNumber *x)
bool mp_is_natural (const MPNumber *x)
bool mp_is_complex (const MPNumber *x)
bool mp_is_equal (const MPNumber *x, const MPNumber *y)
bool mp_is_greater_equal (const MPNumber *x, const MPNumber *y)
bool mp_is_greater_than (const MPNumber *x, const MPNumber *y)
bool mp_is_less_equal (const MPNumber *x, const MPNumber *y)
bool mp_is_less_than (const MPNumber *x, const MPNumber *y)
void mp_abs (const MPNumber *x, MPNumber *z)
void mp_arg (const MPNumber *x, MPAngleUnit unit, MPNumber *z)
void mp_conjugate (const MPNumber *x, MPNumber *z)
void mp_real_component (const MPNumber *x, MPNumber *z)
void mp_imaginary_component (const MPNumber *x, MPNumber *z)
void mp_invert_sign (const MPNumber *x, MPNumber *z)
void mp_add (const MPNumber *x, const MPNumber *y, MPNumber *z)
void mp_add_integer (const MPNumber *x, long y, MPNumber *z)
void mp_subtract (const MPNumber *x, const MPNumber *y, MPNumber *z)
void mp_multiply (const MPNumber *x, const MPNumber *y, MPNumber *z)
void mp_multiply_integer (const MPNumber *x, long y, MPNumber *z)
void mp_divide (const MPNumber *x, const MPNumber *y, MPNumber *z)
void mp_divide_integer (const MPNumber *x, long y, MPNumber *z)
void mp_reciprocal (const MPNumber *, MPNumber *)
void mp_sgn (const MPNumber *x, MPNumber *z)
void mp_integer_component (const MPNumber *x, MPNumber *z)
void mp_fractional_component (const MPNumber *x, MPNumber *z)
void mp_fractional_part (const MPNumber *x, MPNumber *z)
void mp_floor (const MPNumber *x, MPNumber *z)
void mp_ceiling (const MPNumber *x, MPNumber *z)
void mp_round (const MPNumber *x, MPNumber *z)
void mp_ln (const MPNumber *x, MPNumber *z)
void mp_logarithm (long n, const MPNumber *x, MPNumber *z)
void mp_get_pi (MPNumber *z)
void mp_get_eulers (MPNumber *z)
void mp_get_i (MPNumber *z)
void mp_root (const MPNumber *x, long n, MPNumber *z)
void mp_sqrt (const MPNumber *x, MPNumber *z)
void mp_factorial (const MPNumber *x, MPNumber *z)
void mp_modulus_divide (const MPNumber *x, const MPNumber *y, MPNumber *z)
void mp_modular_exponentiation (const MPNumber *x, const MPNumber *y, const MPNumber *p, MPNumber *z)
void mp_xpowy (const MPNumber *x, const MPNumber *y, MPNumber *z)
void mp_xpowy_integer (const MPNumber *x, long y, MPNumber *z)
void mp_epowy (const MPNumber *x, MPNumber *z)
GList * mp_factorize (const MPNumber *x)
GList * mp_factorize_unit64 (uint64_t n)
void mp_set_from_mp (const MPNumber *x, MPNumber *z)
void mp_set_from_float (float x, MPNumber *z)
void mp_set_from_double (double x, MPNumber *z)
void mp_set_from_integer (long x, MPNumber *z)
void mp_set_from_unsigned_integer (ulong x, MPNumber *z)
void mp_set_from_fraction (long numerator, long denominator, MPNumber *z)
void mp_set_from_polar (const MPNumber *r, MPAngleUnit unit, const MPNumber *theta, MPNumber *z)
void mp_set_from_complex (const MPNumber *x, const MPNumber *y, MPNumber *z)
void mp_set_from_random (MPNumber *z)
bool mp_set_from_string (const char *text, int default_base, MPNumber *z)
float mp_to_float (const MPNumber *x)
double mp_to_double (const MPNumber *x)
long mp_to_integer (const MPNumber *x)
ulong mp_to_unsigned_integer (const MPNumber *x)
void mp_sin (const MPNumber *x, MPAngleUnit unit, MPNumber *z)
void mp_cos (const MPNumber *x, MPAngleUnit unit, MPNumber *z)
void mp_tan (const MPNumber *x, MPAngleUnit unit, MPNumber *z)
void mp_asin (const MPNumber *x, MPAngleUnit unit, MPNumber *z)
void mp_acos (const MPNumber *x, MPAngleUnit unit, MPNumber *z)
void mp_atan (const MPNumber *x, MPAngleUnit unit, MPNumber *z)
void mp_sinh (const MPNumber *x, MPNumber *z)
void mp_cosh (const MPNumber *x, MPNumber *z)
void mp_tanh (const MPNumber *x, MPNumber *z)
void mp_asinh (const MPNumber *x, MPNumber *z)
void mp_acosh (const MPNumber *x, MPNumber *z)
void mp_atanh (const MPNumber *x, MPNumber *z)
void mp_erf (const MPNumber *x, MPNumber *z)
void mp_zeta (const MPNumber *x, MPNumber *z)
bool mp_is_overflow (const MPNumber *x, int wordlen)
void mp_and (const MPNumber *x, const MPNumber *y, MPNumber *z)
void mp_or (const MPNumber *x, const MPNumber *y, MPNumber *z)
void mp_xor (const MPNumber *x, const MPNumber *y, MPNumber *z)
void mp_xnor (const MPNumber *x, const MPNumber *y, int wordlen, MPNumber *z)
void mp_not (const MPNumber *x, int wordlen, MPNumber *z)
void mp_shift (const MPNumber *x, int count, MPNumber *z)
void mp_ones_complement (const MPNumber *x, int wordlen, MPNumber *z)
void mp_twos_complement (const MPNumber *x, int wordlen, MPNumber *z)
void convert_to_radians (const MPNumber *x, MPAngleUnit unit, MPNumber *z)
void convert_from_radians (const MPNumber *x, MPAngleUnit unit, MPNumber *z)
Macro Definition Documentation
__attribute__
#define __attribute__ (x)
Value:
/*NOTHING*/
Definition at line 42 of file mp.h.
Referenced by mperr().
PRECISION
#define PRECISION 1000
Definition at line 46 of file mp.h.
Referenced by convert_from_radians(), convert_to_radians(), mp_factorial(), mp_factorize(), mp_factorize_unit64(), mp_new(), mp_new_from_unsigned_integer(), mp_new_ptr(), mp_reciprocal(), and mp_root().
Enumeration Type Documentation
MPAngleUnit
enum MPAngleUnit
Enumerator
MP_RADIANS
MP_DEGREES
MP_GRADIANS
Definition at line 53 of file mp.h.
Function Documentation
convert_from_radians()
void convert_from_radians (const MPNumber * x, MPAngleUnit unit, MPNumber * z)
Definition at line 48 of file mp-trigonometric.c.
References MP_DEGREES, MP_GRADIANS, MP_RADIANS, mp_set_from_mp(), MPNumber::num, and PRECISION.
Referenced by mp_acos(), mp_arg(), mp_asin(), mp_atan(), and mp_xnor().
convert_to_radians()
void convert_to_radians (const MPNumber * x, MPAngleUnit unit, MPNumber * z)
Definition at line 21 of file mp-trigonometric.c.
References MP_DEGREES, MP_GRADIANS, MP_RADIANS, mp_set_from_mp(), MPNumber::num, and PRECISION.
Referenced by mp_cos(), mp_sin(), mp_tan(), and mp_xnor().
mp_abs()
void mp_abs (const MPNumber * x, MPNumber * z)
Definition at line 111 of file mp.c.
References MPNumber::num.
Referenced by mp_factorize(), mp_modular_exponentiation(), mperr(), and pf_do_abs().
mp_acos()
void mp_acos (const MPNumber * x, MPAngleUnit unit, MPNumber * z)
Definition at line 159 of file mp-trigonometric.c.
References _, convert_from_radians(), mp_clear(), mp_compare(), mp_is_complex(), mp_new(), mp_set_from_integer(), mperr(), and MPNumber::num.
Referenced by mp_set_from_float().
mp_acosh()
void mp_acosh (const MPNumber * x, MPNumber * z)
Definition at line 232 of file mp-trigonometric.c.
References _, mp_clear(), mp_is_less_than(), mp_new(), mp_set_from_integer(), mperr(), and MPNumber::num.
Referenced by mp_set_from_float().
mp_add()
void mp_add (const MPNumber * x, const MPNumber * y, MPNumber * z)
Definition at line 157 of file mp.c.
References MPNumber::num.
Referenced by mp_factorial(), mp_modulus_divide(), mp_set_from_string(), mperr(), and pf_do_add().
mp_add_integer()
void mp_add_integer (const MPNumber * x, long y, MPNumber * z)
Definition at line 163 of file mp.c.
References MPNumber::num.
Referenced by character_code_dialog_response_cb(), mp_factorize(), mp_set_from_string(), mp_twos_complement(), mperr(), pf_do_add_percent(), and pf_do_subtract_percent().
mp_and()
void mp_and (const MPNumber * x, const MPNumber * y, MPNumber * z)
Definition at line 109 of file mp-binary.c.
References _, mp_is_positive_integer(), and mperr().
Referenced by mp_set_from_float(), and pf_do_and().
mp_arg()
void mp_arg (const MPNumber * x, MPAngleUnit unit, MPNumber * z)
Definition at line 118 of file mp.c.
References _, convert_from_radians(), mp_is_complex(), mp_is_negative(), mp_is_zero(), mp_set_from_integer(), mperr(), and MPNumber::num.
Referenced by mperr().
mp_asin()
void mp_asin (const MPNumber * x, MPAngleUnit unit, MPNumber * z)
Definition at line 135 of file mp-trigonometric.c.
References _, convert_from_radians(), mp_clear(), mp_compare(), mp_is_complex(), mp_new(), mp_set_from_integer(), mperr(), and MPNumber::num.
Referenced by mp_set_from_float().
mp_asinh()
void mp_asinh (const MPNumber * x, MPNumber * z)
Definition at line 226 of file mp-trigonometric.c.
References MPNumber::num.
Referenced by mp_set_from_float().
mp_atan()
void mp_atan (const MPNumber * x, MPAngleUnit unit, MPNumber * z)
Definition at line 183 of file mp-trigonometric.c.
References _, convert_from_radians(), mp_clear(), mp_is_complex(), mp_is_equal(), mp_new(), mp_set_from_integer(), mperr(), and MPNumber::num.
Referenced by mp_set_from_float().
mp_atanh()
void mp_atanh (const MPNumber * x, MPNumber * z)
Definition at line 252 of file mp-trigonometric.c.
References _, mp_clear(), mp_compare(), mp_new(), mp_set_from_integer(), mperr(), and MPNumber::num.
Referenced by mp_set_from_float().
mp_ceiling()
void mp_ceiling (const MPNumber * x, MPNumber * z)
Definition at line 211 of file mp.c.
References MPNumber::num.
Referenced by mperr(), and pf_do_ceiling().
mp_clear()
void mp_clear (MPNumber * z)
Definition at line 79 of file mp.c.
References NULL, and MPNumber::num.
Referenced by character_code_dialog_response_cb(), do_finc_expression(), finc_response_cb(), math_equation_factorize(), math_equation_shift(), math_equation_store(), math_equation_toggle_bit(), mp_acos(), mp_acosh(), mp_asin(), mp_atan(), mp_atanh(), mp_divide_integer(), mp_factorial(), mp_factorize(), mp_factorize_unit64(), mp_fractional_part(), mp_is_overflow(), mp_logarithm(), mp_modular_exponentiation(), mp_modulus_divide(), mp_not(), mp_ones_complement(), mp_set_from_polar(), mp_set_from_string(), mp_shift(), mp_tan(), mp_xpowy(), mp_zeta(), mperr(), pf_convert_1(), pf_convert_number(), and unit_category_convert().
mp_clear_error()
void mp_clear_error (void)
Definition at line 46 of file mp.c.
References mp_error, and NULL.
Referenced by mp_equation_parse().
mp_compare()
int mp_compare (const MPNumber * x, const MPNumber * y)
Definition at line 225 of file mp.c.
References MPNumber::num.
Referenced by mp_acos(), mp_asin(), mp_atanh(), mp_is_greater_equal(), mp_is_greater_than(), mp_is_less_equal(), mp_is_less_than(), mp_modulus_divide(), mp_zeta(), and mperr().
mp_conjugate()
void mp_conjugate (const MPNumber * x, MPNumber * z)
Definition at line 139 of file mp.c.
References MPNumber::num.
Referenced by mperr().
mp_cos()
void mp_cos (const MPNumber * x, MPAngleUnit unit, MPNumber * z)
Definition at line 92 of file mp-trigonometric.c.
References convert_to_radians(), mp_is_complex(), mp_set_from_mp(), and MPNumber::num.
Referenced by mp_set_from_float(), and mp_set_from_polar().
mp_cosh()
void mp_cosh (const MPNumber * x, MPNumber * z)
Definition at line 214 of file mp-trigonometric.c.
References MPNumber::num.
Referenced by mp_set_from_float().
mp_divide()
void mp_divide (const MPNumber * x, const MPNumber * y, MPNumber * z)
Definition at line 231 of file mp.c.
References _, mp_is_zero(), mp_set_from_integer(), mperr(), and MPNumber::num.
Referenced by mp_divide_integer(), mp_factorize(), mp_logarithm(), mp_modulus_divide(), mp_set_from_string(), mp_shift(), mp_tan(), mperr(), pf_do_divide(), and unit_convert_from().
mp_divide_integer()
void mp_divide_integer (const MPNumber * x, long y, MPNumber * z)
Definition at line 244 of file mp.c.
References mp_clear(), mp_divide(), mp_new(), and mp_set_from_integer().
Referenced by mp_modular_exponentiation(), mp_set_from_fraction(), mp_tan(), mperr(), pf_do_add_percent(), pf_do_percent(), and pf_do_subtract_percent().
mp_epowy()
void mp_epowy (const MPNumber * x, MPNumber * z)
Definition at line 294 of file mp.c.
References MPNumber::num.
Referenced by mperr().
mp_erf()
void mp_erf (const MPNumber * x, MPNumber * z)
Definition at line 611 of file mp.c.
References _, mp_is_complex(), mp_set_from_integer(), mperr(), and MPNumber::num.
Referenced by mp_set_from_float().
mp_factorial()
void mp_factorial (const MPNumber * x, MPNumber * z)
Definition at line 461 of file mp.c.
References _, mp_add(), mp_clear(), mp_is_complex(), mp_is_natural(), mp_is_negative(), mp_is_zero(), mp_new(), mp_set_from_integer(), mp_to_unsigned_integer(), mperr(), MPNumber::num, and PRECISION.
Referenced by mperr(), and pf_do_factorial().
mp_factorize()
GList * mp_factorize (const MPNumber * x)
mp_factorize tries to factorize the value of @x. If @x < 2^64 it calls mp_factorize_unit64 which deals in integers and should be fast enough for most values. If @x > 2^64 the approach to find factors of @x is as follows:
Try to divide @x by prime numbers 2,3,5,7,.. up to min(2^13, sqrt(x))
Use Pollard rho to find prime factors > 2^13. Returns a pointer to a GList with all prime factors of @x which needs to be freed.
Definition at line 843 of file mp.c.
References mp_abs(), mp_add_integer(), mp_clear(), mp_divide(), mp_factorize_unit64(), mp_invert_sign(), mp_is_equal(), mp_is_greater_than(), mp_is_integer(), mp_is_less_equal(), mp_is_negative(), mp_is_zero(), mp_new(), mp_new_from_unsigned_integer(), mp_set_from_integer(), mp_set_from_mp(), mp_set_from_unsigned_integer(), mp_sqrt(), mp_to_unsigned_integer(), NULL, MPNumber::num, PRECISION, and TRUE.
Referenced by mperr().
mp_factorize_unit64()
GList * mp_factorize_unit64 (uint64_t n)
Definition at line 967 of file mp.c.
References mp_clear(), mp_new(), mp_set_from_mp(), mp_set_from_unsigned_integer(), NULL, MPNumber::num, and PRECISION.
Referenced by mp_factorize(), and mperr().
mp_floor()
void mp_floor (const MPNumber * x, MPNumber * z)
Definition at line 204 of file mp.c.
References MPNumber::num.
Referenced by mp_fractional_part(), mp_modular_exponentiation(), mp_modulus_divide(), mp_shift(), mperr(), and pf_do_floor().
mp_fractional_component()
void mp_fractional_component (const MPNumber * x, MPNumber * z)
Definition at line 188 of file mp.c.
References MPNumber::num.
Referenced by mperr().
mp_fractional_part()
void mp_fractional_part (const MPNumber * x, MPNumber * z)
Definition at line 195 of file mp.c.
References mp_clear(), mp_floor(), mp_new(), and mp_subtract().
Referenced by mperr(), and pf_do_fraction().
mp_free()
void mp_free (MPNumber * z)
Definition at line 86 of file mp.c.
References NULL, and MPNumber::num.
Referenced by mperr(), p_parse(), pf_apply_func_with_npower(), pf_apply_func_with_power(), pf_constant(), pf_convert_1(), pf_convert_number(), pf_do_abs(), pf_do_add(), pf_do_add_percent(), pf_do_and(), pf_do_ceiling(), pf_do_divide(), pf_do_factorial(), pf_do_floor(), pf_do_fraction(), pf_do_mod(), pf_do_multiply(), pf_do_not(), pf_do_nth_root(), pf_do_or(), pf_do_percent(), pf_do_root_3(), pf_do_root_4(), pf_do_round(), pf_do_subtract(), pf_do_subtract_percent(), pf_do_x_pow_y(), pf_do_x_pow_y_int(), pf_do_xor(), pf_set_var(), and pf_unary_minus().
mp_get_error()
const char * mp_get_error (void)
Definition at line 41 of file mp.c.
References mp_error.
Referenced by mp_equation_parse().
mp_get_eulers()
void mp_get_eulers (MPNumber * z)
Definition at line 96 of file mp.c.
References MPNumber::num.
Referenced by mperr().
mp_get_i()
void mp_get_i (MPNumber * z)
Definition at line 105 of file mp.c.
References MPNumber::num.
Referenced by mperr().
mp_get_pi()
void mp_get_pi (MPNumber * z)
Definition at line 75 of file mp-trigonometric.c.
References MPNumber::num.
Referenced by mp_tan(), and mperr().
mp_imaginary_component()
void mp_imaginary_component (const MPNumber * x, MPNumber * z)
Definition at line 151 of file mp.c.
References MPNumber::num.
Referenced by mperr().
mp_integer_component()
void mp_integer_component (const MPNumber * x, MPNumber * z)
Definition at line 181 of file mp.c.
References MPNumber::num.
Referenced by mperr().
mp_invert_sign()
void mp_invert_sign (const MPNumber * x, MPNumber * z)
Definition at line 398 of file mp.c.
References MPNumber::num.
Referenced by mp_factorize(), mp_set_from_string(), mperr(), and pf_unary_minus().
mp_is_complex()
bool mp_is_complex (const MPNumber * x)
Definition at line 281 of file mp.c.
References MPNumber::num.
Referenced by mp_acos(), mp_arg(), mp_asin(), mp_atan(), mp_cos(), mp_erf(), mp_factorial(), mp_is_integer(), mp_is_natural(), mp_is_positive_integer(), mp_ln(), mp_root(), mp_sin(), mp_tan(), mp_xpowy(), mp_zeta(), and mperr().
mp_is_equal()
bool mp_is_equal (const MPNumber * x, const MPNumber * y)
Definition at line 287 of file mp.c.
References MPNumber::num.
Referenced by mp_atan(), mp_factorize(), and mperr().
mp_is_greater_equal()
bool mp_is_greater_equal (const MPNumber * x, const MPNumber * y)
Definition at line 313 of file mp.c.
References mp_compare().
Referenced by mperr().
mp_is_greater_than()
bool mp_is_greater_than (const MPNumber * x, const MPNumber * y)
Definition at line 319 of file mp.c.
References mp_compare().
Referenced by math_equation_toggle_bit(), mp_factorize(), mp_is_overflow(), and mperr().
mp_is_integer()
bool mp_is_integer (const MPNumber * x)
Definition at line 254 of file mp.c.
References mp_is_complex(), and MPNumber::num.
Referenced by math_equation_factorize(), mp_factorize(), mp_is_natural(), mp_is_positive_integer(), mp_modulus_divide(), mp_shift(), mp_tan(), mp_xpowy(), and mperr().
mp_is_less_equal()
bool mp_is_less_equal (const MPNumber * x, const MPNumber * y)
Definition at line 325 of file mp.c.
References mp_compare().
Referenced by mp_factorize(), and mperr().
mp_is_less_than()
bool mp_is_less_than (const MPNumber * x, const MPNumber * y)
Definition at line 331 of file mp.c.
References mp_compare().
Referenced by mp_acosh(), and mperr().
mp_is_natural()
bool mp_is_natural (const MPNumber * x)
Definition at line 272 of file mp.c.
References mp_is_complex(), mp_is_integer(), and MPNumber::num.
Referenced by mp_factorial(), and mperr().
mp_is_negative()
bool mp_is_negative (const MPNumber * x)
Definition at line 307 of file mp.c.
References MPNumber::num.
Referenced by currency_manager_get_currency(), math_equation_toggle_bit(), mp_arg(), mp_factorial(), mp_factorize(), mp_ln(), mp_modular_exponentiation(), mp_root(), mp_xpowy(), and mperr().
mp_is_overflow()
bool mp_is_overflow (const MPNumber * x, int wordlen)
Definition at line 95 of file mp-binary.c.
References mp_clear(), mp_is_greater_than(), mp_new(), mp_set_from_integer(), and mp_xpowy_integer().
Referenced by mp_set_from_float(), and pf_do_not().
mp_is_positive_integer()
bool mp_is_positive_integer (const MPNumber * x)
Definition at line 263 of file mp.c.
References mp_is_complex(), mp_is_integer(), and MPNumber::num.
Referenced by mp_and(), mp_not(), mp_or(), mp_xor(), and mperr().
mp_is_zero()
bool mp_is_zero (const MPNumber * x)
Definition at line 300 of file mp.c.
References MPNumber::num.
Referenced by currency_manager_get_currency(), mp_arg(), mp_divide(), mp_factorial(), mp_factorize(), mp_ln(), mp_logarithm(), mp_modular_exponentiation(), mp_xpowy(), mp_xpowy_integer(), and mperr().
mp_ln()
void mp_ln (const MPNumber * x, MPNumber * z)
Definition at line 337 of file mp.c.
References _, mp_is_complex(), mp_is_negative(), mp_is_zero(), mp_set_from_integer(), mperr(), and MPNumber::num.
Referenced by mp_logarithm(), and mperr().
mp_logarithm()
void mp_logarithm (long n, const MPNumber * x, MPNumber * z)
Definition at line 365 of file mp.c.
References _, mp_clear(), mp_divide(), mp_is_zero(), mp_ln(), mp_new(), mp_set_from_integer(), and mperr().
Referenced by mperr().
mp_modular_exponentiation()
void mp_modular_exponentiation (const MPNumber * x, const MPNumber * y, const MPNumber * p, MPNumber * z)
Definition at line 527 of file mp.c.
References mp_abs(), mp_clear(), mp_divide_integer(), mp_floor(), mp_is_negative(), mp_is_zero(), mp_modulus_divide(), mp_multiply(), mp_new(), mp_reciprocal(), mp_set_from_integer(), and mp_set_from_mp().
Referenced by mperr(), and pf_do_mod().
mp_modulus_divide()
void mp_modulus_divide (const MPNumber * x, const MPNumber * y, MPNumber * z)
Definition at line 500 of file mp.c.
References _, mp_add(), mp_clear(), mp_compare(), mp_divide(), mp_floor(), mp_is_integer(), mp_multiply(), mp_new(), mp_set_from_integer(), mp_subtract(), and mperr().
Referenced by mp_modular_exponentiation(), mperr(), and pf_do_mod().
mp_multiply()
void mp_multiply (const MPNumber * x, const MPNumber * y, MPNumber * z)
Definition at line 386 of file mp.c.
References MPNumber::num.
Referenced by mp_modular_exponentiation(), mp_modulus_divide(), mp_set_from_polar(), mp_set_from_string(), mp_shift(), mperr(), pf_do_add_percent(), pf_do_multiply(), pf_do_subtract_percent(), pf_get_variable(), pf_get_variable_with_power(), and unit_convert_to().
mp_multiply_integer()
void mp_multiply_integer (const MPNumber * x, long y, MPNumber * z)
Definition at line 392 of file mp.c.
References MPNumber::num.
Referenced by mp_set_from_string(), mp_shift(), and mperr().
mp_new()
void MPNumber mp_new (void)
Definition at line 54 of file mp.c.
References MPNumber::num, and PRECISION.
Referenced by character_code_dialog_response_cb(), currency_new(), do_finc_expression(), finc_response_cb(), math_equation_factorize(), math_equation_shift(), math_equation_store(), math_equation_toggle_bit(), math_variables_set(), mp_acos(), mp_acosh(), mp_asin(), mp_atan(), mp_atanh(), mp_divide_integer(), mp_factorial(), mp_factorize(), mp_factorize_unit64(), mp_fractional_part(), mp_is_overflow(), mp_logarithm(), mp_modular_exponentiation(), mp_modulus_divide(), mp_not(), mp_ones_complement(), mp_set_from_polar(), mp_set_from_string(), mp_shift(), mp_tan(), mp_xpowy(), mp_zeta(), mperr(), p_parse(), pf_convert_1(), pf_convert_number(), pf_get_variable(), pf_get_variable_with_power(), and unit_category_convert().
mp_new_from_unsigned_integer()
MPNumber mp_new_from_unsigned_integer (ulong x)
Definition at line 62 of file mp.c.
References MPNumber::num, and PRECISION.
Referenced by mp_factorize(), and mperr().
mp_new_ptr()
MPNumber * mp_new_ptr (void)
Definition at line 71 of file mp.c.
References MPNumber::num, and PRECISION.
Referenced by mperr(), pf_apply_func(), pf_apply_func_with_npower(), pf_apply_func_with_power(), pf_constant(), pf_convert_1(), pf_convert_number(), pf_do_abs(), pf_do_add(), pf_do_add_percent(), pf_do_and(), pf_do_ceiling(), pf_do_divide(), pf_do_factorial(), pf_do_floor(), pf_do_fraction(), pf_do_mod(), pf_do_multiply(), pf_do_not(), pf_do_nth_root(), pf_do_or(), pf_do_percent(), pf_do_root_3(), pf_do_root_4(), pf_do_round(), pf_do_sqrt(), pf_do_subtract(), pf_do_subtract_percent(), pf_do_x_pow_y(), pf_do_x_pow_y_int(), pf_do_xor(), pf_get_variable(), pf_get_variable_with_power(), and pf_unary_minus().
mp_not()
void mp_not (const MPNumber * x, int wordlen, MPNumber * z)
Definition at line 145 of file mp-binary.c.
References _, mp_clear(), mp_is_positive_integer(), mp_new(), mp_set_from_integer(), and mperr().
Referenced by mp_ones_complement(), mp_xnor(), and pf_do_not().
mp_ones_complement()
void mp_ones_complement (const MPNumber * x, int wordlen, MPNumber * z)
Definition at line 187 of file mp-binary.c.
References mp_clear(), mp_new(), mp_not(), and mp_set_from_integer().
Referenced by mp_twos_complement(), and mp_xnor().
mp_or()
void mp_or (const MPNumber * x, const MPNumber * y, MPNumber * z)
Definition at line 121 of file mp-binary.c.
References _, mp_is_positive_integer(), and mperr().
Referenced by mp_set_from_float(), and pf_do_or().
mp_real_component()
void mp_real_component (const MPNumber * x, MPNumber * z)
Definition at line 145 of file mp.c.
References MPNumber::num.
Referenced by mperr().
mp_reciprocal()
void mp_reciprocal (const MPNumber * x, MPNumber * z)
Definition at line 404 of file mp.c.
References MPNumber::num, and PRECISION.
Referenced by mp_modular_exponentiation(), mp_xpowy(), and mperr().
mp_root()
void mp_root (const MPNumber * x, long n, MPNumber * z)
Definition at line 414 of file mp.c.
References _, mp_is_complex(), mp_is_negative(), mp_set_from_integer(), mp_set_from_mp(), mperr(), MPNumber::num, and PRECISION.
Referenced by mp_sqrt(), mp_xpowy(), mperr(), pf_do_nth_root(), pf_do_root_3(), and pf_do_root_4().
mp_round()
void mp_round (const MPNumber * x, MPNumber * z)
Definition at line 218 of file mp.c.
References MPNumber::num.
Referenced by mperr(), and pf_do_round().
mp_set_from_complex()
void mp_set_from_complex (const MPNumber * x, const MPNumber * y, MPNumber * z)
Definition at line 75 of file mp-convert.c.
References MPNumber::num.
Referenced by mp_set_from_float(), and mp_set_from_polar().
mp_set_from_double()
void mp_set_from_double (double x, MPNumber * z)
Definition at line 28 of file mp-convert.c.
References MPNumber::num.
Referenced by mp_set_from_float(), and mp_set_from_random().
mp_set_from_float()
void mp_set_from_float (float x, MPNumber * z)
References mp_acos(), mp_acosh(), mp_and(), mp_asin(), mp_asinh(), mp_atan(), mp_atanh(), mp_cos(), mp_cosh(), mp_erf(), mp_is_overflow(), mp_or(), mp_set_from_complex(), mp_set_from_double(), mp_set_from_float(), mp_set_from_fraction(), mp_set_from_integer(), mp_set_from_polar(), mp_set_from_random(), mp_set_from_string(), mp_set_from_unsigned_integer(), mp_sin(), mp_sinh(), mp_tan(), mp_tanh(), mp_to_double(), mp_to_float(), mp_to_integer(), mp_to_unsigned_integer(), mp_xor(), and mp_zeta().
Referenced by mp_set_from_float().
mp_set_from_fraction()
void mp_set_from_fraction (long numerator, long denominator, MPNumber * z)
Definition at line 46 of file mp-convert.c.
References mp_divide_integer(), and mp_set_from_integer().
Referenced by mp_set_from_float(), and mp_set_from_string().
mp_set_from_integer()
void mp_set_from_integer (long x, MPNumber * z)
Definition at line 34 of file mp-convert.c.
References MPNumber::num.
Referenced by character_code_dialog_response_cb(), mp_acos(), mp_acosh(), mp_arg(), mp_asin(), mp_atan(), mp_atanh(), mp_divide(), mp_divide_integer(), mp_erf(), mp_factorial(), mp_factorize(), mp_is_overflow(), mp_ln(), mp_logarithm(), mp_modular_exponentiation(), mp_modulus_divide(), mp_not(), mp_ones_complement(), mp_root(), mp_set_from_float(), mp_set_from_fraction(), mp_set_from_string(), mp_shift(), mp_tan(), mp_xpowy(), mp_xpowy_integer(), mp_zeta(), pf_convert_1(), pf_do_x_pow_y_int(), pf_get_variable(), and pf_get_variable_with_power().
mp_set_from_mp()
void mp_set_from_mp (const MPNumber * x, MPNumber * z)
Definition at line 22 of file mp-convert.c.
References MPNumber::num.
Referenced by convert_from_radians(), convert_to_radians(), currency_set_value(), math_equation_get_number(), math_equation_set_number(), math_history_entry_insert_entry(), math_variables_set(), mp_cos(), mp_equation_parse(), mp_factorize(), mp_factorize_unit64(), mp_modular_exponentiation(), mp_root(), mp_sin(), mp_tan(), mperr(), p_parse(), pf_get_variable(), and pf_get_variable_with_power().
mp_set_from_polar()
void mp_set_from_polar (const MPNumber * r, MPAngleUnit unit, const MPNumber * theta, MPNumber * z)
Definition at line 59 of file mp-convert.c.
References mp_clear(), mp_cos(), mp_multiply(), mp_new(), mp_set_from_complex(), and mp_sin().
Referenced by mp_set_from_float().
mp_set_from_random()
void mp_set_from_random (MPNumber * z)
Definition at line 81 of file mp-convert.c.
References mp_set_from_double().
Referenced by mp_set_from_float().
mp_set_from_string()
bool mp_set_from_string (const char * text, int default_base, MPNumber * z)
Definition at line 221 of file mp-convert.c.
References FALSE, mp_add(), mp_add_integer(), mp_clear(), mp_divide(), mp_invert_sign(), mp_multiply(), mp_multiply_integer(), mp_new(), mp_set_from_fraction(), mp_set_from_integer(), mp_xpowy_integer(), NULL, and TRUE.
Referenced by finc_response_cb(), mp_serializer_from_string(), mp_set_from_float(), pf_constant(), and pf_convert_number().
mp_set_from_unsigned_integer()
void mp_set_from_unsigned_integer (ulong x, MPNumber * z)
Definition at line 40 of file mp-convert.c.
References MPNumber::num.
Referenced by math_equation_toggle_bit(), mp_factorize(), mp_factorize_unit64(), and mp_set_from_float().
mp_sgn()
void mp_sgn (const MPNumber * x, MPNumber * z)
Definition at line 175 of file mp.c.
References MPNumber::num.
Referenced by mperr().
mp_shift()
void mp_shift (const MPNumber * x, int count, MPNumber * z)
Definition at line 162 of file mp-binary.c.
References _, mp_clear(), mp_divide(), mp_floor(), mp_is_integer(), mp_multiply(), mp_multiply_integer(), mp_new(), mp_set_from_integer(), and mperr().
Referenced by character_code_dialog_response_cb(), math_equation_shift(), and mp_xnor().
mp_sin()
void mp_sin (const MPNumber * x, MPAngleUnit unit, MPNumber * z)
Definition at line 82 of file mp-trigonometric.c.
References convert_to_radians(), mp_is_complex(), mp_set_from_mp(), and MPNumber::num.
Referenced by mp_set_from_float(), and mp_set_from_polar().
mp_sinh()
void mp_sinh (const MPNumber * x, MPNumber * z)
Definition at line 208 of file mp-trigonometric.c.
References MPNumber::num.
Referenced by mp_set_from_float().
mp_sqrt()
void mp_sqrt (const MPNumber * x, MPNumber * z)
Definition at line 455 of file mp.c.
References mp_root().
Referenced by mp_factorize(), mperr(), and pf_do_sqrt().
mp_subtract()
void mp_subtract (const MPNumber * x, const MPNumber * y, MPNumber * z)
Definition at line 169 of file mp.c.
References MPNumber::num.
Referenced by mp_fractional_part(), mp_modulus_divide(), mp_tan(), mperr(), and pf_do_subtract().
mp_tan()
void mp_tan (const MPNumber * x, MPAngleUnit unit, MPNumber * z)
Definition at line 102 of file mp-trigonometric.c.
References _, convert_to_radians(), mp_clear(), mp_divide(), mp_divide_integer(), mp_get_pi(), mp_is_complex(), mp_is_integer(), mp_new(), mp_set_from_integer(), mp_set_from_mp(), mp_subtract(), mperr(), and MPNumber::num.
Referenced by mp_set_from_float().
mp_tanh()
void mp_tanh (const MPNumber * x, MPNumber * z)
Definition at line 220 of file mp-trigonometric.c.
References MPNumber::num.
Referenced by mp_set_from_float().
mp_to_double()
double mp_to_double (const MPNumber * x)
Definition at line 105 of file mp-convert.c.
References MPNumber::num.
Referenced by mp_set_from_float().
mp_to_float()
float mp_to_float (const MPNumber * x)
Definition at line 99 of file mp-convert.c.
References MPNumber::num.
Referenced by mp_set_from_float().
mp_to_integer()
long mp_to_integer (const MPNumber * x)
Definition at line 87 of file mp-convert.c.
References MPNumber::num.
Referenced by mp_set_from_float(), mp_xpowy(), and pf_do_x_pow_y_int().
mp_to_unsigned_integer()
ulong mp_to_unsigned_integer (const MPNumber * x)
Definition at line 93 of file mp-convert.c.
References MPNumber::num.
Referenced by math_equation_toggle_bit(), mp_factorial(), mp_factorize(), and mp_set_from_float().
mp_twos_complement()
void mp_twos_complement (const MPNumber * x, int wordlen, MPNumber * z)
Definition at line 197 of file mp-binary.c.
References mp_add_integer(), and mp_ones_complement().
Referenced by mp_xnor().
mp_xnor()
void mp_xnor (const MPNumber * x, const MPNumber * y, int wordlen, MPNumber * z)
References convert_from_radians(), convert_to_radians(), mp_not(), mp_ones_complement(), mp_shift(), mp_twos_complement(), and mp_xnor().
Referenced by mp_xnor().
mp_xor()
void mp_xor (const MPNumber * x, const MPNumber * y, MPNumber * z)
Definition at line 133 of file mp-binary.c.
References _, mp_is_positive_integer(), and mperr().
Referenced by mp_set_from_float(), and pf_do_xor().
mp_xpowy()
void mp_xpowy (const MPNumber * x, const MPNumber * y, MPNumber * z)
Definition at line 570 of file mp.c.
References _, mp_clear(), mp_is_complex(), mp_is_integer(), mp_is_negative(), mp_is_zero(), mp_new(), mp_reciprocal(), mp_root(), mp_set_from_integer(), mp_to_integer(), mperr(), and MPNumber::num.
Referenced by mperr(), and pf_do_x_pow_y().
mp_xpowy_integer()
void mp_xpowy_integer (const MPNumber * x, long y, MPNumber * z)
Definition at line 597 of file mp.c.
References _, mp_is_zero(), mp_set_from_integer(), mperr(), and MPNumber::num.
Referenced by mp_is_overflow(), mp_set_from_string(), mperr(), pf_apply_func_with_npower(), pf_apply_func_with_power(), pf_do_x_pow_y_int(), and pf_get_variable_with_power().
mp_zeta()
void mp_zeta (const MPNumber * x, MPNumber * z)
Definition at line 625 of file mp.c.
References _, mp_clear(), mp_compare(), mp_is_complex(), mp_new(), mp_set_from_integer(), mperr(), and MPNumber::num.
Referenced by mp_set_from_float().
mperr()
void mperr (const char * format, ...)
References __attribute__, mp_abs(), mp_add(), mp_add_integer(), mp_arg(), mp_ceiling(), mp_clear(), mp_compare(), mp_conjugate(), mp_divide(), mp_divide_integer(), mp_epowy(), mp_factorial(), mp_factorize(), mp_factorize_unit64(), mp_floor(), mp_fractional_component(), mp_fractional_part(), mp_free(), mp_get_eulers(), mp_get_i(), mp_get_pi(), mp_imaginary_component(), mp_integer_component(), mp_invert_sign(), mp_is_complex(), mp_is_equal(), mp_is_greater_equal(), mp_is_greater_than(), mp_is_integer(), mp_is_less_equal(), mp_is_less_than(), mp_is_natural(), mp_is_negative(), mp_is_positive_integer(), mp_is_zero(), mp_ln(), mp_logarithm(), mp_modular_exponentiation(), mp_modulus_divide(), mp_multiply(), mp_multiply_integer(), mp_new(), mp_new_from_unsigned_integer(), mp_new_ptr(), mp_real_component(), mp_reciprocal(), mp_root(), mp_round(), mp_set_from_mp(), mp_sgn(), mp_sqrt(), mp_subtract(), mp_xpowy(), and mp_xpowy_integer().