MATE Desktop Environment: msd-xsettings-manager.c File Reference
msd-xsettings-manager.c File Reference
#include "config.h"
#include <sys/types.h>
#include <sys/wait.h>
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <time.h>
#include <X11/Xatom.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <gdk/gdk.h>
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include "mate-settings-profile.h"
#include "msd-xsettings-manager.h"
#include "xsettings-manager.h"
#include "fontconfig-monitor.h"
#include "wm-common.h"
Macros
#define MOUSE_SCHEMA "org.mate.peripherals-mouse"
#define INTERFACE_SCHEMA "org.mate.interface"
#define SOUND_SCHEMA "org.mate.sound"
#define CURSOR_THEME_KEY "cursor-theme"
#define CURSOR_SIZE_KEY "cursor-size"
#define SCALING_FACTOR_KEY "window-scaling-factor"
#define SCALING_FACTOR_QT_KEY "window-scaling-factor-qt-sync"
#define FONT_RENDER_SCHEMA "org.mate.font-rendering"
#define XSETTINGS_PLUGIN_SCHEMA "org.mate.SettingsDaemon.plugins.xsettings"
#define XSETTINGS_OVERRIDE_KEY "overrides"
#define FONT_ANTIALIASING_KEY "antialiasing"
#define FONT_HINTING_KEY "hinting"
#define FONT_RGBA_ORDER_KEY "rgba-order"
#define FONT_DPI_KEY "dpi"
#define DPI_FALLBACK 96
#define DPI_LOW_REASONABLE_VALUE 50
#define DPI_HIGH_REASONABLE_VALUE 500
#define HIDPI_LIMIT (DPI_FALLBACK * 2 * 90 / 100)
#define HIDPI_MIN_HEIGHT 1440
#define GPOINTER_TO_BOOLEAN(i)
#define GBOOLEAN_TO_POINTER(i)
#define MSD_XSETTINGS_ERROR msd_xsettings_error_quark ()
Typedefs
typedef struct _TranslationEntry TranslationEntry
typedef void(* TranslationFunc) (MateXSettingsManager *manager, TranslationEntry *trans, GVariant *value)
Enumerations
enum { MSD_XSETTINGS_ERROR_INIT }
Functions
gboolean mate_xsettings_manager_start (MateXSettingsManager *manager, GError **error)
void mate_xsettings_manager_stop (MateXSettingsManager *manager)
MateXSettingsManager * mate_xsettings_manager_new (void)
Macro Definition Documentation
CURSOR_SIZE_KEY
#define CURSOR_SIZE_KEY "cursor-size"
Definition at line 54 of file msd-xsettings-manager.c.
CURSOR_THEME_KEY
#define CURSOR_THEME_KEY "cursor-theme"
Definition at line 53 of file msd-xsettings-manager.c.
DPI_FALLBACK
#define DPI_FALLBACK 96
Definition at line 78 of file msd-xsettings-manager.c.
DPI_HIGH_REASONABLE_VALUE
#define DPI_HIGH_REASONABLE_VALUE 500
Definition at line 80 of file msd-xsettings-manager.c.
DPI_LOW_REASONABLE_VALUE
#define DPI_LOW_REASONABLE_VALUE 50
Definition at line 79 of file msd-xsettings-manager.c.
FONT_ANTIALIASING_KEY
#define FONT_ANTIALIASING_KEY "antialiasing"
Definition at line 63 of file msd-xsettings-manager.c.
FONT_DPI_KEY
#define FONT_DPI_KEY "dpi"
Definition at line 66 of file msd-xsettings-manager.c.
FONT_HINTING_KEY
#define FONT_HINTING_KEY "hinting"
Definition at line 64 of file msd-xsettings-manager.c.
FONT_RENDER_SCHEMA
#define FONT_RENDER_SCHEMA "org.mate.font-rendering"
Definition at line 58 of file msd-xsettings-manager.c.
FONT_RGBA_ORDER_KEY
#define FONT_RGBA_ORDER_KEY "rgba-order"
Definition at line 65 of file msd-xsettings-manager.c.
GBOOLEAN_TO_POINTER
#define GBOOLEAN_TO_POINTER (i)
Value:
(GINT_TO_POINTER ((i) ? 2 : 1))
Definition at line 93 of file msd-xsettings-manager.c.
GPOINTER_TO_BOOLEAN
#define GPOINTER_TO_BOOLEAN (i)
Value:
((gboolean) ((GPOINTER_TO_INT(i) == 2) ? TRUE : FALSE))
Definition at line 92 of file msd-xsettings-manager.c.
HIDPI_LIMIT
#define HIDPI_LIMIT (DPI_FALLBACK * 2 * 90 / 100)
Definition at line 85 of file msd-xsettings-manager.c.
HIDPI_MIN_HEIGHT
#define HIDPI_MIN_HEIGHT 1440
Definition at line 90 of file msd-xsettings-manager.c.
INTERFACE_SCHEMA
#define INTERFACE_SCHEMA "org.mate.interface"
Definition at line 50 of file msd-xsettings-manager.c.
MOUSE_SCHEMA
#define MOUSE_SCHEMA "org.mate.peripherals-mouse"
Definition at line 49 of file msd-xsettings-manager.c.
MSD_XSETTINGS_ERROR
#define MSD_XSETTINGS_ERROR msd_xsettings_error_quark ()
Definition at line 118 of file msd-xsettings-manager.c.
Referenced by mate_xsettings_manager_start().
SCALING_FACTOR_KEY
#define SCALING_FACTOR_KEY "window-scaling-factor"
Definition at line 55 of file msd-xsettings-manager.c.
SCALING_FACTOR_QT_KEY
#define SCALING_FACTOR_QT_KEY "window-scaling-factor-qt-sync"
Definition at line 56 of file msd-xsettings-manager.c.
SOUND_SCHEMA
#define SOUND_SCHEMA "org.mate.sound"
Definition at line 51 of file msd-xsettings-manager.c.
XSETTINGS_OVERRIDE_KEY
#define XSETTINGS_OVERRIDE_KEY "overrides"
Definition at line 61 of file msd-xsettings-manager.c.
Referenced by mate_xsettings_manager_start().
XSETTINGS_PLUGIN_SCHEMA
#define XSETTINGS_PLUGIN_SCHEMA "org.mate.SettingsDaemon.plugins.xsettings"
Definition at line 60 of file msd-xsettings-manager.c.
Referenced by mate_xsettings_manager_start().
Typedef Documentation
TranslationEntry
typedef struct _TranslationEntry TranslationEntry
Definition at line 95 of file msd-xsettings-manager.c.
TranslationFunc
typedef void(* TranslationFunc) (MateXSettingsManager *manager, TranslationEntry *trans, GVariant *value)
Definition at line 96 of file msd-xsettings-manager.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MSD_XSETTINGS_ERROR_INIT
Definition at line 120 of file msd-xsettings-manager.c.
Function Documentation
mate_xsettings_manager_new()
MateXSettingsManager * mate_xsettings_manager_new (void)
Definition at line 1063 of file msd-xsettings-manager.c.
References MATE_TYPE_XSETTINGS_MANAGER, MATE_XSETTINGS_MANAGER, and NULL.
mate_xsettings_manager_start()
gboolean mate_xsettings_manager_start (MateXSettingsManager * manager, GError ** error)
Definition at line 908 of file msd-xsettings-manager.c.
References error, FALSE, FONT_RENDER_SCHEMA, INTERFACE_SCHEMA, mate_settings_profile_end, mate_settings_profile_start, MOUSE_SCHEMA, MSD_XSETTINGS_ERROR, MSD_XSETTINGS_ERROR_INIT, NULL, SOUND_SCHEMA, TRUE, xsettings_manager_notify(), xsettings_manager_set_overrides(), xsettings_manager_set_string(), XSETTINGS_OVERRIDE_KEY, and XSETTINGS_PLUGIN_SCHEMA.
mate_xsettings_manager_stop()
void mate_xsettings_manager_stop (MateXSettingsManager * manager)
Definition at line 999 of file msd-xsettings-manager.c.
References NULL, and xsettings_manager_destroy().