MATE Desktop Environment: msd-keyboard-xkb.c File Reference
msd-keyboard-xkb.c File Reference
#include "config.h"
#include <string.h>
#include <time.h>
#include <glib/gi18n.h>
#include <gdk/gdk.h>
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <libmate-desktop/mate-image-menu-item.h>
#include <libmatekbd/matekbd-status.h>
#include <libmatekbd/matekbd-keyboard-drawing.h>
#include <libmatekbd/matekbd-desktop-config.h>
#include <libmatekbd/matekbd-keyboard-config.h>
#include <libmatekbd/matekbd-util.h>
#include "msd-keyboard-xkb.h"
#include "delayed-dialog.h"
#include "mate-settings-profile.h"
Macros
#define GTK_RESPONSE_PRINT 2
#define MATEKBD_DESKTOP_SCHEMA "org.mate.peripherals-keyboard-xkb.general"
#define MATEKBD_KBD_SCHEMA "org.mate.peripherals-keyboard-xkb.kbd"
#define KNOWN_FILES_KEY "known-file-list"
#define DISABLE_INDICATOR_KEY "disable-indicator"
#define DUPLICATE_LEDS_KEY "duplicate-leds"
Functions
void msd_keyboard_xkb_set_post_activation_callback (PostActivationCallback fun, void *user_data)
void msd_keyboard_xkb_init (MsdKeyboardManager *kbd_manager)
void msd_keyboard_xkb_shutdown (void)
Macro Definition Documentation
DISABLE_INDICATOR_KEY
#define DISABLE_INDICATOR_KEY "disable-indicator"
Definition at line 53 of file msd-keyboard-xkb.c.
DUPLICATE_LEDS_KEY
#define DUPLICATE_LEDS_KEY "duplicate-leds"
Definition at line 54 of file msd-keyboard-xkb.c.
GTK_RESPONSE_PRINT
#define GTK_RESPONSE_PRINT 2
Definition at line 47 of file msd-keyboard-xkb.c.
KNOWN_FILES_KEY
#define KNOWN_FILES_KEY "known-file-list"
Definition at line 52 of file msd-keyboard-xkb.c.
MATEKBD_DESKTOP_SCHEMA
#define MATEKBD_DESKTOP_SCHEMA "org.mate.peripherals-keyboard-xkb.general"
Definition at line 49 of file msd-keyboard-xkb.c.
Referenced by msd_keyboard_xkb_init().
MATEKBD_KBD_SCHEMA
#define MATEKBD_KBD_SCHEMA "org.mate.peripherals-keyboard-xkb.kbd"
Definition at line 50 of file msd-keyboard-xkb.c.
Referenced by msd_keyboard_xkb_init().
Function Documentation
msd_keyboard_xkb_init()
void msd_keyboard_xkb_init (MsdKeyboardManager * kbd_manager)
Definition at line 569 of file msd-keyboard-xkb.c.
References DATADIR, mate_settings_profile_end, mate_settings_profile_start, matekbd_desktop_config_init(), matekbd_desktop_config_start_listen(), MATEKBD_DESKTOP_SCHEMA, MATEKBD_KBD_SCHEMA, matekbd_keyboard_config_init(), matekbd_keyboard_config_start_listen(), NULL, and TRUE.
msd_keyboard_xkb_set_post_activation_callback()
void msd_keyboard_xkb_set_post_activation_callback (PostActivationCallback fun, void * user_data)
Definition at line 499 of file msd-keyboard-xkb.c.
References user_data.
msd_keyboard_xkb_shutdown()
void msd_keyboard_xkb_shutdown (void)
Definition at line 652 of file msd-keyboard-xkb.c.
References FALSE, and NULL.
Referenced by msd_keyboard_manager_stop().