MATE Desktop Environment: msd-media-keys-manager.c File Reference
msd-media-keys-manager.c File Reference
#include "config.h"
#include <glib.h>
#include <glib/gi18n.h>
#include <gdk/gdk.h>
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include "mate-settings-profile.h"
#include "msd-marshal.h"
#include "msd-media-keys-manager.h"
#include "eggaccelerators.h"
#include "acme.h"
#include "msd-media-keys-window.h"
#include "msd-input-helper.h"
Macros
#define MSD_DBUS_PATH "/org/mate/SettingsDaemon"
#define MSD_DBUS_NAME "org.mate.SettingsDaemon"
#define MSD_MEDIA_KEYS_DBUS_PATH MSD_DBUS_PATH "/MediaKeys"
#define MSD_MEDIA_KEYS_DBUS_NAME MSD_DBUS_NAME ".MediaKeys"
#define TOUCHPAD_SCHEMA "org.mate.peripherals-touchpad"
#define TOUCHPAD_ENABLED_KEY "touchpad-enabled"
#define SOUND_SCHEMA "org.mate.sound"
#define VOLUME_OVERAMPLIFIABLE_KEY "volume-overamplifiable"
#define NO_SCORE 0
#define SCORE_CAN_EJECT 50
#define SCORE_HAS_MEDIA 100
Functions
gboolean msd_media_keys_manager_start (MsdMediaKeysManager *manager, GError **error)
void msd_media_keys_manager_stop (MsdMediaKeysManager *manager)
MsdMediaKeysManager * msd_media_keys_manager_new (void)
Macro Definition Documentation
MSD_DBUS_NAME
#define MSD_DBUS_NAME "org.mate.SettingsDaemon"
Definition at line 51 of file msd-media-keys-manager.c.
MSD_DBUS_PATH
#define MSD_DBUS_PATH "/org/mate/SettingsDaemon"
Definition at line 50 of file msd-media-keys-manager.c.
MSD_MEDIA_KEYS_DBUS_NAME
#define MSD_MEDIA_KEYS_DBUS_NAME MSD_DBUS_NAME ".MediaKeys"
Definition at line 53 of file msd-media-keys-manager.c.
MSD_MEDIA_KEYS_DBUS_PATH
#define MSD_MEDIA_KEYS_DBUS_PATH MSD_DBUS_PATH "/MediaKeys"
Definition at line 52 of file msd-media-keys-manager.c.
NO_SCORE
#define NO_SCORE 0
Definition at line 596 of file msd-media-keys-manager.c.
SCORE_CAN_EJECT
#define SCORE_CAN_EJECT 50
Definition at line 597 of file msd-media-keys-manager.c.
SCORE_HAS_MEDIA
#define SCORE_HAS_MEDIA 100
Definition at line 598 of file msd-media-keys-manager.c.
SOUND_SCHEMA
#define SOUND_SCHEMA "org.mate.sound"
Definition at line 58 of file msd-media-keys-manager.c.
Referenced by mate_xsettings_manager_start().
TOUCHPAD_ENABLED_KEY
#define TOUCHPAD_ENABLED_KEY "touchpad-enabled"
Definition at line 56 of file msd-media-keys-manager.c.
TOUCHPAD_SCHEMA
#define TOUCHPAD_SCHEMA "org.mate.peripherals-touchpad"
Definition at line 55 of file msd-media-keys-manager.c.
VOLUME_OVERAMPLIFIABLE_KEY
#define VOLUME_OVERAMPLIFIABLE_KEY "volume-overamplifiable"
Definition at line 59 of file msd-media-keys-manager.c.
Function Documentation
msd_media_keys_manager_new()
MsdMediaKeysManager * msd_media_keys_manager_new (void)
Definition at line 1834 of file msd-media-keys-manager.c.
References MSD_MEDIA_KEYS_MANAGER, MSD_TYPE_MEDIA_KEYS_MANAGER, and NULL.
Referenced by main().
msd_media_keys_manager_start()
gboolean msd_media_keys_manager_start (MsdMediaKeysManager * manager, GError ** error)
Definition at line 1604 of file msd-media-keys-manager.c.
References error, mate_mixer_context_new(), mate_mixer_context_open(), mate_mixer_is_initialized(), mate_settings_profile_end, mate_settings_profile_start, NULL, and TRUE.
Referenced by main().
msd_media_keys_manager_stop()
void msd_media_keys_manager_stop (MsdMediaKeysManager * manager)
Definition at line 1645 of file msd-media-keys-manager.c.
References FALSE, grab_key_unsafe(), HANDLED_KEYS, key, NULL, and TRUE.