MATE Desktop Environment: msd-timeline.c File Reference
msd-timeline.c File Reference
#include <glib.h>
#include <gtk/gtk.h>
#include <math.h>
#include "msd-timeline.h"
Macros
#define MSECS_PER_SEC 1000
#define FRAME_INTERVAL(nframes)
#define DEFAULT_FPS 30
Typedefs
typedef struct _MsdTimelinePrivate MsdTimelinePrivate
Enumerations
enum {
PROP_0 , PROP_FPS , PROP_DURATION , PROP_LOOP ,
PROP_DIRECTION , PROP_SCREEN , PROP_PROGRESS_TYPE
}
enum {
STARTED , PAUSED , FINISHED , FRAME ,
LAST_SIGNAL
}
Functions
GType msd_timeline_direction_get_type (void)
GType msd_timeline_progress_type_get_type (void)
MsdTimeline * msd_timeline_new (guint duration)
MsdTimeline * msd_timeline_new_for_screen (guint duration, GdkScreen *screen)
void msd_timeline_start (MsdTimeline *timeline)
void msd_timeline_pause (MsdTimeline *timeline)
void msd_timeline_rewind (MsdTimeline *timeline)
gboolean msd_timeline_is_running (MsdTimeline *timeline)
guint msd_timeline_get_fps (MsdTimeline *timeline)
void msd_timeline_set_fps (MsdTimeline *timeline, guint fps)
gboolean msd_timeline_get_loop (MsdTimeline *timeline)
void msd_timeline_set_loop (MsdTimeline *timeline, gboolean loop)
void msd_timeline_set_duration (MsdTimeline *timeline, guint duration)
guint msd_timeline_get_duration (MsdTimeline *timeline)
MsdTimelineDirection msd_timeline_get_direction (MsdTimeline *timeline)
void msd_timeline_set_direction (MsdTimeline *timeline, MsdTimelineDirection direction)
GdkScreen * msd_timeline_get_screen (MsdTimeline *timeline)
void msd_timeline_set_screen (MsdTimeline *timeline, GdkScreen *screen)
void msd_timeline_set_progress_type (MsdTimeline *timeline, MsdTimelineProgressType type)
MsdTimelineProgressType msd_timeline_get_progress_type (MsdTimeline *timeline)
void msd_timeline_set_progress_func (MsdTimeline *timeline, MsdTimelineProgressFunc progress_func)
gdouble msd_timeline_get_progress (MsdTimeline *timeline)
Macro Definition Documentation
DEFAULT_FPS
#define DEFAULT_FPS 30
Definition at line 28 of file msd-timeline.c.
FRAME_INTERVAL
#define FRAME_INTERVAL (nframes)
Value:
(MSECS_PER_SEC / nframes)
Definition at line 27 of file msd-timeline.c.
MSECS_PER_SEC
#define MSECS_PER_SEC 1000
Definition at line 26 of file msd-timeline.c.
Typedef Documentation
MsdTimelinePrivate
typedef struct _MsdTimelinePrivate MsdTimelinePrivate
Definition at line 30 of file msd-timeline.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
STARTED
PAUSED
FINISHED
FRAME
LAST_SIGNAL
Definition at line 58 of file msd-timeline.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_FPS
PROP_DURATION
PROP_LOOP
PROP_DIRECTION
PROP_SCREEN
PROP_PROGRESS_TYPE
Definition at line 48 of file msd-timeline.c.
Function Documentation
msd_timeline_direction_get_type()
GType msd_timeline_direction_get_type (void)
Definition at line 81 of file msd-timeline.c.
References MSD_TIMELINE_DIRECTION_BACKWARD, MSD_TIMELINE_DIRECTION_FORWARD, and NULL.
msd_timeline_get_direction()
MsdTimelineDirection msd_timeline_get_direction (MsdTimeline * timeline)
msd_timeline_get_direction: @timeline: A MsdTimeline
Returns the direction of the timeline.
Return Value: direction
Definition at line 690 of file msd-timeline.c.
References MSD_IS_TIMELINE, and MSD_TIMELINE_DIRECTION_FORWARD.
msd_timeline_get_duration()
guint msd_timeline_get_duration (MsdTimeline * timeline)
Definition at line 670 of file msd-timeline.c.
References MSD_IS_TIMELINE.
msd_timeline_get_fps()
guint msd_timeline_get_fps (MsdTimeline * timeline)
msd_timeline_get_fps: @timeline: A MsdTimeline
Returns the number of frames per second.
Return Value: frames per second
Definition at line 570 of file msd-timeline.c.
References MSD_IS_TIMELINE.
msd_timeline_get_loop()
gboolean msd_timeline_get_loop (MsdTimeline * timeline)
msd_timeline_get_loop: @timeline: A MsdTimeline
Returns whether the timeline loops to the beginning when it has reached the end.
Return Value: TRUE if the timeline loops
Definition at line 622 of file msd-timeline.c.
References FALSE, and MSD_IS_TIMELINE.
msd_timeline_get_progress()
gdouble msd_timeline_get_progress (MsdTimeline * timeline)
Definition at line 807 of file msd-timeline.c.
References MSD_IS_TIMELINE, MSD_TIMELINE_DIRECTION_BACKWARD, and NULL.
msd_timeline_get_progress_type()
MsdTimelineProgressType msd_timeline_get_progress_type (MsdTimeline * timeline)
Definition at line 767 of file msd-timeline.c.
References MSD_IS_TIMELINE, and MSD_TIMELINE_PROGRESS_LINEAR.
msd_timeline_get_screen()
GdkScreen * msd_timeline_get_screen (MsdTimeline * timeline)
Definition at line 722 of file msd-timeline.c.
References MSD_IS_TIMELINE, and NULL.
msd_timeline_is_running()
gboolean msd_timeline_is_running (MsdTimeline * timeline)
msd_timeline_is_running: @timeline: A MsdTimeline
Returns whether the timeline is running or not.
Return Value: TRUE if the timeline is running
Definition at line 550 of file msd-timeline.c.
References FALSE, and MSD_IS_TIMELINE.
Referenced by msd_timeline_rewind(), and msd_timeline_set_fps().
msd_timeline_new()
MsdTimeline * msd_timeline_new (guint duration)
msd_timeline_new: @duration: duration in milliseconds for the timeline
Creates a new MsdTimeline with the specified number of frames.
Return Value: the newly created MsdTimeline
Definition at line 418 of file msd-timeline.c.
References MSD_TYPE_TIMELINE, and NULL.
msd_timeline_new_for_screen()
MsdTimeline * msd_timeline_new_for_screen (guint duration, GdkScreen * screen)
Definition at line 426 of file msd-timeline.c.
References MSD_TYPE_TIMELINE, and NULL.
msd_timeline_pause()
void msd_timeline_pause (MsdTimeline * timeline)
msd_timeline_pause: @timeline: A MsdTimeline
Pauses the timeline.
Definition at line 497 of file msd-timeline.c.
References MSD_IS_TIMELINE, and PAUSED.
Referenced by msd_locate_pointer().
msd_timeline_progress_type_get_type()
GType msd_timeline_progress_type_get_type (void)
Definition at line 100 of file msd-timeline.c.
References MSD_TIMELINE_PROGRESS_EXPONENTIAL, MSD_TIMELINE_PROGRESS_LINEAR, MSD_TIMELINE_PROGRESS_SINUSOIDAL, and NULL.
msd_timeline_rewind()
void msd_timeline_rewind (MsdTimeline * timeline)
msd_timeline_rewind: @timeline: A MsdTimeline
Rewinds the timeline.
Definition at line 521 of file msd-timeline.c.
References MSD_IS_TIMELINE, msd_timeline_is_running(), and NULL.
Referenced by msd_locate_pointer().
msd_timeline_set_direction()
void msd_timeline_set_direction (MsdTimeline * timeline, MsdTimelineDirection direction)
msd_timeline_set_direction: @timeline: A MsdTimeline @direction: direction
Sets the direction of the timeline.
Definition at line 708 of file msd-timeline.c.
References MSD_IS_TIMELINE.
msd_timeline_set_duration()
void msd_timeline_set_duration (MsdTimeline * timeline, guint duration)
Definition at line 655 of file msd-timeline.c.
References MSD_IS_TIMELINE.
msd_timeline_set_fps()
void msd_timeline_set_fps (MsdTimeline * timeline, guint fps)
msd_timeline_set_fps: @timeline: A MsdTimeline @fps: frames per second
Sets the number of frames per second that the timeline will play.
Definition at line 589 of file msd-timeline.c.
References FRAME_INTERVAL, MSD_IS_TIMELINE, and msd_timeline_is_running().
msd_timeline_set_loop()
void msd_timeline_set_loop (MsdTimeline * timeline, gboolean loop)
msd_timeline_set_loop: @timeline: A MsdTimeline @loop: TRUE to make the timeline loop
Sets whether the timeline loops to the beginning when it has reached the end.
Definition at line 641 of file msd-timeline.c.
References FALSE, loop, and MSD_IS_TIMELINE.
msd_timeline_set_progress_func()
void msd_timeline_set_progress_func (MsdTimeline * timeline, MsdTimelineProgressFunc progress_func)
msd_timeline_set_progress_func: @timeline: A MsdTimeline @progress_func: progress function
Sets the progress function. This function will be used to calculate a different progress to pass to the ::frame signal based on the linear progress through the timeline. Setting progress_func to NULL will make the timeline use the default function, which is just a linear progress.
All progresses are in the [0.0, 1.0] range.
Definition at line 795 of file msd-timeline.c.
References MSD_IS_TIMELINE.
msd_timeline_set_progress_type()
void msd_timeline_set_progress_type (MsdTimeline * timeline, MsdTimelineProgressType type)
Definition at line 752 of file msd-timeline.c.
References MSD_IS_TIMELINE.
msd_timeline_set_screen()
void msd_timeline_set_screen (MsdTimeline * timeline, GdkScreen * screen)
Definition at line 733 of file msd-timeline.c.
References MSD_IS_TIMELINE.
msd_timeline_start()
void msd_timeline_start (MsdTimeline * timeline)
msd_timeline_start: @timeline: A MsdTimeline
Runs the timeline from the current frame.
Definition at line 442 of file msd-timeline.c.
References FALSE, FRAME_INTERVAL, MSD_IS_TIMELINE, NULL, and STARTED.
Referenced by msd_locate_pointer().