MATE Desktop Environment: msd-keyboard-xkb.h File Reference
msd-keyboard-xkb.h File Reference
#include <libxklavier/xklavier.h>
#include "msd-keyboard-manager.h"
Typedefs
typedef void(* PostActivationCallback) (void *userData)
Functions
void msd_keyboard_xkb_init (MsdKeyboardManager *manager)
void msd_keyboard_xkb_shutdown (void)
void msd_keyboard_xkb_set_post_activation_callback (PostActivationCallback fun, void *userData)
Typedef Documentation
PostActivationCallback
typedef void(* PostActivationCallback) (void *userData)
Definition at line 34 of file msd-keyboard-xkb.h.
Function Documentation
msd_keyboard_xkb_init()
void msd_keyboard_xkb_init (MsdKeyboardManager * manager)
Definition at line 569 of file msd-keyboard-xkb.c.
References DATADIR, mate_settings_profile_end, mate_settings_profile_start, matekbd_desktop_config_init(), matekbd_desktop_config_start_listen(), MATEKBD_DESKTOP_SCHEMA, MATEKBD_KBD_SCHEMA, matekbd_keyboard_config_init(), matekbd_keyboard_config_start_listen(), NULL, and TRUE.
msd_keyboard_xkb_set_post_activation_callback()
void msd_keyboard_xkb_set_post_activation_callback (PostActivationCallback fun, void * userData)
Definition at line 499 of file msd-keyboard-xkb.c.
References user_data.
msd_keyboard_xkb_shutdown()
void msd_keyboard_xkb_shutdown (void)
Definition at line 652 of file msd-keyboard-xkb.c.
References FALSE, and NULL.
Referenced by msd_keyboard_manager_stop().