MATE Desktop Environment: na-core-utils.c File Reference
na-core-utils.c File Reference
#include <glib/gi18n-lib.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <glib/gstdio.h>
#include <gtk/gtk.h>
#include <api/na-core-utils.h>
Macros
#define CA_SIZE_MIN 1
#define CA_SIZE_MAX 1048576 /* 1 MB */
Functions
gboolean na_core_utils_boolean_from_string (const gchar *string)
int na_core_utils_str_collate (const gchar *str1, const gchar *str2)
gchar * na_core_utils_str_remove_char (const gchar *string, const gchar *to_remove)
gchar * na_core_utils_str_remove_suffix (const gchar *string, const gchar *suffix)
void na_core_utils_str_split_first_word (const gchar *string, gchar **first, gchar **other)
gchar * na_core_utils_str_subst (const gchar *pattern, const gchar *key, const gchar *subst)
void na_core_utils_slist_add_message (GSList **messages, const gchar *format,...)
GSList * na_core_utils_slist_duplicate (GSList *slist)
void na_core_utils_slist_dump (const gchar *prefix, GSList *list)
GSList * na_core_utils_slist_from_split (const gchar *text, const gchar *separator)
GSList * na_core_utils_slist_from_array (const gchar **str_array)
gchar * na_core_utils_slist_join_at_end (GSList *slist, const gchar *link)
GSList * na_core_utils_slist_remove_ascii (GSList *slist, const gchar *text)
GSList * na_core_utils_slist_remove_utf8 (GSList *slist, const gchar *text)
gchar ** na_core_utils_slist_to_array (GSList *slist)
gchar * na_core_utils_slist_to_text (GSList *slist)
GSList * na_core_utils_slist_setup_element (GSList *list, const gchar *element, gboolean set)
guint na_core_utils_slist_count (GSList *list, const gchar *str)
gboolean na_core_utils_slist_find_negated (GSList *list, const gchar *str)
gboolean na_core_utils_slist_are_equal (GSList *a, GSList *b)
void na_core_utils_slist_free (GSList *slist)
gchar * na_core_utils_gstring_joinv (const gchar *start, const gchar *separator, gchar **list)
void na_core_utils_selcount_get_ope_int (const gchar *selcount, gchar **ope, gchar **uint)
gboolean na_core_utils_dir_is_writable_path (const gchar *path)
gboolean na_core_utils_dir_is_writable_uri (const gchar *uri)
void na_core_utils_dir_list_perms (const gchar *path, const gchar *message)
void na_core_utils_dir_split_ext (const gchar *string, gchar **first, gchar **ext)
gboolean na_core_utils_file_delete (const gchar *path)
gboolean na_core_utils_file_exists (const gchar *uri)
gboolean na_core_utils_file_is_loadable (const gchar *uri)
void na_core_utils_file_list_perms (const gchar *path, const gchar *message)
gchar * na_core_utils_file_load_from_uri (const gchar *uri, gsize *length)
void na_core_utils_print_version (void)
Macro Definition Documentation
CA_SIZE_MAX
#define CA_SIZE_MAX 1048576 /* 1 MB */
Definition at line 53 of file na-core-utils.c.
CA_SIZE_MIN
#define CA_SIZE_MIN 1
Definition at line 52 of file na-core-utils.c.
Function Documentation
na_core_utils_boolean_from_string()
gboolean na_core_utils_boolean_from_string (const gchar * string)
na_core_utils_boolean_from_string @string: a string to be converted.
Returns: TRUE if the string evaluates to "true" (case insensitive), FALSE else.
Since: 2.30
Definition at line 72 of file na-core-utils.c.
References FALSE.
Referenced by cadp_reader_ifactory_provider_read_data().
na_core_utils_dir_is_writable_path()
gboolean na_core_utils_dir_is_writable_path (const gchar * path)
na_core_utils_dir_is_writable_path: @path: the path of the directory to be tested.
Returns: TRUE if the directory is writable, FALSE else.
Please note that this type of test is subject to race conditions, as the directory may become unwritable after a successful test, but before the caller has been able to actually write into it.
There is no "super-test". Just try...
Since: 2.30
Definition at line 835 of file na-core-utils.c.
References FALSE.
Referenced by cadp_iio_provider_is_able_to_write().
na_core_utils_dir_is_writable_uri()
gboolean na_core_utils_dir_is_writable_uri (const gchar * uri)
na_core_utils_dir_is_writable_uri: @uri: the URI of the directory to be tested.
Returns: TRUE if the directory is writable, FALSE else.
Please note that this type of test is subject to race conditions, as the directory may become unwritable after a successful test, but before the caller has been able to actually write into it.
There is no "super-test". Just try...
Since: 2.30
Definition at line 868 of file na-core-utils.c.
References FALSE.
Referenced by cact_tree_model_dnd_imulti_drag_source_drag_data_get().
na_core_utils_dir_list_perms()
void na_core_utils_dir_list_perms (const gchar * path, const gchar * message)
na_core_utils_dir_list_perms: @path: the path of the directory to be tested. @message: a message to be printed if not NULL.
Displays the permissions of the directory on debug output.
Since: 3.1
Definition at line 934 of file na-core-utils.c.
References message().
Referenced by cadp_iio_provider_is_able_to_write(), and cadp_iio_provider_write_item().
na_core_utils_dir_split_ext()
void na_core_utils_dir_split_ext (const gchar * string, gchar ** first, gchar ** ext)
na_core_utils_dir_split_ext: @string: the input path or URI to be splitted. @first: a pointer to a buffer which will contain the first part of the split. @ext: a pointer to a buffer which will contain the extension part of the path.
Split the given @string, returning the first part and the extension in newly allocated buffers which should be g_free() by the caller.
The extension is set to an empty string if no extension is detected.
Since: 2.30
Definition at line 953 of file na-core-utils.c.
Referenced by na_tokens_new_for_example(), and na_tokens_new_from_selection().
na_core_utils_file_delete()
gboolean na_core_utils_file_delete (const gchar * path)
na_core_utils_file_delete: @path: the path of the file to be deleted.
Returns: TRUE if the file is successfully deleted, FALSE else.
Since: 2.30
Definition at line 992 of file na-core-utils.c.
References FALSE, and TRUE.
Referenced by cadp_utils_uri_delete().
na_core_utils_file_exists()
gboolean na_core_utils_file_exists (const gchar * uri)
na_core_utils_file_exists: @uri: a file URI.
Returns: TRUE if the specified file exists, FALSE else.
Race condition: cf. na_core_utils_dir_is_writable_path() and na_core_utils_dir_is_writable_uri() comments.
Since: 2.30
Definition at line 1023 of file na-core-utils.c.
References NULL.
na_core_utils_file_is_loadable()
gboolean na_core_utils_file_is_loadable (const gchar * uri)
na_core_utils_file_is_loadable: @uri: the URI to be checked.
Checks that the file is suitable to be loaded in memory, because it is not empty, and its size is reasonable (less than 1MB). Also checks that a file is a regular file (or a symlink to a regular file).
Returns: whether the file is suitable to be loaded in memory.
Since: 3.1
Definition at line 1049 of file na-core-utils.c.
References FALSE.
Referenced by cadp_reader_iimporter_import_from_uri().
na_core_utils_file_list_perms()
void na_core_utils_file_list_perms (const gchar * path, const gchar * message)
na_core_utils_file_list_perms: @path: the path of the file to be tested. @message: a message to be printed if not NULL.
Displays the permissions of the file on debug output.
Since: 3.2
Definition at line 1131 of file na-core-utils.c.
References message().
na_core_utils_file_load_from_uri()
gchar * na_core_utils_file_load_from_uri (const gchar * uri, gsize * length)
na_core_utils_file_load_from_uri: @uri: the URI the file must be loaded from. @length: a pointer to the length of the read content.
Loads the file into a newly allocated buffer, and set up the length of the read content if not NULL.
Returns: the newly allocated buffer which contains the file content, or NULL. This buffer should be g_free() by the caller.
Since: 2.30
Definition at line 1175 of file na-core-utils.c.
References data, error, and NULL.
Referenced by cadp_desktop_file_new_from_uri().
na_core_utils_gstring_joinv()
gchar * na_core_utils_gstring_joinv (const gchar * start, const gchar * separator, gchar ** list)
na_core_utils_gstring_joinv: @start: a prefix to be written at the beginning of the output string. @separator: a string to be used as separator. @list: the list of strings to be concatenated.
Concatenates a gchar **list of strings to a new string.
Returns: a newly allocated string which should be g_free() by the caller.
Since: 2.30
Definition at line 757 of file na-core-utils.c.
References FALSE, and NULL.
na_core_utils_print_version()
void na_core_utils_print_version (void)
na_core_utils_print_version:
Print a version message on the console
<programlisting> caja-actions-new (Caja-Actions) v 2.29.1 Copyright (C) 2005-2007 Frederic Ruaudel Copyright (C) 2009, 2010, 2011, 2012 Pierre Wieser Copyright (C) 2013-2020 Wolfgang Ulbrich Copyright (C) 2021 The MATE developers Caja-Actions is free software, licensed under GPLv2 or later. </programlisting>
Since: 2.30
Definition at line 1226 of file na-core-utils.c.
References _, PACKAGE_NAME, and PACKAGE_VERSION.
Referenced by main().
na_core_utils_selcount_get_ope_int()
void na_core_utils_selcount_get_ope_int (const gchar * selcount, gchar ** ope, gchar ** uint)
Definition at line 798 of file na-core-utils.c.
References NULL.
na_core_utils_slist_add_message()
void na_core_utils_slist_add_message (GSList ** messages, const gchar * format, ...)
Definition at line 329 of file na-core-utils.c.
Referenced by cadp_reader_iimporter_import_from_uri().
na_core_utils_slist_are_equal()
gboolean na_core_utils_slist_are_equal (GSList * a, GSList * b)
na_core_utils_slist_are_equal: : a GSList of strings. : another GSList of strings to be compared with @first.
Compare two string lists, without regards to the order.
Returns: TRUE if the two lists have same content.
Since: 2.30
Definition at line 708 of file na-core-utils.c.
References b, FALSE, na_core_utils_slist_count(), and TRUE.
na_core_utils_slist_count()
guint na_core_utils_slist_count (GSList * list, const gchar * str)
na_core_utils_slist_count: @list: the GSList of strings to be searched. @str: the searched string.
Search for a string in a string list.
Returns: the count of @ßtr in @list list.
Since: 2.30
Definition at line 644 of file na-core-utils.c.
References na_core_utils_str_collate().
Referenced by na_core_utils_slist_are_equal(), and na_core_utils_slist_setup_element().
na_core_utils_slist_dump()
void na_core_utils_slist_dump (const gchar * prefix, GSList * list)
na_core_utils_slist_dump: @prefix: a string to be used as a prefix for each outputed line. @list: a list of strings.
Dumps the content of a list of strings.
Since: 2.30
Definition at line 377 of file na-core-utils.c.
References prefix.
Referenced by base_builder_get_toplevel_by_name(), and main().
na_core_utils_slist_duplicate()
GSList * na_core_utils_slist_duplicate (GSList * slist)
na_core_utils_slist_duplicate: @slist: the #GSList to be duplicated.
Returns: a #GSList of strings.
The returned list should be na_core_utils_slist_free() by the caller.
Since: 2.30
Definition at line 352 of file na-core-utils.c.
References NULL.
Referenced by cact_add_capability_dialog_run(), and cact_add_scheme_dialog_run().
na_core_utils_slist_find_negated()
gboolean na_core_utils_slist_find_negated (GSList * list, const gchar * str)
na_core_utils_slist_find_negated: @list: the GSList of strings to be searched. @str: the searched string.
Search for a string in a string list which may contain nagated items.
Returns: TRUE if the string has been found in list.
Since: 2.30
Definition at line 673 of file na-core-utils.c.
References FALSE, na_core_utils_str_collate(), and TRUE.
na_core_utils_slist_free()
void na_core_utils_slist_free (GSList * slist)
na_core_utils_slist_free: @slist: a #GSList list of strings.
Releases the strings and the list itself.
Since: 2.30
Definition at line 738 of file na-core-utils.c.
References NULL.
Referenced by cact_menubar_edit_on_cut(), cact_menubar_edit_on_delete(), cact_menubar_file_save_items(), cact_providers_list_save(), cact_schemes_list_save_defaults(), cadp_desktop_file_get_string_list(), cadp_iio_provider_write_item(), cadp_reader_ifactory_provider_read_data(), cadp_writer_ifactory_provider_write_data(), main(), na_icontext_check_mimetypes(), na_icontext_replace_folder(), na_icontext_set_not_desktop(), na_icontext_set_only_desktop(), na_icontext_set_scheme(), na_importer_free_result(), na_io_provider_load_items(), na_iprefs_write_level_zero(), na_object_item_rebuild_children_slist(), and na_pivot_load_items().
na_core_utils_slist_from_array()
GSList * na_core_utils_slist_from_array (const gchar ** str_array)
na_core_utils_slist_from_array: @str_array: an NULL-terminated array of strings.
Returns: a #GSList list of strings, which should be na_core_utils_slist_free() by the caller.
Since: 2.30
Definition at line 442 of file na-core-utils.c.
References idx, and NULL.
Referenced by cadp_desktop_file_get_string_list(), cadp_xdg_dirs_get_system_data_dirs(), na_core_utils_slist_from_split(), and na_settings_get_groups().
na_core_utils_slist_from_split()
GSList * na_core_utils_slist_from_split (const gchar * text, const gchar * separator)
na_core_utils_slist_from_split: @text: a string to be splitted. @separator: the string to be used as the separator.
Returns: a #GSList with the list of strings after having been splitted.
The returned #GSList should be na_core_utils_slist_free() by the caller.
Since: 2.30
Definition at line 406 of file na-core-utils.c.
References na_core_utils_slist_from_array(), and NULL.
Referenced by cadp_iio_provider_write_item().
na_core_utils_slist_join_at_end()
gchar * na_core_utils_slist_join_at_end (GSList * slist, const gchar * link)
na_core_utils_slist_join_at_end: @slist: the string list to join. the string used to join each element.
Returns: a newly allocated string which should be g_free() by the caller.
Since: 2.30
Definition at line 468 of file na-core-utils.c.
References FALSE.
Referenced by cact_menubar_edit_on_cut(), cact_menubar_edit_on_delete(), and cact_menubar_file_save_items().
na_core_utils_slist_remove_ascii()
GSList * na_core_utils_slist_remove_ascii (GSList * slist, const gchar * text)
na_core_utils_slist_remove_ascii: @slist: the #GSList to be updated. @text: string to remove.
Removes a string from a GSList of strings.
Returns: the same, updated, @slist.
Since: 2.30
Definition at line 497 of file na-core-utils.c.
Referenced by na_core_utils_slist_setup_element().
na_core_utils_slist_remove_utf8()
GSList * na_core_utils_slist_remove_utf8 (GSList * slist, const gchar * text)
na_core_utils_slist_remove_utf8: @slist: the #GSList to be updated. @text: the string to be removed.
Removes from the @slist the item which has a string which is equal to @text.
Returns: the new @slist start position.
Since: 2.30
Definition at line 527 of file na-core-utils.c.
References na_core_utils_str_collate().
Referenced by na_icontext_replace_folder().
na_core_utils_slist_setup_element()
GSList * na_core_utils_slist_setup_element (GSList * list, const gchar * element, gboolean set)
na_core_utils_slist_setup_element: @list: the GSList of strings to be setup. @element: the string to add to or remove of the list. @set: whether the @element should be set or removed.
Setup the @list so that the @element is once in the @list if @set is TRUE, or not if @set is FALSE.
Returns: the updated @list.
Since: 2.30
Definition at line 616 of file na-core-utils.c.
References na_core_utils_slist_count(), na_core_utils_slist_remove_ascii(), and set.
Referenced by na_icontext_set_not_desktop(), na_icontext_set_only_desktop(), and na_icontext_set_scheme().
na_core_utils_slist_to_array()
gchar ** na_core_utils_slist_to_array (GSList * slist)
na_core_utils_slist_to_array: @slist: a list of strings.
Returns: a newly allocated array of strings, which should be g_strfreev() by the caller.
Since: 2.30
Definition at line 553 of file na-core-utils.c.
References TRUE.
Referenced by cadp_desktop_file_set_string_list().
na_core_utils_slist_to_text()
gchar * na_core_utils_slist_to_text (GSList * slist)
na_core_utils_slist_to_text: @slist: a list of strings.
Concatenates a string list to a semi-colon-separated text suitable for an entry in the user interface
Returns: a newly allocated string, which should be g_free() by the caller.
Since: 2.30
Definition at line 582 of file na-core-utils.c.
na_core_utils_str_collate()
int na_core_utils_str_collate (const gchar * str1, const gchar * str2)
na_core_utils_str_collate: @str1: an UTF-8 encoded string. @str2: an UTF-8 encoded string.
Returns: <itemizedlist> <listitem>
-1 if str1 < str2,
</listitem> <listitem>
0 if str1 = str2,
</listitem> <listitem>
+1 if str1 > str2.
</listitem> </itemizedlist>
Since: 2.30
Definition at line 157 of file na-core-utils.c.
References NULL.
Referenced by cadp_utils_gslist_remove_from(), na_core_utils_slist_count(), na_core_utils_slist_find_negated(), na_core_utils_slist_remove_utf8(), and na_object_id_sort_alpha_asc().
na_core_utils_str_remove_char()
gchar * na_core_utils_str_remove_char (const gchar * string, const gchar * to_remove)
na_core_utils_str_remove_char: @string: source string. @to_remove: the character to remove.
Returns: a newly allocated string, which is a copy of the source @string, minus all the found occurrences of the given @to_remove char.
The returned string should be g_free() by the caller.
Since: 2.30
Definition at line 190 of file na-core-utils.c.
References error, NULL, and regex.
na_core_utils_str_remove_suffix()
gchar * na_core_utils_str_remove_suffix (const gchar * string, const gchar * suffix)
na_core_utils_str_remove_suffix: @string: source string. @suffix: suffix to be removed from @string.
Returns: a newly allocated string, which is a copy of the source @string, minus the removed @suffix if present. If @strings doesn't terminate with @suffix, then the returned string is equal to source @string.
The returned string should be g_free() by the caller.
Since: 2.30
Definition at line 234 of file na-core-utils.c.
References ptr.
na_core_utils_str_split_first_word()
void na_core_utils_str_split_first_word (const gchar * string, gchar ** first, gchar ** other)
na_core_utils_str_split_first_word: @string: a space-separated string. @first: a pointer to a gchar *. @other: a pointer to a gchar *.
Split the @string string into two components: <itemizedlist> <listitem>
the first word which is allocated in @first,
</listitem> <listitem>
the rest of the string which is allocated in @other.
</listitem> </itemizedlist>
The two allocated strings should be g_free() by the caller.
Since: 2.30
Definition at line 270 of file na-core-utils.c.
References NULL.
na_core_utils_str_subst()
gchar * na_core_utils_str_subst (const gchar * pattern, const gchar * key, const gchar * subst)
na_core_utils_str_subst: @pattern: the pattern. @key: the key string to be substituted. @subst: the string which will replace @key.
Returns: a copy of @pattern where the first occurrence of @key has been substituted with @subst, as a newly allocated string which should be g_free() by the caller, or a copy of @pattern if @key is not found in @pattern.
Definition at line 309 of file na-core-utils.c.
References FALSE, and key.
Referenced by na_tokens_command_for_terminal().