MATE Desktop Environment: na-data-boxed.h File Reference
na-data-boxed.h File Reference
#include <glib-object.h>
#include "na-boxed.h"
#include "na-data-def.h"
Classes
struct NADataBoxed
struct NADataBoxedClass
Macros
#define NA_TYPE_DATA_BOXED (na_data_boxed_get_type())
#define NA_DATA_BOXED(object)
#define NA_DATA_BOXED_CLASS(klass)
#define NA_IS_DATA_BOXED(object)
#define NA_IS_DATA_BOXED_CLASS(klass)
#define NA_DATA_BOXED_GET_CLASS(object)
Typedefs
typedef struct _NADataBoxedPrivate NADataBoxedPrivate
typedef struct _NADataBoxedClassPrivate NADataBoxedClassPrivate
Functions
GType na_data_boxed_get_type (void)
NADataBoxed * na_data_boxed_new (const NADataDef *def)
const NADataDef * na_data_boxed_get_data_def (const NADataBoxed *boxed)
void na_data_boxed_set_data_def (NADataBoxed *boxed, const NADataDef *def)
GParamSpec * na_data_boxed_get_param_spec (const NADataDef *def)
gboolean na_data_boxed_is_default (const NADataBoxed *boxed)
gboolean na_data_boxed_is_valid (const NADataBoxed *boxed)
Macro Definition Documentation
NA_DATA_BOXED
#define NA_DATA_BOXED (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST(object, NA_TYPE_DATA_BOXED, NADataBoxed))
Definition at line 60 of file na-data-boxed.h.
Referenced by na_factory_object_are_equal(), na_factory_object_copy(), na_factory_object_dump(), na_factory_object_is_valid(), na_factory_object_iter_on_boxed(), and na_ifactory_object_get_data_boxed().
NA_DATA_BOXED_CLASS
#define NA_DATA_BOXED_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST(klass, NA_TYPE_DATA_BOXED, NADataBoxedClass))
Definition at line 61 of file na-data-boxed.h.
NA_DATA_BOXED_GET_CLASS
#define NA_DATA_BOXED_GET_CLASS (object)
Value:
(G_TYPE_INSTANCE_GET_CLASS((object), NA_TYPE_DATA_BOXED, NADataBoxedClass))
Definition at line 64 of file na-data-boxed.h.
NA_IS_DATA_BOXED
#define NA_IS_DATA_BOXED (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE(object, NA_TYPE_DATA_BOXED))
Definition at line 62 of file na-data-boxed.h.
Referenced by na_data_boxed_get_data_def(), na_data_boxed_is_default(), na_data_boxed_is_valid(), and na_data_boxed_set_data_def().
NA_IS_DATA_BOXED_CLASS
#define NA_IS_DATA_BOXED_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass), NA_TYPE_DATA_BOXED))
Definition at line 63 of file na-data-boxed.h.
NA_TYPE_DATA_BOXED
#define NA_TYPE_DATA_BOXED (na_data_boxed_get_type())
SECTION: data-boxed @title: NADataBoxed @short_description: The Data Factory Element Class Definition caja-actions/na-data-boxed.h
The object which encapsulates an elementary data of NAIFactoryObject. A NADataBoxed object has a type and a value.
NADataBoxed class is derived from NABoxed one, and implements the same types that those defined in na-data-types.h.
Additionally, NADataBoxed class holds the NADataDef data definition suitable for a NAFactoryObject object. It such provides default value and validity status.
Since: 2.30
Definition at line 59 of file na-data-boxed.h.
Referenced by na_data_boxed_new().
Typedef Documentation
NADataBoxedClassPrivate
typedef struct _NADataBoxedClassPrivate NADataBoxedClassPrivate
Definition at line 75 of file na-data-boxed.h.
NADataBoxedPrivate
typedef struct _NADataBoxedPrivate NADataBoxedPrivate
Definition at line 66 of file na-data-boxed.h.
Function Documentation
na_data_boxed_get_data_def()
const NADataDef * na_data_boxed_get_data_def (const NADataBoxed * boxed)
na_data_boxed_get_data_def: @boxed: this NADataBoxed object.
Returns: a pointer to the NADataDef structure attached to the object. Should never be NULL.
Since: 2.30
Definition at line 300 of file na-data-boxed.c.
References NA_IS_DATA_BOXED, NULL, and NADataBoxed::private.
Referenced by cadp_writer_ifactory_provider_write_data(), na_factory_object_are_equal(), na_factory_object_copy(), na_factory_object_dump(), na_factory_object_move_boxed(), and na_ifactory_object_get_data_boxed().
na_data_boxed_get_param_spec()
GParamSpec * na_data_boxed_get_param_spec (const NADataDef * def)
Definition at line 350 of file na-data-boxed.c.
References NULL, and NADataDef::type.
na_data_boxed_get_type()
GType na_data_boxed_get_type (void)
Definition at line 145 of file na-data-boxed.c.
na_data_boxed_is_default()
gboolean na_data_boxed_is_default (const NADataBoxed * boxed)
na_data_boxed_is_default: @boxed: this NADataBoxed object.
Returns: TRUE if the NADataBoxed holds its default value, FALSE else.
Since: 2.30
Definition at line 400 of file na-data-boxed.c.
References FALSE, NA_IS_DATA_BOXED, and NADataBoxed::private.
Referenced by cadp_writer_ifactory_provider_write_data().
na_data_boxed_is_valid()
gboolean na_data_boxed_is_valid (const NADataBoxed * boxed)
na_data_boxed_is_valid: @boxed: the NADataBoxed object whose validity is to be checked.
Returns: TRUE if the boxed is valid, FALSE else.
Since: 2.30
Definition at line 427 of file na-data-boxed.c.
References FALSE, NA_IS_DATA_BOXED, and NADataBoxed::private.
Referenced by na_factory_object_is_valid().
na_data_boxed_new()
NADataBoxed * na_data_boxed_new (const NADataDef * def)
Definition at line 276 of file na-data-boxed.c.
References NA_BOXED, na_boxed_set_type(), NA_TYPE_DATA_BOXED, NULL, NADataBoxed::private, and NADataDef::type.
Referenced by cadp_reader_ifactory_provider_read_data(), na_factory_object_copy(), na_factory_object_set_from_value(), and na_factory_object_set_from_void().
na_data_boxed_set_data_def()
void na_data_boxed_set_data_def (NADataBoxed * boxed, const NADataDef * def)
Definition at line 328 of file na-data-boxed.c.
References NA_IS_DATA_BOXED, NADataBoxed::private, and NADataDef::type.
Referenced by na_factory_object_move_boxed().