MATE Desktop Environment: na-data-boxed.c File Reference
na-data-boxed.c File Reference
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>
#include <api/na-core-utils.h>
#include <api/na-data-def.h>
#include <api/na-data-types.h>
#include <api/na-data-boxed.h>
Functions
GType na_data_boxed_get_type (void)
NADataBoxed * na_data_boxed_new (const NADataDef *def)
const NADataDef * na_data_boxed_get_data_def (const NADataBoxed *boxed)
void na_data_boxed_set_data_def (NADataBoxed *boxed, const NADataDef *new_def)
GParamSpec * na_data_boxed_get_param_spec (const NADataDef *def)
gboolean na_data_boxed_is_default (const NADataBoxed *boxed)
gboolean na_data_boxed_is_valid (const NADataBoxed *boxed)
Function Documentation
na_data_boxed_get_data_def()
const NADataDef * na_data_boxed_get_data_def (const NADataBoxed * boxed)
na_data_boxed_get_data_def: @boxed: this NADataBoxed object.
Returns: a pointer to the NADataDef structure attached to the object. Should never be NULL.
Since: 2.30
Definition at line 300 of file na-data-boxed.c.
References NA_IS_DATA_BOXED, NULL, and NADataBoxed::private.
Referenced by cadp_writer_ifactory_provider_write_data(), na_factory_object_are_equal(), na_factory_object_copy(), na_factory_object_dump(), na_factory_object_move_boxed(), and na_ifactory_object_get_data_boxed().
na_data_boxed_get_param_spec()
GParamSpec * na_data_boxed_get_param_spec (const NADataDef * def)
Definition at line 350 of file na-data-boxed.c.
References NULL, and NADataDef::type.
na_data_boxed_get_type()
GType na_data_boxed_get_type (void)
Definition at line 145 of file na-data-boxed.c.
na_data_boxed_is_default()
gboolean na_data_boxed_is_default (const NADataBoxed * boxed)
na_data_boxed_is_default: @boxed: this NADataBoxed object.
Returns: TRUE if the NADataBoxed holds its default value, FALSE else.
Since: 2.30
Definition at line 400 of file na-data-boxed.c.
References FALSE, NA_IS_DATA_BOXED, and NADataBoxed::private.
Referenced by cadp_writer_ifactory_provider_write_data().
na_data_boxed_is_valid()
gboolean na_data_boxed_is_valid (const NADataBoxed * boxed)
na_data_boxed_is_valid: @boxed: the NADataBoxed object whose validity is to be checked.
Returns: TRUE if the boxed is valid, FALSE else.
Since: 2.30
Definition at line 427 of file na-data-boxed.c.
References FALSE, NA_IS_DATA_BOXED, and NADataBoxed::private.
Referenced by na_factory_object_is_valid().
na_data_boxed_new()
NADataBoxed * na_data_boxed_new (const NADataDef * def)
Definition at line 276 of file na-data-boxed.c.
References NA_BOXED, na_boxed_set_type(), NA_TYPE_DATA_BOXED, NULL, NADataBoxed::private, and NADataDef::type.
Referenced by cadp_reader_ifactory_provider_read_data(), na_factory_object_copy(), na_factory_object_set_from_value(), and na_factory_object_set_from_void().
na_data_boxed_set_data_def()
void na_data_boxed_set_data_def (NADataBoxed * boxed, const NADataDef * new_def)
Definition at line 328 of file na-data-boxed.c.
References NA_IS_DATA_BOXED, NADataBoxed::private, and NADataDef::type.
Referenced by na_factory_object_move_boxed().