MATE Desktop Environment: na-exporter.h File Reference
na-exporter.h File Reference
#include <api/na-iexporter.h>
#include <api/na-object-api.h>
#include "na-ioption.h"
#include "na-pivot.h"
Macros
#define EXPORTER_FORMAT_ASK "Ask"
#define EXPORTER_FORMAT_NOEXPORT "NoExport"
Functions
GList * na_exporter_get_formats (const NAPivot *pivot)
void na_exporter_free_formats (GList *formats)
NAIOption * na_exporter_get_ask_option (void)
gchar * na_exporter_to_buffer (const NAPivot *pivot, const NAObjectItem *item, const gchar *format, GSList **messages)
gchar * na_exporter_to_file (const NAPivot *pivot, const NAObjectItem *item, const gchar *folder_uri, const gchar *format, GSList **messages)
NAIExporter * na_exporter_find_for_format (const NAPivot *pivot, const gchar *format)
Macro Definition Documentation
EXPORTER_FORMAT_ASK
#define EXPORTER_FORMAT_ASK "Ask"
Definition at line 46 of file na-exporter.h.
EXPORTER_FORMAT_NOEXPORT
#define EXPORTER_FORMAT_NOEXPORT "NoExport"
Definition at line 47 of file na-exporter.h.
Referenced by cact_export_ask_user().
Function Documentation
na_exporter_find_for_format()
NAIExporter * na_exporter_find_for_format (const NAPivot * pivot, const gchar * format)
na_exporter_find_for_format: @pivot: the NAPivot instance. @format: the string identifier of the searched format.
Returns: the NAIExporter instance which provides the @format export format. The returned instance is owned by @pivot, and should not be released by the caller.
Definition at line 416 of file na-exporter.c.
References NA_EXPORT_FORMAT, na_export_format_get_provider(), na_exporter_free_formats(), na_exporter_get_formats(), NA_IOPTION, na_ioption_get_id(), NA_IS_PIVOT, and NULL.
Referenced by main(), na_exporter_to_buffer(), and na_exporter_to_file().
na_exporter_free_formats()
void na_exporter_free_formats (GList * formats)
Definition at line 183 of file na-exporter.c.
References NULL.
Referenced by na_exporter_find_for_format().
na_exporter_get_ask_option()
NAIOption * na_exporter_get_ask_option (void)
Definition at line 201 of file na-exporter.c.
References NAIExporterFormatv2::description, NAIExporterFormatv2::format, NAIExporterFormatv2::label, na_export_format_new(), NA_IOPTION, NULL, NAIExporterFormatv2::pixbuf, NAIExporterFormatv2::provider, and NAIExporterFormatv2::version.
na_exporter_get_formats()
GList * na_exporter_get_formats (const NAPivot * pivot)
Definition at line 78 of file na-exporter.c.
References na_export_format_new(), NA_IEXPORTER, NA_IS_PIVOT, na_pivot_free_providers(), na_pivot_get_providers(), NA_TYPE_IEXPORTER, and NULL.
Referenced by na_exporter_find_for_format().
na_exporter_to_buffer()
gchar * na_exporter_to_buffer (const NAPivot * pivot, const NAObjectItem * item, const gchar * format, GSList ** messages)
Definition at line 262 of file na-exporter.c.
References _, NAIExporterBufferParmsv2::buffer, NAIExporterBufferParmsv2::exported, NAIExporterBufferParmsv2::format, item, NAIExporterBufferParmsv2::messages, na_exporter_find_for_format(), NA_IEXPORTER_GET_INTERFACE, NA_IS_OBJECT_ITEM, NA_IS_PIVOT, name, NO_IMPLEMENTATION_MSG, NULL, and NAIExporterBufferParmsv2::version.
na_exporter_to_file()
gchar * na_exporter_to_file (const NAPivot * pivot, const NAObjectItem * item, const gchar * folder_uri, const gchar * format, GSList ** messages)
Definition at line 334 of file na-exporter.c.
References _, NAIExporterFileParmsv2::basename, NAIExporterFileParmsv2::exported, NAIExporterFileParmsv2::folder, NAIExporterFileParmsv2::format, item, NAIExporterFileParmsv2::messages, na_exporter_find_for_format(), NA_IEXPORTER_GET_INTERFACE, NA_IS_OBJECT_ITEM, NA_IS_PIVOT, name, NO_IMPLEMENTATION_MSG, NULL, and NAIExporterFileParmsv2::version.