MATE Desktop Environment: na-ifactory-object.c File Reference
na-ifactory-object.c File Reference
#include <string.h>
#include <api/na-ifactory-object.h>
#include "na-factory-object.h"
Functions
GType na_ifactory_object_get_type (void)
: the name of the elementary data we are searching for.
na_ifactory_object_get_data_boxed: @object: a NAIFactoryObject object.
The returned NADataBoxed is owned by NAIFactoryObject @object, and should not be released by the caller.
Returns: The NADataBoxed object which contains the specified data, or NULL.
Since: 2.30
NADataBoxed * na_ifactory_object_get_data_boxed (const NAIFactoryObject *object, const gchar *name)
NADataGroup * na_ifactory_object_get_data_groups (const NAIFactoryObject *object)
: the elementary data whose value is to be got.
na_ifactory_object_get_as_void: @object: this NAIFactoryObject instance.
If the type of the value is NA_DATA_TYPE_STRING, NA_DATA_TYPE_LOCALE_STRING, or NA_DATA_TYPE_STRING_LIST, then the returned value is a newly allocated one and should be g_free() (resp. na_core_utils_slist_free()) by the caller.
Returns: the searched value.
Since: 2.30
void * na_ifactory_object_get_as_void (const NAIFactoryObject *object, const gchar *name)
: the name of the elementary data whose value is to be set.
na_ifactory_object_set_from_void: @object: this NAIFactoryObject instance.
@data: the value to set.
Set the elementary data with the given value.
Since: 2.30
void na_ifactory_object_set_from_void (NAIFactoryObject *object, const gchar *name, const void *data)
Function Documentation
na_ifactory_object_get_as_void()
void * na_ifactory_object_get_as_void (const NAIFactoryObject * object, const gchar * name)
Definition at line 219 of file na-ifactory-object.c.
References na_factory_object_get_as_void(), NA_IS_IFACTORY_OBJECT, name, and NULL.
na_ifactory_object_get_data_boxed()
NADataBoxed * na_ifactory_object_get_data_boxed (const NAIFactoryObject * object, const gchar * name)
Definition at line 156 of file na-ifactory-object.c.
References NA_DATA_BOXED, na_data_boxed_get_data_def(), NA_IFACTORY_OBJECT_PROP_DATA, NA_IS_IFACTORY_OBJECT, NADataDef::name, name, and NULL.
Referenced by na_factory_object_are_equal(), na_factory_object_copy(), na_factory_object_get_as_value(), na_factory_object_get_as_void(), na_factory_object_is_set(), na_factory_object_set_from_value(), and na_factory_object_set_from_void().
na_ifactory_object_get_data_groups()
NADataGroup * na_ifactory_object_get_data_groups (const NAIFactoryObject * object)
na_ifactory_object_get_data_groups: @object: a NAIFactoryObject object.
The returned NADataGroup is owned by the NAIFactoryObject @object, and should not be released by the caller.
Returns: The NADataGroup groups definition, or NULL.
Since: 2.30
Definition at line 189 of file na-ifactory-object.c.
References NA_IFACTORY_OBJECT_GET_INTERFACE, NA_IS_IFACTORY_OBJECT, and NULL.
na_ifactory_object_get_type()
GType na_ifactory_object_get_type (void)
Definition at line 58 of file na-ifactory-object.c.
na_ifactory_object_set_from_void()
void na_ifactory_object_set_from_void (NAIFactoryObject * object, const gchar * name, const void * data)
Definition at line 237 of file na-ifactory-object.c.
References data, na_factory_object_set_from_void(), NA_IS_IFACTORY_OBJECT, and name.