MATE Desktop Environment: na-io-provider.h File Reference
na-io-provider.h File Reference
#include "na-pivot.h"
Classes
struct NAIOProvider
struct NAIOProviderClass
Macros
#define NA_IO_PROVIDER_TYPE (na_io_provider_get_type())
#define NA_IO_PROVIDER(object)
#define NA_IO_PROVIDER_CLASS(klass)
#define NA_IS_IO_PROVIDER(object)
#define NA_IS_IO_PROVIDER_CLASS(klass)
#define NA_IO_PROVIDER_GET_CLASS(object)
#define IO_PROVIDER_SIGNAL_ITEM_CHANGED "io-provider-item-changed"
Typedefs
typedef struct _NAIOProviderPrivate NAIOProviderPrivate
typedef struct _NAIOProviderClassPrivate NAIOProviderClassPrivate
Functions
GType na_io_provider_get_type (void)
NAIOProvider * na_io_provider_find_writable_io_provider (const NAPivot *pivot)
NAIOProvider * na_io_provider_find_io_provider_by_id (const NAPivot *pivot, const gchar *id)
const GList * na_io_provider_get_io_providers_list (const NAPivot *pivot)
void na_io_provider_unref_io_providers_list (void)
gchar * na_io_provider_get_id (const NAIOProvider *provider)
gchar * na_io_provider_get_name (const NAIOProvider *provider)
gboolean na_io_provider_is_available (const NAIOProvider *provider)
gboolean na_io_provider_is_conf_readable (const NAIOProvider *provider, const NAPivot *pivot, gboolean *mandatory)
gboolean na_io_provider_is_conf_writable (const NAIOProvider *provider, const NAPivot *pivot, gboolean *mandatory)
gboolean na_io_provider_is_finally_writable (const NAIOProvider *provider, guint *reason)
GList * na_io_provider_load_items (const NAPivot *pivot, guint loadable_set, GSList **messages)
guint na_io_provider_write_item (const NAIOProvider *provider, const NAObjectItem *item, GSList **messages)
guint na_io_provider_delete_item (const NAIOProvider *provider, const NAObjectItem *item, GSList **messages)
guint na_io_provider_duplicate_data (const NAIOProvider *provider, NAObjectItem *dest, const NAObjectItem *source, GSList **messages)
gchar * na_io_provider_get_readonly_tooltip (guint reason)
gchar * na_io_provider_get_return_code_label (guint code)
Macro Definition Documentation
IO_PROVIDER_SIGNAL_ITEM_CHANGED
#define IO_PROVIDER_SIGNAL_ITEM_CHANGED "io-provider-item-changed"
Definition at line 94 of file na-io-provider.h.
Referenced by na_iio_provider_item_changed().
NA_IO_PROVIDER
#define NA_IO_PROVIDER (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST(object, NA_IO_PROVIDER_TYPE, NAIOProvider))
Definition at line 67 of file na-io-provider.h.
Referenced by na_io_provider_find_io_provider_by_id().
NA_IO_PROVIDER_CLASS
#define NA_IO_PROVIDER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST(klass, NA_IO_PROVIDER_TYPE, NAIOProviderClass))
Definition at line 68 of file na-io-provider.h.
NA_IO_PROVIDER_GET_CLASS
#define NA_IO_PROVIDER_GET_CLASS (object)
Value:
(G_TYPE_INSTANCE_GET_CLASS((object), NA_IO_PROVIDER_TYPE, NAIOProviderClass))
Definition at line 71 of file na-io-provider.h.
NA_IO_PROVIDER_TYPE
#define NA_IO_PROVIDER_TYPE (na_io_provider_get_type())
Definition at line 66 of file na-io-provider.h.
NA_IS_IO_PROVIDER
#define NA_IS_IO_PROVIDER (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE(object, NA_IO_PROVIDER_TYPE))
Definition at line 69 of file na-io-provider.h.
Referenced by na_io_provider_delete_item(), na_io_provider_duplicate_data(), na_io_provider_get_id(), na_io_provider_get_name(), na_io_provider_is_available(), na_io_provider_is_conf_readable(), na_io_provider_is_conf_writable(), na_io_provider_is_finally_writable(), na_io_provider_write_item(), and na_updater_delete_item().
NA_IS_IO_PROVIDER_CLASS
#define NA_IS_IO_PROVIDER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass), NA_IO_PROVIDER_TYPE))
Definition at line 70 of file na-io-provider.h.
Typedef Documentation
NAIOProviderClassPrivate
typedef struct _NAIOProviderClassPrivate NAIOProviderClassPrivate
Definition at line 82 of file na-io-provider.h.
NAIOProviderPrivate
typedef struct _NAIOProviderPrivate NAIOProviderPrivate
Definition at line 73 of file na-io-provider.h.
Function Documentation
na_io_provider_delete_item()
guint na_io_provider_delete_item (const NAIOProvider * provider, const NAObjectItem * item, GSList ** messages)
Definition at line 1279 of file na-io-provider.c.
References item, NA_IIO_PROVIDER_CODE_PROGRAM_ERROR, NA_IIO_PROVIDER_GET_INTERFACE, NA_IS_IIO_PROVIDER, NA_IS_IO_PROVIDER, NA_IS_OBJECT_ITEM, and NAIOProvider::private.
Referenced by na_updater_delete_item().
na_io_provider_duplicate_data()
guint na_io_provider_duplicate_data (const NAIOProvider * provider, NAObjectItem * dest, const NAObjectItem * source, GSList ** messages)
Definition at line 1313 of file na-io-provider.c.
References dest, NA_IIO_PROVIDER_CODE_PROGRAM_ERROR, NA_IIO_PROVIDER_GET_INTERFACE, NA_IS_IIO_PROVIDER, NA_IS_IO_PROVIDER, NA_IS_OBJECT_ITEM, na_object_get_provider_data, na_object_set_provider_data, NULL, and NAIOProvider::private.
na_io_provider_find_io_provider_by_id()
NAIOProvider * na_io_provider_find_io_provider_by_id (const NAPivot * pivot, const gchar * id)
Definition at line 349 of file na-io-provider.c.
References NA_IO_PROVIDER, na_io_provider_get_io_providers_list(), NULL, and NAIOProvider::private.
na_io_provider_find_writable_io_provider()
NAIOProvider * na_io_provider_find_writable_io_provider (const NAPivot * pivot)
Definition at line 320 of file na-io-provider.c.
References na_io_provider_get_io_providers_list(), NULL, and NAIOProvider::private.
Referenced by na_updater_check_item_writability_status(), and na_updater_write_item().
na_io_provider_get_id()
gchar * na_io_provider_get_id (const NAIOProvider * provider)
Definition at line 648 of file na-io-provider.c.
References NA_IS_IO_PROVIDER, NULL, and NAIOProvider::private.
na_io_provider_get_io_providers_list()
const GList * na_io_provider_get_io_providers_list (const NAPivot * pivot)
Definition at line 392 of file na-io-provider.c.
References NA_IS_PIVOT, and NULL.
Referenced by na_io_provider_find_io_provider_by_id(), and na_io_provider_find_writable_io_provider().
na_io_provider_get_name()
gchar * na_io_provider_get_name (const NAIOProvider * provider)
Definition at line 677 of file na-io-provider.c.
References NA_IIO_PROVIDER_GET_INTERFACE, na_io_provider_is_available(), NA_IS_IO_PROVIDER, name, NULL, and NAIOProvider::private.
na_io_provider_get_readonly_tooltip()
gchar * na_io_provider_get_readonly_tooltip (guint reason)
Definition at line 1351 of file na-io-provider.c.
References _, NA_IIO_PROVIDER_STATUS_INCOMPLETE_API, NA_IIO_PROVIDER_STATUS_ITEM_READONLY, NA_IIO_PROVIDER_STATUS_LOCKED_BY_ADMIN, NA_IIO_PROVIDER_STATUS_LOCKED_BY_USER, NA_IIO_PROVIDER_STATUS_NO_PROVIDER_FOUND, NA_IIO_PROVIDER_STATUS_NOT_ABLE_TO, NA_IIO_PROVIDER_STATUS_NOT_WILLING_TO, NA_IIO_PROVIDER_STATUS_UNAVAILABLE, NA_IIO_PROVIDER_STATUS_WRITABLE, and NULL.
Referenced by cact_main_statusbar_set_locked().
na_io_provider_get_return_code_label()
gchar * na_io_provider_get_return_code_label (guint code)
Definition at line 1412 of file na-io-provider.c.
References _, label, NA_IIO_PROVIDER_CODE_DELETE_CONFIG_ERROR, NA_IIO_PROVIDER_CODE_DELETE_SCHEMAS_ERROR, NA_IIO_PROVIDER_CODE_NOT_WILLING_TO_RUN, NA_IIO_PROVIDER_CODE_OK, NA_IIO_PROVIDER_CODE_PROGRAM_ERROR, NA_IIO_PROVIDER_CODE_WRITE_ERROR, and NULL.
na_io_provider_get_type()
GType na_io_provider_get_type (void)
Definition at line 106 of file na-io-provider.c.
na_io_provider_is_available()
gboolean na_io_provider_is_available (const NAIOProvider * provider)
Definition at line 714 of file na-io-provider.c.
References FALSE, NA_IS_IIO_PROVIDER, NA_IS_IO_PROVIDER, and NAIOProvider::private.
Referenced by na_io_provider_get_name().
na_io_provider_is_conf_readable()
gboolean na_io_provider_is_conf_readable (const NAIOProvider * provider, const NAPivot * pivot, gboolean * mandatory)
Definition at line 747 of file na-io-provider.c.
References FALSE, NA_IPREFS_IO_PROVIDER_GROUP, NA_IPREFS_IO_PROVIDER_READABLE, NA_IS_IO_PROVIDER, NA_IS_PIVOT, na_settings_get_boolean_ex(), NULL, and NAIOProvider::private.
na_io_provider_is_conf_writable()
gboolean na_io_provider_is_conf_writable (const NAIOProvider * provider, const NAPivot * pivot, gboolean * mandatory)
Definition at line 786 of file na-io-provider.c.
References FALSE, NA_IS_IO_PROVIDER, NA_IS_PIVOT, and NAIOProvider::private.
na_io_provider_is_finally_writable()
gboolean na_io_provider_is_finally_writable (const NAIOProvider * provider, guint * reason)
na_io_provider_is_finally_writable: @provider: this NAIOProvider. @reason: if not NULL, a pointer to a guint which will hold the reason.
Returns: the current writability status of this I/O provider.
Definition at line 811 of file na-io-provider.c.
References FALSE, NA_IIO_PROVIDER_STATUS_UNDETERMINED, NA_IS_IO_PROVIDER, and NAIOProvider::private.
Referenced by na_updater_check_item_writability_status().
na_io_provider_load_items()
GList * na_io_provider_load_items (const NAPivot * pivot, guint loadable_set, GSList ** messages)
Definition at line 850 of file na-io-provider.c.
References IPREFS_ORDER_ALPHA_ASCENDING, IPREFS_ORDER_ALPHA_DESCENDING, IPREFS_ORDER_MANUAL, na_core_utils_slist_free(), na_iprefs_get_order_mode(), NA_IPREFS_ITEMS_LEVEL_ZERO_ORDER, na_iprefs_write_level_zero(), NA_IS_PIVOT, na_object_dump_tree, na_object_id_sort_alpha_asc(), na_object_id_sort_alpha_desc(), na_settings_get_string_list(), NULL, and TRUE.
Referenced by na_pivot_load_items().
na_io_provider_unref_io_providers_list()
void na_io_provider_unref_io_providers_list (void)
Definition at line 633 of file na-io-provider.c.
References NULL.
na_io_provider_write_item()
guint na_io_provider_write_item (const NAIOProvider * provider, const NAObjectItem * item, GSList ** messages)
Definition at line 1242 of file na-io-provider.c.
References item, NA_IIO_PROVIDER_CODE_OK, NA_IIO_PROVIDER_CODE_PROGRAM_ERROR, NA_IIO_PROVIDER_GET_INTERFACE, NA_IS_IIO_PROVIDER, NA_IS_IO_PROVIDER, NA_IS_OBJECT_ITEM, na_object_set_provider, and NAIOProvider::private.
Referenced by na_updater_write_item().