MATE Desktop Environment: na-ifactory-provider.c File Reference
na-ifactory-provider.c File Reference
#include <api/na-iio-provider.h>
#include <api/na-ifactory-provider.h>
#include "na-factory-object.h"
#include "na-factory-provider.h"
Functions
GType na_ifactory_provider_get_type (void)
void na_ifactory_provider_read_item (const NAIFactoryProvider *reader, void *reader_data, NAIFactoryObject *object, GSList **messages)
guint na_ifactory_provider_write_item (const NAIFactoryProvider *writer, void *writer_data, NAIFactoryObject *object, GSList **messages)
Function Documentation
na_ifactory_provider_get_type()
GType na_ifactory_provider_get_type (void)
na_ifactory_provider_get_type:
Registers the GType of this interface.
Returns: the NAIFactoryProvider #GType.
Definition at line 67 of file na-ifactory-provider.c.
na_ifactory_provider_read_item()
void na_ifactory_provider_read_item (const NAIFactoryProvider * reader, void * reader_data, NAIFactoryObject * object, GSList ** messages)
na_ifactory_provider_read_item: @reader: the instance which implements this NAIFactoryProvider interface. @reader_data: instance data which will be provided back to the interface methods @object: the NAIFactoryObject object to be unserialilzed. @messages: a pointer to a #GSList list of strings; the implementation may append messages to this list, but shouldn't reinitialize it.
This function is to be called by a NAIIOProvider which would wish read its items. The function takes care of collecting and structuring data, while the callback interface methods NAIFactoryProviderInterface.read_start(), NAIFactoryProviderInterface.read_data() and NAIFactoryProviderInterface.read_done() just have to fill a given NADataBoxed with the ad-hoc data type.
<programlisting> &lcomment;
allocate the object to be read &rcomment; NAObjectItem *item = NA_OBJECT_ITEM(na_object_action_new()); &lcomment;
some data we may need to have access to in callback methods &rcomment; void *data; &lcomment;
now call interface function &rcomment; na_ifactory_provider_read_item(NA_IFACTORY_PROVIDER(provider), data, NA_IFACTORY_OBJECT(item), messages);
</programlisting>
Since: 2.30
Definition at line 188 of file na-ifactory-provider.c.
References na_factory_object_read_item(), NA_IS_IFACTORY_OBJECT, and NA_IS_IFACTORY_PROVIDER.
na_ifactory_provider_write_item()
guint na_ifactory_provider_write_item (const NAIFactoryProvider * writer, void * writer_data, NAIFactoryObject * object, GSList ** messages)
na_ifactory_provider_write_item: @writer: the instance which implements this NAIFactoryProvider interface. @writer_data: instance data. @object: the NAIFactoryObject derived object to be serialized. @messages: a pointer to a #GSList list of strings; the implementation may append messages to this list, but shouldn't reinitialize it.
This function is to be called by a NAIIOProvider which would wish write an item. The function takes care of collecting and writing elementary data.
Returns: a NAIIOProvider operation return code.
Since: 2.30
Definition at line 214 of file na-ifactory-provider.c.
References na_factory_object_write_item(), NA_IIO_PROVIDER_CODE_OK, NA_IIO_PROVIDER_CODE_PROGRAM_ERROR, NA_IS_IFACTORY_OBJECT, and NA_IS_IFACTORY_PROVIDER.
Referenced by cadp_writer_iexporter_export_to_buffer(), and cadp_writer_iexporter_export_to_file().