MATE Desktop Environment: na-object-profile.h File Reference
na-object-profile.h File Reference
#include "na-object-id.h"
Classes
struct NAObjectProfile
struct NAObjectProfileClass
Macros
#define NA_TYPE_OBJECT_PROFILE (na_object_profile_get_type())
#define NA_OBJECT_PROFILE(object)
#define NA_OBJECT_PROFILE_CLASS(klass)
#define NA_IS_OBJECT_PROFILE(object)
#define NA_IS_OBJECT_PROFILE_CLASS(klass)
#define NA_OBJECT_PROFILE_GET_CLASS(object)
Typedefs
typedef struct _NAObjectProfilePrivate NAObjectProfilePrivate
typedef struct _NAObjectProfileClassPrivate NAObjectProfileClassPrivate
Enumerations
enum { NA_EXECUTION_MODE_NORMAL = 1 , NA_EXECUTION_MODE_TERMINAL , NA_EXECUTION_MODE_EMBEDDED , NA_EXECUTION_MODE_DISPLAY_OUTPUT }
Functions
GType na_object_profile_get_type (void)
NAObjectProfile * na_object_profile_new (void)
NAObjectProfile * na_object_profile_new_with_defaults (void)
void na_object_profile_convert_v2_to_last (NAObjectProfile *profile)
Macro Definition Documentation
NA_IS_OBJECT_PROFILE
#define NA_IS_OBJECT_PROFILE (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE(object, NA_TYPE_OBJECT_PROFILE))
Definition at line 47 of file na-object-profile.h.
Referenced by cact_menubar_edit_on_duplicate(), cact_tree_ieditable_insert_items(), cact_tree_model_dnd_imulti_drag_source_row_draggable(), cadp_reader_ifactory_provider_read_data(), cadp_reader_ifactory_provider_read_start(), cadp_writer_ifactory_provider_write_data(), na_object_action_attach_profile(), na_object_id_prepare_for_paste(), na_object_profile_convert_v2_to_last(), and na_updater_should_pasted_be_relabeled().
NA_IS_OBJECT_PROFILE_CLASS
#define NA_IS_OBJECT_PROFILE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass), NA_TYPE_OBJECT_PROFILE))
Definition at line 48 of file na-object-profile.h.
NA_OBJECT_PROFILE
#define NA_OBJECT_PROFILE (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST(object, NA_TYPE_OBJECT_PROFILE, NAObjectProfile))
Definition at line 45 of file na-object-profile.h.
Referenced by cadp_reader_ifactory_provider_read_start().
NA_OBJECT_PROFILE_CLASS
#define NA_OBJECT_PROFILE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST(klass, NA_TYPE_OBJECT_PROFILE, NAObjectProfileClass))
Definition at line 46 of file na-object-profile.h.
NA_OBJECT_PROFILE_GET_CLASS
#define NA_OBJECT_PROFILE_GET_CLASS (object)
Value:
(G_TYPE_INSTANCE_GET_CLASS((object), NA_TYPE_OBJECT_PROFILE, NAObjectProfileClass))
Definition at line 49 of file na-object-profile.h.
NA_TYPE_OBJECT_PROFILE
#define NA_TYPE_OBJECT_PROFILE (na_object_profile_get_type())
SECTION: object-profile @title: NAObjectProfile @short_description: The Action Profile Class Definition caja-actions/na-object-item.h
Definition at line 44 of file na-object-profile.h.
Referenced by na_object_profile_new().
Typedef Documentation
NAObjectProfileClassPrivate
typedef struct _NAObjectProfileClassPrivate NAObjectProfileClassPrivate
Definition at line 60 of file na-object-profile.h.
NAObjectProfilePrivate
typedef struct _NAObjectProfilePrivate NAObjectProfilePrivate
Definition at line 51 of file na-object-profile.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NA_EXECUTION_MODE_NORMAL
NA_EXECUTION_MODE_TERMINAL
NA_EXECUTION_MODE_EMBEDDED
NA_EXECUTION_MODE_DISPLAY_OUTPUT
Definition at line 69 of file na-object-profile.h.
Function Documentation
na_object_profile_convert_v2_to_last()
void na_object_profile_convert_v2_to_last (NAObjectProfile * profile)
na_object_profile_convert_v2_to_last: @profile: the NAObjectProfile profile to be converted.
Converts a v2 profile to the last version, setting the defaults as needed.
This is called after having converted a pre-v2 action on the newly created profile, or just after having read a v2 profile. In all situations, defaults are supposed to have been set.
Since: 2.30
Definition at line 786 of file na-object-profile.c.
References action, NA_IS_OBJECT_PROFILE, NA_OBJECT_ACTION, na_object_get_iversion, na_object_get_parent, and na_object_set_iversion.
na_object_profile_get_type()
GType na_object_profile_get_type (void)
Definition at line 101 of file na-object-profile.c.
na_object_profile_new()
NAObjectProfile * na_object_profile_new (void)
na_object_profile_new:
Allocates a new profile.
Returns: the newly allocated NAObjectProfile profile.
Since: 2.30
Definition at line 743 of file na-object-profile.c.
References NA_TYPE_OBJECT_PROFILE, and NULL.
Referenced by na_object_action_new_with_profile(), and na_object_profile_new_with_defaults().
na_object_profile_new_with_defaults()
NAObjectProfile * na_object_profile_new_with_defaults (void)
na_object_profile_new_with_defaults:
Allocates a new profile, and set default values.
Returns: the newly allocated NAObjectProfile profile.
Since: 2.30
Definition at line 762 of file na-object-profile.c.
References _, na_factory_object_set_defaults(), NA_IFACTORY_OBJECT, na_object_profile_new(), na_object_set_id, and na_object_set_label.
Referenced by cact_menubar_file_on_new_profile(), and na_object_action_new_with_defaults().