MATE Desktop Environment: na-object-menu.c File Reference
na-object-menu.c File Reference
#include <glib/gi18n.h>
#include <string.h>
#include <api/na-iio-provider.h>
#include <api/na-ifactory-object.h>
#include <api/na-object-api.h>
#include "na-factory-provider.h"
#include "na-factory-object.h"
Macros
#define NEW_CAJA_MENU N_("New Caja menu")
Functions
GType na_object_menu_get_type (void)
NAObjectMenu * na_object_menu_new (void)
NAObjectMenu * na_object_menu_new_with_defaults (void)
Variables
NADataGroup menu_data_groups []
Macro Definition Documentation
NEW_CAJA_MENU
#define NEW_CAJA_MENU N_("New Caja menu")
Definition at line 57 of file na-object-menu.c.
Referenced by na_object_menu_new_with_defaults().
Function Documentation
na_object_menu_get_type()
GType na_object_menu_get_type (void)
Definition at line 84 of file na-object-menu.c.
na_object_menu_new()
NAObjectMenu * na_object_menu_new (void)
na_object_menu_new:
Allocates a new NAObjectMenu object.
Returns: the newly allocated NAObjectMenu object.
Since: 2.30
Definition at line 350 of file na-object-menu.c.
References NA_TYPE_OBJECT_MENU, and NULL.
Referenced by na_object_menu_new_with_defaults().
na_object_menu_new_with_defaults()
NAObjectMenu * na_object_menu_new_with_defaults (void)
na_object_menu_new_with_defaults:
Allocates a new NAObjectMenu object, and setup default values.
Returns: the newly allocated NAObjectMenu object.
Since: 2.30
Definition at line 369 of file na-object-menu.c.
References na_factory_object_set_defaults(), NA_IFACTORY_OBJECT, na_object_menu_new(), na_object_set_label, na_object_set_new_id, NEW_CAJA_MENU, and NULL.
Referenced by cact_menubar_file_on_new_menu().
Variable Documentation
menu_data_groups
NADataGroup menu_data_groups[] extern
Definition at line 51 of file na-object-menu-factory.c.