MATE Desktop Environment: na-object-id.h File Reference
na-object-id.h File Reference
#include "na-object.h"
Classes
struct NAObjectId
struct NAObjectIdClass
Macros
#define NA_TYPE_OBJECT_ID (na_object_id_get_type())
#define NA_OBJECT_ID(object)
#define NA_OBJECT_ID_CLASS(klass)
#define NA_IS_OBJECT_ID(object)
#define NA_IS_OBJECT_ID_CLASS(klass)
#define NA_OBJECT_ID_GET_CLASS(object)
Typedefs
typedef struct _NAObjectIdPrivate NAObjectIdPrivate
typedef struct _NAObjectIdClassPrivate NAObjectIdClassPrivate
Functions
GType na_object_id_get_type (void)
gint na_object_id_sort_alpha_asc (const NAObjectId *a, const NAObjectId *b)
gint na_object_id_sort_alpha_desc (const NAObjectId *a, const NAObjectId *b)
void na_object_id_prepare_for_paste (NAObjectId *object, gboolean relabel, gboolean renumber, NAObjectId *parent)
void na_object_id_set_copy_of_label (NAObjectId *object)
void na_object_id_set_new_id (NAObjectId *object, const NAObjectId *new_parent)
Macro Definition Documentation
NA_IS_OBJECT_ID
#define NA_IS_OBJECT_ID (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE(object, NA_TYPE_OBJECT_ID))
Definition at line 51 of file na-object-id.h.
Referenced by na_object_id_prepare_for_paste(), na_object_id_set_copy_of_label(), na_object_id_set_new_id(), na_object_item_append_item(), na_object_item_get_position(), na_object_item_insert_at(), na_object_item_insert_item(), and na_object_item_remove_item().
NA_IS_OBJECT_ID_CLASS
#define NA_IS_OBJECT_ID_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass), NA_TYPE_OBJECT_ID))
Definition at line 52 of file na-object-id.h.
NA_OBJECT_ID
#define NA_OBJECT_ID (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST(object, NA_TYPE_OBJECT_ID, NAObjectId))
Definition at line 49 of file na-object-id.h.
Referenced by na_object_item_get_item().
NA_OBJECT_ID_CLASS
#define NA_OBJECT_ID_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST(klass, NA_TYPE_OBJECT_ID, NAObjectIdClass))
Definition at line 50 of file na-object-id.h.
NA_OBJECT_ID_GET_CLASS
#define NA_OBJECT_ID_GET_CLASS (object)
Value:
(G_TYPE_INSTANCE_GET_CLASS((object), NA_TYPE_OBJECT_ID, NAObjectIdClass))
Definition at line 53 of file na-object-id.h.
NA_TYPE_OBJECT_ID
#define NA_TYPE_OBJECT_ID (na_object_id_get_type())
SECTION: object-id @title: NAObjectId @short_description: The Identified Object Base Class Definition caja-actions/na-object-id.h
This is a pure virtual class, i.e. not an instantiatable one. It serves as the base class for NAObject -derived object which have a unique Id, i.e. for NAObjectItem and NAObjectProfile.
Definition at line 48 of file na-object-id.h.
Typedef Documentation
NAObjectIdClassPrivate
typedef struct _NAObjectIdClassPrivate NAObjectIdClassPrivate
Definition at line 64 of file na-object-id.h.
NAObjectIdPrivate
typedef struct _NAObjectIdPrivate NAObjectIdPrivate
Definition at line 55 of file na-object-id.h.
Function Documentation
na_object_id_get_type()
GType na_object_id_get_type (void)
Definition at line 62 of file na-object-id.c.
na_object_id_prepare_for_paste()
void na_object_id_prepare_for_paste (NAObjectId * object, gboolean relabel, gboolean renumber, NAObjectId * parent)
na_object_id_prepare_for_paste: @object: the NAObjectId object to be pasted. @relabel: whether this object should be relabeled when pasted. @renumber: whether this item should be renumbered ? @parent: the parent of @object, or NULL.
Prepares @object to be pasted.
If a NAObjectProfile, then @object is attached to the specified NAObjectAction @action. The identifier is always renumbered to be suitable with the already existing profiles.
If a NAObjectAction or a NAObjectMenu, a new identifier is allocated if and only if @relabel is TRUE.
Actual relabeling takes place if @relabel is TRUE, depending of the user preferences.
Since: 2.30
Definition at line 269 of file na-object-id.c.
References FALSE, NA_IS_OBJECT_ID, NA_IS_OBJECT_ITEM, NA_IS_OBJECT_MENU, NA_IS_OBJECT_PROFILE, na_object_get_items, na_object_prepare_for_paste, na_object_set_copy_of_label, na_object_set_new_id, na_object_set_parent, na_object_set_provider, na_object_set_provider_data, na_object_set_readonly, NULL, and NAObjectId::private.
na_object_id_set_copy_of_label()
void na_object_id_set_copy_of_label (NAObjectId * object)
na_object_id_set_copy_of_label: @object: the NAObjectId object whose label is to be changed.
Sets the 'Copy of' label.
Since: 2.30
Definition at line 318 of file na-object-id.c.
References _, label, NA_IS_OBJECT_ID, na_object_get_label, na_object_set_label, and NAObjectId::private.
na_object_id_set_new_id()
void na_object_id_set_new_id (NAObjectId * object, const NAObjectId * new_parent)
na_object_id_set_new_id: @object: the NAObjectId object whose internal identifier is to be set. @new_parent: if @object is a NAObjectProfile, then @new_parent should be set to the NAObjectAction new parent. Else, it would not be possible to allocate a new profile id compatible with already existing ones.
Request a new id to the derived class, and set it.
Since: 2.30
Definition at line 352 of file na-object-id.c.
References NA_IS_OBJECT_ID, NA_IS_OBJECT_ITEM, na_object_set_id, and NAObjectId::private.
na_object_id_sort_alpha_asc()
gint na_object_id_sort_alpha_asc (const NAObjectId * a, const NAObjectId * b)
na_object_id_sort_alpha_asc: : first NAObjectId. : second NAObjectId.
Sort the objects in alphabetical ascending order of their label.
Returns:
<itemizedlist> <listitem>
-1 if must be sorted before ,
</listitem> <listitem>
0 if and are equal from the local point of view,
</listitem> <listitem>
1 if must be sorted after .
</listitem> </itemizedlist>
Since: 2.30
Definition at line 202 of file na-object-id.c.
References b, compare, na_core_utils_str_collate(), and na_object_get_label.
Referenced by na_io_provider_load_items(), and na_object_id_sort_alpha_desc().
na_object_id_sort_alpha_desc()
gint na_object_id_sort_alpha_desc (const NAObjectId * a, const NAObjectId * b)
na_object_id_sort_alpha_desc: : first NAObjectId. : second NAObjectId.
Sort the objects in alphabetical descending order of their label.
Returns:
<itemizedlist> <listitem>
-1 if must be sorted before ,
</listitem> <listitem>
0 if and are equal from the local point of view,
</listitem> <listitem>
1 if must be sorted after .
</listitem> </itemizedlist>
Since: 2.30
Definition at line 242 of file na-object-id.c.
References b, and na_object_id_sort_alpha_asc().
Referenced by na_io_provider_load_items().