MATE Desktop Environment: na-object-profile.c File Reference
na-object-profile.c File Reference
#include <glib/gi18n.h>
#include <string.h>
#include <libcaja-extension/caja-file-info.h>
#include <api/na-core-utils.h>
#include <api/na-iio-provider.h>
#include <api/na-ifactory-object.h>
#include <api/na-object-api.h>
#include "na-factory-provider.h"
#include "na-factory-object.h"
#include "na-selected-info.h"
Macros
#define PROFILE_NAME_PREFIX "profile-"
#define na_object_is_file(obj)
#define na_object_is_dir(obj)
#define na_object_is_multiple(obj)
Functions
GType na_object_profile_get_type (void)
NAObjectProfile * na_object_profile_new (void)
NAObjectProfile * na_object_profile_new_with_defaults (void)
void na_object_profile_convert_v2_to_last (NAObjectProfile *profile)
Variables
NADataGroup profile_data_groups []
Macro Definition Documentation
na_object_is_dir
#define na_object_is_dir (obj)
Value:
((gboolean) GPOINTER_TO_UINT(na_ifactory_object_get_as_void(NA_IFACTORY_OBJECT(obj), NAFO_DATA_ISDIR)))
Definition at line 63 of file na-object-profile.c.
na_object_is_file
#define na_object_is_file (obj)
Value:
((gboolean) GPOINTER_TO_UINT(na_ifactory_object_get_as_void(NA_IFACTORY_OBJECT(obj), NAFO_DATA_ISFILE)))
Definition at line 62 of file na-object-profile.c.
na_object_is_multiple
#define na_object_is_multiple (obj)
Value:
((gboolean) GPOINTER_TO_UINT(na_ifactory_object_get_as_void(NA_IFACTORY_OBJECT(obj), NAFO_DATA_MULTIPLE)))
Definition at line 64 of file na-object-profile.c.
PROFILE_NAME_PREFIX
#define PROFILE_NAME_PREFIX "profile-"
Definition at line 60 of file na-object-profile.c.
Function Documentation
na_object_profile_convert_v2_to_last()
void na_object_profile_convert_v2_to_last (NAObjectProfile * profile)
na_object_profile_convert_v2_to_last: @profile: the NAObjectProfile profile to be converted.
Converts a v2 profile to the last version, setting the defaults as needed.
This is called after having converted a pre-v2 action on the newly created profile, or just after having read a v2 profile. In all situations, defaults are supposed to have been set.
Since: 2.30
Definition at line 786 of file na-object-profile.c.
References action, NA_IS_OBJECT_PROFILE, NA_OBJECT_ACTION, na_object_get_iversion, na_object_get_parent, and na_object_set_iversion.
na_object_profile_get_type()
GType na_object_profile_get_type (void)
Definition at line 101 of file na-object-profile.c.
na_object_profile_new()
NAObjectProfile * na_object_profile_new (void)
na_object_profile_new:
Allocates a new profile.
Returns: the newly allocated NAObjectProfile profile.
Since: 2.30
Definition at line 743 of file na-object-profile.c.
References NA_TYPE_OBJECT_PROFILE, and NULL.
Referenced by na_object_action_new_with_profile(), and na_object_profile_new_with_defaults().
na_object_profile_new_with_defaults()
NAObjectProfile * na_object_profile_new_with_defaults (void)
na_object_profile_new_with_defaults:
Allocates a new profile, and set default values.
Returns: the newly allocated NAObjectProfile profile.
Since: 2.30
Definition at line 762 of file na-object-profile.c.
References _, na_factory_object_set_defaults(), NA_IFACTORY_OBJECT, na_object_profile_new(), na_object_set_id, and na_object_set_label.
Referenced by cact_menubar_file_on_new_profile(), and na_object_action_new_with_defaults().
Variable Documentation
profile_data_groups
NADataGroup profile_data_groups[] extern
Definition at line 314 of file na-object-profile-factory.c.