MATE Desktop Environment: na-object-action.h File Reference
na-object-action.h File Reference
#include "na-object-item.h"
#include "na-object-profile.h"
Classes
struct NAObjectAction
struct NAObjectActionClass
Macros
#define NA_TYPE_OBJECT_ACTION (na_object_action_get_type())
#define NA_OBJECT_ACTION(object)
#define NA_OBJECT_ACTION_CLASS(klass)
#define NA_IS_OBJECT_ACTION(object)
#define NA_IS_OBJECT_ACTION_CLASS(klass)
#define NA_OBJECT_ACTION_GET_CLASS(object)
Typedefs
typedef struct _NAObjectActionPrivate NAObjectActionPrivate
typedef struct _NAObjectActionClassPrivate NAObjectActionClassPrivate
Functions
GType na_object_action_get_type (void)
NAObjectAction * na_object_action_new (void)
NAObjectAction * na_object_action_new_with_profile (void)
NAObjectAction * na_object_action_new_with_defaults (void)
gchar * na_object_action_get_new_profile_name (const NAObjectAction *action)
void na_object_action_attach_profile (NAObjectAction *action, NAObjectProfile *profile)
void na_object_action_set_last_version (NAObjectAction *action)
Macro Definition Documentation
NA_IS_OBJECT_ACTION
#define NA_IS_OBJECT_ACTION (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE(object, NA_TYPE_OBJECT_ACTION))
Definition at line 63 of file na-object-action.h.
Referenced by cact_menubar_edit_on_update_sensitivities(), cact_tree_ieditable_insert_items(), cact_tree_ieditable_set_items(), cadp_reader_ifactory_provider_read_done(), na_object_action_attach_profile(), na_object_action_get_new_profile_name(), na_object_action_set_last_version(), and na_updater_should_pasted_be_relabeled().
NA_IS_OBJECT_ACTION_CLASS
#define NA_IS_OBJECT_ACTION_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass), NA_TYPE_OBJECT_ACTION))
Definition at line 64 of file na-object-action.h.
NA_OBJECT_ACTION
#define NA_OBJECT_ACTION (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST(object, NA_TYPE_OBJECT_ACTION, NAObjectAction))
Definition at line 61 of file na-object-action.h.
Referenced by cact_menubar_edit_on_duplicate(), cadp_reader_ifactory_provider_read_done(), and na_object_profile_convert_v2_to_last().
NA_OBJECT_ACTION_CLASS
#define NA_OBJECT_ACTION_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST(klass, NA_TYPE_OBJECT_ACTION, NAObjectActionClass))
Definition at line 62 of file na-object-action.h.
NA_OBJECT_ACTION_GET_CLASS
#define NA_OBJECT_ACTION_GET_CLASS (object)
Value:
(G_TYPE_INSTANCE_GET_CLASS((object), NA_TYPE_OBJECT_ACTION, NAObjectActionClass))
Definition at line 65 of file na-object-action.h.
NA_TYPE_OBJECT_ACTION
#define NA_TYPE_OBJECT_ACTION (na_object_action_get_type())
SECTION: object-action @title: NAObjectAction @short_description: The Action Class Definition caja-actions/na-object-action.h
This is the class which maintains data and properties of a &prodname; action.
<note> <formalpara> <title>Edition status</title>
As a particular rule for a NAObjectItem -derived class, a NAObjectAction is considered modified as soon as any of its profiles has been modified itself (because they are saved as a whole).
</formalpara> </note>
Definition at line 60 of file na-object-action.h.
Referenced by na_object_action_new().
Typedef Documentation
NAObjectActionClassPrivate
typedef struct _NAObjectActionClassPrivate NAObjectActionClassPrivate
Definition at line 76 of file na-object-action.h.
NAObjectActionPrivate
typedef struct _NAObjectActionPrivate NAObjectActionPrivate
Definition at line 67 of file na-object-action.h.
Function Documentation
na_object_action_attach_profile()
void na_object_action_attach_profile (NAObjectAction * action, NAObjectProfile * profile)
na_object_action_attach_profile: @action: the NAObjectAction action to which the profile will be attached. @profile: the NAObjectProfile profile to be attached to @action.
Adds a profile at the end of the list of profiles.
Since: 2.30
Definition at line 727 of file na-object-action.c.
References action, NA_IS_OBJECT_ACTION, NA_IS_OBJECT_PROFILE, na_object_append_item, and na_object_set_parent.
na_object_action_get_new_profile_name()
gchar * na_object_action_get_new_profile_name (const NAObjectAction * action)
na_object_action_get_new_profile_name: @action: the NAObjectAction object which will receive a new profile.
Returns a name suitable as a new profile name.
The search is made by iterating over the standard profile name prefix : basically, we increment a counter until finding a name which is not yet allocated. The provided name is so only suitable for the specified @action.
When inserting a list of profiles in the action, we iter first for new names, before actually do the insertion. We so keep the last allocated name to avoid to allocate the same one twice.
Returns: a newly allocated profile name, which should be g_free() by the caller.
Since: 2.30
Definition at line 684 of file na-object-action.c.
References action, FALSE, NA_IS_OBJECT_ACTION, na_object_get_item, na_object_get_last_allocated, na_object_set_last_allocated, NULL, ok, and TRUE.
na_object_action_get_type()
GType na_object_action_get_type (void)
Definition at line 96 of file na-object-action.c.
na_object_action_new()
NAObjectAction * na_object_action_new (void)
na_object_action_new:
Allocates a new NAObjectAction object.
The new NAObjectAction object is initialized with suitable default values, but without any profile.
Returns: the newly allocated NAObjectAction object.
Since: 2.30
Definition at line 604 of file na-object-action.c.
References action, NA_TYPE_OBJECT_ACTION, and NULL.
Referenced by na_object_action_new_with_defaults(), and na_object_action_new_with_profile().
na_object_action_new_with_defaults()
NAObjectAction * na_object_action_new_with_defaults (void)
na_object_action_new_with_defaults:
Allocates a new NAObjectAction object along with a default profile. These two objects have suitable default values.
Returns: the newly allocated NAObjectAction action.
Since: 2.30
Definition at line 646 of file na-object-action.c.
References action, na_factory_object_set_defaults(), NA_IFACTORY_OBJECT, na_object_action_new(), na_object_attach_profile, na_object_profile_new_with_defaults(), na_object_set_label, na_object_set_new_id, na_object_set_toolbar_label, NEW_CAJA_ACTION, and NULL.
Referenced by cact_menubar_file_on_new_action().
na_object_action_new_with_profile()
NAObjectAction * na_object_action_new_with_profile (void)
na_object_action_new_with_profile:
Allocates a new NAObjectAction object along with a default profile.
Returns: the newly allocated NAObjectAction action.
Since: 2.30
Definition at line 623 of file na-object-action.c.
References action, na_object_action_new(), na_object_attach_profile, and na_object_profile_new().
na_object_action_set_last_version()
void na_object_action_set_last_version (NAObjectAction * action)
na_object_action_set_last_version: @action: the NAObjectAction action to update.
Set the version number of the @action to the last one.
Since: 2.30
Definition at line 748 of file na-object-action.c.
References action, NA_IS_OBJECT_ACTION, and na_object_set_version.