MATE Desktop Environment: na-pivot.h File Reference
na-pivot.h File Reference
#include <api/na-iio-provider.h>
#include <api/na-object-api.h>
#include "na-settings.h"
Classes
struct NAPivot
struct NAPivotClass
Macros
#define NA_TYPE_PIVOT (na_pivot_get_type())
#define NA_PIVOT(object)
#define NA_PIVOT_CLASS(klass)
#define NA_IS_PIVOT(object)
#define NA_IS_PIVOT_CLASS(klass)
#define NA_PIVOT_GET_CLASS(object)
#define PIVOT_PROP_LOADABLE "pivot-prop-loadable"
#define PIVOT_PROP_TREE "pivot-prop-tree"
#define PIVOT_SIGNAL_ITEMS_CHANGED "pivot-items-changed"
Typedefs
typedef struct _NAPivotPrivate NAPivotPrivate
typedef struct _NAPivotClassPrivate NAPivotClassPrivate
Enumerations
enum NAPivotLoadableSet { PIVOT_LOAD_NONE = 0 , PIVOT_LOAD_DISABLED = 1 << 0 , PIVOT_LOAD_INVALID = 1 << 1 , PIVOT_LOAD_ALL = 0xff }
Functions
GType na_pivot_get_type (void)
NAPivot * na_pivot_new (void)
void na_pivot_dump (const NAPivot *pivot)
GList * na_pivot_get_providers (const NAPivot *pivot, GType type)
void na_pivot_free_providers (GList *providers)
NAObjectItem * na_pivot_get_item (const NAPivot *pivot, const gchar *id)
GList * na_pivot_get_items (const NAPivot *pivot)
void na_pivot_load_items (NAPivot *pivot)
void na_pivot_set_new_items (NAPivot *pivot, GList *tree)
void na_pivot_on_item_changed_handler (NAIIOProvider *provider, NAPivot *pivot)
void na_pivot_set_loadable (NAPivot *pivot, guint loadable)
Macro Definition Documentation
NA_IS_PIVOT
#define NA_IS_PIVOT (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE(object, NA_TYPE_PIVOT))
Definition at line 85 of file na-pivot.h.
Referenced by na_exporter_find_for_format(), na_exporter_get_formats(), na_exporter_to_buffer(), na_exporter_to_file(), na_importer_import_from_uris(), na_io_provider_get_io_providers_list(), na_io_provider_is_conf_readable(), na_io_provider_is_conf_writable(), na_io_provider_load_items(), na_pivot_get_item(), na_pivot_get_items(), na_pivot_get_providers(), na_pivot_load_items(), na_pivot_on_item_changed_handler(), na_pivot_set_loadable(), na_pivot_set_new_items(), and na_updater_remove_item().
NA_IS_PIVOT_CLASS
#define NA_IS_PIVOT_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass), NA_TYPE_PIVOT))
Definition at line 86 of file na-pivot.h.
NA_PIVOT
#define NA_PIVOT (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST(object, NA_TYPE_PIVOT, NAPivot))
Definition at line 83 of file na-pivot.h.
Referenced by cact_menubar_file_save_items(), na_updater_check_item_writability_status(), na_updater_insert_item(), na_updater_load_items(), and na_updater_write_item().
NA_PIVOT_CLASS
#define NA_PIVOT_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST(klass, NA_TYPE_PIVOT, NAPivotClass))
Definition at line 84 of file na-pivot.h.
NA_PIVOT_GET_CLASS
#define NA_PIVOT_GET_CLASS (object)
Value:
(G_TYPE_INSTANCE_GET_CLASS((object), NA_TYPE_PIVOT, NAPivotClass))
Definition at line 87 of file na-pivot.h.
NA_TYPE_PIVOT
#define NA_TYPE_PIVOT (na_pivot_get_type())
Definition at line 82 of file na-pivot.h.
Referenced by na_pivot_new().
PIVOT_PROP_LOADABLE
#define PIVOT_PROP_LOADABLE "pivot-prop-loadable"
Definition at line 111 of file na-pivot.h.
PIVOT_PROP_TREE
#define PIVOT_PROP_TREE "pivot-prop-tree"
Definition at line 112 of file na-pivot.h.
Referenced by na_updater_append_item(), na_updater_insert_item(), and na_updater_remove_item().
PIVOT_SIGNAL_ITEMS_CHANGED
#define PIVOT_SIGNAL_ITEMS_CHANGED "pivot-items-changed"
Definition at line 123 of file na-pivot.h.
Referenced by cact_main_window_block_reload().
Typedef Documentation
NAPivotClassPrivate
typedef struct _NAPivotClassPrivate NAPivotClassPrivate
Definition at line 98 of file na-pivot.h.
NAPivotPrivate
typedef struct _NAPivotPrivate NAPivotPrivate
Definition at line 89 of file na-pivot.h.
Enumeration Type Documentation
NAPivotLoadableSet
enum NAPivotLoadableSet
Enumerator
PIVOT_LOAD_NONE
PIVOT_LOAD_DISABLED
PIVOT_LOAD_INVALID
PIVOT_LOAD_ALL
Definition at line 129 of file na-pivot.h.
Function Documentation
na_pivot_dump()
void na_pivot_dump (const NAPivot * pivot)
Definition at line 405 of file na-pivot.c.
na_pivot_free_providers()
void na_pivot_free_providers (GList * providers)
Definition at line 463 of file na-pivot.c.
References na_module_free_extensions_list().
Referenced by na_exporter_get_formats(), and na_importer_import_from_uris().
na_pivot_get_item()
NAObjectItem * na_pivot_get_item (const NAPivot * pivot, const gchar * id)
Definition at line 486 of file na-pivot.c.
References NA_IS_PIVOT, and NULL.
Referenced by na_updater_insert_item().
na_pivot_get_items()
GList * na_pivot_get_items (const NAPivot * pivot)
Definition at line 537 of file na-pivot.c.
References NA_IS_PIVOT, and NULL.
Referenced by na_updater_load_items().
na_pivot_get_providers()
GList * na_pivot_get_providers (const NAPivot * pivot, GType type)
Definition at line 438 of file na-pivot.c.
References NA_IS_PIVOT, na_module_get_extensions_for_type(), and NULL.
Referenced by na_exporter_get_formats(), and na_importer_import_from_uris().
na_pivot_get_type()
GType na_pivot_get_type (void)
Definition at line 107 of file na-pivot.c.
na_pivot_load_items()
void na_pivot_load_items (NAPivot * pivot)
Definition at line 560 of file na-pivot.c.
References na_core_utils_slist_free(), na_io_provider_load_items(), NA_IS_PIVOT, na_object_free_items, and NULL.
Referenced by main(), and na_updater_load_items().
na_pivot_new()
NAPivot * na_pivot_new (void)
Definition at line 386 of file na-pivot.c.
References NA_TYPE_PIVOT, and NULL.
Referenced by main().
na_pivot_on_item_changed_handler()
void na_pivot_on_item_changed_handler (NAIIOProvider * provider, NAPivot * pivot)
Definition at line 624 of file na-pivot.c.
References NA_IS_IIO_PROVIDER, NA_IS_PIVOT, and na_timeout_event().
na_pivot_set_loadable()
void na_pivot_set_loadable (NAPivot * pivot, guint loadable)
Definition at line 663 of file na-pivot.c.
References NA_IS_PIVOT.
Referenced by main().
na_pivot_set_new_items()
void na_pivot_set_new_items (NAPivot * pivot, GList * tree)
Definition at line 592 of file na-pivot.c.
References NA_IS_PIVOT, and na_object_free_items.
Referenced by cact_menubar_file_save_items().