MATE Desktop Environment: na-settings.h File Reference
na-settings.h File Reference
#include <glib-object.h>
Macros
#define NA_IPREFS_IO_PROVIDERS_READ_STATUS "io-providers-read-status-composite-key"
#define NA_IPREFS_ADMIN_PREFERENCES_LOCKED "preferences-locked"
#define NA_IPREFS_ADMIN_IO_PROVIDERS_LOCKED "io-providers-locked"
#define NA_IPREFS_ASSISTANT_ESC_CONFIRM "assistant-esc-confirm"
#define NA_IPREFS_ASSISTANT_ESC_QUIT "assistant-esc-quit"
#define NA_IPREFS_CAPABILITY_ADD_CAPABILITY_WSP "capability-add-capability-wsp"
#define NA_IPREFS_COMMAND_CHOOSER_WSP "command-command-chooser-wsp"
#define NA_IPREFS_COMMAND_CHOOSER_URI "command-command-chooser-lfu"
#define NA_IPREFS_COMMAND_LEGEND_WSP "command-legend-wsp"
#define NA_IPREFS_DESKTOP_ENVIRONMENT "desktop-environment"
#define NA_IPREFS_CONFIRM_LOGOUT_WSP "confirm-logout-wsp"
#define NA_IPREFS_WORKING_DIR_WSP "command-working-dir-chooser-wsp"
#define NA_IPREFS_WORKING_DIR_URI "command-working-dir-chooser-lfu"
#define NA_IPREFS_SHOW_IF_RUNNING_WSP "environment-show-if-running-wsp"
#define NA_IPREFS_SHOW_IF_RUNNING_URI "environment-show-if-running-lfu"
#define NA_IPREFS_TRY_EXEC_WSP "environment-try-exec-wsp"
#define NA_IPREFS_TRY_EXEC_URI "environment-try-exec-lfu"
#define NA_IPREFS_EXPORT_ASK_USER_WSP "export-ask-user-wsp"
#define NA_IPREFS_EXPORT_ASK_USER_LAST_FORMAT "export-ask-user-last-format"
#define NA_IPREFS_EXPORT_ASK_USER_KEEP_LAST_CHOICE "export-ask-user-keep-last-choice"
#define NA_IPREFS_EXPORT_ASSISTANT_WSP "export-assistant-wsp"
#define NA_IPREFS_EXPORT_ASSISTANT_URI "export-assistant-lfu"
#define NA_IPREFS_EXPORT_ASSISTANT_PANED "export-assistant-paned-width"
#define NA_IPREFS_EXPORT_PREFERRED_FORMAT "export-preferred-format"
#define NA_IPREFS_FOLDER_CHOOSER_WSP "folder-chooser-wsp"
#define NA_IPREFS_FOLDER_CHOOSER_URI "folder-chooser-lfu"
#define NA_IPREFS_IMPORT_ASK_USER_WSP "import-ask-user-wsp"
#define NA_IPREFS_IMPORT_ASK_USER_LAST_MODE "import-ask-user-last-mode"
#define NA_IPREFS_IMPORT_ASSISTANT_WSP "import-assistant-wsp"
#define NA_IPREFS_IMPORT_ASSISTANT_URI "import-assistant-lfu"
#define NA_IPREFS_IMPORT_ASK_USER_KEEP_LAST_CHOICE "import-ask-user-keep-last-choice"
#define NA_IPREFS_IMPORT_PREFERRED_MODE "import-preferred-mode"
#define NA_IPREFS_ICON_CHOOSER_URI "item-icon-chooser-lfu"
#define NA_IPREFS_ICON_CHOOSER_PANED "item-icon-chooser-paned-width"
#define NA_IPREFS_ICON_CHOOSER_WSP "item-icon-chooser-wsp"
#define NA_IPREFS_IO_PROVIDERS_WRITE_ORDER "io-providers-write-order"
#define NA_IPREFS_ITEMS_ADD_ABOUT_ITEM "items-add-about-item"
#define NA_IPREFS_ITEMS_CREATE_ROOT_MENU "items-create-root-menu"
#define NA_IPREFS_ITEMS_LEVEL_ZERO_ORDER "items-level-zero-order"
#define NA_IPREFS_ITEMS_LIST_ORDER_MODE "items-list-order-mode"
#define NA_IPREFS_MAIN_PANED "main-paned-width"
#define NA_IPREFS_MAIN_SAVE_AUTO "main-save-auto"
#define NA_IPREFS_MAIN_SAVE_PERIOD "main-save-period"
#define NA_IPREFS_MAIN_TABS_POS "main-tabs-pos"
#define NA_IPREFS_MAIN_TOOLBAR_EDIT_DISPLAY "main-toolbar-edit-display"
#define NA_IPREFS_MAIN_TOOLBAR_FILE_DISPLAY "main-toolbar-file-display"
#define NA_IPREFS_MAIN_TOOLBAR_HELP_DISPLAY "main-toolbar-help-display"
#define NA_IPREFS_MAIN_TOOLBAR_TOOLS_DISPLAY "main-toolbar-tools-display"
#define NA_IPREFS_MAIN_WINDOW_WSP "main-window-wsp"
#define NA_IPREFS_PREFERENCES_WSP "preferences-wsp"
#define NA_IPREFS_PLUGIN_MENU_LOG "plugin-menu-log-enabled"
#define NA_IPREFS_RELABEL_DUPLICATE_ACTION "relabel-when-duplicate-action"
#define NA_IPREFS_RELABEL_DUPLICATE_MENU "relabel-when-duplicate-menu"
#define NA_IPREFS_RELABEL_DUPLICATE_PROFILE "relabel-when-duplicate-profile"
#define NA_IPREFS_SCHEME_ADD_SCHEME_WSP "scheme-add-scheme-wsp"
#define NA_IPREFS_SCHEME_DEFAULT_LIST "scheme-default-list"
#define NA_IPREFS_TERMINAL_PATTERN "terminal-pattern"
#define NA_IPREFS_IO_PROVIDER_GROUP "io-provider"
#define NA_IPREFS_IO_PROVIDER_READABLE "readable"
#define NA_IPREFS_IO_PROVIDER_WRITABLE "writable"
#define SETTINGS_SIGNAL_KEY_CHANGED "settings-key-changed"
Typedefs
typedef void(* NASettingsKeyCallback) (const gchar *group, const gchar *key, gconstpointer new_value, gboolean mandatory, void *user_data)
Functions
void na_settings_register_key_callback (const gchar *key, GCallback callback, gpointer user_data)
void na_settings_free (void)
gboolean na_settings_get_boolean (const gchar *key, gboolean *found, gboolean *mandatory)
gboolean na_settings_get_boolean_ex (const gchar *group, const gchar *key, gboolean *found, gboolean *mandatory)
gchar * na_settings_get_string (const gchar *key, gboolean *found, gboolean *mandatory)
GSList * na_settings_get_string_list (const gchar *key, gboolean *found, gboolean *mandatory)
guint na_settings_get_uint (const gchar *key, gboolean *found, gboolean *mandatory)
GList * na_settings_get_uint_list (const gchar *key, gboolean *found, gboolean *mandatory)
gboolean na_settings_set_boolean (const gchar *key, gboolean value)
gboolean na_settings_set_boolean_ex (const gchar *group, const gchar *key, gboolean value)
gboolean na_settings_set_string (const gchar *key, const gchar *value)
gboolean na_settings_set_string_ex (const gchar *group, const gchar *key, const gchar *value)
gboolean na_settings_set_string_list (const gchar *key, const GSList *value)
gboolean na_settings_set_int_ex (const gchar *group, const gchar *key, int value)
gboolean na_settings_set_uint (const gchar *key, guint value)
gboolean na_settings_set_uint_list (const gchar *key, const GList *value)
GSList * na_settings_get_groups (void)
Macro Definition Documentation
NA_IPREFS_ADMIN_IO_PROVIDERS_LOCKED
#define NA_IPREFS_ADMIN_IO_PROVIDERS_LOCKED "io-providers-locked"
Definition at line 74 of file na-settings.h.
NA_IPREFS_ADMIN_PREFERENCES_LOCKED
#define NA_IPREFS_ADMIN_PREFERENCES_LOCKED "preferences-locked"
Definition at line 73 of file na-settings.h.
Referenced by cact_export_ask_user(), and cact_preferences_editor_run().
NA_IPREFS_ASSISTANT_ESC_CONFIRM
#define NA_IPREFS_ASSISTANT_ESC_CONFIRM "assistant-esc-confirm"
Definition at line 75 of file na-settings.h.
Referenced by cact_assistant_export_run(), and cact_assistant_import_run().
NA_IPREFS_ASSISTANT_ESC_QUIT
#define NA_IPREFS_ASSISTANT_ESC_QUIT "assistant-esc-quit"
Definition at line 76 of file na-settings.h.
Referenced by cact_assistant_export_run(), and cact_assistant_import_run().
NA_IPREFS_CAPABILITY_ADD_CAPABILITY_WSP
#define NA_IPREFS_CAPABILITY_ADD_CAPABILITY_WSP "capability-add-capability-wsp"
Definition at line 77 of file na-settings.h.
NA_IPREFS_COMMAND_CHOOSER_URI
#define NA_IPREFS_COMMAND_CHOOSER_URI "command-command-chooser-lfu"
Definition at line 79 of file na-settings.h.
NA_IPREFS_COMMAND_CHOOSER_WSP
#define NA_IPREFS_COMMAND_CHOOSER_WSP "command-command-chooser-wsp"
Definition at line 78 of file na-settings.h.
NA_IPREFS_COMMAND_LEGEND_WSP
#define NA_IPREFS_COMMAND_LEGEND_WSP "command-legend-wsp"
Definition at line 80 of file na-settings.h.
NA_IPREFS_CONFIRM_LOGOUT_WSP
#define NA_IPREFS_CONFIRM_LOGOUT_WSP "confirm-logout-wsp"
Definition at line 82 of file na-settings.h.
NA_IPREFS_DESKTOP_ENVIRONMENT
#define NA_IPREFS_DESKTOP_ENVIRONMENT "desktop-environment"
Definition at line 81 of file na-settings.h.
NA_IPREFS_EXPORT_ASK_USER_KEEP_LAST_CHOICE
#define NA_IPREFS_EXPORT_ASK_USER_KEEP_LAST_CHOICE "export-ask-user-keep-last-choice"
Definition at line 91 of file na-settings.h.
Referenced by cact_export_ask_user().
NA_IPREFS_EXPORT_ASK_USER_LAST_FORMAT
#define NA_IPREFS_EXPORT_ASK_USER_LAST_FORMAT "export-ask-user-last-format"
Definition at line 90 of file na-settings.h.
Referenced by cact_export_ask_user().
NA_IPREFS_EXPORT_ASK_USER_WSP
#define NA_IPREFS_EXPORT_ASK_USER_WSP "export-ask-user-wsp"
Definition at line 89 of file na-settings.h.
NA_IPREFS_EXPORT_ASSISTANT_PANED
#define NA_IPREFS_EXPORT_ASSISTANT_PANED "export-assistant-paned-width"
Definition at line 94 of file na-settings.h.
NA_IPREFS_EXPORT_ASSISTANT_URI
#define NA_IPREFS_EXPORT_ASSISTANT_URI "export-assistant-lfu"
Definition at line 93 of file na-settings.h.
NA_IPREFS_EXPORT_ASSISTANT_WSP
#define NA_IPREFS_EXPORT_ASSISTANT_WSP "export-assistant-wsp"
Definition at line 92 of file na-settings.h.
NA_IPREFS_EXPORT_PREFERRED_FORMAT
#define NA_IPREFS_EXPORT_PREFERRED_FORMAT "export-preferred-format"
Definition at line 95 of file na-settings.h.
NA_IPREFS_FOLDER_CHOOSER_URI
#define NA_IPREFS_FOLDER_CHOOSER_URI "folder-chooser-lfu"
Definition at line 97 of file na-settings.h.
NA_IPREFS_FOLDER_CHOOSER_WSP
#define NA_IPREFS_FOLDER_CHOOSER_WSP "folder-chooser-wsp"
Definition at line 96 of file na-settings.h.
NA_IPREFS_ICON_CHOOSER_PANED
#define NA_IPREFS_ICON_CHOOSER_PANED "item-icon-chooser-paned-width"
Definition at line 105 of file na-settings.h.
NA_IPREFS_ICON_CHOOSER_URI
#define NA_IPREFS_ICON_CHOOSER_URI "item-icon-chooser-lfu"
Definition at line 104 of file na-settings.h.
NA_IPREFS_ICON_CHOOSER_WSP
#define NA_IPREFS_ICON_CHOOSER_WSP "item-icon-chooser-wsp"
Definition at line 106 of file na-settings.h.
NA_IPREFS_IMPORT_ASK_USER_KEEP_LAST_CHOICE
#define NA_IPREFS_IMPORT_ASK_USER_KEEP_LAST_CHOICE "import-ask-user-keep-last-choice"
Definition at line 102 of file na-settings.h.
NA_IPREFS_IMPORT_ASK_USER_LAST_MODE
#define NA_IPREFS_IMPORT_ASK_USER_LAST_MODE "import-ask-user-last-mode"
Definition at line 99 of file na-settings.h.
NA_IPREFS_IMPORT_ASK_USER_WSP
#define NA_IPREFS_IMPORT_ASK_USER_WSP "import-ask-user-wsp"
Definition at line 98 of file na-settings.h.
Referenced by na_importer_ask_user().
NA_IPREFS_IMPORT_ASSISTANT_URI
#define NA_IPREFS_IMPORT_ASSISTANT_URI "import-assistant-lfu"
Definition at line 101 of file na-settings.h.
NA_IPREFS_IMPORT_ASSISTANT_WSP
#define NA_IPREFS_IMPORT_ASSISTANT_WSP "import-assistant-wsp"
Definition at line 100 of file na-settings.h.
NA_IPREFS_IMPORT_PREFERRED_MODE
#define NA_IPREFS_IMPORT_PREFERRED_MODE "import-preferred-mode"
Definition at line 103 of file na-settings.h.
Referenced by na_importer_import_from_uris().
NA_IPREFS_IO_PROVIDER_GROUP
#define NA_IPREFS_IO_PROVIDER_GROUP "io-provider"
Definition at line 130 of file na-settings.h.
Referenced by na_io_provider_is_conf_readable().
NA_IPREFS_IO_PROVIDER_READABLE
#define NA_IPREFS_IO_PROVIDER_READABLE "readable"
Definition at line 131 of file na-settings.h.
Referenced by na_io_provider_is_conf_readable().
NA_IPREFS_IO_PROVIDER_WRITABLE
#define NA_IPREFS_IO_PROVIDER_WRITABLE "writable"
Definition at line 132 of file na-settings.h.
NA_IPREFS_IO_PROVIDERS_READ_STATUS
#define NA_IPREFS_IO_PROVIDERS_READ_STATUS "io-providers-read-status-composite-key"
Definition at line 69 of file na-settings.h.
NA_IPREFS_IO_PROVIDERS_WRITE_ORDER
#define NA_IPREFS_IO_PROVIDERS_WRITE_ORDER "io-providers-write-order"
Definition at line 107 of file na-settings.h.
Referenced by cact_providers_list_save().
NA_IPREFS_ITEMS_ADD_ABOUT_ITEM
#define NA_IPREFS_ITEMS_ADD_ABOUT_ITEM "items-add-about-item"
Definition at line 108 of file na-settings.h.
NA_IPREFS_ITEMS_CREATE_ROOT_MENU
#define NA_IPREFS_ITEMS_CREATE_ROOT_MENU "items-create-root-menu"
Definition at line 109 of file na-settings.h.
NA_IPREFS_ITEMS_LEVEL_ZERO_ORDER
#define NA_IPREFS_ITEMS_LEVEL_ZERO_ORDER "items-level-zero-order"
Definition at line 110 of file na-settings.h.
Referenced by na_io_provider_load_items(), and na_iprefs_write_level_zero().
NA_IPREFS_ITEMS_LIST_ORDER_MODE
#define NA_IPREFS_ITEMS_LIST_ORDER_MODE "items-list-order-mode"
Definition at line 111 of file na-settings.h.
Referenced by na_iprefs_get_order_mode(), and na_iprefs_set_order_mode().
NA_IPREFS_MAIN_PANED
#define NA_IPREFS_MAIN_PANED "main-paned-width"
Definition at line 112 of file na-settings.h.
NA_IPREFS_MAIN_SAVE_AUTO
#define NA_IPREFS_MAIN_SAVE_AUTO "main-save-auto"
Definition at line 113 of file na-settings.h.
NA_IPREFS_MAIN_SAVE_PERIOD
#define NA_IPREFS_MAIN_SAVE_PERIOD "main-save-period"
Definition at line 114 of file na-settings.h.
NA_IPREFS_MAIN_TABS_POS
#define NA_IPREFS_MAIN_TABS_POS "main-tabs-pos"
Definition at line 115 of file na-settings.h.
Referenced by na_iprefs_get_tabs_pos(), and na_iprefs_set_tabs_pos().
NA_IPREFS_MAIN_TOOLBAR_EDIT_DISPLAY
#define NA_IPREFS_MAIN_TOOLBAR_EDIT_DISPLAY "main-toolbar-edit-display"
Definition at line 116 of file na-settings.h.
NA_IPREFS_MAIN_TOOLBAR_FILE_DISPLAY
#define NA_IPREFS_MAIN_TOOLBAR_FILE_DISPLAY "main-toolbar-file-display"
Definition at line 117 of file na-settings.h.
NA_IPREFS_MAIN_TOOLBAR_HELP_DISPLAY
#define NA_IPREFS_MAIN_TOOLBAR_HELP_DISPLAY "main-toolbar-help-display"
Definition at line 118 of file na-settings.h.
NA_IPREFS_MAIN_TOOLBAR_TOOLS_DISPLAY
#define NA_IPREFS_MAIN_TOOLBAR_TOOLS_DISPLAY "main-toolbar-tools-display"
Definition at line 119 of file na-settings.h.
NA_IPREFS_MAIN_WINDOW_WSP
#define NA_IPREFS_MAIN_WINDOW_WSP "main-window-wsp"
Definition at line 120 of file na-settings.h.
Referenced by na_gtk_utils_restore_window_position().
NA_IPREFS_PLUGIN_MENU_LOG
#define NA_IPREFS_PLUGIN_MENU_LOG "plugin-menu-log-enabled"
Definition at line 122 of file na-settings.h.
NA_IPREFS_PREFERENCES_WSP
#define NA_IPREFS_PREFERENCES_WSP "preferences-wsp"
Definition at line 121 of file na-settings.h.
NA_IPREFS_RELABEL_DUPLICATE_ACTION
#define NA_IPREFS_RELABEL_DUPLICATE_ACTION "relabel-when-duplicate-action"
Definition at line 123 of file na-settings.h.
Referenced by na_updater_should_pasted_be_relabeled().
NA_IPREFS_RELABEL_DUPLICATE_MENU
#define NA_IPREFS_RELABEL_DUPLICATE_MENU "relabel-when-duplicate-menu"
Definition at line 124 of file na-settings.h.
Referenced by na_updater_should_pasted_be_relabeled().
NA_IPREFS_RELABEL_DUPLICATE_PROFILE
#define NA_IPREFS_RELABEL_DUPLICATE_PROFILE "relabel-when-duplicate-profile"
Definition at line 125 of file na-settings.h.
Referenced by na_updater_should_pasted_be_relabeled().
NA_IPREFS_SCHEME_ADD_SCHEME_WSP
#define NA_IPREFS_SCHEME_ADD_SCHEME_WSP "scheme-add-scheme-wsp"
Definition at line 126 of file na-settings.h.
NA_IPREFS_SCHEME_DEFAULT_LIST
#define NA_IPREFS_SCHEME_DEFAULT_LIST "scheme-default-list"
Definition at line 127 of file na-settings.h.
Referenced by cact_schemes_list_save_defaults().
NA_IPREFS_SHOW_IF_RUNNING_URI
#define NA_IPREFS_SHOW_IF_RUNNING_URI "environment-show-if-running-lfu"
Definition at line 86 of file na-settings.h.
NA_IPREFS_SHOW_IF_RUNNING_WSP
#define NA_IPREFS_SHOW_IF_RUNNING_WSP "environment-show-if-running-wsp"
Definition at line 85 of file na-settings.h.
NA_IPREFS_TERMINAL_PATTERN
#define NA_IPREFS_TERMINAL_PATTERN "terminal-pattern"
Definition at line 128 of file na-settings.h.
NA_IPREFS_TRY_EXEC_URI
#define NA_IPREFS_TRY_EXEC_URI "environment-try-exec-lfu"
Definition at line 88 of file na-settings.h.
NA_IPREFS_TRY_EXEC_WSP
#define NA_IPREFS_TRY_EXEC_WSP "environment-try-exec-wsp"
Definition at line 87 of file na-settings.h.
NA_IPREFS_WORKING_DIR_URI
#define NA_IPREFS_WORKING_DIR_URI "command-working-dir-chooser-lfu"
Definition at line 84 of file na-settings.h.
NA_IPREFS_WORKING_DIR_WSP
#define NA_IPREFS_WORKING_DIR_WSP "command-working-dir-chooser-wsp"
Definition at line 83 of file na-settings.h.
SETTINGS_SIGNAL_KEY_CHANGED
#define SETTINGS_SIGNAL_KEY_CHANGED "settings-key-changed"
Definition at line 142 of file na-settings.h.
Typedef Documentation
NASettingsKeyCallback
typedef void(* NASettingsKeyCallback) (const gchar *group, const gchar *key, gconstpointer new_value, gboolean mandatory, void *user_data)
Definition at line 136 of file na-settings.h.
Function Documentation
na_settings_free()
void na_settings_free (void)
na_settings_free:
Definition at line 445 of file na-settings.c.
References NULL.
na_settings_get_boolean()
gboolean na_settings_get_boolean (const gchar * key, gboolean * found, gboolean * mandatory)
na_settings_get_boolean: @key: the key whose value is to be returned. @found: if not NULL, a pointer to a gboolean in which we will store whether the searched @key has been found (TRUE), or if the returned value comes from default (FALSE). @mandatory: if not NULL, a pointer to a gboolean in which we will store whether the returned value has been read from mandatory preferences (TRUE), or from the user preferences (FALSE). When the @key has not been found, @mandatory is set to FALSE.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: the value of the key, of its default value if not found.
Since: 3.1
Definition at line 499 of file na-settings.c.
References key, na_settings_get_boolean_ex(), and NULL.
Referenced by cact_assistant_export_run(), cact_assistant_import_run(), cact_export_ask_user(), cact_preferences_editor_run(), and na_updater_should_pasted_be_relabeled().
na_settings_get_boolean_ex()
gboolean na_settings_get_boolean_ex (const gchar * group, const gchar * key, gboolean * found, gboolean * mandatory)
na_settings_get_boolean_ex: @group: the group where the @key is to be searched for. May be NULL. @key: the key whose value is to be returned. @found: if not NULL, a pointer to a gboolean in which we will store whether the searched @key has been found (TRUE), or if the returned value comes from default (FALSE). @mandatory: if not NULL, a pointer to a gboolean in which we will store whether the returned value has been read from mandatory preferences (TRUE), or from the user preferences (FALSE). When the @key has not been found, @mandatory is set to FALSE.
Returns: the value of the key, of its default value if not found.
Since: 3.1
Definition at line 521 of file na-settings.c.
References FALSE, key, and na_boxed_get_boolean().
Referenced by na_io_provider_is_conf_readable(), and na_settings_get_boolean().
na_settings_get_groups()
GSList * na_settings_get_groups (void)
na_settings_get_groups:
Returns: the list of groups in the configuration; this list should be na_core_utils_slist_free() by the caller.
This function participates to a rather bad hack to obtain the list of known i/o providers from preferences. We do not care of returning unique or sorted group names.
Since: 3.1
Definition at line 932 of file na-settings.c.
References na_core_utils_slist_from_array(), and NULL.
na_settings_get_string()
gchar * na_settings_get_string (const gchar * key, gboolean * found, gboolean * mandatory)
na_settings_get_string: @key: the key whose value is to be returned. @found: if not NULL, a pointer to a gboolean in which we will store whether the searched @key has been found (TRUE), or if the returned value comes from default (FALSE). @mandatory: if not NULL, a pointer to a gboolean in which we will store whether the returned value has been read from mandatory preferences (TRUE), or from the user preferences (FALSE). When the @key has not been found, @mandatory is set to FALSE.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: the value of the key as a newly allocated string, which should be g_free() by the caller.
Since: 3.1
Definition at line 564 of file na-settings.c.
References key, na_boxed_get_string(), and NULL.
Referenced by base_gtk_utils_select_dir(), base_gtk_utils_select_file_with_preview(), cact_export_ask_user(), na_importer_import_from_uris(), na_iprefs_get_order_mode(), and na_iprefs_get_tabs_pos().
na_settings_get_string_list()
GSList * na_settings_get_string_list (const gchar * key, gboolean * found, gboolean * mandatory)
na_settings_get_string_list: @key: the key whose value is to be returned. @found: if not NULL, a pointer to a gboolean in which we will store whether the searched @key has been found (TRUE), or if the returned value comes from default (FALSE). @mandatory: if not NULL, a pointer to a gboolean in which we will store whether the returned value has been read from mandatory preferences (TRUE), or from the user preferences (FALSE). When the @key has not been found, @mandatory is set to FALSE.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: the value of the key as a newly allocated list of strings. The returned list should be na_core_utils_slist_free() by the caller.
Since: 3.1
Definition at line 607 of file na-settings.c.
References key, na_boxed_get_string_list(), and NULL.
Referenced by na_io_provider_load_items().
na_settings_get_uint()
guint na_settings_get_uint (const gchar * key, gboolean * found, gboolean * mandatory)
na_settings_get_uint: @key: the key whose value is to be returned. @found: if not NULL, a pointer to a gboolean in which we will store whether the searched @key has been found (TRUE), or if the returned value comes from default (FALSE). @mandatory: if not NULL, a pointer to a gboolean in which we will store whether the returned value has been read from mandatory preferences (TRUE), or from the user preferences (FALSE). When the @key has not been found, @mandatory is set to FALSE.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: the value of the key.
Since: 3.1
Definition at line 649 of file na-settings.c.
References key, na_boxed_get_uint(), and NULL.
na_settings_get_uint_list()
GList * na_settings_get_uint_list (const gchar * key, gboolean * found, gboolean * mandatory)
na_settings_get_uint_list: @key: the key whose value is to be returned. @found: if not NULL, a pointer to a gboolean in which we will store whether the searched @key has been found (TRUE), or if the returned value comes from default (FALSE). @mandatory: if not NULL, a pointer to a gboolean in which we will store whether the returned value has been read from mandatory preferences (TRUE), or from the user preferences (FALSE). When the @key has not been found, @mandatory is set to FALSE.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: the value of the key as a newly allocated list of uints. The returned list should be g_list_free() by the caller.
Since: 3.1
Definition at line 692 of file na-settings.c.
References key, na_boxed_get_uint_list(), and NULL.
Referenced by na_gtk_utils_restore_window_position().
na_settings_register_key_callback()
void na_settings_register_key_callback (const gchar * key, GCallback callback, gpointer user_data)
na_settings_register_key_callback: @key: the key to be monitored. @callback: the function to be called when the value of the key changes. @user_data: data to be passed to the @callback function.
Registers a new consumer of the monitoring of the @key.
Since: 3.1
Definition at line 464 of file na-settings.c.
References key, and user_data.
na_settings_set_boolean()
gboolean na_settings_set_boolean (const gchar * key, gboolean value)
na_settings_set_boolean: @key: the key whose value is to be returned. @value: the boolean to be written.
This function writes @value as a user preference.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: TRUE is the writing has been successful, FALSE else.
Since: 3.1
Definition at line 730 of file na-settings.c.
References key, NULL, and ok.
Referenced by cact_main_toolbar_activate().
na_settings_set_boolean_ex()
gboolean na_settings_set_boolean_ex (const gchar * group, const gchar * key, gboolean value)
na_settings_set_boolean_ex: @group: the group in the keyed file; @key: the key whose value is to be returned. @value: the boolean to be written.
This function writes @value as a user preference.
Returns: TRUE is the writing has been successful, FALSE else.
Since: 3.1
Definition at line 755 of file na-settings.c.
References key, and ok.
na_settings_set_int_ex()
gboolean na_settings_set_int_ex (const gchar * group, const gchar * key, int value)
na_settings_set_int_ex: @group: the group in the keyed file; @key: the key whose value is to be returned. @value: the unsigned integer to be written.
This function writes @value as a user preference.
Returns: TRUE is the writing has been successful, FALSE else.
Since: 3.2
Definition at line 849 of file na-settings.c.
References key, and ok.
na_settings_set_string()
gboolean na_settings_set_string (const gchar * key, const gchar * value)
na_settings_set_string: @key: the key whose value is to be returned. @value: the string to be written.
This function writes @value as a user preference.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: TRUE is the writing has been successful, FALSE else.
Since: 3.1
Definition at line 782 of file na-settings.c.
References key, and NULL.
Referenced by base_gtk_utils_select_dir(), base_gtk_utils_select_file_with_preview(), na_iprefs_set_order_mode(), and na_iprefs_set_tabs_pos().
na_settings_set_string_ex()
gboolean na_settings_set_string_ex (const gchar * group, const gchar * key, const gchar * value)
na_settings_set_string_ex: @group: the group in the keyed file; @key: the key whose value is to be returned. @value: the string to be written.
This function writes @value as a user preference.
Returns: TRUE is the writing has been successful, FALSE else.
Since: 3.2
Definition at line 800 of file na-settings.c.
References key.
na_settings_set_string_list()
gboolean na_settings_set_string_list (const gchar * key, const GSList * value)
na_settings_set_string_list: @key: the key whose value is to be returned. @value: the list of strings to be written.
This function writes @value as a user preference.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: TRUE is the writing has been successful, FALSE else.
Since: 3.1
Definition at line 820 of file na-settings.c.
References key, NULL, ok, and TRUE.
Referenced by cact_providers_list_save(), cact_schemes_list_save_defaults(), and na_iprefs_write_level_zero().
na_settings_set_uint()
gboolean na_settings_set_uint (const gchar * key, guint value)
na_settings_set_uint: @key: the key whose value is to be returned. @value: the unsigned integer to be written.
This function writes @value as a user preference.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: TRUE is the writing has been successful, FALSE else.
Since: 3.1
Definition at line 876 of file na-settings.c.
References key, NULL, and ok.
na_settings_set_uint_list()
gboolean na_settings_set_uint_list (const gchar * key, const GList * value)
na_settings_set_uint_list: @key: the key whose value is to be returned. @value: the list of unsigned integers to be written.
This function writes @value as a user preference.
This function should only be called for unambiguous keys; the resultat is otherwise undefined (and rather unpredictable).
Returns: TRUE is the writing has been successful, FALSE else.
Since: 3.1
Definition at line 903 of file na-settings.c.
References key, NULL, ok, and TRUE.
Referenced by na_gtk_utils_save_window_position().