MATE Desktop Environment: na-selected-info.c File Reference
na-selected-info.c File Reference
#include <glib/gi18n.h>
#include <string.h>
#include "na-selected-info.h"
Functions
GType na_selected_info_get_type (void)
GList * na_selected_info_get_list_from_item (CajaFileInfo *item)
GList * na_selected_info_get_list_from_list (GList *caja_selection)
GList * na_selected_info_copy_list (GList *files)
void na_selected_info_free_list (GList *files)
gchar * na_selected_info_get_basename (const NASelectedInfo *nsi)
gchar * na_selected_info_get_dirname (const NASelectedInfo *nsi)
gchar * na_selected_info_get_mime_type (const NASelectedInfo *nsi)
gchar * na_selected_info_get_path (const NASelectedInfo *nsi)
gchar * na_selected_info_get_uri (const NASelectedInfo *nsi)
gchar * na_selected_info_get_uri_host (const NASelectedInfo *nsi)
gchar * na_selected_info_get_uri_user (const NASelectedInfo *nsi)
gint na_selected_info_get_uri_port (const NASelectedInfo *nsi)
gchar * na_selected_info_get_uri_scheme (const NASelectedInfo *nsi)
gboolean na_selected_info_is_directory (const NASelectedInfo *nsi)
gboolean na_selected_info_is_regular (const NASelectedInfo *nsi)
gboolean na_selected_info_is_executable (const NASelectedInfo *nsi)
gboolean na_selected_info_is_local (const NASelectedInfo *nsi)
gboolean na_selected_info_is_owner (const NASelectedInfo *nsi, const gchar *user)
gboolean na_selected_info_is_readable (const NASelectedInfo *nsi)
gboolean na_selected_info_is_writable (const NASelectedInfo *nsi)
NASelectedInfo * na_selected_info_create_for_uri (const gchar *uri, const gchar *mimetype, gchar **errmsg)
Function Documentation
na_selected_info_copy_list()
GList * na_selected_info_copy_list (GList * files)
Definition at line 259 of file na-selected-info.c.
References NULL.
na_selected_info_create_for_uri()
NASelectedInfo * na_selected_info_create_for_uri (const gchar * uri, const gchar * mimetype, gchar ** errmsg)
Definition at line 680 of file na-selected-info.c.
na_selected_info_free_list()
void na_selected_info_free_list (GList * files)
Definition at line 280 of file na-selected-info.c.
References NULL.
Referenced by main().
na_selected_info_get_basename()
gchar * na_selected_info_get_basename (const NASelectedInfo * nsi)
Definition at line 295 of file na-selected-info.c.
References NA_IS_SELECTED_INFO, NULL, and NASelectedInfo::private.
Referenced by na_tokens_new_from_selection().
na_selected_info_get_dirname()
gchar * na_selected_info_get_dirname (const NASelectedInfo * nsi)
Definition at line 320 of file na-selected-info.c.
References NA_IS_SELECTED_INFO, NULL, and NASelectedInfo::private.
Referenced by na_tokens_new_from_selection().
na_selected_info_get_list_from_item()
GList * na_selected_info_get_list_from_item (CajaFileInfo * item)
Definition at line 212 of file na-selected-info.c.
References item, and NULL.
na_selected_info_get_list_from_list()
GList * na_selected_info_get_list_from_list (GList * caja_selection)
Definition at line 234 of file na-selected-info.c.
References CAJA_FILE_INFO, and NULL.
na_selected_info_get_mime_type()
gchar * na_selected_info_get_mime_type (const NASelectedInfo * nsi)
Definition at line 344 of file na-selected-info.c.
References NA_IS_SELECTED_INFO, NULL, and NASelectedInfo::private.
Referenced by na_tokens_new_from_selection().
na_selected_info_get_path()
gchar * na_selected_info_get_path (const NASelectedInfo * nsi)
Definition at line 370 of file na-selected-info.c.
References NA_IS_SELECTED_INFO, NULL, and NASelectedInfo::private.
Referenced by na_tokens_new_from_selection().
na_selected_info_get_type()
GType na_selected_info_get_type (void)
Definition at line 81 of file na-selected-info.c.
na_selected_info_get_uri()
gchar * na_selected_info_get_uri (const NASelectedInfo * nsi)
Definition at line 394 of file na-selected-info.c.
References NA_IS_SELECTED_INFO, NULL, and NASelectedInfo::private.
Referenced by na_tokens_new_from_selection().
na_selected_info_get_uri_host()
gchar * na_selected_info_get_uri_host (const NASelectedInfo * nsi)
Definition at line 418 of file na-selected-info.c.
References NA_IS_SELECTED_INFO, NULL, and NASelectedInfo::private.
Referenced by na_tokens_new_from_selection().
na_selected_info_get_uri_port()
gint na_selected_info_get_uri_port (const NASelectedInfo * nsi)
Definition at line 465 of file na-selected-info.c.
References NA_IS_SELECTED_INFO, and NASelectedInfo::private.
Referenced by na_tokens_new_from_selection().
na_selected_info_get_uri_scheme()
gchar * na_selected_info_get_uri_scheme (const NASelectedInfo * nsi)
Definition at line 489 of file na-selected-info.c.
References NA_IS_SELECTED_INFO, NULL, and NASelectedInfo::private.
Referenced by na_selected_info_is_local(), and na_tokens_new_from_selection().
na_selected_info_get_uri_user()
gchar * na_selected_info_get_uri_user (const NASelectedInfo * nsi)
Definition at line 442 of file na-selected-info.c.
References NA_IS_SELECTED_INFO, NULL, and NASelectedInfo::private.
Referenced by na_tokens_new_from_selection().
na_selected_info_is_directory()
gboolean na_selected_info_is_directory (const NASelectedInfo * nsi)
Definition at line 512 of file na-selected-info.c.
References FALSE, NA_IS_SELECTED_INFO, and NASelectedInfo::private.
na_selected_info_is_executable()
gboolean na_selected_info_is_executable (const NASelectedInfo * nsi)
Definition at line 558 of file na-selected-info.c.
References FALSE, NA_IS_SELECTED_INFO, and NASelectedInfo::private.
na_selected_info_is_local()
gboolean na_selected_info_is_local (const NASelectedInfo * nsi)
Definition at line 581 of file na-selected-info.c.
References FALSE, NA_IS_SELECTED_INFO, na_selected_info_get_uri_scheme(), and NASelectedInfo::private.
na_selected_info_is_owner()
gboolean na_selected_info_is_owner (const NASelectedInfo * nsi, const gchar * user)
Definition at line 608 of file na-selected-info.c.
References FALSE, NA_IS_SELECTED_INFO, and NASelectedInfo::private.
na_selected_info_is_readable()
gboolean na_selected_info_is_readable (const NASelectedInfo * nsi)
Definition at line 631 of file na-selected-info.c.
References FALSE, NA_IS_SELECTED_INFO, and NASelectedInfo::private.
na_selected_info_is_regular()
gboolean na_selected_info_is_regular (const NASelectedInfo * nsi)
Definition at line 535 of file na-selected-info.c.
References FALSE, NA_IS_SELECTED_INFO, and NASelectedInfo::private.
na_selected_info_is_writable()
gboolean na_selected_info_is_writable (const NASelectedInfo * nsi)
Definition at line 654 of file na-selected-info.c.
References FALSE, NA_IS_SELECTED_INFO, and NASelectedInfo::private.