MATE Desktop Environment: na-timeout.h File Reference
na-timeout.h File Reference
#include <glib-object.h>
Classes
struct NATimeout
Typedefs
typedef void(* NATimeoutFunc) (void *user_data)
Functions
void na_timeout_event (NATimeout *timeout)
Typedef Documentation
NATimeoutFunc
typedef void(* NATimeoutFunc) (void *user_data)
SECTION: timeout @title: NATimeout @short_description: The NATimeout Structure caja-actions/na-timeout.h
The NATimeout structure is a convenience structure to manage timeout functions.
Since: 3.1 NATimeoutFunc: @user_data: data to be passed to the callback function.
Prototype of the callback function.
Since: 3.1
Definition at line 57 of file na-timeout.h.
Function Documentation
na_timeout_event()
void na_timeout_event (NATimeout * event)
na_timeout_event: @timeout: the NATimeout structure which will handle this event.
Definition at line 44 of file na-timeout.c.
References NATimeout::last_time, NULL, NATimeout::source_id, and NATimeout::timeout.
Referenced by cact_main_window_block_reload(), cadp_desktop_provider_on_monitor_event(), and na_pivot_on_item_changed_handler().