MATE Desktop Environment: na-updater.h File Reference
na-updater.h File Reference
#include "na-pivot.h"
Classes
struct NAUpdater
struct NAUpdaterClass
Macros
#define NA_TYPE_UPDATER (na_updater_get_type())
#define NA_UPDATER(object)
#define NA_UPDATER_CLASS(klass)
#define NA_IS_UPDATER(object)
#define NA_IS_UPDATER_CLASS(klass)
#define NA_UPDATER_GET_CLASS(object)
Typedefs
typedef struct _NAUpdaterPrivate NAUpdaterPrivate
typedef struct _NAUpdaterClassPrivate NAUpdaterClassPrivate
Functions
GType na_updater_get_type (void)
NAUpdater * na_updater_new (void)
void na_updater_check_item_writability_status (const NAUpdater *updater, const NAObjectItem *item)
gboolean na_updater_are_preferences_locked (const NAUpdater *updater)
gboolean na_updater_is_level_zero_writable (const NAUpdater *updater)
void na_updater_append_item (NAUpdater *updater, NAObjectItem *item)
void na_updater_insert_item (NAUpdater *updater, NAObjectItem *item, const gchar *parent_id, gint pos)
void na_updater_remove_item (NAUpdater *updater, NAObject *item)
gboolean na_updater_should_pasted_be_relabeled (const NAUpdater *updater, const NAObject *item)
GList * na_updater_load_items (NAUpdater *updater)
guint na_updater_write_item (const NAUpdater *updater, NAObjectItem *item, GSList **messages)
guint na_updater_delete_item (const NAUpdater *updater, const NAObjectItem *item, GSList **messages)
Macro Definition Documentation
NA_IS_UPDATER
#define NA_IS_UPDATER (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE(object, NA_TYPE_UPDATER))
Definition at line 48 of file na-updater.h.
Referenced by na_updater_append_item(), na_updater_are_preferences_locked(), na_updater_check_item_writability_status(), na_updater_delete_item(), na_updater_insert_item(), na_updater_is_level_zero_writable(), na_updater_load_items(), and na_updater_write_item().
NA_IS_UPDATER_CLASS
#define NA_IS_UPDATER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE((klass), NA_TYPE_UPDATER))
Definition at line 49 of file na-updater.h.
NA_TYPE_UPDATER
#define NA_TYPE_UPDATER (na_updater_get_type())
Definition at line 45 of file na-updater.h.
Referenced by na_updater_new().
NA_UPDATER
#define NA_UPDATER (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST(object, NA_TYPE_UPDATER, NAUpdater))
Definition at line 46 of file na-updater.h.
NA_UPDATER_CLASS
#define NA_UPDATER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST(klass, NA_TYPE_UPDATER, NAUpdaterClass))
Definition at line 47 of file na-updater.h.
NA_UPDATER_GET_CLASS
#define NA_UPDATER_GET_CLASS (object)
Value:
(G_TYPE_INSTANCE_GET_CLASS((object), NA_TYPE_UPDATER, NAUpdaterClass))
Definition at line 50 of file na-updater.h.
Typedef Documentation
NAUpdaterClassPrivate
typedef struct _NAUpdaterClassPrivate NAUpdaterClassPrivate
Definition at line 61 of file na-updater.h.
NAUpdaterPrivate
typedef struct _NAUpdaterPrivate NAUpdaterPrivate
Definition at line 52 of file na-updater.h.
Function Documentation
na_updater_append_item()
void na_updater_append_item (NAUpdater * updater, NAObjectItem * item)
Definition at line 381 of file na-updater.c.
References item, NA_IS_OBJECT_ITEM, NA_IS_UPDATER, NULL, PIVOT_PROP_TREE, and NAUpdater::private.
na_updater_are_preferences_locked()
gboolean na_updater_are_preferences_locked (const NAUpdater * updater)
Definition at line 321 of file na-updater.c.
References NA_IS_UPDATER, NAUpdater::private, and TRUE.
Referenced by cact_providers_list_init_view(), and cact_schemes_list_init_view().
na_updater_check_item_writability_status()
void na_updater_check_item_writability_status (const NAUpdater * updater, const NAObjectItem * item)
Definition at line 250 of file na-updater.c.
References FALSE, item, NA_IIO_PROVIDER_STATUS_ITEM_READONLY, NA_IIO_PROVIDER_STATUS_LEVEL_ZERO, NA_IIO_PROVIDER_STATUS_NO_PROVIDER_FOUND, NA_IIO_PROVIDER_STATUS_UNDETERMINED, NA_IIO_PROVIDER_STATUS_WRITABLE, na_io_provider_find_writable_io_provider(), na_io_provider_is_finally_writable(), NA_IS_OBJECT_ITEM, NA_IS_UPDATER, na_object_get_parent, na_object_get_provider, na_object_is_readonly, na_object_set_writability_status, NA_PIVOT, NAUpdater::private, and TRUE.
Referenced by cact_menubar_file_on_new_action(), and cact_menubar_file_on_new_menu().
na_updater_delete_item()
guint na_updater_delete_item (const NAUpdater * updater, const NAObjectItem * item, GSList ** messages)
Definition at line 598 of file na-updater.c.
References item, NA_IIO_PROVIDER_CODE_OK, NA_IIO_PROVIDER_CODE_PROGRAM_ERROR, na_io_provider_delete_item(), NA_IS_IO_PROVIDER, NA_IS_OBJECT_ITEM, NA_IS_UPDATER, na_object_get_provider, and NAUpdater::private.
Referenced by cact_tree_ieditable_remove_deleted().
na_updater_get_type()
GType na_updater_get_type (void)
Definition at line 68 of file na-updater.c.
na_updater_insert_item()
void na_updater_insert_item (NAUpdater * updater, NAObjectItem * item, const gchar * parent_id, gint pos)
Definition at line 406 of file na-updater.c.
References item, NA_IS_OBJECT_ITEM, NA_IS_UPDATER, na_object_insert_at, NA_PIVOT, na_pivot_get_item(), NULL, PIVOT_PROP_TREE, and NAUpdater::private.
na_updater_is_level_zero_writable()
gboolean na_updater_is_level_zero_writable (const NAUpdater * updater)
Definition at line 357 of file na-updater.c.
References FALSE, NA_IS_UPDATER, and NAUpdater::private.
na_updater_load_items()
GList * na_updater_load_items (NAUpdater * updater)
Definition at line 511 of file na-updater.c.
References NA_IS_UPDATER, NA_PIVOT, na_pivot_get_items(), na_pivot_load_items(), NULL, and NAUpdater::private.
na_updater_new()
NAUpdater * na_updater_new (void)
Definition at line 188 of file na-updater.c.
References NA_TYPE_UPDATER, NULL, and NAUpdater::private.
na_updater_remove_item()
void na_updater_remove_item (NAUpdater * updater, NAObject * item)
Definition at line 441 of file na-updater.c.
References item, NA_IS_PIVOT, na_object_get_items, na_object_get_parent, na_object_set_items, NULL, PIVOT_PROP_TREE, and NAUpdater::private.
na_updater_should_pasted_be_relabeled()
gboolean na_updater_should_pasted_be_relabeled (const NAUpdater * updater, const NAObject * item)
na_updater_should_pasted_be_relabeled: @updater: this NAUpdater instance. @object: the considered #NAObject-derived object.
Whether the specified object should be relabeled when pasted ?
Returns: TRUE if the object should be relabeled, FALSE else.
Definition at line 478 of file na-updater.c.
References FALSE, item, NA_IPREFS_RELABEL_DUPLICATE_ACTION, NA_IPREFS_RELABEL_DUPLICATE_MENU, NA_IPREFS_RELABEL_DUPLICATE_PROFILE, NA_IS_OBJECT_ACTION, NA_IS_OBJECT_MENU, NA_IS_OBJECT_PROFILE, na_settings_get_boolean(), and NULL.
Referenced by cact_menubar_edit_on_duplicate().
na_updater_write_item()
guint na_updater_write_item (const NAUpdater * updater, NAObjectItem * item, GSList ** messages)
Definition at line 556 of file na-updater.c.
References item, NA_IIO_PROVIDER_CODE_PROGRAM_ERROR, NA_IIO_PROVIDER_STATUS_NO_PROVIDER_FOUND, na_io_provider_find_writable_io_provider(), na_io_provider_write_item(), NA_IS_OBJECT_ITEM, NA_IS_UPDATER, na_object_get_provider, NA_PIVOT, and NAUpdater::private.