MATE Desktop Environment: obexftp.c File Reference
obexftp.c File Reference
#include "config.h"
#include <dbus/dbus-glib.h>
#include <dbus/dbus-glib-lowlevel.h>
#include <gio/gio.h>
#include <string.h>
#include "obexftp.h"
#include "user_share-common.h"
#include "user_share-private.h"
Macros
#define GSETTINGS_SCHEMA "org.mate.FileSharing"
Functions
void obexftp_up (void)
void obexftp_down (void)
void obexftp_restart (void)
gboolean obexftp_init (void)
Macro Definition Documentation
GSETTINGS_SCHEMA
#define GSETTINGS_SCHEMA "org.mate.FileSharing"
Definition at line 37 of file obexftp.c.
Function Documentation
obexftp_down()
void obexftp_down (void)
Definition at line 138 of file obexftp.c.
References TRUE.
obexftp_init()
gboolean obexftp_init (void)
Definition at line 151 of file obexftp.c.
References connection, FALSE, NULL, and TRUE.
Referenced by main().
obexftp_restart()
void obexftp_restart (void)
Definition at line 144 of file obexftp.c.
References FALSE, and obexftp_up().
obexftp_up()
void obexftp_up (void)
Definition at line 44 of file obexftp.c.
References connection, FALSE, FILE_SHARING_BLUETOOTH_ALLOW_WRITE, FILE_SHARING_BLUETOOTH_REQUIRE_PAIRING, GSETTINGS_SCHEMA, lookup_public_dir(), NULL, and TRUE.
Referenced by obexftp_restart().