MATE Desktop Environment: obexpush.c File Reference
obexpush.c File Reference
#include "config.h"
#include <glib.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gdk/gdk.h>
#include <gtk/gtk.h>
#include <libnotify/notify.h>
#include <dbus/dbus-glib.h>
#include <dbus/dbus-glib-lowlevel.h>
#include <canberra-gtk.h>
#include <string.h>
#include "marshal.h"
#include "obexpush.h"
#include "user_share-common.h"
#include "user_share-private.h"
Macros
#define DBUS_TYPE_G_STRING_VARIANT_HASHTABLE (dbus_g_type_get_map ("GHashTable", G_TYPE_STRING, G_TYPE_STRING))
#define GSETTINGS_SCHEMA "org.mate.FileSharing"
Functions
void obexpush_up (void)
void obexpush_down (void)
void obexpush_restart (void)
gboolean obexpush_init (void)
void obexpush_set_accept_files_policy (AcceptSetting setting)
void obexpush_set_notify (gboolean enabled)
Macro Definition Documentation
DBUS_TYPE_G_STRING_VARIANT_HASHTABLE
#define DBUS_TYPE_G_STRING_VARIANT_HASHTABLE (dbus_g_type_get_map ("GHashTable", G_TYPE_STRING, G_TYPE_STRING))
Definition at line 44 of file obexpush.c.
GSETTINGS_SCHEMA
#define GSETTINGS_SCHEMA "org.mate.FileSharing"
Definition at line 46 of file obexpush.c.
Function Documentation
obexpush_down()
void obexpush_down (void)
Definition at line 512 of file obexpush.c.
References TRUE.
obexpush_init()
gboolean obexpush_init (void)
Definition at line 525 of file obexpush.c.
References connection, FALSE, marshal_VOID__STRING_STRING_UINT64(), NULL, and TRUE.
Referenced by main().
obexpush_restart()
void obexpush_restart (void)
Definition at line 518 of file obexpush.c.
References FALSE, and obexpush_up().
obexpush_set_accept_files_policy()
void obexpush_set_accept_files_policy (AcceptSetting setting)
Definition at line 551 of file obexpush.c.
obexpush_set_notify()
void obexpush_set_notify (gboolean enabled)
Definition at line 557 of file obexpush.c.
obexpush_up()
void obexpush_up (void)
Definition at line 420 of file obexpush.c.
References connection, FALSE, lookup_download_dir(), NULL, and TRUE.
Referenced by obexpush_restart().