MATE Desktop Environment: oss-device.h File Reference
oss-device.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include "oss-types.h"
Classes
struct _OssDevice
struct _OssDeviceClass
Macros
#define OSS_TYPE_DEVICE (oss_device_get_type ())
#define OSS_DEVICE(o)
#define OSS_IS_DEVICE(o)
#define OSS_DEVICE_CLASS(k)
#define OSS_IS_DEVICE_CLASS(k)
#define OSS_DEVICE_GET_CLASS(o)
Typedefs
typedef struct _OssDeviceClass OssDeviceClass
typedef struct _OssDevicePrivate OssDevicePrivate
Functions
GType oss_device_get_type (void)
OssDevice * oss_device_new (const gchar *name, const gchar *label, const gchar *path, gint fd)
gboolean oss_device_open (OssDevice *device)
gboolean oss_device_is_open (OssDevice *device)
void oss_device_close (OssDevice *device)
void oss_device_load (OssDevice *device)
const gchar * oss_device_get_path (OssDevice *device)
OssStream * oss_device_get_input_stream (OssDevice *device)
OssStream * oss_device_get_output_stream (OssDevice *device)
Macro Definition Documentation
OSS_DEVICE
#define OSS_DEVICE (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), OSS_TYPE_DEVICE, OssDevice))
Definition at line 31 of file oss-device.h.
OSS_DEVICE_CLASS
#define OSS_DEVICE_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST ((k), OSS_TYPE_DEVICE, OssDeviceClass))
Definition at line 35 of file oss-device.h.
OSS_DEVICE_GET_CLASS
#define OSS_DEVICE_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), OSS_TYPE_DEVICE, OssDeviceClass))
Definition at line 39 of file oss-device.h.
OSS_IS_DEVICE
#define OSS_IS_DEVICE (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), OSS_TYPE_DEVICE))
Definition at line 33 of file oss-device.h.
Referenced by oss_device_close(), oss_device_get_input_stream(), oss_device_get_output_stream(), oss_device_get_path(), oss_device_is_open(), oss_device_load(), oss_device_open(), and oss_stream_new().
OSS_IS_DEVICE_CLASS
#define OSS_IS_DEVICE_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), OSS_TYPE_DEVICE))
Definition at line 37 of file oss-device.h.
OSS_TYPE_DEVICE
#define OSS_TYPE_DEVICE (oss_device_get_type ())
Definition at line 29 of file oss-device.h.
Referenced by oss_device_new().
Typedef Documentation
OssDeviceClass
typedef struct _OssDeviceClass OssDeviceClass
Definition at line 42 of file oss-device.h.
OssDevicePrivate
typedef struct _OssDevicePrivate OssDevicePrivate
Definition at line 43 of file oss-device.h.
Function Documentation
oss_device_close()
void oss_device_close (OssDevice * device)
Definition at line 352 of file oss-device.c.
References CLOSED, MATE_MIXER_STREAM, mate_mixer_stream_get_name(), name, NULL, OSS_IS_DEVICE, oss_stream_remove_all(), and _OssDevice::priv.
oss_device_get_input_stream()
OssStream * oss_device_get_input_stream (OssDevice * device)
Definition at line 508 of file oss-device.c.
References NULL, OSS_IS_DEVICE, and _OssDevice::priv.
oss_device_get_output_stream()
OssStream * oss_device_get_output_stream (OssDevice * device)
Definition at line 516 of file oss-device.c.
References NULL, OSS_IS_DEVICE, and _OssDevice::priv.
oss_device_get_path()
const gchar * oss_device_get_path (OssDevice * device)
Definition at line 500 of file oss-device.c.
References NULL, OSS_IS_DEVICE, and _OssDevice::priv.
oss_device_get_type()
GType oss_device_get_type (void)
References label, and name.
oss_device_is_open()
gboolean oss_device_is_open (OssDevice * device)
Definition at line 341 of file oss-device.c.
References FALSE, OSS_IS_DEVICE, _OssDevice::priv, and TRUE.
oss_device_load()
void oss_device_load (OssDevice * device)
Definition at line 401 of file oss-device.c.
References item, MATE_MIXER_DEVICE, mate_mixer_device_get_name(), MATE_MIXER_DIRECTION_INPUT, MATE_MIXER_DIRECTION_OUTPUT, MATE_MIXER_STREAM, mate_mixer_stream_list_controls(), name, NULL, OSS_IS_DEVICE, OSS_POLL_NORMAL, OSS_STREAM_CONTROL, oss_stream_has_controls(), oss_stream_new(), oss_stream_set_default_control(), _OssDevice::priv, and TRUE.
oss_device_new()
OssDevice * oss_device_new (const gchar * name, const gchar * label, const gchar * path, gint fd)
Definition at line 267 of file oss-device.c.
References label, name, NULL, OSS_DEVICE_ICON, OSS_TYPE_DEVICE, and _OssDevice::priv.
oss_device_open()
gboolean oss_device_open (OssDevice * device)
Definition at line 299 of file oss-device.c.
References FALSE, MATE_MIXER_DEVICE, mate_mixer_device_get_label(), OSS_IS_DEVICE, _OssDevice::priv, and TRUE.