MATE Desktop Environment: oss-switch.h File Reference
oss-switch.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include "oss-types.h"
Classes
struct _OssSwitch
struct _OssSwitchClass
Macros
#define OSS_TYPE_SWITCH (oss_switch_get_type ())
#define OSS_SWITCH(o)
#define OSS_IS_SWITCH(o)
#define OSS_SWITCH_CLASS(k)
#define OSS_IS_SWITCH_CLASS(k)
#define OSS_SWITCH_GET_CLASS(o)
Typedefs
typedef struct _OssSwitchClass OssSwitchClass
typedef struct _OssSwitchPrivate OssSwitchPrivate
Functions
GType oss_switch_get_type (void)
OssSwitch * oss_switch_new (OssStream *stream, const gchar *name, const gchar *label, gint fd, GList *options)
void oss_switch_load (OssSwitch *swtch)
void oss_switch_close (OssSwitch *swtch)
Macro Definition Documentation
OSS_IS_SWITCH
#define OSS_IS_SWITCH (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), OSS_TYPE_SWITCH))
Definition at line 33 of file oss-switch.h.
Referenced by oss_switch_close(), and oss_switch_load().
OSS_IS_SWITCH_CLASS
#define OSS_IS_SWITCH_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), OSS_TYPE_SWITCH))
Definition at line 37 of file oss-switch.h.
OSS_SWITCH
#define OSS_SWITCH (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), OSS_TYPE_SWITCH, OssSwitch))
Definition at line 31 of file oss-switch.h.
OSS_SWITCH_CLASS
#define OSS_SWITCH_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST ((k), OSS_TYPE_SWITCH, OssSwitchClass))
Definition at line 35 of file oss-switch.h.
OSS_SWITCH_GET_CLASS
#define OSS_SWITCH_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), OSS_TYPE_SWITCH, OssSwitchClass))
Definition at line 39 of file oss-switch.h.
OSS_TYPE_SWITCH
#define OSS_TYPE_SWITCH (oss_switch_get_type ())
Definition at line 29 of file oss-switch.h.
Referenced by oss_switch_new().
Typedef Documentation
OssSwitchClass
typedef struct _OssSwitchClass OssSwitchClass
Definition at line 42 of file oss-switch.h.
OssSwitchPrivate
typedef struct _OssSwitchPrivate OssSwitchPrivate
Definition at line 43 of file oss-switch.h.
Function Documentation
oss_switch_close()
void oss_switch_close (OssSwitch * swtch)
Definition at line 202 of file oss-switch.c.
References OSS_IS_SWITCH, and _OssSwitch::priv.
Referenced by oss_stream_remove_all().
oss_switch_get_type()
GType oss_switch_get_type (void)
References label, and name.
oss_switch_load()
void oss_switch_load (OssSwitch * swtch)
Definition at line 135 of file oss-switch.c.
References _mate_mixer_switch_set_active_option(), FALSE, MATE_MIXER_SWITCH, mate_mixer_switch_get_name(), MATE_MIXER_SWITCH_OPTION, mate_mixer_switch_option_get_name(), mate_mixer_switch_set_active_option(), NULL, option, OSS_IS_SWITCH, OSS_SWITCH_OPTION, oss_switch_option_get_devnum(), and _OssSwitch::priv.
Referenced by oss_stream_load(), and oss_stream_set_switch_data().
oss_switch_new()
OssSwitch * oss_switch_new (OssStream * stream, const gchar * name, const gchar * label, gint fd, GList * options)
Definition at line 99 of file oss-switch.c.
References label, MATE_MIXER_STREAM_SWITCH_ROLE_PORT, name, NULL, OSS_IS_STREAM, OSS_TYPE_SWITCH, and _OssSwitch::priv.
Referenced by oss_stream_set_switch_data().