MATE Desktop Environment: oss-stream.c File Reference
oss-stream.c File Reference
#include <glib.h>
#include <glib/gi18n.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include <libmatemixer/matemixer-private.h>
#include "oss-device.h"
#include "oss-stream.h"
#include "oss-stream-control.h"
#include "oss-switch.h"
Macros
#define OSS_STREAM_SWITCH_NAME "port"
Functions
OssStream * oss_stream_new (const gchar *name, MateMixerDevice *device, MateMixerDirection direction)
void oss_stream_add_control (OssStream *stream, OssStreamControl *control)
void oss_stream_load (OssStream *stream)
gboolean oss_stream_has_controls (OssStream *stream)
gboolean oss_stream_has_default_control (OssStream *stream)
OssStreamControl * oss_stream_get_default_control (OssStream *stream)
void oss_stream_set_default_control (OssStream *stream, OssStreamControl *control)
void oss_stream_set_switch_data (OssStream *stream, gint fd, GList *options)
void oss_stream_remove_all (OssStream *stream)
Macro Definition Documentation
OSS_STREAM_SWITCH_NAME
#define OSS_STREAM_SWITCH_NAME "port"
Definition at line 29 of file oss-stream.c.
Referenced by oss_stream_remove_all(), and oss_stream_set_switch_data().
Function Documentation
oss_stream_add_control()
void oss_stream_add_control (OssStream * stream, OssStreamControl * control)
Definition at line 109 of file oss-stream.c.
References MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), name, OSS_IS_STREAM, and OSS_IS_STREAM_CONTROL.
oss_stream_get_default_control()
OssStreamControl * oss_stream_get_default_control (OssStream * stream)
Definition at line 168 of file oss-stream.c.
References MATE_MIXER_STREAM, mate_mixer_stream_get_default_control(), NULL, OSS_IS_STREAM, and OSS_STREAM_CONTROL.
oss_stream_has_controls()
gboolean oss_stream_has_controls (OssStream * stream)
Definition at line 146 of file oss-stream.c.
References FALSE, NULL, OSS_IS_STREAM, and TRUE.
Referenced by oss_device_load().
oss_stream_has_default_control()
gboolean oss_stream_has_default_control (OssStream * stream)
Definition at line 157 of file oss-stream.c.
References FALSE, MATE_MIXER_STREAM, mate_mixer_stream_get_default_control(), NULL, OSS_IS_STREAM, and TRUE.
oss_stream_load()
void oss_stream_load (OssStream * stream)
Definition at line 127 of file oss-stream.c.
References NULL, OSS_IS_STREAM, OSS_STREAM_CONTROL, oss_stream_control_load(), and oss_switch_load().
oss_stream_new()
OssStream * oss_stream_new (const gchar * name, MateMixerDevice * device, MateMixerDirection direction)
Definition at line 89 of file oss-stream.c.
References label, mate_mixer_device_get_label(), name, NULL, OSS_IS_DEVICE, and OSS_TYPE_STREAM.
Referenced by oss_device_load().
oss_stream_remove_all()
void oss_stream_remove_all (OssStream * stream)
Definition at line 226 of file oss-stream.c.
References MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), NULL, OSS_IS_STREAM, OSS_STREAM_CONTROL, oss_stream_control_close(), oss_stream_set_default_control(), OSS_STREAM_SWITCH_NAME, and oss_switch_close().
Referenced by oss_device_close().
oss_stream_set_default_control()
void oss_stream_set_default_control (OssStream * stream, OssStreamControl * control)
Definition at line 182 of file oss-stream.c.
References _mate_mixer_stream_set_default_control(), MATE_MIXER_STREAM, MATE_MIXER_STREAM_CONTROL, NULL, OSS_IS_STREAM, and OSS_IS_STREAM_CONTROL.
Referenced by oss_device_load(), and oss_stream_remove_all().
oss_stream_set_switch_data()
void oss_stream_set_switch_data (OssStream * stream, gint fd, GList * options)
Definition at line 195 of file oss-stream.c.
References _, NULL, OSS_IS_STREAM, OSS_STREAM_SWITCH_NAME, oss_switch_load(), and oss_switch_new().