MATE Desktop Environment: pagesel.c File Reference
pagesel.c File Reference
#include <config.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include <limits.h>
#include "mdvi.h"
#include "private.h"
Functions
DviRange * mdvi_parse_range (const char *format, DviRange *limit, int *nitems, char **endptr)
DviPageSpec * mdvi_parse_page_spec (const char *format)
int mdvi_page_selected (DviPageSpec *spec, PageNum page, int dvipage)
void mdvi_free_page_spec (DviPageSpec *spec)
int mdvi_in_range (DviRange *range, int nitems, int value)
int mdvi_range_length (DviRange *range, int nitems)
Variables
char * program_name = "page"
Function Documentation
mdvi_free_page_spec()
void mdvi_free_page_spec (DviPageSpec * spec)
Definition at line 292 of file pagesel.c.
References mdvi_free().
Referenced by __PROTO().
mdvi_in_range()
int mdvi_in_range (DviRange * range, int nitems, int value)
Definition at line 304 of file pagesel.c.
References _DviRange::from, MDVI_RANGE_BOUNDED, MDVI_RANGE_LOWER, MDVI_RANGE_UNBOUNDED, MDVI_RANGE_UPPER, _DviRange::step, _DviRange::to, and _DviRange::type.
Referenced by __PROTO(), and mdvi_page_selected().
mdvi_page_selected()
int mdvi_page_selected (DviPageSpec * spec, PageNum page, int dvipage)
Definition at line 268 of file pagesel.c.
References mdvi_in_range(), and NULL.
Referenced by __PROTO(), and mdvi_init_context().
mdvi_parse_page_spec()
DviPageSpec * mdvi_parse_page_spec (const char * format)
Definition at line 190 of file pagesel.c.
References _, mdvi_error(), mdvi_free(), mdvi_parse_range(), mdvi_warning(), NULL, ptr, xalloc, and xnalloc.
Referenced by __PROTO().
mdvi_parse_range()
DviRange * mdvi_parse_range (const char * format, DviRange * limit, int * nitems, char ** endptr)
Definition at line 36 of file pagesel.c.
References _DviRange::from, mdvi_free(), MDVI_RANGE_BOUNDED, MDVI_RANGE_LOWER, MDVI_RANGE_UNBOUNDED, MDVI_RANGE_UPPER, mdvi_realloc(), mdvi_strdup(), memcpy, NULL, RANGE_HAS_LOWER, RANGE_HAS_UPPER, _DviRange::step, strchr, _DviRange::to, and _DviRange::type.
Referenced by __PROTO(), and mdvi_parse_page_spec().
mdvi_range_length()
int mdvi_range_length (DviRange * range, int nitems)
Definition at line 351 of file pagesel.c.
References _DviRange::from, MDVI_RANGE_BOUNDED, _DviRange::step, _DviRange::to, and _DviRange::type.
Referenced by __PROTO().
Variable Documentation
program_name
char* program_name = "page"
Definition at line 29 of file pagesel.c.
Referenced by main(), main(), mate_about_run(), mate_ui_dialog_about_new_simple(), mate_ui_dialogs_show_about(), mdvi_crash(), mdvi_error(), mdvi_fatal(), mdvi_message(), and mdvi_warning().