MATE Desktop Environment: panel-launch.c File Reference
panel-launch.c File Reference
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gio/gdesktopappinfo.h>
#include <gdk/gdk.h>
#include <gtk/gtk.h>
#include "panel-error.h"
#include "panel-glib.h"
#include "panel-launch.h"
Functions
gboolean panel_app_info_launch_uris (GDesktopAppInfo *appinfo, GList *uris, GdkScreen *screen, const gchar *action, guint32 timestamp, GError **error)
gboolean panel_app_info_launch_uri (GDesktopAppInfo *appinfo, const gchar *uri, GdkScreen *screen, guint32 timestamp, GError **error)
gboolean panel_launch_key_file (GKeyFile *keyfile, GList *uri_list, GdkScreen *screen, const gchar *action, GError **error)
gboolean panel_launch_desktop_file (const char *desktop_file, GdkScreen *screen, GError **error)
gboolean panel_launch_desktop_file_with_fallback (const char *desktop_file, const char *fallback_exec, GdkScreen *screen, GError **error)
Function Documentation
panel_app_info_launch_uri()
gboolean panel_app_info_launch_uri (GDesktopAppInfo * appinfo, const gchar * uri, GdkScreen * screen, guint32 timestamp, GError ** error)
Definition at line 141 of file panel-launch.c.
References error, FALSE, NULL, and panel_app_info_launch_uris().
panel_app_info_launch_uris()
gboolean panel_app_info_launch_uris (GDesktopAppInfo * appinfo, GList * uris, GdkScreen * screen, const gchar * action, guint32 timestamp, GError ** error)
Definition at line 99 of file panel-launch.c.
References action, error, FALSE, NULL, and TRUE.
Referenced by panel_app_info_launch_uri(), panel_launch_desktop_file(), and panel_launch_key_file().
panel_launch_desktop_file()
gboolean panel_launch_desktop_file (const char * desktop_file, GdkScreen * screen, GError ** error)
Definition at line 194 of file panel-launch.c.
References error, FALSE, NULL, panel_app_info_launch_uris(), and panel_g_lookup_in_applications_dirs().
Referenced by panel_launch_desktop_file_with_fallback(), and panel_menu_item_activate_desktop_file().
panel_launch_desktop_file_with_fallback()
gboolean panel_launch_desktop_file_with_fallback (const char * desktop_file, const char * fallback_exec, GdkScreen * screen, GError ** error)
Definition at line 241 of file panel-launch.c.
References error, FALSE, NULL, panel_launch_desktop_file(), and TRUE.
Referenced by panel_menu_bar_invoke_menu(), and panel_menu_button_invoke_menu().
panel_launch_key_file()
gboolean panel_launch_key_file (GKeyFile * keyfile, GList * uri_list, GdkScreen * screen, const gchar * action, GError ** error)
Definition at line 167 of file panel-launch.c.
References action, error, FALSE, NULL, and panel_app_info_launch_uris().
Referenced by launcher_launch().