MATE Desktop Environment: panel-profile.c File Reference
panel-profile.c File Reference
#include <config.h>
#include "panel-profile.h"
#include "panel-layout.h"
#include <string.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gdk/gdkwayland.h>
#include <libpanel-util/panel-list.h>
#include <libmate-desktop/mate-dconf.h>
#include <libmate-desktop/mate-gsettings.h>
#include "applet.h"
#include "panel.h"
#include "panel-widget.h"
#include "panel-util.h"
#include "panel-multimonitor.h"
#include "panel-toplevel.h"
#include "panel-lockdown.h"
#include "panel-schemas.h"
Macros
#define GDK_IS_X11_DISPLAY(object)
#define TOPLEVEL_GET_SET_FUNCS(k, p, t, s, a)
#define TOPLEVEL_GET_SET_BG_FUNCS(k, p, t, s, a)
#define TOPLEVEL_LOCATION_CHANGED_HANDLER(c)
#define TOPLEVEL_POSITION_CHANGED_HANDLER(c)
#define UPDATE_STRING(k, n)
#define UPDATE_ENUM(k, n)
#define UPDATE_INT(k, n)
#define UPDATE_BOOL(k, n)
#define UPDATE_POS(k, n, n2)
#define UPDATE_POS2(k, n, n2)
#define UPDATE_CENTERED(k, n, n2)
#define GET_INT(k, fn)
#define GET_BOOL(k, fn)
#define GET_STRING(k, fn)
#define GET_ENUM(k, fn)
#define GET_POSITION(a, b, c, fn)
Typedefs
typedef const char *(* PanelProfileGetIdFunc) (gpointer object)
typedef gboolean(* PanelProfileOnLoadQueue) (const char *id)
typedef void(* PanelProfileLoadFunc) (const char *id)
typedef void(* PanelProfileDestroyFunc) (const char *id)
Functions
const char * panel_profile_get_toplevel_id (PanelToplevel *toplevel)
PanelToplevel * panel_profile_get_toplevel_by_id (const char *toplevel_id)
char * panel_profile_find_new_id (PanelGSettingsKeyType type)
gboolean panel_profile_key_is_writable (PanelToplevel *toplevel, gchar *key)
gboolean panel_profile_background_key_is_writable (PanelToplevel *toplevel, gchar *key)
void panel_profile_set_background_type (PanelToplevel *toplevel, PanelBackgroundType background_type)
PanelBackgroundType panel_profile_get_background_type (PanelToplevel *toplevel)
void panel_profile_set_background_color (PanelToplevel *toplevel, GdkRGBA *color)
void panel_profile_get_background_color (PanelToplevel *toplevel, GdkRGBA *color)
void panel_profile_set_background_opacity (PanelToplevel *toplevel, gdouble percentage)
gdouble panel_profile_get_background_opacity (PanelToplevel *toplevel)
void panel_profile_set_background_image (PanelToplevel *toplevel, const char *image)
char * panel_profile_get_background_image (PanelToplevel *toplevel)
void panel_profile_set_toplevel_name (PanelToplevel *toplevel, const char *name)
char * panel_profile_get_toplevel_name (PanelToplevel *toplevel)
void panel_profile_set_toplevel_orientation (PanelToplevel *toplevel, PanelOrientation orientation)
PanelOrientation panel_profile_get_toplevel_orientation (PanelToplevel *toplevel)
GSettings * panel_profile_get_attached_object_settings (PanelToplevel *toplevel)
void panel_profile_set_attached_custom_icon (PanelToplevel *toplevel, const char *custom_icon)
char * panel_profile_get_attached_custom_icon (PanelToplevel *toplevel)
gboolean panel_profile_is_writable_attached_custom_icon (PanelToplevel *toplevel)
void panel_profile_set_attached_tooltip (PanelToplevel *toplevel, const char *tooltip)
char * panel_profile_get_attached_tooltip (PanelToplevel *toplevel)
gboolean panel_profile_is_writable_attached_tooltip (PanelToplevel *toplevel)
void panel_profile_add_to_list (PanelGSettingsKeyType type, const char *id)
void panel_profile_remove_from_list (PanelGSettingsKeyType type, const char *id)
gboolean panel_profile_id_lists_are_writable (void)
void panel_profile_create_toplevel (GdkScreen *screen)
void panel_profile_delete_toplevel (PanelToplevel *toplevel)
PanelToplevel * panel_profile_load_toplevel (const char *toplevel_id)
char * panel_profile_prepare_object_with_id (PanelObjectType object_type, const char *toplevel_id, int position, gboolean right_stick)
char * panel_profile_prepare_object (PanelObjectType object_type, PanelToplevel *toplevel, int position, gboolean right_stick)
void panel_profile_delete_object (AppletInfo *applet_info)
void panel_profile_settings_load (void)
void panel_profile_load (void)
gboolean panel_profile_get_show_program_list (void)
gboolean panel_profile_get_enable_program_list (void)
gboolean panel_profile_get_enable_autocompletion (void)
void panel_profile_set_show_program_list (gboolean show_program_list)
gboolean panel_profile_is_writable_show_program_list (void)
gboolean panel_profile_can_be_moved_freely (PanelToplevel *toplevel)
Macro Definition Documentation
GDK_IS_X11_DISPLAY
#define GDK_IS_X11_DISPLAY (object)
Value:
!(G_TYPE_CHECK_INSTANCE_TYPE ((object), GDK_TYPE_WAYLAND_DISPLAY))
Definition at line 41 of file panel-profile.c.
GET_BOOL
#define GET_BOOL (k, fn)
Value:
{                                                                  \
    gboolean val;                                                  \
    val = g_settings_get_boolean (toplevel->settings, k);    \
    panel_toplevel_set_##fn (toplevel, val);                       \
}
Referenced by panel_profile_load_toplevel().
GET_ENUM
#define GET_ENUM (k, fn)
Value:
{                                                               \
    int val;                                                  \
    val = g_settings_get_enum (toplevel->settings, k);        \
    panel_toplevel_set_##fn (toplevel, val);                     \
}
Referenced by panel_profile_load_toplevel().
GET_INT
#define GET_INT (k, fn)
Value:
{                                                               \
    int val;                                                    \
    val = g_settings_get_int (toplevel->settings, k);     \
    panel_toplevel_set_##fn (toplevel, val);                    \
}
Referenced by panel_profile_load_toplevel().
GET_POSITION
#define GET_POSITION (a, b, c, fn)
Value:
{                                                                      \
    gboolean centered;                                                 \
    int      position;                                                 \
    int      position2;                                                \
    centered = g_settings_get_boolean (toplevel->settings, c);   \
    position = g_settings_get_int (toplevel->settings, a);       \
    position2 = g_settings_get_int (toplevel->settings, b);      \
    panel_toplevel_set_##fn (toplevel, position, position2, centered); \
}
Referenced by panel_profile_load_toplevel().
GET_STRING
#define GET_STRING (k, fn)
Value:
{                                                               \
    char *val;                                                  \
    val = g_settings_get_string (toplevel->settings, k);        \
    panel_toplevel_set_##fn (toplevel, val);                     \
    g_free (val);                                               \
}
Referenced by panel_profile_load_toplevel().
TOPLEVEL_GET_SET_BG_FUNCS
#define TOPLEVEL_GET_SET_BG_FUNCS (k, p, t, s, a)
Value:
void                                                          \
panel_profile_set_##p##_##s (PanelToplevel *toplevel, a s)    \
{                                                             \
    g_settings_set_##t (toplevel->background_settings, k, s);            \
}                                                             \
a                                                             \
panel_profile_get_##p##_##s (PanelToplevel *toplevel)         \
{                                                             \
    a retval;                                                 \
    retval = g_settings_get_##t (toplevel->background_settings, k);      \
    return retval;                                            \
}
Definition at line 357 of file panel-profile.c.
TOPLEVEL_GET_SET_FUNCS
#define TOPLEVEL_GET_SET_FUNCS (k, p, t, s, a)
Value:
void                                                          \
panel_profile_set_##p##_##s (PanelToplevel *toplevel, a s)    \
{                                                             \
    g_settings_set_##t (toplevel->settings, k, s);            \
}                                                             \
a                                                             \
panel_profile_get_##p##_##s (PanelToplevel *toplevel)         \
{                                                             \
    a retval;                                                 \
    retval = g_settings_get_##t (toplevel->settings, k);      \
    return retval;                                            \
}
Definition at line 337 of file panel-profile.c.
TOPLEVEL_LOCATION_CHANGED_HANDLER
#define TOPLEVEL_LOCATION_CHANGED_HANDLER (c)
Value:
static void                                                               \
panel_profile_toplevel_##c##_changed (PanelToplevel *toplevel)            \
{                                                                         \
    ToplevelLocationChange change = { NULL };                           \
    change.c##_changed = TRUE;                                        \
    change.c = panel_toplevel_get_##c (toplevel);                     \
    panel_profile_queue_toplevel_location_change (toplevel, &change); \
}
Definition at line 615 of file panel-profile.c.
TOPLEVEL_POSITION_CHANGED_HANDLER
#define TOPLEVEL_POSITION_CHANGED_HANDLER (c)
Value:
static void                                                               \
panel_profile_toplevel_##c##_changed (PanelToplevel *toplevel)            \
{                                                                         \
    ToplevelLocationChange change = { NULL };                           \
    int                    x, y, x_right, y_bottom;                   \
    change.c##_changed = TRUE;                                        \
    panel_toplevel_get_position (toplevel,                            \
                     &x, &x_right,                        \
                     &y, &y_bottom);                      \
    change.c = c;                                                     \
    panel_profile_queue_toplevel_location_change (toplevel, &change); \
}
Definition at line 631 of file panel-profile.c.
UPDATE_BOOL
#define UPDATE_BOOL (k, n)
Value:
if (!strcmp (key, k)) {                                                 \
    panel_toplevel_set_##n (toplevel,                                   \
                            g_settings_get_boolean (settings, key));    \
}
UPDATE_CENTERED
#define UPDATE_CENTERED (k, n, n2)
Value:
if (!strcmp (key, k)) {                                     \
    int x, x_right, y, y_bottom;                            \
    panel_toplevel_get_position (toplevel, &x, &x_right,    \
                     &y, &y_bottom);                        \
    panel_toplevel_set_##n (                                \
        toplevel, n, n2,                                    \
        g_settings_get_boolean (settings, key));            \
}
UPDATE_ENUM
#define UPDATE_ENUM (k, n)
Value:
if (!strcmp (key, k)) {                                                 \
    panel_toplevel_set_##n (toplevel,                                   \
                            g_settings_get_enum (settings, key));       \
}
UPDATE_INT
#define UPDATE_INT (k, n)
Value:
if (!strcmp (key, k)) {                                                 \
    panel_toplevel_set_##n (toplevel,                                   \
                            g_settings_get_int (settings, key));        \
}
UPDATE_POS
#define UPDATE_POS (k, n, n2)
Value:
if (!strcmp (key, k)) {                                                 \
    int x, x_right, y, y_bottom;                            \
    panel_toplevel_get_position (toplevel, &x, &x_right,    \
                     &y, &y_bottom);                        \
    panel_toplevel_set_##n (                                \
        toplevel,                                           \
        g_settings_get_int (settings, key),                 \
        n2,                                                 \
        panel_toplevel_get_##n##_centered (toplevel));      \
}
UPDATE_POS2
#define UPDATE_POS2 (k, n, n2)
Value:
if (!strcmp (key, k)) {                                     \
    int x, x_right, y, y_bottom;                            \
    panel_toplevel_get_position (toplevel, &x, &x_right,    \
                     &y, &y_bottom);                        \
    panel_toplevel_set_##n (                                \
        toplevel,                                           \
        n,                                                  \
        g_settings_get_int (settings, key),                 \
        panel_toplevel_get_##n##_centered (toplevel));      \
}
UPDATE_STRING
#define UPDATE_STRING (k, n)
Value:
if (!strcmp (key, k)) {                                                 \
    gchar *value = g_settings_get_string (settings, key);               \
    panel_toplevel_set_##n (toplevel, value);                           \
    g_free (value);                                                     \
}
Typedef Documentation
PanelProfileDestroyFunc
typedef void(* PanelProfileDestroyFunc) (const char *id)
Definition at line 84 of file panel-profile.c.
PanelProfileGetIdFunc
typedef const char *(* PanelProfileGetIdFunc) (gpointer object)
Definition at line 81 of file panel-profile.c.
PanelProfileLoadFunc
typedef void(* PanelProfileLoadFunc) (const char *id)
Definition at line 83 of file panel-profile.c.
PanelProfileOnLoadQueue
typedef gboolean(* PanelProfileOnLoadQueue) (const char *id)
Definition at line 82 of file panel-profile.c.
Function Documentation
panel_profile_add_to_list()
void panel_profile_add_to_list (PanelGSettingsKeyType type, const char * id)
Definition at line 904 of file panel-profile.c.
References mate_gsettings_append_strv(), NULL, and panel_profile_find_new_id().
Referenced by mate_panel_applet_frame_create(), panel_action_button_create(), panel_drawer_create(), panel_drawer_create_with_id(), panel_launcher_create_with_id(), panel_menu_bar_create(), panel_menu_button_create(), panel_profile_create_toplevel(), and panel_separator_create().
panel_profile_background_key_is_writable()
gboolean panel_profile_background_key_is_writable (PanelToplevel * toplevel, gchar * key)
Definition at line 220 of file panel-profile.c.
References _PanelToplevel::background_settings, and key.
Referenced by panel_receive_dnd_data().
panel_profile_can_be_moved_freely()
gboolean panel_profile_can_be_moved_freely (PanelToplevel * toplevel)
Definition at line 1716 of file panel-profile.c.
References FALSE, panel_lockdown_get_locked_down(), panel_toplevel_get_expand(), PANEL_TOPLEVEL_MONITOR_KEY, PANEL_TOPLEVEL_ORIENTATION_KEY, PANEL_TOPLEVEL_SCREEN_KEY, PANEL_TOPLEVEL_X_CENTERED_KEY, PANEL_TOPLEVEL_X_KEY, PANEL_TOPLEVEL_X_RIGHT_KEY, PANEL_TOPLEVEL_Y_BOTTOM_KEY, PANEL_TOPLEVEL_Y_CENTERED_KEY, PANEL_TOPLEVEL_Y_KEY, _PanelToplevel::settings, and TRUE.
panel_profile_create_toplevel()
void panel_profile_create_toplevel (GdkScreen * screen)
Definition at line 1000 of file panel-profile.c.
References NULL, PANEL_GSETTINGS_TOPLEVELS, panel_profile_add_to_list(), panel_profile_find_new_id(), PANEL_TOPLEVEL_MONITOR_KEY, PANEL_TOPLEVEL_ORIENTATION_KEY, PANEL_TOPLEVEL_PATH, PANEL_TOPLEVEL_SCHEMA, and PANEL_TOPLEVEL_SCREEN_KEY.
panel_profile_delete_object()
void panel_profile_delete_object (AppletInfo * applet_info)
Definition at line 1297 of file panel-profile.c.
References mate_panel_applet_get_id(), PANEL_GSETTINGS_OBJECTS, and panel_profile_remove_from_list().
Referenced by _mate_panel_applet_frame_applet_remove(), drawer_query_deletion(), and mate_panel_applet_register().
panel_profile_delete_toplevel()
void panel_profile_delete_toplevel (PanelToplevel * toplevel)
Definition at line 1075 of file panel-profile.c.
References PANEL_GSETTINGS_TOPLEVELS, panel_profile_get_toplevel_id(), and panel_profile_remove_from_list().
panel_profile_find_new_id()
char * panel_profile_find_new_id (PanelGSettingsKeyType type)
Definition at line 136 of file panel-profile.c.
References mate_dconf_list_subdirs(), NULL, PANEL_GSETTINGS_OBJECTS, PANEL_GSETTINGS_TOPLEVELS, PANEL_OBJECT_DEFAULT_PREFIX, PANEL_OBJECT_PATH, PANEL_TOPLEVEL_DEFAULT_PREFIX, PANEL_TOPLEVEL_PATH, prefix, and TRUE.
Referenced by panel_profile_add_to_list(), panel_profile_create_toplevel(), and panel_profile_prepare_object_with_id().
panel_profile_get_attached_custom_icon()
char * panel_profile_get_attached_custom_icon (PanelToplevel * toplevel)
Definition at line 411 of file panel-profile.c.
References NULL, PANEL_OBJECT_CUSTOM_ICON_KEY, PANEL_OBJECT_USE_CUSTOM_ICON_KEY, panel_profile_get_attached_object_settings(), and panel_toplevel_get_is_attached().
panel_profile_get_attached_object_settings()
GSettings * panel_profile_get_attached_object_settings (PanelToplevel * toplevel)
Definition at line 376 of file panel-profile.c.
References mate_panel_applet_get_id_by_widget(), NULL, PANEL_OBJECT_PATH, PANEL_OBJECT_SCHEMA, and panel_toplevel_get_attach_widget().
Referenced by panel_profile_get_attached_custom_icon(), panel_profile_get_attached_tooltip(), panel_profile_is_writable_attached_custom_icon(), panel_profile_is_writable_attached_tooltip(), panel_profile_set_attached_custom_icon(), and panel_profile_set_attached_tooltip().
panel_profile_get_attached_tooltip()
char * panel_profile_get_attached_tooltip (PanelToplevel * toplevel)
Definition at line 459 of file panel-profile.c.
References NULL, PANEL_OBJECT_TOOLTIP_KEY, panel_profile_get_attached_object_settings(), and panel_toplevel_get_is_attached().
panel_profile_get_background_color()
void panel_profile_get_background_color (PanelToplevel * toplevel, GdkRGBA * color)
Definition at line 256 of file panel-profile.c.
References _PanelToplevel::background_settings.
Referenced by panel_profile_get_background_opacity(), and panel_profile_set_background_opacity().
panel_profile_get_background_image()
char * panel_profile_get_background_image (PanelToplevel * toplevel)
Definition at line 301 of file panel-profile.c.
References _PanelToplevel::background_settings.
panel_profile_get_background_opacity()
gdouble panel_profile_get_background_opacity (PanelToplevel * toplevel)
Definition at line 283 of file panel-profile.c.
References panel_profile_get_background_color().
panel_profile_get_background_type()
PanelBackgroundType panel_profile_get_background_type (PanelToplevel * toplevel)
Definition at line 234 of file panel-profile.c.
References _PanelToplevel::background_settings.
panel_profile_get_enable_autocompletion()
gboolean panel_profile_get_enable_autocompletion (void)
Definition at line 1698 of file panel-profile.c.
panel_profile_get_enable_program_list()
gboolean panel_profile_get_enable_program_list (void)
Definition at line 1692 of file panel-profile.c.
panel_profile_get_show_program_list()
gboolean panel_profile_get_show_program_list (void)
Definition at line 1686 of file panel-profile.c.
panel_profile_get_toplevel_by_id()
PanelToplevel * panel_profile_get_toplevel_by_id (const char * toplevel_id)
Definition at line 120 of file panel-profile.c.
References NULL, panel_profile_get_toplevel_id(), and panel_toplevel_list_toplevels().
panel_profile_get_toplevel_id()
const char * panel_profile_get_toplevel_id (PanelToplevel * toplevel)
Definition at line 111 of file panel-profile.c.
References NULL.
Referenced by panel_launcher_create(), panel_profile_delete_toplevel(), panel_profile_get_toplevel_by_id(), and panel_profile_prepare_object().
panel_profile_get_toplevel_name()
char * panel_profile_get_toplevel_name (PanelToplevel * toplevel)
Definition at line 317 of file panel-profile.c.
References _PanelToplevel::settings.
panel_profile_get_toplevel_orientation()
PanelOrientation panel_profile_get_toplevel_orientation (PanelToplevel * toplevel)
Definition at line 330 of file panel-profile.c.
References _PanelToplevel::settings.
panel_profile_id_lists_are_writable()
gboolean panel_profile_id_lists_are_writable (void)
Definition at line 933 of file panel-profile.c.
References PANEL_GSETTINGS_OBJECTS, and PANEL_GSETTINGS_TOPLEVELS.
Referenced by _mate_panel_applet_frame_applet_broken(), mate_panel_applet_create_menu(), mate_panel_applet_frame_sync_menu_state(), and panel_receive_dnd_data().
panel_profile_is_writable_attached_custom_icon()
gboolean panel_profile_is_writable_attached_custom_icon (PanelToplevel * toplevel)
Definition at line 432 of file panel-profile.c.
References FALSE, PANEL_OBJECT_CUSTOM_ICON_KEY, PANEL_OBJECT_USE_CUSTOM_ICON_KEY, panel_profile_get_attached_object_settings(), and panel_toplevel_get_is_attached().
panel_profile_is_writable_attached_tooltip()
gboolean panel_profile_is_writable_attached_tooltip (PanelToplevel * toplevel)
Definition at line 473 of file panel-profile.c.
References FALSE, PANEL_OBJECT_TOOLTIP_KEY, panel_profile_get_attached_object_settings(), and panel_toplevel_get_is_attached().
panel_profile_is_writable_show_program_list()
gboolean panel_profile_is_writable_show_program_list (void)
Definition at line 1710 of file panel-profile.c.
panel_profile_key_is_writable()
gboolean panel_profile_key_is_writable (PanelToplevel * toplevel, gchar * key)
Definition at line 215 of file panel-profile.c.
References key, and _PanelToplevel::settings.
panel_profile_load()
void panel_profile_load (void)
Definition at line 1659 of file panel-profile.c.
References mate_panel_applet_load_queued_applets(), PANEL_GSETTINGS_OBJECTS, PANEL_GSETTINGS_TOPLEVELS, panel_profile_settings_load(), and TRUE.
Referenced by main().
panel_profile_load_toplevel()
PanelToplevel * panel_profile_load_toplevel (const char * toplevel_id)
Definition at line 1087 of file panel-profile.c.
References _PanelToplevel::background_settings, GET_BOOL, GET_ENUM, GET_INT, GET_POSITION, GET_STRING, name, NULL, panel_setup(), PANEL_TOPLEVEL_BACKGROUND_SCHEMA, PANEL_TOPLEVEL_PATH, PANEL_TOPLEVEL_SCHEMA, panel_toplevel_set_settings_path(), PANEL_TYPE_TOPLEVEL, _PanelToplevel::queued_settings, and _PanelToplevel::settings.
Referenced by drawer_load_from_gsettings().
panel_profile_prepare_object()
char * panel_profile_prepare_object (PanelObjectType object_type, PanelToplevel * toplevel, int position, gboolean right_stick)
Definition at line 1285 of file panel-profile.c.
References panel_profile_get_toplevel_id(), and panel_profile_prepare_object_with_id().
Referenced by mate_panel_applet_frame_create(), panel_action_button_create(), panel_drawer_create(), panel_menu_bar_create(), panel_menu_button_create(), and panel_separator_create().
panel_profile_prepare_object_with_id()
char * panel_profile_prepare_object_with_id (PanelObjectType object_type, const char * toplevel_id, int position, gboolean right_stick)
Definition at line 1251 of file panel-profile.c.
References key_type, PANEL_GSETTINGS_OBJECTS, PANEL_OBJECT_PANEL_RIGHT_STICK_KEY, PANEL_OBJECT_PATH, PANEL_OBJECT_POSITION_KEY, PANEL_OBJECT_SCHEMA, PANEL_OBJECT_TOPLEVEL_ID_KEY, PANEL_OBJECT_TYPE_KEY, and panel_profile_find_new_id().
Referenced by panel_drawer_create_with_id(), panel_launcher_create_with_id(), and panel_profile_prepare_object().
panel_profile_remove_from_list()
void panel_profile_remove_from_list (PanelGSettingsKeyType type, const char * id)
Definition at line 918 of file panel-profile.c.
References mate_gsettings_remove_all_from_strv().
Referenced by panel_profile_delete_object(), and panel_profile_delete_toplevel().
panel_profile_set_attached_custom_icon()
void panel_profile_set_attached_custom_icon (PanelToplevel * toplevel, const char * custom_icon)
Definition at line 398 of file panel-profile.c.
References NULL, PANEL_OBJECT_CUSTOM_ICON_KEY, PANEL_OBJECT_USE_CUSTOM_ICON_KEY, panel_profile_get_attached_object_settings(), and sure_string.
panel_profile_set_attached_tooltip()
void panel_profile_set_attached_tooltip (PanelToplevel * toplevel, const char * tooltip)
Definition at line 449 of file panel-profile.c.
References PANEL_OBJECT_TOOLTIP_KEY, and panel_profile_get_attached_object_settings().
panel_profile_set_background_color()
void panel_profile_set_background_color (PanelToplevel * toplevel, GdkRGBA * color)
Definition at line 243 of file panel-profile.c.
References _PanelToplevel::background_settings.
Referenced by panel_profile_set_background_opacity().
panel_profile_set_background_image()
void panel_profile_set_background_image (PanelToplevel * toplevel, const char * image)
Definition at line 291 of file panel-profile.c.
References _PanelToplevel::background_settings.
panel_profile_set_background_opacity()
void panel_profile_set_background_opacity (PanelToplevel * toplevel, gdouble percentage)
Definition at line 273 of file panel-profile.c.
References panel_profile_get_background_color(), and panel_profile_set_background_color().
panel_profile_set_background_type()
void panel_profile_set_background_type (PanelToplevel * toplevel, PanelBackgroundType background_type)
Definition at line 225 of file panel-profile.c.
References _PanelToplevel::background_settings.
Referenced by panel_receive_dnd_data().
panel_profile_set_show_program_list()
void panel_profile_set_show_program_list (gboolean show_program_list)
Definition at line 1704 of file panel-profile.c.
panel_profile_set_toplevel_name()
void panel_profile_set_toplevel_name (PanelToplevel * toplevel, const char * name)
Definition at line 307 of file panel-profile.c.
References name, and _PanelToplevel::settings.
panel_profile_set_toplevel_orientation()
void panel_profile_set_toplevel_orientation (PanelToplevel * toplevel, PanelOrientation orientation)
Definition at line 323 of file panel-profile.c.
References _PanelToplevel::settings.
panel_profile_settings_load()
void panel_profile_settings_load (void)
Definition at line 1653 of file panel-profile.c.
Referenced by main(), and panel_profile_load().