MATE Desktop Environment: panel-show.c File Reference
panel-show.c File Reference
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gio/gdesktopappinfo.h>
#include <gtk/gtk.h>
#include "panel-error.h"
#include "panel-glib.h"
#include "panel-launch.h"
#include "panel-show.h"
Functions
gboolean panel_show_uri (GdkScreen *screen, const gchar *uri, guint32 timestamp, GError **error)
gboolean panel_show_uri_force_mime_type (GdkScreen *screen, const gchar *uri, const gchar *mime_type, guint32 timestamp, GError **error)
gboolean panel_show_help (GdkScreen *screen, const gchar *doc, const gchar *link, GError **error)
Function Documentation
panel_show_help()
gboolean panel_show_help (GdkScreen * screen, const gchar * doc, const gchar * link, GError ** error)
Definition at line 270 of file panel-show.c.
References error, FALSE, and NULL.
Referenced by panel_action_button_invoke_menu(), panel_menu_bar_invoke_menu(), and panel_menu_button_invoke_menu().
panel_show_uri()
gboolean panel_show_uri (GdkScreen * screen, const gchar * uri, guint32 timestamp, GError ** error)
Definition at line 169 of file panel-show.c.
References error, FALSE, and NULL.
Referenced by panel_show_uri_force_mime_type().
panel_show_uri_force_mime_type()
gboolean panel_show_uri_force_mime_type (GdkScreen * screen, const gchar * uri, const gchar * mime_type, guint32 timestamp, GError ** error)
Definition at line 188 of file panel-show.c.
References error, FALSE, mime_type, NULL, and panel_show_uri().