MATE Desktop Environment: panel-xdg.h File Reference
panel-xdg.h File Reference
#include <gdk/gdk.h>
Functions
char * panel_xdg_icon_remove_extension (const char *icon)
char * panel_xdg_icon_name_from_icon_path (const char *path, GdkScreen *screen)
Function Documentation
panel_xdg_icon_name_from_icon_path()
char * panel_xdg_icon_name_from_icon_path (const char * path, GdkScreen * screen)
Definition at line 64 of file panel-xdg.c.
References DEFAULT_THEME_NAME, FALSE, NULL, panel_xdg_icon_remove_extension(), and strchr.
panel_xdg_icon_remove_extension()
char * panel_xdg_icon_remove_extension (const char * icon)
Definition at line 42 of file panel-xdg.c.
References strrchr.
Referenced by panel_find_icon(), panel_gicon_from_icon_name(), and panel_xdg_icon_name_from_icon_path().