MATE Desktop Environment: panel-widget.h File Reference
panel-widget.h File Reference
#include <gtk/gtk.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include "button-widget.h"
#include "panel-types.h"
#include "panel-background.h"
#include "panel-toplevel.h"
Classes
struct _AppletSizeHints
struct _AppletSizeHintsAlloc
struct _AppletData
struct _PanelWidget
struct _PanelWidgetClass
Macros
#define PANEL_TYPE_WIDGET (panel_widget_get_type())
#define PANEL_WIDGET(object)
#define PANEL_WIDGET_CLASS(klass)
#define PANEL_IS_WIDGET(object)
#define PANEL_MINIMUM_WIDTH 12
#define MATE_PANEL_APPLET_ASSOC_PANEL_KEY "mate_panel_applet_assoc_panel_key"
#define MATE_PANEL_APPLET_FORBIDDEN_PANELS "mate_panel_applet_forbidden_panels"
#define MATE_PANEL_APPLET_DATA "mate_panel_applet_data"
#define PW_DRAG_OFF_CURSOR -1
#define PW_DRAG_OFF_CENTER -2
Typedefs
typedef struct _PanelWidgetClass PanelWidgetClass
typedef struct _AppletRecord AppletRecord
typedef struct _AppletData AppletData
typedef struct _DNDRecord DNDRecord
typedef struct _AppletSizeHints AppletSizeHints
typedef struct _AppletSizeHintsAlloc AppletSizeHintsAlloc
Functions
GType panel_widget_get_type (void)
GtkWidget * panel_widget_new (PanelToplevel *toplevel, gboolean packed, GtkOrientation orient, int sz)
int panel_widget_add (PanelWidget *panel, GtkWidget *applet, gboolean locked, int pos, gboolean insert_at_pos)
void panel_widget_add_forbidden (PanelWidget *panel)
int panel_widget_reparent (PanelWidget *old_panel, PanelWidget *new_panel, GtkWidget *applet, int pos)
gboolean mate_panel_applet_is_in_drag (void)
void panel_widget_applet_drag_start (PanelWidget *panel, GtkWidget *applet, int drag_off, guint32 time_)
void panel_widget_applet_drag_end (PanelWidget *panel)
void panel_widget_set_packed (PanelWidget *panel_widget, gboolean packed)
void panel_widget_set_orientation (PanelWidget *panel_widget, GtkOrientation orientation)
void panel_widget_set_size (PanelWidget *panel_widget, int size)
void panel_widget_draw_all (PanelWidget *panel, GdkRectangle *area)
void panel_widget_draw_icon (PanelWidget *panel, ButtonWidget *applet)
int panel_widget_is_applet_stuck (PanelWidget *panel, GtkWidget *applet)
int panel_widget_get_cursorloc (PanelWidget *panel)
gboolean panel_widget_is_cursor (PanelWidget *panel, int overlap)
void panel_widget_focus (PanelWidget *panel)
PanelOrientation panel_widget_get_applet_orientation (PanelWidget *panel)
void panel_widget_emit_background_changed (PanelWidget *panel)
void panel_widget_set_applet_size_constrained (PanelWidget *panel, GtkWidget *applet, gboolean size_constrained)
void panel_widget_set_applet_expandable (PanelWidget *panel, GtkWidget *applet, gboolean major, gboolean minor)
void panel_widget_set_applet_size_hints (PanelWidget *panel, GtkWidget *applet, int *size_hints, int size_hints_len)
void panel_widget_set_applet_locked (PanelWidget *panel, GtkWidget *applet, gboolean locked)
gboolean panel_widget_get_applet_locked (PanelWidget *panel, GtkWidget *applet)
gboolean panel_widget_toggle_applet_locked (PanelWidget *panel, GtkWidget *applet)
void panel_widget_register_open_dialog (PanelWidget *panel, GtkWidget *dialog)
Macro Definition Documentation
MATE_PANEL_APPLET_ASSOC_PANEL_KEY
#define MATE_PANEL_APPLET_ASSOC_PANEL_KEY "mate_panel_applet_assoc_panel_key"
Definition at line 36 of file panel-widget.h.
Referenced by mate_panel_applet_register().
MATE_PANEL_APPLET_DATA
#define MATE_PANEL_APPLET_DATA "mate_panel_applet_data"
Definition at line 38 of file panel-widget.h.
Referenced by mate_panel_applet_get_position(), panel_widget_add(), panel_widget_get_applet_locked(), panel_widget_is_applet_stuck(), panel_widget_reparent(), panel_widget_set_applet_expandable(), panel_widget_set_applet_locked(), panel_widget_set_applet_size_constrained(), panel_widget_set_applet_size_hints(), and panel_widget_toggle_applet_locked().
MATE_PANEL_APPLET_FORBIDDEN_PANELS
#define MATE_PANEL_APPLET_FORBIDDEN_PANELS "mate_panel_applet_forbidden_panels"
Definition at line 37 of file panel-widget.h.
Referenced by mate_panel_applet_register(), and panel_check_drop_forbidden().
PANEL_IS_WIDGET
#define PANEL_IS_WIDGET (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE((object), PANEL_TYPE_WIDGET))
Definition at line 31 of file panel-widget.h.
Referenced by _mate_panel_applet_frame_applet_move(), mate_panel_applet_frame_change_background(), mate_panel_applet_frame_set_panel(), menu_get_panel(), panel_is_applet_right_stick(), panel_screen_from_panel_widget(), panel_widget_add(), panel_widget_add_forbidden(), panel_widget_applet_drag_end(), panel_widget_applet_drag_start(), panel_widget_get_applet_orientation(), panel_widget_get_cursorloc(), panel_widget_is_applet_stuck(), panel_widget_is_cursor(), panel_widget_reparent(), and panel_widget_set_size().
PANEL_MINIMUM_WIDTH
#define PANEL_MINIMUM_WIDTH 12
Definition at line 34 of file panel-widget.h.
PANEL_TYPE_WIDGET
#define PANEL_TYPE_WIDGET (panel_widget_get_type())
Definition at line 25 of file panel-widget.h.
Referenced by panel_widget_new().
PANEL_WIDGET
#define PANEL_WIDGET (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST((object), PANEL_TYPE_WIDGET, PanelWidget))
Definition at line 27 of file panel-widget.h.
Referenced by _mate_panel_applet_frame_applet_lock(), _mate_panel_applet_frame_applet_move(), launcher_properties(), mate_panel_applet_frame_change_background(), mate_panel_applet_frame_sync_menu_state(), mate_panel_applet_register(), and panel_is_applet_right_stick().
PANEL_WIDGET_CLASS
#define PANEL_WIDGET_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST((klass), PANEL_TYPE_WIDGET, PanelWidgetClass))
Definition at line 29 of file panel-widget.h.
PW_DRAG_OFF_CENTER
#define PW_DRAG_OFF_CENTER -2
Definition at line 170 of file panel-widget.h.
Referenced by _mate_panel_applet_frame_applet_move().
PW_DRAG_OFF_CURSOR
#define PW_DRAG_OFF_CURSOR -1
Definition at line 169 of file panel-widget.h.
Typedef Documentation
AppletData
typedef struct _AppletData AppletData
Definition at line 48 of file panel-widget.h.
AppletRecord
typedef struct _AppletRecord AppletRecord
Definition at line 47 of file panel-widget.h.
AppletSizeHints
typedef struct _AppletSizeHints AppletSizeHints
Definition at line 51 of file panel-widget.h.
AppletSizeHintsAlloc
typedef struct _AppletSizeHintsAlloc AppletSizeHintsAlloc
Definition at line 52 of file panel-widget.h.
DNDRecord
typedef struct _DNDRecord DNDRecord
Definition at line 49 of file panel-widget.h.
PanelWidgetClass
typedef struct _PanelWidgetClass PanelWidgetClass
Definition at line 45 of file panel-widget.h.
Function Documentation
mate_panel_applet_is_in_drag()
gboolean mate_panel_applet_is_in_drag (void)
Definition at line 2918 of file panel-widget.c.
panel_widget_add()
int panel_widget_add (PanelWidget * panel, GtkWidget * applet, gboolean locked, int pos, gboolean insert_at_pos)
Definition at line 2446 of file panel-widget.c.
References _AppletData::applet, APPLET_ADDED_SIGNAL, _PanelWidget::applet_list, _AppletData::cells, _AppletData::constrained, _AppletData::drag_off, _AppletData::expand_major, _AppletData::expand_minor, FALSE, _AppletData::locked, MATE_PANEL_APPLET_DATA, _AppletData::min_cells, NULL, _PanelWidget::orient, _PanelWidget::packed, PANEL_IS_WIDGET, _AppletData::pos, _AppletData::size_constrained, and _AppletData::size_hints.
Referenced by mate_panel_applet_register().
panel_widget_add_forbidden()
void panel_widget_add_forbidden (PanelWidget * panel)
Definition at line 2437 of file panel-widget.c.
References NULL, and PANEL_IS_WIDGET.
Referenced by main().
panel_widget_applet_drag_end()
void panel_widget_applet_drag_end (PanelWidget * panel)
Definition at line 1823 of file panel-widget.c.
References _AppletData::applet, _PanelWidget::currently_dragged_applet, NULL, PANEL_IS_WIDGET, panel_toplevel_pop_autohide_disabler(), and _PanelWidget::toplevel.
Referenced by panel_widget_applet_drag_start().
panel_widget_applet_drag_start()
void panel_widget_applet_drag_start (PanelWidget * panel, GtkWidget * applet, int drag_off, guint32 time_)
Definition at line 1773 of file panel-widget.c.
References FALSE, NULL, PANEL_IS_WIDGET, panel_toplevel_push_autohide_disabler(), panel_widget_applet_drag_end(), and _PanelWidget::toplevel.
Referenced by _mate_panel_applet_frame_applet_move().
panel_widget_draw_all()
void panel_widget_draw_all (PanelWidget * panel, GdkRectangle * area)
panel_widget_draw_icon()
void panel_widget_draw_icon (PanelWidget * panel, ButtonWidget * applet)
panel_widget_emit_background_changed()
void panel_widget_emit_background_changed (PanelWidget * panel)
Definition at line 2633 of file panel-widget.c.
References BACK_CHANGE_SIGNAL.
panel_widget_focus()
void panel_widget_focus (PanelWidget * panel)
Definition at line 2782 of file panel-widget.c.
References NULL, panel_toplevel_get_is_attached(), _PanelWidget::toplevel, and TRUE.
panel_widget_get_applet_locked()
gboolean panel_widget_get_applet_locked (PanelWidget * panel, GtkWidget * applet)
Definition at line 2892 of file panel-widget.c.
References FALSE, _AppletData::locked, and MATE_PANEL_APPLET_DATA.
Referenced by _mate_panel_applet_frame_applet_lock(), mate_panel_applet_create_menu(), mate_panel_applet_frame_sync_menu_state(), and mate_panel_applet_save_position().
panel_widget_get_applet_orientation()
PanelOrientation panel_widget_get_applet_orientation (PanelWidget * panel)
Definition at line 2799 of file panel-widget.c.
References PANEL_IS_TOPLEVEL, PANEL_IS_WIDGET, PANEL_ORIENTATION_TOP, panel_toplevel_get_orientation(), and _PanelWidget::toplevel.
Referenced by mate_panel_applet_frame_activating_get_orientation(), and orientation_change().
panel_widget_get_cursorloc()
int panel_widget_get_cursorloc (PanelWidget * panel)
Definition at line 1846 of file panel-widget.c.
References NULL, _PanelWidget::orient, PANEL_IS_WIDGET, and _PanelWidget::size.
panel_widget_get_type()
GType panel_widget_get_type (void)
panel_widget_is_applet_stuck()
int panel_widget_is_applet_stuck (PanelWidget * panel, GtkWidget * applet)
Definition at line 628 of file panel-widget.c.
References _PanelWidget::applet_list, _AppletData::cells, FALSE, MATE_PANEL_APPLET_DATA, PANEL_IS_WIDGET, _AppletData::pos, _PanelWidget::size, and TRUE.
Referenced by panel_is_applet_right_stick().
panel_widget_is_cursor()
gboolean panel_widget_is_cursor (PanelWidget * panel, int overlap)
Definition at line 1551 of file panel-widget.c.
References _PanelWidget::drop_widget, FALSE, NULL, PANEL_IS_WIDGET, and TRUE.
panel_widget_new()
GtkWidget * panel_widget_new (PanelToplevel * toplevel, gboolean packed, GtkOrientation orient, int sz)
Definition at line 1675 of file panel-widget.c.
References _PanelWidget::drop_widget, FALSE, NULL, _PanelWidget::orient, _PanelWidget::packed, PANEL_TYPE_WIDGET, _PanelWidget::size, _PanelWidget::sz, _PanelWidget::toplevel, and TRUE.
panel_widget_register_open_dialog()
void panel_widget_register_open_dialog (PanelWidget * panel, GtkWidget * dialog)
Definition at line 2924 of file panel-widget.c.
References FALSE, and _PanelWidget::open_dialogs.
Referenced by _mate_panel_applet_frame_applet_broken(), ask_about_launcher(), and launcher_properties().
panel_widget_reparent()
int panel_widget_reparent (PanelWidget * old_panel, PanelWidget * new_panel, GtkWidget * applet, int pos)
Definition at line 2528 of file panel-widget.c.
References _AppletData::applet, _AppletData::constrained, FALSE, MATE_PANEL_APPLET_DATA, MATE_PANEL_APPLET_FRAME, mate_panel_applet_frame_set_panel(), NULL, PANEL_IS_WIDGET, PANEL_OBJECT_APPLET, panel_toplevel_get_is_hidden(), _AppletData::pos, _PanelWidget::toplevel, and TRUE.
panel_widget_set_applet_expandable()
void panel_widget_set_applet_expandable (PanelWidget * panel, GtkWidget * applet, gboolean major, gboolean minor)
Definition at line 2829 of file panel-widget.c.
References _AppletData::expand_major, _AppletData::expand_minor, FALSE, and MATE_PANEL_APPLET_DATA.
Referenced by _mate_panel_applet_frame_update_flags(), and panel_separator_load_from_gsettings().
panel_widget_set_applet_locked()
void panel_widget_set_applet_locked (PanelWidget * panel, GtkWidget * applet, gboolean locked)
Definition at line 2878 of file panel-widget.c.
References FALSE, _AppletData::locked, and MATE_PANEL_APPLET_DATA.
panel_widget_set_applet_size_constrained()
void panel_widget_set_applet_size_constrained (PanelWidget * panel, GtkWidget * applet, gboolean size_constrained)
Definition at line 2808 of file panel-widget.c.
References FALSE, MATE_PANEL_APPLET_DATA, and _AppletData::size_constrained.
Referenced by _mate_panel_applet_frame_activated(), and panel_separator_load_from_gsettings().
panel_widget_set_applet_size_hints()
void panel_widget_set_applet_size_hints (PanelWidget * panel, GtkWidget * applet, int * size_hints, int size_hints_len)
Definition at line 2853 of file panel-widget.c.
References MATE_PANEL_APPLET_DATA, NULL, _AppletData::size_hints, and _AppletData::size_hints_len.
Referenced by _mate_panel_applet_frame_update_size_hints().
panel_widget_set_orientation()
void panel_widget_set_orientation (PanelWidget * panel_widget, GtkOrientation orientation)
Definition at line 2606 of file panel-widget.c.
References _PanelWidget::orient.
Referenced by panel_toplevel_set_orientation().
panel_widget_set_packed()
void panel_widget_set_packed (PanelWidget * panel_widget, gboolean packed)
Definition at line 2597 of file panel-widget.c.
References FALSE, and _PanelWidget::packed.
Referenced by panel_toplevel_set_expand().
panel_widget_set_size()
void panel_widget_set_size (PanelWidget * panel_widget, int size)
Definition at line 2615 of file panel-widget.c.
References PANEL_IS_WIDGET, SIZE_CHANGE_SIGNAL, and _PanelWidget::sz.
Referenced by panel_toplevel_set_size().
panel_widget_toggle_applet_locked()
gboolean panel_widget_toggle_applet_locked (PanelWidget * panel, GtkWidget * applet)
Definition at line 2905 of file panel-widget.c.
References FALSE, _AppletData::locked, and MATE_PANEL_APPLET_DATA.
Referenced by mate_panel_applet_toggle_locked().