MATE Desktop Environment: panel-applet-container.h File Reference
panel-applet-container.h File Reference
#include <glib-object.h>
#include <gtk/gtk.h>
#include "panel.h"
Classes
struct _MatePanelAppletContainer
struct _MatePanelAppletContainerClass
Macros
#define PANEL_TYPE_APPLET_CONTAINER (mate_panel_applet_container_get_type ())
#define MATE_PANEL_APPLET_CONTAINER(obj)
#define MATE_PANEL_APPLET_CONTAINER_CLASS(klass)
#define PANEL_IS_APPLET_CONTAINER(obj)
#define PANEL_IS_APPLET_CONTAINER_CLASS(klass)
#define MATE_PANEL_APPLET_CONTAINER_GET_CLASS(obj)
#define MATE_PANEL_APPLET_CONTAINER_ERROR (mate_panel_applet_container_error_quark())
Typedefs
typedef struct _MatePanelAppletContainer MatePanelAppletContainer
typedef struct _MatePanelAppletContainerClass MatePanelAppletContainerClass
typedef struct _MatePanelAppletContainerPrivate MatePanelAppletContainerPrivate
Enumerations
enum MatePanelAppletContainerError { MATE_PANEL_APPLET_CONTAINER_INVALID_APPLET , MATE_PANEL_APPLET_CONTAINER_INVALID_CHILD_PROPERTY }
Functions
GType mate_panel_applet_container_get_type (void)
GQuark mate_panel_applet_container_error_quark (void)
GtkWidget * mate_panel_applet_container_new (void)
void mate_panel_applet_container_add (MatePanelAppletContainer *container, GdkScreen *screen, const gchar *iid, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data, GVariant *properties)
gboolean mate_panel_applet_container_add_finish (MatePanelAppletContainer *container, GAsyncResult *result, GError **error)
void mate_panel_applet_container_child_popup_menu (MatePanelAppletContainer *container, guint button, guint32 timestamp, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean mate_panel_applet_container_child_popup_menu_finish (MatePanelAppletContainer *container, GAsyncResult *result, GError **error)
gconstpointer mate_panel_applet_container_child_set (MatePanelAppletContainer *container, const gchar *property_name, const GVariant *value, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean mate_panel_applet_container_child_set_finish (MatePanelAppletContainer *container, GAsyncResult *result, GError **error)
gconstpointer mate_panel_applet_container_child_get (MatePanelAppletContainer *container, const gchar *property_name, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
GVariant * mate_panel_applet_container_child_get_finish (MatePanelAppletContainer *container, GAsyncResult *result, GError **error)
void mate_panel_applet_container_cancel_operation (MatePanelAppletContainer *container, gconstpointer operation)
Macro Definition Documentation
MATE_PANEL_APPLET_CONTAINER
#define MATE_PANEL_APPLET_CONTAINER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), PANEL_TYPE_APPLET_CONTAINER, MatePanelAppletContainer))
Definition at line 36 of file panel-applet-container.h.
MATE_PANEL_APPLET_CONTAINER_CLASS
#define MATE_PANEL_APPLET_CONTAINER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST((klass), PANEL_TYPE_APPLET_CONTAINER, MatePanelAppletContainerClass))
Definition at line 37 of file panel-applet-container.h.
MATE_PANEL_APPLET_CONTAINER_ERROR
#define MATE_PANEL_APPLET_CONTAINER_ERROR (mate_panel_applet_container_error_quark())
Definition at line 42 of file panel-applet-container.h.
Referenced by mate_panel_applet_container_child_set().
MATE_PANEL_APPLET_CONTAINER_GET_CLASS
#define MATE_PANEL_APPLET_CONTAINER_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), PANEL_TYPE_APPLET_CONTAINER, MatePanelAppletContainerClass))
Definition at line 40 of file panel-applet-container.h.
PANEL_IS_APPLET_CONTAINER
#define PANEL_IS_APPLET_CONTAINER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), PANEL_TYPE_APPLET_CONTAINER))
Definition at line 38 of file panel-applet-container.h.
Referenced by mate_panel_applet_container_add().
PANEL_IS_APPLET_CONTAINER_CLASS
#define PANEL_IS_APPLET_CONTAINER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), PANEL_TYPE_APPLET_CONTAINER))
Definition at line 39 of file panel-applet-container.h.
PANEL_TYPE_APPLET_CONTAINER
#define PANEL_TYPE_APPLET_CONTAINER (mate_panel_applet_container_get_type ())
Definition at line 35 of file panel-applet-container.h.
Referenced by mate_panel_applet_container_new().
Typedef Documentation
MatePanelAppletContainer
typedef struct _MatePanelAppletContainer MatePanelAppletContainer
Definition at line 49 of file panel-applet-container.h.
MatePanelAppletContainerClass
typedef struct _MatePanelAppletContainerClass MatePanelAppletContainerClass
Definition at line 50 of file panel-applet-container.h.
MatePanelAppletContainerPrivate
typedef struct _MatePanelAppletContainerPrivate MatePanelAppletContainerPrivate
Definition at line 51 of file panel-applet-container.h.
Enumeration Type Documentation
MatePanelAppletContainerError
enum MatePanelAppletContainerError
Enumerator
MATE_PANEL_APPLET_CONTAINER_INVALID_APPLET
MATE_PANEL_APPLET_CONTAINER_INVALID_CHILD_PROPERTY
Definition at line 44 of file panel-applet-container.h.
Function Documentation
mate_panel_applet_container_add()
void mate_panel_applet_container_add (MatePanelAppletContainer * container, GdkScreen * screen, const gchar * iid, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data, GVariant * properties)
Definition at line 546 of file panel-applet-container.c.
References NULL, PANEL_IS_APPLET_CONTAINER, and user_data.
Referenced by mate_panel_applet_frame_dbus_load().
mate_panel_applet_container_add_finish()
gboolean mate_panel_applet_container_add_finish (MatePanelAppletContainer * container, GAsyncResult * result, GError ** error)
Definition at line 564 of file panel-applet-container.c.
References error, and FALSE.
mate_panel_applet_container_cancel_operation()
void mate_panel_applet_container_cancel_operation (MatePanelAppletContainer * container, gconstpointer operation)
Definition at line 827 of file panel-applet-container.c.
References NULL, and _MatePanelAppletContainer::priv.
mate_panel_applet_container_child_get()
gconstpointer mate_panel_applet_container_child_get (MatePanelAppletContainer * container, const gchar * property_name, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 704 of file panel-applet-container.c.
References mate_panel_applet_container_child_get(), NULL, _MatePanelAppletContainer::priv, proxy, and user_data.
Referenced by mate_panel_applet_container_child_get(), and mate_panel_applet_container_child_get_finish().
mate_panel_applet_container_child_get_finish()
GVariant * mate_panel_applet_container_child_get_finish (MatePanelAppletContainer * container, GAsyncResult * result, GError ** error)
Definition at line 752 of file panel-applet-container.c.
References error, mate_panel_applet_container_child_get(), and NULL.
mate_panel_applet_container_child_popup_menu()
void mate_panel_applet_container_child_popup_menu (MatePanelAppletContainer * container, guint button, guint32 timestamp, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 785 of file panel-applet-container.c.
References mate_panel_applet_container_child_popup_menu(), MATE_PANEL_APPLET_INTERFACE, NULL, _MatePanelAppletContainer::priv, proxy, and user_data.
Referenced by mate_panel_applet_container_child_popup_menu(), and mate_panel_applet_container_child_popup_menu_finish().
mate_panel_applet_container_child_popup_menu_finish()
gboolean mate_panel_applet_container_child_popup_menu_finish (MatePanelAppletContainer * container, GAsyncResult * result, GError ** error)
Definition at line 817 of file panel-applet-container.c.
References error, FALSE, and mate_panel_applet_container_child_popup_menu().
mate_panel_applet_container_child_set()
gconstpointer mate_panel_applet_container_child_set (MatePanelAppletContainer * container, const gchar * property_name, const GVariant * value, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 605 of file panel-applet-container.c.
References mate_panel_applet_container_child_set(), MATE_PANEL_APPLET_CONTAINER_ERROR, MATE_PANEL_APPLET_CONTAINER_INVALID_CHILD_PROPERTY, NULL, _MatePanelAppletContainer::priv, proxy, and user_data.
Referenced by mate_panel_applet_container_child_set(), and mate_panel_applet_container_child_set_finish().
mate_panel_applet_container_child_set_finish()
gboolean mate_panel_applet_container_child_set_finish (MatePanelAppletContainer * container, GAsyncResult * result, GError ** error)
Definition at line 661 of file panel-applet-container.c.
References error, FALSE, and mate_panel_applet_container_child_set().
mate_panel_applet_container_error_quark()
GQuark mate_panel_applet_container_error_quark (void)
Definition at line 90 of file panel-applet-container.c.
mate_panel_applet_container_get_type()
GType mate_panel_applet_container_get_type (void)
References error, and user_data.
mate_panel_applet_container_new()
GtkWidget * mate_panel_applet_container_new (void)
Definition at line 254 of file panel-applet-container.c.
References NULL, and PANEL_TYPE_APPLET_CONTAINER.