MATE Desktop Environment: panel-multimonitor.c File Reference
panel-multimonitor.c File Reference
#include <config.h>
#include <gdk/gdkwayland.h>
#include "panel-multimonitor.h"
#include <string.h>
Macros
#define GDK_IS_X11_DISPLAY(object)
Functions
void panel_multimonitor_init (void)
void panel_multimonitor_reinit (void)
int panel_multimonitor_monitors ()
int panel_multimonitor_x (int monitor)
int panel_multimonitor_y (int monitor)
int panel_multimonitor_width (int monitor)
int panel_multimonitor_height (int monitor)
int panel_multimonitor_locate_widget_monitor (GtkWidget *widget)
int panel_multimonitor_get_monitor_at_point (int x, int y)
void panel_multimonitor_is_at_visible_extreme (int n_monitor, gboolean *leftmost, gboolean *rightmost, gboolean *topmost, gboolean *bottommost)
void panel_multimonitor_get_bounds (GdkPoint *min, GdkPoint *max)
Macro Definition Documentation
GDK_IS_X11_DISPLAY
#define GDK_IS_X11_DISPLAY (object)
Value:
!(G_TYPE_CHECK_INSTANCE_TYPE ((object), GDK_TYPE_WAYLAND_DISPLAY))
Definition at line 38 of file panel-multimonitor.c.
Function Documentation
panel_multimonitor_get_bounds()
void panel_multimonitor_get_bounds (GdkPoint * min, GdkPoint * max)
Definition at line 684 of file panel-multimonitor.c.
References MAX, and MIN.
panel_multimonitor_get_monitor_at_point()
int panel_multimonitor_get_monitor_at_point (int x, int y)
Definition at line 582 of file panel-multimonitor.c.
panel_multimonitor_height()
int panel_multimonitor_height (int monitor)
Definition at line 546 of file panel-multimonitor.c.
panel_multimonitor_init()
void panel_multimonitor_init (void)
Definition at line 446 of file panel-multimonitor.c.
References FALSE, GDK_IS_X11_DISPLAY, NULL, and TRUE.
Referenced by main(), and panel_multimonitor_reinit().
panel_multimonitor_is_at_visible_extreme()
void panel_multimonitor_is_at_visible_extreme (int n_monitor, gboolean * leftmost, gboolean * rightmost, gboolean * topmost, gboolean * bottommost)
Definition at line 636 of file panel-multimonitor.c.
References FALSE, and TRUE.
Referenced by panel_struts_set_window_hint().
panel_multimonitor_locate_widget_monitor()
int panel_multimonitor_locate_widget_monitor (GtkWidget * widget)
Definition at line 553 of file panel-multimonitor.c.
References NULL.
panel_multimonitor_monitors()
int panel_multimonitor_monitors (void)
Definition at line 519 of file panel-multimonitor.c.
Referenced by panel_toplevel_set_monitor().
panel_multimonitor_reinit()
void panel_multimonitor_reinit (void)
Definition at line 500 of file panel-multimonitor.c.
References FALSE, and panel_multimonitor_init().
panel_multimonitor_width()
int panel_multimonitor_width (int monitor)
Definition at line 539 of file panel-multimonitor.c.
panel_multimonitor_x()
int panel_multimonitor_x (int monitor)
Definition at line 525 of file panel-multimonitor.c.
panel_multimonitor_y()
int panel_multimonitor_y (int monitor)
Definition at line 532 of file panel-multimonitor.c.