MATE Desktop Environment: panel-lockdown.h File Reference
panel-lockdown.h File Reference
#include <glib.h>
#include <glib-object.h>
Functions
void panel_lockdown_init (void)
void panel_lockdown_finalize (void)
gboolean panel_lockdown_get_locked_down (void)
gboolean panel_lockdown_get_disable_command_line (void)
gboolean panel_lockdown_get_disable_lock_screen (void)
gboolean panel_lockdown_get_disable_log_out (void)
gboolean panel_lockdown_get_disable_force_quit (void)
gboolean panel_lockdown_is_applet_disabled (const char *iid)
void panel_lockdown_notify_add (GCallback callback_func, gpointer user_data)
void panel_lockdown_notify_remove (GCallback callback_func, gpointer user_data)
Function Documentation
panel_lockdown_finalize()
void panel_lockdown_finalize (void)
Definition at line 201 of file panel-lockdown.c.
References FALSE, and NULL.
Referenced by main().
panel_lockdown_get_disable_command_line()
gboolean panel_lockdown_get_disable_command_line (void)
Definition at line 238 of file panel-lockdown.c.
References FALSE.
Referenced by ask_about_launcher(), and panel_run_dialog_present().
panel_lockdown_get_disable_force_quit()
gboolean panel_lockdown_get_disable_force_quit (void)
Definition at line 262 of file panel-lockdown.c.
References FALSE.
panel_lockdown_get_disable_lock_screen()
gboolean panel_lockdown_get_disable_lock_screen (void)
Definition at line 20 of file mate-desktop-item-edit.c.
References FALSE.
Referenced by panel_lock_screen_action(), and panel_lock_screen_action_available().
panel_lockdown_get_disable_log_out()
gboolean panel_lockdown_get_disable_log_out (void)
Definition at line 254 of file panel-lockdown.c.
References FALSE.
Referenced by panel_menu_items_append_lock_logout().
panel_lockdown_get_locked_down()
gboolean panel_lockdown_get_locked_down (void)
Definition at line 230 of file panel-lockdown.c.
References FALSE.
Referenced by mate_panel_applet_can_freely_move(), mate_panel_applet_create_menu(), mate_panel_applet_frame_activating_get_locked_down(), mate_panel_applet_frame_sync_menu_state(), mate_panel_applet_lockable(), panel_check_drop_forbidden(), panel_context_menu_create(), panel_profile_can_be_moved_freely(), panel_receive_dnd_data(), setup_internal_applet_drag(), and setup_uri_drag().
panel_lockdown_init()
void panel_lockdown_init (void)
Definition at line 158 of file panel-lockdown.c.
References FALSE, LOCKDOWN_DISABLE_COMMAND_LINE_KEY, LOCKDOWN_DISABLE_LOCK_SCREEN_KEY, LOCKDOWN_DISABLE_LOG_OUT_KEY, LOCKDOWN_SCHEMA, PANEL_DISABLE_FORCE_QUIT_KEY, PANEL_LOCKED_DOWN_KEY, PANEL_SCHEMA, and TRUE.
Referenced by main().
panel_lockdown_is_applet_disabled()
gboolean panel_lockdown_is_applet_disabled (const char * iid)
Definition at line 270 of file panel-lockdown.c.
References FALSE, and TRUE.
panel_lockdown_notify_add()
void panel_lockdown_notify_add (GCallback callback_func, gpointer user_data)
Definition at line 316 of file panel-lockdown.c.
References closure, NULL, and user_data.
Referenced by _mate_panel_applet_frame_activated(), mate_panel_applet_register(), panel_desktop_menu_item_new(), and panel_setup().
panel_lockdown_notify_remove()
void panel_lockdown_notify_remove (GCallback callback_func, gpointer user_data)
Definition at line 333 of file panel-lockdown.c.
References closure, NULL, and user_data.