MATE Desktop Environment: panel-xutils.c File Reference
panel-xutils.c File Reference
#include <config.h>
#include "panel-xutils.h"
#include <glib.h>
#include <gdk/gdk.h>
#include <gdk/gdkx.h>
#include <X11/Xlib.h>
#include <X11/Xatom.h>
Enumerations
enum {
STRUT_LEFT = 0 , STRUT_RIGHT = 1 , STRUT_TOP = 2 , STRUT_BOTTOM = 3 ,
STRUT_LEFT_START = 4 , STRUT_LEFT_END = 5 , STRUT_RIGHT_START = 6 , STRUT_RIGHT_END = 7 ,
STRUT_TOP_START = 8 , STRUT_TOP_END = 9 , STRUT_BOTTOM_START = 10 , STRUT_BOTTOM_END = 11
}
enum {
STRUT_AREA_X = 0 , STRUT_AREA_Y , STRUT_AREA_WIDTH , STRUT_AREA_HEIGHT ,
STRUT_AREA_LAST
}
Functions
void panel_xutils_set_strut (GdkWindow *gdk_window, PanelOrientation orientation, guint32 strut, guint32 strut_start, guint32 strut_end, GdkRectangle *rect, int scale)
void panel_xutils_unset_strut (GdkWindow *gdk_window)
void panel_warp_pointer (GdkWindow *gdk_window, int x, int y)
guint panel_get_real_modifier_mask (guint mask)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
STRUT_LEFT
STRUT_RIGHT
STRUT_TOP
STRUT_BOTTOM
STRUT_LEFT_START
STRUT_LEFT_END
STRUT_RIGHT_START
STRUT_RIGHT_END
STRUT_TOP_START
STRUT_TOP_END
STRUT_BOTTOM_START
STRUT_BOTTOM_END
Definition at line 44 of file panel-xutils.c.
anonymous enum
anonymous enum
Enumerator
STRUT_AREA_X
STRUT_AREA_Y
STRUT_AREA_WIDTH
STRUT_AREA_HEIGHT
STRUT_AREA_LAST
Definition at line 59 of file panel-xutils.c.
Function Documentation
panel_get_real_modifier_mask()
guint panel_get_real_modifier_mask (guint mask)
Definition at line 190 of file panel-xutils.c.
References GDK_IS_X11_DISPLAY, and mask.
Referenced by panel_bindings_get_mouse_button_modifier_keymask().
panel_warp_pointer()
void panel_warp_pointer (GdkWindow * gdk_window, int x, int y)
Definition at line 169 of file panel-xutils.c.
References GDK_IS_X11_DISPLAY.
panel_xutils_set_strut()
void panel_xutils_set_strut (GdkWindow * gdk_window, PanelOrientation orientation, guint32 strut, guint32 strut_start, guint32 strut_end, GdkRectangle * rect, int scale)
Definition at line 68 of file panel-xutils.c.
References GDK_IS_X11_DISPLAY, PANEL_ORIENTATION_BOTTOM, PANEL_ORIENTATION_LEFT, PANEL_ORIENTATION_RIGHT, PANEL_ORIENTATION_TOP, STRUT_AREA_HEIGHT, STRUT_AREA_LAST, STRUT_AREA_WIDTH, STRUT_AREA_X, STRUT_AREA_Y, STRUT_BOTTOM, STRUT_BOTTOM_END, STRUT_BOTTOM_START, STRUT_LEFT, STRUT_LEFT_END, STRUT_LEFT_START, STRUT_RIGHT, STRUT_RIGHT_END, STRUT_RIGHT_START, STRUT_TOP, STRUT_TOP_END, and STRUT_TOP_START.
Referenced by panel_struts_set_window_hint().
panel_xutils_unset_strut()
void panel_xutils_unset_strut (GdkWindow * gdk_window)
Definition at line 142 of file panel-xutils.c.
Referenced by panel_struts_unset_window_hint().