MATE Desktop Environment: panel-menu-bar.c File Reference
panel-menu-bar.c File Reference
#include <config.h>
#include "panel-menu-bar.h"
#include <string.h>
#include <glib/gi18n.h>
#include <libmate-desktop/mate-image-menu-item.h>
#include <libpanel-util/panel-error.h>
#include <libpanel-util/panel-launch.h>
#include <libpanel-util/panel-show.h>
#include "panel-util.h"
#include "panel-background.h"
#include "panel-action-button.h"
#include "applet.h"
#include "menu.h"
#include "panel-menu-items.h"
#include "panel-globals.h"
#include "panel-profile.h"
#include "panel-lockdown.h"
#include "panel-stock-icons.h"
#include "panel-typebuiltins.h"
#include "panel-icon-names.h"
#include "panel-schemas.h"
Enumerations
enum { PROP_0 , PROP_ORIENTATION }
Functions
void panel_menu_bar_load_from_gsettings (PanelWidget *panel, gboolean locked, int position, gboolean exactpos, const char *id)
void panel_menu_bar_create (PanelToplevel *toplevel, int position)
void panel_menu_bar_invoke_menu (PanelMenuBar *menubar, const char *callback_name)
void panel_menu_bar_popup_menu (PanelMenuBar *menubar, guint32 activate_time)
void panel_menu_bar_change_background (PanelMenuBar *menubar)
void panel_menu_bar_set_orientation (PanelMenuBar *menubar, PanelOrientation orientation)
PanelOrientation panel_menu_bar_get_orientation (PanelMenuBar *menubar)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_ORIENTATION
Definition at line 69 of file panel-menu-bar.c.
Function Documentation
panel_menu_bar_change_background()
void panel_menu_bar_change_background (PanelMenuBar * menubar)
Definition at line 433 of file panel-menu-bar.c.
References _PanelToplevel::background, panel_background_apply_css(), _PanelMenuBar::priv, and _PanelWidget::toplevel.
Referenced by back_change().
panel_menu_bar_create()
void panel_menu_bar_create (PanelToplevel * toplevel, int position)
Definition at line 380 of file panel-menu-bar.c.
References FALSE, PANEL_GSETTINGS_OBJECTS, PANEL_OBJECT_MENU_BAR, panel_profile_add_to_list(), and panel_profile_prepare_object().
panel_menu_bar_get_orientation()
PanelOrientation panel_menu_bar_get_orientation (PanelMenuBar * menubar)
Definition at line 527 of file panel-menu-bar.c.
References PANEL_IS_MENU_BAR, and _PanelMenuBar::priv.
panel_menu_bar_invoke_menu()
void panel_menu_bar_invoke_menu (PanelMenuBar * menubar, const char * callback_name)
Definition at line 389 of file panel-menu-bar.c.
References NULL, PANEL_IS_MENU_BAR, panel_is_program_in_path(), panel_launch_desktop_file_with_fallback(), and panel_show_help().
panel_menu_bar_load_from_gsettings()
void panel_menu_bar_load_from_gsettings (PanelWidget * panel, gboolean locked, int position, gboolean exactpos, const char * id)
Definition at line 375 of file panel-menu-bar.c.
panel_menu_bar_popup_menu()
void panel_menu_bar_popup_menu (PanelMenuBar * menubar, guint32 activate_time)
Definition at line 412 of file panel-menu-bar.c.
References PANEL_IS_MENU_BAR, and _PanelMenuBar::priv.
panel_menu_bar_set_orientation()
void panel_menu_bar_set_orientation (PanelMenuBar * menubar, PanelOrientation orientation)
Definition at line 511 of file panel-menu-bar.c.
References PANEL_IS_MENU_BAR, and _PanelMenuBar::priv.
Referenced by orientation_change().