MATE Desktop Environment: panel-toplevel.c File Reference
panel-toplevel.c File Reference
#include <config.h>
#include "panel-toplevel.h"
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <glib/gi18n.h>
#include "panel-util.h"
#include "panel-profile.h"
#include "panel-frame.h"
#include "panel-multimonitor.h"
#include "panel-a11y.h"
#include "panel-typebuiltins.h"
#include "panel-marshal.h"
#include "panel-widget.h"
#include "panel-bindings.h"
#include "panel-config-global.h"
#include "panel-lockdown.h"
#include "panel-schemas.h"
Macros
#define GDK_IS_X11_DISPLAY(object)
#define DEFAULT_SIZE 48
#define DEFAULT_AUTO_HIDE_SIZE 1
#define DEFAULT_HIDE_DELAY 300
#define DEFAULT_UNHIDE_DELAY 100
#define DEFAULT_DND_THRESHOLD 8
#define MINIMUM_WIDTH 100
#define MAXIMUM_SIZE_SCREEN_RATIO 5
#define SNAP_TOLERANCE_FACTOR 6
#define DEFAULT_ARROW_SIZE 20
#define HANDLE_SIZE 10
#define N_ATTACH_TOPLEVEL_SIGNALS 5
#define N_ATTACH_WIDGET_SIGNALS 5
#define ANIMATION_TIME_FAST 400
#define ANIMATION_TIME_MEDIUM 1200
#define ANIMATION_TIME_SLOW 2000
Enumerations
enum PanelGrabOpType {
PANEL_GRAB_OP_NONE , PANEL_GRAB_OP_MOVE , PANEL_GRAB_OP_RESIZE , PANEL_GRAB_OP_RESIZE_UP ,
PANEL_GRAB_OP_RESIZE_DOWN , PANEL_GRAB_OP_RESIZE_LEFT , PANEL_GRAB_OP_RESIZE_RIGHT
}
enum {
HIDE_SIGNAL , UNHIDE_SIGNAL , POPUP_PANEL_MENU_SIGNAL , TOGGLE_EXPAND_SIGNAL ,
EXPAND_SIGNAL , UNEXPAND_SIGNAL , TOGGLE_HIDDEN_SIGNAL , BEGIN_MOVE_SIGNAL ,
BEGIN_RESIZE_SIGNAL , LAST_SIGNAL
}
enum {
PROP_0 , PROP_NAME , PROP_SETTINGS_PATH , PROP_EXPAND ,
PROP_ORIENTATION , PROP_SIZE , PROP_X , PROP_X_RIGHT ,
PROP_X_CENTERED , PROP_Y , PROP_Y_BOTTOM , PROP_Y_CENTERED ,
PROP_MONITOR , PROP_AUTOHIDE , PROP_HIDE_DELAY , PROP_UNHIDE_DELAY ,
PROP_AUTOHIDE_SIZE , PROP_ANIMATE , PROP_ANIMATION_SPEED , PROP_BUTTONS_ENABLED ,
PROP_ARROWS_ENABLED
}
Functions
GSList * panel_toplevel_list_toplevels (void)
gboolean panel_toplevel_is_last_unattached (PanelToplevel *toplevel)
void panel_toplevel_push_autohide_disabler (PanelToplevel *toplevel)
void panel_toplevel_pop_autohide_disabler (PanelToplevel *toplevel)
void panel_toplevel_update_edges (PanelToplevel *toplevel)
void panel_toplevel_attach_to_widget (PanelToplevel *toplevel, PanelToplevel *attach_toplevel, GtkWidget *attach_widget)
void panel_toplevel_detach (PanelToplevel *toplevel)
gboolean panel_toplevel_get_is_attached (PanelToplevel *toplevel)
PanelToplevel * panel_toplevel_get_attach_toplevel (PanelToplevel *toplevel)
GtkWidget * panel_toplevel_get_attach_widget (PanelToplevel *toplevel)
void panel_toplevel_hide (PanelToplevel *toplevel, gboolean auto_hide, gint direction)
void panel_toplevel_unhide (PanelToplevel *toplevel)
void panel_toplevel_queue_auto_hide (PanelToplevel *toplevel)
void panel_toplevel_queue_auto_unhide (PanelToplevel *toplevel)
void panel_toplevel_queue_initial_unhide (PanelToplevel *toplevel)
PanelWidget * panel_toplevel_get_panel_widget (PanelToplevel *toplevel)
void panel_toplevel_set_name (PanelToplevel *toplevel, const char *name)
void panel_toplevel_set_settings_path (PanelToplevel *toplevel, const char *settings_path)
const char * panel_toplevel_get_name (PanelToplevel *toplevel)
const char * panel_toplevel_get_description (PanelToplevel *toplevel)
void panel_toplevel_set_expand (PanelToplevel *toplevel, gboolean expand)
gboolean panel_toplevel_get_expand (PanelToplevel *toplevel)
gboolean panel_toplevel_get_is_floating (PanelToplevel *toplevel)
void panel_toplevel_set_orientation (PanelToplevel *toplevel, PanelOrientation orientation)
PanelOrientation panel_toplevel_get_orientation (PanelToplevel *toplevel)
void panel_toplevel_set_size (PanelToplevel *toplevel, int size)
int panel_toplevel_get_size (PanelToplevel *toplevel)
void panel_toplevel_set_auto_hide_size (PanelToplevel *toplevel, int auto_hide_size)
int panel_toplevel_get_auto_hide_size (PanelToplevel *toplevel)
void panel_toplevel_set_x (PanelToplevel *toplevel, int x, int x_right, gboolean x_centered)
void panel_toplevel_set_y (PanelToplevel *toplevel, int y, int y_bottom, gboolean y_centered)
void panel_toplevel_get_position (PanelToplevel *toplevel, int *x, int *x_right, int *y, int *y_bottom)
gboolean panel_toplevel_get_x_centered (PanelToplevel *toplevel)
gboolean panel_toplevel_get_y_centered (PanelToplevel *toplevel)
void panel_toplevel_set_monitor (PanelToplevel *toplevel, int monitor)
int panel_toplevel_get_monitor (PanelToplevel *toplevel)
void panel_toplevel_set_auto_hide (PanelToplevel *toplevel, gboolean auto_hide)
gboolean panel_toplevel_get_auto_hide (PanelToplevel *toplevel)
void panel_toplevel_set_hide_delay (PanelToplevel *toplevel, int hide_delay)
int panel_toplevel_get_hide_delay (PanelToplevel *toplevel)
void panel_toplevel_set_unhide_delay (PanelToplevel *toplevel, int unhide_delay)
int panel_toplevel_get_unhide_delay (PanelToplevel *toplevel)
void panel_toplevel_set_animate (PanelToplevel *toplevel, gboolean animate)
gboolean panel_toplevel_get_animate (PanelToplevel *toplevel)
void panel_toplevel_set_animation_speed (PanelToplevel *toplevel, PanelAnimationSpeed animation_speed)
PanelAnimationSpeed panel_toplevel_get_animation_speed (PanelToplevel *toplevel)
void panel_toplevel_set_enable_buttons (PanelToplevel *toplevel, gboolean enable_buttons)
gboolean panel_toplevel_get_enable_buttons (PanelToplevel *toplevel)
void panel_toplevel_set_enable_arrows (PanelToplevel *toplevel, gboolean enable_arrows)
gboolean panel_toplevel_get_enable_arrows (PanelToplevel *toplevel)
void panel_toplevel_rotate (PanelToplevel *toplevel, gboolean clockwise)
PanelState panel_toplevel_get_state (PanelToplevel *toplevel)
gboolean panel_toplevel_get_is_hidden (PanelToplevel *toplevel)
int panel_toplevel_get_minimum_size (PanelToplevel *toplevel)
int panel_toplevel_get_maximum_size (PanelToplevel *toplevel)
Macro Definition Documentation
ANIMATION_TIME_FAST
#define ANIMATION_TIME_FAST 400
ANIMATION_TIME_MEDIUM
#define ANIMATION_TIME_MEDIUM 1200
ANIMATION_TIME_SLOW
#define ANIMATION_TIME_SLOW 2000
DEFAULT_ARROW_SIZE
#define DEFAULT_ARROW_SIZE 20
Definition at line 76 of file panel-toplevel.c.
DEFAULT_AUTO_HIDE_SIZE
#define DEFAULT_AUTO_HIDE_SIZE 1
Definition at line 69 of file panel-toplevel.c.
Referenced by panel_toplevel_get_auto_hide_size().
DEFAULT_DND_THRESHOLD
#define DEFAULT_DND_THRESHOLD 8
Definition at line 72 of file panel-toplevel.c.
DEFAULT_HIDE_DELAY
#define DEFAULT_HIDE_DELAY 300
Definition at line 70 of file panel-toplevel.c.
DEFAULT_SIZE
#define DEFAULT_SIZE 48
Definition at line 68 of file panel-toplevel.c.
DEFAULT_UNHIDE_DELAY
#define DEFAULT_UNHIDE_DELAY 100
Definition at line 71 of file panel-toplevel.c.
GDK_IS_X11_DISPLAY
#define GDK_IS_X11_DISPLAY (object)
Value:
!(G_TYPE_CHECK_INSTANCE_TYPE ((object), GDK_TYPE_WAYLAND_DISPLAY))
Definition at line 65 of file panel-toplevel.c.
HANDLE_SIZE
#define HANDLE_SIZE 10
Definition at line 77 of file panel-toplevel.c.
MAXIMUM_SIZE_SCREEN_RATIO
#define MAXIMUM_SIZE_SCREEN_RATIO 5
Definition at line 74 of file panel-toplevel.c.
Referenced by panel_toplevel_get_maximum_size().
MINIMUM_WIDTH
#define MINIMUM_WIDTH 100
Definition at line 73 of file panel-toplevel.c.
N_ATTACH_TOPLEVEL_SIGNALS
#define N_ATTACH_TOPLEVEL_SIGNALS 5
Definition at line 78 of file panel-toplevel.c.
N_ATTACH_WIDGET_SIGNALS
#define N_ATTACH_WIDGET_SIGNALS 5
Definition at line 79 of file panel-toplevel.c.
SNAP_TOLERANCE_FACTOR
#define SNAP_TOLERANCE_FACTOR 6
Definition at line 75 of file panel-toplevel.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HIDE_SIGNAL
UNHIDE_SIGNAL
POPUP_PANEL_MENU_SIGNAL
TOGGLE_EXPAND_SIGNAL
EXPAND_SIGNAL
UNEXPAND_SIGNAL
TOGGLE_HIDDEN_SIGNAL
BEGIN_MOVE_SIGNAL
BEGIN_RESIZE_SIGNAL
LAST_SIGNAL
Definition at line 215 of file panel-toplevel.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_NAME
PROP_SETTINGS_PATH
PROP_EXPAND
PROP_ORIENTATION
PROP_SIZE
PROP_X
PROP_X_RIGHT
PROP_X_CENTERED
PROP_Y
PROP_Y_BOTTOM
PROP_Y_CENTERED
PROP_MONITOR
PROP_AUTOHIDE
PROP_HIDE_DELAY
PROP_UNHIDE_DELAY
PROP_AUTOHIDE_SIZE
PROP_ANIMATE
PROP_ANIMATION_SPEED
PROP_BUTTONS_ENABLED
PROP_ARROWS_ENABLED
Definition at line 228 of file panel-toplevel.c.
PanelGrabOpType
enum PanelGrabOpType
Enumerator
PANEL_GRAB_OP_NONE
PANEL_GRAB_OP_MOVE
PANEL_GRAB_OP_RESIZE
PANEL_GRAB_OP_RESIZE_UP
PANEL_GRAB_OP_RESIZE_DOWN
PANEL_GRAB_OP_RESIZE_LEFT
PANEL_GRAB_OP_RESIZE_RIGHT
Definition at line 81 of file panel-toplevel.c.
Function Documentation
panel_toplevel_attach_to_widget()
void panel_toplevel_attach_to_widget (PanelToplevel * toplevel, PanelToplevel * attach_toplevel, GtkWidget * attach_widget)
Definition at line 2753 of file panel-toplevel.c.
References FALSE, PANEL_IS_TOPLEVEL, PANEL_STATE_NORMAL, panel_toplevel_get_monitor(), panel_toplevel_push_autohide_disabler(), panel_toplevel_set_expand(), panel_toplevel_set_monitor(), _PanelToplevel::priv, and TRUE.
panel_toplevel_detach()
void panel_toplevel_detach (PanelToplevel * toplevel)
Definition at line 2793 of file panel-toplevel.c.
References FALSE, NULL, PANEL_IS_TOPLEVEL, PANEL_STATE_NORMAL, panel_toplevel_pop_autohide_disabler(), and _PanelToplevel::priv.
panel_toplevel_get_animate()
gboolean panel_toplevel_get_animate (PanelToplevel * toplevel)
Definition at line 5505 of file panel-toplevel.c.
References FALSE, PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_get_animation_speed()
PanelAnimationSpeed panel_toplevel_get_animation_speed (PanelToplevel * toplevel)
Definition at line 5527 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_get_attach_toplevel()
PanelToplevel * panel_toplevel_get_attach_toplevel (PanelToplevel * toplevel)
Definition at line 2824 of file panel-toplevel.c.
References NULL, PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_get_attach_widget()
GtkWidget * panel_toplevel_get_attach_widget (PanelToplevel * toplevel)
Definition at line 2832 of file panel-toplevel.c.
References NULL, PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
Referenced by panel_profile_get_attached_object_settings().
panel_toplevel_get_auto_hide()
gboolean panel_toplevel_get_auto_hide (PanelToplevel * toplevel)
Definition at line 5437 of file panel-toplevel.c.
References FALSE, PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_get_auto_hide_size()
int panel_toplevel_get_auto_hide_size (PanelToplevel * toplevel)
Definition at line 5208 of file panel-toplevel.c.
References DEFAULT_AUTO_HIDE_SIZE, PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_get_description()
const char * panel_toplevel_get_description (PanelToplevel * toplevel)
Definition at line 4960 of file panel-toplevel.c.
References NULL, PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_get_enable_arrows()
gboolean panel_toplevel_get_enable_arrows (PanelToplevel * toplevel)
Definition at line 5577 of file panel-toplevel.c.
References FALSE, PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_get_enable_buttons()
gboolean panel_toplevel_get_enable_buttons (PanelToplevel * toplevel)
Definition at line 5551 of file panel-toplevel.c.
References FALSE, PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_get_expand()
gboolean panel_toplevel_get_expand (PanelToplevel * toplevel)
Definition at line 5013 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, _PanelToplevel::priv, and TRUE.
Referenced by panel_is_applet_right_stick(), panel_profile_can_be_moved_freely(), and wayland_panel_toplevel_update_placement().
panel_toplevel_get_hide_delay()
int panel_toplevel_get_hide_delay (PanelToplevel * toplevel)
Definition at line 5459 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_get_is_attached()
gboolean panel_toplevel_get_is_attached (PanelToplevel * toplevel)
Definition at line 2816 of file panel-toplevel.c.
References FALSE, PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
Referenced by panel_deletion_dialog(), panel_profile_get_attached_custom_icon(), panel_profile_get_attached_tooltip(), panel_profile_is_writable_attached_custom_icon(), panel_profile_is_writable_attached_tooltip(), panel_toplevel_is_last_unattached(), and panel_widget_focus().
panel_toplevel_get_is_floating()
gboolean panel_toplevel_get_is_floating (PanelToplevel * toplevel)
Definition at line 5021 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, _PanelToplevel::priv, and TRUE.
panel_toplevel_get_is_hidden()
gboolean panel_toplevel_get_is_hidden (PanelToplevel * toplevel)
Definition at line 5625 of file panel-toplevel.c.
References FALSE, PANEL_IS_TOPLEVEL, PANEL_STATE_HIDDEN_DOWN, PANEL_STATE_HIDDEN_LEFT, PANEL_STATE_HIDDEN_RIGHT, PANEL_STATE_HIDDEN_UP, _PanelToplevel::priv, and TRUE.
Referenced by panel_widget_reparent().
panel_toplevel_get_maximum_size()
int panel_toplevel_get_maximum_size (PanelToplevel * toplevel)
Definition at line 5646 of file panel-toplevel.c.
References MAXIMUM_SIZE_SCREEN_RATIO, PANEL_HORIZONTAL_MASK, and _PanelToplevel::priv.
panel_toplevel_get_minimum_size()
int panel_toplevel_get_minimum_size (PanelToplevel * toplevel)
Definition at line 5639 of file panel-toplevel.c.
References _PanelToplevel::priv.
panel_toplevel_get_monitor()
int panel_toplevel_get_monitor (PanelToplevel * toplevel)
Definition at line 5405 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
Referenced by panel_toplevel_attach_to_widget().
panel_toplevel_get_name()
const char * panel_toplevel_get_name (PanelToplevel * toplevel)
Definition at line 4953 of file panel-toplevel.c.
References NULL, PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_get_orientation()
PanelOrientation panel_toplevel_get_orientation (PanelToplevel * toplevel)
Definition at line 5147 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, PANEL_ORIENTATION_TOP, and _PanelToplevel::priv.
Referenced by panel_menu_button_popup_menu(), panel_widget_get_applet_orientation(), and wayland_panel_toplevel_update_placement().
panel_toplevel_get_panel_widget()
PanelWidget * panel_toplevel_get_panel_widget (PanelToplevel * toplevel)
Definition at line 4898 of file panel-toplevel.c.
References NULL, PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
Referenced by drawer_query_deletion(), mate_panel_applet_register(), orientation_change(), panel_delete(), and panel_setup().
panel_toplevel_get_position()
void panel_toplevel_get_position (PanelToplevel * toplevel, int * x, int * x_right, int * y, int * y_bottom)
Definition at line 5292 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_get_size()
int panel_toplevel_get_size (PanelToplevel * toplevel)
Definition at line 5176 of file panel-toplevel.c.
References DEFAULT_SIZE, PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_get_state()
PanelState panel_toplevel_get_state (PanelToplevel * toplevel)
Definition at line 5617 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_get_unhide_delay()
int panel_toplevel_get_unhide_delay (PanelToplevel * toplevel)
Definition at line 5481 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_get_x_centered()
gboolean panel_toplevel_get_x_centered (PanelToplevel * toplevel)
Definition at line 5314 of file panel-toplevel.c.
References FALSE, PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_get_y_centered()
gboolean panel_toplevel_get_y_centered (PanelToplevel * toplevel)
Definition at line 5322 of file panel-toplevel.c.
References FALSE, PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_hide()
void panel_toplevel_hide (PanelToplevel * toplevel, gboolean auto_hide, gint direction)
Definition at line 3714 of file panel-toplevel.c.
References HIDE_SIGNAL, PANEL_HORIZONTAL_MASK, PANEL_IS_TOPLEVEL, PANEL_STATE_AUTO_HIDDEN, PANEL_STATE_HIDDEN_DOWN, PANEL_STATE_HIDDEN_LEFT, PANEL_STATE_HIDDEN_RIGHT, PANEL_STATE_HIDDEN_UP, PANEL_STATE_NORMAL, panel_toplevel_pop_autohide_disabler(), PANEL_VERTICAL_MASK, and _PanelToplevel::priv.
Referenced by panel_toplevel_set_auto_hide_size().
panel_toplevel_is_last_unattached()
gboolean panel_toplevel_is_last_unattached (PanelToplevel * toplevel)
Definition at line 317 of file panel-toplevel.c.
References FALSE, panel_toplevel_get_is_attached(), and TRUE.
panel_toplevel_list_toplevels()
GSList * panel_toplevel_list_toplevels (void)
Definition at line 311 of file panel-toplevel.c.
Referenced by panel_profile_get_toplevel_by_id(), and panel_shell_quit().
panel_toplevel_pop_autohide_disabler()
void panel_toplevel_pop_autohide_disabler (PanelToplevel * toplevel)
Definition at line 1126 of file panel-toplevel.c.
References NULL, panel_toplevel_queue_auto_hide(), and _PanelToplevel::priv.
Referenced by panel_toplevel_detach(), panel_toplevel_hide(), and panel_widget_applet_drag_end().
panel_toplevel_push_autohide_disabler()
void panel_toplevel_push_autohide_disabler (PanelToplevel * toplevel)
Definition at line 1118 of file panel-toplevel.c.
References NULL, panel_toplevel_queue_auto_hide(), and _PanelToplevel::priv.
Referenced by panel_deletion_dialog(), panel_menu_button_popup_menu(), panel_toplevel_attach_to_widget(), panel_toplevel_unhide(), and panel_widget_applet_drag_start().
panel_toplevel_queue_auto_hide()
void panel_toplevel_queue_auto_hide (PanelToplevel * toplevel)
Definition at line 3876 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, PANEL_STATE_NORMAL, and _PanelToplevel::priv.
Referenced by panel_toplevel_pop_autohide_disabler(), panel_toplevel_push_autohide_disabler(), and panel_toplevel_set_auto_hide().
panel_toplevel_queue_auto_unhide()
void panel_toplevel_queue_auto_unhide (PanelToplevel * toplevel)
Definition at line 3905 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, PANEL_STATE_AUTO_HIDDEN, and _PanelToplevel::priv.
Referenced by panel_toplevel_set_auto_hide().
panel_toplevel_queue_initial_unhide()
void panel_toplevel_queue_initial_unhide (PanelToplevel * toplevel)
Definition at line 3931 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_rotate()
void panel_toplevel_rotate (PanelToplevel * toplevel, gboolean clockwise)
Definition at line 5585 of file panel-toplevel.c.
References PANEL_ORIENTATION_LEFT, PANEL_ORIENTATION_TOP, panel_toplevel_set_orientation(), and _PanelToplevel::priv.
panel_toplevel_set_animate()
void panel_toplevel_set_animate (PanelToplevel * toplevel, gboolean animate)
Definition at line 5489 of file panel-toplevel.c.
References FALSE, PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_set_animation_speed()
void panel_toplevel_set_animation_speed (PanelToplevel * toplevel, PanelAnimationSpeed animation_speed)
Definition at line 5513 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_set_auto_hide()
void panel_toplevel_set_auto_hide (PanelToplevel * toplevel, gboolean auto_hide)
Definition at line 5413 of file panel-toplevel.c.
References FALSE, PANEL_IS_TOPLEVEL, panel_toplevel_queue_auto_hide(), panel_toplevel_queue_auto_unhide(), and _PanelToplevel::priv.
panel_toplevel_set_auto_hide_size()
void panel_toplevel_set_auto_hide_size (PanelToplevel * toplevel, int auto_hide_size)
Definition at line 5184 of file panel-toplevel.c.
References FALSE, PANEL_IS_TOPLEVEL, PANEL_STATE_AUTO_HIDDEN, panel_toplevel_hide(), panel_toplevel_unhide(), _PanelToplevel::priv, and TRUE.
panel_toplevel_set_enable_arrows()
void panel_toplevel_set_enable_arrows (PanelToplevel * toplevel, gboolean enable_arrows)
Definition at line 5559 of file panel-toplevel.c.
References FALSE, PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_set_enable_buttons()
void panel_toplevel_set_enable_buttons (PanelToplevel * toplevel, gboolean enable_buttons)
Definition at line 5535 of file panel-toplevel.c.
References FALSE, and _PanelToplevel::priv.
panel_toplevel_set_expand()
void panel_toplevel_set_expand (PanelToplevel * toplevel, gboolean expand)
Definition at line 4968 of file panel-toplevel.c.
References FALSE, PANEL_IS_TOPLEVEL, PANEL_ORIENTATION_BOTTOM, PANEL_ORIENTATION_LEFT, PANEL_ORIENTATION_RIGHT, PANEL_ORIENTATION_TOP, panel_toplevel_set_x(), panel_toplevel_set_y(), panel_widget_set_packed(), _PanelToplevel::priv, and TRUE.
Referenced by panel_toplevel_attach_to_widget().
panel_toplevel_set_hide_delay()
void panel_toplevel_set_hide_delay (PanelToplevel * toplevel, int hide_delay)
Definition at line 5445 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_set_monitor()
void panel_toplevel_set_monitor (PanelToplevel * toplevel, int monitor)
Definition at line 5383 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, panel_multimonitor_monitors(), _PanelToplevel::priv, and TRUE.
Referenced by panel_toplevel_attach_to_widget().
panel_toplevel_set_name()
void panel_toplevel_set_name (PanelToplevel * toplevel, const char * name)
Definition at line 4923 of file panel-toplevel.c.
References name, NULL, PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_set_orientation()
void panel_toplevel_set_orientation (PanelToplevel * toplevel, PanelOrientation orientation)
Definition at line 5029 of file panel-toplevel.c.
References FALSE, PANEL_HORIZONTAL_MASK, PANEL_IS_TOPLEVEL, PANEL_STATE_HIDDEN_DOWN, PANEL_STATE_HIDDEN_LEFT, PANEL_STATE_HIDDEN_RIGHT, PANEL_STATE_HIDDEN_UP, PANEL_VERTICAL_MASK, panel_widget_set_orientation(), _PanelToplevel::priv, TRUE, and wayland_panel_toplevel_update_placement().
Referenced by panel_toplevel_rotate().
panel_toplevel_set_settings_path()
void panel_toplevel_set_settings_path (PanelToplevel * toplevel, const char * settings_path)
Definition at line 4947 of file panel-toplevel.c.
References _PanelToplevel::priv.
Referenced by panel_profile_load_toplevel().
panel_toplevel_set_size()
void panel_toplevel_set_size (PanelToplevel * toplevel, int size)
Definition at line 5155 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, panel_widget_set_size(), and _PanelToplevel::priv.
panel_toplevel_set_unhide_delay()
void panel_toplevel_set_unhide_delay (PanelToplevel * toplevel, int unhide_delay)
Definition at line 5467 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, and _PanelToplevel::priv.
panel_toplevel_set_x()
void panel_toplevel_set_x (PanelToplevel * toplevel, int x, int x_right, gboolean x_centered)
Definition at line 5216 of file panel-toplevel.c.
References FALSE, PANEL_IS_TOPLEVEL, _PanelToplevel::priv, and TRUE.
Referenced by panel_toplevel_set_expand().
panel_toplevel_set_y()
void panel_toplevel_set_y (PanelToplevel * toplevel, int y, int y_bottom, gboolean y_centered)
Definition at line 5254 of file panel-toplevel.c.
References FALSE, PANEL_IS_TOPLEVEL, _PanelToplevel::priv, and TRUE.
Referenced by panel_toplevel_set_expand().
panel_toplevel_unhide()
void panel_toplevel_unhide (PanelToplevel * toplevel)
Definition at line 3806 of file panel-toplevel.c.
References PANEL_IS_TOPLEVEL, PANEL_STATE_NORMAL, panel_toplevel_push_autohide_disabler(), _PanelToplevel::priv, and UNHIDE_SIGNAL.
Referenced by panel_toplevel_set_auto_hide_size().
panel_toplevel_update_edges()
void panel_toplevel_update_edges (PanelToplevel * toplevel)
Definition at line 1576 of file panel-toplevel.c.
References FALSE, PANEL_EDGE_BOTTOM, PANEL_EDGE_LEFT, PANEL_EDGE_NONE, PANEL_EDGE_RIGHT, PANEL_EDGE_TOP, panel_frame_set_edges(), PANEL_HORIZONTAL_MASK, PANEL_VERTICAL_MASK, _PanelToplevel::priv, and TRUE.