MATE Desktop Environment: panel-applet-frame-dbus.c File Reference
panel-applet-frame-dbus.c File Reference
#include <config.h>
#include <string.h>
#include <panel-applet-frame.h>
#include <panel-applets-manager.h>
#include "panel-applet-container.h"
#include "panel-applet-frame-dbus.h"
Enumerations
enum MatePanelAppletFlags { APPLET_FLAGS_NONE = 0 , APPLET_EXPAND_MAJOR = 1 << 0 , APPLET_EXPAND_MINOR = 1 << 1 , APPLET_HAS_HANDLE = 1 << 2 }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (MatePanelAppletFrameDBus, mate_panel_applet_frame_dbus, PANEL_TYPE_APPLET_FRAME)
gboolean mate_panel_applet_frame_dbus_load (const gchar *iid, MatePanelAppletFrameActivating *frame_act)
Enumeration Type Documentation
MatePanelAppletFlags
enum MatePanelAppletFlags
Enumerator
APPLET_FLAGS_NONE
APPLET_EXPAND_MAJOR
APPLET_EXPAND_MINOR
APPLET_HAS_HANDLE
Definition at line 46 of file panel-applet-frame-dbus.c.
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (MatePanelAppletFrameDBus , mate_panel_applet_frame_dbus , PANEL_TYPE_APPLET_FRAME)
Definition at line 53 of file panel-applet-frame-dbus.c.
References PANEL_ORIENTATION_BOTTOM, PANEL_ORIENTATION_LEFT, PANEL_ORIENTATION_RIGHT, PANEL_ORIENTATION_TOP, and PANEL_TYPE_APPLET_FRAME.
mate_panel_applet_frame_dbus_load()
gboolean mate_panel_applet_frame_dbus_load (const gchar * iid, MatePanelAppletFrameActivating * frame_act)
Definition at line 405 of file panel-applet-frame-dbus.c.
References _mate_panel_applet_frame_set_iid(), FALSE, mate_panel_applet_container_add(), MATE_PANEL_APPLET_FRAME, mate_panel_applet_frame_activating_get_conf_path(), mate_panel_applet_frame_activating_get_locked(), mate_panel_applet_frame_activating_get_locked_down(), mate_panel_applet_frame_activating_get_orientation(), mate_panel_applet_frame_activating_get_size(), mate_panel_applets_manager_factory_activate(), NULL, panel_applet_frame_activating_get_screen(), PANEL_TYPE_APPLET_FRAME_DBUS, _MatePanelAppletFrameDBus::priv, and TRUE.