MATE Desktop Environment: panel-list.c File Reference
panel-list.c File Reference
#include <glib.h>
#include "panel-list.h"
Functions
GList * panel_g_list_insert_before (GList *list, GList *sibling, GList *link)
GList * panel_g_list_insert_after (GList *list, GList *sibling, GList *link)
GList * panel_g_list_swap_next (GList *list, GList *dl)
GList * panel_g_list_swap_prev (GList *list, GList *dl)
GList * panel_g_list_resort_item (GList *list, gpointer data, GCompareFunc func)
GSList * panel_g_slist_make_unique (GSList *list, GCompareFunc compare, gboolean free_data)
Function Documentation
panel_g_list_insert_after()
GList * panel_g_list_insert_after (GList * list, GList * sibling, GList * link)
Definition at line 69 of file panel-list.c.
References NULL.
panel_g_list_insert_before()
GList * panel_g_list_insert_before (GList * list, GList * sibling, GList * link)
Definition at line 35 of file panel-list.c.
References NULL.
panel_g_list_resort_item()
GList * panel_g_list_resort_item (GList * list, gpointer data, GCompareFunc func)
Definition at line 157 of file panel-list.c.
References data, NULL, panel_g_list_swap_next(), and panel_g_list_swap_prev().
panel_g_list_swap_next()
GList * panel_g_list_swap_next (GList * list, GList * dl)
Definition at line 97 of file panel-list.c.
Referenced by panel_g_list_resort_item().
panel_g_list_swap_prev()
GList * panel_g_list_swap_prev (GList * list, GList * dl)
Definition at line 126 of file panel-list.c.
Referenced by panel_g_list_resort_item().
panel_g_slist_make_unique()
GSList * panel_g_slist_make_unique (GSList * list, GCompareFunc compare, gboolean free_data)
Definition at line 184 of file panel-list.c.
References compare, and NULL.