MATE Desktop Environment: panel-menu-items.c File Reference
panel-menu-items.c File Reference
#include <config.h>
#include "panel-menu-items.h"
#include <string.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <libmate-desktop/mate-gsettings.h>
#include <libmate-desktop/mate-image-menu-item.h>
#include <libpanel-util/panel-error.h>
#include <libpanel-util/panel-glib.h>
#include <libpanel-util/panel-keyfile.h>
#include <libpanel-util/panel-launch.h>
#include <libpanel-util/panel-show.h>
#include "menu.h"
#include "panel-action-button.h"
#include "panel-globals.h"
#include "panel-icon-names.h"
#include "panel-lockdown.h"
#include "panel-recent.h"
#include "panel-stock-icons.h"
#include "panel-util.h"
#include "panel-schemas.h"
Macros
#define MAX_BOOKMARK_ITEMS 100
#define N_MENU_ITEM_SIGNALS 9
Enumerations
enum PanelGioItemType { PANEL_GIO_DRIVE , PANEL_GIO_VOLUME , PANEL_GIO_MOUNT }
Functions
GtkWidget * panel_place_menu_item_new (gboolean use_image)
GtkWidget * panel_desktop_menu_item_new (gboolean use_image, gboolean append_lock_logout)
void panel_place_menu_item_set_panel (GtkWidget *item, PanelWidget *panel)
void panel_desktop_menu_item_set_panel (GtkWidget *item, PanelWidget *panel)
void panel_menu_items_append_lock_logout (GtkWidget *menu)
void panel_menu_item_activate_desktop_file (GtkWidget *menuitem, const char *path)
Macro Definition Documentation
MAX_BOOKMARK_ITEMS
#define MAX_BOOKMARK_ITEMS 100
Definition at line 62 of file panel-menu-items.c.
N_MENU_ITEM_SIGNALS
#define N_MENU_ITEM_SIGNALS 9
Definition at line 63 of file panel-menu-items.c.
Enumeration Type Documentation
PanelGioItemType
enum PanelGioItemType
Enumerator
PANEL_GIO_DRIVE
PANEL_GIO_VOLUME
PANEL_GIO_MOUNT
Definition at line 749 of file panel-menu-items.c.
Function Documentation
panel_desktop_menu_item_new()
GtkWidget * panel_desktop_menu_item_new (gboolean use_image, gboolean append_lock_logout)
Definition at line 1467 of file panel-menu-items.c.
References _, FALSE, NULL, panel_lockdown_notify_add(), panel_menu_icon_get_size(), PANEL_TYPE_DESKTOP_MENU_ITEM, _PanelDesktopMenuItem::priv, and setup_menuitem().
panel_desktop_menu_item_set_panel()
void panel_desktop_menu_item_set_panel (GtkWidget * item, PanelWidget * panel)
Definition at line 1514 of file panel-menu-items.c.
References item, mate_panel_applet_menu_set_recurse(), PANEL_DESKTOP_MENU_ITEM, and _PanelDesktopMenuItem::priv.
panel_menu_item_activate_desktop_file()
void panel_menu_item_activate_desktop_file (GtkWidget * menuitem, const char * path)
Definition at line 1617 of file panel-menu-items.c.
References menuitem_to_screen(), NULL, and panel_launch_desktop_file().
panel_menu_items_append_lock_logout()
void panel_menu_items_append_lock_logout (GtkWidget * menu)
Definition at line 1527 of file panel-menu-items.c.
References _, add_menu_separator(), C_, FALSE, item, label, NULL, PANEL_ACTION_LOCK, PANEL_ACTION_LOGOUT, PANEL_ACTION_SHUTDOWN, panel_lock_screen_action_available(), panel_lockdown_get_disable_log_out(), and TRUE.
panel_place_menu_item_new()
GtkWidget * panel_place_menu_item_new (gboolean use_image)
Definition at line 1440 of file panel-menu-items.c.
References _, FALSE, NULL, PANEL_ICON_FOLDER, panel_menu_icon_get_size(), PANEL_TYPE_PLACE_MENU_ITEM, _PanelPlaceMenuItem::priv, and setup_menuitem().
panel_place_menu_item_set_panel()
void panel_place_menu_item_set_panel (GtkWidget * item, PanelWidget * panel)
Definition at line 1501 of file panel-menu-items.c.
References item, mate_panel_applet_menu_set_recurse(), PANEL_PLACE_MENU_ITEM, and _PanelPlaceMenuItem::priv.