MATE Desktop Environment: panel-applet-container.c File Reference
panel-applet-container.c File Reference
#include <config.h>
#include <string.h>
#include <gtk/gtk.h>
#include <panel-applets-manager.h>
#include "panel-applet-container.h"
#include "panel-marshal.h"
Macros
#define MATE_PANEL_APPLET_BUS_NAME "org.mate.panel.applet.%s"
#define MATE_PANEL_APPLET_FACTORY_INTERFACE "org.mate.panel.applet.AppletFactory"
#define MATE_PANEL_APPLET_FACTORY_OBJECT_PATH "/org/mate/panel/applet/%s"
#define MATE_PANEL_APPLET_INTERFACE "org.mate.panel.applet.Applet"
Enumerations
enum {
APPLET_BROKEN , APPLET_MOVE , APPLET_REMOVE , APPLET_LOCK ,
CHILD_PROPERTY_CHANGED , LAST_SIGNAL
}
Functions
G_DEFINE_TYPE_WITH_PRIVATE (MatePanelAppletContainer, mate_panel_applet_container, GTK_TYPE_EVENT_BOX)
GQuark mate_panel_applet_container_error_quark (void)
GtkWidget * mate_panel_applet_container_new (void)
void mate_panel_applet_container_add (MatePanelAppletContainer *container, GdkScreen *screen, const gchar *iid, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data, GVariant *properties)
gboolean mate_panel_applet_container_add_finish (MatePanelAppletContainer *container, GAsyncResult *result, GError **error)
gconstpointer mate_panel_applet_container_child_set (MatePanelAppletContainer *container, const gchar *property_name, const GVariant *value, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean mate_panel_applet_container_child_set_finish (MatePanelAppletContainer *container, GAsyncResult *result, GError **error)
gconstpointer mate_panel_applet_container_child_get (MatePanelAppletContainer *container, const gchar *property_name, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
GVariant * mate_panel_applet_container_child_get_finish (MatePanelAppletContainer *container, GAsyncResult *result, GError **error)
void mate_panel_applet_container_child_popup_menu (MatePanelAppletContainer *container, guint button, guint32 timestamp, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean mate_panel_applet_container_child_popup_menu_finish (MatePanelAppletContainer *container, GAsyncResult *result, GError **error)
void mate_panel_applet_container_cancel_operation (MatePanelAppletContainer *container, gconstpointer operation)
Macro Definition Documentation
MATE_PANEL_APPLET_BUS_NAME
#define MATE_PANEL_APPLET_BUS_NAME "org.mate.panel.applet.%s"
Definition at line 79 of file panel-applet-container.c.
MATE_PANEL_APPLET_FACTORY_INTERFACE
#define MATE_PANEL_APPLET_FACTORY_INTERFACE "org.mate.panel.applet.AppletFactory"
Definition at line 80 of file panel-applet-container.c.
MATE_PANEL_APPLET_FACTORY_OBJECT_PATH
#define MATE_PANEL_APPLET_FACTORY_OBJECT_PATH "/org/mate/panel/applet/%s"
Definition at line 81 of file panel-applet-container.c.
MATE_PANEL_APPLET_INTERFACE
#define MATE_PANEL_APPLET_INTERFACE "org.mate.panel.applet.Applet"
Definition at line 82 of file panel-applet-container.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
APPLET_BROKEN
APPLET_MOVE
APPLET_REMOVE
APPLET_LOCK
CHILD_PROPERTY_CHANGED
LAST_SIGNAL
Definition at line 52 of file panel-applet-container.c.
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (MatePanelAppletContainer , mate_panel_applet_container , GTK_TYPE_EVENT_BOX)
mate_panel_applet_container_add()
void mate_panel_applet_container_add (MatePanelAppletContainer * container, GdkScreen * screen, const gchar * iid, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data, GVariant * properties)
Definition at line 546 of file panel-applet-container.c.
References NULL, PANEL_IS_APPLET_CONTAINER, and user_data.
Referenced by mate_panel_applet_frame_dbus_load().
mate_panel_applet_container_add_finish()
gboolean mate_panel_applet_container_add_finish (MatePanelAppletContainer * container, GAsyncResult * result, GError ** error)
Definition at line 564 of file panel-applet-container.c.
References error, and FALSE.
mate_panel_applet_container_cancel_operation()
void mate_panel_applet_container_cancel_operation (MatePanelAppletContainer * container, gconstpointer operation)
Definition at line 827 of file panel-applet-container.c.
References NULL, and _MatePanelAppletContainer::priv.
mate_panel_applet_container_child_get()
gconstpointer mate_panel_applet_container_child_get (MatePanelAppletContainer * container, const gchar * property_name, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 704 of file panel-applet-container.c.
References mate_panel_applet_container_child_get(), NULL, _MatePanelAppletContainer::priv, proxy, and user_data.
Referenced by mate_panel_applet_container_child_get(), and mate_panel_applet_container_child_get_finish().
mate_panel_applet_container_child_get_finish()
GVariant * mate_panel_applet_container_child_get_finish (MatePanelAppletContainer * container, GAsyncResult * result, GError ** error)
Definition at line 752 of file panel-applet-container.c.
References error, mate_panel_applet_container_child_get(), and NULL.
mate_panel_applet_container_child_popup_menu()
void mate_panel_applet_container_child_popup_menu (MatePanelAppletContainer * container, guint button, guint32 timestamp, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 785 of file panel-applet-container.c.
References mate_panel_applet_container_child_popup_menu(), MATE_PANEL_APPLET_INTERFACE, NULL, _MatePanelAppletContainer::priv, proxy, and user_data.
Referenced by mate_panel_applet_container_child_popup_menu(), and mate_panel_applet_container_child_popup_menu_finish().
mate_panel_applet_container_child_popup_menu_finish()
gboolean mate_panel_applet_container_child_popup_menu_finish (MatePanelAppletContainer * container, GAsyncResult * result, GError ** error)
Definition at line 817 of file panel-applet-container.c.
References error, FALSE, and mate_panel_applet_container_child_popup_menu().
mate_panel_applet_container_child_set()
gconstpointer mate_panel_applet_container_child_set (MatePanelAppletContainer * container, const gchar * property_name, const GVariant * value, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 605 of file panel-applet-container.c.
References mate_panel_applet_container_child_set(), MATE_PANEL_APPLET_CONTAINER_ERROR, MATE_PANEL_APPLET_CONTAINER_INVALID_CHILD_PROPERTY, NULL, _MatePanelAppletContainer::priv, proxy, and user_data.
Referenced by mate_panel_applet_container_child_set(), and mate_panel_applet_container_child_set_finish().
mate_panel_applet_container_child_set_finish()
gboolean mate_panel_applet_container_child_set_finish (MatePanelAppletContainer * container, GAsyncResult * result, GError ** error)
Definition at line 661 of file panel-applet-container.c.
References error, FALSE, and mate_panel_applet_container_child_set().
mate_panel_applet_container_error_quark()
GQuark mate_panel_applet_container_error_quark (void)
Definition at line 90 of file panel-applet-container.c.
mate_panel_applet_container_new()
GtkWidget * mate_panel_applet_container_new (void)
Definition at line 254 of file panel-applet-container.c.
References NULL, and PANEL_TYPE_APPLET_CONTAINER.