MATE Desktop Environment: panel-config-global.c File Reference
panel-config-global.c File Reference
#include <config.h>
#include "panel-config-global.h"
#include <string.h>
#include <gio/gio.h>
#include "panel-globals.h"
Functions
gboolean panel_global_config_get_highlight_when_over (void)
gboolean panel_global_config_get_enable_animations (void)
gboolean panel_global_config_get_drawer_auto_close (void)
gboolean panel_global_config_get_tooltips_enabled (void)
gboolean panel_global_config_get_confirm_panel_remove (void)
void panel_global_config_load (void)
Function Documentation
panel_global_config_get_confirm_panel_remove()
gboolean panel_global_config_get_confirm_panel_remove (void)
Definition at line 82 of file panel-config-global.c.
References TRUE.
Referenced by drawer_query_deletion(), and panel_delete().
panel_global_config_get_drawer_auto_close()
gboolean panel_global_config_get_drawer_auto_close (void)
Definition at line 66 of file panel-config-global.c.
References TRUE.
panel_global_config_get_enable_animations()
gboolean panel_global_config_get_enable_animations (void)
Definition at line 58 of file panel-config-global.c.
References TRUE.
panel_global_config_get_highlight_when_over()
gboolean panel_global_config_get_highlight_when_over (void)
Definition at line 50 of file panel-config-global.c.
References TRUE.
panel_global_config_get_tooltips_enabled()
gboolean panel_global_config_get_tooltips_enabled (void)
Definition at line 74 of file panel-config-global.c.
References TRUE.
panel_global_config_load()
void panel_global_config_load (void)
Definition at line 125 of file panel-config-global.c.
References NULL, and TRUE.
Referenced by main().