MATE Desktop Environment: panel.c File Reference
panel.c File Reference
#include <config.h>
#include <string.h>
#include <signal.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <libpanel-util/panel-glib.h>
#include <libpanel-util/panel-gtk.h>
#include "panel.h"
#include "applet.h"
#include "drawer.h"
#include "button-widget.h"
#include "launcher.h"
#include "panel-context-menu.h"
#include "panel-util.h"
#include "panel-config-global.h"
#include "panel-profile.h"
#include "panel-applet-frame.h"
#include "panel-action-button.h"
#include "panel-menu-bar.h"
#include "panel-separator.h"
#include "panel-toplevel.h"
#include "panel-menu-button.h"
#include "panel-globals.h"
#include "panel-lockdown.h"
#include "panel-icon-names.h"
Enumerations
enum {
TARGET_URL , TARGET_NETSCAPE_URL , TARGET_DIRECTORY , TARGET_COLOR ,
TARGET_APPLET , TARGET_APPLET_INTERNAL , TARGET_ICON_INTERNAL , TARGET_BGIMAGE ,
TARGET_BACKGROUND_RESET
}
enum { RESPONSE_SET_BACKGROUND , RESPONSE_CREATE_LAUNCHER }
Functions
void orientation_change (AppletInfo *info, PanelWidget *panel)
void size_change (AppletInfo *info, PanelWidget *panel)
void back_change (AppletInfo *info, PanelWidget *panel)
gboolean panel_check_dnd_target_data (GtkWidget *widget, GdkDragContext *context, guint *ret_info, GdkAtom *ret_atom)
gboolean panel_check_drop_forbidden (PanelWidget *panel, GdkDragContext *context, guint info, guint time_)
void panel_receive_dnd_data (PanelWidget *panel, guint info, int pos, GtkSelectionData *selection_data, GdkDragContext *context, guint time_)
PanelData * panel_setup (PanelToplevel *toplevel)
GdkScreen * panel_screen_from_panel_widget (PanelWidget *panel)
gboolean panel_is_applet_right_stick (GtkWidget *applet)
GtkWidget * panel_deletion_dialog (PanelToplevel *toplevel)
void panel_delete (PanelToplevel *toplevel)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RESPONSE_SET_BACKGROUND
RESPONSE_CREATE_LAUNCHER
Definition at line 621 of file panel.c.
anonymous enum
anonymous enum
Enumerator
TARGET_URL
TARGET_NETSCAPE_URL
TARGET_DIRECTORY
TARGET_COLOR
TARGET_APPLET
TARGET_APPLET_INTERNAL
TARGET_ICON_INTERNAL
TARGET_BGIMAGE
TARGET_BACKGROUND_RESET
Definition at line 51 of file panel.c.
Function Documentation
back_change()
void back_change (AppletInfo * info, PanelWidget * panel)
Definition at line 156 of file panel.c.
References _PanelToplevel::background, MATE_PANEL_APPLET_FRAME, mate_panel_applet_frame_change_background(), PANEL_MENU_BAR, panel_menu_bar_change_background(), PANEL_OBJECT_APPLET, PANEL_OBJECT_MENU_BAR, PANEL_OBJECT_SEPARATOR, PANEL_SEPARATOR, panel_separator_change_background(), _PanelWidget::toplevel, and _PanelBackground::type.
Referenced by mate_panel_applet_register().
orientation_change()
void orientation_change (AppletInfo * info, PanelWidget * panel)
Definition at line 67 of file panel.c.
References BUTTON_WIDGET, button_widget_set_orientation(), MATE_PANEL_APPLET_FRAME, mate_panel_applet_frame_change_orientation(), PANEL_MENU_BAR, panel_menu_bar_set_orientation(), PANEL_OBJECT_ACTION, PANEL_OBJECT_APPLET, PANEL_OBJECT_DRAWER, PANEL_OBJECT_LAUNCHER, PANEL_OBJECT_MENU, PANEL_OBJECT_MENU_BAR, PANEL_OBJECT_SEPARATOR, PANEL_SEPARATOR, panel_separator_set_orientation(), panel_toplevel_get_panel_widget(), panel_widget_get_applet_orientation(), and Drawer::toplevel.
Referenced by mate_panel_applet_register().
panel_check_dnd_target_data()
gboolean panel_check_dnd_target_data (GtkWidget * widget, GdkDragContext * context, guint * ret_info, GdkAtom * ret_atom)
Definition at line 1041 of file panel.c.
References BUTTON_IS_WIDGET, FALSE, PANEL_IS_TOPLEVEL, and TRUE.
panel_check_drop_forbidden()
gboolean panel_check_drop_forbidden (PanelWidget * panel, GdkDragContext * context, guint info, guint time_)
Definition at line 1103 of file panel.c.
References BUTTON_IS_WIDGET, FALSE, MATE_PANEL_APPLET_FORBIDDEN_PANELS, panel_lockdown_get_locked_down(), TARGET_APPLET_INTERNAL, TARGET_ICON_INTERNAL, and TRUE.
panel_delete()
void panel_delete (PanelToplevel * toplevel)
Definition at line 1545 of file panel.c.
References _PanelWidget::applet_list, panel_global_config_get_confirm_panel_remove(), and panel_toplevel_get_panel_widget().
panel_deletion_dialog()
GtkWidget * panel_deletion_dialog (PanelToplevel * toplevel)
Definition at line 1466 of file panel.c.
References _, panel_toplevel_get_is_attached(), and panel_toplevel_push_autohide_disabler().
Referenced by drawer_query_deletion().
panel_is_applet_right_stick()
gboolean panel_is_applet_right_stick (GtkWidget * applet)
Definition at line 1405 of file panel.c.
References FALSE, PANEL_IS_WIDGET, panel_toplevel_get_expand(), PANEL_WIDGET, panel_widget_is_applet_stuck(), and _PanelWidget::toplevel.
Referenced by mate_panel_applet_save_position().
panel_receive_dnd_data()
void panel_receive_dnd_data (PanelWidget * panel, guint info, int pos, GtkSelectionData * selection_data, GdkDragContext * context, guint time_)
Definition at line 1212 of file panel.c.
References data, FALSE, mate_panel_applet_frame_create(), PANEL_BACK_NONE, PANEL_ICON_FOLDER, panel_lockdown_get_locked_down(), panel_profile_background_key_is_writable(), panel_profile_id_lists_are_writable(), panel_profile_set_background_type(), TARGET_APPLET, TARGET_APPLET_INTERNAL, TARGET_BACKGROUND_RESET, TARGET_BGIMAGE, TARGET_COLOR, TARGET_DIRECTORY, TARGET_ICON_INTERNAL, TARGET_NETSCAPE_URL, TARGET_URL, _PanelWidget::toplevel, and TRUE.
panel_screen_from_panel_widget()
GdkScreen * panel_screen_from_panel_widget (PanelWidget * panel)
Definition at line 1396 of file panel.c.
References NULL, PANEL_IS_TOPLEVEL, PANEL_IS_WIDGET, and _PanelWidget::toplevel.
panel_setup()
PanelData * panel_setup (PanelToplevel * toplevel)
Definition at line 1345 of file panel.c.
References _PanelData::deactivate_idle, _PanelData::insertion_pos, _PanelData::menu, NULL, _PanelData::panel, PANEL_IS_TOPLEVEL, panel_list, panel_lockdown_notify_add(), and panel_toplevel_get_panel_widget().
Referenced by panel_profile_load_toplevel().
size_change()
void size_change (AppletInfo * info, PanelWidget * panel)
Definition at line 131 of file panel.c.
References MATE_PANEL_APPLET_FRAME, mate_panel_applet_frame_change_size(), PANEL_OBJECT_APPLET, and _PanelWidget::sz.
Referenced by mate_panel_applet_register().