MATE Desktop Environment: panel-recent.h File Reference
panel-recent.h File Reference
#include <gtk/gtk.h>
Functions
void panel_recent_append_documents_menu (GtkWidget *menu, GtkRecentManager *manager, int recent_items_limit)
Function Documentation
panel_recent_append_documents_menu()
void panel_recent_append_documents_menu (GtkWidget * menu, GtkRecentManager * manager, int recent_items_limit)
Definition at line 189 of file panel-recent.c.
References _, add_menu_separator(), FALSE, mate_image_menu_item_new(), menu_dummy_button_press_event(), NULL, PANEL_ICON_RECENT, panel_menu_icon_get_size(), panel_util_set_tooltip_text(), setup_menuitem_with_icon(), and TRUE.