MATE Desktop Environment: panel-widget.c File Reference
panel-widget.c File Reference
#include <config.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <libpanel-util/panel-list.h>
#include "applet.h"
#include "panel-widget.h"
#include "button-widget.h"
#include "panel.h"
#include "panel-util.h"
#include "panel-marshal.h"
#include "panel-typebuiltins.h"
#include "panel-applet-frame.h"
#include "panel-globals.h"
#include "panel-profile.h"
#include "panel-lockdown.h"
Macros
#define MOVE_INCREMENT 1
Enumerations
enum PanelMovementType { PANEL_SWITCH_MOVE = 0 , PANEL_FREE_MOVE , PANEL_PUSH_MOVE }
enum {
SIZE_CHANGE_SIGNAL , BACK_CHANGE_SIGNAL , APPLET_MOVE_SIGNAL , APPLET_ADDED_SIGNAL ,
APPLET_REMOVED_SIGNAL , PUSH_MOVE_SIGNAL , SWITCH_MOVE_SIGNAL , FREE_MOVE_SIGNAL ,
TAB_MOVE_SIGNAL , END_MOVE_SIGNAL , POPUP_PANEL_MENU_SIGNAL , LAST_SIGNAL
}
Functions
G_DEFINE_TYPE (PanelWidget, panel_widget, GTK_TYPE_FIXED)
int panel_widget_is_applet_stuck (PanelWidget *panel_widget, GtkWidget *widget)
gboolean panel_widget_is_cursor (PanelWidget *panel, int overlap)
GtkWidget * panel_widget_new (PanelToplevel *toplevel, gboolean packed, GtkOrientation orient, int sz)
void panel_widget_applet_drag_start (PanelWidget *panel, GtkWidget *applet, int drag_off, guint32 time_)
void panel_widget_applet_drag_end (PanelWidget *panel)
int panel_widget_get_cursorloc (PanelWidget *panel)
void panel_widget_add_forbidden (PanelWidget *panel)
int panel_widget_add (PanelWidget *panel, GtkWidget *applet, gboolean locked, int pos, gboolean insert_at_pos)
gboolean panel_widget_reparent (PanelWidget *old_panel, PanelWidget *new_panel, GtkWidget *applet, int pos)
void panel_widget_set_packed (PanelWidget *panel_widget, gboolean packed)
void panel_widget_set_orientation (PanelWidget *panel_widget, GtkOrientation orientation)
void panel_widget_set_size (PanelWidget *panel_widget, int size)
void panel_widget_emit_background_changed (PanelWidget *panel)
void panel_widget_focus (PanelWidget *panel_widget)
PanelOrientation panel_widget_get_applet_orientation (PanelWidget *panel)
void panel_widget_set_applet_size_constrained (PanelWidget *panel, GtkWidget *applet, gboolean size_constrained)
void panel_widget_set_applet_expandable (PanelWidget *panel, GtkWidget *applet, gboolean major, gboolean minor)
void panel_widget_set_applet_size_hints (PanelWidget *panel, GtkWidget *applet, int *size_hints, int size_hints_len)
void panel_widget_set_applet_locked (PanelWidget *panel, GtkWidget *applet, gboolean locked)
gboolean panel_widget_get_applet_locked (PanelWidget *panel, GtkWidget *applet)
gboolean panel_widget_toggle_applet_locked (PanelWidget *panel, GtkWidget *applet)
gboolean mate_panel_applet_is_in_drag (void)
void panel_widget_register_open_dialog (PanelWidget *panel, GtkWidget *dialog)
Macro Definition Documentation
MOVE_INCREMENT
#define MOVE_INCREMENT 1
Definition at line 34 of file panel-widget.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SIZE_CHANGE_SIGNAL
BACK_CHANGE_SIGNAL
APPLET_MOVE_SIGNAL
APPLET_ADDED_SIGNAL
APPLET_REMOVED_SIGNAL
PUSH_MOVE_SIGNAL
SWITCH_MOVE_SIGNAL
FREE_MOVE_SIGNAL
TAB_MOVE_SIGNAL
END_MOVE_SIGNAL
POPUP_PANEL_MENU_SIGNAL
LAST_SIGNAL
Definition at line 44 of file panel-widget.c.
PanelMovementType
enum PanelMovementType
Enumerator
PANEL_SWITCH_MOVE
PANEL_FREE_MOVE
PANEL_PUSH_MOVE
Definition at line 36 of file panel-widget.c.
Function Documentation
G_DEFINE_TYPE()
G_DEFINE_TYPE (PanelWidget , panel_widget , GTK_TYPE_FIXED)
mate_panel_applet_is_in_drag()
gboolean mate_panel_applet_is_in_drag (void)
Definition at line 2918 of file panel-widget.c.
panel_widget_add()
int panel_widget_add (PanelWidget * panel, GtkWidget * applet, gboolean locked, int pos, gboolean insert_at_pos)
Definition at line 2446 of file panel-widget.c.
References _AppletData::applet, APPLET_ADDED_SIGNAL, _PanelWidget::applet_list, _AppletData::cells, _AppletData::constrained, _AppletData::drag_off, _AppletData::expand_major, _AppletData::expand_minor, FALSE, _AppletData::locked, MATE_PANEL_APPLET_DATA, _AppletData::min_cells, NULL, _PanelWidget::orient, _PanelWidget::packed, PANEL_IS_WIDGET, _AppletData::pos, _AppletData::size_constrained, and _AppletData::size_hints.
Referenced by mate_panel_applet_register().
panel_widget_add_forbidden()
void panel_widget_add_forbidden (PanelWidget * panel)
Definition at line 2437 of file panel-widget.c.
References NULL, and PANEL_IS_WIDGET.
Referenced by main().
panel_widget_applet_drag_end()
void panel_widget_applet_drag_end (PanelWidget * panel)
Definition at line 1823 of file panel-widget.c.
References _AppletData::applet, _PanelWidget::currently_dragged_applet, NULL, PANEL_IS_WIDGET, panel_toplevel_pop_autohide_disabler(), and _PanelWidget::toplevel.
Referenced by panel_widget_applet_drag_start().
panel_widget_applet_drag_start()
void panel_widget_applet_drag_start (PanelWidget * panel, GtkWidget * applet, int drag_off, guint32 time_)
Definition at line 1773 of file panel-widget.c.
References FALSE, NULL, PANEL_IS_WIDGET, panel_toplevel_push_autohide_disabler(), panel_widget_applet_drag_end(), and _PanelWidget::toplevel.
Referenced by _mate_panel_applet_frame_applet_move().
panel_widget_emit_background_changed()
void panel_widget_emit_background_changed (PanelWidget * panel)
Definition at line 2633 of file panel-widget.c.
References BACK_CHANGE_SIGNAL.
panel_widget_focus()
void panel_widget_focus (PanelWidget * panel_widget)
Definition at line 2782 of file panel-widget.c.
References NULL, panel_toplevel_get_is_attached(), _PanelWidget::toplevel, and TRUE.
panel_widget_get_applet_locked()
gboolean panel_widget_get_applet_locked (PanelWidget * panel, GtkWidget * applet)
Definition at line 2892 of file panel-widget.c.
References FALSE, _AppletData::locked, and MATE_PANEL_APPLET_DATA.
Referenced by _mate_panel_applet_frame_applet_lock(), mate_panel_applet_create_menu(), mate_panel_applet_frame_sync_menu_state(), and mate_panel_applet_save_position().
panel_widget_get_applet_orientation()
PanelOrientation panel_widget_get_applet_orientation (PanelWidget * panel)
Definition at line 2799 of file panel-widget.c.
References PANEL_IS_TOPLEVEL, PANEL_IS_WIDGET, PANEL_ORIENTATION_TOP, panel_toplevel_get_orientation(), and _PanelWidget::toplevel.
Referenced by mate_panel_applet_frame_activating_get_orientation(), and orientation_change().
panel_widget_get_cursorloc()
int panel_widget_get_cursorloc (PanelWidget * panel)
Definition at line 1846 of file panel-widget.c.
References NULL, _PanelWidget::orient, PANEL_IS_WIDGET, and _PanelWidget::size.
panel_widget_is_applet_stuck()
int panel_widget_is_applet_stuck (PanelWidget * panel_widget, GtkWidget * widget)
Definition at line 628 of file panel-widget.c.
References _PanelWidget::applet_list, _AppletData::cells, FALSE, MATE_PANEL_APPLET_DATA, PANEL_IS_WIDGET, _AppletData::pos, _PanelWidget::size, and TRUE.
Referenced by panel_is_applet_right_stick().
panel_widget_is_cursor()
gboolean panel_widget_is_cursor (PanelWidget * panel, int overlap)
Definition at line 1551 of file panel-widget.c.
References _PanelWidget::drop_widget, FALSE, NULL, PANEL_IS_WIDGET, and TRUE.
panel_widget_new()
GtkWidget * panel_widget_new (PanelToplevel * toplevel, gboolean packed, GtkOrientation orient, int sz)
Definition at line 1675 of file panel-widget.c.
References _PanelWidget::drop_widget, FALSE, NULL, _PanelWidget::orient, _PanelWidget::packed, PANEL_TYPE_WIDGET, _PanelWidget::size, _PanelWidget::sz, _PanelWidget::toplevel, and TRUE.
panel_widget_register_open_dialog()
void panel_widget_register_open_dialog (PanelWidget * panel, GtkWidget * dialog)
Definition at line 2924 of file panel-widget.c.
References FALSE, and _PanelWidget::open_dialogs.
Referenced by _mate_panel_applet_frame_applet_broken(), ask_about_launcher(), and launcher_properties().
panel_widget_reparent()
gboolean panel_widget_reparent (PanelWidget * old_panel, PanelWidget * new_panel, GtkWidget * applet, int pos)
Definition at line 2528 of file panel-widget.c.
References _AppletData::applet, _AppletData::constrained, FALSE, MATE_PANEL_APPLET_DATA, MATE_PANEL_APPLET_FRAME, mate_panel_applet_frame_set_panel(), NULL, PANEL_IS_WIDGET, PANEL_OBJECT_APPLET, panel_toplevel_get_is_hidden(), _AppletData::pos, _PanelWidget::toplevel, and TRUE.
panel_widget_set_applet_expandable()
void panel_widget_set_applet_expandable (PanelWidget * panel, GtkWidget * applet, gboolean major, gboolean minor)
Definition at line 2829 of file panel-widget.c.
References _AppletData::expand_major, _AppletData::expand_minor, FALSE, and MATE_PANEL_APPLET_DATA.
Referenced by _mate_panel_applet_frame_update_flags(), and panel_separator_load_from_gsettings().
panel_widget_set_applet_locked()
void panel_widget_set_applet_locked (PanelWidget * panel, GtkWidget * applet, gboolean locked)
Definition at line 2878 of file panel-widget.c.
References FALSE, _AppletData::locked, and MATE_PANEL_APPLET_DATA.
panel_widget_set_applet_size_constrained()
void panel_widget_set_applet_size_constrained (PanelWidget * panel, GtkWidget * applet, gboolean size_constrained)
Definition at line 2808 of file panel-widget.c.
References FALSE, MATE_PANEL_APPLET_DATA, and _AppletData::size_constrained.
Referenced by _mate_panel_applet_frame_activated(), and panel_separator_load_from_gsettings().
panel_widget_set_applet_size_hints()
void panel_widget_set_applet_size_hints (PanelWidget * panel, GtkWidget * applet, int * size_hints, int size_hints_len)
Definition at line 2853 of file panel-widget.c.
References MATE_PANEL_APPLET_DATA, NULL, _AppletData::size_hints, and _AppletData::size_hints_len.
Referenced by _mate_panel_applet_frame_update_size_hints().
panel_widget_set_orientation()
void panel_widget_set_orientation (PanelWidget * panel_widget, GtkOrientation orientation)
Definition at line 2606 of file panel-widget.c.
References _PanelWidget::orient.
Referenced by panel_toplevel_set_orientation().
panel_widget_set_packed()
void panel_widget_set_packed (PanelWidget * panel_widget, gboolean packed)
Definition at line 2597 of file panel-widget.c.
References FALSE, and _PanelWidget::packed.
Referenced by panel_toplevel_set_expand().
panel_widget_set_size()
void panel_widget_set_size (PanelWidget * panel_widget, int size)
Definition at line 2615 of file panel-widget.c.
References PANEL_IS_WIDGET, SIZE_CHANGE_SIGNAL, and _PanelWidget::sz.
Referenced by panel_toplevel_set_size().
panel_widget_toggle_applet_locked()
gboolean panel_widget_toggle_applet_locked (PanelWidget * panel, GtkWidget * applet)
Definition at line 2905 of file panel-widget.c.
References FALSE, _AppletData::locked, and MATE_PANEL_APPLET_DATA.
Referenced by mate_panel_applet_toggle_locked().