MATE Desktop Environment: panel-action-button.h File Reference
panel-action-button.h File Reference
#include <gtk/gtk.h>
#include "button-widget.h"
#include "panel-widget.h"
#include "panel-enums.h"
Classes
struct _PanelActionButton
struct _PanelActionButtonClass
Macros
#define PANEL_TYPE_ACTION_BUTTON (panel_action_button_get_type ())
#define PANEL_ACTION_BUTTON(o)
#define PANEL_ACTION_BUTTON_CLASS(k)
#define PANEL_IS_ACTION_BUTTON(o)
#define PANEL_IS_ACTION_BUTTON_CLASS(k)
#define PANEL_ACTION_BUTTON_GET_CLASS(o)
Typedefs
typedef struct _PanelActionButton PanelActionButton
typedef struct _PanelActionButtonClass PanelActionButtonClass
typedef struct _PanelActionButtonPrivate PanelActionButtonPrivate
Functions
GType panel_action_button_get_type (void)
void panel_action_button_create (PanelToplevel *toplevel, int position, PanelActionButtonType type)
void panel_action_button_set_type (PanelActionButton *button, PanelActionButtonType type)
void panel_action_button_load_from_gsettings (PanelWidget *panel, gboolean locked, int position, gboolean exactpos, const char *id)
void panel_action_button_invoke_menu (PanelActionButton *button, const char *callback_name)
void panel_action_button_set_dnd_enabled (PanelActionButton *button, gboolean dnd_enabled)
gboolean panel_action_button_load_from_drag (PanelToplevel *toplevel, int position, const char *drag_string, int *old_applet_idx)
gboolean panel_action_get_is_disabled (PanelActionButtonType type)
GCallback panel_action_get_invoke (PanelActionButtonType type)
const char * panel_action_get_icon_name (PanelActionButtonType type)
const char * panel_action_get_text (PanelActionButtonType type)
const char * panel_action_get_tooltip (PanelActionButtonType type)
const char * panel_action_get_drag_id (PanelActionButtonType type)
Macro Definition Documentation
PANEL_ACTION_BUTTON
#define PANEL_ACTION_BUTTON (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), PANEL_TYPE_ACTION_BUTTON, PanelActionButton))
Definition at line 40 of file panel-action-button.h.
PANEL_ACTION_BUTTON_CLASS
#define PANEL_ACTION_BUTTON_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST((k), PANEL_TYPE_ACTION_BUTTON, PanelActionButtonClass))
Definition at line 41 of file panel-action-button.h.
PANEL_ACTION_BUTTON_GET_CLASS
#define PANEL_ACTION_BUTTON_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), PANEL_TYPE_ACTION_BUTTON, PanelActionButtonClass))
Definition at line 44 of file panel-action-button.h.
PANEL_IS_ACTION_BUTTON
#define PANEL_IS_ACTION_BUTTON (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), PANEL_TYPE_ACTION_BUTTON))
Definition at line 42 of file panel-action-button.h.
Referenced by panel_action_button_invoke_menu(), and panel_action_button_set_dnd_enabled().
PANEL_IS_ACTION_BUTTON_CLASS
#define PANEL_IS_ACTION_BUTTON_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), PANEL_TYPE_ACTION_BUTTON))
Definition at line 43 of file panel-action-button.h.
PANEL_TYPE_ACTION_BUTTON
#define PANEL_TYPE_ACTION_BUTTON (panel_action_button_get_type ())
Definition at line 39 of file panel-action-button.h.
Typedef Documentation
PanelActionButton
typedef struct _PanelActionButton PanelActionButton
Definition at line 46 of file panel-action-button.h.
PanelActionButtonClass
typedef struct _PanelActionButtonClass PanelActionButtonClass
Definition at line 47 of file panel-action-button.h.
PanelActionButtonPrivate
typedef struct _PanelActionButtonPrivate PanelActionButtonPrivate
Definition at line 48 of file panel-action-button.h.
Function Documentation
panel_action_button_create()
void panel_action_button_create (PanelToplevel * toplevel, int position, PanelActionButtonType type)
Definition at line 938 of file panel-action-button.c.
References FALSE, PANEL_GSETTINGS_OBJECTS, PANEL_OBJECT_ACTION, PANEL_OBJECT_ACTION_TYPE_KEY, PANEL_OBJECT_PATH, PANEL_OBJECT_SCHEMA, panel_profile_add_to_list(), and panel_profile_prepare_object().
Referenced by panel_action_button_load_from_drag().
panel_action_button_get_type()
GType panel_action_button_get_type (void)
panel_action_button_invoke_menu()
void panel_action_button_invoke_menu (PanelActionButton * button, const char * callback_name)
Definition at line 986 of file panel-action-button.c.
References NULL, PANEL_ACTION_LAST, PANEL_ACTION_NONE, PANEL_IS_ACTION_BUTTON, panel_show_help(), and _PanelActionButton::priv.
panel_action_button_load_from_drag()
gboolean panel_action_button_load_from_drag (PanelToplevel * toplevel, int position, const char * drag_string, int * old_applet_idx)
Definition at line 1013 of file panel-action-button.c.
References FALSE, NULL, panel_action_button_create(), PANEL_ACTION_LAST, PANEL_ACTION_NONE, and TRUE.
panel_action_button_load_from_gsettings()
void panel_action_button_load_from_gsettings (PanelWidget * panel, gboolean locked, int position, gboolean exactpos, const char * id)
Definition at line 963 of file panel-action-button.c.
References PANEL_OBJECT_ACTION_TYPE_KEY, PANEL_OBJECT_PATH, and PANEL_OBJECT_SCHEMA.
panel_action_button_set_dnd_enabled()
void panel_action_button_set_dnd_enabled (PanelActionButton * button, gboolean dnd_enabled)
Definition at line 1054 of file panel-action-button.c.
References FALSE, NULL, PANEL_IS_ACTION_BUTTON, _PanelActionButton::priv, and TRUE.
panel_action_button_set_type()
void panel_action_button_set_type (PanelActionButton * button, PanelActionButtonType type)
Definition at line 833 of file panel-action-button.c.
References _, BUTTON_WIDGET, button_widget_set_icon_name(), NULL, panel_a11y_set_atk_name_desc(), PANEL_ACTION_LAST, PANEL_ACTION_NONE, panel_util_set_tooltip_text(), and _PanelActionButton::priv.
panel_action_get_drag_id()
const char * panel_action_get_drag_id (PanelActionButtonType type)
Definition at line 648 of file panel-action-button.c.
References NULL, PANEL_ACTION_LAST, and PANEL_ACTION_NONE.
Referenced by setup_internal_applet_drag().
panel_action_get_icon_name()
const char * panel_action_get_icon_name (PanelActionButtonType type)
Definition at line 627 of file panel-action-button.c.
References NULL, PANEL_ACTION_LAST, and PANEL_ACTION_NONE.
Referenced by setup_internal_applet_drag().
panel_action_get_invoke()
GCallback panel_action_get_invoke (PanelActionButtonType type)
Definition at line 618 of file panel-action-button.c.
References NULL, PANEL_ACTION_LAST, and PANEL_ACTION_NONE.
panel_action_get_is_disabled()
gboolean panel_action_get_is_disabled (PanelActionButtonType type)
Definition at line 607 of file panel-action-button.c.
References FALSE, PANEL_ACTION_LAST, and PANEL_ACTION_NONE.
panel_action_get_text()
const char * panel_action_get_text (PanelActionButtonType type)
Definition at line 634 of file panel-action-button.c.
References _, NULL, PANEL_ACTION_LAST, and PANEL_ACTION_NONE.
panel_action_get_tooltip()
const char * panel_action_get_tooltip (PanelActionButtonType type)
Definition at line 641 of file panel-action-button.c.
References _, NULL, PANEL_ACTION_LAST, and PANEL_ACTION_NONE.