MATE Desktop Environment: panel-util.c File Reference
panel-util.c File Reference
#include <config.h>
#include "panel-util.h"
#include <dirent.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <glib/gstdio.h>
#include <gio/gio.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gdk/gdk.h>
#include <libmate-desktop/mate-desktop-utils.h>
#include <libmate-desktop/mate-gsettings.h>
#include <libpanel-util/panel-error.h>
#include <libpanel-util/panel-glib.h>
#include <libpanel-util/panel-keyfile.h>
#include <libpanel-util/panel-xdg.h>
#include "applet.h"
#include "panel-config-global.h"
#include "panel-schemas.h"
#include "panel-globals.h"
#include "launcher.h"
#include "panel-icon-names.h"
#include "panel-lockdown.h"
Macros
#define MATE_DESKTOP_USE_UNSTABLE_API
#define NAME_MAX 255
#define LENGTH_FOR_TMPFILE_EXT 7
#define CAIRO_RED 2
#define CAIRO_GREEN 1
#define CAIRO_BLUE 0
Functions
char * panel_util_make_exec_uri_for_desktop (const char *exec)
int panel_find_applet_index (GtkWidget *widget)
void panel_push_window_busy (GtkWidget *window)
void panel_pop_window_busy (GtkWidget *window)
gboolean panel_is_program_in_path (const char *program)
gboolean panel_is_uri_writable (const char *uri)
gboolean panel_uri_exists (const char *uri)
GIcon * panel_gicon_from_icon_name (const char *icon_name)
char * panel_find_icon (GtkIconTheme *icon_theme, const char *icon_name, gint size)
cairo_surface_t * panel_load_icon (GtkIconTheme *icon_theme, const char *icon_name, int size, int desired_width, int desired_height, char **error_msg)
gboolean panel_lock_screen_action_available (const char *action)
void panel_lock_screen_action (GdkScreen *screen, const char *action)
void panel_lock_screen (GdkScreen *screen)
gboolean panel_launcher_is_in_personal_path (const char *location)
GFile * panel_launcher_get_gfile (const char *location)
char * panel_launcher_get_uri (const char *location)
char * panel_launcher_get_filename (const char *location)
char * panel_make_full_path (const char *dir, const char *filename)
char * panel_make_unique_desktop_path_from_name (const char *dir, const char *name)
char * panel_make_unique_desktop_uri (const char *dir, const char *source)
GdkPixbuf * panel_util_cairo_rgbdata_to_pixbuf (unsigned char *data, int width, int height)
char * guess_icon_from_exec (GtkIconTheme *icon_theme, const gchar *exec)
char * panel_util_get_label_for_uri (const char *text_uri)
char * panel_util_get_icon_for_uri (const char *text_uri)
void panel_util_set_tooltip_text (GtkWidget *widget, const char *text)
GFile * panel_util_get_file_optional_homedir (const char *location)
Macro Definition Documentation
CAIRO_BLUE
#define CAIRO_BLUE 0
Referenced by panel_util_cairo_rgbdata_to_pixbuf().
CAIRO_GREEN
#define CAIRO_GREEN 1
Referenced by panel_util_cairo_rgbdata_to_pixbuf().
CAIRO_RED
#define CAIRO_RED 2
Referenced by panel_util_cairo_rgbdata_to_pixbuf().
LENGTH_FOR_TMPFILE_EXT
#define LENGTH_FOR_TMPFILE_EXT 7
Referenced by panel_make_unique_desktop_path_from_name().
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 34 of file panel-util.c.
NAME_MAX
#define NAME_MAX 255
Referenced by panel_make_unique_desktop_path_from_name().
Function Documentation
guess_icon_from_exec()
char * guess_icon_from_exec (GtkIconTheme * icon_theme, const gchar * exec)
Definition at line 771 of file panel-util.c.
References NULL, and panel_find_icon().
panel_find_applet_index()
int panel_find_applet_index (GtkWidget * widget)
Definition at line 83 of file panel-util.c.
References AppletInfo::data, and mate_panel_applet_list_applets().
panel_find_icon()
char * panel_find_icon (GtkIconTheme * icon_theme, const char * icon_name, gint size)
Definition at line 289 of file panel-util.c.
References NULL, panel_find_icon(), and panel_xdg_icon_remove_extension().
Referenced by guess_icon_from_exec(), panel_find_icon(), and panel_load_icon().
panel_gicon_from_icon_name()
GIcon * panel_gicon_from_icon_name (const char * icon_name)
Definition at line 262 of file panel-util.c.
References name, NULL, and panel_xdg_icon_remove_extension().
Referenced by mate_panel_applet_add_callback(), and setup_menuitem_with_icon().
panel_is_program_in_path()
gboolean panel_is_program_in_path (const char * program)
Definition at line 155 of file panel-util.c.
References FALSE, NULL, and TRUE.
Referenced by panel_menu_bar_invoke_menu(), and panel_menu_button_invoke_menu().
panel_is_uri_writable()
gboolean panel_is_uri_writable (const char * uri)
Definition at line 207 of file panel-util.c.
References FALSE, and NULL.
panel_launcher_get_filename()
char * panel_launcher_get_filename (const char * location)
Definition at line 559 of file panel-util.c.
References NULL, and panel_launcher_get_gfile().
Referenced by panel_launcher_create_copy(), and panel_launcher_create_with_id().
panel_launcher_get_gfile()
GFile * panel_launcher_get_gfile (const char * location)
Definition at line 520 of file panel-util.c.
References NULL, and panel_make_full_path().
Referenced by panel_launcher_create_copy(), panel_launcher_delete(), panel_launcher_get_filename(), and panel_launcher_is_in_personal_path().
panel_launcher_get_uri()
char * panel_launcher_get_uri (const char * location)
Definition at line 539 of file panel-util.c.
References NULL, and panel_make_full_path().
panel_launcher_is_in_personal_path()
gboolean panel_launcher_is_in_personal_path (const char * location)
Definition at line 495 of file panel-util.c.
References FALSE, and panel_launcher_get_gfile().
Referenced by panel_launcher_delete().
panel_load_icon()
cairo_surface_t * panel_load_icon (GtkIconTheme * icon_theme, const char * icon_name, int size, int desired_width, int desired_height, char ** error_msg)
Definition at line 334 of file panel-util.c.
References _, error, NULL, panel_find_icon(), and TRUE.
panel_lock_screen()
void panel_lock_screen (GdkScreen * screen)
Definition at line 484 of file panel-util.c.
References panel_lock_screen_action().
panel_lock_screen_action()
void panel_lock_screen_action (GdkScreen * screen, const char * action)
Definition at line 453 of file panel-util.c.
References _, action, error, mate_gdk_spawn_command_line_on_screen(), NULL, panel_error_dialog(), panel_lockdown_get_disable_lock_screen(), and TRUE.
Referenced by panel_lock_screen().
panel_lock_screen_action_available()
gboolean panel_lock_screen_action_available (const char * action)
Definition at line 433 of file panel-util.c.
References action, FALSE, NULL, panel_lockdown_get_disable_lock_screen(), and TRUE.
Referenced by panel_menu_items_append_lock_logout().
panel_make_full_path()
char * panel_make_full_path (const char * dir, const char * filename)
Definition at line 586 of file panel-util.c.
References NULL.
Referenced by panel_launcher_get_gfile(), panel_launcher_get_uri(), and panel_make_unique_desktop_path_from_name().
panel_make_unique_desktop_path_from_name()
char * panel_make_unique_desktop_path_from_name (const char * dir, const char * name)
Definition at line 611 of file panel-util.c.
References LENGTH_FOR_TMPFILE_EXT, name, NAME_MAX, NULL, panel_make_full_path(), and TRUE.
Referenced by panel_make_unique_desktop_uri().
panel_make_unique_desktop_uri()
char * panel_make_unique_desktop_uri (const char * dir, const char * source)
Definition at line 661 of file panel-util.c.
References _, memmove, name, NULL, panel_make_unique_desktop_path_from_name(), and strrchr.
Referenced by panel_launcher_create_copy(), and panel_launcher_create_from_info().
panel_pop_window_busy()
void panel_pop_window_busy (GtkWidget * window)
Definition at line 131 of file panel-util.c.
References NULL, and TRUE.
panel_push_window_busy()
void panel_push_window_busy (GtkWidget * window)
Definition at line 101 of file panel-util.c.
References FALSE, and NULL.
panel_uri_exists()
gboolean panel_uri_exists (const char * uri)
Definition at line 247 of file panel-util.c.
References FALSE, and NULL.
panel_util_cairo_rgbdata_to_pixbuf()
GdkPixbuf * panel_util_cairo_rgbdata_to_pixbuf (unsigned char * data, int width, int height)
Definition at line 715 of file panel-util.c.
References CAIRO_BLUE, CAIRO_GREEN, CAIRO_RED, data, FALSE, and NULL.
panel_util_get_file_optional_homedir()
GFile * panel_util_get_file_optional_homedir (const char * location)
Definition at line 1207 of file panel-util.c.
References NULL.
panel_util_get_icon_for_uri()
char * panel_util_get_icon_for_uri (const char * text_uri)
Definition at line 1107 of file panel-util.c.
References NULL, PANEL_ICON_BURNER, and PANEL_ICON_SAVED_SEARCH.
panel_util_get_label_for_uri()
char * panel_util_get_label_for_uri (const char * text_uri)
Definition at line 1021 of file panel-util.c.
References _, FALSE, label, NULL, and TRUE.
panel_util_make_exec_uri_for_desktop()
char * panel_util_make_exec_uri_for_desktop (const char * exec)
Definition at line 52 of file panel-util.c.
References FALSE, NULL, and strchr.
panel_util_set_tooltip_text()
void panel_util_set_tooltip_text (GtkWidget * widget, const char * text)
Definition at line 1183 of file panel-util.c.
References FALSE, NULL, PANEL_GLIB_STR_EMPTY, and TRUE.
Referenced by panel_action_button_set_type(), panel_menu_button_set_tooltip(), and panel_recent_append_documents_menu().