MATE Desktop Environment: panel-keyfile.c File Reference
panel-keyfile.c File Reference
#include <string.h>
#include <sys/stat.h>
#include <glib.h>
#include <gio/gio.h>
#include "panel-keyfile.h"
Macros
#define KEYFILE_TRUSTED_SHEBANG "#!/usr/bin/env xdg-open\n"
Functions
GKeyFile * panel_key_file_new_desktop (void)
gboolean panel_key_file_to_file (GKeyFile *keyfile, const gchar *file, GError **error)
gboolean panel_key_file_load_from_uri (GKeyFile *keyfile, const gchar *uri, GKeyFileFlags flags, GError **error)
gboolean panel_key_file_copy_and_mark_trusted (const char *source_path, const char *target_path, GError **error)
gboolean panel_key_file_get_boolean (GKeyFile *keyfile, const gchar *key, gboolean default_value)
void panel_key_file_set_locale_string (GKeyFile *keyfile, const gchar *key, const gchar *value)
void panel_key_file_remove_locale_key (GKeyFile *keyfile, const gchar *key)
void panel_key_file_remove_all_locale_key (GKeyFile *keyfile, const gchar *key)
void panel_key_file_ensure_C_key (GKeyFile *keyfile, const char *key)
Macro Definition Documentation
KEYFILE_TRUSTED_SHEBANG
#define KEYFILE_TRUSTED_SHEBANG "#!/usr/bin/env xdg-open\n"
Definition at line 36 of file panel-keyfile.c.
Referenced by panel_key_file_to_file().
Function Documentation
panel_key_file_copy_and_mark_trusted()
gboolean panel_key_file_copy_and_mark_trusted (const char * source_path, const char * target_path, GError ** error)
Definition at line 210 of file panel-keyfile.c.
References error, FALSE, and panel_key_file_to_file().
panel_key_file_ensure_C_key()
void panel_key_file_ensure_C_key (GKeyFile * keyfile, const char * key)
Definition at line 344 of file panel-keyfile.c.
References key, NULL, panel_key_file_get_locale_string, panel_key_file_get_string, and panel_key_file_set_string.
panel_key_file_get_boolean()
gboolean panel_key_file_get_boolean (GKeyFile * keyfile, const gchar * key, gboolean default_value)
Definition at line 234 of file panel-keyfile.c.
References error, key, and NULL.
Referenced by panel_ditem_editor_sync_display().
panel_key_file_load_from_uri()
gboolean panel_key_file_load_from_uri (GKeyFile * keyfile, const gchar * uri, GKeyFileFlags flags, GError ** error)
Definition at line 159 of file panel-keyfile.c.
References error, FALSE, and NULL.
panel_key_file_new_desktop()
GKeyFile * panel_key_file_new_desktop (void)
Definition at line 39 of file panel-keyfile.c.
Referenced by panel_launcher_create_from_info().
panel_key_file_remove_all_locale_key()
void panel_key_file_remove_all_locale_key (GKeyFile * keyfile, const gchar * key)
Definition at line 311 of file panel-keyfile.c.
References key, and NULL.
panel_key_file_remove_locale_key()
void panel_key_file_remove_locale_key (GKeyFile * keyfile, const gchar * key)
Definition at line 279 of file panel-keyfile.c.
References key, NULL, and strchr.
panel_key_file_set_locale_string()
void panel_key_file_set_locale_string (GKeyFile * keyfile, const gchar * key, const gchar * value)
Definition at line 252 of file panel-keyfile.c.
References key, NULL, and strchr.
Referenced by panel_launcher_create_from_info().
panel_key_file_to_file()
gboolean panel_key_file_to_file (GKeyFile * keyfile, const gchar * file, GError ** error)
Definition at line 94 of file panel-keyfile.c.
References data, error, FALSE, KEYFILE_TRUSTED_SHEBANG, and NULL.
Referenced by panel_key_file_copy_and_mark_trusted(), and panel_launcher_create_from_info().