MATE Desktop Environment: panel-run-dialog.c File Reference
panel-run-dialog.c File Reference
#include <config.h>
#include "panel-run-dialog.h"
#include <string.h>
#include <dirent.h>
#include <errno.h>
#include <sys/types.h>
#include <unistd.h>
#include <glib/gi18n.h>
#include <glib.h>
#include <gio/gio.h>
#include <gdk/gdkkeysyms.h>
#include <matemenu-tree.h>
#include <libmate-desktop/mate-desktop-utils.h>
#include <libpanel-util/panel-error.h>
#include <libpanel-util/panel-glib.h>
#include <libpanel-util/panel-gtk.h>
#include <libpanel-util/panel-keyfile.h>
#include <libpanel-util/panel-show.h>
#include "panel-util.h"
#include "panel-globals.h"
#include "panel-enums.h"
#include "panel-profile.h"
#include "panel-schemas.h"
#include "panel-stock-icons.h"
#include "panel-multimonitor.h"
#include "menu.h"
#include "panel-lockdown.h"
#include "panel-icon-names.h"
Macros
#define MATE_DESKTOP_USE_UNSTABLE_API
#define PANEL_RUN_SCHEMA "org.mate.panel"
#define PANEL_RUN_HISTORY_KEY "history-mate-run"
#define PANEL_RUN_HISTORY_MAX_SIZE_KEY "history-max-size-mate-run"
#define PANEL_RUN_HISTORY_REVERSE_KEY "history-reverse-mate-run"
#define PANEL_RUN_SHOW_PROGRAM_LIST_KEY "show-program-list"
Enumerations
enum {
COLUMN_GICON , COLUMN_NAME , COLUMN_ACCELERATOR_MASK , COLUMN_ACCELERATOR_KEY_VALUE ,
COLUMN_COMMENT , COLUMN_PATH , COLUMN_EXEC , COLUMN_VISIBLE ,
NUM_COLUMNS
}
Functions
void panel_run_dialog_present (GdkScreen *screen, guint32 activate_time)
void panel_run_dialog_quit_on_destroy (void)
Variables
const AcceleratorKeyMapping accelerator_key_mapping []
Macro Definition Documentation
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 47 of file panel-run-dialog.c.
PANEL_RUN_HISTORY_KEY
#define PANEL_RUN_HISTORY_KEY "history-mate-run"
Definition at line 146 of file panel-run-dialog.c.
PANEL_RUN_HISTORY_MAX_SIZE_KEY
#define PANEL_RUN_HISTORY_MAX_SIZE_KEY "history-max-size-mate-run"
Definition at line 147 of file panel-run-dialog.c.
PANEL_RUN_HISTORY_REVERSE_KEY
#define PANEL_RUN_HISTORY_REVERSE_KEY "history-reverse-mate-run"
Definition at line 148 of file panel-run-dialog.c.
PANEL_RUN_SCHEMA
#define PANEL_RUN_SCHEMA "org.mate.panel"
Definition at line 145 of file panel-run-dialog.c.
PANEL_RUN_SHOW_PROGRAM_LIST_KEY
#define PANEL_RUN_SHOW_PROGRAM_LIST_KEY "show-program-list"
Definition at line 149 of file panel-run-dialog.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COLUMN_GICON
COLUMN_NAME
COLUMN_ACCELERATOR_MASK
COLUMN_ACCELERATOR_KEY_VALUE
COLUMN_COMMENT
COLUMN_PATH
COLUMN_EXEC
COLUMN_VISIBLE
NUM_COLUMNS
Definition at line 107 of file panel-run-dialog.c.
Function Documentation
panel_run_dialog_present()
void panel_run_dialog_present (GdkScreen * screen, guint32 activate_time)
Definition at line 2117 of file panel-run-dialog.c.
References GETTEXT_PACKAGE, NULL, panel_lockdown_get_disable_command_line(), and PANEL_RESOURCE_PATH.
Referenced by main().
panel_run_dialog_quit_on_destroy()
void panel_run_dialog_quit_on_destroy (void)
Definition at line 2153 of file panel-run-dialog.c.
References NULL.
Referenced by main().
Variable Documentation
accelerator_key_mapping
const AcceleratorKeyMapping accelerator_key_mapping[]
Initial value:
                                                    =
{
        {0, GDK_MOD1_MASK, GDK_KEY_1 },
        {1, GDK_MOD1_MASK, GDK_KEY_2 },
        {2, GDK_MOD1_MASK, GDK_KEY_3 },
        {3, GDK_MOD1_MASK, GDK_KEY_4 },
        {4, GDK_MOD1_MASK, GDK_KEY_5 },
        {5, GDK_MOD1_MASK, GDK_KEY_6 },
        {6, GDK_MOD1_MASK, GDK_KEY_7 },
        {7, GDK_MOD1_MASK, GDK_KEY_8 },
        {8, GDK_MOD1_MASK, GDK_KEY_9 },
        {9, GDK_MOD1_MASK, GDK_KEY_0 },
}
Definition at line 125 of file panel-run-dialog.c.