MATE Desktop Environment: panel-menu-button.h File Reference
panel-menu-button.h File Reference
#include "button-widget.h"
#include "panel-widget.h"
Classes
struct _PanelMenuButton
struct _PanelMenuButtonClass
Macros
#define PANEL_TYPE_MENU_BUTTON (panel_menu_button_get_type ())
#define PANEL_MENU_BUTTON(o)
#define PANEL_MENU_BUTTON_CLASS(k)
#define PANEL_IS_MENU_BUTTON(o)
#define PANEL_IS_MENU_BUTTON_CLASS(k)
#define PANEL_MENU_BUTTON_GET_CLASS(o)
Typedefs
typedef struct _PanelMenuButton PanelMenuButton
typedef struct _PanelMenuButtonClass PanelMenuButtonClass
typedef struct _PanelMenuButtonPrivate PanelMenuButtonPrivate
Functions
GType panel_menu_button_get_type (void)
gboolean panel_menu_button_create (PanelToplevel *toplevel, int position, const char *filename, const char *menu_path, gboolean use_menu_path, const char *tooltip)
void panel_menu_button_set_menu_path (PanelMenuButton *button, const char *menu_path)
void panel_menu_button_set_custom_icon (PanelMenuButton *button, const char *custom_icon)
void panel_menu_button_set_tooltip (PanelMenuButton *button, const char *tooltip)
void panel_menu_button_set_use_menu_path (PanelMenuButton *button, gboolean use_menu_path)
gboolean panel_menu_button_get_use_menu_path (PanelMenuButton *button)
void panel_menu_button_set_use_custom_icon (PanelMenuButton *button, gboolean use_custom_icon)
void panel_menu_button_set_has_arrow (PanelMenuButton *button, gboolean has_arrow)
void panel_menu_button_load_from_gsettings (PanelWidget *panel, gboolean locked, int position, gboolean exactpos, const char *id)
void panel_menu_button_invoke_menu (PanelMenuButton *button, const char *callback_name)
void panel_menu_button_popup_menu (PanelMenuButton *button, guint n_button, guint32 activate_time)
void panel_menu_button_set_dnd_enabled (PanelMenuButton *button, gboolean dnd_enabled)
Macro Definition Documentation
PANEL_IS_MENU_BUTTON
#define PANEL_IS_MENU_BUTTON (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), PANEL_TYPE_MENU_BUTTON))
Definition at line 39 of file panel-menu-button.h.
Referenced by panel_menu_button_get_use_menu_path(), panel_menu_button_invoke_menu(), panel_menu_button_popup_menu(), panel_menu_button_set_custom_icon(), panel_menu_button_set_dnd_enabled(), panel_menu_button_set_has_arrow(), panel_menu_button_set_menu_path(), panel_menu_button_set_tooltip(), panel_menu_button_set_use_custom_icon(), and panel_menu_button_set_use_menu_path().
PANEL_IS_MENU_BUTTON_CLASS
#define PANEL_IS_MENU_BUTTON_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), PANEL_TYPE_MENU_BUTTON))
Definition at line 40 of file panel-menu-button.h.
PANEL_MENU_BUTTON
#define PANEL_MENU_BUTTON (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), PANEL_TYPE_MENU_BUTTON, PanelMenuButton))
Definition at line 37 of file panel-menu-button.h.
PANEL_MENU_BUTTON_CLASS
#define PANEL_MENU_BUTTON_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST((k), PANEL_TYPE_MENU_BUTTON, PanelMenuButtonClass))
Definition at line 38 of file panel-menu-button.h.
PANEL_MENU_BUTTON_GET_CLASS
#define PANEL_MENU_BUTTON_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), PANEL_TYPE_MENU_BUTTON, PanelMenuButtonClass))
Definition at line 41 of file panel-menu-button.h.
PANEL_TYPE_MENU_BUTTON
#define PANEL_TYPE_MENU_BUTTON (panel_menu_button_get_type ())
Definition at line 36 of file panel-menu-button.h.
Typedef Documentation
PanelMenuButton
typedef struct _PanelMenuButton PanelMenuButton
Definition at line 43 of file panel-menu-button.h.
PanelMenuButtonClass
typedef struct _PanelMenuButtonClass PanelMenuButtonClass
Definition at line 44 of file panel-menu-button.h.
PanelMenuButtonPrivate
typedef struct _PanelMenuButtonPrivate PanelMenuButtonPrivate
Definition at line 45 of file panel-menu-button.h.
Function Documentation
panel_menu_button_create()
gboolean panel_menu_button_create (PanelToplevel * toplevel, int position, const char * filename, const char * menu_path, gboolean use_menu_path, const char * tooltip)
Definition at line 960 of file panel-menu-button.c.
References FALSE, NULL, PANEL_GSETTINGS_OBJECTS, PANEL_OBJECT_MENU, PANEL_OBJECT_MENU_PATH_KEY, PANEL_OBJECT_PATH, PANEL_OBJECT_SCHEMA, PANEL_OBJECT_TOOLTIP_KEY, PANEL_OBJECT_USE_MENU_PATH_KEY, panel_profile_add_to_list(), panel_profile_prepare_object(), and TRUE.
panel_menu_button_get_type()
GType panel_menu_button_get_type (void)
panel_menu_button_get_use_menu_path()
gboolean panel_menu_button_get_use_menu_path (PanelMenuButton * button)
Definition at line 885 of file panel-menu-button.c.
References FALSE, PANEL_IS_MENU_BUTTON, and _PanelMenuButton::priv.
panel_menu_button_invoke_menu()
void panel_menu_button_invoke_menu (PanelMenuButton * button, const char * callback_name)
Definition at line 1009 of file panel-menu-button.c.
References NULL, PANEL_IS_MENU_BUTTON, panel_is_program_in_path(), panel_launch_desktop_file_with_fallback(), and panel_show_help().
panel_menu_button_load_from_gsettings()
void panel_menu_button_load_from_gsettings (PanelWidget * panel, gboolean locked, int position, gboolean exactpos, const char * id)
Definition at line 915 of file panel-menu-button.c.
References PANEL_OBJECT_CUSTOM_ICON_KEY, PANEL_OBJECT_HAS_ARROW_KEY, PANEL_OBJECT_MENU_PATH_KEY, PANEL_OBJECT_PATH, PANEL_OBJECT_SCHEMA, PANEL_OBJECT_TOOLTIP_KEY, PANEL_OBJECT_USE_CUSTOM_ICON_KEY, and PANEL_OBJECT_USE_MENU_PATH_KEY.
panel_menu_button_popup_menu()
void panel_menu_button_popup_menu (PanelMenuButton * button, guint n_button, guint32 activate_time)
Definition at line 437 of file panel-menu-button.c.
References BUTTON_WIDGET, button_widget_set_ignore_leave(), NULL, PANEL_IS_MENU_BUTTON, PANEL_ORIENTATION_BOTTOM, PANEL_ORIENTATION_LEFT, PANEL_ORIENTATION_RIGHT, PANEL_ORIENTATION_TOP, panel_toplevel_get_orientation(), panel_toplevel_push_autohide_disabler(), _PanelMenuButton::priv, and TRUE.
panel_menu_button_set_custom_icon()
void panel_menu_button_set_custom_icon (PanelMenuButton * button, const char * custom_icon)
Definition at line 834 of file panel-menu-button.c.
References NULL, PANEL_IS_MENU_BUTTON, and _PanelMenuButton::priv.
panel_menu_button_set_dnd_enabled()
void panel_menu_button_set_dnd_enabled (PanelMenuButton * button, gboolean dnd_enabled)
Definition at line 1036 of file panel-menu-button.c.
References FALSE, NULL, PANEL_IS_MENU_BUTTON, _PanelMenuButton::priv, and TRUE.
panel_menu_button_set_has_arrow()
void panel_menu_button_set_has_arrow (PanelMenuButton * button, gboolean has_arrow)
Definition at line 904 of file panel-menu-button.c.
References BUTTON_WIDGET, button_widget_set_has_arrow(), FALSE, PANEL_IS_MENU_BUTTON, and _PanelMenuButton::priv.
panel_menu_button_set_menu_path()
void panel_menu_button_set_menu_path (PanelMenuButton * button, const char * menu_path)
Definition at line 799 of file panel-menu-button.c.
References NULL, PANEL_IS_MENU_BUTTON, and _PanelMenuButton::priv.
panel_menu_button_set_tooltip()
void panel_menu_button_set_tooltip (PanelMenuButton * button, const char * tooltip)
Definition at line 849 of file panel-menu-button.c.
References NULL, PANEL_IS_MENU_BUTTON, panel_util_set_tooltip_text(), and _PanelMenuButton::priv.
panel_menu_button_set_use_custom_icon()
void panel_menu_button_set_use_custom_icon (PanelMenuButton * button, gboolean use_custom_icon)
Definition at line 893 of file panel-menu-button.c.
References FALSE, PANEL_IS_MENU_BUTTON, and _PanelMenuButton::priv.
panel_menu_button_set_use_menu_path()
void panel_menu_button_set_use_menu_path (PanelMenuButton * button, gboolean use_menu_path)
Definition at line 864 of file panel-menu-button.c.
References FALSE, NULL, PANEL_IS_MENU_BUTTON, and _PanelMenuButton::priv.