MATE Desktop Environment: paper.h File Reference
paper.h File Reference
Classes
struct _DviPaper
struct _DviPaperSpec
Typedefs
typedef struct _DviPaper DviPaper
typedef struct _DviPaperSpec DviPaperSpec
Enumerations
enum DviPaperClass { MDVI_PAPER_CLASS_ISO , MDVI_PAPER_CLASS_US , MDVI_PAPER_CLASS_ANY , MDVI_PAPER_CLASS_CUSTOM }
Functions
int mdvi_get_paper_size __PROTO ((const char *, DviPaper *))
DviPaperSpec *mdvi_get_paper_specs __PROTO ((DviPaperClass))
void mdvi_free_paper_specs __PROTO ((DviPaperSpec *))
Typedef Documentation
DviPaper
typedef struct _DviPaper DviPaper
Definition at line 4 of file paper.h.
DviPaperSpec
typedef struct _DviPaperSpec DviPaperSpec
Definition at line 5 of file paper.h.
Enumeration Type Documentation
DviPaperClass
enum DviPaperClass
Enumerator
MDVI_PAPER_CLASS_ISO
MDVI_PAPER_CLASS_US
MDVI_PAPER_CLASS_ANY
MDVI_PAPER_CLASS_CUSTOM
Definition at line 7 of file paper.h.
Function Documentation
__PROTO() [1/3]
int mdvi_get_paper_size __PROTO ((const char *, DviPaper *)) extern
References mdvi_get_paper_size().
__PROTO() [2/3]
DviPaperSpec *mdvi_get_paper_specs __PROTO ((DviPaperClass)) extern
References mdvi_get_paper_specs().
__PROTO() [3/3]
void mdvi_free_paper_specs __PROTO ((DviPaperSpec *)) extern
References mdvi_free_paper_specs().