MATE Desktop Environment: pluma-commands-search.c File Reference
pluma-commands-search.c File Reference
#include <string.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include "pluma-commands.h"
#include "pluma-debug.h"
#include "pluma-statusbar.h"
#include "pluma-window.h"
#include "pluma-window-private.h"
#include "pluma-utils.h"
#include "dialogs/pluma-search-dialog.h"
Macros
#define PLUMA_SEARCH_DIALOG_KEY "pluma-search-dialog-key"
#define PLUMA_LAST_SEARCH_DATA_KEY "pluma-last-search-data-key"
#define MAX_MSG_LENGTH 40
Typedefs
typedef struct _LastSearchData LastSearchData
Functions
void _pluma_cmd_search_find (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_search_replace (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_search_find_next (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_search_find_prev (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_search_clear_highlight (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_search_goto_line (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_search_incremental_search (GtkAction *action, PlumaWindow *window)
Macro Definition Documentation
MAX_MSG_LENGTH
#define MAX_MSG_LENGTH 40
Definition at line 131 of file pluma-commands-search.c.
PLUMA_LAST_SEARCH_DATA_KEY
#define PLUMA_LAST_SEARCH_DATA_KEY "pluma-last-search-data-key"
Definition at line 52 of file pluma-commands-search.c.
PLUMA_SEARCH_DIALOG_KEY
#define PLUMA_SEARCH_DIALOG_KEY "pluma-search-dialog-key"
Definition at line 51 of file pluma-commands-search.c.
Referenced by _pluma_cmd_search_find(), and _pluma_cmd_search_replace().
Typedef Documentation
LastSearchData
typedef struct _LastSearchData LastSearchData
Definition at line 54 of file pluma-commands-search.c.
Function Documentation
_pluma_cmd_search_clear_highlight()
void _pluma_cmd_search_clear_highlight (GtkAction * action, PlumaWindow * window)
Definition at line 767 of file pluma-commands-search.c.
References action, DEBUG_COMMANDS, pluma_debug(), PLUMA_DOCUMENT, pluma_document_set_search_text(), PLUMA_SEARCH_DONT_SET_FLAGS, and pluma_window_get_active_document().
_pluma_cmd_search_find()
void _pluma_cmd_search_find (GtkAction * action, PlumaWindow * window)
Definition at line 580 of file pluma-commands-search.c.
References action, data, DEBUG_COMMANDS, FALSE, NULL, pluma_debug(), PLUMA_IS_SEARCH_DIALOG, PLUMA_SEARCH_DIALOG, pluma_search_dialog_get_parse_escapes(), pluma_search_dialog_get_search_text(), pluma_search_dialog_get_show_replace(), PLUMA_SEARCH_DIALOG_KEY, pluma_search_dialog_present_with_time(), pluma_search_dialog_set_search_text(), pluma_search_dialog_set_show_replace(), pluma_utils_unescape_search_text(), and pluma_window_get_active_document().
_pluma_cmd_search_find_next()
void _pluma_cmd_search_find_next (GtkAction * action, PlumaWindow * window)
Definition at line 749 of file pluma-commands-search.c.
References action, DEBUG_COMMANDS, FALSE, and pluma_debug().
_pluma_cmd_search_find_prev()
void _pluma_cmd_search_find_prev (GtkAction * action, PlumaWindow * window)
Definition at line 758 of file pluma-commands-search.c.
References action, DEBUG_COMMANDS, pluma_debug(), and TRUE.
_pluma_cmd_search_goto_line()
void _pluma_cmd_search_goto_line (GtkAction * action, PlumaWindow * window)
Definition at line 781 of file pluma-commands-search.c.
References action, DEBUG_COMMANDS, NULL, pluma_debug(), and pluma_window_get_active_view().
_pluma_cmd_search_incremental_search()
void _pluma_cmd_search_incremental_search (GtkAction * action, PlumaWindow * window)
Definition at line 806 of file pluma-commands-search.c.
References action, DEBUG_COMMANDS, NULL, pluma_debug(), and pluma_window_get_active_view().
_pluma_cmd_search_replace()
void _pluma_cmd_search_replace (GtkAction * action, PlumaWindow * window)
Definition at line 654 of file pluma-commands-search.c.
References action, data, DEBUG_COMMANDS, NULL, pluma_debug(), PLUMA_IS_SEARCH_DIALOG, PLUMA_SEARCH_DIALOG, pluma_search_dialog_get_parse_escapes(), pluma_search_dialog_get_search_text(), pluma_search_dialog_get_show_replace(), PLUMA_SEARCH_DIALOG_KEY, pluma_search_dialog_present_with_time(), pluma_search_dialog_set_search_text(), pluma_search_dialog_set_show_replace(), pluma_utils_unescape_search_text(), pluma_window_get_active_document(), and TRUE.