MATE Desktop Environment: pluma-notebook.h File Reference
pluma-notebook.h File Reference
#include <pluma/pluma-tab.h>
#include <glib.h>
#include <gtk/gtk.h>
Classes
struct _PlumaNotebook
struct _PlumaNotebookClass
Macros
#define PLUMA_TYPE_NOTEBOOK (pluma_notebook_get_type ())
#define PLUMA_NOTEBOOK(o)
#define PLUMA_NOTEBOOK_CLASS(k)
#define PLUMA_IS_NOTEBOOK(o)
#define PLUMA_IS_NOTEBOOK_CLASS(k)
#define PLUMA_NOTEBOOK_GET_CLASS(o)
Typedefs
typedef struct _PlumaNotebookPrivate PlumaNotebookPrivate
typedef struct _PlumaNotebook PlumaNotebook
typedef struct _PlumaNotebookClass PlumaNotebookClass
Functions
GType pluma_notebook_get_type (void)
GtkWidget * pluma_notebook_new (void)
void pluma_notebook_add_tab (PlumaNotebook *nb, PlumaTab *tab, gint position, gboolean jump_to)
void pluma_notebook_remove_tab (PlumaNotebook *nb, PlumaTab *tab)
void pluma_notebook_remove_all_tabs (PlumaNotebook *nb)
void pluma_notebook_reorder_tab (PlumaNotebook *src, PlumaTab *tab, gint dest_position)
void pluma_notebook_move_tab (PlumaNotebook *src, PlumaNotebook *dest, PlumaTab *tab, gint dest_position)
void pluma_notebook_set_close_buttons_sensitive (PlumaNotebook *nb, gboolean sensitive)
gboolean pluma_notebook_get_close_buttons_sensitive (PlumaNotebook *nb)
void pluma_notebook_set_tab_drag_and_drop_enabled (PlumaNotebook *nb, gboolean enable)
gboolean pluma_notebook_get_tab_drag_and_drop_enabled (PlumaNotebook *nb)
Macro Definition Documentation
PLUMA_IS_NOTEBOOK
#define PLUMA_IS_NOTEBOOK (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), PLUMA_TYPE_NOTEBOOK))
Definition at line 55 of file pluma-notebook.h.
Referenced by pluma_notebook_add_tab(), pluma_notebook_get_close_buttons_sensitive(), pluma_notebook_get_tab_drag_and_drop_enabled(), pluma_notebook_move_tab(), pluma_notebook_remove_all_tabs(), pluma_notebook_remove_tab(), pluma_notebook_reorder_tab(), pluma_notebook_set_close_buttons_sensitive(), and pluma_notebook_set_tab_drag_and_drop_enabled().
PLUMA_IS_NOTEBOOK_CLASS
#define PLUMA_IS_NOTEBOOK_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), PLUMA_TYPE_NOTEBOOK))
Definition at line 56 of file pluma-notebook.h.
PLUMA_NOTEBOOK
#define PLUMA_NOTEBOOK (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), PLUMA_TYPE_NOTEBOOK, PlumaNotebook))
Definition at line 53 of file pluma-notebook.h.
Referenced by _pluma_cmd_documents_move_to_new_window(), _pluma_window_move_tab_to_new_window(), pluma_window_close_all_tabs(), pluma_window_close_tab(), pluma_window_close_tabs(), pluma_window_create_tab(), and pluma_window_create_tab_from_uri().
PLUMA_NOTEBOOK_CLASS
#define PLUMA_NOTEBOOK_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST((k), PLUMA_TYPE_NOTEBOOK, PlumaNotebookClass))
Definition at line 54 of file pluma-notebook.h.
PLUMA_NOTEBOOK_GET_CLASS
#define PLUMA_NOTEBOOK_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), PLUMA_TYPE_NOTEBOOK, PlumaNotebookClass))
Definition at line 57 of file pluma-notebook.h.
PLUMA_TYPE_NOTEBOOK
#define PLUMA_TYPE_NOTEBOOK (pluma_notebook_get_type ())
Definition at line 52 of file pluma-notebook.h.
Referenced by pluma_notebook_new().
Typedef Documentation
PlumaNotebook
typedef struct _PlumaNotebook PlumaNotebook
Definition at line 65 of file pluma-notebook.h.
PlumaNotebookClass
typedef struct _PlumaNotebookClass PlumaNotebookClass
Definition at line 78 of file pluma-notebook.h.
PlumaNotebookPrivate
typedef struct _PlumaNotebookPrivate PlumaNotebookPrivate
Definition at line 60 of file pluma-notebook.h.
Function Documentation
pluma_notebook_add_tab()
void pluma_notebook_add_tab (PlumaNotebook * nb, PlumaTab * tab, gint position, gboolean jump_to)
pluma_notebook_add_tab: @nb: a PlumaNotebook @tab: a PlumaTab @position: the position where the @tab should be added @jump_to: TRUE to set the @tab as active
Adds the specified @tab to the @nb.
Definition at line 961 of file pluma-notebook.c.
References PLUMA_IS_NOTEBOOK, PLUMA_IS_TAB, pluma_tab_get_view(), and TAB_ADDED.
Referenced by pluma_notebook_move_tab(), pluma_window_create_tab(), and pluma_window_create_tab_from_uri().
pluma_notebook_get_close_buttons_sensitive()
gboolean pluma_notebook_get_close_buttons_sensitive (PlumaNotebook * nb)
pluma_notebook_get_close_buttons_sensitive: @nb: a PlumaNotebook
Whether the close buttons are sensitive.
Returns: TRUE if the close buttons are sensitive
Definition at line 1145 of file pluma-notebook.c.
References PLUMA_IS_NOTEBOOK, _PlumaNotebook::priv, and TRUE.
pluma_notebook_get_tab_drag_and_drop_enabled()
gboolean pluma_notebook_get_tab_drag_and_drop_enabled (PlumaNotebook * nb)
pluma_notebook_get_tab_drag_and_drop_enabled: @nb: a PlumaNotebook
Whether the drag and drop is enabled in the @nb.
Returns: TRUE if the drag and drop is enabled.
Definition at line 1182 of file pluma-notebook.c.
References PLUMA_IS_NOTEBOOK, _PlumaNotebook::priv, and TRUE.
pluma_notebook_get_type()
GType pluma_notebook_get_type (void)
References dest.
pluma_notebook_move_tab()
void pluma_notebook_move_tab (PlumaNotebook * src, PlumaNotebook * dest, PlumaTab * tab, gint dest_position)
pluma_notebook_move_tab: @src: a PlumaNotebook @dest: a PlumaNotebook @tab: a PlumaTab @dest_position: the position for @tab
Moves @tab from @src to @dest. If dest_position is greater than or equal to the number of tabs of the destination nootebook or negative, tab will be moved to the end of the tabs.
Definition at line 343 of file pluma-notebook.c.
References dest, PLUMA_IS_NOTEBOOK, PLUMA_IS_TAB, pluma_notebook_add_tab(), pluma_notebook_remove_tab(), and TRUE.
Referenced by _pluma_window_move_tab_to_new_window().
pluma_notebook_new()
GtkWidget * pluma_notebook_new (void)
pluma_notebook_new:
Creates a new PlumaNotebook object.
Returns: a new PlumaNotebook
Definition at line 753 of file pluma-notebook.c.
References NULL, and PLUMA_TYPE_NOTEBOOK.
pluma_notebook_remove_all_tabs()
void pluma_notebook_remove_all_tabs (PlumaNotebook * nb)
pluma_notebook_remove_all_tabs: @nb: a PlumaNotebook
Removes all PlumaTab from @nb.
Definition at line 1087 of file pluma-notebook.c.
References NULL, PLUMA_IS_NOTEBOOK, and _PlumaNotebook::priv.
Referenced by pluma_window_close_all_tabs().
pluma_notebook_remove_tab()
void pluma_notebook_remove_tab (PlumaNotebook * nb, PlumaTab * tab)
pluma_notebook_remove_tab: @nb: a PlumaNotebook @tab: a PlumaTab
Removes @tab from @nb.
Definition at line 1057 of file pluma-notebook.c.
References PLUMA_IS_NOTEBOOK, PLUMA_IS_TAB, and _PlumaNotebook::priv.
Referenced by pluma_notebook_move_tab(), pluma_window_close_tab(), and pluma_window_close_tabs().
pluma_notebook_reorder_tab()
void pluma_notebook_reorder_tab (PlumaNotebook * src, PlumaTab * tab, gint dest_position)
pluma_notebook_reorder_tab: @src: a PlumaNotebook @tab: a PlumaTab @dest_position: the position for @tab
Reorders the page containing @tab, so that it appears in @dest_position position. If dest_position is greater than or equal to the number of tabs of the destination notebook or negative, tab will be moved to the end of the tabs.
Definition at line 372 of file pluma-notebook.c.
References PLUMA_IS_NOTEBOOK, PLUMA_IS_TAB, _PlumaNotebook::priv, and TABS_REORDERED.
pluma_notebook_set_close_buttons_sensitive()
void pluma_notebook_set_close_buttons_sensitive (PlumaNotebook * nb, gboolean sensitive)
pluma_notebook_set_close_buttons_sensitive: @nb: a PlumaNotebook @sensitive: TRUE to make the buttons sensitive
Sets whether the close buttons in the tabs of @nb are sensitive.
Definition at line 1119 of file pluma-notebook.c.
References FALSE, PLUMA_IS_NOTEBOOK, and _PlumaNotebook::priv.
pluma_notebook_set_tab_drag_and_drop_enabled()
void pluma_notebook_set_tab_drag_and_drop_enabled (PlumaNotebook * nb, gboolean enable)
pluma_notebook_set_tab_drag_and_drop_enabled: @nb: a PlumaNotebook @enable: TRUE to enable the drag and drop
Sets whether drag and drop of tabs in the @nb is enabled.
Definition at line 1160 of file pluma-notebook.c.
References FALSE, PLUMA_IS_NOTEBOOK, and _PlumaNotebook::priv.