MATE Desktop Environment: pluma-encodings.c File Reference
pluma-encodings.c File Reference
#include <string.h>
#include <glib/gi18n.h>
#include "pluma-encodings.h"
Enumerations
enum PlumaEncodingIndex {
PLUMA_ENCODING_ISO_8859_1 , PLUMA_ENCODING_ISO_8859_2 , PLUMA_ENCODING_ISO_8859_3 , PLUMA_ENCODING_ISO_8859_4 ,
PLUMA_ENCODING_ISO_8859_5 , PLUMA_ENCODING_ISO_8859_6 , PLUMA_ENCODING_ISO_8859_7 , PLUMA_ENCODING_ISO_8859_8 ,
PLUMA_ENCODING_ISO_8859_9 , PLUMA_ENCODING_ISO_8859_10 , PLUMA_ENCODING_ISO_8859_13 , PLUMA_ENCODING_ISO_8859_14 ,
PLUMA_ENCODING_ISO_8859_15 , PLUMA_ENCODING_ISO_8859_16 , PLUMA_ENCODING_UTF_7 , PLUMA_ENCODING_UTF_16 ,
PLUMA_ENCODING_UTF_16_BE , PLUMA_ENCODING_UTF_16_LE , PLUMA_ENCODING_UTF_32 , PLUMA_ENCODING_UCS_2 ,
PLUMA_ENCODING_UCS_4 , PLUMA_ENCODING_ARMSCII_8 , PLUMA_ENCODING_BIG5 , PLUMA_ENCODING_BIG5_HKSCS ,
PLUMA_ENCODING_CP_866 , PLUMA_ENCODING_EUC_JP , PLUMA_ENCODING_EUC_JP_MS , PLUMA_ENCODING_CP932 ,
PLUMA_ENCODING_EUC_KR , PLUMA_ENCODING_EUC_TW , PLUMA_ENCODING_GB18030 , PLUMA_ENCODING_GB2312 ,
PLUMA_ENCODING_GBK , PLUMA_ENCODING_GEOSTD8 , PLUMA_ENCODING_IBM_850 , PLUMA_ENCODING_IBM_852 ,
PLUMA_ENCODING_IBM_855 , PLUMA_ENCODING_IBM_857 , PLUMA_ENCODING_IBM_862 , PLUMA_ENCODING_IBM_864 ,
PLUMA_ENCODING_ISO_2022_JP , PLUMA_ENCODING_ISO_2022_KR , PLUMA_ENCODING_ISO_IR_111 , PLUMA_ENCODING_JOHAB ,
PLUMA_ENCODING_KOI8_R , PLUMA_ENCODING_KOI8__R , PLUMA_ENCODING_KOI8_U , PLUMA_ENCODING_SHIFT_JIS ,
PLUMA_ENCODING_TCVN , PLUMA_ENCODING_TIS_620 , PLUMA_ENCODING_UHC , PLUMA_ENCODING_VISCII ,
PLUMA_ENCODING_WINDOWS_1250 , PLUMA_ENCODING_WINDOWS_1251 , PLUMA_ENCODING_WINDOWS_1252 , PLUMA_ENCODING_WINDOWS_1253 ,
PLUMA_ENCODING_WINDOWS_1254 , PLUMA_ENCODING_WINDOWS_1255 , PLUMA_ENCODING_WINDOWS_1256 , PLUMA_ENCODING_WINDOWS_1257 ,
PLUMA_ENCODING_WINDOWS_1258 , PLUMA_ENCODING_LAST , PLUMA_ENCODING_UTF_8 , PLUMA_ENCODING_UNKNOWN
}
Functions
const PlumaEncoding * pluma_encoding_get_from_charset (const gchar *charset)
const PlumaEncoding * pluma_encoding_get_from_index (gint idx)
const PlumaEncoding * pluma_encoding_get_utf8 (void)
const PlumaEncoding * pluma_encoding_get_current (void)
gchar * pluma_encoding_to_string (const PlumaEncoding *enc)
const gchar * pluma_encoding_get_charset (const PlumaEncoding *enc)
const gchar * pluma_encoding_get_name (const PlumaEncoding *enc)
PlumaEncoding * pluma_encoding_copy (const PlumaEncoding *enc)
void pluma_encoding_free (PlumaEncoding *enc)
GType pluma_encoding_get_type (void)
GSList * _pluma_encoding_strv_to_list (const gchar *const *enc_str)
gchar ** _pluma_encoding_list_to_strv (const GSList *enc_list)
Enumeration Type Documentation
PlumaEncodingIndex
enum PlumaEncodingIndex
Enumerator
PLUMA_ENCODING_ISO_8859_1
PLUMA_ENCODING_ISO_8859_2
PLUMA_ENCODING_ISO_8859_3
PLUMA_ENCODING_ISO_8859_4
PLUMA_ENCODING_ISO_8859_5
PLUMA_ENCODING_ISO_8859_6
PLUMA_ENCODING_ISO_8859_7
PLUMA_ENCODING_ISO_8859_8
PLUMA_ENCODING_ISO_8859_9
PLUMA_ENCODING_ISO_8859_10
PLUMA_ENCODING_ISO_8859_13
PLUMA_ENCODING_ISO_8859_14
PLUMA_ENCODING_ISO_8859_15
PLUMA_ENCODING_ISO_8859_16
PLUMA_ENCODING_UTF_7
PLUMA_ENCODING_UTF_16
PLUMA_ENCODING_UTF_16_BE
PLUMA_ENCODING_UTF_16_LE
PLUMA_ENCODING_UTF_32
PLUMA_ENCODING_UCS_2
PLUMA_ENCODING_UCS_4
PLUMA_ENCODING_ARMSCII_8
PLUMA_ENCODING_BIG5
PLUMA_ENCODING_BIG5_HKSCS
PLUMA_ENCODING_CP_866
PLUMA_ENCODING_EUC_JP
PLUMA_ENCODING_EUC_JP_MS
PLUMA_ENCODING_CP932
PLUMA_ENCODING_EUC_KR
PLUMA_ENCODING_EUC_TW
PLUMA_ENCODING_GB18030
PLUMA_ENCODING_GB2312
PLUMA_ENCODING_GBK
PLUMA_ENCODING_GEOSTD8
PLUMA_ENCODING_IBM_850
PLUMA_ENCODING_IBM_852
PLUMA_ENCODING_IBM_855
PLUMA_ENCODING_IBM_857
PLUMA_ENCODING_IBM_862
PLUMA_ENCODING_IBM_864
PLUMA_ENCODING_ISO_2022_JP
PLUMA_ENCODING_ISO_2022_KR
PLUMA_ENCODING_ISO_IR_111
PLUMA_ENCODING_JOHAB
PLUMA_ENCODING_KOI8_R
PLUMA_ENCODING_KOI8__R
PLUMA_ENCODING_KOI8_U
PLUMA_ENCODING_SHIFT_JIS
PLUMA_ENCODING_TCVN
PLUMA_ENCODING_TIS_620
PLUMA_ENCODING_UHC
PLUMA_ENCODING_VISCII
PLUMA_ENCODING_WINDOWS_1250
PLUMA_ENCODING_WINDOWS_1251
PLUMA_ENCODING_WINDOWS_1252
PLUMA_ENCODING_WINDOWS_1253
PLUMA_ENCODING_WINDOWS_1254
PLUMA_ENCODING_WINDOWS_1255
PLUMA_ENCODING_WINDOWS_1256
PLUMA_ENCODING_WINDOWS_1257
PLUMA_ENCODING_WINDOWS_1258
PLUMA_ENCODING_LAST
PLUMA_ENCODING_UTF_8
PLUMA_ENCODING_UNKNOWN
Definition at line 56 of file pluma-encodings.c.
Function Documentation
_pluma_encoding_list_to_strv()
gchar ** _pluma_encoding_list_to_strv (const GSList * enc_list)
Definition at line 518 of file pluma-encodings.c.
References charset, FALSE, NULL, and pluma_encoding_get_charset().
_pluma_encoding_strv_to_list()
GSList * _pluma_encoding_strv_to_list (const gchar *const * enc_str)
Definition at line 490 of file pluma-encodings.c.
References charset, NULL, and pluma_encoding_get_from_charset().
pluma_encoding_copy()
PlumaEncoding * pluma_encoding_copy (const PlumaEncoding * enc)
Definition at line 440 of file pluma-encodings.c.
References NULL.
Referenced by pluma_encoding_get_type().
pluma_encoding_free()
void pluma_encoding_free (PlumaEncoding * enc)
Definition at line 448 of file pluma-encodings.c.
References NULL.
Referenced by pluma_encoding_get_type().
pluma_encoding_get_charset()
const gchar * pluma_encoding_get_charset (const PlumaEncoding * enc)
Definition at line 414 of file pluma-encodings.c.
References NULL.
Referenced by _pluma_encoding_list_to_strv().
pluma_encoding_get_current()
const PlumaEncoding * pluma_encoding_get_current (void)
Definition at line 356 of file pluma-encodings.c.
References FALSE, NULL, pluma_encoding_get_from_charset(), and TRUE.
Referenced by pluma_document_loader_get_encoding().
pluma_encoding_get_from_charset()
const PlumaEncoding * pluma_encoding_get_from_charset (const gchar * charset)
Definition at line 302 of file pluma-encodings.c.
References charset, NULL, pluma_encoding_get_utf8(), and PLUMA_ENCODING_LAST.
Referenced by _pluma_encoding_strv_to_list(), pluma_application_set_command_line_options(), and pluma_encoding_get_current().
pluma_encoding_get_from_index()
const PlumaEncoding * pluma_encoding_get_from_index (gint idx)
Definition at line 335 of file pluma-encodings.c.
References idx, NULL, and PLUMA_ENCODING_LAST.
pluma_encoding_get_name()
const gchar * pluma_encoding_get_name (const PlumaEncoding * enc)
Definition at line 426 of file pluma-encodings.c.
References _, and NULL.
pluma_encoding_get_type()
GType pluma_encoding_get_type (void)
pluma_encoding_get_type:
Retrieves the GType object which is associated with the PlumaEncoding class.
Return value: the GType associated with PlumaEncoding.
Definition at line 462 of file pluma-encodings.c.
References pluma_encoding_copy(), and pluma_encoding_free().
pluma_encoding_get_utf8()
const PlumaEncoding * pluma_encoding_get_utf8 (void)
Definition at line 348 of file pluma-encodings.c.
Referenced by pluma_encoding_get_from_charset(), and pluma_smart_charset_converter_get_guessed().
pluma_encoding_to_string()
gchar * pluma_encoding_to_string (const PlumaEncoding * enc)
Definition at line 392 of file pluma-encodings.c.
References _, and NULL.
Referenced by _pluma_tab_get_tooltips(), pluma_conversion_error_while_saving_message_area_new(), and pluma_io_loading_error_message_area_new().