MATE Desktop Environment: pluma-debug.h File Reference
pluma-debug.h File Reference
#include <glib.h>
Macros
#define DEBUG_VIEW PLUMA_DEBUG_VIEW, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_SEARCH PLUMA_DEBUG_SEARCH, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_PRINT PLUMA_DEBUG_PRINT, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_PREFS PLUMA_DEBUG_PREFS, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_PLUGINS PLUMA_DEBUG_PLUGINS, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_TAB PLUMA_DEBUG_TAB, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_DOCUMENT PLUMA_DEBUG_DOCUMENT,__FILE__, __LINE__, G_STRFUNC
#define DEBUG_COMMANDS PLUMA_DEBUG_COMMANDS,__FILE__, __LINE__, G_STRFUNC
#define DEBUG_APP PLUMA_DEBUG_APP, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_SESSION PLUMA_DEBUG_SESSION, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_UTILS PLUMA_DEBUG_UTILS, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_METADATA PLUMA_DEBUG_METADATA,__FILE__, __LINE__, G_STRFUNC
#define DEBUG_WINDOW PLUMA_DEBUG_WINDOW, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_LOADER PLUMA_DEBUG_LOADER, __FILE__, __LINE__, G_STRFUNC
#define DEBUG_SAVER PLUMA_DEBUG_SAVER, __FILE__, __LINE__, G_STRFUNC
Enumerations
enum PlumaDebugSection {
PLUMA_NO_DEBUG = 0 , PLUMA_DEBUG_VIEW = 1 << 0 , PLUMA_DEBUG_SEARCH = 1 << 1 , PLUMA_DEBUG_PRINT = 1 << 2 ,
PLUMA_DEBUG_PREFS = 1 << 3 , PLUMA_DEBUG_PLUGINS = 1 << 4 , PLUMA_DEBUG_TAB = 1 << 5 , PLUMA_DEBUG_DOCUMENT = 1 << 6 ,
PLUMA_DEBUG_COMMANDS = 1 << 7 , PLUMA_DEBUG_APP = 1 << 8 , PLUMA_DEBUG_SESSION = 1 << 9 , PLUMA_DEBUG_UTILS = 1 << 10 ,
PLUMA_DEBUG_METADATA = 1 << 11 , PLUMA_DEBUG_WINDOW = 1 << 12 , PLUMA_DEBUG_LOADER = 1 << 13 , PLUMA_DEBUG_SAVER = 1 << 14
}
Functions
void pluma_debug_init (void)
void pluma_debug (PlumaDebugSection section, const gchar *file, gint line, const gchar *function)
void pluma_debug_message (PlumaDebugSection section, const gchar *file, gint line, const gchar *function, const gchar *format,...)
Macro Definition Documentation
DEBUG_APP
#define DEBUG_APP PLUMA_DEBUG_APP, __FILE__, __LINE__, G_STRFUNC
Definition at line 73 of file pluma-debug.h.
Referenced by main().
DEBUG_COMMANDS
#define DEBUG_COMMANDS PLUMA_DEBUG_COMMANDS,__FILE__, __LINE__, G_STRFUNC
Definition at line 72 of file pluma-debug.h.
Referenced by _pluma_cmd_documents_move_to_new_window(), _pluma_cmd_documents_next_document(), _pluma_cmd_documents_previous_document(), _pluma_cmd_edit_copy(), _pluma_cmd_edit_cut(), _pluma_cmd_edit_delete(), _pluma_cmd_edit_invert_case(), _pluma_cmd_edit_lower_case(), _pluma_cmd_edit_paste(), _pluma_cmd_edit_preferences(), _pluma_cmd_edit_redo(), _pluma_cmd_edit_select_all(), _pluma_cmd_edit_title_case(), _pluma_cmd_edit_undo(), _pluma_cmd_edit_upper_case(), _pluma_cmd_file_close(), _pluma_cmd_file_close_all(), _pluma_cmd_file_close_tab(), _pluma_cmd_file_new(), _pluma_cmd_file_open(), _pluma_cmd_file_print(), _pluma_cmd_file_print_preview(), _pluma_cmd_file_quit(), _pluma_cmd_file_revert(), _pluma_cmd_file_save(), _pluma_cmd_file_save_as(), _pluma_cmd_file_save_documents_list(), _pluma_cmd_help_about(), _pluma_cmd_help_contents(), _pluma_cmd_load_files_from_prompt(), _pluma_cmd_search_clear_highlight(), _pluma_cmd_search_find(), _pluma_cmd_search_find_next(), _pluma_cmd_search_find_prev(), _pluma_cmd_search_goto_line(), _pluma_cmd_search_incremental_search(), _pluma_cmd_search_replace(), _pluma_cmd_view_show_bottom_pane(), _pluma_cmd_view_show_side_pane(), _pluma_cmd_view_show_statusbar(), _pluma_cmd_view_show_toolbar(), _pluma_cmd_view_toggle_fullscreen_mode(), pluma_commands_load_uri(), pluma_commands_load_uris(), pluma_commands_save_all_documents(), and pluma_commands_save_document().
DEBUG_DOCUMENT
#define DEBUG_DOCUMENT PLUMA_DEBUG_DOCUMENT,__FILE__, __LINE__, G_STRFUNC
Definition at line 71 of file pluma-debug.h.
Referenced by _pluma_document_get_seconds_since_last_save_or_load(), _pluma_document_search_region(), _pluma_document_set_readonly(), pluma_document_goto_line(), pluma_document_new(), pluma_document_search_backward(), pluma_document_search_forward(), and pluma_document_set_search_text().
DEBUG_LOADER
#define DEBUG_LOADER PLUMA_DEBUG_LOADER, __FILE__, __LINE__, G_STRFUNC
Definition at line 78 of file pluma-debug.h.
Referenced by pluma_document_loader_cancel(), pluma_document_loader_load(), and pluma_document_loader_loading().
DEBUG_METADATA
#define DEBUG_METADATA PLUMA_DEBUG_METADATA,__FILE__, __LINE__, G_STRFUNC
Definition at line 76 of file pluma-debug.h.
Referenced by pluma_metadata_manager_get(), pluma_metadata_manager_set(), and pluma_metadata_manager_shutdown().
DEBUG_PLUGINS
#define DEBUG_PLUGINS PLUMA_DEBUG_PLUGINS, __FILE__, __LINE__, G_STRFUNC
Definition at line 69 of file pluma-debug.h.
DEBUG_PREFS
#define DEBUG_PREFS PLUMA_DEBUG_PREFS, __FILE__, __LINE__, G_STRFUNC
Definition at line 68 of file pluma-debug.h.
Referenced by pluma_settings_get_writable_vfs_schemes(), and pluma_show_preferences_dialog().
DEBUG_PRINT
#define DEBUG_PRINT PLUMA_DEBUG_PRINT, __FILE__, __LINE__, G_STRFUNC
Definition at line 67 of file pluma-debug.h.
DEBUG_SAVER
#define DEBUG_SAVER PLUMA_DEBUG_SAVER, __FILE__, __LINE__, G_STRFUNC
Definition at line 79 of file pluma-debug.h.
Referenced by pluma_document_saver_save(), and pluma_document_saver_saving().
DEBUG_SEARCH
#define DEBUG_SEARCH PLUMA_DEBUG_SEARCH, __FILE__, __LINE__, G_STRFUNC
Definition at line 66 of file pluma-debug.h.
Referenced by pluma_document_set_last_replace_text(), and pluma_utils_escape_search_text().
DEBUG_SESSION
#define DEBUG_SESSION PLUMA_DEBUG_SESSION, __FILE__, __LINE__, G_STRFUNC
Definition at line 74 of file pluma-debug.h.
Referenced by pluma_session_init(), pluma_session_is_restored(), and pluma_session_load().
DEBUG_TAB
#define DEBUG_TAB PLUMA_DEBUG_TAB, __FILE__, __LINE__, G_STRFUNC
Definition at line 70 of file pluma-debug.h.
Referenced by pluma_tab_get_auto_save_enabled(), pluma_tab_get_auto_save_interval(), pluma_tab_set_auto_save_enabled(), and pluma_tab_set_auto_save_interval().
DEBUG_UTILS
#define DEBUG_UTILS PLUMA_DEBUG_UTILS, __FILE__, __LINE__, G_STRFUNC
Definition at line 75 of file pluma-debug.h.
Referenced by G_DEFINE_TYPE_WITH_CODE(), and pluma_utils_uri_exists().
DEBUG_VIEW
#define DEBUG_VIEW PLUMA_DEBUG_VIEW, __FILE__, __LINE__, G_STRFUNC
Definition at line 65 of file pluma-debug.h.
DEBUG_WINDOW
#define DEBUG_WINDOW PLUMA_DEBUG_WINDOW, __FILE__, __LINE__, G_STRFUNC
Definition at line 77 of file pluma-debug.h.
Enumeration Type Documentation
PlumaDebugSection
enum PlumaDebugSection
Enumerator
PLUMA_NO_DEBUG
PLUMA_DEBUG_VIEW
PLUMA_DEBUG_SEARCH
PLUMA_DEBUG_PRINT
PLUMA_DEBUG_PREFS
PLUMA_DEBUG_PLUGINS
PLUMA_DEBUG_TAB
PLUMA_DEBUG_DOCUMENT
PLUMA_DEBUG_COMMANDS
PLUMA_DEBUG_APP
PLUMA_DEBUG_SESSION
PLUMA_DEBUG_UTILS
PLUMA_DEBUG_METADATA
PLUMA_DEBUG_WINDOW
PLUMA_DEBUG_LOADER
PLUMA_DEBUG_SAVER
Definition at line 44 of file pluma-debug.h.
Function Documentation
pluma_debug()
void pluma_debug (PlumaDebugSection section, const gchar * file, gint line, const gchar * function)
Definition at line 138 of file pluma-debug.c.
References debug, and NULL.
Referenced by _pluma_cmd_documents_move_to_new_window(), _pluma_cmd_documents_next_document(), _pluma_cmd_documents_previous_document(), _pluma_cmd_edit_copy(), _pluma_cmd_edit_cut(), _pluma_cmd_edit_delete(), _pluma_cmd_edit_invert_case(), _pluma_cmd_edit_lower_case(), _pluma_cmd_edit_paste(), _pluma_cmd_edit_preferences(), _pluma_cmd_edit_redo(), _pluma_cmd_edit_select_all(), _pluma_cmd_edit_title_case(), _pluma_cmd_edit_undo(), _pluma_cmd_edit_upper_case(), _pluma_cmd_file_close(), _pluma_cmd_file_close_all(), _pluma_cmd_file_close_tab(), _pluma_cmd_file_new(), _pluma_cmd_file_open(), _pluma_cmd_file_print(), _pluma_cmd_file_print_preview(), _pluma_cmd_file_quit(), _pluma_cmd_file_revert(), _pluma_cmd_file_save(), _pluma_cmd_file_save_as(), _pluma_cmd_file_save_documents_list(), _pluma_cmd_help_about(), _pluma_cmd_help_contents(), _pluma_cmd_load_files_from_prompt(), _pluma_cmd_search_clear_highlight(), _pluma_cmd_search_find(), _pluma_cmd_search_find_next(), _pluma_cmd_search_find_prev(), _pluma_cmd_search_goto_line(), _pluma_cmd_search_incremental_search(), _pluma_cmd_search_replace(), _pluma_cmd_view_show_bottom_pane(), _pluma_cmd_view_show_side_pane(), _pluma_cmd_view_show_statusbar(), _pluma_cmd_view_show_toolbar(), _pluma_cmd_view_toggle_fullscreen_mode(), _pluma_document_get_seconds_since_last_save_or_load(), _pluma_document_search_region(), _pluma_document_set_readonly(), pluma_commands_load_uris(), pluma_commands_save_all_documents(), pluma_commands_save_document(), pluma_document_goto_line(), pluma_document_loader_cancel(), pluma_document_loader_load(), pluma_document_new(), pluma_document_saver_save(), pluma_metadata_manager_shutdown(), pluma_session_init(), pluma_session_is_restored(), pluma_session_load(), pluma_settings_get_writable_vfs_schemes(), pluma_show_preferences_dialog(), pluma_tab_get_auto_save_enabled(), pluma_tab_get_auto_save_interval(), pluma_tab_set_auto_save_enabled(), pluma_tab_set_auto_save_interval(), pluma_view_copy_clipboard(), pluma_view_cut_clipboard(), pluma_view_delete_selection(), pluma_view_invert_case_selection(), pluma_view_lower_case_selection(), pluma_view_paste_clipboard(), pluma_view_scroll_to_cursor(), pluma_view_select_all(), pluma_view_set_font(), pluma_view_title_case_selection(), and pluma_view_upper_case_selection().
pluma_debug_init()
void pluma_debug_init (void)
Definition at line 51 of file pluma-debug.c.
References debug, NULL, PLUMA_DEBUG_APP, PLUMA_DEBUG_COMMANDS, PLUMA_DEBUG_DOCUMENT, PLUMA_DEBUG_LOADER, PLUMA_DEBUG_METADATA, PLUMA_DEBUG_PLUGINS, PLUMA_DEBUG_PREFS, PLUMA_DEBUG_PRINT, PLUMA_DEBUG_SAVER, PLUMA_DEBUG_SEARCH, PLUMA_DEBUG_SESSION, PLUMA_DEBUG_TAB, PLUMA_DEBUG_UTILS, PLUMA_DEBUG_VIEW, PLUMA_DEBUG_WINDOW, and PLUMA_NO_DEBUG.
Referenced by main().
pluma_debug_message()
void pluma_debug_message (PlumaDebugSection section, const gchar * file, gint line, const gchar * function, const gchar * format, ...)
Definition at line 101 of file pluma-debug.c.
References debug, and NULL.
Referenced by _pluma_cmd_file_save_documents_list(), create_taglist(), free_taglist(), G_DEFINE_TYPE_WITH_CODE(), main(), pluma_commands_load_uri(), pluma_document_loader_loading(), pluma_document_saver_saving(), pluma_document_search_backward(), pluma_document_search_forward(), pluma_document_set_last_replace_text(), pluma_document_set_search_text(), pluma_metadata_manager_get(), pluma_metadata_manager_set(), pluma_session_is_restored(), pluma_settings_get_writable_vfs_schemes(), pluma_utils_escape_search_text(), pluma_utils_uri_exists(), and pluma_view_new().