MATE Desktop Environment: pluma-io-error-message-area.c File Reference
pluma-io-error-message-area.c File Reference
#include <errno.h>
#include <string.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include "pluma-settings.h"
#include "pluma-utils.h"
#include "pluma-document.h"
#include "pluma-io-error-message-area.h"
#include <pluma/pluma-encodings-combo-box.h>
Macros
#define MAX_URI_IN_DIALOG_LENGTH 50
Functions
GtkWidget * pluma_unrecoverable_reverting_error_message_area_new (const gchar *uri, const GError *error)
GtkWidget * pluma_io_loading_error_message_area_new (const gchar *uri, const PlumaEncoding *encoding, const GError *error)
GtkWidget * pluma_conversion_error_while_saving_message_area_new (const gchar *uri, const PlumaEncoding *encoding, const GError *error)
const PlumaEncoding * pluma_conversion_error_message_area_get_encoding (GtkWidget *message_area)
GtkWidget * pluma_file_already_open_warning_message_area_new (const gchar *uri)
GtkWidget * pluma_externally_modified_saving_error_message_area_new (const gchar *uri, const GError *error)
GtkWidget * pluma_no_backup_saving_error_message_area_new (const gchar *uri, const GError *error)
GtkWidget * pluma_unrecoverable_saving_error_message_area_new (const gchar *uri, const GError *error)
GtkWidget * pluma_externally_modified_message_area_new (const gchar *uri, gboolean document_modified)
Macro Definition Documentation
MAX_URI_IN_DIALOG_LENGTH
#define MAX_URI_IN_DIALOG_LENGTH 50
Definition at line 52 of file pluma-io-error-message-area.c.
Function Documentation
pluma_conversion_error_message_area_get_encoding()
const PlumaEncoding * pluma_conversion_error_message_area_get_encoding (GtkWidget * message_area)
Definition at line 724 of file pluma-io-error-message-area.c.
References NULL, PLUMA_ENCODINGS_COMBO_BOX, and pluma_encodings_combo_box_get_selected_encoding().
pluma_conversion_error_while_saving_message_area_new()
GtkWidget * pluma_conversion_error_while_saving_message_area_new (const gchar * uri, const PlumaEncoding * encoding, const GError * error)
Definition at line 669 of file pluma-io-error-message-area.c.
References _, error, FALSE, MAX_URI_IN_DIALOG_LENGTH, NULL, pluma_encoding_to_string(), pluma_utils_str_middle_truncate(), and pluma_utils_uri_for_display().
pluma_externally_modified_message_area_new()
GtkWidget * pluma_externally_modified_message_area_new (const gchar * uri, gboolean document_modified)
Definition at line 1153 of file pluma-io-error-message-area.c.
References _, MAX_URI_IN_DIALOG_LENGTH, NULL, pluma_utils_str_middle_truncate(), and pluma_utils_uri_for_display().
pluma_externally_modified_saving_error_message_area_new()
GtkWidget * pluma_externally_modified_saving_error_message_area_new (const gchar * uri, const GError * error)
Definition at line 826 of file pluma-io-error-message-area.c.
References _, error, FALSE, MAX_URI_IN_DIALOG_LENGTH, NULL, PLUMA_DOCUMENT_ERROR, PLUMA_DOCUMENT_ERROR_EXTERNALLY_MODIFIED, pluma_utils_str_middle_truncate(), pluma_utils_uri_for_display(), and TRUE.
pluma_file_already_open_warning_message_area_new()
GtkWidget * pluma_file_already_open_warning_message_area_new (const gchar * uri)
Definition at line 739 of file pluma-io-error-message-area.c.
References _, FALSE, MAX_URI_IN_DIALOG_LENGTH, pluma_utils_str_middle_truncate(), pluma_utils_uri_for_display(), and TRUE.
pluma_io_loading_error_message_area_new()
GtkWidget * pluma_io_loading_error_message_area_new (const gchar * uri, const PlumaEncoding * encoding, const GError * error)
Definition at line 558 of file pluma-io-error-message-area.c.
References _, error, FALSE, MAX_URI_IN_DIALOG_LENGTH, NULL, PLUMA_DOCUMENT_ERROR, PLUMA_DOCUMENT_ERROR_CONVERSION_FALLBACK, PLUMA_DOCUMENT_ERROR_ENCODING_AUTO_DETECTION_FAILED, pluma_encoding_to_string(), pluma_utils_str_middle_truncate(), pluma_utils_uri_for_display(), and TRUE.
pluma_no_backup_saving_error_message_area_new()
GtkWidget * pluma_no_backup_saving_error_message_area_new (const gchar * uri, const GError * error)
Definition at line 921 of file pluma-io-error-message-area.c.
References _, error, FALSE, MAX_URI_IN_DIALOG_LENGTH, NULL, PLUMA_DOCUMENT_ERROR, PLUMA_DOCUMENT_ERROR_CANT_CREATE_BACKUP, PLUMA_SCHEMA_ID, PLUMA_SETTINGS_CREATE_BACKUP_COPY, pluma_utils_str_middle_truncate(), pluma_utils_uri_for_display(), and TRUE.
pluma_unrecoverable_reverting_error_message_area_new()
GtkWidget * pluma_unrecoverable_reverting_error_message_area_new (const gchar * uri, const GError * error)
Definition at line 377 of file pluma-io-error-message-area.c.
References _, error, FALSE, MAX_URI_IN_DIALOG_LENGTH, NULL, PLUMA_DOCUMENT_ERROR, pluma_utils_str_middle_truncate(), and pluma_utils_uri_for_display().
pluma_unrecoverable_saving_error_message_area_new()
GtkWidget * pluma_unrecoverable_saving_error_message_area_new (const gchar * uri, const GError * error)
Definition at line 1030 of file pluma-io-error-message-area.c.
References _, error, FALSE, MAX_URI_IN_DIALOG_LENGTH, NULL, PLUMA_DOCUMENT_ERROR, PLUMA_DOCUMENT_ERROR_TOO_BIG, pluma_utils_str_middle_truncate(), and pluma_utils_uri_for_display().