MATE Desktop Environment: pluma.c File Reference
pluma.c File Reference
#include <errno.h>
#include <locale.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
#include "pluma-app.h"
#include "pluma-application.h"
#include "pluma-commands.h"
#include "pluma-debug.h"
#include "pluma-dirs.h"
#include "pluma-encodings.h"
#include "pluma-plugins-engine.h"
#include "pluma-session.h"
#include "pluma-utils.h"
#include "pluma-window.h"
#include "pluma-settings.h"
#include "eggsmclient.h"
#include "eggdesktopfile.h"
#include "pluma-metadata-manager.h"
#include "bacon-message-connection.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 507 of file pluma.c.
References _, bacon_message_connection_free(), bacon_message_connection_get_is_server(), bacon_message_connection_new(), bacon_message_connection_set_callback(), connection, DEBUG_APP, egg_sm_client_get_option_group(), error, file_list, GETTEXT_PACKAGE, NULL, pluma_application_new(), pluma_application_set_command_line_options(), pluma_debug_init(), pluma_debug_message(), and TRUE.