MATE Desktop Environment: pluma-message.c File Reference
pluma-message.c File Reference
#include "pluma-message.h"
#include "pluma-message-type.h"
#include <string.h>
#include <gobject/gvaluecollector.h>
Enumerations
enum { PROP_0 , PROP_OBJECT_PATH , PROP_METHOD , PROP_TYPE }
Functions
const gchar * pluma_message_get_method (PlumaMessage *message)
const gchar * pluma_message_get_object_path (PlumaMessage *message)
void pluma_message_set (PlumaMessage *message,...)
void pluma_message_set_valist (PlumaMessage *message, va_list var_args)
void pluma_message_set_value (PlumaMessage *message, const gchar *key, GValue *value)
void pluma_message_set_valuesv (PlumaMessage *message, const gchar **keys, GValue *values, gint n_values)
void pluma_message_get (PlumaMessage *message,...)
void pluma_message_get_valist (PlumaMessage *message, va_list var_args)
void pluma_message_get_value (PlumaMessage *message, const gchar *key, GValue *value)
GType pluma_message_get_key_type (PlumaMessage *message, const gchar *key)
gboolean pluma_message_has_key (PlumaMessage *message, const gchar *key)
gboolean pluma_message_validate (PlumaMessage *message)
Enumeration Type Documentation
anonymous enum
anonymous enum
SECTION:pluma-message @short_description: message bus message object pluma/pluma-message.h
Communication on a PlumaMessageBus is done through messages. Messages are sent over the bus and received by connecting callbacks on the message bus. A PlumaMessage is an instantiation of a PlumaMessageType, containing values for the arguments as specified in the message type.
A message can be seen as a method call, or signal emission depending on who is the sender and who is the receiver. There is no explicit distinction between methods and signals.
Enumerator
PROP_0
PROP_OBJECT_PATH
PROP_METHOD
PROP_TYPE
Definition at line 22 of file pluma-message.c.
Function Documentation
pluma_message_get()
void pluma_message_get (PlumaMessage * message, ...)
pluma_message_get: @message: the PlumaMessage ...: a NULL variable argument list of key/value container pairs
Get values of message arguments. The supplied @var_args should contain pairs of keys and pointers to variables which are set to the argument value for the specified key.
Definition at line 399 of file pluma-message.c.
References message(), PLUMA_IS_MESSAGE, and pluma_message_get_valist().
pluma_message_get_key_type()
GType pluma_message_get_key_type (PlumaMessage * message, const gchar * key)
pluma_message_get_key_type: @message: the PlumaMessage @key: the argument key
Get the type of a message argument.
Return value: the type of @key
Definition at line 508 of file pluma-message.c.
References key, message(), NULL, PLUMA_IS_MESSAGE, and pluma_message_type_lookup().
Referenced by pluma_message_get_message_type().
pluma_message_get_method()
const gchar * pluma_message_get_method (PlumaMessage * message)
pluma_message_get_method: @message: the PlumaMessage
Get the message method.
Return value: the message method
Definition at line 236 of file pluma-message.c.
References message(), NULL, PLUMA_IS_MESSAGE, and pluma_message_type_get_method().
Referenced by pluma_message_get_message_type().
pluma_message_get_object_path()
const gchar * pluma_message_get_object_path (PlumaMessage * message)
pluma_message_get_object_path: @message: the PlumaMessage
Get the message object path.
Return value: the message object path
Definition at line 253 of file pluma-message.c.
References message(), NULL, PLUMA_IS_MESSAGE, and pluma_message_type_get_object_path().
Referenced by pluma_message_get_message_type().
pluma_message_get_valist()
void pluma_message_get_valist (PlumaMessage * message, va_list var_args)
pluma_message_get_valist: @message: the PlumaMessage @var_args: a NULL variable argument list of key/value container pairs
Get values of message arguments. The supplied @var_args should contain pairs of keys and pointers to variables which are set to the argument value for the specified key.
Definition at line 422 of file pluma-message.c.
References error, FALSE, key, message(), NULL, and PLUMA_IS_MESSAGE.
Referenced by pluma_message_get(), and pluma_message_get_message_type().
pluma_message_get_value()
void pluma_message_get_value (PlumaMessage * message, const gchar * key, GValue * value)
pluma_message_get_value: @message: the PlumaMessage @key: the argument key @value: (out): value return container
Get the value of a specific message argument. @value will be initialized with the correct type.
Definition at line 475 of file pluma-message.c.
References FALSE, key, message(), and PLUMA_IS_MESSAGE.
Referenced by pluma_message_get_message_type().
pluma_message_has_key()
gboolean pluma_message_has_key (PlumaMessage * message, const gchar * key)
pluma_message_has_key: @message: the PlumaMessage @key: the argument key
Check whether the message has a specific key.
Return value: TRUE if @message has argument @key
Definition at line 528 of file pluma-message.c.
References FALSE, key, message(), NULL, and PLUMA_IS_MESSAGE.
Referenced by pluma_message_get_message_type().
pluma_message_set()
void pluma_message_set (PlumaMessage * message, ...)
pluma_message_set: @message: the PlumaMessage ...: a NULL terminated variable list of key/value pairs
Set values of message arguments. The supplied @var_args should contain pairs of keys and argument values.
Definition at line 270 of file pluma-message.c.
References message(), PLUMA_IS_MESSAGE, and pluma_message_set_valist().
Referenced by pluma_message_get_message_type().
pluma_message_set_valist()
void pluma_message_set_valist (PlumaMessage * message, va_list var_args)
pluma_message_set_valist: @message: the PlumaMessage @var_args: a NULL terminated variable list of key/value pairs
Set values of message arguments. The supplied @var_args should contain pairs of keys and argument values.
Definition at line 292 of file pluma-message.c.
References error, key, message(), NULL, PLUMA_IS_MESSAGE, and TRUE.
Referenced by pluma_message_get_message_type(), pluma_message_set(), and pluma_message_type_instantiate_valist().
pluma_message_set_value()
void pluma_message_set_value (PlumaMessage * message, const gchar * key, GValue * value)
pluma_message_set_value: @message: the PlumaMessage @key: the argument key @value: (out): the argument value
Set value of message argument @key to @value.
Definition at line 341 of file pluma-message.c.
References key, message(), PLUMA_IS_MESSAGE, and TRUE.
Referenced by pluma_message_get_message_type(), and pluma_message_set_valuesv().
pluma_message_set_valuesv()
void pluma_message_set_valuesv (PlumaMessage * message, const gchar ** keys, GValue * values, gint n_values)
pluma_message_set_valuesv: @message: the PlumaMessage @keys: (array length=n_values): keys to set values for @values: (array length=n_values): values to set @n_values: number of arguments to set values for
Set message argument values.
Definition at line 372 of file pluma-message.c.
References message(), PLUMA_IS_MESSAGE, and pluma_message_set_value().
Referenced by pluma_message_get_message_type().
pluma_message_validate()
gboolean pluma_message_validate (PlumaMessage * message)
pluma_message_validate: @message: the PlumaMessage
Validates the message arguments according to the message type.
Return value: TRUE if the message is valid
Definition at line 569 of file pluma-message.c.
References FALSE, message(), NULL, PLUMA_IS_MESSAGE, pluma_message_type_foreach(), and TRUE.
Referenced by pluma_message_get_message_type().