MATE Desktop Environment: pluma-spell-checker-dialog.c File Reference
pluma-spell-checker-dialog.c File Reference
#include <string.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <pluma/pluma-utils.h>
#include "pluma-spell-checker-dialog.h"
Enumerations
enum {
IGNORE , IGNORE_ALL , CHANGE , CHANGE_ALL ,
ADD_WORD_TO_PERSONAL , LAST_SIGNAL
}
enum { COLUMN_SUGGESTIONS , NUM_COLUMNS }
Functions
GtkWidget * pluma_spell_checker_dialog_new (const gchar *data_dir)
GtkWidget * pluma_spell_checker_dialog_new_from_spell_checker (PlumaSpellChecker *spell, const gchar *data_dir)
void pluma_spell_checker_dialog_set_spell_checker (PlumaSpellCheckerDialog *dlg, PlumaSpellChecker *spell)
void pluma_spell_checker_dialog_set_misspelled_word (PlumaSpellCheckerDialog *dlg, const gchar *word, gint len)
void pluma_spell_checker_dialog_set_completed (PlumaSpellCheckerDialog *dlg)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
IGNORE
IGNORE_ALL
CHANGE
CHANGE_ALL
ADD_WORD_TO_PERSONAL
LAST_SIGNAL
Definition at line 64 of file pluma-spell-checker-dialog.c.
anonymous enum
anonymous enum
Enumerator
COLUMN_SUGGESTIONS
NUM_COLUMNS
Definition at line 74 of file pluma-spell-checker-dialog.c.
Function Documentation
pluma_spell_checker_dialog_new()
GtkWidget * pluma_spell_checker_dialog_new (const gchar * data_dir)
Definition at line 327 of file pluma-spell-checker-dialog.c.
References NULL, PLUMA_SPELL_CHECKER_DIALOG, and PLUMA_TYPE_SPELL_CHECKER_DIALOG.
pluma_spell_checker_dialog_new_from_spell_checker()
GtkWidget * pluma_spell_checker_dialog_new_from_spell_checker (PlumaSpellChecker * spell, const gchar * data_dir)
Definition at line 342 of file pluma-spell-checker-dialog.c.
References NULL, PLUMA_SPELL_CHECKER_DIALOG, pluma_spell_checker_dialog_set_spell_checker(), and PLUMA_TYPE_SPELL_CHECKER_DIALOG.
pluma_spell_checker_dialog_set_completed()
void pluma_spell_checker_dialog_set_completed (PlumaSpellCheckerDialog * dlg)
Definition at line 699 of file pluma-spell-checker-dialog.c.
References _, FALSE, and PLUMA_IS_SPELL_CHECKER_DIALOG.
pluma_spell_checker_dialog_set_misspelled_word()
void pluma_spell_checker_dialog_set_misspelled_word (PlumaSpellCheckerDialog * dlg, const gchar * word, gint len)
Definition at line 394 of file pluma-spell-checker-dialog.c.
References NULL, PLUMA_IS_SPELL_CHECKER_DIALOG, pluma_spell_checker_check_word(), pluma_spell_checker_get_suggestions(), and TRUE.
Referenced by pluma_spell_checker_dialog_set_spell_checker().
pluma_spell_checker_dialog_set_spell_checker()
void pluma_spell_checker_dialog_set_spell_checker (PlumaSpellCheckerDialog * dlg, PlumaSpellChecker * spell)
Definition at line 362 of file pluma-spell-checker-dialog.c.
References NULL, PLUMA_IS_SPELL_CHECKER_DIALOG, pluma_spell_checker_dialog_set_misspelled_word(), pluma_spell_checker_get_language(), and pluma_spell_checker_language_to_string().
Referenced by pluma_spell_checker_dialog_new_from_spell_checker().