MATE Desktop Environment: pluma-file-chooser-dialog.h File Reference
pluma-file-chooser-dialog.h File Reference
#include <gtk/gtk.h>
#include <pluma/pluma-encodings.h>
#include <pluma/pluma-enum-types.h>
#include <pluma/pluma-document.h>
Classes
struct _PlumaFileChooserDialogClass
struct _PlumaFileChooserDialog
Macros
#define PLUMA_TYPE_FILE_CHOOSER_DIALOG (pluma_file_chooser_dialog_get_type ())
#define PLUMA_FILE_CHOOSER_DIALOG(obj)
#define PLUMA_FILE_CHOOSER_DIALOG_CLASS(klass)
#define PLUMA_IS_FILE_CHOOSER_DIALOG(obj)
#define PLUMA_IS_FILE_CHOOSER_DIALOG_CLASS(klass)
#define PLUMA_FILE_CHOOSER_DIALOG_GET_CLASS(obj)
Typedefs
typedef struct _PlumaFileChooserDialog PlumaFileChooserDialog
typedef struct _PlumaFileChooserDialogClass PlumaFileChooserDialogClass
typedef struct _PlumaFileChooserDialogPrivate PlumaFileChooserDialogPrivate
Functions
GType pluma_file_chooser_dialog_get_type (void)
GtkWidget * pluma_file_chooser_dialog_new (const gchar *title, GtkWindow *parent, GtkFileChooserAction action, const PlumaEncoding *encoding, const gchar *first_button_text,...)
void pluma_file_chooser_dialog_set_encoding (PlumaFileChooserDialog *dialog, const PlumaEncoding *encoding)
const PlumaEncoding * pluma_file_chooser_dialog_get_encoding (PlumaFileChooserDialog *dialog)
void pluma_file_chooser_dialog_set_newline_type (PlumaFileChooserDialog *dialog, PlumaDocumentNewlineType newline_type)
PlumaDocumentNewlineType pluma_file_chooser_dialog_get_newline_type (PlumaFileChooserDialog *dialog)
Macro Definition Documentation
PLUMA_FILE_CHOOSER_DIALOG
#define PLUMA_FILE_CHOOSER_DIALOG (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_FILE_CHOOSER_DIALOG, PlumaFileChooserDialog))
Definition at line 44 of file pluma-file-chooser-dialog.h.
PLUMA_FILE_CHOOSER_DIALOG_CLASS
#define PLUMA_FILE_CHOOSER_DIALOG_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), PLUMA_TYPE_FILE_CHOOSER_DIALOG, PlumaFileChooserDialogClass))
Definition at line 45 of file pluma-file-chooser-dialog.h.
PLUMA_FILE_CHOOSER_DIALOG_GET_CLASS
#define PLUMA_FILE_CHOOSER_DIALOG_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), PLUMA_TYPE_FILE_CHOOSER_DIALOG, PlumaFileChooserDialogClass))
Definition at line 48 of file pluma-file-chooser-dialog.h.
PLUMA_IS_FILE_CHOOSER_DIALOG
#define PLUMA_IS_FILE_CHOOSER_DIALOG (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLUMA_TYPE_FILE_CHOOSER_DIALOG))
Definition at line 46 of file pluma-file-chooser-dialog.h.
Referenced by _pluma_cmd_file_open(), pluma_file_chooser_dialog_get_encoding(), pluma_file_chooser_dialog_get_newline_type(), pluma_file_chooser_dialog_set_encoding(), and pluma_file_chooser_dialog_set_newline_type().
PLUMA_IS_FILE_CHOOSER_DIALOG_CLASS
#define PLUMA_IS_FILE_CHOOSER_DIALOG_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_FILE_CHOOSER_DIALOG))
Definition at line 47 of file pluma-file-chooser-dialog.h.
PLUMA_TYPE_FILE_CHOOSER_DIALOG
#define PLUMA_TYPE_FILE_CHOOSER_DIALOG (pluma_file_chooser_dialog_get_type ())
Definition at line 43 of file pluma-file-chooser-dialog.h.
Typedef Documentation
PlumaFileChooserDialog
typedef struct _PlumaFileChooserDialog PlumaFileChooserDialog
Definition at line 50 of file pluma-file-chooser-dialog.h.
PlumaFileChooserDialogClass
typedef struct _PlumaFileChooserDialogClass PlumaFileChooserDialogClass
Definition at line 51 of file pluma-file-chooser-dialog.h.
PlumaFileChooserDialogPrivate
typedef struct _PlumaFileChooserDialogPrivate PlumaFileChooserDialogPrivate
Definition at line 53 of file pluma-file-chooser-dialog.h.
Function Documentation
pluma_file_chooser_dialog_get_encoding()
const PlumaEncoding * pluma_file_chooser_dialog_get_encoding (PlumaFileChooserDialog * dialog)
Definition at line 522 of file pluma-file-chooser-dialog.c.
References NULL, PLUMA_ENCODINGS_COMBO_BOX, pluma_encodings_combo_box_get_selected_encoding(), PLUMA_IS_ENCODINGS_COMBO_BOX, and PLUMA_IS_FILE_CHOOSER_DIALOG.
pluma_file_chooser_dialog_get_newline_type()
PlumaDocumentNewlineType pluma_file_chooser_dialog_get_newline_type (PlumaFileChooserDialog * dialog)
Definition at line 566 of file pluma-file-chooser-dialog.c.
References PLUMA_DOCUMENT_NEWLINE_TYPE_DEFAULT, and PLUMA_IS_FILE_CHOOSER_DIALOG.
pluma_file_chooser_dialog_get_type()
GType pluma_file_chooser_dialog_get_type (void)
References action.
pluma_file_chooser_dialog_new()
GtkWidget * pluma_file_chooser_dialog_new (const gchar * title, GtkWindow * parent, GtkFileChooserAction action, const PlumaEncoding * encoding, const gchar * first_button_text, ...)
pluma_file_chooser_dialog_new: @title: (allow-none): Title of the dialog, or NULL @parent: (allow-none): Transient parent of the dialog, or NULL @action: Open or save mode for the dialog @first_button_text: (allow-none): icon name or text to go in the first button, or NULL ...: (allow-none): response ID for the first button, then additional (button, id) pairs, ending with NULL
Creates a new PlumaFileChooserDialog. This function is analogous to gtk_dialog_new_with_buttons().
Return value: a new PlumaFileChooserDialog
Definition at line 490 of file pluma-file-chooser-dialog.c.
References action.
Referenced by _pluma_cmd_file_open().
pluma_file_chooser_dialog_set_encoding()
void pluma_file_chooser_dialog_set_encoding (PlumaFileChooserDialog * dialog, const PlumaEncoding * encoding)
Definition at line 510 of file pluma-file-chooser-dialog.c.
References PLUMA_ENCODINGS_COMBO_BOX, pluma_encodings_combo_box_set_selected_encoding(), PLUMA_IS_ENCODINGS_COMBO_BOX, and PLUMA_IS_FILE_CHOOSER_DIALOG.
pluma_file_chooser_dialog_set_newline_type()
void pluma_file_chooser_dialog_set_newline_type (PlumaFileChooserDialog * dialog, PlumaDocumentNewlineType newline_type)
Definition at line 534 of file pluma-file-chooser-dialog.c.
References PLUMA_IS_FILE_CHOOSER_DIALOG.