MATE Desktop Environment: pluma-document-loader.h File Reference
pluma-document-loader.h File Reference
#include <pluma/pluma-document.h>
Classes
struct _PlumaDocumentLoader
struct _PlumaDocumentLoaderClass
Macros
#define PLUMA_TYPE_DOCUMENT_LOADER (pluma_document_loader_get_type())
#define PLUMA_DOCUMENT_LOADER(obj)
#define PLUMA_DOCUMENT_LOADER_CLASS(klass)
#define PLUMA_IS_DOCUMENT_LOADER(obj)
#define PLUMA_IS_DOCUMENT_LOADER_CLASS(klass)
#define PLUMA_DOCUMENT_LOADER_GET_CLASS(obj)
#define STDIN_URI "stdin:"
Typedefs
typedef struct _PlumaDocumentLoaderPrivate PlumaDocumentLoaderPrivate
typedef struct _PlumaDocumentLoader PlumaDocumentLoader
typedef struct _PlumaDocumentLoaderClass PlumaDocumentLoaderClass
Functions
GType pluma_document_loader_get_type (void)
PlumaDocumentLoader * pluma_document_loader_new (PlumaDocument *doc, const gchar *uri, const PlumaEncoding *encoding)
void pluma_document_loader_loading (PlumaDocumentLoader *loader, gboolean completed, GError *error)
void pluma_document_loader_load (PlumaDocumentLoader *loader)
gboolean pluma_document_loader_cancel (PlumaDocumentLoader *loader)
PlumaDocument * pluma_document_loader_get_document (PlumaDocumentLoader *loader)
const gchar * pluma_document_loader_get_uri (PlumaDocumentLoader *loader)
const PlumaEncoding * pluma_document_loader_get_encoding (PlumaDocumentLoader *loader)
PlumaDocumentNewlineType pluma_document_loader_get_newline_type (PlumaDocumentLoader *loader)
goffset pluma_document_loader_get_bytes_read (PlumaDocumentLoader *loader)
GFileInfo * pluma_document_loader_get_info (PlumaDocumentLoader *loader)
Macro Definition Documentation
PLUMA_DOCUMENT_LOADER
#define PLUMA_DOCUMENT_LOADER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_DOCUMENT_LOADER, PlumaDocumentLoader))
Definition at line 44 of file pluma-document-loader.h.
Referenced by pluma_document_loader_load(), and pluma_document_loader_new().
PLUMA_DOCUMENT_LOADER_CLASS
#define PLUMA_DOCUMENT_LOADER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST((klass), PLUMA_TYPE_DOCUMENT_LOADER, PlumaDocumentLoaderClass))
Definition at line 45 of file pluma-document-loader.h.
PLUMA_DOCUMENT_LOADER_GET_CLASS
#define PLUMA_DOCUMENT_LOADER_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS((obj), PLUMA_TYPE_DOCUMENT_LOADER, PlumaDocumentLoaderClass))
Definition at line 48 of file pluma-document-loader.h.
PLUMA_IS_DOCUMENT_LOADER
#define PLUMA_IS_DOCUMENT_LOADER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE((obj), PLUMA_TYPE_DOCUMENT_LOADER))
Definition at line 46 of file pluma-document-loader.h.
Referenced by pluma_document_loader_cancel(), pluma_document_loader_get_bytes_read(), pluma_document_loader_get_document(), pluma_document_loader_get_encoding(), pluma_document_loader_get_info(), pluma_document_loader_get_newline_type(), pluma_document_loader_get_uri(), and pluma_document_loader_load().
PLUMA_IS_DOCUMENT_LOADER_CLASS
#define PLUMA_IS_DOCUMENT_LOADER_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_DOCUMENT_LOADER))
Definition at line 47 of file pluma-document-loader.h.
PLUMA_TYPE_DOCUMENT_LOADER
#define PLUMA_TYPE_DOCUMENT_LOADER (pluma_document_loader_get_type())
Definition at line 43 of file pluma-document-loader.h.
Referenced by pluma_document_loader_new().
STDIN_URI
#define STDIN_URI "stdin:"
Definition at line 102 of file pluma-document-loader.h.
Typedef Documentation
PlumaDocumentLoader
typedef struct _PlumaDocumentLoader PlumaDocumentLoader
Definition at line 56 of file pluma-document-loader.h.
PlumaDocumentLoaderClass
typedef struct _PlumaDocumentLoaderClass PlumaDocumentLoaderClass
Definition at line 67 of file pluma-document-loader.h.
PlumaDocumentLoaderPrivate
typedef struct _PlumaDocumentLoaderPrivate PlumaDocumentLoaderPrivate
Definition at line 51 of file pluma-document-loader.h.
Function Documentation
pluma_document_loader_cancel()
gboolean pluma_document_loader_cancel (PlumaDocumentLoader * loader)
Definition at line 867 of file pluma-document-loader.c.
References DEBUG_LOADER, FALSE, NULL, pluma_debug(), PLUMA_IS_DOCUMENT_LOADER, _PlumaDocumentLoader::priv, and TRUE.
Referenced by pluma_document_load_cancel().
pluma_document_loader_get_bytes_read()
goffset pluma_document_loader_get_bytes_read (PlumaDocumentLoader * loader)
Definition at line 906 of file pluma-document-loader.c.
References PLUMA_IS_DOCUMENT_LOADER, and _PlumaDocumentLoader::priv.
pluma_document_loader_get_document()
PlumaDocument * pluma_document_loader_get_document (PlumaDocumentLoader * loader)
Definition at line 889 of file pluma-document-loader.c.
References NULL, PLUMA_IS_DOCUMENT_LOADER, and _PlumaDocumentLoader::priv.
pluma_document_loader_get_encoding()
const PlumaEncoding * pluma_document_loader_get_encoding (PlumaDocumentLoader * loader)
Definition at line 914 of file pluma-document-loader.c.
References NULL, pluma_encoding_get_current(), PLUMA_IS_DOCUMENT_LOADER, and _PlumaDocumentLoader::priv.
pluma_document_loader_get_info()
GFileInfo * pluma_document_loader_get_info (PlumaDocumentLoader * loader)
Definition at line 937 of file pluma-document-loader.c.
References NULL, PLUMA_IS_DOCUMENT_LOADER, and _PlumaDocumentLoader::priv.
pluma_document_loader_get_newline_type()
PlumaDocumentNewlineType pluma_document_loader_get_newline_type (PlumaDocumentLoader * loader)
Definition at line 928 of file pluma-document-loader.c.
References PLUMA_DOCUMENT_NEWLINE_TYPE_LF, PLUMA_IS_DOCUMENT_LOADER, and _PlumaDocumentLoader::priv.
pluma_document_loader_get_type()
GType pluma_document_loader_get_type (void)
References error.
pluma_document_loader_get_uri()
const gchar * pluma_document_loader_get_uri (PlumaDocumentLoader * loader)
Definition at line 898 of file pluma-document-loader.c.
References NULL, PLUMA_IS_DOCUMENT_LOADER, and _PlumaDocumentLoader::priv.
pluma_document_loader_load()
void pluma_document_loader_load (PlumaDocumentLoader * loader)
Definition at line 838 of file pluma-document-loader.c.
References DEBUG_LOADER, FALSE, NULL, pluma_debug(), PLUMA_DOCUMENT_LOADER, pluma_document_loader_loading(), PLUMA_IS_DOCUMENT_LOADER, _PlumaDocumentLoader::priv, and TRUE.
pluma_document_loader_loading()
void pluma_document_loader_loading (PlumaDocumentLoader * loader, gboolean completed, GError * error)
Definition at line 811 of file pluma-document-loader.c.
References DEBUG_LOADER, error, LOADING, NULL, and pluma_debug_message().
Referenced by pluma_document_loader_load().
pluma_document_loader_new()
PlumaDocumentLoader * pluma_document_loader_new (PlumaDocument * doc, const gchar * uri, const PlumaEncoding * encoding)
Definition at line 315 of file pluma-document-loader.c.
References NULL, PLUMA_DOCUMENT_LOADER, PLUMA_IS_DOCUMENT, and PLUMA_TYPE_DOCUMENT_LOADER.