MATE Desktop Environment: pluma-encodings-combo-box.c File Reference
pluma-encodings-combo-box.c File Reference
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <pluma/pluma-encodings-combo-box.h>
#include <pluma/dialogs/pluma-encodings-dialog.h>
#include "pluma-settings.h"
#include "pluma-utils.h"
Enumerations
enum { NAME_COLUMN , ENCODING_COLUMN , ADD_COLUMN , N_COLUMNS }
enum { PROP_0 , PROP_SAVE_MODE }
Functions
GtkWidget * pluma_encodings_combo_box_new (gboolean save_mode)
const PlumaEncoding * pluma_encodings_combo_box_get_selected_encoding (PlumaEncodingsComboBox *menu)
void pluma_encodings_combo_box_set_selected_encoding (PlumaEncodingsComboBox *menu, const PlumaEncoding *encoding)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NAME_COLUMN
ENCODING_COLUMN
ADD_COLUMN
N_COLUMNS
Definition at line 57 of file pluma-encodings-combo-box.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_SAVE_MODE
Definition at line 66 of file pluma-encodings-combo-box.c.
Function Documentation
pluma_encodings_combo_box_get_selected_encoding()
const PlumaEncoding * pluma_encodings_combo_box_get_selected_encoding (PlumaEncodingsComboBox * menu)
Definition at line 422 of file pluma-encodings-combo-box.c.
References ENCODING_COLUMN, NULL, and PLUMA_IS_ENCODINGS_COMBO_BOX.
Referenced by pluma_conversion_error_message_area_get_encoding(), and pluma_file_chooser_dialog_get_encoding().
pluma_encodings_combo_box_new()
GtkWidget * pluma_encodings_combo_box_new (gboolean save_mode)
Definition at line 414 of file pluma-encodings-combo-box.c.
References NULL, and PLUMA_TYPE_ENCODINGS_COMBO_BOX.
pluma_encodings_combo_box_set_selected_encoding()
void pluma_encodings_combo_box_set_selected_encoding (PlumaEncodingsComboBox * menu, const PlumaEncoding * encoding)
pluma_encodings_combo_box_set_selected_encoding: @menu: @encoding: (allow-none):
Definition at line 451 of file pluma-encodings-combo-box.c.
References b, ENCODING_COLUMN, and PLUMA_IS_ENCODINGS_COMBO_BOX.
Referenced by pluma_file_chooser_dialog_set_encoding().