MATE Desktop Environment: pluma-file-browser-utils.c File Reference
pluma-file-browser-utils.c File Reference
#include "pluma-file-browser-utils.h"
#include <pluma/pluma-utils.h>
#include <glib/gi18n.h>
Functions
GdkPixbuf * pluma_file_browser_utils_pixbuf_from_theme (gchar const *name, GtkIconSize size)
GdkPixbuf * pluma_file_browser_utils_pixbuf_from_icon (GIcon *icon, GtkIconSize size)
GdkPixbuf * pluma_file_browser_utils_pixbuf_from_file (GFile *file, GtkIconSize size)
gchar * pluma_file_browser_utils_file_basename (GFile *file)
gchar * pluma_file_browser_utils_uri_basename (gchar const *uri)
gboolean pluma_file_browser_utils_confirmation_dialog (PlumaWindow *window, GtkMessageType type, gchar const *message, gchar const *secondary)
Function Documentation
pluma_file_browser_utils_confirmation_dialog()
gboolean pluma_file_browser_utils_confirmation_dialog (PlumaWindow * window, GtkMessageType type, gchar const * message, gchar const * secondary)
Definition at line 152 of file pluma-file-browser-utils.c.
References _, message(), and TRUE.
pluma_file_browser_utils_file_basename()
gchar * pluma_file_browser_utils_file_basename (GFile * file)
Definition at line 133 of file pluma-file-browser-utils.c.
References pluma_file_browser_utils_uri_basename().
pluma_file_browser_utils_pixbuf_from_file()
GdkPixbuf * pluma_file_browser_utils_pixbuf_from_file (GFile * file, GtkIconSize size)
Definition at line 107 of file pluma-file-browser-utils.c.
References NULL, and pluma_file_browser_utils_pixbuf_from_icon().
pluma_file_browser_utils_pixbuf_from_icon()
GdkPixbuf * pluma_file_browser_utils_pixbuf_from_icon (GIcon * icon, GtkIconSize size)
Definition at line 78 of file pluma-file-browser-utils.c.
References NULL.
Referenced by pluma_file_browser_utils_pixbuf_from_file().
pluma_file_browser_utils_pixbuf_from_theme()
GdkPixbuf * pluma_file_browser_utils_pixbuf_from_theme (gchar const * name, GtkIconSize size)
Definition at line 57 of file pluma-file-browser-utils.c.
References error, name, and NULL.
pluma_file_browser_utils_uri_basename()
gchar * pluma_file_browser_utils_uri_basename (gchar const * uri)
Definition at line 146 of file pluma-file-browser-utils.c.
References pluma_utils_basename_for_display().
Referenced by pluma_file_browser_utils_file_basename().