MATE Desktop Environment: pluma-file-browser-widget.h File Reference
pluma-file-browser-widget.h File Reference
#include <gtk/gtk.h>
#include "pluma-file-browser-store.h"
#include "pluma-file-bookmarks-store.h"
#include "pluma-file-browser-view.h"
Classes
struct _PlumaFileBrowserWidget
struct _PlumaFileBrowserWidgetClass
Macros
#define PLUMA_TYPE_FILE_BROWSER_WIDGET (pluma_file_browser_widget_get_type ())
#define PLUMA_FILE_BROWSER_WIDGET(obj)
#define PLUMA_FILE_BROWSER_WIDGET_CONST(obj)
#define PLUMA_FILE_BROWSER_WIDGET_CLASS(klass)
#define PLUMA_IS_FILE_BROWSER_WIDGET(obj)
#define PLUMA_IS_FILE_BROWSER_WIDGET_CLASS(klass)
#define PLUMA_FILE_BROWSER_WIDGET_GET_CLASS(obj)
Typedefs
typedef struct _PlumaFileBrowserWidget PlumaFileBrowserWidget
typedef struct _PlumaFileBrowserWidgetClass PlumaFileBrowserWidgetClass
typedef struct _PlumaFileBrowserWidgetPrivate PlumaFileBrowserWidgetPrivate
typedef gboolean(* PlumaFileBrowserWidgetFilterFunc) (PlumaFileBrowserWidget *obj, PlumaFileBrowserStore *model, GtkTreeIter *iter, gpointer user_data)
Functions
GType pluma_file_browser_widget_get_type (void)
void _pluma_file_browser_widget_register_type (GTypeModule *module)
GtkWidget * pluma_file_browser_widget_new (const gchar *data_dir)
void pluma_file_browser_widget_show_bookmarks (PlumaFileBrowserWidget *obj)
void pluma_file_browser_widget_show_files (PlumaFileBrowserWidget *obj)
void pluma_file_browser_widget_set_root (PlumaFileBrowserWidget *obj, gchar const *root, gboolean virtual_root)
void pluma_file_browser_widget_set_root_and_virtual_root (PlumaFileBrowserWidget *obj, gchar const *root, gchar const *virtual_root)
gboolean pluma_file_browser_widget_get_selected_directory (PlumaFileBrowserWidget *obj, GtkTreeIter *iter)
PlumaFileBrowserStore * pluma_file_browser_widget_get_browser_store (PlumaFileBrowserWidget *obj)
PlumaFileBookmarksStore * pluma_file_browser_widget_get_bookmarks_store (PlumaFileBrowserWidget *obj)
PlumaFileBrowserView * pluma_file_browser_widget_get_browser_view (PlumaFileBrowserWidget *obj)
GtkWidget * pluma_file_browser_widget_get_filter_entry (PlumaFileBrowserWidget *obj)
GtkUIManager * pluma_file_browser_widget_get_ui_manager (PlumaFileBrowserWidget *obj)
gulong pluma_file_browser_widget_add_filter (PlumaFileBrowserWidget *obj, PlumaFileBrowserWidgetFilterFunc func, gpointer user_data, GDestroyNotify notify)
void pluma_file_browser_widget_remove_filter (PlumaFileBrowserWidget *obj, gulong id)
void pluma_file_browser_widget_set_filter_pattern (PlumaFileBrowserWidget *obj, gchar const *pattern)
void pluma_file_browser_widget_refresh (PlumaFileBrowserWidget *obj)
void pluma_file_browser_widget_history_back (PlumaFileBrowserWidget *obj)
void pluma_file_browser_widget_history_forward (PlumaFileBrowserWidget *obj)
Macro Definition Documentation
PLUMA_FILE_BROWSER_WIDGET
#define PLUMA_FILE_BROWSER_WIDGET (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_FILE_BROWSER_WIDGET, PlumaFileBrowserWidget))
Definition at line 33 of file pluma-file-browser-widget.h.
PLUMA_FILE_BROWSER_WIDGET_CLASS
#define PLUMA_FILE_BROWSER_WIDGET_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), PLUMA_TYPE_FILE_BROWSER_WIDGET, PlumaFileBrowserWidgetClass))
Definition at line 35 of file pluma-file-browser-widget.h.
PLUMA_FILE_BROWSER_WIDGET_CONST
#define PLUMA_FILE_BROWSER_WIDGET_CONST (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_FILE_BROWSER_WIDGET, PlumaFileBrowserWidget const))
Definition at line 34 of file pluma-file-browser-widget.h.
PLUMA_FILE_BROWSER_WIDGET_GET_CLASS
#define PLUMA_FILE_BROWSER_WIDGET_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), PLUMA_TYPE_FILE_BROWSER_WIDGET, PlumaFileBrowserWidgetClass))
Definition at line 38 of file pluma-file-browser-widget.h.
PLUMA_IS_FILE_BROWSER_WIDGET
#define PLUMA_IS_FILE_BROWSER_WIDGET (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLUMA_TYPE_FILE_BROWSER_WIDGET))
Definition at line 36 of file pluma-file-browser-widget.h.
PLUMA_IS_FILE_BROWSER_WIDGET_CLASS
#define PLUMA_IS_FILE_BROWSER_WIDGET_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_FILE_BROWSER_WIDGET))
Definition at line 37 of file pluma-file-browser-widget.h.
PLUMA_TYPE_FILE_BROWSER_WIDGET
#define PLUMA_TYPE_FILE_BROWSER_WIDGET (pluma_file_browser_widget_get_type ())
Definition at line 32 of file pluma-file-browser-widget.h.
Referenced by pluma_file_browser_widget_new().
Typedef Documentation
PlumaFileBrowserWidget
typedef struct _PlumaFileBrowserWidget PlumaFileBrowserWidget
Definition at line 40 of file pluma-file-browser-widget.h.
PlumaFileBrowserWidgetClass
typedef struct _PlumaFileBrowserWidgetClass PlumaFileBrowserWidgetClass
Definition at line 41 of file pluma-file-browser-widget.h.
PlumaFileBrowserWidgetFilterFunc
typedef gboolean(* PlumaFileBrowserWidgetFilterFunc) (PlumaFileBrowserWidget *obj, PlumaFileBrowserStore *model, GtkTreeIter *iter, gpointer user_data)
Definition at line 45 of file pluma-file-browser-widget.h.
PlumaFileBrowserWidgetPrivate
typedef struct _PlumaFileBrowserWidgetPrivate PlumaFileBrowserWidgetPrivate
Definition at line 42 of file pluma-file-browser-widget.h.
Function Documentation
_pluma_file_browser_widget_register_type()
void _pluma_file_browser_widget_register_type (GTypeModule * module)
Definition at line 3160 of file pluma-file-browser-widget.c.
pluma_file_browser_widget_add_filter()
gulong pluma_file_browser_widget_add_filter (PlumaFileBrowserWidget * obj, PlumaFileBrowserWidgetFilterFunc func, gpointer user_data, GDestroyNotify notify)
Definition at line 1940 of file pluma-file-browser-widget.c.
References PLUMA_FILE_BROWSER_STORE, pluma_file_browser_store_refilter(), PLUMA_IS_FILE_BROWSER_STORE, _PlumaFileBrowserWidget::priv, and user_data.
pluma_file_browser_widget_get_bookmarks_store()
PlumaFileBookmarksStore * pluma_file_browser_widget_get_bookmarks_store (PlumaFileBrowserWidget * obj)
Definition at line 1916 of file pluma-file-browser-widget.c.
References _PlumaFileBrowserWidget::priv.
pluma_file_browser_widget_get_browser_store()
PlumaFileBrowserStore * pluma_file_browser_widget_get_browser_store (PlumaFileBrowserWidget * obj)
Definition at line 1910 of file pluma-file-browser-widget.c.
References _PlumaFileBrowserWidget::priv.
pluma_file_browser_widget_get_browser_view()
PlumaFileBrowserView * pluma_file_browser_widget_get_browser_view (PlumaFileBrowserWidget * obj)
Definition at line 1922 of file pluma-file-browser-widget.c.
References _PlumaFileBrowserWidget::priv.
pluma_file_browser_widget_get_filter_entry()
GtkWidget * pluma_file_browser_widget_get_filter_entry (PlumaFileBrowserWidget * obj)
Definition at line 1934 of file pluma-file-browser-widget.c.
References _PlumaFileBrowserWidget::priv.
pluma_file_browser_widget_get_selected_directory()
gboolean pluma_file_browser_widget_get_selected_directory (PlumaFileBrowserWidget * obj, GtkTreeIter * iter)
Definition at line 1993 of file pluma-file-browser-widget.c.
References FALSE, FILE_IS_DIR, PLUMA_FILE_BROWSER_STORE, PLUMA_FILE_BROWSER_STORE_COLUMN_FLAGS, pluma_file_browser_store_get_iter_virtual_root(), PLUMA_IS_FILE_BROWSER_STORE, _PlumaFileBrowserWidget::priv, and TRUE.
pluma_file_browser_widget_get_type()
GType pluma_file_browser_widget_get_type (void)
References user_data.
pluma_file_browser_widget_get_ui_manager()
GtkUIManager * pluma_file_browser_widget_get_ui_manager (PlumaFileBrowserWidget * obj)
Definition at line 1928 of file pluma-file-browser-widget.c.
References _PlumaFileBrowserWidget::priv.
pluma_file_browser_widget_history_back()
void pluma_file_browser_widget_history_back (PlumaFileBrowserWidget * obj)
Definition at line 2363 of file pluma-file-browser-widget.c.
References _PlumaFileBrowserWidget::priv, and TRUE.
pluma_file_browser_widget_history_forward()
void pluma_file_browser_widget_history_forward (PlumaFileBrowserWidget * obj)
Definition at line 2377 of file pluma-file-browser-widget.c.
References FALSE, and _PlumaFileBrowserWidget::priv.
pluma_file_browser_widget_new()
GtkWidget * pluma_file_browser_widget_new (const gchar * data_dir)
Definition at line 1807 of file pluma-file-browser-widget.c.
References NULL, pluma_file_browser_widget_show_bookmarks(), and PLUMA_TYPE_FILE_BROWSER_WIDGET.
pluma_file_browser_widget_refresh()
void pluma_file_browser_widget_refresh (PlumaFileBrowserWidget * obj)
Definition at line 2345 of file pluma-file-browser-widget.c.
References PLUMA_FILE_BOOKMARKS_STORE, pluma_file_bookmarks_store_refresh(), PLUMA_FILE_BROWSER_STORE, pluma_file_browser_store_refresh(), PLUMA_IS_FILE_BOOKMARKS_STORE, PLUMA_IS_FILE_BROWSER_STORE, and _PlumaFileBrowserWidget::priv.
pluma_file_browser_widget_remove_filter()
void pluma_file_browser_widget_remove_filter (PlumaFileBrowserWidget * obj, gulong id)
Definition at line 1961 of file pluma-file-browser-widget.c.
References item, and _PlumaFileBrowserWidget::priv.
pluma_file_browser_widget_set_filter_pattern()
void pluma_file_browser_widget_set_filter_pattern (PlumaFileBrowserWidget * obj, gchar const * pattern)
Definition at line 1986 of file pluma-file-browser-widget.c.
References TRUE.
pluma_file_browser_widget_set_root()
void pluma_file_browser_widget_set_root (PlumaFileBrowserWidget * obj, gchar const * root, gboolean virtual_root)
Definition at line 1878 of file pluma-file-browser-widget.c.
References NULL, and pluma_file_browser_widget_set_root_and_virtual_root().
pluma_file_browser_widget_set_root_and_virtual_root()
void pluma_file_browser_widget_set_root_and_virtual_root (PlumaFileBrowserWidget * obj, gchar const * root, gchar const * virtual_root)
Definition at line 1858 of file pluma-file-browser-widget.c.
References PLUMA_FILE_BROWSER_STORE_RESULT_NO_CHANGE, pluma_file_browser_store_set_root_and_virtual_root(), _PlumaFileBrowserWidget::priv, and TRUE.
Referenced by pluma_file_browser_widget_set_root().
pluma_file_browser_widget_show_bookmarks()
void pluma_file_browser_widget_show_bookmarks (PlumaFileBrowserWidget * obj)
Definition at line 1823 of file pluma-file-browser-widget.c.
References BOOKMARKS_ID, FALSE, pluma_file_browser_view_set_model(), and _PlumaFileBrowserWidget::priv.
Referenced by pluma_file_browser_widget_new().
pluma_file_browser_widget_show_files()
void pluma_file_browser_widget_show_files (PlumaFileBrowserWidget * obj)
Definition at line 1852 of file pluma-file-browser-widget.c.
References TRUE.