MATE Desktop Environment: pluma-file-browser-store.c File Reference
pluma-file-browser-store.c File Reference
#include <string.h>
#include <glib/gi18n-lib.h>
#include <gio/gio.h>
#include "pluma-file-browser-store.h"
#include "pluma-file-browser-enum-types.h"
#include "pluma-file-browser-error.h"
#include "pluma-file-browser-utils.h"
Macros
#define NODE_IS_DIR(node)
#define NODE_IS_HIDDEN(node)
#define NODE_IS_TEXT(node)
#define NODE_LOADED(node)
#define NODE_IS_FILTERED(node)
#define NODE_IS_DUMMY(node)
#define FILE_BROWSER_NODE_DIR(node)
#define DIRECTORY_LOAD_ITEMS_PER_CALLBACK 100
#define STANDARD_ATTRIBUTE_TYPES
#define FILTER_HIDDEN(mode)
#define FILTER_BINARY(mode)
Typedefs
typedef struct _FileBrowserNode FileBrowserNode
typedef struct _FileBrowserNodeDir FileBrowserNodeDir
typedef struct _AsyncData AsyncData
typedef struct _AsyncNode AsyncNode
typedef gint(* SortFunc) (FileBrowserNode *node1, FileBrowserNode *node2)
Enumerations
enum {
BEGIN_LOADING , END_LOADING , ERROR , NO_TRASH ,
RENAME , BEGIN_REFRESH , END_REFRESH , UNLOAD ,
NUM_SIGNALS
}
Functions
G_DEFINE_DYNAMIC_TYPE_EXTENDED (PlumaFileBrowserStore, pluma_file_browser_store, G_TYPE_OBJECT, 0, G_IMPLEMENT_INTERFACE_DYNAMIC(GTK_TYPE_TREE_MODEL, pluma_file_browser_store_iface_init) G_IMPLEMENT_INTERFACE_DYNAMIC(GTK_TYPE_TREE_DRAG_SOURCE, pluma_file_browser_store_drag_source_init))
PlumaFileBrowserStore * pluma_file_browser_store_new (gchar const *root)
void pluma_file_browser_store_set_value (PlumaFileBrowserStore *tree_model, GtkTreeIter *iter, gint column, GValue *value)
PlumaFileBrowserStoreResult pluma_file_browser_store_set_virtual_root (PlumaFileBrowserStore *model, GtkTreeIter *iter)
PlumaFileBrowserStoreResult pluma_file_browser_store_set_virtual_root_from_string (PlumaFileBrowserStore *model, gchar const *root)
PlumaFileBrowserStoreResult pluma_file_browser_store_set_virtual_root_top (PlumaFileBrowserStore *model)
PlumaFileBrowserStoreResult pluma_file_browser_store_set_virtual_root_up (PlumaFileBrowserStore *model)
gboolean pluma_file_browser_store_get_iter_virtual_root (PlumaFileBrowserStore *model, GtkTreeIter *iter)
gboolean pluma_file_browser_store_get_iter_root (PlumaFileBrowserStore *model, GtkTreeIter *iter)
gboolean pluma_file_browser_store_iter_equal (PlumaFileBrowserStore *model, GtkTreeIter *iter1, GtkTreeIter *iter2)
void pluma_file_browser_store_cancel_mount_operation (PlumaFileBrowserStore *store)
PlumaFileBrowserStoreResult pluma_file_browser_store_set_root_and_virtual_root (PlumaFileBrowserStore *model, gchar const *root, gchar const *virtual_root)
PlumaFileBrowserStoreResult pluma_file_browser_store_set_root (PlumaFileBrowserStore *model, gchar const *root)
gchar * pluma_file_browser_store_get_root (PlumaFileBrowserStore *model)
gchar * pluma_file_browser_store_get_virtual_root (PlumaFileBrowserStore *model)
void _pluma_file_browser_store_iter_expanded (PlumaFileBrowserStore *model, GtkTreeIter *iter)
void _pluma_file_browser_store_iter_collapsed (PlumaFileBrowserStore *model, GtkTreeIter *iter)
PlumaFileBrowserStoreFilterMode pluma_file_browser_store_get_filter_mode (PlumaFileBrowserStore *model)
void pluma_file_browser_store_set_filter_mode (PlumaFileBrowserStore *model, PlumaFileBrowserStoreFilterMode mode)
void pluma_file_browser_store_set_filter_func (PlumaFileBrowserStore *model, PlumaFileBrowserStoreFilterFunc func, gpointer user_data)
void pluma_file_browser_store_refilter (PlumaFileBrowserStore *model)
PlumaFileBrowserStoreFilterMode pluma_file_browser_store_filter_mode_get_default (void)
void pluma_file_browser_store_refresh (PlumaFileBrowserStore *model)
gboolean pluma_file_browser_store_rename (PlumaFileBrowserStore *model, GtkTreeIter *iter, const gchar *new_name, GError **error)
PlumaFileBrowserStoreResult pluma_file_browser_store_delete_all (PlumaFileBrowserStore *model, GList *rows, gboolean trash)
PlumaFileBrowserStoreResult pluma_file_browser_store_delete (PlumaFileBrowserStore *model, GtkTreeIter *iter, gboolean trash)
gboolean pluma_file_browser_store_new_file (PlumaFileBrowserStore *model, GtkTreeIter *parent, GtkTreeIter *iter)
gboolean pluma_file_browser_store_new_directory (PlumaFileBrowserStore *model, GtkTreeIter *parent, GtkTreeIter *iter)
void _pluma_file_browser_store_register_type (GTypeModule *type_module)
Macro Definition Documentation
DIRECTORY_LOAD_ITEMS_PER_CALLBACK
#define DIRECTORY_LOAD_ITEMS_PER_CALLBACK 100
Definition at line 45 of file pluma-file-browser-store.c.
FILE_BROWSER_NODE_DIR
#define FILE_BROWSER_NODE_DIR (node)
Value:
((FileBrowserNodeDir *)(node))
Definition at line 43 of file pluma-file-browser-store.c.
Referenced by _pluma_file_browser_store_iter_collapsed(), pluma_file_browser_store_new_directory(), and pluma_file_browser_store_new_file().
FILTER_BINARY
#define FILTER_BINARY (mode)
Value:
(mode & PLUMA_FILE_BROWSER_STORE_FILTER_MODE_HIDE_BINARY)
Definition at line 966 of file pluma-file-browser-store.c.
FILTER_HIDDEN
#define FILTER_HIDDEN (mode)
Value:
(mode & PLUMA_FILE_BROWSER_STORE_FILTER_MODE_HIDE_HIDDEN)
Definition at line 965 of file pluma-file-browser-store.c.
NODE_IS_DIR
#define NODE_IS_DIR (node)
Value:
(FILE_IS_DIR((node)->flags))
Definition at line 36 of file pluma-file-browser-store.c.
Referenced by _pluma_file_browser_store_iter_collapsed(), _pluma_file_browser_store_iter_expanded(), pluma_file_browser_store_new_directory(), and pluma_file_browser_store_new_file().
NODE_IS_DUMMY
#define NODE_IS_DUMMY (node)
Value:
(FILE_IS_DUMMY((node)->flags))
Definition at line 41 of file pluma-file-browser-store.c.
Referenced by pluma_file_browser_store_delete().
NODE_IS_FILTERED
#define NODE_IS_FILTERED (node)
Value:
(FILE_IS_FILTERED((node)->flags))
Definition at line 40 of file pluma-file-browser-store.c.
NODE_IS_HIDDEN
#define NODE_IS_HIDDEN (node)
Value:
(FILE_IS_HIDDEN((node)->flags))
Definition at line 37 of file pluma-file-browser-store.c.
NODE_IS_TEXT
#define NODE_IS_TEXT (node)
Value:
(FILE_IS_TEXT((node)->flags))
Definition at line 38 of file pluma-file-browser-store.c.
NODE_LOADED
#define NODE_LOADED (node)
Value:
(FILE_LOADED((node)->flags))
Definition at line 39 of file pluma-file-browser-store.c.
Referenced by _pluma_file_browser_store_iter_collapsed(), and _pluma_file_browser_store_iter_expanded().
STANDARD_ATTRIBUTE_TYPES
#define STANDARD_ATTRIBUTE_TYPES
Value:
G_FILE_ATTRIBUTE_STANDARD_TYPE "," \
G_FILE_ATTRIBUTE_STANDARD_IS_HIDDEN "," \
G_FILE_ATTRIBUTE_STANDARD_IS_BACKUP "," \
G_FILE_ATTRIBUTE_STANDARD_NAME "," \
G_FILE_ATTRIBUTE_STANDARD_CONTENT_TYPE "," \
G_FILE_ATTRIBUTE_STANDARD_ICON
Definition at line 46 of file pluma-file-browser-store.c.
Typedef Documentation
AsyncData
typedef struct _AsyncData AsyncData
Definition at line 55 of file pluma-file-browser-store.c.
AsyncNode
typedef struct _AsyncNode AsyncNode
Definition at line 56 of file pluma-file-browser-store.c.
FileBrowserNode
typedef struct _FileBrowserNode FileBrowserNode
Definition at line 53 of file pluma-file-browser-store.c.
FileBrowserNodeDir
typedef struct _FileBrowserNodeDir FileBrowserNodeDir
Definition at line 54 of file pluma-file-browser-store.c.
SortFunc
typedef gint(* SortFunc) (FileBrowserNode *node1, FileBrowserNode *node2)
Definition at line 58 of file pluma-file-browser-store.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BEGIN_LOADING
END_LOADING
ERROR
NO_TRASH
RENAME
BEGIN_REFRESH
END_REFRESH
UNLOAD
NUM_SIGNALS
Definition at line 214 of file pluma-file-browser-store.c.
Function Documentation
_pluma_file_browser_store_iter_collapsed()
void _pluma_file_browser_store_iter_collapsed (PlumaFileBrowserStore * model, GtkTreeIter * iter)
Definition at line 3037 of file pluma-file-browser-store.c.
References FILE_BROWSER_NODE_DIR, item, NODE_IS_DIR, NODE_LOADED, NULL, PLUMA_IS_FILE_BROWSER_STORE, and TRUE.
_pluma_file_browser_store_iter_expanded()
void _pluma_file_browser_store_iter_expanded (PlumaFileBrowserStore * model, GtkTreeIter * iter)
Definition at line 3019 of file pluma-file-browser-store.c.
References NODE_IS_DIR, NODE_LOADED, NULL, and PLUMA_IS_FILE_BROWSER_STORE.
_pluma_file_browser_store_register_type()
void _pluma_file_browser_store_register_type (GTypeModule * type_module)
Definition at line 3548 of file pluma-file-browser-store.c.
G_DEFINE_DYNAMIC_TYPE_EXTENDED()
G_DEFINE_DYNAMIC_TYPE_EXTENDED (PlumaFileBrowserStore , pluma_file_browser_store , G_TYPE_OBJECT , 0 , G_IMPLEMENT_INTERFACE_DYNAMIC(GTK_TYPE_TREE_MODEL, pluma_file_browser_store_iface_init) G_IMPLEMENT_INTERFACE_DYNAMIC(GTK_TYPE_TREE_DRAG_SOURCE, pluma_file_browser_store_drag_source_init))
Definition at line 195 of file pluma-file-browser-store.c.
References PROP_0, and PROP_ROOT.
pluma_file_browser_store_cancel_mount_operation()
void pluma_file_browser_store_cancel_mount_operation (PlumaFileBrowserStore * store)
Definition at line 2908 of file pluma-file-browser-store.c.
References PLUMA_IS_FILE_BROWSER_STORE.
pluma_file_browser_store_delete()
PlumaFileBrowserStoreResult pluma_file_browser_store_delete (PlumaFileBrowserStore * model, GtkTreeIter * iter, gboolean trash)
Definition at line 3420 of file pluma-file-browser-store.c.
References NODE_IS_DUMMY, NULL, pluma_file_browser_store_delete_all(), PLUMA_FILE_BROWSER_STORE_RESULT_NO_CHANGE, and PLUMA_IS_FILE_BROWSER_STORE.
pluma_file_browser_store_delete_all()
PlumaFileBrowserStoreResult pluma_file_browser_store_delete_all (PlumaFileBrowserStore * model, GList * rows, gboolean trash)
Definition at line 3364 of file pluma-file-browser-store.c.
References data, FALSE, NULL, PLUMA_FILE_BROWSER_STORE_RESULT_NO_CHANGE, PLUMA_FILE_BROWSER_STORE_RESULT_OK, and PLUMA_IS_FILE_BROWSER_STORE.
Referenced by pluma_file_browser_store_delete().
pluma_file_browser_store_filter_mode_get_default()
PlumaFileBrowserStoreFilterMode pluma_file_browser_store_filter_mode_get_default (void)
Definition at line 3106 of file pluma-file-browser-store.c.
References PLUMA_FILE_BROWSER_STORE_FILTER_MODE_HIDE_HIDDEN.
pluma_file_browser_store_get_filter_mode()
PlumaFileBrowserStoreFilterMode pluma_file_browser_store_get_filter_mode (PlumaFileBrowserStore * model)
Definition at line 3066 of file pluma-file-browser-store.c.
pluma_file_browser_store_get_iter_root()
gboolean pluma_file_browser_store_get_iter_root (PlumaFileBrowserStore * model, GtkTreeIter * iter)
Definition at line 2880 of file pluma-file-browser-store.c.
References FALSE, NULL, PLUMA_IS_FILE_BROWSER_STORE, and TRUE.
pluma_file_browser_store_get_iter_virtual_root()
gboolean pluma_file_browser_store_get_iter_virtual_root (PlumaFileBrowserStore * model, GtkTreeIter * iter)
Definition at line 2866 of file pluma-file-browser-store.c.
References FALSE, NULL, PLUMA_IS_FILE_BROWSER_STORE, and TRUE.
Referenced by pluma_file_browser_widget_get_selected_directory().
pluma_file_browser_store_get_root()
gchar * pluma_file_browser_store_get_root (PlumaFileBrowserStore * model)
Definition at line 2997 of file pluma-file-browser-store.c.
References NULL, and PLUMA_IS_FILE_BROWSER_STORE.
pluma_file_browser_store_get_virtual_root()
gchar * pluma_file_browser_store_get_virtual_root (PlumaFileBrowserStore * model)
Definition at line 3008 of file pluma-file-browser-store.c.
References NULL, and PLUMA_IS_FILE_BROWSER_STORE.
pluma_file_browser_store_iter_equal()
gboolean pluma_file_browser_store_iter_equal (PlumaFileBrowserStore * model, GtkTreeIter * iter1, GtkTreeIter * iter2)
Definition at line 2894 of file pluma-file-browser-store.c.
References FALSE, NULL, and PLUMA_IS_FILE_BROWSER_STORE.
pluma_file_browser_store_new()
PlumaFileBrowserStore * pluma_file_browser_store_new (gchar const * root)
Definition at line 2708 of file pluma-file-browser-store.c.
References NULL, PLUMA_FILE_BROWSER_STORE, pluma_file_browser_store_set_root(), and PLUMA_TYPE_FILE_BROWSER_STORE.
pluma_file_browser_store_new_directory()
gboolean pluma_file_browser_store_new_directory (PlumaFileBrowserStore * model, GtkTreeIter * parent, GtkTreeIter * iter)
Definition at line 3499 of file pluma-file-browser-store.c.
References _, ERROR, error, FALSE, FILE_BROWSER_NODE_DIR, NODE_IS_DIR, NULL, PLUMA_FILE_BROWSER_ERROR_NEW_DIRECTORY, PLUMA_FILE_BROWSER_ERROR_NEW_FILE, PLUMA_IS_FILE_BROWSER_STORE, and TRUE.
pluma_file_browser_store_new_file()
gboolean pluma_file_browser_store_new_file (PlumaFileBrowserStore * model, GtkTreeIter * parent, GtkTreeIter * iter)
Definition at line 3445 of file pluma-file-browser-store.c.
References _, ERROR, error, FALSE, FILE_BROWSER_NODE_DIR, NODE_IS_DIR, NULL, PLUMA_FILE_BROWSER_ERROR_NEW_FILE, PLUMA_IS_FILE_BROWSER_STORE, and TRUE.
pluma_file_browser_store_refilter()
void pluma_file_browser_store_refilter (PlumaFileBrowserStore * model)
Definition at line 3100 of file pluma-file-browser-store.c.
Referenced by pluma_file_browser_widget_add_filter().
pluma_file_browser_store_refresh()
void pluma_file_browser_store_refresh (PlumaFileBrowserStore * model)
Definition at line 3112 of file pluma-file-browser-store.c.
References BEGIN_REFRESH, END_REFRESH, NULL, PLUMA_IS_FILE_BROWSER_STORE, and TRUE.
Referenced by pluma_file_browser_widget_refresh().
pluma_file_browser_store_rename()
gboolean pluma_file_browser_store_rename (PlumaFileBrowserStore * model, GtkTreeIter * iter, const gchar * new_name, GError ** error)
Definition at line 3157 of file pluma-file-browser-store.c.
References _, error, FALSE, NULL, PLUMA_FILE_BROWSER_ERROR_RENAME, PLUMA_IS_FILE_BROWSER_STORE, RENAME, and TRUE.
pluma_file_browser_store_set_filter_func()
void pluma_file_browser_store_set_filter_func (PlumaFileBrowserStore * model, PlumaFileBrowserStoreFilterFunc func, gpointer user_data)
Definition at line 3088 of file pluma-file-browser-store.c.
References PLUMA_IS_FILE_BROWSER_STORE, and user_data.
pluma_file_browser_store_set_filter_mode()
void pluma_file_browser_store_set_filter_mode (PlumaFileBrowserStore * model, PlumaFileBrowserStoreFilterMode mode)
Definition at line 3072 of file pluma-file-browser-store.c.
References PLUMA_IS_FILE_BROWSER_STORE.
pluma_file_browser_store_set_root()
PlumaFileBrowserStoreResult pluma_file_browser_store_set_root (PlumaFileBrowserStore * model, gchar const * root)
Definition at line 2986 of file pluma-file-browser-store.c.
References NULL, PLUMA_FILE_BROWSER_STORE_RESULT_NO_CHANGE, pluma_file_browser_store_set_root_and_virtual_root(), and PLUMA_IS_FILE_BROWSER_STORE.
Referenced by pluma_file_browser_store_new().
pluma_file_browser_store_set_root_and_virtual_root()
PlumaFileBrowserStoreResult pluma_file_browser_store_set_root_and_virtual_root (PlumaFileBrowserStore * model, gchar const * root, gchar const * virtual_root)
Definition at line 2916 of file pluma-file-browser-store.c.
References FALSE, NULL, PLUMA_FILE_BROWSER_STORE_RESULT_NO_CHANGE, PLUMA_FILE_BROWSER_STORE_RESULT_OK, PLUMA_IS_FILE_BROWSER_STORE, and TRUE.
Referenced by pluma_file_browser_store_set_root(), and pluma_file_browser_widget_set_root_and_virtual_root().
pluma_file_browser_store_set_value()
void pluma_file_browser_store_set_value (PlumaFileBrowserStore * tree_model, GtkTreeIter * iter, gint column, GValue * value)
Definition at line 2720 of file pluma-file-browser-store.c.
References data, NULL, PLUMA_FILE_BROWSER_STORE_COLUMN_EMBLEM, and PLUMA_IS_FILE_BROWSER_STORE.
pluma_file_browser_store_set_virtual_root()
PlumaFileBrowserStoreResult pluma_file_browser_store_set_virtual_root (PlumaFileBrowserStore * model, GtkTreeIter * iter)
Definition at line 2761 of file pluma-file-browser-store.c.
References FALSE, NULL, PLUMA_FILE_BROWSER_STORE_RESULT_NO_CHANGE, PLUMA_IS_FILE_BROWSER_STORE, and TRUE.
pluma_file_browser_store_set_virtual_root_from_string()
PlumaFileBrowserStoreResult pluma_file_browser_store_set_virtual_root_from_string (PlumaFileBrowserStore * model, gchar const * root)
Definition at line 2779 of file pluma-file-browser-store.c.
References FALSE, NULL, PLUMA_FILE_BROWSER_STORE_RESULT_ERROR, PLUMA_FILE_BROWSER_STORE_RESULT_NO_CHANGE, PLUMA_FILE_BROWSER_STORE_RESULT_OK, and PLUMA_IS_FILE_BROWSER_STORE.
pluma_file_browser_store_set_virtual_root_top()
PlumaFileBrowserStoreResult pluma_file_browser_store_set_virtual_root_top (PlumaFileBrowserStore * model)
Definition at line 2833 of file pluma-file-browser-store.c.
References FALSE, PLUMA_FILE_BROWSER_STORE_RESULT_NO_CHANGE, PLUMA_FILE_BROWSER_STORE_RESULT_OK, and PLUMA_IS_FILE_BROWSER_STORE.
pluma_file_browser_store_set_virtual_root_up()
PlumaFileBrowserStoreResult pluma_file_browser_store_set_virtual_root_up (PlumaFileBrowserStore * model)
Definition at line 2849 of file pluma-file-browser-store.c.
References FALSE, PLUMA_FILE_BROWSER_STORE_RESULT_NO_CHANGE, PLUMA_FILE_BROWSER_STORE_RESULT_OK, and PLUMA_IS_FILE_BROWSER_STORE.