MATE Desktop Environment: pluma-plugin.c File Reference
pluma-plugin.c File Reference
#include <glib/gi18n-lib.h>
#include <pluma/pluma-window.h>
#include <pluma/pluma-window-activatable.h>
#include <pluma/pluma-debug.h>
#include "##(PLUGIN_MODULE)-plugin.h"
Enumerations
enum { PROP_0 , PROP_OBJECT }
Functions
struct _ (PLUGIN_ID.camel) PluginPrivate
G_DEFINE_DYNAMIC_TYPE_EXTENDED (##(PLUGIN_ID.camel) Plugin, PEAS_TYPE_EXTENSION_BASE, 0, G_IMPLEMENT_INTERFACE_DYNAMIC(PLUMA_TYPE_WINDOW_ACTIVATABLE, pluma_window_activatable_iface_init)) static void
G_OBJECT_CLASS (##(PLUGIN_ID.lower) _plugin_parent_class) -> final ize(object)
if (plugin->priv->window !=NULL)
if (plugin->priv->action_group)
update_ui (##(PLUGIN_ID.upper) _PLUGIN(activatable) ->priv)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_OBJECT
Definition at line 45 of file pluma-plugin.c.
Function Documentation
_()
struct _ (PLUGIN_ID. camel)
Definition at line 35 of file pluma-plugin.c.
References _, and PLUGIN_ID.
G_DEFINE_DYNAMIC_TYPE_EXTENDED()
G_DEFINE_DYNAMIC_TYPE_EXTENDED (##(PLUGIN_ID.camel) Plugin, PEAS_TYPE_EXTENSION_BASE , 0 , G_IMPLEMENT_INTERFACE_DYNAMIC(PLUMA_TYPE_WINDOW_ACTIVATABLE, pluma_window_activatable_iface_init))
Definition at line 50 of file pluma-plugin.c.
References PLUGIN_ID, and PLUMA_TYPE_WINDOW_ACTIVATABLE.
G_OBJECT_CLASS()
G_OBJECT_CLASS (##(PLUGIN_ID.lower) _plugin_parent_class) -> final
References PLUGIN_ID.
Referenced by _terminal_profile_clone(), EEL_CLASS_BOILERPLATE(), EEL_CLASS_BOILERPLATE(), G_DEFINE_ABSTRACT_TYPE_WITH_CODE(), G_DEFINE_DYNAMIC_TYPE_EXTENDED(), G_DEFINE_TYPE(), G_DEFINE_TYPE_EXTENDED(), G_DEFINE_TYPE_EXTENDED(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), G_DEFINE_TYPE_WITH_CODE(), and mate_rr_screen_class_init().
if() [1/2]
if (plugin->priv-> action_group)
Definition at line 103 of file pluma-plugin.c.
References NULL.
if() [2/2]
if (plugin->priv->window ! = NULL)
Definition at line 97 of file pluma-plugin.c.
References NULL.
update_ui()
update_ui (##(PLUGIN_ID.upper) _PLUGIN(activatable) -> priv)
References PLUGIN_ID.