MATE Desktop Environment: pluma-message-bus.h File Reference
pluma-message-bus.h File Reference
#include <glib-object.h>
#include <pluma/pluma-message.h>
#include <pluma/pluma-message-type.h>
Classes
struct _PlumaMessageBus
struct _PlumaMessageBusClass
Macros
#define PLUMA_TYPE_MESSAGE_BUS (pluma_message_bus_get_type ())
#define PLUMA_MESSAGE_BUS(obj)
#define PLUMA_MESSAGE_BUS_CONST(obj)
#define PLUMA_MESSAGE_BUS_CLASS(klass)
#define PLUMA_IS_MESSAGE_BUS(obj)
#define PLUMA_IS_MESSAGE_BUS_CLASS(klass)
#define PLUMA_MESSAGE_BUS_GET_CLASS(obj)
Typedefs
typedef struct _PlumaMessageBus PlumaMessageBus
typedef struct _PlumaMessageBusClass PlumaMessageBusClass
typedef struct _PlumaMessageBusPrivate PlumaMessageBusPrivate
typedef void(* PlumaMessageCallback) (PlumaMessageBus *bus, PlumaMessage *message, gpointer userdata)
typedef void(* PlumaMessageBusForeach) (PlumaMessageType *message_type, gpointer userdata)
Functions
GType pluma_message_bus_get_type (void)
PlumaMessageBus * pluma_message_bus_get_default (void)
PlumaMessageBus * pluma_message_bus_new (void)
PlumaMessageType * pluma_message_bus_lookup (PlumaMessageBus *bus, const gchar *object_path, const gchar *method)
PlumaMessageType * pluma_message_bus_register (PlumaMessageBus *bus, const gchar *object_path, const gchar *method, guint num_optional,...)
void pluma_message_bus_unregister (PlumaMessageBus *bus, PlumaMessageType *message_type)
void pluma_message_bus_unregister_all (PlumaMessageBus *bus, const gchar *object_path)
gboolean pluma_message_bus_is_registered (PlumaMessageBus *bus, const gchar *object_path, const gchar *method)
void pluma_message_bus_foreach (PlumaMessageBus *bus, PlumaMessageBusForeach func, gpointer userdata)
guint pluma_message_bus_connect (PlumaMessageBus *bus, const gchar *object_path, const gchar *method, PlumaMessageCallback callback, gpointer userdata, GDestroyNotify destroy_data)
void pluma_message_bus_disconnect (PlumaMessageBus *bus, guint id)
void pluma_message_bus_disconnect_by_func (PlumaMessageBus *bus, const gchar *object_path, const gchar *method, PlumaMessageCallback callback, gpointer userdata)
void pluma_message_bus_block (PlumaMessageBus *bus, guint id)
void pluma_message_bus_block_by_func (PlumaMessageBus *bus, const gchar *object_path, const gchar *method, PlumaMessageCallback callback, gpointer userdata)
void pluma_message_bus_unblock (PlumaMessageBus *bus, guint id)
void pluma_message_bus_unblock_by_func (PlumaMessageBus *bus, const gchar *object_path, const gchar *method, PlumaMessageCallback callback, gpointer userdata)
void pluma_message_bus_send_message (PlumaMessageBus *bus, PlumaMessage *message)
void pluma_message_bus_send_message_sync (PlumaMessageBus *bus, PlumaMessage *message)
void pluma_message_bus_send (PlumaMessageBus *bus, const gchar *object_path, const gchar *method,...)
PlumaMessage * pluma_message_bus_send_sync (PlumaMessageBus *bus, const gchar *object_path, const gchar *method,...)
Macro Definition Documentation
PLUMA_IS_MESSAGE_BUS
#define PLUMA_IS_MESSAGE_BUS (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLUMA_TYPE_MESSAGE_BUS))
Definition at line 14 of file pluma-message-bus.h.
Referenced by pluma_message_bus_block(), pluma_message_bus_block_by_func(), pluma_message_bus_connect(), pluma_message_bus_disconnect(), pluma_message_bus_disconnect_by_func(), pluma_message_bus_foreach(), pluma_message_bus_is_registered(), pluma_message_bus_lookup(), pluma_message_bus_register(), pluma_message_bus_send_message(), pluma_message_bus_send_message_sync(), pluma_message_bus_unblock(), pluma_message_bus_unblock_by_func(), pluma_message_bus_unregister(), and pluma_message_bus_unregister_all().
PLUMA_IS_MESSAGE_BUS_CLASS
#define PLUMA_IS_MESSAGE_BUS_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_MESSAGE_BUS))
Definition at line 15 of file pluma-message-bus.h.
PLUMA_MESSAGE_BUS
#define PLUMA_MESSAGE_BUS (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_MESSAGE_BUS, PlumaMessageBus))
Definition at line 11 of file pluma-message-bus.h.
Referenced by pluma_message_bus_new().
PLUMA_MESSAGE_BUS_CLASS
#define PLUMA_MESSAGE_BUS_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), PLUMA_TYPE_MESSAGE_BUS, PlumaMessageBusClass))
Definition at line 13 of file pluma-message-bus.h.
PLUMA_MESSAGE_BUS_CONST
#define PLUMA_MESSAGE_BUS_CONST (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_MESSAGE_BUS, PlumaMessageBus const))
Definition at line 12 of file pluma-message-bus.h.
PLUMA_MESSAGE_BUS_GET_CLASS
#define PLUMA_MESSAGE_BUS_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), PLUMA_TYPE_MESSAGE_BUS, PlumaMessageBusClass))
Definition at line 16 of file pluma-message-bus.h.
PLUMA_TYPE_MESSAGE_BUS
#define PLUMA_TYPE_MESSAGE_BUS (pluma_message_bus_get_type ())
Definition at line 10 of file pluma-message-bus.h.
Referenced by pluma_message_bus_get_default(), and pluma_message_bus_new().
Typedef Documentation
PlumaMessageBus
typedef struct _PlumaMessageBus PlumaMessageBus
Definition at line 18 of file pluma-message-bus.h.
PlumaMessageBusClass
typedef struct _PlumaMessageBusClass PlumaMessageBusClass
Definition at line 19 of file pluma-message-bus.h.
PlumaMessageBusForeach
typedef void(* PlumaMessageBusForeach) (PlumaMessageType *message_type, gpointer userdata)
Definition at line 43 of file pluma-message-bus.h.
PlumaMessageBusPrivate
typedef struct _PlumaMessageBusPrivate PlumaMessageBusPrivate
Definition at line 20 of file pluma-message-bus.h.
PlumaMessageCallback
typedef void(* PlumaMessageCallback) (PlumaMessageBus *bus, PlumaMessage *message, gpointer userdata)
Definition at line 39 of file pluma-message-bus.h.
Function Documentation
pluma_message_bus_block()
void pluma_message_bus_block (PlumaMessageBus * bus, guint id)
pluma_message_bus_block: @bus: a PlumaMessageBus @id: the callback id
Blocks evoking the callback specified by @id. Unblock the callback by using pluma_message_bus_unblock().
Definition at line 886 of file pluma-message-bus.c.
References PLUMA_IS_MESSAGE_BUS.
Referenced by pluma_message_bus_get_type().
pluma_message_bus_block_by_func()
void pluma_message_bus_block_by_func (PlumaMessageBus * bus, const gchar * object_path, const gchar * method, PlumaMessageCallback callback, gpointer userdata)
pluma_message_bus_block_by_func: @bus: a PlumaMessageBus @object_path: the object path @method: the method @callback: (scope call): the callback to block @userdata: the userdata with which the callback was connected
Blocks evoking the callback that matches provided @callback and @userdata. Unblock the callback using pluma_message_unblock_by_func().
Definition at line 907 of file pluma-message-bus.c.
References PLUMA_IS_MESSAGE_BUS.
Referenced by pluma_message_bus_get_type().
pluma_message_bus_connect()
guint pluma_message_bus_connect (PlumaMessageBus * bus, const gchar * object_path, const gchar * method, PlumaMessageCallback callback, gpointer userdata, GDestroyNotify destroy_data)
pluma_message_bus_connect: @bus: a PlumaMessageBus @object_path: the object path @method: the method @callback: function to be called when message @method at @object_path is sent @userdata: userdata to use for the callback @destroy_data: function to evoke with @userdata as argument when @userdata needs to be freed
Connect a callback handler to be evoked when message @method at @object_path is sent over the bus.
Return value: the callback identifier
Definition at line 814 of file pluma-message-bus.c.
References message(), NULL, PLUMA_IS_MESSAGE_BUS, and TRUE.
Referenced by pluma_message_bus_get_type().
pluma_message_bus_disconnect()
void pluma_message_bus_disconnect (PlumaMessageBus * bus, guint id)
pluma_message_bus_disconnect: @bus: a PlumaMessageBus @id: the callback id as returned by pluma_message_bus_connect()
Disconnects a previously connected message callback.
Definition at line 843 of file pluma-message-bus.c.
References PLUMA_IS_MESSAGE_BUS.
Referenced by pluma_message_bus_get_type().
pluma_message_bus_disconnect_by_func()
void pluma_message_bus_disconnect_by_func (PlumaMessageBus * bus, const gchar * object_path, const gchar * method, PlumaMessageCallback callback, gpointer userdata)
pluma_message_bus_disconnect_by_func: @bus: a PlumaMessageBus @object_path: the object path @method: the method @callback: (scope call): the connected callback @userdata: the userdata with which the callback was connected
Disconnects a previously connected message callback by matching the provided callback function and userdata. See also pluma_message_bus_disconnect().
Definition at line 865 of file pluma-message-bus.c.
References PLUMA_IS_MESSAGE_BUS.
Referenced by pluma_message_bus_get_type().
pluma_message_bus_foreach()
void pluma_message_bus_foreach (PlumaMessageBus * bus, PlumaMessageBusForeach func, gpointer userdata)
pluma_message_bus_foreach: @bus: the #PlumaMessagebus @func: (scope call): the callback function @userdata: the user data to supply to the callback function
Calls @func for each message type registered on the bus
Definition at line 785 of file pluma-message-bus.c.
References NULL, PLUMA_IS_MESSAGE_BUS, and _PlumaMessageBus::priv.
Referenced by pluma_message_bus_get_type().
pluma_message_bus_get_default()
PlumaMessageBus * pluma_message_bus_get_default (void)
pluma_message_bus_get_default:
Get the default application PlumaMessageBus.
Return value: (transfer none): the default PlumaMessageBus
Definition at line 512 of file pluma-message-bus.c.
References NULL, and PLUMA_TYPE_MESSAGE_BUS.
pluma_message_bus_get_type()
GType pluma_message_bus_get_type (void)
References message(), pluma_message_bus_block(), pluma_message_bus_block_by_func(), pluma_message_bus_connect(), pluma_message_bus_disconnect(), pluma_message_bus_disconnect_by_func(), pluma_message_bus_foreach(), pluma_message_bus_is_registered(), pluma_message_bus_send(), pluma_message_bus_send_message(), pluma_message_bus_send_message_sync(), pluma_message_bus_send_sync(), pluma_message_bus_unblock(), pluma_message_bus_unblock_by_func(), pluma_message_bus_unregister(), and pluma_message_bus_unregister_all().
pluma_message_bus_is_registered()
gboolean pluma_message_bus_is_registered (PlumaMessageBus * bus, const gchar * object_path, const gchar * method)
pluma_message_bus_is_registered: @bus: a PlumaMessageBus @object_path: the object path @method: the method
Check whether a message type @method at @object_path is registered on the bus.
Return value: TRUE if the @method at @object_path is a registered message type on the bus
Definition at line 741 of file pluma-message-bus.c.
References FALSE, NULL, PLUMA_IS_MESSAGE_BUS, pluma_message_type_identifier(), and _PlumaMessageBus::priv.
Referenced by pluma_message_bus_get_type(), and pluma_message_bus_register().
pluma_message_bus_lookup()
PlumaMessageType * pluma_message_bus_lookup (PlumaMessageBus * bus, const gchar * object_path, const gchar * method)
pluma_message_bus_lookup: @bus: a PlumaMessageBus @object_path: the object path @method: the method
Get the registered PlumaMessageType for @method at @object_path. The returned PlumaMessageType is owned by the bus and should not be unreffed.
Return value: the registered PlumaMessageType or NULL if no message type is registered for @method at @object_path
Definition at line 556 of file pluma-message-bus.c.
References NULL, PLUMA_IS_MESSAGE_BUS, PLUMA_MESSAGE_TYPE, pluma_message_type_identifier(), and _PlumaMessageBus::priv.
pluma_message_bus_new()
PlumaMessageBus * pluma_message_bus_new (void)
pluma_message_bus_new:
Create a new message bus. Use pluma_message_bus_get_default() to get the default, application wide, message bus. Creating a new bus is useful for associating a specific bus with for instance a PlumaWindow.
Return value: a new PlumaMessageBus
Definition at line 537 of file pluma-message-bus.c.
References NULL, PLUMA_MESSAGE_BUS, and PLUMA_TYPE_MESSAGE_BUS.
pluma_message_bus_register()
PlumaMessageType * pluma_message_bus_register (PlumaMessageBus * bus, const gchar * object_path, const gchar * method, guint num_optional, ...)
pluma_message_bus_register: @bus: a PlumaMessageBus @object_path: the object path @method: the method to register @num_optional: the number of optional arguments ...: NULL terminated list of key/gtype method argument pairs
Register a message on the bus. A message must be registered on the bus before it can be send. This function registers the type arguments for @method at @object_path. The arguments are specified with the variable arguments which should contain pairs of const gchar *key and GType terminated by NULL. The last @num_optional arguments are registered as optional (and are thus not required when sending a message).
This function emits a #PlumaMessageBus::registered signal.
Return value: the registered PlumaMessageType. The returned reference is owned by the bus. If you want to keep it alive after unregistering, use pluma_message_type_ref().
Definition at line 597 of file pluma-message-bus.c.
References NULL, PLUMA_IS_MESSAGE_BUS, pluma_message_bus_is_registered(), pluma_message_type_identifier(), pluma_message_type_is_valid_object_path(), pluma_message_type_new_valist(), _PlumaMessageBus::priv, and REGISTERED.
pluma_message_bus_send()
void pluma_message_bus_send (PlumaMessageBus * bus, const gchar * object_path, const gchar * method, ...)
pluma_message_bus_send: @bus: a PlumaMessageBus @object_path: the object path @method: the method ...: NULL terminated list of key/value pairs
This provides a convenient way to quickly send a message @method at @object_path asynchronously over the bus. The variable argument list specifies key (string) value pairs used to construct the message arguments. To send a message synchronously use pluma_message_bus_send_sync().
Definition at line 1078 of file pluma-message-bus.c.
References message().
Referenced by pluma_message_bus_get_type().
pluma_message_bus_send_message()
void pluma_message_bus_send_message (PlumaMessageBus * bus, PlumaMessage * message)
pluma_message_bus_send_message: @bus: a PlumaMessageBus @message: the message to send
This sends the provided @message asynchronously over the bus. To send a message synchronously, use pluma_message_bus_send_message_sync(). The convenience function pluma_message_bus_send() can be used to easily send a message without constructing the message object explicitly first.
Definition at line 1002 of file pluma-message-bus.c.
References message(), PLUMA_IS_MESSAGE, and PLUMA_IS_MESSAGE_BUS.
Referenced by pluma_message_bus_get_type().
pluma_message_bus_send_message_sync()
void pluma_message_bus_send_message_sync (PlumaMessageBus * bus, PlumaMessage * message)
pluma_message_bus_send_message_sync: @bus: a PlumaMessageBus @message: the message to send
This sends the provided @message synchronously over the bus. To send a message asynchronously, use pluma_message_bus_send_message(). The convenience function pluma_message_bus_send_sync() can be used to easily send a message without constructing the message object explicitly first.
Definition at line 1035 of file pluma-message-bus.c.
References message(), PLUMA_IS_MESSAGE, and PLUMA_IS_MESSAGE_BUS.
Referenced by pluma_message_bus_get_type().
pluma_message_bus_send_sync()
PlumaMessage * pluma_message_bus_send_sync (PlumaMessageBus * bus, const gchar * object_path, const gchar * method, ...)
pluma_message_bus_send_sync: @bus: a PlumaMessageBus @object_path: the object path @method: the method ...: NULL terminated list of key/value pairs
This provides a convenient way to quickly send a message @method at @object_path synchronously over the bus. The variable argument list specifies key (string) value pairs used to construct the message arguments. To send a message asynchronously use pluma_message_bus_send().
Return value: (transfer full): the constructed PlumaMessage. The caller owns a reference to the PlumaMessage and should call g_object_unref() when it is no longer needed
Definition at line 1120 of file pluma-message-bus.c.
References message().
Referenced by pluma_message_bus_get_type().
pluma_message_bus_unblock()
void pluma_message_bus_unblock (PlumaMessageBus * bus, guint id)
pluma_message_bus_unblock: @bus: a PlumaMessageBus @id: the callback id
Unblocks the callback specified by @id.
Definition at line 927 of file pluma-message-bus.c.
References PLUMA_IS_MESSAGE_BUS.
Referenced by pluma_message_bus_get_type().
pluma_message_bus_unblock_by_func()
void pluma_message_bus_unblock_by_func (PlumaMessageBus * bus, const gchar * object_path, const gchar * method, PlumaMessageCallback callback, gpointer userdata)
pluma_message_bus_unblock_by_func: @bus: a PlumaMessageBus @object_path: the object path @method: the method @callback: (scope call): the callback to block @userdata: the userdata with which the callback was connected
Unblocks the callback that matches provided @callback and @userdata.
Definition at line 947 of file pluma-message-bus.c.
References PLUMA_IS_MESSAGE_BUS.
Referenced by pluma_message_bus_get_type().
pluma_message_bus_unregister()
void pluma_message_bus_unregister (PlumaMessageBus * bus, PlumaMessageType * message_type)
pluma_message_bus_unregister: @bus: a PlumaMessageBus @message_type: the PlumaMessageType to unregister
Unregisters a previously registered message type. This is especially useful for plugins which should unregister message types when they are deactivated.
This function emits the #PlumaMessageBus::unregistered signal.
Definition at line 673 of file pluma-message-bus.c.
References PLUMA_IS_MESSAGE_BUS, and TRUE.
Referenced by pluma_message_bus_get_type().
pluma_message_bus_unregister_all()
void pluma_message_bus_unregister_all (PlumaMessageBus * bus, const gchar * object_path)
pluma_message_bus_unregister_all: @bus: a PlumaMessageBus @object_path: the object path
Unregisters all message types for @object_path. This is especially useful for plugins which should unregister message types when they are deactivated.
This function emits the #PlumaMessageBus::unregistered signal for all unregistered message types.
Definition at line 714 of file pluma-message-bus.c.
References NULL, PLUMA_IS_MESSAGE_BUS, and _PlumaMessageBus::priv.
Referenced by pluma_file_browser_messages_unregister(), and pluma_message_bus_get_type().