MATE Desktop Environment: pluma-smart-charset-converter.c File Reference
pluma-smart-charset-converter.c File Reference
#include "pluma-smart-charset-converter.h"
#include "pluma-debug.h"
#include "pluma-document.h"
#include <gio/gio.h>
#include <glib/gi18n.h>
Functions
G_DEFINE_TYPE_WITH_CODE (PlumaSmartCharsetConverter, pluma_smart_charset_converter, G_TYPE_OBJECT, G_IMPLEMENT_INTERFACE(G_TYPE_CONVERTER, pluma_smart_charset_converter_iface_init))
PlumaSmartCharsetConverter * pluma_smart_charset_converter_new (GSList *candidate_encodings)
const PlumaEncoding * pluma_smart_charset_converter_get_guessed (PlumaSmartCharsetConverter *smart)
guint pluma_smart_charset_converter_get_num_fallbacks (PlumaSmartCharsetConverter *smart)
Function Documentation
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (PlumaSmartCharsetConverter , pluma_smart_charset_converter , G_TYPE_OBJECT , G_IMPLEMENT_INTERFACE(G_TYPE_CONVERTER, pluma_smart_charset_converter_iface_init))
Definition at line 44 of file pluma-smart-charset-converter.c.
References DEBUG_UTILS, G_OBJECT_CLASS(), pluma_debug_message(), PLUMA_SMART_CHARSET_CONVERTER, and _PlumaSmartCharsetConverter::priv.
pluma_smart_charset_converter_get_guessed()
const PlumaEncoding * pluma_smart_charset_converter_get_guessed (PlumaSmartCharsetConverter * smart)
Definition at line 394 of file pluma-smart-charset-converter.c.
References NULL, pluma_encoding_get_utf8(), PLUMA_IS_SMART_CHARSET_CONVERTER, and _PlumaSmartCharsetConverter::priv.
pluma_smart_charset_converter_get_num_fallbacks()
guint pluma_smart_charset_converter_get_num_fallbacks (PlumaSmartCharsetConverter * smart)
Definition at line 411 of file pluma-smart-charset-converter.c.
References FALSE, NULL, PLUMA_IS_SMART_CHARSET_CONVERTER, and _PlumaSmartCharsetConverter::priv.
pluma_smart_charset_converter_new()
PlumaSmartCharsetConverter * pluma_smart_charset_converter_new (GSList * candidate_encodings)
Definition at line 380 of file pluma-smart-charset-converter.c.
References NULL, PLUMA_TYPE_SMART_CHARSET_CONVERTER, and _PlumaSmartCharsetConverter::priv.