MATE Desktop Environment: pluma-commands-file.c File Reference
pluma-commands-file.c File Reference
#include <string.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include "pluma-commands.h"
#include "pluma-window.h"
#include "pluma-window-private.h"
#include "pluma-statusbar.h"
#include "pluma-debug.h"
#include "pluma-utils.h"
#include "pluma-file-chooser-dialog.h"
#include "dialogs/pluma-close-confirmation-dialog.h"
Macros
#define PLUMA_OPEN_DIALOG_KEY "pluma-open-dialog-key"
#define PLUMA_TAB_TO_SAVE_AS "pluma-tab-to-save-as"
#define PLUMA_LIST_OF_TABS_TO_SAVE_AS "pluma-list-of-tabs-to-save-as"
#define PLUMA_IS_CLOSING_ALL "pluma-is-closing-all"
#define PLUMA_IS_QUITTING "pluma-is-quitting"
#define PLUMA_IS_CLOSING_TAB "pluma-is-closing-tab"
#define PLUMA_IS_QUITTING_ALL "pluma-is-quitting-all"
Functions
void _pluma_cmd_file_new (GtkAction *action, PlumaWindow *window)
void pluma_commands_load_uri (PlumaWindow *window, const gchar *uri, const PlumaEncoding *encoding, gint line_pos)
gint pluma_commands_load_uris (PlumaWindow *window, const GSList *uris, const PlumaEncoding *encoding, gint line_pos)
gint _pluma_cmd_load_files_from_prompt (PlumaWindow *window, GSList *files, const PlumaEncoding *encoding, gint line_pos)
void _pluma_cmd_file_open (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_save (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_save_as (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_save_documents_list (PlumaWindow *window, GList *docs)
void pluma_commands_save_all_documents (PlumaWindow *window)
void _pluma_cmd_file_save_all (GtkAction *action, PlumaWindow *window)
void pluma_commands_save_document (PlumaWindow *window, PlumaDocument *document)
void _pluma_cmd_file_revert (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_close_tab (PlumaTab *tab, PlumaWindow *window)
void _pluma_cmd_file_close (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_close_all (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_quit (GtkAction *action, PlumaWindow *window)
Macro Definition Documentation
PLUMA_IS_CLOSING_ALL
#define PLUMA_IS_CLOSING_ALL "pluma-is-closing-all"
Definition at line 58 of file pluma-commands-file.c.
Referenced by _pluma_cmd_file_close_tab().
PLUMA_IS_CLOSING_TAB
#define PLUMA_IS_CLOSING_TAB "pluma-is-closing-tab"
Definition at line 60 of file pluma-commands-file.c.
PLUMA_IS_QUITTING
#define PLUMA_IS_QUITTING "pluma-is-quitting"
Definition at line 59 of file pluma-commands-file.c.
Referenced by _pluma_cmd_file_close_tab().
PLUMA_IS_QUITTING_ALL
#define PLUMA_IS_QUITTING_ALL "pluma-is-quitting-all"
Definition at line 61 of file pluma-commands-file.c.
Referenced by _pluma_cmd_file_close_tab().
PLUMA_LIST_OF_TABS_TO_SAVE_AS
#define PLUMA_LIST_OF_TABS_TO_SAVE_AS "pluma-list-of-tabs-to-save-as"
Definition at line 57 of file pluma-commands-file.c.
Referenced by _pluma_cmd_file_save_documents_list().
PLUMA_OPEN_DIALOG_KEY
#define PLUMA_OPEN_DIALOG_KEY "pluma-open-dialog-key"
Definition at line 55 of file pluma-commands-file.c.
Referenced by _pluma_cmd_file_open().
PLUMA_TAB_TO_SAVE_AS
#define PLUMA_TAB_TO_SAVE_AS "pluma-tab-to-save-as"
Definition at line 56 of file pluma-commands-file.c.
Function Documentation
_pluma_cmd_file_close()
void _pluma_cmd_file_close (GtkAction * action, PlumaWindow * window)
Definition at line 1732 of file pluma-commands-file.c.
References _pluma_cmd_file_close_tab(), action, DEBUG_COMMANDS, NULL, pluma_debug(), and pluma_window_get_active_tab().
_pluma_cmd_file_close_all()
void _pluma_cmd_file_close_all (GtkAction * action, PlumaWindow * window)
Definition at line 1821 of file pluma-commands-file.c.
References action, DEBUG_COMMANDS, FALSE, pluma_debug(), pluma_window_get_state(), PLUMA_WINDOW_STATE_PRINTING, PLUMA_WINDOW_STATE_SAVING, and PLUMA_WINDOW_STATE_SAVING_SESSION.
_pluma_cmd_file_close_tab()
void _pluma_cmd_file_close_tab (PlumaTab * tab, PlumaWindow * window)
Definition at line 1707 of file pluma-commands-file.c.
References DEBUG_COMMANDS, FALSE, GBOOLEAN_TO_POINTER, pluma_debug(), PLUMA_IS_CLOSING_ALL, PLUMA_IS_QUITTING, PLUMA_IS_QUITTING_ALL, and pluma_window_close_tab().
Referenced by _pluma_cmd_file_close().
_pluma_cmd_file_new()
void _pluma_cmd_file_new (GtkAction * action, PlumaWindow * window)
Definition at line 68 of file pluma-commands-file.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_window_create_tab(), and TRUE.
_pluma_cmd_file_open()
void _pluma_cmd_file_open (GtkAction * action, PlumaWindow * window)
Definition at line 440 of file pluma-commands-file.c.
References _, _pluma_window_get_default_location(), action, data, DEBUG_COMMANDS, NULL, pluma_debug(), pluma_document_get_location(), pluma_file_chooser_dialog_new(), PLUMA_IS_FILE_CHOOSER_DIALOG, PLUMA_OPEN_DIALOG_KEY, and pluma_window_get_active_document().
_pluma_cmd_file_quit()
void _pluma_cmd_file_quit (GtkAction * action, PlumaWindow * window)
Definition at line 1835 of file pluma-commands-file.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_window_get_state(), PLUMA_WINDOW_STATE_PRINTING, PLUMA_WINDOW_STATE_SAVING, PLUMA_WINDOW_STATE_SAVING_SESSION, and TRUE.
_pluma_cmd_file_revert()
void _pluma_cmd_file_revert (GtkAction * action, PlumaWindow * window)
Definition at line 1238 of file pluma-commands-file.c.
References action, DEBUG_COMMANDS, NULL, pluma_debug(), pluma_document_is_untitled(), pluma_tab_get_document(), pluma_tab_get_state(), PLUMA_TAB_STATE_EXTERNALLY_MODIFIED_NOTIFICATION, pluma_window_get_active_tab(), pluma_window_get_group(), and TRUE.
_pluma_cmd_file_save()
void _pluma_cmd_file_save (GtkAction * action, PlumaWindow * window)
Definition at line 880 of file pluma-commands-file.c.
References action, DEBUG_COMMANDS, NULL, pluma_debug(), and pluma_window_get_active_tab().
_pluma_cmd_file_save_all()
void _pluma_cmd_file_save_all (GtkAction * action, PlumaWindow * window)
Definition at line 1049 of file pluma-commands-file.c.
References action, and pluma_commands_save_all_documents().
_pluma_cmd_file_save_as()
void _pluma_cmd_file_save_as (GtkAction * action, PlumaWindow * window)
Definition at line 895 of file pluma-commands-file.c.
References action, DEBUG_COMMANDS, NULL, pluma_debug(), and pluma_window_get_active_tab().
_pluma_cmd_file_save_documents_list()
void _pluma_cmd_file_save_documents_list (PlumaWindow * window, GList * docs)
Definition at line 927 of file pluma-commands-file.c.
References DEBUG_COMMANDS, NULL, pluma_debug(), pluma_debug_message(), PLUMA_DOCUMENT, pluma_document_get_readonly(), pluma_document_get_uri_for_display(), pluma_document_is_untitled(), PLUMA_IS_DOCUMENT, PLUMA_LIST_OF_TABS_TO_SAVE_AS, PLUMA_TAB, pluma_tab_get_from_document(), pluma_tab_get_state(), PLUMA_TAB_STATE_CLOSING, PLUMA_TAB_STATE_GENERIC_NOT_EDITABLE, PLUMA_TAB_STATE_NORMAL, PLUMA_TAB_STATE_PRINT_PREVIEWING, PLUMA_TAB_STATE_PRINTING, PLUMA_TAB_STATE_SHOWING_PRINT_PREVIEW, pluma_window_get_state(), pluma_window_set_active_tab(), PLUMA_WINDOW_STATE_PRINTING, and PLUMA_WINDOW_STATE_SAVING_SESSION.
Referenced by pluma_commands_save_all_documents().
_pluma_cmd_load_files_from_prompt()
gint _pluma_cmd_load_files_from_prompt (PlumaWindow * window, GSList * files, const PlumaEncoding * encoding, gint line_pos)
Definition at line 383 of file pluma-commands-file.c.
References DEBUG_COMMANDS, pluma_debug(), and TRUE.
pluma_commands_load_uri()
void pluma_commands_load_uri (PlumaWindow * window, const gchar * uri, const PlumaEncoding * encoding, gint line_pos)
pluma_commands_load_uri: @window: @uri: @encoding: (allow-none): @line_pos:
Do nothing if uri does not exist
Definition at line 315 of file pluma-commands-file.c.
References DEBUG_COMMANDS, FALSE, NULL, pluma_debug_message(), PLUMA_IS_WINDOW, and pluma_utils_is_valid_uri().
pluma_commands_load_uris()
gint pluma_commands_load_uris (PlumaWindow * window, const GSList * uris, const PlumaEncoding * encoding, gint line_pos)
pluma_commands_load_uris: @window: @uris: @encoding: @line_pos:
Ignore non-existing URIs
Returns:
Definition at line 347 of file pluma-commands-file.c.
References DEBUG_COMMANDS, FALSE, NULL, pluma_debug(), and PLUMA_IS_WINDOW.
pluma_commands_save_all_documents()
void pluma_commands_save_all_documents (PlumaWindow * window)
Definition at line 1033 of file pluma-commands-file.c.
References _pluma_cmd_file_save_documents_list(), DEBUG_COMMANDS, pluma_debug(), PLUMA_IS_WINDOW, and pluma_window_get_documents().
Referenced by _pluma_cmd_file_save_all().
pluma_commands_save_document()
void pluma_commands_save_document (PlumaWindow * window, PlumaDocument * document)
Definition at line 1056 of file pluma-commands-file.c.
References DEBUG_COMMANDS, pluma_debug(), PLUMA_IS_DOCUMENT, PLUMA_IS_WINDOW, and pluma_tab_get_from_document().