MATE Desktop Environment: pluma-automatic-spell-checker.c File Reference
pluma-automatic-spell-checker.c File Reference
#include <string.h>
#include <glib/gi18n.h>
#include <libmate-desktop/mate-image-menu-item.h>
#include "pluma-automatic-spell-checker.h"
#include "pluma-spell-utils.h"
Functions
void pluma_automatic_spell_checker_recheck_all (PlumaAutomaticSpellChecker *spell)
PlumaAutomaticSpellChecker * pluma_automatic_spell_checker_new (PlumaDocument *doc, PlumaSpellChecker *checker)
PlumaAutomaticSpellChecker * pluma_automatic_spell_checker_get_from_document (const PlumaDocument *doc)
void pluma_automatic_spell_checker_free (PlumaAutomaticSpellChecker *spell)
void pluma_automatic_spell_checker_attach_view (PlumaAutomaticSpellChecker *spell, PlumaView *view)
void pluma_automatic_spell_checker_detach_view (PlumaAutomaticSpellChecker *spell, PlumaView *view)
Function Documentation
pluma_automatic_spell_checker_attach_view()
void pluma_automatic_spell_checker_attach_view (PlumaAutomaticSpellChecker * spell, PlumaView * view)
Definition at line 964 of file pluma-automatic-spell-checker.c.
References NULL, and PLUMA_IS_VIEW.
pluma_automatic_spell_checker_detach_view()
void pluma_automatic_spell_checker_detach_view (PlumaAutomaticSpellChecker * spell, PlumaView * view)
Definition at line 995 of file pluma-automatic-spell-checker.c.
References NULL, and PLUMA_IS_VIEW.
pluma_automatic_spell_checker_free()
void pluma_automatic_spell_checker_free (PlumaAutomaticSpellChecker * spell)
Definition at line 888 of file pluma-automatic-spell-checker.c.
References NULL, and pluma_automatic_spell_checker_get_from_document().
pluma_automatic_spell_checker_get_from_document()
PlumaAutomaticSpellChecker * pluma_automatic_spell_checker_get_from_document (const PlumaDocument * doc)
Definition at line 877 of file pluma-automatic-spell-checker.c.
References NULL, and PLUMA_IS_DOCUMENT.
Referenced by pluma_automatic_spell_checker_free(), and pluma_automatic_spell_checker_new().
pluma_automatic_spell_checker_new()
PlumaAutomaticSpellChecker * pluma_automatic_spell_checker_new (PlumaDocument * doc, PlumaSpellChecker * checker)
Definition at line 713 of file pluma-automatic-spell-checker.c.
References FALSE, NULL, pluma_automatic_spell_checker_get_from_document(), PLUMA_IS_DOCUMENT, PLUMA_IS_SPELL_CHECKER, and TRUE.
pluma_automatic_spell_checker_recheck_all()
void pluma_automatic_spell_checker_recheck_all (PlumaAutomaticSpellChecker * spell)
Definition at line 569 of file pluma-automatic-spell-checker.c.
References NULL, and TRUE.