MATE Desktop Environment: pluma-spell-checker-language.c File Reference
pluma-spell-checker-language.c File Reference
#include <string.h>
#include <enchant.h>
#include <glib/gi18n.h>
#include <libxml/xmlreader.h>
#include "pluma-spell-checker-language.h"
#include <pluma/pluma-debug.h>
Macros
#define ISO_639_DOMAIN "iso_639"
#define ISO_3166_DOMAIN "iso_3166"
#define ISOCODESLOCALEDIR ISO_CODES_PREFIX "/share/locale"
Enumerations
enum ParserState { STATE_START , STATE_STOP , STATE_ENTRIES }
Functions
const GSList * pluma_spell_checker_get_available_languages (void)
const gchar * pluma_spell_checker_language_to_string (const PlumaSpellCheckerLanguage *lang)
const gchar * pluma_spell_checker_language_to_key (const PlumaSpellCheckerLanguage *lang)
const PlumaSpellCheckerLanguage * pluma_spell_checker_language_from_key (const gchar *key)
Macro Definition Documentation
ISO_3166_DOMAIN
#define ISO_3166_DOMAIN "iso_3166"
Definition at line 52 of file pluma-spell-checker-language.c.
ISO_639_DOMAIN
#define ISO_639_DOMAIN "iso_639"
Definition at line 51 of file pluma-spell-checker-language.c.
ISOCODESLOCALEDIR
#define ISOCODESLOCALEDIR ISO_CODES_PREFIX "/share/locale"
Definition at line 54 of file pluma-spell-checker-language.c.
Enumeration Type Documentation
ParserState
enum ParserState
Enumerator
STATE_START
STATE_STOP
STATE_ENTRIES
Definition at line 140 of file pluma-spell-checker-language.c.
Function Documentation
pluma_spell_checker_get_available_languages()
const GSList * pluma_spell_checker_get_available_languages (void)
Definition at line 359 of file pluma-spell-checker-language.c.
References NULL, and TRUE.
Referenced by pluma_spell_checker_language_from_key().
pluma_spell_checker_language_from_key()
const PlumaSpellCheckerLanguage * pluma_spell_checker_language_from_key (const gchar * key)
Definition at line 421 of file pluma-spell-checker-language.c.
References key, NULL, and pluma_spell_checker_get_available_languages().
pluma_spell_checker_language_to_key()
const gchar * pluma_spell_checker_language_to_key (const PlumaSpellCheckerLanguage * lang)
Definition at line 413 of file pluma-spell-checker-language.c.
References NULL.
pluma_spell_checker_language_to_string()
const gchar * pluma_spell_checker_language_to_string (const PlumaSpellCheckerLanguage * lang)
Definition at line 401 of file pluma-spell-checker-language.c.
References C_, and NULL.
Referenced by pluma_spell_checker_dialog_set_spell_checker(), and pluma_spell_checker_set_language().