MATE Desktop Environment: pluma-file-chooser-dialog.c File Reference
pluma-file-chooser-dialog.c File Reference
#include <string.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <gtksourceview/gtksource.h>
#include "pluma-file-chooser-dialog.h"
#include "pluma-encodings-combo-box.h"
#include "pluma-language-manager.h"
#include "pluma-debug.h"
#include "pluma-enum-types.h"
#include "pluma-utils.h"
#include "pluma-settings.h"
Macros
#define ALL_FILES _("All Files")
#define ALL_TEXT_FILES _("All Text Files")
Functions
GtkWidget * pluma_file_chooser_dialog_new (const gchar *title, GtkWindow *parent, GtkFileChooserAction action, const PlumaEncoding *encoding, const gchar *first_button_text,...)
void pluma_file_chooser_dialog_set_encoding (PlumaFileChooserDialog *dialog, const PlumaEncoding *encoding)
const PlumaEncoding * pluma_file_chooser_dialog_get_encoding (PlumaFileChooserDialog *dialog)
void pluma_file_chooser_dialog_set_newline_type (PlumaFileChooserDialog *dialog, PlumaDocumentNewlineType newline_type)
PlumaDocumentNewlineType pluma_file_chooser_dialog_get_newline_type (PlumaFileChooserDialog *dialog)
Macro Definition Documentation
ALL_FILES
#define ALL_FILES _("All Files")
Definition at line 53 of file pluma-file-chooser-dialog.c.
ALL_TEXT_FILES
#define ALL_TEXT_FILES _("All Text Files")
Definition at line 54 of file pluma-file-chooser-dialog.c.
Function Documentation
pluma_file_chooser_dialog_get_encoding()
const PlumaEncoding * pluma_file_chooser_dialog_get_encoding (PlumaFileChooserDialog * dialog)
Definition at line 522 of file pluma-file-chooser-dialog.c.
References NULL, PLUMA_ENCODINGS_COMBO_BOX, pluma_encodings_combo_box_get_selected_encoding(), PLUMA_IS_ENCODINGS_COMBO_BOX, and PLUMA_IS_FILE_CHOOSER_DIALOG.
pluma_file_chooser_dialog_get_newline_type()
PlumaDocumentNewlineType pluma_file_chooser_dialog_get_newline_type (PlumaFileChooserDialog * dialog)
Definition at line 566 of file pluma-file-chooser-dialog.c.
References PLUMA_DOCUMENT_NEWLINE_TYPE_DEFAULT, and PLUMA_IS_FILE_CHOOSER_DIALOG.
pluma_file_chooser_dialog_new()
GtkWidget * pluma_file_chooser_dialog_new (const gchar * title, GtkWindow * parent, GtkFileChooserAction action, const PlumaEncoding * encoding, const gchar * first_button_text, ...)
pluma_file_chooser_dialog_new: @title: (allow-none): Title of the dialog, or NULL @parent: (allow-none): Transient parent of the dialog, or NULL @action: Open or save mode for the dialog @first_button_text: (allow-none): icon name or text to go in the first button, or NULL ...: (allow-none): response ID for the first button, then additional (button, id) pairs, ending with NULL
Creates a new PlumaFileChooserDialog. This function is analogous to gtk_dialog_new_with_buttons().
Return value: a new PlumaFileChooserDialog
Definition at line 490 of file pluma-file-chooser-dialog.c.
References action.
Referenced by _pluma_cmd_file_open().
pluma_file_chooser_dialog_set_encoding()
void pluma_file_chooser_dialog_set_encoding (PlumaFileChooserDialog * dialog, const PlumaEncoding * encoding)
Definition at line 510 of file pluma-file-chooser-dialog.c.
References PLUMA_ENCODINGS_COMBO_BOX, pluma_encodings_combo_box_set_selected_encoding(), PLUMA_IS_ENCODINGS_COMBO_BOX, and PLUMA_IS_FILE_CHOOSER_DIALOG.
pluma_file_chooser_dialog_set_newline_type()
void pluma_file_chooser_dialog_set_newline_type (PlumaFileChooserDialog * dialog, PlumaDocumentNewlineType newline_type)
Definition at line 534 of file pluma-file-chooser-dialog.c.
References PLUMA_IS_FILE_CHOOSER_DIALOG.