MATE Desktop Environment: plumatextregion.c File Reference
plumatextregion.c File Reference
#include <glib.h>
#include "plumatextregion.h"
Macros
#define DEBUG(x)
Typedefs
typedef struct _Subregion Subregion
typedef struct _PlumaTextRegionIteratorReal PlumaTextRegionIteratorReal
Functions
PlumaTextRegion * pluma_text_region_new (GtkTextBuffer *buffer)
void pluma_text_region_destroy (PlumaTextRegion *region, gboolean delete_marks)
GtkTextBuffer * pluma_text_region_get_buffer (PlumaTextRegion *region)
void pluma_text_region_add (PlumaTextRegion *region, const GtkTextIter *_start, const GtkTextIter *_end)
void pluma_text_region_subtract (PlumaTextRegion *region, const GtkTextIter *_start, const GtkTextIter *_end)
gint pluma_text_region_subregions (PlumaTextRegion *region)
gboolean pluma_text_region_nth_subregion (PlumaTextRegion *region, guint subregion, GtkTextIter *start, GtkTextIter *end)
PlumaTextRegion * pluma_text_region_intersect (PlumaTextRegion *region, const GtkTextIter *_start, const GtkTextIter *_end)
void pluma_text_region_get_iterator (PlumaTextRegion *region, PlumaTextRegionIterator *iter, guint start)
gboolean pluma_text_region_iterator_is_end (PlumaTextRegionIterator *iter)
gboolean pluma_text_region_iterator_next (PlumaTextRegionIterator *iter)
void pluma_text_region_iterator_get_subregion (PlumaTextRegionIterator *iter, GtkTextIter *start, GtkTextIter *end)
void pluma_text_region_debug_print (PlumaTextRegion *region)
Macro Definition Documentation
DEBUG
#define DEBUG (x)
Definition at line 43 of file plumatextregion.c.
Referenced by pluma_text_region_add(), and pluma_text_region_subtract().
Typedef Documentation
PlumaTextRegionIteratorReal
typedef struct _PlumaTextRegionIteratorReal PlumaTextRegionIteratorReal
Definition at line 57 of file plumatextregion.c.
Subregion
typedef struct _Subregion Subregion
Function Documentation
pluma_text_region_add()
void pluma_text_region_add (PlumaTextRegion * region, const GtkTextIter * _start, const GtkTextIter * _end)
Definition at line 197 of file plumatextregion.c.
References DEBUG, FALSE, NULL, pluma_text_region_debug_print(), and TRUE.
pluma_text_region_debug_print()
void pluma_text_region_debug_print (PlumaTextRegion * region)
Definition at line 629 of file plumatextregion.c.
References NULL.
Referenced by pluma_text_region_add(), and pluma_text_region_subtract().
pluma_text_region_destroy()
void pluma_text_region_destroy (PlumaTextRegion * region, gboolean delete_marks)
Definition at line 139 of file plumatextregion.c.
References NULL.
Referenced by _pluma_document_search_region(), and pluma_document_set_enable_search_highlighting().
pluma_text_region_get_buffer()
GtkTextBuffer * pluma_text_region_get_buffer (PlumaTextRegion * region)
Definition at line 160 of file plumatextregion.c.
References NULL.
pluma_text_region_get_iterator()
void pluma_text_region_get_iterator (PlumaTextRegion * region, PlumaTextRegionIterator * iter, guint start)
Definition at line 556 of file plumatextregion.c.
References NULL.
pluma_text_region_intersect()
PlumaTextRegion * pluma_text_region_intersect (PlumaTextRegion * region, const GtkTextIter * _start, const GtkTextIter * _end)
Definition at line 437 of file plumatextregion.c.
References FALSE, NULL, pluma_text_region_new(), and TRUE.
Referenced by _pluma_document_search_region().
pluma_text_region_iterator_get_subregion()
void pluma_text_region_iterator_get_subregion (PlumaTextRegionIterator * iter, GtkTextIter * start, GtkTextIter * end)
Definition at line 606 of file plumatextregion.c.
References NULL.
pluma_text_region_iterator_is_end()
gboolean pluma_text_region_iterator_is_end (PlumaTextRegionIterator * iter)
Definition at line 575 of file plumatextregion.c.
References FALSE, and NULL.
pluma_text_region_iterator_next()
gboolean pluma_text_region_iterator_next (PlumaTextRegionIterator * iter)
Definition at line 588 of file plumatextregion.c.
References FALSE, NULL, and TRUE.
pluma_text_region_new()
PlumaTextRegion * pluma_text_region_new (GtkTextBuffer * buffer)
Definition at line 124 of file plumatextregion.c.
References NULL.
Referenced by pluma_document_set_enable_search_highlighting(), and pluma_text_region_intersect().
pluma_text_region_nth_subregion()
gboolean pluma_text_region_nth_subregion (PlumaTextRegion * region, guint subregion, GtkTextIter * start, GtkTextIter * end)
Definition at line 415 of file plumatextregion.c.
References FALSE, NULL, and TRUE.
Referenced by _pluma_document_search_region().
pluma_text_region_subregions()
gint pluma_text_region_subregions (PlumaTextRegion * region)
Definition at line 407 of file plumatextregion.c.
References NULL.
Referenced by _pluma_document_search_region().
pluma_text_region_subtract()
void pluma_text_region_subtract (PlumaTextRegion * region, const GtkTextIter * _start, const GtkTextIter * _end)
Definition at line 282 of file plumatextregion.c.
References DEBUG, FALSE, NULL, pluma_text_region_debug_print(), and TRUE.
Referenced by _pluma_document_search_region().