MATE Desktop Environment: pluma-tab.h File Reference
pluma-tab.h File Reference
#include <gtk/gtk.h>
#include <pluma/pluma-view.h>
#include <pluma/pluma-document.h>
Classes
struct _PlumaTab
struct _PlumaTabClass
Macros
#define PLUMA_TYPE_TAB (pluma_tab_get_type())
#define PLUMA_TAB(obj)
#define PLUMA_TAB_CLASS(klass)
#define PLUMA_IS_TAB(obj)
#define PLUMA_IS_TAB_CLASS(klass)
#define PLUMA_TAB_GET_CLASS(obj)
Typedefs
typedef struct _PlumaTabPrivate PlumaTabPrivate
typedef struct _PlumaTab PlumaTab
typedef struct _PlumaTabClass PlumaTabClass
Enumerations
enum PlumaTabState {
PLUMA_TAB_STATE_NORMAL = 0 , PLUMA_TAB_STATE_LOADING , PLUMA_TAB_STATE_REVERTING , PLUMA_TAB_STATE_SAVING ,
PLUMA_TAB_STATE_PRINTING , PLUMA_TAB_STATE_PRINT_PREVIEWING , PLUMA_TAB_STATE_SHOWING_PRINT_PREVIEW , PLUMA_TAB_STATE_GENERIC_NOT_EDITABLE ,
PLUMA_TAB_STATE_LOADING_ERROR , PLUMA_TAB_STATE_REVERTING_ERROR , PLUMA_TAB_STATE_SAVING_ERROR , PLUMA_TAB_STATE_GENERIC_ERROR ,
PLUMA_TAB_STATE_CLOSING , PLUMA_TAB_STATE_EXTERNALLY_MODIFIED_NOTIFICATION , PLUMA_TAB_NUM_OF_STATES
}
Functions
GType pluma_tab_get_type (void)
PlumaView * pluma_tab_get_view (PlumaTab *tab)
PlumaDocument * pluma_tab_get_document (PlumaTab *tab)
PlumaTab * pluma_tab_get_from_document (PlumaDocument *doc)
PlumaTabState pluma_tab_get_state (PlumaTab *tab)
gboolean pluma_tab_get_auto_save_enabled (PlumaTab *tab)
void pluma_tab_set_auto_save_enabled (PlumaTab *tab, gboolean enable)
gint pluma_tab_get_auto_save_interval (PlumaTab *tab)
void pluma_tab_set_auto_save_interval (PlumaTab *tab, gint interval)
void pluma_tab_set_info_bar (PlumaTab *tab, GtkWidget *info_bar)
GtkWidget * _pluma_tab_new (void)
GtkWidget * _pluma_tab_new_from_uri (const gchar *uri, const PlumaEncoding *encoding, gint line_pos, gboolean create)
gchar * _pluma_tab_get_name (PlumaTab *tab)
gchar * _pluma_tab_get_tooltips (PlumaTab *tab)
GdkPixbuf * _pluma_tab_get_icon (PlumaTab *tab)
void _pluma_tab_load (PlumaTab *tab, const gchar *uri, const PlumaEncoding *encoding, gint line_pos, gboolean create)
void _pluma_tab_revert (PlumaTab *tab)
void _pluma_tab_save (PlumaTab *tab)
void _pluma_tab_save_as (PlumaTab *tab, const gchar *uri, const PlumaEncoding *encoding, PlumaDocumentNewlineType newline_type)
void _pluma_tab_print (PlumaTab *tab)
void _pluma_tab_print_preview (PlumaTab *tab)
void _pluma_tab_mark_for_closing (PlumaTab *tab)
gboolean _pluma_tab_can_close (PlumaTab *tab)
Macro Definition Documentation
PLUMA_IS_TAB
#define PLUMA_IS_TAB (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE((obj), PLUMA_TYPE_TAB))
Definition at line 67 of file pluma-tab.h.
Referenced by _pluma_tab_can_close(), _pluma_tab_get_icon(), _pluma_tab_get_name(), _pluma_tab_get_tooltips(), _pluma_tab_load(), _pluma_tab_mark_for_closing(), _pluma_tab_print(), _pluma_tab_print_preview(), _pluma_tab_revert(), _pluma_tab_save(), _pluma_tab_save_as(), _pluma_window_move_tab_to_new_window(), pluma_notebook_add_tab(), pluma_notebook_move_tab(), pluma_notebook_remove_tab(), pluma_notebook_reorder_tab(), pluma_tab_get_auto_save_enabled(), pluma_tab_get_auto_save_interval(), pluma_tab_get_state(), pluma_tab_set_auto_save_enabled(), pluma_tab_set_auto_save_interval(), pluma_tab_set_info_bar(), pluma_window_close_tab(), and pluma_window_set_active_tab().
PLUMA_IS_TAB_CLASS
#define PLUMA_IS_TAB_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_TAB))
Definition at line 68 of file pluma-tab.h.
PLUMA_TAB
#define PLUMA_TAB (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_TAB, PlumaTab))
Definition at line 65 of file pluma-tab.h.
Referenced by _pluma_cmd_file_save_documents_list(), _pluma_tab_new_from_uri(), pluma_tab_get_from_document(), pluma_window_close_tabs(), pluma_window_create_tab(), pluma_window_create_tab_from_uri(), pluma_window_get_active_tab(), pluma_window_get_active_view(), pluma_window_get_tab_from_location(), and pluma_window_get_unsaved_documents().
PLUMA_TAB_CLASS
#define PLUMA_TAB_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST((klass), PLUMA_TYPE_TAB, PlumaTabClass))
Definition at line 66 of file pluma-tab.h.
PLUMA_TAB_GET_CLASS
#define PLUMA_TAB_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS((obj), PLUMA_TYPE_TAB, PlumaTabClass))
Definition at line 69 of file pluma-tab.h.
PLUMA_TYPE_TAB
#define PLUMA_TYPE_TAB (pluma_tab_get_type())
Definition at line 64 of file pluma-tab.h.
Referenced by _pluma_tab_new().
Typedef Documentation
PlumaTab
typedef struct _PlumaTab PlumaTab
Definition at line 77 of file pluma-tab.h.
PlumaTabClass
typedef struct _PlumaTabClass PlumaTabClass
Definition at line 90 of file pluma-tab.h.
PlumaTabPrivate
typedef struct _PlumaTabPrivate PlumaTabPrivate
Definition at line 72 of file pluma-tab.h.
Enumeration Type Documentation
PlumaTabState
enum PlumaTabState
Enumerator
PLUMA_TAB_STATE_NORMAL
PLUMA_TAB_STATE_LOADING
PLUMA_TAB_STATE_REVERTING
PLUMA_TAB_STATE_SAVING
PLUMA_TAB_STATE_PRINTING
PLUMA_TAB_STATE_PRINT_PREVIEWING
PLUMA_TAB_STATE_SHOWING_PRINT_PREVIEW
PLUMA_TAB_STATE_GENERIC_NOT_EDITABLE
PLUMA_TAB_STATE_LOADING_ERROR
PLUMA_TAB_STATE_REVERTING_ERROR
PLUMA_TAB_STATE_SAVING_ERROR
PLUMA_TAB_STATE_GENERIC_ERROR
PLUMA_TAB_STATE_CLOSING
PLUMA_TAB_STATE_EXTERNALLY_MODIFIED_NOTIFICATION
PLUMA_TAB_NUM_OF_STATES
Definition at line 42 of file pluma-tab.h.
Function Documentation
_pluma_tab_can_close()
gboolean _pluma_tab_can_close (PlumaTab * tab)
Definition at line 2664 of file pluma-tab.c.
References FALSE, pluma_document_get_deleted(), PLUMA_IS_TAB, PLUMA_SETTINGS_SHOW_SAVE_CONFIRMATION, pluma_tab_get_document(), pluma_tab_get_state(), PLUMA_TAB_STATE_LOADING, PLUMA_TAB_STATE_LOADING_ERROR, PLUMA_TAB_STATE_REVERTING, PLUMA_TAB_STATE_REVERTING_ERROR, PLUMA_TAB_STATE_SAVING_ERROR, _PlumaTab::priv, and TRUE.
Referenced by pluma_window_get_unsaved_documents().
_pluma_tab_get_icon()
GdkPixbuf * _pluma_tab_get_icon (PlumaTab * tab)
Definition at line 1925 of file pluma-tab.c.
References NULL, pluma_document_get_location(), PLUMA_IS_TAB, pluma_tab_get_document(), PLUMA_TAB_STATE_EXTERNALLY_MODIFIED_NOTIFICATION, PLUMA_TAB_STATE_GENERIC_ERROR, PLUMA_TAB_STATE_LOADING, PLUMA_TAB_STATE_LOADING_ERROR, PLUMA_TAB_STATE_PRINT_PREVIEWING, PLUMA_TAB_STATE_PRINTING, PLUMA_TAB_STATE_REVERTING, PLUMA_TAB_STATE_REVERTING_ERROR, PLUMA_TAB_STATE_SAVING, PLUMA_TAB_STATE_SAVING_ERROR, PLUMA_TAB_STATE_SHOWING_PRINT_PREVIEW, and _PlumaTab::priv.
_pluma_tab_get_name()
gchar * _pluma_tab_get_name (PlumaTab * tab)
Definition at line 1700 of file pluma-tab.c.
References _, MAX_DOC_NAME_LENGTH, name, NULL, pluma_document_get_readonly(), pluma_document_get_short_name_for_display(), PLUMA_IS_TAB, pluma_tab_get_document(), and pluma_utils_str_middle_truncate().
_pluma_tab_get_tooltips()
gchar * _pluma_tab_get_tooltips (PlumaTab * tab)
Definition at line 1743 of file pluma-tab.c.
References _, mime_type, NULL, pluma_document_get_content_type(), pluma_document_get_encoding(), pluma_document_get_mime_type(), pluma_document_get_uri_for_display(), pluma_encoding_to_string(), PLUMA_IS_TAB, pluma_tab_get_document(), PLUMA_TAB_STATE_LOADING_ERROR, PLUMA_TAB_STATE_REVERTING_ERROR, PLUMA_TAB_STATE_SAVING_ERROR, pluma_utils_replace_home_dir_with_tilde(), and _PlumaTab::priv.
_pluma_tab_load()
void _pluma_tab_load (PlumaTab * tab, const gchar * uri, const PlumaEncoding * encoding, gint line_pos, gboolean create)
Definition at line 2028 of file pluma-tab.c.
References pluma_document_load(), PLUMA_IS_DOCUMENT, PLUMA_IS_TAB, pluma_tab_get_document(), PLUMA_TAB_STATE_LOADING, PLUMA_TAB_STATE_NORMAL, and _PlumaTab::priv.
Referenced by _pluma_tab_new_from_uri().
_pluma_tab_mark_for_closing()
void _pluma_tab_mark_for_closing (PlumaTab * tab)
Definition at line 2655 of file pluma-tab.c.
References PLUMA_IS_TAB, PLUMA_TAB_STATE_CLOSING, PLUMA_TAB_STATE_NORMAL, and _PlumaTab::priv.
_pluma_tab_new()
GtkWidget * _pluma_tab_new (void)
Definition at line 1640 of file pluma-tab.c.
References NULL, and PLUMA_TYPE_TAB.
Referenced by _pluma_tab_new_from_uri(), and pluma_window_create_tab().
_pluma_tab_new_from_uri()
GtkWidget * _pluma_tab_new_from_uri (const gchar * uri, const PlumaEncoding * encoding, gint line_pos, gboolean create)
Definition at line 1648 of file pluma-tab.c.
References _pluma_tab_load(), _pluma_tab_new(), NULL, and PLUMA_TAB.
Referenced by pluma_window_create_tab_from_uri().
_pluma_tab_print()
void _pluma_tab_print (PlumaTab * tab)
Definition at line 2629 of file pluma-tab.c.
References PLUMA_IS_TAB, PLUMA_TAB_STATE_SHOWING_PRINT_PREVIEW, and _PlumaTab::priv.
Referenced by _pluma_cmd_file_print().
_pluma_tab_print_preview()
void _pluma_tab_print_preview (PlumaTab * tab)
Definition at line 2646 of file pluma-tab.c.
References PLUMA_IS_TAB.
Referenced by _pluma_cmd_file_print_preview().
_pluma_tab_revert()
void _pluma_tab_revert (PlumaTab * tab)
Definition at line 2058 of file pluma-tab.c.
References FALSE, NULL, pluma_document_get_encoding(), pluma_document_get_uri(), pluma_document_load(), PLUMA_IS_DOCUMENT, PLUMA_IS_TAB, pluma_tab_get_document(), PLUMA_TAB_STATE_EXTERNALLY_MODIFIED_NOTIFICATION, PLUMA_TAB_STATE_NORMAL, PLUMA_TAB_STATE_REVERTING, and _PlumaTab::priv.
_pluma_tab_save()
void _pluma_tab_save (PlumaTab * tab)
Definition at line 2096 of file pluma-tab.c.
References NULL, pluma_document_get_encoding(), pluma_document_get_uri(), pluma_document_is_untitled(), pluma_document_save(), PLUMA_DOCUMENT_SAVE_IGNORE_MTIME, PLUMA_IS_DOCUMENT, PLUMA_IS_TAB, pluma_tab_get_document(), PLUMA_TAB_STATE_EXTERNALLY_MODIFIED_NOTIFICATION, PLUMA_TAB_STATE_NORMAL, PLUMA_TAB_STATE_SAVING, PLUMA_TAB_STATE_SHOWING_PRINT_PREVIEW, and _PlumaTab::priv.
_pluma_tab_save_as()
void _pluma_tab_save_as (PlumaTab * tab, const gchar * uri, const PlumaEncoding * encoding, PlumaDocumentNewlineType newline_type)
Definition at line 2206 of file pluma-tab.c.
References NULL, pluma_document_save_as(), pluma_document_set_newline_type(), PLUMA_IS_DOCUMENT, PLUMA_IS_TAB, pluma_tab_get_document(), PLUMA_TAB_STATE_EXTERNALLY_MODIFIED_NOTIFICATION, PLUMA_TAB_STATE_NORMAL, PLUMA_TAB_STATE_SAVING, PLUMA_TAB_STATE_SHOWING_PRINT_PREVIEW, and _PlumaTab::priv.
pluma_tab_get_auto_save_enabled()
gboolean pluma_tab_get_auto_save_enabled (PlumaTab * tab)
pluma_tab_get_auto_save_enabled: @tab: a PlumaTab
Gets the current state for the autosave feature
Return value: TRUE if the autosave is enabled, else FALSE
Definition at line 2704 of file pluma-tab.c.
References DEBUG_TAB, FALSE, pluma_debug(), PLUMA_IS_TAB, and _PlumaTab::priv.
pluma_tab_get_auto_save_interval()
gint pluma_tab_get_auto_save_interval (PlumaTab * tab)
pluma_tab_get_auto_save_interval: @tab: a PlumaTab
Gets the current interval for the autosaves
Return value: the value of the autosave
Definition at line 2784 of file pluma-tab.c.
References DEBUG_TAB, pluma_debug(), PLUMA_IS_TAB, and _PlumaTab::priv.
pluma_tab_get_document()
PlumaDocument * pluma_tab_get_document (PlumaTab * tab)
pluma_tab_get_document: @tab: a PlumaTab
Gets the PlumaDocument associated to @tab.
Returns: (transfer none): the PlumaDocument associated to @tab
Definition at line 1691 of file pluma-tab.c.
References PLUMA_DOCUMENT, and _PlumaTab::priv.
Referenced by _pluma_cmd_file_revert(), _pluma_tab_can_close(), _pluma_tab_get_icon(), _pluma_tab_get_name(), _pluma_tab_get_tooltips(), _pluma_tab_load(), _pluma_tab_revert(), _pluma_tab_save(), _pluma_tab_save_as(), pluma_tab_set_auto_save_enabled(), pluma_tab_set_auto_save_interval(), pluma_window_get_tab_from_location(), and pluma_window_get_unsaved_documents().
pluma_tab_get_from_document()
PlumaTab * pluma_tab_get_from_document (PlumaDocument * doc)
pluma_tab_get_from_document: @doc: a PlumaDocument
Gets the PlumaTab associated with @doc.
Returns: (transfer none): the PlumaTab associated with @doc
Definition at line 2016 of file pluma-tab.c.
References NULL, PLUMA_IS_DOCUMENT, PLUMA_TAB, and PLUMA_TAB_KEY.
Referenced by _pluma_cmd_file_save_documents_list(), and pluma_commands_save_document().
pluma_tab_get_state()
PlumaTabState pluma_tab_get_state (PlumaTab * tab)
pluma_tab_get_state: @tab: a PlumaTab
Gets the PlumaTabState of @tab.
Returns: the PlumaTabState of @tab
Definition at line 311 of file pluma-tab.c.
References PLUMA_IS_TAB, PLUMA_TAB_STATE_NORMAL, and _PlumaTab::priv.
Referenced by _pluma_cmd_file_revert(), _pluma_cmd_file_save_documents_list(), _pluma_tab_can_close(), pluma_tab_label_set_close_button_sensitive(), and pluma_window_close_tab().
pluma_tab_get_type()
GType pluma_tab_get_type (void)
pluma_tab_get_view()
PlumaView * pluma_tab_get_view (PlumaTab * tab)
pluma_tab_get_view: @tab: a PlumaTab
Gets the PlumaView inside @tab.
Returns: (transfer none): the PlumaView inside @tab
Definition at line 1677 of file pluma-tab.c.
References PLUMA_VIEW, and _PlumaTab::priv.
Referenced by pluma_notebook_add_tab(), and pluma_window_get_active_view().
pluma_tab_set_auto_save_enabled()
void pluma_tab_set_auto_save_enabled (PlumaTab * tab, gboolean enable)
pluma_tab_set_auto_save_enabled: @tab: a PlumaTab @enable: enable (TRUE) or disable (FALSE) auto save
Enables or disables the autosave feature. It does not install an autosave timeout if the document is new or is read-only
Definition at line 2722 of file pluma-tab.c.
References DEBUG_TAB, FALSE, NULL, pluma_app_get_default(), pluma_app_get_lockdown(), pluma_debug(), pluma_document_get_readonly(), pluma_document_is_untitled(), PLUMA_IS_TAB, PLUMA_LOCKDOWN_SAVE_TO_DISK, pluma_tab_get_document(), PLUMA_TAB_STATE_LOADING, PLUMA_TAB_STATE_LOADING_ERROR, PLUMA_TAB_STATE_REVERTING, PLUMA_TAB_STATE_REVERTING_ERROR, PLUMA_TAB_STATE_SAVING, PLUMA_TAB_STATE_SAVING_ERROR, and _PlumaTab::priv.
pluma_tab_set_auto_save_interval()
void pluma_tab_set_auto_save_interval (PlumaTab * tab, gint interval)
pluma_tab_set_auto_save_interval: @tab: a PlumaTab @interval: the new interval
Sets the interval for the autosave feature. It does nothing if the interval is the same as the one already present. It removes the old interval timeout and adds a new one with the autosave passed as argument.
Definition at line 2804 of file pluma-tab.c.
References DEBUG_TAB, NULL, pluma_debug(), pluma_document_get_readonly(), pluma_document_is_untitled(), PLUMA_IS_DOCUMENT, PLUMA_IS_TAB, pluma_tab_get_document(), and _PlumaTab::priv.
pluma_tab_set_info_bar()
void pluma_tab_set_info_bar (PlumaTab * tab, GtkWidget * info_bar)
Definition at line 2838 of file pluma-tab.c.
References NULL, and PLUMA_IS_TAB.