MATE Desktop Environment: pluma-history-entry.c File Reference
pluma-history-entry.c File Reference
#include <string.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include "pluma-history-entry.h"
#include "pluma-settings.h"
Macros
#define MIN_ITEM_LEN 3
#define PLUMA_HISTORY_ENTRY_HISTORY_LENGTH_DEFAULT 10
Enumerations
enum { PROP_0 , PROP_HISTORY_ID , PROP_HISTORY_LENGTH }
Functions
void pluma_history_entry_prepend_text (PlumaHistoryEntry *entry, const gchar *text)
void pluma_history_entry_append_text (PlumaHistoryEntry *entry, const gchar *text)
void pluma_history_entry_clear (PlumaHistoryEntry *entry)
void pluma_history_entry_set_history_length (PlumaHistoryEntry *entry, guint history_length)
guint pluma_history_entry_get_history_length (PlumaHistoryEntry *entry)
gchar * pluma_history_entry_get_history_id (PlumaHistoryEntry *entry)
void pluma_history_entry_set_enable_completion (PlumaHistoryEntry *entry, gboolean enable)
gboolean pluma_history_entry_get_enable_completion (PlumaHistoryEntry *entry)
GtkWidget * pluma_history_entry_new (const gchar *history_id, gboolean enable_completion)
GtkWidget * pluma_history_entry_get_entry (PlumaHistoryEntry *entry)
void pluma_history_entry_set_escape_func (PlumaHistoryEntry *entry, PlumaHistoryEntryEscapeFunc escape_func)
Macro Definition Documentation
MIN_ITEM_LEN
#define MIN_ITEM_LEN 3
Definition at line 50 of file pluma-history-entry.c.
PLUMA_HISTORY_ENTRY_HISTORY_LENGTH_DEFAULT
#define PLUMA_HISTORY_ENTRY_HISTORY_LENGTH_DEFAULT 10
Definition at line 52 of file pluma-history-entry.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_HISTORY_ID
PROP_HISTORY_LENGTH
Definition at line 44 of file pluma-history-entry.c.
Function Documentation
pluma_history_entry_append_text()
void pluma_history_entry_append_text (PlumaHistoryEntry * entry, const gchar * text)
Definition at line 338 of file pluma-history-entry.c.
References FALSE, NULL, and PLUMA_IS_HISTORY_ENTRY.
pluma_history_entry_clear()
void pluma_history_entry_clear (PlumaHistoryEntry * entry)
Definition at line 380 of file pluma-history-entry.c.
References PLUMA_IS_HISTORY_ENTRY.
pluma_history_entry_get_enable_completion()
gboolean pluma_history_entry_get_enable_completion (PlumaHistoryEntry * entry)
Definition at line 479 of file pluma-history-entry.c.
References FALSE, NULL, PLUMA_IS_HISTORY_ENTRY, and _PlumaHistoryEntry::priv.
pluma_history_entry_get_entry()
GtkWidget * pluma_history_entry_get_entry (PlumaHistoryEntry * entry)
Definition at line 540 of file pluma-history-entry.c.
References NULL, and PLUMA_IS_HISTORY_ENTRY.
Referenced by pluma_history_entry_set_enable_completion().
pluma_history_entry_get_history_id()
gchar * pluma_history_entry_get_history_id (PlumaHistoryEntry * entry)
Definition at line 429 of file pluma-history-entry.c.
References NULL, PLUMA_IS_HISTORY_ENTRY, and _PlumaHistoryEntry::priv.
pluma_history_entry_get_history_length()
guint pluma_history_entry_get_history_length (PlumaHistoryEntry * entry)
Definition at line 421 of file pluma-history-entry.c.
References PLUMA_IS_HISTORY_ENTRY, and _PlumaHistoryEntry::priv.
pluma_history_entry_new()
GtkWidget * pluma_history_entry_new (const gchar * history_id, gboolean enable_completion)
Definition at line 487 of file pluma-history-entry.c.
References NULL, PLUMA_HISTORY_ENTRY, pluma_history_entry_set_enable_completion(), PLUMA_TYPE_HISTORY_ENTRY, and TRUE.
pluma_history_entry_prepend_text()
void pluma_history_entry_prepend_text (PlumaHistoryEntry * entry, const gchar * text)
Definition at line 328 of file pluma-history-entry.c.
References NULL, PLUMA_IS_HISTORY_ENTRY, and TRUE.
pluma_history_entry_set_enable_completion()
void pluma_history_entry_set_enable_completion (PlumaHistoryEntry * entry, gboolean enable)
Definition at line 437 of file pluma-history-entry.c.
References FALSE, MIN_ITEM_LEN, NULL, pluma_history_entry_get_entry(), PLUMA_IS_HISTORY_ENTRY, _PlumaHistoryEntry::priv, and TRUE.
Referenced by pluma_history_entry_new().
pluma_history_entry_set_escape_func()
void pluma_history_entry_set_escape_func (PlumaHistoryEntry * entry, PlumaHistoryEntryEscapeFunc escape_func)
Definition at line 566 of file pluma-history-entry.c.
References NULL, and PLUMA_IS_HISTORY_ENTRY.
pluma_history_entry_set_history_length()
void pluma_history_entry_set_history_length (PlumaHistoryEntry * entry, guint history_length)
Definition at line 409 of file pluma-history-entry.c.
References PLUMA_IS_HISTORY_ENTRY, and _PlumaHistoryEntry::priv.