MATE Desktop Environment: pluma-commands-edit.c File Reference
pluma-commands-edit.c File Reference
#include <gtk/gtk.h>
#include "pluma-commands.h"
#include "pluma-window.h"
#include "pluma-debug.h"
#include "pluma-view.h"
#include "dialogs/pluma-preferences-dialog.h"
Functions
void _pluma_cmd_edit_undo (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_redo (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_cut (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_copy (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_paste (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_delete (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_select_all (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_upper_case (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_lower_case (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_invert_case (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_title_case (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_preferences (GtkAction *action, PlumaWindow *window)
Function Documentation
_pluma_cmd_edit_copy()
void _pluma_cmd_edit_copy (GtkAction * action, PlumaWindow * window)
Definition at line 105 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_copy_clipboard(), and pluma_window_get_active_view().
_pluma_cmd_edit_cut()
void _pluma_cmd_edit_cut (GtkAction * action, PlumaWindow * window)
Definition at line 89 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_cut_clipboard(), and pluma_window_get_active_view().
_pluma_cmd_edit_delete()
void _pluma_cmd_edit_delete (GtkAction * action, PlumaWindow * window)
Definition at line 137 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_delete_selection(), and pluma_window_get_active_view().
_pluma_cmd_edit_invert_case()
void _pluma_cmd_edit_invert_case (GtkAction * action, PlumaWindow * window)
Definition at line 201 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_invert_case_selection(), and pluma_window_get_active_view().
_pluma_cmd_edit_lower_case()
void _pluma_cmd_edit_lower_case (GtkAction * action, PlumaWindow * window)
Definition at line 185 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_lower_case_selection(), and pluma_window_get_active_view().
_pluma_cmd_edit_paste()
void _pluma_cmd_edit_paste (GtkAction * action, PlumaWindow * window)
Definition at line 121 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_paste_clipboard(), and pluma_window_get_active_view().
_pluma_cmd_edit_preferences()
void _pluma_cmd_edit_preferences (GtkAction * action, PlumaWindow * window)
Definition at line 233 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), and pluma_show_preferences_dialog().
_pluma_cmd_edit_redo()
void _pluma_cmd_edit_redo (GtkAction * action, PlumaWindow * window)
Definition at line 68 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_scroll_to_cursor(), and pluma_window_get_active_view().
_pluma_cmd_edit_select_all()
void _pluma_cmd_edit_select_all (GtkAction * action, PlumaWindow * window)
Definition at line 153 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_select_all(), and pluma_window_get_active_view().
_pluma_cmd_edit_title_case()
void _pluma_cmd_edit_title_case (GtkAction * action, PlumaWindow * window)
Definition at line 217 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_title_case_selection(), and pluma_window_get_active_view().
_pluma_cmd_edit_undo()
void _pluma_cmd_edit_undo (GtkAction * action, PlumaWindow * window)
Definition at line 47 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_scroll_to_cursor(), and pluma_window_get_active_view().
_pluma_cmd_edit_upper_case()
void _pluma_cmd_edit_upper_case (GtkAction * action, PlumaWindow * window)
Definition at line 169 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_upper_case_selection(), and pluma_window_get_active_view().