MATE Desktop Environment: pluma-commands-file-print.c File Reference
pluma-commands-file-print.c File Reference
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include "pluma-commands.h"
#include "pluma-window.h"
#include "pluma-tab.h"
#include "pluma-debug.h"
Functions
void _pluma_cmd_file_print_preview (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_print (GtkAction *action, PlumaWindow *window)
Function Documentation
_pluma_cmd_file_print()
void _pluma_cmd_file_print (GtkAction * action, PlumaWindow * window)
Definition at line 62 of file pluma-commands-file-print.c.
References _pluma_tab_print(), action, DEBUG_COMMANDS, NULL, pluma_debug(), and pluma_window_get_active_tab().
_pluma_cmd_file_print_preview()
void _pluma_cmd_file_print_preview (GtkAction * action, PlumaWindow * window)
Definition at line 47 of file pluma-commands-file-print.c.
References _pluma_tab_print_preview(), action, DEBUG_COMMANDS, NULL, pluma_debug(), and pluma_window_get_active_tab().