MATE Desktop Environment: pluma-document.h File Reference
pluma-document.h File Reference
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <gtksourceview/gtksource.h>
#include <pluma/pluma-encodings.h>
Classes
struct _PlumaDocument
struct _PlumaDocumentClass
Macros
#define PLUMA_TYPE_DOCUMENT (pluma_document_get_type())
#define PLUMA_DOCUMENT(obj)
#define PLUMA_DOCUMENT_CLASS(klass)
#define PLUMA_IS_DOCUMENT(obj)
#define PLUMA_IS_DOCUMENT_CLASS(klass)
#define PLUMA_DOCUMENT_GET_CLASS(obj)
#define PLUMA_METADATA_ATTRIBUTE_POSITION "metadata::pluma-position"
#define PLUMA_METADATA_ATTRIBUTE_ENCODING "metadata::pluma-encoding"
#define PLUMA_METADATA_ATTRIBUTE_LANGUAGE "metadata::pluma-language"
#define PLUMA_DOCUMENT_NEWLINE_TYPE_DEFAULT PLUMA_DOCUMENT_NEWLINE_TYPE_LF
#define PLUMA_DOCUMENT_ERROR pluma_document_error_quark ()
#define PLUMA_SEARCH_IS_DONT_SET_FLAGS(sflags)
#define PLUMA_SEARCH_SET_DONT_SET_FLAGS(sflags, state)
#define PLUMA_SEARCH_IS_ENTIRE_WORD(sflags)
#define PLUMA_SEARCH_SET_ENTIRE_WORD(sflags, state)
#define PLUMA_SEARCH_IS_CASE_SENSITIVE(sflags)
#define PLUMA_SEARCH_SET_CASE_SENSITIVE(sflags, state)
#define PLUMA_SEARCH_IS_PARSE_ESCAPES(sflags)
#define PLUMA_SEARCH_SET_PARSE_ESCAPES(sflags, state)
#define PLUMA_SEARCH_IS_MATCH_REGEX(sflags)
#define PLUMA_SEARCH_SET_MATCH_REGEX(sflags, state)
Typedefs
typedef struct _PlumaDocumentPrivate PlumaDocumentPrivate
typedef struct _PlumaDocument PlumaDocument
typedef struct _PlumaDocumentClass PlumaDocumentClass
typedef GMountOperation *(* PlumaMountOperationFactory) (PlumaDocument *doc, gpointer userdata)
Enumerations
enum PlumaDocumentNewlineType { PLUMA_DOCUMENT_NEWLINE_TYPE_LF , PLUMA_DOCUMENT_NEWLINE_TYPE_CR , PLUMA_DOCUMENT_NEWLINE_TYPE_CR_LF }
enum PlumaSearchFlags {
PLUMA_SEARCH_DONT_SET_FLAGS = 1 << 0 , PLUMA_SEARCH_ENTIRE_WORD = 1 << 1 , PLUMA_SEARCH_CASE_SENSITIVE = 1 << 2 , PLUMA_SEARCH_PARSE_ESCAPES = 1 << 3 ,
PLUMA_SEARCH_MATCH_REGEX = 1 << 4
}
enum PlumaDocumentSaveFlags { PLUMA_DOCUMENT_SAVE_IGNORE_MTIME = 1 << 0 , PLUMA_DOCUMENT_SAVE_IGNORE_BACKUP = 1 << 1 , PLUMA_DOCUMENT_SAVE_PRESERVE_BACKUP = 1 << 2 }
enum {
PLUMA_DOCUMENT_ERROR_EXTERNALLY_MODIFIED , PLUMA_DOCUMENT_ERROR_CANT_CREATE_BACKUP , PLUMA_DOCUMENT_ERROR_TOO_BIG , PLUMA_DOCUMENT_ERROR_ENCODING_AUTO_DETECTION_FAILED ,
PLUMA_DOCUMENT_ERROR_CONVERSION_FALLBACK , PLUMA_DOCUMENT_NUM_ERRORS
}
Functions
GQuark pluma_document_error_quark (void)
GType pluma_document_get_type (void)
PlumaDocument * pluma_document_new (void)
GFile * pluma_document_get_location (PlumaDocument *doc)
gchar * pluma_document_get_uri (PlumaDocument *doc)
void pluma_document_set_uri (PlumaDocument *doc, const gchar *uri)
gchar * pluma_document_get_uri_for_display (PlumaDocument *doc)
gchar * pluma_document_get_short_name_for_display (PlumaDocument *doc)
void pluma_document_set_short_name_for_display (PlumaDocument *doc, const gchar *name)
gchar * pluma_document_get_content_type (PlumaDocument *doc)
void pluma_document_set_content_type (PlumaDocument *doc, const gchar *content_type)
gchar * pluma_document_get_mime_type (PlumaDocument *doc)
gboolean pluma_document_get_readonly (PlumaDocument *doc)
void pluma_document_load (PlumaDocument *doc, const gchar *uri, const PlumaEncoding *encoding, gint line_pos, gboolean create)
gboolean pluma_document_insert_file (PlumaDocument *doc, GtkTextIter *iter, const gchar *uri, const PlumaEncoding *encoding)
gboolean pluma_document_load_cancel (PlumaDocument *doc)
void pluma_document_save (PlumaDocument *doc, PlumaDocumentSaveFlags flags)
void pluma_document_save_as (PlumaDocument *doc, const gchar *uri, const PlumaEncoding *encoding, PlumaDocumentSaveFlags flags)
gboolean pluma_document_is_untouched (PlumaDocument *doc)
gboolean pluma_document_is_untitled (PlumaDocument *doc)
gboolean pluma_document_is_local (PlumaDocument *doc)
gboolean pluma_document_get_deleted (PlumaDocument *doc)
gboolean pluma_document_goto_line (PlumaDocument *doc, gint line)
gboolean pluma_document_goto_line_offset (PlumaDocument *doc, gint line, gint line_offset)
void pluma_document_set_search_text (PlumaDocument *doc, const gchar *text, guint flags)
gchar * pluma_document_get_search_text (PlumaDocument *doc, guint *flags)
gchar * pluma_document_get_last_replace_text (PlumaDocument *doc)
void pluma_document_set_last_replace_text (PlumaDocument *doc, const gchar *text)
gboolean pluma_document_get_can_search_again (PlumaDocument *doc)
gboolean pluma_document_search_forward (PlumaDocument *doc, const GtkTextIter *start, const GtkTextIter *end, GtkTextIter *match_start, GtkTextIter *match_end)
gboolean pluma_document_search_backward (PlumaDocument *doc, const GtkTextIter *start, const GtkTextIter *end, GtkTextIter *match_start, GtkTextIter *match_end)
gint pluma_document_replace_all (PlumaDocument *doc, const gchar *find, const gchar *replace, guint flags)
void pluma_document_set_language (PlumaDocument *doc, GtkSourceLanguage *lang)
GtkSourceLanguage * pluma_document_get_language (PlumaDocument *doc)
const PlumaEncoding * pluma_document_get_encoding (PlumaDocument *doc)
void pluma_document_set_enable_search_highlighting (PlumaDocument *doc, gboolean enable)
gboolean pluma_document_get_enable_search_highlighting (PlumaDocument *doc)
void pluma_document_set_newline_type (PlumaDocument *doc, PlumaDocumentNewlineType newline_type)
PlumaDocumentNewlineType pluma_document_get_newline_type (PlumaDocument *doc)
gchar * pluma_document_get_metadata (PlumaDocument *doc, const gchar *key)
void pluma_document_set_metadata (PlumaDocument *doc, const gchar *first_key,...)
void _pluma_document_set_readonly (PlumaDocument *doc, gboolean readonly)
glong _pluma_document_get_seconds_since_last_save_or_load (PlumaDocument *doc)
gboolean _pluma_document_check_externally_modified (PlumaDocument *doc)
void _pluma_document_search_region (PlumaDocument *doc, const GtkTextIter *start, const GtkTextIter *end)
void _pluma_document_set_mount_operation_factory (PlumaDocument *doc, PlumaMountOperationFactory callback, gpointer userdata)
GMountOperation * _pluma_document_create_mount_operation (PlumaDocument *doc)
Macro Definition Documentation
PLUMA_DOCUMENT
#define PLUMA_DOCUMENT (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_DOCUMENT, PlumaDocument))
Definition at line 49 of file pluma-document.h.
Referenced by _pluma_cmd_file_save_documents_list(), _pluma_cmd_search_clear_highlight(), pluma_document_new(), pluma_tab_get_document(), pluma_view_cut_clipboard(), pluma_view_delete_selection(), pluma_view_paste_clipboard(), and pluma_window_get_active_document().
PLUMA_DOCUMENT_CLASS
#define PLUMA_DOCUMENT_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST((klass), PLUMA_TYPE_DOCUMENT, PlumaDocumentClass))
Definition at line 50 of file pluma-document.h.
PLUMA_DOCUMENT_ERROR
#define PLUMA_DOCUMENT_ERROR pluma_document_error_quark ()
Definition at line 154 of file pluma-document.h.
Referenced by pluma_externally_modified_saving_error_message_area_new(), pluma_io_loading_error_message_area_new(), pluma_no_backup_saving_error_message_area_new(), pluma_unrecoverable_reverting_error_message_area_new(), and pluma_unrecoverable_saving_error_message_area_new().
PLUMA_DOCUMENT_GET_CLASS
#define PLUMA_DOCUMENT_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS((obj), PLUMA_TYPE_DOCUMENT, PlumaDocumentClass))
Definition at line 53 of file pluma-document.h.
PLUMA_DOCUMENT_NEWLINE_TYPE_DEFAULT
#define PLUMA_DOCUMENT_NEWLINE_TYPE_DEFAULT PLUMA_DOCUMENT_NEWLINE_TYPE_LF
Definition at line 66 of file pluma-document.h.
Referenced by pluma_document_output_stream_detect_newline_type(), and pluma_file_chooser_dialog_get_newline_type().
PLUMA_IS_DOCUMENT
#define PLUMA_IS_DOCUMENT (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE((obj), PLUMA_TYPE_DOCUMENT))
Definition at line 51 of file pluma-document.h.
Referenced by _pluma_cmd_file_save_documents_list(), _pluma_document_check_externally_modified(), _pluma_document_create_mount_operation(), _pluma_document_get_seconds_since_last_save_or_load(), _pluma_document_search_region(), _pluma_document_set_mount_operation_factory(), _pluma_document_set_readonly(), _pluma_tab_load(), _pluma_tab_revert(), _pluma_tab_save(), _pluma_tab_save_as(), pluma_automatic_spell_checker_get_from_document(), pluma_automatic_spell_checker_new(), pluma_commands_save_document(), pluma_document_get_can_search_again(), pluma_document_get_content_type(), pluma_document_get_deleted(), pluma_document_get_enable_search_highlighting(), pluma_document_get_encoding(), pluma_document_get_language(), pluma_document_get_last_replace_text(), pluma_document_get_location(), pluma_document_get_metadata(), pluma_document_get_mime_type(), pluma_document_get_newline_type(), pluma_document_get_readonly(), pluma_document_get_search_text(), pluma_document_get_short_name_for_display(), pluma_document_get_uri(), pluma_document_get_uri_for_display(), pluma_document_goto_line(), pluma_document_goto_line_offset(), pluma_document_insert_file(), pluma_document_is_local(), pluma_document_is_untitled(), pluma_document_is_untouched(), pluma_document_load(), pluma_document_load_cancel(), pluma_document_loader_new(), pluma_document_replace_all(), pluma_document_save(), pluma_document_save_as(), pluma_document_search_backward(), pluma_document_search_forward(), pluma_document_set_content_type(), pluma_document_set_enable_search_highlighting(), pluma_document_set_language(), pluma_document_set_last_replace_text(), pluma_document_set_metadata(), pluma_document_set_newline_type(), pluma_document_set_search_text(), pluma_document_set_short_name_for_display(), pluma_document_set_uri(), pluma_tab_get_from_document(), pluma_tab_set_auto_save_interval(), and pluma_view_new().
PLUMA_IS_DOCUMENT_CLASS
#define PLUMA_IS_DOCUMENT_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_DOCUMENT))
Definition at line 52 of file pluma-document.h.
PLUMA_METADATA_ATTRIBUTE_ENCODING
#define PLUMA_METADATA_ATTRIBUTE_ENCODING "metadata::pluma-encoding"
Definition at line 56 of file pluma-document.h.
PLUMA_METADATA_ATTRIBUTE_LANGUAGE
#define PLUMA_METADATA_ATTRIBUTE_LANGUAGE "metadata::pluma-language"
Definition at line 57 of file pluma-document.h.
PLUMA_METADATA_ATTRIBUTE_POSITION
#define PLUMA_METADATA_ATTRIBUTE_POSITION "metadata::pluma-position"
Definition at line 55 of file pluma-document.h.
PLUMA_SEARCH_IS_CASE_SENSITIVE
#define PLUMA_SEARCH_IS_CASE_SENSITIVE (sflags)
Value:
((sflags &  PLUMA_SEARCH_CASE_SENSITIVE) != 0)
Definition at line 321 of file pluma-document.h.
Referenced by pluma_document_replace_all(), pluma_document_search_backward(), and pluma_document_search_forward().
PLUMA_SEARCH_IS_DONT_SET_FLAGS
#define PLUMA_SEARCH_IS_DONT_SET_FLAGS (sflags)
Value:
((sflags & PLUMA_SEARCH_DONT_SET_FLAGS) != 0)
Definition at line 313 of file pluma-document.h.
Referenced by pluma_document_set_search_text().
PLUMA_SEARCH_IS_ENTIRE_WORD
#define PLUMA_SEARCH_IS_ENTIRE_WORD (sflags)
Value:
((sflags & PLUMA_SEARCH_ENTIRE_WORD) != 0)
Definition at line 317 of file pluma-document.h.
Referenced by pluma_document_replace_all(), pluma_document_search_backward(), and pluma_document_search_forward().
PLUMA_SEARCH_IS_MATCH_REGEX
#define PLUMA_SEARCH_IS_MATCH_REGEX (sflags)
Value:
((sflags &  PLUMA_SEARCH_MATCH_REGEX) != 0)
Definition at line 329 of file pluma-document.h.
Referenced by pluma_document_replace_all(), pluma_document_search_backward(), and pluma_document_search_forward().
PLUMA_SEARCH_IS_PARSE_ESCAPES
#define PLUMA_SEARCH_IS_PARSE_ESCAPES (sflags)
Value:
((sflags &  PLUMA_SEARCH_PARSE_ESCAPES) != 0)
Definition at line 325 of file pluma-document.h.
PLUMA_SEARCH_SET_CASE_SENSITIVE
#define PLUMA_SEARCH_SET_CASE_SENSITIVE (sflags, state)
Value:
((state == TRUE) ? \
(sflags |= PLUMA_SEARCH_CASE_SENSITIVE) : (sflags &= ~PLUMA_SEARCH_CASE_SENSITIVE))
Definition at line 322 of file pluma-document.h.
PLUMA_SEARCH_SET_DONT_SET_FLAGS
#define PLUMA_SEARCH_SET_DONT_SET_FLAGS (sflags, state)
Value:
((state == TRUE) ? \
(sflags |= PLUMA_SEARCH_DONT_SET_FLAGS) : (sflags &= ~PLUMA_SEARCH_DONT_SET_FLAGS))
Definition at line 314 of file pluma-document.h.
PLUMA_SEARCH_SET_ENTIRE_WORD
#define PLUMA_SEARCH_SET_ENTIRE_WORD (sflags, state)
Value:
((state == TRUE) ? \
(sflags |= PLUMA_SEARCH_ENTIRE_WORD) : (sflags &= ~PLUMA_SEARCH_ENTIRE_WORD))
Definition at line 318 of file pluma-document.h.
PLUMA_SEARCH_SET_MATCH_REGEX
#define PLUMA_SEARCH_SET_MATCH_REGEX (sflags, state)
Value:
((state == TRUE) ? \
(sflags |= PLUMA_SEARCH_MATCH_REGEX) : (sflags &= ~PLUMA_SEARCH_MATCH_REGEX))
Definition at line 330 of file pluma-document.h.
PLUMA_SEARCH_SET_PARSE_ESCAPES
#define PLUMA_SEARCH_SET_PARSE_ESCAPES (sflags, state)
Value:
((state == TRUE) ? \
(sflags |= PLUMA_SEARCH_PARSE_ESCAPES) : (sflags &= ~PLUMA_SEARCH_PARSE_ESCAPES))
Definition at line 326 of file pluma-document.h.
PLUMA_TYPE_DOCUMENT
#define PLUMA_TYPE_DOCUMENT (pluma_document_get_type())
Definition at line 48 of file pluma-document.h.
Referenced by pluma_document_new().
Typedef Documentation
PlumaDocument
typedef struct _PlumaDocument PlumaDocument
Definition at line 97 of file pluma-document.h.
PlumaDocumentClass
typedef struct _PlumaDocumentClass PlumaDocumentClass
Definition at line 110 of file pluma-document.h.
PlumaDocumentPrivate
typedef struct _PlumaDocumentPrivate PlumaDocumentPrivate
Definition at line 92 of file pluma-document.h.
PlumaMountOperationFactory
typedef GMountOperation *(* PlumaMountOperationFactory) (PlumaDocument *doc, gpointer userdata)
Definition at line 334 of file pluma-document.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PLUMA_DOCUMENT_ERROR_EXTERNALLY_MODIFIED
PLUMA_DOCUMENT_ERROR_CANT_CREATE_BACKUP
PLUMA_DOCUMENT_ERROR_TOO_BIG
PLUMA_DOCUMENT_ERROR_ENCODING_AUTO_DETECTION_FAILED
PLUMA_DOCUMENT_ERROR_CONVERSION_FALLBACK
PLUMA_DOCUMENT_NUM_ERRORS
Definition at line 156 of file pluma-document.h.
PlumaDocumentNewlineType
enum PlumaDocumentNewlineType
Enumerator
PLUMA_DOCUMENT_NEWLINE_TYPE_LF
PLUMA_DOCUMENT_NEWLINE_TYPE_CR
PLUMA_DOCUMENT_NEWLINE_TYPE_CR_LF
Definition at line 59 of file pluma-document.h.
PlumaDocumentSaveFlags
enum PlumaDocumentSaveFlags
PlumaDocumentSaveFlags: @PLUMA_DOCUMENT_SAVE_IGNORE_MTIME: save file despite external modifications. @PLUMA_DOCUMENT_SAVE_IGNORE_BACKUP: write the file directly without attempting to backup. @PLUMA_DOCUMENT_SAVE_PRESERVE_BACKUP: preserve previous backup file, needed to support autosaving.
Enumerator
PLUMA_DOCUMENT_SAVE_IGNORE_MTIME
PLUMA_DOCUMENT_SAVE_IGNORE_BACKUP
PLUMA_DOCUMENT_SAVE_PRESERVE_BACKUP
Definition at line 84 of file pluma-document.h.
PlumaSearchFlags
enum PlumaSearchFlags
Enumerator
PLUMA_SEARCH_DONT_SET_FLAGS
PLUMA_SEARCH_ENTIRE_WORD
PLUMA_SEARCH_CASE_SENSITIVE
PLUMA_SEARCH_PARSE_ESCAPES
PLUMA_SEARCH_MATCH_REGEX
Definition at line 68 of file pluma-document.h.
Function Documentation
_pluma_document_check_externally_modified()
gboolean _pluma_document_check_externally_modified (PlumaDocument * doc)
Definition at line 1300 of file pluma-document.c.
References _pluma_document_set_readonly(), FALSE, NULL, PLUMA_IS_DOCUMENT, and _PlumaDocument::priv.
_pluma_document_create_mount_operation()
GMountOperation * _pluma_document_create_mount_operation (PlumaDocument * doc)
Definition at line 2826 of file pluma-document.c.
References NULL, PLUMA_IS_DOCUMENT, and _PlumaDocument::priv.
_pluma_document_get_seconds_since_last_save_or_load()
glong _pluma_document_get_seconds_since_last_save_or_load (PlumaDocument * doc)
Definition at line 2385 of file pluma-document.c.
References DEBUG_DOCUMENT, pluma_debug(), PLUMA_IS_DOCUMENT, and _PlumaDocument::priv.
_pluma_document_search_region()
void _pluma_document_search_region (PlumaDocument * doc, const GtkTextIter * start, const GtkTextIter * end)
Definition at line 2635 of file pluma-document.c.
References DEBUG_DOCUMENT, NULL, pluma_debug(), PLUMA_IS_DOCUMENT, pluma_text_region_destroy(), pluma_text_region_intersect(), pluma_text_region_nth_subregion(), pluma_text_region_subregions(), pluma_text_region_subtract(), _PlumaDocument::priv, and TRUE.
_pluma_document_set_mount_operation_factory()
void _pluma_document_set_mount_operation_factory (PlumaDocument * doc, PlumaMountOperationFactory callback, gpointer userdata)
Definition at line 2815 of file pluma-document.c.
References PLUMA_IS_DOCUMENT, and _PlumaDocument::priv.
_pluma_document_set_readonly()
void _pluma_document_set_readonly (PlumaDocument * doc, gboolean readonly)
pluma_document_set_readonly: @doc: a PlumaDocument @readonly: TRUE to se the document as read-only
If @readonly is TRUE sets @doc as read-only.
Definition at line 1278 of file pluma-document.c.
References DEBUG_DOCUMENT, pluma_debug(), and PLUMA_IS_DOCUMENT.
Referenced by _pluma_document_check_externally_modified().
pluma_document_error_quark()
GQuark pluma_document_error_quark (void)
Definition at line 188 of file pluma-document.c.
pluma_document_get_can_search_again()
gboolean pluma_document_get_can_search_again (PlumaDocument * doc)
Definition at line 2024 of file pluma-document.c.
References FALSE, NULL, PLUMA_IS_DOCUMENT, and _PlumaDocument::priv.
Referenced by pluma_document_set_enable_search_highlighting(), and pluma_document_set_search_text().
pluma_document_get_content_type()
gchar * pluma_document_get_content_type (PlumaDocument * doc)
Definition at line 1224 of file pluma-document.c.
References NULL, PLUMA_IS_DOCUMENT, and _PlumaDocument::priv.
Referenced by _pluma_tab_get_tooltips().
pluma_document_get_deleted()
gboolean pluma_document_get_deleted (PlumaDocument * doc)
Definition at line 1804 of file pluma-document.c.
References FALSE, PLUMA_IS_DOCUMENT, pluma_utils_uri_exists(), and _PlumaDocument::priv.
Referenced by _pluma_tab_can_close().
pluma_document_get_enable_search_highlighting()
gboolean pluma_document_get_enable_search_highlighting (PlumaDocument * doc)
Definition at line 2785 of file pluma-document.c.
References FALSE, NULL, PLUMA_IS_DOCUMENT, and _PlumaDocument::priv.
Referenced by pluma_document_replace_all().
pluma_document_get_encoding()
const PlumaEncoding * pluma_document_get_encoding (PlumaDocument * doc)
Definition at line 2377 of file pluma-document.c.
References NULL, PLUMA_IS_DOCUMENT, and _PlumaDocument::priv.
Referenced by _pluma_tab_get_tooltips(), _pluma_tab_revert(), and _pluma_tab_save().
pluma_document_get_language()
GtkSourceLanguage * pluma_document_get_language (PlumaDocument * doc)
pluma_document_get_language: @doc:
Return value: (transfer none):
Definition at line 2369 of file pluma-document.c.
References NULL, and PLUMA_IS_DOCUMENT.
pluma_document_get_last_replace_text()
gchar * pluma_document_get_last_replace_text (PlumaDocument * doc)
pluma_document_get_last_replace_text: @doc:
Definition at line 2016 of file pluma-document.c.
References NULL, PLUMA_IS_DOCUMENT, and _PlumaDocument::priv.
pluma_document_get_location()
GFile * pluma_document_get_location (PlumaDocument * doc)
pluma_document_get_location: @doc: a PlumaDocument
Returns: (allow-none) (transfer full): a new #GFile
Definition at line 1142 of file pluma-document.c.
References NULL, PLUMA_IS_DOCUMENT, and _PlumaDocument::priv.
Referenced by _pluma_cmd_file_open(), _pluma_tab_get_icon(), and pluma_window_get_tab_from_location().
pluma_document_get_metadata()
gchar * pluma_document_get_metadata (PlumaDocument * doc, const gchar * key)
Definition at line 2839 of file pluma-document.c.
References key, NULL, pluma_document_is_untitled(), PLUMA_IS_DOCUMENT, pluma_metadata_manager_get(), and _PlumaDocument::priv.
pluma_document_get_mime_type()
gchar * pluma_document_get_mime_type (PlumaDocument * doc)
pluma_document_get_mime_type: @doc:
Note: this never returns NULL.
Definition at line 1238 of file pluma-document.c.
References mime_type, NULL, PLUMA_IS_DOCUMENT, and _PlumaDocument::priv.
Referenced by _pluma_tab_get_tooltips().
pluma_document_get_newline_type()
PlumaDocumentNewlineType pluma_document_get_newline_type (PlumaDocument * doc)
Definition at line 2807 of file pluma-document.c.
References PLUMA_IS_DOCUMENT, and _PlumaDocument::priv.
pluma_document_get_readonly()
gboolean pluma_document_get_readonly (PlumaDocument * doc)
Definition at line 1292 of file pluma-document.c.
References PLUMA_IS_DOCUMENT, _PlumaDocument::priv, and TRUE.
Referenced by _pluma_cmd_file_save_documents_list(), _pluma_tab_get_name(), pluma_tab_set_auto_save_enabled(), pluma_tab_set_auto_save_interval(), pluma_view_cut_clipboard(), pluma_view_delete_selection(), and pluma_view_paste_clipboard().
pluma_document_get_search_text()
gchar * pluma_document_get_search_text (PlumaDocument * doc, guint * flags)
pluma_document_get_search_text: @doc: @flags: (allow-none):
Definition at line 1983 of file pluma-document.c.
References NULL, PLUMA_IS_DOCUMENT, pluma_utils_escape_search_text(), and _PlumaDocument::priv.
pluma_document_get_short_name_for_display()
gchar * pluma_document_get_short_name_for_display (PlumaDocument * doc)
pluma_document_get_short_name_for_display: @doc:
Note: this never returns NULL.
Definition at line 1193 of file pluma-document.c.
References _, NULL, PLUMA_IS_DOCUMENT, pluma_utils_basename_for_display(), and _PlumaDocument::priv.
Referenced by _pluma_tab_get_name(), and pluma_print_job_print().
pluma_document_get_type()
GType pluma_document_get_type (void)
References key, and name.
pluma_document_get_uri()
gchar * pluma_document_get_uri (PlumaDocument * doc)
Definition at line 1150 of file pluma-document.c.
References NULL, PLUMA_IS_DOCUMENT, and _PlumaDocument::priv.
Referenced by _pluma_tab_revert(), and _pluma_tab_save().
pluma_document_get_uri_for_display()
gchar * pluma_document_get_uri_for_display (PlumaDocument * doc)
pluma_document_get_uri_for_display: @doc:
Note: this never returns NULL.
Definition at line 1175 of file pluma-document.c.
References _, NULL, PLUMA_IS_DOCUMENT, pluma_utils_uri_for_display(), and _PlumaDocument::priv.
Referenced by _pluma_cmd_file_save_documents_list(), and _pluma_tab_get_tooltips().
pluma_document_goto_line()
gboolean pluma_document_goto_line (PlumaDocument * doc, gint line)
Definition at line 1816 of file pluma-document.c.
References DEBUG_DOCUMENT, FALSE, pluma_debug(), PLUMA_IS_DOCUMENT, and TRUE.
pluma_document_goto_line_offset()
gboolean pluma_document_goto_line_offset (PlumaDocument * doc, gint line, gint line_offset)
Definition at line 1849 of file pluma-document.c.
References FALSE, PLUMA_IS_DOCUMENT, and TRUE.
pluma_document_insert_file()
gboolean pluma_document_insert_file (PlumaDocument * doc, GtkTextIter * iter, const gchar * uri, const PlumaEncoding * encoding)
Definition at line 1758 of file pluma-document.c.
References FALSE, NULL, and PLUMA_IS_DOCUMENT.
pluma_document_is_local()
gboolean pluma_document_is_local (PlumaDocument * doc)
Definition at line 1791 of file pluma-document.c.
References FALSE, NULL, PLUMA_IS_DOCUMENT, pluma_utils_uri_has_file_scheme(), and _PlumaDocument::priv.
pluma_document_is_untitled()
gboolean pluma_document_is_untitled (PlumaDocument * doc)
Definition at line 1783 of file pluma-document.c.
References NULL, PLUMA_IS_DOCUMENT, _PlumaDocument::priv, and TRUE.
Referenced by _pluma_cmd_file_revert(), _pluma_cmd_file_save_documents_list(), _pluma_tab_save(), pluma_document_get_metadata(), pluma_document_set_metadata(), pluma_tab_set_auto_save_enabled(), and pluma_tab_set_auto_save_interval().
pluma_document_is_untouched()
gboolean pluma_document_is_untouched (PlumaDocument * doc)
Definition at line 1774 of file pluma-document.c.
References NULL, PLUMA_IS_DOCUMENT, _PlumaDocument::priv, and TRUE.
pluma_document_load()
void pluma_document_load (PlumaDocument * doc, const gchar * uri, const PlumaEncoding * encoding, gint line_pos, gboolean create)
pluma_document_load: @doc: the PlumaDocument. @uri: the uri where to load the document from. @encoding: the PlumaEncoding to encode the document. @line_pos: the line to show. @create: whether the document should be created if it doesn't exist.
Load a document. This results in the "load" signal to be emitted.
Definition at line 1565 of file pluma-document.c.
References LOAD, NULL, PLUMA_IS_DOCUMENT, and pluma_utils_is_valid_uri().
Referenced by _pluma_tab_load(), and _pluma_tab_revert().
pluma_document_load_cancel()
gboolean pluma_document_load_cancel (PlumaDocument * doc)
pluma_document_load_cancel: @doc: the PlumaDocument.
Cancel load of a document.
Definition at line 1585 of file pluma-document.c.
References FALSE, NULL, pluma_document_loader_cancel(), PLUMA_IS_DOCUMENT, and _PlumaDocument::priv.
pluma_document_new()
PlumaDocument * pluma_document_new (void)
Definition at line 1028 of file pluma-document.c.
References DEBUG_DOCUMENT, NULL, pluma_debug(), PLUMA_DOCUMENT, and PLUMA_TYPE_DOCUMENT.
pluma_document_replace_all()
gint pluma_document_replace_all (PlumaDocument * doc, const gchar * find, const gchar * replace, guint flags)
Definition at line 2214 of file pluma-document.c.
References FALSE, NULL, pluma_document_get_enable_search_highlighting(), pluma_document_set_enable_search_highlighting(), pluma_gtk_text_iter_regex_search(), PLUMA_IS_DOCUMENT, PLUMA_SEARCH_IS_CASE_SENSITIVE, PLUMA_SEARCH_IS_ENTIRE_WORD, PLUMA_SEARCH_IS_MATCH_REGEX, pluma_utils_unescape_search_text(), _PlumaDocument::priv, and TRUE.
pluma_document_save()
void pluma_document_save (PlumaDocument * doc, PlumaDocumentSaveFlags flags)
pluma_document_save: @doc: the PlumaDocument. @flags: optionnal PlumaDocumentSaveFlags.
Save the document to its previous location. This results in the "save" signal to be emitted.
Definition at line 1713 of file pluma-document.c.
References NULL, PLUMA_IS_DOCUMENT, _PlumaDocument::priv, and SAVE.
Referenced by _pluma_tab_save().
pluma_document_save_as()
void pluma_document_save_as (PlumaDocument * doc, const gchar * uri, const PlumaEncoding * encoding, PlumaDocumentSaveFlags flags)
pluma_document_save_as: @doc: the PlumaDocument. @uri: the uri where to save the document. @encoding: the PlumaEncoding to encode the document. @flags: optionnal PlumaDocumentSaveFlags.
Save the document to a new location. This results in the "save" signal to be emitted.
Definition at line 1738 of file pluma-document.c.
References NULL, PLUMA_DOCUMENT_SAVE_IGNORE_MTIME, PLUMA_IS_DOCUMENT, and SAVE.
Referenced by _pluma_tab_save_as().
pluma_document_search_backward()
gboolean pluma_document_search_backward (PlumaDocument * doc, const GtkTextIter * start, const GtkTextIter * end, GtkTextIter * match_start, GtkTextIter * match_end)
pluma_document_search_backward: @doc: @start: (allow-none): @end: (allow-none): @match_start: (allow-none): @match_end: (allow-none):
Definition at line 2130 of file pluma-document.c.
References DEBUG_DOCUMENT, FALSE, NULL, pluma_debug_message(), pluma_gtk_text_iter_regex_search(), PLUMA_IS_DOCUMENT, PLUMA_SEARCH_IS_CASE_SENSITIVE, PLUMA_SEARCH_IS_ENTIRE_WORD, PLUMA_SEARCH_IS_MATCH_REGEX, and _PlumaDocument::priv.
pluma_document_search_forward()
gboolean pluma_document_search_forward (PlumaDocument * doc, const GtkTextIter * start, const GtkTextIter * end, GtkTextIter * match_start, GtkTextIter * match_end)
pluma_document_search_forward: @doc: @start: (allow-none): @end: (allow-none): @match_start: (allow-none): @match_end: (allow-none):
Definition at line 2041 of file pluma-document.c.
References DEBUG_DOCUMENT, FALSE, NULL, pluma_debug_message(), pluma_gtk_text_iter_regex_search(), PLUMA_IS_DOCUMENT, PLUMA_SEARCH_IS_CASE_SENSITIVE, PLUMA_SEARCH_IS_ENTIRE_WORD, PLUMA_SEARCH_IS_MATCH_REGEX, _PlumaDocument::priv, and TRUE.
pluma_document_set_content_type()
void pluma_document_set_content_type (PlumaDocument * doc, const gchar * content_type)
pluma_document_set_content_type: @doc: @content_type: (allow-none):
Definition at line 1095 of file pluma-document.c.
References PLUMA_IS_DOCUMENT.
pluma_document_set_enable_search_highlighting()
void pluma_document_set_enable_search_highlighting (PlumaDocument * doc, gboolean enable)
Definition at line 2731 of file pluma-document.c.
References FALSE, NULL, pluma_document_get_can_search_again(), PLUMA_IS_DOCUMENT, pluma_text_region_destroy(), pluma_text_region_new(), _PlumaDocument::priv, and TRUE.
Referenced by pluma_document_replace_all().
pluma_document_set_language()
void pluma_document_set_language (PlumaDocument * doc, GtkSourceLanguage * lang)
pluma_document_set_language: @doc: @lang: (allow-none):
Definition at line 2354 of file pluma-document.c.
References PLUMA_IS_DOCUMENT, and TRUE.
pluma_document_set_last_replace_text()
void pluma_document_set_last_replace_text (PlumaDocument * doc, const gchar * text)
pluma_document_set_last_replace_text: @doc: @text: (allow-none):
Definition at line 2000 of file pluma-document.c.
References DEBUG_SEARCH, NULL, pluma_debug_message(), PLUMA_IS_DOCUMENT, and _PlumaDocument::priv.
pluma_document_set_metadata()
void pluma_document_set_metadata (PlumaDocument * doc, const gchar * first_key, ...)
Definition at line 2856 of file pluma-document.c.
References key, NULL, pluma_document_is_untitled(), PLUMA_IS_DOCUMENT, pluma_metadata_manager_set(), and _PlumaDocument::priv.
pluma_document_set_newline_type()
void pluma_document_set_newline_type (PlumaDocument * doc, PlumaDocumentNewlineType newline_type)
Definition at line 2793 of file pluma-document.c.
References PLUMA_IS_DOCUMENT, and _PlumaDocument::priv.
Referenced by _pluma_tab_save_as().
pluma_document_set_search_text()
void pluma_document_set_search_text (PlumaDocument * doc, const gchar * text, guint flags)
pluma_document_set_search_text: @doc: @text: (allow-none): @flags:
Definition at line 1916 of file pluma-document.c.
References DEBUG_DOCUMENT, FALSE, NULL, pluma_debug_message(), pluma_document_get_can_search_again(), PLUMA_IS_DOCUMENT, PLUMA_SEARCH_IS_DONT_SET_FLAGS, pluma_utils_unescape_search_text(), _PlumaDocument::priv, and TRUE.
Referenced by _pluma_cmd_search_clear_highlight().
pluma_document_set_short_name_for_display()
void pluma_document_set_short_name_for_display (PlumaDocument * doc, const gchar * name)
Definition at line 1212 of file pluma-document.c.
References PLUMA_IS_DOCUMENT, and _PlumaDocument::priv.
pluma_document_set_uri()
void pluma_document_set_uri (PlumaDocument * doc, const gchar * uri)
Definition at line 1158 of file pluma-document.c.
References NULL, and PLUMA_IS_DOCUMENT.