MATE Desktop Environment: pluma-view.h File Reference
pluma-view.h File Reference
#include <gtk/gtk.h>
#include <pluma/pluma-document.h>
#include <gtksourceview/gtksource.h>
Classes
struct _PlumaView
struct _PlumaViewClass
Macros
#define PLUMA_TYPE_VIEW (pluma_view_get_type ())
#define PLUMA_VIEW(obj)
#define PLUMA_VIEW_CLASS(klass)
#define PLUMA_IS_VIEW(obj)
#define PLUMA_IS_VIEW_CLASS(klass)
#define PLUMA_VIEW_GET_CLASS(obj)
Typedefs
typedef struct _PlumaViewPrivate PlumaViewPrivate
typedef struct _PlumaView PlumaView
typedef struct _PlumaViewClass PlumaViewClass
Functions
GType pluma_view_get_type (void)
GtkWidget * pluma_view_new (PlumaDocument *doc)
void pluma_view_cut_clipboard (PlumaView *view)
void pluma_view_copy_clipboard (PlumaView *view)
void pluma_view_paste_clipboard (PlumaView *view)
void pluma_view_delete_selection (PlumaView *view)
void pluma_view_upper_case_selection (PlumaView *view)
void pluma_view_lower_case_selection (PlumaView *view)
void pluma_view_invert_case_selection (PlumaView *view)
void pluma_view_title_case_selection (PlumaView *view)
void pluma_view_select_all (PlumaView *view)
void pluma_view_scroll_to_cursor (PlumaView *view)
void pluma_override_font (PlumaView *view, const gchar *item, PangoFontDescription *font)
void pluma_view_set_font (PlumaView *view, gboolean def, const gchar *font_name)
Macro Definition Documentation
PLUMA_IS_VIEW
#define PLUMA_IS_VIEW (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE((obj), PLUMA_TYPE_VIEW))
Definition at line 48 of file pluma-view.h.
Referenced by pluma_automatic_spell_checker_attach_view(), pluma_automatic_spell_checker_detach_view(), pluma_print_job_new(), pluma_view_copy_clipboard(), pluma_view_cut_clipboard(), pluma_view_delete_selection(), pluma_view_invert_case_selection(), pluma_view_lower_case_selection(), pluma_view_paste_clipboard(), pluma_view_scroll_to_cursor(), pluma_view_select_all(), pluma_view_set_font(), pluma_view_title_case_selection(), and pluma_view_upper_case_selection().
PLUMA_IS_VIEW_CLASS
#define PLUMA_IS_VIEW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_VIEW))
Definition at line 49 of file pluma-view.h.
PLUMA_TYPE_VIEW
#define PLUMA_TYPE_VIEW (pluma_view_get_type ())
Definition at line 45 of file pluma-view.h.
Referenced by pluma_view_activatable_default_init(), and pluma_view_new().
PLUMA_VIEW
#define PLUMA_VIEW (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST((obj), PLUMA_TYPE_VIEW, PlumaView))
Definition at line 46 of file pluma-view.h.
Referenced by pluma_tab_get_view().
PLUMA_VIEW_CLASS
#define PLUMA_VIEW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST((klass), PLUMA_TYPE_VIEW, PlumaViewClass))
Definition at line 47 of file pluma-view.h.
PLUMA_VIEW_GET_CLASS
#define PLUMA_VIEW_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS((obj), PLUMA_TYPE_VIEW, PlumaViewClass))
Definition at line 50 of file pluma-view.h.
Typedef Documentation
PlumaView
typedef struct _PlumaView PlumaView
Definition at line 58 of file pluma-view.h.
PlumaViewClass
typedef struct _PlumaViewClass PlumaViewClass
Definition at line 71 of file pluma-view.h.
PlumaViewPrivate
typedef struct _PlumaViewPrivate PlumaViewPrivate
Definition at line 53 of file pluma-view.h.
Function Documentation
pluma_override_font()
void pluma_override_font (PlumaView * view, const gchar * item, PangoFontDescription * font)
References item, and level.
pluma_view_copy_clipboard()
void pluma_view_copy_clipboard (PlumaView * view)
Definition at line 741 of file pluma-view.c.
References DEBUG_VIEW, NULL, pluma_debug(), and PLUMA_IS_VIEW.
Referenced by _pluma_cmd_edit_copy().
pluma_view_cut_clipboard()
void pluma_view_cut_clipboard (PlumaView * view)
Definition at line 712 of file pluma-view.c.
References DEBUG_VIEW, FALSE, NULL, pluma_debug(), PLUMA_DOCUMENT, pluma_document_get_readonly(), PLUMA_IS_VIEW, and PLUMA_VIEW_SCROLL_MARGIN.
Referenced by _pluma_cmd_edit_cut().
pluma_view_delete_selection()
void pluma_view_delete_selection (PlumaView * view)
pluma_view_delete_selection: @view: a PlumaView
Deletes the text currently selected in the #GtkTextBuffer associated to the view and scroll to the cursor position.
Definition at line 797 of file pluma-view.c.
References DEBUG_VIEW, FALSE, NULL, pluma_debug(), PLUMA_DOCUMENT, pluma_document_get_readonly(), PLUMA_IS_VIEW, PLUMA_VIEW_SCROLL_MARGIN, and TRUE.
Referenced by _pluma_cmd_edit_delete().
pluma_view_get_type()
GType pluma_view_get_type (void)
pluma_view_invert_case_selection()
void pluma_view_invert_case_selection (PlumaView * view)
Definition at line 860 of file pluma-view.c.
References DEBUG_VIEW, NULL, pluma_debug(), and PLUMA_IS_VIEW.
Referenced by _pluma_cmd_edit_invert_case().
pluma_view_lower_case_selection()
void pluma_view_lower_case_selection (PlumaView * view)
Definition at line 841 of file pluma-view.c.
References DEBUG_VIEW, NULL, pluma_debug(), and PLUMA_IS_VIEW.
Referenced by _pluma_cmd_edit_lower_case().
pluma_view_new()
GtkWidget * pluma_view_new (PlumaDocument * doc)
pluma_view_new: @doc: a PlumaDocument
Creates a new PlumaView object displaying the @doc document. @doc cannot be NULL.
Return value: a new PlumaView
Definition at line 694 of file pluma-view.c.
References DEBUG_VIEW, NULL, pluma_debug_message(), PLUMA_IS_DOCUMENT, and PLUMA_TYPE_VIEW.
pluma_view_paste_clipboard()
void pluma_view_paste_clipboard (PlumaView * view)
Definition at line 761 of file pluma-view.c.
References DEBUG_VIEW, FALSE, NULL, pluma_debug(), PLUMA_DOCUMENT, pluma_document_get_readonly(), PLUMA_IS_VIEW, and PLUMA_VIEW_SCROLL_MARGIN.
Referenced by _pluma_cmd_edit_paste().
pluma_view_scroll_to_cursor()
void pluma_view_scroll_to_cursor (PlumaView * view)
pluma_view_scroll_to_cursor: @view: a PlumaView
Scrolls the @view to the cursor position.
Definition at line 927 of file pluma-view.c.
References DEBUG_VIEW, FALSE, NULL, pluma_debug(), and PLUMA_IS_VIEW.
Referenced by _pluma_cmd_edit_redo(), and _pluma_cmd_edit_undo().
pluma_view_select_all()
void pluma_view_select_all (PlumaView * view)
pluma_view_select_all: @view: a PlumaView
Selects all the text displayed in the @view.
Definition at line 904 of file pluma-view.c.
References DEBUG_VIEW, NULL, pluma_debug(), and PLUMA_IS_VIEW.
Referenced by _pluma_cmd_edit_select_all().
pluma_view_set_font()
void pluma_view_set_font (PlumaView * view, gboolean def, const gchar * font_name)
Definition at line 974 of file pluma-view.c.
References _pluma_settings_get_singleton(), DEBUG_VIEW, NULL, pluma_debug(), PLUMA_IS_VIEW, pluma_settings_get_system_font(), and _PlumaView::priv.
pluma_view_title_case_selection()
void pluma_view_title_case_selection (PlumaView * view)
Definition at line 879 of file pluma-view.c.
References DEBUG_VIEW, NULL, pluma_debug(), and PLUMA_IS_VIEW.
Referenced by _pluma_cmd_edit_title_case().
pluma_view_upper_case_selection()
void pluma_view_upper_case_selection (PlumaView * view)
Definition at line 822 of file pluma-view.c.
References DEBUG_VIEW, NULL, pluma_debug(), and PLUMA_IS_VIEW.
Referenced by _pluma_cmd_edit_upper_case().