MATE Desktop Environment: pluma-encodings.h File Reference
pluma-encodings.h File Reference
#include <glib.h>
#include <glib-object.h>
Macros
#define PLUMA_TYPE_ENCODING (pluma_encoding_get_type ())
Typedefs
typedef struct _PlumaEncoding PlumaEncoding
Functions
GType pluma_encoding_get_type (void)
const PlumaEncoding * pluma_encoding_get_from_charset (const gchar *charset)
const PlumaEncoding * pluma_encoding_get_from_index (gint index)
gchar * pluma_encoding_to_string (const PlumaEncoding *enc)
const gchar * pluma_encoding_get_name (const PlumaEncoding *enc)
const gchar * pluma_encoding_get_charset (const PlumaEncoding *enc)
const PlumaEncoding * pluma_encoding_get_utf8 (void)
const PlumaEncoding * pluma_encoding_get_current (void)
PlumaEncoding * pluma_encoding_copy (const PlumaEncoding *enc)
void pluma_encoding_free (PlumaEncoding *enc)
GSList * _pluma_encoding_strv_to_list (const gchar *const *enc_str)
gchar ** _pluma_encoding_list_to_strv (const GSList *enc)
Macro Definition Documentation
PLUMA_TYPE_ENCODING
#define PLUMA_TYPE_ENCODING (pluma_encoding_get_type ())
Definition at line 42 of file pluma-encodings.h.
Typedef Documentation
PlumaEncoding
typedef struct _PlumaEncoding PlumaEncoding
Definition at line 40 of file pluma-encodings.h.
Function Documentation
_pluma_encoding_list_to_strv()
gchar ** _pluma_encoding_list_to_strv (const GSList * enc)
Definition at line 518 of file pluma-encodings.c.
References charset, FALSE, NULL, and pluma_encoding_get_charset().
_pluma_encoding_strv_to_list()
GSList * _pluma_encoding_strv_to_list (const gchar *const * enc_str)
Definition at line 490 of file pluma-encodings.c.
References charset, NULL, and pluma_encoding_get_from_charset().
pluma_encoding_copy()
PlumaEncoding * pluma_encoding_copy (const PlumaEncoding * enc)
Definition at line 440 of file pluma-encodings.c.
References NULL.
Referenced by pluma_encoding_get_type().
pluma_encoding_free()
void pluma_encoding_free (PlumaEncoding * enc)
Definition at line 448 of file pluma-encodings.c.
References NULL.
Referenced by pluma_encoding_get_type().
pluma_encoding_get_charset()
const gchar * pluma_encoding_get_charset (const PlumaEncoding * enc)
Definition at line 414 of file pluma-encodings.c.
References NULL.
Referenced by _pluma_encoding_list_to_strv().
pluma_encoding_get_current()
const PlumaEncoding * pluma_encoding_get_current (void)
Definition at line 356 of file pluma-encodings.c.
References FALSE, NULL, pluma_encoding_get_from_charset(), and TRUE.
Referenced by pluma_document_loader_get_encoding().
pluma_encoding_get_from_charset()
const PlumaEncoding * pluma_encoding_get_from_charset (const gchar * charset)
Definition at line 302 of file pluma-encodings.c.
References charset, NULL, pluma_encoding_get_utf8(), and PLUMA_ENCODING_LAST.
Referenced by _pluma_encoding_strv_to_list(), pluma_application_set_command_line_options(), and pluma_encoding_get_current().
pluma_encoding_get_from_index()
const PlumaEncoding * pluma_encoding_get_from_index (gint index)
Definition at line 335 of file pluma-encodings.c.
References idx, NULL, and PLUMA_ENCODING_LAST.
pluma_encoding_get_name()
const gchar * pluma_encoding_get_name (const PlumaEncoding * enc)
Definition at line 426 of file pluma-encodings.c.
References _, and NULL.
pluma_encoding_get_type()
GType pluma_encoding_get_type (void)
pluma_encoding_get_type:
Retrieves the GType object which is associated with the PlumaEncoding class.
Return value: the GType associated with PlumaEncoding.
Definition at line 462 of file pluma-encodings.c.
References pluma_encoding_copy(), and pluma_encoding_free().
pluma_encoding_get_utf8()
const PlumaEncoding * pluma_encoding_get_utf8 (void)
Definition at line 348 of file pluma-encodings.c.
Referenced by pluma_encoding_get_from_charset(), and pluma_smart_charset_converter_get_guessed().
pluma_encoding_to_string()
gchar * pluma_encoding_to_string (const PlumaEncoding * enc)
Definition at line 392 of file pluma-encodings.c.
References _, and NULL.
Referenced by _pluma_tab_get_tooltips(), pluma_conversion_error_while_saving_message_area_new(), and pluma_io_loading_error_message_area_new().