MATE Desktop Environment: pluma-session.c File Reference
pluma-session.c File Reference
#include <unistd.h>
#include <string.h>
#include <libxml/tree.h>
#include <libxml/xmlwriter.h>
#include "pluma-session.h"
#include "pluma-debug.h"
#include "pluma-plugins-engine.h"
#include "pluma-metadata-manager.h"
#include "pluma-window.h"
#include "pluma-app.h"
#include "pluma-commands.h"
#include "dialogs/pluma-close-confirmation-dialog.h"
#include "eggsmclient.h"
Macros
#define PLUMA_SESSION_LIST_OF_DOCS_TO_SAVE "pluma-session-list-of-docs-to-save-key"
Functions
void pluma_session_init (void)
gboolean pluma_session_is_restored (void)
gboolean pluma_session_load (void)
Macro Definition Documentation
PLUMA_SESSION_LIST_OF_DOCS_TO_SAVE
#define PLUMA_SESSION_LIST_OF_DOCS_TO_SAVE "pluma-session-list-of-docs-to-save-key"
Definition at line 65 of file pluma-session.c.
Function Documentation
pluma_session_init()
void pluma_session_init (void)
pluma_session_init:
Initializes session management support. This function should be called near the beginning of the program.
Definition at line 407 of file pluma-session.c.
References DEBUG_SESSION, egg_sm_client_get(), NULL, and pluma_debug().
pluma_session_is_restored()
gboolean pluma_session_is_restored (void)
pluma_session_is_restored:
Returns whether this pluma is running from a restarted session.
Return value: TRUE if the session manager restarted us, FALSE otherwise. This should be used to determine whether to pay attention to command line arguments in case the session was not restored.
Definition at line 439 of file pluma-session.c.
References DEBUG_SESSION, egg_sm_client_is_resumed(), FALSE, pluma_debug(), and pluma_debug_message().
pluma_session_load()
gboolean pluma_session_load (void)
pluma_session_load:
Loads the session by fetching the necessary information from the session manager and opening files.
Return value: TRUE if the session was loaded successfully, FALSE otherwise.
Definition at line 579 of file pluma-session.c.
References DEBUG_SESSION, egg_sm_client_get_state_file(), FALSE, NULL, pluma_debug(), and TRUE.