MATE Desktop Environment: pluma-close-confirmation-dialog.h File Reference
pluma-close-confirmation-dialog.h File Reference
#include <glib.h>
#include <gtk/gtk.h>
#include <pluma/pluma-document.h>
Classes
struct _PlumaCloseConfirmationDialog
struct _PlumaCloseConfirmationDialogClass
Macros
#define PLUMA_TYPE_CLOSE_CONFIRMATION_DIALOG (pluma_close_confirmation_dialog_get_type ())
#define PLUMA_CLOSE_CONFIRMATION_DIALOG(obj)
#define PLUMA_CLOSE_CONFIRMATION_DIALOG_CLASS(klass)
#define PLUMA_IS_CLOSE_CONFIRMATION_DIALOG(obj)
#define PLUMA_IS_CLOSE_CONFIRMATION_DIALOG_CLASS(klass)
#define PLUMA_CLOSE_CONFIRMATION_DIALOG_GET_CLASS(obj)
Typedefs
typedef struct _PlumaCloseConfirmationDialog PlumaCloseConfirmationDialog
typedef struct _PlumaCloseConfirmationDialogClass PlumaCloseConfirmationDialogClass
typedef struct _PlumaCloseConfirmationDialogPrivate PlumaCloseConfirmationDialogPrivate
Functions
GType pluma_close_confirmation_dialog_get_type (void)
GtkWidget * pluma_close_confirmation_dialog_new (GtkWindow *parent, GList *unsaved_documents, gboolean logout_mode)
GtkWidget * pluma_close_confirmation_dialog_new_single (GtkWindow *parent, PlumaDocument *doc, gboolean logout_mode)
const GList * pluma_close_confirmation_dialog_get_unsaved_documents (PlumaCloseConfirmationDialog *dlg)
GList * pluma_close_confirmation_dialog_get_selected_documents (PlumaCloseConfirmationDialog *dlg)
Macro Definition Documentation
PLUMA_CLOSE_CONFIRMATION_DIALOG
#define PLUMA_CLOSE_CONFIRMATION_DIALOG (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_CLOSE_CONFIRMATION_DIALOG, PlumaCloseConfirmationDialog))
Definition at line 39 of file pluma-close-confirmation-dialog.h.
PLUMA_CLOSE_CONFIRMATION_DIALOG_CLASS
#define PLUMA_CLOSE_CONFIRMATION_DIALOG_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), PLUMA_TYPE_CLOSE_CONFIRMATION_DIALOG, PlumaCloseConfirmationDialogClass))
Definition at line 40 of file pluma-close-confirmation-dialog.h.
PLUMA_CLOSE_CONFIRMATION_DIALOG_GET_CLASS
#define PLUMA_CLOSE_CONFIRMATION_DIALOG_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj),PLUMA_TYPE_CLOSE_CONFIRMATION_DIALOG, PlumaCloseConfirmationDialogClass))
Definition at line 43 of file pluma-close-confirmation-dialog.h.
PLUMA_IS_CLOSE_CONFIRMATION_DIALOG
#define PLUMA_IS_CLOSE_CONFIRMATION_DIALOG (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLUMA_TYPE_CLOSE_CONFIRMATION_DIALOG))
Definition at line 41 of file pluma-close-confirmation-dialog.h.
Referenced by pluma_close_confirmation_dialog_get_selected_documents(), and pluma_close_confirmation_dialog_get_unsaved_documents().
PLUMA_IS_CLOSE_CONFIRMATION_DIALOG_CLASS
#define PLUMA_IS_CLOSE_CONFIRMATION_DIALOG_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_CLOSE_CONFIRMATION_DIALOG))
Definition at line 42 of file pluma-close-confirmation-dialog.h.
PLUMA_TYPE_CLOSE_CONFIRMATION_DIALOG
#define PLUMA_TYPE_CLOSE_CONFIRMATION_DIALOG (pluma_close_confirmation_dialog_get_type ())
Definition at line 38 of file pluma-close-confirmation-dialog.h.
Referenced by pluma_close_confirmation_dialog_new().
Typedef Documentation
PlumaCloseConfirmationDialog
typedef struct _PlumaCloseConfirmationDialog PlumaCloseConfirmationDialog
Definition at line 45 of file pluma-close-confirmation-dialog.h.
PlumaCloseConfirmationDialogClass
typedef struct _PlumaCloseConfirmationDialogClass PlumaCloseConfirmationDialogClass
Definition at line 46 of file pluma-close-confirmation-dialog.h.
PlumaCloseConfirmationDialogPrivate
typedef struct _PlumaCloseConfirmationDialogPrivate PlumaCloseConfirmationDialogPrivate
Definition at line 47 of file pluma-close-confirmation-dialog.h.
Function Documentation
pluma_close_confirmation_dialog_get_selected_documents()
GList * pluma_close_confirmation_dialog_get_selected_documents (PlumaCloseConfirmationDialog * dlg)
Definition at line 352 of file pluma-close-confirmation-dialog.c.
References NULL, PLUMA_IS_CLOSE_CONFIRMATION_DIALOG, and _PlumaCloseConfirmationDialog::priv.
pluma_close_confirmation_dialog_get_type()
GType pluma_close_confirmation_dialog_get_type (void)
pluma_close_confirmation_dialog_get_unsaved_documents()
const GList * pluma_close_confirmation_dialog_get_unsaved_documents (PlumaCloseConfirmationDialog * dlg)
Definition at line 823 of file pluma-close-confirmation-dialog.c.
References NULL, PLUMA_IS_CLOSE_CONFIRMATION_DIALOG, and _PlumaCloseConfirmationDialog::priv.
pluma_close_confirmation_dialog_new()
GtkWidget * pluma_close_confirmation_dialog_new (GtkWindow * parent, GList * unsaved_documents, gboolean logout_mode)
Definition at line 360 of file pluma-close-confirmation-dialog.c.
References NULL, PLUMA_TYPE_CLOSE_CONFIRMATION_DIALOG, PLUMA_WINDOW, and pluma_window_get_group().
Referenced by pluma_close_confirmation_dialog_new_single().
pluma_close_confirmation_dialog_new_single()
GtkWidget * pluma_close_confirmation_dialog_new_single (GtkWindow * parent, PlumaDocument * doc, gboolean logout_mode)
Definition at line 385 of file pluma-close-confirmation-dialog.c.
References NULL, and pluma_close_confirmation_dialog_new().