MATE Desktop Environment: pluma-file-browser-widget.c File Reference
pluma-file-browser-widget.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <string.h>
#include <glib.h>
#include <glib/gi18n-lib.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <pluma/pluma-utils.h>
#include "pluma-file-browser-utils.h"
#include "pluma-file-browser-error.h"
#include "pluma-file-browser-widget.h"
#include "pluma-file-browser-view.h"
#include "pluma-file-browser-store.h"
#include "pluma-file-bookmarks-store.h"
#include "pluma-file-browser-enum-types.h"
Macros
#define XML_UI_FILE "pluma-file-browser-widget-ui.xml"
#define LOCATION_DATA_KEY "pluma-file-browser-widget-location"
Typedefs
typedef struct _SignalNode SignalNode
Enumerations
enum {
BOOKMARKS_ID , SEPARATOR_CUSTOM_ID , SEPARATOR_ID , PATH_ID ,
NUM_DEFAULT_IDS
}
enum {
COLUMN_INDENT , COLUMN_ICON , COLUMN_NAME , COLUMN_FILE ,
COLUMN_ID , N_COLUMNS
}
enum { PROP_0 , PROP_FILTER_PATTERN , PROP_ENABLE_DELETE }
enum {
URI_ACTIVATED , ERROR , CONFIRM_DELETE , CONFIRM_NO_TRASH ,
NUM_SIGNALS
}
Functions
G_DEFINE_DYNAMIC_TYPE_EXTENDED (PlumaFileBrowserWidget, pluma_file_browser_widget, GTK_TYPE_BOX, 0, G_ADD_PRIVATE_DYNAMIC(PlumaFileBrowserWidget))
GtkWidget * pluma_file_browser_widget_new (const gchar *data_dir)
void pluma_file_browser_widget_show_bookmarks (PlumaFileBrowserWidget *obj)
void pluma_file_browser_widget_show_files (PlumaFileBrowserWidget *obj)
void pluma_file_browser_widget_set_root_and_virtual_root (PlumaFileBrowserWidget *obj, gchar const *root, gchar const *virtual_root)
void pluma_file_browser_widget_set_root (PlumaFileBrowserWidget *obj, gchar const *root, gboolean virtual_root)
PlumaFileBrowserStore * pluma_file_browser_widget_get_browser_store (PlumaFileBrowserWidget *obj)
PlumaFileBookmarksStore * pluma_file_browser_widget_get_bookmarks_store (PlumaFileBrowserWidget *obj)
PlumaFileBrowserView * pluma_file_browser_widget_get_browser_view (PlumaFileBrowserWidget *obj)
GtkUIManager * pluma_file_browser_widget_get_ui_manager (PlumaFileBrowserWidget *obj)
GtkWidget * pluma_file_browser_widget_get_filter_entry (PlumaFileBrowserWidget *obj)
gulong pluma_file_browser_widget_add_filter (PlumaFileBrowserWidget *obj, PlumaFileBrowserWidgetFilterFunc func, gpointer user_data, GDestroyNotify notify)
void pluma_file_browser_widget_remove_filter (PlumaFileBrowserWidget *obj, gulong id)
void pluma_file_browser_widget_set_filter_pattern (PlumaFileBrowserWidget *obj, gchar const *pattern)
gboolean pluma_file_browser_widget_get_selected_directory (PlumaFileBrowserWidget *obj, GtkTreeIter *iter)
void pluma_file_browser_widget_refresh (PlumaFileBrowserWidget *obj)
void pluma_file_browser_widget_history_back (PlumaFileBrowserWidget *obj)
void pluma_file_browser_widget_history_forward (PlumaFileBrowserWidget *obj)
void _pluma_file_browser_widget_register_type (GTypeModule *type_module)
Macro Definition Documentation
LOCATION_DATA_KEY
#define LOCATION_DATA_KEY "pluma-file-browser-widget-location"
Definition at line 46 of file pluma-file-browser-widget.c.
XML_UI_FILE
#define XML_UI_FILE "pluma-file-browser-widget-ui.xml"
Definition at line 45 of file pluma-file-browser-widget.c.
Typedef Documentation
SignalNode
typedef struct _SignalNode SignalNode
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_FILTER_PATTERN
PROP_ENABLE_DELETE
Definition at line 68 of file pluma-file-browser-widget.c.
anonymous enum
anonymous enum
Enumerator
BOOKMARKS_ID
SEPARATOR_CUSTOM_ID
SEPARATOR_ID
PATH_ID
NUM_DEFAULT_IDS
Definition at line 48 of file pluma-file-browser-widget.c.
anonymous enum
anonymous enum
Enumerator
COLUMN_INDENT
COLUMN_ICON
COLUMN_NAME
COLUMN_FILE
COLUMN_ID
N_COLUMNS
Definition at line 57 of file pluma-file-browser-widget.c.
anonymous enum
anonymous enum
Enumerator
URI_ACTIVATED
ERROR
CONFIRM_DELETE
CONFIRM_NO_TRASH
NUM_SIGNALS
Definition at line 77 of file pluma-file-browser-widget.c.
Function Documentation
_pluma_file_browser_widget_register_type()
void _pluma_file_browser_widget_register_type (GTypeModule * type_module)
Definition at line 3160 of file pluma-file-browser-widget.c.
G_DEFINE_DYNAMIC_TYPE_EXTENDED()
G_DEFINE_DYNAMIC_TYPE_EXTENDED (PlumaFileBrowserWidget , pluma_file_browser_widget , GTK_TYPE_BOX , 0 , G_ADD_PRIVATE_DYNAMIC(PlumaFileBrowserWidget))
Definition at line 234 of file pluma-file-browser-widget.c.
References data, item, and NULL.
pluma_file_browser_widget_add_filter()
gulong pluma_file_browser_widget_add_filter (PlumaFileBrowserWidget * obj, PlumaFileBrowserWidgetFilterFunc func, gpointer user_data, GDestroyNotify notify)
Definition at line 1940 of file pluma-file-browser-widget.c.
References PLUMA_FILE_BROWSER_STORE, pluma_file_browser_store_refilter(), PLUMA_IS_FILE_BROWSER_STORE, _PlumaFileBrowserWidget::priv, and user_data.
pluma_file_browser_widget_get_bookmarks_store()
PlumaFileBookmarksStore * pluma_file_browser_widget_get_bookmarks_store (PlumaFileBrowserWidget * obj)
Definition at line 1916 of file pluma-file-browser-widget.c.
References _PlumaFileBrowserWidget::priv.
pluma_file_browser_widget_get_browser_store()
PlumaFileBrowserStore * pluma_file_browser_widget_get_browser_store (PlumaFileBrowserWidget * obj)
Definition at line 1910 of file pluma-file-browser-widget.c.
References _PlumaFileBrowserWidget::priv.
pluma_file_browser_widget_get_browser_view()
PlumaFileBrowserView * pluma_file_browser_widget_get_browser_view (PlumaFileBrowserWidget * obj)
Definition at line 1922 of file pluma-file-browser-widget.c.
References _PlumaFileBrowserWidget::priv.
pluma_file_browser_widget_get_filter_entry()
GtkWidget * pluma_file_browser_widget_get_filter_entry (PlumaFileBrowserWidget * obj)
Definition at line 1934 of file pluma-file-browser-widget.c.
References _PlumaFileBrowserWidget::priv.
pluma_file_browser_widget_get_selected_directory()
gboolean pluma_file_browser_widget_get_selected_directory (PlumaFileBrowserWidget * obj, GtkTreeIter * iter)
Definition at line 1993 of file pluma-file-browser-widget.c.
References FALSE, FILE_IS_DIR, PLUMA_FILE_BROWSER_STORE, PLUMA_FILE_BROWSER_STORE_COLUMN_FLAGS, pluma_file_browser_store_get_iter_virtual_root(), PLUMA_IS_FILE_BROWSER_STORE, _PlumaFileBrowserWidget::priv, and TRUE.
pluma_file_browser_widget_get_ui_manager()
GtkUIManager * pluma_file_browser_widget_get_ui_manager (PlumaFileBrowserWidget * obj)
Definition at line 1928 of file pluma-file-browser-widget.c.
References _PlumaFileBrowserWidget::priv.
pluma_file_browser_widget_history_back()
void pluma_file_browser_widget_history_back (PlumaFileBrowserWidget * obj)
Definition at line 2363 of file pluma-file-browser-widget.c.
References _PlumaFileBrowserWidget::priv, and TRUE.
pluma_file_browser_widget_history_forward()
void pluma_file_browser_widget_history_forward (PlumaFileBrowserWidget * obj)
Definition at line 2377 of file pluma-file-browser-widget.c.
References FALSE, and _PlumaFileBrowserWidget::priv.
pluma_file_browser_widget_new()
GtkWidget * pluma_file_browser_widget_new (const gchar * data_dir)
Definition at line 1807 of file pluma-file-browser-widget.c.
References NULL, pluma_file_browser_widget_show_bookmarks(), and PLUMA_TYPE_FILE_BROWSER_WIDGET.
pluma_file_browser_widget_refresh()
void pluma_file_browser_widget_refresh (PlumaFileBrowserWidget * obj)
Definition at line 2345 of file pluma-file-browser-widget.c.
References PLUMA_FILE_BOOKMARKS_STORE, pluma_file_bookmarks_store_refresh(), PLUMA_FILE_BROWSER_STORE, pluma_file_browser_store_refresh(), PLUMA_IS_FILE_BOOKMARKS_STORE, PLUMA_IS_FILE_BROWSER_STORE, and _PlumaFileBrowserWidget::priv.
pluma_file_browser_widget_remove_filter()
void pluma_file_browser_widget_remove_filter (PlumaFileBrowserWidget * obj, gulong id)
Definition at line 1961 of file pluma-file-browser-widget.c.
References item, and _PlumaFileBrowserWidget::priv.
pluma_file_browser_widget_set_filter_pattern()
void pluma_file_browser_widget_set_filter_pattern (PlumaFileBrowserWidget * obj, gchar const * pattern)
Definition at line 1986 of file pluma-file-browser-widget.c.
References TRUE.
pluma_file_browser_widget_set_root()
void pluma_file_browser_widget_set_root (PlumaFileBrowserWidget * obj, gchar const * root, gboolean virtual_root)
Definition at line 1878 of file pluma-file-browser-widget.c.
References NULL, and pluma_file_browser_widget_set_root_and_virtual_root().
pluma_file_browser_widget_set_root_and_virtual_root()
void pluma_file_browser_widget_set_root_and_virtual_root (PlumaFileBrowserWidget * obj, gchar const * root, gchar const * virtual_root)
Definition at line 1858 of file pluma-file-browser-widget.c.
References PLUMA_FILE_BROWSER_STORE_RESULT_NO_CHANGE, pluma_file_browser_store_set_root_and_virtual_root(), _PlumaFileBrowserWidget::priv, and TRUE.
Referenced by pluma_file_browser_widget_set_root().
pluma_file_browser_widget_show_bookmarks()
void pluma_file_browser_widget_show_bookmarks (PlumaFileBrowserWidget * obj)
Definition at line 1823 of file pluma-file-browser-widget.c.
References BOOKMARKS_ID, FALSE, pluma_file_browser_view_set_model(), and _PlumaFileBrowserWidget::priv.
Referenced by pluma_file_browser_widget_new().
pluma_file_browser_widget_show_files()
void pluma_file_browser_widget_show_files (PlumaFileBrowserWidget * obj)
Definition at line 1852 of file pluma-file-browser-widget.c.
References TRUE.