MATE Desktop Environment: pluma-settings.c File Reference
pluma-settings.c File Reference
#include <string.h>
#include "pluma-settings.h"
#include "pluma-debug.h"
#include "pluma-view.h"
#include "pluma-window.h"
#include "pluma-style-scheme-manager.h"
#include "pluma-window-private.h"
Macros
#define PLUMA_SETTINGS_LOCKDOWN_COMMAND_LINE "disable-command-line"
#define PLUMA_SETTINGS_LOCKDOWN_PRINTING "disable-printing"
#define PLUMA_SETTINGS_LOCKDOWN_PRINT_SETUP "disable-print-setup"
#define PLUMA_SETTINGS_LOCKDOWN_SAVE_TO_DISK "disable-save-to-disk"
#define PLUMA_SETTINGS_SYSTEM_FONT "monospace-font-name"
Functions
PlumaSettings * _pluma_settings_get_singleton (void)
void pluma_settings_unref_singleton (void)
PlumaLockdownMask pluma_settings_get_lockdown (PlumaSettings *self)
gchar * pluma_settings_get_system_font (PlumaSettings *self)
PlumaToolbarSetting pluma_settings_get_toolbar_style (PlumaSettings *self)
GtkSourceSmartHomeEndType pluma_settings_get_smart_home_end (PlumaSettings *self)
GtkWrapMode pluma_settings_get_wrap_mode (GSettings *settings, const gchar *key)
void pluma_settings_set_wrap_mode (GSettings *settings, const gchar *key, GtkWrapMode mode)
GSList * pluma_settings_get_list (GSettings *settings, const gchar *key)
void pluma_settings_set_list (GSettings *settings, const gchar *key, GSList *list)
GSList * pluma_settings_get_writable_vfs_schemes (GSettings *settings)
Macro Definition Documentation
PLUMA_SETTINGS_LOCKDOWN_COMMAND_LINE
#define PLUMA_SETTINGS_LOCKDOWN_COMMAND_LINE "disable-command-line"
Definition at line 34 of file pluma-settings.c.
Referenced by pluma_settings_get_lockdown().
PLUMA_SETTINGS_LOCKDOWN_PRINT_SETUP
#define PLUMA_SETTINGS_LOCKDOWN_PRINT_SETUP "disable-print-setup"
Definition at line 36 of file pluma-settings.c.
Referenced by pluma_settings_get_lockdown().
PLUMA_SETTINGS_LOCKDOWN_PRINTING
#define PLUMA_SETTINGS_LOCKDOWN_PRINTING "disable-printing"
Definition at line 35 of file pluma-settings.c.
Referenced by pluma_settings_get_lockdown().
PLUMA_SETTINGS_LOCKDOWN_SAVE_TO_DISK
#define PLUMA_SETTINGS_LOCKDOWN_SAVE_TO_DISK "disable-save-to-disk"
Definition at line 37 of file pluma-settings.c.
Referenced by pluma_settings_get_lockdown().
PLUMA_SETTINGS_SYSTEM_FONT
#define PLUMA_SETTINGS_SYSTEM_FONT "monospace-font-name"
Definition at line 39 of file pluma-settings.c.
Function Documentation
_pluma_settings_get_singleton()
PlumaSettings * _pluma_settings_get_singleton (void)
Definition at line 871 of file pluma-settings.c.
References NULL, and PLUMA_TYPE_SETTINGS.
Referenced by pluma_view_set_font().
pluma_settings_get_list()
GSList * pluma_settings_get_list (GSettings * settings, const gchar * key)
Definition at line 1066 of file pluma-settings.c.
References key, and NULL.
Referenced by pluma_settings_get_writable_vfs_schemes().
pluma_settings_get_lockdown()
PlumaLockdownMask pluma_settings_get_lockdown (PlumaSettings * self)
Definition at line 896 of file pluma-settings.c.
References PLUMA_LOCKDOWN_COMMAND_LINE, PLUMA_LOCKDOWN_PRINT_SETUP, PLUMA_LOCKDOWN_PRINTING, PLUMA_LOCKDOWN_SAVE_TO_DISK, PLUMA_SETTINGS_LOCKDOWN_COMMAND_LINE, PLUMA_SETTINGS_LOCKDOWN_PRINT_SETUP, PLUMA_SETTINGS_LOCKDOWN_PRINTING, PLUMA_SETTINGS_LOCKDOWN_SAVE_TO_DISK, and _PlumaSettings::priv.
pluma_settings_get_smart_home_end()
GtkSourceSmartHomeEndType pluma_settings_get_smart_home_end (PlumaSettings * self)
Definition at line 972 of file pluma-settings.c.
References NULL, PLUMA_IS_SETTINGS, and _PlumaSettings::priv.
pluma_settings_get_system_font()
gchar * pluma_settings_get_system_font (PlumaSettings * self)
Definition at line 926 of file pluma-settings.c.
References NULL, PLUMA_IS_SETTINGS, and _PlumaSettings::priv.
Referenced by pluma_view_set_font().
pluma_settings_get_toolbar_style()
PlumaToolbarSetting pluma_settings_get_toolbar_style (PlumaSettings * self)
Definition at line 939 of file pluma-settings.c.
References NULL, PLUMA_IS_SETTINGS, PLUMA_TOOLBAR_ICONS, PLUMA_TOOLBAR_ICONS_AND_TEXT, PLUMA_TOOLBAR_ICONS_BOTH_HORIZ, PLUMA_TOOLBAR_SYSTEM, and _PlumaSettings::priv.
pluma_settings_get_wrap_mode()
GtkWrapMode pluma_settings_get_wrap_mode (GSettings * settings, const gchar * key)
Definition at line 1020 of file pluma-settings.c.
References key, and NULL.
pluma_settings_get_writable_vfs_schemes()
GSList * pluma_settings_get_writable_vfs_schemes (GSettings * settings)
Definition at line 1095 of file pluma-settings.c.
References DEBUG_PREFS, pluma_debug(), pluma_debug_message(), pluma_settings_get_list(), and PLUMA_SETTINGS_WRITABLE_VFS_SCHEMES.
Referenced by pluma_utils_uri_has_writable_scheme().
pluma_settings_set_list()
void pluma_settings_set_list (GSettings * settings, const gchar * key, GSList * list)
Definition at line 1082 of file pluma-settings.c.
References key, and TRUE.
pluma_settings_set_wrap_mode()
void pluma_settings_set_wrap_mode (GSettings * settings, const gchar * key, GtkWrapMode mode)
Definition at line 1049 of file pluma-settings.c.
References key, and NULL.
pluma_settings_unref_singleton()
void pluma_settings_unref_singleton (void)
Definition at line 882 of file pluma-settings.c.
References NULL.