MATE Desktop Environment: pluma-view.c File Reference
pluma-view.c File Reference
#include <string.h>
#include <stdlib.h>
#include <gtk/gtk.h>
#include <gdk/gdkkeysyms.h>
#include <libpeas/peas-extension-set.h>
#include <glib/gi18n.h>
#include "pluma-view.h"
#include "pluma-view-activatable.h"
#include "pluma-plugins-engine.h"
#include "pluma-debug.h"
#include "pluma-pango.h"
#include "pluma-utils.h"
#include "pluma-settings.h"
Macros
#define PLUMA_VIEW_SCROLL_MARGIN 0.02
#define PLUMA_VIEW_SEARCH_DIALOG_TIMEOUT (30*1000) /* 30 seconds */
#define MIN_SEARCH_COMPLETION_KEY_LEN 3
Enumerations
enum SearchMode { GOTO_LINE , SEARCH }
enum { TARGET_URI_LIST = 100 }
enum {
START_INTERACTIVE_SEARCH , START_INTERACTIVE_GOTO_LINE , RESET_SEARCHED_TEXT , DROP_URIS ,
LAST_SIGNAL
}
enum PlumaSearchEntryState { PLUMA_SEARCH_ENTRY_NORMAL , PLUMA_SEARCH_ENTRY_NOT_FOUND }
Functions
GtkWidget * pluma_view_new (PlumaDocument *doc)
void pluma_view_cut_clipboard (PlumaView *view)
void pluma_view_copy_clipboard (PlumaView *view)
void pluma_view_paste_clipboard (PlumaView *view)
void pluma_view_delete_selection (PlumaView *view)
void pluma_view_upper_case_selection (PlumaView *view)
void pluma_view_lower_case_selection (PlumaView *view)
void pluma_view_invert_case_selection (PlumaView *view)
void pluma_view_title_case_selection (PlumaView *view)
void pluma_view_select_all (PlumaView *view)
void pluma_view_scroll_to_cursor (PlumaView *view)
void pluma_view_set_font (PlumaView *view, gboolean def, const gchar *font_name)
Variables
GtkListStore * search_completion_model = NULL
Macro Definition Documentation
MIN_SEARCH_COMPLETION_KEY_LEN
#define MIN_SEARCH_COMPLETION_KEY_LEN 3
Definition at line 58 of file pluma-view.c.
PLUMA_VIEW_SCROLL_MARGIN
#define PLUMA_VIEW_SCROLL_MARGIN 0.02
Definition at line 55 of file pluma-view.c.
Referenced by pluma_view_cut_clipboard(), pluma_view_delete_selection(), and pluma_view_paste_clipboard().
PLUMA_VIEW_SEARCH_DIALOG_TIMEOUT
#define PLUMA_VIEW_SEARCH_DIALOG_TIMEOUT (30*1000) /* 30 seconds */
Definition at line 56 of file pluma-view.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TARGET_URI_LIST
Definition at line 69 of file pluma-view.c.
anonymous enum
anonymous enum
Enumerator
START_INTERACTIVE_SEARCH
START_INTERACTIVE_GOTO_LINE
RESET_SEARCHED_TEXT
DROP_URIS
LAST_SIGNAL
Definition at line 182 of file pluma-view.c.
PlumaSearchEntryState
enum PlumaSearchEntryState
Enumerator
PLUMA_SEARCH_ENTRY_NORMAL
PLUMA_SEARCH_ENTRY_NOT_FOUND
Definition at line 193 of file pluma-view.c.
SearchMode
enum SearchMode
Enumerator
GOTO_LINE
SEARCH
Definition at line 63 of file pluma-view.c.
Function Documentation
pluma_view_copy_clipboard()
void pluma_view_copy_clipboard (PlumaView * view)
Definition at line 741 of file pluma-view.c.
References DEBUG_VIEW, NULL, pluma_debug(), and PLUMA_IS_VIEW.
Referenced by _pluma_cmd_edit_copy().
pluma_view_cut_clipboard()
void pluma_view_cut_clipboard (PlumaView * view)
Definition at line 712 of file pluma-view.c.
References DEBUG_VIEW, FALSE, NULL, pluma_debug(), PLUMA_DOCUMENT, pluma_document_get_readonly(), PLUMA_IS_VIEW, and PLUMA_VIEW_SCROLL_MARGIN.
Referenced by _pluma_cmd_edit_cut().
pluma_view_delete_selection()
void pluma_view_delete_selection (PlumaView * view)
pluma_view_delete_selection: @view: a PlumaView
Deletes the text currently selected in the #GtkTextBuffer associated to the view and scroll to the cursor position.
Definition at line 797 of file pluma-view.c.
References DEBUG_VIEW, FALSE, NULL, pluma_debug(), PLUMA_DOCUMENT, pluma_document_get_readonly(), PLUMA_IS_VIEW, PLUMA_VIEW_SCROLL_MARGIN, and TRUE.
Referenced by _pluma_cmd_edit_delete().
pluma_view_invert_case_selection()
void pluma_view_invert_case_selection (PlumaView * view)
Definition at line 860 of file pluma-view.c.
References DEBUG_VIEW, NULL, pluma_debug(), and PLUMA_IS_VIEW.
Referenced by _pluma_cmd_edit_invert_case().
pluma_view_lower_case_selection()
void pluma_view_lower_case_selection (PlumaView * view)
Definition at line 841 of file pluma-view.c.
References DEBUG_VIEW, NULL, pluma_debug(), and PLUMA_IS_VIEW.
Referenced by _pluma_cmd_edit_lower_case().
pluma_view_new()
GtkWidget * pluma_view_new (PlumaDocument * doc)
pluma_view_new: @doc: a PlumaDocument
Creates a new PlumaView object displaying the @doc document. @doc cannot be NULL.
Return value: a new PlumaView
Definition at line 694 of file pluma-view.c.
References DEBUG_VIEW, NULL, pluma_debug_message(), PLUMA_IS_DOCUMENT, and PLUMA_TYPE_VIEW.
pluma_view_paste_clipboard()
void pluma_view_paste_clipboard (PlumaView * view)
Definition at line 761 of file pluma-view.c.
References DEBUG_VIEW, FALSE, NULL, pluma_debug(), PLUMA_DOCUMENT, pluma_document_get_readonly(), PLUMA_IS_VIEW, and PLUMA_VIEW_SCROLL_MARGIN.
Referenced by _pluma_cmd_edit_paste().
pluma_view_scroll_to_cursor()
void pluma_view_scroll_to_cursor (PlumaView * view)
pluma_view_scroll_to_cursor: @view: a PlumaView
Scrolls the @view to the cursor position.
Definition at line 927 of file pluma-view.c.
References DEBUG_VIEW, FALSE, NULL, pluma_debug(), and PLUMA_IS_VIEW.
Referenced by _pluma_cmd_edit_redo(), and _pluma_cmd_edit_undo().
pluma_view_select_all()
void pluma_view_select_all (PlumaView * view)
pluma_view_select_all: @view: a PlumaView
Selects all the text displayed in the @view.
Definition at line 904 of file pluma-view.c.
References DEBUG_VIEW, NULL, pluma_debug(), and PLUMA_IS_VIEW.
Referenced by _pluma_cmd_edit_select_all().
pluma_view_set_font()
void pluma_view_set_font (PlumaView * view, gboolean def, const gchar * font_name)
Definition at line 974 of file pluma-view.c.
References _pluma_settings_get_singleton(), DEBUG_VIEW, NULL, pluma_debug(), PLUMA_IS_VIEW, pluma_settings_get_system_font(), and _PlumaView::priv.
pluma_view_title_case_selection()
void pluma_view_title_case_selection (PlumaView * view)
Definition at line 879 of file pluma-view.c.
References DEBUG_VIEW, NULL, pluma_debug(), and PLUMA_IS_VIEW.
Referenced by _pluma_cmd_edit_title_case().
pluma_view_upper_case_selection()
void pluma_view_upper_case_selection (PlumaView * view)
Definition at line 822 of file pluma-view.c.
References DEBUG_VIEW, NULL, pluma_debug(), and PLUMA_IS_VIEW.
Referenced by _pluma_cmd_edit_upper_case().
Variable Documentation
search_completion_model
GtkListStore* search_completion_model = NULL
Definition at line 113 of file pluma-view.c.