MATE Desktop Environment: pluma-app.c File Reference
pluma-app.c File Reference
#include <string.h>
#include <unistd.h>
#include <glib/gi18n.h>
#include <libpeas/peas-extension-set.h>
#include <gdk/gdk.h>
#include <gdk/gdkx.h>
#include "pluma-app.h"
#include "pluma-commands.h"
#include "pluma-notebook.h"
#include "pluma-debug.h"
#include "pluma-utils.h"
#include "pluma-enum-types.h"
#include "pluma-dirs.h"
#include "pluma-settings.h"
#include "pluma-app-activatable.h"
#include "pluma-plugins-engine.h"
Macros
#define PLUMA_PAGE_SETUP_FILE "pluma-page-setup"
#define PLUMA_PRINT_SETTINGS_FILE "pluma-print-settings"
Enumerations
enum { PROP_0 , PROP_LOCKDOWN }
Functions
PlumaApp * pluma_app_get_default (void)
PlumaWindow * pluma_app_create_window (PlumaApp *app, GdkScreen *screen)
PlumaWindow * _pluma_app_restore_window (PlumaApp *app, const gchar *role)
const GList * pluma_app_get_windows (PlumaApp *app)
PlumaWindow * pluma_app_get_active_window (PlumaApp *app)
PlumaWindow * _pluma_app_get_window_in_viewport (PlumaApp *app, GdkScreen *screen, gint workspace, gint viewport_x, gint viewport_y)
GList * pluma_app_get_documents (PlumaApp *app)
GList * pluma_app_get_views (PlumaApp *app)
PlumaLockdownMask pluma_app_get_lockdown (PlumaApp *app)
void _pluma_app_set_lockdown (PlumaApp *app, PlumaLockdownMask lockdown)
void _pluma_app_set_lockdown_bit (PlumaApp *app, PlumaLockdownMask bit, gboolean value)
GtkPageSetup * _pluma_app_get_default_page_setup (PlumaApp *app)
void _pluma_app_set_default_page_setup (PlumaApp *app, GtkPageSetup *page_setup)
GtkPrintSettings * _pluma_app_get_default_print_settings (PlumaApp *app)
void _pluma_app_set_default_print_settings (PlumaApp *app, GtkPrintSettings *settings)
Macro Definition Documentation
PLUMA_PAGE_SETUP_FILE
#define PLUMA_PAGE_SETUP_FILE "pluma-page-setup"
Definition at line 55 of file pluma-app.c.
PLUMA_PRINT_SETTINGS_FILE
#define PLUMA_PRINT_SETTINGS_FILE "pluma-print-settings"
Definition at line 56 of file pluma-app.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_LOCKDOWN
Definition at line 59 of file pluma-app.c.
Function Documentation
_pluma_app_get_default_page_setup()
GtkPageSetup * _pluma_app_get_default_page_setup (PlumaApp * app)
Definition at line 887 of file pluma-app.c.
References NULL, PLUMA_IS_APP, and _PlumaApp::priv.
_pluma_app_get_default_print_settings()
GtkPrintSettings * _pluma_app_get_default_print_settings (PlumaApp * app)
Definition at line 912 of file pluma-app.c.
References NULL, PLUMA_IS_APP, and _PlumaApp::priv.
_pluma_app_get_window_in_viewport()
PlumaWindow * _pluma_app_get_window_in_viewport (PlumaApp * app, GdkScreen * screen, gint workspace, gint viewport_x, gint viewport_y)
_pluma_app_get_window_in_viewport: @app: the PlumaApp @screen: the #GdkScreen @workspace: the workspace number @viewport_x: the viewport horizontal origin @viewport_y: the viewport vertical origin
Since a workspace can be larger than the screen, it is divided into several equal parts called viewports. This function retrives the PlumaWindow in the given viewport of the given workspace.
Return value: the PlumaWindow in the given viewport of the given workspace.
Definition at line 738 of file pluma-app.c.
References NULL, pluma_app_create_window(), PLUMA_IS_APP, PLUMA_IS_WINDOW, and _PlumaApp::priv.
_pluma_app_restore_window()
PlumaWindow * _pluma_app_restore_window (PlumaApp * app, const gchar * role)
Definition at line 627 of file pluma-app.c.
References FALSE.
_pluma_app_set_default_page_setup()
void _pluma_app_set_default_page_setup (PlumaApp * app, GtkPageSetup * page_setup)
Definition at line 898 of file pluma-app.c.
References NULL, PLUMA_IS_APP, and _PlumaApp::priv.
_pluma_app_set_default_print_settings()
void _pluma_app_set_default_print_settings (PlumaApp * app, GtkPrintSettings * settings)
Definition at line 923 of file pluma-app.c.
References NULL, PLUMA_IS_APP, and _PlumaApp::priv.
_pluma_app_set_lockdown()
void _pluma_app_set_lockdown (PlumaApp * app, PlumaLockdownMask lockdown)
Definition at line 860 of file pluma-app.c.
References PLUMA_IS_APP, and _PlumaApp::priv.
_pluma_app_set_lockdown_bit()
void _pluma_app_set_lockdown_bit (PlumaApp * app, PlumaLockdownMask bit, gboolean value)
Definition at line 871 of file pluma-app.c.
References PLUMA_IS_APP, and _PlumaApp::priv.
pluma_app_create_window()
PlumaWindow * pluma_app_create_window (PlumaApp * app, GdkScreen * screen)
pluma_app_create_window: @app: the PlumaApp @screen: (allow-none):
Create a new PlumaWindow part of @app.
Return value: (transfer none): the new PlumaWindow
Definition at line 609 of file pluma-app.c.
References NULL, and TRUE.
Referenced by _pluma_app_get_window_in_viewport().
pluma_app_get_active_window()
PlumaWindow * pluma_app_get_active_window (PlumaApp * app)
pluma_app_get_active_window: @app: the PlumaApp
Retrives the PlumaWindow currently active.
Return value: (transfer none): the active PlumaWindow
Definition at line 663 of file pluma-app.c.
References NULL, PLUMA_IS_APP, and _PlumaApp::priv.
pluma_app_get_default()
PlumaApp * pluma_app_get_default (void)
pluma_app_get_default:
Returns the PlumaApp object. This object is a singleton and represents the running pluma instance.
Return value: (transfer none): the PlumaApp pointer
Definition at line 407 of file pluma-app.c.
References NULL, PLUMA_APP, and PLUMA_TYPE_APP.
Referenced by pluma_tab_set_auto_save_enabled().
pluma_app_get_documents()
GList * pluma_app_get_documents (PlumaApp * app)
pluma_app_get_documents: @app: the PlumaApp
Returns all the documents currently open in PlumaApp.
Return value: (element-type Pluma.Document) (transfer container): a newly allocated list of PlumaDocument objects
Definition at line 781 of file pluma-app.c.
References NULL, PLUMA_IS_APP, PLUMA_WINDOW, pluma_window_get_documents(), and _PlumaApp::priv.
pluma_app_get_lockdown()
PlumaLockdownMask pluma_app_get_lockdown (PlumaApp * app)
pluma_app_get_lockdown: @app: a PlumaApp
Gets the lockdown mask (see PlumaLockdownMask) for the application. The lockdown mask determines which functions are locked down using the MATE-wise lockdown GSettings keys.
Definition at line 840 of file pluma-app.c.
References PLUMA_IS_APP, PLUMA_LOCKDOWN_ALL, and _PlumaApp::priv.
Referenced by pluma_tab_set_auto_save_enabled().
pluma_app_get_views()
GList * pluma_app_get_views (PlumaApp * app)
pluma_app_get_views: @app: the PlumaApp
Returns all the views currently present in PlumaApp.
Return value: (element-type Pluma.View) (transfer container): a newly allocated list of PlumaView objects
Definition at line 811 of file pluma-app.c.
References NULL, PLUMA_IS_APP, PLUMA_WINDOW, pluma_window_get_views(), and _PlumaApp::priv.
pluma_app_get_windows()
const GList * pluma_app_get_windows (PlumaApp * app)
pluma_app_get_windows: @app: the PlumaApp
Returns all the windows currently present in PlumaApp.
Return value: (element-type Pluma.Window) (transfer none): the list of #PlumaWindows objects. The list should not be freed
Definition at line 647 of file pluma-app.c.
References NULL, PLUMA_IS_APP, and _PlumaApp::priv.