MATE Desktop Environment: pluma-message.h File Reference
pluma-message.h File Reference
#include <glib-object.h>
#include <stdarg.h>
Classes
struct _PlumaMessage
struct _PlumaMessageClass
Macros
#define PLUMA_TYPE_MESSAGE (pluma_message_get_type ())
#define PLUMA_MESSAGE(obj)
#define PLUMA_MESSAGE_CONST(obj)
#define PLUMA_MESSAGE_CLASS(klass)
#define PLUMA_IS_MESSAGE(obj)
#define PLUMA_IS_MESSAGE_CLASS(klass)
#define PLUMA_MESSAGE_GET_CLASS(obj)
Typedefs
typedef struct _PlumaMessage PlumaMessage
typedef struct _PlumaMessageClass PlumaMessageClass
typedef struct _PlumaMessagePrivate PlumaMessagePrivate
Functions
GType pluma_message_get_type (void)
struct _PlumaMessageType pluma_message_get_message_type (PlumaMessage *message)
void pluma_message_get (PlumaMessage *message,...)
void pluma_message_get_valist (PlumaMessage *message, va_list var_args)
void pluma_message_get_value (PlumaMessage *message, const gchar *key, GValue *value)
void pluma_message_set (PlumaMessage *message,...)
void pluma_message_set_valist (PlumaMessage *message, va_list var_args)
void pluma_message_set_value (PlumaMessage *message, const gchar *key, GValue *value)
void pluma_message_set_valuesv (PlumaMessage *message, const gchar **keys, GValue *values, gint n_values)
const gchar * pluma_message_get_object_path (PlumaMessage *message)
const gchar * pluma_message_get_method (PlumaMessage *message)
gboolean pluma_message_has_key (PlumaMessage *message, const gchar *key)
GType pluma_message_get_key_type (PlumaMessage *message, const gchar *key)
gboolean pluma_message_validate (PlumaMessage *message)
Macro Definition Documentation
PLUMA_IS_MESSAGE
#define PLUMA_IS_MESSAGE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((obj), PLUMA_TYPE_MESSAGE))
Definition at line 13 of file pluma-message.h.
Referenced by pluma_message_bus_send_message(), pluma_message_bus_send_message_sync(), pluma_message_get(), pluma_message_get_key_type(), pluma_message_get_method(), pluma_message_get_object_path(), pluma_message_get_valist(), pluma_message_get_value(), pluma_message_has_key(), pluma_message_set(), pluma_message_set_valist(), pluma_message_set_value(), pluma_message_set_valuesv(), and pluma_message_validate().
PLUMA_IS_MESSAGE_CLASS
#define PLUMA_IS_MESSAGE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), PLUMA_TYPE_MESSAGE))
Definition at line 14 of file pluma-message.h.
PLUMA_MESSAGE
#define PLUMA_MESSAGE (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_MESSAGE, PlumaMessage))
Definition at line 10 of file pluma-message.h.
Referenced by pluma_message_type_instantiate_valist().
PLUMA_MESSAGE_CLASS
#define PLUMA_MESSAGE_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), PLUMA_TYPE_MESSAGE, PlumaMessageClass))
Definition at line 12 of file pluma-message.h.
PLUMA_MESSAGE_CONST
#define PLUMA_MESSAGE_CONST (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), PLUMA_TYPE_MESSAGE, PlumaMessage const))
Definition at line 11 of file pluma-message.h.
PLUMA_MESSAGE_GET_CLASS
#define PLUMA_MESSAGE_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), PLUMA_TYPE_MESSAGE, PlumaMessageClass))
Definition at line 15 of file pluma-message.h.
PLUMA_TYPE_MESSAGE
#define PLUMA_TYPE_MESSAGE (pluma_message_get_type ())
Definition at line 9 of file pluma-message.h.
Referenced by pluma_message_type_instantiate_valist().
Typedef Documentation
PlumaMessage
typedef struct _PlumaMessage PlumaMessage
Definition at line 17 of file pluma-message.h.
PlumaMessageClass
typedef struct _PlumaMessageClass PlumaMessageClass
Definition at line 18 of file pluma-message.h.
PlumaMessagePrivate
typedef struct _PlumaMessagePrivate PlumaMessagePrivate
Definition at line 19 of file pluma-message.h.
Function Documentation
pluma_message_get()
void pluma_message_get (PlumaMessage * message, ...)
pluma_message_get: @message: the PlumaMessage ...: a NULL variable argument list of key/value container pairs
Get values of message arguments. The supplied @var_args should contain pairs of keys and pointers to variables which are set to the argument value for the specified key.
Definition at line 399 of file pluma-message.c.
References message(), PLUMA_IS_MESSAGE, and pluma_message_get_valist().
pluma_message_get_key_type()
GType pluma_message_get_key_type (PlumaMessage * message, const gchar * key)
pluma_message_get_key_type: @message: the PlumaMessage @key: the argument key
Get the type of a message argument.
Return value: the type of @key
Definition at line 508 of file pluma-message.c.
References key, message(), NULL, PLUMA_IS_MESSAGE, and pluma_message_type_lookup().
Referenced by pluma_message_get_message_type().
pluma_message_get_message_type()
struct _PlumaMessageType pluma_message_get_message_type (PlumaMessage * message)
References key, message(), pluma_message_get_key_type(), pluma_message_get_message_type(), pluma_message_get_method(), pluma_message_get_object_path(), pluma_message_get_valist(), pluma_message_get_value(), pluma_message_has_key(), pluma_message_set(), pluma_message_set_valist(), pluma_message_set_value(), pluma_message_set_valuesv(), and pluma_message_validate().
Referenced by pluma_message_get_message_type().
pluma_message_get_method()
const gchar * pluma_message_get_method (PlumaMessage * message)
pluma_message_get_method: @message: the PlumaMessage
Get the message method.
Return value: the message method
Definition at line 236 of file pluma-message.c.
References message(), NULL, PLUMA_IS_MESSAGE, and pluma_message_type_get_method().
Referenced by pluma_message_get_message_type().
pluma_message_get_object_path()
const gchar * pluma_message_get_object_path (PlumaMessage * message)
pluma_message_get_object_path: @message: the PlumaMessage
Get the message object path.
Return value: the message object path
Definition at line 253 of file pluma-message.c.
References message(), NULL, PLUMA_IS_MESSAGE, and pluma_message_type_get_object_path().
Referenced by pluma_message_get_message_type().
pluma_message_get_type()
GType pluma_message_get_type (void)
pluma_message_get_valist()
void pluma_message_get_valist (PlumaMessage * message, va_list var_args)
pluma_message_get_valist: @message: the PlumaMessage @var_args: a NULL variable argument list of key/value container pairs
Get values of message arguments. The supplied @var_args should contain pairs of keys and pointers to variables which are set to the argument value for the specified key.
Definition at line 422 of file pluma-message.c.
References error, FALSE, key, message(), NULL, and PLUMA_IS_MESSAGE.
Referenced by pluma_message_get(), and pluma_message_get_message_type().
pluma_message_get_value()
void pluma_message_get_value (PlumaMessage * message, const gchar * key, GValue * value)
pluma_message_get_value: @message: the PlumaMessage @key: the argument key @value: (out): value return container
Get the value of a specific message argument. @value will be initialized with the correct type.
Definition at line 475 of file pluma-message.c.
References FALSE, key, message(), and PLUMA_IS_MESSAGE.
Referenced by pluma_message_get_message_type().
pluma_message_has_key()
gboolean pluma_message_has_key (PlumaMessage * message, const gchar * key)
pluma_message_has_key: @message: the PlumaMessage @key: the argument key
Check whether the message has a specific key.
Return value: TRUE if @message has argument @key
Definition at line 528 of file pluma-message.c.
References FALSE, key, message(), NULL, and PLUMA_IS_MESSAGE.
Referenced by pluma_message_get_message_type().
pluma_message_set()
void pluma_message_set (PlumaMessage * message, ...)
pluma_message_set: @message: the PlumaMessage ...: a NULL terminated variable list of key/value pairs
Set values of message arguments. The supplied @var_args should contain pairs of keys and argument values.
Definition at line 270 of file pluma-message.c.
References message(), PLUMA_IS_MESSAGE, and pluma_message_set_valist().
Referenced by pluma_message_get_message_type().
pluma_message_set_valist()
void pluma_message_set_valist (PlumaMessage * message, va_list var_args)
pluma_message_set_valist: @message: the PlumaMessage @var_args: a NULL terminated variable list of key/value pairs
Set values of message arguments. The supplied @var_args should contain pairs of keys and argument values.
Definition at line 292 of file pluma-message.c.
References error, key, message(), NULL, PLUMA_IS_MESSAGE, and TRUE.
Referenced by pluma_message_get_message_type(), pluma_message_set(), and pluma_message_type_instantiate_valist().
pluma_message_set_value()
void pluma_message_set_value (PlumaMessage * message, const gchar * key, GValue * value)
pluma_message_set_value: @message: the PlumaMessage @key: the argument key @value: (out): the argument value
Set value of message argument @key to @value.
Definition at line 341 of file pluma-message.c.
References key, message(), PLUMA_IS_MESSAGE, and TRUE.
Referenced by pluma_message_get_message_type(), and pluma_message_set_valuesv().
pluma_message_set_valuesv()
void pluma_message_set_valuesv (PlumaMessage * message, const gchar ** keys, GValue * values, gint n_values)
pluma_message_set_valuesv: @message: the PlumaMessage @keys: (array length=n_values): keys to set values for @values: (array length=n_values): values to set @n_values: number of arguments to set values for
Set message argument values.
Definition at line 372 of file pluma-message.c.
References message(), PLUMA_IS_MESSAGE, and pluma_message_set_value().
Referenced by pluma_message_get_message_type().
pluma_message_validate()
gboolean pluma_message_validate (PlumaMessage * message)
pluma_message_validate: @message: the PlumaMessage
Validates the message arguments according to the message type.
Return value: TRUE if the message is valid
Definition at line 569 of file pluma-message.c.
References FALSE, message(), NULL, PLUMA_IS_MESSAGE, pluma_message_type_foreach(), and TRUE.
Referenced by pluma_message_get_message_type().