MATE Desktop Environment: pluma-progress-message-area.c File Reference
pluma-progress-message-area.c File Reference
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include "pluma-progress-message-area.h"
Enumerations
enum { PROP_0 , PROP_HAS_CANCEL_BUTTON }
Functions
GtkWidget * pluma_progress_message_area_new (const gchar *image_id, const gchar *markup, gboolean has_cancel)
void pluma_progress_message_area_set_image (PlumaProgressMessageArea *area, const gchar *image_id)
void pluma_progress_message_area_set_markup (PlumaProgressMessageArea *area, const gchar *markup)
void pluma_progress_message_area_set_text (PlumaProgressMessageArea *area, const gchar *text)
void pluma_progress_message_area_set_fraction (PlumaProgressMessageArea *area, gdouble fraction)
void pluma_progress_message_area_pulse (PlumaProgressMessageArea *area)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_HAS_CANCEL_BUTTON
Definition at line 44 of file pluma-progress-message-area.c.
Function Documentation
pluma_progress_message_area_new()
GtkWidget * pluma_progress_message_area_new (const gchar * image_id, const gchar * markup, gboolean has_cancel)
Definition at line 168 of file pluma-progress-message-area.c.
References NULL, PLUMA_PROGRESS_MESSAGE_AREA, pluma_progress_message_area_set_image(), pluma_progress_message_area_set_markup(), and PLUMA_TYPE_PROGRESS_MESSAGE_AREA.
pluma_progress_message_area_pulse()
void pluma_progress_message_area_pulse (PlumaProgressMessageArea * area)
Definition at line 235 of file pluma-progress-message-area.c.
References PLUMA_IS_PROGRESS_MESSAGE_AREA, and _PlumaProgressMessageArea::priv.
pluma_progress_message_area_set_fraction()
void pluma_progress_message_area_set_fraction (PlumaProgressMessageArea * area, gdouble fraction)
Definition at line 225 of file pluma-progress-message-area.c.
References PLUMA_IS_PROGRESS_MESSAGE_AREA, and _PlumaProgressMessageArea::priv.
pluma_progress_message_area_set_image()
void pluma_progress_message_area_set_image (PlumaProgressMessageArea * area, const gchar * image_id)
Definition at line 191 of file pluma-progress-message-area.c.
References NULL, PLUMA_IS_PROGRESS_MESSAGE_AREA, and _PlumaProgressMessageArea::priv.
Referenced by pluma_progress_message_area_new().
pluma_progress_message_area_set_markup()
void pluma_progress_message_area_set_markup (PlumaProgressMessageArea * area, const gchar * markup)
Definition at line 203 of file pluma-progress-message-area.c.
References NULL, PLUMA_IS_PROGRESS_MESSAGE_AREA, and _PlumaProgressMessageArea::priv.
Referenced by pluma_progress_message_area_new().
pluma_progress_message_area_set_text()
void pluma_progress_message_area_set_text (PlumaProgressMessageArea * area, const gchar * text)
Definition at line 214 of file pluma-progress-message-area.c.
References NULL, PLUMA_IS_PROGRESS_MESSAGE_AREA, and _PlumaProgressMessageArea::priv.