MATE Desktop Environment: pluma-commands.h File Reference
pluma-commands.h File Reference
#include <gtk/gtk.h>
#include <pluma/pluma-window.h>
Functions
void pluma_commands_load_uri (PlumaWindow *window, const gchar *uri, const PlumaEncoding *encoding, gint line_pos)
gint pluma_commands_load_uris (PlumaWindow *window, const GSList *uris, const PlumaEncoding *encoding, gint line_pos)
void pluma_commands_save_document (PlumaWindow *window, PlumaDocument *document)
void pluma_commands_save_all_documents (PlumaWindow *window)
gint _pluma_cmd_load_files_from_prompt (PlumaWindow *window, GSList *files, const PlumaEncoding *encoding, gint line_pos)
void _pluma_cmd_file_new (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_open (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_save (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_save_as (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_save_all (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_revert (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_open_uri (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_print_preview (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_print (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_close (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_close_all (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_quit (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_undo (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_redo (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_cut (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_copy (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_paste (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_delete (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_upper_case (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_lower_case (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_invert_case (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_title_case (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_select_all (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_edit_preferences (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_view_show_toolbar (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_view_show_statusbar (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_view_show_side_pane (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_view_show_bottom_pane (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_view_toggle_fullscreen_mode (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_view_leave_fullscreen_mode (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_search_find (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_search_find_next (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_search_find_prev (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_search_replace (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_search_clear_highlight (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_search_goto_line (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_search_incremental_search (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_documents_previous_document (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_documents_next_document (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_documents_move_to_new_window (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_help_contents (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_help_about (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_file_close_tab (PlumaTab *tab, PlumaWindow *window)
void _pluma_cmd_file_save_documents_list (PlumaWindow *window, GList *docs)
Function Documentation
_pluma_cmd_documents_move_to_new_window()
void _pluma_cmd_documents_move_to_new_window (GtkAction * action, PlumaWindow * window)
Definition at line 70 of file pluma-commands-documents.c.
References _pluma_window_get_notebook(), _pluma_window_move_tab_to_new_window(), action, DEBUG_COMMANDS, NULL, pluma_debug(), PLUMA_NOTEBOOK, and pluma_window_get_active_tab().
_pluma_cmd_documents_next_document()
void _pluma_cmd_documents_next_document (GtkAction * action, PlumaWindow * window)
Definition at line 58 of file pluma-commands-documents.c.
References _pluma_window_get_notebook(), action, DEBUG_COMMANDS, and pluma_debug().
_pluma_cmd_documents_previous_document()
void _pluma_cmd_documents_previous_document (GtkAction * action, PlumaWindow * window)
Definition at line 46 of file pluma-commands-documents.c.
References _pluma_window_get_notebook(), action, DEBUG_COMMANDS, and pluma_debug().
_pluma_cmd_edit_copy()
void _pluma_cmd_edit_copy (GtkAction * action, PlumaWindow * window)
Definition at line 105 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_copy_clipboard(), and pluma_window_get_active_view().
_pluma_cmd_edit_cut()
void _pluma_cmd_edit_cut (GtkAction * action, PlumaWindow * window)
Definition at line 89 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_cut_clipboard(), and pluma_window_get_active_view().
_pluma_cmd_edit_delete()
void _pluma_cmd_edit_delete (GtkAction * action, PlumaWindow * window)
Definition at line 137 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_delete_selection(), and pluma_window_get_active_view().
_pluma_cmd_edit_invert_case()
void _pluma_cmd_edit_invert_case (GtkAction * action, PlumaWindow * window)
Definition at line 201 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_invert_case_selection(), and pluma_window_get_active_view().
_pluma_cmd_edit_lower_case()
void _pluma_cmd_edit_lower_case (GtkAction * action, PlumaWindow * window)
Definition at line 185 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_lower_case_selection(), and pluma_window_get_active_view().
_pluma_cmd_edit_paste()
void _pluma_cmd_edit_paste (GtkAction * action, PlumaWindow * window)
Definition at line 121 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_paste_clipboard(), and pluma_window_get_active_view().
_pluma_cmd_edit_preferences()
void _pluma_cmd_edit_preferences (GtkAction * action, PlumaWindow * window)
Definition at line 233 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), and pluma_show_preferences_dialog().
_pluma_cmd_edit_redo()
void _pluma_cmd_edit_redo (GtkAction * action, PlumaWindow * window)
Definition at line 68 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_scroll_to_cursor(), and pluma_window_get_active_view().
_pluma_cmd_edit_select_all()
void _pluma_cmd_edit_select_all (GtkAction * action, PlumaWindow * window)
Definition at line 153 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_select_all(), and pluma_window_get_active_view().
_pluma_cmd_edit_title_case()
void _pluma_cmd_edit_title_case (GtkAction * action, PlumaWindow * window)
Definition at line 217 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_title_case_selection(), and pluma_window_get_active_view().
_pluma_cmd_edit_undo()
void _pluma_cmd_edit_undo (GtkAction * action, PlumaWindow * window)
Definition at line 47 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_scroll_to_cursor(), and pluma_window_get_active_view().
_pluma_cmd_edit_upper_case()
void _pluma_cmd_edit_upper_case (GtkAction * action, PlumaWindow * window)
Definition at line 169 of file pluma-commands-edit.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_view_upper_case_selection(), and pluma_window_get_active_view().
_pluma_cmd_file_close()
void _pluma_cmd_file_close (GtkAction * action, PlumaWindow * window)
Definition at line 1732 of file pluma-commands-file.c.
References _pluma_cmd_file_close_tab(), action, DEBUG_COMMANDS, NULL, pluma_debug(), and pluma_window_get_active_tab().
_pluma_cmd_file_close_all()
void _pluma_cmd_file_close_all (GtkAction * action, PlumaWindow * window)
Definition at line 1821 of file pluma-commands-file.c.
References action, DEBUG_COMMANDS, FALSE, pluma_debug(), pluma_window_get_state(), PLUMA_WINDOW_STATE_PRINTING, PLUMA_WINDOW_STATE_SAVING, and PLUMA_WINDOW_STATE_SAVING_SESSION.
_pluma_cmd_file_close_tab()
void _pluma_cmd_file_close_tab (PlumaTab * tab, PlumaWindow * window)
Definition at line 1707 of file pluma-commands-file.c.
References DEBUG_COMMANDS, FALSE, GBOOLEAN_TO_POINTER, pluma_debug(), PLUMA_IS_CLOSING_ALL, PLUMA_IS_QUITTING, PLUMA_IS_QUITTING_ALL, and pluma_window_close_tab().
Referenced by _pluma_cmd_file_close().
_pluma_cmd_file_new()
void _pluma_cmd_file_new (GtkAction * action, PlumaWindow * window)
Definition at line 68 of file pluma-commands-file.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_window_create_tab(), and TRUE.
_pluma_cmd_file_open()
void _pluma_cmd_file_open (GtkAction * action, PlumaWindow * window)
Definition at line 440 of file pluma-commands-file.c.
References _, _pluma_window_get_default_location(), action, data, DEBUG_COMMANDS, NULL, pluma_debug(), pluma_document_get_location(), pluma_file_chooser_dialog_new(), PLUMA_IS_FILE_CHOOSER_DIALOG, PLUMA_OPEN_DIALOG_KEY, and pluma_window_get_active_document().
_pluma_cmd_file_open_uri()
void _pluma_cmd_file_open_uri (GtkAction * action, PlumaWindow * window)
References action.
_pluma_cmd_file_print()
void _pluma_cmd_file_print (GtkAction * action, PlumaWindow * window)
Definition at line 62 of file pluma-commands-file-print.c.
References _pluma_tab_print(), action, DEBUG_COMMANDS, NULL, pluma_debug(), and pluma_window_get_active_tab().
_pluma_cmd_file_print_preview()
void _pluma_cmd_file_print_preview (GtkAction * action, PlumaWindow * window)
Definition at line 47 of file pluma-commands-file-print.c.
References _pluma_tab_print_preview(), action, DEBUG_COMMANDS, NULL, pluma_debug(), and pluma_window_get_active_tab().
_pluma_cmd_file_quit()
void _pluma_cmd_file_quit (GtkAction * action, PlumaWindow * window)
Definition at line 1835 of file pluma-commands-file.c.
References action, DEBUG_COMMANDS, pluma_debug(), pluma_window_get_state(), PLUMA_WINDOW_STATE_PRINTING, PLUMA_WINDOW_STATE_SAVING, PLUMA_WINDOW_STATE_SAVING_SESSION, and TRUE.
_pluma_cmd_file_revert()
void _pluma_cmd_file_revert (GtkAction * action, PlumaWindow * window)
Definition at line 1238 of file pluma-commands-file.c.
References action, DEBUG_COMMANDS, NULL, pluma_debug(), pluma_document_is_untitled(), pluma_tab_get_document(), pluma_tab_get_state(), PLUMA_TAB_STATE_EXTERNALLY_MODIFIED_NOTIFICATION, pluma_window_get_active_tab(), pluma_window_get_group(), and TRUE.
_pluma_cmd_file_save()
void _pluma_cmd_file_save (GtkAction * action, PlumaWindow * window)
Definition at line 880 of file pluma-commands-file.c.
References action, DEBUG_COMMANDS, NULL, pluma_debug(), and pluma_window_get_active_tab().
_pluma_cmd_file_save_all()
void _pluma_cmd_file_save_all (GtkAction * action, PlumaWindow * window)
Definition at line 1049 of file pluma-commands-file.c.
References action, and pluma_commands_save_all_documents().
_pluma_cmd_file_save_as()
void _pluma_cmd_file_save_as (GtkAction * action, PlumaWindow * window)
Definition at line 895 of file pluma-commands-file.c.
References action, DEBUG_COMMANDS, NULL, pluma_debug(), and pluma_window_get_active_tab().
_pluma_cmd_file_save_documents_list()
void _pluma_cmd_file_save_documents_list (PlumaWindow * window, GList * docs)
Definition at line 927 of file pluma-commands-file.c.
References DEBUG_COMMANDS, NULL, pluma_debug(), pluma_debug_message(), PLUMA_DOCUMENT, pluma_document_get_readonly(), pluma_document_get_uri_for_display(), pluma_document_is_untitled(), PLUMA_IS_DOCUMENT, PLUMA_LIST_OF_TABS_TO_SAVE_AS, PLUMA_TAB, pluma_tab_get_from_document(), pluma_tab_get_state(), PLUMA_TAB_STATE_CLOSING, PLUMA_TAB_STATE_GENERIC_NOT_EDITABLE, PLUMA_TAB_STATE_NORMAL, PLUMA_TAB_STATE_PRINT_PREVIEWING, PLUMA_TAB_STATE_PRINTING, PLUMA_TAB_STATE_SHOWING_PRINT_PREVIEW, pluma_window_get_state(), pluma_window_set_active_tab(), PLUMA_WINDOW_STATE_PRINTING, and PLUMA_WINDOW_STATE_SAVING_SESSION.
Referenced by pluma_commands_save_all_documents().
_pluma_cmd_help_about()
void _pluma_cmd_help_about (GtkAction * action, PlumaWindow * window)
Definition at line 58 of file pluma-commands-help.c.
References _, ABOUT_GROUP, action, DEBUG_COMMANDS, EMAILIFY, error, N_, NULL, PACKAGE_URL, pluma_debug(), TRUE, and VERSION.
_pluma_cmd_help_contents()
void _pluma_cmd_help_contents (GtkAction * action, PlumaWindow * window)
Definition at line 48 of file pluma-commands-help.c.
References action, DEBUG_COMMANDS, NULL, pluma_debug(), and pluma_help_display().
_pluma_cmd_load_files_from_prompt()
gint _pluma_cmd_load_files_from_prompt (PlumaWindow * window, GSList * files, const PlumaEncoding * encoding, gint line_pos)
Definition at line 383 of file pluma-commands-file.c.
References DEBUG_COMMANDS, pluma_debug(), and TRUE.
_pluma_cmd_search_clear_highlight()
void _pluma_cmd_search_clear_highlight (GtkAction * action, PlumaWindow * window)
Definition at line 767 of file pluma-commands-search.c.
References action, DEBUG_COMMANDS, pluma_debug(), PLUMA_DOCUMENT, pluma_document_set_search_text(), PLUMA_SEARCH_DONT_SET_FLAGS, and pluma_window_get_active_document().
_pluma_cmd_search_find()
void _pluma_cmd_search_find (GtkAction * action, PlumaWindow * window)
Definition at line 580 of file pluma-commands-search.c.
References action, data, DEBUG_COMMANDS, FALSE, NULL, pluma_debug(), PLUMA_IS_SEARCH_DIALOG, PLUMA_SEARCH_DIALOG, pluma_search_dialog_get_parse_escapes(), pluma_search_dialog_get_search_text(), pluma_search_dialog_get_show_replace(), PLUMA_SEARCH_DIALOG_KEY, pluma_search_dialog_present_with_time(), pluma_search_dialog_set_search_text(), pluma_search_dialog_set_show_replace(), pluma_utils_unescape_search_text(), and pluma_window_get_active_document().
_pluma_cmd_search_find_next()
void _pluma_cmd_search_find_next (GtkAction * action, PlumaWindow * window)
Definition at line 749 of file pluma-commands-search.c.
References action, DEBUG_COMMANDS, FALSE, and pluma_debug().
_pluma_cmd_search_find_prev()
void _pluma_cmd_search_find_prev (GtkAction * action, PlumaWindow * window)
Definition at line 758 of file pluma-commands-search.c.
References action, DEBUG_COMMANDS, pluma_debug(), and TRUE.
_pluma_cmd_search_goto_line()
void _pluma_cmd_search_goto_line (GtkAction * action, PlumaWindow * window)
Definition at line 781 of file pluma-commands-search.c.
References action, DEBUG_COMMANDS, NULL, pluma_debug(), and pluma_window_get_active_view().
_pluma_cmd_search_incremental_search()
void _pluma_cmd_search_incremental_search (GtkAction * action, PlumaWindow * window)
Definition at line 806 of file pluma-commands-search.c.
References action, DEBUG_COMMANDS, NULL, pluma_debug(), and pluma_window_get_active_view().
_pluma_cmd_search_replace()
void _pluma_cmd_search_replace (GtkAction * action, PlumaWindow * window)
Definition at line 654 of file pluma-commands-search.c.
References action, data, DEBUG_COMMANDS, NULL, pluma_debug(), PLUMA_IS_SEARCH_DIALOG, PLUMA_SEARCH_DIALOG, pluma_search_dialog_get_parse_escapes(), pluma_search_dialog_get_search_text(), pluma_search_dialog_get_show_replace(), PLUMA_SEARCH_DIALOG_KEY, pluma_search_dialog_present_with_time(), pluma_search_dialog_set_search_text(), pluma_search_dialog_set_show_replace(), pluma_utils_unescape_search_text(), pluma_window_get_active_document(), and TRUE.
_pluma_cmd_view_leave_fullscreen_mode()
void _pluma_cmd_view_leave_fullscreen_mode (GtkAction * action, PlumaWindow * window)
Definition at line 139 of file pluma-commands-view.c.
References _pluma_cmd_view_toggle_fullscreen_mode(), _pluma_window_unfullscreen(), action, and FALSE.
_pluma_cmd_view_show_bottom_pane()
void _pluma_cmd_view_show_bottom_pane (GtkAction * action, PlumaWindow * window)
Definition at line 103 of file pluma-commands-view.c.
References action, DEBUG_COMMANDS, pluma_debug(), and pluma_window_get_bottom_panel().
_pluma_cmd_view_show_side_pane()
void _pluma_cmd_view_show_side_pane (GtkAction * action, PlumaWindow * window)
Definition at line 79 of file pluma-commands-view.c.
References action, DEBUG_COMMANDS, pluma_debug(), and pluma_window_get_side_panel().
_pluma_cmd_view_show_statusbar()
void _pluma_cmd_view_show_statusbar (GtkAction * action, PlumaWindow * window)
Definition at line 63 of file pluma-commands-view.c.
References action, DEBUG_COMMANDS, and pluma_debug().
_pluma_cmd_view_show_toolbar()
void _pluma_cmd_view_show_toolbar (GtkAction * action, PlumaWindow * window)
Definition at line 47 of file pluma-commands-view.c.
References action, DEBUG_COMMANDS, and pluma_debug().
_pluma_cmd_view_toggle_fullscreen_mode()
void _pluma_cmd_view_toggle_fullscreen_mode (GtkAction * action, PlumaWindow * window)
Definition at line 127 of file pluma-commands-view.c.
References _pluma_window_fullscreen(), _pluma_window_is_fullscreen(), _pluma_window_unfullscreen(), action, DEBUG_COMMANDS, and pluma_debug().
Referenced by _pluma_cmd_view_leave_fullscreen_mode().
pluma_commands_load_uri()
void pluma_commands_load_uri (PlumaWindow * window, const gchar * uri, const PlumaEncoding * encoding, gint line_pos)
pluma_commands_load_uri: @window: @uri: @encoding: (allow-none): @line_pos:
Do nothing if uri does not exist
Definition at line 315 of file pluma-commands-file.c.
References DEBUG_COMMANDS, FALSE, NULL, pluma_debug_message(), PLUMA_IS_WINDOW, and pluma_utils_is_valid_uri().
pluma_commands_load_uris()
gint pluma_commands_load_uris (PlumaWindow * window, const GSList * uris, const PlumaEncoding * encoding, gint line_pos)
pluma_commands_load_uris: @window: @uris: @encoding: @line_pos:
Ignore non-existing URIs
Returns:
Definition at line 347 of file pluma-commands-file.c.
References DEBUG_COMMANDS, FALSE, NULL, pluma_debug(), and PLUMA_IS_WINDOW.
pluma_commands_save_all_documents()
void pluma_commands_save_all_documents (PlumaWindow * window)
Definition at line 1033 of file pluma-commands-file.c.
References _pluma_cmd_file_save_documents_list(), DEBUG_COMMANDS, pluma_debug(), PLUMA_IS_WINDOW, and pluma_window_get_documents().
Referenced by _pluma_cmd_file_save_all().
pluma_commands_save_document()
void pluma_commands_save_document (PlumaWindow * window, PlumaDocument * document)
Definition at line 1056 of file pluma-commands-file.c.
References DEBUG_COMMANDS, pluma_debug(), PLUMA_IS_DOCUMENT, PLUMA_IS_WINDOW, and pluma_tab_get_from_document().