MATE Desktop Environment: pluma-utils.c File Reference
pluma-utils.c File Reference
#include <errno.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <fcntl.h>
#include <string.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include "pluma-utils.h"
#include "pluma-settings.h"
#include "pluma-document.h"
#include "pluma-debug.h"
#include <gdk/gdkx.h>
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/Xatom.h>
Functions
gboolean pluma_utils_uri_has_file_scheme (const gchar *uri)
gboolean pluma_utils_uri_has_writable_scheme (const gchar *uri)
void pluma_utils_menu_position_under_widget (GtkMenu *menu, gint *x, gint *y, gboolean *push_in, gpointer user_data)
void menu_popup_at_treeview_selection (GtkWidget *menu, GtkWidget *treeview)
GtkWidget * pluma_gtk_button_new_with_icon (const gchar *label, const gchar *icon_name)
GtkWidget * pluma_dialog_add_button (GtkDialog *dialog, const gchar *text, const gchar *icon_name, gint response_id)
gboolean g_utf8_caselessnmatch (const char *s1, const char *s2, gssize n1, gssize n2)
: Atk name string
pluma_utils_set_atk_name_description: @widget: The Gtk widget for which name/description to be set
@description: Atk description string
This function sets up name and description for a specified gtk widget.
void pluma_utils_set_atk_name_description (GtkWidget *widget, const gchar *name, const gchar *description)
void pluma_utils_set_atk_relation (GtkWidget *obj1, GtkWidget *obj2, AtkRelationType rel_type)
gboolean pluma_utils_uri_exists (const gchar *text_uri)
gchar * pluma_utils_escape_search_text (const gchar *text)
gchar * pluma_utils_unescape_search_text (const gchar *text)
void pluma_warning (GtkWindow *parent, const gchar *format,...)
gchar * pluma_utils_escape_underscores (const gchar *text, gssize length)
gchar * pluma_utils_str_middle_truncate (const gchar *string, guint truncate_length)
gchar * pluma_utils_str_end_truncate (const gchar *string, guint truncate_length)
gchar * pluma_utils_make_valid_utf8 (const char *name)
gchar * pluma_utils_uri_get_dirname (const gchar *uri)
gchar * pluma_utils_location_get_dirname_for_display (GFile *location)
gchar * pluma_utils_replace_home_dir_with_tilde (const gchar *uri)
guint pluma_utils_get_current_workspace (GdkScreen *screen)
guint pluma_utils_get_window_workspace (GtkWindow *gtkwindow)
void pluma_utils_get_current_viewport (GdkScreen *screen, gint *x, gint *y)
gboolean pluma_utils_is_valid_uri (const gchar *uri)
gboolean pluma_utils_get_ui_objects (const gchar *filename, gchar **root_objects, GtkWidget **error_widget, const gchar *object_name,...)
gchar * pluma_utils_make_canonical_uri_from_shell_arg (const gchar *str)
gboolean pluma_utils_file_has_parent (GFile *gfile)
gchar * pluma_utils_basename_for_display (gchar const *uri)
gchar * pluma_utils_uri_for_display (const gchar *uri)
gchar ** pluma_utils_drop_get_uris (GtkSelectionData *selection_data)
gboolean pluma_utils_decode_uri (const gchar *uri, gchar **scheme, gchar **user, gchar **host, gchar **port, gchar **path)
gboolean pluma_gtk_text_iter_regex_search (const GtkTextIter *iter, const gchar *str, GtkTextSearchFlags flags, GtkTextIter *match_start, GtkTextIter *match_end, const GtkTextIter *limit, gboolean forward_search, gchar **replace_text)
Function Documentation
g_utf8_caselessnmatch()
gboolean g_utf8_caselessnmatch (const char * s1, const char * s2, gssize n1, gssize n2)
Definition at line 239 of file pluma-utils.c.
References FALSE, and NULL.
menu_popup_at_treeview_selection()
void menu_popup_at_treeview_selection (GtkWidget * menu, GtkWidget * treeview)
Definition at line 156 of file pluma-utils.c.
References NULL.
pluma_dialog_add_button()
GtkWidget * pluma_dialog_add_button (GtkDialog * dialog, const gchar * text, const gchar * icon_name, gint response_id)
pluma_dialog_add_button: @dialog: @text: @icon_name: @response_id:
Returns: (transfer none):
Definition at line 212 of file pluma-utils.c.
References NULL, pluma_gtk_button_new_with_icon(), and TRUE.
pluma_gtk_button_new_with_icon()
GtkWidget * pluma_gtk_button_new_with_icon (const gchar * label, const gchar * icon_name)
pluma_gtk_button_new_with_icon: @label: @icon_name:
Returns: (transfer full):
Definition at line 189 of file pluma-utils.c.
References label.
Referenced by pluma_dialog_add_button().
pluma_gtk_text_iter_regex_search()
gboolean pluma_gtk_text_iter_regex_search (const GtkTextIter * iter, const gchar * str, GtkTextSearchFlags flags, GtkTextIter * match_start, GtkTextIter * match_end, const GtkTextIter * limit, gboolean forward_search, gchar ** replace_text)
Definition at line 1563 of file pluma-utils.c.
References FALSE, NULL, and regex.
Referenced by pluma_document_replace_all(), pluma_document_search_backward(), pluma_document_search_forward(), and pluma_utils_uri_get_dirname().
pluma_utils_basename_for_display()
gchar * pluma_utils_basename_for_display (gchar const * uri)
pluma_utils_basename_for_display: @uri: uri for which the basename should be displayed
Return the basename of a file suitable for display to users.
Definition at line 1268 of file pluma-utils.c.
References _, name, NULL, pluma_utils_decode_uri(), pluma_utils_file_has_parent(), and pluma_utils_make_valid_utf8().
Referenced by pluma_document_get_short_name_for_display(), pluma_file_browser_utils_uri_basename(), and pluma_utils_uri_get_dirname().
pluma_utils_decode_uri()
gboolean pluma_utils_decode_uri (const gchar * uri, gchar ** scheme, gchar ** user, gchar ** host, gchar ** port, gchar ** path)
pluma_utils_decode_uri: @uri: the uri to decode @scheme: (allow-none): return value pointer for the uri's scheme (e.g. http, sftp, ...), or NULL @user: (allow-none): return value pointer for the uri user info, or NULL @host: (allow-none): return value pointer for the uri host, or NULL @port: (allow-none): return value pointer for the uri port, or NULL @path: (allow-none): return value pointer for the uri path, or NULL
Parse and break an uri apart in its individual components like the uri scheme, user info, port, host and path. The return value pointer can be NULL to ignore certain parts of the uri. If the function returns TRUE, then all return value pointers should be freed using g_free
Return value: TRUE if the uri could be properly decoded, FALSE otherwise.
Definition at line 1435 of file pluma-utils.c.
References FALSE, NULL, and TRUE.
Referenced by pluma_utils_basename_for_display(), pluma_utils_location_get_dirname_for_display(), and pluma_utils_uri_get_dirname().
pluma_utils_drop_get_uris()
gchar ** pluma_utils_drop_get_uris (GtkSelectionData * selection_data)
pluma_utils_drop_get_uris: @selection_data: the #GtkSelectionData from drag_data_received
Create a list of valid uri's from a uri-list drop.
Return value: (transfer full): a string array which will hold the uris or NULL if there were no valid uris. g_strfreev should be used when the string array is no longer used
Definition at line 1378 of file pluma-utils.c.
References NULL, and pluma_utils_make_canonical_uri_from_shell_arg().
Referenced by pluma_utils_uri_get_dirname().
pluma_utils_escape_search_text()
gchar * pluma_utils_escape_search_text (const gchar * text)
Definition at line 359 of file pluma-utils.c.
References DEBUG_SEARCH, FALSE, NULL, and pluma_debug_message().
Referenced by pluma_document_get_search_text().
pluma_utils_escape_underscores()
gchar * pluma_utils_escape_underscores (const gchar * text, gssize length)
Definition at line 532 of file pluma-utils.c.
References FALSE, and NULL.
pluma_utils_file_has_parent()
gboolean pluma_utils_file_has_parent (GFile * gfile)
pluma_utils_file_has_parent: @gfile: the GFile to check the parent for
Return TRUE if the specified gfile has a parent (is not the root), FALSE otherwise
Definition at line 1247 of file pluma-utils.c.
References NULL.
Referenced by pluma_utils_basename_for_display(), and pluma_utils_uri_get_dirname().
pluma_utils_get_current_viewport()
void pluma_utils_get_current_viewport (GdkScreen * screen, gint * x, gint * y)
pluma_utils_get_current_viewport:
Get the current viewport origin
Get the currently visible viewport origin for the #GdkScreen.
If the X11 window property isn't found, (0, 0) is returned.
Definition at line 951 of file pluma-utils.c.
References GDK_IS_X11_DISPLAY, and NULL.
Referenced by pluma_utils_uri_get_dirname().
pluma_utils_get_current_workspace()
guint pluma_utils_get_current_workspace (GdkScreen * screen)
pluma_utils_get_current_workspace:
Get the current workspace
Get the currently visible workspace for the #GdkScreen.
If the X11 window property isn't found, 0 (the first workspace) is returned.
Definition at line 847 of file pluma-utils.c.
References GDK_IS_X11_DISPLAY.
Referenced by pluma_utils_uri_get_dirname().
pluma_utils_get_ui_objects()
gboolean pluma_utils_get_ui_objects (const gchar * filename, gchar ** root_objects, GtkWidget ** error_widget, const gchar * object_name, ...)
pluma_utils_get_ui_objects: @filename: the path to the gtk builder file @root_objects: a NULL terminated list of root objects to load or NULL to load all objects @error_widget: a pointer were a #GtkLabel @object_name: the name of the first object ...: a pointer were the first object is returned, followed by more name / object pairs and terminated by NULL.
This function gets the requested objects from a GtkBuilder ui file. In case of error it returns FALSE and sets error_widget to a GtkLabel containing the error message to display.
Returns: FALSE if an error occurs, TRUE on success.
Definition at line 1113 of file pluma-utils.c.
References _, error, FALSE, name, NULL, and TRUE.
Referenced by pluma_utils_uri_get_dirname().
pluma_utils_get_window_workspace()
guint pluma_utils_get_window_workspace (GtkWindow * gtkwindow)
pluma_utils_get_window_workspace:
Get the workspace the window is on
This function gets the workspace that the #GtkWindow is visible on, it returns PLUMA_ALL_WORKSPACES if the window is sticky, or if the window manager doesn support this function
Definition at line 898 of file pluma-utils.c.
References GDK_IS_X11_DISPLAY, and PLUMA_ALL_WORKSPACES.
Referenced by pluma_utils_uri_get_dirname().
pluma_utils_is_valid_uri()
gboolean pluma_utils_is_valid_uri (const gchar * uri)
Definition at line 1030 of file pluma-utils.c.
References FALSE, NULL, and TRUE.
Referenced by pluma_commands_load_uri(), pluma_document_load(), pluma_utils_make_canonical_uri_from_shell_arg(), and pluma_utils_uri_get_dirname().
pluma_utils_location_get_dirname_for_display()
gchar * pluma_utils_location_get_dirname_for_display (GFile * location)
pluma_utils_location_get_dirname_for_display: @location: the location
Returns a string suitable to be displayed in the UI indicating the name of the directory where the file is located. For remote files it may also contain the hostname etc. For local files it tries to replace the home dir with ~.
Returns: a string to display the dirname
Definition at line 727 of file pluma-utils.c.
References NULL, pluma_utils_decode_uri(), and pluma_utils_uri_get_dirname().
Referenced by pluma_utils_uri_get_dirname().
pluma_utils_make_canonical_uri_from_shell_arg()
gchar * pluma_utils_make_canonical_uri_from_shell_arg (const gchar * str)
Definition at line 1203 of file pluma-utils.c.
References NULL, and pluma_utils_is_valid_uri().
Referenced by pluma_utils_drop_get_uris(), and pluma_utils_uri_get_dirname().
pluma_utils_make_valid_utf8()
gchar * pluma_utils_make_valid_utf8 (const char * name)
Definition at line 644 of file pluma-utils.c.
References FALSE, name, and NULL.
Referenced by pluma_utils_basename_for_display().
pluma_utils_menu_position_under_widget()
void pluma_utils_menu_position_under_widget (GtkMenu * menu, gint * x, gint * y, gboolean * push_in, gpointer user_data)
Definition at line 124 of file pluma-utils.c.
References NULL, TRUE, and user_data.
pluma_utils_replace_home_dir_with_tilde()
gchar * pluma_utils_replace_home_dir_with_tilde (const gchar * uri)
Definition at line 790 of file pluma-utils.c.
References NULL.
Referenced by _pluma_tab_get_tooltips(), pluma_utils_uri_get_dirname(), and pluma_utils_uri_get_dirname().
pluma_utils_set_atk_name_description()
void pluma_utils_set_atk_name_description (GtkWidget * widget, const gchar * name, const gchar * description)
Definition at line 286 of file pluma-utils.c.
References name.
pluma_utils_set_atk_relation()
void pluma_utils_set_atk_relation (GtkWidget * obj1, GtkWidget * obj2, AtkRelationType rel_type)
pluma_set_atk_relation: @obj1: specified widget. @obj2: specified widget. @rel_type: the type of relation to set up.
This function establishes atk relation between 2 specified widgets.
Definition at line 314 of file pluma-utils.c.
pluma_utils_str_end_truncate()
gchar * pluma_utils_str_end_truncate (const gchar * string, guint truncate_length)
Definition at line 637 of file pluma-utils.c.
References FALSE.
pluma_utils_str_middle_truncate()
gchar * pluma_utils_str_middle_truncate (const gchar * string, guint truncate_length)
Definition at line 630 of file pluma-utils.c.
References TRUE.
Referenced by _pluma_tab_get_name(), pluma_conversion_error_while_saving_message_area_new(), pluma_externally_modified_message_area_new(), pluma_externally_modified_saving_error_message_area_new(), pluma_file_already_open_warning_message_area_new(), pluma_io_loading_error_message_area_new(), pluma_no_backup_saving_error_message_area_new(), pluma_unrecoverable_reverting_error_message_area_new(), and pluma_unrecoverable_saving_error_message_area_new().
pluma_utils_unescape_search_text()
gchar * pluma_utils_unescape_search_text (const gchar * text)
Definition at line 415 of file pluma-utils.c.
References FALSE, NULL, and TRUE.
Referenced by _pluma_cmd_search_find(), _pluma_cmd_search_replace(), pluma_document_replace_all(), and pluma_document_set_search_text().
pluma_utils_uri_exists()
gboolean pluma_utils_uri_exists (const gchar * text_uri)
Definition at line 339 of file pluma-utils.c.
References DEBUG_UTILS, FALSE, NULL, and pluma_debug_message().
Referenced by pluma_document_get_deleted().
pluma_utils_uri_for_display()
gchar * pluma_utils_uri_for_display (const gchar * uri)
pluma_utils_uri_for_display: @uri: uri to be displayed.
Filter, modify, unescape and change @uri to make it appropriate for display to users.
This function is a convenient wrapper for g_file_get_parse_name
Return value: a string which represents @uri and can be displayed.
Definition at line 1355 of file pluma-utils.c.
Referenced by pluma_conversion_error_while_saving_message_area_new(), pluma_document_get_uri_for_display(), pluma_externally_modified_message_area_new(), pluma_externally_modified_saving_error_message_area_new(), pluma_file_already_open_warning_message_area_new(), pluma_io_loading_error_message_area_new(), pluma_no_backup_saving_error_message_area_new(), pluma_unrecoverable_reverting_error_message_area_new(), pluma_unrecoverable_saving_error_message_area_new(), and pluma_utils_uri_get_dirname().
pluma_utils_uri_get_dirname()
gchar * pluma_utils_uri_get_dirname (const gchar * uri)
pluma_utils_uri_get_dirname:
Note: this function replace home dir with ~
Definition at line 690 of file pluma-utils.c.
References NULL, and pluma_utils_replace_home_dir_with_tilde().
Referenced by pluma_utils_location_get_dirname_for_display(), and pluma_utils_uri_get_dirname().
pluma_utils_uri_has_file_scheme()
gboolean pluma_utils_uri_has_file_scheme (const gchar * uri)
pluma_utils_uris_has_file_scheme
Returns: TRUE if @uri is a file: uri and is not a chained uri
Definition at line 67 of file pluma-utils.c.
Referenced by pluma_document_is_local().
pluma_utils_uri_has_writable_scheme()
gboolean pluma_utils_uri_has_writable_scheme (const gchar * uri)
Definition at line 81 of file pluma-utils.c.
References FALSE, NULL, PLUMA_SCHEMA_ID, and pluma_settings_get_writable_vfs_schemes().
pluma_warning()
void pluma_warning (GtkWindow * parent, const gchar * format, ...)
Definition at line 489 of file pluma-utils.c.
References FALSE, and NULL.