MATE Desktop Environment: pluma-commands-help.c File Reference
pluma-commands-help.c File Reference
#include <glib.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include "pluma-commands.h"
#include "pluma-debug.h"
#include "pluma-help.h"
#include "pluma-dirs.h"
Macros
#define ABOUT_GROUP "About"
#define EMAILIFY(string)
Functions
void _pluma_cmd_help_contents (GtkAction *action, PlumaWindow *window)
void _pluma_cmd_help_about (GtkAction *action, PlumaWindow *window)
Macro Definition Documentation
ABOUT_GROUP
#define ABOUT_GROUP "About"
Definition at line 55 of file pluma-commands-help.c.
EMAILIFY
#define EMAILIFY (string)
Value:
(g_strdelimit ((string), "%", '@'))
Definition at line 56 of file pluma-commands-help.c.
Function Documentation
_pluma_cmd_help_about()
void _pluma_cmd_help_about (GtkAction * action, PlumaWindow * window)
Definition at line 58 of file pluma-commands-help.c.
References _, ABOUT_GROUP, action, DEBUG_COMMANDS, EMAILIFY, error, N_, NULL, PACKAGE_URL, pluma_debug(), TRUE, and VERSION.
_pluma_cmd_help_contents()
void _pluma_cmd_help_contents (GtkAction * action, PlumaWindow * window)
Definition at line 48 of file pluma-commands-help.c.
References action, DEBUG_COMMANDS, NULL, pluma_debug(), and pluma_help_display().