MATE Desktop Environment: polkitmateauthenticator.c File Reference
polkitmateauthenticator.c File Reference
#include "config.h"
#include <string.h>
#include <sys/types.h>
#include <pwd.h>
#include <glib/gi18n.h>
#include <gdk/gdkx.h>
#include <polkit/polkit.h>
#include <polkitagent/polkitagent.h>
#include "polkitmateauthenticator.h"
#include "polkitmateauthenticationdialog.h"
Enumerations
enum { COMPLETED_SIGNAL , LAST_SIGNAL }
Functions
G_DEFINE_TYPE (PolkitMateAuthenticator, polkit_mate_authenticator, G_TYPE_OBJECT)
PolkitMateAuthenticator * polkit_mate_authenticator_new (const gchar *action_id, const gchar *message, const gchar *icon_name, PolkitDetails *details, const gchar *cookie, GList *identities)
void polkit_mate_authenticator_initiate (PolkitMateAuthenticator *authenticator)
void polkit_mate_authenticator_cancel (PolkitMateAuthenticator *authenticator)
const gchar * polkit_mate_authenticator_get_cookie (PolkitMateAuthenticator *authenticator)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
COMPLETED_SIGNAL
LAST_SIGNAL
Definition at line 68 of file polkitmateauthenticator.c.
Function Documentation
G_DEFINE_TYPE()
G_DEFINE_TYPE (PolkitMateAuthenticator , polkit_mate_authenticator , G_TYPE_OBJECT)
polkit_mate_authenticator_cancel()
void polkit_mate_authenticator_cancel (PolkitMateAuthenticator * authenticator)
Definition at line 498 of file polkitmateauthenticator.c.
References NULL, POLKIT_MATE_AUTHENTICATION_DIALOG, polkit_mate_authentication_dialog_cancel(), and TRUE.
polkit_mate_authenticator_get_cookie()
const gchar * polkit_mate_authenticator_get_cookie (PolkitMateAuthenticator * authenticator)
Definition at line 512 of file polkitmateauthenticator.c.
polkit_mate_authenticator_initiate()
void polkit_mate_authenticator_initiate (PolkitMateAuthenticator * authenticator)
Definition at line 491 of file polkitmateauthenticator.c.
polkit_mate_authenticator_new()
PolkitMateAuthenticator * polkit_mate_authenticator_new (const gchar * action_id, const gchar * message, const gchar * icon_name, PolkitDetails * details, const gchar * cookie, GList * identities)
Definition at line 205 of file polkitmateauthenticator.c.
References error, message(), NULL, polkit_mate_authentication_dialog_new(), POLKIT_MATE_AUTHENTICATOR, and POLKIT_MATE_TYPE_AUTHENTICATOR.