MATE Desktop Environment: prefs.c File Reference
prefs.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include "prefs.h"
#include "ui.h"
#include "util.h"
#include <gdk/gdk.h>
#include <gio/gio.h>
#include <string.h>
#include <stdlib.h>
#include "all-keybindings.h"
Macros
#define MAX_REASONABLE_WORKSPACES 36
#define KEY_GENERAL_SCHEMA "org.mate.Marco.general"
#define KEY_GENERAL_TITLEBAR_FONT "titlebar-font"
#define KEY_GENERAL_NUM_WORKSPACES "num-workspaces"
#define KEY_GENERAL_COMPOSITOR "compositing-manager"
#define KEY_GENERAL_COMPOSITOR_FAST_ALT_TAB "compositing-fast-alt-tab"
#define KEY_GENERAL_CENTER_NEW_WINDOWS "center-new-windows"
#define KEY_GENERAL_ICON_SIZE "icon-size"
#define KEY_GENERAL_ALT_TAB_MAX_COLUMNS "alt-tab-max-columns"
#define KEY_GENERAL_ALT_TAB_RAISE_WINDOWS "alt-tab-raise-windows"
#define KEY_GENERAL_ALT_TAB_EXPAND_TO_FIT_TITLE "alt-tab-expand-to-fit-title"
#define KEY_COMMAND_SCHEMA "org.mate.Marco.keybinding-commands"
#define KEY_COMMAND_PREFIX "command-"
#define KEY_SCREEN_BINDINGS_SCHEMA "org.mate.Marco.global-keybindings"
#define KEY_WINDOW_BINDINGS_SCHEMA "org.mate.Marco.window-keybindings"
#define KEY_WORKSPACE_NAME_SCHEMA "org.mate.Marco.workspace-names"
#define KEY_WORKSPACE_NAME_PREFIX "name-"
#define KEY_MATE_INTERFACE_SCHEMA "org.mate.interface"
#define KEY_MATE_INTERFACE_ACCESSIBILITY "accessibility"
#define KEY_MATE_INTERFACE_ENABLE_ANIMATIONS "enable-animations"
#define KEY_MATE_TERMINAL_SCHEMA "org.mate.applications-terminal"
#define KEY_MATE_TERMINAL_COMMAND "exec"
#define KEY_MATE_MOUSE_SCHEMA "org.mate.peripherals-mouse"
#define KEY_MATE_MOUSE_CURSOR_THEME "cursor-theme"
#define KEY_MATE_MOUSE_CURSOR_SIZE "cursor-size"
#define SETTINGS(s)
#define METAINTPREFERENCE_NO_CHANGE_ON_DESTROY G_MININT
#define MAX_REASONABLE_AUTO_RAISE_DELAY 10000
#define keybind(name, handler, param, flags)
#define _BINDINGS_DEFINED_CONSTANTS 1
#define BINDING_PER_WINDOW 0x01
#define BINDING_REVERSES 0x02
#define BINDING_IS_REVERSED 0x04
#define REVERSES_AND_REVERSED (BINDING_REVERSES | BINDING_IS_REVERSED)
Functions
void meta_prefs_add_listener (MetaPrefsChangedFunc func, gpointer data)
void meta_prefs_remove_listener (MetaPrefsChangedFunc func, gpointer data)
void meta_prefs_init (void)
MetaVirtualModifier meta_prefs_get_mouse_button_mods (void)
MetaFocusMode meta_prefs_get_focus_mode (void)
MetaFocusNewWindows meta_prefs_get_focus_new_windows (void)
gboolean meta_prefs_get_attach_modal_dialogs (void)
gboolean meta_prefs_get_raise_on_click (void)
const char * meta_prefs_get_theme (void)
const char * meta_prefs_get_cursor_theme (void)
int meta_prefs_get_cursor_size (void)
int meta_prefs_get_icon_size (void)
int meta_prefs_get_alt_tab_max_columns (void)
gboolean meta_prefs_get_alt_tab_expand_to_fit_title (void)
gboolean meta_prefs_get_alt_tab_raise_windows (void)
gboolean meta_prefs_is_in_skip_list (char *class)
const PangoFontDescription * meta_prefs_get_titlebar_font (void)
int meta_prefs_get_num_workspaces (void)
gboolean meta_prefs_get_dynamic_workspaces (void)
MetaWrapStyle meta_prefs_get_wrap_style (void)
gboolean meta_prefs_get_application_based (void)
gboolean meta_prefs_get_disable_workarounds (void)
void meta_prefs_set_num_workspaces (int n_workspaces)
const char * meta_prefs_get_command (int i)
char * meta_prefs_get_settings_key_for_command (int i)
const char * meta_prefs_get_terminal_command (void)
const char * meta_prefs_get_settings_key_for_terminal_command (void)
const char * meta_prefs_get_workspace_name (int i)
void meta_prefs_change_workspace_name (int i, const char *name)
void meta_prefs_get_button_layout (MetaButtonLayout *button_layout_p)
gboolean meta_prefs_get_visual_bell (void)
gboolean meta_prefs_bell_is_audible (void)
MetaVisualBellType meta_prefs_get_visual_bell_type (void)
void meta_prefs_get_key_bindings (const MetaKeyPref **bindings, int *n_bindings)
MetaActionTitlebar meta_prefs_get_action_double_click_titlebar (void)
MetaActionTitlebar meta_prefs_get_action_middle_click_titlebar (void)
MetaActionTitlebar meta_prefs_get_action_right_click_titlebar (void)
MetaActionTitlebar meta_prefs_get_action_scroll_up_titlebar (void)
MetaActionTitlebar meta_prefs_get_action_scroll_down_titlebar (void)
gboolean meta_prefs_get_auto_raise (void)
int meta_prefs_get_auto_raise_delay (void)
gboolean meta_prefs_get_reduced_resources (void)
gboolean meta_prefs_get_mate_accessibility ()
gboolean meta_prefs_get_mate_animations ()
MetaKeyBindingAction meta_prefs_get_keybinding_action (const char *name)
void meta_prefs_get_window_binding (const char *name, unsigned int *keysym, MetaVirtualModifier *modifiers)
gboolean meta_prefs_get_compositing_manager (void)
gboolean meta_prefs_get_compositing_fast_alt_tab (void)
gboolean meta_prefs_get_center_new_windows (void)
gboolean meta_prefs_get_allow_tiling ()
gboolean meta_prefs_get_allow_top_tiling ()
gboolean meta_prefs_get_allow_tile_cycling ()
guint meta_prefs_get_mouse_button_resize (void)
guint meta_prefs_get_mouse_button_menu (void)
gboolean meta_prefs_show_tab_border (void)
gboolean meta_prefs_get_force_fullscreen (void)
MetaPlacementMode meta_prefs_get_placement_mode (void)
void meta_prefs_set_force_compositing_manager (gboolean whether)
void meta_prefs_set_compositing_fast_alt_tab (gboolean whether)
void meta_prefs_set_center_new_windows (gboolean whether)
void meta_prefs_set_force_fullscreen (gboolean whether)
Variables
gboolean(* preference_update_handler [])(const gchar *, GSettings *)
Macro Definition Documentation
_BINDINGS_DEFINED_CONSTANTS
#define _BINDINGS_DEFINED_CONSTANTS 1
BINDING_IS_REVERSED
#define BINDING_IS_REVERSED 0x04
BINDING_PER_WINDOW
#define BINDING_PER_WINDOW 0x01
Referenced by keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), and keybind().
BINDING_REVERSES
#define BINDING_REVERSES 0x02
Referenced by keybind(), keybind(), keybind(), keybind(), keybind(), keybind(), and keybind().
KEY_COMMAND_PREFIX
#define KEY_COMMAND_PREFIX "command-"
Definition at line 59 of file prefs.c.
Referenced by meta_prefs_get_settings_key_for_command().
KEY_COMMAND_SCHEMA
#define KEY_COMMAND_SCHEMA "org.mate.Marco.keybinding-commands"
Definition at line 58 of file prefs.c.
Referenced by meta_prefs_init().
KEY_GENERAL_ALT_TAB_EXPAND_TO_FIT_TITLE
#define KEY_GENERAL_ALT_TAB_EXPAND_TO_FIT_TITLE "alt-tab-expand-to-fit-title"
Definition at line 56 of file prefs.c.
KEY_GENERAL_ALT_TAB_MAX_COLUMNS
#define KEY_GENERAL_ALT_TAB_MAX_COLUMNS "alt-tab-max-columns"
Definition at line 54 of file prefs.c.
KEY_GENERAL_ALT_TAB_RAISE_WINDOWS
#define KEY_GENERAL_ALT_TAB_RAISE_WINDOWS "alt-tab-raise-windows"
Definition at line 55 of file prefs.c.
KEY_GENERAL_CENTER_NEW_WINDOWS
#define KEY_GENERAL_CENTER_NEW_WINDOWS "center-new-windows"
Definition at line 52 of file prefs.c.
Referenced by meta_prefs_set_center_new_windows().
KEY_GENERAL_COMPOSITOR
#define KEY_GENERAL_COMPOSITOR "compositing-manager"
Definition at line 50 of file prefs.c.
KEY_GENERAL_COMPOSITOR_FAST_ALT_TAB
#define KEY_GENERAL_COMPOSITOR_FAST_ALT_TAB "compositing-fast-alt-tab"
Definition at line 51 of file prefs.c.
Referenced by meta_prefs_set_compositing_fast_alt_tab().
KEY_GENERAL_ICON_SIZE
#define KEY_GENERAL_ICON_SIZE "icon-size"
Definition at line 53 of file prefs.c.
KEY_GENERAL_NUM_WORKSPACES
#define KEY_GENERAL_NUM_WORKSPACES "num-workspaces"
Definition at line 49 of file prefs.c.
Referenced by meta_prefs_set_num_workspaces().
KEY_GENERAL_SCHEMA
#define KEY_GENERAL_SCHEMA "org.mate.Marco.general"
Definition at line 47 of file prefs.c.
Referenced by meta_prefs_init().
KEY_GENERAL_TITLEBAR_FONT
#define KEY_GENERAL_TITLEBAR_FONT "titlebar-font"
Definition at line 48 of file prefs.c.
KEY_MATE_INTERFACE_ACCESSIBILITY
#define KEY_MATE_INTERFACE_ACCESSIBILITY "accessibility"
Definition at line 69 of file prefs.c.
Referenced by meta_prefs_init().
KEY_MATE_INTERFACE_ENABLE_ANIMATIONS
#define KEY_MATE_INTERFACE_ENABLE_ANIMATIONS "enable-animations"
Definition at line 70 of file prefs.c.
Referenced by meta_prefs_init().
KEY_MATE_INTERFACE_SCHEMA
#define KEY_MATE_INTERFACE_SCHEMA "org.mate.interface"
Definition at line 68 of file prefs.c.
Referenced by meta_prefs_init().
KEY_MATE_MOUSE_CURSOR_SIZE
#define KEY_MATE_MOUSE_CURSOR_SIZE "cursor-size"
Definition at line 77 of file prefs.c.
Referenced by meta_prefs_init().
KEY_MATE_MOUSE_CURSOR_THEME
#define KEY_MATE_MOUSE_CURSOR_THEME "cursor-theme"
Definition at line 76 of file prefs.c.
Referenced by meta_prefs_init().
KEY_MATE_MOUSE_SCHEMA
#define KEY_MATE_MOUSE_SCHEMA "org.mate.peripherals-mouse"
Definition at line 75 of file prefs.c.
Referenced by meta_prefs_init().
KEY_MATE_TERMINAL_COMMAND
#define KEY_MATE_TERMINAL_COMMAND "exec"
Definition at line 73 of file prefs.c.
Referenced by meta_prefs_get_settings_key_for_terminal_command(), and meta_prefs_init().
KEY_MATE_TERMINAL_SCHEMA
#define KEY_MATE_TERMINAL_SCHEMA "org.mate.applications-terminal"
Definition at line 72 of file prefs.c.
Referenced by meta_prefs_init().
KEY_SCREEN_BINDINGS_SCHEMA
#define KEY_SCREEN_BINDINGS_SCHEMA "org.mate.Marco.global-keybindings"
Definition at line 61 of file prefs.c.
Referenced by meta_prefs_init().
KEY_WINDOW_BINDINGS_SCHEMA
#define KEY_WINDOW_BINDINGS_SCHEMA "org.mate.Marco.window-keybindings"
Definition at line 63 of file prefs.c.
Referenced by meta_prefs_init().
KEY_WORKSPACE_NAME_PREFIX
#define KEY_WORKSPACE_NAME_PREFIX "name-"
Definition at line 66 of file prefs.c.
KEY_WORKSPACE_NAME_SCHEMA
#define KEY_WORKSPACE_NAME_SCHEMA "org.mate.Marco.workspace-names"
Definition at line 65 of file prefs.c.
Referenced by meta_prefs_init().
keybind
#define keybind (name, handler, param, flags)
Value:
{ #name, NULL, !!(flags & BINDING_REVERSES), !!(flags & BINDING_PER_WINDOW) },
Definition at line 1784 of file prefs.c.
MAX_REASONABLE_AUTO_RAISE_DELAY
#define MAX_REASONABLE_AUTO_RAISE_DELAY 10000
Definition at line 1615 of file prefs.c.
MAX_REASONABLE_WORKSPACES
#define MAX_REASONABLE_WORKSPACES 36
Definition at line 37 of file prefs.c.
Referenced by meta_prefs_change_workspace_name(), meta_prefs_get_workspace_name(), and meta_prefs_set_num_workspaces().
METAINTPREFERENCE_NO_CHANGE_ON_DESTROY
#define METAINTPREFERENCE_NO_CHANGE_ON_DESTROY G_MININT
Definition at line 275 of file prefs.c.
REVERSES_AND_REVERSED
#define REVERSES_AND_REVERSED (BINDING_REVERSES | BINDING_IS_REVERSED)
SETTINGS
#define SETTINGS (s)
Value:
g_hash_table_lookup (settings_schemas, (s))
Definition at line 79 of file prefs.c.
Function Documentation
meta_prefs_add_listener()
void meta_prefs_add_listener (MetaPrefsChangedFunc func, gpointer data)
Definition at line 841 of file prefs.c.
References data.
Referenced by main(), meta_display_init_keys(), meta_screen_new(), and meta_window_ensure_frame().
meta_prefs_bell_is_audible()
gboolean meta_prefs_bell_is_audible (void)
Definition at line 2301 of file prefs.c.
meta_prefs_change_workspace_name()
void meta_prefs_change_workspace_name (int i, const char * name)
Definition at line 2241 of file prefs.c.
References key, MAX_REASONABLE_WORKSPACES, META_DEBUG_PREFS, name, and NULL.
Referenced by meta_screen_update_workspace_names().
meta_prefs_get_action_double_click_titlebar()
MetaActionTitlebar meta_prefs_get_action_double_click_titlebar (void)
Definition at line 2322 of file prefs.c.
meta_prefs_get_action_middle_click_titlebar()
MetaActionTitlebar meta_prefs_get_action_middle_click_titlebar (void)
Definition at line 2328 of file prefs.c.
meta_prefs_get_action_right_click_titlebar()
MetaActionTitlebar meta_prefs_get_action_right_click_titlebar (void)
Definition at line 2334 of file prefs.c.
meta_prefs_get_action_scroll_down_titlebar()
MetaActionTitlebar meta_prefs_get_action_scroll_down_titlebar (void)
Definition at line 2346 of file prefs.c.
meta_prefs_get_action_scroll_up_titlebar()
MetaActionTitlebar meta_prefs_get_action_scroll_up_titlebar (void)
Definition at line 2340 of file prefs.c.
meta_prefs_get_allow_tile_cycling()
gboolean meta_prefs_get_allow_tile_cycling (void)
Definition at line 2475 of file prefs.c.
meta_prefs_get_allow_tiling()
gboolean meta_prefs_get_allow_tiling (void)
Definition at line 2463 of file prefs.c.
meta_prefs_get_allow_top_tiling()
gboolean meta_prefs_get_allow_top_tiling (void)
Definition at line 2469 of file prefs.c.
meta_prefs_get_alt_tab_expand_to_fit_title()
gboolean meta_prefs_get_alt_tab_expand_to_fit_title (void)
Definition at line 1182 of file prefs.c.
Referenced by meta_screen_ensure_tab_popup().
meta_prefs_get_alt_tab_max_columns()
int meta_prefs_get_alt_tab_max_columns (void)
Definition at line 1176 of file prefs.c.
Referenced by meta_screen_ensure_tab_popup().
meta_prefs_get_alt_tab_raise_windows()
gboolean meta_prefs_get_alt_tab_raise_windows (void)
Definition at line 1188 of file prefs.c.
meta_prefs_get_application_based()
gboolean meta_prefs_get_application_based (void)
Definition at line 1602 of file prefs.c.
References FALSE.
meta_prefs_get_attach_modal_dialogs()
gboolean meta_prefs_get_attach_modal_dialogs (void)
Definition at line 1134 of file prefs.c.
Referenced by meta_core_get(), and meta_window_appears_focused().
meta_prefs_get_auto_raise()
gboolean meta_prefs_get_auto_raise (void)
Definition at line 2352 of file prefs.c.
Referenced by meta_workspace_focus_default_window().
meta_prefs_get_auto_raise_delay()
int meta_prefs_get_auto_raise_delay (void)
Definition at line 2358 of file prefs.c.
Referenced by meta_display_queue_autoraise_callback().
meta_prefs_get_button_layout()
void meta_prefs_get_button_layout (MetaButtonLayout * button_layout_p)
Definition at line 2289 of file prefs.c.
meta_prefs_get_center_new_windows()
gboolean meta_prefs_get_center_new_windows (void)
Definition at line 2457 of file prefs.c.
Referenced by meta_window_place().
meta_prefs_get_command()
const char * meta_prefs_get_command (int i)
Definition at line 2106 of file prefs.c.
References MAX_COMMANDS, and NULL.
meta_prefs_get_compositing_fast_alt_tab()
gboolean meta_prefs_get_compositing_fast_alt_tab (void)
Definition at line 2451 of file prefs.c.
Referenced by meta_screen_ensure_tab_popup().
meta_prefs_get_compositing_manager()
gboolean meta_prefs_get_compositing_manager (void)
Definition at line 2443 of file prefs.c.
Referenced by meta_frames_apply_shapes(), and meta_screen_ensure_tab_popup().
meta_prefs_get_cursor_size()
int meta_prefs_get_cursor_size (void)
Definition at line 1158 of file prefs.c.
meta_prefs_get_cursor_theme()
const char * meta_prefs_get_cursor_theme (void)
Definition at line 1152 of file prefs.c.
meta_prefs_get_disable_workarounds()
gboolean meta_prefs_get_disable_workarounds (void)
Definition at line 1610 of file prefs.c.
Referenced by meta_window_configure_request(), meta_window_move_resize_request(), and meta_window_place().
meta_prefs_get_dynamic_workspaces()
gboolean meta_prefs_get_dynamic_workspaces (void)
Definition at line 1590 of file prefs.c.
Referenced by meta_screen_update_dynamic_workspaces().
meta_prefs_get_focus_mode()
MetaFocusMode meta_prefs_get_focus_mode (void)
Definition at line 1122 of file prefs.c.
Referenced by meta_display_grab_focus_window_button(), meta_window_notify_focus(), and meta_workspace_focus_default_window().
meta_prefs_get_focus_new_windows()
MetaFocusNewWindows meta_prefs_get_focus_new_windows (void)
Definition at line 1128 of file prefs.c.
Referenced by meta_window_set_user_time().
meta_prefs_get_force_fullscreen()
gboolean meta_prefs_get_force_fullscreen (void)
Definition at line 2499 of file prefs.c.
Referenced by meta_window_move_resize_request().
meta_prefs_get_icon_size()
int meta_prefs_get_icon_size (void)
Definition at line 1167 of file prefs.c.
Referenced by meta_ui_get_default_window_icon(), meta_ui_get_window_icon_from_desktop_id(), and meta_window_update_icon_now().
meta_prefs_get_key_bindings()
void meta_prefs_get_key_bindings (const MetaKeyPref ** bindings, int * n_bindings)
Definition at line 2313 of file prefs.c.
References int().
meta_prefs_get_keybinding_action()
MetaKeyBindingAction meta_prefs_get_keybinding_action (const char * name)
Definition at line 2382 of file prefs.c.
References META_KEYBINDING_ACTION_NONE, and name.
meta_prefs_get_mate_accessibility()
gboolean meta_prefs_get_mate_accessibility (void)
Definition at line 2370 of file prefs.c.
Referenced by meta_display_begin_grab_op().
meta_prefs_get_mate_animations()
gboolean meta_prefs_get_mate_animations (void)
Definition at line 2376 of file prefs.c.
meta_prefs_get_mouse_button_menu()
guint meta_prefs_get_mouse_button_menu (void)
Definition at line 2487 of file prefs.c.
meta_prefs_get_mouse_button_mods()
MetaVirtualModifier meta_prefs_get_mouse_button_mods (void)
Definition at line 1116 of file prefs.c.
meta_prefs_get_mouse_button_resize()
guint meta_prefs_get_mouse_button_resize (void)
Definition at line 2481 of file prefs.c.
meta_prefs_get_num_workspaces()
int meta_prefs_get_num_workspaces (void)
Definition at line 1584 of file prefs.c.
meta_prefs_get_placement_mode()
MetaPlacementMode meta_prefs_get_placement_mode (void)
Definition at line 2505 of file prefs.c.
Referenced by meta_window_place().
meta_prefs_get_raise_on_click()
gboolean meta_prefs_get_raise_on_click (void)
Definition at line 1140 of file prefs.c.
Referenced by meta_core_maximize(), meta_core_show_window_menu(), meta_core_toggle_maximize(), meta_core_toggle_maximize_horizontally(), meta_core_toggle_maximize_vertically(), meta_core_unmaximize(), meta_core_user_lower_and_unfocus(), meta_display_begin_grab_op(), meta_display_check_threshold_reached(), meta_display_end_grab_op(), meta_window_client_message(), and meta_window_notify_focus().
meta_prefs_get_reduced_resources()
gboolean meta_prefs_get_reduced_resources (void)
Definition at line 2364 of file prefs.c.
Referenced by meta_display_begin_grab_op().
meta_prefs_get_settings_key_for_command()
char * meta_prefs_get_settings_key_for_command (int i)
Definition at line 2114 of file prefs.c.
References AREA_SCREENSHOT_COMMAND_IDX, key, KEY_COMMAND_PREFIX, SCREENSHOT_COMMAND_IDX, and WIN_SCREENSHOT_COMMAND_IDX.
meta_prefs_get_settings_key_for_terminal_command()
const char * meta_prefs_get_settings_key_for_terminal_command (void)
Definition at line 2144 of file prefs.c.
References KEY_MATE_TERMINAL_COMMAND.
meta_prefs_get_terminal_command()
const char * meta_prefs_get_terminal_command (void)
Definition at line 2138 of file prefs.c.
meta_prefs_get_theme()
const char * meta_prefs_get_theme (void)
Definition at line 1146 of file prefs.c.
Referenced by main().
meta_prefs_get_titlebar_font()
const PangoFontDescription * meta_prefs_get_titlebar_font (void)
Definition at line 1575 of file prefs.c.
References NULL.
Referenced by meta_ui_theme_get_frame_borders().
meta_prefs_get_visual_bell()
gboolean meta_prefs_get_visual_bell (void)
Definition at line 2295 of file prefs.c.
meta_prefs_get_visual_bell_type()
MetaVisualBellType meta_prefs_get_visual_bell_type (void)
Definition at line 2307 of file prefs.c.
meta_prefs_get_window_binding()
void meta_prefs_get_window_binding (const char * name, unsigned int * keysym, MetaVirtualModifier * modifiers)
Definition at line 2403 of file prefs.c.
References MetaKeyCombo::keysym, MetaKeyCombo::modifiers, and name.
Referenced by meta_core_get_menu_accelerator().
meta_prefs_get_workspace_name()
const char * meta_prefs_get_workspace_name (int i)
Definition at line 2227 of file prefs.c.
References MAX_REASONABLE_WORKSPACES, META_DEBUG_PREFS, and NULL.
Referenced by meta_workspace_get_name().
meta_prefs_get_wrap_style()
MetaWrapStyle meta_prefs_get_wrap_style (void)
Definition at line 1596 of file prefs.c.
Referenced by meta_workspace_get_neighbor().
meta_prefs_init()
void meta_prefs_init (void)
Definition at line 956 of file prefs.c.
References KEY_COMMAND_SCHEMA, KEY_GENERAL_SCHEMA, KEY_MATE_INTERFACE_ACCESSIBILITY, KEY_MATE_INTERFACE_ENABLE_ANIMATIONS, KEY_MATE_INTERFACE_SCHEMA, KEY_MATE_MOUSE_CURSOR_SIZE, KEY_MATE_MOUSE_CURSOR_THEME, KEY_MATE_MOUSE_SCHEMA, KEY_MATE_TERMINAL_COMMAND, KEY_MATE_TERMINAL_SCHEMA, KEY_SCREEN_BINDINGS_SCHEMA, KEY_WINDOW_BINDINGS_SCHEMA, KEY_WORKSPACE_NAME_SCHEMA, and NULL.
Referenced by main().
meta_prefs_is_in_skip_list()
gboolean meta_prefs_is_in_skip_list (char * class)
Definition at line 1194 of file prefs.c.
References FALSE, item, and TRUE.
Referenced by meta_screen_show_desktop().
meta_prefs_remove_listener()
void meta_prefs_remove_listener (MetaPrefsChangedFunc func, gpointer data)
Definition at line 854 of file prefs.c.
References data, meta_bug(), and NULL.
Referenced by meta_display_close(), meta_display_shutdown_keys(), meta_screen_free(), and meta_window_destroy_frame().
meta_prefs_set_center_new_windows()
void meta_prefs_set_center_new_windows (gboolean whether)
Definition at line 2526 of file prefs.c.
References KEY_GENERAL_CENTER_NEW_WINDOWS.
meta_prefs_set_compositing_fast_alt_tab()
void meta_prefs_set_compositing_fast_alt_tab (gboolean whether)
Definition at line 2518 of file prefs.c.
References KEY_GENERAL_COMPOSITOR_FAST_ALT_TAB.
meta_prefs_set_force_compositing_manager()
void meta_prefs_set_force_compositing_manager (gboolean whether)
Sets whether the compositor is turned on.
Parameters
whether TRUE to turn on, FALSE to turn off
Definition at line 2511 of file prefs.c.
References TRUE.
Referenced by main().
meta_prefs_set_force_fullscreen()
void meta_prefs_set_force_fullscreen (gboolean whether)
Definition at line 2534 of file prefs.c.
Referenced by main().
meta_prefs_set_num_workspaces()
void meta_prefs_set_num_workspaces (int n_workspaces)
Definition at line 1771 of file prefs.c.
References KEY_GENERAL_NUM_WORKSPACES, and MAX_REASONABLE_WORKSPACES.
meta_prefs_show_tab_border()
gboolean meta_prefs_show_tab_border (void)
Definition at line 2493 of file prefs.c.
Referenced by meta_screen_ensure_tab_popup().
Variable Documentation
preference_update_handler
gboolean(* preference_update_handler[])(const gchar *, GSettings *) (const gchar * , GSettings *)
Initial value:
= {
  handle_preference_update_enum,
  handle_preference_update_bool,
  handle_preference_update_string,
  handle_preference_update_int,
  NULL
}
Definition at line 1010 of file prefs.c.