MATE Desktop Environment: prefs-dialog.h File Reference
prefs-dialog.h File Reference
#include "sensors-applet.h"
Classes
struct PrefsDialog
Functions
void prefs_dialog_open (SensorsApplet *sensors_applet)
void prefs_dialog_close (SensorsApplet *sensors_applet)
Function Documentation
prefs_dialog_close()
void prefs_dialog_close (SensorsApplet * sensors_applet)
Definition at line 35 of file prefs-dialog.c.
References PrefsDialog::dialog, NULL, _SensorsApplet::prefs_dialog, _SensorsApplet::sensors, sensors_applet_settings_save_sensors(), sensors_applet_update_active_sensors(), _SensorsApplet::settings, TIMEOUT, and _SensorsApplet::timeout_id.
Referenced by prefs_dialog_open().
prefs_dialog_open()
void prefs_dialog_open (SensorsApplet * sensors_applet)
Definition at line 393 of file prefs-dialog.c.
References _, PrefsDialog::buttons_box, PrefsDialog::dialog, DISPLAY_GRAPH, PrefsDialog::display_header, DISPLAY_ICON, DISPLAY_MODE, PrefsDialog::display_mode_combo_box, PrefsDialog::display_mode_label, DISPLAY_NOTIFICATIONS, DISPLAY_VALUE, ENABLE_COLUMN, PrefsDialog::enable_column, PrefsDialog::enable_renderer, FALSE, PrefsDialog::globals_grid, GRAPH_SIZE, PrefsDialog::graph_size_adjust, PrefsDialog::graph_size_label, PrefsDialog::graph_size_spinbutton, HIDE_UNITS, PrefsDialog::icon_column, ICON_PIXBUF_COLUMN, PrefsDialog::icon_renderer, ID_COLUMN, PrefsDialog::id_column, PrefsDialog::id_renderer, label, LABEL_COLUMN, PrefsDialog::label_column, PrefsDialog::label_renderer, LAYOUT_MODE, PrefsDialog::layout_mode_combo_box, PrefsDialog::layout_mode_label, PrefsDialog::notebook, NULL, _SensorsApplet::prefs_dialog, prefs_dialog_close(), PrefsDialog::scrolled_window, _SensorsApplet::selection, PrefsDialog::sensor_config_button, PrefsDialog::sensor_config_hbox, PrefsDialog::sensor_down_button, PrefsDialog::sensor_up_button, _SensorsApplet::sensors, PrefsDialog::sensors_applet, PrefsDialog::sensors_hbox, PrefsDialog::sensors_vbox, _SensorsApplet::settings, PrefsDialog::show_units, PrefsDialog::size_group, TEMPERATURE_SCALE, PrefsDialog::temperature_scale_combo_box, PrefsDialog::temperature_scale_label, TIMEOUT, PrefsDialog::timeout_adjust, _SensorsApplet::timeout_id, PrefsDialog::timeout_label, PrefsDialog::timeout_spinbutton, TRUE, PrefsDialog::update_header, PrefsDialog::view, and VISIBLE_COLUMN.