MATE Desktop Environment: prefs.h File Reference
prefs.h File Reference
#include "common.h"
#include <pango/pango-font.h>
Classes
struct MetaKeyCombo
struct MetaKeyPref
Macros
#define MAX_COMMANDS (32 + NUM_EXTRA_COMMANDS)
#define NUM_EXTRA_COMMANDS 3
#define SCREENSHOT_COMMAND_IDX (MAX_COMMANDS - 3)
#define WIN_SCREENSHOT_COMMAND_IDX (MAX_COMMANDS - 2)
#define AREA_SCREENSHOT_COMMAND_IDX (MAX_COMMANDS - 1)
Typedefs
typedef void(* MetaPrefsChangedFunc) (MetaPreference pref, gpointer data)
typedef enum _MetaKeyBindingAction MetaKeyBindingAction
Enumerations
enum MetaPreference {
META_PREF_MOUSE_BUTTON_MODS , META_PREF_FOCUS_MODE , META_PREF_FOCUS_NEW_WINDOWS , META_PREF_ATTACH_MODAL_DIALOGS ,
META_PREF_RAISE_ON_CLICK , META_PREF_ACTION_DOUBLE_CLICK_TITLEBAR , META_PREF_ACTION_MIDDLE_CLICK_TITLEBAR , META_PREF_ACTION_RIGHT_CLICK_TITLEBAR ,
META_PREF_ACTION_SCROLL_UP_TITLEBAR , META_PREF_ACTION_SCROLL_DOWN_TITLEBAR , META_PREF_AUTO_RAISE , META_PREF_AUTO_RAISE_DELAY ,
META_PREF_THEME , META_PREF_TITLEBAR_FONT , META_PREF_NUM_WORKSPACES , META_PREF_DYNAMIC_WORKSPACES ,
META_PREF_WRAP_STYLE , META_PREF_APPLICATION_BASED , META_PREF_KEYBINDINGS , META_PREF_DISABLE_WORKAROUNDS ,
META_PREF_COMMANDS , META_PREF_TERMINAL_COMMAND , META_PREF_BUTTON_LAYOUT , META_PREF_WORKSPACE_NAMES ,
META_PREF_VISUAL_BELL , META_PREF_AUDIBLE_BELL , META_PREF_VISUAL_BELL_TYPE , META_PREF_REDUCED_RESOURCES ,
META_PREF_MATE_ACCESSIBILITY , META_PREF_MATE_ANIMATIONS , META_PREF_CURSOR_THEME , META_PREF_CURSOR_SIZE ,
META_PREF_ICON_SIZE , META_PREF_ALT_TAB_MAX_COLUMNS , META_PREF_ALT_TAB_RAISE_WINDOWS , META_PREF_ALT_TAB_EXPAND_TO_FIT_TITLE ,
META_PREF_COMPOSITING_MANAGER , META_PREF_COMPOSITING_FAST_ALT_TAB , META_PREF_RESIZE_WITH_RIGHT_BUTTON , META_PREF_SHOW_TAB_BORDER ,
META_PREF_CENTER_NEW_WINDOWS , META_PREF_ALLOW_TILING , META_PREF_ALLOW_TOP_TILING , META_PREF_ALLOW_TILE_CYCLING ,
META_PREF_FORCE_FULLSCREEN , META_PREF_PLACEMENT_MODE , META_PREF_SHOW_DESKTOP_SKIP_LIST
}
enum _MetaKeyBindingAction {
META_KEYBINDING_ACTION_NONE = -1 , META_KEYBINDING_ACTION_WORKSPACE_1 , META_KEYBINDING_ACTION_WORKSPACE_2 , META_KEYBINDING_ACTION_WORKSPACE_3 ,
META_KEYBINDING_ACTION_WORKSPACE_4 , META_KEYBINDING_ACTION_WORKSPACE_5 , META_KEYBINDING_ACTION_WORKSPACE_6 , META_KEYBINDING_ACTION_WORKSPACE_7 ,
META_KEYBINDING_ACTION_WORKSPACE_8 , META_KEYBINDING_ACTION_WORKSPACE_9 , META_KEYBINDING_ACTION_WORKSPACE_10 , META_KEYBINDING_ACTION_WORKSPACE_11 ,
META_KEYBINDING_ACTION_WORKSPACE_12 , META_KEYBINDING_ACTION_WORKSPACE_LEFT , META_KEYBINDING_ACTION_WORKSPACE_RIGHT , META_KEYBINDING_ACTION_WORKSPACE_UP ,
META_KEYBINDING_ACTION_WORKSPACE_DOWN , META_KEYBINDING_ACTION_WORKSPACE_MOVE_LEFT , META_KEYBINDING_ACTION_WORKSPACE_MOVE_RIGHT , META_KEYBINDING_ACTION_WORKSPACE_MOVE_UP ,
META_KEYBINDING_ACTION_WORKSPACE_MOVE_DOWN , META_KEYBINDING_ACTION_SWITCH_GROUP , META_KEYBINDING_ACTION_SWITCH_GROUP_BACKWARD , META_KEYBINDING_ACTION_SWITCH_WINDOWS ,
META_KEYBINDING_ACTION_SWITCH_WINDOWS_BACKWARD , META_KEYBINDING_ACTION_SWITCH_WINDOWS_ALL , META_KEYBINDING_ACTION_SWITCH_WINDOWS_ALL_BACKWARD , META_KEYBINDING_ACTION_SWITCH_PANELS ,
META_KEYBINDING_ACTION_SWITCH_PANELS_BACKWARD , META_KEYBINDING_ACTION_CYCLE_GROUP , META_KEYBINDING_ACTION_CYCLE_GROUP_BACKWARD , META_KEYBINDING_ACTION_CYCLE_WINDOWS ,
META_KEYBINDING_ACTION_CYCLE_WINDOWS_BACKWARD , META_KEYBINDING_ACTION_CYCLE_PANELS , META_KEYBINDING_ACTION_CYCLE_PANELS_BACKWARD , META_KEYBINDING_ACTION_SHOW_DESKTOP ,
META_KEYBINDING_ACTION_PANEL_MAIN_MENU , META_KEYBINDING_ACTION_PANEL_RUN_DIALOG , META_KEYBINDING_ACTION_COMMAND_1 , META_KEYBINDING_ACTION_COMMAND_2 ,
META_KEYBINDING_ACTION_COMMAND_3 , META_KEYBINDING_ACTION_COMMAND_4 , META_KEYBINDING_ACTION_COMMAND_5 , META_KEYBINDING_ACTION_COMMAND_6 ,
META_KEYBINDING_ACTION_COMMAND_7 , META_KEYBINDING_ACTION_COMMAND_8 , META_KEYBINDING_ACTION_COMMAND_9 , META_KEYBINDING_ACTION_COMMAND_10 ,
META_KEYBINDING_ACTION_COMMAND_11 , META_KEYBINDING_ACTION_COMMAND_12
}
enum MetaVisualBellType { META_VISUAL_BELL_INVALID = 0 , META_VISUAL_BELL_FULLSCREEN_FLASH , META_VISUAL_BELL_FRAME_FLASH }
Functions
void meta_prefs_add_listener (MetaPrefsChangedFunc func, gpointer data)
void meta_prefs_remove_listener (MetaPrefsChangedFunc func, gpointer data)
void meta_prefs_init (void)
const char * meta_preference_to_string (MetaPreference pref)
MetaVirtualModifier meta_prefs_get_mouse_button_mods (void)
guint meta_prefs_get_mouse_button_resize (void)
guint meta_prefs_get_mouse_button_menu (void)
MetaFocusMode meta_prefs_get_focus_mode (void)
MetaFocusNewWindows meta_prefs_get_focus_new_windows (void)
gboolean meta_prefs_get_attach_modal_dialogs (void)
gboolean meta_prefs_get_raise_on_click (void)
const char * meta_prefs_get_theme (void)
const PangoFontDescription * meta_prefs_get_titlebar_font (void)
int meta_prefs_get_num_workspaces (void)
gboolean meta_prefs_get_dynamic_workspaces (void)
gboolean meta_prefs_get_application_based (void)
gboolean meta_prefs_get_disable_workarounds (void)
gboolean meta_prefs_get_auto_raise (void)
int meta_prefs_get_auto_raise_delay (void)
MetaWrapStyle meta_prefs_get_wrap_style (void)
gboolean meta_prefs_get_reduced_resources (void)
gboolean meta_prefs_get_mate_accessibility (void)
gboolean meta_prefs_get_mate_animations (void)
gboolean meta_prefs_get_allow_tiling (void)
gboolean meta_prefs_get_allow_top_tiling (void)
gboolean meta_prefs_get_allow_tile_cycling (void)
const char * meta_prefs_get_command (int i)
char * meta_prefs_get_settings_key_for_command (int i)
const char * meta_prefs_get_terminal_command (void)
const char * meta_prefs_get_settings_key_for_terminal_command (void)
void meta_prefs_get_button_layout (MetaButtonLayout *button_layout)
MetaActionTitlebar meta_prefs_get_action_double_click_titlebar (void)
MetaActionTitlebar meta_prefs_get_action_middle_click_titlebar (void)
MetaActionTitlebar meta_prefs_get_action_right_click_titlebar (void)
MetaActionTitlebar meta_prefs_get_action_scroll_up_titlebar (void)
MetaActionTitlebar meta_prefs_get_action_scroll_down_titlebar (void)
MetaPlacementMode meta_prefs_get_placement_mode (void)
void meta_prefs_set_num_workspaces (int n_workspaces)
const char * meta_prefs_get_workspace_name (int i)
void meta_prefs_change_workspace_name (int i, const char *name)
const char * meta_prefs_get_cursor_theme (void)
int meta_prefs_get_cursor_size (void)
int meta_prefs_get_icon_size (void)
int meta_prefs_get_alt_tab_max_columns (void)
gboolean meta_prefs_get_alt_tab_expand_to_fit_title (void)
gboolean meta_prefs_get_alt_tab_raise_windows (void)
gboolean meta_prefs_get_compositing_manager (void)
gboolean meta_prefs_get_compositing_fast_alt_tab (void)
gboolean meta_prefs_get_center_new_windows (void)
gboolean meta_prefs_get_force_fullscreen (void)
gboolean meta_prefs_show_tab_border (void)
gboolean meta_prefs_is_in_skip_list (char *class)
void meta_prefs_set_force_compositing_manager (gboolean whether)
void meta_prefs_set_compositing_fast_alt_tab (gboolean whether)
void meta_prefs_set_center_new_windows (gboolean whether)
void meta_prefs_set_force_fullscreen (gboolean whether)
void meta_prefs_get_key_bindings (const MetaKeyPref **bindings, int *n_bindings)
MetaKeyBindingAction meta_prefs_get_keybinding_action (const char *name)
void meta_prefs_get_window_binding (const char *name, unsigned int *keysym, MetaVirtualModifier *modifiers)
gboolean meta_prefs_get_visual_bell (void)
gboolean meta_prefs_bell_is_audible (void)
MetaVisualBellType meta_prefs_get_visual_bell_type (void)
Macro Definition Documentation
AREA_SCREENSHOT_COMMAND_IDX
#define AREA_SCREENSHOT_COMMAND_IDX (MAX_COMMANDS - 1)
Definition at line 36 of file prefs.h.
Referenced by meta_prefs_get_settings_key_for_command().
MAX_COMMANDS
#define MAX_COMMANDS (32 + NUM_EXTRA_COMMANDS)
Definition at line 32 of file prefs.h.
Referenced by meta_prefs_get_command().
NUM_EXTRA_COMMANDS
#define NUM_EXTRA_COMMANDS 3
Definition at line 33 of file prefs.h.
SCREENSHOT_COMMAND_IDX
#define SCREENSHOT_COMMAND_IDX (MAX_COMMANDS - 3)
Definition at line 34 of file prefs.h.
Referenced by meta_prefs_get_settings_key_for_command().
WIN_SCREENSHOT_COMMAND_IDX
#define WIN_SCREENSHOT_COMMAND_IDX (MAX_COMMANDS - 2)
Definition at line 35 of file prefs.h.
Referenced by meta_prefs_get_settings_key_for_command().
Typedef Documentation
MetaKeyBindingAction
typedef enum _MetaKeyBindingAction MetaKeyBindingAction
MetaPrefsChangedFunc
typedef void(* MetaPrefsChangedFunc) (MetaPreference pref, gpointer data)
Definition at line 89 of file prefs.h.
Enumeration Type Documentation
_MetaKeyBindingAction
enum _MetaKeyBindingAction
Enumerator
META_KEYBINDING_ACTION_NONE
META_KEYBINDING_ACTION_WORKSPACE_1
META_KEYBINDING_ACTION_WORKSPACE_2
META_KEYBINDING_ACTION_WORKSPACE_3
META_KEYBINDING_ACTION_WORKSPACE_4
META_KEYBINDING_ACTION_WORKSPACE_5
META_KEYBINDING_ACTION_WORKSPACE_6
META_KEYBINDING_ACTION_WORKSPACE_7
META_KEYBINDING_ACTION_WORKSPACE_8
META_KEYBINDING_ACTION_WORKSPACE_9
META_KEYBINDING_ACTION_WORKSPACE_10
META_KEYBINDING_ACTION_WORKSPACE_11
META_KEYBINDING_ACTION_WORKSPACE_12
META_KEYBINDING_ACTION_WORKSPACE_LEFT
META_KEYBINDING_ACTION_WORKSPACE_RIGHT
META_KEYBINDING_ACTION_WORKSPACE_UP
META_KEYBINDING_ACTION_WORKSPACE_DOWN
META_KEYBINDING_ACTION_WORKSPACE_MOVE_LEFT
META_KEYBINDING_ACTION_WORKSPACE_MOVE_RIGHT
META_KEYBINDING_ACTION_WORKSPACE_MOVE_UP
META_KEYBINDING_ACTION_WORKSPACE_MOVE_DOWN
META_KEYBINDING_ACTION_SWITCH_GROUP
META_KEYBINDING_ACTION_SWITCH_GROUP_BACKWARD
META_KEYBINDING_ACTION_SWITCH_WINDOWS
META_KEYBINDING_ACTION_SWITCH_WINDOWS_BACKWARD
META_KEYBINDING_ACTION_SWITCH_WINDOWS_ALL
META_KEYBINDING_ACTION_SWITCH_WINDOWS_ALL_BACKWARD
META_KEYBINDING_ACTION_SWITCH_PANELS
META_KEYBINDING_ACTION_SWITCH_PANELS_BACKWARD
META_KEYBINDING_ACTION_CYCLE_GROUP
META_KEYBINDING_ACTION_CYCLE_GROUP_BACKWARD
META_KEYBINDING_ACTION_CYCLE_WINDOWS
META_KEYBINDING_ACTION_CYCLE_WINDOWS_BACKWARD
META_KEYBINDING_ACTION_CYCLE_PANELS
META_KEYBINDING_ACTION_CYCLE_PANELS_BACKWARD
META_KEYBINDING_ACTION_SHOW_DESKTOP
META_KEYBINDING_ACTION_PANEL_MAIN_MENU
META_KEYBINDING_ACTION_PANEL_RUN_DIALOG
META_KEYBINDING_ACTION_COMMAND_1
META_KEYBINDING_ACTION_COMMAND_2
META_KEYBINDING_ACTION_COMMAND_3
META_KEYBINDING_ACTION_COMMAND_4
META_KEYBINDING_ACTION_COMMAND_5
META_KEYBINDING_ACTION_COMMAND_6
META_KEYBINDING_ACTION_COMMAND_7
META_KEYBINDING_ACTION_COMMAND_8
META_KEYBINDING_ACTION_COMMAND_9
META_KEYBINDING_ACTION_COMMAND_10
META_KEYBINDING_ACTION_COMMAND_11
META_KEYBINDING_ACTION_COMMAND_12
Definition at line 179 of file prefs.h.
MetaPreference
enum MetaPreference
Enumerator
META_PREF_MOUSE_BUTTON_MODS
META_PREF_FOCUS_MODE
META_PREF_FOCUS_NEW_WINDOWS
META_PREF_ATTACH_MODAL_DIALOGS
META_PREF_RAISE_ON_CLICK
META_PREF_ACTION_DOUBLE_CLICK_TITLEBAR
META_PREF_ACTION_MIDDLE_CLICK_TITLEBAR
META_PREF_ACTION_RIGHT_CLICK_TITLEBAR
META_PREF_ACTION_SCROLL_UP_TITLEBAR
META_PREF_ACTION_SCROLL_DOWN_TITLEBAR
META_PREF_AUTO_RAISE
META_PREF_AUTO_RAISE_DELAY
META_PREF_THEME
META_PREF_TITLEBAR_FONT
META_PREF_NUM_WORKSPACES
META_PREF_DYNAMIC_WORKSPACES
META_PREF_WRAP_STYLE
META_PREF_APPLICATION_BASED
META_PREF_KEYBINDINGS
META_PREF_DISABLE_WORKAROUNDS
META_PREF_COMMANDS
META_PREF_TERMINAL_COMMAND
META_PREF_BUTTON_LAYOUT
META_PREF_WORKSPACE_NAMES
META_PREF_VISUAL_BELL
META_PREF_AUDIBLE_BELL
META_PREF_VISUAL_BELL_TYPE
META_PREF_REDUCED_RESOURCES
META_PREF_MATE_ACCESSIBILITY
META_PREF_MATE_ANIMATIONS
META_PREF_CURSOR_THEME
META_PREF_CURSOR_SIZE
META_PREF_ICON_SIZE
META_PREF_ALT_TAB_MAX_COLUMNS
META_PREF_ALT_TAB_RAISE_WINDOWS
META_PREF_ALT_TAB_EXPAND_TO_FIT_TITLE
META_PREF_COMPOSITING_MANAGER
META_PREF_COMPOSITING_FAST_ALT_TAB
META_PREF_RESIZE_WITH_RIGHT_BUTTON
META_PREF_SHOW_TAB_BORDER
META_PREF_CENTER_NEW_WINDOWS
META_PREF_ALLOW_TILING
META_PREF_ALLOW_TOP_TILING
META_PREF_ALLOW_TILE_CYCLING
META_PREF_FORCE_FULLSCREEN
META_PREF_PLACEMENT_MODE
META_PREF_SHOW_DESKTOP_SKIP_LIST
Definition at line 38 of file prefs.h.
MetaVisualBellType
enum MetaVisualBellType
Enumerator
META_VISUAL_BELL_INVALID
META_VISUAL_BELL_FULLSCREEN_FLASH
META_VISUAL_BELL_FRAME_FLASH
Definition at line 268 of file prefs.h.
Function Documentation
meta_preference_to_string()
const char * meta_preference_to_string (MetaPreference pref)
References name.
meta_prefs_add_listener()
void meta_prefs_add_listener (MetaPrefsChangedFunc func, gpointer data)
Definition at line 841 of file prefs.c.
References data.
Referenced by main(), meta_display_init_keys(), meta_screen_new(), and meta_window_ensure_frame().
meta_prefs_bell_is_audible()
gboolean meta_prefs_bell_is_audible (void)
Definition at line 2301 of file prefs.c.
meta_prefs_change_workspace_name()
void meta_prefs_change_workspace_name (int i, const char * name)
Definition at line 2241 of file prefs.c.
References key, MAX_REASONABLE_WORKSPACES, META_DEBUG_PREFS, name, and NULL.
Referenced by meta_screen_update_workspace_names().
meta_prefs_get_action_double_click_titlebar()
MetaActionTitlebar meta_prefs_get_action_double_click_titlebar (void)
Definition at line 2322 of file prefs.c.
meta_prefs_get_action_middle_click_titlebar()
MetaActionTitlebar meta_prefs_get_action_middle_click_titlebar (void)
Definition at line 2328 of file prefs.c.
meta_prefs_get_action_right_click_titlebar()
MetaActionTitlebar meta_prefs_get_action_right_click_titlebar (void)
Definition at line 2334 of file prefs.c.
meta_prefs_get_action_scroll_down_titlebar()
MetaActionTitlebar meta_prefs_get_action_scroll_down_titlebar (void)
Definition at line 2346 of file prefs.c.
meta_prefs_get_action_scroll_up_titlebar()
MetaActionTitlebar meta_prefs_get_action_scroll_up_titlebar (void)
Definition at line 2340 of file prefs.c.
meta_prefs_get_allow_tile_cycling()
gboolean meta_prefs_get_allow_tile_cycling (void)
Definition at line 2475 of file prefs.c.
meta_prefs_get_allow_tiling()
gboolean meta_prefs_get_allow_tiling (void)
Definition at line 2463 of file prefs.c.
meta_prefs_get_allow_top_tiling()
gboolean meta_prefs_get_allow_top_tiling (void)
Definition at line 2469 of file prefs.c.
meta_prefs_get_alt_tab_expand_to_fit_title()
gboolean meta_prefs_get_alt_tab_expand_to_fit_title (void)
Definition at line 1182 of file prefs.c.
Referenced by meta_screen_ensure_tab_popup().
meta_prefs_get_alt_tab_max_columns()
int meta_prefs_get_alt_tab_max_columns (void)
Definition at line 1176 of file prefs.c.
Referenced by meta_screen_ensure_tab_popup().
meta_prefs_get_alt_tab_raise_windows()
gboolean meta_prefs_get_alt_tab_raise_windows (void)
Definition at line 1188 of file prefs.c.
meta_prefs_get_application_based()
gboolean meta_prefs_get_application_based (void)
Definition at line 1602 of file prefs.c.
References FALSE.
meta_prefs_get_attach_modal_dialogs()
gboolean meta_prefs_get_attach_modal_dialogs (void)
Definition at line 1134 of file prefs.c.
Referenced by meta_core_get(), and meta_window_appears_focused().
meta_prefs_get_auto_raise()
gboolean meta_prefs_get_auto_raise (void)
Definition at line 2352 of file prefs.c.
Referenced by meta_workspace_focus_default_window().
meta_prefs_get_auto_raise_delay()
int meta_prefs_get_auto_raise_delay (void)
Definition at line 2358 of file prefs.c.
Referenced by meta_display_queue_autoraise_callback().
meta_prefs_get_button_layout()
void meta_prefs_get_button_layout (MetaButtonLayout * button_layout)
Definition at line 2289 of file prefs.c.
meta_prefs_get_center_new_windows()
gboolean meta_prefs_get_center_new_windows (void)
Definition at line 2457 of file prefs.c.
Referenced by meta_window_place().
meta_prefs_get_command()
const char * meta_prefs_get_command (int i)
Definition at line 2106 of file prefs.c.
References MAX_COMMANDS, and NULL.
meta_prefs_get_compositing_fast_alt_tab()
gboolean meta_prefs_get_compositing_fast_alt_tab (void)
Definition at line 2451 of file prefs.c.
Referenced by meta_screen_ensure_tab_popup().
meta_prefs_get_compositing_manager()
gboolean meta_prefs_get_compositing_manager (void)
Definition at line 2443 of file prefs.c.
Referenced by meta_frames_apply_shapes(), and meta_screen_ensure_tab_popup().
meta_prefs_get_cursor_size()
int meta_prefs_get_cursor_size (void)
Definition at line 1158 of file prefs.c.
meta_prefs_get_cursor_theme()
const char * meta_prefs_get_cursor_theme (void)
Definition at line 1152 of file prefs.c.
meta_prefs_get_disable_workarounds()
gboolean meta_prefs_get_disable_workarounds (void)
Definition at line 1610 of file prefs.c.
Referenced by meta_window_configure_request(), meta_window_move_resize_request(), and meta_window_place().
meta_prefs_get_dynamic_workspaces()
gboolean meta_prefs_get_dynamic_workspaces (void)
Definition at line 1590 of file prefs.c.
Referenced by meta_screen_update_dynamic_workspaces().
meta_prefs_get_focus_mode()
MetaFocusMode meta_prefs_get_focus_mode (void)
Definition at line 1122 of file prefs.c.
Referenced by meta_display_grab_focus_window_button(), meta_window_notify_focus(), and meta_workspace_focus_default_window().
meta_prefs_get_focus_new_windows()
MetaFocusNewWindows meta_prefs_get_focus_new_windows (void)
Definition at line 1128 of file prefs.c.
Referenced by meta_window_set_user_time().
meta_prefs_get_force_fullscreen()
gboolean meta_prefs_get_force_fullscreen (void)
Definition at line 2499 of file prefs.c.
Referenced by meta_window_move_resize_request().
meta_prefs_get_icon_size()
int meta_prefs_get_icon_size (void)
Definition at line 1167 of file prefs.c.
Referenced by meta_ui_get_default_window_icon(), meta_ui_get_window_icon_from_desktop_id(), and meta_window_update_icon_now().
meta_prefs_get_key_bindings()
void meta_prefs_get_key_bindings (const MetaKeyPref ** bindings, int * n_bindings)
Definition at line 2313 of file prefs.c.
References int().
meta_prefs_get_keybinding_action()
MetaKeyBindingAction meta_prefs_get_keybinding_action (const char * name)
Definition at line 2382 of file prefs.c.
References META_KEYBINDING_ACTION_NONE, and name.
meta_prefs_get_mate_accessibility()
gboolean meta_prefs_get_mate_accessibility (void)
Definition at line 2370 of file prefs.c.
Referenced by meta_display_begin_grab_op().
meta_prefs_get_mate_animations()
gboolean meta_prefs_get_mate_animations (void)
Definition at line 2376 of file prefs.c.
meta_prefs_get_mouse_button_menu()
guint meta_prefs_get_mouse_button_menu (void)
Definition at line 2487 of file prefs.c.
meta_prefs_get_mouse_button_mods()
MetaVirtualModifier meta_prefs_get_mouse_button_mods (void)
Definition at line 1116 of file prefs.c.
meta_prefs_get_mouse_button_resize()
guint meta_prefs_get_mouse_button_resize (void)
Definition at line 2481 of file prefs.c.
meta_prefs_get_num_workspaces()
int meta_prefs_get_num_workspaces (void)
Definition at line 1584 of file prefs.c.
meta_prefs_get_placement_mode()
MetaPlacementMode meta_prefs_get_placement_mode (void)
Definition at line 2505 of file prefs.c.
Referenced by meta_window_place().
meta_prefs_get_raise_on_click()
gboolean meta_prefs_get_raise_on_click (void)
Definition at line 1140 of file prefs.c.
Referenced by meta_core_maximize(), meta_core_show_window_menu(), meta_core_toggle_maximize(), meta_core_toggle_maximize_horizontally(), meta_core_toggle_maximize_vertically(), meta_core_unmaximize(), meta_core_user_lower_and_unfocus(), meta_display_begin_grab_op(), meta_display_check_threshold_reached(), meta_display_end_grab_op(), meta_window_client_message(), and meta_window_notify_focus().
meta_prefs_get_reduced_resources()
gboolean meta_prefs_get_reduced_resources (void)
Definition at line 2364 of file prefs.c.
Referenced by meta_display_begin_grab_op().
meta_prefs_get_settings_key_for_command()
char * meta_prefs_get_settings_key_for_command (int i)
Definition at line 2114 of file prefs.c.
References AREA_SCREENSHOT_COMMAND_IDX, key, KEY_COMMAND_PREFIX, SCREENSHOT_COMMAND_IDX, and WIN_SCREENSHOT_COMMAND_IDX.
meta_prefs_get_settings_key_for_terminal_command()
const char * meta_prefs_get_settings_key_for_terminal_command (void)
Definition at line 2144 of file prefs.c.
References KEY_MATE_TERMINAL_COMMAND.
meta_prefs_get_terminal_command()
const char * meta_prefs_get_terminal_command (void)
Definition at line 2138 of file prefs.c.
meta_prefs_get_theme()
const char * meta_prefs_get_theme (void)
Definition at line 1146 of file prefs.c.
Referenced by main().
meta_prefs_get_titlebar_font()
const PangoFontDescription * meta_prefs_get_titlebar_font (void)
Definition at line 1575 of file prefs.c.
References NULL.
Referenced by meta_ui_theme_get_frame_borders().
meta_prefs_get_visual_bell()
gboolean meta_prefs_get_visual_bell (void)
Definition at line 2295 of file prefs.c.
meta_prefs_get_visual_bell_type()
MetaVisualBellType meta_prefs_get_visual_bell_type (void)
Definition at line 2307 of file prefs.c.
meta_prefs_get_window_binding()
void meta_prefs_get_window_binding (const char * name, unsigned int * keysym, MetaVirtualModifier * modifiers)
Definition at line 2403 of file prefs.c.
References MetaKeyCombo::keysym, MetaKeyCombo::modifiers, and name.
Referenced by meta_core_get_menu_accelerator().
meta_prefs_get_workspace_name()
const char * meta_prefs_get_workspace_name (int i)
Definition at line 2227 of file prefs.c.
References MAX_REASONABLE_WORKSPACES, META_DEBUG_PREFS, and NULL.
Referenced by meta_workspace_get_name().
meta_prefs_get_wrap_style()
MetaWrapStyle meta_prefs_get_wrap_style (void)
Definition at line 1596 of file prefs.c.
Referenced by meta_workspace_get_neighbor().
meta_prefs_init()
void meta_prefs_init (void)
Definition at line 956 of file prefs.c.
References KEY_COMMAND_SCHEMA, KEY_GENERAL_SCHEMA, KEY_MATE_INTERFACE_ACCESSIBILITY, KEY_MATE_INTERFACE_ENABLE_ANIMATIONS, KEY_MATE_INTERFACE_SCHEMA, KEY_MATE_MOUSE_CURSOR_SIZE, KEY_MATE_MOUSE_CURSOR_THEME, KEY_MATE_MOUSE_SCHEMA, KEY_MATE_TERMINAL_COMMAND, KEY_MATE_TERMINAL_SCHEMA, KEY_SCREEN_BINDINGS_SCHEMA, KEY_WINDOW_BINDINGS_SCHEMA, KEY_WORKSPACE_NAME_SCHEMA, and NULL.
Referenced by main().
meta_prefs_is_in_skip_list()
gboolean meta_prefs_is_in_skip_list (char * class)
Definition at line 1194 of file prefs.c.
References FALSE, item, and TRUE.
Referenced by meta_screen_show_desktop().
meta_prefs_remove_listener()
void meta_prefs_remove_listener (MetaPrefsChangedFunc func, gpointer data)
Definition at line 854 of file prefs.c.
References data, meta_bug(), and NULL.
Referenced by meta_display_close(), meta_display_shutdown_keys(), meta_screen_free(), and meta_window_destroy_frame().
meta_prefs_set_center_new_windows()
void meta_prefs_set_center_new_windows (gboolean whether)
Definition at line 2526 of file prefs.c.
References KEY_GENERAL_CENTER_NEW_WINDOWS.
meta_prefs_set_compositing_fast_alt_tab()
void meta_prefs_set_compositing_fast_alt_tab (gboolean whether)
Definition at line 2518 of file prefs.c.
References KEY_GENERAL_COMPOSITOR_FAST_ALT_TAB.
meta_prefs_set_force_compositing_manager()
void meta_prefs_set_force_compositing_manager (gboolean whether)
Sets whether the compositor is turned on.
Parameters
whether TRUE to turn on, FALSE to turn off
Definition at line 2511 of file prefs.c.
References TRUE.
Referenced by main().
meta_prefs_set_force_fullscreen()
void meta_prefs_set_force_fullscreen (gboolean whether)
Definition at line 2534 of file prefs.c.
Referenced by main().
meta_prefs_set_num_workspaces()
void meta_prefs_set_num_workspaces (int n_workspaces)
Definition at line 1771 of file prefs.c.
References KEY_GENERAL_NUM_WORKSPACES, and MAX_REASONABLE_WORKSPACES.
meta_prefs_show_tab_border()
gboolean meta_prefs_show_tab_border (void)
Definition at line 2493 of file prefs.c.
Referenced by meta_screen_ensure_tab_popup().