MATE Desktop Environment: prelexer.h File Reference
prelexer.h File Reference
#include <glib.h>
Classes
struct PreLexerState
Enumerations
enum LexerTokenType {
T_UNKNOWN =0 , PL_DECIMAL , PL_DIGIT , PL_HEX ,
PL_SUPER_DIGIT , PL_SUPER_MINUS , PL_SUB_DIGIT , PL_FRACTION ,
PL_DEGREE , PL_MINUTE , PL_SECOND , PL_LETTER ,
PL_EOS , PL_SKIP , T_ADD , T_SUBTRACT ,
T_MULTIPLY , T_DIV , T_MOD , T_L_FLOOR ,
T_R_FLOOR , T_L_CEILING , T_R_CEILING , T_ROOT ,
T_ROOT_3 , T_ROOT_4 , T_NOT , T_AND ,
T_OR , T_XOR , T_IN , T_NUMBER ,
T_SUP_NUMBER , T_NSUP_NUMBER , T_SUB_NUMBER , T_FUNCTION ,
T_VARIABLE , T_ASSIGN , T_L_R_BRACKET , T_R_R_BRACKET ,
T_L_S_BRACKET , T_R_S_BRACKET , T_L_C_BRACKET , T_R_C_BRACKET ,
T_ABS , T_POWER , T_FACTORIAL , T_PERCENTAGE
}
Functions
PreLexerState * pl_create_scanner (const gchar *)
void pl_destroy_scanner (PreLexerState *)
void pl_roll_back (PreLexerState *)
gunichar pl_get_next_gunichar (PreLexerState *)
void pl_set_marker (PreLexerState *)
gchar * pl_get_marked_substring (const PreLexerState *)
LexerTokenType pl_get_next_token (PreLexerState *)
Enumeration Type Documentation
LexerTokenType
enum LexerTokenType
Enumerator
T_UNKNOWN
PL_DECIMAL
PL_DIGIT
PL_HEX
PL_SUPER_DIGIT
PL_SUPER_MINUS
PL_SUB_DIGIT
PL_FRACTION
PL_DEGREE
PL_MINUTE
PL_SECOND
PL_LETTER
PL_EOS
PL_SKIP
T_ADD
T_SUBTRACT
T_MULTIPLY
T_DIV
T_MOD
T_L_FLOOR
T_R_FLOOR
T_L_CEILING
T_R_CEILING
T_ROOT
T_ROOT_3
T_ROOT_4
T_NOT
T_AND
T_OR
T_XOR
T_IN
T_NUMBER
T_SUP_NUMBER
T_NSUP_NUMBER
T_SUB_NUMBER
T_FUNCTION
T_VARIABLE
T_ASSIGN
T_L_R_BRACKET
T_R_R_BRACKET
T_L_S_BRACKET
T_R_S_BRACKET
T_L_C_BRACKET
T_R_C_BRACKET
T_ABS
T_POWER
T_FACTORIAL
T_PERCENTAGE
Definition at line 16 of file prelexer.h.
Function Documentation
pl_create_scanner()
PreLexerState * pl_create_scanner (const gchar * input)
Definition at line 10 of file prelexer.c.
References PreLexerState::length, PreLexerState::mark_index, PreLexerState::next_index, NULL, and PreLexerState::stream.
Referenced by l_create_lexer().
pl_destroy_scanner()
void pl_destroy_scanner (PreLexerState * state)
Definition at line 26 of file prelexer.c.
References PreLexerState::stream.
Referenced by l_destroy_lexer().
pl_get_marked_substring()
gchar * pl_get_marked_substring (const PreLexerState * state)
Definition at line 71 of file prelexer.c.
References PreLexerState::mark_index, PreLexerState::next_index, and PreLexerState::stream.
pl_get_next_gunichar()
gunichar pl_get_next_gunichar (PreLexerState * state)
Definition at line 47 of file prelexer.c.
References PreLexerState::length, PreLexerState::next_index, and PreLexerState::stream.
Referenced by pl_get_next_token().
pl_get_next_token()
LexerTokenType pl_get_next_token (PreLexerState * state)
Definition at line 91 of file prelexer.c.
References PL_DECIMAL, PL_DEGREE, PL_DIGIT, PL_EOS, PL_FRACTION, pl_get_next_gunichar(), PL_HEX, PL_LETTER, PL_MINUTE, PL_SECOND, PL_SKIP, PL_SUB_DIGIT, PL_SUPER_DIGIT, PL_SUPER_MINUS, T_ABS, T_ADD, T_AND, T_ASSIGN, T_DIV, T_FACTORIAL, T_L_C_BRACKET, T_L_CEILING, T_L_FLOOR, T_L_R_BRACKET, T_L_S_BRACKET, T_MULTIPLY, T_NOT, T_OR, T_PERCENTAGE, T_POWER, T_R_C_BRACKET, T_R_CEILING, T_R_FLOOR, T_R_R_BRACKET, T_R_S_BRACKET, T_ROOT, T_ROOT_3, T_ROOT_4, T_SUBTRACT, T_UNKNOWN, and T_XOR.
pl_roll_back()
void pl_roll_back (PreLexerState * state)
Definition at line 34 of file prelexer.c.
References PreLexerState::next_index, NULL, and PreLexerState::stream.
pl_set_marker()
void pl_set_marker (PreLexerState * state)
Definition at line 64 of file prelexer.c.
References PreLexerState::mark_index, and PreLexerState::next_index.