MATE Desktop Environment: pulse-sink-control.c File Reference
pulse-sink-control.c File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include <libmatemixer/matemixer-private.h>
#include <pulse/pulseaudio.h>
#include "pulse-connection.h"
#include "pulse-monitor.h"
#include "pulse-stream-control.h"
#include "pulse-sink.h"
#include "pulse-sink-control.h"
Functions
G_DEFINE_TYPE (PulseSinkControl, pulse_sink_control, PULSE_TYPE_STREAM_CONTROL)
PulseSinkControl * pulse_sink_control_new (PulseConnection *connection, const pa_sink_info *info, PulseSink *parent)
void pulse_sink_control_update (PulseSinkControl *control, const pa_sink_info *info)
Function Documentation
G_DEFINE_TYPE()
G_DEFINE_TYPE (PulseSinkControl , pulse_sink_control , PULSE_TYPE_STREAM_CONTROL)
References PULSE_TYPE_STREAM_CONTROL.
pulse_sink_control_new()
PulseSinkControl * pulse_sink_control_new (PulseConnection * connection, const pa_sink_info * info, PulseSink * parent)
Definition at line 56 of file pulse-sink-control.c.
References connection, MATE_MIXER_STREAM_CONTROL_HAS_DECIBEL, MATE_MIXER_STREAM_CONTROL_HAS_MONITOR, MATE_MIXER_STREAM_CONTROL_MUTE_READABLE, MATE_MIXER_STREAM_CONTROL_MUTE_WRITABLE, MATE_MIXER_STREAM_CONTROL_ROLE_MASTER, MATE_MIXER_STREAM_CONTROL_ROLE_PORT, MATE_MIXER_STREAM_CONTROL_VOLUME_READABLE, MATE_MIXER_STREAM_CONTROL_VOLUME_WRITABLE, NULL, PULSE_IS_CONNECTION, PULSE_IS_SINK, pulse_sink_control_update(), pulse_sink_get_index_monitor(), and PULSE_TYPE_SINK_CONTROL.
Referenced by pulse_sink_new().
pulse_sink_control_update()
void pulse_sink_control_update (PulseSinkControl * control, const pa_sink_info * info)
Definition at line 99 of file pulse-sink-control.c.
References _mate_mixer_stream_control_set_mute(), FALSE, MATE_MIXER_STREAM_CONTROL, NULL, PULSE_IS_SINK_CONTROL, PULSE_STREAM_CONTROL, pulse_stream_control_set_channel_map(), pulse_stream_control_set_cvolume(), and TRUE.
Referenced by pulse_sink_control_new(), and pulse_sink_update().