MATE Desktop Environment: pulse-device.c File Reference
pulse-device.c File Reference
#include <string.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include <libmatemixer/matemixer-private.h>
#include <pulse/pulseaudio.h>
#include "pulse-connection.h"
#include "pulse-device.h"
#include "pulse-device-profile.h"
#include "pulse-device-switch.h"
#include "pulse-port.h"
#include "pulse-stream.h"
Enumerations
enum { PROP_0 , PROP_INDEX , PROP_CONNECTION , N_PROPERTIES }
Functions
PulseDevice * pulse_device_new (PulseConnection *connection, const pa_card_info *info)
void pulse_device_update (PulseDevice *device, const pa_card_info *info)
void pulse_device_add_stream (PulseDevice *device, PulseStream *stream)
void pulse_device_remove_stream (PulseDevice *device, PulseStream *stream)
guint32 pulse_device_get_index (PulseDevice *device)
PulseConnection * pulse_device_get_connection (PulseDevice *device)
PulsePort * pulse_device_get_port (PulseDevice *device, const gchar *name)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_INDEX
PROP_CONNECTION
N_PROPERTIES
Definition at line 46 of file pulse-device.c.
Function Documentation
pulse_device_add_stream()
void pulse_device_add_stream (PulseDevice * device, PulseStream * stream)
Definition at line 262 of file pulse-device.c.
References MATE_MIXER_STREAM, mate_mixer_stream_get_name(), name, _PulseDevice::priv, PULSE_IS_DEVICE, and PULSE_IS_STREAM.
pulse_device_get_connection()
PulseConnection * pulse_device_get_connection (PulseDevice * device)
Definition at line 309 of file pulse-device.c.
References NULL, _PulseDevice::priv, and PULSE_IS_DEVICE.
pulse_device_get_index()
guint32 pulse_device_get_index (PulseDevice * device)
Definition at line 301 of file pulse-device.c.
References _PulseDevice::priv, and PULSE_IS_DEVICE.
pulse_device_get_port()
PulsePort * pulse_device_get_port (PulseDevice * device, const gchar * name)
Definition at line 317 of file pulse-device.c.
References name, NULL, _PulseDevice::priv, and PULSE_IS_DEVICE.
Referenced by pulse_sink_new(), and pulse_source_new().
pulse_device_new()
PulseDevice * pulse_device_new (PulseConnection * connection, const pa_card_info * info)
Definition at line 218 of file pulse-device.c.
References connection, label, NULL, pulse_device_update(), PULSE_IS_CONNECTION, and PULSE_TYPE_DEVICE.
pulse_device_remove_stream()
void pulse_device_remove_stream (PulseDevice * device, PulseStream * stream)
Definition at line 283 of file pulse-device.c.
References MATE_MIXER_STREAM, mate_mixer_stream_get_name(), name, _PulseDevice::priv, PULSE_IS_DEVICE, and PULSE_IS_STREAM.
pulse_device_update()
void pulse_device_update (PulseDevice * device, const pa_card_info * info)
Definition at line 251 of file pulse-device.c.
References NULL, _PulseDevice::priv, pulse_device_switch_set_active_profile_by_name(), and PULSE_IS_DEVICE.
Referenced by pulse_device_new().