MATE Desktop Environment: pulse-sink.h File Reference
pulse-sink.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <pulse/pulseaudio.h>
#include "pulse-stream.h"
#include "pulse-types.h"
Classes
struct _PulseSink
struct _PulseSinkClass
Macros
#define PULSE_TYPE_SINK (pulse_sink_get_type ())
#define PULSE_SINK(o)
#define PULSE_IS_SINK(o)
#define PULSE_SINK_CLASS(k)
#define PULSE_IS_SINK_CLASS(k)
#define PULSE_SINK_GET_CLASS(o)
Typedefs
typedef struct _PulseSinkClass PulseSinkClass
typedef struct _PulseSinkPrivate PulseSinkPrivate
Functions
GType pulse_sink_get_type (void)
PulseSink * pulse_sink_new (PulseConnection *connection, const pa_sink_info *info, PulseDevice *device)
gboolean pulse_sink_add_input (PulseSink *sink, const pa_sink_input_info *info)
void pulse_sink_remove_input (PulseSink *sink, guint32 index)
void pulse_sink_update (PulseSink *sink, const pa_sink_info *info)
guint32 pulse_sink_get_index_monitor (PulseSink *sink)
Macro Definition Documentation
PULSE_IS_SINK
#define PULSE_IS_SINK (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_SINK))
Definition at line 35 of file pulse-sink.h.
Referenced by pulse_sink_add_input(), pulse_sink_control_new(), pulse_sink_get_index_monitor(), pulse_sink_input_new(), pulse_sink_remove_input(), pulse_sink_switch_new(), and pulse_sink_update().
PULSE_IS_SINK_CLASS
#define PULSE_IS_SINK_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_SINK))
Definition at line 39 of file pulse-sink.h.
PULSE_SINK
#define PULSE_SINK (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_SINK, PulseSink))
Definition at line 33 of file pulse-sink.h.
PULSE_SINK_CLASS
#define PULSE_SINK_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_SINK, PulseSinkClass))
Definition at line 37 of file pulse-sink.h.
PULSE_SINK_GET_CLASS
#define PULSE_SINK_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_SINK, PulseSinkClass))
Definition at line 41 of file pulse-sink.h.
PULSE_TYPE_SINK
#define PULSE_TYPE_SINK (pulse_sink_get_type ())
Definition at line 31 of file pulse-sink.h.
Referenced by pulse_sink_new().
Typedef Documentation
PulseSinkClass
typedef struct _PulseSinkClass PulseSinkClass
Definition at line 44 of file pulse-sink.h.
PulseSinkPrivate
typedef struct _PulseSinkPrivate PulseSinkPrivate
Definition at line 45 of file pulse-sink.h.
Function Documentation
pulse_sink_add_input()
gboolean pulse_sink_add_input (PulseSink * sink, const pa_sink_input_info * info)
Definition at line 183 of file pulse-sink.c.
References connection, FALSE, MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), name, NULL, _PulseSink::priv, PULSE_IS_SINK, pulse_sink_input_new(), pulse_sink_input_update(), PULSE_STREAM, pulse_stream_get_connection(), and TRUE.
pulse_sink_get_index_monitor()
guint32 pulse_sink_get_index_monitor (PulseSink * sink)
Definition at line 259 of file pulse-sink.c.
References _PulseSink::priv, and PULSE_IS_SINK.
Referenced by pulse_sink_control_new().
pulse_sink_get_type()
GType pulse_sink_get_type (void)
References connection.
pulse_sink_new()
PulseSink * pulse_sink_new (PulseConnection * connection, const pa_sink_info * info, PulseDevice * device)
Definition at line 119 of file pulse-sink.c.
References _, _mate_mixer_stream_set_default_control(), connection, MATE_MIXER_DIRECTION_OUTPUT, MATE_MIXER_STREAM, MATE_MIXER_STREAM_CONTROL, MATE_MIXER_SWITCH_OPTION, mate_mixer_switch_option_get_icon(), NULL, _PulseSink::priv, PULSE_DEVICE, pulse_device_get_port(), PULSE_IS_CONNECTION, PULSE_IS_DEVICE, pulse_port_new(), pulse_port_switch_add_port(), pulse_port_switch_set_active_port(), pulse_sink_control_new(), pulse_sink_switch_new(), pulse_sink_update(), and PULSE_TYPE_SINK.
pulse_sink_remove_input()
void pulse_sink_remove_input (PulseSink * sink, guint32 index)
Definition at line 219 of file pulse-sink.c.
References MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), name, NULL, _PulseSink::priv, and PULSE_IS_SINK.
pulse_sink_update()
void pulse_sink_update (PulseSink * sink, const pa_sink_info * info)
Definition at line 242 of file pulse-sink.c.
References NULL, _PulseSink::priv, PULSE_IS_SINK, pulse_port_switch_set_active_port_by_name(), and pulse_sink_control_update().
Referenced by pulse_sink_new().