MATE Desktop Environment: pulse-sink.c File Reference
pulse-sink.c File Reference
#include <glib.h>
#include <glib/gi18n.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include <libmatemixer/matemixer-private.h>
#include <pulse/pulseaudio.h>
#include "pulse-connection.h"
#include "pulse-device.h"
#include "pulse-monitor.h"
#include "pulse-port.h"
#include "pulse-port-switch.h"
#include "pulse-stream.h"
#include "pulse-sink.h"
#include "pulse-sink-control.h"
#include "pulse-sink-input.h"
#include "pulse-sink-switch.h"
Functions
G_DEFINE_TYPE_WITH_PRIVATE (PulseSink, pulse_sink, PULSE_TYPE_STREAM)
PulseSink * pulse_sink_new (PulseConnection *connection, const pa_sink_info *info, PulseDevice *device)
gboolean pulse_sink_add_input (PulseSink *sink, const pa_sink_input_info *info)
void pulse_sink_remove_input (PulseSink *sink, guint32 index)
void pulse_sink_update (PulseSink *sink, const pa_sink_info *info)
guint32 pulse_sink_get_index_monitor (PulseSink *sink)
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (PulseSink , pulse_sink , PULSE_TYPE_STREAM)
References PULSE_TYPE_STREAM.
pulse_sink_add_input()
gboolean pulse_sink_add_input (PulseSink * sink, const pa_sink_input_info * info)
Definition at line 183 of file pulse-sink.c.
References connection, FALSE, MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), name, NULL, _PulseSink::priv, PULSE_IS_SINK, pulse_sink_input_new(), pulse_sink_input_update(), PULSE_STREAM, pulse_stream_get_connection(), and TRUE.
pulse_sink_get_index_monitor()
guint32 pulse_sink_get_index_monitor (PulseSink * sink)
Definition at line 259 of file pulse-sink.c.
References _PulseSink::priv, and PULSE_IS_SINK.
Referenced by pulse_sink_control_new().
pulse_sink_new()
PulseSink * pulse_sink_new (PulseConnection * connection, const pa_sink_info * info, PulseDevice * device)
Definition at line 119 of file pulse-sink.c.
References _, _mate_mixer_stream_set_default_control(), connection, MATE_MIXER_DIRECTION_OUTPUT, MATE_MIXER_STREAM, MATE_MIXER_STREAM_CONTROL, MATE_MIXER_SWITCH_OPTION, mate_mixer_switch_option_get_icon(), NULL, _PulseSink::priv, PULSE_DEVICE, pulse_device_get_port(), PULSE_IS_CONNECTION, PULSE_IS_DEVICE, pulse_port_new(), pulse_port_switch_add_port(), pulse_port_switch_set_active_port(), pulse_sink_control_new(), pulse_sink_switch_new(), pulse_sink_update(), and PULSE_TYPE_SINK.
pulse_sink_remove_input()
void pulse_sink_remove_input (PulseSink * sink, guint32 index)
Definition at line 219 of file pulse-sink.c.
References MATE_MIXER_STREAM_CONTROL, mate_mixer_stream_control_get_name(), name, NULL, _PulseSink::priv, and PULSE_IS_SINK.
pulse_sink_update()
void pulse_sink_update (PulseSink * sink, const pa_sink_info * info)
Definition at line 242 of file pulse-sink.c.
References NULL, _PulseSink::priv, PULSE_IS_SINK, pulse_port_switch_set_active_port_by_name(), and pulse_sink_control_update().
Referenced by pulse_sink_new().