MATE Desktop Environment: pulse-device.h File Reference
pulse-device.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include <pulse/pulseaudio.h>
#include "pulse-types.h"
Classes
struct _PulseDevice
struct _PulseDeviceClass
Macros
#define PULSE_TYPE_DEVICE (pulse_device_get_type ())
#define PULSE_DEVICE(o)
#define PULSE_IS_DEVICE(o)
#define PULSE_DEVICE_CLASS(k)
#define PULSE_IS_DEVICE_CLASS(k)
#define PULSE_DEVICE_GET_CLASS(o)
Typedefs
typedef struct _PulseDeviceClass PulseDeviceClass
typedef struct _PulseDevicePrivate PulseDevicePrivate
Functions
GType pulse_device_get_type (void)
PulseDevice * pulse_device_new (PulseConnection *connection, const pa_card_info *info)
void pulse_device_update (PulseDevice *device, const pa_card_info *info)
void pulse_device_add_stream (PulseDevice *device, PulseStream *stream)
void pulse_device_remove_stream (PulseDevice *device, PulseStream *stream)
guint32 pulse_device_get_index (PulseDevice *device)
PulseConnection * pulse_device_get_connection (PulseDevice *device)
PulsePort * pulse_device_get_port (PulseDevice *device, const gchar *name)
Macro Definition Documentation
PULSE_DEVICE
#define PULSE_DEVICE (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_DEVICE, PulseDevice))
Definition at line 33 of file pulse-device.h.
Referenced by pulse_sink_new(), pulse_source_new(), and pulse_stream_get_device().
PULSE_DEVICE_CLASS
#define PULSE_DEVICE_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_DEVICE, PulseDeviceClass))
Definition at line 37 of file pulse-device.h.
PULSE_DEVICE_GET_CLASS
#define PULSE_DEVICE_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_IS_DEVICE, PulseDeviceClass))
Definition at line 41 of file pulse-device.h.
PULSE_IS_DEVICE
#define PULSE_IS_DEVICE (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_DEVICE))
Definition at line 35 of file pulse-device.h.
Referenced by pulse_device_add_stream(), pulse_device_get_connection(), pulse_device_get_index(), pulse_device_get_port(), pulse_device_remove_stream(), pulse_device_switch_new(), pulse_device_update(), pulse_sink_new(), and pulse_source_new().
PULSE_IS_DEVICE_CLASS
#define PULSE_IS_DEVICE_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_DEVICE))
Definition at line 39 of file pulse-device.h.
PULSE_TYPE_DEVICE
#define PULSE_TYPE_DEVICE (pulse_device_get_type ())
Definition at line 31 of file pulse-device.h.
Referenced by pulse_device_new().
Typedef Documentation
PulseDeviceClass
typedef struct _PulseDeviceClass PulseDeviceClass
Definition at line 44 of file pulse-device.h.
PulseDevicePrivate
typedef struct _PulseDevicePrivate PulseDevicePrivate
Definition at line 45 of file pulse-device.h.
Function Documentation
pulse_device_add_stream()
void pulse_device_add_stream (PulseDevice * device, PulseStream * stream)
Definition at line 262 of file pulse-device.c.
References MATE_MIXER_STREAM, mate_mixer_stream_get_name(), name, _PulseDevice::priv, PULSE_IS_DEVICE, and PULSE_IS_STREAM.
pulse_device_get_connection()
PulseConnection * pulse_device_get_connection (PulseDevice * device)
Definition at line 309 of file pulse-device.c.
References NULL, _PulseDevice::priv, and PULSE_IS_DEVICE.
pulse_device_get_index()
guint32 pulse_device_get_index (PulseDevice * device)
Definition at line 301 of file pulse-device.c.
References _PulseDevice::priv, and PULSE_IS_DEVICE.
pulse_device_get_port()
PulsePort * pulse_device_get_port (PulseDevice * device, const gchar * name)
Definition at line 317 of file pulse-device.c.
References name, NULL, _PulseDevice::priv, and PULSE_IS_DEVICE.
Referenced by pulse_sink_new(), and pulse_source_new().
pulse_device_get_type()
GType pulse_device_get_type (void)
References connection, and name.
pulse_device_new()
PulseDevice * pulse_device_new (PulseConnection * connection, const pa_card_info * info)
Definition at line 218 of file pulse-device.c.
References connection, label, NULL, pulse_device_update(), PULSE_IS_CONNECTION, and PULSE_TYPE_DEVICE.
pulse_device_remove_stream()
void pulse_device_remove_stream (PulseDevice * device, PulseStream * stream)
Definition at line 283 of file pulse-device.c.
References MATE_MIXER_STREAM, mate_mixer_stream_get_name(), name, _PulseDevice::priv, PULSE_IS_DEVICE, and PULSE_IS_STREAM.
pulse_device_update()
void pulse_device_update (PulseDevice * device, const pa_card_info * info)
Definition at line 251 of file pulse-device.c.
References NULL, _PulseDevice::priv, pulse_device_switch_set_active_profile_by_name(), and PULSE_IS_DEVICE.
Referenced by pulse_device_new().