MATE Desktop Environment: pulse-ext-stream.c File Reference
pulse-ext-stream.c File Reference
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include <libmatemixer/matemixer-private.h>
#include <pulse/pulseaudio.h>
#include <pulse/ext-stream-restore.h>
#include "pulse-connection.h"
#include "pulse-ext-stream.h"
#include "pulse-helpers.h"
#include "pulse-stream.h"
#include "pulse-stream-control.h"
Enumerations
enum { PROP_0 , PROP_CONNECTION , PROP_APP_INFO , N_PROPERTIES }
Functions
PulseExtStream * pulse_ext_stream_new (PulseConnection *connection, const pa_ext_stream_restore_info *info, PulseStream *parent)
void pulse_ext_stream_update (PulseExtStream *ext, const pa_ext_stream_restore_info *info, PulseStream *parent)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_CONNECTION
PROP_APP_INFO
N_PROPERTIES
Definition at line 43 of file pulse-ext-stream.c.
Function Documentation
pulse_ext_stream_new()
PulseExtStream * pulse_ext_stream_new (PulseConnection * connection, const pa_ext_stream_restore_info * info, PulseStream * parent)
Definition at line 241 of file pulse-ext-stream.c.
References _mate_mixer_app_info_free(), _mate_mixer_app_info_new(), _mate_mixer_app_info_set_id(), _mate_mixer_app_info_set_name(), connection, MATE_MIXER_DIRECTION_INPUT, MATE_MIXER_DIRECTION_OUTPUT, MATE_MIXER_DIRECTION_UNKNOWN, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_UNKNOWN, MATE_MIXER_STREAM_CONTROL_MOVABLE, MATE_MIXER_STREAM_CONTROL_MUTE_READABLE, MATE_MIXER_STREAM_CONTROL_MUTE_WRITABLE, MATE_MIXER_STREAM_CONTROL_ROLE_APPLICATION, MATE_MIXER_STREAM_CONTROL_ROLE_UNKNOWN, MATE_MIXER_STREAM_CONTROL_STORED, NULL, pulse_convert_media_role_name(), pulse_ext_stream_update(), PULSE_IS_CONNECTION, PULSE_TYPE_EXT_STREAM, and strchr.
pulse_ext_stream_update()
void pulse_ext_stream_update (PulseExtStream * ext, const pa_ext_stream_restore_info * info, PulseStream * parent)
Definition at line 331 of file pulse-ext-stream.c.
References _mate_mixer_stream_control_set_flags(), _mate_mixer_stream_control_set_mute(), _mate_mixer_stream_control_set_stream(), FALSE, MATE_MIXER_STREAM, MATE_MIXER_STREAM_CONTROL, MATE_MIXER_STREAM_CONTROL_CAN_BALANCE, MATE_MIXER_STREAM_CONTROL_CAN_FADE, mate_mixer_stream_control_get_flags(), MATE_MIXER_STREAM_CONTROL_VOLUME_READABLE, MATE_MIXER_STREAM_CONTROL_VOLUME_WRITABLE, NULL, _PulseExtStream::priv, PULSE_IS_EXT_STREAM, and TRUE.
Referenced by pulse_ext_stream_new().