MATE Desktop Environment: pulse-device-switch.c File Reference
pulse-device-switch.c File Reference
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include <libmatemixer/matemixer-private.h>
#include "pulse-connection.h"
#include "pulse-device.h"
#include "pulse-device-profile.h"
#include "pulse-device-switch.h"
Functions
PulseDeviceSwitch * pulse_device_switch_new (const gchar *name, const gchar *label, PulseDevice *device)
void pulse_device_switch_add_profile (PulseDeviceSwitch *swtch, PulseDeviceProfile *profile)
void pulse_device_switch_set_active_profile (PulseDeviceSwitch *swtch, PulseDeviceProfile *profile)
void pulse_device_switch_set_active_profile_by_name (PulseDeviceSwitch *swtch, const gchar *name)
Function Documentation
pulse_device_switch_add_profile()
void pulse_device_switch_add_profile (PulseDeviceSwitch * swtch, PulseDeviceProfile * profile)
Definition at line 99 of file pulse-device-switch.c.
References _PulseDeviceSwitch::priv, PULSE_IS_DEVICE_PROFILE, and PULSE_IS_DEVICE_SWITCH.
pulse_device_switch_new()
PulseDeviceSwitch * pulse_device_switch_new (const gchar * name, const gchar * label, PulseDevice * device)
Definition at line 84 of file pulse-device-switch.c.
References label, MATE_MIXER_DEVICE_SWITCH_ROLE_PROFILE, name, NULL, PULSE_IS_DEVICE, and PULSE_TYPE_DEVICE_SWITCH.
pulse_device_switch_set_active_profile()
void pulse_device_switch_set_active_profile (PulseDeviceSwitch * swtch, PulseDeviceProfile * profile)
Definition at line 110 of file pulse-device-switch.c.
References _mate_mixer_switch_set_active_option(), MATE_MIXER_SWITCH, MATE_MIXER_SWITCH_OPTION, PULSE_IS_DEVICE_PROFILE, and PULSE_IS_DEVICE_SWITCH.
Referenced by pulse_device_switch_set_active_profile_by_name().
pulse_device_switch_set_active_profile_by_name()
void pulse_device_switch_set_active_profile_by_name (PulseDeviceSwitch * swtch, const gchar * name)
Definition at line 121 of file pulse-device-switch.c.
References item, name, NULL, _PulseDeviceSwitch::priv, PULSE_DEVICE_PROFILE, pulse_device_switch_set_active_profile(), and PULSE_IS_DEVICE_SWITCH.
Referenced by pulse_device_update().