MATE Desktop Environment: pulse-helpers.c File Reference
pulse-helpers.c File Reference
#include <string.h>
#include <glib.h>
#include <libmatemixer/matemixer-enums.h>
#include <pulse/pulseaudio.h>
#include "pulse-helpers.h"
Functions
MateMixerStreamControlMediaRole pulse_convert_media_role_name (const gchar *name)
Variables
const MateMixerChannelPosition pulse_channel_map_from [PA_CHANNEL_POSITION_MAX]
const pa_channel_position_t pulse_channel_map_to [MATE_MIXER_CHANNEL_MAX]
Function Documentation
pulse_convert_media_role_name()
MateMixerStreamControlMediaRole pulse_convert_media_role_name (const gchar * name)
Definition at line 74 of file pulse-helpers.c.
References MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_A11Y, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_ABSTRACT, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_ANIMATION, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_EVENT, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_FILTER, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_GAME, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_MUSIC, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_PHONE, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_PRODUCTION, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_TEST, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_UNKNOWN, MATE_MIXER_STREAM_CONTROL_MEDIA_ROLE_VIDEO, name, and NULL.
Referenced by pulse_ext_stream_new(), pulse_sink_input_new(), and pulse_source_output_new().
Variable Documentation
pulse_channel_map_from
const MateMixerChannelPosition pulse_channel_map_from[PA_CHANNEL_POSITION_MAX]
Initial value:
                                                      =
{
    [PA_CHANNEL_POSITION_MONO]                  = MATE_MIXER_CHANNEL_MONO,
    [PA_CHANNEL_POSITION_FRONT_LEFT]            = MATE_MIXER_CHANNEL_FRONT_LEFT,
    [PA_CHANNEL_POSITION_FRONT_RIGHT]           = MATE_MIXER_CHANNEL_FRONT_RIGHT,
    [PA_CHANNEL_POSITION_FRONT_CENTER]          = MATE_MIXER_CHANNEL_FRONT_CENTER,
    [PA_CHANNEL_POSITION_LFE]                   = MATE_MIXER_CHANNEL_LFE,
    [PA_CHANNEL_POSITION_REAR_LEFT]             = MATE_MIXER_CHANNEL_BACK_LEFT,
    [PA_CHANNEL_POSITION_REAR_RIGHT]            = MATE_MIXER_CHANNEL_BACK_RIGHT,
    [PA_CHANNEL_POSITION_FRONT_LEFT_OF_CENTER]  = MATE_MIXER_CHANNEL_FRONT_LEFT_CENTER,
    [PA_CHANNEL_POSITION_FRONT_RIGHT_OF_CENTER] = MATE_MIXER_CHANNEL_FRONT_RIGHT_CENTER,
    [PA_CHANNEL_POSITION_SIDE_LEFT]             = MATE_MIXER_CHANNEL_SIDE_LEFT,
    [PA_CHANNEL_POSITION_SIDE_RIGHT]            = MATE_MIXER_CHANNEL_SIDE_RIGHT,
    [PA_CHANNEL_POSITION_TOP_FRONT_LEFT]        = MATE_MIXER_CHANNEL_TOP_FRONT_LEFT,
    [PA_CHANNEL_POSITION_TOP_FRONT_RIGHT]       = MATE_MIXER_CHANNEL_TOP_FRONT_RIGHT,
    [PA_CHANNEL_POSITION_TOP_FRONT_CENTER]      = MATE_MIXER_CHANNEL_TOP_FRONT_CENTER,
    [PA_CHANNEL_POSITION_TOP_CENTER]            = MATE_MIXER_CHANNEL_TOP_CENTER,
    [PA_CHANNEL_POSITION_TOP_REAR_LEFT]         = MATE_MIXER_CHANNEL_TOP_BACK_LEFT,
    [PA_CHANNEL_POSITION_TOP_REAR_RIGHT]        = MATE_MIXER_CHANNEL_TOP_BACK_RIGHT,
    [PA_CHANNEL_POSITION_TOP_REAR_CENTER]       = MATE_MIXER_CHANNEL_TOP_BACK_CENTER
}
Definition at line 27 of file pulse-helpers.c.
pulse_channel_map_to
const pa_channel_position_t pulse_channel_map_to[MATE_MIXER_CHANNEL_MAX]
Initial value:
                                                 =
{
    [MATE_MIXER_CHANNEL_UNKNOWN]                = PA_CHANNEL_POSITION_INVALID,
    [MATE_MIXER_CHANNEL_MONO]                   = PA_CHANNEL_POSITION_MONO,
    [MATE_MIXER_CHANNEL_FRONT_LEFT]             = PA_CHANNEL_POSITION_FRONT_LEFT,
    [MATE_MIXER_CHANNEL_FRONT_RIGHT]            = PA_CHANNEL_POSITION_FRONT_RIGHT,
    [MATE_MIXER_CHANNEL_FRONT_CENTER]           = PA_CHANNEL_POSITION_FRONT_CENTER,
    [MATE_MIXER_CHANNEL_LFE]                    = PA_CHANNEL_POSITION_LFE,
    [MATE_MIXER_CHANNEL_BACK_LEFT]              = PA_CHANNEL_POSITION_REAR_LEFT,
    [MATE_MIXER_CHANNEL_BACK_RIGHT]             = PA_CHANNEL_POSITION_REAR_RIGHT,
    [MATE_MIXER_CHANNEL_BACK_CENTER]            = PA_CHANNEL_POSITION_REAR_CENTER,
    [MATE_MIXER_CHANNEL_FRONT_LEFT_CENTER]      = PA_CHANNEL_POSITION_FRONT_LEFT_OF_CENTER,
    [MATE_MIXER_CHANNEL_FRONT_RIGHT_CENTER]     = PA_CHANNEL_POSITION_FRONT_RIGHT_OF_CENTER,
    [MATE_MIXER_CHANNEL_SIDE_LEFT]              = PA_CHANNEL_POSITION_SIDE_LEFT,
    [MATE_MIXER_CHANNEL_SIDE_RIGHT]             = PA_CHANNEL_POSITION_SIDE_RIGHT,
    [MATE_MIXER_CHANNEL_TOP_FRONT_LEFT]         = PA_CHANNEL_POSITION_TOP_FRONT_LEFT,
    [MATE_MIXER_CHANNEL_TOP_FRONT_RIGHT]        = PA_CHANNEL_POSITION_TOP_FRONT_RIGHT,
    [MATE_MIXER_CHANNEL_TOP_FRONT_CENTER]       = PA_CHANNEL_POSITION_TOP_FRONT_CENTER,
    [MATE_MIXER_CHANNEL_TOP_CENTER]             = PA_CHANNEL_POSITION_TOP_CENTER,
    [MATE_MIXER_CHANNEL_TOP_BACK_LEFT]          = PA_CHANNEL_POSITION_TOP_REAR_LEFT,
    [MATE_MIXER_CHANNEL_TOP_BACK_RIGHT]         = PA_CHANNEL_POSITION_TOP_REAR_RIGHT,
    [MATE_MIXER_CHANNEL_TOP_BACK_CENTER]        = PA_CHANNEL_POSITION_TOP_REAR_CENTER
}
Definition at line 49 of file pulse-helpers.c.