MATE Desktop Environment: pulse-port-switch.h File Reference
pulse-port-switch.h File Reference
#include <glib.h>
#include <glib-object.h>
#include <libmatemixer/matemixer.h>
#include "pulse-types.h"
Classes
struct _PulsePortSwitch
struct _PulsePortSwitchClass
Macros
#define PULSE_TYPE_PORT_SWITCH (pulse_port_switch_get_type ())
#define PULSE_PORT_SWITCH(o)
#define PULSE_IS_PORT_SWITCH(o)
#define PULSE_PORT_SWITCH_CLASS(k)
#define PULSE_IS_PORT_SWITCH_CLASS(k)
#define PULSE_PORT_SWITCH_GET_CLASS(o)
Typedefs
typedef struct _PulsePortSwitchClass PulsePortSwitchClass
typedef struct _PulsePortSwitchPrivate PulsePortSwitchPrivate
Functions
GType pulse_port_switch_get_type (void)
PulseStream * pulse_port_switch_get_stream (PulsePortSwitch *swtch)
void pulse_port_switch_add_port (PulsePortSwitch *swtch, PulsePort *port)
void pulse_port_switch_set_active_port (PulsePortSwitch *swtch, PulsePort *port)
void pulse_port_switch_set_active_port_by_name (PulsePortSwitch *swtch, const gchar *name)
Macro Definition Documentation
PULSE_IS_PORT_SWITCH
#define PULSE_IS_PORT_SWITCH (o)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((o), PULSE_TYPE_PORT_SWITCH))
Definition at line 33 of file pulse-port-switch.h.
Referenced by pulse_port_switch_add_port(), pulse_port_switch_get_stream(), pulse_port_switch_set_active_port(), and pulse_port_switch_set_active_port_by_name().
PULSE_IS_PORT_SWITCH_CLASS
#define PULSE_IS_PORT_SWITCH_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((k), PULSE_TYPE_PORT_SWITCH))
Definition at line 37 of file pulse-port-switch.h.
PULSE_PORT_SWITCH
#define PULSE_PORT_SWITCH (o)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((o), PULSE_TYPE_PORT_SWITCH, PulsePortSwitch))
Definition at line 31 of file pulse-port-switch.h.
PULSE_PORT_SWITCH_CLASS
#define PULSE_PORT_SWITCH_CLASS (k)
Value:
(G_TYPE_CHECK_CLASS_CAST ((k), PULSE_TYPE_PORT_SWITCH, PulsePortSwitchClass))
Definition at line 35 of file pulse-port-switch.h.
PULSE_PORT_SWITCH_GET_CLASS
#define PULSE_PORT_SWITCH_GET_CLASS (o)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((o), PULSE_TYPE_PORT_SWITCH, PulsePortSwitchClass))
Definition at line 39 of file pulse-port-switch.h.
PULSE_TYPE_PORT_SWITCH
#define PULSE_TYPE_PORT_SWITCH (pulse_port_switch_get_type ())
Definition at line 29 of file pulse-port-switch.h.
Typedef Documentation
PulsePortSwitchClass
typedef struct _PulsePortSwitchClass PulsePortSwitchClass
Definition at line 42 of file pulse-port-switch.h.
PulsePortSwitchPrivate
typedef struct _PulsePortSwitchPrivate PulsePortSwitchPrivate
Definition at line 43 of file pulse-port-switch.h.
Function Documentation
pulse_port_switch_add_port()
void pulse_port_switch_add_port (PulsePortSwitch * swtch, PulsePort * port)
Definition at line 92 of file pulse-port-switch.c.
References _PulsePortSwitch::priv, PULSE_IS_PORT, and PULSE_IS_PORT_SWITCH.
Referenced by pulse_sink_new(), and pulse_source_new().
pulse_port_switch_get_stream()
PulseStream * pulse_port_switch_get_stream (PulsePortSwitch * swtch)
Definition at line 84 of file pulse-port-switch.c.
References MATE_MIXER_STREAM_SWITCH, mate_mixer_stream_switch_get_stream(), NULL, PULSE_IS_PORT_SWITCH, and PULSE_STREAM.
pulse_port_switch_get_type()
GType pulse_port_switch_get_type (void)
References name.
pulse_port_switch_set_active_port()
void pulse_port_switch_set_active_port (PulsePortSwitch * swtch, PulsePort * port)
Definition at line 103 of file pulse-port-switch.c.
References _mate_mixer_switch_set_active_option(), MATE_MIXER_SWITCH, MATE_MIXER_SWITCH_OPTION, PULSE_IS_PORT, and PULSE_IS_PORT_SWITCH.
Referenced by pulse_port_switch_set_active_port_by_name(), pulse_sink_new(), and pulse_source_new().
pulse_port_switch_set_active_port_by_name()
void pulse_port_switch_set_active_port_by_name (PulsePortSwitch * swtch, const gchar * name)
Definition at line 113 of file pulse-port-switch.c.
References item, name, NULL, _PulsePortSwitch::priv, PULSE_IS_PORT_SWITCH, PULSE_PORT, and pulse_port_switch_set_active_port().
Referenced by pulse_sink_update(), and pulse_source_update().