MATE Desktop Environment: rfkill-glib.c File Reference
rfkill-glib.c File Reference
#include <errno.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <string.h>
#include <glib.h>
#include <gio/gio.h>
#include <gio/gunixoutputstream.h>
#include "rfkill-glib.h"
Macros
#define CHANGE_ALL_TIMEOUT 500
Enumerations
enum { CHANGED , LAST_SIGNAL }
Functions
gboolean cc_rfkill_glib_send_event_finish (CcRfkillGlib *rfkill, GAsyncResult *res, GError **error)
void cc_rfkill_glib_send_event (CcRfkillGlib *rfkill, struct rfkill_event *event, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
gboolean cc_rfkill_glib_send_change_all_event_finish (CcRfkillGlib *rfkill, GAsyncResult *res, GError **error)
void cc_rfkill_glib_send_change_all_event (CcRfkillGlib *rfkill, guint rfkill_type, gboolean enable, GCancellable *cancellable, GAsyncReadyCallback callback, gpointer user_data)
int cc_rfkill_glib_open (CcRfkillGlib *rfkill)
CcRfkillGlib * cc_rfkill_glib_new (void)
Macro Definition Documentation
CHANGE_ALL_TIMEOUT
#define CHANGE_ALL_TIMEOUT 500
Definition at line 63 of file rfkill-glib.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CHANGED
LAST_SIGNAL
Definition at line 42 of file rfkill-glib.c.
Function Documentation
cc_rfkill_glib_new()
CcRfkillGlib * cc_rfkill_glib_new (void)
Definition at line 519 of file rfkill-glib.c.
References CC_RFKILL_GLIB, CC_RFKILL_TYPE_GLIB, and NULL.
Referenced by msd_rfkill_manager_start().
cc_rfkill_glib_open()
int cc_rfkill_glib_open (CcRfkillGlib * rfkill)
Definition at line 395 of file rfkill-glib.c.
References rfkill_event::hard, rfkill_event::idx, NULL, rfkill_event::op, _CcRfkillGlib::priv, RFKILL_EVENT_SIZE_V1, RFKILL_IS_GLIB, RFKILL_OP_ADD, rfkill_event::soft, TRUE, and rfkill_event::type.
Referenced by msd_rfkill_manager_start().
cc_rfkill_glib_send_change_all_event()
void cc_rfkill_glib_send_change_all_event (CcRfkillGlib * rfkill, guint rfkill_type, gboolean enable, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 206 of file rfkill-glib.c.
References cc_rfkill_glib_send_change_all_event(), NULL, _CcRfkillGlib::priv, RFKILL_IS_GLIB, RFKILL_OP_CHANGE_ALL, and user_data.
Referenced by cc_rfkill_glib_send_change_all_event(), and cc_rfkill_glib_send_change_all_event_finish().
cc_rfkill_glib_send_change_all_event_finish()
gboolean cc_rfkill_glib_send_change_all_event_finish (CcRfkillGlib * rfkill, GAsyncResult * res, GError ** error)
Definition at line 120 of file rfkill-glib.c.
References cc_rfkill_glib_send_change_all_event(), error, FALSE, and RFKILL_IS_GLIB.
cc_rfkill_glib_send_event()
void cc_rfkill_glib_send_event (CcRfkillGlib * rfkill, struct rfkill_event * event, GCancellable * cancellable, GAsyncReadyCallback callback, gpointer user_data)
Definition at line 97 of file rfkill-glib.c.
References cc_rfkill_glib_send_event(), NULL, _CcRfkillGlib::priv, RFKILL_IS_GLIB, and user_data.
Referenced by cc_rfkill_glib_send_event(), and cc_rfkill_glib_send_event_finish().
cc_rfkill_glib_send_event_finish()
gboolean cc_rfkill_glib_send_event_finish (CcRfkillGlib * rfkill, GAsyncResult * res, GError ** error)
Definition at line 69 of file rfkill-glib.c.
References cc_rfkill_glib_send_event(), error, FALSE, and RFKILL_IS_GLIB.