MATE Desktop Environment: screenshot-utils.c File Reference
screenshot-utils.c File Reference
#include "screenshot-utils.h"
#include <X11/Xatom.h>
#include <gdk/gdkx.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include <glib.h>
#include <glib/gi18n.h>
Macros
#define SELECTION_NAME "_MATE_PANEL_SCREENSHOT"
Functions
gboolean screenshot_grab_lock (void)
void screenshot_release_lock (void)
GdkWindow * screenshot_find_current_window ()
void screenshot_select_area_async (SelectAreaCallback callback)
GdkPixbuf * screenshot_get_pixbuf (GdkWindow *window, GdkRectangle *rectangle, gboolean include_pointer, gboolean include_border, gboolean include_mask)
void screenshot_show_error_dialog (GtkWindow *parent, const gchar *message, const gchar *detail)
void screenshot_show_gerror_dialog (GtkWindow *parent, const gchar *message, GError *error)
Macro Definition Documentation
SELECTION_NAME
#define SELECTION_NAME "_MATE_PANEL_SCREENSHOT"
Definition at line 40 of file screenshot-utils.c.
Function Documentation
screenshot_find_current_window()
GdkWindow * screenshot_find_current_window (void)
Definition at line 169 of file screenshot-utils.c.
References NULL.
screenshot_get_pixbuf()
GdkPixbuf * screenshot_get_pixbuf (GdkWindow * window, GdkRectangle * rectangle, gboolean include_pointer, gboolean include_border, gboolean include_mask)
Definition at line 600 of file screenshot-utils.c.
References MAX, NULL, and TRUE.
screenshot_grab_lock()
gboolean screenshot_grab_lock (void)
Definition at line 47 of file screenshot-utils.c.
References FALSE, NULL, SELECTION_NAME, and TRUE.
screenshot_release_lock()
void screenshot_release_lock (void)
Definition at line 83 of file screenshot-utils.c.
References NULL.
screenshot_select_area_async()
void screenshot_select_area_async (SelectAreaCallback callback)
Definition at line 387 of file screenshot-utils.c.
References data, FALSE, and NULL.
screenshot_show_error_dialog()
void screenshot_show_error_dialog (GtkWindow * parent, const gchar * message, const gchar * detail)
Definition at line 842 of file screenshot-utils.c.
References message(), and NULL.
Referenced by screenshot_show_gerror_dialog().
screenshot_show_gerror_dialog()
void screenshot_show_gerror_dialog (GtkWindow * parent, const gchar * message, GError * error)
Definition at line 871 of file screenshot-utils.c.
References error, message(), NULL, and screenshot_show_error_dialog().