MATE Desktop Environment: screen.c File Reference
screen.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include "screen-private.h"
#include "util.h"
#include "errors.h"
#include "window-private.h"
#include "frame-private.h"
#include "prefs.h"
#include "workspace.h"
#include "keybindings.h"
#include "stack.h"
#include "xprops.h"
#include "compositor.h"
#include <X11/Xatom.h>
#include <cairo/cairo-xlib.h>
#include <locale.h>
#include <string.h>
#include <stdio.h>
#include "atomnames.h"
Macros
#define MAX_REASONABLE_WORKSPACES 36
#define EWMH_ATOMS_ONLY
#define item(x)
#define N_VALS 6
#define MAX_PREVIEW_SCREEN_FRACTION 0.33
#define MAX_PREVIEW_SIZE 300.0
#define ICON_OFFSET 6
#define OUTLINE_WIDTH 5
#define TILE_PREVIEW_TIMEOUT_MS 200
#define _NET_WM_ORIENTATION_HORZ 0
#define _NET_WM_ORIENTATION_VERT 1
#define _NET_WM_TOPLEFT 0
#define _NET_WM_TOPRIGHT 1
#define _NET_WM_BOTTOMRIGHT 2
#define _NET_WM_BOTTOMLEFT 3
Functions
MetaScreen * meta_screen_new (MetaDisplay *display, int number, guint32 timestamp)
void meta_screen_free (MetaScreen *screen, guint32 timestamp)
void meta_screen_manage_all_windows (MetaScreen *screen)
void meta_screen_composite_all_windows (MetaScreen *screen)
MetaScreen * meta_screen_for_x_screen (Screen *xscreen)
void meta_screen_foreach_window (MetaScreen *screen, MetaScreenWindowFunc func, gpointer data)
void meta_screen_queue_frame_redraws (MetaScreen *screen)
void meta_screen_queue_window_resizes (MetaScreen *screen)
int meta_screen_get_n_workspaces (MetaScreen *screen)
MetaWorkspace * meta_screen_get_workspace_by_index (MetaScreen *screen, int idx)
void meta_screen_update_dynamic_workspaces (MetaScreen *screen)
void meta_screen_set_cursor (MetaScreen *screen, MetaCursor cursor)
void meta_screen_update_cursor (MetaScreen *screen)
void meta_screen_ensure_tab_popup (MetaScreen *screen, MetaTabList list_type, MetaTabShowType show_type)
void meta_screen_ensure_workspace_popup (MetaScreen *screen)
void meta_screen_tile_preview_update (MetaScreen *screen, gboolean delay)
void meta_screen_tile_preview_hide (MetaScreen *screen)
MetaWindow * meta_screen_get_mouse_window (MetaScreen *screen, MetaWindow *not_this_one)
const MetaXineramaScreenInfo * meta_screen_get_xinerama_for_rect (MetaScreen *screen, MetaRectangle *rect)
const MetaXineramaScreenInfo * meta_screen_get_xinerama_for_window (MetaScreen *screen, MetaWindow *window)
const MetaXineramaScreenInfo * meta_screen_get_xinerama_neighbor (MetaScreen *screen, int which_xinerama, MetaScreenDirection direction)
void meta_screen_get_natural_xinerama_list (MetaScreen *screen, int **xineramas_list, int *n_xineramas)
const MetaXineramaScreenInfo * meta_screen_get_current_xinerama (MetaScreen *screen)
void meta_screen_update_workspace_layout (MetaScreen *screen)
void meta_screen_update_workspace_names (MetaScreen *screen)
Window meta_create_offscreen_window (Display *xdisplay, Window parent, long valuemask)
void meta_screen_queue_workarea_recalc (MetaScreen *screen)
void meta_screen_calc_workspace_layout (MetaScreen *screen, int num_workspaces, int current_space, MetaWorkspaceLayout *layout)
void meta_screen_free_workspace_layout (MetaWorkspaceLayout *layout)
void meta_screen_resize (MetaScreen *screen, int width, int height)
void meta_screen_update_showing_desktop_hint (MetaScreen *screen)
void meta_screen_minimize_all_on_active_workspace_except (MetaScreen *screen, MetaWindow *keep)
void meta_screen_show_desktop (MetaScreen *screen, guint32 timestamp)
void meta_screen_unshow_desktop (MetaScreen *screen)
gboolean meta_screen_apply_startup_properties (MetaScreen *screen, MetaWindow *window)
int meta_screen_get_screen_number (MetaScreen *screen)
MetaDisplay * meta_screen_get_display (MetaScreen *screen)
Window meta_screen_get_xroot (MetaScreen *screen)
void meta_screen_get_size (MetaScreen *screen, int *width, int *height)
gpointer meta_screen_get_compositor_data (MetaScreen *screen)
void meta_screen_set_compositor_data (MetaScreen *screen, gpointer compositor)
Macro Definition Documentation
_NET_WM_BOTTOMLEFT
#define _NET_WM_BOTTOMLEFT 3
Definition at line 2156 of file screen.c.
Referenced by meta_screen_update_workspace_layout().
_NET_WM_BOTTOMRIGHT
#define _NET_WM_BOTTOMRIGHT 2
Definition at line 2155 of file screen.c.
Referenced by meta_screen_update_workspace_layout().
_NET_WM_ORIENTATION_HORZ
#define _NET_WM_ORIENTATION_HORZ 0
Definition at line 2150 of file screen.c.
Referenced by meta_screen_update_workspace_layout().
_NET_WM_ORIENTATION_VERT
#define _NET_WM_ORIENTATION_VERT 1
Definition at line 2151 of file screen.c.
Referenced by meta_screen_update_workspace_layout().
_NET_WM_TOPLEFT
#define _NET_WM_TOPLEFT 0
Definition at line 2153 of file screen.c.
Referenced by meta_screen_update_workspace_layout().
_NET_WM_TOPRIGHT
#define _NET_WM_TOPRIGHT 1
Definition at line 2154 of file screen.c.
Referenced by meta_screen_update_workspace_layout().
EWMH_ATOMS_ONLY
#define EWMH_ATOMS_ONLY
ICON_OFFSET
#define ICON_OFFSET 6
Referenced by meta_screen_ensure_tab_popup().
item
#define item (x)
Value:
screen->display->atom_##x,
MAX_PREVIEW_SCREEN_FRACTION
#define MAX_PREVIEW_SCREEN_FRACTION 0.33
Definition at line 1528 of file screen.c.
MAX_PREVIEW_SIZE
#define MAX_PREVIEW_SIZE 300.0
Definition at line 1529 of file screen.c.
MAX_REASONABLE_WORKSPACES
#define MAX_REASONABLE_WORKSPACES 36
Definition at line 58 of file screen.c.
N_VALS
#define N_VALS 6
OUTLINE_WIDTH
#define OUTLINE_WIDTH 5
Referenced by meta_screen_ensure_tab_popup(), and meta_tile_preview_show().
TILE_PREVIEW_TIMEOUT_MS
#define TILE_PREVIEW_TIMEOUT_MS 200
Definition at line 1860 of file screen.c.
Referenced by meta_screen_tile_preview_update().
Function Documentation
meta_create_offscreen_window()
Window meta_create_offscreen_window (Display * xdisplay, Window parent, long valuemask)
Definition at line 2329 of file screen.c.
Referenced by meta_screen_new().
meta_screen_apply_startup_properties()
gboolean meta_screen_apply_startup_properties (MetaScreen * screen, MetaWindow * window)
Definition at line 3102 of file screen.c.
References FALSE, META_DEBUG_STARTUP, meta_window_get_startup_id(), NULL, and TRUE.
Referenced by meta_window_new_with_attrs().
meta_screen_calc_workspace_layout()
void meta_screen_calc_workspace_layout (MetaScreen * screen, int num_workspaces, int current_space, MetaWorkspaceLayout * layout)
Definition at line 2486 of file screen.c.
References meta_bug(), meta_is_verbose(), meta_pop_no_msg_prefix(), meta_push_no_msg_prefix(), META_SCREEN_BOTTOMLEFT, META_SCREEN_BOTTOMRIGHT, META_SCREEN_TOPLEFT, and META_SCREEN_TOPRIGHT.
Referenced by meta_screen_ensure_workspace_popup(), meta_window_show_menu(), and meta_workspace_get_neighbor().
meta_screen_composite_all_windows()
void meta_screen_composite_all_windows (MetaScreen * screen)
Definition at line 832 of file screen.c.
References _MetaDisplay::compositor, meta_compositor_add_window(), meta_display_lookup_x_window(), meta_stack_freeze(), meta_stack_thaw(), and NULL.
meta_screen_ensure_tab_popup()
void meta_screen_ensure_tab_popup (MetaScreen * screen, MetaTabList list_type, MetaTabShowType show_type)
Definition at line 1587 of file screen.c.
References BORDER_OUTLINE_TAB, BORDER_OUTLINE_WINDOW, FALSE, _MetaRectangle::height, ICON_OFFSET, meta_display_get_tab_list(), meta_prefs_get_alt_tab_expand_to_fit_title(), meta_prefs_get_alt_tab_max_columns(), meta_prefs_get_compositing_fast_alt_tab(), meta_prefs_get_compositing_manager(), meta_prefs_show_tab_border(), META_TAB_SHOW_INSTANTLY, meta_ui_tab_popup_new(), meta_window_get_icon_geometry(), meta_window_get_outer_rect(), meta_window_showing_on_its_workspace(), NULL, OUTLINE_WIDTH, and _MetaRectangle::width.
Referenced by meta_display_begin_grab_op().
meta_screen_ensure_workspace_popup()
void meta_screen_ensure_workspace_popup (MetaScreen * screen)
Definition at line 1743 of file screen.c.
References BORDER_OUTLINE_WORKSPACE, FALSE, meta_screen_calc_workspace_layout(), meta_screen_free_workspace_layout(), meta_screen_get_n_workspaces(), meta_screen_get_workspace_by_index(), meta_ui_tab_popup_new(), meta_workspace_get_name(), meta_workspace_index(), NULL, and TRUE.
Referenced by meta_display_begin_grab_op().
meta_screen_for_x_screen()
MetaScreen * meta_screen_for_x_screen (Screen * xscreen)
Definition at line 871 of file screen.c.
References meta_display_for_x_display(), meta_display_screen_for_x_screen(), and NULL.
Referenced by meta_core_get_active_workspace(), and meta_core_get_num_workspaces().
meta_screen_foreach_window()
void meta_screen_foreach_window (MetaScreen * screen, MetaScreenWindowFunc func, gpointer data)
Definition at line 1016 of file screen.c.
References data, and NULL.
Referenced by meta_screen_queue_frame_redraws(), meta_screen_queue_window_resizes(), meta_screen_resize(), and meta_workspace_new().
meta_screen_free()
void meta_screen_free (MetaScreen * screen, guint32 timestamp)
Definition at line 645 of file screen.c.
References _, _MetaDisplay::closing, FALSE, meta_compositor_unmanage_screen(), meta_display_grab(), meta_display_ungrab(), meta_display_unmanage_windows_for_screen(), meta_error_trap_pop_with_return(), meta_error_trap_push(), meta_prefs_remove_listener(), meta_screen_ungrab_keys(), meta_stack_free(), meta_tile_preview_free(), meta_ui_free(), meta_warning(), NULL, and _MetaDisplay::xdisplay.
Referenced by meta_display_close(), and meta_display_unmanage_screen().
meta_screen_free_workspace_layout()
void meta_screen_free_workspace_layout (MetaWorkspaceLayout * layout)
Definition at line 2751 of file screen.c.
Referenced by meta_screen_ensure_workspace_popup(), meta_window_show_menu(), and meta_workspace_get_neighbor().
meta_screen_get_compositor_data()
gpointer meta_screen_get_compositor_data (MetaScreen * screen)
Definition at line 3261 of file screen.c.
meta_screen_get_current_xinerama()
const MetaXineramaScreenInfo * meta_screen_get_current_xinerama (MetaScreen * screen)
Definition at line 2102 of file screen.c.
References FALSE, _MetaRectangle::height, META_DEBUG_XINERAMA, meta_rectangle_contains_rect(), _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_screen_get_natural_xinerama_list(), meta_window_can_tile(), and meta_window_place().
meta_screen_get_display()
MetaDisplay * meta_screen_get_display (MetaScreen * screen)
Definition at line 3240 of file screen.c.
meta_screen_get_mouse_window()
MetaWindow * meta_screen_get_mouse_window (MetaScreen * screen, MetaWindow * not_this_one)
Definition at line 1896 of file screen.c.
References _MetaWindow::desc, META_DEBUG_FOCUS, meta_error_trap_pop(), meta_error_trap_push(), meta_stack_get_default_focus_window_at_point(), and TRUE.
Referenced by meta_workspace_focus_default_window().
meta_screen_get_n_workspaces()
int meta_screen_get_n_workspaces (MetaScreen * screen)
Definition at line 1080 of file screen.c.
Referenced by meta_core_get_num_workspaces(), meta_screen_ensure_workspace_popup(), meta_window_show_menu(), and meta_workspace_get_neighbor().
meta_screen_get_natural_xinerama_list()
void meta_screen_get_natural_xinerama_list (MetaScreen * screen, int ** xineramas_list, int * n_xineramas)
Definition at line 2007 of file screen.c.
References FALSE, META_SCREEN_DOWN, meta_screen_get_current_xinerama(), meta_screen_get_xinerama_neighbor(), META_SCREEN_LEFT, META_SCREEN_RIGHT, META_SCREEN_UP, _MetaXineramaScreenInfo::number, and TRUE.
meta_screen_get_screen_number()
int meta_screen_get_screen_number (MetaScreen * screen)
Definition at line 3234 of file screen.c.
meta_screen_get_size()
void meta_screen_get_size (MetaScreen * screen, int * width, int * height)
Definition at line 3252 of file screen.c.
meta_screen_get_workspace_by_index()
MetaWorkspace * meta_screen_get_workspace_by_index (MetaScreen * screen, int idx)
Definition at line 1086 of file screen.c.
References idx, and NULL.
Referenced by meta_core_change_workspace(), meta_core_get_workspace_name_with_index(), meta_screen_ensure_workspace_popup(), meta_screen_new(), meta_window_client_message(), meta_window_new_with_attrs(), and meta_workspace_get_neighbor().
meta_screen_get_xinerama_for_rect()
const MetaXineramaScreenInfo * meta_screen_get_xinerama_for_rect (MetaScreen * screen, MetaRectangle * rect)
Definition at line 1931 of file screen.c.
References dest, meta_rectangle_area(), and meta_rectangle_intersect().
Referenced by meta_screen_get_xinerama_for_window(), and meta_window_move_resize_request().
meta_screen_get_xinerama_for_window()
const MetaXineramaScreenInfo * meta_screen_get_xinerama_for_window (MetaScreen * screen, MetaWindow * window)
Definition at line 1963 of file screen.c.
References meta_screen_get_xinerama_for_rect(), and meta_window_get_outer_rect().
Referenced by meta_window_get_current_tile_area(), and meta_window_get_work_area_current_xinerama().
meta_screen_get_xinerama_neighbor()
const MetaXineramaScreenInfo * meta_screen_get_xinerama_neighbor (MetaScreen * screen, int which_xinerama, MetaScreenDirection direction)
Definition at line 1974 of file screen.c.
References _MetaRectangle::height, meta_rectangle_horiz_overlap(), meta_rectangle_vert_overlap(), META_SCREEN_DOWN, META_SCREEN_LEFT, META_SCREEN_RIGHT, META_SCREEN_UP, NULL, _MetaXineramaScreenInfo::rect, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_screen_get_natural_xinerama_list().
meta_screen_get_xroot()
Window meta_screen_get_xroot (MetaScreen * screen)
Definition at line 3246 of file screen.c.
meta_screen_manage_all_windows()
void meta_screen_manage_all_windows (MetaScreen * screen)
Definition at line 789 of file screen.c.
References meta_compositor_add_window(), meta_display_grab(), meta_display_ungrab(), meta_stack_freeze(), meta_stack_thaw(), meta_window_new_with_attrs(), NULL, and TRUE.
meta_screen_minimize_all_on_active_workspace_except()
void meta_screen_minimize_all_on_active_workspace_except (MetaScreen * screen, MetaWindow * keep)
Definition at line 2827 of file screen.c.
References _MetaWindow::has_minimize_func, meta_window_minimize(), NULL, and _MetaWindow::screen.
meta_screen_new()
MetaScreen * meta_screen_new (MetaDisplay * display, int number, guint32 timestamp)
Definition at line 338 of file screen.c.
References _, FALSE, meta_create_offscreen_window(), META_CURSOR_DEFAULT, meta_error_trap_pop_with_return(), meta_error_trap_push(), meta_get_replace_current_wm(), meta_prefs_add_listener(), meta_prop_get_cardinal(), meta_screen_get_workspace_by_index(), meta_screen_grab_keys(), meta_screen_set_cursor(), META_SCREEN_TOPLEFT, meta_screen_update_workspace_layout(), meta_stack_new(), meta_ui_new(), meta_warning(), META_WIREFRAME_XOR_LINE_WIDTH, meta_workspace_activate(), meta_workspace_new(), _MetaDisplay::name, NULL, and _MetaDisplay::xdisplay.
meta_screen_queue_frame_redraws()
void meta_screen_queue_frame_redraws (MetaScreen * screen)
Definition at line 1062 of file screen.c.
References meta_screen_foreach_window(), and NULL.
meta_screen_queue_window_resizes()
void meta_screen_queue_window_resizes (MetaScreen * screen)
Definition at line 1074 of file screen.c.
References meta_screen_foreach_window(), and NULL.
meta_screen_queue_workarea_recalc()
void meta_screen_queue_workarea_recalc (MetaScreen * screen)
Definition at line 2450 of file screen.c.
References META_DEBUG_WORKAREA, META_PRIORITY_WORK_AREA_HINT, and NULL.
Referenced by meta_workspace_invalidate_work_area().
meta_screen_resize()
void meta_screen_resize (MetaScreen * screen, int width, int height)
Definition at line 2771 of file screen.c.
References meta_screen_foreach_window().
meta_screen_set_compositor_data()
void meta_screen_set_compositor_data (MetaScreen * screen, gpointer compositor)
Definition at line 3267 of file screen.c.
meta_screen_set_cursor()
void meta_screen_set_cursor (MetaScreen * screen, MetaCursor cursor)
Definition at line 1500 of file screen.c.
References meta_display_create_x_cursor().
Referenced by meta_screen_new().
meta_screen_show_desktop()
void meta_screen_show_desktop (MetaScreen * screen, guint32 timestamp)
Definition at line 2850 of file screen.c.
References meta_prefs_is_in_skip_list(), meta_screen_update_showing_desktop_hint(), META_WINDOW_DESKTOP, meta_window_focus(), NULL, _MetaWindow::res_class, _MetaWindow::screen, TRUE, and _MetaWindow::type.
meta_screen_tile_preview_hide()
void meta_screen_tile_preview_hide (MetaScreen * screen)
Definition at line 1886 of file screen.c.
References meta_tile_preview_hide().
meta_screen_tile_preview_update()
void meta_screen_tile_preview_update (MetaScreen * screen, gboolean delay)
Definition at line 1863 of file screen.c.
References delay, and TILE_PREVIEW_TIMEOUT_MS.
meta_screen_unshow_desktop()
void meta_screen_unshow_desktop (MetaScreen * screen)
Definition at line 2885 of file screen.c.
References FALSE, and meta_screen_update_showing_desktop_hint().
meta_screen_update_cursor()
void meta_screen_update_cursor (MetaScreen * screen)
Definition at line 1517 of file screen.c.
References meta_display_create_x_cursor().
Referenced by meta_display_set_cursor_theme().
meta_screen_update_dynamic_workspaces()
void meta_screen_update_dynamic_workspaces (MetaScreen * screen)
Definition at line 1360 of file screen.c.
References meta_prefs_get_dynamic_workspaces().
Referenced by meta_workspace_add_window(), and meta_workspace_remove_window().
meta_screen_update_showing_desktop_hint()
void meta_screen_update_showing_desktop_hint (MetaScreen * screen)
Definition at line 2786 of file screen.c.
References data, FALSE, meta_error_trap_pop(), and meta_error_trap_push().
Referenced by meta_screen_show_desktop(), meta_screen_unshow_desktop(), and meta_workspace_activate_with_focus().
meta_screen_update_workspace_layout()
void meta_screen_update_workspace_layout (MetaScreen * screen)
Definition at line 2159 of file screen.c.
References _NET_WM_BOTTOMLEFT, _NET_WM_BOTTOMRIGHT, _NET_WM_ORIENTATION_HORZ, _NET_WM_ORIENTATION_VERT, _NET_WM_TOPLEFT, _NET_WM_TOPRIGHT, FALSE, meta_prop_get_cardinal_list(), META_SCREEN_BOTTOMLEFT, META_SCREEN_BOTTOMRIGHT, META_SCREEN_TOPLEFT, META_SCREEN_TOPRIGHT, meta_warning(), meta_XFree, NULL, and TRUE.
Referenced by meta_screen_new().
meta_screen_update_workspace_names()
void meta_screen_update_workspace_names (MetaScreen * screen)
Definition at line 2292 of file screen.c.
References META_DEBUG_PREFS, meta_prefs_change_workspace_name(), meta_prop_get_utf8_list(), and NULL.