MATE Desktop Environment: scrollarea.c File Reference
scrollarea.c File Reference
#include <gdk/gdkprivate.h>
#include "scrollarea.h"
#include "foo-marshal.h"
Classes
struct AutoScrollInfo
Typedefs
typedef struct BackingStore BackingStore
typedef void(* ExposeFunc) (cairo_t *cr, cairo_region_t *region, gpointer data)
typedef struct InputPath InputPath
typedef struct InputRegion InputRegion
typedef struct AutoScrollInfo AutoScrollInfo
typedef void(* PathForeachFunc) (double *x, double *y, gpointer data)
Enumerations
enum { VIEWPORT_CHANGED , PAINT , INPUT , LAST_SIGNAL }
enum {
PROP_0 , PROP_VADJUSTMENT , PROP_HADJUSTMENT , PROP_HSCROLL_POLICY ,
PROP_VSCROLL_POLICY
}
Functions
G_DEFINE_TYPE_WITH_CODE (FooScrollArea, foo_scroll_area, GTK_TYPE_CONTAINER, G_IMPLEMENT_INTERFACE(GTK_TYPE_SCROLLABLE, NULL))
void foo_scroll_area_get_viewport (FooScrollArea *scroll_area, GdkRectangle *viewport)
void foo_scroll_area_set_size_fixed_y (FooScrollArea *scroll_area, int width, int height, int old_y, int new_y)
void foo_scroll_area_set_size (FooScrollArea *scroll_area, int width, int height)
FooScrollArea * foo_scroll_area_new (void)
void foo_scroll_area_set_min_size (FooScrollArea *scroll_area, int min_width, int min_height)
void foo_scroll_area_add_input_from_fill (FooScrollArea *scroll_area, cairo_t *cr, FooScrollAreaEventFunc func, gpointer data)
void foo_scroll_area_add_input_from_stroke (FooScrollArea *scroll_area, cairo_t *cr, FooScrollAreaEventFunc func, gpointer data)
void foo_scroll_area_invalidate (FooScrollArea *scroll_area)
void foo_scroll_area_invalidate_region (FooScrollArea *area, cairo_region_t *region)
void foo_scroll_area_invalidate_rect (FooScrollArea *scroll_area, int x, int y, int width, int height)
void foo_scroll_area_begin_grab (FooScrollArea *scroll_area, FooScrollAreaEventFunc func, gpointer input_data)
void foo_scroll_area_end_grab (FooScrollArea *scroll_area)
gboolean foo_scroll_area_is_grabbed (FooScrollArea *scroll_area)
void foo_scroll_area_set_viewport_pos (FooScrollArea *scroll_area, int x, int y)
void foo_scroll_area_auto_scroll (FooScrollArea *scroll_area, FooScrollAreaEvent *event)
void foo_scroll_area_begin_auto_scroll (FooScrollArea *scroll_area)
void foo_scroll_area_end_auto_scroll (FooScrollArea *scroll_area)
Typedef Documentation
AutoScrollInfo
typedef struct AutoScrollInfo AutoScrollInfo
Definition at line 33 of file scrollarea.c.
BackingStore
typedef struct BackingStore BackingStore
Definition at line 27 of file scrollarea.c.
ExposeFunc
typedef void(* ExposeFunc) (cairo_t *cr, cairo_region_t *region, gpointer data)
Definition at line 29 of file scrollarea.c.
InputPath
typedef struct InputPath InputPath
Definition at line 31 of file scrollarea.c.
InputRegion
typedef struct InputRegion InputRegion
Definition at line 32 of file scrollarea.c.
PathForeachFunc
typedef void(* PathForeachFunc) (double *x, double *y, gpointer data)
Definition at line 319 of file scrollarea.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_VADJUSTMENT
PROP_HADJUSTMENT
PROP_HSCROLL_POLICY
PROP_VSCROLL_POLICY
Definition at line 108 of file scrollarea.c.
anonymous enum
anonymous enum
Enumerator
VIEWPORT_CHANGED
PAINT
INPUT
LAST_SIGNAL
Definition at line 100 of file scrollarea.c.
Function Documentation
foo_scroll_area_add_input_from_fill()
void foo_scroll_area_add_input_from_fill (FooScrollArea * scroll_area, cairo_t * cr, FooScrollAreaEventFunc func, gpointer data)
Definition at line 1212 of file scrollarea.c.
References data, FALSE, FOO_IS_SCROLL_AREA, NULL, and FooScrollArea::priv.
foo_scroll_area_add_input_from_stroke()
void foo_scroll_area_add_input_from_stroke (FooScrollArea * scroll_area, cairo_t * cr, FooScrollAreaEventFunc func, gpointer data)
Definition at line 1225 of file scrollarea.c.
References data, FOO_IS_SCROLL_AREA, NULL, FooScrollArea::priv, and TRUE.
foo_scroll_area_auto_scroll()
void foo_scroll_area_auto_scroll (FooScrollArea * scroll_area, FooScrollAreaEvent * event)
Definition at line 1444 of file scrollarea.c.
References MAX, MIN, FooScrollAreaEvent::x, and FooScrollAreaEvent::y.
foo_scroll_area_begin_auto_scroll()
void foo_scroll_area_begin_auto_scroll (FooScrollArea * scroll_area)
Definition at line 1488 of file scrollarea.c.
foo_scroll_area_begin_grab()
void foo_scroll_area_begin_grab (FooScrollArea * scroll_area, FooScrollAreaEventFunc func, gpointer input_data)
Definition at line 1319 of file scrollarea.c.
References FOO_IS_SCROLL_AREA, FooScrollArea::priv, and TRUE.
foo_scroll_area_end_auto_scroll()
void foo_scroll_area_end_auto_scroll (FooScrollArea * scroll_area)
Definition at line 1494 of file scrollarea.c.
foo_scroll_area_end_grab()
void foo_scroll_area_end_grab (FooScrollArea * scroll_area)
Definition at line 1335 of file scrollarea.c.
References FALSE, FOO_IS_SCROLL_AREA, NULL, and FooScrollArea::priv.
foo_scroll_area_get_viewport()
void foo_scroll_area_get_viewport (FooScrollArea * scroll_area, GdkRectangle * viewport)
Definition at line 518 of file scrollarea.c.
References FOO_IS_SCROLL_AREA.
foo_scroll_area_invalidate()
void foo_scroll_area_invalidate (FooScrollArea * scroll_area)
Definition at line 1238 of file scrollarea.c.
References foo_scroll_area_invalidate_rect(), and FooScrollArea::priv.
foo_scroll_area_invalidate_rect()
void foo_scroll_area_invalidate_rect (FooScrollArea * scroll_area, int x, int y, int width, int height)
Definition at line 1300 of file scrollarea.c.
References FOO_IS_SCROLL_AREA, and foo_scroll_area_invalidate_region().
Referenced by foo_scroll_area_invalidate().
foo_scroll_area_invalidate_region()
void foo_scroll_area_invalidate_region (FooScrollArea * area, cairo_region_t * region)
Definition at line 1277 of file scrollarea.c.
References FOO_IS_SCROLL_AREA, FooScrollArea::priv, and TRUE.
Referenced by foo_scroll_area_invalidate_rect().
foo_scroll_area_is_grabbed()
gboolean foo_scroll_area_is_grabbed (FooScrollArea * scroll_area)
Definition at line 1345 of file scrollarea.c.
References FooScrollArea::priv.
foo_scroll_area_new()
FooScrollArea * foo_scroll_area_new (void)
Definition at line 1152 of file scrollarea.c.
References FOO_TYPE_SCROLL_AREA, and NULL.
foo_scroll_area_set_min_size()
void foo_scroll_area_set_min_size (FooScrollArea * scroll_area, int min_width, int min_height)
Definition at line 1158 of file scrollarea.c.
References FooScrollArea::priv.
foo_scroll_area_set_size()
void foo_scroll_area_set_size (FooScrollArea * scroll_area, int width, int height)
Definition at line 945 of file scrollarea.c.
References FOO_IS_SCROLL_AREA, and FooScrollArea::priv.
foo_scroll_area_set_size_fixed_y()
void foo_scroll_area_set_size_fixed_y (FooScrollArea * scroll_area, int width, int height, int old_y, int new_y)
Definition at line 928 of file scrollarea.c.
References FooScrollArea::priv.
foo_scroll_area_set_viewport_pos()
void foo_scroll_area_set_viewport_pos (FooScrollArea * scroll_area, int x, int y)
Definition at line 1351 of file scrollarea.c.
References FooScrollArea::priv.
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (FooScrollArea , foo_scroll_area , GTK_TYPE_CONTAINER , G_IMPLEMENT_INTERFACE(GTK_TYPE_SCROLLABLE, NULL))
References NULL, and parent_class.