MATE Desktop Environment: sensors-applet-plugin.c File Reference
sensors-applet-plugin.c File Reference
#include <sensors-applet/sensors-applet-plugin.h>
Functions
void sensors_applet_plugin_find_sensors (GList **sensors, const gchar *path, SensorsAppletPluginTestSensorFunc test_sensor)
GQuark sensors_applet_plugin_error_quark (void)
void sensors_applet_plugin_default_sensor_limits (SensorType type, gdouble *low_value, gdouble *high_value)
void sensors_applet_plugin_add_sensor (GList **sensors, const gchar *path, const gchar *id, const gchar *label, SensorType type, gboolean enable, IconType icon, const gchar *graph_color)
void sensors_applet_plugin_add_sensor_with_limits (GList **sensors, const gchar *path, const gchar *id, const gchar *label, SensorType type, gboolean enable, gdouble low_value, gdouble high_value, IconType icon, const gchar *graph_color)
Variables
const gchar * plugin_name
Function Documentation
sensors_applet_plugin_add_sensor()
void sensors_applet_plugin_add_sensor (GList ** sensors, const gchar * path, const gchar * id, const gchar * label, SensorType type, gboolean enable, IconType icon, const gchar * graph_color)
Definition at line 99 of file sensors-applet-plugin.c.
References label, sensors_applet_plugin_add_sensor_with_limits(), and sensors_applet_plugin_default_sensor_limits().
sensors_applet_plugin_add_sensor_with_limits()
void sensors_applet_plugin_add_sensor_with_limits (GList ** sensors, const gchar * path, const gchar * id, const gchar * label, SensorType type, gboolean enable, gdouble low_value, gdouble high_value, IconType icon, const gchar * graph_color)
Definition at line 125 of file sensors-applet-plugin.c.
References label.
Referenced by sensors_applet_plugin_add_sensor().
sensors_applet_plugin_default_sensor_limits()
void sensors_applet_plugin_default_sensor_limits (SensorType type, gdouble * low_value, gdouble * high_value)
Definition at line 80 of file sensors-applet-plugin.c.
References FAN_SENSOR, and TEMP_SENSOR.
Referenced by sensors_applet_plugin_add_sensor().
sensors_applet_plugin_error_quark()
GQuark sensors_applet_plugin_error_quark (void)
Definition at line 66 of file sensors-applet-plugin.c.
References plugin_name.
sensors_applet_plugin_find_sensors()
void sensors_applet_plugin_find_sensors (GList ** sensors, const gchar * path, SensorsAppletPluginTestSensorFunc test_sensor)
Definition at line 33 of file sensors-applet-plugin.c.
References NULL, and sensors_applet_plugin_find_sensors().
Referenced by sensors_applet_plugin_find_sensors().
Variable Documentation
plugin_name
const gchar* plugin_name extern
Definition at line 29 of file acpi-plugin.c.
Referenced by sensors_applet_plugin_error_quark(), and sensors_applet_plugin_name().