MATE Desktop Environment: sensors-applet.c File Reference
sensors-applet.c File Reference
#include <glib/gi18n.h>
#include <glib/gprintf.h>
#include <gio/gio.h>
#include "sensors-applet.h"
#include "active-sensor.h"
#include "sensors-applet-settings.h"
#include "sensors-applet-plugins.h"
#include "prefs-dialog.h"
#include "about-dialog.h"
Macros
#define SENSORS_APPLET_MENU_FILE "SensorsApplet.xml"
#define DEFAULT_APPLET_SIZE 24
#define COLUMN_SPACING 2
#define ROW_SPACING 1
Functions
void sensors_applet_notify_active_sensor (ActiveSensor *active_sensor, NotifType notif_type)
void sensors_applet_notify_end (ActiveSensor *active_sensor, NotifType notif_type)
void sensors_applet_notify_end_all (SensorsApplet *sensors_applet)
GdkPixbuf * sensors_applet_load_icon (IconType icon_type)
gboolean sensors_applet_add_sensor (SensorsApplet *sensors_applet, const gchar *path, const gchar *id, const gchar *label, const gchar *interface, SensorType type, gboolean enable, gdouble low_value, gdouble high_value, gboolean alarm_enable, const gchar *low_alarm_command, const gchar *high_alarm_command, gint alarm_timeout, gdouble multiplier, gdouble offset, IconType icon_type, const gchar *graph_color)
void sensors_applet_display_layout_changed (SensorsApplet *sensors_applet)
void sensors_applet_alarm_off (SensorsApplet *sensors_applet, GtkTreePath *path, NotifType notif_type)
void sensors_applet_all_alarms_off (SensorsApplet *sensors_applet, GtkTreePath *path)
void sensors_applet_sensor_enabled (SensorsApplet *sensors_applet, GtkTreePath *path)
void sensors_applet_reorder_sensors (SensorsApplet *sensors_applet)
void sensors_applet_sensor_disabled (SensorsApplet *sensors_applet, GtkTreePath *path)
void sensors_applet_update_sensor (SensorsApplet *sensors_applet, GtkTreePath *path)
void sensors_applet_icon_changed (SensorsApplet *sensors_applet, GtkTreePath *path)
gboolean sensors_applet_update_active_sensors (SensorsApplet *sensors_applet)
void sensors_applet_graph_size_changed (SensorsApplet *sensors_applet)
gdouble sensors_applet_convert_temperature (gdouble value, TemperatureScale old, TemperatureScale new)
void sensors_applet_init (SensorsApplet *sensors_applet)
Macro Definition Documentation
COLUMN_SPACING
#define COLUMN_SPACING 2
Definition at line 51 of file sensors-applet.c.
DEFAULT_APPLET_SIZE
#define DEFAULT_APPLET_SIZE 24
Definition at line 50 of file sensors-applet.c.
Referenced by sensors_applet_init().
ROW_SPACING
#define ROW_SPACING 1
Definition at line 52 of file sensors-applet.c.
SENSORS_APPLET_MENU_FILE
#define SENSORS_APPLET_MENU_FILE "SensorsApplet.xml"
Contain the functions for operating on the SensorsApplet structure (represents the applet itself, and its associated variables.
Definition at line 48 of file sensors-applet.c.
Referenced by sensors_applet_init().
Function Documentation
sensors_applet_add_sensor()
gboolean sensors_applet_add_sensor (SensorsApplet * sensors_applet, const gchar * path, const gchar * id, const gchar * label, const gchar * interface, SensorType type, gboolean enable, gdouble low_value, gdouble high_value, gboolean alarm_enable, const gchar * low_alarm_command, const gchar * high_alarm_command, gint alarm_timeout, gdouble multiplier, gdouble offset, IconType icon_type, const gchar * graph_color)
Definition at line 827 of file sensors-applet.c.
References ALARM_ENABLE_COLUMN, ALARM_ENABLED, ALARM_TIMEOUT, ALARM_TIMEOUT_COLUMN, _SensorsApplet::applet, ENABLE_COLUMN, ENABLED, FALSE, GRAPH_COLOR, GRAPH_COLOR_COLUMN, HIGH_ALARM_COMMAND, HIGH_ALARM_COMMAND_COLUMN, HIGH_VALUE, HIGH_VALUE_COLUMN, ICON_PIXBUF_COLUMN, ICON_TYPE, ICON_TYPE_COLUMN, ID, ID_COLUMN, INTERFACE, INTERFACE_COLUMN, LABEL, label, LABEL_COLUMN, LOW_ALARM_COMMAND, LOW_ALARM_COMMAND_COLUMN, LOW_VALUE, LOW_VALUE_COLUMN, mate_panel_applet_get_preferences_path(), MULTIPLIER, MULTIPLIER_COLUMN, N_COLUMNS, NULL, OFFSET, OFFSET_COLUMN, PATH, PATH_COLUMN, _SensorsApplet::required_plugins, SENSOR_TYPE, SENSOR_TYPE_COLUMN, _SensorsApplet::sensors, sensors_applet_load_icon(), sensors_applet_sensor_enabled(), sensors_applet_settings_get_unique_id(), TRUE, and VISIBLE_COLUMN.
Referenced by sensors_applet_settings_load_sensors().
sensors_applet_alarm_off()
void sensors_applet_alarm_off (SensorsApplet * sensors_applet, GtkTreePath * path, NotifType notif_type)
to be called by things like prefs dialog to turn off a sensor alarm
Definition at line 1066 of file sensors-applet.c.
References active_sensor_alarm_off(), and NULL.
Referenced by sensors_applet_all_alarms_off().
sensors_applet_all_alarms_off()
void sensors_applet_all_alarms_off (SensorsApplet * sensors_applet, GtkTreePath * path)
Definition at line 1076 of file sensors-applet.c.
References HIGH_ALARM, LOW_ALARM, and sensors_applet_alarm_off().
sensors_applet_convert_temperature()
gdouble sensors_applet_convert_temperature (gdouble value, TemperatureScale old, TemperatureScale new)
Definition at line 1185 of file sensors-applet.c.
References CELSIUS, FAHRENHEIT, and KELVIN.
Referenced by active_sensor_update().
sensors_applet_display_layout_changed()
void sensors_applet_display_layout_changed (SensorsApplet * sensors_applet)
Definition at line 1054 of file sensors-applet.c.
References _SensorsApplet::active_sensors, FALSE, NULL, sensors_applet_update_active_sensors(), and _ActiveSensor::updated.
sensors_applet_graph_size_changed()
void sensors_applet_graph_size_changed (SensorsApplet * sensors_applet)
Definition at line 1159 of file sensors-applet.c.
References active_sensor_update_graph_dimensions(), _SensorsApplet::active_sensors, _SensorsApplet::applet, GRAPH_SIZE, mate_panel_applet_get_orient(), _SensorsApplet::settings, and _SensorsApplet::size.
sensors_applet_icon_changed()
void sensors_applet_icon_changed (SensorsApplet * sensors_applet, GtkTreePath * path)
Definition at line 1134 of file sensors-applet.c.
References active_sensor_icon_changed(), and NULL.
sensors_applet_init()
void sensors_applet_init (SensorsApplet * sensors_applet)
Definition at line 1230 of file sensors-applet.c.
References _, _SensorsApplet::applet, DEFAULT_APPLET_SIZE, GETTEXT_PACKAGE, label, MATE_PANEL_APPLET_EXPAND_MINOR, mate_panel_applet_set_background_widget(), mate_panel_applet_set_flags(), mate_panel_applet_settings_new(), mate_panel_applet_setup_menu_from_file(), NULL, _SensorsApplet::plugins, _SensorsApplet::required_plugins, _SensorsApplet::sensors, SENSORS_APPLET_MENU_FILE, sensors_applet_plugins_load_all(), sensors_applet_settings_sort_sensors(), sensors_applet_update_active_sensors(), _SensorsApplet::sensors_hash_array, _SensorsApplet::settings, _SensorsApplet::size, TIMEOUT, and _SensorsApplet::timeout_id.
sensors_applet_load_icon()
GdkPixbuf * sensors_applet_load_icon (IconType icon_type)
Definition at line 788 of file sensors-applet.c.
References DEFAULT_ICON_SIZE, error, and NULL.
Referenced by sensor_config_dialog_create(), and sensors_applet_add_sensor().
sensors_applet_notify_active_sensor()
void sensors_applet_notify_active_sensor (ActiveSensor * active_sensor, NotifType notif_type)
Definition at line 250 of file sensors-applet.c.
References _, active_sensor_libnotify_notify(), _ActiveSensor::alarm_timeout, CELSIUS, CURRENT_SENSOR, DISPLAY_NOTIFICATIONS, FAHRENHEIT, FALSE, FAN_SENSOR, HIGH_ALARM, KELVIN, LABEL_COLUMN, LOW_ALARM, message(), MIN, NULL, PATH_COLUMN, _ActiveSensor::sensor_high_value, SENSOR_INTERFACE_ERROR, _ActiveSensor::sensor_low_value, _ActiveSensor::sensor_row, SENSOR_TYPE_COLUMN, _ActiveSensor::sensor_values, _SensorsApplet::sensors, _ActiveSensor::sensors_applet, _SensorsApplet::settings, TEMP_SENSOR, TEMPERATURE_SCALE, TIMEOUT, TRUE, UNITS_CELSIUS, UNITS_CURRENT, UNITS_FAHRENHEIT, UNITS_KELVIN, UNITS_RPM, UNITS_VOLTAGE, and VOLTAGE_SENSOR.
Referenced by active_sensor_update().
sensors_applet_notify_end()
void sensors_applet_notify_end (ActiveSensor * active_sensor, NotifType notif_type)
Definition at line 400 of file sensors-applet.c.
References active_sensor_libnotify_notify_end().
Referenced by active_sensor_alarm_off().
sensors_applet_notify_end_all()
void sensors_applet_notify_end_all (SensorsApplet * sensors_applet)
Definition at line 413 of file sensors-applet.c.
References _SensorsApplet::active_sensors, and NULL.
sensors_applet_reorder_sensors()
void sensors_applet_reorder_sensors (SensorsApplet * sensors_applet)
Definition at line 1098 of file sensors-applet.c.
References active_sensor_compare(), and _SensorsApplet::active_sensors.
Referenced by sensors_applet_settings_sort_sensors().
sensors_applet_sensor_disabled()
void sensors_applet_sensor_disabled (SensorsApplet * sensors_applet, GtkTreePath * path)
Definition at line 1104 of file sensors-applet.c.
References active_sensor_destroy(), _SensorsApplet::active_sensors, and NULL.
sensors_applet_sensor_enabled()
void sensors_applet_sensor_enabled (SensorsApplet * sensors_applet, GtkTreePath * path)
Definition at line 1081 of file sensors-applet.c.
References active_sensor_compare(), active_sensor_new(), active_sensor_update(), _SensorsApplet::active_sensors, and _SensorsApplet::sensors.
Referenced by sensors_applet_add_sensor().
sensors_applet_update_active_sensors()
gboolean sensors_applet_update_active_sensors (SensorsApplet * sensors_applet)
Definition at line 1146 of file sensors-applet.c.
References active_sensor_update(), _SensorsApplet::active_sensors, FALSE, and TRUE.
Referenced by prefs_dialog_close(), sensors_applet_display_layout_changed(), and sensors_applet_init().
sensors_applet_update_sensor()
void sensors_applet_update_sensor (SensorsApplet * sensors_applet, GtkTreePath * path)
Definition at line 1123 of file sensors-applet.c.
References active_sensor_update(), and NULL.