MATE Desktop Environment: sensors-applet-settings.c File Reference
sensors-applet-settings.c File Reference
#include <string.h>
#include <glib.h>
#include "sensors-applet.h"
#include "sensors-applet-settings.h"
Macros
#define GSGVTS "s"
#define GSGVTSA "as"
Functions
gchar * sensors_applet_settings_get_unique_id (const gchar *interface, const gchar *id, const gchar *path)
gboolean sensors_applet_settings_load_sensors (SensorsApplet *sensors_applet)
gboolean sensors_applet_settings_sort_sensors (SensorsApplet *sensors_applet)
gboolean sensors_applet_settings_save_sensors (SensorsApplet *sensors_applet)
Macro Definition Documentation
GSGVTS
#define GSGVTS "s"
Definition at line 37 of file sensors-applet-settings.c.
Referenced by sensors_applet_settings_load_sensors(), and sensors_applet_settings_save_sensors().
GSGVTSA
#define GSGVTSA "as"
Definition at line 39 of file sensors-applet-settings.c.
Referenced by sensors_applet_settings_load_sensors(), and sensors_applet_settings_save_sensors().
Function Documentation
sensors_applet_settings_get_unique_id()
gchar * sensors_applet_settings_get_unique_id (const gchar * interface, const gchar * id, const gchar * path)
Definition at line 41 of file sensors-applet-settings.c.
References NULL.
Referenced by sensors_applet_add_sensor(), and sensors_applet_settings_save_sensors().
sensors_applet_settings_load_sensors()
gboolean sensors_applet_settings_load_sensors (SensorsApplet * sensors_applet)
Definition at line 64 of file sensors-applet-settings.c.
References ALARM_ENABLED, ALARM_TIMEOUT, _SensorsApplet::applet, ENABLED, GRAPH_COLOR, GSGVTS, GSGVTSA, HIGH_ALARM_COMMAND, HIGH_VALUE, ICON_TYPE, ID, INTERFACE, LABEL, LOW_ALARM_COMMAND, LOW_VALUE, mate_panel_applet_get_preferences_path(), MULTIPLIER, NULL, OFFSET, PATH, SENSOR_TYPE, sensors_applet_add_sensor(), _SensorsApplet::settings, and TRUE.
sensors_applet_settings_save_sensors()
gboolean sensors_applet_settings_save_sensors (SensorsApplet * sensors_applet)
Definition at line 537 of file sensors-applet-settings.c.
References ALARM_ENABLE_COLUMN, ALARM_ENABLED, ALARM_TIMEOUT, ALARM_TIMEOUT_COLUMN, _SensorsApplet::applet, ENABLE_COLUMN, ENABLED, GRAPH_COLOR, GRAPH_COLOR_COLUMN, GSGVTS, GSGVTSA, HIGH_ALARM_COMMAND, HIGH_ALARM_COMMAND_COLUMN, HIGH_VALUE, HIGH_VALUE_COLUMN, ICON_TYPE, ICON_TYPE_COLUMN, ID, ID_COLUMN, INTERFACE, INTERFACE_COLUMN, LABEL, LABEL_COLUMN, LOW_ALARM_COMMAND, LOW_ALARM_COMMAND_COLUMN, LOW_VALUE, LOW_VALUE_COLUMN, mate_panel_applet_get_preferences_path(), MULTIPLIER, MULTIPLIER_COLUMN, NULL, OFFSET, OFFSET_COLUMN, PATH, PATH_COLUMN, SENSOR_TYPE, SENSOR_TYPE_COLUMN, _SensorsApplet::sensors, sensors_applet_settings_get_unique_id(), _SensorsApplet::settings, and TRUE.
Referenced by prefs_dialog_close().
sensors_applet_settings_sort_sensors()
gboolean sensors_applet_settings_sort_sensors (SensorsApplet * sensors_applet)
Definition at line 432 of file sensors-applet-settings.c.
References FALSE, NULL, sensors_applet_reorder_sensors(), _SensorsApplet::sensors_hash_array, _SensorsApplet::settings, and TRUE.
Referenced by sensors_applet_init().