MATE Desktop Environment: session.c File Reference
session.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include "session.h"
#include <X11/Xatom.h>
#include <time.h>
#include <sys/wait.h>
Functions
void meta_session_init (const char *client_id, const char *save_file)
void meta_session_shutdown (void)
const MetaWindowSessionInfo * meta_window_lookup_saved_state (MetaWindow *window)
void meta_window_release_saved_state (const MetaWindowSessionInfo *info)
Function Documentation
meta_session_init()
void meta_session_init (const char * client_id, const char * save_file)
Definition at line 37 of file session.c.
References META_DEBUG_SM.
Referenced by main().
meta_session_shutdown()
void meta_session_shutdown (void)
Definition at line 44 of file session.c.
meta_window_lookup_saved_state()
const MetaWindowSessionInfo * meta_window_lookup_saved_state (MetaWindow * window)
Definition at line 50 of file session.c.
References NULL.
Referenced by meta_window_new_with_attrs().
meta_window_release_saved_state()
void meta_window_release_saved_state (const MetaWindowSessionInfo * info)
Definition at line 56 of file session.c.
Referenced by meta_window_new_with_attrs().