MATE Desktop Environment: shares.c File Reference
shares.c File Reference
#include <glib/gi18n-lib.h>
#include <string.h>
#include <time.h>
#include <sys/types.h>
#include <sys/wait.h>
#include "shares.h"
Macros
#define NET_USERSHARE_ARGV0 "net"
#define NUM_CALLS_BETWEEN_TIMESTAMP_UPDATES 100
#define TIMESTAMP_THRESHOLD 10 /* seconds */
#define KEY_PATH "path"
#define KEY_COMMENT "comment"
#define KEY_ACL "usershare_acl"
#define KEY_GUEST_OK "guest_ok"
Functions
gboolean shares_supports_guest_ok (gboolean *supports_guest_ok_ret, GError **error)
GQuark shares_error_quark (void)
void shares_free_share_info (ShareInfo *info)
gboolean shares_get_path_is_shared (const char *path, gboolean *ret_is_shared, GError **error)
gboolean shares_get_share_info_for_path (const char *path, ShareInfo **ret_share_info, GError **error)
gboolean shares_get_share_name_exists (const char *share_name, gboolean *ret_exists, GError **error)
gboolean shares_get_share_info_for_share_name (const char *share_name, ShareInfo **ret_share_info, GError **error)
gboolean shares_modify_share (const char *old_path, ShareInfo *info, GError **error)
gboolean shares_get_share_info_list (GSList **ret_info_list, GError **error)
void shares_free_share_info_list (GSList *list)
void shares_set_debug (gboolean error_on_refresh, gboolean error_on_add, gboolean error_on_modify, gboolean error_on_remove)
Macro Definition Documentation
KEY_ACL
#define KEY_ACL "usershare_acl"
Definition at line 31 of file shares.c.
KEY_COMMENT
#define KEY_COMMENT "comment"
Definition at line 30 of file shares.c.
KEY_GUEST_OK
#define KEY_GUEST_OK "guest_ok"
Definition at line 32 of file shares.c.
KEY_PATH
#define KEY_PATH "path"
Definition at line 29 of file shares.c.
NET_USERSHARE_ARGV0
#define NET_USERSHARE_ARGV0 "net"
Definition at line 18 of file shares.c.
NUM_CALLS_BETWEEN_TIMESTAMP_UPDATES
#define NUM_CALLS_BETWEEN_TIMESTAMP_UPDATES 100
Definition at line 24 of file shares.c.
TIMESTAMP_THRESHOLD
#define TIMESTAMP_THRESHOLD 10 /* seconds */
Definition at line 25 of file shares.c.
Function Documentation
shares_error_quark()
GQuark shares_error_quark (void)
Definition at line 761 of file shares.c.
shares_free_share_info()
void shares_free_share_info (ShareInfo * info)
shares_free_share_info: @info: A ShareInfo structure.
Frees a ShareInfo structure.
Definition at line 778 of file shares.c.
References NULL.
Referenced by shares_free_share_info_list().
shares_free_share_info_list()
void shares_free_share_info_list (GSList * list)
shares_free_share_info_list: @list: List of ShareInfo structures, or NULL.
Frees a list of ShareInfo structures as returned by shares_get_share_info_list().
Definition at line 996 of file shares.c.
References shares_free_share_info().
shares_get_path_is_shared()
gboolean shares_get_path_is_shared (const char * path, gboolean * ret_is_shared, GError ** error)
shares_get_path_is_shared: @path: A full path name ("/foo/bar/baz") in file system encoding. @ret_is_shared: Location to store result value (TRUE if the path is shared, FALSE otherwise) @error: Location to store error, or NULL.
Checks whether a path is shared through Samba.
Return value: TRUE if the info could be queried successfully, FALSE otherwise. If this function returns FALSE, an error code will be returned in the @error argument, and *@ret_is_shared will be set to FALSE.
Definition at line 801 of file shares.c.
References error, FALSE, NULL, and TRUE.
shares_get_share_info_for_path()
gboolean shares_get_share_info_for_path (const char * path, ShareInfo ** ret_share_info, GError ** error)
shares_get_share_info_for_path: @path: A full path name ("/foo/bar/baz") in file system encoding. @ret_share_info: Location to store result with the share's info - on return, will be non-NULL if the path is indeed shared, or NULL if the path is not shared. You must free the non-NULL value with shares_free_share_info(). @error: Location to store error, or NULL.
Queries the information for a shared path: its share name, its read-only status, etc.
Return value: TRUE if the info could be queried successfully, FALSE otherwise. If this function returns FALSE, an error code will be returned in the @error argument, and *@ret_share_info will be set to NULL.
Definition at line 831 of file shares.c.
References error, FALSE, NULL, and TRUE.
shares_get_share_info_for_share_name()
gboolean shares_get_share_info_for_share_name (const char * share_name, ShareInfo ** ret_share_info, GError ** error)
shares_get_share_info_for_share_name: @share_name: Name of a share. @ret_share_info: Location to store result with the share's info - on return, will be non-NULL if there is a share for the specified name, or NULL if no share has such name. You must free the non-NULL value with shares_free_share_info(). @error: Location to store error, or NULL.
Queries the information for the share which has a specific name.
Return value: TRUE if the info could be queried successfully, FALSE otherwise. If this function returns FALSE, an error code will be returned in the @error argument, and *@ret_share_info will be set to NULL.
Definition at line 894 of file shares.c.
References error, FALSE, NULL, and TRUE.
shares_get_share_info_list()
gboolean shares_get_share_info_list (GSList ** ret_info_list, GError ** error)
shares_get_share_info_list: @ret_info_list: Location to store the return value, which is a list of ShareInfo structures. Free this with shares_free_share_info_list(). @error: Location to store error, or NULL.
Gets the list of shared folders and their information.
Return value: TRUE if the info could be queried successfully, FALSE otherwise. If this function returns FALSE, an error code will be returned in the @error argument, and *@ret_info_list will be set to NULL.
Definition at line 973 of file shares.c.
References error, FALSE, NULL, and TRUE.
shares_get_share_name_exists()
gboolean shares_get_share_name_exists (const char * share_name, gboolean * ret_exists, GError ** error)
shares_get_share_name_exists: @share_name: Name of a share. @ret_exists: Location to store return value; TRUE if the share name exists, FALSE otherwise.
Queries whether a share name already exists in the user's list of shares.
Return value: TRUE if the info could be queried successfully, FALSE otherwise. If this function returns FALSE, an error code will be returned in the @error argument, and *@ret_exists will be set to FALSE.
Definition at line 862 of file shares.c.
References error, FALSE, NULL, and TRUE.
shares_modify_share()
gboolean shares_modify_share (const char * old_path, ShareInfo * info, GError ** error)
shares_modify_share: @old_path: Path of the share to modify, or NULL. @info: Info of the share to modify/add, or NULL to delete a share. @error: Location to store error, or NULL.
Can add, modify, or delete shares. To add a share, pass NULL for @old_path, and a non-null @info. To modify a share, pass a non-null @old_path and non-null @info; in this case, @info->path must have the same contents as @old_path. To remove a share, pass a non-NULL @old_path and a NULL @info.
Return value: TRUE if the share could be modified, FALSE otherwise. If this returns FALSE, then the error information will be placed in @error.
Definition at line 928 of file shares.c.
References error, FALSE, and NULL.
shares_set_debug()
void shares_set_debug (gboolean error_on_refresh, gboolean error_on_add, gboolean error_on_modify, gboolean error_on_remove)
Definition at line 1008 of file shares.c.
shares_supports_guest_ok()
gboolean shares_supports_guest_ok (gboolean * supports_guest_ok_ret, GError ** error)
shares_supports_guest_ok: @supports_guest_ok_ret: Location to store whether "usershare allow guests" is enabled. @error: Location to store error, or NULL.
Determines whether the option "usershare allow guests" is enabled in samba config as shown by testparm.
Return value: TRUE if if the info could be queried successfully, FALSE otherwise. If this function returns FALSE, an error code will be returned in the @error argument, and *@ret_info_list will be set to FALSE.
Definition at line 520 of file shares.c.
References _, error, FALSE, message(), NULL, SHARES_ERROR, SHARES_ERROR_FAILED, and TRUE.