MATE Desktop Environment: skey-popup.c File Reference
skey-popup.c File Reference
#include <config.h>
#include "terminal-intl.h"
#include "terminal-util.h"
#include "terminal-screen.h"
#include "skey-popup.h"
#include "skey/skey.h"
#include <stdlib.h>
#include <string.h>
Macros
#define SKEY_PREFIX "s/key "
#define OTP_PREFIX "otp-"
Functions
void terminal_skey_do_popup (GtkWindow *window, TerminalScreen *screen, const gchar *skey_match)
Macro Definition Documentation
OTP_PREFIX
#define OTP_PREFIX "otp-"
Definition at line 32 of file skey-popup.c.
SKEY_PREFIX
#define SKEY_PREFIX "s/key "
Definition at line 31 of file skey-popup.c.
Referenced by terminal_skey_do_popup().
Function Documentation
terminal_skey_do_popup()
void terminal_skey_do_popup (GtkWindow * window, TerminalScreen * screen, const gchar * skey_match)
Definition at line 150 of file skey-popup.c.
References _, data, hash, label, MD5, NULL, SKEY_PREFIX, terminal_util_dialog_response_on_delete(), terminal_util_load_builder_resource(), terminal_util_show_error_dialog(), and TRUE.