MATE Desktop Environment: sn-dbus-menu-item.h File Reference
sn-dbus-menu-item.h File Reference
#include <gtk/gtk.h>
Classes
struct SnShortcut
struct SnDBusMenuItem
Functions
SnDBusMenuItem * sn_dbus_menu_item_new (GVariant *props)
void sn_dbus_menu_item_free (gpointer data)
void sn_dbus_menu_item_update_props (SnDBusMenuItem *item, GVariant *props)
void sn_dbus_menu_item_remove_props (SnDBusMenuItem *item, GVariant *props)
Function Documentation
sn_dbus_menu_item_free()
void sn_dbus_menu_item_free (gpointer data)
Definition at line 256 of file sn-dbus-menu-item.c.
References data, item, and NULL.
sn_dbus_menu_item_new()
SnDBusMenuItem * sn_dbus_menu_item_new (GVariant * props)
Definition at line 126 of file sn-dbus-menu-item.c.
References FALSE, item, MATE_IMAGE_MENU_ITEM, mate_image_menu_item_new(), mate_image_menu_item_set_image(), NULL, and TRUE.
sn_dbus_menu_item_remove_props()
void sn_dbus_menu_item_remove_props (SnDBusMenuItem * item, GVariant * props)
Definition at line 412 of file sn-dbus-menu-item.c.
References item, MATE_IMAGE_MENU_ITEM, mate_image_menu_item_set_image(), MATE_IS_IMAGE_MENU_ITEM, NULL, and TRUE.
sn_dbus_menu_item_update_props()
void sn_dbus_menu_item_update_props (SnDBusMenuItem * item, GVariant * props)
Definition at line 282 of file sn-dbus-menu-item.c.
References FALSE, item, MATE_IMAGE_MENU_ITEM, mate_image_menu_item_set_image(), NULL, and TRUE.