MATE Desktop Environment: sound-theme-file-utils.c File Reference
sound-theme-file-utils.c File Reference
#include <config.h>
#include <glib/gstdio.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <utime.h>
#include <strings.h>
#include "sound-theme-file-utils.h"
Macros
#define CUSTOM_THEME_NAME "__custom"
Functions
void custom_theme_update_time (void)
char * custom_theme_dir_path (const char *child)
void delete_custom_theme_dir (void)
gboolean custom_theme_dir_is_empty (void)
void delete_old_files (const char **sounds)
void delete_disabled_files (const char **sounds)
void add_disabled_file (const char **sounds)
void add_custom_file (const char **sounds, const char *filename)
void create_custom_theme (const char *parent)
Detailed Description
capplet_file_delete_recursive :
@error :
A utility routine to delete files and/or directories, including non-empty directories.
Definition in file sound-theme-file-utils.c.
Macro Definition Documentation
CUSTOM_THEME_NAME
#define CUSTOM_THEME_NAME "__custom"
Definition at line 30 of file sound-theme-file-utils.c.
Function Documentation
add_custom_file()
void add_custom_file (const char ** sounds, const char * filename)
Definition at line 256 of file sound-theme-file-utils.c.
References custom_theme_dir_path(), name, and NULL.
add_disabled_file()
void add_disabled_file (const char ** sounds)
Definition at line 236 of file sound-theme-file-utils.c.
References custom_theme_dir_path(), name, and NULL.
create_custom_theme()
void create_custom_theme (const char * parent)
Definition at line 281 of file sound-theme-file-utils.c.
References _, custom_theme_dir_path(), custom_theme_update_time(), data, and NULL.
custom_theme_dir_is_empty()
gboolean custom_theme_dir_is_empty (void)
Definition at line 146 of file sound-theme-file-utils.c.
References custom_theme_dir_path(), error, FALSE, NULL, and TRUE.
custom_theme_dir_path()
char * custom_theme_dir_path (const char * child)
Definition at line 45 of file sound-theme-file-utils.c.
References CUSTOM_THEME_NAME, and NULL.
Referenced by add_custom_file(), add_disabled_file(), create_custom_theme(), custom_theme_dir_is_empty(), custom_theme_update_time(), and delete_custom_theme_dir().
custom_theme_update_time()
void custom_theme_update_time (void)
Definition at line 35 of file sound-theme-file-utils.c.
References custom_theme_dir_path(), and NULL.
Referenced by create_custom_theme().
delete_custom_theme_dir()
void delete_custom_theme_dir (void)
Definition at line 131 of file sound-theme-file-utils.c.
References capplet_file_delete_recursive(), custom_theme_dir_path(), and NULL.
delete_disabled_files()
void delete_disabled_files (const char ** sounds)
Definition at line 215 of file sound-theme-file-utils.c.
References NULL.
delete_old_files()
void delete_old_files (const char ** sounds)
Definition at line 205 of file sound-theme-file-utils.c.
References NULL.