MATE Desktop Environment: sp-epsf.c File Reference
sp-epsf.c File Reference
#include <config.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
#include "mdvi.h"
#include "private.h"
Macros
#define LLX 0
#define LLY 1
#define URX 2
#define URY 3
#define RWI 4
#define RHI 5
#define HOFF 6
#define VOFF 7
#define HSIZE 8
#define VSIZE 9
#define HSCALE 10
#define VSCALE 11
#define ANGLE 12
#define NKEYS (sizeof(keys) / sizeof(keys[0]))
Functions
void epsf_special __PROTO ((DviContext *dvi, char *prefix, char *arg))
void epsf_special (DviContext *dvi, char *prefix, char *arg)
Macro Definition Documentation
ANGLE
#define ANGLE 12
Definition at line 50 of file sp-epsf.c.
HOFF
#define HOFF 6
Definition at line 44 of file sp-epsf.c.
HSCALE
#define HSCALE 10
Definition at line 48 of file sp-epsf.c.
HSIZE
#define HSIZE 8
Definition at line 46 of file sp-epsf.c.
LLX
#define LLX 0
Definition at line 38 of file sp-epsf.c.
LLY
#define LLY 1
Definition at line 39 of file sp-epsf.c.
NKEYS
#define NKEYS (sizeof(keys) / sizeof(keys[0]))
RHI
#define RHI 5
Definition at line 43 of file sp-epsf.c.
RWI
#define RWI 4
Definition at line 42 of file sp-epsf.c.
URX
#define URX 2
Definition at line 40 of file sp-epsf.c.
URY
#define URY 3
Definition at line 41 of file sp-epsf.c.
VOFF
#define VOFF 7
Definition at line 45 of file sp-epsf.c.
VSCALE
#define VSCALE 11
Definition at line 49 of file sp-epsf.c.
VSIZE
#define VSIZE 9
Definition at line 47 of file sp-epsf.c.
Function Documentation
__PROTO()
void epsf_special __PROTO ((DviContext *dvi, char *prefix, char *arg))
References epsf_special(), name, and prefix.
epsf_special()
void epsf_special (DviContext * dvi, char * prefix, char * arg)
Definition at line 234 of file sp-epsf.c.
References _DviContext::device, _DviParams::dpi, _DviDevice::draw_ps, _DviDevice::draw_rule, _DviContext::filename, FROUND, _DviState::hh, _DviParams::hshrink, _DviParams::mag, mdvi_build_path_from_cwd(), mdvi_free(), mdvi_malloc(), mdvi_strrstr(), NULL, _DviContext::params, _DviContext::pos, prefix, special(), _DviParams::vdpi, _DviParams::vshrink, and _DviState::vv.
Referenced by __PROTO(), and SPECIAL().