MATE Desktop Environment: gpm-common.c File Reference
gpm-common.c File Reference
#include "config.h"
#include <glib.h>
#include <string.h>
#include <glib/gi18n.h>
#include <gdk/gdk.h>
#include <gtk/gtk.h>
#include "gpm-common.h"
Functions
gchar * gpm_get_timestring (guint time_secs)
guint gpm_discrete_from_percent (guint percentage, guint levels)
guint gpm_discrete_to_percent (guint discrete, guint levels)
void gpm_help_display (const gchar *link_id)
gboolean gpm_notebook_scroll_event_cb (GtkWidget *widget, GdkEventScroll *event)
Function Documentation
gpm_discrete_from_percent()
guint gpm_discrete_from_percent (guint percentage, guint levels)
gpm_discrete_from_percent: @percentage: The percentage to convert @levels: The number of discrete levels
We have to be carefull when converting from %->discrete as precision is very important if we want the highest value.
Return value: The discrete value for this percentage.
Definition at line 92 of file src/gpm-common.c.
gpm_discrete_to_percent()
guint gpm_discrete_to_percent (guint discrete, guint levels)
gpm_discrete_to_percent: @hw: The discrete level @levels: The number of discrete levels
We have to be carefull when converting from discrete->%.
Return value: The percentage for this discrete value.
Definition at line 117 of file src/gpm-common.c.
gpm_get_timestring()
gchar * gpm_get_timestring (guint time_secs)
gpm_get_timestring: @time_secs: The time value to convert in seconds @cookie: The cookie we are looking for
Returns a localised timestring
Return value: The time string, e.g. "2 hours 3 minutes"
Definition at line 43 of file src/gpm-common.c.
References _, int(), and NULL.
Referenced by gpm_upower_get_device_description(), and gpm_upower_get_device_summary().
gpm_help_display()
void gpm_help_display (const gchar * link_id)
gpm_help_display: @link_id: Subsection of mate-power-manager help section
Definition at line 137 of file src/gpm-common.c.
References error, and NULL.
gpm_notebook_scroll_event_cb()
gboolean gpm_notebook_scroll_event_cb (GtkWidget * widget, GdkEventScroll * event)
Definition at line 161 of file src/gpm-common.c.
References FALSE, NULL, and TRUE.
Referenced by main().