MATE Desktop Environment: stickynotes_applet.c File Reference
stickynotes_applet.c File Reference
#include <config.h>
#include <string.h>
#include "stickynotes_applet.h"
#include "stickynotes_applet_callbacks.h"
#include "stickynotes.h"
#include <gtk/gtk.h>
#include <gdk/gdkx.h>
Functions
PANEL_APPLET_FACTORY ("StickyNotesAppletFactory", PANEL_TYPE_APPLET, "stickynotes_applet", stickynotes_applet_factory, NULL)
void stickynotes_applet_init (MatePanelApplet *mate_panel_applet)
void stickynotes_applet_init_prefs (void)
StickyNotesApplet * stickynotes_applet_new (MatePanelApplet *mate_panel_applet)
void stickynotes_applet_update_icon (StickyNotesApplet *applet)
void stickynotes_applet_update_prefs (void)
void stickynotes_applet_update_menus (void)
void stickynotes_applet_update_tooltips (void)
void stickynotes_applet_panel_icon_get_geometry (int *x, int *y, int *width, int *height)
Variables
StickyNotes * stickynotes = NULL
Function Documentation
PANEL_APPLET_FACTORY()
PANEL_APPLET_FACTORY ("StickyNotesAppletFactory" , PANEL_TYPE_APPLET , "stickynotes_applet" , stickynotes_applet_factory , NULL)
Definition at line 87 of file stickynotes_applet.c.
References b, dest, NULL, and PANEL_TYPE_APPLET.
stickynotes_applet_init()
void stickynotes_applet_init (MatePanelApplet * mate_panel_applet)
Definition at line 165 of file stickynotes_applet.c.
References _, GDK_IS_X11_DISPLAY, install_check_click_on_desktop(), int(), mate_panel_applet_get_size(), NULL, preferences_apply_cb(), stickynotes, stickynotes_applet_init_prefs(), stickynotes_load(), STICKYNOTES_SCHEMA, and TRUE.
stickynotes_applet_init_prefs()
void stickynotes_applet_init_prefs (void)
Definition at line 243 of file stickynotes_applet.c.
References FALSE, NULL, preferences_color_cb(), preferences_delete_cb(), preferences_font_cb(), preferences_response_cb(), preferences_save_cb(), stickynotes, and stickynotes_applet_update_prefs().
Referenced by stickynotes_applet_init().
stickynotes_applet_new()
StickyNotesApplet * stickynotes_applet_new (MatePanelApplet * mate_panel_applet)
Definition at line 376 of file stickynotes_applet.c.
References _, action, StickyNotesApplet::action_group, applet_button_cb(), applet_change_orient_cb(), applet_cross_cb(), applet_destroy_cb(), applet_focus_cb(), applet_key_cb(), applet_size_allocate_cb(), StickyNotesApplet::destroy_all_dialog, FALSE, GETTEXT_PACKAGE, MATE_PANEL_APPLET_EXPAND_MINOR, mate_panel_applet_get_locked_down(), mate_panel_applet_get_orient(), mate_panel_applet_get_size(), mate_panel_applet_set_flags(), mate_panel_applet_setup_menu_from_resource(), StickyNotesApplet::menu_tip, NULL, StickyNotesApplet::panel_orient, StickyNotesApplet::panel_size, StickyNotesApplet::prelighted, stickynotes_applet_update_icon(), StickyNotesApplet::w_applet, and StickyNotesApplet::w_image.
stickynotes_applet_panel_icon_get_geometry()
void stickynotes_applet_panel_icon_get_geometry (int * x, int * y, int * width, int * height)
Definition at line 654 of file stickynotes_applet.c.
References NULL, stickynotes, and StickyNotesApplet::w_image.
Referenced by stickynote_set_visible().
stickynotes_applet_update_icon()
void stickynotes_applet_update_icon (StickyNotesApplet * applet)
Definition at line 458 of file stickynotes_applet.c.
References StickyNotesApplet::panel_size, StickyNotesApplet::prelighted, stickynotes, and StickyNotesApplet::w_image.
Referenced by applet_cross_cb(), applet_focus_cb(), applet_size_allocate_cb(), and stickynotes_applet_new().
stickynotes_applet_update_menus()
void stickynotes_applet_update_menus (void)
Definition at line 579 of file stickynotes_applet.c.
References action, StickyNotesApplet::action_group, FALSE, StickyNote::locked, NULL, stickynotes, and TRUE.
Referenced by preferences_apply_cb(), and stickynote_set_locked().
stickynotes_applet_update_prefs()
void stickynotes_applet_update_prefs (void)
Definition at line 489 of file stickynotes_applet.c.
References MAX, and stickynotes.
Referenced by menu_preferences_cb(), preferences_apply_cb(), and stickynotes_applet_init_prefs().
stickynotes_applet_update_tooltips()
void stickynotes_applet_update_tooltips (void)
Definition at line 620 of file stickynotes_applet.c.
References _, StickyNotesApplet::menu_tip, stickynotes, and StickyNotesApplet::w_applet.
Referenced by stickynotes_add(), and stickynotes_remove().
Variable Documentation
stickynotes
StickyNotes* stickynotes = NULL
Definition at line 29 of file stickynotes_applet.c.
Referenced by applet_destroy_cb(), menu_preferences_cb(), menu_toggle_lock_cb(), preferences_apply_cb(), preferences_color_cb(), preferences_font_cb(), preferences_save_cb(), stickynote_change_properties(), stickynote_set_color(), stickynote_set_font(), stickynote_set_title(), stickynote_set_visible(), stickynotes_add(), stickynotes_applet_init(), stickynotes_applet_init_prefs(), stickynotes_applet_panel_icon_get_geometry(), stickynotes_applet_update_icon(), stickynotes_applet_update_menus(), stickynotes_applet_update_prefs(), stickynotes_applet_update_tooltips(), stickynotes_load(), stickynotes_remove(), and stickynotes_save_now().