MATE Desktop Environment: stickynotes_callbacks.c File Reference
stickynotes_callbacks.c File Reference
#include <config.h>
#include <stickynotes_callbacks.h>
Functions
gboolean stickynote_toggle_lock_cb (GtkWidget *widget, StickyNote *note)
gboolean stickynote_close_cb (GtkWidget *widget, StickyNote *note)
gboolean stickynote_resize_cb (GtkWidget *widget, GdkEventButton *event, StickyNote *note)
gboolean stickynote_move_cb (GtkWidget *widget, GdkEventButton *event, StickyNote *note)
gboolean stickynote_configure_cb (GtkWidget *widget, GdkEventConfigure *event, StickyNote *note)
gboolean stickynote_delete_cb (GtkWidget *widget, GdkEvent *event, StickyNote *note)
gboolean stickynote_show_popup_menu (GtkWidget *widget, GdkEventButton *event, GtkWidget *popup_menu)
gboolean stickynote_keypress_cb (GtkWidget *widget, GdkEventKey *event, GtkMenu *popup_menu)
void popup_create_cb (GtkWidget *widget, StickyNote *note)
void popup_destroy_cb (GtkWidget *widget, StickyNote *note)
void popup_toggle_lock_cb (GtkCheckMenuItem *item, StickyNote *note)
void popup_properties_cb (GtkWidget *widget, StickyNote *note)
void properties_apply_title_cb (StickyNote *note)
void properties_apply_color_cb (StickyNote *note)
void properties_apply_font_cb (StickyNote *note)
void properties_color_cb (GtkWidget *button, StickyNote *note)
void properties_font_cb (GtkWidget *button, StickyNote *note)
void properties_activate_cb (GtkWidget *widget, StickyNote *note)
Function Documentation
popup_create_cb()
void popup_create_cb (GtkWidget * widget, StickyNote * note)
Definition at line 171 of file stickynotes_callbacks.c.
References stickynotes_add(), and StickyNote::w_window.
popup_destroy_cb()
void popup_destroy_cb (GtkWidget * widget, StickyNote * note)
Definition at line 179 of file stickynotes_callbacks.c.
References stickynotes_remove().
popup_properties_cb()
void popup_properties_cb (GtkWidget * widget, StickyNote * note)
Definition at line 196 of file stickynotes_callbacks.c.
References stickynote_change_properties().
popup_toggle_lock_cb()
void popup_toggle_lock_cb (GtkCheckMenuItem * item, StickyNote * note)
Definition at line 187 of file stickynotes_callbacks.c.
References item, and stickynote_set_locked().
properties_activate_cb()
void properties_activate_cb (GtkWidget * widget, StickyNote * note)
Definition at line 266 of file stickynotes_callbacks.c.
References StickyNote::w_properties.
properties_apply_color_cb()
void properties_apply_color_cb (StickyNote * note)
Definition at line 212 of file stickynotes_callbacks.c.
References NULL, stickynote_set_color(), TRUE, StickyNote::w_color, StickyNote::w_def_color, and StickyNote::w_font_color.
Referenced by properties_color_cb().
properties_apply_font_cb()
void properties_apply_font_cb (StickyNote * note)
Definition at line 237 of file stickynotes_callbacks.c.
References NULL, stickynote_set_font(), TRUE, StickyNote::w_def_font, and StickyNote::w_font.
properties_apply_title_cb()
void properties_apply_title_cb (StickyNote * note)
Definition at line 204 of file stickynotes_callbacks.c.
References stickynote_set_title(), and StickyNote::w_entry.
properties_color_cb()
void properties_color_cb (GtkWidget * button, StickyNote * note)
Definition at line 249 of file stickynotes_callbacks.c.
References properties_apply_color_cb().
properties_font_cb()
void properties_font_cb (GtkWidget * button, StickyNote * note)
Definition at line 257 of file stickynotes_callbacks.c.
References stickynote_set_font(), and TRUE.
stickynote_close_cb()
gboolean stickynote_close_cb (GtkWidget * widget, StickyNote * note)
Definition at line 35 of file stickynotes_callbacks.c.
References stickynotes_remove(), and TRUE.
stickynote_configure_cb()
gboolean stickynote_configure_cb (GtkWidget * widget, GdkEventConfigure * event, StickyNote * note)
Definition at line 90 of file stickynotes_callbacks.c.
References FALSE, StickyNote::h, stickynotes_save(), StickyNote::w, StickyNote::x, and StickyNote::y.
stickynote_delete_cb()
gboolean stickynote_delete_cb (GtkWidget * widget, GdkEvent * event, StickyNote * note)
Definition at line 106 of file stickynotes_callbacks.c.
References stickynotes_remove(), and TRUE.
stickynote_keypress_cb()
gboolean stickynote_keypress_cb (GtkWidget * widget, GdkEventKey * event, GtkMenu * popup_menu)
Definition at line 132 of file stickynotes_callbacks.c.
References FALSE, NULL, and TRUE.
stickynote_move_cb()
gboolean stickynote_move_cb (GtkWidget * widget, GdkEventButton * event, StickyNote * note)
Definition at line 72 of file stickynotes_callbacks.c.
References FALSE, stickynote_change_properties(), TRUE, and StickyNote::w_window.
stickynote_resize_cb()
gboolean stickynote_resize_cb (GtkWidget * widget, GdkEventButton * event, StickyNote * note)
Definition at line 44 of file stickynotes_callbacks.c.
References FALSE, TRUE, StickyNote::w_resize_se, and StickyNote::w_window.
stickynote_show_popup_menu()
gboolean stickynote_show_popup_menu (GtkWidget * widget, GdkEventButton * event, GtkWidget * popup_menu)
Definition at line 117 of file stickynotes_callbacks.c.
References FALSE.
stickynote_toggle_lock_cb()
gboolean stickynote_toggle_lock_cb (GtkWidget * widget, StickyNote * note)
Definition at line 25 of file stickynotes_callbacks.c.
References StickyNote::locked, stickynote_set_locked(), and TRUE.