MATE Desktop Environment: parser_state Struct Reference
parser_state Struct Reference
#include <parser.h>
Public Attributes
ParseNode * root
ParseNode * right_most
LexerState * lexer
guint depth_level
MPEquationOptions * options
int error
char * error_token
MPNumber ret
int(* variable_is_defined)(struct parser_state *state, const char *name)
int(* get_variable)(struct parser_state *state, const char *name, MPNumber *z)
void(* set_variable)(struct parser_state *state, const char *name, const MPNumber *x)
int(* function_is_defined)(struct parser_state *state, const char *name)
int(* get_function)(struct parser_state *state, const char *name, const MPNumber *x, MPNumber *z)
int(* convert)(struct parser_state *state, const MPNumber *x, const char *x_units, const char *z_units, MPNumber *z)
Detailed Description
Definition at line 52 of file mate-calc/src/parser.h.
Member Data Documentation
convert
int(* parser_state::convert) (struct parser_state *state, const MPNumber *x, const char *x_units, const char *z_units, MPNumber *z)
Definition at line 67 of file mate-calc/src/parser.h.
Referenced by pf_convert_1(), and pf_convert_number().
depth_level
guint parser_state::depth_level
Definition at line 57 of file mate-calc/src/parser.h.
error
int parser_state::error
Definition at line 59 of file mate-calc/src/parser.h.
error_token
char* parser_state::error_token
Definition at line 60 of file mate-calc/src/parser.h.
function_is_defined
int(* parser_state::function_is_defined) (struct parser_state *state, const char *name)
Definition at line 65 of file mate-calc/src/parser.h.
get_function
int(* parser_state::get_function) (struct parser_state *state, const char *name, const MPNumber *x, MPNumber *z)
Definition at line 66 of file mate-calc/src/parser.h.
Referenced by pf_apply_func(), pf_apply_func_with_npower(), and pf_apply_func_with_power().
get_variable
int(* parser_state::get_variable) (struct parser_state *state, const char *name, MPNumber *z)
Definition at line 63 of file mate-calc/src/parser.h.
Referenced by pf_get_variable(), and pf_get_variable_with_power().
lexer
LexerState* parser_state::lexer
Definition at line 56 of file mate-calc/src/parser.h.
options
MPEquationOptions* parser_state::options
Definition at line 58 of file mate-calc/src/parser.h.
Referenced by pf_constant(), pf_convert_number(), and pf_do_not().
ret
MPNumber parser_state::ret
Definition at line 61 of file mate-calc/src/parser.h.
right_most
ParseNode* parser_state::right_most
Definition at line 55 of file mate-calc/src/parser.h.
root
ParseNode* parser_state::root
Definition at line 54 of file mate-calc/src/parser.h.
set_variable
void(* parser_state::set_variable) (struct parser_state *state, const char *name, const MPNumber *x)
Definition at line 64 of file mate-calc/src/parser.h.
Referenced by pf_set_var().
variable_is_defined
int(* parser_state::variable_is_defined) (struct parser_state *state, const char *name)
Definition at line 62 of file mate-calc/src/parser.h.
The documentation for this struct was generated from the following file:
mate-calc/src/parser.h