MATE Desktop Environment: _EvDocumentAnnotationsInterface Struct Reference
_EvDocumentAnnotationsInterface Struct Reference
#include <ev-document-annotations.h>
Public Attributes
GTypeInterface base_iface
EvMappingList *(* get_annotations)(EvDocumentAnnotations *document_annots, EvPage *page)
gboolean(* document_is_modified)(EvDocumentAnnotations *document_annots)
void(* add_annotation)(EvDocumentAnnotations *document_annots, EvAnnotation *annot, EvRectangle *rect)
void(* save_annotation)(EvDocumentAnnotations *document_annots, EvAnnotation *annot, EvAnnotationsSaveMask mask)
void(* remove_annotation)(EvDocumentAnnotations *document_annots, EvAnnotation *annot)
Detailed Description
Definition at line 68 of file ev-document-annotations.h.
Member Data Documentation
add_annotation
void(* _EvDocumentAnnotationsInterface::add_annotation) (EvDocumentAnnotations *document_annots, EvAnnotation *annot, EvRectangle *rect)
Definition at line 76 of file ev-document-annotations.h.
Referenced by ev_document_annotations_add_annotation(), and ev_document_annotations_can_add_annotation().
base_iface
GTypeInterface _EvDocumentAnnotationsInterface::base_iface
Definition at line 70 of file ev-document-annotations.h.
document_is_modified
gboolean(* _EvDocumentAnnotationsInterface::document_is_modified) (EvDocumentAnnotations *document_annots)
Definition at line 75 of file ev-document-annotations.h.
Referenced by ev_document_annotations_document_is_modified().
get_annotations
EvMappingList *(* _EvDocumentAnnotationsInterface::get_annotations) (EvDocumentAnnotations *document_annots, EvPage *page)
Definition at line 73 of file ev-document-annotations.h.
Referenced by ev_document_annotations_get_annotations().
remove_annotation
void(* _EvDocumentAnnotationsInterface::remove_annotation) (EvDocumentAnnotations *document_annots, EvAnnotation *annot)
Definition at line 82 of file ev-document-annotations.h.
Referenced by ev_document_annotations_can_remove_annotation(), and ev_document_annotations_remove_annotation().
save_annotation
void(* _EvDocumentAnnotationsInterface::save_annotation) (EvDocumentAnnotations *document_annots, EvAnnotation *annot, EvAnnotationsSaveMask mask)
Definition at line 79 of file ev-document-annotations.h.
Referenced by ev_document_annotations_save_annotation().
The documentation for this struct was generated from the following file:
ev-document-annotations.h