MATE Desktop Environment: _CajaViewInfo Struct Reference
_CajaViewInfo Struct Reference
#include <caja-view-factory.h>
Public Attributes
char * id
char * view_combo_label
char * view_menu_label_with_mnemonic
char * error_label
char * startup_error_label
char * display_location_label
gboolean single_view
CajaView *(* create)(CajaWindowSlotInfo *slot)
gboolean(* supports_uri)(const char *uri, GFileType file_type, const char *mime_type)
Detailed Description
Definition at line 41 of file caja-view-factory.h.
Member Data Documentation
create
CajaView *(* _CajaViewInfo::create) (CajaWindowSlotInfo *slot)
Definition at line 50 of file caja-view-factory.h.
Referenced by caja_view_factory_create().
display_location_label
char* _CajaViewInfo::display_location_label
Definition at line 48 of file caja-view-factory.h.
error_label
char* _CajaViewInfo::error_label
Definition at line 46 of file caja-view-factory.h.
id
char* _CajaViewInfo::id
Definition at line 43 of file caja-view-factory.h.
Referenced by caja_view_factory_get_views_for_uri(), caja_view_factory_lookup(), and caja_view_factory_register().
single_view
gboolean _CajaViewInfo::single_view
Definition at line 49 of file caja-view-factory.h.
Referenced by caja_view_factory_get_views_for_uri().
startup_error_label
char* _CajaViewInfo::startup_error_label
Definition at line 47 of file caja-view-factory.h.
supports_uri
gboolean(* _CajaViewInfo::supports_uri) (const char *uri, GFileType file_type, const char *mime_type)
Definition at line 52 of file caja-view-factory.h.
Referenced by caja_view_factory_get_views_for_uri(), and caja_view_factory_view_supports_uri().
view_combo_label
char* _CajaViewInfo::view_combo_label
Definition at line 44 of file caja-view-factory.h.
view_menu_label_with_mnemonic
char* _CajaViewInfo::view_menu_label_with_mnemonic
Definition at line 45 of file caja-view-factory.h.
The documentation for this struct was generated from the following file:
caja-view-factory.h