MATE Desktop Environment: _EvSelectionInterface Struct Reference
_EvSelectionInterface Struct Reference
#include <ev-selection.h>
Public Attributes
GTypeInterface base_iface
void(* render_selection)(EvSelection *selection, EvRenderContext *rc, cairo_surface_t **surface, EvRectangle *points, EvRectangle *old_points, EvSelectionStyle style, GdkColor *text, GdkColor *base)
gchar *(* get_selected_text)(EvSelection *selection, EvPage *page, EvSelectionStyle style, EvRectangle *points)
cairo_region_t *(* get_selection_region)(EvSelection *selection, EvRenderContext *rc, EvSelectionStyle style, EvRectangle *points)
Detailed Description
Definition at line 51 of file ev-selection.h.
Member Data Documentation
base_iface
GTypeInterface _EvSelectionInterface::base_iface
Definition at line 53 of file ev-selection.h.
get_selected_text
gchar *(* _EvSelectionInterface::get_selected_text) (EvSelection *selection, EvPage *page, EvSelectionStyle style, EvRectangle *points)
Definition at line 63 of file ev-selection.h.
Referenced by ev_selection_get_selected_text().
get_selection_region
cairo_region_t *(* _EvSelectionInterface::get_selection_region) (EvSelection *selection, EvRenderContext *rc, EvSelectionStyle style, EvRectangle *points)
Definition at line 67 of file ev-selection.h.
Referenced by ev_selection_get_selection_region().
render_selection
void(* _EvSelectionInterface::render_selection) (EvSelection *selection, EvRenderContext *rc, cairo_surface_t **surface, EvRectangle *points, EvRectangle *old_points, EvSelectionStyle style, GdkColor *text, GdkColor *base)
Definition at line 55 of file ev-selection.h.
Referenced by ev_selection_render_selection().
The documentation for this struct was generated from the following file:
ev-selection.h