MATE Desktop Environment: _EvDocumentFontsInterface Struct Reference
_EvDocumentFontsInterface Struct Reference
#include <ev-document-fonts.h>
Public Attributes
GTypeInterface base_iface
gboolean(* scan)(EvDocumentFonts *document_fonts, int n_pages)
double(* get_progress)(EvDocumentFonts *document_fonts)
void(* fill_model)(EvDocumentFonts *document_fonts, GtkTreeModel *model)
Detailed Description
Definition at line 56 of file ev-document-fonts.h.
Member Data Documentation
base_iface
GTypeInterface _EvDocumentFontsInterface::base_iface
Definition at line 58 of file ev-document-fonts.h.
fill_model
void(* _EvDocumentFontsInterface::fill_model) (EvDocumentFonts *document_fonts, GtkTreeModel *model)
Definition at line 64 of file ev-document-fonts.h.
Referenced by ev_document_fonts_fill_model().
get_progress
double(* _EvDocumentFontsInterface::get_progress) (EvDocumentFonts *document_fonts)
Definition at line 63 of file ev-document-fonts.h.
Referenced by ev_document_fonts_get_progress().
scan
gboolean(* _EvDocumentFontsInterface::scan) (EvDocumentFonts *document_fonts, int n_pages)
Definition at line 61 of file ev-document-fonts.h.
Referenced by ev_document_fonts_scan().
The documentation for this struct was generated from the following file:
ev-document-fonts.h