MATE Desktop Environment: _MetaCompositor Struct Reference
_MetaCompositor Struct Reference
#include <compositor-private.h>
Public Attributes
void(* destroy)(MetaCompositor *compositor)
void(* manage_screen)(MetaCompositor *compositor, MetaScreen *screen)
void(* unmanage_screen)(MetaCompositor *compositor, MetaScreen *screen)
void(* add_window)(MetaCompositor *compositor, MetaWindow *window, Window xwindow, XWindowAttributes *attrs)
void(* remove_window)(MetaCompositor *compositor, Window xwindow)
void(* set_updates)(MetaCompositor *compositor, MetaWindow *window, gboolean update)
void(* process_event)(MetaCompositor *compositor, XEvent *event, MetaWindow *window)
cairo_surface_t *(* get_window_surface)(MetaCompositor *compositor, MetaWindow *window)
void(* set_active_window)(MetaCompositor *compositor, MetaScreen *screen, MetaWindow *window)
void(* free_window)(MetaCompositor *compositor, MetaWindow *window)
void(* maximize_window)(MetaCompositor *compositor, MetaWindow *window)
void(* unmaximize_window)(MetaCompositor *compositor, MetaWindow *window)
Detailed Description
Definition at line 27 of file compositor-private.h.
Member Data Documentation
add_window
void(* _MetaCompositor::add_window) (MetaCompositor *compositor, MetaWindow *window, Window xwindow, XWindowAttributes *attrs)
Definition at line 35 of file compositor-private.h.
Referenced by meta_compositor_add_window().
destroy
void(* _MetaCompositor::destroy) (MetaCompositor *compositor)
Definition at line 29 of file compositor-private.h.
Referenced by meta_compositor_destroy().
free_window
void(* _MetaCompositor::free_window) (MetaCompositor *compositor, MetaWindow *window)
Definition at line 53 of file compositor-private.h.
Referenced by meta_compositor_free_window().
get_window_surface
cairo_surface_t *(* _MetaCompositor::get_window_surface) (MetaCompositor *compositor, MetaWindow *window)
Definition at line 47 of file compositor-private.h.
Referenced by meta_compositor_get_window_surface().
manage_screen
void(* _MetaCompositor::manage_screen) (MetaCompositor *compositor, MetaScreen *screen)
Definition at line 31 of file compositor-private.h.
Referenced by meta_compositor_manage_screen().
maximize_window
void(* _MetaCompositor::maximize_window) (MetaCompositor *compositor, MetaWindow *window)
Definition at line 56 of file compositor-private.h.
Referenced by meta_compositor_maximize_window().
process_event
void(* _MetaCompositor::process_event) (MetaCompositor *compositor, XEvent *event, MetaWindow *window)
Definition at line 44 of file compositor-private.h.
Referenced by meta_compositor_process_event().
remove_window
void(* _MetaCompositor::remove_window) (MetaCompositor *compositor, Window xwindow)
Definition at line 39 of file compositor-private.h.
Referenced by meta_compositor_remove_window().
set_active_window
void(* _MetaCompositor::set_active_window) (MetaCompositor *compositor, MetaScreen *screen, MetaWindow *window)
Definition at line 49 of file compositor-private.h.
Referenced by meta_compositor_set_active_window().
set_updates
void(* _MetaCompositor::set_updates) (MetaCompositor *compositor, MetaWindow *window, gboolean update)
Definition at line 41 of file compositor-private.h.
Referenced by meta_compositor_set_updates().
unmanage_screen
void(* _MetaCompositor::unmanage_screen) (MetaCompositor *compositor, MetaScreen *screen)
Definition at line 33 of file compositor-private.h.
Referenced by meta_compositor_unmanage_screen().
unmaximize_window
void(* _MetaCompositor::unmaximize_window) (MetaCompositor *compositor, MetaWindow *window)
Definition at line 58 of file compositor-private.h.
Referenced by meta_compositor_unmaximize_window().
The documentation for this struct was generated from the following file:
compositor-private.h