MATE Desktop Environment: _EvFileExporterInterface Struct Reference
_EvFileExporterInterface Struct Reference
#include <ev-file-exporter.h>
Public Attributes
GTypeInterface base_iface
void(* begin)(EvFileExporter *exporter, EvFileExporterContext *fc)
void(* begin_page)(EvFileExporter *exporter)
void(* do_page)(EvFileExporter *exporter, EvRenderContext *rc)
void(* end_page)(EvFileExporter *exporter)
void(* end)(EvFileExporter *exporter)
EvFileExporterCapabilities(* get_capabilities)(EvFileExporter *exporter)
Detailed Description
Definition at line 75 of file ev-file-exporter.h.
Member Data Documentation
base_iface
GTypeInterface _EvFileExporterInterface::base_iface
Definition at line 76 of file ev-file-exporter.h.
begin
void(* _EvFileExporterInterface::begin) (EvFileExporter *exporter, EvFileExporterContext *fc)
Definition at line 79 of file ev-file-exporter.h.
Referenced by ev_file_exporter_begin().
begin_page
void(* _EvFileExporterInterface::begin_page) (EvFileExporter *exporter)
Definition at line 81 of file ev-file-exporter.h.
Referenced by ev_file_exporter_begin_page().
do_page
void(* _EvFileExporterInterface::do_page) (EvFileExporter *exporter, EvRenderContext *rc)
Definition at line 82 of file ev-file-exporter.h.
Referenced by ev_file_exporter_do_page().
end
void(* _EvFileExporterInterface::end) (EvFileExporter *exporter)
Definition at line 85 of file ev-file-exporter.h.
Referenced by ev_file_exporter_end().
end_page
void(* _EvFileExporterInterface::end_page) (EvFileExporter *exporter)
Definition at line 84 of file ev-file-exporter.h.
Referenced by ev_file_exporter_end_page().
get_capabilities
EvFileExporterCapabilities(* _EvFileExporterInterface::get_capabilities) (EvFileExporter *exporter)
Definition at line 86 of file ev-file-exporter.h.
Referenced by ev_file_exporter_get_capabilities().
The documentation for this struct was generated from the following file:
ev-file-exporter.h