MATE Desktop Environment: _EvDocumentFormsInterface Struct Reference
_EvDocumentFormsInterface Struct Reference
#include <ev-document-forms.h>
Public Attributes
GTypeInterface base_iface
EvMappingList *(* get_form_fields)(EvDocumentForms *document_forms, EvPage *page)
gboolean(* document_is_modified)(EvDocumentForms *document_forms)
gchar *(* form_field_text_get_text)(EvDocumentForms *document_forms, EvFormField *field)
void(* form_field_text_set_text)(EvDocumentForms *document_forms, EvFormField *field, const gchar *text)
gboolean(* form_field_button_get_state)(EvDocumentForms *document_forms, EvFormField *field)
void(* form_field_button_set_state)(EvDocumentForms *document_forms, EvFormField *field, gboolean state)
gchar *(* form_field_choice_get_item)(EvDocumentForms *document_forms, EvFormField *field, gint index)
gint(* form_field_choice_get_n_items)(EvDocumentForms *document_forms, EvFormField *field)
gboolean(* form_field_choice_is_item_selected)(EvDocumentForms *document_forms, EvFormField *field, gint index)
void(* form_field_choice_select_item)(EvDocumentForms *document_forms, EvFormField *field, gint index)
void(* form_field_choice_toggle_item)(EvDocumentForms *document_forms, EvFormField *field, gint index)
void(* form_field_choice_unselect_all)(EvDocumentForms *document_forms, EvFormField *field)
void(* form_field_choice_set_text)(EvDocumentForms *document_forms, EvFormField *field, const gchar *text)
gchar *(* form_field_choice_get_text)(EvDocumentForms *document_forms, EvFormField *field)
Detailed Description
Definition at line 46 of file ev-document-forms.h.
Member Data Documentation
base_iface
GTypeInterface _EvDocumentFormsInterface::base_iface
Definition at line 48 of file ev-document-forms.h.
document_is_modified
gboolean(* _EvDocumentFormsInterface::document_is_modified) (EvDocumentForms *document_forms)
Definition at line 53 of file ev-document-forms.h.
Referenced by ev_document_forms_document_is_modified().
form_field_button_get_state
gboolean(* _EvDocumentFormsInterface::form_field_button_get_state) (EvDocumentForms *document_forms, EvFormField *field)
Definition at line 59 of file ev-document-forms.h.
Referenced by ev_document_forms_form_field_button_get_state().
form_field_button_set_state
void(* _EvDocumentFormsInterface::form_field_button_set_state) (EvDocumentForms *document_forms, EvFormField *field, gboolean state)
Definition at line 61 of file ev-document-forms.h.
Referenced by ev_document_forms_form_field_button_set_state().
form_field_choice_get_item
gchar *(* _EvDocumentFormsInterface::form_field_choice_get_item) (EvDocumentForms *document_forms, EvFormField *field, gint index)
Definition at line 64 of file ev-document-forms.h.
Referenced by ev_document_forms_form_field_choice_get_item().
form_field_choice_get_n_items
gint(* _EvDocumentFormsInterface::form_field_choice_get_n_items) (EvDocumentForms *document_forms, EvFormField *field)
Definition at line 67 of file ev-document-forms.h.
Referenced by ev_document_forms_form_field_choice_get_n_items().
form_field_choice_get_text
gchar *(* _EvDocumentFormsInterface::form_field_choice_get_text) (EvDocumentForms *document_forms, EvFormField *field)
Definition at line 83 of file ev-document-forms.h.
Referenced by ev_document_forms_form_field_choice_get_text().
form_field_choice_is_item_selected
gboolean(* _EvDocumentFormsInterface::form_field_choice_is_item_selected) (EvDocumentForms *document_forms, EvFormField *field, gint index)
Definition at line 69 of file ev-document-forms.h.
Referenced by ev_document_forms_form_field_choice_is_item_selected().
form_field_choice_select_item
void(* _EvDocumentFormsInterface::form_field_choice_select_item) (EvDocumentForms *document_forms, EvFormField *field, gint index)
Definition at line 72 of file ev-document-forms.h.
Referenced by ev_document_forms_form_field_choice_select_item().
form_field_choice_set_text
void(* _EvDocumentFormsInterface::form_field_choice_set_text) (EvDocumentForms *document_forms, EvFormField *field, const gchar *text)
Definition at line 80 of file ev-document-forms.h.
Referenced by ev_document_forms_form_field_choice_set_text().
form_field_choice_toggle_item
void(* _EvDocumentFormsInterface::form_field_choice_toggle_item) (EvDocumentForms *document_forms, EvFormField *field, gint index)
Definition at line 75 of file ev-document-forms.h.
Referenced by ev_document_forms_form_field_choice_toggle_item().
form_field_choice_unselect_all
void(* _EvDocumentFormsInterface::form_field_choice_unselect_all) (EvDocumentForms *document_forms, EvFormField *field)
Definition at line 78 of file ev-document-forms.h.
Referenced by ev_document_forms_form_field_choice_unselect_all().
form_field_text_get_text
gchar *(* _EvDocumentFormsInterface::form_field_text_get_text) (EvDocumentForms *document_forms, EvFormField *field)
Definition at line 54 of file ev-document-forms.h.
Referenced by ev_document_forms_form_field_text_get_text().
form_field_text_set_text
void(* _EvDocumentFormsInterface::form_field_text_set_text) (EvDocumentForms *document_forms, EvFormField *field, const gchar *text)
Definition at line 56 of file ev-document-forms.h.
Referenced by ev_document_forms_form_field_text_set_text().
get_form_fields
EvMappingList *(* _EvDocumentFormsInterface::get_form_fields) (EvDocumentForms *document_forms, EvPage *page)
Definition at line 51 of file ev-document-forms.h.
Referenced by ev_document_forms_get_form_fields().
The documentation for this struct was generated from the following file:
ev-document-forms.h