MATE Desktop Environment: _CajaViewIface Struct Reference
_CajaViewIface Struct Reference
#include <caja-view.h>
Public Attributes
GTypeInterface g_iface
void(* title_changed)(CajaView *view)
void(* zoom_level_changed)(CajaView *view)
const char *(* get_view_id)(CajaView *view)
GtkWidget *(* get_widget)(CajaView *view)
void(* load_location)(CajaView *view, const char *location_uri)
void(* stop_loading)(CajaView *view)
int(* get_selection_count)(CajaView *view)
GList *(* get_selection)(CajaView *view)
void(* set_selection)(CajaView *view, GList *list)
void(* invert_selection)(CajaView *view)
char *(* get_first_visible_file)(CajaView *view)
void(* scroll_to_file)(CajaView *view, const char *uri)
char *(* get_title)(CajaView *view)
gboolean(* supports_zooming)(CajaView *view)
void(* bump_zoom_level)(CajaView *view, int zoom_increment)
void(* zoom_to_level)(CajaView *view, CajaZoomLevel level)
CajaZoomLevel(* get_zoom_level)(CajaView *view)
void(* restore_default_zoom_level)(CajaView *view)
gboolean(* can_zoom_in)(CajaView *view)
gboolean(* can_zoom_out)(CajaView *view)
void(* grab_focus)(CajaView *view)
void(* update_menus)(CajaView *view)
void(* pop_up_location_context_menu)(CajaView *view, GdkEventButton *event, const char *location)
void(* drop_proxy_received_uris)(CajaView *view, GList *uris, const char *target_location, GdkDragAction action)
void(* drop_proxy_received_netscape_url)(CajaView *view, const char *source_url, const char *target_location, GdkDragAction action)
void(* set_is_active)(CajaView *view, gboolean is_active)
void(* _reserved1)(void)
void(* _reserved2)(void)
void(* _reserved3)(void)
void(* _reserved4)(void)
void(* _reserved5)(void)
void(* _reserved6)(void)
void(* _reserved7)(void)
Detailed Description
Definition at line 46 of file caja-view.h.
Member Data Documentation
_reserved1
void(* _CajaViewIface::_reserved1) (void)
Definition at line 137 of file caja-view.h.
_reserved2
void(* _CajaViewIface::_reserved2) (void)
Definition at line 138 of file caja-view.h.
_reserved3
void(* _CajaViewIface::_reserved3) (void)
Definition at line 139 of file caja-view.h.
_reserved4
void(* _CajaViewIface::_reserved4) (void)
Definition at line 140 of file caja-view.h.
_reserved5
void(* _CajaViewIface::_reserved5) (void)
Definition at line 141 of file caja-view.h.
_reserved6
void(* _CajaViewIface::_reserved6) (void)
Definition at line 142 of file caja-view.h.
_reserved7
void(* _CajaViewIface::_reserved7) (void)
Definition at line 143 of file caja-view.h.
bump_zoom_level
void(* _CajaViewIface::bump_zoom_level) (CajaView *view, int zoom_increment)
Definition at line 101 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
can_zoom_in
gboolean(* _CajaViewIface::can_zoom_in) (CajaView *view)
Definition at line 107 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
can_zoom_out
gboolean(* _CajaViewIface::can_zoom_out) (CajaView *view)
Definition at line 108 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
drop_proxy_received_netscape_url
void(* _CajaViewIface::drop_proxy_received_netscape_url) (CajaView *view, const char *source_url, const char *target_location, GdkDragAction action)
Definition at line 129 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
drop_proxy_received_uris
void(* _CajaViewIface::drop_proxy_received_uris) (CajaView *view, GList *uris, const char *target_location, GdkDragAction action)
Definition at line 125 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
g_iface
GTypeInterface _CajaViewIface::g_iface
Definition at line 48 of file caja-view.h.
get_first_visible_file
char *(* _CajaViewIface::get_first_visible_file) (CajaView *view)
Definition at line 89 of file caja-view.h.
get_selection
GList *(* _CajaViewIface::get_selection) (CajaView *view)
Definition at line 79 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
get_selection_count
int(* _CajaViewIface::get_selection_count) (CajaView *view)
Definition at line 76 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
get_title
char *(* _CajaViewIface::get_title) (CajaView *view)
Definition at line 97 of file caja-view.h.
get_view_id
const char *(* _CajaViewIface::get_view_id) (CajaView *view)
Definition at line 60 of file caja-view.h.
get_widget
GtkWidget *(* _CajaViewIface::get_widget) (CajaView *view)
Definition at line 64 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
get_zoom_level
CajaZoomLevel(* _CajaViewIface::get_zoom_level) (CajaView *view)
Definition at line 105 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
grab_focus
void(* _CajaViewIface::grab_focus) (CajaView *view)
Definition at line 110 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
invert_selection
void(* _CajaViewIface::invert_selection) (CajaView *view)
Definition at line 86 of file caja-view.h.
load_location
void(* _CajaViewIface::load_location) (CajaView *view, const char *location_uri)
Definition at line 69 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
pop_up_location_context_menu
void(* _CajaViewIface::pop_up_location_context_menu) (CajaView *view, GdkEventButton *event, const char *location)
Definition at line 121 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
restore_default_zoom_level
void(* _CajaViewIface::restore_default_zoom_level) (CajaView *view)
Definition at line 106 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
scroll_to_file
void(* _CajaViewIface::scroll_to_file) (CajaView *view, const char *uri)
Definition at line 92 of file caja-view.h.
set_is_active
void(* _CajaViewIface::set_is_active) (CajaView *view, gboolean is_active)
Definition at line 133 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
set_selection
void(* _CajaViewIface::set_selection) (CajaView *view, GList *list)
Definition at line 82 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
stop_loading
void(* _CajaViewIface::stop_loading) (CajaView *view)
Definition at line 73 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
supports_zooming
gboolean(* _CajaViewIface::supports_zooming) (CajaView *view)
Definition at line 100 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
title_changed
void(* _CajaViewIface::title_changed) (CajaView *view)
Definition at line 53 of file caja-view.h.
update_menus
void(* _CajaViewIface::update_menus) (CajaView *view)
Definition at line 111 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
zoom_level_changed
void(* _CajaViewIface::zoom_level_changed) (CajaView *view)
Definition at line 55 of file caja-view.h.
zoom_to_level
void(* _CajaViewIface::zoom_to_level) (CajaView *view, CajaZoomLevel level)
Definition at line 103 of file caja-view.h.
Referenced by fm_directory_view_init_view_iface().
The documentation for this struct was generated from the following file:
caja-view.h