MATE Desktop Environment: _EvDocumentTextInterface Struct Reference
_EvDocumentTextInterface Struct Reference
#include <ev-document-text.h>
Public Attributes
GTypeInterface base_iface
cairo_region_t *(* get_text_mapping)(EvDocumentText *document_text, EvPage *page)
gchar *(* get_text)(EvDocumentText *document_text, EvPage *page)
gboolean(* get_text_layout)(EvDocumentText *document_text, EvPage *page, EvRectangle **areas, guint *n_areas)
PangoAttrList *(* get_text_attrs)(EvDocumentText *document_text, EvPage *page)
Detailed Description
Definition at line 47 of file ev-document-text.h.
Member Data Documentation
base_iface
GTypeInterface _EvDocumentTextInterface::base_iface
Definition at line 49 of file ev-document-text.h.
get_text
gchar *(* _EvDocumentTextInterface::get_text) (EvDocumentText *document_text, EvPage *page)
Definition at line 54 of file ev-document-text.h.
Referenced by ev_document_text_get_text(), and ev_view_supports_caret_navigation().
get_text_attrs
PangoAttrList *(* _EvDocumentTextInterface::get_text_attrs) (EvDocumentText *document_text, EvPage *page)
Definition at line 60 of file ev-document-text.h.
Referenced by ev_document_text_get_text_attrs().
get_text_layout
gboolean(* _EvDocumentTextInterface::get_text_layout) (EvDocumentText *document_text, EvPage *page, EvRectangle **areas, guint *n_areas)
Definition at line 56 of file ev-document-text.h.
Referenced by ev_document_text_get_text_layout(), and ev_view_supports_caret_navigation().
get_text_mapping
cairo_region_t *(* _EvDocumentTextInterface::get_text_mapping) (EvDocumentText *document_text, EvPage *page)
Definition at line 52 of file ev-document-text.h.
Referenced by ev_document_text_get_text_mapping().
The documentation for this struct was generated from the following file:
ev-document-text.h