MATE Desktop Environment: _MateMixerBackendClass Struct Reference
_MateMixerBackendClass Struct Reference
#include <matemixer-backend.h>
Public Attributes
GObjectClass parent_class
void(* set_app_info)(MateMixerBackend *backend, MateMixerAppInfo *info)
void(* set_server_address)(MateMixerBackend *backend, const gchar *address)
gboolean(* open)(MateMixerBackend *backend)
void(* close)(MateMixerBackend *backend)
const GList *(* list_devices)(MateMixerBackend *backend)
const GList *(* list_streams)(MateMixerBackend *backend)
const GList *(* list_stored_controls)(MateMixerBackend *backend)
gboolean(* set_default_input_stream)(MateMixerBackend *backend, MateMixerStream *stream)
gboolean(* set_default_output_stream)(MateMixerBackend *backend, MateMixerStream *stream)
void(* device_added)(MateMixerBackend *backend, const gchar *name)
void(* device_removed)(MateMixerBackend *backend, const gchar *name)
void(* stream_added)(MateMixerBackend *backend, const gchar *name)
void(* stream_removed)(MateMixerBackend *backend, const gchar *name)
void(* stored_control_added)(MateMixerBackend *backend, const gchar *name)
void(* stored_control_removed)(MateMixerBackend *backend, const gchar *name)
Detailed Description
Definition at line 54 of file matemixer-backend.h.
Member Data Documentation
close
void(* _MateMixerBackendClass::close) (MateMixerBackend *backend)
Definition at line 65 of file matemixer-backend.h.
Referenced by mate_mixer_backend_close().
device_added
void(* _MateMixerBackendClass::device_added) (MateMixerBackend *backend, const gchar *name)
Definition at line 77 of file matemixer-backend.h.
device_removed
void(* _MateMixerBackendClass::device_removed) (MateMixerBackend *backend, const gchar *name)
Definition at line 79 of file matemixer-backend.h.
list_devices
const GList *(* _MateMixerBackendClass::list_devices) (MateMixerBackend *backend)
Definition at line 67 of file matemixer-backend.h.
Referenced by mate_mixer_backend_list_devices().
list_stored_controls
const GList *(* _MateMixerBackendClass::list_stored_controls) (MateMixerBackend *backend)
Definition at line 69 of file matemixer-backend.h.
Referenced by mate_mixer_backend_list_stored_controls().
list_streams
const GList *(* _MateMixerBackendClass::list_streams) (MateMixerBackend *backend)
Definition at line 68 of file matemixer-backend.h.
Referenced by mate_mixer_backend_list_streams().
open
gboolean(* _MateMixerBackendClass::open) (MateMixerBackend *backend)
Definition at line 64 of file matemixer-backend.h.
parent_class
GObjectClass _MateMixerBackendClass::parent_class
Definition at line 56 of file matemixer-backend.h.
set_app_info
void(* _MateMixerBackendClass::set_app_info) (MateMixerBackend *backend, MateMixerAppInfo *info)
Definition at line 59 of file matemixer-backend.h.
Referenced by mate_mixer_backend_set_app_info().
set_default_input_stream
gboolean(* _MateMixerBackendClass::set_default_input_stream) (MateMixerBackend *backend, MateMixerStream *stream)
Definition at line 71 of file matemixer-backend.h.
Referenced by mate_mixer_backend_set_default_input_stream().
set_default_output_stream
gboolean(* _MateMixerBackendClass::set_default_output_stream) (MateMixerBackend *backend, MateMixerStream *stream)
Definition at line 73 of file matemixer-backend.h.
Referenced by mate_mixer_backend_set_default_output_stream().
set_server_address
void(* _MateMixerBackendClass::set_server_address) (MateMixerBackend *backend, const gchar *address)
Definition at line 61 of file matemixer-backend.h.
Referenced by mate_mixer_backend_set_server_address().
stored_control_added
void(* _MateMixerBackendClass::stored_control_added) (MateMixerBackend *backend, const gchar *name)
Definition at line 85 of file matemixer-backend.h.
stored_control_removed
void(* _MateMixerBackendClass::stored_control_removed) (MateMixerBackend *backend, const gchar *name)
Definition at line 87 of file matemixer-backend.h.
stream_added
void(* _MateMixerBackendClass::stream_added) (MateMixerBackend *backend, const gchar *name)
Definition at line 81 of file matemixer-backend.h.
stream_removed
void(* _MateMixerBackendClass::stream_removed) (MateMixerBackend *backend, const gchar *name)
Definition at line 83 of file matemixer-backend.h.
The documentation for this struct was generated from the following file:
matemixer-backend.h