MATE Desktop Environment: _NaItemInterface Struct Reference
_NaItemInterface Struct Reference
#include <na-item.h>
Public Attributes
GTypeInterface g_iface
const gchar *(* get_id)(NaItem *item)
NaItemCategory(* get_category)(NaItem *item)
gboolean(* draw_on_parent)(NaItem *item, GtkWidget *parent, cairo_t *parent_cr)
Detailed Description
Definition at line 42 of file na-item.h.
Member Data Documentation
draw_on_parent
gboolean(* _NaItemInterface::draw_on_parent) (NaItem *item, GtkWidget *parent, cairo_t *parent_cr)
Definition at line 49 of file na-item.h.
Referenced by na_item_draw_on_parent().
g_iface
GTypeInterface _NaItemInterface::g_iface
Definition at line 44 of file na-item.h.
get_category
NaItemCategory(* _NaItemInterface::get_category) (NaItem *item)
Definition at line 47 of file na-item.h.
Referenced by na_item_get_category().
get_id
const gchar *(* _NaItemInterface::get_id) (NaItem *item)
Definition at line 46 of file na-item.h.
Referenced by na_item_get_id().
The documentation for this struct was generated from the following file:
na-item.h