MATE Desktop Environment: _EvDocumentClass Struct Reference
_EvDocumentClass Struct Reference
#include <ev-document.h>
Public Attributes
GObjectClass base_class
gboolean(* load)(EvDocument *document, const char *uri, GError **error)
gboolean(* save)(EvDocument *document, const char *uri, GError **error)
gint(* get_n_pages)(EvDocument *document)
EvPage *(* get_page)(EvDocument *document, gint index)
void(* get_page_size)(EvDocument *document, EvPage *page, double *width, double *height)
gchar *(* get_page_label)(EvDocument *document, EvPage *page)
cairo_surface_t *(* render)(EvDocument *document, EvRenderContext *rc)
EvDocumentInfo *(* get_info)(EvDocument *document)
gboolean(* get_backend_info)(EvDocument *document, EvDocumentBackendInfo *info)
gboolean(* support_synctex)(EvDocument *document)
void(* toggle_night_mode)(EvDocument *document, gboolean night)
void(* check_add_night_sheet)(EvDocument *document)
Detailed Description
Definition at line 92 of file ev-document.h.
Member Data Documentation
base_class
GObjectClass _EvDocumentClass::base_class
Definition at line 94 of file ev-document.h.
check_add_night_sheet
void(* _EvDocumentClass::check_add_night_sheet) (EvDocument *document)
Definition at line 120 of file ev-document.h.
Referenced by ev_document_check_add_night_sheet().
get_backend_info
gboolean(* _EvDocumentClass::get_backend_info) (EvDocument *document, EvDocumentBackendInfo *info)
Definition at line 115 of file ev-document.h.
Referenced by ev_document_get_backend_info().
get_info
EvDocumentInfo *(* _EvDocumentClass::get_info) (EvDocument *document)
Definition at line 114 of file ev-document.h.
get_n_pages
gint(* _EvDocumentClass::get_n_pages) (EvDocument *document)
Definition at line 103 of file ev-document.h.
get_page
EvPage *(* _EvDocumentClass::get_page) (EvDocument *document, gint index)
Definition at line 104 of file ev-document.h.
Referenced by ev_document_get_page().
get_page_label
gchar *(* _EvDocumentClass::get_page_label) (EvDocument *document, EvPage *page)
Definition at line 110 of file ev-document.h.
get_page_size
void(* _EvDocumentClass::get_page_size) (EvDocument *document, EvPage *page, double *width, double *height)
Definition at line 106 of file ev-document.h.
load
gboolean(* _EvDocumentClass::load) (EvDocument *document, const char *uri, GError **error)
Definition at line 97 of file ev-document.h.
Referenced by ev_document_load().
render
cairo_surface_t *(* _EvDocumentClass::render) (EvDocument *document, EvRenderContext *rc)
Definition at line 112 of file ev-document.h.
Referenced by ev_document_render().
save
gboolean(* _EvDocumentClass::save) (EvDocument *document, const char *uri, GError **error)
Definition at line 100 of file ev-document.h.
Referenced by ev_document_save().
support_synctex
gboolean(* _EvDocumentClass::support_synctex) (EvDocument *document)
Definition at line 117 of file ev-document.h.
toggle_night_mode
void(* _EvDocumentClass::toggle_night_mode) (EvDocument *document, gboolean night)
Definition at line 119 of file ev-document.h.
Referenced by ev_document_toggle_night_mode().
The documentation for this struct was generated from the following file:
ev-document.h