MATE Desktop Environment: EggTreeMultiDragSourceIface Struct Reference
EggTreeMultiDragSourceIface Struct Reference
#include <egg-tree-multi-dnd.h>
Public Attributes
GTypeInterface g_iface
gboolean(* row_draggable)(EggTreeMultiDragSource *drag_source, GList *path_list)
gboolean(* drag_data_get)(EggTreeMultiDragSource *drag_source, GdkDragContext *context, GtkSelectionData *selection_data, GList *path_list, guint info)
gboolean(* drag_data_delete)(EggTreeMultiDragSource *drag_source, GList *path_list)
GtkTargetList *(* get_target_list)(EggTreeMultiDragSource *drag_source)
void(* free_target_list)(EggTreeMultiDragSource *drag_source, GtkTargetList *list)
GdkDragAction(* get_drag_actions)(EggTreeMultiDragSource *drag_source)
Detailed Description
Definition at line 37 of file egg-tree-multi-dnd.h.
Member Data Documentation
drag_data_delete
gboolean(* EggTreeMultiDragSourceIface::drag_data_delete) (EggTreeMultiDragSource *drag_source, GList *path_list)
Definition at line 44 of file egg-tree-multi-dnd.h.
Referenced by egg_tree_multi_drag_source_drag_data_delete().
drag_data_get
gboolean(* EggTreeMultiDragSourceIface::drag_data_get) (EggTreeMultiDragSource *drag_source, GdkDragContext *context, GtkSelectionData *selection_data, GList *path_list, guint info)
Definition at line 43 of file egg-tree-multi-dnd.h.
Referenced by egg_tree_multi_drag_source_drag_data_get(), egg_tree_multi_drag_source_drag_data_get(), and egg_tree_multi_drag_source_drag_data_get().
free_target_list
void(* EggTreeMultiDragSourceIface::free_target_list) (EggTreeMultiDragSource *drag_source, GtkTargetList *list)
Definition at line 46 of file egg-tree-multi-dnd.h.
g_iface
GTypeInterface EggTreeMultiDragSourceIface::g_iface
Definition at line 39 of file egg-tree-multi-dnd.h.
get_drag_actions
GdkDragAction(* EggTreeMultiDragSourceIface::get_drag_actions) (EggTreeMultiDragSource *drag_source)
Definition at line 47 of file egg-tree-multi-dnd.h.
get_target_list
GtkTargetList *(* EggTreeMultiDragSourceIface::get_target_list) (EggTreeMultiDragSource *drag_source)
Definition at line 45 of file egg-tree-multi-dnd.h.
row_draggable
gboolean(* EggTreeMultiDragSourceIface::row_draggable) (EggTreeMultiDragSource *drag_source, GList *path_list)
Definition at line 42 of file egg-tree-multi-dnd.h.
Referenced by egg_tree_multi_drag_source_row_draggable().
The documentation for this struct was generated from the following file:
egg-tree-multi-dnd.h