MATE Desktop Environment: _EvDocumentLinksInterface Struct Reference
_EvDocumentLinksInterface Struct Reference
#include <ev-document-links.h>
Public Attributes
GTypeInterface base_iface
gboolean(* has_document_links)(EvDocumentLinks *document_links)
GtkTreeModel *(* get_links_model)(EvDocumentLinks *document_links)
EvMappingList *(* get_links)(EvDocumentLinks *document_links, EvPage *page)
EvLinkDest *(* find_link_dest)(EvDocumentLinks *document_links, const gchar *link_name)
gint(* find_link_page)(EvDocumentLinks *document_links, const gchar *link_name)
Detailed Description
Definition at line 59 of file ev-document-links.h.
Member Data Documentation
base_iface
GTypeInterface _EvDocumentLinksInterface::base_iface
Definition at line 61 of file ev-document-links.h.
find_link_dest
EvLinkDest *(* _EvDocumentLinksInterface::find_link_dest) (EvDocumentLinks *document_links, const gchar *link_name)
Definition at line 68 of file ev-document-links.h.
Referenced by ev_document_links_find_link_dest().
find_link_page
gint(* _EvDocumentLinksInterface::find_link_page) (EvDocumentLinks *document_links, const gchar *link_name)
Definition at line 70 of file ev-document-links.h.
Referenced by ev_document_links_find_link_page().
get_links
EvMappingList *(* _EvDocumentLinksInterface::get_links) (EvDocumentLinks *document_links, EvPage *page)
Definition at line 66 of file ev-document-links.h.
Referenced by ev_document_links_get_links().
get_links_model
GtkTreeModel *(* _EvDocumentLinksInterface::get_links_model) (EvDocumentLinks *document_links)
Definition at line 65 of file ev-document-links.h.
Referenced by ev_document_links_get_links_model().
has_document_links
gboolean(* _EvDocumentLinksInterface::has_document_links) (EvDocumentLinks *document_links)
Definition at line 64 of file ev-document-links.h.
Referenced by ev_document_links_has_document_links().
The documentation for this struct was generated from the following file:
ev-document-links.h