MATE Desktop Environment: _MateMixerStreamControlClass Struct Reference
_MateMixerStreamControlClass Struct Reference
#include <matemixer-stream-control.h>
Public Attributes
GObjectClass parent_class
MateMixerAppInfo *(* get_app_info)(MateMixerStreamControl *control)
gboolean(* set_stream)(MateMixerStreamControl *control, MateMixerStream *stream)
gboolean(* set_mute)(MateMixerStreamControl *control, gboolean mute)
guint(* get_num_channels)(MateMixerStreamControl *control)
guint(* get_volume)(MateMixerStreamControl *control)
gboolean(* set_volume)(MateMixerStreamControl *control, guint volume)
gdouble(* get_decibel)(MateMixerStreamControl *control)
gboolean(* set_decibel)(MateMixerStreamControl *control, gdouble decibel)
gboolean(* has_channel_position)(MateMixerStreamControl *control, MateMixerChannelPosition position)
MateMixerChannelPosition(* get_channel_position)(MateMixerStreamControl *control, guint channel)
guint(* get_channel_volume)(MateMixerStreamControl *control, guint channel)
gboolean(* set_channel_volume)(MateMixerStreamControl *control, guint channel, guint volume)
gdouble(* get_channel_decibel)(MateMixerStreamControl *control, guint channel)
gboolean(* set_channel_decibel)(MateMixerStreamControl *control, guint channel, gdouble decibel)
gboolean(* set_balance)(MateMixerStreamControl *control, gfloat balance)
gboolean(* set_fade)(MateMixerStreamControl *control, gfloat fade)
gboolean(* get_monitor_enabled)(MateMixerStreamControl *control)
gboolean(* set_monitor_enabled)(MateMixerStreamControl *control, gboolean enabled)
guint(* get_min_volume)(MateMixerStreamControl *control)
guint(* get_max_volume)(MateMixerStreamControl *control)
guint(* get_normal_volume)(MateMixerStreamControl *control)
guint(* get_base_volume)(MateMixerStreamControl *control)
void(* monitor_value)(MateMixerStreamControl *control, gdouble value)
Detailed Description
MateMixerStreamControlClass: @parent_class: The parent class.
The class structure for MateMixerStreamControl.
Definition at line 72 of file matemixer-stream-control.h.
Member Data Documentation
get_app_info
MateMixerAppInfo *(* _MateMixerStreamControlClass::get_app_info) (MateMixerStreamControl *control)
Definition at line 77 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_get_app_info().
get_base_volume
guint(* _MateMixerStreamControlClass::get_base_volume) (MateMixerStreamControl *control)
Definition at line 125 of file matemixer-stream-control.h.
get_channel_decibel
gdouble(* _MateMixerStreamControlClass::get_channel_decibel) (MateMixerStreamControl *control, guint channel)
Definition at line 106 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_get_channel_decibel().
get_channel_position
MateMixerChannelPosition(* _MateMixerStreamControlClass::get_channel_position) (MateMixerStreamControl *control, guint channel)
Definition at line 97 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_get_channel_position().
get_channel_volume
guint(* _MateMixerStreamControlClass::get_channel_volume) (MateMixerStreamControl *control, guint channel)
Definition at line 100 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_get_channel_volume().
get_decibel
gdouble(* _MateMixerStreamControlClass::get_decibel) (MateMixerStreamControl *control)
Definition at line 91 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_get_decibel().
get_max_volume
guint(* _MateMixerStreamControlClass::get_max_volume) (MateMixerStreamControl *control)
Definition at line 123 of file matemixer-stream-control.h.
get_min_volume
guint(* _MateMixerStreamControlClass::get_min_volume) (MateMixerStreamControl *control)
Definition at line 122 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_get_channel_volume(), and mate_mixer_stream_control_get_volume().
get_monitor_enabled
gboolean(* _MateMixerStreamControlClass::get_monitor_enabled) (MateMixerStreamControl *control)
Definition at line 118 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_get_monitor_enabled().
get_normal_volume
guint(* _MateMixerStreamControlClass::get_normal_volume) (MateMixerStreamControl *control)
Definition at line 124 of file matemixer-stream-control.h.
get_num_channels
guint(* _MateMixerStreamControlClass::get_num_channels) (MateMixerStreamControl *control)
Definition at line 85 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_get_num_channels().
get_volume
guint(* _MateMixerStreamControlClass::get_volume) (MateMixerStreamControl *control)
Definition at line 87 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_get_volume().
has_channel_position
gboolean(* _MateMixerStreamControlClass::has_channel_position) (MateMixerStreamControl *control, MateMixerChannelPosition position)
Definition at line 95 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_has_channel_position().
monitor_value
void(* _MateMixerStreamControlClass::monitor_value) (MateMixerStreamControl *control, gdouble value)
Definition at line 128 of file matemixer-stream-control.h.
parent_class
GObjectClass _MateMixerStreamControlClass::parent_class
Definition at line 74 of file matemixer-stream-control.h.
set_balance
gboolean(* _MateMixerStreamControlClass::set_balance) (MateMixerStreamControl *control, gfloat balance)
Definition at line 112 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_set_balance().
set_channel_decibel
gboolean(* _MateMixerStreamControlClass::set_channel_decibel) (MateMixerStreamControl *control, guint channel, gdouble decibel)
Definition at line 108 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_set_channel_decibel().
set_channel_volume
gboolean(* _MateMixerStreamControlClass::set_channel_volume) (MateMixerStreamControl *control, guint channel, guint volume)
Definition at line 102 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_set_channel_volume().
set_decibel
gboolean(* _MateMixerStreamControlClass::set_decibel) (MateMixerStreamControl *control, gdouble decibel)
Definition at line 92 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_set_decibel().
set_fade
gboolean(* _MateMixerStreamControlClass::set_fade) (MateMixerStreamControl *control, gfloat fade)
Definition at line 115 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_set_fade().
set_monitor_enabled
gboolean(* _MateMixerStreamControlClass::set_monitor_enabled) (MateMixerStreamControl *control, gboolean enabled)
Definition at line 119 of file matemixer-stream-control.h.
set_mute
gboolean(* _MateMixerStreamControlClass::set_mute) (MateMixerStreamControl *control, gboolean mute)
Definition at line 82 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_set_mute().
set_stream
gboolean(* _MateMixerStreamControlClass::set_stream) (MateMixerStreamControl *control, MateMixerStream *stream)
Definition at line 79 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_set_stream().
set_volume
gboolean(* _MateMixerStreamControlClass::set_volume) (MateMixerStreamControl *control, guint volume)
Definition at line 88 of file matemixer-stream-control.h.
Referenced by mate_mixer_stream_control_set_volume().
The documentation for this struct was generated from the following file:
matemixer-stream-control.h