MATE Desktop Environment: tabpopup.h File Reference
tabpopup.h File Reference
#include "common.h"
#include "boxes.h"
#include "types.h"
#include <X11/Xlib.h>
#include <glib.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gtk/gtk.h>
Classes
struct _MetaTabEntry
Typedefs
typedef struct _MetaTabEntry MetaTabEntry
typedef struct _MetaTabPopup MetaTabPopup
typedef void * MetaTabEntryKey
typedef enum border_outline_t border_outline_t
Enumerations
enum border_outline_t { BORDER_OUTLINE_WINDOW = 1 , BORDER_OUTLINE_TAB = 2 , BORDER_OUTLINE_WORKSPACE = 4 }
Functions
MetaTabPopup * meta_ui_tab_popup_new (const MetaTabEntry *entries, MetaScreen *meta_screen, int entry_count, int width, gboolean expand_for_titles, gboolean outline)
void meta_ui_tab_popup_free (MetaTabPopup *popup)
void meta_ui_tab_popup_set_showing (MetaTabPopup *popup, gboolean showing)
void meta_ui_tab_popup_forward (MetaTabPopup *popup)
void meta_ui_tab_popup_backward (MetaTabPopup *popup)
void meta_ui_tab_popup_down (MetaTabPopup *popup)
void meta_ui_tab_popup_up (MetaTabPopup *popup)
MetaTabEntryKey meta_ui_tab_popup_get_selected (MetaTabPopup *popup)
void meta_ui_tab_popup_select (MetaTabPopup *popup, MetaTabEntryKey key)
GtkWidget * meta_ui_tab_popup_get_widget (MetaTabPopup *popup)
void meta_ui_tab_popup_mouse_press (MetaTabPopup *popup, gint x, gint y)
Typedef Documentation
border_outline_t
typedef enum border_outline_t border_outline_t
MetaTabEntry
typedef struct _MetaTabEntry MetaTabEntry
Definition at line 37 of file tabpopup.h.
MetaTabEntryKey
typedef void* MetaTabEntryKey
Definition at line 39 of file tabpopup.h.
MetaTabPopup
typedef struct _MetaTabPopup MetaTabPopup
Definition at line 38 of file tabpopup.h.
Enumeration Type Documentation
border_outline_t
enum border_outline_t
Enumerator
BORDER_OUTLINE_WINDOW
BORDER_OUTLINE_TAB
BORDER_OUTLINE_WORKSPACE
Definition at line 41 of file tabpopup.h.
Function Documentation
meta_ui_tab_popup_backward()
void meta_ui_tab_popup_backward (MetaTabPopup * popup)
Definition at line 663 of file tabpopup.c.
References NULL.
meta_ui_tab_popup_down()
void meta_ui_tab_popup_down (MetaTabPopup * popup)
Definition at line 700 of file tabpopup.c.
References NULL.
meta_ui_tab_popup_forward()
void meta_ui_tab_popup_forward (MetaTabPopup * popup)
Definition at line 644 of file tabpopup.c.
References NULL.
meta_ui_tab_popup_free()
void meta_ui_tab_popup_free (MetaTabPopup * popup)
Definition at line 557 of file tabpopup.c.
References NULL.
Referenced by meta_display_end_grab_op().
meta_ui_tab_popup_get_selected()
MetaTabEntryKey meta_ui_tab_popup_get_selected (MetaTabPopup * popup)
Definition at line 726 of file tabpopup.c.
meta_ui_tab_popup_get_widget()
GtkWidget * meta_ui_tab_popup_get_widget (MetaTabPopup * popup)
Definition at line 771 of file tabpopup.c.
References NULL.
meta_ui_tab_popup_mouse_press()
void meta_ui_tab_popup_mouse_press (MetaTabPopup * popup, gint x, gint y)
Definition at line 780 of file tabpopup.c.
References FALSE, and NULL.
meta_ui_tab_popup_new()
MetaTabPopup * meta_ui_tab_popup_new (const MetaTabEntry * entries, MetaScreen * meta_screen, int entry_count, int width, gboolean expand_for_titles, gboolean outline)
References key.
Referenced by meta_screen_ensure_tab_popup(), and meta_screen_ensure_workspace_popup().
meta_ui_tab_popup_select()
void meta_ui_tab_popup_select (MetaTabPopup * popup, MetaTabEntryKey key)
Definition at line 741 of file tabpopup.c.
References key, and NULL.
meta_ui_tab_popup_set_showing()
void meta_ui_tab_popup_set_showing (MetaTabPopup * popup, gboolean showing)
Definition at line 573 of file tabpopup.c.
References meta_core_increment_event_serial().
meta_ui_tab_popup_up()
void meta_ui_tab_popup_up (MetaTabPopup * popup)
Definition at line 713 of file tabpopup.c.
References NULL.