MATE Desktop Environment: terminal-accels.c File Reference
terminal-accels.c File Reference
#include <config.h>
#include <string.h>
#include <gdk/gdkkeysyms.h>
#include "terminal-accels.h"
#include "terminal-app.h"
#include "terminal-debug.h"
#include "terminal-intl.h"
#include "terminal-profile.h"
#include "terminal-util.h"
#include "terminal-version.h"
Macros
#define ACCEL_PATH_ROOT "<Actions>/Main/"
#define ACCEL_PATH_NEW_TAB ACCEL_PATH_ROOT "FileNewTab"
#define ACCEL_PATH_NEW_WINDOW ACCEL_PATH_ROOT "FileNewWindow"
#define ACCEL_PATH_NEW_PROFILE ACCEL_PATH_ROOT "FileNewProfile"
#define ACCEL_PATH_SAVE_CONTENTS ACCEL_PATH_ROOT "FileSaveContents"
#define ACCEL_PATH_CLOSE_TAB ACCEL_PATH_ROOT "FileCloseTab"
#define ACCEL_PATH_CLOSE_WINDOW ACCEL_PATH_ROOT "FileCloseWindow"
#define ACCEL_PATH_COPY ACCEL_PATH_ROOT "EditCopy"
#define ACCEL_PATH_PASTE ACCEL_PATH_ROOT "EditPaste"
#define ACCEL_PATH_SELECT_ALL ACCEL_PATH_ROOT "EditSelectAll"
#define ACCEL_PATH_SEARCH_FIND ACCEL_PATH_ROOT "SearchFind"
#define ACCEL_PATH_SEARCH_FIND_NEXT ACCEL_PATH_ROOT "SearchFindNext"
#define ACCEL_PATH_SEARCH_FIND_PREVIOUS ACCEL_PATH_ROOT "SearchFindPrevious"
#define ACCEL_PATH_TOGGLE_MENUBAR ACCEL_PATH_ROOT "ViewMenubar"
#define ACCEL_PATH_FULL_SCREEN ACCEL_PATH_ROOT "ViewFullscreen"
#define ACCEL_PATH_RESET ACCEL_PATH_ROOT "TerminalReset"
#define ACCEL_PATH_RESET_AND_CLEAR ACCEL_PATH_ROOT "TerminalResetClear"
#define ACCEL_PATH_PREV_PROFILE ACCEL_PATH_ROOT "ProfilePrevious"
#define ACCEL_PATH_NEXT_PROFILE ACCEL_PATH_ROOT "ProfileNext"
#define ACCEL_PATH_PREV_TAB ACCEL_PATH_ROOT "TabsPrevious"
#define ACCEL_PATH_NEXT_TAB ACCEL_PATH_ROOT "TabsNext"
#define ACCEL_PATH_SET_TERMINAL_TITLE ACCEL_PATH_ROOT "TerminalSetTitle"
#define ACCEL_PATH_HELP ACCEL_PATH_ROOT "HelpContents"
#define ACCEL_PATH_ZOOM_IN ACCEL_PATH_ROOT "ViewZoomIn"
#define ACCEL_PATH_ZOOM_OUT ACCEL_PATH_ROOT "ViewZoomOut"
#define ACCEL_PATH_ZOOM_NORMAL ACCEL_PATH_ROOT "ViewZoom100"
#define ACCEL_PATH_MOVE_TAB_LEFT ACCEL_PATH_ROOT "TabsMoveLeft"
#define ACCEL_PATH_MOVE_TAB_RIGHT ACCEL_PATH_ROOT "TabsMoveRight"
#define ACCEL_PATH_DETACH_TAB ACCEL_PATH_ROOT "TabsDetach"
#define ACCEL_PATH_SWITCH_TAB_PREFIX ACCEL_PATH_ROOT "TabsSwitch"
#define KEY_CLOSE_TAB "close-tab"
#define KEY_CLOSE_WINDOW "close-window"
#define KEY_COPY "copy"
#define KEY_DETACH_TAB "detach-tab"
#define KEY_FULL_SCREEN "full-screen"
#define KEY_HELP "help"
#define KEY_MOVE_TAB_LEFT "move-tab-left"
#define KEY_MOVE_TAB_RIGHT "move-tab-right"
#define KEY_NEW_PROFILE "new-profile"
#define KEY_NEW_TAB "new-tab"
#define KEY_NEW_WINDOW "new-window"
#define KEY_NEXT_PROFILE "next-profile"
#define KEY_NEXT_TAB "next-tab"
#define KEY_PASTE "paste"
#define KEY_PREV_PROFILE "prev-profile"
#define KEY_PREV_TAB "prev-tab"
#define KEY_RESET_AND_CLEAR "reset-and-clear"
#define KEY_RESET "reset"
#define KEY_SEARCH_FIND "search-find"
#define KEY_SEARCH_FIND_NEXT "search-find-next"
#define KEY_SEARCH_FIND_PREVIOUS "search-find-previous"
#define KEY_SELECT_ALL "select-all"
#define KEY_SAVE_CONTENTS "save-contents"
#define KEY_SET_TERMINAL_TITLE "set-terminal-title"
#define KEY_TOGGLE_MENUBAR "toggle-menubar"
#define KEY_ZOOM_IN "zoom-in"
#define KEY_ZOOM_NORMAL "zoom-normal"
#define KEY_ZOOM_OUT "zoom-out"
#define KEY_SWITCH_TAB_PREFIX "switch-to-tab-"
Enumerations
enum { ACTION_COLUMN , KEYVAL_COLUMN , N_COLUMNS }
Functions
void terminal_accels_init (void)
void terminal_accels_shutdown (void)
void terminal_edit_keys_dialog_show (GtkWindow *transient_parent)
void terminal_accels_set_gaction_accels (GtkApplication *app)
Macro Definition Documentation
ACCEL_PATH_CLOSE_TAB
#define ACCEL_PATH_CLOSE_TAB ACCEL_PATH_ROOT "FileCloseTab"
Definition at line 55 of file terminal-accels.c.
ACCEL_PATH_CLOSE_WINDOW
#define ACCEL_PATH_CLOSE_WINDOW ACCEL_PATH_ROOT "FileCloseWindow"
Definition at line 56 of file terminal-accels.c.
ACCEL_PATH_COPY
#define ACCEL_PATH_COPY ACCEL_PATH_ROOT "EditCopy"
Definition at line 57 of file terminal-accels.c.
ACCEL_PATH_DETACH_TAB
#define ACCEL_PATH_DETACH_TAB ACCEL_PATH_ROOT "TabsDetach"
Definition at line 78 of file terminal-accels.c.
ACCEL_PATH_FULL_SCREEN
#define ACCEL_PATH_FULL_SCREEN ACCEL_PATH_ROOT "ViewFullscreen"
Definition at line 64 of file terminal-accels.c.
ACCEL_PATH_HELP
#define ACCEL_PATH_HELP ACCEL_PATH_ROOT "HelpContents"
Definition at line 72 of file terminal-accels.c.
ACCEL_PATH_MOVE_TAB_LEFT
#define ACCEL_PATH_MOVE_TAB_LEFT ACCEL_PATH_ROOT "TabsMoveLeft"
Definition at line 76 of file terminal-accels.c.
ACCEL_PATH_MOVE_TAB_RIGHT
#define ACCEL_PATH_MOVE_TAB_RIGHT ACCEL_PATH_ROOT "TabsMoveRight"
Definition at line 77 of file terminal-accels.c.
ACCEL_PATH_NEW_PROFILE
#define ACCEL_PATH_NEW_PROFILE ACCEL_PATH_ROOT "FileNewProfile"
Definition at line 53 of file terminal-accels.c.
ACCEL_PATH_NEW_TAB
#define ACCEL_PATH_NEW_TAB ACCEL_PATH_ROOT "FileNewTab"
Definition at line 51 of file terminal-accels.c.
ACCEL_PATH_NEW_WINDOW
#define ACCEL_PATH_NEW_WINDOW ACCEL_PATH_ROOT "FileNewWindow"
Definition at line 52 of file terminal-accels.c.
ACCEL_PATH_NEXT_PROFILE
#define ACCEL_PATH_NEXT_PROFILE ACCEL_PATH_ROOT "ProfileNext"
Definition at line 68 of file terminal-accels.c.
ACCEL_PATH_NEXT_TAB
#define ACCEL_PATH_NEXT_TAB ACCEL_PATH_ROOT "TabsNext"
Definition at line 70 of file terminal-accels.c.
ACCEL_PATH_PASTE
#define ACCEL_PATH_PASTE ACCEL_PATH_ROOT "EditPaste"
Definition at line 58 of file terminal-accels.c.
ACCEL_PATH_PREV_PROFILE
#define ACCEL_PATH_PREV_PROFILE ACCEL_PATH_ROOT "ProfilePrevious"
Definition at line 67 of file terminal-accels.c.
ACCEL_PATH_PREV_TAB
#define ACCEL_PATH_PREV_TAB ACCEL_PATH_ROOT "TabsPrevious"
Definition at line 69 of file terminal-accels.c.
ACCEL_PATH_RESET
#define ACCEL_PATH_RESET ACCEL_PATH_ROOT "TerminalReset"
Definition at line 65 of file terminal-accels.c.
ACCEL_PATH_RESET_AND_CLEAR
#define ACCEL_PATH_RESET_AND_CLEAR ACCEL_PATH_ROOT "TerminalResetClear"
Definition at line 66 of file terminal-accels.c.
ACCEL_PATH_ROOT
#define ACCEL_PATH_ROOT "<Actions>/Main/"
Definition at line 50 of file terminal-accels.c.
ACCEL_PATH_SAVE_CONTENTS
#define ACCEL_PATH_SAVE_CONTENTS ACCEL_PATH_ROOT "FileSaveContents"
Definition at line 54 of file terminal-accels.c.
ACCEL_PATH_SEARCH_FIND
#define ACCEL_PATH_SEARCH_FIND ACCEL_PATH_ROOT "SearchFind"
Definition at line 60 of file terminal-accels.c.
ACCEL_PATH_SEARCH_FIND_NEXT
#define ACCEL_PATH_SEARCH_FIND_NEXT ACCEL_PATH_ROOT "SearchFindNext"
Definition at line 61 of file terminal-accels.c.
ACCEL_PATH_SEARCH_FIND_PREVIOUS
#define ACCEL_PATH_SEARCH_FIND_PREVIOUS ACCEL_PATH_ROOT "SearchFindPrevious"
Definition at line 62 of file terminal-accels.c.
ACCEL_PATH_SELECT_ALL
#define ACCEL_PATH_SELECT_ALL ACCEL_PATH_ROOT "EditSelectAll"
Definition at line 59 of file terminal-accels.c.
ACCEL_PATH_SET_TERMINAL_TITLE
#define ACCEL_PATH_SET_TERMINAL_TITLE ACCEL_PATH_ROOT "TerminalSetTitle"
Definition at line 71 of file terminal-accels.c.
ACCEL_PATH_SWITCH_TAB_PREFIX
#define ACCEL_PATH_SWITCH_TAB_PREFIX ACCEL_PATH_ROOT "TabsSwitch"
Definition at line 79 of file terminal-accels.c.
ACCEL_PATH_TOGGLE_MENUBAR
#define ACCEL_PATH_TOGGLE_MENUBAR ACCEL_PATH_ROOT "ViewMenubar"
Definition at line 63 of file terminal-accels.c.
ACCEL_PATH_ZOOM_IN
#define ACCEL_PATH_ZOOM_IN ACCEL_PATH_ROOT "ViewZoomIn"
Definition at line 73 of file terminal-accels.c.
ACCEL_PATH_ZOOM_NORMAL
#define ACCEL_PATH_ZOOM_NORMAL ACCEL_PATH_ROOT "ViewZoom100"
Definition at line 75 of file terminal-accels.c.
ACCEL_PATH_ZOOM_OUT
#define ACCEL_PATH_ZOOM_OUT ACCEL_PATH_ROOT "ViewZoomOut"
Definition at line 74 of file terminal-accels.c.
KEY_CLOSE_TAB
#define KEY_CLOSE_TAB "close-tab"
Definition at line 81 of file terminal-accels.c.
KEY_CLOSE_WINDOW
#define KEY_CLOSE_WINDOW "close-window"
Definition at line 82 of file terminal-accels.c.
KEY_COPY
#define KEY_COPY "copy"
Definition at line 83 of file terminal-accels.c.
KEY_DETACH_TAB
#define KEY_DETACH_TAB "detach-tab"
Definition at line 84 of file terminal-accels.c.
KEY_FULL_SCREEN
#define KEY_FULL_SCREEN "full-screen"
Definition at line 85 of file terminal-accels.c.
KEY_HELP
#define KEY_HELP "help"
Definition at line 86 of file terminal-accels.c.
KEY_MOVE_TAB_LEFT
#define KEY_MOVE_TAB_LEFT "move-tab-left"
Definition at line 87 of file terminal-accels.c.
KEY_MOVE_TAB_RIGHT
#define KEY_MOVE_TAB_RIGHT "move-tab-right"
Definition at line 88 of file terminal-accels.c.
KEY_NEW_PROFILE
#define KEY_NEW_PROFILE "new-profile"
Definition at line 89 of file terminal-accels.c.
KEY_NEW_TAB
#define KEY_NEW_TAB "new-tab"
Definition at line 90 of file terminal-accels.c.
KEY_NEW_WINDOW
#define KEY_NEW_WINDOW "new-window"
Definition at line 91 of file terminal-accels.c.
KEY_NEXT_PROFILE
#define KEY_NEXT_PROFILE "next-profile"
Definition at line 92 of file terminal-accels.c.
KEY_NEXT_TAB
#define KEY_NEXT_TAB "next-tab"
Definition at line 93 of file terminal-accels.c.
KEY_PASTE
#define KEY_PASTE "paste"
Definition at line 94 of file terminal-accels.c.
KEY_PREV_PROFILE
#define KEY_PREV_PROFILE "prev-profile"
Definition at line 95 of file terminal-accels.c.
KEY_PREV_TAB
#define KEY_PREV_TAB "prev-tab"
Definition at line 96 of file terminal-accels.c.
KEY_RESET
#define KEY_RESET "reset"
Definition at line 98 of file terminal-accels.c.
KEY_RESET_AND_CLEAR
#define KEY_RESET_AND_CLEAR "reset-and-clear"
Definition at line 97 of file terminal-accels.c.
KEY_SAVE_CONTENTS
#define KEY_SAVE_CONTENTS "save-contents"
Definition at line 103 of file terminal-accels.c.
KEY_SEARCH_FIND
#define KEY_SEARCH_FIND "search-find"
Definition at line 99 of file terminal-accels.c.
KEY_SEARCH_FIND_NEXT
#define KEY_SEARCH_FIND_NEXT "search-find-next"
Definition at line 100 of file terminal-accels.c.
KEY_SEARCH_FIND_PREVIOUS
#define KEY_SEARCH_FIND_PREVIOUS "search-find-previous"
Definition at line 101 of file terminal-accels.c.
KEY_SELECT_ALL
#define KEY_SELECT_ALL "select-all"
Definition at line 102 of file terminal-accels.c.
KEY_SET_TERMINAL_TITLE
#define KEY_SET_TERMINAL_TITLE "set-terminal-title"
Definition at line 104 of file terminal-accels.c.
KEY_SWITCH_TAB_PREFIX
#define KEY_SWITCH_TAB_PREFIX "switch-to-tab-"
Definition at line 109 of file terminal-accels.c.
KEY_TOGGLE_MENUBAR
#define KEY_TOGGLE_MENUBAR "toggle-menubar"
Definition at line 105 of file terminal-accels.c.
KEY_ZOOM_IN
#define KEY_ZOOM_IN "zoom-in"
Definition at line 106 of file terminal-accels.c.
KEY_ZOOM_NORMAL
#define KEY_ZOOM_NORMAL "zoom-normal"
Definition at line 107 of file terminal-accels.c.
KEY_ZOOM_OUT
#define KEY_ZOOM_OUT "zoom-out"
Definition at line 108 of file terminal-accels.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ACTION_COLUMN
KEYVAL_COLUMN
N_COLUMNS
Definition at line 356 of file terminal-accels.c.
Function Documentation
terminal_accels_init()
void terminal_accels_init (void)
Definition at line 414 of file terminal-accels.c.
References CONF_KEYS_SCHEMA, I_, and NULL.
terminal_accels_set_gaction_accels()
void terminal_accels_set_gaction_accels (GtkApplication * app)
Definition at line 1172 of file terminal-accels.c.
References NULL.
terminal_accels_shutdown()
void terminal_accels_shutdown (void)
Definition at line 458 of file terminal-accels.c.
References NULL.
terminal_edit_keys_dialog_show()
void terminal_edit_keys_dialog_show (GtkWindow * transient_parent)
Definition at line 988 of file terminal-accels.c.
References _, _TERMINAL_DEBUG_IF, ACTION_COLUMN, KEYVAL_COLUMN, N_COLUMNS, NULL, TERMINAL_APP_ENABLE_MENU_BAR_ACCEL, TERMINAL_APP_ENABLE_MNEMONICS, terminal_app_get(), TERMINAL_DEBUG_ACCELS, terminal_util_bind_object_property_to_widget(), terminal_util_load_builder_resource(), and TRUE.
Referenced by terminal_app_edit_keybindings().