MATE Desktop Environment: terminal-window.c File Reference
terminal-window.c File Reference
#include <config.h>
#include <string.h>
#include <stdlib.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <gdk/gdkkeysyms.h>
#include "terminal-accels.h"
#include "terminal-actions.h"
#include "terminal-app.h"
#include "terminal-debug.h"
#include "terminal-encoding.h"
#include "terminal-intl.h"
#include "terminal-screen-container.h"
#include "terminal-search-dialog.h"
#include "terminal-tab-label.h"
#include "terminal-tabs-menu.h"
#include "terminal-util.h"
#include "terminal-window.h"
#include "terminal-version.h"
Macros
#define PROFILE_DATA_KEY "GT::Profile"
#define FILE_NEW_TERMINAL_TAB_UI_PATH "/menubar/File/FileNewTabProfiles"
#define FILE_NEW_TERMINAL_WINDOW_UI_PATH "/menubar/File/FileNewWindowProfiles"
#define SET_ENCODING_UI_PATH "/menubar/Terminal/TerminalSetEncoding/EncodingsPH"
#define SET_ENCODING_ACTION_NAME_PREFIX "TerminalSetEncoding"
#define PROFILES_UI_PATH "/menubar/Terminal/TerminalProfiles/ProfilesPH"
#define PROFILES_POPUP_UI_PATH "/Popup/PopupTerminalProfiles/ProfilesPH"
#define SIZE_TO_UI_PATH "/menubar/Terminal/TerminalSizeToPH"
#define SIZE_TO_ACTION_NAME_PREFIX "TerminalSizeTo"
#define STOCK_NEW_TAB "tab-new"
#define ENCODING_DATA_KEY "encoding"
#define NoValue 0x0000
#define XValue 0x0001
#define YValue 0x0002
#define WidthValue 0x0004
#define HeightValue 0x0008
#define XNegative 0x0010
#define YNegative 0x0020
#define MIN_WIDTH_CHARS 4
#define MIN_HEIGHT_CHARS 1
#define ABOUT_GROUP "About"
#define EMAILIFY(string)
Functions
TerminalWindow * terminal_window_new (void)
void terminal_window_set_is_restored (TerminalWindow *window)
void terminal_window_add_screen (TerminalWindow *window, TerminalScreen *screen, int position)
void terminal_window_remove_screen (TerminalWindow *window, TerminalScreen *screen)
void terminal_window_move_screen (TerminalWindow *source_window, TerminalWindow *dest_window, TerminalScreen *screen, int dest_position)
GList * terminal_window_list_screen_containers (TerminalWindow *window)
void terminal_window_set_menubar_visible (TerminalWindow *window, gboolean setting)
gboolean terminal_window_get_menubar_visible (TerminalWindow *window)
void terminal_window_set_icon (TerminalWindow *window, const char *icon)
GtkWidget * terminal_window_get_notebook (TerminalWindow *window)
void terminal_window_update_size (TerminalWindow *window, TerminalScreen *screen, gboolean even_if_mapped)
gboolean terminal_window_update_size_set_geometry (TerminalWindow *window, TerminalScreen *screen, gboolean even_if_mapped, gchar *geometry_string)
void terminal_window_switch_screen (TerminalWindow *window, TerminalScreen *screen)
TerminalScreen * terminal_window_get_active (TerminalWindow *window)
void terminal_window_update_copy_selection (TerminalScreen *screen, TerminalWindow *window)
void terminal_window_update_geometry (TerminalWindow *window)
GtkUIManager * terminal_window_get_ui_manager (TerminalWindow *window)
void terminal_window_show_find_dialog (TerminalWindow *window)
void terminal_window_show_set_title_dialog (TerminalWindow *window)
void terminal_window_detach_screen (TerminalWindow *window, TerminalScreen *screen)
void terminal_window_show_about_dialog (GtkWindow *parent)
void terminal_window_save_state (TerminalWindow *window, GKeyFile *key_file, const char *group)
TerminalWindow * terminal_window_get_latest_focused (TerminalWindow *window1, TerminalWindow *window2)
Macro Definition Documentation
ABOUT_GROUP
#define ABOUT_GROUP "About"
Definition at line 4534 of file terminal-window.c.
EMAILIFY
#define EMAILIFY (string)
Value:
(g_strdelimit ((string), "%", '@'))
Definition at line 4535 of file terminal-window.c.
ENCODING_DATA_KEY
#define ENCODING_DATA_KEY "encoding"
Definition at line 134 of file terminal-window.c.
FILE_NEW_TERMINAL_TAB_UI_PATH
#define FILE_NEW_TERMINAL_TAB_UI_PATH "/menubar/File/FileNewTabProfiles"
Definition at line 121 of file terminal-window.c.
FILE_NEW_TERMINAL_WINDOW_UI_PATH
#define FILE_NEW_TERMINAL_WINDOW_UI_PATH "/menubar/File/FileNewWindowProfiles"
Definition at line 122 of file terminal-window.c.
HeightValue
#define HeightValue 0x0008
Definition at line 406 of file terminal-window.c.
Referenced by terminal_window_update_size_set_geometry().
MIN_HEIGHT_CHARS
#define MIN_HEIGHT_CHARS 1
Referenced by terminal_window_update_geometry().
MIN_WIDTH_CHARS
#define MIN_WIDTH_CHARS 4
Referenced by terminal_window_update_geometry().
NoValue
#define NoValue 0x0000
Definition at line 402 of file terminal-window.c.
Referenced by terminal_window_update_size_set_geometry().
PROFILE_DATA_KEY
#define PROFILE_DATA_KEY "GT::Profile"
Definition at line 119 of file terminal-window.c.
PROFILES_POPUP_UI_PATH
#define PROFILES_POPUP_UI_PATH "/Popup/PopupTerminalProfiles/ProfilesPH"
Definition at line 127 of file terminal-window.c.
PROFILES_UI_PATH
#define PROFILES_UI_PATH "/menubar/Terminal/TerminalProfiles/ProfilesPH"
Definition at line 126 of file terminal-window.c.
SET_ENCODING_ACTION_NAME_PREFIX
#define SET_ENCODING_ACTION_NAME_PREFIX "TerminalSetEncoding"
Definition at line 124 of file terminal-window.c.
SET_ENCODING_UI_PATH
#define SET_ENCODING_UI_PATH "/menubar/Terminal/TerminalSetEncoding/EncodingsPH"
Definition at line 123 of file terminal-window.c.
SIZE_TO_ACTION_NAME_PREFIX
#define SIZE_TO_ACTION_NAME_PREFIX "TerminalSizeTo"
Definition at line 130 of file terminal-window.c.
SIZE_TO_UI_PATH
#define SIZE_TO_UI_PATH "/menubar/Terminal/TerminalSizeToPH"
Definition at line 129 of file terminal-window.c.
STOCK_NEW_TAB
#define STOCK_NEW_TAB "tab-new"
Definition at line 132 of file terminal-window.c.
WidthValue
#define WidthValue 0x0004
Definition at line 405 of file terminal-window.c.
Referenced by terminal_window_update_size_set_geometry().
XNegative
#define XNegative 0x0010
Definition at line 407 of file terminal-window.c.
Referenced by terminal_window_update_size_set_geometry().
XValue
#define XValue 0x0001
Definition at line 403 of file terminal-window.c.
Referenced by terminal_window_update_size_set_geometry().
YNegative
#define YNegative 0x0020
Definition at line 408 of file terminal-window.c.
Referenced by terminal_window_update_size_set_geometry().
YValue
#define YValue 0x0002
Definition at line 404 of file terminal-window.c.
Referenced by terminal_window_update_size_set_geometry().
Function Documentation
terminal_window_add_screen()
void terminal_window_add_screen (TerminalWindow * window, TerminalScreen * screen, int position)
Definition at line 2689 of file terminal-window.c.
References NULL, TERMINAL_IS_WINDOW, terminal_screen_container_new(), terminal_tab_label_new(), TERMINAL_WINDOW, terminal_window_remove_screen(), and TRUE.
Referenced by terminal_app_new_terminal(), and terminal_window_move_screen().
terminal_window_detach_screen()
void terminal_window_detach_screen (TerminalWindow * window, TerminalScreen * screen)
Definition at line 4649 of file terminal-window.c.
References NULL, TERMINAL_IS_SCREEN, and TERMINAL_IS_WINDOW.
terminal_window_get_active()
TerminalScreen * terminal_window_get_active (TerminalWindow * window)
Definition at line 3032 of file terminal-window.c.
Referenced by terminal_app_handle_options(), and terminal_window_save_state().
terminal_window_get_latest_focused()
TerminalWindow * terminal_window_get_latest_focused (TerminalWindow * window1, TerminalWindow * window2)
Definition at line 4744 of file terminal-window.c.
References NULL, and _TerminalWindow::priv.
Referenced by terminal_app_get_current_window().
terminal_window_get_menubar_visible()
gboolean terminal_window_get_menubar_visible (TerminalWindow * window)
Definition at line 2841 of file terminal-window.c.
terminal_window_get_notebook()
GtkWidget * terminal_window_get_notebook (TerminalWindow * window)
Definition at line 2877 of file terminal-window.c.
References NULL, and TERMINAL_IS_WINDOW.
terminal_window_get_ui_manager()
GtkUIManager * terminal_window_get_ui_manager (TerminalWindow * window)
Definition at line 4625 of file terminal-window.c.
terminal_window_list_screen_containers()
GList * terminal_window_list_screen_containers (TerminalWindow * window)
Definition at line 2797 of file terminal-window.c.
Referenced by terminal_window_save_state().
terminal_window_move_screen()
void terminal_window_move_screen (TerminalWindow * source_window, TerminalWindow * dest_window, TerminalScreen * screen, int dest_position)
Definition at line 2761 of file terminal-window.c.
References _TerminalWindow::priv, TERMINAL_IS_SCREEN, TERMINAL_IS_SCREEN_CONTAINER, TERMINAL_IS_WINDOW, terminal_screen_container_get_from_screen(), terminal_window_add_screen(), and TRUE.
terminal_window_new()
TerminalWindow * terminal_window_new (void)
Definition at line 2555 of file terminal-window.c.
References NULL, and TERMINAL_TYPE_WINDOW.
Referenced by terminal_app_new_window().
terminal_window_remove_screen()
void terminal_window_remove_screen (TerminalWindow * window, TerminalScreen * screen)
Definition at line 2754 of file terminal-window.c.
References FALSE.
Referenced by terminal_window_add_screen().
terminal_window_save_state()
void terminal_window_save_state (TerminalWindow * window, GKeyFile * key_file, const char * group)
Definition at line 4672 of file terminal-window.c.
References FALSE, NULL, TERMINAL_CONFIG_WINDOW_PROP_ACTIVE_TAB, TERMINAL_CONFIG_WINDOW_PROP_FULLSCREEN, TERMINAL_CONFIG_WINDOW_PROP_GEOMETRY, TERMINAL_CONFIG_WINDOW_PROP_ICON, TERMINAL_CONFIG_WINDOW_PROP_MAXIMIZED, TERMINAL_CONFIG_WINDOW_PROP_MENUBAR_VISIBLE, TERMINAL_CONFIG_WINDOW_PROP_ROLE, TERMINAL_CONFIG_WINDOW_PROP_TABS, TERMINAL_SCREEN_CONTAINER, terminal_screen_container_get_screen(), terminal_screen_get_size(), terminal_screen_save_config(), terminal_window_get_active(), terminal_window_list_screen_containers(), and TRUE.
Referenced by terminal_app_save_config().
terminal_window_set_icon()
void terminal_window_set_icon (TerminalWindow * window, const char * icon)
Definition at line 2849 of file terminal-window.c.
References _, error, and NULL.
Referenced by terminal_app_handle_options().
terminal_window_set_is_restored()
void terminal_window_set_is_restored (TerminalWindow * window)
terminal_window_set_is_restored: @window:
Marks the window as restored from session.
Definition at line 2567 of file terminal-window.c.
References TERMINAL_IS_WINDOW, and TRUE.
Referenced by terminal_app_handle_options().
terminal_window_set_menubar_visible()
void terminal_window_set_menubar_visible (TerminalWindow * window, gboolean setting)
Definition at line 2806 of file terminal-window.c.
References action, FALSE, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, NULL, TERMINAL_DEBUG_GEOMETRY, terminal_window_update_size(), and TRUE.
Referenced by terminal_app_handle_options().
terminal_window_show_about_dialog()
void terminal_window_show_about_dialog (GtkWindow * parent)
Definition at line 4657 of file terminal-window.c.
References NULL, TERMINAL_IS_WINDOW, and TERMINAL_WINDOW.
terminal_window_show_find_dialog()
void terminal_window_show_find_dialog (TerminalWindow * window)
Definition at line 4635 of file terminal-window.c.
References NULL, and TERMINAL_IS_WINDOW.
terminal_window_show_set_title_dialog()
void terminal_window_show_set_title_dialog (TerminalWindow * window)
Definition at line 4642 of file terminal-window.c.
References NULL, and TERMINAL_IS_WINDOW.
terminal_window_switch_screen()
void terminal_window_switch_screen (TerminalWindow * window, TerminalScreen * screen)
Definition at line 3017 of file terminal-window.c.
References TERMINAL_IS_SCREEN_CONTAINER, and terminal_screen_container_get_from_screen().
Referenced by terminal_app_handle_options(), and terminal_app_new_terminal().
terminal_window_update_copy_selection()
void terminal_window_update_copy_selection (TerminalScreen * screen, TerminalWindow * window)
Definition at line 3426 of file terminal-window.c.
References TERMINAL_PROFILE_COPY_SELECTION, terminal_profile_get_property_boolean(), and terminal_screen_get_profile().
terminal_window_update_geometry()
void terminal_window_update_geometry (TerminalWindow * window)
Definition at line 3498 of file terminal-window.c.
References FALSE, GDK_IS_X11_DISPLAY, MIN_HEIGHT_CHARS, MIN_WIDTH_CHARS, NULL, TERMINAL_DEBUG_GEOMETRY, terminal_screen_get_cell_size(), terminal_screen_get_size(), and TRUE.
Referenced by terminal_window_update_size_set_geometry().
terminal_window_update_size()
void terminal_window_update_size (TerminalWindow * window, TerminalScreen * screen, gboolean even_if_mapped)
Definition at line 2887 of file terminal-window.c.
References NULL, and terminal_window_update_size_set_geometry().
Referenced by terminal_window_set_menubar_visible().
terminal_window_update_size_set_geometry()
gboolean terminal_window_update_size_set_geometry (TerminalWindow * window, TerminalScreen * screen, gboolean even_if_mapped, gchar * geometry_string)
Definition at line 2896 of file terminal-window.c.
References FALSE, HeightValue, NoValue, NULL, TERMINAL_DEBUG_GEOMETRY, terminal_screen_get_size(), terminal_window_update_geometry(), TRUE, WidthValue, XNegative, XValue, YNegative, and YValue.
Referenced by terminal_app_handle_options(), and terminal_window_update_size().