MATE Desktop Environment: terminal-profile.c File Reference
terminal-profile.c File Reference
#include <config.h>
#include <string.h>
#include <stdlib.h>
#include <gtk/gtk.h>
#include "terminal-app.h"
#include "terminal-debug.h"
#include "terminal-intl.h"
#include "terminal-profile.h"
#include "terminal-screen.h"
#include "terminal-type-builtins.h"
Macros
#define KEY_ALLOW_BOLD "allow-bold"
#define KEY_BACKGROUND_COLOR "background-color"
#define KEY_BACKGROUND_DARKNESS "background-darkness"
#define KEY_BACKGROUND_IMAGE_FILE "background-image"
#define KEY_BACKGROUND_TYPE "background-type"
#define KEY_BACKSPACE_BINDING "backspace-binding"
#define KEY_BOLD_COLOR "bold-color"
#define KEY_BOLD_COLOR_SAME_AS_FG "bold-color-same-as-fg"
#define KEY_CURSOR_BLINK_MODE "cursor-blink-mode"
#define KEY_CURSOR_SHAPE "cursor-shape"
#define KEY_CUSTOM_COMMAND "custom-command"
#define KEY_DEFAULT_SHOW_MENUBAR "default-show-menubar"
#define KEY_DEFAULT_SIZE_COLUMNS "default-size-columns"
#define KEY_DEFAULT_SIZE_ROWS "default-size-rows"
#define KEY_DELETE_BINDING "delete-binding"
#define KEY_EXIT_ACTION "exit-action"
#define KEY_FONT "font"
#define KEY_FOREGROUND_COLOR "foreground-color"
#define KEY_LOGIN_SHELL "login-shell"
#define KEY_PALETTE "palette"
#define KEY_SCROLL_BACKGROUND "scroll-background"
#define KEY_SCROLLBACK_LINES "scrollback-lines"
#define KEY_SCROLLBACK_UNLIMITED "scrollback-unlimited"
#define KEY_SCROLLBAR_POSITION "scrollbar-position"
#define KEY_SCROLL_ON_KEYSTROKE "scroll-on-keystroke"
#define KEY_SCROLL_ON_OUTPUT "scroll-on-output"
#define KEY_SILENT_BELL "silent-bell"
#define KEY_COPY_SELECTION "copy-selection"
#define KEY_TITLE_MODE "title-mode"
#define KEY_TITLE "title"
#define KEY_USE_CUSTOM_COMMAND "use-custom-command"
#define KEY_USE_CUSTOM_DEFAULT_SIZE "use-custom-default-size"
#define KEY_USE_SKEY "use-skey"
#define KEY_USE_URLS "use-urls"
#define KEY_USE_SYSTEM_FONT "use-system-font"
#define KEY_USE_THEME_COLORS "use-theme-colors"
#define KEY_VISIBLE_NAME "visible-name"
#define KEY_WORD_CHARS "word-chars"
#define DEFAULT_ALLOW_BOLD (TRUE)
#define DEFAULT_BACKGROUND_COLOR ("#FFFFDD")
#define DEFAULT_BOLD_COLOR_SAME_AS_FG (TRUE)
#define DEFAULT_BACKGROUND_DARKNESS (0.5)
#define DEFAULT_BACKGROUND_IMAGE_FILE ("")
#define DEFAULT_BACKGROUND_TYPE (TERMINAL_BACKGROUND_SOLID)
#define DEFAULT_BACKSPACE_BINDING (VTE_ERASE_ASCII_DELETE)
#define DEFAULT_CURSOR_BLINK_MODE (VTE_CURSOR_BLINK_SYSTEM)
#define DEFAULT_CURSOR_SHAPE (VTE_CURSOR_SHAPE_BLOCK)
#define DEFAULT_CUSTOM_COMMAND ("")
#define DEFAULT_DEFAULT_SHOW_MENUBAR (TRUE)
#define DEFAULT_DEFAULT_SIZE_COLUMNS (80)
#define DEFAULT_DEFAULT_SIZE_ROWS (24)
#define DEFAULT_DELETE_BINDING (VTE_ERASE_DELETE_SEQUENCE)
#define DEFAULT_EXIT_ACTION (TERMINAL_EXIT_CLOSE)
#define DEFAULT_FONT ("Monospace 12")
#define DEFAULT_FOREGROUND_COLOR ("#000000")
#define DEFAULT_LOGIN_SHELL (FALSE)
#define DEFAULT_NAME (NULL)
#define DEFAULT_PALETTE (terminal_palettes[TERMINAL_PALETTE_TANGO])
#define DEFAULT_SCROLL_BACKGROUND (TRUE)
#define DEFAULT_SCROLLBACK_LINES (512)
#define DEFAULT_SCROLLBACK_UNLIMITED (FALSE)
#define DEFAULT_SCROLLBAR_POSITION (TERMINAL_SCROLLBAR_RIGHT)
#define DEFAULT_SCROLL_ON_KEYSTROKE (TRUE)
#define DEFAULT_SCROLL_ON_OUTPUT (FALSE)
#define DEFAULT_SILENT_BELL (FALSE)
#define DEFAULT_COPY_SELECTION (FALSE)
#define DEFAULT_TITLE_MODE (TERMINAL_TITLE_REPLACE)
#define DEFAULT_TITLE (N_("Terminal"))
#define DEFAULT_USE_CUSTOM_COMMAND (FALSE)
#define DEFAULT_USE_CUSTOM_DEFAULT_SIZE (FALSE)
#define DEFAULT_USE_SKEY (TRUE)
#define DEFAULT_USE_URLS (TRUE)
#define DEFAULT_USE_SYSTEM_FONT (TRUE)
#define DEFAULT_USE_THEME_COLORS (TRUE)
#define DEFAULT_VISIBLE_NAME (N_("Unnamed"))
#define DEFAULT_WORD_CHARS ("-A-Za-z0-9,./?%&#:_=+@~")
#define TERMINAL_PROFILE_PSPEC_STATIC (G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB)
#define TERMINAL_PROFILE_PROPERTY(propId, propSpec, propGSettings)
#define TERMINAL_PROFILE_PROPERTY_OUTER(propId, propSpec)
#define TERMINAL_PROFILE_PROPERTY_BOOLEAN(prop, propDefault, propGSettings)
#define TERMINAL_PROFILE_PROPERTY_BOXED(prop, propType, propGSettings)
#define TERMINAL_PROFILE_PROPERTY_DOUBLE(prop, propMin, propMax, propDefault, propGSettings)
#define TERMINAL_PROFILE_PROPERTY_ENUM(prop, propType, propDefault, propGSettings)
#define TERMINAL_PROFILE_PROPERTY_INT(prop, propMin, propMax, propDefault, propGSettings)
#define TERMINAL_PROFILE_PROPERTY_OBJECT(prop, propType)
#define TERMINAL_PROFILE_PROPERTY_STRING(prop, propDefault, propGSettings)
#define TERMINAL_PROFILE_PROPERTY_STRING_CO(prop, propDefault)
#define TERMINAL_PROFILE_PROPERTY_VALUE_ARRAY_BOXED(prop, propElementName, propElementType, propGSettings)
Enumerations
enum {
PROP_0 , PROP_ALLOW_BOLD , PROP_BACKGROUND_COLOR , PROP_BACKGROUND_DARKNESS ,
PROP_BACKGROUND_IMAGE , PROP_BACKGROUND_IMAGE_FILE , PROP_BACKGROUND_TYPE , PROP_BACKSPACE_BINDING ,
PROP_BOLD_COLOR , PROP_BOLD_COLOR_SAME_AS_FG , PROP_CURSOR_BLINK_MODE , PROP_CURSOR_SHAPE ,
PROP_CUSTOM_COMMAND , PROP_DEFAULT_SIZE_COLUMNS , PROP_DEFAULT_SIZE_ROWS , PROP_DEFAULT_SHOW_MENUBAR ,
PROP_DELETE_BINDING , PROP_EXIT_ACTION , PROP_FONT , PROP_FOREGROUND_COLOR ,
PROP_LOGIN_SHELL , PROP_NAME , PROP_PALETTE , PROP_SCROLL_BACKGROUND ,
PROP_SCROLLBACK_LINES , PROP_SCROLLBACK_UNLIMITED , PROP_SCROLLBAR_POSITION , PROP_SCROLL_ON_KEYSTROKE ,
PROP_SCROLL_ON_OUTPUT , PROP_SILENT_BELL , PROP_TITLE , PROP_TITLE_MODE ,
PROP_USE_CUSTOM_COMMAND , PROP_USE_CUSTOM_DEFAULT_SIZE , PROP_USE_SKEY , PROP_USE_URLS ,
PROP_USE_SYSTEM_FONT , PROP_USE_THEME_COLORS , PROP_VISIBLE_NAME , PROP_WORD_CHARS ,
PROP_COPY_SELECTION , LAST_PROP
}
enum { FORGOTTEN , LAST_SIGNAL }
Functions
G_DEFINE_TYPE_WITH_PRIVATE (TerminalProfile, terminal_profile, G_TYPE_OBJECT)
TerminalProfile * _terminal_profile_new (const char *name)
void _terminal_profile_forget (TerminalProfile *profile)
gboolean _terminal_profile_get_forgotten (TerminalProfile *profile)
TerminalProfile * _terminal_profile_clone (TerminalProfile *base_profile, const char *visible_name)
gboolean terminal_profile_get_property_boolean (TerminalProfile *profile, const char *prop_name)
gconstpointer terminal_profile_get_property_boxed (TerminalProfile *profile, const char *prop_name)
double terminal_profile_get_property_double (TerminalProfile *profile, const char *prop_name)
int terminal_profile_get_property_enum (TerminalProfile *profile, const char *prop_name)
int terminal_profile_get_property_int (TerminalProfile *profile, const char *prop_name)
gpointer terminal_profile_get_property_object (TerminalProfile *profile, const char *prop_name)
const char * terminal_profile_get_property_string (TerminalProfile *profile, const char *prop_name)
gboolean terminal_profile_property_locked (TerminalProfile *profile, const char *prop_name)
void terminal_profile_reset_property (TerminalProfile *profile, const char *prop_name)
gboolean terminal_profile_get_palette (TerminalProfile *profile, GdkRGBA *colors, guint *n_colors)
gboolean terminal_profile_get_palette_is_builtin (TerminalProfile *profile, guint *n)
void terminal_profile_set_palette_builtin (TerminalProfile *profile, guint n)
gboolean terminal_profile_modify_palette_entry (TerminalProfile *profile, guint i, const GdkRGBA *color)
Macro Definition Documentation
DEFAULT_ALLOW_BOLD
#define DEFAULT_ALLOW_BOLD (TRUE)
Definition at line 132 of file terminal-profile.c.
DEFAULT_BACKGROUND_COLOR
#define DEFAULT_BACKGROUND_COLOR ("#FFFFDD")
Definition at line 133 of file terminal-profile.c.
DEFAULT_BACKGROUND_DARKNESS
#define DEFAULT_BACKGROUND_DARKNESS (0.5)
Definition at line 135 of file terminal-profile.c.
DEFAULT_BACKGROUND_IMAGE_FILE
#define DEFAULT_BACKGROUND_IMAGE_FILE ("")
Definition at line 136 of file terminal-profile.c.
DEFAULT_BACKGROUND_TYPE
#define DEFAULT_BACKGROUND_TYPE (TERMINAL_BACKGROUND_SOLID)
Definition at line 137 of file terminal-profile.c.
DEFAULT_BACKSPACE_BINDING
#define DEFAULT_BACKSPACE_BINDING (VTE_ERASE_ASCII_DELETE)
Definition at line 138 of file terminal-profile.c.
DEFAULT_BOLD_COLOR_SAME_AS_FG
#define DEFAULT_BOLD_COLOR_SAME_AS_FG (TRUE)
Definition at line 134 of file terminal-profile.c.
DEFAULT_COPY_SELECTION
#define DEFAULT_COPY_SELECTION (FALSE)
Definition at line 159 of file terminal-profile.c.
DEFAULT_CURSOR_BLINK_MODE
#define DEFAULT_CURSOR_BLINK_MODE (VTE_CURSOR_BLINK_SYSTEM)
Definition at line 139 of file terminal-profile.c.
DEFAULT_CURSOR_SHAPE
#define DEFAULT_CURSOR_SHAPE (VTE_CURSOR_SHAPE_BLOCK)
Definition at line 140 of file terminal-profile.c.
DEFAULT_CUSTOM_COMMAND
#define DEFAULT_CUSTOM_COMMAND ("")
Definition at line 141 of file terminal-profile.c.
DEFAULT_DEFAULT_SHOW_MENUBAR
#define DEFAULT_DEFAULT_SHOW_MENUBAR (TRUE)
Definition at line 142 of file terminal-profile.c.
DEFAULT_DEFAULT_SIZE_COLUMNS
#define DEFAULT_DEFAULT_SIZE_COLUMNS (80)
Definition at line 143 of file terminal-profile.c.
DEFAULT_DEFAULT_SIZE_ROWS
#define DEFAULT_DEFAULT_SIZE_ROWS (24)
Definition at line 144 of file terminal-profile.c.
DEFAULT_DELETE_BINDING
#define DEFAULT_DELETE_BINDING (VTE_ERASE_DELETE_SEQUENCE)
Definition at line 145 of file terminal-profile.c.
DEFAULT_EXIT_ACTION
#define DEFAULT_EXIT_ACTION (TERMINAL_EXIT_CLOSE)
Definition at line 146 of file terminal-profile.c.
DEFAULT_FONT
#define DEFAULT_FONT ("Monospace 12")
Definition at line 147 of file terminal-profile.c.
DEFAULT_FOREGROUND_COLOR
#define DEFAULT_FOREGROUND_COLOR ("#000000")
Definition at line 148 of file terminal-profile.c.
DEFAULT_LOGIN_SHELL
#define DEFAULT_LOGIN_SHELL (FALSE)
Definition at line 149 of file terminal-profile.c.
DEFAULT_NAME
#define DEFAULT_NAME (NULL)
Definition at line 150 of file terminal-profile.c.
DEFAULT_PALETTE
#define DEFAULT_PALETTE (terminal_palettes[TERMINAL_PALETTE_TANGO])
Definition at line 151 of file terminal-profile.c.
DEFAULT_SCROLL_BACKGROUND
#define DEFAULT_SCROLL_BACKGROUND (TRUE)
Definition at line 152 of file terminal-profile.c.
DEFAULT_SCROLL_ON_KEYSTROKE
#define DEFAULT_SCROLL_ON_KEYSTROKE (TRUE)
Definition at line 156 of file terminal-profile.c.
DEFAULT_SCROLL_ON_OUTPUT
#define DEFAULT_SCROLL_ON_OUTPUT (FALSE)
Definition at line 157 of file terminal-profile.c.
DEFAULT_SCROLLBACK_LINES
#define DEFAULT_SCROLLBACK_LINES (512)
Definition at line 153 of file terminal-profile.c.
DEFAULT_SCROLLBACK_UNLIMITED
#define DEFAULT_SCROLLBACK_UNLIMITED (FALSE)
Definition at line 154 of file terminal-profile.c.
DEFAULT_SCROLLBAR_POSITION
#define DEFAULT_SCROLLBAR_POSITION (TERMINAL_SCROLLBAR_RIGHT)
Definition at line 155 of file terminal-profile.c.
DEFAULT_SILENT_BELL
#define DEFAULT_SILENT_BELL (FALSE)
Definition at line 158 of file terminal-profile.c.
DEFAULT_TITLE
#define DEFAULT_TITLE (N_("Terminal"))
Definition at line 161 of file terminal-profile.c.
DEFAULT_TITLE_MODE
#define DEFAULT_TITLE_MODE (TERMINAL_TITLE_REPLACE)
Definition at line 160 of file terminal-profile.c.
DEFAULT_USE_CUSTOM_COMMAND
#define DEFAULT_USE_CUSTOM_COMMAND (FALSE)
Definition at line 162 of file terminal-profile.c.
DEFAULT_USE_CUSTOM_DEFAULT_SIZE
#define DEFAULT_USE_CUSTOM_DEFAULT_SIZE (FALSE)
Definition at line 163 of file terminal-profile.c.
DEFAULT_USE_SKEY
#define DEFAULT_USE_SKEY (TRUE)
Definition at line 164 of file terminal-profile.c.
DEFAULT_USE_SYSTEM_FONT
#define DEFAULT_USE_SYSTEM_FONT (TRUE)
Definition at line 166 of file terminal-profile.c.
DEFAULT_USE_THEME_COLORS
#define DEFAULT_USE_THEME_COLORS (TRUE)
Definition at line 167 of file terminal-profile.c.
DEFAULT_USE_URLS
#define DEFAULT_USE_URLS (TRUE)
Definition at line 165 of file terminal-profile.c.
DEFAULT_VISIBLE_NAME
#define DEFAULT_VISIBLE_NAME (N_("Unnamed"))
Definition at line 168 of file terminal-profile.c.
DEFAULT_WORD_CHARS
#define DEFAULT_WORD_CHARS ("-A-Za-z0-9,./?%&#:_=+@~")
Definition at line 169 of file terminal-profile.c.
KEY_ALLOW_BOLD
#define KEY_ALLOW_BOLD "allow-bold"
Definition at line 92 of file terminal-profile.c.
KEY_BACKGROUND_COLOR
#define KEY_BACKGROUND_COLOR "background-color"
Definition at line 93 of file terminal-profile.c.
KEY_BACKGROUND_DARKNESS
#define KEY_BACKGROUND_DARKNESS "background-darkness"
Definition at line 94 of file terminal-profile.c.
KEY_BACKGROUND_IMAGE_FILE
#define KEY_BACKGROUND_IMAGE_FILE "background-image"
Definition at line 95 of file terminal-profile.c.
KEY_BACKGROUND_TYPE
#define KEY_BACKGROUND_TYPE "background-type"
Definition at line 96 of file terminal-profile.c.
KEY_BACKSPACE_BINDING
#define KEY_BACKSPACE_BINDING "backspace-binding"
Definition at line 97 of file terminal-profile.c.
KEY_BOLD_COLOR
#define KEY_BOLD_COLOR "bold-color"
Definition at line 98 of file terminal-profile.c.
KEY_BOLD_COLOR_SAME_AS_FG
#define KEY_BOLD_COLOR_SAME_AS_FG "bold-color-same-as-fg"
Definition at line 99 of file terminal-profile.c.
KEY_COPY_SELECTION
#define KEY_COPY_SELECTION "copy-selection"
Definition at line 119 of file terminal-profile.c.
KEY_CURSOR_BLINK_MODE
#define KEY_CURSOR_BLINK_MODE "cursor-blink-mode"
Definition at line 100 of file terminal-profile.c.
KEY_CURSOR_SHAPE
#define KEY_CURSOR_SHAPE "cursor-shape"
Definition at line 101 of file terminal-profile.c.
KEY_CUSTOM_COMMAND
#define KEY_CUSTOM_COMMAND "custom-command"
Definition at line 102 of file terminal-profile.c.
KEY_DEFAULT_SHOW_MENUBAR
#define KEY_DEFAULT_SHOW_MENUBAR "default-show-menubar"
Definition at line 103 of file terminal-profile.c.
KEY_DEFAULT_SIZE_COLUMNS
#define KEY_DEFAULT_SIZE_COLUMNS "default-size-columns"
Definition at line 104 of file terminal-profile.c.
KEY_DEFAULT_SIZE_ROWS
#define KEY_DEFAULT_SIZE_ROWS "default-size-rows"
Definition at line 105 of file terminal-profile.c.
KEY_DELETE_BINDING
#define KEY_DELETE_BINDING "delete-binding"
Definition at line 106 of file terminal-profile.c.
KEY_EXIT_ACTION
#define KEY_EXIT_ACTION "exit-action"
Definition at line 107 of file terminal-profile.c.
KEY_FONT
#define KEY_FONT "font"
Definition at line 108 of file terminal-profile.c.
KEY_FOREGROUND_COLOR
#define KEY_FOREGROUND_COLOR "foreground-color"
Definition at line 109 of file terminal-profile.c.
KEY_LOGIN_SHELL
#define KEY_LOGIN_SHELL "login-shell"
Definition at line 110 of file terminal-profile.c.
KEY_PALETTE
#define KEY_PALETTE "palette"
Definition at line 111 of file terminal-profile.c.
KEY_SCROLL_BACKGROUND
#define KEY_SCROLL_BACKGROUND "scroll-background"
Definition at line 112 of file terminal-profile.c.
KEY_SCROLL_ON_KEYSTROKE
#define KEY_SCROLL_ON_KEYSTROKE "scroll-on-keystroke"
Definition at line 116 of file terminal-profile.c.
KEY_SCROLL_ON_OUTPUT
#define KEY_SCROLL_ON_OUTPUT "scroll-on-output"
Definition at line 117 of file terminal-profile.c.
KEY_SCROLLBACK_LINES
#define KEY_SCROLLBACK_LINES "scrollback-lines"
Definition at line 113 of file terminal-profile.c.
KEY_SCROLLBACK_UNLIMITED
#define KEY_SCROLLBACK_UNLIMITED "scrollback-unlimited"
Definition at line 114 of file terminal-profile.c.
KEY_SCROLLBAR_POSITION
#define KEY_SCROLLBAR_POSITION "scrollbar-position"
Definition at line 115 of file terminal-profile.c.
KEY_SILENT_BELL
#define KEY_SILENT_BELL "silent-bell"
Definition at line 118 of file terminal-profile.c.
KEY_TITLE
#define KEY_TITLE "title"
Definition at line 121 of file terminal-profile.c.
KEY_TITLE_MODE
#define KEY_TITLE_MODE "title-mode"
Definition at line 120 of file terminal-profile.c.
KEY_USE_CUSTOM_COMMAND
#define KEY_USE_CUSTOM_COMMAND "use-custom-command"
Definition at line 122 of file terminal-profile.c.
KEY_USE_CUSTOM_DEFAULT_SIZE
#define KEY_USE_CUSTOM_DEFAULT_SIZE "use-custom-default-size"
Definition at line 123 of file terminal-profile.c.
KEY_USE_SKEY
#define KEY_USE_SKEY "use-skey"
Definition at line 124 of file terminal-profile.c.
KEY_USE_SYSTEM_FONT
#define KEY_USE_SYSTEM_FONT "use-system-font"
Definition at line 126 of file terminal-profile.c.
KEY_USE_THEME_COLORS
#define KEY_USE_THEME_COLORS "use-theme-colors"
Definition at line 127 of file terminal-profile.c.
KEY_USE_URLS
#define KEY_USE_URLS "use-urls"
Definition at line 125 of file terminal-profile.c.
KEY_VISIBLE_NAME
#define KEY_VISIBLE_NAME "visible-name"
Definition at line 128 of file terminal-profile.c.
KEY_WORD_CHARS
#define KEY_WORD_CHARS "word-chars"
Definition at line 129 of file terminal-profile.c.
TERMINAL_PROFILE_PROPERTY
#define TERMINAL_PROFILE_PROPERTY (propId, propSpec, propGSettings)
Value:
{\
  GParamSpec *pspec = propSpec;\
  g_object_class_install_property (object_class, propId, pspec);\
  g_param_spec_set_qdata (pspec, gsettings_key_quark, (gpointer) propGSettings);\
  g_hash_table_insert (klass->gsettings_keys, (gpointer) propGSettings, pspec);\
}
TERMINAL_PROFILE_PROPERTY_BOOLEAN
#define TERMINAL_PROFILE_PROPERTY_BOOLEAN (prop, propDefault, propGSettings)
Value:
TERMINAL_PROFILE_PROPERTY (PROP_##prop,\
  g_param_spec_boolean (TERMINAL_PROFILE_##prop, NULL, NULL,\
                        propDefault,\
                        G_PARAM_READWRITE | TERMINAL_PROFILE_PSPEC_STATIC),\
  propGSettings)
TERMINAL_PROFILE_PROPERTY_BOXED
#define TERMINAL_PROFILE_PROPERTY_BOXED (prop, propType, propGSettings)
Value:
TERMINAL_PROFILE_PROPERTY (PROP_##prop,\
  g_param_spec_boxed (TERMINAL_PROFILE_##prop, NULL, NULL,\
                      propType,\
                      G_PARAM_READWRITE | TERMINAL_PROFILE_PSPEC_STATIC),\
  propGSettings)
TERMINAL_PROFILE_PROPERTY_DOUBLE
#define TERMINAL_PROFILE_PROPERTY_DOUBLE (prop, propMin, propMax, propDefault, propGSettings)
Value:
TERMINAL_PROFILE_PROPERTY (PROP_##prop,\
  g_param_spec_double (TERMINAL_PROFILE_##prop, NULL, NULL,\
                       propMin, propMax, propDefault,\
                       G_PARAM_READWRITE | TERMINAL_PROFILE_PSPEC_STATIC),\
  propGSettings)
TERMINAL_PROFILE_PROPERTY_ENUM
#define TERMINAL_PROFILE_PROPERTY_ENUM (prop, propType, propDefault, propGSettings)
Value:
TERMINAL_PROFILE_PROPERTY (PROP_##prop,\
  g_param_spec_enum (TERMINAL_PROFILE_##prop, NULL, NULL,\
                     propType, propDefault,\
                     G_PARAM_READWRITE | TERMINAL_PROFILE_PSPEC_STATIC),\
  propGSettings)
TERMINAL_PROFILE_PROPERTY_INT
#define TERMINAL_PROFILE_PROPERTY_INT (prop, propMin, propMax, propDefault, propGSettings)
Value:
TERMINAL_PROFILE_PROPERTY (PROP_##prop,\
  g_param_spec_int (TERMINAL_PROFILE_##prop, NULL, NULL,\
                    propMin, propMax, propDefault,\
                    G_PARAM_READWRITE | TERMINAL_PROFILE_PSPEC_STATIC),\
  propGSettings)
TERMINAL_PROFILE_PROPERTY_OBJECT
#define TERMINAL_PROFILE_PROPERTY_OBJECT (prop, propType)
Value:
TERMINAL_PROFILE_PROPERTY_OUTER (PROP_##prop,\
  g_param_spec_object (TERMINAL_PROFILE_##prop, NULL, NULL,\
                       propType,\
                       G_PARAM_READABLE | TERMINAL_PROFILE_PSPEC_STATIC))
TERMINAL_PROFILE_PROPERTY_OUTER
#define TERMINAL_PROFILE_PROPERTY_OUTER (propId, propSpec)
Value:
{\
  GParamSpec *pspec = propSpec;\
  g_object_class_install_property (object_class, propId, pspec);\
}
TERMINAL_PROFILE_PROPERTY_STRING
#define TERMINAL_PROFILE_PROPERTY_STRING (prop, propDefault, propGSettings)
Value:
TERMINAL_PROFILE_PROPERTY (PROP_##prop,\
  g_param_spec_string (TERMINAL_PROFILE_##prop, NULL, NULL,\
                       propDefault,\
                       G_PARAM_READWRITE | TERMINAL_PROFILE_PSPEC_STATIC),\
  propGSettings)
TERMINAL_PROFILE_PROPERTY_STRING_CO
#define TERMINAL_PROFILE_PROPERTY_STRING_CO (prop, propDefault)
Value:
TERMINAL_PROFILE_PROPERTY_OUTER (PROP_##prop,\
  g_param_spec_string (TERMINAL_PROFILE_##prop, NULL, NULL,\
                       propDefault,\
                       G_PARAM_READWRITE | G_PARAM_CONSTRUCT_ONLY | TERMINAL_PROFILE_PSPEC_STATIC))
TERMINAL_PROFILE_PROPERTY_VALUE_ARRAY_BOXED
#define TERMINAL_PROFILE_PROPERTY_VALUE_ARRAY_BOXED (prop, propElementName, propElementType, propGSettings)
Value:
TERMINAL_PROFILE_PROPERTY (PROP_##prop,\
  g_param_spec_value_array (TERMINAL_PROFILE_##prop, NULL, NULL,\
                            g_param_spec_boxed (propElementName, NULL, NULL,\
                                                propElementType, \
                                                G_PARAM_READWRITE | TERMINAL_PROFILE_PSPEC_STATIC),\
                            G_PARAM_READWRITE | TERMINAL_PROFILE_PSPEC_STATIC),\
  propGSettings)
TERMINAL_PROFILE_PSPEC_STATIC
#define TERMINAL_PROFILE_PSPEC_STATIC (G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FORGOTTEN
LAST_SIGNAL
Definition at line 292 of file terminal-profile.c.
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_ALLOW_BOLD
PROP_BACKGROUND_COLOR
PROP_BACKGROUND_DARKNESS
PROP_BACKGROUND_IMAGE
PROP_BACKGROUND_IMAGE_FILE
PROP_BACKGROUND_TYPE
PROP_BACKSPACE_BINDING
PROP_BOLD_COLOR
PROP_BOLD_COLOR_SAME_AS_FG
PROP_CURSOR_BLINK_MODE
PROP_CURSOR_SHAPE
PROP_CUSTOM_COMMAND
PROP_DEFAULT_SIZE_COLUMNS
PROP_DEFAULT_SIZE_ROWS
PROP_DEFAULT_SHOW_MENUBAR
PROP_DELETE_BINDING
PROP_EXIT_ACTION
PROP_FONT
PROP_FOREGROUND_COLOR
PROP_LOGIN_SHELL
PROP_NAME
PROP_PALETTE
PROP_SCROLL_BACKGROUND
PROP_SCROLLBACK_LINES
PROP_SCROLLBACK_UNLIMITED
PROP_SCROLLBAR_POSITION
PROP_SCROLL_ON_KEYSTROKE
PROP_SCROLL_ON_OUTPUT
PROP_SILENT_BELL
PROP_TITLE
PROP_TITLE_MODE
PROP_USE_CUSTOM_COMMAND
PROP_USE_CUSTOM_DEFAULT_SIZE
PROP_USE_SKEY
PROP_USE_URLS
PROP_USE_SYSTEM_FONT
PROP_USE_THEME_COLORS
PROP_VISIBLE_NAME
PROP_WORD_CHARS
PROP_COPY_SELECTION
LAST_PROP
Definition at line 46 of file terminal-profile.c.
Function Documentation
_terminal_profile_clone()
TerminalProfile * _terminal_profile_clone (TerminalProfile * base_profile, const char * visible_name)
Definition at line 1382 of file terminal-profile.c.
References G_OBJECT_CLASS(), I_, NULL, _TerminalProfile::priv, terminal_app_get(), terminal_app_get_profile_by_name(), TERMINAL_PROFILE_GET_CLASS, TERMINAL_PROFILE_NAME, TERMINAL_PROFILE_VISIBLE_NAME, and TERMINAL_TYPE_PROFILE.
_terminal_profile_forget()
void _terminal_profile_forget (TerminalProfile * profile)
Definition at line 1363 of file terminal-profile.c.
References FORGOTTEN, _TerminalProfile::priv, and TRUE.
_terminal_profile_get_forgotten()
gboolean _terminal_profile_get_forgotten (TerminalProfile * profile)
Definition at line 1376 of file terminal-profile.c.
References _TerminalProfile::priv.
_terminal_profile_new()
TerminalProfile * _terminal_profile_new (const char * name)
Definition at line 1355 of file terminal-profile.c.
References name, NULL, and TERMINAL_TYPE_PROFILE.
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (TerminalProfile , terminal_profile , G_TYPE_OBJECT)
References b.
terminal_profile_get_palette()
gboolean terminal_profile_get_palette (TerminalProfile * profile, GdkRGBA * colors, guint * n_colors)
Definition at line 1600 of file terminal-profile.c.
References FALSE, MIN, NULL, _TerminalProfile::priv, PROP_PALETTE, TERMINAL_IS_PROFILE, and TRUE.
Referenced by terminal_profile_get_palette_is_builtin().
terminal_profile_get_palette_is_builtin()
gboolean terminal_profile_get_palette_is_builtin (TerminalProfile * profile, guint * n)
Definition at line 1631 of file terminal-profile.c.
References FALSE, TERMINAL_PALETTE_N_BUILTINS, TERMINAL_PALETTE_SIZE, terminal_profile_get_palette(), and TRUE.
terminal_profile_get_property_boolean()
gboolean terminal_profile_get_property_boolean (TerminalProfile * profile, const char * prop_name)
Definition at line 1472 of file terminal-profile.c.
References FALSE, and NULL.
Referenced by terminal_screen_new(), terminal_screen_set_font(), and terminal_window_update_copy_selection().
terminal_profile_get_property_boxed()
gconstpointer terminal_profile_get_property_boxed (TerminalProfile * profile, const char * prop_name)
Definition at line 1486 of file terminal-profile.c.
References NULL.
terminal_profile_get_property_double()
double terminal_profile_get_property_double (TerminalProfile * profile, const char * prop_name)
Definition at line 1500 of file terminal-profile.c.
References NULL.
terminal_profile_get_property_enum()
int terminal_profile_get_property_enum (TerminalProfile * profile, const char * prop_name)
Definition at line 1514 of file terminal-profile.c.
References NULL.
Referenced by _terminal_screen_update_scrollbar().
terminal_profile_get_property_int()
int terminal_profile_get_property_int (TerminalProfile * profile, const char * prop_name)
Definition at line 1528 of file terminal-profile.c.
References NULL.
Referenced by terminal_screen_new().
terminal_profile_get_property_object()
gpointer terminal_profile_get_property_object (TerminalProfile * profile, const char * prop_name)
Definition at line 1542 of file terminal-profile.c.
References NULL.
terminal_profile_get_property_string()
const char * terminal_profile_get_property_string (TerminalProfile * profile, const char * prop_name)
Definition at line 1556 of file terminal-profile.c.
References NULL.
Referenced by terminal_screen_save_config().
terminal_profile_modify_palette_entry()
gboolean terminal_profile_modify_palette_entry (TerminalProfile * profile, guint i, const GdkRGBA * color)
Definition at line 1668 of file terminal-profile.c.
References FALSE, _TerminalProfile::priv, PROP_PALETTE, TERMINAL_PROFILE_PALETTE, and TRUE.
terminal_profile_property_locked()
gboolean terminal_profile_property_locked (TerminalProfile * profile, const char * prop_name)
Definition at line 1570 of file terminal-profile.c.
References FALSE, NULL, and _TerminalProfile::priv.
terminal_profile_reset_property()
void terminal_profile_reset_property (TerminalProfile * profile, const char * prop_name)
Definition at line 1585 of file terminal-profile.c.
References NULL, and TRUE.
terminal_profile_set_palette_builtin()
void terminal_profile_set_palette_builtin (TerminalProfile * profile, guint n)
Definition at line 1654 of file terminal-profile.c.
References TERMINAL_PALETTE_N_BUILTINS, TERMINAL_PALETTE_SIZE, and TERMINAL_PROFILE_PALETTE.