MATE Desktop Environment: terminal-window.h File Reference
terminal-window.h File Reference
#include <gtk/gtk.h>
#include "terminal-screen.h"
Classes
struct _TerminalWindow
struct _TerminalWindowClass
Macros
#define TERMINAL_TYPE_WINDOW (terminal_window_get_type ())
#define TERMINAL_WINDOW(object)
#define TERMINAL_WINDOW_CLASS(klass)
#define TERMINAL_IS_WINDOW(object)
#define TERMINAL_IS_WINDOW_CLASS(klass)
#define TERMINAL_WINDOW_GET_CLASS(obj)
Typedefs
typedef struct _TerminalWindowClass TerminalWindowClass
typedef struct _TerminalWindowPrivate TerminalWindowPrivate
Functions
GType terminal_window_get_type (void)
TerminalWindow * terminal_window_new (void)
void terminal_window_set_is_restored (TerminalWindow *window)
GtkUIManager * terminal_window_get_ui_manager (TerminalWindow *window)
void terminal_window_add_screen (TerminalWindow *window, TerminalScreen *screen, int position)
void terminal_window_remove_screen (TerminalWindow *window, TerminalScreen *screen)
void terminal_window_move_screen (TerminalWindow *source_window, TerminalWindow *dest_window, TerminalScreen *screen, int dest_position)
void terminal_window_set_menubar_visible (TerminalWindow *window, gboolean setting)
gboolean terminal_window_get_menubar_visible (TerminalWindow *window)
void terminal_window_set_icon (TerminalWindow *window, const char *icon)
void terminal_window_switch_screen (TerminalWindow *window, TerminalScreen *screen)
TerminalScreen * terminal_window_get_active (TerminalWindow *window)
GList * terminal_window_list_screen_containers (TerminalWindow *window)
void terminal_window_update_geometry (TerminalWindow *window)
void terminal_window_update_size (TerminalWindow *window, TerminalScreen *screen, gboolean even_if_mapped)
gboolean terminal_window_update_size_set_geometry (TerminalWindow *window, TerminalScreen *screen, gboolean even_if_mapped, gchar *geometry_string)
GtkWidget * terminal_window_get_notebook (TerminalWindow *window)
void terminal_window_save_state (TerminalWindow *window, GKeyFile *key_file, const char *group)
void terminal_window_update_copy_selection (TerminalScreen *screen, TerminalWindow *window)
TerminalWindow * terminal_window_get_latest_focused (TerminalWindow *window1, TerminalWindow *window2)
void terminal_window_show_find_dialog (TerminalWindow *window)
void terminal_window_show_set_title_dialog (TerminalWindow *window)
void terminal_window_detach_screen (TerminalWindow *window, TerminalScreen *screen)
void terminal_window_show_about_dialog (GtkWindow *parent)
Macro Definition Documentation
TERMINAL_IS_WINDOW
#define TERMINAL_IS_WINDOW (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((object), TERMINAL_TYPE_WINDOW))
Definition at line 33 of file terminal-window.h.
Referenced by terminal_app_get_current_window(), terminal_app_new_terminal(), terminal_app_save_config(), terminal_window_add_screen(), terminal_window_detach_screen(), terminal_window_get_notebook(), terminal_window_move_screen(), terminal_window_set_is_restored(), terminal_window_show_about_dialog(), terminal_window_show_find_dialog(), and terminal_window_show_set_title_dialog().
TERMINAL_IS_WINDOW_CLASS
#define TERMINAL_IS_WINDOW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), TERMINAL_TYPE_WINDOW))
Definition at line 34 of file terminal-window.h.
TERMINAL_TYPE_WINDOW
#define TERMINAL_TYPE_WINDOW (terminal_window_get_type ())
Definition at line 30 of file terminal-window.h.
Referenced by terminal_window_new().
TERMINAL_WINDOW
#define TERMINAL_WINDOW (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((object), TERMINAL_TYPE_WINDOW, TerminalWindow))
Definition at line 31 of file terminal-window.h.
Referenced by terminal_app_get_current_window(), terminal_app_save_config(), terminal_window_add_screen(), and terminal_window_show_about_dialog().
TERMINAL_WINDOW_CLASS
#define TERMINAL_WINDOW_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), TERMINAL_TYPE_WINDOW, TerminalWindowClass))
Definition at line 32 of file terminal-window.h.
TERMINAL_WINDOW_GET_CLASS
#define TERMINAL_WINDOW_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), TERMINAL_TYPE_WINDOW, TerminalWindowClass))
Definition at line 35 of file terminal-window.h.
Typedef Documentation
TerminalWindowClass
typedef struct _TerminalWindowClass TerminalWindowClass
Definition at line 37 of file terminal-window.h.
TerminalWindowPrivate
typedef struct _TerminalWindowPrivate TerminalWindowPrivate
Definition at line 38 of file terminal-window.h.
Function Documentation
terminal_window_add_screen()
void terminal_window_add_screen (TerminalWindow * window, TerminalScreen * screen, int position)
Definition at line 2689 of file terminal-window.c.
References NULL, TERMINAL_IS_WINDOW, terminal_screen_container_new(), terminal_tab_label_new(), TERMINAL_WINDOW, terminal_window_remove_screen(), and TRUE.
Referenced by terminal_app_new_terminal(), and terminal_window_move_screen().
terminal_window_detach_screen()
void terminal_window_detach_screen (TerminalWindow * window, TerminalScreen * screen)
Definition at line 4649 of file terminal-window.c.
References NULL, TERMINAL_IS_SCREEN, and TERMINAL_IS_WINDOW.
terminal_window_get_active()
TerminalScreen * terminal_window_get_active (TerminalWindow * window)
Definition at line 3032 of file terminal-window.c.
Referenced by terminal_app_handle_options(), and terminal_window_save_state().
terminal_window_get_latest_focused()
TerminalWindow * terminal_window_get_latest_focused (TerminalWindow * window1, TerminalWindow * window2)
Definition at line 4744 of file terminal-window.c.
References NULL, and _TerminalWindow::priv.
Referenced by terminal_app_get_current_window().
terminal_window_get_menubar_visible()
gboolean terminal_window_get_menubar_visible (TerminalWindow * window)
Definition at line 2841 of file terminal-window.c.
terminal_window_get_notebook()
GtkWidget * terminal_window_get_notebook (TerminalWindow * window)
Definition at line 2877 of file terminal-window.c.
References NULL, and TERMINAL_IS_WINDOW.
terminal_window_get_type()
GType terminal_window_get_type (void)
terminal_window_get_ui_manager()
GtkUIManager * terminal_window_get_ui_manager (TerminalWindow * window)
Definition at line 4625 of file terminal-window.c.
terminal_window_list_screen_containers()
GList * terminal_window_list_screen_containers (TerminalWindow * window)
Definition at line 2797 of file terminal-window.c.
Referenced by terminal_window_save_state().
terminal_window_move_screen()
void terminal_window_move_screen (TerminalWindow * source_window, TerminalWindow * dest_window, TerminalScreen * screen, int dest_position)
Definition at line 2761 of file terminal-window.c.
References _TerminalWindow::priv, TERMINAL_IS_SCREEN, TERMINAL_IS_SCREEN_CONTAINER, TERMINAL_IS_WINDOW, terminal_screen_container_get_from_screen(), terminal_window_add_screen(), and TRUE.
terminal_window_new()
TerminalWindow * terminal_window_new (void)
Definition at line 2555 of file terminal-window.c.
References NULL, and TERMINAL_TYPE_WINDOW.
Referenced by terminal_app_new_window().
terminal_window_remove_screen()
void terminal_window_remove_screen (TerminalWindow * window, TerminalScreen * screen)
Definition at line 2754 of file terminal-window.c.
References FALSE.
Referenced by terminal_window_add_screen().
terminal_window_save_state()
void terminal_window_save_state (TerminalWindow * window, GKeyFile * key_file, const char * group)
Definition at line 4672 of file terminal-window.c.
References FALSE, NULL, TERMINAL_CONFIG_WINDOW_PROP_ACTIVE_TAB, TERMINAL_CONFIG_WINDOW_PROP_FULLSCREEN, TERMINAL_CONFIG_WINDOW_PROP_GEOMETRY, TERMINAL_CONFIG_WINDOW_PROP_ICON, TERMINAL_CONFIG_WINDOW_PROP_MAXIMIZED, TERMINAL_CONFIG_WINDOW_PROP_MENUBAR_VISIBLE, TERMINAL_CONFIG_WINDOW_PROP_ROLE, TERMINAL_CONFIG_WINDOW_PROP_TABS, TERMINAL_SCREEN_CONTAINER, terminal_screen_container_get_screen(), terminal_screen_get_size(), terminal_screen_save_config(), terminal_window_get_active(), terminal_window_list_screen_containers(), and TRUE.
Referenced by terminal_app_save_config().
terminal_window_set_icon()
void terminal_window_set_icon (TerminalWindow * window, const char * icon)
Definition at line 2849 of file terminal-window.c.
References _, error, and NULL.
Referenced by terminal_app_handle_options().
terminal_window_set_is_restored()
void terminal_window_set_is_restored (TerminalWindow * window)
terminal_window_set_is_restored: @window:
Marks the window as restored from session.
Definition at line 2567 of file terminal-window.c.
References TERMINAL_IS_WINDOW, and TRUE.
Referenced by terminal_app_handle_options().
terminal_window_set_menubar_visible()
void terminal_window_set_menubar_visible (TerminalWindow * window, gboolean setting)
Definition at line 2806 of file terminal-window.c.
References action, FALSE, G_GNUC_BEGIN_IGNORE_DEPRECATIONS, G_GNUC_END_IGNORE_DEPRECATIONS, NULL, TERMINAL_DEBUG_GEOMETRY, terminal_window_update_size(), and TRUE.
Referenced by terminal_app_handle_options().
terminal_window_show_about_dialog()
void terminal_window_show_about_dialog (GtkWindow * parent)
Definition at line 4657 of file terminal-window.c.
References NULL, TERMINAL_IS_WINDOW, and TERMINAL_WINDOW.
terminal_window_show_find_dialog()
void terminal_window_show_find_dialog (TerminalWindow * window)
Definition at line 4635 of file terminal-window.c.
References NULL, and TERMINAL_IS_WINDOW.
terminal_window_show_set_title_dialog()
void terminal_window_show_set_title_dialog (TerminalWindow * window)
Definition at line 4642 of file terminal-window.c.
References NULL, and TERMINAL_IS_WINDOW.
terminal_window_switch_screen()
void terminal_window_switch_screen (TerminalWindow * window, TerminalScreen * screen)
Definition at line 3017 of file terminal-window.c.
References TERMINAL_IS_SCREEN_CONTAINER, and terminal_screen_container_get_from_screen().
Referenced by terminal_app_handle_options(), and terminal_app_new_terminal().
terminal_window_update_copy_selection()
void terminal_window_update_copy_selection (TerminalScreen * screen, TerminalWindow * window)
Definition at line 3426 of file terminal-window.c.
References TERMINAL_PROFILE_COPY_SELECTION, terminal_profile_get_property_boolean(), and terminal_screen_get_profile().
terminal_window_update_geometry()
void terminal_window_update_geometry (TerminalWindow * window)
Definition at line 3498 of file terminal-window.c.
References FALSE, GDK_IS_X11_DISPLAY, MIN_HEIGHT_CHARS, MIN_WIDTH_CHARS, NULL, TERMINAL_DEBUG_GEOMETRY, terminal_screen_get_cell_size(), terminal_screen_get_size(), and TRUE.
Referenced by terminal_window_update_size_set_geometry().
terminal_window_update_size()
void terminal_window_update_size (TerminalWindow * window, TerminalScreen * screen, gboolean even_if_mapped)
Definition at line 2887 of file terminal-window.c.
References NULL, and terminal_window_update_size_set_geometry().
Referenced by terminal_window_set_menubar_visible().
terminal_window_update_size_set_geometry()
gboolean terminal_window_update_size_set_geometry (TerminalWindow * window, TerminalScreen * screen, gboolean even_if_mapped, gchar * geometry_string)
Definition at line 2896 of file terminal-window.c.
References FALSE, HeightValue, NoValue, NULL, TERMINAL_DEBUG_GEOMETRY, terminal_screen_get_size(), terminal_window_update_geometry(), TRUE, WidthValue, XNegative, XValue, YNegative, and YValue.
Referenced by terminal_app_handle_options(), and terminal_window_update_size().