MATE Desktop Environment: terminal-app.h File Reference
terminal-app.h File Reference
#include <gtk/gtk.h>
#include "terminal-encoding.h"
#include "terminal-screen.h"
#include "terminal-options.h"
Macros
#define TERMINAL_CONFIG_VERSION (1) /* Bump this for any changes */
#define TERMINAL_CONFIG_COMPAT_VERSION (1) /* Bump this for incompatible changes */
#define TERMINAL_CONFIG_GROUP "MATE Terminal Configuration"
#define TERMINAL_CONFIG_PROP_VERSION "Version"
#define TERMINAL_CONFIG_PROP_COMPAT_VERSION "CompatVersion"
#define TERMINAL_CONFIG_PROP_WINDOWS "Windows"
#define TERMINAL_CONFIG_WINDOW_PROP_ACTIVE_TAB "ActiveTerminal"
#define TERMINAL_CONFIG_WINDOW_PROP_FULLSCREEN "Fullscreen"
#define TERMINAL_CONFIG_WINDOW_PROP_GEOMETRY "Geometry"
#define TERMINAL_CONFIG_WINDOW_PROP_ICON "Icon"
#define TERMINAL_CONFIG_WINDOW_PROP_MAXIMIZED "Maximized"
#define TERMINAL_CONFIG_WINDOW_PROP_MENUBAR_VISIBLE "MenubarVisible"
#define TERMINAL_CONFIG_WINDOW_PROP_ROLE "Role"
#define TERMINAL_CONFIG_WINDOW_PROP_TABS "Terminals"
#define TERMINAL_CONFIG_TERMINAL_PROP_HEIGHT "Height"
#define TERMINAL_CONFIG_TERMINAL_PROP_COMMAND "Command"
#define TERMINAL_CONFIG_TERMINAL_PROP_PROFILE_ID "ProfileID"
#define TERMINAL_CONFIG_TERMINAL_PROP_TITLE "Title"
#define TERMINAL_CONFIG_TERMINAL_PROP_WIDTH "Width"
#define TERMINAL_CONFIG_TERMINAL_PROP_WORKING_DIRECTORY "WorkingDirectory"
#define TERMINAL_CONFIG_TERMINAL_PROP_ZOOM "Zoom"
#define CONF_PREFIX "org.mate.terminal"
#define CONF_GLOBAL_SCHEMA CONF_PREFIX ".global"
#define CONF_PROFILES_SCHEMA CONF_PREFIX ".profiles"
#define CONF_PROFILE_SCHEMA CONF_PREFIX ".profile"
#define CONF_KEYS_SCHEMA CONF_PREFIX ".keybindings"
#define CONF_PROFILE_PREFIX "/org/mate/terminal/profiles/"
#define MATE_TERMINAL_ICON_NAME "utilities-terminal"
#define TERMINAL_APP_DEFAULT_PROFILE "default-profile"
#define TERMINAL_APP_ENABLE_MENU_BAR_ACCEL "enable-menu-accels"
#define TERMINAL_APP_ENABLE_MNEMONICS "enable-mnemonics"
#define TERMINAL_APP_SYSTEM_FONT "system-font"
#define TERMINAL_APPLICATION_ID "org.mate.Terminal"
#define TERMINAL_TYPE_APP (terminal_app_get_type ())
#define TERMINAL_APP(object)
#define TERMINAL_APP_CLASS(klass)
#define TERMINAL_IS_APP(object)
#define TERMINAL_IS_APP_CLASS(klass)
#define TERMINAL_APP_GET_CLASS(obj)
Typedefs
typedef struct _TerminalAppClass TerminalAppClass
typedef struct _TerminalApp TerminalApp
typedef struct _TerminalAppPrivate TerminalAppPrivate
Functions
GType terminal_app_get_type (void)
TerminalApp * terminal_app_get (void)
GSettings * terminal_app_get_global_settings (TerminalApp *app)
gboolean terminal_app_handle_options (TerminalApp *app, TerminalOptions *options, gboolean allow_resume, GError **error)
void terminal_app_edit_profile (TerminalApp *app, TerminalProfile *profile, GtkWindow *transient_parent, const char *widget_name)
void terminal_app_new_profile (TerminalApp *app, TerminalProfile *default_base_profile, GtkWindow *transient_parent)
TerminalWindow * terminal_app_new_window (TerminalApp *app, GdkScreen *screen)
TerminalScreen * terminal_app_new_terminal (TerminalApp *app, TerminalWindow *window, TerminalProfile *profile, char **override_command, const char *title, const char *working_dir, char **child_env, double zoom)
TerminalWindow * terminal_app_get_current_window (TerminalApp *app, GdkScreen *screen, int curr_workspace)
void terminal_app_manage_profiles (TerminalApp *app, GtkWindow *transient_parent)
void terminal_app_edit_keybindings (TerminalApp *app, GtkWindow *transient_parent)
void terminal_app_edit_encodings (TerminalApp *app, GtkWindow *transient_parent)
GList * terminal_app_get_profile_list (TerminalApp *app)
TerminalProfile * terminal_app_ensure_profile_fallback (TerminalApp *app)
TerminalProfile * terminal_app_get_profile_by_name (TerminalApp *app, const char *name)
TerminalProfile * terminal_app_get_profile_by_visible_name (TerminalApp *app, const char *name)
TerminalProfile * terminal_app_get_default_profile (TerminalApp *app)
TerminalProfile * terminal_app_get_profile_for_new_term (TerminalApp *app)
TerminalEncoding * terminal_app_ensure_encoding (TerminalApp *app, const char *charset)
GHashTable * terminal_app_get_encodings (TerminalApp *app)
GSList * terminal_app_get_active_encodings (TerminalApp *app)
void terminal_app_save_config (TerminalApp *app, GKeyFile *key_file)
gboolean terminal_app_save_config_file (TerminalApp *app, const char *file_name, GError **error)
Macro Definition Documentation
CONF_GLOBAL_SCHEMA
#define CONF_GLOBAL_SCHEMA CONF_PREFIX ".global"
Definition at line 63 of file terminal-app.h.
CONF_KEYS_SCHEMA
#define CONF_KEYS_SCHEMA CONF_PREFIX ".keybindings"
Definition at line 66 of file terminal-app.h.
Referenced by terminal_accels_init().
CONF_PREFIX
#define CONF_PREFIX "org.mate.terminal"
Definition at line 62 of file terminal-app.h.
CONF_PROFILE_PREFIX
#define CONF_PROFILE_PREFIX "/org/mate/terminal/profiles/"
Definition at line 67 of file terminal-app.h.
CONF_PROFILE_SCHEMA
#define CONF_PROFILE_SCHEMA CONF_PREFIX ".profile"
Definition at line 65 of file terminal-app.h.
CONF_PROFILES_SCHEMA
#define CONF_PROFILES_SCHEMA CONF_PREFIX ".profiles"
Definition at line 64 of file terminal-app.h.
MATE_TERMINAL_ICON_NAME
#define MATE_TERMINAL_ICON_NAME "utilities-terminal"
Definition at line 69 of file terminal-app.h.
TERMINAL_APP
#define TERMINAL_APP (object)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((object), TERMINAL_TYPE_APP, TerminalApp))
Definition at line 82 of file terminal-app.h.
Referenced by terminal_app_get().
TERMINAL_APP_CLASS
#define TERMINAL_APP_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_CAST ((klass), TERMINAL_TYPE_APP, TerminalAppClass))
Definition at line 83 of file terminal-app.h.
TERMINAL_APP_DEFAULT_PROFILE
#define TERMINAL_APP_DEFAULT_PROFILE "default-profile"
Definition at line 71 of file terminal-app.h.
TERMINAL_APP_ENABLE_MENU_BAR_ACCEL
#define TERMINAL_APP_ENABLE_MENU_BAR_ACCEL "enable-menu-accels"
Definition at line 72 of file terminal-app.h.
Referenced by terminal_edit_keys_dialog_show().
TERMINAL_APP_ENABLE_MNEMONICS
#define TERMINAL_APP_ENABLE_MNEMONICS "enable-mnemonics"
Definition at line 73 of file terminal-app.h.
Referenced by terminal_edit_keys_dialog_show().
TERMINAL_APP_GET_CLASS
#define TERMINAL_APP_GET_CLASS (obj)
Value:
(G_TYPE_INSTANCE_GET_CLASS ((obj), TERMINAL_TYPE_APP, TerminalAppClass))
Definition at line 86 of file terminal-app.h.
TERMINAL_APP_SYSTEM_FONT
#define TERMINAL_APP_SYSTEM_FONT "system-font"
Definition at line 74 of file terminal-app.h.
TERMINAL_APPLICATION_ID
#define TERMINAL_APPLICATION_ID "org.mate.Terminal"
Definition at line 77 of file terminal-app.h.
Referenced by main().
TERMINAL_CONFIG_COMPAT_VERSION
#define TERMINAL_CONFIG_COMPAT_VERSION (1) /* Bump this for incompatible changes */
Definition at line 36 of file terminal-app.h.
Referenced by terminal_app_save_config(), and terminal_options_merge_config().
TERMINAL_CONFIG_GROUP
#define TERMINAL_CONFIG_GROUP "MATE Terminal Configuration"
Definition at line 38 of file terminal-app.h.
Referenced by terminal_app_save_config(), and terminal_options_merge_config().
TERMINAL_CONFIG_PROP_COMPAT_VERSION
#define TERMINAL_CONFIG_PROP_COMPAT_VERSION "CompatVersion"
Definition at line 40 of file terminal-app.h.
Referenced by terminal_app_save_config(), and terminal_options_merge_config().
TERMINAL_CONFIG_PROP_VERSION
#define TERMINAL_CONFIG_PROP_VERSION "Version"
Definition at line 39 of file terminal-app.h.
Referenced by terminal_app_save_config(), and terminal_options_merge_config().
TERMINAL_CONFIG_PROP_WINDOWS
#define TERMINAL_CONFIG_PROP_WINDOWS "Windows"
Definition at line 41 of file terminal-app.h.
Referenced by terminal_app_save_config(), and terminal_options_merge_config().
TERMINAL_CONFIG_TERMINAL_PROP_COMMAND
#define TERMINAL_CONFIG_TERMINAL_PROP_COMMAND "Command"
Definition at line 53 of file terminal-app.h.
Referenced by terminal_options_merge_config(), and terminal_screen_save_config().
TERMINAL_CONFIG_TERMINAL_PROP_HEIGHT
#define TERMINAL_CONFIG_TERMINAL_PROP_HEIGHT "Height"
Definition at line 52 of file terminal-app.h.
Referenced by terminal_screen_save_config().
TERMINAL_CONFIG_TERMINAL_PROP_PROFILE_ID
#define TERMINAL_CONFIG_TERMINAL_PROP_PROFILE_ID "ProfileID"
Definition at line 54 of file terminal-app.h.
Referenced by terminal_options_merge_config(), and terminal_screen_save_config().
TERMINAL_CONFIG_TERMINAL_PROP_TITLE
#define TERMINAL_CONFIG_TERMINAL_PROP_TITLE "Title"
Definition at line 55 of file terminal-app.h.
Referenced by terminal_options_merge_config(), and terminal_screen_save_config().
TERMINAL_CONFIG_TERMINAL_PROP_WIDTH
#define TERMINAL_CONFIG_TERMINAL_PROP_WIDTH "Width"
Definition at line 56 of file terminal-app.h.
Referenced by terminal_screen_save_config().
TERMINAL_CONFIG_TERMINAL_PROP_WORKING_DIRECTORY
#define TERMINAL_CONFIG_TERMINAL_PROP_WORKING_DIRECTORY "WorkingDirectory"
Definition at line 57 of file terminal-app.h.
Referenced by terminal_options_merge_config(), and terminal_screen_save_config().
TERMINAL_CONFIG_TERMINAL_PROP_ZOOM
#define TERMINAL_CONFIG_TERMINAL_PROP_ZOOM "Zoom"
Definition at line 58 of file terminal-app.h.
Referenced by terminal_screen_save_config().
TERMINAL_CONFIG_VERSION
#define TERMINAL_CONFIG_VERSION (1) /* Bump this for any changes */
Definition at line 35 of file terminal-app.h.
Referenced by terminal_app_save_config().
TERMINAL_CONFIG_WINDOW_PROP_ACTIVE_TAB
#define TERMINAL_CONFIG_WINDOW_PROP_ACTIVE_TAB "ActiveTerminal"
Definition at line 43 of file terminal-app.h.
Referenced by terminal_window_save_state().
TERMINAL_CONFIG_WINDOW_PROP_FULLSCREEN
#define TERMINAL_CONFIG_WINDOW_PROP_FULLSCREEN "Fullscreen"
Definition at line 44 of file terminal-app.h.
Referenced by terminal_options_merge_config(), and terminal_window_save_state().
TERMINAL_CONFIG_WINDOW_PROP_GEOMETRY
#define TERMINAL_CONFIG_WINDOW_PROP_GEOMETRY "Geometry"
Definition at line 45 of file terminal-app.h.
Referenced by terminal_options_merge_config(), and terminal_window_save_state().
TERMINAL_CONFIG_WINDOW_PROP_ICON
#define TERMINAL_CONFIG_WINDOW_PROP_ICON "Icon"
Definition at line 46 of file terminal-app.h.
Referenced by terminal_options_merge_config(), and terminal_window_save_state().
TERMINAL_CONFIG_WINDOW_PROP_MAXIMIZED
#define TERMINAL_CONFIG_WINDOW_PROP_MAXIMIZED "Maximized"
Definition at line 47 of file terminal-app.h.
Referenced by terminal_options_merge_config(), and terminal_window_save_state().
TERMINAL_CONFIG_WINDOW_PROP_MENUBAR_VISIBLE
#define TERMINAL_CONFIG_WINDOW_PROP_MENUBAR_VISIBLE "MenubarVisible"
Definition at line 48 of file terminal-app.h.
Referenced by terminal_options_merge_config(), and terminal_window_save_state().
TERMINAL_CONFIG_WINDOW_PROP_ROLE
#define TERMINAL_CONFIG_WINDOW_PROP_ROLE "Role"
Definition at line 49 of file terminal-app.h.
Referenced by terminal_options_merge_config(), and terminal_window_save_state().
TERMINAL_CONFIG_WINDOW_PROP_TABS
#define TERMINAL_CONFIG_WINDOW_PROP_TABS "Terminals"
Definition at line 50 of file terminal-app.h.
Referenced by terminal_options_merge_config(), and terminal_window_save_state().
TERMINAL_IS_APP
#define TERMINAL_IS_APP (object)
Value:
(G_TYPE_CHECK_INSTANCE_TYPE ((object), TERMINAL_TYPE_APP))
Definition at line 84 of file terminal-app.h.
Referenced by terminal_app_get(), terminal_app_get_default_profile(), terminal_app_get_global_settings(), terminal_app_get_profile_by_name(), terminal_app_get_profile_by_visible_name(), terminal_app_get_profile_for_new_term(), terminal_app_get_profile_list(), and terminal_app_new_terminal().
TERMINAL_IS_APP_CLASS
#define TERMINAL_IS_APP_CLASS (klass)
Value:
(G_TYPE_CHECK_CLASS_TYPE ((klass), TERMINAL_TYPE_APP))
Definition at line 85 of file terminal-app.h.
TERMINAL_TYPE_APP
#define TERMINAL_TYPE_APP (terminal_app_get_type ())
Definition at line 81 of file terminal-app.h.
Referenced by main().
Typedef Documentation
TerminalApp
typedef struct _TerminalApp TerminalApp
Definition at line 89 of file terminal-app.h.
TerminalAppClass
typedef struct _TerminalAppClass TerminalAppClass
Definition at line 88 of file terminal-app.h.
TerminalAppPrivate
typedef struct _TerminalAppPrivate TerminalAppPrivate
Definition at line 90 of file terminal-app.h.
Function Documentation
terminal_app_edit_encodings()
void terminal_app_edit_encodings (TerminalApp * app, GtkWindow * transient_parent)
Definition at line 2029 of file terminal-app.c.
References terminal_encoding_dialog_show().
terminal_app_edit_keybindings()
void terminal_app_edit_keybindings (TerminalApp * app, GtkWindow * transient_parent)
Definition at line 2022 of file terminal-app.c.
References terminal_edit_keys_dialog_show().
terminal_app_edit_profile()
void terminal_app_edit_profile (TerminalApp * app, TerminalProfile * profile, GtkWindow * transient_parent, const char * widget_name)
Definition at line 2013 of file terminal-app.c.
References terminal_profile_edit().
terminal_app_ensure_encoding()
TerminalEncoding * terminal_app_ensure_encoding (TerminalApp * app, const char * charset)
terminal_app_ensure_encoding: @app: @charset:
Ensures there's a TerminalEncoding for @charset available.
Definition at line 2169 of file terminal-app.c.
References _, charset, NULL, terminal_encoding_get_id(), terminal_encoding_new(), and TRUE.
terminal_app_ensure_profile_fallback()
TerminalProfile * terminal_app_ensure_profile_fallback (TerminalApp * app)
References charset, error, and name.
terminal_app_get()
TerminalApp * terminal_app_get (void)
Definition at line 1774 of file terminal-app.c.
References NULL, TERMINAL_APP, and TERMINAL_IS_APP.
Referenced by _terminal_profile_clone(), terminal_edit_keys_dialog_show(), terminal_encoding_dialog_show(), and terminal_screen_set_font().
terminal_app_get_active_encodings()
GSList * terminal_app_get_active_encodings (TerminalApp * app)
terminal_app_get_active_encodings:
Returns: a newly allocated list of newly referenced TerminalEncoding objects.
Definition at line 2195 of file terminal-app.c.
References TerminalEncoding::is_active, key, NULL, and terminal_encoding_ref().
terminal_app_get_current_window()
TerminalWindow * terminal_app_get_current_window (TerminalApp * app, GdkScreen * screen, int curr_workspace)
Definition at line 2040 of file terminal-app.c.
References NULL, TERMINAL_IS_WINDOW, TERMINAL_WINDOW, and terminal_window_get_latest_focused().
Referenced by terminal_app_handle_options().
terminal_app_get_default_profile()
TerminalProfile * terminal_app_get_default_profile (TerminalApp * app)
Definition at line 2129 of file terminal-app.c.
References NULL, and TERMINAL_IS_APP.
terminal_app_get_encodings()
GHashTable * terminal_app_get_encodings (TerminalApp * app)
Definition at line 2156 of file terminal-app.c.
terminal_app_get_global_settings()
GSettings * terminal_app_get_global_settings (TerminalApp * app)
Definition at line 1786 of file terminal-app.c.
References NULL, and TERMINAL_IS_APP.
terminal_app_get_profile_by_name()
TerminalProfile * terminal_app_get_profile_by_name (TerminalApp * app, const char * name)
Definition at line 2101 of file terminal-app.c.
References name, NULL, and TERMINAL_IS_APP.
Referenced by _terminal_profile_clone(), and terminal_app_handle_options().
terminal_app_get_profile_by_visible_name()
TerminalProfile * terminal_app_get_profile_by_visible_name (TerminalApp * app, const char * name)
Definition at line 2111 of file terminal-app.c.
References name, NULL, and TERMINAL_IS_APP.
Referenced by terminal_app_handle_options().
terminal_app_get_profile_for_new_term()
TerminalProfile * terminal_app_get_profile_for_new_term (TerminalApp * app)
Definition at line 2137 of file terminal-app.c.
References NULL, and TERMINAL_IS_APP.
Referenced by terminal_app_handle_options().
terminal_app_get_profile_list()
GList * terminal_app_get_profile_list (TerminalApp * app)
terminal_profile_get_list:
Returns: a #GList containing all TerminalProfile objects. The content of the list is owned by the backend and should not be modified or freed. Use g_list_free() when done using the list.
Definition at line 2093 of file terminal-app.c.
References NULL, and TERMINAL_IS_APP.
terminal_app_get_type()
GType terminal_app_get_type (void)
References error.
terminal_app_handle_options()
gboolean terminal_app_handle_options (TerminalApp * app, TerminalOptions * options, gboolean allow_resume, GError ** error)
terminal_app_handle_options: @app: @options: a TerminalOptions @allow_resume: whether to merge the terminal configuration from the saved session on resume @error: a #GError to fill in
Processes @options. It loads or saves the terminal configuration, or opens the specified windows and tabs.
Returns: TRUE if @options could be successfully handled, or FALSE on error
Definition at line 1808 of file terminal-app.c.
References _, InitialTab::active, egg_sm_client_get(), egg_sm_client_get_state_file(), egg_sm_client_is_resumed(), error, InitialTab::exec_argv, FALSE, InitialWindow::force_menubar_state, InitialWindow::geometry, InitialWindow::icon, InitialWindow::menubar_state, NULL, InitialTab::profile, InitialTab::profile_is_id, InitialWindow::role, SOURCE_DEFAULT, SOURCE_SESSION, InitialWindow::source_tag, InitialWindow::start_fullscreen, InitialWindow::start_maximized, InitialWindow::tabs, terminal_app_get_current_window(), terminal_app_get_profile_by_name(), terminal_app_get_profile_by_visible_name(), terminal_app_get_profile_for_new_term(), terminal_app_new_terminal(), terminal_app_new_window(), terminal_app_save_config_file(), TERMINAL_DEBUG_FACTORY, TERMINAL_DEBUG_GEOMETRY, TERMINAL_OPTION_ERROR, TERMINAL_OPTION_ERROR_NOT_IN_FACTORY, terminal_options_ensure_window(), terminal_options_merge_config(), terminal_window_get_active(), terminal_window_set_icon(), terminal_window_set_is_restored(), terminal_window_set_menubar_visible(), terminal_window_switch_screen(), terminal_window_update_size_set_geometry(), InitialTab::title, TRUE, InitialTab::working_dir, InitialTab::zoom, and InitialTab::zoom_set.
terminal_app_manage_profiles()
void terminal_app_manage_profiles (TerminalApp * app, GtkWindow * transient_parent)
Definition at line 1295 of file terminal-app.c.
References FALSE, NULL, and terminal_util_load_builder_resource().
terminal_app_new_profile()
void terminal_app_new_profile (TerminalApp * app, TerminalProfile * default_base_profile, GtkWindow * transient_parent)
Definition at line 1199 of file terminal-app.c.
References _, FALSE, NULL, terminal_util_load_builder_resource(), terminal_util_set_atk_name_description(), and TRUE.
terminal_app_new_terminal()
TerminalScreen * terminal_app_new_terminal (TerminalApp * app, TerminalWindow * window, TerminalProfile * profile, char ** override_command, const char * title, const char * working_dir, char ** child_env, double zoom)
Definition at line 1988 of file terminal-app.c.
References NULL, TERMINAL_IS_APP, TERMINAL_IS_WINDOW, terminal_screen_new(), terminal_window_add_screen(), and terminal_window_switch_screen().
Referenced by terminal_app_handle_options().
terminal_app_new_window()
TerminalWindow * terminal_app_new_window (TerminalApp * app, GdkScreen * screen)
Definition at line 1972 of file terminal-app.c.
References terminal_window_new().
Referenced by terminal_app_handle_options().
terminal_app_save_config()
void terminal_app_save_config (TerminalApp * app, GKeyFile * key_file)
Definition at line 2216 of file terminal-app.c.
References FALSE, NULL, PACKAGE_STRING, TERMINAL_CONFIG_COMPAT_VERSION, TERMINAL_CONFIG_GROUP, TERMINAL_CONFIG_PROP_COMPAT_VERSION, TERMINAL_CONFIG_PROP_VERSION, TERMINAL_CONFIG_PROP_WINDOWS, TERMINAL_CONFIG_VERSION, TERMINAL_IS_WINDOW, TERMINAL_WINDOW, and terminal_window_save_state().
Referenced by terminal_app_save_config_file().
terminal_app_save_config_file()
gboolean terminal_app_save_config_file (TerminalApp * app, const char * file_name, GError ** error)
Definition at line 2257 of file terminal-app.c.
References data, error, NULL, and terminal_app_save_config().
Referenced by terminal_app_handle_options().