MATE Desktop Environment: test.h File Reference
test.h File Reference
#include <config.h>
#include <gtk/gtk.h>
#include <eel/eel-debug.h>
#include <eel/eel.h>
#include <libcaja-private/caja-file-utilities.h>
Functions
void test_init (int *argc, char ***argv)
int test_quit (int exit_code)
void test_delete_event (GtkWidget *widget, GdkEvent *event, gpointer callback_data)
GtkWidget * test_window_new (const char *title, guint border_width)
void test_gtk_widget_set_background_image (GtkWidget *widget, const char *image_name)
void test_gtk_widget_set_background_color (GtkWidget *widget, const char *color_spec)
GdkPixbuf * test_pixbuf_new_named (const char *name, float scale)
GtkWidget * test_label_new (const char *text, gboolean with_background, int num_sizes_larger)
void test_pixbuf_draw_rectangle_tiled (GdkPixbuf *pixbuf, const char *tile_name, int x0, int y0, int x1, int y1, int opacity)
void test_window_set_title_with_pid (GtkWindow *window, const char *title)
Function Documentation
test_delete_event()
void test_delete_event (GtkWidget * widget, GdkEvent * event, gpointer callback_data)
Definition at line 25 of file caja/test/test.c.
References test_quit().
Referenced by test_window_new().
test_gtk_widget_set_background_color()
void test_gtk_widget_set_background_color (GtkWidget * widget, const char * color_spec)
Definition at line 71 of file caja/test/test.c.
References eel_background_set_color(), eel_get_widget_background(), and NULL.
test_gtk_widget_set_background_image()
void test_gtk_widget_set_background_image (GtkWidget * widget, const char * image_name)
Definition at line 52 of file caja/test/test.c.
References eel_background_set_image_uri(), eel_get_widget_background(), and NULL.
test_init()
void test_init (int * argc, char *** argv)
Definition at line 6 of file caja/test/test.c.
References eel_make_warnings_and_criticals_stop_in_debugger().
Referenced by main().
test_label_new()
GtkWidget * test_label_new (const char * text, gboolean with_background, int num_sizes_larger)
Definition at line 123 of file caja/test/test.c.
References label, and NULL.
test_pixbuf_draw_rectangle_tiled()
void test_pixbuf_draw_rectangle_tiled (GdkPixbuf * pixbuf, const char * tile_name, int x0, int y0, int x1, int y1, int opacity)
test_pixbuf_new_named()
GdkPixbuf * test_pixbuf_new_named (const char * name, float scale)
Definition at line 85 of file caja/test/test.c.
References name, and NULL.
test_quit()
int test_quit (int exit_code)
Definition at line 15 of file caja/test/test.c.
Referenced by main(), and test_delete_event().
test_window_new()
GtkWidget * test_window_new (const char * title, guint border_width)
Definition at line 33 of file caja/test/test.c.
References NULL, and test_delete_event().
Referenced by main().
test_window_set_title_with_pid()
void test_window_set_title_with_pid (GtkWindow * window, const char * title)
Definition at line 139 of file caja/test/test.c.