MATE Desktop Environment: test-languages.c File Reference
test-languages.c File Reference
#include <stdio.h>
#include <locale.h>
#include "mate-languages.h"
Macros
#define MATE_DESKTOP_USE_UNSTABLE_API
Functions
void test_one_locale (const gchar *locale)
void test_locales (void)
int main (int argc, char **argv)
Macro Definition Documentation
MATE_DESKTOP_USE_UNSTABLE_API
#define MATE_DESKTOP_USE_UNSTABLE_API
Definition at line 20 of file test-languages.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 80 of file test-languages.c.
References test_locales(), and test_one_locale().
test_locales()
void test_locales (void)
Definition at line 66 of file test-languages.c.
References mate_get_all_locales(), and test_one_locale().
Referenced by main().
test_one_locale()
void test_one_locale (const gchar * locale)
Definition at line 26 of file test-languages.c.
References mate_get_country_from_code(), mate_get_country_from_locale(), mate_get_language_from_code(), mate_get_language_from_locale(), mate_language_has_translations(), mate_normalize_locale(), mate_parse_locale(), and modifier.
Referenced by main(), and test_locales().