MATE Desktop Environment: theme-installer.c File Reference
theme-installer.c File Reference
#include "appearance.h"
#include <string.h>
#include <glib.h>
#include <glib/gi18n.h>
#include <gio/gio.h>
#include <glib/gstdio.h>
#include <unistd.h>
#include "capplet-util.h"
#include "file-transfer-dialog.h"
#include "theme-installer.h"
#include "theme-util.h"
Macros
#define g_pattern_spec_match_string g_pattern_match_string
Enumerations
enum {
THEME_INVALID , THEME_ICON , THEME_MATE , THEME_GTK ,
THEME_ENGINE , THEME_MARCO , THEME_CURSOR , THEME_ICON_CURSOR
}
enum { TARGZ , TARBZ , TARXZ , DIRECTORY }
Functions
void mate_theme_install (GFile *file, GtkWindow *parent)
void mate_theme_installer_run (GtkWindow *parent)
Macro Definition Documentation
g_pattern_spec_match_string
#define g_pattern_spec_match_string g_pattern_match_string
Definition at line 38 of file theme-installer.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TARGZ
TARBZ
TARXZ
DIRECTORY
Definition at line 52 of file theme-installer.c.
anonymous enum
anonymous enum
Enumerator
THEME_INVALID
THEME_ICON
THEME_MATE
THEME_GTK
THEME_ENGINE
THEME_MARCO
THEME_CURSOR
THEME_ICON_CURSOR
Definition at line 41 of file theme-installer.c.
Function Documentation
mate_theme_install()
void mate_theme_install (GFile * file, GtkWindow * parent)
Definition at line 704 of file theme-installer.c.
References _, FALSE, FILE_TRANSFER_DIALOG, file_transfer_dialog_copy_async(), FILE_TRANSFER_DIALOG_DEFAULT, file_transfer_dialog_new_with_parent(), and NULL.
Referenced by main(), and mate_theme_installer_run().
mate_theme_installer_run()
void mate_theme_installer_run (GtkWindow * parent)
Definition at line 808 of file theme-installer.c.
References _, FALSE, mate_theme_install(), NULL, and TRUE.