MATE Desktop Environment: theme.h File Reference
theme.h File Reference
#include "boxes.h"
#include "gradient.h"
#include "common.h"
#include <gtk/gtk.h>
Classes
struct _MetaFrameLayout
struct _MetaButtonSpace
struct _MetaFrameGeometry
struct _MetaColorSpec
struct _MetaGradientSpec
struct _MetaAlphaGradientSpec
struct _MetaDrawInfo
struct PosToken
struct _MetaDrawSpec
struct _MetaDrawOp
struct _MetaDrawOpList
struct _MetaFrameStyle
struct _MetaFrameStyleSet
struct _MetaTheme
struct _MetaPositionExprEnv
Macros
#define META_THEME_ERROR (g_quark_from_static_string ("meta-theme-error"))
#define ADDRESS_OF_BUTTON_RECTS(fgeom)
#define LENGTH_OF_BUTTON_RECTS (G_STRUCT_OFFSET (MetaFrameGeometry, right_single_background) + sizeof (GdkRectangle) - G_STRUCT_OFFSET (MetaFrameGeometry, close_rect))
#define MAX_MIDDLE_BACKGROUNDS (MAX_BUTTONS_PER_CORNER - 2)
#define META_THEME_ALLOWS(theme, feature)
#define META_THEME_SHADE_STICK_ABOVE_BUTTONS 2
#define META_THEME_UBIQUITOUS_CONSTANTS 2
#define META_THEME_VARIED_ROUND_CORNERS 2
#define META_THEME_IMAGES_FROM_ICON_THEMES 2
#define META_THEME_UNRESIZABLE_SHADED_STYLES 2
#define META_THEME_DEGREES_IN_ARCS 2
#define META_THEME_HIDDEN_BUTTONS 2
#define META_THEME_COLOR_CONSTANTS 2
#define META_THEME_FRAME_BACKGROUNDS 2
Typedefs
typedef struct _MetaFrameStyle MetaFrameStyle
typedef struct _MetaFrameStyleSet MetaFrameStyleSet
typedef struct _MetaDrawOp MetaDrawOp
typedef struct _MetaDrawOpList MetaDrawOpList
typedef struct _MetaGradientSpec MetaGradientSpec
typedef struct _MetaAlphaGradientSpec MetaAlphaGradientSpec
typedef struct _MetaColorSpec MetaColorSpec
typedef struct _MetaFrameLayout MetaFrameLayout
typedef struct _MetaButtonSpace MetaButtonSpace
typedef struct _MetaFrameGeometry MetaFrameGeometry
typedef struct _MetaTheme MetaTheme
typedef struct _MetaPositionExprEnv MetaPositionExprEnv
typedef struct _MetaDrawInfo MetaDrawInfo
typedef struct _MetaDrawSpec MetaDrawSpec
Enumerations
enum MetaThemeError {
META_THEME_ERROR_FRAME_GEOMETRY , META_THEME_ERROR_BAD_CHARACTER , META_THEME_ERROR_BAD_PARENS , META_THEME_ERROR_UNKNOWN_VARIABLE ,
META_THEME_ERROR_DIVIDE_BY_ZERO , META_THEME_ERROR_MOD_ON_FLOAT , META_THEME_ERROR_FAILED
}
enum MetaButtonSizing { META_BUTTON_SIZING_ASPECT , META_BUTTON_SIZING_FIXED , META_BUTTON_SIZING_LAST }
enum MetaImageFillType { META_IMAGE_FILL_SCALE , META_IMAGE_FILL_TILE }
enum MetaColorSpecType {
META_COLOR_SPEC_BASIC , META_COLOR_SPEC_GTK , META_COLOR_SPEC_GTK_CUSTOM , META_COLOR_SPEC_BLEND ,
META_COLOR_SPEC_SHADE
}
enum MetaGtkColorComponent {
META_GTK_COLOR_FG , META_GTK_COLOR_BG , META_GTK_COLOR_LIGHT , META_GTK_COLOR_DARK ,
META_GTK_COLOR_MID , META_GTK_COLOR_TEXT , META_GTK_COLOR_BASE , META_GTK_COLOR_TEXT_AA ,
META_GTK_COLOR_LAST
}
enum MetaDrawType {
META_DRAW_LINE , META_DRAW_RECTANGLE , META_DRAW_ARC , META_DRAW_CLIP ,
META_DRAW_TINT , META_DRAW_GRADIENT , META_DRAW_IMAGE , META_DRAW_GTK_ARROW ,
META_DRAW_GTK_BOX , META_DRAW_GTK_VLINE , META_DRAW_ICON , META_DRAW_TITLE ,
META_DRAW_OP_LIST , META_DRAW_TILE
}
enum PosTokenType {
POS_TOKEN_INT , POS_TOKEN_DOUBLE , POS_TOKEN_OPERATOR , POS_TOKEN_VARIABLE ,
POS_TOKEN_OPEN_PAREN , POS_TOKEN_CLOSE_PAREN
}
enum PosOperatorType {
POS_OP_NONE , POS_OP_ADD , POS_OP_SUBTRACT , POS_OP_MULTIPLY ,
POS_OP_DIVIDE , POS_OP_MOD , POS_OP_MAX , POS_OP_MIN
}
enum MetaButtonState { META_BUTTON_STATE_NORMAL , META_BUTTON_STATE_PRESSED , META_BUTTON_STATE_PRELIGHT , META_BUTTON_STATE_LAST }
enum MetaButtonType {
META_BUTTON_TYPE_LEFT_LEFT_BACKGROUND , META_BUTTON_TYPE_LEFT_MIDDLE_BACKGROUND , META_BUTTON_TYPE_LEFT_RIGHT_BACKGROUND , META_BUTTON_TYPE_LEFT_SINGLE_BACKGROUND ,
META_BUTTON_TYPE_RIGHT_LEFT_BACKGROUND , META_BUTTON_TYPE_RIGHT_MIDDLE_BACKGROUND , META_BUTTON_TYPE_RIGHT_RIGHT_BACKGROUND , META_BUTTON_TYPE_RIGHT_SINGLE_BACKGROUND ,
META_BUTTON_TYPE_CLOSE , META_BUTTON_TYPE_MAXIMIZE , META_BUTTON_TYPE_MINIMIZE , META_BUTTON_TYPE_MENU ,
META_BUTTON_TYPE_APPMENU , META_BUTTON_TYPE_SHADE , META_BUTTON_TYPE_ABOVE , META_BUTTON_TYPE_STICK ,
META_BUTTON_TYPE_UNSHADE , META_BUTTON_TYPE_UNABOVE , META_BUTTON_TYPE_UNSTICK , META_BUTTON_TYPE_LAST
}
enum MetaMenuIconType {
META_MENU_ICON_TYPE_CLOSE , META_MENU_ICON_TYPE_MAXIMIZE , META_MENU_ICON_TYPE_UNMAXIMIZE , META_MENU_ICON_TYPE_MINIMIZE ,
META_MENU_ICON_TYPE_LAST
}
enum MetaFramePiece {
META_FRAME_PIECE_ENTIRE_BACKGROUND , META_FRAME_PIECE_TITLEBAR , META_FRAME_PIECE_TITLEBAR_MIDDLE , META_FRAME_PIECE_LEFT_TITLEBAR_EDGE ,
META_FRAME_PIECE_RIGHT_TITLEBAR_EDGE , META_FRAME_PIECE_TOP_TITLEBAR_EDGE , META_FRAME_PIECE_BOTTOM_TITLEBAR_EDGE , META_FRAME_PIECE_TITLE ,
META_FRAME_PIECE_LEFT_EDGE , META_FRAME_PIECE_RIGHT_EDGE , META_FRAME_PIECE_BOTTOM_EDGE , META_FRAME_PIECE_OVERLAY ,
META_FRAME_PIECE_LAST
}
enum MetaFrameState {
META_FRAME_STATE_NORMAL , META_FRAME_STATE_MAXIMIZED , META_FRAME_STATE_TILED_LEFT , META_FRAME_STATE_TILED_RIGHT ,
META_FRAME_STATE_SHADED , META_FRAME_STATE_MAXIMIZED_AND_SHADED , META_FRAME_STATE_TILED_LEFT_AND_SHADED , META_FRAME_STATE_TILED_RIGHT_AND_SHADED ,
META_FRAME_STATE_LAST
}
enum MetaFrameResize {
META_FRAME_RESIZE_NONE , META_FRAME_RESIZE_VERTICAL , META_FRAME_RESIZE_HORIZONTAL , META_FRAME_RESIZE_BOTH ,
META_FRAME_RESIZE_LAST
}
enum MetaFrameFocus { META_FRAME_FOCUS_NO , META_FRAME_FOCUS_YES , META_FRAME_FOCUS_LAST }
Functions
MetaFrameLayout * meta_frame_layout_new (void)
MetaFrameLayout * meta_frame_layout_copy (const MetaFrameLayout *src)
void meta_frame_layout_ref (MetaFrameLayout *layout)
void meta_frame_layout_unref (MetaFrameLayout *layout)
void meta_frame_layout_get_borders (const MetaFrameLayout *layout, int text_height, MetaFrameFlags flags, MetaFrameType type, MetaFrameBorders *borders)
void meta_frame_layout_calc_geometry (const MetaFrameLayout *layout, int text_height, MetaFrameFlags flags, int client_width, int client_height, const MetaButtonLayout *button_layout, MetaFrameGeometry *fgeom, MetaTheme *theme)
gboolean meta_frame_layout_validate (const MetaFrameLayout *layout, GError **error)
gboolean meta_parse_position_expression (MetaDrawSpec *spec, const MetaPositionExprEnv *env, int *x_return, int *y_return, GError **err)
gboolean meta_parse_size_expression (MetaDrawSpec *spec, const MetaPositionExprEnv *env, int *val_return, GError **err)
MetaDrawSpec * meta_draw_spec_new (MetaTheme *theme, const char *expr, GError **error)
void meta_draw_spec_free (MetaDrawSpec *spec)
MetaColorSpec * meta_color_spec_new (MetaColorSpecType type)
MetaColorSpec * meta_color_spec_new_from_string (const char *str, GError **err)
MetaColorSpec * meta_color_spec_new_gtk (MetaGtkColorComponent component, GtkStateFlags state)
void meta_color_spec_free (MetaColorSpec *spec)
void meta_color_spec_render (MetaColorSpec *spec, GtkStyleContext *style_gtk, GdkRGBA *color)
MetaDrawOp * meta_draw_op_new (MetaDrawType type)
void meta_draw_op_free (MetaDrawOp *op)
void meta_draw_op_draw (const MetaDrawOp *op, GtkWidget *widget, cairo_t *cr, const MetaDrawInfo *info, MetaRectangle logical_region)
void meta_draw_op_draw_with_style (const MetaDrawOp *op, GtkStyleContext *style_gtk, cairo_t *cr, const MetaDrawInfo *info, MetaRectangle logical_region)
MetaDrawOpList * meta_draw_op_list_new (int n_preallocs)
void meta_draw_op_list_ref (MetaDrawOpList *op_list)
void meta_draw_op_list_unref (MetaDrawOpList *op_list)
void meta_draw_op_list_draw (const MetaDrawOpList *op_list, GtkWidget *widget, cairo_t *cr, const MetaDrawInfo *info, MetaRectangle rect)
void meta_draw_op_list_draw_with_style (const MetaDrawOpList *op_list, GtkStyleContext *style_gtk, cairo_t *cr, const MetaDrawInfo *info, MetaRectangle rect)
void meta_draw_op_list_append (MetaDrawOpList *op_list, MetaDrawOp *op)
gboolean meta_draw_op_list_validate (MetaDrawOpList *op_list, GError **error)
gboolean meta_draw_op_list_contains (MetaDrawOpList *op_list, MetaDrawOpList *child)
MetaGradientSpec * meta_gradient_spec_new (MetaGradientType type)
void meta_gradient_spec_free (MetaGradientSpec *desc)
void meta_gradient_spec_render (const MetaGradientSpec *spec, const MetaAlphaGradientSpec *alpha_spec, cairo_t *cr, GtkStyleContext *context, gint x, gint y, gint width, gint height)
gboolean meta_gradient_spec_validate (MetaGradientSpec *spec, GError **error)
MetaAlphaGradientSpec * meta_alpha_gradient_spec_new (MetaGradientType type, int n_alphas)
void meta_alpha_gradient_spec_free (MetaAlphaGradientSpec *spec)
cairo_pattern_t * meta_alpha_gradient_spec_get_mask (const MetaAlphaGradientSpec *spec)
MetaFrameStyle * meta_frame_style_new (MetaFrameStyle *parent)
void meta_frame_style_ref (MetaFrameStyle *style)
void meta_frame_style_unref (MetaFrameStyle *style)
void meta_frame_style_draw (MetaFrameStyle *style, GtkWidget *widget, cairo_t *cr, const MetaFrameGeometry *fgeom, int client_width, int client_height, PangoLayout *title_layout, int text_height, MetaButtonState button_states[META_BUTTON_TYPE_LAST], GdkPixbuf *mini_icon, GdkPixbuf *icon)
void meta_frame_style_draw_with_style (MetaFrameStyle *style, GtkStyleContext *style_gtk, cairo_t *cr, const MetaFrameGeometry *fgeom, int client_width, int client_height, PangoLayout *title_layout, int text_height, MetaButtonState button_states[META_BUTTON_TYPE_LAST], GdkPixbuf *mini_icon, GdkPixbuf *icon)
gboolean meta_frame_style_validate (MetaFrameStyle *style, guint current_theme_version, GError **error)
MetaFrameStyleSet * meta_frame_style_set_new (MetaFrameStyleSet *parent)
void meta_frame_style_set_ref (MetaFrameStyleSet *style_set)
void meta_frame_style_set_unref (MetaFrameStyleSet *style_set)
gboolean meta_frame_style_set_validate (MetaFrameStyleSet *style_set, GError **error)
MetaTheme * meta_theme_get_current (void)
void meta_theme_set_current (const char *name, gboolean force_reload)
MetaTheme * meta_theme_new (void)
void meta_theme_free (MetaTheme *theme)
gboolean meta_theme_validate (MetaTheme *theme, GError **error)
GdkPixbuf * meta_theme_load_image (MetaTheme *theme, const char *filename, guint size_of_theme_icons, GError **error)
MetaFrameStyle * meta_theme_get_frame_style (MetaTheme *theme, MetaFrameType type, MetaFrameFlags flags)
double meta_theme_get_title_scale (MetaTheme *theme, MetaFrameType type, MetaFrameFlags flags)
void meta_theme_draw_frame (MetaTheme *theme, GtkStyleContext *style_gtk, cairo_t *cr, MetaFrameType type, MetaFrameFlags flags, int client_width, int client_height, PangoLayout *title_layout, int text_height, const MetaButtonLayout *button_layout, MetaButtonState button_states[META_BUTTON_TYPE_LAST], GdkPixbuf *mini_icon, GdkPixbuf *icon)
void meta_theme_draw_frame_by_name (MetaTheme *theme, GtkWidget *widget, cairo_t *cr, const gchar *style_name, MetaFrameFlags flags, int client_width, int client_height, PangoLayout *title_layout, int text_height, const MetaButtonLayout *button_layout, MetaButtonState button_states[META_BUTTON_TYPE_LAST], GdkPixbuf *mini_icon, GdkPixbuf *icon)
void meta_theme_get_frame_borders (MetaTheme *theme, MetaFrameType type, int text_height, MetaFrameFlags flags, MetaFrameBorders *borders)
void meta_theme_calc_geometry (MetaTheme *theme, MetaFrameType type, int text_height, MetaFrameFlags flags, int client_width, int client_height, const MetaButtonLayout *button_layout, MetaFrameGeometry *fgeom)
MetaFrameLayout * meta_theme_lookup_layout (MetaTheme *theme, const char *name)
void meta_theme_insert_layout (MetaTheme *theme, const char *name, MetaFrameLayout *layout)
MetaDrawOpList * meta_theme_lookup_draw_op_list (MetaTheme *theme, const char *name)
void meta_theme_insert_draw_op_list (MetaTheme *theme, const char *name, MetaDrawOpList *op_list)
MetaFrameStyle * meta_theme_lookup_style (MetaTheme *theme, const char *name)
void meta_theme_insert_style (MetaTheme *theme, const char *name, MetaFrameStyle *style)
MetaFrameStyleSet * meta_theme_lookup_style_set (MetaTheme *theme, const char *name)
void meta_theme_insert_style_set (MetaTheme *theme, const char *name, MetaFrameStyleSet *style_set)
gboolean meta_theme_define_int_constant (MetaTheme *theme, const char *name, int value, GError **error)
gboolean meta_theme_lookup_int_constant (MetaTheme *theme, const char *name, int *value)
gboolean meta_theme_define_float_constant (MetaTheme *theme, const char *name, double value, GError **error)
gboolean meta_theme_lookup_float_constant (MetaTheme *theme, const char *name, double *value)
gboolean meta_theme_define_color_constant (MetaTheme *theme, const char *name, const char *value, GError **error)
gboolean meta_theme_lookup_color_constant (MetaTheme *theme, const char *name, char **value)
gboolean meta_theme_replace_constants (MetaTheme *theme, PosToken *tokens, int n_tokens, GError **err)
PangoFontDescription * meta_gtk_widget_get_font_desc (GtkWidget *widget, double scale, const PangoFontDescription *override)
int meta_pango_font_desc_get_text_height (const PangoFontDescription *font_desc, PangoContext *context)
MetaGtkColorComponent meta_color_component_from_string (const char *str)
const char * meta_color_component_to_string (MetaGtkColorComponent component)
MetaButtonState meta_button_state_from_string (const char *str)
const char * meta_button_state_to_string (MetaButtonState state)
MetaButtonType meta_button_type_from_string (const char *str, MetaTheme *theme)
const char * meta_button_type_to_string (MetaButtonType type)
MetaFramePiece meta_frame_piece_from_string (const char *str)
const char * meta_frame_piece_to_string (MetaFramePiece piece)
MetaFrameState meta_frame_state_from_string (const char *str)
const char * meta_frame_state_to_string (MetaFrameState state)
MetaFrameResize meta_frame_resize_from_string (const char *str)
const char * meta_frame_resize_to_string (MetaFrameResize resize)
MetaFrameFocus meta_frame_focus_from_string (const char *str)
const char * meta_frame_focus_to_string (MetaFrameFocus focus)
MetaFrameType meta_frame_type_from_string (const char *str)
const char * meta_frame_type_to_string (MetaFrameType type)
MetaGradientType meta_gradient_type_from_string (const char *str)
const char * meta_gradient_type_to_string (MetaGradientType type)
GtkStateFlags meta_gtk_state_from_string (const char *str)
GtkShadowType meta_gtk_shadow_from_string (const char *str)
const char * meta_gtk_shadow_to_string (GtkShadowType shadow)
GtkArrowType meta_gtk_arrow_from_string (const char *str)
const char * meta_gtk_arrow_to_string (GtkArrowType arrow)
MetaImageFillType meta_image_fill_type_from_string (const char *str)
const char * meta_image_fill_type_to_string (MetaImageFillType fill_type)
void meta_gtk_style_get_light_color (GtkStyleContext *style, GtkStateFlags state, GdkRGBA *color)
void meta_gtk_style_get_dark_color (GtkStyleContext *style, GtkStateFlags state, GdkRGBA *color)
guint meta_theme_earliest_version_with_button (MetaButtonType type)
Macro Definition Documentation
ADDRESS_OF_BUTTON_RECTS
#define ADDRESS_OF_BUTTON_RECTS (fgeom)
Value:
(((char*)(fgeom)) + G_STRUCT_OFFSET (MetaFrameGeometry, close_rect))
Definition at line 186 of file theme.h.
Referenced by meta_frame_layout_calc_geometry().
LENGTH_OF_BUTTON_RECTS
#define LENGTH_OF_BUTTON_RECTS (G_STRUCT_OFFSET (MetaFrameGeometry, right_single_background) + sizeof (GdkRectangle) - G_STRUCT_OFFSET (MetaFrameGeometry, close_rect))
Definition at line 187 of file theme.h.
Referenced by meta_frame_layout_calc_geometry().
MAX_MIDDLE_BACKGROUNDS
#define MAX_MIDDLE_BACKGROUNDS (MAX_BUTTONS_PER_CORNER - 2)
Definition at line 202 of file theme.h.
Referenced by meta_frame_style_draw_with_style().
META_THEME_ALLOWS
#define META_THEME_ALLOWS (theme, feature)
Value:
(theme->format_version >= feature)
Definition at line 1163 of file theme.h.
Referenced by meta_button_type_from_string(), and meta_theme_load_image().
META_THEME_COLOR_CONSTANTS
#define META_THEME_COLOR_CONSTANTS 2
Definition at line 1173 of file theme.h.
META_THEME_DEGREES_IN_ARCS
#define META_THEME_DEGREES_IN_ARCS 2
Definition at line 1171 of file theme.h.
META_THEME_ERROR
#define META_THEME_ERROR (g_quark_from_static_string ("meta-theme-error"))
Definition at line 46 of file theme.h.
Referenced by meta_color_spec_new_from_string(), meta_frame_layout_validate(), meta_frame_style_set_validate(), meta_frame_style_validate(), meta_gradient_spec_validate(), meta_theme_define_color_constant(), meta_theme_define_float_constant(), meta_theme_define_int_constant(), meta_theme_load(), and meta_theme_validate().
META_THEME_FRAME_BACKGROUNDS
#define META_THEME_FRAME_BACKGROUNDS 2
Definition at line 1174 of file theme.h.
META_THEME_HIDDEN_BUTTONS
#define META_THEME_HIDDEN_BUTTONS 2
Definition at line 1172 of file theme.h.
META_THEME_IMAGES_FROM_ICON_THEMES
#define META_THEME_IMAGES_FROM_ICON_THEMES 2
Definition at line 1169 of file theme.h.
Referenced by meta_theme_load_image().
META_THEME_SHADE_STICK_ABOVE_BUTTONS
#define META_THEME_SHADE_STICK_ABOVE_BUTTONS 2
Definition at line 1166 of file theme.h.
Referenced by meta_button_type_from_string().
META_THEME_UBIQUITOUS_CONSTANTS
#define META_THEME_UBIQUITOUS_CONSTANTS 2
Definition at line 1167 of file theme.h.
META_THEME_UNRESIZABLE_SHADED_STYLES
#define META_THEME_UNRESIZABLE_SHADED_STYLES 2
Definition at line 1170 of file theme.h.
META_THEME_VARIED_ROUND_CORNERS
#define META_THEME_VARIED_ROUND_CORNERS 2
Definition at line 1168 of file theme.h.
Typedef Documentation
MetaAlphaGradientSpec
typedef struct _MetaAlphaGradientSpec MetaAlphaGradientSpec
Definition at line 37 of file theme.h.
MetaButtonSpace
typedef struct _MetaButtonSpace MetaButtonSpace
Definition at line 40 of file theme.h.
MetaColorSpec
typedef struct _MetaColorSpec MetaColorSpec
Definition at line 38 of file theme.h.
MetaDrawInfo
typedef struct _MetaDrawInfo MetaDrawInfo
Definition at line 44 of file theme.h.
MetaDrawOp
typedef struct _MetaDrawOp MetaDrawOp
Definition at line 34 of file theme.h.
MetaDrawOpList
typedef struct _MetaDrawOpList MetaDrawOpList
Definition at line 35 of file theme.h.
MetaFrameGeometry
typedef struct _MetaFrameGeometry MetaFrameGeometry
Definition at line 41 of file theme.h.
MetaFrameLayout
typedef struct _MetaFrameLayout MetaFrameLayout
Definition at line 39 of file theme.h.
MetaFrameStyle
typedef struct _MetaFrameStyle MetaFrameStyle
Definition at line 32 of file theme.h.
MetaFrameStyleSet
typedef struct _MetaFrameStyleSet MetaFrameStyleSet
Definition at line 33 of file theme.h.
MetaGradientSpec
typedef struct _MetaGradientSpec MetaGradientSpec
Definition at line 36 of file theme.h.
MetaPositionExprEnv
typedef struct _MetaPositionExprEnv MetaPositionExprEnv
Definition at line 43 of file theme.h.
MetaTheme
typedef struct _MetaTheme MetaTheme
Definition at line 42 of file theme.h.
Enumeration Type Documentation
MetaButtonSizing
enum MetaButtonSizing
Whether a button's size is calculated from the area around it (aspect sizing) or is given as a fixed height and width in pixels (fixed sizing).
Enumerator
META_BUTTON_SIZING_ASPECT
META_BUTTON_SIZING_FIXED
META_BUTTON_SIZING_LAST
Definition at line 66 of file theme.h.
MetaButtonState
enum MetaButtonState
Enumerator
META_BUTTON_STATE_NORMAL
META_BUTTON_STATE_PRESSED
META_BUTTON_STATE_PRELIGHT
META_BUTTON_STATE_LAST
Definition at line 589 of file theme.h.
MetaButtonType
enum MetaButtonType
Enumerator
META_BUTTON_TYPE_LEFT_LEFT_BACKGROUND
META_BUTTON_TYPE_LEFT_MIDDLE_BACKGROUND
META_BUTTON_TYPE_LEFT_RIGHT_BACKGROUND
META_BUTTON_TYPE_LEFT_SINGLE_BACKGROUND
META_BUTTON_TYPE_RIGHT_LEFT_BACKGROUND
META_BUTTON_TYPE_RIGHT_MIDDLE_BACKGROUND
META_BUTTON_TYPE_RIGHT_RIGHT_BACKGROUND
META_BUTTON_TYPE_RIGHT_SINGLE_BACKGROUND
META_BUTTON_TYPE_CLOSE
META_BUTTON_TYPE_MAXIMIZE
META_BUTTON_TYPE_MINIMIZE
META_BUTTON_TYPE_MENU
META_BUTTON_TYPE_APPMENU
META_BUTTON_TYPE_SHADE
META_BUTTON_TYPE_ABOVE
META_BUTTON_TYPE_STICK
META_BUTTON_TYPE_UNSHADE
META_BUTTON_TYPE_UNABOVE
META_BUTTON_TYPE_UNSTICK
META_BUTTON_TYPE_LAST
Definition at line 597 of file theme.h.
MetaColorSpecType
enum MetaColorSpecType
Enumerator
META_COLOR_SPEC_BASIC
META_COLOR_SPEC_GTK
META_COLOR_SPEC_GTK_CUSTOM
META_COLOR_SPEC_BLEND
META_COLOR_SPEC_SHADE
Definition at line 231 of file theme.h.
MetaDrawType
enum MetaDrawType
A drawing operation in our simple vector drawing language.
Enumerator
META_DRAW_LINE
Basic drawing– line
META_DRAW_RECTANGLE
Basic drawing– rectangle
META_DRAW_ARC
Basic drawing– arc
META_DRAW_CLIP
Clip to a rectangle
META_DRAW_TINT
Just a filled rectangle with alpha
META_DRAW_GRADIENT
META_DRAW_IMAGE
META_DRAW_GTK_ARROW
GTK theme engine stuff
META_DRAW_GTK_BOX
META_DRAW_GTK_VLINE
META_DRAW_ICON
App's window icon
META_DRAW_TITLE
App's window title
META_DRAW_OP_LIST
a draw op list
META_DRAW_TILE
tiled draw op list
Definition at line 309 of file theme.h.
MetaFrameFocus
enum MetaFrameFocus
Enumerator
META_FRAME_FOCUS_NO
META_FRAME_FOCUS_YES
META_FRAME_FOCUS_LAST
Definition at line 747 of file theme.h.
MetaFramePiece
enum MetaFramePiece
Enumerator
META_FRAME_PIECE_ENTIRE_BACKGROUND
META_FRAME_PIECE_TITLEBAR
META_FRAME_PIECE_TITLEBAR_MIDDLE
META_FRAME_PIECE_LEFT_TITLEBAR_EDGE
META_FRAME_PIECE_RIGHT_TITLEBAR_EDGE
META_FRAME_PIECE_TOP_TITLEBAR_EDGE
META_FRAME_PIECE_BOTTOM_TITLEBAR_EDGE
META_FRAME_PIECE_TITLE
META_FRAME_PIECE_LEFT_EDGE
META_FRAME_PIECE_RIGHT_EDGE
META_FRAME_PIECE_BOTTOM_EDGE
META_FRAME_PIECE_OVERLAY
META_FRAME_PIECE_LAST
Definition at line 631 of file theme.h.
MetaFrameResize
enum MetaFrameResize
Enumerator
META_FRAME_RESIZE_NONE
META_FRAME_RESIZE_VERTICAL
META_FRAME_RESIZE_HORIZONTAL
META_FRAME_RESIZE_BOTH
META_FRAME_RESIZE_LAST
Definition at line 738 of file theme.h.
MetaFrameState
enum MetaFrameState
Enumerator
META_FRAME_STATE_NORMAL
META_FRAME_STATE_MAXIMIZED
META_FRAME_STATE_TILED_LEFT
META_FRAME_STATE_TILED_RIGHT
META_FRAME_STATE_SHADED
META_FRAME_STATE_MAXIMIZED_AND_SHADED
META_FRAME_STATE_TILED_LEFT_AND_SHADED
META_FRAME_STATE_TILED_RIGHT_AND_SHADED
META_FRAME_STATE_LAST
Definition at line 725 of file theme.h.
MetaGtkColorComponent
enum MetaGtkColorComponent
Enumerator
META_GTK_COLOR_FG
META_GTK_COLOR_BG
META_GTK_COLOR_LIGHT
META_GTK_COLOR_DARK
META_GTK_COLOR_MID
META_GTK_COLOR_TEXT
META_GTK_COLOR_BASE
META_GTK_COLOR_TEXT_AA
META_GTK_COLOR_LAST
Definition at line 240 of file theme.h.
MetaImageFillType
enum MetaImageFillType
Enumerator
META_IMAGE_FILL_SCALE
META_IMAGE_FILL_TILE
Definition at line 225 of file theme.h.
MetaMenuIconType
enum MetaMenuIconType
Enumerator
META_MENU_ICON_TYPE_CLOSE
META_MENU_ICON_TYPE_MAXIMIZE
META_MENU_ICON_TYPE_UNMAXIMIZE
META_MENU_ICON_TYPE_MINIMIZE
META_MENU_ICON_TYPE_LAST
Definition at line 622 of file theme.h.
MetaThemeError
enum MetaThemeError
Enumerator
META_THEME_ERROR_FRAME_GEOMETRY
META_THEME_ERROR_BAD_CHARACTER
META_THEME_ERROR_BAD_PARENS
META_THEME_ERROR_UNKNOWN_VARIABLE
META_THEME_ERROR_DIVIDE_BY_ZERO
META_THEME_ERROR_MOD_ON_FLOAT
META_THEME_ERROR_FAILED
Definition at line 48 of file theme.h.
PosOperatorType
enum PosOperatorType
Enumerator
POS_OP_NONE
POS_OP_ADD
POS_OP_SUBTRACT
POS_OP_MULTIPLY
POS_OP_DIVIDE
POS_OP_MOD
POS_OP_MAX
POS_OP_MIN
Definition at line 353 of file theme.h.
PosTokenType
enum PosTokenType
Enumerator
POS_TOKEN_INT
POS_TOKEN_DOUBLE
POS_TOKEN_OPERATOR
POS_TOKEN_VARIABLE
POS_TOKEN_OPEN_PAREN
POS_TOKEN_CLOSE_PAREN
Definition at line 343 of file theme.h.
Function Documentation
meta_alpha_gradient_spec_free()
void meta_alpha_gradient_spec_free (MetaAlphaGradientSpec * spec)
Definition at line 1297 of file marco/src/ui/theme.c.
References _MetaAlphaGradientSpec::alphas, and NULL.
Referenced by meta_draw_op_free().
meta_alpha_gradient_spec_get_mask()
cairo_pattern_t * meta_alpha_gradient_spec_get_mask (const MetaAlphaGradientSpec * spec)
Definition at line 1306 of file marco/src/ui/theme.c.
References _MetaAlphaGradientSpec::alphas, META_GRADIENT_HORIZONTAL, _MetaAlphaGradientSpec::n_alphas, NULL, and _MetaAlphaGradientSpec::type.
meta_alpha_gradient_spec_new()
MetaAlphaGradientSpec * meta_alpha_gradient_spec_new (MetaGradientType type, int n_alphas)
Definition at line 1280 of file marco/src/ui/theme.c.
References _MetaAlphaGradientSpec::alphas, _MetaAlphaGradientSpec::n_alphas, NULL, and _MetaAlphaGradientSpec::type.
meta_button_state_from_string()
MetaButtonState meta_button_state_from_string (const char * str)
Definition at line 6377 of file marco/src/ui/theme.c.
References META_BUTTON_STATE_LAST, META_BUTTON_STATE_NORMAL, META_BUTTON_STATE_PRELIGHT, and META_BUTTON_STATE_PRESSED.
meta_button_state_to_string()
const char * meta_button_state_to_string (MetaButtonState state)
Definition at line 6390 of file marco/src/ui/theme.c.
References META_BUTTON_STATE_LAST, META_BUTTON_STATE_NORMAL, META_BUTTON_STATE_PRELIGHT, and META_BUTTON_STATE_PRESSED.
Referenced by meta_frame_style_validate().
meta_button_type_from_string()
MetaButtonType meta_button_type_from_string (const char * str, MetaTheme * theme)
Definition at line 6408 of file marco/src/ui/theme.c.
References META_BUTTON_TYPE_ABOVE, META_BUTTON_TYPE_APPMENU, META_BUTTON_TYPE_CLOSE, META_BUTTON_TYPE_LAST, META_BUTTON_TYPE_LEFT_LEFT_BACKGROUND, META_BUTTON_TYPE_LEFT_MIDDLE_BACKGROUND, META_BUTTON_TYPE_LEFT_RIGHT_BACKGROUND, META_BUTTON_TYPE_LEFT_SINGLE_BACKGROUND, META_BUTTON_TYPE_MAXIMIZE, META_BUTTON_TYPE_MENU, META_BUTTON_TYPE_MINIMIZE, META_BUTTON_TYPE_RIGHT_LEFT_BACKGROUND, META_BUTTON_TYPE_RIGHT_MIDDLE_BACKGROUND, META_BUTTON_TYPE_RIGHT_RIGHT_BACKGROUND, META_BUTTON_TYPE_RIGHT_SINGLE_BACKGROUND, META_BUTTON_TYPE_SHADE, META_BUTTON_TYPE_STICK, META_BUTTON_TYPE_UNABOVE, META_BUTTON_TYPE_UNSHADE, META_BUTTON_TYPE_UNSTICK, META_THEME_ALLOWS, and META_THEME_SHADE_STICK_ABOVE_BUTTONS.
meta_button_type_to_string()
const char * meta_button_type_to_string (MetaButtonType type)
Definition at line 6457 of file marco/src/ui/theme.c.
References META_BUTTON_TYPE_ABOVE, META_BUTTON_TYPE_APPMENU, META_BUTTON_TYPE_CLOSE, META_BUTTON_TYPE_LAST, META_BUTTON_TYPE_LEFT_LEFT_BACKGROUND, META_BUTTON_TYPE_LEFT_MIDDLE_BACKGROUND, META_BUTTON_TYPE_LEFT_RIGHT_BACKGROUND, META_BUTTON_TYPE_LEFT_SINGLE_BACKGROUND, META_BUTTON_TYPE_MAXIMIZE, META_BUTTON_TYPE_MENU, META_BUTTON_TYPE_MINIMIZE, META_BUTTON_TYPE_RIGHT_LEFT_BACKGROUND, META_BUTTON_TYPE_RIGHT_MIDDLE_BACKGROUND, META_BUTTON_TYPE_RIGHT_RIGHT_BACKGROUND, META_BUTTON_TYPE_RIGHT_SINGLE_BACKGROUND, META_BUTTON_TYPE_SHADE, META_BUTTON_TYPE_STICK, META_BUTTON_TYPE_UNABOVE, META_BUTTON_TYPE_UNSHADE, and META_BUTTON_TYPE_UNSTICK.
Referenced by meta_frame_style_validate().
meta_color_component_from_string()
MetaGtkColorComponent meta_color_component_from_string (const char * str)
Definition at line 6326 of file marco/src/ui/theme.c.
References META_GTK_COLOR_BASE, META_GTK_COLOR_BG, META_GTK_COLOR_DARK, META_GTK_COLOR_FG, META_GTK_COLOR_LAST, META_GTK_COLOR_LIGHT, META_GTK_COLOR_MID, META_GTK_COLOR_TEXT, and META_GTK_COLOR_TEXT_AA.
Referenced by meta_color_spec_new_from_string().
meta_color_component_to_string()
const char * meta_color_component_to_string (MetaGtkColorComponent component)
Definition at line 6349 of file marco/src/ui/theme.c.
References META_GTK_COLOR_BASE, META_GTK_COLOR_BG, META_GTK_COLOR_DARK, META_GTK_COLOR_FG, META_GTK_COLOR_LAST, META_GTK_COLOR_LIGHT, META_GTK_COLOR_MID, META_GTK_COLOR_TEXT, and META_GTK_COLOR_TEXT_AA.
meta_color_spec_free()
void meta_color_spec_free (MetaColorSpec * spec)
Definition at line 1377 of file marco/src/ui/theme.c.
References _MetaColorSpec::background, _MetaColorSpec::base, _MetaColorSpec::basic, _MetaColorSpec::blend, _MetaColorSpec::color_name, _MetaColorSpec::data, DEBUG_FILL_STRUCT, _MetaColorSpec::fallback, _MetaColorSpec::foreground, _MetaColorSpec::gtk, _MetaColorSpec::gtkcustom, META_COLOR_SPEC_BASIC, META_COLOR_SPEC_BLEND, meta_color_spec_free(), META_COLOR_SPEC_GTK, META_COLOR_SPEC_GTK_CUSTOM, META_COLOR_SPEC_SHADE, NULL, _MetaColorSpec::shade, and _MetaColorSpec::type.
Referenced by meta_color_spec_free(), meta_color_spec_new_from_string(), meta_draw_op_free(), and meta_frame_style_unref().
meta_color_spec_new()
MetaColorSpec * meta_color_spec_new (MetaColorSpecType type)
Definition at line 1338 of file marco/src/ui/theme.c.
References data, META_COLOR_SPEC_BASIC, META_COLOR_SPEC_BLEND, META_COLOR_SPEC_GTK, META_COLOR_SPEC_GTK_CUSTOM, META_COLOR_SPEC_SHADE, and _MetaColorSpec::type.
Referenced by meta_color_spec_new_from_string(), and meta_color_spec_new_gtk().
meta_color_spec_new_from_string()
MetaColorSpec * meta_color_spec_new_from_string (const char * str, GError ** err)
Definition at line 1418 of file marco/src/ui/theme.c.
References _, _MetaColorSpec::alpha, _MetaColorSpec::background, _MetaColorSpec::base, _MetaColorSpec::basic, _MetaColorSpec::blend, _MetaColorSpec::color, _MetaColorSpec::color_name, _MetaColorSpec::component, _MetaColorSpec::data, debug, _MetaColorSpec::factor, _MetaColorSpec::fallback, FALSE, _MetaColorSpec::foreground, _MetaColorSpec::gtk, _MetaColorSpec::gtkcustom, meta_color_component_from_string(), META_COLOR_SPEC_BASIC, META_COLOR_SPEC_BLEND, meta_color_spec_free(), META_COLOR_SPEC_GTK, META_COLOR_SPEC_GTK_CUSTOM, meta_color_spec_new(), meta_color_spec_new_from_string(), META_COLOR_SPEC_SHADE, META_GTK_COLOR_LAST, meta_gtk_state_from_string(), META_THEME_ERROR, META_THEME_ERROR_FAILED, NULL, _MetaColorSpec::shade, _MetaColorSpec::state, strrchr, and TRUE.
Referenced by meta_color_spec_new_from_string().
meta_color_spec_new_gtk()
MetaColorSpec * meta_color_spec_new_gtk (MetaGtkColorComponent component, GtkStateFlags state)
Definition at line 1712 of file marco/src/ui/theme.c.
References _MetaColorSpec::component, _MetaColorSpec::data, _MetaColorSpec::gtk, META_COLOR_SPEC_GTK, meta_color_spec_new(), and _MetaColorSpec::state.
meta_color_spec_render()
void meta_color_spec_render (MetaColorSpec * spec, GtkStyleContext * style_gtk, GdkRGBA * color)
Definition at line 1852 of file marco/src/ui/theme.c.
References _MetaColorSpec::alpha, _MetaColorSpec::background, _MetaColorSpec::base, _MetaColorSpec::basic, _MetaColorSpec::blend, _MetaColorSpec::color, _MetaColorSpec::color_name, _MetaColorSpec::component, _MetaColorSpec::data, _MetaColorSpec::factor, _MetaColorSpec::fallback, _MetaColorSpec::foreground, _MetaColorSpec::gtk, _MetaColorSpec::gtkcustom, META_COLOR_SPEC_BASIC, META_COLOR_SPEC_BLEND, META_COLOR_SPEC_GTK, META_COLOR_SPEC_GTK_CUSTOM, meta_color_spec_render(), META_COLOR_SPEC_SHADE, NULL, _MetaColorSpec::shade, _MetaColorSpec::state, and _MetaColorSpec::type.
Referenced by meta_color_spec_render().
meta_draw_op_draw()
void meta_draw_op_draw (const MetaDrawOp * op, GtkWidget * widget, cairo_t * cr, const MetaDrawInfo * info, MetaRectangle logical_region)
Definition at line 4487 of file marco/src/ui/theme.c.
References meta_draw_op_draw_with_style(), and op.
meta_draw_op_draw_with_style()
void meta_draw_op_draw_with_style (const MetaDrawOp * op, GtkStyleContext * style_gtk, cairo_t * cr, const MetaDrawInfo * info, MetaRectangle logical_region)
Definition at line 4468 of file marco/src/ui/theme.c.
References op.
Referenced by meta_draw_op_draw().
meta_draw_op_free()
void meta_draw_op_free (MetaDrawOp * op)
Definition at line 3227 of file marco/src/ui/theme.c.
References meta_alpha_gradient_spec_free(), meta_color_spec_free(), META_DRAW_ARC, META_DRAW_CLIP, META_DRAW_GRADIENT, META_DRAW_GTK_ARROW, META_DRAW_GTK_BOX, META_DRAW_GTK_VLINE, META_DRAW_ICON, META_DRAW_IMAGE, META_DRAW_LINE, META_DRAW_OP_LIST, meta_draw_op_list_unref(), META_DRAW_RECTANGLE, meta_draw_spec_free(), META_DRAW_TILE, META_DRAW_TINT, META_DRAW_TITLE, meta_gradient_spec_free(), NULL, and op.
Referenced by meta_draw_op_list_unref().
meta_draw_op_list_append()
void meta_draw_op_list_append (MetaDrawOpList * op_list, MetaDrawOp * op)
Definition at line 4618 of file marco/src/ui/theme.c.
References _MetaDrawOpList::n_allocated, _MetaDrawOpList::n_ops, op, and _MetaDrawOpList::ops.
meta_draw_op_list_contains()
gboolean meta_draw_op_list_contains (MetaDrawOpList * op_list, MetaDrawOpList * child)
Definition at line 4647 of file marco/src/ui/theme.c.
References _MetaDrawOp::data, FALSE, META_DRAW_OP_LIST, meta_draw_op_list_contains(), META_DRAW_TILE, _MetaDrawOpList::n_ops, _MetaDrawOp::op_list, _MetaDrawOpList::ops, _MetaDrawOp::tile, TRUE, and _MetaDrawOp::type.
Referenced by meta_draw_op_list_contains().
meta_draw_op_list_draw()
void meta_draw_op_list_draw (const MetaDrawOpList * op_list, GtkWidget * widget, cairo_t * cr, const MetaDrawInfo * info, MetaRectangle rect)
Definition at line 4604 of file marco/src/ui/theme.c.
References meta_draw_op_list_draw_with_style().
meta_draw_op_list_draw_with_style()
void meta_draw_op_list_draw_with_style (const MetaDrawOpList * op_list, GtkStyleContext * style_gtk, cairo_t * cr, const MetaDrawInfo * info, MetaRectangle rect)
Definition at line 4547 of file marco/src/ui/theme.c.
References META_DRAW_CLIP, _MetaDrawOpList::n_ops, NULL, op, and _MetaDrawOpList::ops.
Referenced by meta_draw_op_list_draw(), and meta_frame_style_draw_with_style().
meta_draw_op_list_new()
MetaDrawOpList * meta_draw_op_list_new (int n_preallocs)
Definition at line 4500 of file marco/src/ui/theme.c.
References _MetaDrawOpList::n_allocated, _MetaDrawOpList::n_ops, NULL, _MetaDrawOpList::ops, and _MetaDrawOpList::refcount.
meta_draw_op_list_ref()
void meta_draw_op_list_ref (MetaDrawOpList * op_list)
Definition at line 4517 of file marco/src/ui/theme.c.
References NULL, and _MetaDrawOpList::refcount.
Referenced by meta_theme_insert_draw_op_list().
meta_draw_op_list_unref()
void meta_draw_op_list_unref (MetaDrawOpList * op_list)
Definition at line 4525 of file marco/src/ui/theme.c.
References DEBUG_FILL_STRUCT, meta_draw_op_free(), _MetaDrawOpList::n_ops, NULL, _MetaDrawOpList::ops, and _MetaDrawOpList::refcount.
Referenced by meta_draw_op_free(), meta_frame_style_unref(), and meta_theme_new().
meta_draw_op_list_validate()
gboolean meta_draw_op_list_validate (MetaDrawOpList * op_list, GError ** error)
Definition at line 4632 of file marco/src/ui/theme.c.
References error, FALSE, NULL, and TRUE.
meta_draw_op_new()
MetaDrawOp * meta_draw_op_new (MetaDrawType type)
Definition at line 3154 of file marco/src/ui/theme.c.
References data, META_DRAW_ARC, META_DRAW_CLIP, META_DRAW_GRADIENT, META_DRAW_GTK_ARROW, META_DRAW_GTK_BOX, META_DRAW_GTK_VLINE, META_DRAW_ICON, META_DRAW_IMAGE, META_DRAW_LINE, META_DRAW_OP_LIST, META_DRAW_RECTANGLE, META_DRAW_TILE, META_DRAW_TINT, META_DRAW_TITLE, and op.
meta_draw_spec_free()
void meta_draw_spec_free (MetaDrawSpec * spec)
Definition at line 3121 of file marco/src/ui/theme.c.
References _MetaDrawSpec::n_tokens, and _MetaDrawSpec::tokens.
Referenced by meta_draw_op_free(), and meta_draw_spec_new().
meta_draw_spec_new()
MetaDrawSpec * meta_draw_spec_new (MetaTheme * theme, const char * expr, GError ** error)
Definition at line 3129 of file marco/src/ui/theme.c.
References _MetaDrawSpec::constant, error, meta_draw_spec_free(), meta_theme_replace_constants(), _MetaDrawSpec::n_tokens, NULL, _MetaDrawSpec::tokens, and _MetaDrawSpec::value.
meta_frame_focus_from_string()
MetaFrameFocus meta_frame_focus_from_string (const char * str)
Definition at line 6660 of file marco/src/ui/theme.c.
References META_FRAME_FOCUS_LAST, META_FRAME_FOCUS_NO, and META_FRAME_FOCUS_YES.
meta_frame_focus_to_string()
const char * meta_frame_focus_to_string (MetaFrameFocus focus)
Definition at line 6671 of file marco/src/ui/theme.c.
References META_FRAME_FOCUS_LAST, META_FRAME_FOCUS_NO, and META_FRAME_FOCUS_YES.
Referenced by meta_frame_style_set_validate().
meta_frame_layout_calc_geometry()
void meta_frame_layout_calc_geometry (const MetaFrameLayout * layout, int text_height, MetaFrameFlags flags, int client_width, int client_height, const MetaButtonLayout * button_layout, MetaFrameGeometry * fgeom, MetaTheme * theme)
Definition at line 758 of file marco/src/ui/theme.c.
References _MetaFrameGeometry::above_rect, ADDRESS_OF_BUTTON_RECTS, _MetaFrameGeometry::appmenu_rect, _MetaFrameGeometry::borders, _MetaFrameGeometry::bottom_left_corner_rounded_radius, _MetaFrameGeometry::bottom_right_corner_rounded_radius, _MetaFrameGeometry::bottom_titlebar_edge, _MetaFrameGeometry::button_layout, _MetaButtonSpace::clickable, _MetaFrameGeometry::close_rect, FALSE, _MetaFrameGeometry::height, int(), _MetaFrameBorders::invisible, _MetaFrameGeometry::left_left_background, _MetaFrameGeometry::left_middle_backgrounds, _MetaFrameGeometry::left_right_background, _MetaFrameGeometry::left_single_background, _MetaFrameGeometry::left_titlebar_edge, LENGTH_OF_BUTTON_RECTS, MAX_BUTTONS_PER_CORNER, _MetaFrameGeometry::max_rect, memmove, _MetaFrameGeometry::menu_rect, meta_bug(), META_BUTTON_FUNCTION_LAST, META_BUTTON_SIZING_ASPECT, META_BUTTON_SIZING_FIXED, META_BUTTON_SIZING_LAST, meta_frame_layout_get_borders(), META_FRAME_MAXIMIZED, META_FRAME_SHADED, META_FRAME_TILED_LEFT, META_FRAME_TILED_RIGHT, META_FRAME_TYPE_NORMAL, _MetaFrameGeometry::min_rect, _MetaFrameGeometry::n_left_buttons, _MetaFrameGeometry::n_right_buttons, NULL, _MetaFrameGeometry::right_left_background, _MetaFrameGeometry::right_middle_backgrounds, _MetaFrameGeometry::right_right_background, _MetaFrameGeometry::right_single_background, _MetaFrameGeometry::right_titlebar_edge, _MetaFrameGeometry::shade_rect, _MetaFrameGeometry::stick_rect, _MetaFrameGeometry::title_rect, _MetaFrameGeometry::top_left_corner_rounded_radius, _MetaFrameGeometry::top_right_corner_rounded_radius, _MetaFrameGeometry::top_titlebar_edge, _MetaFrameBorders::total, _MetaButtonSpace::visible, _MetaFrameBorders::visible, and _MetaFrameGeometry::width.
Referenced by meta_theme_calc_geometry(), meta_theme_draw_frame(), and meta_theme_draw_frame_by_name().
meta_frame_layout_copy()
MetaFrameLayout * meta_frame_layout_copy (const MetaFrameLayout * src)
Definition at line 477 of file marco/src/ui/theme.c.
References _MetaFrameLayout::refcount.
meta_frame_layout_get_borders()
void meta_frame_layout_get_borders (const MetaFrameLayout * layout, int text_height, MetaFrameFlags flags, MetaFrameType type, MetaFrameBorders * borders)
Definition at line 514 of file marco/src/ui/theme.c.
References _MetaFrameBorders::invisible, MAX, META_FRAME_ALLOWS_HORIZONTAL_RESIZE, META_FRAME_ALLOWS_VERTICAL_RESIZE, meta_frame_borders_clear(), META_FRAME_FULLSCREEN, META_FRAME_MAXIMIZED, META_FRAME_SHADED, META_FRAME_TILED_LEFT, META_FRAME_TILED_RIGHT, META_FRAME_TYPE_ATTACHED, NULL, _MetaFrameBorders::resize, _MetaFrameBorders::shadow, _MetaFrameBorders::total, and _MetaFrameBorders::visible.
Referenced by meta_frame_layout_calc_geometry(), and meta_theme_get_frame_borders().
meta_frame_layout_new()
MetaFrameLayout * meta_frame_layout_new (void)
Creates a new, empty MetaFrameLayout. The fields will be set to dummy values.
Returns
The newly created MetaFrameLayout.
Definition at line 318 of file marco/src/ui/theme.c.
References META_BUTTON_SIZING_LAST, and TRUE.
meta_frame_layout_ref()
void meta_frame_layout_ref (MetaFrameLayout * layout)
Definition at line 491 of file marco/src/ui/theme.c.
References NULL.
Referenced by meta_theme_insert_layout().
meta_frame_layout_unref()
void meta_frame_layout_unref (MetaFrameLayout * layout)
Definition at line 499 of file marco/src/ui/theme.c.
References DEBUG_FILL_STRUCT, and NULL.
Referenced by meta_frame_style_unref(), and meta_theme_new().
meta_frame_layout_validate()
gboolean meta_frame_layout_validate (const MetaFrameLayout * layout, GError ** error)
Definition at line 427 of file marco/src/ui/theme.c.
References _, CHECK_GEOMETRY_BORDER, CHECK_GEOMETRY_VALUE, error, FALSE, META_BUTTON_SIZING_ASPECT, META_BUTTON_SIZING_FIXED, META_BUTTON_SIZING_LAST, META_THEME_ERROR, META_THEME_ERROR_FRAME_GEOMETRY, NULL, and TRUE.
meta_frame_piece_from_string()
MetaFramePiece meta_frame_piece_from_string (const char * str)
Definition at line 6507 of file marco/src/ui/theme.c.
References META_FRAME_PIECE_BOTTOM_EDGE, META_FRAME_PIECE_BOTTOM_TITLEBAR_EDGE, META_FRAME_PIECE_ENTIRE_BACKGROUND, META_FRAME_PIECE_LAST, META_FRAME_PIECE_LEFT_EDGE, META_FRAME_PIECE_LEFT_TITLEBAR_EDGE, META_FRAME_PIECE_OVERLAY, META_FRAME_PIECE_RIGHT_EDGE, META_FRAME_PIECE_RIGHT_TITLEBAR_EDGE, META_FRAME_PIECE_TITLE, META_FRAME_PIECE_TITLEBAR, META_FRAME_PIECE_TITLEBAR_MIDDLE, and META_FRAME_PIECE_TOP_TITLEBAR_EDGE.
meta_frame_piece_to_string()
const char * meta_frame_piece_to_string (MetaFramePiece piece)
Definition at line 6538 of file marco/src/ui/theme.c.
References META_FRAME_PIECE_BOTTOM_EDGE, META_FRAME_PIECE_BOTTOM_TITLEBAR_EDGE, META_FRAME_PIECE_ENTIRE_BACKGROUND, META_FRAME_PIECE_LAST, META_FRAME_PIECE_LEFT_EDGE, META_FRAME_PIECE_LEFT_TITLEBAR_EDGE, META_FRAME_PIECE_OVERLAY, META_FRAME_PIECE_RIGHT_EDGE, META_FRAME_PIECE_RIGHT_TITLEBAR_EDGE, META_FRAME_PIECE_TITLE, META_FRAME_PIECE_TITLEBAR, META_FRAME_PIECE_TITLEBAR_MIDDLE, and META_FRAME_PIECE_TOP_TITLEBAR_EDGE.
meta_frame_resize_from_string()
MetaFrameResize meta_frame_resize_from_string (const char * str)
Definition at line 6625 of file marco/src/ui/theme.c.
References META_FRAME_RESIZE_BOTH, META_FRAME_RESIZE_HORIZONTAL, META_FRAME_RESIZE_LAST, META_FRAME_RESIZE_NONE, and META_FRAME_RESIZE_VERTICAL.
meta_frame_resize_to_string()
const char * meta_frame_resize_to_string (MetaFrameResize resize)
Definition at line 6640 of file marco/src/ui/theme.c.
References META_FRAME_RESIZE_BOTH, META_FRAME_RESIZE_HORIZONTAL, META_FRAME_RESIZE_LAST, META_FRAME_RESIZE_NONE, and META_FRAME_RESIZE_VERTICAL.
Referenced by meta_frame_style_set_validate().
meta_frame_state_from_string()
MetaFrameState meta_frame_state_from_string (const char * str)
Definition at line 6574 of file marco/src/ui/theme.c.
References META_FRAME_STATE_LAST, META_FRAME_STATE_MAXIMIZED, META_FRAME_STATE_MAXIMIZED_AND_SHADED, META_FRAME_STATE_NORMAL, META_FRAME_STATE_SHADED, META_FRAME_STATE_TILED_LEFT, META_FRAME_STATE_TILED_LEFT_AND_SHADED, META_FRAME_STATE_TILED_RIGHT, and META_FRAME_STATE_TILED_RIGHT_AND_SHADED.
meta_frame_state_to_string()
const char * meta_frame_state_to_string (MetaFrameState state)
Definition at line 6597 of file marco/src/ui/theme.c.
References META_FRAME_STATE_LAST, META_FRAME_STATE_MAXIMIZED, META_FRAME_STATE_MAXIMIZED_AND_SHADED, META_FRAME_STATE_NORMAL, META_FRAME_STATE_SHADED, META_FRAME_STATE_TILED_LEFT, META_FRAME_STATE_TILED_LEFT_AND_SHADED, META_FRAME_STATE_TILED_RIGHT, and META_FRAME_STATE_TILED_RIGHT_AND_SHADED.
Referenced by meta_frame_style_set_validate().
meta_frame_style_draw()
void meta_frame_style_draw (MetaFrameStyle * style, GtkWidget * widget, cairo_t * cr, const MetaFrameGeometry * fgeom, int client_width, int client_height, PangoLayout * title_layout, int text_height, MetaButtonState button_states[META_BUTTON_TYPE_LAST], GdkPixbuf * mini_icon, GdkPixbuf * icon)
Definition at line 5241 of file marco/src/ui/theme.c.
References META_BUTTON_TYPE_LAST, and meta_frame_style_draw_with_style().
Referenced by meta_theme_draw_frame_by_name().
meta_frame_style_draw_with_style()
void meta_frame_style_draw_with_style (MetaFrameStyle * style, GtkStyleContext * style_gtk, cairo_t * cr, const MetaFrameGeometry * fgeom, int client_width, int client_height, PangoLayout * title_layout, int text_height, MetaButtonState button_states[META_BUTTON_TYPE_LAST], GdkPixbuf * mini_icon, GdkPixbuf * icon)
Definition at line 5001 of file marco/src/ui/theme.c.
References _MetaFrameGeometry::borders, _MetaFrameGeometry::bottom_titlebar_edge, _MetaDrawInfo::fgeom, _MetaFrameGeometry::height, _MetaDrawInfo::icon, _MetaFrameBorders::invisible, _MetaFrameGeometry::left_titlebar_edge, MAX_MIDDLE_BACKGROUNDS, META_BUTTON_TYPE_LAST, META_BUTTON_TYPE_LEFT_MIDDLE_BACKGROUND, META_BUTTON_TYPE_RIGHT_MIDDLE_BACKGROUND, meta_draw_op_list_draw_with_style(), META_FRAME_PIECE_BOTTOM_EDGE, META_FRAME_PIECE_BOTTOM_TITLEBAR_EDGE, META_FRAME_PIECE_ENTIRE_BACKGROUND, META_FRAME_PIECE_LAST, META_FRAME_PIECE_LEFT_EDGE, META_FRAME_PIECE_LEFT_TITLEBAR_EDGE, META_FRAME_PIECE_OVERLAY, META_FRAME_PIECE_RIGHT_EDGE, META_FRAME_PIECE_RIGHT_TITLEBAR_EDGE, META_FRAME_PIECE_TITLE, META_FRAME_PIECE_TITLEBAR, META_FRAME_PIECE_TITLEBAR_MIDDLE, META_FRAME_PIECE_TOP_TITLEBAR_EDGE, meta_rect(), _MetaDrawInfo::mini_icon, NULL, _MetaFrameStyle::parent, _MetaFrameStyle::pieces, _MetaFrameGeometry::right_titlebar_edge, _MetaDrawInfo::title_layout, _MetaDrawInfo::title_layout_height, _MetaDrawInfo::title_layout_width, _MetaFrameGeometry::title_rect, _MetaFrameGeometry::top_titlebar_edge, _MetaFrameBorders::visible, and _MetaFrameGeometry::width.
Referenced by meta_frame_style_draw(), and meta_theme_draw_frame().
meta_frame_style_new()
MetaFrameStyle * meta_frame_style_new (MetaFrameStyle * parent)
Constructor for a MetaFrameStyle.
Parameters
parent The parent style. Data not filled in here will be looked for in the parent style, and in its parent style, and so on.
Returns
The newly-constructed style.
Definition at line 4689 of file marco/src/ui/theme.c.
References meta_frame_style_ref(), _MetaFrameStyle::parent, _MetaFrameStyle::refcount, and _MetaFrameStyle::window_background_alpha.
meta_frame_style_ref()
void meta_frame_style_ref (MetaFrameStyle * style)
Increases the reference count of a frame style. If the style is NULL, this is a no-op.
Parameters
style The style.
Definition at line 4714 of file marco/src/ui/theme.c.
References NULL, and _MetaFrameStyle::refcount.
Referenced by meta_frame_style_new(), and meta_theme_insert_style().
meta_frame_style_set_new()
MetaFrameStyleSet * meta_frame_style_set_new (MetaFrameStyleSet * parent)
Definition at line 5262 of file marco/src/ui/theme.c.
References meta_frame_style_set_ref(), _MetaFrameStyleSet::parent, and _MetaFrameStyleSet::refcount.
meta_frame_style_set_ref()
void meta_frame_style_set_ref (MetaFrameStyleSet * style_set)
Definition at line 5288 of file marco/src/ui/theme.c.
References NULL, and _MetaFrameStyleSet::refcount.
Referenced by meta_frame_style_set_new(), and meta_theme_insert_style_set().
meta_frame_style_set_unref()
void meta_frame_style_set_unref (MetaFrameStyleSet * style_set)
Definition at line 5296 of file marco/src/ui/theme.c.
References DEBUG_FILL_STRUCT, _MetaFrameStyleSet::maximized_and_shaded_styles, _MetaFrameStyleSet::maximized_styles, META_FRAME_RESIZE_LAST, meta_frame_style_set_unref(), _MetaFrameStyleSet::normal_styles, NULL, _MetaFrameStyleSet::parent, _MetaFrameStyleSet::refcount, _MetaFrameStyleSet::shaded_styles, _MetaFrameStyleSet::tiled_left_and_shaded_styles, _MetaFrameStyleSet::tiled_left_styles, _MetaFrameStyleSet::tiled_right_and_shaded_styles, and _MetaFrameStyleSet::tiled_right_styles.
Referenced by meta_frame_style_set_unref(), meta_theme_free(), and meta_theme_new().
meta_frame_style_set_validate()
gboolean meta_frame_style_set_validate (MetaFrameStyleSet * style_set, GError ** error)
Definition at line 5445 of file marco/src/ui/theme.c.
References _, error, FALSE, META_FRAME_FOCUS_LAST, meta_frame_focus_to_string(), META_FRAME_RESIZE_LAST, meta_frame_resize_to_string(), META_FRAME_STATE_MAXIMIZED, META_FRAME_STATE_MAXIMIZED_AND_SHADED, META_FRAME_STATE_NORMAL, META_FRAME_STATE_SHADED, meta_frame_state_to_string(), META_THEME_ERROR, META_THEME_ERROR_FAILED, NULL, and TRUE.
meta_frame_style_unref()
void meta_frame_style_unref (MetaFrameStyle * style)
Definition at line 4733 of file marco/src/ui/theme.c.
References _MetaFrameStyle::buttons, DEBUG_FILL_STRUCT, _MetaFrameStyle::layout, meta_color_spec_free(), meta_draw_op_list_unref(), meta_frame_layout_unref(), META_FRAME_PIECE_LAST, meta_frame_style_unref(), NULL, _MetaFrameStyle::parent, _MetaFrameStyle::pieces, _MetaFrameStyle::refcount, and _MetaFrameStyle::window_background_color.
Referenced by meta_frame_style_unref(), and meta_theme_new().
meta_frame_style_validate()
gboolean meta_frame_style_validate (MetaFrameStyle * style, guint current_theme_version, GError ** error)
Definition at line 4876 of file marco/src/ui/theme.c.
References _, error, FALSE, _MetaFrameStyle::layout, META_BUTTON_STATE_LAST, meta_button_state_to_string(), META_BUTTON_TYPE_CLOSE, META_BUTTON_TYPE_LAST, meta_button_type_to_string(), meta_theme_earliest_version_with_button(), META_THEME_ERROR, META_THEME_ERROR_FAILED, NULL, and TRUE.
meta_frame_type_from_string()
MetaFrameType meta_frame_type_from_string (const char * str)
Definition at line 6687 of file marco/src/ui/theme.c.
References META_FRAME_TYPE_ATTACHED, META_FRAME_TYPE_BORDER, META_FRAME_TYPE_DIALOG, META_FRAME_TYPE_LAST, META_FRAME_TYPE_MENU, META_FRAME_TYPE_MODAL_DIALOG, META_FRAME_TYPE_NORMAL, and META_FRAME_TYPE_UTILITY.
meta_frame_type_to_string()
const char * meta_frame_type_to_string (MetaFrameType type)
Definition at line 6712 of file marco/src/ui/theme.c.
References META_FRAME_TYPE_ATTACHED, META_FRAME_TYPE_BORDER, META_FRAME_TYPE_DIALOG, META_FRAME_TYPE_LAST, META_FRAME_TYPE_MENU, META_FRAME_TYPE_MODAL_DIALOG, META_FRAME_TYPE_NORMAL, and META_FRAME_TYPE_UTILITY.
Referenced by meta_theme_validate().
meta_gradient_spec_free()
void meta_gradient_spec_free (MetaGradientSpec * desc)
Definition at line 1221 of file marco/src/ui/theme.c.
References _MetaGradientSpec::color_specs, DEBUG_FILL_STRUCT, and NULL.
Referenced by meta_draw_op_free().
meta_gradient_spec_new()
MetaGradientSpec * meta_gradient_spec_new (MetaGradientType type)
Definition at line 1138 of file marco/src/ui/theme.c.
References _MetaGradientSpec::color_specs, NULL, and _MetaGradientSpec::type.
meta_gradient_spec_render()
void meta_gradient_spec_render (const MetaGradientSpec * spec, const MetaAlphaGradientSpec * alpha_spec, cairo_t * cr, GtkStyleContext * context, gint x, gint y, gint width, gint height)
Definition at line 1233 of file marco/src/ui/theme.c.
References NULL.
meta_gradient_spec_validate()
gboolean meta_gradient_spec_validate (MetaGradientSpec * spec, GError ** error)
Definition at line 1263 of file marco/src/ui/theme.c.
References _, _MetaGradientSpec::color_specs, error, FALSE, META_THEME_ERROR, META_THEME_ERROR_FAILED, NULL, and TRUE.
meta_gradient_type_from_string()
MetaGradientType meta_gradient_type_from_string (const char * str)
Definition at line 6742 of file marco/src/ui/theme.c.
References META_GRADIENT_DIAGONAL, META_GRADIENT_HORIZONTAL, META_GRADIENT_LAST, and META_GRADIENT_VERTICAL.
meta_gradient_type_to_string()
const char * meta_gradient_type_to_string (MetaGradientType type)
Definition at line 6755 of file marco/src/ui/theme.c.
References META_GRADIENT_DIAGONAL, META_GRADIENT_HORIZONTAL, META_GRADIENT_LAST, and META_GRADIENT_VERTICAL.
meta_gtk_arrow_from_string()
GtkArrowType meta_gtk_arrow_from_string (const char * str)
Definition at line 6833 of file marco/src/ui/theme.c.
meta_gtk_arrow_to_string()
const char * meta_gtk_arrow_to_string (GtkArrowType arrow)
Definition at line 6850 of file marco/src/ui/theme.c.
meta_gtk_shadow_from_string()
GtkShadowType meta_gtk_shadow_from_string (const char * str)
Definition at line 6796 of file marco/src/ui/theme.c.
meta_gtk_shadow_to_string()
const char * meta_gtk_shadow_to_string (GtkShadowType shadow)
Definition at line 6813 of file marco/src/ui/theme.c.
meta_gtk_state_from_string()
GtkStateFlags meta_gtk_state_from_string (const char * str)
Definition at line 6773 of file marco/src/ui/theme.c.
Referenced by meta_color_spec_new_from_string().
meta_gtk_style_get_dark_color()
void meta_gtk_style_get_dark_color (GtkStyleContext * style, GtkStateFlags state, GdkRGBA * color)
Definition at line 1783 of file marco/src/ui/theme.c.
References DARKNESS_MULT.
Referenced by wnck_draw_workspace().
meta_gtk_style_get_light_color()
void meta_gtk_style_get_light_color (GtkStyleContext * style, GtkStateFlags state, GdkRGBA * color)
Definition at line 1774 of file marco/src/ui/theme.c.
References LIGHTNESS_MULT.
meta_gtk_widget_get_font_desc()
PangoFontDescription * meta_gtk_widget_get_font_desc (GtkWidget * widget, double scale, const PangoFontDescription * override)
Definition at line 6278 of file marco/src/ui/theme.c.
References MAX, NULL, and TRUE.
meta_image_fill_type_from_string()
MetaImageFillType meta_image_fill_type_from_string (const char * str)
Returns a fill_type from a string. The inverse of meta_image_fill_type_to_string().
Parameters
str a string representing a fill_type
Returns
the fill_type, or -1 if it represents no fill_type.
Definition at line 6877 of file marco/src/ui/theme.c.
References META_IMAGE_FILL_SCALE, and META_IMAGE_FILL_TILE.
meta_image_fill_type_to_string()
const char * meta_image_fill_type_to_string (MetaImageFillType fill_type)
Returns a string representation of a fill_type. The inverse of meta_image_fill_type_from_string().
Parameters
fill_type the fill type
Returns
a string representing that type
Definition at line 6895 of file marco/src/ui/theme.c.
References META_IMAGE_FILL_SCALE, and META_IMAGE_FILL_TILE.
meta_pango_font_desc_get_text_height()
int meta_pango_font_desc_get_text_height (const PangoFontDescription * font_desc, PangoContext * context)
Returns the height of the letters in a particular font.
Parameters
font_desc the font
context the context of the font
Returns
the height of the letters
Definition at line 6307 of file marco/src/ui/theme.c.
Referenced by meta_ui_theme_get_frame_borders().
meta_parse_position_expression()
gboolean meta_parse_position_expression (MetaDrawSpec * spec, const MetaPositionExprEnv * env, int * x_return, int * y_return, GError ** err)
Definition at line 2947 of file marco/src/ui/theme.c.
References _MetaDrawSpec::constant, FALSE, NULL, _MetaPositionExprEnv::rect, TRUE, _MetaDrawSpec::value, _MetaRectangle::x, and _MetaRectangle::y.
meta_parse_size_expression()
gboolean meta_parse_size_expression (MetaDrawSpec * spec, const MetaPositionExprEnv * env, int * val_return, GError ** err)
Definition at line 2983 of file marco/src/ui/theme.c.
References _MetaDrawSpec::constant, FALSE, MAX, NULL, TRUE, and _MetaDrawSpec::value.
meta_theme_calc_geometry()
void meta_theme_calc_geometry (MetaTheme * theme, MetaFrameType type, int text_height, MetaFrameFlags flags, int client_width, int client_height, const MetaButtonLayout * button_layout, MetaFrameGeometry * fgeom)
Definition at line 5984 of file marco/src/ui/theme.c.
References _MetaFrameStyle::layout, meta_frame_layout_calc_geometry(), META_FRAME_TYPE_LAST, and NULL.
meta_theme_define_color_constant()
gboolean meta_theme_define_color_constant (MetaTheme * theme, const char * name, const char * value, GError ** error)
Definition at line 6208 of file marco/src/ui/theme.c.
References _, _MetaTheme::color_constants, error, FALSE, META_THEME_ERROR, META_THEME_ERROR_FAILED, name, NULL, and TRUE.
meta_theme_define_float_constant()
gboolean meta_theme_define_float_constant (MetaTheme * theme, const char * name, double value, GError ** error)
Definition at line 6143 of file marco/src/ui/theme.c.
References _, error, FALSE, _MetaTheme::float_constants, META_THEME_ERROR, META_THEME_ERROR_FAILED, name, NULL, and TRUE.
meta_theme_define_int_constant()
gboolean meta_theme_define_int_constant (MetaTheme * theme, const char * name, int value, GError ** error)
Definition at line 6083 of file marco/src/ui/theme.c.
References _, error, FALSE, _MetaTheme::integer_constants, META_THEME_ERROR, META_THEME_ERROR_FAILED, name, NULL, and TRUE.
meta_theme_draw_frame()
void meta_theme_draw_frame (MetaTheme * theme, GtkStyleContext * style_gtk, cairo_t * cr, MetaFrameType type, MetaFrameFlags flags, int client_width, int client_height, PangoLayout * title_layout, int text_height, const MetaButtonLayout * button_layout, MetaButtonState button_states[META_BUTTON_TYPE_LAST], GdkPixbuf * mini_icon, GdkPixbuf * icon)
Definition at line 5870 of file marco/src/ui/theme.c.
References _MetaFrameStyle::layout, META_BUTTON_TYPE_LAST, meta_frame_layout_calc_geometry(), meta_frame_style_draw_with_style(), META_FRAME_TYPE_LAST, and NULL.
meta_theme_draw_frame_by_name()
void meta_theme_draw_frame_by_name (MetaTheme * theme, GtkWidget * widget, cairo_t * cr, const gchar * style_name, MetaFrameFlags flags, int client_width, int client_height, PangoLayout * title_layout, int text_height, const MetaButtonLayout * button_layout, MetaButtonState button_states[META_BUTTON_TYPE_LAST], GdkPixbuf * mini_icon, GdkPixbuf * icon)
Definition at line 5915 of file marco/src/ui/theme.c.
References _MetaFrameStyle::layout, META_BUTTON_TYPE_LAST, meta_frame_layout_calc_geometry(), meta_frame_style_draw(), meta_theme_lookup_style(), and NULL.
meta_theme_earliest_version_with_button()
guint meta_theme_earliest_version_with_button (MetaButtonType type)
Returns the earliest version of the theme format which required support for a particular button. (For example, "shade" first appeared in v2, and "close" in v1.)
Parameters
type the button type
Returns
the number of the theme format
Definition at line 7334 of file marco/src/ui/theme.c.
References META_BUTTON_TYPE_ABOVE, META_BUTTON_TYPE_APPMENU, META_BUTTON_TYPE_CLOSE, META_BUTTON_TYPE_LEFT_LEFT_BACKGROUND, META_BUTTON_TYPE_LEFT_MIDDLE_BACKGROUND, META_BUTTON_TYPE_LEFT_RIGHT_BACKGROUND, META_BUTTON_TYPE_LEFT_SINGLE_BACKGROUND, META_BUTTON_TYPE_MAXIMIZE, META_BUTTON_TYPE_MENU, META_BUTTON_TYPE_MINIMIZE, META_BUTTON_TYPE_RIGHT_LEFT_BACKGROUND, META_BUTTON_TYPE_RIGHT_MIDDLE_BACKGROUND, META_BUTTON_TYPE_RIGHT_RIGHT_BACKGROUND, META_BUTTON_TYPE_RIGHT_SINGLE_BACKGROUND, META_BUTTON_TYPE_SHADE, META_BUTTON_TYPE_STICK, META_BUTTON_TYPE_UNABOVE, META_BUTTON_TYPE_UNSHADE, META_BUTTON_TYPE_UNSTICK, and meta_warning().
Referenced by meta_frame_style_validate().
meta_theme_free()
void meta_theme_free (MetaTheme * theme)
Definition at line 5576 of file marco/src/ui/theme.c.
References _MetaTheme::author, _MetaTheme::copyright, _MetaTheme::date, DEBUG_FILL_STRUCT, _MetaTheme::description, _MetaTheme::dirname, _MetaTheme::draw_op_lists_by_name, _MetaTheme::filename, _MetaTheme::images_by_filename, _MetaTheme::integer_constants, _MetaTheme::layouts_by_name, meta_frame_style_set_unref(), META_FRAME_TYPE_LAST, _MetaTheme::name, NULL, _MetaTheme::readable_name, _MetaTheme::style_sets_by_name, _MetaTheme::style_sets_by_type, and _MetaTheme::styles_by_name.
Referenced by meta_theme_set_current().
meta_theme_get_current()
MetaTheme * meta_theme_get_current (void)
Definition at line 5478 of file marco/src/ui/theme.c.
Referenced by meta_ui_have_a_theme(), and meta_ui_theme_get_frame_borders().
meta_theme_get_frame_borders()
void meta_theme_get_frame_borders (MetaTheme * theme, MetaFrameType type, int text_height, MetaFrameFlags flags, MetaFrameBorders * borders)
Definition at line 5958 of file marco/src/ui/theme.c.
References _MetaFrameStyle::layout, meta_frame_borders_clear(), meta_frame_layout_get_borders(), META_FRAME_TYPE_LAST, and NULL.
Referenced by meta_ui_theme_get_frame_borders().
meta_theme_get_frame_style()
MetaFrameStyle * meta_theme_get_frame_style (MetaTheme * theme, MetaFrameType type, MetaFrameFlags flags)
Definition at line 5838 of file marco/src/ui/theme.c.
References META_FRAME_TYPE_LAST, and NULL.
Referenced by meta_preview_get_clip_region().
meta_theme_get_title_scale()
double meta_theme_get_title_scale (MetaTheme * theme, MetaFrameType type, MetaFrameFlags flags)
Definition at line 5852 of file marco/src/ui/theme.c.
References _MetaFrameStyle::layout, META_FRAME_TYPE_LAST, NULL, and _MetaFrameLayout::title_scale.
meta_theme_insert_draw_op_list()
void meta_theme_insert_draw_op_list (MetaTheme * theme, const char * name, MetaDrawOpList * op_list)
Definition at line 6036 of file marco/src/ui/theme.c.
References _MetaTheme::draw_op_lists_by_name, meta_draw_op_list_ref(), and name.
meta_theme_insert_layout()
void meta_theme_insert_layout (MetaTheme * theme, const char * name, MetaFrameLayout * layout)
Definition at line 6020 of file marco/src/ui/theme.c.
References _MetaTheme::layouts_by_name, meta_frame_layout_ref(), and name.
meta_theme_insert_style()
void meta_theme_insert_style (MetaTheme * theme, const char * name, MetaFrameStyle * style)
Definition at line 6052 of file marco/src/ui/theme.c.
References meta_frame_style_ref(), name, and _MetaTheme::styles_by_name.
meta_theme_insert_style_set()
void meta_theme_insert_style_set (MetaTheme * theme, const char * name, MetaFrameStyleSet * style_set)
Definition at line 6068 of file marco/src/ui/theme.c.
References meta_frame_style_set_ref(), name, and _MetaTheme::style_sets_by_name.
meta_theme_load_image()
GdkPixbuf * meta_theme_load_image (MetaTheme * theme, const char * filename, guint size_of_theme_icons, GError ** error)
Definition at line 5681 of file marco/src/ui/theme.c.
References _MetaTheme::dirname, error, _MetaTheme::images_by_filename, META_THEME_ALLOWS, META_THEME_IMAGES_FROM_ICON_THEMES, and NULL.
meta_theme_lookup_color_constant()
gboolean meta_theme_lookup_color_constant (MetaTheme * theme, const char * name, char ** value)
Looks up a colour constant.
Parameters
theme the theme containing the constant
name the name of the constant
value [out] the string representation of the colour, or NULL if it doesn't exist
Returns
TRUE if it exists, FALSE otherwise
Definition at line 6253 of file marco/src/ui/theme.c.
References _MetaTheme::color_constants, FALSE, name, NULL, and TRUE.
meta_theme_lookup_draw_op_list()
MetaDrawOpList * meta_theme_lookup_draw_op_list (MetaTheme * theme, const char * name)
Definition at line 6029 of file marco/src/ui/theme.c.
References _MetaTheme::draw_op_lists_by_name, and name.
meta_theme_lookup_float_constant()
gboolean meta_theme_lookup_float_constant (MetaTheme * theme, const char * name, double * value)
Definition at line 6183 of file marco/src/ui/theme.c.
References FALSE, _MetaTheme::float_constants, name, NULL, and TRUE.
Referenced by meta_theme_replace_constants().
meta_theme_lookup_int_constant()
gboolean meta_theme_lookup_int_constant (MetaTheme * theme, const char * name, int * value)
Definition at line 6119 of file marco/src/ui/theme.c.
References FALSE, _MetaTheme::integer_constants, name, NULL, and TRUE.
Referenced by meta_theme_replace_constants().
meta_theme_lookup_layout()
MetaFrameLayout * meta_theme_lookup_layout (MetaTheme * theme, const char * name)
Definition at line 6013 of file marco/src/ui/theme.c.
References _MetaTheme::layouts_by_name, and name.
meta_theme_lookup_style()
MetaFrameStyle * meta_theme_lookup_style (MetaTheme * theme, const char * name)
Definition at line 6045 of file marco/src/ui/theme.c.
References name, and _MetaTheme::styles_by_name.
Referenced by meta_theme_draw_frame_by_name().
meta_theme_lookup_style_set()
MetaFrameStyleSet * meta_theme_lookup_style_set (MetaTheme * theme, const char * name)
Definition at line 6061 of file marco/src/ui/theme.c.
References name, and _MetaTheme::style_sets_by_name.
meta_theme_new()
MetaTheme * meta_theme_new (void)
Definition at line 5518 of file marco/src/ui/theme.c.
References _MetaTheme::draw_op_lists_by_name, _MetaTheme::images_by_filename, _MetaTheme::layouts_by_name, meta_draw_op_list_unref(), meta_frame_layout_unref(), meta_frame_style_set_unref(), meta_frame_style_unref(), _MetaTheme::quark_bottom_height, _MetaTheme::quark_frame_x_center, _MetaTheme::quark_frame_y_center, _MetaTheme::quark_height, _MetaTheme::quark_icon_height, _MetaTheme::quark_icon_width, _MetaTheme::quark_left_width, _MetaTheme::quark_mini_icon_height, _MetaTheme::quark_mini_icon_width, _MetaTheme::quark_object_height, _MetaTheme::quark_object_width, _MetaTheme::quark_right_width, _MetaTheme::quark_title_height, _MetaTheme::quark_title_width, _MetaTheme::quark_top_height, _MetaTheme::quark_width, _MetaTheme::style_sets_by_name, and _MetaTheme::styles_by_name.
meta_theme_replace_constants()
gboolean meta_theme_replace_constants (MetaTheme * theme, PosToken * tokens, int n_tokens, GError ** err)
Definition at line 3016 of file marco/src/ui/theme.c.
References PosToken::d, FALSE, PosToken::i, meta_theme_lookup_float_constant(), meta_theme_lookup_int_constant(), PosToken::name, PosToken::name_quark, POS_TOKEN_DOUBLE, POS_TOKEN_INT, POS_TOKEN_VARIABLE, TRUE, PosToken::type, PosToken::v, and PosToken::val.
Referenced by meta_draw_spec_new().
meta_theme_set_current()
void meta_theme_set_current (const char * name, gboolean force_reload)
Definition at line 5484 of file marco/src/ui/theme.c.
References _, META_DEBUG_THEMES, meta_theme_free(), meta_theme_load(), meta_warning(), name, and NULL.
Referenced by meta_ui_set_current_theme().
meta_theme_validate()
gboolean meta_theme_validate (MetaTheme * theme, GError ** error)
Definition at line 5615 of file marco/src/ui/theme.c.
References _, _MetaTheme::author, _MetaTheme::copyright, _MetaTheme::date, _MetaTheme::description, error, FALSE, int(), META_FRAME_TYPE_ATTACHED, META_FRAME_TYPE_LAST, meta_frame_type_to_string(), META_THEME_ERROR, META_THEME_ERROR_FAILED, _MetaTheme::name, NULL, _MetaTheme::readable_name, _MetaTheme::style_sets_by_type, and TRUE.