MATE Desktop Environment: theme-parser.h File Reference
theme-parser.h File Reference
#include "theme.h"
Functions
MetaTheme * meta_theme_load (const char *theme_name, GError **err)
Function Documentation
meta_theme_load()
MetaTheme * meta_theme_load (const char * theme_name, GError ** err)
Definition at line 4339 of file theme-parser.c.
References _, error, meta_is_debugging(), META_THEME_ERROR, META_THEME_ERROR_FAILED, NULL, THEME_MAJOR_VERSION, and THEME_SUBDIR.
Referenced by main(), and meta_theme_set_current().