MATE Desktop Environment: time-zone.h File Reference
time-zone.h File Reference
#include "time-share.h"
Classes
struct TzDB
struct TzLocation
struct TzInfo
Macros
#define TZ_DATA_FILE "/usr/share/zoneinfo/zone.tab"
Typedefs
typedef struct TzDB TzDB
typedef struct TzLocation TzLocation
typedef struct TzInfo TzInfo
Functions
TzDB * tz_load_db (void)
void SetupTimezoneDialog (TimeAdmin *ta)
void RunTimeZoneDialog (GtkButton *button, gpointer data)
void TimeZoneDateBaseFree (TzDB *db)
GPtrArray * tz_get_locations (TzDB *db)
TzInfo * tz_info_from_location (TzLocation *loc)
glong tz_location_get_utc_offset (TzLocation *loc)
char * tz_info_get_clean_name (TzDB *tz_db, const char *tz)
void tz_info_free (TzInfo *tzinfo)
Macro Definition Documentation
TZ_DATA_FILE
#define TZ_DATA_FILE "/usr/share/zoneinfo/zone.tab"
Definition at line 33 of file time-zone.h.
Typedef Documentation
TzDB
typedef struct TzDB TzDB
TzInfo
typedef struct TzInfo TzInfo
TzLocation
typedef struct TzLocation TzLocation
Function Documentation
RunTimeZoneDialog()
void RunTimeZoneDialog (GtkButton * button, gpointer data)
Definition at line 689 of file time-zone.c.
References data, and TimeAdmin::dialog.
SetupTimezoneDialog()
void SetupTimezoneDialog (TimeAdmin * ta)
Definition at line 470 of file time-zone.c.
References _, TimeAdmin::dialog, FALSE, TimeAdmin::map, NULL, TimeAdmin::SearchBar, TimeAdmin::TimezoneEntry, TRUE, TimeAdmin::TZclose, and TimeAdmin::TZconfire.
TimeZoneDateBaseFree()
void TimeZoneDateBaseFree (TzDB * db)
Definition at line 706 of file time-zone.c.
References TzDB::backward, TzDB::locations, NULL, and TRUE.
tz_get_locations()
GPtrArray * tz_get_locations (TzDB * db)
Definition at line 714 of file time-zone.c.
References TzDB::locations.
Referenced by timezone_map_set_timezone().
tz_info_free()
void tz_info_free (TzInfo * tzinfo)
Definition at line 533 of file time-zone.c.
References NULL, TzInfo::tzname_daylight, and TzInfo::tzname_normal.
Referenced by tz_location_get_utc_offset().
tz_info_from_location()
TzInfo * tz_info_from_location (TzLocation * loc)
Definition at line 631 of file time-zone.c.
References TzInfo::daylight, NULL, TzInfo::tzname_daylight, TzInfo::tzname_normal, TzInfo::utc_offset, and TzLocation::zone.
Referenced by tz_location_get_utc_offset().
tz_info_get_clean_name()
char * tz_info_get_clean_name (TzDB * tz_db, const char * tz)
Definition at line 587 of file time-zone.c.
References aliases, TzDB::backward, FALSE, NULL, orig, and TRUE.
Referenced by timezone_map_set_timezone().
tz_load_db()
TzDB * tz_load_db (void)
Definition at line 155 of file time-zone.c.
References TzLocation::comment, TzLocation::country, TzLocation::latitude, TzDB::locations, TzLocation::longitude, NULL, and TzLocation::zone.
tz_location_get_utc_offset()
glong tz_location_get_utc_offset (TzLocation * loc)
Definition at line 677 of file time-zone.c.
References tz_info_free(), tz_info_from_location(), and TzInfo::utc_offset.