MATE Desktop Environment: time-share.h File Reference
time-share.h File Reference
#include <gtk/gtk.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <sys/time.h>
#include <gio/gio.h>
Classes
struct TimeAdmin
Functions
int ErrorMessage (const char *Title, const char *Msg)
void SetTooltip (GtkWidget *box, gboolean mode)
Variables
int TimeoutFlag
Function Documentation
ErrorMessage()
int ErrorMessage (const char * Title, const char * Msg)
Definition at line 26 of file time-share.c.
References NULL.
Referenced by ChangeNtpSync(), GetNtpState(), and SetTimeZone().
SetTooltip()
void SetTooltip (GtkWidget * box, gboolean mode)
Definition at line 47 of file time-share.c.
References _, and NULL.
Variable Documentation
TimeoutFlag
int TimeoutFlag extern
Definition at line 24 of file time-share.c.