MATE Desktop Environment: time-tool.c File Reference
time-tool.c File Reference
#include "time-tool.h"
#include <glib/gi18n.h>
Functions
struct tm * GetCurrentTime (void)
void ta_refresh_time (TimeAdmin *ta, struct tm *LocalTime)
void ta_refresh_date (TimeAdmin *ta, struct tm *LocalTime)
void Update_Clock_Start (TimeAdmin *ta)
void Update_Clock_Stop (TimeAdmin *ta)
gboolean GetNtpState (TimeAdmin *ta)
const gchar * GetTimeZone (TimeAdmin *ta)
void SetTimeZone (GDBusProxy *proxy, const char *zone)
gboolean ChangeNtpSync (GtkSwitch *widget, gboolean state, gpointer data)
void SaveModifyTime (GtkButton *button, gpointer data)
Function Documentation
ChangeNtpSync()
gboolean ChangeNtpSync (GtkSwitch * widget, gboolean state, gpointer data)
Definition at line 214 of file time-tool.c.
References _, data, error, ErrorMessage(), FALSE, TimeAdmin::NtpState, NULL, TimeAdmin::proxy, TRUE, and Update_Clock_Start().
GetCurrentTime()
struct tm * GetCurrentTime (void)
Definition at line 24 of file time-tool.c.
References NULL.
Referenced by SaveModifyTime().
GetNtpState()
gboolean GetNtpState (TimeAdmin * ta)
Definition at line 98 of file time-tool.c.
References _, TimeAdmin::Connection, error, ErrorMessage(), FALSE, NULL, and proxy.
GetTimeZone()
const gchar * GetTimeZone (TimeAdmin * ta)
Definition at line 141 of file time-tool.c.
References TimeAdmin::Connection, error, NULL, and proxy.
SaveModifyTime()
void SaveModifyTime (GtkButton * button, gpointer data)
Definition at line 285 of file time-tool.c.
References data, GetCurrentTime(), TimeAdmin::proxy, ta_refresh_date(), and ta_refresh_time().
SetTimeZone()
void SetTimeZone (GDBusProxy * proxy, const char * zone)
Definition at line 183 of file time-tool.c.
References _, error, ErrorMessage(), NULL, and proxy.
ta_refresh_date()
void ta_refresh_date (TimeAdmin * ta, struct tm * LocalTime)
Definition at line 46 of file time-tool.c.
References TimeAdmin::Calendar.
Referenced by SaveModifyTime().
ta_refresh_time()
void ta_refresh_time (TimeAdmin * ta, struct tm * LocalTime)
Definition at line 34 of file time-tool.c.
References TimeAdmin::HourSpin, TimeAdmin::MinuteSpin, and TimeAdmin::SecondSpin.
Referenced by SaveModifyTime().
Update_Clock_Start()
void Update_Clock_Start (TimeAdmin * ta)
Definition at line 81 of file time-tool.c.
References TimeAdmin::UpdateTimeId.
Referenced by ChangeNtpSync().
Update_Clock_Stop()
void Update_Clock_Stop (TimeAdmin * ta)
Definition at line 89 of file time-tool.c.
References TimeAdmin::UpdateTimeId.