MATE Desktop Environment: unit-manager.c File Reference
unit-manager.c File Reference
#include <string.h>
#include <glib/gi18n.h>
#include "unit-manager.h"
#include "currency-manager.h"
Functions
G_DEFINE_TYPE_WITH_PRIVATE (UnitManager, unit_manager, G_TYPE_OBJECT)
UnitManager * unit_manager_get_default (void)
UnitCategory * unit_manager_add_category (UnitManager *manager, const gchar *name, const gchar *display_name)
const GList * unit_manager_get_categories (UnitManager *manager)
UnitCategory * unit_manager_get_category (UnitManager *manager, const gchar *category)
Unit * unit_manager_get_unit_by_name (UnitManager *manager, const gchar *name)
Unit * unit_manager_get_unit_by_symbol (UnitManager *manager, const gchar *symbol)
gboolean unit_manager_convert_by_symbol (UnitManager *manager, const MPNumber *x, const char *x_symbol, const char *z_symbol, MPNumber *z)
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (UnitManager , unit_manager , G_TYPE_OBJECT)
References b, and NULL.
unit_manager_add_category()
UnitCategory * unit_manager_add_category (UnitManager * manager, const gchar * name, const gchar * display_name)
Definition at line 146 of file unit-manager.c.
References category, name, NULL, unit_category_new(), and unit_manager_get_category().
Referenced by unit_manager_get_default().
unit_manager_convert_by_symbol()
gboolean unit_manager_convert_by_symbol (UnitManager * manager, const MPNumber * x, const char * x_symbol, const char * z_symbol, MPNumber * z)
Definition at line 224 of file unit-manager.c.
References FALSE, NULL, TRUE, unit_category_convert(), and unit_category_get_unit_by_symbol().
unit_manager_get_categories()
const GList * unit_manager_get_categories (UnitManager * manager)
Definition at line 162 of file unit-manager.c.
References NULL.
unit_manager_get_category()
UnitCategory * unit_manager_get_category (UnitManager * manager, const gchar * category)
Definition at line 169 of file unit-manager.c.
References category, NULL, and unit_category_get_name().
Referenced by unit_manager_add_category(), and unit_manager_get_default().
unit_manager_get_default()
UnitManager * unit_manager_get_default (void)
Definition at line 34 of file unit-manager.c.
References _, category, currency_get_display_name(), currency_get_name(), currency_get_symbol(), currency_manager_get_currencies(), currency_manager_get_default(), N_, name, NULL, unit_category_add_unit(), unit_manager_add_category(), unit_manager_get_category(), unit_manager_get_type(), and unit_new().
Referenced by math_converter_set_conversion().
unit_manager_get_unit_by_name()
Unit * unit_manager_get_unit_by_name (UnitManager * manager, const gchar * name)
Definition at line 186 of file unit-manager.c.
References name, NULL, and unit_category_get_unit_by_name().
Referenced by math_converter_set_conversion().
unit_manager_get_unit_by_symbol()
Unit * unit_manager_get_unit_by_symbol (UnitManager * manager, const gchar * symbol)
Definition at line 205 of file unit-manager.c.
References NULL, and unit_category_get_unit_by_symbol().