MATE Desktop Environment: unit.c File Reference
unit.c File Reference
#include <string.h>
#include "unit.h"
#include "mp-serializer.h"
#include "mp-equation.h"
#include "currency-manager.h"
Functions
G_DEFINE_TYPE_WITH_PRIVATE (Unit, unit, G_TYPE_OBJECT)
Unit * unit_new (const gchar *name, const gchar *display_name, const gchar *format, const gchar *from_function, const gchar *to_function, const gchar *symbols)
const gchar * unit_get_name (Unit *unit)
const gchar * unit_get_display_name (Unit *unit)
gboolean unit_matches_symbol (Unit *unit, const gchar *symbol)
const GList * unit_get_symbols (Unit *unit)
gboolean unit_convert_from (Unit *unit, const MPNumber *x, MPNumber *z)
gboolean unit_convert_to (Unit *unit, const MPNumber *x, MPNumber *z)
gchar * unit_format (Unit *unit, MPNumber *x)
Function Documentation
G_DEFINE_TYPE_WITH_PRIVATE()
G_DEFINE_TYPE_WITH_PRIVATE (Unit , unit , G_TYPE_OBJECT)
unit_convert_from()
gboolean unit_convert_from (Unit * unit, const MPNumber * x, MPNumber * z)
Definition at line 131 of file unit.c.
References currency_manager_get_default(), currency_manager_get_value(), FALSE, mp_divide(), NULL, CurrencyManager::priv, and TRUE.
Referenced by unit_category_convert().
unit_convert_to()
gboolean unit_convert_to (Unit * unit, const MPNumber * x, MPNumber * z)
Definition at line 152 of file unit.c.
References currency_manager_get_default(), currency_manager_get_value(), FALSE, mp_multiply(), NULL, CurrencyManager::priv, and TRUE.
Referenced by unit_category_convert().
unit_format()
gchar * unit_format (Unit * unit, MPNumber * x)
Definition at line 173 of file unit.c.
References FALSE, mp_serializer_to_string(), and NULL.
unit_get_display_name()
const gchar * unit_get_display_name (Unit * unit)
Definition at line 65 of file unit.c.
References NULL.
unit_get_name()
const gchar * unit_get_name (Unit * unit)
Definition at line 58 of file unit.c.
References NULL.
Referenced by unit_category_get_unit_by_name().
unit_get_symbols()
const GList * unit_get_symbols (Unit * unit)
Definition at line 89 of file unit.c.
References NULL.
unit_matches_symbol()
gboolean unit_matches_symbol (Unit * unit, const gchar * symbol)
Definition at line 72 of file unit.c.
References FALSE, NULL, and TRUE.
Referenced by unit_category_get_unit_by_symbol().
unit_new()
Unit * unit_new (const gchar * name, const gchar * display_name, const gchar * format, const gchar * from_function, const gchar * to_function, const gchar * symbols)
Definition at line 33 of file unit.c.
References name, NULL, and unit_get_type().
Referenced by unit_manager_get_default().