MATE Desktop Environment: unzip.c File Reference
unzip.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "zlib.h"
#include "unzip.h"
#include <errno.h>
Macros
#define NOUNCRYPT
#define local static
#define CASESENSITIVITYDEFAULT_NO
#define UNZ_BUFSIZE (16384)
#define UNZ_MAXFILENAMEINZIP (256)
#define ALLOC(size)
#define TRYFREE(p)
#define SIZECENTRALDIRITEM (0x2e)
#define SIZEZIPLOCALHEADER (0x1e)
#define CASESENSITIVITYDEFAULTVALUE 2
#define STRCMPCASENOSENTIVEFUNCTION strcmpcasenosensitive_internal
#define BUFREADCOMMENT (0x400)
Typedefs
typedef struct unz_file_info64_internal_s unz_file_info64_internal
Functions
local int unz64local_getByte OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, int *pi))
local int unz64local_getByte (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, int *pi)
local int unz64local_getShort OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, uLong *pX))
local int unz64local_getShort (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, uLong *pX)
local int unz64local_getLong (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, uLong *pX)
local int unz64local_getLong64 OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, ZPOS64_T *pX))
local int unz64local_getLong64 (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, ZPOS64_T *pX)
local int strcmpcasenosensitive_internal (const char *fileName1, const char *fileName2)
int ZEXPORT unzStringFileNameCompare (const char *fileName1, const char *fileName2, int iCaseSensitivity)
local ZPOS64_T unz64local_SearchCentralDir OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream))
local ZPOS64_T unz64local_SearchCentralDir (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream)
local ZPOS64_T unz64local_SearchCentralDir64 (const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream)
local unzFile unzOpenInternal (const void *path, zlib_filefunc64_32_def *pzlib_filefunc64_32_def, int is64bitOpenFunction)
unzFile ZEXPORT unzOpen2 (const char *path, zlib_filefunc_def *pzlib_filefunc32_def)
unzFile ZEXPORT unzOpen2_64 (const void *path, zlib_filefunc64_def *pzlib_filefunc_def)
unzFile ZEXPORT unzOpen (const char *path)
unzFile ZEXPORT unzOpen64 (const void *path)
int ZEXPORT unzClose (unzFile file)
int ZEXPORT unzGetGlobalInfo64 (unzFile file, unz_global_info64 *pglobal_info)
int ZEXPORT unzGetGlobalInfo (unzFile file, unz_global_info *pglobal_info32)
local void unz64local_DosDateToTmuDate (ZPOS64_T ulDosDate, tm_unz *ptm)
local int unz64local_GetCurrentFileInfoInternal OF ((unzFile file, unz_file_info64 *pfile_info, unz_file_info64_internal *pfile_info_internal, char *szFileName, uLong fileNameBufferSize, void *extraField, uLong extraFieldBufferSize, char *szComment, uLong commentBufferSize))
local int unz64local_GetCurrentFileInfoInternal (unzFile file, unz_file_info64 *pfile_info, unz_file_info64_internal *pfile_info_internal, char *szFileName, uLong fileNameBufferSize, void *extraField, uLong extraFieldBufferSize, char *szComment, uLong commentBufferSize)
int ZEXPORT unzGetCurrentFileInfo64 (unzFile file, unz_file_info64 *pfile_info, char *szFileName, uLong fileNameBufferSize, void *extraField, uLong extraFieldBufferSize, char *szComment, uLong commentBufferSize)
int ZEXPORT unzGetCurrentFileInfo (unzFile file, unz_file_info *pfile_info, char *szFileName, uLong fileNameBufferSize, void *extraField, uLong extraFieldBufferSize, char *szComment, uLong commentBufferSize)
int ZEXPORT unzGoToFirstFile (unzFile file)
int ZEXPORT unzGoToNextFile (unzFile file)
int ZEXPORT unzLocateFile (unzFile file, const char *szFileName, int iCaseSensitivity)
int ZEXPORT unzGetFilePos64 (unzFile file, unz64_file_pos *file_pos)
int ZEXPORT unzGetFilePos (unzFile file, unz_file_pos *file_pos)
int ZEXPORT unzGoToFilePos64 (unzFile file, const unz64_file_pos *file_pos)
int ZEXPORT unzGoToFilePos (unzFile file, unz_file_pos *file_pos)
local int unz64local_CheckCurrentFileCoherencyHeader (unz64_s *s, uInt *piSizeVar, ZPOS64_T *poffset_local_extrafield, uInt *psize_local_extrafield)
int ZEXPORT unzOpenCurrentFile3 (unzFile file, int *method, int *level, int raw, const char *password)
int ZEXPORT unzOpenCurrentFile (unzFile file)
int ZEXPORT unzOpenCurrentFilePassword (unzFile file, const char *password)
int ZEXPORT unzOpenCurrentFile2 (unzFile file, int *method, int *level, int raw)
ZPOS64_T ZEXPORT unzGetCurrentFileZStreamPos64 (unzFile file)
int ZEXPORT unzReadCurrentFile (unzFile file, voidp buf, unsigned len)
z_off_t ZEXPORT unztell (unzFile file)
ZPOS64_T ZEXPORT unztell64 (unzFile file)
int ZEXPORT unzeof (unzFile file)
int ZEXPORT unzGetLocalExtrafield (unzFile file, voidp buf, unsigned len)
int ZEXPORT unzCloseCurrentFile (unzFile file)
int ZEXPORT unzGetGlobalComment (unzFile file, char *szComment, uLong uSizeBuf)
ZPOS64_T ZEXPORT unzGetOffset64 (unzFile file)
uLong ZEXPORT unzGetOffset (unzFile file)
int ZEXPORT unzSetOffset64 (unzFile file, ZPOS64_T pos)
int ZEXPORT unzSetOffset (unzFile file, uLong pos)
Macro Definition Documentation
ALLOC
#define ALLOC (size)
Value:
(malloc(size))
Definition at line 106 of file unzip.c.
Referenced by unz64local_SearchCentralDir(), unz64local_SearchCentralDir64(), unzOpenCurrentFile3(), and unzOpenInternal().
BUFREADCOMMENT
#define BUFREADCOMMENT (0x400)
Definition at line 388 of file unzip.c.
Referenced by unz64local_SearchCentralDir(), and unz64local_SearchCentralDir64().
CASESENSITIVITYDEFAULT_NO
#define CASESENSITIVITYDEFAULT_NO
Definition at line 93 of file unzip.c.
CASESENSITIVITYDEFAULTVALUE
#define CASESENSITIVITYDEFAULTVALUE 2
Definition at line 355 of file unzip.c.
Referenced by unzStringFileNameCompare().
local
#define local static
Definition at line 87 of file unzip.c.
Referenced by OF(), OF(), OF(), OF(), OF(), strcmpcasenosensitive_internal(), unz64local_CheckCurrentFileCoherencyHeader(), unz64local_DosDateToTmuDate(), unz64local_getByte(), unz64local_GetCurrentFileInfoInternal(), unz64local_getLong(), unz64local_getLong64(), unz64local_getShort(), unz64local_SearchCentralDir(), unz64local_SearchCentralDir64(), and unzOpenInternal().
NOUNCRYPT
#define NOUNCRYPT
Definition at line 69 of file unzip.c.
SIZECENTRALDIRITEM
#define SIZECENTRALDIRITEM (0x2e)
Definition at line 112 of file unzip.c.
Referenced by unzGoToNextFile().
SIZEZIPLOCALHEADER
#define SIZEZIPLOCALHEADER (0x1e)
Definition at line 113 of file unzip.c.
Referenced by unz64local_CheckCurrentFileCoherencyHeader(), and unzOpenCurrentFile3().
STRCMPCASENOSENTIVEFUNCTION
#define STRCMPCASENOSENTIVEFUNCTION strcmpcasenosensitive_internal
Definition at line 361 of file unzip.c.
Referenced by unzStringFileNameCompare().
TRYFREE
#define TRYFREE (p)
Value:
{if (p) free(p);}
Definition at line 109 of file unzip.c.
Referenced by unz64local_SearchCentralDir(), unz64local_SearchCentralDir64(), unzClose(), unzCloseCurrentFile(), and unzOpenCurrentFile3().
UNZ_BUFSIZE
#define UNZ_BUFSIZE (16384)
Definition at line 98 of file unzip.c.
Referenced by unzOpenCurrentFile3(), and unzReadCurrentFile().
UNZ_MAXFILENAMEINZIP
#define UNZ_MAXFILENAMEINZIP (256)
Definition at line 102 of file unzip.c.
Referenced by unzLocateFile().
Typedef Documentation
unz_file_info64_internal
typedef struct unz_file_info64_internal_s unz_file_info64_internal
Function Documentation
OF() [1/5]
local ZPOS64_T unz64local_SearchCentralDir64 OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream))
References local, unz64local_SearchCentralDir(), and voidpf().
OF() [2/5]
local int unz64local_getByte OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, int *pi))
References local, unz64local_getByte(), and voidpf().
OF() [3/5]
local int unz64local_getLong OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, uLong *pX))
References local, uLong(), unz64local_getShort(), and voidpf().
OF() [4/5]
local int unz64local_getLong64 OF ((const zlib_filefunc64_32_def *pzlib_filefunc_def, voidpf filestream, ZPOS64_T *pX))
References local, unz64local_getLong64(), and voidpf().
OF() [5/5]
local int unz64local_GetCurrentFileInfoInternal OF ((unzFile file, unz_file_info64 *pfile_info, unz_file_info64_internal *pfile_info_internal, char *szFileName, uLong fileNameBufferSize, void *extraField, uLong extraFieldBufferSize, char *szComment, uLong commentBufferSize))
References local, uLong(), and unz64local_GetCurrentFileInfoInternal().
strcmpcasenosensitive_internal()
local int strcmpcasenosensitive_internal (const char * fileName1, const char * fileName2)
Definition at line 333 of file unzip.c.
References local.
unz64local_CheckCurrentFileCoherencyHeader()
local int unz64local_CheckCurrentFileCoherencyHeader (unz64_s * s, uInt * piSizeVar, ZPOS64_T * poffset_local_extrafield, uInt * psize_local_extrafield)
Definition at line 1346 of file unzip.c.
References unz_file_info64_s::compressed_size, unz_file_info64_s::compression_method, unz_file_info64_s::crc, local, unz_file_info64_s::size_filename, SIZEZIPLOCALHEADER, uLong(), unz_file_info64_s::uncompressed_size, unz64local_getLong(), unz64local_getShort(), UNZ_BADZIPFILE, UNZ_ERRNO, UNZ_OK, Z_BZIP2ED, ZLIB_FILEFUNC_SEEK_SET, and ZSEEK64.
Referenced by unzOpenCurrentFile3().
unz64local_DosDateToTmuDate()
local void unz64local_DosDateToTmuDate (ZPOS64_T ulDosDate, tm_unz * ptm)
Definition at line 824 of file unzip.c.
References local, tm_unz_s::tm_hour, tm_unz_s::tm_mday, tm_unz_s::tm_min, tm_unz_s::tm_mon, tm_unz_s::tm_sec, and tm_unz_s::tm_year.
Referenced by unz64local_GetCurrentFileInfoInternal().
unz64local_getByte()
local int unz64local_getByte (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream, int * pi)
Definition at line 198 of file unzip.c.
References int(), local, UNZ_EOF, UNZ_ERRNO, UNZ_OK, voidpf(), ZERROR64, and ZREAD64.
Referenced by OF(), unz64local_getLong(), unz64local_getLong64(), and unz64local_getShort().
unz64local_GetCurrentFileInfoInternal()
local int unz64local_GetCurrentFileInfoInternal (unzFile file, unz_file_info64 * pfile_info, unz_file_info64_internal * pfile_info_internal, char * szFileName, uLong fileNameBufferSize, void * extraField, uLong extraFieldBufferSize, char * szComment, uLong commentBufferSize)
Definition at line 851 of file unzip.c.
References unz_file_info64_s::compressed_size, unz_file_info64_s::compression_method, unz_file_info64_s::crc, unz_file_info64_s::disk_num_start, unz_file_info64_s::dosDate, unz_file_info64_s::external_fa, unz_file_info64_s::flag, unz_file_info64_s::internal_fa, local, MAXU32, NULL, unz_file_info64_s::size_file_comment, unz_file_info64_s::size_file_extra, unz_file_info64_s::size_filename, unz_file_info64_s::tmu_date, uLong(), unz_file_info64_s::uncompressed_size, unz64local_DosDateToTmuDate(), unz64local_getLong(), unz64local_getLong64(), unz64local_getShort(), UNZ_BADZIPFILE, UNZ_ERRNO, UNZ_OK, UNZ_PARAMERROR, unz_file_info64_s::version, unz_file_info64_s::version_needed, ZLIB_FILEFUNC_SEEK_CUR, ZLIB_FILEFUNC_SEEK_SET, ZREAD64, and ZSEEK64.
Referenced by OF(), unzGetCurrentFileInfo(), unzGetCurrentFileInfo64(), unzGoToFilePos64(), unzGoToFirstFile(), unzGoToNextFile(), and unzSetOffset64().
unz64local_getLong()
local int unz64local_getLong (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream, uLong * pX)
Definition at line 251 of file unzip.c.
References local, uLong(), unz64local_getByte(), UNZ_OK, and voidpf().
Referenced by unz64local_CheckCurrentFileCoherencyHeader(), unz64local_GetCurrentFileInfoInternal(), unz64local_SearchCentralDir64(), and unzOpenInternal().
unz64local_getLong64()
local int unz64local_getLong64 (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream, ZPOS64_T * pX)
Definition at line 286 of file unzip.c.
References local, unz64local_getByte(), UNZ_OK, and voidpf().
Referenced by OF(), unz64local_GetCurrentFileInfoInternal(), unz64local_SearchCentralDir64(), and unzOpenInternal().
unz64local_getShort()
local int unz64local_getShort (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream, uLong * pX)
Definition at line 224 of file unzip.c.
References local, uLong(), unz64local_getByte(), UNZ_OK, and voidpf().
Referenced by OF(), unz64local_CheckCurrentFileCoherencyHeader(), unz64local_GetCurrentFileInfoInternal(), and unzOpenInternal().
unz64local_SearchCentralDir()
local ZPOS64_T unz64local_SearchCentralDir (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream)
Definition at line 396 of file unzip.c.
References ALLOC, BUFREADCOMMENT, local, NULL, TRYFREE, uLong(), voidpf(), ZLIB_FILEFUNC_SEEK_END, ZLIB_FILEFUNC_SEEK_SET, ZREAD64, ZSEEK64, and ZTELL64.
Referenced by OF(), and unzOpenInternal().
unz64local_SearchCentralDir64()
local ZPOS64_T unz64local_SearchCentralDir64 (const zlib_filefunc64_32_def * pzlib_filefunc_def, voidpf filestream)
Definition at line 459 of file unzip.c.
References ALLOC, BUFREADCOMMENT, local, NULL, TRYFREE, uLong(), unz64local_getLong(), unz64local_getLong64(), UNZ_OK, voidpf(), ZLIB_FILEFUNC_SEEK_END, ZLIB_FILEFUNC_SEEK_SET, ZREAD64, ZSEEK64, and ZTELL64.
Referenced by unzOpenInternal().
unzClose()
int ZEXPORT unzClose (unzFile file) extern
Definition at line 781 of file unzip.c.
References NULL, TRYFREE, UNZ_OK, UNZ_PARAMERROR, unzCloseCurrentFile(), and ZCLOSE64.
Referenced by OF().
unzCloseCurrentFile()
int ZEXPORT unzCloseCurrentFile (unzFile file) extern
Definition at line 1955 of file unzip.c.
References NULL, TRYFREE, UNZ_CRCERROR, UNZ_OK, UNZ_PARAMERROR, and Z_BZIP2ED.
Referenced by OF(), unzClose(), and unzOpenCurrentFile3().
unzeof()
int ZEXPORT unzeof (unzFile file) extern
Definition at line 1877 of file unzip.c.
References NULL, and UNZ_PARAMERROR.
Referenced by OF().
unzGetCurrentFileInfo()
int ZEXPORT unzGetCurrentFileInfo (unzFile file, unz_file_info * pfile_info, char * szFileName, uLong fileNameBufferSize, void * extraField, uLong extraFieldBufferSize, char * szComment, uLong commentBufferSize) extern
Definition at line 1101 of file unzip.c.
References unz_file_info64_s::compressed_size, unz_file_info_s::compressed_size, unz_file_info64_s::compression_method, unz_file_info_s::compression_method, unz_file_info64_s::crc, unz_file_info_s::crc, unz_file_info64_s::disk_num_start, unz_file_info_s::disk_num_start, unz_file_info64_s::dosDate, unz_file_info_s::dosDate, unz_file_info64_s::external_fa, unz_file_info_s::external_fa, unz_file_info64_s::flag, unz_file_info_s::flag, unz_file_info64_s::internal_fa, unz_file_info_s::internal_fa, NULL, unz_file_info64_s::size_file_comment, unz_file_info_s::size_file_comment, unz_file_info64_s::size_file_extra, unz_file_info_s::size_file_extra, unz_file_info64_s::size_filename, unz_file_info_s::size_filename, unz_file_info64_s::tmu_date, unz_file_info_s::tmu_date, uLong(), unz_file_info64_s::uncompressed_size, unz_file_info_s::uncompressed_size, unz64local_GetCurrentFileInfoInternal(), UNZ_OK, unz_file_info64_s::version, unz_file_info_s::version, unz_file_info64_s::version_needed, and unz_file_info_s::version_needed.
Referenced by OF().
unzGetCurrentFileInfo64()
int ZEXPORT unzGetCurrentFileInfo64 (unzFile file, unz_file_info64 * pfile_info, char * szFileName, uLong fileNameBufferSize, void * extraField, uLong extraFieldBufferSize, char * szComment, uLong commentBufferSize) extern
Definition at line 1089 of file unzip.c.
References NULL, uLong(), and unz64local_GetCurrentFileInfoInternal().
Referenced by OF(), and unzLocateFile().
unzGetCurrentFileZStreamPos64()
ZPOS64_T ZEXPORT unzGetCurrentFileZStreamPos64 (unzFile file) extern
Addition for GDAL : START
Definition at line 1616 of file unzip.c.
References NULL.
Referenced by OF().
unzGetFilePos()
int ZEXPORT unzGetFilePos (unzFile file, unz_file_pos * file_pos) extern
Definition at line 1285 of file unzip.c.
References unz64_file_pos_s::num_of_file, unz_file_pos_s::num_of_file, unz64_file_pos_s::pos_in_zip_directory, unz_file_pos_s::pos_in_zip_directory, uLong(), UNZ_OK, and unzGetFilePos64().
unzGetFilePos64()
int ZEXPORT unzGetFilePos64 (unzFile file, unz64_file_pos * file_pos) extern
Definition at line 1269 of file unzip.c.
References NULL, unz64_file_pos_s::num_of_file, unz64_file_pos_s::pos_in_zip_directory, UNZ_END_OF_LIST_OF_FILE, UNZ_OK, and UNZ_PARAMERROR.
Referenced by unzGetFilePos().
unzGetGlobalComment()
int ZEXPORT unzGetGlobalComment (unzFile file, char * szComment, uLong uSizeBuf) extern
Definition at line 1998 of file unzip.c.
References NULL, unz_global_info64_s::size_comment, uLong(), UNZ_ERRNO, UNZ_PARAMERROR, ZLIB_FILEFUNC_SEEK_SET, ZREAD64, and ZSEEK64.
Referenced by OF().
unzGetGlobalInfo()
int ZEXPORT unzGetGlobalInfo (unzFile file, unz_global_info * pglobal_info32) extern
Definition at line 810 of file unzip.c.
References NULL, unz_global_info64_s::number_entry, unz_global_info_s::number_entry, unz_global_info64_s::size_comment, unz_global_info_s::size_comment, uLong(), UNZ_OK, and UNZ_PARAMERROR.
Referenced by OF().
unzGetGlobalInfo64()
int ZEXPORT unzGetGlobalInfo64 (unzFile file, unz_global_info64 * pglobal_info) extern
Definition at line 800 of file unzip.c.
References NULL, UNZ_OK, and UNZ_PARAMERROR.
Referenced by OF().
unzGetLocalExtrafield()
int ZEXPORT unzGetLocalExtrafield (unzFile file, voidp buf, unsigned len) extern
Definition at line 1907 of file unzip.c.
References NULL, UNZ_ERRNO, UNZ_PARAMERROR, ZLIB_FILEFUNC_SEEK_SET, ZREAD64, and ZSEEK64.
Referenced by OF().
unzGetOffset()
uLong ZEXPORT unzGetOffset (unzFile file) extern
Definition at line 2041 of file unzip.c.
References NULL, uLong(), and unzGetOffset64().
unzGetOffset64()
ZPOS64_T ZEXPORT unzGetOffset64 (unzFile file) extern
Definition at line 2026 of file unzip.c.
References NULL, and unz_global_info64_s::number_entry.
Referenced by unzGetOffset().
unzGoToFilePos()
int ZEXPORT unzGoToFilePos (unzFile file, unz_file_pos * file_pos) extern
Definition at line 1321 of file unzip.c.
References NULL, unz64_file_pos_s::num_of_file, unz_file_pos_s::num_of_file, unz64_file_pos_s::pos_in_zip_directory, unz_file_pos_s::pos_in_zip_directory, UNZ_PARAMERROR, and unzGoToFilePos64().
unzGoToFilePos64()
int ZEXPORT unzGoToFilePos64 (unzFile file, const unz64_file_pos * file_pos) extern
Definition at line 1299 of file unzip.c.
References NULL, unz64_file_pos_s::num_of_file, unz64_file_pos_s::pos_in_zip_directory, unz64local_GetCurrentFileInfoInternal(), UNZ_OK, and UNZ_PARAMERROR.
Referenced by unzGoToFilePos().
unzGoToFirstFile()
int ZEXPORT unzGoToFirstFile (unzFile file) extern
Definition at line 1142 of file unzip.c.
References NULL, unz64local_GetCurrentFileInfoInternal(), UNZ_OK, and UNZ_PARAMERROR.
Referenced by OF(), unzLocateFile(), and unzOpenInternal().
unzGoToNextFile()
int ZEXPORT unzGoToNextFile (unzFile file) extern
Definition at line 1163 of file unzip.c.
References NULL, unz_global_info64_s::number_entry, unz_file_info64_s::size_file_comment, unz_file_info64_s::size_file_extra, unz_file_info64_s::size_filename, SIZECENTRALDIRITEM, unz64local_GetCurrentFileInfoInternal(), UNZ_END_OF_LIST_OF_FILE, UNZ_OK, and UNZ_PARAMERROR.
Referenced by OF(), and unzLocateFile().
unzLocateFile()
int ZEXPORT unzLocateFile (unzFile file, const char * szFileName, int iCaseSensitivity) extern
Definition at line 1195 of file unzip.c.
References NULL, UNZ_END_OF_LIST_OF_FILE, UNZ_MAXFILENAMEINZIP, UNZ_OK, UNZ_PARAMERROR, unzGetCurrentFileInfo64(), unzGoToFirstFile(), unzGoToNextFile(), and unzStringFileNameCompare().
Referenced by OF().
unzOpen()
unzFile ZEXPORT unzOpen (const char * path) extern
Definition at line 766 of file unzip.c.
References NULL, and unzOpenInternal().
Referenced by OF().
unzOpen2()
unzFile ZEXPORT unzOpen2 (const char * path, zlib_filefunc_def * pzlib_filefunc32_def) extern
Definition at line 738 of file unzip.c.
References fill_zlib_filefunc64_32_def_from_filefunc32(), NULL, and unzOpenInternal().
Referenced by OF().
unzOpen2_64()
unzFile ZEXPORT unzOpen2_64 (const void * path, zlib_filefunc64_def * pzlib_filefunc_def) extern
Definition at line 751 of file unzip.c.
References NULL, unzOpenInternal(), zlib_filefunc64_32_def_s::zfile_func64, zlib_filefunc64_32_def_s::zseek32_file, and zlib_filefunc64_32_def_s::ztell32_file.
Referenced by OF().
unzOpen64()
unzFile ZEXPORT unzOpen64 (const void * path) extern
Definition at line 771 of file unzip.c.
References NULL, and unzOpenInternal().
Referenced by OF().
unzOpenCurrentFile()
int ZEXPORT unzOpenCurrentFile (unzFile file) extern
Definition at line 1599 of file unzip.c.
References NULL, and unzOpenCurrentFile3().
Referenced by OF().
unzOpenCurrentFile2()
int ZEXPORT unzOpenCurrentFile2 (unzFile file, int * method, int * level, int raw) extern
Definition at line 1609 of file unzip.c.
References level, NULL, and unzOpenCurrentFile3().
Referenced by OF().
unzOpenCurrentFile3()
int ZEXPORT unzOpenCurrentFile3 (unzFile file, int * method, int * level, int raw, const char * password) extern
Definition at line 1432 of file unzip.c.
References ALLOC, unz_file_info64_s::compressed_size, unz_file_info64_s::compression_method, unz_file_info64_s::crc, unz_file_info64_s::flag, int(), level, NULL, SIZEZIPLOCALHEADER, TRYFREE, unz_file_info64_s::uncompressed_size, unz64local_CheckCurrentFileCoherencyHeader(), UNZ_BADZIPFILE, UNZ_BUFSIZE, UNZ_INTERNALERROR, UNZ_OK, UNZ_PARAMERROR, unzCloseCurrentFile(), voidpf(), Z_BZIP2ED, ZREAD64, and ZSEEK64.
Referenced by OF(), unzOpenCurrentFile(), unzOpenCurrentFile2(), and unzOpenCurrentFilePassword().
unzOpenCurrentFilePassword()
int ZEXPORT unzOpenCurrentFilePassword (unzFile file, const char * password) extern
Definition at line 1604 of file unzip.c.
References NULL, and unzOpenCurrentFile3().
Referenced by OF().
unzOpenInternal()
local unzFile unzOpenInternal (const void * path, zlib_filefunc64_32_def * pzlib_filefunc64_32_def, int is64bitOpenFunction)
Definition at line 564 of file unzip.c.
References ALLOC, fill_fopen64_filefunc(), local, NULL, unz_global_info64_s::number_entry, unz_global_info64_s::size_comment, uLong(), unz64local_getLong(), unz64local_getLong64(), unz64local_getShort(), unz64local_SearchCentralDir(), unz64local_SearchCentralDir64(), UNZ_BADZIPFILE, UNZ_ERRNO, UNZ_OK, unzGoToFirstFile(), ZCLOSE64, zlib_filefunc64_32_def_s::zfile_func64, ZLIB_FILEFUNC_MODE_EXISTING, ZLIB_FILEFUNC_MODE_READ, ZLIB_FILEFUNC_SEEK_SET, ZOPEN64, zlib_filefunc64_32_def_s::zseek32_file, ZSEEK64, and zlib_filefunc64_32_def_s::ztell32_file.
Referenced by unzOpen(), unzOpen2(), unzOpen2_64(), and unzOpen64().
unzReadCurrentFile()
int ZEXPORT unzReadCurrentFile (unzFile file, voidp buf, unsigned len) extern
Addition for GDAL : END
Definition at line 1642 of file unzip.c.
References NULL, uLong(), UNZ_BUFSIZE, UNZ_END_OF_LIST_OF_FILE, UNZ_EOF, UNZ_ERRNO, UNZ_OK, UNZ_PARAMERROR, Z_BZIP2ED, ZLIB_FILEFUNC_SEEK_SET, ZREAD64, and ZSEEK64.
Referenced by OF().
unzSetOffset()
int ZEXPORT unzSetOffset (unzFile file, uLong pos) extern
Definition at line 2069 of file unzip.c.
References uLong(), and unzSetOffset64().
unzSetOffset64()
int ZEXPORT unzSetOffset64 (unzFile file, ZPOS64_T pos) extern
Definition at line 2051 of file unzip.c.
References NULL, unz_global_info64_s::number_entry, unz64local_GetCurrentFileInfoInternal(), UNZ_OK, and UNZ_PARAMERROR.
Referenced by unzSetOffset().
unzStringFileNameCompare()
int ZEXPORT unzStringFileNameCompare (const char * fileName1, const char * fileName2, int iCaseSensitivity) extern
Definition at line 373 of file unzip.c.
References CASESENSITIVITYDEFAULTVALUE, and STRCMPCASENOSENTIVEFUNCTION.
Referenced by OF(), and unzLocateFile().
unztell()
z_off_t ZEXPORT unztell (unzFile file) extern
Definition at line 1843 of file unzip.c.
References NULL, and UNZ_PARAMERROR.
Referenced by OF().
unztell64()
ZPOS64_T ZEXPORT unztell64 (unzFile file) extern
Definition at line 1858 of file unzip.c.
References NULL.
Referenced by OF().