MATE Desktop Environment: unzip.h File Reference
unzip.h File Reference
#include "zlib.h"
#include "ioapi.h"
Classes
struct tm_unz_s
struct unz_global_info64_s
struct unz_global_info_s
struct unz_file_info64_s
struct unz_file_info_s
struct unz_file_pos_s
struct unz64_file_pos_s
Macros
#define Z_BZIP2ED 12
#define UNZ_OK (0)
#define UNZ_END_OF_LIST_OF_FILE (-100)
#define UNZ_ERRNO (Z_ERRNO)
#define UNZ_EOF (0)
#define UNZ_PARAMERROR (-102)
#define UNZ_BADZIPFILE (-103)
#define UNZ_INTERNALERROR (-104)
#define UNZ_CRCERROR (-105)
Typedefs
typedef voidp unzFile
typedef struct tm_unz_s tm_unz
typedef struct unz_global_info64_s unz_global_info64
typedef struct unz_global_info_s unz_global_info
typedef struct unz_file_info64_s unz_file_info64
typedef struct unz_file_info_s unz_file_info
typedef struct unz_file_pos_s unz_file_pos
typedef struct unz64_file_pos_s unz64_file_pos
Functions
int ZEXPORT unzStringFileNameCompare OF ((const char *fileName1, const char *fileName2, int iCaseSensitivity))
unzFile ZEXPORT unzOpen OF ((const char *path))
unzFile ZEXPORT unzOpen64 OF ((const void *path))
unzFile ZEXPORT unzOpen2 OF ((const char *path, zlib_filefunc_def *pzlib_filefunc_def))
unzFile ZEXPORT unzOpen2_64 OF ((const void *path, zlib_filefunc64_def *pzlib_filefunc_def))
int ZEXPORT unzClose OF ((unzFile file))
int ZEXPORT unzGetGlobalInfo OF ((unzFile file, unz_global_info *pglobal_info))
int ZEXPORT unzGetGlobalInfo64 OF ((unzFile file, unz_global_info64 *pglobal_info))
int ZEXPORT unzGetGlobalComment OF ((unzFile file, char *szComment, uLong uSizeBuf))
int ZEXPORT unzLocateFile OF ((unzFile file, const char *szFileName, int iCaseSensitivity))
int ZEXPORT unzGetFilePos (unzFile file, unz_file_pos *file_pos)
int ZEXPORT unzGoToFilePos (unzFile file, unz_file_pos *file_pos)
int ZEXPORT unzGetFilePos64 (unzFile file, unz64_file_pos *file_pos)
int ZEXPORT unzGoToFilePos64 (unzFile file, const unz64_file_pos *file_pos)
int ZEXPORT unzGetCurrentFileInfo64 OF ((unzFile file, unz_file_info64 *pfile_info, char *szFileName, uLong fileNameBufferSize, void *extraField, uLong extraFieldBufferSize, char *szComment, uLong commentBufferSize))
int ZEXPORT unzGetCurrentFileInfo OF ((unzFile file, unz_file_info *pfile_info, char *szFileName, uLong fileNameBufferSize, void *extraField, uLong extraFieldBufferSize, char *szComment, uLong commentBufferSize))
int ZEXPORT unzOpenCurrentFilePassword OF ((unzFile file, const char *password))
int ZEXPORT unzOpenCurrentFile2 OF ((unzFile file, int *method, int *level, int raw))
int ZEXPORT unzOpenCurrentFile3 OF ((unzFile file, int *method, int *level, int raw, const char *password))
int ZEXPORT unzReadCurrentFile OF ((unzFile file, voidp buf, unsigned len))
ZPOS64_T ZEXPORT unzGetOffset64 (unzFile file)
uLong ZEXPORT unzGetOffset (unzFile file)
int ZEXPORT unzSetOffset64 (unzFile file, ZPOS64_T pos)
int ZEXPORT unzSetOffset (unzFile file, uLong pos)
Macro Definition Documentation
UNZ_BADZIPFILE
#define UNZ_BADZIPFILE (-103)
Definition at line 78 of file unzip.h.
Referenced by unz64local_CheckCurrentFileCoherencyHeader(), unz64local_GetCurrentFileInfoInternal(), unzOpenCurrentFile3(), and unzOpenInternal().
UNZ_CRCERROR
#define UNZ_CRCERROR (-105)
Definition at line 80 of file unzip.h.
Referenced by unzCloseCurrentFile().
UNZ_END_OF_LIST_OF_FILE
#define UNZ_END_OF_LIST_OF_FILE (-100)
Definition at line 74 of file unzip.h.
Referenced by unzGetFilePos64(), unzGoToNextFile(), unzLocateFile(), and unzReadCurrentFile().
UNZ_EOF
#define UNZ_EOF (0)
Definition at line 76 of file unzip.h.
Referenced by unz64local_getByte(), and unzReadCurrentFile().
UNZ_ERRNO
#define UNZ_ERRNO (Z_ERRNO)
Definition at line 75 of file unzip.h.
Referenced by unz64local_CheckCurrentFileCoherencyHeader(), unz64local_getByte(), unz64local_GetCurrentFileInfoInternal(), unzGetGlobalComment(), unzGetLocalExtrafield(), unzOpenInternal(), and unzReadCurrentFile().
UNZ_INTERNALERROR
#define UNZ_INTERNALERROR (-104)
Definition at line 79 of file unzip.h.
Referenced by unzOpenCurrentFile3().
UNZ_OK
#define UNZ_OK (0)
Definition at line 73 of file unzip.h.
Referenced by unz64local_CheckCurrentFileCoherencyHeader(), unz64local_getByte(), unz64local_GetCurrentFileInfoInternal(), unz64local_getLong(), unz64local_getLong64(), unz64local_getShort(), unz64local_SearchCentralDir64(), unzClose(), unzCloseCurrentFile(), unzGetCurrentFileInfo(), unzGetFilePos(), unzGetFilePos64(), unzGetGlobalInfo(), unzGetGlobalInfo64(), unzGoToFilePos64(), unzGoToFirstFile(), unzGoToNextFile(), unzLocateFile(), unzOpenCurrentFile3(), unzOpenInternal(), unzReadCurrentFile(), and unzSetOffset64().
UNZ_PARAMERROR
#define UNZ_PARAMERROR (-102)
Definition at line 77 of file unzip.h.
Referenced by unz64local_GetCurrentFileInfoInternal(), unzClose(), unzCloseCurrentFile(), unzeof(), unzGetFilePos64(), unzGetGlobalComment(), unzGetGlobalInfo(), unzGetGlobalInfo64(), unzGetLocalExtrafield(), unzGoToFilePos(), unzGoToFilePos64(), unzGoToFirstFile(), unzGoToNextFile(), unzLocateFile(), unzOpenCurrentFile3(), unzReadCurrentFile(), unzSetOffset64(), and unztell().
Z_BZIP2ED
#define Z_BZIP2ED 12
Definition at line 62 of file unzip.h.
Referenced by unz64local_CheckCurrentFileCoherencyHeader(), unzCloseCurrentFile(), unzOpenCurrentFile3(), and unzReadCurrentFile().
Typedef Documentation
tm_unz
typedef struct tm_unz_s tm_unz
unz64_file_pos
typedef struct unz64_file_pos_s unz64_file_pos
unz_file_info
typedef struct unz_file_info_s unz_file_info
unz_file_info64
typedef struct unz_file_info64_s unz_file_info64
unz_file_pos
typedef struct unz_file_pos_s unz_file_pos
unz_global_info
typedef struct unz_global_info_s unz_global_info
unz_global_info64
typedef struct unz_global_info64_s unz_global_info64
unzFile
typedef voidp unzFile
Definition at line 70 of file unzip.h.
Function Documentation
OF() [1/16]
int ZEXPORT unzStringFileNameCompare OF ((const char *fileName1, const char *fileName2, int iCaseSensitivity)) extern
References unzStringFileNameCompare().
OF() [2/16]
unzFile ZEXPORT unzOpen OF ((const char *path)) extern
References unzOpen().
OF() [3/16]
unzFile ZEXPORT unzOpen2 OF ((const char *path, zlib_filefunc_def *pzlib_filefunc_def)) extern
References unzOpen2().
OF() [4/16]
unzFile ZEXPORT unzOpen64 OF ((const void *path)) extern
References unzOpen64().
OF() [5/16]
unzFile ZEXPORT unzOpen2_64 OF ((const void *path, zlib_filefunc64_def *pzlib_filefunc_def)) extern
References unzOpen2_64().
OF() [6/16]
int ZEXPORT unzeof OF ((unzFile file)) extern
Addition for GDAL : START
Addition for GDAL : END
References unzClose().
OF() [7/16]
int ZEXPORT unzGetGlobalComment OF ((unzFile file, char *szComment, uLong uSizeBuf)) extern
References uLong(), unzGetGlobalComment(), unzGoToFirstFile(), and unzGoToNextFile().
OF() [8/16]
int ZEXPORT unzOpenCurrentFilePassword OF ((unzFile file, const char *password)) extern
References unzOpenCurrentFilePassword().
OF() [9/16]
int ZEXPORT unzLocateFile OF ((unzFile file, const char *szFileName, int iCaseSensitivity)) extern
References unzLocateFile().
OF() [10/16]
int ZEXPORT unzOpenCurrentFile2 OF ((unzFile file, int *method, int *level, int raw)) extern
References level, and unzOpenCurrentFile2().
OF() [11/16]
int ZEXPORT unzOpenCurrentFile3 OF ((unzFile file, int *method, int *level, int raw, const char *password)) extern
References level, unzCloseCurrentFile(), and unzOpenCurrentFile3().
OF() [12/16]
int ZEXPORT unzGetCurrentFileInfo OF ((unzFile file, unz_file_info *pfile_info, char *szFileName, uLong fileNameBufferSize, void *extraField, uLong extraFieldBufferSize, char *szComment, uLong commentBufferSize)) extern
References uLong(), unzGetCurrentFileInfo(), unzGetCurrentFileZStreamPos64(), and unzOpenCurrentFile().
OF() [13/16]
int ZEXPORT unzGetCurrentFileInfo64 OF ((unzFile file, unz_file_info64 *pfile_info, char *szFileName, uLong fileNameBufferSize, void *extraField, uLong extraFieldBufferSize, char *szComment, uLong commentBufferSize)) extern
References uLong(), and unzGetCurrentFileInfo64().
OF() [14/16]
int ZEXPORT unzGetGlobalInfo OF ((unzFile file, unz_global_info *pglobal_info)) extern
References unzGetGlobalInfo().
OF() [15/16]
int ZEXPORT unzGetGlobalInfo64 OF ((unzFile file, unz_global_info64 *pglobal_info)) extern
References unzGetGlobalInfo64().
OF() [16/16]
int ZEXPORT unzGetLocalExtrafield OF ((unzFile file, voidp buf, unsigned len)) extern
References uLong(), unzeof(), unzGetLocalExtrafield(), unzReadCurrentFile(), unztell(), and unztell64().
unzGetFilePos()
int ZEXPORT unzGetFilePos (unzFile file, unz_file_pos * file_pos) extern
Definition at line 1285 of file unzip.c.
References unz64_file_pos_s::num_of_file, unz_file_pos_s::num_of_file, unz64_file_pos_s::pos_in_zip_directory, unz_file_pos_s::pos_in_zip_directory, uLong(), UNZ_OK, and unzGetFilePos64().
unzGetFilePos64()
int ZEXPORT unzGetFilePos64 (unzFile file, unz64_file_pos * file_pos) extern
Definition at line 1269 of file unzip.c.
References NULL, unz64_file_pos_s::num_of_file, unz64_file_pos_s::pos_in_zip_directory, UNZ_END_OF_LIST_OF_FILE, UNZ_OK, and UNZ_PARAMERROR.
Referenced by unzGetFilePos().
unzGetOffset()
uLong ZEXPORT unzGetOffset (unzFile file) extern
Definition at line 2041 of file unzip.c.
References NULL, uLong(), and unzGetOffset64().
unzGetOffset64()
ZPOS64_T ZEXPORT unzGetOffset64 (unzFile file) extern
Definition at line 2026 of file unzip.c.
References NULL, and unz_global_info64_s::number_entry.
Referenced by unzGetOffset().
unzGoToFilePos()
int ZEXPORT unzGoToFilePos (unzFile file, unz_file_pos * file_pos) extern
Definition at line 1321 of file unzip.c.
References NULL, unz64_file_pos_s::num_of_file, unz_file_pos_s::num_of_file, unz64_file_pos_s::pos_in_zip_directory, unz_file_pos_s::pos_in_zip_directory, UNZ_PARAMERROR, and unzGoToFilePos64().
unzGoToFilePos64()
int ZEXPORT unzGoToFilePos64 (unzFile file, const unz64_file_pos * file_pos) extern
Definition at line 1299 of file unzip.c.
References NULL, unz64_file_pos_s::num_of_file, unz64_file_pos_s::pos_in_zip_directory, unz64local_GetCurrentFileInfoInternal(), UNZ_OK, and UNZ_PARAMERROR.
Referenced by unzGoToFilePos().
unzSetOffset()
int ZEXPORT unzSetOffset (unzFile file, uLong pos) extern
Definition at line 2069 of file unzip.c.
References uLong(), and unzSetOffset64().
unzSetOffset64()
int ZEXPORT unzSetOffset64 (unzFile file, ZPOS64_T pos) extern
Definition at line 2051 of file unzip.c.
References NULL, unz_global_info64_s::number_entry, unz64local_GetCurrentFileInfoInternal(), UNZ_OK, and UNZ_PARAMERROR.
Referenced by unzSetOffset().