MATE Desktop Environment: user_share.c File Reference
user_share.c File Reference
#include "config.h"
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
#include <glib/gi18n.h>
#include <glib/gstdio.h>
#include <gio/gio.h>
#include <X11/Xlib.h>
#include "user_share-private.h"
#include "user_share-common.h"
#include "http.h"
#include <stdarg.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <unistd.h>
Macros
#define GSETTINGS_SCHEMA "org.mate.FileSharing"
#define GSETTINGS_KEY_FILE_SHARING_ENABLED "enabled"
#define GSETTINGS_KEY_FILE_SHARING_REQUIRE_PASSWORD "require-password"
Functions
int main (int argc, char **argv)
Macro Definition Documentation
GSETTINGS_KEY_FILE_SHARING_ENABLED
#define GSETTINGS_KEY_FILE_SHARING_ENABLED "enabled"
Definition at line 59 of file user_share.c.
GSETTINGS_KEY_FILE_SHARING_REQUIRE_PASSWORD
#define GSETTINGS_KEY_FILE_SHARING_REQUIRE_PASSWORD "require-password"
Definition at line 60 of file user_share.c.
GSETTINGS_SCHEMA
#define GSETTINGS_SCHEMA "org.mate.FileSharing"
Definition at line 58 of file user_share.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 390 of file user_share.c.
References FALSE, GETTEXT_PACKAGE, GSETTINGS_KEY_FILE_SHARING_BLUETOOTH_ALLOW_WRITE, GSETTINGS_KEY_FILE_SHARING_BLUETOOTH_ENABLED, GSETTINGS_KEY_FILE_SHARING_BLUETOOTH_OBEXPUSH_ACCEPT_FILES, GSETTINGS_KEY_FILE_SHARING_BLUETOOTH_OBEXPUSH_ENABLED, GSETTINGS_KEY_FILE_SHARING_BLUETOOTH_OBEXPUSH_NOTIFY, GSETTINGS_KEY_FILE_SHARING_BLUETOOTH_REQUIRE_PAIRING, GSETTINGS_KEY_FILE_SHARING_ENABLED, GSETTINGS_KEY_FILE_SHARING_REQUIRE_PASSWORD, GSETTINGS_SCHEMA, http_init(), MATELOCALEDIR, NULL, obexftp_init(), and obexpush_init().