MATE Desktop Environment: weather.h File Reference
weather.h File Reference
#include <gdk-pixbuf/gdk-pixbuf.h>
Classes
struct _WeatherLocation
struct _WeatherPrefs
Macros
#define weather_info_new(location, prefs, cb, data)
#define weather_info_update(info, prefs, cb, data)
Typedefs
typedef struct _WeatherLocation WeatherLocation
typedef enum _WeatherForecastType WeatherForecastType
typedef struct _WeatherPrefs WeatherPrefs
typedef struct _WeatherInfo WeatherInfo
typedef void(* WeatherInfoFunc) (WeatherInfo *info, gpointer data)
typedef enum _WeatherWindDirection WeatherWindDirection
typedef enum _WeatherSky WeatherSky
typedef enum _WeatherConditionPhenomenon WeatherConditionPhenomenon
typedef enum _WeatherConditionQualifier WeatherConditionQualifier
typedef gdouble WeatherMoonPhase
typedef gdouble WeatherMoonLatitude
Enumerations
enum _WeatherForecastType { FORECAST_STATE , FORECAST_ZONE , FORECAST_LIST }
enum TempUnit {
TEMP_UNIT_INVALID = 0 , TEMP_UNIT_DEFAULT , TEMP_UNIT_KELVIN , TEMP_UNIT_CENTIGRADE ,
TEMP_UNIT_FAHRENHEIT
}
enum SpeedUnit {
SPEED_UNIT_INVALID = 0 , SPEED_UNIT_DEFAULT , SPEED_UNIT_MS , SPEED_UNIT_KPH ,
SPEED_UNIT_MPH , SPEED_UNIT_KNOTS , SPEED_UNIT_BFT
}
enum PressureUnit {
PRESSURE_UNIT_INVALID = 0 , PRESSURE_UNIT_DEFAULT , PRESSURE_UNIT_KPA , PRESSURE_UNIT_HPA ,
PRESSURE_UNIT_MB , PRESSURE_UNIT_MM_HG , PRESSURE_UNIT_INCH_HG , PRESSURE_UNIT_ATM
}
enum DistanceUnit {
DISTANCE_UNIT_INVALID = 0 , DISTANCE_UNIT_DEFAULT , DISTANCE_UNIT_METERS , DISTANCE_UNIT_KM ,
DISTANCE_UNIT_MILES
}
enum _WeatherWindDirection {
WIND_INVALID = -1 , WIND_VARIABLE , WIND_N , WIND_NNE ,
WIND_NE , WIND_ENE , WIND_E , WIND_ESE ,
WIND_SE , WIND_SSE , WIND_S , WIND_SSW ,
WIND_SW , WIND_WSW , WIND_W , WIND_WNW ,
WIND_NW , WIND_NNW , WIND_LAST
}
enum _WeatherSky {
SKY_INVALID = -1 , SKY_CLEAR , SKY_BROKEN , SKY_SCATTERED ,
SKY_FEW , SKY_OVERCAST , SKY_LAST
}
enum _WeatherConditionPhenomenon {
PHENOMENON_INVALID = -1 , PHENOMENON_NONE , PHENOMENON_DRIZZLE , PHENOMENON_RAIN ,
PHENOMENON_SNOW , PHENOMENON_SNOW_GRAINS , PHENOMENON_ICE_CRYSTALS , PHENOMENON_ICE_PELLETS ,
PHENOMENON_HAIL , PHENOMENON_SMALL_HAIL , PHENOMENON_UNKNOWN_PRECIPITATION , PHENOMENON_MIST ,
PHENOMENON_FOG , PHENOMENON_SMOKE , PHENOMENON_VOLCANIC_ASH , PHENOMENON_SAND ,
PHENOMENON_HAZE , PHENOMENON_SPRAY , PHENOMENON_DUST , PHENOMENON_SQUALL ,
PHENOMENON_SANDSTORM , PHENOMENON_DUSTSTORM , PHENOMENON_FUNNEL_CLOUD , PHENOMENON_TORNADO ,
PHENOMENON_DUST_WHIRLS , PHENOMENON_LAST
}
enum _WeatherConditionQualifier {
QUALIFIER_INVALID = -1 , QUALIFIER_NONE , QUALIFIER_VICINITY , QUALIFIER_LIGHT ,
QUALIFIER_MODERATE , QUALIFIER_HEAVY , QUALIFIER_SHALLOW , QUALIFIER_PATCHES ,
QUALIFIER_PARTIAL , QUALIFIER_THUNDERSTORM , QUALIFIER_BLOWING , QUALIFIER_SHOWERS ,
QUALIFIER_DRIFTING , QUALIFIER_FREEZING , QUALIFIER_LAST
}
Functions
WeatherLocation * weather_location_new (const gchar *trans_name, const gchar *code, const gchar *zone, const gchar *radar, const gchar *coordinates, const gchar *country_code, const gchar *tz_hint)
WeatherLocation * weather_location_clone (const WeatherLocation *location)
void weather_location_free (WeatherLocation *location)
gboolean weather_location_equal (const WeatherLocation *location1, const WeatherLocation *location2)
WeatherInfo * _weather_info_fill (WeatherInfo *info, WeatherLocation *location, const WeatherPrefs *prefs, WeatherInfoFunc cb, gpointer data)
void weather_info_abort (WeatherInfo *info)
WeatherInfo * weather_info_clone (const WeatherInfo *info)
void weather_info_free (WeatherInfo *info)
gboolean weather_info_is_valid (WeatherInfo *info)
gboolean weather_info_network_error (WeatherInfo *info)
void weather_info_to_metric (WeatherInfo *info)
void weather_info_to_imperial (WeatherInfo *info)
const WeatherLocation * weather_info_get_location (WeatherInfo *info)
const gchar * weather_info_get_location_name (WeatherInfo *info)
const gchar * weather_info_get_update (WeatherInfo *info)
const gchar * weather_info_get_sky (WeatherInfo *info)
const gchar * weather_info_get_conditions (WeatherInfo *info)
const gchar * weather_info_get_temp (WeatherInfo *info)
const gchar * weather_info_get_temp_min (WeatherInfo *info)
const gchar * weather_info_get_temp_max (WeatherInfo *info)
const gchar * weather_info_get_dew (WeatherInfo *info)
const gchar * weather_info_get_humidity (WeatherInfo *info)
const gchar * weather_info_get_wind (WeatherInfo *info)
const gchar * weather_info_get_pressure (WeatherInfo *info)
const gchar * weather_info_get_visibility (WeatherInfo *info)
const gchar * weather_info_get_apparent (WeatherInfo *info)
const gchar * weather_info_get_sunrise (WeatherInfo *info)
const gchar * weather_info_get_sunset (WeatherInfo *info)
const gchar * weather_info_get_forecast (WeatherInfo *info)
GSList * weather_info_get_forecast_list (WeatherInfo *info)
GdkPixbufAnimation * weather_info_get_radar (WeatherInfo *info)
const gchar * weather_info_get_temp_summary (WeatherInfo *info)
gchar * weather_info_get_weather_summary (WeatherInfo *info)
const gchar * weather_info_get_icon_name (WeatherInfo *info)
gint weather_info_next_sun_event (WeatherInfo *info)
gboolean weather_info_get_value_update (WeatherInfo *info, time_t *value)
gboolean weather_info_get_value_sky (WeatherInfo *info, WeatherSky *sky)
gboolean weather_info_get_value_conditions (WeatherInfo *info, WeatherConditionPhenomenon *phenomenon, WeatherConditionQualifier *qualifier)
gboolean weather_info_get_value_temp (WeatherInfo *info, TempUnit unit, gdouble *value)
gboolean weather_info_get_value_temp_min (WeatherInfo *info, TempUnit unit, gdouble *value)
gboolean weather_info_get_value_temp_max (WeatherInfo *info, TempUnit unit, gdouble *value)
gboolean weather_info_get_value_dew (WeatherInfo *info, TempUnit unit, gdouble *value)
gboolean weather_info_get_value_apparent (WeatherInfo *info, TempUnit unit, gdouble *value)
gboolean weather_info_get_value_wind (WeatherInfo *info, SpeedUnit unit, gdouble *speed, WeatherWindDirection *direction)
gboolean weather_info_get_value_pressure (WeatherInfo *info, PressureUnit unit, gdouble *value)
gboolean weather_info_get_value_visibility (WeatherInfo *info, DistanceUnit unit, gdouble *value)
gboolean weather_info_get_value_sunrise (WeatherInfo *info, time_t *value)
gboolean weather_info_get_value_sunset (WeatherInfo *info, time_t *value)
gboolean weather_info_get_value_moonphase (WeatherInfo *info, WeatherMoonPhase *value, WeatherMoonLatitude *lat)
gboolean weather_info_get_upcoming_moonphases (WeatherInfo *info, time_t *phases)
Macro Definition Documentation
weather_info_new
#define weather_info_new (location, prefs, cb, data)
Value:
_weather_info_fill (NULL, (location), (prefs), (cb), (data))
Definition at line 138 of file weather.h.
Referenced by mateweather_location_get_weather(), and mateweather_update().
weather_info_update
#define weather_info_update (info, prefs, cb, data)
Value:
_weather_info_fill ((info), NULL, (prefs), (cb), (data))
Definition at line 139 of file weather.h.
Referenced by mateweather_update().
Typedef Documentation
WeatherConditionPhenomenon
typedef enum _WeatherConditionPhenomenon WeatherConditionPhenomenon
Definition at line 237 of file weather.h.
WeatherConditionQualifier
typedef enum _WeatherConditionQualifier WeatherConditionQualifier
Definition at line 261 of file weather.h.
WeatherForecastType
typedef enum _WeatherForecastType WeatherForecastType
WeatherInfo
typedef struct _WeatherInfo WeatherInfo
Definition at line 129 of file weather.h.
WeatherInfoFunc
typedef void(* WeatherInfoFunc) (WeatherInfo *info, gpointer data)
Definition at line 131 of file weather.h.
WeatherLocation
typedef struct _WeatherLocation WeatherLocation
Definition at line 50 of file weather.h.
WeatherMoonLatitude
typedef gdouble WeatherMoonLatitude
Definition at line 263 of file weather.h.
WeatherMoonPhase
typedef gdouble WeatherMoonPhase
Definition at line 262 of file weather.h.
WeatherPrefs
typedef struct _WeatherPrefs WeatherPrefs
Definition at line 123 of file weather.h.
WeatherSky
typedef enum _WeatherSky WeatherSky
Definition at line 201 of file weather.h.
WeatherWindDirection
typedef enum _WeatherWindDirection WeatherWindDirection
Definition at line 189 of file weather.h.
Enumeration Type Documentation
_WeatherConditionPhenomenon
enum _WeatherConditionPhenomenon
Enumerator
PHENOMENON_INVALID
PHENOMENON_NONE
PHENOMENON_DRIZZLE
PHENOMENON_RAIN
PHENOMENON_SNOW
PHENOMENON_SNOW_GRAINS
PHENOMENON_ICE_CRYSTALS
PHENOMENON_ICE_PELLETS
PHENOMENON_HAIL
PHENOMENON_SMALL_HAIL
PHENOMENON_UNKNOWN_PRECIPITATION
PHENOMENON_MIST
PHENOMENON_FOG
PHENOMENON_SMOKE
PHENOMENON_VOLCANIC_ASH
PHENOMENON_SAND
PHENOMENON_HAZE
PHENOMENON_SPRAY
PHENOMENON_DUST
PHENOMENON_SQUALL
PHENOMENON_SANDSTORM
PHENOMENON_DUSTSTORM
PHENOMENON_FUNNEL_CLOUD
PHENOMENON_TORNADO
PHENOMENON_DUST_WHIRLS
PHENOMENON_LAST
Definition at line 203 of file weather.h.
_WeatherConditionQualifier
enum _WeatherConditionQualifier
Enumerator
QUALIFIER_INVALID
QUALIFIER_NONE
QUALIFIER_VICINITY
QUALIFIER_LIGHT
QUALIFIER_MODERATE
QUALIFIER_HEAVY
QUALIFIER_SHALLOW
QUALIFIER_PATCHES
QUALIFIER_PARTIAL
QUALIFIER_THUNDERSTORM
QUALIFIER_BLOWING
QUALIFIER_SHOWERS
QUALIFIER_DRIFTING
QUALIFIER_FREEZING
QUALIFIER_LAST
Definition at line 239 of file weather.h.
_WeatherForecastType
enum _WeatherForecastType
Enumerator
FORECAST_STATE
FORECAST_ZONE
FORECAST_LIST
Definition at line 68 of file weather.h.
_WeatherSky
enum _WeatherSky
Enumerator
SKY_INVALID
SKY_CLEAR
SKY_BROKEN
SKY_SCATTERED
SKY_FEW
SKY_OVERCAST
SKY_LAST
Definition at line 191 of file weather.h.
_WeatherWindDirection
enum _WeatherWindDirection
Enumerator
WIND_INVALID
WIND_VARIABLE
WIND_N
WIND_NNE
WIND_NE
WIND_ENE
WIND_E
WIND_ESE
WIND_SE
WIND_SSE
WIND_S
WIND_SSW
WIND_SW
WIND_WSW
WIND_W
WIND_WNW
WIND_NW
WIND_NNW
WIND_LAST
Definition at line 179 of file weather.h.
DistanceUnit
enum DistanceUnit
Enumerator
DISTANCE_UNIT_INVALID
DISTANCE_UNIT_DEFAULT
DISTANCE_UNIT_METERS
DISTANCE_UNIT_KM
DISTANCE_UNIT_MILES
Definition at line 103 of file weather.h.
PressureUnit
enum PressureUnit
Enumerator
PRESSURE_UNIT_INVALID
PRESSURE_UNIT_DEFAULT
PRESSURE_UNIT_KPA
PRESSURE_UNIT_HPA
PRESSURE_UNIT_MB
PRESSURE_UNIT_MM_HG
PRESSURE_UNIT_INCH_HG
PRESSURE_UNIT_ATM
Definition at line 92 of file weather.h.
SpeedUnit
enum SpeedUnit
Enumerator
SPEED_UNIT_INVALID
SPEED_UNIT_DEFAULT
SPEED_UNIT_MS
SPEED_UNIT_KPH
SPEED_UNIT_MPH
SPEED_UNIT_KNOTS
SPEED_UNIT_BFT
Definition at line 82 of file weather.h.
TempUnit
enum TempUnit
Enumerator
TEMP_UNIT_INVALID
TEMP_UNIT_DEFAULT
TEMP_UNIT_KELVIN
TEMP_UNIT_CENTIGRADE
TEMP_UNIT_FAHRENHEIT
Definition at line 74 of file weather.h.
Function Documentation
_weather_info_fill()
WeatherInfo * _weather_info_fill (WeatherInfo * info, WeatherLocation * location, const WeatherPrefs * prefs, WeatherInfoFunc cb, gpointer data)
Definition at line 479 of file weather.c.
References cb, data, _WeatherPrefs::distance_unit, FALSE, free_forecast_list(), iwin_start_open(), metar_start_open(), NULL, PHENOMENON_NONE, _WeatherPrefs::pressure_unit, QUALIFIER_NONE, _WeatherPrefs::radar, _WeatherPrefs::radar_custom_url, requests_init(), _WeatherPrefs::speed_unit, _WeatherPrefs::temperature_unit, _WeatherPrefs::type, weather_location_clone(), and wx_start_open().
weather_info_abort()
void weather_info_abort (WeatherInfo * info)
Definition at line 567 of file weather.c.
References NULL.
Referenced by weather_info_free().
weather_info_clone()
WeatherInfo * weather_info_clone (const WeatherInfo * info)
Definition at line 578 of file weather.c.
References _WeatherInfo::forecast, _WeatherInfo::forecast_list, _WeatherInfo::location, memmove, NULL, _WeatherInfo::radar, _WeatherInfo::radar_url, weather_info_clone(), and weather_location_clone().
Referenced by weather_info_clone().
weather_info_free()
void weather_info_free (WeatherInfo * info)
Definition at line 614 of file weather.c.
References free_forecast_list(), NULL, weather_info_abort(), and weather_location_free().
Referenced by free_forecast_list(), and mateweather_update().
weather_info_get_apparent()
const gchar * weather_info_get_apparent (WeatherInfo * info)
Definition at line 890 of file weather.c.
References _, FALSE, and NULL.
Referenced by mateweather_dialog_update(), and weather_info_setup_tooltip().
weather_info_get_conditions()
const gchar * weather_info_get_conditions (WeatherInfo * info)
Definition at line 741 of file weather.c.
References NULL, and weather_conditions_string().
Referenced by main(), mateweather_dialog_update(), weather_info_get_weather_summary(), and weather_info_setup_tooltip().
weather_info_get_dew()
const gchar * weather_info_get_dew (WeatherInfo * info)
Definition at line 857 of file weather.c.
References _, FALSE, and NULL.
Referenced by main(), and mateweather_dialog_update().
weather_info_get_forecast()
const gchar * weather_info_get_forecast (WeatherInfo * info)
Definition at line 1094 of file weather.c.
References NULL.
Referenced by mateweather_dialog_update().
weather_info_get_forecast_list()
GSList * weather_info_get_forecast_list (WeatherInfo * info)
weather_info_get_forecast_list: Returns list of WeatherInfo* objects for the forecast. The list is owned by the 'info' object thus is alive as long as the 'info'. This list is filled only when requested with type FORECAST_LIST and if available for given location. The 'update' property is the date/time when the forecast info is used for.
Definition at line 1110 of file weather.c.
References NULL.
weather_info_get_humidity()
const gchar * weather_info_get_humidity (WeatherInfo * info)
Definition at line 870 of file weather.c.
References _, and NULL.
Referenced by mateweather_dialog_update().
weather_info_get_icon_name()
const gchar * weather_info_get_icon_name (WeatherInfo * info)
Definition at line 1155 of file weather.c.
References FALSE, MOON_PHASES, NULL, _WeatherConditions::phenomenon, PHENOMENON_DRIZZLE, PHENOMENON_DUST, PHENOMENON_DUST_WHIRLS, PHENOMENON_DUSTSTORM, PHENOMENON_FOG, PHENOMENON_FUNNEL_CLOUD, PHENOMENON_HAIL, PHENOMENON_HAZE, PHENOMENON_ICE_CRYSTALS, PHENOMENON_ICE_PELLETS, PHENOMENON_INVALID, PHENOMENON_LAST, PHENOMENON_MIST, PHENOMENON_NONE, PHENOMENON_RAIN, PHENOMENON_SAND, PHENOMENON_SANDSTORM, PHENOMENON_SMALL_HAIL, PHENOMENON_SMOKE, PHENOMENON_SNOW, PHENOMENON_SNOW_GRAINS, PHENOMENON_SPRAY, PHENOMENON_SQUALL, PHENOMENON_TORNADO, PHENOMENON_UNKNOWN_PRECIPITATION, PHENOMENON_VOLCANIC_ASH, _WeatherConditions::qualifier, QUALIFIER_THUNDERSTORM, RADIANS_TO_DEGREES, _WeatherConditions::significant, SKY_BROKEN, SKY_CLEAR, SKY_FEW, SKY_INVALID, SKY_LAST, SKY_OVERCAST, SKY_SCATTERED, TRUE, weather_info_get_location(), and weather_info_get_value_moonphase().
Referenced by mateweather_dialog_update(), and weather_info_setup_tooltip().
weather_info_get_location()
const WeatherLocation * weather_info_get_location (WeatherInfo * info)
Definition at line 676 of file weather.c.
References NULL.
Referenced by mateweather_update(), and weather_info_get_icon_name().
weather_info_get_location_name()
const gchar * weather_info_get_location_name (WeatherInfo * info)
Definition at line 683 of file weather.c.
References NULL.
Referenced by mateweather_dialog_update(), and weather_info_get_weather_summary().
weather_info_get_pressure()
const gchar * weather_info_get_pressure (WeatherInfo * info)
Definition at line 968 of file weather.c.
References _, NULL, PRESSURE_INCH_TO_ATM, PRESSURE_INCH_TO_HPA, PRESSURE_INCH_TO_KPA, PRESSURE_INCH_TO_MB, PRESSURE_INCH_TO_MM, PRESSURE_UNIT_ATM, PRESSURE_UNIT_DEFAULT, PRESSURE_UNIT_HPA, PRESSURE_UNIT_INCH_HG, PRESSURE_UNIT_INVALID, PRESSURE_UNIT_KPA, PRESSURE_UNIT_MB, and PRESSURE_UNIT_MM_HG.
Referenced by main(), and mateweather_dialog_update().
weather_info_get_radar()
GdkPixbufAnimation * weather_info_get_radar (WeatherInfo * info)
Definition at line 1121 of file weather.c.
References NULL.
Referenced by mateweather_dialog_update().
weather_info_get_sky()
const gchar * weather_info_get_sky (WeatherInfo * info)
Definition at line 730 of file weather.c.
References _, NULL, and weather_sky_string().
Referenced by main(), mateweather_dialog_update(), weather_info_get_weather_summary(), and weather_info_setup_tooltip().
weather_info_get_sunrise()
const gchar * weather_info_get_sunrise (WeatherInfo * info)
Definition at line 1052 of file weather.c.
References _, calc_sun(), and NULL.
Referenced by mateweather_dialog_update().
weather_info_get_sunset()
const gchar * weather_info_get_sunset (WeatherInfo * info)
Definition at line 1073 of file weather.c.
References _, calc_sun(), and NULL.
Referenced by mateweather_dialog_update().
weather_info_get_temp()
const gchar * weather_info_get_temp (WeatherInfo * info)
Definition at line 818 of file weather.c.
References _, FALSE, and NULL.
Referenced by main(), mateweather_dialog_update(), and weather_info_setup_tooltip().
weather_info_get_temp_max()
const gchar * weather_info_get_temp_max (WeatherInfo * info)
Definition at line 844 of file weather.c.
References _, FALSE, and NULL.
weather_info_get_temp_min()
const gchar * weather_info_get_temp_min (WeatherInfo * info)
Definition at line 831 of file weather.c.
References _, FALSE, and NULL.
weather_info_get_temp_summary()
const gchar * weather_info_get_temp_summary (WeatherInfo * info)
Definition at line 1128 of file weather.c.
References NULL, and TRUE.
weather_info_get_upcoming_moonphases()
gboolean weather_info_get_upcoming_moonphases (WeatherInfo * info, time_t * phases)
weather_info_get_upcoming_moonphases: @info: WeatherInfo containing the time_t of interest @phases: An array of four time_t values that will hold the returned values. The values are estimates of the time of the next new, quarter, full and three-quarter moons.
Returns: gboolean indicating success or failure
Definition at line 1657 of file weather.c.
References calc_moon_phases(), FALSE, and NULL.
weather_info_get_update()
const gchar * weather_info_get_update (WeatherInfo * info)
Definition at line 691 of file weather.c.
References _, and NULL.
Referenced by mateweather_dialog_update().
weather_info_get_value_apparent()
gboolean weather_info_get_value_apparent (WeatherInfo * info, TempUnit unit, gdouble * value)
Definition at line 1532 of file weather.c.
References FALSE, and NULL.
weather_info_get_value_conditions()
gboolean weather_info_get_value_conditions (WeatherInfo * info, WeatherConditionPhenomenon * phenomenon, WeatherConditionQualifier * qualifier)
Definition at line 1459 of file weather.c.
References FALSE, NULL, PHENOMENON_INVALID, PHENOMENON_LAST, QUALIFIER_INVALID, QUALIFIER_LAST, and TRUE.
weather_info_get_value_dew()
gboolean weather_info_get_value_dew (WeatherInfo * info, TempUnit unit, gdouble * value)
Definition at line 1520 of file weather.c.
References FALSE, and NULL.
weather_info_get_value_moonphase()
gboolean weather_info_get_value_moonphase (WeatherInfo * info, WeatherMoonPhase * value, WeatherMoonLatitude * lat)
Definition at line 1586 of file weather.c.
References FALSE, NULL, and TRUE.
Referenced by weather_info_get_icon_name().
weather_info_get_value_pressure()
gboolean weather_info_get_value_pressure (WeatherInfo * info, PressureUnit unit, gdouble * value)
Definition at line 1624 of file weather.c.
References FALSE, and NULL.
weather_info_get_value_sky()
gboolean weather_info_get_value_sky (WeatherInfo * info, WeatherSky * sky)
Definition at line 1442 of file weather.c.
References FALSE, NULL, SKY_INVALID, SKY_LAST, and TRUE.
weather_info_get_value_sunrise()
gboolean weather_info_get_value_sunrise (WeatherInfo * info, time_t * value)
Definition at line 1558 of file weather.c.
References FALSE, NULL, and TRUE.
Referenced by weather_info_setup_tooltip().
weather_info_get_value_sunset()
gboolean weather_info_get_value_sunset (WeatherInfo * info, time_t * value)
Definition at line 1572 of file weather.c.
References FALSE, NULL, and TRUE.
Referenced by weather_info_setup_tooltip().
weather_info_get_value_temp()
gboolean weather_info_get_value_temp (WeatherInfo * info, TempUnit unit, gdouble * value)
Definition at line 1484 of file weather.c.
References FALSE, and NULL.
weather_info_get_value_temp_max()
gboolean weather_info_get_value_temp_max (WeatherInfo * info, TempUnit unit, gdouble * value)
Definition at line 1508 of file weather.c.
References FALSE, and NULL.
weather_info_get_value_temp_min()
gboolean weather_info_get_value_temp_min (WeatherInfo * info, TempUnit unit, gdouble * value)
Definition at line 1496 of file weather.c.
References FALSE, and NULL.
weather_info_get_value_update()
gboolean weather_info_get_value_update (WeatherInfo * info, time_t * value)
Definition at line 1544 of file weather.c.
References FALSE, NULL, and TRUE.
weather_info_get_value_visibility()
gboolean weather_info_get_value_visibility (WeatherInfo * info, DistanceUnit unit, gdouble * value)
Definition at line 1636 of file weather.c.
References FALSE, and NULL.
weather_info_get_value_wind()
gboolean weather_info_get_value_wind (WeatherInfo * info, SpeedUnit unit, gdouble * speed, WeatherWindDirection * direction)
Definition at line 1603 of file weather.c.
References FALSE, NULL, WIND_INVALID, and WIND_LAST.
weather_info_get_visibility()
const gchar * weather_info_get_visibility (WeatherInfo * info)
Definition at line 1016 of file weather.c.
References _, DISTANCE_UNIT_DEFAULT, DISTANCE_UNIT_INVALID, DISTANCE_UNIT_KM, DISTANCE_UNIT_METERS, DISTANCE_UNIT_MILES, NULL, VISIBILITY_SM_TO_KM, and VISIBILITY_SM_TO_M.
Referenced by main(), and mateweather_dialog_update().
weather_info_get_weather_summary()
gchar * weather_info_get_weather_summary (WeatherInfo * info)
Definition at line 1140 of file weather.c.
References _, NULL, weather_info_get_conditions(), weather_info_get_location_name(), and weather_info_get_sky().
weather_info_get_wind()
const gchar * weather_info_get_wind (WeatherInfo * info)
Definition at line 945 of file weather.c.
References _, NULL, and weather_wind_direction_string().
Referenced by main(), mateweather_dialog_update(), and weather_info_setup_tooltip().
weather_info_is_valid()
gboolean weather_info_is_valid (WeatherInfo * info)
Definition at line 640 of file weather.c.
References FALSE, and NULL.
weather_info_network_error()
gboolean weather_info_network_error (WeatherInfo * info)
Definition at line 647 of file weather.c.
References FALSE, and NULL.
weather_info_next_sun_event()
gint weather_info_next_sun_event (WeatherInfo * info)
weather_info_next_sun_event: @info: WeatherInfo structure
Returns: the interval, in seconds, until the next "sun event":
local midnight, when rise and set times are recomputed
next sunrise, when icon changes to daytime version
next sunset, when icon changes to nighttime version
Definition at line 323 of file weather-sun.c.
References calc_sun(), and NULL.
weather_info_to_imperial()
void weather_info_to_imperial (WeatherInfo * info)
Definition at line 665 of file weather.c.
References DISTANCE_UNIT_MILES, NULL, PRESSURE_UNIT_INCH_HG, SPEED_UNIT_MPH, and TEMP_UNIT_FAHRENHEIT.
weather_info_to_metric()
void weather_info_to_metric (WeatherInfo * info)
Definition at line 654 of file weather.c.
References DISTANCE_UNIT_METERS, NULL, PRESSURE_UNIT_HPA, SPEED_UNIT_MS, and TEMP_UNIT_CENTIGRADE.
Referenced by main().
weather_location_clone()
WeatherLocation * weather_location_clone (const WeatherLocation * location)
Definition at line 188 of file weather.c.
References _WeatherLocation::code, _WeatherLocation::coordinates, _WeatherLocation::country_code, _WeatherLocation::latitude, _WeatherLocation::latlon_valid, _WeatherLocation::longitude, _WeatherLocation::name, NULL, _WeatherLocation::radar, _WeatherLocation::tz_hint, weather_location_new(), and _WeatherLocation::zone.
Referenced by _weather_info_fill(), and weather_info_clone().
weather_location_equal()
gboolean weather_location_equal (const WeatherLocation * location1, const WeatherLocation * location2)
Definition at line 221 of file weather.c.
References _WeatherLocation::code, _WeatherLocation::name, and NULL.
Referenced by mateweather_update().
weather_location_free()
void weather_location_free (WeatherLocation * location)
Definition at line 205 of file weather.c.
References _WeatherLocation::code, _WeatherLocation::coordinates, _WeatherLocation::country_code, _WeatherLocation::name, _WeatherLocation::radar, _WeatherLocation::tz_hint, and _WeatherLocation::zone.
Referenced by mateweather_location_get_weather(), mateweather_prefs_load(), and weather_info_free().
weather_location_new()
WeatherLocation * weather_location_new (const gchar * trans_name, const gchar * code, const gchar * zone, const gchar * radar, const gchar * coordinates, const gchar * country_code, const gchar * tz_hint)
Definition at line 121 of file weather.c.
References _WeatherLocation::code, _WeatherLocation::coordinates, _WeatherLocation::country_code, FALSE, _WeatherLocation::latitude, _WeatherLocation::latlon_valid, _WeatherLocation::longitude, _WeatherLocation::name, name, NULL, _WeatherLocation::radar, TRUE, _WeatherLocation::tz_hint, _WeatherLocation::zone, and _WeatherLocation::zone_valid.
Referenced by mateweather_location_to_weather_location(), mateweather_prefs_load(), and weather_location_clone().