MATE Desktop Environment: weather-moon.c File Reference
weather-moon.c File Reference
#include <math.h>
#include <time.h>
#include <string.h>
#include <glib.h>
#include "weather-priv.h"
Macros
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
#define LUNAR_MEAN_LONGITUDE 218.316
#define LUNAR_PERIGEE_MEAN_LONG 318.15
#define LUNAR_NODE_MEAN_LONG 125.08
#define LUNAR_PROGRESSION 13.176358
#define LUNAR_INCLINATION DEGREES_TO_RADIANS(5.145396)
Functions
gboolean calc_moon (WeatherInfo *info)
gboolean calc_moon_phases (WeatherInfo *info, time_t *phases)
Macro Definition Documentation
LUNAR_INCLINATION
#define LUNAR_INCLINATION DEGREES_TO_RADIANS(5.145396)
Definition at line 51 of file weather-moon.c.
Referenced by calc_moon().
LUNAR_MEAN_LONGITUDE
#define LUNAR_MEAN_LONGITUDE 218.316
Definition at line 47 of file weather-moon.c.
Referenced by calc_moon().
LUNAR_NODE_MEAN_LONG
#define LUNAR_NODE_MEAN_LONG 125.08
Definition at line 49 of file weather-moon.c.
Referenced by calc_moon().
LUNAR_PERIGEE_MEAN_LONG
#define LUNAR_PERIGEE_MEAN_LONG 318.15
Definition at line 48 of file weather-moon.c.
Referenced by calc_moon().
LUNAR_PROGRESSION
#define LUNAR_PROGRESSION 13.176358
Definition at line 50 of file weather-moon.c.
Referenced by calc_moon(), and calc_moon_phases().
MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
Definition at line 38 of file weather-moon.c.
Function Documentation
calc_moon()
gboolean calc_moon (WeatherInfo * info)
calc_moon: @info: WeatherInfo containing time_t of interest. The values moonphase, moonlatitude and moonValid are updated on success.
Returns: gboolean indicating success or failure. moonphase is expressed as degrees where '0' is a new moon, '90' is first quarter, etc.
Definition at line 65 of file weather-moon.c.
References DEGREES_TO_RADIANS, ecl2equ(), EPOCH_TO_J2000, LUNAR_INCLINATION, LUNAR_MEAN_LONGITUDE, LUNAR_NODE_MEAN_LONG, LUNAR_PERIGEE_MEAN_LONG, LUNAR_PROGRESSION, MEAN_ECLIPTIC_LONGITUDE, PERIGEE_LONGITUDE, RADIANS_TO_DEGREES, sunEclipLongitude(), and TRUE.
Referenced by calc_moon_phases(), main(), and request_done().
calc_moon_phases()
gboolean calc_moon_phases (WeatherInfo * info, time_t * phases)
calc_moon_phases: @info: WeatherInfo containing the time_t of interest @phases: An array of four time_t values that will hold the returned values. The values are estimates of the time of the next new, quarter, full and three-quarter moons.
Returns: gboolean indicating success or failure
Definition at line 151 of file weather-moon.c.
References calc_moon(), FALSE, idx, LUNAR_PROGRESSION, _WeatherInfo::moonphase, NULL, TRUE, and _WeatherInfo::update.
Referenced by main(), and weather_info_get_upcoming_moonphases().