MATE Desktop Environment: weather-iwin.c File Reference
weather-iwin.c File Reference
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include <libxml/parser.h>
#include "weather.h"
#include "weather-priv.h"
Macros
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
#define XC (const xmlChar *)
#define isElem(_node, _name)
Functions
void iwin_start_open (WeatherInfo *info)
Macro Definition Documentation
isElem
#define isElem (_node, _name)
Value:
g_str_equal ((const char *)_node->name, _name)
MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
#define MATEWEATHER_I_KNOW_THIS_IS_UNSTABLE
Definition at line 29 of file weather-iwin.c.
XC
#define XC (const xmlChar *)
Function Documentation
iwin_start_open()
void iwin_start_open (WeatherInfo * info)
Definition at line 407 of file weather-iwin.c.
References bom_start_open(), FORECAST_LIST, free_forecast_list(), _WeatherLocation::latitude, _WeatherLocation::latlon_valid, _WeatherLocation::longitude, metoffice_start_open(), NULL, RADIANS_TO_DEGREES, and _WeatherLocation::zone.
Referenced by _weather_info_fill().