MATE Desktop Environment: window.c File Reference
window.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include "window-private.h"
#include "edge-resistance.h"
#include "util.h"
#include "frame-private.h"
#include "errors.h"
#include "workspace.h"
#include "stack.h"
#include "keybindings.h"
#include "ui.h"
#include "place.h"
#include "session.h"
#include "effects.h"
#include "prefs.h"
#include "resizepopup.h"
#include "xprops.h"
#include "group.h"
#include "window-props.h"
#include "constraints.h"
#include "compositor.h"
#include <X11/Xatom.h>
#include <X11/Xlibint.h>
#include <string.h>
Macros
#define N_INITIAL_PROPS 22
#define _NET_WM_MOVERESIZE_SIZE_TOPLEFT 0
#define _NET_WM_MOVERESIZE_SIZE_TOP 1
#define _NET_WM_MOVERESIZE_SIZE_TOPRIGHT 2
#define _NET_WM_MOVERESIZE_SIZE_RIGHT 3
#define _NET_WM_MOVERESIZE_SIZE_BOTTOMRIGHT 4
#define _NET_WM_MOVERESIZE_SIZE_BOTTOM 5
#define _NET_WM_MOVERESIZE_SIZE_BOTTOMLEFT 6
#define _NET_WM_MOVERESIZE_SIZE_LEFT 7
#define _NET_WM_MOVERESIZE_MOVE 8
#define _NET_WM_MOVERESIZE_SIZE_KEYBOARD 9
#define _NET_WM_MOVERESIZE_MOVE_KEYBOARD 10
#define _NET_WM_MOVERESIZE_CANCEL 11
#define MAX_N_ACTIONS 12
#define DRAG_THRESHOLD_TO_SHAKE_THRESHOLD_FACTOR 2
Functions
MetaWindow * meta_window_new (MetaDisplay *display, Window xwindow, gboolean must_be_viewable)
MetaWindow * meta_window_new_with_attrs (MetaDisplay *display, Window xwindow, gboolean must_be_viewable, XWindowAttributes *attrs)
void meta_window_free (MetaWindow *window, guint32 timestamp)
gboolean meta_window_located_on_workspace (MetaWindow *window, MetaWorkspace *workspace)
gboolean meta_window_showing_on_its_workspace (MetaWindow *window)
gboolean meta_window_should_be_showing (MetaWindow *window)
void meta_window_calc_showing (MetaWindow *window)
void meta_window_queue (MetaWindow *window, guint queuebits)
gboolean __window_is_terminal (MetaWindow *window)
void meta_window_minimize (MetaWindow *window)
void meta_window_unminimize (MetaWindow *window)
void meta_window_maximize_internal (MetaWindow *window, MetaMaximizeFlags directions, MetaRectangle *saved_rect)
void meta_window_maximize (MetaWindow *window, MetaMaximizeFlags directions)
void meta_window_tile (MetaWindow *window)
void meta_window_untile (MetaWindow *window)
gboolean meta_window_can_tile (MetaWindow *window)
void meta_window_unmaximize (MetaWindow *window, MetaMaximizeFlags directions)
void meta_window_move_to_monitor (MetaWindow *window, const MetaXineramaScreenInfo *from_monitor, const MetaXineramaScreenInfo *to_monitor)
void meta_window_make_above (MetaWindow *window)
void meta_window_unmake_above (MetaWindow *window)
void meta_window_make_fullscreen_internal (MetaWindow *window)
void meta_window_make_fullscreen (MetaWindow *window)
void meta_window_unmake_fullscreen (MetaWindow *window)
void meta_window_update_fullscreen_monitors (MetaWindow *window, unsigned long top, unsigned long bottom, unsigned long left, unsigned long right)
void meta_window_shade (MetaWindow *window, guint32 timestamp)
void meta_window_unshade (MetaWindow *window, guint32 timestamp)
void meta_window_activate (MetaWindow *window, guint32 timestamp)
void meta_window_activate_with_workspace (MetaWindow *window, guint32 timestamp, MetaWorkspace *workspace)
void meta_window_resize (MetaWindow *window, gboolean user_op, int w, int h)
void meta_window_move (MetaWindow *window, gboolean user_op, int root_x_nw, int root_y_nw)
void meta_window_move_resize (MetaWindow *window, gboolean user_op, int root_x_nw, int root_y_nw, int w, int h)
void meta_window_resize_with_gravity (MetaWindow *window, gboolean user_op, int w, int h, int gravity)
void meta_window_get_position (MetaWindow *window, int *x, int *y)
void meta_window_get_client_root_coords (MetaWindow *window, MetaRectangle *rect)
void meta_window_get_gravity_position (MetaWindow *window, int gravity, int *root_x, int *root_y)
void meta_window_get_geometry (MetaWindow *window, int *x, int *y, int *width, int *height)
void meta_window_get_input_rect (const MetaWindow *window, MetaRectangle *rect)
void meta_window_get_outer_rect (const MetaWindow *window, MetaRectangle *rect)
void meta_window_get_xor_rect (MetaWindow *window, const MetaRectangle *grab_wireframe_rect, MetaRectangle *xor_rect)
void meta_window_begin_wireframe (MetaWindow *window)
void meta_window_update_wireframe (MetaWindow *window, int x, int y, int width, int height)
void meta_window_end_wireframe (MetaWindow *window)
const char * meta_window_get_startup_id (MetaWindow *window)
void meta_window_focus (MetaWindow *window, guint32 timestamp)
void meta_window_change_workspace (MetaWindow *window, MetaWorkspace *workspace)
void meta_window_stick (MetaWindow *window)
void meta_window_unstick (MetaWindow *window)
unsigned long meta_window_get_net_wm_desktop (MetaWindow *window)
void meta_window_set_current_workspace_hint (MetaWindow *window)
MetaWindow * meta_window_find_root_ancestor (MetaWindow *window)
void meta_window_raise (MetaWindow *window)
void meta_window_lower (MetaWindow *window)
void meta_window_send_icccm_message (MetaWindow *window, Atom atom, guint32 timestamp)
void meta_window_move_resize_request (MetaWindow *window, guint value_mask, int gravity, int new_x, int new_y, int new_width, int new_height)
gboolean meta_window_configure_request (MetaWindow *window, XEvent *event)
gboolean meta_window_property_notify (MetaWindow *window, XEvent *event)
gboolean meta_window_client_message (MetaWindow *window, XEvent *event)
gboolean meta_window_notify_focus (MetaWindow *window, XEvent *event)
gboolean meta_window_get_icon_geometry (MetaWindow *window, MetaRectangle *rect)
void meta_window_update_role (MetaWindow *window)
void meta_window_update_net_wm_type (MetaWindow *window)
void meta_window_update_icon_now (MetaWindow *window)
MetaWorkspace * meta_window_get_workspace (MetaWindow *window)
GList * meta_window_get_workspaces (MetaWindow *window)
void meta_window_update_struts (MetaWindow *window)
void meta_window_recalc_window_type (MetaWindow *window)
void meta_window_frame_size_changed (MetaWindow *window)
void meta_window_recalc_features (MetaWindow *window)
void meta_window_show_menu (MetaWindow *window, int root_x, int root_y, int button, guint32 timestamp)
void meta_window_shove_titlebar_onscreen (MetaWindow *window)
gboolean meta_window_titlebar_is_onscreen (MetaWindow *window)
void meta_window_handle_mouse_grab_op_event (MetaWindow *window, XEvent *event)
void meta_window_set_gravity (MetaWindow *window, int gravity)
void meta_window_get_work_area_current_xinerama (MetaWindow *window, MetaRectangle *area)
void meta_window_get_work_area_for_xinerama (MetaWindow *window, int which_xinerama, MetaRectangle *area)
void meta_window_get_work_area_all_xineramas (MetaWindow *window, MetaRectangle *area)
void meta_window_get_current_tile_area (MetaWindow *window, MetaRectangle *tile_area)
gboolean meta_window_same_application (MetaWindow *window, MetaWindow *other_window)
void meta_window_refresh_resize_popup (MetaWindow *window)
void meta_window_foreach_transient (MetaWindow *window, MetaWindowForeachFunc func, void *data)
void meta_window_foreach_ancestor (MetaWindow *window, MetaWindowForeachFunc func, void *data)
gboolean meta_window_is_ancestor_of_transient (MetaWindow *window, MetaWindow *transient)
void meta_window_begin_grab_op (MetaWindow *window, MetaGrabOp op, gboolean frame_action, guint32 timestamp)
void meta_window_update_keyboard_resize (MetaWindow *window, gboolean update_cursor)
void meta_window_update_keyboard_move (MetaWindow *window)
void meta_window_update_layer (MetaWindow *window)
void meta_window_stack_just_below (MetaWindow *window, MetaWindow *below_this_one)
void meta_window_set_user_time (MetaWindow *window, guint32 timestamp)
void meta_window_set_demands_attention (MetaWindow *window)
void meta_window_unset_demands_attention (MetaWindow *window)
MetaFrame * meta_window_get_frame (MetaWindow *window)
gboolean meta_window_appears_focused (MetaWindow *window)
gboolean meta_window_has_focus (MetaWindow *window)
gboolean meta_window_is_shaded (MetaWindow *window)
MetaRectangle * meta_window_get_rect (MetaWindow *window)
MetaScreen * meta_window_get_screen (MetaWindow *window)
MetaDisplay * meta_window_get_display (MetaWindow *window)
Window meta_window_get_xwindow (MetaWindow *window)
MetaWindow * meta_window_get_transient_for (MetaWindow *window)
gboolean meta_window_is_maximized (MetaWindow *window)
gboolean meta_window_is_tiled_left (MetaWindow *window)
gboolean meta_window_is_tiled_right (MetaWindow *window)
gboolean meta_window_is_client_decorated (MetaWindow *window)
cairo_region_t * meta_window_get_frame_bounds (MetaWindow *window)
Macro Definition Documentation
_NET_WM_MOVERESIZE_CANCEL
#define _NET_WM_MOVERESIZE_CANCEL 11
Definition at line 5121 of file window.c.
Referenced by meta_window_client_message().
_NET_WM_MOVERESIZE_MOVE
#define _NET_WM_MOVERESIZE_MOVE 8
Definition at line 5118 of file window.c.
Referenced by meta_window_client_message().
_NET_WM_MOVERESIZE_MOVE_KEYBOARD
#define _NET_WM_MOVERESIZE_MOVE_KEYBOARD 10
Definition at line 5120 of file window.c.
Referenced by meta_window_client_message().
_NET_WM_MOVERESIZE_SIZE_BOTTOM
#define _NET_WM_MOVERESIZE_SIZE_BOTTOM 5
Definition at line 5115 of file window.c.
Referenced by meta_window_client_message().
_NET_WM_MOVERESIZE_SIZE_BOTTOMLEFT
#define _NET_WM_MOVERESIZE_SIZE_BOTTOMLEFT 6
Definition at line 5116 of file window.c.
Referenced by meta_window_client_message().
_NET_WM_MOVERESIZE_SIZE_BOTTOMRIGHT
#define _NET_WM_MOVERESIZE_SIZE_BOTTOMRIGHT 4
Definition at line 5114 of file window.c.
Referenced by meta_window_client_message().
_NET_WM_MOVERESIZE_SIZE_KEYBOARD
#define _NET_WM_MOVERESIZE_SIZE_KEYBOARD 9
Definition at line 5119 of file window.c.
Referenced by meta_window_client_message().
_NET_WM_MOVERESIZE_SIZE_LEFT
#define _NET_WM_MOVERESIZE_SIZE_LEFT 7
Definition at line 5117 of file window.c.
Referenced by meta_window_client_message().
_NET_WM_MOVERESIZE_SIZE_RIGHT
#define _NET_WM_MOVERESIZE_SIZE_RIGHT 3
Definition at line 5113 of file window.c.
Referenced by meta_window_client_message().
_NET_WM_MOVERESIZE_SIZE_TOP
#define _NET_WM_MOVERESIZE_SIZE_TOP 1
Definition at line 5111 of file window.c.
Referenced by meta_window_client_message().
_NET_WM_MOVERESIZE_SIZE_TOPLEFT
#define _NET_WM_MOVERESIZE_SIZE_TOPLEFT 0
Definition at line 5110 of file window.c.
Referenced by meta_window_client_message().
_NET_WM_MOVERESIZE_SIZE_TOPRIGHT
#define _NET_WM_MOVERESIZE_SIZE_TOPRIGHT 2
Definition at line 5112 of file window.c.
Referenced by meta_window_client_message().
DRAG_THRESHOLD_TO_SHAKE_THRESHOLD_FACTOR
#define DRAG_THRESHOLD_TO_SHAKE_THRESHOLD_FACTOR 2
MAX_N_ACTIONS
#define MAX_N_ACTIONS 12
N_INITIAL_PROPS
#define N_INITIAL_PROPS 22
Function Documentation
__window_is_terminal()
gboolean __window_is_terminal (MetaWindow * window)
Definition at line 1941 of file window.c.
References FALSE, NULL, and TRUE.
Referenced by meta_window_set_user_time().
meta_window_activate()
void meta_window_activate (MetaWindow * window, guint32 timestamp)
Definition at line 3236 of file window.c.
References META_CLIENT_TYPE_PAGER, and NULL.
meta_window_activate_with_workspace()
void meta_window_activate_with_workspace (MetaWindow * window, guint32 timestamp, MetaWorkspace * workspace)
Definition at line 3247 of file window.c.
References META_CLIENT_TYPE_APPLICATION.
meta_window_appears_focused()
gboolean meta_window_appears_focused (MetaWindow * window)
Definition at line 8929 of file window.c.
References FALSE, meta_prefs_get_attach_modal_dialogs(), META_WINDOW_DOCK, meta_window_foreach_transient(), META_WINDOW_SPLASHSCREEN, and TRUE.
Referenced by meta_frame_get_flags().
meta_window_begin_grab_op()
void meta_window_begin_grab_op (MetaWindow * window, MetaGrabOp op, gboolean frame_action, guint32 timestamp)
Definition at line 8660 of file window.c.
References FALSE, meta_display_begin_grab_op(), and op.
Referenced by meta_window_client_message().
meta_window_begin_wireframe()
void meta_window_begin_wireframe (MetaWindow * window)
Definition at line 4280 of file window.c.
References meta_effects_begin_wireframe(), meta_window_get_client_root_coords(), and meta_window_get_xor_rect().
Referenced by meta_display_begin_grab_op().
meta_window_calc_showing()
void meta_window_calc_showing (MetaWindow * window)
Definition at line 1546 of file window.c.
References meta_window_should_be_showing().
Referenced by meta_display_begin_grab_op(), and meta_display_end_grab_op().
meta_window_can_tile()
gboolean meta_window_can_tile (MetaWindow * window)
Definition at line 2759 of file window.c.
References FALSE, _MetaRectangle::height, meta_frame_calc_borders(), meta_screen_get_current_xinerama(), meta_window_get_work_area_for_xinerama(), _MetaFrameBorders::visible, and _MetaRectangle::width.
meta_window_change_workspace()
void meta_window_change_workspace (MetaWindow * window, MetaWorkspace * workspace)
Definition at line 4527 of file window.c.
References meta_window_foreach_ancestor(), and meta_window_foreach_transient().
Referenced by meta_core_change_workspace(), meta_window_client_message(), meta_window_focus(), and meta_workspace_activate_with_focus().
meta_window_client_message()
gboolean meta_window_client_message (MetaWindow * window, XEvent * event)
Definition at line 5124 of file window.c.
References _NET_WM_MOVERESIZE_CANCEL, _NET_WM_MOVERESIZE_MOVE, _NET_WM_MOVERESIZE_MOVE_KEYBOARD, _NET_WM_MOVERESIZE_SIZE_BOTTOM, _NET_WM_MOVERESIZE_SIZE_BOTTOMLEFT, _NET_WM_MOVERESIZE_SIZE_BOTTOMRIGHT, _NET_WM_MOVERESIZE_SIZE_KEYBOARD, _NET_WM_MOVERESIZE_SIZE_LEFT, _NET_WM_MOVERESIZE_SIZE_RIGHT, _NET_WM_MOVERESIZE_SIZE_TOP, _NET_WM_MOVERESIZE_SIZE_TOPLEFT, _NET_WM_MOVERESIZE_SIZE_TOPRIGHT, _NET_WM_STATE_ADD, _NET_WM_STATE_TOGGLE, action, FALSE, mask, META_CLIENT_TYPE_MAX_RECOGNIZED, META_CLIENT_TYPE_UNKNOWN, META_DEBUG_WINDOW_OPS, meta_display_begin_grab_op(), meta_display_end_grab_op(), meta_display_get_current_time(), meta_display_get_current_time_roundtrip(), meta_error_trap_pop(), meta_error_trap_pop_with_return(), meta_error_trap_push(), META_GRAB_OP_KEYBOARD_MOVING, META_GRAB_OP_KEYBOARD_RESIZING_UNKNOWN, META_GRAB_OP_MOVING, META_GRAB_OP_NONE, META_GRAB_OP_RESIZING_E, META_GRAB_OP_RESIZING_N, META_GRAB_OP_RESIZING_NE, META_GRAB_OP_RESIZING_NW, META_GRAB_OP_RESIZING_S, META_GRAB_OP_RESIZING_SE, META_GRAB_OP_RESIZING_SW, META_GRAB_OP_RESIZING_W, meta_is_verbose(), META_MAXIMIZE_HORIZONTAL, META_MAXIMIZE_VERTICAL, meta_prefs_get_raise_on_click(), META_QUEUE_MOVE_RESIZE, meta_screen_get_workspace_by_index(), meta_warning(), meta_window_begin_grab_op(), meta_window_change_workspace(), meta_window_delete(), meta_window_make_fullscreen(), meta_window_maximize(), meta_window_minimize(), meta_window_move_resize_request(), meta_window_queue(), meta_window_raise(), meta_window_set_demands_attention(), meta_window_shade(), meta_window_show_menu(), meta_window_stick(), meta_window_unmake_fullscreen(), meta_window_unmaximize(), meta_window_unset_demands_attention(), meta_window_unshade(), meta_window_unstick(), meta_window_update_fullscreen_monitors(), meta_window_update_layer(), meta_XFree, NULL, op, TRUE, and _MetaDisplay::xdisplay.
meta_window_configure_request()
gboolean meta_window_configure_request (MetaWindow * window, XEvent * event)
Definition at line 5020 of file window.c.
References _MetaWindow::desc, _MetaWindow::display, _MetaDisplay::expected_focus_window, META_DEBUG_STACK, meta_prefs_get_disable_workarounds(), meta_window_lower(), meta_window_move_resize_request(), meta_window_raise(), meta_window_same_application(), meta_window_set_demands_attention(), _MetaWindow::net_wm_user_time, TRUE, and XSERVER_TIME_IS_BEFORE.
meta_window_end_wireframe()
void meta_window_end_wireframe (MetaWindow * window)
Definition at line 4339 of file window.c.
References meta_effects_end_wireframe().
Referenced by meta_display_end_grab_op().
meta_window_find_root_ancestor()
MetaWindow * meta_window_find_root_ancestor (MetaWindow * window)
Definition at line 4732 of file window.c.
References meta_window_foreach_ancestor().
Referenced by meta_window_compute_group(), and meta_window_raise().
meta_window_focus()
void meta_window_focus (MetaWindow * window, guint32 timestamp)
Definition at line 4403 of file window.c.
References _MetaScreen::active_workspace, _MetaWindow::desc, FALSE, META_DEBUG_FOCUS, meta_display_set_input_focus_window(), meta_effect_run_focus(), meta_window_change_workspace(), meta_window_send_icccm_message(), meta_window_unset_demands_attention(), NULL, _MetaWindow::on_all_workspaces, _MetaWindow::screen, _MetaWorkspace::screen, TRUE, _MetaWindow::unmanaging, and _MetaWindow::workspace.
Referenced by meta_core_show_window_menu(), meta_core_user_focus(), meta_screen_show_desktop(), meta_window_grab_all_keys(), meta_window_shade(), meta_window_unshade(), meta_workspace_activate_with_focus(), and meta_workspace_focus_default_window().
meta_window_foreach_ancestor()
void meta_window_foreach_ancestor (MetaWindow * window, MetaWindowForeachFunc func, void * data)
Definition at line 8456 of file window.c.
References data, _MetaWindow::display, meta_display_lookup_x_window(), NULL, _MetaWindow::transient_parent_is_root_window, TRUE, and _MetaWindow::xtransient_for.
Referenced by meta_window_change_workspace(), meta_window_find_root_ancestor(), meta_window_is_ancestor_of_transient(), and meta_window_showing_on_its_workspace().
meta_window_foreach_transient()
void meta_window_foreach_transient (MetaWindow * window, MetaWindowForeachFunc func, void * data)
Definition at line 8429 of file window.c.
References data, meta_display_list_windows(), meta_window_is_ancestor_of_transient(), and NULL.
Referenced by meta_window_appears_focused(), meta_window_change_workspace(), meta_window_minimize(), meta_window_new_with_attrs(), meta_window_stick(), meta_window_unminimize(), and meta_window_unstick().
meta_window_frame_size_changed()
void meta_window_frame_size_changed (MetaWindow * window)
Definition at line 6614 of file window.c.
References meta_frame_clear_cached_borders().
Referenced by meta_window_make_above(), meta_window_maximize_internal(), meta_window_shade(), meta_window_unmake_above(), meta_window_unmaximize(), and meta_window_unshade().
meta_window_free()
void meta_window_free (MetaWindow * window, guint32 timestamp)
Definition at line 1004 of file window.c.
References FALSE, meta_bug(), meta_compositor_free_window(), meta_compositor_set_active_window(), META_DEBUG_FOCUS, META_DEBUG_WORKAREA, meta_display_end_grab_op(), META_DISPLAY_HAS_SHAPE, meta_display_ungrab_focus_window_button(), meta_display_ungrab_window_buttons(), meta_display_unregister_x_window(), meta_error_trap_pop(), meta_error_trap_push(), meta_group_update_layers(), META_QUEUE_CALC_SHOWING, META_QUEUE_MOVE_RESIZE, META_QUEUE_UPDATE_ICON, meta_stack_freeze(), meta_stack_remove(), meta_stack_thaw(), meta_ui_window_menu_free(), meta_window_destroy_frame(), meta_window_free_delete_dialog(), meta_window_get_group(), meta_window_shutdown_group(), meta_window_ungrab_keys(), meta_workspace_focus_default_window(), meta_workspace_remove_window(), _MetaWorkspace::mru_list, NULL, TRUE, and _MetaWorkspace::windows.
Referenced by meta_display_unmanage_windows_for_screen().
meta_window_get_client_root_coords()
void meta_window_get_client_root_coords (MetaWindow * window, MetaRectangle * rect)
Definition at line 4059 of file window.c.
References _MetaRectangle::height, meta_window_get_position(), _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_display_begin_grab_op(), meta_window_begin_wireframe(), meta_window_move_to_monitor(), meta_window_refresh_resize_popup(), and meta_window_unmaximize().
meta_window_get_current_tile_area()
void meta_window_get_current_tile_area (MetaWindow * window, MetaRectangle * tile_area)
Definition at line 8243 of file window.c.
References _MetaRectangle::height, int(), meta_screen_get_xinerama_for_window(), META_TILE_BOTTOM_LEFT, META_TILE_BOTTOM_RIGHT, META_TILE_CYCLE_100, META_TILE_CYCLE_25, META_TILE_CYCLE_33, META_TILE_CYCLE_50, META_TILE_CYCLE_66, META_TILE_CYCLE_75, META_TILE_CYCLE_NONE, META_TILE_MAXIMIZED, META_TILE_NONE, META_TILE_RIGHT, META_TILE_TOP_LEFT, META_TILE_TOP_RIGHT, meta_warning(), meta_window_get_work_area_for_xinerama(), _MetaXineramaScreenInfo::number, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_window_unmake_fullscreen().
meta_window_get_display()
MetaDisplay * meta_window_get_display (MetaWindow * window)
Definition at line 8973 of file window.c.
meta_window_get_frame()
MetaFrame * meta_window_get_frame (MetaWindow * window)
Definition at line 8913 of file window.c.
meta_window_get_frame_bounds()
cairo_region_t * meta_window_get_frame_bounds (MetaWindow * window)
meta_window_get_frame_bounds:
Gets a region representing the outer bounds of the window's frame.
Return value: (transfer none) (allow-none): a #cairo_region_t holding the outer bounds of the window, or NULL if the window doesn't have a frame.
Definition at line 9053 of file window.c.
References meta_frame_get_frame_bounds().
meta_window_get_geometry()
void meta_window_get_geometry (MetaWindow * window, int * x, int * y, int * width, int * height)
Definition at line 4152 of file window.c.
References meta_window_get_gravity_position().
meta_window_get_gravity_position()
void meta_window_get_gravity_position (MetaWindow * window, int gravity, int * root_x, int * root_y)
Definition at line 4068 of file window.c.
References _MetaRectangle::height, NULL, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_window_get_geometry(), and meta_window_move_resize_request().
meta_window_get_icon_geometry()
gboolean meta_window_get_icon_geometry (MetaWindow * window, MetaRectangle * rect)
Definition at line 5914 of file window.c.
References FALSE, _MetaRectangle::height, meta_prop_get_cardinal_list(), meta_XFree, NULL, TRUE, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_screen_ensure_tab_popup().
meta_window_get_input_rect()
void meta_window_get_input_rect (const MetaWindow * window, MetaRectangle * rect)
meta_window_get_input_rect: @window: a MetaWindow @rect: (out): pointer to an allocated MetaRectangle
Gets the rectangle that bounds @window that is responsive to mouse events. This includes decorations - the visible portion of its border - and (if present) any invisible area that we make make responsive to mouse clicks in order to allow convenient border dragging.
Definition at line 4179 of file window.c.
meta_window_get_net_wm_desktop()
unsigned long meta_window_get_net_wm_desktop (MetaWindow * window)
Definition at line 4648 of file window.c.
References meta_workspace_index().
Referenced by meta_core_get(), meta_window_set_current_workspace_hint(), and meta_window_show_menu().
meta_window_get_outer_rect()
void meta_window_get_outer_rect (const MetaWindow * window, MetaRectangle * rect)
meta_window_get_outer_rect: @window: a MetaWindow @rect: (out): pointer to an allocated MetaRectangle
Gets the rectangle that bounds @window that is responsive to mouse events. This includes only what is visible; it doesn't include any extra reactive area we add to the edges of windows.
Definition at line 4198 of file window.c.
References _MetaRectangle::height, _MetaFrameBorders::invisible, meta_frame_calc_borders(), _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_screen_ensure_tab_popup(), meta_screen_get_xinerama_for_window(), meta_window_edge_resistance_for_move(), meta_window_edge_resistance_for_resize(), meta_window_place(), meta_window_set_demands_attention(), meta_window_shove_titlebar_onscreen(), and meta_window_titlebar_is_onscreen().
meta_window_get_position()
void meta_window_get_position (MetaWindow * window, int * x, int * y)
Definition at line 4038 of file window.c.
Referenced by meta_core_get(), meta_window_get_client_root_coords(), meta_window_place(), meta_window_resize(), and meta_window_resize_with_gravity().
meta_window_get_rect()
MetaRectangle * meta_window_get_rect (MetaWindow * window)
Definition at line 8961 of file window.c.
meta_window_get_screen()
MetaScreen * meta_window_get_screen (MetaWindow * window)
Definition at line 8967 of file window.c.
meta_window_get_startup_id()
const char * meta_window_get_startup_id (MetaWindow * window)
Definition at line 4348 of file window.c.
References meta_group_get_startup_id(), meta_window_get_group(), and NULL.
Referenced by meta_screen_apply_startup_properties().
meta_window_get_transient_for()
MetaWindow * meta_window_get_transient_for (MetaWindow * window)
meta_window_get_transient_for: @window: a MetaWindow
Returns the MetaWindow for the window that is pointed to by the WM_TRANSIENT_FOR hint on this window (see XGetTransientForHint() or XSetTransientForHint()). Marco keeps transient windows above their parents. A typical usage of this hint is for a dialog that wants to stay above its associated window.
Return value: (transfer none): the window this window is transient for, or NULL if the WM_TRANSIENT_FOR hint is unset or does not point to a toplevel window that Marco knows about.
Definition at line 8999 of file window.c.
References meta_display_lookup_x_window(), and NULL.
Referenced by meta_core_get().
meta_window_get_work_area_all_xineramas()
void meta_window_get_work_area_all_xineramas (MetaWindow * window, MetaRectangle * area)
Definition at line 8217 of file window.c.
References _MetaRectangle::height, META_DEBUG_WORKAREA, meta_rectangle_intersect(), meta_window_get_workspaces(), meta_workspace_get_work_area_all_xineramas(), NULL, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
meta_window_get_work_area_current_xinerama()
void meta_window_get_work_area_current_xinerama (MetaWindow * window, MetaRectangle * area)
Definition at line 8192 of file window.c.
References meta_screen_get_xinerama_for_window(), meta_window_get_work_area_for_xinerama(), NULL, and _MetaXineramaScreenInfo::number.
meta_window_get_work_area_for_xinerama()
void meta_window_get_work_area_for_xinerama (MetaWindow * window, int which_xinerama, MetaRectangle * area)
Definition at line 8205 of file window.c.
Referenced by meta_window_can_tile(), meta_window_get_current_tile_area(), meta_window_get_work_area_current_xinerama(), and meta_window_place().
meta_window_get_workspace()
MetaWorkspace * meta_window_get_workspace (MetaWindow * window)
Definition at line 6252 of file window.c.
References _MetaScreen::active_workspace, and _MetaWorkspace::screen.
Referenced by meta_stack_lower(), and meta_stack_raise().
meta_window_get_workspaces()
GList * meta_window_get_workspaces (MetaWindow * window)
Definition at line 6261 of file window.c.
References _MetaWorkspace::screen, and _MetaScreen::workspaces.
Referenced by meta_window_get_work_area_all_xineramas().
meta_window_get_xor_rect()
void meta_window_get_xor_rect (MetaWindow * window, const MetaRectangle * grab_wireframe_rect, MetaRectangle * xor_rect)
Definition at line 4228 of file window.c.
References _MetaRectangle::height, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_window_begin_wireframe(), meta_window_edge_resistance_for_move(), meta_window_edge_resistance_for_resize(), and meta_window_update_wireframe().
meta_window_get_xwindow()
Window meta_window_get_xwindow (MetaWindow * window)
Definition at line 8979 of file window.c.
meta_window_handle_mouse_grab_op_event()
void meta_window_handle_mouse_grab_op_event (MetaWindow * window, XEvent * event)
Definition at line 7999 of file window.c.
References FALSE, meta_compositor_set_updates(), META_DEBUG_RESIZING, meta_display_check_threshold_reached(), meta_display_end_grab_op(), meta_grab_op_is_moving(), meta_grab_op_is_resizing(), META_GRAB_OP_KEYBOARD_RESIZING_E, META_GRAB_OP_KEYBOARD_RESIZING_N, META_GRAB_OP_KEYBOARD_RESIZING_NE, META_GRAB_OP_KEYBOARD_RESIZING_NW, META_GRAB_OP_KEYBOARD_RESIZING_S, META_GRAB_OP_KEYBOARD_RESIZING_SE, META_GRAB_OP_KEYBOARD_RESIZING_SW, META_GRAB_OP_KEYBOARD_RESIZING_W, META_GRAB_OP_RESIZING_E, META_GRAB_OP_RESIZING_N, META_GRAB_OP_RESIZING_NE, META_GRAB_OP_RESIZING_NW, META_GRAB_OP_RESIZING_S, META_GRAB_OP_RESIZING_SE, META_GRAB_OP_RESIZING_SW, META_GRAB_OP_RESIZING_W, META_MAXIMIZE_HORIZONTAL, META_MAXIMIZE_VERTICAL, META_TILE_MAXIMIZED, META_TILE_NONE, meta_window_maximize(), meta_window_tile(), and TRUE.
meta_window_has_focus()
gboolean meta_window_has_focus (MetaWindow * window)
Definition at line 8949 of file window.c.
meta_window_is_ancestor_of_transient()
gboolean meta_window_is_ancestor_of_transient (MetaWindow * window, MetaWindow * transient)
Definition at line 8525 of file window.c.
References FALSE, and meta_window_foreach_ancestor().
Referenced by meta_window_foreach_transient().
meta_window_is_client_decorated()
gboolean meta_window_is_client_decorated (MetaWindow * window)
meta_window_is_client_decorated:
Check if if the window has decorations drawn by the client. (window->decorated refers only to whether we should add decorations)
Definition at line 9032 of file window.c.
Referenced by meta_window_move_resize_request().
meta_window_is_maximized()
gboolean meta_window_is_maximized (MetaWindow * window)
Definition at line 9008 of file window.c.
References META_WINDOW_MAXIMIZED.
meta_window_is_shaded()
gboolean meta_window_is_shaded (MetaWindow * window)
Definition at line 8955 of file window.c.
meta_window_is_tiled_left()
gboolean meta_window_is_tiled_left (MetaWindow * window)
Definition at line 9014 of file window.c.
References META_WINDOW_TILED_LEFT.
meta_window_is_tiled_right()
gboolean meta_window_is_tiled_right (MetaWindow * window)
Definition at line 9020 of file window.c.
References META_WINDOW_TILED_RIGHT.
meta_window_located_on_workspace()
gboolean meta_window_located_on_workspace (MetaWindow * window, MetaWorkspace * workspace)
Definition at line 1347 of file window.c.
References _MetaWorkspace::screen.
Referenced by meta_core_user_lower_and_unfocus(), meta_display_get_tab_current(), meta_stack_list_windows(), meta_stack_lower(), meta_stack_raise(), meta_window_notify_focus(), meta_window_should_be_showing(), and meta_workspace_list_windows().
meta_window_lower()
void meta_window_lower (MetaWindow * window)
Definition at line 4781 of file window.c.
References META_DEBUG_WINDOW_OPS, and meta_stack_lower().
Referenced by meta_core_user_lower_and_unfocus(), and meta_window_configure_request().
meta_window_make_above()
void meta_window_make_above (MetaWindow * window)
Definition at line 2944 of file window.c.
References meta_window_frame_size_changed(), meta_window_raise(), meta_window_update_layer(), and TRUE.
Referenced by meta_core_make_above().
meta_window_make_fullscreen()
void meta_window_make_fullscreen (MetaWindow * window)
Definition at line 3002 of file window.c.
References META_QUEUE_MOVE_RESIZE, meta_window_make_fullscreen_internal(), and meta_window_queue().
Referenced by meta_window_client_message().
meta_window_make_fullscreen_internal()
void meta_window_make_fullscreen_internal (MetaWindow * window)
Definition at line 2966 of file window.c.
References FALSE, META_DEBUG_WINDOW_OPS, meta_display_get_current_time_roundtrip(), meta_stack_freeze(), meta_stack_thaw(), meta_window_raise(), meta_window_unshade(), meta_window_update_layer(), and TRUE.
Referenced by meta_window_make_fullscreen(), and meta_window_move_resize_request().
meta_window_maximize()
void meta_window_maximize (MetaWindow * window, MetaMaximizeFlags directions)
Definition at line 2612 of file window.c.
References FALSE, meta_compositor_maximize_window(), meta_display_get_current_time_roundtrip(), META_MAXIMIZE_HORIZONTAL, META_MAXIMIZE_VERTICAL, META_QUEUE_MOVE_RESIZE, META_TILE_NONE, meta_window_maximize_internal(), meta_window_queue(), meta_window_unshade(), and NULL.
Referenced by meta_core_maximize(), meta_core_toggle_maximize(), meta_core_toggle_maximize_horizontally(), meta_core_toggle_maximize_vertically(), meta_window_client_message(), and meta_window_handle_mouse_grab_op_event().
meta_window_maximize_internal()
void meta_window_maximize_internal (MetaWindow * window, MetaMaximizeFlags directions, MetaRectangle * saved_rect)
Definition at line 2566 of file window.c.
References META_DEBUG_WINDOW_OPS, META_MAXIMIZE_HORIZONTAL, META_MAXIMIZE_VERTICAL, meta_window_frame_size_changed(), NULL, and TRUE.
Referenced by meta_window_maximize(), and meta_window_tile().
meta_window_minimize()
void meta_window_minimize (MetaWindow * window)
Definition at line 2420 of file window.c.
References META_DEBUG_FOCUS, META_QUEUE_CALC_SHOWING, meta_window_foreach_transient(), meta_window_queue(), NULL, and TRUE.
Referenced by meta_core_minimize(), meta_screen_minimize_all_on_active_workspace_except(), and meta_window_client_message().
meta_window_move()
void meta_window_move (MetaWindow * window, gboolean user_op, int root_x_nw, int root_y_nw)
Definition at line 3931 of file window.c.
References META_IS_MOVE_ACTION, and META_IS_USER_ACTION.
Referenced by meta_core_user_move(), and meta_display_end_grab_op().
meta_window_move_resize()
void meta_window_move_resize (MetaWindow * window, gboolean user_op, int root_x_nw, int root_y_nw, int w, int h)
Definition at line 3947 of file window.c.
References META_IS_MOVE_ACTION, META_IS_RESIZE_ACTION, and META_IS_USER_ACTION.
Referenced by meta_window_move_to_monitor(), meta_window_shove_titlebar_onscreen(), meta_window_unmake_fullscreen(), and meta_window_unmaximize().
meta_window_move_resize_request()
void meta_window_move_resize_request (MetaWindow * window, guint value_mask, int gravity, int new_x, int new_y, int new_width, int new_height)
Definition at line 4826 of file window.c.
References FALSE, _MetaRectangle::height, META_DEBUG_GEOMETRY, META_GRAB_OP_MOVING, META_GRAB_OP_NONE, META_GRAB_OP_RESIZING_E, META_GRAB_OP_RESIZING_N, META_GRAB_OP_RESIZING_NE, META_GRAB_OP_RESIZING_NW, META_GRAB_OP_RESIZING_S, META_GRAB_OP_RESIZING_SE, META_GRAB_OP_RESIZING_SW, META_GRAB_OP_RESIZING_W, META_IS_CONFIGURE_REQUEST, META_IS_MOVE_ACTION, META_IS_RESIZE_ACTION, meta_prefs_get_disable_workarounds(), meta_prefs_get_force_fullscreen(), meta_rectangle_equal(), meta_screen_get_xinerama_for_rect(), META_WINDOW_DIALOG, meta_window_get_gravity_position(), meta_window_is_client_decorated(), meta_window_make_fullscreen_internal(), META_WINDOW_MODAL_DIALOG, META_WINDOW_SPLASHSCREEN, _MetaXineramaScreenInfo::rect, TRUE, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_window_client_message(), and meta_window_configure_request().
meta_window_move_to_monitor()
void meta_window_move_to_monitor (MetaWindow * window, const MetaXineramaScreenInfo * from_monitor, const MetaXineramaScreenInfo * to_monitor)
Definition at line 2884 of file window.c.
References _MetaRectangle::height, meta_window_get_client_root_coords(), meta_window_move_resize(), meta_window_tile(), META_WINDOW_TILED, _MetaXineramaScreenInfo::number, _MetaXineramaScreenInfo::rect, TRUE, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
meta_window_new()
MetaWindow * meta_window_new (MetaDisplay * display, Window xwindow, gboolean must_be_viewable)
Definition at line 211 of file window.c.
References FALSE, meta_display_grab(), meta_display_ungrab(), meta_error_trap_pop(), meta_error_trap_pop_with_return(), meta_error_trap_push(), meta_window_new_with_attrs(), NULL, TRUE, and _MetaDisplay::xdisplay.
meta_window_new_with_attrs()
MetaWindow * meta_window_new_with_attrs (MetaDisplay * display, Window xwindow, gboolean must_be_viewable, XWindowAttributes * attrs)
Definition at line 255 of file window.c.
References _MetaScreen::active_workspace, _MetaWindow::desc, _MetaDisplay::display_opening, FALSE, META_DEBUG_PLACEMENT, META_DEBUG_SHAPES, meta_display_get_current_time_roundtrip(), meta_display_grab(), meta_display_grab_focus_window_button(), meta_display_grab_window_buttons(), META_DISPLAY_HAS_SHAPE, meta_display_lookup_x_window(), meta_display_register_x_window(), meta_display_ungrab(), meta_display_xwindow_is_a_no_focus_window(), meta_error_trap_pop(), meta_error_trap_pop_with_return(), meta_error_trap_push(), meta_icon_cache_init(), META_IS_CONFIGURE_REQUEST, META_IS_MOVE_ACTION, META_IS_RESIZE_ACTION, META_LAYER_LAST, meta_prop_get_cardinal_with_atom_type(), META_QUEUE_CALC_SHOWING, meta_screen_apply_startup_properties(), meta_screen_get_workspace_by_index(), meta_set_normal_hints(), meta_stack_add(), meta_stack_freeze(), meta_stack_thaw(), META_TILE_NONE, META_TYPE_WINDOW, meta_window_compute_group(), META_WINDOW_DESKTOP, META_WINDOW_DOCK, meta_window_ensure_frame(), meta_window_foreach_transient(), meta_window_grab_keys(), meta_window_lookup_saved_state(), META_WINDOW_NORMAL, meta_window_queue(), meta_window_release_saved_state(), meta_window_reload_properties(), meta_window_set_current_workspace_hint(), meta_window_set_user_time(), meta_window_update_icon_now(), meta_window_update_net_wm_type(), meta_window_update_role(), meta_window_update_struts(), meta_workspace_add_window(), N_INITIAL_PROPS, _MetaWindow::net_wm_user_time, NULL, _MetaWindow::on_all_workspaces, _MetaWorkspace::screen, _MetaDisplay::screens, TRUE, _MetaWindow::workspace, _MetaDisplay::xdisplay, and _MetaScreen::xroot.
Referenced by meta_screen_manage_all_windows(), and meta_window_new().
meta_window_notify_focus()
gboolean meta_window_notify_focus (MetaWindow * window, XEvent * event)
Definition at line 5640 of file window.c.
References FALSE, meta_compositor_set_active_window(), META_DEBUG_FOCUS, meta_display_grab_focus_window_button(), meta_display_ungrab_focus_window_button(), meta_display_update_active_window_hint(), meta_error_trap_pop(), meta_error_trap_push(), meta_event_detail_to_string(), meta_event_mode_to_string(), META_FOCUS_MODE_CLICK, meta_prefs_get_focus_mode(), meta_prefs_get_raise_on_click(), meta_window_located_on_workspace(), meta_window_update_layer(), NULL, and TRUE.
meta_window_property_notify()
gboolean meta_window_property_notify (MetaWindow * window, XEvent * event)
Definition at line 5104 of file window.c.
meta_window_queue()
void meta_window_queue (MetaWindow * window, guint queuebits)
Definition at line 1766 of file window.c.
References META_DEBUG_WINDOW_STATE, META_PRIORITY_RESIZE, NULL, and NUMBER_OF_QUEUES.
Referenced by meta_core_queue_frame_resize(), meta_display_queue_retheme_all_windows(), meta_window_client_message(), meta_window_destroy_frame(), meta_window_make_fullscreen(), meta_window_maximize(), meta_window_minimize(), meta_window_new_with_attrs(), meta_window_shade(), meta_window_tile(), meta_window_unminimize(), meta_window_unshade(), meta_window_update_fullscreen_monitors(), meta_workspace_add_window(), meta_workspace_invalidate_work_area(), meta_workspace_queue_calc_showing(), and meta_workspace_remove_window().
meta_window_raise()
void meta_window_raise (MetaWindow * window)
Definition at line 4741 of file window.c.
References _MetaWindow::desc, META_DEBUG_WINDOW_OPS, meta_stack_raise(), meta_warning(), meta_window_find_root_ancestor(), _MetaWindow::screen, and _MetaScreen::stack.
Referenced by meta_core_maximize(), meta_core_show_window_menu(), meta_core_toggle_maximize(), meta_core_toggle_maximize_horizontally(), meta_core_toggle_maximize_vertically(), meta_core_unmaximize(), meta_core_user_raise(), meta_display_begin_grab_op(), meta_display_end_grab_op(), meta_window_client_message(), meta_window_configure_request(), meta_window_make_above(), meta_window_make_fullscreen_internal(), meta_window_unmake_above(), and meta_workspace_activate_with_focus().
meta_window_recalc_features()
void meta_window_recalc_features (MetaWindow * window)
Definition at line 6702 of file window.c.
meta_window_recalc_window_type()
void meta_window_recalc_window_type (MetaWindow * window)
Definition at line 6544 of file window.c.
Referenced by meta_window_update_net_wm_type().
meta_window_refresh_resize_popup()
void meta_window_refresh_resize_popup (MetaWindow * window)
Definition at line 8351 of file window.c.
References META_DEBUG_WINDOW_OPS, META_GRAB_OP_KEYBOARD_RESIZING_E, META_GRAB_OP_KEYBOARD_RESIZING_N, META_GRAB_OP_KEYBOARD_RESIZING_NE, META_GRAB_OP_KEYBOARD_RESIZING_NW, META_GRAB_OP_KEYBOARD_RESIZING_S, META_GRAB_OP_KEYBOARD_RESIZING_SE, META_GRAB_OP_KEYBOARD_RESIZING_SW, META_GRAB_OP_KEYBOARD_RESIZING_UNKNOWN, META_GRAB_OP_KEYBOARD_RESIZING_W, META_GRAB_OP_NONE, META_GRAB_OP_RESIZING_E, META_GRAB_OP_RESIZING_N, META_GRAB_OP_RESIZING_NE, META_GRAB_OP_RESIZING_NW, META_GRAB_OP_RESIZING_S, META_GRAB_OP_RESIZING_SE, META_GRAB_OP_RESIZING_SW, META_GRAB_OP_RESIZING_W, meta_ui_resize_popup_new(), meta_ui_resize_popup_set(), meta_ui_resize_popup_set_showing(), meta_window_get_client_root_coords(), NULL, and TRUE.
Referenced by meta_display_begin_grab_op().
meta_window_resize()
void meta_window_resize (MetaWindow * window, gboolean user_op, int w, int h)
Definition at line 3913 of file window.c.
References META_IS_RESIZE_ACTION, META_IS_USER_ACTION, and meta_window_get_position().
meta_window_resize_with_gravity()
void meta_window_resize_with_gravity (MetaWindow * window, gboolean user_op, int w, int h, int gravity)
Definition at line 3965 of file window.c.
References META_IS_RESIZE_ACTION, META_IS_USER_ACTION, and meta_window_get_position().
Referenced by meta_core_user_resize(), and meta_display_end_grab_op().
meta_window_same_application()
gboolean meta_window_same_application (MetaWindow * window, MetaWindow * other_window)
Definition at line 8321 of file window.c.
References meta_window_get_group(), and NULL.
Referenced by meta_window_configure_request().
meta_window_send_icccm_message()
void meta_window_send_icccm_message (MetaWindow * window, Atom atom, guint32 timestamp)
Definition at line 4790 of file window.c.
References FALSE, meta_error_trap_pop(), and meta_error_trap_push().
Referenced by meta_display_ping_window(), meta_window_delete(), and meta_window_focus().
meta_window_set_current_workspace_hint()
void meta_window_set_current_workspace_hint (MetaWindow * window)
Definition at line 4690 of file window.c.
References data, FALSE, meta_error_trap_pop(), meta_error_trap_push(), meta_window_get_net_wm_desktop(), and NULL.
Referenced by meta_window_new_with_attrs(), meta_workspace_add_window(), and meta_workspace_remove_window().
meta_window_set_demands_attention()
void meta_window_set_demands_attention (MetaWindow * window)
Definition at line 8839 of file window.c.
References _MetaScreen::active_workspace, FALSE, META_DEBUG_WINDOW_OPS, meta_rectangle_overlap(), meta_window_get_outer_rect(), NULL, _MetaWindow::on_all_workspaces, _MetaWorkspace::screen, TRUE, and _MetaWindow::workspace.
Referenced by meta_window_client_message(), and meta_window_configure_request().
meta_window_set_gravity()
void meta_window_set_gravity (MetaWindow * window, int gravity)
Definition at line 8141 of file window.c.
References FALSE, meta_error_trap_pop(), and meta_error_trap_push().
meta_window_set_user_time()
void meta_window_set_user_time (MetaWindow * window, guint32 timestamp)
Definition at line 8798 of file window.c.
References __window_is_terminal(), FALSE, META_DEBUG_STARTUP, META_FOCUS_NEW_WINDOWS_STRICT, meta_prefs_get_focus_new_windows(), TRUE, and XSERVER_TIME_IS_BEFORE.
Referenced by meta_window_new_with_attrs().
meta_window_shade()
void meta_window_shade (MetaWindow * window, guint32 timestamp)
Definition at line 3084 of file window.c.
References META_DEBUG_FOCUS, META_DEBUG_WINDOW_OPS, META_QUEUE_CALC_SHOWING, META_QUEUE_MOVE_RESIZE, meta_window_focus(), meta_window_frame_size_changed(), meta_window_queue(), and TRUE.
Referenced by meta_core_shade(), and meta_window_client_message().
meta_window_should_be_showing()
gboolean meta_window_should_be_showing (MetaWindow * window)
Definition at line 1439 of file window.c.
References meta_window_located_on_workspace(), meta_window_showing_on_its_workspace(), and meta_workspace_index().
Referenced by meta_window_calc_showing().
meta_window_shove_titlebar_onscreen()
void meta_window_shove_titlebar_onscreen (MetaWindow * window)
Definition at line 7194 of file window.c.
References FALSE, FIXED_DIRECTION_X, _MetaRectangle::height, meta_rectangle_expand_region(), meta_rectangle_shove_into_region(), meta_window_get_outer_rect(), meta_window_move_resize(), _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
meta_window_show_menu()
void meta_window_show_menu (MetaWindow * window, int root_x, int root_y, int button, guint32 timestamp)
Definition at line 7065 of file window.c.
References META_MENU_OP_ABOVE, META_MENU_OP_DELETE, META_MENU_OP_MAXIMIZE, META_MENU_OP_MINIMIZE, META_MENU_OP_MOVE, META_MENU_OP_MOVE_DOWN, META_MENU_OP_MOVE_LEFT, META_MENU_OP_MOVE_RIGHT, META_MENU_OP_MOVE_UP, META_MENU_OP_NONE, META_MENU_OP_RECOVER, META_MENU_OP_RESIZE, META_MENU_OP_SHADE, META_MENU_OP_STICK, META_MENU_OP_UNABOVE, META_MENU_OP_UNMAXIMIZE, META_MENU_OP_UNSHADE, META_MENU_OP_UNSTICK, META_MENU_OP_WORKSPACES, meta_screen_calc_workspace_layout(), meta_screen_free_workspace_layout(), meta_screen_get_n_workspaces(), META_UI_DIRECTION_LTR, meta_ui_get_direction(), meta_ui_window_menu_free(), meta_ui_window_menu_new(), meta_ui_window_menu_popup(), META_WINDOW_ALLOWS_MOVE, META_WINDOW_ALLOWS_RESIZE, META_WINDOW_DESKTOP, META_WINDOW_DOCK, meta_window_get_net_wm_desktop(), META_WINDOW_MAXIMIZED, META_WINDOW_SPLASHSCREEN, meta_window_titlebar_is_onscreen(), meta_workspace_index(), and NULL.
Referenced by meta_core_show_window_menu(), and meta_window_client_message().
meta_window_showing_on_its_workspace()
gboolean meta_window_showing_on_its_workspace (MetaWindow * window)
Definition at line 1380 of file window.c.
References _MetaScreen::active_workspace, FALSE, meta_window_foreach_ancestor(), NULL, _MetaWorkspace::screen, _MetaWorkspace::showing_desktop, and TRUE.
Referenced by meta_screen_ensure_tab_popup(), meta_window_place(), and meta_window_should_be_showing().
meta_window_stack_just_below()
void meta_window_stack_just_below (MetaWindow * window, MetaWindow * below_this_one)
Definition at line 8774 of file window.c.
References _MetaWindow::desc, META_DEBUG_STACK, meta_window_set_stack_position(), NULL, and _MetaWindow::stack_position.
meta_window_stick()
void meta_window_stick (MetaWindow * window)
Definition at line 4628 of file window.c.
References meta_window_foreach_transient(), and TRUE.
Referenced by meta_core_stick(), and meta_window_client_message().
meta_window_tile()
void meta_window_tile (MetaWindow * window)
Definition at line 2700 of file window.c.
References FALSE, META_MAXIMIZE_VERTICAL, META_QUEUE_MOVE_RESIZE, META_TILE_BOTTOM_LEFT, META_TILE_BOTTOM_RIGHT, META_TILE_LEFT, META_TILE_NONE, META_TILE_RIGHT, META_TILE_TOP_LEFT, META_TILE_TOP_RIGHT, meta_window_maximize_internal(), meta_window_queue(), NULL, and TRUE.
Referenced by meta_window_handle_mouse_grab_op_event(), and meta_window_move_to_monitor().
meta_window_titlebar_is_onscreen()
gboolean meta_window_titlebar_is_onscreen (MetaWindow * window)
Definition at line 7240 of file window.c.
References FALSE, _MetaRectangle::height, meta_rectangle_intersect(), meta_window_get_outer_rect(), MIN, TRUE, and _MetaRectangle::width.
Referenced by meta_core_get(), and meta_window_show_menu().
meta_window_unmake_above()
void meta_window_unmake_above (MetaWindow * window)
Definition at line 2955 of file window.c.
References FALSE, meta_window_frame_size_changed(), meta_window_raise(), and meta_window_update_layer().
Referenced by meta_core_unmake_above().
meta_window_unmake_fullscreen()
void meta_window_unmake_fullscreen (MetaWindow * window)
Definition at line 3014 of file window.c.
References FALSE, _MetaRectangle::height, META_DEBUG_WINDOW_OPS, meta_window_get_current_tile_area(), meta_window_move_resize(), META_WINDOW_TILED, meta_window_update_layer(), _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_window_client_message().
meta_window_unmaximize()
void meta_window_unmaximize (MetaWindow * window, MetaMaximizeFlags directions)
Definition at line 2788 of file window.c.
References FALSE, _MetaRectangle::height, meta_compositor_unmaximize_window(), META_DEBUG_WINDOW_OPS, meta_grab_op_is_moving(), META_MAXIMIZE_HORIZONTAL, META_MAXIMIZE_VERTICAL, META_TILE_NONE, meta_window_frame_size_changed(), meta_window_get_client_root_coords(), meta_window_move_resize(), _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_core_toggle_maximize(), meta_core_toggle_maximize_horizontally(), meta_core_toggle_maximize_vertically(), meta_core_unmaximize(), meta_window_client_message(), and meta_window_untile().
meta_window_unminimize()
void meta_window_unminimize (MetaWindow * window)
Definition at line 2449 of file window.c.
References FALSE, META_QUEUE_CALC_SHOWING, meta_window_foreach_transient(), meta_window_queue(), NULL, and TRUE.
meta_window_unset_demands_attention()
void meta_window_unset_demands_attention (MetaWindow * window)
Definition at line 8903 of file window.c.
References FALSE, and META_DEBUG_WINDOW_OPS.
Referenced by meta_window_client_message(), and meta_window_focus().
meta_window_unshade()
void meta_window_unshade (MetaWindow * window, guint32 timestamp)
Definition at line 3111 of file window.c.
References FALSE, META_DEBUG_FOCUS, META_DEBUG_WINDOW_OPS, META_QUEUE_CALC_SHOWING, META_QUEUE_MOVE_RESIZE, meta_window_focus(), meta_window_frame_size_changed(), and meta_window_queue().
Referenced by meta_core_unshade(), meta_window_client_message(), meta_window_make_fullscreen_internal(), and meta_window_maximize().
meta_window_unstick()
void meta_window_unstick (MetaWindow * window)
Definition at line 4638 of file window.c.
References FALSE, and meta_window_foreach_transient().
Referenced by meta_core_unstick(), and meta_window_client_message().
meta_window_untile()
void meta_window_untile (MetaWindow * window)
Definition at line 2745 of file window.c.
References FALSE, META_MAXIMIZE_HORIZONTAL, META_MAXIMIZE_VERTICAL, and meta_window_unmaximize().
meta_window_update_fullscreen_monitors()
void meta_window_update_fullscreen_monitors (MetaWindow * window, unsigned long top, unsigned long bottom, unsigned long left, unsigned long right)
Definition at line 3056 of file window.c.
References META_QUEUE_MOVE_RESIZE, and meta_window_queue().
Referenced by meta_window_client_message().
meta_window_update_icon_now()
void meta_window_update_icon_now (MetaWindow * window)
Definition at line 6169 of file window.c.
References META_MINI_ICON_HEIGHT, META_MINI_ICON_WIDTH, meta_prefs_get_icon_size(), meta_read_icons(), and NULL.
Referenced by meta_invalidate_all_icons(), meta_invalidate_default_icons(), and meta_window_new_with_attrs().
meta_window_update_keyboard_move()
void meta_window_update_keyboard_move (MetaWindow * window)
Definition at line 8707 of file window.c.
meta_window_update_keyboard_resize()
void meta_window_update_keyboard_resize (MetaWindow * window, gboolean update_cursor)
Definition at line 8683 of file window.c.
References meta_display_set_grab_op_cursor(), NULL, and TRUE.
meta_window_update_layer()
void meta_window_update_layer (MetaWindow * window)
Definition at line 8717 of file window.c.
References meta_group_update_layers(), meta_stack_freeze(), meta_stack_thaw(), meta_stack_update_layer(), and meta_window_get_group().
Referenced by meta_window_client_message(), meta_window_make_above(), meta_window_make_fullscreen_internal(), meta_window_notify_focus(), meta_window_unmake_above(), and meta_window_unmake_fullscreen().
meta_window_update_net_wm_type()
void meta_window_update_net_wm_type (MetaWindow * window)
Definition at line 6071 of file window.c.
References meta_error_trap_pop(), meta_error_trap_push(), meta_is_verbose(), meta_prop_get_atom_list(), meta_window_recalc_window_type(), meta_XFree, NULL, and TRUE.
Referenced by meta_window_new_with_attrs().
meta_window_update_role()
void meta_window_update_role (MetaWindow * window)
Definition at line 6050 of file window.c.
References meta_prop_get_latin1_string(), meta_XFree, and NULL.
Referenced by meta_window_new_with_attrs().
meta_window_update_struts()
void meta_window_update_struts (MetaWindow * window)
Definition at line 6284 of file window.c.
References BOX_BOTTOM, BOX_RIGHT, _MetaStrut::edge, FALSE, _MetaRectangle::height, META_DEBUG_WORKAREA, META_EDGE_SCREEN, META_EDGE_XINERAMA, meta_prop_get_cardinal_list(), meta_rectangle_contains_rect(), meta_rectangle_equal(), META_SIDE_BOTTOM, META_SIDE_LEFT, META_SIDE_RIGHT, META_SIDE_TOP, meta_XFree, NULL, _MetaStrut::rect, _MetaStrut::side, TRUE, _MetaRectangle::width, _MetaRectangle::x, and _MetaRectangle::y.
Referenced by meta_window_new_with_attrs().
meta_window_update_wireframe()
void meta_window_update_wireframe (MetaWindow * window, int x, int y, int width, int height)
Definition at line 4305 of file window.c.
References meta_effects_update_wireframe(), and meta_window_get_xor_rect().