MATE Desktop Environment: window-menu.c File Reference
window-menu.c File Reference
#include <string.h>
#include <mate-panel-applet.h>
#include <glib/gi18n.h>
#include <gdk/gdkkeysyms.h>
#include "wncklet.h"
#include "window-menu.h"
Macros
#define GDK_IS_X11_DISPLAY(object)
#define WINDOW_MENU_ICON "mate-panel-window-menu"
Functions
gboolean window_menu_applet_fill (MatePanelApplet *applet)
Macro Definition Documentation
GDK_IS_X11_DISPLAY
#define GDK_IS_X11_DISPLAY (object)
Value:
!(G_TYPE_CHECK_INSTANCE_TYPE ((object), GDK_TYPE_WAYLAND_DISPLAY))
Definition at line 49 of file window-menu.c.
WINDOW_MENU_ICON
#define WINDOW_MENU_ICON "mate-panel-window-menu"
Definition at line 55 of file window-menu.c.
Function Documentation
window_menu_applet_fill()
gboolean window_menu_applet_fill (MatePanelApplet * applet)
Definition at line 236 of file window-menu.c.
References _, GDK_IS_X11_DISPLAY, GETTEXT_PACKAGE, MATE_PANEL_APPLET_EXPAND_MINOR, mate_panel_applet_get_orient(), mate_panel_applet_get_size(), mate_panel_applet_set_flags(), mate_panel_applet_setup_menu_from_resource(), TRUE, and WNCKLET_RESOURCE_PATH.