MATE Desktop Environment: window-props.c File Reference
window-props.c File Reference
#include <config.h>
#include <glib/gi18n-lib.h>
#include "window-props.h"
#include "errors.h"
#include "xprops.h"
#include "frame-private.h"
#include "group.h"
#include <X11/Xatom.h>
#include <X11/extensions/XRes.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <sys/types.h>
#include <pwd.h>
Macros
#define _GNU_SOURCE
#define _XOPEN_SOURCE /* for gethostname() */
#define HOST_NAME_MAX 255
#define MAX_TITLE_LENGTH 512
#define FLAG_TOGGLED_ON(old, new, flag)
#define FLAG_TOGGLED_OFF(old, new, flag)
#define FLAG_CHANGED(old, new, flag)
Typedefs
typedef void(* ReloadValueFunc) (MetaWindow *window, MetaPropValue *value, gboolean initial)
typedef struct MetaWindowPropHooks MetaWindowPropHooks
Functions
void meta_window_reload_property (MetaWindow *window, Atom property, gboolean initial)
void meta_window_reload_properties (MetaWindow *window, const Atom *properties, int n_properties, gboolean initial)
void meta_window_reload_property_from_xwindow (MetaWindow *window, Window xwindow, Atom property, gboolean initial)
void meta_window_reload_properties_from_xwindow (MetaWindow *window, Window xwindow, const Atom *properties, int n_properties, gboolean initial)
void meta_set_normal_hints (MetaWindow *window, XSizeHints *hints)
void meta_display_init_window_prop_hooks (MetaDisplay *display)
void meta_display_free_window_prop_hooks (MetaDisplay *display)
Detailed Description
MetaWindow property handling
A system which can inspect sets of properties of given windows and take appropriate action given their values.
Note that all the meta_window_reload_propert* functions require a round trip to the server.
The guts of this system are in meta_display_init_window_prop_hooks(). Reading this function will give you insight into how this all fits together.
Definition in file window-props.c.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 38 of file window-props.c.
_XOPEN_SOURCE
#define _XOPEN_SOURCE /* for gethostname() */
Definition at line 39 of file window-props.c.
FLAG_CHANGED
#define FLAG_CHANGED (old, new, flag)
Value:
(FLAG_TOGGLED_ON(old,new,flag) || FLAG_TOGGLED_OFF(old,new,flag))
Definition at line 1023 of file window-props.c.
FLAG_TOGGLED_OFF
#define FLAG_TOGGLED_OFF (old, new, flag)
Value:
(((old)->flags & (flag)) != 0 &&      \
 ((new)->flags & (flag)) == 0)
Definition at line 1019 of file window-props.c.
FLAG_TOGGLED_ON
#define FLAG_TOGGLED_ON (old, new, flag)
Value:
(((old)->flags & (flag)) == 0 &&     \
 ((new)->flags & (flag)) != 0)
Definition at line 1015 of file window-props.c.
HOST_NAME_MAX
#define HOST_NAME_MAX 255
Definition at line 65 of file window-props.c.
MAX_TITLE_LENGTH
#define MAX_TITLE_LENGTH 512
Definition at line 467 of file window-props.c.
Typedef Documentation
MetaWindowPropHooks
typedef struct MetaWindowPropHooks MetaWindowPropHooks
ReloadValueFunc
typedef void(* ReloadValueFunc) (MetaWindow *window, MetaPropValue *value, gboolean initial)
Definition at line 68 of file window-props.c.
Function Documentation
meta_display_free_window_prop_hooks()
void meta_display_free_window_prop_hooks (MetaDisplay * display)
Frees the hooks used for the reload_propert* functions for a particular display.
Parameters
display The display.
Definition at line 1734 of file window-props.c.
References NULL, _MetaDisplay::prop_hooks, and _MetaDisplay::prop_hooks_table.
Referenced by meta_display_close().
meta_display_init_window_prop_hooks()
void meta_display_init_window_prop_hooks (MetaDisplay * display)
Initialises the property hooks system. Each row in the table named "hooks" represents an action to take when a property is found on a newly-created window, or when a property changes its value.
The first column shows which atom the row concerns. The second gives the type of the property data. The property will be queried for its new value, unless the type is given as META_PROP_VALUE_INVALID, in which case nothing will be queried. The third column gives the name of a callback which gets called with the new value. (If the new value was not retrieved because the second column was META_PROP_VALUE_INVALID, the callback still gets called anyway.) This value may be NULL, in which case no callback will be called.
Definition at line 1667 of file window-props.c.
References META_PROP_VALUE_ATOM_LIST, META_PROP_VALUE_CARDINAL, META_PROP_VALUE_CARDINAL_LIST, META_PROP_VALUE_CLASS_HINT, META_PROP_VALUE_INVALID, META_PROP_VALUE_MOTIF_HINTS, META_PROP_VALUE_SIZE_HINTS, META_PROP_VALUE_STRING, META_PROP_VALUE_SYNC_COUNTER, META_PROP_VALUE_TEXT_PROPERTY, META_PROP_VALUE_UTF8, META_PROP_VALUE_WINDOW, META_PROP_VALUE_WM_HINTS, NULL, _MetaDisplay::prop_hooks, and _MetaDisplay::prop_hooks_table.
meta_set_normal_hints()
void meta_set_normal_hints (MetaWindow * window, XSizeHints * hints)
Sets the size hints for a window. This happens when a WM_NORMAL_HINTS property is set on a window, but it is public because the size hints are set to defaults when a window is created. See http://tronche.com/gui/x/icccm/sec-4.html#WM_NORMAL_HINTS for the X details.
Parameters
window The window to set the size hints on.
hints Either some X size hints, or NULL for default.
Definition at line 1076 of file window-props.c.
References META_DEBUG_GEOMETRY.
Referenced by meta_window_new_with_attrs().
meta_window_reload_properties()
void meta_window_reload_properties (MetaWindow * window, const Atom * properties, int n_properties, gboolean initial)
Requests the current values of a set of properties for a given window from the server, and deals with them appropriately. Does not return them to the caller (they've been dealt with!)
Parameters
window The window.
properties A pointer to a list of X atoms, "n_properties" long.
n_properties The length of the properties list.
Definition at line 91 of file window-props.c.
References meta_window_reload_properties_from_xwindow().
Referenced by meta_window_new_with_attrs(), and meta_window_reload_property().
meta_window_reload_properties_from_xwindow()
void meta_window_reload_properties_from_xwindow (MetaWindow * window, Window xwindow, const Atom * properties, int n_properties, gboolean initial)
Requests the current values of a set of properties for a given window from the server, and deals with them appropriately. Does not return them to the caller (they've been dealt with!)
Parameters
window A window on the same display as the one we're investigating (only used to find the display)
xwindow The X handle for the window.
properties A pointer to a list of X atoms, "n_properties" long.
n_properties The length of the properties list.
Definition at line 114 of file window-props.c.
References MetaPropValue::atom, meta_prop_free_values(), meta_prop_get_values(), META_PROP_VALUE_INVALID, NULL, and MetaPropValue::type.
Referenced by meta_window_reload_properties(), and meta_window_reload_property_from_xwindow().
meta_window_reload_property()
void meta_window_reload_property (MetaWindow * window, Atom property, gboolean initial)
Requests the current values of a single property for a given window from the server, and deals with it appropriately. Does not return it to the caller (it's been dealt with!)
Parameters
window The window.
property A single X atom.
Definition at line 83 of file window-props.c.
References meta_window_reload_properties().
meta_window_reload_property_from_xwindow()
void meta_window_reload_property_from_xwindow (MetaWindow * window, Window xwindow, Atom property, gboolean initial)
Requests the current values of a single property for a given window from the server, and deals with it appropriately. Does not return it to the caller (it's been dealt with!)
Parameters
window A window on the same display as the one we're investigating (only used to find the display)
xwindow The X handle for the window.
property A single X atom.
Definition at line 104 of file window-props.c.
References meta_window_reload_properties_from_xwindow().