MATE Desktop Environment: workspace-switcher.c File Reference
workspace-switcher.c File Reference
#include <string.h>
#include <mate-panel-applet.h>
#include <mate-panel-applet-gsettings.h>
#include <stdlib.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <libmate-desktop/mate-gsettings.h>
#include "workspace-switcher.h"
#include "wncklet.h"
Macros
#define MAX_REASONABLE_ROWS 16
#define DEFAULT_ROWS 1
#define WORKSPACE_SWITCHER_SCHEMA "org.mate.panel.applet.workspace-switcher"
#define NEVER_SENSITIVE "never_sensitive"
#define MARCO_GENERAL_SCHEMA "org.mate.Marco.general"
#define NUM_WORKSPACES "num-workspaces"
#define MARCO_WORKSPACES_SCHEMA "org.mate.Marco.workspace-names"
#define WORKSPACE_NAME "name-1"
#define WORKSPACE_SWITCHER_ICON "mate-panel-workspace-switcher"
#define PAGER_CONTAINER_TYPE (pager_container_get_type ())
#define PAGER_CONTAINER(obj)
#define WID(s)
Typedefs
typedef struct _PagerContainer PagerContainer
typedef GtkBinClass PagerContainerClass
Enumerations
enum PagerWM {
PAGER_WM_MARCO , PAGER_WM_METACITY , PAGER_WM_COMPIZ , PAGER_WM_I3 ,
PAGER_WM_XMONAD , PAGER_WM_UNKNOWN
}
Functions
gboolean workspace_switcher_applet_fill (MatePanelApplet *applet)
Macro Definition Documentation
DEFAULT_ROWS
#define DEFAULT_ROWS 1
Definition at line 44 of file workspace-switcher.c.
MARCO_GENERAL_SCHEMA
#define MARCO_GENERAL_SCHEMA "org.mate.Marco.general"
Definition at line 49 of file workspace-switcher.c.
MARCO_WORKSPACES_SCHEMA
#define MARCO_WORKSPACES_SCHEMA "org.mate.Marco.workspace-names"
Definition at line 51 of file workspace-switcher.c.
MAX_REASONABLE_ROWS
#define MAX_REASONABLE_ROWS 16
Definition at line 43 of file workspace-switcher.c.
Referenced by workspace_switcher_applet_fill().
NEVER_SENSITIVE
#define NEVER_SENSITIVE "never_sensitive"
Definition at line 48 of file workspace-switcher.c.
NUM_WORKSPACES
#define NUM_WORKSPACES "num-workspaces"
Definition at line 50 of file workspace-switcher.c.
PAGER_CONTAINER
#define PAGER_CONTAINER (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), PAGER_CONTAINER_TYPE, PagerContainer))
Definition at line 66 of file workspace-switcher.c.
PAGER_CONTAINER_TYPE
#define PAGER_CONTAINER_TYPE (pager_container_get_type ())
Definition at line 65 of file workspace-switcher.c.
WID
#define WID (s)
Value:
GTK_WIDGET(gtk_builder_get_object(builder, s))
Definition at line 1094 of file workspace-switcher.c.
WORKSPACE_NAME
#define WORKSPACE_NAME "name-1"
Definition at line 52 of file workspace-switcher.c.
WORKSPACE_SWITCHER_ICON
#define WORKSPACE_SWITCHER_ICON "mate-panel-workspace-switcher"
Definition at line 54 of file workspace-switcher.c.
WORKSPACE_SWITCHER_SCHEMA
#define WORKSPACE_SWITCHER_SCHEMA "org.mate.panel.applet.workspace-switcher"
Definition at line 46 of file workspace-switcher.c.
Typedef Documentation
PagerContainer
typedef struct _PagerContainer PagerContainer
Definition at line 60 of file workspace-switcher.c.
PagerContainerClass
typedef GtkBinClass PagerContainerClass
Definition at line 61 of file workspace-switcher.c.
Enumeration Type Documentation
PagerWM
enum PagerWM
Enumerator
PAGER_WM_MARCO
PAGER_WM_METACITY
PAGER_WM_COMPIZ
PAGER_WM_I3
PAGER_WM_XMONAD
PAGER_WM_UNKNOWN
Definition at line 203 of file workspace-switcher.c.
Function Documentation
workspace_switcher_applet_fill()
gboolean workspace_switcher_applet_fill (MatePanelApplet * applet)
Definition at line 739 of file workspace-switcher.c.
References action, FALSE, GDK_IS_X11_DISPLAY, GETTEXT_PACKAGE, MATE_PANEL_APPLET_EXPAND_MINOR, mate_panel_applet_get_locked_down(), mate_panel_applet_get_orient(), mate_panel_applet_set_flags(), mate_panel_applet_setup_menu_from_resource(), MAX_REASONABLE_ROWS, PAGER_WM_UNKNOWN, TRUE, and WNCKLET_RESOURCE_PATH.