MATE Desktop Environment: xprops.h File Reference
xprops.h File Reference
#include <config.h>
#include "display.h"
#include <X11/Xutil.h>
Classes
struct MotifWmHints
struct MetaPropValue
Macros
#define MWM_HINTS_FUNCTIONS (1L << 0)
#define MWM_HINTS_DECORATIONS (1L << 1)
#define MWM_HINTS_INPUT_MODE (1L << 2)
#define MWM_HINTS_STATUS (1L << 3)
#define MWM_FUNC_ALL (1L << 0)
#define MWM_FUNC_RESIZE (1L << 1)
#define MWM_FUNC_MOVE (1L << 2)
#define MWM_FUNC_MINIMIZE (1L << 3)
#define MWM_FUNC_MAXIMIZE (1L << 4)
#define MWM_FUNC_CLOSE (1L << 5)
#define MWM_DECOR_ALL (1L << 0)
#define MWM_DECOR_BORDER (1L << 1)
#define MWM_DECOR_RESIZEH (1L << 2)
#define MWM_DECOR_TITLE (1L << 3)
#define MWM_DECOR_MENU (1L << 4)
#define MWM_DECOR_MINIMIZE (1L << 5)
#define MWM_DECOR_MAXIMIZE (1L << 6)
#define MWM_INPUT_MODELESS 0
#define MWM_INPUT_PRIMARY_APPLICATION_MODAL 1
#define MWM_INPUT_SYSTEM_MODAL 2
#define MWM_INPUT_FULL_APPLICATION_MODAL 3
#define MWM_INPUT_APPLICATION_MODAL MWM_INPUT_PRIMARY_APPLICATION_MODAL
#define MWM_TEAROFF_WINDOW (1L<<0)
Typedefs
typedef struct MotifWmHints MwmHints
Enumerations
enum MetaPropValueType {
META_PROP_VALUE_INVALID , META_PROP_VALUE_UTF8 , META_PROP_VALUE_STRING , META_PROP_VALUE_STRING_AS_UTF8 ,
META_PROP_VALUE_MOTIF_HINTS , META_PROP_VALUE_CARDINAL , META_PROP_VALUE_WINDOW , META_PROP_VALUE_CARDINAL_LIST ,
META_PROP_VALUE_UTF8_LIST , META_PROP_VALUE_ATOM_LIST , META_PROP_VALUE_TEXT_PROPERTY , META_PROP_VALUE_WM_HINTS ,
META_PROP_VALUE_CLASS_HINT , META_PROP_VALUE_SIZE_HINTS , META_PROP_VALUE_SYNC_COUNTER
}
Functions
gboolean meta_prop_get_atom_list (MetaDisplay *display, Window xwindow, Atom xatom, Atom **atoms_p, int *n_atoms_p)
gboolean meta_prop_get_motif_hints (MetaDisplay *display, Window xwindow, Atom xatom, MotifWmHints **hints_p)
gboolean meta_prop_get_cardinal_list (MetaDisplay *display, Window xwindow, Atom xatom, gulong **cardinals_p, int *n_cardinals_p)
gboolean meta_prop_get_latin1_string (MetaDisplay *display, Window xwindow, Atom xatom, char **str_p)
gboolean meta_prop_get_utf8_string (MetaDisplay *display, Window xwindow, Atom xatom, char **str_p)
gboolean meta_prop_get_utf8_list (MetaDisplay *display, Window xwindow, Atom xatom, char ***str_p, int *n_str_p)
void meta_prop_set_utf8_string_hint (MetaDisplay *display, Window xwindow, Atom atom, const char *val)
gboolean meta_prop_get_window (MetaDisplay *display, Window xwindow, Atom xatom, Window *window_p)
gboolean meta_prop_get_cardinal (MetaDisplay *display, Window xwindow, Atom xatom, gulong *cardinal_p)
gboolean meta_prop_get_cardinal_with_atom_type (MetaDisplay *display, Window xwindow, Atom xatom, Atom prop_type, gulong *cardinal_p)
gboolean meta_prop_get_text_property (MetaDisplay *display, Window xwindow, Atom xatom, char **utf8_str_p)
gboolean meta_prop_get_wm_hints (MetaDisplay *display, Window xwindow, Atom xatom, XWMHints **hints_p)
gboolean meta_prop_get_class_hint (MetaDisplay *display, Window xwindow, Atom xatom, XClassHint *class_hint)
gboolean meta_prop_get_size_hints (MetaDisplay *display, Window xwindow, Atom xatom, XSizeHints **hints_p, gulong *flags_p)
void meta_prop_get_values (MetaDisplay *display, Window xwindow, MetaPropValue *values, int n_values)
void meta_prop_free_values (MetaPropValue *values, int n_values)
Macro Definition Documentation
MWM_DECOR_ALL
#define MWM_DECOR_ALL (1L << 0)
Definition at line 59 of file xprops.h.
MWM_DECOR_BORDER
#define MWM_DECOR_BORDER (1L << 1)
Definition at line 60 of file xprops.h.
MWM_DECOR_MAXIMIZE
#define MWM_DECOR_MAXIMIZE (1L << 6)
Definition at line 65 of file xprops.h.
MWM_DECOR_MENU
#define MWM_DECOR_MENU (1L << 4)
Definition at line 63 of file xprops.h.
MWM_DECOR_MINIMIZE
#define MWM_DECOR_MINIMIZE (1L << 5)
Definition at line 64 of file xprops.h.
MWM_DECOR_RESIZEH
#define MWM_DECOR_RESIZEH (1L << 2)
Definition at line 61 of file xprops.h.
MWM_DECOR_TITLE
#define MWM_DECOR_TITLE (1L << 3)
Definition at line 62 of file xprops.h.
MWM_FUNC_ALL
#define MWM_FUNC_ALL (1L << 0)
Definition at line 52 of file xprops.h.
MWM_FUNC_CLOSE
#define MWM_FUNC_CLOSE (1L << 5)
Definition at line 57 of file xprops.h.
MWM_FUNC_MAXIMIZE
#define MWM_FUNC_MAXIMIZE (1L << 4)
Definition at line 56 of file xprops.h.
MWM_FUNC_MINIMIZE
#define MWM_FUNC_MINIMIZE (1L << 3)
Definition at line 55 of file xprops.h.
MWM_FUNC_MOVE
#define MWM_FUNC_MOVE (1L << 2)
Definition at line 54 of file xprops.h.
MWM_FUNC_RESIZE
#define MWM_FUNC_RESIZE (1L << 1)
Definition at line 53 of file xprops.h.
MWM_HINTS_DECORATIONS
#define MWM_HINTS_DECORATIONS (1L << 1)
Definition at line 48 of file xprops.h.
Referenced by main().
MWM_HINTS_FUNCTIONS
#define MWM_HINTS_FUNCTIONS (1L << 0)
Definition at line 47 of file xprops.h.
MWM_HINTS_INPUT_MODE
#define MWM_HINTS_INPUT_MODE (1L << 2)
Definition at line 49 of file xprops.h.
MWM_HINTS_STATUS
#define MWM_HINTS_STATUS (1L << 3)
Definition at line 50 of file xprops.h.
MWM_INPUT_APPLICATION_MODAL
#define MWM_INPUT_APPLICATION_MODAL MWM_INPUT_PRIMARY_APPLICATION_MODAL
Definition at line 71 of file xprops.h.
MWM_INPUT_FULL_APPLICATION_MODAL
#define MWM_INPUT_FULL_APPLICATION_MODAL 3
Definition at line 70 of file xprops.h.
MWM_INPUT_MODELESS
#define MWM_INPUT_MODELESS 0
Definition at line 67 of file xprops.h.
MWM_INPUT_PRIMARY_APPLICATION_MODAL
#define MWM_INPUT_PRIMARY_APPLICATION_MODAL 1
Definition at line 68 of file xprops.h.
MWM_INPUT_SYSTEM_MODAL
#define MWM_INPUT_SYSTEM_MODAL 2
Definition at line 69 of file xprops.h.
MWM_TEAROFF_WINDOW
#define MWM_TEAROFF_WINDOW (1L<<0)
Definition at line 73 of file xprops.h.
Typedef Documentation
MwmHints
typedef struct MotifWmHints MwmHints
Enumeration Type Documentation
MetaPropValueType
enum MetaPropValueType
Enumerator
META_PROP_VALUE_INVALID
META_PROP_VALUE_UTF8
META_PROP_VALUE_STRING
META_PROP_VALUE_STRING_AS_UTF8
META_PROP_VALUE_MOTIF_HINTS
META_PROP_VALUE_CARDINAL
META_PROP_VALUE_WINDOW
META_PROP_VALUE_CARDINAL_LIST
META_PROP_VALUE_UTF8_LIST
META_PROP_VALUE_ATOM_LIST
META_PROP_VALUE_TEXT_PROPERTY
META_PROP_VALUE_WM_HINTS
META_PROP_VALUE_CLASS_HINT
META_PROP_VALUE_SIZE_HINTS
META_PROP_VALUE_SYNC_COUNTER
Definition at line 144 of file xprops.h.
Function Documentation
meta_prop_free_values()
void meta_prop_free_values (MetaPropValue * values, int n_values)
Definition at line 1267 of file xprops.c.
Referenced by meta_group_reload_properties(), and meta_window_reload_properties_from_xwindow().
meta_prop_get_atom_list()
gboolean meta_prop_get_atom_list (MetaDisplay * display, Window xwindow, Atom xatom, Atom ** atoms_p, int * n_atoms_p)
Definition at line 238 of file xprops.c.
References FALSE, and NULL.
Referenced by meta_window_update_net_wm_type().
meta_prop_get_cardinal()
gboolean meta_prop_get_cardinal (MetaDisplay * display, Window xwindow, Atom xatom, gulong * cardinal_p)
Definition at line 604 of file xprops.c.
References meta_prop_get_cardinal_with_atom_type().
Referenced by meta_screen_new().
meta_prop_get_cardinal_list()
gboolean meta_prop_get_cardinal_list (MetaDisplay * display, Window xwindow, Atom xatom, gulong ** cardinals_p, int * n_cardinals_p)
Definition at line 282 of file xprops.c.
References FALSE, and NULL.
Referenced by meta_screen_update_workspace_layout(), meta_window_get_icon_geometry(), and meta_window_update_struts().
meta_prop_get_cardinal_with_atom_type()
gboolean meta_prop_get_cardinal_with_atom_type (MetaDisplay * display, Window xwindow, Atom xatom, Atom prop_type, gulong * cardinal_p)
Definition at line 633 of file xprops.c.
References FALSE.
Referenced by meta_prop_get_cardinal(), and meta_window_new_with_attrs().
meta_prop_get_class_hint()
gboolean meta_prop_get_class_hint (MetaDisplay * display, Window xwindow, Atom xatom, XClassHint * class_hint)
Definition at line 856 of file xprops.c.
References FALSE, and NULL.
meta_prop_get_latin1_string()
gboolean meta_prop_get_latin1_string (MetaDisplay * display, Window xwindow, Atom xatom, char ** str_p)
Definition at line 380 of file xprops.c.
References FALSE, and NULL.
Referenced by meta_window_update_role().
meta_prop_get_motif_hints()
gboolean meta_prop_get_motif_hints (MetaDisplay * display, Window xwindow, Atom xatom, MotifWmHints ** hints_p)
Definition at line 348 of file xprops.c.
References FALSE, and NULL.
meta_prop_get_size_hints()
gboolean meta_prop_get_size_hints (MetaDisplay * display, Window xwindow, Atom xatom, XSizeHints ** hints_p, gulong * flags_p)
Definition at line 931 of file xprops.c.
References FALSE, and NULL.
meta_prop_get_text_property()
gboolean meta_prop_get_text_property (MetaDisplay * display, Window xwindow, Atom xatom, char ** utf8_str_p)
Definition at line 702 of file xprops.c.
References FALSE.
meta_prop_get_utf8_list()
gboolean meta_prop_get_utf8_list (MetaDisplay * display, Window xwindow, Atom xatom, char *** str_p, int * n_str_p)
Definition at line 522 of file xprops.c.
References FALSE, and NULL.
Referenced by meta_screen_update_workspace_names().
meta_prop_get_utf8_string()
gboolean meta_prop_get_utf8_string (MetaDisplay * display, Window xwindow, Atom xatom, char ** str_p)
Definition at line 428 of file xprops.c.
References FALSE, and NULL.
meta_prop_get_values()
void meta_prop_get_values (MetaDisplay * display, Window xwindow, MetaPropValue * values, int n_values)
Definition at line 980 of file xprops.c.
References ag_get_next_completed_task(), ag_task_get_reply_and_free(), ag_task_have_reply(), ag_Xmalloc(), MetaPropValue::atom, MetaPropValue::atom_list, MetaPropValue::atoms, MetaPropValue::cardinal, MetaPropValue::cardinal_list, MetaPropValue::cardinals, MetaPropValue::class_hint, MetaPropValue::flags, MetaPropValue::hints, meta_bug(), META_DEBUG_SYNC, META_PROP_VALUE_ATOM_LIST, META_PROP_VALUE_CARDINAL, META_PROP_VALUE_CARDINAL_LIST, META_PROP_VALUE_CLASS_HINT, META_PROP_VALUE_INVALID, META_PROP_VALUE_MOTIF_HINTS, META_PROP_VALUE_SIZE_HINTS, META_PROP_VALUE_STRING, META_PROP_VALUE_STRING_AS_UTF8, META_PROP_VALUE_SYNC_COUNTER, META_PROP_VALUE_TEXT_PROPERTY, META_PROP_VALUE_UTF8, META_PROP_VALUE_UTF8_LIST, META_PROP_VALUE_WINDOW, META_PROP_VALUE_WM_HINTS, meta_XFree, MetaPropValue::motif_hints, MetaPropValue::n_atoms, MetaPropValue::n_cardinals, MetaPropValue::n_strings, NULL, MetaPropValue::required_type, MetaPropValue::size_hints, MetaPropValue::str, MetaPropValue::string_list, MetaPropValue::strings, MetaPropValue::type, MetaPropValue::v, MetaPropValue::wm_hints, _MetaDisplay::xdisplay, and MetaPropValue::xwindow.
Referenced by meta_group_reload_properties(), and meta_window_reload_properties_from_xwindow().
meta_prop_get_window()
gboolean meta_prop_get_window (MetaDisplay * display, Window xwindow, Atom xatom, Window * window_p)
Definition at line 587 of file xprops.c.
References FALSE.
meta_prop_get_wm_hints()
gboolean meta_prop_get_wm_hints (MetaDisplay * display, Window xwindow, Atom xatom, XWMHints ** hints_p)
Definition at line 795 of file xprops.c.
References FALSE, and NULL.
meta_prop_set_utf8_string_hint()
void meta_prop_set_utf8_string_hint (MetaDisplay * display, Window xwindow, Atom atom, const char * val)
Definition at line 541 of file xprops.c.
References FALSE, meta_error_trap_pop(), meta_error_trap_push(), and _MetaDisplay::xdisplay.