MATE Desktop Environment: xsettings-common.c File Reference
xsettings-common.c File Reference
#include "string.h"
#include "stdlib.h"
#include <X11/Xlib.h>
#include <X11/Xmd.h>
#include "xsettings-common.h"
Functions
XSettingsSetting * xsettings_setting_copy (XSettingsSetting *setting)
XSettingsList * xsettings_list_copy (XSettingsList *list)
int xsettings_setting_equal (XSettingsSetting *setting_a, XSettingsSetting *setting_b)
void xsettings_setting_free (XSettingsSetting *setting)
void xsettings_list_free (XSettingsList *list)
XSettingsResult xsettings_list_insert (XSettingsList **list, XSettingsSetting *setting)
XSettingsResult xsettings_list_delete (XSettingsList **list, const char *name)
XSettingsSetting * xsettings_list_lookup (XSettingsList *list, const char *name)
char xsettings_byte_order (void)
Function Documentation
xsettings_byte_order()
char xsettings_byte_order (void)
Definition at line 261 of file xsettings-common.c.
Referenced by xsettings_manager_notify().
xsettings_list_copy()
XSettingsList * xsettings_list_copy (XSettingsList * list)
Definition at line 82 of file xsettings-common.c.
References error, _XSettingsList::next, NULL, _XSettingsList::setting, xsettings_list_free(), and xsettings_setting_copy().
xsettings_list_delete()
XSettingsResult xsettings_list_delete (XSettingsList ** list, const char * name)
Definition at line 213 of file xsettings-common.c.
References _XSettingsSetting::name, name, _XSettingsList::next, NULL, _XSettingsList::setting, XSETTINGS_FAILED, xsettings_setting_free(), and XSETTINGS_SUCCESS.
Referenced by xsettings_manager_delete_setting(), and xsettings_manager_set_setting().
xsettings_list_free()
void xsettings_list_free (XSettingsList * list)
Definition at line 159 of file xsettings-common.c.
References _XSettingsList::next, _XSettingsList::setting, and xsettings_setting_free().
Referenced by xsettings_list_copy(), and xsettings_manager_destroy().
xsettings_list_insert()
XSettingsResult xsettings_list_insert (XSettingsList ** list, XSettingsSetting * setting)
Definition at line 173 of file xsettings-common.c.
References _XSettingsSetting::name, _XSettingsList::next, NULL, _XSettingsList::setting, XSETTINGS_DUPLICATE_ENTRY, XSETTINGS_NO_MEM, and XSETTINGS_SUCCESS.
Referenced by xsettings_manager_set_setting().
xsettings_list_lookup()
XSettingsSetting * xsettings_list_lookup (XSettingsList * list, const char * name)
Definition at line 243 of file xsettings-common.c.
References _XSettingsSetting::name, name, _XSettingsList::next, NULL, and _XSettingsList::setting.
Referenced by xsettings_manager_set_setting().
xsettings_setting_copy()
XSettingsSetting * xsettings_setting_copy (XSettingsSetting * setting)
Definition at line 33 of file xsettings-common.c.
References _XSettingsSetting::data, _XSettingsSetting::last_change_serial, memcpy, _XSettingsSetting::name, NULL, _XSettingsSetting::type, _XSettingsSetting::v_color, _XSettingsSetting::v_int, _XSettingsSetting::v_string, XSETTINGS_TYPE_COLOR, XSETTINGS_TYPE_INT, and XSETTINGS_TYPE_STRING.
Referenced by xsettings_list_copy(), and xsettings_manager_set_setting().
xsettings_setting_equal()
int xsettings_setting_equal (XSettingsSetting * setting_a, XSettingsSetting * setting_b)
Definition at line 121 of file xsettings-common.c.
References _XSettingsColor::alpha, _XSettingsColor::blue, _XSettingsSetting::data, _XSettingsColor::green, _XSettingsSetting::name, _XSettingsColor::red, _XSettingsSetting::type, _XSettingsSetting::v_color, _XSettingsSetting::v_int, _XSettingsSetting::v_string, XSETTINGS_TYPE_COLOR, XSETTINGS_TYPE_INT, and XSETTINGS_TYPE_STRING.
Referenced by xsettings_manager_set_setting().
xsettings_setting_free()
void xsettings_setting_free (XSettingsSetting * setting)
Definition at line 147 of file xsettings-common.c.
References _XSettingsSetting::data, _XSettingsSetting::name, _XSettingsSetting::type, _XSettingsSetting::v_string, and XSETTINGS_TYPE_STRING.
Referenced by xsettings_list_delete(), xsettings_list_free(), and xsettings_manager_set_setting().