MATE Desktop Environment: xstuff.c File Reference
xstuff.c File Reference
#include <config.h>
#include <string.h>
#include <unistd.h>
#include <gdk/gdk.h>
#include <gdk/gdkx.h>
#include <gtk/gtk.h>
#include <X11/Xlib.h>
#include "panel-enums.h"
#include "xstuff.h"
Macros
#define MINIATURIZE_ANIMATION_FRAMES_Z 1
#define MINIATURIZE_ANIMATION_STEPS_Z 6
#define MINIATURIZE_ANIMATION_DELAY_Z 10
#define ZOOM_FACTOR 5
#define ZOOM_STEPS 14
#define ZOOM_DELAY 10
#define FRAMES (MINIATURIZE_ANIMATION_FRAMES_Z)
Functions
gboolean is_using_x11 ()
void xstuff_zoom_animate (GtkWidget *widget, cairo_surface_t *surface, PanelOrientation orientation, GdkRectangle *opt_rect)
gboolean xstuff_is_display_dead (void)
void xstuff_init (void)
Macro Definition Documentation
FRAMES
#define FRAMES (MINIATURIZE_ANIMATION_FRAMES_Z)
MINIATURIZE_ANIMATION_DELAY_Z
#define MINIATURIZE_ANIMATION_DELAY_Z 10
Definition at line 43 of file xstuff.c.
MINIATURIZE_ANIMATION_FRAMES_Z
#define MINIATURIZE_ANIMATION_FRAMES_Z 1
Definition at line 40 of file xstuff.c.
MINIATURIZE_ANIMATION_STEPS_Z
#define MINIATURIZE_ANIMATION_STEPS_Z 6
Definition at line 41 of file xstuff.c.
Referenced by xstuff_zoom_animate().
ZOOM_DELAY
#define ZOOM_DELAY 10
Definition at line 48 of file xstuff.c.
ZOOM_FACTOR
#define ZOOM_FACTOR 5
Definition at line 46 of file xstuff.c.
ZOOM_STEPS
#define ZOOM_STEPS 14
Definition at line 47 of file xstuff.c.
Function Documentation
is_using_x11()
gboolean is_using_x11 (void)
Definition at line 50 of file xstuff.c.
References GDK_IS_X11_DISPLAY.
Referenced by _mate_panel_applet_frame_applet_broken(), panel_bindings_get_mouse_button_modifier_keymask(), and panel_session_init().
xstuff_init()
void xstuff_init (void)
Definition at line 425 of file xstuff.c.
Referenced by main().
xstuff_is_display_dead()
gboolean xstuff_is_display_dead (void)
Definition at line 402 of file xstuff.c.
Referenced by _mate_panel_applet_frame_applet_broken().
xstuff_zoom_animate()
void xstuff_zoom_animate (GtkWidget * widget, cairo_surface_t * surface, PanelOrientation orientation, GdkRectangle * opt_rect)
Definition at line 343 of file xstuff.c.
References dest, and MINIATURIZE_ANIMATION_STEPS_Z.